### ISSUE TITLE
[Feature Request] hopes that the table column can be dragged freely

### ISSUE THREAD

**Issue by xiaofengleiyu** [ElemeFE/element#10000]
### Existing Component
否

### Component Name
表格列拖拽

### Description
希望表格列可以实现自由拖拽。目前有些需求是要求要能根据实际需要自由拖拽，但是现在的表格无法满足

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/drobh9a9/1/

![untitled1](https://user-images.githubusercontent.com/10095631/36966983-7129d988-2099-11e8-883a-1b486c934d6c.gif)
