### ISSUE TITLE
[Bug Report] [checkbox] when I use Firefox and press on 'shift' key, I can't choose checkbox 

### ISSUE THREAD

**Issue by ruiyong-lee** [ElemeFE/element#10007]
### Element UI version
2.2.1

### OS/Browsers version
windows10 / Firefox

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/7o1duso6/1/](https://jsfiddle.net/7o1duso6/1/)

### Steps to reproduce
when I use Firefox and press on 'shift' key, I can't choose checkbox. but Chrome can

### What is Expected?
Firefox  can

### What is actually happening?
Firefox can't

**Comment by Leopoldthecoder** [comment]
请详细描述操作步骤。

**Comment by ruiyong-lee** [comment]
使用火狐浏览器，按住shift键无法选择checkbox，谷歌浏览器可以，我们项目是为了实现按住shift可以连选两个勾选框中间所有的勾选框，就像windows选择文件一样的操作方式

**Comment by Leopoldthecoder** [comment]
看上去是 FireFox 的问题，即使是原生的 checkbox，在 FireFox 中按住 shift 也无法选中，而在 Chrome 里是可以的：https://jsfiddle.net/7o1duso6/6/

**Comment by qingqiuerpan** [comment]
> 使用火狐浏览器，按住移位键无法选择复选框，谷歌浏览器可以，我们项目是为了实现按住移位可以连选两个勾选框中间所有的勾选框，就像窗口选择文件一样的操作方式

请问有解决方法吗？

**Comment by LwcReber** [comment]
重置Checkbox组件中input的样式即可，不过仅是支持框内点击选中，对于label文字的点击暂时无效果
```
.el-checkbox__input {
  .el-checkbox__original {
    width: 14px;
    height: 14px;
    z-index: 1;
    left: 0;
    cursor: pointer;
  }
}
```
