### ISSUE TITLE
[Feature Request] date range selection for automatic time range

### ISSUE THREAD

**Issue by yiwuyu** [ElemeFE/element#10001]
### Existing Component
是

### Component Name
datePicker

### Description
当选择日期范围的时候，点击一个时间不需要强制性绑定为开始时间，希望能支持反向选择时间，比如 先勾选 3月5日，再勾选3月1日，就能直接获取到 0301-0305，而不需要重新点开始时间

**Comment by wacky6** [comment]
https://github.com/ElemeFE/element/pull/8156

**Comment by yiwuyu** [comment]
good job!
