### ISSUE TITLE
[Bug Report] remotely searches for select components, which will open the page after getting the data, resulting in a scroll bar

### ISSUE THREAD

**Issue by lky5230** [ElemeFE/element#10015]
### Element UI version
2.2.1

### OS/Browsers version
win32/chrome v64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/bububu123321/8g00yr3w/3/](https://jsfiddle.net/bububu123321/8g00yr3w/3/)

### Steps to reproduce
1、点击搜索框，等待远程数据获取
2、得到数据后，会撑开页面出现滚动条

### What is Expected?
不出现滚动条

### What is actually happening?
出现了滚动条！
如图就比较严重：
本来底部没有滚动条，撑开后出现滚动条，比较丑。。。
![qq 20180305200506](https://user-images.githubusercontent.com/21300963/36974157-98f65b5a-20b0-11e8-990f-c24e8790c677.png)

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
