### ISSUE TITLE
[Feature Request] select multiple collapse-tags function is not effective

### ISSUE THREAD

**Issue by dinglittle** [ElemeFE/element#10010]
### Existing Component
Yes

### Component Name
2.0.4

### Description
chrome  63.0.3239.108

在如上 chrome 版本下 , select multiple collapse-tags 功能不生效
```
<el-select v-model="riskSection" multiple collapse-tags  placeholder="请选择">
            <el-option 
                v-for="item in riskSections" 
                :key="item.enumCode" 
                :label="item.showMsg" 
                :value="item.showMsg">
            </el-option>
</el-select>
```

**实现 : 如下图**
![image](https://user-images.githubusercontent.com/17232138/36970812-c3d6ff16-20a4-11e8-84f1-f096ec72e908.png)

**期待:**
![image](https://user-images.githubusercontent.com/17232138/36970919-2253d046-20a5-11e8-99d8-ee27fcb3cd36.png)

**Comment by wacky6** [comment]
collapse-tags 这个选项 2.0.5 以后才有，请参考 changelog

**Comment by dinglittle** [comment]
另一个问题  , 同上环境 , 我将 element-ui 升级到  2.2.1 , 当某个选项 过长时 无法自动 填充 select width , 如图 :
![image](https://user-images.githubusercontent.com/17232138/37011177-e79656f6-2129-11e8-96a7-563d977d670e.png)

**Comment by wacky6** [comment]
新开个issue吧，把demo贴上来。
