### ISSUE TITLE
[Feature Request] Adobe XD CC Components Template

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [ElemeFE/element#10011]
### Existing Component
No

### Component Name
All

### Description
Please, add an Adobe XD CC Template to the website [resources section](http://element.eleme.io/#/en-US/resource) so Windows users could benefit as well.

**Comment by Leopoldthecoder** [comment]
I talked to our designers, and we'll add some PhotoShop templates (`.psd`) for the Windows users.

**Comment by AndrewBogdanovTSS** [comment]
@Leopoldthecoder why not add both? More and more users start using Adobe XD as a prime design tool that is specific to a purpose of web UX

**Comment by Leopoldthecoder** [comment]
I was told very few designers in China use Adobe XD, and our designers don't have access to it.

**Comment by mrinc** [comment]
Just letting anyone that comes across this that Adobe XD can now open .sketch files.

**Comment by AndrewBogdanovTSS** [comment]
@mrinc is it also a valid statement for Windows version?

**Comment by mrinc** [comment]
@AndrewBogdanovTSS - I opened the .sketch file on my Windows PC using AdobeXD - so yes 💯
