### ISSUE TITLE
[Feature Request] Can you provide a Tree Data Table similar to Ant.Design?

### ISSUE THREAD

**Issue by StingGao** [ElemeFE/element#10017]
### Existing Component
是

### Component Name
table

### Description
Like this. https://github.com/ant-design/ant-design/blob/master/components/table/demo/expand-children.md

**Comment by spiritree** [comment]
Here is a tree table based on element.
https://github.com/PanJiaChen/vue-element-admin/tree/master/src/components/TreeTable

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this any time soon. Please consider the suggestion @spiritree gave.

**Comment by lxmbetterman** [comment]
I also hope that the official can provide 'treeTable', each layer of data can be folded or expanded in the table, the current tree component is not suitable for displaying too many data occasions

**Comment by vuchan** [comment]
@lxmbetterman Same requirements. i ever written a tree-table use `el-table` component, but i found one thing is `el-table-column` has no any custom render method with row-header cell, it means i cannot show diff header type between `select` and `expand` in one [column](http://element-cn.eleme.io/#/zh-CN/component/table#table-column-attributes). little funny !!!

**Comment by KevinPan** [comment]
I want this, please add this function
