### ISSUE TITLE
[Feature Request] List Component

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [ElemeFE/element#10012]
### Existing Component
No

### Component Name
List

### Description
Could you add component that would allow us to structure/stylize lists of data, similarly how it's implemented in other component libraries ([example1](http://tachyons.io/components/lists/border-spaced/index.html), [example2](http://tachyons.io/components/lists/follower-notifications/index.html)). That way ElementUI would allow creating simple lists as well as nesting existing components such as Card into a list.

**Comment by kaungmyatlwin** [comment]
Isn't it better to use `v-for` directive and style it to your needs rather than creating a new component?

**Comment by AndrewBogdanovTSS** [comment]
Yeah, using v-for is also an option. Maybe a list of classes that stylize lists can be added to speed up development?

**Comment by kaungmyatlwin** [comment]
http://element.eleme.io/#/en-US/component/card

Simple card is what you might be looking for.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
