### ISSUE TITLE
[Bug Report]loading button will be triggered by key pressing

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#10018]
### Element UI version
2.2.1

### OS/Browsers version
all

### Vue version
2.5.13

### Reproduction Link
https://jsfiddle.net/888xe3qt/

### Steps to reproduce
1. make the button get focused 
2. hit enter repeatly
3. callback will be triggered every time you hit the button even if it's in `loading` state

### What is Expected?
it should totally be disabled when in `loading` state

**Comment by wacky6** [comment]
@Leopoldthecoder Should `loading` imply `disabled`? Not sure what the design was.

**Comment by wacky6** [comment]
After patch: https://jsfiddle.net/888xe3qt/3/
