### ISSUE TITLE
[Bug Report] el-date-picker控件中文日期时间格式，日期选取输入框显示格式不正确

### ISSUE THREAD

**Issue by icyxing** [ElemeFE/element#10030]
Element UI version
2.2.1

OS/Browsers version
Windows 10 / Chrome 64.0.3282.186

Vue version
2.5.13

Reproduction Link
[jsfiddle](https://jsfiddle.net/t7zypsgs/)

Steps to reproduce
1.  el-date-picker 属性设置 type="datetime" format="yyyy年MM月dd日 HH:mm:ss"
2. 选择一个时间戳
3. 点击el-date-picker打开选择面板，尝试更新选择时间戳

What is Expected?
面板上方日期输入框显示“2018年03月14日”

What is actually happening?
面板上方日期输入框显示“2018年03月14”

**Comment by liuyingqq123** [comment]
问题还不解决呢
