### ISSUE TITLE
[Bug Report] element-2.2.x.zip source code is compiled and packaged dist after Windows10/Mac. The final index.css and index.js are used to make simple demo according to official website code, and el-pagination component is rendered and reported wrong.

### ISSUE THREAD

**Issue by penggle** [ElemeFE/element#10033]
### Element UI version
2.2.0

### OS/Browsers version
Windows10，Mac

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/418/](https://jsfiddle.net/mmx38qxw/418/)

### Steps to reproduce
element-2.2.x.zip源码在windows10下编译打包，nodejs，npm都是最新稳定版，执行npm install和npm run dist，在无任何错误并且dist成功的情况下，取其lib下的index.js，index.css，fonts等按照官网做简单demo，其中el-pagination组件渲染报错：TypeError: t.children is undefined。少量修改定制element-ui对于一些公司或团队来说是很有必要的，非常关切这个问题！！！
以下是我对element-2.2.x.zip中文件的修改及执行步骤：
1、element-2.2.x\packages\theme-chalk\src\common\var.scss 中修改了primary的颜色值
2、element-2.2.x\.eslintignore文件中加入一行： packages/theme-chalk/src/fonts/*
然后执行 npm install
               npm run dist

### What is Expected?
因为少量修改定制element-ui对于一些公司或团队来说是很有必要的，非常关切这个问题！！！期待给出我本地dist打包后的代码出现上述问题的根源。

### What is actually happening?
取本地dist后的index.js，index.css做简单demo，其中el-pagination组件渲染报错：TypeError: t.children is undefined。

**Comment by penggle** [comment]
我在好几个同事的机器(Windows10，Mac)上，都出现上述问题，救命啊。。。

**Comment by Leopoldthecoder** [comment]
删掉 `node_modules`，改用 `yarn` 安装依赖试试。

**Comment by merjiezo** [comment]
用npm安装最新依赖的时候报的问题，老依赖不存在，看情况是用JSX动态创建VNode的时候children为undefined，之前不存在这个问题，Element可以试着尝试以下方法解决：
if (undefined === template.children) {
  template.children = []
}

**Comment by Leopoldthecoder** [comment]
Resolved in https://github.com/ElemeFE/element/commit/b3062de0d2b8c0b4f89ab44767ca86ef702ce7ee

**Comment by penggle** [comment]
@merjiezo 我就是这么干的，修改了Element的pagination.js中的源码的，加入了
if (undefined === template.children) {
template.children = []
} 这段代码才好的。^_^

**Comment by merjiezo** [comment]
@penggle Element修复了，用他的解决方案升级一下即可，这个依赖库的非兼容性更新还蛮难发现的，因为安装老依赖的环境是不会有这个问题的😄
