### ISSUE TITLE
[Bug Report] el-tooltip Invalid prop: type check failed for prop "openDelay".

### ISSUE THREAD

**Issue by shiny** [ElemeFE/element#10032]
### Element UI version
2.2.1

### OS/Browsers version
OS X Chrome 64.0.3282.186

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/415/](https://jsfiddle.net/mmx38qxw/415/)

### Steps to reproduce
打开开发者工具，提示

vue.js:584 [Vue warn]: Invalid prop: type check failed for prop "openDelay". Expected Number, got String.

found in

---> <ElTooltip>
       <Root>

### What is Expected?
无任何 Vue warn 

### What is actually happening?
vue.js:584 [Vue warn]: Invalid prop: type check failed for prop "openDelay". Expected Number, got String.

found in

---> <ElTooltip>
       <Root>

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/420/
