### ISSUE TITLE
Table 的多选Checkbox，在加载数据时如何实现选择制定行？

### ISSUE THREAD

**Issue by miaosun009** [ElemeFE/element#1003]
Table 的多选Checkbox，在加载数据时如何实现选中指定行？
 没有相应的api获取所有行，也没有相应的事件在数据加载时去操作， 望解答。

**Comment by furybean** [comment]
Table 有提供 toggleRowSelection，有两个参数：row, selected。如果不提供第二个参数，则是 toggle 操作，如果提供，则是设置为 『选中』 或者 『非选中』 操作。

**Comment by miaosun009** [comment]
` watch: {
           groupData:function (a) {
                for(var i in a){
                    this.$refs.groupTable.toggleRowSelection(a[i],true)
                }
        },`

这是我的测试例子
我在监听数据变化的时候，让他全部选择，但是没有效果， toggleRowSelection 的row参数，是一个特殊对象，还是只要给groupData某一条数据即可？

**Comment by furybean** [comment]
@miaosun009 我试了一下，可以全选：http://jsfiddle.net/chxtbh1h/

**Comment by miaosun009** [comment]
首先非常感谢您的例子， 通过按钮点击的事件去选择是可以选的，但是我的需求是，在数据加载的过程中，我需要动态的指定某条数据选中状态， 这样好像不行，我是在watch里面监听数据变化的时候用你说的方法，是不行的。

**Comment by furybean** [comment]
@miaosun009 加个 this.$nextTick 试试？data 在变化后会清空一次 selection。

**Comment by miaosun009** [comment]
非常感谢，已经解决了我的问题。

**Comment by wlx200510** [comment]
@miaosun009  您好  我也遇到了类似问题  但加上 this.$nextTick仍然不管用，您当时具体的代码能借鉴下吗？

**Comment by lal55** [comment]
@miaosun009 你好 ,现在刚用ele...  也遇到了这个问题 ,  请问怎么解决的

**Comment by stefli** [comment]
// 定义ref
<el-table ref="table" .../>
 
// 设置选中状态
axios.post('/api/xxx').then((response) => {
  this.entry = response.data.items;
   
  // 以下为重点代码
  this.$nextTick(() => {
    this.entry.map((row, index) => {
      if (index % 2 == 0) {
        this.$refs.table.toggleRowSelection(row, true);
      }
    });
  });
}, (err) => {
  console.log(err)
});

**Comment by caolaichao** [comment]
<template>
	<div class="">
		<el-button @click="setDefaultSelectedRows">设置初始值</el-button>
		<el-table ref="selectUserTable" :data="tableData" row-key="id" height="calc(100% - 90px)" @selection-change="handleSelectionChange">
			<el-table-column reserve-selection type="selection" width="55" align="center" />
			<el-table-column prop="date" label="序号" width="80"> </el-table-column>
			<el-table-column prop="deptName" label="所属单位" width="180"> </el-table-column>
			<el-table-column prop="nickname" label="姓名"> </el-table-column>
			<el-table-column prop="mobile" label="手机号码"> </el-table-column>
		</el-table>
	</div>
</template>

<script>
export default {
	data() {
		return {
			tableData: []
		}
	},
	mounted(){
		this.loadData()
	},
	methods: {
		setDefaultSelectedRows() {
			let rows = [...Array(2 || 0).keys()].map((v, i) => ({
				deptName: '单位',
				nickname: `李四${i}`,
				mobile: '18322222222',
				id: `id+${i}`
			}))
			this.$nextTick(() => {
				rows.forEach(row => {
					this.$refs.selectUserTable.toggleRowSelection(row, true)
				})
			})
		},
		loadData() {
			this.tableData = [...Array(2 || 0).keys()].map((v, i) => ({
				deptName: '单位',
				nickname: `李四${i}`,
				mobile: '18322222222',
				id: `id+${i}`
			}))
		},
		handleSelectionChange(e) {
			console.log('选中',e)
		}
	}
}
</script>

<style></style>
我这边动态获取拿到选中数据，然后进行设置不生效

**Comment by caolaichao** [comment]
![Uploading 企业微信截图_1710324144318.png…]()
