### ISSUE TITLE
[Bug Report] DatePicker of type year failed when the value is integer and not string (

### ISSUE THREAD

**Issue by rodrigore** [ElemeFE/element#10040]
### Element UI version
2.2.1

### OS/Browsers version
Mac OS, Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/pysdxq05/6/](https://jsfiddle.net/pysdxq05/6/)

### Steps to reproduce
Hi, the use case of this is that I store the year inside a integer column on the database. So If I return from the api the year as integer the datepicker with the value-format 'yyyy' it fail.

In order to fix this, I need to cast the year to string from the server side.

Here is the valid example https://jsfiddle.net/pysdxq05/5/ where the value is a string.

### What is Expected?
Datepicker display the year

### What is actually happening?
An exception is throwing and the datepicker fail

**Comment by wacky6** [comment]
Sorry, the value must be a string. This is to keep consistent with other value-formats.
