### ISSUE TITLE
[Feature Request] adds a scroll bar positioning function to the setCurrentRow of the el-table component

### ISSUE THREAD

**Issue by blueroseslol** [ElemeFE/element#10041]
### Existing Component
是

### Component Name
el-table

### Description
setCurrentRow我认为应该需要提供滚动条定位的功能，或者提供当前row的所在高度也可以。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/tk37c5cb/14/

**Comment by liuyingqq123** [comment]
can not open the address https://jsfiddle.net/tk37c5cb/14/. can you paste the code at this. thank you very much!
