### ISSUE TITLE
[Bug Report] Slow to hide the <el-menu>

### ISSUE THREAD

**Issue by rhk10** [ElemeFE/element#10049]
### Element UI version
2.2.1

### OS/Browsers version
macOS High Sierra / Google Chrome 64.0.3282.186

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/yustnghk/](https://jsfiddle.net/yustnghk/)

### Steps to reproduce
Click 'hide!' button to hide el-menu

### What is Expected?
el-menu and el-menu-items are hidden immediately with v-if directive.

### What is actually happening?
Menu items remain until after a second.

**Comment by Leopoldthecoder** [comment]
Toggling `v-if` directly on the `<el-menu>` element triggers transition intended for collapse effects. So either move the `v-if` to `<el-menu>`'s parent element or add a CSS rule to remove the transition: https://jsfiddle.net/yustnghk/9/ .
