### ISSUE TITLE
<el-input>控件无法监听keyup.enter事件

### ISSUE THREAD

**Issue by LittleStupid** [ElemeFE/element#1004]
我希望完成这样的场景: 假设一个搜索input框,我在input里面输入文字，输入完后直接按回车，就可以显示出搜索结果。
类似 <input @keyup.enter="search">。

然而,
<el-input icon="search" v-model="keyWord"  @keyup.enter="search">
</el-input>   这里我按了回车，keyup.enter没有被侦测到。

**Comment by Leopoldthecoder** [comment]
请阅读 FAQ：https://github.com/ElemeFE/element/blob/master/FAQ.md
