### ISSUE TITLE
el-dialog里定义百度地图报错问题

### ISSUE THREAD

**Issue by Lmangoxx** [ElemeFE/element#10058]
<el-dialog title="位置选择" width="80%" :visible.sync="addressStatus">
        <div id="allmap"></div>
</el-dialog>

mounted () {
        this.$nextTick(() => {
                var map = new BMap.Map('allmap')    // 创建Map实例
        })
}

TypeError: Cannot read property 'gc' of undefined
百度地图找不到id=“allmap”的标签，如果把标签放到el-dialog外面，可以正常显示

**Comment by warmilk** [comment]
同问
