### ISSUE TITLE
[Bug Report] table组件能否在 el-table 上设置 align="center"  所有el-table-column均居中，如果el-table-column设置align，则渲染自定义align

### ISSUE THREAD

**Issue by kuangyazhou** [ElemeFE/element#10051]
### Element UI version
2.2.1

### OS/Browsers version
win10/chrome61

### Vue version
2.5.13

### Reproduction Link
[github.com/kuangyazhou/BTC](github.com/kuangyazhou/BTC)

### Steps to reproduce
<el-table :data="wareData" :border="false" size="mini" style="width: 100%">
            <el-table-column prop="productName" align="center" label="商品名称"></el-table-column>
            <el-table-column prop="productName" align="center" label="显示权限"></el-table-column>
            <el-table-column prop="productName" align="center" label="建仓">

### What is Expected?
在table上定义aling属性，column继承

### What is actually happening?
只由column自定义

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
