### ISSUE TITLE
date-picker :clearable="false" not work with type="datetimerange"

### ISSUE THREAD

**Issue by Ttdnts** [ElemeFE/element#10056]
### Element UI version
2.2.1

### OS/Browsers version
win10 google & firefox

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/426/](https://jsfiddle.net/mmx38qxw/426/)

### Steps to reproduce
1.use el-date-picker
2.set type as datetimerange
3.set clearable as false

### What is Expected?
the clear button appeared and clickable

### What is actually happening?
this clear button should not appear

**Comment by furybean** [comment]
If you add a clearable prop for an element, the clearable value will be true. If you want to set this prop as false, you should add `:clearable="false"` for the component.

Update example here: https://jsfiddle.net/mmx38qxw/476/

**Comment by Ttdnts** [comment]
@furybean im using :clearable="false" certainly

sorry for the code was wrong, however the issue can be reproduced

i just updated the code, and u can see in
https://jsfiddle.net/mmx38qxw/489/

**Comment by Leopoldthecoder** [comment]
- `:clearable="false"` means there is no clear button
- `:clearable="true"` means there is clear button

Your demo behaves correctly.

**Comment by Ttdnts** [comment]
try this plz
https://jsfiddle.net/ng347h9m/1/

**Comment by Leopoldthecoder** [comment]
By "clear button", we mean this one:
![image](https://user-images.githubusercontent.com/10095631/37187855-450918d2-2387-11e8-955e-b3b7782f8a8c.png)

**Comment by vinayakkulkarni** [comment]
You can hide the `Clear` button by using the below css snippet. it's a hack though 😞 
```css
<style scoped>
button.el-button.el-picker-panel__link-btn.el-button--text.el-button--mini {
  display: none;
}
</style>
```

**Comment by 3lement3** [comment]
How to catch or how name is event when  happens click  'clear button'?

**Comment by Samaev** [comment]
@3lement3 <date-picker @clear="catchClearEffect" />
const catchClearEffect = () => {
    console.log('It worked for me in Nuxt3")
}

hope it is not too late)
