### ISSUE TITLE
There is no getHalfCheckedNodes and getHalfCheckedKeys in the [Bug Report] Tree component

### ISSUE THREAD

**Issue by loveboom** [ElemeFE/element#10055]
### Element UI version
2.2.1

### OS/Browsers version
dsad

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element/issues/10054](https://github.com/ElemeFE/element/issues/10054)

### Steps to reproduce
Tree组件中getHalfCheckedNodes和getHalfCheckedKeys是没有的

### What is Expected?
Tree组件中getHalfCheckedNodes和getHalfCheckedKeys是没有的

### What is actually happening?
this.$refs.tree.getHalfCheckedNodes()会报错 ，is not  a function  ，打印了一下tree ，根本没有这个方法

**Comment by Leopoldthecoder** [comment]
这两个方法在 2.2.0 版本中加入，看下项目中的版本对不对。
