### ISSUE TITLE
[Bug Report] El-select placeholder text is not reactive, doesn't re-translate

### ISSUE THREAD

**Issue by kevrousso** [ElemeFE/element#10063]
### Element UI version
2.2.1

### OS/Browsers version
all

### Vue version
2.5.13

### Reproduction Link
[https://codepen.io/kevrousso/pen/oEarxM](https://codepen.io/kevrousso/pen/oEarxM)

### Steps to reproduce
When the app boot up, the locale is set, but whenever you change it dynamically the placeholder for the Select doesn't reflect the correct locale.

However, the DatePicker is picking it up but I assume it's because it's being refreshed on click.

### What is Expected?
The locale of the placeholder for the select is reflected when changing the locale dynamically.

### What is actually happening?
The locale of the placeholder for the select is not reflected when changing the locale dynamically.

**Comment by Leopoldthecoder** [comment]
Currently all i18n texts are not responsive. For the DatePicker, you're right that it's being refreshed on click.

So I'm afraid you'll have to manually set the `placeholder` prop each time the locale is updated.
