### ISSUE TITLE
[Bug Report]select El-option label values are overlaid out of el-select, and the layout is abnormal when the content is too large

### ISSUE THREAD

**Issue by dinglittle** [ElemeFE/element#10065]
### Element UI version
2.2.1

### OS/Browsers version
64.0.3282.186（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/dinglittle/pen/xWKYBP](https://codepen.io/dinglittle/pen/xWKYBP)

### Steps to reproduce
el-select 当选择, option label值过长时, 超过 el-select 大小

### What is Expected?
自动撑大 el-select 

### What is actually happening?
el-option label 值覆盖在 el-select 外, 内容过大时  布局异常

**Comment by Leopoldthecoder** [comment]
Select doesn't have the ability to extend its width dynamically. See https://github.com/ElemeFE/element/issues/9352 .
