### ISSUE TITLE
[Bug Report] The initial type of el-input makes different height

### ISSUE THREAD

**Issue by HADB** [ElemeFE/element#10061]
### Element UI version
2.2.0

### OS/Browsers version
macOS High Sierra 10.13.3 / Chrome 64.0.3282.186

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/460/](https://jsfiddle.net/mmx38qxw/460/)

### Steps to reproduce
el-form中多个el-input的v-model的初始值设置number和string两种类型，会发现排列出现错乱，两种类型的高度不一样

### What is Expected?
高度一致，排列不错乱

### What is actually happening?
高度不一致，排列出现错乱

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/463/ . You have to wrap each row in one `<el-row>`.

**Comment by HADB** [comment]
This small different in height may cause some other bugs. Mine is just an example to show that.

**Comment by HADB** [comment]
Also, wrap several rows in one `el-row` is usable because `el-col` is float. And there's a "column wrapping" since bootstrap. This bug is caused by the different height of input not wrapping multiple row in one `el-row`. I think your answer was thoughtlessly.

**Comment by Leopoldthecoder** [comment]
It seems this only happens in Chrome. In https://github.com/ElemeFE/element/pull/10064 the `line-height` for input element is explicitly declared in `px` instead of the original `1`, which works for me.
