### ISSUE TITLE
Table事件selection-change的参数在表格数据更新时未清空。

### ISSUE THREAD

**Issue by yu1234dong** [ElemeFE/element#1006]
我用的vue-resource的$http更新表格数据，在有表格行被选中的情况下，更新数据会使checkbox框的勾消失，可再次选中，但是回调函数的参数值会多出几项。
目前自己用的解决办法是Table的clearSelection方法清空，但是似乎因为过渡效果的原因。不能马上生效。我是给后续操作加上延时解决。不知道有没有其他的解决方法？

**Comment by furybean** [comment]
没看懂你是打算保留选择，还是不打算保留选择。如果希望保留选项，使用 reserve-selection 即可。

如果还是没能解决你的问题的话，请提供版本以及可重现用例。

**Comment by yu1234dong** [comment]
之前的版本是rc.8。升级到1.0.0就没有这个问题了。感谢！
