### ISSUE TITLE
The [Bug Report] Dropdown cannot terminate the click event delivery when it is at trigger='click'.

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#10066]
### Element UI version
2.2.0

### OS/Browsers version
win 10/chrome 64.0.3282.186

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/dxq4n47z/10/](https://jsfiddle.net/dxq4n47z/10/)

### Steps to reproduce
使用Collapse组件时自定义title,在title中嵌入Dropdown组件并设置trigger='click'，但是Dropdown中没有终止click事件传递相关Attributes或者抛出click并让我手动触发Dropdown展开的event。

### What is Expected?
使用Collapse组件时自定义title,在title中嵌入Dropdown组件并设置trigger='click'，在点击Dropdown组件时，只有Dropdown组件展开，Collapse组件不会展开。

### What is actually happening?
使用Collapse组件时自定义title,在title中嵌入Dropdown组件并设置trigger='click'，在点击Dropdown组件时，同时展开，没有达到我想要的效果。

**Comment by Leopoldthecoder** [comment]
You can add `@click.native.stop`: https://jsfiddle.net/dxq4n47z/16/
