### ISSUE TITLE
Two hook functions of before-upload and on-remove in [Bug Report] el-upload are executed at the same time

### ISSUE THREAD

**Issue by feng9217** [ElemeFE/element#10060]
### Element UI version
2.2.1

### OS/Browsers version
WIN10

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/434/](https://jsfiddle.net/mmx38qxw/434/)

### Steps to reproduce
在添加的时候 就连删除的操作一起执行了

### What is Expected?
按钩子的周期执行

### What is actually happening?
同时执行

**Comment by Leopoldthecoder** [comment]
可以通过一个 flag 来解决：https://jsfiddle.net/mmx38qxw/439/
