### ISSUE TITLE
[Bug Report] default-time attribute only works with date range picker, not date picker

### ISSUE THREAD

**Issue by dak** [ElemeFE/element#10078]
### Element UI version
2.2.1

### OS/Browsers version
All browsers

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/535/](https://jsfiddle.net/mmx38qxw/535/)

### Steps to reproduce
1. Create a datetime picker with the default-time attribute
2. Choose a date
3. The time will be set by default to the current time, rather than the default-time

### What is Expected?
The default-time attribute should work with datetime picker the same way it works with datetimerange picker. When selecting a date, the time should be set to the value defined by the default-time attribute.

### What is actually happening?
The time is being set by default to the current time on the datetime picker.

**Comment by Leopoldthecoder** [comment]
This not a bug. `default-time` only works in range mode.

@wacky6 Do you think we can get it to work in non-range mode?

**Comment by wacky6** [comment]
Sounds ok to me. Should not be a huge problem.

I'd say PR welcome for this issue. I'm too busy recently to implement this myself.

**Comment by Leopoldthecoder** [comment]
@wacky6 Got it.

**Comment by gnijuohz** [comment]
@Leopoldthecoder I would like to work on this issue if no one is currently working on it :)

**Comment by wacky6** [comment]
@gnijuohz Thanks for contribution. Just remember to write tests and update the documentation.

**Comment by Leopoldthecoder** [comment]
Resolved in https://github.com/ElemeFE/element/pull/10321 .
