### ISSUE TITLE
[Bug Report] Vue elementUI select [bug] multiselect drop-down box group (http://jsrun.net/bRqKp/edit)

### ISSUE THREAD

**Issue by vicoolee** [ElemeFE/element#10075]
### Element UI version
2.0.10

### OS/Browsers version
Google Chrome 版本 63.0.3239.108（正式版本） （32 位）

### Vue version
2.5.11

### Reproduction Link
[jsfiddle见标题](jsfiddle见标题)

### Steps to reproduce
版本 问题；1.4.5无此问题；2.0以上存在该问题

### What is Expected?
http://jsrun.net/bRqKp/edit  求解决方法

### What is actually happening?
http://jsrun.net/bRqKp/edit 打开链接；切换注释版本可复现问题

**Comment by Leopoldthecoder** [comment]
请描述 bug 内容。

**Comment by vicoolee** [comment]
select下拉框 多选 分组 同时使用时，
option很多的时候，下拉框内出现滚动条

存在# 【**## 点击选项option后 下拉框内的滚动条自动回到顶部**】.
