### ISSUE TITLE
The formateer method of the [Bug Report] table component can not reformat the data after the server data is obtained with async/await?

### ISSUE THREAD

**Issue by rianran1993** [ElemeFE/element#10072]
### Element UI version
2.2.1

### OS/Browsers version
mac

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
无

### What is Expected?
等获取到数据后 再 返回对应数据

### What is actually happening?
直接 返回成undefined

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by rianran1993** [comment]
@Leopoldthecoder  https://jsfiddle.net/mmx38qxw/510/
