### ISSUE TITLE
[Feature Request] Row height fix

### ISSUE THREAD

**Issue by jjh30331** [ElemeFE/element#10071]
### Existing Component
Yes

### Component Name
Table

### Description
I can not find attribute related with fix row height
please let me know If it is available

**Comment by Leopoldthecoder** [comment]
There's no such attribute. What's your use case?

**Comment by jjh30331** [comment]
It's just simple.
I'm making Project Management web-app.
then some of projects have long content.
In this case,  the row height is fitted to the longest column height

**Comment by Leopoldthecoder** [comment]
You mean like this https://jsfiddle.net/gs7uos75/ ?

What do you expect the table to look like in this case?

**Comment by jjh30331** [comment]
That is same case. Thanks.
I want to just fix every row's height what ever there is overflowed content.
Will it be possible?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gs7uos75/3/

**Comment by jjh30331** [comment]
Thanks. 
Hope you have a good one
