### ISSUE TITLE
element-ui 1.0.0 el-table-column 添加 inline-template 后报错

### ISSUE THREAD

**Issue by oldway520** [ElemeFE/element#1007]
![image](https://cloud.githubusercontent.com/assets/3321193/20236616/c7979d4a-a8f5-11e6-9c57-efe43bda663a.png)

### 代码是拿官方文档的例子
![image](https://cloud.githubusercontent.com/assets/3321193/20236653/66e2061a-a8f6-11e6-9c38-2e919f5ee621.png)

**Comment by QingWei-Li** [comment]
vue-loader 今早上改了代码逻辑把 with 去掉了，目前 Table 的自定义模板对之前的特性依赖比较深，下版本会修复这个问题

**Comment by QingWei-Li** [comment]
建议目前先将 vue-template-es2015-compiler 锁定为 1.0.0 的版本
