### ISSUE TITLE
[Feature Request] Support slot for fully customized loading

### ISSUE THREAD

**Issue by paulpdaniels** [ElemeFE/element#10085]
### Existing Component
Yes

### Component Name
Loading

### Description
The loading component has some flexibility around what gets inserted into it. But currently there is no way to insert a custom svg into it. It appears that the logic [here](https://github.com/ElemeFE/element/blob/dev/packages/loading/src/loading.vue#L8) could be wrapped in a default `slot` tag so that it could be fully customized by the end user. I'm happy to open a PR to that effect if there are no objections.

**Comment by Leopoldthecoder** [comment]
PR welcome. There's something we need to decide, though. Loading now can be used as a directive or a service, how do you propose to pass a slot into it?

```html
<div v-loading="loading">
  ...
</div>
```

```js
this.$loading({ ... })
```

**Comment by Leopoldthecoder** [comment]
Close for no interactivity.
