### ISSUE TITLE
How to remove arrow inside el-collapse-item?

### ISSUE THREAD

**Issue by konti-dylan** [ElemeFE/element#10088]
### Existing Component
Yes

### Component Name
Collapse

### Description
Hi,

i love the collapse accordion component. However, i'd like to add my own custom buttons that will trigger the opening and closing of the Accordion.

For example: title    ...Button (at far right)

Is this currently customisable?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/dxq4n47z/17/

**Comment by konti-dylan** [comment]
Hi Leo,

Thanks for the demo but can i only trigger the collapse (opening/closing) by the Custom Button?

**Comment by Leopoldthecoder** [comment]
I'm afraid not.

**Comment by konti-dylan** [comment]
Noted. Maybe this can be a "Feature request"?

Thank you !
