### ISSUE TITLE
[Bug Report] time selection control, when used in Table, select box suspension location error

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#10087]
### Element UI version
2.2.1

### OS/Browsers version
Win10/Chrome64.0.32

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mtkn9oj9/](https://jsfiddle.net/mtkn9oj9/)

### Steps to reproduce
在Table中使用el-date-picker

### What is Expected?
el-date-picker 时间选择悬浮框能正确显示。

### What is actually happening?
悬浮框全部对准在第一个框下。

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/37241622-0f2b467a-2497-11e8-9e0b-9385bf3cb802.gif)

未能重现。你的问题可能是视口高度不够，所以下拉框会自动上移，直到能在视口中完整显示。这是设计中的。

**Comment by yinjunonly** [comment]
@Leopoldthecoder 谢谢，确实是这个问题，没有意识到，多谢帮助。
