### ISSUE TITLE
[Bug Report] Element UI Input's `minlength` not work

### ISSUE THREAD

**Issue by sheldonzf** [ElemeFE/element#10082]
### Element UI version
2.2.1

### OS/Browsers version
mac

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/vbs4s7qy/1/](https://jsfiddle.net/vbs4s7qy/1/)

### Steps to reproduce
1. delete input's word one by one

### What is Expected?
input's minlength should be 3

### What is actually happening?
input's value can be empty

**Comment by Leopoldthecoder** [comment]
It should be a **number**, not a string: https://jsfiddle.net/vbs4s7qy/5/ . Plus, `minlength` doesn't mean the value cannot be empty: https://jsfiddle.net/vbs4s7qy/6/ .

**Comment by sheldonzf** [comment]
```
minlength | 最小输入长度 | number

```
if `minlength` doesn't mean the value cannot be empty，what is the prop's effect ?

**Comment by Leopoldthecoder** [comment]
This is just a native attribute and we simply pass it to the native input element. What the browser handles this prop is out of our control.

For input validations, use Form.

**Comment by sheldonzf** [comment]
OK，I see.
But is `minlength` is input's native attribute ？
If not, is it should be remove from the document ?

**Comment by Leopoldthecoder** [comment]
It is. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by sheldonzf** [comment]
It seems no work on any browser.
