### ISSUE TITLE
When [Bug Report] uses render to dynamically render el-menu components, scopedSlots can not be used in <el-submenu/>, while scopedSlots in <el-menu-item/> is no problem

### ISSUE THREAD

**Issue by penggle** [ElemeFE/element#10096]
### Element UI version
2.2.1

### OS/Browsers version
windows 10

### Vue version
2.5.14

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/549/](https://jsfiddle.net/mmx38qxw/549/)

### Steps to reproduce
以上代码在ElementUI-1.x版本没问题，但是在2.x版本使用render动态渲染el-menu组件时，<el-submenu/>中无法使用scopedSlots，而<el-menu-item/>中使用scopedSlots却没问题

### What is Expected?
不知道是不是bug或者是我使用不对，因为菜单是动态从数据库中load出来的，所以必须使用render来渲染，请ElementUI大神给出解决方案，急啊

### What is actually happening?
submenu的自定义title渲染不出来

**Comment by penggle** [comment]
recurisiveLoadSubMenu: function(h, menus){
					var _this = this;
					var elements = [];
					if(menus && menus.length){
						menus.forEach(function(menu){
							var item = null;
							if(menu.subMenuList && menu.subMenuList.length){
								item = h({
									template: '<el-submenu :index="index"><template slot="title"><i :class="menuIcon"></i><span>{{menuName}}</span></template><slot></slot></el-submenu>',
									data: function(){
										return {
											index: menu.menuPath,
											menuIcon: menu.menuIcon,
											menuName: menu.menuName
										};
									}
								}, {
									scopedSlots: {
										default: function(){
											return _this.recurisiveLoadSubMenu(h, menu.subMenuList);
										}
									}
								});
								elements.push(item);
							}else{
								item = h('el-menu-item', {
									props: {
										index: menu.menuPath
									}
								},[h('i', {'class': [menu.menuIcon]}), h('span', menu.menuName)]);
								elements.push(item);
							}
						}, this);
					}
					return elements;
				}

哎，好长时间没搞vue了，这个不bug，终于试出来了，只能像上面那样做了

**Comment by penggle** [comment]
`item = h({
							template: '<el-submenu :index="index" :popper-class="popperClass"><template slot="title"><i :class="menuIcon"></i><span>{{menuName}}</span></template><slot></slot></el-submenu>',
							data: function(){
								return {
									index: menu.menuPath,
									popperClass: 'admin-aside-submenu',
									menuIcon: _this.formatMenuIcon(menu.menuIcon),
									menuName: menu.menuName
								};
							}
						}, {
							scopedSlots: {
								default: function(){
									return _this.recurisiveLoadSubMenu(h, menu.subMenuList, level + 1);
								}
							}
						});`

以上面的方式来渲染的确可以，但是如果collapse=true时，即菜单收起的时候，submenu的子菜单popper在鼠标hover时，不显示，还是存在问题！

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/606/

**Comment by penggle** [comment]
非常感谢提供demo，本人偏后台语言开发，好长时间没摸vue、element了，这个菜单动态加载弄了我好长时间了 @Leopoldthecoder
