### ISSUE TITLE
[Bug Report] Pagination with "sizes" in layout causes error

### ISSUE THREAD

**Issue by ryantbrown** [ElemeFE/element#10094]
### Element UI version
2.2.1

### OS/Browsers version
OSX 10.13.2 / Chrome 64.0.3282.186

### Vue version
2.5.14

### Reproduction Link
[https://jsfiddle.net/re4soysx/5/](https://jsfiddle.net/re4soysx/5/)

### Steps to reproduce
Add `<el-pagination>` element with `sizes` in the `layout` prop.

### What is Expected?
The size select should show up and be selectable.

### What is actually happening?
The size select does not show up and the console has the following errors:
```js
[Vue warn]: Error in nextTick: "TypeError: _this12.$refs.reference.$el.getBoundingClientRect is not a function"
[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"
All found in: <ElSelect><Sizes><ElPagination>
```

**Comment by ryantbrown** [comment]
I actually found this error while using 2.0.1 but then upgraded to 2.2.1 to see if a fix was pushed, but found the same error.

Here is another fiddle with both `@current-change` and `@size-change` set: https://jsfiddle.net/re4soysx/8/. I still get the same error.

**Comment by ryantbrown** [comment]
So downgrading to Vue `2.5.13` fixes this. Vue `2.5.14` was released a few hours ago.

**Comment by Leopoldthecoder** [comment]
Hi, thanks for reporting this issue. Since #10093 has more participants, I'll update the progress there.
