### ISSUE TITLE
[Feature Request] Disable Cancel button on server call

### ISSUE THREAD

**Issue by nasr18** [ElemeFE/element#10090]
### Existing Component
Yes

### Component Name
MessageBox

### Description
I wanna disable the cancel button in MessageBox after making the server request. It would be very nice if u provide this option...

here's the screenshot...
https://user-images.githubusercontent.com/7514936/37213055-edf770fc-23d6-11e8-99f6-43b836b7749f.png

**Comment by Leopoldthecoder** [comment]
See this example: http://element.eleme.io/2.2/#/en-US/component/message-box#customization .

**Comment by nasr18** [comment]
@Leopoldthecoder so u want me to `hide` the cancel button while making server call. am i rt?
