### ISSUE TITLE
ElementUI 表头扩充

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1010]
请问最新的elementUI 有没有扩充表头分组的功能，如果需求扩充怎么扩充

**Comment by furybean** [comment]
请问『表头分组』是否指的是多级表头的功能？

**Comment by yuanshengchao** [comment]
是的

**Comment by yuanshengchao** [comment]
请问自己需要该功能需要怎么扩充或者修改源码呢？

**Comment by yuanshengchao** [comment]
请问自己需要该功能需要怎么扩充或者修改源码呢？

**Comment by furybean** [comment]
这个需求与 #993 重复。
Table 所有的源代码都在这里：https://github.com/ElemeFE/element/tree/master/packages/table/src
