### ISSUE TITLE
Main will be compressed when the [Bug Report] container is set up for header

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#10100]
### Element UI version
2.2.1

### OS/Browsers version
win10/ Chrome 65.0.3325.146

### Vue version
2.5.14

### Reproduction Link
[https://jsfiddle.net/fv4LLcym/](https://jsfiddle.net/fv4LLcym/)

### Steps to reproduce
无

### What is Expected?
main应该为自适应

### What is actually happening?
main的高度为0

**Comment by Leopoldthecoder** [comment]
容器没有高度，自然无法「自适应」：https://jsfiddle.net/fv4LLcym/3/

**Comment by gaecfov** [comment]
原本是设置了高度的，如果container有嵌套就会出现这个情况
https://jsfiddle.net/hpuxkmvz/8/
原本嵌套时内部的container是放在父container的main中的，在2.0.11版本之前是没问题的
现在如果内部container放在父容器的container下也是没问题的，不过要修改之前所有嵌套在main中的代码
查看了版本历史发现是由于container和main设置了flex-basis引起的，请问这个是bug吗？flex-basis这个不太理解
谢谢！

**Comment by Leopoldthecoder** [comment]
少了一层 `<el-container>`: https://jsfiddle.net/hpuxkmvz/18/
