### ISSUE TITLE
[Feature Request] Reset form validation

### ISSUE THREAD

**Issue by Chalkin** [ElemeFE/element#10104]
### Existing Component
Yes

### Component Name
form validation

### Description
I could not find a way on how to reset the validation state of a form. Is there any way? If not, this would come in really handy to implement.

**Comment by Leopoldthecoder** [comment]
Reseting validation state without clearing input?

**Comment by Chalkin** [comment]
Yes, correct. Without clearing the values.

**Comment by Leopoldthecoder** [comment]
You can use `clearValidate`. You can find it in the docs for Form.
