### ISSUE TITLE
[Bug Report] <el-select> broken in Vue 2.5.14

### ISSUE THREAD

**Issue by shiny** [ElemeFE/element#10103]
### Element UI version
2.2.1

### OS/Browsers version
OS X

### Vue version
2.5.14

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/591/](https://jsfiddle.net/mmx38qxw/591/)

### Steps to reproduce
复制文档中第一个默认示例，在 2.5.13 版本中能正常运行，在 2.5.14 中有出错
这是低一个版本号的示例： https://jsfiddle.net/mmx38qxw/590/
这是最新版本号中的示例：https://jsfiddle.net/mmx38qxw/591/

[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"

found in

---> <ElInput>
       <ElSelect>
         <Root>

### What is Expected?
正常运行

### What is actually happening?
出现 Vue warn 并且空白

**Comment by Leopoldthecoder** [comment]
Duplicate of #10093

**Comment by gaolongxin062** [comment]
解决了吗这个问题，我也遇到了这个错误

**Comment by gaolongxin062** [comment]
> > 解决了吗这个问题，我也遇到了这个错误
> 
> 看 #10093 里的情况，升级 Vue 应该能解决问题。我当时的处理是降级 element 版本也能运行。

我之前降级到2.5.13没有作用，还是报错；我现在升级到了2.5.15希望能起作用吧，这个错误不是一直出现，偶尔才会出现
