### ISSUE TITLE
Switch 开关 初始化时回调

### ISSUE THREAD

**Issue by jfb** [ElemeFE/element#1011]
### ElementUI version
 1.0.0

### OS/Browers version
 macOS/Chrome 53

### Vue version
 2.0.0-rc.4

### Reproduction Link
https://jsfiddle.net/62paL6go/

### Steps to reproduce

mounted后如果值和默认值不一样，会产生change事件。

**Comment by Leopoldthecoder** [comment]
Fixed in #1002
