### ISSUE TITLE
[Feature Request] Tree  lacks the attribute of the default selected key (not the checkbox selection)

### ISSUE THREAD

**Issue by zhou470259742** [ElemeFE/element#10118]
### Existing Component
是

### Component Name
tree

### Description
开发中偶尔会遇到这样的场景，默认初始化时需要选中树中的一个节点，等于node的click方法，目前tree提供的方法中有setCurrentKey这样的方法，但是这样的方法并不方便，而且存在一个异步的问题，如果要使用的话需要在调用方法的代码块上嵌套一个setTimeout，建议可以提供类似于default-checked-keys这样的属性，可以更方便的达到想要的效果

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
