### ISSUE TITLE
[Bug Report] officially guides the installation of select components to memory leaks

### ISSUE THREAD

**Issue by doramart** [ElemeFE/element#10113]
### Element UI version
2.0.11

### OS/Browsers version
版本 64.0.3282.186（正式版本） （64 位）

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce

`
> npm i -g vue-cli
> mkdir my-project && cd my-project
> vue init webpack
> npm i && npm i element-ui
`

在 main.js 中写入以下内容：

import Vue from 'vue'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import App from './App.vue'

Vue.use(ElementUI)

new Vue({
  el: '#app',
  render: h => h(App)
})
这些步骤跟官网完全一致，下面在 HelloWorld.vue 中加入select组件：
`
<el-select v-model="value" placeholder="请选择">
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value">
    </el-option>
  </el-select>
`
data中添加 value和options，跟官网demo一致

页面自动刷新，报内存溢出，必现，这个问题是在项目中发现的，排查很久以为是编码问题，原因是重新安装依赖包引起的，然后尝试官网快速入门demo，只要新装了依赖包，这个问题必现。

### What is Expected?
select 组件不报错

### What is actually happening?
只要引入选择组件，必然报异常
![image](https://user-images.githubusercontent.com/11911066/37250137-8145b350-2530-11e8-8d84-d739869ef529.png)

**Comment by Leopoldthecoder** [comment]
请升级 Vue 至 2.5.15，#10093
