### ISSUE TITLE
[Bug Report] el-select err in electron-vue

### ISSUE THREAD

**Issue by cobola** [ElemeFE/element#10124]
### Element UI version
2.2.1

### OS/Browsers version
vue-electron 1.0.6

### Vue version
2.5.15

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
it works in web,
i cannot reproduct in jsfiddle

just use 
el-select in electron-vue

只是简单的把el-select 加在界面里面 没有增加任何处理
在electron  环境中报错
http://ww1.sinaimg.cn/large/3e646cdcly1fpa01sndoaj22j61ba7m3.jpg

### What is Expected?
select element as the result 

### What is actually happening?
[Vue warn]: Error in nextTick: "TypeError: _this12.$refs.reference.$el.getBoundingClientRect is not a function"

[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'style' of undefined"

http://ww1.sinaimg.cn/large/3e646cdcly1fpa01sndoaj22j61ba7m3.jpg

**Comment by furybean** [comment]
抱歉，我们没人任何人有使用 vue-electron 的经验，目前当做 `need: repro` 处理。
如果你能解决这个问题，欢迎你提 PR，谢谢。

**Comment by Leopoldthecoder** [comment]
从报错来看，应该是因为使用了 2.5.14 版本的 Vue（参考#10093）。升级 Vue 到 2.5.15 试试。

**Comment by cobola** [comment]
搞定了 是这个原因 多谢

**Comment by gaolongxin062** [comment]
> 搞定了 是这个原因 多谢

升级到2.5.15可以吗，我也遇到了这个问题
