### ISSUE TITLE
[Bug Report]  When the table component loads the data asynchronously and uses the fix attribute, the style is disorderly under Safari and IOS

### ISSUE THREAD

**Issue by kenziD** [ElemeFE/element#10125]
### Element UI version
2.2.1

### OS/Browsers version
safari,ios 11

### Vue version
2.5.15

### Reproduction Link
[https://jsfiddle.net/ymd0su33/11/](https://jsfiddle.net/ymd0su33/11/)

### Steps to reproduce
使用ajax异步获取table的data，并设置一个某列固定

### What is Expected?
第一列固定的table

### What is actually happening?
被固定的那一列，样式错乱，使用colgroup定义的宽度没有起作用

![](http://7xk7fp.com1.z0.glb.clouddn.com/TIM%E5%9B%BE%E7%89%8720180312140840.png)

**Comment by kenziD** [comment]
感觉是colgroup中定义的width没有被(safari浏览器、iphone6\iphone5的微信浏览器)识别，但是使用了v-if将表格和其他展示页切换一下后，表格又显示正常了。只有在初始化时样式是错乱的，所以不确定是safari浏览器不支持colgroup中的width还是数据监听部分出现问题，比如没有rerender之类。

使用style或者class去设置width后问题解决，但不确定是否是正确的解决的方法。。。
table-column.js
![](http://7xk7fp.com1.z0.glb.clouddn.com/Image%2016.png)

table-header.js
![](http://7xk7fp.com1.z0.glb.clouddn.com/Image%2017.png)

**Comment by sandesh-bhoir** [comment]
the issue still persists, is there any update on same?
