### ISSUE TITLE
[Bug Report] Tooltip don't work

### ISSUE THREAD

**Issue by kolesoffac** [ElemeFE/element#10127]
### Element UI version
2.2.1

### OS/Browsers version
MacOs Version: 10.13.1 / Chrome Version: 63.0.3239

### Vue version
2.5.15

### Reproduction Link
No

### Steps to reproduce
* there is creating popperVM
![image](https://user-images.githubusercontent.com/11459507/37275030-273dd044-25ef-11e8-84f1-365b7b2846fe.png)
* 
![image](https://user-images.githubusercontent.com/11459507/37275076-4b700888-25ef-11e8-8fe6-3341b84a80a3.png)
*
![image](https://user-images.githubusercontent.com/11459507/37275114-622e9a58-25ef-11e8-915b-24f0ea4f1229.png)
*
![image](https://user-images.githubusercontent.com/11459507/37275167-83cc5fe2-25ef-11e8-92e1-6e74b1de0d91.png)

### What is Expected?
visible tooltip

### What is actually happening?
Don't visible tooltip

Why can don't create instance virtual node from popoverVM.node?

On jsfiddle.com all works. (

Tell me, please, what specific problems I may have.

Thanks

**Comment by Leopoldthecoder** [comment]
Please minify your project and push it to a GitHub repo. We couldn't figure out what went wrong without actual code.

**Comment by kolesoffac** [comment]
I undestand, that need repro, but I use element in private project. And don't can to reproduce on jsfiddle.com. But what can be causes, that popoverVM.node don't render?

**Comment by kolesoffac** [comment]
`<script src="//unpkg.com/element-ui@2.2.0/lib/index.js">`
is there index not minified? what could I do debug code...

**Comment by Leopoldthecoder** [comment]
It doesn't matter if your project is private. You can remove all irrelevant code, making the repo as small as possible, but still can reproduce the problem.

**Comment by Leopoldthecoder** [comment]
Please open a new issue when you have a repro. Closing this one.

**Comment by jimliang** [comment]
I found overflow tooltip don't work when using webpack.DllPlugin to pack element-ui into vendor.

**Comment by anonymous-wang** [comment]
Same issue with @jimliang

**Comment by foreverhot1019** [comment]
using webpack to load element-ui &vue,  element-ui has code require('vue'),and it will load vue.js，if you config vue.min.js Tooltip will not working
