### ISSUE TITLE
[Bug Report] vue-multiselect in table dropdown not show

### ISSUE THREAD

**Issue by anonymous-qsh** [ElemeFE/element#10120]
### Element UI version
2.2.1

### OS/Browsers version
chrome-LTS

### Vue version
2.5.15

### Reproduction Link
[https://jsfiddle.net/jqofkzxc/1246/](https://jsfiddle.net/jqofkzxc/1246/)

### Steps to reproduce
1. using npm install dependence.
2.create element ui and vue-multiselect object by doc.
3.put vue-multiselect component in element table component.
4.the dropdown does not show.

### What is Expected?
should show the option in vue-multiselect dropdown box.

### What is actually happening?
The dropdown box is hidden, but I could select option by enter.

**Comment by Leopoldthecoder** [comment]
That's because table cell has `overflow: hidden`. Here's a simplified demo: https://jsfiddle.net/jqofkzxc/1272/ . You may want to +1 for https://github.com/shentao/vue-multiselect/issues/618 .
