### ISSUE TITLE
官网的树形插件demo 自定义节点内容 -使用 scoped slot方式 实现append 和delete 方式的 不能用

### ISSUE THREAD

**Issue by zhouDCC** [ElemeFE/element#10122]
具体表现 在 jsfiddle 里面在线运行是可以用的 但是复制到本地的vue 文件里面  scoped solt 方式 实现 就不能显示出 append 和delete  按钮

**Comment by zhouDCC** [comment]
秒关issue？

**Comment by DengMingHao** [comment]
这是2.2以后的新版本特性，你看看你的版本是否正确。我刚刚也遇到这个问题。
