### ISSUE TITLE
[Feature Request] Updation of element-table NPM package

### ISSUE THREAD

**Issue by mdsadique2** [ElemeFE/element#10133]
### Existing Component
Yes

### Component Name
element-table

### Description
I am using element-table (https://www.npmjs.com/package/element-table), but the NPM package is pretty old where I am not getting your fixes related to "Forward fixed column's mousewheel event to entire table #9323".

Can you please update the NPM package ?

**Comment by Leopoldthecoder** [comment]
Published `element-table@2.2.2`.
