### ISSUE TITLE
[Bug Report] why not element-dev support npm install while latest npm already support package-lock?

### ISSUE THREAD

**Issue by liwenda122** [ElemeFE/element#10132]
### Element UI version
2.2.1

### OS/Browsers version
windows 7/chrome

### Vue version
2.5.15

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
1.clone latest element-ui dev master
2.run npm install

### What is Expected?
support npm install 

### What is actually happening?
npm install failure

**Comment by wacky6** [comment]
Please provide more information of the error. For example, npm error log
