### ISSUE TITLE
Whether [Feature Request] el-transfer can add a method to get the current selected value

### ISSUE THREAD

**Issue by wuzechuan** [ElemeFE/element#10144]
### Existing Component
Yes

### Component Name
el-transfer

### Description
当我在穿梭框选中任一选项的时候，我希望能够获取到选中的这个选项的key或者value以便在穿梭框下面加一个span添加备注说明

**Comment by Leopoldthecoder** [comment]
如果添加一个事件，这个事件在用户选中项目前的多选框（并未真正移动项目）时触发，参数是当前已选中的项目的 key 组成的数组，是否满足你的需求？

**Comment by wuzechuan** [comment]
@Leopoldthecoder 我想要的是类似select的focus方法，可以获取到当前鼠标点击选项的key/value，然后在移动项目后的框也希望可以这样
