### ISSUE TITLE
[Feature Request] Range slider should not have identical value max and min

### ISSUE THREAD

**Issue by arxanter** [ElemeFE/element#10145]
### Existing Component
Yes

### Component Name
Slider

### Description
Range slider should not have identical value max and min. I think need override values when this happened.

Example. step = 10. If change [20, 20] override [20,30] or [10, 20]

**Comment by Leopoldthecoder** [comment]
You should handle this on your end.

**Comment by arxanter** [comment]
Yes, ofc. But I think it's a good attribute for the component. Ok. Thank you for Element UI.
