### ISSUE TITLE
[Feature Request] Table: Ctrl/Shift Click multi table

### ISSUE THREAD

**Issue by zhangzhongjiang** [ElemeFE/element#10146]
### Existing Component
是

### Component Name
Table

### Description
在项目开发中，有很多需求需要类似于Excel表格的操作方式，就是先按下shift或ctrl键，然后再点击，实现选中连续的多行单元格的目的。

**Comment by Leopoldthecoder** [comment]
可以借助现有 API 实现：https://jsfiddle.net/6j8bpg0a/12/
![untitled1](https://user-images.githubusercontent.com/10095631/37335610-f7d30152-26e9-11e8-8cc2-45b97679eaf7.gif)

只实现了 shift 的连选，ctrl 应该类似。
