### ISSUE TITLE
[Bug Report] el-time-select bug

### ISSUE THREAD

**Issue by xyhxyw** [ElemeFE/element#10150]
### Element UI version
2.2.1

### OS/Browsers version
chrome65

### Vue version
2.5.15

### Reproduction Link
[https://jsfiddle.net/xyhxyw/L5bu56fq/](https://jsfiddle.net/xyhxyw/L5bu56fq/)

### Steps to reproduce
1 click open Dialog
2 manually set the startTime as 'abcd'(illegal string).
3 click open Dialog again,the startTime value is still there even the resetFields function was executed when close the dialog.

### What is Expected?
1 when the resetFields function was executed,the startTime shoud be set to default value
2 how to validate the startTime value when people set the value manually 

### What is actually happening?
1 startTime value is still there

**Comment by Leopoldthecoder** [comment]
Fixed in #10176
