### ISSUE TITLE
[Feature Request] Keep columns in expanded table row

### ISSUE THREAD

**Issue by jacek-rzrz** [ElemeFE/element#10151]
### Existing Component
Yes

### Component Name
Table

### Description
Currently, expanded rows always render a `<tr><td colspan={ this.columns.length }`. Our team needs to implement a functionality where an expanded section consists of a few rows, each holding the same number of columns as the table.

We are happy to start a pull request and implement it provided that such addition would be welcome in the table API. We were thinking of an additional slot that can optionally replace the whole <tr> tag, but are interested in hearing alternative ideas!

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
