### ISSUE TITLE
[Bug Report] Cannot use with Rollup

### ISSUE THREAD

**Issue by zont** [ElemeFE/element#10162]
### Element UI version
2.2.1

### OS/Browsers version
any

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/](https://github.com/ElemeFE/element/)

### Steps to reproduce
1) create index.js:
```js
import Vue from 'vue';
import ElementUI from 'element-ui';

Vue.use(ElementUI);
```

2) create rollup config:
```js
import resolve from 'rollup-plugin-node-resolve';
import vue from 'rollup-plugin-vue';

export default {
  input: 'src/ui/index.js',
    output: {
      intro: 'const process = { env: { NODE_ENV: "production" } };',
      file: 'static/bundle.js',
      format: 'iife',
      name: 'app'
    },
    plugins: [
      resolve({ jsnext: true, browser: true }),
      vue({ css: true })
    ]
};
```

3) run build:
```
rollup --config rollup.config.js
```

### What is Expected?
Build ok

### What is actually happening?
Build fail:
![image](https://user-images.githubusercontent.com/821305/37389424-59a93f96-2775-11e8-8be7-9eef8a07d487.png)

**Comment by Leopoldthecoder** [comment]
You need to install [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs), and update your rollup config:
```js
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import vue from 'rollup-plugin-vue';

export default {
  input: './index.js',
  output: {
    intro: 'const process = { env: { NODE_ENV: "production" } };',
    file: 'static/bundle.js',
    format: 'iife',
    name: 'app'
  },
  plugins: [
    commonjs({ include: 'node_modules/**' }),
    resolve({ jsnext: true, browser: true }),
    vue({ css: true })
  ]
};
```

**Comment by zont** [comment]
Not working

**Comment by zont** [comment]
Not working:
![image](https://user-images.githubusercontent.com/821305/37395234-d13302d4-2786-11e8-8a6e-e9bfccedc73e.png)

**Comment by Leopoldthecoder** [comment]
Please upload your directory to a GitHub repo.

**Comment by zont** [comment]
Sorry, I used not latest rollup version (0.55)
