### ISSUE TITLE
Table组件显示问题

### ISSUE THREAD

**Issue by huarundong** [ElemeFE/element#10165]
![image](https://user-images.githubusercontent.com/28342941/37390835-4d5dec1c-27a4-11e8-830f-5088244a0148.png)
在2.0.11版本中使用表格，当升级版本到2.2.1后表头和内容之间出现边框错位的问题（如上图）！
谷歌浏览器测试问题如下：
所有列使用固定宽度时，出现错位
所有列不使用固定宽度时，正常

**Comment by Zhang-Yida** [comment]
遇到同样的问题
