### ISSUE TITLE
After [Bug Report] modifies the table-border color of element-variables.scss, the border of table displays inconsistencies

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#10172]
### Element UI version
2.2.2

### OS/Browsers version
windows10/chrome  64.0.3282.186

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/sek9um1e/](https://jsfiddle.net/sek9um1e/)

### Steps to reproduce
项目修改了element-variables.scss的table-border的颜色，如下：
/* Table
-------------------------- */
$--table-border:  1px solid $--border-color-lighter !default;
把$--border-color-lighter改成了$--border-color-base。
table显示的最右的边框和最下的边框颜色偏淡。

### What is Expected?
修改了element-variables.scss的table-border的颜色后，边框颜色一致。

### What is actually happening?
颜色不一致。

**Comment by AprilXtt** [comment]
效果图如下：
![image](https://user-images.githubusercontent.com/30852982/37410686-141893de-27dc-11e8-9c7c-ae53fbd92f59.png)

**Comment by Leopoldthecoder** [comment]
#10179 新增了 `$--table-border-color` 变量，发布后改写这个变量即可。
