### ISSUE TITLE
[Feature Request] recommends increasing the response of more optional dimensions

### ISSUE THREAD

**Issue by gaoshijun1993** [ElemeFE/element#10180]
### Existing Component
是

### Component Name
el-col

### Description
现在支持的最低的响应分辨率是768px (xs),在768px以下就无法响应了. 
 阿里的[飞冰](https://alibaba.github.io/ice/#/component/grid) 已经可以支持更小的响应尺寸

**Comment by Leopoldthecoder** [comment]
Element 不支持移动设备，所以小于 768 像素的屏幕不是 Element 的适配目标。

**Comment by vgavro** [comment]
If anyone interested what @Leopoldthecoder said - "Element does not support mobile devices, so screens that are smaller than 768 pixels are not an Element's fit.". it's actually sad that core developers answers in tickets in chinese language. And by the way - Element-ui working excellent on mobile devices, and support touch screens, so why not to use bootstrap's grid also?
