### ISSUE TITLE
[Bug Report] Enable scrolling of tab pane only (and not tabs themselves)

### ISSUE THREAD

**Issue by trapperkeeper** [ElemeFE/element#10198]
### Element UI version
2.2.2

### OS/Browsers version
MacOS High Sierra 10.13.3 / Chrome

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/detwiler/pen/LdZZNw](https://codepen.io/detwiler/pen/LdZZNw)

### Steps to reproduce
See codepen, decrease your browser window size enough that tab content must scroll. 

### What is Expected?
I would think that the desired behavior would be to scroll the content, but leave the navigation tabs in place?

### What is actually happening?
On scroll, tabs scroll off of screen with tab content. Setting size or overflow behavior of el-tabs and/or el-tab-pane, in CSS, does not seem to change this.

**Comment by Leopoldthecoder** [comment]
https://codepen.io/leopoldthecoder/pen/RMRMdK

**Comment by trapperkeeper** [comment]
Thank you Leopoldthecoder! Apparently my css-fu is inadequate. I will return to the mountains, find a css master, and begin my training anew.

**Comment by jri** [comment]
@Leopoldthecoder thank you for the tremendously useful pen!
