### ISSUE TITLE
The [Bug Report] component, [Alert] and [Notification], is not automatically switched on a long number.

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#10192]
### Element UI version
2.2.2

### OS/Browsers version
win10/chrome 65.0.3325.146（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/zo42jdru/1/](https://jsfiddle.net/zo42jdru/1/)

### Steps to reproduce
1.在Alert or Notification 的内容字段上填充数字型内容，则无法换行。

### What is Expected?
能正常换行。

### What is actually happening?
未换行。

**Comment by Leopoldthecoder** [comment]
请自行添加 CSS：https://jsfiddle.net/zo42jdru/3/

**Comment by yinjunonly** [comment]
@Leopoldthecoder 为什么组件会有这样的差异？
