### ISSUE TITLE
[Feature Request] Custom sort prop on el-table-column

### ISSUE THREAD

**Issue by jwenjian** [ElemeFE/element#10199]
### Existing Component
Yes

### Component Name
el-table-column

### Description
Recently, I am using element-ui to do an admin interface. In my use case, I want to do the backend sorting when I click some sortable column header.

Simple request, right?

But I faced a problem that the `prop` of the `<el-table-column>` is not the one I want to sort with in backend.Yes, I can do this converting in backend, but it's better if we have this new feature.

For example, we have a column named [create time], and the prop of `<el-table-column>` is "createTime", like below:
```html
<el-table-column prop="createTime" sortable></el-table-column>
```
 After I send the request with sort to the backend, I want the sort prop be "create_time" instead of "createTime" to make backend sorting easier.

So it will be great if we have a new prop like "propForSort" to handle this kind of use cases.

New el-table-column will be like this:
```html
<el-table-column prop="createTime" propForSort="create_time" sortable></el-table-column>
```

Maybe we already have some solution for this which I didn't know, it's very thanks for anyone who can tell me about that.

Thanks.

**Comment by Leopoldthecoder** [comment]
I don't think this is necessary because it's easy to do a prop name mapping before sending requests: https://jsfiddle.net/sgduseb5/3/

**Comment by jwenjian** [comment]
I still vote for a new prop on `el-table-column` because :

1. The `sortProp`(let't named it) is more reasonable to be a field of a `el-table-column`

2. It's easier to maintain the `prop` and the `sortProp` because they are in the same place(within the tag `el-table-column`).

Anyway, thanks for the link.
