### ISSUE TITLE
How [Feature Request] correctly sets the boder attribute of el-table

### ISSUE THREAD

**Issue by blueroseslol** [ElemeFE/element#10200]
### Existing Component
是

### Component Name
el-table

### Description
我自己尝试了修改了一下，不知道是否是正确方法：
https://jsfiddle.net/t75obz8w/2/

另外请教一下如果正确修改全局的el-table的border？
  .el-table--border td,.el-table--border th,.el-table td, .el-table th.is-leaf{
    border-color: #f50003;
  }
  .el-table--border{
    border-color: #f50003;
    border-bottom: 1px solid #f50003;
    border-right: 1px solid #f50003;
  }
这样修改是否是正确方法？

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/t75obz8w/6/

**Comment by feichangtutu** [comment]
sililar issue ,but I need border bottom none ,then solve issue by use
```
.el-table--border::after, .el-table--group::after, .el-table::before {
    content: '';
    position: absolute;
    background-color: #ebeef5;
    z-index: 1;
}
```
