### ISSUE TITLE
[Bug Report] [Bug Report] el table width isn't fix 100% when use v-if to hide a table-column

### ISSUE THREAD

**Issue by nekorice** [ElemeFE/element#10208]
### Element UI version
2.0.11

### OS/Browsers version
Windows 7 / Chrome 64.0.3282.186

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/g2s25j0d/4/](https://jsfiddle.net/g2s25j0d/4/)

### Steps to reproduce
set el-table width to width:100%
use v-if to hide a Table-column of the el-table
then the table width is broken

### What is Expected?
table element width to fix the el-table container width.

### What is actually happening?
the table lose the width of the hide table-column

**Comment by Leopoldthecoder** [comment]
不是 bug。Table 本身的宽度已经是 100% 了，但是后两列的宽度写死了。可以其中某一列不写 `width`，或把 `width` 换成 `min-width`: https://jsfiddle.net/g2s25j0d/10/
