### ISSUE TITLE
[Bug Report] Windows 10 system IE11 Table fixed no lateral scroll bar causes the mouse to be unable to drag and drag to view more column information

### ISSUE THREAD

**Issue by gefangshuai** [ElemeFE/element#10206]
### Element UI version
2.2.2

### OS/Browsers version
Windows10 / IE 11 & Edge

### Vue version
2.5.16

### Reproduction Link
[https://user-images.githubusercontent.com/3143306/37508882-f151c08c-292f-11e8-9ace-5c668eacef68.png](https://user-images.githubusercontent.com/3143306/37508882-f151c08c-292f-11e8-9ace-5c668eacef68.png)

### Steps to reproduce
当Table 左右有fixed属性，并且列较多的时候，可横向滚动查看所有列，但是Windows10下的IE11 浏览器和Edge浏览器没有出现横向滚动条，导致用户无法用鼠标进行横向拖拽滚动，看不到隐藏的列

### What is Expected?
可出现横向滚动条，可用鼠标进行横向拖拽

### What is actually happening?
可出现横向滚动条，可用鼠标进行横向拖拽

**Comment by Leopoldthecoder** [comment]
无法复现。

在 IE 11 和 Edge 下的官网：
![image](https://user-images.githubusercontent.com/10095631/37562739-b6e5cc14-2aaa-11e8-99d9-f87684512751.png)


在 IE 11 和 Edge 下的 jsfiddle：
![image](https://user-images.githubusercontent.com/10095631/37562736-9c3c561c-2aaa-11e8-9d80-cd2101fc45d3.png)

**Comment by gefangshuai** [comment]
@Leopoldthecoder Windows10 的IE滚动条微软已经做过处理，会类似Mac失去焦点自动隐藏
