### ISSUE TITLE
When [Bug Report] uses el-menu components, el-menu-item has a basic style. Padding-left can not cover / using component el-menu got a CSS CSS, it has no effect.

### ISSUE THREAD

**Issue by feng9217** [ElemeFE/element#10218]
### Element UI version
2.2.2

### OS/Browsers version
win10家庭版 / chrome the lastest

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/706/](https://jsfiddle.net/mmx38qxw/706/)

### Steps to reproduce
在将侧边栏整体改为 el-menu   el-menu-item 过程中, el-menu-item 元素始终有个 padding-left: 20px 的值无法覆盖, 查看chrome的dom盒子, 是在
element.style {
    padding-left: 20px;
}
中定义的, 请教如何将其覆盖掉, 高度这些el-menu-item的默认样式已经覆盖掉了, 唯独这个无解

### What is Expected?
去除el-menu-item的padding-left

### What is actually happening?
el-menu-item 出现无法覆盖的 padding-left

**Comment by Leopoldthecoder** [comment]
用 `!important`：https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity

**Comment by feng9217** [comment]
it works, thanks a lot 忘了这茬了

**Comment by quadraxas** [comment]
solution to this should not be !important.

**Comment by Acezhangloo** [comment]
👎  We should avoid !important in our code

**Comment by LiMengyang990726** [comment]
If not using `!important`, may I know the solution to this?
