### ISSUE TITLE
[Bug Report] TypeScript declaration file for ElInput does not include focus method

### ISSUE THREAD

**Issue by zhangbobell** [ElemeFE/element#10219]
### Element UI version
2.2.2

### OS/Browsers version
MacOS 10.13.3 (17D102) / Chrome 65.0.3325.162（正式版本） （64 位）

### Vue version
2.5.3

### Reproduction Link
[http://www.jsbin.com/no/need](http://www.jsbin.com/no/need)

### Steps to reproduce
TypeScript version 2.7.2

1. `ElInput` has exposed `input` method, developers could use it to make input element focused.
2. But I could not use it in TypeScript since the declaration for ElInput class does not include `input` method, you could see it [here](https://github.com/ElemeFE/element/blob/dev/types/input.d.ts).
3. I've tried to augment the declaration but failed, since class declaration could not be augmented in TypeScript.
4. I came up with a solution, but not very elegant, as:

```
// myproject/fold/input.d.ts
import { ElInput } from 'element-ui/types/input';

export declare class MyInput extends ElInput {

    focus(): void;
}
```

```
// my-component.tsx
import { MyInput } from 'myproject/fold/input';

@Component
export default class SiteName extends Vue {
    public $refs: {
        nameInput: MyInput
    };
    
    public someMethod( ) {
        this.$refs.nameInput.focus();
    }
}
```

6. The right way to solve it will be adding `focus` method to `element/types/input.d.ts`. So I open the issue here.

PS: `focus` is not the only omitted method, `inputSelect` method too. And with any other components too.

**If necessary, I'm glad to propose a pull request for this problem.**

### What is Expected?
There will be `focus` method on ElInput in TypeScript

### What is actually happening?
But there did not.

**Comment by zhangbobell** [comment]
@Leopoldthecoder Thank you very much for your rapid response with this issue, it's really help me a lot. And as mentioned above, could you please add `inputSelect ` method to the `input.d.ts` too? Since I want to select all in input box outside. 

Through this issue, I realized that writing declaration  is maybe a **systematic work**, we have to analysis the scenes that developer used, to determine which methods should be put into declare files.

I'm looking forward to discussion with you, and I could do something for this if necessary.

Thank you again!

**Comment by zhangbobell** [comment]
I simply compared the current documentation with current decalaration files, get a checklist below:
* menu.d.ts
    - [ ] open
    - [ ] close
* upload.d.ts
    - [ ] clearFiles
    - [ ] abort
* transfer.d.ts
    - [ ] clearQuery
* table.d.ts
    - [ ] toggleRowExpansion
    - [ ] clearSort
    - [ ] clearFilter
    - [ ] doLayout
* tree.d.ts
    - [ ] updateKeyChildren
    - [ ] getHalfCheckedNodes
    - [ ] getHalfCheckedKeys
    - [ ] getNode
    - [ ] remove
    - [ ] append
    - [ ] insertBefore
    - [ ] insertAfter

**Comment by Leopoldthecoder** [comment]
Actually `inputSelect` of ElInput is an inner method which is not exposed to users. We may not add it on the types definition.

The checklist makes sense because these methods are documented on the docs. If you're interested, you can help add their definitions.

**Comment by zhangbobell** [comment]
Thanks for your reply, I'll completed the job in the checklist soon.

At the same time, I know the `inputSelect` is a "private" method,  But a common scenes is: dynamically instantiate ElInput with some text, first focus it, and then select all the initial text. I could not do the second step without `inputSelect` method. Would you please consider to expose to the developers ? 

From this perspective, It has the same meaning with `focus` method. We may wrap the `inputSelect` method, and expose a public one.

**Comment by Leopoldthecoder** [comment]
I think we can do that because the `inputSelect` method is relatively independent and not coupled with other methods. I'll rename it to `select` and add it on the docs.

**Comment by zhangbobell** [comment]
Okey, I'll launch a pull request for the declaration files. 😆
