### ISSUE TITLE
[Bug Report] tag is closeable when option is disabled in a multiple select

### ISSUE THREAD

**Issue by da-development-id** [ElemeFE/element#10214]
### Element UI version
2.2.2

### OS/Browsers version
Mac / Chrome 65.0.x

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/odw2t8nq/12/](https://jsfiddle.net/odw2t8nq/12/)

### Steps to reproduce
create a el-select with multiple enabled with one option disabled and the data store has a default value set to the disabled option's value.

### What is Expected?
expecting the tag of the selected value to not be closeable so that value cannot be deselected.

### What is actually happening?
the tag can be closed by clicking on the close icon.

**Comment by wacky6** [comment]
Right now, you can handle input + value yourself. https://jsfiddle.net/z91kqfmr/

I'm inclined to consider `disabled` to be "can not be selected" instead of "can not be removed"

**Comment by Leopoldthecoder** [comment]
I agree with wacky.
