### ISSUE TITLE
[Bug Report] Table component el-table-column does not support asynchronous components

### ISSUE THREAD

**Issue by povs2012** [ElemeFE/element#10215]
### Element UI version
2.2.2

### OS/Browsers version
win10/chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/9xyos6y1/4/](https://jsfiddle.net/9xyos6y1/4/)

### Steps to reproduce
el-table中的el-table-column在使用scoped slot渲染时，所使用的组件是异步组件时，不能正确渲染异步组件。

### What is Expected?
异步加载的组件正确渲染

### What is actually happening?
异步加载的组件未渲染，切换expand后渲染成功

**Comment by povs2012** [comment]
应该是的

**Comment by ThoughtZer** [comment]
@povs2012 目前你有好的解决办法吗？

**Comment by povs2012** [comment]
没有，因为我的是异步组件加载导致的，不用异步组件就可以正常渲染

**Comment by ThoughtZer** [comment]
好吧，我的内部表格数据必须是点击箭头扩展之后异步获取的。数据是异步的了。一会也提一个issue吧

**Comment by BGOnline-CN** [comment]
刚刚正好帮同事解决了这个问题，给你们说说解决步骤吧。
先说说我们要实现什么业务：
1.页面中有个列表A
2.A列表的每一行可以展开
3.A列表展开的每一行中，有个B列表，B列表的数据是通过A列表每一行的ID查询出来的
大体业务就是这样的，很简单，但是在实现过程中一直掉坑。下面说说具体有哪些坑：
1.第一次点开A列表的每一行时，数据正常拿到但是无法渲染出B列表
第一个坑的原因猜想，大致因为，我们的B列表是异步获取的，数据没拿到，但是A列表已经展开。为了解决第一个坑，使A列表的行必须在数据拿到的情况下才打开，此时第一个坑基本就解决了，但是随之而来的是第二个坑
2.第一次点击A列表第一行，不渲染，但是点击第二行成功渲染B列表
为了解决第二个坑，尝试这在获取B列表数据的时候，将B列表的数据插入到A列表数据的当前行中，同时A列表的展开行采用slot-scope的方式赋值给B列表
到此，问题全部解决。代码我就不贴了，因为代码不在我的电脑中，我也是帮同时解决过程中，看到这个帖子，所以来分享下

**Comment by ThoughtZer** [comment]
我今天也找到一个解决的办法，但是不知道性能是否会有影响，业务场景也是：一个表格内部嵌套扩展表格，扩展表格的数据是根据外部表格当前行的ID异步获取。
我在data中维护了一个obj变量一开始是空的。然后每次点击前面的扩展，拿当前行的ID请求数据，请求到的数据使用this.$set设置到obj的变量中，key是当前行ID，value是数据。
```javascript
// 子组件向外emit点击扩展事件
expandChange(row) {
     this.$emit('expandChange', row)
}
// 子组件watch父组件传递过来的值chartingData,子组件使用innerChartingData 接收父组件传值
chartingData(newVal) {
  this.innerChartingData = newVal
}


// 父组件监听子组件的expandChange
expandChange(row) {
    // 根据row的id去请求数据之后，放到chartingData中
   ....
   this.$set(this.chartingData, row.id, data)      
}
```模版大致是这么写的
<div>
  <el-table :data="tableData.data"
            @expand-change='expandChange'>
    <el-table-column type="expand">
      <template slot-scope="props" v-if="innerChartingData[props.row.id] && innerChartingData[props.row.id].data.length">
        <el-table ref="innerChartingTable" :data="innerChartingData[props.row.id] && innerChartingData[props.row.id].data">
          <el-table-column v-for="(th, index) in innerChartingData[props.row.id] && innerChartingData[props.row.id].thead"
                           :key='index'
                           align="center"
                           :fixed="th.fixed ? th.fixed: false"
                           :label="th.label"
                           :prop="th.prop">
          </el-table-column>
        </el-table>
      </template>
    </el-table-column>
    <el-table-column v-for="(th, index) in tableData.thead"
                     :key='index'
                     :label="th.label"
                     :fixed="th.fixed ? th.fixed: false"
                     :sortable="th.sortable ? th.sortable: false"
                     :prop="th.prop">
    </el-table-column>
  </el-table>
</div>

**Comment by povs2012** [comment]
@Leopoldthecoder 我又进一步测试了一下，发现vue自身的scope-slot是支持异步组件的，https://jsfiddle.net/9xyos6y1/8/，是不是虽然table组件用了scope-slot，但并不是直接利用的vue的scope-slot机制？这个算不算table组件的问题？

**Comment by TuKun33** [comment]
@expand-change 同样的需求，该怎么拿到当前展开行的下标 还有展开状态

**Comment by ThoughtZer** [comment]
@TuKun33 它的回调函数会告诉你当前被展开收起的行和所有当前的展开行数组，通过后面的数组查询前面的行应该就可以。

**Comment by Even-Lau** [comment]
这个问题解决了吗，最近遇到同样问题，请问有好的解决方案吗？

**Comment by lemonW** [comment]
> 这个问题解决了吗，最近遇到同样问题，请问有好的解决方案吗？

昨天试了个办法，就是把异步拿到的数据推入`table`的数据中，譬如`this.tableData.find(v => v.orderId == id).remark= res.data`，然后模板中
`
<el-table-column type="expand">
            <template slot-scope="scope">
              
              <el-table :data="scope.row.remark">
                <el-table-column property="payType"
                  label="方式"
                  width="150"
                  align="center">
                  
                  <template slot-scope="scope">
                    <el-button v-if="scope.row.type == 1"
                      type="text"
                      size="mini">第一种</el-button>
                  </template>
                </el-table-column>
              </el-table>
            </template>
          </el-table-column>
`

**Comment by 841660202** [comment]
点击展开有回调吗？我需要再发送个请求拉取数据取一部分数据 @element-bot

**Comment by fanshl** [comment]
也遇到了同样的问题

**Comment by ziyoung** [comment]
现在显示正常了。
![image](https://user-images.githubusercontent.com/12947422/56337039-a70baf80-61d5-11e9-9e70-a7b2d5e5250e.png)

**Comment by bingyuea** [comment]
> 刚刚正好帮同事解决了这个问题，给你们说说解决步骤吧。
> 先说说我们要实现什么业务：
> 1.页面中有个列表A
> 2.A列表的每一行可以展开
> 3.A列表展开的每一行中，有个B列表，B列表的数据是通过A列表每一行的ID查询出来的
> 大体业务就是这样的，很简单，但是在实现过程中一直掉坑。下面说说具体有哪些坑：
> 1.第一次点开A列表的每一行时，数据正常拿到但是无法渲染出B列表
> 第一个坑的原因猜想，大致因为，我们的B列表是异步获取的，数据没拿到，但是A列表已经展开。为了解决第一个坑，使A列表的行必须在数据拿到的情况下才打开，此时第一个坑基本就解决了，但是随之而来的是第二个坑
> 2.第一次点击A列表第一行，不渲染，但是点击第二行成功渲染B列表
> 为了解决第二个坑，尝试这在获取B列表数据的时候，将B列表的数据插入到A列表数据的当前行中，同时A列表的展开行采用slot-scope的方式赋值给B列表
> 到此，问题全部解决。代码我就不贴了，因为代码不在我的电脑中，我也是帮同时解决过程中，看到这个帖子，所以来分享下

![image](https://user-images.githubusercontent.com/20988336/76195588-9916b100-6223-11ea-92c0-988afeb0deed.png)

这样就没有问题了
