### ISSUE TITLE
[Feature Request] drag and drop the zoom rotation component

### ISSUE THREAD

**Issue by yippeesoft** [ElemeFE/element#10226]
### Existing Component
否

### Component Name
vue-drag-resize-rotate

### Description
Draw a scene like a flowchart. The user can drag and drag a diamond square and so on and can zoom in

Similar to https://github.com/tigerlove/vue-drag-resize-rotate
Rather than like Vue.Draggable, only drag and drop and so on. Thank you

**Comment by furybean** [comment]
Sorry, we have no plan to support this.
