### ISSUE TITLE
[Bug Report] Menu router active-link

### ISSUE THREAD

**Issue by ar53n** [ElemeFE/element#10220]
### Element UI version
2.2.2

### OS/Browsers version
MacOS

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/kdh50btv/51/](https://jsfiddle.net/kdh50btv/51/)

### Steps to reproduce
1. Set route state

### What is Expected?
When you go to any URL link not have used activeClass or linkExactActiveClass

### What is actually happening?
Not work activeClassLink and linkExactActiveClass

**Comment by Leopoldthecoder** [comment]
There doesn't seem to be activeClass or linkExactActiveClass in your demo. Not sure what the problem is.

**Comment by wacky6** [comment]
I guess this is a duplicate for https://github.com/ElemeFE/element/pull/8353

**Comment by ar53n** [comment]
Can we implement router-link when the router is active?  and add an active class when the route active

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/kdh50btv/107/

**Comment by ar53n** [comment]
@Leopoldthecoder Its little bit not correct because if we change url in browser address bar we have two `is-active` class

**Comment by wacky6** [comment]
@Leopoldthecoder 

I'm considering if it's possible to give sensible behavior using `$router.resolve( menuItemRoute )` to "guess" which menu item should be active. 

Basically, menu-items whose `$router.resolve(menuItemRoute)` are prefix of `$router.currentRoute.path` are considered `is-active`.

---

This idea works for my toy project, whose menu / route looks like:

| Menu                | menuItem route    | path         |
|---------------------|-------------------|--------------|
| System Management   | /sys/             |              |
| - Initialization    | /sys/init/        |              |
| - Global Settings   | /sys/global/      |              |
| User Management     | /users/           |              |
| - `:uid` sub-routes |                   | /users/:uid  |

Support currentRoute is `/users/uid_1`, user management will be active.

**Comment by meteorlxy** [comment]
@wacky6 Any news on that ?

I just want a `menu-item` to be `is-active` when it is not `exact`, just like what `router-link` behaves.

But current `is-active` judgement is too "exact".
https://github.com/ElemeFE/element/blob/1aed314527036a00ad8449047343c115eac7bc7c/packages/menu/src/menu-item.vue#L54-L56

**Comment by wacky6** [comment]
Right now you need to hack it. There is no recent plan to change current behavior

**Comment by meteorlxy** [comment]
Alright, tkx
