### ISSUE TITLE
文件命名格式是不是错误了

### ISSUE THREAD

**Issue by gzponline** [ElemeFE/element#1022]
webpack.config.json  ==> webpack.config.js

**Comment by QingWei-Li** [comment]
哪个位置？我们没有 `webpack.config.json`

**Comment by gzponline** [comment]
[这里](http://element.eleme.io/#/component/quickstart)
![image](https://cloud.githubusercontent.com/assets/12186221/20246089/498b1ee0-a9ea-11e6-82be-e70da4725ff5.png)

**Comment by Leopoldthecoder** [comment]
> webpack.config.json ==> webpack.config.json

是希望改成什么？因为箭头两边看上去是一样的。

**Comment by furybean** [comment]
@Leopoldthecoder  webpack.config.js

**Comment by gzponline** [comment]
抱歉 我没说明白

**Comment by Leopoldthecoder** [comment]
#1035

**Comment by Leopoldthecoder** [comment]
多谢提醒，刚才糊涂了……

**Comment by Leopoldthecoder** [comment]
Fixed in #1035

**Comment by gzponline** [comment]
哈哈  我也是一下子发现了 最近在看 你们很棒的
