### ISSUE TITLE
[Bug Report] theme-chalk-preview (skin function is not compatible with IE ie speed and compatibility mode.)

### ISSUE THREAD

**Issue by haogjin** [ElemeFE/element#10234]
### Element UI version
2.0.11

### OS/Browsers version
ie

### Vue version
2.5.13

### Reproduction Link
https://elementui.github.io/theme-preview/#/zh-CN

### Steps to reproduce
在ie上运行链接，点击切换主题色，只改变了页面的头部颜色，页面的按钮颜色不会改变。

### What is Expected?
在ie浏览器上点击切换颜色提交，整体页面的颜色都改变（包括按钮）

### What is actually happening?
点击切换主题色，只改变了页面的头部颜色，页面的按钮颜色不会改变。

**Comment by Leopoldthecoder** [comment]
这个服务没有打算兼容 IE。请使用现代浏览器。

**Comment by haogjin** [comment]
完全不兼容，我们需求要兼容，请问能不能提供下解决思路？

**Comment by haogjin** [comment]
360和qq浏览器极速模式也是不兼容的

**Comment by Leopoldthecoder** [comment]
这只是用来下载样式文件的，并不面向终端用户，为何要做兼容？
