### ISSUE TITLE
[Bug Report] How to give "New Line \n" in any alter or messagebox?

### ISSUE THREAD

**Issue by fsaiyedOB** [ElemeFE/element#10235]
### Element UI version
1.4.13

### OS/Browsers version
Ubuntu 16.04 / Chrome 65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/724/](https://jsfiddle.net/mmx38qxw/724/)

### Steps to reproduce
Need new line in message box

### What is Expected?
New line should be implemented using \n

### What is actually happening?
New line not comming

**Comment by Leopoldthecoder** [comment]
Because https://jsfiddle.net/leopoldthecuber/mmx38qxw/729/

If you're using 2.x, you can https://jsfiddle.net/leopoldthecuber/3jm4Lm1L/
