### ISSUE TITLE
[Feature Request] Add Custom/Auxillary class to components

### ISSUE THREAD

**Issue by ptrwllrd** [ElemeFE/element#10238]
### Existing Component
Yes

### Component Name
Row, Col, Button, others

### Description
I know we can add a class natively like this: `<el-col class="custom__elelement--class" :xs="24">` but the result is that the custom class appears as first on the classlist, right before the "`el-col`" and other layout classes (`el-col-xs-24`). The custom class(es) should come last so as to be able to override the framework classes without using !important.

A similar problem manifests when using the `<el-button>` component but in this case the custom class comes between two Element classes: "`el-button custom-class el-button--default`".

Perhaps the components (all of them for that matter) should have an additional prop like for instance `:aux-class` which would allow for passing custom class(es) to the component and append them reliably at the end of the classlist?

**Comment by Leopoldthecoder** [comment]
> The custom class(es) should come last so as to be able to override the framework classes without using !important

CSS priority doesn't care about the order of classes in the template. It's the order of declarations in the style sheet that matters: whatever comes last overrides everything before it. Demo: https://jsfiddle.net/eg1n171u/1/ https://jsfiddle.net/eg1n171u/2/

So unless the style is written on the template (aka inline styles), overriding component styles doesn't need `!important`: https://jsfiddle.net/hzfpyvg6/2920/ .
