### ISSUE TITLE
[Bug Report] el-tooltip manual mode setting value display invalid

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#10231]
### Element UI version
2.2.2

### OS/Browsers version
win10/65.0.3325.162

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/365q0jx2/](https://jsfiddle.net/365q0jx2/)

### Steps to reproduce
设置属性 manual=“true” 设置value=“true”

### What is Expected?
显示tip

### What is actually happening?
未显示

**Comment by Leopoldthecoder** [comment]
目前可能没什么好的解决办法，建议这样处理：https://jsfiddle.net/leopoldthecuber/365q0jx2/3/
