### ISSUE TITLE
[Bug Report] v-loading on el-table(with border) causing el-table border display issue

### ISSUE THREAD

**Issue by jwenjian** [ElemeFE/element#10248]
### Element UI version
2.2.2

### OS/Browsers version
Windows 10/ Chrome 65.0.3325.162(32bits)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/h7kv5tap/7/](https://jsfiddle.net/h7kv5tap/7/)

### Steps to reproduce
just pay attention to the border-top and border-left lines(in red color for more clear) while el-table loading

### What is Expected?
border-top and border-left of el-table do not disappear when loading

### What is actually happening?
border-top and border-left of el-table will disappear when loading and show again after loading, thus will causing the table shaking in vision

**Comment by anilsth915** [comment]
**Use styles:**
```
.el-table--border,
.el-table--border td,
.el-table--border th,
.el-table th.is-leaf {
  border-color: #f50003;
}

.el-table::before,
.el-table::after {
  background-color: #f50003;
}

```
