### ISSUE TITLE
Module build failed: Error: No PostCSS Config found in: D:\vue\element-ui\node_modules\_element-ui@1.3.7@element-ui\lib\theme-default

### ISSUE THREAD

**Issue by ZhiGang-Fang** [ElemeFE/element#10249]
ERROR in ./node_modules/_css-loader@0.28.4@css-loader!./node_modules/_postcss-loader@2.0.6@postcss-loader/lib!./node_modules/_element-ui@1.3.7@element-ui/lib/theme-defa
ult/index.css
Module build failed: Error: No PostCSS Config found in: D:\vue\element-ui\node_modules\_element-ui@1.3.7@element-ui\lib\theme-default
    at Error (native)
    at D:\vue\element-ui\node_modules\_postcss-load-config@1.2.0@postcss-load-config\index.js:51:26
 @ ./node_modules/_element-ui@1.3.7@element-ui/lib/theme-default/index.css 4:14-145 18:2-22:4 19:20-151
 @ ./src/main.js
 @ multi webpack-dev-server/client?http://0.0.0.0:8888/ webpack/hot/dev-server webpack-hud ./src/main.js
webpack: Failed to compile.

**Comment by yanyang1116** [comment]
需要在 postcssloader ，里声明一个配置项: plugins 字段，空数组即可。
`  const postcssLoader = {
    loader: 'postcss-loader',
    options: {
      sourceMap: options.sourceMap,
      plugins: [], // 吐血，这个地方要声明，不然安装 elementui 会报错
    }
  }`

**Comment by liuximing2016** [comment]
碰到同样问题，困扰了半天，解决办法：
1. 在项目根路径下添加postcss.config.js，参考https://blog.csdn.net/qq_41831345/article/details/80636053
2. 按楼上yanyang1116的方法设置下postcssloader。

两步骤都做了，才解决
