### ISSUE TITLE
[Bug Report] [el-upload] fails to put the :data value in request payload that has been set in :before-upload

### ISSUE THREAD

**Issue by BkunS** [ElemeFE/element#10242]
### Element UI version
2.2.0

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element/tree/v2.2.0](https://github.com/ElemeFE/element/tree/v2.2.0)

### Steps to reproduce
html:
<el-upload :action="${postURL}" :data="uploadData" :before-upload="setUploadData" ...></el-upload>

scripts:
export default {
  data () {
    return {
      uploadData: {}
    }
  },
  methods: {
    setUploadData () {
      this.uploadData = {
        cloudStoragePath: '/test'
      }
    }
  }
}

### What is Expected?
Posting image payload should contain { cloudStoragePath: '/test' } in request payload.

### What is actually happening?
The image upload request body does NOT have updated uploadData object. Probably it is sent before the uploadData has been set, or the uploadData has been set but the upload request fails to retrieve the new value.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
