### ISSUE TITLE
Table location offset after the use of v-loading in [Bug Report] 2.2.2 version table

### ISSUE THREAD

**Issue by xiaofan9** [ElemeFE/element#10250]
### Element UI version
2.2.2

### OS/Browsers version
window 10/Chrome 65.0.3325.146

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/sifan/18bq16kw/](https://jsfiddle.net/sifan/18bq16kw/)

### Steps to reproduce
对比 https://jsfiddle.net/sifan/18bq16kw/ 与 https://jsfiddle.net/sifan/8vd0rwxm/ , 明显发现table loading 之后一个位置发生偏移，一个没有，怀疑css 改动问题，目前将css 换成以前版本没有此问题。

### What is Expected?
预期table loaing之后位置不发生偏移

### What is actually happening?
table loaing之后位置发生了偏移,大概在3-5px左右

**Comment by Leopoldthecoder** [comment]
Duplicate of #10248
