### ISSUE TITLE
[Bug Report] el-date-picker in IE 11 to assignment

### ISSUE THREAD

**Issue by fabin5** [ElemeFE/element#10255]
### Element UI version
2.2.2

### OS/Browsers version
win7/IE11

### Vue version
2.2.1

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、在IE11下
2、el-date-picker有默认值
3、通过双向数据绑定，改变其绑定的值

### What is Expected?
1、el-date-picker的值发生改变

### What is actually happening?
1、el-date-picker的值没有发生改变。

**Comment by Leopoldthecoder** [comment]
@fabin5 请更新你的 demo。

**Comment by fabin5** [comment]
@Leopoldthecoder   该问题我再看了一下，具体的情况为：为date-picker添加:placeholder，该placeholder为国际后的值（this.$t('xxx.yy'），这时候为时间控件更新值。该问题暂时无法通过例子证明。

**Comment by Leopoldthecoder** [comment]
Duplicate of #8548

**Comment by 381510688** [comment]
@Leopoldthecoder 什么时间可以修复~~~

**Comment by laola2013** [comment]
最近开发的项目也遇到了类似问题~

**Comment by jerry7723** [comment]
我也遇到相同问题，设置了placeholder以后就无法更新，在ie10，ie edge上。ie9没问题

**Comment by liwenda122** [comment]
IE9 不支持placeholder 当然没问题了

**Comment by liwenda122** [comment]
elment-ui 直接宣布只支持chrome算了

**Comment by chentangchun** [comment]
IE11 时间控件赋值也是有问题
