### ISSUE TITLE
如何管理多个按钮的loading状态？

### ISSUE THREAD

**Issue by miaosun009** [ElemeFE/element#1025]
### Vue version

我一个页面的若干个按钮组件，每个按钮都有:loading属性， 每一个组件都对应着一个ajax的请求，我想在点击某个按钮进行请求的时候当前点击按钮的:loading 的属性为true， 通常是用一个逻辑型的data数据来管理他的状态，如果每个按钮都应用这个data来管理状态的话， 只要一个按钮loading了，全部按钮的状态都会变成loading了， 难道要为每个按钮都指定一个不同的data来控制它的loading吗？ 还是有更好的方式。望解答。

**Comment by Leopoldthecoder** [comment]
一个思路：http://jsfiddle.net/leopoldthecuber/adoehw19/

这个问题和 Element 关系不大，先关闭了。
