### ISSUE TITLE
Whether [Bug Report] can insert el-date-picker in the table header

### ISSUE THREAD

**Issue by JZLeung** [ElemeFE/element#10257]
### Element UI version
2.2.2

### OS/Browsers version
windows7 

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/735/](https://jsfiddle.net/mmx38qxw/735/)

### Steps to reproduce
如链接中的代码。

### What is Expected?
![image](https://user-images.githubusercontent.com/7995232/37639285-bfb421f4-2c4b-11e8-8429-78196008a408.png)
如图，点击可以弹出选择框，并拿到已选择的时间段。

### What is actually happening?
实际效果：
![image](https://user-images.githubusercontent.com/7995232/37639326-de33b842-2c4b-11e8-8d18-cd510d65f4e7.png)
取出的 event 为 undefined。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/739/

**Comment by JZLeung** [comment]
@Leopoldthecoder 
if I want to process this data in a function defined in vue, how can i call the function?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/742/

**Comment by JZLeung** [comment]
@Leopoldthecoder 
ok, thx.

**Comment by JZLeung** [comment]
@Leopoldthecoder 
oh on, it still throw an error in `.vue` file. vm is not the Vue instance.
![image](https://user-images.githubusercontent.com/7995232/37644760-c6174166-2c5f-11e8-96b8-f358b3b232b6.png)
