### ISSUE TITLE
[Bug Report] The UI of empty status in table will be broken if there has multiple lines

### ISSUE THREAD

**Issue by cherry200604** [ElemeFE/element#10252]
### Element UI version
2.2.2

### OS/Browsers version
Chrome 65.0.3325.146

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/9rja7dam/6/](https://jsfiddle.net/9rja7dam/6/)

### Steps to reproduce
1. Use slot="empty" to set the empty text of table
2. Type with multiple lines in the slot block

### What is Expected?
The height of the empty block should be auto adjusted with the content that user set.

### What is actually happening?
The height didn't adjusted automatically and the lines would be covered.

**Comment by Leopoldthecoder** [comment]
I'd say the empty slot doesn't expect to be filled with long contents. But you can get what you want pretty easily with CSS: https://jsfiddle.net/leopoldthecuber/9rja7dam/8/

**Comment by cherry200604** [comment]
@Leopoldthecoder If I change the class style of the `.el-table__empty-text`, then it'll change to the style broken with I use the `empty-text` in the table props: https://jsfiddle.net/9rja7dam/11/

Does it means that I should always use only one way of them to use in my codebase?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/9rja7dam/13/
