### ISSUE TITLE
[Feature Request] How can I include image to a el-radio ?

### ISSUE THREAD

**Issue by nxmohamad** [ElemeFE/element#10264]
### Existing Component
Yes

### Component Name
el-radio

### Description
I have a el-radio-group with multiple el-radio options
I'd like to include an image so that it's like a card
I have tried nesting the <img> inside of the <el-radio> tags but that removes the label completely
How can I insert the image but still retain the label?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/ghcxj0d5/4/
