### ISSUE TITLE
[Bug Report] Two Navmenu on one page, active remains on one menu when other is clicked.

### ISSUE THREAD

**Issue by Wolrab1** [ElemeFE/element#10262]
### Element UI version
2.2.2

### OS/Browsers version
Version 65.0.3325.162 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/7ev2nsuh/](https://jsfiddle.net/7ev2nsuh/)

### What is Expected?
Two navMenus, when clicking a navmenuitem on one the other navmenuitem on another navmenu should be reset

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/7ev2nsuh/3/
