### ISSUE TITLE
[Bug Report] Table width breaks inside incactive tab pane

### ISSUE THREAD

**Issue by BobNobrain** [ElemeFE/element#10265]
### Element UI version
2.2.2

### OS/Browsers version
Ubuntu 16.04, Firefox 59.0.1

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/Lmpfc2xk/3/](https://jsfiddle.net/Lmpfc2xk/3/)

### Steps to reproduce
1. See that table has 100% width (as expected)
2. Go to 'Button' tab
3. Press 'Break table'
4. Go back to 'Table' tab

### What is Expected?
Table width should remain 100%

### What is actually happening?
Table width is broken. Table appears narrowed, it's second column collapses (because it has no width attribute specified)

**Comment by cougarwww** [comment]
附议

**Comment by cougarwww** [comment]
2.0.11 没有问题，2.1.0，2.2.2 有问题

**Comment by xfmeng17** [comment]
Same problem occurs, wait to update.
