### ISSUE TITLE
[Bug Report] el-select组件 改变disbaled时 控制台报错:"TypeError: Cannot read property 'clientHeight' of undefined"

### ISSUE THREAD

**Issue by yisayu** [ElemeFE/element#10274]
### Element UI version
1.4.13

### OS/Browsers version
ie9

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/yx71ju47/6/](https://jsfiddle.net/yx71ju47/6/)

### Steps to reproduce
修改el-select disabled状态 出现报错

### What is Expected?
修改el-select禁用状态

### What is actually happening?
禁用效果是达到了但是出现报错 "TypeError: Cannot read property 'clientHeight' of undefined" 虽然知道好像2.2.2版本里这个问题已经没有了  但是由于现在没有时间升级项目的element版本 希望等得到一个暂时解决1.4.13版本的解决方法 谢谢

**Comment by Leopoldthecoder** [comment]
这个问题仅在 1.4.8 和 1.4.9 出现。升级到 1.4.13 就可以。

**Comment by yisayu** [comment]
好的 谢谢 看了一下好像确实是1.4.9版本
