### ISSUE TITLE
[Bug Report] fixed table columns border-right missing

### ISSUE THREAD

**Issue by zh68319220** [ElemeFE/element#10277]
### Element UI version
2.2.2

### OS/Browsers version
windows 10 / chrome 65.0.3325.162

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/3m64s2gt/1/](https://jsfiddle.net/3m64s2gt/1/)

### Steps to reproduce
https://jsfiddle.net/3m64s2gt/1/

### What is Expected?
‘姓名 ’列的右边框显示

### What is actually happening?
‘姓名 ’列的右边框不显示

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/37703357-62fb46c8-2d30-11e8-9325-7815ec74c60c.png)

Demo 未能重现。

**Comment by zh68319220** [comment]
不好意思没有描述清楚：拉宽表格，使表格的横向滚动条消失之后，就能重现了。
![image](https://user-images.githubusercontent.com/13728178/37704789-d8db77ec-2d34-11e8-934a-585bd53a3254.png)
