### ISSUE TITLE
[Feature Request] Is there any way to determining which tree nodes can be expanded during click event？

### ISSUE THREAD

**Issue by miaojiuchen** [ElemeFE/element#10286]
### Existing Component
Yes

### Component Name
tree

### Description
The "expand-on-click-node" attribute disables all node's event action, what if I want to get programmable control?

**For example:**
I have a three-level tree, the first level is only a basic category, I want it expand immediate when clicking it.
In the second level node, there are some operation buttons on it, rendered by slot or renderContent or something else,
I don't want to expand it when I click the bar, because the third level content is insignificant sometimes, I only click the triangle on the left to expand it when I need them.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/32ancgfq/3/

**Comment by miaojiuchen** [comment]
谢谢！
