### ISSUE TITLE
[Bug Report] Table can not set dynamic height and max-height

### ISSUE THREAD

**Issue by VinceHuiWan** [ElemeFE/element#10289]
### Element UI version
2.2.2

### OS/Browsers version
Chrome & Saifri

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/773/](https://jsfiddle.net/mmx38qxw/773/)

### Steps to reproduce
Follow the jsfiddle, then uncomment the sentence in the mounted() function, the table will disappear.

### What is Expected?
The height should be become which I set

### What is actually happening?
The table will disappear or the height is just equal to the init value

**Comment by Leopoldthecoder** [comment]
Because `this.$refs.colTable.offsetHeight` is `0`: https://jsfiddle.net/leopoldthecuber/mmx38qxw/778/ .

**Comment by VinceHuiWan** [comment]
但是在实际中我这里是有问题的.
![04254f08-3e57-4bf8-ba43-090698015d22](https://user-images.githubusercontent.com/14930691/37714169-d4d997d6-2d53-11e8-9dff-7d536bcb806a.png)

打印出来:
<img width="565" alt="2f3643de-4f88-411b-a5f4-1489bb4588c1" src="https://user-images.githubusercontent.com/14930691/37714208-f2cd896e-2d53-11e8-97f5-8e371b1f0cf7.png">


页面显示

![dabe8581-25d1-4593-b769-e9885f74b997](https://user-images.githubusercontent.com/14930691/37714269-149202a0-2d54-11e8-8f64-ad215991ce17.png)
