### ISSUE TITLE
[Bug Report] IE11, MessageBox component, Click OK, the popup layer disappears, second

### ISSUE THREAD

**Issue by lily-elephant** [ElemeFE/element#10285]
### Element UI version
2.2.2

### OS/Browsers version
IE11

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/LilyEle/qpjxer0u/2/](https://jsfiddle.net/LilyEle/qpjxer0u/2/)

### Steps to reproduce
The main reason is that when the popup layer of ie11 is clicked, the pop-up page will disappear before the current page, and then it will flash again and disappear. Therefore, the pop-up layer will be seen on the page after the jump.
主要是ie11下：
功能是添加页面，我在调用接口添加成功以后，弹出添加成功弹层，点击确认跳转到列表页。但实际执行时，点击确认，弹出层消失，并没有立刻跳转，而是又一次显示添加成功的弹层，然后跳转了，或者就是显示的结果会在列表看到弹层闪现。

### What is Expected?
Do not see the pop-up on the page after the jump.

### What is actually happening?
see the pop-up on the page after the jump

**Comment by Leopoldthecoder** [comment]
You demo cannot be executed.

**Comment by lily-elephant** [comment]
That doesn't have a vue environment.

**Comment by Leopoldthecoder** [comment]
Use this as a template: https://jsfiddle.net/leopoldthecuber/kdh50btv/59/ .

**Comment by lily-elephant** [comment]
代码已更新，但是ie11环境下测试不了 https://jsfiddle.net/LilyEle/kdh50btv/70/

**Comment by lily-elephant** [comment]
![image](https://user-images.githubusercontent.com/19464247/37704903-3e0707c6-2d35-11e8-8768-aa40ceb59ffb.png)
这是点击确定按钮以后，没有跳转到列表页之前，又弹出了一次“添加成功框”

**Comment by Leopoldthecoder** [comment]
demo 中没有进行实际的路由跳转，请添加相关逻辑。

jsfiddle 与 IE11 不兼容，但是我们可以把代码放在兼容 IE11 的环境里跑，前提是你提供能正确运行的 demo。

**Comment by lily-elephant** [comment]
经过反复测试，调用接口会触发这种情况，不调用接口则没有。接口地址在代码里，外网访问不了
https://jsfiddle.net/LilyEle/kdh50btv/90/

**Comment by Leopoldthecoder** [comment]
demo 中仍然没有进行实际的路由跳转，关闭 issue。

**Comment by lily-elephant** [comment]
这是项目中的一个页面，跳到项目的另一个页面，在jsfiddle里怎么跳转路由
