### ISSUE TITLE
table el-table-column template里面的组件会渲染两次

### ISSUE THREAD

**Issue by wyjieying** [ElemeFE/element#10297]
在 el-table里面， el-table-column template 用自定义的控件， 然后如果加了 el-table-column selection fixed 
会导致template里面的控件created2次

代码 可以看一下 把fixed属性取消跟加上，查看 打印信息
<template>
    <el-table v-if="inited" :data="tableData" border style="width: 100%">
        <el-table-column v-if="inited" type="selection" width="44" fixed>
        </el-table-column>
        <el-table-column label="日期" width="180">
            <template scope="scope">
                <table-item></table-item>
            </template>
        </el-table-column>
    </el-table>
</template>

<script>
    import Vue from 'vue'
    const TableItem = Vue.extend({
        name: 'xt-table-item',
        render(createElement) {
            console.log('table item render...')
            return createElement('span', 'tableitem')
        },
        mounted() {
            console.log('table item mounted...')
        },
        destroyed() {
            console.log('table item destroyed...')
        },
        created() {
            console.log('table item created...')
        }
    })

    export default {
        components: {
            TableItem: TableItem
        },
        data() {
            return {
                tableData: [],
                inited: false
            }
        },
        mounted() {
            this.inited = true
            this.tableData.push({
                date: '2016-05-02',
                name: '王小虎',
                address: '上海市普陀区金沙江路 1518 弄'
            })
        }
    }

</script>

这样会导致一个问题， 如果template里面放 el-form-item 会使得el-form的验证fields里面保存了多份field，校验有问题

**Comment by littleBoBoy** [comment]
我也是这个问题，查了半天发现是fixed导致的，加上后 通过方法调用校验会触发两次
