### ISSUE TITLE
怎样用 js 关闭 Notification ?

### ISSUE THREAD

**Issue by niceue** [ElemeFE/element#1029]
因为要马上清除已经打开的 Notifications

**Comment by Leopoldthecoder** [comment]
目前可以做到，不过比较绕：
```javascript
let notifications = document.querySelectorAll('.el-notification')
[].forEach.call(notifications, notification => {
  notification.__vue__.$parent.handleClose()
})
```
会优化一下，在调用 `Notification` 时返回当前实例，然后直接调用 `handleClose` 就可以关闭。

**Comment by niceue** [comment]
@Leopoldthecoder 

谢谢，暂时这样子是解决了。element-ui 挺不错 :+1: 

建议像原生 [Notification](https://developer.mozilla.org/en-US/docs/Web/API/notification) 那样提供 `close` 方法
```javascript
this.$notify.close()
```

**Comment by Leopoldthecoder** [comment]
在 #1033 里加了。
