### ISSUE TITLE
[Feature Request] Nested component validation

### ISSUE THREAD

**Issue by maxim25** [ElemeFE/element#10294]
### Existing Component
Yes

### Component Name
el-form

### Description
I have a dynamically created form which has a number of nested components. Each nested component has a number of el-inputs etc inside of them. 

I bind every child component with v-model. In order to not violate vue's rule of not mutating a parent data inside a child component I emit an input event to bind it to the prop.

Everything works great until I start implementing validation. 
Since the el-input is bound to an intermediate variable --in order to not mutate the parent variable inside a child-- the v-model and the prop differ for the el-input I want to validate. Ex. The prop is "child.myInput" while the v-model is "mutableChild.myInput". This creates an error (it actually still works, although not on blur and only on submit).

```
vue.esm.js?efeb:578 [Vue warn]: Error in mounted hook: "Error: please transfer a valid prop path to form item!"
found in
---> <ElFormItem>
       <Room> at src/components/booking/Room.vue
         <Order> at src/components/booking/Order.vue
           <ElForm>
             <TransactionNew> at src/components/booking/TransactionNew.vue
               <BookingNew> at src/pages/booking_new.vue
                 <ElMain>
                   <ElContainer>... (2 recursive calls)
                     <Admin> at src/layouts/admin.vue
                       <App> at src/App.vue
                         <Root>
```

Is there a workaround for this? Or maybe a better structure I could be using.

**Comment by Leopoldthecoder** [comment]
Please write a demo of your form on [jsfiddle.net](https://jsfiddle.net).

**Comment by bubnenkoff** [comment]
The link to issue https://stackoverflow.com/questions/52446553/how-to-validate-nested-form-data-in-vue-element

JSFeedle https://jsfiddle.net/7nxkyrbf/
