### ISSUE TITLE
[Bug Report] upload can't get local connection and wide high information before uploading

### ISSUE THREAD

**Issue by ithack** [ElemeFE/element#10303]
### Element UI version
2.2.2

### OS/Browsers version
chrome

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/issues/10302](https://github.com/ElemeFE/element/issues/10302)

### Steps to reproduce
提交前我想做图片宽高判断

### What is Expected?
拿到文件上传前的地址

### What is actually happening?
只有file的有限几个属性可以拿到，不满足

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
