### ISSUE TITLE
[Bug Report] [Table] dynamic Height and max-height cannot be set in the 2.2.2 version, but in 2.0. 11 can be

### ISSUE THREAD

**Issue by VinceHuiWan** [ElemeFE/element#10306]
### Element UI version
2.2.2

### OS/Browsers version
Max OS & Windows 7

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/808/](https://jsfiddle.net/mmx38qxw/808/)

### Steps to reproduce
在jsfiddle没法真正的重现这个问题，但是我本地可以重现给你看。如果觉得可以的话我可以等下给你截图重现这个问题。

### What is Expected?
Table可以设置动态高度

### What is actually happening?
Table不可以设置动态高度

**Comment by no-simple** [comment]
我也遇到这个bug。在IE和forefox中才有该bug。 max-height的无法在created或mounted时期赋值修改

**Comment by no-simple** [comment]
把max-height的初始值设置为 负数就可以了。。例如  data () { return: maxHeight: -1 }.     在mounted在赋值即可。

**Comment by VinceHuiWan** [comment]
还有这种操作？我试一试。不过这个就是个bug啊，我昨天提了，作者不信啊

**Comment by Leopoldthecoder** [comment]
> 我昨天提了，作者不信啊

我已经在那个 issue 里回复，你昨天的 demo 有误，把 Table 高度设置为了 `0`。

> 如果觉得可以的话我可以等下给你截图重现这个问题

截图只能证明问题存在，并不能说明问题出在哪里，无助于我们定位问题。

##

本 issue 中的 demo 在 Chrome 和 FireFox 中均无法重现问题。如果在 jsfiddle 确实无法重现，请 @VinceHuiWan @no-simple 两位将出问题的项目简化并上传至 GitHub。

**Comment by VinceHuiWan** [comment]
我尝试了在jsfiddle中重现问题，但是好像并不能重现。在vue模板中maxHeight设置是没问题的，我重试了不还原vue版本,还原Element-ui版本，这个问题就不存在了，还原VUE版本不还原Element-UI版本，这个问题还是存在的,说明这个问题是Element-ui的问题.VUE的传值是有结果的，但是Table max-height好像只要初始化了一个正确数值以后就不会更新了。比如说把传参数改成-1能正常显示，但是改成一个正数就不行了。
当adminTableHeight: -1,的时候
![0y3jt 4bzd22 1 n mr5oj](https://user-images.githubusercontent.com/14930691/37810121-6b7b116c-2e8d-11e8-94ca-2bd8c9d292e1.png)


当adminTableHeight: 200 的时候
![3x s wt704sf 7m wi mnbb](https://user-images.githubusercontent.com/14930691/37810134-866408ee-2e8d-11e8-8c89-b92ef9b30dfe.png)


项目简化上传的话可能需要时间

**Comment by zdz1993** [comment]
同样遇到这个问题

**Comment by zdz1993** [comment]
在mounted不能给maxHeight赋值

**Comment by VinceHuiWan** [comment]
这个问题我重现不了

**Comment by Leopoldthecoder** [comment]
如果有问题，请提供 demo 并开一个新 issue。

**Comment by CielNonam** [comment]
在table的column里面设置了fixed之后，table中的去这么设置“  :max-height=“ ‘500’ ”   ”会报错误：
 Error in render: "TypeError: Cannot read property 'length' of null"

但是效果max-height的效果会成功的展示出来

红色警告很刺眼，麻烦解决一下

**Comment by govo** [comment]
问题很好的重现，只2.8.2中复现，table的max-height无法设置，退回2.4.11后一切正常。

**Comment by Sky-Young** [comment]
2.5.4 也有这个问题。
