### ISSUE TITLE
[Bug Report] The Filter menu of table show at wrong place when Click the blank area under the label

### ISSUE THREAD

**Issue by laomu1988** [ElemeFE/element#10300]
### Element UI version
2.2.2

### OS/Browsers version
chrome 65.0.3325.162

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/numLzqzj/3/](https://jsfiddle.net/numLzqzj/3/)

### Steps to reproduce
click at the bottom of fitler td field
点击筛选标签下面空白区域
![image](https://user-images.githubusercontent.com/6356903/37749411-c1d0e5c6-2dc2-11e8-8374-41460f36e853.png)

### What is Expected?
show filter menu at the bottom of the filter td
在筛选标签正下方展示筛选菜单

### What is actually happening?
show filter menu at the middle of table tr
在表格头部中央位置展示的筛选菜单

**Comment by lazycatL** [comment]
同样遇到这个问题，什么时候能解决呀

**Comment by WGL878420** [comment]
没有解决啊  表格多次 v-if  一列的时候  top left 样式还是0
