### ISSUE TITLE
[Feature Request] Update the slider range through inputs 

### ISSUE THREAD

**Issue by diemah77** [ElemeFE/element#10310]
### Existing Component
Yes

### Component Name
Slider

### Description
I'm trying to use the slider (range) with two inputs representing the boundary values:

https://jsfiddle.net/97hodst1/2/

When the input values change I'd like the slider to reflect those changes.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/97hodst1/9/
