### ISSUE TITLE
[Bug Report] el-upload before-remove removes thumbnail

### ISSUE THREAD

**Issue by Chris1904** [ElemeFE/element#10319]
### Element UI version
2.2.2

### OS/Browsers version
Chrome 65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/rfus4udh/](https://jsfiddle.net/rfus4udh/)

### Steps to reproduce
create a simple el-upload component with a "before-remove" attribute. Populate fileList with a few items.

### What is Expected?
Then click on the [x] to remove an upload and the thumbnail will disappear, even though it should stay because the removing of it was canceled.

### What is actually happening?
When [x] is clicked to remove an item and then the process is canceled, the thumbnail will disappear.

**Comment by Leopoldthecoder** [comment]
`$confirm` returns a Promise but your `handleRemove` method is a synchronous function. Making it async would work: https://jsfiddle.net/leopoldthecuber/rfus4udh/6/

**Comment by guohuihot** [comment]
这个方法需要同步的调用还有什么意义，都在异步删除服务器数据后才需要这样，不然也用不到它

**Comment by hongweipeng** [comment]
![image](https://user-images.githubusercontent.com/7546325/67927560-dc1ca400-fbf3-11e9-90f9-16b652f8ff34.png)
我从官网的demo而来。示例上的代码建议更新了。如上讨论的，$confirm 返回个 Promise 使得文件中总是删除。
