### ISSUE TITLE
Dialog组件的两个BUG

### ISSUE THREAD

**Issue by ronankim** [ElemeFE/element#1031]
环境：vue cli创建的初始环境 + vue-resource + vuex + vue-router等，具体环境见下面贴出的package.json
版本：rc8、rc9到当前的正式版均如此
BUG描述：
* dialog右上角的x按了后(或按ecs键)无法关闭，试着隐藏掉右上角的x自己在footer处写了个关闭的btn，调用this.$refs.xxx.close()，依然无法关闭。无法关闭的现象为：只是dialog背面的黑色遮罩层没了，dialog却没能关闭。相似BUG issue：[issue1](https://github.com/ElemeFE/element/issues/970)，[issue2](https://github.com/ElemeFE/element/issues/989)
* dialog内switch控件失效，无法左右开闭

package.json
```
dependencies": {
    "element-ui": "^1.0.0",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.1",
    "vuex": "^2.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.0",
    "babel-core": "^6.0.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.0.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.1.0",
    "css-loader": "^0.25.0",
    "eslint": "^3.7.1",
    "eslint-config-airbnb-base": "^8.0.0",
    "eslint-friendly-formatter": "^2.0.5",
    "eslint-import-resolver-webpack": "^0.6.0",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-html": "^1.3.0",
    "eslint-plugin-import": "^1.16.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.8.1",
    "http-proxy-middleware": "^0.17.2",
    "json-loader": "^0.5.4",
    "opn": "^4.0.2",
    "ora": "^0.3.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.4",
    "url-loader": "^0.5.7",
    "vue-loader": "^9.4.0",
    "vue-style-loader": "^1.0.0",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"
  },
```

**Comment by ronankim** [comment]
另：刚才试了下用this.$refs.dialog.open()打开对话框也会出现问题，仅仅出现黑色背景遮罩层，对话框却没能展示出来

**Comment by Leopoldthecoder** [comment]
第一个问题，应该是因为你没有为 `el-dialog` 指定 `v-model`。以目前版本的实现，通过 `open` 和 `close` 方法打开/关闭 Dialog 也需要绑定`v-model`。已经想到一种方法可以避免，可能会随着下个版本发布。

第二个问题，我这里没有重现，请给出 demo。

**Comment by ronankim** [comment]
@Leopoldthecoder 
1, 我这里试过把dialog中的v-model绑定到vuex的state.visible，父组件通过设置state.visible = true可以让子组件中的dialog出现，但是这个dialog按下x却无法关闭。
2, 我试着把dialog中的v-model绑定到子组件的prop 'visible'上，父组件再给子组件prop双向绑定 :visible=state.visible。父组件通过设置state.visible = true可以让子组件中的dialog正常打开，同样按x也可以关闭了，但是每次操作都会有vue warning，这点很不爽。
3, 有一点我不是很明白为什么要设置v-model才能调用open和close方法？open和close方法调用的目的不正是想避免绑定v-model而直接操作对话框吗。

**Comment by ronankim** [comment]
@Leopoldthecoder 
1, 我这里试过把dialog中的v-model绑定到vuex的state.visible，父组件通过设置state.visible = true可以让子组件中的dialog出现，但是这个dialog按下x却无法关闭。
2, 我试着把dialog中的v-model绑定到子组件的prop 'visible'上，父组件再给子组件prop双向绑定 :visible=state.visible。父组件通过设置state.visible = true可以让子组件中的dialog正常打开，同样按x也可以关闭了，但是每次操作都会有vue warning，这点很不爽。
3, 有一点我不是很明白为什么要设置v-model才能调用open和close方法？open和close方法调用的目的不正是想避免绑定v-model而直接操作对话框吗。

**Comment by ronankim** [comment]
@Leopoldthecoder 
1, 我这里试过把dialog中的v-model绑定到vuex的state.visible，父组件通过设置state.visible = true可以让子组件中的dialog出现，但是这个dialog按下x却无法关闭。
2, 我试着把dialog中的v-model绑定到子组件的prop 'visible'上，父组件再给子组件prop双向绑定 :visible=state.visible。父组件通过设置state.visible = true可以让子组件中的dialog正常打开，同样按x也可以关闭了，但是每次操作都会有vue warning，这点很不爽。
3, 有一点我不是很明白为什么要设置v-model才能调用open和close方法？open和close方法调用的目的不正是想避免绑定v-model而直接操作对话框吗。

**Comment by ronankim** [comment]
@Leopoldthecoder 
1, 我这里试过把dialog中的v-model绑定到vuex的state.visible，父组件通过设置state.visible = true可以让子组件中的dialog出现，但是这个dialog按下x却无法关闭。
2, 我试着把dialog中的v-model绑定到子组件的prop 'visible'上，父组件再给子组件prop双向绑定 :visible=state.visible。父组件通过设置state.visible = true可以让子组件中的dialog正常打开，同样按x也可以关闭了，但是每次操作都会有vue warning，这点很不爽。
3, 有一点我不是很明白为什么要设置v-model才能调用open和close方法？open和close方法调用的目的不正是想避免绑定v-model而直接操作对话框吗。

**Comment by Leopoldthecoder** [comment]
是的，目前 prop 和 vuex 的 state 都是不能直接修改的。为 Dialog 引入 `v-model` ，也是为了解决 Vue 在取消 `.sync` 后子组件的 prop 和父组件中的变量同步的问题。

至于「要设置v-model才能调用open和close方法」，牵涉到 Dialog 内部一个 mixin 的具体实现。我试一下修改这个 mixin，应该可以绕过去。

**Comment by lin-xin** [comment]
请问关闭不了dialog 的问题解决了吗，有指定v-model也是关闭不了啊，我看了好几个问题都没看到解决方法？

**Comment by yelingfeng** [comment]
vuex绑定v-model 确实关闭不了 这问题 我今儿也遇到了 等待修复 close 我也没用明白 v-on:close 这个绑定后也不执行啊

**Comment by Leopoldthecoder** [comment]
今天晚些时候发布 1.0.1 版，可以直接关闭 Dialog 了。
@yelingfeng 想要关闭 Dialog 的话，`close` 不是这样用的。它是一个方法，你这样写的话是指定了关闭之后的回调。正确用法：
```html
<el-dialog ref="dialog"></el-dialog>
```

```javascript
this.$refs.dialog.close()
```

**Comment by yelingfeng** [comment]
@Leopoldthecoder  好的 谢谢 ， 我是按之前API 提供的event猜的 哈， refs的我也试了 不好使嘛 ：）

**Comment by blanklin030** [comment]
el-dialog还有一个bug，嵌套在dialog里的子组件的方法，无法被父组件调用，描述如下：
parent.vue页面：

<template>
<el-button @click="showDialog"></el-button>
<el-dialog v-model="isVisible" :visible.sync="isVisible">
<v-child ref="vChild"></v-child>
</el-dialog>
</template>
<script>
import vChild from "child.vue";
export default {
 components:{
  vComponent
 }
 data(){
  return {
   isVisible:false
  }
 },
methods:{
 showDialog(){
    this.$refs.vChild.test();
  }
}
}
</script>

child.vue页面
<template>
 <div>xxx</div>
</template>
<script>
  export default{
    methods:{
    test(){
      console.log("xxx");
     }
   }
}
</script>

会显示无法调用子组件的test方法
应该是调用dialog时，子组件还没渲染出来，所以它的方法也无法调用
解决方法就是：
调用的时候设置延迟时间
setTimeout(() => {
        this.$refs.vStep.setRow(row);
      }, 0);
