### ISSUE TITLE
[Bug Report] the example of "Number Validate" in the document is wrong

### ISSUE THREAD

**Issue by qidaneix** [ElemeFE/element#10315]
### Element UI version
2.2.2

### OS/Browsers version
any browser

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/kkkr31o6/](https://jsfiddle.net/kkkr31o6/)

### Steps to reproduce
input '1oneoneone'

### What is Expected?
alert "it is not a number"

### What is actually happening?
it is validity

**Comment by qidaneix** [comment]
[element-ui的文档](http://element.eleme.io/#/en-US/component/form#number-validate)一个示例有问题。

输入 ‘123jdfnsd’，会判定为合法的数字。但是并不是。

**Comment by llavre** [comment]
Seems it's globally bug with number validations - #10312 and #10305

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/7945
