### ISSUE TITLE
[Bug Report] Input Number - blank input ignores minimum

### ISSUE THREAD

**Issue by LokiOfNZ** [ElemeFE/element#10312]
### Element UI version
2.2.2

### OS/Browsers version
Windows 10 / Chrome 64

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/6az1fqtt/](https://jsfiddle.net/6az1fqtt/)

### Steps to reproduce
Create an el-input-number with :min="1" and :max="10"

Set value to 1, defocus, result is 1

Set value to 0, defocus, result is 1

Set value to -1, defocus, result is 1

Set value to abc, defocus, result is 1

Set value to " " (ie space), defocus, result is 1

Set value to blank (ie delete all content including blank characters), defocus

### What is Expected?
Result is 1

### What is actually happening?
Result is undefined

**Comment by wacky6** [comment]
This does not appears to be bug. Blank input -> not set the number.

**Comment by Leopoldthecoder** [comment]
This is intended, otherwise if the end user doesn't want to fill out this field, there's no way to make it empty.

**Comment by LokiOfNZ** [comment]
Hmm I see what you're saying, however I suppose I assumed (given out-of-bounds, non-numeric or whitespace input is ignored/set to min) that blank input would also be illegal. Particularly because the +/- controls strongly suggest this is a integer only control and give no way to set a blank input. It's certainly not obvious to the end user that they can choose not to fill out this field, particularly because initialising the bound value to null sets the control to min; https://jsfiddle.net/6az1fqtt/2/

I can see the use case where the dev wants the end user to be able to set blank value, however I would suggest given the look and feel of the control that the more common use case would be where the dev wants the end user to choose value between min and max ONLY and blank input is simply illogical (eg Please specify your salary).

Perhaps a optional prop defining the behaviour on blank input that then allows for both use cases would be useful?

**Comment by wacky6** [comment]
In that case, try Slider component. Or write a validator(if you use a form).
NumberInput is designed to be a generic number, it is not limited to integer, +/- can have a step of 0.1.

**Comment by LokiOfNZ** [comment]
I'm happy to accept blank input is allowable on this control (ie as intended) 
However just to point out ;

- I don't think slider would be an appropriate replacement in all (or most situations) as slider displays the entire range (think salary, most people would be selecting a value around the average salary while some people would have a value 10 times that, so slider becomes too fiddly at the lower end for 99% of users).
- Also, oddly, when setting slider to show-input a very very similar number input control appears, and setting blank value on that sets the slider value to min (very oddly only on the first time, if you then blank out the auto-set min value again it then sets the bound value to null.) https://jsfiddle.net/rgsvwqph/1/
- I also don't think a validator is appropriate either, as other illegal input isn't validated but simply ignored. 

I've ended up setting a watcher that sets the value back to min if blank is entered, however this doesn't update the displayed value in the control. The logic doesn't break as the bound value is not null but the display isn't quite right.
