### ISSUE TITLE
[Bug Report] Unable to Set Current Activated MenuItem After Updating Menu's Children

### ISSUE THREAD

**Issue by Kris-Lee-SH** [ElemeFE/element#10324]
### Element UI version
2.2.2

### OS/Browsers version
all

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/KrisLeeSH/mmx38qxw/869/](https://jsfiddle.net/KrisLeeSH/mmx38qxw/869/)

### Steps to reproduce
In the reference page, every time u click the navigation will active the first leaf menu of the aside menu

1. click '一级 1', see current activated menu and the DEBUGS INFOS, or the console log
2. click '一级 2', see current activated menu and the DEBUGS INFOS, or the console log
3. click '一级 3', see current activated menu and the DEBUGS INFOS, or the console log

### What is Expected?
The current activated menu could be set properly.

### What is actually happening?
It lose the correct way to show the correct aside menu and current activated menu-item.

**Comment by Leopoldthecoder** [comment]
- Add `key` on `<el-menu-item>`
- Execute `menuData` watcher in the `nextTick` to ensure the menu items are actually created
- Use `$set` when writing new props to an object

https://jsfiddle.net/leopoldthecuber/mmx38qxw/880/

**Comment by Kris-Lee-SH** [comment]
Leopoldthecoder’s reply helps a lot. Thanks
