### ISSUE TITLE
[Feature Request] Add option to change plus/minus symbols for InputNumber

### ISSUE THREAD

**Issue by jpcaparas** [ElemeFE/element#10320]
### Existing Component
Yes

### Component Name
InputNumber

### Description
Hi there,

It would be nice to have the ability to change the plus/minus symbols to something else for the InputNumber component. 

In our situation, we'd like to have the ability to change the plus/minus symbols into left/right arrows, respectively.

Looking forward to hearing from you soon.

Thanks,
JP

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
