### ISSUE TITLE
[Feature Request] Provides a way of removing duplicate Message

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#10322]
### Existing Component
Yes

### Component Name
Message

### Description
I hope have a way to show only one Message in a short time  
eg: 
a page have lots of child component with themselves http request

**Comment by wacky6** [comment]
Wrap `$message` method and check onClose callback?

**Comment by Leopoldthecoder** [comment]
Maybe like this: https://jsfiddle.net/leopoldthecuber/eb2ra3pk/10/
