### ISSUE TITLE
[Bug Report] In IE11, the MessageBox pop-up box is clicked to confirm

### ISSUE THREAD

**Issue by lily-elephant** [ElemeFE/element#10327]
### Element UI version
2.2.1

### OS/Browsers version
IE11

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/LilyEle/mmx38qxw/885/](https://jsfiddle.net/LilyEle/mmx38qxw/885/)

### Steps to reproduce
在IE11或者360（兼容模式）下，多测试几次，弹框点击确定按钮消失以后，会有二次闪现问题

### What is Expected?
点击确定按钮，关闭弹窗，不要二次闪现弹窗

### What is actually happening?
实际上，在IE11下或者360（兼容模式），弹框有时候会二次闪现，公司测试提出bug

**Comment by lily-elephant** [comment]
经过实际测试，elementUI官网上的demo在IE11上也会有这个问题

**Comment by lily-elephant** [comment]
elementUI前端开发者能否回应下这个问题？

**Comment by lily-elephant** [comment]
elementUI的前端能否回应下这个问题？在IE11（360兼容模式），弹框体验不太友好啊

**Comment by ziyoung** [comment]
无法重现。
下面是我本地的测试结果。
![msgbox](https://user-images.githubusercontent.com/12947422/40235391-b39a3ab0-5adc-11e8-90ed-20e23443b57a.gif)
