### ISSUE TITLE
[Feature Request] I want to add Settings for the Tree component to

### ISSUE THREAD

**Issue by mgss** [ElemeFE/element#10323]
### Existing Component
是

### Component Name
El-Tree

### Description
I want to add Settings for the Tree component to expand and close events. For example, setCheckedKeys() or setCheckedNodes(). I don't know if anyone else has the same needs as me. 
Thanks.

**Comment by Leopoldthecoder** [comment]
没太明白，请用中文描述。

**Comment by Leopoldthecoder** [comment]
示例：https://jsfiddle.net/leopoldthecuber/j5999vwo/3/
如果有更多用户需要，我们会考虑将方法写进文档。
