### ISSUE TITLE
[Bug Report] Steps border color is not a setting color

### ISSUE THREAD

**Issue by GeunHeeKim** [ElemeFE/element#10333]
### Element UI version
2.2.0

### OS/Browsers version
mac / 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/890/](https://jsfiddle.net/mmx38qxw/890/)

### Steps to reproduce
Check steps border color (#c0c4cc).

### What is Expected?
steps border color is  #e4e7ed( $--disabled-border-base = $--border-color-light in element-variables.scss) 

### What is actually happening?
steps border color is #c0c4cc.
I wonder why steps border color is not #e4e7ed but #c0c4cc.
I did not set border-color-light to #c0c4cc
.
p.s = my develop environment is NUXT.

**Comment by Leopoldthecoder** [comment]
Because the border color is not `$--disabled-border-base`: https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/step.scss#L36

**Comment by GeunHeeKim** [comment]
Thank you for quick response.
In "element-variables.scss" file > Steps section > `$--steps-border-color: $--disabled-border-base !default;`
I thought `$--steps-border-color` is steps border color.
If it is not, `$--steps-border-color` is what for?
