### ISSUE TITLE
[Feature Request] Remove margin and padding of form label

### ISSUE THREAD

**Issue by thibaultvanluchene** [ElemeFE/element#10334]
### Existing Component
Yes

### Component Name
el-form-item

### Description
I would like to know if it's possible to somehow remove margin and padding off a form label using the style tags of a Vue component. 
When using the .el-form-item__label class in the style of the Vue component it doens't work, however when I do it in style tags on the index page it works.

**Comment by Leopoldthecoder** [comment]
See the `Deep Selectors` section in https://vue-loader.vuejs.org/en/features/scoped-css.html , or simply remove `scoped` from the style tag of you .vue file.
