### ISSUE TITLE
[Bug Report] adds the white-space:nowrap style in the form of elements in a column, the column text will exceed the column width

### ISSUE THREAD

**Issue by fabin5** [ElemeFE/element#10339]
### Element UI version
2.2.2

### OS/Browsers version
macOS / Safari 11.0.1

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/fabin5/ndg7mtuz/](https://jsfiddle.net/fabin5/ndg7mtuz/)

### Steps to reproduce
1、为el-table-column设置width
2、在el-table-column中添加一个span，将其样式设置为display:inline-block; white-space:nowrap
3、span中的文字很长

### What is Expected?
将el-table-column中的文字超出width部分隐藏

### What is actually happening?
文字超出列宽，未将其隐藏

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ndg7mtuz/5/

**Comment by lin-hun** [comment]
这样做之后
1.内容和表头没对齐（原因是element table里有边距）
2.设过宽度了,但是还得对标签重设max-width

希望：能在element 内部解决这个样式
