### ISSUE TITLE
[Bug Report] Uncaught TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Demon-HY** [ElemeFE/element#10344]
### Element UI version
2.2.2

### OS/Browsers version
 65.0.3325.162 chrome

### Vue version
2.5.2

### Reproduction Link
[https://github.com/Demon-HY/ControlSituation/tree/master/web/ControlSituationWeb](https://github.com/Demon-HY/ControlSituation/tree/master/web/ControlSituationWeb)

### Steps to reproduce
# main.js
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
Vue.use(ElementUI);
Vue.$message.error('test');

### What is Expected?
run ok

### What is actually happening?
Error: Uncaught TypeError: Cannot read property 'error' of undefined

**Comment by Leopoldthecoder** [comment]
Vue.prototype.$message.error('test')

**Comment by Demon-HY** [comment]
Can not be accessed through Vue.$message.error('test')?

**Comment by Leopoldthecoder** [comment]
No you can't. Because it's registered on Vue.prototype.

**Comment by Demon-HY** [comment]
why? There is no annotation on the document. http://element.eleme.io/#/zh-CN/component/quickstart

**Comment by Leopoldthecoder** [comment]
> Because it's registered on Vue.prototype

![image](https://user-images.githubusercontent.com/10095631/37863440-5b146b5e-2f99-11e8-811b-3a6f79d7ed33.png)

**Comment by Demon-HY** [comment]
thank you!
