### ISSUE TITLE
[Bug Report] date-picker empty ID error

### ISSUE THREAD

**Issue by viewweiwu** [ElemeFE/element#10349]
### Element UI version
2.2.2

### OS/Browsers version
win10 chrome 65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/urp2xuhc/2/](https://jsfiddle.net/urp2xuhc/2/)

### Steps to reproduce
当 type='password' 的 input 存在时，
如果另外有重复 id 的 input 存在时，chrome 会报错,
chrome 的标准最后一条：https://goo.gl/9p2vKq
Web browsers are designed with the HTML specification in mind, and going against it can lead to unexpected issues with your web page. This means:
Element id attributes should be unique: no two elements should have the same id.

### What is Expected?
datepicker 不要添加一个空的 id 在标签上

### What is actually happening?
没有设置 datepicker  的 id 时，会有一个空的 id 在标签上

**Comment by Leopoldthecoder** [comment]
Fixed in #10360
