### ISSUE TITLE
[Bug Report] pagination font-size default is 13px

### ISSUE THREAD

**Issue by kuangyazhou** [ElemeFE/element#10355]
### Element UI version
2.2.2

### OS/Browsers version
chrome 65

### Vue version
2.5.0

### Reproduction Link
[https://github.com/kuangyazhou/BTC](https://github.com/kuangyazhou/BTC)

### Steps to reproduce
分页器默认字体为13px chrome上显示效果不佳，mac上区别更明显

### What is Expected?
分页器默认font-size改为12px或者14px

### What is actually happening?
.el-pager li font-size:13px;

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/37883823-4725e338-30df-11e8-8709-e92a2f84af34.png)

未见效果不佳。设计就是如此，如果有问题请自行覆盖 CSS。
