### ISSUE TITLE
[Bug Report] Layout Container does not expand on the screen

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#10354]
### Element UI version
2.2.2

### OS/Browsers version
Chrome 65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/kutmania/kzskzth9/1/](https://jsfiddle.net/kutmania/kzskzth9/1/)

### Steps to reproduce
Copy the layout code Container with css and javascript

### What is Expected?
Let the template fill the entire screen expanding.

### What is actually happening?
I've been working on this for two days. When copying the Container layout the dimensions are small.
I need a starting point to start building my administrative panel.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/kzskzth9/3/
