### ISSUE TITLE
The [Bug Report] Popover pop-up box component, which is not available in [Table].

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#10350]
### Element UI version
2.2.2

### OS/Browsers version
win10/版本 65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/9xyu31Ld/1/](https://jsfiddle.net/9xyu31Ld/1/)

### Steps to reproduce
详情见重现链接。

### What is Expected?
能正常使用。

### What is actually happening?
未作出期待的反馈。

**Comment by Leopoldthecoder** [comment]
与组件渲染顺序有关，Element 这边没什么好办法。另外，即使能够渲染，Popover 也不支持与多个以指令方式创建的元素绑定，即这个 Popover 只能被最后一行的 Button 触发。建议改写：https://jsfiddle.net/leopoldthecuber/9xyu31Ld/3/
