### ISSUE TITLE
[Feature Request] Select is expected to support the quick select choice and empty

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#10357]
### Existing Component
Yes

### Component Name
Select选择器

### Description
Select下拉多选时希望可以支持快捷全选和清空。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/47oLy5Lb/3/

**Comment by wacky6** [comment]
@Leopoldthecoder 要不要在文档里说一下这个用法？或者新加一个slot？

**Comment by Leopoldthecoder** [comment]
@wacky6 觉得在文档里加例子有些怪怪的。本质上就是利用了默认 slot，这个对于 Vue 用户来说应该是比较自然的。可能只是因为会有一个弹出框夹在中间，模板 => 渲染结果的映射关系没有那么清晰。比如拿 Form 来说，它的子组件除了文档例子写明的 `<el-form-item>` 以外，很多用户都会很自然地放一些 `el-row` 进去，其实和 Select 的道理是一样的。

**Comment by wacky6** [comment]
有道理。但是我查了一下原生select，它里面只允许option和optgroup。
vue确实没这个限制，但是如果是从原生转过来的话在select里放别的东西感觉不是那么自然的能想到？

**Comment by Leopoldthecoder** [comment]
倒也是。我在文档上补充一个例子吧。
