### ISSUE TITLE
[Feature Request] Cascader cascade selector (selection change) optimization suggestion

### ISSUE THREAD

**Issue by Evil-S** [ElemeFE/element#10369]
### Existing Component
是

### Component Name
Cascader 级联选择器

### Description
Cascader 级联选择器选择及改变功能使用起来有不方便的地方：只能通过点击最后一级才会自动关闭，当我只想选择前几级的时候，需要去点击选择框外去关闭且用hover去展开时容易误选择。
建议提供点击事件（主动关闭选择框）以做到通过hover去展开子节点，通过点击选中并关闭选择框，使得cascader控件的使用更加的灵活。

**Comment by Leopoldthecoder** [comment]
Duplicate of #9851
