### ISSUE TITLE
[Bug Report] ElSelect组件使用远程搜索（remote）与多选(multiple)时，tag标签会显示为value值

### ISSUE THREAD

**Issue by ZhanYishu** [ElemeFE/element#10366]
### Element UI version
2.0.11

### OS/Browsers version
mac

### Vue version
2.5.9

### Steps to reproduce
1、选中随便几条数据
2、继续搜索不同关键词，后端返回新的选项集合
3、之前已选的数据会显示出另外的选项
4、继续选中时，之前选项变为value值
![image](https://user-images.githubusercontent.com/22268690/37894217-1d9ecba2-3110-11e8-8a45-5ee883f7f6f9.png)

### What is Expected?
继续搜索不同关键词之前已选选项能够正确的显示label值
看了源码是cachedOptions没有缓存下来，每次搜索关键词获取到新的选项时cachedOptions会被重置为新的options，而之前已选的选项每次都会重新渲染，造成找不到对应label值

### What is actually happening?
1、搜索不同关键词之前已选选项显示为不同的选项
2、继续点击选中数据，之前的选项变为value值

**Comment by fengyun2** [comment]
我的直接报错了

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
