### ISSUE TITLE
Cascader 级联选择器选择即改变方式优化建议

### ISSUE THREAD

**Issue by Evil-S** [ElemeFE/element#10368]
Cascader 级联选择器选择及改变功能使用起来有不方便的地方：只能通过点击最后一级才会自动关闭，当我只想选择前几级的时候，需要去点击选择框外去关闭且用hover去展开时容易误选择。
建议提供点击事件（主动关闭选择框）以做到通过hover去展开子节点，通过点击选中并关闭选择框，使得cascader控件的使用更加的灵活。

**Comment by wzwxwc** [comment]
这个社区能不能多关注人家的问题，而不是以格式不对就敷衍了事，不管不问了啊！！
