### ISSUE TITLE
[Bug Report] Display error when el-input using slot="append(or prepend)" in Chrome

### ISSUE THREAD

**Issue by MessiLiu** [ElemeFE/element#10365]
### Element UI version
2.2.2

### OS/Browsers version
Windows 7 x64 / Chrome 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/liuyuan/2m53badL/](https://jsfiddle.net/liuyuan/2m53badL/)

### Steps to reproduce
See reproduction link.

### What is Expected?
An el-input should always be centered with the label of the outer el-form-item component.

### What is actually happening?
When the el-input component is in the el-form-item component, and the el-form-item component has the label attribute, and the el-input component using slot="append(or prepend)". The label of the el-form-item component and the el-input component will not be horizontally centered in Google Chrome, but it's well in IE11.

**Comment by Leopoldthecoder** [comment]
Fixed in #10189
