### ISSUE TITLE
element 确定支持ie9吗？？在ie9上有很多问题啊，都是样式的问题

### ISSUE THREAD

**Issue by chenzhe-pro** [ElemeFE/element#1037]
hi～ 我看到主页上写的是ie9+，那应该是能支持ie9的吧，但是我测试后发现element在ie9上又很多样式上的问题，看代码发现样式大部分使用css3的地方都是没有做兼容性的处理。
支持element，真心期待下个版本这方面能有优化～～～
下面给几个截图：
代码未对ms-transform做兼容
<img width="1231" alt="default" src="https://cloud.githubusercontent.com/assets/12438085/20245678/45da33b6-a9e1-11e6-9c62-382f3c15b604.png">

<img width="406" alt="default" src="https://cloud.githubusercontent.com/assets/12438085/20245565/de01afd2-a9de-11e6-970c-e23a5a387fee.png">
<img width="393" alt="badge" src="https://cloud.githubusercontent.com/assets/12438085/20245566/e4eb2314-a9de-11e6-9458-7703d700f2df.png">
<img width="632" alt="slider" src="https://cloud.githubusercontent.com/assets/12438085/20245567/ec675220-a9de-11e6-836a-b574a3c22535.png">
<img width="434" alt="default" src="https://cloud.githubusercontent.com/assets/12438085/20245569/f2a0907a-a9de-11e6-88d3-2af264b456b5.png">
<img width="271" alt="default" src="https://cloud.githubusercontent.com/assets/12438085/20245570/f762ece8-a9de-11e6-8e27-614374d53f79.png">

**Comment by QingWei-Li** [comment]
官网由于样式文件是压缩后的，css-loader 的压缩用的是 cssnano，里面默认会[把 `unnecessary prefixes` 给移除](http://cssnano.co/optimisations/autoprefixer/)，所以 `-ms-` 就被压缩掉了。`css-loader` 已经将它默认设置为关闭 https://github.com/webpack/css-loader/issues/369 ，但是还没有发新版。如果你自己使用的话，用 autoprefixer 自己把前缀补上就好了。

**Comment by hbrls** [comment]
css-loader 也可以传配置进去

    css?{ "safe": true , "autoprefixer": { "add": true, "browsers": ["IE >= 8"] }}

**Comment by 540692039** [comment]
> css-loader 也可以传配置进去
> 
> ```
> css?{ "safe": true , "autoprefixer": { "add": true, "browsers": ["IE >= 8"] }}
> ```

老哥麻烦能给贴一下配置位置吗……谢谢     我这自己的组件autoprefixer能正常加-ms-前缀，element的样式就没有加前缀。
