### ISSUE TITLE
[Bug Report] el-select default value not work when active value is number 

### ISSUE THREAD

**Issue by dongwenting** [ElemeFE/element#10375]
### Element UI version
2.2.1

### OS/Browsers version
windows chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/928/](https://jsfiddle.net/mmx38qxw/928/)

### Steps to reproduce
click run

### What is Expected?
el-select should select yes, not no

### What is actually happening?
el-select should select yes, not no

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/934/

**Comment by dongwenting** [comment]
我从后台返回的数据就是integer的，难道要一个个全部转换成string吗

**Comment by dongwenting** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
那就改 `active-value` 和 `inactive-value`：https://jsfiddle.net/leopoldthecuber/mmx38qxw/935/

**Comment by dongwenting** [comment]
@Leopoldthecoder  非常感谢，原来关键是active-value和inactive-value前面必须加冒号。
