### ISSUE TITLE
[Feature Request] Masked Input

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#10377]
### Element UI version
2.2.2

### OS/Browsers version
Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[http://jsfiddle.net/igorescobar/6pco4om7/](http://jsfiddle.net/igorescobar/6pco4om7/)

### Steps to reproduce
There is not

### What is Expected?
when you type text in a text field the text is masked.

(xx) xxxx-xxxx

### What is actually happening?
Sorry, because I know that here is not the best place to ask that.
I have already researched and noted that element does not support this.
I can use another external mask library?? Do you have an example?
I just need this functionality to start building using the element

**Comment by omerciftcibasi** [comment]
Need additional text features too. Such as:
- Uppercase,
- length restriction,
- etc...
