### ISSUE TITLE
[Bug Report] Version upgrade causes webpack to slow down (2.2.1=>2.2.2)

### ISSUE THREAD

**Issue by Nick-Tsao** [ElemeFE/element#10380]
### Element UI version
2.2.2

### OS/Browsers version
MAC 10.13.3/chome 64.0.32

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/no-connection/sorry](https://jsfiddle.net/no-connection/sorry)

### Steps to reproduce
2.2.2 Version compile Theme files (theme.scss)   eight times slower  than  2.2.1

### What is Expected?
repair 2.2.2  Slow compilation.

### What is actually happening?
2.2.1 takes 0.4 seconds to compile time.
2.2.2 takes 8 seconds to compile time.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by miracledan** [comment]
@Leopoldthecoder 这个问题是存在的。我这边可以复现。
mac上使用webpack构建electron-vue项目，开启热更新。
并且使用了element自定义scss
```
$--button-mini-padding-vertical: 3px;
$--button-mini-padding-horizontal: 6px;

/* 改变 icon 字体路径变量，必需 */
$--font-path: '~element-ui/lib/theme-chalk/fonts';

@import "~element-ui/packages/theme-chalk/src/index";

.el-date-editor.el-range-editor.el-input__inner.el-date-editor--daterange.el-range-editor--mini {
  width: 240px;
  padding: 3px 5px;
  .el-range-input {
    width: 80px;
  }
}
```
修改代码，触发项目热更新。element-ui 2.2.1版本与2.3.6版本的执行时间差异较大。
element-ui@2.2.1版本：需要1.4s
![2.2.1版本](https://user-images.githubusercontent.com/7239657/39394845-67fab7ac-4b09-11e8-8902-13efcfac066f.png)

element-ui@2.3.6版本：需要7s
![2.3.6版本](https://user-images.githubusercontent.com/7239657/39394810-0cb5d1d8-4b09-11e8-82c5-f0b6471e9e3c.png)

因为是私有项目，所以不太好给出复现的链接。
麻烦看一下，新版本的scss是不是有所改动，在使用时要注意什么才不会导致编译时间变长。
