### ISSUE TITLE
[Feature Request] Hope to set default value in cell while the value

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#10385]
### Existing Component
是

### Component Name
Table

### Description
1.Table Attributes： 能够设置整个表格的单元格默认文案(当某个值为空时)
2.Table-column Attributes ：能够设置具体某一列单元格的默认文案(当某个值为空时)
例如:
<el-table :data="data"  default-text="--">
  <el-table-column prop="id" label="ID"></el-table-column>
  <el-table-column prop="name" label="名称" default-text="暂无名称"></el-table-column>
</el-table>

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can use `formatter` to return a fallback.
