### ISSUE TITLE
[Feature Request] Spacing Utilities

### ISSUE THREAD

**Issue by raphaelsaunier** [ElemeFE/element#10386]
### Existing Component
No

### Component Name
Layout

### Description
Element UI already provides utilities to control the horizontal layout of elements as well as their visibility, but doesn't offer any tools to control the vertical spacing.

It would be nice to also have a set of spacing utilities similar to what Bootstrap 4 is offering https://getbootstrap.com/docs/4.0/utilities/spacing/ to control adjust the spacing (margin & padding) of elements.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by kurucu** [comment]
In addition to layout - it would be useful to have helper utilities for spacing around cards and other items.

**Comment by raphaelsaunier** [comment]
I ended up solving this by including [`tachyons-spacing`](https://www.npmjs.com/package/tachyons-spacing), a lightweight CSS lib which provides a set of responsive padding/margin helpers.

Docs: http://tachyons.io/docs/layout/spacing/
