### ISSUE TITLE
[Feature Request] Handle click events for autocomplete results

### ISSUE THREAD

**Issue by Yorgovan** [ElemeFE/element#10383]
### Existing Component
Yes

### Component Name
Autocomplete

### Description
At the moment there is @select event for autocomplete but I need to handle middle click with it so I can open new tab.
Is there a way to listen for all click types or keypress on autocomplete results?

**Comment by Leopoldthecoder** [comment]
You can write your own suggestion item template to handle events: https://jsfiddle.net/leopoldthecuber/vhm7cups/1/ .
