### ISSUE TITLE
[Bug Report] table's show-overflow-tooltip property doesn't work when columns created by V-for

### ISSUE THREAD

**Issue by hb2md** [ElemeFE/element#10393]
### Element UI version
2.0.8

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
table's show-overflow-tooltip property doesn't work when columns created by v-for

### What is Expected?
使用  v-for  产生 table 的 column ，使用show-overflow-tooltip 属性 正常应该在数据超出cell宽度时候显示tooltip
<el-table-column
                                v-for = "col in columns"
                                :key="col.prop"
                                :prop = "col.prop.toUpperCase()"
                                :label = "col.label"
                                show-overflow-tooltip >

### What is actually happening?
使用  v-for  产生 table 的 column ，使用show-overflow-tooltip 属性 不生效

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
