### ISSUE TITLE
When the table is nested in [Feature Request] dialog, the first open can not get the table instance.

### ISSUE THREAD

**Issue by morelearn1990** [ElemeFE/element#10399]
### Existing Component
是

### Component Name
dialog

### Description
dialog 里面嵌套 table ，我这而需要在点开 dialog 时，能够触发 table 的实例方法 toggleRowSelection 。但是，好像 dialog 第一次打开时是实时渲染 dialog 组件 body 里面内容，所以第一次打开时没法通过 $refs 获取 table 的实例。

**Comment by Leopoldthecoder** [comment]
在 Dialog 的 `open` 事件回调里做。

**Comment by morelearn1990** [comment]
试过了，没用，还是拿不到。我查看了 element dialog 的源码，open 这个事件回调函数是在 rendered 之前就触发了，应该在渲染完成触发一个 opened 我才能获取到里面的 table 组件实例

**Comment by morelearn1990** [comment]
我这是需要重新提个 issue 么？还是这儿回答也能看得见？

**Comment by Leopoldthecoder** [comment]
写个 demo。

**Comment by wacky6** [comment]
https://jsfiddle.net/hLvyv61w/ 
`$nextTick` 等 DOM 更新了再获取 refs

**Comment by morelearn1990** [comment]
谢谢，忘记还有这个 api 了
