### ISSUE TITLE
[Bug Report] Form表单输入框后面增加<template slot="append">.com</template>时，label和输入框的布局错了，label不会居中，直接置顶了

### ISSUE THREAD

**Issue by xiaofengleiyu** [ElemeFE/element#10397]
### Element UI version
2.2.2

### OS/Browsers version
WIN7/谷歌

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/ac8kac9o/1/](https://jsfiddle.net/ac8kac9o/1/)

### Steps to reproduce
Form表单输入框后面增加<template slot="append">.com</template>时，label和输入框的布局错了，label不会居中，直接置顶了

### What is Expected?
布局保持不变

### What is actually happening?
label不会居中，直接置顶了

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/10189
