### ISSUE TITLE
[Feature Request] hope to provide a way to set activeIndex with propp

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#10395]
### Existing Component
Yes

### Component Name
NavMenu

### Description
menu item active state is invalid if dynamic change menu item options  
default-active is been used when first time render active state only  
hope to allow that set active index with props as a form

**Comment by Leopoldthecoder** [comment]
Actually now `default-active` is reactive: https://jsfiddle.net/leopoldthecuber/kep375gj/2/
