### ISSUE TITLE
[Feature Request] routing keepalive A page pop-up dialog box click button to enter the B page, the B page has a mask

### ISSUE THREAD

**Issue by zmhuahua** [ElemeFE/element#10392]
### Existing Component
是

### Component Name
dialog

### Description
使用场景
主页面弹出对话框显示会员列表，子项按钮充值进入充值页面，会出现遮罩。
可否让遮罩可以选择在实例里面显示，另外append to body是否也可以类似可选择

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
