### ISSUE TITLE
[Bug Report] input组件使用$attr后 type="password"无效

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#10407]
### Element UI version
2.3.0

### OS/Browsers version
osx chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/jh0r0jkj/1/](https://jsfiddle.net/jh0r0jkj/1/)

### Steps to reproduce
文本框输入内容未用*隐藏

prop type和input 原生type冲突，$attr未能传入type="password"

### What is Expected?
密码输入框有效

### What is actually happening?
密码输入框无效

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/10415/commits/3a086ee51595bb661440862a8883c7bc8b32cabf

**Comment by zhumeisongsong** [comment]
在新的release来之前 我只能用原生input么？
