### ISSUE TITLE
[Bug Report] is configured with filterable under IE11 and can not enter the content of the filter and press the delete key many times, and the page will jump to the route page. (select of the official network also has this BUG under IE11)

### ISSUE THREAD

**Issue by ruizhou8888** [ElemeFE/element#10403]
### Element UI version
2.2.2

### OS/Browsers version
IE11

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/ruizhou/project/editor/DQbQQa](https://codepen.io/ruizhou/project/editor/DQbQQa)

### Steps to reproduce
1.el-select 配置 filterable 属性；
2.在IE11浏览器下打开，然后在select里尝试输入文字或字母，数字
3.在select获取焦点的情况下 多次按删除键

### What is Expected?
el-select 配置 filterable 属性后能正常输入文字进行搜索，并且多次按删除键不会跳转。（行为应该和谷歌浏览器一样）

### What is actually happening?
el-select 配置 filterable 属性后不能正常输入文字进行搜索，并且多次按删除键页面会跳转至路由首页。（行为和谷歌浏览器不一样）

**Comment by sietzekeuning** [comment]
Got the same issue here. Going back to version 2.0.11 fixed the problem for me.

**Comment by ruizhou8888** [comment]
@sietzekeuning Is there only this solution at the moment?

**Comment by sietzekeuning** [comment]
I think going back a few versions is the quickest solution for now, until there has been a patch addressing this issue.

**Comment by Leopoldthecoder** [comment]
The latest working version is 2.2.0.

I'm still trying to find what causes this.

**Comment by ruizhou8888** [comment]
@Leopoldthecoder 现在有查到问题吗？

**Comment by Leopoldthecoder** [comment]
Try this HTML in IE11:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
</head>
<body>
  <div>
    <input type="text" readonly="true">
  </div>
</body>
<script>
  var div = document.querySelector('div');
  var input = document.querySelector('input');
  div.addEventListener('click', function() {
    if (input.getAttribute('readonly')) {
      input.removeAttribute('readonly');
    } else {
      input.setAttribute('readonly', 'true');
    }
  });
</script>
</html>
```

Just like filterable Select, you cannot type in the input. This may require some hacking.

**Comment by Leopoldthecoder** [comment]
@focusdada Hopefully I'll work around it this weekend.

**Comment by 11120** [comment]
请问官方有解决方案吗？
