### ISSUE TITLE
[Feature Request] el-date-picker（type="daterange"） 是否可以提供一个清空日期的接口（类似于Attributes中clearable的功能）

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#10400]
### Existing Component
是

### Component Name
el-date-picker

### Description
`el-date-picker（type="daterange"）` 是否可以提供一个清空日期的接口（类似于Attributes中clearable的功能），某些情况下需要手动清空日期。而直接对 `el-date-picker（type="daterange"）` 的 `v-model` 设置为空数组，再次打开日期面板，里面的日期还是处于高亮状态。
![image](https://user-images.githubusercontent.com/8147202/38014814-805ed0ec-329c-11e8-860b-74e842f1a82f.png)

**Comment by wacky6** [comment]
清空需要设置为值null

**Comment by Leopoldthecoder** [comment]
试了一下，并没有保持高亮：https://jsfiddle.net/leopoldthecuber/83n25oom/2/

**Comment by fengyun2** [comment]
@wacky6 我设置为空字符串('')了

**Comment by fengyun2** [comment]
@Leopoldthecoder https://jsfiddle.net 在国内不稳定，经常打不开，就算连上了vpn也是这种情况。

**Comment by Leopoldthecoder** [comment]
你的链接是空的，没保存。我的例子的动图：

![untitled1](https://user-images.githubusercontent.com/10095631/38128331-b6fe4cea-342c-11e8-8ee7-8809f8916998.gif)

设置成空数组是没问题的。

**Comment by fengyun2** [comment]
@Leopoldthecoder https://codesandbox.io/s/5zvovj9l4，
![image](https://user-images.githubusercontent.com/8147202/38131081-3359513a-3438-11e8-85cd-739a6f8bb0ed.png)
