### ISSUE TITLE
Whether the isLeaf property of the [Feature Request] Tree component can be used in non lazy mode

### ISSUE THREAD

**Issue by xugege** [ElemeFE/element#10402]
### Existing Component
是

### Component Name
Tree

### Description
Tree组件的isLeaf属性必须是在lazy=true下才能使用，这个局限太大了，不能完全交给用户去控制

**Comment by Leopoldthecoder** [comment]
对于非 lazy 情况，所有数据都已经拿到了，每个节点是否为叶子节点是确定的。

**Comment by xugege** [comment]
有时候业务时非常复杂的，我现在的这个场景
两部分数据
1.一个单位的组织机构，有个2百多条数据，可以一次性加载，结合tree的filterNode实用性很强
2.每个组织机构下有人员，人员总共有6千多条数据，只能在展开机构时去加载数据。

现在我基于eleme的tree基本实现了功能，只是叶子机构不能显示展开图标

**Comment by Emiya0306** [comment]
+1，isLeaf应该可以交由用户去控制。试想一下如果是文件夹结构，那么如果这个文件夹下面没有文件，那么下拉箭头难道可以去掉么？对业务来讲，这是显然**不正确**的。

合理的做法是：当用户没有设置isLeaf的时候，element-Tree组件去判断他是不是leaf；如果当用户设置了isLeaf，则依照用户的设置，去显示是不是leaf。
