### ISSUE TITLE
在谷歌浏览器65.0.3325.146版本表格不对齐问题

### ISSUE THREAD

**Issue by theLaowang** [ElemeFE/element#10410]
![image](https://user-images.githubusercontent.com/25023344/38018172-b7fcf4fc-32a6-11e8-87f8-ae47da280969.png)

**Comment by theLaowang** [comment]
![image](https://user-images.githubusercontent.com/25023344/38018217-d9df54a2-32a6-11e8-8bc8-ba5b9f4af46a.png)
在官网也是会有这个问题

**Comment by zh68319220** [comment]
@theLaowang 
![image](https://user-images.githubusercontent.com/13728178/38020267-5a84fca6-32ac-11e8-8dfd-683574a2b5b4.png)
如果你的操作系统是windows10的话，如果将上图缩放与布局设置成125，就会出现上面的问题，100%的时候显示正常

**Comment by theLaowang** [comment]
Thanks!

**Comment by wangxueyou110** [comment]
老版本是好的，请问可以支持下吗

**Comment by wangxueyou110** [comment]
[我调了100%，怎么还是有错位
![image](https://user-images.githubusercontent.com/30291910/38465965-94337d50-3b54-11e8-919e-7bdc4f1a4417.png)
