### ISSUE TITLE
Active-bar length is inaccurate after the [Bug Report] tabs component overrides the style of the.El-tabs__item

### ISSUE THREAD

**Issue by santiaomaojin** [ElemeFE/element#10414]
### Element UI version
2.2.2

### OS/Browsers version
mac10.13.3 (17D47)/chorme65

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/santiaomaojin/9j5p76y1/](https://jsfiddle.net/santiaomaojin/9j5p76y1/)

### Steps to reproduce
  .el-tabs__item {
    padding: 0 5px
  }
进行样式覆盖后，tab切换观察active-bar

### What is Expected?
可以通过element-theme自定义主题更改选项之间的间距或样式覆盖后active-bar的宽度正确计算

### What is actually happening?
active-bar的宽度不正确，element-ui 1.13版本时没问题的

**Comment by romyatziv** [comment]
I'm also having considerable trouble getting the active bar to calculate correctly after modifying the tabs to have the precise padding and margin that we need.
