### ISSUE TITLE
[Bug Report] timepicker value-format="HH:mm A" Can't choose After 1pm

### ISSUE THREAD

**Issue by stevieyu** [ElemeFE/element#10412]
### Element UI version
2.3.0

### OS/Browsers version
最新

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/dugujianxiao/jkwu323b/26/](https://jsfiddle.net/dugujianxiao/jkwu323b/26/)

### Steps to reproduce
timepicker value-format="HH:mm A"  选择不了下午1点之后的时间

### What is Expected?
可以选择下午1点之后的时间

### What is actually happening?
选择不了下午1点之后的时间

**Comment by wacky6** [comment]
24小时制不能和AM/PM混用吧。https://jsfiddle.net/j8gxy6L7/
