### ISSUE TITLE
请问有计划增加contextmenu组件吗?

### ISSUE THREAD

**Issue by dbskccc** [ElemeFE/element#1041]
有不少地方用右键菜单感觉还是方便的,目前是树型控件上的node操作需要用到

**Comment by yelingfeng** [comment]
同求

**Comment by Leopoldthecoder** [comment]
没有增加这个组件的计划。

**Comment by PLQin** [comment]
@yelingfeng 
@dbskccc 

建议参考: 
[ElementUi] 需要实现 `tree`组件上右键弹出菜单并且 `获得 tree node的id值` - Starch的回答 - SegmentFault
https://segmentfault.com/q/1010000012940760/a-1020000012955488
