### ISSUE TITLE
[Bug Report] Component Upload on-success event issue (ASAP?)

### ISSUE THREAD

**Issue by LG0012** [ElemeFE/element#10425]
### Element UI version
2.3.0

### OS/Browsers version
Windows 10 64bit / Chrome 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/4y64kods/5/](https://jsfiddle.net/4y64kods/5/)

### Steps to reproduce
Select few images and try to upload. And you will see that you are getting x times depending on how many files you are selected. With the same fileList.
What if i need only one event response with the fileList and then map all promises?

### What is Expected?
How can I map all file responses in Promise.all, then fire up the even, when the all uploading processes are completed and get the response with sucessfully uploaded files?

### What is actually happening?
Why success event triggers each time depending how many files im trying to upload (multiple = true)?
Where is the event with response with uploaded files? I mean event which will fire only after after all responses are getted from all uploading files?

**Comment by yitianzhuan** [comment]
element ui does not support get all responses  when all files upload over, it upload files one by one， and return response for every file。
but you can put all response in a array

**Comment by LG0012** [comment]
Thanks for reply, I ended up with this solution - https://prnt.sc/ixp6hh

On each success event response we get uploading file list, what we need to do is just need to wait untill we get all response from each on of them, then we can execute the another submit for example - save comment or something like that. I know, that solution little bit smells, but in other hand, it doing the job.

Of course guys, if you have any solutions how to handle in the better way at that case, would be awesome to take a look at the examples :)

**Comment by Leopoldthecoder** [comment]
Right, `on-success` is called every time a file is uploaded successfully. We may not change this behavior.

**Comment by eduardosilvajobs** [comment]
Hello I also found myself in this "characteristic", I understand why it was designed that way but. 
What I did to solve this was: 
```:on-change="afterSubmit"```

```
afterSubmit () {
    let filesUploaded = 0;

    this.$refs.upload.uploadFiles.forEach(file => {
        if (file.status == 'success') {
            filesUploaded++;
        };
    });

    if (filesUploaded === this.$refs.upload.uploadFiles.length) {
        this.$router.push('/');
        this.alertCreatedSuccess('o Job');
    };
},
```
I know it isn't the most beautiful way, but that would solve the issue 😃

**Comment by gaganhn** [comment]
Hey Guys, i have an issue, regarding on-success event, 
When we upload multiple files at once, on-success is supposed to be called every time a file is uploaded successfully, But it only fires once for the first on.
Using Element UI version 2.3.6.
