### ISSUE TITLE
[Feature Request] Multiple $message display

### ISSUE THREAD

**Issue by Yorgovan** [ElemeFE/element#10429]
### Existing Component
Yes

### Component Name
MessageBox

### Description
Is it possible to have multiple MessageBoxes like it is possible to have multiple notifications?

For example I have array of unread messages and I want to display MessageBox for each of those messages saying that you have new message and do you want to read it. But instead I am getting just one MessageBox with last message.
When I try same thing with notifications I get multiple.

Example is here https://jsfiddle.net/5nb4hubq/

**Comment by wacky6** [comment]
Right now, $message does not support displaying multiple instances. You can try $notify which should work for multiple non-synchronous calls.

**Comment by Leopoldthecoder** [comment]
@wacky6 I think this is about MessageBox, not Message.

Actually you can put all MessageBoxes in a queue and they will pop up when the previous one is closed: https://jsfiddle.net/leopoldthecuber/5nb4hubq/8/ . In your specific use case, I think it's better to call the next MessageBox when the Dialog is closed: https://jsfiddle.net/leopoldthecuber/5nb4hubq/13/ .
