### ISSUE TITLE
[Bug Report] type = password doesn't work on <el-input>!!!!

### ISSUE THREAD

**Issue by jwenjian** [ElemeFE/element#10420]
### Element UI version
2.3.0

### OS/Browsers version
Win10 / Chrome  65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/jreyyuf9/](https://jsfiddle.net/jreyyuf9/)

### Steps to reproduce
Just input some characters in the first or the second input box

### What is Expected?
The value of the input box should be masked since the type of which is specified as password

### What is actually happening?
The value of the input box showed the plain text!!!!
Please fixed it as soon as possible.

**Comment by jwenjian** [comment]
Aww, duplicated, I will close this issue now.

**Comment by AndreyBor1** [comment]
Дебил

**Comment by AndreyBor1** [comment]
Any link???
