### ISSUE TITLE
[Bug Report] tree component's check-change event is weird

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#10423]
### Element UI version
2.3.0

### OS/Browsers version
macos / chrome 65

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xlaoyu/fo9kerhj/6/](https://jsfiddle.net/xlaoyu/fo9kerhj/6/)

### Steps to reproduce
1. 点击“通过 key 设置”，选中“一级 3”以及它的子节点
2. 点击"uncheck node id = 7"，uncheck 一个子节点
3. 看 check-change 触发，并没有把 id=7的 node 传进来，而是只触发了 “一级 3”节点的 check-change

从代码来看，是因为没有展开过的节点是还没有渲染这个子节点组件的，导致节点的 data.checked 虽然改变了，但是没有触发节点组件的`handleSelectChange`事件从而没有触发 `check-change`
```js
watch: {
      'node.indeterminate'(val) {
        this.handleSelectChange(this.node.checked, val);
      },

      'node.checked'(val) {
        this.handleSelectChange(val, this.node.indeterminate);
      },

      'node.expanded'(val) {
        this.$nextTick(() => this.expanded = val);
        if (val) {
          this.childNodeRendered = true;
        }
      }
    },

    methods: {
      getNodeKey(node) {
        return getNodeKey(this.tree.nodeKey, node.data);
      },

      handleSelectChange(checked, indeterminate) {
        if (this.oldChecked !== checked && this.oldIndeterminate !== indeterminate) {
          this.tree.$emit('check-change', this.node.data, checked, indeterminate);
        }
        this.oldChecked = checked;
        this.indeterminate = indeterminate;
      },
```

### What is Expected?
 触发 id=7节点的 check-change 事件

### What is actually happening?
没有触发。

**Comment by Leopoldthecoder** [comment]
需要节点 7 触发事件的话就必须把 `render-after-expand` 关闭：https://jsfiddle.net/leopoldthecuber/fo9kerhj/12/ 。

**Comment by Yuliang-Lee** [comment]
这个有没有优化的空间？因为如果树的节点非常多，比如是一棵省份-城市树，设置了这个属性会生成非常多的VNODE和 dom node，渲染比较慢而且占用内存比较多
