### ISSUE TITLE
[Bug Report] form validation cannot be passed

### ISSUE THREAD

**Issue by DougFlands** [ElemeFE/element#10422]
### Element UI version
2.3.0

### OS/Browsers version
chrome65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/d26mot25/](https://jsfiddle.net/d26mot25/)

### Steps to reproduce
v-model绑定为type时验证始终无法通过

### What is Expected?
选择后为绿色通过

### What is actually happening?
选择后提示需要选择

**Comment by jwenjian** [comment]
`<el-form-item>`的`prop`指定的属性名, `<el-input>`中的`v-model`绑定的属性名和`rules`中设置的属性名需要保持一致~
参见[https://jsfiddle.net/d26mot25/3/](https://jsfiddle.net/d26mot25/3/)

**Comment by amanbolat** [comment]
i encountered same problem. May be it should be in docs?
