### ISSUE TITLE
[Feature Request] select is unable to obtain other custom attributes of the current selected option

### ISSUE THREAD

**Issue by zheng18633149754** [ElemeFE/element#10432]
### Existing Component
是

### Component Name
select

### Description
现有 select 组件再change 事件中只返回了value 值  然而我想获取选中option 上其他自定义绑定属性无法获取    希望change事件中默认返回value  有需求 可以接收返回（  当前选中项 option   ）
![qq 20180329092734](https://user-images.githubusercontent.com/20103991/38065060-d8229830-3333-11e8-8cc4-dfdc7d22133b.png)

**Comment by Leopoldthecoder** [comment]
请自行在 options 里查找：https://jsfiddle.net/leopoldthecuber/9cqmc0ao/1/ 。

**Comment by zheng18633149754** [comment]
单选这样可以但是有没有想过多选的情况下呢？
单选返回id 去查找只过滤一次数据就可以 ，
多选的时候如果只是增加选项可以过滤value的最后一项将其取到，
如果多选的时候已经选择了其中某几项，要将选择的其中一项取消选择，如何知晓取消选择的是哪一项，
还是要去select的数据中去将所有的剩余选择项全部过滤出来呢？
全部过滤出来  不如将当前操作的 option 项返回  直接使用方便、快速

**Comment by zheng18633149754** [comment]
单选这样可以但是有没有想过多选的情况下呢？
单选返回id 去查找只过滤一次数据就可以 ，
多选的时候如果只是增加选项可以过滤value的最后一项将其取到，
如果多选的时候已经选择了其中某几项，要将选择的其中一项取消选择，如何知晓取消选择的是哪一项，
还是要去select的数据中去将所有的剩余选择项全部过滤出来呢？
全部过滤出来 不如将当前操作的 option 项返回 直接使用方便、快速

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 杨奕 <notifications@github.com>
发送时间: Thursday, March 29, 2018 10:30:36 AM
收件人: ElemeFE/element
抄送: P|; Author
主题: Re: [ElemeFE/element] [Feature Request] select is unable to obtain other custom attributes of the current selected option (#10432)


请自行在 options 里查找：https://jsfiddle.net/leopoldthecuber/9cqmc0ao/1/ 。

―
