### ISSUE TITLE
Does the [Bug Report] eleme do not support the UMD mode package?

### ISSUE THREAD

**Issue by xugege** [ElemeFE/element#10431]
### Element UI version
2.3.0

### OS/Browsers version
windows

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
两个问题
问题1.
1.下载eleme源码

2.yarn

3.yarn dist:all

问题2
yarn dist

### What is Expected?
问题1：
生成eleme的umd模式的css和js文件

问题2：
能够正常的执行成功

### What is actually happening?
问题:1：
只生成了css文件

问题2：
yarn run v1.5.1
$ npm run clean && npm run build:file && npm run lint && cooking build -c build/
cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run
 build:utils && npm run build:umd && npm run build:theme

> element-ui@2.3.0 clean D:\develop\work\node\workspace\element3
> rimraf lib && rimraf packages/*/lib && rimraf test/**/coverage && lerna clean
--yes

Lerna v2.0.0-beta.32
Independent Versioning Mode
element-carousel                                   ╢█████░░░░░░░░░░░░░░░░░
element-table                                      ╢█████████░░░░░░░░░
element-upload                                     ╢█████████████
element-datepicker                                 ╢█████████████
element-loading                                    ╢█████████████
element-pagination                                 ╢█████████████
All clean!

> element-ui@2.3.0 build:file D:\develop\work\node\workspace\element3
> node build/bin/iconInit.js & node build/bin/build-entry.js & node build/bin/i1
8n.js & node build/bin/version.js

(node:2720) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
ut callback is deprecated.
[build entry] DONE: D:\develop\work\node\workspace\element3\src\index.js

> element-ui@2.3.0 lint D:\develop\work\node\workspace\element3
> eslint src/**/* test/**/* packages/**/* build/**/* --quiet

D:\develop\work\node\workspace\element3\packages\theme-chalk\src\fonts\element-i
cons.ttf
  1:1  error  Parsing error: Unexpected character '

**Comment by xugege** [comment]
我在.eslintignore加上如下代码即可了
*.ttf
*.woff

**Comment by Leopoldthecoder** [comment]
注意一下 eslint 及相关依赖的版本吧，类似问题都是依赖版本过高导致的。
