### ISSUE TITLE
[Bug Report] table multiple click sorting

### ISSUE THREAD

**Issue by quyinggang** [ElemeFE/element#10435]
### Element UI version
0.1.0

### OS/Browsers version
Mac/Chrome lastest

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/0gv3c04a/](https://jsfiddle.net/0gv3c04a/)

### Steps to reproduce
just need multiple click sorting（连续点击查看即可）

### What is Expected?
Multiple click sorting is normal （多次点击的效果应该是正确的）

### What is actually happening?
The data is messy when 3N hits （连续点击，3n次时数据是乱的）

**Comment by Leopoldthecoder** [comment]
Table 的排序会随着用户点击在以下几种状态中循环：升序 -> 降序 -> 恢复原始顺序 -> 升序…，因此第 3n 次点击是恢复原始顺序（即按 data 属性所传递的数组的顺序），对应地，sort-change 事件参数中的 order 为 ascending，descending 和 null。
