### ISSUE TITLE
A small proposal for [Feature Request] (A little suggest)

### ISSUE THREAD

**Issue by Mingscript** [ElemeFE/element#10449]
### Existing Component
否

### Component Name
。

### Description
在官网复制一些代码（方法或者数据）的时候，经常会有括号多复制或少复制的一个情况，可以在某些代码结尾的地方用一个换行来提示一下，或者在methods最后一个方法结尾也加上逗号，这样复制代码的时候不怎么会出错了，也不用数括号了，对类似我这样的萌新还是挺有用了，如果不能改的话，我会关闭的。谢谢了。
In website copy some code （method or data), often have more brackets, copy or less of a situation, can at the end of a certain code with a newline to tip, or at the end of the methods the last method is combined with a comma, so why not make a mistake when copying code, also need not number of parentheses, is very useful for sprout new or like I, if can't change, I will shut down. Thank you.（英文不好，见谅吧！）
![image](https://user-images.githubusercontent.com/21995558/38077393-69ede53a-336b-11e8-9ee4-d3dcd00d0836.png)
类似于图中第二个方法，我不能很快速直接的复制完，第一个方法就很直观，也有换行隔开。
Similar to the second method in the diagram, I can't copy it very quickly and directly, the first method is straightforward, and there is a line break.

**Comment by Leopoldthecoder** [comment]
大概不会支持了，工作量太大，对于 Element 本身而言也没什么意义。自己注意一下吧。

**Comment by Mingscript** [comment]
嗯好的，谢谢了 @Leopoldthecoder
