### ISSUE TITLE
[Bug Report] el-tree[draggable] does not work in IE11

### ISSUE THREAD

**Issue by Hotbrains** [ElemeFE/element#10444]
### Element UI version
2.3.2

### OS/Browsers version
ie11

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://codepen.io/Hotbrains/pen/oqEWMq](https://codepen.io/Hotbrains/pen/oqEWMq)

### Steps to reproduce
drag/drop does not work on ie11.

### What is Expected?
drag/drop works.

### What is actually happening?
error ocurrs.

**Comment by Leopoldthecoder** [comment]
Fixed in #10494

**Comment by lyon007** [comment]
![image](https://user-images.githubusercontent.com/21033119/38297033-c682d4ae-3825-11e8-9747-b85ab13473b1.png)
