### ISSUE TITLE
[Bug Report] DateTimeRangePicker, when I use the shortcuts, after that, I change.

### ISSUE THREAD

**Issue by weihaopeng** [ElemeFE/element#10441]
### Element UI version
2.3.1

### OS/Browsers version
macOs10.13.3/chrome65.0.3325

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/amn50bg3/2/](https://jsfiddle.net/amn50bg3/2/)

### Steps to reproduce
首先设置快捷选择时间（如最近一周）时，然后再打开时间日期范围选择器，通过键盘修改时间时，时间有时不会改变。

First I set time by shutcuts once(for example, a week), and then I open the date and time range picker again, set time by using keyboard, the time cannot change sometime(not always).

### What is Expected?
当我设置快捷选择时间（如最近一周）时，然后再打开时间日期范围选择器，通过键盘修改时间时，时间会正确改变。

When I set time by shutcuts once(for example, a week), and then I open the date and time range picker again, set time by using keyboard, the time will change successfully.

### What is actually happening?
当我设置快捷选择时间（如最近一周）时，然后再打开时间日期范围选择器，通过键盘修改时间时，时间有时不会改变。

When I set time by shutcuts once(for example, a week), and then I open the date and time range picker again, set time by using keyboard, the time cannot change sometime(not always).

**Comment by Leopoldthecoder** [comment]
没有太理解，最好能有一个动图，然后说明一下在什么时机，什么状态下通过键盘上的什么键修改哪里的时间。

**Comment by weihaopeng** [comment]
已上传gif，可以查看第一个gif图，最后点击时间选择时，通过键盘输入并修改时间小时为20，然后点击时间部分的确认，此时时间input中的小时会改变，但是最外层的时段没有改变（键盘输入时，时间下拉菜单中的小时也没变）；点击右下角确认后，时段仍未改变。这个不是每次必现。
![1](https://user-images.githubusercontent.com/33681454/38096633-fa471aea-33a5-11e8-9af4-17bd439dedec.gif)
![2](https://user-images.githubusercontent.com/33681454/38096669-0a94bff6-33a6-11e8-8dac-9db444a10f96.gif)

**Comment by weihaopeng** [comment]
gif图有点快，补充一下操作：
1.  打开picker，选择最近一周，pikcer会关闭，时间为最近一周；
1.  再次打开picker，将起始时间的时间input进行修改，小时从'23'改为'20'，具体修改是通过键盘，先退格delete掉3，然后输入0，此时时间的下拉菜单中，小时仍然定位在23那里；
1.  点击时间input的确定，时间input中的小时修改为了20；
1.  点击右下角确认，picker收起，但是外层显示的时段并为改变（在项目中使用时，此时返回的时间起始时间也没有改变为20:02:21。
1.  再次打开picker，时间input那里仍为20:02:21；且确定时仍不会改变。

**Comment by Leopoldthecoder** [comment]
> 通过键盘，先退格delete掉3，然后输入0

 @wacky6 我看了一下，在执行以上操作后，再点击「确定」按钮，之后代码的执行会出现以下三种情况（本身就挺奇怪了）：
- 执行一次 `handleTimeChange`，这种情况下不会出现问题
- 执行一次 `handleTimeChange`，之后执行一次 `handleMinTimePick`，且 `handleMinTimePick` 中 `value.getHours()` 是 `20`，这种情况下不会出现问题
- 执行一次 `handleTimeChange`，之后执行一次 `handleMinTimePick`，且 `handleMinTimePick` 中 `value.getHours()` 是 `23`，这种情况下就会出现问题

你看看能不能给点提示吧

**Comment by wacky6** [comment]
我这里在 `yarn dev` 里还没复现出来。

猜测 `date-range` 的 `el-input` 的 `@input.native` / `@change.native` 有问题，试试换成组件自己的 input / change。（似乎是去年做 2.0 的时候 change 发射行为改过以后没替换掉 date-range 里面的写法）
