### ISSUE TITLE
“选择日期范围”可以增加一个只选择“年-月”的组件吗？

### ISSUE THREAD

**Issue by zwl1619** [ElemeFE/element#1044]
“选择日期范围”有个可以选择“年-月-日”的组件，http://element.eleme.io/#/component/date-picker#xuan-ze-ri-qi-fan-wei   
可以增加一个只选择“年-月”，的组件吗？

**Comment by furybean** [comment]
可以试试 type 设置为 month 能不能满足你的需求。
