### ISSUE TITLE
Can the [Feature Request] el-breadcrumb component provide slot custom bread crumbs?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#10440]
### Existing Component
是

### Component Name
el-breadcrumb

### Description
el-breadcrumb 组件能否提供 slot 定制面包屑呢？

**Comment by Leopoldthecoder** [comment]
是指什么？`<el-breadcrumb-item>活动管理</el-breadcrumb-item>` 现在就是通过 slot 写内容进去。

**Comment by fengyun2** [comment]
有时候，页面内容空间不够，可以让面包屑装载更多的内容(包括按钮，除面包屑外的展示文字等卢)，而不仅仅只是显示 `el-breadcrumb-item`。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/ns1oysxk/1/ 也可以放其他元素，不过要写些样式了。总之不是一个常见场景，应该不会支持。
