### ISSUE TITLE
[Feature Request] Can el-table or el-table-column set column width  based on the content width of this column?

### ISSUE THREAD

**Issue by VeAmas** [ElemeFE/element#10450]
### Existing Component
是

### Component Name
el-table-column

### Description
如题，
是否可以不通过设置width或者min-width来自动控制列宽？
不行的话有什么好的办法？
Is there any way to control the column width automatically without 'widht' or 'min-width' property?
if not, is there any hack way to do that?

**Comment by Leopoldthecoder** [comment]
不支持宽度自适应。目前的实现不太可能做到这一点，算是 Table 的一个限制了。
