### ISSUE TITLE
Setting the current inputNum associated V-model invalid in the [Bug Report] inputNum blur event callback method

### ISSUE THREAD

**Issue by lzy68187311** [ElemeFE/element#10456]
### Element UI version
2.3.2

### OS/Browsers version
chrome

### Vue version
2.5.16

### Reproduction Link
[   https://jsfiddle.net/b1afpb85/13/](   https://jsfiddle.net/b1afpb85/17/)

### Steps to reproduce
inputNum 组件  删除inputNum组件中的内容  触发blur事件  设置默认值 无法设置 只有第一次赋值成功 后续 触发blur事件 均不成功

### What is Expected?
组件的值发生变化

### What is actually happening?
组件的值未发生变化

**Comment by lzy68187311** [comment]
更新代码地址  https://jsfiddle.net/b1afpb85/17/

**Comment by Leopoldthecoder** [comment]
You may need to use `$nextTick`: https://jsfiddle.net/leopoldthecuber/b1afpb85/29/
