### ISSUE TITLE
[Bug Report] is unable to modify the subject on the document using the SCSS project

### ISSUE THREAD

**Issue by lim-roid** [ElemeFE/element#10455]
### Element UI version
2.3.2

### OS/Browsers version
Google Chrome 版本 64.0.3282.186（正式版本） （64 位）

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1101/](https://jsfiddle.net/mmx38qxw/1101/)

### Steps to reproduce
就是按照文档步骤
/* 改变主题色变量 */
$--color-primary: teal;

/* 改变 icon 字体路径变量，必需 */
$--font-path: '~element-ui/lib/theme-chalk/fonts';

@import "~element-ui/packages/theme-chalk/src/index";
将此文件替换main.js中的 import 'element-ui/lib/theme-chalk/index.css';
但是不仅不起作用，还丢失了原本的样式

### What is Expected?
按照文档所示更换主题色

### What is actually happening?
不但没有更换主题色，连原本的样式也丢失了

**Comment by Leopoldthecoder** [comment]
请将出问题的项目精简一下（去除业务代码和其他不相关代码），放到 GitHub 上我们看看。

**Comment by lim-roid** [comment]
https://github.com/lim-roid/element-bug

**Comment by lim-roid** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
https://github.com/lim-roid/element-bug/pull/1

vue-cli 模板的 webpack 配置：https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L43-L83 ，你这里加了一段错误的配置，造成无法编译 scss 文件。
