### ISSUE TITLE
[Feature Request] Enhance the new features of the table

### ISSUE THREAD

**Issue by Jerry-goodboy** [ElemeFE/element#10453]
### Existing Component
是

### Component Name
el-table

### Description
1. I wanna TreeGrid or TreeTable
2. I wanna line editing
3. when "type=selection" is given, if I give a completed sign, I wanna modify the select box to the completed Icon, it is very urgent

**Comment by Leopoldthecoder** [comment]
1. We have no plan to add TreeGrid or TreeTable
2. Use scoped slots
3. What is a completed icon? You can use Chinese if you prefer

**Comment by Jerry-goodboy** [comment]
@Leopoldthecoder 
1. 为啥不支持 TreeGrid or TreeTable 呢，这个功能也很常用的？
2. scoped slots 怎么用，有示例代码吗？
3. 完成图标指的就是类似一个对号或者其他可以表示完成意思的图标，正常的时候表格的每一行前面都是复选框，但是当我想表示这一行已经是完成状态时，不允许让别人勾选了，那么我就需要把复选框替换成一个图标，这个需求很普遍，可以考虑支持一下，原来用JQ表格插件的时候，我都是自己改的库的源码，希望这个功能能够底层支持一下

**Comment by Jerry-goodboy** [comment]
@element-bot @Leopoldthecoder @hex-ci @et @fireyy

**Comment by Leopoldthecoder** [comment]
1. 没有精力
2. 看文档 http://element-cn.eleme.io/#/zh-CN/component/table#zi-ding-yi-lie-mo-ban
3. 看文档 `selectable`
