### ISSUE TITLE
[Feature Request] Hope for new component

### ISSUE THREAD

**Issue by JiangYinyuan12** [ElemeFE/element#10454]
### Existing Component
否

### Component Name
无

### Description
issue description can not put picture             
view this website: http://ac.qq.com/Comic/all/search/time/page/1        
is there exist some way to realize the search bar[检索框] like the website.            
if there is noway to use vue or elementui to realize that,i really hope for this feature

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
