### ISSUE TITLE
[Bug Report] when Select get focus, the options not Auto Show

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#10469]
### Element UI version
2.3.2

### OS/Browsers version
win10 1709 / 360Chrome 9.5.0.124

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/pjturrum/6/](https://jsfiddle.net/pjturrum/6/)

### Steps to reproduce
click "聚焦" button

### What is Expected?
the select focus,and the options show

### What is actually happening?
ths select focus , but the options is not show,
this problem is appear in version 2.2.0,  
In version 2.1.0, there is no problem

**Comment by Leopoldthecoder** [comment]
This is a feature in 2.2.0 to make Select align with native select, which does not show options on focus. We're currently working on a new prop to let user configure this behavior. #10042
