### ISSUE TITLE
[Feature Request] Tree tree control setCurrentKey does not trigger node-click events, and no event listens to key changes, SetCurrentKey becomes very small.

### ISSUE THREAD

**Issue by Jiro25330** [ElemeFE/element#10463]
### Existing Component
是

### Component Name
Tree

### Description
Tree树形控件setCurrentKey不会触发node-click事件，现在也没有事件可以监听key的改变，这个SetCurrentKey就变的很鸡肋了。想实现默认选中树节点都很困难。

**Comment by Leopoldthecoder** [comment]
> 默认选中树节点

https://jsfiddle.net/leopoldthecuber/yvh4La87/1/

> 现在也没有事件可以监听key的改变

`current-change`

**Comment by yin112234** [comment]
设置 setCurrentKey 后，应该触发 current-change 事件， 可惜没有!!!  希望能尽快加上，3q！！
