### ISSUE TITLE
[Bug Report] changes in navMenu design after introducing el-row

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [ElemeFE/element#10468]
### Element UI version
2.3.2

### OS/Browsers version
Elementary OS / Firefox 59.0

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mIcHyAmRaNe/yy0k8bpy/14/](https://jsfiddle.net/mIcHyAmRaNe/yy0k8bpy/14/)

### Steps to reproduce
- hover on About or Contact items
- click on About or Contact items

### What is Expected?
- `About & Contact` items do not turn grey on hover (no effect)

- display the blue line like with the item at start (`Home`) when we click on `About` or `Contact` item (selected)

### What is actually happening?
- when we hover `About` or `Contact` items a grey rectangle is displayed 

- when we click on `About` or `Contact` item the blue line is not displayed like with Home item

**Comment by Leopoldthecoder** [comment]
Menu can be nested, so to precisely control menu item's style, we have to use the `>` selector when writing CSS. For your special use case, you'll need to write some CSS: https://jsfiddle.net/leopoldthecuber/yy0k8bpy/19/

**Comment by mIcHyAmRaNe** [comment]
i had to add `background: none`  to disable the grey effect when item clicked
and had to add `opacity` parameter to get an harmonious result :)

so the css becomes: 
```
.el-menu--horizontal>.el-row>.el-menu-item {
  height: 60px;
  line-height: 60px;
  opacity: 0.5;
}
.el-menu--horizontal>.el-row>.el-menu-item:not(.is-disabled):hover {
  background-color: #fff;
  opacity: 1;
}

.el-menu--horizontal>.el-row>.el-menu-item.is-active {
    border-bottom: 2px solid #409EFF;
    color: #303133;
    background: none;
    opacity: 1;
}

```

Thank you for showing me the way.
