### ISSUE TITLE
Where are all the styles?

### ISSUE THREAD

**Issue by FranzSkuffka** [ElemeFE/element#1046]
In the docs I found color, typography etc. but no info on where to get the styles. Where can I find the stylesheets to make the UI actually look as presented in the docs.

Example:
```
el-form.bg-white-dark
```
has no effects.

**Comment by Leopoldthecoder** [comment]
Here: https://raw.githubusercontent.com/ElemeFE/element/master/examples/docs/zh-CN/color.md

Note that these styles do not come with Element, they are for demo only.

**Comment by FranzSkuffka** [comment]
Ah thanks, but why are they so prominent in the docs then? What is the rationale for not making them available as theme or so?

Thanks

**Comment by Leopoldthecoder** [comment]
`Color` and `Typography`, these two parts are more like suggestions on how to make your page more visually consistent with Element. We think Element, as a UI component library, doesn't get to control which color or font users should use on other parts of the page.

On top of that, every component included in Element has a set of theme. You don't need to write additional styles for them. And of course, we provide a custom theme tool for you to customize your own themes, but that's a whole other story.

Generally I think you are right, maybe we should elaborate this on the `Color` and `Typography` docs.

**Comment by FranzSkuffka** [comment]
I think much better would be simply proving these two style sheets instead of isolating them. As a separate asset for example that would be great. I started prototyping rapidly with element and had to realise that some parts are missing. Kind of broke the entire flow for me.
