### ISSUE TITLE
[Bug Report] sup of badge was hidden (display: none), when value of (0)

### ISSUE THREAD

**Issue by zcanjie** [ElemeFE/element#10460]
### Element UI version
2.3.2

### OS/Browsers version
window7 / chrome (58.0.3029.110 (64-bit))

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/qpy5m6za/6/](https://jsfiddle.net/qpy5m6za/6/)

### Steps to reproduce

        <el-badge :value="0" :max="99" class="item">
          <el-button size="mini">评论</el-button>
        </el-badge>

      the sup was hidden...(display: none)

### What is Expected?
1、the sup should be show, when the value of badge is zero (value = 0)

### What is actually happening?
1、the sup was hidden (display: none), when the value of badge bound is zero (value = 0)

**Comment by elfman** [comment]
你是不是贴错网址了？
