### ISSUE TITLE
[Bug Report] The table contents are displayed incorrectly after the merge column.

### ISSUE THREAD

**Issue by Ethan997** [ElemeFE/element#10473]
### Element UI version
2.3.2

### OS/Browsers version
OS 10.13.3 / Chrome  65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/Ethan_HangZhou/548x7nsd/5/](https://jsfiddle.net/Ethan_HangZhou/548x7nsd/5/)

### Steps to reproduce
Seting rowIndex === Number.jsfiddle really describes the problem.

### What is Expected?
The table contents are displayed correctly after the merge column, and the other rows or columns are not affected.

### What is actually happening?
The table contents are not displayed correctly after the merge column, and the other rows or columns are affected.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/548x7nsd/8/
