### ISSUE TITLE
[Bug Report] 使用 el-date-picker  type="daterange"  和   el-date-picker  type="month"  同时使用，页面会错乱

### ISSUE THREAD

**Issue by liyuanliang** [ElemeFE/element#10479]
### Element UI version
2.3.2

### OS/Browsers version
win7 / 谷歌 65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
1，先点击 el-date-picker  type="daterange" 这个组件，打开关闭
2，在打开 el-date-picker  type="month" 这个组件， 打开关闭
3  在点击 el-date-picker  type="daterange" 这个组件，就可以看到位置错乱

还有一个问题 二个 el-date-picker  type="month"  组件摆放一排的时候偶然会出现位置混乱

### What is Expected?
位置不要混乱

### What is actually happening?
位置不要混乱

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
