### ISSUE TITLE
[Bug Report] table component header and column cannot align in (Google)

### ISSUE THREAD

**Issue by MyYuan** [ElemeFE/element#10472]
### Element UI version
2.3.2

### OS/Browsers version
google  65.0.3325.181（正式版本） 

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element/issues/8768](https://github.com/ElemeFE/element/issues/8768)

### Steps to reproduce
element ui 2.3.2版本，table列设置min-width属性，当浏览器的100%时表头与列对齐，非100%时均不对齐

### What is Expected?
对齐

### What is actually happening?
不对齐

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
