### ISSUE TITLE
table内的td默认padding能否修改？

### ISSUE THREAD

**Issue by lizhuowei** [ElemeFE/element#1047]
表格栏比较多，不想出现横向滚动条，怎么减少td内的默认padding值？

**Comment by furybean** [comment]
可以看看这样是否满足需求：http://jsfiddle.net/hqvnwsdk/

**Comment by lizhuowei** [comment]
ok，已经解决！

**Comment by lizhuowei** [comment]
已经解决，谢谢你！

在 2016-11-14 14:43:53，"杨奕" <notifications@github.com> 写道：


Closed #1047.
