### ISSUE TITLE
版本号为2.2.2 el-progress，color修改没有作用，如果取消了color，请更新文档

### ISSUE THREAD

**Issue by 529457764** [ElemeFE/element#10483]
```
<el-progress :text-inside="true" :stroke-width="18" :percentage="80" color="rgba(142, 113, 199, 0.7)"></el-progress>

color is not effect
```
<img width="739" alt="wx20180330-172622 2x" src="https://user-images.githubusercontent.com/5729496/38132894-85179fe8-343f-11e8-821b-1e47efcc5580.png">

**Comment by Leopoldthecoder** [comment]
使用 2.2.2 的话请查看 2.2.2 的文档：http://element-cn.eleme.io/2.2/#/zh-CN/component/progress

**Comment by 529457764** [comment]
thank you, I update my plugin version to fix it!
