### ISSUE TITLE
[Bug Report] table Table performance issues

### ISSUE THREAD

**Issue by future3002** [ElemeFE/element#10485]
### Element UI version
2.3.2

### OS/Browsers version
win10

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/zhubaisong/ageg19sx/25/](https://jsfiddle.net/zhubaisong/ageg19sx/25/)

### Steps to reproduce
数据量够大的时候   单纯的勾选操作都会卡慢

### What is Expected?
支持最少几千条数据不卡

### What is actually happening?
不仅卡，而且还会有间歇性内存溢出

**Comment by Leopoldthecoder** [comment]
Duplicate of #6089
