### ISSUE TITLE
Table数据量超过100都会有卡顿的感觉

### ISSUE THREAD

**Issue by future3002** [ElemeFE/element#10482]
看了源代码，表格主体Body部分使用的是render整体生成，但是每次更新数据都会重新生成，而且数据量越大每次更新不管大小，都会卡的要死，建议部分改为templete
我试着改了除了colums的部分，性能好很多，但是还不够，和其他框架比还是差不少

**Comment by nailfar** [comment]
老哥  改成template 为什么会性能好很多 ，template最后不是还是转成render 函数了，关键是如何让它异步渲染。
