### ISSUE TITLE
The [Bug Report] select component sets the initial value, and under Safari, there will be an overlap with the placeholder

### ISSUE THREAD

**Issue by anyisky** [ElemeFE/element#10480]
### Element UI version
2.2.2

### OS/Browsers version
mac/safari

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/chunyanhuang/mmx38qxw/1140/](https://jsfiddle.net/chunyanhuang/mmx38qxw/1140/)

### Steps to reproduce
用safari打开上面链接，会有一闪而过的叠影。
在静态页上demo更明显，叠影会一直在，除非触发到任意事件才会消失。

### What is Expected?
当下拉框有值时，placeholder消失

### What is actually happening?
当下拉框有值时，placeholder的值也隐在后面。

**Comment by Leopoldthecoder** [comment]
Safari 11.0.2 未见叠影（页面加载时也没有出现「一闪而过的叠影」）：
![image](https://user-images.githubusercontent.com/10095631/38129870-60adf42e-3433-11e8-9800-03ca74eaace7.png)

**Comment by anyisky** [comment]
@Leopoldthecoder 
用2.2.2 这个版本好像会有这问题，但在jsfiddle上的确不明显，我用html写小demo就明显叠影
![image](https://user-images.githubusercontent.com/4426273/38132860-6a42094c-343f-11e8-8d1f-3414a799dd63.png)
![image](https://user-images.githubusercontent.com/4426273/38132883-7b94accc-343f-11e8-9384-b1f23466c53d.png)
safari版本：
![image](https://user-images.githubusercontent.com/4426273/38132934-a88e4e54-343f-11e8-8c15-39df8007d464.png)

**Comment by Leopoldthecoder** [comment]
试了一下，无法复现：
![image](https://user-images.githubusercontent.com/10095631/38133199-cb47fe80-3440-11e8-88a7-3a6fa6bbacd0.png)

所用代码：
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <!-- import CSS -->
  <link rel="stylesheet" href="https://unpkg.com/element-ui@2.2.2/lib/theme-chalk/index.css">
</head>
<body>
<div id="app">
  <el-select v-model="value" placeholder="Select">
    <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value">
    </el-option>
  </el-select>
</div>
</body>
<!-- import Vue before Element -->
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<!-- import JavaScript -->
<script src="https://unpkg.com/element-ui@2.2.2/lib/index.js"></script>
<script>
  new Vue({
    el: '#app',
    data() {
      return {
        options: [{
          value: 'Option1',
          label: 'Option1'
        }, {
          value: 'Option2',
          label: 'Option2'
        }, {
          value: 'Option3',
          label: 'Option3'
        }, {
          value: 'Option4',
          label: 'Option4'
        }, {
          value: 'Option5',
          label: 'Option5'
        }],
        value: 'Option2'
      }
    }
  })
</script>
</html>
```

看下是不是被什么浏览器扩展影响了吧。

**Comment by anyisky** [comment]
我找safari 11+ 测试了下，的确复现不出这问题了，出现这问题的是在safari 10+的时候：
![image](https://user-images.githubusercontent.com/4426273/38133698-e7c6b734-3442-11e8-8ad5-f7d3d2b3bd3e.png)
