### ISSUE TITLE
When the [Bug Report] <el-menu> component tag adds its own <x-input> component, the input input box cannot enter the data with a space.

### ISSUE THREAD

**Issue by Lamborshea** [ElemeFE/element#10489]
### Element UI version
2.0.10

### OS/Browsers version
Win10 / Chrome 65.0.3325.181

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/nanbo/rnw562d2/](https://jsfiddle.net/nanbo/rnw562d2/)

### Steps to reproduce
在输入框中以空格开始输入数据，会发现无法输入空格。
当在 取消 mode="horizontal" 时，就可以以空格开始输入数据了。

### What is Expected?
在 <el-menu mode="horizontal"> 组件里添加自定义的 input 组件时，input 输入框本应该是可以以空格开始输入的

### What is actually happening?
在 <el-menu mode="horizontal"> 组件里添加自定义的 input 组件时，input 输入框本不能以空格开始输入数据

**Comment by Leopoldthecoder** [comment]
Duplicate of #8812
