### ISSUE TITLE
[Bug Report] [el-upload] fails to put the :data value in request payload that has been set in :before-upload

### ISSUE THREAD

**Issue by BkunS** [ElemeFE/element#10507]
### Element UI version
2.3.2

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1164/](https://jsfiddle.net/mmx38qxw/1164/)

### Steps to reproduce
html:
<el-upload :action="${postURL}" :data="uploadData" :before-upload="setUploadData" ...>

scripts:
export default {
  data () {
    return {
      uploadData: {}
    }
  },
  methods: {
    setUploadData () {
      this.uploadData = {
        cloudStoragePath: '/test'
      }
    }
  }
}

### What is Expected?
  Posting image payload should contain { cloudStoragePath: '/test' } in request payload.

### What is actually happening?
The image upload request body does NOT have updated uploadData object at the first time, but will do the second time and after. Probably it is sent before the uploadData has been set, or the uploadData has been set but the upload request fails to retrieve the new value.

**Comment by Leopoldthecoder** [comment]
This demo explains why this happens: https://jsfiddle.net/leopoldthecuber/m5fa3Lwu/4/ . A possible workaround is https://jsfiddle.net/leopoldthecuber/m5fa3Lwu/5/ .

For Upload, there's another workaround: https://jsfiddle.net/leopoldthecuber/mmx38qxw/1174/

**Comment by keyvan21904** [comment]
set auto-upload true

**Comment by keyvan21904** [comment]
I had a similar problem and solved it that way
:auto-upload="true"
