### ISSUE TITLE
webpack引入ui是css引入失败

### ISSUE THREAD

**Issue by h3n5** [ElemeFE/element#10509]
使用的是vue-cli搭建的项目，webpack版本3.6.0。在按照文档使用后css引入失败，报错。
This dependency was not found:

* element-ui/lib/style.css in ./src/main.js

To install it, you can run: npm install --save element-ui/lib/style.css
其中css-loader配置和说明的一样

**Comment by KayneWang** [comment]
> 使用的是vue-cli搭建的项目，webpack版本3.6.0。在按照文档使用后css引入失败，报错。
> This dependency was not found:
> 
> * element-ui/lib/style.css in ./src/main.js
> 
> To install it, you can run: npm install --save element-ui/lib/style.css
> 其中css-loader配置和说明的一样

**Comment by KayneWang** [comment]
这个问题为啥没人回答？

**Comment by KayneWang** [comment]
@h3n5 同样遇到这个问题，你目前找到解决办法了么？

**Comment by h3n5** [comment]
> @h3n5 同样遇到这个问题，你目前找到解决办法了么？

额，太久了，我都忘了。而且这是被关闭的issue，要按格式提交issue才能通过

**Comment by KayneWang** [comment]
@h3n5 哎。。。好吧，你这个问题最后怎么解决的。T.T

**Comment by KayneWang** [comment]
@h3n5 谢谢，已经没问题了。:)

**Comment by guohuihot** [comment]
与bablerc配置有关，这里记录下，有人遇到这个问题，可以从这个思路去排查
我的是多了这个设置
```


    "plugins": [
        //这里这个有问题
        ["component", [{
            "libraryName": "mint-ui",
            "style": true
        }]],
        "transform-vue-jsx",
        "transform-runtime"
    ],
```
