### ISSUE TITLE
Scrollbar style beautification and unification of [Feature Request] table components

### ISSUE THREAD

**Issue by mismo** [ElemeFE/element#10504]
### Existing Component
是

### Component Name
Table 表格

### Description
“Table 表格”组件的滚动条样式希望可以与“Select 选择器”组件的下拉面板的滚动条样式保持一致，按需显示。
另外，“Cascader 级联选择器”等组件也一样。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
