### ISSUE TITLE
[Bug Report] Do not put the selected values in the attribute name to value

### ISSUE THREAD

**Issue by fynduck** [ElemeFE/element#10505]
### Element UI version
0.1.0

### OS/Browsers version
winsows 10 / google chrome 65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/3utsgwzz/8/](https://jsfiddle.net/3utsgwzz/8/)

### Steps to reproduce
Set to 
```html
<el-select
multiple
filterable
remote
reserve-keyword
:remote-method="remoteMethod">
```
if set :multiple="false" is worked, set selected value

### What is Expected?
Need put on the `<input name="pages[]">` selected values

### What is actually happening?
Not set on `<input name="pages[]">` selected values

input value is empty

**Comment by Leopoldthecoder** [comment]
Value won't be set to input element. Please use `v-model` instead.

**Comment by fynduck** [comment]
I know what I can use `v-model`,

but why multiple="false" put value to input but multiple="true" not put

**Comment by sebastiaanluca** [comment]
Having the same issue. Value is correctly set and sent with form data when `multiple` is `false`. When multiselect is enabled, it's only bound to `v-model` and not set on the input's value. I'd expect a comma-separated list of selected items or something.
