### ISSUE TITLE
[Bug Report] Failed to get name attribute inside input via ref

### ISSUE THREAD

**Issue by longFeiLi** [ElemeFE/element#10518]
### Element UI version
2.3.2

### OS/Browsers version
mac/ 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/longfei0925/mdty6g3c/4/](https://jsfiddle.net/longfei0925/mdty6g3c/4/)

### Steps to reproduce
Click on the button to see the console, printing is null

v2.2.2 version is possible

### What is Expected?
Can get the name value

### What is actually happening?
Failed to get

**Comment by Leopoldthecoder** [comment]
In the current version we're using `v-bind="$attrs"` to pass native attributes to the input element. So now you'll have to https://jsfiddle.net/mdty6g3c/7/
