### ISSUE TITLE
table  fixed-column-count bug

### ISSUE THREAD

**Issue by xierenyuan** [ElemeFE/element#1051]
### ElementUI version

1.0.0-rc.2
### OS/Browers version

macOs/Chrome 53
### Vue version

2.0
### Reproduction Link

https://codepen.io/aping/pen/GNZeMG
### Steps to reproduce
详情见提供的 列子 
我循环绑定表格列 并且指定  fixed-column-count 为2时 出现了相同列
### What is Expected?
期望不出现重复列

### What is actually happening?
我尝试过 当列多的时候 这个 重复列并不存在

**Comment by furybean** [comment]
这个属性已经被废弃了，新版的 API 在这里：http://element.eleme.io/#/component/table#gu-ding-lie

**Comment by xierenyuan** [comment]
0.0 @furybean  后边我看呢 其实 我使用的版本是 ^1.0.0-rc.7  并不是最新版  。暂时因为项目以上线,并且做了一些自定时的事情, 主题什么 我单独修改过的问题 还木法快速升级。 如果新版本 木有问题就关闭这个bug 吧。
