### ISSUE TITLE
[Bug Report] [table] Don't work min width column

### ISSUE THREAD

**Issue by kolesoffac** [ElemeFE/element#10519]
### Element UI version
2.3.2

### OS/Browsers version
Mac 10.13.1 / Chrome Version: 65.0.3325

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/f85u60mj/3/](https://jsfiddle.net/f85u60mj/3/)

### Steps to reproduce
* change width all columns

### What is Expected?
When set width of column less, than min-width, then set min-width.

### What is actually happening?
Don't set min width column.

**Comment by Leopoldthecoder** [comment]
Sorry I don't quite understand what your problem is. Could you elaborate?

**Comment by kolesoffac** [comment]
I set prop _min-width_ for _el-table-column_. But can set real width less, than value  _min-width_ (use resizer of column).

**Comment by Leopoldthecoder** [comment]
`min-width` only works when doing layout for the Table. It does not restrict users from resizing columns by dragging.
