### ISSUE TITLE
In the [Bug Report] tree component, the function of the second parameters of the setCheckedKeys method seems to have no effect. (keys, leafOnly)

### ISSUE THREAD

**Issue by hasbug** [ElemeFE/element#10510]
### Element UI version
2.2.2

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1184/](https://jsfiddle.net/mmx38qxw/1184/)

### Steps to reproduce
看了文档，对术语不是很理解。

可能理解有误，但我刚好有这么个需求：在tree组件中的setCheckedKeys(keys, leafOnly)  我用于回显后端返回的已经勾选的数据，但这个数组里面包含未全选的父ID以及被勾选的子项，也包含全选的父ID以及被勾选的子项，我通过这个方法进行设置的时候，非全选的会导致所有子项都被全部勾选，并没有达到我想要的半选状态。

无论第二参数我设置false还是true，效果一样。难道不是设置为true后，tree节点能够判断这个非全选父ID属于非全选，仅仅去匹配数组中的id去勾选，而不是认为是全选吗？

### What is Expected?
setCheckedKeys(keys, true)能够根据已选数组中的id去筛选回显全选和非全选的情况。

### What is actually happening?
setCheckedKeys(keys, leafOnly)  并不能识别当前这个id是否全选和非全选

**Comment by Leopoldthecoder** [comment]
通俗的解释是，默认情况下，你传一个 ID 进来，那么 Tree 会把它自己和它全部的后代节点选中；第二个参数若为 `true`，则仅选中「它自己和它全部的后代节点」中的叶子节点。

并不会判断是否为非全选。
