### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by wwt0317** [ElemeFE/element#10526]
请教一个版本2.3.2 的分页问题题， 每一页10条数据，我有11条数据，我在第2页删除第11条数据，那么我的页面只有1页了，为什么不触发current-change事件呢。之前1.4.4是会触发的

**Comment by Missliuzy** [comment]
分页中为每个nubmer加入边框后，当点击当前分页的Number时，下一个number的内容宽度会变大，导致左边框会消失。
