### ISSUE TITLE
[Feature Request] prohibits breadcrumb jump

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#10529]
### Existing Component
是

### Component Name
breadcrumb

### Description
希望可以设置每个breadcrumb-item是否跳转的属性

**Comment by Leopoldthecoder** [comment]
是需要一个 `disabled` 属性吗？

**Comment by Kingwl** [comment]
倾向于第二个。。。

**Comment by Kingwl** [comment]
thanks!
