### ISSUE TITLE
[Feature Request] How to achieve upload? I want to upload img and

### ISSUE THREAD

**Issue by newBird01** [ElemeFE/element#10524]
### Existing Component
否

### Component Name
upload

### Description
How to achieve  upload? upload image text at the same time

**Comment by newBird01** [comment]
**# _i want to use elemeUI to achieve the following effects_**
`<form action="/addPro" method="post" enctype="multipart/form-data">
			  <input type="text" class="form-control" aria-describedby="basic-addon1" name="mallName" >
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productImg">				 
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productDetailImg">	 
</form>`

**Comment by newBird01** [comment]
**# _i want to use elemeUI to achieve the following effects_**
`<form action="/addPro" method="post" enctype="multipart/form-data">
			  <input type="text" class="form-control" aria-describedby="basic-addon1" name="mallName" >
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productImg">				 
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productDetailImg">	 
</form>`

**Comment by newBird01** [comment]
**# _i want to use elemeUI to achieve the following effects_**
**`<form action="/addPro" method="post" enctype="multipart/form-data">
			  <input type="text" class="form-control" aria-describedby="basic-addon1" name="mallName" >
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productImg">				 
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productDetailImg">	 
</form>`**

**Comment by newBird01** [comment]
**# _i want to use elemeUI to achieve the following effects_**
`、<、form action="/addPro" method="post" enctype="multipart/form-data">
			  <input type="text" class="form-control" aria-describedby="basic-addon1" name="mallName" >
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productImg">				 
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productDetailImg">	 
<、/、form>`

**Comment by newBird01** [comment]
**# _i want to use elemeUI to achieve the following effects_**
`\<form action="/addPro" method="post" enctype="multipart/form-data">
			  <input type="text" class="form-control" aria-describedby="basic-addon1" name="mallName" >
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productImg">				 
			  <input type="file" class="form-control" aria-describedby="basic-addon1" name="productDetailImg">	 
<\/form>`

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
