### ISSUE TITLE
[Bug Report] version 2.3.2 recurrent the issue #10415: pass native types to

### ISSUE THREAD

**Issue by Higginshuangjing** [ElemeFE/element#10539]
### Element UI version
2.3.2

### OS/Browsers version
macOS hIGH Sierra 10.13.1 / 浏览器 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
 when I use el-input and type="password", I found the password in clear text.

but i don't have the right Reproduction Link.

### What is Expected?
not clear text.

### What is actually happening?
clear text.

**Comment by Higginshuangjing** [comment]
啊~  sorry 我网进不去  jsfiddle.net

**Comment by Leopoldthecoder** [comment]
已确认 2.3.2 版本没有这个问题。请检查项目中 Element 的版本。

**Comment by Higginshuangjing** [comment]
sorry ~  我知道了
