### ISSUE TITLE
[Feature Request] Need click event when user click the el-step

### ISSUE THREAD

**Issue by gitpaladin** [ElemeFE/element#10538]
### Existing Component
是

### Component Name
el-step

### Description
el-steps is very useful to submit a large form. But sometimes the user may review his forms before. I want a click event bound at the el-step, then I will switch the panel to the corresponding step to let my user review his previous form.

**Comment by Leopoldthecoder** [comment]
`@click.native`

**Comment by kevrousso** [comment]
@gitpaladin I was having the same need and so I was able with a @click.native to accomplish this.
See here: https://codepen.io/kevrousso/pen/wmNVoq
