### ISSUE TITLE
[Bug Report] 日期选择器 type 为 week 的时候，添加 value-format="yyyy 第 WW 周" ,没法选择时间，控制台会报错

### ISSUE THREAD

**Issue by FAKER-A** [ElemeFE/element#10530]
### Element UI version
2.3.2

### OS/Browsers version
windows 10 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/8p3yu9sr/1/](https://jsfiddle.net/8p3yu9sr/1/)

### Steps to reproduce
使用周日期选择器 随机选择某一周。

### What is Expected?
时间选择器输入框的值变化
    

### What is actually happening?

时间选择器输入框的值没有变化    

打开控制台会看到报错

**Comment by Leopoldthecoder** [comment]
Duplicate of #8783
