### ISSUE TITLE
[Bug Report] Popper for DatePicker Appear at the Wrong Place when Its Type Changes

### ISSUE THREAD

**Issue by Kris-Lee-SH** [ElemeFE/element#10534]
### Element UI version
2.3.2

### OS/Browsers version
all / all

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/KrisLeeSH/mmx38qxw/1215/](https://jsfiddle.net/KrisLeeSH/mmx38qxw/1215/)

### Steps to reproduce
1. click "month" button, focus to the date-picker component
2. click "daterange" button, focus to the date-picker component
3. click "month" button, focus to the date-picker component and pay attention to the popper-panel's position

### What is Expected?
The popper shows in the right position (on the bottom of the input component)

### What is actually happening?
The popper appears at the top-left corner of the page

**Comment by Kris-Lee-SH** [comment]
And sometimes when the date-picker's type changed, the popper panel wouldn't show after focus in the input area.

**Comment by Leopoldthecoder** [comment]
You need to use `key` to force a re-render: https://jsfiddle.net/mmx38qxw/1218/ . Actually it's discouraged to mutate `type` dynamically.
