### ISSUE TITLE
[Feature Request] officials have no intention of creating a set of back-end programs that can be used in a box.

### ISSUE THREAD

**Issue by renji566** [ElemeFE/element#10536]
### Existing Component
是

### Component Name
admin

### Description
官方有没有意向出一套后台方案，可以开箱使用的

**Comment by Leopoldthecoder** [comment]
目前没有计划。可以考虑社区用户的作品：https://github.com/ElementUI/awesome-element#boilerplates

**Comment by lspnet** [comment]
现在iview已经出了开箱即用的方案，因为现在好多周边的朋友都因为这个推荐用iview了。

希望官方也出一个，确实比较喜欢element ui。

**Comment by lspnet** [comment]
> 目前没有计划。可以考虑社区用户的作品：https://github.com/ElementUI/awesome-element#boilerplates

现在iview已经出了开箱即用的方案，因为现在好多周边的朋友都因为这个推荐用iview了。

希望官方也出一个，确实比较喜欢element ui。
