### ISSUE TITLE
The problem of [Bug Report] container layout container

### ISSUE THREAD

**Issue by tonycody** [ElemeFE/element#10546]
### Element UI version
2.3.2

### OS/Browsers version
Windows 10

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/ewq7rhs1/2/](https://jsfiddle.net/ewq7rhs1/2/)

### Steps to reproduce
<el-container>
  <el-header>Header</el-header>
  <el-main>Main</el-main>
  <el-footer>Footer</el-footer>
</el-container>

这个组件是基于vue实例的，但是el-main 里面可能是动态变化的填充页面。填充的页面也会有自己的vue实例。

由于Container容器本身有一个vue实例了，这样会导致实例嵌套了。这种怎么解？

### What is Expected?
不写布局的 vue 实例

### What is actually happening?
必须要有布局的vue实例

**Comment by Leopoldthecoder** [comment]
没懂什么意思。具体问题是什么？
