### ISSUE TITLE
[Feature Request] select multi selector, can acquire multiple objects

### ISSUE THREAD

**Issue by dawayway** [ElemeFE/element#10543]
### Existing Component
Yes

### Component Name
select 选择器

### Description
select 选择器 单选时，可以获取value值为对象，多选时，获取的是字符串数组，我想，能不能多选时，也支持获取多个对象的数组，类似[ {}, {} ]
这是我的例子： https://jsfiddle.net/8jq7ozuz/22/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/8jq7ozuz/30/
