### ISSUE TITLE
[Bug Report] el-scrollbar cuts the last item on the list (el-select and el-table-column)

### ISSUE THREAD

**Issue by jocabrera** [ElemeFE/element#10548]
### Element UI version
2.2.0

### OS/Browsers version
windows 10 / chrome 65

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1235/](https://jsfiddle.net/mmx38qxw/1235/)

### Steps to reproduce
When the component is on a mobile device, el-scrollbar cuts the last item on the list (el-select and el-table-column)

Note: On Mac OS 10.13 / Chrome 65 works as expected

### What is Expected?
The last item needs to keep the same height that previous items

### What is actually happening?
el-scrollbar cuts the last item on the list (el-select and el-table-column)

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. It's discouraged to use it on mobile devices.
