### ISSUE TITLE
[Bug Report] el-upload can not achieve an asynchronous request after the success of the request, and then delete the picture

### ISSUE THREAD

**Issue by Create-Peace** [ElemeFE/element#10547]
### Element UI version
2.3.2

### OS/Browsers version
chrome66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1231/](https://jsfiddle.net/mmx38qxw/1231/)

### Steps to reproduce
鼠标移动到想要删除的图片上，点击删除按钮，想要等异步请求成功后，再删除当前图片。但是一点击就立刻删除了

### What is Expected?
点击删除按钮，弹出 提示确认框，点击取消，提示已经取消了删除图片，图片不删除。点击确定按钮，等异步请求成功后，才删除图片。

### What is actually happening?
点击删除按钮后，无论点击确定还是取消都是立刻删除当前图片

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/1242/
