### ISSUE TITLE
When the [Feature Request] table is merged with a cell, the serial number will not be merged

### ISSUE THREAD

**Issue by qqcbqqkcel** [ElemeFE/element#10554]
### Existing Component
是

### Component Name
ea-table

### Description
表格合并单元格时，序号不会合并重新计算。
如第一列指定为 el-table-column type="index"
然后把第1行和第3行合并，会出现序号不连贯的问题。

**Comment by Leopoldthecoder** [comment]
列的序号不会考虑合并行的情况，请自行通过 `index` 属性处理。
