### ISSUE TITLE
[Feature Request] DatePicker can dynamically change the date format

### ISSUE THREAD

**Issue by fan-lv** [ElemeFE/element#10559]
### Existing Component
是

### Component Name
DatePicker

### Description
1. 日期选择控件可以动态的更改日期格式，希望可以把切换日期格式的功能集成到组件里面去
[![24efcf.png](https://miao.su/images/2018/04/04/24efcf.png)](https://miao.su/image/w9w8k)

[![14e08d.png](https://miao.su/images/2018/04/04/14e08d.png)](https://miao.su/image/w9dMf)
2. 日期范围的选择能够支持选择年或月，目前只能修改显示的格式为年或月，而日期选择面板还是天的选择
[![3bad35.md.png](https://miao.su/images/2018/04/04/3bad35.md.png)](https://miao.su/image/w9xeo)

**Comment by Leopoldthecoder** [comment]
- `type` 可以是动态的：https://jsfiddle.net/leopoldthecuber/jjb9zwLw/1/
- 无计划支持。
