### ISSUE TITLE
El-input-number control button BUG

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#10552]
### Element UI version
2.3.2

### OS/Browsers version
win7/谷歌

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/v6so74v6/6/](https://jsfiddle.net/v6so74v6/6/)

### Steps to reproduce
当input-number在v-for下，点击控制按钮的值在对应数组里的值总是不对。

### What is Expected?
期待修正。

### What is actually happening?
当input-number在v-for下，点击控制按钮的值在对应数组里的值总是不对，貌似数字永远少1

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/v6so74v6/9/

**Comment by Liupeng8** [comment]
@Leopoldthecoder 我在change事件里打印input-number  v-model绑定的数据，都是错的。

**Comment by Liupeng8** [comment]
@Leopoldthecoder https://jsfiddle.net/v6so74v6/20/

**Comment by Liupeng8** [comment]
@Leopoldthecoder input输入框手动输入一点问题都没有，我先用这个代替下，有时间的话，辛苦帮看下。谢谢

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/10553

**Comment by Liupeng8** [comment]
@Leopoldthecoder 按照你说的，代码调整了后，问题依旧

**Comment by Leopoldthecoder** [comment]
你调整的哪个文件？

**Comment by Liupeng8** [comment]
@Leopoldthecoder packages/input-number/src/input-number.vue这个
