### ISSUE TITLE
[Bug Report] Expected identifier error for {row, rowIndex} type of function

### ISSUE THREAD

**Issue by arisliang** [ElemeFE/element#10558]
### Element UI version
2.3.2

### OS/Browsers version
Windows 10 / Microsoft Edge

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/7kgpgw3j/](https://jsfiddle.net/7kgpgw3j/)

### Steps to reproduce
Open the link with Microsoft Edge

### What is Expected?
To show row 2, 4 as colored.

### What is actually happening?
The table is not shown at all.

**Comment by Leopoldthecoder** [comment]
Does the console print any errors?

**Comment by arisliang** [comment]
yes.
> SCRIPT1010: Expected identifier

And it's basically complaining about this `tableRowClassName({row, rowIndex}) `. If changed it to `tableRowClassName(row, rowIndex) ` (without the {}). The table will show, although the row color is still not showing correctly.

**Comment by wacky6** [comment]
Does this occur in production (after webpack build)? Or it is just a problem of jsfiddle in Edge.

**Comment by arisliang** [comment]
This is the link came from the official documentation. http://element.eleme.io/#/en-US/component/table#table-with-status. Click `Run this demo on jsfiddle.net`

**Comment by Leopoldthecoder** [comment]
Most likely to be because certain Edge versions do not support destructuring assignment.

**Comment by arisliang** [comment]
By the way, same problem is on IE 11 as well.

**Comment by arisliang** [comment]
I checked the compatibility of the destructuring assignment at <a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment'>here</a>. There're like half of the browsers don't support them, including all IE, Edge, Safari, iOS Safari.

**Comment by Leopoldthecoder** [comment]
So don't use it in your code or use babel to compile it.
```js
tableRowClassName(obj) {
  var rowIndex = obj.rowIndex;
  if (rowIndex === 1) {
    return 'warning-row';
  } else if (rowIndex === 3) {
    return 'success-row';
  }
  return '';
}
```

**Comment by arisliang** [comment]
@Leopoldthecoder Thanks, it's working now as you suggested. Might consider to mention it the documentation though. Seems to be a pretty common scenario.

**Comment by Leopoldthecoder** [comment]
Actually this is a JavaScript / ES6 issue, not much related to Vue or Element.

**Comment by arisliang** [comment]
Well, I'd say it's more of a browser compatibility thing, since half of the browsers don't support this feature yet.
