### ISSUE TITLE
[AutoComplete] 在 Table 内不显示下拉列表

### ISSUE THREAD

**Issue by liwenkuiJG** [ElemeFE/element#1056]
### Steps to reproduce
更新了element-ui1.0.0版本 autocomplete 在 table 内还是不显示下拉列表，html的代码结构如下，没有写javascript代码。
```Vue
<el-table :data="tableData"  border style="width: 100%">
    <el-table-column inline-template  label="记录" width="200">
        <span>
            <el-autocomplete  v-model="state1"  :fetch-suggestions="querySearch" 
              placeholder="请输入内容"
              @select="handleSelect"
            ></el-autocomplete>
        </span>
    </el-table-column>
</el-table>
```
### What is Expected?
预期的下拉列表没出现

**Comment by uglybachelor** [comment]
类似的问题，直接copy文档中的“固定列”的代码业无法正常显示。并且加了inline-template就会报错：`t._h is not a function`。代码如下：
  ```
<el-table-column inline-template label="操作" width="200">
      <span>
            <el-button type="text" size="small" @click="goToClient(client.client_name)">查看</el-button>
            <el-button type="text" size="small" @click="$router.push('#')">编辑</el-button>
      </span>
</el-table-column>
```

**Comment by Leopoldthecoder** [comment]
@uglybachelor 这个问题升到 1.0.1 应该可以解决。

@liwenkuiJG 你反映的这个问题我们会在 1.1 版本中修复。因为牵涉到下拉框 DOM 节点位置的变动，也许会造成原有用户自己写的 CSS 失效，所以是一个非兼容性更新，要放在 minor 版本里。

**Comment by hijourney** [comment]
@Leopoldthecoder 有暂时性的解决方案么。

**Comment by liwenkuiJG** [comment]
<td>
              <el-autocomplete
                class="my-autocomplete"
                custom-item="my-item-zh"
                v-model="row.name"
                size="small"
                :fetch-suggestions="querySearchDrug"
                placeholder="药品搜索"
                :trigger-on-focus="false"
                @select="handleSelectDrug">
              </el-autocomplete>
           </td>
我是直接用原生的Table去做，说真的element的Table不怎么漂亮，可以自己写个Table

**Comment by liwenkuiJG** [comment]
如何喜欢element的Table样式，模仿着写个样式也不难

**Comment by baiyaaaaa** [comment]
1.1.0+版本已修复此问题
