### ISSUE TITLE
[Bug Report] datePicker shows date from the day before

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#10569]
### Element UI version
2.3.3

### OS/Browsers version
google chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/kutmania/gf3ey7fj/2/](https://jsfiddle.net/kutmania/gf3ey7fj/2/)

### Steps to reproduce
Normal use of datePicker

### What is Expected?
the expected output is the date entered in the v-model. If I start the component with date 2018-01-01, the date of the previous day appears (2017-12-31) - inside input
Image of erro: [IMAGE](https://scontent.fvdc1-1.fna.fbcdn.net/v/t1.0-9/29683793_1039966839475216_8688601187768860672_o.jpg?_nc_cat=0&oh=d31448e0feae1d537b0eb7968110b43a&oe=5B340D56)

### What is actually happening?
Expected output is the same date as reported on the model

**Comment by Leopoldthecoder** [comment]
This is how Date object in JavaScript handles time zone. Try this demo: https://jsfiddle.net/gf3ey7fj/5/

You may want to check this part of the docs: http://element.eleme.io/#/en-US/component/date-picker#date-formats
