### ISSUE TITLE
[Bug Report] In some cases, pagination current-change event doesn't trigger

### ISSUE THREAD

**Issue by porcelainHeart** [ElemeFE/element#10561]
### Element UI version
2.3.2

### OS/Browsers version
macOS High Sierra / Chrome 63

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/dofrk09z/4/](https://jsfiddle.net/dofrk09z/4/)

### Steps to reproduce
1. Click on the third page
2. Click the search button, then the page jumps to the first page
3. Click on the third page, then you can see current-change event doesn't trigger

### What is Expected?
alert(page: 3)

### What is actually happening?
none

**Comment by warplan** [comment]
遇到了相同的问题，求解决方法

**Comment by porcelainHeart** [comment]
@warplan 
等新版本修复此bug, 已经merge 估计很快
或者自己维护额外的flag去强制更新状态

**Comment by warplan** [comment]
@porcelainHeart 感觉element-ui的bug有点多啊，pagination的问题就已经是第二次了，希望饿了么的同学来点士力架

**Comment by Curitis** [comment]
遇到同样的问题，比如点击了第三页 ，然后点击查询按钮设置current-page=1，再次点击第三页就失效了

**Comment by porcelainHeart** [comment]
此bug在element-ui@2.3.4测试已修复, thanks
