### ISSUE TITLE
[Feature Request] Option for Slider change event to happen while dragging mouse

### ISSUE THREAD

**Issue by manelclos** [ElemeFE/element#10570]
### Existing Component
Yes

### Component Name
Slider

### Description
It is not possible now to get all value changes while dragging with the mouse. Something like "continuous: true" should allow the programmer to get "change" events for every value change while dragging with the mouse.

**Comment by wacky6** [comment]
https://jsfiddle.net/b72soh9p/

**Comment by manelclos** [comment]
Great! it would be good to add such event to the "input" event to the documentation, here: http://element.eleme.io/#/en-US/component/slider

Thanks!
