### ISSUE TITLE
[Bug Report] Date-Picker cannot remove prefix-icon

### ISSUE THREAD

**Issue by pmochine** [ElemeFE/element#10578]
### Element UI version
2.3.3

### OS/Browsers version
Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/cmtwfkgL/](https://jsfiddle.net/cmtwfkgL/)

### Steps to reproduce
<el-date-picker
      v-model="value1"
      type="date"
      placeholder="Pick a day"
      :prefix-icon="''">
    </el-date-picker>

### What is Expected?
Prefix Icon should be gone

### What is actually happening?
Prefix Icon is still there

**Comment by wacky6** [comment]
You need to overwrite css in this case.
