### ISSUE TITLE
[Bug Report] Unable to render RouterLink via createElement inside $notify message param.

### ISSUE THREAD

**Issue by dobromir-hristov** [ElemeFE/element#10571]
### Element UI version
2.0.10

### OS/Browsers version
Windows 10

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1259/](https://jsfiddle.net/mmx38qxw/1259/)

### Steps to reproduce
Call $notify with message property being a Vnode that has router-link inside.

### What is Expected?
The notification should be shown with a success message and a link.

### What is actually happening?
The router-link component says the `router` param is undefined.

**Comment by Leopoldthecoder** [comment]
I have boiled it down to this: https://jsfiddle.net/leopoldthecuber/mmx38qxw/1281/

I'm not sure what caused this, maybe there's some restrictions of vue-router that I don't know. If you have some idea about how to fix it, please share.

Right now I'd suggest using an `<a>` element as a replacement.

**Comment by dobromir-hristov** [comment]
Exactly what I did :)
