### ISSUE TITLE
dialog 调用 messageBox 引发闪烁

### ISSUE THREAD

**Issue by asmodai1985** [ElemeFE/element#1057]
### ElementUI version
1.0.0 

### OS/Browers version
windows/Chrome 50

### Vue version
2.0.5

### Reproduction Link
https://jsbin.com/fajawew/edit?html,js,output

### Steps to reproduce
dialog 调用 messageBox

### What is Expected?
正常显示，组件互不干扰

### What is actually happening?
dialog本身遮罩被极短时间被隐藏，显出背景色，之后messageBox正常显示。视觉冲击太强，显示非常不友好

**Comment by reverland** [comment]
感觉是zindex那个inline的管理。。。

**Comment by reverland** [comment]
不要用popper manager统一管理zindex了？

**Comment by Leopoldthecoder** [comment]
感觉和 inline 没关系，是因为每次有一个新的遮罩出现都会来一遍「从无到有」的动画。我修一下。

**Comment by Leopoldthecoder** [comment]
Fixed in #1038
