### ISSUE TITLE
The [Bug Report] Input cursor is full of the input box, and the browser's performance is inconsistent

### ISSUE THREAD

**Issue by zxmLoveLife** [ElemeFE/element#10572]
### Element UI version
2.3.3

### OS/Browsers version
Mac / 10.13.4

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Safari下Input光标高度和Input 内容区高度一致，和Chrome下表现不一致。
建议修改以下样式
.el-input__inner{
    line-height: 24px;padding: 8px 15px;
}

### What is Expected?
不同浏览器下光标高度表现一致

### What is actually happening?
光标高度不一致

**Comment by Leopoldthecoder** [comment]
The line height was set to `40px` to fix another buggy behavior in Chrome. Guess we couldn't have it both ways. I suggest you override it in your project like this:
```css
.el-input__inner {
  line-height: 1;
}
```
https://jsfiddle.net/mmx38qxw/1272/
