### ISSUE TITLE
[Bug Report] navigation menu folding unnatural

### ISSUE THREAD

**Issue by niefufeng** [ElemeFE/element#10576]
### Element UI version
2.3.3

### OS/Browsers version
OSX 10.13.4 / Chrome  65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/Outshine/qhw82j4g/4/](https://jsfiddle.net/Outshine/qhw82j4g/4/)

### Steps to reproduce
新建一个menu，然后在展开和折叠之间切换

### What is Expected?
折叠的时候菜单应该很自然的折叠起来（参考：https://preview.pro.ant.design）

展开的时候宽度应该为所有子菜单展开的那个宽度

### What is actually happening?
菜单折叠很不自然，菜单会先折叠，然后再隐藏文字

在折叠状态展开后，会按照一级菜单宽度展开，如果点击一个有二级菜单的一级菜单（比如点击Demo左侧的任意一个一级菜单），才会达到那个宽度

**Comment by Leopoldthecoder** [comment]
需要手动设定宽度：https://jsfiddle.net/leopoldthecuber/qhw82j4g/10/

**Comment by niefufeng** [comment]
@Leopoldthecoder 哈哈，其实我主要是提第上面的那个问题：`折叠的时候菜单应该很自然的折叠起来`。

我觉得菜单折叠完成之后才开始隐藏文字有点生硬（因为试过阿里家（现在应该和你们是一家。。。）的https://preview.pro.ant.design）。

当然，这不是一个八阿哥~
