### ISSUE TITLE
[Feature Request] Expand / Collapse all rows programmatically

### ISSUE THREAD

**Issue by arisliang** [ElemeFE/element#10575]
### Existing Component
Yes

### Component Name
Table

### Description
I want to expand / collapse all rows programmatically. How to do that? Need to loop all rows? There's a columns collection. But I don't find rows collection. Please advise. Thanks.

**Comment by Leopoldthecoder** [comment]
Run `toggleRowExpansion` against each row.

**Comment by arisliang** [comment]
How to loop the row?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/rykztwd4/1/

**Comment by arisliang** [comment]
Fantastic, thanks!

**Comment by arisliang** [comment]
The link is not working in IE. But I think it's IE forEach problem.
