### ISSUE TITLE
offset doesn't work properly for popover

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#10587]
### Element UI version
2.3.3

### OS/Browsers version
windows10 Chrome70

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/cqd8yy9w/

### Steps to reproduce
1. set a offset for popover
2. and then change the number
3. what it displayed is the same as before, number has no meaning here

**Comment by Leopoldthecoder** [comment]
`offset` should be a number: https://jsfiddle.net/leopoldthecuber/cqd8yy9w/4/

**Comment by zzzgit** [comment]
yes thanks, but i think the documentation should be more detailed
