### ISSUE TITLE
[Bug Report]  Using popover in column with table column fixed will cause duplicate popover

### ISSUE THREAD

**Issue by Baifann** [ElemeFE/element#10588]
### Element UI version
2.3.3

### OS/Browsers version
macOS 10.13.3/Chome 65.0.3325.181

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/baifann/m417c85a/18/](https://jsfiddle.net/baifann/m417c85a/18/)

### Steps to reproduce
Use the popover in the column of the table, the column uses the property fixed, and the popover controls the display hiding through the v-model. Move the mouse over the "control" button and the popover is displayed.

### What is Expected?
只出现1个popover

### What is actually happening?
出现了2个相同的popover

**Comment by Baifann** [comment]
![image_1cafcv7e712261ff61q5us2foj79.png-21.3kB][2]

[2]: http://static.zybuluo.com/baifann/lbmowkwop2qia51g4acz3lon/image_1cafcv7e712261ff61q5us2foj79.png

**Comment by Leopoldthecoder** [comment]
固定列是通过把该列克隆一份来实现的（具体可参考 https://zhuanlan.zhihu.com/p/33280304），因此会有两个 Popover 实例，在使用`v-model` 控制显示与隐藏的情况下确实会发生同步现象。目前没有什么好方法，可以稍微 hack 一下：https://jsfiddle.net/leopoldthecuber/m417c85a/39/

**Comment by Hideer** [comment]
@Leopoldthecoder  你好，我遇到了同样的问题，但是你的hack连接打不开了，请问你的解决方法是什么

**Comment by xianshenglu** [comment]
https://jsfiddle.net/xianshenglu/61jhg4uf/1/ even if I fixed another column, this situation will still happen.

**Comment by Kiuyu** [comment]
在数据渲染后，找到多出来的popover隐藏起来，直接操作dom比较暴力。
不知道有没有更好的办法
