### ISSUE TITLE
[Feature Request] How to get the scrollTop or offsetTop property of the.

### ISSUE THREAD

**Issue by mgss** [ElemeFE/element#10597]
### Existing Component
是

### Component Name
el-table

### Description
How to get the scrollTop or offsetTop property of the currently selected row of the table？

英文不太好，用中文描述下：

我想实现其他组件控制table组件选中表格中的一行，并且将选中行滚动到表格顶端或中间，想知道有没有实现这个的API？非常感谢

**Comment by Leopoldthecoder** [comment]
请自行操作 DOM。
