### ISSUE TITLE
What is the value attribute of [Bug Report] Select component, and the official document is not written, but the source code is value attribute required, not value attribute console red is not good.

### ISSUE THREAD

**Issue by bosongarvin** [ElemeFE/element#10590]
### Element UI version
2.3.3

### OS/Browsers version
Windows10 64bit 专业版 / Chrome65

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1286/](https://jsfiddle.net/mmx38qxw/1286/)

### Steps to reproduce

<el-select placeholder="请选择">
</el-select>

### What is Expected?
开发时控制台应没有警告

### What is actually happening?
官方文档没有写明value属性的作用,开发时控制台报红警告

**Comment by Leopoldthecoder** [comment]
就是 `v-model`。

**Comment by bosongarvin** [comment]
我知道是v-model,但是它非得要我再加个value="",不然一打开控制台就报警告,还是红色的,看着老不舒服了, @Leopoldthecoder
