### ISSUE TITLE
How [Bug Report] encapsulates the operation bar with scope

### ISSUE THREAD

**Issue by eyii** [ElemeFE/element#10609]
### Element UI version
2.3.3

### OS/Browsers version
QQ

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
<el-table-column label="操作" width="300"> <template slot-scope="scope"> <el-button size="mini" @click="other.row_index=scope.$index;other.showDialog=true;sessionStorage.setItem('name',JSON.stringify(scope.row)); ">修改</el-button> <el-button size="mini" type="danger" @click="post(urls.del,{'uid':scope.row.uid},delCallBack);other.row_index=scope.$index">删除</el-button> <a :href="'auth/role_permission_index?roleId=' scope.row.permission" v-if="scope.row.permission>0">修改权限</a> </template> </el-table-column>

### What is Expected?
scope如何封装 你们这样左 还怎么封装
<el-table-column label="操作" width="300"> <template slot-scope="scope"> <el-button size="mini" @click="other.row_index=scope.$index;other.showDialog=true;sessionStorage.setItem('name',JSON.stringify(scope.row)); ">修改</el-button> <el-button size="mini" type="danger" @click="post(urls.del,{'uid':scope.row.uid},delCallBack);other.row_index=scope.$index">删除</el-button> <a :href="'auth/role_permission_index?roleId=' scope.row.permission" v-if="scope.row.permission>0">修改权限</a> </template> </el-table-column>

### What is actually happening?
scope如何封装 你们这样左 还怎么封装

**Comment by Leopoldthecoder** [comment]
- 描述不全，不知道你的场景是什么，你需要什么样的功能
- 没有 demo
- 代码没有格式化

请尊重我们双方的时间。
