### ISSUE TITLE
[Feature Request] Enable date-picker showWeekNumber

### ISSUE THREAD

**Issue by PewienTyp** [ElemeFE/element#10608]
### Existing Component
Yes

### Component Name
date-picker

### Description
Please enable changing showWeekNumber, currently is not possible to change this param.

**Comment by Leopoldthecoder** [comment]
I took a look and found that `showWeekNumber` is actually legacy code and should be removed.

**Comment by hanwsscan** [comment]
> I took a look and found that `showWeekNumber` is actually legacy code and should be removed.

也有场景需要，为何删除呢？如果需要请问是否有启用办法？showWeekNumber  2.4.4版本里也还有相关代码。功能确定弃用了吗请问？

**Comment by suyi91** [comment]
> > I took a look and found that `showWeekNumber` is actually legacy code and should be removed.
> 
> 也有场景需要，为何删除呢？如果需要请问是否有启用办法？showWeekNumber 2.4.4版本里也还有相关代码。功能确定弃用了吗请问？

Same to me. 

I forked ElementUI and did some modification to enable "show-week-number".

[FYI.](https://github.com/suyi91/element)
