### ISSUE TITLE
Whether [Feature Request] dialog components can destroy subcomponents after closing

### ISSUE THREAD

**Issue by yezongyang** [ElemeFE/element#10600]
### Existing Component
是

### Component Name
dialog

### Description
场景：在dialog组件里用form表单填写数据，希望在关闭后再打开还是初始化的空表单，产品方面需求比较多

**Comment by Leopoldthecoder** [comment]
已在 https://github.com/ElemeFE/element/issues/9691#issuecomment-379526884 回复。

**Comment by yezongyang** [comment]
我就是这样处理的，但是是否加一个属性更方便，谢谢

**Comment by xianshenglu** [comment]
https://github.com/ElemeFE/element/pull/16455
