### ISSUE TITLE
After the input component type is set to number, the input box cursor moves up after entering the Chinese carriage return.

### ISSUE THREAD

**Issue by himushroom** [ElemeFE/element#10603]
### Element UI version
2.3.3

### OS/Browsers version
win7（64位）/chrome 65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/himushroom/Lc54w0uv/](https://jsfiddle.net/himushroom/Lc54w0uv/)

### Steps to reproduce
1.将el-input组件的type属性设置为number
2.将输入法切换成中文
3.在输入框中打字然后回车
4.此时输入框的光标会上移

### What is Expected?
输入框的光标能够正常显示

### What is actually happening?
输入框的光标上移了，测试原生input并不会产生此现象

**Comment by Leopoldthecoder** [comment]
仅仅是因为设置了 `line-height`：https://jsfiddle.net/Lc54w0uv/6/ 。可能和 Chrome 有关，在 FireFox 下没问题。可以自己覆盖一下 CSS。
