### ISSUE TITLE
[Bug Report] In the el-upload file upload screen opens twice by tab key and enter key operation

### ISSUE THREAD

**Issue by 909173** [ElemeFE/element#10612]
### Element UI version
2.3.3

### OS/Browsers version
windows10/ Google Chrome 65.0.3325.181

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1302/](https://jsfiddle.net/mmx38qxw/1302/)

### Steps to reproduce
1. Focus the upload button by moving with the tab key
2. Make sure that you clicked the button with the enter key, and start up the file upload screen
3. Select a file and upload it
4.The upload is canceled and the file selection screen is activated again

### What is Expected?
In the first file selection, the file is uploaded correctly.

### What is actually happening?
You can not upload files correctly unless you select the file twice.

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/38480926-e4aa05e6-3bfa-11e8-9d30-0021219fe7ec.gif)

Cannot reproduce.

**Comment by 909173** [comment]
I wrote the environment with win10. I do not know if it will work on linux, Mac, but this bug has occurred at least in win10's explorer.

**Comment by Leopoldthecoder** [comment]
Only in Windows10 IE or also in Windows 10 Chrome?

**Comment by 909173** [comment]
This bug occurs in win10 and Edge, win10 and IE, win10 and chrome environment.
In the win10 and fireFox environment this bug did not occur.

**Comment by sodatea** [comment]
@Leopoldthecoder 
Make sure to use tab & enter key. This bug can be reproduced on Chrome for Mac, too.
It's an accessibility issue, actually.

**Comment by Leopoldthecoder** [comment]
I am using tab and enter. Do you guys have a screenshot?

**Comment by Leopoldthecoder** [comment]
OK, I have reproduced this.
