### ISSUE TITLE
[Bug Report] Duplicate identifier 'showTimeout'

### ISSUE THREAD

**Issue by texdc** [ElemeFE/element#10619]
### Element UI version
2.3.3

### OS/Browsers version
@vue/cli-service

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1324/](https://jsfiddle.net/mmx38qxw/1324/)

### Steps to reproduce
```
$ vue-cli-service serve --open
```
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    // ...
  }
}
```

### What is Expected?
When compiling Typescript, no errors should occur.

### What is actually happening?
This is a compile-time error.
```
ERROR in {project_dir}/node_modules/element-ui/types/submenu.d.ts
12:3 Duplicate identifier 'showTimeout'.
    10 |
    11 |   /** Delay time before showing a sub-menu */
  > 12 |   showTimeout: number
       |   ^
    13 |
    14 |   /** Delay time before hiding a sub-menu */
    15 |   hideTimeout: number
Version: typescript 2.7.2
```

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/10566
