### ISSUE TITLE
[Bug Report] Press enter will redirect/refresh in form label if it has only one input label

### ISSUE THREAD

**Issue by xmflswood** [ElemeFE/element#10615]
### Element UI version
2.3.3

### OS/Browsers version
all/all

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/ctgax3n2/1/](https://jsfiddle.net/ctgax3n2/1/)

### Steps to reproduce
1.creat only one input label in form
2.write something in the input then press enter

### What is Expected?
do not redirect or refresh

### What is actually happening?
redirect or refresh

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/38480797-2a177a92-3bfa-11e8-82a5-46b518a2644f.png)

文档有说明。
