### ISSUE TITLE
The change event in [Bug Report] input does not work, it will trigger to lose focus

### ISSUE THREAD

**Issue by wangxueyou110** [ElemeFE/element#10614]
### Element UI version
2.3.3

### OS/Browsers version
win10

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1315/](https://jsfiddle.net/mmx38qxw/1315/)

### Steps to reproduce
在输入框中输入内容，不触发事件，只有在失去焦点时才会触发

### What is Expected?
修复这个问题

### What is actually happening?
修复这个问题

**Comment by Leopoldthecoder** [comment]
不是 bug，`change` 事件本来就应该失去焦点才触发：https://developer.mozilla.org/en-US/docs/Web/Events/change

> When the element loses focus after its value was changed, but not commited

如果需要随着输入一直触发，使用 `input` 事件。

**Comment by JingYihhh** [comment]
@Leopoldthecoder 
![image](https://user-images.githubusercontent.com/31948533/38481789-10cdfa7a-3bff-11e8-94ba-44f822a51c92.png) 这种写法会导致校验规则失效，请问怎么解决呢？

**Comment by Leopoldthecoder** [comment]
`trigger: 'blur'` 或 `trigger: 'change'`

**Comment by JingYihhh** [comment]
一条规则只能有一个触发方式吗？

**Comment by Leopoldthecoder** [comment]
多个的话应该写成 `trigger: ['blur', 'change']`

**Comment by JingYihhh** [comment]
按trigger: ['blur', 'change']这种方式试验了一下，
![image](https://user-images.githubusercontent.com/31948533/38482820-657b4e5c-3c03-11e8-8486-e9fd3ddc9bbe.png)
输入超出字数后触发了错误信息提示
![image](https://user-images.githubusercontent.com/31948533/38482929-bfbe93d8-3c03-11e8-8aaf-7cbafa894d28.png)
，但是失去焦点后又变成校验成功了
![image](https://user-images.githubusercontent.com/31948533/38482951-ce61e7be-3c03-11e8-9b45-9bbc424b2dcc.png)

**Comment by Leopoldthecoder** [comment]
提供一下 demo。

**Comment by JingYihhh** [comment]
@Leopoldthecoder 抱歉抱歉！trigger: ['blur', 'change']这个是没有问题的，我的锅

**Comment by yf287** [comment]
@Leopoldthecoder 希望更新一下官方文档的提供的代码，http://element-cn.eleme.io/2.3/#/zh-CN/component/form
![image](https://user-images.githubusercontent.com/18239400/38920742-8e63dfda-4326-11e8-933a-bfb34694e467.png)

**Comment by Leopoldthecoder** [comment]
@yf287 多谢提醒
