### ISSUE TITLE
[Bug Report] Menu state is not saved

### ISSUE THREAD

**Issue by Deemetr** [ElemeFE/element#10622]
### Element UI version
2.3.3

### OS/Browsers version
Chrome 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/deemetr/eywraw8t/23943/](https://jsfiddle.net/deemetr/eywraw8t/23943/)

### Steps to reproduce
1. Click on "expand" button
2. Select node "Navigation One\item four\item one"
3. Click on button "collapse"
4. Click on button "expand"

### What is Expected?
The node from step №2 still selected

### What is actually happening?
Navbar state set to default

**Comment by alek5ey** [comment]
I have the same problem

**Comment by iPhosgen** [comment]
I face this bug too

**Comment by d3en9** [comment]
+1

**Comment by qingwufengyang** [comment]
怎么解决

**Comment by jikkai** [comment]
Fixed in #12178

**Comment by w-rudolph** [comment]
There is any way to make the behavior of collapse and expand menu same as [anti-design menu](https://ant.design/components/menu/)? when i expand  the menu,  it's behavior should be  same as the last behavior before i collapse the menu.
