### ISSUE TITLE
[Bug Report] use element ui as umd directly in html, el-pagination doesn't trigger event current-change when total is set to 0

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#10625]
### Element UI version
2.3.3

### OS/Browsers version
mac chrome 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/10e9mjq9/7/](https://jsfiddle.net/10e9mjq9/7/)

### Steps to reproduce
1. click pagination page 2, you can a message says 2
2. click the button `changeToatalToZero`, current page is change to 1

### What is Expected?
event `current-change` should be emitted.

### What is actually happening?
event `current-change` is not emitted.

> This issue seems not occur when use element-ui as module in webpack.

**Comment by Leopoldthecoder** [comment]
`current-change` only triggers when the end user clicks on the pagers, inputs a number in the jumper input, or chooses a different page size which updates the current page.

It'll not trigger when you programatically change the current page or other props (in this case, `total`) that lead to a current page change.

**Comment by njleonzhang** [comment]
It changes when use with using in webpack as a module.

```
<template lang="pug">
  .app-wrapper
    <el-button @click="changeToZero">changeToatalToZero</el-button>
    <el-pagination :total='total' @current-change="currentChange"></el-pagination>
</template>

<script>
  export default {
    data() {
      return {
        page: 1,
        total: 100
      }
    },
    methods: {
      changeToZero() {
        this.total = 0
      },
      currentChange(currentPage) {
        this.$message(`${currentPage}`)
      }
    }
  }
</script>
```
You can try this code within webpack. I am confused on the behavior.
If the `current-change` doesn't emit when `total` change, it is difficult for outer component to know `currentPage` when `total` change.  For example, the `total` is 100, and `pageSize` is 20, and the `currentPage` is 5. Then total change to 50, the `currentPage` will change to 3, according to inner logic of `el-pagination`, if `current-change` is not emitted, it's hard for outer component to know `currentPage`.
In fact, [vue-data-tables](https://github.com/njleonzhang/vue-data-tables) rely on `current-change` event deeply to update the table data, and this issue is from https://github.com/njleonzhang/vue-data-tables/issues/161. would you please take a look at my analysis in [that issue](https://github.com/njleonzhang/vue-data-tables/issues/161) and provide more info on this confusing behavior?

**Comment by JinTZH** [comment]
@Leopoldthecoder It maybe nice design as a component but I think it's bad as product。
