### ISSUE TITLE
[Bug Report] Select with filter-method keeps resetting the input

### ISSUE THREAD

**Issue by Terrijoo** [ElemeFE/element#10620]
### Element UI version
2.3.3

### OS/Browsers version
Chrome 65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/Terrijoo/rm4jtet1/](https://jsfiddle.net/Terrijoo/rm4jtet1/)

### Steps to reproduce
Type a "b" (for example) into the select box.

### What is Expected?
The values being filtered and the last input still being there to continue filtering

### What is actually happening?
The value is getting resettet to the default/last selected/empty on every change to the filtered option list.
This does not happen if you remove the filter-method and rely on the build in filter function.

Or maybe I am missing something on how to use the filter-method properly, since the docs aren't too clear about imo.

**Comment by Leopoldthecoder** [comment]
`:key="item.value"`: https://jsfiddle.net/leopoldthecuber/rm4jtet1/6/

**Comment by Terrijoo** [comment]
Aaah, thank you! I didn't think of that one.
