### ISSUE TITLE
[Bug Report] Element with Vuex bug when using highlight-current-row

### ISSUE THREAD

**Issue by babycannotsay** [ElemeFE/element#10639]
### Element UI version
2.0.8

### OS/Browsers version
Chrome 65.0.3325.181

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/giggle/pen/GxPMLV](https://codepen.io/giggle/pen/GxPMLV)

### Steps to reproduce
一.页面渲染完成后，点击添加一行，第一行没有高亮，再次点击也不会高亮

二.注释31行，使用32行。重新渲染页面，点击添加一行，第一行高亮，功能正常。

first.  After the page is rendered, click `add row`, the first line is not highlighted, and when click the row again, it does not highlight too.

second.  Comment 31 lines, use 32 lines. Re-render the page, click `add row`, the first row highlights, it is perfect.

### What is Expected?
在`一.`中，添加完第一行，第一行默认高亮。

when  `first.` is used in the demo, adding the first row and the first line highlights.

### What is actually happening?
第一行没有高亮，再次点击也不会高亮

The first line is not highlighted, and when click the row again, it does not highlight too.

### bug source: 

in `/element-ui/packages/table/src/table-store.js`  273 line.  The bug is related to dom rendering. Maybe `setCurrentRow` was effective, the dom is rendered. So the first row is not highlight. When  `first.` is used in the demo,  clicking the first row, the `if` statement will not be execute for the `oldCurrentRow` is equal `the row`.

**Comment by Leopoldthecoder** [comment]
与 Vuex、Element 都无关：https://codepen.io/leopoldthecoder/pen/BrMLKw?editors=1010
