### ISSUE TITLE
The next and prev button clicks of the disabled state of the [Bug Report] el-pagination component trigger the current-change event

### ISSUE THREAD

**Issue by CHEN-DONG** [ElemeFE/element#10631]
### Element UI version
2.3.3

### OS/Browsers version
window10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/oscar_xi/nh7ho83e/](https://jsfiddle.net/oscar_xi/nh7ho83e/)

### Steps to reproduce
点击next按钮或者prev按钮

### What is Expected?
不触发current-change事件

### What is actually happening?
会触发current-change事件

**Comment by Leopoldthecoder** [comment]
#10628
