### ISSUE TITLE
[Bug Report] TimePicker range

### ISSUE THREAD

**Issue by S-anasol** [ElemeFE/element#10634]
### Element UI version
2.1.0

### OS/Browsers version
OSX High Sierra

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/bpg6f8wk/2/](https://jsfiddle.net/bpg6f8wk/2/)

### Steps to reproduce
Time picker with settings:

Start - any time after midnight

End - midnight

### What is Expected?
Time range from NN:NN to 00:00 (inclusive)

09:00
10:00
...
23:00
00:00

### What is actually happening?
No selectable options at all.

**Comment by Leopoldthecoder** [comment]
This not a bug. `00:00` is considered to be the start of a day.

**Comment by Evacaca** [comment]
I had the same problem.
