### ISSUE TITLE
How methods in the [Feature Request] component uses

### ISSUE THREAD

**Issue by GuitarHusky** [ElemeFE/element#10633]
### Existing Component
是

### Component Name
Carousel 走马灯

### Description
在vue项目中想使用Carousel 走马灯中pre和next方法，手动来调用，但是不知道什么定义和使用才可以，

**Comment by Leopoldthecoder** [comment]
https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements
