### ISSUE TITLE
[Bug Report] The check box is cleared when the table is refreshed.

### ISSUE THREAD

**Issue by mengxiaobo130401** [ElemeFE/element#10643]
### Element UI version
2.1.0

### OS/Browsers version
Windows10/Google Chrome 64.0.3282.186 (official version) (64 bit)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mengxiaobo/mmx38qxw/1393/](https://jsfiddle.net/mengxiaobo/mmx38qxw/1393/)

### Steps to reproduce
When multiple check boxes in the table are selected, click Refresh, and then the data in the table will refresh, and the value selected in the check box will be reset to empty. When one or more of the status in table is 0, the table is automatically refreshed, and the check box selected during this period is also reset to empty after updating.

### What is Expected?
When one of  the items is selected, the table is refreshed and the selected one is still there.

### What is actually happening?
When one of the items is selected, the table is refreshed and the selected data is reset to unselected.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/1391/

**Comment by mengxiaobo130401** [comment]
This attribute will also be remembered after page turning. I don't want to memorize after page turning. How to get it? clearSelection this method?

**Comment by Leopoldthecoder** [comment]
Yes, use `clearSelection`.
