### ISSUE TITLE
The [Bug Report] form verifies that the trigger cannot be triggered when multiple triggers are contained

### ISSUE THREAD

**Issue by lms5610134** [ElemeFE/element#10642]
### Element UI version
2.3.3

### OS/Browsers version
chrom 版本 65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1378/](https://jsfiddle.net/mmx38qxw/1378/)

### Steps to reproduce
1、输入一个错误的邮箱    
2、点击别处，使输入框失去焦点

### What is Expected?
两步都应该触发表单验证，而导致错误提示

### What is actually happening?
没有输入错误提示 
ps： 这是官方文档中的demo ， 文档中也不好使，文档地址如下：
http://element-cn.eleme.io/#/zh-CN/component/form#dong-tai-zeng-jian-biao-dan-xiang

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/1379/
