### ISSUE TITLE
[Bug Report] Website unavailable

### ISSUE THREAD

**Issue by vdcrea** [ElemeFE/element#10647]
### Element UI version
2.3.3

### OS/Browsers version
any

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/1h3oyxja/](https://jsfiddle.net/1h3oyxja/)

### Steps to reproduce
Open official website with browser

### What is Expected?
Website DNS up and running

### What is actually happening?
ERR_NAME_NOT_RESOLVED

**Comment by Leopoldthecoder** [comment]
We're looking into it. For now please visit https://element.faas.ele.me instead.

**Comment by raphaelsaunier** [comment]
Currently down for me too: https://downforeveryoneorjustme.com/element.eleme.io

The DNS for eleme.io was updated recently (2018-04-10T08:02:00Z) so it’s probably related.

**Comment by vdcrea** [comment]
@Leopoldthecoder thanks!

**Comment by Leopoldthecoder** [comment]
It's back online.
