### ISSUE TITLE
DatePicker 选择月的时候左右切换年无效

### ISSUE THREAD

**Issue by niceue** [ElemeFE/element#1064]
### ElementUI version
1.0.0

### OS/Browers version
win10/Chrome 53

### Vue version
2.0.5

### Reproduction Link
https://jsfiddle.net/niceue/fv0Lnsfs/

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/1498854/20263970/252a4d04-aaa4-11e6-9be4-8e519a57b9f0.png)

### What is Expected?
点击 12 月，值应该为 2017-12

### What is actually happening?
实际值是 2016-12

**Comment by furybean** [comment]
和 #1070 重复，请关注另一个 issue。
