### ISSUE TITLE
[Bug Report] Chrome中，el-input 无法输入字母 "t"

### ISSUE THREAD

**Issue by sootma** [ElemeFE/element#10656]
### Element UI version
2.3.3

### OS/Browsers version
win7, chrome

### Vue version
2.5.16

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
< el-form-item class="el-col-21" label="门店全称" prop="fullName">
          < el-input v-model="vo.fullName" :maxlength="50" />
        < /el-form-item>

在chrome中，无法输入字母“t”，其他键都ok, 在其他浏览器没这个问题

### What is Expected?
正常输入t

### What is actually happening?
无反应

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/38608322-9e827c9c-3dad-11e8-91b7-9899d238403e.gif)

无法重现。
