### ISSUE TITLE
[Feature Request] el-checkbox components value and label can be bound separately

### ISSUE THREAD

**Issue by xiaowei9495** [ElemeFE/element#10659]
### Existing Component
是

### Component Name
el-checkbox

### Description
el-checkbox 组件 value 与label能否单独绑定，在我只想绑定value时，会在页面展示，这不是我想要的效果

**Comment by Leopoldthecoder** [comment]
可以使用默认 slot，如果不想显示任何内容，可以放一个空标签：https://jsfiddle.net/leopoldthecuber/km45a20s/1/
