### ISSUE TITLE
Dynamic SRC error of [Bug Report] img

### ISSUE THREAD

**Issue by sootma** [ElemeFE/element#10655]
### Element UI version
2.3.3

### OS/Browsers version
win7, firefox

### Vue version
2.5.16

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
img 的动态src错误
< img src="xxx.jpg" > OK
< img :src="'xxx.jpg'" > Error

### What is Expected?
OK

### What is actually happening?
Error

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
