### ISSUE TITLE
table 表格inline-template 报错

### ISSUE THREAD

**Issue by liubingjun** [ElemeFE/element#1065]
在里面使用{{XX}}报错 官方demo也报错
![image](https://cloud.githubusercontent.com/assets/7686824/20264282/af32e924-aaa5-11e6-883e-05a964981714.png)

![image](https://cloud.githubusercontent.com/assets/7686824/20264256/91df363e-aaa5-11e6-8a17-f2c16934b4a4.png)

**Comment by topul** [comment]
table 组件遇到同样的问题

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/1032

**Comment by niceue** [comment]
同样问题+1，花了几个小时没能解决
不知道是不是与 vue-loader 有关，但是降级 vue-loader 版本也没用了
开发环境，只要加上 `inline-template` 就会报同样错误；不用单文件组件，直接写个 jsfiddle 示例又正常

**Comment by QingWei-Li** [comment]
原因和解决方案在这里 https://github.com/ElemeFE/element/issues/1032#issuecomment-260271148

这个 issue 等我们发 1.0.1 在关吧

**Comment by liubingjun** [comment]
@QingWei-Li @niceue  
{
  "vue-loader": "9.8.0",
  "vue-template-es2015-compiler": "1.1.0"
}
这个确实也不管用了 还请尽快修复

**Comment by Leopoldthecoder** [comment]
@liubingjun 请确认 `node_modules` 里面这两个包的版本。回退之后应该是没问题的。

**Comment by liubingjun** [comment]
@Leopoldthecoder   ok了 谢谢
