### ISSUE TITLE
[Bug Report] official documents cannot be copied

### ISSUE THREAD

**Issue by zhangdaren** [ElemeFE/element#10662]
### Element UI version
2.3.3

### OS/Browsers version
windows

### Vue version
2.5.17-beta.0

### Reproduction Link
[www.jsfiddle.com](www.jsfiddle.com)

### Steps to reproduce
官方文档都不能复制啊，一定得按F12，点击了，才能显示文字光标，才能复制

### What is Expected?
官方文档都不能复制啊，一定得按F12，点击了，才能显示文字光标，才能复制

### What is actually happening?
官方文档都不能复制啊，一定得按F12，点击了，才能显示文字光标，才能复制

**Comment by Leopoldthecoder** [comment]
实测没有问题。看下是不是被浏览器插件影响了。
