### ISSUE TITLE
When [Bug Report] uses the formatter of Table-column Attributes to format the table column content, it is found that the method of formatter is called two times

### ISSUE THREAD

**Issue by lsylovelmy** [ElemeFE/element#10668]
### Element UI version
2.3.3

### OS/Browsers version
win10 64位   chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/没翻墙没有重现链接](https://jsfiddle.net/api/post/library/pure/没翻墙没有重现链接)

### Steps to reproduce
<el-table-column prop="status" label="状态" width="120" :formatter="formatStatus"></el-table-column>

formatStatus(row, column, cellValue) {
                console.log("...formatStatus...")； // 刷新页面，这个日志会被打印两次
                return “”;
 }

### What is Expected?
打印的日志只打印一次

### What is actually happening?
打印的日志只打印两次

**Comment by Leopoldthecoder** [comment]
不是 bug，固定列是通过把该列克隆一份来实现的（具体可参考 https://zhuanlan.zhihu.com/p/33280304 ），因此会有两个实例。
