### ISSUE TITLE
vue project seems not to compile some components of element-ui in production environment

### ISSUE THREAD

**Issue by aforwardz** [ElemeFE/element#10664]
### Element UI version
2.3.3

### OS/Browsers version
Ubuntu16.04/Chrome 65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
in dev environment, everything is fine
but when I run "npm run build", then I found the element-ui components were missing

### What is Expected?
hope element-ui components could be compiled

### What is actually happening?
in dev environment, everything is fine
but when I run "npm run build", then I found the element-ui components were missing

**Comment by aforwardz** [comment]
Dev Env:  
![screenshot from 2018-04-11 16-40-46](https://user-images.githubusercontent.com/19967761/38606596-0bcdb4b0-3da9-11e8-9c7f-d3789ac99f08.png)
![screenshot from 2018-04-11 16-41-16](https://user-images.githubusercontent.com/19967761/38606599-0f6a5fec-3da9-11e8-8f99-ad318ccdb11d.png)


PRO ENV:  
![screenshot from 2018-04-11 16-39-49](https://user-images.githubusercontent.com/19967761/38606608-1ab44412-3da9-11e8-8b94-d81ecb939534.png)
![screenshot from 2018-04-11 16-40-10](https://user-images.githubusercontent.com/19967761/38606615-1ef14034-3da9-11e8-8f11-658086cd6803.png)


I'm comfused

**Comment by Leopoldthecoder** [comment]
提供一个最小可重现问题的项目仓库。

**Comment by aforwardz** [comment]
不好意思，我弄错了，不是编译问题。
![screenshot from 2018-04-13 17-21-45](https://user-images.githubusercontent.com/19967761/38730267-5f789e90-3f48-11e8-9d26-6c393e506d87.png)

这是生产环境编译之后才有的，导致login-body部分出错

我在[jsfiddle](https://jsfiddle.net/pLv253hd/5/)里试了没有问题

是我哪里写的不对吗。。
