### ISSUE TITLE
[Bug Report] Dns can not resolve for element-cn.eleme.io

### ISSUE THREAD

**Issue by shiny** [ElemeFE/element#10660]
### Element UI version
0.1.0

### OS/Browsers version
any

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
visit http://element-cn.eleme.io or get ping result in https://www.17ce.com/ 

### What is Expected?
Resolve an ip for element-cn.eleme.io

### What is actually happening?
Cannot resolve element-cn.eleme.io, ERR_NAME_NOT_RESOLVED

**Comment by shiny** [comment]
![image](https://user-images.githubusercontent.com/117487/38602446-5343cb56-3d9d-11e8-9bc2-e9833b4e25c6.png)

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/38608525-31b0947c-3dae-11e8-8e66-114cbc4a9382.png)

现在应该没问题了。
