### ISSUE TITLE
[Bug Report] MessageBox bomb box cannot customize the label of element-ui

### ISSUE THREAD

**Issue by LiuJun0** [ElemeFE/element#10663]
### Element UI version
2.3.3

### OS/Browsers version
Mac、Windows / Chrome、Safari

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/5wxsskoe/9/](https://jsfiddle.net/5wxsskoe/9/)

### Steps to reproduce
MessageBox 弹框自定义el-input标签，点击button弹出MessageBox。

### What is Expected?
1、MessageBox 弹框自定义HTML，可以添加element-ui 的标签。
2、使用$msgbox弹出的输入框，可以修改输入框的属性，比如value和readonly 属性。
3、自定义的标签可以修改style。

### What is actually happening?
MessageBox 弹框自定义el-input标签，el-message-box__message 的内容却不显示。
并且自定义了普通input标签，却不能修改style。
就算是使用$msgbox封装了 element-ui的标签，但value属性不能赋值。

**Comment by Leopoldthecoder** [comment]
HTML 字符串是不会被编译的，因此不能使用组件。要传入组件必须使用 VNode。
