### ISSUE TITLE
[Tree] 异步加载节点不会自动更新

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#1066]
### ElementUI version

1.0.0
### What is actually happening?
http://element.eleme.io/#/component/tree
关于官网tree组件的第二个样例：可选择。
有个问题请教下：这个可选择的tree组件，貌似就第一次加载子树数据的时候会执行属性load绑定的loadNode方法，如果第二次在点击的时候就不执行属性load绑定的loadNode方法。
比如：我第一次点击根节点 tree1，会执行属性load绑定的loadNode方法并展开子树；当我第二次点击根节点tree1的时候关闭子树；当我第三次点击根节点tree1的时候，这时候貌似没有执行load绑定的loadNode方法，同时展开第一次点击根节点 tree1时获取的子树数据。
现在的问题是：如果第一次展开子树后，我在根节点 tree1下添加了一个子节点。当第二次展开子树（也就是上面说的第三次点击根节点tree1）的时候，子节点中并没有刚新增的节点。
### What is Expected?
希望展开子树的时候，显示当前最新子节点数据。

**Comment by furybean** [comment]
@kopheece 能否告知怎么添加的节点？现在应该可以做到根据数据自动生成节点的。

**Comment by kopheece** [comment]
@furybean  节点数据是从后台取的list  
功能大体如下：左边是tree组件，右边有个table，用来显示左边选中节点下的下级节点信息，table支持新增/删除节点。如果左边点击1级节点，则展示二级节点信息，同时右边table显示二级节点列表，如果在table那边新增/删除二级节点，左边tree组件不同时显示新增/删除的节点，就算左边的一级节点点击几次，都没同步到新增/删除的节点

**Comment by wumaohui** [comment]
请问一下怎么控制某些特定节点呀，我想要所有非子节点（没有子节点的节点）都不可选，但没有找到合适的方法，想请教一下您可还行~

**Comment by Leopoldthecoder** [comment]
@wumaohui 目前没有这个功能

**Comment by wumaohui** [comment]
@Leopoldthecoder 好吧，麻烦了~谢谢呀

**Comment by wilsonIs** [comment]
@wumaohui 我目前用了一个方法实现了selectLeafOnly的功能，点击node的时候会反悔当前的isLeaf状态，true的时候给当前的.el-tree-node__content加上.selected类，然后这个绑定是通过render-content设置v-bind:class实现的

**Comment by EasonShen1989** [comment]
@furybean  同一个节点第二次再点击箭头图标 （load | 加载子树数据的方法，不再执行了）请问什么原因啊？
