### ISSUE TITLE
The current-change event is not triggered when the [Bug Report] paging component total changes causes the current-page to change.

### ISSUE THREAD

**Issue by JinTZH** [ElemeFE/element#10677]
### Element UI version
2.3.2

### OS/Browsers version
window10/chrome 65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://codepen.io/jintzh-the-reactor/pen/vRMgOr](https://codepen.io/jintzh-the-reactor/pen/vRMgOr)

### Steps to reproduce
1.父组件正常使用分页组件
2.设置分页组件总数400，每页100条
3.然后翻页到第四页，设置总条数为200

### What is Expected?
分页组件内部current-page发生变化，
触发current-change事件

### What is actually happening?
分页组件内部current-page发生变化，
没有触发current-change事件，
父组件无法实时改变current-change

**Comment by Leopoldthecoder** [comment]
See https://github.com/ElemeFE/element/issues/10625
