### ISSUE TITLE
[Bug Report] under IE, the click button directly modifies the date component binding value, and the Google browser is normal

### ISSUE THREAD

**Issue by wlinshicong** [ElemeFE/element#10675]
### Element UI version
2.3.3

### OS/Browsers version
IE

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/drm7odb1/2/](https://jsfiddle.net/drm7odb1/2/)

### Steps to reproduce
1.如果直接点击按钮修改绑定值，页面显示时间不变，但是实际上绑定值已经改了
2.如果先点击日期选择器，再关闭，之后点击按钮就能正常显示了
3.在谷歌浏览器下，一切正常，直接点击按钮，页面显示的时间正常

### What is Expected?
1.希望在IE下能通过代码修改绑定值，更改显示的时间
2.或者在IE下能自定义按钮直接调用快捷选项的picker.$emit('pick',new Date())

### What is actually happening?
IE下无法通过修改绑定的V-model来更改时间

**Comment by Leopoldthecoder** [comment]
IE 输入框的行为有些怪异，不会对此做兼容处理。
