### ISSUE TITLE
[Bug Report] span-method -- Automatic merge cells do not meet expectations.

### ISSUE THREAD

**Issue by Ethan997** [ElemeFE/element#10673]
### Element UI version
2.3.3

### OS/Browsers version
OS 10.13.3/chrome 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/Ethan_HangZhou/a84t3erq/19/](https://jsfiddle.net/Ethan_HangZhou/a84t3erq/19/)

### Steps to reproduce
(1)点击添加，然后点击编辑 。（2）在rowindex===1的附件输入框内写如‘a’，然后点击完成。（3）重复以上操作，保证rowindex<3的附件内容是‘a’。 （4）在rowindex>3 && rowindex<5的附件输入框内输入相同的内容。

### What is Expected?
自动合并后的单元格行为正确

### What is actually happening?
row>3自动合并单元格才生效，且除了第一组内容相同的单元格合并后行为正确以外，其他合并后的单元格行为错误。如图：https://upload-images.jianshu.io/upload_images/6089846-1cd5f4779fa86b6a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by Ethan997** [comment]
Leopoldthecoder哥，如果看到了可不可以帮帮我？ 谢谢～

**Comment by Leopoldthecoder** [comment]
你的算法有问题，编辑前三行时，没有进入返回值的 if 块中。

**Comment by Ethan997** [comment]
Leopoldthecoder哥,我修改后前三行可以进入返回值的 if 块中了，但是for循环在设置rowspan和colspan为0时候，变量 j（ j 为可合并的具有相同内容的嵌套数组下标） 总是等于 0 （我觉得问题在代码**第57行**的else的块级作用域内）。我已经卡在这个地方很久了，Leopoldthecoder哥可以指点我一下吗？谢谢～
重现链接：https://jsfiddle.net/Ethan_HangZhou/a84t3erq/36/

**Comment by Ethan997** [comment]
Leopoldthecoder哥，今天已经把问题根源已经找到，晚上我修改代码。

**Comment by Ethan997** [comment]
@Leopoldthecoder 
Leopoldthecoder哥，我已经修复了编辑前三行时，没有进入返回值的 if 块的问题。但是表格行为还是有问题，我觉得问题在代码第59行的else块内，我已经卡在这里很久了，您可以帮我看一下吗？谢谢🙏～
重现链接：https://jsfiddle.net/Ethan_HangZhou/a84t3erq/37/

**Comment by Ethan997** [comment]
已经实现了自动合并单元格
