### ISSUE TITLE
[Bug Report] el-table bug of scroll y and max-height

### ISSUE THREAD

**Issue by lu0371** [ElemeFE/element#10678]
![tttttttt](https://user-images.githubusercontent.com/16933276/38658247-eb2b88b4-3e56-11e8-9438-710d6605b0b4.png)

### Element UI version
2.1.0

### OS/Browsers version
window 7/firfox 59.0.1 (64 位)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/944/](https://jsfiddle.net/pj71jkyw/944/)

### Steps to reproduce
1、set max-height of table
2、when current table rows greeter than 2 but the table height less than max-height
3、the scroll-y will not visible but place the table space，the row width is not 100% of the table width

### What is Expected?
the scroll-y will not visible and the row width is 100% of the table width

### What is actually happening?
the scroll-y will not visible but place the table space，the row width is not 100% of the table width

**Comment by hisland** [comment]
max-height, now, type number ok,  but when I pass  max-height="50vh", it's wrong, can we use `calc(50vh - headerHeight - footerHeight)`

![image](https://user-images.githubusercontent.com/417448/47357683-0b075c80-d6fa-11e8-80ec-cf4182864b9e.png)

**Comment by gcloutier** [comment]
same problem for, any issue someone?
