### ISSUE TITLE
[Bug Report] New Installation - Error upon run - Missing vue-style-loader

### ISSUE THREAD

**Issue by GarlandM** [ElemeFE/element#10670]
### Element UI version
2.3.3

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
- Install vuejs via vue-cli
- Install Nuxt
- Install Element

Use: https://glitch.com/edit/#!/nuxt-element-ui?path=plugins/element-ui.js:6:0 to configure Element with Nuxt

- npm run dev

These dependencies were not found:

* !!vue-style-loader?{"sourceMap":true}!css-loader?{"sourceMap":true,"minimize":false,"importLoaders":0,"alias":{"/assets":"D:\\Tali\\assets","/static":"D:\\Tali\\static"}}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-d8adad8a","scoped":false,"hasInlineConfig":true}!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./nuxt-error.vue in ./.nuxt/components/nuxt-error.vue
* !!vue-style-loader?{"sourceMap":true}!css-loader?{"sourceMap":true,"minimize":false,"importLoaders":0,"alias":{"/assets":"D:\\Tali\\assets","/static":"D:\\Tali\\static"}}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-774a78a2","scoped":false,"hasInlineConfig":true}!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./nuxt-loading.vue in ./.nuxt/components/nuxt-loading.vue
* !!vue-style-loader?{"sourceMap":true}!css-loader?{"sourceMap":true,"minimize":false,"importLoaders":0,"alias":{"/assets":"D:\\Tali\\assets","/static":"D:\\Tali\\static"}}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-419267d0","scoped":false,"hasInlineConfig":true}!element-ui/lib/theme-default/index.css in ./layouts/default.vue
* !!vue-style-loader?{"sourceMap":true}!css-loader?{"sourceMap":true,"minimize":false,"importLoaders":0,"alias":{"/assets":"D:\\Tali\\assets","/static":"D:\\Tali\\static"}}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-1b011d9c","scoped":false,"hasInlineConfig":true}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./index.vue in ./pages/index.vue

### What is Expected?
Page load as normal.

### What is actually happening?
Errors out, missing dependencies.

Installing said dependencies does not solve the issue.

**Comment by Leopoldthecoder** [comment]
Please minify your project and put it in a GitHub repo.
