### ISSUE TITLE
[Feature Request]  Hope that the form validation framework has an active method to trigger the specified "el-form-item" error message

### ISSUE THREAD

**Issue by Baifann** [ElemeFE/element#10679]
### Existing Component
是

### Component Name
form

### Description
后台可能也会进行表单的校验，校验完成之后会将错误的信息进行返回，比方说返回了一个prop为name的el-form-item有「一个长度太长」的问题，这个时候能否让我主动去触发这个el-form-item，给出后台返回的错误提示。

**Comment by Leopoldthecoder** [comment]
使用 `error` 属性。
