### ISSUE TITLE
[Feature Request] Unable to use Vue filters on data within the table component.

### ISSUE THREAD

**Issue by nickclicksco** [ElemeFE/element#10689]
### Existing Component
Yes

### Component Name
el-table

### Description
Hi, it would nice if we could use Vue filters on table data like so:
```
      <el-table-column
        prop="created_at | moment"
        label="Date"
        width="180">
      </el-table-column>
```

Obviously this wouldn't work as I am passing a string. I feel limited without being able to use filters on the data.

In the mean time does anybody know of any other methods that allow me to  use my Vue filters with the el-table?

**Comment by Leopoldthecoder** [comment]
`:prop="created_at | moment"`

**Comment by koala91** [comment]
@nickclicksco  the same question

**Comment by Leopoldthecoder** [comment]
:prop="'created_at' | moment"

**Comment by tracker1999** [comment]
:prop="'created_at' | moment"

我这么设置不生效啊，全局filter mement收到的参数是字符串【created_at】

**Comment by kxion** [comment]
我怀疑，这个created_at 的 _ ，导致错误
