### ISSUE TITLE
[Bug Report] expansion and rise menu, the current activation menu is inconsistent

### ISSUE THREAD

**Issue by lwzhang** [ElemeFE/element#10682]
### Element UI version
2.3.3

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、收起导航菜单，点击弹出的某个子菜单
2.、展开导航菜单，查看当前激活菜单

### What is Expected?
希望展开与收起菜单时，当前激活菜单能一致

### What is actually happening?
展开导航菜单与收起导航菜单时，激活的菜单不一致

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by lwzhang** [comment]
那个链接是饿了么官方文档的例子，原来你们自己也打不开啊😂
