### ISSUE TITLE
[Feature Request] Custom template for label attribute of select option

### ISSUE THREAD

**Issue by arslanyunus** [ElemeFE/element#10685]
### Existing Component
Yes

### Component Name
select

### Description
Is there a possibility that you can add a feature that give us a chance to insert customized HTML templates into the label(shown text of selected option).

**Comment by wacky6** [comment]
It's not supported now. Ask @Leopoldthecoder to see if this is a PR-welcome feature.
Current design used input, which is required for making select filterable/can choose with keyboard only.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
