### ISSUE TITLE
[Feature Request] How to add click on icon

### ISSUE THREAD

**Issue by kangbb** [ElemeFE/element#10693]
### Existing Component
Yes

### Component Name
icon

### Description
Can I add a click to the icon? I try as this, but it doen't work. What should I do to achieve it?
```
<i src="el-icon-third-document_add control" @click="appendFile"></i>
<i class="el-icon-third-folder_add control" @click="appendDir"></i>
```

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
