### ISSUE TITLE
[Bug Report] El-date-picker selector  binding Date object is not displayed under IE11 browser

### ISSUE THREAD

**Issue by ZhanYishu** [ElemeFE/element#10694]
### Element UI version
2.3.4

### OS/Browsers version
IE11

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/zhanzf/dacwdatv/](https://jsfiddle.net/zhanzf/dacwdatv/)

### Steps to reproduce
El-date-picker selector  binding Date object is not displayed under IE11 browser

### What is Expected?
El-date-picker selector  binding Date object could display normally under IE11 browser

### What is actually happening?
El-date-picker selector  binding Date object is not displayed under IE11 browser

**Comment by ZhanYishu** [comment]
New Date（timestamp）is invalid under IE11

**Comment by ZhanYishu** [comment]
1.

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/38776258-9f4172b6-40c6-11e8-8c5c-55ffe2a38771.png)

Cannot reproduce this.

**Comment by ZhanYishu** [comment]
I am so sorry about it. It reproduces when opening macro task queue width setTimeout api.
Hope you could review it. [](https://jsfiddle.net/zhanzf/dacwdatv/)

**Comment by Leopoldthecoder** [comment]
Then it's duplicate of https://github.com/ElemeFE/element/issues/8548
