### ISSUE TITLE
简单封装table，v-for动态设置表头及列，配置的第一列总会跑到最后一列

### ISSUE THREAD

**Issue by qianduanwuzi** [ElemeFE/element#10698]
ElementUI version
1.0.0

OS/Browers version
Chrome 

Vue version
2.0.0

问题描述
假设场景
使用el-table进行封装，根据配置动态生成表格。

现存问题
v-for动态设置表头及列，配置的第一列总会跑到最后一列

组件：
![es 66o1ylq95lmitlp m9o0](https://user-images.githubusercontent.com/25190248/38720106-8336e290-3f27-11e8-957e-20f372181275.png)

前端使用：
![1 6cr 3 bg 5gh4 ehenc v](https://user-images.githubusercontent.com/25190248/38720147-a9d75c18-3f27-11e8-970b-1ea6abd3a094.png)
![u 0 2kqw c _j 4i1 538](https://user-images.githubusercontent.com/25190248/38720167-bd708150-3f27-11e8-90b1-27fd7461350f.png)

实际view：
![ad 52k9i 6 pm 8x z _ lo](https://user-images.githubusercontent.com/25190248/38720197-dba212a6-3f27-11e8-84ee-6f691623d825.png)

已使用方案：
给el-table-column加key；表格数据变化重载table； 都没作用。
急啊~

**Comment by TJ666** [comment]
刚解决过这个问题，把你的span标签去掉就好了！，使用template替代！！！

**Comment by qianduanwuzi** [comment]
这我写的组件。就没必要再提供测试代码了吧。发现很多人提了这个bug。但未看到最佳办法。

**Comment by qianduanwuzi** [comment]
how？ @TJ666

**Comment by qianduanwuzi** [comment]
直接把span标签替换成tempalte？？？@TJ666

**Comment by TJ666** [comment]
你现在所有的column都被一个span包着，改成
<el-table>
    <template v-for="xxxx">
         <el-column>

**Comment by qianduanwuzi** [comment]
tks。已成功@TJ666

**Comment by TJ666** [comment]
循环template

**Comment by TJ666** [comment]
OK
