### ISSUE TITLE
[Bug Report]  Dropdown and Tabs would trigger reflow when applying style

### ISSUE THREAD

**Issue by marswong** [ElemeFE/element#10695]
### Element UI version
2.3.3

### OS/Browsers version
macOS 10.13.4 / Chrome 65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1485/](https://jsfiddle.net/mmx38qxw/1485/)

### Steps to reproduce
Just run the demo to see the rendering of page

### What is Expected?
reflow should not be triggered and it'd be better to show a export of the Table before completion of computation

### What is actually happening?
as you see, the label of TabPane and item of Dropdown would be reflowed at startup before table is rendered.

**Comment by marswong** [comment]
the screenshot of our website:

<img width="1440" alt="screen shot" src="https://user-images.githubusercontent.com/10388933/38715771-bd9e9044-3f0f-11e8-92c7-e80fbc5e5340.png">

**Comment by ryouaki** [comment]
I have the same problem
