### ISSUE TITLE
[Feature Request] Floating action button

### ISSUE THREAD

**Issue by ViljoenJG** [ElemeFE/element#10690]
### Existing Component
No

### Component Name
FloatingActionButton

### Description
One feature I miss in element ui that exists in a lot of other libraries is the Floating action button like the Compose button in Google's Inbox

[Examples](https://material.io/guidelines/components/buttons-floating-action-button.html)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
