### ISSUE TITLE
[Feature Request] Toolbar component

### ISSUE THREAD

**Issue by kurucu** [ElemeFE/element#10705]
### Existing Component
No

### Component Name
N/A

### Description
It would be great to be able to create a toolbar component, to house buttons / button groups, text boxes etc, along with alignment facilities (maybe left, centre and right). At the moment I hack the card component for this, but it's not very elegant!

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by kurucu** [comment]
That's fair, you can take it in any direction you like. But could you please explain why? What guidelines or principles are you using to direct your decision making so that others can understand them? When it's hard to tell what a products future is, it's much harder to convince yourself its the right tool to use on your project; and I think opening a dialogue with your users would really establish some trust.
