### ISSUE TITLE
Problems in the [Bug Report] Merge Table

### ISSUE THREAD

**Issue by ablikim915** [ElemeFE/element#10702]
### Element UI version
2.3.3

### OS/Browsers version
win10 / Google Chrome 已是最新版本 版本 65.0.3325.181（正式版本） （32 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/ablikim/mmx38qxw/1492/](https://jsfiddle.net/ablikim/mmx38qxw/1492/)

### Steps to reproduce
重现链接上直接访问页面就能看的到问题的。

### What is Expected?
我想要的效果是，当给第三列或者第三列后面的列（第四，第五列）添加大于一行内容的时候显示的正常。

### What is actually happening?
这是sku表格，当sku添加到三列并且第三列都是一行的时候没问题的（后面的四个输入框是固定的，每行对应一个。前面的规格部分2列的时候加多少行都正常的。），给第三列再加一行变成两行的时候就出现那种问题，就是把合并过的第一列添加到第三列的第一行。（我的重现链接就是有问题的情况）。

**Comment by Leopoldthecoder** [comment]
你的算法有误：https://jsfiddle.net/leopoldthecuber/mmx38qxw/1619/ 。可以在控制台看到，第三行第一列和第七行第一列都错误地占据了四行。
