### ISSUE TITLE
[Feature Request] Notification type class in component

### ISSUE THREAD

**Issue by nancoder** [ElemeFE/element#10700]
### Existing Component
Yes

### Component Name
Notification

### Description
Currently, all the notifications, no matter what type they are, have the same el-notification class, I would like the notification type were added to the notification element node css class to set custom css properties for each notification type.

**Comment by Leopoldthecoder** [comment]
Use `customClass`.

**Comment by nancoder** [comment]
Thank you @Leopoldthecoder, is there a way to set default options, incluiding `customClass` for each notification type? Instead of adding  a `customClass` in every new notification.
