### ISSUE TITLE
[Bug Report] global configuration size is not effective in $confirm

### ISSUE THREAD

**Issue by islenbo** [ElemeFE/element#10708]
### Element UI version
2.3.4

### OS/Browsers version
MacOS Chrome65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1599/](https://jsfiddle.net/mmx38qxw/1599/)

### Steps to reproduce
- 通过全局设置组件尺寸 `Vue.use(ElementUI, {size: 'mini'});`
- 在function使用 `this.$confirm('确认删除？');`，导出对话框的尺寸还是为small

### What is Expected?
对话框尺寸应该与全局配置一致

### What is actually happening?
对话框尺寸与全局配置不一致

**Comment by Leopoldthecoder** [comment]
这个还请通过 CSS 来改变，因为 `size` 的初衷是为了满足在页面空间不大时能够放下更多的组件，而 MessageBox 作为弹出类组件，并不太会受到页面空间尺寸的影响。
