### ISSUE TITLE
[Bug Report] Date Picker Blur and input values

### ISSUE THREAD

**Issue by SatanEnglish** [ElemeFE/element#10719]
### Element UI version
2.3.4

### OS/Browsers version
Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1678/](https://jsfiddle.net/mmx38qxw/1678/)

### Steps to reproduce
Type "abc" into date box.
Click outside box.

OR

Put in 2015-10-10 (e.g wrong format)
Click outside box

### What is Expected?
The information on the obj to be updated to "abc" inside the blur method.

OR

The date box to blank out the value if it's not valid

### What is actually happening?
The data is not getting to the blur event as it should be.
The date box is not being updated

**Comment by wacky6** [comment]
The point of using date-picker is to disallow malformed dates. Why would you need raw user input.

**Comment by SatanEnglish** [comment]
Well at the moment it's because it allows values that are not dates.
Basiclly I need it to either give me the malformed dates in the blur so **I** can fix it.
**OR** It needs to not let me put them in.

I'd be happy with either of these cases currently it doesn't do either.

**Comment by SatanEnglish** [comment]
My main concern here is as follows.
User puts in 10-2015 which doesn't actually fire off any change event.
They now believe that the date has been accepted however it hasn't!

At least if it's wiped they have some feedback that it's not correct.

**Comment by SatanEnglish** [comment]
@wacky6 
Also If I select a date lets say '10-10-2015'.
Then put 'abc' in I'd expect the underlying value to reflect whats in the input. 
(Currently stays 10-10-2015)

e.g.
If the best thing to do is wipe then the value should be null or ''.
If instead the value stays as '10-10-2015' then the text box should revert to '10-10-2015' when I click outside of it.

hope this is enough information to go off.

**Comment by wacky6** [comment]
I just checked the code. Current behavior (preserving malformed input) is to remain consistent with legacy 1.0 version's behavior.

Nuking invalid input seems a good idea. Ask @Leopoldthecoder if such change is acceptable.

---

At the time being, you can check date-picker's `userInput` to see whether user input is accepted. But I guess we can come to a resolution soon enough.

**Comment by SatanEnglish** [comment]
@wacky6 
Can you give me an example of how I can check `userInput ` for this?
Fiddle example would be really helpful as it's roadblocking something I'm doing.

**Comment by wacky6** [comment]
Use vue's ref.

<el-date-picker ref="picker" />

In code:
this.$refs.picker.userInput

**Comment by Leopoldthecoder** [comment]
I think we should restore the previously entered (or picked) valid date after blur. If there's no previous value, just clear the input. Also see #9790

**Comment by Leopoldthecoder** [comment]
Closed in #10749
