### ISSUE TITLE
[Bug Report] uses multiple el-date-picker different Type interfaces at the same time

### ISSUE THREAD

**Issue by lixing0323** [ElemeFE/element#10715]
### Element UI version
2.3.4

### OS/Browsers version
mac 10.13.4 / Chrome 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1630/](https://jsfiddle.net/mmx38qxw/1630/)

### Steps to reproduce
1. html 是这样写的  <el-date-picker class="margin-left-30" v-model="today" :type="dateType" :format="getWeekFormat" :picker-options="pickerDate" size="small">  </el-date-picker> 。dateType根据radio-button的选择，分别为date/week/month/year，如下图：
![avatar](http://chuantu.biz/t6/286/1523778464x-1566638255.png) 

2. 第一次选择radio-button-周，然后弹出下拉列表，不选择。如下图
![avatar](http://chuantu.biz/t6/286/1523780111x-1404795433.png)

3. 第二次选择radio-button年，弹出下拉列表，界面错乱。如下图
![avatar](http://chuantu.biz/t6/286/1523779426x-1566657848.png)

### What is Expected?
这个应该是个bug吧，能否修改？

### What is actually happening?
这个应该是个bug吧，能否修改？

**Comment by Leopoldthecoder** [comment]
加 `key`：https://jsfiddle.net/leopoldthecuber/mmx38qxw/1635/ 。
