### ISSUE TITLE
增加Message的样式自定义

### ISSUE THREAD

**Issue by chenkby** [ElemeFE/element#1071]
能不能给el-message加个type类。比如当前type="error"，给el-message的父节点加个"el-message-error"。现在只有个el-message，想修改下不同type下的样式，无从下手啊。

当然，并不是说你们现在的message外观有什么不好，只是，能够自己定制下更好。。

**Comment by michaellyu** [comment]
有时需求可能是一个比较轻量的提示，比如仅仅想要一个纯文本色块的提示message。这里的type却是必须的，就有一定的矛盾。

**Comment by Leopoldthecoder** [comment]
1.0.7 版本已可以为 Message 指定类名。
