### ISSUE TITLE
[Feature Request] recommends that the sass file variable be strengthened. The compact style can be output.

### ISSUE THREAD

**Issue by c5ms** [ElemeFE/element#10728]
### Existing Component
否

### Component Name
样式主题.

### Description
深爱贵库.代表公司感激不尽.
公司项目属于企业/政府类项目.比较需要的是那种紧凑主题,类似ExtJs4.x那种.
已经在基础上修改处一套主题.但是毕竟不是办法,
如果el的sass文件稍微深度修改,升级还是比较费劲的.
故此.冒昧请求对样式表进行深度升级.
增加变量,允许通过全局修改计算出紧凑主题.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
