### ISSUE TITLE
Switch绑定width的问题？

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#1072]
### OS/Browers version
macOS/Chrome 50

### Reproduction Link
http://jsfiddle.net/pu1oa4qy/1/

### What is Expected?
当给Switch设定width 并绑定时 第一次切换会无效（卡住？）

**Comment by Leopoldthecoder** [comment]
是 bug，下个版本修复。

**Comment by terranc** [comment]
查了半天问题。。。原来是width

**Comment by Kingwl** [comment]
2333

**Comment by Leopoldthecoder** [comment]
Fixed in #1076
