### ISSUE TITLE
[Bug Report] cascaded selector props properties cannot be rendered in value

### ISSUE THREAD

**Issue by DougFlands** [ElemeFE/element#10720]
### Element UI version
2.3.4

### OS/Browsers version
chrome65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/6bb879gj/](https://jsfiddle.net/6bb879gj/)

### Steps to reproduce
选择完后点击a按钮，

### What is Expected?
value正常绑定

### What is actually happening?
打印中绑定数据为label值不为value值

**Comment by Leopoldthecoder** [comment]
```js
props: {
  value: 'label',
  children: 'cities'
}
```

你这里显式地指定了将 `label` 字段作为值，自然绑定值是 `label`。
