### ISSUE TITLE
Render-header is invalid when [Bug Report] el-table-column type=index

### ISSUE THREAD

**Issue by alasq** [ElemeFE/element#10723]
### Element UI version
2.3.4

### OS/Browsers version
win7 x64/chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/7t4juvgj/](https://jsfiddle.net/7t4juvgj/)

### Steps to reproduce
看演示地址吧

### What is Expected?
index也能自定义渲染方式

### What is actually happening?
render-header无效

**Comment by Leopoldthecoder** [comment]
不是 bug，所有指定了 `type` 的列都不支持 `render-header`，但是 `type="index"` 和 `type="expand"` 的列支持使用 `label`。
