### ISSUE TITLE
[Bug Report] v2.0.0 is upgraded to v2.3.4, and the project runs out

### ISSUE THREAD

**Issue by axl-axl** [ElemeFE/element#10733]
### Element UI version
2.0.0

### OS/Browsers version
window

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/eywraw8t/39691/](https://jsfiddle.net/eywraw8t/39691/)

### Steps to reproduce
因为是升级版本所以没有办法给出复现办法，但是我从2.0.0版本开始升级测试，发现升级到2.0.4出现这个问题。在2.0.4版本之前每个连接都是可以正常访问，但是升级到2.0.4点击链接之后就一直加载，直到浏览器报崩溃。
看到版本升级信息，说是“提升 Cascader、Dropdown、Message、Notification、Popover、Tooltip、Tree 的可访问性”。怀疑是这个升级后的原因，因为我有用到message。
我现在完全不知道，问题到底出来哪儿，因为我点击以后什么报错都没有，但是整个页面就是死掉了。
路由我用的是vue-router

### What is Expected?
期望我的程序能够正常的跑起来，或者有个问题的方向，我现在真的是蒙圈了。

### What is actually happening?
没有任何错误提示。。。

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
