### ISSUE TITLE
[Bug Report] header-row-style

### ISSUE THREAD

**Issue by danny00lo** [ElemeFE/element#10730]
### Element UI version
0.1.0

### OS/Browsers version
window7

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1690/](https://jsfiddle.net/mmx38qxw/1690/)

### Steps to reproduce
最新版css完全没有效果

### What is Expected?
能够更改

### What is actually happening?
不能更改

**Comment by danny00lo** [comment]
in 2.0.8 can change the style
However in 2.3.4 , it is not work

**Comment by Leopoldthecoder** [comment]
2.1.0 对 Table 进行了一定程度的重构，目前表头的背景色是由
```css
.el-table th, .el-table tr {
    background-color: #fff;
}
```
定义的，因此修改 `<tr>` 元素的背景色后，仍会被 `<th>` 的背景色覆盖。如果要修改背景色，请使用 `header-cell-style`：https://jsfiddle.net/leopoldthecuber/mmx38qxw/1705/
