### ISSUE TITLE
[Bug Report] el-input cannot set placeholder

### ISSUE THREAD

**Issue by viewweiwu** [ElemeFE/element#10738]
### Element UI version
0.1.0

### OS/Browsers version
win10 / chrome65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/9tyszwuo/](https://jsfiddle.net/9tyszwuo/)

### Steps to reproduce
直接看输出

### What is Expected?
render 函数可以设置 placeholder

### What is actually happening?
使用 render 函数，el-input 设置 placeholder 无效

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/9tyszwuo/5/ Guess it has something to do with us using `v-bind="$attrs"` to handle native attributes.
