### ISSUE TITLE
[Bug Report] Cascader unremoves filterable cursor and unremoves

### ISSUE THREAD

**Issue by zhonghaozhang** [ElemeFE/element#10739]
### Element UI version
2.3.4

### OS/Browsers version
MacOs10.12.6、谷歌版本 65.0.3325.181（正式版本）（64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/xyhxyw/kp3ffLtw/](https://jsfiddle.net/xyhxyw/kp3ffLtw/)

### Steps to reproduce
我这边项目使用到级联选择器开启filterable，出现了光标无法移动的问题，当然在官方文档demo上也是这个问题，我认为是bug，在选择一个选项以后，无法移动删除，光标强制在最前方，如果想在输入搜索也是可以但是体验非常差，这个功能我觉得应该尽快修复一下。

### What is Expected?
选择一个选项以后也应该可以移动光标重新选择搜索

### What is actually happening?
实际不可以移动光标删除，只能重新输入，但是在重新输入的时候原文字还在，很不美观，建议调整

**Comment by ziyoung** [comment]
@zhonghaozhang 禁止**光标移动**还是比较好一点。假设现在输入框中的内容是 `
指南 / 设计原则 / 可控`，移动光标删除了一些字，变成了`设计原则 / 可控`，这样的话，是没有相匹配的选项的。
