### ISSUE TITLE
[Bug Report] under IE9, uploading pictures frequently false 'URL undefined'

### ISSUE THREAD

**Issue by gaoyujie** [ElemeFE/element#10732]
### Element UI version
2.3.4

### OS/Browsers version
windows10/IE9

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1302/](https://jsfiddle.net/mmx38qxw/1302/)

### Steps to reproduce
点击上传按钮，选择图片或者文件，报错

### What is Expected?
正常上传

### What is actually happening?
报错‘URL未定义’

**Comment by Leopoldthecoder** [comment]
Element is not compatible with IE9.
