### ISSUE TITLE
[Feature Request] Message is not displayed in the visual area.

### ISSUE THREAD

**Issue by qqcbqqkcel** [ElemeFE/element#10742]
### Existing Component
是
### Component Name
Message
### Description
当页面滚动到底时，在iframe中（iframe中也是一个vue项目）调用message将会看不到信息（消息会在上面显示）
el-dialog <iframe height="2000"> el-dialog

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
