### ISSUE TITLE
The [Bug Report] select component is enclosed in a layer of dialog components, and the dropdown will be blocked by the mask layer

### ISSUE THREAD

**Issue by anyisky** [ElemeFE/element#10747]
### Element UI version
2.2.2

### OS/Browsers version
mac 10.12.6/chrome 63.0.3239.132

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1747/](https://jsfiddle.net/mmx38qxw/1747/)

### Steps to reproduce
直接在父组件里定义子组件是复现不了，要用import方式引入子组件才回复现这情况，jsfiddle里不太好组织这个demo
1、将dialog组件封装成一个组件，方便页面调用
2、在页面上调用被封装过的dialog组件
3、dialog组件中放select，datepicker等带有popover的组件
4、弹窗出来后，点击select框，首次点击后，select的下拉菜单会被遮罩层盖住，再点一次会出来

### What is Expected?
封装后的dialog，每次点击select框，都能正常出现下拉

### What is actually happening?
封装后的dialog，首次点击select框，下拉会被盖住

**Comment by Leopoldthecoder** [comment]
那么请准备一个能复现的项目并上传至 GitHub，然后开一个新 issue。
