### ISSUE TITLE
[Bug Report] form check automatically triggers bug second bombs

### ISSUE THREAD

**Issue by zphtown** [ElemeFE/element#10748]
### Element UI version
2.3.4

### OS/Browsers version
window/google

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1752/](https://jsfiddle.net/mmx38qxw/1752/)

### Steps to reproduce
图形验证码，短信验证码随便输，点击下一步，form校验被自动触发，这里与第一次提的bug不一样，此时只有一个form，这种情况怎么解决

### What is Expected?
图形验证码，短信验证码随便输，点击下一步，form校验不被自动触发

### What is actually happening?
图形验证码，短信验证码随便输，点击下一步，form校验被自动触发

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/1755/
