### ISSUE TITLE
el-input 和 el-select在设置placeholder不起效果。

### ISSUE THREAD

**Issue by xuanGetit** [ElemeFE/element#10743]
element-ui版本为2.3.4，vue版本2.2.1。在vue文件中，使用el-input的时候，发现placeholder不显示。在浏览及查看元素发现，placeholder属性真正添加到了包裹input元素的外围div上了。现在我的问题已经解决了，我把element回退到2.2.1版本就没问题了

**Comment by 1003047593** [comment]
题主，我也是刚碰到这个问题，  element-ui  v1.4=> input.vue 中 有段这个代码placeholder: String,而2.23中没有。
