### ISSUE TITLE
[Bug Report] form rows merge in disorder

### ISSUE THREAD

**Issue by osinglee** [ElemeFE/element#10751]
### Element UI version
2.3.4

### OS/Browsers version
macOS10 / chrome65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/8ob275v7/8/](https://jsfiddle.net/8ob275v7/8/)

### Steps to reproduce
合并表格行后，缩小浏览器宽度，使表格出现横向滚动条，会发现表格样式不对称

### What is Expected?
合并后应与原样式保持一致

### What is actually happening?
表格样式不对称

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/8ob275v7/10/

**Comment by osinglee** [comment]
@Leopoldthecoder Thank you
