### ISSUE TITLE
[Feature Request] Dynamic height for tables with fixed header

### ISSUE THREAD

**Issue by lucas-bremond** [ElemeFE/element#10750]
### Existing Component
Yes

### Component Name
Table

### Description
Hi!

Would that be difficult to also define the table height (with fixed headers) dynamically?

Ideally, I would like the table to use 100% of the parent div.
The problem is that the parent div can be resized, I currently need to use signals to re-render the table whenever the parent div height changes (using computed properties and $refs).

This is not very elegant and introduces coupling between components...

Do you think this behavior could be embedded into the table component itself?

Cheers!

**Comment by Leopoldthecoder** [comment]
I think it can be done using `height` prop: https://jsfiddle.net/wfxbxmgc/4/

**Comment by lucas-bremond** [comment]
This is actually what I am already doing and this is the problem.

Height is absolute, in pixels.

I would like to set height = 100%.

**Comment by Leopoldthecoder** [comment]
The `height` of Table **is** 100%. I only set the parent container's height in px to mimic the "resize" you mentioned.

**Comment by lucas-bremond** [comment]
@Leopoldthecoder You're absolutely right, thank you so much. It's actually working like a charm.
