### ISSUE TITLE
[Bug Report] is there a plan to fix the bug #9916?

### ISSUE THREAD

**Issue by xyhxyw** [ElemeFE/element#10757]
### Element UI version
2.3.4

### OS/Browsers version
IE11

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/xyhxyw/kp3ffLtw/](https://jsfiddle.net/xyhxyw/kp3ffLtw/)

### Steps to reproduce
see detail on [#9916](https://github.com/ElemeFE/element/issues/9916)

### What is Expected?
fix this bug

### What is actually happening?
the latest  element-ui version is 2.3.4, but it seems there is no plan to fix the bug since element-ui 2.2.0.

**Comment by Leopoldthecoder** [comment]
目前没有人手。有进展会在 #9916 更新。
