### ISSUE TITLE
[Bug Report] checkbox radio modified style invalid

### ISSUE THREAD

**Issue by WiFiUncle** [ElemeFE/element#10756]
### Element UI version
2.3.4

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
		
<el-checkbox v-model="checked" fill="#EFF" text-color="#000">姗姗来迟</el-checkbox>
    <el-radio :label="9" fill="#ccc">备选项</el-radio>

### What is Expected?
自定义checkbox的颜色

### What is actually happening?
没变色

**Comment by WiFiUncle** [comment]
http://runjs.cn/code/czq7tesj
由于不能直接贴演示地址。就写这里了

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/38861134-5eaa3f5e-4264-11e8-8977-5528d14aed18.png)

仅对按钮形式的 Checkbox，即 `<el-checkbox-button>` 有效：https://jsfiddle.net/jn6nakpy/1/
