### ISSUE TITLE
[Bug Report] ie 11, select component of filterable, often appear unable to input filtering conditions

### ISSUE THREAD

**Issue by nightost** [ElemeFE/element#10759]
### Element UI version
2.3.4

### OS/Browsers version
windows/ie11

### Vue version
2.0.7

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1758/](https://jsfiddle.net/mmx38qxw/1758/)

### Steps to reproduce
1. 在ie11中打开重现链接（官网链接同样情况[官网](http://element.eleme.io/#/zh-CN/component/select)）
2. 当下拉存在，或者部分其他情况
3. 无法输入过滤文字

### What is Expected?
在ie11中可以正常输入过滤条件

### What is actually happening?
在ie11中可以不可以正常输入过滤条件

**Comment by Leopoldthecoder** [comment]
Duplicate of https://github.com/ElemeFE/element/issues/10403
