### ISSUE TITLE
Whether the authentication information of the [Feature Request] el-form component supports the mouse hover to be displayed in the form of tooltip

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#10758]
### Existing Component
是

### Component Name
el-form

### Description
当表单项验证失败的时候,只对表单项进行标红,当鼠标移上去之后以tooltip形式展示显示错误信息.

**Comment by Leopoldthecoder** [comment]
可以自己实现：https://jsfiddle.net/zt96yzmp/5/
