### ISSUE TITLE
表单内使用复合型输入框,el-select 异常,且错位

### ISSUE THREAD

**Issue by Teddy-Zhu** [ElemeFE/element#1075]
**ElementUI version**

1.0.0

**OS/Browers version**

macOS/Chrome 54

**Vue version**

2.0.5

**Steps to reproduce**

http://jsfiddle.net/vx687kby/2/

**What is Expected?**

正常使用

**What is actually happening?**

input 内嵌 select , select功能异常,且错位

选择select内容后无反应, 查询绑定的model无变化

**Comment by Leopoldthecoder** [comment]
我看到你更新了 demo，现在功能上没问题了。内嵌的 select 的宽度需要自己加样式来指定，比如：
```CSS
.el-select .el-input {
  width: 200px;
}
```
高度差了 1 像素的问题下个版本修正。

**Comment by Teddy-Zhu** [comment]
@Leopoldthecoder  我这边看到除了错位是有问题的, select 无法使用
![image](http://ww2.sinaimg.cn/mw690/005ZDRGHgw1f9v4vq2rxbg30f104u0sx.gif)

**Comment by Teddy-Zhu** [comment]
@Leopoldthecoder  额 明白了 宽度太小导致遮住了结果 , thx
