### ISSUE TITLE
[Bug Report]el-tree will be re-rendered if it's in a v-for cycle

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#10767]
### Element UI version
2.3.4

### OS/Browsers version
all

### Vue version
2.5.4

### Reproduction Link
https://jsfiddle.net/x2oz49go/21/

### Steps to reproduce
1. check a node of the tree
2. try to check another one
3. the tree will totally been re-rendered
4. comment `<div>{{selected}}</div>`
5. repeat step 1 to 2, there will be no problem any more

### What is Expected?
don't re-render the tree even if `selected` is in use

**Comment by Leopoldthecoder** [comment]
Not an Element bug.

`:data="[item]"` You should avoid writing things like this. This is an array literal, which will cause a re-render when Vue updates. Passing a variable instead will work: https://jsfiddle.net/x2oz49go/32/
