### ISSUE TITLE
[Feature Request] Switch static value disables creating new template.

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#10762]
### Existing Component
Yes

### Component Name
Switch

### Description
This line has a static value which is 20. It is the witdh/height of switch dongle. It doesn't allow different sizes. So i can't create new theme by just using css files.
https://github.com/ElemeFE/element/blob/dev/packages/switch/src/component.vue#L109

BTW. I am creating the theme from source code because other options have issues or bugs. Thanks.

**Comment by Leopoldthecoder** [comment]
Currently you can change its size using CSS: https://jsfiddle.net/leopoldthecuber/3gs7gs6v/4/ . We do have plans to allow users to customize its height (you can already change its width with the `width` prop).

**Comment by atilkan** [comment]
So i have to give one param with prop one param by overwriting css.
