### ISSUE TITLE
[Form]希望 validate 支持多级验证

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#1077]
### ElementUI version
1.0.0

### Vue version
2.0.5

### Reproduction Link
http://jsfiddle.net/yn6ymg6r/1/

### Steps to reproduce
点击打开弹框，点击加或减，比如导致`require`验证错误，因为`el-input-number`绑定的是二级的

**Comment by baiyaaaaa** [comment]
#1363

**Comment by magang0425** [comment]
这个现在是支持了吗?为什么最新版本还是不行
