### ISSUE TITLE
[Bug Report] el-slider created using Render function resets to '0' on dragend

### ISSUE THREAD

**Issue by OpsSingular** [ElemeFE/element#10775]
### Element UI version
2.3.4

### OS/Browsers version
Windows 10 / Chrome 65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/vuzn7usg/8/](https://jsfiddle.net/vuzn7usg/8/)

### Steps to reproduce
Drag slider to the right and end the drag

### What is Expected?
on dragend, the value at which the slider stops should be current value

### What is actually happening?
on dragend, the slider resets to '0' value

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/vuzn7usg/11/

**Comment by OpsSingular** [comment]
Thanks
