### ISSUE TITLE
The [Bug Report] table uses a fixed column, a multilevel table, and a filtering error.

### ISSUE THREAD

**Issue by NightingaleM** [ElemeFE/element#10773]
### Element UI version
2.3.4

### OS/Browsers version
Windows10, Chrome Version 65.0.3325.181 (Official Build) (64 bits)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/18yjLykd/64/](https://jsfiddle.net/18yjLykd/64/)

### Steps to reproduce
展开展开行，在展开行中的表格进行筛选

### What is Expected?
子表格筛选后，无论是父表格固定列覆盖范围内还是非固定列范围，都将同步更新出筛选后的数据

### What is actually happening?

父表格使用固定列、展开行
在展开行内有子表格，子表格使用了筛选，
当使用筛选后，数据更新时，父表格固定列宽度中内容不会变
（如果筛选是在固定列宽度中执行的，那么非固定部分数据不变）
这样便导致格式、数据错乱

**Comment by Leopoldthecoder** [comment]
这是实现的时候就考虑到的问题，当时的实现就决定了 type="expand" 无法与锁定列一块使用。

完整回答见这里：#8994
