### ISSUE TITLE
When input size is small text is not v-center

### ISSUE THREAD

**Issue by liuhuaxia** [ElemeFE/element#10787]
### Element UI version
2.3.4

### OS/Browsers version
all

### Vue version
2.5.17-beta.0

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/input](http://element.eleme.io/#/zh-CN/component/input)

### Steps to reproduce
样式调整

### What is Expected?
font-size改为偶数

### What is actually happening?
font-size为奇数

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
