### ISSUE TITLE
In [Bug Report] form, when rule's trigger is'blur, change', check invalidation.

### ISSUE THREAD

**Issue by athena0304** [ElemeFE/element#10785]
### Element UI version
2.3.4

### OS/Browsers version
mac 10.12.6 / chrome 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/athena0304/8uLw66wL/](https://jsfiddle.net/athena0304/8uLw66wL/)

### Steps to reproduce
trigger: 'blur,change'情况下，在年龄输入框中输入非法字段，任何校验都没有生效，如果是单独的blur或者change是可以的

### What is Expected?
trigger: 'blur,change'情况下可以正常校验

### What is actually happening?
trigger: 'blur,change'情况下没有正常校验

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/8uLw66wL/1/ The docs has been fixed: https://github.com/ElemeFE/element/pull/10778
