### ISSUE TITLE
[Table]希望可以在使用 CSS 控制高度的情况下固定表头

### ISSUE THREAD

**Issue by KINGGUOKUN** [ElemeFE/element#1078]
Table组件没办法同时自适应容器高度以及固定表头。目前想固定表头只能给一个固定高度，但这个高度没办法灵活填充父容器。

**Comment by furybean** [comment]
1.0.2 中 Table height 设置为任意字符串，比如 "auto"，则可以使用 CSS 来控制高度。

**Comment by codepan** [comment]
height="auto"，为什么表格不停的上下运动
