### ISSUE TITLE
[Bug Report] How to change Table component Col title backgroundColor?

### ISSUE THREAD

**Issue by muxi2015** [ElemeFE/element#10781]
### Element UI version
1.2.3

### OS/Browsers version
Linux 4.14 / Chrome 65(Stable)

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1783/](https://jsfiddle.net/mmx38qxw/1783/)

### Steps to reproduce
el-table-column set prop label-class-name="co"  don't work

### What is Expected?
backgroundColor changed

### What is actually happening?
 label-class-name  don't work

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/1788/

**Comment by muxi2015** [comment]
@Leopoldthecoder Sorry,  description of the problem,  expecte is change **background-color** rather than “color”

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/1795/

**Comment by muxi2015** [comment]
@Leopoldthecoder  Thank you very much.
