### ISSUE TITLE
[Feature Request] how do I set up a default value for v-select components loaded with remote data?

### ISSUE THREAD

**Issue by fengyunhe** [ElemeFE/element#10786]
### Existing Component
是

### Component Name
 el-select

### Description
比如，编辑已有数据时渲染，需要显示默认值显示到 el-select组件上，并且可以编辑时正常使用 remote 方式自动完成

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
