### ISSUE TITLE
Can [Feature Request] increase the selection function of tree components?

### ISSUE THREAD

**Issue by HenryYong** [ElemeFE/element#10789]
### Existing Component
Yes

### Component Name
Tree

### Description
用现有的禁用模拟单选很复杂，很多点击情况不能覆盖到，容易导致样式错乱。

**Comment by Leopoldthecoder** [comment]
可以使用 `highlight-current` 属性来模拟单选，配套有 `current-change` 事件和 `getCurrentKey`、`setCurrentKey`、`getCurrentNode`、`setCurrentNode` 方法。
