### ISSUE TITLE
[Bug Report] El-tree watch does not fire when change one of children in the tree

### ISSUE THREAD

**Issue by Hideman85** [ElemeFE/element#10794]
### Element UI version
2.3.4

### What is Expected?
Tree updated when we modify one of children values : 
```
data : [{
    label: 'Root Node',
    children: [{
        label: 'Child Node' // when we change this by any way ( input, database update, ... )
    }]
}]
```

### What is actually happening?
Tree only updated when root element is inserted or removed
Maybe just need to add deep: true in watch of data

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
