### ISSUE TITLE
[Feature Request] Custom CSS On Demand Load

### ISSUE THREAD

**Issue by pixelpaulaus** [ElemeFE/element#10796]
### Existing Component
Yes

### Component Name
SCSS

### Description
How do i do custom CSS when i load the components on demand?
I can only see a way to do it when i load the entire 'element-u'

**Comment by pixelpaulaus** [comment]
i actually figured out how to do it, thanks.
However, is it possible to not include any style/css at all? as i want to handle it all myself in seperate files.

**Comment by Leopoldthecoder** [comment]
To not include any css files, you can remove `babel-plugin-component` (in `package.json`, `.babelrc` and `node_modules`), and import components like this:
```js
import Button from 'element-ui/lib/button.js';
Vue.use(Button)
```
