### ISSUE TITLE
[Bug Report] Cant have proportional column width in el-table component.

### ISSUE THREAD

**Issue by huyaxiong** [ElemeFE/element#10790]
### Element UI version
2.3.4

### OS/Browsers version
MAC Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1800/](https://jsfiddle.net/mmx38qxw/1800/)

### Steps to reproduce
I want that every column in table has proportioal width, but when I set style porperty in el-table like below is not working,
`<el-table :data="tableData" style="width: 100%" stripe>`

And then I set global style like below
`
table {
  font-size: 12px;
  width: 100% !important;
}
`

### What is Expected?
Every column el-table component has proportional width.

### What is actually happening?
The header part of el-table component dont have proportional width.

**Comment by Leopoldthecoder** [comment]
Table columns don't support proportional widths.
