### ISSUE TITLE
[Bug Report] How to trigger the event validation of an input - <inpu>

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#10793]
### Element UI version
2.3.4

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/nj3cLoum/2/](https://jsfiddle.net/nj3cLoum/2/)

### Steps to reproduce
use <input> within <el-form-item> and validation works

### What is Expected?
Validate an input field - <input>

### What is actually happening?
Sorry for creating a doubt here.
Estou tentando usar o v-money, mas ele só funciona corretamente com elemento input <input />
I tried using <el-input>, but it does not work well

The problem is that the validation does not work when I use <input>
How can I trigger the validation event on a non <el-input>

example:

```
<el-form-item label="name" prop="name">
 <input type="tel"
         :value="data.name"
         @change="change"
         v-money="{precision, decimal, thousands, prefix, suffix}"
         class="v-money" />
</el-form-item>
```

**Comment by wacky6** [comment]
Validation is a el-form feature. Or you need to write your own validation logic.

For third-party libraries, **you** need to figure out how to integrate them with element. We don't have the resource to troubleshoot integration problems.
