### ISSUE TITLE
[Bug Report] el-select: this.$refs.selectorRef.selected.currentLabel gives previous selection

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#10809]
### Element UI version
2.3.5

### OS/Browsers version
Chrome / Linux

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1834/](https://jsfiddle.net/mmx38qxw/1834/)

### Steps to reproduce
See the jsfiddle code.

I've downgraded element-ui to **2.3.2** from **2.3.5**. _Same issue_.

### What is Expected?
That the `this.$refs.&lt;ref&gt;.selected.currentLabel` be the actual **label** chosen.

### What is actually happening?
It's selecting the prior selection.

**Comment by wacky6** [comment]
This is **not** a public facing API, so **don't** use it (or at your own risk).

**Comment by adavie1** [comment]
OK, so how do I get the label then?

**Comment by adavie1** [comment]
Fair enough, thanks for your answer.

However, I think a more elegant solution would be to pass in the change event, the second parameter is the label. I'll put a feature request in for that.
