### ISSUE TITLE
多选框组、单选框组多行对齐问题

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#1080]
### ElementUI version
1.0.0

### Steps to reproduce
将多选框组或单选框组中的选项变成一列（多行）

### What is Expected?
每行的选项对齐

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/3336443/20301387/13be9e02-ab5e-11e6-8399-c5629dcbaf81.png)

**Comment by baiyaaaaa** [comment]
考虑到普遍的场景，组件默认设置了相邻checkbox和radio会有一定得margin，如果不需要你可以自己通过样式去掉

**Comment by furybean** [comment]
这种场景没办法从组件上解决的， 你需要根据自己的场景来写 CSS 解决。

比如你可以根据屏幕宽度来决定是否让 el-checkbox 旁边有 margin，或者设计的时候就让这些 CheckBox 是多行。
