### ISSUE TITLE
[Feature Request] How to change styles ( scss ) for input

### ISSUE THREAD

**Issue by l3lock** [ElemeFE/element#10803]
### Existing Component
Yes

### Component Name
Input

### Description
I try this but it doesn't work 

<style lang="scss" scoped>
.el-input__inner {
  color: #FFFFFF;
  background-color: transparent;
}
</style>

**Comment by Leopoldthecoder** [comment]
https://vue-loader.vuejs.org/en/features/scoped-css.html See the `Deep Selectors` section.

**Comment by curryz** [comment]
IE doesn‘t work，is there something else？

**Comment by curryz** [comment]
@Leopoldthecoder
