### ISSUE TITLE
[Bug Report] 【el-table】When el-table-column sets the fixed attribute and el-table initializes the data asynchronously, I could not get the vue instance in table-cell.

### ISSUE THREAD

**Issue by ZhanYishu** [ElemeFE/element#10818]
### Element UI version
2.3.5

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/zhanzf/4qjvhLnL/9/](https://jsfiddle.net/zhanzf/4qjvhLnL/9/)

### Steps to reproduce
1、Sets the fixed attribute of el-table-column
2、Initializes the table data asynchronously
3、Click the edit button

### What is Expected?
I could get the el-tag instance.
The el-tag would not display.

### What is actually happening?
I could not get the el-tag instance.
The el-tag still displays.

**Comment by Leopoldthecoder** [comment]
不是 bug，和 Table 固定列的实现有关（可参考：https://zhuanlan.zhihu.com/p/33280304）。`display: none` 实际作用在了被隐藏的单元格。
一个可能的替代方案：https://jsfiddle.net/leopoldthecuber/4qjvhLnL/13/

**Comment by ZhanYishu** [comment]
非常感谢！我知道隐藏的元素实际上是固定列所复制出的元素，但是我实际想要获取到的是当前的组件实例，以便于我对它进行操作。
当固定列去掉或者不采用异步获取数据渲染表格组件时，获取到的组件实例实际上是正确的。
不知道能否对此进行优化，因为写在单元格中组件，却获取不到，会造成多数人的困惑
