### ISSUE TITLE
完善表格筛选文档

### ISSUE THREAD

**Issue by jfb** [ElemeFE/element#1081]
### Reproduction Link
https://jsfiddle.net/tLe0aLwt/1/

### What is Expected?

点击 `家`，完成表格里家相关数据的筛选
点击 `公司`， 完成表格里公司相关数据的筛选
点击 `清除筛选`，清除筛选条件

**Comment by furybean** [comment]
如果想要这个效果，关闭 filterMultiple 就可以。

**Comment by jfb** [comment]
@furybean 如果不用系统自带的过滤组件如何实现那？

还想实现本地数据搜索，好像也没提供api

**Comment by furybean** [comment]
@jfb 直接操作 data 属性就可以。
