### ISSUE TITLE
[Bug Report] Popover can not pop up the last in table

### ISSUE THREAD

**Issue by anonymous-qsh** [ElemeFE/element#10811]
### Element UI version
2.3.4

### OS/Browsers version
MAC/CHROME

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/6hr287ot/1/](https://jsfiddle.net/6hr287ot/1/)

### Steps to reproduce
1. Add the el-table
2. Add the el-button
3. Add the popover in el-button

### What is Expected?
The last item in the table should pop up the popover.

### What is actually happening?
The last item in the table not pop up the popover.

**Comment by jwenjian** [comment]
Same issue.
The event ['input', 'hide'] of `<el-popover>` not triggered on the last item, you can check that via the Vue dev tool.

**Comment by Leopoldthecoder** [comment]
This is related to Vue `ref` mechanism. Basically you should avoid setting multiple elements with the same `ref` (in your case, all `<el-popper>` has the same `ref` of 'popover') in a non-v-for structure.

Use named slot instead: https://jsfiddle.net/leopoldthecuber/6hr287ot/5/
