### ISSUE TITLE
[Feature Request] tree controls do not think that each node adds different icons based on the field of the node.

### ISSUE THREAD

**Issue by runner-mei** [ElemeFE/element#10814]
### Existing Component
是

### Component Name
Tree 树形控件

### Description
能为树形控件的每个节点加上图标， 根据节点的某个字段值而显示不同的图标，像 https://www.jstree.com  那样

**Comment by Leopoldthecoder** [comment]
节点内容是支持自定义的，你可以往里面放任何东西：http://element-cn.eleme.io/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong
