### ISSUE TITLE
[Feature Request] NavMenu navigation menu

### ISSUE THREAD

**Issue by 2015-lizaiyang** [ElemeFE/element#10829]
### Existing Component
是

### Component Name
Menu

### Description
NavMenu 导航菜单选中的项目文字可以自定义颜色，但是文字的背景色没有自定义颜色的api。
![image](https://user-images.githubusercontent.com/21666293/39102148-db9e5090-46d3-11e8-97a5-1912c264682d.png)
![image 1](https://user-images.githubusercontent.com/21666293/39102149-dbfd502c-46d3-11e8-8c5a-d2a8575a1e47.png)
<img width="257" alt="qq20180423-085629 2x" src="https://user-images.githubusercontent.com/21666293/39102211-59ac8024-46d4-11e8-86cd-7ea497a73904.png">
<img width="1407" alt="qq20180423-085933 2x" src="https://user-images.githubusercontent.com/21666293/39102255-aab33792-46d4-11e8-81bf-186c5cf42416.png">

**Comment by Leopoldthecoder** [comment]
Duplicate of #7686
