### ISSUE TITLE
[Feature Request] form custom check validator callback function return parameter increase label

### ISSUE THREAD

**Issue by lizm2011** [ElemeFE/element#10820]
### Existing Component
是

### Component Name
form

### Description
目前的回调方法只有rule, value, callback三个参数，需要自己写每一个字段的错误提示信息，
比如：
var checkAge = (rule, value, callback) => {
        if (!value) {
          return callback(new Error('年龄不能为空'));
        }
      };
页面上的label是“年龄”，那么对应的提示信息应该是围绕“年龄”来提示的，可以考虑增加一个label参数，方便开发者直接通过label拼接提示信息，就不需要每个自定义方法都写上这个校验的提示信息了。
比如：
var checkAge = (rule, value, callback, label) => {
        if (!value) {
          return callback(new Error(label   '不能为空'));
        }
      };

**Comment by Leopoldthecoder** [comment]
查了一下，校验使用的库 async-validator 是支持更多参数的：
```js
var descriptor = {
  email: [
    {type: "string", required: true, pattern: schema.pattern.email},
    {validator(rule, value, callback, source, options) {
      var errors = [];
      // test if email address already exists in a database
      // and add a validation error to the errors array if it does
      callback(errors);
    }}
  ]
}
```

在 `source` 里可以找到当前表单项所对应的 `rules` 里的字段，但是是英文的，无法获取中文参数名，所以 Element 这边也无能为力。

**Comment by lizm2011** [comment]
this.elForm && this.elForm.$emit('validate', this.prop, !errors);
这一句不能把 this.label 传出来吗
