### ISSUE TITLE
[Feature Request] Get information about row index while row-click or current-change

### ISSUE THREAD

**Issue by pawelpanek81** [ElemeFE/element#10827]
### Existing Component
Yes

### Component Name
Table

### Description
It would be nice to know clicked row index.
Currently I don't see this ability.
E.g.
Table:
```
|#    Name    Surname|
|1    a           b|
|2    c           d|
|3    e           f|
```

`@row-click` or `@current-change` could have parameter "`index`", but now it have only `(row, event, column)` or `(currentRow, oldCurrentRow)`.

**Comment by Leopoldthecoder** [comment]
`[yourTableDataSourceArray].indexOf(row)`

**Comment by hanzichi** [comment]
@Leopoldthecoder 
clever solution.  will the team consider about adding the `index` to the parameters of `row-click` function?
