### ISSUE TITLE
[Feature Request] Hello, I don't know how I correctly use element-ui in nuxtjs to load on demand.

### ISSUE THREAD

**Issue by warriorBrian** [ElemeFE/element#10825]
### Existing Component
是

### Component Name
babel-plugin-component

### Description
element-ui官网上并没有详细的nuxtjs使用说明，而且我按照官网的按需加载.
**我在项目中，仅仅只是引入了一个导航栏和轮播图，体积翻了几倍！！！**
在nuxt.config.js中配置babel,并使用npm run build的时候，vendor.js文件的体积还是跟原来全部加载一样大，并没有按需引入的效果。
这使我怀疑element-ui到底支不支持nuxt.js。请看见issue后回复，我们在做项目开发使用element-ui框架，这个问题我一直在关注。请及时回复。谢谢。
![tim 20180421172003](https://user-images.githubusercontent.com/28696399/39082639-095b81de-4589-11e8-96a7-68e9a74205fa.png)
![tim 20180421172652](https://user-images.githubusercontent.com/28696399/39082655-4bac8d8a-4589-11e8-8edd-d75e9dfe036e.png)

**Comment by Leopoldthecoder** [comment]
我测了一下，结果如下：

- 完整引入：
![image](https://user-images.githubusercontent.com/10095631/39083676-c1701f80-459a-11e8-8398-2a922f0f8810.png)


- 按需引入，仅引入 Button 组件：
![image](https://user-images.githubusercontent.com/10095631/39083677-c4c488ba-459a-11e8-97e2-0fc621cd5b26.png)


- 按需引入，引入 Button、Select 和 Option 组件：
![image](https://user-images.githubusercontent.com/10095631/39083679-d1e5fc90-459a-11e8-8f66-8cb10a0fe3ab.png)


代码在 https://github.com/Leopoldthecoder/nuxt-element

**Comment by warriorBrian** [comment]
@Leopoldthecoder 谢谢你的示例，这让我能减少体积达到目的。
解决问题的效率真的是很快。点赞~

**Comment by stylehuan** [comment]
这样包体是小了，但是本地环境为什么会去加载default的样式文件。
![image](https://user-images.githubusercontent.com/6212099/39170319-a7384f90-47cd-11e8-8ceb-0a7545eb4d9a.png)
实际这个路径并没有的。只有theme-chalk主题目录

**Comment by stylehuan** [comment]
解决了！
`
babel: {
      "plugins": [["component", {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }]],
      comments: false//去掉就好了
    },
`
不明白跟注释有什么关系呢
