### ISSUE TITLE
[Bug Report] Tree component: Error when tree-node-drag-end emit

### ISSUE THREAD

**Issue by TomomiSawako** [ElemeFE/element#10824]
### Element UI version
2.3.5

### OS/Browsers version
MacOS/Safari Version 11.1 (13605.1.33.1.2)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/bmcL60sc/](https://jsfiddle.net/bmcL60sc/)

### Steps to reproduce
*Happend in Safari*
In the official example, drag 三级 3-2-1 to 三级 3-1 will throw error
在官方example中，将 三级 3-2-1 拖拽到 三级 3-1 上会显示一下错误

[Vue warn]: Error in event handler for "tree-node-drag-end": "TypeError: null is not an object (evaluating 'r.node.parent.insertBefore')"

found in

---> <ElTree>
       <Root>
warn — vue.js:597
logError — vue.js:1739
globalHandleError — vue.js:1734
handleError — vue.js:1723
$emit — vue.js:2540
handleDragEnd — index.js:19558
handleDragEnd
dragend — index.js:19621
_withTask — vue.js:1828
logError — vue.js:1743

### What is Expected?
I don't know, cause this is official example...
我也不知道，因为这事官方example

### What is actually happening?
[Vue warn]: Error in event handler for "tree-node-drag-end": "TypeError: null is not an object (evaluating 'r.node.parent.insertBefore')"

**Comment by TomomiSawako** [comment]
oh, i forget it 😢

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/39084898-9af7583c-45ae-11e8-81f1-4a07347dc17b.gif)

![image](https://user-images.githubusercontent.com/10095631/39084917-cbc61868-45ae-11e8-8abe-b9aff9dacbfe.png)

Cannot reproduce it.

**Comment by TomomiSawako** [comment]
![bug](https://user-images.githubusercontent.com/1460808/39090839-af714378-461b-11e8-8e07-642b5d9aa73d.gif)

![qq20180422-105029](https://user-images.githubusercontent.com/1460808/39090808-fee68c02-461a-11e8-8e7f-9f3eb0ed7ab5.png)

@Leopoldthecoder
