### ISSUE TITLE
[Feature Request] Add custom class to el-dialog wrapper

### ISSUE THREAD

**Issue by ccqgithub** [ElemeFE/element#10831]
### Existing Component
是

### Component Name
el-dialog 

### Description
I want some dialog to center in the page,  but some not (like default), so i need to set el-dialog__wrapper display with `flex`(and any other style with custom class)

but now i can only add `custom-class` to `el-dialog`, can not add `custom-class` to the wrapper.

what i want: Add custom class to el-dialog wrapper

**Comment by Leopoldthecoder** [comment]
Use `class` directly on `<el-dialog>`.

**Comment by guohuihot** [comment]
主要是想在外层加动态处理class, 做dialog的自定义动画，希望给个这样的接口
