### ISSUE TITLE
[Bug Report]  Injection "elForm" not found  found in  <ElDatePicker> (all the project of my team depends on vue 2.4.2. I wonder if there are ways to solve this problem without upgrade vue versions. since upgrade vue versions need consider a lot of things and need times. )

### ISSUE THREAD

**Issue by shengxiuzhou** [ElemeFE/element#10837]
### Element UI version
2.0.0

### OS/Browsers version
win7

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1.open jsfiddle and run
2.press F12  then you can see error like this:
.vue.js:485 [Vue warn]: Injection "elForm" not found

found in

---> <ElDatePicker>

### What is Expected?
without warn

### What is actually happening?
have warn

**Comment by Leopoldthecoder** [comment]
Element 2.0.0 最低兼容 Vue 2.5.2。

**Comment by shengxiuzhou** [comment]
看来要么升级vue版本，要么不用element-ui了。。。

**Comment by llojkue** [comment]
Any solution?Please

**Comment by kiichi** [comment]
Update Vue version e.g.
```html
<script src="https://unpkg.com/vue@2.5.2/dist/vue.js"></script>
<script src="https://unpkg.com/element-ui@2.3.6/lib/index.js"></script>
<script src="https://unpkg.com/element-ui@2.3.6/lib/umd/locale/en.js"></script>
```
and the css
```
<link rel="stylesheet" href="https://unpkg.com/element-ui@2.3.6/lib/theme-chalk/index.css">
```
those combination worked for me
