### ISSUE TITLE
[Feature Request] Group By 

### ISSUE THREAD

**Issue by rugged-service** [ElemeFE/element#10845]
### Existing Component
Yes

### Component Name
Table

### Description
Is it possible to group rows by a field? Example: 

`
tableData: [
            { id: 1, c: 'aaa',  name: "John", age: "20" },
            { id: 2, c: 'aaa', name: "Jane", age: "24" },
            { id: 3, c: 'ddd', name: "Susan", age: "16" },
            { id: 4, c: 'ddd', name: "Chris", age: "55" },
            { id: 5, c: 'ddd', name: "Dan", age: "40" }
        ],
`

Where rows are grouped by 'c' field.

**Comment by Leopoldthecoder** [comment]
Use `span-method`.

**Comment by rugged-service** [comment]
After investigating the span-method I'm still unsure how to get this to work correctly. Does span method transform the data or, just add span properties? I would like to bundle all the elements in the tableData array by "c" so everything with c: "aaa" are grouped together and everything with c: "ddd" are grouped together, no matter their index in the tableData array.
