### ISSUE TITLE
[Feature Request] Long Press Button Attribute

### ISSUE THREAD

**Issue by OzairP** [ElemeFE/element#10844]
### Existing Component
Yes

### Component Name
el-button

### Description
Add an optional attribute `:long-press="5000"` to indicate the button must be pressed down for 5000 milliseconds to trigger the event.

See https://jsfiddle.net/qr9ykxpp/

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can add `mousedown` and `mouseup` listeners to handle this.
