### ISSUE TITLE
Can the form of new version of [Feature Request] return to 1.X version?

### ISSUE THREAD

**Issue by yangfei4913438** [ElemeFE/element#10858]
### Existing Component
是

### Component Name
el-table

### Description
新版的表格，基本看不到色彩了，而且默认行高也比1.x版本的大好多，看起来感觉好畸形。
能不能让1.x的样式回归，一开始用2.X版本，我的内心是崩溃的。。。
难道，2.x的目标是所有样式，让用户自己手写？？？

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
