### ISSUE TITLE
[Bug Report]  ElSelect: the arrow's style displayed error

### ISSUE THREAD

**Issue by ohhoney1** [ElemeFE/element#10855]
### Element UI version
2.3.6

### OS/Browsers version
mac OS/ chrome 

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/p39nnt1j/](https://jsfiddle.net/p39nnt1j/)

### Steps to reproduce
The width and color of the arrows are not the same as the `el-select-dropdown` or `el-popover`

### What is Expected?
Width and color are consistent.

### What is actually happening?
The width and color of the arrows are not the same as the `el-select-dropdown` or `el-popover`

**Comment by Leopoldthecoder** [comment]
Which arrows? How are they different? Please add some screenshots.

**Comment by ohhoney1** [comment]
arrow's width and color are different from the `el-select-dropdown`'s border-color and width
![wechatimg48](https://user-images.githubusercontent.com/20284707/39187554-3464ba98-4800-11e8-86a1-97ebcbe2cc3f.jpeg)

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/39189230-4ff98ce4-4804-11e8-8dd7-18da4412fd05.png)

##

![image](https://user-images.githubusercontent.com/10095631/39189236-535d5348-4804-11e8-9924-c2175f14e22e.png)

They're the same.

**Comment by ohhoney1** [comment]
![image](https://user-images.githubusercontent.com/20284707/39191110-b58737c4-4808-11e8-9f48-ffbe6f2a5b75.png)
