### ISSUE TITLE
[Bug Report] [Select compenent] Focus event will be trigger twice and select option also will be trigger while add filterable parameter

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#10854]
### Element UI version
2.3.6

### OS/Browsers version
window 7 / Chrome

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/6hsytktz/1/](https://jsfiddle.net/6hsytktz/1/)

### Steps to reproduce
鼠标点击select组件，调用focus方法

### What is Expected?
聚焦时，focus方法只会调用一次，选择选项时不会被调用 

### What is actually happening?
 聚焦时，focus方法会调用多次，选择选项时也会被调用

**Comment by leslieSie** [comment]
无法重现

**Comment by sotaan** [comment]
up plz
