### ISSUE TITLE
[Feature Request] el-select @change 2nd parameter should be label

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#10850]
### Existing Component
Yes

### Component Name
el-select

### Description
The `el-select` component where the value and label are different, when a change happens on the select, the first parameter to the change method is the new value, which is fine.

The suggestion is to have an optional 2nd parameter **if the label and value are different** that is the label value.

[See the issue #10809 for an example](https://github.com/ElemeFE/element/issues/10809#issuecomment-383094304)

**Comment by wacky6** [comment]
@Leopoldthecoder What do you think?
