### ISSUE TITLE
Can the class name of the drop-down icon of [Feature Request] el-submenu be changed to props?

### ISSUE THREAD

**Issue by wuchuguang** [ElemeFE/element#10859]
### Existing Component
是

### Component Name
el-submenu

### Description
submenu.vue文件
<i :class="{
        'el-submenu__icon-arrow': true,
        'el-icon-arrow-down': rootMenu.mode === 'vertical',
        'el-icon-caret-bottom': rootMenu.mode === 'horizontal'
      }">
      </i>

el-icon-arrow-down
el-icon-caret-bottom 
这两个类名支持prop方式。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
