### ISSUE TITLE
[Feature Request] Element table column label type add Object

### ISSUE THREAD

**Issue by justforuse** [ElemeFE/element#10852]
### Existing Component
是

### Component Name
Table

### Description
I want use render-header to customize table header, but the label only accept `string` not `object`
I want to use `el-table-column` render-header like this:
```
<el-table-column
     v-for="(header, index) in headers"
     :key="index"
     :label="header"
     :render-header="renderHeader">
</el-table-column>

<script>
data: {
    headers: [
      {
        label: 'Column1',
        info: 'col1-info'
      },
      {
        label: 'Column2',
        info: 'col2-info'
      }
    ]
  },
  methods: {
    renderHeader(createElement, {column}) {
      return createElement(
        'span',
        [column.label.label, ':' , column.label.info]
      )
    }
  }
</script>
```
It performs well, but an error occured: `Invalid prop: type check failed for prop "label". Expected String, got Object.
`
here is a demo: https://codepen.io/justforuse/pen/LmGKgr

**Comment by Leopoldthecoder** [comment]
You don't have to add `label`: https://codepen.io/leopoldthecoder/pen/RyabPo

**Comment by justforuse** [comment]
thanks a lot
