### ISSUE TITLE
[Bug Report] el-tree not adding dynamic node to tree

### ISSUE THREAD

**Issue by chauriya** [ElemeFE/element#10868]
### Element UI version
2.3.6

### OS/Browsers version
windows 10

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/chauriyagaurav/2mekfhfr/](https://jsfiddle.net/chauriyagaurav/2mekfhfr/)

### Steps to reproduce
1. click `Level one 3` node on Tab 2. This should add new node to el-tree as written in `handleNodeClick` method.
2. Inspect htlm with developer tool, new element can be seen in Tab 1 el-tree.

### What is Expected?
New tree node should be added to same active tree

### What is actually happening?
New node is always getting added to first tab's tree node.

### Additional Information
 The issue is been occurring from version 2.2.0 and working perfectly fine with version 2.1.0.

**Comment by ziyoung** [comment]
I think this is not a bug. Don't share data between two or more Tree components.

https://github.com/ElemeFE/element/blob/94434dcb795ad6ab5cc7948ade38b0ce1877a446/packages/tree/src/model/node.js#L435-L441


If `item[NODE_KEY]` exists,  Tree doesn't regard the new item as new node. When the second tree rerenders, the new item's `NODE_KEY` exists. So only the first Tree update.
