### ISSUE TITLE
[Bug Report] el-select: RemoteMethod is not called when the query is removed after focused by click

### ISSUE THREAD

**Issue by junpei-tsutsui** [ElemeFE/element#10860]
### Element UI version
2.3.6

### OS/Browsers version
MacOS Sierra / Chrome 66

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/msej7pj6/](https://jsfiddle.net/msej7pj6/)

### Steps to reproduce
1. Input 'ala' and choose 'Alaska' from the remote search single select component
2. Unfocus and focus the component by click (not Tab key)
3. As focused, the input text 'Alaska' is highlighted and just one press of Delete key removes the whole text
4. The options are not updated because the RemoteMethod is not called (the options should become empty if the RemoteMethod is called in this case)

### What is Expected?
RemoteMethod is called.

If I focus the component by Tab key in the step 2, the RemoteMethod is called.

### What is actually happening?
RemoteMethod is not called.

**Comment by leslieSie** [comment]
you should add this property like this:
`v-on:keyup.native.delete="remoteMethod"`
this problem is not element bug, you program should be more stronger

**Comment by ziyoung** [comment]
@junpei-tsutsui `query` is empty after SelectDropdown is closed. If you delete all text, `selectedLabel` is also empty. So the function `handleQueryChange ` won't be called.
https://github.com/ElemeFE/element/blob/d73821bc720ff28418e8c7509837fd634825ceba/packages/select/src/select.vue#L777-L780

@leslieSie has provided a solution which should work for you. https://jsfiddle.net/zhiyang/msej7pj6/4/
