### ISSUE TITLE
[Feature Request] Form input element's label or not linked to their respective input

### ISSUE THREAD

**Issue by CedricLeGallo** [ElemeFE/element#10861]
### Existing Component
Yes

### Component Name
el-input

### Description
When using label attribute on el-input (and el-select, and  el-switch) the generated label is not linked (by a for/id couple or aria-labelledby/id couple) to the input, causing a click on label to be ineffective, it is an accessibility issue for Section 508 (US Law) RGAA (French Law)

Details : 
On this page : https://element.eleme.io/#/en-US/component/form, 
- clic on Instant delivery should toggle the switch
- clic on Activity name should give the focus to associate input
- etc

el-radio and el-checkox are fine

**Comment by Leopoldthecoder** [comment]
It already works for Input and Select: https://jsfiddle.net/leopoldthecuber/ds9ox2c2/ . After #10862 Switch will be supported too.
