### ISSUE TITLE
[Table] 希望 type="index" 的 Column 可以支持分页

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1086]
table分页，序号使用的是type="index"，点击下一页后，序号没有对应按照上一页的数据继续增加，而是直接显示为1,2,3，。。。
![image](https://cloud.githubusercontent.com/assets/16740731/20310482/1c741f58-ab87-11e6-8763-bd10f5c7704c.png)

**Comment by furybean** [comment]
是需要优化的点，不过目前 Table 组件并不包含 Pagination，currentPage 和 pageSize 都是未知，需要权衡下怎么去实现。

**Comment by jfb** [comment]
@furybean 希望表格多多完善，表格应该是使用最多的组件之一。

**Comment by yuanshengchao** [comment]
请问有什么解决方案，暂时可以保证该序号连续吗？

**Comment by yuanshengchao** [comment]
今天又去好好做琢磨了一下element的api文档和vue，突然发现了一个可以完美解决table分页的序号连续问题。具体请看代码，使用了element的table组件的inline-template，然后在其中使用vue的获取序号的方式：$index来进行。其实element文档中也有说明，不过只能说时间太紧，element的团队的伙伴们还没有来得急讲文档写的很详细。具体如下图所示：
1、此图是使用element的inline-template
![image](https://cloud.githubusercontent.com/assets/16740731/20602560/d0fa1866-b298-11e6-901c-d193a7639ba7.png)
2、data申明默认数据
![image](https://cloud.githubusercontent.com/assets/16740731/20602589/f420f6ac-b298-11e6-9feb-4fea25b93900.png)
3、此图是调用分页组件的分页方法
![image](https://cloud.githubusercontent.com/assets/16740731/20602611/1071c8ae-b299-11e6-8ded-a5ef7c9f2e8f.png)

**Comment by yuanshengchao** [comment]
@furybean 已经ok啦，谢谢

**Comment by lhajh** [comment]
目前 Element ui 版本为 1.4.4，按官方说法
> 1.1 后支持通过 Scoped slot 自定义模板。之前的 inline-template 同样适用，但不推荐。

![](https://cloud.githubusercontent.com/assets/16740731/20602560/d0fa1866-b298-11e6-901c-d193a7639ba7.png)
上图中红线圈出的部分可以修改为如下代码：
```
  <el-table-column
        min-width="25"
        label="序号">
        <template scope="scope">
            {{scope.$index + addIndex}}
        </template>
    </el-table-column>
```

**Comment by ceerqingting** [comment]
![_20180620115114](https://user-images.githubusercontent.com/20520365/41636319-4bdbc4bc-7480-11e8-8a99-291cbdb52cab.png)
新版的文档用这个方法也可以
