### ISSUE TITLE
[Bug Report] el-upload: How to disable the delete key to trigger to?

### ISSUE THREAD

**Issue by LuxPax** [ElemeFE/element#10866]
### Element UI version
2.3.3

### OS/Browsers version
windows7 / Chrome  65.0.3325.181

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/1900/f7jbog25/)

### Steps to reproduce
点击文件列表，然后在按 delete 键，会触发删除事件，还会提示按 delete 键可删除，文字提示已经通过样式隐藏，但是按 delete 键还是会触发删除事件，请问怎样可以禁用这个功能

### What is Expected?
希望可以有一个事件可以禁用 delete 键触发删除事件

### What is actually happening?
api上没有找到禁用方法

**Comment by Leopoldthecoder** [comment]
为何需要禁用此功能？

**Comment by LuxPax** [comment]
因为我们的需求是上传一个文件会附带一些信息，删除是点击一个按钮把文件信息和文件一起删除，不单独删除文件，所以希望 fileList 不触发删除事件
![image](https://user-images.githubusercontent.com/23111937/39221532-34b22778-486a-11e8-9e85-547d2276afdc.png)

**Comment by Leopoldthecoder** [comment]
可能不会支持禁用。建议在按 delete 键删除文件后通过 `on-remove` 将文件信息一并删除。

**Comment by LuxPax** [comment]
好的 谢谢

**Comment by Jack-cool** [comment]
> 为何需要禁用此功能？



> 因为我们的需求是上传一个文件会附带一些信息，删除是点击一个按钮把文件信息和文件一起删除，不单独删除文件，所以希望 fileList 不触发删除事件
> ![image](https://user-images.githubusercontent.com/23111937/39221532-34b22778-486a-11e8-9e85-547d2276afdc.png)

你好想问下，“还会提示按 delete 键可删除”这文案你是怎么隐藏的，我这边没有复现，但是其他人delete时有复现（element ui版本2.10.1）

**Comment by mengxiaoxu** [comment]
可以在源码里面找，修改对应的源码就可以，比如下面的时 el-tabs 的实现。
```js
'keydown': function keydown(ev) {
              if (closable && (ev.keyCode === 46 || ev.keyCode === 8)) {
                onTabRemove(pane, ev);
              }
            }
```

**Comment by Milkker** [comment]
我在上傳檔案編輯備註的需求上也遇到類似問題，刪除備註文字時觸發刪除事件。

處理方式是在 before-remove 做event 判斷，若 window.event.keyCode == 8 則不處理刪除事件。

範例碼：https://jsfiddle.net/Milkker/pxocten5/
![image](https://user-images.githubusercontent.com/5615640/81889821-16212680-95d7-11ea-8f2e-4b1da299bd85.png)

``` html
<el-upload v-bind:before-remove="beforeRemove" <!--...-->>
  <div slot='file' slot-scope='{ file }'>
     <a href='#'>{{ file.name }}</a>
     <input type='text' v-model='file.memo' v-on:change='editMemo(file, $event.target.memo)'/>
  </div>
</el-upload>
```

``` javascript

Vue({
  //...
  methods: {
    //...
    beforeRemove(file, fileList) {
      //避免點選 Backspace 觸發刪除檔案。
      if (window.event.type == "keydown" && window.event.keyCode == 8)
        return false;

      return true;
    },
   editMemo(file, memo) {
     //修改資料庫備註...
   }
  }
});
```
