### ISSUE TITLE
[Bug Report] elementUI select creates duplicate entries, and all duplicate entries are automatically deleted.

### ISSUE THREAD

**Issue by fifty0six** [ElemeFE/element#10877]
### Element UI version
2.3.6

### OS/Browsers version
win7

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/9Lwa884r/](https://jsfiddle.net/9Lwa884r/)

### Steps to reproduce
select创建条目重复，所有重复的条目都被自动删除

### What is Expected?
elementUI select创建条目重复时，做去重，而不是把一样的都删除

### What is actually happening?
select创建条目重复，所有重复的条目都被自动删除

**Comment by Leopoldthecoder** [comment]
「做去重」是一个什么操作？请用动图解释一下。

**Comment by fifty0six** [comment]
@Leopoldthecoder 就是只保留一个条目，把其他重复的去掉。目前如果我的输入是[1,1,2,3]，只会保留[2,3]，直接把1删除了，我希望的结果是[1,2,3]

**Comment by Leopoldthecoder** [comment]
「输入第二个 `1`  -> 回车」这一操作等同于点击下拉菜单中的 `1`，即取消选择。不会对这一行为作出变更。
