### ISSUE TITLE
[Bug Report] Avoid White Space in Form Validation

### ISSUE THREAD

**Issue by creativemind1** [ElemeFE/element#10875]
### Element UI version
2.3.6

### OS/Browsers version
Windows / Chrome v66

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/esujevpL/2/](https://jsfiddle.net/esujevpL/2/)

### Steps to reproduce
Press space in the input field and you can see there is no error message

### What is Expected?
Validation should check the value written and should throw the error if only spaces are there

### What is actually happening?
Validation is not working if there are only spaces to the field

**Comment by Leopoldthecoder** [comment]
This is how [async-validator](https://github.com/yiminghe/async-validator) handles required props. Write your own `validator` or `pattern` to filter out spaces-only inputs.

**Comment by creativemind1** [comment]
I found the pattern which will not accept initial spaces
`https://stackoverflow.com/questions/44395768/vue-js-element-ui-form-validation-regexp`
`pattern: /^[^-\s][a-zA-Z0-9_\s-]+$/`

Is there not any way to make it globally because we are having hundreds of forms and hundreds of fields..
