### ISSUE TITLE
使用el-radio和el-popover时事件冲突

### ISSUE THREAD

**Issue by xubing6243** [ElemeFE/element#10873]
<template v-for="(item, index) in modelList">
            <el-popover
              ref="popover"
              placement="top"
              :title="item.name"
              width="200"
              trigger="hover">
                <p>{{item.details}}</p>
                <div style="text-align: center;">
                  <el-button size="mini">查看详情</el-button>
                </div>
              <template slot="reference">
                <el-radio class="radio-image" v-model="type_id" :label="item.id" border>{{item.name}}/el-radio>
              </template>
            </el-popover>
          </template>

报错：
Uncaught TypeError: instance.focus is not a function
    at HTMLLabelElement.eval (element-ui.common.js?ccbf:18104)

**Comment by songzeng2016** [comment]
请问解决了吗，我也遇到同样的问题了
