### ISSUE TITLE
[Bug Report] In the tree control, "setCurrentKey" does not trigger a "current-change" event

### ISSUE THREAD

**Issue by yin112234** [ElemeFE/element#10871]
### Element UI version
2.3.6

### OS/Browsers version
win7 / chrome V63

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/issues/10463](https://github.com/ElemeFE/element/issues/10463)

### Steps to reproduce
使用setCurrentKey方法改变tree的选中状态时，没有触发current-change 事件。

### What is Expected?
代码使用setCurrentKey方法改变tree的选中状态时，  触发current-change 事件。

### What is actually happening?
使用setCurrentKey方法改变tree的选中状态时，没有触发current-change 事件。

**Comment by Leopoldthecoder** [comment]
`setCurrentKey` 不会触发 `current-change` 事件。`current-change` 事件**仅响应用户交互**，不会在通过代码改变 current key 时触发。这点和所有表单组件的 `change` 事件一致。

**Comment by yin112234** [comment]
在table组件中，调用setCurrentRow方法就会触发 current-change 事件，
可为什么在tree组件中，setCurrentKey 不会触发 current-change 事件，why？？

**Comment by Leopoldthecoder** [comment]
那么 Table 是有问题的，我们看一下。
