### ISSUE TITLE
[Feature Request] Nested other components or div in steps

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#10870]
### Existing Component
是

### Component Name
steps

### Description
如何在 el-step 嵌套定制 内容（项目需要按列表展示）

![image](https://user-images.githubusercontent.com/8147202/39221939-6807ada8-486c-11e8-8e71-5a3812c8516c.png)

https://jsfiddle.net/supguqmf/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/caobm232/
