### ISSUE TITLE
Does [Bug Report] Tree have such an attribute of an array of key with default highlight nodes?

### ISSUE THREAD

**Issue by osinglee** [ElemeFE/element#10886]
### Element UI version
2.3.6

### OS/Browsers version
OS 10.12.1

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/e5LLxk4w/)

### Steps to reproduce
我希望我可以设置默认 tree 中某个节点高亮

### What is Expected?
我希望我可以设置默认 tree 中某个节点高亮

### What is actually happening?
我希望我可以设置默认 tree 中某个节点高亮

**Comment by Leopoldthecoder** [comment]
使用 `setCurrentKey` 或 `setCurrentNode`。
