### ISSUE TITLE
[Bug Report] question about iframe-upload of el-upload with onload onDrop handleDragover handleDragleave

### ISSUE THREAD

**Issue by jinying134** [ElemeFE/element#10887]
### Element UI version
0.1.0

### OS/Browsers version
win10 ie9

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator, http://192.168.0.100/#/project](https://elementui.github.io/issue-generator, http://192.168.0.100/#/project)

### Steps to reproduce
console.log(this.onload, this.onDrop, this.handleDragover, this.handleDragleave) at iframe-upload component. import el-upload to business component , open project at ie9 Browser, all of them is undefind but used at event handler, i can't find them at props and methods, so where are they come from?

### What is Expected?
this.onload, this.onDrop, this.handleDragover, this.handleDragleave is function

### What is actually happening?
this.onload, this.onDrop, this.handleDragover, this.handleDragleave is undefind

**Comment by Leopoldthecoder** [comment]
Element is no longer compatible with IE9, so `iframe-upload` is actually deprecated. We just forgot to delete this file.
