### ISSUE TITLE
[Feature Request] Opening el-dropdown using javascript

### ISSUE THREAD

**Issue by sudo-shubham** [ElemeFE/element#10883]
### Existing Component
Yes

### Component Name
el-dropdown

### Description
Is there a way to open the el-dropdown using javascript?

**Comment by Leopoldthecoder** [comment]
You can use the `show` method: https://jsfiddle.net/leopoldthecuber/e1g8gu3u/ . It's not on the docs yet, but if this is a popular demand, we'd let people know.
