### ISSUE TITLE
[Bug Report] Sorting failure of table

### ISSUE THREAD

**Issue by liuke115** [ElemeFE/element#10892]
### Element UI version
2.3.6

### OS/Browsers version
windows 10/Chrome 64.0.3282.119

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/liuke115/aLssb8n2/](https://jsfiddle.net/liuke115/aLssb8n2/)

### Steps to reproduce
点击table的表头日期旁边的排序按钮，但是排序不起作用

### What is Expected?
希望使用 <template slot-scope="scope">{{ scope.row.date }}</template>来填充的列也能排序

### What is actually happening?
貌似使用 <template slot-scope="scope">{{ scope.row.date }}</template>来填充的列就不能使用排序功能

**Comment by Leopoldthecoder** [comment]
排序列需要指定 `prop` 属性。

**Comment by liuke115** [comment]
我懂了，多谢
