### ISSUE TITLE
[Bug Report] DatePicker date multi select function. When selecting non current month date, the control will jump to the current month after selection.

### ISSUE THREAD

**Issue by 2016geek** [ElemeFE/element#10890]
### Element UI version
2.3.6

### OS/Browsers version
mac系统/chrome版本 65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/dxyliuchang/00afj77z/](https://jsfiddle.net/dxyliuchang/00afj77z/)

### Steps to reproduce
1.点击下个月，切换到5月
2.点击5月任意2天
3.面板跳转到4月

### What is Expected?
点击非当前月，面板不需要跳转到当前月

### What is actually happening?
点击非当前月，面板跳转到当前月

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/10973
