### ISSUE TITLE
[Feature Request] input complete split display and binding value

### ISSUE THREAD

**Issue by justforuse** [ElemeFE/element#10898]
### Existing Component
是

### Component Name
complete

### Description
Is `el-autocomplete` has the same function like `el-select`‘s `label` and `value`? split display and binding value?

**Comment by Leopoldthecoder** [comment]
For Autocomplete, its binding value and what appears in the input box are always the same.

**Comment by justforuse** [comment]
@Leopoldthecoder  All right.. do you consider to add this feature in the future?

**Comment by Leopoldthecoder** [comment]
Currently no. You can have another variable to handle the label -> value conversion.
