### ISSUE TITLE
[Feature Request] Select Option with Html

### ISSUE THREAD

**Issue by carmas123** [ElemeFE/element#10899]
### Existing Component
Yes

### Component Name
select

### Description
Please can you add the ability to insert html code into select option label:

      <el-select>
        <el-option v-for="item in items"
                   :key="item.key"
                   :label="item.label"    <---Here if I use html into label value it will be converted into text
                   :value="item.key">
        </el-option>
      </el-select>

**Comment by Leopoldthecoder** [comment]
https://element.eleme.io/#/en-US/component/select#custom-template

**Comment by carmas123** [comment]
@Leopoldthecoder Hi and thank you so much for you reply, but I need that this html code is displayed also into "input" control when is selected.

**Comment by Leopoldthecoder** [comment]
> I need that this html code is displayed also into "input" control

I'm not sure if I get this right, but input control only displays plain texts, not HTML strings.

**Comment by carmas123** [comment]
ok...thanks
