### ISSUE TITLE
[Feature Request] For el-table'filter-change'event, can only get current selected filters data

### ISSUE THREAD

**Issue by duxinxiao** [ElemeFE/element#10904]
### Existing Component
是

### Component Name
el-table

### Description
当表格存在多个 filter 的时候，每次改变 filter，filter-change 事件只能拿到当前改变的选项，我认为拿到当前所有的 filter 选项会更好一点

**Comment by Leopoldthecoder** [comment]
可以自己实现：https://jsfiddle.net/leopoldthecuber/xpppuvo2/

**Comment by duxinxiao** [comment]
@Leopoldthecoder 你误解我意思了，比如你给的这个例子，我说的问题是，如果我同时选了两个筛选（日期和标签），handler 拿到的 obj 只有我当前选择的那个筛选项（只有日期，或者标签，但事实是我同时激活了两个）

**Comment by duxinxiao** [comment]
当然这个我也可以自己实现拿到当前选择的所有筛选项，但是我觉得这个行为最好还是改变框架的设计(现在只返回只有一个 key 的 obj，很奇怪不是吗)

**Comment by Leopoldthecoder** [comment]
`filter-change` 的意义是告知筛选条件发生了变化，因此它的参数是**变化的筛选项**，而不是当前所有的**筛选状态**。

**Comment by duxinxiao** [comment]
那文档上写接受参数为 filters 就很不清真了啊。而且这个 filters 参数是个 object，结果这个 object 永远只有一个 key，非常容易让人误解。另外提供一个获取当前选择的所有 filter 非常必要，比如我现在这个需求是想手动处理 filters 的数据，但是没有一个方便的方法拿到全部（手动处理 filter 的人总是关心全部筛选条件的）
