### ISSUE TITLE
[Bug Report] While listening to blur events and Keyup enter events for input, when I trigger keyup enter events, the blur events also be triggered

### ISSUE THREAD

**Issue by essencemike** [ElemeFE/element#10902]
### Element UI version
1.4.2

### OS/Browsers version
macOS High Sierra 10.13 / chrome 66

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/Lnqpqogb/1/](https://jsfiddle.net/Lnqpqogb/1/)

### Steps to reproduce
1. click the new tag button.
2. input something.
3. press return.
4. open the chrome devtools, you can see output 2 times the number 1.

### What is Expected?
1. when I press return, only execute the kekup enter function.
2. when the focus is lost, only execute the loses focus function.

### What is actually happening?
1. when I press return, both execute the keyup enter function and the loses focus function.
2. when the focus is lost, only execute the loses focus function.

**Comment by Leopoldthecoder** [comment]
This is how native input works, so there's not much we can do: https://jsfiddle.net/leopoldthecuber/Lnqpqogb/2/
