### ISSUE TITLE
[Bug Report] Submenu is wrong display where you set width is 200px

### ISSUE THREAD

**Issue by kankk** [ElemeFE/element#10906]
### Element UI version
2.3.3

### OS/Browsers version
MacOS, chrome65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
If you use <el-menu-item> in <el-submenu> and set the width in 200px, you will find that <el-menu-item> with 200px, and <el-submenu> with 199px. and I found that the style in `.el-submenu .el-menu-item` with param about `min-width: 200px`. and I think that cause the two width is not equal. Btw, when I set the width more than 200px, there are in correct display.

### What is Expected?
set <el-menu-item> with 200px
<el-submenu> with (200px or) 199px;
<el-menu-item> 200px;

### What is actually happening?
set <el-menu-item> with 200px
the width of <el-submenu> and <el-menu-item>  is equal

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
