### ISSUE TITLE
 [Bug Report] Must el-form-item be put in el-form?

### ISSUE THREAD

**Issue by tim0991** [ElemeFE/element#10905]
### Element UI version
2.3.6

### OS/Browsers version
osx

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/tim0991/873gtqzb/](https://jsfiddle.net/tim0991/873gtqzb/)

### Steps to reproduce
有两个表单使用的el-form组件，分别是a-form和b-form，两个表单内只有一小部分的item不同，有没有办法把相同的部分抽离出来做成一个component之类的，这样能增加复用程度，链接中一个表单只有三个item，实际情况可能有更多变化，

### What is Expected?
我希望el-form-item可以脱离el-form也能正常运行

### What is actually happening?
el-form-item的外层如果没有el-form则报错

**Comment by Leopoldthecoder** [comment]
把相同的 FormItem 做成组件，然后把这个组件放到 Form 里。

**Comment by tim0991** [comment]
按上述方法拆分子组件之后，如果子组件中包含el-select 无法正常验证，已排除option的type类型问题，确认是string

**Comment by STLighter** [comment]
@tim0991 在jsfiddle写个demo?

**Comment by tim0991** [comment]
@STLighter 已关联了issue
