### ISSUE TITLE
[Bug Report] Question: Select with remote-method and pre-selected value is not rendering.

### ISSUE THREAD

**Issue by johncade** [ElemeFE/element#10909]
### Element UI version
2.3.6

### OS/Browsers version
Windows 10 / Chrome  65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/jnkah8Lv/2/](https://jsfiddle.net/jnkah8Lv/2/)

### Steps to reproduce
I am at a complete loss trying to get this to work. The situation I am in is a I have a select box that uses a remote method to query my api for results. This works pretty well on the initial selection, however when I load the page and a value was previously selected it does not render. I remember having this problem before, so I went back and searched through some previously filed issues of mine and found this: https://github.com/ElemeFE/element/issues/7882

The suggested solution in that issue was to initialize the list I feed to el-option, and it works great if that is possible. However, I have a situation where the API my service pulls from only returns partial results. As a result there is no way to pre-load the entire list. In fact that defeats the whole purpose of remote-search if I have to pre-load every option to only then make remote calls for the select options. This is sort of an obvious problem, so I am sure you guys have developed an approach, but I just cannot find it. Any feedback would be greatly appreciated

### What is Expected?
the pre-selected value renders in the select box

### What is actually happening?
The select box is empty, even though there is a value in the state

**Comment by Leopoldthecoder** [comment]
See the comments in the `mounted` hook: https://jsfiddle.net/leopoldthecuber/jnkah8Lv/3/
