### ISSUE TITLE
[Bug Report] something wrong with  Cascader  component

### ISSUE THREAD

**Issue by SekyGrande** [ElemeFE/element#10900]
### Element UI version
2.3.6

### OS/Browsers version
mac OS / chrome version: 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/sekygrande/x7p5vwzm/](https://jsfiddle.net/sekygrande/x7p5vwzm/)

### Steps to reproduce
just click A , B ,C in the cascader component and see what show on the input and console.log

### What is Expected?
click A , the input show A and the console.log is A

### What is actually happening?
when i click B , the console.log is B but the input is only A , and click C the input is 'A-B',and it happened by accident , same code but different result ,sometime its right.

**Comment by wacky6** [comment]
I don't know what you mean.
I can see only one output with 'A-B-C'

**Comment by Leopoldthecoder** [comment]
Then please minify your project and provide a valid reproduction.

**Comment by SekyGrande** [comment]
![2018-04-26 6 24 26](https://user-images.githubusercontent.com/15918850/39300822-973bdcfc-497f-11e8-98f9-c67e6a5ae386.png)
![2018-04-26 6 24 21](https://user-images.githubusercontent.com/15918850/39300823-978c673a-497f-11e8-93e9-8fd750230d29.png)
@wacky6 @Leopoldthecoder this is what happened.. and it does'nt happen all time..same code  and in other view its right..

**Comment by SekyGrande** [comment]
[https://jsfiddle.net/sekygrande/mmx38qxw/1855/](url) this is my code

**Comment by Leopoldthecoder** [comment]
You should at least make sure your demo actually runs without error.
