### ISSUE TITLE
[Feature Request] Typescript definations

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#10918]
### Existing Component
Yes

### Component Name
All

### Description
Please provide typescript defination files.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/tree/master/types

**Comment by atilkan** [comment]
@Leopoldthecoder 
Why i have to put **// @ts-ignore** everywhere? You know definitions should be better. 
An example might:

<img width="273" alt="screen shot 2018-04-29 at 23 32 49" src="https://user-images.githubusercontent.com/1254613/39410749-b0d96b6a-4c05-11e8-80b6-8fcde87255cc.png">
Shows error and doesn't compile.
<img width="238" alt="screen shot 2018-04-29 at 23 32 54" src="https://user-images.githubusercontent.com/1254613/39410750-b0fcc682-4c05-11e8-84e7-c7ce50bcd241.png">
