### ISSUE TITLE
[Feature Request] select-all for table

### ISSUE THREAD

**Issue by changhuaC** [ElemeFE/element#10915]
### Existing Component
是

### Component Name
el-table

### Description
when use select-all in table compnent for uncheck ,only one param "selection" ,but some time need to known i uncheck what data
but i can't get it now ,the only one  param selection and it return []  ,

**Comment by Leopoldthecoder** [comment]
创建一个变量，在 `selection-change` 事件回调里更新该变量为当前选中的数据即可。
