### ISSUE TITLE
[Bug Report] ElPagination component `internalCurrentPage`'s immediate option result in useless initial `currentPage` setting.

### ISSUE THREAD

**Issue by bq-hentai** [ElemeFE/element#10913]
### Element UI version
2.3.6

### OS/Browsers version
Windows7/Chrome 65

### Vue version
2.5.2

### Reproduction Link
[www.fake-jsfiddle.com](www.fake-jsfiddle.com)

### Steps to reproduce
Download following zip & unzip, then `npm install` and at last, use `npm start` to bootstrap it.

If successfully, the page will show `vm.currentPage === 2`, but the pagination will make the first item active.

I use setTimeout to simulate the async situation:
I should set the initial pagenum to 10(when I return to list page from a detail page) and want to preserve previous pagenum.

I checked the code and found the library(v2.3.6) set the `internalCurrentPage`  to an immediate watcher. If I set a default `currentPage`, the `internalCurrentPage` watcher handler will exec later. But it will check whether it is valid. So the final result is the default value is useless.

The previous version(I use v2.0.11 now but I am not sure what version changed) is ok because the `immediate` option hasn't been set.

Of course, I can jump to the certain page or set the `currentPage` after I load data. But it's not very good when we need  to combine the `ElPagination` and some other components.

### What is Expected?
The default `currentPage` effects.

### What is actually happening?
The default `currentPage` doesn't effect.

**Comment by bq-hentai** [comment]
Test codes are this:
[test_current_page.zip](https://github.com/ElemeFE/element/files/1954508/test_current_page.zip)

NOTE: If I set `:currentPage.sync`, the result is not expected either. It change to first.

**Comment by Leopoldthecoder** [comment]
不是 bug。由于 `total` 的初始值是 0，此时是没有第二页的，因此 `currentPage: 2` 不是一个合法的值，会被重置。当 `total` 变为 50 后，你需要再次把 `currentPage` 赋值为 2。https://jsfiddle.net/leopoldthecuber/pL4gn5ej/4/

**Comment by bq-hentai** [comment]
@Leopoldthecoder 我知道这也不算是bug。今天发现这个问题是我组合了一下 Table和Pagination，形成一个新的组件A，想初始化最初跳转的页码。同事的升级到了2.3.6，debug出来发现的问题。

如果需要在 total 变化之后，再进行 currentPage 赋值，这样的话，如果是通过组合的组件来传递这个初始跳转的页码属性，最后产出的代码并不是很好。而且也并不是很*声明式*。
