### ISSUE TITLE
:file-list="fileList" 上传照片组件动态绑定的问题

### ISSUE THREAD

**Issue by weige0088** [ElemeFE/element#10916]
我使用了 upload 组件    :file-list="fileList"  动态绑定到了一个数组里面
这个动态绑定没有成功是什么个情况
goodsImgList:[ 
        {
          name:"白色",
          id  : 11,
          imageList:[]
        }, {
          name : "黑色",
          id : 12,
          imageList:[]
        }
      ]
根据上面的数组循环出了2个，上传图片列表，  
把每一个  :file-list  绑定到  goodsImgList 数组下面 对象的 数组 imageList   
但是 imageList 里面没有值   这个是什么情况

**Comment by xiaolv899** [comment]
兄弟，最后怎么解决？ @element-bot 的回复没找到解决方案。

**Comment by zhancxcf** [comment]
大兄弟 最后怎么解决呢

**Comment by zhancxcf** [comment]
大兄弟 最后怎么解决呢@ @weige0088
