### ISSUE TITLE
[Bug Report] TimePicker plugin in from rules can't get value

### ISSUE THREAD

**Issue by a1245582339** [ElemeFE/element#10924]
### Element UI version
2.3.6

### OS/Browsers version
Google Chrome  66.0.3359.139

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/49mjwrav/1/](https://jsfiddle.net/49mjwrav/1/)

### Steps to reproduce
在表单中加入时间选择器，rules设置为必填，触发设置为change，改变时间，无法获取到时间，表单验证始终为未填写

In the form, the TimeSelect is added, the rules set is required, the trigger is set to change, the time is changed, the time can not be obtained, the form validation is always unfilled.

### What is Expected?
改变时间，表单验证可以正常显示

Change the time, the form validation can be displayed normally

### What is actually happening?
改变时间，表单验证显示异常，无法获取更改的值

Change time, form validation exception, unable to get the change value.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/49mjwrav/2/
