### ISSUE TITLE
[Bug Report] el-menu-item updated index without updating items of parent component el-menu.

### ISSUE THREAD

**Issue by xubaifuCode** [ElemeFE/element#10926]
### Element UI version
2.3.6

### OS/Browsers version
Window 10 / Google Chrome版本 66.0.3359.139

### Vue version
2.5.16

### Reproduction Link
[https://github.com/xubaifuCode/nav-project](https://github.com/xubaifuCode/nav-project)

### Steps to reproduce
运行项目后，分别点击顶部的【菜单1】和【菜单2】，在控制台可看到输出内容。
![image](https://user-images.githubusercontent.com/14217592/39393349-e9920a08-4af6-11e8-9bc5-55e34e368a77.png)

### What is Expected?
单击【菜单2】后，【我的菜单1】的is-active样式被激活。
如下图：
![image](https://user-images.githubusercontent.com/14217592/39393357-fd77cfd0-4af6-11e8-9cf1-bb54ca5a2adb.png)

### What is actually happening?
单击【菜单2】后，【我的菜单1】的is-active样式没有被激活。同时，手动点击【菜单2】下【我的菜单1】时，样式也没有激活，只有【菜单1】下的导航菜单有激活样式。
如下图：
![image](https://user-images.githubusercontent.com/14217592/39393366-105f0078-4af7-11e8-8154-d30a124ee25c.png)

看过源码后发现是el-menu的items没有随着el-menu-item的index改变。

**Comment by Leopoldthecoder** [comment]
https://github.com/xubaifuCode/nav-project/pull/1

**Comment by fuqi1001** [comment]
Hi there, I face the same problem here. Do you have any way to solve this, sorry the repo is already deleted.
