### ISSUE TITLE
table 的 inline-template 有问题

### ISSUE THREAD

**Issue by wikidson** [ElemeFE/element#1092]
代码：
`<el-table-column
                    inline-template
                    label="operation"
                    width="100">
                    <span>
                        <el-button type="primary" icon="edit"></el-button>
                        <el-button type="primary" icon="share"></el-button>
                        <el-button type="primary" icon="delete"></el-button>
                    </span>
            </el-table-column>`

报错：

 [Vue warn]: Error when rendering component <table-body>
TypeError: _vm._h is not a function(…)

如果不内嵌element 的标签，即代码修改成这样：

`<el-table-column
                    inline-template
                    label="operation"
                    width="100">
                    <span>
                         <span>Edit</span>
                        <span>Delete</span>
                    </span>
            </el-table-column>`

是ok的；

再赶项目，求回答。。。急。。。急。。。急。。。

**Comment by Leopoldthecoder** [comment]
和 #1065 #1032 重复，里面有解决方案。或者等今天的新版本。

**Comment by wikidson** [comment]
今天什么时候发布新版本啊。。。
