### ISSUE TITLE
Can the content in the array of [Feature Request] checkbox-group's V-model properties be an object?

### ISSUE THREAD

**Issue by GrapeDing** [ElemeFE/element#10925]
### Existing Component
是

### Component Name
el-checkbox-group

### Description
如果checkbox-group的v-model绑定的数组的内容是对象的时候，给该数组赋值之后，复选框没有显示任何选中状态

**Comment by Leopoldthecoder** [comment]
不支持对象。

**Comment by zgr126** [comment]
所以遇到同名id定位的情况咋办
