### ISSUE TITLE
[Bug Report] checkbox component indeterminate status problem. Default values are all selected instead of check styles.

### ISSUE THREAD

**Issue by jessonxiang** [ElemeFE/element#10934]
### Element UI version
2.3.6

### OS/Browsers version
Google Chrome  65.0.3325.181

### Vue version
2.5.13

### Reproduction Link
https://jsfiddle.net/pb7ofeo0/

### Steps to reproduce
将默认选中值设置为全部  但是 全选那里还是显示 indeterminate的样式.而不是全部选中

### What is Expected?
当值为全部选中时显示被选中状态 即 is check 的样式

### What is actually happening?
当前版本显示的是  indeterminate样式

- [ ] 
![_20180428182354](https://user-images.githubusercontent.com/24713249/39395476-8144f832-4b11-11e8-89bc-ac64fbe96e72.png)

**Comment by jessonxiang** [comment]
重现链接:https://jsfiddle.net/pb7ofeo0/

**Comment by jessonxiang** [comment]
https://jsfiddle.net/pb7ofeo0/

**Comment by wacky6** [comment]
https://jsfiddle.net/pb7ofeo0/1/

初始值要自己算
