### ISSUE TITLE
[Bug Report] Problem of verify

### ISSUE THREAD

**Issue by 01wqx** [ElemeFE/element#10935]
### Element UI version
2.3.6

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
我们系统使用第三方vue-verify-plugin做表单校验，在本地开发时表单校验的提示信息没有显示，但服务器上的可以正常显示。在本地开发的问题，经过多次操作发现需要触发dom树的重绘才能让表单校验的提示信息显示。在控制台打日志，服务器上跟本地的流程一样。
English:I use the third party vue-verify-plugin to do the form check. The prompt message of the form validation is not displayed when the local development is developed, but the server can display normally. In the case of local development, after multiple operations, the redraw of the dom tree needs to be triggered to display the prompt message of the form validation. Log on the console, the same as the local process on the server.

### What is Expected?
本地开发跟服务器上的效果一样，当触发校验时，显示校验提示信息
English:The local development is the same as the one on the server, when the check is triggered, the check prompt message is displayed.

### What is actually happening?
本地开发的提示信息没有显示，需要触发dom树重绘才能显示出来。
English：The local development prompt does not show that the dom tree redraw is needed to display.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
