### ISSUE TITLE
How does [Feature Request] check the file upload component form? Trigger is filled with change and cannot trigger checkout

### ISSUE THREAD

**Issue by LeifJG** [ElemeFE/element#10941]
### Existing Component
是

### Component Name
el-upload

### Description
校验文件上传组件表单trigger内填change，无法触发校验，如何校验?

**Comment by Leopoldthecoder** [comment]
因为服务端的返回是千变万化的，所以目前 Upload 没有类似 Input 等表单组件的绑定值的概念，需要在上传成功后自行更新变量并触发校验：https://jsfiddle.net/leopoldthecuber/1neyqayL/

**Comment by zzlw** [comment]
同问 https://jsfiddle.net/leopoldthecuber/1neyqayL/ 打不开

**Comment by okool** [comment]
不得不吐cao,el的组件质量真差劲.扩展性极差,各种常见业务场景不支持,,很多pr都没关闭,只能重写.

**Comment by Even-Lau** [comment]
您好，上面回答为自动上传的情况。手动上传的情况下，又该如何在上传前触发校验呢？ @Leopoldthecoder

**Comment by hqzh** [comment]
转antd吧
