### ISSUE TITLE
npm  包版本固定 && 新版本具体时间

### ISSUE THREAD

**Issue by wikidson** [ElemeFE/element#1094]
1. 建议使用 npm 的版本 固定配置文件 或者 使用 yarn ， yarn.lock 还是不错的
2. 今天发布新版本的具体时间有么。。。

**Comment by QingWei-Li** [comment]
1. 暂时没有开发阶段需要锁定版本的需求
2. 下午

**Comment by wikidson** [comment]
好的，谢谢。
