### ISSUE TITLE
[Bug Report] could you tell me how to Encapsulation components with have "cope" in table

### ISSUE THREAD

**Issue by eyii** [ElemeFE/element#10943]
### Element UI version
2.3.6

### OS/Browsers version
win7

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
could you tell me how to Encapsulation components with have "cope" in table

### What is Expected?
could you tell me how to Encapsulation components with have "cope" in table

### What is actually happening?
could you tell me how to Encapsulation components with have "cope" in table

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/2rj6juga/
