### ISSUE TITLE
[Bug Report] angular paging component does not have pageSizeChange event! Hurry up!

### ISSUE THREAD

**Issue by Yin-Xie** [ElemeFE/element#10958]
### Element UI version
2.3.7

### OS/Browsers version
win10 64位 chrome最新

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com](https://github.com)

### Steps to reproduce
pageSizeChange事件

### What is Expected?
pageSizeChange事件

### What is actually happening?
pageSizeChange事件

**Comment by wacky6** [comment]
We don't deal with angular version's issue here.
