### ISSUE TITLE
Can [Feature Request] paging component add events before triggering page?

### ISSUE THREAD

**Issue by yf287** [ElemeFE/element#10959]
### Existing Component
是

### Component Name
pagination

### Description
希望添加新功能，点击翻页，页码改变前提供一个事件，可以用于做判断，若未通过判断，则不翻页，不改变页码

**Comment by JjiaoLiu** [comment]
你可以尝试在el-pagination添加自定义事件---如果事件成功，设置当前页current-page为你想要的值；否则，你的错误处理。

**Comment by Leopoldthecoder** [comment]
可能没有太大必要，可以直接在 `current-change` 中处理，如果不满足某些条件，把当前页复原为之前的值即可。

**Comment by cliens** [comment]
还是加上勾子是比较合理的

**Comment by hthmh** [comment]
感觉current-change中复原之前的值还需要watch一下保存之前的值
