### ISSUE TITLE
[Feature Request] Select: filter-mothod design improvement 

### ISSUE THREAD

**Issue by KedAyAyA** [ElemeFE/element#10952]
### Existing Component
是

### Component Name
Select

### Description
In Select component, I set filterable and the component can filter the data bind with el-option automatically with the value I input in the select component. That's awesome and work as expected.
But in some cases, I have to filter data use some ways which is not simple like the default. For example, I have a list data like 
```
[
  {
    name: '北京',
    abbr: 'bj',
    pinyin: 'beijing'
  },
 {
  ... so many
 }
]
```
Now I have a requirement to filter by name, abbr & pinyin. So I define a function to bind filter-method, expecting to filter data successfully. But nothing happend. It is invoked but data list don't change.

I read the source code and find it is just called but not send emit to change the options' visiable value. And I wonder why the default filterable can work well so I read more. At last I find it emit 'queryChange' to options and queryChange method just use a regexp to filter the data you input to test label, then changing the visiable value. But if use filter-mothed, it can't work. So i must to define another array to save the filterable data and that leads to the problem i must write more extra code and more place to save the filterabel array.I think that's not elegant.

So I wonder if it can be a more elegant way to implement the filter-method or a more elegant way to this requirement.

Thank you for your work in Element. That's a awesome UI Components.

**Comment by wacky6** [comment]
Good idea. I agree that filter-method should behave similarly to native array.filter.

But, this is a breaking change, so we won't consider such change unless there is a major version update.

**Comment by KedAyAyA** [comment]
Got it. Looking forward to it! ^_^

**Comment by lilililee** [comment]
Has this problem been solved?

**Comment by KedAyAyA** [comment]
You can look forward to the new Version.

**Comment by miccuci** [comment]
Is there any other way to solve the problem?
I had try filter-method,but exist a bug that when input value is always change

**Comment by miccuci** [comment]
find a simple way to solve the problem,here are the code
`
<el-select v-model="queryParams.medicineTypeCode" clearable filterable >
                <el-option v-for="(item, index) in dictDataList[0]"
                  :key="index"
                  :label="`${item.valueDesc}                                                                                              ${item.pinyin+item.wubi}`"
                  :value="item.valueId">
                  <span>{{item.valueDesc}}</span>
                </el-option>
              </el-select>
`
you need to add many blank to hide other fields
上面是一段示例代码，可以通过给label属性拼接上你需要模糊检索的字段，同时在显示值和其他字段中间需要添加一段空格将其他字段挤开，避免选中值后将其他字段也显示出来
