### ISSUE TITLE
[Feature Request], do you support webpack to directly introduce corresponding components through improt source and do your own debugging?

### ISSUE THREAD

**Issue by kidsit** [ElemeFE/element#10950]
### Existing Component
是

### Component Name
radio-group, radio

### Description
我使用radio-group和radio组件在手机微信浏览器中发现radio选择不起作用，为了调试解决对应的问题，我希望直接import radio-group和radio的vue代码方式build，并加上一些自己的调试代码来调查问题。请问，能够支持直接import source的方式来引用对应的vue文件并且通过webpack build到自己的bundle中去？如果支持，请问如何操作？

**Comment by kidsit** [comment]
i found myself, it is ok using import Radio from 'element-ui/packages/radio'.
But still no clue to fix the issue itself. Radio item click in wechat browser will pop up input bar, the radio model value not changed.

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop, it is strongly discouraged to use it on mobile devices. As for importing the source component, you're doing it right.

**Comment by kidsit** [comment]
i also found root cause why not work in wechat browser: node_modules has not been babel transpiled. 
@Leopoldthecoder , Is there a mobile version for element?　It is great to use in desktop web app. But not very great in mobile browser.
