### ISSUE TITLE
Message box has a bug

### ISSUE THREAD

**Issue by johnninja** [ElemeFE/element#10967]
### Element UI version
2.3.7

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击关闭按钮或确定按钮关闭弹窗，看浏览器控制台

### What is Expected?
不报错

### What is actually happening?
报错: Uncaught (in promise) cancel

**Comment by Leopoldthecoder** [comment]
不是 bug，因为点击取消实际是 reject 了一个 promise，所以需要 catch 一下。
