### ISSUE TITLE
When [Bug Report] nested el-form components, the el-form-item elements in the subcomponents are not normally checked.

### ISSUE THREAD

**Issue by tim0991** [ElemeFE/element#10966]
### Element UI version
0.1.0

### OS/Browsers version
OSX

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/tim0991/kw13d45s/](https://jsfiddle.net/tim0991/kw13d45s/)

### Steps to reproduce
填写子组件表单元素时出现问题

### What is Expected?
嵌套的子组件中的表单元素可以被正常校验

### What is actually happening?
子组件中的元素无法校验，不论输入或者不输入，都显示 xxx is required

**Comment by tim0991** [comment]
https://github.com/ElemeFE/element/issues/10905

**Comment by STLighter** [comment]
表单验证找的是`form`上的`model`, 查找`model`上对应的prop`, 因此在你的例子中需要保证`this.ruleForm.desc`有值.
例如:https://jsfiddle.net/ST_Lighter/2pjqbdrg/1/

**Comment by Leopoldthecoder** [comment]
请参照 @STLighter 给出的例子。

**Comment by tim0991** [comment]
@STLighter 那是不是意味着需要为子组件中每个`el-form-item`元素都挨个设置类似的`change`事件来确保子组件与父组件之间的数据同步？

**Comment by STLighter** [comment]
@tim0991 可以尝试mixins/extends

**Comment by tim0991** [comment]
请问有没有例子啊。。。

**Comment by STLighter** [comment]
Sorry, 可能我理解错了你前面的意思. 
如果想要一个子组件里面出现多个`el-form-item`, 并且保证父子组件的耦合较小的话, 是需要挨个设置属性的.
但也有简单的实现方法, 但会导致组件间数据的耦合. 具体的做法就是将`ruleForm`对象''穿透''到子组件里面.
举例: https://jsfiddle.net/ST_Lighter/2pjqbdrg/2/
