### ISSUE TITLE
When [Bug Report] uses DateTimePicker, when startTime is set up sometimes, endTime changes at the same time.

### ISSUE THREAD

**Issue by wensmoke** [ElemeFE/element#10960]
### Element UI version
2.3.7

### OS/Browsers version
ubuntu16.04/firefox59.0.2

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/fantuan/ucmjfmv8/](https://jsfiddle.net/fantuan/ucmjfmv8/)

### Steps to reproduce
1.设置开始和结束日期为通一天，如2018-05-03。
2.点击开始时间的时间输入框，选择输入时间

### What is Expected?
点击开始时间的时间输入框，选择输入时间，选择时，结束时间的时间输入框的值不变

### What is actually happening?
点击开始时间的时间输入框，选择输入时间，选择时，结束时间的时间输入框的值改变了

**Comment by wacky6** [comment]
因为结束时间不能早于开始时间。
