### ISSUE TITLE
[Bug Report] El -table wide adaptive, Give width a width,style="width:100%" doesn't work.1.4 version can.

### ISSUE THREAD

**Issue by s-jingli** [ElemeFE/element#10977]
### Element UI version
2.3.7

### OS/Browsers version
google

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
el-table给列一个宽度width:70,然后设置el-table样式style="width:100%",结果并没有自适应100%，老版本1.4是可以的，升级最新版本后就不行了

### What is Expected?
el-table给列一个宽度width:70,然后设置el-table样式style="width:100%",列宽自动填充，表格充满100%。

### What is actually happening?
el-table给列一个宽度width:70,然后设置el-table样式style="width:100%",列宽固定70*n列，表格未填充100%，空出一大截，style="width:100%"没起作用

**Comment by Leopoldthecoder** [comment]
1.4 也不能「自适应」：https://jsfiddle.net/leopoldthecuber/1qrdcvw9/ 。对于 `<el-table-column>`，宽度一定是 width 属性指定的值，不会根据内容调整。
