### ISSUE TITLE
[Feature Request] Add event when slider value is reset due to invalid value

### ISSUE THREAD

**Issue by jiayexie** [ElemeFE/element#10976]
### Existing Component
Yes

### Component Name
Slider

### Description
When providing a slider with input, if the user types an invalid value into the input, the value gets reset without any warning. We'd like to show some kind of hint as why the value gets reset so the user is not confused. Would you be able to provide an event hook with the reset reason?

Example scenario: I have a slider with minimum value of 1000 and maximum value of 10000, and step set to 1000. The initial value of the input is 1000. User tries to change the value by hitting backspace on the number input, but as soon as the value is changed to 100, it restores itself to 1000. This looks like a buggy experience, and we'd like to let the user know why this is happening.

**Comment by wacky6** [comment]
In this case, I think it's better to tell users about the minimum and maximum value on the UI (a label or hint), so they can get it right at first attempt, instead of correcting them when things goes wrong (they still have to input the correct thing afterwards).

**Comment by jiayexie** [comment]
Thanks, that makes sense, but I still wonder if it's the right experience for users who are just trying to clear and type in the right value. e.g. I know the minimum value is 1000 and I'd like to type in 2000, but as soon as I start backspacing to delete the current value, it resets itself without giving me the chance to type in the correct value.

**Comment by jikkai** [comment]
@jiayexie 
In my opinion, although the component gives users the chance to manually fix the invalid value, they may still forget to do it.
As @wacky6 said, the better way is clearly to tell users the `min` and `max` value on the UI.
