### ISSUE TITLE
[Bug Report] I have some problems with editing and checking in the form.

### ISSUE THREAD

**Issue by heqh** [ElemeFE/element#10979]
### Element UI version
2.3.7

### OS/Browsers version
window7    chrome 44.0.2403.89

### Vue version
2.5.17-beta.0

### Steps to reproduce
我在 el-table 外面套了一个  el-form  我需要在表格里面直接遍历 
然后在提交的时候   我是遍历每一行  将每一行的数据 赋值给 el-form的 model
因为每一行的 字段名都一样的  我只能逐行校验。
  
然后调用 el-form的  validate 校验方法    
但结果我发现  我哪怕将表格的  第一行赋值给  form  最终校验的时候  还是去的 表格的最后一行去校验 
第二次再校验就对了  第一次一直错误。

### What is Expected?
我希望  form 的 validate 能使用 我手动给 form 赋值的数据去校验。

this.tableData.map(functino(obj, index){
    this.formData = obj;
    _this.$refs['testForm'].validate();
});
   
我有这种操作。

### What is actually happening?
this.tableData.map(functino(obj, index){
    this.formData = obj;
    _this.$refs['testForm'].validate();
});
实际上我的 赋值操作没效果  校验最终还是 拿tableData的最一行数据校验的   没有使用我赋值的数据

**Comment by wacky6** [comment]
写个demo吧

**Comment by heqh** [comment]
http://hzc14.com/vue.html#/tableEdit

**Comment by heqh** [comment]
是不是有些处理是同步的 我赋值后  延迟个100毫秒再去校验 就对了

**Comment by wacky6** [comment]
麻烦 https://jsfiddle.net/ 或者 https://codepen.io/ 。你这个看不到代码，并且请不要带上业务逻辑

**Comment by Leopoldthecoder** [comment]
<p align="center">
  <table>
    <tbody>
      <tr>
        <td align="center" valign="middle">
          <a href="https://tipe.io/?ref=element" target="_blank">
            <img width="150px" src="https://user-images.githubusercontent.com/1016365/34124854-48fafa06-e3e9-11e7-8c04-251055feebee.png">
          </a>
        </td>
        <td align="center" valign="middle">
          <a href="https://www.duotai.cn/?utm_source=element" target="_blank">
            <img width="140px" src="https://user-images.githubusercontent.com/10095631/39403151-c42dbcee-4ba5-11e8-9c09-8e5283da4144.png">
          </a>
        </td>
        <td align="center" valign="middle">
          <a href="https://www.duohui.cn/?utm_source=element&utm_medium=web&utm_campaign=element-index" target="_blank">
            <img width="150px" src="https://user-images.githubusercontent.com/10095631/35603534-bb24470c-0678-11e8-8bcc-17ceaef8cbef.png">
          </a>
        </td>
      </tr>
    </tbody>
  </table>
</p>
