### ISSUE TITLE
[Bug Report] NavMenu component, moved into the removed bug

### ISSUE THREAD

**Issue by lky5230** [ElemeFE/element#10978]
### Element UI version
2.3.7

### OS/Browsers version
win32/chrome 64

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/lky5230/m8doqvrv/](https://jsfiddle.net/lky5230/m8doqvrv/)

### Steps to reproduce
1、为 NavMenu 组件的 subMenu 增加 v-bind:popper-append-to-body="true" 属性
2、鼠标移到1级菜单出现2级菜单，再移到2级菜单上出现3级菜单，再移到3级菜单
3、鼠标离开3级菜单并且注意不要 移到1级、2级菜单上
4、3级菜单消失，但是2级菜单不消失

### What is Expected?
不管鼠标离开3级，甚至4级，都只保留1级菜单

### What is actually happening?
鼠标离开3级并且不再移到1级和2级菜单，3级消失但2级不消失

**Comment by cel533** [comment]
是的我也发现了这个BUG...我是2.3.4...

**Comment by jikkai** [comment]
@lky5230 
一般好像只挂载一个层级的`submenu`就足够了，是有什么需要都挂载到 body 的场景吗？
https://jsfiddle.net/0e2fnmwL/

**Comment by lky5230** [comment]
@jikkai 有些需求是左侧菜单栏需要三层

**Comment by jikkai** [comment]
@lky5230
像我前面那个 demo 一样只对最外层设置`popper-append-to-body`似乎可以实现你的需求

**Comment by jikkai** [comment]
对已经设置了 `popper-append-to-body` 的 submenu 内嵌套的 submenu 再设置 `popper-append-to-body` 似乎是一个**没有必要**的操作，应当尽量避免这种使用方式。后续考虑对这种边缘 case 做下处理，这个 issue 先关了。
