### ISSUE TITLE
[Bug Report] Explicitly set the datepicker value

### ISSUE THREAD

**Issue by bcsthecoder** [ElemeFE/element#10983]
### Element UI version
2.3.6

### OS/Browsers version
Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/NifrasBcs/zL9wpy1r/4/](https://jsfiddle.net/NifrasBcs/zL9wpy1r/4/)

### Steps to reproduce
1)Click on radio button
2)Look at the datepicker, It's not update the value

### What is Expected?
Need to set the datepicker value through the radio button.

### What is actually happening?
Datepicker does not bind the date value explicitly.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/zL9wpy1r/5/
