### ISSUE TITLE
The [Feature Request] table component sets a fixed property separately for the header, for scrolling lists.

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#10986]
### Existing Component
是

### Component Name
table

### Description
有时候表格组件只是作为一个浮层，其高度随着台式机或者笔记本的高速变化，想要保证表头不随滚动条滚动，但是我只设置了table外层的高度(通过css设置)以及设置   overflow-y: auto;
![image](https://user-images.githubusercontent.com/8147202/39565387-51c7a33e-4eea-11e8-8d32-a5f406a43b5f.png)

demo：[https://codesandbox.io/s/5y3ywyq37x](https://codesandbox.io/s/5y3ywyq37x)

**Comment by Leopoldthecoder** [comment]
https://codesandbox.io/s/nrkjj8kz0p
