### ISSUE TITLE
[Bug Report] ElFormItem missing TypeScript declarations for necessary method

### ISSUE THREAD

**Issue by zhangbobell** [ElemeFE/element#10981]
### Element UI version
2.3.7

### OS/Browsers version
macOS High Sierra 10.13.3/版本 66.0.3359.117（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://www.jsfiddle.com/not.necessary](https://www.jsfiddle.com/not.necessary)

### Steps to reproduce
`resetField` methods was not included in `form-item.d.ts`, but appears in the documentation.

**Besides**, If developer wants to control the validate message in item grain, if we just expose `resetField`, it's not enough. would we also expose `validate` and `clearValidate` method ? Since `validateField` method is include in `form.d.ts`.

**PS**: Discussion is welcome, and if need, I would like to propose a pull request for this.

### What is Expected?
`form-item.d.ts` include:
1. `resetField`
2. `validate`
3. `clearValidate`

### What is actually happening?
`form-item.d.ts` not include:
1. `resetField`
2. `validate`
3. `clearValidate`

**Comment by Leopoldthecoder** [comment]
OK, I'll add `clearValidate` on the docs and `form-item.d.ts`.

**Comment by zhangbobell** [comment]
Thanks so much !
