### ISSUE TITLE
[Bug Report] Rate Icon No display

### ISSUE THREAD

**Issue by 18402025768** [ElemeFE/element#10988]
### Element UI version
2.3.7

### OS/Browsers version
谷歌最新版

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/t8a873pe/1/](https://jsfiddle.net/t8a873pe/1/)

### Steps to reproduce
没有像官方文档一样显示自定义图片

### What is Expected?
7

### What is actually happening?
代码出现BUG

**Comment by Leopoldthecoder** [comment]
自定义图标类名时，你需要自行准备对应的 iconfont。
