### ISSUE TITLE
Clear icon is displaying while nothing selected when v-model is object

### ISSUE THREAD

**Issue by akki-jat** [ElemeFE/element#10999]
OS : Windows 7
Browser: Chrome 66.0.3359.139
Vue : 2.5.11
Element UI : 2.3.7

Reproduction Link : https://codepen.io/akki-jat/pen/MGoGEP

Steps to reproduce: Just hover to select component

What is Happening? : Clear icon is visible

What supposed to happen: Clear should not be visible

Here is the image also :

![1](https://user-images.githubusercontent.com/26685162/39575460-99975ca0-4ea8-11e8-831a-978dec6d1d2c.png)

**Comment by akki-jat** [comment]
Issue generator is not working.
It is not showing Repository Version and Vue Version.

**Comment by akki-jat** [comment]
Hi @Leopoldthecoder, can you tell if it is bug or intended work like that?

**Comment by Leopoldthecoder** [comment]
This is an edge case we didn't cover. For now I suggest setting `selectedModelValue` to `undefined` or `''`: https://codepen.io/leopoldthecoder/pen/RyxomK

**Comment by akki-jat** [comment]
@Leopoldthecoder, if there is any progress then tell me, for now I am closing this issue.
Thnaks.
