### ISSUE TITLE
[Feature Request] form lable supports custom styles

### ISSUE THREAD

**Issue by shiqian123** [ElemeFE/element#10991]
比如 lable="测试代码" 我想让测试显示蓝色，代码显示红色

### Existing Component
No

### Component Name
2.3.7

### Description
Chrome 版本 66.0.3359.139（正式版本） （64 位

**Comment by STLighter** [comment]
这样?
https://jsfiddle.net/ST_Lighter/3ex5o2od/

**Comment by Leopoldthecoder** [comment]
@STLighter 多谢回复，@shiqian123 问的应该是 Table：https://jsfiddle.net/leopoldthecuber/h3ydpk6k/
