### ISSUE TITLE
[Bug Report] Pagination current-change bug

### ISSUE THREAD

**Issue by Attax** [ElemeFE/element#10992]
### Element UI version
2.3.7

### OS/Browsers version
windows 10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1880/](https://jsfiddle.net/mmx38qxw/1880/)

### Steps to reproduce
At first if  you change the select component to trigger filterQuery function,the current-page will be the correct  number '1',and you click the Pagination Component like 2 or 3 or any nubmer which is not the no.1,and next you change the select component,you will find that the current page wasn't the No.1 that you expected.And you click the highlight page no,the callback function can't be triggered。It means that the current page was the no you clicked last time before you changed the select componet.

### What is Expected?
The 'current page' will be the correct number 

### What is actually happening?
The 'current page' was not the correct number

**Comment by STLighter** [comment]
try`:current-page.sync`
https://jsfiddle.net/ST_Lighter/mmx38qxw/1881/

**Comment by Leopoldthecoder** [comment]
You need `.sync` indeed, otherwise `this.curPage` will stay `1` as you click the pagers.

**Comment by Attax** [comment]
@STLighter Yeah,It will works at some simple demo,but in my real project,I need to register a user-defined component like this https://jsfiddle.net/mmx38qxw/1883/ ，and the `.sync` will not works. And if I add the `.sync` to the Pagination component which was imported by me,the error will be occured.

**Comment by Attax** [comment]
@STLighter @Leopoldthecoder In fact.before the version 2.3.0 Diamond,The bug of current-change has exist for a long time,I guess the bug's was like this:users set the current-page by hand,the current-change callback method will be emited.Thougth it was a bug ,I can compare the old value of current-page width the new value to avoid this question.But now,I have no idea to solve this.Could you help me?Thank you very much.如果没办法，我就只能去饿了么公司当面请教两位了

**Comment by STLighter** [comment]
https://jsfiddle.net/ST_Lighter/mmx38qxw/1884/
`$emit` an `update` event in `handleChangePage` to make `.asyc` work.
see Vue docs for more https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier

**Comment by Attax** [comment]
@STLighter thank you very much !I did not kown Vue support $emit an update event,Thank you for your time !
