### ISSUE TITLE
How does text in [Bug Report] table implement a newline?

### ISSUE THREAD

**Issue by aforwardz** [ElemeFE/element#10996]
### Element UI version
2.3.6

### OS/Browsers version
Ubuntu16.04

### Vue version
2.5.12

### Reproduction Link
[https://jsfiddle.net/aforwardz/smbsswc8/](https://jsfiddle.net/aforwardz/smbsswc8/)

### Steps to reproduce
table中text中，无论是\n还是\r\n还是</br>都无法解析出来实现换行

### What is Expected?
文本换行

### What is actually happening?
未解析换行符

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/smbsswc8/3/

**Comment by KevinHeidi** [comment]
請問下，table text無法解析\n執行換行的問題解決沒？

**Comment by aforwardz** [comment]
@KevinHeidi 你看上面jsfiddle里的例子，用\</br\>可以换行

**Comment by XiaoJianPeng** [comment]
请问下  换行符解析不了的问题解决了吗？我用</br> 也不可以啊
