### ISSUE TITLE
[Feature Request] Allow el-select remoteMethod to be triggered on focus

### ISSUE THREAD

**Issue by aleksei-a-savitski** [ElemeFE/element#10994]
### Existing Component
Yes

### Component Name
el-select

### Description
Currently: El-select doesn't execute remoteMethod when select is focused. 
Expected: remoteMethod to be executed with empty query.

The current behaviour was introduced in v2.2.2 with this commit https://github.com/ElemeFE/element/commit/62b0e2ace9f607d2b0c73e77972695613382277a. In case of simple filterable el-select it is natural that all options are already available on front-end and they are shown on focus. But in case of remote search it's more desirable to make a request for default options only when user focuses on the element. Removing trigger for remoteMethod on focus makes setting default options for el-select more complicated. For example if we have many el-select with remote search, we would need to prefetch default options, which requires requesting them from backend proactively. We would like to avoid it, so we would have to fetch default options on @focus event. Does this complication make sense?

**Comment by WangHansen** [comment]
I agree with the proposal, currently the hack is to also call the function at `focus` event
for example:
```javascript
<el-select
    :remote-method="callAPI"
    @focus="callAPI"
    ...
></el-select>
```
