### ISSUE TITLE
[Bug Report] pagination current-change event doesn't trigger

### ISSUE THREAD

**Issue by mvpleung** [ElemeFE/element#11007]
### Element UI version
2.3.7

### OS/Browsers version
Chrome 64.0.3282.140

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mcrj9j0u/](https://jsfiddle.net/mcrj9j0u/)

### Steps to reproduce
1.点击下一页，current-change 正常触发，显示当前页码为 2

2.点击下方 “第一页” 按钮，current-change 不会触发

3.继续点击下一页，current-change 不会触发

### What is Expected?
1.点击下一页，current-change 正常触发，显示当前页码为 2

2.点击下方 “第一页” 按钮，current-change 触发，显示当前页面为 1

3.继续点击下一页，current-change 触发，显示当前页面为 2

### What is actually happening?
1.点击下一页，current-change 正常触发，显示当前页码为 2

2.点击下方 “第一页” 按钮，current-change 不会触发

3.继续点击下一页，current-change 不会触发

**Comment by mvpleung** [comment]
跟踪源码，发现是 lastEmittedPage 这个状态没有重置，手动改变当前页面的时候，lastEmittedPage 的值没有改变，导致点击下一页时
`if (**this.internalCurrentPage !== this.lastEmittedPage** || this.userChangePageSize) {
          this.$emit('current-change', this.internalCurrentPage);
          this.lastEmittedPage = this.internalCurrentPage;
          this.userChangePageSize = false;
        }`
**this.internalCurrentPage !== this.lastEmittedPage** 校验未通过

**Comment by Leopoldthecoder** [comment]
> 点击下方 “第一页” 按钮，current-change 不会触发

通过代码修改当前页不会触发 `current-change` 事件。

**Comment by kerwin1** [comment]
@Leopoldthecoder 我的分页是保存在vuex中的，和localStorage同步。current-page是直接绑定的vuex的值。那这么，我如果从第二页进入后，返回，就一直就显示的第一页了？有什么办法，返回时候，第二页的分页数字高亮么
