### ISSUE TITLE
[Feature Request] the width of the recommended tips with autocomplete

### ISSUE THREAD

**Issue by wslyh123** [ElemeFE/element#11005]
### Existing Component
是

### Component Name
el-autocomplete

### Description
带提示的输入框在弹出提示的时候由于提示信息太长不能全部显示，希望能够动态改变提示框的长度,谢谢。
when I use the autocomplete with the recommended tips, the tips are too long to show all of them, I hope the width of the tips box can change automatically, thanks a lot.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/sphqza5b/
