### ISSUE TITLE
[Feature Request] Form form custom check rule, no asterisk (*)

### ISSUE THREAD

**Issue by asd8855** [ElemeFE/element#11009]
### Existing Component
是

### Component Name
Form

### Description
Form 表单自定义校验规则，没有星号（*）；
有的表单项需要自定义校验规则，但是自定义校验规则的表单项前面没有*号，导致视觉上不统一

**Comment by Leopoldthecoder** [comment]
星号仅代表必填。

**Comment by asd8855** [comment]
已解决添加required 即可

**Comment by asd8855** [comment]
@Leopoldthecoder  自定义组件怎么添加校验，change blur都触发不了
