### ISSUE TITLE
When [Bug Report] table has 2 levels of header, modify the data and bug of the header.

### ISSUE THREAD

**Issue by Grewer** [ElemeFE/element#11014]
### Element UI version
2.3.7

### OS/Browsers version
MacOS 10.12.5 / Chrome 66.0.3359.139

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/grewer/ogkro4uq/](https://jsfiddle.net/grewer/ogkro4uq/)

### Steps to reproduce
 点击 change data 按钮

### What is Expected?
表格显示正常

### What is actually happening?
少了一列的数据,并且数据重叠,在我使用了 doLayout() 和 clearSort() 这两个方法后仍无效

**Comment by Leopoldthecoder** [comment]
需要在 `<el-table-column>` 上加 `key`：https://jsfiddle.net/ogkro4uq/2/
