### ISSUE TITLE
[Feature Request] Submit Event for -el-form

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#11016]
### Existing Component
Yes

### Component Name
el-form

### Description
Please provide submit event for el-form component.

**Comment by Leopoldthecoder** [comment]
`@submit.native`

**Comment by atilkan** [comment]
@Leopoldthecoder 
https://jsfiddle.net/g93gyt3y/
I don't understand why this doesn't trigger the event.

**Comment by jikkai** [comment]
@atilkan 
https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2
> When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.

**Comment by atilkan** [comment]
@jikkai 
Thanks. I read the spec before, i am aware of this. But in my normal forms enter works that way. I am wondering if element does something to hijack. 
**Edit:** After putting native-type="submit" to form button it works even on forms with more than one inputs. 
These things should be on docs.
