### ISSUE TITLE
[Bug Report] el-form validate not working

### ISSUE THREAD

**Issue by GitHubCloud** [ElemeFE/element#11010]
### Element UI version
2.3.6

### OS/Browsers version
Win10 / Chrome66

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/Encloud/3sdpq766/](https://jsfiddle.net/Encloud/3sdpq766/)

### Steps to reproduce
focus any input on the page and then blur.

### What is Expected?
Should be a error message on the bottom of the input, says it should't be empty.
And the form validate function callback variable 'valid' should be false

### What is actually happening?
It doesn't show any errors, and the 'valid' variable is always true.

On my enviroment, the console printed a warn '[Element Warn][Form]model is required for validate to work!'
Which i look it up, it should only printed when a form doesn't have a model and called validate function, which is not my case.

**Comment by GitHubCloud** [comment]
https://jsfiddle.net/Encloud/dLyL2r3b/2/
here is another sample, they are nearly the same, but this one work just fine.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/3sdpq766/1/
