### ISSUE TITLE
[Feature Request] The collapsed menu's component of el-tooltip-popover need to be to

### ISSUE THREAD

**Issue by YouzhiWang** [ElemeFE/element#11011]
### Existing Component
是

### Component Name
el-menu & el-menu-item

### Description
When el-menu is collapsed, the el-menu-item is replaced by el-tooltip, and the el-tooltip__popper's style is constant.
It's necessary to provide a property, and I can change the el-tooltip__popper's style by this property.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by xiaohubei** [comment]
hey, men , we have met same question, only solve this problem by style overlay, but it was not a smart method, so ,hope a property will be provided to solve this question

**Comment by fujianxiamen** [comment]
我也碰到这样问题，特别是有换肤的情况下，tooltip只要两种背景色，希望能提供对tooltip的样式
