### ISSUE TITLE
[Feature Request] Tabs lazy loading

### ISSUE THREAD

**Issue by lucas-bremond** [ElemeFE/element#11022]
### Existing Component
Yes

### Component Name
Tabs

### Description
Hi,

Is there a way to lazy load tab contents?

Since tabs may contain entire sections of the app, this would decrease load time drastically.
Of course, is it possible to manage this at the contents level, but having a native solution would require less boilerplate.

Thanks!

**Comment by goody9807** [comment]
how to fix it ?

**Comment by mouyong** [comment]
![image](https://user-images.githubusercontent.com/10336437/40194280-6b414772-5a3c-11e8-9f9b-66c6f0e5be31.png)
