### ISSUE TITLE
The message parameter of the [Bug Report] Notification component contains no longer lines when it contains long letters.

### ISSUE THREAD

**Issue by Braised-Cakes** [ElemeFE/element#11026]
### Element UI version
2.3.7

### OS/Browsers version
mac 10.12.6/chrome 66.0.3359.139

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/braisedcakes/3fm7Ljc4/](https://jsfiddle.net/braisedcakes/3fm7Ljc4/)

### Steps to reproduce
直接调用 this.$notify 组件， 且message参数含超长字母

### What is Expected?
满一行则换行

### What is actually happening?
没有换行

**Comment by Leopoldthecoder** [comment]
In different situations, people may need different work breaking behaviors. So you'll need to add your own CSS: https://jsfiddle.net/3fm7Ljc4/1/
