### ISSUE TITLE
[Bug Report] [ssr bug]TypeError: Cannot read property'clientWidth'of undefined

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/element#11037]
### Element UI version
2.3.7

### OS/Browsers version
macos/Chrome/66.0.3359.139 Safari/537.36

### Vue version
2.5.16

### Steps to reproduce
在nuxt下使用

### What is Expected?
支持ssr

### What is actually happening?
ssr下报错TypeError: Cannot read property 'clientWidth' of undefined

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by tanmengmeng** [comment]
![image](https://user-images.githubusercontent.com/20035463/39790460-e26b6a42-5368-11e8-9301-c458a6ff5904.png)
使用nuxt编译element报错

**Comment by marekchen** [comment]
@Leopoldthecoder I have the same problem,you can use the following repo to reproduction this issue.
[](https://github.com/marekchen/pm-web3)

**Comment by yuchonghua** [comment]
@Leopoldthecoder This question already has @marekchen  @tanmengmeng  provided the wrong code and link, now it is necessary to resubmit issues or say you reopen issues

**Comment by marekchen** [comment]
@yuchonghua have fixed this issue #11109
