### ISSUE TITLE
[Feature Request] Add optional value prop for Switch component (and maybe others) for one way binding

### ISSUE THREAD

**Issue by Koc** [ElemeFE/element#11030]
### Existing Component
Yes

### Component Name
Switch

### Description
I'm trying combine Switch component with Vuex like described in official guide for forms https://vuex.vuejs.org/en/forms.html .
But this input hasn't optional value prop http://element.eleme.io/#/en-US/component/switch . As workaround I'm using computed property with `get`/`set`-methods. IMHO

**Comment by wacky6** [comment]
v-model is a syntax sugar for `:value` + `@input`, you can refer to vue documentation.
