### ISSUE TITLE
[Table] 某些情况下动态增删列会出现问题

### ISSUE THREAD

**Issue by perfectyang** [ElemeFE/element#1103]
element-ui 1.0
vue 2.0.5

![image](https://cloud.githubusercontent.com/assets/8724828/20338763/f553966e-ac13-11e6-9bd2-e258f2bcbe3e.png)
![image](https://cloud.githubusercontent.com/assets/8724828/20338796/163f3248-ac14-11e6-814d-ac9a90d39489.png)
表格固定列，当tab切换时，当没有固定消失时，还保留一个
![image](https://cloud.githubusercontent.com/assets/8724828/20338885/83834fa6-ac14-11e6-959f-d293eeafb431.png)

**Comment by furybean** [comment]
Tab 切换会导致第一个 Tab 的 Content 的 display 是 none 吧？想象不到这个 Bug 是怎么出现的 😂

**Comment by perfectyang** [comment]
<el-table-column inline-template align="center" label="操作" width="220" v-if="tabIndex == '2'"  fixed="right">
           <div class="operate-btn">
             <el-button class="o-btn" size="small" type="primary" @click.native="confirmGood(row)">确认收货</el-button>
           </div>
 </el-table-column>

v-if="tabIndex == '2'"   关键点在于这里，当tab切 换到其他条件时，此时表格中没有固定列时，还是会保留这个固定列的外层div

**Comment by furybean** [comment]
#1182 修复了此问题。
