### ISSUE TITLE
ElInput 控件问题

### ISSUE THREAD

**Issue by sstun** [ElemeFE/element#11046]
handleInput(event) {
        const value = event.target.value;
        this.$emit('input', value);
        this.setCurrentValue(value);
      },

**这个地方再 emit之后重新设置 setCurrentValue 会导致继承的 控件使用 input事件处理事务的时候无法取的效果，例如我里面判断 输入不合法重新设置 value 后无效，我认为反过来应该比较合理
handleInput(event) {
        const value = event.target.value;
        this.setCurrentValue(value);
        this.$emit('input', value);        
      },
**

**Comment by bundery** [comment]
+1
