### ISSUE TITLE
[Bug Report] Options are not scrolling with keyboard down key when option-group is given

### ISSUE THREAD

**Issue by akki-jat** [ElemeFE/element#11047]
### Element UI version
2.3.7

### OS/Browsers version
Windows 7 / Chrome 66.0.3359.139

### Vue version
2.5.11

### Reproduction Link
[https://codepen.io/akki-jat/pen/odwyww](https://codepen.io/akki-jat/pen/odwyww)

### Steps to reproduce
Iterate through list using keyboard down key

### What is Expected?
Option list should scroll

### What is actually happening?
Option list is not scrolling

**Comment by akki-jat** [comment]
@Leopoldthecoder It is not working

**Comment by Leopoldthecoder** [comment]
Wait for our next release.

**Comment by akki-jat** [comment]
@Leopoldthecoder thanks man.
