### ISSUE TITLE
Why is there no custom form-item in [Feature Request] document?

### ISSUE THREAD

**Issue by shhhplus** [ElemeFE/element#11056]
### Existing Component
是

### Component Name
form

### Description
某些场景下，form-item里有多个输入框（input、select、checkbox等都有可能），整个form-item的值是对象或者数组。此时可能需要自定义form-item，不知道官方文档里没有提到这个概念。

**Comment by Leopoldthecoder** [comment]
可参考 http://element-cn.eleme.io/#/zh-CN/component/form#dong-tai-zeng-jian-biao-dan-xiang

**Comment by shhhplus** [comment]
@Leopoldthecoder 
场景不太一样，动态表单里form-item内部还是单个input，这些都没问题。我描述的场景是form-item里有多个input。
ant design里有自定义表单控件的概念。可参考下demo [http://ant.design/components/form-cn/#components-form-demo-customized-form-controls](http://ant.design/components/form-cn/#components-form-demo-customized-form-controls)

**Comment by Leopoldthecoder** [comment]
如果需要校验的话，那么每个 FormItem 里只能有一个 input

**Comment by shhhplus** [comment]
ant design提供了自定义表单控件的概念，只要保证form-item有value和onChange这两个接口，就能插拔到form'框架'里。希望element后续可以考虑支持。辛苦了！
