### ISSUE TITLE
[Bug Report] el-upload components need to be clicked two times before chrome mobile terminal debugging to open.

### ISSUE THREAD

**Issue by feng9217** [ElemeFE/element#11055]
### Element UI version
2.3.7

### OS/Browsers version
chrome版本 66.0.3359.139（正式版本）（64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/feng9217/issueForMsite/blob/master/src/pages/usercenter/editUserInfo.vue](https://github.com/feng9217/issueForMsite/blob/master/src/pages/usercenter/editUserInfo.vue)

### Steps to reproduce
vux模板搭建的项目
将项目直接提取出来放到了Github上 可以直接 npm install --> npm run dev
页面路由地址为 /home
在页面底部提交上 大的圈是 el-upload 小的是input写的

### What is Expected?
单次点击后可唤起移动端 选择图片或拍照 的功能

### What is actually happening?
需要双击才能唤起

**Comment by Leopoldthecoder** [comment]
Element is designed for desktops. It may not be compatible with mobile devices.
