### ISSUE TITLE
[Feature Request] Be able to drag and drop table rows

### ISSUE THREAD

**Issue by sergey-zhidkov** [ElemeFE/element#11057]
### Existing Component
Yes

### Component Name
Table

### Description
Would like to have an ability to drag and drop rows inside table body (probably, rows inside table header also). Similar to ElTree drag and drop support. Ready to implement but not sure you have this feature in plans and will accept changes.

**Comment by Leopoldthecoder** [comment]
See https://jsfiddle.net/gozhg07a/84/ and https://github.com/ElemeFE/element/issues/3543
