### ISSUE TITLE
[Feature Request] [HELP] Get information from row table using @row-click

### ISSUE THREAD

**Issue by idindrakusuma** [ElemeFE/element#11050]
### Existing Component
Yes

### Component Name
Table

### Description
I have tried to get row data from table using @row-click. I have an error, data always return 'undefined'.

i have read the doc and issue from https://github.com/ElemeFE/element/issues/10827, but still error..

can you help me?

this is my sample code

```
<el-table class="table-striped" highlight-current-row @row-click="handleClick(tableData.indexOf(row))"
                  :data="tableData" height="320" style="width: 100%" border>
```

and my method..

      handleClick (data) {
        alert(`you was clicked ${data.unitPrice}`);
      },

**Comment by Leopoldthecoder** [comment]
`@row-click="handleClick"`

**Comment by idindrakusuma** [comment]
@Leopoldthecoder it's work for access function. But variable still undefined.
     ```
 handleClick (data) {
        alert(`you was clicked ${data.unitPrice}`);
      },
```

> you was clicked undefined

Can you write the example code for my methods? not just in el-table. thank you :)

**Comment by Leopoldthecoder** [comment]
Actually if you're running into troubles, you're the one who should write a demo.
