### ISSUE TITLE
[Feature Request] DateRange:  Allow the right picker to be the min / default value. 

### ISSUE THREAD

**Issue by smitt04** [ElemeFE/element#11052]
### Existing Component
Yes

### Component Name
date-picker

### Description
In my use case I want the user to select a date range in the past. This is used for analytics so you can't select a future date.  It would be nice if the min / max / default could display on the right picker instead of left.

**Comment by wacky6** [comment]
Not sure what you are trying to do.

If you only want to let right panel show today, set default-value to `current date - 1 month`.

**Comment by wacky6** [comment]
I see.

Currently you might need to wrap the date-picker, then fiddle with panels' internal states a little bit `$refs.datePicker.picker.{left, right}Date`.

We might consider support your use case after a consensus on API / usage is finalized. @Leopoldthecoder
