### ISSUE TITLE
[Feature Request] el-scrollbar has no description in the documentation

### ISSUE THREAD

**Issue by AndrewProts** [ElemeFE/element#11068]
### Existing Component
Yes

### Component Name
scrollbar

### Description
How can i use scroll bar? I can`t find any information about this.

**Comment by Leopoldthecoder** [comment]
Scrollbar is an internal component just for other Element components, and is subject to changes in the future, so it's not advised for users to use it in their projects. If you must, you can refer to the source code of the official website.
