### ISSUE TITLE
The [Bug Report] tree component invoked the setCurrentKey method without triggering current-change events.

### ISSUE THREAD

**Issue by hyn0000hyn** [ElemeFE/element#11065]
### Element UI version
2.3.7

### OS/Browsers version
chrome

### Vue version
2.1.8

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
tree组件调用setCurrentKey方法时没有触发current-change事件

### What is Expected?
tree组件调用setCurrentKey方法时触发current-change事件

### What is actually happening?
tree组件调用setCurrentKey方法时触发current-change事件

**Comment by Leopoldthecoder** [comment]
`current-change` only triggers on user input, i.e. the user changes the current tree node through the interface. It'll not trigger when you programmatically change the current node, e.g. using `setCurrentKey`.
