### ISSUE TITLE
[Bug Report] DateTimePicker wrong position when `type` property is changed

### ISSUE THREAD

**Issue by rwparris2** [ElemeFE/element#11072]
### Element UI version
2.3.7

### OS/Browsers version
osx chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/8qg3abrp/2/](https://jsfiddle.net/8qg3abrp/2/)

### Steps to reproduce
Use an ElDatePicker component with the `type` property bound to a reactive property. 
Initialize the `type` as `date` or any non-range property.
Open the picker and pick  a date.
Change the `type` property from `date` to `daterange`
Open the picker again.

### What is Expected?
Picker should appear in same position (i.e. directly under the date input) after modifying the `type` property.

### What is actually happening?
Position of picker is top-left of window instead of directly under the date input.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/8qg3abrp/3/

**Comment by rwparris2** [comment]
Thanks!

Is this documented anywhere? How should I know that key does this?
