### ISSUE TITLE
Can [Feature Request] el-checkbox add readonly attribute?

### ISSUE THREAD

**Issue by hegoku** [ElemeFE/element#11073]
### Existing Component
Yes

### Component Name
el-checkbox

### Description
el-checkbox只有disabled属性却没有readonly，可以加上吗

**Comment by Leopoldthecoder** [comment]
会考虑的，移到 Product Backlog 里了。https://github.com/ElemeFE/element/projects/8#card-9625263

**Comment by luoyifanff** [comment]
> 会考虑的，移到 Product Backlog 里了。https://github.com/ElemeFE/element/projects/8#card-9625263

why not？过去四年了，忘记了吗。还有radio
