### ISSUE TITLE
When [Bug Report] el-dialog is higher than one screen, scroll to the bottom and close dialog. Once again, dialog is not reset to the top.

### ISSUE THREAD

**Issue by jyouli** [ElemeFE/element#11085]
### Element UI version
2.3.7

### OS/Browsers version
chrome 66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1920/](https://jsfiddle.net/mmx38qxw/1920/)

### Steps to reproduce
点击“点击打开dialog”按钮 --》
滚动弹窗到底部 --》
点击“关闭”按钮 --》
再次点击“点击打开dialog”按钮 --》
dialog弹窗仍然停留在弹窗底部位置

### What is Expected?
每次dialog被打开之后，弹窗从顶部开始展示信息，
或者希望el-dialog添加一个 “dialog出现时是否复位到顶部” 属性，灵活满足各种需求

### What is actually happening?
dialog弹窗仍然停留在弹窗底部位置

**Comment by jyouli** [comment]
试过scrollTop=0控制el-dialog滚动到顶部，但不起作用

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/1921/

**Comment by jyouli** [comment]
@Leopoldthecoder thank you , 不过还是希望在el-dialog上能添加这个属性，方便大家使用😁

**Comment by MysteryAngle** [comment]
这个实际上涉及到了DOM操作，对于怎么在VUE中操作这种DOM的属性还是没有一种官方的用法吧。不过这个解决方法最直接简单。

**Comment by MysteryAngle** [comment]
这个实际上涉及到了DOM操作，对于怎么在VUE中操作这种DOM的属性还是没有一种官方的用法吧。不过这个解决方法最直接简单。
