### ISSUE TITLE
[Bug Report] [el-tree] no dragged nodes can be dragged.

### ISSUE THREAD

**Issue by SmallBlanckPig** [ElemeFE/element#11081]
### Element UI version
2.3.7

### OS/Browsers version
win7 / 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[Http://element.eleme.io/#/zh-CN/component/tree](Http://element.eleme.io/#/zh-CN/component/tree)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/tree 
任意一个例子都能重新。
点击一个节点，长按并拖动，若第一次未重现，可以多尝试几遍（除开disabled为true的节点）

### What is Expected?
未设置draggable为true不允许拖动

### What is actually happening?
未设置未设置draggable为true仍然可以拖动

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/39809171-a4b01be4-53b3-11e8-9151-4dfba6574af9.gif)

无法重现。

**Comment by SmallBlanckPig** [comment]
![el-tree](https://user-images.githubusercontent.com/6890343/39850573-c12a0d16-5444-11e8-91df-eb995484ea07.gif)
