### ISSUE TITLE
[Feature Request] popup / modal / dialog - `lockScroll` feature add class instead of modifying `body.style` directly

### ISSUE THREAD

**Issue by hartmut-co-uk** [ElemeFE/element#11086]
### Existing Component
Yes

### Component Name
Dialog (utils/popup), ..?

### Description
Hi everyone, 

the `lockScroll` modifies `body.style` directly, e.g. setting `document.body.style.paddingRight = ..`
(src/utils/popup/index.js)

This is all working just fine - while I run into an issue (with fixed header) where I've had to add similar stying while modal open...transitioned close - to an object in my DOM. If the logic would add a class, e.g. `.modal-active` to the `body` instead of setting plain style this would allow adding custom css for my object in question. 
Could this be added / refactored to use a class over plain style?

Hope my explanation makes sense, if not pls let me know, could add references to e.g. what bootstrap / twitter are doing in a similar fashion.. :-)

Many thanks
Hartmut

**Comment by Leopoldthecoder** [comment]
#11114

**Comment by hartmut-co-uk** [comment]
thanks, will have a look once released!
