### ISSUE TITLE
[Feature Request] Mobile UI handling?

### ISSUE THREAD

**Issue by liuzhen2008** [ElemeFE/element#11089]
### Existing Component
No

### Component Name
Mobile UI

### Description
How should people deal with mobile UI?

Specifically, regarding to font sizes. What strategy should people use to deal with mobile font sizes? does element ui has built in support in scaling font sizes on mobile devices?

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. Please avoid using it on mobile devices.
