### ISSUE TITLE
When [Bug Report] el-select component has scrollbars, UI displays exceptions in dialog.

### ISSUE THREAD

**Issue by zhuss** [ElemeFE/element#11087]
### Element UI version
2.3.7

### OS/Browsers version
mac 10.11.6/ chrome 版本 66.0.3359.139（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1924/](https://jsfiddle.net/mmx38qxw/1924/)

### Steps to reproduce
点击按钮 显示dialog即可看到select组件的小箭头没有了,ui中出现一条斜线。

### What is Expected?
正常显示下拉选组件

### What is actually happening?
下拉选组件显示有异常

**Comment by zhuss** [comment]
似乎el-select只要有滚动条 ui都是显示异常的，这个问题在官网组件就有再现。[http://element-cn.eleme.io/2.1/#/zh-CN/component/select](http://element-cn.eleme.io/2.1/#/zh-CN/component/select)

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/39849923-5868d1ca-5441-11e8-8094-ae4e83d1bba7.gif)

未能重现。

**Comment by zhuss** [comment]
录制了视频这是地址，你有时间点开看下哈。[http://video.yingtu.co/20180510211348365.mp4](http://video.yingtu.co/20180510211348365.mp4)
