### ISSUE TITLE
[Feature Request] Any solution to highlight a\some date-range(s) but no affect to any action?

### ISSUE THREAD

**Issue by ylvict** [ElemeFE/element#11080]
### Existing Component
Yes

### Component Name
datepicker

### Description
The scenario is we need mark some date(s) highlights for user reference (such as mark up public holidays), but we don`t want to make any changes for action and behaviour to the calendar.

Such as Jan-1st to Jan-3rd is a public holiday, we wanna to display these dates as red background, but only presenting update, it still allow the user to select and when user select the date, all other actions follow what currently implemented.

Thanks for any suggestions.

**Comment by Leopoldthecoder** [comment]
没有提供相关支持。建议尝试操作 DOM 并修改 CSS。

**Comment by genffy** [comment]
https://github.com/charliekassel/vuejs-datepicker
