### ISSUE TITLE
[Bug Report] Select not working properly (safari on ios)

### ISSUE THREAD

**Issue by alex-schmidigital** [ElemeFE/element#11083]
### Element UI version
2.3.7

### OS/Browsers version
safari ios

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://codepen.io/anon/pen/jxZyMp?editors=1111](https://codepen.io/anon/pen/jxZyMp?editors=1111)

### Steps to reproduce
Click into the select field
Click outside

### What is Expected?
We do not want the focus indicator to show if it is not filterable
On click outside the select we want the dropdown to close

### What is actually happening?
Focus indicator shows for non filterable inputs
Outside click will not close dropdown reliably

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop pages. Please don't use it on mobile devices.

**Comment by pmochine** [comment]
wtf do you think I'm going to use another package just for mobile??

sucks that it won't close.  Actually so simple you just need to update utils/clickoutside.js
