### ISSUE TITLE
[Bug Report] MessageBox default insert to body, causing MessageBox to disappear when switching routes.

### ISSUE THREAD

**Issue by ReAlign** [ElemeFE/element#11099]
### Element UI version
2.3.7

### OS/Browsers version
macOS10.13.4 / chrome66.0

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.js#L112](https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.js#L112)

### Steps to reproduce
https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.js#L112

### What is Expected?
能提供 MessageBox 插入位置的选项

### What is actually happening?
默认是插入到body上的

**Comment by Leopoldthecoder** [comment]
You can close it in the `beforeDestroy` hook: https://jsfiddle.net/emr8s9n1/
