### ISSUE TITLE
[Bug Report] time-range-picker emit change event while blur

### ISSUE THREAD

**Issue by tttuuu123** [ElemeFE/element#11090]
### Element UI version
2.3.7

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
1 focus time-range-picker component
2 click out side component

### What is Expected?
component unvisible only

### What is actually happening?
component unvisible and emit change event

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/11017

**Comment by tttuuu123** [comment]
@Leopoldthecoder however, if focus time-range-picker component first, then change time, click out side. component unvisible and emit change event. the issua you provide only refer to compare value equal, but doesn't considering just click out side without click confirm button.
如果改变了组件的值，再点击组件外部，组件隐藏并且触发了change事件，源码里仅仅作了新旧值的比较，和点击外部隐藏这个组件的场景是有区别的。今天早上我重新install了的element-ui 2.3.7i，无论我做什么操作，包括取消，都会触发下载。

**Comment by Leopoldthecoder** [comment]
仅仅修复了，还没有发布。

**Comment by tttuuu123** [comment]
@Leopoldthecoder 非常感谢，element-ui真的不错，还是想多问一句，修复的是我在2.3.3版本上提到的改变time值，点击外部隐藏组件触发change事件么，而不仅仅是2.3.7版本上无论做什么操作，都会触发change。
有几个小建议，都是2.3.3的版本下的。
1、table组件改变current-page会触发current-change事件，一般查询表格会单独写一个方法，某些场景下，比如我要重置current-page为第一页，可能我个人倾向于改变current-page为1，再去调用查询表格方法。而不是仅仅改变current-page。
2、form表单没有标识位标记表单的校验状态。
3、调用挂在Vue原型链上的全局方法 $loading是返回一个单例，并且调用了这个方法就开启了全局loading效果，如果能有个和close()对应的open()方法可能会更好，通过open()方法去开启loading效果。
