### ISSUE TITLE
Can [Feature Request] el-table provide a sequential adjustment method for columns?

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#11093]
### Existing Component
是

### Component Name
el-table

### Description
```html
<el-table ref="table" :data="dataList">
    <el-table-column v-for="item in columnList" :key="item.name" :label="item.name" :prop="item.name"></el-table-column>
</el-table>
```
通过以上的方法进行表格动态列渲染,但是我对columnList顺序进行调整后,table的列并不会调整顺序, 能否提供一个方法,根据调整后的列重新渲染

https://codepen.io/zsedcbm/pen/dedxjm

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/xcnowf5q/
