### ISSUE TITLE
[Feature Request] uses el-table plus V-for to make one more tab of push line. Why not add a line?

### ISSUE THREAD

**Issue by 846553673** [ElemeFE/element#11106]
### Existing Component
是

### Component Name
el-table

### Description
使用el-table加v-for进行push一行时直接多了一个tab！为什么不是增加一行的？

**Comment by 846553673** [comment]
Existing Component

是
Component Name

el-table
Description
我是使用表做增加一行，里面有输入框和选择器。
![default](https://user-images.githubusercontent.com/11608061/39860593-71e3759a-5470-11e8-99cc-5c3eb710e2c0.png)

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by 846553673** [comment]
Existing Component

是
Component Name

el-table
Description
我是使用表做增加一行，里面有输入框和选择器。
选择器不使用v-model绑定选择了没有效果，很多都需要v-mode绑定。但新增时不确认
