### ISSUE TITLE
[Bug Report] Table width won't resize in flex layout

### ISSUE THREAD

**Issue by wiwimouse** [ElemeFE/element#11102]
### Element UI version
2.3.7

### OS/Browsers version
Chrome 66

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/wiwimouse/uuavwm9e/](https://jsfiddle.net/wiwimouse/uuavwm9e/)

### Steps to reproduce
Just click button to toggle side block

### What is Expected?
table should trigger resizing when toggle

### What is actually happening?
resizing only trigger when hiding side block

**Comment by Leopoldthecoder** [comment]
Add `overflow: hidden` on `.main`: https://jsfiddle.net/uuavwm9e/1/

**Comment by wiwimouse** [comment]
It's work. Thanks!

**Comment by FE-xiaoJiang** [comment]
nice
