### ISSUE TITLE
The closing and cancellation of the pop-up module

### ISSUE THREAD

**Issue by hungenqianqiu** [ElemeFE/element#11104]
### Element UI version
2.3.7

### OS/Browsers version
各种版本

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/8cbwd0nm/2/](https://jsfiddle.net/8cbwd0nm/2/)

### Steps to reproduce
调用实例的$confirm方法，会出现一个弹窗；点击弹窗右上角的叉号，会触发cancel事件。

### What is Expected?
点击右上角叉号，仅仅需要关闭弹窗即可。

这可能不算一个bug，而是组件涉及理念问题。的确，大多数情况下，点击关闭和点击取消的行为是一致的；但是实际中还有大量的情景，希望对这两种行为加以区别。比如，弹窗后有“审核通过”、“驳回请求”这样一个二选一的场景，审核人员可能一时拿不定主义，想关闭弹窗，先思考一会再做决定，但是这个时候，点击关闭会触发“驳回请求”。

作为一个广泛使用的UI框架，在弹窗这样的基础组件中，还是希望能给与开发者更大的灵活度。希望官方可以考虑一下这个功能。

### What is actually happening?
不仅关闭的弹窗，还触发了取消事件，和点击取消按钮行为重叠

**Comment by Leopoldthecoder** [comment]
This is by design. Closing the confirm means to cancel the operation.

**Comment by hungenqianqiu** [comment]
@Leopoldthecoder 我知道这是by design，但是能不能不要这么简单粗暴，连个讨论和对话的机会也不给？ 

的确，大多数情况下，点击关闭和点击取消的行为是一致的；但是实际中还有大量的情景，希望对这两种行为加以区别。比如，弹窗后有“审核通过”、“驳回请求”这样一个二选一的场景，审核人员可能一时拿不定主义，想关闭弹窗，先思考一会再做决定，但是这个时候，点击关闭会触发“驳回请求”。

作为一个广泛使用的UI框架，在弹窗这样的基础组件中，还是希望能给与开发者更大的灵活度。希望官方可以考虑一下这个功能。

**Comment by Leopoldthecoder** [comment]
confirm 的适用场景是「是否执行某操作」，而不是「执行 A 操作还是 B 操作」。
