### ISSUE TITLE
[Bug Report] Form validator doesn't work properly for array of fields

### ISSUE THREAD

**Issue by AshwinTayson** [ElemeFE/element#11112]
### Element UI version
2.3.7

### OS/Browsers version
Ubuntu 16.06 / Chrome 66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/gk47153m/](https://jsfiddle.net/gk47153m/)

### Steps to reproduce
1. Have an array of form-items formed using v-for.

2. Pass validator to the validation rule

3. Fill all the fields and remove value from only one text box

### What is Expected?
If one field is error then show error for only that field

### What is actually happening?
If one field is error then all fields throws error even if they are right

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gk47153m/2/
