### ISSUE TITLE
[Bug Report] response is slow when a large number of el-autocomplete of

### ISSUE THREAD

**Issue by zhuzidian** [ElemeFE/element#11119]
### Element UI version
2.2.2

### OS/Browsers version
win7 / chrome Version 66.0.3359.139 (Official Build) (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/zhuzidian/8vpp9phe/](https://jsfiddle.net/zhuzidian/8vpp9phe/)

### Steps to reproduce
点add按钮

### What is Expected?
用el-input的时候就响应很快

### What is actually happening?
  点add按钮后有明显的卡顿。
  点add前滚动条可以正常滚动。点add后，拖动滚动条也会有明显的卡顿。

**Comment by Leopoldthecoder** [comment]
You need to `key` the `<tr>`: https://jsfiddle.net/8vpp9phe/7/ .

**Comment by zhuzidian** [comment]
sorry, i update the link https://jsfiddle.net/zhuzidian/8vpp9phe/

What is actually happening?
when i use <template slot-scope="{item}"> in el-autocomplete and click add button, 
it is work slowly
