### ISSUE TITLE
When using el-date-picker, [Bug Report] uses state control'type'or'v-if' to switch the date, and the location of el-picker-panel is wrong.

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#11110]
### Element UI version
2.3.7

### OS/Browsers version
win10 / chrome 66.0.3359.139

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/qacftLff/1/](https://jsfiddle.net/qacftLff/1/)

### Steps to reproduce
第一次点击 el-date-picker 时 el-picker-panel 出现位置正常（el-date-picker下方），用 select 选择 来控制  v-if  或 type  变动，再点击 el-date-picker 时 el-picker-panel 出现位置错误（页面左上方）

### What is Expected?
第一次点击 el-date-picker 时 el-picker-panel 出现位置正常（el-date-picker下方），用 select 选择 来控制  v-if  或 type  变动，再点击 el-date-picker 时 el-picker-panel 出现位置正常（el-date-picker下方）

### What is actually happening?
第一次点击 el-date-picker 时 el-picker-panel 出现位置正常（el-date-picker下方），用 select 选择 来控制  v-if  或 type  变动，再点击 el-date-picker 时 el-picker-panel 出现位置错误（页面左上方）

**Comment by Leopoldthecoder** [comment]
You need to `key` the `<el-date-picker>`: https://jsfiddle.net/qacftLff/2/
