### ISSUE TITLE
[Feature Request] Tree: append root node

### ISSUE THREAD

**Issue by TMantas** [ElemeFE/element#11118]
### Existing Component
Yes

### Component Name
Tree

### Description
There should be easy way to append root (top level) node. Maybe reuse `append` method and if second parameter (`parentNode`) is empty - then append to top level.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by TMantas** [comment]
Oh. I thought this should be easy to implement.

Then maybe at least there should be a method to reload the tree?

**Comment by ahuang** [comment]
i solved this by add tree level 0 to root:
```
this.$refs.myTree.root.data = this.level0Data; //  this.level0Data is  data from node level 0 
this.$refs.myTree.insertBefore({ id:10, name: `newnode`}, 1); //  1 is mouted node data id. 
```

**Comment by fyeeme** [comment]
@ahuang  it works for me ,thanks
