### ISSUE TITLE
[Feature Request] pagination why not emit ('update:pageSize') when user change it it change

### ISSUE THREAD

**Issue by WilkinWendy** [ElemeFE/element#11117]
### Existing Component
是

### Component Name
pagination

### Description
pagination why not emit('update:pageSize') when user change it using select.

in this case ,I can ensure synchorous by the suffix '.sync' like current-num.sync, page-size.sync

**Comment by Leopoldthecoder** [comment]
收录进 Product Backlog：https://github.com/ElemeFE/element/projects/8#card-9686676 ，后期会支持。

**Comment by kid1412621** [comment]
> 收录进 Product Backlog：https://github.com/ElemeFE/element/projects/8#card-9686676 ，后期会支持。

所以在哪个版本支持了呢?
