### ISSUE TITLE
如何将表单与第三方验证器结合？例如VeeValidator

### ISSUE THREAD

**Issue by chenkby** [ElemeFE/element#1111]
找到个issue https://github.com/ElemeFE/element/issues/898
不过发的链接已经挂了..

eui version:1.0.1

**Comment by QingWei-Li** [comment]
表单已经内置了校验功能，如果需要和 vue-validator 请到它的相关社区咨询，所有输入组件都是支持 `v-model` 的，那么可以直接使用 vue-validator，用法请看它的文档。这不属于 Element 的 issue
