### ISSUE TITLE
[Bug Report] Get this error in console "ReferenceError: scope is not defined" when use <el-table>

### ISSUE THREAD

**Issue by caifagithub** [ElemeFE/element#11129]
### Element UI version
2.3.8

### OS/Browsers version
Windows / Chrome 66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/usertouch/mvcjxyg5/](https://jsfiddle.net/usertouch/mvcjxyg5/)

### Steps to reproduce
I use vue.js   element ui with ThinkPHP 3.2
I don't use webpack, just pure html and js code

### What is Expected?
I want to use slot-scope attribute to use methods inside the el-table tag.

### What is actually happening?
When I try to use slot-scope in el-table it response me an error.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
