### ISSUE TITLE
[Feature Request] How to make children(show data in childern object) in tree if we are rendering with lazy loading.

### ISSUE THREAD

**Issue by Enigma10** [ElemeFE/element#11126]
### Existing Component
Yes

### Component Name
Tree

### Description
Hello,
I am loading tree-data with lazy/(load-data) method which calling to an additional API to render data which comes under it. I am doing this because we are having 6 level data and product is more than 200000. I need children-parents relationship so i can filter data.

**Comment by Leopoldthecoder** [comment]
I'm not sure what the problem is. Could you elaborate on this? A demo would really help.

**Comment by Enigma10** [comment]
Hi,

I want to set one node to partially selected but since it's child data is loading dynamically. it is not possible right now. Shouldn't we have attribute as feature? If our children is loading partially. :question:
