### ISSUE TITLE
[Bug Report] upload file component: the role of on-preview method is inconsistent with the document.

### ISSUE THREAD

**Issue by ykl124** [ElemeFE/element#11122]
### Element UI version
2.3.7

### OS/Browsers version
Windows 7

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
用vue-cli本地构建一个新项目，
制作一个简单的上传文件demo，
需求：上传文件后拿到服务器端返回的数据，
根据文档：http://element.eleme.io/#/zh-CN/component/upload
on-preview的功能是：
点击已上传的文件链接时的钩子, 可以通过 file.response 拿到服务端返回数据
但是实际上执行的时候发现， :on-preview="handlePreview"这个方法根本没有被执行

如果这是个bug，请你们修复
如果这个方法是别的作用，也请你们更新文档说明
谢谢。

PS：最后我用 on-success解决了问题。

### What is Expected?
请你们判断以上问题是bug还是文档说明有误，
如果是bug，请修复bug
如果是文档说明错误，请更新文档。

### What is actually happening?
请你们判断以上问题是bug还是文档说明有误，
如果是bug，请修复bug
如果是文档说明错误，请更新文档。

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/39919156-5b0ea56c-5545-11e8-9fdd-679003b7bdf3.gif)

文档有误，应该是 `file.url`。我改一下。

**Comment by gitspringcould** [comment]
我也遇到了这个问题，后面解决了吗
