### ISSUE TITLE
[Bug Report] upload manually Uploaded

### ISSUE THREAD

**Issue by asd8855** [ElemeFE/element#11123]
### Element UI version
2.3.7

### OS/Browsers version
chrome 66

### Vue version
2.5.13

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
upload 手动上传；
第一次可以触发到上传动作；这时server报错，用户手动修改文件并保存后，文件名和路径均未改变。这时调用this.$refs.upload.submit();  没有触发到上传事件

### What is Expected?
可以再次上传

### What is actually happening?
再次上传未触发上传事件

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by Zeus-Iqd** [comment]
我也遇到了这个问题
