### ISSUE TITLE
[Feature Request] Make in el-button component property to render tag <a>

### ISSUE THREAD

**Issue by rootboard** [ElemeFE/element#11125]
### Existing Component
Yes

### Component Name
el-button

### Description
Sometimes is needed to make `<el-button>` like an `<a>` tag, not `<button>`

**Comment by Leopoldthecoder** [comment]
It'll always render a `<button>` since it is called El**Button**. If you must, you can use ElButton's class on an `<a>` element: https://jsfiddle.net/xbotxmnh/ .
