### ISSUE TITLE
[Bug Report] Transfer component

### ISSUE THREAD

**Issue by susdud** [ElemeFE/element#11139]
### Element UI version
2.3.7

### OS/Browsers version
Mac el capitan / chrome 66

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/susdud/mmx38qxw/1934/](https://jsfiddle.net/susdud/mmx38qxw/1934/)

### Steps to reproduce
No particular steps. No matter how you do it, the issue will be obvious

### What is Expected?
'No Data' is to be displayed when model array is empty

### What is actually happening?
its displaying something in chinese

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/1935/
http://element.eleme.io/#/en-US/component/i18n#import-via-cdn
