### ISSUE TITLE
多张图片不能一次选择，浏览器不兼容

### ISSUE THREAD

**Issue by strongant** [ElemeFE/element#1113]
进行多张图片上传时，如果使用QQ浏览器则可以一次选择多张图片进行上传，如果选择手机自带的浏览器进行选择上传时，只能一张一站进行选择？这个是不是没办法解决？

**Comment by furybean** [comment]
这个是浏览器的限制。

**Comment by strongant** [comment]
好的，谢谢

**Comment by 598220654** [comment]
@strongant  
![image](https://cloud.githubusercontent.com/assets/15324717/21756126/db8f20f4-d657-11e6-91a3-15ac6d20b074.png)
