### ISSUE TITLE
[Bug Report] Model value does not update until 'space' is pressed on Android

### ISSUE THREAD

**Issue by vc-nick** [ElemeFE/element#11132]
### Element UI version
2.3.6

### OS/Browsers version
Android 6.0.1 / Chrome 66

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/e731ktyd/](https://jsfiddle.net/e731ktyd/)

### Steps to reproduce
On android, type into the input box

### What is Expected?
The value in the input should display below it.

### What is actually happening?
The input value is not updating until 'space' is pressed on android. On desktop the value updates as expected.

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

**Comment by vc-nick** [comment]
Could you please elaborate more on this? If this is the case, why include a break point variable in the scss for phone sized screens and component properties that help with page design on smaller screens?
