### ISSUE TITLE
The default values of remote select after version 2.2.1 cannot be rendered normally.

### ISSUE THREAD

**Issue by penggy** [ElemeFE/element#11136]
### Element UI version
2.3.8

### OS/Browsers version
Windows10 Chrome66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
                <el-select v-model="form.vods" value-key="id" automatic-dropdown multiple filterable remote :remote-method="queryVods" placeholder="请选择" style="width: 100%;" v-show="form.type == 'vod'">
                    <el-option v-for="item of vods" :key="item.id" :label="item.name" :value="{id: item.id, name: item.name}">
                    </el-option>
                </el-select>

### What is Expected?
默认值正常渲染

### What is actually happening?
默认值不能正常渲染

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
