### ISSUE TITLE
Can [Feature Request] el-tooltip show the effect of tooltip by judging the value accords with the conditions?

### ISSUE THREAD

**Issue by wuzechuan** [ElemeFE/element#11142]
### Existing Component
是

### Component Name
el-tooltip

### Description
我通过for循环生成一排el-tag，但是在这些el-tag中，个别tag它们特定字段有值，比如说address这个字段。希望address有值的时候el-tooltip的disable为true，address没值的时候disable为false。请问如何实现？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
