### ISSUE TITLE
[Bug Report] form checking problem

### ISSUE THREAD

**Issue by JcRaymee** [ElemeFE/element#11140]
### Element UI version
2.0.8

### OS/Browsers version
win10

### Vue version
2.5.10

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
1.创建表单,添加两个校验域(如:userName, 和address)
2.address根据一个动态变量进行渲染,v-if='expression'
3.当expression为真得时候this.$refs[formName].validate不对address进行校验

### What is Expected?
使用v-if动态渲染的组件的也能被form进行校验

### What is actually happening?
使用v-if动态渲染的组件的没有被form进行校验

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
