### ISSUE TITLE
[Bug Report] input does not support setSelectionRange method.

### ISSUE THREAD

**Issue by songzeng2016** [ElemeFE/element#11145]
### Element UI version
2.3.8

### OS/Browsers version
Chrome 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/SongZeng/mmx38qxw/1937/](https://jsfiddle.net/SongZeng/mmx38qxw/1937/)

### Steps to reproduce
对 input 使用 setSelectionRange  方法无效，提示 this.$refs.input.setSelectionRange is not a function

### What is Expected?
希望 input 支持 setSelectionRange   方法

### What is actually happening?
this.$refs.input.setSelectionRange is not a function

**Comment by Leopoldthecoder** [comment]
需要在原生 input 元素上执行：https://jsfiddle.net/mmx38qxw/1938/

**Comment by songzeng2016** [comment]
OK，希望能在文档里添加上说明

**Comment by DrJaxx** [comment]
> 需要在原生 input 元素上执行：https://jsfiddle.net/mmx38qxw/1938/

I don't understand the language but the answer was in the fiddle, thank you !
