### ISSUE TITLE
[Bug Report] https://jsfiddle.net/kerwinddd/vu9nq5bh/

### ISSUE THREAD

**Issue by kerwin1** [ElemeFE/element#11141]
### Element UI version
2.3.8

### OS/Browsers version
macOS13.1.3

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/kerwinddd/vu9nq5bh/](https://jsfiddle.net/kerwinddd/vu9nq5bh/)

### Steps to reproduce
抱歉，无法直接重现。我完成的是vuex记录页码跳转的功能。大概是，从列表页面中选择第二页，点击任一栏，跳转路由到详情页面。返回后，列表页面仍然是第二页。vuex中的值显示正确为2，列表数据也是第二页的数据。但是分页的组件active始终选中的是第一页。

### What is Expected?
从一级路由的第二页，进入到二级路由。返回到一级路由，仍然是第二页

### What is actually happening?
数据渲染和vuex中的值都正确，但是active选中的始终是第一页。

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly. You can minimize your project and upload it to GitHub.
