### ISSUE TITLE
[Feature Request] request el-transfer dynamic disabled

### ISSUE THREAD

**Issue by luozhihua** [ElemeFE/element#11154]
### Existing Component
Yes

### Component Name
el-transfer

### Description
I need a dynamic `disabled` property to limit left column must have one item don't be move to right column.

https://jsfiddle.net/Colin_Luo/k73h27r7/2/

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/40033964-6426a7cc-582d-11e8-8697-7083ee3beda5.png)

disabled 拼错了：https://jsfiddle.net/k73h27r7/3/
