### ISSUE TITLE
[Bug Report] el-table-column multiple selection columns use V-IF to render rendering problems.

### ISSUE THREAD

**Issue by zz1103316200** [ElemeFE/element#11153]
### Element UI version
2.3.8

### OS/Browsers version
windows/chrome 66.0.3359.139

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/ov6zLd0p/](https://jsfiddle.net/ov6zLd0p/)

### Steps to reproduce
点击切换第二、第三行的选中状态即可看到table没有正确展现

### What is Expected?
点击后只展示姓名和地址列，不展现多选列

### What is actually happening?
展示了多选列，且多了两列无关数据

**Comment by Leopoldthecoder** [comment]
You need to `key` the column: https://jsfiddle.net/ov6zLd0p/1/

**Comment by mengxb** [comment]
@Leopoldthecoder  The problem confused me very much, and thanks for your solution. Can you explain the cause of this problem or why your solution can resolve this problem ?
