### ISSUE TITLE
pagination最好提供直接设置页数的method

### ISSUE THREAD

**Issue by initial-wu** [ElemeFE/element#1115]
### ElementUI version
1.0.1

**Comment by furybean** [comment]
直接使用 :current-page="yourCurrentPage" 不可以么

**Comment by initial-wu** [comment]
:current-page绑定到一个computed，computed变化的时候可以看到Elpagination内部的currentPage(prop)变化但是internalCurrentPage并没有随之变化

**Comment by furybean** [comment]
@initial-wu 可以满足你的需求么？可以满足请关了这个 issue 吧。
