### ISSUE TITLE
[Bug Report] table component, mouse slid through cell times (Failed to execute'setEnd'on'Range') error

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#11157]
### Element UI version
2.3.8

### OS/Browsers version
Mac OS/Chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/b9pvwuuo/1/](https://jsfiddle.net/b9pvwuuo/1/)

### Steps to reproduce
1. 打开重现链接
2. 鼠标滑过'姓名'那一列, 控制台报错 Failed to execute 'setEnd' on 'Range': There is no child at offset 1.

当el-table-column用prop时, prop的值在对象中不存在, 或者是空值时, 鼠标滑过该列就会报错
而使用< template slot-scope="scope" >则不会

### What is Expected?
鼠标滑过空值的单元格不会报错

### What is actually happening?
鼠标滑过空值的单元格报错

**Comment by zzl7** [comment]
I met the same problem

**Comment by Leopoldthecoder** [comment]
Fixed in #11137

**Comment by MrSuperYang** [comment]
"element-ui": "^2.3.8","vue": "^2.5.2",我也遇到这个问题了，怎么修复

**Comment by lincenying** [comment]
@MrSuperYang 还没发布吧... 等2.3.9版, 现在暂时可以先退回2.3.7
