### ISSUE TITLE
[Feature Request] Dynamic Form Validation , can't change rule by ':prop'

### ISSUE THREAD

**Issue by daledelv** [ElemeFE/element#11159]
### Existing Component
Yes

### Component Name
el-form-item

### Description
I can't change the rule for optional input by three order,like the value's length isn't 0,but if the rule initial value isn't  ‘’ , the rule can natural switch between 'myRule' and ''. Is the prop can‘t bidirectional binding if its initial value is '' ?

**Comment by Leopoldthecoder** [comment]
Write a demo and open a new issue with it. From the description above, I really can't figure out what your problem is.

**Comment by daledelv** [comment]
For example:
`<el-form-item label="银行卡" :prop="formUseman.bankcard?'bankcard':''">
            <el-input type="number" v-model="formUseman.bankcard"></el-input>
  </el-form-item>`
I want to check a optional input if its value length isn't 0.it's effective when 'formUseman.bankcard's 
initial value isn't empty,conversely,it's failed.

**Comment by ZengFanhui** [comment]
Hello, have you solved the problem? I also met this problem

**Comment by daledelv** [comment]
后来我就不用切换方案了 直接重写了一个验证器 做个非空过滤

**Comment by ZengFanhui** [comment]
哈哈，我后来也是这样做的，自己重写的
