### ISSUE TITLE
[Bug Report] el-date-picker can't display date with V-model.

### ISSUE THREAD

**Issue by moonose** [ElemeFE/element#11160]
### Element UI version
2.3.8

### OS/Browsers version
win10 / Google Chrome v66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1940](https://jsfiddle.net/mmx38qxw/1940)

### Steps to reproduce
el-date-picker 使用 v-model 无法显示日期

element 2.3.7 没问题

### What is Expected?
el-date-picker 使用 v-model 可以正确显示日期

### What is actually happening?
el-date-picker 使用 v-model 无法显示日期

element 2.3.7 没问题

**Comment by Leopoldthecoder** [comment]
对于单选的 DatePicker，请确保其值为一个 Date 对象，而不是一个数组：https://jsfiddle.net/mmx38qxw/1941/
