### ISSUE TITLE
[Bug Report] Form form digital verification input numeric character can be verified through.

### ISSUE THREAD

**Issue by liu1235** [ElemeFE/element#11165]
### Element UI version
0.1.0

### OS/Browsers version
windows 10

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/vq71mfdb/](https://jsfiddle.net/vq71mfdb/)

### Steps to reproduce
1.先输入数字
2.在数字后面接着输入字符还是可以验证通过

### What is Expected?
Form表单验证数字时 输入框输入数字 字符可以验证通过，希望修复

### What is actually happening?
Form表单验证数字时 输入框输入数字 字符可以验证通过

**Comment by jikkai** [comment]
#5805
这不是一个 bug，是 Vue `number`修饰符的特性。

**Comment by STLighter** [comment]
不用`.number`, 自己做转换吧.
https://jsfiddle.net/ST_Lighter/zoj971xj/
