### ISSUE TITLE
[Bug Report] Form-Item prop cannot transfer key in this format'obj.d'.

### ISSUE THREAD

**Issue by likaixuan** [ElemeFE/element#11161]
### Element UI version
2.3.8

### OS/Browsers version
google 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/bugli/eywraw8t/59201/](https://jsfiddle.net/bugli/eywraw8t/59201/)

### Steps to reproduce
进入重现链接即可

### What is Expected?
Form-Item prop  接收 'obj.a' 这种格式的key时不会报错

### What is actually happening?
 Error in mounted hook: "Error: please transfer a valid prop path to form item!
 Error: please transfer a valid prop path to form item!

**Comment by Leopoldthecoder** [comment]
`prop="age.d"` 需要这样的结构：
```js
obj: {
  age: {
    a: ''
  }
}
```
