### ISSUE TITLE
[Bug Report] When trigger a mouseEnter event on an empty table cell, it consoles err

### ISSUE THREAD

**Issue by coolucifer** [ElemeFE/element#11171]
### Element UI version
2.3.8
### OS/Browsers version
Win10 Chrome 66.0.3359.139 x86

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/coolucifer/xdcbhtxt/](https://jsfiddle.net/coolucifer/xdcbhtxt/)

### Steps to reproduce
1.create a table with empty table cells
2.press 'F12' to open console
3.move mouse into an empty cell
4.it consoles an error

### What is Expected?
no error happens

### What is actually happening?
error occurs
![tim 20180515174544](https://user-images.githubusercontent.com/23123540/40049625-d3380716-5867-11e8-9efb-22f36bdb52b8.png)

**Comment by Leopoldthecoder** [comment]
Yes, it's fixed in #11137. Please wait for our next release. Or downgrade Element to 2.3.7 for now.
