### ISSUE TITLE
[Bug Report] InputNumber Components must use V-model

### ISSUE THREAD

**Issue by BengBu-YueZhang** [ElemeFE/element#11179]
### Element UI version
2.3.8

### OS/Browsers version
win10/ Chrome 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1943/](https://jsfiddle.net/mmx38qxw/1943/)

### Steps to reproduce
1. 页面上添加 InputNumber 组件
2. 不在 InputNumber 组件上使用 v-model
3. InputNumber 组件只能加到1

### What is Expected?
InputNumber 组件 不需要绑定 v-model也能正常使用

### What is actually happening?
InputNumber 组件 不绑定 v-model不能正常使用

**Comment by Leopoldthecoder** [comment]
This is not a bug, `v-model` is required.
