### ISSUE TITLE
[Bug Report] specific el-table mouseEnter error

### ISSUE THREAD

**Issue by jx-boom** [ElemeFE/element#11189]
### Element UI version
2.3.8

### OS/Browsers version
w10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/boom666/tgzpj2y9/1/](https://jsfiddle.net/boom666/tgzpj2y9/1/)

### Steps to reproduce
1.新建table组件
2.加入 el-table-column
3.  当不输入prop 或者 prop 为空时，控制台报错
   >>>>>Failed to execute 'setEnd' on 'Range': There is no child at offset 1.

### What is Expected?
控制台不会抛出异常

### What is actually happening?
控制台抛出异常

**Comment by Leopoldthecoder** [comment]
Fixed in #11137
