### ISSUE TITLE
[Feature Request] Seems there is no way to highlight/bold the search value

### ISSUE THREAD

**Issue by tonystaark** [ElemeFE/element#11188]
### Existing Component
Yes

### Component Name
el-select fiterable

### Description
Using the filterable search component, Is there anyway to highlight or bolden the search values that pop up in the dropdown?  If it returns 5 objects that contains the search values, each search value ought to be highlighted/ bold in the dropdown.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. But since `<el-option>` supports slot, you can insert the processed content (using render function / JSX, maybe) into it.
