### ISSUE TITLE
[Feature Request] open selectAll function

### ISSUE THREAD

**Issue by wangcongyi** [ElemeFE/element#11181]
### Existing Component
是

### Component Name
el-table

### Description
在使用多选表格组件中，selectAll 按钮并不是一定都在 table header 中。
希望开放功能，使得开发者能自由配置全选功能的所在UI位置。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/c0omr8t0/

**Comment by wangcongyi** [comment]
@Leopoldthecoder 与 table header 里的多选框不联动，
本来想法是 做一个 table header里 多选框的‘复制品’   到UI的任何地方，
有可能 在 table footer 上
