### ISSUE TITLE
After [Bug Report] [ElTooltip] changes the value of the attribute disabled, tooltip is not in the right place and the arrow is gone.

### ISSUE THREAD

**Issue by ohhoney1** [ElemeFE/element#11183]
### Element UI version
2.3.7

### OS/Browsers version
mac OS 10.13 / chrome 66

### Vue version
2.5.15

### Reproduction Link
[https://jsfiddle.net/emnj5kns/](https://jsfiddle.net/emnj5kns/)

### Steps to reproduce
1. 属性disabled默认设为true，
2. 当通过点击事件设为false，1200ms后设置为true，
（注意：期间鼠标不要移开）
3. 这时，再次点击，tooltip的位置不对，且箭头消失

### What is Expected?
tooltip的位置不变，且箭头存在

### What is actually happening?
tooltip的位置变了，箭头消失了

**Comment by Leopoldthecoder** [comment]
You need to `key` the tooltip: https://jsfiddle.net/emnj5kns/1/
