### ISSUE TITLE
[Bug Report] with input suggests quick typing with a focus of confusion.

### ISSUE THREAD

**Issue by zh68319220** [ElemeFE/element#11199]
### Element UI version
2.3.8

### OS/Browsers version
win10/65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/fkpwjc71/](https://jsfiddle.net/fkpwjc71/)

### Steps to reproduce
以官网实例【激活即列出输入建议】为例：
1.在输入框中输入“三全鲜食”
2.将光标放至“全”和“鲜”之间
3.切换至中文输入法，快速重复地输入某个文字（如：重复操作 q 空格 q 空格 q 空格）

### What is Expected?
输入框文字变成“三全去去去鲜食”

### What is actually happening?
输入框文字变成“三全去鲜食去去”

**Comment by Leopoldthecoder** [comment]
未能重现。请排除是否是输入法或浏览器插件的原因。

**Comment by STLighter** [comment]
@Leopoldthecoder 我这里可以复现, 需要切换到中文输入法并使用空格键快速键入文字(win 7/ chorme 66).
经过测试是在2.3.3版本引入的问题.

**Comment by STLighter** [comment]
引入问题的pr: #10517 
关联组件: `el-autocomplete`, `el-input`
产生原因: 
`compositionend`后更新内部`currentValue`, vue将会在**稍后同步**修改到dom中

在**同步前**用户又在输入法中键入了新的内容触发`compositionstart/compositionupdate/input`但未触发`compositionend`, 此时实际dom中value为新的内容

**同步时**dom中的`value`被重新修改回原值
