### ISSUE TITLE
[Bug Report] Edge browser el-button rendering problem

### ISSUE THREAD

**Issue by rootboard** [ElemeFE/element#11196]
### Element UI version
2.3.8

### OS/Browsers version
Windows 10 / Edge 17 (Edge 42)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/zgt7o2b3/2/](https://jsfiddle.net/zgt7o2b3/2/)

### Steps to reproduce
Click on the button "I'm not fine" and "After click I'll be fine"

### What is Expected?
Rendering default classes from component with adding from v-bind:class

### What is actually happening?
If el-button component has v-bind:class with logic for adding or not another class, so it renders without any classes at all and looks like classic browser's button.
If we have v-on:click in el-button component there we manipulate with data which are in v-bind:class and change them, so button gets all classes. If we have just v-on:click and don't change data - nothing changes.

**Comment by Leopoldthecoder** [comment]
It seems Edge doesn't work well when there're both `class` and `:class`. Write it this way: https://jsfiddle.net/zgt7o2b3/3/ .
