### ISSUE TITLE
[Bug Report] about a table component bug ‘Failed to execute 'setEnd' on 'Range': There is no child at offset 1’

### ISSUE THREAD

**Issue by vasttian** [ElemeFE/element#11203]
### Element UI version
2.3.8

### OS/Browsers version
high sierra/chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/vasttian/b69ts6zm/1/](https://jsfiddle.net/vasttian/b69ts6zm/1/)

### Steps to reproduce
表格数据里没有对应的 prop 或对应 prop 数值为空时，表格渲染后，鼠标移到空单元格时会报错。
之前版本无此问题。

### What is Expected?
-
![image](https://user-images.githubusercontent.com/17924984/40155824-4c3e0c12-59c8-11e8-834c-96bacb552931.png)

### What is actually happening?
报错

**Comment by Leopoldthecoder** [comment]
Fixed in #11137
