### ISSUE TITLE
[Bug Report] v2.3.8 el-switch miss a button

### ISSUE THREAD

**Issue by AlexZhong22c** [ElemeFE/element#11201]
### Element UI version
2.3.8

### OS/Browsers version
win10 x64 chrome

### Vue version
2.4.4

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/switch/src/component.vue](https://github.com/ElemeFE/element/blob/dev/packages/switch/src/component.vue)

### Steps to reproduce
https://github.com/ElemeFE/element/blob/dev/packages/switch/src/component.vue

as shown,at version v2.3.8,
`<span class="el-switch__core" ref="core" :style="{ 'width': coreWidth   'px' }">`

miss a HTML element: `<span class= "el-switch__button"></span>`

### What is Expected?
a normal el-switch

### What is actually happening?
the el-switch element miss a inner html tag

**Comment by Leopoldthecoder** [comment]
`.el-switch__button` is intentionally removed.

**Comment by AlexZhong22c** [comment]
thanks for info.If possible,log it in the changelog.It's a big change.

**Comment by armysheng** [comment]
官网的组件库好像还有这个小圆点 @Leopoldthecoder
