### ISSUE TITLE
Arbitrary time picker scrollbars

### ISSUE THREAD

**Issue by cAstraea** [ElemeFE/element#1120]
### OS/Browers version

chrome 54
### Reproduction Link

http://element.eleme.io/#/en-US/component/time-picker
### Steps to reproduce
trying out the arbitrary time picker scrolling through different values
### What is Expected?
On edge / IE no scrolls bars appear . On chrome / firefox scrollbars appear for each of the three segments.
### What is actually happening?
Example seen below. Also the numbers don't flow on exact increments, sometimes the slider stops in between the numbers. 
![image](https://cloud.githubusercontent.com/assets/13070662/20356574/9586b292-ac2d-11e6-8abd-159742ae59ab.png)

**Comment by Leopoldthecoder** [comment]
Yes, currently we are not content with how TimePicker looks. This will get improved later.

**Comment by aniforprez** [comment]
Hey is there a particular reason this was closed? It's still an issue and a big one at that.

**Comment by Leopoldthecoder** [comment]
@aniforprez  It's kinda overlapping with #326. We will trace that one and update progress there.
But you can reopen this issue if you think necessary.

**Comment by aniforprez** [comment]
Ah cool. That's what I was asking. I can't figure out which issues are duplicates because a lot are in Chinese and I don't know the language and can't search in it either. As long as the issue is being tracked it's all good.

**Comment by Leopoldthecoder** [comment]
I figured it has to be because the language. Should have added a link to #326 before I close this.

**Comment by aniforprez** [comment]
Are you guys taking PRs for this issue? I can try to help out

**Comment by Leopoldthecoder** [comment]
@aniforprez Absolutely. Contributions are always welcome.

**Comment by aniforprez** [comment]
Sweet

**Comment by QingWei-Li** [comment]
#1947
