### ISSUE TITLE
[Feature Request] el-tree does not need to cancel the currently selected method.

### ISSUE THREAD

**Issue by jiangyitao** [ElemeFE/element#11202]
### Existing Component
Yes

### Component Name
el-tree

### Description
1.可以通过this.$refs.tree.setCurrentKey()设置当前高亮选中的行
2.但是无法取消当前高亮选中的行

**Comment by Leopoldthecoder** [comment]
是 Tree 还是 Table？

**Comment by jiangyitao** [comment]
不好意思 是tree
