### ISSUE TITLE
[Feature Request] adds Index signature for type of TreeNode.

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#11204]
### Existing Component
是

### Component Name
Tree

### Description
Tree的data可以接受除id label children等定义在TreeData内的属性之外, 还应该可以接受其他自定义属性, 但是它目前并不能

**Comment by ziyoung** [comment]
@Kingwl 我觉得可以添加一个 `meta` 字段，里面放一些用户自定义信息。

```js
{
  label: '',
  children: [],
  meta: {}
}
```

**Comment by Kingwl** [comment]
差不多...
