### ISSUE TITLE
[Feature Request] custom upload settings can not be deleted after reaching limit limit.

### ISSUE THREAD

**Issue by qqcbqqkcel** [ElemeFE/element#11217]
### Existing Component
是

### Component Name
el-upload

### Description
使用自定义上传并且设置limit 为2
当上传2个文件时移动到文件列表不会显示删除按钮，没有达到限制就会显示

**Comment by Leopoldthecoder** [comment]
这是 Bug Report，不是 Feature Request。请不要因为不想写 demo 就选择 Feature Request。
