### ISSUE TITLE
[Feature Request] tabs adds new toggle hooks, similar to beforeRouterLeave.

### ISSUE THREAD

**Issue by PilgrimErick** [ElemeFE/element#11213]
### Existing Component
是

### Component Name
Tabs

### Description
Tabs能否新增一个切换前的钩子，类似于beforeRouterLeave，方便在用户编辑未保存后切换到另一个标签页，导致前面的编辑因进入标签页时丢失编辑内容。

**Comment by Leopoldthecoder** [comment]
可以支持，已列入 Product Backlog：https://github.com/ElemeFE/element/projects/8#card-9843847
