### ISSUE TITLE
[Bug Report] tree component, when lazy data loading mode, can not add lower level nodes through append method.

### ISSUE THREAD

**Issue by Kanchil** [ElemeFE/element#11218]
### Element UI version
2.3.8

### OS/Browsers version
windows10 Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/halfBeta/mmx38qxw/1947/](https://jsfiddle.net/halfBeta/mmx38qxw/1947/)

### Steps to reproduce
tree组件异步获取数据之后，想实现可以添加节点或者删除节点；然而获取tree实例后，通过append和remove方法对节点进行的操作无效

### What is Expected?
通过tree实例的append和remove方法对节点进行操作

### What is actually happening?
操作无效

**Comment by kouguopeng** [comment]
你好像写错了this.$refs.tree.append 方法里面加的是数据和节点，所有是this.$refs.tree.append(newChild, node),不是this.$refs.tree.append(newChild, data)

**Comment by Leopoldthecoder** [comment]
Tree 的 `node-key` 被指定为了 `id`，但是 `loadNode1` 返回的数据里并没有 `id` 字段。
