### ISSUE TITLE
[Bug Report] <el-table> Error when hovering over empty cells

### ISSUE THREAD

**Issue by hairui219** [ElemeFE/element#11219]
### Element UI version
2.3.8

### OS/Browsers version
Windows 10
Chrome  66.0.3359.139
Electron 2.0.0

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/h9q86pev/](https://jsfiddle.net/h9q86pev/)

### Steps to reproduce

```javascript
// element-ui/packages/table/src/table-body.js, Line 343
    range.setEnd(cellChild, 1);
```

And the data in the cell is empty ("")

### What is Expected?
No error output.

### What is actually happening?
If the cell is empty, when mouse move on to the cell, the console will output:

```
Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.
```

**Comment by lochstar** [comment]
This was previous reported here: https://github.com/ElemeFE/element/issues/11203 and has been fixed here: https://github.com/ElemeFE/element/pull/11137
