### ISSUE TITLE
http://element-cn.eleme.io   is null page!!!

### ISSUE THREAD

**Issue by tangmin721** [ElemeFE/element#11227]
### Element UI version
2.3.8

### OS/Browsers version
window

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
The document page is null page.  
http://element.eleme.io/#/zh-CN
http://element.eleme.io/#/zh-CN/component/

### What is Expected?
The document page is null

### What is actually happening?
The document page  is null

**Comment by CCWork** [comment]
+1

**Comment by uniquejava** [comment]
reading plain text version 😢  https://github.com/ElemeFE/element/blob/dev/examples/docs/en-US/table.md

**Comment by DarG002** [comment]
+1

**Comment by JianShaw** [comment]
+1

**Comment by hoythan** [comment]
+10086

**Comment by ukhack** [comment]
+2k

**Comment by LeslieZhang** [comment]
+1

**Comment by LeslieZhang** [comment]
是不是和阮一峰一样，被攻击了？

**Comment by sarsshitou** [comment]
+

**Comment by sarsshitou** [comment]
+1

**Comment by Leopoldthecoder** [comment]
No, we're not under attack. There's a problem during DNS lookup.

**Comment by Leopoldthecoder** [comment]
We're aware that this affects almost everybody, so please don't +1 here.

The team's working on it.

**Comment by Leopoldthecoder** [comment]
https://element.eleme.io and http://element-cn.eleme.io are back online.
