### ISSUE TITLE
[Bug Report] table with show-overflow-tooltip can not display tooltips correctly (IE11).

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#11220]
### Element UI version
2.3.8

### OS/Browsers version
windows10，IE11

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/xn8ddb14/](https://jsfiddle.net/xn8ddb14/)

### Steps to reproduce
1.给单元格添加 show-overflow-tooltip 属性
2.当单元格的字段长度超过宽度，单元格出现省略号;
3.现在在IE11中无论被隐藏的字段为多少个，都不显示了(之前在ElementUI v2.3.6提过一个issue，在被隐藏的字段为一个或者两个中文字符 #11120)；
4.在 IE11 中无法正常显示 tooltip（谷歌浏览器能正常显示）

### What is Expected?
在  IE 中也能正常显示

### What is actually happening?
现在IE11中无论被隐藏的字段为多少个，hover 都无法显示 tooltip

**Comment by fengyun2** [comment]
我从github拉取了源码到本地后，按照 [1341588](https://github.com/ElemeFE/element/commit/13415882105a98345e18302cbe1b39bd2b611c9f) 修改了 `packages/table/src/table-body.js` 的源码, 用`yarn install` 安装了依赖后，再运行`yarn run dist` 打包，在谷歌和火狐上正常了，IE11中 在被隐藏的字段为一个或者两个中文字符时仍然无法正常显示 tooltip。

**Comment by Leopoldthecoder** [comment]
是的，这个应该没有办法解决了。
