### ISSUE TITLE
The total of [Bug Report] table will aggregate the columns which are not numeric but conform to isNaN.

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#11223]
### Element UI version
2.3.8

### OS/Browsers version
win10/chrome66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/09Ld4d5g/](https://jsfiddle.net/09Ld4d5g/)

### Steps to reproduce
无

### What is Expected?
不合计，footer显示空

### What is actually happening?
id也进行了合计
建议：为column增加是否参与合计的标记和列级自定义合计方法

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/09Ld4d5g/1/

**Comment by gaecfov** [comment]
summary-method是可以实现，不过用到的地方很多，每个地方都需要去设置summary-method也是很麻烦的事情，而且summary-method中的column没有将额外加到table-column的attribute加进来，所以也不能通过给的自定义标记来处理，还是建议给table-column加上是否参与合计的prop和column级的summary-method
