### ISSUE TITLE
The show-text attribute of [Feature Request] rate cannot set its location.

### ISSUE THREAD

**Issue by wufeng123456** [ElemeFE/element#11231]
### Existing Component
是

### Component Name
el-rate

### Description
el-rate组件的show-text属性 显示的文字都是在图标右侧，但不能设置位置， 能否添加position属性 ，使文字可以设置位置

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can change its position using CSS.

**Comment by wufeng123456** [comment]
谢谢啊， 我遇到的问题被我解决了
