### ISSUE TITLE
[Bug Report] carousel bug for el-carouosel__container can't add style to change

### ISSUE THREAD

**Issue by T-OneSoul** [ElemeFE/element#11236]
### Element UI version
2.3.9

### OS/Browsers version
window 7   appCodeName : "Mozilla" appName : "Netscape" appVersion : "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5221.400 QQBrowser/10.0.1125.400"

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
english:（English is not good enough）you can build vue-cli project and use carousel at element-ui,you will see that class name el-carousel__container in the div,and you can't plus style to change this div  eg. plus the style property height,then anything change 
中文：创建一个vue工程化项目，使用element-ui中的走马灯组件，你会发现生轮播生出来的div,class为 el-carousel__container 该div无法添加样式去改变这个div的样式，后来我仔细对比发现主要是这div没有生出对应的data-v-33e07980属性，所以无法更改

### What is Expected?
english :（English is not good enough）can change class name for el-carousel__container at the div and that change style
中文：（英文莫不好见怪）想改变这个class 为 el-carousel__container的div的样式

### What is actually happening?
english :（English is not good enough）can change class name for el-carousel__container at the div and that can't change style
中文：（英文莫不好见怪）改变不了这个class 为 el-carousel__container的div的样式

**Comment by Leopoldthecoder** [comment]
https://vue-loader.vuejs.org/zh/guide/scoped-css.html#%E6%B7%B1%E5%BA%A6%E4%BD%9C%E7%94%A8%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by T-OneSoul** [comment]
@Leopoldthecoder  无法解决 该div的父类、子类都自动生成了深度样式data-v-33e07980，为啥就唯独该div没生成？我自己添加了深度符 >>>也无效

**Comment by jokerforweb** [comment]
深度作用选择器>>>是作用于css的 如果是SCSS啥的得用::v-deep
`
.el-carousel {
  &::v-deep {
    .el-carousel__container {
      .el-carousel__arrow {
        width: 100px;
        height: 100px;
        i {
          font-size: 50px;
          font-weight: 600;
        }
      }
    }
  }
}
`
