### ISSUE TITLE
[Bug Report] cascadar cannot display the last level text.

### ISSUE THREAD

**Issue by JZLeung** [ElemeFE/element#11232]
### Element UI version
2.3.2

### OS/Browsers version
macOs/chrome

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/5fgvdL0f/](https://jsfiddle.net/5fgvdL0f/)

### Steps to reproduce
demo 中是正常的，但是在我的实际项目中却无法正常显示。数据配置也是一样的。

### What is Expected?
选择后显示最后一级文本。

### What is actually happening?
显示第一级的文本，并且重新选择时，没有默认值。
![image](https://user-images.githubusercontent.com/7995232/40221480-33545c00-5aaf-11e8-99dd-66be7a1ba1ea.png)

![image](https://user-images.githubusercontent.com/7995232/40221474-2c15dd6a-5aaf-11e8-99b4-18e7257b9365.png)

**Comment by Leopoldthecoder** [comment]
请将你的项目最小化，并上传至 GitHub。然后开一个新的 issue，在 Reproduction Link 中填入 GitHub 仓库地址。

**Comment by JZLeung** [comment]
找到问题了，原因是在 change 回调中，将传入的 value 给 reverse 了，所以导致出错。
