### ISSUE TITLE
[Bug Report] tabs content property how to add a components dynamically

### ISSUE THREAD

**Issue by GreedyPirate** [ElemeFE/element#11237]
### Element UI version
2.0.8

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
click the add button, my question is how to add a component dynamically by a click event, Tab-pane'property content is String type now

### What is Expected?
I can add a component in a js function

### What is actually happening?
let detail = resolve => require(['../taskDetail/taskDetail'], resolve);
        let newTabName =   this.tabIndex   '';
        this.tabData.push({
          title: row.name.substring(0,3) ' ...',
          name: newTabName,
          content: detail
        });
it doesn't work

**Comment by jikkai** [comment]
Please provide a valid reproduction link.

**Comment by jikkai** [comment]
You can use [`<component>`](https://vuejs.org/v2/api/#component) to render dynamic components.
I created a demo here: [https://jsfiddle.net/vj5kt2y0/](https://jsfiddle.net/vj5kt2y0/)

**Comment by hqzh** [comment]
https://github.com/ElemeFE/element/issues/3257
