### ISSUE TITLE
[Bug Report], your official website has been hung up. No, it's 2018-05-18-20:26 now.

### ISSUE THREAD

**Issue by woaixiangbao** [ElemeFE/element#11241]
### Element UI version
2.3.9

### OS/Browsers version
Macbook

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
直接打开http://element.eleme.io/#/zh-CN/component/message

### What is Expected?
啊啊

### What is actually happening?
发发发

**Comment by jikkai** [comment]
duplicate to #11227
