### ISSUE TITLE
[Bug Report] Items in select combobox jiggle when you zoom out with chrome

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#11242]
### Element UI version
2.3.9

### OS/Browsers version
Windows 10 / Chrome - latest

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/p84pdxwe/2/](https://jsfiddle.net/p84pdxwe/2/)

### Steps to reproduce
Open link with chrome.
Ctrl   scroll down   to zoom out to 90%. 

In the reproduction link, the items only jiggle at 90%, but in our application, we've see the items jiggle at 90, 80, 67, and 25. Everything over 100% works fine.

### What is Expected?
The items to say put

### What is actually happening?
The items jiggle.

**Comment by TUARAN** [comment]
Has it been solved?

**Comment by ChuckFields** [comment]
Hi @TUARAN, this has not be solved yet. I've realize it's hard to see in my reproduction link. The effects of the jiggling become magnified when components are stacked. Here is an updated jsfiddle using element 2.4.8:
[https://jsfiddle.net/964c5azu/](https://jsfiddle.net/964c5azu/)
