### ISSUE TITLE
[Bug Report] Close el-select the arrow with filterable

### ISSUE THREAD

**Issue by iumag** [ElemeFE/element#11249]
### Element UI version
2.3.9

### OS/Browsers version
Windows 10 Pro/Chrome 66.0.3359.1

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/IUMag/mmx38qxw/1948/](https://jsfiddle.net/IUMag/mmx38qxw/1948/)

### Steps to reproduce
1. Click on the arrow
2. When open select, again Click on the arrow

### What is Expected?
Close select

### What is actually happening?
When a filterable is used in an el-select, then if you click on the arrow, the select will open, but if you then click again on the arrow, it does not close.If you click on the field, everything works fine

**Comment by badpunman** [comment]
In addition, it seems that when you click outside to close the popover, it takes two clicks on the arrow to open it back up again.
