### ISSUE TITLE
tabs 样式问题

### ISSUE THREAD

**Issue by jiangchengshi2016** [ElemeFE/element#1124]
### ElementUI version
"element-ui": "^1.0.0-rc.8",

### OS/Browers version
Chrome  54.0

### Vue version
"vue": "^2.0.1",

### Reproduction Link
http://jsfiddle.net/jx5tt0k6/

### Steps to reproduce
当内容过长是， border-bottom样式有问题。
el-tabs__active-bar   width: 60px;

特别是 单个tab时问题更明显

### What is Expected?
样式正常

### What is actually happening?
样式错乱

**Comment by furybean** [comment]
看不懂这个 issue，`<el-tab-pane>` 中的内容不是标题，是这个 Tab 中显示的内容。

**Comment by jiangchengshi2016** [comment]
是 内容过长，导致 border-bottom变长，但是 el-tabs__active-bar  的style中width计算有问题。 跟border-bottom不一样长度

**Comment by baiyaaaaa** [comment]
@jiangchengshi2016 el-tabs__active-bar 的width没问题，只不过是整个tabs元素因为内容区被撑开而导致header也自适应延长，实际上因为它是个行内元素你应该制定el-tabs的宽度。我们有考虑将这个改成block元素

**Comment by MRzyb** [comment]
el-tab-pane里面再次嵌套el-tabs，且最外层的el-tabs的type为card或者border-card的时候，el-tab-pane里嵌套的el-tabs的el-tab-pane的 el-tabs__active-bar宽度计算不正确
`  <el-tabs v-model="activeLi" type="border-card">
      <el-tab-pane label="aaaa" name="aaaa">要哭设置</el-tab-pane>
      <el-tab-pane label="bbbb" name="bbbb">预约设置</el-tab-pane>
      <el-tab-pane label="ccccc" name="ccccc">
          <el-tabs v-model="activeLi1" tab-position="top" >
            <el-tab-pane label="111111" name="1">
             111111
            </el-tab-pane>
            <el-tab-pane label="12222222222" name="2">
              12222222222
            </el-tab-pane>
            <el-tab-pane label="33333333333" name="3">
              33333333333
            </el-tab-pane>
          </el-tabs>
      </el-tab-pane>
    </el-tabs>`

**Comment by lanpangzhi** [comment]
> el-tab-pane里面再次嵌套el-tabs，且最外层的el-tabs的type为card或者border-card的时候，el-tab-pane里嵌套的el-tabs的el-tab-pane的 el-tabs__active-bar宽度计算不正确
> ` <el-tabs v-model="activeLi" type="border-card"> <el-tab-pane label="aaaa" name="aaaa">要哭设置</el-tab-pane> <el-tab-pane label="bbbb" name="bbbb">预约设置</el-tab-pane> <el-tab-pane label="ccccc" name="ccccc"> <el-tabs v-model="activeLi1" tab-position="top" > <el-tab-pane label="111111" name="1"> 111111 </el-tab-pane> <el-tab-pane label="12222222222" name="2"> 12222222222 </el-tab-pane> <el-tab-pane label="33333333333" name="3"> 33333333333 </el-tab-pane> </el-tabs> </el-tab-pane> </el-tabs>`

这个问题还存在2.4.11版本

**Comment by puxiaotaoc** [comment]
需要手动修改active-bar的尺寸
/deep/.el-tabs__active-bar {
  min-width: 146px !important;
}
![image](https://user-images.githubusercontent.com/20106942/160376898-77a8d39d-8bdd-4d44-9e43-103a0d17e2b7.png)
