### ISSUE TITLE
[Bug Report] Turn on Css Modules and report errors

### ISSUE THREAD

**Issue by shibin-you** [ElemeFE/element#11254]
### Element UI version
2.3.8

### OS/Browsers version
all

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/issues/11253](https://github.com/ElemeFE/element/issues/11253)

### Steps to reproduce
1. When the CSS Modules are closed, it can be used normally, and the error is reported when it is opened.

2. When opening CSS Modules, comment out the 'import 'element- UI /lib/theme-chalk/index.css'.

### What is Expected?
Open Css Modules can be used normally.

### What is actually happening?
Turn on Css Modules and report errors

**Comment by Leopoldthecoder** [comment]
Please minify your project and upload it to GitHub, and open a new issue with it.
