### ISSUE TITLE
[Feature Request] questions about the return node information after the tree component is selected.

### ISSUE THREAD

**Issue by Destinygu** [ElemeFE/element#11258]
### Existing Component
是

### Component Name
el-tree

### Description
树形组件勾选后，getCheckedNodes返回的是每个选中结点对象的数组，getHalfCheckedNodes返回的是每个半选中结点对象的数组。但如果我想要得到当前处于选中状态的整个树，即返回的树中只要某个子结点被选中，即使并未全选，其祖先结点的信息也嵌套该子结点返回。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
