### ISSUE TITLE
[Feature Request] provides configuration items for table component to trigger sorting order.

### ISSUE THREAD

**Issue by Tk-archer** [ElemeFE/element#11255]
### Existing Component
Yes

### Component Name
el-table

### Description
现在点击 el-table 表头排序时默认是 ascending 再到 descending。

有的业务场景中 descending 的频率更高，

因此需要一个配置项使得点击表头时先触发 descending 再触发 ascending

**Comment by Leopoldthecoder** [comment]
@jikkai 结合 #3994，感觉可以提供一个属性，让用户传入某一列在排序时的轮转顺序。比如这个属性默认是 `['ascending', 'descending', null]`，即升序 -> 降序 -> 还原 -> 升序；如果传入 `['descending', 'ascending']`，则为降序 -> 升序 -> 降序。

参考：
https://github.com/ElemeFE/element/blob/54eeb5ced374f16d8b26d82fb823b61ef50794c5/packages/table/src/table-header.js#L478-L480
