### ISSUE TITLE
[Tree] 设置了 lazy 的时候，希望可以不缓存获取到的子节点数据

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#1125]
### What is Expected?
tree组件 点击上级节点的时候如何每次都刷新子树数据或者是重新获取子树数据呢

**Comment by furybean** [comment]
数据默认都会缓存的，现在并没有提供缓存与否的开关，后续我会考虑增加这个功能。

**Comment by wilsonIs** [comment]
@furybean 是不是会在某个情况下清掉缓存？测试发现点同一个节点的数据，第一次慢，第二次快。但是如果切换点击了另一个节点后，然后再来点刚才点过的节点时，发现又变慢了。

**Comment by liangbizhi** [comment]
不需要缓存的时候关闭this.$refs.yourTree.$data.store.lazy = false
需要的时候再开启。。。
