### ISSUE TITLE
How to close the opening expendable row in el-table when clicking the others' expend arrows?

### ISSUE THREAD

**Issue by suyi91** [ElemeFE/element#11268]
### Element UI version
2.3.9

### OS/Browsers version
MacOS/Chrome 66

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/ennb8tq1/](https://jsfiddle.net/ennb8tq1/)

### Steps to reproduce
1. click the first row's expend arrow
2. click the second row's expend arrow

### What is Expected?
Want to close the first row.

### What is actually happening?
The first and the second rows are expended.

**Comment by Leopoldthecoder** [comment]
A possible solution: https://jsfiddle.net/2a5t5dud/

**Comment by suyi91** [comment]
@Leopoldthecoder 
😁Thanks for your response. It's a really great idea. But there's something not so good.

As expanded is an array, `!expanded === false`. If click the first row's arrow, and then click it again, the row isn't closed.

I edit the code to meet the requirement. [https://jsfiddle.net/2a5t5dud/1/](https://jsfiddle.net/2a5t5dud/1/)

**Comment by Leopoldthecoder** [comment]
Yes you're right.
