### ISSUE TITLE
[Feature Request] <el-pagination> English information to Chinese

### ISSUE THREAD

**Issue by PiedPiperr** [ElemeFE/element#11264]
### Existing Component
是

### Component Name
el-pagination

### Description
'total','/page','Go to'. 

How to translate into Chinese

**Comment by Leopoldthecoder** [comment]
默认就是中文的，只有设置了 i18n 才会显示其他语言。

**Comment by PiedPiperr** [comment]
谢谢我已经解决了

const i18n = new VueI18n({
  locale: 'zh', // 设置语言
  messages // set locale messages
})
