### ISSUE TITLE
[Bug Report] When scroll parent is body, the position of ElSelect's dropdown in ElDialog is incorrect.

### ISSUE THREAD

**Issue by bq-hentai** [ElemeFE/element#11272]
### Element UI version
2.3.9

### OS/Browsers version
Windows 7/Chrome 65

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/mmx38qxw/1951/

### Steps to reproduce
Scroll top for a distance and click `Show Dialog` button. Then click the ElSelect in the dialog.

See the position of the option list.

Note: the actual reason is the result of `getScrollParent` is `body`. But the parent of dropdown is html. So the bounding is not consistent.

### What is Expected?
The position is correct.

### What is actually happening?
The position is not correct.

**Comment by bq-hentai** [comment]
Reproduction test.
[test.zip](https://github.com/ElemeFE/element/files/2024866/test.zip)

**Comment by bq-hentai** [comment]
P.s. There is a typo in the comment of `getScrollParent` function.

```javascript
// Firefox puts the **scrollTOp **value on `documentElement` instead 
```

**Comment by Leopoldthecoder** [comment]
补个 demo：https://jsfiddle.net/mmx38qxw/1951/

**Comment by Leopoldthecoder** [comment]
@ziyoung 算是 popup 的问题。

**Comment by ziyoung** [comment]
像是 HTML 元素上加了 `overflow: hidden;` 造成的。https://jsfiddle.net/zhiyang/dLw3mmfv/1/
```css
html {
  overflow: hidden;
 /*  height: 100%; */
} 

body {
  overflow: auto;
  height: 100%;
  margin: 0;
} 
```

**Comment by ziyoung** [comment]
element-ui 使用的 popper.js 版本有点老了。我在本地试了一下，如果最新版的 popper.js ，就不会出现这个问题了。我们正在考虑升级一下 popper.js。

**Comment by bq-hentai** [comment]
@ziyoung 期待新的版本。

另外建议增加某个特性开始发布的版本。比如增加了某个prop，在旁边标注一下since xxx version。

**Comment by ddddderek** [comment]
@ziyoung 有没有什么临时解决方案呢？我我的html标签并没有overflow:hidden这样的属性，也有相同的问题。

**Comment by ziyoung** [comment]
@ddddderek 提供一个可重现问题的例子。

**Comment by ddddderek** [comment]
@ziyoung 不好意思。我的不是在dialog中。标题没看清楚。
后面我会提一个issues。

**Comment by bq-hentai** [comment]
@ziyoung dalao这个什么时候能更新呢 还是已经更新过了

**Comment by bq-hentai** [comment]
某个版本之后有个popper-append-to-body= =
![image](https://user-images.githubusercontent.com/19964297/42745413-299a01ea-8905-11e8-8b3a-4298f3020f4f.png)

**Comment by bq-hentai** [comment]
now fixed and close.

refs:

[ref](https://github.com/ElemeFE/element/pull/11778)
[doc](http://element-cn.eleme.io/#/zh-CN/component/select)
