### ISSUE TITLE
[Bug Report] 'v-popover'  was invalid   in the last tr when using el-table, 

### ISSUE THREAD

**Issue by tombear110** [ElemeFE/element#11277]
### Element UI version
2.3.9

### OS/Browsers version
win7 chrome62.0.3202.94

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/tombear/5qy6nqr4/15/](https://jsfiddle.net/tombear/5qy6nqr4/15/)

### Steps to reproduce
1. open the jsfiddle link;
2. compare two buttons of 'slot-true' and 'v-po-false';
3. in the last tr, hovering the button of 'v-po-false', dialog was  disappeared, 

### What is Expected?
v-popover has the same result with "slot='reference'"

### What is actually happening?
'v-popover'  was invalid   in the last tr when using el-table,

**Comment by ziyoung** [comment]
这不是 bug。我觉得你的用法不太合理。
- ref 用来引用组件或者 DOM 元素。对数组 tableData 进行遍历时，会创建很多的 `<el-popover ref="popover">`，那么最后 `this.$refs.popover` 到底是那一个元素？
- 目前，在使用 v-popover 指令时，也无法做到多个元素共用一个 Popover 组件。参考 #9498 

对你的例子做出了一点修改，现在正常了。https://jsfiddle.net/zhiyang/d0f1L58v/1/

**Comment by tombear110** [comment]
是的。谢谢了。
