### ISSUE TITLE
[Bug Report] Element-select selector (which supports grouping, multi selection, and search function) after selecting two rows, the height of the input box is not a fixed value.

### ISSUE THREAD

**Issue by TUARAN** [ElemeFE/element#11279]
### Element UI version
2.3.9

### OS/Browsers version
win10/64位/opera v-53.0

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/TUARAN/elmentSelectInputBug](https://github.com/TUARAN/elmentSelectInputBug)

### Steps to reproduce
1.在1440px分辨率下：一定要注意分辨率，在某些分辨率下没有此bug，可尝试ctrl 滚轮将页面缩小一点再勾选观察；
2.可打开控制器观察input框的高度，边勾选边注意input框的高度(勾选了两行、八行会触发此bug);
3.hover在inoput选择框下边框出现闪烁，离开下边框不出现闪烁;

### What is Expected?
1.勾选后，经过计算，高度应该为一个定值，而非一直在变化；

### What is actually happening?
1.勾选后高度在两个值反复变化，比如89px和90px,而不是一个定值；

**Comment by Leopoldthecoder** [comment]
Duplicate of #11242
