### ISSUE TITLE
[Feature Request] way to sets default form component size when set global size

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#11287]
### Existing Component
Yes

### Component Name
all form related component

### Description
while global size set via `Vue.use(Element, { size: 'small' });`, is there any way to set some specific form component instance (e.g. `el-button`) to its default size?
Because default size was no longer explicitly declared

**Comment by Leopoldthecoder** [comment]
You can set its size to `large`. Actually anything other than `medium`, `small` or `mini` will fallback to its default size: https://jsfiddle.net/nkxvejme/

**Comment by troy351** [comment]
Thanks, maybe this feature could be mentioned in the doc

**Comment by troy351** [comment]
I got that, other `size` won't overwrite the default css rules
