### ISSUE TITLE
[Bug Report] ElTree插件当data为null时引起异常.

### ISSUE THREAD

**Issue by dinfer** [ElemeFE/element#11280]
### Element UI version
2.3.9

### OS/Browsers version
Widnow10, Chrome 66

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/blob/4fe58a3d96b308843c682bbc07b5977d24be92e1/packages/tree/src/model/util.js#L4](https://github.com/ElemeFE/element/blob/4fe58a3d96b308843c682bbc07b5977d24be92e1/packages/tree/src/model/util.js#L4)

### Steps to reproduce
无需重现. 代码没有进行空值判断.

对于ElTree组件, 设置data为null时, 如下语句因为没有空值判断, 引起异常.
[代码](https://github.com/ElemeFE/element/blob/4fe58a3d96b308843c682bbc07b5977d24be92e1/packages/tree/src/model/util.js#L4)

此语句直接读取data[NODE_KEY]导致Cannot read property '$treeNodeId' of undefined

### What is Expected?
如果data为null,可以设置一个没有children的空节点表示空值

### What is actually happening?
导致Cannot read property '$treeNodeId' of undefined

**Comment by Leopoldthecoder** [comment]
无法复现：https://jsfiddle.net/jp1atks1/ ，请提供 demo。
另：只有 `data` 为 truthy 时才会调用 `markNodeData`。

**Comment by dinfer** [comment]
代码摘录出来了.

https://github.com/dinfer/element-ui-bug

重复步骤:
打开vue devtools, vuex页面
点击两次新建步骤
点解vuex的commit all

提示错误如下:
![image](https://user-images.githubusercontent.com/11496403/40354177-d9386844-5de5-11e8-9051-f11ad8d08cb0.png)

**Comment by ziyoung** [comment]
el-tree 的 data 应该是数组，使用 vuex revert all 后，data 变成了 undefined。
![image](https://user-images.githubusercontent.com/12947422/40540135-aa408376-6049-11e8-8baf-89a771a5eb70.png)

**Comment by dinfer** [comment]
是的，即使是commit all, data也会变成undedined。
