### ISSUE TITLE
Official explanation and use of [Bug Report]'s resetFields method for form forms

### ISSUE THREAD

**Issue by old-bin** [ElemeFE/element#11294]
### Element UI version
2.3.7

### OS/Browsers version
这不是重点

### Vue version
2.5.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
我的使用场景是这样的，我有一个增加和编辑是用的同一个 form 表单对象，但是每次调用 resetFields 时发现它并不是把表单重置为我在data 定义的 form 的 model，而是我第一次使用表单组件时使用的数据。

但是官方文档里对resetFields 方法的描述是： 对整个表单进行重置，将所有字段值重置为初始值并移除校验结果。

看到这个描述，我感觉完全被误导了，按我的理解，真正的初始值应该是 data 里定义的 model，而不是第一次调用 form 表单并初始化时使用的数据。

个人建议文档里对这点进行更合理的解释，或者增加说明。另外希望能加一个方法或者能在 resetFields 方法里传递参数以将字段值重置为 data 里最原始的值。

### What is Expected?
form 表单的 resetFields 无法重置为 data 里定义 form model 中的原始值

### What is actually happening?
form 表单的 resetFields 重置的是第一次调用 form 表单是使用的数据

**Comment by Leopoldthecoder** [comment]
`resetFields` 就是重置为在 data 定义的 form 的 model。有问题请提供 demo。

**Comment by AnyGong** [comment]
我理解他说的是什么意思。 比如初始data是 ` {a:'',b:''}`, 进行操作赋值之后是 ` {a:'1',b:'2'}`, 成功之后这个时候再次操作赋值 `{a:'3',b:'4'}`,成功之后 然后调用 `resetFields` @old-bin 你想的是实际状态是应该回到 ` {a:'',b:''}` 这个吗？
