### ISSUE TITLE
[Feature Request] InputNumber with slot for unit (kg, cm....)

### ISSUE THREAD

**Issue by WTDuck** [ElemeFE/element#11290]
### Existing Component
Yes

### Component Name
InputNumber

### Description
Let's say you need to properly specify the unit of a data (lb, kg, cm...)
Why not implement something like the input slot of Input component ?

https://stackoverflow.com/questions/29661058/how-do-i-add-text-based-units-like-lbs-floated-to-right-inside-of-an-input-ele

**Comment by leslieSie** [comment]
I am work it, It is a very well feature

**Comment by leslieSie** [comment]
this is no a problem.
you can write the specify unit outside the input component and do it very simple.

**Comment by WTDuck** [comment]
I was thinking including the unit like a [input-group](https://getbootstrap.com/docs/4.0/components/input-group/)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
