### ISSUE TITLE
[Bug Report] Paginator calculates the total page inadequately when you specify total

### ISSUE THREAD

**Issue by germanp** [ElemeFE/element#11299]
### Element UI version
2.3.9

### OS/Browsers version
Manjaro Linux / Chrome 66

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Check the queantity of pages

Here is the line that is doing the calculation:
https://github.com/ElemeFE/element/blob/66c7b3cfc17b487e1a1c4015ae4325eb540d9957/packages/pagination/src/pagination.js#L368

It should use Math.floor instead of Math.ceil

### What is Expected?
For 44 records should show 4 pages

### What is actually happening?
It is showing 5 pages.

**Comment by Leopoldthecoder** [comment]
Page 1: 1st record to 10th record
Page 2: 11th record to 20th record
Page 3: 21st record to 30th record
Page 4: 31st record to 40th record
Page 5: 41st record to 44th record.
