### ISSUE TITLE
Datepicker: 当给一个初始值，type="datetimerange"时，日历视图并没有显示到初始值的日期，而是当前月 

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1129]
当给一个初始值时，日历视图并没有显示到初始值的日期，而是当前月
`time: ["2015-10-05 16:00:00", "2015-10-08 16:00:00"]`
`<el-date-picker
	v-model="time"
        type="datetimerange"
	style="width:350px">
</el-date-picker>`

**Comment by Kingwl** [comment]
为啥我这里是好的。。http://jsfiddle.net/api/post/library/pure/

**Comment by LabiKyo** [comment]
同样遇到了这个bug。

@Kingwl 你给的地址是错的

**Comment by wendysun0315** [comment]
type ="daterange"时同样有此问题,给了默认时间界面上没显示
![image](https://cloud.githubusercontent.com/assets/20597145/20548792/866bba1c-b161-11e6-96a8-cdd8a3125001.png)

**Comment by ivan403704409** [comment]
@QingWei-Li   这个bug貌似在v1.0.4还没修复 [demo](http://jsfiddle.net/wpnka5sd/)

**Comment by reverland** [comment]
怎么加到1.1.0里了，这个要重构么

**Comment by QingWei-Li** [comment]
@reverland 改动可能会有点大

**Comment by reverland** [comment]
1.1.0计划什么时候，1.0.5下一个么？@QingWei-Li 

要是还要一段时间我可以先patch(魔改)下。。

**Comment by Leopoldthecoder** [comment]
@reverland 你先魔改吧，1.1.0 还有几个新组件要做。

**Comment by reverland** [comment]
@Leopoldthecoder 关注有啥新组件

**Comment by DreamFox** [comment]
根据1.0.6的修复的话，没设置初始值或者初始值是null，会变成1970-1-1的日期，这样反而体验不好了。如果没有初始值或者初始值是null，期望默认还是按当前月份展示吧？

**Comment by QingWei-Li** [comment]
@DreamFox http://jsfiddle.net/peybccdv/ 不，null 的话就是什么都没有（空的输入框）

**Comment by DreamFox** [comment]
不好意思，又确认了一下。我是用的daterange模式，然后初始化为dateRange: [null, null]。这样的情况下，我的两个日期表默认值是1970年，但是如果dateRange: null的话，就默认是当前月了。然后我初始化dateRange: [new Date(), new Date()]也可以默认是当月，但是鼠标hover到X的时候就突然变成了1970年。1.0.6版本。 @QingWei-Li 应该也算是bug。但我目前可以先初始化为null。

**Comment by DreamFox** [comment]
现在daterange点X的时候，初始化会变成1970年，这个应该是必现的。不论我初始化的v-model是什么值都是这样。@1.0.6。

**Comment by QingWei-Li** [comment]
@DreamFox 是的 hover 到 icon 上会改变值这个问题发完 1.0.6 后我也发现了 😂，初始值是数组的问题我下版本修复

**Comment by DreamFox** [comment]
@QingWei-Li 嗯，官网文档上的daterange的case也会点X的时候变成1970年，应该不是我写的问题。期待下次更修复。

**Comment by khh8023lyf** [comment]
How do you implement the today with datepicker?
![image](https://user-images.githubusercontent.com/33194038/53463333-8e0e3a00-3a81-11e9-9b65-9a6621a84c6f.png)
@wendysun0315

**Comment by khh8023lyf** [comment]
![image](https://user-images.githubusercontent.com/33194038/53463402-c281f600-3a81-11e9-98c2-c59a82ad82b4.png)
@wendysun0315
