### ISSUE TITLE
How [Feature Request] adds components

### ISSUE THREAD

**Issue by Webjiacheng** [ElemeFE/element#11306]
### Existing Component
否

### Component Name
无

### Description
由于风格的不一致，所以导致需要定制化组件，请问下该如何实现在原有的基础上新增组件呢

**Comment by jikkai** [comment]
如果是样式上的定制，可以直接覆盖 css 或者通过[自定义主题](http://element.eleme.io/#/zh-CN/component/custom-theme)实现。
如果是功能上的定制，可以借用一些已有的样式 class，然后自行封装或者开发组件。
这类特殊需求见仁见智，建议根据自身业务需求制定二次开发策略。
