### ISSUE TITLE
How can [Feature Request] element-ui and nuxt open the function of SSR?

### ISSUE THREAD

**Issue by KoyoDevil** [ElemeFE/element#11308]
### Existing Component
是

### Component Name
el-table

### Description
你好，我在组件里写了这一段代码，因为我用nuxt的，我希望访问页面的时候的页面是渲染好的html，而不是数据在js里面的，首次的数据是我从父组件传进来的数据，请问怎么个写法才能让他直接渲染出来的？

------我的代码------
<template>
  <div class="dccon">
    <div class="dccon_datu sea_re_datu" id="dccon_datu" style="overflow: hidden; display: block;margin-top: 10px">
      <el-table
        v-loading="loading"
        :data="LocalDetailDataInfo.DataList"
        style="width: 100%"
        border>

        <el-table-column
          v-for="column in LocalDetailDataInfo.ColumnList"
          :label="column.label"
          :prop="column.prop"
          :key="column.label">
        </el-table-column>
      </el-table>
      <div style="margin:12px auto;width: 400px;">
        <el-pagination
          background
          layout="prev, pager, next"
          @current-change="handleCurrentChange"
          :current-page="currentPage"
          :total="1000">
        </el-pagination>
      </div>
    </div>
  </div>
</template>
<script>
  import axios from 'axios'

  export default {
    props: ['DetailDataInfo'],
    data: function () {
      return {
        pagesize: 10,
        currentPage: parseInt(this.DetailDataInfo.CurrentPage),
        loading: false,
        LocalDetailDataInfo: this.DetailDataInfo,
        AppId: this.DetailDataInfo.AppId
      }
    },
    methods: {
      //页码变更
      handleCurrentChange: function (val) {
        this.currentPage = val;
        this.loadData(this.currentPage, this.pagesize);
      },
      async loadData(currentPage, pagesize) {
        axios.get(__BACKEND_URL__  'yuansj/detailinfo/getList?pageNumber='   currentPage  
          '&pageSize='   pagesize   '&id='   this.AppId)
          .then((res) => {
            this.LocalDetailDataInfo = res.data.Result
          })
      },
    }
  }
</script>

----查看页面源代码----

......<script type="text/javascript">window.__NUXT__={"layout":"default","data":[{"DetailBaseInfo":{"DetailIntroduce":"业内知名火锅品牌","AppId":"710c78b783af921174b0b08bd29600ab","DataTitle":"知名火锅品牌"},"DataList":[{"b5894313c2d9cc88561f8cdc7071f9f5":"028-87714666,87714555","34e314a145c46767b385b84de707300c":"http:\u002F\u002Fwww.makong.cn\u002F","4e8713492666705f8a0e2ecb87f91157":"麻辣空间MOTSPAGE","d4b097041df68c34677c2aaecf9ad30d":"四川麻辣空间餐饮管理有限公司","e064945990dc95823913a318f2251dba":"成都市高新区交子大道88号1栋12层1205号、1206号、1207号、1208号"},{"b5894313c2d9cc88561f8cdc7071f9f5".........

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
