### ISSUE TITLE
The content of [Bug Report] dialog can be a component. When you write another dialog in the component, there will be background coverage.

### ISSUE THREAD

**Issue by xiongxt** [ElemeFE/element#11302]
### Element UI version
2.3.9

### OS/Browsers version
win10/ chrome 65.0.3325.146

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1952/](https://jsfiddle.net/mmx38qxw/1952/)

### Steps to reproduce
点击click me即可出现

### What is Expected?
正常弹出dialog

### What is actually happening?
第二层dialog被第一层背景覆盖

**Comment by Leopoldthecoder** [comment]
http://element-cn.eleme.io/#/zh-CN/component/dialog#qian-tao-de-dialog

**Comment by xiongxt** [comment]
虽然这样的用法有点傻逼，但我确实遇到了，dialog内是一个组件，组件内有个按钮去弹出另外一个dialog，如果把dialog提出来做成两个dialog同级，就不会出现问题，但是会多写很多传递消息的代码

**Comment by xiongxt** [comment]
谢谢，看文档没仔细
