### ISSUE TITLE
[Bug Report] when $loading with dialog first time open callback, the, open,

### ISSUE THREAD

**Issue by wfesorg** [ElemeFE/element#11309]
### Element UI version
2.3.8

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1953/](https://jsfiddle.net/mmx38qxw/1953/)

### Steps to reproduce
打开dialog  open回调触发$loading

### What is Expected?
打开dialog  open回调触发$loading

### What is actually happening?
$loading无法遮住dialog

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/1954/
