### ISSUE TITLE
[Feature Request] combine selection using shift key modifier

### ISSUE THREAD

**Issue by sotaan** [ElemeFE/element#11316]
### Existing Component
Yes

### Component Name
el-table

### Description
When user shift clicked on a checkbox, it should combine previous selection with all intermediary lines selected.
This feature is very trivial, you have it in every OS and web apps with data tables.

**Comment by leslieSie** [comment]
It is seems like a simple problem that everybody can solve it quickly.But i think is not so easy.Because you must face many trouble in your research and development. Event though, I am interested in this feature.waiting and I prepare to do it.

**Comment by sotaan** [comment]
I try to implement that using provided events but it's not integrable: cell-click is not trigerred if you click on selection checkbox, I cannot bind a click event (native included) on `el-table-column, ...

**Comment by sotaan** [comment]
After reading the packages folder I think it might be doable from the library context yeah. The minimal implementation being that I can bind my own click event on a table-column

**Comment by jikkai** [comment]
ref #11993
