### ISSUE TITLE
[Feature Request] requests all options similar to dropdown in one direction.

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#11315]
### Existing Component
是

### Component Name
Select, Cascader, TimePicker, DatePicker, DateTimePicker, ColorPicker

### Description
请求维持Dropdown组件继承性，或者类似继承性特征， 例如
placement 这个选项

没仔细看源码， 不知道是不是调用了 Dropdown 这个组件去展开内容。

但是我在实际应用中有2个场景突然涉及到这些组件的 Dropdown 弹出方向的需求。

需求场景是出现在当有虚拟键盘弹出来的时候页面容器会被扩大， 例如你一个 Select 刚好在文档底部的时候， 因为虚拟键盘的出现， 这个dropdown 就直接往下拉了。

这估计很难去判断， 所以我希望能给出一个  placement 的参数 去让开发者选择 auto 或者写死 弹出方向。

另外一个请求： TimePicker ， DatePicker ， DateTimePicker 这些能不能 选择弹出的方式是 dropdown 还是 modal ， 还是 插入到一个 vNode  / DOM 容器里？

例如 portal-vue 这个插件的方式。

**Comment by ziyoung** [comment]
- 是在移动端使用 Element 吗？Element 对移动端设备支持不太好。
- 包含 Dropdown 的这些组件都使用了 vue-popper 这个 mixin。你可以直接设置 placement 这个参数。
- portal-vue 这个库看起来很不错。我们也在考虑在项目中使用它。
