### ISSUE TITLE
v1.0.1编译CSS出错

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1131]
`import ElementUI from 'element-ui'`
`import 'element-ui/lib/theme-default/index.css'`

`Invalid CSS after "...t:calc(1 / 24 *": expected expression (e.g. 1px, bold), was "$(i) * 100) %}.el-c"`

**Comment by soliury** [comment]
我也遇到这个错误，应该补发一个新版本吧，这样一直1.0.1不能用。。。。

**Comment by Leopoldthecoder** [comment]
今天就发

**Comment by soliury** [comment]
ok，

**Comment by QingWei-Li** [comment]
fixed via https://github.com/ElemeFE/element/pull/1134
