### ISSUE TITLE
[Bug Report] Selecting a date or time with mouse resets tabIndex

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#11317]
### Element UI version
2.3.9

### OS/Browsers version
Windows 10/Chrome- latest

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/7rkvvmw1/](https://jsfiddle.net/7rkvvmw1/)

### Steps to reproduce
Tab into the date and/or time field
Select a date using the mouse
Hit tab

### What is Expected?
The focus to go to the next field

### What is actually happening?
The current tabIndex gets reset

**Comment by leslieSie** [comment]
## It is an interesting case.Because if you select the the date or time field then you will unfocus the input where in the page. if you want to reach your expect that you can write a function bind on change event make cursor after you select.

**Comment by ChuckFields** [comment]
@leslieSie I've created a solution based on your comment here: [https://jsfiddle.net/amoafc0f/](https://jsfiddle.net/amoafc0f/).  On change, you just need to call:
`      	this.$refs.datePicker.focus();`
`        this.$refs.datePicker.pickerVisible = false;`
I'm wondering if this should be the default behavior of this component though.

**Comment by leslieSie** [comment]
@ChuckFields  Good Job!!!!!

**Comment by ChuckFields** [comment]
Well.. my workaround doesn't always work. If you select a date in the picker that is already selected, the change function does not fire and the focus does not get reset. 
I should also note that this is an issue with the time picker as well.
