### ISSUE TITLE
[Bug Report] Holding arrow key down on radio button causes the whole screen to turn white

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#11318]
### Element UI version
2.3.9

### OS/Browsers version
WIndows 10/Chome- latest

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/7rkvvmw1/](https://jsfiddle.net/7rkvvmw1/)

### Steps to reproduce
Select one of the radio buttons using the mouse
Hold down the right or left arrow key for a few seconds

### What is Expected?
The values to bounce back and forth

### What is actually happening?
The whole screen gets overtaken by white circles until you let go of the arrow key.

**Comment by dpy1123** [comment]
interesting...

**Comment by leslieSie** [comment]
Demo Link is lost and I dont't know what you say

**Comment by gterras** [comment]
Can confirm on Linux/Chrome latest (firefox behave correctly though). 

The culprit seems to be `span.el-radio__inner::after` that keeps growing.
