### ISSUE TITLE
[Bug Report] Weird behaviour when typing Chinese and there is a timer to update UI

### ISSUE THREAD

**Issue by bitjjj** [ElemeFE/element#11310]
### Element UI version
2.3.8

### OS/Browsers version
Mac OS / Chrome 66

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/bitjjj/ogszk8g2/](https://jsfiddle.net/bitjjj/ogszk8g2/)

### Steps to reproduce
1. slowly input Chinese in input area
2. sometimes you will see Chinese word will disappear automatically

### What is Expected?
Input Chinese word correctly

### What is actually happening?
Sometimes word will disappear automatically.

Checking different version code of ElementUI, I find this issue will happen after using composition event in Input component. This issue will not happen in Element UI version 2.0.5

**Comment by leslieSie** [comment]
I am do it

**Comment by Leopoldthecoder** [comment]
Fixed in #11235

**Comment by leslieSie** [comment]
@Leopoldthecoder 你太牛叉了

**Comment by Leopoldthecoder** [comment]
@leslieSie 没有，是之前一位社区开发者修复的。

**Comment by leslieSie** [comment]
@Leopoldthecoder 留几个bug给小弟修一修，你们的速度这么快。拼不过
