### ISSUE TITLE
[Bug Report] when using the transform: scale attribute, the tooltip location of the table component is inaccurate.

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#11329]
### Element UI version
2.3.9

### OS/Browsers version
windows10 / chrome 67

### Vue version
2.5.10

### Reproduction Link
[https://codesandbox.io/s/o4w53yv29q](https://codesandbox.io/s/o4w53yv29q)

### Steps to reproduce
不全屏显示浏览器时，用鼠标移动到省略文字（地址栏）上面，看到tooltip展示的位置明显偏移了。

### What is Expected?
tooltip显示的位置在鼠标触发的省略号文字的上面。

### What is actually happening?
tooltip展示的位置明显偏移了
![image](https://user-images.githubusercontent.com/8147202/40485367-e738afa6-5f90-11e8-82bc-64c0a8b5531f.png)

**Comment by ziyoung** [comment]
不是 bug。虽然你给元素设置了 transform: scale(xx)，但是元素本身的宽度或者高度并没有变化。getComputedStyle 并无法计算出 transform 之后的宽度或者高度。看看这个小例子：https://jsfiddle.net/zhiyang/Ln09c6r0/

**Comment by fengyun2** [comment]
有什么办法解决么？

**Comment by ziyoung** [comment]
不用 transform 。如果觉得要展示信息过多，我觉得可以使用[固定列](http://element-cn.eleme.io/#/zh-CN/component/table#gu-ding-lie)。

**Comment by fengyun2** [comment]
@ziyoung 我们的产品需要把网站做成全自适应（用到了transform属性），其中有一块的table宽度固定了为300px, 列数并不多，但是某列内容比较多，内容过多时，需要鼠标移过时，出现省略的部分。

**Comment by ziyoung** [comment]
@fengyun2 栅格化应该是一种更好的选择。element-ui 也提供了[响应式布局](http://element-cn.eleme.io/#/zh-CN/component/layout#xiang-ying-shi-bu-ju)。

使用 transform 的话，问题还是挺多的。假设一段文本的 font-size: 12px，再 scale(0.5)，那人还能看清楚字吗？

**Comment by fengyun2** [comment]
@ziyoung 我们的产品是全屏百度地图以及在上面放置table展示数据

**Comment by fengyun2** [comment]
@ziyoung 这时候tooltip放在父元素下方可能可以解决这个问题吧（利用定位）？但是文档没有提供tooltip是否是插入到body元素上还是父元素下吧？

**Comment by ziyoung** [comment]
@fengyun2 这样试试？
```
<tool-tip :append-to-body="false"></tool-tip>
```

**Comment by fengyun2** [comment]
@ziyoung 我说的是集成在table中的tooltip的配置参数，而不是单独的tooltip。

**Comment by jikkai** [comment]
ref 一下 #11367
