### ISSUE TITLE
[Bug Report] el-input bug,type="number",still can input char 'e'

### ISSUE THREAD

**Issue by jt-lion** [ElemeFE/element#11324]
### Element UI version
2.3.9

### OS/Browsers version
chrome 66.0.3359.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/friskjt/6dunv01m/3/](https://jsfiddle.net/friskjt/6dunv01m/3/)

### Steps to reproduce
just input:111eee

### What is Expected?
111

### What is actually happening?
111eee

**Comment by jikkai** [comment]
This is not a bug, native input also has the same behavior. 
You can use [InputNumber](http://element.eleme.io/#/en-US/component/input-number) instead of it.

**Comment by mccxiv** [comment]
Should we perhaps reopen this? In native inputs, `type="number"` restricts characters: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Comment by woren951** [comment]
@jikkai its input field with type "Number" and type of all values must be "Number"! User is not allowed to record into this field string and other text chars.

**Comment by subdance** [comment]
> This is not a bug, native input also has the same behavior.
> You can use [InputNumber](http://element.eleme.io/#/en-US/component/input-number) instead of it.

So in input-number cpmponent you mentioned, we can still type characters in that input 'number' field... Isn't it a bit wierd？

**Comment by Johnny-Zhuravlev** [comment]
The problem is actual yet(
