### ISSUE TITLE
[Feature Request] table pagination filter

### ISSUE THREAD

**Issue by wangcongyi** [ElemeFE/element#11321]
### Existing Component
是

### Component Name
table / pagination 

### Description
table 组件与 pagination 组件 组合起来使用，在table filter过程中 只是当前 page 进行了filter ，并没有在全部 data 中进行 filter。
造成各个 page 条目不一样的情况

**Comment by Leopoldthecoder** [comment]
如果需要 filter 全部条目，请使用 `filter-method`。
