### ISSUE TITLE
[Feature Request] el-tooltip cannot display multiple lines when the text is stored in a variable

### ISSUE THREAD

**Issue by giantpoplar** [ElemeFE/element#11327]
### Existing Component
是

### Component Name
el-tooltip

### Description
same as the issue title

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by Simill** [comment]
I am having this issue still.

Versions:
Electron 2.3.4
Vue: 2.5.16
Browser: Chrome 67
OS: Win 10 Pro

I can reproduce this in a [JSfiddle](https://jsfiddle.net/eywraw8t/171293/)
