### ISSUE TITLE
[Bug Report] when I use V-IF switch date picker, the picker modal position is wrong

### ISSUE THREAD

**Issue by Joshwoooooooooooooooooooooooooooooooong** [ElemeFE/element#11339]
### Element UI version
2.3.7

### OS/Browsers version
 66.0.3359.181(official version) （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/vuo6Lg0a/1/](https://jsfiddle.net/vuo6Lg0a/1/)

### Steps to reproduce
I create a button, use v-if control the picker 1 and picker 2 is show or not,default the picker 1 is show, when I click the button, it will show the picker 2.
actually situation: 
step 1. click the picker, picker modal is normal position
step 2. click the button, show the picker 2
step 3. click the picker, picker modal is wrong position

### What is Expected?
when I do the step 3, the picker modal position is normal.

### What is actually happening?
when I do the step 3, the picker modal position is wrong.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/vuo6Lg0a/2/
