### ISSUE TITLE
[Bug Report] Mixed Inputs Appended & Prepended Buttons Style Issue

### ISSUE THREAD

**Issue by NoahCardoza** [ElemeFE/element#11338]
### Element UI version
0.1.0

### OS/Browsers version
Mac / Chome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Just run the code in the provided link.

### What is Expected?
A red button on either side of the text input.

### What is actually happening?
No style is being applied. The class is there but it is overridden. However, if you apply the class to the parent div, it looks fine.

**Comment by Leopoldthecoder** [comment]
Because `<el-button>` in prepend and append slots has its default styles. If you need apply your own style, make sure its CSS selector has higher priority than the default.
