### ISSUE TITLE
[Bug Report] checkbox component true-label/false-label parameter cannot set number type, only support string type.

### ISSUE THREAD

**Issue by harryliuy** [ElemeFE/element#11337]
### Element UI version
2.3.9

### OS/Browsers version
chrome 版本 66.0.3359.181（正式版本） （32 位）

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1960/](https://jsfiddle.net/mmx38qxw/1960/)

### Steps to reproduce
选中checkbox,我想要获取number类型的数据，但是只能获取到string类型，而官网显示 true-label/false-label是支持number类型的
http://element-cn.eleme.io/#/zh-CN/component/checkbox

### What is Expected?
按照官网显示，支持 string/number 类型，不仅是支持string

### What is actually happening?
按照官网显示，支持 string/number 类型

**Comment by jikkai** [comment]
https://jsfiddle.net/mmx38qxw/1961/
