### ISSUE TITLE
When [Bug Report] touches the form with touchpad, the movement of the head and the dislocation of the data move.

### ISSUE THREAD

**Issue by Grewer** [ElemeFE/element#11334]
### Element UI version
2.3.9

### OS/Browsers version
mac OS 10.12.4 / Chrome  61.0.3163.79（正式版本） （64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/grewer/jaygkn4o/](https://jsfiddle.net/grewer/jaygkn4o/)

### Steps to reproduce
鼠标移入表格,使用触摸板左右滑动,会发现表头的移动会有问题
![截屏](https://grewer.github.io/dataSave/table-scroll.gif)

### What is Expected?
滑动正常

### What is actually happening?
滑动速度不同,位置错位

**Comment by Leopoldthecoder** [comment]
表头与表格体是通过事件一起移动的，会有一定延迟。
