### ISSUE TITLE
[Feature Request] Form validation affects multiple controls in a form item

### ISSUE THREAD

**Issue by AshinLee** [ElemeFE/element#11332]
### Existing Component
是

### Component Name
Form

### Description
If I add a selection box and input box to the form item, when the form is verified, I just want the style of the input box to change.

**Comment by Leopoldthecoder** [comment]
Please elaborate. Use Chinese if you prefer.

**Comment by AshinLee** [comment]
表单进行验证，如果一个表单项中有不同的控件例如下拉框和输入框，我在这边添加验证，判断输入框的值是否为空，验证通过或者不通过边框样式会显示绿色或者红色，能否只限定输入框的颜色改变，而不是在同一个表单项的控件的颜色都改变 @Leopoldthecoder

**Comment by jikkai** [comment]
@AshinLee 这对绝大多数用户来说并不是一个常见需求，定制化的特殊需求可以通过覆盖 css 或其他手段来 hack 实现

**Comment by AshinLee** [comment]
好的 感谢 @Leopoldthecoder @jikkai
