### ISSUE TITLE
[Bug Report] Can't remove body's class: el-popup-parent--hidden while using messageBox twice

### ISSUE THREAD

**Issue by VanFangbo** [ElemeFE/element#11341]
### Element UI version
2.3.9

### OS/Browsers version
MacOS chrome 66.0.3359.181

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1962/](https://jsfiddle.net/mmx38qxw/1962/)

### Steps to reproduce
1.Using this.$confirm() to alert a messageBox (set the lockScroll as true)
2.User click the confirm/cancel button , receive promise callback
3.Then use another this.$confirm() to alert an other messageBox (set the lockScroll as true)
4.close the last messageBox, the body can't scroll. Find that the body still has a class: el-popup-parent--hidden, it's style is "overflow: hidden"
5.remove the class : el-popup-parent--hidden , the body can scroll.

### What is Expected?
need to scroll the body while using the messageBox twice

### What is actually happening?
can't scroll

**Comment by VanFangbo** [comment]
To fix it right now, I use setTimeout to avoid this bug.

**Comment by VanFangbo** [comment]
I use setTimeout to avoid this bug

**Comment by leslieSie** [comment]
show me you code

**Comment by leslieSie** [comment]
@VanFangbo

**Comment by VanFangbo** [comment]
@leslieSie 代码是公司项目的不好透露。看这个吧：https://jsfiddle.net/mmx38qxw/1962/ 。我也是类似于这么使用的。而且这个代码也出了同样的问题

**Comment by dgroh** [comment]
This also happens for `Dialog` component when two are open at the same time
