### ISSUE TITLE
[Bug Report] Can't see the messageBox while using this.$confirm twice

### ISSUE THREAD

**Issue by VanFangbo** [ElemeFE/element#11344]
### Element UI version
2.3.9

### OS/Browsers version
iPhone Safari 11.3

### Vue version
2.5.13

### Reproduction Link
open it in iPhone Safari:
[https://jsfiddle.net/mmx38qxw/1963/](https://jsfiddle.net/mmx38qxw/1963/)

### Steps to reproduce
1.Using this.$confirm() to alert a messageBox (set the lockScroll as true)
2.User click the confirm/cancel button , receive promise callback
3.Then use another this.$confirm() to alert an other messageBox (set the lockScroll as true)
4.The second messageBox can't display on screen. It flashed then disappear. But, I put a textarea in the msgBox, it can also be entered.

### What is Expected?
show the second messageBox in right way.

### What is actually happening?
disappear

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

**Comment by JeryZeng** [comment]
this issue occur in mac safari also

**Comment by yytt968** [comment]
这个问题也发生在Mac Safari中
