### ISSUE TITLE
[Bug Report] el-tree, lazy mode, data.children object

### ISSUE THREAD

**Issue by abernov** [ElemeFE/element#11346]
### Element UI version
2.3.9

### OS/Browsers version
win10 Chrome Version 66.0.3359.139 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/abernov/bskwqb3e/](https://jsfiddle.net/abernov/bskwqb3e/)

### Steps to reproduce
1. Expand all nodes
2. Click on node "region"
3. Click button "Show current node", see that "node.data" object does not have "children"
4. Click button "Append node to current"
5. Click button "Show current node", see that "node.data" object has "children" but only 1 item!

### What is Expected?
"node.data" object  does not have "children"
or
has 3 children and on step 3 has 2 children

### What is actually happening?
on step 3 - no children
on step 5 - only one child!

**Comment by ziyoung** [comment]
Yes, it is indeed the case. If you want to get the children of tree node, use `node.childNodes` rather than `node.data`.

**Comment by shopnb1** [comment]
这个问题没有被解决吧？如果他有子项里面有isLeaf: false,他append children数据,这个时候数据是不会动态刷新的
