### ISSUE TITLE
[Bug Report] unit test has an international I18N report error.

### ISSUE THREAD

**Issue by mgbq** [ElemeFE/element#11342]
### Element UI version
2.3.9

### OS/Browsers version
1.9

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/Molunerfinn/vue-koa-demo/issues/32](https://github.com/Molunerfinn/vue-koa-demo/issues/32)

### Steps to reproduce
你好，我参考了element test util.js ，我是这样引入i18n的
import i18n from '@/lang'
Vue.use(Element, {
size: 'medium', // set element-ui default size
i18n: (key, value) => i18n.t(key, value)
})

可是它报错了 信息为 ERROR LOG: TypeError: undefined is not an object (evaluating 'i18n._t')
改成
import i18n from '@/lang'
Vue.use(i18n) 也是报这个错，百忙中求解答

### What is Expected?
期望正常test

### What is actually happening?
ERROR LOG: TypeError: undefined is not an object (evaluating 'i18n._t')

**Comment by mgbq** [comment]
thanks

**Comment by jikkai** [comment]
根据你给出的片段感觉是用法有问题，请仔细阅读[文档 - 国际化](http://element.eleme.io/#/zh-CN/component/i18n#guo-ji-hua)获得帮助。如果确认不是用法问题而是可复现的 bug，请整理一个最小化可复现 demo。
