### ISSUE TITLE
[Feature Request] change type attribute for buttons

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#11359]
### Existing Component
Yes

### Component Name
button

### Description
There is currently no way to set type="submit" for buttons. type should not be used for buttons. This also disables the native form submit.

**Comment by jikkai** [comment]
You can use `native-type="submit"` instead of it.

**Comment by atilkan** [comment]
@jikkai 
Thanks. But again i think it is better not to hijack native type.
