### ISSUE TITLE
[Bug Report] install element ui show error 'async-validator' not found

### ISSUE THREAD

**Issue by deltacat** [ElemeFE/element#11356]
### Element UI version
2.3.9

### OS/Browsers version
centos7

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
npm i element-ui

### What is Expected?
element ui installed correctly

### What is actually happening?
cannot complete install.
error message:

npm ERR! code E404
npm ERR! 404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

**Comment by leslieSie** [comment]
It is maybe sever port was taken up.you can close your computer then try again.. if neither, you can change npm to another sunch as yarn,cnpm and so on. @deltacat

**Comment by paritoshmmmec** [comment]
I am also facing same problem.  it is not related to computer for sure. I am on windows.

**Comment by Leopoldthecoder** [comment]
I found this https://github.com/yiminghe/async-validator/issues/105 , which leads me to https://github.com/npm/registry/issues/329 . Looks like an npm issue.

For now you can use a different npm mirror, as suggested [here](https://github.com/yiminghe/async-validator/issues/103#issuecomment-392250149). And wait for npm to repair it.
