### ISSUE TITLE
[Bug Report], when multiple columns are hidden, top and left are 0

### ISSUE THREAD

**Issue by WGL878420** [ElemeFE/element#11354]
### Element UI version
0.1.0

### OS/Browsers version
chrome 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/zctya/pL0cwd3k/1/](https://jsfiddle.net/zctya/pL0cwd3k/1/)

### Steps to reproduce
When I click on options to form multiple columns show hidden screen box top and left to 0, do not have this problem before have after upgrade, just like you to modify this part but many show hidden form a column to obtain the background data rendering filter box went flying.

### What is Expected?
The filter box can still be under the filter field when a column is hidden multiple times in the table. Can I control its top and left by myself

### What is actually happening?
The actual filter box has an in-line style top and left of 0

**Comment by jikkai** [comment]
Already fixed in 2.3.0 and Element 1.x is no longer maintained.
