### ISSUE TITLE
[Bug Report] Input field doesn't work in google map search box while we validate it

### ISSUE THREAD

**Issue by hlaporthein** [ElemeFE/element#11355]
### Element UI version
2.3.9

### OS/Browsers version
MacOS High Sierra / Any Browsers

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/hlaporthein/6vh1670w/6/](https://jsfiddle.net/hlaporthein/6vh1670w/6/)

### Steps to reproduce
https://jumpshare.com/v/tab1oKO78uzBx0nlQyBU

### What is Expected?
I wanna input field to be ok with google map search box while we validate it.

### What is actually happening?
Input field doesn't work with google map search box while we are validating input. If no validation for field, it works. So, I believe there would be an error in validating trigger. Here is the screencast of the problem https://jumpshare.com/v/tab1oKO78uzBx0nlQyBU

**Comment by Bounty31** [comment]
Also when you select a google autocomplete result it doesn't get updated in the input v-model, I think it has to do with the fact that the Google Autocomplete API changes the input value directly and Vue/Element don't see the value update.

**Comment by jikkai** [comment]
Maybe you forget to set `model` for `el-form`.
https://jsfiddle.net/6vh1670w/7/

**Comment by hlaporthein** [comment]
Hi @jikkai , adding **el-form** doesn't solve the project. I have tested raw html input, it worked well. But, when I use el-input, it doesn't work

**Comment by Bounty31** [comment]
@jikkai try entering "Paris" and click on the result, it will not be set in the el-input v-model and you will see a flicker of the input's value. Any idea how to fix this?

**Comment by jikkai** [comment]
I created a demo: https://jsfiddle.net/6vh1670w/9/

Whatever you validate the input or not, you should set the input `v-model` by yourself.

**Comment by Bounty31** [comment]
@jikkai Ok this changes the `v-model` but the flicker is still there.
For example when you type "Paris" in the input move down with the down key and highlight the first result
- Right before you click or hit enter the input value will be "Paris Town Gali No 6, Batala Rd, Amritsar, Punjab 143001, Inde"
- When you select the result the input value will switch to "paris"
- Then the place_changed gets triggered and the input value is set correctly to "Paris Town Gali No 6, Batala Rd, Amritsar, Punjab 143001, Inde" again.

Is there a way to fix this using an el-input? If not maybe there is a way to make our own input and make the **el-form** rules check the custom input value with the form validation?

**Comment by Bounty31** [comment]
@jikkai Do you see the problem I am describing? To me it's not a complete solution if the user sees a flicker. Any idea on a suggested workaround?

**Comment by jikkai** [comment]
@Bounty31 
What about this https://jsfiddle.net/6vh1670w/47/

**Comment by jikkai** [comment]
@Bounty31 What about this https://jsfiddle.net/6vh1670w/48/

**Comment by Bounty31** [comment]
@jikkai That's better, I think with `v-model` instead of @change it's even simpler, see https://jsfiddle.net/y2z73Lw3/1/ also with the on result click changing the v-model

**Comment by IEfucker** [comment]
what if the filed element is ueditor or something but <input>
data and validation logic is right, but event does not fire when data changes
how to fire the validation
