### ISSUE TITLE
[Bug Report] el-table component's el-checkbox in filter panel cannot be checked.

### ISSUE THREAD

**Issue by FioneraGH** [ElemeFE/element#11368]
### Element UI version
2.3.7

### OS/Browsers version
MacOS 10.13.4 / Chrome 66.0.3359.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1. Clone the source code from https://github.com/ElemeFE/element
2. Use yarn to build the lib
3. import ElementUI from './element' // './element' is the path of lib which was built from source code.
4. Use filter in el-table, when I click the header, I cannot check the checkbox.
5. Console shows '$listener is readonly'.

### What is Expected?
Check the el-checkbox in el-table's filter panel correctly.

### What is actually happening?
Cannot check the box. just the 'isFocus' is set to true, 'isChecked' is false.

**Comment by FioneraGH** [comment]
链接是官方好用的代码，表述可能不太清楚，其实就是自己clone源码打包依赖后，table组件里的筛选选不中，控制台报'$attr/$listener is readonly'，如果有人遇到过帮助一下，谢谢

**Comment by jikkai** [comment]
我这里无法重现这个问题，请提供最小化可复现 demo

**Comment by FioneraGH** [comment]
我尝试写了个只有element的工程，发现不会出现这个问题。那这个应该是工程里配置的问题，因为把打包出来的文件放到node_modules/element-ui/里覆盖lib文件夹就不会出现这种状况，谢谢
