### ISSUE TITLE
[Bug Report] Server side render Maximum call stack size exceeded ui-dialog (vue 2.5.13)

### ISSUE THREAD

**Issue by slevp** [ElemeFE/element#11363]
### Element UI version
2.3.3

### OS/Browsers version
Ubuntu16.04 / IE9

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/6696585/40586625-3852fd70-61f7-11e8-89da-be1c178850d0.png)

![image](https://user-images.githubusercontent.com/6696585/40587022-73a946d6-61fc-11e8-9116-e90a991010a2.png)

vue: 2.5.13
element-ui: 2.3.3
nuxt: 1.4.0

I found some related issues（[Maximum call stack size exceeded](https://github.com/ElemeFE/element/issues?utf8=%E2%9C%93&q=Maximum call stack size exceeded)）, i restored vue to 2.5.13 but still prudence.

The issue could not be produced with examples or demos on [jsfiddle](https://jsfiddle.net/mmx38qxw/), it will product during 2 days when our production servers restart, so i did not new it on issue-generator(https://elementui.github.io/issue-generator), pls undenstand -, -

### What is Expected?
work regular

### What is actually happening?
not work

**Comment by Leopoldthecoder** [comment]
The reproduction demo doesn't have to be on jsfiddle. You can minify your project and upload it to GitHub. Please open a new issue with a reproduction.
