### ISSUE TITLE
[Feature Request] Much better support for Mobile

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#11375]
### Existing Component
Yes

### Component Name
All Eelement components

### Description
I think element-ui is freaking awesome. Probably one of the most well balanced UI frameworks out there. However, for mobile it really doesn't come out well at all.

Yes, I get that there is Mint-UI. Are they inter-operable? For that to work, the ability to detect media needs to massively improve in element-ui. Right now the `<el-col :xs="" ...>` is the only thing that works OK. The CSS `hidden-on-...` classes don't work for me.

As Mint-UI it looks nice, but I don't want to have to redevelop my app for mobile, good design these days is mobile first. Please see what can be done to make element-ui brilliant on mobile.

The biggest issue I am facing is responsiveness on fonts and then the CSS `hidden-on-...` don't work.

Thanks for the excellent work in element-ui. I've been using it since 1.x for the last year or so. Brilliant

**Comment by jikkai** [comment]
#4223
