### ISSUE TITLE
[Bug Report] IE11, clicking on the selection box of the select component, prompts the text to disappear and displays the hint of the cursor to be entered (so the non editable input box has the compatibility problem)

### ISSUE THREAD

**Issue by shudery** [ElemeFE/element#11377]
### Element UI version
2.3.9

### OS/Browsers version
windows

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/L3ufgbmr/](https://jsfiddle.net/L3ufgbmr/)

### Steps to reproduce
1、点击选择框

### What is Expected?
选择框placeholder提示文字不消失，不出现待输入的光标，不对用户造成可输入的误解

### What is actually happening?
选择框提示文字消失，出现提示可输入的光标

**Comment by ziyoung** [comment]
@shudery 给 `el-select` 设置 `filterable` 属性。https://jsfiddle.net/zhiyang/L3ufgbmr/3/
