### ISSUE TITLE
The [Bug Report] table adds show-overflow-tooltip, and there will be an empty misplaced tooltip on the 360 browser.

### ISSUE THREAD

**Issue by RootLoveWorld** [ElemeFE/element#11373]
### Element UI version
2.3.9

### OS/Browsers version
windows7 360安全浏览器9  版本号9.1.0.422

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/9sxeg7h3/](https://jsfiddle.net/9sxeg7h3/)

### Steps to reproduce
打开官网给的地址，修改下面两处就可以看到bug：      

<el-table-column prop="name" label="姓名" width="180" show-overflow-tooltip >
      </el-table-column>

 tableData: [{
            date: '2016-05-02',
            name: '',
            address: '上海市普陀区金沙江路 1518 弄'
          }]

### What is Expected?
表格单元格为空不应该出现tip提示。

### What is actually happening?
表格单元格为空出现tip提示，而且样式还是错位的。

**Comment by RootLoveWorld** [comment]
https://jsfiddle.net/9sxeg7h3/

**Comment by yezongyang** [comment]
谷歌老版本浏览器也有这种情况

**Comment by zackfly** [comment]
qq浏览器也有问题

**Comment by zackfly** [comment]
cellMouseEnter(row, column, cell, event) {
      if (!row[column.property]) {
        cell.innerHTML = '';
      }
    }

**Comment by zackfly** [comment]
我现在是这么特殊处理的
··
cellMouseEnter(row, column, cell, event) {
  if (!row[column.property]) {
    cell.innerHTML = '';
  }
}
··

**Comment by zackfly** [comment]
我现在是这么特殊处理的
cellMouseEnter(row, column, cell, event) {
  if (!row[column.property]) {
    cell.innerHTML = '';
  }
}

**Comment by zackfly** [comment]
还是希望element能修复这个问题

**Comment by ziyoung** [comment]
@jikkai 兼容性问题。问题应该是出现在下面这段代码里。
https://github.com/ElemeFE/element/blob/b799d2ec4dfe7a08cb42d510de5653c8165a3219/packages/table/src/table-body.js#L350-L353

**Comment by xiaoniezi** [comment]
Hope to be resolved

**Comment by pz25925** [comment]
希望修复

**Comment by chwech** [comment]
Hope to be resolved

**Comment by ziyoung** [comment]
在 pr #13152 修复了。
