### ISSUE TITLE
[Bug Report] Validation does not work in field with IF

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#11383]
### Element UI version
2.4.0

### OS/Browsers version
Google Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/kutmania/a409hg5s/3/](https://jsfiddle.net/kutmania/a409hg5s/3/)

### Steps to reproduce
1- Construct a form with a select field and two input fields;
2 - Show the first input or the second input according to select selection;
3 - Add validation in second input;

### What is Expected?
Mandatory field validation happens

If I remove the if from the second field, the validation happens

### What is actually happening?
The field is not validated.

**Comment by jikkai** [comment]
https://jsfiddle.net/a409hg5s/4/
