### ISSUE TITLE
ResetFields doesn't work when [Bug Report] dialog components are nested form forms.

### ISSUE THREAD

**Issue by haryzxw** [ElemeFE/element#11389]
### Element UI version
2.4.0

### OS/Browsers version
macos 10.13.4/Google Chrome 66.0.3359.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://codepen.io/zhengxiaowen/pen/MOKZaN?editors=0000](https://codepen.io/zhengxiaowen/pen/MOKZaN?editors=0000)

### Steps to reproduce
先点表格里的编辑按钮，关闭后，再点击新增按钮，form表单的值没有被清空

### What is Expected?
点击新增的时候，应该把之前编辑渲染的值清空

### What is actually happening?
先点击编辑按钮，再点击新增按钮的时候，form值没有被清空

**Comment by Leopoldthecoder** [comment]
`<el-form-item>` should have `prop` for `resetFields` to work: https://codepen.io/leopoldthecoder/pen/LrPKqm

**Comment by haryzxw** [comment]
已经加上prop  但是先点击编辑，再点击新增的时候 依旧没有清空。但是先点击新增按钮，再编辑，再新增又是正常的。

**Comment by haryzxw** [comment]
https://codepen.io/zhengxiaowen/pen/MOKZaN @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
看下我的 demo，可能需要 `nextTick` 一下

**Comment by haryzxw** [comment]
@Leopoldthecoder  ok！ 3q

**Comment by yiwuyu** [comment]
@Leopoldthecoder  https://jsfiddle.net/es5hfxvg/ 我也遇到了这个问题
