### ISSUE TITLE
[Feature Request] introduces the address of CDN through script tag, can't it be imported on demand?

### ISSUE THREAD

**Issue by dxvgef** [ElemeFE/element#11380]
### Existing Component
是

### Component Name
index.js

### Description
我通过CDN引用element-ui，但是也希望客户端的流量小点，想只用到几个组件，但发现只有引入index.js这个完整组件的方法？

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
