### ISSUE TITLE
The default value of the [Bug Report] Switch component has a BUG

### ISSUE THREAD

**Issue by Chocky99** [ElemeFE/element#11381]
### Element UI version
2.4.0

### OS/Browsers version
Windows10，Chrome 66 X64

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1964/](https://jsfiddle.net/mmx38qxw/1964/)

### Steps to reproduce
两个问题，两个步骤
1、第一个问题，打开页面，直接就可以看见。
2、第二个问题，需要设置active-value和inactive-value之后，再Run,就可以看见

### What is Expected?
在不设置Actice-value的时候，打开页面之后，Switch组件应该提供默认的值。而且应该提供期待的类型。

### What is actually happening?
1、Switch开关不能正常提供Number类型的值，
2、而且如果不设置active-value和inactive-value的话，打开页面之后默认的值直接就是undefined，
3、点击一下开关才会正常成为Boolean类型的值。
4、往往在用JSON的时候出现问题。尤其是服务端收到值之后的转换。

**Comment by jikkai** [comment]
1. demo 中绑定的值是 `string` 的 `100` 和 `0`；
2. 默认值的 `undefined` 是你在 data 中设置的。
以上两个问题均为 Vue 使用上的问题，请详细阅读 Vue 的文档。

附一个 demo：https://jsfiddle.net/mmx38qxw/1966/

**Comment by Chocky99** [comment]
谢谢你，我的错。
没有活学活用
