### ISSUE TITLE
[Bug Report] hi! Date-picker-bug

### ISSUE THREAD

**Issue by ppvy** [ElemeFE/element#11390]
### Element UI version
2.4.0

### OS/Browsers version
win10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
功能是 日、周、月的一个按钮点击切换 date-picker 组件进行相应改变选择日  选择 周 或选择月
当日比如在本月二十几号月底的时候  切换到月选择器 会变成下一个月的 可能是四舍五入人了
不能截图请原谅 谢谢~

### What is Expected?
按正常逻辑 比如日选择‘2018-5-28’  值是2018-05-28T16:00:00.000Z  然后点击月按钮切换到月的时候type=‘seek’  会变成五月 然后点四月的时候选择器是四月但是值会变成 ‘2018-03-31T16:00:00.000Z’

### What is actually happening?
...

**Comment by jikkai** [comment]
这个不是 bug，UTC 时间就是这样的，#1705

**Comment by yoonasy** [comment]
非常感谢~  very thanks~
