### ISSUE TITLE
[Feature Request] el-scrollbar, Should you add two attributes, hidden-x or hidden-y

### ISSUE THREAD

**Issue by iunfire** [ElemeFE/element#11391]
### Existing Component
是

### Component Name
el-scrollbar

### Description
el-scrollbar, Should you add two attributes, hidden-x or hidden-y.
when use el-scrollbar , the scrollbar will always show, and I hope, I can close a direction bar. 
---
是否能添加两个属性，隐藏-x或隐藏。
当使用el-scrollbar时，滚动条总是显示，我希望，我可以关闭一个方向栏。

**Comment by jikkai** [comment]
Scrollbar 组件目前仅为 Element 组件内部使用，不推荐在外部使用。
