### ISSUE TITLE
[Bug Report] has no response to the use of vue2.4.0 version of asynchronous assignment el-checkbox.

### ISSUE THREAD

**Issue by Mingscript** [ElemeFE/element#11405]
### Element UI version
2.4.0

### OS/Browsers version
WIN7/chrome63.0.3239.132

### Vue version
2.4.0

### Reproduction Link
[https://jsfiddle.net/ggg123456/5z97qg9L/](https://jsfiddle.net/ggg123456/5z97qg9L/)

### Steps to reproduce
使用异步取值并赋值给el-checkbox的时候，发现checkbox点击无反应，会出现边框。
一个表单 新增与编辑 公用
新增  没有问题
编辑  通过接口拿值 给checkbox 赋值。。。。出现点击无反应现象
部分 html  
<el-checkbox class="checkag-item" v-model="addObj.isprovinceCitiyDistrict" label=""></el-checkbox>
部分 js    

this.$store.dispatch('get_group_particular', updateObj.id).then((data)=>{
                        if(data && data.result){
                            let tempObj = data.result
          
  ......................
   this.addObj.isprovinceCitiyDistrict = tempObj.isprovinceCitiyDistrict == 1?true:false
  ......................
}})

                           

### What is Expected?
正常选中或者不选中

### What is actually happening?
不能显示选中，已选的也不能取消选中

**Comment by Mingscript** [comment]
我这边不太好写，可以给你一个链接https://segmentfault.com/q/1010000011649557
基本上跟这个问题差不多，但是我不太能理解这个人的解决方法
@jikkai 谢谢

**Comment by jikkai** [comment]
看上去像是使用上的问题。没有具体可复现 element 问题的 demo 很难定位问题并给予帮助，请谅解。

有可复现问题的 demo 的时候欢迎再打开 issue 😄
