### ISSUE TITLE
[Bug Report] change the selector component default icon

### ISSUE THREAD

**Issue by feng9217** [ElemeFE/element#11406]
### Element UI version
2.4.0

### OS/Browsers version
win10 / the lastest chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1979/](https://jsfiddle.net/mmx38qxw/1979/)

### Steps to reproduce
看了下官方源码
select中 使用的箭头是icon中的 el-icon-arrow-up
有没有什么slot让我修改这个icon 或者让我能把它替换成 el-icon-caret-top

### What is Expected?
修改默认的el-icon-arrow-up 或者让我能把它替换成 el-icon-caret-top

### What is actually happening?
文档内暂无说明

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by Zhang1051127659** [comment]
同遇到这个问题，现在来看，似乎是只能去改变源码去做到更改icon

**Comment by feng9217** [comment]
其实可以不用改变源码
我把默认的箭头定位到屏幕外了
然后再自己定位需要的样式箭头进来用
