### ISSUE TITLE
[Bug Report] has no response to the use of vue2.4.0 version of asynchronous assignment el-checkbox.

### ISSUE THREAD

**Issue by Mingscript** [ElemeFE/element#11404]
### Element UI version
2.4.0

### OS/Browsers version
WIN7/chrome63.0.3239.132

### Vue version
2.4.0

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
使用异步取值并赋值给el-checkbox的时候，发现checkbox点击无反应，会出现边框。
一个表单 新增与编辑 公用
新增  没有问题
编辑  通过接口拿值 给checkbox 赋值。。。。出现点击无反应现象
部分 html  
<el-checkbox class="checkag-item" v-model="addObj.isprovinceCitiyDistrict" label=""></el-checkbox>
部分 js    

this.$store.dispatch('get_group_particular', updateObj.id).then((data)=>{
                        if(data && data.result){
                            let tempObj = data.result
          
  ......................
   this.addObj.isprovinceCitiyDistrict = tempObj.isprovinceCitiyDistrict == 1?true:false
  ......................
}})

                           

### What is Expected?
正常选中或者不选中

### What is actually happening?
不能显示选中，已选的也不能取消选中

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
