### ISSUE TITLE
[Bug Report] 带有placeholder属性的el-date-picker控件在IE10\IE11下无法赋值的问题

### ISSUE THREAD

**Issue by newnewff** [ElemeFE/element#11407]
### Element UI version
2.4.0

### OS/Browsers version
WIN7 IE10 IE11

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
重现链接没有，代码很简单：
< body>
< div id="app">
	< el-date-picker v-model="data.DateValue4" ></el-date-picker>
	< el-date-picker v-model="data.DateValue5" ></el-date-picker>
	< el-date-picker v-model="data.DateValue5" placeholder="选择日期时间" ></el-date-picker>
< /div>

< /body>
< script>
var vm=new Vue({el:'#app',data:{data:{DateValue4:null,DateValue5:null}}});
$(function(){
	vm.$watch('data.DateValue4',function(val,oldval){
		vm.data.DateValue5=val;
	})
});
< /script>

在改变第一个控件的值时，在IE10 IE11下第三个控件值不会改变，将placeholder="选择日期时间" 去掉后正常。

### What is Expected?
修复

### What is actually happening?
修复

**Comment by jikkai** [comment]
IE11 下无法复现 https://jsfiddle.net/mmx38qxw/1981/

**Comment by han-daniel** [comment]
@jikkai 
       你好，我用IE11打开了你提供的链接https://jsfiddle.net/mmx38qxw/1981/，第三个带placeholder的框确实有问题，复现步骤如下：
1.页面打开后，直接点击第一个文本框，选择日期，第二个出现值，第三个不显示；点击第三个框，显示日期选择框，这时点击空白处，日期选择框隐藏，第三个显示值；
2.页面打开后，先点击一次第三个框，不用选择日期，然后点击空白处关闭日期选择框；之后再点击第一个框选择日期，此时第三个框的值会随着第一个框变动。

**Comment by jikkai** [comment]
@han-daniel https://jsfiddle.net/mmx38qxw/1983 看下这样有没有问题

**Comment by liwenda122** [comment]
太容易重现了 低级BUG  IE10 IE11都不行 ，这elment-ui的IE兼容性堪忧
