### ISSUE TITLE
When [Feature Request] el-switch is displayed in table, is it possible to change Ajax first according to the result of Ajax after Ajax?

### ISSUE THREAD

**Issue by miuqiang** [ElemeFE/element#11402]
### Existing Component
是

### Component Name
el-switch 

### Description
1、table里v-for循环出来的el-switch，在点击的时候改变model，是否能够先Ajax后，根据Ajax的结果来决定是否改变model的值。
2、现在的文字描述都放到label外面去了吗？

**Comment by jikkai** [comment]
这个感觉有点怪怪的，如果点击发起异步请求前如果没有给用户一个反馈的话，用户可能会认为没点击上，就会造成多次点击并发送请求。先讨论下看看？

**Comment by miuqiang** [comment]
恩，我主要是想用来做一个开关操作，比如禁用和启用用户。

**Comment by jikkai** [comment]
@miuqiang 先改变 switch 的数据，然后在 change 事件中捕获到开关为打开的时候发起请求，请求不成功则关闭开关，请求成功则保持原状。我觉得这样的交互思路可能会比较合理一些？

**Comment by jikkai** [comment]
类似场景可能比较少见，先关了，有后续意见可以继续讨论 😀
