### ISSUE TITLE
[Bug Report] table multilevel header and when show-summary is used, the rowspan problem of the total row is summed up.

### ISSUE THREAD

**Issue by smiledy** [ElemeFE/element#11414]
### Element UI version
2.3.9

### OS/Browsers version
mac chrome版本 66.0.3359.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/hz1uLsjq/1/](https://jsfiddle.net/hz1uLsjq/1/)

### Steps to reproduce
打开浏览器控制台，在Table含有多级表头时，并有show-summary合计行时，合计行的rowspan自动等于了表头的rowspan，虽然页面上不影响显示，但是如果导出该table到excel中，rowspan会影响显示，希望有参数能自己控制合计行的rowspan

### What is Expected?
希望合计行的rowspan可以有地方根据需求自行控制

### What is actually happening?
合计行的rowspan = 表头的rowspan

**Comment by jikkai** [comment]
在这样的场景下使用 [append slot](http://element.eleme.io/#/zh-CN/component/table#table-slot) 会比较合适
