### ISSUE TITLE
[Feature Request] Add getBottomCheckedNodes for tree

### ISSUE THREAD

**Issue by gaoshijun1993** [ElemeFE/element#11411]
### Existing Component
是

### Component Name
Tree

### Description
Hope tree select component could support getBottomCheckedNodes method, which will return the checked nodes which is not nessisarily leaf node in lazy load mode, but the loaded bottom node, for example: node 1-1-2 has been loaded, but it's isLeaf property is false, and I havn't load the children of it, so with this method I will get this node.

**Comment by ziyoung** [comment]
Tree 提供了许多[方法](http://element-cn.eleme.io/#/zh-CN/component/tree#fang-fa)。基于这些法，你可以根据业务需求来实现一些函数。作为一个 ui 库，我们倾向于提供一些更通用的方法。
