### ISSUE TITLE
[Bug Report] please not use onRemve / onChange ... as props ！ those attrs is interpreted as event by JSX syntax，therefore there's no way to pass these attrs

### ISSUE THREAD

**Issue by xiaoshude** [ElemeFE/element#11410]
### Element UI version
2.4.0

### OS/Browsers version
all

### Vue version
2.5.16

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
rt

### What is Expected?
rt

### What is actually happening?
rt

**Comment by jikkai** [comment]
I found this [PR](https://github.com/vuejs/babel-plugin-transform-vue-jsx/pull/126/files) from `babel-plugin-transform-vue-jsx`, it may solve your problem.
