### ISSUE TITLE
[Bug Report] Autocomplete suggestions popper covers input field

### ISSUE THREAD

**Issue by machinek56** [ElemeFE/element#11423]
### Element UI version
2.4.0

### OS/Browsers version
Android 6.0, Chrome 66

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1987/](https://jsfiddle.net/mmx38qxw/1987/)

### Steps to reproduce
1. Go to reproduction link
2. Open on Android Chrome
3. Start typing or simply focus on field autocomplete

It doesn't reproducing in JsFiddle, but reproducing in element.io docs and on my production site
http://element.eleme.io/#/en-US/component/input#autocomplete

### What is Expected?
I expect that popper not cover input field, and stay under virtual keyboard, like as in iOS Safari or JsFiddle example.

### What is actually happening?
It covers input field and i have to scroll page down to see field itself

**Comment by machinek56** [comment]
![image](https://user-images.githubusercontent.com/12989125/40744390-0826a120-645d-11e8-846a-c89df5df1ca0.png)

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

**Comment by machinek56** [comment]
@ziyoung what libraries are you suggest to use on mobile?

**Comment by ziyoung** [comment]
@machinek56 https://github.com/vuejs/awesome-vue#mobile-1

**Comment by chendatony31** [comment]
Nooooo...no... n....
