### ISSUE TITLE
[Feature Request] disabled form items can skip validation

### ISSUE THREAD

**Issue by pixelpaulaus** [ElemeFE/element#11428]
### Existing Component
Yes

### Component Name
form

### Description
form inputs that have validation on them still require to be TRUE even if disabled.
If a form item is disabled it should no longer require validation

**Comment by jikkai** [comment]
It's not a common use case, so we have no plan to add this support. 
But you can change validation rules of form when you disable the form item. 
https://jsfiddle.net/L87gpphj/
