### ISSUE TITLE
Nav menu open is error

### ISSUE THREAD

**Issue by qingwufengyang** [ElemeFE/element#11425]
### Element UI version
2.3.7

### OS/Browsers version
mac 10.16.6 / chrome 66.0.33559

### Vue version
2.5.16

### Reproduction Link
[http://jsfiddle.net/chenjunjun/hzfpyvg6/6060/](http://jsfiddle.net/chenjunjun/hzfpyvg6/6060/)

### Steps to reproduce
1.给menu菜单绑定ref="testMenu"
2.点击展开菜单
3.点击打开菜单， 使用this.$refs.testMenu.open('1');
4.结果报indexPath 没有找到，There is no expansion of the menu 
注意：经过测试发现是因为 加了collapse-transition="false" 不加就不会报错 

### What is Expected?
menu open

### What is actually happening?
There is no expansion of the menu

**Comment by jikkai** [comment]
先试下加个 `key` 能不能用
http://jsfiddle.net/hzfpyvg6/6061/

**Comment by qingwufengyang** [comment]
@jikkai  可以
