### ISSUE TITLE
[Feature Request] validateField, accept array of field names

### ISSUE THREAD

**Issue by pixelpaulaus** [ElemeFE/element#11429]
### Existing Component
Yes

### Component Name
form

### Description
it would be good to accept an array for field names for form.validateField if you wanted to validate more then 1 field but not the entire form.

**Comment by ziyoung** [comment]
Maybe the method name called `validateFields` is a bit better.

**Comment by ziyoung** [comment]
@pixelpaulaus the arguments of `validateField` are `prop` and `callback`. If the first argument is an array, we use the same callback for these fields. It seems not flexible.
