### ISSUE TITLE
[Bug Report] ClearValidate() does not work with modal

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#11422]
### Element UI version
2.4.0

### OS/Browsers version
Google Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/kutmania/sedsahwr/3/](https://jsfiddle.net/kutmania/sedsahwr/3/)

### Steps to reproduce
1 - Create a modal with a form inside
2 - Open the modal with a text inside the input
3 - Close and open the modal without text and no validation error messages

Note

I linked the `v-on:close` and use the method `this.$refs.data.clearValidate()`; to delete form text, but does not work;
If I initialize the variable `data = { name: ''}`, validation errors appear

### What is Expected?
The form text is deleted and no validation errors appear.

### What is actually happening?
The form text is not deleted.
the method `this.$refs.data.clearValidate()`; is not working;
See example in reproduction Link

**Comment by renatosistemasvc** [comment]
I understood the cause of the problem.
In my real case, the problem happens because I get the api data and assign the variable this way:

`this.data = response.data`

The vue can not see changes because the variable is overwritten. To solve the problem I'm associating item by array item. 

like this:

```
this.data.name = response.data.name
this.data.address = response.data.address

```
In this way the method `this.$refs.data.clearValidate() ` works well.
I'm closing the question.

**Comment by ziyoung** [comment]
The method `clearValidate` is used to clear validation message for all fields.

**Comment by renatosistemasvc** [comment]
@ziyoung 
You did not understand my question. I did not question what you answered.
My report was another. My report questions the reason the method does not work in the reported situation

**Comment by Leopoldthecoder** [comment]
@renatosistemasvc `clearValidate` does not clear the input text. It only removed the validation status of the field.

**Comment by renatosistemasvc** [comment]
@Leopoldthecoder @ziyoung 

Please, forgive me. I reproduced the example wrongly. I changed the reproducion link.

https://jsfiddle.net/kutmania/sedsahwr/4/

Notice that the reset does not work on the input in the dialog. What should I do to clear this input?

**Comment by ziyoung** [comment]
@renatosistemasvc `resetFields` resets all the fields. It reverts the value before it was changed.

![resetfields](https://user-images.githubusercontent.com/12947422/40760841-37aac26e-64cb-11e8-8997-8bb154d8386a.gif)

**Comment by Leopoldthecoder** [comment]
`resetField` resets every field to their **initial input**. The initial value of your input box is `'does not display this text the next time the modal is opened'`, so calling `resetField` basically means to
```js
this.data.name = 'does not display this text the next time the modal is opened'
```

**Comment by renatosistemasvc** [comment]
@Leopoldthecoder 
I understand! Many thanks for the reply.
What you said makes a lot of sense!

I need to find a way to clear the form. Because the same form can be used to edit a record or create a new record. In my system if the user opens the form to edit a record and then open the form to register a new record, the form is not reset. I do not know what to do. But thank you.

**Comment by renatosistemasvc** [comment]
@Leopoldthecoder 
I was able to find an alternative to solve my problem.
Instead of using the method `resetField` to reset the form... 
I do the following:

```
reset (){

        this.data.name = '';
        this.$refs.data.clearValidate();
}
```

I clean the form manually and then clean the validations. Solved my problem. I do not know if this is the best way to do it, but solved. Thanks for the explanations, my friend!
