### ISSUE TITLE
[Feature Request] need to call a function upon click event on option el-element

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#11421]
### Existing Component
Yes

### Component Name
el-option

### Description
I would like to do be able to use el-select and el-option to call function upon request, example below:

<el-select placeholder="Actions">
	<el-option @click.stop="functionA(valueA)" label=";abelA"></el-option>
	<el-option @click.stop="functionB(valueB)" label="labelB"></el-option>
	<el-option @click.stop="functionC(valueC)" label="labelC"></el-option>
</el-select>

I also tried putting a value

<el-select placeholder="Actions">
	<el-option @click.stop="functionA(valueA)" label=";abelA" value=null></el-option>
	<el-option @click.stop="functionB(valueB)" label="labelB" value=null></el-option>
	<el-option @click.stop="functionC(valueC)" label="labelC" value=null></el-option>
</el-select>

but didn't work

any idea how can I call a function upon click event on an el-option element?

**Comment by Leopoldthecoder** [comment]
`@click.native`
