### ISSUE TITLE
[Feature Request] suggests adding the beforeDestory hook function to packages/date-picker/src/picker.vue and calling unmountPicker in it.

### ISSUE THREAD

**Issue by lq111lq** [ElemeFE/element#11435]
### Existing Component
是

### Component Name
picker.vue

### Description
建议在 packages/date-picker/src/picker.vue 添加 beforeDestory钩子函数，并在其中调用unmountPicker。
用以销毁 this.picker。

**Comment by ziyoung** [comment]
@lq111lq picker 组件使用了 `vue-pooper`，这个 mixin 提供了 beforeDestory 钩子函数。
