### ISSUE TITLE
[Bug Report] select search pickup plug-in search box with multiple selection and search will be automatically emptied.

### ISSUE THREAD

**Issue by HelloKevinTian** [ElemeFE/element#11440]
### Element UI version
2.4.0

### OS/Browsers version
win7/chrome65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/alsowen/Laudf7hp/](https://jsfiddle.net/alsowen/Laudf7hp/)

### Steps to reproduce
添加一个select选择器，加入多选multiple和搜索功能filterable，输入一个关键词a后会出现多个带a的选项，点击某一个带a选项后搜索框会被清空，导致仍需再输入一遍a才能搜索并选中其他带a的选项。

### What is Expected?
搜索框不被自动清空。

### What is actually happening?
搜索框每次点选条目时都会被清空！

**Comment by Leopoldthecoder** [comment]
Use `reserve-keyword`.
