### ISSUE TITLE
使用jsx渲染inline-template时报错

### ISSUE THREAD

**Issue by sindu12jun** [ElemeFE/element#1144]
`                return <el-table-column
                    inlineTemplate
                    label={item.title}>
                    { $index }
                  </el-table-column>`
报错：

> vue.js?3583:2264 ReferenceError: $index is not defined(…)

使用jsx渲染时怎么取的row和$index数据呢？是我取的方式不对吗

**Comment by malin1988** [comment]
请问是怎样解决的？
