### ISSUE TITLE
[Bug Report] The lazy attribute of  Tabs has 2 BUG

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#11444]
### Element UI version
2.4.0

### OS/Browsers version
Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/0bwsy7bo/1/](https://jsfiddle.net/0bwsy7bo/1/)

### Steps to reproduce
1. 按顺序排列的四个pane，第三个加上lazy属性，其余不加

2.lazy属性的pane中放入自定义组件

### What is Expected?
1. tab栏按顺序排列

2.自定义组件只初始化一次  

### What is actually happening?
1.tab栏顺序乱了

2.每次进入lazy属性的pane都会重新初始化一次自定义组件

**Comment by LastHeaven** [comment]
这是本人的解决方案
https://jsfiddle.net/0bwsy7bo/2/

**Comment by ArrayZheng** [comment]
同遇这个问题，加lazy属性后tab乱序了

**Comment by sueblue** [comment]
我也遇到了这个问题，加了lazy属性，tab乱序。

**Comment by hcyfreedom** [comment]
目测用v-if控制tab的渲染可以达到和lazy一样的效果。
<el-tabs @tab-click="toRoute" v-model="thisTab.routeName">
    <el-tab-pane :label="item.text" :key="index" v-for="(item, index) in tabList" :name="item.routeName">
      <span v-if="item.routeName === $route.name">
        <router-view></router-view>
      </span>
    </el-tab-pane>
  </el-tabs>

**Comment by hcyfreedom** [comment]
> 目测用v-if控制tab的渲染可以达到和lazy一样的效果。
> <el-tabs @tab-click="toRoute" v-model="thisTab.routeName">

参考：https://blog.csdn.net/SanJiK/article/details/79764429
