### ISSUE TITLE
[Feature Request] suggests adding help to the form.

### ISSUE THREAD

**Issue by tangmingming** [ElemeFE/element#11446]
### Existing Component
Yes

### Component Name
2.*

### Description
chrome最新版

**Comment by Leopoldthecoder** [comment]
你可以使用 Tooltip 包裹一个表单项。

**Comment by tangmingming** [comment]
如果直接包含表单项 显示会有问题
![image](https://user-images.githubusercontent.com/7803319/40901373-8a88b3c6-6802-11e8-8a12-5b964b349f85.png)

如果写在表单项里面   得到焦点不会自动显示   只有将鼠标放上面才会显示
