### ISSUE TITLE
[Bug Report] Clearable el-select shows clear button on hovering when value is null

### ISSUE THREAD

**Issue by topclaudy** [ElemeFE/element#11451]
### Element UI version
2.4.0

### OS/Browsers version
Chrome 66, Firefox 60.0.1

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/p04y83r4/](https://jsfiddle.net/p04y83r4/)

### Steps to reproduce
Go to the reproduction link
Hover the clearable select

### What is Expected?
No clear button

### What is actually happening?
It shows the clear button even when the value is null

**Comment by wangjun521** [comment]
Remove your clearable attribute

**Comment by topclaudy** [comment]
I want it to be clearable (when it's not null or not empty)

**Comment by wangjun521** [comment]
还想让他是个下拉选择框还得是可清除的 有没有感觉你这种需求很奇葩啊亲
And you want him to be a drop-down box and you have to be able to clear it and you have to feel like you have a weird need
