### ISSUE TITLE
Can [Feature Request] date be supported by directly selecting dates instead of clicking the input box?

### ISSUE THREAD

**Issue by SituC** [ElemeFE/element#11456]
### Existing Component
是

### Component Name
DatePicker

### Description
日期组件能不能支持直接选择日期而非点击输入框弹出。现在日期组件需要点击输入框，弹出，并且点击完日期消失。希望能加直接存在的日期组件而不是作用到输入框。如果已经有这个功能还希望能在api的demo里面展示出来。

**Comment by wacky6** [comment]
https://github.com/ElemeFE/element/issues/9878

**Comment by SituC** [comment]
3Q
