### ISSUE TITLE
The [Bug Report] upload upload component appears bug

### ISSUE THREAD

**Issue by mgbq** [ElemeFE/element#11454]
### Element UI version
2.4.0

### OS/Browsers version
windows

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element/issues/11133](https://github.com/ElemeFE/element/issues/11133)

### Steps to reproduce
开启upload组件的拖拽属性，然后点击组件弹出文件管理器，从文件管理器中拖拽文件到组件中，之后再点击文件管理器确认按钮，浏览器崩溃，Chrome和360亲测

### What is Expected?
不卡死

### What is actually happening?
开启upload组件的拖拽属性，然后点击组件弹出文件管理器，从文件管理器中拖拽文件到组件中，之后再点击文件管理器确认按钮，浏览器崩溃，Chrome和360亲测

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by Joker1995** [comment]
Well,I met it sometime,maybe there was some problem
