### ISSUE TITLE
[Feature Request] supports the state of binding NavMenu and shows which navigation should be opened.

### ISSUE THREAD

**Issue by axetroy** [ElemeFE/element#11455]
### Existing Component
是

### Component Name
menu

### Description
有一些页面需要跳转路由. 在Javascript代码里面运行的.

这就导致了路由跳转了，导航栏还是原来的那个状态，对应的导航没有被打开.

能否通过一个绑定属性，来显示的指定哪个导航是被打开的?

``default-active``和``default-openeds``都只是绑定了初始化的状态.

可以另起一个属性绑定，来显示的指定哪个导航应该是打开状态吗？

**Comment by jikkai** [comment]
可以尝试下
```
<el-menu :default-active="$route.path"></el-menu>
```
