### ISSUE TITLE
Fix TS2300: Duplicate identifier'selectWhenUnmatched'

### ISSUE THREAD

**Issue by pantsli** [ElemeFE/element#11459]
### Existing Component
是

### Component Name
autocomplete

### Description
ERROR in node_modules/element-ui/types/autocomplete.d.ts(60,3)
TS2300: Duplicate identifier 'selectWhenUnmatched'.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/11388
