### ISSUE TITLE
The default-expand-all property of [Feature Request] table can be set dynamically, rather than traversing the assignment expand-row-keys to achieve full deployment.

### ISSUE THREAD

**Issue by KnorienChang** [ElemeFE/element#11463]
### Existing Component
是

### Component Name
el-table

### Description
table的default-expand-all属性可以动态设置，而不是通过遍历赋值expand-row-keys来实现全部展开。

The table's default-expand-all property can be set dynamically instead of traversing the expand-row-keys assignment to achieve full expansion. -- by Google Translate
https://jsfiddle.net/u0f3rxjp/

**Comment by jikkai** [comment]
Sorry, we have no plan to support this feature.
