### ISSUE TITLE
[Bug Report] Dropdown issue

### ISSUE THREAD

**Issue by tekbahadur1996** [ElemeFE/element#11468]
### Element UI version
2.2.1

### OS/Browsers version
Linux / Chrome Version 66.0.3359.181

### Vue version
2.2.1

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1992/](https://jsfiddle.net/mmx38qxw/1992/)

### Steps to reproduce
Open jsfiddle

### What is Expected?
dropdown must stay open after clicking elements in it.

### What is actually happening?
dropdown is closing

**Comment by OpsSingular** [comment]
Not sure if that is the intended behaviour of drop down.

Take a look at http://element.eleme.io/#/en-US/component/select

**Comment by jikkai** [comment]
`trigger="click"`
https://jsfiddle.net/mmx38qxw/1993/
