### ISSUE TITLE
[Bug Report] datepicker when value is string. all date is OK except week

### ISSUE THREAD

**Issue by lovewxz** [ElemeFE/element#11477]
### Element UI version
2.4.0

### OS/Browsers version
mac 10.13.3 / Chorme 66.0.3359.181（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/1o6kfhe0/](https://jsfiddle.net/1o6kfhe0/)

### Steps to reproduce
e.getTime is not a function

### What is Expected?
should like day,year,month

### What is actually happening?
e.getTime is not a function

**Comment by jikkai** [comment]
https://jsfiddle.net/1o6kfhe0/1/

**Comment by wacky6** [comment]
To use a string date, you must specify value-format. Otherwise, the component's behavior is undefined.
