### ISSUE TITLE
[Bug Report] Inconsistency in load icon for input & select field

### ISSUE THREAD

**Issue by Bikkel007** [ElemeFE/element#11479]
### Element UI version
2.4.0

### OS/Browsers version
macOs High Sierra v10.13.4 / Safari v11.1

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Check the examples in the Element UI documents for remote loading of the <el-select> and <el-input> elements.

### What is Expected?
I expected that for both the <el-input> and the <-el-select> a loading icon is shown. Is this possible?

### What is actually happening?
For loading items in a <el-input> a spinning icon is used while the text "loading" is used for loading items in a <el-select>

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
