### ISSUE TITLE
[Tabs] How to tell the active tab name

### ISSUE THREAD

**Issue by akirak** [ElemeFE/element#1147]
I want to know which tab is active after the user switches a tab. I thought a variable set as `:active-name` should be changed, but it doesn't change. How can I tell the active tab? 

 

### Reproduction Link

http://jsfiddle.net/Lkr4Lgdp/

### Steps to reproduce
Switch tab

### What is Expected?
`activeTab` is changed, and its tab name is logged to the console

### What is actually happening?
The initial tab name is logged every time

**Comment by wdmtech** [comment]
```

**Comment by akirak** [comment]
@wdmtech Thank you, it works!
