### ISSUE TITLE
[Feature Request] prettify the scrollbar style for table component just like just

### ISSUE THREAD

**Issue by stephen-liu1974** [ElemeFE/element#11473]
### Existing Component
是

### Component Name
table

### Description
I submitted one issue the same as this one some days ago, and thank you for your reply. After I reviewed the referenced issue you sent to me, I still think that the most cases used to table are paginated by small rows, so performance hit wouldn't make a big mess. Can you consider to add an additional CLASS for scrollbar within table component, thus the programmer can decide by themselves.

**Comment by jikkai** [comment]
Duplicate of #11208
