### ISSUE TITLE
[Bug Report] Message.close() doesn't work

### ISSUE THREAD

**Issue by ChuanfengZhang** [ElemeFE/element#11488]
### Element UI version
2.4.0

### OS/Browsers version
Mac OS 10.13.4 (17E199) Chrome 67.0.3396.62

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/prq3vc7g/3/](https://jsfiddle.net/prq3vc7g/3/)

### Steps to reproduce
1.Create a new instance of Message with options: "duration: 0"
2.this.$message.close()

### What is Expected?
The current Message can be closed.

### What is actually happening?
The current Message can't be closed.
If close() need an id, how can I get it?

**Comment by ChuanfengZhang** [comment]
According to [Doc](http://element.eleme.io/#/zh-CN/component/message), there's nothing else need to provide.

**Comment by jikkai** [comment]
https://jsfiddle.net/prq3vc7g/5/

**Comment by ChuanfengZhang** [comment]
@jikkai Thanks.
