### ISSUE TITLE
[Bug Report] The  fixed  table will repeatedly render data to the DOM node

### ISSUE THREAD

**Issue by naihe138** [ElemeFE/element#11487]
### Element UI version
2.4.0

### OS/Browsers version
mac 10.13.4

### Vue version
2.5.17-beta.0

### Steps to reproduce

In the fixed table, some columns do not need to be rendered, but they still exist on the document

### What is Expected?
Do not render unnecessary dom nodes

### What is actually happening?
Three tables will be rendered. The table data of the fixed column is the same as the main table data.

![wx20180605-121455](https://user-images.githubusercontent.com/12893716/40955020-1b6e6ffe-68ba-11e8-9add-5470678c12fc.png)

**Comment by jikkai** [comment]
These columns should be rendered because they are used to keep the struct of the fixed table.

**Comment by naihe138** [comment]
what?????I saw ant-design not like this
