### ISSUE TITLE
[Bug Report] el-select with multiple and remote-method would display values but values

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/element#11483]
### Element UI version
2.4.0

### OS/Browsers version
Chrome latest

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/nefhgsa3/](https://jsfiddle.net/nefhgsa3/)

### Steps to reproduce
Just load the page, the select would show '选项1' and '选项5' but not '黄金糕' and '北京烤鸭'

### What is Expected?
Show '黄金糕' and '北京烤鸭'

### What is actually happening?
Show '选项1' and '选项5'

**Comment by Leopoldthecoder** [comment]
You should initiate `options` with pre-selected values: https://jsfiddle.net/nefhgsa3/2/
