### ISSUE TITLE
[Bug Report] el-upload file-list cannot sync

### ISSUE THREAD

**Issue by davyzhang** [ElemeFE/element#11482]
### Element UI version
2.4.0

### OS/Browsers version
Chrome/Macos

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/m4atout7/1/](https://jsfiddle.net/m4atout7/1/)

### Steps to reproduce
移除所有上传中的文件
加入新的文件
点击上传按钮
console里面的fileList依然是原有值

这样flist-list这个属性只能用于初始化

### What is Expected?
file-list 能同步更新 文件列表

### What is actually happening?
file-list不能同步更新

**Comment by davyzhang** [comment]
Currently, the way I found to hack it is to listen to the change event and assign the fileList every time 
```typedscript
onChange(f:File,fl:File[]){
this.fileList = fl;
}
```

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/40952122-a5f97640-68ac-11e8-9d79-307df03d0b53.png)
