### ISSUE TITLE
[Bug Report] The bug "Duplicate identifier 'selectWhenUnmatched'" is still there when i installed the package today

### ISSUE THREAD

**Issue by ludesong** [ElemeFE/element#11498]
### Element UI version
2.4.0

### OS/Browsers version
windows10

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/issues/11459](https://github.com/ElemeFE/element/issues/11459)

### Steps to reproduce
1. install package in a Vue Project
2. run dev

### What is Expected?
Compiled successfully

### What is actually happening?
in **\node_modules\element-ui\types\autocomplete.d.ts

(60,3): error TS2300: Duplicate identifier 'selectWhenUnmatched'.

**Comment by Leopoldthecoder** [comment]
It's fixed and will be shipped with our next release.

**Comment by Hellowor1d** [comment]
@Leopoldthecoder  👍 
Thanks for your hard work, 
BTW, When will the next release come?

**Comment by Leopoldthecoder** [comment]
Before next week.

**Comment by ludesong** [comment]
@Leopoldthecoder 
Thanks for your answer
