### ISSUE TITLE
[Feature Request] form-item prop accept dot-and-bracket notation

### ISSUE THREAD

**Issue by newraina** [ElemeFE/element#11491]
### Existing Component
是

### Component Name
form-item

### Description
Currently, `form-item` attribute `prop` accept string path with dot notation:

```js
'contact.billing.time'
```

Sometimes, field value structure is more complicated:

```js
'contact.billing.address[2].phones[1].areaCode'
```

It would be nice if  `prop` accept dot-and-bracket notation, just like Redux-Form does: [Field Component]( https://redux-form.com/7.3.0/docs/api/field.md/#-code-name-string-code-required-)

**Comment by ziyoung** [comment]
@newraina form-item `prop` accepts dot-and-bracket notation. https://jsfiddle.net/zhiyang/hjwsL4gm/2/ The FormItem with a `prop` should have a corresponding rule.
