### ISSUE TITLE
[Bug Report] v-loading on el-dialog will become a fullscreen loading

### ISSUE THREAD

**Issue by jaguarsy** [ElemeFE/element#11495]
### Element UI version
2.4.0

### OS/Browsers version
MacOS 10.12.6 / Chrome  66.0.3359.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/z8p4umew/6/](https://jsfiddle.net/z8p4umew/6/)

### Steps to reproduce
click the "Open Dialog" button.

### What is Expected?
The loading mask is full of the dialog.

### What is actually happening?
The loading mask is full of the screen. And user can't close the dialog before the loading close.

**Comment by Leopoldthecoder** [comment]
This is because the outmost element of Dialog is a fullscreen wrapper. Use `$loading` instead: https://jsfiddle.net/z8p4umew/11/

**Comment by sundongxu** [comment]
@Leopoldthecoder is this bug resolved? could u please give a demo using $loading ? cause I can't open that jsfiddle link ... thks.
