### ISSUE TITLE
[Feature Request] hopes that the DatePicker component can add the multiple attribute, and it can choose the date after opening.

### ISSUE THREAD

**Issue by gee1k** [ElemeFE/element#11496]
### Existing Component
Yes

### Component Name
DatePicker

### Description
首先非常感谢 elemeFE 团队开源这么好用的 UI 库。省去了很多开发上的重复工作。之前做项目里经常会有日期多选功能。然后最近使用 Element UI，发现没有这个功能，希望 DatePicker 组件能新增 multiple 属性，开启后可以多选日期，使用场景蛮多的

**Comment by jikkai** [comment]
`type="dates"`
https://jsfiddle.net/6sgxfc75/
