### ISSUE TITLE
[Feature Request] Can the tree extend full deployment and full collection?

### ISSUE THREAD

**Issue by z649319834** [ElemeFE/element#11494]
### Existing Component
是

### Component Name
tree

### Description
Can the tree extend full deployment and full collection?

**Comment by ziyoung** [comment]
@z649319834 不太理解你的意思，能描述再详细一点吗？

**Comment by z649319834** [comment]
@ziyoung 希望能够扩展全部展开和全部收起的方法

**Comment by ziyoung** [comment]
@z649319834 在 Tree 组件懒加载时，节点是不是子节点，这是不确定的。**全部展开**的功能其实是很难处理这些节点的。目前，我们没有计划去实现该功能。
