### ISSUE TITLE
input输入建议自定义模板用template渲染点击下拉没有触发选中

### ISSUE THREAD

**Issue by plusice** [ElemeFE/element#1149]
### Vue version 2.0.5 

input输入建议的自定义模板（下拉列表项自己定义一个组件），如果是用template渲染的话（用jsx也是），下拉列表点击没有触发选中。

[看这里](http://jsfiddle.net/wxbgovb6/)

**Comment by baiyaaaaa** [comment]
自定义的列表项组件需要是一个functional component才能将其原有的列表项属性（点击事件）传进去，请参考文档写法http://element.eleme.io/#/zh-CN/component/input#zi-ding-yi-mo-ban。

**Comment by plusice** [comment]
好的，感谢回复~
