### ISSUE TITLE
[Feature Request] validateField should return promise

### ISSUE THREAD

**Issue by germansokolov13** [ElemeFE/element#11507]
### Existing Component
Yes

### Component Name
form

### Description
Form's method `validate` can return promise if callback is omitted(which is documented). On the other hand `validateField` does return a promise(which is not documented) but it always resolves. It should resolve on validity approved only and reject otherwise. And it should be documented.

**Comment by Leopoldthecoder** [comment]
`validateField` always expects a callback. For the time being, we have no plan to make it support promises.

**Comment by germansokolov13** [comment]
Maybe I could make a pr on this? And the callbak doesn't even return bool, but returns error messsge, which could be blank or undefined
