### ISSUE TITLE
After the [Feature Request] el-date-picker set the default start time and end time, the change date calendar plug-in cannot show the time to change, but the value of the related JS instance is changed to the time for modification.

### ISSUE THREAD

**Issue by wkx359518081** [ElemeFE/element#11505]
### Existing Component
是

### Component Name
el-date-picker

### Description
如果我不传默认值的话就一切正常
<el-date-picker
                v-model="hotelProductForm.dateTimeRange"
                size="small"
                type="daterange"
                :placeholder="$t('addProduct.pleaseSelect',{name:$t('addProduct.dateRange')})">
              </el-date-picker>
hotelProductForm.dateTimeRange原来是一个空的数组 [],
使用hotelProductForm.dateTimeRange接收后台传过来的开始时间跟结束时间,
            在mounted阶段我这样给开始时间与结束时间赋默认值this.hotelProductForm.dateTimeRange = [res.hotelProduct.saleStartDate, res.hotelProduct.saleStopDate]

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
