### ISSUE TITLE
<el-input type=""number></el-input> not working!

### ISSUE THREAD

**Issue by fangsueluo** [ElemeFE/element#11506]
### Element UI version
0.1.0

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[ https://elementui.github.io/issue-generator]( https://elementui.github.io/issue-generator)

### Steps to reproduce
<el-input type="number"></el-input> not working!

### What is Expected?
<el-input type="number"></el-input> only input number

### What is actually happening?
<el-input type="number"></el-input> can input letters

**Comment by jikkai** [comment]
Duplicate of #11324
