### ISSUE TITLE
[Bug Report] pagination can't go to prev page or first page when total >= 0 && current-page-size > 0

### ISSUE THREAD

**Issue by bq-hentai** [ElemeFE/element#11517]
### Element UI version
2.4.0

### OS/Browsers version
win7/chrome62

### Vue version
2.5.2

### Reproduction Link
[www.jsfiddle-fake-url.com](www.jsfiddle-fake-url.com)

### Steps to reproduce
see [this](https://github.com/ElemeFE/element/pull/10247#issuecomment-378106298)

### What is Expected?
redirect to prev/first page

### What is actually happening?
rt

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by bq-hentai** [comment]
Sry for late reply and no reproduction link.

I created a codepen, plz see [this](https://codepen.io/anon/pen/NzJoGv).

Step: Click prev button, no `current-change` event emitted, so no alert.

**Comment by bq-hentai** [comment]
另外附上：
[造成影响的commit](https://github.com/ElemeFE/element/pull/10247/commits/0406b9cff61517bc65edfa8dd7822d2ae5bfdde9)

[之前的记录](https://github.com/ElemeFE/element/pull/10247#issuecomment-394262991)

**Comment by bq-hentai** [comment]
@Leopoldthecoder 但是此时的改变是由于组件内部判断，然后往前移一页，这种如果不触发 `current-change` 用户并不能感知啊。用户最好也是不需要在自己的业务代码中编写和组件里面的 validate 一样的代码吧。

**Comment by bq-hentai** [comment]
另外，对于这种变化如果是预期的，建议文档可以注明= =
