### ISSUE TITLE
When [Bug Report] browsers are zoomed, the table header and data part will be misplaced.

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#11511]
### Element UI version
0.1.0

### OS/Browsers version
windows/chrome 65.0.3325.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/z9c6x1qu/56/](https://jsfiddle.net/z9c6x1qu/56/)

### Steps to reproduce
浏览器页面缩小为90%
表格单元格错位，边框不对齐了。

### What is Expected?
缩放不影响表格布局。

### What is actually happening?
浏览器缩小为90%，边框错位不对齐了。
2.0.11版本及以前没有该问题。
升级到2.2.0时出现了该问题。

**Comment by AprilXtt** [comment]
![table](https://user-images.githubusercontent.com/30852982/41029933-a98efd1c-69af-11e8-9841-297290eb0029.png)
对比了原来的布局，好像是表头和合计行没有同步缩放。

**Comment by rookiebulls** [comment]
I met this problem too,  but when you set a fixed width to each column, this problem disappeared. But I need the columns to expand automatically.

**Comment by loyalforyou** [comment]
@AprilXtt 解决了吗? 遇到同样问题   同时与@rookiebulls的描述一致,设置固定宽度bug消失,但是我也需要自动适应啊...

**Comment by Glenfiddish** [comment]
官网放大到1.1时, 感觉是排序时的css没有处理好?
![cuow](https://user-images.githubusercontent.com/22559022/45746237-57600800-bc35-11e8-87a9-7fc8664de1c0.png)

**Comment by LaiHuanMin** [comment]
@AprilXtt @rookiebulls @loyalforyou 我找到解决方案的issue了，参考https://github.com/ElemeFE/element/issues/11019这个地址，issue作者使用了这个workaround的方式：  
 

```
mounted() {
$("colgroup").find('col[name=gutter]').css('display', 'none');
}
```

**Comment by LaiHuanMin** [comment]
不过这是暂时的方案。。。虽然不太优雅，但是管用啊 :doge

**Comment by 1008611** [comment]
@LaiHuanMin 使用min-whidth时候会出现错位问题。固定宽度时候没问题。
好吧 暂时 使用这个吧，this.$refs.table.$el.querySelector('col[name=gutter]').style.display = 'none'

**Comment by Zeus-Iqd** [comment]
我们产品也说这个了，真是什么都能搞到，我们的目的就是满足产品

**Comment by XAHTEP26** [comment]
.el-table__header colgroup col[name=gutter] {
    display: none;
}

**Comment by ziyoung** [comment]
该功能不支持。

**Comment by ferrinweb** [comment]
关于这个表格的边框还有另一个问题：当用户的屏幕为高分屏，且使用系统推荐的缩放比例（比如125%），则表格头部的下边框会消失。

**Comment by BooHome** [comment]
> 关于这个表格的边框还有另一个问题：当用户的屏幕为高分屏，并且使用系统推荐的缩放比例（尺寸125％），则表格标题的下边框会消失。

也遇到这个问题了，而且不是全部消失

**Comment by chenyuhu** [comment]
> 关于这个表格的边框还有另一个问题：当用户的屏幕为高分屏，且使用系统推荐的缩放比例（比如125%），则表格头部的下边框会消失。

这个问题解决了吗
