### ISSUE TITLE
使用table的属性出现各种警告，如何解决

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1151]
使用用element1.0.0，在使用器table组件的时候，vue出现各种警告，如何解决
![image](https://cloud.githubusercontent.com/assets/16740731/20382529/4281efb6-ace7-11e6-9abf-ea72b1af08d8.png)
具体的packages的配置如下：
![image](https://cloud.githubusercontent.com/assets/16740731/20382561/59eb7a96-ace7-11e6-9ddd-b644f5e32b9c.png)

**Comment by Leopoldthecoder** [comment]
属性绑定写错了，建议查阅 Vue 文档的相关部分。比如应该这样写：
```javascript
:stripe="false"
```
而不是
```javascript
stripe="false"
```

**Comment by yuanshengchao** [comment]
恩恩谢谢，不过showOverflowTooltip这个是没有的一个属性呢。为什么还会提醒呢？

**Comment by Leopoldthecoder** [comment]
「没有的一个属性」是指？

**Comment by yuanshengchao** [comment]
就是我代码里面没有写过showOverflowTooltip这个属性，为什么还一直警告呢？
![image](https://cloud.githubusercontent.com/assets/16740731/20384008/1198fc9a-aced-11e6-9aaf-d2a931cb1291.png)

**Comment by Leopoldthecoder** [comment]
有这个警告的话，看上去代码里应该是出现了这个属性的。方便的话贴一下你的代码。

**Comment by yuanshengchao** [comment]
好的，稍等

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20385676/5b3b250c-acf3-11e6-999c-2ee114c4c8e6.png)

**Comment by yuanshengchao** [comment]
这个代码就是会报mising span

**Comment by Leopoldthecoder** [comment]
`missing span` 是因为 `span` 是 `el-col` 的必填属性（1.0.1 版不再是必填了），你这里没有填。

**Comment by yuanshengchao** [comment]
您好，我已经全部解决了。可以close了，谢谢。
