### ISSUE TITLE
The [Bug Report] table table is merged and the floating point number is not processed.

### ISSUE THREAD

**Issue by LuckyTaoTao** [ElemeFE/element#11518]
### Element UI version
2.4.0

### OS/Browsers version
window 10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
table表格计算，输入浮点数，计算结果有误，希望及时更改

### What is Expected?
及时修复

### What is actually happening?
及时修复

**Comment by jikkai** [comment]
这不是 element 的 bug。JavaScript 中的 Number 遵循 IEEE 754 标准，因此浮点数计算可能会带来精度丢失问题。

**Comment by Leopoldthecoder** [comment]
事实上，Element 已经对浮点数进行了处理。如果有问题，请提供 demo。
