### ISSUE TITLE
Can the icon of the date and time control of [Feature Request] 2.X version be changed to the right?

### ISSUE THREAD

**Issue by yuanjinyong** [ElemeFE/element#11513]
### Existing Component
是

### Component Name
DateTimePicker

### Description
原来1.x版本的日期时间控件的图标放在右边很好的，现在2.x版本的放到左边了，当和Selector等右边有图标的组件垂直对其排列时，看起来太怪了，日期时间控件和普通输入框的左边文字的起始位置不在一条竖线上，整个表单的排版不美观。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
