### ISSUE TITLE
There are too many options for [Bug Report] searchable Select selectors, which can not be entered when the page height is exceeded. Because the option has covered the input box.

### ISSUE THREAD

**Issue by wushanchao** [ElemeFE/element#11514]
### Element UI version
2.4.0

### OS/Browsers version
win10/Chrome68

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
可搜索的Select选择器的选项过多，超过页面高度时，无法进行输入操作。因为选项已经覆盖了输入框。

### What is Expected?
提供一个属性值，控制选项高度。进行选项内部滚动。

### What is actually happening?
可搜索的Select选择器的选项过多，超过页面高度时，无法进行输入操作。因为选项已经覆盖了输入框。

**Comment by Leopoldthecoder** [comment]
You can always override Element style to your favor.

**Comment by ziyoung** [comment]
@wubaiqing 打开 https://jsfiddle.net/mmx38qxw/ ，也没重现你的问题。我自己新建了一个：https://jsfiddle.net/zhiyang/g4nmst6j/1/，没有出现上诉问题。
