### ISSUE TITLE
[Bug Report] CommonJS bundle causes webpack to bundle duplicate copies of some components

### ISSUE THREAD

**Issue by LachlanStuart** [ElemeFE/element#11528]
### Element UI version
2.3.9 and 2.4.0

### OS/Browsers version
N/A

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElementUI/element-starter](https://github.com/ElementUI/element-starter)

### Steps to reproduce
(Note: This is not an issue with the webpack config in the starter repository - the code that's shipped in element-ui's NPM package already contains the duplicate code - see below for explanation)

* Check out https://github.com/ElementUI/element-starter
* (Optional) Run `yarn upgrade` to update to the latest Element-UI. It doesn't affect the outcome.
* Run `yarn run build`
* Open `dist/vendor.js` in a text editor and search for some text that should only appear once per component, e.g. `componentName:"ElSelect"`

### What is Expected?
Only one instance of that text should be found

### What is actually happening?
Two instances of the text are found. It's obvious that there are 2 copies of the source code for this module

From what I could tell when investigating this, the issue is that the compiled `element-ui.common.js` contains both the source code for `ElSelect` and also a `require("element-ui/lib/select")`, which causes the consuming application's webpack to include a 2nd copy of `ElSelect`. The source code is bundled into `element-ui.common.js` because `src/index.js` imports from `'../packages/select/index.js'` which webpack includes in the bundle, whereas other components such as `packages/pagination/src/pagination.js` import from  `'element-ui/packages/select'` which matches one of the "externals" given to Webpack, causing it to translate that import into a `require`.

I tested 2 solutions locally:

* (1) [Change `build/bin/build-entry.js` so that the imports in `src/index.js` are consistent with everywhere else](https://github.com/LachlanStuart/element/commit/38fed83d58539c4a128aecd5dcf2d62405cd47ec), causing the Webpack externals to be respected and the component source to not be included in `element-ui.common.js` - this got rid of the duplicate code but increased my application's minified but non-gzipped bundle size by 64kB. I'm not sure why the bundle size increases.
* (2) [Change `build/config.js` to exclude components from the "externals"](https://github.com/LachlanStuart/element/commit/6bb03585d0b1d0678085cb95eb50a4f7b48221dd), causing `element-ui.common.js` to not include any `require`s to components. This also removed the duplicate code and decreased my minified application bundle size by 80kB.

I haven't made either of these into a PR because (1) seems like it's more in the spirit of how `webpack.common.js` was intended to function, but a 64kB increase in bundle size is not good. And (2) seems like a hack that would break other bundles, and existing users' who directly import components e.g. from `import ElSelect from 'element-ui/lib/select'`.

**Comment by Leopoldthecoder** [comment]
@jikkai Might be something to look at.
