### ISSUE TITLE
[Bug Report] Datepicker tries to validate even when required is false

### ISSUE THREAD

**Issue by miguelRivero** [ElemeFE/element#11529]
### Element UI version
2.4.0

### OS/Browsers version
Chrome 66.0 (Mac)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/5nd8q6uw/1/](https://jsfiddle.net/5nd8q6uw/1/)

### Steps to reproduce
Include a datepicker or timepicker as in the demos, but with required = false in their rules

### What is Expected?
Not to show the error style (red borders)

### What is actually happening?
Apparently it expects a value and throws an error (i.e. "date1 is nos a date"). If I choose a date and delete it, the error dissapears and the component is styled with the green color, as expected.

**Comment by Leopoldthecoder** [comment]
Try initiating `date1` and `date2` to `null`: https://jsfiddle.net/5nd8q6uw/3/ .

**Comment by miguelRivero** [comment]
That made it. Thanks!
