### ISSUE TITLE
How does [Feature Request] compile Element for web tag reference based on component requirements?

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#11526]
### Existing Component
否

### Component Name
按需引入

### Description
根据使用文档，WebPack打包可以按需引入Element-UI。可是有些时候，不需要打包，但是直接用script标签引入element-ui会太大了，请问要如何根据需求生成适用于script标签引入的element组件呢？（例如只需要使用其中的两三个组件）

**Comment by jikkai** [comment]
Duplicate of #11380

Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
