### ISSUE TITLE
[CheckboxGroup] 在和 Col 一起用的时候无法勾选

### ISSUE THREAD

**Issue by gofmt** [ElemeFE/element#1152]
### ElementUI version
1.0.0

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.6

### What is actually happening?

`          <el-row>
            <el-checkbox-group v-model="checkList">
              <el-col :span="3">
                <el-checkbox label="售价" name="售价"></el-checkbox>
              </el-col>
            </el-checkbox-group>
          </el-row>
`

这种情况下,el-checkbox无法响应勾选事件.

**Comment by reverland** [comment]
为啥这样嵌套，你把el-col作为el-row的直接子元素

**Comment by gofmt** [comment]
大量的checkbox超过一行时,需要这样嵌套,否则就是参差不齐.

**Comment by reverland** [comment]
所以这是什么bug，是要支持这种嵌套方式？

**Comment by QingWei-Li** [comment]
算是 bug，下一版支持这种用法

**Comment by reverland** [comment]
就是说允许

```
el-row
  other-tags
    el-col
  another-tag
    el-col
```

的用法？好奇怪啊，如果other-tags设定宽度了，el-col怎么办
