### ISSUE TITLE
[Bug Report] About Select Component:  if i switch radio to multiple, input value is not be cleared

### ISSUE THREAD

**Issue by guchunwen** [ElemeFE/element#11520]
### Element UI version
0.1.0

### OS/Browsers version
mac/chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/hqtuo74n/1/](https://jsfiddle.net/hqtuo74n/1/)

### Steps to reproduce
Start, Select is radio,   
First, choose a option;
Second  ,  click multiple button to switch,; 
but now  Input's value  is not be cleared;( I think is should be cleared )
Third, choose some options,  you can see  ,the previous value is appear;

### What is Expected?
I think when switch multiple,   Input's value shoud be cleared

### What is actually happening?
when switch multiple,   Input's value is not be cleared

**Comment by Leopoldthecoder** [comment]
You can `key` the `<el-select>`: https://jsfiddle.net/hqtuo74n/7/

**Comment by guchunwen** [comment]
@Leopoldthecoder   thanks ！  but why use multiple for key ?  the purpose is update dom?
