### ISSUE TITLE
[Bug Report] Tree dragged customs input need to double click to click

### ISSUE THREAD

**Issue by chenam** [ElemeFE/element#11537]
### Element UI version
2.4.0

### OS/Browsers version
window/ IE

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/xtbvej1r/](https://jsfiddle.net/xtbvej1r/)

### Steps to reproduce
IE下 ，添加 drag的属性的tree，自定义input ，双击才能获得光标

### What is Expected?
单击可以获得光标

### What is actually happening?
双击才能获得光标

**Comment by ziyoung** [comment]
@chenam FYI: https://stackoverflow.com/questions/28594699/within-a-draggable-true-element-textareas-and-inputs-need-2-clicks-to-edit-in-i
