### ISSUE TITLE
[Bug Report] resetFields uses  with v-if/v-else error [bug]

### ISSUE THREAD

**Issue by a631807682** [ElemeFE/element#11534]
### Element UI version
2.3.3

### OS/Browsers version
 Chrome 64.0.3282.186

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/s5ar1un3/39/](https://jsfiddle.net/s5ar1un3/39/)

### Steps to reproduce
1. 点击'点我'按钮
2. 选择'类型1'
3. 关闭模态框
4. 再次点击'点我'按钮，报错。

### What is Expected?
期望`resetFields`把`formData.text`还原为初始值。

### What is actually happening?
`resetFields`把`formData.text`还原为`formData.value`的初始值。

**Comment by Leopoldthecoder** [comment]
You need to `key` the form items: https://jsfiddle.net/s5ar1un3/41/

**Comment by a631807682** [comment]
What about question 2 in your code  [https://jsfiddle.net/s5ar1un3/41/](https://jsfiddle.net/s5ar1un3/41/)
1. click the 'click me' button.
2. select component 1 to 'type 2'  and select component  2 value.
3. select component 1 to 'type 1'
4. close dialog
5. click the 'click me' button.
6. select component 1 to 'type 2' or see the `console.log` message .

**Comment by Leopoldthecoder** [comment]
和 `if(this.prop)` 无关，是因为切换 `formData.class` 时触发了其他 `<el-form-item>` 的 `beforeDestroy` 钩子。可以在切换 `formData.class` 后重置表单：https://jsfiddle.net/s5ar1un3/42/

**Comment by a631807682** [comment]
嗯嗯 发现了 所以撤销了后面的commit 谢谢你
