### ISSUE TITLE
[Bug Report] el-table can not sort with Pug template language used.

### ISSUE THREAD

**Issue by leRenart** [ElemeFE/element#11531]
Element UI version
2.3.9

OS/Browsers version
firefox/chrome

Vue version
2.5.16

Reproduction Link
https://codepen.io/anon/pen/ERgJqq

Steps to reproduce
Used the api document's data.Works fine in HTML,not working in PUG.

What is Expected?
el-table sort works in PUG.

What is actually happening?
not working

[I'm reopening an[ old issue #8995](https://github.com/ElemeFE/element/issues/8995) closed for no apparent reason]

**Comment by aitk** [comment]
Hi @leRenart I managed to get your code pen to work by using colons in front of `sortable` https://codepen.io/anon/pen/dKjKJr

**Comment by leRenart** [comment]
Yeah, thank you @aitk 👍 I've found it too but never update that issue because it was closed (that's a bit lame sorry) 😅
