### ISSUE TITLE
[Bug Report] Pagination- paging component does not automatically invoke page number change current-change events when page number currentPage changes.

### ISSUE THREAD

**Issue by cqliulei** [ElemeFE/element#11535]
### Element UI version
0.1.0

### OS/Browsers version
windows7/chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2119/](https://jsfiddle.net/mmx38qxw/2119/)

### Steps to reproduce
Pagination-分页组件 
在页码currentPage 发生变化时(非手动点击分页按钮)，未自动调用页码变化的current-change事件
示例说明：
1、进入页码mounted后，将页码改变
2、分页组件@current-change，打印当前页码

```
 <el-pagination @size-change="handleSizeChange" @current-change="handleCurrentChange" :current-page.sync="currentPage" :page-size="100" layout="total, prev, pager, next" :total="1000">
    </el-pagination>
```
 
   ```
methods: {     
      handleCurrentChange(val) {
        alert(`当前页: ${val}`);
      }
    },
    mounted(){
    	var _this=this;
        window.setTimeout(function(){
        	alert('开始改变页码');
        	_this.currentPage1= 6;
        },2000)
    },
    data() {
      return {
        currentPage: 5
       
      };
    }

```

### What is Expected?
Pagination-分页组件 
在页码currentPage 发生变化时(非手动点击分页按钮)，应自动调用页码变化的current-change事件

### What is actually happening?
Pagination-分页组件 
在页码currentPage 发生变化时(非手动点击分页按钮)，未自动调用页码变化的current-change事件

**Comment by Leopoldthecoder** [comment]
`current-change` 仅响应用户交互，不会在通过代码改变当前页时触发。这是设计中的，表单类组件的 `change` 事件也是如此。

**Comment by xiongyizhu** [comment]
为什么在旧版本中支持呢，比如1.4.13版本中就是支持的
例子：https://jsfiddle.net/mmx38qxw/2163/
点击变成一页按钮就触发了current-change事件，但是新版本不支持
