### ISSUE TITLE
[Bug Report] DatePicker does not update on v-model variable update

### ISSUE THREAD

**Issue by bleikg90** [ElemeFE/element#11533]
### Element UI version
2.4.0

### OS/Browsers version
Mac 10.13 Chrome Version 66.0.3359.181 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/bleikg90/ub582cfm/](https://jsfiddle.net/bleikg90/ub582cfm/)

### Steps to reproduce
Create datepicker
Assing v-model variable
update date on variable through other user action i.e. button 

### What is Expected?
The text Field on the Datepicker should update with the v-model variables value

### What is actually happening?
The popper displays the correct date on the v-mode variable but the textfield does not update accordingly 

If there is a way to access the textfield directly and update it manually please let me know as this is the quickest solution.

**Comment by Leopoldthecoder** [comment]
Vue cannot detect `setDate` (proof: https://jsfiddle.net/ub582cfm/2/). So you may have to take a detour here: https://jsfiddle.net/ub582cfm/3/ .

**Comment by bleikg90** [comment]
Thank you! Works perfectly!

**Comment by freeman983** [comment]
你好,[ https://jsfiddle.net/ub582cfm/2/ ] 这个例子中,修改了v-model的值后,快捷选择就无法工作了.请这个问题怎么解决?
