### ISSUE TITLE
The placeholder of the form item in the [Bug Report] form form-item is automatically checked with the internationalized text when it is loaded.

### ISSUE THREAD

**Issue by suibianxieyige** [ElemeFE/element#11530]
### Element UI version
2.4.0

### OS/Browsers version
win7/IE11

### Vue version
2.5.15

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、用el-form写一个表单
2、其中某个el-form-item加入校验并且为必填，加上prop属性，中的el-input的placeholder用 国际化后的内容 例如 :placeholder="$t('inputUsername')"
3、打开该页面后会自动校验一次

### What is Expected?
不会自动校验一次，

### What is actually happening?
会自动校验一次，并且提示错误。

**Comment by fabin5** [comment]
我也遇到了这个问题，当placeholder是国际化后的内容，打开页面的时候会自动报错一次

**Comment by ziyoung** [comment]
@suibianxieyige 提供一个可重现的例子。

**Comment by badpunman** [comment]
This is an issue in every single elementui component that has i18n texts as default values of props.

**Comment by fabin5** [comment]
@ziyoung 可以看这个例子。https://jsfiddle.net/fabin5/jsgqpdy4/3/ 代码是这样写的，但是JSFiddle中，IE11打开不这里例子。

**Comment by ziyoung** [comment]
@fabin5 无法重现。
![locale](https://user-images.githubusercontent.com/12947422/41210718-f1382cb0-6d65-11e8-8b2a-57672fb7d7fe.gif)


打开控制台，出现下面这段警告信息。
>  Cannot translate the value of keypath "message". Use the value of keypath as default

vue-i18n v5 与 v6 有较大差别，使用时要注意区分。
对你的例子稍微进行了改动，现在显示正常了。https://jsfiddle.net/zhiyang/jsgqpdy4/5/ ，但还是没有复现这个问题。

**Comment by fabin5** [comment]
@ziyoung 在IE11下才有出现哦。

**Comment by jinboyigu** [comment]
临时解决方案可参考 https://github.com/ElemeFE/element/issues/13578#issuecomment-442697258
