### ISSUE TITLE
[Feature Request] Clearable select component usability suggestion

### ISSUE THREAD

**Issue by badpunman** [ElemeFE/element#11542]
### Existing Component
Yes

### Component Name
El-Select

### Description
Clearable-attributed el-select components currently, while hovering the control, replace the menu-icon with the clear-icon. This confuses many users as they don't expect this to happen. Most people expect the menu to open and do not notice the icon changing. I suggest moving the close-button to be on the side of the menu-icon instead of replacing it.

I can try implement this and do a pull request if this the type of behavior that other developers here agree to.

![image](https://user-images.githubusercontent.com/937289/41148908-cdaefcce-6b12-11e8-8120-9e4d870c14e8.png)

**Comment by atilkan** [comment]
Or i could be like multiselect. But i like current style.

**Comment by badpunman** [comment]
A work in progress version committed to my fork. Can't pull request it yet with good conscience since it breaks existing usability/functionality. But maybe to a new major version some day.
