### ISSUE TITLE
TimePicker组件，滚动选择时间时，会发生样式错位

### ISSUE THREAD

**Issue by zhangliang2008v** [ElemeFE/element#1154]
![qq 20161117172131](https://cloud.githubusercontent.com/assets/6396617/20383362/652902fe-acea-11e6-8948-813bad85cb16.png)

**Comment by QingWei-Li** [comment]
目前就是这样，后面设计师会重新设计

**Comment by BLUE-FAT** [comment]
现在是不是还没有解决这个问题啊
