### ISSUE TITLE
[Bug Report] datepicker values stored as array with the same variance name in different components will affect each other

### ISSUE THREAD

**Issue by lazybonee** [ElemeFE/element#11543]
### Element UI version
2.3.9

### OS/Browsers version
windows10/Chrome 67.0.3396.79

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/lazybone/8Lo451t2/](https://jsfiddle.net/lazybone/8Lo451t2/)

### Steps to reproduce
1.You can copy my code in https://jsfiddle.net/lazybone/8Lo451t2/.  
2.And if you create another vue component, and create the same datepicker as in the code example,and you also store the date values in variance  array 'pickerValue'.   
3.Then your choice of date in a component will affect the values of another component.  
4.But if you change the  variance pickerValue(type array) to be pickerValue0(type string) and pickerValue1(type string),it won't affect each other. 

### What is Expected?
Store the picked date values in pickerValue(type array)，the values in different components shouldn't affect each other.

### What is actually happening?
Store the picked date values in pickerValue(type array)，the values in different components actually affect each other.

**Comment by badpunman** [comment]
Not sure i understand, but in your example you haven't initialized the values inside the array you are referencing. Make sure they exist somehow for example [null, null]

**Comment by Leopoldthecoder** [comment]
Didn't reproduce: https://jsfiddle.net/8Lo451t2/1/ .

Make sure you're not referencing the same array in both of your components.

**Comment by lazybonee** [comment]
@Leopoldthecoder Yes..Sorry for the bug report.I misused the same array in my components.
