### ISSUE TITLE
[Bug Report] el-select requires 2 tabs when using multiple and filterable

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#11549]
### Element UI version
2.4.1

### OS/Browsers version
Windows 10 / Chrome - latest

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/9s2evjtp/](https://jsfiddle.net/9s2evjtp/)

### Steps to reproduce
Focus in the first el-input.
Tab to the first el-select.
Tab to the second el-select.
Hit tab.

### What is Expected?
The focus to jump to the last el-input.

### What is actually happening?
The focus remains in the el-select until you hit tab once more.

**Comment by badpunman** [comment]
>Also, it requires 2 clicks to open popper if you are focused on other input. Not always though.
https://github.com/iumag/element/commit/29c7cc23232f2551e64afa583ed6aa758260f769
this seems to fix the issue. Issue occurs with just filterable attribute alone.
