### ISSUE TITLE
Select source code listens to Keyup event processing, causing the Chinese input method to remotely search and trigger the user's expected results.

### ISSUE THREAD

**Issue by Sean-Xulw** [ElemeFE/element#11540]
### Element UI version
2.4.1

### OS/Browsers version
windows

### Vue version
2.5.17-beta.0

### Steps to reproduce
1. 远程搜索非多选模式
2. 先选中一个
3. 开启中文输入法，点击input框，输入字母，此时会触发keyup的debouncedOnInputChange回调，行为不符合预期
4. 若第一次点击input框无法触发，blur后再试一次，很容易重现

### What is Expected?
中文输入法输入后未选中时，不应该出发select的回调，比较简单的方法是不监听keyup而是监听input事件

### What is actually happening?
中文输入法输入后未选中时触发了select的回调

**Comment by Sean-Xulw** [comment]
The FAQ can't fix this issue, can someone real person look into this?

**Comment by Leopoldthecoder** [comment]
请提供 demo。

**Comment by beitaz** [comment]
我也遇到了这种情况。无论是使用 async/await 还是传统的 then callback chain 都会在第一次输入拼音后导致远程搜索失效，刷新后输入非拼音字母则可以正常使用。
