### ISSUE TITLE
[Bug Report] The collapsed menu section will appear again after page render 

### ISSUE THREAD

**Issue by sstraus** [ElemeFE/element#11553]
### Element UI version
2.4.1

### OS/Browsers version
Windows 10 / Chrome - latest in IOS emulation mode / Any touch device

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/4jyc9fep/](https://jsfiddle.net/4jyc9fep/)

### Steps to reproduce
You should work in browser compatibility mode (iPad), on JSFiddle is not very functional, but the same issue is present on your website at this url: 
http://element.eleme.io/#/en-US/component/menu

To reproduce, open a root item of the NavMenu (in collapsed example), click the first available item, choose an item from the submenu, and the menu will disappear and appear again after page rendering.

### What is Expected?
The menu section will appear again after page render if used as a content selector

### What is actually happening?
The menu section will appear again after page render if used as a content selector

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

**Comment by sstraus** [comment]
Well, but there are many touch desktops. I think that is an issue anyway.
