### ISSUE TITLE
[Feature Request] el-upload sort file order

### ISSUE THREAD

**Issue by user20161119** [ElemeFE/element#11557]
### Existing Component
是

### Component Name
el-upload

### Description
After upload photos,want to adjust the photo order .
like product photos,need a main photo in the product detail page.
Maybe drag the the photo to adjust the order is a better idea.thanks
![image](https://user-images.githubusercontent.com/123967/41189462-ea087aaa-6c00-11e8-904d-a9487d8590c6.png)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can implement your own file list with drag and drop in the default slot of `<el-upload>`.

**Comment by cloydlau** [comment]
See https://github.com/cloydlau/faim#faimageupload
