### ISSUE TITLE
[Feature Request] Server-side form validation

### ISSUE THREAD

**Issue by akorz** [ElemeFE/element#11556]
### Existing Component
Yes

### Component Name
Form

### Description
Where can I get a example how to validate from on server side?

**Comment by atilkan** [comment]
Do you know the concept of server side languages? It is out of scope of element i believe.

**Comment by akorz** [comment]
Why? I see a lot of examples for client side validation there http://element.eleme.io/#/en-US/component/form but nothing how to validate on server side. I guess it'a a lack of documentation

**Comment by atilkan** [comment]
What are you trying to accomplish? This can be done with various ways. You should be specific.

**Comment by akorz** [comment]
I want to submit my form to server. There is a very complicated validation on server. When validation fail I want to return errors and show error messages near according inputs.

**Comment by atilkan** [comment]
You should use stackoverflow for this. Very long process.
To be frank, send your form to server, get result and apply errors. You can do it for individual inputs to. Like live validation. 
sorry i can't help any further.

**Comment by akorz** [comment]
Yes, I have to apply errors. I found #1216. But I don't get the final solution. Should I set errors.my_input_name for that?

**Comment by atilkan** [comment]
Use stackoverflow. This is not a help forum.

**Comment by akorz** [comment]
Sure, https://stackoverflow.com/questions/50771887/how-to-apply-individual-error-message-in-vuejs-element It will be funny if there is no options to do that :)

**Comment by atilkan** [comment]
You can close this issue now. Be sure it is not about element, it is about lock of knowledge.

**Comment by akorz** [comment]
No, it's explicit lack of documentation of element in part of validation. Finally, I did what I wanted but I had to check source code of element ui and found some undocumented features. Sad to see how so cool project does not pay attention to such important things for full stack development like server side validation.

**Comment by osman-mohamad** [comment]
@akorz can you guide me about this . I have the same issue

**Comment by Muffinman** [comment]
Having the same problem and I found this pull request @osman-mohamad #12212 

Looks like you just need to set an `error` attribute against the form item and then it will show the validation message.

For anyone else who stumbles across this issue at the top of Google like I did:


```vue
<template>
    <div>
        <el-form ref="userForm" :rules="rules" :model="user">
            <el-form-item label="Email address" prop="email" :error="formErrors.email">
                <el-input v-model="email"></el-input>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" @click="submitForm('userForm')">Save</el-button>
            </el-form-item>
        </el-form>
    </div>
</template>

<script>
export default {
    data() {
        return {
            user: {
                email: 'example@example.com'
            },
            rules: {
                email: [
                    { required: true, message: 'Please input an email address', trigger: ['blur'] },
                    { type: 'email', message: 'Please enter a valid email address', trigger: ['blur'] }
                ],
            },
            formErrors: {
                email: null,
            }
        }
    },
    methods {
        submitForm() {
            this.$refs['userForm'].validate((valid) => {
                if (valid) {
                    this.$http.request({
                        method: 'POST',
                        url: '/endpoint',
                        data: this.user,
                    })
                    .then(() => {
                        // Success Action
                    })
                    .catch((error) => {
                        this. formErrors.email = error.response.data.errors.email[0];
                    });
                } else {
                    return false;
                }
            });
        },
    }
}
</script>
```
