### ISSUE TITLE
[Bug Report] el-row behaved strangely when using router-link.

### ISSUE THREAD

**Issue by ghost** [ElemeFE/element#11558]
### Element UI version
2.4.1

### OS/Browsers version
macos / electron

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/pipilupipixia/Vportal](https://github.com/pipilupipixia/Vportal)

### Steps to reproduce
使用electron-vue，自带router。
整个页面都在router-view内
跳转几次页面即可重现

### What is Expected?
两个el-row分别在两行

### What is actually happening?
第一次渲染（没有跳转页面时） 两个el-row分别在两行，跳转后就变为一行

**Comment by pipilupipixia** [comment]
经过查看，两者的html没有区别

**Comment by pipilupipixia** [comment]
原因是el-col放到了el-container的el-main中 去掉外面两层就解决了这个问题。
