### ISSUE TITLE
[Bug Report] El-autocomplete cannot pass async-validator once

### ISSUE THREAD

**Issue by aabc6419tw** [ElemeFE/element#11566]
### Element UI version
2.4.1

### OS/Browsers version
mac10 / googleChrome

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/aabc6419tw/pen/KeWdxP](https://codepen.io/aabc6419tw/pen/KeWdxP)

### Steps to reproduce
我想要可以帶出輸入建議放置在表單，
但是無法在點擊的第一次就通過驗證

### What is Expected?
可以在第一次點擊autocomplete就通過驗證

### What is actually happening?
我想要可以帶出輸入建議放置在表單，
但是無法在點擊的第一次就通過驗證。

**Comment by ziyoung** [comment]
把 `trigger: blur` 去掉。

**Comment by aabc6419tw** [comment]
太好了！問題解決了，非常感謝您的幫忙！
