### ISSUE TITLE
[Bug Report] The ElTable content is misplaced when there are more rows to expand and set table height

### ISSUE THREAD

**Issue by kkbblzq** [ElemeFE/element#11569]
### Element UI version
2.4.1

### OS/Browsers version
WIN7 / Chrome 66

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xzokegw4/](https://jsfiddle.net/xzokegw4/)

### Steps to reproduce
1.Open expand
2.Close expand
3.See the header and content location

### What is Expected?
Content location unchanged

### What is actually happening?
Misplaced content

**Comment by jikkai** [comment]
I can't reproduce it.
![untitled](https://user-images.githubusercontent.com/14025786/41218947-700005c6-6d8f-11e8-8abf-03b78ce29cf9.gif)

**Comment by jonasyuk** [comment]
hihi, this issue need to limit the table height to reproduce,  i have also met this issue.
