### ISSUE TITLE
关于网站视觉方面的一点小意见

### ISSUE THREAD

**Issue by zjbco2** [ElemeFE/element#1156]
因为是作为一个开发工作观看型网站，用户是会长时间看着你们的网站的，所以个人觉得，希望颜色不要太清太亮。
因为本身就是大白底了，但是再加上你们的饿了蓝还有其他的辅助颜色都很清新，表单啊边线啊什么的都很清新，整体看起来，挺刺眼的。
整体咋一看是蛮好看蛮清新的，但是停留几分钟后就开始感觉刺眼不舒服了。。。
小小建议哈

**Comment by Leopoldthecoder** [comment]
感谢建议，我们会和设计师沟通这个问题。
