### ISSUE TITLE
[Feature Request] expects NavMenu SubMenu Title to accept a click event.

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#11561]
### Existing Component
是

### Component Name
el-submenu

### Description
由于国内大环境, 很多需求都需要 submenu 的 标题可以点击, 然后进入一个页面, 虽然我知道 既然菜单有submenu 就不应该还可以点击这个逻辑, 但我已经遇到很多次这种需求了. 期望加上一个 click 事件就好了. 或者是 route 模式下 , submenu 的 index 也能 起作用最好了

**Comment by Leopoldthecoder** [comment]
`@click.native`
