### ISSUE TITLE
[Bug Report] form

### ISSUE THREAD

**Issue by yahaoli** [ElemeFE/element#11568]
### Element UI version
2.4.1

### OS/Browsers version
Google Chrome 68.0.3440.7

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/yahaoli/kzewxsn6/](https://jsfiddle.net/yahaoli/kzewxsn6/)

### Steps to reproduce
点击切换

### What is Expected?
生成一个新的form

### What is actually happening?
新的form生成 但form验证出现问题

**Comment by jikkai** [comment]
In this case, you should use `key` attribute to force replacement of the component. 
https://jsfiddle.net/kzewxsn6/1/
