### ISSUE TITLE
[Bug Report] table always get highlight current row feature no matter highlight-current-row set or not

### ISSUE THREAD

**Issue by pzgz** [ElemeFE/element#11560]
### Element UI version
2.4.1

### OS/Browsers version
macOS/Chrome 69

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/6hovps5r/](https://jsfiddle.net/6hovps5r/)

### Steps to reproduce
* Create a el-table
* Without specified `highlight-current-row`, or set with `:highlight-current-row="false"`
* The table still has highlight current row feature when click on rows

### What is Expected?
When `highlight-current-row` is not set or false, click on table row shouldn't highlight current row.

### What is actually happening?
Click on table row highlight current row all the time

**Comment by MgenGlder** [comment]
This commit does not seem to fix the bug. The error is still occurring on any table that has sort functionality on deploy preview: https://deploy-preview-11563--element.netlify.com.

**Comment by sam-araiza** [comment]
Still an issue.

**Comment by pablosebastianr** [comment]
Yes, still happening.
The highlight-current-row attribute doesn't do anything.

**Comment by ramigs** [comment]
still an issue, at least in 2.4.11
