### ISSUE TITLE
[Bug Report] el-table-column contains template when using if to show hidden report $scopedSlots.default is not a function error.

### ISSUE THREAD

**Issue by songzeng2016** [ElemeFE/element#11574]
### Element UI version
2.4.1

### OS/Browsers version
Chrome   66.0.3359.181

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2124/](https://jsfiddle.net/mmx38qxw/2124/)

### Steps to reproduce
el-table-column 使用 if 判断时，如果 el-table-column 里面包含 template 报 _self.$scopedSlots.default is not a function 错误

### What is Expected?
期待没有错误

### What is actually happening?
el-table-column 使用 if 判断时，如果 el-table-column 里面包含 template 报 _self.$scopedSlots.default is not a function 错误，有时可以正常使用，有时 el-table-column 的宽度不对

**Comment by songzeng2016** [comment]
我的项目报错位置在 element-ui.common.js  的 13638 行，我把这一行改成
return typeof _self.$scopedSlots.default === 'function' && _self.$scopedSlots.default(data);
就不会报错了，功能试了下也没影响，不知道这样修改是否合理。

**Comment by jikkai** [comment]
建议对表结构进行更改的时候加上 `key` 关键词来强制重新渲染组件以避免出现此类情况。 https://jsfiddle.net/mmx38qxw/2125/

**Comment by yubaoquan** [comment]
遇到了同样的问题

```html
      <template v-for="(column, index) of columnCfg">
        <el-table-column
          v-if="(index === 4) && (activeName === 'organ')"
          :key="index"
          :label="column.label"
          :prop="column.prop"
        >
          <template slot-scope="scope">
            <el-button
              type="text"
              :disabled="scope.row.roleAmount === 0"
              @click="showRoleUser(scope.row)"
              style="cursor: pointer;"
            >
              {{scope.row.roleAmount}}
            </el-button>
          </template>
        </el-table-column>

        <el-table-column
          v-else
          :key="index"
          :label="column.label"
          :prop="column.prop"
          :formatter="column.formatter || commonFormatter"
        />
      </template>
```

**把key改成column.prop就好了** 什么鬼??
