### ISSUE TITLE
[Bug Report] Fixed table header seems not synchronize in mobile

### ISSUE THREAD

**Issue by irron** [ElemeFE/element#11570]
### Element UI version
0.1.0

### OS/Browsers version
xiaomi v9.5.5

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2123/](https://jsfiddle.net/mmx38qxw/2123/)

### Steps to reproduce
【Mobile system browser】
Slide  <Table with fixed columns and header>

### What is Expected?
columns and headers are  synchronize 

### What is actually happening?
columns and headers are  synchronize with some delays; 
not same problem in iviewUI

**Comment by jikkai** [comment]
Element is designed for desktop. It's not compatible with mobile devices.
