### ISSUE TITLE
[Feature Request] Add auto-closable property to el-select

### ISSUE THREAD

**Issue by fergardi** [ElemeFE/element#11578]
### Existing Component
Yes

### Component Name
el-select

### Description
Add boolean property to make the el-select auto-closable after an option has been selected. Meanwhile I need to create a custom method and call it in every select I have.

https://jsfiddle.net/g0nm9uLv/11/

**Comment by jikkai** [comment]
You can implement it with a little hack code
https://jsfiddle.net/g0nm9uLv/16/

**Comment by fergardi** [comment]
Yeah but that means I need to add a new ref for every select in every view/component in my app, as well as the method (which I could perhaps add it as a mixin method, I know). Just asking for an improvement.
