### ISSUE TITLE
[Feature Request] add disableCurrent to the props of the Tree component

### ISSUE THREAD

**Issue by smalllong** [ElemeFE/element#11573]
### Existing Component
是

### Component Name
Tree

### Description
There are cases that only some Nodes can be selected as current, while others not.

For example, to build a tree with highlight-current prop, composed of department Nodes and people Nodes while the department Nodes are not selectable is impossible by now.

So I advise to add a disableCurrent prop to the props as a function which returns a Boolean indicating whether the Node can be selected as current or not. As a result, only the people Nodes on the tree can be selected as current.

**Comment by ziyoung** [comment]
I'm intended to add this feature that the node can't be highlighted when it's disabled.
