### ISSUE TITLE
2.4.1DatePicker组件修改时间报错问题

### ISSUE THREAD

**Issue by xie1922858869** [ElemeFE/element#11583]
问题重现：用v-model给DatePicker绑定一个默认的时间，通过new Date() 或指定时间戳时，选择修改时间，会报错：date.getHours is not a function
代码片段：
`<el-date-picker size="mini"  v-model="searchData.startDate"  type="date" placeholder="开始日期"></el-date-picker>`
` searchData: {
          startDate: new Date()
 }
`

**Comment by zhengshengliang** [comment]
解决了吗？

**Comment by arbing** [comment]
#11621
