### ISSUE TITLE
[Bug Report] Tree控件的节点过滤，应当显示命中节点的子节点，如果存在子节点的话

### ISSUE THREAD

**Issue by JabariZheng** [ElemeFE/element#11589]
### Element UI version
2.4.1

### OS/Browsers version
Windows 10 PRO  / Chrome 66.0.3359.181

### Vue version
2.5.15

### Reproduction Link
https://jsfiddle.net/c6td49eL/

### Steps to reproduce
在过滤输入框 输入 一级 1 ，过滤完之后应该其子节点，如果存在的话

### What is Expected?
显示过滤完之后的节点一级其子节点

### What is actually happening?
不显示其节点的子节点

**Comment by JabariZheng** [comment]
https://jsfiddle.net/c6td49eL/

**Comment by ziyoung** [comment]
@JabariZheng 我不太明白你的意思。输入 `一级 1` 后，子节点没有相匹配的，自然不会显示。

**Comment by wq0923** [comment]
确实是需要展示子节点的啊 因为搜出来之后 想选择的是子节点
