### ISSUE TITLE
[Feature Request] A field identifies the default value used by the by

### ISSUE THREAD

**Issue by Jer-X** [ElemeFE/element#11598]
### Existing Component
是

### Component Name
el-select

### Description
Now when the data type is the selected value of the string, the string will be displayed by default, but when the data type is an array of objects, when the multi-select component sets the default value, the value of the tag is set to be empty by default, and it is desirable to have a field to identify the need to read. Which field in the object is to be currentLabel. Component source code：
```javascript
getOption() {
  ...some code here
  const label = !isObject ? value : '';
  let newOption = {
    value: value,
    currentLabel: label
  };
  if (this.multiple) {
    newOption.hitState = false;
  }
 return newOption;
}
```

Hope to use a field to identify currentLabel

现在多选的数据类型是对象数组的时候设置组件默认已选中对象时，tag标签显示为空，希望能有个字段去指定读取对象里面哪个字段做为label的值

**Comment by wacky6** [comment]
给个demo吧

**Comment by Jer-X** [comment]
demo：https://jsfiddle.net/zeroJer/5rpnyvbk/
Chinese: 在远程搜索模式下或者初始的options数组为空的情况下设置v-model的值有默认值的话，是不能显示出已选择项的label项，造成空白tag。目前的hack是把已选择的项将其默认插入到option里面去，这样能获取到label的值。看了源码发现在v-model绑定为对象时默认的label会被设置为空字符串，希望能够有个类似于label-key的prop去获取当前默认值的label值
English: If the value of the v-model is set to the default value in the remote search mode or the initial options array is empty, the label item of the selected item cannot be displayed, resulting in a blank tag. The current hack is to insert the selected item into the option by default, so that the value of the label can be obtained. Looked at the source code and found that the default label will be set to an empty string when the v-model is bound to an object. I hope to have a label-key parameter to get the label value of the current default value.

**Comment by wacky6** [comment]
这个情景我不认为应该让 element 处理。类比原生 select，在没有 option 的情况下，自然应该显示为空。换句话说，select 显示出某个 option 的前提是：这个 option 在 select 的选项列表中，并且这个 option 被选择了。

从语义上来说，如果一个 option 不在 select 的选项列表中，这个 option 是无效的。

另外，如果我没有使用对象作为 el-option 的绑定值，用 prop 标明 label 字段是没有意义的。https://jsfiddle.net/gpekjmbn/

**Comment by NickeyLin** [comment]
您好，谢谢回复。

我的需求和 Jer-X 的需求有点不一样。

**Comment by wacky6** [comment]
这种情况的话，我的建议是自行封装一个组件。把不存在的选项处理一下（映射到 `{value:3, label:'已离职'}`）。

element 对这种情况做统一处理不一定合适，你的例子中，特定员工是无效值的原因可能是多个，比如：离职、安全权限不够、休假 等等

**Comment by Jer-X** [comment]
emmmmm这个的确需要商讨一下。但是对于一个默认值来说并不会去考虑option是否在select里面，而且在搜索的情况下，你不能确保之前选择的option仍然在select里面，但是之前选择的仍然是一个有效的值。从这个方面来说对于默认值用个prop去标明label就有意义了，而且绑定值为对象的情况下，我可以设置option选择的时候label为详细信息，当选择之后的label为简要信息。

**Comment by Yuliang-Lee** [comment]
@Jer-X 有同样的需求
