### ISSUE TITLE
[Feature Request] NavMenu needs hover-color configuration

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#11592]
### Existing Component
是

### Component Name
NavMenu

### Description
目前已有 background-color、text-color 和 active-text-color, 但是 hover color 居然是自动配置的. 文档说了, 只支持 HEX 格式, 但有特殊需求例如 rgba 或者 透明的情况下,  hover 就不能自动生成需要的颜色了, 这时候如果有 hover-color 可以配置 那就完美了. 不过可以暂时通过 CSS !impotent  优先级顶掉 行内css 不过真的很不优雅.

**Comment by Leopoldthecoder** [comment]
Duplicate of #7686
