### ISSUE TITLE
[Bug Report] Required rule for slider element

### ISSUE THREAD

**Issue by nunure** [ElemeFE/element#11596]
### Element UI version
2.4.1

### OS/Browsers version
Windows 7 / Chrome Version 67.0.3396.79

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/nunure/8nftqkrs/1/](https://jsfiddle.net/nunure/8nftqkrs/1/)

### Steps to reproduce
In the jsfiddle you will see a slider and an input that are both using the same rule: require: true.
They are initiated with null value in their respective v-model and submit them without putting any value in the form.

### What is Expected?
We should have an error message for each form item that is null.

### What is actually happening?
The slider component doesn't return any error message.

In the slider main file you are overwriting initial value if it's not a number:

```
if (typeof this.value !== 'number' || isNaN(this.value)) {
  this.firstValue = this.min;
} else {
  this.firstValue = Math.min(this.max, Math.max(this.min, this.value));
}
```

Maybe check if the value is nulll or undefined for this issue ?

**Comment by jikkai** [comment]
This is intended, Slider component requires `number` or `array` to initialize its value.

**Comment by nunure** [comment]
Ok I understand, it could be useful to put something on the documentation to say that the required rule is ineffective on this component ?
