### ISSUE TITLE
分页器下一页按钮偶尔不触发

### ISSUE THREAD

**Issue by zengyuanqiu** [ElemeFE/element#11602]
按下一页按钮有时不触发handleCurrentChange方法
比如搜索会把currentPage重置为1后，排序也把currentPage重置为1后
再点击下一页按钮就会偶尔不触发
`<el-pagination
      style="text-align: center;"
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :page-sizes="[2, 3, 5, 10]"
      :current-page.sync="currentPage"
      :page-size="pageSize"
      layout="sizes, prev, pager, next, jumper"
      background
      :total="userAllCount">
    </el-pagination>

    handleCurrentChange (currentPage) {
        console.log('change')
        // this.currentPage = currentPage
        this.pageChange(currentPage, this.sortProp)
      },
`
正常显示
![image](https://user-images.githubusercontent.com/30031554/41327806-7356ec58-6ef7-11e8-8721-3f6b2ecbf6d5.png)

异常显示
![image](https://user-images.githubusercontent.com/30031554/41327752-3924eec2-6ef7-11e8-977f-66e3a0b78c82.png)

**Comment by zengyuanqiu** [comment]
有没有遇到过的

**Comment by Wenyi-Jhang** [comment]
我現在也有遇到一樣的問題
發生情境是 
先在第N頁分頁，換頁用 method 改變 :current-page="currentPage" 這個Attributes的內容，設定 currentPage = M，不是透過 @current-change 換到第 M 頁
這時候再按第 N 頁分頁，頁面依然停留在第 M 頁
