### ISSUE TITLE
[Table]在指定了语言的情况下还是使用了中文

### ISSUE THREAD

**Issue by NemoAlex** [ElemeFE/element#1160]
### OS/Browers version
Chrome 54

### Vue version
2.0.3

### Steps to reproduce
```
import ElementUI from 'element-ui'
import locale from 'element-ui/lib/locale/lang/en'
Vue.use(ElementUI, { locale })
```

### What is Expected?
使用英文

### What is actually happening?
还是中文，例如 emptyText 是“暂无数据”

日期组件工作正常

**Comment by QingWei-Li** [comment]
fixed via https://github.com/ElemeFE/element/pull/1145

**Comment by 6gunner** [comment]
2.6.1这个版本还是存在这个bug似乎
