### ISSUE TITLE
分页器的下一页按钮有时不触发

### ISSUE THREAD

**Issue by zengyuanqiu** [ElemeFE/element#11600]
按下一页按钮有时不触发handleCurrentChange方法
`<el-pagination
      style="text-align: center;"
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :page-sizes="[2, 3, 5, 10]"
      :current-page.sync="currentPage"
      :page-size="pageSize"
      layout="sizes, prev, pager, next, jumper"
      background
      :total="userAllCount">
    </el-pagination>

    handleCurrentChange (currentPage) {
        console.log('change')
        // this.currentPage = currentPage
        this.pageChange(currentPage, this.sortProp)
      },
`
正常显示
![image](https://user-images.githubusercontent.com/30031554/41327806-7356ec58-6ef7-11e8-8721-3f6b2ecbf6d5.png)

异常显示
![image](https://user-images.githubusercontent.com/30031554/41327752-3924eec2-6ef7-11e8-977f-66e3a0b78c82.png)

**Comment by zhengshengliang** [comment]
第二幅图应该是因为点了查询， 你应该在查询里将页码重置为1吧
```
            submitForm(formName) {
                this.$refs[formName].validate((valid) => {
                    if (valid) {
                        this.View.currentPage = 1;
                        this.query();
                    } else {
                        return false;
                    }
                });
            },
            query() {
                const params = {
                    ...this.View.queryParams,
                    currentPage: this.View.currentPage,
                    pageSize: this.View.pageSize,
                };
          }
```
