### ISSUE TITLE
[Feature Request] suggests adding el-switch toggle to display the corresponding text in the component.

### ISSUE THREAD

**Issue by xuliangzhan** [ElemeFE/element#11606]
### Existing Component
是

### Component Name
el-switch

### Description
active-text和inactive-text属性只能将内容显示在外面，如果希望文本内容显示在组件里面怎么处理？

**Comment by Leopoldthecoder** [comment]
我们没有提供相关 API 的计划，请使用 CSS 对文本样式进行覆盖。

**Comment by qiangbro** [comment]
@Leopoldthecoder 有示例代码么，我不太明确要怎么使用 CSS 对文本样式进行覆盖呢？

**Comment by cloydlau** [comment]
This will do it:

```vue
<template>
  <PopSwitch
    active-text="上架"
    inactive-text="下架"
  />
</template>

<script>
// install 'kikimore' first
import { PopSwitch } from 'kikimore'

export default {
  components: { PopSwitch }
}
</script>
```

Width is self-adapting, document [here](https://github.com/cloydlau/kikimore)
