### ISSUE TITLE
el-upload在IE10上的BUG

### ISSUE THREAD

**Issue by LCattle** [ElemeFE/element#11612]
上传成功一个件（aaa.pdf）之后，删除当前上传的文件，当第二次选择同一个文件（aaa.pdf）的时候，没有反应，所有的钩子函数都不执行，如果选择（bbb.pdf）跟第一个文件不同则没有这个BUG，在IE11、chrome和FF都是可以的，唯独IE10不行，不知道有没有遇到同样问题 的大神，假如有幸能被您看到，那麻烦留一下解决方案！在线等！

**Comment by jingyuhao1995** [comment]
> 上传成功一个件（aaa.pdf）之后，删除当前上传的文件，当第二次选择同一个文件（aaa.pdf）的时候，没有反应，所有的钩子函数都不执行，如果选择（bbb.pdf）跟第一个文件不同则没有这个BUG，在IE11、chrome和FF都是可以的，唯独IE10不行，不知道有没有遇到同样问题 的大神，假如有幸能被您看到，那麻烦留一下解决方案！在线等！

请问咋解决的
