### ISSUE TITLE
el-form-item 里 el-select 验证失效，checkbox-group 选一个结果全选了

### ISSUE THREAD

**Issue by old-bin** [ElemeFE/element#11618]
我一个 form 表单，每一个 el-form-item 都设置了 prop, el-input 的验证没有问题，但是 el-select 验证不起作用，el-checkbox-group 选中也有问题

el-select 和 el-checkbox-group 都是有子元素的，所以很可能是 el-form-item 的 prop 不对作用这种类型的结构。

代码：
```
<el-form :model="formData" :rules="formRules" ref="formData">
	<el-form-item label="描述" prop="description" :label-width="'150px'">
        <el-input v-model="formData.description" auto-complete="off"></el-input>
    </el-form-item>
    <el-form-item label="分类--这里的验证不生效" prop="category" :label-width="'150px'">
        <el-select v-model="formData.category" placeholder="业务分类" @change="selectList">
            <el-option
                v-for="item in fields.category"
                :key="item.value"
                :label="item.label"
                :value="item.value">
            </el-option>
        </el-select>
    </el-form-item>
    <el-form-item label="配置--这里的checkbox的单个选中会触发全部选中" prop="config" :label-width="'150px'">
        <el-checkbox-group v-model="formData.config" v-for="(item, key) in configFieldList">
            <el-checkbox :label="item" name="config" :key="key">{{item}}</el-checkbox>
        </el-checkbox-group>
    </el-form-item>
</el-form>
```

**Comment by mdh-git** [comment]
el-checkbox-group 这个如果是编辑，传值过来，校验规则总是在，问题好多，官网的例子我试了，重置都不能用。。。。

**Comment by tulies** [comment]
> 我一个 form 表单，每一个 el-form-item 都设置了 prop, el-input 的验证没有问题，但是 el-select 验证不起作用，el-checkbox-group 选中也有问题
> 
> el-select 和 el-checkbox-group 都是有子元素的，所以很可能是 el-form-item 的 prop 不对作用这种类型的结构。
> 
> 代码：
> 
> ```
> <el-form :model="formData" :rules="formRules" ref="formData">
> 	<el-form-item label="描述" prop="description" :label-width="'150px'">
>         <el-input v-model="formData.description" auto-complete="off"></el-input>
>     </el-form-item>
>     <el-form-item label="分类--这里的验证不生效" prop="category" :label-width="'150px'">
>         <el-select v-model="formData.category" placeholder="业务分类" @change="selectList">
>             <el-option
>                 v-for="item in fields.category"
>                 :key="item.value"
>                 :label="item.label"
>                 :value="item.value">
>             </el-option>
>         </el-select>
>     </el-form-item>
>     <el-form-item label="配置--这里的checkbox的单个选中会触发全部选中" prop="config" :label-width="'150px'">
>         <el-checkbox-group v-model="formData.config" v-for="(item, key) in configFieldList">
>             <el-checkbox :label="item" name="config" :key="key">{{item}}</el-checkbox>
>         </el-checkbox-group>
>     </el-form-item>
> </el-form>
> ```

+1 我也碰到 不知如何解决。你搞定了吗

**Comment by tulies** [comment]
+1 我也碰到 不知如何解决。你搞定了吗
