### ISSUE TITLE
[Bug Report] When there has only one input field in a el-form and clicks enter in the input, the URL which with has will be changed

### ISSUE THREAD

**Issue by cherry200604** [ElemeFE/element#11613]
### Element UI version
2.4.1

### OS/Browsers version
Version 67.0.3396.87 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/8toj5s4c/](https://jsfiddle.net/8toj5s4c/)

### Steps to reproduce
1. Click the enter in the input field and see nothing happened
2. Update the url to https://jsfiddle.net/#/8toj5s4c/ and run again
3. Do the step 1 again
4. Will see the result become to 404 not found

You can reproduce this issue in the official website here: http://element.eleme.io/#/en-US/component/form#number-validate

after you click enter, the page will reload again and the url will change to http://element.eleme.io/?#/en-US/component/form#number-validate

### What is Expected?
The page should not reload again with change the url when there has only one field in a el-form

### What is actually happening?
The page will reload and the url with hash will be changed (Add like a ?query= in front of the hash(#))
e.g.:
http://element.eleme.io/#/en-US/component/form
becomes to
http://element.eleme.io/?#/en-US/component/form

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/41343244-a346c3aa-6f30-11e8-81cb-d3a1c1468bba.png)

**Comment by cherry200604** [comment]
@Leopoldthecoder Actually I did add such as `@submit.prevent="submitForm"` and `@submit.native.prevent="submitForm"`on `<el-form>` but both of them don't work.

**Comment by cherry200604** [comment]
Found my error. Sorry for disturb and thank you!
