### ISSUE TITLE
DOM is not cleared after [Bug Report] message is closed

### ISSUE THREAD

**Issue by 735900718** [ElemeFE/element#11615]
### Element UI version
2.4.0

### OS/Browsers version
macOS 10.13.3 / chrome 67

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/zre075tp/](https://jsfiddle.net/zre075tp/)

### Steps to reproduce
在当前页面时没问题，但是页面最小化或者切换出去后，在开发者工具中可以看到，弹窗的dom元素并未被删除。

### What is Expected?
弹窗dom会被删除掉

### What is actually happening?
弹窗dom在页面最小化或者切换出去后并未被删除

**Comment by ziyoung** [comment]
@735900718 是这样的。
https://github.com/ElemeFE/element/blob/0178893db16a273e29af3dcbc5837281f821df3c/packages/message-box/src/main.vue#L2-L7

这里使用了 v-show 来控制显示与隐藏。组件没有销毁，只是隐藏了。

**Comment by 735900718** [comment]
应该销毁这个dom才对，否则dom会越积越多。而且在当前页面下这个dom确实会被销毁，只是在页面切换出去后才会发生dom不销毁的现象。
