### ISSUE TITLE
[Bug Report] <el-form-item> required indicator on wrong side for label-position top or left

### ISSUE THREAD

**Issue by d--j** [ElemeFE/element#11619]
### Element UI version
2.4.1

### OS/Browsers version
All

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/bahc1Lve/](https://jsfiddle.net/bahc1Lve/) (includes a fix in the SCSS)  
https://elementui.github.io/issue-generator/#/en-US Your own issue generator has label-position top

### Steps to reproduce
Have a `<el-form-item>` inside a `<el-form>` with a `label-position` of `top` or `left`. This `<el-form-item>` has a `label` and is `required`.

```vue
<el-form label-position="top">
  <el-form-item label="Name" required></el-form-item>
</el-form>
```

### What is Expected?
The required indicator (the red *) should be on the right side of the label.

### What is actually happening?
The required indicator is on the left side of the label.

**Comment by ziyoung** [comment]
According to the [doc](http://element.eleme.io/#/en-US/component/form#alignment), the `label-position` attribute decides how labels align. This does not affect how the identifier is placed.

**Comment by ziyoung** [comment]
I think users can decide the position of the indicator by using CSS.
