### ISSUE TITLE
[Bug Report] DatePicker throw TypeError: e.getHours is not a function, When, a,

### ISSUE THREAD

**Issue by arbing** [ElemeFE/element#11621]
### Element UI version
2.4.1

### OS/Browsers version
All

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/1ouzpf5c/](https://jsfiddle.net/1ouzpf5c/)

### Steps to reproduce
DatePicker 组件 v-model 绑定非空值，类型是字符串或者数值，不能正常选择其他日期。

抛出异常：
[Vue warn]: Error in event handler for "pick": "TypeError: e.getHours is not a function"
    at t.modifyDate (index.js:1)
    at Vue.handleDatePick (index.js:1)
    at VueComponent.invoker (vue.js:2029)
    at VueComponent.Vue.$emit (vue.js:2538)
    at VueComponent.handleClick (index.js:1)
    at invoker (vue.js:2029)
    at HTMLTableElement.fn._withTask.fn._withTask (vue.js:1828)

v2.4.0是正常的

https://jsfiddle.net/j1h0pysw/

### What is Expected?
DatePicker 组件 v-model 绑定值类型可以是字符串或者数值

### What is actually happening?
DatePicker 组件 v-model 绑定值类型只能是 Date

**Comment by Leopoldthecoder** [comment]
如果你需要 value 的值为字符串，请指定 `value-format`：https://jsfiddle.net/1ouzpf5c/3/

**Comment by arbing** [comment]
`value-format` 属性是可选的，因为后端api返回字段类型字符串和`timestamp`都有，之前都未指定具体值。升级到v2.4.1后，发现日期组件都不能用了。

**Comment by arbing** [comment]
`value-format`未指定时，是否可以跟`default-value`一样，用`new Date()`解析下

**Comment by Leopoldthecoder** [comment]
@wacky6 这个改动是计划中的吗？

**Comment by wacky6** [comment]
这么没有计划改。字符串进，Date对象出并不像是一个好主意。

**Comment by arbing** [comment]
绑定值是JS时间戳，也会有同样的问题：

v2.4.1：https://jsfiddle.net/1ouzpf5c/5/
v2.4.0：https://jsfiddle.net/j1h0pysw/2/

清除一次值，再次选择日期，就不报错了

**Comment by wacky6** [comment]
这个issue我重新看了一下，出现问题的用法是 文档上没有说的 / 非最佳实践。文档说明或提供样例代码的「指定 value-format 并传入字符串/时间戳」 或 「不指定 value-format 并传入 Date」这两种情况是没有问题的。

2.0 date-picker重构后，文档已说明「默认情况下，组件**接受**并**返回** Date 对象」。出错的用法为传入 string 或 timestamp，且没有指定 value-format，并期望组件输出 Date 对象。

这个用法以前没有挂，但现在挂了是因为：
1. picker 内部没有做严格的类型检测
2. #11450 修复之前，date-time-picker 在发射日期时，使用了内部的date属性，该属性一定是Date对象，用来标示面板当前显示的年月（而不是用户已经选择的时间）
3. 如果制定了 value-format，picker会按照格式解析绑定值，得到对应的Date对象，并将这个对象传给面板。如果没有指定value-format，不会对绑定值作出处理。这一行为参照文档中「默认为Date对象」的说明。
4. 面板的 value（用户已选值）应当为 Date 对象。picker.vue 会根据3中行为处理组件绑定值。在未指定value-format且传入了非Date对象的情况下，面板拿到的不是Date，于是导致了`.getTime()`调用出错。

---

如果现在挂了，怎么办：

* 锁2.4.0版本
* 指定value-format 或 自行解析非Date输入（比如：https://jsfiddle.net/j1h0pysw/5/
* 让后端统一格式，然后更新前端代码

---

@Leopoldthecoder 
老大看一下这个 issue 到底要不要处理。

1. 让组件容忍文档未提及且不符合最佳实践的做法并不是好主意。
2. 如果未来还要重构，这样的用法也不会被考虑的（以后还是会挂掉）
3. 如果要修：
    * 在 picker 里面检测不正确用法，立刻emit `new Date(value)`后的值刷新绑定值 -> 会出发额外的input事件，并且会触发watch，可能影响到form的change验证
    * 在 modifyTime / modifyDate 里面修 -> 多余代码和if判断

**Comment by axetroy** [comment]
@wacky6 

2.4.1版本，输入Date，输出string

```html
          <el-col :span="11">
            <el-time-picker placeholder="开始时间" :default-value="form.startTime" v-model="form.startTime" style="width:100%"></el-time-picker>
            {{typeof form.startTime}} {{form.startTime}}
          </el-col>
          <el-col class="line" :span="2">-</el-col>
          <el-col :span="11">
            <el-time-picker placeholder="结束时间" :default-value="form.endTime" v-model="form.endTime" style="width:100%"></el-time-picker>
            {{typeof form.endTime}} {{form.endTime}}
          </el-col>
```

![1](https://user-images.githubusercontent.com/9758711/41583711-eb9a8712-73d7-11e8-8be6-40ed9ee7d802.png)

然后点击选择时间就报1楼的错...

**Comment by wacky6** [comment]
@axetroy 未能复现，有问题请写jsfiddle或codepen提供demo。另外，default-value通常不会和v-model指向同样的变量。

**Comment by Leopoldthecoder** [comment]
@wacky6 现在的主要问题其实是在一个 patch 版本中引入了向后不兼容的改动。确实修改之后更合理一些，不过似乎放在 minor 或者 major 版本里更好。最近看到有一些用户反馈这个问题，所以最好先兼容一下吧。

BTW, there may not be another minor version for 2.x, if you know what I mean. So are you available for the refactor as mentioned in #9878?

**Comment by wacky6** [comment]
好的。这个兼容我稍后处理一下。大版本更新再移除。

---

For refactoring, I can not promise any time at the moment. My next semester starts next month (graduation project / thesis, internship, employment, etc.), and I have other works at hand now.

But I am generally happy to try and elaborate on some designs that might be helpful to refactoring, so it can be helpful to whoever is going to implement it (me or others).

**Comment by Leopoldthecoder** [comment]
@wacky6 Sure. I'll consider how we can handle the refactoring.

**Comment by Leopoldthecoder** [comment]
#11673
