### ISSUE TITLE
v1.0.1，el-switch @change觸發時機似乎有誤

### ISSUE THREAD

**Issue by red010182** [ElemeFE/element#1162]
如以下範例([v1.0.1](https://unpkg.com/element-ui@1.0.1/lib/index.js))，照理說文字永遠應該=switch的值，但卻不然。switch在第一次切換的時候後，不會更新`onOffCopy`
[DEMO](https://jsfiddle.net/pytsao/txLdjp18/18/)

change鉤子似乎是在model被修改之前觸發？
建議把鉤子做更精確的命名：例如用 willChange, didChange，否則搞不太清楚到底值變更了沒

```
<div id="app">
  <el-switch v-model="onOff" @change="onSwitch"></el-switch>
  <p>{{ onOffCopy ? "ON" : "OFF" }}</p>
</div>

var vm = new Vue({
  el: '#app',
  data: {
    onOff:true,
    onOffCopy:true  
  },
  methods: {
    onSwitch() {
      this.onOffCopy = this.onOff;
    }
  }
});
```

此外，[v1.0.0](https://unpkg.com/element-ui@1.0.0/lib/index.js)是正常的。

**Comment by Leopoldthecoder** [comment]
是 bug，已在 #1166 修复。有兴趣的话可以在 [这里](https://github.com/ElemeFE/element/tree/dev/src/locale/lang) 贡献一下正体中文的 i18n😁

**Comment by QingWei-Li** [comment]
fixed via #1166
