### ISSUE TITLE
Multiple Form-Item combination validation of [Feature Request] Form component validator

### ISSUE THREAD

**Issue by a631807682** [ElemeFE/element#11638]
### Existing Component
是

### Component Name
Form

### Description
问题
-----
我有一个`Form`组件，里面有多个`Form-Item`，而这多个组件我只需要验证通过一个，整体就算通过。
比如我需要填写**手机/座机/邮箱**其中一个，就能验证通过。
当然可能通过比如`radio/v-if`，或者共用一个`Form-Item`来曲线救国，但是这样限制了`UI`设计。
由于`Form`的`validate`依赖于`Form-Item`的`validate`，所以我目前只能想到这样做 [https://jsfiddle.net/j03saev7/](https://jsfiddle.net/j03saev7/)，但其实很不方便。

期望
----
希望在`validate`之前有个拦截器，让我执行某些逻辑，然后决定继续使用`validate`或直接抛出`prop`所关联的`Field`的错误。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. Another possible (and simpler) solution would be https://jsfiddle.net/j03saev7/5/ .

**Comment by a631807682** [comment]
好吧，事实上这个表单肯定不止几项，并且不修改变原来的验证。那就先这样吧[https://jsfiddle.net/j03saev7/12/](https://jsfiddle.net/j03saev7/12/)
