### ISSUE TITLE
怎么收缩导航呢，官方文档就写了一个可以收缩，怎么收缩呢

### ISSUE THREAD

**Issue by DullSky** [ElemeFE/element#1163]
![image](https://cloud.githubusercontent.com/assets/15259698/20389475/becf8b24-ad04-11e6-989b-722519b15bb0.png)

**Comment by Leopoldthecoder** [comment]
目前还没有做这个功能，后续会添加。

**Comment by Jiiiiiin** [comment]
欧买噶~~
