### ISSUE TITLE
When [Feature Request] cascade selector is loaded asynchronously, it is hoped to increase the default value.

### ISSUE THREAD

**Issue by zhongxx** [ElemeFE/element#11632]
### Existing Component
是

### Component Name
Cascader 级联选择器

### Description
级联选择器异步加载时，希望能增加默认值

**Comment by ziyoung** [comment]
选项都没有加载完，怎么选择默认值？

**Comment by zhongxx** [comment]
级联选择器返回的结果是怎样，就可以遵循此格式传入值作为默认值。
假设区域级联选择返回的结果是{key:'1.2.3',value:'广东.广州.天河'}，那我在设置里配置默认值为{key:'1.2.3',value:'广东.广州.天河'}不就 ok 了？

**Comment by jikkai** [comment]
这个可以自行实现，比如在异步数据返回前，直接用返回结果去填充级联选择器的数据源，等异步数据返回后再替换即可。

**Comment by zhongxx** [comment]
个人觉得这中与业务无关的功能，应该归到组件功能中

**Comment by jikkai** [comment]
这个恰恰属于业务问题。出于具体需求、接口实现等等因素，不同的业务对数据源的处理往往是不一样的。
组件在设计和实现上面临的问题不仅仅是“是否与业务相关”，还需要考虑通用性和向下兼容等等诸多因素。因此该功能暂时不会被实现。

**Comment by laosandegudai** [comment]
当使用异步加载时，使用的是 active-item-change 事件，此时若想启用  选择即改变  功能则导致 active-item-change事件无效，目前现象是启用 active-item-change 事件异步加载数据则无法选中任意项只能一路到底选择父目录，不知道该咋办了，有米有子项点击事件的口子也好作处理。

**Comment by guohuihot** [comment]
> 个人觉得这中与业务无关的功能，应该归到组件功能中

这个功能虽然自己可以开发，但是我也觉得应该是组件本身的功能，iview人家也实现了，我用时还专门查这个功能，谁知道没有

**Comment by Veyhunk** [comment]
https://github.com/ElemeFE/element/issues/16136
