### ISSUE TITLE
Can [Feature Request] el-table make the characteristic of listview?

### ISSUE THREAD

**Issue by wuchuguang** [ElemeFE/element#11630]
### Existing Component
是

### Component Name
el-table

### Description
:data="data"很大时，el-table会很卡，（data做分列，但体验不好）
能否加listview特性，只渲染data里正在el-table可视内的column，不需要把所有data全渲染出来。
提供配置如：show-item-count     start,   end,   bench

**Comment by Leopoldthecoder** [comment]
Duplicate of #9761
