### ISSUE TITLE
[Feature Request] Tabs can add hash, if the tabs table below, table, hash

### ISSUE THREAD

**Issue by xcsweb** [ElemeFE/element#11639]
### Existing Component
是

### Component Name
Tabs

### Description
Tabs can add hash, if the tabs table below, there are changes, then return to the first tabs page
![](https://ws1.sinaimg.cn/large/af65cd95gy1fsboxilu4fj20l90c8wez.jpg)

**Comment by Leopoldthecoder** [comment]
没有看懂你的描述，请使用中文。

**Comment by jikkai** [comment]
@xcsweb 
可以通过指定 `v-model` 的值实现你的需求
https://jsfiddle.net/k7y2zbaj/2/
