### ISSUE TITLE
[Bug Report] el-tree allowDrop breaks if .el-tree-node__content height is too large

### ISSUE THREAD

**Issue by hsindesu** [ElemeFE/element#11635]
### Element UI version
2.4.1

### OS/Browsers version
Windows 10/ Chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/yancyknight/pen/VdzyBr](https://codepen.io/yancyknight/pen/VdzyBr)

### Steps to reproduce
```js
allowDrop: function(draggingNode, dropNode, type) {
      if (type !== 'inner') {
        return false;
      }
      return true;
}
```

When the .el-tree-node__content is default height, this works as expected and disallows drops between nodes. If you give .el-tree-node__content class 48px height, margin, or padding (whatever increase the overall height of the tree node), it allows drops between nodes and sometimes will drop in the wrong place if you do try to drop between nodes.

### What is Expected?
allowDrop will perform as expected regardless of .el-tree-node__content height.

### What is actually happening?
el-tree is allowing nodes to be dropped even though allowDrop is returning false.

**Comment by MrLiuTY** [comment]
我也遇到了同样的问题，.el-tree-node__content自定义高度超过了默认高度拖拽会出现异常

**Comment by MrLiuTY** [comment]
@ziyoung 能给一个可调试的链接么。我把修复后的代码覆盖到我项目中依然会出错。我仔细看看是不是我这边出了问题。十分感谢
