### ISSUE TITLE
[Bug Report] Pagination paging style error

### ISSUE THREAD

**Issue by bigzs** [ElemeFE/element#11640]
### Element UI version
2.4.1

### OS/Browsers version
WIN10/Google Chrome 67.0.3396.87

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击分页条数，图标不在中间

### What is Expected?
分页的每页条数下拉图标应该在中间

### What is actually happening?
分页的每页条数下拉图标错位，偏上

**Comment by Leopoldthecoder** [comment]
请更新 demo

**Comment by evolutionjay** [comment]
<img width="1072" alt="wx20180619-160123 2x" src="https://user-images.githubusercontent.com/4468540/41585191-eb10b8bc-73db-11e8-9d7c-b5d383ca22c2.png">
同个问题, 今天更新了一下custom theme 就出现了, 是不是因为 custom theme 的问题?

**Comment by Leopoldthecoder** [comment]
Fixed in #11622
