### ISSUE TITLE
After the [Bug Report] project is packaged, the button system becomes larger in the windows system, and the development environment and the macOS system are normal.

### ISSUE THREAD

**Issue by guchunwen** [ElemeFE/element#11647]
### Element UI version
2.4.1

### OS/Browsers version
windows/chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2311/](https://jsfiddle.net/mmx38qxw/2311/)

### Steps to reproduce
按钮设置size=“small”后，在windows的dev  以及macOS的dev和build都是正常small尺寸，
但是在windows的build后  尺寸变大，手动设置高度为33px后才符合small的尺寸

### What is Expected?
应该兼容windows的build才对

### What is actually happening?
不兼容windows的build

**Comment by Leopoldthecoder** [comment]
请提供最小化可重现问题的项目仓库。
