### ISSUE TITLE
[Bug Report] ElTransfer After moving left and right, the selected data selected

### ISSUE THREAD

**Issue by clys** [ElemeFE/element#11645]
### Element UI version
2.4.1

### OS/Browsers version
OS:Deepin 4.14.12-2 Explorer:Chrome/63.0.3239.132

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2301/](https://jsfiddle.net/mmx38qxw/2301/)

### Steps to reproduce
@right-check-change的返回值保存到一个变量
将右边列表勾选的数据左移

### What is Expected?
@right-check-change得到的变量变为空

### What is actually happening?
@right-check-change得到的变量没有变化

**Comment by jikkai** [comment]
是不是忘记给 @right-check-change 赋值了 https://jsfiddle.net/mmx38qxw/2304/

**Comment by clys** [comment]
= =额 放上来的确实是个@right-check-change忘记写了的 不过问题并不是这个  
在勾选右边2个后rightCheck得到了2个值  然后我把右边的东西移动到左边rightCheck里还是有这2个

**Comment by jikkai** [comment]
@clys 因为你是在触发 right-check-change 的时候自己做的赋值操作，移动过去后没有触发任何能够给你你创建的这个变量赋值的操作。想要清空的话可以在 change 事件里处理 https://jsfiddle.net/mmx38qxw/2307/
