### ISSUE TITLE
[Feature Request] how to double click to edit?

### ISSUE THREAD

**Issue by weituotian** [ElemeFE/element#11642]
### Existing Component
否

### Component Name
DoubleClickEdit

### Description
when double click, to edit the content

**Comment by Leopoldthecoder** [comment]
什么组件？

**Comment by weituotian** [comment]
@Leopoldthecoder 
```
Existing Component
no
```

**Comment by Leopoldthecoder** [comment]
我的意思是，你需要在哪个组件上实现双击编辑功能？

**Comment by weituotian** [comment]
比如说标签组件。

还有input组件，希望它通常的时候显示文字，双击进入编辑模式。

For example, the label component.

There is also an input component, which is expected to display text when int normal time, and double-click to enter edit mode.

**Comment by jikkai** [comment]
这并不是一个常见通用的需求，并且通常来说开发者可以通过一些简单的 hack 手段实现[类似效果](https://jsfiddle.net/zhk2o7br/3/)，所以我们暂无实现此类组件的计划。

**Comment by weituotian** [comment]
@jikkai 你们那边封装一下不好吗？这个不难吧？给一个参数来控制，需要用到的人就打开，比如说在标签组件那里增加一个doubclickEdit参数

**Comment by weituotian** [comment]
@jikkai @ziyoung 
刚去参加了开源论坛，问了一位讲师，他说这根本是在耍流氓。优秀的开源作品，完全可以以examples的方式来扩展组件，examples里面的组件是完全开放给用户，由用户自主控制和维护的，不加入也不影响核心组件。当我说我用的仓库是饿了么的时候，他说不敢相信，饿了么也算家喻户晓的大公司了，但是开源作品却让人感到缺乏一些专业精神，做不到更高更远。

**Comment by jikkai** [comment]
非常感谢您的建议，我个人的想法是，该需求的实现会带来较多的冗余代码，更多的冗余也就意味着失去可控性和可用性的风险，甚至可能带来一些不必要的破坏性更新。这对已经在使用 element 的广大开发者来说这或许不是一件好事，因此暂时不考虑实现该功能，请您谅解。

若有相关后续计划，我们会在此 issue 内告知您，如果有更好的建议也希望您可以继续提出，当然我们也非常欢迎解决方案的 PR :)

**Comment by jikkai** [comment]
关于这个问题，[社区](https://github.com/ElementUI/awesome-element)提供了一些解决方案，其中不乏有涉及面较全的 https://github.com/PanJiaChen/vue-element-admin

同时我们现阶段确实在着手规划提供实用 examples 相关的工作，再次非常感谢您的鞭策和建议 😀
