### ISSUE TITLE
[Bug Report] MessageBox VNode is unable to get the value of the form element when it is a form element.

### ISSUE THREAD

**Issue by OneAndOnly1111** [ElemeFE/element#11644]
### Element UI version
2.4.1

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/limeiling/surnce2L/](https://jsfiddle.net/limeiling/surnce2L/)

### Steps to reproduce
选中checkbox， 点击确定无法获取值

### What is Expected?
期望有示例告知如何获取表单元素的值， 
在此示例为如何获取 el-checkbox的值

### What is actually happening?
无法获取，也无法添加事件

**Comment by ziyoung** [comment]
使用 [dialog](https://element.faas.ele.me/#/zh-CN/component/dialog)。

**Comment by jikkai** [comment]
你需要为 checkbox 手动绑定 value 和 input 事件，参考：
https://cn.vuejs.org/v2/guide/render-function.html#v-model
