### ISSUE TITLE
[Feature Request] Select dropdown (popover) customization

### ISSUE THREAD

**Issue by ar53n** [ElemeFE/element#11649]
### Existing Component
Yes

### Component Name
Select

### Description
Have any possibilities for customizing popover for select. Like an increase min-width

**Comment by Leopoldthecoder** [comment]
If you're trying to customize its style, please write your own CSS to override it.

**Comment by ar53n** [comment]
@Leopoldthecoder just have the problem with the scroll in dropdown. We can't manipulate with it. When we customize height we have some problem.
