### ISSUE TITLE
table inline-template渲染bug

### ISSUE THREAD

**Issue by chenkby** [ElemeFE/element#1165]
eui ver:1.0.1

1.0没发现这个问题

```
          <el-table-column label="操作" align="right" width="120px" inline-template>
            <div>
              <a href="javascript:" @click="editRowHandle(row.id)">修改</a>
              <span>|</span>
              <a href="javascript:;" @click="deleteRowHandle(row.id)">删除</a>
            </div>
          </el-table-column>
```

上面这段代码在1.0是可以的，然后在1.0.1中出现这个错误

```
vue.js?b6db:2611 [Vue warn]: Error when rendering component <table-body>: warn @ vue.js?b6db:2611Vue._render @ vue.js?b6db:2243(anonymous function) @ vue.js?b6db:1695get @ vue.js?b6db:740run @ vue.js?b6db:809flushSchedulerQueue @ vue.js?b6db:627nextTickHandler @ vue.js?b6db:405
2vue.js?b6db:2301 Uncaught TypeError: Cannot read property 'call' of undefined
```

一开始我以为是span标签的问题，各种换标签问题依旧，最后改成这样才可以：

```
<span :class="row.id">|</span>
```

**Comment by QingWei-Li** [comment]
似乎和你给的这段代码没啥关系，我按照你给的写了一份 http://jsfiddle.net/g6kmfov5/ 并没有重现，不清楚 https://github.com/ElemeFE/element/pull/1161 这里的修复是不是能解决你的问题

**Comment by chenkby** [comment]
应该是vue或者是vue-loader的版本问题。
vue  2.0.1 => 2.0.7
vue-loader 9.4.0 => 9.9.5

**Comment by yidazh** [comment]
我也遇到了。
element 1.0.0 vue-loader 9.9.0时，inline-template有bug，按照示例嵌入 `<span><el-button>button</el-button>`出错，1.0.1的changelog里提到的应该就是这个bug；

升到1.0.1后，出现新bug，嵌入静态HTML则出错`<div>2333</div>`，换成动态内容则无问题`<div>{{row.id}}</div>`

**Comment by yidazh** [comment]
element 1.0.2 vue-loader 9.9.5 问题解决了
