### ISSUE TITLE
[Bug Report]failed to lint css

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#11657]
### Element UI version
the newest

### OS/Browsers version
all

### Vue version
the newest

### Reproduction Link
none

### Steps to reproduce
1. npm run lint
2. failed to lint

![image](https://user-images.githubusercontent.com/1060733/41525202-c2ef6b2c-7312-11e8-9afc-7c9653a23049.png)

**Comment by jikkai** [comment]
Duplicate of #11343
