### ISSUE TITLE
[Bug Report] PopperJS is not a constructor

### ISSUE THREAD

**Issue by chencanbin** [ElemeFE/element#11653]
### Element UI version
2.4.1

### OS/Browsers version
Win10/Chrome

### Vue version
2.5.16

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
按照官网的demo 写select 组件，组件点击出现PopperJS is not a constructor

### What is Expected?
期望如官网的效果

### What is actually happening?
select 样式错乱， 报 “PopperJS is not a constructor”错误

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by kim-jeongki** [comment]
You must config in babel-loader exclude options below code
```js
rules: [
    {
        loader: 'babel-loader',
        include: [ __dirname + '/src/, __dirname + '../node_modules/element-ui/src/utils'],
        exclude: /node_modules\/element-ui\/src\/(utils\/popper\.js|utils\/date.\js)/
   }, ...
```

**Comment by jocabrera** [comment]
This is the correct way of excluding modules for windows.

/node_modules\\element-ui\\src\\(utils\\popper\.js|utils\\date\.js)/

**Comment by qiangbro** [comment]
what for vue/cli 3+?
