### ISSUE TITLE
[Bug Report] autocomplete on input elements always gets set to 'off' instead of the actual value

### ISSUE THREAD

**Issue by bartvanremortele** [ElemeFE/element#11650]
### Element UI version
2.4.1

### OS/Browsers version
OS X / Chrome 67.0.3396.87  

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/bartvanremortele/wnbucrg8/](https://jsfiddle.net/bartvanremortele/wnbucrg8/)

### Steps to reproduce
Set password autocomplete to "new-password", inspect html to see that it's being set to "off"

### What is Expected?
Expected is that autocomplete takes the value from the el-input element and applies it to the input element.

### What is actually happening?
Value is always being set to "off"

**Comment by Leopoldthecoder** [comment]
For now you need to assign `auto-complete` on `<el-input>`: https://jsfiddle.net/wnbucrg8/3/ . We'll support the native `autocomplete` attribute in the next major version.

**Comment by mistabiggx** [comment]
This issue persists as of v2.12.0
