### ISSUE TITLE
[Bug Report] Checkbox not working in v-for loop

### ISSUE THREAD

**Issue by basvdijk** [ElemeFE/element#11659]
### Element UI version
2.4.1

### OS/Browsers version
Chrome OSX

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2380/](https://jsfiddle.net/mmx38qxw/2380/)

### Steps to reproduce
Check https://jsfiddle.net/mmx38qxw/2380/ test and test2 and Option A

### What is Expected?
The checkboxes variable should be ['test', 'test2', 'Option A']

### What is actually happening?
The checkboxes variable is [ "Option A", null ] It looks like it has something todo with the checkbox inside a v-for

**Comment by jikkai** [comment]
It's not a bug. You should bind `label` to it.
https://jsfiddle.net/mmx38qxw/2394/
