### ISSUE TITLE
[Feature Request] Add attribute `create-method` when `allow-create` is enabled

### ISSUE THREAD

**Issue by robinhuy** [ElemeFE/element#11658]
### Existing Component
Yes

### Component Name
Select

### Description
When `allow-create` is enabled, it should have a `create-method` attribute to custom create method. 
Ex: I want to call an API to create option on server.

**Comment by qwIvan** [comment]
+1

**Comment by flowbywind** [comment]
+1

**Comment by flowbywind** [comment]
有好的解决方案了没

**Comment by Lazac92** [comment]
same as #12468
