### ISSUE TITLE
[Bug Report] popover/button not showing

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#11654]
### Element UI version
2.4.1

### OS/Browsers version
macos chrome Version 67.0.3396.87 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/6yjhm9su/64/](https://jsfiddle.net/6yjhm9su/64/)

### Steps to reproduce
create a el-table and add a cell with popover and a button as shown in the link.
neither popover nor button will show on screen

### What is Expected?
to show a button and a popover

### What is actually happening?
button/popover not displayed/rendered on screen

**Comment by jikkai** [comment]
`slot="reference" `
https://jsfiddle.net/6yjhm9su/73/
