### ISSUE TITLE
[Feature Request] Add icon for the Tree Component

### ISSUE THREAD

**Issue by hnoivy** [ElemeFE/element#11662]
### Existing Component
是

### Component Name
Tree

### Description
请问树组件中能不能增加一个icon属性，其中填写icon的类型（类似于el-icon-info），就可以在对应的树节点中显示该图标，如果存在checkbox,则在checkbox后面显示对应的图标，如果不存在checkbox就显示在展开伸缩按钮后面

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can use `render-content` or scoped slot to implement it.
