### ISSUE TITLE
[Bug Report] DatePicker will not select the date set after default-value is set.

### ISSUE THREAD

**Issue by soso24086** [ElemeFE/element#11669]
### Element UI version
2.4.1

### OS/Browsers version
Windows 7 / chrome 67.0.3396.87

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2420/](https://jsfiddle.net/mmx38qxw/2420/)

### Steps to reproduce
点选日期选择器

### What is Expected?
开启日期选择器时，设定default-value的日期应该反蓝

### What is actually happening?
设定default-value后，开启日期选择器会正常显示在设定的年份与月份，但日期却没有反蓝

日期设定在2018-09-09
![image](https://user-images.githubusercontent.com/12797345/41590991-0e254eb2-73eb-11e8-849a-30a707003e15.png)

日期选择器没有将9月9号那个日期标注起来
![image](https://user-images.githubusercontent.com/12797345/41590954-f3c78896-73ea-11e8-8392-6554a3817621.png)

正常应该要像这样
![image](https://user-images.githubusercontent.com/12797345/41591087-5d25adb8-73eb-11e8-969a-0108d34bc45b.png)

**Comment by wacky6** [comment]
default-value 设计上就不会蓝色显示，它只控制默认显示的日期
蓝色显示表示今天。
