### ISSUE TITLE
[Feature Request] adds an attribute to enable the display line to be fully customizable, so that the layout of the expansion line is identical with the unexpanded line.

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#11666]
### Existing Component
是

### Component Name
el-table

### Description
加一个属性使展开行可以完全自定义，使展开行的布局和非展开行完全一致。
这样可以方便做数据对比，行与展开行直接比较。

**Comment by jikkai** [comment]
能详细描述一下具体需求场景吗

**Comment by LastHeaven** [comment]
比如有一个表格需要展示手机商品数据，需要展示小米，华为，OPPO等等品牌的手机数据，每一行都是展示每个品牌最新款的手机，展示的列有：型号，cpu，屏幕尺寸，分辨率，内存，价格等等信息。展开后可以展示该品牌所有旧款手机的型号，cpu，屏幕尺寸，分辨率，内存，价格等等信息。

**Comment by jikkai** [comment]
当前的展开行功能似乎是满足你所描述的这个需求的，还是说在样式上有什么特殊需求？

**Comment by LastHeaven** [comment]
问题是列宽发生改变的时候，展开项的列宽不会跟着改变

**Comment by jikkai** [comment]
有具体可复现该问题的 demo 吗

**Comment by LastHeaven** [comment]
https://jsfiddle.net/j7pLn9sw/6/
根本做不到展开项的列宽和表格列宽一样，并且列宽能跟着改变。
比如用鼠标通过拖动改变商品id的列宽，展开项商品id的列宽是做不到跟着变动的

**Comment by jikkai** [comment]
这个场景其实有点怪，展开行大多数的应用场景都是类似[官网例子](http://element.eleme.io/#/zh-CN/component/table#zhan-kai-xing)这样对行项目详情的自由补充。

实现以下场景可能会对用户造成误导：

![image](https://user-images.githubusercontent.com/14025786/41590001-85795da8-73e8-11e8-8f06-f16bc690f99e.png)

这个误导主要来源于列名可能会和展开列不对应，因为它只是行项目的补充而非对应列的项目。

因此相应来说该需求场景可能会比较少，短期内可能不会考虑实现。
