### ISSUE TITLE
[Bug Report] el-select does not extend to el-col size

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#11678]
### Element UI version
2.4.1

### OS/Browsers version
windows chrome 67.0.3396.87

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2445/](https://jsfiddle.net/mmx38qxw/2445/)

### Steps to reproduce
create a el-row with 2 el-cols with :span="12" each and put an el-select element on each col.

### What is Expected?
I expect the el-select to be as wide as the span column value (see the el-input in the same jsfiddle example link)

### What is actually happening?
the el-select is shorter than the el-col span which looks weird when combined in a form with other inputs. The el-input size is different than the el-select and they both should have same size.

**Comment by Leopoldthecoder** [comment]
This is because the default `display` of `<el-select>` is `inline-block`: https://jsfiddle.net/mmx38qxw/2828/
