### ISSUE TITLE
[Bug Report] ie10 SCRIPT65535: parameters are required.

### ISSUE THREAD

**Issue by rongjuan** [ElemeFE/element#11674]
### Element UI version
2.4.1

### OS/Browsers version
win10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
element-ui官网 ie10下缩放窗口会出现SCRIPT65535: 参数是必选项
在项目中使用ie10下也会出现一样的情况

### What is Expected?
希望在ie下不报错

### What is actually happening?
在ie下会报错，但是不影响使用

**Comment by jikkai** [comment]
能否提供详细报错信息或者截图

**Comment by rongjuan** [comment]
element-ui官网 360浏览器 模拟器ie10 窗口缩放

![1529486206 1](https://user-images.githubusercontent.com/19533035/41649355-f82b34be-74ad-11e8-90c2-44c94870d192.jpg)
