### ISSUE TITLE
[Bug Report] Tooltip text hints that enterable attribute does not work.

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#11684]
### Element UI version
2.4.1

### OS/Browsers version
window 64  / chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/    这个应该不用填写吧  官网的例子就不行  官网网址粘贴不过来](https://jsfiddle.net/mmx38qxw/    这个应该不用填写吧  官网的例子就不行  官网网址粘贴不过来)

### Steps to reproduce
Tooltip 文字提示  enterable属性不起作用   设置完之后还是可以将鼠标移入到气泡框中

### What is Expected?
Tooltip 文字提示  enterable属性起作用   设置完之后还是不可以将鼠标移入到气泡框中

### What is actually happening?
Tooltip 文字提示  enterable属性不起作用   设置完之后还是可以将鼠标移入到气泡框中

**Comment by jikkai** [comment]
请确保您的 [Vue 的语法](https://cn.vuejs.org/v2/api/#v-bind)是否正确
https://jsfiddle.net/mmx38qxw/2456/

**Comment by LemonAppleMo** [comment]
气泡提示框有一个200ms 的延迟  可以由开发者去除吗？
