### ISSUE TITLE
tree能否绑定onmousedown来实现鼠标右击事件，或者事件代理

### ISSUE THREAD

**Issue by chaohuaGH** [ElemeFE/element#1168]
### ElementUI version

1.0.1
### What is actually happening?
我的需求是右键点击tree的节点，然后生成一个小的菜单
我试着在tree上绑定@mousedown不起作用。
我又视图利用事件代理，在tree外加了一个div,来绑定@mousedown，可以相应事件，但是屏蔽了事件向下传播，tree无法操作。使用@mousedown.self，tree可以操作，div却不能接收到事件。。。。
请问下，我改怎么做，初学vue+elemnet，请赐教，急~~~~

**Comment by Leopoldthecoder** [comment]
由于 Tree 的每个节点不写在模板里，所以感觉你这样绑定似乎达不到效果。可以在恰当的时机获取节点的 DOM 元素，然后使用 `addEventListener` 来绑定事件。

另外，「试着在tree上绑定@mousedown不起作用」是因为需要 `.native` 修饰符，详见 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) 的第一问。

**Comment by liuzhibin123** [comment]
右键怎么获取到 当前node的数据信息？

**Comment by PLQin** [comment]
同问楼上!

**Comment by PLQin** [comment]
@chao-hua 
@liuzhibin123 
@hex-ci 
建议参考: 
[ElementUi] 需要实现 `tree`组件上右键弹出菜单并且 `获得 tree node的id值` - Starch的回答 - SegmentFault
https://segmentfault.com/q/1010000012940760/a-1020000012955488
