### ISSUE TITLE
[Feature Request] Is there a way to add slot for labels for?

### ISSUE THREAD

**Issue by liran319** [ElemeFE/element#11681]
### Existing Component
是

### Component Name
Table

### Description
I want to add an icon with tooltip to table head column, which can give visitors some tips or messages when hover.
But the column labels only receive string objects, so will you enable slot props for table column component, just like form items?

**Comment by jikkai** [comment]
You can use `render-header` attribute
https://jsfiddle.net/53rkaLcp/7/
