### ISSUE TITLE
[Feature Request] Whether there is a globally configured empty data API data

### ISSUE THREAD

**Issue by Zhang1051127659** [ElemeFE/element#11695]
### Existing Component
是

### Component Name
el-table

### Description
In the case of using many tables in the project, I need to configure the prompt information when the tables data is empty. In the API, only the interface that configures the current form is empty. I would like to ask if there is an empty message that can be empty by the global configuration data. Where is it?

**Comment by jikkai** [comment]
I think you can wrap your own table component with `el-table`
