### ISSUE TITLE
Can [Feature Request] Tabs Tags add render of custom operation?

### ISSUE THREAD

**Issue by iunfire** [ElemeFE/element#11699]
### Existing Component
是

### Component Name
el-tabs

### Description
在使用tabs时, 在标签右侧无法添加自定义操作, 希望能添加一个添加自定义操作的render

**Comment by jikkai** [comment]
可以自行通过 CSS 实现：https://jsfiddle.net/a4z1pjqg/1/

**Comment by advsets** [comment]
ok, thanks, That's what I've done so far

**Comment by duyhung85** [comment]
Hi,

I am searching for a solution to place custom actions/ elements next to/on the left/ on the right of tab label too. Something like this:
![screen shot 2018-10-15 at 9 58 26 am](https://user-images.githubusercontent.com/4004056/46927973-78641f00-d062-11e8-8fa1-109749c88f95.png)

Is there anyway I can accomplish it?

Thanks,
Hungnd
