### ISSUE TITLE
[Bug Report] table expend icon not show when I use @import scss source file

### ISSUE THREAD

**Issue by frustigor** [ElemeFE/element#11694]
### Element UI version
2.4.1

### OS/Browsers version
Chrome Version 67.0.3396.87

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/frustigor/26vcp3Lw/](https://jsfiddle.net/frustigor/26vcp3Lw/)

### Steps to reproduce
Use the same template and js code as you provided here https://jsfiddle.net/api/post/library/pure/ , change the scss code to import scss source file as http://element.eleme.io/#/zh-CN/component/custom-theme said. 
The table expend icon do not show and cannot expend the row.

### What is Expected?
Working with scss source file.

### What is actually happening?
Not working.

**Comment by ziyoung** [comment]
@frustigor create a project in [codesandbox](https://codesandbox.io/).

**Comment by ziyoung** [comment]
Add `$--font-path` in element-variables.scss. http://element.eleme.io/#/zh-CN/component/custom-theme#zai-xiang-mu-zhong-gai-bian-scss-bian-liang
