### ISSUE TITLE
[Bug Report] table component fixed column custom template appears multiple Popover

### ISSUE THREAD

**Issue by chenbinqun** [ElemeFE/element#11704]
### Element UI version
2.4.1

### OS/Browsers version
win10 / chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/chenbinqun/wpc1Lug5/16/](https://jsfiddle.net/chenbinqun/wpc1Lug5/16/)

### Steps to reproduce
1、table组件，表格列比较多会出现横向滚动条
2、固定列fixed="right"，添加操作按钮
3、在固定列操作按钮中使用popover组件
4、在上面jsfiddle例子中点击删除按钮看效果

### What is Expected?
只出现一个popover弹窗

### What is actually happening?
只出现两个popover弹窗

**Comment by Leopoldthecoder** [comment]
以目前的实现看可能不算是 bug，参考 #10588

**Comment by jikkai** [comment]
目前评估下来确实不好处理，推荐是从使用上避免此类问题。
后续考虑下更改固定列的实现，看看能不能优化一下，这个 issue 暂时先 close 了，有更好的建议欢迎提出 🙇

**Comment by johyin** [comment]
终于找了解决的方法
el-popover的v-model="scope.row.del"的值使用map赋值
`      this.tableData.map( m => {
           m.del = false;
           return m
      })`
就会只出现一个popover弹窗了
传送门https://jsfiddle.net/damojun/njdpb0s5/3/
