### ISSUE TITLE
[Bug Report] createElement creates el-input MaxLength attribute not effective.

### ISSUE THREAD

**Issue by rainbowzx** [ElemeFE/element#11707]
### Element UI version
2.4.0

### OS/Browsers version
macos10.13.3/chrome 66.0.3359.181

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2525/](https://jsfiddle.net/mmx38qxw/2525/)

### Steps to reproduce
props设置maxlength属性

### What is Expected?
maxlength属性 生效

### What is actually happening?
maxlength没有生效

**Comment by jikkai** [comment]
https://jsfiddle.net/mmx38qxw/2532/
```
attrs: {
  maxlength: 4
}
```
