### ISSUE TITLE
[Feature Request] about el-table rowspan and colSpan

### ISSUE THREAD

**Issue by Cage24** [ElemeFE/element#11700]
### Existing Component
是

### Component Name
el-table

### Description
I see in the official document el-table merged cell data is tile data, but the actual development of data returned by the background is a master-slave relationship, such as
[
    "order_id"：123,
   "goods"：[
       {
          "name"："clothes"
       }，
      {
          ”name“："Shoes"
      }
   ]
]
How is this data merged？

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
