### ISSUE TITLE
The display order of [Bug Report] table component is reversed after the two encapsulation.

### ISSUE THREAD

**Issue by liub1934** [ElemeFE/element#11708]
### Element UI version
2.4.1

### OS/Browsers version
win10/Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/xunmeng/mmx38qxw/2550/](https://jsfiddle.net/xunmeng/mmx38qxw/2550/)

### Steps to reproduce
直接Run运行就行了

### What is Expected?
日期那一列应该显示在前面的，还有包括姓名
![image](https://user-images.githubusercontent.com/29849550/41760102-63e2f468-7624-11e8-8347-f5de666a3889.png)

### What is actually happening?
日期跑到后面了，姓名也跑到后面了，顺讯都反了
![image](https://user-images.githubusercontent.com/29849550/41760120-75cbabd4-7624-11e8-80d1-d92d301758d1.png)

**Comment by jikkai** [comment]
你的 `my-column` 组件外层包了一个 div，`el-table` 的 default slot 不支持嵌套 `el-table-column` 以外的组件，可以考虑把 `my-column` 放回 `my-table` 中。

**Comment by liub1934** [comment]
@jikkai   完美解决多级表头嵌套，可以正常显示了，理论上可以无限级嵌套，贴上地址：https://jsfiddle.net/mmx38qxw/2765/

**Comment by qwIvan** [comment]
https://github.com/ElemeFE/element/issues/11868
el-table下，不可避免地要在el-table-column周围嵌套一层div。因为每个vue组件都只能有一个跟节点。

**Comment by jikkai** [comment]
@qwIvan 有两种方法可以帮助拆分 table 和 table-column 组件：
一个是可以考虑以 el-table-column 为根节点构建自定义 table-column 组件，另一个是用 jsx + 函数式组件绕过只能嵌套一层的限制

```javascript
{
  functional: true,
  render(h) {
    return [
      <el-table-column prop="date" label="日期" width="180" />,
      <el-table-column prop="name" label="姓名" width="180" />,
      <el-table-column prop="address" label="地址" />
    ]
  }
};
```

**Comment by qwIvan** [comment]
@jikkai 为什么这个问题，不能直接解决掉呢？
