### ISSUE TITLE
The secondary menu of [Bug Report] cascade selector still generates the next level when children is empty.

### ISSUE THREAD

**Issue by SliverYuki** [ElemeFE/element#11701]
### Element UI version
2.4.1

### OS/Browsers version
Windows 10 1803 17134.112 / Chrome 67.0.3396.87 (64bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2484/](https://jsfiddle.net/mmx38qxw/2484/)

### Steps to reproduce
点击选择器-示例1

### What is Expected?
选中示例1，并且不展开空的次级菜单

### What is actually happening?
选中示例1，展开了空的次级菜单

**Comment by jikkai** [comment]
深入考虑了一下这个问题，children 置空可以视作[动态加载次级选项](http://element.eleme.io/#/zh-CN/component/cascader#dong-tai-jia-zai-ci-ji-xuan-xiang)的一个中间状态，因为这个时候数据为明确的`Array`，且长度为 0。如果数据上明确没有次级选项的话，应该将 children 设置为`null`或者`undefined`。
