### ISSUE TITLE
[Bug Report] select with "remote"  is loosing dropdown arrow 

### ISSUE THREAD

**Issue by jerzyk** [ElemeFE/element#11705]
### Element UI version
2.4.1

### OS/Browsers version
Mac OS 10.13.5

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2510/](https://jsfiddle.net/mmx38qxw/2510/)

### Steps to reproduce
if there is a select dropdown with "remote" set - it looses arrow-down icon on the undrelying input, but place for the icon is still there 
so a) arrow should not be there - then an issue is that this place is occupied and therefore any label will be trimmed on the right size
b) down/up arrow should be there 

### What is Expected?
arrow should be there at least - there is a distinct functionality between select dropdown (even with remote data) and autocomplete - autocomplete does not need an arrow as it is not enforcing option selection (with single select)

### What is actually happening?
no icon!

**Comment by weisiwu** [comment]
@jerzyk 
im encounter the same question as you, but version of mine is 2.0.11
it seems element-ui generate a wrong class for el-select tag:
![image](https://user-images.githubusercontent.com/10015884/42071000-854f4342-7b8b-11e8-95fa-4f4d0191949d.png)
the correct seems like:
![image](https://user-images.githubusercontent.com/10015884/42071015-95d0fec2-7b8b-11e8-8f31-26be736a39bb.png)
you can bypass this problem by remove 'filterable' attribute in el-select tag. the detail you can reference here: [code](https://github.com/ElemeFE/element/blob/c913ce156b8590bdee9954e1a7cf70ec951b6c75/packages/select/src/select.vue#L177)
