### ISSUE TITLE
When [Bug Report] tabs is too many, the current screen can not be automatically positioned and scrolled to tab at active.

### ISSUE THREAD

**Issue by 1008611** [ElemeFE/element#11703]
### Element UI version
2.1.0

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/C__C/w4sx0mhk/](https://jsfiddle.net/C__C/w4sx0mhk/)

### Steps to reproduce
1.添加多个tab
2.通过activeName选中非当前屏幕的tab
3.不能自动定位并滚动到active的tab标签

### What is Expected?
通过Tab-pane 的name属性，可以自动定位并滚动到active的tab标签

### What is actually happening?
需要手动翻页，才能看到选中的标签。（我看源码中有scrollToActiveTab（）等方法）。

**Comment by jikkai** [comment]
该问题在新版本中已经修复

**Comment by 1008611** [comment]
@jikkai  你好。我在[jsfiddle](https://jsfiddle.net/C__C/w4sx0mhk/)中使用的就是最新的@2.4.1.你说的新版本是还没发布的么？

**Comment by jikkai** [comment]
@1008611 精简了一下你的 demo，在 2.4.1 下无法复现：https://jsfiddle.net/w4sx0mhk/6/

**Comment by 1008611** [comment]
@jikkai  en 谢谢，我发现是tab失去焦点后（点击翻页切换后），再次进行选择时候，就没效果了。
![如图](http://oims9p4rv.bkt.clouddn.com/5.gif)

**Comment by 1008611** [comment]
@jikkai  好的 谢谢 👍  （因为我们的业务逻辑：使用NavMenu的router模式，打开较多页签时，就存在定位不到activeTab的问题了。）
