### ISSUE TITLE
[Bug Report] form validation mailbox type:email @ supports Chinese input

### ISSUE THREAD

**Issue by OneAndOnly1111** [ElemeFE/element#11706]
### Element UI version
2.4.1

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/limeiling/8jd34onu/](https://jsfiddle.net/limeiling/8jd34onu/)

### Steps to reproduce
邮箱输入框输入:  测试@qq.com 
结果： 验证通过

### What is Expected?
邮箱的规则验证应该不支持输入中文

### What is actually happening?
支持输入中文

**Comment by OneAndOnly1111** [comment]
例如： 测试@qq.com
结果： 验证通过

**Comment by jikkai** [comment]
[async-validator](https://github.com/yiminghe/async-validator/blob/master/src/rule/type.js#L8) 的校验规则是这样的，这个场景下建议使用自定义验证
