### ISSUE TITLE
[Bug Report] <el-select-dropdown> error when use @vue/test-utils and jest

### ISSUE THREAD

**Issue by Senasiko** [ElemeFE/element#11715]
### Element UI version
2.4.1

### OS/Browsers version
win10 / chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://github.com/Senasiko/element-bug](https://github.com/Senasiko/element-bug)

### Steps to reproduce
`npm install`
`npm run test:unit` 出现异常
`npm run setve` 正常

### What is Expected?
`npm run test:unit` 正常通过

### What is actually happening?
`npm run test:unit` 出现异常

**Comment by ziyoung** [comment]
jest 使用了 [jsdom](https://github.com/jsdom/jsdom)，jsdom 中 DOM 元素的宽高是 0（如果你不手动设置的话）。dropdown 组件在渲染时，需要计算宽度或者高度，可能某个地方就出错了。可以[用 Karma 测试单文件组件](https://vue-test-utils.vuejs.org/zh/guides/testing-SFCs-with-karma.html)。
