### ISSUE TITLE
[Bug Report] messageBox memory leaks

### ISSUE THREAD

**Issue by hanz520** [ElemeFE/element#11714]
### Element UI version
2.4.1

### OS/Browsers version
win10/ Chrome

### Vue version
2.4.1

### Reproduction Link
[https://github.com/hanz520/messageBox-memory-leaks](https://github.com/hanz520/messageBox-memory-leaks)

### Steps to reproduce
step 1：open demo，Automatically load the home page

step 2：open devtools profiles, take a snapshot. ( now, we have 6 VueComponets )

step 3：click go page1 to switch router to page 1, take a snapshot again. ( now, we have 18 VueComponets )

step 4：click go home to switch router to home, take a snapshot again. ( now, we have 6 VueComponets, this is the result we want to see. )

step 5: click go page1 to switch router to page 1, and click click me to call MessageBox, take a snapshot again. ( now, we have 22 VueComponets )

step 6: click go page1 to switch router to page 1, take a snapshot again. ( now, we have 23 VueComponets, the componet of page 1 is not destroyed )

英语水平有限，所以用中文再做一次描述:

步骤一： 打开demo, 自动加载home页面

步骤二： 打开devtools profiles, 拍一张内存快照 （这个时候有6个 vue组件）

步骤三： 点击路由链接，跳转到页面一， 拍一张快照， （这个时候有18个 vue组件）

步骤四： 回到home页面，拍快照， （这个时候也只有 6 vue组件，属于正常情况）

步骤五： 再点路由链接，跳转到页面一，并且点击一下click me 调用一次messageBox， 拍快照。（这个时候有 22 个vue组件, 对比可以发现，之前页面一里面的 el-input 和 el-button 等组件并没有被销毁掉。）

另外还有一个现象，就是我先在页面一调用一次messageBox 的时候，然后再到页面二调用一次messageBox，完了，回到home 去抓快照，

这个时候的情况是：发现抓到的是页面二里面的vue组件被残留下来了，没有被销毁

所以我觉得是不是最后哪个路由页面里面调用了一次messageBox后，该路由里面所有的组件就会一直不被销毁，直到下一次 再调用messageBox，当前没被销毁的vue组件才会被销毁掉，但是又会重新产生一批新的vue组件去占用内存。

之前好像有人提过一次，this.$confirm 内存泄漏，但是官方给出的解释是，这是预期行为，messageBox创建一个单独的实力，知道window关闭才会被销毁，这我也觉得合理，但是由于messageBox导致了该页面的所有其他组件不能被销毁，这样是不是不合理了？一个页面的vue组件少说也有几百上千个吧！这个还是挺占内存的。

### What is Expected?
When we use messageBox，and use router to turn page， the vueComponents can be released。
当我在这个页面使用了messageBox的时候，通过路由跳转页面了，在另外一个页面，不应当在内存里面还保存着我上一个页面的组件，除非是我特意让它保留下来的。

### What is actually happening?
the vueComponents can not be released。

**Comment by ziyoung** [comment]
@hanz520 我这边无法重现。截屏录了个视频，https://drive.google.com/open?id=1440sry9ZYXsyn_wzaBSkstC63aFHwjc_

**Comment by hanz520** [comment]
@ziyoung dom 节点是被移除了没错，但是在内存里面，引用还是被占用到的，您稍等，我做个截图你看就明白了

**Comment by hanz520** [comment]
@ziyoung   你那边需要用profiles才能看到占用内存没被释放的组件，vue-devtools看不到没有被释放的组件。 [https://drive.google.com/file/d/1G4Mrcdb6WK6oT_fKbtdM1_dGlldBkqHY/view](查看视频)

**Comment by hanz520** [comment]
@ziyoung  你那边需要用profiles才能看到占用内存没被释放的组件，vue-devtools看不到没有被释放的组件。 [https://github.com/ElemeFE/element/issues/11714](https://github.com/ElemeFE/element/issues/11714)

**Comment by hanz520** [comment]
@ziyoung   用vue-devtools 没法看到没被释放的组件，需要用到 frofiles才能看的到。  [https://drive.google.com/file/d/1G4Mrcdb6WK6oT_fKbtdM1_dGlldBkqHY/view](https://drive.google.com/file/d/1G4Mrcdb6WK6oT_fKbtdM1_dGlldBkqHY/view)

**Comment by hanz520** [comment]
@ziyoung  我又特地截图了一下，请过目
![1](https://user-images.githubusercontent.com/24839877/41837726-ed2f52a2-7890-11e8-8d9c-a87bca34108d.jpg)
![2](https://user-images.githubusercontent.com/24839877/41837729-f0b0e3a0-7890-11e8-898a-728e3b8e7ab9.jpg)
![3](https://user-images.githubusercontent.com/24839877/41837733-f3aff2d0-7890-11e8-8e93-b4bbbf8311d9.jpg)

**Comment by hanz520** [comment]
才发现，好像有一个button组件是来自于messageBox弹框里面

**Comment by ziyoung** [comment]
@hanz520 路由切换后，组件是都销毁了。全局注册一个 mixin，给每个组件加一个 beforeDestroy 钩子。
```js
Vue.mixin({
  beforeDestroy() {
    console.log(`%c component ${this.name || this.$options.name} will be destoryed`, 'color: red;')
  }
})
```
最终效果如下：https://codesandbox.io/s/l99vqoor6l

**Comment by hanz520** [comment]
@ziyoung 那内存快照里面看到的那些VueComponent怎么解释呢？求解答。还有，明显，不调用一次messageBox组件比调用一次之后，回到home页面，所占用的内存会多大约1M，因为当前page1 组件比较少，所以只多了1M，我目前项目中，两者相差大概有20M之多。

**Comment by hanz520** [comment]
@ziyoung 那个到底算不算一个vue组件我也不太理解，但是说是一个js对象，肯定没错吧，很明显这些个js对象没有被内存释放呀

**Comment by hanz520** [comment]
@ziyoung 
![_20180627183122](https://user-images.githubusercontent.com/24839877/41968905-5d5e3e46-7a38-11e8-99c7-fee760f2fcbb.png)

**Comment by cn1001wang** [comment]
element plus现在还是有内存泄漏这个问题

**Comment by wangzhanpeng** [comment]
组件destroy了，但是组件this实例还在内存中，有引用，没有释放，内存会不断增加
