### ISSUE TITLE
[Feature Request] 2.4.1's tab control before-leave method adds a parameter to the current item tab.

### ISSUE THREAD

**Issue by yangchaojiang** [ElemeFE/element#11712]
### Existing Component
是

### Component Name
tab

### Description
2.4.1的tab的控制 before-leave 方法  添加一个参数，当前的item的tab

**Comment by jikkai** [comment]
是指目标 tab 的 name 吗？

**Comment by yangchaojiang** [comment]
是的

**Comment by yangchaojiang** [comment]
我是实现方法后, 添加业务逻辑，发现没有参数 ,不知道要切换到那个item?。一下就懵逼了:sob::sob::sob:
