### ISSUE TITLE
[Bug Report] Customized column filter with render-header and sortable

### ISSUE THREAD

**Issue by VinceBassman** [ElemeFE/element#11721]
### Element UI version
2.4.1

### OS/Browsers version
Google Chrome Version 67.0.3396.87

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/49z1rjbg/](https://jsfiddle.net/49z1rjbg/)

### Steps to reproduce
1. Click into the input field under Name (first column) to enter a free text

### What is Expected?
Just a text should be visible in the input field. No sorting action should be triggered focusing on the input field. The sort function should only be triggered clicking on the carets (like using the filters column attribute). By the way it would be great to be able to place the carets beside the label and not below the input field.

### What is actually happening?
Clicking the input field to enter a value triggers the sort function

**Comment by jikkai** [comment]
In this case, you need to stop event propagation by yourself.
https://jsfiddle.net/49z1rjbg/4/

**Comment by VinceBassman** [comment]
Thanks, that's it!
Is there a way to place the carets after the label using sortable? Or are they placed always in a span at the end?
