### ISSUE TITLE
[Bug Report] DateTimePicker date time picker how to get the local time (I now get the 0 zone).

### ISSUE THREAD

**Issue by WiFiUncle** [ElemeFE/element#11729]
### Element UI version
2.4.1

### OS/Browsers version
win

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
DateTimePicker 日期时间选择器 如何获取本地时间(我现在拿到的好像是0区的)
没找到相关参数配置2018-06-19T16:00:00.000Z  

### What is Expected?
能获取本地时间

### What is actually happening?
获取的是0区时间

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
