### ISSUE TITLE
The [Feature Request] form form component disabled property should not override the sub component disabled attribute.

### ISSUE THREAD

**Issue by yezongyang** [ElemeFE/element#11725]
### Existing Component
是

### Component Name
el-form

### Description
用form表单创建编辑页面，页面里面会有一些查看按钮。 没有权限的时候不可编辑，但是可以点击查看按钮查看信息

**Comment by jikkai** [comment]
可以通过控制数据源和基本的 vue 指令实现

**Comment by xuwencheng** [comment]
+1  个人觉得子组件属性值的优先级应该高于从父组件透传过来的属性， 就和rules一样，el-form 和el-form-item 都可以设置，当规则相同时，后者优先级更高
