### ISSUE TITLE
[Feature Request] Adding before-change events to select components

### ISSUE THREAD

**Issue by axetroy** [ElemeFE/element#11723]
### Existing Component
是

### Component Name
select

### Description
有个需求，在 ``el-select`` 组件，在用户选择对于的选项之前，会给它一个提示，是否要确认选择这个选项。

如果返回true，则变更绑定的值，如果返回false，则保持不变

**Comment by jikkai** [comment]
感谢您的建议。
首先我认为这是一个非常奇怪的交互，有点类似 #11402 中针对 switch 组件的提议。
我的观点也还是和那个 issue 下回复的一致：非导航组件应用这种交互很有可能因为阻塞导致用户体验大打折扣。
所以在有更好的方案之前，我们可能短期内不会考虑实现此功能。
