### ISSUE TITLE
[Bug Report] el-cascader unresponsive when inside an el-card component

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#11720]
### Element UI version
2.3.0

### OS/Browsers version
Linux / Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2743/](https://jsfiddle.net/mmx38qxw/2743/)

### Steps to reproduce
Put a el-cascader inside an el-card. It won't open.

### What is Expected?
That the cascader should work.

### What is actually happening?
Cascader doesn't respond. Appears disabled.

**Comment by ziyoung** [comment]
@adavie1 you need wrap `el-col`  in `el-row`.  https://jsfiddle.net/mmx38qxw/2748/

**Comment by adavie1** [comment]
Thanks, that fixed it. However, I often use el-col without a el-row wrapper and it works fine in most cases. Would you recommend refactoring all that code?
