### ISSUE TITLE
Does [Feature Request] provide a default API for loading dialog content DOM?

### ISSUE THREAD

**Issue by SkyLin0909** [ElemeFE/element#11732]
### Existing Component
是

### Component Name
el-dialog

### Description
当我在<el-dialog><div ref="form"><div><el-dialog>, 写入一个ref属性，首次打开dialog, this.$refs.form并没有dom节点，而title和footer已经加载完成，确实这样默认不加载能提升一点性能，能否给开发者一个api,主动选择了？

**Comment by jikkai** [comment]
试试 `this.$nextTick`
