### ISSUE TITLE
[Bug Report] Simplify v-model binding with <el-select> in custom components

### ISSUE THREAD

**Issue by Hippoom** [ElemeFE/element#11734]
### Element UI version
2.3.8

### OS/Browsers version
Mac, Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
I'm using [el-select](http://element.eleme.io/#/en-US/component/select) to build a select component. Something like this:

    <template>
        //omitted code
        <el-select v-model="filterForm.client"
                        filterable
                        remote
                        placeholder="Please enter a keyword"
                        :remote-method="filterClients"
                        :loading="loading">
                    <el-option
                            v-for="item in clientCandidates"
                            :key="item._id"
                            :label="item.name"
                            :value="item._id">
                    </el-option>
                </el-select>
    </template>
    <scripts>
        export default {
            data() {
               filterForm: {
                    client: ''
               },
               clientCandidates: [],
               loading: false
            },
            methods: {
                filterClients(query) {
                    if (query !== '') {
                        this.loading = true;
                        setTimeout(() => {
                            this.loading = false;
                            this.clientCandidates = [{_id: '1', name: 'foo'}, {_id: '2', name: 'bar'}];
                        }, 200);
                    } else {
                        this.clientCandidates = [];
                    }
                }
            }
        }
    </scripts>

So far so good, but since the component will appear in different pages, so I want to extract a custom component to avoid duplication.

According to the [guideline](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components), 

    v-model="fullName"

is equivalent to 

    v-bind:value="fullName"
    v-on:input="$emit('input', $event)"

So I extracted the select component like this:

    <template>
    <el-select
            v-bind:value="clientId"
            v-on:input="$emit('input', $event)"
            placeholder="Filter by short name"
            filterable="true"
            remote="true"
            :remote-method="filter"
            :loading="loading">
        <el-option
                v-for="item in clients"
                :key="item._id"
                :label="item.name"
                :value="item._id">
        </el-option>
    </el-select>
    </template>
    <scripts>
    export default {
        props: {
            clientId: {
                type: String,
                required: true
            }
        },
        data() {
            return {
                clients: [],
                loading: false,
            }
        },
        methods: {
            filter(query) {
                if (query !== '') {
                    this.loading = true;
                    setTimeout(() => {
                        this.loading = false;
                        this.clients = [{_id: '1', name: 'foo'}, {_id: '2', name: 'bar'}];
                    }, 200);
                } else {
                    this.clients = [];
                }
            }
        }
    }
    </scripts>

And the parent component looks like this:

    <select-client v-model="filterForm.clientId"></select-client>

The select drop down works fine, but unfortunately, the select does not reveal the option I selected, it remains empty after I choose an option. I suspect that maybe I should switch the `v-on:input` to 'v-on:change', but it does not work either.

**Sample**

I created a simple example, you can clone it [here](https://github.com/Hippoom/element-ui-questions/tree/el-select-as-component), please checkout the `el-select-as-component` branch. Run

    npm install
    npm run dev

You will see a simple page with 3 kinds of select:  
The left one is a custom component written in raw select, it works fine.  
The middle one is a custom component written in `el-select`, the dropdown remains empty but you can see the `filterForm.elClientId` in the console once you click `Filter` button. This is why I raise this question.  
The right one is a plain `el-select`, it works fine.

### What is Expected?
Only `emit('input', e)` is required and keep `clientId` a props. Just like <el-input/>

### What is actually happening?
**Workaround**
I have to switch `clientId` from `props` to `data`, and update the value explicitly after emitting the event. 
     
     <el-select
        :value="clientId"
        @input="dispatch"    
     //...omitted code
     data() {
      return {
        clientId: '',

     //...omitted code
     dispatch(e) {
        this.$emit('input', e);
        this.clientId = e;
      }

You can find the details [here](https://github.com/Hippoom/element-ui-questions/pull/1)

**Comment by Leopoldthecoder** [comment]
https://github.com/Hippoom/element-ui-questions/pull/2 Please read the Vue docs more carefully.
