### ISSUE TITLE
The validation properties of the [Bug Report] form form are invalid,

### ISSUE THREAD

**Issue by freeMan-qian** [ElemeFE/element#11747]
### Element UI version
2.4.1

### OS/Browsers version
谷歌浏览器 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/jo0r1udk/1/](https://jsfiddle.net/jo0r1udk/1/)

### Steps to reproduce
以前使用 v-bind:rules="[
      { type: 'email', message: '请输入正确的邮箱', trigger: 'blur,change' }]"    type=email是可以验证邮箱的，现在发现以前做过的功能都失效了，请帮忙查看

### What is Expected?
以前使用 v-bind:rules="[
      { type: 'email', message: '请输入正确的邮箱', trigger: 'blur,change' }]"    type=email是可以验证邮箱的，现在发现以前做过的功能都失效了，请帮忙查看

### What is actually happening?
以前使用 v-bind:rules="[
      { type: 'email', message: '请输入正确的邮箱', trigger: 'blur,change' }]"    type=email是可以验证邮箱的，现在发现以前做过的功能都失效了，请帮忙查看

**Comment by ziyoung** [comment]
@freeMan-qian 把 v-model 上的修饰符去掉，https://jsfiddle.net/zhiyang/jo0r1udk/2/

**Comment by freeMan-qian** [comment]
@ziyoung  这只是官网的例子，我刚刚改忘了，我实际应用中，并没有加这个修饰符，我实际应用的写起来比较复杂，之前是有用的，现在没用用了，我的写法如下：
 <el-form-item v-bind:label="item.DisplayName" v-else-if="!item.IsRequired && item.FieldName=='Email'" v-bind:prop="'Fields.'+index+'.DefaultValue'" v-bind:rules="[
      { type: 'email', message: '请输入正确的邮箱', trigger: 'blur,change' }]">
                                        <el-input v-model.email="item.DefaultValue" ></el-input>
                                    </el-form-item>

**Comment by freeMan-qian** [comment]
有时间再把我的贴出来，现在有点忙，反正这个应该是更新出了问题
