### ISSUE TITLE
Two date controls bug in a component of [Bug Report]

### ISSUE THREAD

**Issue by wubrchina** [ElemeFE/element#11740]
### Element UI version
2.4.1

### OS/Browsers version
win7 / chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
同一个组件中两个日期控件，每个日期控件触发change事件都会被执行两次（console了两条出来，change带上参数后发现是另一个日期控件的change也被一起触发了）。PS：不要说用日期范围选择控件，客户指定要两个日期控件。

### What is Expected?
当独执行各自的事件

### What is actually happening?
当独执行各自的事件

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
