### ISSUE TITLE
dialog的show-close参数无效

### ISSUE THREAD

**Issue by annieh12** [ElemeFE/element#1174]
### ElementUI version

1.0.1

### OS/Browers version

Windows7 / Chrome 54.0.2840.71

### Vue version

2.0.3

### Steps to reproduce
template里
```
  <el-dialog :close-on-click-modal="closeBool" :close-on-press-escape="closeBool" :show-close="closeBool" v-model="dialogVisible" size="tiny">
  .......
  </el-dialog>
```
script里
```
export default {
  data () {
    return {
      closeBool: false
    }
  }
}
```

### What is Expected?
我是想让这个dialog无论是点击modal还是ESC都不能关闭，更不能显示关闭按钮。于是我添加了这些参数。

### What is actually happening?
可是，参数close-on-click-modal、close-on-press-escape都生效，只有show-close没有生效

**Comment by Leopoldthecoder** [comment]
试了一下没问题：http://jsfiddle.net/leopoldthecuber/aakrd742/
麻烦提供一个可以复现问题的 demo

**Comment by annieh12** [comment]
噢 不好意思，ElementUI 版本并没有升级到1.0.1，，，升级后就没问题了

**Comment by Leopoldthecoder** [comment]
是的，`show-close` 是 1.0.1 版本加入的。

**Comment by yuanshengchao** [comment]
您好，这个show-close没有显示出来关闭的图标呢，http://jsfiddle.net/leopoldthecuber/aakrd742/。这个例子也没有显示。请问是什么原因。版本1.0.1和版本1.0.2都不正常，但是1.0.0却正常

**Comment by Leopoldthecoder** [comment]
@yuanshengchao 因为 `show-close` 的值是 `false` 啊，所以不显示关闭图标。
