### ISSUE TITLE
[Bug Report] Upload input keeps showing after reaching limit

### ISSUE THREAD

**Issue by LuisMendoza2295** [ElemeFE/element#11745]
### Element UI version
2.4.1

### OS/Browsers version
Google Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2839/](https://jsfiddle.net/mmx38qxw/2839/)

### Steps to reproduce
Set limit of files

### What is Expected?
file-input hiding

### What is actually happening?
file-input showing

**Comment by my9074** [comment]
请问 现在有解决方案么？ hack 的也可以 @ziyoung

**Comment by ziyoung** [comment]
@my9074 在 upload 组件上添加一个 class，通过 CSS 来控制上传卡片的显示与隐藏。https://jsfiddle.net/zhiyang/mmx38qxw/4293/

**Comment by jikkai** [comment]
Duplicate of #8689
