### ISSUE TITLE
[Feature Request] paging component can add jumper-text, similar to prev-text and next-text, replace the forward page with any character.

### ISSUE THREAD

**Issue by bigzs** [ElemeFE/element#11748]
### Existing Component
是

### Component Name
Pagination 分页

### Description
分页组件能否添加jumper-text，类似prev-text和next-text，将'前进页'替换成任意字符，如传一个对象{jumperTextBefore:'跳转至',jumperInputAfter:'页'}

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by jikkai** [comment]
可以通过自定义 i18n 实现

**Comment by bigzs** [comment]
但是我只想一个页面这样改，其他页面不改，自定义i18n可以局部设置吗。
