### ISSUE TITLE
关于el-menu中@close @open 事件stopPropagation问题

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1175]
### ElementUI version
1.01

### OS/Browers version
 macOS/Chrome 53

### Vue version
2.0.7
### Reproduction Link

https://jsfiddle.net/yelingfeng/5u16k232/1/

### Steps to reproduce

menu @open @close事件 加不了stop  会报错
![image](https://cloud.githubusercontent.com/assets/1932350/20415746/508603ac-ad75-11e6-9f71-4fe76cd3ebf0.png)

我想阻止冒泡到上层div 但是现在貌似回掉里 没有$event

**Comment by Kingwl** [comment]
https://vuejs.org/v2/api/#v-on ：
> When listening to native DOM events, the method receives the native event as the only argument.

**Comment by Leopoldthecoder** [comment]
`open` 和 `close` 是自定义组件 `$emit` 出来的事件，不会冒泡到上层，不需要 `stopPropagation`

**Comment by yelingfeng** [comment]
但是你内部现在绑定了click  如果我el-menu上层组件绑定了click 它就会触发冒泡啊 这个问题在解决？

**Comment by Leopoldthecoder** [comment]
`el-menu` 上层组件绑定 `click` 事件时使用 `self` 修饰符。

**Comment by yelingfeng** [comment]
我上层是jsx on-click的 。。。

**Comment by Leopoldthecoder** [comment]
那在事件回调里判断一下 `event.target` 是不是你想要的不就好了。

**Comment by yelingfeng** [comment]
好吧 谢大神
