### ISSUE TITLE
[Feature Request] Progress supporting customize text format 

### ISSUE THREAD

**Issue by imageslr** [ElemeFE/element#11769]
### Existing Component
是

### Component Name
Progress

### Description
当前进度条的 text 只支持显示百分比形式：75%，希望能够提供一个 `format` 属性，允许自定义文字格式，如：  
`<progress percent="75" format="$percent 折"></progress>`   
显示 “75折"。

`format` 属性还可以是回调函数的形式，其参数为当前百分比。

I hope I can customize the text format of Progress component, instead of only unique format "75%". For instance, the component provides `format` attribute and it can be String or Function. If it is a function, the argument will be current percent.

`<progress percent="70" format="$percent 折"></progress>`  
and the text of the component will be `75折`。

**Comment by upupzealot** [comment]
I would vote this request up!

**Comment by benmo1602** [comment]
动态 更新 format 会导致 

You may have an infinite update loop in a component render function.

**Comment by konglingwen94** [comment]
添加`format`属性或者`slot`都可以试验一下，在项目场景中我也遇到了这个需求
