### ISSUE TITLE
[Feature Request] form validate multiple form-item prop in one validator callback validator

### ISSUE THREAD

**Issue by de1ck** [ElemeFE/element#11768]
### Existing Component
yes
### Component Name
form form-item

### Description
multiple form-item validate in one validator callback functions.In some cases, we need more than one prop to compare together an immediately respond to the tree results

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/41958331-4bbfa5d8-7a1c-11e8-9cc3-ca57bc5c41b5.png)

You can access other field values like this.

**Comment by de1ck** [comment]
in some case , props Between each other validate @Leopoldthecoder

**Comment by tylerdong** [comment]
@Leopoldthecoder 我也是这么写的，但是this绑定的对象还是validator
![image](https://user-images.githubusercontent.com/20137895/48892023-f7c1eb00-ee77-11e8-8503-b50c8cdeb317.png)
