### ISSUE TITLE
[Bug Report] Popover content should re-render upon inner width/height changes.

### ISSUE THREAD

**Issue by ultraN** [ElemeFE/element#11766]
### Element UI version
2.4.2

### OS/Browsers version
Mac

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/ultraN/xa9L5o1f/1/](https://jsfiddle.net/ultraN/xa9L5o1f/1/)

### Steps to reproduce
Click the button, and popover shows. 
Wait for 1 second and more text content will be appended. (Simulate ajax loading using simple timeout function.)

### What is Expected?
The popover content should always be shown in full (as much as possible, if window height/width allows) even when the inner content size changes.

### What is actually happening?
The appended content is outside of the window, thus user can't see the content unless they reopen the popover.

**Comment by Leopoldthecoder** [comment]
You can manually update the popover: https://jsfiddle.net/xa9L5o1f/6/

**Comment by ultraN** [comment]
Thank you. Didn't know this API before.

**Comment by ziyoung** [comment]
@ultraN `Popover` is also built with `Vue-popper`. You can call `updatePopper`method of `Vue-popper` to recalculate the position of Popover. https://jsfiddle.net/zhiyang/xa9L5o1f/9/

**Comment by Leopoldthecoder** [comment]
Yes, `updatePopper` is not listed on the docs because we do not expect users to call it on their end. Though in this specific case, it comes in handy.
