### ISSUE TITLE
[Bug Report] Nested properties Validation

### ISSUE THREAD

**Issue by osman-mohamad** [ElemeFE/element#11767]
### Element UI version
2.3.9

### OS/Browsers version
electronJS

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/agk23yz8/](https://jsfiddle.net/agk23yz8/)

### Steps to reproduce
- write simple form
- add array of items (each item have id, quantity)
- add validation rules (required, number, ...)

### What is Expected?
I need to validate array of objects properties . but I can't . in async-validator there is section named deep-rules . I want to use this feature to make it work but it did not

see 
https://github.com/yiminghe/async-validator#deep-rules

### What is actually happening?
the form inputs is not validated

**Comment by ziyoung** [comment]
@osman-mohamad `rule` and `data` are needed before validating. The FormItem attribute `prop` is a key of the model. When `prop` is **id** or **quantity**, FormItem can't get data and rule from Form. So some inputs are not validated. I think you can write a [customized input component](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components) and [customize own validation rules](http://element.eleme.io/#/en-US/component/form#custom-validation-rules) for this component.

**Comment by ziyoung** [comment]
@osman-mohamad I write a demo for you. https://codesandbox.io/s/24p86xxvnn
