### ISSUE TITLE
1.0.1版本，在el-tooltip里面添加多个标签时，会报如下错,在1.0.0不会报错

### ISSUE THREAD

**Issue by perfectyang** [ElemeFE/element#1176]
这是1.0.1版本跑出来的结果： 
![image](https://cloud.githubusercontent.com/assets/8724828/20417896/b01e426c-ad83-11e6-98e5-b0692a1d2122.png)
![image](https://cloud.githubusercontent.com/assets/8724828/20417899/b2c1554a-ad83-11e6-8864-228b18c5338c.png)
－－－－－－－－－－
这是1.0.0跑出来的结果
![image](https://cloud.githubusercontent.com/assets/8724828/20417928/f7fb4e36-ad83-11e6-8dab-8fafdca19441.png)

**Comment by QingWei-Li** [comment]
请升级 vue-loader 到最新版

**Comment by perfectyang** [comment]
"vue-loader": "^9.9.5",
"vue": "^2.0.5",
  "element-ui": "^1.0.1",
![image](https://cloud.githubusercontent.com/assets/8724828/20418194/5cb5b4d6-ad86-11e6-9870-85f97f4195d6.png)

**Comment by perfectyang** [comment]
还是报这个错

**Comment by perfectyang** [comment]
![image](https://cloud.githubusercontent.com/assets/8724828/20418237/c9bfd1f6-ad86-11e6-8fb7-7a01fbf86c75.png)
感觉是在表格cell渲染出了问题

**Comment by QingWei-Li** [comment]
看起来是漏掉了静态数据渲染的问题

https://github.com/ElemeFE/element/pull/1161/files#diff-f43e7f4b2490f361bf951c67aefd2d8aR225

这里已经有修复了，今天会发 1.0.2

**Comment by perfectyang** [comment]
能不能表格的label变量，支持一下html的定义啊

**Comment by QingWei-Li** [comment]
表头支持自定义渲染规则 

http://element.eleme.io/#/zh-CN/component/table#table-column-attributes `render-header`

**Comment by perfectyang** [comment]
![image](https://cloud.githubusercontent.com/assets/8724828/20420627/fdd42cea-ad99-11e6-864f-36314df15fb6.png)
![image](https://cloud.githubusercontent.com/assets/8724828/20420652/1a352d1c-ad9a-11e6-96c2-6b4709890e9d.png)
只能是字，不能解析html的内容

**Comment by perfectyang** [comment]
应该把自定义的东西，当作html插入进去解析

**Comment by Leopoldthecoder** [comment]
那是因为你 return 的是个字符串。应该这样：
```javascript
return <b>退货匹号</b>
```

**Comment by perfectyang** [comment]
这样子，vue-loader不解析啊，是jsx的写法不支持啊
![image](https://cloud.githubusercontent.com/assets/8724828/20420830/1c6294a2-ad9b-11e6-8171-d18d7fa06da0.png)

**Comment by perfectyang** [comment]
有啥好办法么

**Comment by Leopoldthecoder** [comment]
有安装 `babel-plugin-transform-vue-jsx` 吗？参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) 第三问。

**Comment by perfectyang** [comment]
就是这个了，感谢大神指点

**Comment by QingWei-Li** [comment]
fixed in 1.0.2

**Comment by jasonlam0619** [comment]
@perfectyang 求问！`render-header` 如何使用，才能在表格头部渲染 HTML 内容？屡试无效。能否提供代码片段？
