### ISSUE TITLE
[Bug Report] at <el-cascader> filterable </el-cascader> doesn't work @active-item-change

### ISSUE THREAD

**Issue by bbogda** [ElemeFE/element#11760]
### Element UI version
2.3.2 (and 2.4.2)

### OS/Browsers version
Chrome 67.0

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/Bear4/zn5tves7/](https://jsfiddle.net/Bear4/zn5tves7/)

### Steps to reproduce
Open console and use filtering (by keyboard) item at  <el-cascader> (console.log without message)
And when select (by mouse) item at <el-cascader> method handleItemChange() is active. (console.log has message)

### What is Expected?
Is there any way to get filtering item options from <el-cascader> ?
Need this options to render chart.

### What is actually happening?
When filtering (by keyboard) item at <el-cascader> there is no active method: 
@active-item-change="handleItemChange" (code console.log without message)
so I can't get which options are set at <el-cascader> 

Oposite when select (by mouse) item at <el-cascader> method handleItemChange() is active.
And when changed second time only last children options method handleItemChange() doesn't run...

**Comment by ziyoung** [comment]
@bbogda according to the doc, `active-item-change` event triggers when active option changes. If `filterable` is true and you type some text, there's no action option.

**Comment by bbogda** [comment]
Thanks for info. So after searching I tried that:
```
<el-cascader
            placeholder="select item..."
            :options = "$store.state.rok.mocRok"
            @change="handleItemChange"
            filterable>

<script>
export default {
data() {
    return {
     daneGauss: []
},
  methods: {
    handleItemChange(val) {
      console.log('active itemV:', val)
      this.daneGauss = val
    }
}
</script>
```
It works fine with filerable and with change only last children.
At **daneGauss[]** have selected options.
