### ISSUE TITLE
[Feature Request] Upload component can on click download this file .

### ISSUE THREAD

**Issue by aabc6419tw** [ElemeFE/element#11772]
### Existing Component
Yes

### Component Name
Upload

### Description
希望能夠增加Upload 在點擊 file-list 時可下載該檔案
（預設file-list =>上传的文件列表, 例如: [{name: 'food.jpg', url: 'https://xxx.cdn.com/xxx.jpg'}] ）
file-list 已有url 所以建議可以增加此功能 ：）

**Comment by jikkai** [comment]
可以在 `on-preview` 中处理下载任务

**Comment by aabc6419tw** [comment]
非常感謝！！！！
