### ISSUE TITLE
[Bug Report] upload component: photo wall: upload interface 503

### ISSUE THREAD

**Issue by athousandsplendidsuns** [ElemeFE/element#11770]
### Element UI version
0.1.0

### OS/Browsers version
Chrome 66.0.3359.181（正式版本） （64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
upload组件->照片墙->上传一张145kb的图片，图片上传成功后消失，接口503

### What is Expected?
长传成功，此图片不消失，接口不报错

### What is actually happening?
上传成功，图片消失，接口503

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly. Perhaps it is an interface issue, not Element bug.
