### ISSUE TITLE
[Bug Report] [ElTable] changing highlight-current-row or nullifying current-row-key doesn't change the current row and so highlighted row stay highlighted 

### ISSUE THREAD

**Issue by amgadserry** [ElemeFE/element#11776]
### Element UI version
2.3.4

### OS/Browsers version
Ubuntu 16.10/ Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/wz3trjqy/](https://jsfiddle.net/wz3trjqy/)

### Steps to reproduce
1- click on any row on table
2- click on the button 

### What is Expected?
The highlighted row should be unhighlighted

### What is actually happening?
The highlighted row stay highlighted

**Comment by atilkan** [comment]
+1
