### ISSUE TITLE
[Bug Report] tree component setCurrentNode Bug

### ISSUE THREAD

**Issue by luohuanyu** [ElemeFE/element#11775]
### Element UI version
2.4.2

### OS/Browsers version
win10 chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN ( 没有这个地址）](https://elementui.github.io/issue-generator/#/zh-CN ( 没有这个地址）)

### Steps to reproduce
                  var tempNode=tree.getNode(data);
                   debugger;
                   tree.setCurrentNode(tempNode);

### What is Expected?
选中 数据是 data 的 节点

### What is actually happening?
没有选中 数据是 data 的 节点 

 TreeStore.prototype.setUserCurrentNode = function setUserCurrentNode(node) {
    var key = node[this.key];  // 错误代码
    var currNode = this.nodesMap[key];
    this.setCurrentNode(currNode);
  };
 我觉得应该 使用 node.data[this.key];

**Comment by ziyoung** [comment]
@luohuanyu 不太明白你的意思，如果有 bug，请提供一个可重现问题的例子。

**Comment by Singein** [comment]
我遇到了`setCurrentNode` 同样的问题。
官方文档的描述中，该方法传入的参数是`node`
![图片](https://user-images.githubusercontent.com/18239246/59020755-36038280-887d-11e9-8506-ca05b2d66ae4.png)
但是按照文档来的话，会出现如下错误：
![图片](https://user-images.githubusercontent.com/18239246/59020850-5f241300-887d-11e9-8bbf-d16216d331be.png)

但是当我将参数改为 `node-key` 时，便没有错误了，一切按照预期的正常运行。

所以这是文档错了，还是实现方式 错了？
