### ISSUE TITLE
[Bug Report] tree componet's highlight-current in attributes is always in an active state, whether the value is true or false 

### ISSUE THREAD

**Issue by Bonjourjw** [ElemeFE/element#11787]
### Element UI version
2.4.2

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/Bonjourjw/5jvk9f0a/9/](https://jsfiddle.net/Bonjourjw/5jvk9f0a/9/)

### Steps to reproduce
1. click node and current node isn't active.
2.set highlight-current as true,yes it is actived in highlight.
3.set highlight-current as false,it is actived in highlight too.

### What is Expected?
it should not to be active when the highlight-current set as false.

### What is actually happening?
it's active in highlight when the highlight-current set as false.

**Comment by Leopoldthecoder** [comment]
`:highlight-current="false"`, not `highlight-current="false"`.
