### ISSUE TITLE
The [Bug Report] table component uses prop binding fields, using V-IF to judge that rendering will appear: l.$scopedSlots.default is not a function

### ISSUE THREAD

**Issue by LucienSK** [ElemeFE/element#11784]
### Element UI version
2.0.8

### OS/Browsers version
windows / Chrome

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/lucien603/7tLedhwm/2/](https://jsfiddle.net/lucien603/7tLedhwm/2/)

### Steps to reproduce
1. 点击最右边的按钮
2. 点击中间的按钮

注：不使用prop，改使用template slot-scope则不会出现这样的错误

### What is Expected?
切换视图 table 的字段应该正常的绑定并渲染

### What is actually happening?
视图无法渲染

**Comment by Leopoldthecoder** [comment]
You need to `key` the Tables: https://jsfiddle.net/7tLedhwm/5/

**Comment by LucienSK** [comment]
@Leopoldthecoder Why do you need to add a key? There is no such skill on the official web document

**Comment by ziyoung** [comment]
issue #11534 也是类似的问题。

**Comment by Leopoldthecoder** [comment]
@LucienSK https://vuejs.org/v2/api/#key

**Comment by LucienSK** [comment]
@Leopoldthecoder thank you！！！I got it

**Comment by shiny** [comment]
遇到了同样的问题
