### ISSUE TITLE
Can [Bug Report] message components be automatically destroyed in component switching (component destruction)?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#11789]
### Element UI version
2.3.9

### OS/Browsers version
windows10/chrome 67

### Vue version
2.5.2

### Reproduction Link
[https://codesandbox.io/s/n91j80lqn4](https://codesandbox.io/s/n91j80lqn4)

### Steps to reproduce
在lis页面(主页面)获取完列表后，弹出message信息框，点击跳转到详情页，在详情页面，message信息框还是存在。

### What is Expected?
在lis页面(主页面)获取完列表后，弹出message信息框，点击跳转到详情页，在跳转前(beforeDestroy/destroyed)时，message信息框能自动销毁，在detail(详情页)不显示message信息框。

### What is actually happening?
在lis页面(主页面)获取完列表后，弹出message信息框，点击跳转到详情页，在详情页面，message信息框还是存在。

**Comment by ziyoung** [comment]
Duplicate of #11615

**Comment by Leopoldthecoder** [comment]
@ziyoung 不是这个问题。
@fengyun2 可以在 list 页面添加以下代码：
```js
watch: {
    "$route.path"() {
      this.$message.closeAll();
    }
  }
```
