### ISSUE TITLE
Can [Feature Request] use the form of El to submit it without using Ajax?

### ISSUE THREAD

**Issue by misskter** [ElemeFE/element#11782]
### Existing Component
是

### Component Name
el-form

### Description
我们使用的是Jsp的方式，因为现在有个需求是vue 实现，但是发现很多功能都必须得依赖于jquery 所以使用vue 和 jquery分开的方式实现，现在的需求是Vue提交的表单然后跳转到另外的页面里，想问下可不可以使用类似于原来的java web的方式提交表单的方式，不使用vue-resource或者axios这种ajax的方式提交

**Comment by jikkai** [comment]
https://jsfiddle.net/cwL6ug4a/
