### ISSUE TITLE
[Feature Request] Select component can not fold when click the top the

### ISSUE THREAD

**Issue by irenexixi** [ElemeFE/element#11786]
### Existing Component
是

### Component Name
Select

### Description
展开下拉框后操作浏览器顶部工具栏，例如输入url，点击其他可交互的文字或按钮，下拉框未收起，查看antDesign是可以的

**Comment by Leopoldthecoder** [comment]
目前所有弹出类菜单的行为都是如此，暂时没有计划修改。
