### ISSUE TITLE
Popover slot内嵌table时定位错误

### ISSUE THREAD

**Issue by chenjsh36** [ElemeFE/element#1179]
### ElementUI version

1.0.1
### OS/Browers version

chrome53
### Vue version

2.0.5
### Reproduction Link

http://jsfiddle.net/chenjsh36/pjxxnpx6/
### Steps to reproduce
jsfiddle ,第一次点击按钮后，弹出的表格定位错误，关闭后再次点击这个按钮才恢复正常定位
### What is Expected?
希望能正常定位表格的位置

**Comment by QingWei-Li** [comment]
抱歉这么晚回复
这个要修复起来有点麻烦，而且比较特殊（只针对 Table），如果只为了解决这个问题，可以给 table 设置 `height` 属性

http://jsfiddle.net/cinwell_li/pjxxnpx6/5/

```html
<el-table
      :data="topicAllArticle"
      :height="500"
      style="width: 100%">
```

**Comment by lihuangshuaige** [comment]
新版本解决了吗？
