### ISSUE TITLE
[Feature Request] Unable to have check boxes without label

### ISSUE THREAD

**Issue by sohail85** [ElemeFE/element#11790]
### Existing Component
Yes

### Component Name
el-checkbox

### Description
I am trying to display data in tabular layout with checkbox for each record. I tried to make use of el-checkbox but without binding to label properties I am unable to make it work propery, it would be nice to render checkboxes under list without having labels.
something as follow
`<el-checkbox v-model="bindingModel" :value="valueToBeAddedInsideBindingModelList"/>`

**Comment by jikkai** [comment]
Do you mean this https://jsfiddle.net/yqdrpLv3/

**Comment by sohail85** [comment]
@jikkai : this is exactly what I wanted and I end up styling the list to make the display property of labels none, although the provided solution is also a hacky solution.
display label should not be the bounded value of checkbox and it should be fixed to make it powerfull component
