### ISSUE TITLE
[Bug Report] how to use custom theme with babel-plugin-component

### ISSUE THREAD

**Issue by chavesgu** [ElemeFE/element#11796]
### Element UI version
2.4.1

### OS/Browsers version
macos/chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
i use babel-plugin-component to load element-component i need, and it will auto load corresponding css,
but i want to use my theme for element-component loaded, so  how can i do to load scss i need once.

### What is Expected?
load scss i need once.

### What is actually happening?
load all scss and some css file for element-component loaded

**Comment by ziyoung** [comment]
Set `styleLibraryName` for babel-plugin-component. http://element.eleme.io/#/zh-CN/component/custom-theme

**Comment by chavesgu** [comment]
@ziyoung 文档上是要install官方的主题工具 然后编译成所有组件对应的css  然后通过babel-plugin-component引入   用原本的scss文件无法按需引入吗？？

**Comment by ziyoung** [comment]
直接引用编译后的 CSS 文件就可以了，为什么还要再引入原来的 scss 呢？https://github.com/ElementUI/babel-plugin-component#example

**Comment by chavesgu** [comment]
@ziyoung   因为我尝试使用自定义主题，我修改了babel-plugin-component的`core.js`的源码，
concat(libraryName, "/").concat("**packages**", "/").concat(themeName);
然后在.babelrc里设置`styleLibraryName`为`theme-chalk/src`，设置`ext`为`.scss`
完成了我想要的结果，这个做法虽然不规范，不过省去了官方文档繁琐的过程。
你觉得如何

**Comment by songStar0904** [comment]
> @ziyoung 因为我尝试使用自定义主题，我修改了babel-plugin-component的`core.js`的源码，
> concat(libraryName, "/").concat("**packages**", "/").concat(themeName);
> 然后在.babelrc里设置`styleLibraryName`为`theme-chalk/src`，设置`ext`为`.scss`
> 完成了我想要的结果，这个做法虽然不规范，不过省去了官方文档繁琐的过程。
> 你觉得如何

![image](https://user-images.githubusercontent.com/21984603/79890117-98cc2100-8431-11ea-840c-1a9a133698a4.png)
我用了你的方法打包还是报错 好像是无法解析 请问要怎么处理
