### ISSUE TITLE
[Bug Report] Style error when using "prepend"/"append" slots on el-input-number

### ISSUE THREAD

**Issue by coolucifer** [ElemeFE/element#11792]
### Element UI version
2.4.2

### OS/Browsers version
Windows 10 1803

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/coolucifer/4x0taejk/4/](https://jsfiddle.net/coolucifer/4x0taejk/4/)

### Steps to reproduce
create one el-input-number, add template slot='append' or 'prepend'

### What is Expected?
same as el-input with 'prepend'/'append' slots

### What is actually happening?
controls = "true":
![image](https://user-images.githubusercontent.com/23123540/42068723-4bd56eda-7b80-11e8-9472-d5891e78485e.png)

controls = "false":
![image](https://user-images.githubusercontent.com/23123540/42068736-5bef9f5c-7b80-11e8-9d4a-c0ce687ef617.png)

**Comment by Leopoldthecoder** [comment]
InputNumber doesn't support prepend and append slots.

**Comment by coolucifer** [comment]
@Leopoldthecoder [#1709](https://github.com/ElemeFE/element/pull/1709)
so this update has been discarded?

**Comment by Leopoldthecoder** [comment]
Yes, that update only worked until 1.1.6. And only the `prepend` slot actually worked without a style error: https://jsfiddle.net/qmh02fyz/2/ .

**Comment by zhangbing3** [comment]
2.4.6为啥删除 “prepend” 和 “append”，前面已经使用了这两个属性，这一升级工作量太大了，能否加回啊。
![image](https://user-images.githubusercontent.com/20416489/44827455-c6a19800-ac45-11e8-9531-5395c3a4a2b5.png)
