### ISSUE TITLE
[Bug Report] used Popover to delete the operation in table, rendering multiple Popover forms at one time.

### ISSUE THREAD

**Issue by Shruan** [ElemeFE/element#11791]
### Element UI version
2.4.2

### OS/Browsers version
Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://shruan.github.io/AdminTemplate/#/activityManage/myActivity](https://shruan.github.io/AdminTemplate/#/activityManage/myActivity)

### Steps to reproduce
 项目展示效果：https://shruan.github.io/AdminTemplate/#/activityManage/myActivity  
实际代码（250-280行）：https://github.com/Shruan/AdminTemplate/blob/master/src/pages/activityManage/myActivity/Index.vue
jsfiddle代码：https://jsfiddle.net/u5tL86o9/11/

同样的代码在jsfiddle里没有出现这个问题  但是在我的项目里出现了 而且还一次渲染了三个窗体

![image](https://user-images.githubusercontent.com/28869029/42048814-e67e29bc-7b36-11e8-91b2-802bdb0df252.png)

![image](https://user-images.githubusercontent.com/28869029/42049175-c3012344-7b37-11e8-8043-f3f2735620a6.png)

### What is Expected?
希望能知道这是不是代码bug 还是组件有问题。或者能提供一个关闭全部popover的事件

### What is actually happening?
点击删除按钮 出现三个popover窗体 点击取消按钮或三个窗体同时消失

**Comment by jikkai** [comment]
Duplicate of #11704
