### ISSUE TITLE
[Bug Report] el-input-number defaultValue

### ISSUE THREAD

**Issue by Disoc** [ElemeFE/element#11800]
### Element UI version
2.4.1

### OS/Browsers version
all

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Initializes the el-input-number，Why is the default value is equal to zero？
I think should be what all don't show，otherwise seem to be very abrupt

### What is Expected?
Initializes the el-input-numbe,The initial value is empty

### What is actually happening?
el-input-number defualt value is equal to zero

**Comment by jikkai** [comment]
Maybe it's a similar issue that with #11596. InputNumber can only accept numerical values.

**Comment by 191854169** [comment]
set the property of v-model equal to undefined
