### ISSUE TITLE
table 表头分组（多表头）

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1180]
更新的1.0.1版本没有更新有关表头分组（多表头）的功能，个人觉得在PC端table表格应该是用的最多最频繁的，很多业务都需要使用表头分组以此来区分不同的业务或者模块。请问下一个版本是否可以更新多表头的功能。

**Comment by summeryun** [comment]
表示强烈需要多表头功能，用户明确提出了这项需求，希望能尽快造福于我们哈

**Comment by WangTaoLove** [comment]
强烈希望您那边能够完善多表头的功能，谢谢🙏

**Comment by perfectyang** [comment]
我也觉得，什么强烈啊

**Comment by furybean** [comment]
与 #1012 重复，请关注 1012 的状态。
