### ISSUE TITLE
内置和外置同时使用导致内置图标错位

### ISSUE THREAD

**Issue by Wfuren** [ElemeFE/element#11804]
![default](https://user-images.githubusercontent.com/29916783/42084680-e90f7232-7bc0-11e8-89d2-7ff7f148c81e.png)
![default](https://user-images.githubusercontent.com/29916783/42084686-f7276636-7bc0-11e8-83f9-3f261d6ce37d.png)
内置和外置同时使用导致内置图标错位

**Comment by ziyoung** [comment]
ref #11441
