### ISSUE TITLE
After the [Feature Request] tree component changes the show-checkbox property, the interface is rendered incorrectly.

### ISSUE THREAD

**Issue by xionggen** [ElemeFE/element#11806]
### Existing Component
是

### Component Name
el-tree

### Description
1.默认设置show-checkbox组件为false，不展示节点的复选框
2.手动更改show-checkbox的值为true，一级树节点未展示复选框

**Comment by jikkai** [comment]
请提供一个在线 demo

**Comment by ruofeng086** [comment]
+1
