### ISSUE TITLE
[Feature Request] upload "limit" reached, I hope it can replace the old file when i reselect file.

### ISSUE THREAD

**Issue by MicyToy** [ElemeFE/element#11801]
### Existing Component
Yes

### Component Name
EL-UPLOAD

### Description
when i set "limit" to uplaod. I think there may be a switch to set that I can replace the old file when i reselect file, otherwise response nothing.
like https://jsfiddle.net/1bntk75u/12/

**Comment by jikkai** [comment]
Sorry, we have no plan to support this. You can implement it like your demo.
