### ISSUE TITLE
[Feature Request] Can add  table columns filter slot at el-table?

### ISSUE THREAD

**Issue by ruifeng96150** [ElemeFE/element#11807]
### Existing Component
Yes

### Component Name
el-table

### Description
Sometimes, users want to search some thing at special column, so I think it is possible to implement at el-table? Yes, the requirement that column with enumeration filter has been implemented at current version. But some columns may need date range or number range or input keyword and so on. So slot and function interface may allow user to define their filters. This slot can placed between the table header and table data.

**Comment by verzilka** [comment]
+1 I need this too.
I had to create my own wrapper instead of filter-panel and patch table elements in ugly way =(
Hope this can have native support. Please )

**Comment by iuxw** [comment]
+1

**Comment by sotaan** [comment]
+1 plz this will be usefull

**Comment by Mont4** [comment]
Similar to https://onewaytech.github.io/vue2-datatable/examples/dist/

<img width="1440" alt="screen shot 2018-12-29 at 9 17 38 pm" src="https://user-images.githubusercontent.com/41866067/50540866-39e4f780-0baf-11e9-8c1a-d3c28510e118.png">

**Comment by Mortimer2013** [comment]
+1
