### ISSUE TITLE
[Bug Report] built-in and external use leads to built-in icon misplacement.

### ISSUE THREAD

**Issue by Wfuren** [ElemeFE/element#11805]
### Element UI version
2.4.1

### OS/Browsers version
UBUNTU

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3004/](https://jsfiddle.net/mmx38qxw/3004/)

### Steps to reproduce
input使用内置外置，导致内置图标不能垂直居中

### What is Expected?
input使用内置外置，应该可以垂直居中

### What is actually happening?
input使用内置外置，导致内置图标不能垂直居中

**Comment by jikkai** [comment]
https://jsfiddle.net/mmx38qxw/3007/
