### ISSUE TITLE
[Bug Report] form validation does not work with v-model but it works with using :model

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#11812]
### Element UI version
2.4.2

### OS/Browsers version
mac os chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/oga09bk4/13/](https://jsfiddle.net/oga09bk4/13/)

### Steps to reproduce
type any string in input field

### What is Expected?
form should be valid if any character is typed in the input field

### What is actually happening?
it is not validating.

NOTE:
the validation works after changing v-model="ruleForm" for :model="ruleForm"

**Comment by Leopoldthecoder** [comment]
1. Your demo seems to be irrelevant.
2. This is not a bug:
![image](https://user-images.githubusercontent.com/10095631/42130102-aa7fea28-7d0b-11e8-8a5d-f68f682584a0.png)
