### ISSUE TITLE
Unexpanded rows in [Bug Report] el-table and span tags are not complete.

### ISSUE THREAD

**Issue by wangmin19861205** [ElemeFE/element#11813]
### Element UI version
2.4.1

### OS/Browsers version
macbook 10.11.5

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3020/](https://jsfiddle.net/mmx38qxw/3020/)

### Steps to reproduce
展开行的span标签,在展示过长的字符串时,没有换行,没有滚动条

### What is Expected?
换行

### What is actually happening?
没有换行,没有滚动条

**Comment by wangmin19861205** [comment]
<img width="1276" alt="qq20180701-093940 2x" src="https://user-images.githubusercontent.com/7638971/42130282-b4cca4ce-7d12-11e8-822a-63e8fb245a14.png">
<img width="1254" alt="qq20180701-093924 2x" src="https://user-images.githubusercontent.com/7638971/42130283-b52009c0-7d12-11e8-97b1-f165f854d64c.png">

**Comment by jikkai** [comment]
特殊使用场景可以考虑覆盖 css：https://jsfiddle.net/mmx38qxw/3021/
