### ISSUE TITLE
[Bug Report] How to edit/update same object in the array without changing index value

### ISSUE THREAD

**Issue by creativemind1** [ElemeFE/element#11815]
### Element UI version
2.4.2

### OS/Browsers version
Windows 8.1

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/creativemind1/4q1f58xj/24/](https://jsfiddle.net/creativemind1/4q1f58xj/24/)

### Steps to reproduce
1. Please add any text in the input box and submit. The text will be added in the array of table box with edit button.
2. Click on edit button, the same added text of that row will be re-added in the input box.
3. Please change the text to something different.
4. Submit
5. You will notice it will create new object instead of updating same object

### What is Expected?
The old value should be replaced with the newly updated text (object).

### What is actually happening?
New object is creating

**Comment by Leopoldthecoder** [comment]
I don't see anything wrong here. When you submit, you're always pushing a new object to the `this.tableData` array:
```js
this.tableData.push({
  value: this.value1
})
```
So of course a new object will be created.

**Comment by creativemind1** [comment]
No I mean I'm missing some code like this.$set(this.tableData) which will update the edited object. I'm unable to update the object
