### ISSUE TITLE
[Feature Request] select provides the parameters of the custom input area length, and is currently fixed 50px dead.

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#11826]
### Existing Component
是

### Component Name
select

### Description
当 select使用filter、multiple、collapse-tags参数时，输入框输入区域固定死50px。希望自定义。
element 代码：
       if (this.multiple && this.filterable) {
          const length = this.$refs.input.value.length * 15   20;
          this.inputLength = this.collapseTags ? Math.min(50, length) : length;
          ……
        }

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
