### ISSUE TITLE
[Feature Request] Suggest: Event bubbling

### ISSUE THREAD

**Issue by wangcch** [ElemeFE/element#11820]
### Existing Component
No

### Component Name
2.4.2

### Description
Mac OS / Chrome 67.0.3396.99

### Reproduction Link
https://jsfiddle.net/wangcch/65k8btx0/6/

### Steps to reproduce
Table ( Expandable row ) whole row click event. and row have other click events

### What is Expected?
Not a problem. One Suggest. Add event bubbling attribute (boolean)

Thank you~

**Comment by jikkai** [comment]
Actually vuejs has [directive postfixes](https://vuejs.org/v2/guide/events.html#Event-Modifiers) to stop event bubbling.

So we can make it easier: https://jsfiddle.net/65k8btx0/7/
