### ISSUE TITLE
[Feature Request] Add 'disabled' option to el-dropdown split-button buttons

### ISSUE THREAD

**Issue by hairui219** [ElemeFE/element#11823]
### Existing Component
Yes

### Component Name
el-dropdown

### Description
The option items can be disabled with ```disabled``` flag. But the button of ```split-button``` option didn't support the ```disabled``` flag. Disable the button is useful at some cases.

**Comment by ziyoung** [comment]
@hairui219 Yes, ElDropdown should support `disabled` attribute.

**Comment by pengliheng** [comment]
how to disabled, no reference in `Element-UI` document.

**Comment by walirt** [comment]
> @hairui219 Yes, ElDropdown should support `disabled` attribute.
Not the disabled option of `el-dropdown`, is `split-button`

**Comment by walirt** [comment]
> @hairui219 Yes, ElDropdown should support `disabled` attribute.

Not the disabled option of el-dropdown, is split-button

**Comment by walirt** [comment]
> @hairui219 Yes, ElDropdown should support `disabled` attribute.

Not a disabled option for `el-dropdown`, but `split-button`

**Comment by gamenic-dipendra** [comment]
Just use class 'disabled' to achieve this
```
<el-dropdown split-button type="primary"
          class="disabled">
```
