### ISSUE TITLE
[Feature Request] Uploading multiple files to different urls with different data.

### ISSUE THREAD

**Issue by denciochronize** [ElemeFE/element#11828]
### Existing Component
Yes

### Component Name
File upload

### Description
Upload 2 files to different urls with different data. Currently, the file upload can only use specific url and data. I want the upload :action and :data attributes to be dynamically set per file upload request.
Is there a way in onBeforeUpload hook event that I could change the file url and data before proceeding to upload process.

**Comment by ziyoung** [comment]
@denciochronize Uploading files is concurrent, not blocked. 
https://github.com/ElemeFE/element/blob/b799d2ec4dfe7a08cb42d510de5653c8165a3219/packages/upload/src/upload.vue#L79-L82
Maybe you need use two `ElUpload` components.

**Comment by denciochronize** [comment]
@ziyoung 
Thank you for your response, but I am confused right now. My current implementation is I only have 1 
`ElUpload`

**Comment by denciochronize** [comment]
@ziyoung 
Thank you for your response. Sorry but I am still confused, right now my current implementation is I have 1 `ElUpload` component then in `before-upload` hook I have a checking whether which URL is supposed to be used. If I will add another `ElUpload` component that means there will be 2 drop areas with same `before-upload` hook. Or I am missing something here. I hope you will read this comment and give me advise. Thank you.

**Comment by ziyoung** [comment]
@denciochronize maybe you need set `http-request` for `el-upload`. http://element.eleme.io/#/en-US/component/upload#attributes

**Comment by denciochronize** [comment]
@ziyoung Sorry to take your time, I found a workaround. thank you.

**Comment by my9074** [comment]
@denciochronize  I have the same problem，What's your solution

**Comment by lishuo666** [comment]
666

**Comment by denciochronize** [comment]
@my9074 @lishuo666

Hi sorry for late response,
The workaround was during upload I would create an array of object e.g. 
[{
  file,
  url,
  etc.. // whatever property you like
}]

Since you can catch the file object onBeforeUpload event, you could also specify what url you want and more. Finally, iterate those list of objects with <el-upload> set the properties like the url etc. and manually submit those <el-upload> instances you created with different url.

*Note: I added a key for each object so I would know what to submit.
