### ISSUE TITLE
[Bug Report] [MessageBox]click to open the message box, then press the enter , the box disappear, then press the enter again ,the box will appear again

### ISSUE THREAD

**Issue by rabbit-deer-you** [ElemeFE/element#11829]
### Element UI version
2.4.2

### OS/Browsers version
macos/chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3106/](https://jsfiddle.net/mmx38qxw/3106/)

### Steps to reproduce
click to open the message box, then press the enter , the box disappear, then press the enter again ,the box will appear again

### What is Expected?
the messagebox will not appear once

### What is actually happening?
the messagebox will appear twice

**Comment by Leopoldthecoder** [comment]
This is an intended accessibility feature.

**Comment by jinbaoqi** [comment]
@Leopoldthecoder what's its purpose? its callbacks will trigger again and when will this event unset?
