### ISSUE TITLE
[Bug Report], due to the problem of Vue running mechanism, can cause the span-method method to trigger the table component when the data of each binding changes, and the format of the table will change.

### ISSUE THREAD

**Issue by PrincipleFirst** [ElemeFE/element#11836]
### Element UI version
2.4.3

### OS/Browsers version
windows 10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3120/](https://jsfiddle.net/mmx38qxw/3120/)

### Steps to reproduce
选择时间后再点击页面，表格格式就会发生改变

### What is Expected?
其他数据发生变化时不触发span-method方法，表格格式不发生变化

### What is actually happening?
其他数据发生变化时触发了span-method方法，表格格式发生变化

**Comment by Leopoldthecoder** [comment]
看了一下，和其他数据的变化无关。问题的原因是点击 Table 的某一行时，会触发组件内部一些数据的更新，从而使 Table 重新渲染，而此时 `spanMark` 已经不是 0 了。解决方法是在每次渲染后将 `spanMark` 重置：https://jsfiddle.net/mmx38qxw/3135/
