### ISSUE TITLE
The problem of Chinese input method for [Bug Report] Select selector

### ISSUE THREAD

**Issue by pz25925** [ElemeFE/element#11844]
### Element UI version
2.4.3

### OS/Browsers version
window10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3139/](https://jsfiddle.net/mmx38qxw/3139/)

### Steps to reproduce
1. 使用中文输入法

2. 输入 a

3, Enter 键入

4, 没有触发搜索

### What is Expected?
搜索a

### What is actually happening?
没有搜索

**Comment by ziyoung** [comment]
@pz25925 设置一下 `el-option` 的 `value` 属性。https://jsfiddle.net/zhiyang/mmx38qxw/3146/

**Comment by Leopoldthecoder** [comment]
经测试发现在 Windows 10、Chrome 和搜狗浏览器条件下能够重现问题。
