### ISSUE TITLE
When [Bug Report] select is set to be multiple selected and searchable, the drop-down list cannot be clicked away.

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#11846]
### Element UI version
2.4.3

### OS/Browsers version
windows 10 /chrome 67.0.3396.79

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/cy4nka65/5/](https://jsfiddle.net/cy4nka65/5/)

### Steps to reproduce
select 设置为多选、可搜索时，
点击输入，下拉列表展开，
再次点击，不能被收起。

### What is Expected?
下拉列表收起。

### What is actually happening?
下拉列表未收起。

**Comment by ziyoung** [comment]
@AprilXtt 两个 select 组件 v-model 绑定的都是同一个值。多选的话，v-model 绑定的值该是数组才对。https://jsfiddle.net/zhiyang/cy4nka65/7/
