### ISSUE TITLE
[Feature Request] there is no visible attribute in props in el-dialog's source code. Where is it, please?

### ISSUE THREAD

**Issue by w1301625107** [ElemeFE/element#11857]
### Existing Component
Yes

### Component Name
el-dialog

### Description
 <el-dialog title="角色信息修改"
               :visible.sync="dialogVisible"
               width="800px">
这里的 :visible , 为什么我在el-dialog里的源码props 里没有看到，请问是在哪里

**Comment by Leopoldthecoder** [comment]
In the popup mixin: https://github.com/ElemeFE/element/blob/dev/src/utils/popup/index.js
