### ISSUE TITLE
[Bug Report] clicks <el-input> in the <el-upload> tag and pops out the selection file window.

### ISSUE THREAD

**Issue by blueroseslol** [ElemeFE/element#11855]
### Element UI version
2.4.1

### OS/Browsers version
win7 chrome 65.0

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/bluerose/wr0u8vo2/1/](https://jsfiddle.net/bluerose/wr0u8vo2/1/)

### Steps to reproduce
点击el-input

### What is Expected?
一般el-input的行为

### What is actually happening?
点击el-input后，会弹出el-upload的选择文件窗口

**Comment by jikkai** [comment]
这需求比较偏，不是很常见，好像也有更好的解决方案在，先在原有的基础上尝试下阻止冒泡吧：https://jsfiddle.net/wr0u8vo2/2/

**Comment by blueroseslol** [comment]
问题解决，感谢回复
