### ISSUE TITLE
[Feature Request] How do you return data to the tree component tree?

### ISSUE THREAD

**Issue by itlixiaolong** [ElemeFE/element#11856]
### Existing Component
是

### Component Name
el-tree

### Description
When a node is selected by clicking on the checkbox, I want to return the data to the tree component after modifying it,how should i realize this

**Comment by ziyoung** [comment]
@itlixiaolong 不太明白什么意思？

**Comment by itlixiaolong** [comment]
我想做的操作是这样的点击某个checkbox,想修改这个chekbox对应的传入tree组件的node的数据,这个怎么实现

**Comment by jikkai** [comment]
看看提供的[事件](http://element.eleme.io/#/zh-CN/component/tree)能否解决你的问题，我觉得`check`或者`check-change`应该能满足你描述的需求。

**Comment by itlixiaolong** [comment]
谢谢您的回复,目前的elemntui中的tree组件的关于checkbox的事件回调参数中缺少node参数,只有 data参数,我在尝试采用其他方法解决 @jikkai @ziyoung
