### ISSUE TITLE
The [Bug Report] form method was miswritten in API

### ISSUE THREAD

**Issue by wang3156** [ElemeFE/element#11862]
### Element UI version
2.4.3

### OS/Browsers version
谷歌

### Vue version
2.5.17-beta.0

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
Form-Item Methods
方法名	说明	参数
resetField	对该表单项进行重置，将其值重置为初始值并移除校验结果	-
clearValidate	移除该表单项的校验结果	-
这个是官方说明 
但我调用resetField	时一直提示不存在,后来查了资料发现应该是resetFields 调整后就正常了,请确认

### What is Expected?
另外希望的功能 
   在绑定数据时能获取到绑定该行的原数据,如 下拉列表 绑定时只绑定了 label和val 和key 但我在change事件里就获取不到这个数据( api写的回调参数是当前选择的val但实际上没获取到,但如果我在绑定事件处改为 changexxx($event) 则会接收到用户选择的值),很多时候 我希望能获取到绑定的行数据中的其它数据去显示到页面操作就比较麻烦

### What is actually happening?
无

**Comment by jikkai** [comment]
`resetField`是`el-form-item`的方法，你说的`resetFields`应该是`el-form`的方法，请注意两者之间的区别：https://jsfiddle.net/cLxtau8g/
