### ISSUE TITLE
[Bug Report] A funny issue.

### ISSUE THREAD

**Issue by qwIvan** [ElemeFE/element#11868]
### Element UI version
2.4.3

### OS/Browsers version
x86_64 Linux 4.17.3-1-ARCH，Chrome 67.0.3396.99

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/pkoz6a9s/](https://jsfiddle.net/pkoz6a9s/)

### Steps to reproduce
https://jsfiddle.net/o2s8m9qg/ 是官方demo
我在<el-table>下加了一个<div>，变成https://jsfiddle.net/pkoz6a9s/的效果，第一列（日期）竟然跑到最后了。

### What is Expected?
日期应在第一列，如 https://jsfiddle.net/o2s8m9qg/

### What is actually happening?
https://jsfiddle.net/pkoz6a9s/
日期跑到了最后

**Comment by qwIvan** [comment]
我有一个
```
    <el-table :data="dataList">
      <slot/>
    </el-table>
```
同时又有一个table.vue
```
<template>
	<div>
		<el-table-column>
         		...
		</el-table-column>
	</div>
</template>

```
我试图把table.vue填充进<slot>中，这个问题就产生了。

**Comment by jikkai** [comment]
Duplicate of #11708
