### ISSUE TITLE
[Bug Report] single form-item (input>text) press enter event bug

### ISSUE THREAD

**Issue by wangcch** [ElemeFE/element#11865]
### Element UI version
2.4.3

### OS/Browsers version
Mac OS / Chrome 67.0.3396.99

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/wangcch/bLx06rj5/16/](https://jsfiddle.net/wangcch/bLx06rj5/16/) 
Notice: You need to click 'Run' (jsfiddle)  again to run

### Steps to reproduce
Use a single el-form-item el-form with an input>text box. Next,  you need to select the input box and press enter.

### What is Expected?
Perform related events.  (Suppose a carriage return event binding is added.)

### What is actually happening?
The url will change, causing the route changes

**Comment by jikkai** [comment]
https://element.eleme.io/#/en-US/component/form#basic-form
![image](https://user-images.githubusercontent.com/14025786/42274832-b68dc26a-7fc0-11e8-9887-93991e835ceb.png)

**Comment by wangcch** [comment]
I'm sorry. It's my fault
