### ISSUE TITLE
[Bug Report]The tree component returns through the data request, and then executes the selected event. At this time, no effect is selected and settomeout is needed.

### ISSUE THREAD

**Issue by janxy** [ElemeFE/element#11876]
### Existing Component
是

### Component Name
tree

### Description
tree组件通过数据请求回来，然后在执行选中事件，这时选中无效果，需要settomeout才可以。

**Comment by ziyoung** [comment]
@janxy 请提供一个可重现问题的 demo。

**Comment by janxy** [comment]
就是想问问，tree组件动态获取data后有类似加载完成的方法和事件吗。

**Comment by jikkai** [comment]
尝试下[`this.$nextTick`](https://cn.vuejs.org/v2/api/index.html#vm-nextTick)，另外：

1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
