### ISSUE TITLE
[Bug Report] uses el-select component in IE browser, readonly is invalid, cursor still focuses.

### ISSUE THREAD

**Issue by 994060165** [ElemeFE/element#11874]
### Element UI version
1.4.1

### OS/Browsers version
windows10/ie11

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
界面中引用el-select组件，在ie浏览器下查看，使用readonly属性，仍可看到光标聚焦在input框上；（http://element.eleme.io/2.4/#/zh-CN/component/select）在ie浏览器下查看；
element-ui官网上即可查看，重现链接因为一直未通过，所以用的别人的链接，非常抱歉；

### What is Expected?
希望在ie浏览器下查看，使用readonly属性，光标不再聚焦在input框上；

### What is actually happening?
在ie浏览器下使用el-select组件，使用readonly属性，仍可看到光标聚焦在input框上；

**Comment by ziyoung** [comment]
IE 的 bug 吧。https://stackoverflow.com/questions/7917592/html-cursor-showing-in-readonly-input-text

**Comment by 994060165** [comment]
好的，非常感谢您查看了这个问题。我在项目中使用了其它的方法处理了这个问题。

**Comment by janly-li** [comment]
我也遇到的相同的问题，请问你是用什么方法处理这个问题的？

**Comment by fengCol** [comment]
how to resolve the bug?

**Comment by fengCol** [comment]
刚在stackoverflow上面找到答案
**const nodeList = document.querySelectorAll('input[readonly]')
    
for(let i = 0;i<nodeList.length;i++) {
      nodeList[i].addEventListener('focus',function(){
      this.blur();
});**

**Comment by janly-li** [comment]
> 刚在stackoverflow上面找到答案
> const nodeList = document.querySelectorAll('input[readonly]')
> 
> for(let i = 0;i<nodeList.length;i++) {
> nodeList[i].addEventListener('focus',function(){
> this.blur();
> });

这样会不会所有的input都只读了？

**Comment by fengCol** [comment]
> > 刚在stackoverflow上面找到答案
> > const nodeList = document.querySelectorAll('input[readonly]')
> > for(let i = 0;i<nodeList.length;i++) {
> > nodeList[i].addEventListener('focus',function(){
> > this.blur();
> > });
> 
> 这样会不会所有的input都只读了？

只针对只读的input框做隐藏光标的设置，不是针对所有的input

**Comment by janly-li** [comment]
> > > 刚在stackoverflow上面找到答案
> > > const nodeList = document.querySelectorAll('input[readonly]')
> > > for(let i = 0;i<nodeList.length;i++) {
> > > nodeList[i].addEventListener('focus',function(){
> > > this.blur();
> > > });
> > 
> > 
> > 这样会不会所有的input都只读了？
> 
> 只针对只读的input框做隐藏光标的设置，不是针对所有的input

好的，非常感谢你

**Comment by fengCol** [comment]
> > > > 刚在stackoverflow上面找到答案
> > > > const nodeList = document.querySelectorAll('input[readonly]')
> > > > for(let i = 0;i<nodeList.length;i++) {
> > > > nodeList[i].addEventListener('focus',function(){
> > > > this.blur();
> > > > });
> > > 
> > > 
> > > 这样会不会所有的input都只读了？
> > 
> > 
> > 只针对只读的input框做隐藏光标的设置，不是针对所有的input
> 
> 好的，非常感谢你

不客气
