### ISSUE TITLE
[Bug Report] el-input value change does not trigger @change event

### ISSUE THREAD

**Issue by GaliMU** [ElemeFE/element#11873]
### Element UI version
2.4.3

### OS/Browsers version
mac / chrome 67

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3264/](https://jsfiddle.net/mmx38qxw/3264/)

### Steps to reproduce
1. 在输入框输入任意字符，div 里的value并不会改变。
2. 使输入框失去焦点，触发valuechange事件

### What is Expected?
@change 在 el-input 的值改变的时候触发，在element-ui 1.4.13 中是这样触发的。

### What is actually happening?
@change 在el-input失去焦点或会车时才触发

**Comment by jikkai** [comment]
Duplicate of #9284
