### ISSUE TITLE
fork到本地 出现 找不到 installation.md问题

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#1188]
### What is actually happening?

![image](https://cloud.githubusercontent.com/assets/6311122/20421842/8d3ad5f8-ada1-11e6-9d88-a424c6f9752b.png)

**Comment by QingWei-Li** [comment]
不会呀 这个文件是存在的 https://github.com/ElemeFE/element/blob/dev/examples/docs/zh-CN/installation.md 重新 clone 试试

**Comment by spademan** [comment]
只能是这样了 ~~
