### ISSUE TITLE
[Feature Request] Enhancement for the el-select component multiple rows for every for

### ISSUE THREAD

**Issue by david2tdw** [ElemeFE/element#11880]
### Existing Component
是

### Component Name
el-select

### Description
Could you help to do an enhancement for the el-select component?

i need a dropdown list that have multiple rows for one option. i know we can put html template to el-option slot, but it only can show one row for  one option.

you can refer to the 运价查询 tab in web http://www.feeair.com/ for sample.

Thanks

**Comment by jikkai** [comment]
You can implement this case with a little CSS: https://jsfiddle.net/qnzp7Lef/

**Comment by david2tdw** [comment]
@jikkai thank you.

**Comment by legreco** [comment]
@jikkai It doesnt work for me. I have the same problem
