### ISSUE TITLE
[Bug Report] El-Input will remove minus sign if the number starts with zero

### ISSUE THREAD

**Issue by fergardi** [ElemeFE/element#11885]
### Element UI version
2.4.3

### OS/Browsers version
Google Chrome Versión 67.0.3396.99 (Build oficial) (64 bits)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/dox3qvLk/](https://jsfiddle.net/dox3qvLk/)

### Steps to reproduce
Try to type this number:

-0.25

1. Type "-" (MINUS)
2. Type "0" (ZERO) => The minus disappears!
3. Type "." (DOT)
4. Type "2" (TWO)
5. Type "5" (FIVE)

### What is Expected?
The minus should not disappear.

### What is actually happening?
The minus sign disappears.

**Comment by ziyoung** [comment]
@fergardi maybe you don't need use `number` [modifier](https://vuejs.org/v2/guide/forms.html#number).  [InputNumber](http://element.eleme.io/#/zh-CN/component/input-number) is your choice.

**Comment by fergardi** [comment]
@ziyoung `input-number` does not allow null or empty values whith a placeholder shown. **It translates the null to zero**.

**Comment by fergardi** [comment]
@ziyoung no placeholder then :sob: https://jsfiddle.net/ukrnfw75/

**Comment by ziyoung** [comment]
@fergardi sorry for my fault. I will reopen the issue.
