### ISSUE TITLE
[Feature Request] Turn el-select into tags input if it doesnt have el-option 

### ISSUE THREAD

**Issue by threeid** [ElemeFE/element#11897]
### Existing Component
Yes

### Component Name
el-select

### Description
Hello ElemeFE Team,

Thank you for make this awesome ElementUI.

Please consider turn el-select into tags input if it doesnt have el-option by disabling option panel (the bottom one).
https://jsfiddle.net/Lt52grqe/
![screenshot_20180706_202813](https://user-images.githubusercontent.com/37827220/42381424-338559a4-815b-11e8-8fd6-4afcf7f2bd6a.png)

This is helpful if you want to make unique tags input.
Like following picture:
![screenshot_20180706_201735](https://user-images.githubusercontent.com/37827220/42381229-a814c0ee-815a-11e8-863f-d8f43416d443.png)

Have a great weekends,
threeid

**Comment by threeid** [comment]
Thank @jikkai for taking this issue. 🤗

**Comment by jikkai** [comment]
Will, here is a tricky situation with this feature. Users can not enter two equal values with `el-select`, so we have to create a new `TagInput` component. Unfortunately now we have not enough resources to handle this case.

But you can still hide option panel by CSS which is just a workaround: https://jsfiddle.net/Lt52grqe/1/
