### ISSUE TITLE
The related problems of the [Feature Request] photo wall

### ISSUE THREAD

**Issue by cherishloveyou** [ElemeFE/element#11895]
### Existing Component
是

### Component Name
upload

### Description
感觉uploader picture-card的问题很多
1: 是 号达到最大限制数不隐藏 
2: 照片怎么修改大小 好像固定死了148px, 目前css !important修改会污染全局
3: 上传完毕后右上角有个绿色的指示状态 然后有个白色的√ 图片 （布局方式不对  修改大小后 位置会显示异常）
4: 上传大小时白色的圆环进度条  布局也有问题 大小不能自定义
5：就是已上传的照片交换显示位置（主要让fileList也排下序）社区也有提交patch 为什么没合并上来 我觉得还是实用的
   作为VUE的菜鸟，请大佬解答一下这些问题，怎么处理？

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by cherishloveyou** [comment]
我这明显是bug  布局问题不是bug么？  修改大小问题 算feature 还是bug 我也不好划分  我请问的并不是怎么使用的问题

**Comment by jikkai** [comment]
如果确认是 bug，请提供可复现问题的在线 demo。

如果有特殊需求，建议自行覆盖 css 解决

**Comment by cherishloveyou** [comment]
就是想调整大小 我觉得是正常需求不是什么特殊要求 只是通过CSS覆盖会造成全局污染 
然后通过CSS调整el-upload-list__item大小  发现原来的有些子元素布局方式不合理 
会造成好几个子布局错乱
