### ISSUE TITLE
The problem of [Bug Report] el-date-picker selection time

### ISSUE THREAD

**Issue by onefuyun** [ElemeFE/element#11901]
### Element UI version
0.1.0

### OS/Browsers version
window10  chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io](https://elementui.github.io)

### Steps to reproduce
给日期控件设置时间，默认显示，修改时间的时候，选中其他日期就报错：error in event handler for "pick" : "TypeError : date.getHours is not a function"    就给日期控件v-model="a"     。a = 15234230000这样一个时间戳。一些电脑是好的，另外一些不行。

### What is Expected?
可以选中日期

### What is actually happening?
给日期控件设置时间，默认显示，修改时间的时候，选中其他日期就报错：error in event handler for "pick" : "TypeError : date.getHours is not a function"    就给日期控件v-model="a"     。a = 15234230000这样一个时间戳。一些电脑是好的，另外一些不行。

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
