### ISSUE TITLE
[Bug Report] Slider show input setting Too strong, can't set width

### ISSUE THREAD

**Issue by weituotian** [ElemeFE/element#11903]
### Element UI version
2.4.1

### OS/Browsers version
windows7 chrome67

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/2e1y97sm/](https://jsfiddle.net/2e1y97sm/)

### Steps to reproduce
Using the Slider component, the outer layer width is 250px

### What is Expected?
Ability to set the width of the show-input

### What is actually happening?
Unable to set the width of show-input

![image](https://user-images.githubusercontent.com/7270968/42416658-fa3f6ad8-82a7-11e8-8c26-3a6b0158327b.png)

**Comment by weituotian** [comment]
This is the effect of `eqxiu` which i wanted. : 
![image](https://user-images.githubusercontent.com/7270968/42416673-2f5c18ba-82a8-11e8-826e-924daed938c0.png)

I used element-ui and have divided it into two lines. The effect is still so bad.
Can element ui do a better job? So many pits

**Comment by jikkai** [comment]
Sorry about that, UI library may not cover every case. In this case, you can overwrite the CSS.

**Comment by weituotian** [comment]
@jikkai 好坑好坑
