### ISSUE TITLE
[Feature Request] Every event needs more cunstom argument

### ISSUE THREAD

**Issue by see311** [ElemeFE/element#11902]
### Existing Component
是

### Component Name
el-select

### Description
The default event like @change of el-select needs more custom argument.
Default argument of change callback function is selected value, but some times I need transfer my own argument into it.
For example in a loop:
```html
<li v-for="(item, index) in roles">
    <el-select v-model="roleIds" multiple style="width:100%;" :disabled="length==0"  @change="projChange(value,index)">
        <el-option v-for="item in userRoleList[scope.$index]" :key="item.roleId" :label="item.roleName" :value="item.roleId"></el-option>
    </el-select>
</li>
```
I need selected value and index in the same time

**Comment by jikkai** [comment]
```
<el-select ... @change="value => handleChange(value, 'extra args')">
```

https://jsfiddle.net/4epq5raf/1/
