### ISSUE TITLE
[Bug Report] how to set daterange component disable the same date

### ISSUE THREAD

**Issue by Xavier0818** [ElemeFE/element#11907]
### Element UI version
2.3.9

### OS/Browsers version
win10,chrome 67

### Vue version
2.5.17-beta.0

### Steps to reproduce
1.select  start date
2.select  end date

### What is Expected?
after i select start date,the start date should be disabled,
then i could select other date except the start date,because it's disabled,
finally,i'll select a daterange that the start date and the end date are different

### What is actually happening?
after i select start date,the start date still can  be select,
user perhaps select the same date to get a daterange

**Comment by Xavier0818** [comment]
this issue  is my particular demand,and i found it was unnecessary to achieve after i practiced，
so i have the other revolution.i add a determine sentence to not allow user select the same date,
thanks for answers!!

**Comment by jikkai** [comment]
This is intended.

BTW, start date is not determined on first click :)

![](https://user-images.githubusercontent.com/14025786/42429630-af75626c-836c-11e8-9297-03669df579db.gif)
