### ISSUE TITLE
[Feature Request] change Pagination's layout text

### ISSUE THREAD

**Issue by bgadiel** [ElemeFE/element#11905]
### Existing Component
Yes

### Component Name
el-pagination

### Description
Is there a way to change the text for the ["total, jumper"]?
There is 'prev-text' and 'next-text', but I am looking for a way to update 'Go to' to something else.
Thanks.

**Comment by jikkai** [comment]
You can create your own locale file to overwrite `goto `
https://github.com/ElemeFE/element/blob/45241cbaa83a91198ffe1aae2483f67b862ddd75/src/locale/lang/en.js#L72-L77
