### ISSUE TITLE
[Feature Request] Let the page-sizes attribute supports “all”

### ISSUE THREAD

**Issue by shady-xia** [ElemeFE/element#11916]
### Existing Component
Yes

### Component Name
Pagination

### Description
Now the "page-sizes" attribute in "pagination" only support for Number[]，like this：[10, 20, 30, 40, 50, 100]
In my project, I need to show all data in table.  Is their any options , for example, "All", can be available to show all data in table?

I used to use datatables, the "lengthMenu" option can be 2D array, which will use the first inner array as the page length values and the second inner array as the displayed options. This is useful for language strings such as 'All'.

![image](https://user-images.githubusercontent.com/20945955/42444670-430fc70c-83a3-11e8-9bdf-d9d0dca08693.png)

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.
