### ISSUE TITLE
希望可以给el-table组件的expand-change事件回调函数增加一个当前被展开行的index参数

### ISSUE THREAD

**Issue by Generalize** [ElemeFE/element#11919]

**Comment by shiny** [comment]
我刚刚也遇到了这个问题， expand-change 事件中，如果修改了变量无法让 Vue 追踪到变化，只能通过 this.$set 的方式，但由于没有当前的 index，这种办法也无法实现。

**Comment by DusuWen** [comment]
你可以在格式化数据的时候在row里自己加一个属性index

**Comment by shiny** [comment]
可以参考这个 issue 里使用 indexOf 获取 index 的方式： #11920
