### ISSUE TITLE
[Feature Request] el-tree component plus node-hover events

### ISSUE THREAD

**Issue by kenziD** [ElemeFE/element#11911]
### Existing Component
是

### Component Name
el-tree

### Description
遇到一个功能点，使用json树结构渲染一个页面，然后使用el-tree展示这个json树，每个树节点是页面中的某个控件。需要鼠标悬浮在树的节点上，页面上对应的控件部分高亮。
I happen encounter a demand that there is a html page rendered by json tree structure data. And I use <el-tree> to display the json tree which tree node is a control in the page.I need when mouse hover on the tree node,the relative control part in the page will be highlighted.so I need a node-hover event.

**Comment by ziyoung** [comment]
@kenziD 这个场景真的很少见。

**Comment by ziyoung** [comment]
我们没有计划去实现该功能。
