### ISSUE TITLE
The [Bug Report] upload component changed the action parameter in before-upload, failed to make a correct report, and the change was not successful.

### ISSUE THREAD

**Issue by hongxiangWang** [ElemeFE/element#11922]
<img width="1279" alt="qq20180710-114901 2x" src="https://user-images.githubusercontent.com/17492881/42489068-76a0d97e-843b-11e8-84a3-00e47a2fb37b.png">

### Element UI version
2.4.3

### OS/Browsers version
mac 10.13 / Safari

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3400/](https://jsfiddle.net/mmx38qxw/3400/)

### Steps to reproduce
1、action 在data初始为空
2、获取上传文件只能在before-upload函数中，并对文件的类型，改变action的值
3、自动触发上传函数后报错
4、若在action初始值设为有效地址，不会报错

### What is Expected?
1、更改action的编码方式
2、使用on-change钩也无法更改成功

### What is actually happening?
无

**Comment by ziyoung** [comment]
@hongxiangWang 不是 ElementUI 的 bug。你可以通过设置 `http-request` 来覆盖默认的上传行为来实现该功能。
