### ISSUE TITLE
[Bug Report] Tree component item loses checkmark after drag&drop

### ISSUE THREAD

**Issue by primoz990** [ElemeFE/element#11927]
### Element UI version
2.4.3

### OS/Browsers version
MacOs-10.13.5/Chrome-67.0.3396.99

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mpbs4rt5/19/](https://jsfiddle.net/mpbs4rt5/19/)

### Steps to reproduce
1. First check one item,
2. Drag & drop it to a different position.

### What is Expected?
The dragged item should stay checked.

### What is actually happening?
The item loses its checkmark after drop

**Comment by yisiliang** [comment]
文件[tree.vue](https://github.com/ElemeFE/element/blob/dev/packages/tree/src/tree.vue#L451)的451行只取了node.data，应该还要取draggingNode.node.checked
```
        if (draggingNode && dropNode) {
          const draggingNodeCopy = { data: draggingNode.node.data };
          if (dropType !== 'none') {
            draggingNode.node.remove();
          }
```

**Comment by louisscrew** [comment]
这个bug在2.5.2中修复了吗？

**Comment by jplumez** [comment]
Hello,

It seems that a pull request #13276 has been done to fix this issue, but hasn't been merged. Is it possible to check it please ? 

I am facing this issue right now :( 

Thanks in advance !
