### ISSUE TITLE
[Feature Request] input-number controls event

### ISSUE THREAD

**Issue by Leo-lay** [ElemeFE/element#11921]
### Existing Component
Yes

### Component Name
InputNumber

### Description
the input-number component had a event of value change ,why not have a event by controls button? add and minus event.

**Comment by jikkai** [comment]
Sorry, we have no plan to support this. You can handle it like this: https://jsfiddle.net/xj9wvfsd/

**Comment by ziyoung** [comment]
@Leo-lay The InputNumber component is similar to the input element, so it can trigger `change` event.

**Comment by Leo-lay** [comment]
@ziyoung thank you reply 
 i know your means, in my project i use the same way @jikkai did it ,it looks like I have to encapsulate this component myself.
