### ISSUE TITLE
[Feature Request] hopes to add a index parameter of the currently displayed row to the callback function of the expand-change event of the el-table component.

### ISSUE THREAD

**Issue by Generalize** [ElemeFE/element#11920]
### Existing Component
Yes

### Component Name
el-table

### Description
希望可以给el-table组件的expand-change事件的回调函数增加一个当前被展开行的index参数
![image](https://user-images.githubusercontent.com/26076140/42462378-aedd24ac-83d5-11e8-911b-f4c59aa8efd3.png)

**Comment by jikkai** [comment]
expand-change 提供了 `row` 参数，可以通过其获取索引。

**Comment by shiny** [comment]
@jikkai 求教，row 参数不是只有当前行的值吗，如何才能获取 row 所处数组的 index？因为需要让 Vue 追踪 TableData 的变化，通过 this.$sex 需要此值。

**Comment by jikkai** [comment]
@shiny 
一般业务上有两种做法，如果是想追踪当前列表展开项的索引的话可以用 `indexOf`：https://jsfiddle.net/teq06m1v/ ，如果是想追踪整个数据源的索引的话建议把索引放在 row 中，每次展开直接就能获取到了
