### ISSUE TITLE
[Bug Report] form check, regardless of whether the check item has passed, the validate () method will call the check rule of all check items in full amount.

### ISSUE THREAD

**Issue by a346721573** [ElemeFE/element#11925]
### Element UI version
2.4.3

### OS/Browsers version
windows,mac;chrome 67.0.3396.99

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3423/](https://jsfiddle.net/mmx38qxw/3423/)

### Steps to reproduce
在做表单检验时，每次调用validate() 方法都会全量调用个个校验项的校验规则；
比如，每个校验项操作后，已通过规则，在调用validate()时，还会跑每个校验项的校验规则方法

### What is Expected?
表单校验通过后，不要始终重复调用校验项的校验规则

### What is actually happening?
表单已校验通过，始终会不停调用校验规则

**Comment by jikkai** [comment]
这里`trigger: blur`决定了每次失焦都会执行校验，因为不能保证每次失焦时校验规则不被动态改变。因此这个行为不能被算作是一个 bug。

**Comment by a346721573** [comment]
@jikkai 是否可以通过传入某个标识来保证校验规则不会改变？ 目前10多个校验唯一校验项每次保存就先请求10多次有点蠢

**Comment by jikkai** [comment]
验证时机可以考虑改成 change 然后做下防抖，感觉这样会比较合理点

**Comment by a346721573** [comment]
@jikkai 可是改用 change 也同样会在validate() 时调用哦；说到防抖目前是自己加的，可以的话，建议也加个debounce属性自己填时间，在trigger为change的时候生效，不然目前如果有多项校验只能每个都自己套一层。
