### ISSUE TITLE
When editable on [Bug Report] datepicker is false, it can still be written.

### ISSUE THREAD

**Issue by danny00lo** [ElemeFE/element#11934]
### Element UI version
2.4.3

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3451/](https://jsfiddle.net/mmx38qxw/3451/)

### Steps to reproduce
当editable为false的时候，理应选择了该日期和时间后 不能在文本框修改什么东西
但是仍然可以修改，且修改后，按确定会成功

### What is Expected?
不能修改选择后的时间

### What is actually happening?
仍然可以修改选择后的时间

**Comment by danny00lo** [comment]
editable 为false 的时候
可以手动选择上面的时间和日期，应该不能输入时间...
![123](https://user-images.githubusercontent.com/22129445/42501946-6f0d74ac-8467-11e8-95fe-e5ae0c6210e8.png)

**Comment by jikkai** [comment]
`editable`对于时间范围选择器来说，仅控制原输入框是否允许输入，而非 picker 的输入框，这个行为是经过设计且和 datetime picker 保持一致的。
