### ISSUE TITLE
[Bug Report] can't use editable attribute in datepicker.

### ISSUE THREAD

**Issue by danny00lo** [ElemeFE/element#11933]
### Element UI version
2.4.3

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3447/](https://jsfiddle.net/mmx38qxw/3447/)

### Steps to reproduce
不能使用editable属性

### What is Expected?
能使用

### What is actually happening?
实际无效果

**Comment by jikkai** [comment]
你的 demo 中设置了`false`，改为`true`后是可用的
https://jsfiddle.net/mmx38qxw/3448/

**Comment by danny00lo** [comment]
editable 为false 的时候
可以手动选择上面的时间和日期，不是应该不能输入...
而且...为什么把问题那么快关闭...
![123](https://user-images.githubusercontent.com/22129445/42501660-c7f039a2-8466-11e8-8513-4aef99a92c4e.png)
