### ISSUE TITLE
[Feature Request] Text Align: Is there a element-ui class or not?

### ISSUE THREAD

**Issue by biapar** [ElemeFE/element#11949]
### Existing Component
Yes

### Component Name
Text

### Description
Alignment

**Comment by ziyoung** [comment]
@biapar ElementUI doesn't provide it.

**Comment by leume** [comment]
@ziyoung when default classes like text-center, margin, padding, typography (size, weight, type), shadow, border and others will be added as component? if they will exist, sure you are much better than bootstrap:)
