### ISSUE TITLE
[Bug Report] $refs is undefined when components are inside dialog

### ISSUE THREAD

**Issue by dgroh** [ElemeFE/element#11942]
### Element UI version
2.4.3

### OS/Browsers version
Windows 10 / Chrome  67.0.3396.99

### Vue version
2.5.16

### Reproduction Link
https://jsfiddle.net/s4cj9ynv/

### Steps to reproduce
Create a dialog component and place an element inside with the **ref** attribute, then try to access the referenced component from the **open** event of the dialog.

### What is Expected?
The referenced components inside the dialog should not be undefined.

As per documentation, the **ref** should be accessible in the **open** event of the dialog component. Currently this is not happening:

> The content of Dialog is lazily rendered, which means the default slot is not rendered onto the DOM until it is firstly opened. Therefore, if you need to perform a DOM manipulation or access a component using ref, do it in the open event callback.

### What is actually happening?
The **ref** of the component inside the dialog is undefined.

**Comment by jikkai** [comment]
In this case, you should use [`vm.$nextTick`](https://vuejs.org/v2/api/#vm-nextTick)
https://jsfiddle.net/s4cj9ynv/1/

**Comment by dgroh** [comment]
Thanks. It would be nice to update this in the docs of dialog tho

**Comment by StoneCode5** [comment]
I get the same problem, check my code for half a hour. 
"It would be nice to update this in the docs of dialog tho"
