### ISSUE TITLE
[Bug Report] Select triggers validation when a form is empty

### ISSUE THREAD

**Issue by CreateClear** [ElemeFE/element#11941]
### Element UI version
2.4.3

### OS/Browsers version
windows 10 / chrome 63.0.3239.132

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/m7tnqyx4/2/](https://jsfiddle.net/m7tnqyx4/2/)

### Steps to reproduce
1. Select the active area,
2. reset it
3. triggering active area validation. 
4. in @2.4.2 & @2.4.3

### What is Expected?
no valid when i try to reset it

### What is actually happening?
there is a validation when i reset it

**Comment by ziyoung** [comment]
@CreateClear the validation rule of `region` is as follow
```js
[
    { required: true, message: '请选择活动区域', trigger: 'change' }
]
```
After you reset the form, the value of `region` changes. So`region` is validated. You can set `trigger` to `blur`. https://jsfiddle.net/zhiyang/m7tnqyx4/5/
