### ISSUE TITLE
[Bug Report] tree component "default-checked-keys" invalid in sometimes

### ISSUE THREAD

**Issue by SD-Gaming** [ElemeFE/element#11956]
### Element UI version
2.4.3

### OS/Browsers version
win10 / chrome 67.0.3396.99（正式版本） （64 位）

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/SD_Gaming/0ovwu95p/19/](https://jsfiddle.net/SD_Gaming/0ovwu95p/19/)

### Steps to reproduce
打开链接即可，观察默认选中状态

### What is Expected?
默认选中和默认展开按照传入的数组生效

### What is actually happening?
只有默认展开生效

**Comment by qinzitong** [comment]
确实有这个问题，我看了一下代码：
defaultCheckedKeys(newVal) {
        this.store.defaultCheckedKeys = newVal;
        this.store.**setDefaultCheckedKey**(newVal);
      },

      defaultExpandedKeys(newVal) {
        this.store.defaultExpandedKeys = newVal;
        this.store.**setDefaultExpandedKeys**(newVal);
      },
一个设置的是key，一个是keys
