### ISSUE TITLE
[Bug Report] el-scrollbar did not recalculation  onresize

### ISSUE THREAD

**Issue by LrCeacar** [ElemeFE/element#11958]
### Element UI version
2.4.3

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/eywraw8t/159620/](https://jsfiddle.net/eywraw8t/159620/)

### Steps to reproduce
1.resize browser or iframe to change el-scrollbar's height.
2.then can see scrollbar thumb did not recalculation.

I see the source code,and you only bind resize event on 'el-scrollbar__view' .But sometimes only 'el-scrollbar__wrap' resize.So i think it should be bind on 'el-scrollbar__wrap' too.
by the way, your official website has same problem because of it

### What is Expected?
scrollbar thumb recalculation when resize.

### What is actually happening?
scrollbar thumb did not recalculation when resize.

**Comment by ziyoung** [comment]
@LrCeacar `Scrollbar` is not exposed to the user. It's not designed for every case.

**Comment by nekdolan** [comment]
You can put a key on the el scrolbar element to force vue to redraw it like so:
`<el-scrollbar :noresize="false" :key="changedvalue">`
