### ISSUE TITLE
[Bug Report] [Bug Report] el-tree child node did not trigger a trigger

### ISSUE THREAD

**Issue by giserJason** [ElemeFE/element#11964]
### Element UI version
2.4.3

### OS/Browsers version
Win10/Chrome 版本 66.0.3359.181（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/giserJason/k6r9hson/5/](https://jsfiddle.net/giserJason/k6r9hson/5/)

### Steps to reproduce
Click on the root node directly and find that the child node is also checked, but no check-change event is triggered,But after expanding the parent, click on the parent, and the child below triggers a check-change event when selected

### What is Expected?
When the parent node is not expanded, the child node also needs to trigger a check-change event when the parent node is checked or unchecked

### What is actually happening?
When the parent node is not expanded, the child node won't trigger a check-change event when the parent node is checked or unchecked

**Comment by ziyoung** [comment]
@giserJason the child nodes don't render if their parent node is not expanded. You need to set `render-after-expand` to `false`. https://jsfiddle.net/zhiyang/k6r9hson/7/
