### ISSUE TITLE
Sort-change events should not be triggered when [Bug Report] forms are initialized.

### ISSUE THREAD

**Issue by DoveAz** [ElemeFE/element#11966]
### Element UI version
2.4.3

### OS/Browsers version
win10 chrome  67.0.3396.99

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3576/](https://jsfiddle.net/mmx38qxw/3576/)

### Steps to reproduce
no steps

### What is Expected?
按照文档的说明：当表格的排序条件发生变化的时候会触发该事件，
所以表格初始化的时候不应触发sort-change事件，

### What is actually happening?
现在表格初始化的时候也会触发sort-change事件

**Comment by avinograd0v** [comment]
met this bug too, set default-sort, and after table is loaded 'sort-change' event is emmited

**Comment by matthew-williamson-sd** [comment]
This is still an issue

**Comment by DoveAz** [comment]
> This is still an issue
It seems that the latest version has been solved.
