### ISSUE TITLE
[Bug Report] Button-group with dropdown bug

### ISSUE THREAD

**Issue by ingria** [ElemeFE/element#11963]
### Element UI version
2.4.3

### OS/Browsers version
Any

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/43x2mwoc/2/](https://jsfiddle.net/43x2mwoc/2/)

### Steps to reproduce
Create button group with 2 or more buttons. Put dropdown in any place of the row except the first.

### What is Expected?
![shot1](https://user-images.githubusercontent.com/2178368/42607094-cf5855b6-8589-11e8-8860-6311b6290065.png)

### What is actually happening?
![shot2](https://user-images.githubusercontent.com/2178368/42607103-d8dd09f6-8589-11e8-942a-a886b3efb305.png)

**Comment by jikkai** [comment]
ButtonGroup does not support nested dropdown. If must, there is a work-around way: https://jsfiddle.net/43x2mwoc/6/
