### ISSUE TITLE
[Bug Report] Tree setCurrentKey not highlighting tree node

### ISSUE THREAD

**Issue by dgroh** [ElemeFE/element#11960]
### Element UI version
2.4.3

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/x4hs2u73/](https://jsfiddle.net/x4hs2u73/)

### Steps to reproduce
Create a tree, select the first node with `setCurrentKey`.

### What is Expected?
I expect the tree node to be highlighted. The same behavior when a node is clicked.

### What is actually happening?
After setting `setCurrentKey`, the node **is not highlighted**. As per documentation, the node should be highlighted:

> setCurrentKey: set highlighted node by key, only works when node-key is assigned

**Comment by dgroh** [comment]
I'm closing this issue as I created a jsFiddle which works. This means something is wrong or our side.

https://jsfiddle.net/7fn9uv4h/

**Comment by whj768702** [comment]
highlight-current should be true.

**Comment by isSkyid** [comment]
我也遇到这个问题，暂时没有解决
