### ISSUE TITLE
[Feature Request] Allow customing collapse-item style (el-collapse-head)

### ISSUE THREAD

**Issue by threeid** [ElemeFE/element#11976]
### Existing Component
Yes

### Component Name
Collapse

### Description
Hi team,

It would be great if collapse-item can be custom, 
since it's style, especially el-collapse-head has fixed height.

```css
.el-collapse-head { 
  height: 48px;
  line-height: 48px;
...
}
```

If title slot has multiple item, it will look out of place.
https://jsfiddle.net/t0mrop1L/1/
![screenshot_20180713_074456](https://user-images.githubusercontent.com/37827220/42666675-c10973c2-8670-11e8-8d7a-d01fce7efbec.png)

And please allow the right arrow can be change its place to left, and change it to left arrow.

Many thanks,
threeid

**Comment by ziyoung** [comment]
@threeid you can overwrite the style of `collapse-head` if necessary.
