### ISSUE TITLE
[Feature Request] Table component should append on-change hook and prop "default-select-all"

### ISSUE THREAD

**Issue by NumerHero** [ElemeFE/element#11978]
### Existing Component
是

### Component Name
Table

### Description
Yes, It was very hard and trouble to handler when My Table component was very complex， Because of I want to render multiple tables with similar type dataes ，I just want default-select-all  but the component didnt support !!!  I didnt want to use  toggleRowSelection again！！！

**Comment by NumerHero** [comment]
Meanwhile  I  need a hook(on-change) When dataes change and tables component has been load !

**Comment by jikkai** [comment]
I created a PR to expose the `toggleAllSelection` method of Table. This may help you to solve your problem.

**Comment by NumerHero** [comment]
@jikkai  Nice Work Thx you
