### ISSUE TITLE
[Bug Report] Date picker in table header with render-header

### ISSUE THREAD

**Issue by VinceBassman** [ElemeFE/element#11974]
### Element UI version
2.4.1

### OS/Browsers version
Windows 7 / Chrome Version 67.0.3396.99 (Build officiel) (64 bits)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/49z1rjbg/39](https://jsfiddle.net/49z1rjbg/39)

### Steps to reproduce
1. click on date-picker range
2. Select a date range

### What is Expected?
It should print the range values (min/max) into the input field of date picker

### What is actually happening?
Date picker field remains empty after date selection. But if I open the date picker once again it set it with the previously selected values. How to bind with the input field?

**Comment by ziyoung** [comment]
@VinceBassman you need bind value to `DatePicker`. https://jsfiddle.net/zhiyang/49z1rjbg/44/
