### ISSUE TITLE
[Feature Request] Pagination paging can only listen to current-change events, hoping to increase events before the current page changes.

### ISSUE THREAD

**Issue by LIAOTOW** [ElemeFE/element#11988]
### Existing Component
是

### Component Name
Pagination 分页

### Description
标题：Pagination分页只能监听current-change事件，希望增加当前页改变之前的事件。
需求：分页设置 10页数之前的按钮设置高亮,10页数之后的置灰不可点击 
困难：希望在改变之前获取到要改变的页数，逻辑通过则执行下一步。无法设置分页li标签的class，如10页之前的按钮 class为‘red‘，其他分页li标签为‘green’

**Comment by ziyoung** [comment]
@LIAOTOW 你自己可以在 `current-change` 的回调函数中修改 `current-page`。

**Comment by LIAOTOW** [comment]
使用setTimeout绕过vue的检测？
if (val > 5) {
                    this.searchParam.page = 4;
                    setTimeout(() => {
                        this.searchParam.page = 5;
                    }, 0);
                } else {
                    this.searchParam.page = val;
                };

**Comment by LIAOTOW** [comment]
无法设置Pagination分页下的每个按钮className。如10页之前的按钮 class为‘red‘，其他分页li标签为‘green’
