### ISSUE TITLE
[Feature Request] why does el-tab-pane automatically add ID, pane-${paneName}? Is there a configuration that can cancel this default behavior?

### ISSUE THREAD

**Issue by tmyeahsing** [ElemeFE/element#11989]
### Existing Component
是

### Component Name
el-tabs

### Description
不能去掉id，也不能自定义id规则的话，就有可能会出现id冲突

**Comment by jikkai** [comment]
为了提升可访问性。详请参阅 https://www.w3.org/TR/WCAG20-TECHS/ARIA7.html
