### ISSUE TITLE
[Bug Report] el-input-number initial value 

### ISSUE THREAD

**Issue by wisdomsuper** [ElemeFE/element#11980]
### Element UI version
2.4.3

### OS/Browsers version
Win10/Chrome 66

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/guohao/project/editor/AQyJkr](https://codepen.io/guohao/project/editor/AQyJkr)

### Steps to reproduce
when a property is null, the value of el-input-number become zero automatically.

### What is Expected?
Initializes the el-input-numbe,The initial value is empty

### What is actually happening?
el-input-number value become to zero

**Comment by ziyoung** [comment]
@wisdomsuper you can set the initial value to `undefined`.
https://github.com/ElemeFE/element/blob/b18642f716aedae9e8de409b64c078bf510ba264/packages/input-number/src/input-number.vue#L107-L110
The initial value doesn't support `null` and `null` can be converted to 0.

**Comment by wisdomsuper** [comment]
It's not convenient，the data usually generated by JSON, I must change the json generation.

**Comment by kevrousso** [comment]
I am facing this issue as well, this really frustrating as the only solution - workaround provided here is to add watcher on the actual input value, which decreases dramatically the performances when typing in it.
It is also not convenient as my data comes from the server, and the server doesn't handle undefined values...
@Leopoldthecoder What do you think? Is there anything else we can do to bypass this?

**Comment by Bodom78** [comment]
I have the same issue. When empty, the number value is undefined and firestore throws an error as undefined is not a number.

The number input should always be a number, 0 should be it's default empty value.

Or you should at least have the option to make 0 the default/empty value.

**Comment by wacky6** [comment]
There is plan to rewrite input-number to support null/undefined zero. Resetting invalid value is inappropriate, and will cause problem when there are not `@input` event handler.

Reopen this issue.

**Comment by ginkosen** [comment]
god , null is valid for number ? why not provide default value on props ?

**Comment by t0milee** [comment]
I have found a workaround for this and it's to pass the initial value as `undefined`, seems to be working as expected in this issue. Btw, this is not working if I pass `null`.
