### ISSUE TITLE
[Bug Report] table custom column problem, slot-scope in V-IF when data handover is delayed.

### ISSUE THREAD

**Issue by Xavier0818** [ElemeFE/element#11984]
### Element UI version
2.3.9

### OS/Browsers version
win10/chrome 66

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3646/](https://jsfiddle.net/mmx38qxw/3646/)

### Steps to reproduce
1、初始化表格数据加载，列的props属性对应值正确
2、切换标签，列的props属性对应值部分没变
3、再次切换，列的props属性部分对应值为上次对应值数据

### What is Expected?
每次切换标签时，列的props值与数据对应

### What is actually happening?
每次切换标签时，列的props值与数据不对应，且错一步

**Comment by SnowZhangXl** [comment]
![image](https://user-images.githubusercontent.com/30932683/42698982-0ab1e172-86f2-11e8-9d48-9aebf566e0aa.png)
试试这样呢？

**Comment by jikkai** [comment]
Table 暂时不能完全支持根据`prop`动态更新，可以加个 `key` 强制刷新下组件：https://jsfiddle.net/mmx38qxw/3653/
