### ISSUE TITLE
[Feature Request] expects table components to add scrollPosition to props

### ISSUE THREAD

**Issue by pbnull** [ElemeFE/element#11992]
### Existing Component
是

### Component Name
el-table

### Description
需求：具有横向滚动的表格，希望可以通过props直接滚动到最后面。调试发现表格组件有个 State： scrollPosition，希望暴露到props里给开发者使用。

**Comment by mrin9** [comment]
> I do not understand Chinese, I am using google translate, so pardon me if my understanding is incorrect.

Well scrollToPosition will be really a nice feature, in an multiuser situation when a user is in 4th page and deletes an record, we refresh the data again, but the user is taken back to the first page. Instead it would be nice if I can bring him back to same page/position either by an method or a prop

**Comment by toddwong** [comment]
And when switch tabs, the scroll positions of inner tables will be lost
