### ISSUE TITLE
[Feature Request] render-header examples

### ISSUE THREAD

**Issue by bgadiel** [ElemeFE/element#11999]
### Existing Component
Yes

### Component Name
table

### Description
Hello,
I am trying to find examples on how to use render-header for table columns.
My goal is to print the label   SVG (with tooltip on hover) for each column. 
appreciate any help.
Thanks.

**Comment by jikkai** [comment]
Hi, issues is used to track bugs or feature requests, please do not abuse it.
You may find some solution here: https://github.com/ElemeFE/element/issues?utf8=%E2%9C%93&q=is%3Aissue+table+render-header
