### ISSUE TITLE
[Bug Report] input-el inside table with border-spacing gets effected

### ISSUE THREAD

**Issue by mrin9** [ElemeFE/element#11990]
### Element UI version
2.4.4

### OS/Browsers version
all

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3665/](https://jsfiddle.net/mmx38qxw/3665/)

### Steps to reproduce
Create an ```<el-input>``` with append/prepend slot inside a table.
change the table style ```border-spacing``` 
the styles gets leaked to the input element

### What is Expected?
styles of table should not get inherited by the input element

### What is actually happening?
styles of applied to table is effecting the the input element

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/blob/55c97e588c1331c0d96fcf9f27b75b56aa31be0d/packages/theme-chalk/src/input.scss#L222-L225
@mrin9 you need use scoped CSS. `Input` uses `inline-table` layout, so it inherits style from a table.

**Comment by mrin9** [comment]
It seems the solution offered is just a temporary work-around not a solution, 
In my opinion the frame-work should not force me to use scoped CSS.  
What if I like to re-use my styles elsewhere in the App.  

Instead I think its the frameworks responsibility to apply more specific CSS to its controls, which it is doing for many other controls

Is there anyway I can get this issue another consideration ? 
or should  I create a new issue stating in-line styles of ```<table>```  breaks styles for ```<el-input>```

**Comment by ziyoung** [comment]
@mrin9 It seems that scoped CSS is not a good solution. You can make a pull request.😀
