### ISSUE TITLE
关于支持版本的问题

### ISSUE THREAD

**Issue by ChaoYuLeo** [ElemeFE/element#12]
> Desktop UI elements for Vue.js 2.0

这是目前项目的介绍，所以此项目是只支持Vue 2.0吗？
因为考虑到目前Vue主流开发还是使用1.0，Vue2.0也还未发布正式版，项目团队是否有考虑开一个兼容1.0的分支。

**Comment by baiyaaaaa** [comment]
@ChaoYuLeo  element 也未正式发布，处于 RC 版本中，我们是面向 Vue 2.0 来开发的，没有兼容 1.0 的计划。
