### ISSUE TITLE
How to realize the following functions of [Feature Request] cascader cascading menu

### ISSUE THREAD

**Issue by wzwxwc** [ElemeFE/element#12000]
### Existing Component
是

### Component Name
cascader 

### Description
前提条件：
change-on-select属性设置为true
expand-trigger="hover"
cascader 级联菜单如何实现下述功能
鼠标hover的时候展开下级菜单
鼠标click的时候，直接选中你当前的node（支持非最后级别的node）
现在无法在中间node的时候，click来结束选择！！

**Comment by ziyoung** [comment]
@wzwxwc 是这样吗？https://jsfiddle.net/zhiyang/aswerfdc/
