### ISSUE TITLE
[Bug Report] In safari, the height of the input box line is problematic and does not match chrome

### ISSUE THREAD

**Issue by dengxiaozhen** [ElemeFE/element#12004]
### Element UI version
2.4.4

### OS/Browsers version
Mac OS 10.13.5 / Safari 11.1.1

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Major/0ze3dn4r/](https://jsfiddle.net/Major/0ze3dn4r/)

### Steps to reproduce
The height of the cursor does not match chrome when the input box is clicked

### What is Expected?
Line high hopes to be consistent with chrome

### What is actually happening?
Line height is not consistent with chrome

**Comment by bboy-xp** [comment]
我也遇到了同样的问题，求解

**Comment by jiangguangyao** [comment]
请问是怎么解决的，我看这重复的跳圈跳到这来了，但具体是怎么解决的呢？？？
