### ISSUE TITLE
el-input 無法觸發鍵盤事件 @keyup.enter

### ISSUE THREAD

**Issue by red010182** [ElemeFE/element#1200]
### ElementUI version
1.0.1

### OS/Browers version
OSX 10.11.6/Chrome 54

### Vue version
2.0.7

### Reproduction Link
https://jsfiddle.net/pytsao/4q6d44zh/1/

### Steps to reproduce
在input框與el-input框按下enter鍵

### What is Expected?
login()方法應該要被呼叫

### What is actually happening?
el-input框，無法trigger鍵盤enter事件，然而一般input可以

**Comment by QingWei-Li** [comment]
`@keyup.enter.native`
