### ISSUE TITLE
[Bug Report] Pagination paging, reset the value of current-page.sync, click the page again, do not go current-change method.

### ISSUE THREAD

**Issue by liuyingqq123** [ElemeFE/element#12019]
### Element UI version
2.4.4

### OS/Browsers version
win7

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
1. 页面初始化列表数据, 用Pagination分页.
2. 点击第二页, 列表数据切换到了第二页.
3. 点击页面的查询按钮, 查询数据后, 重新设置了current-page.sync, page-size和total, current-page.sync设置的是第一页.
4. 再点击第二页,不走current-change方法

### What is Expected?
current-change事件的方法被正确调用

### What is actually happening?
current-change事件的方法没有被正确调用

**Comment by Hxiaodou** [comment]
你看下这篇博客https://www.heiya123.com/article/5,里面讲解了怎么解决这个问题

**Comment by jikkai** [comment]
Duplicate of #11535

**Comment by superddr** [comment]
这绝逼是bug。。。
