### ISSUE TITLE
[Feature Request] Flag or function to select all Checked items ("checked" and "indeterminate")

### ISSUE THREAD

**Issue by morgangraphics** [ElemeFE/element#12011]
### Existing Component
Yes

### Component Name
Tree

### Description
Having separate functions to handle both checked and indeterminate is a bit difficult to merge because of the underlying behavior and redundancy of the children nodes. I needed a function that just grabbed all checked items, both checked and indeterminate. 

Perhaps a flag in the `getCheckedNodes` function would be easiest to handle
```
getCheckedNodes(leafOnly = false, includeIndeterminate=false) {
    const checkedNodes = [];
    const traverse = function(node) {
      const childNodes = node.root ? node.root.childNodes : node.childNodes;

      childNodes.forEach((child) => {
        if ((child.checked && (!leafOnly || (leafOnly && child.isLeaf))) || (child.checked && includeIndeterminate)) {
          checkedNodes.push(child.data);
        }
   
        traverse(child);
      });
    };

    traverse(this);

    return checkedNodes;
  }
```

**Comment by ziyoung** [comment]
@morgangraphics yes, the second param of `getCheckedNodes` is needed.
