### ISSUE TITLE
Can [Feature Request] add the list / group of cards and increase the drag and drop attributes of cards?

### ISSUE THREAD

**Issue by fudax** [ElemeFE/element#12012]
### Existing Component
是

### Component Name
el-card

### Description
参考阿里飞冰物料库中的board-list：
https://alibaba.github.io/ice/block/board-list?type=react

**Comment by jikkai** [comment]
这是一个业务级组件，我们暂时没有计划实现它。

**Comment by fudax** [comment]
好吧，我自己实现吧
