### ISSUE TITLE
[Bug Report] tree nodes updated but source data not update

### ISSUE THREAD

**Issue by yansenlei** [ElemeFE/element#12015]
### Element UI version
2.3.4

### OS/Browsers version
mac / chrome 67.0.3396.99

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/leiys/pn429zeo/4/](https://jsfiddle.net/leiys/pn429zeo/4/)

### Steps to reproduce
append,remove 改变节点数据会触发视图更新，同时watch 可以监听到源数据的变化。如果是update，改变了该节点数据视图变化而源数据没有改变。

### What is Expected?
修改节点内容，可以触发源数据更新

### What is actually happening?
修改节点内容，没有触发源数据更新

**Comment by ziyoung** [comment]
@yansenlei **没有触发源数据更新** 什么意思？

**Comment by yansenlei** [comment]
@ziyoung 
在[例子中](https://jsfiddle.net/leiys/pn429zeo/4/)，append，remove不仅会触发视图更新，实际数据也会有变动，我尝试update某个节点数据，视图会发生变化，但是 `console.log`打印中可以看出节点数据没有变动，是需要有什么操作来触发到数据更新吗？

**Comment by ziyoung** [comment]
@yansenlei 直接修改 `node.data` 中的某些字段，而不是给 `node.data` 重新赋值。
```js
node.data.label = 'new label';
```
https://jsfiddle.net/zhiyang/pn429zeo/6/

**Comment by yansenlei** [comment]
@ziyoung 
好的，感谢。
