### ISSUE TITLE
select下拉菜单无法调整高度？

### ISSUE THREAD

**Issue by LittleChild** [ElemeFE/element#1202]
因为input提供了size属性，我用了`size="large"`,在同一个页面即有input又有select的时候，select明显会小很多。目前我的处理办法是hack掉select样式中的高度属性`.el-input__inner {height: 42px;}`,有什么更好的办法吗？

**Comment by Leopoldthecoder** [comment]
目前 Select 并没有提供 `size` 这个属性，只能通过 CSS 覆盖。后面会提供相关接口。

**Comment by LittleChild** [comment]
知道了，谢谢。
