### ISSUE TITLE
The [Feature Request] cascade selector does not get the selected object.

### ISSUE THREAD

**Issue by shengrongchun** [ElemeFE/element#12029]
### Existing Component
是

### Component Name
级联选择器

### Description
级联只能通过value获取到一个数组值，但我想获取我选中的对象，而不仅仅是对象里面的value值，还有options的label和value是否可以动态设置呢？这样会更灵活

**Comment by jikkai** [comment]
参照文档 [`props ` 属性](http://element-cn.eleme.io/#/zh-CN/component/cascader#props) 和[示例](http://element-cn.eleme.io/#/zh-CN/component/cascader#dong-tai-jia-zai-ci-ji-xuan-xiang)
