### ISSUE TITLE
[Feature Request] TimePicker > disable time

### ISSUE THREAD

**Issue by flamner** [ElemeFE/element#12027]
### Existing Component
Yes

### Component Name
TimePicker

### Description
Missing one option, the disable time, should works like disabledDate in DatePicker

**Comment by ziyoung** [comment]
@flamner you can limit the time range by specifying `selectableRange`. http://element.eleme.io/#/en-US/component/time-picker#arbitrary-time-picker

**Comment by flamner** [comment]
@ziyoung Yes, I know, but I tried to make a reservation system, set range from 8:00 to 24:00 and set steps every 30 minutes. So, as you suggested, using selectableRange is too complicated solution to this, so much easier will be add  new option like disabledDate in date picker :/
