### ISSUE TITLE
The change event of [Bug Report] Carousel cannot be invoked.

### ISSUE THREAD

**Issue by dmh19900611** [ElemeFE/element#12022]
### Element UI version
2.4.4

### OS/Browsers version
window/mac chrome

### Vue version
2.4.4

### Reproduction Link
[http://jsfiddle.net](http://jsfiddle.net)

### Steps to reproduce
template:
  <el-carousel ref="carousel" :interval="12000" arrow="always" :height="height" @change="carouselChanged">
js:
      carouselChanged: function (index, oindex) {
}
不能调用。

### What is Expected?
期待调用carouselChanged

### What is actually happening?
不调用carouselChanged

**Comment by dmh19900611** [comment]
js内函数大小写被自动修改。实际首字母非大写。

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
