### ISSUE TITLE
[Bug Report] Placeholder for el-input in render-header not working

### ISSUE THREAD

**Issue by VinceBassman** [ElemeFE/element#12032]
### Element UI version
2.4.1

### OS/Browsers version
Chrome Version 67.0.3396.99 (Build officiel) (64 bits)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/49z1rjbg/47](https://jsfiddle.net/49z1rjbg/47)

### Steps to reproduce
Nothing, just look at the input fields

### What is Expected?
Placeholder should be present in all input fields in table header

### What is actually happening?
All input fields in the table header are empty, no text is shown...

**Comment by jikkai** [comment]
https://jsfiddle.net/49z1rjbg/48/
