### ISSUE TITLE
Can [Feature Request] set the verification result of el-form by function?

### ISSUE THREAD

**Issue by suzitao** [ElemeFE/element#12036]
### Existing Component
是

### Component Name
el-form

### Description
我的需求是这样的，当表单验证正确后请求后台登陆接口，如后台返回异常结果（如：密码错误、用户不存在、其它系统异常信息），将结果回填到form的验证信息中。这应该是个通用需求。
目前我尝试通过Form-Item的error属性来满足这个需求，但发现存在问题，当连续二次登陆错误时，errMessage不会显示出来（表单显示验证正确）

<el-form-item prop="password" ref="password" error="loginDialog.errMessage">
     <el-input v-model="loginDialog.editForm.password" placeholder="请输入密码"></el-input>
</el-form-item>

async function login() {
    await this.$refs.loginForm.validate()
    try {
        await httpPost('api/user/login', date)
    } catch (err) {
        this.loginDialog.errMessage = err.message
    }
}

**Comment by jikkai** [comment]
请参考 [async-validator](https://github.com/yiminghe/async-validator) 文档，可以通过类似这样规则处理
```javascript
field: [
    {type: "string", required: true},
    {validator(rule, value, callback, source, options) {
      // 处理远程校验
      const errors = execRemoteValidator();
      callback(errors);
    }}
  ]
```
