### ISSUE TITLE
[Bug Report] Yarn build fails with babel-plugin-component

### ISSUE THREAD

**Issue by lyzs90** [ElemeFE/element#12033]
### Element UI version
2.4.4

### OS/Browsers version
Windows 10 / 67.0.3396.99

### Vue version
2.5.16

### Reproduction Link
[https://github.com/lyzs90/element-ui-bug-repro](https://github.com/lyzs90/element-ui-bug-repro)

### Steps to reproduce
Follow on demand import of Element components guide (http://element.eleme.io/#/en-US/component/quickstart) then run yarn build

### What is Expected?
Build should be successful

### What is actually happening?
Build fails with error: Plugin/Preset files are not allowed to export objects, only functions.

**Comment by jikkai** [comment]
babel.config.js
```diff
module.exports = {
- presets: ['@vue/app', ['es2015', { modules: false }]],
+ presets: ['@vue/app'],
  plugins: [
    [
      'component',
      {
        libraryName: 'element-ui',
        styleLibraryName: 'theme-chalk'
      }
    ]
  ]
};
```

**Comment by jjmontgo** [comment]
This would be great to mention in the Quick Start.
