### ISSUE TITLE
[Bug Report] datetimerange scrolling

### ISSUE THREAD

**Issue by xiaoming062** [ElemeFE/element#12039]
### Element UI version
2.4.4

### OS/Browsers version
谷歌浏览器，360极速模式

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/z0ukaygt/](https://jsfiddle.net/z0ukaygt/)

### Steps to reproduce
把type改成datetimerange，选择时间的时候滚动，滚动一下滚动了三个时间点，360极速模式无法点击某个时间点进行选中

### What is Expected?
滚动一下只滚动一个时间点，360极速模式可以点击选中

### What is actually happening?
把type改成datetimerange，选择时间的时候滚动，滚动一下滚动了三个时间点，360极速模式无法点击某个时间点进行选中

**Comment by jikkai** [comment]
Fixed in #12415
