### ISSUE TITLE
[Feature Request] Allow drop outside of el-tree element

### ISSUE THREAD

**Issue by martincarles** [ElemeFE/element#12046]
### Existing Component
Yes

### Component Name
el-tree

### Description
I am trying to export information from one el-tree to a drop zone elsewhere in my app. 
I am very happy with the tree as it is but I'm unable to drop one leaf of my tree outside of the el-tree itself.
See fiddle below: 
https://jsfiddle.net/martincarles/ey83790u/62/

What I'd like to do is cancel the drop within the tree itself because as soon as my mouse leaves the tree element, it records the last/exit position of my pointer and then, on drop, use this position instead of the actual pointer position.

Thanks in advance for your comments on this potential new feature or for your suggestions.

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
