### ISSUE TITLE
[Bug Report] [Bug Report] pagination can't go to prev page or first page when total >= 0 && current-page-size > 0

### ISSUE THREAD

**Issue by bq-hentai** [ElemeFE/element#12049]
### Element UI version
2.4.0

### OS/Browsers version
win7/Chrome62

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/anon/pen/NzJoGv](https://codepen.io/anon/pen/NzJoGv)

### Steps to reproduce
Click prev button, no `current-change` event emitted, so no alert.

[ref](https://github.com/ElemeFE/element/issues/11517)

### What is Expected?
emit `current-change`.

### What is actually happening?
none

**Comment by bq-hentai** [comment]
这个[issue](https://github.com/ElemeFE/element/issues/11517) 里提到，current-change只响应用户的交互，但是这种经过validate之后，代码层面的变动未触发。那这种情况，用户现在怎么更好的处理比较好呢。基于ElPagination搞一个高阶组件达到最大化的复用？

**Comment by wacky6** [comment]
直接 watch `currentPage`，`handleCurrentChange` 放到 watch `currentPage` 的处理函数里面去

**Comment by bq-hentai** [comment]
@wacky6 i.e. v-bind.sync

看起来不错。
