### ISSUE TITLE
The [Feature Request] el-tree component implements the tree list refresh after clicking the button outside the tree.

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#12043]
### Existing Component
是

### Component Name
el-tree

### Description
希望官方能够提供点击树状节点外的按钮，点击按钮请求ajax，把返回的数据替换原来的节点树内容。
源码：
![image](https://img-ask.csdn.net/upload/201806/27/1530082476_338930.png)
![image](https://user-images.githubusercontent.com/8147202/42868903-15317bb4-8aa6-11e8-9f4f-e6192fa7090a.png)

**Comment by ziyoung** [comment]
@fengyun2 这种需求也太小众了吧。我们暂时没有计划去实现该功能。

**Comment by fengyun2** [comment]
已解决

**Comment by LoLDragon** [comment]
@fengyun2 朋友，请问一下 你这个问题是怎么解决的啊？可以给我提供一个思路吗？万分感谢！
