### ISSUE TITLE
[Bug Report] when you set Dialog to modal:false, you can't click on the elements behind Dialog.

### ISSUE THREAD

**Issue by linziguan** [ElemeFE/element#12042]
### Element UI version
2.4.4

### OS/Browsers version
win10/chrome 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3835/](https://jsfiddle.net/mmx38qxw/3835/)

### Steps to reproduce
当只需要一个悬浮框时，将Dialog组件的modal设为了false，但点击时还是会点到遮罩层上。

### What is Expected?
当modal:false时，点击界面元素，可以不被遮罩层遮挡。

### What is actually happening?
当只需要一个悬浮框时，将Dialog组件的modal设为了false，但点击时还是会点到遮罩层上。原来界面上的元素都被遮罩层遮挡了。

**Comment by jikkai** [comment]
`modal` 只负责遮罩层的渲染与否，与本来就占据高层级的 Dialog 容器无关；加之 Dialog 打开时应当预期用户把操作 foucs 在 Dialog 上，否则会出现非常混乱的交互，因此即使 `modal` 设置为 `false`，上层仍旧有 Dialog 容器的遮罩，这是经过设计的。

**Comment by jikkai** [comment]
Dialog 的 `width` 设置 `100%`，然后手动 hack 下 `el-dialog__wrapper` 的宽度和位置吧。这种交互其实很糟糕，并不是很推荐这样使用 🤣

**Comment by jKatherine** [comment]
“那有没有办法可以利用原有的element组件，在弹出窗口之余，还能点击原来界面的元素呢？比如说我有A、B，两个按钮。点击A按钮后，弹出Dialog，但不关闭，还想点击B按钮，弹出别一个窗口。”楼主有没有解决这个问题呢？遇到类似的

**Comment by huangshiqiang** [comment]
Drawer 也一样不支持，好郁闷！窗口非模态，可以点击后面的内容是一个非常常见的需求。好多功能都是这么设计的，可以提高用户体验。楼主解决了吗？

**Comment by huangshiqiang** [comment]
> `modal` 只负责遮罩层的渲染与否，与本来就占据高层级的 Dialog 容器无关；加之 Dialog 打开时应当预期用户把操作 foucs 在 Dialog 上，否则会出现非常混乱的交互，因此即使 `modal` 设置为 `false`，上层仍旧有 Dialog 容器的遮罩，这是经过设计的。
> 
> PS：如果希望在 `model="false"` 的情况下禁用点击关闭，可以同时设置 `close-on-click-modal="false"`

Drawer 有close-on-click-modal能加上这个属性吗？侧边栏非模态，可以点击页面元素是非常常见的需求哦。比如希望点击不同的表格行数据，查看明细信息。希望侧边栏可以不关闭。

**Comment by StoneStone11** [comment]
5年过去了，还是不支持
