### ISSUE TITLE
[Feature Request] code formatting

### ISSUE THREAD

**Issue by yanlibo2013** [ElemeFE/element#12040]
### Existing Component
否

### Component Name
vue

### Description
element 源码格式风格，具体是怎样配置的，多谢

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
