### ISSUE TITLE
[Bug Report] el-tabs v-bind not change but tab changed

### ISSUE THREAD

**Issue by korewayume** [ElemeFE/element#12052]
### Element UI version
2.4.4

### OS/Browsers version
MacOS Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/8yzp5kt3/3/](https://jsfiddle.net/8yzp5kt3/3/)

### Steps to reproduce
在JSFiddle中打开el-tabs文档中的第一个例子，把`el-tabs`的`v-model`改成`:value`
然后点击tab，发现bind value没有变化，但是tab切换了

### What is Expected?
active tab 应该与 value 绑定的 activeName 一致

### What is actually happening?
active tab 与 value 绑定的 activeName 不一致

**Comment by ziyoung** [comment]
@korewayume 建议先熟悉一下 Vue，了解一下 `v-model` 与 `value` 区别。https://cn.vuejs.org/v2/guide/components.html#%E5%9C%A8%E7%BB%84%E4%BB%B6%E4%B8%8A%E4%BD%BF%E7%94%A8-v-model

**Comment by korewayume** [comment]
你看看https://github.com/ElemeFE/element/blob/f23e45b4040b2fb8ce6b49506e596ad6897edebf/packages/tabs/src/tabs.vue#L73
73 74行，先修改了currentName再emit input，而没有理会此时input消息是否改变了绑定value的值

**Comment by korewayume** [comment]
好吧我的需求用`before-leave`可以实现，不过既然value不是响应式的，那么希望能明确弃用value，以免给用户造成误解

**Comment by JUST-Limbo** [comment]
> 我知道v-model与value的区别，我现在就是只想用v-bind:value绑定一个值，为什么绑定值没变，但是tab切换了，我并没有处理@input消息

我也赞同这个观点，从currentName的逻辑来看，这实际上并不是严谨的双向绑定。
