### ISSUE TITLE
The [Bug Report] el-tree component opens the lazy and check-strictly options. If the default-checked-keys is not empty, the state of the father child node or the correlation between them.

### ISSUE THREAD

**Issue by Jack-X-Yang** [ElemeFE/element#12056]
### Element UI version
2.4.4

### OS/Browsers version
mac 10.13.5 / Chrome 67

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3898/](https://jsfiddle.net/mmx38qxw/3898/)

### Steps to reproduce
el-tree 组件开启 lazy 和 check-strictly 选项，default-checked-keys 不为空。如果父结点未被选中，子结点在 default-checked-keys 中，展开父结点，父结点会被选中。

### What is Expected?
父子结点的选中状态不关联

### What is actually happening?
父子结点的选中状态关联

**Comment by Jack-X-Yang** [comment]
解决方法：

https://github.com/ElemeFE/element/blob/dev/packages/tree/src/model/node.js#L318

```js
reInitChecked(this);
```
改为
```js
if (!this.store.checkStrictly) {
  reInitChecked(this);
}
```

**Comment by ziyoung** [comment]
@Jack-X-Yang 链接打开后，无法正常渲染。重新编辑了一下：https://jsfiddle.net/zhiyang/mmx38qxw/3931/
欢迎来提 pr。
