### ISSUE TITLE
[Feature Request] only gets the parent node when all child nodes are selected.

### ISSUE THREAD

**Issue by yuanfang008** [ElemeFE/element#12051]
### Existing Component
是

### Component Name
tree

### Description
是否可以在 getCheckedNodes 时 增加一个 parentOnly 属性，当子节点全部选中时，只获取父节点（会存在叶子节点过多的情况）

**Comment by ziyoung** [comment]
@yuanfang008 你自己可以对 `getCheckedNodes` 的返回值过滤一下，即可实现该功能。
