### ISSUE TITLE
[Feature Request] Table header click optional behaviour

### ISSUE THREAD

**Issue by wolf991** [ElemeFE/element#12055]
### Existing Component
Yes

### Component Name
Table

### Description
Clicking on the column header sorts the table if column is sortable.
Clicking on the column header filters the table if column is filterable.
But if a column is sortable and filterable clicking on the column header does nothing.
It would be nice to have an option to choose what happens when clicking the header.

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.

**Comment by shivamkumar110** [comment]
It is really frustrating when you have rendered an input-box inside table header. And table sorts on its focus. -_- . @jikkai 
At least fix that.
