### ISSUE TITLE
[Bug Report] before-upload upload callback problem

### ISSUE THREAD

**Issue by huan0118** [ElemeFE/element#12053]
### Element UI version
2.3.4

### OS/Browsers version
Chrome win10

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/mmx38qxw/3954/

### Steps to reproduce
在before-upload的回调函数里面返回一个Promise，当一个上传的队列中有一个读取文件失败 就会影响其他图片，比如我有一张正常图片，一张错误图片（通过直接修改后缀名），这两张同时上传导致正常图片无法上传；
并在源码这个地方
handleProgress: function(e, t) {
                    var i = this.getFile(t);
                    this.onProgress(e, i, this.uploadFiles),
                    i.status = "uploading",（出错）
                    i.percentage = e.percent || 0
                },

### What is Expected?
希望当reject（）时其余图片不受影响

### What is actually happening?
如果有两张一张正常一张不正常就会有问题！但是在多个正常图片中含有一张怀图的话；比如十张中包含一张怀图有八张上传成功

**Comment by ziyoung** [comment]
@huan0118 无法重现的。检查一下代码，看看例子能不能精简一下，也方便我们排查问题。

**Comment by huan0118** [comment]
@ziyoung 能否提供一个简单的上传接口 我这边是公司oss的上传借口不方便暴露key等参数

**Comment by jikkai** [comment]
@huan0118 你提供的 demo 里同时上传多张图被 reject 的原因是服务端 429。
我这里测试下来也没有出现你描述的情况。issues 先关了，如果能稳定复现问题欢迎随时 reopen
