### ISSUE TITLE
[Feature Request] input multivalued support

### ISSUE THREAD

**Issue by tangmingming** [ElemeFE/element#12050]
### Existing Component
是

### Component Name
input输入框

### Description
希望Input输入框可以增加对多值输入支持 在很多场景下input输入为一个列表  有的人使用逗号来分割   如果能像select多选一样就更完美了  但select创建条目多选不支持重复

**Comment by ziyoung** [comment]
@tangmingming 针对你们的业务，可以对 Input 组件进行一下封装。我们暂时没有计划去是实现该功能。

**Comment by tangmingming** [comment]
呃。。。好吧  封装了一个  但是灵活性少了很多   感谢你们的辛勤付出
