### ISSUE TITLE
[Bug Report] el-tabs component uses for to loop el-tab-pane, and when the data order changes, the order of tab is unchanged.

### ISSUE THREAD

**Issue by tinder1024** [ElemeFE/element#12063]
### Element UI version
2.4.4

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/3928/](https://jsfiddle.net/mmx38qxw/3928/)

### Steps to reproduce
el-tabs组件，用for循环el-tab-pane，当数据顺序发生变化时，可见tab的顺序没有变化

### What is Expected?
tab标签顺序改变

### What is actually happening?
tab标签的顺序没有改变

**Comment by jikkai** [comment]
加个 `key` 刷新下组件：https://jsfiddle.net/mmx38qxw/3932/
