### ISSUE TITLE
[Feature Request] Table combined sorting -- Table Multi-Columns Sort

### ISSUE THREAD

**Issue by liaotup** [ElemeFE/element#12069]
### Existing Component
是

### Component Name
Table

### Description
Table组件现在不支持组合排序，点击第一个排序按钮，再点击第二个排序按钮，点完第二个排序后第一个排序状态就被去掉了。
The table component does not support multi-columns sort，mean i can not control more than 2 column sort status same time。

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.
