### ISSUE TITLE
[Bug Report] Screen flicker with dialog and carousel

### ISSUE THREAD

**Issue by 909173** [ElemeFE/element#12064]
### Element UI version
2.4.4

### OS/Browsers version
Win10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/xya4k68r/15/](https://jsfiddle.net/xya4k68r/15/)

### Steps to reproduce
I put a carousel in the dialog.
The carousel is controlled only by the buttons prepared in the dialog.
If the carousel is showing pages other than the first page, closing the dialog will return the first page of the carousel.
When you open the dialog again, the carousel can see the process of returning the page for a moment.
Once the carousel returns the page, you will see it every time you open a dialog regardless of the Carousel page.

### What is Expected?
When opening a dialog, animation that returns carousel can not be inserted

### What is actually happening?
When opening the dialog, the animation returning the carousel appears

**Comment by lucyonegit** [comment]
I have the same problem!!!
