### ISSUE TITLE
[Bug Report] table: filter cannot delay assignment

### ISSUE THREAD

**Issue by xiongsongsong** [ElemeFE/element#12079]
### Element UI version
2.4.4

### OS/Browsers version
MacOS Chrome 67

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/ja93zuLe/4/](https://jsfiddle.net/ja93zuLe/4/)

### Steps to reproduce
1. 点击日期，无法展现筛选界面。
2. 将Element UI切换到2.4.3，点击日期可以展现筛选界面。

### What is Expected?
能够正常筛选日期列。

### What is actually happening?
不能筛选日期列。

**Comment by jikkai** [comment]
Duplicate of #12007
