### ISSUE TITLE
[Feature Request] The select module is always in focus after the after

### ISSUE THREAD

**Issue by caokunyu** [ElemeFE/element#12073]
### Existing Component
否

### Component Name
el-select 

### Description
After the first selection on the ios device, the selection module is always in focus and then clicks the input cannot open option
··· javascript

  <el-select v-model="value" :placeholder="placeholder"  @focus="getedFocus"  @visible-change="switchFocus">

    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value">
    </el-option>

  </el-select>

<script>

    export default {
        data() {
            return {
                temporaryDom: null
            }
        },
        props: ['value', 'placeholder', 'options'],
        methods: {
            change: function(val) {
                this.$emit('input', val);
            },
            getedFocus(e) {
                this.temporaryDom = e.target;
            },
            switchFocus(e) {
                if( e === false && this.temporaryDom) {
                    this.temporaryDom.blur()
                }
            }
        },
    }
</script>
```

<!-- generated by https://eleme-issue.surge.sh DO NOT REMOVE -->

**Comment by caokunyu** [comment]
After the first selection on the ios device, the selection module is always in focus and then clicks the input cannot open option

**Comment by ziyoung** [comment]
@caokunyu 如果是 bug 的话，请新建例子说明问题。
