### ISSUE TITLE
The validate information of the [Bug Report] Form form can not be inserted into html/jsx.

### ISSUE THREAD

**Issue by my9074** [ElemeFE/element#12075]
### Element UI version
2.4.4

### OS/Browsers version
chrome 67 

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/2xfodyrh/2/](https://jsfiddle.net/2xfodyrh/2/)

### Steps to reproduce
-

### What is Expected?
form 的表单验证依赖的 https://github.com/yiminghe/async-validator 的库是支持在 message 中写jsx的。https://github.com/yiminghe/async-validator#messages 。

### What is actually happening?
 现在有需求在form 验证信息中加入例如 a 标签供用户点击，但是现在在 message 中无法插入类似 
{name: {type: "string", required: true, message: <b>Name is required</b>}} 这样的结构

**Comment by merryfox** [comment]
我们也有类似的需求，需要在 form 的验证信息中加一些 html

**Comment by ziyoung** [comment]
如果使用者想使用 jsx 作为验证信息的话，那得安装这个插架了 [babel-plugin-transform-vue-jsx](https://www.npmjs.com/package/babel-plugin-transform-vue-jsx)，并且版本号要大于 3.4.0。

**Comment by ziyoung** [comment]
@my9074 Form 目前不具备该功能。即便是我们提供了这个功能，如果用户要使用 jsx 做验证信息的话，还需要自己安装  babel-plugin-transform-vue-jsx 插件。

**Comment by my9074** [comment]
@ziyoung  目前我装了 babel-plugin-transform-vue-jsx，也不生效。
![image](https://user-images.githubusercontent.com/4555635/43193689-440e7044-9033-11e8-91ff-5040c5d6c9b9.png)
我觉得这种场景还是挺常见的。
![image](https://user-images.githubusercontent.com/4555635/43193724-5aa1f740-9033-11e8-82f6-9398fcb0d72f.png)

**Comment by jikkai** [comment]
@my9074 我们在评估是否在今后的版本中支持此功能，请保持关注。
![image](https://user-images.githubusercontent.com/14025786/43194505-1469a83e-9035-11e8-9348-40d61337fb03.png)

**Comment by my9074** [comment]
@jikkai  好的~

**Comment by my9074** [comment]
@jikkai  请问这个 Feature 有进展吗？

**Comment by imshenshen** [comment]
这么通用的需求居然不支持，目前message传入vNode的话，form-item会报错

**Comment by JuneDeng2014** [comment]
强烈需要这个功能。
