### ISSUE TITLE
[Bug Report] Notification component cyclic invocation, overlap problem

### ISSUE THREAD

**Issue by zhengel** [ElemeFE/element#12087]
### Element UI version
2.4.4

### OS/Browsers version
win10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/4mtLj8vw/](https://jsfiddle.net/4mtLj8vw/)

### Steps to reproduce
点击"不会自动关闭"按钮,循环输出Notification标签重叠在一起

### What is Expected?
平铺开

### What is actually happening?
重叠

**Comment by jikkai** [comment]
Duplicate of #7389
