### ISSUE TITLE
[Bug Report] Uploader has not changed: the object of file-list binding.

### ISSUE THREAD

**Issue by git8023** [ElemeFE/element#12080]
### Element UI version
2.4.4

### OS/Browsers version
Win10 / Google Chrome 67.0.3396.99（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4033/](https://jsfiddle.net/mmx38qxw/4033/)

### Steps to reproduce
上传任意文件
-------------------------
Vue version: 3.0.0-rc.3  
NodeJs version: 5.6.0  
  
elementUI 官方示例:  
http://element-cn.eleme.io/#/zh-CN/component/upload  
https://jsfiddle.net/api/post/library/pure/  

### What is Expected?
同步更新被引用对象

### What is actually happening?
被引用无变化

**Comment by git8023** [comment]
https://jsfiddle.net/mmx38qxw/4034/

**Comment by jikkai** [comment]
`fileList` 是由用户传入的 props，父子传参遵循单项数据流，具体请参照 Vue 的[官方文档](https://cn.vuejs.org/v2/guide/components-props.html#%E5%8D%95%E5%90%91%E6%95%B0%E6%8D%AE%E6%B5%81)
