### ISSUE TITLE
[Feature Request] make a mark on some special dates

### ISSUE THREAD

**Issue by KeepLifeCoding** [ElemeFE/element#12099]
### Existing Component
Yes

### Component Name
DatePicker

### Description
In some case, we may want to mark some special dates like the holidays,deadlines .etc on the datepicker,Would you consider adding this?

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.

**Comment by che5ya** [comment]
I recently wanted to add a national holiday feature to 'date-picker' while developing a specific feature,
but I had no choice but to treat it as 'disabledDate'.

Still not interested in this matter?
