### ISSUE TITLE
When [Feature Request] tree increases click label, checkbox is selected.

### ISSUE THREAD

**Issue by qinzitong** [ElemeFE/element#12092]
### Existing Component
是

### Component Name
el-tree

### Description
el-tree 组件在show-checkbox的时候，希望点击label的时候checkbox被选中

**Comment by jikkai** [comment]
这样做就不能展开 tree 的子节点了。如果为了增大 checkbox 的交互区域而减少字节点展开的点击区域的话，对于 tree 这样的一个组件来说就是舍本求末得不偿失了。因此在没有更好的解决方案前不会实现该功能。

**Comment by qinzitong** [comment]
这样为啥不能展开子节点呢？
