### ISSUE TITLE
[Bug Report] When fixed in a column of a table, the focus method with input is invalid

### ISSUE THREAD

**Issue by yanzhimin10** [ElemeFE/element#12093]
### Element UI version
2.4.4

### OS/Browsers version
Chrome 67.0.3396.99

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4057/](https://jsfiddle.net/mmx38qxw/4057/)

### Steps to reproduce
点击表格中的"Click here"

### What is Expected?
单元格中出现Input，并且处于focused状态

### What is actually happening?
没有处于focused状态

**Comment by ziyoung** [comment]
@yanzhimin10 `cell-click` 事件都没有触发，你写的回调函数没有执行。或许你需要监听 `selection-change` 事件。

**Comment by yanzhimin10** [comment]
@ziyoung 样例可能有点让人误解，需要点击的是Tex下方的单元格，而不是多选框

**Comment by jikkai** [comment]
改用 `v-show` 试试：https://jsfiddle.net/mmx38qxw/4060/

**Comment by yanzhimin10** [comment]
@jikkai Thanks
