### ISSUE TITLE
Table header 不同步

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#121]
### ElementUI version

 1.0.0-rc.4 
### Vue version
2.0.0-rc.5
### What is actually happening?
 
![image](https://cloud.githubusercontent.com/assets/6311122/18735680/4ca70b68-80b2-11e6-8f8b-e53094876c1e.png)

**Comment by QingWei-Li** [comment]
Vue 升级到 rc6 呢

**Comment by spademan** [comment]
vue-template-compiler  和vue  升级到 rc.6就正常了 ~~

**Comment by spademan** [comment]
table头部全部都 变成固定的了 vue.rc6  element rc.4

**Comment by QingWei-Li** [comment]
什么意思？

**Comment by spademan** [comment]
就是 更新过后 ，
table-header部分 我没有设置成固定的 都变成固定的了

**Comment by QingWei-Li** [comment]
我的项目里用的是正常的哦，并没有固定

**Comment by spademan** [comment]
我的项目会出现 并且 我尝试在 docs（我fork你们的项目）里面 跑 也会出现

**Comment by spademan** [comment]
![image](https://cloud.githubusercontent.com/assets/6311122/18739649/a74e55c4-80d7-11e6-953c-0c6851a71662.png)

![image](https://cloud.githubusercontent.com/assets/6311122/18739643/9f6dd33e-80d7-11e6-9243-743d1b634164.png)
