### ISSUE TITLE
The el-main width in the [Bug Report] el-container component keeps 100px on IE10.

### ISSUE THREAD

**Issue by snowzijun** [ElemeFE/element#12103]
### Element UI version
2.4.4

### OS/Browsers version
IE10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/zijun/0sewrfq5/](https://jsfiddle.net/zijun/0sewrfq5/)

### Steps to reproduce
在IE10上面打开 http://element-cn.eleme.io/#/zh-CN/component/container 即可看到问题

### What is Expected?
宽度应该充满父容器

### What is actually happening?
宽度一致显示100px左右

**Comment by jikkai** [comment]
手头没有 pc 机，方便的话能提供更详细一点的信息和截图给我们吗

**Comment by ziyoung** [comment]
@snowzijun 要是样式的问题，你这边能否尝试修复一下呢？欢迎提 pr。👻

**Comment by zwmmm** [comment]
请问解决了么

**Comment by ziyoung** [comment]
@zwmmm IE 对 HTML 5 新元素支持性不太好😅。我们修复一下这个问题。https://caniuse.com/#search=main
