### ISSUE TITLE
The weekly settings in the [Bug Report] date control show the problem from Monday, format is yyyy-MM-dd, and the return time is Tuesday.

### ISSUE THREAD

**Issue by chen4342024** [ElemeFE/element#12100]
### Element UI version
2.4.4

### OS/Browsers version
chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
https://elementui.github.io/issue-generator/#/zh-CN

### What is Expected?
日期控件中的周设置从周一开始显示问题，format为yyyy-MM-dd， 返回的开始时间为周一

### What is actually happening?
日期控件中的周设置从周一开始显示问题，format为yyyy-MM-dd， 返回的开始时间为周二

**Comment by ziyoung** [comment]
@chen4342024 请提供一个可以重现问题的链接。

**Comment by chen4342024** [comment]
https://jsfiddle.net/pj71jkyw/396/  希望返回周一而不是周二

**Comment by chen4342024** [comment]
https://jsfiddle.net/krmcte81/   希望返回周一而不是周二 , 因为我想要日历以周一为第一天，所以我设置了firstDayOfWeek

**Comment by chen4342024** [comment]
@ziyoung https://jsfiddle.net/krmcte81/ 希望返回周一而不是周二 , 因为我想要日历以周一为第一天，所以我设置了firstDayOfWeek=1

**Comment by chen4342024** [comment]
@ziyoung 有没有办法设置日历是以周一开头，然后返回的开始时间也为周一呢。现在返回周二不是想要的结果

**Comment by jikkai** [comment]
Duplicate of #6754
