### ISSUE TITLE
Ability to set a group of cards

### ISSUE THREAD

**Issue by mehranrasulian** [ElemeFE/element#1210]
Do you have any plan to implement this feature so we can set a group of cards with a matching height between them in the same row ?

**Comment by Leopoldthecoder** [comment]
I don't quite understand what you are referring to. Could you elaborate more? I'm kinda confused by "a matching height between them".

**Comment by mehranrasulian** [comment]
Sorry!
For example, semantic UI says:
> To ensure cards are equal height use the plural, [cards](http://semantic-ui.com/views/card.html#cards). Card groups automatically uses [flex](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes) styles to match height between cards in the same row.

**Comment by mehranrasulian** [comment]
In the docs > cards,  there are two cards with images and their height is match but when I add some more words to the title of one of them, their height is not match anymore.

So it would be great if you add one example for a group of cards with different contact length but still same height.

sorry for my bad English

**Comment by Leopoldthecoder** [comment]
No worries. I see what you mean.

We don't have plans to add this feature because this can be done with CSS. One possible solution: http://jsfiddle.net/leopoldthecuber/ra7mycbj/ .
