### ISSUE TITLE
[Feature Request] add ionic icons to stepper

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#12116]
### Existing Component
Yes

### Component Name
step

### Description
step component can change icons using the "icon" property or slot however I can't find the way to use other icons like ionic icons.

I tried something like this which didn't work

<el-step 
	v-for="trackingEvent in trackingEventsVal" status=finish 
        :title="format_date(trackingEvent.event_datetime)   ' - '   trackingEvent.status_description" 
	:description="trackingEvent.event_description">
	<i class="add-circle-outline"></i>
</el-step>

Any idea how this can be done?

**Comment by jikkai** [comment]
```
<el-step icon="ion-ios-add"></el-step>
```

**Comment by Masber** [comment]
Hi,

what about if I download the icon in a svg file? I tried this but didn't work

`<el-step icon="../assets/img/package.svg"></el-step>`

thanks
