### ISSUE TITLE
[Bug Report] Why cant my '$confirm' set option 'distinguishCancelAndClose'?There is also no ts declare for it in my package.

### ISSUE THREAD

**Issue by ludesong** [ElemeFE/element#12111]
### Element UI version
2.4.4

### OS/Browsers version
win10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element/pull/11831](https://github.com/ElemeFE/element/pull/11831)

### Steps to reproduce
just install it and use $confirm

### What is Expected?
can use option 'distinguishCancelAndClose'

### What is actually happening?
cant

**Comment by HungryBird** [comment]
why it dosent work when I copy demo's code on http://element-cn.eleme.io/#/zh-CN/component/message-box.
I missing what type?
