### ISSUE TITLE
[Bug Report] official document: http://element.eleme.io access is extremely slow, probably not accessible.

### ISSUE THREAD

**Issue by vinceok** [ElemeFE/element#12117]
### Element UI version
2.4.4

### OS/Browsers version
win10    /    Chrome 版本 69.0.3486.0（正式版本） （32 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
1. 复制链接到浏览器http://element.eleme.io
2. 回车

### What is Expected?
能顺利打开

### What is actually happening?
不能顺利打开

**Comment by jikkai** [comment]
墙内用户推荐访问 http://element-cn.eleme.io
