### ISSUE TITLE
对话框 表单不能获取焦点

### ISSUE THREAD

**Issue by jfb** [ElemeFE/element#1211]
### ElementUI version
 1.0.2

### OS/Browers version
 macOS/Chrome 53

### Vue version
 2.0.7

### Reproduction Link
https://jsfiddle.net/tLe0aLwt/3/

### Steps to reproduce

input 虽然设置了autofocus，不能获取到焦点。而且 `确认` 也不能正确的响应回车。

**Comment by Leopoldthecoder** [comment]
这个 Demo 我这里是能获取到焦点的。

关于「确认也不能正确的响应回车」：如果焦点是在确认按钮上，是可以响应回车的，可以参考 `MessageBox` 的效果：http://jsfiddle.net/leopoldthecuber/kL3sd0LL/ ，打开 MessageBox 后，直接按下回车是可以关闭的；如果是希望焦点不在确认按钮上时，按下回车也能关闭，这个逻辑应该由用户自己处理。

**Comment by jfb** [comment]
这个和MessageBox的效果不完全相同。

点击 `打开嵌套表单的 Dialog` 后，应该 `活动名称` 获取到焦点。但是改 input 并没有获取到焦点，此时任意按键 input 里并不会有任何输入。

测试浏览器： Firefox IE10 Chrome53

**Comment by jfb** [comment]
![ee](https://cloud.githubusercontent.com/assets/15835605/20454307/d1755d7a-ae77-11e6-896b-802ffcf82c23.gif)

**Comment by jfb** [comment]
@Leopoldthecoder 获取到焦点后，输入框是蓝色的。

**Comment by furybean** [comment]
input 的 autofocus 是浏览器实现的，这个是在创建 input 的时候获得的。

实际上 Dialog 并没有懒渲染，是创建好了，在点击的时候又显示的，这样就造成了浏览器的 autofocus 无法生效的问题。

即使 Dialog 改成了懒渲染，在第二次打开 Dialog 的时候，autofocus 依然会失效。

这个问题没什么太好的解决办法，只能在 Dialog 的 open 回调里面主动调用这个 input 的 focus，否则是无法解决的。

**Comment by Leopoldthecoder** [comment]
我试了一下，在 Chrome 和 Safari 里面能够获取到焦点，Firefox 里不行。感觉和浏览器实现有关。

**Comment by jfb** [comment]
@Leopoldthecoder 这里 Chrome 偶尔能获取到，Firefox和 IE 基本没办法获取。

感觉是浏览器实现有区别，那先close把。
