### ISSUE TITLE
Transfer no data or 无数据?

### ISSUE THREAD

**Issue by arisliang** [ElemeFE/element#12125]
### Element UI version
2.4.4

### OS/Browsers version
Windows 10 / Chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/f1w4ush5/](https://jsfiddle.net/f1w4ush5/)

### Steps to reproduce
1. On the above link, when there's no data, it shows chinese "无数据".
2. On the official doc (http://element.eleme.io/#/en-US/component/transfer), when there's no data, it shows English "No data".

### What is Expected?
Show English "No data" by default. Or better to have a configuration option to provide the text by user.

### What is actually happening?
Sometimes it shows English, sometimes Chinese. Lack of consistency.

![transfer-no-data](https://user-images.githubusercontent.com/1115503/43192489-3fc06496-9030-11e8-9108-846b3578b7a0.PNG)

**Comment by jikkai** [comment]
Default language is Chinese, if you wish to use another language, i18n is required. See:
 http://element.eleme.io/#/en-US/component/i18n

Demo: https://jsfiddle.net/f1w4ush5/1/
