### ISSUE TITLE
loading service 全屏模式是否应该使用单例模式

### ISSUE THREAD

**Issue by ly303550688** [ElemeFE/element#1212]
loading service can't get the fullscreen loading instanse opening

**Comment by Leopoldthecoder** [comment]
看到你在 Gitter 里的提问了。似乎你是想关闭已经打开的 Loading？这个文档里有说明：调用时会返回一个实例，需要关闭的话在这个实例上调用 `close` 方法就可以。

关于单例，应该只是全屏的时候才需要。这个我看反馈情况再决定做不做。

**Comment by yiling-e0** [comment]
如何在此打开已经关闭的loading service呢 @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@yiling-e0 第一次怎么打开的就怎么打开

**Comment by yiling-e0** [comment]
你好  我的需求是   打开loading组件加载200个异步资源  并动态显示文案 1/200，现在加载文案并不支持数据模型同步，只能加载一个关闭loading 再打开  这样导致loading组件动画就不能播放 每次打开动画都被重置 @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@yiling-e0 或许可以不用 Loading 的 `text`，在打开 Loading 的时候自己显示一个文案在你需要的位置。
