### ISSUE TITLE
[Bug Report] popover nesting checkbox, switch  checkbox, trigger  popover  hide and show, Lead to splash screen

### ISSUE THREAD

**Issue by zhouxinnana** [ElemeFE/element#12127]
### Element UI version
2.3.8

### OS/Browsers version
win10, chrome 69

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/dfne2m95/4/](https://jsfiddle.net/dfne2m95/4/)

### Steps to reproduce
click checbox, trigger  popover  hide and show,

### What is Expected?
Do not trigger popover  hide and show, ,no Lead to splash screen

### What is actually happening?
Lead to splash screen

**Comment by ziyoung** [comment]
@zhouxinnana 不太明白你的意思。用中文描述吧。
