### ISSUE TITLE
[Feature Request] How to show el-table column based on existence of props

### ISSUE THREAD

**Issue by creativemind1** [ElemeFE/element#12126]
### Existing Component
Yes

### Component Name
El-Table

### Description
I will have dynamic data in which sometimes my array of objects will contains the property as 'month' and it's value. However I have to hide that if it doesn't exist. I tried here in the below jSFiddle. How can I achieve this?
https://jsfiddle.net/creativemind1/o35w9z7k/

**Comment by jikkai** [comment]
You should confirm if there is `month` in the objects
https://jsfiddle.net/o35w9z7k/3/

BTW, issues is ONLY used to track bugs and feature requests, please do not abuse it.
