### ISSUE TITLE
[Feature Request] MessageBox internal components can not use vuex and vue-router introduced in my business.

### ISSUE THREAD

**Issue by ahauzq** [ElemeFE/element#12129]
### Existing Component
是

### Component Name
MessageBox

### Description
看了下源码  MessageBox应该是设计思路上和别的组件不同，在内部重新引入了一个Vue，导致了内部的实例用不了业务当中引入的vuex

**Comment by ziyoung** [comment]
是的，或许你可以用 dialog 组件。
