### ISSUE TITLE
[Bug Report] el-select in remote mode displays the wrong item

### ISSUE THREAD

**Issue by sylvaincaillot** [ElemeFE/element#12139]
### Element UI version
2.4.5

### OS/Browsers version
Chrome

### Vue version
2.5.14

### Reproduction Link
[https://jsfiddle.net/sylvainc/eywraw8t/211856/](https://jsfiddle.net/sylvainc/eywraw8t/211856/)

### Steps to reproduce
This select input shows countries. By typing at least 3 letters, you see the matching countries.
So start entering FRA, you should get France and French Polynesia displayed.
Choose The first item  (France), the selected item is effectivelly France as shown on the side of the select input but the information displayed in the select is the last item of the option list (french Polynesia).

You can also try with ESP which return a long list of countries.
If you choose the first one of the list (Azerbaijan), the last one of the option list will be displayed in the select input (Uzbekistan)

### What is Expected?
I would expect the information displayed in the select input to be the information of the option I have chosen

### What is actually happening?
The information displayed in the select is the information of the last option in the list.

**Comment by wacky6** [comment]
https://jsfiddle.net/49jbdm27/

You must specify `value-key` to distinguish options from one and another, if its bounded value is object.
