### ISSUE TITLE
[Bug Report] chome浏览器中表格表头拖动后，显示出现偏移

### ISSUE THREAD

**Issue by myopenresources** [ElemeFE/element#12137]
### Element UI version
2.4.3

### OS/Browsers version
win10/google chrome 67.0.3396.99（正式版本） （32 位）

### Vue version
2.5.2

### Reproduction Link
可参考官网“表尾合计行”示例，[http://element-cn.eleme.io/#/zh-CN/component/table](http://element-cn.eleme.io/#/zh-CN/component/table)

### Steps to reproduce
带checkbox的表格并且有边框的，左右来回拖去表头后，发现表头与表体之间显示偏移了1像素，官网“表尾合计行”示例上出现的也是同一个问题，通过浏览器源代码查看后，发现表头上多了“<th class="gutter" style="width: 0px; display: none;"></th>”列，并且<colgroup>标签下也多了“<col name="gutter" width="0">”，奇怪的是colgroup的这个列并没有隐藏，如果将<col name="gutter" width="0">加上 display: none;" 后问题解决了，或者把这两个生成的列都删除了，问题也解决了

### What is Expected?
在googole chrome表格上拖动不会有像素的偏移

### What is actually happening?
在googole chrome表格上拖动会有像素的偏移

**Comment by jikkai** [comment]
官网表尾合计行示例并没有你描述的带 checkbox，请提供一个在线 demo

**Comment by myopenresources** [comment]
您好，我发现和checkbox没关系，同样是官网的那个示例，在是windows系统下的google chrome会有问题，在mac系统上的google chrome没有问题，我换成了mac都正常了。
