### ISSUE TITLE
[Bug Report] TypeError: Failed to execute'getComputedStyle'on'Window': parameter 1 is parameter

### ISSUE THREAD

**Issue by HadiChen** [ElemeFE/element#12135]
### Element UI version
2.2.1

### OS/Browsers version
macos 10.12.6 (16G29)

### Vue version
2.5.16

### Reproduction Link
[nuxtelement](https://github.com/ElemeFE/element/files/2232167/nuxtelement.zip)

### Installation

```shell
wget https://github.com/ElemeFE/element/files/2232167/nuxtelement.zip
unzip nuxtelement.zip
cd nuxtelement
npm i
npm run dev
```

### Steps to reproduce
把窗口打开到子窗口
这个时候，如果在子窗口操作所以的下拉，使用了isFixed 和 getStyleComputedProperty 都会报错
![操作演示](https://user-images.githubusercontent.com/11555571/43266907-162c1a4a-911f-11e8-825a-374e1a707173.gif)

### What is Expected?
能够自由在子窗口和父窗口之间拖动

### What is actually happening?
目前使用了isFixed仅仅是使用root下面的，这个获取有点问题

**Comment by jikkai** [comment]
你的 demo 在我这里跑起来有点问题，最好精简一个最小化可运行 demo

**Comment by yuchonghua** [comment]
方便截图您的问题给我吗
@jikkai

**Comment by ziyoung** [comment]
@HadiChen 看着像 `popper.js` 的问题，1. 先尝试升级  ElementUI 到最新版。2. 对例子精简一下。

**Comment by yuchonghua** [comment]
[nuxt-element-simplify.zip](https://github.com/ElemeFE/element/files/2234388/nuxt-element-simplify.zip)

这个dome可以样式可以重现问题

`package.json`文件中包需要以下版本
```json
{
  "name": "nuxt-element",
  "version": "1.0.0"
  "scripts": {
    "dev": "nuxt"
  },
  "dependencies": {
    "ddv-multi-window": "0.1.0",
    "element-ui": "2.4.5",
    "nuxt": "1.4.1"
  },
  "devDependencies": {
    "cross-env": "^5.0.1"
  }
}
```

`nuxt.config.js`配置全局样式
```JavaScript
module.exports = {
  mode: 'universal',
  // 全局样式 Global CSS
  css: [
    'element-ui/lib/theme-chalk/index.css',
    '@/assets/style/task.css',
    '@/assets/iconfont/iconfont.css'
  ],

  // 插件 plugins
  plugins: [
    '@/plugins/element-ui'
  ]
}
```
`plugins\element-ui.js`
```vue

import Vue from 'vue'
import Element from 'element-ui'
import DdvMultiWindow from 'ddv-multi-window'

Vue.use(DdvMultiWindow)
Vue.use(Element)
Vue.prototype.$alert = Element.MessageBox.alert;
```

**Comment by yeziZ** [comment]
`ddv-multi-window`是跨窗口的子窗口多tab应用，可以使用，目前问题好像是在子窗口的时候，dom在子窗口，事件在主窗口，然而在element-ui在主窗口查找子窗口的dom
初步估计是 `isFixed` 和 `getStyleComputedProperty` 方法的问题

/ping @ziyoung @jikkai @HadiChen

**Comment by yuchonghua** [comment]
[electron-nuxt-element.zip](https://github.com/ElemeFE/element/files/2234482/electron-nuxt-element.zip)

一个 electron  nuxt  element-ui 的dome
可以实现不同窗口之间的拖动

**Comment by HadiChen** [comment]
我主要是在[electron](https://electronjs.org/)中使用[element-ui](https://element.eleme.io/)，目前我的应用是基于[nuxt](https://nuxtjs.org/)的，出现这个问题估计如 [yeziZ](https://github.com/ElemeFE/element/issues/12135#issuecomment-408307109) 说的  [isFixed 和 getStyleComputedProperty](https://github.com/ElemeFE/element/issues/12135#issuecomment-408307109) 方法的问题，实际应用场景如 [yuchonghua](https://github.com/ElemeFE/element/issues/12135#issuecomment-408312075) 在 [electron-nuxt-element.](https://github.com/ElemeFE/element/files/2234482/electron-nuxt-element.zip)

/ping @jikkai @ziyoung

**Comment by HadiChen** [comment]
![image](https://user-images.githubusercontent.com/11555571/43303479-87627fc8-91a2-11e8-82e2-13a739c34971.png)

**Comment by HadiChen** [comment]
![2](https://user-images.githubusercontent.com/11555571/43303621-1f5bbb14-91a3-11e8-9930-cde58b06ff25.gif)

**Comment by yuchonghua** [comment]
有没有修复的建议呢？
/ping @jikkai

**Comment by wohaofan** [comment]
这个感觉挺不错的，不知道官方的element是否会支持多窗口呢？真的非常期待

**Comment by Caiyi-LI** [comment]
看着好高大上的功能。不知什么时候能够支持啊？？？非常期待

**Comment by glass4pk** [comment]
遇到类似难问题
这个功能比较有用，希望能修复

**Comment by Ethennoob** [comment]
功能不错，非常期待这个功能

**Comment by Oce4nChen** [comment]
这个组件还不错，支持下！

**Comment by linyueb** [comment]
支持一下

**Comment by zengfanyao** [comment]
Good function, very looking forward to this feature

**Comment by yuchonghua** [comment]
目前官方有修复的计划吗？非常期待能够修复一下，完美实现多窗口使用
@jikkai

**Comment by xhdf** [comment]
最近在开发中也遇到这个问题，希望能够修复一下

**Comment by xhdf** [comment]
这个功能我感觉挺酷的，期待能集成到自己的后台中...
饿了么的ui还是挺给力的，支持一下👍👍👍👍👍👍

**Comment by jikkai** [comment]
看了下，这应该不是 Element 的 bug，甚至在新窗口中调用 refresh 后 window 的指向也是父窗口的。
不过找到了一个 workaround 的办法，这个打开窗口的选项中 `mode` 改成 `iframe` 强制刷新掉页面应该能临时解决问题。

@yuchonghua @HadiChen 建议两位从依赖库上继续排查下问题。

**Comment by yuchonghua** [comment]
非常感谢您抽时间看来这个demo，这个新窗口里面是有的window是指向父窗口的，因为执行的所有的js是在原窗口[父窗口]执行的，新窗口的window并没有执行新代码，仅仅是document和样式是使用了新窗口的。

因为开始设计的时候，是使得了组件在不同的窗口之间拖到，那拖到新窗口后，如果重新实例vue，会有各种数据的同步问题，现在就是直接把document移动到了新窗口，这样一来，getComputedStyle的调用是在原窗口运行的，而document却在了新窗口，也就是说Element我是在原窗口[父窗口]实例化的，Element所引用的document在新窗口

@jikkai 您有更好的建议吗

**Comment by yuchonghua** [comment]
好的，非常感谢 @ziyoung @jikkai

**Comment by yuchonghua** [comment]
我安装 [HadiChen的步骤](https://github.com/ElemeFE/element/pull/11778#issuecomment-412258626) 测试后，发现 [popper.js](https://github.com/FezVrasta/popper.js) 能很好的兼容 [ddv-multi-window](https://github.com/ElemeFE/element/files/2280001/nuxt-element-vue-popper.zip)，[popper.js](https://github.com/FezVrasta/popper.js/issues/665) 暂时不需要 向 popper.js 提 [issue](https://github.com/FezVrasta/popper.js/issues/665)，不过 @ziyoung 修改后的 [pr#11778](https://github.com/ElemeFE/element/pull/11778) ，视乎还存在一些问题

> 文件[/src/utils/vue-popper.js](https://github.com/ziyoung/element/blob/vue-popper/src/utils/vue-popper.js)的[第99行](https://github.com/ziyoung/element/blob/vue-popper/src/utils/vue-popper.js#L99)到[第102行](https://github.com/ziyoung/element/blob/vue-popper/src/utils/vue-popper.js#L102)视乎可以删除，
因为[appendToBody](https://github.com/ElemeFE/element/blob/46284143d971b05d0ae1ebfe38dcea3167d0d6f5/src/utils/vue-popper.js#L137)在使用 [popper.js](https://github.com/FezVrasta/popper.js)后，变得视乎没有了实际意义，
然而[第137行](https://github.com/ziyoung/element/blob/vue-popper/src/utils/vue-popper.js#L137)的存在使得，[appendToBody](https://github.com/ElemeFE/element/blob/46284143d971b05d0ae1ebfe38dcea3167d0d6f5/src/utils/vue-popper.js#L137)为`true`时，拖动到新子窗口，
已经打开的下拉菜单没法跟随窗口切换，
因为该元素`appendChild`到了 `原窗口`的`document.body`

`仅仅以下`的`改动`经过测试可以`成功解决`了 [element#issues#12135](https://github.com/ElemeFE/element/issues/12135)和[ddv-multi-window](https://github.com/ddvjs/ddv-multi-window)功能的问题

[第99行](https://github.com/ziyoung/element/blob/vue-popper/src/utils/vue-popper.js#L99)到[第102行](https://github.com/ziyoung/element/blob/vue-popper/src/utils/vue-popper.js#L102)视乎可以删除，
[第137行](https://github.com/ElemeFE/element/blob/46284143d971b05d0ae1ebfe38dcea3167d0d6f5/src/utils/vue-popper.js#L137)可以删除
[第239行](https://github.com/ElemeFE/element/pull/11778/files#diff-cb3efcfdf157956fce0480ea920e5e5cR239)可以修改为
```JavaScript


  beforeDestroy() {
    this.doDestroy(true);
    if (this.popperElm) {
      this.popperElm.removeEventListener('click', stop);
    }
  },

```

 [popper.js](https://github.com/FezVrasta/popper.js) 和[ddv-multi-window](https://github.com/ElemeFE/element/files/2280001/nuxt-element-vue-popper.zip)测试效果如下

----

![run-demo](https://user-images.githubusercontent.com/17898715/43988589-9bd7350a-9d6b-11e8-99ca-a290f7d6712c.gif)

----

另外存在 [`HTMLElement `问题](https://github.com/ElemeFE/element/pull/11778#pullrequestreview-145449486)、[`esm `问题](https://github.com/ElemeFE/element/pull/11778#pullrequestreview-145449455)和[`props`中`popperOptions `建议](https://github.com/ElemeFE/element/pull/11778#pullrequestreview-145448142) 将在 [vue-popper-pr#11778](https://github.com/ElemeFE/element/pull/11778) 提出。

最后感谢 @ziyoung @jikkai 以及 [element](https://github.com/ElemeFE/element) 的支持

**Comment by yuchonghua** [comment]
https://github.com/ElemeFE/element/issues/12135#issuecomment-412282520 的回复非常期待得到饿了么的支持，感谢饿了么

/ping @ziyoung @jikkai
