### ISSUE TITLE
[Feature Request] I used the CDN of element, but it didn't work in the page.

### ISSUE THREAD

**Issue by ZSH-HSZ** [ElemeFE/element#12130]
### Existing Component
Yes

### Component Name
all

### Description
使用npm方式引入的样式是正常的，我在网上找到了同样的一个问题，里边有一个demo链接，也是使用的cdn，好像并没有效果，这是demo链接https://codepen.io/QingWei-Li/pen/vXwJrY

**Comment by jikkai** [comment]
这个是旧版本的 css 引入路径，2.x 以后的路径为
```
<link rel="stylesheet" href="//unpkg.com/element-ui@next/lib/theme-chalk/index.css">
```

**Comment by ZSH-HSZ** [comment]
那在nuxt上如何使用element cdn呢

**Comment by jikkai** [comment]
详情参照 nuxt 文档 https://zh.nuxtjs.org/faq/

BTW

1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by ZSH-HSZ** [comment]
你好，使用element cdn的时候，element中的自定义标签不会自动转换，使用的nuxt框架，已经在nuxt.conf.js中配置了head，
![image](https://user-images.githubusercontent.com/31639046/43243748-a694b35c-90da-11e8-867c-2de186717175.png)
![image](https://user-images.githubusercontent.com/31639046/43243762-b6b070dc-90da-11e8-8471-fe4d86943131.png)
然后在页面中标签不会转化

**Comment by Normol** [comment]
@ZSH-HSZ 请问你解决了吗

**Comment by lxc455735702** [comment]
@ZSH-HSZ @Normol 同问，在nuxt框架中如何使用element cdn 在nuxt issues 找了很多也没有解决方案 希望有答案相互可以分享
