### ISSUE TITLE
[Bug Report] el-autocomplete automatically takes validation errors before it is input, using rules validation.

### ISSUE THREAD

**Issue by aabc6419tw** [ElemeFE/element#12144]
### Element UI version
2.4.4

### OS/Browsers version
windows10 / ie11

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/aabc6419tw/pen/KeWdxP](https://codepen.io/aabc6419tw/pen/KeWdxP)

### Steps to reproduce
依據https://github.com/ElemeFE/element/issues/11566
我將 trigger: 'blur' 拿掉後，在chrome 能夠正常的運行，
但使用ie11時，會在未輸入前，直接自動驗證錯誤。

### What is Expected?
應該是在點擊輸入框 (input) 後，或在點擊送出表單後再進行驗證

### What is actually happening?
在未輸入表單時就直接驗證了，並顯示錯誤！
另外希望可以在表單文件上增加關於trigger能使用的類型及說明。

#autocomplete #form #rules

**Comment by bnckatona** [comment]
+1

**Comment by ziyoung** [comment]
@aabc6419tw 更新最新的 element 版本了，我本地无法重现。请确认一下该问题是否在 window 上存在。https://codepen.io/ziyoung/pen/zMxawB?editors=1111

**Comment by classLfz** [comment]
遇到同样问题，我感觉应该是点击了列表后，触发了 `blur` 事件导致的？我的解决方案是把 `trigger: 'blur'` 改成 `trigger: 'change'` 。
