### ISSUE TITLE
Is [Feature Request] element UI table planning to support table columns that can be dynamically added and deleted?

### ISSUE THREAD

**Issue by zccccccc** [ElemeFE/element#12145]
### Existing Component
否

### Component Name
Table 表格

### Description
el-table 是否有计划支持 列的动态选择 ，如： 按照现在的生成完表格数据后，列头上有一按钮，可以弹出选择显示或隐藏哪一列

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.
