### ISSUE TITLE
[Bug Report] popper-class cannot dynamically setting

### ISSUE THREAD

**Issue by qilvnuanqingyou** [ElemeFE/element#12142]
### Element UI version
2.4.5

### OS/Browsers version
win10/chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/qilvnuanqingyou/9w35dz2f/4/](https://jsfiddle.net/qilvnuanqingyou/9w35dz2f/4/)

### Steps to reproduce
:popper-class="{'light' : flag}"

### What is Expected?
no  warn

### What is actually happening?
Invalid prop: type check failed for prop "popperClass". Expected String, got Object.

**Comment by ziyoung** [comment]
@qilvnuanqingyou `popper-class` accepts a string type value.
```
:popper-class="flag ? 'light' : '' "
```

**Comment by qilvnuanqingyou** [comment]
@ziyoung thanks a lot
