### ISSUE TITLE
[Bug Report] upload upload control upload a picture will appear two times chagne calls.

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#12143]
### Element UI version
2.4.5

### OS/Browsers version
Window 10 Chrome 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/0kvzqomf/3/](https://jsfiddle.net/0kvzqomf/3/)

### Steps to reproduce
请看控制台  第一次的时候没有走接口  第二次是走完接口 又重新调用了一次change事件，  我的初衷是想通过自己来传参数  不想使用action 当时如果通过change的话 就会每次都调用两次接口

### What is Expected?
希望每次change只在调用的时候进行一次

### What is actually happening?
每次change只在调用的时候进行两次次

**Comment by jikkai** [comment]
根据文档：
![image](https://user-images.githubusercontent.com/14025786/43300721-5775cf54-9193-11e8-97a9-9919e2a116d8.png)
`on-change`是个钩子，而且添加文件和上传失败确实应该执行两次。

如果想自定义上传行为，可以使用`http-request`属性。
