### ISSUE TITLE
[Bug Report] [bug] Cannot read property'$el'of undefined

### ISSUE THREAD

**Issue by linmoer** [ElemeFE/element#12158]
### Element UI version
2.4.5

### OS/Browsers version
windows chrome-67.0.3396.99

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://github.com/ElemeFE/element/issues/3004](https://github.com/ElemeFE/element/issues/3004)

### Steps to reproduce
在测试环境出现，即node环境下出现
 TypeError: Cannot read property '$el' of undefined
      at VueComponent.mounted (node_modules\_element-ui@2.4.5@element-ui\lib\element-ui.common.js:9127:54)

### What is Expected?
麻烦在 element.common.js 里的
this.referenceElm = this.$parent.$refs.reference.$el;
前面加上
if (!this.$parent.$refs.reference) return;

### What is actually happening?
...

**Comment by ziyoung** [comment]
@linmoer 应该不是 element-ui 的 bug。
https://github.com/ElemeFE/element/blob/2bb9fd64818dd108635e7fa91214f908f8b3dbb1/packages/select/src/select-dropdown.vue#L65-L67
`mounted` 钩子在服务器端渲染期间不被调用。检查一下 [isServer](https://cn.vuejs.org/v2/api/#vm-isServer) 是否是 `true`。

**Comment by linmoer** [comment]
不是服务端渲染，是测试，，

**Comment by linmoer** [comment]
@wacky6 @jikkai @mrin9 @ziyoung  这个问题怎么是服务器端渲染呢？这是前端测试时的报的错，我也检查了isServer，是为false的，然后我这个项目也是一个纯前端的项目，不涉及到ssr

**Comment by linmoer** [comment]
这个刚刚搭的一个demo：https://github.com/linmoer/el-test，，，跑测试的时候就会出现题目中的错误，错误是el-select这个组件抛出的

**Comment by jikkai** [comment]
用 jest 做测试的话，你可以参照下这个 #11811

**Comment by linmoer** [comment]
eeee，https://github.com/ElemeFE/element/issues/11811
并不能解决这个问题，目前只有el-select这个组件抛出了这个问题，其他的没问题

**Comment by bmfs** [comment]
Also faced the same problem and I'm already using jest for testing.

**Comment by miser** [comment]
@jikkai 
我用karma、mocha、 vue/unit-test 进行单测

遇到el-select组件，就会报出 

> Cannot read property '$el' of undefined

不知道这个问题能否修复

**Comment by kokokele** [comment]
jest test select 还是报错

**Comment by kokokele** [comment]
jest test select 还是报错

**Comment by kokokele** [comment]
fix this: https://github.com/ElemeFE/element/pull/13098

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/12634#issuecomment-429552223

**Comment by hengkx** [comment]
我单元测试也报错 `jest` 
![image](https://user-images.githubusercontent.com/8358236/48813175-aed33f00-ed70-11e8-9c5b-40d1329ac63e.png)

**Comment by yinyihui** [comment]
这个问题貌似还没有修复，请问有没有什么进展？

**Comment by Akimyou** [comment]
Still have this problem in v2.13.2

**Comment by Ogurimuio** [comment]
https://vue-test-utils.vuejs.org/api/components/

import { config } from '@vue/test-utils'
config.stubs.transition = false

**Comment by Ogurimuio** [comment]
遇到了同样的问题
https://vue-test-utils.vuejs.org/api/components/

添加以下代码，可以解决问题。
import { config } from '@vue/test-utils'
config.stubs.transition = false
