### ISSUE TITLE
[Bug Report] the table component cannot follow automatically when I shrink shrink,

### ISSUE THREAD

**Issue by liweili50** [ElemeFE/element#12150]
### Element UI version
2.4.5

### OS/Browsers version
macOS 10.13.6/Chrome 67.0.3396.99（正式版） （64 位）

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/handsomeJonas/mmx38qxw/4236/](https://jsfiddle.net/handsomeJonas/mmx38qxw/4236/)

### Steps to reproduce
The normal table component expands with the width of the parent element, but when using the 'display:table' to set a parent element and using the 'display: table-cell' to set the children element, the table component in children element only become larger as the width becomes larger, but the size of the table component will not shrink after the browser becomes smaller.

### What is Expected?
the table component expands with the width of the parent element

### What is actually happening?
the table component only become larger as the width becomes larger, but the size of the table component will not shrink after the browser becomes smaller.

**Comment by jikkai** [comment]
Try to add `table-layout: fixed;`

https://jsfiddle.net/mmx38qxw/4310/
