### ISSUE TITLE
[Bug Report] Table aggregate line support merger

### ISSUE THREAD

**Issue by osinglee** [ElemeFE/element#12151]
### Element UI version
2.4.0

### OS/Browsers version
mac0s 10.13.4

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/v1sk37du/2/](https://jsfiddle.net/v1sk37du/2/)

### Steps to reproduce
- 

### What is Expected?
I hope that the aggregate bank can support the merge cell

### What is actually happening?
combined bank does not support merger

**Comment by jikkai** [comment]
Merging cells is not support in summary row. If you want a highly customized one, `append` slot may help you.
