### ISSUE TITLE
[Feature Request] NavMenu navigation menu mouse moves up the background color.

### ISSUE THREAD

**Issue by Undefined123456789** [ElemeFE/element#12152]
### Existing Component
是

### Component Name
NavMenu 导航菜单

### Description
建议NavMenu 导航菜单组件，鼠标移上去的背景色可支持配置，目前element-ui使用编程方式写内联样式来设置背景色，不提倡这样做。故我建议下增加以下属性：hover-background-color（鼠标移上去的背景颜色）、hover-text-color（鼠标移上去菜单的文字颜色）

**Comment by jikkai** [comment]
Duplicate of #7686
