### ISSUE TITLE
In [Bug Report] Table, cell clicks occasionally trigger cell-mouse-leave without cause.

### ISSUE THREAD

**Issue by shadowprompt** [ElemeFE/element#12156]
![cellclick](https://user-images.githubusercontent.com/1947096/43382484-7f477d7e-940a-11e8-8f18-63c5f8c92505.gif)

### Element UI version
2.4.5

### OS/Browsers version
window 10/chrome 68

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4304/](https://jsfiddle.net/mmx38qxw/4304/)

### Steps to reproduce
来回在表格中随意点击任意行，尝试个50遍以内肯定会出现复现

### What is Expected?
在鼠标已经移入当前行后，在行内点击，不会出现闪动（css效果），无任何变化才对

### What is actually happening?
某个当前被点击行出现闪动，貌似触发了cell-mouse-leave和cell-mouse-enter。附件gif图中每次操作为click，并非hover，最后在第6行出现闪动，“编辑”二字出现短暂消失后再次显示。

**Comment by jikkai** [comment]
我这里没能复现出来，能否提供一个稳定复现的方法，纯点击应该是不会去触发 `cell-mouse-leave` 和 `cell-mouse-enter` 的

**Comment by shadowprompt** [comment]
@jikkai 我就是靠点击发现的，不需要试很久啊。我提供的jsfiddle地方就可以，会发现‘编辑’闪动一下的

**Comment by shadowprompt** [comment]
@jikkai 不管了吗

**Comment by jikkai** [comment]
我这里无法复现，你这边换台电脑或者浏览器也有同样的问题吗

**Comment by shadowprompt** [comment]
@jikkai 还真跟浏览器有关，我的chrome是Version 68.0.3440.75 (Official Build) (64-bit）英文版，但是用英文版火狐没有问题，刚将chrome更新至最新的Version 68.0.3440.84 (Official Build) (64-bit)英文版，问题依旧。

**Comment by ziyoung** [comment]
@shadowprompt 我这边也无法重现。Chrome 版本：67.0.3396.99。
