### ISSUE TITLE
[Bug Report] tree loading problems in dialog

### ISSUE THREAD

**Issue by ruanxuefeng** [ElemeFE/element#12168]
### Element UI version
2.4.5

### OS/Browsers version
谷歌浏览器

### Vue version
2.5.17-beta.0

### Reproduction Link
https://jsfiddle.net/mmx38qxw/4356/

### Steps to reproduce
在第一次打开dialog，this.$refs.tree为undefined，下次打开才能正常使用

### What is Expected?
第一次打开可以用

### What is actually happening?
第一次打开不可以用

**Comment by ziyoung** [comment]
不算是 element  的 bug 。试着用 $nextTick，https://jsfiddle.net/zhiyang/mmx38qxw/4366/
