### ISSUE TITLE
The filters parameters filtered by the [Bug Report] Table component cannot be displayed under asynchronous conditions.

### ISSUE THREAD

**Issue by xiongsongsong** [ElemeFE/element#12163]
### Element UI version
2.4.5

### OS/Browsers version
All

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/8qu9c73v/6/](https://jsfiddle.net/8qu9c73v/6/)

### Steps to reproduce
* 点击日期表头，无法展现筛选框。

此问题已经上报过： https://github.com/ElemeFE/element/issues/12079 ，在2.4.5仍然出现。

### What is Expected?
Table的表头筛选设置项:filtes，在异步设置值的情况下可以点选。

### What is actually happening?
表头的筛选未出现下拉的icon，点击后也无反应。

**Comment by Judyya** [comment]
你好，你那边这个问题解决了吗，我这边也是遇到一样的问题

**Comment by xiongsongsong** [comment]
@Judyya 看样子2.5.6会修复。

**Comment by yuanyuanshen** [comment]
是 table 的filter是异步的请求，设置了tilter ，但是下拉列表加载不出来么？
