### ISSUE TITLE
[Bug Report] vue-cli run build element-ui  time-picker 'minite' and 'second' cannot scroll to greater than 23

### ISSUE THREAD

**Issue by jingmiaohe** [ElemeFE/element#12166]
### Element UI version
2.4.5

### OS/Browsers version
chrome 68

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
check node_modules element-ui  element-ui.common.js file, 
you can  find 'time-picker' component has a method 'handleScroll', 
and you see there is one line writes '   ' '   type === 'hours' ? 23 : 59         '; 
 but when after run build,  you can find this line in vendor.js changes like this '    "hour" e?23:59      '
,,,, so what happend during the pack？？？？？ 

### What is Expected?
time-picker 'minite' and 'second' can scroll to greater than 23

### What is actually happening?
time-picker 'minite' and 'second' cannot  scroll to greater than 23

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
