### ISSUE TITLE
[Feature Request] recommends adding checked to the data property

### ISSUE THREAD

**Issue by dongsuju** [ElemeFE/element#12161]
### Existing Component
是

### Component Name
tree

### Description
目前default-checked-keys 只是在组件初始化的时候起作用，如果用lazy方式加载 ，就不能及时显示checked。

**Comment by jikkai** [comment]
lazy 下应该也是支持的，demo：https://jsfiddle.net/zay0wfr3/1/

**Comment by ziyoung** [comment]
@dongsuju  不太明白你的意思，在这个例子中 default-checked-keys 是生效的。 https://jsfiddle.net/zhiyang/jL0mrowc/3/

**Comment by dongsuju** [comment]
先确定 tree的default-checked-keys，再点击tree 进行加载节点，这是加载后的节点没有根据default-checked-keys 进行checked。

**Comment by jikkai** [comment]
@dongsuju 这样也是支持的：https://jsfiddle.net/zay0wfr3/2/

**Comment by dongsuju** [comment]
好的，谢谢各位了，我再研究一下。
