### ISSUE TITLE
[Bug Report] The fixed attribute in <el-table-column> will causes <el-table-body> to be rendered twice

### ISSUE THREAD

**Issue by SHERlocked93** [ElemeFE/element#12177]
### Element UI version
2.4.5

### OS/Browsers version
win10 / chrome 68

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/SHERlocked93/mmx38qxw/4395/](https://jsfiddle.net/SHERlocked93/mmx38qxw/4395/)

### Steps to reproduce
点击右边的展开按钮

Click the expand button on the right

### What is Expected?
只渲染组件 `<el-table-body>` 一次，`<this-expand>`组件中的mounted方法只打印一次

Render the component `<el-table-body>` only once, and the mounted method in the <this-expand> component only prints once.

### What is actually happening?
`<el-table>`下面的`<el-table-body>`会渲染两个，在开发模式下，打开vue-devtools发现`<ElTable>`下面有两个`<ElTableBody>`，因此其中的组件也会被渲染两次

<el-table-body> under <el-table> will render two. In development mode, open vue-devtools and find that there are two <ElTableBody> under <ElTable>, so the components will also be rendered twice

**Comment by jikkai** [comment]
这不是一个 BUG。因为现在 fixed table 的实现方式就是用多个 table 拼装而成的，甚至头尾列都被 fixed 的时候 table body 会被渲染三次。

**Comment by hoythan** [comment]
我认为它应当属于一个为了 实现 fixed 效果而衍生的 bug。

**Comment by miccuci** [comment]
这个确实会导致bug，如果table-column里面使用slot动态渲染的组件指定了ref的话，会导致ref重复，通过ref无法访问到该组件

**Comment by Wetoria** [comment]
> 这不是一个 BUG。因为现在 fixed table 的实现方式就是用多个 table 拼装而成的，甚至头尾列都被 fixed 的时候 table body 会被渲染三次。

针对这个问题，目前有没有解决办法？
在组件中可以通过parent来判断组件是否属于fixed dom下，但是这很依赖于element的实现方式，如果有变动，那么这个判断逻辑就会改变。

**Comment by icemirror** [comment]
> > 这不是一个 BUG。因为现在 fixed table 的实现方式就是用多个 table 拼装而成的，甚至头尾列都被 fixed 的时候 table body 会被渲染三次。
> 
> 针对这个问题，目前有没有解决办法？
> 在组件中可以通过parent来判断组件是否属于fixed dom下，但是这很依赖于element的实现方式，如果有变动，那么这个判断逻辑就会改变。

请问可以请教一下你的实现思路吗?

**Comment by Wetoria** [comment]
通过'$parent.$el.offsetParent.className'获取父节点的class，判断里面是否包含fixed字段来判断是否输入fixed节点下渲染的。然后在非fixed节点下时，再进行后续的方法。

不过这个方法依赖Element的实现方式，万一有变更的话，会影响这个判断逻辑。我们项目目前把elementUI的版本给定死了

**Comment by icemirror** [comment]
> 通过'$parent.$el.offsetParent.className'获取父节点的class，判断里面是否包含fixed字段来判断是否输入fixed节点下渲染的。然后在非fixed节点下时，再进行后续的方法。 不过这个方法依赖Element的实现方式，万一有变更的话，会影响这个判断逻辑。我们项目目前把elementUI的版本给定死了
> […](#)

谢谢~

**Comment by twocucao** [comment]
目前这个问题依旧存在

**Comment by yinyihui** [comment]
就是用而言，table这个组件在一般使用情况下还是可以的，一旦加入fixed和tree prop之后表现就有点差强人意了
