### ISSUE TITLE
[Bug Report] el-select multi select drop-down box option too long when the style is confused.

### ISSUE THREAD

**Issue by Xiaoxiaoaiya** [ElemeFE/element#12173]
### Element UI version
2.4.5

### OS/Browsers version
win8/Chrome  67.0.3396.99

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/g53s10zw/](https://jsfiddle.net/g53s10zw/)

### Steps to reproduce
选中内容很长的选项后，样式错乱。如何优雅展示？

### What is Expected?
选中内容很长的选项后，样式错乱。如何优雅展示？

### What is actually happening?
选中内容很长的选项后，样式错乱。如何优雅展示？

**Comment by jikkai** [comment]
See #9352
