### ISSUE TITLE
tree 叶子节点分页展示

### ISSUE THREAD

**Issue by TabCrazy** [ElemeFE/element#12174]
叶子节点1000万多条数据，已经启用懒加载。等待时间还是比较长，PO提出叶子节点需要分页展示，tree有能力实现分页叶子节点分页加载展示吗？

**Comment by yuleiQ** [comment]
> 叶子节点1000万多条数据，已经启用懒加载。等待时间还是比较长，PO提出叶子节点需要分页展示，tree有能力实现分页叶子节点分页加载展示吗？

请问您是怎么操作的呢
