### ISSUE TITLE
[Bug Report] table el-table-column type="selection" 如何默认选中某项

### ISSUE THREAD

**Issue by gauseen** [ElemeFE/element#12172]
### Element UI version
2.4.5

### OS/Browsers version
all

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/4qzrudps/8/](https://jsfiddle.net/4qzrudps/8/)

### Steps to reproduce
https://jsfiddle.net/4qzrudps/8/

### What is Expected?
类似 iview ui 的 给 data 项设置特殊 key _checked: true 可以默认选中当前项。
https://www.iviewui.com/components/table#DX
谢谢！

### What is actually happening?
https://jsfiddle.net/4qzrudps/8/

**Comment by ziyoung** [comment]
@gauseen 你这提的这个 issue，不是 bug report 也不是 feature request，请不要滥用 issue。

**Comment by ziyoung** [comment]
可以试试 [toggleRowSelection](https://element.faas.ele.me/#/zh-CN/component/table#table-methods) 这个函数去选择某一行。https://jsfiddle.net/zhiyang/3kunm687/2/
```js
mounted() {
   this.$refs.multipleTable.toggleRowSelection(this.tableData3[1]);
}
```
