### ISSUE TITLE
[Bug Report] select component single selection and reelection switching problem

### ISSUE THREAD

**Issue by lovewxz** [ElemeFE/element#12180]
### Element UI version
2.4.5

### OS/Browsers version
chrome 69.0.3497.12

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/971brqea/45/](https://jsfiddle.net/971brqea/45/)

### Steps to reproduce
点击切换按钮的时候，当单选框切换成多选框的时候，input框并没有被清空

### What is Expected?
input框清空

### What is actually happening?
input框未清空

**Comment by jikkai** [comment]
加个 [`key`](https://cn.vuejs.org/v2/api/#key)
https://jsfiddle.net/971brqea/47/
