### ISSUE TITLE
The page crashes after [Bug Report] uses the el-tabs component

### ISSUE THREAD

**Issue by xiaomizhou66** [ElemeFE/element#12183]
### Element UI version
2.4.5

### OS/Browsers version
win7/ chrome 67.0.3396.99

### Vue version
2.5.2

### Reproduction Link
[https://github.com/xiaomizhou66/element-ui-el-tabs](https://github.com/xiaomizhou66/element-ui-el-tabs)

### Steps to reproduce
①npm install
②npm run dev
③错误在src/components/pagevue/pos.vue 页面，目前已经解决这个页面崩溃，但是解决得莫名奇怪的，不知所以，具体办法如下，

页面布局：使用的float布局
解决办法也在pos.vue页面，
① 在组件el-tabs前面加一行标题
② 在组件el-tabs 外层加一个el-row
③ 清除页面布局中的float

### What is Expected?
npm run dev  正常

### What is actually happening?
在没有使用以下的办法情况下，npm run dev 没有正常打开页面，崩溃了。
解决办法也在pos.vue页面，
① 在组件el-tabs前面加一行标题
② 在组件el-tabs 外层加一个el-row组件
③ 清除页面布局中的float

**Comment by jikkai** [comment]
你的 demo 移除 el-row 运行以后也未出现异常。
如果所谓的“页面崩溃”是指布局上出现问题，可以排查下是否是因为你这边 CSS 的原因造成的。

如果能提供稳定复现的 demo，推荐使用 https://jsfiddle.net 做一个最小化在线 demo 排除你自己的代码造成的干扰。

**Comment by poncianodiego** [comment]
I'm experiencing the same issue
