### ISSUE TITLE
[InputNumber] Bug: the input control type is not number

### ISSUE THREAD

**Issue by riovir** [ElemeFE/element#1218]
### ElementUI version
1.0.2

### OS/Browers version
All

### Vue version
2.0.7

### Reproduction Link
http://jsfiddle.net/bbg0x1kf/

### Steps to reproduce
Run the JSFiddle and inspect the element
```
 .el-input-number -> 
    .el-input -> <input type="text"  ... >
```            

### What is Expected?
```<input type="number" ... />```. This would make the widget easy to use with a mobile phone.

### What is actually happening?
```<input type="text" ... />```. This causes mobile devices to show a regular keyboard instead of numbers.

**Comment by baiyaaaaa** [comment]
![image](https://cloud.githubusercontent.com/assets/3655403/20453426/7e7b2568-ae5f-11e6-8d5f-ecb5112b2bee.png)

if set the type to number, we can not remove the build-in controls button as show above.
