### ISSUE TITLE
[Bug Report] el-table made page flash

### ISSUE THREAD

**Issue by fanxianbin** [ElemeFE/element#12185]
### Element UI version
2.3.5

### OS/Browsers version
window / chrome 62.0.3202.94

### Vue version
2.5.16

### Reproduction Link
[https://elementui.github.io/noRealLink](https://elementui.github.io/noRealLink)

### Steps to reproduce
<keep-alive>
    <router-view></router-view>
</keep-alive>

1. page contains el-table tag   2.don't set all column width 3.reenter page

### What is Expected?
dont's make el-table content flash, Stay the same whenever you enter the page

### What is actually happening?
el-table content will flash when is reenter my page

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
