### ISSUE TITLE
[Bug Report] Flashing occurs when I try to close the Dialog, but not every time

### ISSUE THREAD

**Issue by clxhhsy** [ElemeFE/element#12186]
### Element UI version
2.4.5

### OS/Browsers version
win10/IE11

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/tg2r3wq0/](https://jsfiddle.net/tg2r3wq0/)

### Steps to reproduce
The example on the official website can also present this problem, triggered when closed, but not necessarily every time

### What is Expected?
Looking forward to Dialog hiding directly, no flickering

### What is actually happening?
flicker

**Comment by ziyoung** [comment]
Can't reproduce.

**Comment by clxhhsy** [comment]
@ziyoung 试过截图，但是图上没办法呈现这个问题，因为速度太快了，来不及

**Comment by clxhhsy** [comment]
@ziyoung IE11打不开官方网站，我跑的源码，`npm run dev`，可以重现这个问题

**Comment by clxhhsy** [comment]
![bandicam 2018-08-01 14-45-48-923](https://user-images.githubusercontent.com/11402690/43505604-08f443f0-959a-11e8-98d4-dfc61e626ff5.gif)不是很清晰，但还是能看到闪烁的

**Comment by ziyoung** [comment]
@clxhhsy 看来是有问题的。Windows 上的 Chrome 浏览器会出现吗？打开两个 dialog 时，才会出现这个问题？

**Comment by clxhhsy** [comment]
@ziyoung chrome没问题，打开一个也会有这个问题，我是为了容易复现这个问题，所以开的两个

**Comment by ccchhhccc** [comment]
两个对话框的时候，要先把一个对话框打开，强制刷新视图，再关闭另一个就不会闪了

**Comment by mmd0308** [comment]
这个问题现在有解决方案吗？项目中遇到这个问题，求解决方案。

**Comment by somsne** [comment]
同样在项目中碰到这个问题，主要不方便在于这种情况不是每次都能复现。
但目前测试下来能知道的是，在性能不是很好的设备上更容易出现这个情况

**Comment by Lyd9607** [comment]
这个可以给dialog加上key试一下，应该就没有了
