### ISSUE TITLE
[Bug Report] el-date-picker clearable empty button error display

### ISSUE THREAD

**Issue by viewweiwu** [ElemeFE/element#12189]
### Element UI version
2.4.5

### OS/Browsers version
win10 / chrome67

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/qvdxp178/](https://jsfiddle.net/qvdxp178/)

### Steps to reproduce
1、打开时间选择器
2、右下角会出现【清空】按钮

### What is Expected?
设置了 clearable 的 datepicker ，隐藏【清空】按钮

### What is actually happening?
出现了【清空】按钮

**Comment by jikkai** [comment]
@wacky6 大佬来看下。要实现这个的化，现阶段好像 data-range 只能从 refs 的 maxInput 和 minInput 里拿 `clearable`？

**Comment by wacky6** [comment]
给 date-panel 加一个新的属性就好了，然后从 picker.vue proxy进去。 `refs` 慎用。

* date-range.vue 的 `data()` 里面加个 `clearable` 或者 `hideClearButton` 之类的属性
* picker.vue L827-829 对 `format` 的做法参考一下就好了；可以考虑一下 `updateOptions` 里面把 `pickerOptions` 的同名属性排除（一样可以用 `format` 做参照）

（好想用 vue-portal 重写啊

**Comment by sxtaosdo** [comment]
最后怎么处理的？
