### ISSUE TITLE
[Feature Request] select component should be able to clear the option

### ISSUE THREAD

**Issue by littleant111** [ElemeFE/element#12182]
### Existing Component
是

### Component Name
el-select

### Description
Select component should be able to clear a option with a 'x' button at the end of a option.
And i think select component could use the 'append' and 'prepend'

**Comment by wacky6** [comment]
Please explain why are these features necessary.

What's their use scenario?
Are there any design / framework that offers this kind of UI design?
Where would you expect the clear icon be (it can't be in same place as the downward arrow).
