### ISSUE TITLE
[Bug Report] Invalid HTML in popover

### ISSUE THREAD

**Issue by danielchodusov** [ElemeFE/element#12199]
### Element UI version
2.4.5

### OS/Browsers version
any

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4462/](https://jsfiddle.net/mmx38qxw/4462/)

### Steps to reproduce
Popover generates invalid HTML5 - span contains div element which is not valid in HTML5, and seems this span (template  -> span) has no use at all, it doesn't bind any CSS to it. Why it's here? It also disallow to use popover in ul/li elemens. I think this span could be removed.
```
<template>
  <span>
    <transition
      :name="transition"
      @after-enter="handleAfterEnter"
      @after-leave="handleAfterLeave">
      <div
```

### What is Expected?
```
<div id="app">
<div> <--- it should be div here or event better, no element
<div class="menu-item el-popover__reference" aria-describedby="el-popover-4237" tabindex="0">
<span>
        something
</span>
</div>
</div>
</div>
```

### What is actually happening?
````
<div id="app">
<span> <--- but actually there is a span
<div class="menu-item el-popover__reference" aria-describedby="el-popover-4237" tabindex="0">
<span>
        something
</span>
</div>
</span>
</div>
```

<!-- generated by https://eleme-issue.surge.sh DO NOT REMOVE -->

**Comment by ziyoung** [comment]
@danielchodusov yes, span element shouldn't contain div element. But the span element can't be removed.
https://github.com/ElemeFE/element/blob/156fccd83482a4c3b702104598c1290f6170caab/packages/popover/src/main.vue#L30-L33
Popover uses `vue-poppoer` mixin which has `append-to-body` attribute. When `append-to-body` is false, the reference element is mounted to the span element.
