### ISSUE TITLE
How can [Feature Request] el-table implement highlight-current-row functions similar to single selection tables in multiple selection tables?

### ISSUE THREAD

**Issue by elewen** [ElemeFE/element#12191]
### Existing Component
Yes

### Component Name
el-table

### Description
开发中需要实现 table 在多选表格中高亮所有选中行的功能，但 el-table 并未提供类似于 highlight-selected-rows 的功能。发现有个highlight-current-row的功能，但是却无法嫁接到现有需求当中。也尝试结合 el-table 提供的其他event和method来达到目的，但是各种尝试后发现并没有比较好的解决办法，要实现高亮所有选中行真的很麻烦。希望能添加对此功能的支持，谢谢

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.
