### ISSUE TITLE
Can [Feature Request] ride the lantern height?

### ISSUE THREAD

**Issue by axolo** [ElemeFE/element#12198]
### Existing Component
是

### Component Name
carousel

### Description
carousel height能否根据item的高度自适应？

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.

**Comment by ontheway0101** [comment]
@axolo 你好，我的图片style如下

> style="width: 100%;height: auto;max-width: 100%;max-height: 100%;"

使用你的方法获取到的clientHeight一直是0，不过在this.$refs.item[this.active]中显示clientHeight并不是0，请问这是什么原因？

谢谢
