### ISSUE TITLE
When [Bug Report] introduces message components on demand, an empty message prompt is automatically popped up when it enters the page.

### ISSUE THREAD

**Issue by TothingWay** [ElemeFE/element#12195]
### Element UI version
2.4.5

### OS/Browsers version
macOS 10.12.6 / chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://github.com/TothingWay/element-ui-message-bug](https://github.com/TothingWay/element-ui-message-bug)

### Steps to reproduce
使用 vue-cli 3.0.0-rc.10版本生成的项目按需引入 message 组件后，在刚进入页面时候会弹出一个空的，type 为 info 的消息提示

### What is Expected?
不自动弹出空的消息提示

### What is actually happening?
自动弹出一个空的，type 为 info 的消息提示，刷新一次页面弹一次

**Comment by jikkai** [comment]
https://github.com/TothingWay/element-ui-message-bug/blob/master/src/main.js#L8
这行是多余的
