### ISSUE TITLE
After [Bug Report] el-tree default-checked-keys changes, the previous checked nodes will not be removed.

### ISSUE THREAD

**Issue by gaoshijun1993** [ElemeFE/element#12194]
### Element UI version
2.4.5

### OS/Browsers version
win10/chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/w8nxscza/2/](https://jsfiddle.net/w8nxscza/2/)

### Steps to reproduce
1.设置default-checked-keys=[id1]
2.设置default-checked-keys=[id2]

### What is Expected?
 id1的node checked的状态应该为false
id2的node checked的状态应该为true

### What is actually happening?
 id1的node checked的状态依然为true
id2的node checked的状态为true

**Comment by jikkai** [comment]
`default-checked-key` 不是用来动态绑定节点选中数据的。

如果需要设置节点选中，请参照[文档](http://element-cn.eleme.io/#/zh-CN/component/tree#shu-jie-dian-de-xuan-ze)操作

**Comment by gaoshijun1993** [comment]
@jikkai 既然default-checked-key 不是用来动态绑定节点选中数据, 那么最好就不要在tree组件中watch它
