### ISSUE TITLE
[Bug Report] popover nested dialog ,when the dialog click, popover will be hide.

### ISSUE THREAD

**Issue by Mr-SPM** [ElemeFE/element#12207]
### Element UI version
2.4.5

### OS/Browsers version
win10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4532/](https://jsfiddle.net/mmx38qxw/4532/)

### Steps to reproduce
1. click the popover 
2. open dialog 
3. click dialog content
4. popover hide(i don't want)

### What is Expected?
keep popover show.

### What is actually happening?
popover hide

**Comment by jikkai** [comment]
In this case, you should use `trigger ="manual"` https://jsfiddle.net/mmx38qxw/4540/
