### ISSUE TITLE
[Select] bug 下拉框右侧图标点击无响应

### ISSUE THREAD

**Issue by chaohuaGH** [ElemeFE/element#1220]
### ElementUI version

1.0.2
### What is actually happening?
今天更新1.0.2发现<el-select>点击右侧的下拉三角不会出现下拉框，只有点击输入框，才会出现下拉框，不知道是不是个例。

**Comment by Kingwl** [comment]
应该不是 http://element.eleme.io/#/zh-CN/component/select 官方例子也没有

**Comment by aguegu** [comment]
童鞋们加油啊，我们要出活儿，面对测试MM的压力也很大的说～

**Comment by Leopoldthecoder** [comment]
Fixed in #1253
