### ISSUE TITLE
[Bug Report] From forms verify that rules within IE9 is wrong.

### ISSUE THREAD

**Issue by wipphj** [ElemeFE/element#12218]
### Element UI version
2.4.5

### OS/Browsers version
WIN10 / IE9

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/h5js4mbn/](https://jsfiddle.net/h5js4mbn/)

### Steps to reproduce
用IE9 或者把代码放到单文件中用IE9打开

### What is Expected?
控制台不报错，页面正常显示

### What is actually happening?
控制台报错 Vue编译期错误

**Comment by jikkai** [comment]
Element UI doesn't support Internet Explorer 9.

**Comment by wipphj** [comment]
谢谢,预期不是element ui 的问题.
参见  [issue](https://github.com/vuejs/vue/issues/8602)
