### ISSUE TITLE
[Bug Report] [NavMenu] select event only triggered when you click menu item?

### ISSUE THREAD

**Issue by creeperyang** [ElemeFE/element#12219]
### Element UI version
2.4.5

### OS/Browsers version
macOS 10.13.5/Chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/no-need/](https://jsfiddle.net/no-need/)

### Steps to reproduce
always

### What is Expected?
When default-active changed, "select" callback should be invoked.

### What is actually happening?
"select" callback doesn't get invoked.

https://github.com/ElemeFE/element/blob/7f2510f0f104fac7f064aa12acc622b0f8d2a719/packages/menu/src/menu-item.vue#L96-L100

https://github.com/ElemeFE/element/blob/7f2510f0f104fac7f064aa12acc622b0f8d2a719/packages/menu/src/menu.vue#L303

https://github.com/ElemeFE/element/blob/7f2510f0f104fac7f064aa12acc622b0f8d2a719/packages/menu/src/menu.vue#L251-L267

I checked the source code, and it looks like `select` only triggered when menu item clicked. Maybe it's better to trigger `select` when `activeIndex` changed.

**Comment by ziyoung** [comment]
I think it's not a bug. Supposing there's one input in a page as follows.
```
<input :value="value" type="text" @change="handleChange" />
```
If the binding value changes, `handleChange` isn't called.

**Comment by creeperyang** [comment]
In fact, It's still an acceptable choice that if `handleChange` get called in your situation.
