### ISSUE TITLE
[Feature Request] Implement popperAppendToBody in autocomplete component

### ISSUE THREAD

**Issue by buremba** [ElemeFE/element#12211]
### Existing Component
Yes

### Component Name
autocomplete

### Description
It's required if the input is in a component which close itself on `outsideClick`, I think that for convenience, all the components should have `popperAppendToBody` parameter that passes `append-to-body` to the inside popover.

**Comment by ziyoung** [comment]
@buremba I don’t quite understand what you mean. Can you provide a demo or explain more clearly?

**Comment by buremba** [comment]
@ziyoung It's actually quite similar to https://github.com/ElemeFE/element/issues/11176 If we use autocomplete input in a popper, the autosuggestion div will be appended to body so when we click one of the items the popover closes without actually selecting the value.
