### ISSUE TITLE
[feature enhance] [el-table] formatter don't work in template

### ISSUE THREAD

**Issue by chenEdgar** [ElemeFE/element#12215]
### Element UI version
2.4.3

### OS/Browsers version
chrome Version 67.0.3396.99 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/8fac5psb/9/](https://jsfiddle.net/8fac5psb/9/)

### Steps to reproduce
just see demo in jsfiddle

### What is Expected?
in table component, it should be work when  formatting the table-cell using formatter attribute which is wrapped in template

### What is actually happening?
it failed

**Comment by jikkai** [comment]
`formatter` does not work in slot. If you want, you can manually format it like this demo: https://jsfiddle.net/8fac5psb/13/

**Comment by chenEdgar** [comment]
thanks. it works well by this way.
