### ISSUE TITLE
Vue.set is called in [Bug Report] el-table expand-change. The first content will not start

### ISSUE THREAD

**Issue by maxxiao** [ElemeFE/element#12217]
### Element UI version
0.1.0

### OS/Browsers version
chrome 67.0.3396.99

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/r50eu8j6/](https://jsfiddle.net/r50eu8j6/)

### Steps to reproduce
第一次点击expand
内容不展开

### What is Expected?
第一次点击expand
内容展开

### What is actually happening?
第一次点击expand
内容不展开

**Comment by jikkai** [comment]
不推荐在这里修改 row 的数据，如有需要应该直接改数据源：https://jsfiddle.net/r50eu8j6/9/
