### ISSUE TITLE
[Feature Request] Swap table orientation (swap columns and rows)

### ISSUE THREAD

**Issue by c-ampferer** [ElemeFE/element#12224]
### Existing Component
Yes

### Component Name
Table

### Description
I would like to swap the table orientation (swap columns and rows).
The table header should be on the left side.
Currently I have the following table:
```
 A | B | C 
-----------
 1 | 2 | 3
 4 | 5 | 6
```
The feature should allow to display the table like below:
```
 A  |  1   4 
--------------
 B  |  2   5
--------------
 C  |  3   6
```
Thank you, we love Element-UI!

**Comment by Frankstar** [comment]
+1     
would be a nice feature
