### ISSUE TITLE
Element是否可以直接修改默认样式的颜色？

### ISSUE THREAD

**Issue by anshengme** [ElemeFE/element#1222]
如图，感觉这两个颜色都不太搭配，我怎么才能自定义颜色呢？
![qq 20161119160716](https://cloud.githubusercontent.com/assets/16428340/20454148/581099a4-ae72-11e6-874c-66fb70013709.png)

**Comment by QingWei-Li** [comment]
pagination 的白色背景色是 bug 应该要去掉

如何自定义主题（主题色）请参考文档「自定义主题」一章
