### ISSUE TITLE
[Bug Report] $alert cannot be performed continuously

### ISSUE THREAD

**Issue by wfesorg** [ElemeFE/element#12221]
### Element UI version
2.4.5

### OS/Browsers version
windows10/chrome60

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/L25yth8r/1/](https://jsfiddle.net/L25yth8r/1/)

### Steps to reproduce
app.$alert('2', '1'),app.$alert('4', '3');

### What is Expected?
show two alert dialog

### What is actually happening?
only show last alert dialog

**Comment by jikkai** [comment]
Try to add `this.$nextTick` https://jsfiddle.net/L25yth8r/3/

**Comment by wfesorg** [comment]
https://jsfiddle.net/L25yth8r/9/
in fact, i want to use $alert by "for loops"
