### ISSUE TITLE
[Feature Request] el-tabs searchable tab-panes

### ISSUE THREAD

**Issue by legreco** [ElemeFE/element#12230]
### Existing Component
Yes

### Component Name
el-tabs

### Description
It will be great if you can have an option to search for tab pane label. currently i have an el-tabs with 30  el-tab-pane, it can be cumbersome for the user to look at 30 tab-pane name to finally find the right tab-pane.

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.
