### ISSUE TITLE
Can the numbers displayed in the [Feature Request] InputNumber component be right-justified or set to the right way?

### ISSUE THREAD

**Issue by cuivip** [ElemeFE/element#12232]
### Existing Component
是

### Component Name
InputNumber 

### Description
InputNumber  这个组件中显示的数字是否可以右对齐，或是可以设置对其方式
数值组件中的数字右对齐，比较符合习惯

**Comment by wacky6** [comment]
https://jsfiddle.net/ja4s2cko/
