### ISSUE TITLE
The nodes added by [Bug Report] tree control through the append method will dissolve other sub nodes.

### ISSUE THREAD

**Issue by 186A8** [ElemeFE/element#12231]
### Element UI version
2.4.5

### OS/Browsers version
windows10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
重现地址是假的，描述一下问题：
tree控件通过append方法增加的节点会把其他子节点搞消失了

### What is Expected?
正常情况append增加的子节点应该排在其他子节点之后，而不是只剩下增加的子节点

### What is actually happening?
tree控件通过append方法增加的节点会把其他子节点搞消失了

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
