### ISSUE TITLE
[Bug Report] in iframe page, @click.native="location.href='a.html'" not record history

### ISSUE THREAD

**Issue by otizis** [ElemeFE/element#12240]
### Element UI version
2.4.5

### OS/Browsers version
win10/firefox61

### Vue version
2.5.17

### Reproduction Link
[http://otizis.github.io/elementCase](http://otizis.github.io/elementCase)

### Steps to reproduce
1. click "goto start.html" in iframe init.html
2. click "pageX.html" in iframe start.html
3. click "goBack" in iframe pageX.html, page back to init.html , not start.html

### What is Expected?
at stage 3 , click "goback" in iframe pageX.html, back to start.html.

### What is actually happening?
after click "goback" in iframe "pageX.html", page back to "init.html".

if you  click "pageA.html" in stage 2, click "goback" in pageA.html, page back to start.html.
same page will ok , when open init.html directly not in iframe.

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by otizis** [comment]
这是el-radio-group组件的bug 啊，挂在此组件上的click事件影响history记录了啊
我写了一个简易的button组件，是不会影响click事件记录history的，看我的例子网页。
现在通过 pageY的写法可以绕过此bug
```
           <el-radio-group value="">
                <el-radio-button label="X" @click.native="goto('pageX.html')" >pageX.html</el-radio-button>
                <el-radio-button label="Y"  >
                      <span @click="goto('pageY.html')">pageY.html</span>
                </el-radio-button>
            </el-radio-group>
```
