### ISSUE TITLE
[Bug Report] tree node selection problem

### ISSUE THREAD

**Issue by Gavin-zsl** [ElemeFE/element#12247]
### Element UI version
2.4.5

### OS/Browsers version
Google Chrome 版本 67.0.3396.99（正式版本） （64 位

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4634/](https://jsfiddle.net/mmx38qxw/4634/)

### Steps to reproduce
数据渲染，在父节点勾选状态下，就算子节点未保存也会出现全部选中的情况，items: [{'label': '测试', 'name': 'test', 'children': [{'label': '测试2','name': 'test2' }, {'label': '测试3','name': 'test3' }, {'label': '测试4','name': 'test4' }] }]。实际我需要渲染的只有['test', 'test2']这test2节点，但是因为前期保存了父节点的名称，导致全部选中了。

### What is Expected?
因为勾选结果是保存在数据库里面，前期是全部勾选状态，后期增加新的子节点希望能识别选中效果。

### What is actually happening?
tree联动的时候，如果父节点被选中过的话，子节点在渲染也会默认选择。但是实际上新增加的子节点是不存在数据库中的。

**Comment by jikkai** [comment]
这不是一个 bug，树就是这样设计的，父节点选中自然意味着子节点全选。

**Comment by Gavin-zsl** [comment]
这个有什么解决办法吗，后期子节点的数肯定是一直在增加的，如果都是默认全选中的话，权限控制就会出现错乱

**Comment by q27488** [comment]
但是问题是，提交的时候，节点不是全选的，也会将父节点的id给获取到。
目前看到的处理方法是 自己做数据过滤和识别：https://blog.csdn.net/deng1456694385/article/details/83515057
