### ISSUE TITLE
[Feature Request] Why does ElInputNumber not specify type attribute?

### ISSUE THREAD

**Issue by ochi51** [ElemeFE/element#12245]
### Existing Component
Yes

### Component Name
ElInputNumber

### Description
I think that the type attribute of ElInputNumber should be `number`.
However, ElInputNumber does not specify the type of props of ElInput, so the type attribute is `text`.

I want ElInputNumber to specify the type attribute to `number` or to specify type as props.

**Comment by ziyoung** [comment]
@ochi51 if the type of input is `number`, the browser may opt to provide stepper arrows. The style of input is inconsistent between browsers. We can also [hide step arrows by CSS](https://css-tricks.com/snippets/css/turn-off-number-input-spinners/), but it works on web-kit browsers.
