### ISSUE TITLE
[Bug Report] inputNumber data cannot be displayed synchronously

### ISSUE THREAD

**Issue by yuminjustin** [ElemeFE/element#12244]
### Element UI version
2.4.5

### OS/Browsers version
win10/chromium 63

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/L3w6mrt2/2//](http://jsfiddle.net/L3w6mrt2/2//)

### Steps to reproduce
链接中的示例：手动输入1.6，进入绑定的change事件中，把组件state改成非浮点数。由于初始值就是1，输入的1.6，使用Math.floor的方法将值改成了1，组件的test实际为1，但界面依然是1.6。除非另外输入2.6，界面就会显示成2。

### What is Expected?
其实我就是新作一个禁止输入浮点数的功能

### What is actually happening?
当change事件中经过处理后的值跟原来的值相同时，无法变更界面显示。

**Comment by yuminjustin** [comment]
刚才尝试一下把change事件做了一下改变：

            handleNum(value) {
                this.test = value * 100;
                setTimeout(() => {
                    if (!/^[1-9]\d*$/.test(value)) {
                        this.test = Math.floor(value);
                    }
                }, 10)

            }

可以达到目的，但是感觉这样太low了

**Comment by ziyoung** [comment]
只输入整数吗？试试设置 precision 属性。https://jsfiddle.net/zhiyang/yt6cm0e1/

**Comment by yuminjustin** [comment]
@ziyoung 你的例子的确可以用，但是很奇怪 precision = 0
官方文档里面：http://element-cn.eleme.io/#/zh-CN/component/input-number
![image](https://user-images.githubusercontent.com/8414340/43711699-2f17ec02-99a6-11e8-9041-a7cdfb8098ef.png)
 precision的值必须是一个正整数
。。。。。。。

**Comment by ziyoung** [comment]
@yuminjustin 文档描述的有问题😅，precision 应该是整数才对。
https://github.com/ElemeFE/element/blob/8de71d0c91929f6200860c1b42098ea3f8fa177c/packages/input-number/src/input-number.vue#L94-L97
