### ISSUE TITLE
[Bug Report] ElTable inside ElTab doesn't calculate the column width properly

### ISSUE THREAD

**Issue by bgadiel** [ElemeFE/element#12242]
### Element UI version
2.4.5

### OS/Browsers version
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/qhxvLa0k/33/](https://jsfiddle.net/qhxvLa0k/33/)

### Steps to reproduce
switching back and forth between 'Profile' tab and Industry' tab

### What is Expected?
The width of the table is being calculated dynamically using clientWidth.
The table width will be the same for all tabs

### What is actually happening?
The table width is not being calculated correctly for the second tab (probably because the table is not being rendered yet?)
Issue resembles #10692

**Comment by jikkai** [comment]
I'm afraid that this not a bug. When the Tab is completely rendered, the second panel has `display: none`. Which means its `clientWidth` is `0`, and the Table width can't be calculated correctly at this time.

Maybe `lazy` attribute will work for you.
https://jsfiddle.net/qhxvLa0k/34/

**Comment by bgadiel** [comment]
yap, lazy did the trick!
btw - how lazy affects clientWidth?
thanks.
