### ISSUE TITLE
[Bug Report] After insert into the dialog, it doesn't play after, doesn't

### ISSUE THREAD

**Issue by 15klli** [ElemeFE/element#12253]
### Element UI version
2.4.5

### OS/Browsers version
Chrome  67.0.3396.99 (64bit)

### Vue version
2.5.17
### Compent version
* VideoJs V6.6.2
* Element-UI v2.4.5
### Reproduction Link
[https://jsfiddle.net/15klli/h63s104c/14/](https://jsfiddle.net/15klli/h63s104c/14/)

### Steps to reproduce
1. 点击“打开dialog”--click the link to open dialog
2. 点击 poster中间的播放按钮（无反应）  --  click the Play button on the center of the poster(it doesn't works)
3. 点击 “触发提示” 按钮 （有反应） -- click the toggle noticiation （it works.）

### What is Expected?
点击 poster 中间的播放按钮可以播放 -- After clicking the Play button on the center of the poster, the video begins to play.

### What is actually happening?
点击 poster中间的播放按钮（无反应）  --  click the Play button on the center of the poster(it doesn't works)

**Comment by ziyoung** [comment]
@15klli 不像是 element-ui 的 bug。我不把播放器放在 dialog 里面，点击之后还是无法播放。https://jsfiddle.net/zhiyang/h63s104c/20/

**Comment by 15klli** [comment]
@ziyoung 把`id="app"的``</div>`移到 视频块`id="vueapp"` 的前面就可以点击打开了 https://jsfiddle.net/15klli/h63s104c/24/
