### ISSUE TITLE
When [Bug Report] el-card nested el-table, the window width is bigger.

### ISSUE THREAD

**Issue by droidXZ** [ElemeFE/element#12254]
### Element UI version
2.4.5

### OS/Browsers version
chrome 68.0.3440.84

### Vue version
2.5.17

### Reproduction Link
[https://github.com/droidXZ/element-issue](https://github.com/droidXZ/element-issue)

### Steps to reproduce
1.使用脚手架新建一个vue项目，引入element。
2.将HelloWorld默认的代码全部删除，在HelloWorld中拷贝el-card的基本用法到相应的位置。
3.拷贝el-table的固定表头用法，嵌套到刚刚拷贝的el-card中。
4.将style中.box-card的width设置为100%。
5.在App中使用HelloWorld的标签，并添加style float:left。

### What is Expected?
一个正常的表格。

### What is actually happening?
表格的宽度不断变大，导致窗口也不断变大。

**Comment by jikkai** [comment]
Duplicate of #11420
