### ISSUE TITLE
[Bug Report] notification bug

### ISSUE THREAD

**Issue by w514986768** [ElemeFE/element#12258]
### Element UI version
2.4.5

### OS/Browsers version
win7

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/eywraw8t/244460/](http://jsfiddle.net/eywraw8t/244460/)

### Steps to reproduce
when the notification is show two, one is success, one is error, the styles is confused;

### What is Expected?
the styles is right

### What is actually happening?
the styles is confused

**Comment by wacky6** [comment]
Use `$nextTick` for second notification. Otherwise there is no way to compute rendered height of the first notification.

http://jsfiddle.net/feckh1sg/

**Comment by kevrousso** [comment]
@wacky6 Would there be any way of adding a delay property on the notification itself? I am using the notification everywhere in my app by a wrapper I made, so the nextTick workaround would not work in my case.

I tried to delay the notification myself by doing something like this:
```js
let count = 0;
export default {
  _notify({ title = '', message = '', type = 'info', autoClose = true }) {
    this.count++;

    _.delay(() => {
      Vue.prototype.$notify({
        title,
        message,
        type,
        dangerouslyUseHTMLString: true,
        offset: 60,
        duration: autoClose ? 4500 : 0
      });
      this.count--;
    }, count * 300);
  }
};
```
But with this, I am not able to return the instance of the notification since the invocation is delayed, thus I don't have access to the instance methods like `close`.

**Comment by kevrousso** [comment]
I noticed that the Popper have this kind of behavior I am looking for:
http://element.eleme.io/#/en-US/component/popover
open-delay | delay of appearance when trigger is hover, in milliseconds

Would it be possible to add a parameter like this one to the Notification?

**Comment by wacky6** [comment]
You can use promise and setTimeout to do so.

**Comment by kevrousso** [comment]
Got it working finally, for anyone who might want to do this, this is how I solved it:
```js
// wrapper
let count = 0;
export default {
  _notify({ title = '', message = '', type = 'info', autoClose = true }) {
    count++;
    return new Promise((resolve, reject) => {
      _.delay(() => {
        resolve(Vue.prototype.$notify({
          title,
          message,
          type,
          dangerouslyUseHTMLString: true,
          offset: 60,
          duration: autoClose ? 4500 : 0
        }));
        count--;
      }, count * 300);
    })
  }
};

// usage
const notif = await this._notify({ title: 'Title', message: 'Message' });
```
