### ISSUE TITLE
The value-key attribute value of [Bug Report] el-select is highlighted except value.

### ISSUE THREAD

**Issue by yanping-jessie** [ElemeFE/element#12250]
### Element UI version
2.4.5

### OS/Browsers version
win7 64位 chrome[67.0.3396.79]

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/48fnk1sm/4/](https://jsfiddle.net/48fnk1sm/4/)

### Steps to reproduce
1、el-select的value设置为一个对象
2、设置value-key为唯一值的属性名b
3、随意选中一个值，所有的选项都会是高亮的

### What is Expected?
当前选中值为高亮

### What is actually happening?
所有的选项都会是高亮的

**Comment by wacky6** [comment]
https://jsfiddle.net/48fnk1sm/6/

**Comment by yanping-jessie** [comment]
😂😂Thanks for your help~
