### ISSUE TITLE
[Bug Report] displays exceptions when it uses a filter function in a table with a fixed column and does not match the data.

### ISSUE THREAD

**Issue by gorkys** [ElemeFE/element#12257]
### Element UI version
2.4.5

### OS/Browsers version
windowns/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/w1mo38bx/5/](https://jsfiddle.net/w1mo38bx/5/)

### Steps to reproduce
点击“省份”表头，选中筛选项"省份"，点击“筛选”。

### What is Expected?
如果所筛选项没有匹配到对应数据，即显示表格初始状态：无数据(显示一行)。另：筛选中的重置是否可以给出一个回调方法。

### What is actually happening?
在拥有固定列的表格中，筛选时没有匹配到对应数据时，固定列的显示有异常。

**Comment by jikkai** [comment]
这是有意为之的。“无数据”意味着表格不存在源数据，而不是经过筛选后没有得到匹配的数据。

**Comment by gorkys** [comment]
那这种显示问题是算不上bug么？dome中的筛选项是随意弄的，如果是正常情况下筛选了一种状态，但这个状态确实是在当前页没有。这种显示问题需要如何解决？dome中的列并不算多，如果多几列的话，这种显示异常会导致后面的列被固定列覆盖住。

**Comment by gorkys** [comment]
@jikkai 那这种显示问题是算不上bug么？dome中的筛选项是随意弄的，如果是正常情况下筛选了一种状态，但这个状态确实是在当前页没有。这种显示问题需要如何解决？dome中的列并不算多，如果多几列的话，这种显示异常会导致后面的列被固定列覆盖住。

**Comment by my9074** [comment]
@jikkai @gorkys 我理解应该暴露个类似 `slot="filterEmpty"`，通过判断 `isFilter && state._data === []` 来显示过滤为空时的显示信息
