### ISSUE TITLE
[Bug Report] Operate with the same el-slider range values, it becomes NaN

### ISSUE THREAD

**Issue by sdr0x07b6** [ElemeFE/element#12252]
### Element UI version
2.4.5

### OS/Browsers version
macOS 10.13.6, Google Chrome 68.0.3440.84

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/waq1dg4L/](https://jsfiddle.net/waq1dg4L/)

### Steps to reproduce
The values of min and max are the same.
Move the slider to become NaN.

For example, at the EC site, there is a slider UI that narrows down items by price.
The sliders min and max are the lowest and highest value of the item price.
When all items are the same price, min and max are the same.
In this case, I can think of disabling the slider, but it should be fundamentally improved.

### What is Expected?
Min and max must be set for both ends of the slider.

### What is actually happening?
The value becomes NaN.
Whatever the specification is, NaN should be avoided.

**Comment by jikkai** [comment]
Yep, `NaN` must be avoided, so I'll fix for that. But min and max point can't be set for both ends of the slider, this is by design. 😞
