### ISSUE TITLE
Button loading状态建议

### ISSUE THREAD

**Issue by miaosun009** [ElemeFE/element#1225]
### Reproduction Link

在项目使用的过程中，发现现在button的loading状态有一个不合理的情况， 通常来说，我们用一个逻辑型的data来控制按钮的loading状态， 如果一个页面只有一个按钮的时候，这没什么关系， 但是如果一个页面有很多按钮，并且可能同时若干个按钮会出现loading状态的情况下，这就有点无能为力了（比如，我点击按钮1发起了一个ajax请求，然后让按钮进入loading状态，等ajax请求完后才消除加载状态， 但在这个时候，用户可能会马上点击了按钮2发起另外一个请求，按钮也需要进入loading状态，而这个时候状按钮1的请求还没有完成，loading状态还不能消除。），虽然通过重新封装button组件可以实现，但是感觉还是太麻烦了， 希望官方可以完善一下这个功能

**Comment by Kingwl** [comment]
这个已经属于业务逻辑了 没法放到通用的组件里
其实实现起来也很简单
一个computed + 一个object就行

**Comment by miaosun009** [comment]
能具体说个例子么，不是特别明白，望答复。

**Comment by Leopoldthecoder** [comment]
请通过多个变量或一个对象的不同属性来自行解决。
