### ISSUE TITLE
Input 输入框和原生输入框的异同

### ISSUE THREAD

**Issue by jfb** [ElemeFE/element#1226]
### ElementUI version
 1.0.2

### OS/Browers version
win10/ Firfox, IE10, Chrome

### Vue version
 2.0.7

### Reproduction Link
https://jsfiddle.net/z9Ld3zra/1/

### Steps to reproduce

相比原生输入框，`.lazy`特性不支持，同时不支持 `keyup`

**Comment by Kingwl** [comment]
1. 确实不支持.lazy 因为input和change是同时emit的
2.https://jsfiddle.net/kingwl/z9Ld3zra/2/  请使用keyup.native以及检查拼写

**Comment by jfb** [comment]
@Kingwl 谢谢，可以关闭了。这些最好文档写下，下午这里浪费了很久的时间。

**Comment by Kingwl** [comment]
@Leopoldthecoder
