### ISSUE TITLE
[Bug Report] The Chrome form automatic fill does't work when using elementui's form component

### ISSUE THREAD

**Issue by LIPSong** [ElemeFE/element#12267]
### Element UI version
2.4.5

### OS/Browsers version
MacOS 10.13.6

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4685/](https://jsfiddle.net/mmx38qxw/4685/)

### Steps to reproduce
Open JSFiddle to input username and password, then tap enter.    

### What is Expected?
After I do the above operator in Chrome,  I open Chrome again username and password should be auto filled, but with elementui form input component, Chrome doesn't.
Something doesn't like Antd, when I try to implement the similar function using Antd form, the Chrome will auto fill the input fields and input will get yellow background color. I think this may be a elementui form data binding bug，which prevent Chrome default behavior

### What is actually happening?
The Chrome auto fill doesn't work.

**Comment by ziyoung** [comment]
@LIPSong Chrome will only save the autocomplete information on submit. Clicking the submit button doesn't trigger the form submit event. https://stackoverflow.com/questions/19345879/input-autocomplete-on-does-not-work-with-chrome-is-it-a-bug

**Comment by LIPSong** [comment]
@ziyoung Senior！ "Please provide ID to your input variable" ,this helps! Thank you！What a beautiful trick！
