### ISSUE TITLE
[Bug Report] date selector source code picker.vue exists error reporting

### ISSUE THREAD

**Issue by msidolphin** [ElemeFE/element#12263]
### Element UI version
2.4.5

### OS/Browsers version
win10 / chrome 68.0.3440.84

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
picker.vue ranged属性会报错 
Cannot read property 'indexOf' of undefined

### What is Expected?
不会报错。。。。

### What is actually happening?
。。。

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by msidolphin** [comment]
@jikkai 这个我给不了重现链接，我发现修改picker.vue源码会报错，所以才提了这个
