### ISSUE TITLE
当两个select联动，第一个select的onchange事件触发数据加载，填充再第二个select上面的时候，如果第二个select又存在表单验证的情况，会导致第二个select选不中（表象是选不中值，实际上是选中了，change事件也触发了，但是选中的值再select上面展示不出来。）

### ISSUE THREAD

**Issue by yinwanli** [ElemeFE/element#12266]
当两个select联动，第一个select的onchange事件触发数据加载，填充再第二个select上面的时候，如果第二个select又存在表单验证的情况，会导致第二个select选不中（表象是选不中值，实际上是选中了，change事件也触发了，但是选中的值再select上面展示不出来。）

**Comment by yinwanli** [comment]
site_id: [{ required: true, message: '请选择名称', trigger: 'change'}]。多次试验，发现是表单验证导致的延迟。这里的二级联动说的是第一个select选中数据，通过change事件发起ajax请求，得到的数据放到第二个select上面。第二个select又存在必填的表单验证的时候，就会导致select表现出选不中数据的情况。

**Comment by Hunmanlife** [comment]
有解决方法吗？
