### ISSUE TITLE
[Bug Report] Draggable tree node remove problem

### ISSUE THREAD

**Issue by ceyhunkerti** [ElemeFE/element#12270]
### Element UI version
2.4.5

### OS/Browsers version
Ubuntu / Chrome Version 68.0.3440.84 (Official Build) (64-bit)

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/p0Lo8q45/1/](https://jsfiddle.net/p0Lo8q45/1/)

### Steps to reproduce
1 - drop a node to a different parent
2 - remove the dropped node in step 1

### What is Expected?
Node should be removed with the remove method

### What is actually happening?
node is not being removed

**Comment by ceyhunkerti** [comment]
there is a node key, `node-key="id"`
docs says pass the data to remove function, i also looked up the source and it is also possible with 
node key as well. that's why i am passing `draggingNode.data.id`
am i still missing something ?

**Comment by ceyhunkerti** [comment]
btw. I can remove a node before a drag-drop op. but not after

**Comment by ziyoung** [comment]
@ceyhunkerti 
```js
handleDrop(draggingNode, dropNode, dropType, ev) {
  this.$refs.tree.remove(draggingNode.data);
}
```
