### ISSUE TITLE
Tree setCheckedNodes 怎么用？我已经设置了node-key

### ISSUE THREAD

**Issue by ruizhou8888** [ElemeFE/element#1228]
Tree setCheckedNodes 怎么用？我已经设置了node-key 然后this.$refs.menuTree.setCheckedNodes([this.treeData[0]]); 
传进去的数组对象是直接获取的树上的数据也不行？

**Comment by CharkeyQK** [comment]
furybean给我的例子，我顺手放在我的repo [Tree.vue](https://github.com/CharkeyQK/vue-demo/blob/master/src/components/Tree.vue)

**Comment by furybean** [comment]
重复了，统一在 #1236 里面处理吧。
