### ISSUE TITLE
[Feature Request] set lazy loading for el-tree, can you expand the node through the load function when initialization?

### ISSUE THREAD

**Issue by DAHU123** [ElemeFE/element#12287]
### Existing Component
是

### Component Name
Tree 树形控件

### Description
<el-tree
                    class="me_self_tree me_distributeTree"
                    node-key="treeId"
                    :data="treeData"
                    ref="treeL"
                    :indent="25"
                    :props="props1"
                    :load="loadNode1"
                    lazy
                    :highlight-current="true"
                    :expand-on-click-node="false"
                    @node-click="showQudao">
                    <span class="custom-tree-node" slot-scope="{ node, data }">
                        
                        <span>{{ node.label }}</span>
                    </span>
                </el-tree>
上面的是我对tree的一些初始化设置

现在我的问题就是我在loadNode1函数中，获取初始化数据，获取到了三个层级的节点数据，即一级节点数据＞二级节点数据＞三级节点数据，可不可以把这三个层级的数据所对应的节点都统统展开？但是初始化之后，没有办法去展开一级节点下的二级节点，二级节点对应的数据也是没办法渲染到页面中的．

**Comment by ziyoung** [comment]
懒加载时，节点数据是一段段加载的。你的意思是一次请求就把所有的数据获取了？那样的话，为什么要懒加载呢？

**Comment by DAHU123** [comment]
有一部分节点是一次性获取数据，这个是出于业务层面的需求，但是其他节点要通过懒加载来获取数据

**Comment by ziyoung** [comment]
也就是说：既有懒加载的，也有非懒加载的。那不如试试不适用懒加载，而是自己手动在节点绑定事件，手动添加节点呢？

**Comment by DAHU123** [comment]
就只在页面初始化的时候加载了三层节点的数据，并且要全部展开，其他的节点是需要设置懒加载的

**Comment by ziyoung** [comment]
可以这样试试：不使用懒加载，设置 default-expand-all 为 true，在第三层节点绑定点击事件，[手动创建树节点](https://element.faas.ele.me/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong)。

**Comment by DAHU123** [comment]
建议给Node这个节点数据绑定一个load方法，可以用来手动加载当前节点的子级节点．

**Comment by ziyoung** [comment]
我们讨论一下。issue 先关了。
