### ISSUE TITLE
[Bug Report] Resize event doesn't fire up when decreasing size (Grid-Layout)

### ISSUE THREAD

**Issue by clementdubois** [ElemeFE/element#12285]
### Element UI version
2.4.5

### OS/Browsers version
Ubuntu / Firefox developper edition

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4740/](https://jsfiddle.net/mmx38qxw/4740/)

### Steps to reproduce
- 1 : Embed a table element in a grid layout container 
- 2 : Decrease the size of the windows

### What is Expected?
The table should decrease in size to fit the grid container

### What is actually happening?
The table keep his size.
NB: If you increase the size of the windows, the table increase in size.

Digging in the lib code it seems that the "resize-observer-polyfill" doesn't trigger the resize event when windows size is decreasing

**Comment by firesh** [comment]
Why not flex?

**Comment by bcruddy** [comment]
Workaround:

```
.el-table__header,
.el-table__body,
.el-table__empty-block {
    max-width: 100%;
    width: auto !important; /* override inline width with !important */
}
```

**Comment by CreateClear** [comment]
@bcruddy hi, It works very well when windows size is decreasing but the fixed columns do not work properly

**Comment by CreateClear** [comment]
There is a solution here 
[https://github.com/ElemeFE/element/issues/3320](url)

**Comment by ineghi** [comment]
@CreateClear Hi, the issue seems to be deleted. Do you remember what the solution was ?
