### ISSUE TITLE
[Feature Request] Slider component increments MouseMove event, step has time unit, time 30

### ISSUE THREAD

**Issue by benmo1602** [ElemeFE/element#12288]
### Existing Component
否

### Component Name
Slider

### Description
Slider component increments mousemove event , step has time unit, for example 30 milliseconds

The drag component of the slider component is sometimes used to control the change of the image size. Only the change event makes the image change unfriendly. If the input is added or subtracted, the value of the step is too small. For example, the image 100 is increased by 500.

**Comment by jikkai** [comment]
I can't fully understand what you need. Could you provide us more details?

**Comment by caokunyu** [comment]
The slider module currently only has a change event, how to get the current value during the drag and drop process.
