### ISSUE TITLE
Can [Bug Report] step Steps operation logic be modified?

### ISSUE THREAD

**Issue by Mrcxt** [ElemeFE/element#12282]
### Element UI version
2.4.5

### OS/Browsers version
Mac/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击<下一步>，已完成的步骤和正在进行的步骤之间的横线是否应该是已完成状态

### What is Expected?
<已完成的>步骤和<正在进行的>步骤之间的横线应该是<已完成状态>,也就是应该改变状态，而不是<已完成的>步骤和<已完成的>步骤之间的横线才会变成<已完成状态>

### What is actually happening?
<已完成的>步骤和<正在进行的>步骤之间的横线未发生变化

**Comment by jikkai** [comment]
We have no plan to change it because this is by design.
