### ISSUE TITLE
[Feature Request] el-submenu Title support for dynamic modification

### ISSUE THREAD

**Issue by SeanBurt** [ElemeFE/element#12286]
### Existing Component
是

### Component Name
NavMenu

### Description
el-submenu title set with static text, but i want to set title by dynamic vue data variable. so, how can i do?

**Comment by ziyoung** [comment]
https://jsfiddle.net/zhiyang/cm79gdr0/3/
```vue
<el-menu-item index="3">
    <i class="el-icon-document"></i>
    <span slot="title">{{title}}</span>
</el-menu-item>
```

**Comment by jikkai** [comment]
https://vuejs.org/v2/guide/syntax.html

```html
<template slot="title">{{title}}</template>
```

**Comment by SeanBurt** [comment]
@ziyoung thx, i use vue directive 'v-text', but it can't work. so, why?

**Comment by jikkai** [comment]
@SeanBurt https://github.com/vuejs/vue/issues/6988
