### ISSUE TITLE
Can [Bug Report] navigation expand the menu with click?

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#12298]
### Element UI version
2.4.5

### OS/Browsers version
WIndow 10 / Chrome 64

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4763/](https://jsfiddle.net/mmx38qxw/4763/)

### Steps to reproduce
导航可以用click进行菜单的展开吗？

### What is Expected?
导航可以用click进行菜单的展开吗？

### What is actually happening?
导航可以用click进行菜单的展开吗？

**Comment by jikkai** [comment]
`menu-trigger` 设置为 `click` 即可，文档里漏了这边补一下

**Comment by LemonAppleMo** [comment]
好的 谢谢
