### ISSUE TITLE
[Feature Request] header selection for el-table-column

### ISSUE THREAD

**Issue by acodercat** [ElemeFE/element#12295]
### Existing Component
Yes

### Component Name
el-table-column

### Description
el-table-column的表头筛选filters是否可以支持通过API接口向后台获取数据，然后分页。而不是只是筛选当前页的数据。如果通过filter-method来实现的话有一个问题，就是会执行多次执行filterHandler，其实我就想获取每次选择了哪些值，然后发送给后端然后获取数据。

**Comment by jikkai** [comment]
使用 `filter-change` 事件处理：https://jsfiddle.net/2wh59ctj/3/

**Comment by ziyoung** [comment]
你请求数据，动态改变 filters 的值不也是可以的吗。

**Comment by acodercat** [comment]
好的感谢，但是这样的话其实我的filter-method是没有的，但是这个方法又必须加上。怎么办呢

**Comment by niugengyun** [comment]
是的 这确实是有问题 怎么解决呢
