### ISSUE TITLE
[Bug Report] DatePicker日期组件设置type="daterange"后选择不了年和月

### ISSUE THREAD

**Issue by haizhilin2013** [ElemeFE/element#12306]
### Element UI version
2.3.6

### OS/Browsers version
win10

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
DatePicker日期组件设置type="daterange"后选择不了年和月了
![image](https://user-images.githubusercontent.com/5070345/43883062-78334522-9be4-11e8-95d9-41161be8305c.png)

### What is Expected?
可以快速地选择年和月

### What is actually happening?
不能选择年和月

**Comment by wacky6** [comment]
设计上就是这样。

**Comment by jxy0724** [comment]
有解决办法可以做到用daterange仍然可以选择年和月么？现在项目有这样的需求 @wacky6
