### ISSUE TITLE
[Feature Request] when el-tree does not set lazy loading, does it cause errors to change the state of lazy in store to a single node node? Node.store.lazy = true

### ISSUE THREAD

**Issue by DAHU123** [ElemeFE/element#12300]
### Existing Component
是

### Component Name
 Tree 树形控件

### Description
                            node.store.lazy = true ;
                            node.updateLeafState();
调用上面这两行代码的一个背景如下:
在el-tree这个组件初始化的时候，没有设置懒加载，但是在对某个节点的后续操作中调用了上面的两行代码，这样子做的目的是为了让此node节点的箭头图标（就是控制此节点展开与折叠的图标）显示出来，这样子做会不会引发其他的错误？

**Comment by jikkai** [comment]
文档中未注明的 workaround 手段无法保证其可靠性。

你之前的需求我们已经在评估了，如果有更新会在之前的 issue 中跟进，请勿滥用 issues。

**Comment by DAHU123** [comment]
大神我的这个需求你们现在评估的怎么样了?有没有考虑要加这个特性呀?
