### ISSUE TITLE
[Bug Report] date-time-picker by the button "now" can select disabled date

### ISSUE THREAD

**Issue by r27-cmcs** [ElemeFE/element#12303]
### Element UI version
2.4.5

### OS/Browsers version
chrome 67

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/3zgLx1mc/3/](https://jsfiddle.net/3zgLx1mc/3/)

### Steps to reproduce
Set the the property disabledDate of picker-options,today can't be selected.Then click the button "now"

### What is Expected?
today can't be selected

### What is actually happening?
today be selected

**Comment by wacky6** [comment]
https://jsfiddle.net/8fvrmhcj/

**Comment by r27-cmcs** [comment]
I don't wanna today can be selected.

**Comment by wacky6** [comment]
Well. In that case, I can't select today in your jsfiddle. You may need to upload a screen capture.

**Comment by r27-cmcs** [comment]
[https://jsfiddle.net/8fvrmhcj/2](https://jsfiddle.net/8fvrmhcj/2/)
Ok,in this jsfiddle,u can find can't select today,but when i click the button "now" on bottom of panel,today be selected.
![image](https://user-images.githubusercontent.com/40757092/43956600-692d1604-9cd7-11e8-9a13-16bd1093c95c.png)

**Comment by wacky6** [comment]
This is an edge case, you can: https://jsfiddle.net/gbv93m25/
