### ISSUE TITLE
[Bug Report] window operating system, table components, setting show-summary, the scroll bar of the fixed column can not be dragged normally.

### ISSUE THREAD

**Issue by scaleryvan** [ElemeFE/element#12309]
### Element UI version
2.4.5

### OS/Browsers version
win10/google chrome 版本 66.0.3359.181（正式版本） （32 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/yvan1212/9nxah2o3/](https://jsfiddle.net/yvan1212/9nxah2o3/)

### Steps to reproduce
1.table组件显示合计行
2.固定首列
3.列表宽度设置为可滚动
4.点击固定列下的滚动条无法正常鼠标点击后拖动

### What is Expected?
固定列的滚动条可以正常点击拖动

### What is actually happening?
点击固定列下的滚动条无法正常鼠标点击后拖动

**Comment by ziyoung** [comment]
Duplicate of #6089
