### ISSUE TITLE
[Bug Report] el-select radio input state cannot pop-up input method el-select cannot show input method to type on phone

### ISSUE THREAD

**Issue by jimliang** [ElemeFE/element#12315]
### Element UI version
2.4.5

### OS/Browsers version
android、ios

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4773/](https://jsfiddle.net/mmx38qxw/4773/)

### Steps to reproduce
有移动端环境下，这两个可输入状态的el-select，点击并输入搜索关键字。

### What is Expected?
两个el-select都能正常输入然后搜索

### What is actually happening?
上面那个单选的无法弹出输入法，就无法正常输入，下面那个多选的则可以正常弹出输入法进行输入。

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

**Comment by yeAlice** [comment]
Is this problem solved?

**Comment by liuyueqi18** [comment]
可以尝试更改一下吗？在某些情况下，操作人员可能会使用移动端操作，所以希望select远程搜索时候可以在移动端上弹出键盘，谢谢

**Comment by liuyueqi18** [comment]
可以尝试更改一下吗？在某些情况下，操作人员可能会使用移动端操作，所以希望选择远程搜索时可以在移动端上弹出键盘，谢谢
