### ISSUE TITLE
When the cascade selector is selected, the input box is not active

### ISSUE THREAD

**Issue by msidolphin** [ElemeFE/element#12316]
### Element UI version
2.4.5

### OS/Browsers version
win7 谷歌68.0.3440.84

### Vue version
2.5.16

### Reproduction Link
[http://jsfiddle.net/0ps9z9sd/398/](http://jsfiddle.net/0ps9z9sd/398/)

### Steps to reproduce
选择的时候激活状态失效

### What is Expected?
选择的时候仍然处于激活状态，就像日期选择器一样

### What is actually happening?
选择的时候激活状态失效

**Comment by ziyoung** [comment]
**激活状态失效**是什么意思？不太理解。

**Comment by msidolphin** [comment]
@ziyoung 就是输入框边框颜色变了。打开选择框的时候输入框边框是主题色，但是当我选择的时候边框就变灰色了
