### ISSUE TITLE
[Feature Request] wants to provide a way to set the tree semi-selected node

### ISSUE THREAD

**Issue by dongsuju** [ElemeFE/element#12314]
### Existing Component
是

### Component Name
tree

### Description
当check-strictly 为true时，自己代码控制 节点的check状态是否级联。需要设置节点的checke为半选状态。

**Comment by ziyoung** [comment]
这个功能我们暂不打算去实现。我觉得你可以试试设置 render-content，渲染 checkbox ，去实现该功能。
