### ISSUE TITLE
[Bug Report] The type attribute does not work when the button component is included in the input component

### ISSUE THREAD

**Issue by huixu123** [ElemeFE/element#12313]
### Element UI version
2.4.5

### OS/Browsers version
win10

### Vue version
2.5.17

### Reproduction Link
[  https://elementui.github.io/issue-generator](  https://elementui.github.io/issue-generator)

### Steps to reproduce
  https://elementui.github.io/issue-generator

### What is Expected?
type属性起作用

### What is actually happening?
type属性不起作用

**Comment by ziyoung** [comment]
没有提供 reproduction link 的 issue 将会直接关闭。
