### ISSUE TITLE
When [Bug Report] form and checkbox are used together and initial values are provided dynamically, checkbox cannot switch display status properly

### ISSUE THREAD

**Issue by Fevercorn** [ElemeFE/element#12324]
### Element UI version
2.3.8

### OS/Browsers version
windows10 / chrome  67.0.3396.99

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/9oj47hgn/12/](https://jsfiddle.net/9oj47hgn/12/)

### Steps to reproduce
1.点击checkbox -> checkbox无法切换显示的状态
2.在上方的输入框输入字符之后，checkbox刷新了显示状态

### What is Expected?
点击checkbox之后，checkbox 立即更新显示状态

### What is actually happening?
点击checkbox之后，checkbox没有更新显示状态

**Comment by jikkai** [comment]
这是 Vue 的使用问题，Vue 无法监听初始化时不存在的对象，需要通过 Vue.set 创建：https://jsfiddle.net/9oj47hgn/14/

**Comment by ziyoung** [comment]
```js
/* _this.form[itm.prop] = itm.initVal */
_this.$set(_this.form, itm.prop, itm.initVal)
```
https://jsfiddle.net/zhiyang/9oj47hgn/15/
