### ISSUE TITLE
[Bug Report] datepicker selects multiple dates to report errors.

### ISSUE THREAD

**Issue by suqiuhui** [ElemeFE/element#12323]
### Element UI version
2.4.5

### OS/Browsers version
windows10 / chrome等主流浏览器

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/4582fe73/2/](https://jsfiddle.net/4582fe73/2/)

### Steps to reproduce
点击多个日期选择框，选择目标日期后确定，然后点击选择框中的清除按钮，将刚刚选择的日期清除，然后重新选择，就会出现初步的交互不正常现象，重复操作的过程中可穿插点击页面空白处隐藏日期弹框，会看到日期不能再被选中及控制台报错现象(Uncaught TypeError: Cannot read property 'push' of null)
报错位置应该在date-table.vue文件的490行左右的 if (!cell.selected) {selectedDate.push(newDate);}处
![image](https://user-images.githubusercontent.com/19644289/43944152-8b677132-9cb0-11e8-996f-4784200d84bd.png)
![image](https://user-images.githubusercontent.com/19644289/43944145-8526da88-9cb0-11e8-93b7-2beb53acd860.png)
![image](https://user-images.githubusercontent.com/19644289/43944168-96a79824-9cb0-11e8-8d95-871ea63c5328.png)
![image](https://user-images.githubusercontent.com/19644289/43944213-beab6ab2-9cb0-11e8-9afc-792cf38024dc.png)

### What is Expected?
1. 不要报错
2. 日期可选中
3. 像一般日期选择一样，点击空白处隐藏日期弹出框时刻获取到选中的日期，而非点击确定方可获取
4. issue可粘贴图片以供方便清晰描述问题所在

### What is actually happening?
1. 交互存在不正确现在
2. 继续操作会报错且日期不能再被选中

**Comment by wacky6** [comment]
我这里看 jsfiddle 没复现。

**Comment by suqiuhui** [comment]
您可以在element官网试试看，我是在官网上测试出来的，相应的截图也是官网上的，很容易就复现了，也许是我的步骤描述不是很清晰但是这个问题今天试了多次，没有不能复现的情况，麻烦再试一下吧

发自我的 iPhone

**Comment by firesh** [comment]
@wacky6 我复现出来了，不要点确定按钮，点控件外。
