### ISSUE TITLE
[Feature Request] Test Tool e2e

### ISSUE THREAD

**Issue by renatosistemasvc** [ElemeFE/element#12334]
### Existing Component
No

### Component Name
2.4.6

### Description
I'm trying to use nightwatchjs to run the e2e tests on my system using the element. And I can not make the select work. 
The problem is that the element uses input instead of the <selec>

And nightwatchjs uses the following command to select the option: .click('select[id="myselectbox"] option[value="somevalue"]')

Is there any other tool compatible with e2e test element?

**Comment by jikkai** [comment]
Well, Issues is used to track bugs or feature requests.
If you have some questions that really need help, [stackoverflow](https://stackoverflow.com/) & [gitter](https://gitter.im/element-en/Lobby) will be a better place :)
