### ISSUE TITLE
[Bug Report] Input with icon - icon blocking focusing the field

### ISSUE THREAD

**Issue by shapiromichael** [ElemeFE/element#12337]
### Element UI version
2.4.6

### OS/Browsers version
Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4839/](https://jsfiddle.net/mmx38qxw/4839/)

### Steps to reproduce
Using input with an icon (search icon)
Clicking on the search icon - does not focus the input

### What is Expected?
The input field should be focused

### What is actually happening?
Nothing

**Comment by jikkai** [comment]
This is intentional, events of prefix / suffix icon should be handled on user side.
https://jsfiddle.net/mmx38qxw/4841/
