### ISSUE TITLE
[Feature Request] Deep rules validate and validation by submit in el-form-item

### ISSUE THREAD

**Issue by palpich** [ElemeFE/element#12330]
### Existing Component
Yes

### Component Name
el-form-item

### Description
If you use multiple input fields inside `el-form-item` and do a deep validate, it will work every time I switch between input.
How can I validate only when I press the submit button, without blur and change events?
https://jsfiddle.net/edbyt7o5/9/

**Comment by wacky6** [comment]
https://jsfiddle.net/edbyt7o5/11/

**Comment by palpich** [comment]
Thanks @wacky6 for the answer, but it does not work.
I want to validate only by pressing the button submit, and in your example, validation is performed immediately after input.

**Comment by wacky6** [comment]
Looks like I forgot to save: https://jsfiddle.net/8dcpL3ym/

**Comment by palpich** [comment]
Thx!
