### ISSUE TITLE
[Feature Request] how to pass validateMessage to slot?

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#12340]
### Existing Component
Yes

### Component Name
el-form-item

### Description
![image](https://user-images.githubusercontent.com/1060733/44015890-46a8c828-9f05-11e8-85eb-ad92456070be.png)

In `form-item.vue`, there's a variable `validateMessage`, how can I pass it to the default slot?
I tried this: 

1. define a prop called `message` in `input.vue` 
2. modify that line in `form-item.vue` to `<slot message="validateMessage"></slot>`

but I didn't work at all.

**Comment by ziyoung** [comment]
```js
  computed: {
    validateMessage() {
      if (this.$parent.$options.componentName === 'ElFormItem') {
        return this.$parent.validateMessage;
      } else {
        return '';
      }
    }
  }
```
http://jsfiddle.net/zhiyang/0ps9z9sd/407/
