### ISSUE TITLE
关于date picker 以及 time picker 参数建议

### ISSUE THREAD

**Issue by stevieyu** [ElemeFE/element#1234]
首先月份以及年份选择最好根据 format 来判断显示，然后 type 用来显示是否范围选择，或者用 :range="true" 来做范围选择，以此加强整个组件适合范围性

**Comment by furybean** [comment]
感谢建议。

能否详细描述下『以此加强整个组件适合范围性』所包含的点？这么做解决了哪些问题？

**Comment by stevieyu** [comment]
首先减少参数的传递，之前需要传两个参数的，一个就可以。比如传 format 为 yyyy-mm 后还得传 type 为 month ，这有些过于繁琐，一个参数搞定 format 站在语义化的角度也更好。 有个参数限定传 range 如果传的 ～ ，那就把中间的 - 替换掉，如果为真就用默认的 - ，以增加灵活度，有些界面中间的字是需要换掉的，还有些界面是要一个文本框搞定 range，比如简历的工作经历里的日期，还有就是最好范围多个选择 `至今` 的文字，否则的话只能自己花时间改，毫无疑问这样有点浪费效率

**Comment by QingWei-Li** [comment]
替换文字的话可以用 i18n 的特性，这里面的默认文字都是可以替换的 https://github.com/ElemeFE/element/blob/dev/src/locale/lang/zh-CN.js 自己配置一份文件然后引入时改加载语言包

```javascript
import Vue from 'vue'
imprt ElementUI from 'element-ui'

Vue.use(ElementUI, { locale: {/* 你的配置 */} }) 
```

**Comment by furybean** [comment]
『比如传 format 为 yyyy-mm 后还得传 type 为 month ，这有些过于繁琐，一个参数搞定 format 站在语义化的角度也更好。』
如果我 type 是 month，但是 format 需要显示 yyyy-MM-dd 怎样解决？

**Comment by stevieyu** [comment]
那直接 format 设置 成 yyyy-MM-dd 就行让其做日期选择，并不常见 format 为  yyyy-MM-dd 且只能选择month。再说，真有的话，那就保留 format 跟 type，平时只用 format 搞定一切的年月日星期选择，特殊情况加 type 参数来限定选择的是年月日星期， 做范围选择时用 range，这不就行了

**Comment by furybean** [comment]
抱歉，我并没有看到这么做的必要性。

我们不可能为了一个小的改进影响到目前在生产上使用的用户，做 出Breaking Change 一定是因为这么做可以带来更多的好处。
