### ISSUE TITLE
[Bug Report] When the el-dialog component is re-encapsulated as a nested component, when the nested component is closed, if the interface has a scrollbar, the scrollbar that would have been locked appears again

### ISSUE THREAD

**Issue by MrLiuTY** [ElemeFE/element#12359]
### Element UI version
2.4.6

### OS/Browsers version
Win10/ Chrom 67.0.3396.99（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/shilan/ctjwmfub/](https://jsfiddle.net/shilan/ctjwmfub/)

### Steps to reproduce
初始DOM高度是存在滚动条的，两个二次封装 el-dialog 的全局组件(parent/child)
点击 “打开外层dialog” 按钮，出现弹窗，滚动条被锁定，超出可视界面的部分被隐藏
点击 “打开内层” 按钮，出现嵌套弹窗，此时滚动条依然被锁定
当关闭嵌套弹窗时候 ，滚动条出现，界面出现可滚动现象

### What is Expected?
两个组件均是用v-if判断，如果条件不成立，该组件会被销毁。
嵌套弹窗被销毁时候，界面应该保持被锁定状态，body上的“el-popup-parent--hidden”样式不应该被清除，
当父级弹窗被销毁时，才清除body上的“el-popup-parent--hidden”样式

### What is actually happening?
当嵌套弹窗被销毁时，滚动条出现，body上的“el-popup-parent--hidden”样式被清除。
如果将嵌套弹窗组件的v-if改成v-show，则不会出现这个现象，但是嵌套的弹窗不会被销毁。
往往很多时候需要弹窗自动销毁，但是当存在弹窗时候，界面还能滚动，会造成非常差的用户体验。
麻烦在百忙中的开发人员能够注意下这个问题

**Comment by ziyoung** [comment]
我试了一下，文档上的[嵌套 dialog](https://element.faas.ele.me/#/zh-CN/component/dialog#qian-tao-de-dialog) 这个例子并没有问题。

**Comment by MrLiuTY** [comment]
你需要把el-dialog 二次封装成一个组件来嵌套使用，就会出现这种情况。比如一个弹窗封装的是添加用户，用户需要有头像，就导入一个公共的剪切图片的弹窗组件，如果销毁这个公共剪切图片的组件之后，原本被锁定的body就会出现滚动条

**Comment by MrLiuTY** [comment]
@PhamLinh0889 
Sorry buddy,Can you speak more clearly?I didn't understand somewhat.

**Comment by MrLiuTY** [comment]
虽然在关闭回调中直接emit修改父类的v-if的值就可以解决，但是关闭窗口的动画就没了。我始终在就这 关闭动画，可算找到个方法解决了
需要在窗口关闭动画结束后的回调中加入
this.$nextTick(() => {
       document.body.className = "el-popup-parent--hidden"
})

**Comment by KDWangBoss** [comment]
好像版本2.15.9还有这个问题，貌似没有解决。
