### ISSUE TITLE
loading service的close中$destroy会导致和其它一些第三方扩展冲突

### ISSUE THREAD

**Issue by terranc** [ElemeFE/element#1235]
version：1.0.1

跟踪代码发现，在`loadingService.close`中最后面有一个`this.$destroy()`会导致诸如vue-head插件无法正常工作，想问是否这一句必要或者有更纯净的方案？我尝试去除了这一句也能正常工作。

**Comment by baiyaaaaa** [comment]
理论上这个语句应该不会导致这个问题，能给出在线重现的demo么

**Comment by terranc** [comment]
@baiyaaaaa 发现是vue-head里面用了全局mixin beforeDestroy，所以被一起触发了。
