### ISSUE TITLE
[Bug Report] When the selector component configures the clearable option to true, the arrow does not rotate the second time the selection box is opened

### ISSUE THREAD

**Issue by msidolphin** [ElemeFE/element#12352]
### Element UI version
2.4.6

### OS/Browsers version
win10 / chrome 68.0.3440.106

### Vue version
2.5.16

### Reproduction Link
[http://jsfiddle.net/0ps9z9sd/417/](http://jsfiddle.net/0ps9z9sd/417/)

### Steps to reproduce
选择器组件配置了clearable选项为true后，选择一条记录后再次打开选择框时，箭头不会旋转，不知道是否是设计如此

### What is Expected?
箭头正常翻转

### What is actually happening?
箭头朝向不变

**Comment by firesh** [comment]
Issue reproduced, I'll check.
![image](https://user-images.githubusercontent.com/7334304/44039659-1c70b95c-9f4c-11e8-8501-123bfc55c252.png)

**Comment by firesh** [comment]
已经提交PR修复了该问题：https://deploy-preview-12353--element.netlify.com/#/zh-CN/component/select

**Comment by ziyoung** [comment]
鼠标悬浮在 Select 上面时，右侧直接变成了清除按钮，所以才没有过滤动画。
@firesh 修改完之后，交互就更奇怪了。
![kapture 2018-08-14 at 11 05 53](https://user-images.githubusercontent.com/12947422/44069811-2fad0978-9fb3-11e8-8b6c-1d3a3a5a0ad6.gif)

**Comment by firesh** [comment]
@ziyoung 我的理解，在展开下啦列表的时候，箭头应该始终朝上。 参见基础单选：
![image](https://user-images.githubusercontent.com/7334304/44104601-d5316524-a021-11e8-8b09-cb0e068bb18a.png)
