### ISSUE TITLE
[Feature Request] el-select filtered cannot complete using tab

### ISSUE THREAD

**Issue by jodevelofer** [ElemeFE/element#12351]
### Existing Component
Yes

### Component Name
el-select 

### Description
I used el-select and add filtered on it. When I try it and type on the dropdown, its working when i click or pressing enter. But when I press tab its not working.. Is it possible? if not , any workaround?

**Comment by ziyoung** [comment]
We usually use the tab key to focus the element which can be focused. If you press tab key, next element will be focused. FYI: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
