### ISSUE TITLE
Tree 的 setCheckedNodes 到底怎么用？调用了没反应 也不报错

### ISSUE THREAD

**Issue by ruizhou8888** [ElemeFE/element#1236]
### What is actually happening?
Tree 的 setCheckedNodes 到底怎么用？调用了没反应 也不报错

**Comment by djjandyhl** [comment]
我也想知道......同一个tree组件要多次改变勾选的节点，如果只设置了属性default-checked-keys的话，会有一个问题就是当default-checked-keys中数组的值变化少了过后，之前勾选的不会取消勾选。

**Comment by CharkeyQK** [comment]
@furybean 给我的[例子](https://github.com/ElemeFE/element/issues/1199) [Tree.vue](https://github.com/CharkeyQK/vue-demo/blob/master/src/components/Tree.vue)

**Comment by djjandyhl** [comment]
强烈建议tree组件设置在勾中复选框时用default-checked-keys做一个响应式的。而不是每次改变去调用 setCheckedNodes。我只想关注我勾中的node-key数组....

**Comment by ruizhou8888** [comment]
我也是这么觉得

**Comment by djjandyhl** [comment]
而且我设置check-strictly为false时。setCheckedNodes调用没反应了a .要疯了.....

**Comment by ruizhou8888** [comment]
我是做用户授权这块  好多要用tree的check

**Comment by djjandyhl** [comment]
我也是啊。哈哈哈

**Comment by furybean** [comment]
@djjandyhl default-checked-keys 使用的场景是初次加载完成 Node，勾选上次提交选中的 Node。

**Comment by furybean** [comment]
@djjandyhl  从我的角度看，setCheckedNodes 应该是一个很少会使用到的方法，你的使用场景是怎么样的？

**Comment by ruizhou8888** [comment]
我操  是不是check-strictly 必须得设置为true才有用？

**Comment by djjandyhl** [comment]
但是在我编辑多个角色权限时，我要复用同一个tree组件多次....

**Comment by ruizhou8888** [comment]
@furybean  就是点击表格中一个用户 或者是角色 右边的权限树 会勾选上当前选中用户已有的权限。。。

**Comment by furybean** [comment]
@ruizhou8888 defaultCheckedKeys 绑定的变量重新赋值一次就可以。

**Comment by djjandyhl** [comment]
在做权限树状展示的时候，每个人的权限不一样，我就要不停地去切换选中的树节点。而且我还要编辑勾中的节点，所以我很想只关注勾中的节点key数组。

**Comment by ruizhou8888** [comment]
我试过了，是可以 但是之前得勾选没有取消掉。

**Comment by ruizhou8888** [comment]
@furybean  建议加个 flag 如果为true 就表示取消之前得所有勾选重新设置，false即为追加勾选。

**Comment by djjandyhl** [comment]
我也是啊。重新给defaultCheckedKeys赋值，之前勾的不会被取消掉。而且我看了源码，你只会遍历defaultCheckedKeys数组，没去检查之前被勾中的。

**Comment by ruizhou8888** [comment]
@djjandyhl 加个flag 应该就可以了 只关注数据 才更能体现出 VUE 的数据驱动的概念。

**Comment by furybean** [comment]
@ruizhou8888  整颗树的节点不都重新加载了么？为什么会存在『之前勾选』的节点？

**Comment by djjandyhl** [comment]
我觉得就该把defaultCheckedKeys这个值做成响应式的。defaultCheckedKeys数组里有哪些key就勾选。用户点击勾选defaultCheckedKeys改变，代码设置defaultCheckedKeys，勾选的改变。只需要关注defaultCheckedKeys这个数组就行了。。

**Comment by ruizhou8888** [comment]
@djjandyhl  我也是这个意思

**Comment by ruizhou8888** [comment]
@furybean  树不重新加载啊。数据多的话 我每点一次渲染不会很慢吗？

**Comment by furybean** [comment]
@ruizhou8888 @djjandyhl Okay，了解了，我看一下这种场景怎么处理。

**Comment by djjandyhl** [comment]
@furybean 谢谢

**Comment by furybean** [comment]
@ruizhou8888 @djjandyhl setCheckedKeys 可以暂时通过这种方式实现：http://jsfiddle.net/8wo0sm4w/

需要说明一下 setCheckedNodes 的执行机制，setCheckedNodes 的表现很奇怪的主要原因是因为 check-strictly 为 false。

在执行任意节点的 setChecked 的时候，实际上该节点会影响父节点，也会影响所有的子节点。传入一个 checkedNodes 或者 checkedKeys，有两种方式可以设置节点的 checked：

- 假设我从最底层开始设置 checked 属性，那么如果你的 checked keys 里面不包含最上层，整个树可能就无法获得任何勾选，因为最上层执行了 setChecked 为 false。
- 假设我从最上层开始设置 checked 属性，则会导致本来不该被勾选的节点获得了勾选。

我会考虑下此处的 API 怎么处理才不会那么奇怪，你们可以先看看上面的例子能不能满足你的需求。

**Comment by djjandyhl** [comment]
用你给出的例子调用setCheckedNodes 时，可以不用设置check-strictly为true。
我希望还是能给出一个属性直接是响应当前勾中项key值的数组。

**Comment by furybean** [comment]
@djjandyhl 对，因为例子里面，相当于我重写了一个 setCheckedKeys。
getCheckedKeys 会加，但是版本发布是有节奏的，1.0.3 的发布日期还没定。

**Comment by fewiki** [comment]
1.0.5 tree setChecked 还是一头雾水，有走通的么

**Comment by fewiki** [comment]
this.$refs.tree.setChecked('305890105',true,false) key为节点的id，这样做可以

但 tree的check的方法只能有checkbox的tree有效，我想实现初始化选中tree的节点，现在有方法么
如下：（初始化就选中 下面高亮的节点）
![image](https://cloud.githubusercontent.com/assets/13325335/21000749/84b98184-bd57-11e6-8342-a2e272ae8386.png)

**Comment by soulkiller** [comment]
@fewiki  我也遇到这个需求了 这个tree好像不能满足~

**Comment by yursile** [comment]
@furybean 亲，这个例子跑不动啊，现在setCheckedNodes这个方法也还是跑不了，有其他的解决方式了吗

**Comment by yursile** [comment]
这个例子跑不动 http://jsfiddle.net/8wo0sm4w/

**Comment by yursile** [comment]
我悲劣的用了v-if，但不应该这么玩啊

**Comment by Leopoldthecoder** [comment]
@yursile 直接按照文档上的例子跑就行：https://jsfiddle.net/ncs9L1pL/

**Comment by kkcode24** [comment]
@fewiki  我也遇到这个需求，你实现了吗？使用tree组件

**Comment by kkcode24** [comment]
@soulkiller @fewiki 我也遇到这个需求，你实现了吗？使用tree组件

**Comment by qinzitong** [comment]
设置node-key="id"

**Comment by gypjoy** [comment]
@fewiki @kkcode24  你们的tree setCheckedNodes 实现了吗？

**Comment by houyaowei** [comment]
this.$refs.tree.store.nodesMap[id值].checked = true; 这个也不起作用

**Comment by houyaowei** [comment]
> @fewiki @kkcode24 你们的tree setCheckedNodes 实现了吗？

这个是针对带CheckBox的

**Comment by houyaowei** [comment]
@fewiki  @soulkiller  @yursile  可以使用一下方法 ，亲测可用
this.$refs.tree.setCurrentNode({
        id:2,
        label:'产品简介'
      }) 

但是有个问题，node-click绑定的方法不会触发

**Comment by ailuhaosi** [comment]
如果仅仅是想修改`el-tree`的`default-checked-keys`属性，由于default-checked-keys`只在`el-tree`组件创建的时候赋值
可以使用`v-if`，强制重渲染。切换`v-if`之前重新给`default-checked-keys`赋值。

**Comment by Song19939334056** [comment]
vue.esm.js?efeb:591 [Vue warn]: Error in event handler for "click": "TypeError: Cannot read property 'setCheckedKeys' of undefined"
 
相信很多人遇到过这个问题，这是因为this.dialogVisible = true时并没有立即更新dom，而是等整个逻辑执行完后再一次新渲染，因此此时的弹框并未渲染，在dom树中是不存在的，
this.$refs.tree is undefined的所以setCheckedKeys肯定也是undefined。
 
解决方法: this.$nextTick()，this.$nextTick()会在dom更新之后在执行回调：
 
opetation (auth) {
  this.dialogVisible = true
  this.$nextTick(function() {
    this.$refs.tree.setCheckedKeys(auth)
  })
地址：https://blog.csdn.net/weixin_33743703/article/details/88126575
