### ISSUE TITLE
[Feature Request] shortcuts layout api

### ISSUE THREAD

**Issue by NumerHero** [ElemeFE/element#12363]
### Existing Component
是

### Component Name
DatePicker

### Description
The date-picker component need config shortcuts btns location in project

Hope ele FE give a new Feature that date-picker shortcuts can config layout loction included top、bottom、left (default) 、 right

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.

**Comment by NumerHero** [comment]
emmmm oh right, I realize this by myself.
However, I thought It's easy to finish, just change the layout and scss

supply a design sketch like this
![image](https://user-images.githubusercontent.com/12696061/44131132-708456e2-a083-11e8-9911-48692b3ed834.png)
