### ISSUE TITLE
[Bug Report] datepicker with shortcut option has been selected during the last three months.

### ISSUE THREAD

**Issue by suqiuhui** [ElemeFE/element#12374]
### Element UI version
2.4.6

### OS/Browsers version
windows10 / chrome等主流浏览器

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/z7tpdc60/](https://jsfiddle.net/z7tpdc60/)

### Steps to reproduce
1. 选中带快捷选项的日期选择器
2. 点击弹出框中的最近三个月
3. 日期选择器输入框中出现 2018-05-17 至 2018-08-15 的日期区间
![image](https://user-images.githubusercontent.com/19644289/44135435-a8131b4e-a09b-11e8-8753-e3aac7cc405e.png)

### What is Expected?
应该是 2018-05-16 至 2018-08-15 的日期区间

### What is actually happening?
出现 2018-05-17 至 2018-08-15 的日期区间

此问题可在官网发现

**Comment by jikkai** [comment]
你可以关注下你发的链接中 js 代码 36 行，这个时间是用户自己设置的，你可以任意根据你的需要修改它。
