### ISSUE TITLE
[Bug Report] tableData change can not affect checkbox in custom template 

### ISSUE THREAD

**Issue by legendjslc** [ElemeFE/element#12375]
### Element UI version
2.4.6

### OS/Browsers version
win10， chrome68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/c61yve53/39/](https://jsfiddle.net/c61yve53/39/)

### Steps to reproduce
1. open the fiddle url: https://jsfiddle.net/c61yve53/39/
2. click 'checkAll' button, you can see text in column 1 and column 3 changed, but checkbox status not change.

### What is Expected?
checkbox will checked as expected.

### What is actually happening?
checkbox status not changed

**Comment by jikkai** [comment]
https://jsfiddle.net/c61yve53/44/
