### ISSUE TITLE
[Select]如何在搜索不匹配时，显示请选择或者置空，而不是填入最后一次的匹配项

### ISSUE THREAD

**Issue by akaylh** [ElemeFE/element#1237]
### ElementUI version

1.0.2

### Vue version

2.0.7

### What is Expected?
[Select]如何在搜索不匹配时，显示请选择或者置空，而不是填入最后一次的匹配项

### What is actually happening?
select组件，我启用了filterable，来用过滤数据，但发现个问题，就是输入的条件，没有匹配到值时，会自动填入最后一次匹配的项，举个例子：

列表如下：
AAAAAA
BBBBBBB
CCCCCC

输出B时，能够匹配到BBBBBBB，当再输入D时，没有匹配到任何值，组件却默认设置成了BBBBBBB。

**Comment by Leopoldthecoder** [comment]
如果匹配不到任何选项，那么在 Select 失去焦点后，Select 的值仍为上一次选择的值，这个应该是符合直觉的。你需要清空的具体场景是？可否通过设置 `clearable` 属性来完成，而不是在匹配不到选项的时候清空？

**Comment by Leopoldthecoder** [comment]
超过 7 天没有反馈的 issue 我们会先关闭。如果需要再次反馈，可以再打开。
