### ISSUE TITLE
[Bug Report] This.$message.error('wrong, this is an error message'); after calling the popup, I found that the attributes of the html tag (such as lang="en-US") were deleted?

### ISSUE THREAD

**Issue by liuhuanhui** [ElemeFE/element#12378]
### Element UI version
2.4.6

### OS/Browsers version
GOOGLE

### Vue version
2.5.17

### Reproduction Link
[https://github.com/liuhuanhui/bug01/](https://github.com/liuhuanhui/bug01/)

### Steps to reproduce
https://github.com/liuhuanhui/bug01/
F12, run, check the HTML tag, and then click the button on the page.

**Comment by jikkai** [comment]
debugger 了一下感觉这个问题应该不是 element 造成的，最好尝试看下是不是受到 nuxt-i18n 影响。

**Comment by liuhuanhui** [comment]
@jikkai 我也调试了下 确实是引入了nuxt-i18n才会出现这种问题。

**Comment by trylovetom** [comment]
Same Problem Here, 
I try this setting below, solve the problem
`seo: false`
