### ISSUE TITLE
[Bug Report] TREE node custom style scoped slot mode, el-row, el-col layout invalid

### ISSUE THREAD

**Issue by yuweiming2016** [ElemeFE/element#12382]
### Element UI version
0.1.0

### OS/Browsers version
WIN7/CHROME

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4922/](https://jsfiddle.net/mmx38qxw/4922/)

### Steps to reproduce
1、添加el-tree
2、添加自定义节点scoped slot
3、添加一个简单的布局:一行两列，平均分隔

### What is Expected?
一行两列，平均分隔

### What is actually happening?
靠左对齐了

**Comment by jikkai** [comment]
因为你父级元素用的是 `span` 并且也没有设置宽度。https://jsfiddle.net/mmx38qxw/4924/
