### ISSUE TITLE
[Bug Report] How to properly fork ElementUI? npm run dev gets This dependency was not found:  * element-ui in ./src/main.js

### ISSUE THREAD

**Issue by GustavoFenilli** [ElemeFE/element#12384]
### Element UI version
2.4.6

### OS/Browsers version
Google Chrome

### Vue version
2.5.17

### Reproduction Link
[https://github.com/GustavoFenilli/element](https://github.com/GustavoFenilli/element)

### Steps to reproduce
1. Fork the repository
2. npm install --save https://github.com/GustavoFenilli/element
3. npm run dev

It will give a error
This dependency was not found:  * element-ui in ./src/main.js

So what is the proper way to fork and work on your own version of this project?

### What is Expected?
To run properly like the npm version

### What is actually happening?
Not running at all.

**Comment by jikkai** [comment]
Use yarn instead of npm.

**Comment by GustavoFenilli** [comment]
yarn gives the same error.

**Comment by jikkai** [comment]
Try to remove the `node_modules` folder and `package-lock.json`, then try it again 🤔

**Comment by GustavoFenilli** [comment]
Already did that, still doesn't change anything, there is something wrong with what I did? like in the steps? fork, install the forked git, and tried to run? there is something between that I should be doing?

**Comment by GustavoFenilli** [comment]
After looking for the problem a lot, the problem is probably that if you fork the project, the lib folder doesn't go with it, so you can build the project yourself, the main: "lib/element-ui.common.js".

So would be nice to have in the .github CONTRIBUTING how to build the lib also.
