### ISSUE TITLE
[Feature Request] Whether form validation can provide warning mode

### ISSUE THREAD

**Issue by pcloth** [ElemeFE/element#12387]
### Existing Component
yes

### Component Name
form

### Description
A prompt message is displayed, but the function passed is still verified. Generally used for reminders such as passwords that are not rigorous.

**Comment by ziyoung** [comment]
@pcloth We use [async-validator](https://www.npmjs.com/package/async-validator) to validate form data .`async-validator` doesn't provide the warning message if validation doesn't pass.

**Comment by romyatziv** [comment]
Also looking for this feature.
