### ISSUE TITLE
[Bug Report]  Tree in lazy mode, set child node 'default-checked-keys', display wrong：All nodes are fulfilled

### ISSUE THREAD

**Issue by PuRonglong** [ElemeFE/element#12383]
### Element UI version
2.4.6

### OS/Browsers version
Chrome 68.0.3440.106 (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/puronglong/b6yoqp5t/4/](https://jsfiddle.net/puronglong/b6yoqp5t/4/)

### Steps to reproduce
id,2,3,4,5是下面的四个子节点，当第一个和第二个子节点默认选中的时候，所有的节点都被选中了，当不是前两个子节点默认选中的时候，正常，可修改default-checked-keys值复现

### What is Expected?
default-checked-keys有的值才被选中

### What is actually happening?
当第一个和第二个子节点默认选中的时候，所有的节点都被选中了，当不是前两个子节点默认选中的时候，正常。可修改default-checked-keys值复现

**Comment by mcu13321** [comment]
这个问题之前遇到过，懒加载下选中父节点下的第一个节点（现在是前两个节点），所有的都会选中，做了个hack，在树节点下加一个id为-1的节点，但是树逻辑复杂的情况下，处理的细节更多，希望尽快解决，谢谢作者

**Comment by otizis** [comment]
我改的方法是，在load函数里面判断，若加载的是 default-checked-keys 里面的，在nextTick重新设置。
会有多次触发，不过干净一些。
```
checkNode(){
      this.$nextTick(()=> {
        console.log("set checked key")
        this.$refs.elTreeInOrgTree.setCheckedKeys(this.value.map(item=>{
          return item.id;
        }));
      });
    },
    loadNode(node, resolve) {
      let data = node.data;
      return this.getOrgByPid(data.id, nodeLevel).then(orgs => {
          console.log("loaded  sub ")
          if(this.defaultExpandedKeys.indexOf(data.id)){
            this.checkNode();
          }
        return resolve(orgs);
      });
    },
```

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/14847#issuecomment-476557047

**Comment by yangmiao7** [comment]
https://jsfiddle.net/x47j0dr6/ 案例中的情况只能用于load中的异步操作已经执行完毕，然后再用setCheckedKeys 进行勾选回显设置，业务中常见的懒加载情况为，load中的异步操作可能在不可预知的时间执行完毕，也初始化需要展开的展开项目为多个，load会多次执行，这个时候没法确定什么时间调用setCheckedKeys函数，只要setCheckedKeys不是在所有load异步操作结束之后调用的，就可能依然有问题

示例代码：https://jsfiddle.net/wtrvx13z/1/

请问这种情况推荐如何处理
