### ISSUE TITLE
Slider 滑块拖动到边界卡死

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/element#1239]
### ElementUI version
 1.0.2 

### OS/Browers version
 win7/Chrome 53

### Vue version
2.0.3

Slider 滑块 step值为0.1，最小0，最大3.5，拖动到上边界3.5时卡死

另外step值为0.1，拖动的单位是1，而不是0.1，拖动的step应该和 step值保持一致，而现在不是

项目中在用Slider组件， 请帮修复，谢谢

**Comment by Kingwl** [comment]
确实存在

**Comment by Leopoldthecoder** [comment]
是 bug，今天修复。
