### ISSUE TITLE
Can [Feature Request] extract the drop-down menu of the datePicker component as a calendar component?

### ISSUE THREAD

**Issue by Rainylane** [ElemeFE/element#12395]
### Existing Component
是

### Component Name
datePicker

### Description
能不能把datePicker组件的下拉菜单提取出来，作为一个日历(calendar)组件？

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.

**Comment by Rainylane** [comment]
但是现在你们有日历组件了。真香？？

**Comment by Rainylane** [comment]
> 对不起，我们没有计划支持这个。

但是现在你们有日历组件了。真香？
