### ISSUE TITLE
[Feature Request] Populate and activate popover dynamically

### ISSUE THREAD

**Issue by Yorgovan** [ElemeFE/element#12393]
### Existing Component
Yes

### Component Name
Popover

### Description
Is it possible to populate and activate popover dynamically?
In my case I have fullcalendar and want to activate popover on event hover but since there is only this code for calendar...

`<full-calendar :events="events" :config="config" @event-render="eventRender" @event-selected="eventSelected" ref="calendar"></fullcalendar>`

...then I can't wrap event in popover element.

Is it possible to trigger it from method like notifications for example or like with bootstrap where we can do something like this:
```
element.popover({
  animation: true,
  delay: 1000,
  content: '<p>some content</p>',
  trigger: 'hover',
  placement: 'auto',
  container: 'body',
  html: true
})
```

**Comment by ziyoung** [comment]
Maybe you need [vue-popper](https://github.com/freeze-component/vue-popper) mixin.
