### ISSUE TITLE
[Bug Report] tree lazy loading drag and drop problem

### ISSUE THREAD

**Issue by dongsuju** [ElemeFE/element#12390]
### Element UI version
2.4.6

### OS/Browsers version
Google Chrome

### Vue version
2.5.17

### Steps to reproduce
1 lazy 方式加载节点
2  树的 节点为：
    中国 
    **北京
    ** 河北
     ****廊坊
 3 先拖节点：廊坊到北京下，此时树节点为：
  中国 
   ** 北京
   *****廊坊
    **河北
  4 再拖 河北到北京下，就会出现2个廊坊
  节点如下：
 中国 
  **北京
 ****廊坊
 *****河北
 *******廊坊

说明： * 代表空格，否则都给对齐了，看不出上下级关系。

### What is Expected?
拖拽出的节点不能再出现原来父级节点下。

### What is actually happening?
如果此节点下子节点拖出，再拖拽此节点，原来的子节点又出现。

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
