### ISSUE TITLE
[Bug Report] clearFilter filtered-value

### ISSUE THREAD

**Issue by yuanyuanshen** [ElemeFE/element#12391]
### Element UI version
2.4.6

### OS/Browsers version
w10/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
in element ui  table,after use clearFilter  to clear table Filter, then ,changge  filter ,filtered-value  bind array do not change

### What is Expected?
(1)use clearFilter
(2)changge  filter
(3)filtered-value also change

### What is actually happening?
(1)use clearFilter
(2)changge  filter
(3)filtered-value not change

**Comment by ziyoung** [comment]
@yuanyuanshen Please provide a right reproduction link.

**Comment by EdgarAllanzp** [comment]
Relatived issue https://github.com/ElemeFE/element/issues/12391
