### ISSUE TITLE
Unable to see translated text.

### ISSUE THREAD

**Issue by crow1796** [ElemeFE/element#1240]
### ElementUI version
1.0.1

### OS/Browers version
Windows 7/Chrome 54

### Vue version
2.0.1

### Reproduction Link
Sorry, I can't create reproduction link so I'll just screenshot some of my code.
http://prntscr.com/d9tr97
http://prntscr.com/d9trgn

### Steps to reproduce
http://prntscr.com/d9tqo7
http://prntscr.com/d9tqxg

### What is Expected?
Should be able to see translated text.

### What is actually happening?
Unable to see translated text.

**Comment by QingWei-Li** [comment]
Can you provide a repo?

**Comment by QingWei-Li** [comment]
Maybe you should try `1.0.2`

**Comment by Leopoldthecoder** [comment]
See if 1.0.2+ helps. Closing this issue now, you can reopen it if the problems still exists.
