### ISSUE TITLE
[Bug Report] In vue-cli project, el-select with multiple and filter will show chattering phenomena

### ISSUE THREAD

**Issue by XHappyness** [ElemeFE/element#12409]
### Element UI version
2.4.6

### OS/Browsers version
版本 68.0.3440.106（正式版本） （32 位）

### Vue version
2.5.17

### Reproduction Link
[https://github.com/XHappyness/elementUI-issue](https://github.com/XHappyness/elementUI-issue)

### Steps to reproduce
1. 下载链接中项目
2. 进入项目文件中安装依赖： npm install
3. 启动项目： npm run serve
4. 项目启动后打开http://localhost:8080/ （如果8080端口被占用，可能是其他端口，具体地址以项目启动成功后给出的地址为准）

5. 发现el-select组件当是“多选并且具有搜索功能时” 会出现el-select框抖动的问题（多选几个值换行的情况下）；

6.为了对比，项目中staticpage文件下创建了静态网页index.html，并通过CDN方式引入element-ui，同样使用el-select则没有这个问题。

### What is Expected?
期望在vue-cli创建的项目下，使用同时具有“多选和搜索”功能的el-selce时，多选换行时不再产生抖动的问题

### What is actually happening?
在vue-cli创建的项目下，使用同时具有“多选和搜索”功能的el-selce时，多选换行时产生抖动的问题

**Comment by XHappyness** [comment]
chrome版本升级为版本 70.0.3538.102（正式版本） （32 位）后，该问题消失

**Comment by fruitGirl** [comment]
想问下这个最后还有其他的解决方案吗

**Comment by johyin** [comment]
73.0.3683.86（正式版本）（32位）版本也会出现这个问题，想问还有其他的解决方案吗

**Comment by johyin** [comment]
把el-select下的el-select__input高度设置原来的28px就不会出现抖动了
原因可能是size=‘mini/small’重置了height
