### ISSUE TITLE
[Bug Report] The expansion parameter of the Table component with fixed causes the inserted template to be rendered twice.

### ISSUE THREAD

**Issue by hoythan** [ElemeFE/element#12404]
### Element UI version
2.4.6

### OS/Browsers version
MacOS Last Version

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/hoythan/zf8nob3d/6/](https://jsfiddle.net/hoythan/zf8nob3d/6/)

### Steps to reproduce

1. 打开调试模式，显示 console

2.点击 RUN

3.查看 console 控制台，发现出现两次 created 来自 component 组件的 created => console.log

### What is Expected?
不论是否添加 fixed，都应当只渲染一次，以免造成性能损失。

### What is actually happening?
运行后点击展开，将会出现 两次 console.log 内容为 created。如果移除 fixed 问题不会复现。

**Comment by ziyoung** [comment]
Duplicate of #12177
