### ISSUE TITLE
[Bug Report] className rendering sequence problem

### ISSUE THREAD

**Issue by ovarte** [ElemeFE/element#12407]
### Element UI version
2.4.6

### OS/Browsers version
win7 /chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
<el-input class="input" ></el-input>

### What is Expected?
<div data-v-589c2793="" class="el-input input">
    <input type="text" autocomplete="off" class="el-input__inner">
</div>
期待添加的class类名 出现在默认class类名之后，这样就可以覆盖原来的样式 。 期待所有类似组件的class 都改为这种形式。
在本地会覆盖默认样式，上线就会出现问题。

### What is actually happening?
<div data-v-589c2793="" class="input el-input">
    <input type="text" autocomplete="off" class="el-input__inner">
</div>

**Comment by ziyoung** [comment]
你把自定义类的样式权重提高一点不就可以了。
