### ISSUE TITLE
[Feature Request] Can Table hide space which was layout at the at?

### ISSUE THREAD

**Issue by tun100** [ElemeFE/element#12401]
### Existing Component
是

### Component Name
Table

### Description
Version desc:
Element: 2.4.6
Chrome: Lastest, not compatible question

Hello, There's two pictures you can see:
1, current display: https://imgchr.com/i/PWQiBq
2, wanna display: https://s1.ax1x.com/2018/08/17/PWQV4U.png

When I fixed the table height, the top right cornor will displayed, but I wanna make it hidden. Just like table-body inner scrollbar, and not like the outside scrollbar.
I wanna change the css style, but seems the top right space was depended by inner html dom structction. I think it's very useful feature for the user to change UI.

**Comment by ziyoung** [comment]
Please create a demo in [jsfiddle](https://jsfiddle.net/).

**Comment by LaiHuanMin** [comment]
@ziyoung Here you are, https://jsfiddle.net/laihuanmin/3j0yh9mk/
