### ISSUE TITLE
dropdown-item  command指令

### ISSUE THREAD

**Issue by wikidson** [ElemeFE/element#1241]
http://element.eleme.io/#/zh-CN/component/dropdown

没看懂  ：

command	点击菜单项触发的事件回调	dropdown-item 的指令 

怎么使用。。。

**Comment by baiyaaaaa** [comment]
文档解释有点问题，理解成dropdown的command事件的回调参数就好了，用来确认点击的是哪个item

**Comment by wikidson** [comment]
谢谢，采用了其他的方式。。。。

**Comment by zhangkuiworld** [comment]
同问 咋解决的？

**Comment by HyperSimon** [comment]
然而还是没有说清楚该怎么用
