### ISSUE TITLE
[Bug Report] Tree component lazy drag and drop and add and delete problems

### ISSUE THREAD

**Issue by junglehuang** [ElemeFE/element#12412]
### Element UI version
2.4.6

### OS/Browsers version
mac

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
1、tree组件加上lazy和load属性
2、加上draggable属性或者直接this.refs.tree调用remove和insertBefore接口

### What is Expected?
正常拖拽，正常增删

### What is actually happening?
拖拽后出现两个相同的节点，报错是key重复，因为你们在删除的时候，只处理了node下面的childrenNode做删除。而没删除node下data里面的children。所以导致没有真正的删除节点，在insert的时候又是拿data去做处理的，所以导致了key冲突。希望下个版本能解决这个问题，现在分层加载下，都无法正常拖拽。只能自己手动去删除node data里面的数据。

**Comment by ziyoung** [comment]
@junglehuang 在 https://jsfiddle.net/ 新建个 demo 吧。

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
