### ISSUE TITLE
[Feature Request] escape event needs to be captured

### ISSUE THREAD

**Issue by duanyijie** [ElemeFE/element#12425]
### Existing Component
是

### Component Name
select

### Description

我查了下源码，esc的keydown事件用了冒泡阻止，但是我需要捕捉用户按下esc键后的相关处理
希望能不要阻止冒泡

**Comment by ziyoung** [comment]
你自己可以手动监听 keydown 事件。https://jsfiddle.net/zhiyang/ahxg5301/3/
