### ISSUE TITLE
[Feature Request] Add custom class to dialog's header, body and footer

### ISSUE THREAD

**Issue by justforuse** [ElemeFE/element#12429]
### Existing Component
是

### Component Name
el-dialog

### Description
Sometimes I want to add custom class to dialog body or some else, but there is no direct prop to define it, and I think the `.my-dialog .el-dialog__body` is not elegant, so it may be great to have some props to define class

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by udbmnm** [comment]
I search dialog  header found this , i need this feature too，but now we can only modify CSS.

**Comment by udbmnm** [comment]
you can use custom-class @justforuse
