### ISSUE TITLE
 [Bug Report] When the paging component is in 0 data, clicking the jumper box will result in the repeated handover of 0 and 1.

### ISSUE THREAD

**Issue by hoythan** [ElemeFE/element#12422]
### Element UI version
2.4.6

### OS/Browsers version
 MacOS last version

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/hoythan/czgmqtxn/1/](https://jsfiddle.net/hoythan/czgmqtxn/1/)

### Steps to reproduce
当 total 为0 时，鼠标单击换页的输入框，反复失焦时，页码会从 0 - 1 反复变更
![](https://ws4.sinaimg.cn/large/006tNbRwgy1fug4xg7w14g30b403uas7.gif)
### What is Expected?
当 total 为0 时，鼠标单击换页的输入框，反复失焦时，页码会从 0 - 1 反复变更

### What is actually happening?
永远显示 1

**Comment by ng-work** [comment]
![image](https://user-images.githubusercontent.com/22250220/44332358-6f116880-a49e-11e8-8383-29c704cd0c95.png)
当 total 为0 时 应该显示第一页吧

**Comment by WormGirl** [comment]
I have the same problem
