### ISSUE TITLE
[Bug Report] Position of dialog close-button

### ISSUE THREAD

**Issue by Hannicke** [ElemeFE/element#12427]
### Element UI version
2.4.6

### OS/Browsers version
Windows 10 / Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5054/](https://jsfiddle.net/mmx38qxw/5054/)

### Steps to reproduce
当dialog  width取某一固定宽度，title文字较多，且存在标点等特殊字符时，关闭按钮有被title文字遮挡的可能

### What is Expected?
关闭按钮不应该被文字遮盖

### What is actually happening?
关闭按钮有被title文字遮盖的可能

**Comment by ziyoung** [comment]
我们没有限制 title 文字的长度，这个控制可以让用户来做。
