### ISSUE TITLE
When the number of child nodes in [Bug Report] node reaches 3000, the whole interface is carton.

### ISSUE THREAD

**Issue by chenziyue** [ElemeFE/element#12423]
### Element UI version
2.4.6

### OS/Browsers version
WINDOWS10

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
1、生成拥有3000个同一层级子节点的树
2、展开该节点
3、页面基本无法再做其他操作了，卡到不行
4、具体引起卡顿的节点数量有待验证

### What is Expected?
树节点的数量不受限

### What is actually happening?
节点数量上升，整体界面的表现不尽人意

**Comment by ziyoung** [comment]
或许你可以试着懒加载，去掉一些动画，性能会好很多。#12249

**Comment by chenziyue** [comment]
尝试关掉动画，懒加载，依旧卡到爆表，关键应该是节点的数量，同样使用jquery的z-tree，不存在这个问题

**Comment by zhangqianjun** [comment]
这个问题解决了吗  我也遇到这个问题了 去掉动画会好一点  还有更好的解决方法吗
