### ISSUE TITLE
The [Bug Report] tree component removes nodes directly from the data operation, and the components are not updated.

### ISSUE THREAD

**Issue by shuaiyaotian** [ElemeFE/element#12421]
### Element UI version
2.4.6

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3526.0 Safari/537.36

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/yt5jnqrm/](https://jsfiddle.net/yt5jnqrm/)

### Steps to reproduce
1. 点击删除按钮，data已经更新，但界面上tree的节点没有被删除
2. 点击增加按钮，data已更新，按钮新增，之前删除的节点仍然可以看到

### What is Expected?
期望直接操作数据，界面与数据同步。

### What is actually happening?
直接操作数据删除节点，界面没有同步。

**Comment by huahaichuan** [comment]
try   this.$refs.tree.remove(data);

**Comment by MrLiuTY** [comment]
@ziyoung 我也遇到同样的问题，element升级到了2.4.6出现的问题。官网上的文档删除按钮也失效了
