### ISSUE TITLE
[Bug Report] in MessageBox component, if it is not closed by button, it will cause errors.

### ISSUE THREAD

**Issue by atzcl** [ElemeFE/element#12436]
### Element UI version
2.4.6

### OS/Browsers version
Mac 10.13 / Chrome  68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
【 在 jsfiddle 中无法重现，但是在官网上面的示例是可以重现的：http://element.eleme.io/#/zh-CN/component/message-box  】
使用 MessageBox 组件，通过点击遮罩层、ESC 快捷键关闭弹窗，控制台报错：` common.js:67 Uncaught (in promise) {message: "The message port closed before a response was received."} ` ` Error in event handler for runtime.onMessage: TypeError: Cannot read property 'isVisible' of undefined `

### What is Expected?
无报错

### What is actually happening?
【 在 jsfiddle 中无法重现，但是在官网上面的示例是可以重视的：http://element.eleme.io/#/zh-CN/component/message-box  】
控制台报错：` common.js:67 Uncaught (in promise) {message: "The message port closed before a response was received."} ` ` Error in event handler for runtime.onMessage: TypeError: Cannot read property 'isVisible' of undefined `

**Comment by ziyoung** [comment]
无法重现。

**Comment by atzcl** [comment]
@ziyoung 刚刚在官网重试了下，依然存在。
![image](https://user-images.githubusercontent.com/28823188/44391931-9c741a00-a563-11e8-97b1-13cebe69dcc2.png)

**Comment by ziyoung** [comment]
你那个报错的消息来自于浏览器插件，不是 element-ui 本身的 bug。
