### ISSUE TITLE
form的验证默认message如何改成中文

### ISSUE THREAD

**Issue by ocean-7** [ElemeFE/element#1243]
表单验证的时候，每次都写message挺麻烦的，但是不写的话，默认提示是英文的。
比如这段代码就会提示：name is requred
```
<el-form-item label="名称" prop="name">
    <el-input v-model="form.name"></el-input>
</el-form-item>
```

请问，是否可以有办法进行中文化，把提示变成：名称是必填项

**Comment by Leopoldthecoder** [comment]
Element 内置了 [async-validator](https://github.com/yiminghe/async-validator)，它的默认错误信息就是英文的。这个我们应该不会改。

**Comment by tryingpzm** [comment]
这波。。等于所有el-form-item不能用required...

**Comment by chaosforfun** [comment]
这是一个国际化的 bug 啊.明明设置了中文
