### ISSUE TITLE
[Bug Report] Tree, append method has problem in lazy mode

### ISSUE THREAD

**Issue by AlkalizZ** [ElemeFE/element#12433]
### Element UI version
2.4.6

### OS/Browsers version
mac / chrome 68

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5077/](https://jsfiddle.net/mmx38qxw/5077/)

### Steps to reproduce
1. click `append data`
2. click `append data2`

### What is Expected?
`lazy` mode tree can append the data correctly like another tree

### What is actually happening?
`lazy` mode tree cannot append data
and the console show `TypeError: Cannot read property 'indexOf' of undefined`

**Comment by ziyoung** [comment]
Try to avoid appending nodes in lazy mode. ref #12235

**Comment by AlkalizZ** [comment]
But what should i do if i want to append to the root node?
i tried `getNode(0)`but i just get `null`
