### ISSUE TITLE
[Bug Report] Select is ReadOnly by default.

### ISSUE THREAD

**Issue by lonesomeme** [ElemeFE/element#12432]
### Element UI version
2.4.6

### OS/Browsers version
windows chrome 66.0.3359.139 x64

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ElemeFE/element/issues/12431](https://github.com/ElemeFE/element/issues/12431)

### Steps to reproduce
<el-form-item label="状态">
          <el-select placeholder="状态" v-model="formQuery.state">
                   <el-option v-for="item in stateOptions" :key="item.id" :label="item.text" :value="item.id"></el-option> 
          </el-select> 
</el-form-item>

output html:
<input type="text" readonly="readonly" autocomplete="off" placeholder="状态" class="el-input__inner">

### What is Expected?
select output html has no readonly property default

### What is actually happening?
select output html has readonly property default

**Comment by lonesomeme** [comment]
input:
<el-form-item label="状态"> <el-select placeholder="状态" v-model="formQuery.state"> <el-option v-for="item in stateOptions" :key="item.id" :label="item.text" :value="item.id"></el-option> </el-select> </el-form-item>

**Comment by lonesomeme** [comment]
input:
`<el-form-item label="状态"> <el-select placeholder="状态" v-model="formQuery.state"> <el-option v-for="item in stateOptions" :key="item.id" :label="item.text" :value="item.id"></el-option> </el-select> </el-form-item>`

**Comment by ziyoung** [comment]
默认情况下，Select 中 input 不允许输入，所以 readonly 设为 true。

**Comment by essramos** [comment]
Any solution on this? Im having similar issue with select being readonly on default.
