### ISSUE TITLE
[Bug Report] In ios, the cursor appears when the el-select component is selected.

### ISSUE THREAD

**Issue by L15018105103** [ElemeFE/element#12434]
### Element UI version
2.4.5

### OS/Browsers version
ios

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
1. The el-select component is used in the page and opened in the browser of ios.
2. Select the options of the drop-down box.

### What is Expected?
can select options normally.

### What is actually happening?
After selecting the option, the cursor in the input box will appear after the option string selected in the drop-down box.

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

**Comment by VincentAry** [comment]
Is solved ?
