### ISSUE TITLE
[Bug Report] Table Component Multilevel Table Header Fixed Merge Row Column has a fixed ='right'bug, fixed does not take effect

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#12430]
### Element UI version
2.3.9

### OS/Browsers version
windows10/ chrome 68

### Vue version
2.5.2

### Reproduction Link
[https://codesandbox.io/s/n3447pnnw4](https://codesandbox.io/s/n3447pnnw4)

### Steps to reproduce
直接运行代码，代码在components/testTable.vue文件中

### What is Expected?
设置fixed="right"的列可以固定在表格右边

### What is actually happening?
设置fixed="right"的列没有任何效果

**Comment by liuzhiqi** [comment]
补充：父层若添加 fixed属性，可以触发固定列（多级子列只固定第一列），若父层不添加fixed属性则子层添加fixed不生效
