### ISSUE TITLE
[Bug Report] The [Icon] is missing from the types declaration

### ISSUE THREAD

**Issue by mobei** [ElemeFE/element#12444]
### Element UI version
2.4.6

### OS/Browsers version
Mac

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/types/element-ui.d.ts](https://github.com/ElemeFE/element/blob/dev/types/element-ui.d.ts)

### Steps to reproduce
没有 icon 声明

### What is Expected?
有icon声明

### What is actually happening?
没有

**Comment by jikkai** [comment]
内部组件不提供声明文件，请通过指定 className 来使用 icon。
