### ISSUE TITLE
[Bug Report] Dialog margin changes on close

### ISSUE THREAD

**Issue by PierreTurnbull** [ElemeFE/element#12446]
### Element UI version
2.4.6

### OS/Browsers version
Ubuntu / Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/nounoursnoir/srke28uz/10/](https://jsfiddle.net/nounoursnoir/srke28uz/10/)

### Steps to reproduce
Nothing to do, I set an interval that opens/closes the dialog every 1 second.
The behaviour is difficult to perceive so you may go in the inspector and select the div with the class 'el-dialog' in order to see its margin value. It will be easy to spot if you are on Chrome since they provide a visual tool to see the borders/paddings/margins/sizes of the selected element.

### What is Expected?
The margin of the 'el-dialog' should stay the same all the time, even if a scrollbar appears when closing the dialog.

### What is actually happening?
Before the dialog closes, there is a small time in which the margin value changes.
The bug doesn't appear systematically so you may have to try a few times (for me it's about 1 out of 2 times).

I think this is due to the scrollbar appearing and disappearing. It takes some space and changes the margins of items that should be centered in the window. [It is based on `document.documentElement.clientWidth`](https://javascript.info/size-and-scroll-window), which takes the scrollbar in consideration, while it should be based on `window.innerWidth`, which doesn't take the scrollbar in consideration.
You can observe this behaviour here: https://jsfiddle.net/nounoursnoir/ajf9cxkt/5/

**Comment by ziyoung** [comment]
Maybe you need set `lock-scroll` to `false`.

**Comment by PierreTurnbull** [comment]
Well that would solve the problem but I don't want the body to be scrollable when a dialog is open

**Comment by ziyoung** [comment]
When the scroll bar appears, the width of the body element changes. We set Dialog margins to `auto` to horizontally center Dialog, so the margin changes. The same is true of bootstrap's modal. https://getbootstrap.com/docs/4.1/components/modal/

**Comment by PierreTurnbull** [comment]
I understand how it works and I find it to be a bad behaviour. However I would understand that you say you don't want to work on an issue with such little impact.
