### ISSUE TITLE
Value of [Bug Report] autocomplete should support numbers and strings.

### ISSUE THREAD

**Issue by shijunti19** [ElemeFE/element#12449]
### Element UI version
2.4.6

### OS/Browsers version
widnows10

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
     valueKey: {
        type: String,
        default: 'value'
      },
这里应该数字也支持，
当纯数字的时候这个autocomplete组件一直报错，当把数字转成字符串，因为转成小写又报错

### What is Expected?
     valueKey: {
        type: String,
        default: 'value'
      },

### What is actually happening?
     valueKey: {
        type: String,
        default: 'value'
      },

**Comment by ziyoung** [comment]
请提供一个可重现问题的链接。

**Comment by jikkai** [comment]
规范上决定了 input 输入值的类型是 `string`，请参考[这里](https://www.w3.org/TR/2012/WD-html-markup-20120315/input.text.html)

**Comment by shijunti19** [comment]
@jikkai 如果规范上不准改，那只能改这个错误toLowerCase() ，当把数字转成字符串“1“,"2","3"作为下拉选项值传进autocomplete组件的的时候，会调用toLowerCase，导致报错，toLowerCase执行前是不是应该判断下，现在的结果就是这个组件不能传纯数字的选项进去，其实select之类都不行，必须转成字符串。

**Comment by xem1987** [comment]
@ziyoung  @jikkai 我觉得二位可能没有理解楼主的问题，ValueKey是决定cb的数组对象arr中的item中的key名称，那假如返回的item也是一个数组呢？
``` js
arr = [
  ['xxx','inputValue1' ],
  ['xxx','inputValue2' ],
  ['xxx','inputValue3' ]
]
```
此时我打算把inputValue1或者inputValue2，赋值给input值，是不是ValueKey就应该是数组下标1所以ValueKey应该可以支持number类型
还有一种情况
``` js
arr = [
  'inputValue1',
  'inputValue2',
  'inputValue3'
]
```
这本应该是最简单的使用形式，但是现在的ValueKey没有空值判断或者判断item类型，所以，必须将字符串数组每一个元素再包装成对象加一个ValueKey的属性才能被组件使用，十分不方便，如果可以给ValueKey加一个空值判断，如果为空值，直接使用item赋值，会方便很多

**Comment by shijunti19** [comment]
```js
<el-autocomplete
                  v-if="column.render.name === '$user'"
                  v-model="data[column.field]"
                  type="number"
                  value-key="id"
                  :focus="(currentField = column.field)"
                  :disabled="column.disabled"
                  :clearable="true"
                  :placeholder="'请搜索' + column.title"
                  :fetch-suggestions="querySearch"
                  @select="handleSelect"
                >


data[column.field]=3


vue.runtime.esm.js?0261:619 [Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "24", got Number with value 24.

found in

---> <ElAutocomplete> at packages/autocomplete/src/autocomplete.vue
       <ElFormItem> at packages/form/src/form-item.vue
         <ElCol>
           <ElRow>
             <ElForm> at packages/form/src/form.vue
               <DataEdit>
                 <VxeModal>
                   <DataList> at src/views/data/list.vue
                     <AppMain> at src/layout/components/AppMain.vue
                       <Layout> at src/layout/index.vue
                         <App> at src/App.vue
                           <Root>
```

you should

```js

type | 类型 | string | text，textarea 和其他 原生 input 的 type 值
-- | -- | -- | --



```
