### ISSUE TITLE
[Bug Report] el-upload components cannot upload multiple images in UC browser.

### ISSUE THREAD

**Issue by Niefee** [ElemeFE/element#12443]
### Element UI version
2.0.8

### OS/Browsers version
Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1

### Vue version
2.5.9

### Reproduction Link
[https://codepen.io/niefee/pen/JajxVV](https://codepen.io/niefee/pen/JajxVV)

### Steps to reproduce
用uc浏览器或者APP内置浏览器选中多张，实际只会上传一张，其他选中的图片会被忽略，其他浏览器正常。

### What is Expected?
其实项目是用在webview中的，在iPad里的APP中选中多张，每次只能上传一张。在iPad的uc浏览器有同样的问题。同样的代码在其他平台没有问题，期待可以修复这个问题

### What is actually happening?
iPad端有兼容问题

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.
