### ISSUE TITLE
[select] 建议可以手输而不仅仅是选择

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#1244]
### ElementUI version
1.0.1

### OS/Browers version
 windows/Chrome 54

### Vue version
 2.0.7

### What is Expected?
期待实现的需求：类似QQ登陆界面的账号输入框，可以手动输入账号，也可以在下拉框里选择历史输入账号，若现有的解决方案也可以实现，还望告知，谢谢！

**Comment by Leopoldthecoder** [comment]
目前没有这个功能。和 #782 重复，会在那里更新进展，这个 issue 先关闭了。

**Comment by Leopoldthecoder** [comment]
不过你这个需求似乎可以用 `el-autocomplete` 来实现。

**Comment by topul** [comment]
@Leopoldthecoder 其实需要的应该是select带搜索那个，但是点击下拉箭头的时候又要出现全部的内容
