### ISSUE TITLE
[Bug Report] Date control reset value is invalid under IE

### ISSUE THREAD

**Issue by lmyekong** [ElemeFE/element#12455]
### Element UI version
2.4.6

### OS/Browsers version
IE10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5128/](https://jsfiddle.net/mmx38qxw/5128/)

### Steps to reproduce
Set the default value of the date control in the date method
Reset this value in the created method.

### What is Expected?
Date control shows the latest value

### What is actually happening?
Null value

**Comment by wanglang1995** [comment]
me too ,my friend

**Comment by hehuan0630** [comment]
me too,but google and FF is ok ,why?
