### ISSUE TITLE
The type attribute of allowDrop attribute is not correct when dragging [Bug Report] tee component.

### ISSUE THREAD

**Issue by caiyihua** [ElemeFE/element#12453]
### Element UI version
2.4.6

### OS/Browsers version
win 7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5124/](https://jsfiddle.net/mmx38qxw/5124/)

### Steps to reproduce
拖拽节点 到另一个节点 打开控制台 allowDrag的type值

### What is Expected?
节点偏上 应该为prev 中间 为inner 偏下为next

### What is actually happening?
永远 直接返回prev  inner  next 值

**Comment by ziyoung** [comment]
拖拽时，计算位置的比例需要再调整一下。
https://github.com/ElemeFE/element/blob/ea45d54b6789bfa83f19b39f69ea97d5ceb0e2c2/packages/tree/src/tree.vue#L408-L409
