### ISSUE TITLE
[Feature Request] font size unit use'rem'

### ISSUE THREAD

**Issue by qw8880000** [ElemeFE/element#12463]
### Existing Component
No

### Component Name
rem

### Description
希望字体单位是rem，组件也基于rem而设计，个人觉得这样适配的能力更强些。

**Comment by jikkai** [comment]
首先 Element 是针对 Desktop 端设计的，感觉改成 rem 的收效并不是很突出，我觉得关于这个点可以在这里先讨论一下

**Comment by ziyoung** [comment]
如果是面向移动端的组件库才可以使用 rem，比如[这个](https://youzan.github.io/vant/#/zh-CN/quickstart)。感觉这个功能并不是这么实用。

**Comment by jikkai** [comment]
issues 先关了，这个需求暂时不考虑实现，有其他想法可以继续讨论下。

**Comment by qinzitong** [comment]
现在pc端也需要兼容很多分辨率，使用rem 可以更好的兼容不同分辨率
