### ISSUE TITLE
[Bug Report] el-select with remote will remember the last operation when I push down enter key

### ISSUE THREAD

**Issue by MoonyPoet** [ElemeFE/element#12469]
### Element UI version
2.4.6

### OS/Browsers version
Win 10/Chrome 68.0.3440.84

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/6d29fqt1/3/](https://jsfiddle.net/6d29fqt1/3/)

### Steps to reproduce
1.select an option like 'Florida'
2.push down button called 'new' to change the value of the select
3.focus the select, and push down enter key. Then, the last choose value will fill in the select

### What is Expected?
when I perform the third step, don't change the value

### What is actually happening?
when I perform the third step, the value changed

**Comment by ziyoung** [comment]
After you change the value by hand, you need reset options. https://jsfiddle.net/zhiyang/6d29fqt1/8/

**Comment by MoonyPoet** [comment]
if el-select with filterable, and I defined the filter method.
I must show all of the options when I set the value with ''.
Now, the third step above arises again.

**Comment by MoonyPoet** [comment]
https://jsfiddle.net/oxmrwtea/11/
