### ISSUE TITLE
[Feature Request] select allow-create custom method

### ISSUE THREAD

**Issue by abcwt112** [ElemeFE/element#12468]
### Existing Component
是

### Component Name
select

### Description
Could you please add a method for select component when user create a new record.
example:
          <el-form-item label="设置标签：">
            <el-select multiple filterable placeholder="请输输入并选择或创建新标签" v-model="tags" :style="{width:'400px'}" :remote="true" :remote-method="searchTag" :loading="tagLoading"
                       value-key="id"
                       allow-create>
              <el-option v-for="item in tagList" :key="item.name" :label="item.name" :value="item"></el-option>
            </el-select>
el-option :value is "item" not "item.name". It's a Object. But in allow-create mode, the input is string. 
In that situation, v-model="tags" will contains both Object(user selected) and String(user created). So please give me a callback to change what the user created.
Thank you

**Comment by abcwt112** [comment]
example:
`            <el-select multiple filterable placeholder="请输输入并选择或创建新标签" v-model="tags" :style="{width:'400px'}" :remote="true" :remote-method="searchTag" :loading="tagLoading"
                       value-key="id"
                       allow-create>
              <el-option v-for="item in tagList" :key="item.name" :label="item.name" :value="item"></el-option>
            </el-select>`

**Comment by abcwt112** [comment]
example:
`            <el-select multiple filterable placeholder="请输输入并选择或创建新标签" v-model="tags" :style="{width:'400px'}" :remote="true" :remote-method="searchTag" :loading="tagLoading"
                       value-key="id"
                       allow-create>
              <el-option v-for="item in tagList" :key="item.name" :label="item.name" :value="item"></el-option>
            </el-select>`

**Comment by flowbywind** [comment]
解决这个问题了没 我也想要你说的这个特性

**Comment by abcwt112** [comment]
@flowbywind 
并没有...我是在使用的时候再判断...有点坑爹

**Comment by sebasijan** [comment]
This would be really useful

**Comment by Skytim** [comment]
My Method when enter, then create
 <el-select
            v-model="select"
            :remote="true"
            @keyup.enter.native="selectCreate"
            :popper-append-to-body="false"
            style="display: block"
            filterable
            allow-create
            default-first-option
          >
          </el-select>
