### ISSUE TITLE
form验证规则中type的问题

### ISSUE THREAD

**Issue by dongpeizhi** [ElemeFE/element#1246]
templete
```
<el-form :model="form" ref="form" :rules="rules">
    <el-form-item label="年龄" prop="age">
        <el-input v-model="form.age"></el-input>
    </el-form-item>
</el-form>
```

script
```
export default {
    data() {
        return: {
            form: {
               age: 0,
            },
            rules:{
              age: [
                  { type: 'integer' }
              ]
            }
        }
    }
}

```

然后即使在输入框中输入整形（比如123），也会报age is not a integer

**Comment by spademan** [comment]
从某个程度上来讲 可能真的是string 所以你可以 给 `<el-input v-model="form.age" type='number'></el-input>` 但是我觉得 element ui是可以优化一下这里

**Comment by Leopoldthecoder** [comment]
```html
<el-input v-model.number="form.age"></el-input>
```
Vue 本身就会把值默认转为 String，加 `.number` 修饰符可以解决。

**Comment by mosejiang** [comment]
如果是浮点型的呢，可以用吗？11.23 @Leopoldthecoder

**Comment by szm1002** [comment]
但是加.number修饰符后，输入123abc也能验证通过，何解？

**Comment by jikkai** [comment]
@szm1002 因为Vue 的机制如此。

`.number` 修饰符本质上是调用了 `parseFloat`，详见 Vue 的 [源码](https://github.com/vuejs/vue/blob/eea0920f14d0ea63d1b94c648eeb36ac7dfb4b05/src/shared/util.js#L74)

parseFloat 的结果如下：
![image](https://user-images.githubusercontent.com/14025786/28114695-791a39fe-6734-11e7-9f4c-669c96881c9e.png)

此时绑定数据的值不是 `123abc`，而是 `123`，验证自然能通过

**Comment by szm1002** [comment]
@jikkai 感谢解答，我知道原理是这样。但我的问题是，因为输入框限制只能输入整数，所以我就是不想让'123abc'验证通过，何解呢？

**Comment by ratelgogo** [comment]
@szm1002 将input的type设置成number，是HTML5的属性
```
<el-form :model="form" ref="form" :rules="rules">
    <el-form-item label="年龄" prop="age">
        <el-input type="number" v-model="form.age"></el-input>
    </el-form-item>
</el-form>
```

**Comment by AvaSiam** [comment]
如果需要输入的数字是带有小数点的呢
