### ISSUE TITLE
[Bug Report] el-select multiple

### ISSUE THREAD

**Issue by Zclhlmgqzc** [ElemeFE/element#12470]
### Element UI version
2.4.6

### OS/Browsers version
Win 10/Chrome 68.0.3440.84

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5189/](https://jsfiddle.net/mmx38qxw/5189/)

### Steps to reproduce
reset el-select's value(undefined or null)

### What is Expected?
reset el-select's value(undefined or null)

```js
  getValueIndex: function getValueIndex() {
    var _this12 = this;
Now:
    var arr = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];
Expected:
    var arr = arguments.length > 0 && arguments[0] ? arguments[0] : [];

...

  value: function value(val, oldVal) {
    if (this.multiple) {
      this.resetInputHeight();
Now:
      if (val.length > 0 || this.$refs.input && this.query !== '') {
        ...
Expected:
      if ((val && val.length > 0) || this.$refs.input && this.query !== '') {
        ...
```

### What is actually happening?
[Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'length' of undefined"

found in

---> <ElSelect>

VM182 vue.js:1743 TypeError: Cannot read property 'length' of undefined
    at VueComponent.value (VM161 index.js:1)
    at Watcher.run (VM182 vue.js:3231)
    at flushSchedulerQueue (VM182 vue.js:2981)
    at Array.<anonymous> (VM182 vue.js:1839)
    at MessagePort.flushCallbacks (VM182 vue.js:1760)

**Comment by jikkai** [comment]
This is because multiple Select accepts an array as value, you should reset it with an empty array.

**Comment by yoyo837** [comment]
@jikkai 动态写入字段的怎么处理？需要支持null，如果OK的话我提PR

**Comment by FionaWong** [comment]
同样的问题，解决办法

**Comment by Blankll** [comment]
need initialize the value of v-model as an empty array

`<el-select multiple v-model="value" placeholder="plesea select">`
