### ISSUE TITLE
[Feature Request] [new demand] component tree:The connection between nodes is not is

### ISSUE THREAD

**Issue by xujiujiu** [ElemeFE/element#12472]
### Existing Component
是

### Component Name
component tree

### Description
'Is-leaf' style is not enough for tree-node，the connection between tree-node is not obvious, could add class for tree-node, so we can customize the icon before the node, that such as 'is-expend'.

**Comment by ziyoung** [comment]
You set `render-content` attribute to customize the content of tree nodes. http://element-cn.eleme.io/#/en-US/component/tree#custom-node-content

**Comment by xujiujiu** [comment]
![image](https://user-images.githubusercontent.com/25719101/44520236-eb57b600-a701-11e8-8b75-0859d3d03d6f.png)
not node, is pre-node
