### ISSUE TITLE
[Feature Request] Allow for disabling of Select dropdown's auto-positioning

### ISSUE THREAD

**Issue by hsindesu** [ElemeFE/element#12486]
### Existing Component
Yes

### Component Name
el-select

### Description
The dropdown can auto-position excessively on user input when filterable. This issue may be exacerbated on custom filter methods.

**Comment by wacky6** [comment]
Please provide a demo of your problem.

**Comment by yancyknight** [comment]
![element-select](https://user-images.githubusercontent.com/10783124/44738911-86121500-aab3-11e8-91cd-c694e582e892.gif)
Link to demo from gif: https://codepen.io/yancyknight/pen/oPLaXN?editors=1010

If the dropdown is too close to the bottom for the unfiltered list, it appears above the select. Then as the list is filtered, it can suddenly jump below the select, creating a jarring experience for users. We expect that if it starts above the select, it should stay above regardless of scrolling or filtering.

**Comment by wacky6** [comment]
IMO: Ideally the positioning should be sticky, unless user scrolls the page.

**Comment by yancyknight** [comment]
I agree, on scroll the page is already moving so it's not necessary to keep the list is the same place. The jump when they filter is mostly what we're concerned about.
