### ISSUE TITLE
[Feature Request] Support pass object to el-table

### ISSUE THREAD

**Issue by myrfy001** [ElemeFE/element#12485]
### Existing Component
Yes

### Component Name
el-table

### Description
Now, el-table only support array data, If I pass an object to it, it works, but will output type check error in the console.

Suppose I have the following data, There keys are limited to a small set:
```
list: {
  'jianshu': {'user':10, 'read':20},
  'zhihu': {'user':10, 'read': 5},
  'twitter': {'user':10, 'read':20},
  'facebook': {'user':10, 'read': 5},
}
```

And I want to build a table like that:
```
    <el-table :data="list" v-loading.body="listLoading" border fit highlight-current-row style="width: 100%">
      <el-table-column align="center" label="Platform" width="205">
        <template slot-scope="scope">
          <span>{{ scope.$index }}</span>
        </template>
      </el-table-column>

      <el-table-column align="center" label="User Count" width="205">
        <template slot-scope="scope">
          <span>{{ scope.row.user }}</span>
        </template>
      </el-table-column>

      <el-table-column align="center" label="Read Count" width="400">
        <template slot-scope="scope">
          <a class="link-type" target='_blank' :herf="scope.row.link">
            {{ scope.row.read }}
          </a>
        </template>
      </el-table-column>
    </el-table>


```

The Above code really works, but the console will show 
`[Vue warn]: Invalid prop: type check failed for prop "data". Expected Array, got Object.`

I think it should allow pass object as well as array to build a table.

**Comment by jikkai** [comment]
Sorry, we have no plan to support this.

**Comment by myrfy001** [comment]
Is there any reason for not supporting this?

**Comment by huangri212** [comment]
el-table only support bind data with type of array
