### ISSUE TITLE
[Bug Report] Nuxt using element table can not SSR, the problem is not solved #5158

### ISSUE THREAD

**Issue by zhujz** [ElemeFE/element#12496]
### Element UI version
2.4.6

### OS/Browsers version
Mac Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
1、Network查看请求到的Doc文件，看这个链接https://guiltless-antler.glitch.me
2、在表格中没有对应的数据，表格中的数字1和2是异步渲染的

### What is Expected?
有没有其他解决方案让table组件能够服务端渲染

### What is actually happening?
table组件不能够服务端渲染，因为table-column 在mounted 时候才计算columns。 服务端渲染时，是不会执行mounted事件的

**Comment by jikkai** [comment]
因为 columns 的计算依赖浏览器环境，所以该步骤无法支持 SSR。
