### ISSUE TITLE
[Bug Report] Zebra print is not correct when zebra is merged.

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#12497]
### Element UI version
2.4.6

### OS/Browsers version
Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xhna5c8f/7/](https://jsfiddle.net/xhna5c8f/7/)

### Steps to reproduce
1.合并1,2行数据的第一列
2.合并3,4行数据的第一列

### What is Expected?
0.合并的行应该当成一行算
1.合并的1,2行数据背景色都为白色
2.合并的3,4行数据背景色都为蓝色

### What is actually happening?
1.第一列都是白色
2.背景色是按未合并时算的

鼠标hover在一行数据上时有同样的bug

**Comment by jikkai** [comment]
This is intentional, so we won't fix this :(
