### ISSUE TITLE
[Bug Report] Icon Background showing in Steps step

### ISSUE THREAD

**Issue by stran12** [ElemeFE/element#12494]
### Element UI version
2.4.6

### OS/Browsers version
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5227/](https://jsfiddle.net/mmx38qxw/5227/)

### Steps to reproduce
1. If you set the icon attribute in the steps UI component to an Elemen UI icon
2. Set the background of your application to a non-white color. In the above JSFiddle, I used blue to create a clear contrast in the icon background versus the application's background color.
3. Render the application and you will see the background behind the icon set to white, which is stylistically unusable.

### What is Expected?
I expect the icon to be transparent and not have a white square background when setting the icon attribute on each step of Element UI's Steps component.

### What is actually happening?
The background behind the icon set to white, which is stylistically unusable.

**Comment by jikkai** [comment]
This is not a bug. Because of the step line, the background color is required. 

![image](https://user-images.githubusercontent.com/14025786/44630116-5c5dce80-a98b-11e8-8edc-6168d28cd85d.png)

BTW, you can overwrite it with CSS.

**Comment by stran12** [comment]
Ah ok. Thank you @jikkai
