### ISSUE TITLE
[Bug Report] el-input-number do not validate when trigger is change

### ISSUE THREAD

**Issue by nailfar** [ElemeFE/element#12495]
### Element UI version
2.4.6

### OS/Browsers version
win10 - chrome68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5233/](https://jsfiddle.net/mmx38qxw/5233/)

### Steps to reproduce
1 创建el-form 表单    
el-form 绑定 规则   :rules="{ test:[{max:6,message:'test is bigger than 6',trigger:'change'}] }"
el-form-item 绑定 prop = "test"  表单中设置 el-input-number  
参见复现链接
2. 修改el-input-number 值 为 7
3.没有触发验证

### What is Expected?
 修改el-input-number 值 为 7
立即触发验证 并显示错误信息

### What is actually happening?
修改el-input-number 值 为 7
没有触发验证

**Comment by jikkai** [comment]
https://jsfiddle.net/mmx38qxw/5237/

**Comment by nailfar** [comment]
@jikkai  Change the value by typing 7 with keyboard  not click the increase button

**Comment by nailfar** [comment]
@jikkai Change the value by typing 7 with keyboard not click the increase button

**Comment by flyinglove** [comment]
> https://jsfiddle.net/mmx38qxw/5237/

i noticed that in the reproduce demo,  if i input 'a', it will trigger validation ("年龄必须为数字值"), but if i input '1a'(anything that starts with a number), this validation will not be triggered. Is this a bug?
