### ISSUE TITLE
[Feature Request] Can't use Third party icon packs like font-awesome in attribute icons

### ISSUE THREAD

**Issue by looney-toon** [ElemeFE/element#12492]
### Existing Component
Yes

### Component Name
el-input

### Description
Cannot use third party icon packs in the arrtibutes of components e.g. `<el-input suffix-icon="fa-icon-view"></el-input>`, kindly integrate this functionality or expand the Element UI icon pack

**Comment by looney-toon** [comment]
<el-input suffix-icon="fa-icon">

**Comment by jikkai** [comment]
See #9268
BTW, You can use any icons with suffix slot.
