### ISSUE TITLE
The [Bug Report] input component can still empty the content with the clear button when the form disabled, but it cannot empty itself when the form disabled, and the performance of both should be consistent.

### ISSUE THREAD

**Issue by 188007803** [ElemeFE/element#12505]
### Element UI version
2.4.6

### OS/Browsers version
MAC

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5248/](https://jsfiddle.net/mmx38qxw/5248/)

### Steps to reproduce
(1)、新建一个表单 el-form, 设置disabled
(2)、表单里建一个 el-input, 绑定 this.data.input, 并设置 clearable
(3)、this.data.input 里随便填个值，即可重现（ el-input 禁用，但仍然可以清空内容）

### What is Expected?
el-input 禁用时，不论是自己的禁用，还是继承的表单的禁用，清空按钮都应该失效才对。

### What is actually happening?
el-input 禁用时，来自自身的禁用，会让清空按钮失效，但是继承于表单的禁用，清空按钮不失效。

**Comment by ziyoung** [comment]
Duplicate of #12505

**Comment by elfman** [comment]
@ziyoung 这个issue就是 #12505 啊，你标记错了吧？

**Comment by ziyoung** [comment]
@elfman 我的锅。标记错了。😅
