### ISSUE TITLE
[Bug Report] InputNumber and select components do not support prefix and suffix of Slots.

### ISSUE THREAD

**Issue by firecodes** [ElemeFE/element#12504]
### Element UI version
2.4.6

### OS/Browsers version
google

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/firecodes/8qu9c73v/23/](https://jsfiddle.net/firecodes/8qu9c73v/23/)

### Steps to reproduce
<template>
<div id="app">
  <el-select v-model="value" placeholder="请选择">
    <el-option v-for="item in options" key="item.value"  :label="item.label" :value="item.value">
    </el-option>
    <i slot="prefix" class="el-input__icon el-icon-search"></i>
    <i slot="suffix" class="el-input__icon el-icon-date"></i>
  </el-select>
  <br/>
  <el-input-number v-model="num" :controls="false" controls-position="right" :min="1" :max="10">
    <i slot="prefix" class="el-input__icon el-icon-search"></i>
    <i slot="suffix" class="el-input__icon el-icon-date"></i>
  </el-input-number>  
</div>

</template>

### What is Expected?
希望支持，InputNumber和select增加带单位功能和事件图标， 和 input增加搜索图片功能一样

### What is actually happening?
目前不支持，需要排版后面增加

**Comment by jikkai** [comment]
Select 和 InputNumber 由于设计因素（比如已经有下拉图标或者控制按钮），不会为其添加类似 Input 的插槽。

**Comment by firecodes** [comment]
有些特殊功能，例如输入框后面带不同的图标和单位，就因为一句设计不好，就不要功能了。功能不提供，开发怎么玩，又不能改源代码，看看问题这么多。

**Comment by kenziD** [comment]
最近也遇到类似，数字框需要带单位的需求，如果InputNumber框不提供slot，就要自己用input框重新封装。很麻烦。。。为什么不能提供一下slot呢。

**Comment by davidAlittle** [comment]
If controls are disabled, then there's no design conflict.
