### ISSUE TITLE
[Feature Request] how to make Carousel scroll vertically up and down

### ISSUE THREAD

**Issue by longyunrui** [ElemeFE/element#12503]
### Existing Component
是

### Component Name
Carousel

### Description
请问能设置 Carousel 的切换方式为上下滚动而不是现在的左右滚动吗

**Comment by jikkai** [comment]
不支持，暂时也没有计划实现该功能。

**Comment by iTaster** [comment]
> 不支持，暂时也没有计划实现该功能。
希望添加一个属性，允许上下轮播（例如：滚动公告会用到）
