### ISSUE TITLE
[Bug Report] native-type native type attribute reset

### ISSUE THREAD

**Issue by huyanyawei** [ElemeFE/element#12509]
### Element UI version
2.4.6

### OS/Browsers version
W10 chrome

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN    没上线](https://elementui.github.io/issue-generator/#/zh-CN    没上线)

### Steps to reproduce
native-type 原生 type 属性 reset,    只把输入框清空了,并没有把form的值清空,

### What is Expected?
点击reset,把form的值清空,

### What is actually happening?
点击reset,并没有把form的值清空,

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
