### ISSUE TITLE
InputNumber is used in the [Bug Report] form. When the form is reset, the counter is not reset.

### ISSUE THREAD

**Issue by jianghuzai** [ElemeFE/element#12502]
### Element UI version
2.4.6

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/liguanhua/tou8xkgh/1/](https://jsfiddle.net/liguanhua/tou8xkgh/1/)

### Steps to reproduce
修改表单中的数据，然后点击重置

### What is Expected?
表单中所有数据重置为初始值

### What is actually happening?
第一个内容成功重置，但是，计数器没有重置

**Comment by jikkai** [comment]
https://jsfiddle.net/tou8xkgh/3/

**Comment by jianghuzai** [comment]
@jikkai thank you verymuch
