### ISSUE TITLE
[Feature Request] about the accordion component el-collapse has title slot, can you have a bottom slot?

### ISSUE THREAD

**Issue by 755966092** [ElemeFE/element#12506]
### Existing Component
是

### Component Name
el-collapse

### Description
就是 现在有title这个slot, 可以自定义标题, 能不能加一个底部的一个slot啊  就是折叠后显示标题和底部的slot,  
比如这个这贴面板内折叠的内容是一个订单下的几件商品, 折叠后我先显示这个订单号就是title的slot, 和 总价, 付款等按钮, 这样现在的版本是满足不了的

**Comment by jikkai** [comment]
这种场景其实破坏了 collapse 原有的功能和设计理念了，推荐自己 hack 下吧：https://jsfiddle.net/n6poj7wh/
