### ISSUE TITLE
[Bug Report] scope.row variables cannot assign values to attributes of an element.

### ISSUE THREAD

**Issue by ThomasLau** [ElemeFE/element#12510]
### Element UI version
1.3.7

### OS/Browsers version
MacOS/chrome

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/nonenonenone](https://jsfiddle.net/mmx38qxw/nonenonenone)

### Steps to reproduce
刚入门elmentui，不过发现下面这种写法，el-tooltip content没有被正确的赋值，请问这是该修复的bug还是我的写法不对？
```js
              <el-table-column prop="dataId" label="配置项" width="200">
                    <template scope="scope">
                        <el-tooltip content='{{ scope.row.memo}}'>
                           <span style="margin-left: 1px">{{ scope.row.dataId }}</span>
                        </el-tooltip>
                    </template>
                </el-table-column>
````

### What is Expected?
el-tooltip content应该是正确的memo值

### What is actually happening?
实际上是 {{ scope.row.memo}}

**Comment by wacky6** [comment]
`content='{{ scope.row.memo}}'` -> `:content='{{ scope.row.memo}}'`

---

Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by ThomasLau** [comment]
好的下次注意。
不过上面content='{{ scope.row.memo}}' -> :content='{{ scope.row.memo}}'报错了。
换成 :content='scope.row.memo' 才ok。
