### ISSUE TITLE
[Table] 可否提供自定义行高的属性

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1251]
目前有需求根据行数 算行高 不知可否提供类似属性

**Comment by furybean** [comment]
没太听懂， 行高现在是根据内容决定的。

『目前有需求根据行数 算行高』
算的是 Table 的高度，还是 Table 中行的高度？

**Comment by yelingfeng** [comment]
table每一行的高度 应该属于tr的高吧，比如我绑定个style ,return  {line-height: param + "px"}

**Comment by furybean** [comment]
目前是存在 rowClassName 属性的，可以试试这个属性能不能满足你的需求。

**Comment by yelingfeng** [comment]
rowClassName这个是class  我需要动态传值 ：)

**Comment by furybean** [comment]
@yelingfeng 还是不太理解场景，每行的行高都不一样？rowClassName 可以是动态的，可以是 Function。

**Comment by yelingfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1932350/20508928/0747925e-b0a0-11e6-8516-d4dac101f3e7.png)
table组件这个height是控制行高的吧  我想通过计算动态设置 就是这个需求。
 rowClassName只是作用到class ，我想要作用到style的height属性
行高是一样的 但是根据“表格高度” + “自定义行数” 算出来的

**Comment by furybean** [comment]
这个 height 控制的是最小高度，并不是真正的高度。
你想实现的效果是不管表格有几行，显示的都是一样的行数？

**Comment by yelingfeng** [comment]
我们需求是这样 用户表格大小可控（拖拽大小） 行数可控(输入一个行数)  根据这个动态算每一行的行高

**Comment by yelingfeng** [comment]
我们内容就是一般的文字数据 没有图片啥的 不需要内容撑开

**Comment by yelingfeng** [comment]
大神这个feature 可否考虑 ？table卡在这里了 ：（

**Comment by furybean** [comment]
#1251 已经增加 rowStyle 属性。
