### ISSUE TITLE
[Feature Request] Table uses the expand attribute to expand the column, unable to customize the expanded icon or text plus icon.

### ISSUE THREAD

**Issue by TabCrazy** [ElemeFE/element#12518]
### Existing Component
是

### Component Name
table

### Description
Table uses the expand attribute to expand the column.  You can customize the contents of the columns that expand and shrink.

table 组件 使用expand 属性时候，可以自定义展开收缩的列显示的内容

**Comment by jikkai** [comment]
展开列的内容是可以自定义的，官网例子里就有 https://jsfiddle.net/947eL0on/

**Comment by jikkai** [comment]
@TabCrazy 暂时没有计划实现该功能，可能只能先用 CSS 和 `expand-change` 进行 hack 了

**Comment by TabCrazy** [comment]
@jikkai 明白，三克油。哪就通过操作dom实现好了
