### ISSUE TITLE
[Bug Report] Click invalid under Dropdown contain Upload on FireFox

### ISSUE THREAD

**Issue by BlackEyeByLee** [ElemeFE/element#12519]
### Element UI version
2.4.6

### OS/Browsers version
win10/firefox61.0.2

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1951/](https://jsfiddle.net/mmx38qxw/1951/)

### Steps to reproduce
              <el-dropdown split-button  @command="handleCommand">
                <el-upload class="file-upload" :show-file-list="false" :action="importAction" :on-change="handleImport" accept="xlsx">
                  <el-button size="mini" type="primary">上传代发订单</el-button>
                </el-upload>
                <el-dropdown-menu slot="dropdown">
                  <el-dropdown-item command="export">下载模板</el-dropdown-item>
                </el-dropdown-menu>
              </el-dropdown>

the `el-upload ` can not run

### What is Expected?
the `el-upload `  can run

### What is actually happening?
it doesnot

**Comment by jikkai** [comment]
Issues without a valid reproduction link will be closed directly.
