### ISSUE TITLE
[Bug Report] Turn off autocomplete for date picker range

### ISSUE THREAD

**Issue by abdallanayer** [ElemeFE/element#12520]
### Element UI version
2.4.6

### OS/Browsers version
All

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/vkqLf8c3/](https://jsfiddle.net/vkqLf8c3/)

### Steps to reproduce
-Focus on datepicker range inside a form
-Autocomplete is displayed

### What is Expected?
Autocomplete should be always turned off for date range picker to be the same behaviour for  date picker

### What is actually happening?
Autocomplete is always turned on

**Comment by abdallanayer** [comment]
I created a PR to fix this issue.
https://github.com/ElemeFE/element/pull/12521

**Comment by jikkai** [comment]
Merged.
Thanks for contributing!
