### ISSUE TITLE
[Bug Report] Slider is not working when the range equals false

### ISSUE THREAD

**Issue by cguodesign** [ElemeFE/element#12523]
### Element UI version
2.4.6

### OS/Browsers version
Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/du5w78ar/](https://jsfiddle.net/du5w78ar/)

### Steps to reproduce
1. Open the attached link.

### What is Expected?
1. The slider has only one knob.
2. The slider could read the right value from the setup, which is 2 in this case

### What is actually happening?
1. The slider has two knobs
2. The value was set to [0,10] by default.

**Comment by jikkai** [comment]
https://jsfiddle.net/du5w78ar/2/
