### ISSUE TITLE
[Bug Report] element UI el-pagination problem

### ISSUE THREAD

**Issue by baby1798** [ElemeFE/element#12534]
### Element UI version
2.4.6

### OS/Browsers version
window

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
我想问下，使用el-pagination翻页器， layout="prev, pager, next, jumper" jumper属性是添加选填输入跳到指定页面，现在的问题是，输入完页码之后，点击页面任何地方都可能触发跳转，怎么控制点击指定按钮跳转

### What is Expected?
怎么控制点击指定按钮跳转

### What is actually happening?
，点击页面任何地方都可能触发跳转

**Comment by jikkai** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [SegmentFault](https://segmentfault.com/t/element-ui) 或 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
