### ISSUE TITLE
[Bug Report] 2.4.4开始，Table组件中filter不再包含“全部”

### ISSUE THREAD

**Issue by xiongsongsong** [ElemeFE/element#12538]
### Element UI version
2.4.6

### OS/Browsers version
All

### Vue version
2.5.17

### Reproduction Link
> 2.4.3 is ok. https://jsfiddle.net/fxpaomL7/44/
> 2.4.4 ~ 2.4.6 is wrong. https://jsfiddle.net/x9wz6md8/

### Steps to reproduce
1. 进入页面时，需要给filter设置一个默认值
2. 服务器可能不返回任何结果，这是需要将filter更改为全部
3. 点击filter，不出现全部。

### What is Expected?
如果":filters"指向一个空数组，点击filter出现"全部"选项。

### What is actually happening?
在2.4.4 以上版本，点击filter，无法选择全部。

**Comment by xiongsongsong** [comment]
@jikkai 效率杠杠滴！👍

**Comment by BusyHe** [comment]
v2.13.0 filter-multiple:false  问题依然存在，
