### ISSUE TITLE
[Bug Report] ElTable: empty-text does not display center

### ISSUE THREAD

**Issue by ohhoney1** [ElemeFE/element#12541]
### Element UI version
2.4.6

### OS/Browsers version
windows7 ie11.0.49

### Vue version
2.5.17

### Reproduction Link
https://s.codepen.io/cnjs/debug/VGYVPY/WPkLYNZeVXOM

### Steps to reproduce
Open your ie browser.

The reason is the commit: [#11965](https://github.com/ElemeFE/element/pull/11965), and `align-items` attr

### What is Expected?
display center

### What is actually happening?
not center

**Comment by jikkai** [comment]
Your reproduction link is broken.

`browserslist`  is assigned to `['ie > 9', 'last 2 versions']`. So i think `align-items: center` will be transformed to `-ms-flex-pack:center` at last.

https://github.com/ElemeFE/element/blob/8a32c3414f7d2b35f06a87c3b78912b3c350efd3/packages/theme-chalk/gulpfile.js#L12

**Comment by ohhoney1** [comment]
[this reproduction link works](https://s.codepen.io/cnjs/debug/VGYVPY/nqMwvGWRDyak)
and the screenshots:

![image](https://user-images.githubusercontent.com/20284707/44775477-4aa54280-aba8-11e8-9b92-32ac077f730f.png)
![image](https://user-images.githubusercontent.com/20284707/44775495-5bee4f00-aba8-11e8-8750-b96bdb012f00.png)

**Comment by jikkai** [comment]
I found an IE bug from https://github.com/philipwalton/flexbugs#flexbug-3 🤔
