### ISSUE TITLE
[Feature Request] multi-line label for <el-table-column/>

### ISSUE THREAD

**Issue by mr-chick** [ElemeFE/element#12542]
### Existing Component
Yes

### Component Name
<el-table-column>

### Description
Greetings,

Is this possible to have multiple lines as the column header? I couldn't find a way to add multiple lines on table-column header.

For example, I need something like this as column header (the date on the first line, the day name on the second one)

```php
2018.08.29
Wednesday
```

**Comment by jikkai** [comment]
https://jsfiddle.net/56sw4qez/
