### ISSUE TITLE
Daterange selector cannot be checked through form.

### ISSUE THREAD

**Issue by QT001** [ElemeFE/element#12546]
### Element UI version
2.4.6

### OS/Browsers version
win7 360浏览器

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/992695235/z8duao0w/7/](https://jsfiddle.net/992695235/z8duao0w/7/)

### Steps to reproduce
点击创建无法通过时间校验

### What is Expected?
可以通过校验，进行创建

### What is actually happening?
无论是否选择时间范围，都一直提示验证失败

**Comment by jikkai** [comment]
https://jsfiddle.net/z8duao0w/9/
