### ISSUE TITLE
[Bug Report] [el-table-column]: sort-method not working / custom sorting invalid

### ISSUE THREAD

**Issue by guahsu** [ElemeFE/element#12540]
### Element UI version
2.4.6

### OS/Browsers version
Mac / Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/67rtdvz1/1/](https://jsfiddle.net/67rtdvz1/1/)

### Steps to reproduce
Do sort / 執行排序功能

### What is Expected?
want to make some row bump to top via data.isTop / 想要透過資料中的`isTop`來使排序時某行置頂

### What is actually happening?
this is what i want to do :https://jsfiddle.net/6nba29q8/4/

發現無法達成想要的效果，即便把sortData內容改為僅return 0仍會有三段排序功能，
想達成的效果如下連結：https://jsfiddle.net/6nba29q8/4/
主要是因為看到文件上寫與Array.sort()一樣的效果才想做此嘗試，感謝！

**Comment by jikkai** [comment]
https://jsfiddle.net/67rtdvz1/3/
如果觉得 filter icon 碍事的话可以用 css 隐藏掉

**Comment by guahsu** [comment]
謝謝您的快速回覆，

想請問對於`sort-method`有方法可以得知傳入的排序類型嗎？
例如：`:sort-method="(a, b) => sortData(a, b, order)"`
因為`:sort-orders`預設有`['ascending', 'descending', null]`這三種，不知該如何獲取傳入之排序類型。

還是説`sort-method`僅可針對單一排序類型去撰寫呢？
(如同您的範例中，應該加上`sort-orders`去指明排序類型)

感謝：）
