### ISSUE TITLE
When [Bug Report] gets focus in ie11 input, pressing Enter key can not trigger change event properly.

### ISSUE THREAD

**Issue by yangmiao7** [ElemeFE/element#12543]
### Element UI version
2.4.6

### OS/Browsers version
win10，ie11

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5403/](https://jsfiddle.net/mmx38qxw/5403/)

### Steps to reproduce
ie11运行上述代码，input输入值后，获取焦点状态时按回车

### What is Expected?
触发input的change事件

### What is actually happening?
change事件没有触发，在ie11中change事件只在表单失去焦点时触发

### 其他相关问题
https://github.com/ElemeFE/element/issues/11710
因为上述问题，导致pagination中jumper组件，在ie11中输入值后按enter按键不能正常跳转（enter只能触发一次change事件）

**Comment by ziyoung** [comment]
`ElInput` 组件的 `change` 也是 `input` 输入框的 `change` 事件。一种可行的方案是监听 `keydown` 事件 https://stackoverflow.com/questions/38642802/input-change-event-on-enter-key-not-working-in-ie 。但是对于 `ElInput` 组件来讲，这个就不是原先的 `change` 事件了。

**Comment by ziyoung** [comment]
我现在倾向于用户自己监听 keydown 事件。最主要的原因是事件回调函数中的  event 参数我们很难模拟出来。
