### ISSUE TITLE
tree组件最新版，删除某一子树，数据删除了，但是见面没有变更

### ISSUE THREAD

**Issue by hanmaker-hc** [ElemeFE/element#12558]
tree组件最新版，删除某一子树，数据删除了，但是见面没有变更

**Comment by huanglins** [comment]
请问下，问题解决了吗，我也遇到了同样的问题

**Comment by cuicuicuinice** [comment]
遇到同样的问题了  直接删除tree数据源，视图一点反应都没有，但是做增加操作就会有反应，而且不知道为什么，在issues里，此类问题都被标记成无效了.......

**Comment by lanpangzhi** [comment]
更新2.4.7版本
