### ISSUE TITLE
[Feature Request] default-checked-keys parameter short circuit for all selected by default when show-checkbox is true e.g. :default-checked-keys=['*']

### ISSUE THREAD

**Issue by morgangraphics** [ElemeFE/element#12551]
### Existing Component
Yes

### Component Name
Tree

### Description
The `:default-checked-keys` attribute takes an array to select checkboxes when show-checkbox is true.

By default an empty array e.g. `:default-checked-keys=[]` doesn't select anything which is expected. 

I'm asking for a short circuit e.g. `:default-checked-keys=['*']` to select all checkboxes by default 

it might look like

`https://github.com/ElemeFE/element/blob/dev/packages/tree/src/model/tree-store.js`

```
  _initDefaultCheckedNodes() {
  const defaultCheckedKeys = this.defaultCheckedKeys || [];
  const nodesMap = this.nodesMap;

  if (defaultCheckedKeys[0] === '*'){
    nodesMap.forEach((node) => {
        node.setChecked(true, !this.checkStrictly);
    });
  } else {
    defaultCheckedKeys.forEach((checkedKey) => {
      const node = nodesMap[checkedKey];

      if (node) {
        node.setChecked(true, !this.checkStrictly);
      }
    });
  }
}
```

similar functionality could also be applied to the `setCheckedNodes` and `setCheckedKeys` methods.

**Comment by ziyoung** [comment]
It seems a good idea, but it will cause confusion. If a node value is `*`, all nodes will be checked after selecting this node. The asterisk(*) is just a string, not an asterisk in regular expression

**Comment by morgangraphics** [comment]
I figure that this would be an easier bar for entry rather than setting up the infrastructure for handling arbitrary RegEX passed in as an argument (unless this functionality exists in other components already). 

There would have to be a number of checks to see the type of data passed in. This could be a bit problematic when handling multiple types of data

```javascript
if(data instanceof Array){
          .... Do Something
} else if (data instance of RegEx){
          .... Do Something Else
} else if (data instance of String){
          .... Do Something Else Again
} else {
          .... Default to Something
}
```
The "match anything" regex in JS is something like `/.*/` anyhow. (Global being optional in multiline strings so I'm not sure this applies to id's). '*' is just a placeholder for `/.*/` anyhow. 

The reason I ask is that when you have a nested structure containing thousands of potential options, I have to maintain that Array of selected/non-selected. There are times when a "select all" option would be handy.
