### ISSUE TITLE
[Feature Request] Table collapse with tree row

### ISSUE THREAD

**Issue by SethaVa** [ElemeFE/element#12557]
### Existing Component
Yes

### Component Name
Table Expandable row

### Description
I want to use table expandable with tree table row

![2222](https://user-images.githubusercontent.com/35280240/44839006-daf68c80-ac67-11e8-9e39-06faa3152257.png)

**Comment by mt89vein** [comment]
Hi, u can place into expandable row another el-table, and it works normally
