### ISSUE TITLE
[Bug Report] default-value not working for date picker (normal and range mode)

### ISSUE THREAD

**Issue by ajerez** [ElemeFE/element#12559]
### Element UI version
2.4.6

### OS/Browsers version
OSX 10.12.6 / Chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/x6fbkz1r/](https://jsfiddle.net/x6fbkz1r/)

### Steps to reproduce
Load the demo page and the datepicker is empty by default

### What is Expected?
The datepicker have a default value, in normal and range mode

### What is actually happening?
The datepicker is empty (it happen too in your official docs https://element.eleme.io/#/en-US/component/date-picker)

**Comment by wacky6** [comment]
Please read the documentations carefully. `default-value` means the "default date of the calendar".
![image](https://user-images.githubusercontent.com/9319556/44844676-e7421000-ac8e-11e8-9af0-d4e98ae6ef8f.png)

To achieve what you said, use v-model / value directly. https://jsfiddle.net/h7v29d5j/
