### ISSUE TITLE
[Bug Report] table flashes when routing is added to keep-alive.

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#12566]
### Element UI version
2.4.6

### OS/Browsers version
chrome63, qq浏览器

### Vue version
2.5.17

### Reproduction Link
[https://wkvjx02jj8.codesandbox.io/#/foo](https://wkvjx02jj8.codesandbox.io/#/foo)

### Steps to reproduce
打开codesandbox, 在页面一和页面二来回切换,表格闪烁

### What is Expected?
不闪烁,chrome 最新版不会闪烁

### What is actually happening?
经常闪烁

**Comment by ziyoung** [comment]
无法重现。
![kapture 2018-08-31 at 16 53 56](https://user-images.githubusercontent.com/12947422/44903248-9853b380-ad3e-11e8-8a9f-bf7be64a36de.gif)

**Comment by zlab** [comment]
chrome63

**Comment by zlab** [comment]
safari百分百重现

**Comment by zlab** [comment]
目前chrome68没有问题
