### ISSUE TITLE
Trigger action on pagination component

### ISSUE THREAD

**Issue by kwnovi** [ElemeFE/element#1256]
### ElementUI version
1.0.0-rc.2 

### OS/Browers version
macOS/Chrome 53 

### Vue version
 2.0.0-rc.4

I'm using the pagination component : 
`el-pagination(layout='prev, pager, next', :total='1000', :current-page=" @current-change="handleChange")
`
But I can't manage to trigger an action when the user click on an element of the pagination component (preview, next or a number on the list) 

```
methods : {

   [...] 

    handleChange : function(val) {
        console.log('current page:', val);
    }
}
```

**Comment by furybean** [comment]
if element-ui version is 1.0.0-rc.2, @current-change should rename to @currentchange.
