### ISSUE TITLE
If [Bug Report] el-tooltip is combined with el-table, the width of table column will not expand adaptively.

### ISSUE THREAD

**Issue by ZinLeo** [ElemeFE/element#12568]
### Element UI version
2.3.9

### OS/Browsers version
chrom次新、最新版本都一样

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mz8cs9r7/2/](https://jsfiddle.net/mz8cs9r7/2/)

### Steps to reproduce
直接看 jsfiddle 源码，代码都是从文档中 copy 进去的

### What is Expected?
表格的列宽度自动拓展

### What is actually happening?
列宽度即使设置了min-width也不会自动拓展

**Comment by ziyoung** [comment]
应该是 autofocus 属性的兼容性问题，而不是 element 本身的 bug。你可以尝试监听 `visible` 的变化，手动让第一个 input 聚焦。

**Comment by ZinLeo** [comment]
excuse me?
提的 bug 哪个地方和 input、autofocus 有关了？
别欺负我读的书少
![image](https://user-images.githubusercontent.com/12324444/44969779-464ea000-af81-11e8-9b77-e11635aa705a.png)

**Comment by ziyoung** [comment]
@ZinLeo 我的锅。跟这个 issue 12576 搞混了。

**Comment by ziyoung** [comment]
我觉得你这个问题不太好解决😅。table 的宽度需要外部元素的宽度计算得来，而 tooltip 的 popper 绝对定位，宽度又由里面的元素决定。官网上的这个例子[http://element-cn.eleme.io/#/zh-CN/component/popover#qian-tao-xin-xi] 给 table 加了个宽度。

**Comment by ziyoung** [comment]
这种场景下，目前也没有更好的解决方案，还是手动添加给 table 一个宽度吧。
