### ISSUE TITLE
[Bug Report] select componment, Option disabled Attributes not working

### ISSUE THREAD

**Issue by xiaohp** [ElemeFE/element#12569]
### Element UI version
2.4.6

### OS/Browsers version
macOS 10.13.3/ chrome  68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/ogfjx20d/1/](https://jsfiddle.net/ogfjx20d/1/)

### Steps to reproduce
the second option set disabled attr true , but not working 

### What is Expected?
the disabled option can't select

### What is actually happening?
the disabled option could select

**Comment by ziyoung** [comment]
```
<option :disabled="item.disabled">
```
https://jsfiddle.net/zhiyang/ogfjx20d/2/
