### ISSUE TITLE
[Feature Request] Add input key validation at el-input-number. 

### ISSUE THREAD

**Issue by arxanter** [ElemeFE/element#12573]
### Existing Component
Yes

### Component Name
el-input-number

### Description
While user is typing not number key it symbol mustn't be in v-model input.  Ignoring that symbol. And control max and min attr during typing value
It happens when occurs @change.  But can it happend when user typing the key?

Example input-number at IView lib 
https://www.iviewui.com/components/input-number-en

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by arxanter** [comment]
If I make a PR would you approve it?
