### ISSUE TITLE
[Bug Report] input autofocus can only be focused once in dialog.

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#12576]
### Element UI version
2.4.6

### OS/Browsers version
chrome68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/zhanqi/u9aw31jf/](https://jsfiddle.net/zhanqi/u9aw31jf/)

### Steps to reproduce
1. 点击【测试】按钮
2. 第一个输入框获得了焦点
3.点击关闭，dialog已销毁
4.点击【测试】按钮
5.无法获得焦点

### What is Expected?
每次打开都能获得焦点

### What is actually happening?
只有第一次可以获得焦点

**Comment by zlab** [comment]
mac safari 没有问题，mac chrome68可以重现

**Comment by ziyoung** [comment]
应该是 autofocus 属性的兼容性问题，可以试着监听 visible 的变化，手动让 input 聚焦。

**Comment by zlab** [comment]
@ziyoung 就这样关了??

**Comment by tudi2d** [comment]
Why is this issue closed? I´m facing the same problem. Manually focusing elements is not a great work around...
