### ISSUE TITLE
Popover under [Bug Report] double scroll bars will trigger bug that cannot be updated in real time.

### ISSUE THREAD

**Issue by cjd6568358** [ElemeFE/element#12579]
### Element UI version
2.4.6

### OS/Browsers version
window7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
popover 在双滚动条下 可以正常响应父级滚动行为，父级的父级就无法响应了

### What is Expected?
可以正常显示

### What is actually happening?
无法正常显示

**Comment by cjd6568358** [comment]
![gif](https://user-images.githubusercontent.com/3970494/44952701-9f9ecc80-aeb8-11e8-814f-48800359211c.gif)

**Comment by cjd6568358** [comment]
@ziyoung 
帐号 admin/YunbanSp123. 
左侧部门中dropdown-menu 组件在右侧滚动条滚动时不跟随滚动
https://qa-ecard.iyunban.com/user 
![image](https://user-images.githubusercontent.com/3970494/44992843-162bef00-afcb-11e8-8279-63cdb2ae3381.png)

**Comment by cjd6568358** [comment]
@ziyoung
点击导航弹出popover 组件出现双滚动条只响应直接父级滚动行为，父级的父级滚动条滚动时不跟随滚动
https://qa-ecard.iyunban.com/card/package
![image](https://user-images.githubusercontent.com/3970494/44993052-c1d53f00-afcb-11e8-8c66-61c30c958e86.png)

**Comment by cjd6568358** [comment]
@ziyoung 链接给了 麻烦给下邮箱

**Comment by island205** [comment]
@cjd6568358 zhi.cun@ele.me 发这里

**Comment by BusyHe** [comment]
+1
