### ISSUE TITLE
[Feature Request] el-cascader @change method triggering problem

### ISSUE THREAD

**Issue by Gmle7** [ElemeFE/element#12572]
### Existing Component
是

### Component Name
el-cascader

### Description
el-cascader组件的change事件，在有多个层级时，改变其中的两级数据，会触发两次change事件。能不能无论更改了几层数据，整个change事件只在修改最后一层数据的时候触发？

**Comment by Gmle7** [comment]
sorry,I forget Attributes：change-on-select

**Comment by Gmle7** [comment]
I used Attributes：change-on-select

**Comment by Gmle7** [comment]
在使用blur事件时，最后一层的数据也不会被绑定

**Comment by ziyoung** [comment]
如果是设置了 `change-on-select`，点击或移入选项即表示选中该项。这时候，值改变了，那么接下来 change 事件肯定要触发。

**Comment by Gmle7** [comment]
假设整个数据有三层，那么我在设置了change-on-select之后，想用click拉出子选项，那么点击第二层想打开第三层时，就会直接触发change事件。就没法取到第三层的值了。用hover就更容易触发change事件了。有没有好的办法可以解决这个问题。

**Comment by yhnbgfd** [comment]
我也有这个问题，我的需求其实是“允许用户选择任意一级选项”，但是看了文档目前只有change-on-select才能实现，但是change-on-select导致的change事件频繁触发又不是我想要的。
