### ISSUE TITLE
[Bug Report] el-table@cell-mouse-enter/leave event conflicts with el-dialog:visible

### ISSUE THREAD

**Issue by git8023** [ElemeFE/element#12575]
### Element UI version
2.4.6

### OS/Browsers version
Windows10 x64 / Google Chrome 版本 67.0.3396.99（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5447/](https://jsfiddle.net/mmx38qxw/5447/)

### Steps to reproduce
1. 监听表格的 `cell-mouse-enter/leave` 两个事件
2. 鼠标进入单元格, 执行`cell-mouse-enter`函数, dialog对话框显示

### What is Expected?
1. 鼠标进入单元格, 显示dialog
2. 鼠标离开单元格, 隐藏dialog    

Ps: dialog只有一个, 但内容会根据单元格所处的行数据不同而不同

### What is actually happening?
鼠标进入单元格后观察的结果如下:   
> cell-mouse-enter -> visible=true -> cell-mouse-leave    

`cell-mouse-leave` 在dialog显示的瞬间被执行, 导致鼠标不离开单元格, dialog就会不停的显示/隐藏/显示/...  

dialog已启用属性 `modal=false`

**Comment by jikkai** [comment]
即使 `modal` 设置为 `false`，Dialog 也是有外层容器遮罩的。因此打开 dialog 的同时本来就应该触发`cell-mouse-enter`，这是预期正常行为。

**Comment by gdmec07150942** [comment]
我这边试过
Element UI version
2.4.11
OS/Browsers version
Windows10 x64 / Google Chrome 版本 67.0.3396.99（正式版本） （64 位）
Steps to reproduce
监听表格的 cell-mouse-enter/leave 两个事件
鼠标进入单元格, 执行cell-mouse-enter函数, 输出打印1，鼠标只要右移动几下，没有移出单元格，却会触发 cell-mouse-leave事件，输出打印了2
