### ISSUE TITLE
[Bug Report] Remote Search is unable to open the system keyboard input on IOS.

### ISSUE THREAD

**Issue by ch8771** [ElemeFE/element#12588]
### Element UI version
2.4.6

### OS/Browsers version
ios11/safari

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5507/](https://jsfiddle.net/mmx38qxw/5507/)

### Steps to reproduce
使用iphone/ipad系统内置的safari浏览器打开连接，点击Remote Search，无法正常弹出系统键盘进行输入；当将Remote Search 的multiple设置为true后，方可进行键盘输入

### What is Expected?
Remote Search 的multiple设置为false时，也可进行键盘输入

### What is actually happening?
Remote Search 的multiple设置为false时，无法唤醒系统键盘进行输入

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.
