### ISSUE TITLE
[Bug Report] DateTimePicker to form banned bug

### ISSUE THREAD

**Issue by zhaixinhua** [ElemeFE/element#12583]
### Element UI version
2.4.6

### OS/Browsers version
Win10/google，Mac/google

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/zhaixinhua/za6dsxg2/](https://jsfiddle.net/zhaixinhua/za6dsxg2/)

### Steps to reproduce
1.设置禁选日期；（例子中已设置）
2.更改上面的输入框中的时间为禁选的时间
3.确认保存
4.发现日期为禁选的日期

### What is Expected?
禁选日期无论在哪里输入永远禁选

### What is actually happening?
禁选日期仅仅不能点选，但能输入选择

**Comment by ziyoung** [comment]
无法重现。

**Comment by zhaixinhua** [comment]
![bug](https://user-images.githubusercontent.com/25002917/44966546-704a9700-af6e-11e8-844b-9da289ce0269.jpg)

**Comment by ziyoung** [comment]
还是无法重现。是不是你电脑的时间修改过了？
![kapture 2018-09-03 at 11 58 25](https://user-images.githubusercontent.com/12947422/44966951-bf91c700-af70-11e8-883c-6cec5a20034a.gif)

**Comment by zhaixinhua** [comment]
你那个上面没有输入框，我是通过输入框更改的，不是选择的
