### ISSUE TITLE
[Feature Request] can Tree support non-unique node-key?

### ISSUE THREAD

**Issue by Twinkle999** [ElemeFE/element#12585]
### Existing Component
是

### Component Name
Tree

### Description
Some time Tree has non-unique node-key, if I use Tree component, once I choose a non-unique node-key node, and I delete it ,  it can't delete the selected style in the Tree component, and then i choose another node, the one i delete non-unique node-key node appear, **i wonder if it is possible for Element UI team to support non-unique node-key Tree component**, i think it is very useful for everyone. I am looking forward to your reply.

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this. We use nodeKey as the id of TreeNode. If two TreeNodes have the same key, it may cause chaos when you delete or remove TreeNode.
