### ISSUE TITLE
[Bug Report] Checkbox Group multi row Checkbox arrangement chaos

### ISSUE THREAD

**Issue by dsjtlmy** [ElemeFE/element#12586]
### Element UI version
2.4.6

### OS/Browsers version
Win10  Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/gpbt65s2/1/](https://jsfiddle.net/gpbt65s2/1/)

### Steps to reproduce
1、点击官网组件>Form>Form 表单 http://element-cn.eleme.io/#/zh-CN/component/form 。
2、查看第一个示例 “典型表单”，可以看到双行复选框排列整齐。
3、点击下面的“在线运行”，打开网址 https://jsfiddle.net/api/post/library/pure/ 。
4、修改在线示例的的 SCSS 部分，增加样式 #app{width:520px}。 点击 Run 运行。
5、结果：在线示例与官网示例不同。 多行Checkbox 排列不整齐。

### What is Expected?
多行Checkbox 排列整齐。

### What is actually happening?
多行Checkbox 排列不整齐。

**Comment by ziyoung** [comment]
宽度不够的，内容换行显示。
![image](https://user-images.githubusercontent.com/12947422/44971016-a4ca4d00-af86-11e8-9f5c-f56a8a368d29.png)
第二行的那个如果没有对齐，你完全可以通过 CSS 来对齐。
