### ISSUE TITLE
The way of [Bug Report] service calls loading into target. After repeated calls, it becomes global loading.

### ISSUE THREAD

**Issue by LiuSuY** [ElemeFE/element#12584]
### Element UI version
2.4.6

### OS/Browsers version
mac / chrome V68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://github.com/LiuSuY/marketplace_view](https://github.com/LiuSuY/marketplace_view)

### Steps to reproduce
版本为vue3.0
1 点击login 进入 login 页
2 连续点击 register 按钮 出现问题 

### What is Expected?
 连续多次重复点击后不会变成全局loading

### What is actually happening?
连续多次重复点击后依然是局部loading

**Comment by ziyoung** [comment]
在 https://jsfiddle.net/ 上新建了 demo 吧。

**Comment by LiuSuY** [comment]
并没有，打不开这个网站




------------------ 原始邮件 ------------------
发件人: "hetech"<notifications@github.com>;
发送时间: 2018年9月3日(星期一) 中午11:57
收件人: "ElemeFE/element"<element@noreply.github.com>;
抄送: "雅殇"<851209312@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ElemeFE/element] The way of [Bug Report] service calls loadinginto target. After repeated calls, it becomes global loading. (#12584)




在 https://jsfiddle.net/ 上新建了 demo 吧。
