### ISSUE TITLE
[Feature Request] Whether the datepicker component supports input icon configuration

### ISSUE THREAD

**Issue by DvShu** [ElemeFE/element#12589]
### Existing Component
是

### Component Name
DatePicker

### Description
The UI designer asked to put the icon of the input behind, Whether the datepicker component supports input icon configuration similar to the input configuration。

**Comment by island205** [comment]
来个放 icon 示例截图看看

**Comment by ReconcileMySelf** [comment]
我就需要一个在 input 输入框中带icon的输入框的示例一样，把图标放置到后面
