### ISSUE TITLE
[Feature Request] Add a "router" attribute on Menu-Item

### ISSUE THREAD

**Issue by qdechochen** [ElemeFE/element#12594]
### Existing Component
是

### Component Name
Menu-Item

### Description
I have a Menu, and there are 20  items under it. With "router" set to true, it's very convenient to route. But for only a few menu items, I want to use my own @click. So I suggest to add an attribute "router" on MenuItem, to prevent the behavior inherits from Menu. And maybe it can also be added to Menu-Group.

**Comment by csvwolf** [comment]
Duplicate https://github.com/ElemeFE/element/issues/13292
