### ISSUE TITLE
[Bug Report]  Does render-header support $refs to get a component instance?

### ISSUE THREAD

**Issue by proceduremonkey** [ElemeFE/element#12592]
### Element UI version
2.4.6

### OS/Browsers version
windows 10 /chrome 68.0.3440.84

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/mmx38qxw/5515/

### Steps to reproduce
I want to introduce reusable components into the custom header and call the component's methods, but I can't access it via vue's $refs

### What is Expected?
I want to introduce reusable components into the custom header and call the component's methods, but I can't access it via vue's $refs

### What is actually happening?
I want to introduce reusable components into the custom header and call the component's methods, but I can't access it via vue's $refs

**Comment by ziyoung** [comment]
`ref` is supported. https://jsfiddle.net/zhiyang/mmx38qxw/5522/

**Comment by proceduremonkey** [comment]
thanks for your reply . I mean FitlterValue is a component ,but $refs only callback table dom without the component instance,so I can't call  it's methods

**Comment by ziyoung** [comment]
It seems hard to get this component instances.
https://jsfiddle.net/9uL6om82/18/
