### ISSUE TITLE
[Feature Request] Autocomplete: Allow not using popper

### ISSUE THREAD

**Issue by SebT** [ElemeFE/element#12602]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
Greetings,

I'm trying to use the autocomplete component but I don't want the suggestions to be displayed in a popover. I just want them to be displayed under my input.

So I've used `:popper-append-to-body="false"`, now I have to remove ALL style from popper, which is hacky and dirty. 
Isn't there already a way to disable all popper styles?

If not, I think this would be a nice feature to have, agnostic autocomplete logic with a default, overridable suggestions display.

**Comment by ziyoung** [comment]
`Autocomplete` uses `vue-popper` mixin which can recalculate the position of popper when the page scrolls. If you don't want to use popper, I think you can write you owner autocomplete by using `ElInput`.
