### ISSUE TITLE
[Bug Report] The initial currentPage doesn't work

### ISSUE THREAD

**Issue by bowencool** [ElemeFE/element#12608]
### Element UI version
2.4.6

### OS/Browsers version
Chrome版本 68.0.3440.106（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/1wr3t9ed/29/](https://jsfiddle.net/1wr3t9ed/29/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/20217146/45006926-d8ac7d80-b02d-11e8-8534-5c56256e3331.png)

### What is Expected?
能按照预期展示

### What is actually happening?
没能按照预期显示

**Comment by bowencool** [comment]
找到复现方法了 https://jsfiddle.net/1wr3t9ed/29/

**Comment by YKKate** [comment]
I found that when the total is 0, it will cause currentPage to be always 1.
I can use currentPage successfully with v-if="total > 0"

[https://jsfiddle.net/1wr3t9ed/31/](https://jsfiddle.net/1wr3t9ed/31/)
