### ISSUE TITLE
[Bug Report] el-pagination paging component search bug, is there a better solution?

### ISSUE THREAD

**Issue by julietdesigner** [ElemeFE/element#12601]
### Element UI version
2.4.6

### OS/Browsers version
chrome  67.0.3396.99

### Vue version
2.5.16

### Reproduction Link
[https://github.com/ElemeFE/element/issues/12600](https://github.com/ElemeFE/element/issues/12600)

### Steps to reproduce
elementUI 分页组件 el-pagination 搜索bug
1、先点击到第 N（N>=2）
2、然后搜索某个内容，
3、最后重置搜索内容，页面跳到 第1页，
4、在这个基础上点击第 N 页无反应，无法触发组件current-change事件

解决
利用 v-if 强制刷新分页组件

### What is Expected?
current-change事件触发

### What is actually happening?
分页组件 el-pagination 搜索bug
1、先点击到第 N（N>=2）
2、然后搜索某个内容，
3、最后重置搜索内容，页面跳到 第1页，
4、在这个基础上点击第 N 页无反应，无法触发组件current-change事件

**Comment by ziyoung** [comment]
在 https://jsfiddle.net/ 新建个 demo，描述一下你的问题吧。

**Comment by Leeesin** [comment]
我也碰到这个问题了

**Comment by julietdesigner** [comment]
更新到最新版本就好了
