### ISSUE TITLE
[Bug Report] date-picker`s 'editable="false" clearable="false"' does not work

### ISSUE THREAD

**Issue by hacker0000** [ElemeFE/element#12604]
### Element UI version
2.4.6

### OS/Browsers version
win10 / chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/qr0cLo7x/1/](https://jsfiddle.net/qr0cLo7x/1/)

### Steps to reproduce
为默认的date-picker加上'editable="false" clearable="false"'属性，实测未生效，大胆猜测应该不止这两个属性有类似问题...

### What is Expected?
生效

### What is actually happening?
未生效

**Comment by ziyoung** [comment]
[如何传入一个布尔值](https://cn.vuejs.org/v2/guide/components-props.html#%E4%BC%A0%E5%85%A5%E4%B8%80%E4%B8%AA%E5%B8%83%E5%B0%94%E5%80%BC)

**Comment by Renhj90520** [comment]
@ziyoung  :clearable="false" 弹出的面板上仍然有清空
