### ISSUE TITLE
[Bug Report] After changing the scrollbar style globally, when the table height is set to hold the left fixed column, the left fixed column blocks the horizontal scrollbar, and the scroll to the bottom border will dislocate

### ISSUE THREAD

**Issue by zhangzhi93** [ElemeFE/element#12607]
### Element UI version
2.4.6

### OS/Browsers version
window10/chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5538/](https://jsfiddle.net/mmx38qxw/5538/)

### Steps to reproduce
下拉到最下面，即可看到fixed列挡住了横向滚动条，并且最下面几行分隔线错位

### What is Expected?
自定义滚动条时不挡住滚动条，横线不错位

### What is actually happening?
滚动条被遮挡，横线错位，感觉是自定义滚动条之后计算表格高度时有误

**Comment by guohuihot** [comment]
我也遇到这个问题了，这个滚动条宽度是根据哪个元素计算的？

**Comment by guohuihot** [comment]
看了源码，是根据这个class “el-scrollbar__wrap”计算宽度的，如果有需要修改宽度，可以设置这个class

**Comment by zhangzhi93** [comment]
> 看了源码，是根据这个class “el-scrollbar__wrap”计算宽度的，如果有需要修改宽度，可以设置这个class
👍，我试下

**Comment by zhangzhi93** [comment]
> 看了源码，是根据这个class “el-scrollbar__wrap”计算宽度的，如果有需要修改宽度，可以设置这个class

👍，我试下

**Comment by NewNewKing** [comment]
我也看了源码  bug产生的原因是scrollbar的 height 和width是不一致造成的  需要源码修复

**Comment by hoythan** [comment]
> 看了源码，是根据这个class “el-scrollbar__wrap”计算宽度的，如果有需要修改宽度，可以设置这个class

请教是如何添加这个class的在哪个位置？

**Comment by guohuihot** [comment]
> > 看了源码，是根据这个class “el-scrollbar__wrap”计算宽度的，如果有需要修改宽度，可以设置这个class
> 
> 请教是如何添加这个class的在哪个位置？

我没调整位置，我只是设置了大小，因为列表的的大小是根据这个class计算的，其它的我没怎么动
