### ISSUE TITLE
The [Bug Report] tree component, which sets the first two nodes to chekeNode in lazy load mode, selects all of them when the load expands

### ISSUE THREAD

**Issue by otizis** [ElemeFE/element#12617]
### Element UI version
2.4.6

### OS/Browsers version
win10，chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/jaxer/xmkf90zd/10/](https://jsfiddle.net/jaxer/xmkf90zd/10/)

### Steps to reproduce
打开页面即现。
==
代码逻辑：
1. 设置tree为懒加载
2. 增加一个默认展开节点
3. 在load函数前设置选中节点，为子节点的前2个以上连续节点。
4. 节点展开后，选中了所有。

### What is Expected?
自动展开后只选中了1，2

### What is actually happening?
自动展开后选中可所有节点。
==
设置checkedNode 为 [1，2] 会出现 选中全部的bug。
若是设置选中[2，3]不会出现这个问题，只会选中 2 和 3 节点。

**Comment by ziyoung** [comment]
Duplicate of #12383
