### ISSUE TITLE
[Bug Report] resetFields throw error with dynimic form items

### ISSUE THREAD

**Issue by cjz9032** [ElemeFE/element#12618]
### Element UI version
2.0.11

### OS/Browsers version
windows7 - chrome 68

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/cjz9032/k5Lsgan4/16/](https://jsfiddle.net/cjz9032/k5Lsgan4/16/)

### Steps to reproduce
1.Add domain
2.Reset form
3.Error: please transfer a valid prop path to form item!

### What is Expected?
would not throw error

### What is actually happening?
 throw error

**Comment by ziyoung** [comment]
The prop of FormItem is `domains.0.value`, and FormItem can't get vaue from form model. https://jsfiddle.net/k5Lsgan4/20/
