### ISSUE TITLE
[Bug Report] Checkbox Group multi row Checkbox arrangement using v-for

### ISSUE THREAD

**Issue by nuneramu** [ElemeFE/element#12615]
### Element UI version
2.3.2

### OS/Browsers version
Version 68.0.3440.106

### Vue version
2.5.16

### Reproduction Link
https://jsfiddle.net/rnune/5xpy4s2j/6/

### Steps to reproduce
I want checkbox group elements to be aligned one element on each row (display: block) sort of.

### What is Expected?
An element on each row with proper styling.

### What is actually happening?
It is having elements inline

**Comment by ziyoung** [comment]
https://jsfiddle.net/zhiyang/5xpy4s2j/8/

**Comment by nuneramu** [comment]
@ziyoung ziyoung
I implemented the correction you mentioned but for me when content is more it is showing like the one below
![pic](https://user-images.githubusercontent.com/10026061/45154195-62a64300-b1f4-11e8-9db5-4290054354e9.png)

1) https://jsfiddle.net/zhiyang/5xpy4s2j/8/

**Comment by thukuwanjiku** [comment]
@ziyoung I'm having a similar problem.
The labels i'm using for the group checkboxes are quite long and flowing out of the parent container
![eleme-checkboxes-misaligned](https://user-images.githubusercontent.com/17809323/48068774-c80eb400-e1e4-11e8-97e1-695cae8e3702.png)



I tried fiddling with the css a little on the chrome dev tools and almost achived what I desire

![eleme-checkbox-desired](https://user-images.githubusercontent.com/17809323/48068817-e4125580-e1e4-11e8-9194-ce612c3ca047.png)

How can I or override the checkbox css to get this?
