### ISSUE TITLE
[Bug Report] select component, clicking on the first click will have no animation effect. It's normal after the second time. Use ie11 browser normal

### ISSUE THREAD

**Issue by Breezes1993** [ElemeFE/element#12623]
### Element UI version
2.4.6

### OS/Browsers version
68.0.3440.106（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、重启浏览器
2、重新进入点击select组件

### What is Expected?
第一次点击的时候，卡顿，动画效果无，或者被卡顿影响

### What is actually happening?
第一次点击的时候，跟第二次之后的点击，有同样的效果，不卡顿

**Comment by ziyoung** [comment]
Duplicate of #11629
