### ISSUE TITLE
[Bug Report] table filter menu doesn't disappear when the table in a iframe and click outside of this iframe

### ISSUE THREAD

**Issue by duola8789** [ElemeFE/element#12622]
### Element UI version
2.4.6

### OS/Browsers version
win7/chrome68.0.3440.75

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/mmx38qxw/5565/](http://jsfiddle.net/mmx38qxw/5565/)

### Steps to reproduce
1. Put a page which contains <el-table> in a iframe
2. Click the filter button of the table and the filter menu will popup
3. Click  outer region of the iframe

### What is Expected?
the filter menu disappears

### What is actually happening?
the filter menu doesn't disappear

**Comment by ziyoung** [comment]
If you click outside of a frame, it means this click can't be captured by this frame. Also, you should avoid using iframe. https://stackoverflow.com/questions/23178505/good-reasons-why-not-to-use-iframes-in-page-content
