### ISSUE TITLE
select远程搜索时想用事件填写value的bug

### ISSUE THREAD

**Issue by liwenkuiJG** [ElemeFE/element#1262]
### ElementUI version

1.0.1
### OS/Browers version

win7 x64/Chrome
### Vue version

2.0.7
### Reproduction Link

http://jsfiddle.net/feqzxzcx/9/
### Steps to reproduce
在上面加上的链接加上下面的代码
<el-button type="primary" @click.native="changeInfo">修改</el-button>
methods: {
      changeInfo() {
        this.options4 = [{ value: "Tennessee", label: "Tennessee" }];
        this.value9 = ["Tennessee"];
      }
}
### What is Expected?
当点击‘修改’事件时，select的值为‘Tennessee’，并显示‘Tennessee’。
### What is actually happening?
点击‘修改’事件时，select的值为‘Tennessee’，但不显示‘Tennessee’。

**Comment by Leopoldthecoder** [comment]
Fixed in #1401
