### ISSUE TITLE
[Feature Request] El-Table when there's a large amount of data need to display, the scrolling performance is getting unsatisfactory

### ISSUE THREAD

**Issue by CalvinVon** [ElemeFE/element#12626]
### Existing Component
是

### Component Name
el-table

### Description
El-Table: when there's large amount of data need to display, the scrolling performance is getting unsatisfactory.
So, it is recommended that VIRTUAL scroll can be built in to improve this situation.

**Comment by ziyoung** [comment]
Duplicate of #6089
