### ISSUE TITLE
[Bug Report] check-on-click-node property set to true, click the text of the tree node, unable to check the current node

### ISSUE THREAD

**Issue by hardy-maxtry** [ElemeFE/element#12627]
### Element UI version
2.3.6

### OS/Browsers version
mac OS 10.13.6 / chrome 68

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5598/](https://jsfiddle.net/mmx38qxw/5598/)

### Steps to reproduce
在设置check-on-click-node=true后
点击树节点的文本，无法勾选当前节点

### What is Expected?
check-on-click-node=true 正确生效

### What is actually happening?
check-on-click-node属性设置为true后，点击树节点的文本，无法勾选当前节点

**Comment by ziyoung** [comment]
@hardy-maxtry Element 的版本是 2.3.6，升级版本就好了。https://jsfiddle.net/zhiyang/mmx38qxw/5889/
