### ISSUE TITLE
element-ui 2.4.6版本  树形菜单 自定义节点内容  删除那块有bug .

### ISSUE THREAD

**Issue by xdlumia** [ElemeFE/element#12636]
<!--
重要: 请使用以下链接创建新 issue

  https://elementui.github.io/issue-generator

未通过以上链接创建的 issue 会被机器人直接关闭。

########

element-ui 2.4.6版本  树形菜单 自定义节点内容  删除那块有bug .

**Comment by xdlumia** [comment]
element-ui 2.4.6版本  树形菜单 自定义节点内容  删除那块有bug . 只能新增 不能删除 2.4.5就没有问题

**Comment by DAHU123** [comment]
element-ui 2.4.6版本 树形菜单 删除 就不能通过官网提供的那种方式去删除，你们看下是什么情况？
