### ISSUE TITLE
更新element1.0.2 版本后，弹出层失效

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1263]
项目中使用1.0.0的时候弹出层是正常的，昨天刚刚将1.0.0更改为1.0.2后，弹出层失效。
![image](https://cloud.githubusercontent.com/assets/16740731/20510630/cba0486a-b0ac-11e6-85e3-08380ed06db2.png)

**Comment by Leopoldthecoder** [comment]
请帖代码。

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20511549/397bf882-b0b4-11e6-88b9-9b596d210ce3.png)

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20511569/56935f8c-b0b4-11e6-916e-a8036080454e.png)

**Comment by AaronChen2012** [comment]
查看table文档，里面增加了这个context 属性

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20512428/4853de0a-b0ba-11e6-8f5c-e7ffce9dc60c.png)
增加了context属性还是不行呢

**Comment by yuanshengchao** [comment]
点击那个dialog不能够弹出弹出框，而且也不报错。请问这是什么问题，但是换成1.0.0版本就正常了，1.0.0和1.0.2都不正常

**Comment by furybean** [comment]
@yuanshengchao 你这么做太重了，相当于每一行里面都会创建一个 Dialog + Table。建议把 Dialog 移动到外面，通过方法显示出来。

**Comment by yuanshengchao** [comment]
尽快是抽取出来，但是dialog还是无法正常显示呀。1.0.1和1.0.2都是有问题的

**Comment by Leopoldthecoder** [comment]
试试把 `dialogVisible = true` 抽成一个方法放在 `methods` 里面，然后在点击 `el-button` 时调用这个方法。

**Comment by yuanshengchao** [comment]
好的，已成功。可以close了
