### ISSUE TITLE
When [Bug Report] updates data in el-tree with Vue.set, new nodes appear instead of updating data.

### ISSUE THREAD

**Issue by hardy-maxtry** [ElemeFE/element#12647]
### Element UI version
2.4.6

### OS/Browsers version
macOS 10.13 / chrome 68

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/fh2j7n5q/4/](https://jsfiddle.net/fh2j7n5q/4/)

### Steps to reproduce
打开节点 “一级 2”，点击"click"按钮
在2.3.9版本没有这个问题

### What is Expected?
点击"click"按钮后，"二级2-1"被更新为"new"

### What is actually happening?
点击"click"按钮后，出现了新的节点"new"，同时 "二级2-1" 节点仍然存在

**Comment by ziyoung** [comment]
Vue.set 使用方式的问题。https://jsfiddle.net/zhiyang/fh2j7n5q/6/
```js
Vue.set(temp.children[0], 'label', 'new')
```

**Comment by hardy-maxtry** [comment]
@ziyoung 
我需要更新的是整个节点啊，并不只是要更新label

**Comment by ziyoung** [comment]
@hardy-maxtry 嗯，我这边的问题。跟 #12421 有点像。
