### ISSUE TITLE
[Bug Report] el-cascader can not be precisely selected, and online testing is also problematic.

### ISSUE THREAD

**Issue by hhch** [ElemeFE/element#12645]
### Element UI version
2.4.6

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/26ungd0L/1/](https://jsfiddle.net/26ungd0L/1/)

### Steps to reproduce
首先设置cascader为 expand-trigger="hover"  :change-on-select="true"，然后随意将某一2级选项的children去掉，就是在官网的测试例子上把任意一个2级选项的子菜单去掉，然后开始测试，点击尝试选择该没有子元素的选项

### What is Expected?
预期是该没有子菜单的选项能选中

### What is actually happening?
结果是该没有子菜单的选项选不中，选到其他的选项了,因为单击选择的时候，面板上移隐藏，因为hover选择，选中其他选项了
![image](https://user-images.githubusercontent.com/21006441/45253007-2dcff280-b392-11e8-8419-30d62d4354e5.png)
点击Form，但是选中的却是其他选项

**Comment by ziyoung** [comment]
Duplicate of #12508

**Comment by ziyoung** [comment]
升级一下版本，这个问题已经修复了。
