### ISSUE TITLE
[Bug Report] select component problem

### ISSUE THREAD

**Issue by Dueot** [ElemeFE/element#12646]
### Element UI version
2.4.6

### OS/Browsers version
macOS 10.13.6 (17G65) / 68.0.3440.106（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
Sorry, I have no link!
![](http://ww1.sinaimg.cn/large/7ed7d3dfly1fuzvwnnrp0g20vl0ah7dh.gif)

### Steps to reproduce
1、两个 select ，option 都是动态获取数据并渲染，类似级联；
2、只有第一个 select 选择了内容，第二个 select 的 option 才会加载，例如： 第一个选择框选了 ‘北京’，第二个选择框才能渲染‘北京的区县’以供选择；
3、当两个 select 都选择了值，并且重新选择第一个 select 的值时，第二个 select 的 label 会消失并且变为 value 的值；

### What is Expected?
当两个 select 都选择了值，并且重新选择第一个 select 的值时，第二个 select 应该被清空

### What is actually happening?
第二个 select 的 label 会消失并且变为 value 的值

**Comment by ziyoung** [comment]
在 https://jsfiddle.net/ 上新建个例子吧。

**Comment by Dueot** [comment]
这是一个粗糙的例子。
https://jsfiddle.net/p49oy1su/

**Comment by ziyoung** [comment]
在获取城市列表之后，你需要手动 `form.city` 的值给重置。如果绑定的还是原来的值，那么在 label 那里将会显示现在的 value。https://jsfiddle.net/zhiyang/w8qrnh0o/

**Comment by Dueot** [comment]
也就是说，默认的设定是：如果没有 label 值，默认会显示 value？
