### ISSUE TITLE
How does [Feature Request] get the list of tables through cell-click? Attention is not the first few lines!

### ISSUE THREAD

**Issue by GetemJay** [ElemeFE/element#12655]
### Existing Component
是

### Component Name
table

### Description
通过cell-click怎么获取点击的是表格的第几列？
注意：：：
问的不是第几行

**Comment by ziyoung** [comment]
cell-click 回调函数中有一个 column 属性，可以通过 `column.id` 来获取到时第几列。
https://jsfiddle.net/zhiyang/z9w2Lxfd/2/
