### ISSUE TITLE
[Bug Report] When using the'fixed'property of'table' component, Popover cannot be created properly.

### ISSUE THREAD

**Issue by Stonewuu** [ElemeFE/element#12651]
### Element UI version
2.4.6

### OS/Browsers version
window 10 / chrome 69.0.3497.81

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/s6ywLofx/](https://jsfiddle.net/s6ywLofx/)

### Steps to reproduce
table component add 'fixed' property

表格组件下的el-table-column增加fixed属性

click the delete button

点击delete按钮

### What is Expected?
Normal creation of popover

正常创建Popover

### What is actually happening?
Unable to create popover

无法创建Popover

**Comment by ziyoung** [comment]
Duplicate of #11704
