### ISSUE TITLE
[Bug Report] How do I get a file object before the submit ()

### ISSUE THREAD

**Issue by z1900** [ElemeFE/element#12650]
### Element UI version
2.4.6

### OS/Browsers version
windows 7  / Chrome 69.0.3497.81

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/1900/ngjv2t3s/](https://jsfiddle.net/1900/ngjv2t3s/)

### Steps to reproduce
在点击 “选取文件“  按钮选完文件之后，怎样立即获取到 file 对象，而不是点击 “上传到服务器” 按钮后触发了 submit() 方法后才获取到

### What is Expected?
在点击 “选取文件“  按钮选完文件之后，立即获取到 file 对象

### What is actually happening?
获取不到

**Comment by ziyoung** [comment]
设置 before-upload 钩子函数，[例子点击这里](http://element-cn.eleme.io/#/zh-CN/component/upload#yong-hu-tou-xiang-shang-chuan)。

**Comment by z1900** [comment]
你看我的重现链接了吗，手动上传选取完图片之后在 before-upload 中无法立即获取到 file 对象，只有点击上传到服务器才能拿到，没 get 到你说的是那个例子 @ziyoung
