### ISSUE TITLE
[Bug Report] Tree Components: The root node cannot unchecked if his grandchildren has a disabled node except the first child and his children.

### ISSUE THREAD

**Issue by jadestrong** [ElemeFE/element#12656]
### Element UI version
2.4.2

### OS/Browsers version
Mac/Chorme68

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/jadestrong/1sv9p8La/7/](https://jsfiddle.net/jadestrong/1sv9p8La/7/)

### Steps to reproduce
1. Disabled the [三级 3-2-1] or [三级 3-3-1] or their sibling node;
2. Then the [一级2] only can checked , but cannot unchecked unless also disabled their parent node, such as [二级2-2].

### What is Expected?
Can uncheck the root node

### What is actually happening?
Cannot unchecked .

**Comment by ziyoung** [comment]
> key 有点小问题我这里稍微改了一下 https://jsfiddle.net/1sv9p8La/8/
> 
> 在这个例子中节点选中的逻辑是这样的：
> 
> 1. 将处于 `半选中` 状态的 `一级 2` 节点设置为 `true`（因为半选中状态是 false，toggle 后是 true）
> 2. 级联操作将子节点设置为 `true`，此时跳过带有 `disable` 属性的节点
> 3. 由子节点重新计算父节点的状态，由于 `三级 3-2-1` 为未选中 disabled 状态，导致 `二级 2-2` 为半选中状态，进而 `一级 2` 节点也为半选中状态，第一步设置的 `true` 状态还原回 `false`

不算是 bug，先关闭了。
ant.design 计算父节点选中状态的时候会忽略掉 disabled 的节点，从而避免出现了该问题。但是这样会看起来很怪。

**Comment by jadestrong** [comment]
Soga，只是这样感觉会影响用户体验，毕竟用户并不关心实现逻辑，如果不能按习惯的认识来就会把它当成bug了。
