### ISSUE TITLE
[Bug Report] table has lock table header, lock table column, and can not scroll when combined.

### ISSUE THREAD

**Issue by denonzhu** [ElemeFE/element#12666]
### Element UI version
2.4.6

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5683/](https://jsfiddle.net/mmx38qxw/5683/)

### Steps to reproduce
见重新连接

### What is Expected?
被锁表列的横向滚动条能点击滚动

### What is actually happening?
出现横向滚动条的时候，被锁表列的滚动条部分被遮挡了，无法滚动

**Comment by denonzhu** [comment]
例子中的日期列被锁表列,下发滚动条的地方无法点击滚动

**Comment by denonzhu** [comment]
![image](https://user-images.githubusercontent.com/5187679/45207885-d3fcf900-b2bb-11e8-82fe-44ae0d6134a5.png)
该区域无法点击滚动

**Comment by denonzhu** [comment]
分析原因还是由于锁的表列把表格内容区域遮挡,导致滚动条无法点击,希望官方能快点修复

**Comment by ziyoung** [comment]
Duplicate of #7564

**Comment by andyaccount** [comment]
今天来发现这个问题只是被合并到另一个很久之前的问题上了，请问针对目前2.4.6版本的element-ui，这个bug有暂时的解决方案吗？

**Comment by andyaccount** [comment]
一直关注这个bug，今天来看，发现这个bug被简单合并到了另一个很久之前的问题上。最新的2.4.7版本也没有解决这个bug，请问现在有什么暂时性的解决方案吗？

**Comment by denonzhu** [comment]
我这个问题跟 ＃7564 还不太一样，这是个滚动条被浮动列给挡住了 浮动列的位置 没法点击滚动条

**Comment by denonzhu** [comment]
> 一直关注这个bug，今天来看，发现这个bug被简单合并到了另一个很久之前的问题上。最新的2.4.7版本也没有解决这个bug，请问现在有什么暂时性的解决方案吗？

这个问题目前没法解决，是table组件布局问题，看过ivews的table相关布局 就不会出现这个问题

**Comment by andyaccount** [comment]
找到一个简单的解决办法，给图中这个元素添加z-index：3；这个属性，就是把带有滚动条的容器的z-index值与固定列的z-index值统一。
![image](https://user-images.githubusercontent.com/30610634/45614033-b6d5e080-ba9a-11e8-85b2-6e8e5e2df064.png)

**Comment by ziyoung** [comment]
@denonzhu 我打开你这个链接：https://jsfiddle.net/mmx38qxw/5683/ ，发现跟 #7564 很像。你再补充个链接吧，我把 issue 重新打开。

**Comment by ziyoung** [comment]
补充个链接：https://jsfiddle.net/xtqbpmLe/

**Comment by denonzhu** [comment]
https://jsfiddle.net/mmx38qxw/5683/
![image](https://user-images.githubusercontent.com/5187679/46455666-a897fc00-c7de-11e8-84bd-7afce63dcae0.png)
图上标记的位置 是没法点击的滚动条的

**Comment by denonzhu** [comment]
> https://jsfiddle.net/mmx38qxw/5683/
> ![image](https://user-images.githubusercontent.com/5187679/46455666-a897fc00-c7de-11e8-84bd-7afce63dcae0.png)
> 图上标记的位置 是没法点击的滚动条的

由于锁了表列 并且有合计,导致在table出现横向滚得的时候，被锁的表列的滚动条部分没发点击

**Comment by denonzhu** [comment]
> 找到一个简单的解决办法，给图中这个元素添加z-index：3；这个属性，就是把带有滚动条的容器的z-index值与固定列的z-index值统一。
> ![image](https://user-images.githubusercontent.com/30610634/45614033-b6d5e080-ba9a-11e8-85b2-6e8e5e2df064.png)

这个方案试过了，是可以的只需要在全局样式表里面加入
```
.is-scrolling-left{
  z-index: 3;
}

```
这个是对锁左列起作用，右列的应该是 .is-scrolling-right

**Comment by MrLiuTY** [comment]
看了楼上，只有全局加入这个，希望官方尽快修复 。我是2.4.8版本
.is-scrolling-left, .is-scrolling-right { /*fixBug 当el-table左边，右边存在固定列时被遮住部分滚动条不能拖动*/
    z-index: 3;
}

**Comment by ziyoung** [comment]
layui 的 table 「合计」那一行没有固定。就完全不用担心这个问题了。😂https://www.layui.com/demo/
![image](https://user-images.githubusercontent.com/12947422/56487984-8e6e0300-650f-11e9-82f4-2af5857f4b7c.png)

**Comment by Eflet** [comment]
试试这个，我觉得比调整zinde好用，全局css加上这个：
```
.el-table {
  .el-table__fixed {
    pointer-events: none;
    > * {
      pointer-events: auto;
    }
  }
}
```
用css禁用掉鼠标事件，然后下一层再全部放开鼠标事件

**Comment by ziyoung** [comment]
另一种解决方案：#15471
