### ISSUE TITLE
[Bug Report] elementUI 2.4.6 version can not delete tree nodes.

### ISSUE THREAD

**Issue by DAHU123** [ElemeFE/element#12664]
### Element UI version
2.4.6

### OS/Browsers version
window7旗舰版

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
就在官网提供的ＡＰＩ上，点击删除，不能正常的删除节点
这个就是重现的链接: 
http://element-cn.eleme.io/2.4/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong
上面个重现链接是不正确的，这个重新啊链接才是争取的

### What is Expected?
点击删除，可以正常的删除树形节点

### What is actually happening?
点击删除，不可以正常的删除树形节点

**Comment by mario56** [comment]
try to change `const children = parent.data.children || parent.data;` to `const children = parent.childNodes;` in remove function

**Comment by DAHU123** [comment]
现在问题已经解决了,,,就是按照上面那位大神说的,,,多谢!!!

**Comment by cuicuicuinice** [comment]
没看懂啥意思呢......

**Comment by DAHU123** [comment]
仔细注意一下vue和elementUI的版本,,,elementUI2.4.6这个版本中,官网API提供的删除树形节点的remove方法不起作用,,,,就是这个意思....

**Comment by cuicuicuinice** [comment]
哇！！这么快就回了  好感动！！！
我没用官方提供remove
我是直接操作tree的数据源，
操作数据源做添加操作的时，tree视图会正常刷新显示，
但是在数据源做删除操作时，tree视图没有刷新，没有一点反应

**Comment by DAHU123** [comment]
现在elementUI2.4.6官网的API提供的删除树形节点的方法：确实不能通过那样子的方法进行删除，用1楼的那个大神提供的方法就能够删除了,,,,我现在树形节点的删除问题已经解决了．．．．

**Comment by cuicuicuinice** [comment]
哇  又是这么快回复  巨感动~~~~~！第一次用github有人回复！！
但是他这个代码没怎么看懂......
可以加个微信或者QQ交流蛮？

**Comment by cuicuicuinice** [comment]
我用的就是这个方法，在splice做删除的时候视图不更新，做添加时候视图就更新，很奇怪

**Comment by DAHU123** [comment]
注意一下vue的版本,和elementUI的版本  
Element UI version2.4.6
Vue version2.5.16
要满足这两个版本,上面我说的那个方法才有效果的

**Comment by cuicuicuinice** [comment]
深感无奈。。。溺了两天了这问题，
还是不行，版本换了后。。。
用谷歌插件vuetool查看了tree的computed，
![image](https://user-images.githubusercontent.com/34976688/45290973-723ec800-b523-11e8-85b1-0188f6e964ab.png)
做数据源增加时候，children和treeItemArray都在更改，
做数据源删除的时候，只有children在变，treeItemArray没变，
现在我这个截图，就是添加后再删除的操作，按理说children和treeItemArray数量应该一样的，
结果现在children只有6个，
treeItemArray是18个

**Comment by ziyoung** [comment]
2.4.6 版本才会有该问题。
在修复 tree 的 issue 的时候，优化一些代码时候出的锅。本周会发一个新版本，请继续关注 ElementUI。
安装 ElementUI 时候，可以指定版本号来避免该问题。
```
npm i element-ui@2.4.5
```

**Comment by cuicuicuinice** [comment]
官方大佬，到底有没有比较实在的解决方案诶？起初本来就是2.4.5，然后换成2.4.6，现在又换回2.4.5，还是一样得.....

**Comment by DAHU123** [comment]
我现在用的就是2.4.6用最上面的那个大佬的方法已经把问题解决了...不用来回切换的....没有那么麻烦的....
