### ISSUE TITLE
Can the node-click event of [Feature Request] tree component return the event parameter?

### ISSUE THREAD

**Issue by bigStuart** [ElemeFE/element#12669]
### Existing Component
是

### Component Name
tree

### Description
node-click事件中没有event参数回，有时进行组件组合使用时点击事件冲突无法进行阻止冒泡

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/blob/0e617d0fc6abd792b3dfcf9e6504931bb2f145ea/packages/tree/src/tree-node.vue#L2-L6
我们已经阻止 click 事件向上冒泡，检查一下，看看是不是使用上的问题。
