### ISSUE TITLE
[Bug Report] How to make a table with full selection disable only the full selection / check boxes for the header, and the selection boxes for other rows are still available.

### ISSUE THREAD

**Issue by lixing0323** [ElemeFE/element#12663]
### Element UI version
2.4.6

### OS/Browsers version
mac

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5665/](https://jsfiddle.net/mmx38qxw/5665/)

### Steps to reproduce
如何让一个有全选功能的表格，只禁用表头的全选/反选框，其他行的选择框仍可以使用。

### What is Expected?
设置参数。

### What is actually happening?
设置参数。

**Comment by ChaoFTic** [comment]
如果只是想要去掉表头的全选的`checkbox`的话，可以利用`el-table-column`的嵌套渲染
```
<el-table-column width="150px" label="slot-checkbox">
    <template slot-scope="scope">
        <el-checkbox :checked="true"></el-checkbox>
    </template>
</el-table-column>
```
[官网例子](http://element-cn.eleme.io/#/zh-CN/component/table#zi-ding-yi-lie-mo-ban)

**Comment by lixing0323** [comment]
@ChaoFTic ，自定义渲染的话，就不能使用官方的 selection-change方法了，也不能获取正常获取数据了。

**Comment by ChaoFTic** [comment]
@lixing0323 不一定要用官方的办法，获取数据可以在`checkbox`上用v-model来绑定单个`checkbook`的值，同时在template 标签内也可以用`scope.row`或`scope.column`来获取整行或者整列的数据

**Comment by ziyoung** [comment]
我觉得 @ChaoFTic 的方案可行。
对于这种场景，还是用户自己通过 TableColumn 来实现吧。我们目前不打算提供该功能。
