### ISSUE TITLE
[Bug Report] Cannot prevent event bubbling to table header

### ISSUE THREAD

**Issue by kife-design** [ElemeFE/element#12665]
### Element UI version
2.4.6

### OS/Browsers version
Mac os High Sierra

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5680/](https://jsfiddle.net/mmx38qxw/5680/)

### Steps to reproduce
- Click in the header textbox. 
- See the sorting change

### What is Expected?
I added a e.stopPropagation() in the textfield input event to stop the table from sorting.

### What is actually happening?
The table is sorting

**Comment by shivamkumar110** [comment]
Facing the same issue. Tried a lot couldn't fix that.

**Comment by ohhoney1** [comment]
hey, guies! @kife-design @shivamkumar110 it works. [https://jsfiddle.net/mmx38qxw/6236/](https://jsfiddle.net/mmx38qxw/6236/)
