### ISSUE TITLE
[Bug Report] [el-pagination] :page-size.sync ="pageSize",  access the this.pageSize in the size-change event, this.pageSize not right

### ISSUE THREAD

**Issue by qinshenxue** [ElemeFE/element#12679]
### Element UI version
2.4.6

### OS/Browsers version
win7  chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5721/](https://jsfiddle.net/mmx38qxw/5721/)

### Steps to reproduce
1、:page-size.sync ="pageSize" , @size-change="handleSizeChange"
2、click to change page-size value
3、access the this.pageSize in handleSizeChange method

### What is Expected?
after change page-size,  this.pageSize should change immediately

### What is actually happening?
after change page-size,  this.pageSize not change

**Comment by ziyoung** [comment]
Try to use `nextTick`. https://jsfiddle.net/zhiyang/mmx38qxw/5807/
