### ISSUE TITLE
[Bug Report] select component selects multiple text cover buttons.

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#12682]
### Element UI version
2.4.6

### OS/Browsers version
windows10,chrome69

### Vue version
2.5.2

### Reproduction Link
[https://codesandbox.io/s/jnlxl5q4pw](https://codesandbox.io/s/jnlxl5q4pw)

### Steps to reproduce
选择  "黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕" 或者 “双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶” 选项后，右边的搜索按钮被遮住了。

### What is Expected?
选择过过长的选项，选项展示的宽度不超过外层的input框的宽度，超出部分以省略号形式展示。

### What is actually happening?
选择  "黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕黄金糕" 或者 “双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶双皮奶” 选项后，右边的搜索按钮被遮住了。

![image](https://user-images.githubusercontent.com/8147202/45274943-6b489300-b4ec-11e8-922a-1c507f13ff65.png)

**Comment by ziyoung** [comment]
Duplicate of #9352
