### ISSUE TITLE
tree控件删除数据源控件不刷新

### ISSUE THREAD

**Issue by cuicuicuinice** [ElemeFE/element#12689]
很奇怪的问题，最新版tree控件做修改操作，直接操作数据源，做增加操作控件会刷新，但是做删除操作没有一点反应，
用了vuetool工具查看了computed，随着对数据源的增加操作，children和treeItemArray都有变化，
但是做数据源删除操作的时候，只有children变化，而treeItemArray没有变化.
这是bug还是操作不当造成的呢？
有前辈解决这类问题了嘛？

**Comment by lanpangzhi** [comment]
升级2.47
