### ISSUE TITLE
动态tabs无法正确显示

### ISSUE THREAD

**Issue by wanghaolu** [ElemeFE/element#1268]
### ElementUI version

1.0.2

### OS/Browers version

chrome 54

### Vue version

2.0.8

### Reproduction Link

http://jsfiddle.net/ur9rsukg/

### Steps to reproduce
1. 点击 Add
2.点击tab1-tab4中的任何一个

### What is Expected?
点击Add后新的tab-pane应该出现在tabs中

### What is actually happening?
而是点击已有tab-pane后才显示，并不是像预期那样点击add后就出现在tabs中

**Comment by lodamemory** [comment]
bug+1，添加第一个时会出现在tabs中，但第二个不会出现，添加第三个会生成第二个，然后切换时会完整显示第三个

**Comment by newlife** [comment]
把` <el-tab-pane v-for="tab in tabs" :label="tab.label" :name="tab.name">用户管理</el-tab-pane>`中的name部分去掉可以避免这个问题，然而name就不能用了

**Comment by furybean** [comment]
@wanghaolu  @lodamemory  可以临时这么解决：http://jsfiddle.net/ur9rsukg/1/

**Comment by lodamemory** [comment]
@furybean jsfiddle暂时打不开，有简单一点的描述么？

**Comment by wanghaolu** [comment]
@lodamemory 可以访问啊， @furybean 的解决方案是
` 	add () {
      	this.tabs.push({
        	label: 'added',
          name: 'added' + count++
        });
        this.$nextTick(() => {
          this.$refs.tabs.$forceUpdate();
        });
      }`

手动通知tabs更新

**Comment by lodamemory** [comment]
@wanghaolu 感谢，网络问题有时打得开有时打不开
