### ISSUE TITLE
[Bug Report] Menu components switch to a non active menu menu or in the original activation state.

### ISSUE THREAD

**Issue by Venbor** [ElemeFE/element#12680]
### Element UI version
2.4.6

### OS/Browsers version
macOS 10.13.6

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Menu components switch to a non active menu menu or in the original activation state.

### What is Expected?
Can you consider clearing the original activation state when switching from an existing activation menu (Attribute:default-active) to an nonexistent activation menu in menu components(NavMenu)?

### What is actually happening?
The activation menu does nothing when you switch from an existing activation menu to an nonexistent activation menu

**Comment by zhenghaiyang** [comment]
I have the same problem   :(  

I ended up using " window.location.href “  to solve this problem

**Comment by ziyoung** [comment]
@Venbor please provide a right link.
