### ISSUE TITLE
[Feature Request] Table component Selected Value

### ISSUE THREAD

**Issue by ColinLights** [ElemeFE/element#12697]
### Existing Component
Yes

### Component Name
Table

### Description
Hi is there a possibility to return the value of the main checkbox when using Element UI table with selected column

**Comment by ziyoung** [comment]
https://jsfiddle.net/zhiyang/9twqeLh1/
```
<el-table @selection-change="handleSelectionChange">
```

**Comment by ColinLight3** [comment]
Hi that method only returns the rows my question was how do you get the checkbox value ... true false.
Because you cant , am i missing something ?

**Comment by ziyoung** [comment]
@ColinLights3 sorry, I forgot to save demo.
```js
handleSelectionChange(val) {
  this.multipleSelection = val;
  this.$nextTick(() => {
    console.log(this.$refs.multipleTable.store.states.isAllSelected)
  })
}
```
