### ISSUE TITLE
[Feature Request] Is it possible to use other validation libraries with Element UI ?

### ISSUE THREAD

**Issue by davestewart** [ElemeFE/element#12692]
### Existing Component
Yes

### Component Name
Form / FormItem

### Description
We'd like to use other validation libraries with Element UI, rather than use the rather cumbersome AsyncValidator.

Is this possible, short of forking the library?

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by davestewart** [comment]
Is there any way to validate other than Async Validator?

**Comment by ziyoung** [comment]
Maybe you use other libraries to validate the form data and pass `error` to FormItem.

**Comment by davestewart** [comment]
OK, thanks, we'll take a look at this approach.

Would you be interested in a PR if we decide to look at the core code?
