### ISSUE TITLE
When [Bug Report] re rendered el-menu in JSX, active item was not updated.

### ISSUE THREAD

**Issue by jason-chang** [ElemeFE/element#12694]
### Element UI version
2.4.6

### OS/Browsers version
mac os 10.13/ Vivaldi/1.96.1147.64

### Vue version
2.5.17

### Reproduction Link
[https://github.com/jason-chang/icoding-dashboard](https://github.com/jason-chang/icoding-dashboard)

### Steps to reproduce
1. 克隆项目
 git clone https://github.com/jason-chang/icoding-dashboard.git
2. 检出 forPr 分支
 git fetch
 git fetch forPr:forPr
 git checkout forPr 
3. 安装
 npm i
4. Dev
 npm run dev
5. 观察 侧栏状态了解 bug 情况
 打开 http://localhost:9200
 点击顶部菜单栏与侧栏和tab，观察 侧栏菜单 active item 状态。

### What is Expected?
点击 tab页、顶部菜单和侧栏的时候,根据权限所在的 menu 子树重新组装侧栏，然后默认选中特定侧栏项目。

### What is actually happening?
  我的 default-active 附加正确，然而相应 el-menu-item 没有附加 active 状态。
  实际原因我 debug 下来，发现是使用 jsx 组装和重新渲染 el-menu 的时候。因为 vue 复用了组件实例，所以 el-menu-item 的 “mounted” 勾子不一定每次都会调用，然而 “updated” 可以，el-menu 中 附加到 items 的条目 index 和 item.index 不一致。我提交了一个 pr (#12678)[https://github.com/ElemeFE/element/pull/12678] ，然而没通过 unit test. 我不懂 karma 不知到如何修复。官人可以参考我的代码了解 bug 原因。

**Comment by ziyoung** [comment]
@jason-chang 把例子精简一下，在 https://jsfiddle.net/ 上创建一个可以重现问题的链接。

**Comment by ziyoung** [comment]
@jason-chang 提供个例子吧，你那个仓库东西太多。

**Comment by jason-chang** [comment]
@ziyoung 我想象办法吧，主要逻辑有点复杂。

**Comment by Nullaha** [comment]
其实就是v-for的时候el-menu-item没有加key  -->  导致旧的menuItem组件被复用了 --> 无法触发旧menuItem组件的mounted钩子 -->也就没法通过addItem方法添加到menu组件的items属性中。。。。。items和子组件对不上，就会导致点击发生错乱。。。
