### ISSUE TITLE
[Bug Report] When use disabled Date in DateTimePicker and current time is disabled, the confirm button still set current time as the result.

### ISSUE THREAD

**Issue by verymuch** [ElemeFE/element#12701]
### Element UI version
2.4.6

### OS/Browsers version
mac OS / Chrome 68.0.3440.106 / Firefox / Safari

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5773/](https://jsfiddle.net/mmx38qxw/5773/)

### Steps to reproduce
打开日期选择器，直接点击确定按钮，可以选中当前时间，但是当前时间已禁用

### What is Expected?
不要把确认按钮和当前时间的功能绑在一起

### What is actually happening?
确认按钮默认为当前时间，但当前时间被禁用后，仍能点击确认选中当前时间

**Comment by zhangyufen** [comment]
I have encountered the same problem，hope the question to be fixed as soon as possible

**Comment by yuanyuanshen** [comment]
？？？？？同样的问题，？无法解决？为什么不能像time-picker一样设置 option选项，设计的时候不是应该这样设计么
