### ISSUE TITLE
Z-Index self increment of multiple components of [Bug Report] element-ui

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#12707]
### Element UI version
2.4.6

### OS/Browsers version
win10 /chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/573814zL/55/](https://jsfiddle.net/573814zL/55/)

### Steps to reproduce
实现一个容器，若z-index只比minxin了Popup（比如：Dialog、Datepicker、Dorpdown、Popover、MessageBox等）的组件稍微大一点，组件第一次可被容器覆盖，直到Popup的z-index 自增至大于实现的容器导致无法覆盖，出现场景，自定义dialog、自定义悬浮块。

### What is Expected?
自定义的悬浮块能覆盖Dialog、Dorpdown、Popover等组件

### What is actually happening?
当z-index 小于minxin了Popup的组件的时候，可覆盖在上，但因为Popup相关组件每切换visible一次会自增z-index，当Popup相关组件的z-index大于自定义的组件时，自定义组件会被覆盖

**Comment by ziyoung** [comment]
@2yllll 目前确实是这样的。增加 `z-index` 的那段代码很早之间就添加了。😂我猜 `z-index` 不断增加的目的是为了要确保弹出层显示在最前面吧。不过 Element 用户用户配置初始的 `z-index` 值，我想这样做应该可以规避这些问题。

**Comment by 2yllll** [comment]
@ziyoung 不行啊，我试过，自定义的上用element的`Datepicker`，`z-index` 太高 `Datepicker` 会被覆盖，`z-index`太低 我的组件会被 `Dorpdown、 Dialog、MessageBox` 覆盖，这`z-index` 自增也太恶心了吧，能开放一个attr来设置是否自增么？还有`Modal`也会有这问题

**Comment by ziyoung** [comment]
@2yllll 考虑到稍微复杂一点的情形：一个 Dialog 内部嵌套另一个 Dialog。如果 z-index 不增加的话，怎么能保证第二个 Dialog 以及遮罩层在第一个 Dialog 上面？

在这种场景下，是不是考虑把一部分内容放在 Dialog 等组件里面呢？

**Comment by Richard-Choooou** [comment]
对于这种情况应该提供一个获取当前zIndex的接口供用户调用，调用后，zIndex自增，之后的组件也不用担心覆盖或者被覆盖
