### ISSUE TITLE
Upload 上传，multiple多选时能否设置上传顺序为文件选择的顺序？

### ISSUE THREAD

**Issue by CharkeyQK** [ElemeFE/element#1270]
### ElementUI version
1.0.1

### OS/Browers version
Chrome 54

### Vue version
2.0.3

### What is Expected?
Upload 上传，multiple多选时能否设置上传顺序为文件选择的顺序？
在点击upload之后，弹出文件选择框，我选择了三张图片A、B、C，希望这三张图片的上传顺序也是A、B、C；

**Comment by baiyaaaaa** [comment]
无法支持
