### ISSUE TITLE
[Bug Report] Options dettached from select component when scrolled

### ISSUE THREAD

**Issue by vincebanzon** [ElemeFE/element#12704]
### Element UI version
2.4.6

### OS/Browsers version
Windows 10, Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5797/](https://jsfiddle.net/mmx38qxw/5797/)

### Steps to reproduce
I'm not quite sure how this is not working in my application. On other page, it is working as expected but for some page also, it isn't
I am using vuetify and element to the same project.
I have tried cleaning to the point these are the only codes left (in this page) but is still having issue.

### What is Expected?
The options remains attached to the select component even when scrolled far away.
In other pages, the Options component adjusts it's TOP in css when scrolled, but not in this page's case.

### What is actually happening?
What's happening actually is the options detaches from the select component when it is scrolled far away. By the time the select component is not visible from the page anymore, the options, still remain in it's place blocking the view of other components.

**Comment by ziyoung** [comment]
@vincebanzon Sorry, I don't know what's going wrong.
![kapture 2018-09-25 at 18 30 49](https://user-images.githubusercontent.com/12947422/46009170-46117280-c0f1-11e8-909d-d552c2820c9c.gif)
