### ISSUE TITLE
[Bug Report] this lint will trigger select validation

### ISSUE THREAD

**Issue by xiaoshude** [ElemeFE/element#12706]
### Element UI version
2.4.6

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.com](http://jsfiddle.com)

### Steps to reproduce
w

### What is Expected?
del this line
https://github.com/ElemeFE/element/blob/4017fe4bd948ecf966afd256328c4e8911d97812/packages/select/src/select.vue#L849

### What is actually happening?
dirty when first into

**Comment by ziyoung** [comment]
这段代码是纠正一下传入的 value。多选时，value 必须是数组才对呀。

**Comment by xiaoshude** [comment]
@ziyoung 但是这段代码会触发 校验， 比如设置了 required，那么进来就会显示未填的错误信息

**Comment by xiaoshude** [comment]
@ziyoung 为啥进来就要纠正呢，只需要在选择时 传出正确的值即可
