### ISSUE TITLE
Upload build exception on [Bug Report] Safari

### ISSUE THREAD

**Issue by cherishloveyou** [ElemeFE/element#12710]
### Element UI version
2.4.6

### OS/Browsers version
Safari

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/much13/43njkqoc/1/](https://jsfiddle.net/much13/43njkqoc/1/)

### Steps to reproduce
Safari浏览器上官方的Demo 图片列表缩略图 上预览就异常
然后打开带缩略图跑在jsfiddle上就能复现出来

### What is Expected?
Safari上传图片正常

### What is actually happening?
Safari上传图片异常

**Comment by ziyoung** [comment]
我这边无法重现。Safari 版本是 11.1.2 (13605.3.8)。

**Comment by atmjs** [comment]
beforeUpload里面返回 Promise的时候可重现
