### ISSUE TITLE
element-ui@1.0.2中,<el-upload> <el-steps> 以及 <el-table>中的多选框，这几个组件的样式，在引入bootstrap样式文件后,会不正常。

### ISSUE THREAD

**Issue by ganjingcun** [ElemeFE/element#1271]
element-ui@1.0.2中,<el-upload> <el-steps> 以及 <el-table>中的多选框，这几个组件的样式，在引入bootstrap样式文件后,会不正常。

![snip20161122_41](https://cloud.githubusercontent.com/assets/9986377/20515529/19ffccb8-b0cd-11e6-817e-316e177ad850.png)

![snip20161122_42](https://cloud.githubusercontent.com/assets/9986377/20515580/4f83387a-b0cd-11e6-8387-1b2969215ae7.png)

**Comment by cycold** [comment]
```
// 对于多选框
// element-ui中使用的before after盒子模型为content-box 而bootstrap中使用的为border-box
*::before, *::after { box-sizing: content-box; }
```
