### ISSUE TITLE
[Bug Report] About the echo of el-select under multiple, remote, and value-key conditions! Urgent!

### ISSUE THREAD

**Issue by yang123guo** [ElemeFE/element#12713]
### Element UI version
2.4.6

### OS/Browsers version
无关操作系统和浏览器版本

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/1erjhcL3/773/](https://jsfiddle.net/1erjhcL3/773/)

### Steps to reproduce
回显内容 看不见，
只有再次change以后才会出现
![www](https://user-images.githubusercontent.com/17383237/45364303-5ebb5c00-b60c-11e8-9828-3f930723bbf0.png)

### What is Expected?
回显能不触发远程调用，把内容显示出来

### What is actually happening?
回显内容 看不见，只有再次change以后才会出现

**Comment by yang123guo** [comment]
@nanomen   Thanks for your suggestion, I"ll try it!

**Comment by nanomen** [comment]
@yang123guo you're welcome! If you want, look the fixed fork in my repo https://github.com/nanomen/element

And you can write own select element, just use root select element as extend in your own select element.

```js
// own select

import { Select } from 'element-ui'

export default {
  name: 'OwnSelect',
  extend: Select,
  props: {
    labelKey: {
       type: String,
       default: 'label'
    }
  },
  methods: {
    getOptions (value) {
      ...
      const label = (isObject && !isNull) 
        ? value[this.labelKey] ? value[this.labelKey] : ''
        : (!isObject && !isNull) ? value : '';
      ...
    }
  }
}
```

and use in your code.

**Comment by yang123guo** [comment]
got it! @nanomen

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/12735#issuecomment-422088645
