### ISSUE TITLE
[Feature Request] - Allow a new prop for el-select to  reference which element to append to in the DOM when popperAppendToBody is false

### ISSUE THREAD

**Issue by kgrosvenor** [ElemeFE/element#12716]
### Existing Component
Yes

### Component Name
el-select

### Description
Hello Element UI Team!

To get to the point I'm developing a javascript application which has a window system and they are draggable. 

The issue I am having is the select box is not following the window when being moved, but i think i can have a solution to this with one extra prop, or i'm open to other ideas which allow the opened select box to stick to a parent element when it's being moved around on screen.

Please see the following to view evidence of the behaviour I'm explaining
https://i.gyazo.com/067fd601da2c6b827916a6550ddbf49c.mp4

I was thinking of just an *element* that is passed as a prop to tell el-select to *append to the desired element of choice*, in my use case it needs to be one div down so it's in the lower half of the window, I.E the body, not the header, so then then it wont underlap the window body<div>.

Lastly, I would like to say thank you for making such a great UI framework, it's got some absolutely wonderful features and I hope this issue makes a good contribution/idea

**Comment by ziyoung** [comment]
@kgrosvenor Element uses popper.js to calculate the position of popper element. When the pages scrolls or window resizes, popper.js will re-calculate the position. But if you drag the reference element, popper.js won't re-calculate the position. A workaround may be like this:
```
<div @drag="handleDrag">
<el-select ref="select"></el-select>
</div>
<script>
...
handleDrag() {
 this.$refs.select.broadcast('ElSelectDropdown', 'destroyPopper');
}
...
</script>
```

**Comment by kgrosvenor** [comment]
This is great thank you !!

**Comment by kgrosvenor** [comment]
Closing issue

**Comment by kgrosvenor** [comment]
> @kgrosvenor Element uses popper.js to calculate the position of popper element. When the pages scrolls or window resizes, popper.js will re-calculate the position. But if you drag the reference element, popper.js won't re-calculate the position. A workaround may be like this:
> 
> ```
> <div @drag="handleDrag">
> <el-select ref="select"></el-select>
> </div>
> <script>
> ...
> handleDrag() {
>  this.$refs.select.broadcast('ElSelectDropdown', 'updatePopper');
> }
> ...
> </script>
> ```

Does this work with ElDropdown too? Can't seem to get it to work for that? Re opening the issue
