### ISSUE TITLE
[Bug Report] dialog modal remove error

### ISSUE THREAD

**Issue by 381510688** [ElemeFE/element#12729]
### Element UI version
2.4.0

### OS/Browsers version
Mac-OS/Chrome

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/src/utils/popup/popup-manager.js](https://github.com/ElemeFE/element/blob/dev/src/utils/popup/popup-manager.js)

### Steps to reproduce
https://github.com/ElemeFE/element/blob/dev/src/utils/popup/popup-manager.js
单页面系统，从A页面到B页面，A页面打开弹窗跳转到B页面，B页面同时打开一个弹窗，B关闭弹窗时依然有遮罩<添加了modal-append-to-body=“false”>
```javascript
// 多个时，不移除modal，导致页面跳转时出现问题
if (modalStack.length === 0) {
      if (this.modalFade) {
        addClass(modalDom, 'v-modal-leave');
      }
      setTimeout(() => {
        // 是否应该判断是否为当前DOM下挂载的modal
        if (modalStack.length === 0) {
          if (modalDom.parentNode) modalDom.parentNode.removeChild(modalDom);
          modalDom.style.display = 'none';
          PopupManager.modalDom = undefined;
        }
        removeClass(modalDom, 'v-modal-leave');
      }, 200);
    }
}
```

### What is Expected?
希望能准确去除掉自己dom的遮罩 

### What is actually happening?
多个modalStack时，并不去除遮罩

**Comment by ziyoung** [comment]
@381510688 提供个例子吧。

**Comment by 381510688** [comment]
@ziyoung 涉及到页面跳转，在jsfiddle中，不太好举例！
但是，从源码里就能看出有问题啊！当多个modal时，并不会移除~~
个人认为：应该判断隶属于那个DOM，然后做处理

**Comment by luy19** [comment]
@ziyoung here is the example: https://codesandbox.io/s/m4kxl7rwvp

follow the steps below:
1. open home dialog
2. open other page
3. open other dialog
4. close other dialog

then you can see the unexpected mask.
thanks.
