### ISSUE TITLE
[Bug Report] number validate  bug  

### ISSUE THREAD

**Issue by RabbDream** [ElemeFE/element#12728]
### Element UI version
2.4.6

### OS/Browsers version
win10/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
When we enter a number first and then enter a Chinese character or an English letter, it doesn't report an error but runs through it. But in my opinion, age can't type out characters other than numbers,

### What is Expected?
I hope you'll be more careful when you write a demo and solve it

### What is actually happening?
i don’t know

**Comment by ziyoung** [comment]
@RabbDream 请提供一个正确的链接。
