### ISSUE TITLE
[Bug Report] tabindex=“-1” 未准确加在控件上

### ISSUE THREAD

**Issue by shuangwhywhy** [ElemeFE/element#12721]
### Element UI version
2.4.6

### OS/Browsers version
macos 10.13.6, Chrome v69

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5812/](https://jsfiddle.net/mmx38qxw/5812/)

### Steps to reproduce
给所有组件加上 tabindex="-1"
生成项目
查看页面元素
发现很多组件都没有按期望的处理方式处理 tabindex

### What is Expected?
把 tabindex=“-1” 加在控件上，或者对应的元素上，达到禁用tab键遍历的目的

### What is actually happening?
tabindex 在稍微复杂点的组件中，都加在了外围div上或不相关的地方，无法控制 tab 遍历。

**Comment by ziyoung** [comment]
目前的话，表单组件类似 select，checkbox 都支持 tab 键访问。支持 tab 访问，是给使用者带来了方便。至于要让所有的组件都支持设置 tabindex，我认为这个可以再讨论一下。

**Comment by shuangwhywhy** [comment]
> 目前的话，表单组件类似 select，checkbox 都支持 tab 键访问。支持 tab 访问，是给使用者带来了方便。至于要让所有的组件都支持设置 tabindex，我认为这个可以再讨论一下。

select 的确支持 tab 遍历，但是我想要的效果是禁用 tab 键遍历，要怎么做呢？如我 jsfiddle 的例子，加上了 tabindex=“-1”，但是从 input 开始按 tab 键还是能遍历到 select 上（其实是 select 里面的 input 上）。我目前找到的方法是页面加载后去 querySelectAll 所有的 input 元素，用 setAttribute 再去设置一遍 tabindex。

**Comment by wacky6** [comment]
@ziyoung Select 现在是不支持 tabindex 的，代码里面没处理。 正确做法是把 tabindex 加到 input 元素上面。

date-picker也可以考虑加上
