### ISSUE TITLE
[Bug Report] resetFields function and v-if

### ISSUE THREAD

**Issue by vovek** [ElemeFE/element#12738]
### Element UI version
2.4.6

### OS/Browsers version
Ubuntu 18.04/Chrome 69.0.3497.81

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/r6yk3o0p/55/](https://jsfiddle.net/r6yk3o0p/55/)

### Steps to reproduce
1. Fill name input with 'name'. Validation works as expected
2. Switch to "Legal entity" and try to fill any input
3. Switch back to "Physical person" and try to fill any input
_resetFields() executed while radiogroup @change event_

### What is Expected?
All inputs of the form are cleared and validation works correctly from first symbol input

### What is actually happening?
1. After switching to "Legal entity" validation of inputs starts only from second symbol
2. After switching back to "Physical person" validation of inputs starts only from second symbol
3. Inputs with v-if are not cleared with resetFields() method.

**Comment by ziyoung** [comment]
https://jsfiddle.net/zhiyang/r6yk3o0p/63/

**Comment by vovek** [comment]
> ```js
> this.$nextTick(() => {
>   this.$refs.registrationForm.resetFields()
> })
> ```
> 
> https://jsfiddle.net/zhiyang/r6yk3o0p/63/

@ziyoung thx for reply!
I see that nothing changed. I have updated the fiddle to be more simple https://jsfiddle.net/d5xm0t8a/9/
I have two problems:

1. Input data with v-if won't reset with resetFields()
You can test it by input Name field, switch on 'Legal' radio and then switch back to 'Physical'. Name input won't be cleared

2. Validation on change event start only from second symbol. You cat reproduce it multiple ways
- click 'reset' button on empty form and try to fill any input(also reproduces in official example)
- firstly switch radio value and try to fill any input
- fill any value, switch radio button and try to fill any input

**Comment by ziyoung** [comment]
@vovek Sorry for my fault. My solution does'nt work. 
I think it's not a bug of ElementUI.
https://github.com/ElemeFE/element/blob/098ba463c3ced8d76165b8f87f909b97e2cce9dc/packages/form/src/form-item.vue#L266-L276
If you use `v-if` with FormItem, FormItem may be rerendered. So the `initialValue` of FormItem may change. You can use two Forms and don't use `v-if` with Form or FormItem.
