### ISSUE TITLE
[Bug Report] in form-item, color-picker causes height and other inconsistencies.

### ISSUE THREAD

**Issue by ZSkycat** [ElemeFE/element#12730]
### Element UI version
2.4.6

### OS/Browsers version
win10，chrome 69.0.3497.81，firefox 62.0

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/m1rh8ug2/](https://jsfiddle.net/m1rh8ug2/)

### Steps to reproduce
第三行 “颜色” 的高度，和其他行不一致。

通过开发工具可以看到，高度是在 `.el-form-item__content` 中发生改变的，`.el-color-picker` 的高度是正确的。
当我将 `.el-color-picker` 的 display 修改为 `block` 或 `inline-flex` 时，高度就会正常。

### What is Expected?
高度和其他 form-item 一致

### What is actually happening?
在默认 size 下，高度增加了 15px
在 medium size 下，高度增加了 13px

**Comment by ZSkycat** [comment]
可能和见鬼了的 `line-height` 有关系。

当我将 .el-color-picker 元素的 `innerHTML` 改为纯文本时，去掉 `line-height: normal;`，高度恢复正常。
但是在不修改 dom 的情况下，去掉 `line-height: normal;` 是无效的。不过当我添加 vertical-align: top; 之后，高度也可以恢复正常。

后续：
当我添加 vertical-align: baseline; 时，可以发现，`el-form-item__label` 的文本 和 `el-color-picker__icon` 的箭头图标 的基线对齐了！
也就说是因为基线强行对齐导致强行挤出高度

**Comment by ZSkycat** [comment]
临时解决方案
```css
.el-form-item__content > .el-color-picker {
    vertical-align: top;
}
```

**Comment by ziyoung** [comment]
@ZSkycat 确实是 line-height 引起的问题。https://jsfiddle.net/zhiyang/v593az6k/2/ 
使用 line-height 居中，有些时候不一定生效。在本例中， select 之类组件的 `display` 也是 `block`，却不会引起高度增加。😅
