### ISSUE TITLE
Can [Feature Request] tree components customize triangle icons?

### ISSUE THREAD

**Issue by lovewxz** [ElemeFE/element#12737]
### Existing Component
是

### Component Name
tree

### Description
https://jsfiddle.net/70xeny1r/25/
rendercontent,slot-scope方式只能修改节点内的内容。并不能影响到原生的三角形图标
目前只能通过修改css的方式去覆盖原来三角的图标。是否可以考虑后续增加自定义图标的入口

**Comment by ziyoung** [comment]
@lovewxz 目前是只能这么做了。以后可以添加一个 icon 属性。
