### ISSUE TITLE
[Bug Report] CSS rotation attribute rotate and elementUI select selector clash clicking select when font jitter

### ISSUE THREAD

**Issue by Eunknight** [ElemeFE/element#12734]
### Element UI version
2.4.6

### OS/Browsers version
windows/ chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Eunknight/pjcfa0t3/22/](https://jsfiddle.net/Eunknight/pjcfa0t3/22/)

### Steps to reproduce
点击选择框

### What is Expected?
字体不抖动

### What is actually happening?
字体抖动

**Comment by ziyoung** [comment]
@Eunknight 原因未知。与正常的文字相比，但是内容在旋转之后是字体是变细了的。😅
https://jsfiddle.net/zhiyang/pjcfa0t3/30/
![image](https://user-images.githubusercontent.com/12947422/45605562-7bbeb780-ba70-11e8-9c29-33396d113d68.png)

**Comment by island205** [comment]
Sorry, we have no plan to support this.
