### ISSUE TITLE
[Bug Report] Form-Item does not emit individual errors as they happen

### ISSUE THREAD

**Issue by YamenSharaf** [ElemeFE/element#12732]
### Element UI version
2.4.6

### OS/Browsers version
All

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mkv54a6s/](https://jsfiddle.net/mkv54a6s/)

### Steps to reproduce
Try to react to errors on individual form items by displaying a different kind of error messages

### What is Expected?
To be able to react to errors and have my own custom validation strategy. have more general flexibility

### What is actually happening?
Not possible to react to errors in a different way than existing implementation

**Comment by YamenSharaf** [comment]
Created PR to fix this issue by emitting an array of errors when an error occurs. User can then listen to that event which provides the name of the field associated and the error message.

https://github.com/ElemeFE/element/pull/12733

**Comment by ziyoung** [comment]
`Validate` is added in pr #10351. I think you also can get error info by listening the `validate` event.

**Comment by YamenSharaf** [comment]
Validate event works on the form as a whole, so it's not easy to make a component to wrap each form element and handle them individually, which is what I'm trying to rectify with this.

I made this PR and [another one](https://github.com/ElemeFE/element/pull/12715) to essentially make errors more customizable by the end user since currently, it's unwieldy to try to change how error messages look like in a different way than the default behaviour (red text under form element).

**Comment by YamenSharaf** [comment]
One more thing. The Form element's validate event does not emit the error message (Which should be fixed too imo). It just returns the validation status as a boolean which isn't very useful.

**Comment by ziyoung** [comment]
ref #12860
