### ISSUE TITLE
Don't require span attribute for flex rows.

### ISSUE THREAD

**Issue by tomtev** [ElemeFE/element#1274]
Right now you get a error message if you don't have span on `<el-col>.`
This is often not needed if you have a `<el-row type="flex">`

Is it possible to disable the error message on flex rows?

**Comment by Leopoldthecoder** [comment]
`span` is no longer `required` since Element 1.0.1 ([changelog](http://element.eleme.io/#/en-US/component/changelog)), so perhaps you can just upgrade it.
