### ISSUE TITLE
[Bug Report] Checkbox Group multi row Checkbox arrangement using v-for

### ISSUE THREAD

**Issue by nuneramu** [ElemeFE/element#12740]
### Element UI version
2.4.6

### OS/Browsers version
Windows 8.1

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/rnune/z9mwgfkd/8/](https://jsfiddle.net/rnune/z9mwgfkd/8/)

### Steps to reproduce
Checkbox Items should be on new line and it is not fitting within the dialog. It should also wrap on to new line

### What is Expected?
Checkbox Items should be on new line and it is not fitting within the dialog. It should also wrap on to new line

### What is actually happening?
It is overflowing out of the dialog

**Comment by wacky6** [comment]
Just write your own css.
