### ISSUE TITLE
[Feature Request] suggests that Cascader support whether the disabled option can be expanded.

### ISSUE THREAD

**Issue by PilgrimErick** [ElemeFE/element#12745]
### Existing Component
是

### Component Name
Cascader

### Description
产品开发过程中碰到一个需求：对于区域树而言，用户没有“深圳市”权限，但是有其市区级例如“龙华区”的权限，这时想要点击“深圳市”时展开下级区域，且不触发“深圳市”本身的change，目前是不满足的，因为“深圳市”disabled为true时，直接就不让展开了。

建议新增一个如 disabled-openable 的 Attribute，值类型为Boolean，默认为false，表示禁用项不可展开，true表示禁用项可以展开。

**Comment by ziyoung** [comment]
Cascader 组件中的数据有着很明显的上下级层次。像你这种场景算是非常特殊的情况，我们暂时没有打算去实现该功能。

**Comment by 9-lives** [comment]
> Cascader 组件中的数据有着很明显的上下级层次。像你这种场景算是非常特殊的情况，我们暂时没有打算去实现该功能。

这种情况并不少见。我们之前基于 change-on-select 封装了类似的逻辑，现在如何升级到新版？
