### ISSUE TITLE
[Bug Report] el-select keyboard for iOS devices doesn't show up when filterable is true but mutliple is false

### ISSUE THREAD

**Issue by pcaleja** [ElemeFE/element#12742]
### Element UI version
2.4.6

### OS/Browsers version
iOS Safari

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/45kvjg6u/13/](https://jsfiddle.net/45kvjg6u/13/)

### Steps to reproduce
When using the iOS simulator, use an iPad Pro device to open the reproduction link
- Click the first select and try typing with the keyboard and text won't be inputted
- Click the second select and try typing with the keyboard and text is inputted

When using an actual device
- Clicking the first select will not render the iOS keyboard
- Clicking the second select will render the iOS keyboard

### What is Expected?
Users should be able to input text for el-select components when filterable is true for iOS devices

### What is actually happening?
Users are only able to input text for el-select components when filterable is true when mutliple is also true for iOS devices

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1

**Comment by AlexGodbehere** [comment]
This is a terrible answer. For the most part, ElementUI works (and looks!) great on mobiles with a few tweaks to the css.

Has anyone managed to get round this?

**Comment by scs-ben** [comment]
I agree, ignoring mobile is not possible. This will be require me to use a different framework.

**Comment by vytya** [comment]
I had same issue with el-select. 
Could not solve it and started to use el-autocomplete. In my case everything is ok on IOS.

**Comment by caesaram** [comment]
It's a shame because it works fine on desktop, even in mobiles based on Android OS.

It doesn't make sense that it won't work only in IOS based web browsers

**Comment by aotechsmartsoft** [comment]
> Element is designed for desktop. It's not compatible with mobile devices. You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1

@ziyoung ElementIO works perfectly in Android browsers (it's mobile too). 
Maybe instead of saying "you can use other libraries", you could point this bug with less priority, to see it later.

Regards

**Comment by mattharley** [comment]
a good workaround is to set `multiple` and `:multiple-limit="1"`

**Comment by robertrm0** [comment]
> una buena solución es establecer y `multiple``:multiple-limit="1"`

The best solution so far

**Comment by TravisHi** [comment]
Hey guys, thankfully "Dongdong notes" an alternate fix for this that seems to work for my use case here: [https://cdmana.com/2021/01/20210119003837456j.html](https://cdmana.com/2021/01/20210119003837456j.html)
(I couldn't use @mattharley solution above)

Here's the solution directly from "Dongdongs notes", check out the above link for a more in depth explanation:

```
<template>
    <el-select
        ref="select"
        @hook:mounted="cancalReadOnly"
        @visible-change="cancalReadOnly"
    >
        
    </el-select>
</template>

<script>
    export default {
        methods: {
            cancalReadOnly(onOff) {
                this.$nextTick(() => {
                    if (!onOff) {
                        const {select} = this.$refs;
                        const input = select.$el.querySelector('.el-input__inner');
                        input.removeAttribute('readonly');
                    }
                });
            }
        }
    }
</script>
```

**Comment by jayrom123** [comment]
> Hey guys, thankfully "Dongdong notes" has an alternate fix for this that seems to work for my use case here: https://cdmana.com/2021/01/20210119003837456j.html
> (I couldn't use @mattharley solution above)
> 
> Here's the solution directly from "Dongdongs notes", check out the above link for a more in depth explanation:
> 
> ```
> <template>
>     <el-select
>         ref="select"
>         @hook:mounted="cancalReadOnly"
>         @visible-change="cancalReadOnly"
>     >
>         
>     </el-select>
> </template>
> 
> <script>
>     export default {
>         methods: {
>             cancalReadOnly(onOff) {
>                 this.$nextTick(() => {
>                     if (!onOff) {
>                         const {select} = this.$refs;
>                         const input = select.$el.querySelector('.el-input__inner');
>                         input.removeAttribute('readonly');
>                     }
>                 });
>             }
>         }
>     }
> </script>
> ```

could add ` input.blur()`

**Comment by xlch88** [comment]
`//fix
let fixElSelect = function () {
	document.querySelectorAll('.el-select[data-is-search="true"]:hover').forEach((v) => {
		let a = document.querySelector('.el-select[data-is-search="true"]:hover input[readonly]');
		if (a) {
			console.log(a);
			a.readOnly = false;
			a.blur();
			a.focus();
		}
	});
};
document.addEventListener("focusin", fixElSelect);
document.addEventListener("click", fixElSelect);
document.addEventListener("touchstart", fixElSelect);`

**Comment by mes01** [comment]
The most stable solution with the directive `v-cancel-read-only`

Template:
`<el-select v-cancel-read-only>...</el-select>`

Script: 
```js
directives: {
  cancelReadOnly (el) {
    const input = el.querySelector('.el-input__inner');
    input.removeAttribute('readonly');
  }
}
```

**Comment by lovempty** [comment]
> Add the following code to main.js, and add `data-is-search="true"` to each el-select
> 
> ```js
> //fix el-select
> let fixElSelect = function () {
> 	document.querySelectorAll('.el-select[data-is-search="true"]:hover').forEach((v) => {
> 		let elInput = document.querySelector('.el-select[data-is-search="true"]:hover input[readonly]');
> 		if (elInput) {
> 			elInput.readOnly = false;
> 			elInput.blur();
> 			elInput.focus();
> 		}
> 	});
> };
> document.addEventListener("focusin", fixElSelect);
> document.addEventListener("click", fixElSelect);
> document.addEventListener("touchstart", fixElSelect);
> ```

thank you so much. it seems work to me
