### ISSUE TITLE
[Bug Report] should not import Vue in the tooltip component

### ISSUE THREAD

**Issue by Hanks10100** [ElemeFE/element#12741]
### Element UI version
2.4.6

### OS/Browsers version
any

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/blob/4017fe4bd948ecf966afd256328c4e8911d97812/packages/tooltip/src/main.js#L6](https://github.com/ElemeFE/element/blob/4017fe4bd948ecf966afd256328c4e8911d97812/packages/tooltip/src/main.js#L6)

### Steps to reproduce
Just try this (with a well configured build environment): 

```js
import { Tooltip } from 'element-ui'
Vue.use(Tooltip)
```

It'll package the whole source code of Vue.js.

### What is Expected?
The generated file should not contain the source code of Vue.js.

### What is actually happening?
If the Vue package is imported separately (such as via `<script>`), it'll import another Vue and override the former one.

> I guess the reason to import vue is to implement the [`popperVM`](https://github.com/ElemeFE/element/blob/4017fe4bd948ecf966afd256328c4e8911d97812/packages/tooltip/src/main.js#L69), but I think it's a little tricky. There must be another way to achieve it.

**Comment by Hanks10100** [comment]
I also found these files also import the Vue.js:

```
element/packages/cascader/src/main.vue
element/packages/color-picker/src/draggable.js
element/packages/date-picker/src/picker.vue
element/packages/loading/src/directive.js
element/packages/loading/src/index.js
element/packages/message-box/src/main.js
element/packages/message/src/main.js
element/packages/notification/src/main.js
element/packages/popover/index.js
element/packages/table/src/dropdown.js
element/packages/table/src/table-header.js
element/packages/table/src/table-layout.js
element/packages/table/src/table-store.js
element/packages/tooltip/src/main.js
element/src/locale/index.js
element/src/utils/clickoutside.js
element/src/utils/dom.js
element/src/utils/popup/index.js
element/src/utils/popup/popup-manager.js
element/src/utils/scroll-into-view.js
element/src/utils/scrollbar-width.js
element/src/utils/vue-popper.js
```

**Comment by ziyoung** [comment]
The output bundles don't contain Vue. We set `externals` in webpack config.
https://github.com/ElemeFE/element/blob/4017fe4bd948ecf966afd256328c4e8911d97812/build/config.js#L30-L34

**Comment by Hanks10100** [comment]
@ziyoung Yes, you did. But I may not always treat Vue as external.

If I want to require a standalone component of element-ui, I have to modify so many configs and may have conflicts with my former one. Import vue in the component can cause unnecessary complexity of build scripts.
