### ISSUE TITLE
[Bug Report] editable timerange select - display bug

### ISSUE THREAD

**Issue by LiCasey** [ElemeFE/element#12751]
### Element UI version
2.4.6

### OS/Browsers version
Windows 10 1803 17134.228 / Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5841/](https://jsfiddle.net/mmx38qxw/5841/)

### Steps to reproduce
1. type a start time later than end time
2. try to change the end time

### What is Expected?
the end time text change as click on different number in the popover menu

### What is actually happening?
if you select an end time using the popover menu, the text displayed on the time select will not be changed

**Comment by ziyoung** [comment]
Can't reproduce.
