### ISSUE TITLE
[Bug Report] Tabs component colors and font size can not be modified by user

### ISSUE THREAD

**Issue by YamenSharaf** [ElemeFE/element#12758]
### Element UI version
2.4.6

### OS/Browsers version
All

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/gpv6eywd/](https://jsfiddle.net/gpv6eywd/)

### Steps to reproduce
Try to change tabs and tab item colors.

### What is Expected?
Being able to change colors via prop or sass variable.

### What is actually happening?
No way to change colors or font size.

**Comment by YamenSharaf** [comment]
I made a [PR](https://github.com/ElemeFE/element/pull/12759) to address this issue by implementing color variables in vars.scss files. As of right now, colors are baked right into the component. https://github.com/ElemeFE/element/pull/12759

**Comment by ziyoung** [comment]
Now Tab doesn't support so many variables. I also think there's no need to do this. If you like, you can overwrite the default style of Tab.

**Comment by lianzhao** [comment]
@ziyoung  Element provided variable [`$--tab-font-size`](https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/common/var.scss#L497), but the `font-size` of `.el-tabs__item` element was hard-coded to `14px` in the [source code](https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/tabs.scss#L99).
