### ISSUE TITLE
[Bug Report] Table component bug, when the parent has a two-tier flex layout, Table components cannot be responsively laid out according to the browser width

### ISSUE THREAD

**Issue by FE-xiaoJiang** [ElemeFE/element#12756]
### Element UI version
2.3.7

### OS/Browsers version
win8

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/不好意思，这个bug无需链接或者项目](https://jsfiddle.net/mmx38qxw/不好意思，这个bug无需链接或者项目)

### Steps to reproduce
1、如下代码父级双层flex布局：
[div style="height: 306px;display: flex;"]
    [div style="display: flex;height: 300px;flex: 1;"]
      [Table height="270"
              row-class-name="row"
              header-row-class-name="dt-header"
              cell-class-name="col"
              style="width: 100%;"
              ]
          [table-column
            prop="seq11"
            label="排名11"]
      [/Table]
    [/div]
  [/div]
(ps:这里<>会被过滤)
2、刷新完成后，缩小浏览器，发现table不会自适应，尺寸会超出布局

### What is Expected?
能够正常随浏览器缩放自适应

### What is actually happening?
缩小浏览器，发现table不会自适应，尺寸会超出布局

**Comment by LovelyAndy** [comment]
Hello @FE-xiaoJiang , I know this was a long time ago, but did you figure out how to fix this? I'm running into the same issue
