### ISSUE TITLE
建议 可搜索select 交互改为 不可直接在框中输入，防止输入不正确信息

### ISSUE THREAD

**Issue by cat-eat-what** [ElemeFE/element#1275]
可以改为这种方式
![image](https://cloud.githubusercontent.com/assets/13806668/20520265/18c25b7c-b0e1-11e6-9fa6-52669b6d4615.png)

在本地改完，但是不知道你们会不会接受这种形式～

**Comment by Leopoldthecoder** [comment]
看到你在 Gitter 里的讨论了。我们内部商量一下，如果可以的话欢迎 PR。

**Comment by Leopoldthecoder** [comment]
看到你的 PR 了，感谢贡献。后续会在那个 PR 里反馈，这个 issue 先关掉了。
