### ISSUE TITLE
When [Bug Report] Selector does not assign initial value to V-model, click invalid (label does not switch).

### ISSUE THREAD

**Issue by HelloKevinTian** [ElemeFE/element#12753]
### Element UI version
2.4.6

### OS/Browsers version
Windows7/chrome67.0.3396.99

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/Laudf7hp/3/](https://jsfiddle.net/Laudf7hp/3/)

### Steps to reproduce
点击Selector其他选项无法切换。

### What is Expected?
在未给Selector赋初始值的情况下，点击Selector选项正常切换。

### What is actually happening?
点击Selector其他选项无法切换。

**Comment by wacky6** [comment]
https://jsfiddle.net/8mncy43f/

麻烦先学一下 vue 基础。

**Comment by HelloKevinTian** [comment]
> https://jsfiddle.net/8mncy43f/
> 
> 麻烦先学一下 vue 基础。

你好，我的使用的场景并不是初始化就给select的v-model赋值的，表单都是动态生成的。所以v-model里的字段都是动态添加的，数量也是没有上限的。

**Comment by HelloKevinTian** [comment]
谢谢  重新看了一下vue文档，使用 this.$set(this.form, case_n, n) 解决。
