### ISSUE TITLE
[Feature Request] increases the location of components such as Dropdown under transform (scale).

### ISSUE THREAD

**Issue by 2227068304** [ElemeFE/element#12750]
### Existing Component
是

### Component Name
dropdown

### Description
为了方便适配各种屏幕 利用了在body上添加transform(scale)进行放大缩小  结果发现之前很好用的dropdown现在的弹出位置一坨x  偏移了十万八千里  看了下源码  在transform下popper库获取不到正确的位置了 这个不知道算不算bug 只能自己手动把源码改了 各位element的大神 是否可以添加此项功能 这个库已经很好用了 要是能连放大缩小的场景也能支持就更完美了  我是element的真爱粉  希望此库越来越强大

**Comment by ziyoung** [comment]
Duplicate of #10311

**Comment by ziyoung** [comment]
找到了一个类似的 issue。https://github.com/FezVrasta/popper.js/issues/376
