### ISSUE TITLE
date-picker的样式问题

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#1276]
### Reproduction Link
http://element.eleme.io/#/zh-CN/component/datetime-picker

### Steps to reproduce
![1](http://p1.bqimg.com/1949/bfa0eeeac55453c9.png)
### What is Expected?
某个时间的color还是 .el-time-spinner__item.active:not(.disabled) 的样式 color为#fff

**Comment by reverland** [comment]
233

**Comment by QingWei-Li** [comment]
fixed in #1276
