### ISSUE TITLE
[Bug Report] why elementUI's MessageBox showInput attribute is invalid?

### ISSUE THREAD

**Issue by qinkaiyuan** [ElemeFE/element#12769]
### Element UI version
0.1.0

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
import { MessageBox } from 'element-ui'

MessageBox('请输入邮箱', '提示', {
    showInput: true,
    inputValue: 'haha',
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    inputPattern: /[\w!#$%&'* /=?^_`{|}~-] (?:\.[\w!#$%&'* /=?^_`{|}~-] )*@(?:[\w](?:[\w-]*[\w])?\.) [\w](?:[\w-]*[\w])?/,
    inputErrorMessage: '邮箱格式不正确'
  }).then(({ value }) => {
    console.log(value)
  }).catch(() => {
  })
}

### What is Expected?
能正常显示input

### What is actually happening?

不显示

**Comment by ziyoung** [comment]
```js
Vue.prototype.$msgbox = MessageBox
// ...
this.$msgbox('请输入邮箱', '提示')
```

**Comment by qinkaiyuan** [comment]
> ```js
> Vue.prototype.$msgbox = MessageBox
> // ...
> this.$msgbox('请输入邮箱', '提示')
> ```

您这个并不能显示input框，我说的是showInput这个属性无效

**Comment by qinkaiyuan** [comment]
> @qinkaiyuan 不好意思，这是我的锅。😅
> 最快的方式是按照下面使用：
> 
> ```js
> Vue.prototype.$prompt = MessageBox.prompt
> this.$prompt()
> // 或者
> MessageBox.prompt()
> ```
> 
> 不过直接调用 Message ，设置的 showInput 属性不应该被默认值覆盖了。
> [element/packages/message-box/src/main.js](https://github.com/ElemeFE/element/blob/1cbc9f6363878961a1cfe002aa9966e9702e705c/packages/message-box/src/main.js#L139)
> 
> Line 139 in [1cbc9f6](/ElemeFE/element/commit/1cbc9f6363878961a1cfe002aa9966e9702e705c)
> 
>  options: merge({}, defaults, MessageBox.defaults, options), 
> 
> 有时间我再看一下问题。

您好，我有个私人问题，可以付您酬劳，能帮忙解决下么，或者说一下酬劳多少您可以接受，谢谢

这样只能显示一个input，我需要两个input，用来输入用户名和密码，在一个纯JS页面，获取不到vue的this对象，所以我无法使用dialog，希望您能帮助解决一下，比较着急，谢谢

**Comment by qinkaiyuan** [comment]
> @qinkaiyuan 不好意思，这是我的锅。😅
> 最快的方式是按照下面使用：
> 
> ```js
> Vue.prototype.$prompt = MessageBox.prompt
> this.$prompt()
> // 或者
> MessageBox.prompt()
> ```
> 
> 不过直接调用 Message ，设置的 showInput 属性不应该被默认值覆盖了。
> [element/packages/message-box/src/main.js](https://github.com/ElemeFE/element/blob/1cbc9f6363878961a1cfe002aa9966e9702e705c/packages/message-box/src/main.js#L139)
> 
> Line 139 in [1cbc9f6](/ElemeFE/element/commit/1cbc9f6363878961a1cfe002aa9966e9702e705c)
> 
>  options: merge({}, defaults, MessageBox.defaults, options), 
> 
> 有时间我再看一下问题。

我没找到站内信功能，抱歉， wx qq都可以

**Comment by qinkaiyuan** [comment]
> @qinkaiyuan 不好意思，这是我的锅。😅
> 最快的方式是按照下面使用：
> 
> ```js
> Vue.prototype.$prompt = MessageBox.prompt
> this.$prompt()
> // 或者
> MessageBox.prompt()
> ```
> 
> 不过直接调用 Message ，设置的 showInput 属性不应该被默认值覆盖了。
> [element/packages/message-box/src/main.js](https://github.com/ElemeFE/element/blob/1cbc9f6363878961a1cfe002aa9966e9702e705c/packages/message-box/src/main.js#L139)
> 
> Line 139 in [1cbc9f6](/ElemeFE/element/commit/1cbc9f6363878961a1cfe002aa9966e9702e705c)
> 
>  options: merge({}, defaults, MessageBox.defaults, options), 
> 
> 有时间我再看一下问题。

您好我的微信是 qky19941212  如果可以的话请您加我下 谢谢

**Comment by ziyoung** [comment]
@qinkaiyuan 如果你的项目中用到了 babel-plugin-transform-vue-jsx 这个插件，这个就很好解决了。
https://jsfiddle.net/r1ktewp3/3/

**Comment by qinkaiyuan** [comment]
> @qinkaiyuan 如果你的项目中用到了 babel-plugin-transform-vue-jsx 这个插件，这个就很好解决了。
> https://jsfiddle.net/r1ktewp3/3/

能否私聊下呢，愿意付酬劳的，不白白让您辛苦，我对前端不太懂，搞后台java的，最近做个登录涉及到权限 跨域，等等所以才弄的前端，可以么
