### ISSUE TITLE
[Bug Report] el-form with one el-form-item cause chrome browser reboot

### ISSUE THREAD

**Issue by abernov** [ElemeFE/element#12760]
### Element UI version
2.4.6

### OS/Browsers version
Windows/ Chrome Version 69.0.3497.92 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/abernov/0e8koj3y/](https://jsfiddle.net/abernov/0e8koj3y/)

### Steps to reproduce
select el-input and click Enter on keyboard. 

If add second el-input then BUG disappears.

### What is Expected?
The browser will not reboot

### What is actually happening?
The browser will reboot.

**Comment by xi-osman** [comment]
Its not rebooting it is submitting the Form this is standard. Please read the docs .

W3C regulates that -> https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2

When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.

To prevent this behavior, you can add @submit.native.prevent on <el-form>.

**Comment by abernov** [comment]
Thanks. It work!
