### ISSUE TITLE
[Bug Report] table multilevel header fixed attribute invalid

### ISSUE THREAD

**Issue by tool2014** [ElemeFE/element#12764]
### Element UI version
2.4.6

### OS/Browsers version
windows10 / chrome 63

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5886/](https://jsfiddle.net/mmx38qxw/5886/)

### Steps to reproduce
table多级表头，第一级分别为1，2，3。对应的子标题分别为（1-1，1-2，1-3），（2-1，2-2，2-3），（3-1，3-2，3-3）。
需求：让大标题1固定在table左边，无论是给1或者（1-1，1-2，1-3）或者两者都加fixed均无法实现效果，

### What is Expected?
给大标题1加入fixed可实现（1-1，1-2，1-3）固定

### What is actually happening?
给大标题1加入fixed时仅（1-1）固定，给大标题2加fixed时（1-2）固定，给（1-1，1-2）等子标题加fixed无任何效果

**Comment by ziyoung** [comment]
Duplicate of #9926
