### ISSUE TITLE
[Feature Request] Possibility to render DatePicker without input element

### ISSUE THREAD

**Issue by DmitryLobachov** [ElemeFE/element#12779]
### Existing Component
Yes

### Component Name
DatePicker

### Description
It would be very useful if we could render DatePicker without input element, so it will be always visible for user. For example like in google's calendar page https://prnt.sc/kuyp9w
At the moment it is mandatory to click on input element to see DatePicker.

**Comment by wacky6** [comment]
See https://github.com/ElemeFE/element/issues/12779.

There is no clear timeline for this feature (as significant refactoring is required), because most maintainers lack time and resources at the moment.
