### ISSUE TITLE
[Feature Request] Table width adaptation

### ISSUE THREAD

**Issue by 13662150517** [ElemeFE/element#12773]
### Existing Component
是

### Component Name
Table

### Description
表格单元格内容太长，可以不换行，宽度自适应内容

**Comment by ziyoung** [comment]
我听得是一头雾水。用个例子展示你的问题吧。

**Comment by 13662150517** [comment]
表格一个单元格内容太长，如果内容不想换行，目前会显示 '...' 来表示超出部分，然后鼠标放到单元格上才显示全部内容，例如https://jsfiddle.net/13662150517/bsokxp47/9/ 链接里的地址那一列，我的意思是不显示 '...' 不换行，该列宽度根据内容加宽，当然也需要设置最小的宽度，内容超出最小宽度该列根据内容进行加宽

**Comment by ziyoung** [comment]
你的意思是：如果某一列的内容比较多，我需要把这一列宽度（这里的宽度可能是已经设置过的，也可能是剩余的宽度）自动增加？

**Comment by 13662150517** [comment]
是的

**Comment by shuaninfo** [comment]
+1

**Comment by tomieric** [comment]
try like this [https://kuaizi-co.github.io/kz-table/](https://kuaizi-co.github.io/kz-table/)

**Comment by qiushuaichang** [comment]
+1 ，I also want to get the style like bootstrap table, which Adaptive without width。
         我也想得到像bootstrap 表格一样的样式，就是不给列宽的情况下，表格自适应。
         如果某一列的内容比较多，我需要把这一列宽度自动增加，或者内容少的那列宽度本来很宽，可以自动减小？

**Comment by lela520** [comment]
+1待解决

**Comment by JiYJCoder** [comment]
求解决啊，很久的问题了，原生的table这个功能是自带的

**Comment by JiYJCoder** [comment]
已解决了。写一个css就可以了

**Comment by JiYJCoder** [comment]
原生table自带的功能，写成组件倒是没有了。建议不要使用colgroup来控制每一列了

**Comment by xiaodingmao** [comment]
啥时候可以单元格宽度自适应内容呀

**Comment by ziyoung** [comment]
可以先阅读一下这篇文章：https://zhuanlan.zhihu.com/p/33280304
这个功能大家呼声还是很强的。应该提供这种功能。

**Comment by longlonggi** [comment]
在移动端表格横向布局的时候，超出内容显示成toptip，方向和位置都不对，请问有什么好的方法解决吗，或者可以让列宽根据内容宽度自适应
