### ISSUE TITLE
[Bug Report] Table does not appear scrollbars.

### ISSUE THREAD

**Issue by 13662150517** [ElemeFE/element#12774]
### Element UI version
2.4.7

### OS/Browsers version
chrome69.0.3497.92

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/13662150517/mp6Lh38c/2/](https://jsfiddle.net/13662150517/mp6Lh38c/2/)

### Steps to reproduce
打开链接查看表格

### What is Expected?
显示滚动条

### What is actually happening?
表格内容部分已经查出给定的高度，但没有显示滚动条

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
