### ISSUE TITLE
How does a form with [Feature Request] dynamic loops get the value of the current check index or loop item in a custom Validator?

### ISSUE THREAD

**Issue by x269147836** [ElemeFE/element#12788]
### Existing Component
是

### Component Name
el-form-item

### Description
循环的表单中只有两个字段A与B，字段A的校验依赖字段B的状态，如果填写了B，那么必须填写B字段吗，否则可以不填写。

例如选择了a，可以不填写b，但是填写了b必须选择a：

<div v-for="(item, index) in value">
	<el-form-item label="字段A" :prop="'formData.'   index   '.a'" :rules="rules.a">
		<el-cascader :options="someData" v-model="item.b"></el-cascader>
	</el-form-item>
	<el-form-item label="字段B" :prop="'formData.'   index   '.b'" :rules="rules.b">
		<el-input v-model="item.b"></el-input>
	</el-form-item>
</div>

**Comment by ziyoung** [comment]
https://jsfiddle.net/bdj83tLa/7/
