### ISSUE TITLE
[Feature Request] Programmatically set validation field to invalid state

### ISSUE THREAD

**Issue by DmitryLobachov** [ElemeFE/element#12780]
### Existing Component
Yes

### Component Name
el-form

### Description
At the moment there is no way to set validation field to invalid state programmatically. We could trigger 'validateField' method for specific field, but it will only trigger existing validation rules.
It would be nice if we had some method that accepts desired field to validate and error message as string (e.g. form.invalidField(field, 'Some error message')). 
Currently as a workaround its possible to do this hack that achieves desired effect:
```javascript
const falsyValidator = {
    validator: (rule, value, callback) => callback(new Error(errorMessage)),
    trigger: 'manual'
  };
  validationRules[field].push(falsyValidator);
  form.validateField(field, () => validationRules[field].splice(-1, 1));
```

I'm adding 'falsy' validator that will always return error to validation rules for specified field, than we need to trigger validateField method and afterwards remove this validator. As a result user will see error message and invalid field on UI.

**Comment by ziyoung** [comment]
You can set FormItem error attribute. https://jsfiddle.net/04dmf85w/ It works for you.
Right now, we have no plan to support this.
