### ISSUE TITLE
There is a bug about dynamic tabs support 

### ISSUE THREAD

**Issue by cycold** [ElemeFE/element#1278]
element-ui 1.0.2
vue 2.0.3
chrome 53

https://github.com/ElemeFE/element/pull/812
https://github.com/ElemeFE/element/issues/407

目前可以动态push,但是不能splice
报错: `Cannot read property 'removeChild' of null`
```
destroyed:function(){this.$el&&this.$el.parentNode.removeChild(this.$el)}
```
重现: http://codepen.io/cycold/pen/dOvBqx

**Comment by furybean** [comment]
#1285 已经修复。
