### ISSUE TITLE
[Feature Request] give me some small suggestions.

### ISSUE THREAD

**Issue by langyuxiansheng** [ElemeFE/element#12785]
### Existing Component
是

### Component Name
所有带有滚动条的组件

### Description
可以将所有带有滚动条的组件处理一下,这样就避免了粗大的滚动条了

**Comment by ziyoung** [comment]
如果你对默认的样式不满意的话，可以使用 CSS 设置 scroll 样式。我们目前没有不打算去实现这个功能。
