### ISSUE TITLE
[Bug Report] Date selection, the background color and font color are identical.

### ISSUE THREAD

**Issue by 0123cf** [ElemeFE/element#12789]
### Element UI version
2.4.7

### OS/Browsers version
window10

### Vue version
2.5.17

### Steps to reproduce
see： https://upload-images.jianshu.io/upload_images/6759456-2efe423800d661d7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

### What is Expected?
https://upload-images.jianshu.io/upload_images/6759456-2efe423800d661d7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

### What is actually happening?
https://upload-images.jianshu.io/upload_images/6759456-2efe423800d661d7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by wacky6** [comment]
Please provide the actual code that reproduce this problem. 
Our demo/documentation code seems fine.
