### ISSUE TITLE
[Bug Report] change to

### ISSUE THREAD

**Issue by fakaka** [ElemeFE/element#12787]
### Element UI version
2.4.7

### OS/Browsers version
windows10/chrome62

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/](https://github.com/ElemeFE/element/)

### Steps to reproduce
timeline 组件的文档页面的 ‘⾃ 定义’ 改为自定义

### What is Expected?
自定义

### What is actually happening?
 ‘⾃ 定义’

**Comment by fakaka** [comment]
这个真的秀到我了

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/45752473-26d59980-bc48-11e8-9902-4a6f378747a1.png)
在文档里搜索一下，并没有发现。能直接告诉我们是在哪个地方吗？

**Comment by fakaka** [comment]
我记得当时你们合并了next分支

**Comment by ziyoung** [comment]
@faka 这是 timeline 组件的文档，https://deploy-preview-11736--element.netlify.com/#/zh-CN/component/timeline 暂时我也没发现你说的问题。

**Comment by fakaka** [comment]
![360 20180921164320700](https://user-images.githubusercontent.com/12379312/45870463-85705400-bdbd-11e8-9a35-fb456e59ebf7.jpg)
![360 20180921164333942](https://user-images.githubusercontent.com/12379312/45870464-85705400-bdbd-11e8-9cc0-2fe6aeeba8bb.jpg)

@ziyoung 应该看得出不一样吧
下面是正确的
![360 20180921164453537](https://user-images.githubusercontent.com/12379312/45870530-b05aa800-bdbd-11e8-9aa3-ec968adc49d8.jpg)

**Comment by ziyoung** [comment]
> ⾃定义时间戳
> 当内容在垂直⽅向上过⾼时，可将时间戳置于内容之上。

这样写有什么问题吗？

如果文档描述的不清，你觉得有更好的做法，欢迎提 pr 。

**Comment by fakaka** [comment]
@ziyoung 文档表达的信息没有问题，是错别字。把 ‘⾃’ 改为 ‘自’。
