### ISSUE TITLE
一个建议: tab 组件可否增加一个disabled状态

### ISSUE THREAD

**Issue by cycold** [ElemeFE/element#1279]
<img width="387" alt="qq20161122-0 2x" src="https://cloud.githubusercontent.com/assets/2446601/20523926/7eaa2f1c-b0f2-11e6-8e81-076316b6db19.png">

**Comment by furybean** [comment]
目前的 Tab 应该没有垂直状态？

**Comment by cycold** [comment]
调整了css 设置成的垂直
