### ISSUE TITLE
[Bug Report] Popper will not follow the rolling container when it is in slot.

### ISSUE THREAD

**Issue by ac51300696** [ElemeFE/element#12797]
### Element UI version
2.4.7

### OS/Browsers version
mac/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5996/](https://jsfiddle.net/mmx38qxw/5996/)

### Steps to reproduce
滚动一下

### What is Expected?
随之滚动

### What is actually happening?
popper没有随之滚动

**Comment by ac51300696** [comment]
有没有什么暂时比较好的解决方案

**Comment by ziyoung** [comment]
把右侧的 fixed 属性给去掉。https://jsfiddle.net/zhiyang/mmx38qxw/6108/

**Comment by ziyoung** [comment]
目前项目用的 Popperjs 版本很老了，估计在升级完之后就没问题了。相关的 pr #11778

**Comment by ac51300696** [comment]
这个升级什么时候能提上去呢，因为demo里的是个栗子,实际上用的不是table组件，所以这里的修改是具体修改了什么属性，修改了parents的position？

**Comment by feijuncheng** [comment]
所以这个问题有什么解决办法吗？
