### ISSUE TITLE
[Bug Report] Table summary method called multiple times

### ISSUE THREAD

**Issue by glittle** [ElemeFE/element#12795]
### Element UI version
2.4.7

### OS/Browsers version
Windows 8.1 / Chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/glittle/mmx38qxw/5988/](https://jsfiddle.net/glittle/mmx38qxw/5988/)

### Steps to reproduce
Run the sample.

The sample has a table with a summary function. In the function, a property in the current component is modified. This causes the table footer to have an infinite update warning.

### What is Expected?
The console should show one line showing "doing summary false"

### What is actually happening?
The console shows over 100 lines of "doing summary..." and ends with:
[Vue warn]: You may have an infinite update loop in a component render function.

**Comment by ziyoung** [comment]
@glittle Don't change data in `summaryMethod`. If you change some data in `summaryMethod`, the component re-renders and this method is called again. So it causes an infinite loop.
https://jsfiddle.net/zhiyang/mmx38qxw/6115/

**Comment by glittle** [comment]
This should be mentioned in the documentation!
