### ISSUE TITLE
When [Bug Report] slider is nested in table, drag failure occurs.

### ISSUE THREAD

**Issue by qinzitong** [ElemeFE/element#12796]
### Element UI version
2.4.7

### OS/Browsers version
Chrome 69.0.3497.92（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/15ud3pmq/](https://jsfiddle.net/15ud3pmq/)

### Steps to reproduce
https://jsfiddle.net/15ud3pmq/

### What is Expected?
在table中嵌套的slider 可以拖动

### What is actually happening?
在table中嵌套的slider 不可以拖动

**Comment by ziyoung** [comment]
v-model 暂时无法修改 slot-scope 中的数据 https://stackoverflow.com/questions/49512190/v-model-and-scoped-slots-not-working
建议在 data 中声明一个数组来保存绑定的值：https://jsfiddle.net/zhiyang/15ud3pmq/3/
