### ISSUE TITLE
[Bug Report] El-Upload displays native input button along the el-button

### ISSUE THREAD

**Issue by simonkaspersen** [ElemeFE/element#12794]
### Element UI version
2.4.7

### OS/Browsers version
Mac Os / Chrome 68.0.3440.106

### Vue version
2.1.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
I am implementing ElementUI inside a already existing project. All components are displaying fine except the el-upload. It shows the native input alongside the el-button:

```html
<el-row>
    <el-col :span="6">
      <el-upload
        class="image-uploader"
        ref="imageUploader"
        action="http://localhost:5000/api/blog/upload"
        :auto-upload="false"
        :file-list="fileList"
        :limit="1"
        accept=".jpg, .jpeg, .png"
        list-type="picture">
        <el-button slot="trigger" size="small" type="primary">select file</el-button>
        <div slot="tip">jpg/png files with a size less than 500kb</div>
      </el-upload>
    </el-col>
  </el-row>
```
https://imgur.com/a/22LXvyu

### What is Expected?
Only the el-button, like in the example and in the reproduction-link

### What is actually happening?
Both buttons is showing

**Comment by ziyoung** [comment]
@simonkaspersen Could you please provide a right link?

**Comment by suyridan** [comment]
Hello! 

I had the same problem and i fixed with this:

`input[type=file] {
    display:none;
}`

Grettings!!
