### ISSUE TITLE
[Bug Report] <el-checkbox>responsive mode can not be implemented when using checked attribute.

### ISSUE THREAD

**Issue by 15992033543** [ElemeFE/element#12799]
### Element UI version
2.4.7

### OS/Browsers version
win10 / chrome 69.0.3497.92

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6012/](https://jsfiddle.net/mmx38qxw/6012/)

### Steps to reproduce
1、el-checkbox use v-bind:checked="checked"

2、change checked value

3、el-checkbox no change style

I know the v-model directive.but consider the following scenario:

return this.$createdElement('el-checkbox', {
  props: {
    checked: this.checked
  }
})

because createElement cannot use v-model. so i don't know what are the best ways to change the style of checkbox when i change the checke value.

And I think it should be consistent with \<input type="checkbox" :checked="checked"\>.

### What is Expected?
el-checkbox change style

### What is actually happening?
el-checkbox no change style

**Comment by wacky6** [comment]
Please learn Vue basics before using element. https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
