### ISSUE TITLE
npm run bootstrap 安装出错是什么问题

### ISSUE THREAD

**Issue by sbbs3626** [ElemeFE/element#128]
> npm run bootstrap && npm run build:file && cooking watch -c scripts/cooking.demo.js -p

> element-ui@1.0.0-rc.4 bootstrap /Users/zhengqiong/GitHub/element
> npm i && lerna bootstrap --loglevel=error

npm WARN vue-infinite-scroll@0.2.3 requires a peer of vue@^1.0.10 but none was installed.
npm WARN vue-swipe@0.2.6 requires a peer of vue@^1.0.10 but none was installed.
npm WARN element-ui@1.0.0-rc.4 No license field.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Initializing Git repository.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

child_process.js:526
    throw err;
    ^

Error: Command failed: git init

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

**Comment by QingWei-Li** [comment]
XCode license 

```shell
sudo xcodebuild -license
```

**Comment by sbbs3626** [comment]
谢谢，已解决！
