### ISSUE TITLE
[Feature Request] Initializes the display position when the dialog pop-up window opens or adds a drag-and-drop event (instruction)

### ISSUE THREAD

**Issue by KnorienChang** [ElemeFE/element#12802]
### Existing Component
是

### Component Name
dialog

### Description
dialog 弹窗打开的时候初始化显示位置，自定义指令拖拽dialog的时候，改变了弹窗的位置，调用visable=false的时候，会记录下之前移动的弹窗位置。希望在自定义指令拖拽事件的时候，初始化dialog的位置或者提供拖拽的自定义指令。

**Comment by KnorienChang** [comment]
这里提供一个例子：https://jsfiddle.net/jk0e6g7u/5/

**Comment by ziyoung** [comment]
每次打开时，位置还原？https://jsfiddle.net/jk0e6g7u/9/
直接给 Dialog 设置个 key 就可以。这样能满足你的需求吧。

**Comment by KnorienChang** [comment]
@ziyoung 这样确实能够满足需求。我没有采用drag事件而是采用的监听mouse事件来写的指令。
