### ISSUE TITLE
[select]在提供了filter-method后，会出现删掉的内容被原来内容覆盖

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#1280]
### ElementUI version
1.0.2

### OS/Browers version
win10/Chrome 53 

### Vue version
2.0.8

### Reproduction Link
https://jsfiddle.net/gbw1jLd4/

### Steps to reproduce
在选中一个项后，再次点击，然后一下一下按回退键，会出现删掉的内容被原来内容覆盖，一直反复

**Comment by Leopoldthecoder** [comment]
和 Select 本身无关，是这个 demo 没写好。我改了一下：https://jsfiddle.net/gbw1jLd4/3/

**Comment by cmxz** [comment]
@Leopoldthecoder 如果想在删除掉已选内容后（即input框为空）显示所有选项，该怎么写？
http://jsfiddle.net/dw6uaaL4/1/ 这里提供了filterMethod方法，当从下拉列表选择一个值后，删掉内容后会自动恢复，当我把filterMethod中else逻辑去掉后就不会自动恢复，但是那样的情况就是当输入框无内容时，下拉列表里也无内容（理论上这时应该显示所有选项才比较合理）

**Comment by cmxz** [comment]
@Leopoldthecoder  参考你在https://github.com/ElemeFE/element/issues/2335#issuecomment-271792883 的回复搞定了，文档中没有关于这块儿的说明，有些不太友好，希望至少在http://element.eleme.io/#/zh-CN/component/select#ke-sou-suo 里的在线运行里提供一个有filter-method的demo
