### ISSUE TITLE
[Bug Report] el-input (decorated by v-model.number) can't input number like -0.xxx

### ISSUE THREAD

**Issue by goforward01** [ElemeFE/element#12804]
### Element UI version
2.4.7

### OS/Browsers version
windows 10 / Chrome 68.0.3440.84

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/goforward01/4jhmburs/1/](https://jsfiddle.net/goforward01/4jhmburs/1/)

### Steps to reproduce
input a number like -0.0001

### What is Expected?
appear to be -0.0001

### What is actually happening?
turn out to be 0.0001

**Comment by ziyoung** [comment]
Duplicate of #11885
