### ISSUE TITLE
[Bug Report] el-select - instant validation can not be triggered when set the trigger method with blur

### ISSUE THREAD

**Issue by cheqianxiao** [ElemeFE/element#12818]
### Element UI version
2.4.7

### OS/Browsers version
win 10 / chrome 68

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6101/](https://jsfiddle.net/mmx38qxw/6101/)

### Steps to reproduce
dropdown the select component and select nothing 

### What is Expected?
show error message when user blurs  the select input with noting selected

### What is actually happening?
does not show error message

**Comment by ziyoung** [comment]
Duplicate of #12273
