### ISSUE TITLE
[Feature Request] Badge Color

### ISSUE THREAD

**Issue by brunossn** [ElemeFE/element#12813]
### Existing Component
Yes

### Component Name
Badge

### Description
The red badge is perfect for warnings, but sometimes we need a different color for less important counters, like gray or blue, like this.

![image](https://user-images.githubusercontent.com/1033649/45710166-42fc0c80-bb5c-11e8-89fb-c863e9694637.png)

**Comment by ziyoung** [comment]
You can custom your theme or use CSS to overwrite the fault style.

**Comment by brunossn** [comment]
It's right, I created a class "mark-information" in CSS:

```
.mark-information sup {
    background-color: rgb(153, 173, 207);
}
```

So, I applied it to el-badge element:

`<el-badge class="mark" value="10" />`

**Comment by igeligel** [comment]
Hey @ziyoung, I am working on this issue right now. Actually quite far already. Would you be so nice and assign this issue to me, happy to contribute 👍 Also awesome framework. At my old company, we have used the date picker a lot.
