### ISSUE TITLE
[Bug Report] how can I update el-checkbox checked value in the table refresh-header?

### ISSUE THREAD

**Issue by 15992033543** [ElemeFE/element#12817]
### Element UI version
2.4.7

### OS/Browsers version
win 10 / chrome 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6098/](https://jsfiddle.net/mmx38qxw/6098/)

### Steps to reproduce
Yesterday I submitted a bug of el-checkbox.But it was closed.issue:https://github.com/ElemeFE/element/issues/12799

I'm sorry to cause you trouble.But I don't think it's my mistake to use Vue.

See the jsfiddle link.When I change the checkbox state of the list,I hope that the checkbox state of the head will also be changed.Using input(type=checkbox) can achieve this effect,but el-checkbox can not.I think that when the parent component modifies the child component state, the state of the child component should be updated.

### What is Expected?
See the jsfiddle link

### What is actually happening?
See the jsfiddle link

**Comment by 15992033543** [comment]
> ```diff
> props: {
> -  checked: that.allChecked1
> +  value: that.allChecked1
> },
> ```
> 
> https://jsfiddle.net/mmx38qxw/6157/

Thank you very much!Perfectly solves the problem!However, the document does not have the value attribute.It is easy to cause doubts.

**Comment by wacky6** [comment]
If you don't know where `value` is coming from, you should go and learn Vue basics: https://vuejs.org/v2/guide/components.html

**Comment by 15992033543** [comment]
> If you don't know where `value` is coming from, you should go and learn Vue basics: https://vuejs.org/v2/guide/components.html

Thank you very much!I need to learn again.
