### ISSUE TITLE
[Bug Report] Navigation menu folding state, using the mobile touch to open the submenu, click the submenu will be closed and then automatically reopen the submenu

### ISSUE THREAD

**Issue by DougFlands** [ElemeFE/element#12824]
### Element UI version
2.4.7

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6104/](https://jsfiddle.net/mmx38qxw/6104/)

### Steps to reproduce
浏览器F12使用移动端模式或使用移动端浏览器打开，点击一级菜单，点击二级菜单，此时二级菜单关闭，之后重新打开

### What is Expected?
不再重新打开

### What is actually happening?
会二次打开

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.
