### ISSUE TITLE
[Bug Report] el-dropdown placement is not work

### ISSUE THREAD

**Issue by sanyu1225** [ElemeFE/element#12823]
### Element UI version
2.4.6

### OS/Browsers version
win10 / chrome 69.0.3497.100 

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/v39k5d46/](https://jsfiddle.net/v39k5d46/)

### Steps to reproduce
<el-dropdown split-button type="primary" placement="top">
  默认尺寸
  <el-dropdown-menu slot="dropdown">
    <el-dropdown-item>黄金糕</el-dropdown-item>
    <el-dropdown-item>狮子头</el-dropdown-item>
    <el-dropdown-item>螺蛳粉</el-dropdown-item>
    <el-dropdown-item>双皮奶</el-dropdown-item>
    <el-dropdown-item>蚵仔煎</el-dropdown-item>
  </el-dropdown-menu>
</el-dropdown>

### What is Expected?
can change placement

### What is actually happening?
is not work

**Comment by ziyoung** [comment]
@sanyu1225 不算是 Element 的 bug。虽然你设置了 placement 为 top，但是因为 Dropdown 组件上面没有那么多的空间放置 popper，所以你觉得不生效。https://jsfiddle.net/zhiyang/v39k5d46/4/

Dropdown 组件依赖了 popperjs，popperjs 会自动计算能不能放得下 popper 元素，然后决定元素的位置。
