### ISSUE TITLE
[Slider]的v-model绑定一个NaN的值 浏览器貌似会卡住

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1282]
`
 <el-slider v-model="value4"">
    </el-slider>
`
今儿写到slider 赋值时候 this.value = parseInt( a ) 这个a是值是空字符串 然后chrome内存就开始无限+了 
不知是不是bug

https://jsfiddle.net/yelingfeng/5u16k232/4/

**Comment by Leopoldthecoder** [comment]
Fixed in #1286
