### ISSUE TITLE
[Bug Report] [Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by gaolongxin062** [ElemeFE/element#12827]
### Element UI version
2.4.6

### OS/Browsers version
win10/Chrome/61.0.3163.100

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1、我的项目是electron中引用element-ui;
2、在项目中使用select组件，偶尔会出现这种情况；

### What is Expected?
无报错

### What is actually happening?
报错，无法显示select组件，页面一片空白

**Comment by ziyoung** [comment]
@gaolongxin062 提供个可重现问题的链接吧。这样没法排查问题。

**Comment by CBCzed** [comment]
楼主，这个问题解决了吗？我也是在electron中引用element,版本是2.4.11，vue的版本升级了，偶尔也会出现同样的错误

**Comment by gaolongxin062** [comment]
> 楼主，这个问题解决了吗？我也是在electron中引用element,版本是2.4.11，vue的版本升级了，偶尔也会出现同样的错误

没有解决，试过很多方法了，都不管用，还是会出现。不知道怎么回事。

**Comment by DipSyJava** [comment]
到现在了，解决了么？ 同这个问题，偶现。
