### ISSUE TITLE
[Bug Report] el-table component, data gives dynamic data, and then selects one of them to become fully elected.

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/element#12826]
### Element UI version
2.4.6

### OS/Browsers version
Google Chrome/69.0.3497.92

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/t35a1wox/](https://jsfiddle.net/t35a1wox/)

### Steps to reproduce
选中其中某一项，就变为全选了
![image](https://user-images.githubusercontent.com/24503453/45742657-1663f580-bc2d-11e8-9988-86b7770bc0e0.png)

### What is Expected?
只选中我选中的那一项

### What is actually happening?
全选了

**Comment by ziyoung** [comment]
https://jsfiddle.net/t35a1wox/8/
```js
// arr.push(this.test))
arr.push(Object.assign({}, this.test))
```
