### ISSUE TITLE
[Bug Report] theme style coverage

### ISSUE THREAD

**Issue by oldDirver001** [ElemeFE/element#12834]
### Element UI version
2.4.7

### OS/Browsers version
win10/chrome 68.0.3440.84

### Vue version
2.5.17

### Reproduction Link
[https://github.com/oldDirver001/myDemo](https://github.com/oldDirver001/myDemo)

### Steps to reproduce
使用element-ui的自定义主题，搭配插件按需引入组件——Vue.use()，在使用组件的过程中发现样式覆盖，主题样式的引入顺序，与入口文件（main.js）当中Vue.use()方法引入组件的顺序有关。

重现链接是一个重新新建的小例子，在transfer组件当中，checkbox的样式和input的样式明显与官方文档中的例子不一样，这个项目就一个页面，打开页面就可以看得到，F12可以明显看到 transfer 的样式在很后面，被前面use的组件所覆盖。

在main.js当中，将Vue.use(transfer)放到最前面，这个问题就没有了。

也可能是我使用方式有问题，我是按照element文档中的步骤来使用“按需引用”、“自定义主题”这两个功能的。新建demo按步骤操作也有这种情况。

以上。

### What is Expected?
希望组件样式正常，不应该受到main.js当中引入顺序的影响

### What is actually happening?
theme当中的样式的引入顺序，与main.js当中的组件引入顺序有关。前面引入的组件，覆盖后面组件的样式。

**Comment by see311** [comment]
同样问题，按需引入后，在main.js中引入的css都被index.css覆盖
