### ISSUE TITLE
[Feature Request] select component always displays unmatched data if the filter mode is opened.

### ISSUE THREAD

**Issue by cuivip** [ElemeFE/element#12835]
### Existing Component
是

### Component Name
select

### Description
如题，在使用的过程中，还没进行录入，从何谈起有匹配结果呢？所以，那个东西不能默认显示，只能是输入内容后，确实没有匹配到时，才显示

**Comment by ziyoung** [comment]
![kapture 2018-09-20 at 16 00 05](https://user-images.githubusercontent.com/12947422/45804321-5b039580-bcee-11e8-9685-82edc2c02b58.gif)
拿官网上的这个例子来说：如果我没有输入，显示所有的 option 列表。假设我输入 1，找不到结果，显示无匹配数据项。从这里看不出你说的问题。

@cuivip 你说的我不太明白，能否提供了例子来说明？
