### ISSUE TITLE
The value-format attribute of the [Feature Request] DatePicker component does not support YYYY (upper case) and supports only yyyyy lowercase

### ISSUE THREAD

**Issue by yangjiacheng** [ElemeFE/element#12832]
### Existing Component
是

### Component Name
DatePicker

### Description
`<el-date-picker value-format="YYYY-MM-DD"></el-date-picker>`无法正常选择日期
https://momentjs.com都是采用YYYY大写格式
https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/standard-date-and-time-format-strings#YearMonth
“Y”或“y”在标准格式中应该是等价的

**Comment by wacky6** [comment]
Sorry, momentjs and MSDN can not be considered as standard. If you can find some ISO/IEEE/RFC documents that says YYYY and yyyy are equivalent, we might consider implementing it.
