### ISSUE TITLE
[Bug Report] when el-select delete el-option ,open el-dialog, el-option is not close

### ISSUE THREAD

**Issue by lazycatL** [ElemeFE/element#12842]
### Element UI version
2.4.7

### OS/Browsers version
Chrome69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6175/](https://jsfiddle.net/mmx38qxw/6175/)

### Steps to reproduce
1. select a el-option
2.click delete icon

### What is Expected?
el-option is close

### What is actually happening?
el-option display

**Comment by wacky6** [comment]
You have to blur select manually.

https://jsfiddle.net/23twzcuh/

**Comment by lazycatL** [comment]
> You have to blur select manually.
> 
> https://jsfiddle.net/23twzcuh/

thank you
