### ISSUE TITLE
The priority of `show-message and inline-message` of [Feature Request] Form component and Form-Item sub component

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#12844]
### Existing Component
是

### Component Name
Form、Form-Item

### Description
`Form`组件配置了`show-message、inline-message`，并且在`Form-Item`上也配置了不同于`Form`的`show-message、inline-message`，现在生效的仍是`Form`上的，不是`Form-Item`上的配置，这是要每个`Form-Item`都配置一遍才行？如果`Form和Form-Item`都配置了相同的属性，按理来说应该是子组件优先才对吧

**Comment by ziyoung** [comment]
就目前的实现来讲，是否显示错误信息是有 Form 与 FormItem 的 `show-message` 属性共同决定的。
https://github.com/ElemeFE/element/blob/17d817c0ce7a64bc290a021015e749720c932eb0/packages/form/src/form-item.vue#L18-L21
