### ISSUE TITLE
[Bug Report] NavMenu navigation. After changing pages, the background color of the active menu button changes to RGB (204204204).

### ISSUE THREAD

**Issue by NMSAzulX** [ElemeFE/element#12847]
### Element UI version
2.4.7

### OS/Browsers version
win10/最新的谷歌/最新的火狐

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、NavMenu菜单按钮自写样式
.hover_menu li:hover {
            background-color: #00000049 !important;
}
2、鼠标移动到菜单按钮上，菜单按钮显示透明黑色背景。
3、切换浏览器的tab页面，再切换回来
4、菜单按钮的颜色变成了白色rgb(204,204,204);

### What is Expected?
切换tab页不变颜色，菜单按钮的颜色不变，原来是什么样就什么样。

### What is actually happening?
切换tab页不变颜色，菜单按钮的颜色变成了白色rgb(204,204,204);

**Comment by NMSAzulX** [comment]
点击后正常：
![image](https://user-images.githubusercontent.com/16236903/45863573-5354f700-bda9-11e8-9d7b-5ba830fa8eec.png)
切换后异常：
![image](https://user-images.githubusercontent.com/16236903/45863557-39b3af80-bda9-11e8-969b-ed01653a49d5.png)

**Comment by ziyoung** [comment]
提供个可重现问题的链接。
