### ISSUE TITLE
[Feature Request] No uniquely identifiable selector for ElSelectDropdown child of ELSelect

### ISSUE THREAD

**Issue by lionslair** [ElemeFE/element#12845]
### Existing Component
Yes

### Component Name
ElSelectDropdown child of ElSelect

### Description
When performing browser based automated testing using Dusk (https://laravel.com/docs/5.7/dusk#introduction) I have an issue when I have multiple ElSelect on the one page or form.

When I click on the ElSelect element to display the dropdown this is added to the bottom of the page.

```
<template>
  <div
    class="el-select-dropdown el-popper"
    :class="[{ 'is-multiple': $parent.multiple }, popperClass]"
    :style="{ minWidth: minWidth }">
    <slot></slot>
  </div>
</template>
```

The selector for this is 

`.el-select-dropdown.el-popper.is-multiple`

or

`.el-select-dropdown.el-popper`

When I have two on the page my test does not pass because even if it's not visible I can not bind to the specific element that I clicked to display.

My request is to add a new prop to ElSelect that allows me to set an  id class or some attribute which can be passed into the div so that I can uniquely identify the dropdown when I am using multiple selects on a single page.

I did try to access the selectors with :first and -nth etc but that did not work and its not assured that the one currently displayed is the first or -nth on the page either.

**Comment by wacky6** [comment]
You can use `popperClass `

**Comment by lionslair** [comment]
Thank you for the response. That has helped me identify the one that is open. I still wasn't able to select the first item in the list. However when allowing multiple I was able to click on the button for select all.

Maybe a note could be added to the this line in the documentation to help others.


popper-class | custom class name for Select's dropdown | string | — | —
-- | -- | -- | -- | --


Just to help others that may encounter the same issue / problem

**Comment by wacky6** [comment]
Could you provide your test code snippet?

Selection of dropdown list item should be possible. Our own test does this.

**Comment by wacky6** [comment]
My recommendation is to make sure you have waited enough time for the dropdown to show (wait for animation).

And, the selector for option does not look right. Element uses `ul > li`, there is no button inside the dropdown.

**Comment by lionslair** [comment]
> My recommendation is to make sure you have waited enough time for the dropdown to show (wait for animation).
> 
> And, the selector for option does not look right. Element uses `ul > li`, there is no button inside the dropdown.

There is if you allow multiple
