### ISSUE TITLE
dialog show-close 无效

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1284]
在版本为1.0.0中，出现关闭按钮，但是一旦升级为1.0.1或者1.0.2就出现关闭按钮消失的情况。
![image](https://cloud.githubusercontent.com/assets/16740731/20529724/2109e82e-b10c-11e6-8cf6-bca670929138.png)
![image](https://cloud.githubusercontent.com/assets/16740731/20529738/29c5cc3a-b10c-11e6-907c-b41659dbc528.png)

**Comment by yuanshengchao** [comment]
已经找到原因了，show-close不能写成show-close，但是不写成带冒号的就会出现警告
![image](https://cloud.githubusercontent.com/assets/16740731/20533056/2e1ad8b0-b117-11e6-94fd-9a7866740fb0.png)

**Comment by Leopoldthecoder** [comment]
`show-close` 的值为 `true` 时才会显示关闭按钮，你的 `closeBool` 是 `false` 吧？

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20557625/2ebc44d0-b1a7-11e6-82b3-12f68fdf766f.png)
![image](https://cloud.githubusercontent.com/assets/16740731/20557632/38d9c820-b1a7-11e6-956d-bc739f71bb06.png)
![image](https://cloud.githubusercontent.com/assets/16740731/20557659/4e6e9724-b1a7-11e6-9bf8-fa2d74a03035.png)
您好，还是无法显示。请问是什么问题，如何解决？

**Comment by Leopoldthecoder** [comment]
把整个 `:show-close="compareClose"` 去掉呢？如果还不行的话，请提供 demo

**Comment by yuanshengchao** [comment]
我已经指导原因了，是tabs本事影响了close的样式造成看不见。可以关闭该问题了
