### ISSUE TITLE
[Bug Report] table 中类型为type="index"的header column不能自定义header-render

### ISSUE THREAD

**Issue by dmodaii** [ElemeFE/element#12848]
### Element UI version
2.4.7

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mocept/mmx38qxw/6196/](https://jsfiddle.net/mocept/mmx38qxw/6196/)

### Steps to reproduce
直接运行代码即可， 只能对非type的 column进行headerrender

### What is Expected?
希望有type的 column可以正常进行headerrender

### What is actually happening?
希有type的 column不能可常进行headerrender

**Comment by ziyoung** [comment]
render-header 没有被调用，但是 label 属性却可以生效。😅

**Comment by elfman** [comment]
当type为index时，reader-header已经被替换为内置的函数，所有看起来没有被调用，实际已经调用了，只是不是自己定义的那个。

**Comment by MoErm** [comment]
当type为selection时，reader-header也一样没有调用

**Comment by wohui** [comment]
{
                    type: 'index',
                    label: "序号",
                    width:"300",

 },
是不是width 也不生效啊
