### ISSUE TITLE
[Bug Report] Table form filtering drop-down alignment problem

### ISSUE THREAD

**Issue by yangjingjing** [ElemeFE/element#12855]
### Element UI version
2.4.7

### OS/Browsers version
所有

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
table筛选点击下拉

### What is Expected?
应该根据整体左右对齐

### What is actually happening?
现在是根据下拉图标 看着就是视觉bug

**Comment by ziyoung** [comment]
如果对默认的样式不满意，可以通过自定义样式。
