### ISSUE TITLE
[Bug Report] <el-input></el-input> cannot use watch and @input to monitor blank space in real time.

### ISSUE THREAD

**Issue by ovarte** [ElemeFE/element#12850]
### Element UI version
2.4.7

### OS/Browsers version
Chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6204/](https://jsfiddle.net/mmx38qxw/6204/)

### Steps to reproduce
jsfiddle

### What is Expected?
<input v-model='msg' @input="e=> msg = e.target.value.replace(/\s*/g,'')">
可以实现实时去空格
https://jsfiddle.net/mmx38qxw/6206/

### What is actually happening?
 <el-input v-model='msg' @input="e=> msg = e.replace(/\s*/g,'')"></el-input>
组件的行为是，输入空格后 空格不会去除，当再次输入文本的时候，才去除空格
https://jsfiddle.net/mmx38qxw/6204/

**Comment by liangShengSen** [comment]
![image](https://user-images.githubusercontent.com/21200409/55300487-47d63d00-546a-11e9-8783-021545bdd8c6.png)
获取不到导致undefind报错
![image](https://user-images.githubusercontent.com/21200409/55300509-5e7c9400-546a-11e9-8df7-1249af128928.png)

**Comment by sunchanglong** [comment]
this.$nextTick(() => {
          let input = this.getInput();
           input.value = this.value;
         });
这段代码会导致
<el-input type="number" v-model.number="testNum"/> 时 不能输入 小数点后面带0的数值。
比如 1.0 会在输入时丢失 .0 导致无法输入 1.01
https://codepen.io/sunchanglong/pen/wZqVjx

**Comment by guojianlan** [comment]
@sunchanglong 因为1.0 === 1. 所以你输入失败了，感觉这里不应该有number类型

**Comment by gslvly** [comment]
v-model.trim直接失效了，空格不能输入
