### ISSUE TITLE
[Bug Report] EDGE browser, using select component browser, carton, or even collapse.

### ISSUE THREAD

**Issue by SnuggleE** [ElemeFE/element#12856]
### Element UI version
0.1.0

### OS/Browsers version
Windows10 EDGE 42.17134.1.0

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/cd5njLvp/8//](https://jsfiddle.net/cd5njLvp/8/)

### Steps to reproduce
打开官网：http://element-cn.eleme.io/#/zh-CN/component/select
下拉切换select组件，可以稍快速。

### What is Expected?
组件正常使用

### What is actually happening?
浏览器卡顿，自动刷新页面，甚至崩溃

**Comment by SnuggleE** [comment]
Thank you！

**Comment by ziyoung** [comment]
Duplicate of #11629

**Comment by sunset-L** [comment]
+1,element-ui官网都会出现这个问题

**Comment by phpsupai** [comment]
> +1,element-ui官网都会出现这个问题
所以 这个问题有得到解决吗

**Comment by SnuggleE** [comment]
> > +1,element-ui官网都会出现这个问题
> > 所以 这个问题有得到解决吗

use chrome instead.
