### ISSUE TITLE
The [Bug Report] el-input select () event does not work on iOS.

### ISSUE THREAD

**Issue by liuz430524** [ElemeFE/element#12864]
### Element UI version
2.4.7

### OS/Browsers version
iOS 12

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/1497236186/eywraw8t/393392/](https://jsfiddle.net/1497236186/eywraw8t/393392/)

### Steps to reproduce
在iPhone等iOS设备上打开 https://jsfiddle.net/1497236186/eywraw8t/393392/ ，查看文本框中文字是否选中。

### What is Expected?
文本框中的文字正常选中。

### What is actually happening?
文本框中的文字未正常选中。
原因是iOS设备对select()支持有限： https://caniuse.com/#search=select ，使用 https://caniuse.com/#search=setSelectionRange 正常。

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1
