### ISSUE TITLE
[Feature Request] Carousel prohibits loop play.

### ISSUE THREAD

**Issue by SpringHgui** [ElemeFE/element#12869]
### Existing Component
是

### Component Name
Carousel

### Description
增加一个属性，用来控制Carousel，禁止循环播放。

**Comment by ziyoung** [comment]
`autoplay` 属性应该可以满足你的需求吧。http://element-cn.eleme.io/#/zh-CN/component/carousel#carousel-attributes

**Comment by SpringHgui** [comment]
> `autoplay` 属性应该可以满足你的需求吧。http://element-cn.eleme.io/#/zh-CN/component/carousel#carousel-attributes

不是禁用自动播放哦，轮播图点到最后一张时就不能再切换了，现在是会切换到第一张
