### ISSUE TITLE
[Bug Report] vue-cli3.0, webpack4.0 appears after the table table horizontal scroll bar can not display scrolling.

### ISSUE THREAD

**Issue by LuckyTaoTao** [ElemeFE/element#12865]
### Element UI version
2.4.7

### OS/Browsers version
window      

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
vue-cli2.0随着项目越来越大，明显感觉编译速度有点跟不上，于是升级了vue-cli3.0,一开始以为是vue-cli的问题，测试只升级了webpack，但是问题依旧，也就是说element  table对webpack4.x不是特别友好

### What is Expected?
希望能修复

### What is actually happening?
希望能修复

**Comment by Clareyang213** [comment]
遇到同样的问题，希望能尽快修复

**Comment by ziyoung** [comment]
lock 文件也删除了？如果还是存在，那你在  https://codesandbox.io  新建个项目吧。

**Comment by LuckyTaoTao** [comment]
好的

**Comment by LuckyTaoTao** [comment]
[@[](url)](url)
![111](https://user-images.githubusercontent.com/34666627/46185975-e2649080-c30e-11e8-9973-3ba2e7db41a6.gif)
