### ISSUE TITLE
[Bug Report] tree component setCurrentNode behavior not right

### ISSUE THREAD

**Issue by SunGuoQiang123** [ElemeFE/element#12861]
### Element UI version
2.4.7

### OS/Browsers version
macOS/chrome 71.0.3554.0

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/sunguoqiang/ec7xyL0v/5/#&togetherjs=5RHKERsiDu](https://jsfiddle.net/sunguoqiang/ec7xyL0v/5/#&togetherjs=5RHKERsiDu)

### Steps to reproduce
in mounted hook,
1、pass id as a parameter to getNode() method
2、get the node to be highlighted
3、pass the node to setCurrentNode method  but the node not highlighted

### What is Expected?
the node passed to setCurrentNode method highlighted

### What is actually happening?
not the node passed to setCurrentNode method highlighted

**Comment by ziyoung** [comment]
https://jsfiddle.net/ec7xyL0v/9/

**Comment by SunGuoQiang123** [comment]
thx 文档里没有说清楚。。。
