### ISSUE TITLE
[Bug Report] When resizing window size, el-table will trigger "ResizeObserver loop limit" error

### ISSUE THREAD

**Issue by Fundebug** [ElemeFE/element#12866]
### Element UI version
2.4.3

### OS/Browsers version
MacOS High Sierra 10.13.6

### Vue version
2.5.16

### Reproduction Link
[https://github.com/Fundebug/reproduce-ResizeObserver-loop-limit-exceeded](https://github.com/Fundebug/reproduce-ResizeObserver-loop-limit-exceeded)

### Steps to reproduce
1. 安装依赖
    `npm install`
2.  运行
    `npm run dev`
3. 打开浏览器窗口
    http://localhost:8080/#/
4. 缩小窗口大小直到手机号折叠成两行，就会触发

这是我们使用[Fundebug](https://www.fundebug.com/)监控到的报错信息：

![2018-11-07 10 29 42](https://user-images.githubusercontent.com/26496557/48106838-233db680-e278-11e8-95a1-46e7ed06c45c.png)

### What is Expected?
不会报错

### What is actually happening?
报错：ResizeObserver loop limit exceeded http://localhost:8080/#/ 0 0 null

**Comment by Jackliu007888** [comment]
the same

**Comment by qiuyeduxin** [comment]
the same

**Comment by Artorias-ycq** [comment]
the same, and only when i use chrome

**Comment by njueyupeng** [comment]
the same , chrome version  over 68.0

**Comment by swwinone** [comment]
the same,resize table will lead to  the chrome error with chrome version over 68.0

**Comment by wacky6** [comment]
See:

https://github.com/sagemathinc/cocalc/issues/3264#issuecomment-427982137
https://github.com/WICG/ResizeObserver/issues/38

---

In short, ignore this error.

**Comment by liull89** [comment]
现在还是重现

**Comment by nullhan** [comment]
the same

**Comment by njueyupeng** [comment]
【自动回复】您好，我已收到您的邮件。

**Comment by Lana-Lan** [comment]
the same, in case of [v-if element-ui table]

**Comment by njueyupeng** [comment]
【自动回复】您好，我已收到您的邮件。
