### ISSUE TITLE
[Feature Request] Popover set maximum height

### ISSUE THREAD

**Issue by cuicuicuinice** [ElemeFE/element#12868]
### Existing Component
是

### Component Name
Popover

### Description
popover可以设置最大高度吗，超出的部分显示滚动条

**Comment by cuicuicuinice** [comment]
突然发觉  这是一个很蠢的问题!
直接在要展示的元素外套一层容器，设置最大高度，超出显示滚动即可，根本不需要设置popover

**Comment by ziyoung** [comment]
@cuicuicuinice 这样做应该是可行的， issue 先关了。
