### ISSUE TITLE
[Bug Report] Popover with directive

### ISSUE THREAD

**Issue by fakaka** [ElemeFE/element#12870]
### Element UI version
2.4.7

### OS/Browsers version
Windows 10  Chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/vsmj012/b2ye7x5k/](https://jsfiddle.net/vsmj012/b2ye7x5k/)

### Steps to reproduce
1. 设置 popover 为指令
2. 指令的 binding.arg 有大写

```
  <el-popover ref="popOver2" placement="right" title="标题" width="200" trigger="focus" 
      content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
  </el-popover>
  <el-button v-popover:popOver2>hover 激活 2</el-button>
```

### What is Expected?
不显示 popover

### What is actually happening?
显示 popover

**Comment by fakaka** [comment]
在 `packages/popover/src/directive.js` 中 binding.arg 就是小写的 arg。(我猜)可能是 vue 的指令的 binding.arg 参数默认就是小写
``` js
const getReference = (el, binding, vnode) => {
  const _ref = binding.expression ? binding.value : binding.arg;
  const popper = vnode.context.$refs[_ref];
  if (popper) {
    if (Array.isArray(popper)) {
      popper[0].$refs.reference = el;
    } else {
      popper.$refs.reference = el;
    }
  }
};
```

**Comment by ziyoung** [comment]
不算是 Element 的 bug。https://jsfiddle.net/kt69aq30/ arg 会被转成小写字母，使用的时候避免出现这个问题吧。
