### ISSUE TITLE
The [Bug Report] Select selector does not display the drop-down content and the Dialog dialog does not display the mask.

### ISSUE THREAD

**Issue by SpringHgui** [ElemeFE/element#12872]
### Element UI version
2.4.7

### OS/Browsers version
Chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://springhgui.github.io/test.html](https://springhgui.github.io/test.html)

### Steps to reproduce
见链接页面

### What is Expected?
正常显示，兼容页面部分全屏化

### What is actually happening?
不能正常使用控件

**Comment by ziyoung** [comment]
问题确实存在，但是原因未知。

**Comment by SpringHgui** [comment]
显示不出来的元素，他们都不是全屏化的那个根元素的子元素，所以不显示。

**Comment by elfman** [comment]
这页面里是将full内的元素全屏化，mask与dropdown都是append在body的最下面，并没有包含在full内部，所以显示不出来。
最简单的解决办法是将mask或dropdown手动移到full内部
```
this.$nextTick(() => {
  document.querySelector('#full').appendChild(document.querySelector('.v-modal'))
})
```
dropdown同理

**Comment by awebird** [comment]
下面两个属性可以解决
el-dialog :modal-append-to-body="false"
el-select :popper-append-to-body="false"

**Comment by awebird** [comment]
el-cascader能否提供popper-append-to-body参数？ 或者提供更全局的配置，直接append在body下会有类似的问题

**Comment by island205** [comment]
建议直接把 `id="full"` 加到 `body` 元素上。

**Comment by lucasleelz** [comment]
这个不是坑么，怎么就直接关闭了？ 这里的需求很明显是想全屏某个部分啊。

**Comment by JasonLam0990** [comment]
elfman的方法可用，我是在一个子组件使用的Tooltip，并且需要将包含这个子组件的div全屏化。

### 解决方法如下

#### 在需要触发tooltip的地方加一个@mouseover事件，这个事件用emit触发父页面的append方法。

子组件：
```
<el-tooltip class="item" effect="dark" :content="name" placement="top">
  <div class="name" @mouseover="show()">{{ name }}</div>
</el-tooltip>
```
```
show() {
  this.$emit('showTooltip');
},
```

父页面(主要看自定义的方法)
```
<PDFViewer
  control="height"
  :src="currentPdfUrl"
  style="height:75vh;"
  ref="pdf"
  @showTooltip="showTooltip()"
></PDFViewer>
```
#### 这里是要F12查看一下元素，根据自己项目的实际情况来写的。我的项目是全屏化了ref为fullScreen的div，所以我需要append的就是在this.$refs.fullScreen下面。
#### 一定要加setTimeout并延迟100ms执行，否则第一次触发mouseover的时候，document.querySelector('.el-tooltip__popper')还获取不到，用nextTick也是获取不到。结果试了下用setTImeout，延迟100ms就成功了！
```
showTooltip() {
  setTimeout(() => {
    console.log(this.$refs.fullScreen);
    if (document.querySelector('.el-tooltip__popper')) {
      this.$refs.fullScreen.appendChild(document.querySelector('.el-tooltip__popper'));
    }
  }, 100);
}
```

## 感谢elfman！！！

**Comment by tianxiaguixin8** [comment]
很多弹出层都是添加到body上的，可以换一种思路，不直接全屏目标元素，将目标元素position为fixed，top/left设置为0，然后将body全屏

**Comment by taojiujiu1986** [comment]
I got this solution!!! pls Follow this blog, It can resolve your problem！
http://www.gudii.cn/post/22.html
