### ISSUE TITLE
[Bug Report] Cascader cascade selector component drop-down box items do not overflow the screen in very long cases, there is no mouse hover prompt title, drop-down box project text need to add mouse hover prompt title

### ISSUE THREAD

**Issue by aiwosuoaispace** [ElemeFE/element#12883]
### Element UI version
2.4.7

### OS/Browsers version
windows7 64位旗舰版/谷歌浏览器69.0.3497.81（正式版本）（64位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/oca1w8fr/2/](https://jsfiddle.net/oca1w8fr/2/)

### Steps to reproduce
1.将选项参数项各个标签属性值设置为很长的文字; 
2.编译运行; 
3.展开级联选择下拉框; 
4.观察下拉框数据项。

### What is Expected?
选项参数项各个标签属性值设置为很长的文字的情况下，导致屏蔽显示不全文字，希望在每一项中增加鼠标悬浮提示标题，达到显示出级联项中的完整文字效果。

### What is actually happening?
下拉项文字溢出到屏幕外，无法完全显示下拉项文字

**Comment by ziyoung** [comment]
@aiwosuoaispace Select 组件也有一个类似的问题，#9352

对于这类输入的组件，你会发现下拉列表都是都是把所有信息展示出来的。

**Comment by aiwosuoaispace** [comment]
有些业务场景下内容要求填写很多文字，这种情况下会超出屏幕显示不下，所以建议还是增加鼠标悬停提示标题体验比较好
