### ISSUE TITLE
动态tab删除时需要返回index来删除对应数据

### ISSUE THREAD

**Issue by lsbrucelincoln** [ElemeFE/element#1288]
### ElementUI version
1.0.1

### OS/Browers version
Chrome 53

### Vue version
2.0.7

### Reproduction Link

https://jsfiddle.net/hpx4dzud/2/

### What is Expected?
tab-remove事件有一个参数返回被删除tab的index，方便使用splice，2.0不是已经没有$remove了么
### What is actually happening?
现在返回的是tab实例，不知道该如何去删除对应的数据

**Comment by Kingwl** [comment]
[Array.prototype.findIndex](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)

**Comment by lsbrucelincoln** [comment]
现在返回的是被删除的vue实例，这个findIndex有什么用……

**Comment by furybean** [comment]
@lsbrucelincoln  实例其实有 index 属性的，只不过是从 1 开始的。

**Comment by Kingwl** [comment]
https://jsfiddle.net/kingwl/pmqyz9sv/
这样用

**Comment by lsbrucelincoln** [comment]
@Kingwl 原来是用的label这个attribute，没想到，多谢

**Comment by aguu125** [comment]
@Kingwl  这个问题解决了吗，我看了示例 https://jsfiddle.net/kingwl/pmqyz9sv/
里面的this.tabList.splice(index, 0) 并没有删掉数据啊。
改成this.tabList.splice(index, 1),关闭中间的一个tab会出现tab混乱。
