### ISSUE TITLE
[Bug Report] Cascader cascade selector component drop-down box project in a very long case text display is not overflowing screen, no mouse suspension prompt title, drop-down box project text need to add a mouse suspension prompt title

### ISSUE THREAD

**Issue by aiwosuoaispace** [ElemeFE/element#12881]
### Element UI version
2.4.7

### OS/Browsers version
windows7 64位旗舰版 / Google Chrome 69.0.3497.81（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.将options参数项各个label属性值设置为很长的文字；
2.编译运行；
3.展开级联选择下拉框；
4.观察下拉框数据项。

### What is Expected?
options参数项各个label属性值设置为很长的文字的情况下，导致屏蔽显示不全文字，希望在每一项中增加鼠标悬浮提示title,达到显示出级联项中的完整文字效果。

### What is actually happening?
下拉项文字溢出到屏幕外，无法完全显示下拉项文字。

**Comment by ziyoung** [comment]
Duplicate of #12881
