### ISSUE TITLE
When using validation forms, the form is only associated with one element. In el-input, the carriage returns to the page even if there is no binding function.

### ISSUE THREAD

**Issue by mingmLiang** [ElemeFE/element#12897]
### Element UI version
2.4.7

### OS/Browsers version
谷歌浏览器/win10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Lv6rpfqk/11/?utm_source=website&utm_medium=embed&utm_campaign=Lv6rpfqk](https://jsfiddle.net/Lv6rpfqk/11/?utm_source=website&utm_medium=embed&utm_campaign=Lv6rpfqk)

### Steps to reproduce
1.打开重现链接
2.选中选择框，不输入任何信息
3.直接回车
4.发现跳转页面404
5.分析发现只有当表单只有一个元素的时候，才会出现的行为

### What is Expected?
不跳转页面

### What is actually happening?
发现跳转页面

**Comment by wacky6** [comment]
看文档 https://element.eleme.io/#/zh-CN/component/form
