### ISSUE TITLE
[Bug Report] el-button

### ISSUE THREAD

**Issue by Terrijoo** [ElemeFE/element#12894]
### Element UI version
2.4.7

### OS/Browsers version
Chrome v69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Terrijoo/1v89Lk5n/](https://jsfiddle.net/Terrijoo/1v89Lk5n/)

### Steps to reproduce
Press on the Element button, the state doesn't change
Press on the default HTML button, the second state does change

### What is Expected?
The mouse events triggering on the element button like suggested here: https://github.com/ElemeFE/element/issues/10844

### What is actually happening?
The mouse events are not being triggered.

**Comment by wacky6** [comment]
https://jsfiddle.net/kuLx79so/

Element button does not provide `mouse{down,up,leave}` event. Please **READ DOCUMENTATION** carefully, and [**LEARN VUE BASICS**](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components).

**Comment by ziyoung** [comment]
you can use the `.native` modifier. https://jsfiddle.net/1v89Lk5n/12/
