### ISSUE TITLE
Manual upload is invalid when using upload component in [Bug Report] table.

### ISSUE THREAD

**Issue by 982991084** [ElemeFE/element#12893]
### Element UI version
2.4.7

### OS/Browsers version
谷歌最新69

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/982991084/mmx38qxw/6268/](https://jsfiddle.net/982991084/mmx38qxw/6268/)

### Steps to reproduce
手动上传图片，没有报错，但是没有触发上传时间

### What is Expected?
能触发上传事件，自定义的http-request

### What is actually happening?
没有反应

**Comment by ziyoung** [comment]
固定列是通过把 table 复制一份来实现的，Upload 会存在两个，ref 会指向被复制的那份。解决方案 hack，通过 DOM 查询到视图内可见的 Upload 组件，然后手动调用 submit 方法。https://jsfiddle.net/mmx38qxw/6398/

相关的 issue #10588。

或者你不不适用固定列，便不会有这个问题了。
