### ISSUE TITLE
[Bug Report] Clear action is not listening empty value  for rerender header input

### ISSUE THREAD

**Issue by skortabeast** [ElemeFE/element#12909]
### Element UI version
2.4.7

### OS/Browsers version
Версия 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/49z1rjbg/109/](https://jsfiddle.net/49z1rjbg/109/)

### Steps to reproduce
When use clearable attr, clear is working but not listening empty value for updating data

### What is Expected?
When click clearable method  listening it and update data

### What is actually happening?
value is clearing but  no action for @clear attr

**Comment by ziyoung** [comment]
@skortabeast listening clear event? https://jsfiddle.net/49z1rjbg/110/ Does this work for you?

**Comment by skortabeast** [comment]
@ziyoung  it's working for console.log only?:)
How I call custom method ?
From **nativeOn** I can call my method, but if use **on**  get error, see - https://jsfiddle.net/49z1rjbg/111/

**Comment by ziyoung** [comment]
Use arrow function to bind `this` pointer. https://jsfiddle.net/49z1rjbg/112/

**Comment by skortabeast** [comment]
thx
