### ISSUE TITLE
[Bug Report] Use the render-header to customize the header to nest el-popover, but when manually closed, the position of the Popover is fixed at the time of rendering. The scroll bar is pulled and clicked to overflow.

### ISSUE THREAD

**Issue by proceduremonkey** [ElemeFE/element#12907]
### Element UI version
2.4.7

### OS/Browsers version
windows 10 /chrome

### Vue version
2.5.17

### Reproduction Link
[https://github.com/HongjianguoWebDevelopmentGroup/hongjianguo/tree/filter](https://github.com/HongjianguoWebDevelopmentGroup/hongjianguo/tree/filter)

### Steps to reproduce
因为项目组件复用的原因，不好再jsfiddle中写，代码在src=>components=>comom =>AppTable.vue, 项目中专利模块，点击测试按钮，出来表头筛选项，点击之后，在拉动横向滚动条，再点击任何一个表头筛选项，popover这个弹窗就会在原来的位置，并没有监听滚动条的改变，没有在对应列的下面，而是出现偏移

### What is Expected?
希望拉动滚动条也能在对应位置显示

### What is actually happening?
popover这个弹窗就会在原来的位置，并没有监听滚动条的改变，没有在对应列的下面，而是出现偏移

如图：
![image](https://user-images.githubusercontent.com/17590085/46130492-0de26f00-c26c-11e8-84d1-31413925c3cf.png)

**Comment by ziyoung** [comment]
仓库东西太多了，精简代码，在 https://codesandbox.io 新建个项目吧。

**Comment by proceduremonkey** [comment]
具体代码在AppTable.vue 的handleRenderHeader 方法中
![image](https://user-images.githubusercontent.com/17590085/46143103-93c1e280-c28b-11e8-909f-37adc3535211.png)

**Comment by ziyoung** [comment]
你还是提供个重现问题的最小的例子吧，方便我们这边排查问题。

**Comment by proceduremonkey** [comment]
https://jsfiddle.net/svu5d7tn/59/
为什么我在jsfiddle调试了下 是正常的呢 在我的项目中就比较诡异，我项目中的tabel是v-for遍历生成的，和这个有关吗

**Comment by proceduremonkey** [comment]
这个问题是我通过hack处理调用你们的doCloser方法一开始引用的是$refs fixedTableHeader下面的，现在换成TableHeader就解决了,但是我发现你们这个组件还有个bug 就是table中设置了fixed 属性，那就会触发两次实例，重复了一次，当列表字段很多的时候有可能会影响性能上的问题

**Comment by ziyoung** [comment]
怀疑是使用上的问题。
你可以把项目的依赖以及 package-lock 文件删除后，再重新安装依赖。等你找到稳定重现问题的方法，再打开这个 issue 吧。
