### ISSUE TITLE
[Bug Report] source code compilation, the use of NPM install is a problem, the use of yarn is no problem.

### ISSUE THREAD

**Issue by sds0917** [ElemeFE/element#12903]
### Element UI version
2.4.7

### OS/Browsers version
Windows10

### Vue version
2.5.2

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
1、下载releases最新版(2.4.7)源代码，node版本v8.12.0，npm版本6.4.1；
2、使用npm install安装依赖，再执行npm run dist产生的/lib/index.js引入到项目中，tabs组件当前选中的没有那个蓝色的下划线标识；
3、使用yarn安装依赖，再执行npm run dist产生的/lib/index.js引入到项目中，tabs组件当前选中的那个蓝色的下划线标识是正常的；
![qq 20180927114413](https://user-images.githubusercontent.com/7779851/46122356-bed81200-c24a-11e8-84ff-023f2583230b.png)

### What is Expected?
现在不明确npm install的dist出来的产物有问题的原因。

### What is actually happening?
npm install之后dist的产物引入项目，tabs组件当前选中的没有那个蓝色下划线标识。

**Comment by ziyoung** [comment]
应该不是 Element 本身的 bug。如果使用 npm 安装依赖有问题的话，把 node_moudles 文件夹以及 package-lock 文件删除掉，然后再重新安装。
