### ISSUE TITLE
建议增加，能够修改table中的这个el-table__empty-text属性

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#1291]
比如在取数据的时候，会更改为：正在获取数据...

**Comment by furybean** [comment]
:empty-text="myText" 应该是可以的。

**Comment by iou90** [comment]
<span slot="empty">lol</span> works.

**Comment by iou90** [comment]
`<span slot="empty">lol</span>` works.

**Comment by dirunru** [comment]
empty-text="正在获取数据。。。"，但是提示一点这个是data没数据的时候显示的
