### ISSUE TITLE
[Feature Request] Selected and disabled checkbox-button

### ISSUE THREAD

**Issue by sekikatsu36** [ElemeFE/element#12915]
### Existing Component
Yes

### Component Name
Checkbox-button

### Description
A checkbox-button doesn't have a style for selected and disabled. 

When we use a normal checkbox component, we can distinguish a disable one of selected from not selected.
I hope checkbox-button has a style for the state like checkbox.

**Comment by ziyoung** [comment]
> A checkbox-button doesn't have a style for selected and disabled.

The styles of these two buttons are different. You can also use your style to overwrite default style.
![image](https://user-images.githubusercontent.com/12947422/46242785-33ec4880-c3ff-11e8-932d-09be7e53630c.png)
