### ISSUE TITLE
When the [Bug Report] loop lists, the time of the list is bound to DatePicker, and the time is unchanged when the value on the date panel is selected

### ISSUE THREAD

**Issue by babyjin** [ElemeFE/element#12910]
### Element UI version
2.4.7

### OS/Browsers version
 Google Chrome 68.0.3440.106（正式版本）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/687m4Lyd/6/](https://jsfiddle.net/687m4Lyd/6/)

### Steps to reproduce
打开列表中任意一子项的时间控件，在面板上选值

### What is Expected?
点击选中面板上的值时，页面显示的值为选中的值

### What is actually happening?
点击选中面板上的值时，页面显示的值未改变

**Comment by ziyoung** [comment]
[注意事项](https://cn.vuejs.org/v2/guide/list.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
https://jsfiddle.net/687m4Lyd/7/
