### ISSUE TITLE
[Bug Report] dynamic form validation, when the form has default values, validation validation object in the'field Value'can not get real-time form input values, resulting in the failure to validate new input values

### ISSUE THREAD

**Issue by wyz1210355476** [ElemeFE/element#12918]
### Element UI version
2.4.7

### OS/Browsers version
window7/Google Chrome 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
动态表单校验，没有初始值的校验正常，一旦在编辑状态有初始值时，就会导致表单对象中的校验值‘fieldValue‘无法实时获取修改后的值，‘fieldValue‘取到的值还是之前表单的默认值。导致无法验证修改的值。

### What is Expected?
动态表单校验，有默认值时可以实时取到表单里的值

### What is actually happening?
动态表单校验，表单有默认值时，验证时验证对象中的‘fieldValue‘无法实时获取表单输入的值，导致无法验证新输入的值

**Comment by ziyoung** [comment]
如果是 bug，请提供个可重现问题的链接。
