### ISSUE TITLE
[Bug Report] when I use a property array and 'v-for' in 'ElTable' to 'generate' ElColumn dynamiclly, the sequence of the array isn't identical to table head's sequence,the first item of array truns into the last column head of the table,this issue can be found above V1.4.13

### ISSUE THREAD

**Issue by UserNotExist** [ElemeFE/element#12912]
### Element UI version
2.4.7

### OS/Browsers version
windows 10 build 17134 /chrome 69.0

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/eywraw8t/396395/](https://jsfiddle.net/eywraw8t/396395/)

### Steps to reproduce
 when I use a property array and 'v-for' in 'ElTable' to 'generate' ElColumn dynamiclly, the sequence of the array isn't identical to table head's sequence,the first item of array truns into the last column head of the table,this issue can be found above V1.4.13,

<code>I just figure it out !! this issue can be found when I'm using 'v-for' in 'div' then wrap the 'ElColumn ',but it won't happen when I use 'v-for' in 'ElColumn ' directly ,is 'div' change the default behaviour of 'ElTable'?</code>

### What is Expected?
the sequence of the property Array shoudle be identical to the sequence of table column head

### What is actually happening?
the first item of array truns into the last column head of the table

**Comment by ziyoung** [comment]
不要用元素包裹 TableColumn，这将会导致 Table 无法正确计算出它的顺序。具体的代码在这里。
https://github.com/ElemeFE/element/blob/6b76896c409f0b0791467f7297a2d92e184d586c/packages/table/src/table-column.js#L439-L445
