### ISSUE TITLE
[Feature Request] MessageBox validate supports triiger type

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#12923]
### Existing Component
是

### Component Name
MessageBox

### Description
官方示例子 https://jsfiddle.net/gehu6418/

邮箱inputPattern 验证下

在input输入框 第一次输入时就弹出inputErrorMessage了

https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.vue#L26

看起来像是@keydown.enter 验证了，能否做成 trigger blur后再验证

**Comment by ziyoung** [comment]
你好像看错代码了。
https://github.com/ElemeFE/element/blob/b55ea514e2afb26a7a61a35bc2d0f8bc347a19da/packages/message-box/src/main.vue#L42-L47
失焦时触发校验可以加上。不过涉及到更为复杂的功能，还是用 Dialog 包裹 Form 来实现吧。

**Comment by ziyoung** [comment]
尝试在失焦时，触发校验。但这么做总感觉怪怪的。打开弹窗时，输入框是聚焦的。我点击关闭按钮(x) 也出发校验，这样在输入框就会展示校验的信息。
![kapture 2018-09-28 at 19 10 45](https://user-images.githubusercontent.com/12947422/46205274-976c6c80-c352-11e8-945f-443e512dd2ad.gif)
MessageBox 只提供了有限的功能，如果想要复杂的功能，还是用于 Dialog 做吧。

**Comment by ac88** [comment]
了解，目前我采用 更改instance 等一些属性来手动触发instance.validate()
