### ISSUE TITLE
[Bug Report] Deselect sub-item (make it inactive) from menu

### ISSUE THREAD

**Issue by industral** [ElemeFE/element#12925]
### Element UI version
2.4.7

### OS/Browsers version
any

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6399/](https://jsfiddle.net/mmx38qxw/6399/)

### Steps to reproduce
by default selected one sub-menu. When click on any sub-menu - they become active as well. But now, there's no way to deactivate that sub-menu.

Regression issue here: https://github.com/ElemeFE/element/commit/6bb49b959013f3351bee9308b2e627d80d857cfd

### What is Expected?
Code should be fixed (removed this.items[this.activeIndex]) in order to be able to control active sub-menu.

### What is actually happening?
Due to regression in https://github.com/ElemeFE/element/commit/6bb49b959013f3351bee9308b2e627d80d857cfd it's impossible to control active sub-menu now

**Comment by zhangyaoFkr** [comment]
May be you can have a try like this:
Change attribute ```default-active```  to 'placeholder' that produced by an invisible element ```<el-menu-item index="placeholder" v-if="false" />```. It's not a final solution but seems to be 'unselected'.
It works to me.

**Comment by industral** [comment]
@zhangyaoFkr that doesn't work for me at all. Could you please provide a jsfiddle with your working solution, that will be very helpful. Thanks!

**Comment by industral** [comment]
Thanks! Works for me as well. Had to change a lot of code though.
