### ISSUE TITLE
[Bug Report] Destroy  previous rendered el-select element

### ISSUE THREAD

**Issue by skortabeast** [ElemeFE/element#12926]
### Element UI version
2.4.7

### OS/Browsers version
 69.0.3497.100 

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/49z1rjbg/113/](https://jsfiddle.net/49z1rjbg/113/)

### Steps to reproduce
Click button repeatedly, watch Memory Heap

### What is Expected?
previous el-select destroy and memory set free

### What is actually happening?
memory heap increase every time

**Comment by ziyoung** [comment]
@skortabeast set key for each Select component. https://jsfiddle.net/49z1rjbg/114/
