### ISSUE TITLE
Select tag V-model a int type cannot match Option

### ISSUE THREAD

**Issue by panlimin** [ElemeFE/element#12920]
### Element UI version
2.4.7

### OS/Browsers version
Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6363/](https://jsfiddle.net/mmx38qxw/6363/)

### Steps to reproduce
Open the example directly to view
打开例子查看

### What is Expected?
Add a parameter to indicate whether the Select tag allows simultaneous matching of numbers
添加一个参数表示是否在匹配字符串的同时，匹配INT类型

### What is actually happening?
No such function
无此功能

**Comment by panlimin** [comment]
Add a Function parameter to match the Option tag.
Compare(currentValue,OptionValue)=>boolean

**Comment by ziyoung** [comment]
不是 Element 的 bug吧。这种条件你完全可以自行处理。我们暂时没有打算去实现该功能。

**Comment by panlimin** [comment]
已自行处理：
Vue.component('ElSelect').options.methods.getOption = function(value) {
			const isObject = Object.prototype.toString.call(value).toLowerCase() === '[object object]';
			const isNull = Object.prototype.toString.call(value).toLowerCase() === '[object null]';
			for (let i = this.cachedOptions.length - 1; i >= 0; i--) {
				const cachedOption = this.cachedOptions[i];
				const isEqual = isObject
					? getValueByPath(cachedOption.value, this.valueKey) == getValueByPath(value, this.valueKey)
					: cachedOption.value == value;
				if (isEqual && cachedOption) return cachedOption;
			}
			const label = !isObject && !isNull ? value : '';
			let newOption = {
				value: value,
				currentLabel: label,
			};
			if (this.multiple) {
				newOption.hitState = false;
			}
			return newOption;
		};
