### ISSUE TITLE
el-card中文乱码

### ISSUE THREAD

**Issue by lyg1949** [ElemeFE/element#1292]
在1.0.2中，el-card中的中文会变成乱码，el-menu及其他组件不会这样。

**Comment by furybean** [comment]
请提供一个例子。

**Comment by lyg1949** [comment]
我把代码放到jsfiddle上是正常的，但是在我自己的浏览器上就不正常
![default](https://cloud.githubusercontent.com/assets/6082887/20551115/6852960c-b177-11e6-81fc-aad74fd7e29e.PNG)

我的浏览器版本是google chrome v54，系统是win10

**Comment by furybean** [comment]
@lyg1949 执行一下 webpack 打包一下，看看是否源代码里面就已经乱码了。

**Comment by lyg1949** [comment]
@furybean 没错，打包的源代码里面就是乱码!

**Comment by furybean** [comment]
@lyg1949 那就和 Element 没关系了，应该是 webpack 相关的 Bug。
