### ISSUE TITLE
[Feature Request] Solves the problem of native horizontal scrollbars in chrome and Firefox when using Scrollbar components

### ISSUE THREAD

**Issue by nailao** [ElemeFE/element#12927]
### Existing Component
是

### Component Name
Scrollbar

### Description
\element-ui\packages\scrollbar\src\main.js
```
const gutterStyle = `margin-bottom: ${gutterWith}; margin-right: ${gutterWith}; padding-bottom: ${gutter}px;`;
```
加个padding-bottom，这样就可以解决在chrome和Firefox还是会显示横向滚动条的问题，另外在样式上再加上
```
.el-scrollbar__wrap::-webkit-scrollbar {
    display: none;
}
```
这个能修复在chrome浏览器使用padding-bottom而出现的多余高度

**Comment by ziyoung** [comment]
提 pr 吧。😀
在 pr 中告诉你修复的是什么问题。issue 不是用来处理这个的。
