### ISSUE TITLE
tree树结构目录过长拖动时如何显示全名

### ISSUE THREAD

**Issue by ahuang** [ElemeFE/element#12931]
![image](https://user-images.githubusercontent.com/730550/46240236-e0fe9b00-c3d6-11e8-95db-7af802a8335d.png)

默认静止时也是被隐藏，覆盖了样式之后，可以实现静止时显示全名
.split{
  overflow: visible;
}
.el-tree-node>.el-tree-node__children{
  overflow: visible;
}

现在的问题是，拖动时，过长的目录依然被隐藏，有没有什么办法，可以在拖动时也显示全名呢？

**Comment by klren0312** [comment]
这样比较好
```
.el-tree-node__content {
  height: 100%;
  word-break: break-all;
}
```
