### ISSUE TITLE
[Bug Report] Button group style is not beautiful

### ISSUE THREAD

**Issue by fakaka** [ElemeFE/element#12933]
### Element UI version
2.4.7

### OS/Browsers version
windows10/chrome62

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/vsmj012/y3tzjm7n/1/#update](https://jsfiddle.net/vsmj012/y3tzjm7n/1/#update)

### Steps to reproduce
1. 使用按钮组
2. 一个按钮有图标，一个按钮没有

1. use el-button-group 
2. one button with icon,other 

### What is Expected?
高度一样

### What is actually happening?
高度不一致

**Comment by ziyoung** [comment]
高度不一样？
![image](https://user-images.githubusercontent.com/12947422/46241441-a43d9e80-c3ec-11e8-8e24-b885e9a35594.png)

**Comment by fakaka** [comment]
@ziyoung 我看到的是这样的额，可能是这个浏览器的原因？

![360 20180929134915887](https://user-images.githubusercontent.com/12379312/46241577-7eb19480-c3ee-11e8-8953-4afac4b75ea8.jpg)

**Comment by fakaka** [comment]
最新版 chrome 好像也有点问题
![image](https://user-images.githubusercontent.com/12379312/46241750-c802e380-c3f0-11e8-9e6b-c0ccf42c36cc.png)

**Comment by ziyoung** [comment]
你把内容全换成英文试试？怀疑是跟中文字体有关系。

**Comment by ziyoung** [comment]
难道系统有关系？要不然你尝试修复一下？

**Comment by fakaka** [comment]
你可以试试浏览器缩放，不同比例可能会出现这个情况

**Comment by Adityaperiwal** [comment]
Is it solved?

**Comment by fakaka** [comment]
no

**Comment by csvwolf** [comment]
![image](https://user-images.githubusercontent.com/8280645/48038837-5bc48e00-e1ad-11e8-83ba-38a9ade7f020.png)
@ziyoung Reproduce in Firefox in Mac & only in 100% scale...Emmmm, 1 px.

**Comment by shady-xia** [comment]
我估计你的windows是125%的布局，如果你尝试缩放的话，应该不会有这个问题
其实是缩放时`i`标签略微地影响了`button`内部的高度，你可以给`i`标签加个`vertical-align:bottom`，这个问题就解决了。
