### ISSUE TITLE
The URL field in [Feature Request] 2.4.7 Version (file object in file: fileList) is missing.

### ISSUE THREAD

**Issue by chen-zzz** [ElemeFE/element#12934]
### Existing Component
是

### Component Name
Upload

### Description
2.4.7版本中（ file: fileList 中的 file 对象 ）的url字段不见了，之前一直基于url这个字段写的逻辑，2.4.6版本回调中还有，更新后就消失了，更新日志里面也没有任何体现！！！

**Comment by ziyoung** [comment]
应该是这个 pr #12402。
当 type 不为照片墙时，没有必要生成预览图片。
对于暴露出的方法，我们不会轻易修改。这个属性，我们未在文档中有描述，所以 changelog 里也不会出现。

**Comment by z1948296027** [comment]
文档中没有写你就说删就删掉，线上出bug了，愤怒

**Comment by svenjia** [comment]
> 应该是这个 pr #12402。
> 当 type 不为照片墙时，没有必要生成预览图片。
> 对于暴露出的方法，我们不会轻易修改。这个属性，我们未在文档中有描述，所以 changelog 里也不会出现。

现在场景是这样的，在我的项目中（element-ui 版本2.3.9），在on-change钩子里面使用file.url，
![image](https://user-images.githubusercontent.com/29444841/50586719-be888c00-0eb5-11e9-9fac-ca73cbf68594.png)
，这里我是需要手动实现一个预览功能，因为上传功能是在一个dialog里面，获取到文件后，dialog就消失，element自带的预览这里就不适用了。
这里的list-type默认是text，但是当我升级element版本后，list-type还是text，然后却没有url字段了，所以就出bug了，我觉得没有必要判断list-type类型，这样也不会出现这样的问题了，这样的变化，也应该在release log里面体现吧，我估计还有部分用户也会遇到这个问题。

**Comment by svenjia** [comment]
> 文档中没有写你就说删就删掉，线上出bug了，愤怒

我也遇到这个问题了
