### ISSUE TITLE
tree 1，2级有数据， 动态获取第3级数据，但视图不更新

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1293]
`<el-tree :data="data" :props="defaultProps" @node-click="handleNodeClick"></el-tree>`

请问，data中，第1级和2级已经有数据，3级数据是动态从后端获取，
拿到后，在data的2级中加入数据，但是视图并没渲染出第三级的数据

请问有什么方法可以重新渲染吗？？？

**Comment by furybean** [comment]
#1283 应该修了这个问题。1.0.2 版本确实存在添加了子节点之后，左侧展开图标也无法显示的 Bug。

**Comment by ivan403704409** [comment]
@furybean
好的，thx!
能否加个选中高亮的功能？

**Comment by furybean** [comment]
@ivan403704409 可以看看 highlight-current 属性能不能满足你的需求。

**Comment by ivan403704409** [comment]
@furybean 满足，没看清楚文档，不好意思~~
