### ISSUE TITLE
[Feature Request] dialog closes the corresponding v-modal mask layer.

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#12935]
### Existing Component
是

### Component Name
dialog

### Description
如果打开多个dialog (我们的项目是由多个选项卡组成的后台，并不是单纯的单页面应用，所以dialog被包含在选项卡内，通过修改dialog的position为绝对定位，实现在选项卡内部)，当打开一个并未关闭，这时再从某个选项卡内再次打开一个新的dialog，就会将其他的v-modal关闭，我想请求一个新特性，就是关闭dialog可以关闭对应的v-modal遮罩层，而不影响其他的v-modal

**Comment by ziyoung** [comment]
即便是你打开多个 Dialog，遮罩层只会有一个。这个功能暂时没法实现。

**Comment by LemonAppleMo** [comment]
好的  谢谢
