### ISSUE TITLE
[Bug Report] Form element initial values are dynamically assigned, and all values are emptied when the form is reset

### ISSUE THREAD

**Issue by zbjy** [ElemeFE/element#12945]
### Element UI version
2.4.7

### OS/Browsers version
win7/Chrome 版本 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/a3hygzn0/2/](https://jsfiddle.net/a3hygzn0/2/)

### Steps to reproduce
在mounted方法里初始化表单值， 什么都不操作，直接调用重置表单的方法，会把值都清空

### What is Expected?
重置的时候不清空动态赋值的元素，保留初始值

### What is actually happening?
重置的时候不清空动态赋值的元素，保留初始值

**Comment by ziyoung** [comment]
在 mounted 的时候，给表单赋值。这时候 Form 组件已经创建了，接收的初始值是空，所以才这样。你可是把 mounted 改为 created https://jsfiddle.net/a3hygzn0/3/
