### ISSUE TITLE
无法自定义主题

### ISSUE THREAD

**Issue by xiaofeiapis** [ElemeFE/element#1294]
npm i element-theme -D  全局安装的话，之后在et编译的时候报错，找不到popup.css；
安装在项目里面的话，之后et -i， 即使在node_modules/.bin ,也一直提示element-theme-default没有安装

**Comment by 598220654** [comment]
楼主解决了吗,为什么我跟着文档node_modules/.bin/et -i  ,去到这里,他说:'node_modules' 不是内部或外部命令，也不是可运行的程序或批处理文件。我应该从哪里执行命令

**Comment by QingWei-Li** [comment]
请贴错误信息

@598220654 是让你直接运行 `node_modules/.bin/et -i`，如果有错误请同样贴错误信息

**Comment by reverland** [comment]
theme-defaut依赖vue-popup

**Comment by 598220654** [comment]
@reverland 怎么依赖     throw er; // Unhandled 'error' event
      ^
 Error: ENOENT: no such file or directory, open 'C:\Users\puban\Desktop\vue2.0\my-vue\node_modules\element-theme-default\src\vue-popup\lib\popup.css'
    at Error (native)
报了这个错误

**Comment by QingWei-Li** [comment]
如果不熟悉 npm 机制的话，推荐用全局安装的方式
```shell
npm element-theme -g
```

**Comment by callmewhy** [comment]
➜  fe-main git:(develop) ✗ et

✔ build theme font
⠏ build element theme

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/Users/why/workspace/advance.ai/fe-main/node_modules/element-theme-default/src/vue-popup/lib/popup.css'
    at Error (native)

**Comment by Leopoldthecoder** [comment]
@callmewhy 参照 #1443
