### ISSUE TITLE
[Feature Request] how to dynamically add <image> or <i>before tab label in el-tabs nav item

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/element#12946]
### Existing Component
Yes

### Component Name
el-tab

### Description
hope to add image before label
like :
![image](https://user-images.githubusercontent.com/8478315/46253489-90a73c00-c4af-11e8-80a3-2d5ac3871b43.png)
I hope  I can add image before each label,  depend on my route data, like:
`[
{
    path: '/',
    name: 'tab1',
    icon: 'icon1'
},
{
    path: '/tab2',
    name: 'tab2',
    icon: 'icon2 or img link'
 }
]`

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this. You can use label slot.
