### ISSUE TITLE
[Bug Report] Upload is not work in chrome 69.0.3497.100 (official version) (64 bits)

### ISSUE THREAD

**Issue by appleCXT** [ElemeFE/element#12940]
### Element UI version
2.4.7

### OS/Browsers version
chrome 69.0.3497.100（正式版本）（64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.click the button upload then choose a file, then the problem comes. 

### What is Expected?
when use the Upload component it can work normally and chrome will not throw error or not work.

### What is actually happening?
You can test the Upload component in the http://element-cn.eleme.io/#/zh-CN/component/installation, chrome will stop working and throw out error.

**Comment by ziyoung** [comment]
请提供正确的链接。

**Comment by ziyoung** [comment]
> > 请提供正确的链接。
> 
> https://jsfiddle.net/a3hygzn0/5/

链接不正确把。打开怎么是这样的？
![image](https://user-images.githubusercontent.com/12947422/46255365-c576bb80-c4ce-11e8-9b8c-8c520b8919ea.png)

**Comment by zbjy** [comment]
> Translation of this issue:
> 
> Element UI version
> 2.4.7
> 
> OS/Browsers version
> Chrome 69.0.3497.100 (official version) (64 bits)
> 
> Vue version
> 2.5.17
> 
> Reproduction Link
> https://jsfiddle.net/api/post/library/pure/
> 
> Steps to reproduce
> 1.click the button upload then choose a file, then the problem the
> 
> What is Expected?
> When use the Upload component it can work normally and chrome and
> 
> What is actually happening?
> You can test the Upload component in the http://element-cn.eleme.io/#/zh-CN/component/installation, chrome will stop working and throw out error.



> > > 请提供正确的链接。
> > 
> > 
> > https://jsfiddle.net/a3hygzn0/5/
> 
> 链接不正确把。打开怎么是这样的？
> ![image](https://user-images.githubusercontent.com/12947422/46255365-c576bb80-c4ce-11e8-9b8c-8c520b8919ea.png)

是这样的，我的问题是我在mounted给表单赋初始值，然后直接点击重置按钮，会把我刚赋值的数据清空，正常是应该恢复到我赋的初始值吧，而不是清空掉数据
![image](https://user-images.githubusercontent.com/19985529/46255410-11c1fb80-c4cf-11e8-905b-933baa04e6ab.png)

**Comment by wacky6** [comment]
Element的重置按钮本来就是清空所有值。要恢复初始值的话，自己写函数处理。

**Comment by ziyoung** [comment]
@zbjy https://github.com/ElemeFE/element/issues/12945#issuecomment-425699787

**Comment by zbjy** [comment]
> @zbjy [#12945 (comment)](https://github.com/ElemeFE/element/issues/12945#issuecomment-425699787)
如果是直接赋值的是没问题，但是数据如果是通过异步获取的话，就会有问题，因为会有时间差，此时你所说的Form 组件已经创建了，那这种情况是不是就没办法解决了，只能通过写函数处理了呢
https://jsfiddle.net/a3hygzn0/9/

**Comment by clydeqin7** [comment]
我在chrome 69.0.3497.100（正式版本）（64 位）使用upload组件也出现了同样的问题： 
    点击上传文件button再关闭后，chrome就出现未响应（今天早晨2018-10-11 9:30以前，刚开电脑测试就一直出现未响应，但现在测试又正常工作了-。-！） 
链接：
https://jsfiddle.net/b1nm2v5e/ (这链接就是element的upload示例另存的)

**Comment by ziyoung** [comment]
@clydeqin7 如果依旧存在问题的话，能否稳定重现？
