### ISSUE TITLE
[Bug Report] Tooltip doesn't work in full screen

### ISSUE THREAD

**Issue by goforward01** [ElemeFE/element#12947]
### Element UI version
2.4.7

### OS/Browsers version
Chrome/Firefox

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/goforward01/6qeLc4ns/8/](https://jsfiddle.net/goforward01/6qeLc4ns/8/)

### Steps to reproduce
click the button of fullscreen

### What is Expected?
show the tooltip while hover on the button

### What is actually happening?
show nothing while hover

**Comment by ziyoung** [comment]
跟 issue #12947 差不多。两个都算是属于同一类问题。

**Comment by taojiujiu1986** [comment]
I got this solution!!! pls Follow this blog, It can resolve your problem！
http://www.gudii.cn/post/22.html
