### ISSUE TITLE
[Bug Report] When the Input type = "number" is input in Chinese, the cursor will be positioned upwards.

### ISSUE THREAD

**Issue by x710894881** [ElemeFE/element#12942]
### Element UI version
2.4.7

### OS/Browsers version
mac/chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/3w4aqx2o/](https://jsfiddle.net/3w4aqx2o/)

### Steps to reproduce
When the Input type = "number" is input in Chinese, the cursor will be positioned upwards.

### What is Expected?
the cursor will be positioned center.

### What is actually happening?
the cursor will be positioned upwards.

**Comment by ziyoung** [comment]
@x710894881 Maybe it's a bug of the web browser. https://jsfiddle.net/3w4aqx2o/1/

**Comment by csvwolf** [comment]
@ziyoung It the matter of `line-height`: https://stackoverflow.com/questions/15603197/how-to-solve-buggy-line-height-on-input-fields

**Comment by csvwolf** [comment]
The fix plan will import lots of breaking changes, maybe we can solve it in Element 3.0 later.
