### ISSUE TITLE
[Feature Request] How to break range date picker into two lines ?

### ISSUE THREAD

**Issue by odhikari** [ElemeFE/element#12943]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
I am using your range date picker, currently I am able to show date range in one line like 2018-05-10 TO 2018-09-12 but I want them in two different lines . Like start date and end date with different line.
Thanks

**Comment by ziyoung** [comment]
Maybe you can use two Datepicker components.
 For range date picker, we have no plan to support this feature.
