### ISSUE TITLE
[Table]selection列使用toggleRowSelection表头的checkbox不能选中

### ISSUE THREAD

**Issue by chenkby** [ElemeFE/element#1295]
eui ver:1.0.1

需求是这样的，我在table底部加了个工具条，里面也有个checkbox，他的功能跟table中的全选(checkbox)是一样的。我希望表头的checkbox跟工具栏checkbox的选中/未选中状态是一致的。比如我点了上面的，中间的数据行会选中，工具栏checkbox也能选中。假如手动勾选中间的数据行，如果全部数据行都选中的话上面跟工具条的也会选中(这个好像你们自己实现了，在点击的情况下)。

上面的功能已经被我解决掉了。现在就是遇到一个问题，当我选中工具条的checkbox时，我能把数据行的所有数据选中，但是，表头中checkbox没有选中。

看简略代码,工具栏被我写成了一个组件：

```
工具栏的checkbox

<el-checkbox  v-model="checked" @change='checkboxChange'></el-checkbox>

method:

    checkboxChange (event) {
      // vm：工具栏组件 grid:表格引用
      var vm = this
      this.grid.tableData.forEach(function (row) {
        vm.grid.toggleRowSelection(row, vm.checked)
      })
    }
```

我是通过toggleRowSelection来让所有数据行选中的，但是即使全部选中，表头的checkbox也不会选中，可如果我是手动点击把数据行都选中的话，表头的checkbox就会选中。。。这里，感觉逻辑有点奇怪，按理表头的checkbox是否选中应该是看当前页的数据行是否全选的，但是手动选中跟用toggleRowSelection选中的结果却不一样。

当前版本下，有什么方式可以控制表头的checkbox，或者通过什么方式能达到我所述需求？

另外我觉得，如果table能够暴露全选/取消全选的方法会更方便些。

**Comment by furybean** [comment]
确实存在，可以看一下 Demo 是不是这个意思：http://jsfiddle.net/647r4xx5/

**Comment by chenkby** [comment]
嗯，在提交这个issue前，我已经看过这个demo，就是这个意思。demo中单击select all按钮，数据行全选，但是表头的未改变状态

**Comment by chenkby** [comment]
还有一个bug.就是用toggleRowSelection方法后，table的selection属性没有变化，还是undefined。但手动点击或者点击表头的全选，table的selection是不同的。

**Comment by furybean** [comment]
@chenkby  table 的 selection 属性？不应该存在这个一个属性吧，我看看文档。

**Comment by chenkby** [comment]
文档上没有写，不过能读到

**Comment by Kingwl** [comment]
那你也敢用2333

**Comment by furybean** [comment]
@chenkby 你应该使用 selection-change，如果这个事件能触发，就是正常的，否则就是 bug。

**Comment by chenkby** [comment]
@furybean 使用toggleRowSelection方法后，table的selection-change没有触发。“只有当我点击任一数据行，或者点击表头的全选”后才会触发。

我看文档上对"selection-change"的说明是"当选择项发生变化时会触发该事件".按理用toggleRowSelection后选择项也是发生了变化才对。

**Comment by furybean** [comment]
@chenby 看起来 #1198 修了这个问题。

**Comment by furybean** [comment]
#1300 修了这个问题，下个版本会包含该修复。
