### ISSUE TITLE
[Feature Request]: highlight submenu when is active

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#12951]
### Existing Component
Yes

### Component Name
Menu

### Description
When the menu-item below submenu is selected, it is recommended to highlight submenu.

![11](https://user-images.githubusercontent.com/8121621/46255383-e808d480-c4ce-11e8-888b-e808090a7428.jpg)
![22](https://user-images.githubusercontent.com/8121621/46255386-ec34f200-c4ce-11e8-920a-48170505221e.jpg)

https://github.com/PanJiaChen/vue-element-admin/pull/1154

Since this involves `UI` style problem, it is not good to make pr. I hope the official optimizes it.

**Comment by PanJiaChen** [comment]
ping...ping...ping...

**Comment by tang9716** [comment]
...

**Comment by siyuan5616** [comment]
大神之路

**Comment by ResyLG** [comment]
Who can give me another kind of combination of colors that looks beautiful (sidebar)?Appreciate it!

**Comment by 1Dumbo** [comment]
侧边栏修改样式的时候会有一些意向不到的问题
