### ISSUE TITLE
[Feature Request] Make autocomplete selection tab-able

### ISSUE THREAD

**Issue by bernerha** [ElemeFE/element#12955]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
It would be nice if the user could use tab with the excisting enter key handler to select an active element to get it from the list to the input.
Because a poweruser is used to use tab for completion and jumping forward to the next field. The enter key breaks the flow.

**Comment by xi-osman** [comment]
Agree this is important for quick data entry.

**Comment by Trosky** [comment]
It's really anoying that you can't choose the key handler.

**Comment by xi-osman** [comment]
Having this on el-select would be awesome.

**Comment by ziyoung** [comment]
Autocomplete is an input element like native input. It's focusable and you can press the tab key to focus it. I know the programmers usually use tab completion to type commands faster. But for other users of a website, they don't know tab completion.

**Comment by bernerha** [comment]
Maybe we are talking about different behaviours.
I made a short video to show my desired behaviour.
If someone selects the suggestions from google with the curser and then presses tab, the selected element gets set on the input field.

https://giphy.com/gifs/1BbZUAice3SG9FGKc6
