### ISSUE TITLE
[Table]给一个column绑定的width进行修改报错

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1296]
需求：自定义某列表格的宽度 动态设置表格列width变化
结果：报错
![image](https://cloud.githubusercontent.com/assets/1932350/20552812/8c1673c6-b189-11e6-8113-cf50b5023392.png)
demp:
https://jsfiddle.net/yelingfeng/3uhow6h6/

**Comment by ZhaoWJ1994** [comment]
如果width能支持百分比就最好不过了。

**Comment by furybean** [comment]
@ZhaoWJ1994 可以试试 min-width，在绝大部分场景下可以替代百分比的作用。

**Comment by ZhaoWJ1994** [comment]
@furybean 感谢大神，一开始没注意这个属性。赞！
