### ISSUE TITLE
[Feature Request] Select: Make using filter method easier

### ISSUE THREAD

**Issue by dodas** [ElemeFE/element#12960]
### Existing Component
Yes

### Component Name
Select

### Description
Currently, it is possible to use `filter-method` property of Select to customize filter behaviour. However, this method is only called with current filter value and remaining implementation of behaviour is up to programmer.

In most cases, programmer just wants to customize comparing logic and let `element-ui` handle the rest: hiding options.

It would be nice if I could just get both current filter value and all select options, and then return filtered options.

We could do this:
```html
<template>
  <el-select v-model="selectedValue" filterable :filter-method="filterOptions">
    <el-option v-for="option in options" :key="option" :label="option" />
  </el-select>
</template>

<script>
export default {
  data() {
    return {
      selectedValue: "apple"
      options: ["apple", "orange", "banana"],
    }
  },
  methods: {
    filterOptions(filterValue, allOptions) {
      return allOptions.filter(option => option.includes(filterValue))
    }
  }
}
</script>
```

Instead of this:
```html
<template>
  <el-select v-model="selectedValue" filterable :filter-method="filterOptions">
    <el-option v-for="option in filteredOptions" :key="option" :label="option" />
  </el-select>
</template>

<script>
export default {
  data() {
    return {
      selectedValue: "apple"
      allOptions: ["apple", "orange", "banana"],
      filteredOptions: []
    }
  },
  watch: {
    allOptions: {
      handler(newAllOptions) {
        this.filteredOptions = [...newAllOptions]
      },
      immediate: true
    }
  },
  methods: {
    filterOptions(filterValue) {
      this.filteredOptions = this.allOptions.filter(
        option => option.includes(filterValue)
      )
    }
  }
}
</script>
```
In second example, we must store filtered options on our vue instance, then we need to watch `allOptions` for changes and reset `filteredOptions` (and this isn't even correct – we should reset and filter it, but that way we would also need to store current filter value on our instance, which isn't possible, as there isn't event for filter change).

It seems like a lot of logic needs to be implemented in userland, when all programmer needs is changing logic from case-insensitive to case-sensitive matching, for example.

What do you think?
I think I can send an PR, if we agree on an implementation.

Cheers.

**Comment by wacky6** [comment]
I agree that current `filter-method` design is flawed. This modification can be 3.0 candidate (because it is a breaking change).

The word "filter" hints that `filter-method` should behave similarly to `Array.filter`. `filterMethod(option, filterValue) => true / false` sounds reasonable.

Before putting your effort into making a PR, you should wait for other maintainers' approval.

CC @ziyoung @jikkai

**Comment by dodas** [comment]
I just thought returning whole filtered array, instead of true/false for each option would allow for a slightly greater flexibility, but either is sufficient I guess.

Btw, is there any 3.0 roadmap?

Thanks.

**Comment by JPustkuchen** [comment]
I guess this should be reopened, it still makes sense what was suggested?

**Comment by aless673** [comment]
Yes, re-open it

**Comment by mr-magnus** [comment]
Please reopen and implement the suggestion! :)

**Comment by Anton-Zelenkov** [comment]
Please reopen it. It will be very usefull and appropriate for developer experience

**Comment by cacious7** [comment]
We really need this please reopen this issue. The current implementation is really annoying to work with if you have a complex UI structure
