### ISSUE TITLE
[Feature Request] Add component Skeleton

### ISSUE THREAD

**Issue by ankology** [ElemeFE/element#12968]
### Existing Component
No

### Component Name
Skeleton

### Description
Something like https://ant.design/components/skeleton/

**Comment by ArtemSyzonenko** [comment]
Some good examples for inspiration:

https://polaris.shopify.com/components/feedback-indicators/skeleton-display-text#navigation

https://blueprintjs.com/docs/#core/components/skeleton

https://developer.microsoft.com/en-us/fabric#/controls/web/shimmer
