### ISSUE TITLE
[select]在多选时，自己操控选中项出现多次添加问题

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#1297]
### ElementUI version
1.0.2

### OS/Browers version
win10/Chrome 53

### Vue version
2.0.8

### Reproduction Link
http://runjs.cn/detail/aysaxk5j

### Steps to reproduce
我输入1，然后回车选中了1。再输入2，回车，选中标签变成了2,1,2.这时再输入3回车就控制台就报错了
![image](https://cloud.githubusercontent.com/assets/9530813/20552906/76ab15f4-b18a-11e6-8af9-8ee2c54cf3e0.png)

**Comment by erguotou520** [comment]
http://jsfiddle.net/s7jnqpz4/

**Comment by Leopoldthecoder** [comment]
在 Gitter 里看到了你的需求，研究了一下你的 demo。简单来说，这个需求已经和 Select 的交互有比较大的差别了，不建议在 Select 的基础上 hack。

首先，hack 需要用到不少 Select 内部的属性和方法，这些在未来是很有可能发生变化的。其次，demo 报错的原因是，Select 自身也监听了键盘回车事件，它和你的回调产生了一些冲突的地方。建议自行解决这个需求。
