### ISSUE TITLE
ScopedSlots default render is inaccurate when [Bug Report] table header changes order dynamically.

### ISSUE THREAD

**Issue by laucher** [ElemeFE/element#12975]
### Element UI version
2.4.8

### OS/Browsers version
chrome 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/laucher/mmx38qxw/6458/](https://jsfiddle.net/laucher/mmx38qxw/6458/)

### Steps to reproduce
1. 初始化设置table的data值为[{name:"test1",zip:"10086"}]。
2. 初始化header值是空数组，该数组用于动态生成elTableColumn组件，初始化一个按钮，用于对header进行reverse操作。
3. 设置elTableColumn中scopedSlots的default为header数组中的每个元素的renderCell属性值，该值返回一个vnode。
4. mounted钩子函数中异步调用重置header为含有2个元素的数组，其中1个renderCell返回为按钮的vnode，另外1个renderCell返回为普通文本的vnode。
5. 第一次渲染的时候是正常渲染，点击按钮对header进行reverse时，则发现渲染错误，renderCell都渲染成为普通文本，按钮的vnode不见了。
6. 再次点击按钮，都渲染成为按钮的vnode。

### What is Expected?
期待el-table-column中能按照动态传递传递的scopedSlots的渲染函数渲染。

### What is actually happening?
el-table-column中scopedSlots渲染函数错误。

**Comment by ziyoung** [comment]
再次点击按钮后，renderCell 函数会已经调用了。暂时不知道是哪里的问题。

**Comment by laucher** [comment]
在这个情况下，实际上renderCell 函数的调用要比预计的调用次数多，经过排查是table-body的的render函数频繁执行。我也不知道为什么会这样。。。。一直很纳闷。

**Comment by ziyoung** [comment]
每次改变表头，都让 table 重新渲染吧，暂时先这么做😅。https://jsfiddle.net/mmx38qxw/6549/
目前，还在排查原因中。

**Comment by laucher** [comment]
> 每次改变表头，都让 table 重新渲染吧，暂时先这么做。https://jsfiddle.net/mmx38qxw/6549/
> 目前，还在排查原因中。

好的 暂时只能先这样了。

**Comment by ziyoung** [comment]
当数据改变时，`table-body` 的 render  执行了两次。这里是有点问题。
另外，当 render-cell 函数中的给 VNode 设置 key，也是不能解决问题。

**Comment by superchangme** [comment]
> 当数据改变时，`table-body` 的 render 执行了两次。这里是有点问题。
> 另外，当 render-cell 函数中的给 VNode 设置 key，也是不行。

请问你解决了重复渲染的问题了吗，我这边也遇到了

**Comment by xuxuanwei** [comment]
我也有这个问题
