### ISSUE TITLE
[Feature Request] Any way to access programmatically last z-index computed by element-ui?

### ISSUE THREAD

**Issue by ankology** [ElemeFE/element#12971]
### Existing Component
Yes

### Component Name
Any

### Description
I'm building custom components where himself use element-ui components internally, to solve z-index issues i need to know the last z-index computed by element-ui to increase in my custom context. I have searched in source of the project and i found a method in (element/src/utils/popup/popup-manager.js) called PopupManager.nextZIndex(), this is the correct way to found it? Thanks for help =)

**Comment by ziyoung** [comment]
@ankology Maybe you don't need to get zIndex. Just call `nextZIndex` and use the return value to set zIndex.
