### ISSUE TITLE
[Bug Report] el-select inside el-table will not work if one column has fixed attribute.

### ISSUE THREAD

**Issue by xi-osman** [ElemeFE/element#12970]
### Element UI version
2.4.8

### OS/Browsers version
Windows 10/ Chrome 69.0.3497.100 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xiosman/0274p9d8/23/](https://jsfiddle.net/xiosman/0274p9d8/23/)

### Steps to reproduce
In 'works card' if you go to the Operations column and click on the row edit button, the row will focus on the el-select. Same thing will happen on 'Does not work' but once you click on the Delete button then click on the row edit button the functionality for focus will not work. 

### What is Expected?
Even if I trigger the delete I should be able to Focus or Blur any ref input / select with a Fixed column.

### What is actually happening?
Once I trigger the delete button and there is a fixed column in my table, Im no longer able to Focus or Blur a ref el-element.

**Comment by ziyoung** [comment]
The fixed column is achieved by clone another table. So sometimes, `ref` doesn't work.

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/10588#issuecomment-379460140
