### ISSUE TITLE
[Feature Request] recommends: popper.js use the new version of export default Popper

### ISSUE THREAD

**Issue by ayiaq1** [ElemeFE/element#12979]
### Existing Component
是

### Component Name
popper

### Description
扩展功能的时候涉及到到组件打包，popper在window下会默认为request导致扩展组件打包会报警告引起部分代码打包失败，
我执行修改popper为export default popper;方式打包成功，一下为代码段：
`function popper() {

    'use strict';

    var root = window;
     ........
     ......

     return Popper;
};

var popper = popper();

export default popper;`

**Comment by ziyoung** [comment]
这里的 popper.js 是 ElementUI 内部使用的。我们已经对 popper.js 做出了许多的修改。不建议你在项目中直接使用。
如果你要使用的话，可以直接把 popper.js 添加为项目的依赖。
