### ISSUE TITLE
When [Feature Request] DateTimePicker is used, you can't select only one.

### ISSUE THREAD

**Issue by jianghuzai** [ElemeFE/element#12978]
### Existing Component
是

### Component Name
DateTimePicker 

### Description
作为数据筛选条件时，可能会对某个时间字段例如“createTime”进行筛选，对于范围选择时，如果不选结束时间，表示在某个时间之后创建的记录
然后，组件中，开启了范围选择，就必须选中结束时间才生效。

**Comment by ziyoung** [comment]
提供个例子吧。

**Comment by jianghuzai** [comment]
@ziyoung 
![image](https://user-images.githubusercontent.com/16590040/46614712-1a5aa780-cb49-11e8-941e-ff3a1126e539.png)
例如上图，把“创建时间作为筛选条件时”，意思就是说：显示所有在"开始时间"之后，并且在“结束时间”之前的记录。当我使用日期时间范围选择控件时，必须指定开始时间和结束时间，无法表达“在某之间之后的所有记录”或者“在某时间之前的所有记录”。要实现这两个，只能拆分成两个日期时间选择器，这样我又得自己写一遍判断，不允许结束时间在开始时间之前。。。。

当使用日期时间范围选择时：
现状：可以    同时选择两个  或者  同时两个都不选
期待：可以     只选择开始时间     或者     只选择结束时间   或者   同时选择两个    或者  同时两个都不选

**Comment by jianghuzai** [comment]
@ziyoung 
![image](https://user-images.githubusercontent.com/16590040/46615282-6a863980-cb4a-11e8-88c0-e44e7f3b4174.png)


例如上图，把“创建时间作为筛选条件时”，意思就是说：显示所有在"开始时间"之后，并且在“结束时间”之前的记录。当我使用日期时间范围选择控件时，必须指定开始时间和结束时间，无法表达“在某之间之后的所有记录”或者“在某时间之前的所有记录”。要实现这两个，只能拆分成两个日期时间选择器，这样我又得自己写一遍判断，不允许结束时间在开始时间之前。。。。

当使用日期时间范围选择时：
现状：可以 同时选择两个 或者 同时两个都不选
期待：可以 只选择开始时间 或者 只选择结束时间 或者 同时选择两个 或者 同时两个都不选

**Comment by ziyoung** [comment]
你是想通过设置 pickerOptions 中的 disabledDate 来实现这个功能吧。当你选择第一个时间时，在 disabledDate 函数中中无法访问这个值的。所以我觉得就目前的实现来讲，这个不太好做。
