### ISSUE TITLE
Is there any drag triggered event in the [Feature Request] <el-scrollbar> hidden component?

### ISSUE THREAD

**Issue by chanmufeng** [ElemeFE/element#12988]
### Existing Component
Yes

### Component Name
<el-scrollbar>

### Description
最近想利用<el-scrollbar>来模拟滚动条，需要用到事件触发，希望知道的大佬告知一下

**Comment by ziyoung** [comment]
el-scrollbar 组件仅仅是供组件内部使用，不推荐在项目中使用。
