### ISSUE TITLE
[Bug Report] Vue SSR server will overflow memory

### ISSUE THREAD

**Issue by Jandysang** [ElemeFE/element#12984]
### Element UI version
2.4.0

### OS/Browsers version
windows 7/chrome  69.0.3497.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
使用vue ssr部署服务器后；一般在24小时之后，内存会溢出后而宕机

### What is Expected?
解决在vue SSR环境下，内存溢出的问题

### What is actually happening?
目前，内存溢出；不知是不是使用方法不当的原因；如何之前有这方面的问题，已处理处理。请问什么版本是解决了这个问题的；

**Comment by ziyoung** [comment]
确定是 Element 的 bug 吗？
是不是你这边使用上的问题。建议结合日志排查一下。

**Comment by ziyoung** [comment]
有一篇文章：http://taobaofed.org/blog/2016/04/16/how-to-find-memory-leak/ 可以参考下。

**Comment by Jandysang** [comment]
新增一个空白的情况；然后同Apache ab压测这个空白；内存会保持在150M左右，不会变化；但是在这个页面上使用了几个element的UI（el-dropdown、el-dropdown-menu、el-dropdown-item、el-popover、el-input-number、el-button；不太能确定是这个其中的那个组件引起的）；没有任何逻辑和数据；然后再压测后发现，内存发生缓慢的溢出；所以用于整个系统的情况下，docker 1G的内存；24小时左右就耗完了；
