### ISSUE TITLE
[Feature Request] Can you support autocomplete suggestions prefix & suffix

### ISSUE THREAD

**Issue by mygu** [ElemeFE/element#12989]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
I need to add something custom before autocomplete suggestions such as a table header.

![20181009103157](https://user-images.githubusercontent.com/3753924/46643450-b9fe5100-cbae-11e8-9e27-77e7c033007c.png)

**Comment by workforx** [comment]
同求!!!关注. 顶.

**Comment by mygu** [comment]
就是功能太简单了，大佬都在忙别的大事呢~看来只能等着大佬闲了再来看了 :)

**Comment by csvwolf** [comment]
PR is welcomed

**Comment by ziyoung** [comment]
目前的话，用户可以通过 scoped slot 来实现这个功能。

**Comment by csvwolf** [comment]
PR is ready. Closed.
