### ISSUE TITLE
[Bug Report] Upload list transition has a bad behavior

### ISSUE THREAD

**Issue by Michkkael** [ElemeFE/element#12987]
### Element UI version
2.4.8

### OS/Browsers version
Mac OS Mojave, Chrome Version 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/gwd9phLo/2/](https://jsfiddle.net/gwd9phLo/2/)

### Steps to reproduce
Just delete the file at the top of the list.

### What is Expected?
When you delete then, you should just see the file stay in its place and disappear.

### What is actually happening?
When you delete then, you will see that the file moves to the very bottom of the list and disappears.

This is due to the dynamic v-key value which is, in that case, based on the array index of the file. So on remove, all indexes changes.

### How to fix this issue?

[Here](https://github.com/ElemeFE/element/blob/dev/packages/upload/src/upload-list.vue#L14), instead of using `index`, please use `file.name`

**Comment by zykoikaze** [comment]
[Video_2018-11-02_234232.zip](https://github.com/ElemeFE/element/files/2543167/Video_2018-11-02_234232.zip)
现在我的刷新页面有动画，我不想要~

**Comment by zykoikaze** [comment]
![2018-11-03_122916](https://user-images.githubusercontent.com/28927210/47948057-29742000-df64-11e8-9477-5defab3ec4ff.png)
[Video_2018-11-02_234232.zip](https://github.com/ElemeFE/element/files/2544626/Video_2018-11-02_234232.zip)
file-list改为获取数据时，会出现很奇怪的动画。

**Comment by Liuhuang814** [comment]
手动上传执行submit()方法会触发文件删除方法，是bug还是正常的？

**Comment by pizhihui** [comment]
@zykoikaze 我想问一下，奇怪的动画的问题解决了没有。我这里也有

**Comment by hzx930415** [comment]
我也有这个动画的问题，好烦人啊

**Comment by pinkchen** [comment]
好像用了file-list 就会有吧
