### ISSUE TITLE
<el-table> cell 里的 button 如何指向所在 row的数据？

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#1299]
~~~html
<el-table-column
     inline-template
     :context="_self"
     width="80"
     label="操作">
  <span>
    <el-button type="text" size="small" class="text-success" @click="handleClick">编辑</el-button>
  </span>
</el-table-column>
~~~

~~~js
tableData: [{
  id: 1,
  account: 'admin'
},  {
  id: 2,
  account: 'admin',
}]
~~~

![image](https://cloud.githubusercontent.com/assets/8470477/20553660/34bef5e6-b191-11e6-9903-23f7b55c487d.png)

像这里，「编辑」按钮的 `handleClick` 函数应如何能访问到当前行（即 `tableData` 对象数组中的特定成员）？`:context="_self"` 如何使用？试过为 `handleClick` 传入 `_self` 参数但没用。

**Comment by furybean** [comment]
handleClick => handleClick(row)?
