### ISSUE TITLE
The original color of the [Bug Report] color-picker component is red (expressed in either of  F00 / ff0000 / red / RGB (255, 0, 0) / RGBA (255, 0, 0, 1)), opens the pickup panel, and cannot fill in the current color value in the input box

### ISSUE THREAD

**Issue by rosesky** [ElemeFE/element#12994]
### Element UI version
2.4.8

### OS/Browsers version
win7(64位)/chrome  65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/jc10np8q/](https://jsfiddle.net/jc10np8q/)

### Steps to reproduce
①打开测试页面，地址为：https://jsfiddle.net/jc10np8q/  ；
②修改data数据color1属性为字符串"#f00"、"#ff0000"、"red"、"rgb(255,0,0)"、"rgba(255,0,0,1)"中的任意一个,点击页面左上角Run按钮，右下角预览区域对应的拾色器组件颜色变为红色；
③点击右下角预览区与color1对应的组件打开拾色器面板，观察面板左下角的输入框中是否能够回填当前颜色值

### What is Expected?
拾色器面板左下角输入框能够正确回填#f00、#ff0000、red、rgb(255,0,0)、rgba(255,0,0,1)中的一个

### What is actually happening?
拾色器面板左下角输入框显示为空

**Comment by rosesky** [comment]
@ziyoung 测试地址我已经更新了，请问这个问题是否会得到修复？

**Comment by csvwolf** [comment]
@rosesky I have post a pr. Thanks for your issue.
