### ISSUE TITLE
Show-overflow-tooltip in [Bug Report] form does not work in chrome 69 version.

### ISSUE THREAD

**Issue by ElNinoT9** [ElemeFE/element#12998]
### Element UI version
2.4.6

### OS/Browsers version
macOS / Mojave / chrome 69.0.3497.100（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
el-table-column标签中设置show-overflow-tooltip属性。当内容过长，自动隐藏，多余部分变为省略号，该情形下。

### What is Expected?
鼠标悬浮，显示全部内容

### What is actually happening?
chrome 69.0.3497.100（正式版本） （64 位）鼠标悬浮无效果（将element-ui更新到2.4.8同样不起作用）；
chrome 68、ie10、360急速均正常显示。

**Comment by ElNinoT9** [comment]
打包的问题，当时将几个大的第三方插件（含element）单独打包为文件A，在index.html中引用，每次服务器自动发布时，只打包其他插件， 这样做导致element的toolTips无法正常使用。     现在将element从A的打包中抽离，每次build都打包element，就正常了。        具体什么原因导致的，尚不清楚，请不吝帮忙解答。

**Comment by csvwolf** [comment]
Please get a jsfiddle link? There is no problem for Chrome 70.x
