### ISSUE TITLE
[Feature Request] table filter checkbox option too many options box CSS problem

### ISSUE THREAD

**Issue by mjyg** [ElemeFE/element#12992]
### Existing Component
是

### Component Name
table

### Description
table filter checkbox 选项过多时选项框长度过长，希望可以设定固定高度，添加滚动条，当过滤选项过多时可以向下滚动

**Comment by ziyoung** [comment]
支持的。https://jsfiddle.net/v2ysf5x3/
你可以通过设置 el-table-filter__wrap 的样式来调整高度。
