### ISSUE TITLE
[Bug Report] submenu's submenus don't hide when mouseleave in collapse mode

### ISSUE THREAD

**Issue by guidetheorient** [ElemeFE/element#13005]
### Element UI version
2.4.8

### OS/Browsers version
windows 10/chrome 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/cmp4whsb/](https://jsfiddle.net/cmp4whsb/)

### Reproduction Gif
![reproduction gif](http://p6p7zen1i.bkt.clouddn.com/GIF.gif)

### Steps to reproduce
1. mouse hover to show all level submenus
2. mouse leave third-class submenu
3. mouse hover the postition icon and leave

### What is Expected?
when mouse hover the postion icon, the second-class submenu shound hide

### What is actually happening?
when mouse hover the postion icon, the second-class submenu doesn't hide

**Comment by ziyoung** [comment]
@guidetheorient can't reproduce.

![kapture 2018-11-05 at 18 19 01](https://user-images.githubusercontent.com/12947422/47992233-5290de00-e127-11e8-8168-be40cef04083.gif)

**Comment by guidetheorient** [comment]
step two: don't click the third class submenu, just mouseleave and hover the root icon again

**Comment by wacky6** [comment]
Removing nested `popper-append-to-body` works fine. https://jsfiddle.net/70ek1xqb/

**Comment by guidetheorient** [comment]
@wacky6  I know it, but I need this property.  if , without this property, I don't know how to make the submenu scroll y-axis when its height exceeds the body's height.

**Comment by wacky6** [comment]
What do you mean by saying "scroll y-axis", you can update your jsfiddle to show the problem.

**Comment by guidetheorient** [comment]
https://jsfiddle.net/0jpd27ne/3/    without  `popper-append-to-body`, scroll like this jsfiddle with defined height

**Comment by csvwolf** [comment]
@ziyoung I reproduce it. In fact I think the structure design of navbar menu is a bit awful. Maybe we can refactor it in next version. ( Just meet the standards of the HTML semantic )

**Comment by foyewy** [comment]
I reproduce it

**Comment by foyewy** [comment]
I also found this situation.
