### ISSUE TITLE
[Feature Request] Sticky elements?

### ISSUE THREAD

**Issue by Aztriltus** [ElemeFE/element#13007]
### Existing Component
No

### Component Name
Sticky element

### Description
Is there a way to implement sticky elements inside of a el-main container? 

<el-main>
<div>
<div class="sticky"></div>
<div class="other-content"></div
</div>
</el-main>

.sticky {
position: sticky;
top: 0;
}

In the example above, I added the css required for sticky to work but it isn't working. I'm assuming that the el-main caused this issue and unless I remove all element.io layout containers, it wouldn't work. Do you have any clue how I can implement a sticky element?

**Comment by ziyoung** [comment]
Many browsers don't support sticky https://caniuse.com/#search=sticky 
If we add this component, we have to use polyfill. So we have no plan to support this.
