### ISSUE TITLE
[Feature Request] Reactive table expand row

### ISSUE THREAD

**Issue by fatoldsun00** [ElemeFE/element#13000]
### Existing Component
Yes

### Component Name
Table

### Description
Hi, 

it's maybe possible : i had a table with expand attribute row and template. On event expand-change i fire ajax script and i add response to data table with this.$set. But experience with expand row is strange : when data are load the row collapse.

There are any way to load ajax data in a expand row or, better, hava a hook on before expand ?

Thanks a lot

**Comment by coffeeyen** [comment]
use attribute expand-row-keys,
example:
https://jsfiddle.net/bjw4ueoh/

**Comment by ziyoung** [comment]
@fatoldsun00 this should work for you. Thank you @coffeeyen 

> use attribute expand-row-keys,
> example:
> https://jsfiddle.net/bjw4ueoh/

**Comment by fatoldsun00** [comment]
Thanks for response !

I need to precise that i make an ajax call for data display in expand.

In your example data in expandable box are load at start.

By the way i tried your solution, without success :(

**Comment by bingyuea** [comment]
now ， i meet this question but it did not work

**Comment by bingyuea** [comment]
> now ， i meet this question but it did not work

https://jsfiddle.net/bjw4ueoh/

In your example data in expandable box are load at start.

**Comment by coffeeyen** [comment]
> > now ， i meet this question but it did not work
> 
> https://jsfiddle.net/bjw4ueoh/
> 
> In your example data in expandable box are load at start.

??? nth different
https://jsfiddle.net/bjw4ueoh/12/

**Comment by fatoldsun00** [comment]
:row-key='getRowKey' save me

`<el-table ref="tab" :row-key='getRowKey' :data="Object.values(liste)" @expand-change="expand">
          <el-table-column type="expand">
            <template slot-scope="listscope">
              <div v-if="listscope.row.salesorderdetail == undefined" v-loading="expandableLoading"></div>
              <div v-else v-for="(item,key) in listscope.row.salesorderdetail" :key="key">
                <el-row :gutter="10">
                  <el-col :span="6">
                    <strong>Ref : </strong>{{ item.articlecode }}
                  </el-col>
                  <el-col :span="4">
                    <strong>{{ $tc('global.quantity') }} :</strong> {{ item.quantity }}
                  </el-col>
                  <el-col :span="4">
                    <img style="width: 100%" :src=" item.imagename " />
                  </el-col>
                  <el-col :span="6">
                    <strong>{{ $tc('global.marques',1) }} : </strong>{{ item.makename }}
                  </el-col>
                  <el-col :span="4">
                   <strong> {{ $tc('global.couleurs',1) }} : </strong>{{ item.optionname }}
                  </el-col>
                </el-row>
              </div>
            </template>
          </el-table-column>

....

 methods : {  
    getRowKey: function(row){
      return row.salesorderno;
    },
}`
