### ISSUE TITLE
[Feature Request] el-input validation outside a form

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#13001]
### Existing Component
Yes

### Component Name
el-input

### Description
would it be possible to validate an el-input value outside a form or el-form-item elements?

**Comment by ziyoung** [comment]
Element doesn't support this.

**Comment by Masber** [comment]
why not?

**Comment by rktyt** [comment]
@ziyoung I also want it. Because i want to divide it as a component, such as when there are many form items.

**Comment by CodeDreamfy** [comment]
This is very frustrating
