### ISSUE TITLE
[Bug Report] el-date-picker set format yyyy-MM-dd HH:00:00 but time options display options

### ISSUE THREAD

**Issue by noxxxxxxxx** [ElemeFE/element#13016]
### Element UI version
2.4.8

### OS/Browsers version
mac/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/2y0rku5t/](https://jsfiddle.net/2y0rku5t/)

### Steps to reproduce
<el-date-picker v-model="value1" type="datetime" placeholder="选择日期时间" format="yyyy-MM-dd HH:00:00"></el-date-picker>

### What is Expected?
Only display the hour options or still show the full options [HH:mm:ss]

### What is actually happening?
Display hour options and seconds options
![image](https://user-images.githubusercontent.com/37919656/46779058-f1086a00-cd48-11e8-84a0-d0741cb6630f.png)

**Comment by muzishuiji** [comment]
> Translation of this issue:
> 
> Element UI version
> 2.4.8
> 
> OS/Browsers version
> Mac/chrome
> 
> Vue version
> 2.5.17
> 
> Reproduction Link
> https://jsfiddle.net/2y0rku5t/
> 
> Steps to reproduce
> < el-date-picker V-model = "value1" type = "datetime" placeholder = "select date and time" format = "yyyy-MM-dd HH: 00:00" >
> 
> What is Expected?
> Only display the hour options or still show the full options full
> 
> What is actually happening?
> Display hour options and seconds options
> 
> [image](https://user-images.githubusercontent.com/37919656/46779058-f1086a00-cd48-11e8-84a0-d0741cb6630f.png)

时间选择不能设置不允许清空这个很不合理

**Comment by noxxxxxxxx** [comment]
> Translation of this issue:
> 
> Element UI version
> 2.4.8
> 
> OS/Browsers version
> Mac/chrome
> 
> Vue version
> 2.5.17
> 
> Reproduction Link
> https://jsfiddle.net/2y0rku5t/
> 
> Steps to reproduce
> < el-date-picker V-model = "value1" type = "datetime" placeholder = "select date and time" format = "yyyy-MM-dd HH: 00:00" >
> 
> What is Expected?
> Only display the hour options or still show the full options full
> 
> What is actually happening?
> Display hour options and seconds options
> 
> [image](https://user-images.githubusercontent.com/37919656/46779058-f1086a00-cd48-11e8-84a0-d0741cb6630f.png)

![image](https://user-images.githubusercontent.com/37919656/46860534-327d4000-ce43-11e8-90ea-4263503d6c62.png)

**Comment by wacky6** [comment]
I think date-picker only supports hiding second picker. If you only want date+hour, consider to build a custom component with date-picker + time-select.
