### ISSUE TITLE
How does [Feature Request] NavMenu's open method specifically use?

### ISSUE THREAD

**Issue by Mingscript** [ElemeFE/element#13014]
### Existing Component
是

### Component Name
NavMenu

### Description
官方没有NavMenu open方法的具体示例，只有open回调的示例，网上也没找到具体的使用方法，能告诉我具体应该怎么使用么，就是特定展开某个submenu 的方法示例

**Comment by ziyoung** [comment]
文档的拼写错误，参数是需要打开的 sub-menu 的 index。
![image](https://user-images.githubusercontent.com/12947422/46945010-4e345080-d0a6-11e8-80ff-600c776a8c9b.png)
