### ISSUE TITLE
[Bug Report] The datepicker panel is not updated when I change the value of the v-model.

### ISSUE THREAD

**Issue by suuzee** [ElemeFE/element#13015]
### Element UI version
2.2.1

### OS/Browsers version
macOS Mojave 10.14/ Google Chrome 69.0.3497.100

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/ze_su/zkwt5sqj/20](https://jsfiddle.net/ze_su/zkwt5sqj/20)

### Steps to reproduce
The date-picker panel is not updated when I change the value of the v-model.

### What is Expected?
The date-picker panel is not updated when I change the value of the v-model.

### What is actually happening?
The date-picker panel will be updated when I change the value of the v-model.

**Comment by wacky6** [comment]
At the moment, you have to `setTimeout` or `nextTick`. The picker panel is a separate component, the data from is not synchronously passed to it.
