### ISSUE TITLE
[Feature Request] select selector recommends adding full selection function.

### ISSUE THREAD

**Issue by shejianmin** [ElemeFE/element#13010]
### Existing Component
Yes

### Component Name
el-select

### Description
select选择器多选时，希望增加个全选功能

**Comment by coffeeyen** [comment]
a not perfect solution:
https://jsfiddle.net/coffeeyen/eywraw8t/419920/
hope it can help you~

**Comment by ziyoung** [comment]
> a not perfect solution:
> https://jsfiddle.net/coffeeyen/eywraw8t/419920/
> hope it can help you~

@shejianmin 上面的方案可行。如果数据是有层次关系的，推荐使用 tree-select（3.x 新增的组件）。

**Comment by L-x-C** [comment]
@ziyoung 敢问有3.x的tree-select的体验版么...
