### ISSUE TITLE
[Bug Report] table sorting is not sorted in the right order.

### ISSUE THREAD

**Issue by gdutwyg** [ElemeFE/element#13028]
### Element UI version
2.4.8

### OS/Browsers version
window/ chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/9kxf150u/](https://jsfiddle.net/9kxf150u/)

### Steps to reproduce
打开重现链接查看即可

### What is Expected?
期望是445 33 11 2 排序

### What is actually happening?
默认是降序排序，但是结果确是445 33 2 11

**Comment by coffeeyen** [comment]
不是bug, 你的date是字符串, 字符串的排序就是这样的, 返回的是第一个不同的字符大小比较. 改为number就按照你期望的排序了. https://jsfiddle.net/9kxf150u/1/
