### ISSUE TITLE
[Bug Report] Multiple ElTables with the same data source have BUG when switching (unable to switch display and report errors)

### ISSUE THREAD

**Issue by newdefence** [ElemeFE/element#13023]
### Element UI version
2.4.8

### OS/Browsers version
windows 10 / chrome 66

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/newdefence/mmx38qxw/6507/](https://jsfiddle.net/newdefence/mmx38qxw/6507/)

### Steps to reproduce
1. 进入页面，等待页面渲染完成
2. 点击页面的第一个按钮“无法切换回第一个表格BUG”，此时显示 第一个 v-else 逻辑的表格(有红色字体）
3. 再次点击“无法切换回第一个表格BUG”，此时应该显示 第一个 v-if 逻辑的表格（无红色字体）
-------
4. 开始第2个bug的步骤
5. 点击页面的“切换回第一个表格时查看控制台BUG” 按钮，显示 第二个 v-else 逻辑的表格（有3列）
6 再次点击“切换回第一个表格时查看控制台BUG”，此时控制台开始出现BUG
7.重复点击此按钮，控制台不断出现Error
--------------
8. BUG原因分析：多个表格引用同一个数据源时，有相同列 prop 的渲染时会出现（一个表格列使用 slot-scope，另外一个表格列不使用）

### What is Expected?
1. 能正常切换2个table
2. 切换table时不报错

### What is actually happening?
1. 不能正常切换table
2. 不能正常切换table，且报错

**Comment by coffeeyen** [comment]
其实是同一个问题, el-table被vue复用了, 但el-table-column其实修改了.
解决方案, 给每个el-table加上不同的key, 则不会复用
参考: [用 key 管理可复用的元素](https://cn.vuejs.org/v2/guide/conditional.html#%E7%94%A8-key-%E7%AE%A1%E7%90%86%E5%8F%AF%E5%A4%8D%E7%94%A8%E7%9A%84%E5%85%83%E7%B4%A0)

**Comment by ziyoung** [comment]
@newdefence 这个方案是可行的。

> 其实是同一个问题, el-table被vue复用了, 但el-table-column其实修改了.
> 解决方案, 给每个el-table加上不同的key, 则不会复用
> 参考: [用 key 管理可复用的元素](https://cn.vuejs.org/v2/guide/conditional.html#%E7%94%A8-key-%E7%AE%A1%E7%90%86%E5%8F%AF%E5%A4%8D%E7%94%A8%E7%9A%84%E5%85%83%E7%B4%A0)
