### ISSUE TITLE
[Bug Report] The el-option of the  el-select component does not follow scrolling.

### ISSUE THREAD

**Issue by david2tdw** [ElemeFE/element#13037]
### Element UI version
2.4.8

### OS/Browsers version
windows 7 / chrome 67.0.3396.79（正式版本） （32 位）

### Vue version
2.5.17

### Reproduction Link
[https://codepen.io/david2018/pen/mzMbLy](https://codepen.io/david2018/pen/mzMbLy)

### Steps to reproduce
1. 点击一个select，下拉列表出现。
2. 用鼠标中建滚动页面。

### What is Expected?
在页面滚动的时候，下拉列表也跟随一起滚动。

### What is actually happening?
在页面滚动的时候，下拉列表依然固定在原来的位置，没有跟随滚动。

**Comment by coffeeyen** [comment]
Set CSS 'overflow-y: scroll;height:300px;' in '.main-1' instead of '.main' in your code can solve it

**Comment by ziyoung** [comment]
应该是 `popperjs` 的问题，相关 pr 在这里 #11778。

**Comment by david2tdw** [comment]
@coffeeyen yes. But there is a default scroll bar in our main page of application. so not able to change the overflow-y property to inner div. 
It's better to resolve this if possible.

**Comment by david2tdw** [comment]
@ziyoung 好的

**Comment by VitaliZinkevich** [comment]
Got the same issue with el-select and el-datepicker. Dropdowns are scrolling with the body.
"element-ui": "2.11.1"

**Comment by shivajiranaware** [comment]
Any update on this issue ?
