### ISSUE TITLE
After the [Bug Report] [2.4.8] version Upload component selects files, the URL attribute in file is gone.

### ISSUE THREAD

**Issue by willeweit** [ElemeFE/element#13033]
### Element UI version
2.4.8

### OS/Browsers version
chrome 69.0.3497.100（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
选择文件 -> 通过on-preview回调 打印file ->查看file属性

### What is Expected?
旧版本中file属性中有url属性

### What is actually happening?
现在这个url属性没了

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/12934#issuecomment-425622248
