### ISSUE TITLE
[Bug Report] Using v-text inside the Button component causes the effect of loading to fail

### ISSUE THREAD

**Issue by cduyzh** [ElemeFE/element#13036]
### Element UI version
2.4.3

### OS/Browsers version
win10

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/dun5pt26/](https://jsfiddle.net/dun5pt26/)

### Steps to reproduce
<el-button type="primary" :loading="true" v-text="'s'"></el-button>

### What is Expected?
I want to be able to insert the text of the button in v-text to make sure that the loading is valid

### What is actually happening?
The effect of loading fails when v-text is used inside the Button

**Comment by wacky6** [comment]
v-text should only be used on native HTML elements.

https://vuejs.org/v2/api/#v-text
