### ISSUE TITLE
[Bug Report] [Bug Report] el-pagination Input box shows red border when total is no zero

### ISSUE THREAD

**Issue by zuoLand** [ElemeFE/element#13038]
### Element UI version
2.4.6

### OS/Browsers version
Window10/FireFox Quantum 62.0.3(64Bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/4g1pvae9/](https://jsfiddle.net/4g1pvae9/)

### Steps to reproduce
Run https://jsfiddle.net/4g1pvae9/ Link can show the bug.

### What is Expected?
el-pagination Input box shows defualt color border when total is no zero.

### What is actually happening?
el-pagination Input box shows red border when total is no zero.

**Comment by zuoLand** [comment]
![snipaste_2018-10-12_17-43-08](https://user-images.githubusercontent.com/17779376/46861962-71f95b80-ce46-11e8-8eb6-226b199de5c3.png)

**Comment by ziyoung** [comment]
没有第 0 页。

**Comment by causelaputa** [comment]
When `total` is ZERO, the computed value `internalPageCount` in file `element/packages/pagination/src/pagination.js` is ZERO too, so `getValidCurrentPage()` may return an ZERO that we don't expect.
