### ISSUE TITLE
[Feature Request] access row data within pickerOptions.disabledDate

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#13045]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
I have an el-table with each row showing a field called "minDate" and a el-date-picker element. What I am trying to do is to disable any date before the minDate on the el-date-picker element but I don't know how to access the minDate value form the disabledDate method. This is an example https://jsfiddle.net/mmx38qxw/6542/

**Comment by wacky6** [comment]
Use High Order Function: https://jsfiddle.net/bfk1Ln3j/
