### ISSUE TITLE
message 组件有什么推荐的方式进行扩展修改么?

### ISSUE THREAD

**Issue by asmodai1985** [ElemeFE/element#1304]
### ElementUI version
1.0.2

除了自己copy代码重新实现还有什么好点的方式么？看了下源代码，发现基本算写死了。

现在有个小需求，message需要传入 富文本 而不是纯文本，组件并没有提供参数，只能自己修改了

**Comment by Leopoldthecoder** [comment]
是的。从我们的角度看，Message 是很轻量的，目前不计划支持富文本。
