### ISSUE TITLE
[Feature Request] Slots on datepicker

### ISSUE THREAD

**Issue by andrewckor** [ElemeFE/element#13040]
### Existing Component
Yes

### Component Name
Datepicker

### Description
I would like to create two new slots for [Datepicker](https://element.eleme.io/#/en-US/component/date-picker) similar to [Dialog](https://element.eleme.io/#/en-US/component/dialog#slot) component.
One `header` and one `footer` that you can put custom views in there.
We can alternatively call them `prefix` / `suffix`.

I'm creating this ticket to ask @Leopoldthecoder , if a feature like this could be accepted and worth my time making it. The implementation will be very minimal and will not affect any existing user.

Here is a potential use case:
![screenshot 2018-10-12 at 14 33 23](https://user-images.githubusercontent.com/929765/46866931-ef63a280-ce2b-11e8-9ea2-456726696bf5.png)

**Comment by wacky6** [comment]
You should ask @jikkai and @ziyoung for new feature requests now.

But, from technical perspective, given existing code base: this feature can not be easily implemented. The popup you see is isolated from date-picker's input box. I guess considerable refactor is needed to make these slots possible. You can check refactor considerations here: https://github.com/ElemeFE/element/issues/9878

Though I am stuck with school work at this moment, and do not have time to implement these refactors myself.

**Comment by andrewckor** [comment]
Your feedback is welcome @wacky6 but I don't know how can I contribute to those tickets, and because #9878 is too big I don't see it finishing any time soon.

Do you have any suggestion on how to proceed with smaller fixes?

**Comment by andrewckor** [comment]
I'm afraid that if the datepicker structure changes completely it might be a waste of time to build something at the moment, until you are done. Or not?

**Comment by wacky6** [comment]
The problem is that I don't know when I would have enough time to do so.

Small changes are ok, like value-format. I don't think they will be thrown away even if we do a major refactor.

As long as the new feature does not change the code structure significantly, and is a non-breaking change, they can be performed now. Also, when I did the refactor for 2.0 last year, most code are reused (but may be cut-pasted into different locations).

If you really want add header / footer, ask for @ziyoung 's approval. I would recommend you come up with more convincing use cases.

Don't worry about API design at the moment. If we are to include 9878 in 3.0 release, most date-picker API **will be broken anyway** (That's the purpose of doing a major release).

**Comment by andrewckor** [comment]
Ok thank you, then let's wait for @ziyoung 's approval before I start.

**Comment by ziyoung** [comment]
@andrewckor Can you explain the usage scenario of this? You can choose week, month or year by setting type now.http://element-cn.eleme.io/#/en-US/component/date-picker#other-measurements

**Comment by wacky6** [comment]
I just want to add that dynamically change type of date picker is to be deprecated in the future. Switching of panel type will require a full remount of the component.

**Comment by andrewckor** [comment]
@wacky6 This is how I did it today, I used the shortcut links to change the type unmount and remount the calendar. It's dirty but it works.

```
text: 'Weekly',
onClick: (picker) => {
    this.type = 'week';
    this.visible = false;
    
    this.$nextTick(() => {
        this.visible = true;
        this.$nextTick(() => {
            this.$refs.picker.focus();
        })
    })
}
```

It works like this:
![2018-10-12 20 26 59](https://user-images.githubusercontent.com/929765/46884311-4df54480-ce5d-11e8-99c8-3f93221f55c3.gif)

**Comment by ziyoung** [comment]
> Another example would be an option to display an alert message at the top of the calendar that notify your customers.

Could you explain why add this attribute?
