### ISSUE TITLE
[Bug Report] table show-summary merge cell

### ISSUE THREAD

**Issue by osinglee** [ElemeFE/element#13046]
### Element UI version
2.4.5

### OS/Browsers version
macOS 10.13.4 

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
期望能实现 合计行可以自定义向左或向右合并单元格

### What is Expected?
期望能实现 合计行可以自定义向左或向右合并单元格

### What is actually happening?
合并行无法进行单元格合并

**Comment by coffeeyen** [comment]
It's a feature not a bug. And I think you can solve it by add an headless el-table under your table and calculate summary by yourself. It's easy to use and flexible. That's also what element-ui does when you set 'show-summary' true.

**Comment by ziyoung** [comment]
可以试试 @coffeeyen  的方案。
