### ISSUE TITLE
[Bug Report] Wrap the horizontal menu items with div

### ISSUE THREAD

**Issue by edwinhuish** [ElemeFE/element#13051]
### Element UI version
2.4.8

### OS/Browsers version
Win10 / Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/z8u29og3/](https://jsfiddle.net/z8u29og3/)

### Steps to reproduce
Wrap the horizontal menu items with div

### What is Expected?
register the menu items as component

### What is actually happening?
el-menu's display mode setting invalid, displaying in vertical mode

**Comment by wacky6** [comment]
SubMenu/MenuItem must be direct descendants of Menu. Wrapping then in other elements are not supported.

https://jsfiddle.net/zdraoLm8/

**Comment by ruixiu** [comment]
如果要动态生成应该如何做?

**Comment by edwinhuish** [comment]
> 如果要动态生成应该如何做?

我当时也是动态生成的，自己加CSS就可以解决。

**Comment by ito27** [comment]
You could use <template> instead of <div>.
