### ISSUE TITLE
[Bug Report] el-steps component line color not correct

### ISSUE THREAD

**Issue by sunchenguang** [ElemeFE/element#13068]
### Element UI version
2.4.8

### OS/Browsers version
chrome 69 mac 10.13.6

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/b9hqdzgu/](https://jsfiddle.net/b9hqdzgu/)

### Steps to reproduce
we have three el-step, set el-steps attribute process-status and finish-status are success, active is 1。
it is a style problem.

### What is Expected?
we expect the first and second el-step circle is green, and the line between first and second el-step should be green ,but the line is grey

### What is actually happening?
 the line between first and second el-step is grey

**Comment by stranger26** [comment]
I just did some testing on your fiddle. I observed that using `finish-status` alone will keep the line colored, but using `process-status` will not. I'll see if I can work on a fix.

**Comment by sunchenguang** [comment]
@stranger26 nice try!
but i see this line, the judge is useless. it will always be 0.
```
if (currentProcessStatus) {
    step = this.currentStatus !== 'error' ? 0 : 0;	     
 } 
```
i think below code will solve this issue
```
if (currentProcessStatus) {
    step = this.currentStatus !== 'success' ? 0 : 100;	     
 } 
```

**Comment by ziyoung** [comment]
It seems like a bug. But it's strange that `finish-status` is the same of `process-status`.

**Comment by sunchenguang** [comment]
some scene may use this. 
for example, i just want to **distinguish completed and uncompleted**, just two situation.

**Comment by JackZhouMine** [comment]
> It seems like a bug. But it's strange that `finish-status` is the same of `process-status`.

Hi,what are diffence betweetn `process-status="success"` and `finish-status="success"`?

`process-status`  和 `finish-status` 有什么不同呢？
最后一步就在所有步骤里面，那么执行到最后一步，就是当成步骤，当前步骤成功，这时就是最后一步成功，没有执行到最后一步，它就是处于等待状态。
为何要单独设置最后一步的状态呢？能举一个使用场景吗？

**Comment by sunchenguang** [comment]
@JackZhouMine 没懂你想表达什么
这个issue先关了  反正官方也不管

**Comment by siningintherain** [comment]
那个process-status属性确实就是个bug，怎么设置都没有用
但是这个问题其实可以通过在每一个el-step标签上加上status属性来指定每一个步骤的状态即可
