### ISSUE TITLE
There is logic problem in sorting API sort-method of [Bug Report] form component.

### ISSUE THREAD

**Issue by chongyue110** [ElemeFE/element#13065]
### Element UI version
2.4.8

### OS/Browsers version
win10 / 谷歌

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
sort-method 的回调 api 设计的 function (a, b) {} 类似 Array.sort(), 但是在实际使用的时候我还会希望知道当前排序的列对应的字段信息而不是仅仅前后两条数据的信息,不然当一个表格存在多个字段需要排序的时候我触发了这个函数却不知道要根据什么字段去排序.

### What is Expected?
sort-method 的回调除了 a, b 前后两条数据的信息之外额外提供 当前列的信息,方便排序

### What is actually happening?
sort-method 的回调除了 a, b 前后两条数据的信息之外没有提供任何其他信息,导致我不知道究竟是哪一个列在排序.

**Comment by coffeeyen** [comment]
sort-change event

**Comment by ziyoung** [comment]
> sort-change event

@chongyue110
