### ISSUE TITLE
[Bug Report] el-select trigger blur when call focus()

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#13067]
### Element UI version
2.4.8

### OS/Browsers version
mac/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/a1L3vygb/1/](https://jsfiddle.net/a1L3vygb/1/)

### Steps to reproduce
programmatic trigger `el-select` focus() method

### What is Expected?
focus in el-select, not trigger blur event

### What is actually happening?
will trigger once blur event

**Comment by ziyoung** [comment]
realted issue #10810
