### ISSUE TITLE
[Bug Report] how to change default  text in  el-pagination

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/element#13062]
### Element UI version
2.4.8

### OS/Browsers version
mac

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Yanni_Jia/mmx38qxw/6551/](https://jsfiddle.net/Yanni_Jia/mmx38qxw/6551/)

### Steps to reproduce
as shows in filddle
I hope to change default text into my own word like:‘共10条记录’

### What is Expected?
I can change total default text

### What is actually happening?
I do not find in doc

**Comment by feichangtutu** [comment]
Besides, I hope the total num can display special color like:
![image](https://user-images.githubusercontent.com/8478315/46993285-ed0d8b00-d140-11e8-8ce6-5d901611ca4e.png)

**Comment by porcelainHeart** [comment]
@feichangtutu 很简单你把layout里的sizes去掉, 然后自己拿size去写你要的个性化展示内容

**Comment by feichangtutu** [comment]
@porcelainHeart size个性化展示内容是？能给个fiddle例子么？感谢！

**Comment by porcelainHeart** [comment]
https://jsfiddle.net/bm1zf632/2/
@feichangtutu

**Comment by feichangtutu** [comment]
thanks so much!
@porcelainHeart
