### ISSUE TITLE
[Feature Request] el-autocomplete should use a prop for dropData instate of through fetch-suggestions callback.

### ISSUE THREAD

**Issue by mengfairy** [ElemeFE/element#13076]
### Existing Component
是

### Component Name
el-autocomplete

### Description
The only way to change the dropData is through fetch-suggestions callback. But sometimes i should change the dropData by other operation which don't pass the el-autocomplete inner trigger way.
I think is's better to use a prop for dropData instate of through fetch-suggestions callback.

**Comment by ziyoung** [comment]
This seems a breaking change. I think you can use Select instead.
Now, we have no plan to support this.
