### ISSUE TITLE
[Bug Report] How can I style el-input ?

### ISSUE THREAD

**Issue by frontvin** [ElemeFE/element#13077]
### Element UI version
2.4.8

### OS/Browsers version
Ubuntu 16.04 

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6594/](https://jsfiddle.net/mmx38qxw/6594/)

### Steps to reproduce
I have a trouble. When I try to style el-input element, I can't do this. I need a border-bottom: 2px solid yellow in my input field, but styles are aplied to all el-input element. When I used google chrome devtools I saw that el-input generate this structure (divs with classes): .el-form-item > .el-form-item__content > .el-input > input.el-input__inner

### What is Expected?
I need style only input element in my form. I need a border-bottom: 2px solid yellow in my input field.

### What is actually happening?
Styles are aplied to all el-input element, but not to input. When I used google chrome devtools I saw that el-input generate this structure (divs with classes): .el-form-item > .el-form-item__content > .el-input > input.el-input__inner

**Comment by porcelainHeart** [comment]
You can use `Deep Selectors`.
Visit this link for details: [https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors)

**Comment by frontvin** [comment]
> You can use `Deep Selectors`.
> Visit this link for details: https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

Thanks! I'll try it
