### ISSUE TITLE
[Feature Request] el-select: add a slot for the content of tags used by multiple select

### ISSUE THREAD

**Issue by leobartkus** [ElemeFE/element#13081]
### Existing Component
Yes

### Component Name
el-select

### Description
We can make a template for the dropdown options, but not the tags that show the selected items.  I want to be able to customize the selected items, too, and render more than just text in a span.

**Comment by SatanEnglish** [comment]
I third this one though for me even being able to change the tag type would do. e.g. tag-type="danger"

**Comment by DwarGrak** [comment]
I need this feature too! Same issue as SatanEnglish has

**Comment by pixagraphic** [comment]
Yeah this would be such a nice feature. I really need this, as I have a list of people and I want to link to the corresponding people profiles in the tags. I recently migrated from vue-multiselect and this is the only thing I am missing with el-select.

**Comment by jupegarnica** [comment]
Any update about this?   I willing to have it !
