### ISSUE TITLE
[Bug Report] child node lazy loading drag and drop, dragging to el-tree boundary report error

### ISSUE THREAD

**Issue by shadowprompt** [ElemeFE/element#13080]
### Element UI version
2.4.8

### OS/Browsers version
windows 10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/shadowprompt/73ynd2z4/2/](https://jsfiddle.net/shadowprompt/73ynd2z4/2/)

### Steps to reproduce
拖拽任意节点至el-tree界外

### What is Expected?
console.log不报错

### What is actually happening?
console.log报错 
![image](https://user-images.githubusercontent.com/1947096/47087132-d2750800-d24d-11e8-9a90-8dc56728d7ee.png)

**Comment by shen-lan** [comment]
1.官网的文档：
isLeaf | 指定节点是否为叶子节点，仅在指定了 lazy 属性的情况下生效 | boolean, function(data, node)
2.官方的demo
        props1: {
          label: 'name',
          children: 'zones',
          isLeaf: 'leaf'
        }
isLeaf的数据类型不是 限定布尔值 、方法吗？
为什么demo里是字符串？
http://element-cn.eleme.io/#/zh-CN/component/tree

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/47554594-39747a00-d93c-11e8-8593-5a10540a9455.png)
props 是配置选项。
假设 data 中的数据有一个 name 字段，但是没有 label 字段。你想树节点显示其中的 name 字段。
但对于树节点而言，它需要 label 来渲染的。那你就可以把 name 指定为 label。

**Comment by ziyoung** [comment]
懒加载不应该支持拖拽的。
懒加载数据的 load 函数更加层级返回数据。拖拽节点会改变层级，可能会造成数据的冲突。

**Comment by uniquejava** [comment]
大数据量下 比如5000个节点, 必须用lazy mode 然而 dnd等 大部分附加功能全部不好使了. 换别的库了.
