### ISSUE TITLE
The global style problem between 2.0.8~2.4.8 components of [Bug Report] el-menu component causes typesetting disorder.

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [ElemeFE/element#13083]
### Element UI version
2.4.8

### OS/Browsers version
masOS 10.13.4 (17E199), chrome 版本 70.0.3538.67（正式版本） （64 位）

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/2gpft14x/6/](https://jsfiddle.net/2gpft14x/6/)

### Steps to reproduce
1. 原vue@2.5.10   element-ui@2.0.8, el-menu[mode="horizontal"]，样式正常
2. yarn add element-ui
3. package.json 显示更新为最新 element-ui@2.4.8
4. el-menu[mode="horizontal"]组件样式menu及submenu错位

### What is Expected?
2.0.8及以后版本全局样式不影响el-menu默认组件样式

### What is actually happening?
2.0.8及以后版本全局样式已影响el-menu默认组件样式

**Comment by ziyoung** [comment]
文档上的例子http://element-cn.eleme.io/#/zh-CN/component/menu#ding-lan 正常的，应该不是 Element 本身的问题。
从 2.0 到 2.4 出现很多的更新，建议结合自己的项目自行排查一下。

**Comment by HiZhaoxiaoyang** [comment]
可以肯定是只从2.0.8更新至2.4.8导致的el-menu样式冲突错乱。 具体代码之后自查并更新jsfiddle。
