### ISSUE TITLE
[Bug Report] 2.4.8 el-date-picker, when disabledDate is set, there is no choice of current day.

### ISSUE THREAD

**Issue by dwt11** [ElemeFE/element#13093]
### Element UI version
2.4.8

### OS/Browsers version
WIN10/chromium63.0.3239

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/286rd1hp/5/](https://jsfiddle.net/286rd1hp/5/)

### Steps to reproduce
当前示例为:可选择当日及当日以前的任意时间范围,但出现以下问题。
1、点击日期选择范围框,选择时间范围 从1日到当前日,会无法选择。
2、双击当前日,无法选择当前日。

### What is Expected?
1、点击日期选择范围框,选择时间范围 从1日到当前日,可正确选择。
2、双击当前日,时间范围为当前日。

### What is actually happening?
1、点击日期选择范围框,选择时间范围 从1日到当前日,可正确选择。
2、双击当前日,时间范围为当前日。

**Comment by wacky6** [comment]
你需要准确指定下一日的时间。 https://jsfiddle.net/98vn5u0d/
