### ISSUE TITLE
V-model implementation of [Feature Request] Slider components

### ISSUE THREAD

**Issue by chen-zzz** [ElemeFE/element#13095]
### Existing Component
是

### Component Name
Slider

### Description
当我把v-model改写成:value & @input的用法时  组件外部修改value的值的时候，@input事件会被触发，这么实现的目的是什么呢？

例子：

https://jsfiddle.net/bn7j9mz8/14/

<el-slider :value="value1" @input="value1Change"></el-slider>
在例子中，在外部修改"value1" 的值时，就会触发@input事件的value1Change方法

**Comment by ziyoung** [comment]
https://jsfiddle.net/bn7j9mz8/15/ 在这个例子中，我把初始值设置的很大，对于 Slider 组件来说，肯定需要去**纠正**输入值，这个时候要触发 input 事件了。

对于输入组件，还是直接使用 v-model 指令吧。输入值才是用户真正想要的。

在这里，input 事件触发频率有点高。考虑到目前的设计，确实如此。😅
