### ISSUE TITLE
[Bug Report] element UI select selector set value-key problem

### ISSUE THREAD

**Issue by liub1934** [ElemeFE/element#13099]
### Element UI version
2.4.8

### OS/Browsers version
win10/Chrome 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xunmeng/1erjhcL3/903/](https://jsfiddle.net/xunmeng/1erjhcL3/903/)

### Steps to reproduce
select设置了value-key
一开始的时候
![image](https://user-images.githubusercontent.com/29849550/47209878-10943800-d3c4-11e8-98e5-d10d34d72482.png)
选择黄金糕，点击ChangeValue按钮，当前选中的会变成按钮事件改变的值，如select选择了黄金糕，点击按钮后，黄金糕变成了龙须面，和下面的龙须面一块儿被选中了
![image](https://user-images.githubusercontent.com/29849550/47209940-36214180-d3c4-11e8-98bd-9ac12d5a1ee0.png)
这种写法会出现上述的情况
`
this.value.id = '选项4';
this.value.label = '龙须面'
`
但这种情况确实正常的
`
this.value = {
  id: '选项4',
  label: '龙须面'
}
`
不知道是不是算个BUG
### What is Expected?
应该只有ChangeValue动态改变的值才会被选中

### What is actually happening?
会出现2个相同的选中的值

**Comment by coffeeyen** [comment]
你的value是个绑定的是object, 所以传递的是引用, 第一种, 并没有修改引用的地址, 只是修改了值, 也就是选项中那项的值

**Comment by ziyoung** [comment]
加个对 value 的 watcher 就看出结果了。https://jsfiddle.net/1erjhcL3/905/
