### ISSUE TITLE
[Bug Report] CDN require.js undefined

### ISSUE THREAD

**Issue by mrquokka** [ElemeFE/element#13092]
### Element UI version
2.4.7

### OS/Browsers version
Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6643/](https://jsfiddle.net/mmx38qxw/6643/)

### Steps to reproduce
uses require.js to import element ui cdn

### What is Expected?
returning Element
or create Vue Components automaticly

### What is actually happening?
returning undefined

**Comment by ziyoung** [comment]
Duplicate of #12408

**Comment by ziyoung** [comment]
https://jsfiddle.net/zhiyang/q0kgfxns/9/
