### ISSUE TITLE
`<el-table>`表头内插入 HTML 标签？

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#1309]
```html
<el-table
  :data="tableData"
  style="width: 100%">
  <el-table-column
    prop="id"
    width="80"
    label="序号">
  </el-table-column>
  ...
</el-table>
```

表头能否插入 HTML 标签？如图：

![image](https://cloud.githubusercontent.com/assets/8470477/20556199/e2fada12-b1a0-11e6-896a-c82a261fff89.png)

**Comment by furybean** [comment]
render-header 属性应该能满足你的需求。

**Comment by jasonlam0619** [comment]
@furybean `render-header="html标签"`？试过无效。怎么用来的？找不到 api 文档😂

**Comment by Leopoldthecoder** [comment]
@jasonlam0619 参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) 第三问

**Comment by jasonlam0619** [comment]
@Leopoldthecoder 参考了，也装了 babel-plugin-transform-vue-jsx 插件了。Vue api 里的 render functions 帮不了领悟怎么写 el-table 的 render-header 吧？

~~~html
<el-table-column
  prop="username"
  width="90"
  label="讲师名称"
  render-header="<i>lorem</i>()">
</el-table-column>
~~~

能否抽空指明下 render-header 到底怎么写？

**Comment by jikkai** [comment]
@jasonlam0619  http://cn.vuejs.org/v2/guide/render-function.html
Vue的文档说得挺清楚的呀

**Comment by jasonlam0619** [comment]
@jikkai 我有读过，恕我愚钝，怎么运用到 el-table 的 render-header 属性里呢？

**Comment by furybean** [comment]
@jasonlam0619  写了个例子，请参考：http://jsfiddle.net/770tasuc/

**Comment by jasonlam0619** [comment]
@furybean 谢谢！明白了。但
如果想在表头植入组件，例如 `<el-date-picker>` 日期选择器，似乎就不可能了？

**Comment by furybean** [comment]
理论上可以，用 jsx 或者参考官方文档。

**Comment by leeqqiang** [comment]
```javascript
    renderHeader: function (creatElement, { column, $index }) {
        let fields = this.fields
        let tip = fields[$index].tip

        if (tip) {
          return creatElement('div', [
            column.label,
            creatElement(
              'el-tooltip',
              {
                class: 'cell-s-tip',
                props: {
                  content: tip,
                  effect: 'dark',
                  placement: 'top'
                }
              },
              [
                creatElement('i', {
                  class: 'fa fa-question-circle'
                })
              ]
            )
          ])
        }
        else {
          return column.label
        }
    }

**Comment by mozhs** [comment]
@furybean 你好，可以通过`render-header`属性渲染全局组件到header，但是如何渲染非全局组件到header呢？

再A.vue里面的组件引入组件`<app-test></app-test>`，把`app-test`组件用`render-header`渲染时报错:
> [Vue warn]: Unknown custom element: <column-type> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

因为不是全局组件，再table header里面无法使用`app-test`

**Comment by yinzifa** [comment]
template:  
<el-table-column label="设置主推卖品" :render-header="formatColumnText" align="center" width="300">
js:
formatColumnText: function (creatElement, {column, $index}) {
                var _this = this;
                return  creatElement('div', [
                    column.label+" ",
                    creatElement('i',
                        {
                            class: 'el-icon-warning'
                        }
                    )
                ]);
            },

**Comment by 15521054523** [comment]
![image](https://user-images.githubusercontent.com/19297519/33978406-7f221856-e0da-11e7-9e7c-d88f57d8f9e2.png)
为什么 attr 属性没有生效？

**Comment by cag2050** [comment]
这个自己写的table头部加popover的例子（使用了vue-data-tables插件），地址：https://github.com/cag2050/vue_tables_xlsx_demo/blob/master/src/views/useDataTablesComp.vue

**Comment by Yangjia23** [comment]
> @furybean 谢谢！明白了。但
> 如果想在表头植入组件，例如 `<el-date-picker>` 日期选择器，似乎就不可能了？

实现了吗

**Comment by mqliutie** [comment]
jsx写法原来可以- - 编辑器报错,我以为不行- -
