### ISSUE TITLE
[Bug Report] MessageBox automatically saves passwords when it is used repeatedly, and is not browser specific.

### ISSUE THREAD

**Issue by qinkaiyuan** [ElemeFE/element#13097]
### Element UI version
2.4.6

### OS/Browsers version
win7/chrome

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/公司内网限制无法提供](https://jsfiddle.net/公司内网限制无法提供)

### Steps to reproduce
    openMsg() {
        const h = Vue.prototype.$createElementNode
        MessageBox({
          title: '第二人确认',
          message: h('div', null, [
            h('span', '第二人确认人用户名：'),
            h('el-input', {
              props: {
                value: ''
              }
            }),
            h('span', '第二人确认人密码：'),
            h('el-input', {
              props: {
                value: '',
                type: 'password'
              }
            })
          ]),
          showCancelButton: true,
          confirmButtonText: '确定',
          cancelButtonText: '取消'
        }).then(() => {
          console.log('确定')
        })
      },

### What is Expected?
每次能创建新的弹框，用户名和密码显示为 空字符串

### What is actually happening?
每次点击按钮触发 openMsg()方法，会显示上一次输入的账号和密码，

**Comment by qinkaiyuan** [comment]
MessageBox是一个全局公用的组件么，

里面有这样类似逻辑的判断吗？如果本次传值和上次传值内容一样，则不新建组件MessageBox，而是使用上一个MessageBox组件，

猜的

**Comment by ziyoung** [comment]
添加个 key。https://jsfiddle.net/zy576pme/ 
请仔细阅读文档。http://element-cn.eleme.io/#/zh-CN/component/message-box#zi-ding-yi

**Comment by ziyoung** [comment]
https://jsfiddle.net/zy576pme/

**Comment by ziyoung** [comment]
http://element-cn.eleme.io/#/zh-CN/component/message-box#zi-ding-yi

**Comment by qinkaiyuan** [comment]
> http://element-cn.eleme.io/#/zh-CN/component/message-box#zi-ding-yi

thanks
