### ISSUE TITLE
[Feature Request] Minimize and drag Dialog

### ISSUE THREAD

**Issue by zsoltFocus** [ElemeFE/element#13101]
### Existing Component
Yes

### Component Name
Dialog

### Description
Hello,

It would be nice to have an Attribute to enable Dialog component minimization (and maximization). It could be to the side of the screen (selectable which side) or in place (floating).

I am also pulling this `vue-element-dialog-drag` package to enable Draggable option, but it would be nice if it would work out of the box.

Thank you very much.

Regards.

**Comment by ziyoung** [comment]
It's easy to add drag feature.  https://jsfiddle.net/jk0e6g7u/9/
We have no plan to support this.

**Comment by ziyoung** [comment]
related #12802
