### ISSUE TITLE
Can show-overflow-tooltip of [Feature Request] table components provide the number of selected rows?

### ISSUE THREAD

**Issue by zwmmm** [ElemeFE/element#13100]
### Existing Component
是

### Component Name
table

### Description
table 组件的 show-overflow-tooltip 在内容溢出是会显示... 并且鼠标悬浮展示tips，这是一个非常棒的功能，但是有时候一行内容就隐藏对用户而言看见的内容太短，是否考虑增加一个参数可以控制大于多少行时才溢出隐藏

**Comment by coffeeyen** [comment]
这个是利用css的text-overflow属性, 能影响的只是父的宽度和文本的宽度, 所以要控制内容长度, 要么增加父宽度, 要么减少字号, 在同样宽度下显示更多的字.

**Comment by ziyoung** [comment]
这种高度定制化的组件，自己设置 Table-column Scoped Slot 实现。
