### ISSUE TITLE
[Feature Request] parse HTML in el-popover

### ISSUE THREAD

**Issue by bgadiel** [ElemeFE/element#13105]
### Existing Component
Yes

### Component Name
el-popover

### Description
Hi,
I am using render-header to create custom headers in el-table:

`<el-table-column :render-header="renderCustomHeader">`

```
renderCustomHeader(h, {column, $index}) {
        return h('span', [
          h('span', {
            domProps: {
              innerHTML: column.label
            }
          }),
          h('el-popover', {
              props: {
                placement: 'top',
                trigger: 'hover',
                content: this.getHeaderTooltip(column.label)
              },
            },
            [
              h(
                'span',
                {
                  slot: 'reference',
                  class: 'tooltip-icon-white',
                  style: 'font-size: 11px; margin-left: 7px;'
                },
                ''
              )]
          )
        ]);
      },
```

My getHeaderTooltip contains HTML tags.
Is there a way to parse content as HTML in content (I tried to use domProps without luck)?

Thanks.

**Comment by ziyoung** [comment]
The `content ` of the popover is expected to be a String. If you want to custom content, you can use slot.
 It's painful to write render functions, I recommend you use JSX. https://vuejs.org/v2/guide/render-function.html#JSX

**Comment by bgadiel** [comment]
thank you for replying.
As you can see from my example, I already use slot.
Lets ignore the render function. How would you use slot in this simple
example?
https://jsfiddle.net/zmxhgbfo/
