### ISSUE TITLE
el-table支持多列过滤？

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1311]
如题，请问是否有机会支持

**Comment by furybean** [comment]
现在的表头过滤功能应该默认就是多列的，你可以自己试试。

**Comment by njleonzhang** [comment]
@furybean 我的意思是第一行是独立的 ，每个cell里是一个input，用作本列的过滤。按照目前的设计好像并不能实现。

**Comment by furybean** [comment]
目前筛选的设计不是这样，理论上一个功能也不会设计两种入口。
