### ISSUE TITLE
[Bug Report] Upload component selects files, the raw.lastModified attribute in file is gone

### ISSUE THREAD

**Issue by willeweit** [ElemeFE/element#13118]
### Element UI version
2.4.8

### OS/Browsers version
win10/ie11

### Vue version
2.5.2

### Reproduction Link
[http://jsrun.net/uahKp/edit](http://jsrun.net/uahKp/edit)

### Steps to reproduce
Select File > > Print File > > through on-preview callback to view file attribute

### What is Expected?
the lastModified attribute is included in the file.raw attribute.

### What is actually happening?
Now the lastModified attribute is missing.

**Comment by willeweit** [comment]
Why is it always deleted automatically

**Comment by ziyoung** [comment]
@willeweit Please provide a correct link.

**Comment by willeweit** [comment]
@ziyoung http://jsrun.net/uahKp/edit  由于JSFiddle不支持 IE11，所以改换这个地址

**Comment by ziyoung** [comment]
IE11 这么神奇的，对 [createObjectURL](https://developer.mozilla.org/zh-CN/docs/Web/API/URL/createObjectURL) 支持不太好。https://stackoverflow.com/questions/45142722/url-createobjecturlblob-not-creating-proper-url-in-ie-11

**Comment by willeweit** [comment]
@ziyoung 上传没问题，就是这个标识没了。暂时做排重，麻烦了^_^
