### ISSUE TITLE
When [Bug Report] generates table locking columns, the X axis scroll bar is covered.

### ISSUE THREAD

**Issue by daai123** [ElemeFE/element#13112]
### Element UI version
2.4.8

### OS/Browsers version
win7/全浏览器

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/daai123/dm9gys1k](https://jsfiddle.net/daai123/dm9gys1k)

### Steps to reproduce
进入页面 下拉框在列锁定部分无法拖动

### What is Expected?
是由于index.js生成table时z-index 顺序覆盖导致；
多次调试 发现 只要把 class为 ：1、hidden-columns；  2、el-table__header-wrapper；3、el-table__body-wrapper is-scrolling-left；4、el-table__footer-wrapper；5：el-table__fixed的div生成顺序改为：1、hidden-columns；3：el-table__fixed ； 3、el-table__header-wrapper；4、el-table__body-wrapper is-scrolling-left；5、el-table__footer-wrapper；便可完美解决

### What is actually happening?
是由于index.js生成table时z-index 顺序覆盖导致；
多次调试 发现 只要把 class为 ：1、hidden-columns；  2、el-table__header-wrapper；3、el-table__body-wrapper is-scrolling-left；4、el-table__footer-wrapper；5：el-table__fixed的div生成顺序改为：1、hidden-columns；3：el-table__fixed ； 3、el-table__header-wrapper；4、el-table__body-wrapper is-scrolling-left；5、el-table__footer-wrapper；便可完美解决

**Comment by daai123** [comment]
望采纳 希望新版的index.js调整div生成顺序

**Comment by daai123** [comment]
望采纳 希望新版的index.js调整div生成顺序

**Comment by daai123** [comment]
或者有更好的解决方案

**Comment by ziyoung** [comment]
Duplicate of #12666

**Comment by ziyoung** [comment]
链接坏掉了，跟 12666 很像。合并到一起了。
要是方案可行，提 pr 吧。
