### ISSUE TITLE
Can [Feature Request] provide a new feature for the cascader component to click on the right-hand arrow icon next to the label in the menu to redisplay the submenu, which is helpful for the change-on-select to select any level of menu feature

### ISSUE THREAD

**Issue by Gmle7** [ElemeFE/element#13124]
### Existing Component
是

### Component Name
cascader

### Description
目前的触发方式click和hover都不太适合change-on-select特性，尤其是在不选择最后一级菜单的时候，需要点击组件外部才可以，有点影响用户体验。或者用另外一种方式：在选择完最后一级菜单的时候，不要关闭浮窗，开发者可以自己写一个确定按钮，你们提供按钮也行，会更贴合目前的样式风格。

**Comment by ziyoung** [comment]
把 `expand-trigger` 设置为 hover，也不存在你说的这个问题。https://jsfiddle.net/025j4f6v/

另外，这种交互也太奇怪了，我们目前不打算实现该功能。

**Comment by webInRoad** [comment]
I also have this problem, if the user switches to other options (blur), as the value in the text box is changed, clicking on the other position of the page will still trigger the blur event. I hope to change the value in the text box when the user clicks the option

**Comment by coffee4code** [comment]
`this.$refs['your-cascade-comp'].toggleDropDownVisible()` working properly.
