### ISSUE TITLE
[Feature Request] How to add transition animation to the el-progress width el-progress

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/element#13120]
### Existing Component
是

### Component Name
el-progress

### Description
I add 
```
.content{
  /deep/ .el-progress-bar__inner{
           -webkit-transition: width 1s;
           -moz-transition: width 1s;
           -ms-transition: width 1s;
           -o-transition: width 1s;
           transition: width 1s;
           border-radius: 0px;
         }
}
```
hope to add transition style to the progress, but not work

reproduce in fiddle:
[https://jsfiddle.net/Yanni_Jia/v3zk0md9/](https://jsfiddle.net/Yanni_Jia/v3zk0md9/)

**Comment by ziyoung** [comment]
It works. https://jsfiddle.net/v3zk0md9/2/
![kapture 2018-10-23 at 15 42 29](https://user-images.githubusercontent.com/12947422/47344136-5c075880-d6da-11e8-946a-472f9094339c.gif)

You can make a pr to add this feature.

**Comment by feichangtutu** [comment]
wow, thank u .
so I have to add some trigger?
