### ISSUE TITLE
[Bug Report] when the table has two or many filters, how, filters

### ISSUE THREAD

**Issue by yuanyuanshen** [ElemeFE/element#13126]
### Element UI version
2.4.8

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/yyshen_11/5vos0fdr/11/](https://jsfiddle.net/yyshen_11/5vos0fdr/11/)

### Steps to reproduce
(1) 日期筛选 随便选一个
（2）家和公司筛选随便选一个
（3）点击清空日期筛选
（4）clearFliter的方法会清除所有筛选

### What is Expected?
clearFliter只清除日期的筛选

### What is actually happening?
clearFliter的方法会清除所有筛选

**Comment by ziyoung** [comment]
目前是不支持。clearFliter 函数应该可以接收参数。

**Comment by coffeeyen** [comment]
其实也可以做到这个效果
https://jsfiddle.net/5vos0fdr/17/
