### ISSUE TITLE
Watch el-input, when use paste to change el-input V-model, V-model didn't work

### ISSUE THREAD

**Issue by Amyuan23** [ElemeFE/element#13133]
### Element UI version
2.4.8

### OS/Browsers version
win10 /chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mkz56jpn/](https://jsfiddle.net/mkz56jpn/)

### Steps to reproduce
直接粘贴（ctrl v）一串字符之后，el-input框没有清空。手动输入是可以按照条件清空输入框的。

### What is Expected?
清空el-input框

### What is actually happening?
v-model里面的值请空了，但是el-input框没有清空，原生的input框是可以的

**Comment by ziyoung** [comment]
使用 nextTick。Vue 在 diff 的时候认为输入前与输入后值一样（都是空），导致 input 输入框内容没有同步。https://jsfiddle.net/mkz56jpn/1/
