### ISSUE TITLE
[Feature Request] Switch vs Radio trigger keys consistency

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#13136]
### Existing Component
Yes

### Component Name
Switch, Radio

### Description
Switch input trigger with **enter key** -> https://github.com/ElemeFE/element/blob/31d31d904ddaf267951af63f9a537f07cd1dbfdb/packages/switch/src/component.vue#L20
Radio input triggers with **space key** -> https://github.com/ElemeFE/element/blob/31d31d904ddaf267951af63f9a537f07cd1dbfdb/packages/radio/src/radio.vue#L15

I think both should be space key. Reason is enter triggers form submit.

**Comment by stranger26** [comment]
I think this could be made as an attribute to allow user to decide if *space key* or *enter key* should be used. This will not only not break support for existing trigger keys, and will allow customisation for different use cases. (Such as using switch input as standalone component will make sense to have enter trigger key, while using it in a long form will not, as pointed out)

**Comment by ziyoung** [comment]
ElRadio is similar to native radio. You can switch by the arrow key. For native radio, space and enter key are not supported. https://jsfiddle.net/h5m4n6zL/1/

**Comment by stranger26** [comment]
Thank you for the example, @ziyoung ! Some observations I made from it are:

1. The native radio is focused collectively (can't focus to next option, thus only arrow keys switching).

2. I can't use arrow keys when I tab focus on ElRadio unless I click on one of the options.
