### ISSUE TITLE
[Bug Report] form label did not honor global size config

### ISSUE THREAD

**Issue by awuliu** [ElemeFE/element#13130]
### Element UI version
2.4.8

### OS/Browsers version
windows 10 / chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/c6Lut3ow/1/](https://jsfiddle.net/c6Lut3ow/1/)

### Steps to reproduce

1 Vue.prototype.$ELEMENT = { size: 'mini' };
2 form label font-size is bigger than input controls font-size

### What is Expected?
form label font-size equals input controls font-size

### What is actually happening?
form lable font-size is bigger than input controls font-size

**Comment by ziyoung** [comment]
It's not an Element bug.  The font size of label doesn't change. You can set font size by overwriting css.
