### ISSUE TITLE
[Feature Request] Can I init or change the width of the the width?

### ISSUE THREAD

**Issue by chxuzzu** [ElemeFE/element#13135]
### Existing Component
是

### Component Name
table

### Description
I need to change the width of the table's column on different scrren, I had try to add style for the "th" and "td", but it have no effect. So can I init or change the width of the table column like the "layout" component?

**Comment by coffeeyen** [comment]
set the 'width'  attribute of el-table-column

**Comment by chxuzzu** [comment]
Thanks for your comment, what should I do if I want to set the column's width is "200px" on desktop and "100px" on mobile?

**Comment by coffeeyen** [comment]
> Thanks for your comment, what should I do if I want to set the column's width is "200px" on desktop and "100px" on mobile?

you can check width of the page, then set column width.
for example:
```javascript
let w = window.innerWidth || document.body.clientWidth;
let colWidth = 200;
if(w <= 768){
  colWidth = 100;
}
...
```
if you want set it when page width dynamically change, you can do this on 'resize' event

```javascript
//add listener when component is created
window.addEventListener("resize", this.handleResize);
...
//and do not forget remove it before you destroy component
window.removeEventListener("resize", this.handleResize);
```

**Comment by ziyoung** [comment]
@chxuzzu It should work for you.
