### ISSUE TITLE
[Feature Request] How does the upload component of the elementUI echo the image queried and support modification?

### ISSUE THREAD

**Issue by Bertwindwang** [ElemeFE/element#13144]
### Existing Component
Yes

### Component Name
图片上传组件

### Description
想要通过upload图片上传组件回显接口返回的图片，并支持重新修改与删除~~

**Comment by ziyoung** [comment]
请仔细查看文档，这些功能都是支持的。

**Comment by Bertwindwang** [comment]
已经仔细看了文档，发现了，待上传的就是可以回显查询的数据
