### ISSUE TITLE
[Bug Report] Select BUG: Multiple Select can not hide dropdown when click arrow icon when set filterable attribute

### ISSUE THREAD

**Issue by Lee-Tanghui** [ElemeFE/element#13140]
### Element UI version
2.4.8

### OS/Browsers version
MacOs/Chrome newest

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6694/](https://jsfiddle.net/mmx38qxw/6694/)

### Steps to reproduce
1. use <el-select>
2. set `multiple` and `filterable` attribute both
3. click arrow icon to show dropdown
4. click arrow icon to hide dropdown

### What is Expected?
dropdown not be hidden

### What is actually happening?
dropdown should be hidden

**Comment by ziyoung** [comment]
It's not a bug. ElSelect is waiting for you to type something when it's is focused.

**Comment by Lee-Tanghui** [comment]
> It's not a bug. ElSelect is waiting for you to type something when it's is focused.

So it is such a design that user click arrow icon can not hide dropdown menu when ElSelect is focused? I do think it is not a good design, coz not expect usual habits

**Comment by zxzhgk** [comment]
可以尝试下，开启多选，再开启搜索，此时要想关闭只能点击页面其他地方才能关闭，这个交互很诡异
