### ISSUE TITLE
[Feature Request] date component supports multiple selections

### ISSUE THREAD

**Issue by lichenhao** [ElemeFE/element#13148]
### Existing Component
是

### Component Name
 el-date-picker

### Description
使用多选而不是区间类型可以配合`disabled-date`配置日期排除功能。如 
['2018-10-01', '2018-10-16'] 排除 ['2018-10-03', '2018-10-13', '2018-10-15']

**Comment by ziyoung** [comment]
通过 disabledDate 做更加灵活一点。这个功能我们暂不打算支持。
