### ISSUE TITLE
[Feature Request] Thumbnail picture and description in search results

### ISSUE THREAD

**Issue by matthagemann** [ElemeFE/element#13155]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
Is there a way to show a thumbnail picture and/or a 2nd line for description in each search result element? Our app is heavily content-based with imagery, and having this extra information for search results would be very helpful.

**Comment by ziyoung** [comment]
You can use scoped slot. It should work for you. http://element-cn.eleme.io/#/en-US/component/input#custom-template
