### ISSUE TITLE
[Bug Report] ElSelect - multiple select component with line-height cause a height error 

### ISSUE THREAD

**Issue by hxlyd** [ElemeFE/element#13153]
### Element UI version
2.4.8

### OS/Browsers version
Mac / Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/hxlyd/36y4g5ow/34/](https://jsfiddle.net/hxlyd/36y4g5ow/34/)

### Steps to reproduce
1、set multiple property and small size for the select;

2、set line-height for body；

3、the height calc error；

4、i think below line and the `resetInputHeight ` method cause this problem:

https://github.com/ElemeFE/element/blob/f23c63c5c2e84c7f4bac3c23591223b8067ded00/packages/select/src/select.vue#L871

### What is Expected?
height right

### What is actually happening?
height error

**Comment by ziyoung** [comment]
Add one more demo: https://jsfiddle.net/36y4g5ow/35/

**Comment by elfman** [comment]
这个也能算bug吗？body设置了`line-height`导致`input`盒模型的高度也变成`100px`，如果高度不是100px那正确的值应该是多少？

**Comment by blachworld** [comment]
i think is not bug. 
'line-height: 100px' css will affect getBoundingClientRect of DOM api
ElSelect height will be  the max of input hieght or el-tags height

`Math.max(
              tags ? (tags.clientHeight + (tags.clientHeight > sizeInMap ? 6 : 0)) : 0,
              sizeInMap
            ) + 'px';`
