### ISSUE TITLE
[Feature Request] TimePicker: DO NOT select current time automatically.

### ISSUE THREAD

**Issue by DeanDrake** [ElemeFE/element#13158]
### Existing Component
是

### Component Name
TimePicker

### Description
When focus in, TimePicker may pick up current time automatically. I wish this option can be closed if I want to fill in the duration of a movie or a song. 

TimePicker 组件在没有设定默认值, 起止时间区间的时候输入, 会自动选择当前的时间. 当我要填写一部电影的时长或者是音乐的时长的时, 这种自动填写当前时间的效果很不友好. 目前也没有发现能关闭这种效果的选项, 希望能添加进去. (可以参考下layui的时间选择器)

**Comment by wacky6** [comment]
自动选当前时间从 1.0 就是这样的。设计当初shi yon是用来选时间而不是时长的，要改的话等有空搞3.0再说吧。

这个要弄的话要大改，时长对数据格式和Date不兼容。（改成存毫秒数？）

取消功能我这里看是好的。

![qq20181027-201506](https://user-images.githubusercontent.com/9319556/47602074-1245a780-da25-11e8-9beb-0a6bab723f9e.gif)
