### ISSUE TITLE
Internationalization setup with webpack IgnorePlugin results to an error

### ISSUE THREAD

**Issue by abiaskosty** [ElemeFE/element#1315]
### ElementUI version
1.0.2

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.8

### Steps to reproduce
Set up internationalization with 'en' locale as described in [docs](http://element.eleme.io/#/en-US/component/i18n).

### What is Expected?
ElementUI should use 'en' locale. Webpack IgnorePlugin should not resolve 'zh-CN' locale module.

### What is actually happening?
IgnorePlugin doesn't load 'zn-CN' local (which is right) but in runtime, when page is being loaded, the code which requires 'zh-CN' locale is executed. Therefore following error is thrown to browser console:
```
Uncaught Error: Cannot find module "element-ui/lib/locale/lang/zh-CN"
```

I was able to solve this by using NormalModuleReplacementPlugin instead of IgnorePlugin.
```
new webpack.NormalModuleReplacementPlugin(/element-ui[\/\\]lib[\/\\]locale[\/\\]lang[\/\\]zh-CN/, 'element-ui/lib/locale/lang/en')
```
With this config I don't need to import 'en' locale in code.

**Comment by QingWei-Li** [comment]
Hmm, my bad. The use of `NormalModuleReplacementPlugin ` should be more appropriate than using `IgnorePlugin`. Maybe we should update the doc, what do you think?

**Comment by abiaskosty** [comment]
Definitely docs must not contain wrong configuration. I wonder what config did contributors use when they bring new languages. @henninghorn, @furybean, @riveg, @waam, @wannymiarelli do you have another solution for this issue?

**Comment by wannymiarelli** [comment]
Actually all of my projects ( in production ) run the 1.0.1 version of Element, i will try to reproduce the error tomorrow after upgrading and report back to you.

**Comment by zephraph** [comment]
I stumbled across the same issue and ended up here. The above solution worked for me as well.
