### ISSUE TITLE
[Feature Request] Cleaner source code

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#13154]
### Existing Component
Yes

### Component Name
Radio

### Description
Don't be smart, be clean. 
<img width="666" alt="screen shot 2018-10-24 at 16 40 31" src="https://user-images.githubusercontent.com/1254613/47434933-42cedc80-d7ac-11e8-8145-b22df9e089eb.png">

ref:
https://javascript.info/ninja-code

**Comment by ziyoung** [comment]
pr is welcome.
