### ISSUE TITLE
[Feature Request] TimePicker TimePicker TimePicker TimePicker TimePicker TimePicker TimePicker TimePicker TimePicker TimePicker

### ISSUE THREAD

**Issue by viveohmf** [ElemeFE/element#13163]
### Existing Component
是

### Component Name
TimePicker

### Description
TimePicker时间选择器,希望增加可支持自定义配置来选择时-分或分-秒等

**Comment by porcelainHeart** [comment]
机器人故障了啊, 这个title翻译的有毒 @ziyoung

**Comment by ziyoung** [comment]
描述清楚一点吧。

**Comment by viveohmf** [comment]
目前是只能设置HH:mm:ss时间格式，但有很多场景需求不需要选择秒数项，例如HH:mm时间格式，或不需要选择小时项，例如mm:ss时间格式。希望能增加Attributes来实现。

**Comment by viveohmf** [comment]
> 描述清楚一点吧。最好举个例子。
目前是只能设置HH：MM：SS时间格式，但有很多场景需求不需要选择秒数项，例如HH：MM时间格式，或不需要选择小时项，例如MM：SS，时间格式希望能增加属性来实现。
