### ISSUE TITLE
pagination控件 改变total属性值导致的current-page 不正确问题？

### ISSUE THREAD

**Issue by ouyangshan09** [ElemeFE/element#1316]
当前环境：
vue 2.0.5
element-ui 1.0.2
浏览器 chrome 49

代码如下:
```
<template>
        <el-button @click="testPagination">测试</el-button>
        <el-pagination
                @size-change="handleSizeChange"
                @current-change="handleCurrentChange"
                :page-sizes="pageSizeChange"
                :total="total"
                :current-page="currentPager"
                layout="sizes, prev, pager, next, jumper, ->, total"
        >
        </el-pagination>
</template>
<script>
     export default{
        data(){
            return {
                tableData: [],
                pageSizeChange: [20,40,60,80,100],
                pages: 0,
                total: 7748,
                currentPager: 1
            }
        },
        methods: {
            handleSizeChange(value){
                console.info("handleSizeChange");
                console.log(`size: ${value}`);
            },
            handleCurrentChange(value){
                console.info("handleCurrentChange");
                console.log(`page: ${value}`);
            },
            testPagination(){
                let self = this;
                self.total = 43;
            }
        },
}
</script>
```
以上代码模拟表格条件查询成功后返回数据对pagination的total值进行改变 ，在使用时先跳转到最后一页，通过testPagination方法改变total的值，会导致pagination 跳转到第3页，并触发handleCurrentChange()方法。并不是想的第1页，即使设置page属性也不管用。

请问这个是我的使用方法不对 还是本身不能这么做？

使用场景如下，改变页码和显示数量都会根据page-sizes和current-page重新加载并显示数据，在最后一页进行条件查询时，重新拿到查找后数据并并改变原有total值(和一开始没有条件查询的数量是不一致的)，该改变又触发了handleCurrentChange()方法导致 又一次请求并加载数据。

**Comment by furybean** [comment]
@ouyangshan09 我写了个在线的例子：http://jsfiddle.net/wzf1ojp9/

这个地方的逻辑是这样的，当你变更 total 的时候，Pagination 会找一个最合理的值设置为 current-page，假设你目前在第 6 页，但是你的 total 变成了一共三页，Pagination 认为最合理的值是第三页，而不是第一页，所以造成了你看到的这个现象。

**Comment by ouyangshan09** [comment]
@furybean 那要如何做 才可以到第一页？ 
目前来看 通过查询已经得到正确的数据了，并已经正确显示从第一页开始，但后面pagination 似乎会自动触发@current-change上的方法，并且里面值并不是我使用鼠标点击后的值

**Comment by ouyangshan09** [comment]
@furybean Pagination 认为最合理的值是第三页，但它又同时触发了@current-change上的方法，传入了当前页为3，对于传入的数值@current-change上的方法 无法判断正确性吧？ 这导致每次查询的结果都是最后一页，看上去蛮奇怪的

**Comment by furybean** [comment]
@ouyangshan09 是，应该允许用户重置 current-page。我看一下怎么处理最合适，今天给回复。

**Comment by furybean** [comment]
稍微修改了下例子：http://jsfiddle.net/wzf1ojp9/3/ 因为 current-pager 并不是 .sync 的，所以需要在 handleChange 里面赋值一次。

另外，需要结合 #1336 这个 PR 来解决这个问题。

**Comment by ouyangshan09** [comment]
@furybean 即使在赋值一次也无法改变，前面提到过吧。后面使用pagination时 又发现 pagination对current-page的判断逻辑有点奇怪 ，对total进行赋值改变时有以下情况：
1、总数（total） <  当前选中页（current-page）*  每页显示个数（page-size）时 
current-page 总是最后一个，即使对current-page 也没用
2、总数（total）>= 当前选中页（current-page）*  每页显示个数（page-size）时 
current-page可以被改变，不进行赋值操作时，保持原样

**Comment by furybean** [comment]
@ouyangshan09 需要 #1336 的 PR 才能正常执行。

**Comment by furybean** [comment]
Fixed in #1336，等待下一个版本即可。

测试用例见此：https://github.com/ElemeFE/element/pull/1336/files#diff-25f403ea7680c6f4c3d65baa48ab5d57R96
