### ISSUE TITLE
[Bug Report] value is not the first day of week in DatePicker week type

### ISSUE THREAD

**Issue by thelastto** [ElemeFE/element#13164]
### Element UI version
2.4.8

### OS/Browsers version
mac / chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/thelastto/zpahvywL/](https://jsfiddle.net/thelastto/zpahvywL/)

### Steps to reproduce
1. run code in https://jsfiddle.net/thelastto/zpahvywL/
2. select a week
3. wrong value

### What is Expected?
value should be the first day of week

### What is actually happening?
value is the second day of week

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/12320#issuecomment-412078551
