### ISSUE TITLE
[Bug Report] paging component status update exception

### ISSUE THREAD

**Issue by hgrourou** [ElemeFE/element#13167]
### Element UI version
2.4.8

### OS/Browsers version
win7   chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/网络封禁,上不去这个网页](https://jsfiddle.net/mmx38qxw/网络封禁,上不去这个网页)

### Steps to reproduce
代码如下  <el-pagination :current-page.sync="pager.currentPage" :page-size="pager.pageSize"
        layout="total ,prev, pager, next, jumper"
        ref="page"
        :total="pager.totalCount" @current-change="doSomeThing">
      </el-pagination>

第一步:pager.currentPage = 1

第二步: 点击第三页,然后跳转到第三页

第三步:此时如果搜索,手动设置pager.currentPage = 1,并显示第一页的数据

第四部:再点击第三页不会触发current-change事件

### What is Expected?
触发current-change事件

### What is actually happening?
没有触发current-change事件

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
