### ISSUE TITLE
[Bug Report] el-input use problem summary

### ISSUE THREAD

**Issue by chongyue110** [ElemeFE/element#13168]
### Element UI version
2.4.8

### OS/Browsers version
win10/谷歌70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6705/](https://jsfiddle.net/mmx38qxw/6705/)

### Steps to reproduce
1, 输入多个 e ,在往后面输入任何内容将不会触发 change 事件,切无法获取到原始输入内容,暴露的事件 api 又远远不够,类似 keyup, keydown 等等原生的无法设置,组件没有暴露

### What is Expected?
1, 限定只能输入一个 e 或者不允许输入 e
2, 开发者可以获取到原始输入内容方便进行处理
3, 暴露原生事件

### What is actually happening?
1, 可以输入多个 e 切输入多个 e 之后将不会在触发change 事件
2, 开发者无法获取到原始输入内容
3, 许多原生事件无法使用,暴露的事件 api 又远远不够使用
4, 包含elementUI 的许多表单组件都存在这样的问题, 类似 select

**Comment by daofresh** [comment]
Same issue here
