### ISSUE TITLE
[Bug Report] can't change the required: true or required: false of a property of the rule in real time, set it from true to false, and the red asterisk of the required entry can't be removed

### ISSUE THREAD

**Issue by s-jingli** [ElemeFE/element#13172]
### Element UI version
2.4.8

### OS/Browsers version
win10,谷歌浏览器，IE11

### Vue version
2.5.17

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
1,设置页面：
<el-form class="demo-ruleForm"   ref="APPLICANTBASEINFO" :model="XzspPhkyAcceptObj.APPLICANTBASEINFO"  :rules="rules">
   <el-form-item label="身份证号:" prop="IDCARD">
     <el-input ref="sfzh" v-model="XzspPhkyAcceptObj.APPLICANTBASEINFO.IDCARD" size="small" placeholder="请输入"></el-input>
    </el-form-item>
<el-form>
2,设置js:添加data属性：
rules: {
               IDCARD: [
                    { required: true, message: '身份证号必须填写', trigger: 'change' },
                    { min: 15, max: 18, message: '15~18位身份证号', trigger: 'change' }
                ]
}
3,mounted里手动修改rules里IDCARD的值
   this.rules.IDCARD[0] = { required: false, message: '身份证号必须填写', trigger: 'change' }
4，发现验证规则已修改，但必填项的红色星号仍然存在。

### What is Expected?
当修改required:false时，必填项的红色星号消失，
当修改required:true时，必填项的红色星号出现，

### What is actually happening?
当修改required:false时，但必填项的红色星号仍然存在。

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
