### ISSUE TITLE
[Bug Report] el-select selects multiple window jitter.

### ISSUE THREAD

**Issue by cmlgzhang** [ElemeFE/element#13173]
### Element UI version
2.4.6

### OS/Browsers version
win 10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6711/](https://jsfiddle.net/mmx38qxw/6711/)

### Steps to reproduce
多选的时候会出现窗口抖动

### What is Expected?
不需要窗口抖动

### What is actually happening?
出现窗口抖动

**Comment by ziyoung** [comment]
无法重现。难道是跟 QQ 浏览器有关系？

**Comment by DeanDrake** [comment]
chrome 正常, QQ 浏览器确实会出现抖动的异常现象.

**Comment by abisuq** [comment]
@ziyoung 
可能需要把[这里](https://github.com/ElemeFE/element/blob/5b32ec426dda88858d5e3c85f260e14e73a035ab/packages/select/src/select.vue#L641)取高度的方法换成`getBoundingClientRect().heigt`,



related issue: https://github.com/ElemeFE/element/issues/8731

**Comment by Alex-Ifax** [comment]
@ziyoung 
Hi!
Can't read chinees, so may be I missed something.
But bug is easy reporducable now  on http://element.eleme.io/#/en-US/component/select if select several options in multilple select (leave dropdown open) and change zoom  - I've got a bug on 33% anytime. In my app it reproducies on meny other zooms.

please, fix it asap.

**Comment by sunchenguang** [comment]
> @ziyoung
> 可能需要把[这里](https://github.com/ElemeFE/element/blob/5b32ec426dda88858d5e3c85f260e14e73a035ab/packages/select/src/select.vue#L641)取高度的方法换成`getBoundingClientRect().height`,
> 
> related issue: #8731

it seems solve the problem.

**Comment by YuzhiZhang** [comment]
官网例子，Chrome 设置缩放比例为90%或者其他非100%可以复现bug，望修复
