### ISSUE TITLE
When [Bug Report] Pagination page initializes content each time, the page number is set to the first page.

### ISSUE THREAD

**Issue by ovarte** [ElemeFE/element#13179]
### Element UI version
2.4.8

### OS/Browsers version
chrome 68

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/bt5Ly8a4/16/](https://jsfiddle.net/bt5Ly8a4/16/)

### Steps to reproduce
点击其他页码后，初始化页面，设置页面的页码为1，而显示的页码不能跳转到第一页

### What is Expected?
点击页面初始化 方法，页码数在第一页

### What is actually happening?
点击页面初始化 方法，页码数不在第一页

**Comment by porcelainHeart** [comment]
你需要对`current-page`属性使用`.sync`修饰符
这是一个很久远的问题, 也算不上是bug, 具体原因可以查阅pagination组件的相关代码
暂时使用这种方式实现你要的功能

https://jsfiddle.net/bt5Ly8a4/18/

**Comment by ziyoung** [comment]
怀疑是你使用上的问题：https://jsfiddle.net/bt5Ly8a4/19/

**Comment by ziyoung** [comment]
Thanks you @porcelainHeart
