### ISSUE TITLE
When [Bug Report] el-table components are using fixed, the internal components of table cannot be focus.

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#13186]
### Element UI version
2.4.9

### OS/Browsers version
win10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/wukon/mmx38qxw/6728/](https://jsfiddle.net/wukon/mmx38qxw/6728/)

### Steps to reproduce
1. 点击第2行,激活文本框
2. 点击 focusItem 按钮, 使 第2行文本框被激活

 将fixed属性移除掉后再重复上面的操作,可以得到期待的行为
https://jsfiddle.net/wukon/mmx38qxw/6727/

### What is Expected?
第2行 文本框被激活

### What is actually happening?
第2行 文本框没有被激活

**Comment by zsedcbm** [comment]
https://jsfiddle.net/wukon/mmx38qxw/6728/
执行的效果:
![fail](https://user-images.githubusercontent.com/5986396/47600767-e14f7d80-d9f8-11e8-88a2-7f2dc323992d.gif)

https://jsfiddle.net/wukon/mmx38qxw/6727/
执行的效果(期待的效果): 
![success](https://user-images.githubusercontent.com/5986396/47600768-e1e81400-d9f8-11e8-83ed-74c697bcc989.gif)

**Comment by ziyoung** [comment]
Duplicate of #10588

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/10588#issuecomment-379460140
