### ISSUE TITLE
[Bug Report] official website documents can not be opened for a long time, nobody cares?

### ISSUE THREAD

**Issue by imhuzi** [ElemeFE/element#13194]
### Element UI version
2.4.9

### OS/Browsers version
mac 10.14/69.0.3497

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
http://element-cn.eleme.io/

### What is Expected?
官网应该正常呀？

### What is actually happening?
打开空白提示：  https://cdn.jsdelivr.net/npm/vue-router@2.7.0/dist/vue-router.min.js
文件请求不到
![image](https://user-images.githubusercontent.com/785921/47611684-feda2100-daa4-11e8-8622-0820667f36fa.png)
在这个cdn官方确实也找不到这个文件
![image](https://user-images.githubusercontent.com/785921/47611691-29c47500-daa5-11e8-848a-5f0ac2acb181.png)

**Comment by ingria** [comment]
Works fine for me. Seems like the problem is in your provider.

**Comment by ziyoung** [comment]
你自己网络的问题。

**Comment by weihomechen** [comment]
I got this problem too.
