### ISSUE TITLE
[Bug Report] el-dialog: ESC keypress target is document body

### ISSUE THREAD

**Issue by ingria** [ElemeFE/element#13199]
### Element UI version
2.4.9

### OS/Browsers version
*

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6732/](https://jsfiddle.net/mmx38qxw/6732/)

### Steps to reproduce
1. Open the Fiddle
2. Press ESC key
3. Modal shows the event target (`HTMLBodyElement`)

### What is Expected?
Event target should be contained in the modal element (`el-dialog__wrapper`), not document body.

For example of correct behavior, click on the dropdown element and press ESC. Alert shows `HTMLSpanElement`.

### What is actually happening?
Event target is `HTMLBodyElement`

**Comment by ziyoung** [comment]
I think it's not a bug.
When you click the dropdown, the dropdown element is focused. If the key is pressed, the target of keydown event is HTML element.

I write a simple demo https://jsfiddle.net/mtj7kco8/

**Comment by ingria** [comment]
If you have some other action binded to Esc key (say global hotkey) and you are pressing Esc to close the modal, the event will be propagated to the top of the page. As result, it will trigger that other action.
