### ISSUE TITLE
[Bug Report] bug that element-ui's select selector fails to search correctly after injecting the filter attribute to turn on searchable

### ISSUE THREAD

**Issue by 872022610** [ElemeFE/element#13190]
### Element UI version
2.0.10

### OS/Browsers version
windows10 / chrome 版本号67.0.3396.99

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/872022610/pen/wYOWeV](https://codepen.io/872022610/pen/wYOWeV)

### Steps to reproduce
      在输入框用win10自带的中文输入法输入拼音出现汉字后，如果使用键盘上方的数字键或者空格键选择目标汉字，select选择器会正确的搜索出结果。但是当使用鼠标点击来选取目标汉字时，即使下拉框中有匹配的数据，选择器也会提示无匹配数据。但是当用中文输入法输入英文并用鼠标进行选择时，则不会出现任何问题。
      尝试在element-ui官网上运行最新版本的选择器（element-ui 2.4.8），同样的操作，当用鼠标选取汉字时选择器则会对输入栏的数据变化毫无反应，而且用中文输入法输入英文并用鼠标进行选择时，也会出现选择器对输入栏的数据变化毫无反应的问题。

### What is Expected?
选择器会正确的渲染出结果  

### What is actually happening?
选择器提示无匹配项

**Comment by 872022610** [comment]
it may be that the selector connot listen correctly to the input method's  mouse click operation, I thought....

**Comment by ziyoung** [comment]
@872022610 跟这个问题有点类似 #11844。
把 demo 中用到的 element 版本升级到最新，然后再确定该问题是否存在。
我这边没法重现，你可以录个 GIF 图。

**Comment by 872022610** [comment]
@ziyoung 
  我用element的官网上最新版本的Demo测试，chrome 67.0.3396.99 +win 10，输入框对鼠标的点击毫无反应

![test](https://user-images.githubusercontent.com/31399723/47639910-522f9a80-db9d-11e8-96b9-0675d73a829a.gif)

**Comment by ziyoung** [comment]
@872022610 这真是诡异的问题。
换个其他输入法呢？比如搜狗输入法。对了，Chrome 浏览器竟然也会出这种问题。IE 什么的表现如何。😂

**Comment by 872022610** [comment]
@ziyoung 
分别换了一台搜狗输入法的电脑以及qq输入法的电脑，在chrome下访问国内的element的官网，2.4.8版本下都是同样的问题，但是用edge有的电脑正常，有的电脑不正常。。。另外我访问国外的element官网，发现最新版本是2.4.9，但是还是有同样的问题，而且不管是哪台电脑哪个游览器，2.4.9版本都会出现无法监听到鼠标点击的问题。。。

**Comment by ziyoung** [comment]
这么神奇的吗？😅

**Comment by 872022610** [comment]
@ziyoung 确实挺神奇的。。。这个问题感觉和游览器有关

**Comment by liuhuaxia** [comment]
还有我有个疑问，vue自带的v-model以上的这几种操作它都能检测到变化，中文输入法的也是汉字出来了v-model值才变化，为啥不直接监听v-model的值，而是用@input，@compositionstart，@compositionupdate，@compositionend，@keyup.native来进行繁琐的判断，上面这几种情况是@keyup.native这个事件不会触发

**Comment by ziyoung** [comment]
@liuhuaxia 看一下这个 pr https://github.com/ElemeFE/element/pull/10517
添加这个就是避免中文输入时，触发 input 事件。

但是我刚刚新建个 demo，输入中文时也不存在上述问题。😅https://jsfiddle.net/7v6kj598/
> vue自带的v-model以上的这几种操作它都能检测到变化
这个特性是什么时候添加的？

**Comment by ziyoung** [comment]
@liuhuaxia 看一下这个 pr https://github.com/ElemeFE/element/pull/10517
添加这个就是避免中文输入时，触发 input 事件。

但是我刚刚新建个 demo，输入中文时也不存在上述问题。😅https://jsfiddle.net/7v6kj598/
> vue自带的v-model以上的这几种操作它都能检测到变化
这个特性是什么时候添加的？

**Comment by ziyoung** [comment]
element 使用的 Vue 版本是 2.5.2。可以升级一波了。

**Comment by liuhuaxia** [comment]
你们监听的是@input事件，这个输中文的时候有问题，v-model一直都可以的

**Comment by ziyoung** [comment]
> 还有我有个疑问，vue自带的v-model以上的这几种操作它都能检测到变化，中文输入法的也是汉字出来了v-model值才变化，为啥不直接监听v-model的值，而是用@input，@compositionstart，@compositionupdate，@compositionend，@keyup.native来进行繁琐的判断，上面这几种情况是@keyup.native这个事件不会触发

@viveohmf 这样做应该可以避免这个问题，并且代码也会简单很多。😂我再理一理代码。

**Comment by wacky6** [comment]
@viveohmf @ziyoung `composition{Start,End}` 是因为： https://github.com/ElemeFE/element/issues/11665 https://github.com/ElemeFE/element/issues/10611

但是原 issue 里面的问题我在 mac 的输入法没法复现，不排除是个别浏览器和输入法的问题；
