### ISSUE TITLE
The [Bug Report] Select selector shows the exception in the selected item.

### ISSUE THREAD

**Issue by SpringHgui** [ElemeFE/element#13201]
### Element UI version
2.4.9

### OS/Browsers version
win10 chrome

### Vue version
2.5.17

### Reproduction Link
[https://springhgui.github.io/element_select.html](https://springhgui.github.io/element_select.html)

http://jsfiddle.net/SpringHgui/esu3cbnp/

### Steps to reproduce
1.打开重现链接
2.对第二个选择框切换选择

### What is Expected?
1.未选择前，显示未选择
2.选择框选择完毕显示的lable与选择的项显示不符

### What is actually happening?
始终显示最后一个项的lable，即使初始化时未选择任何项

**Comment by porcelainHeart** [comment]
请提供jsfiddle的重现代码, 而不是编译后的版本 #

**Comment by porcelainHeart** [comment]
仔细阅读select组件的文档, 当value是对象类型时, 必须指定value-key字段

具体用法如下: http://jsfiddle.net/esu3cbnp/1/
