### ISSUE TITLE
[Feature Request] How can el-select achieve the same option multiple times?

### ISSUE THREAD

**Issue by frontendwq** [ElemeFE/element#13204]
### Existing Component
是

### Component Name
el-select

### Description
How can el-select achieve the same option multiple times? （在多选的情况下multiple ，el-select 是否可以实现同一个选项被选中多次，如果可以，怎么实现）

**Comment by ziyoung** [comment]
你这个功能一点通用性都没有，我们不打算实现。

不过你在项目里可以通过 `collapse-tags` 来**模拟**这个功能。
