### ISSUE TITLE
[Bug Report] Form can not verify nested prop with '' (DASH)

### ISSUE THREAD

**Issue by Sora233** [ElemeFE/element#13211]
### Element UI version
2.4.9

### OS/Browsers version
Ubuntu 18.04 / Chrome 69.0.3497.100（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6739/](https://jsfiddle.net/mmx38qxw/6739/)

### Steps to reproduce
jsfiddle链接点击run，在两个输入框中输入任意值，第一个正确校验，第二个校验显示不能为空。

### What is Expected?
两个输入框均校验正确

### What is actually happening?
第二个输入框校验显示不能为空，实际上不为空。

**Comment by porcelainHeart** [comment]
prop命名问题, 不要使用横线即可, 把`test-1` 替换为 `test_1`可以正常使用

这里是一个demo:  https://jsfiddle.net/mmx38qxw/6740/

**Comment by Sora233** [comment]
> prop命名问题, 不要使用横线即可, 把`test-1` 替换为 `test_1`可以正常使用
> 
> 这里是一个demo: https://jsfiddle.net/mmx38qxw/6740/

现在是换_解决了，这里会转成kv再传给别处，这样就是没法区分横线和下划线，实际场景这里的值要做成xml标签。

**Comment by porcelainHeart** [comment]
> > prop命名问题, 不要使用横线即可, 把`test-1` 替换为 `test_1`可以正常使用
> > 这里是一个demo: https://jsfiddle.net/mmx38qxw/6740/
> 
> 现在是换_解决了，这里会转成kv再传给别处，这样就是没法区分横线和下划线，实际场景这里的值要做成xml标签。

不要直接在html里使用这个带横线的key即可, 你非要用横线, 也可以通过其他的字段来关联

**Comment by Sora233** [comment]
'~'这些符号也不行，so不认定是bug的话，close issue plz. @porcelainHeart

**Comment by Sora233** [comment]
顺便再贴一个workaround，把原来的verify去掉，el-form-item加一个is-required的class来显示必填标志，:rules规则手写一个validator高阶函数，把prop校验没法正确拿到的值传给外层函数，eg.
```
<el-form-item :rules="{validator: emptyValid(xxx)}" class="is-required"> </el-form-item>

var emptyValid = function(true_value) {
                var warpper = function (rule, value, callback) {
                    value = true_value;
                    if (value === '') {
                        callback(new Error('关键字不能为空'));
                    } else {
                        callback();
                    }
                };
                return warpper
            };
```

**Comment by ziyoung** [comment]
在JavaScript中，标识符只能包含字母或数字或下划线（“_”）或美元符号（“$”），且不能以数字开头。`test-1 ` 不能被正常解析。你这边对数据处理一下吧。
