### ISSUE TITLE
[Bug Report] el-date-picker-- types is the problem of dates selection.

### ISSUE THREAD

**Issue by lanleiming** [ElemeFE/element#13212]
### Element UI version
2.4.9

### OS/Browsers version
windows google

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/q4pvboyg/](https://jsfiddle.net/q4pvboyg/)

### Steps to reproduce
当type为dates时，没有选中的样式

### What is Expected?
期望type为dates时，也支持选中。

### What is actually happening?
当type为dates时，没有选中的样式

**Comment by porcelainHeart** [comment]
因为dates的取值是每一天的0点整,
你传入的默认值是当前时间,
与0点不同 所以没有应用选中样式
如果要默认选择当天,
默认值请设置为 `new Date(new Date().setHours(0,0,0,0))`

这里是一个demo: https://jsfiddle.net/q4pvboyg/1/
