### ISSUE TITLE
[Bug Report] 当table使用fixed="right" 固定操作列时，当列比较少时会出现多一列，样式错乱

### ISSUE THREAD

**Issue by 347154468** [ElemeFE/element#13220]
### Element UI version
2.4.9

### OS/Browsers version
mac10.14 chrome70.0.3538.77

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/qo0s4afp/](https://jsfiddle.net/qo0s4afp/)

### Steps to reproduce
直接运行上述demo可见

### What is Expected?
期待表格不错位

### What is actually happening?
实际表格错位

**Comment by liuchuzhang** [comment]
@347154468  这是你把左边列 `width` 都写死了，table 非固定的宽度还不够整体的宽度，右边固定中间空白，这并不是多出了一列。

**Comment by porcelainHeart** [comment]
所有的 `width` 都改为 `min-width` 即可

**Comment by ziyoung** [comment]
不是 bug。参考楼上两位给出的方案。
