### ISSUE TITLE
[Bug Report] (some Google browsers) files take a long time to upload and open up Computer Resource Manager

### ISSUE THREAD

**Issue by mingugu** [ElemeFE/element#13225]
### Element UI version
2.4.9

### OS/Browsers version
无

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/k9rxa6yu/](https://jsfiddle.net/k9rxa6yu/)

### Steps to reproduce
1，使用文件上传组件el-upload; 
2，有些谷歌浏览器打开电脑资源管理器需要大于5秒的时间（是要做浏览器兼容操作吗？）

### What is Expected?
打开电脑资源管理器快些

### What is actually happening?
打开电脑资源管理器很慢

**Comment by runtop** [comment]
升级谷歌浏览器

**Comment by mingugu** [comment]
> 升级谷歌浏览器

升级了，不慢了，应该是跟谷歌浏览器版本有关，谢啦！
