### ISSUE TITLE
[Bug Report] (some Google Browsers) files take a long time to upload and open up the computer resource manager

### ISSUE THREAD

**Issue by mingugu** [ElemeFE/element#13223]
### Element UI version
2.4.8

### OS/Browsers version
无

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、使用文件上传组件 el-upload;
2、有些谷歌浏览器打开电脑资源管理器需要大于5秒的时间（是要做浏览器兼容操作吗？）

### What is Expected?
打开电脑资源管理器快些

### What is actually happening?
打开电脑资源管理器很慢

**Comment by ziyoung** [comment]
这个不一定是 element 的bug 吧。或者是你电脑性能不够好，打开控制台太多。
