### ISSUE TITLE
[Feature Request] uploads pictures to increase compression requirements

### ISSUE THREAD

**Issue by zongzmz** [ElemeFE/element#13228]
### Existing Component
Yes

### Component Name
el-upload

### Description
上传图片是不是可以增加一个 是否开启压缩的功能？比如给出 开启压缩、压缩多少大小之内、压缩的图片质量等接口开放？

**Comment by ziyoung** [comment]
自己编写 http-request 来处理吧。我们暂时不打算支持该功能。
