### ISSUE TITLE
[Bug Report] issues about tree deployment nodes

### ISSUE THREAD

**Issue by Higginshuangjing** [ElemeFE/element#13230]
### Element UI version
2.4.8

### OS/Browsers version
版本 70.0.3538.67（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1） 选取例子： 默认展开和默认选中 https://jsfiddle.net/api/post/library/pure/
2） :default-expanded-keys="[2]"
3） 修改data数据结构为：  data2: [{
          id: 1,
          label: '一级 1',
          children: [{
            id: 4,
            label: '二级 1-1',
            children: [{
              id: 9,
              label: '三级 1-1-1'
            }, {
              id: 10,
              label: '三级 1-1-2'
            }]
          }]
        }, {
          id: 2,
          label: '一级 2',
          children: [{
            id: 5,
            label: '二级 2-1'
          }, {
            id: 6,
            label: '二级 2-2'
          }]
        }, {
          id: 3,
          label: '一级 3',
          children: [{
            id: 2,
            label: '二级 3-1'
          }, {
            id: 8,
            label: '二级 3-2'
          }]
        }]

========> 将id为3的对象children的id改成2，会发现默认展开的是2个节点

### What is Expected?
只展开父节点 id = 2

### What is actually happening?
只展开父节点 id = 2 
也展开了children id = 2的节点

因为实际项目中出现了children 的id 跟 父 id重复的问题，很焦灼~  请问怎么解决 哭z~

**Comment by coffeeyen** [comment]
别用数据中的id字段作为id呗, 自己保证id唯一性

**Comment by ziyoung** [comment]
> 别用数据中的id字段作为id呗, 自己保证id唯一性

@Higginshuangjing
