### ISSUE TITLE
[Bug Report] If the computed time in the computed property is long, el-select's label does not display right property.

### ISSUE THREAD

**Issue by 909173** [ElemeFE/element#13231]
### Element UI version
2.4.9

### OS/Browsers version
win10/ chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/turai/em76khbc/72/](https://jsfiddle.net/turai/em76khbc/72/)

### Steps to reproduce
Prepare a list that takes time to calculate in the list displayed by el-option and put it in computed.

### What is Expected?
The correct expected result is that label is correctly displayed in the upper part el-select and the lower part el-select.

### What is actually happening?
I made a variable that determines the item of el-option in the computed item of vue.js.
If the calculation time to determine the computed variable is long, it seems that the value displayed in el-select is not the value of label, but the value of value is chosen.

The elapsed time of the elapsed portion of the reproduction item pasted on the link takes time to filter.

On the other hand, since the el-option in the lower part is simply returning the value stored in data, the calculation time is short.

For this reason, label is not displayed in el-select in the upper part, and label appears correctly in el-select in the lower part.

**Comment by csvwolf** [comment]
Emmmm，can you get more additional details for Steps to reproduce like screenshots? I think the performance is expected

**Comment by 909173** [comment]
I found a mistake in my code.
Since there is no value to reference in the list, it is common not to display it. That is a my careless mistake.
This is not my bug but my mistake. I am sorry I opened a place like this. It will be helpful if you close this page.
