### ISSUE TITLE
[Feature Request] When will the table component go out of the remote filtering mode? The current filtering mode is very small in most cases. When remote filter mode will be added into the component 'el-table'?

### ISSUE THREAD

**Issue by yiidot** [ElemeFE/element#13244]
### Existing Component
是

### Component Name
el-table

### Description
在开发过程中，经常会使用到表格列筛选这个功能，当前element的筛选只能从table中已存在的数据进行筛选，而无法从服务器上获取新的符合筛选条件的数据，希望能出一个远程筛选的模式。

**Comment by Lynn-cc** [comment]
同求。现在只能自己去加一个表头的popover内塞el-select来做，真的很难受。。。
