### ISSUE TITLE
[Bug Report] Inconsistent performance between the official environment and the local the

### ISSUE THREAD

**Issue by Sliect** [ElemeFE/element#13243]
### Element UI version
2.4.9

### OS/Browsers version
win10/chrome67

### Vue version
2.5.17

### Reproduction Link
[https://github.com/Sliect/element-demo/blob/master/issue.md](https://github.com/Sliect/element-demo/blob/master/issue.md)

### Steps to reproduce
element/examples/play/index.vue 
```
<el-row>
    <el-button>默认按钮</el-button>
    <el-button type="primary">主要按钮</el-button>
    <el-button type="success">成功按钮</el-button>
    <el-button type="info">信息按钮</el-button>
    <el-button type="warning">警告按钮</el-button>
    <el-button type="danger">危险按钮</el-button>
</el-row>
```

### What is Expected?
There is a space between inline-block.

### What is actually happening?
There are no spaces between inline-block

**Comment by Sliect** [comment]
I think it might be the role of webpack.demo.js, because the same css and js files are imported, the effect is different.

**Comment by Sliect** [comment]
![image](https://user-images.githubusercontent.com/26275750/47768973-259e8e80-dd15-11e8-8db4-c944f83c91f6.png)

**Comment by Sliect** [comment]
![image](https://user-images.githubusercontent.com/26275750/47769015-4961d480-dd15-11e8-9d60-67bc2a61e604.png)

**Comment by ziyoung** [comment]
You need use [normalize.css](https://necolas.github.io/normalize.css/).

**Comment by Sliect** [comment]
The spaces that appear here are due to indentation, but there is no space in the official environment. I am sure this has nothing to do with normalize.css

**Comment by Sliect** [comment]
I got it! 
```
preserveWhitespace: false
```
I am sure that this attribute plays a role.
