### ISSUE TITLE
The [Feature Request] date time picker cannot remove the bottom control block.

### ISSUE THREAD

**Issue by SirZhangL** [ElemeFE/element#13240]
### Existing Component
是

### Component Name
DateTimePicke

### Description
点击日期后仍需点击确定按钮才能选择时间   期待的行为：可以去掉底部控制拦   点击日期即选择

**Comment by ziyoung** [comment]
你应该直接使用 date-picker 而是 date-time-picker，date-time-picker 交互确实是这样。
