### ISSUE TITLE
[Bug Report] [el-table] displays old images when table data has been updated.

### ISSUE THREAD

**Issue by BkunS** [ElemeFE/element#13253]
### Element UI version
2.4.5

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/BkunS/nbmhuj9s/](https://jsfiddle.net/BkunS/nbmhuj9s/)

### Steps to reproduce
Click Update Button to update data in table, images could take several seconds to load. Before new image is loaded, the table is displaying new data with old images.

### What is Expected?
The table should NOT continue to display old image while table data being updated and new image is still being download. The image slot should go blank when there's an update in url.

### What is actually happening?
The image stays the same and will be swapped after new image finished downloading. This will cause table displaying new table text data with old images data during the loading period of new images.

**Comment by ziyoung** [comment]
@BkunS specify key for image https://jsfiddle.net/nbmhuj9s/1/

**Comment by BkunS** [comment]
@ziyoung Thank you so much!!
