### ISSUE TITLE
[Bug Report] NavMenu can not memorize the state of submenu when it is unfolded.

### ISSUE THREAD

**Issue by squallliu** [ElemeFE/element#13258]
### Element UI version
2.4.9

### OS/Browsers version
macos mojave / chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/9prca0us/](https://jsfiddle.net/9prca0us/)

### Steps to reproduce
1、展开submenu不激活任何一个menuitem
2、收起菜单
3、展开菜单

### What is Expected?
展开的submenu保持原来的状态

### What is actually happening?
原来展开的submenu状态丢失

**Comment by csvwolf** [comment]
I think it's a feature instead.

Pull Request: https://github.com/ElemeFE/element/commit/5137867044e87704ae14230a0823419889f0e54b
