### ISSUE TITLE
[el-select] Limiting the number of selections

### ISSUE THREAD

**Issue by Fatih90** [ElemeFE/element#1325]
is there a way to limit the number of selection for example like this https://select2.github.io/examples.html#multiple-max
?

**Comment by Leopoldthecoder** [comment]
Fixed in #1401 . A new attribute `multiple-limit` is added.

**Comment by Fatih90** [comment]
@Leopoldthecoder multiple-limit is not working or i do something wrong please help

this is how i do it

```vue
<label for="genres">Filter by genres...</label>
<el-select placeholder="Genres" v-model="genres" multiple="true" multiple-limit="2" @change="sortByGenre">
    <el-option v-for="item in sort_by_genre" :label="item.title" :value="item.value"></el-option>
</el-select>
```

but i can still select more then 2 options

**Comment by Leopoldthecoder** [comment]
`:multiple-limit="2"`

**Comment by Fatih90** [comment]
@Leopoldthecoder correct, i found one thing the limit does not work if you place it before `@change`

so this does not work
```vue
<label for="genres">Filter by genres...</label>
<el-select placeholder="Genres" v-model="genres" multiple="true" :multiple-limit="2" @change="sortByGenre">
<el-option v-for="item in sort_by_genre" :label="item.title" :value="item.value">
</el-option>
</el-select>
```

but this works 

```vue
<label for="genres">Filter by genres...</label>
<el-select placeholder="Genres" v-model="genres" multiple="true" @change="sortByGenre" :multiple-limit="2">
<el-option v-for="item in sort_by_genre" :label="item.title" :value="item.value">
</el-option>
</el-select>
```

**Comment by Leopoldthecoder** [comment]
That's strange...
Here's a demo with `multiple-limit` placed before `@change`, but it works: http://jsfiddle.net/leopoldthecuber/51w8v26z/

Could you provide a demo of it not working?

**Comment by nifrasbcs** [comment]
Well, Guys how to work on separate multiple-limit for each option group. I need to acheive the following selection with two group and limitations.

	<el-select v-model="filterBy[filterKey]" @change="resetFiltersValue" multiple>
		<el-option-group label="Select one" :multiple-limit=1>
			<el-option
					v-for="(item, key, index) in makeList(mainTypes[filterKey])"
					v-if="index < 3"
					:label="item"
					:value="key">
			</el-option>
		</el-option-group>
		<el-option-group label="Select multiple" :multiple-limit=0>
			<el-option
					v-for="(item, key, index) in makeList(mainTypes[filterKey])"
					v-if="index >= 3"
					:label="item"
					:value="key">
			</el-option>
		</el-option-group>
	</el-select>

How to make it possible?

**Comment by Leopoldthecoder** [comment]
@nifrasbcs I'm afraid this is not supported. Seems the only way is to divide them into two separate Selects.

**Comment by nifrasbcs** [comment]
@Leopoldthecoder Thanks for your quickest reply. I wanna single select with two groups as mentioned above. Because I'm migrating of exciting UI to element UI kit.So there is no any way to accomplish by single select?

**Comment by Leopoldthecoder** [comment]
Sorry, currently no.
