### ISSUE TITLE
新手请教一个问题

### ISSUE THREAD

**Issue by qq490507385** [ElemeFE/element#13250]
最近在看Element的源码   看到date-picker的时候有段代码理解不了。如图

![qq 20181031182944](https://user-images.githubusercontent.com/41324581/47782583-8476fe80-dd3b-11e8-8bd7-542471bf022f.png)

此代码在packages/date-picker/basic/date-table.vue     #115行

这个date是prop中的一个对象，他怎么用getFullYear()这个方法的。
我把这个代码单独出来运行就是会报错 ！！！
大神求赐教！

**Comment by Eflet** [comment]
这个date外面控件传进来的嘛，
packages/date-picker/panel/date.vue
这里传了个date进去，这个date是个js 的Date对象，有getFullYear这些方法
