### ISSUE TITLE
[Bug Report] el table is not reactive

### ISSUE THREAD

**Issue by darekmeco** [ElemeFE/element#13251]
### Element UI version
2.4.9

### OS/Browsers version
Linux/Opera

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6771/](https://jsfiddle.net/mmx38qxw/6771/)

### Steps to reproduce
Click Delete

### What is Expected?
Table has no entries.

### What is actually happening?
Nothing, but uncomment 
this.shipment.parcels = _.clone(this.shipment.parcels);
to make it works.

**Comment by BkunS** [comment]
Try deleting table items like this: this.$delete(this.shipment.parcels, scope.$index);

**Comment by ziyoung** [comment]
> Try deleting table items like this: this.$delete(this.shipment.parcels, scope.$index);
> 
> Vue recommends to use this.$set/this.$delete when you try to update items in array, so that it could pick up the changes.
> Official Doc: https://vuejs.org/v2/api/#Vue-set

@darekmeco it should work for you.
Thanks @BkunS

**Comment by chenkunlia** [comment]
how to use the this.$set?

**Comment by BkunS** [comment]
> how to use the this.$set?

It's attached to Vue instance, so it would be: this.$set(this.arrayInData, index, newVal). // this -> Vue
