### ISSUE TITLE
[Feature Request] custom theme adds global prefix

### ISSUE THREAD

**Issue by IanSean** [ElemeFE/element#13264]
### Existing Component
是

### Component Name
theme-chalk

### Description
想通过直接编译SCSS的在项目中引入多套样式, 却发现有些样式存在干扰, 原因是, 里面有些样式是通过`@at-root` 提到顶级了.  建议给引入SCSS时, 可增加一个全局的自定义主题前缀的参数.
```
.custom-theme-1 {
  @import 'element-variables-1.scss';
  @import 'common-variables.scss';
}

.custom-theme-2 {
  @import 'element-variables-2.scss';
  @import 'common-variables.scss';
}
```
建议修改: 
`theme-chalk/src/mixins/config.scss` 修改
```
$namespace: 'el' !default;
```

这样可以通过以下设置 来给所有组件加上全局的前缀
```
$namespace: 'custom-theme-1 el'
```

**Comment by ziyoung** [comment]
这个做不到。在单文件组件中元素的 class 都是带有前缀的。

**Comment by TimZhang2090** [comment]
是否可以这样修改组件sass样式，比如 `table.scss` 中：
`  @include m(scrollable-x) {
    .#{$namespace}-table__body-wrapper {
      overflow-x: auto;
    }
  }`
