### ISSUE TITLE
When the form check of the [Bug Report] composite input box is not passed, the highlight of the red box shows the error.

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#13265]
### Element UI version
0.1.0

### OS/Browsers version
window10 / 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/863oxhmg/6/](https://jsfiddle.net/863oxhmg/6/)

### Steps to reproduce
点击“提交”按钮

### What is Expected?
红色高亮显示在选择框中

### What is actually happening?
红色高亮框显示在input框中

**Comment by ziyoung** [comment]
不是 bug。错误信息是在 FormItem 元素里的，不是跟输入框对应的。这种场景可以使用 error slot 去自定义错误信息显示。
