### ISSUE TITLE
[Feature Request] TimePicker time selector, hoping to support custom properties to configure time format items.

### ISSUE THREAD

**Issue by viveohmf** [ElemeFE/element#13262]
### Existing Component
是

### Component Name
TimePicker

### Description
目前是只能默认设置HH：MM：SS时间格式，但有很多场景需求不需要选择秒数项，例如HH：MM时间格式，只需弹出 小时：分钟的选择框；或不需要选择小时项，例如MM：SS时间格式，只需弹出 分钟：秒的选择框，希望能增加属性来实现。

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by pz25925** [comment]
希望支持
