### ISSUE TITLE
[Bug Report] Opening the el-dialog and pressing tabulator key will focus html nodes out of the el-dialog

### ISSUE THREAD

**Issue by Youngtse** [ElemeFE/element#13267]
### Element UI version
2.4.9

### OS/Browsers version
macOS Sierra / Chrome 70.0.3538.77

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/jae7zw8L/](https://jsfiddle.net/jae7zw8L/)

### Steps to reproduce
1, open the el-dialog
2, press the tabulator key repeatedly

### What is Expected?
Only node in the el-dialog can be focus.

### What is actually happening?
Area out of the el-dialog can be focus, too.

**Comment by ziyoung** [comment]
It's not a bug. After pressing the tab key, element which tabinex is 1 can be focused.

**Comment by Youngtse** [comment]
> It's not a bug. After pressing the tab key, element which tabinex is 1 can be focused.

I have tried to add tabindex="-1" but it was not effective.  Bootstrap' modal with tabindex="-1" is ok.Would you mind telling me how to fix my question?
