### ISSUE TITLE
[BUG] el-input-number 初始值为null时，双击加减按钮有问题。

### ISSUE THREAD

**Issue by zhuowenli** [ElemeFE/element#1327]
### ElementUI version
1.0.2

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.5

### Reproduction Link
http://codepen.io/zhuowenli/pen/dORPrX

### Steps to reproduce
1. 当 el-input-number 初始值为 `null` 时。
2. 多点击几次，或者双击加号按钮。
3. 然后在输入框内输入数字

输入框里面的值无限鬼畜递增。🌚

**Comment by QingWei-Li** [comment]
fixed in #1330
