### ISSUE TITLE
[Feature Request] select selector multiselect mode, drop-down option if not to operate, it simply does not appear to be multiselect

### ISSUE THREAD

**Issue by chrisleung73** [ElemeFE/element#13274]
### Existing Component
是

### Component Name
ELSelect

### Description
select选择器，多选模式下，下拉选项看上去和单选是一样的，如果不去选择，不太容易看出是多选，所以是否考虑为多选添加checkbox，或者有什么办法能够不需要二次判断就能区分多选和单选

**Comment by ziyoung** [comment]
区别在于选中的值显示方式不一样。
你说的这个新功能，我们暂时不打算实现。
