### ISSUE TITLE
Table row-class-name of [Feature Request] el-table supports only one attribute.

### ISSUE THREAD

**Issue by yaozaiyu** [ElemeFE/element#13271]
### Existing Component
是

### Component Name
el-table

### Description
el-table的table row-class-name只支持一个属性，当多个属性同时作用的情况下，该如何实现？

**Comment by ziyoung** [comment]
请仔细阅读文档。
![image](https://user-images.githubusercontent.com/12947422/47893016-bbf9be00-de95-11e8-8824-4acbcd591287.png)
`row-class-name` 支持回调函数，你可以用这个。

**Comment by yaozaiyu** [comment]
我用的就是回调函数，但是return只能是一个string，object不能接受到，但是我需要两个属性在列表上

**Comment by yaozaiyu** [comment]
![image](https://user-images.githubusercontent.com/25170955/47898414-be1d4600-deb0-11e8-8a2c-2302b5e90cb2.png)

**Comment by yaozaiyu** [comment]
@ziyoung
