### ISSUE TITLE
[Feature Request] Does uploader support folder uploading?

### ISSUE THREAD

**Issue by zhangalex** [ElemeFE/element#13289]
### Existing Component
是

### Component Name
el-upload

### Description
The uploader is powerful, but my requirement is that does the plugin support directory uploading? It's likely that the chrome provided a 'webkitdirectory' attribute to support this feature. Thanks in advanced.

**Comment by csvwolf** [comment]
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

So I think support it is not a good idea.

**Comment by wacky6** [comment]
This feature is unlikely to be supported.

* No native way to select a folder (except Webkit's `webkitdirectory`). I doubt W3C will ever add folder selection feature.
* No standard / conventional way to upload a folder to backend server (e.g, archive / S3 protocol, etc.)

**Comment by zhangalex** [comment]
Thanks, guys. I am going to close the ticket.
