### ISSUE TITLE
[Bug Report] Tooltip manual display does not work.

### ISSUE THREAD

**Issue by nikkwong** [ElemeFE/element#13283]
### Element UI version
2.4.9

### OS/Browsers version
osx

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
view the page. 

### What is Expected?
Tooltip should be shown automatically when using v-model or :value, but it does not

### What is actually happening?
not showing up

**Comment by elfman** [comment]
it seems you don't set the tooltip in your demo

**Comment by csvwolf** [comment]
Emmm, it seems you forget to press `save` button?

**Comment by csvwolf** [comment]
If you want support later, reopen it please.
