### ISSUE TITLE
[Feature Request] Add Icon for file.state ="fail"

### ISSUE THREAD

**Issue by abernov** [ElemeFE/element#13281]
### Existing Component
Yes

### Component Name
Upload

### Description
For example

Hook "before-upload" return false, then in the upload list no icon visible. I can manually set fileList[idx].status ='fail'. But there is no icon for this state! Please, add icon for state "fail"

**Comment by abernov** [comment]
Then before performing hook "on-error", component do not need to delete the file from the fileList. If need it may be deleted in the hook "on-error". 

If this is not done, then such a situation is possible.
The user has set to download a huge file and leave the computer.
In case of an error, the file will silently disappear from the fileList.

**Comment by ziyoung** [comment]
> I can manually set fileList[idx].status ='fail'.

Don't do that!
When the return value of `before-upload` is false, the file won't be uploaded. You can show feedback by using Message.
