### ISSUE TITLE
[Bug Report] el-submenu dropdown isn't closing automatically when clicked outside 

### ISSUE THREAD

**Issue by georgyfarniev** [ElemeFE/element#13293]
### Element UI version
2.4.9

### OS/Browsers version
Windows 10 / Chrome Version 70.0.3538.77 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/wv4fnaro/2/](https://jsfiddle.net/wv4fnaro/2/)

### Steps to reproduce
1) Click to dropdown menu (Workspace)
2) Click outside of menu

### What is Expected?
Menu dropdown is closed, which is typical behavior

### What is actually happening?
Menu dropdown stays opened

**Comment by csvwolf** [comment]
The case will be triggerred when the setting is `menu-trigger='click'`. Will fix it later, thank you.

**Comment by georgyfarniev** [comment]
Reopened because of https://github.com/ElemeFE/element/pull/13478

**Comment by ziyoung** [comment]
ralated issue #13452

**Comment by japhfortin** [comment]
+1

**Comment by NathanBnm** [comment]
This remains unfixed. Please reopen.

**Comment by NathanBnm** [comment]
@element-bot please reopen

**Comment by NathanBnm** [comment]
For the people it can help this can be fixed by using the `v-clickoutside` directive directly on your submenu:

```vue
<template>
    <el-menu
      ref="menu"
      menu-trigger="click"
    >
      <el-submenu
        ref="submenu"
        v-clickoutside="handleClickOutsideSubmenu"
        index="1"
      >
        <template slot="title">
          Menu title
        </template>
        <el-menu-item  index="1-1">
          Menu item 1
        </el-menu-item>
        <el-menu-item index="1-2">
          Menu item 2
        </el-menu-item>
      </el-submenu>
    </el-menu>
</template>

<script>
import Clickoutside from "element-ui/src/utils/clickoutside";

export default {
  name: "Menu",
  directives: {
    Clickoutside
  },
  methods: {
    handleClickOutsideSubmenu() {
      if(this.$refs["submenu"].$el.classList.contains("is-opened")) {
        this.$refs["menu"].close("1");
      }
    }
  }
};
</script>
```
