### ISSUE TITLE
[Feature Request] It should be possible to create style options to set personal style?

### ISSUE THREAD

**Issue by a631807682** [ElemeFE/element#13297]
### Existing Component
是

### Component Name
Slider

### Description
There's no way to set personal `style` in `el-slider`, such as process bar color or background color .

希望提供背景和拖动进度的`style`的设置。
比如基础的修改颜色需求，或者特殊一点的要给分块不同的颜色，样式可能都需要动态计算。
比如这样的效果：
https://jsfiddle.net/631807682/5mxqtj1b/2/

**Comment by ziyoung** [comment]
看起来很酷。但是这种使用场景比较少，建议跟业务密切的功能可以编写组件自行实现。我们暂时不会支持该功能。

**Comment by a631807682** [comment]
```
     ....
    <div class="el-slider__runway"
      :class="{ 'show-input': showInput, 'disabled': sliderDisabled }"
      :style="runwayStyle"
      @click="onSliderClick"
      ref="slider">
      <div
        class="el-slider__bar"
        :style="barStyle">
      </div>
      ...
```
可能举的例子比较极端。
我的意思只是希望把`barStyle`和`runwayStyle`作为作为特性提供出来，或者可以添加`barClass`和`runwayClass`。
比如我整个主题色明明不是蓝色，但这里就只能用蓝色了。

**Comment by lizux** [comment]
最近，我收到了相关的需求，不过经过研究发现可以在 Slider 外部进行封装，然后覆盖组件的内置样式即可

https://ye1on.csb.app/
