### ISSUE TITLE
[Feature Request] Consider adding an HTML editor component

### ISSUE THREAD

**Issue by jesse51076008** [ElemeFE/element#13291]
### Existing Component
否

### Component Name
Editor

### Description
Consider adding an HTML editor component

**Comment by csvwolf** [comment]
Can you give us a reason why you need this?

Otherwise we won't add this.

Emmm, and by  the way, I don't agree to add the component since there is lots of mature projects like: [CodeMirror](https://codemirror.net/) or [monaco](https://github.com/Microsoft/monaco-editor)

**Comment by ziyoung** [comment]
Duplicate of #11841
