### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by sunabozu** [ElemeFE/element#133]
I'm looking at your UI library and it's amazing, one of the best I've ever seen.
But for many developers it's very hard to use it without English documentation.
Are you planing to make it or this project is not supposed to be fully international?

Sorry for not complying with your guidelines.

**Comment by Leopoldthecoder** [comment]
Hi there! I believe you are the first foreign developer to reach out to us🎉.
We are aware that the majority of the community needs an English documentation. However our team may not be able to provide one due to limited manpower.
It doesn't mean there may never be an English documentation. Actually, we have plans to ask the community to help us create the translation. We haven't started it yet but for now what we have in mind is that our team's gonna provide a translation template so that anyone interested can contribute their translation based on it. Maybe then you and your friends can get involved😊.

**Comment by Leopoldthecoder** [comment]
Now we have some updates regarding English documentation.

A professional translation team has volunteered to help us. They are well experienced in technical documentation translation and did some really awesome jobs in the past. We're excited to have them working with us.

So stay tuned😁.

**Comment by sunabozu** [comment]
I’m very glad to hear that!
On Mon, Sep 26, 2016 at 15:57, 杨奕 <notifications@github.com> wrote:
Now we have some updates regarding English documentation.

A professional translation team has volunteered to help us. They are well experienced in technical documentation translation and did some really awesome jobs in the past. We're excited to have them working with us.

So stay tuned😁.

**Comment by sunabozu** [comment]
I'm very glad to hear that!

**Comment by HerringtonDarkholme** [comment]
I wonder where is the documentation source code hosted? I can only find compiled code on gh-pages branch.

**Comment by QingWei-Li** [comment]
@HerringtonDarkholme 

here https://github.com/ElemeFE/element/tree/master/examples
https://github.com/ElemeFE/element/tree/master/examples/docs

**Comment by HerringtonDarkholme** [comment]
Thanks! Looking forward to English translation. If the directory structure for English docs is available, I can also help to translate it.

**Comment by Leopoldthecoder** [comment]
@HerringtonDarkholme Thanks!

But I think the translation team has already distributed all the docs to its members. Maybe later you can help review the translated docs.

Again, thanks for asking!

**Comment by shentao** [comment]
The components look really awesome! Looking forward to the English documentation!

**Comment by richstandbrook** [comment]
Fantastic great to hear English docs are on the way. Seems like an amazing library, really good work!

**Comment by kivervinicius** [comment]
Awesome lib!

**Comment by scoufman** [comment]
Hi,

Thank you for this beautiful library. One thing I wanted to ask, although not totally related to the documentation but a translation question, do you have any plans to add the ability to use multiple languages in some UI components or the ability to change specific texts through props? (e.g. Datepicker).

Thank you in advance.

**Comment by Leopoldthecoder** [comment]
@scoufman Most components have configurable texts (e.g. placeholder in `input` component) so you can change them through props. Few doesn't but we will add multiple languages to them later.

**Comment by elisangelacarla** [comment]
下午好你的圖書館是偉大的，我不知道如果用英文的文件已經可用？
Xiàwǔ hǎo nǐ de túshū guǎn shì wěidà de, wǒ bù zhīdào rúguǒ yòng yīngwén de wénjiàn yǐjīng kěyòng?

**Comment by Leopoldthecoder** [comment]
@elisangelacarla Not yet. Hopefully it will be done this month. Once it's done, we will close this issue.

**Comment by rightaway** [comment]
Anything people who don't speak chinese can do to help?

**Comment by Leopoldthecoder** [comment]
@rightaway Indeed yes, you can help review the translated docs.

We've created the `EnglishDocs` branch, and now the translation team has pushed some of their work to it: https://github.com/ElemeFE/element/tree/EnglishDocs/examples/docs/en-us .

Anyone, especially native English speakers, please feel free to review these docs by creating new pull requests.

We appreciate your contribution.

**Comment by Leopoldthecoder** [comment]
Hi everyone, today we are thrilled to announce that English docs for Element is online.

After nearly two months of working with a professional translation team, we finally have all the docs translated. That being said, these docs are forged by a bunch of Chinese. I believe they can be improved in a native English speaker's eyes. So feel free to contribute if you find the language we use in the docs any non-native.

Last week we released Element 1.0.0 after nine release candidates. Today, together with the English docs, we released version 1.0.1. Our community cannot thrive without you guys, so please don't hesitate to use Element today!

Thank you for your patience. We'll see you in [element.eleme.io](element.eleme.io/#/en-US).

**Comment by Bisewski** [comment]
Guys, is someone working on Sketch resources translation? Our team wants to use Element and I could translate this for english if no one is working on it.

**Comment by Leopoldthecoder** [comment]
@Bisewski Great! Design resource translations are welcome. Maybe you can create a PR to https://github.com/ElementUI/Resources when you finish.

Thank you in advance. If you have any questions, just ask.
