### ISSUE TITLE
The table row-class-name of [Feature Request] el-table only supports one attribute. How can it be implemented when multiple attributes work simultaneously? Callback function can only be one attribute of return!

### ISSUE THREAD

**Issue by yaozaiyu** [ElemeFE/element#13309]
### Existing Component
是

### Component Name
el-table

### Description
el-table的table row-class-name只支持一个属性，当多个属性同时作用的情况下，该如何实现？回调函数也只能return一个属性！

**Comment by island205** [comment]
https://jsfiddle.net/island205/9rtm5dxb/1/ 用空格隔开试试？

**Comment by yaozaiyu** [comment]
@island205 谢谢，不好意思，打扰了
