### ISSUE TITLE
[Bug Report] In IE environment, when the date component changes the binding model, the view is not updated, but the data is actually updated.

### ISSUE THREAD

**Issue by kaerhasnoballs** [ElemeFE/element#13306]
### Element UI version
2.3.7

### OS/Browsers version
Windows 10 / IE 11(11.345.17134.0)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/dfeyt1sc/](https://jsfiddle.net/dfeyt1sc/)

### Steps to reproduce
1、el-date-picker组件绑定mode——'currentDate', 某个组件A绑定click事件去修改这个model值，但是出发A组件click事件之后，el-date-picker组件组件没有更新，但是通过控制台监视，数据是变化了，这个时候focus一下el-date-picker组件，让其的日期选择面板显示一下再blur，之前修改的值就更新上去了，之后再去出发组件A的click事件，el-date-picker组件就可以正常更新了
2、如果在最开始就先focus->blur el-date-picker组件，就可以正常update el-date-picker组件

### What is Expected?
model值变化的时候组件刷新

### What is actually happening?
model值变化的时候组件没有刷新成对应修改之后的值

**Comment by wacky6** [comment]
可能和这个有关 https://github.com/ElemeFE/element/issues/8548
