### ISSUE TITLE
[Feature Request] NavMenu: support of using more than one menu

### ISSUE THREAD

**Issue by georgyfarniev** [ElemeFE/element#13300]
### Existing Component
Yes

### Component Name
ElMenu

### Description
Currently, when using two menus, which is common use-case (for example, top menu and left sidebar menu), it's not possible to track current selected menu item correctly. If two menus have different links, then if we click first menu, and then another one, link on the first menu will stay selected, so we will have incorrect duplicate menu selection. There's two obvious ways to implement this behavior:

1) Monitor **$router** if prop router is set to true and track current menu item. In my opinion, it is the best option, but may require little reworking of internal logic of **ElMenu** as it seems from the quick look into the code.

2) At least add method for **ElMenu** (for example, **reset()**) to clear current selection, and leave this task to code using menu. For example, we can subscribe to menu click event and reset another menu in this case. Below is the link that reproduce lack of this feature

Steps: 
1) Click menu item on top menu
2) Click menu on the left
3) Observe that top menu item is still selected, but current item has changed and only left menu contains it

https://jsfiddle.net/81uhm47o/2/

**Comment by atilkan** [comment]
Your example suffers from errors. Can you correct them first.

**Comment by georgyfarniev** [comment]
@atilkan thank you for your notice. Fiddle has been updated: https://jsfiddle.net/81uhm47o/2/

**Comment by yesworld** [comment]
@atilkan I'm interested in the same question. #13554

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/49007395-5522a880-f1a6-11e8-9953-9c60e4e8e324.png)
You mean only one menu should be selected?

**Comment by georgyfarniev** [comment]
@ziyoung yes, exactly. It doesn't make sense to have focus on both menus for 99% cases.

**Comment by georgyfarniev** [comment]
@csvwolf may I know why this issue was closed without any explanation?

**Comment by csvwolf** [comment]
@georgyfarniev Since it's an issue last year and no one reply it, I think if you still need it, can you update the example to latest element version?

**Comment by georgyfarniev** [comment]
> @georgyfarniev Since it's an issue last year and no one reply it, I think if you still need it, can you update the example to latest element version?

If no one reply, it doesn’t mean that issue doesn’t exist. Issue still persists, however I updated example: https://jsfiddle.net/5b6vqtuy/

P.S: are you in charge for element ui? I have few questions about it, I asked other developers but they probably don’t have time to reply me.
