### ISSUE TITLE
Rolling carton when [Bug Report] Table components are too large

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#13315]
### Element UI version
2.4.9

### OS/Browsers version
版本 70.0.3538.77（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
无

### Steps to reproduce
在表格data属性对应的集合中加入数据，直到count>=1000

### What is Expected?
还能正常滚动，不卡顿

### What is actually happening?
数据量在600~1000左右时，上下滑动，出现严重卡顿

**Comment by ziyoung** [comment]
Duplicate of #6089

**Comment by ziyoung** [comment]
使用虚拟列表吧。https://github.com/ElemeFE/element/issues/6089#issuecomment-353519906
