### ISSUE TITLE
[Feature Request] Trigger native mobile select options

### ISSUE THREAD

**Issue by Danielguang** [ElemeFE/element#13312]
### Existing Component
是

### Component Name
Select

### Description
When I used elementUI to do responsive website.I perfer to using native mobile select instead of using windows. Can you please add a options to trigger mobile select

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1
