### ISSUE TITLE
table中存在固定列时，在360极速浏览器和火狐中滚动滚动条，表格会有错位现象。

### ISSUE THREAD

**Issue by ZHUSIYU15358** [ElemeFE/element#13310]
table中存在固定列时，在360极速浏览器和火狐中滚动滚动条，表格会有错位现象。
![default](https://user-images.githubusercontent.com/37064867/48049888-16b75080-e1db-11e8-908d-9398121e0189.jpg)

**Comment by ZHUSIYU15358** [comment]
并没有～

**Comment by haryzxw** [comment]
@ZHUSIYU15358  我昨天测试的时候，发现只有当表格横向滚动条、纵向滚动条（设置了el-table的height属性）以及el-table-column有show-overflow-tooltip属性的时候，在safari测试才有错位现象。饿了么版本为@2.3.9。最后是去掉了show-overflow-tooltip属性，强行正常了

**Comment by ZHUSIYU15358** [comment]
我这里没有设show-overflow-tooltip，高度的话，是必须有的，不然数据太多，去掉高度，肯定就没有错位现象了。

**Comment by cjy816618** [comment]
我也遇到这个问题。2022都没有修复这个问题

**Comment by haryzxw** [comment]
> 我也遇到这个问题。2022都没有修复这个问题

哈哈哈，这属于陈年旧code了
