### ISSUE TITLE
popover 滚动视图后样式错误

### ISSUE THREAD

**Issue by think2011** [ElemeFE/element#1331]
![image](https://cloud.githubusercontent.com/assets/3961388/20589131/711d3182-b255-11e6-98da-b3d9ffdc6f87.png)

http://element.eleme.io/#/zh-CN/component/popover
在这个页面中，点击 删除 按钮后不关闭，滚动到最底下，再滚上去，箭头指示样式没有恢复。

**Comment by baiyaaaaa** [comment]
没看出来。。。箭头指示样式有什么问题

**Comment by QingWei-Li** [comment]
这个是 Chrome 的问题，改了几次没法绕过去，也不影响使用，先这样吧。
