### ISSUE TITLE
Can [Feature Request] add a special class to the last level?

### ISSUE THREAD

**Issue by xunzou** [ElemeFE/element#13327]
### Existing Component
是

### Component Name
tree

### Description
希望给最后一级tree增加一个class。来控制最后一级的样式。

**Comment by ziyoung** [comment]
自定义 `render-content` 来实现。

**Comment by xunzou** [comment]
> 自定义 `render-content` 来实现。

可能我说的不是太清楚，我是希望能再最后一级的 
el-tree-node__children   上面增加样式，render-content好像不能实现
