### ISSUE TITLE
引入CSS问题，按照star里面改了也是报错，请帮忙看看！

### ISSUE THREAD

**Issue by jiangchengshi2016** [ElemeFE/element#1332]
### ElementUI version
"element-ui": "^1.0.2",

### OS/Browers version
Chrome

### Vue version
"vue": "^2.1.0",

### Steps to reproduce
  "webpack": "^1.13.3" 
{
                test: /\.css$/,
                loader: 'style!css',
                exclude:  /node_modules/
            },
            {
                test: /\.(eot|svg|ttf|woff|woff2)(\?\S*)?$/,
                loader: 'file'
            },

.babelrc：
   {
  "presets": [
    "es2015",
    "stage-1"
  ],
  "plugins": [
    "transform-runtime"
  ],
  "comments": false
}

 编译报错：
     ERROR in ./~/element-ui/lib/theme-default/index.css
Module parse failed: D:\Workspace\storm\wedding\node_modules\element-ui\lib\theme-default\index.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)

**Comment by QingWei-Li** [comment]
请提供个 repo 地址

**Comment by jiangchengshi2016** [comment]
https://git.oschina.net/jiangchengshi/wedding.git

**Comment by jiangchengshi2016** [comment]
方便加个QQ吗？421156722

**Comment by QingWei-Li** [comment]
好像文档给的 css 配置并没有 `exclude: /node_modules/` 🌚
```javascript
{
  test: /\.css$/,
  loader: 'style-loader!css-loader'
}
```

**Comment by jiangchengshi2016** [comment]
sorry，加这个是因为之前报错加的，改了之后忘记去掉了，太着急了，去掉可以了，谢谢！
