### ISSUE TITLE
[Bug Report] uploaded the file suddenly wrong, after 2.4.9 issue.

### ISSUE THREAD

**Issue by fanhua1994** [ElemeFE/element#13323]
### Element UI version
2.4.9

### OS/Browsers version
Google

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
啥意思。反馈一个问题，这么麻烦

### What is Expected?
上传成功

### What is actually happening?
Uncaught TypeError: r.append is not a function
    at element.js:15131
    at Array.forEach (<anonymous>)
    at VueComponent.r (element.js:15130)
    at VueComponent.post (element.js:15080)
    at VueComponent.upload (element.js:15043)
    at element.js:15039
    at Array.forEach (<anonymous>)
    at VueComponent.uploadFiles (element.js:15038)
    at VueComponent.handleChange (element.js:15033)
    at invoker (vue.js:2029)

**Comment by ziyoung** [comment]
@fanhua1994 请提供正确的链接。

**Comment by ziyoung** [comment]
> Steps to reproduce
啥意思。反馈一个问题，这么麻烦

对用户来讲，**提 issue 是没有成本的**。但对于开发者来讲，**需要很多时间来排查**，请先把问题描述清楚。

**Comment by fanhua1994** [comment]
<el-upload
--
  | class="upload-demo"
  | ref="upload"
  | :limit="1"
  | :on-remove="handleRemove"
  | :on-success="successUpload"
  | :on-error="errorUpload"
  | :data="uploadData"
  | action="/oiw/file/uploadFile">
  | <div class="avatar">
  |  
  | <div class="uploadBtn" v-text="uploadText">上传照片</div>
  | <img id="head" v-if="isUpload" :src="imgUrl"
  | onerror="this.src='/Themes/oiw/imgs/placeholder_img.png'"/>
  | </div>
  | </el-upload>


这是前端的上传代码，上传就直接刨除了错误。
Uncaught TypeError: r.append is not a function

At element.js:15131
At Array.forEach ()

At VueComponent.r (element.js:15130)
At VueComponent.post (element.js:15080)

At VueComponent.upload (element.js:15043)
At element.js:15039

At Array.forEach ()
At VueComponent.uploadFiles (element.js:15038)

At VueComponent.handleChange (element.js:15033)
At invoker (vue.js:2029)
