### ISSUE TITLE
[Feature Request] DatePicker component need direct show in div

### ISSUE THREAD

**Issue by xujiujiu** [ElemeFE/element#13322]
### Existing Component
是

### Component Name
DatePicker

### Description
need show DatePicker don't depend on  click <input>，doesn't it realize？

**Comment by ashokkumar360** [comment]
> @xujiujiu you can show the picker by this
> 
> ```js
> this.$refs.picker.pickerVisible = true;
> ```

> but it's not working me. can you explain more details
