### ISSUE TITLE
Configuration of component props default value

### ISSUE THREAD

**Issue by crazynan** [ElemeFE/element#13330]
### Existing Component
否

### Component Name
所有组件

### Description
情景描述：比如我需要用到table表格，但是我整个后台需要的样式跟默认值不太一样，我就需要对所有这个表格进行props的配置，不方便管理。
能否做一个默认的配置文件，在引用Element UI的时候，可以自定义个配置文件，根据自己需求配置这些默认值

**Comment by island205** [comment]
可能与阿里的 Fusion 结合满足您的需求，issue 暂时关闭
