### ISSUE TITLE
[Feature Request] Can i prgrammatically clear a multiple select  ?

### ISSUE THREAD

**Issue by fatoldsun00** [ElemeFE/element#13338]
### Existing Component
Yes

### Component Name
select

### Description
Hi, i can found if i can (and how i can) totaly clear a multiple select into js code.

Can anyone help me ?

Thanks !

**Comment by georgyfarniev** [comment]
@fatoldsun00 can you please explain more clearly? You need to reset el-select with multiple option? Resetting model value should be sufficient to clear currently selected data.

**Comment by fatoldsun00** [comment]
hum... I'm a big asshole... 

Thanks a lot

**Comment by fatoldsun00** [comment]
v-model need to be [ ] or errer is handle when you try select option after reset
