### ISSUE TITLE
toggleAllSelection 无法使用

### ISSUE THREAD

**Issue by mr-wiggless** [ElemeFE/element#13348]
组件 table 中的  多选表格的 toggleAllSelection 方法无法使用，
报错未找到该方法，

**Comment by Joseph-xie** [comment]
http://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.runtime.min.js

http://cdn.jsdelivr.net/npm/vue-router@2.7.0/dist/vue-router.min.js

Ping 请求找不到主机 cdn.jsdelivr.net。请检查该名称，然后重试。

这两个地址访问失败！
