### ISSUE TITLE
[Bug Report] select remote remote search how to set the default display is value, the submitted value is ID?

### ISSUE THREAD

**Issue by fly2017313** [ElemeFE/element#13350]
### Element UI version
2.4.8

### OS/Browsers version
Mac OS、Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/fantasygm/sujkf2y3/1/](https://jsfiddle.net/fantasygm/sujkf2y3/1/)

### Steps to reproduce
在编辑表单的时候，由于因为<el-select v-model="form.parentAgent" > 即要承担显示功能，又要承担提交功能，但这2者的数据格式不一样，不知道怎么操作，请求帮助！

### What is Expected?
由于初始化给的数据格式是{"id":1,"value":"我是值1"},需求上希望显示的是文本value，同时编辑提交的数据是id，如：{"parentAgent":1}

### What is actually happening?
实际显示的是要么是 id，要么是value。请问，有没有办法让表单显示的是value，并且form存的值是id，就与最初选择候选集合的时候是一样的效果？

**Comment by ziyoung** [comment]
两种思路吧：
1. 使用 value-key 试试。
2. 或者你把提交的数据转换一下。
