### ISSUE TITLE
[Feature Request] Add swipe feature to tabs component for mobile device

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#13356]
### Existing Component
yes

### Component Name
tabs

### Description
The problem is if the tabs component has too many options or the title is too long, on mobile device it will very difficult to switch between the options (because the toggle button is too small for mobile screen). 
It's recommended to add a swipe feature to the tabs(only on the tab title bar) for mobile device.

**Comment by kfeng0806** [comment]
中文:
tabs组件中由于过多标签页或者标签页标题过长导致在移动设备中很难进行翻页操作(因为翻页按钮实在太小很不容易被正确点击)
建议在移动设备中为tabs的标题栏增加滑动翻页特性

**Comment by ziyoung** [comment]
一开始 element 不是为移动端设计的。另外加这个功能要写很多的代码（处理 touch 等一大堆事件），我们暂时没有计划去支持该功能。另外针对移动端的特别，自行实现的 tabs 组件可以做到更为轻量。
