### ISSUE TITLE
[Feature Request] el-tabs initialization, tab-bar no display.

### ISSUE THREAD

**Issue by mopkq** [ElemeFE/element#13352]
### Existing Component
是

### Component Name
el-tabs tab-bar

### Description
el-tabs initialization, tab-bar no display.

**Comment by georgyfarniev** [comment]
Can you please explain what exactly you want to achieve? If you are looking to hide tab bar, you can add custom class to el-tabs and hide it child element with class el-tabs__header. You can read more information about class binding in vue here: https://vuejs.org/v2/guide/class-and-style.html

**Comment by mopkq** [comment]
el-tabs每个nav的下划线 不显示
https://github.com/ElemeFE/element/blob/v2.4.9/packages/tabs/src/tab-bar.vue
注释以下代码 正常显示
` if (!this.$parent.$refs.tabs) return {};`
vue的版本2.5.2

**Comment by ziyoung** [comment]
@mopkq 是 bug 的话，请描述你的问题，提供重现问题的链接。如果是新功能，也描述清楚一点。

**Comment by mopkq** [comment]
![image](https://user-images.githubusercontent.com/8299029/48241616-9ed36b00-e412-11e8-8d38-1273e24f0b77.png)
@ziyoung @georgyfarniev

**Comment by ziyoung** [comment]
无法重现。
![image](https://user-images.githubusercontent.com/12947422/48459958-74652180-e807-11e8-82af-7801f127ef60.png)
你打开这个例子再验证一下： https://jsfiddle.net/hyLzc5dp/

**Comment by Sept-i** [comment]
高亮的线宽度是0，导致不显示，有什么方式能解决？，除了手动赋值宽度
