### ISSUE TITLE
[Bug Report] Table-column scoped-slot header

### ISSUE THREAD

**Issue by yantaolu** [ElemeFE/element#13351]
### Element UI version
2.4.9

### OS/Browsers version
Mac/Chrome70.0.3538.77

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
官方文档描述的：header	自定义表头的内容. 参数为 { column, $index }
实际上参数为：ƒ (a, b, c, d) { return createElement(vm, a, b, c, d, true); }，实际上是一个function，并非object

### What is Expected?
官方文档描述的：header	自定义表头的内容. 参数为 { column, $index }

### What is actually happening?
实际上参数为：ƒ (a, b, c, d) { return createElement(vm, a, b, c, d, true); }，实际上是一个function，并非object

**Comment by ziyoung** [comment]
Duplicate of #13261
