### ISSUE TITLE
Table Table-column Attributes

### ISSUE THREAD

**Issue by xushuailing** [ElemeFE/element#13359]
### Element UI version
2.4.9

### OS/Browsers version
mac/Chrome70.0.3538.77

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xslmenghuan/3Ltyzjpv/4/](https://jsfiddle.net/xslmenghuan/3Ltyzjpv/4/)

### Steps to reproduce
当 table 组件 el-table-column 设置 show-overflow-tooltip 为 true 时，如果内容过多 tooltip 的 left 会变成负数

### What is Expected?
当 table 组件 el-table-column 设置 show-overflow-tooltip 为 true 时，如果内容过多 tooltip 正常显示

### What is actually happening?
如果内容过多 tooltip 的 left 会变成负数

**Comment by ziyoung** [comment]
>  left 会变成负数

left 是指什么？描述清楚一点。

**Comment by xushuailing** [comment]
![image](https://user-images.githubusercontent.com/25056086/48243568-fe824400-e41b-11e8-8e86-13922ab069ef.png)
