### ISSUE TITLE
[Bug Report] when form-item's type is array , the resetFields method can't reset the form status

### ISSUE THREAD

**Issue by SunGuoQiang123** [ElemeFE/element#13354]
### Element UI version
2.4.9

### OS/Browsers version
macOS 10.13.6 / chrome  72.0.3602.2

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/sunguoqiang/qxs8ezmw/](https://jsfiddle.net/sunguoqiang/qxs8ezmw/)

### Steps to reproduce
1、modify the user input and modify the province value
2、click the resetForm button 
3、the user item has been reset to original value but the province value is still the modified value

### What is Expected?
array type value in form can also be reset by the resetFields method

### What is actually happening?
the array type value in form can't be reset

**Comment by ziyoung** [comment]
It's not a bug. 

> reset current field and remove validation result

According to the descript of resetFields method, the initial value of this FormItem is `provinces[index]` which is not `provinces`. So after calling resetFields method, `provinces` was not reseted.
