### ISSUE TITLE
When [Bug Report] dialog is used as component import, the use of $message is sometimes blocked by mask layer.

### ISSUE THREAD

**Issue by limili** [ElemeFE/element#13353]
### Element UI version
2.4.9

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6830/](https://jsfiddle.net/mmx38qxw/6830/)

### Steps to reproduce
dialog作为组件import时，使用$message有时候会被遮罩层遮挡

### What is Expected?
dialog作为组件import时，使用$message有时候不会被遮罩层遮挡，
同时dialog嵌套使用时，$message也应该显示在最上层

### What is actually happening?
dialog作为组件import时，使用$message有时候会被遮罩层遮挡，
同时dialog嵌套使用时，$message也有几率被遮挡，快速多点几次弹message框操作，就可以变回正常

**Comment by ziyoung** [comment]
@limili 你提供的链接是没法重现了。难道说按需加载才出现吗？
你在 https://codesandbox.io/ 建个可从重现问题的项目吧。
