### ISSUE TITLE
[Bug Report] [el-tooltip] tooltip is not visible when default value is true

### ISSUE THREAD

**Issue by Senasiko** [ElemeFE/element#13368]
### Element UI version
2.4.9

### OS/Browsers version
chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/senasiko/wa8dto6y](https://jsfiddle.net/senasiko/wa8dto6y)

### Steps to reproduce
当 tooltip 的 manual 和 value 默认都为 true 的时候，tooltip 不会显示。必须要 value 默认设置为 false，然后在 mounted 里面修改 value 为 true 才会出现。

### What is Expected?
当 tooltip 的 manual 和 value 默认都为 true 的时候 tooltip 显示。

### What is actually happening?
当 tooltip 的 manual 和 value 默认都为 true 的时候 tooltip 不会显示。

**Comment by ziyoung** [comment]
> 手动控制模式，设置为 true 后，mouseenter 和 mouseleave 事件将不会生效

设置了 manual 之后，要自行控制 tooltip 的显示与隐藏了。
如果把 tooltip 的 value 初始值设置为 true，确实有问题。https://jsfiddle.net/7w54y0b9/

**Comment by ziyoung** [comment]
这个问题不难修，但需要改动 vue-popper 这个 mixin。很多组件又依赖这个 mixin，放到 3.0 吧。可以适当的优化一下 vue-popper 。

**Comment by peakchen90** [comment]
@ziyoung 在 vue-popper.js 这个文件里监听 value 的处理函数里面，将 `this.showPopper = val` 放到 `Vue.nextTick()` 回调里面就行，不知道有其他影响没

**Comment by ziyoung** [comment]
先放到 2.7 了。找到了一种新的解决方案。tooltip 的有些代码写的挺奇怪。
