### ISSUE TITLE
[Bug Report] upload filelist URL can not download

### ISSUE THREAD

**Issue by masterLei** [ElemeFE/element#13364]
### Element UI version
2.4.9

### OS/Browsers version
chrome 52

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/L9e1vt8d/](https://jsfiddle.net/L9e1vt8d/)

### Steps to reproduce
upload组件的filelist 里面的url 虽然填写正确但点击后没有反应，没有下载文件

### What is Expected?
filelist显示的文件能够下载

### What is actually happening?
usually

**Comment by ziyoung** [comment]
不是 bug。这个功能要你自己实现的。https://scarletsky.github.io/2016/07/03/download-file-using-javascript/
