### ISSUE TITLE
[Bug Report] Cannot emit row-click event when select the text with text

### ISSUE THREAD

**Issue by chenyuncai** [ElemeFE/element#13363]
### Element UI version
2.4.9

### OS/Browsers version
MacOS Latest; Chrome Latest and all the browsers;

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6841/](https://jsfiddle.net/mmx38qxw/6841/)

### Steps to reproduce
1. bind the row-click event to el-table element
2. click the row but hold the mouse and leave the row area
3. release mouse left button

### What is Expected?
can emit the row-click event

### What is actually happening?
nothing runs

### 中文描述
表格绑定行单击时间，正常使用一切正常，但是在划词选词的时候，鼠标滑出开始点击的那一行，row-click事件未触发。

**Comment by ziyoung** [comment]
无法重现。应该是浏览器插件导致的。

**Comment by chenyuncai** [comment]
可以重现呀，我打开我百年都不用的Safari也可以重现。
就是正常情况你单击单元格会弹出alert，在单元格里正常划词也会触发，但是划词的时候将鼠标划到单元格外面去后再释放鼠标，就不会触发alert。
