### ISSUE TITLE
[Feature Request] Official site component add TOC

### ISSUE THREAD

**Issue by hengkx** [ElemeFE/element#13365]
### Existing Component
是

### Component Name
site

### Description
add `TOC`  quick access.
![image](https://user-images.githubusercontent.com/8358236/48250781-6778b480-e43a-11e8-8ac7-0516c164dc6f.png)
example:
[antd](https://ant.design/components/table/)
![image](https://user-images.githubusercontent.com/8358236/48250810-84ad8300-e43a-11e8-9081-7814fc88fab6.png)

**Comment by ziyoung** [comment]
related pr #11609

**Comment by ziyoung** [comment]
Comparing to the docs of other libraries like [vuetify](https://vuetifyjs.com/en/) or [vuesax](https://lusaxweb.github.io/vuesax/), ElementUI doc seems unfriendly. We also need to refactor doc innext major version.
