### ISSUE TITLE
[Feature Request] cascade selector loading secondary options animation

### ISSUE THREAD

**Issue by Mrli2016** [ElemeFE/element#13367]
### Existing Component
是

### Component Name
cascader

### Description
在异步加载次级选项时显示加载中动画，不然话用户体验很差 看到的是一片空白 不知道目前正在加载中 我看iview是有这个属性的

**Comment by ziyoung** [comment]
@Mrli2016 Cascader 的异步加载是通过直接修改 data 来实现的。这种功能目前来讲做不到。属于组件设计方面的问题。懒加载时，应该是通过调用钩子函数来获取数据才对。

**Comment by atmjs** [comment]
> @Mrli2016 Cascader 的异步加载是通过直接修改 data 来实现的。这种功能目前来讲做不到。属于组件设计方面的问题。懒加载时，应该是通过调用钩子函数来获取数据才对。

{  value: 'value',
    label: 'label',
    loading: true
}
数据设置留给用户来配置，cascader读取loading字段然后配置个loading图标不行？
