### ISSUE TITLE
[Bug Report] Form Number Validation still submit mix value, i.e 8abc

### ISSUE THREAD

**Issue by widiu7omo** [ElemeFE/element#13377]
### Element UI version
2.4.9

### OS/Browsers version
Chrome v70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/widiu7omo/mmx38qxw/6869/](https://jsfiddle.net/widiu7omo/mmx38qxw/6869/)

### Steps to reproduce
https://element.eleme.io/#/en-US/component/form
from that link, goto number validate, and type number with character follow, i.e 8abc. 
Form are validate that value as valid input, and it can submit even the value is mixed.
sorry for bad language

### What is Expected?
it can validate only number no matter the digit is

### What is actually happening?
may be, its validate only the first digit number. just assume. Thanks.

**Comment by porcelainHeart** [comment]
https://vuejs.org/v2/guide/forms.html#number

It is not an element bug

Maybe you should use `el-input-number`

i.e https://jsfiddle.net/mmx38qxw/6873/

**Comment by cjzZZZzzz** [comment]
官网上为啥不用 `el-input-number`

**Comment by porcelainHeart** [comment]
@cjzZZZzzz 官网的例子是为了说明如何验证数字类型, 重点在验证, 而不是用哪个表单组件, 没去考虑这个细节吧
