### ISSUE TITLE
[Bug Report] el-select not showing selected label when options are deep copied objects

### ISSUE THREAD

**Issue by kneekill** [ElemeFE/element#13373]
### Element UI version
2.3.7

### OS/Browsers version
Chrome 70.0.3538.77

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/c8auL7fk/](https://jsfiddle.net/c8auL7fk/)

### Steps to reproduce
Deep copy objects that are used for `el-option` either in `beforeMount()`, before passing it in as a prop or in computed.

### What is Expected?
`el-option :label` should be displayed after being selected.

### What is actually happening?
It is not displayed though `v-model` is being updated with `el-option :value`.

**Comment by wacky6** [comment]
Please write `headers_required` in an immutable way. Dynamically created properties are not watched / caught by Vue.

https://wecodetheweb.com/2016/02/12/immutable-javascript-using-es6-and-beyond/
