### ISSUE TITLE
[Bug Report] Carousel not working on mobile devices

### ISSUE THREAD

**Issue by invisor** [ElemeFE/element#13381]
### Element UI version
2.4.9

### OS/Browsers version
Firefox, Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/bgcj0tfu/](https://jsfiddle.net/bgcj0tfu/)

### Steps to reproduce
Just create carrousel with this parameters: autoplay="false", indicator-position="none", arrow="never"

### What is Expected?
When user swipes gallery on mobile devices it should change slides

### What is actually happening?
Nothin happening. I can see only first slide, and I haven't any way to change it

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1
