### ISSUE TITLE
[Bug Report] I introduced error in import ElemetUI from'element-ui/src'with source code.

### ISSUE THREAD

**Issue by PolanZ** [ElemeFE/element#13386]
### Element UI version
2.4.9

### OS/Browsers version
window10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Polan/eywraw8t/456105/](https://jsfiddle.net/Polan/eywraw8t/456105/)

### Steps to reproduce
import ElemetUI from 'element-ui/src' 
编译时出现了错误
```
./node_modules/element-ui/packages/table/src/table-body.js
Module parse failed: Unexpected token (33:6)
You may need an appropriate loader to handle this file type.
|     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
|     return (
|       <table
|         class="el-table__body"
|         cellspacing="0"
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/element-ui/packages/table/src/table.vue 224:0-37
 @ ./node_modules/element-ui/packages/table/src/table.vue
 @ ./node_modules/element-ui/packages/table/index.js
 @ ./node_modules/element-ui/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 webpack/hot/dev-server ./src/main.js

 还有更多
````
或者部分引入```import { ElTable } from 'element-ui/src'```也是一样

### What is Expected?
因为利用了```utils/popup```，但是又和element-ui分别同时处理z-index，这个时候就出现了层级问题
那么想用源码方式引入解决掉这个问题
请问：还有其他方式解决这样的需求吗

当然用的是webpack 3.x

### What is actually happening?

编译过程中出错

**Comment by PolanZ** [comment]
自己找到解决了
调用utils/popup，不要去调用src，调用lib下的就可以同步解决层级问题了。

**Comment by ziyoung** [comment]
> 自己找到解决了
> 调用utils/popup，不要去调用src，调用lib下的就可以同步解决层级问题了。

可以。
