### ISSUE TITLE
Can [Feature Request] add a class to pagination's jumper?

### ISSUE THREAD

**Issue by AlexZhong22c** [ElemeFE/element#13385]
### Existing Component
是

### Component Name
pagination

### Description
pagination的jumper有一个“前往”按钮，是纯文本来的，如果要修改它的文字还比较容易，但是修改它的样式就很麻烦。能不能给它加一个class就很容易控制样式。
(作为一个有click事件的按钮，hover上去的时候鼠标不是显示可点击的状态，所以我想改它的样式。而且没有样式的单纯一个text node，用户也不知道它是可点击的。)

**Comment by ziyoung** [comment]
jumper  的 DOM 结构如下所示。要修改样式，完全可以通过 CSS 来实现。
![image](https://user-images.githubusercontent.com/12947422/48388410-33e8a380-e734-11e8-973c-69745409bbb9.png)

**Comment by AlexZhong22c** [comment]
我懂了，“前往”和“页”都是可以点击的。一开始我只想在“前往”上面加个cursor:pointer，是很麻烦的。
