### ISSUE TITLE
[Feature Request] table front-end sorting paging problem

### ISSUE THREAD

**Issue by Mrli2016** [ElemeFE/element#13380]
### Existing Component
是

### Component Name
table

### Description
表格排好序后无法按照分页的参数去渲染，可以的话希望sort-change方法能排好序后返回全部数据，然后前端分页进行分割。

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by Mrli2016** [comment]
> Sorry, we have no plan to support this.

i just want the sorted data, now, sort-change function return {column, prop, order}, you can add the sorted data in it, for example: {column, prop, order, sortedDataArray}
