### ISSUE TITLE
[Bug Report] Basic multiple select widget Name length overflow

### ISSUE THREAD

**Issue by bf185003** [ElemeFE/element#13395]
### Element UI version
0.1.0

### OS/Browsers version
windows 10/ chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/0kwLcy4n/](https://jsfiddle.net/0kwLcy4n/)

### Steps to reproduce
If the widget have the below values:        
options: [{
          value: 'w1',
          label: 'SimpleBar left1'
        }, {
          value: 'w2',
          label: 'SimplePie Bottom Right yearly 1'
        }, {
          value: 'w3',
          label: 'Central Map'
        }, {
          value: 'w4',
          label: 'List by monthly'
        }, {
          value: 'w5',
          label: 'list by yearly'
        }],

Than the name will display outside of widget.

### What is Expected?
keep name inside.

### What is actually happening?
outside indeed.

![image](https://user-images.githubusercontent.com/23185348/48386541-44e1e680-e72d-11e8-834c-5cc294f36668.png)

**Comment by ziyoung** [comment]
The issue did exit. But I think option label should display all and don't lose some text.
You can see this demo: https://jsfiddle.net/o8fb0e2w/
I suggest you set width for Select.
