### ISSUE TITLE
el-upload 可否不立即上传，只获取 form-data？

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#1339]
RT。

或如何获取转换后的 form data？

**Comment by Kingwl** [comment]
好像没啥办法。。。

**Comment by jikkai** [comment]
@jasonlam0619 可以在before-upload这个钩子里获取到file，并且可以通过return false/Promise阻止上传，然后就可以在合适的时候处理获取到的file了

**Comment by baiyaaaaa** [comment]
现在还没有关闭自动上传的功能。。后续会出来

**Comment by crossingmay** [comment]
upload组件多张一起上传的时候会出问题，会只有一张能上传成功，剩下的几张进度卡在100%然后就不动。这个是组件的限制么？

**Comment by baiyaaaaa** [comment]
@crossingmay 不是，多少张的情况下会这样？我本地试不会有这个问题

**Comment by baiyaaaaa** [comment]
auto-upload will be support in 1.2, #2827
