### ISSUE TITLE
[Bug Report], when the select component sets filterable, the blur event will not respond.

### ISSUE THREAD

**Issue by msidolphin** [ElemeFE/element#13402]
### Element UI version
2.4.9

### OS/Browsers version
win10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/nbdotsyv/1/](https://jsfiddle.net/nbdotsyv/1/)

### Steps to reproduce
el-select组件设置filerable为true

### What is Expected?
能够正常响应blur事件

### What is actually happening?
不能响应blur时间

**Comment by ziyoung** [comment]
related #13067
