### ISSUE TITLE
[Bug Report] when i use router-view in el-tabs, the component's hook function trigger many times

### ISSUE THREAD

**Issue by huibinwang** [ElemeFE/element#13400]
### Element UI version
2.4.9

### OS/Browsers version
chrome 71

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/eywraw8t/457065/](http://jsfiddle.net/eywraw8t/457065/)

### Steps to reproduce
use el-tabs and v-for el-tab-pane with a array, 
put <router-view></router-view> in each el-tab-pane, 
bind tab-click event and when click which tab, trigger vue-router's push method，and then, if i have two el-tab-pane, component's hook function in  router-view will trigger many times

### What is Expected?
hook function just trigger once

### What is actually happening?
hook function just trigger many times

**Comment by dive2Pro** [comment]
This is more like a vue-router usecase issues
 tab-pane just like a normal div, use v-show to control the content visibility under the hood,  because you put router-view in a for loop, so the code semantically equivalent to this:

```
<el-tabs>
<div v-for="item in list">
  <router-view v-show="active"/> // active was computed by tab-pane, 
</div>
</el-tabs>
```

**Comment by bum-hyun** [comment]
Because of v-for, it triggers many times.
