### ISSUE TITLE
[Bug Report] Cascader component crash caused automatic refresh on Edge

### ISSUE THREAD

**Issue by AyerCai** [ElemeFE/element#13405]
### Element UI version
2.4.9

### OS/Browsers version
edge

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/gqxrfev1/](http://jsfiddle.net/gqxrfev1/)

### Steps to reproduce
连续操作选择 很容易就会组件崩溃页面卡死自动刷新。
我在页面上用了Cascader 级联获取省市区出现的频率更高 
看了看官网Select 和Cascader 也是这样的情况...

### What is Expected?
正确的选择，不会卡死自动刷新

### What is actually happening?
Select 和Cascader 卡死页面自动刷新

**Comment by AyerCai** [comment]
不清楚是不是bug= = 先放在bug下面了...

**Comment by AyerCai** [comment]
![img]http://p73nmeexj.bkt.clouddn.com/20181113_162238.gif

**Comment by ziyoung** [comment]
IE 这么多问题。忍不住想吐槽。
出现这类问题，我们也是很难处理。😅也许随着 Vue3.0 推出，我们可以逐渐放弃对 IE 的支持。

**Comment by ziyoung** [comment]
Duplicate of #11629
