### ISSUE TITLE
[Bug Report] When confirming with MessageBox, if a series of data is separated by commas in the prompt content information, it will automatically occupy a line when displaying, and the data content will exceed the scope of the pop-up window.

### ISSUE THREAD

**Issue by 1162597506** [ElemeFE/element#13409]
### Element UI version
2.4.9

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/95eqgfd2/1/](https://jsfiddle.net/95eqgfd2/1/)

### Steps to reproduce
如果数据中的逗号分隔成空格，则显示数据不会有问题。
If the commas in the data are separated into spaces, there is no problem in displaying the data.。
---------------------

The data used in the pop-up are：
您正在提交共 10 条数据到批处理队列中，其中数据为 nummchnd1,numavg1,maxamt1,numS22,amtfangcha,num123,amtnum,amtavg,maxamt,amt123456 的定时任务将被删除，确认操作？
----------------------
The code is as follows：
var Main = {
    methods: {
      open4() {
        let confirmMsg = "您正在提交共 10 条数据到批处理队列中，其中数据为 nummchnd1,numavg1,maxamt1,numS22,amtfangcha,num123,amtnum,amtavg,maxamt,amt123456 的定时任务将被删除，确认操作？"
       confirmMsg = `${confirmMsg}，确认操作？`
          this.$confirm(confirmMsg, '提示', {
            type: 'warning'
          }).then(action => {
          this.$message({
            type: 'info',
            message: 'action: '   action
          });
        });
      }
    }
  }
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')

### What is Expected?
界面中的文字和字母正常换行展示，一个字符一个字符的连接起来展示
The characters and letters in the interface are displayed in line, and a character is connected by a character.

### What is actually happening?
nummchnd1,numavg1,maxamt1,numS22,amtfangcha,num123,amtnum,amtavg,maxamt,amt123456

上面的数据单独成行展示，并且超出的弹唱的访问，超出部分的数据看不见
The above data is displayed separately, and the access beyond the singing and singing is out of sight.

**Comment by ziyoung** [comment]
不是 bug。可通过设置 CSS 来解决。https://jsfiddle.net/95eqgfd2/2/
