### ISSUE TITLE
[Bug Report] form control custom header does not display bug

### ISSUE THREAD

**Issue by miccuci** [ElemeFE/element#13412]
### Element UI version
2.3.4

### OS/Browsers version
win10/谷歌浏览器

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
按官网的文档将表格控件自定义表头部分代码应用到项目中发现表头无法显示，在jsfiddle上同样无法显示

### What is Expected?
显示自定义表头

### What is actually happening?
未显示表头

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by zhangnan000** [comment]
我也遇到了同样的问题，请问有解决吗？我是通过slot header自定义了表头，但是不生效，element-ui是2.4.8版本

**Comment by q27488** [comment]
同上，直接copy官方演示代码， table自定义hedaer不显示
win7-64位，
"vue": "^2.5.16",
"element-ui": "^2.4.1",
