### ISSUE TITLE
在firefox上  table中的el-table__empty-block的min-height: 60px;不兼容bug

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#1341]
在firefox上  table中的el-table__empty-block 的 min-height: 60px;不兼容bug

是否考虑去掉el-table__empty-block这个属性，在el-table__empty-text中设置 padding: 0 xxpx

**Comment by AaronChen2012** [comment]
是否考虑去掉el-table__empty-block这个属性，在el-table__empty-text中设置 padding: 0 xxpx

**Comment by furybean** [comment]
Fixed in #1347
