### ISSUE TITLE
[Bug Report] input-number placeholder has no effect.

### ISSUE THREAD

**Issue by DevilLeven** [ElemeFE/element#13411]
### Element UI version
2.4.9

### OS/Browsers version
所有版本

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6885/](https://jsfiddle.net/mmx38qxw/6885/)

### Steps to reproduce
F12 开发者工具。即可看到 placeholder 属性其实是绑定到了 <input> 父级的<div> 上，以至于 placeholder 不生效

### What is Expected?
为 el-input  增加 props -- placeholder 使得 input-number 的 placeholder 可以正确绑定到 input 上

### What is actually happening?
placeholder 属性其实是绑定到了 <input> 父级的<div> 上

**Comment by ziyoung** [comment]
Duplicate of #13221

**Comment by ziyoung** [comment]
fixed in #13275

**Comment by iTaster** [comment]
这个问题并没有被修复@ziyoung

**Comment by L-x-C** [comment]
@ziyoung 并没有被修复+1，默认为null时，显示的是0，把0按delete删除后，变成了placerholder效果
