### ISSUE TITLE
[Bug Report] 在table fliter中设置单选 :filter-multiple="false" 出现滚动条 用鼠标点击滚动条下拉 在滚回顶部 全部选项被影藏掉 哈

### ISSUE THREAD

**Issue by yuanyuanshen** [ElemeFE/element#13421]
### Element UI version
2.4.9

### OS/Browsers version
chorme

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/yyshen_11/rqau25fL/11/](https://jsfiddle.net/yyshen_11/rqau25fL/11/)

### Steps to reproduce
（1）table下拉筛选出现滚动条
（2）点击滚动条下拉 返回顶部
（3）发现全部这个选项变为空白

### What is Expected?
（1）table下拉筛选出现滚动条
（2）点击滚动条下拉 返回顶部
（3）发现全部这个选项正常显示

### What is actually happening?
（1）table下拉筛选出现滚动条
（2）点击滚动条下拉 返回顶部
（3）发现全部这个选项变为空白

**Comment by yuanyuanshen** [comment]
有的电脑上不能复现，如果不能复现的，我可以提供图片地址

**Comment by ziyoung** [comment]
请不要提重复的 issue。

**Comment by ziyoung** [comment]
无法重现。你录制一下 GIF 图描述你的问题。

**Comment by yuanyuanshen** [comment]
> 无法重现。你录制一下 GIF 图描述你的问题。

![bug](https://github.com/yuanyuanshen/vue-derectives/blob/master/static/table%20filter.gif)

**Comment by yuanyuanshen** [comment]
gif 图片地址 https://github.com/yuanyuanshen/vue-derectives/blob/master/static/table%20filter.gif

**Comment by yuanyuanshen** [comment]
@ziyoung

**Comment by yuanyuanshen** [comment]
为什么问题又被搁置了。。。。

**Comment by ziyoung** [comment]
@yuanyuanshen 我这边是无法重现。其他浏览器呢？

**Comment by yuanyuanshen** [comment]
正在更新 Google Chrome
版本 70.0.3538.102（正式版本） （32 位）
@ziyoung   这个是我的chrome版本，有一个同事电脑上无法复现，win10 上边

**Comment by yuanyuanshen** [comment]
@ziyoung
Google Chrome
版本 70.0.3538.102（正式版本） （32 位） win10系统
有一个同事电脑上也无法复现
刚试了firfox，没有复现
table 单选下拉，除了写死高度，有没有别的方法，可以添加滚动，或者element之后的版本支持多条自动添加滚动呢？
我看了一下，内部z-index是10000多，如果我修改z-index，是没有这个问题的，但是table的一条边会覆盖下拉列表

**Comment by ziyoung** [comment]
> 内部z-index是10000多，如果我修改z-index，是没有这个问题的

我这边一直没法重现。不过 z-index 的值怎么会这么高。
