### ISSUE TITLE
是不是可以搞一个TODO出来

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#1342]
可以把一些比较大块儿的东西列出来
然后其他人认领

**Comment by Leopoldthecoder** [comment]
可以探讨一下。我个人感觉，可能全新的组件不太容易让社区来做，已有组件的新 feature 倒是可以。

另外，用我们的主题工具做一些不一样的主题出来，这个应该可以搞。

**Comment by QingWei-Li** [comment]
标签 `contribution welcome` 就是鼓励大家做贡献嘛

**Comment by reverland** [comment]
可以看看 https://github.com/FE-Driver/vue-beauty

然而这种方式开发的东西不大敢在产品中用。。。











虽然，element-ui的bug也好多啊好多啊
