### ISSUE TITLE
[Bug Report] elementUI table can not adaptive

### ISSUE THREAD

**Issue by qiushuaichang** [ElemeFE/element#13424]
### Element UI version
2.4.9

### OS/Browsers version
windows，mac ，all browsers

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.Change the browser window, you can see that。
2.Tables don't change the width of the columns, the width of the browser, the column with more content doesn't automatically calculate the length, and the column with less content doesn't automatically get shorter。
3.The bootstrap table automatically calculates and ADAPTS to the width of the current screen and makes each column of table the most appropriate width

### What is Expected?
Expect to be able to automatically adapt each column like bootstrap table

### What is actually happening?
In fact, the elementui table cannot be self-adaptive. Even if the column width is not given, each column will be equally divided, even if one column contains a lot of content

**Comment by georgyfarniev** [comment]
As I understand from reading stakeholders comments here, element ui is not supposed to be responsive, at least for now, unfortunately. But it would be great to have that feature for table.
