### ISSUE TITLE
[Bug Report] el-col bug about responsive side

### ISSUE THREAD

**Issue by alekoshen712** [ElemeFE/element#13428]
### Element UI version
2.4.9

### OS/Browsers version
All

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6890/](https://jsfiddle.net/mmx38qxw/6890/)

### Steps to reproduce
resize the window which is in the lower right corner to 768px

### What is Expected?
the first one should be as same as the second one.

### What is actually happening?
not the same

### More.
![image](https://user-images.githubusercontent.com/19506220/48532028-a941a900-e8d9-11e8-8b83-ffa18efb351f.png)

![image](https://user-images.githubusercontent.com/19506220/48532345-feca8580-e8da-11e8-8a14-cc630925e4db.png)

**Comment by ziyoung** [comment]
@alekoshen712 pr welcome.
