### ISSUE TITLE
There is only one button in [Feature Request] el-button-group when there is no border around it.

### ISSUE THREAD

**Issue by qqcbqqkcel** [ElemeFE/element#13429]
### Existing Component
是

### Component Name
el-button-group

### Description
在判断权限时，多个按钮会退化成只有一个，导致这种问题。

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/48595546-1152c680-e990-11e8-976b-e2e6688fa994.png)
有分割线的。不太明白你的问题。

**Comment by qqcbqqkcel** [comment]
只有一个按钮时

**Comment by qqcbqqkcel** [comment]
> ![image](https://user-images.githubusercontent.com/12947422/48595546-1152c680-e990-11e8-976b-e2e6688fa994.png)
> 有分割线的。不太明白你的问题。

只有一个按钮时

**Comment by qqcbqqkcel** [comment]
![image](https://user-images.githubusercontent.com/4516585/48602381-ebd4b580-e9ad-11e8-9c3b-13302935fce6.png)
您看我这代码，在判断权限时，会出现这个组里面只有一个按钮。（查看通知邮件内容）
现在这样的处理太麻烦了。

**Comment by qqcbqqkcel** [comment]
![image](https://user-images.githubusercontent.com/4516585/48602451-250d2580-e9ae-11e8-9a2a-aa17b85833ba.png)
组里面只有一个按钮的情况下

**Comment by ziyoung** [comment]
试了一下并不存在问题，请检查一下你自己的代码。https://jsfiddle.net/15srwe7c/1/

**Comment by qqcbqqkcel** [comment]
> 试了一下并不存在问题，请检查一下你自己的代码。https://jsfiddle.net/15srwe7c/1/

不好意思，由于我对问题描述不清楚的原因耽误了您宝贵的时间。

现在我确认了一下加上plain才会出现这个问题。
