### ISSUE TITLE
弹出层中修改值，同步到父级了，但自身值却没变化。

### ISSUE THREAD

**Issue by mustify** [ElemeFE/element#13425]
### Element UI version
2.4.9

### OS/Browsers version
WINDOWS10

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce

        <el-dialog  title="<?php echo lang('Sort spec');?>" ref="dailog" :visible.sync="box2">
                <div id='muit' >
                  <div class="tile" v-for="(item,index) in ori" > 
                       <div class="tile__name drag"> {{ index }} </div>
                       <div class="tile__list">
                        <el-tag v-for="(v ,index2) in item" class="drag left"   closable @close="removeSpec(index,v)" >
                          {{ v }}  
                          <input type='hidden' :name="spec_sort_name(index,v)">
                          
                        </el-tag>  
                      </div>
                  </div>
                </div>
               <el-button @click="spec_sort_save()"  type="success" >
                      <?php echo lang('Save sort');?>
               </el-button>

        </el-dialog>
        

### What is Expected?
其中的  v-for="(item,index) in ori"  
在ori值在弹出窗口改变后，发现这个ori的值没有对应跟随变化 。

### What is actually happening?
希望与 this.ori值保持一致

**Comment by mustify** [comment]
使用 spec_sort_save 改变 了 ori的值了。

**Comment by mustify** [comment]
![image](https://user-images.githubusercontent.com/39790804/48485875-f3cd1200-e854-11e8-9ab5-2e68bc0c22c7.png)

**Comment by mustify** [comment]
![image](https://user-images.githubusercontent.com/39790804/48485939-1ceda280-e855-11e8-9e2e-3ba38021a8be.png)

**Comment by mustify** [comment]
部分代码，这个ori的值，在弹出层里面总是不对的。
        
        /**
          * 规格排序
          * @return {[type]} [description]
          */
         spec_sort_save:function(){
            var _this = this;
            this.$nextTick(function(){
                var post_data = new Array;
                $("input[name^='spec_name']").each(function(i,el){
                    post_data.push(el.name); 
                });
                $.post("<?php echo murl('muitspec/Hook/sortSpec');?>",{data:post_data,goods_id:_this.goods_id},function(res){
                  if(res.status){
                    _this.ori = res.ori; 
                    _this.$emit('ori', res.ori);

                    alert("<?php echo lang('Spec sort has changed');?>");
                  }

                },'json');
                console.log(post_data);
            });
              
         },

**Comment by mustify** [comment]
_this.ori = res.ori; 
改变了上一层的值，但里面的这个值没有同步

**Comment by mustify** [comment]
打印发现，两个数组，在上一层一直是对的，在弹出窗口，使用的ori是上一次的ori值。。。。

**Comment by mustify** [comment]
弹出层中修改值，同步到父级了，但自身值却没变化。

**Comment by mustify** [comment]
发现加入 setTimeout 就可以出来，但是这样有页面局部刷新的问题。


                   _this.ori = {};
                    setTimeout(function(){
                         _this.ori = res.ori; 
                         _this.box();
                    },'500');

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by ziyoung** [comment]
应该是使用上的问题。注意单一数据流。
