### ISSUE TITLE
[Bug Report] IE11 will show some bug when template is used, and it will not display.

### ISSUE THREAD

**Issue by chentangchun** [ElemeFE/element#13437]
### Element UI version
2.4.9

### OS/Browsers version
IE11

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6905/](https://jsfiddle.net/mmx38qxw/6905/)

### Steps to reproduce
 <el-table-column prop="IsAdmin"
                         label="管理员"
                         width="80"
                        >
            <template slot-scope="scope">
                <el-checkbox :checked="scope.row.IsAdmin" />
            </template>
        </el-table-column>
        <el-table-column prop="IsActive"
                         label="启用"
                         width="80">
            <template slot-scope="scope">
                <el-checkbox :checked="scope.row.IsActive" />
            </template>
        </el-table-column>

    <el-autocomplete v-model="form.Code"
                                         popper-class="my-autocomplete"
                                         :fetch-suggestions="peopleSearch"
                                         placeholder="请输入内容"
                                         @@select="handlePeopleSelect">
                            <template slot-scope="{ item }">
                                <div class="Code">代码：{{ item.Code }}</div>
                                <div class="Name">姓名：{{ item.Name }}</div>
                                <span class="Year">时间：{{ item.Year }}</span>
                                <hr />
                            </template>
                        </el-autocomplete>

### What is Expected?
组件能正常使用

### What is actually happening?
组件直接不显示、或者直接页面报错 此问题 只在IE11里面出现

**Comment by ziyoung** [comment]
打开控制台查看错误信息。

如果你在项目中使用的 webpack 以及 vue-loader 的话，单文件组件会被编译成 js 文件，应该不会出现这种问题。

**Comment by chentangchun** [comment]
> 打开控制台查看错误信息。
> 
> 如果你在项目中使用的 webpack 以及 vue-loader 的话，单文件组件会被编译成 js 文件，应该不会出现这种问题。

我使用的是传统的开发模式 ，没有使用的 webpack 以及 vue-loader
