### ISSUE TITLE
[Bug Report] The unlink-panels attribute of the date picker does not work

### ISSUE THREAD

**Issue by liaoYang102** [ElemeFE/element#13435]
### Element UI version
2.4.9

### OS/Browsers version
win 10 / Google Chrome(68.0.3440.106)(64位)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/kywp8d79/](https://jsfiddle.net/kywp8d79/)

### Steps to reproduce
1. Open date selection box.
2. the left and right panels will be linked.

### What is Expected?
two panels will independently switch the current month.

### What is actually happening?
Left and right panels will be linked.

**Comment by wacky6** [comment]
It's working normally. Please upload a screenshot illustrating what's going wrong.

**Comment by liaoYang102** [comment]
> 它正常工作。请上传截图，说明出现了什么问题。

![unlink-panels](https://user-images.githubusercontent.com/31953349/48593435-cb920000-e987-11e8-97ec-7accb0820b82.gif)

**Comment by liaoYang102** [comment]
> 它正常工作。请上传截图，说明出现了什么问题。

The attribute of unlink-panels does not play a role , 
But the document says that it can close the connection between panels.

**Comment by liaoYang102** [comment]
@wacky6

**Comment by ziyoung** [comment]
`unlink-panels` 属性的描述是

> 在范围选择器里取消两个日期面板之间的联动

`unlink-panels` 设置为 true 时，意味着切换到下一月时，另一个 date-picker 不切换。

**Comment by ziyoung** [comment]
行为是正常的。
![kapture 2018-11-16 at 10 41 57](https://user-images.githubusercontent.com/12947422/48594634-4a893780-e98c-11e8-82f2-ab3b44a8cd8e.gif)

**Comment by liaoYang102** [comment]
不好意思，是我理解错了，我理解为设置unlink-panels为true时，第一次选好开始日期和结束日期，第二次选择结束日期时，开始日期会默认是第一次所选择的，不用再次点击了。 @ziyoung ,谢谢了
