### ISSUE TITLE
在table控件中进行分页，如何在下一页中序号保持连续增加，而不是从1开始

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1343]
![image](https://cloud.githubusercontent.com/assets/16740731/20595676/c0d2ef8a-b275-11e6-992d-58b277b2b505.png)
![image](https://cloud.githubusercontent.com/assets/16740731/20595687/d275e346-b275-11e6-99e3-9a97f12b6a27.png)

**Comment by Kingwl** [comment]
table里面的每个item添加的时候可以加一个序号喽 然后每次操作的时候维护一下

**Comment by yuanshengchao** [comment]
嗯嗯，这个可以作为一个解决方案，就不知道会不会造成在排序的时候序号也会混乱。谢谢你，我先来试试

**Comment by Kingwl** [comment]
排序的时候肯定会乱的。。。

**Comment by yuanshengchao** [comment]
那这个解决方案就不行了

**Comment by Kingwl** [comment]
可以排序后重新加一次序号嘛

**Comment by jikkai** [comment]
感觉这个偏向业务逻辑啊……你要的可能是这个效果？
rowIndex + (currentPage - 1) * pageSizes

或者直接让后端给你生成好序号吧

**Comment by yuanshengchao** [comment]
但是使用后端乘生成好序列号会出现的效果是，排序就会出现混乱，不能每次排序还要使用后台就不方便了

**Comment by yuanshengchao** [comment]
@jikkai 对，我就是想要你写的那个效果，rowIndex + (currentPage - 1) * pageSizes，但是这个该怎么植入到table这个组件里面的type="index"中呢?

**Comment by yuanshengchao** [comment]
谢谢上面的各位亲的帮助和耐心解答。我写了一个解决方案，在问题#1086中。
#1086

**Comment by furybean** [comment]
和 #1086 重复，先关了这个。
