### ISSUE TITLE
[Feature Request] How to merge the cells of the summary row in the table？

### ISSUE THREAD

**Issue by dupeiduo** [ElemeFE/element#13436]
### Existing Component
Yes.

### Component Name
table

### Description
It is exist `rowspan` and `colspan`. But it doesn't work for the `summary` row. How to merge the cells of the summary row in the table？Just like the picture below.

![image](https://user-images.githubusercontent.com/15188363/48591413-c41a2900-e97e-11e8-956f-2c31b2d2ff11.png)

**Comment by ziyoung** [comment]
It's hard to achieve this feature. We have no plan to support this.
