### ISSUE TITLE
[Bug Report] elementUI table can not adaptive

### ISSUE THREAD

**Issue by qiushuaichang** [ElemeFE/element#13446]
##

### Element UI version
2.4.9

### OS/Browsers version
windows，mac ，all browsers

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.Resize the browser window, you can see that。

### What is Expected?
Change the browser window size. The table without setting the column width can adapt to the content in "td" and the width of "td". Just like the _bootstrap_ table, the table with the column width is not given.
**For example, if the table has fewer content in the first column and more content in the second, the table will automatically make the width of the first column smaller and the width of the second column larger**

### What is actually happening?
But now, if you don't give the table each column width, each column width is the same, which leads to some trouble. For example, the first column has less content, and the second column has more content, which results in the same width of the two columns, but the second column causes the row height to be higher and the style to be messy.

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
