### ISSUE TITLE
[Bug Report] After multiple dialogs pop-up/close, the message-box popped up by one of the dialog clicks is covered under it

### ISSUE THREAD

**Issue by PiedPiperr** [ElemeFE/element#13448]
### Element UI version
2.4.8

### OS/Browsers version
windows

### Vue version
2.5.0

### Reproduction Link
[https://github.com/PiedPiperr/images/blob/master/bug.jpg](https://github.com/PiedPiperr/images/blob/master/bug.jpg)

### Steps to reproduce
1.在一个页面，添加多了el-dialog。
2.依次将对这些dialog进行open/close。
3.其中有一个dialog(A)有个点击元素，点击可以弹出message-box(提示确认弹框),但是这个message-box却被覆盖在当前dialog(A)下方
4.通过检测，message-box的z-index 低于 dialog(A)的z-index。
5.bug截图:https://github.com/PiedPiperr/images/blob/master/bug.jpg

### What is Expected?
message-box应该显示在dialog上方

### What is actually happening?
message-box显示在dialog下方

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by PiedPiperr** [comment]
我发送链接了呀，一张bug图片。而且也在截图上指明了问题点。
![image](https://user-images.githubusercontent.com/32378929/48743995-7d8b3e00-eca0-11e8-9c56-414a633889d4.png)

**Comment by PiedPiperr** [comment]
@PiedPiperr 
就是在有多个dialog情况下，this.$message.info('xx')的提示框，被dialog覆盖住了。

**Comment by bingyuea** [comment]
I was in this situation.  same question ,It hasn't been disposed of yet

**Comment by ihepta** [comment]
element 的 issue 是不是关的有点随意了...
