### ISSUE TITLE
[Bug Report] 2.4.10 version navMenu component unique-opened = true, click on any area of the browser, sub-menu will be triggered to collect

### ISSUE THREAD

**Issue by weenta** [ElemeFE/element#13450]
### Element UI version
2.4.10

### OS/Browsers version
mac、win7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
el-submenu展开后，点击屏幕任何区域即可

### What is Expected?
点击其他区域，el-submenu不会收起

### What is actually happening?
点击其他区域，el-submenu收起

**Comment by alicksnake22** [comment]
的确是有这个问题，menu本身默认可以展开多个，我在2.2.2可以，然后用了2.4.10，就只能同时展开一个了。是用官方的例子测试的

**Comment by alicksnake22** [comment]
同时还有一个问题，menu本身默认可以展开多个，我在2.2.2可以，然后用了2.4.10，就只能同时展开一个了。是用官方的例子测试的。

**Comment by tangaoyu520hf** [comment]
是的 我也发现了，同样的问题
Yes, I also found the same problem.

**Comment by sds0917** [comment]
unique-opened  这个属性也不生效了

**Comment by sds0917** [comment]
2.4.10版本中应该是两个问题：
1、布局若为左右布局，左侧为垂直菜单，右侧为内容区域。但展开左侧菜单，并点击其中一个菜单项，再去点击非菜单区域，左侧菜单会自动合起来；
2、unique-opened这个属性不生效，始终会收缩当前已展开的菜单。

**Comment by dive2Pro** [comment]
测试过,  2.4.9 也是没问题的

**Comment by ziyoung** [comment]
@dive2Pro @weenta @sds0917 @alicksnake22 修复一个 issue 导致的 bug。大家在 13452 这个 issue 中讨论吧。

**Comment by ziyoung** [comment]
Duplicate of #13452
