### ISSUE TITLE
 [Bug Report] 合并单元行在有 fixed 参数时且只有一个合并行时显示错误 The merge unit row displays errors when there is a fixed parameter and only one merge line.

### ISSUE THREAD

**Issue by hoythan** [ElemeFE/element#13459]
### Element UI version
2.4.10 - 2.5.4

### OS/Browsers version
macOS Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/hoythan/reswf2hy/1/](https://jsfiddle.net/hoythan/reswf2hy/1/)
### Steps to reproduce
[https://jsfiddle.net/hoythan/reswf2hy/1/](https://jsfiddle.net/hoythan/reswf2hy/1/)

将参数改为
```
// 正常效果参数，拥有两个合并行
{
          id: '12987122',
          name: '王小虎',
          amount1: '234',
          amount2: '3.2',
          amount3: 10,
          row:2
        }, {
          id: '12987122',
          name: '王小虎',
          amount1: '165',
          amount2: '4.43',
          amount3: 12,
          row:2
        }, {
          id: '12987123',
          name: '王小虎',
          amount1: '324',
          amount2: '1.9',
          amount3: 9,
          row:1
        }
// 导致错误显示的参数，只拥有一个合并行
{
          id: '12987122',
          name: '王小虎',
          amount1: '234',
          amount2: '3.2',
          amount3: 10,
          row:3
        }, {
          id: '12987122',
          name: '王小虎',
          amount1: '165',
          amount2: '4.43',
          amount3: 12,
          row:3
        }, {
          id: '12987122',
          name: '王小虎',
          amount1: '324',
          amount2: '1.9',
          amount3: 9,
          row:3
        }
```

只有在table有两个合并行，或删除所有 fixed 后 table 效果才正常
否则table将出现第一列无法出现的bug

### What is Expected?
返回正常的效果

### What is actually happening?
当table只有一个合并行，且table 拥有fixed参数时，table显示不正确。

**Comment by hoythan** [comment]
还有bug就是单个合并行的时候，如果刷新table上的数据，比如点击按钮改变某个数据，table不论是否设置了fixed，都会消失。多个合并行还未测试

**Comment by hoythan** [comment]
多个合并行不会出现上面提到的bug

**Comment by ziyoung** [comment]
> 如果刷新table上的数据，比如点击按钮改变某个数据，table不论是否设置了fixed，都会消失

也补个例子吧。固定列的实现本来就有些复杂，加上单元合并，难免出锅。😅

**Comment by hoythan** [comment]
> > 如果刷新table上的数据，比如点击按钮改变某个数据，table不论是否设置了fixed，都会消失
> 
> 也补个例子吧。固定列的实现本来就有些复杂，加上单元合并，难免出锅。😅

https://jsfiddle.net/hoythan/uyndm4hf/1/

点击按钮后修改数据时，第一列会消失，且没有设置fixed。

**Comment by molikar** [comment]
![image](https://user-images.githubusercontent.com/27952297/48932754-7b431100-ef38-11e8-9a89-6a799a441d02.png)
当我把6行合并为一列； 小计下面就只能渲染出第一个数据，后面的数据 都不会渲染；
![image](https://user-images.githubusercontent.com/27952297/48932820-c4936080-ef38-11e8-9fe5-43da0c1e5235.png)
![image](https://user-images.githubusercontent.com/27952297/48932840-d412a980-ef38-11e8-8c8f-75730a9b0f9e.png)

**Comment by hoythan** [comment]
请问近期有修复的安排吗，有什么好办法可以临时解决这个问题？

**Comment by hoythan** [comment]
span-method 不正确的使用导致。
