### ISSUE TITLE
[Bug Report] NavMenu component, submenu loses focus will automatically retract.

### ISSUE THREAD

**Issue by wxxcarl** [ElemeFE/element#13452]
### Element UI version
2.4.10

### OS/Browsers version
MAC OS 10.13.6    /    Chrome 70.0.3538.102

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
鼠标点击展开子菜单后，在页面其他地方随意点击鼠标，子菜单会自动收起。

### What is Expected?
鼠标点击展开子菜单后，在页面其他地方随意点击鼠标，子菜单保持不动

### What is actually happening?
鼠标点击展开子菜单后，在页面其他地方随意点击鼠标，子菜单自动收起。发现这个问题在2.3.9种不存在，只有2.4.10。因为这个bug，同样导致了unique-opened配置失效

**Comment by sds0917** [comment]
2.4.10版本中应该是两个问题：
1、布局若为左右布局，左侧为垂直菜单，右侧为内容区域。但展开左侧菜单，并点击其中一个菜单项，再去点击非菜单区域，左侧菜单会自动合起来；
2、unique-opened这个属性不生效，始终会收缩当前已展开的菜单。

**Comment by ziyoung** [comment]
pr #13296 导致的该问题。这个 pr 的目的是点击菜单外部时，关闭已经打开的菜单。没想到升级会导致这么多问题。

> 点击菜单外部时，关闭已经打开的菜单

这个功能有那么重要吗？

**Comment by wxxcarl** [comment]
@ziyoung 垂直模式的时候，这个体验糟糕透顶，你可以去体验一下

**Comment by bestmike007** [comment]
SubMenu中引入了[Clickoutside directive](https://github.com/ElemeFE/element/blob/dev/packages/menu/src/submenu.vue#L326)，如果能有一个配置项就好了，目前可以dirty hack一下：

``` js
const closeMenu = this.$refs.menu.closeMenu.bind(this.$refs.menu);
this.$refs.menu.closeMenu = (index) => {
  if (new Error().stack.indexOf('handleSubmenuClick') < 0) return;
  closeMenu(index);
};
```

**Comment by zhangyile** [comment]
> 今天升级后，遇到同样的问题 ，求解。

要么退回去，要么将就着等更新么。

**Comment by ziyoung** [comment]
@wxxcarl @bestmike007 @sds0917 先回撤到旧版。另外大家讨论一下这个功能吧。

> pr #13296 导致的该问题。这个 pr 的目的是点击菜单外部时，关闭已经打开的菜单。没想到升级会导致这么多问题。
> 
> > 点击菜单外部时，关闭已经打开的菜单
> 
> 这个功能有那么重要吗？

**Comment by sds0917** [comment]
就功能而言没有问题。是否有个配置项能好一些？

**Comment by squallliu** [comment]
自己打了个补丁先用着
if (this.opened && this.rootMenu.mode==='horizontal') this.rootMenu.closeMenu(this.index);

**Comment by ziyoung** [comment]
在 #13478 中已经把代码回滚了。
@dive2Pro 提了一个 pr，增加了配置项，但是对于垂直状态下的 menu，还是不能关闭。点击外部关闭菜单的功能还是暂时不加了。

**Comment by dusksoft** [comment]
我还以为就我遇到这个问题，原来是个Bug，已经放弃2.4.10的升级，回滚回去了。。

**Comment by ziyoung** [comment]
这次造成的影响比较大。明天发一下小版本。大家先回撤到 2.4.9 吧。

**Comment by tom-hanks** [comment]
我的是2.4.5 为什么也有这个问题？就是导航总会收起，点击任何地方都收起

**Comment by ziyoung** [comment]
> 我的是2.4.5 为什么也有这个问题？就是导航总会收起，点击任何地方都收起

你确定正在使用的是 2.4.5 ？

**Comment by ziyoung** [comment]
2.4.11 已发布。
