### ISSUE TITLE
[Feature Request] Tab-pane label supports custom HTML Tags

### ISSUE THREAD

**Issue by 1297947244** [ElemeFE/element#13462]
### Existing Component
Yes

### Component Name
tabs

### Description
tab 组件，label 上需要显示提醒数量或者小红点，现在 label属性只支持字符串

**Comment by ziyoung** [comment]
请仔细阅读文档：http://element-cn.eleme.io/#/zh-CN/component/tabs#zi-ding-yi-biao-qian-ye
