### ISSUE TITLE
There is only one input box in the [Bug Report] dialog box. In the input box, you get the focus state. Press enter to trigger the page jump.

### ISSUE THREAD

**Issue by Modaol** [ElemeFE/element#13464]
### Element UI version
2.4.10

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/](https://github.com/ElemeFE/element/)

### Steps to reproduce
1.打开官网
2.选择组件
3.选择Dialog对话框
4.点击“打开嵌套表单的 Dialog”打开对话框
5.按'F12',打开开发者工具
6.使用开发者工具的选择器选择"el-select 选择器"组件，然后将"el-select 选择器"组件所在的`表单项`元素删除
7.点击输入框获得焦点，按'enter'
8.页面自动刷新，地址栏中的锚点(#)前，多了一个'?'

### What is Expected?
为什么会自动刷新？怎么取消刷新？

### What is actually happening?
页面自动刷新，地址栏中的锚点(#)前，多了一个'?'

**Comment by ziyoung** [comment]
1. 你应该提供正确的例子。
2. 
> 使用开发者工具的选择器选择"el-select 选择器"组件，然后将"el-select 选择器"组件所在的表单项元素删除

为什么要有这样的操作。这种 DOM 操作不论你是使用何种框架都是不提倡的。

**Comment by Modaol** [comment]
@ziyoung 因为我没有一个上线了的服务，然后官网上并没有一个只有一个输入框的对话框，只是用这种方式产生一个只有一个输入框的对话框来重现。

**Comment by anrananran** [comment]
这个bug现在还存在，版本2.15.6
