### ISSUE TITLE
button和button-group同级放置时出现异常

### ISSUE THREAD

**Issue by initial-wu** [ElemeFE/element#1346]
![qq 20161124200541](https://cloud.githubusercontent.com/assets/17722900/20597982/c1c5cf28-b281-11e6-9074-ea4fa46833f9.jpg)
![qq 20161124200708](https://cloud.githubusercontent.com/assets/17722900/20597983/c451362e-b281-11e6-8e20-c4d22cb11a93.jpg)
button向下移动

**Comment by initial-wu** [comment]
而且button-group中只有一个button时border-radius都会被去掉

**Comment by baiyaaaaa** [comment]
fix in #1349
