### ISSUE TITLE
[Bug Report] header selection for el-table-column

### ISSUE THREAD

**Issue by lujinggirl** [ElemeFE/element#13465]
### Element UI version
2.4.10

### OS/Browsers version
chrome70.0.3538.102

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
用vueElement中el-table的过滤，在列表渲染之后，异步请求表头过滤数据filtersValue， 表头没有过滤按钮

### What is Expected?
用vueElement中el-table的过滤，在列表渲染之后，异步请求表头过滤数据filtersValue， 表头可以正常过滤，按钮可以正常显示

### What is actually happening?
用vueElement中el-table的过滤，在列表渲染之后，异步请求表头过滤数据filtersValue， 表头没有过滤按钮

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
