### ISSUE TITLE
[Bug Report] NavMenu loses focus and automatically folds submenus.

### ISSUE THREAD

**Issue by jmjlbmn** [ElemeFE/element#13461]
### Element UI version
2.4.10

### OS/Browsers version
Chrome 70.x

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/jmjlbmn/yzk0aju9](https://jsfiddle.net/jmjlbmn/yzk0aju9)

### Steps to reproduce
官方示例即可重现,展开子级菜单(二级,三级)后,点击其他位置,会自动折叠子级菜单,没有设置unique-opened,换成2.4.9版本正常,

### What is Expected?
保持子级菜单展开,或者有配置参数可以保持

### What is actually happening?
点击其他地方(失去焦点)自动折叠子级菜单

**Comment by wangqh** [comment]
我也遇到这个问题了，项目不小心升级到了2.4.10就出现了这个bug，打算降回2.4.9，希望能尽快修复

**Comment by ziyoung** [comment]
Duplicate of #13452

**Comment by ziyoung** [comment]
修复一个 issue 导致的 bug。大家在 13452 这个 issue 中讨论吧。
