### ISSUE TITLE
[Bug Report] Carousel takes the left and right toggle button of the lantern component to disappear automatically.

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#13460]
### Element UI version
2.4.10

### OS/Browsers version
win10 / chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/2cx3tL74/](https://jsfiddle.net/2cx3tL74/)

### Steps to reproduce
将鼠标移入左边上一个按钮或者右边下一个按钮，当点击几次之后，按钮会出现自动消失的情况。

### What is Expected?
鼠标移出才会消失

### What is actually happening?
在鼠标over期间，会出现自动消失的情况

**Comment by ziyoung** [comment]
无法重现。再描述清楚一点。

![kapture 2018-11-19 at 18 40 24](https://user-images.githubusercontent.com/12947422/48701996-c0aaca00-ec2a-11e8-8cc4-46318b770d79.gif)

**Comment by LemonAppleMo** [comment]
![gif](https://user-images.githubusercontent.com/32638462/48762715-94ed1a00-ece6-11e8-9063-6a88b0e315a2.gif)

具体就是这个样子

**Comment by ziyoung** [comment]
还是无法重现呀！
难道是 Windows 独有的问题。你再检查一下吧。
