### ISSUE TITLE
[Feature Request] [Table] UX: Selecting filters should apply changes instead of confirming

### ISSUE THREAD

**Issue by kevrousso** [ElemeFE/element#13470]
### Existing Component
Yes

### Component Name
El-Table

### Description
In a UX perspective, I find this a bit of a hassle having to click confirm everytime I select a checkbox in the filters list.
Applying the filters on checkbox click would be much more efficient and less repetitive.

Also, I noticed that when checking a filter but not confirming yet the label of the column gets bold, which gets really confusing if you didn't apply filters...

**Comment by lxmfly123** [comment]
The behavior of filter can be very confusing sometimes. After I select some item without confirming, the next time I trigger the filter, it still keeps the unconfirmed item. So how can I tell if one specific item is selected or not in this case?
