### ISSUE TITLE
[Bug Report] table column attribute 'show-overflow-tooltip'issue

### ISSUE THREAD

**Issue by Fulun** [ElemeFE/element#13480]
### Element UI version
2.4.10

### OS/Browsers version
chrome Version 70.0.3538.102 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6945/](https://jsfiddle.net/mmx38qxw/6945/)

### Steps to reproduce
1. set the attribute 'show-overflow-tooltip' to true (将show-overflow-tooltip属性设置为true)
2. copy so many contents in the column (copy 大量内容到某一列)
3. The tooltips can not display correctly. the table is repainting repeatedly when the mouse is on the cell containing vast contents. (tooltips 无法正常显示，当鼠标放在包含大量内容的cell上时，表格在不断的在重绘).

### What is Expected?
The tooltips can display correctly when the switch 'show-overflow-tooltip' is open and the cell contains so many contents.(当列包含大量内容时，tooltips可以正常显示)

### What is actually happening?
The tooltips can not display correctly when the switch 'show-overflow-tooltip' is open and the cell contains so many contents.(当列包含大量内容时，tooltips不能够正常显示)

**Comment by Fulun** [comment]
定义了最大宽度和高度也没有用

**Comment by ziyoung** [comment]
不算是 bug。内容太多时，滚动条出现，触发了 tooltip 重新计算。可以通过给 tooltip 设置宽高。
不过这么多信息放在 tooltip 中是否合适呢？毕竟一屏都显示不下。https://jsfiddle.net/mmx38qxw/6974/
