### ISSUE TITLE
[Bug Report] el-checkbox is selected by default, and the check button can not show the tick.

### ISSUE THREAD

**Issue by pk110** [ElemeFE/element#13483]
### Element UI version
2.4.6

### OS/Browsers version
window7 chrome 70

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/1Lm6gjze/](https://jsfiddle.net/1Lm6gjze/)

### Steps to reproduce
默认进入页面时，所有勾选项默认都被勾选，但是全选勾选框没有显示打勾

### What is Expected?
全选勾选框应该显示打勾

### What is actually happening?
全选勾选框没有显示打勾

**Comment by pk110** [comment]
bug

**Comment by ziyoung** [comment]
> 默认进入页面时，所有勾选项默认都被勾选，但是全选勾选框没有显示打勾

indeterminate 的初始值是 true，当然打钩了。

**Comment by zhuSass** [comment]
并没有

> > 默认进入页面时，所有勾选项默认都被勾选，但是全选勾选框没有显示打勾
> 
> indeterminate的初始值是true，当然打钩了。

indeterminate 属性用以表示 checkbox 的不确定状态，不确认状态并不等于全选状态，此问题确实存在
