### ISSUE TITLE
[Bug Report] input输入框type="number"，输入类似0...1的值，用v-model取到值为  " "（空）

### ISSUE THREAD

**Issue by 1429880240** [ElemeFE/element#13484]
### Element UI version
2.4.10

### OS/Browsers version
谷歌双核浏览器或者谷歌

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xihaiyu/nqc297ek/12/](https://jsfiddle.net/xihaiyu/nqc297ek/12/)

### Steps to reproduce
输入类似0...1的值，用v-model取到值为  " "（空）

### What is Expected?
输入类似0...1的值，用v-model取到值为 0...1，取到的值和输入的值一致

### What is actually happening?
输入类似0...1的值，用v-model取到值为 " "

**Comment by ziyoung** [comment]
```
Number('0.......1') // Nan
```

**Comment by 1429880240** [comment]
ok

**Comment by 1429880240** [comment]
@ziyoung thank you
