### ISSUE TITLE
[Bug Report] Version 2.4.10 Navigation Menu, click anywhere in the body, the menu sub-options will be withdrawn by default, unable to set the status to remain.

### ISSUE THREAD

**Issue by htmlzhoyan** [ElemeFE/element#13488]
### Element UI version
2.4.10

### OS/Browsers version
最新版本

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
菜单导航-打开子菜单-点击body

### What is Expected?
菜单导航-打开子菜单-点击body-子菜单不收回

### What is actually happening?
菜单导航-打开子菜单-点击body-子菜单收回

**Comment by belief-cyf** [comment]
+1

**Comment by htmlzhoyan** [comment]
看了版本源码，
之前版本的
![icon_create](https://user-images.githubusercontent.com/22017167/48765087-64a87a00-ecec-11e8-99d8-d4b60500892b.png)
最新2.4.10版本的
![tim 20181120174722](https://user-images.githubusercontent.com/22017167/48765135-7f7aee80-ecec-11e8-9f4d-b07589670456.png)
一对比，新版本的写死了，怪不得点任何地方，会收回去呢
这样写有问题的，比如我现在去点子菜单，结果去点击子菜单对应的路由页面，一点页面，子菜单收缩回去了，这不很别扭吗

**Comment by ziyoung** [comment]
Duplicate of #13452

**Comment by ziyoung** [comment]
@htmlzhoyan 是我的锅。代码 review 没检查出来，明天个发小版本。
