### ISSUE TITLE
[Bug Report] Scroll bar height does not adjust when changing window size

### ISSUE THREAD

**Issue by yoonasy** [ElemeFE/element#13489]
### Element UI version
2.4.10

### OS/Browsers version
chrome new version

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6958/](https://jsfiddle.net/mmx38qxw/6958/)

### Steps to reproduce
Window size changes the position of the scroll bar is not accurate

### What is Expected?
ok

### What is actually happening?
。

**Comment by ziyoung** [comment]
We don't recommend users to use Scrollbar. It's not exposed to users.

**Comment by yoonasy** [comment]
thank
