### ISSUE TITLE
[Bug Report] 2.4.10 will automatically shrink the submenu anywhere on the NavMenu clicking page.

### ISSUE THREAD

**Issue by dusksoft** [ElemeFE/element#13481]
### Element UI version
2.4.10

### OS/Browsers version
Win7-64/Chrome- 70.0.3538.102

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、点击父菜单展开子菜单
2、点击非菜单的其它页面位置会自动收缩子菜单

### What is Expected?
点击页面其它位置不影响到菜单的展开和收缩

### What is actually happening?
点击页面任意位置会影响菜单的显示

**Comment by languanghao** [comment]
+1，同样遇到这个问题

**Comment by justin107** [comment]
确实有这个问题，点页面其余地方菜单收起来，不科学

**Comment by dusksoft** [comment]
https://jsfiddle.net/r3qt1L2f/ @element-bot

**Comment by ziyoung** [comment]
Duplicate of #13452

**Comment by ziyoung** [comment]
受这个问题影响的比较多。已经把相关代码更回滚了。新版本会尽快发出。
