### ISSUE TITLE
[Bug Report] uses scoped slots to distribute el-select to a specified location, and does not echo when the median is selected, but the value bound in the V-model has changed accordingly.

### ISSUE THREAD

**Issue by normal-xsw** [ElemeFE/element#13499]
### Element UI version
2.4.10

### OS/Browsers version
windows10, chrome

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
把el-select分发到子组件的指定位置，并用作用域插槽从子组件传值，会导致select选中值时，回显框没有更新，但是v-model中的值已经时选中的value值了
类似代码：
```vue
  <template slot="zxc" slot-scope="prop">
        <el-select v-model="prop.value" placeholder="请选择" @change="changeInfo(val, prop.value)">
          <el-option
            v-for="item in prop.options"
            :key="item.value"
            :label="item.label"
            :value="item.value">
          </el-option>
        </el-select>
    </template>
```

### What is Expected?
无

### What is actually happening?
无

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by ziyoung** [comment]
组件复用了，加个 key。

**Comment by normal-xsw** [comment]
我在select上加了key,但是没有解决问题

**Comment by ljyf5593** [comment]
我也遇到相同的问题

**Comment by ljyf5593** [comment]
我的问题已经解决，我估计你的问题和我问题类似。v-model的对象是从另外一个对象赋值过来的，但是因为js里默认对象赋值只是赋值的对应的引用，因此会出现这个问题，解决方法也比较简单，改成深拷贝赋值就可以了
