### ISSUE TITLE
2.4.10 menu have bugs for unique-opened, bug 2.4.9 is normal

### ISSUE THREAD

**Issue by chenmanru75** [ElemeFE/element#13495]
2.4.10版本的menu组件bug
![default](https://user-images.githubusercontent.com/42316876/48776890-0ee3ca00-ed0c-11e8-86bc-1db79a6ea9c1.png)
unique-opened 属性配置后无效
而且点击页面 menu的子菜单会自动收起，在 2.4.9就可以正常使用

**Comment by xulei890817** [comment]
点击页面其他位置，menu都会自己收起来，我也遇到了。没看到有设置项可以解决

**Comment by chenmanru75** [comment]
是的啊 所以改版本了用2.4.9就没问题




| |
陈曼如
邮箱：chenmanru75@163.com
|

签名由 网易邮箱大师 定制

On 11/21/2018 17:52, xulei890817 wrote:

点击页面其他位置，menu都会自己收起来，我也遇到了。没看到有设置项可以解决
