### ISSUE TITLE
[Bug Report] row-class-name repeatedly executes multiple questions

### ISSUE THREAD

**Issue by javadoge** [ElemeFE/element#13508]
### Element UI version
2.4.10

### OS/Browsers version
win7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/javadoge/ea02stjg/4/#](https://jsfiddle.net/javadoge/ea02stjg/4/#)

### Steps to reproduce
运行代码，debugger调试即可看到效果，row-class-name 事件重复执行了多次

### What is Expected?
table多少条纪录row-class-name事件就执行多少次

### What is actually happening?
row-class-name重复执行了很多次

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/10588#issuecomment-379460140
