### ISSUE TITLE
[Bug Report] El-table - dynamic key problem in el-table-column with v-for

### ISSUE THREAD

**Issue by hxlyd** [ElemeFE/element#13502]
### Element UI version
2.4.10

### OS/Browsers version
Mac/Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/hxlyd/x1yno4mc/32/](https://jsfiddle.net/hxlyd/x1yno4mc/32/)

### Steps to reproduce
1、change the order of columns；
2、el-table with :key="column.prop" will not update.

### What is Expected?
table update.

### What is actually happening?
table not update.

**Comment by StashOfCode** [comment]
Any news on this one?
