### ISSUE TITLE
选择框没办法通过键盘回车键失去焦点

### ISSUE THREAD

**Issue by wangzhenaccount** [ElemeFE/element#13504]

**Comment by wangzhenaccount** [comment]
![image](https://user-images.githubusercontent.com/26521572/48820062-19df3e80-ed8e-11e8-97e7-c4694a2ea8de.png)
![image](https://user-images.githubusercontent.com/26521572/48820088-42ffcf00-ed8e-11e8-9c24-c95534b733cf.png)
![image](https://user-images.githubusercontent.com/26521572/48820108-61fe6100-ed8e-11e8-871e-13f84e3f5723.png)
![image](https://user-images.githubusercontent.com/26521572/48820142-88240100-ed8e-11e8-94ea-3150f043eb3c.png)
![image](https://user-images.githubusercontent.com/26521572/48820267-32038d80-ed8f-11e8-90c0-a1cd7a37bbe0.png)
![image](https://user-images.githubusercontent.com/26521572/48820161-9d009480-ed8e-11e8-80c4-2cb9dc0c5bcf.png)
![image](https://user-images.githubusercontent.com/26521572/48820180-c0c3da80-ed8e-11e8-8dc8-95ebe585b660.png)
新增的时候tableData等于【】进入详情页选择，进行选择药库和查询单号以后，利用VUE.SET给tableData赋值，选择框的下拉菜单还是不能通过键盘回车事件让选择框失去焦点

**Comment by xulei890817** [comment]
一样，这个select有bug，切换到别的页面，再切换回来，会自动下拉。
