### ISSUE TITLE
[Feature Request] how to set half checked keys with tree component?

### ISSUE THREAD

**Issue by mrleex** [ElemeFE/element#13503]
### Existing Component
是

### Component Name
tree

### Description
Hello, I have a organization tree with lazy load, when someone choose what they want to manage, save it, and then reopen the tree, I want to keep checked status, however, I can set checked keys with setChecked method, but there is not half checked status, is there any way to set half checked keys?  :)

**Comment by ziyoung** [comment]
Duplicate of #13500

**Comment by imyoursazhou** [comment]
i have same issue with you,do you have any answer now?
