### ISSUE TITLE
[Bug Report] When el-tree and el-menu are used together, the expansion event of el-tree affects the expansion of el-menu.

### ISSUE THREAD

**Issue by summerstarlee** [ElemeFE/element#13509]
### Element UI version
2.4.10

### OS/Browsers version
Version 70.0.3538.110

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/do93hvtu/71/](https://jsfiddle.net/do93hvtu/71/)

### Steps to reproduce
1： Expand el-menu's first item
2： Click on an item in el-tree
3：the expend status changed 

### What is Expected?
The expanded states of el-tree and el-menu are handled separately and are not affected by each other.

### What is actually happening?
When el-tree and el-menu are used together, the expansion event of el-tree affects the expansion of el-menu.

**Comment by summerstarlee** [comment]
没有遇见警告， 我在  https://jsfiddle.net/do93hvtu/71/   里面把 elemnet 切换成 2.4.8 就不会有这个问题了

**Comment by ziyoung** [comment]
升级到 2.4.11 吧，2.4.10 的 bug。
