### ISSUE TITLE
[Feature Request] tree components support setHalfCheckedNodes and setHalfCheckedkeys

### ISSUE THREAD

**Issue by dongsuo** [ElemeFE/element#13500]
### Existing Component
Yes

### Component Name
Tree component

### Description
子节点为异步加载时，需要为父节点设置半选状态

**Comment by ziyoung** [comment]
半选是计算出来的，不支持设置。

**Comment by luchanan** [comment]
看了半天，没看到API有对应的方法，于是在想根据对象的引用可以这样设置
```
let tree = this.$refs.elTree[0].getNode(1125)
          if (tree) {
            tree.indeterminate = true
          }
```

**Comment by ViavaCos** [comment]
> 看了半天，没看到API有对应的方法，于是在想根据对象的引用可以这样设置
> 
> ```
> let tree = this.$refs.elTree[0].getNode(1125)
> if (tree) {
>    tree.indeterminate = true
>  }
> ```


非常好的想法，亲测有效

**Comment by kingdsa** [comment]
> 看了半天，没看到API有对应的方法，于是在想根据对象的引用可以这样设置
> 
> ```
> let tree = this.$refs.elTree[0].getNode(1125)
> if (tree) {
>    tree.indeterminate = true
>  }
> ```
亲测有效
