### ISSUE TITLE
[Bug Report] NavMenu component bug

### ISSUE THREAD

**Issue by xuixnwei** [ElemeFE/element#13507]
### Element UI version
2.4.10

### OS/Browsers version
win7/CHROME V70.0.3538.77

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6977/](https://jsfiddle.net/mmx38qxw/6977/)

### Steps to reproduce
点击开启任何一个导航菜单，然后点击导航以外区域，导航菜单自动关闭

### What is Expected?
处理为正常状态，点击不会被自动关闭

### What is actually happening?
点击开启任何一个导航菜单，然后点击导航以外区域，导航菜单自动关闭

**Comment by ziyoung** [comment]
Duplicate of #13452

**Comment by ziyoung** [comment]
今天发布一个小版本修复这个问题，不要再重复提问了。
