### ISSUE TITLE
[Bug Report] input输入框，type="number"的时候如果填入的是汉字时，替换为空值时光标展示的错误。

### ISSUE THREAD

**Issue by TommyCat008** [ElemeFE/element#13501]
### Element UI version
2.4.10

### OS/Browsers version
win10，chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/TommyZhang/mmx38qxw/6975/](https://jsfiddle.net/TommyZhang/mmx38qxw/6975/)

### Steps to reproduce
1、打开重现链接地址
2、使用搜狗输入法随意输入汉字，输入框的type是number会把汉字给替换掉
3、光标展示错误，光标靠上展示。

### What is Expected?
期待光标的位置为上下居中展示。

### What is actually happening?
光标的展示位置，太靠上了，不是正常的展示位置。

**Comment by ziyoung** [comment]
Duplicate of #12004
