### ISSUE TITLE
<el-table>固定列和合计行同时出现时且有横向滚动条时，固定列部分区域滚动条不能拖动

### ISSUE THREAD

**Issue by tongxuerui** [ElemeFE/element#13516]
<el-table>固定列和合计行同时出现时且有横向滚动条时，固定列部分区域滚动条不能拖动，fixed 遮住了滚动条

**Comment by xiejunping** [comment]
我也发现了同样的问题，怎么说没参照格式就关闭的，大佬
![image](https://user-images.githubusercontent.com/24519769/50879949-b67d9e80-1417-11e9-821a-7ff05aa68cbe.png)
