### ISSUE TITLE
NavMenu 导航菜单建议

### ISSUE THREAD

**Issue by hhxyjsj** [ElemeFE/element#13517]
- ElementUI version
2.4.5

- OS/Browers version
MacOs/Chrome 70.0.3538.102

- Vue version
2.5.17

-问题描述： NavMenu 导航菜单配置如下图所示：
![a](https://user-images.githubusercontent.com/31506377/48834671-507e7e80-edb9-11e8-9898-41dc075e7146.jpeg)
如上图所示，左侧为菜单【导航区域】，右侧为数据列表【数据区域】
在左侧展开某一个一级菜单后，在右侧数据列表中的任意地方单击，左侧的菜单会自动收起来。

- 建议
菜单的收起、展开只在点击菜单的时候发生。而不是上述问题那样，随便点击某处都会收起菜单

**Comment by oxiaojiano** [comment]
你解决这个问题了吗？

**Comment by Ronustine** [comment]
支持一个
