### ISSUE TITLE
[Bug Report] When table headers and table contents are separated and slots are used to modify table headers, table contents and table headers do not match.

### ISSUE THREAD

**Issue by chaijinsong** [ElemeFE/element#13513]
### Element UI version
2.4.11

### OS/Browsers version
macOS10.14 / Chrome 版本 70.0.3538.102（正式版本） 

### Vue version
2.5.17

### Reproduction Link
[https://codepen.io/chaijinsong/pen/OazaOx](https://codepen.io/chaijinsong/pen/OazaOx)

### Steps to reproduce
直接进入两秒后表头和表格内容不匹配。

### What is Expected?
修改表头的顺序之后，表格内容和表头一一匹配

### What is actually happening?
修改表头的顺序之后，表格内容和表头匹配混乱。
注：不使用template slot自定义表格内容时，即使修改了表头顺序，表格内容和表头是能匹配正确的。只有使用自定义表格内容时才出现混乱

**Comment by ziyoung** [comment]
要设置正确的 key https://codepen.io/ziyoung/pen/OaQGEo

**Comment by chaijinsong** [comment]
可是设置key之后，你给的例子中表头的顺序不会变化了。我目前的解决方案是重新给tableData赋值，强制重新渲染才会正确。

**Comment by chaijinsong** [comment]
> 要设置正确的 key https://codepen.io/ziyoung/pen/OaQGEo
可是设置key之后，你给的例子中表头的顺序不会变化了。我目前的解决方案是重新给tableData赋值，强制重新渲染才会正确。
