### ISSUE TITLE
[Bug Report] When a nested menu exists in the NavMenu navigation menu, click on the nested menu, and then click anywhere on the screen, the parent will automatically close.

### ISSUE THREAD

**Issue by TY-LIU** [ElemeFE/element#13512]
### Element UI version
2.4.10

### OS/Browsers version
WIN10 / 70.0.3538.102 (正式版本) （64 位）

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/mgukfrjy/

### Steps to reproduce
当NavMenu导航菜单存在嵌套菜单时，点击嵌套菜单，再点击屏幕任何地方，嵌套菜单的父级菜单会自动关闭

### What is Expected?
除了我手动去关闭父级菜单，任何情况下都不应该自动关闭。
建议做成开关，默认关闭

### What is actually happening?
展开父级菜单，点击子菜单后，再点击网页任意区域（除了导航菜单），父级菜单会自动关闭。
如果我有几层菜单，选择几层菜单之后，在我浏览内容时候，点击某个地方后，该嵌套菜单的顶层菜单会自动关闭，如果我想到嵌套菜单的某个同级菜单，就得重新打开菜单一层一层的打开，非常不方便

**Comment by ziyoung** [comment]
Duplicate of #13452

**Comment by ziyoung** [comment]
2.4.11 已发布。造成问题的 pr 已经撤销。

**Comment by TY-LIU** [comment]
![ge yj 44a9rfup0r4j s4w](https://user-images.githubusercontent.com/29595097/48830397-7b63d500-edaf-11e8-8c9f-fa8dab16bda1.jpg)
