### ISSUE TITLE
[Bug Report] 由于element-ui version2  使用了typescript，导致使用全局引入element-ui时webstrom无法识别element标签，从而给出”Unknown html tag el-menu ”警告

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#13527]
### Element UI version
2.4.11

### OS/Browsers version
无关

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/无关](https://jsfiddle.net/mmx38qxw/无关)

### Steps to reproduce
由于element-ui version2  使用了typescript，导致使用全局引入element-ui时webstrom无法识别element标签，从而给出”Unknown html tag el-menu ”警告

### What is Expected?
在webstrom中使用标签能只能补全，并且不会给出“Unknown html tag el-menu ”的警告

### What is actually happening?
webstrom找不到element-ui的vue组件，并且给出警告（不影响实际运行，但确实很不好。）

**Comment by ziyoung** [comment]
不算是 element 的 bug。建议查阅一下 webstorm 的文档，看看如何加载指定的 d.ts 文件。

**Comment by yinjunonly** [comment]
> 不算是 element 的 bug。建议查阅一下 webstorm 的文档，看看如何加载指定的 d.ts 文件。

你们现在是用什么工具开发的

**Comment by yinjunonly** [comment]
@ziyoung

**Comment by qinkaiyuan** [comment]
请问是如何解决的？

**Comment by qinkaiyuan** [comment]
希望官网人员不要逃避bug，虽然不是elm的bug，但是也影响了大家使用elm，希望官方能够提供合适的解决办法
