### ISSUE TITLE
[Bug Report] Cascader cascade selector is wrapped in lable tags and cannot open [with a recurrence link]

### ISSUE THREAD

**Issue by OBKoro1** [ElemeFE/element#13528]
### Element UI version
2.4.9

### OS/Browsers version
mac , Chrome:70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/OBKoro1/j8pyxm1q/3/](https://jsfiddle.net/OBKoro1/j8pyxm1q/3/)

### Steps to reproduce
用label标签将Cascader 级联选择器包裹即可重现

### What is Expected?
正常显示

### What is actually happening?
点不开级联选择器

**Comment by ziyoung** [comment]
不要用 label 包裹 cascader，点击 label 时会造成 cascader 的失焦与点击触发两次。https://jsfiddle.net/7mph9j3v/3/

**Comment by OBKoro1** [comment]
@ziyoung 或许你们应该给用户一些提示，或者加一个常见问题的页面，不然用户不知道这个问题，就可能被坑很久。
