### ISSUE TITLE
When [Bug Report] table and upload are used at the same time, 2 kinds of animation will appear when refreshing the page.

### ISSUE THREAD

**Issue by zykoikaze** [ElemeFE/element#13521]
### Element UI version
2.4.11

### OS/Browsers version
win10/chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/lvfangfang/mmx38qxw/6981/#fork](https://jsfiddle.net/lvfangfang/mmx38qxw/6981/#fork)

### Steps to reproduce
执行 run

### What is Expected?
如何解决，联系我~

### What is actually happening?
如何解决，联系我~

**Comment by zykoikaze** [comment]
<el-table-column type="selection" width="55"></el-table-column>  
table中加入多选，会重新加载

**Comment by ziyoung** [comment]
原因暂时未知。尝试固定upload-list 的高度，但是动画还是有问题。https://jsfiddle.net/mmx38qxw/6983/

**Comment by zykoikaze** [comment]
[https://jsfiddle.net/mmx38qxw/6985/](url)加上多选，选中某项的时候，会刷新

**Comment by zykoikaze** [comment]
<a href="https://jsfiddle.net/mmx38qxw/6985/"></a>加上多选，选中某项会刷新

**Comment by zykoikaze** [comment]
[](https://jsfiddle.net/mmx38qxw/6985/)加入多选，选中某项会刷新

**Comment by zykoikaze** [comment]
https://jsfiddle.net/mmx38qxw/6985/

**Comment by zykoikaze** [comment]
引入多选，选中某项会刷新https://jsfiddle.net/mmx38qxw/6985/

**Comment by zykoikaze** [comment]
2.4.8版本还是好的，更新大20409版本就这样了

**Comment by ziyoung** [comment]
在 2.4.9 版本中修改了 upload 组件，这次修改的主要目的是把原有的 key 由 index 换成了 uid，我认为这样的修改也不会造成什么问题呀。https://github.com/ElemeFE/element/pull/13054/files

**Comment by pizhihui** [comment]
@zykoikaze 说的对，2.4.8版本是正常的，我这里写了个components，只要file-list动态获取，就会出现这个奇怪的动画，不知道什么原因。公司项目很捉急，不行就降版本了。

**Comment by zykoikaze** [comment]
最新的版本好像更乱了https://jsfiddle.net/ntya3zbk/
