### ISSUE TITLE
[Bug Report] tree controls can cause errors when used together with asynchronous loading and dragging

### ISSUE THREAD

**Issue by kakercoco** [ElemeFE/element#13532]
### Element UI version
2.4.11

### OS/Browsers version
w10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
<el-tree :props="props1" draggable :load="loadNode1" lazy="" show-checkbox>
</el-tree>
子元素拖动到最外面会直接报错

### What is Expected?
正常拖动

### What is actually happening?
直接报错 Error in event handler for "tree-node-drag-end": "TypeError: Cannot read property 'indexOf' of undefined"

**Comment by kakercoco** [comment]
我这暂时没有链接，不过可以在官方的异步加载demo上加上draggable 拖动试试看就可以发现问题

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/13080#issuecomment-433780301
