### ISSUE TITLE
[Feature Request] The select component selected the value meanwhile to get ID

### ISSUE THREAD

**Issue by firekcc** [ElemeFE/element#13533]
### Existing Component
是

### Component Name
select

### Description
The select component selected the value meanwhile to get id ，i find the event is not support，also is not  IN Param

**Comment by ziyoung** [comment]
是 feature 还是 issue？描述清楚一点。也请提供一个例子，不要让我们去猜你的意图。

**Comment by firekcc** [comment]
是特点吧 就是选择框组件如果我选择一个value的同时click事件有同时获取id的兼容么，因为很多时候需要用到id去做其他业务操作，我用watch方法获取的还是lable和name，change事件里面传进来的也是name

**Comment by ziyoung** [comment]
我们暂时不支持该功能。
