### ISSUE TITLE
[Bug Report] tree filter support filter in the loaded data?

### ISSUE THREAD

**Issue by huyansheng3** [ElemeFE/element#13539]
### Element UI version
2.4.11

### OS/Browsers version
mac

### Vue version
2.5.17

### Reproduction Link
[http://github.com](http://github.com)

### Steps to reproduce
1. 使用load异步加载的树，树可能会很大，假设100条
2. 搜索的时候，会触发所有的子树去load方法，去加载对应的内容，但是数据量可能会很大。。这样有点没办法接受。

### What is Expected?
filter的时候支持只对已加载的树进行过滤

### What is actually happening?
filter的时候会主动去加载所有节点的子树，过滤出所有节点的数据

**Comment by Ende93** [comment]
你可以在搜索的时候设置个标识，load 方法里判断下

**Comment by ziyoung** [comment]
@Ende93 的答案可以解决你的问题。

**Comment by huyansheng3** [comment]
> @Ende93 的答案可以解决你的问题。

```
    filterValue(val) {
      this.isSearching = true;
      this.$refs.tree.filter(val);
      this.isSearching = false;
    },
```

```
  loadNode(node, resolve, type) {
      if (this.isSearching) return resolve([]);

      if (node.level === 1 && node.data.id) {
        this.query(node.data.id).then(data => {
          resolve(data);
        });
      } else {
        resolve([]);
      }
    }
```

搜索的时候，如果把load跳过，node的状态就被置为 loaded，后续点击展开时就没法触发触发 loadNode，之后数据都不会加载了。

**Comment by Ende93** [comment]
问题没解决的话，你要 reopen 这个 issue

**Comment by huyansheng3** [comment]
@Ende93  我好想没有办法 reopen这个issue。其实el-tree的源码看的差不多，在用户体验上考虑的确实蛮多，但是貌似没有办法跳过搜索时自动 expand这一步，expand就会去加载数据。一开始想的是魔改，但是成本比较大。 在我这边的场景下 https://github.com/amsik/liquor-tree 这个tree看起来更合适，搜索是基于现有数据。
