### ISSUE TITLE
[Bug Report] el-input trim trailing spaces not cleared

### ISSUE THREAD

**Issue by TMantas** [ElemeFE/element#13530]
### Element UI version
2.4.11

### OS/Browsers version
any

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/4z5ctkha/](https://jsfiddle.net/4z5ctkha/)

### Steps to reproduce
Try typing some spaces after the "0" in both inputs and focus out.

### What is Expected?
Trailing spaces should be cleared in both native and el-input.

### What is actually happening?
Spaces are cleared only in native input

**Comment by elfman** [comment]
@TMantas please take a look at this [https://github.com/vuejs/vue/issues/5847](https://github.com/vuejs/vue/issues/5847)
`trim` is indeed some special handling that is only present in native v-model. you can do the some thing with `@blur` event.

**Comment by TMantas** [comment]
Oh, thanks @elfman! Didn't read that thread before. Thanks!
