### ISSUE TITLE
请问 form 表单验证规则 rules 的文档在哪里

### ISSUE THREAD

**Issue by KarnaughK** [ElemeFE/element#13544]
### Element UI version
2.4.11

### OS/Browsers version
chrome

### Vue version
2.5.17

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/form#form-item-attributes
文档里只是写了object类型：【 rules	表单验证规则	object】，没有写可以怎么操作rules（我不是要自定义）

### What is Expected?
请告诉我rules文档。。。。

### What is actually happening?
111

**Comment by Ende93** [comment]
示例里有写，也可以看[这个文档](https://github.com/yiminghe/async-validator)
