### ISSUE TITLE
[Bug Report] el-submenu not scrollable, items getting cut off

### ISSUE THREAD

**Issue by Terrijoo** [ElemeFE/element#13543]
### Element UI version
2.4.11

### OS/Browsers version
Windows 10 / Google Chrome v70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Terrijoo/7oxq0whL/](https://jsfiddle.net/Terrijoo/7oxq0whL/)

### Steps to reproduce
Simple hover over the "Test"

### What is Expected?
To have a scrollbar to scroll through the list, if the list is too long

### What is actually happening?
The top items are getting cut off the screen
Not sure if I might have missed something on the config

**Comment by ziyoung** [comment]
a workground https://jsfiddle.net/4ft6qxua/

**Comment by ghostman-git** [comment]
> a workground https://jsfiddle.net/4ft6qxua/

https://jsfiddle.net/92x8L5ga/
