### ISSUE TITLE
[Bug Report] el-pagination component with small prop does not apply small to sizes dropdown

### ISSUE THREAD

**Issue by coolcorey** [ElemeFE/element#13545]
### Element UI version
2.4.11

### OS/Browsers version
Chrome, All

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7007/](https://jsfiddle.net/mmx38qxw/7007/)

### Steps to reproduce
apply small prop to el-pagination component

### What is Expected?
when using the small prop, the sizes select should also become small.

### What is actually happening?
the sizes select does not change in size when using the small prop

**Comment by ziyoung** [comment]
This is not a bug. https://jsfiddle.net/mmx38qxw/7009/

**Comment by coolcorey** [comment]
What does your jsfiddle have to do with my ticket? It absolutely is a bug and I think you are not understanding my ticket.
