### ISSUE TITLE
select为多选的情况时，如果多个option的label值一样但value值不一样，会出现无法同时选中这两个option的情况

### ISSUE THREAD

**Issue by yyzych** [ElemeFE/element#1354]
select为多选的情况时，如果多个option的label值一样但value值不一样，会出现无法同时选中这两个option的情况

[jsfiddle](http://jsfiddle.net/xtvg5vuq/#&togetherjs=AuVNsR2pt8)

**Comment by Leopoldthecoder** [comment]
Fixed in #1356
