### ISSUE TITLE
[Bug Report] click arrow can't show selection dropdown when use el-select as form label 

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#13558]
### Element UI version
2.4.11

### OS/Browsers version
macOS/chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xlaoyu/k2bsvd71/](https://jsfiddle.net/xlaoyu/k2bsvd71/)

### Steps to reproduce
click el-select's arrow

### What is Expected?
show selection dropdown

### What is actually happening?
not show

**Comment by ziyoung** [comment]
Don't use label to wrap Input component. It will cause unexpected behavior.
