### ISSUE TITLE
[Feature Request] [question] how to combine el-menu components? 

### ISSUE THREAD

**Issue by yesworld** [ElemeFE/element#13554]
### Existing Component
Yes

### Component Name
el-menu

### Description
I have two el-menu components, how to combine them together? So that when you click on one of the elements(el-menu-item) of one menu, the class "is-active" disappears in another menu.

**Comment by georgyfarniev** [comment]
Probably duplicate of https://github.com/ElemeFE/element/issues/13300

**Comment by yesworld** [comment]
@georgyfarniev Yes, it is.

**Comment by ziyoung** [comment]
Duplicate of #13300
