### ISSUE TITLE
The week selector V-model of [Bug Report] datepicker failed to pass values, and the median error was selected.

### ISSUE THREAD

**Issue by jingxiawl** [ElemeFE/element#13552]
### Element UI version
2.4.11

### OS/Browsers version
windows 7 / chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/jingxiawl/cs2neLry/4/](https://jsfiddle.net/jingxiawl/cs2neLry/4/)

### Steps to reproduce
1.设置datapicker从周六开始为一周的开始
2.为周选择器绑定v-model为value3，values3的值是默认给定的new Date（2018， 10， 27）
3.页面加载完成，点击选择器查看选中的周，（初始化values3的值并不在选中周内）
3.切换日期选择，查看alert出来的选择后的值

### What is Expected?
1.我传入的values3的值应该属于哪个周默认选中哪个周，现在没有默认选中当前values3所选的周，
2.并且当我点击了周切换希望返回的是选中周的时间段而不是选中周的第二天，即使不是时间段也希望返回的是开始时间

### What is actually happening?
1.传入的values3没在选中周里面
2.当选择一周过后，返回选中周第二天

**Comment by ziyoung** [comment]
Duplicate of #6754

**Comment by jingxiawl** [comment]
@ziyoung 那你们要改这个问题么？？？？？
