### ISSUE TITLE
[Bug Report] el-select fails to set default value

### ISSUE THREAD

**Issue by Youngtse** [ElemeFE/element#13557]
### Element UI version
2.4.11

### OS/Browsers version
Windows 7 / Chrome 70.0.3538.110

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/56fyLj8c/1/](https://jsfiddle.net/56fyLj8c/1/)

### Steps to reproduce
open the jsfiddle link

### What is Expected?
show default value "9 test"

### What is actually happening?
show "9"

**Comment by ziyoung** [comment]
You are using `remote-method`, the selected label won't update until you select one option.

**Comment by ziyoung** [comment]
You are using `remote-method`, the selected label won't update until you select one option.

**Comment by Erbenos** [comment]
Workaround:

You can prepopulate ´<el-option>´'s inside ´remote-method´ ´<el-select>´, before setting its v-model, then the default value displays properly. Since you already have the value you want displayed there is no need to search for it.
