### ISSUE TITLE
[Feature Request] Add `prefix` and `suffix` properties for <el-table-column>

### ISSUE THREAD

**Issue by frontbear** [ElemeFE/element#13561]
原 issue: #13514 

--------------------------------------

### Existing Component
Yes

### Component Name
table

### Description
usage example:

```html
1. <el-table-column prop="price" label="价格" prefix="￥"></el-table-column>
2. <el-table-column prop="price" label="价格" suffix="元"></el-table-column>
```

output:

```
1. ￥300
2. 300元
```

---------------------
@ziyoung 这两个属性确实非常实用，我这里举个例子向您展示一下：

输出效果：
----------------

|年龄  |价格
| ------------------ | ---
|11岁  |￥300.00

目前的方式（需要10行代码完成，属性太多则不易阅读）：
---------

```html
<el-table-column label="年龄">
  <template slot-scope="scope">
    <div>{{ scope.row.age }} 岁</div>
  </template>
</el-table-column>

<el-table-column label="价格">
  <template slot-scope="scope">
    <div>￥{{ scope.row.price }}</div>
  </template>
</el-table-column>
```

使用前缀和后缀（仅两行代码完成，干净整洁）：
-------------------
```html
<el-table-column prop="age" label="年龄" suffix="岁"></el-table-column>

<el-table-column prop="price" label="价格" prefix="￥"></el-table-column>
```

麻烦您再考虑一下我的提议，感谢！

**Comment by ziyoung** [comment]
@frontbear 如果添加了这两个属性。用户说我想自定义 prefix 或者 suffix 咋办呢？好了，那又得添加 prefix 与 suffix 两个 slot。一下子添加了四个属性。

另外如果添加了这两个属性，用户在使用时又使用了 scoped-slot，那么到底要如何处理这种情况呢？

----

现在，我们想一想，这功能是不是特别不好实现？
答案是：比较容易实现。

因此我觉得没有必要去添加。

**Comment by frontbear** [comment]
@ziyoung 我认为逻辑应该是这样：

<br>

> 用户说我想自定义 prefix 或者 suffix 咋办呢？

这两个属性类似于编程语言`语法糖`的效果，方便、实用，不支持自定义

<br>

> 另外如果添加了这两个属性，用户在使用时又使用了 scoped-slot，那么到底要如何处理这种情况呢？

如果同时使用了 `scoped-slot` 和 `prefix/suffix` ，则 `prefix/suffix` 不起作用，类似 `prop`
