### ISSUE TITLE
[Feature Request] date range picker, better year/month navigation

### ISSUE THREAD

**Issue by joaomnb** [ElemeFE/element#13567]
### Element UI version
2.4.11

### OS/Browsers version
macOS Mojave / Chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Open both the regular datepicker and the range picker, and compare the headers. The first is clickable, the second is not. Thus, when selecting a range, if the user wants to navigate to a year in the past, clicking the arrows multiple times is the only option.

### What is Expected?
I wonder if it is not possible to have the range picker's header work just like the regular one, where clicking the month/year changes the UI for faster navigation.

### What is actually happening?
Unlike the regular date picker (type="date"), the range picker's header (month and year) is not clickable.

**Comment by gauravneema** [comment]
I am facing the same issue. Is there any workaround for this?

**Comment by wacky6** [comment]
In short: this is not a bug; no workaround now.

If you know the time user is likely to select, use `default-value` to set the default year/month when picker is opened.

---

Some questions are to be answered before we can consider to support this.

* If `unlink-panels` is not set, left and right calendar will be one month apart (Mar, Apr). In this case, how to display year/month table.
* If `unlink-panels` is set, left and right calendar can be arbitrary months. In this case, how to display year/month table. (One easy solution is to reuse current date-picker's code)

In either case, the modification is non-trivial.

**Comment by joaomnb** [comment]
I see, thanks for the explanation! My guess is that the best approach would be to follow the second option you mentioned (and specify in the docs that this functionality is only available when using `unlink-panels`)... Seems to make sense to me, but I understand that this should go through further discussion before any change.
