### ISSUE TITLE
[Bug Report] isVertical on PascalCase ELContainer not working

### ISSUE THREAD

**Issue by monsdroid** [ElemeFE/element#13566]
### Element UI version
2.4.11

### OS/Browsers version
Chrome

### Vue version
2.5.17

### Reproduction Link
[https://github.com/ElemeFE/element/blob/0e7a7d345f508531cfb170a613a6ece1a2c398b7/packages/container/src/main.vue#L27](https://github.com/ElemeFE/element/blob/0e7a7d345f508531cfb170a613a6ece1a2c398b7/packages/container/src/main.vue#L27)

### Steps to reproduce
Use ELContainer with ELHeader or ELFooter in PascalCase wont set isVertical on ELContainer

Cause: https://github.com/ElemeFE/element/blob/0e7a7d345f508531cfb170a613a6ece1a2c398b7/packages/container/src/main.vue#L27

Vue ESLint recommends to use PascalCase so...

### What is Expected?
isVertical is set on ELContainer

### What is actually happening?
isVertical is not set

Quickfix ist to set direction prop on ELContainer

**Comment by wacky6** [comment]
Please, write a jsfiddle demo. A source code fragment is not really useful in determining the cause.

**Comment by monsdroid** [comment]
https://github.com/ElemeFE/element/blob/dev/test/unit/specs/container.spec.js
```
it('vertical-PascalCase', () => {
    vm = createVue({
      template: `
        <ELContainer>
          <ELHeader></ELHeader>
          <ELMain></ELMain>
        </ELContainer>
      `
    }, true);
    expect(vm.$children[0].$el.classList.contains('is-vertical')).to.true;
  });
```

**Comment by jinan5694** [comment]
@monsdroid i can fix this issue by add prop "direction" with value "vertical"

`
<ElContainer direction="vertical">
`
