### ISSUE TITLE
[Bug Report] table-column components cannot synchronize height changes to fixed columns using highly variable components

### ISSUE THREAD

**Issue by theWorkFsz** [ElemeFE/element#13564]
### Element UI version
2.4.11

### OS/Browsers version
liunx/chrome 72

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/7tcLzhse/](https://jsfiddle.net/7tcLzhse/)

### Steps to reproduce
点击地址列任意一条数据，
展开数据，
两边 fixed 高度不一致，
猜测：
封装过后的组件，实际有其独立作用域，而计算 fixed 高度的表格中嵌入的实际上是同一组件的不同实例，因此高度不共享，无法触发高度变化

### What is Expected?
主表单列中的组件高度变化应当同步给 fixed 列

### What is actually happening?
fixed 列高度变化不同步

**Comment by theWorkFsz** [comment]
> 固定列的实现本来就有些复杂。把 fixed 去掉，一切就正常。

这个说不上是一种解决方法，只是规避了问题......

**Comment by ziyoung** [comment]
Duplicate of #12078
