### ISSUE TITLE
[Bug Report] el-select 的 dropdown 无法跟随内容一起水平滚动

### ISSUE THREAD

**Issue by mu-yu** [ElemeFE/element#13577]
### Element UI version
2.4.11

### OS/Browsers version
win10 / chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/52myhkcv/](https://jsfiddle.net/52myhkcv/)

### Steps to reproduce
打开下拉框，按住shift滚动滚轮，使得表格内容滚动，可见下拉框内容未跟随左右滚动

### What is Expected?
当内容水平滚动时，el-select 的下拉选项能跟随内容一起移动

### What is actually happening?
当内容水平滚动时，el-select 的下拉选项无法跟随内容一起移动

**Comment by ziyoung** [comment]
Duplicate of #12797
