### ISSUE TITLE
[Bug Report] When I use v-if to switch column, the custom header  becomes confused

### ISSUE THREAD

**Issue by z1900** [ElemeFE/element#13579]
### Element UI version
2.4.11

### OS/Browsers version
windows 10 / chrome 70.0.3538.110

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/z1900/bq20a4nm/17/](https://jsfiddle.net/z1900/bq20a4nm/17/)

### Steps to reproduce
点击 toggle 按钮

### What is Expected?
根据 showAddress 切换 table-column

### What is actually happening?
自定义表头渲染出错

**Comment by ziyoung** [comment]
添加一个 key https://jsfiddle.net/gxk89f4u/

**Comment by z1900** [comment]
可以了  非常感谢 @ziyoung
