### ISSUE TITLE
el-button第一次点击不会触发，但是第二次开始会连续增加的触发是什么原因

### ISSUE THREAD

**Issue by jiaxiaon** [ElemeFE/element#13575]
这个是组件
<el-button :id="gernerateId(scope.$index)"><span :id="gernerateId1(scope.$index)" @click="newFilePic(scope.$index)">上传图片</span></el-button>
这个是methdos方法
newFilePic(index){
       var that = this;
       setuploaderinit("selectFile"+index,"contain"+index,true,2,that,index);
}

**Comment by jiaxiaon** [comment]
setuploaderinit("selectFile"+index,"contain"+index,true,2,that,index);

这个是封装好的一个函数，用来上传到阿里云

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
