### ISSUE TITLE
[Bug Report] IE10+  el-input中input event默认会触发，导致form自动验证

### ISSUE THREAD

**Issue by jinboyigu** [ElemeFE/element#13578]
### Element UI version
2.4.11

### OS/Browsers version
WIN10/IE11

### Vue version
2.5.17

### Reproduction Link
[jsfiddle不支持ie](jsfiddle不支持ie)

### Steps to reproduce
form表单中下有input输入框，且需要校验

源码例子如下：
```
<template>
    <el-form :rules="rules" :model="model" @submit.native.prevent>
        <el-form-item prop="value" label="输入框">
            <el-input v-model="model.value"></el-input>
        </el-form-item>
    </el-form>
</template>

<script>
export default {
    name: 'input',
    data() {
        return {
            model: {
                value: '',
            },
            rules: {
                model: [
                    { required: true, message: '不能为空', trigger: ['change', 'blur'] },
                ]
            }
        }
    }
}
</script>
```

### What is Expected?
初次进入该页面不进行校验。

### What is actually happening?
初次进入该页面进行了自动验证。

<input @input="handleInput" v-model="value"/>没有触发handleInput

而<el-input\/> 则触发了

**Comment by ziyoung** [comment]
这种情形用户可以自行 hack 一下。IE 的兼容性问题不好修。

**Comment by jinboyigu** [comment]
再搜了issue ，是跟 #11530 一样的问题。感觉是 placeholder的实现导致兼容性问题。

是不是 有placeholder 就更新了input.value？

**Comment by jinboyigu** [comment]
外部hack的方式都不太完美
