### ISSUE TITLE
[Bug Report] Select with option "allow create" do not store value if Tab pressed

### ISSUE THREAD

**Issue by maryasov** [ElemeFE/element#13570]
### Element UI version
2.4.11

### OS/Browsers version
Linux

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/maryasov/yofh4d8g/1/](https://jsfiddle.net/maryasov/yofh4d8g/1/)

### Steps to reproduce
- type some text
- press Tab
= no value stored

### What is Expected?
when I press Tab is expected to store new value & focus to the next fields on form

### What is actually happening?
Tab is just escaping input field without storing value.
there is "visible = false" action attached for Tab event. if add some Timeout to action, the value has time to save & works fine

**Comment by maryasov** [comment]
there is "visible = false" action attached for Tab event. if I add some Timeout to action, the value has time to save & works fine

**Comment by wacky6** [comment]
This is the intended behavior. To confirm / a select value, user has to hit enter.

Similarly, when use down arrow to select (highlighting) option, then Tab away without enter, the option will not be selected.
