### ISSUE TITLE
table 存在固定列时，异步更新table 数据，table高度没有撑开

### ISSUE THREAD

**Issue by haochengxu** [ElemeFE/element#1357]
图如下

![image](https://cloud.githubusercontent.com/assets/7252540/20616387/eeea22c4-b31c-11e6-829f-646c0bade90c.png)

**Comment by haochengxu** [comment]
<div class="el-table__body-wrapper" style="height: 60px;"></div>

**Comment by furybean** [comment]
请提供版本信息；请提供 el-table 的属性设置。

**Comment by haochengxu** [comment]
"element-ui": "^1.0.0-rc.8",
```
      <el-table v-loading="loading"
        :data="tableData"
        border
        style="width: 100%">
```

**Comment by furybean** [comment]
@haochengxu 这是一个修正过的问题，参考这里：#839
