### ISSUE TITLE
When [Bug Report] el-table loads too much data, when multiple rows of data are selected, the action is jammed.

### ISSUE THREAD

**Issue by mingugu** [ElemeFE/element#13589]
### Element UI version
0.1.0

### OS/Browsers version
无

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/64kczura/](https://jsfiddle.net/64kczura/)

### Steps to reproduce
1，用了el-table，第一列为选择类型的;表格数据有一百行。
2，为了能够点击某一行勾选改行，用了@toggleRowSelection的方法;为了渲染不一样的行样式，用了@ row-class-name;还用了doLayout方法。
3，选择某一行或者多选，选中动作会出现卡顿的情况

### What is Expected?
选中动作不会出现卡顿

### What is actually happening?
选中动作会出现卡顿

**Comment by ziyoung** [comment]
Duplicate of #6089
