### ISSUE TITLE
ie浏览器   el-input 嵌套下拉选择的时候，在input标签上添加 clearable 属性会到时浏览器崩溃

### ISSUE THREAD

**Issue by Ckefan** [ElemeFE/element#13580]
ie浏览器   el-input 嵌套下拉选择的时候，在input标签上添加 clearable 属性会到时浏览器崩溃

![image](https://user-images.githubusercontent.com/23022046/49073315-1efc2c00-f26d-11e8-9e6d-4dbc3b3c96f4.png)

**Comment by ziyoung** [comment]
IE 的问题。而非 element 的 bug，用户自行处理吧。
