### ISSUE TITLE
[Bug Report] chrome 70下upload控件里面的el-buttom设置disabled属性为true，还可以触发点击事件。

### ISSUE THREAD

**Issue by yinwanli** [ElemeFE/element#13582]
### Element UI version
2.4.11

### OS/Browsers version
chrome70 win7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/bLfgmqs8/](https://jsfiddle.net/bLfgmqs8/)

### Steps to reproduce
给el-button添加disabled属性，点击save，run，chrome点击 按钮，居然可以弹出选择图片的框。firefox下表现正常。

### What is Expected?
添加disabled属性，不可以再点击

### What is actually happening?
按钮已经变灰，样式起作用了，但是点击事件还是触发了。

**Comment by ziyoung** [comment]
你应该设置 upload 组件的 disabled  属性 https://jsfiddle.net/bLfgmqs8/1/

**Comment by ziyoung** [comment]
虽然在 upload 上设置了 disabled 属性，但是按钮样式没有改变是因为这是 slot 的内容。
