### ISSUE TITLE
[Feature Request] Prevent Popper from closing if clicked outside

### ISSUE THREAD

**Issue by caraffa** [ElemeFE/element#13585]
### Existing Component
Yes

### Component Name
popover

### Description
I'm using the popover like this:

    <el-popover placement="top-start" width="160" v-model="selectorVisible">
      <p>Seleziona le campagne che desideri cancellare e clicca su 'Elimina'</p>
      <div style="text-align: right; margin: 0">
        <el-button size="mini" type="text" @click="selectorVisible = false">Annulla</el-button>
        <el-button type="primary" size="mini" @click="handleDelete">Elimina</el-button>
      </div>
      <div slot="reference" class="el-ghost-reference">
        &nbsp;
      </div>
    </el-popover>

I need the popover to stay open even if the user clicks outside the popper window, but I don't seem to find a way to do that.

Thanks

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by ZTrainWilliams** [comment]
trigger="manual"

**Comment by caraffa** [comment]
Thank you ZTrainWilliams, I apologize, I haven't noticed that in the docs
