### ISSUE TITLE
Can [Feature Request] publish all components?

### ISSUE THREAD

**Issue by iwangx** [ElemeFE/element#13591]
### Existing Component
是

### Component Name
el-scrollbar

### Description
有时候需要对一些组件进行二次封装是发现如下的提示：
```
Unknown custom element: <el-scrollbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
这下懵逼了，引入吧，ts检查又会报错，不引入吧，又会报错，希望各位大佬把能用的都公布出来吧~~~

**Comment by ziyoung** [comment]
`el-scrollbar` 仅仅是满足组件库内部的使用需求，不是一个通用的组件。

**Comment by iwangx** [comment]
@ziyoung 那为什么我自己封装组件的时候会报这个错？是封装的`el-table-column`，然后使用filter后就会报这个错
