### ISSUE TITLE
How does the onClick of the [Bug Report] Notification component execute when a message pops up?

### ISSUE THREAD

**Issue by cnx2016** [ElemeFE/element#13594]
### Element UI version
2.4.11

### OS/Browsers version
Win10 / Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/hatgcyLf/1/](https://jsfiddle.net/hatgcyLf/1/)

### Steps to reproduce
点击成功按钮

### What is Expected?
应该在点击消息框再执行onClick里的代码。

### What is actually happening?
在弹出消息时就执行了onClick里的代码。

**Comment by wacky6** [comment]
麻烦去补一下 js 基础，了解一下回调函数 https://jsfiddle.net/hatgcyLf/2/
