### ISSUE TITLE
使用keep-alive，Tooltip无法自动隐藏。

### ISSUE THREAD

**Issue by aalexlin** [ElemeFE/element#1359]
使用keep-alive，Tooltip无法自动隐藏。
![](https://raw.githubusercontent.com/aalexlin/imgsrouce/master/pic1.png)

### ElementUI version
1.0.0

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.0

**Comment by QingWei-Li** [comment]
可有 demo？我试了下没问题 http://jsfiddle.net/cinwell_li/7jaw4z0w/

```html
<div id="app">
  <keep-alive>
    <el-tooltip content="Top center" placement="top">
      <el-button>Dark</el-button>
    </el-tooltip>
  </keep-alive>
</div>
```

**Comment by aalexlin** [comment]
不，是切换路由时，上一个视图的Tooltip还会继续显示并且不能隐藏了

**Comment by QingWei-Li** [comment]
我拿自己项目试了下还是没问题，可否提供个 demo？不然我也没办法定位问题

**Comment by aalexlin** [comment]
DEMO:https://jsfiddle.net/aalexlkx/73vq1dm5/

**Comment by Nekoooo** [comment]
我也遇到这个问题了
在router-view在面包裹了keep-alive，切换路由的时候气泡没有隐藏

不过这个气泡是el-table组件里面的，添加show-overflow-tooltip属性

![image](https://cloud.githubusercontent.com/assets/17408282/22242518/97917d6c-e25e-11e6-8cf8-e77160c406c3.png)


ElementUI version 1.1.6

OS/Browers version   
OSX Chrome 55

Vue version  2.0.7

**Comment by HyperSimon** [comment]
升级到了 Element 1.2.1还是会存在这种问题

**Comment by QingWei-Li** [comment]
还没发布

**Comment by nailfar** [comment]
@QingWei-Li  
![image](https://user-images.githubusercontent.com/12581226/53544523-4828a300-3b61-11e9-883c-d90c7293b20e.png)
你的代码为何这么优秀

**Comment by nailfar** [comment]
https://jsfiddle.net/h469fney/1/     @QingWei-Li

**Comment by youmin** [comment]
> 我也遇到这个问题了
> 在router-view在面包裹了keep-alive，切换路由的时候气泡没有隐藏
> 
> 不过这个气泡是el-table组件里面的，添加show-overflow-tooltip属性
> 
> ![image](https://cloud.githubusercontent.com/assets/17408282/22242518/97917d6c-e25e-11e6-8cf8-e77160c406c3.png)
> 
> ElementUI version 1.1.6
> 
> OS/Browers version
> OSX Chrome 55
> 
> Vue version 2.0.7

请问你怎么解决的，我也遇到了这个问题

**Comment by hexzhen** [comment]
请问下这个问题解决了吗

**Comment by 1396531115** [comment]
从16年拖到现在都没人解决？

**Comment by wxhqq** [comment]
this.$refs.tooltipRef.handleClosePopper()可解决

**Comment by 807460453** [comment]
该问题现在依然存在，或者更清晰的描述为
点击带有tooltip的cell附近的cell内按钮切换路由，tooltip是关闭状态
但是在路由切换完毕后，该tooltip被激活了
@QingWei-Li
