### ISSUE TITLE
[Bug Report] Selects the parent node, and after lazy loading unfolds, the parent node changes from the original selected state to the unselected state.

### ISSUE THREAD

**Issue by qqcbqqkcel** [ElemeFE/element#13608]
### Element UI version
2.4.11

### OS/Browsers version
windows

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/qqcbqqkcel/s3udtgqb/](https://jsfiddle.net/qqcbqqkcel/s3udtgqb/)

### Steps to reproduce
1.选中第一个节点
2.点击左侧三角形展开
3.选中的父级节点被取消了

### What is Expected?
期待没有被取消，现在的有一个需求是父节点和子节点非级联的关系可以单独选中。使用了树的默认选中 默认展开功能之后父级全被取消了。

### What is actually happening?
如上

**Comment by qqcbqqkcel** [comment]
希望在check-strictly设置为true的时候不用自动取消

**Comment by qqcbqqkcel** [comment]
我看了一下，好像是修复这个bug导致的
https://github.com/ElemeFE/element/pull/12256

**Comment by chenhangbin2008** [comment]
我也遇到了一样的问题，不过是我和一个同事没问题，另外两个同事有这个问题，不知道为什么
