### ISSUE TITLE
[Bug Report] in nuxt project, custom element-ui theme color cause error!

### ISSUE THREAD

**Issue by jsweibo** [ElemeFE/element#13606]
### Element UI version
2.4.6

### OS/Browsers version
Win10 1803/Chrome 70.0.3538.110

### Nuxt version
2.0.0

### Reproduction Link
[https://github.com/jsweibo/learn_nuxt_element-ui](https://github.com/jsweibo/learn_nuxt_element-ui)

### Steps to reproduce
1. create a nuxt.js project, choose integrate element-ui
2. install node-sass and sass-loader
3. create element-variables.scss in /assets/
4. import '~/assets/element-variables.scss' in nuxt.config.js
5. npm run dev
6. open project index in Google Chrome

### What is Expected?
element theme color changed

### What is actually happening?
Invalid or unexpected token

**Comment by jsweibo** [comment]
复现过程
1. 创建一个nuxt项目，创建过程中直接集成element-ui
2. 安装node-sass和sass-loader
3. 在assets/下创建element-variables.scss
4. 在nuxt.config.js的css属性下引入'~/assets/element-variables.scss'
5. npm run dev
6. 打开浏览器进入项目首页
7. 页面提示报错

**Comment by jsweibo** [comment]
```scss
// element-variables.scss
/* 改变主题色变量 */
$--color-primary: teal;

/* 改变 icon 字体路径变量，必需 */
$--font-path: '~element-ui/lib/theme-chalk/fonts';

@import "~element-ui/packages/theme-chalk/src/index";
```

**Comment by jsweibo** [comment]
```js
//nuxt.config.js
module.exports = {
css: [
    // 'element-ui/lib/theme-chalk/index.css'
    '~/assets/element-variables.scss'
  ],
}
```

**Comment by ziyoung** [comment]
> ~element-ui/packages/theme-chalk/src/index

不存在这个文件的。theme-chalk 下的样式都是编译过的。

如果想自定义样式，请参考文档。直接引入编译后的文件吧。

**Comment by zackfly** [comment]
@jsweibo https://github.com/nuxt/nuxt.js/issues/3997

**Comment by chokWing** [comment]
怎么解决
