### ISSUE TITLE
[Feature Request] Synchronous autocomplete suggestions

### ISSUE THREAD

**Issue by nhynes** [ElemeFE/element#13609]
### Existing Component
Yes

### Component Name
autocomplete

### Description
Currently the autocomplete component exposes a callback-based method of setting suggestions which is odd because it doesn't follow the "reactive data binding" pattern of the rest of the Vue framework. It also means that it's very difficult to get this component to work with [vue-instantsearch](https://v2--vue-instantsearch.netlify.com/components/autocomplete).

Suggestion: expose something like a `suggestions` prop through which to pass synchronous suggestions. Compare to [(Vuetify autocomplete `items`](https://vuetifyjs.com/en/components/autocompletes)

**Comment by nhynes** [comment]
If anyone wants a temporary workaround,

```html
<ais-autocomplete>
  <el-autocomplete
    slot-scope="{ currentRefinement, refine, indices }"
    :value="currentRefinement"
    :debounce="0"
    :fetchSuggestions="querySearchAsync(indices)"
    @input="refine">
    ref="searchBar">
  </el-autocomplete>
</ais-autocomplete>
```

and then

```js
export default {
  name: 'App',

  data: () => ({
    indices: null,
  }),

  methods: {
    querySearchAsync(indices) {
      this.$data.indices = indices;
      // call cb immediately to set `autocomplete.loading = false` so that
      // the search box will be hidden when empty search results arrive
      return (_, cb) => (cb(indices[0].hits));
    },
  },

  watch: {
    indices([{ hits }]) {
      // manually populate suggestions whenever they arrive
      this.$refs.searchBar.suggestions = hits;
    },
  },
};
```

**Comment by wacky6** [comment]
This usage is a bit like el-select + remote-method 😅
