### ISSUE TITLE
[Feature Request] wants to provide a functional way to open dialog

### ISSUE THREAD

**Issue by loooSwc** [ElemeFE/element#13601]
### Existing Component
是

### Component Name
dialog

### Description
通常dialog中出现的业务与打开dialog前业务不是同一个（比如列表页中点击编辑按钮打开编辑弹出框），而通过:visible.sync方式来控制dialog的展示，岂不是将dialog中的业务与打开dialog页面的业务绑定在了一起，能否提供一个类似$dialog的方式，通过传入dialog业务的component的方式，来打开一个dialog，这样dialog中的业务可以在自己页面中实现，代码逻辑也更清晰

**Comment by island205** [comment]
有可以参考的例子么？

**Comment by wacky6** [comment]
自行封装一个就行了。 例子 https://github.com/NKMUN/hi.nkmun.cn/blob/master/src/components/SeriousConfirm.js
