### ISSUE TITLE
Does the el-tabs_u content container in the [Bug Report] el-tabs component necessarily need to set overflow: hidden?

### ISSUE THREAD

**Issue by parkyang** [ElemeFE/element#13616]
### Element UI version
2.4.11

### OS/Browsers version
Chrome 70.0.3538.110

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/parkyang/e29tngh3/1/](https://jsfiddle.net/parkyang/e29tngh3/1/)

### Steps to reproduce
直接看效果行：
链接1: https://jsfiddle.net/parkyang/e29tngh3/1/
链接2: https://codepen.io/parkyang/pen/VVVayY

### What is Expected?
能正常显示内部元素的阴影

### What is actually happening?
阴影被overflow:hidden截断了

**Comment by GH1995** [comment]
same here
