### ISSUE TITLE
[datepick]日期控件设置不允许编辑报错

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#1361]
![image](https://cloud.githubusercontent.com/assets/12726826/20620137/358cf18c-b333-11e6-9fa6-7624dcbd52a0.png)
![image](https://cloud.githubusercontent.com/assets/12726826/20620148/40f433be-b333-11e6-986f-85000eb4460b.png)
日期控件editable=false加了这个会报错呀，不管我false有没有加引号又是一样，这应该是你们的问题吧？
传过去的明明是个布尔值啊
版本是1.0.2

**Comment by QingWei-Li** [comment]
`:editable="false"`

**Comment by Leopoldthecoder** [comment]
建议先阅读 Vue 文档 `v-bind` 的[相关内容](http://vuejs.org/v2/api/#v-bind)
