### ISSUE TITLE
[Bug Report] navmenu 纵向vertical导航菜单 可以自定义设置 二级菜单等 展开方式吗 x-placement="right-start"

### ISSUE THREAD

**Issue by ZooTopiaGG** [ElemeFE/element#13611]
### Element UI version
2.4.11

### OS/Browsers version
xx

### Vue version
2.5.17

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
使用 el-menu mode="vertical" 组件 

### What is Expected?
希望能有自定义属性 设置二级菜单展开方向 比如向下 bottom-start  向右 right-start等

### What is actually happening?
e

**Comment by fallowu** [comment]
可以自己加。加了两个属性isPopup,https://gitee.com/fmic/element.git
![image](https://user-images.githubusercontent.com/3997050/53938531-838c1a00-40eb-11e9-9a5f-47cbad75ab52.png)

**Comment by wangyegg1989** [comment]
> 可以自己加。加了两个属性isPopup,https://gitee.com/fmic/element.git
> ![image](https://user-images.githubusercontent.com/3997050/53938531-838c1a00-40eb-11e9-9a5f-47cbad75ab52.png)

你的这个配置的is-popup不行哦，而且还让收起状态不显示菜单弹出了。
