### ISSUE TITLE
In [Bug Report] file upload, files that failed to upload may also appear in file-list

### ISSUE THREAD

**Issue by wanderbaby** [ElemeFE/element#13617]
### Element UI version
2.4.11

### OS/Browsers version
win10企业版

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/e29tngh3/2/](https://jsfiddle.net/e29tngh3/2/)

### Steps to reproduce
大概就是在on-success钩子中返回response中返回的状态是false，但是在图片还是渲染在了uploadFiles中，望解决

### What is Expected?
上传失败的文件就不要渲染在页面里了

### What is actually happening?
但是在图片还是渲染在了uploadFiles中

**Comment by ziyoung** [comment]
重新设置 fileList
