### ISSUE TITLE
Implementation Principle of [Feature Request] Table show-overflow-tooltip

### ISSUE THREAD

**Issue by mingming-tang** [ElemeFE/element#13612]
### Existing Component
是

### Component Name
Table

### Description
Table show-overflow-tooltip 功能非常好用   希望在其它地方也能用上  想问一下你们 Table show-overflow-tooltip 实现原理是怎样的 是否显示tooltip是如何判断的

**Comment by ziyoung** [comment]
Duplicate of #13576
