### ISSUE TITLE
[Feature Request] Enable select just one date at date range

### ISSUE THREAD

**Issue by xkubow** [ElemeFE/element#13621]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
Component should be able to select just one date to define until date or from date.

**Comment by Blanen** [comment]
Don't use date range if you don't want a range?

**Comment by wacky6** [comment]
No plan to support this right now.

If you only want to select one date, why not use a `type='date'`

**Comment by xkubow** [comment]
Because the decision to select just one date should have user no programmer. Yes I can use two picker with type date, but why?
Example:
I have store data where is delivery date. 
Filtering option for the date shout by :
1.) 1.1.2017 - until now (yes, here is possibility to set default date to now)
2.) 1.1.2017 - 1.1.2018 (this is possible)
3.) from first record - 1.1.2018 (this is not possible with daterange)

I thing the third option should be possible (with not selected firs date). All three options are date range and I have to have it covered in my solution. Now I have to use two separated date picker for defining range for the filter data. That's not correct when you have daterange possibility.

**Comment by EdwinBetanc0urt** [comment]
https://github.com/ElemeFE/element/issues/17685
