### ISSUE TITLE
[Bug Report] el-select is broken by object as value

### ISSUE THREAD

**Issue by Blanen** [ElemeFE/element#13625]
### Element UI version
2.4.11

### OS/Browsers version
Firefox: 63.0.3 ; Chrome: 70.0.3538.110

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/m7860gx9/2/](https://jsfiddle.net/m7860gx9/2/)

### Steps to reproduce
Have any :value of the the el-option be an object

### What is Expected?
The value-object gets inserted into the v-model and the label is shown as chosen the option's label.

### What is actually happening?
The chosen label is actually just the label of the last option, while the v-model is still the correct value( the object).

When a chosen value is an object, all other object's option's labels are shown in blue.
When a chosen value is not an object, but they are present in the options, all options in the dropdown become blue.

**Comment by Blanen** [comment]
A version with the object only being on a single option's value so people don't think it's due to non-unique value.

**Comment by Blanen** [comment]
Something goes wrong in here:

https://github.com/ElemeFE/element/blob/dev/packages/select/src/select.vue#L531

**Comment by Blanen** [comment]
Having the value BE the whole item also breaks the select, but differently:

https://jsfiddle.net/m7860gx9/4/

**Comment by Blanen** [comment]
@wacky6 My original usecase was every possible value being an object. I think I'm using the key-value correctly here?
If it's meant that the value-key is the key to the choice object's value then that should just be 'value' here, right? Like so: 
https://jsfiddle.net/m7860gx9/9/

I made every value unique too since it states "unique identity key name for value". I mean, the value key will never be unique so that might be a misnomer, but the option object's value on the non-unique key is unique.

But neither of these work correctly either

**Comment by wacky6** [comment]
The correct usage for `value-key` is: https://jsfiddle.net/bqzeknc5/1/

**Comment by Blanen** [comment]
@wacky6 Weird but thanks.

**Comment by ITmrHoang** [comment]
you can  using  JSON.stringify(item) for value of el-option
