### ISSUE TITLE
[Bug Report] Element-ui el-tree tree control @check-change event problem

### ISSUE THREAD

**Issue by AiMe1991** [ElemeFE/element#13629]
### Element UI version
2.4.11

### OS/Browsers version
Google Chrome  版本 69.0.3497.81（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/AiMe/eywraw8t/483039/](https://jsfiddle.net/AiMe/eywraw8t/483039/)

### Steps to reproduce
第一步：选择：“一级 1”（相当于全选）
会有4个alert弹框，会提示每一个复选框是否被选中

第二部：选择：“三级 1-1-2”（由选择状态变为未选择状态）
选项“一级 1”、“二级 1-1”、“三级 1-1-1”提示选中true，“三级 1-1-2”提示未选中false

第三步：选择：“三级 1-1-2”（由未选择状态变为选择状态）
选项“一级 1”、“二级 1-1”、“三级 1-1-1”，““三级 1-1-2””提示选中true

### What is Expected?
期望的效果，每次点击复选框的时候，@check-change事件只执行一次，返回的是本次选择节点的状态，以及该节点数据。应用场景：我们选择改节点，当然是为了获取该节点的状态，以及该节点的数据。
例如：回调还是要根据选择的节点的id进行下一步操作，如果@check-change事件触发多次，那么回调函数也会触发多次，这样是不是不合理？

### What is actually happening?
每次点击复选框的时候@check-change事件会执行多次。

**Comment by ziyoung** [comment]
文档对 check-change 的描述如下：

> 节点选中状态发生变化时的回调

因为节点之间有联动，导致该事件触发频繁。

**Comment by AlexZhong22c** [comment]
的确是因为联动，一次操作会触发多次该事件。

百度一下“函数节流”，节省调用即可。
