### ISSUE TITLE
[Feature Request] Allow to change arrow icon of a node

### ISSUE THREAD

**Issue by ivar-os** [ElemeFE/element#13623]
### Existing Component
Yes

### Component Name
Tree

### Description
For our implementation, we like to be able to exchange the arrow left on the node (either pointing to the right or down) for a custom icon.

The request: the ability to change the icon of a node into a custom icon.

Example:
![screenshot 2018-11-29 13 22 31](https://user-images.githubusercontent.com/44036196/49221638-06f5eb00-f3da-11e8-91bd-116fa6837d9b.png)
We would like to change the arrow in node one for the custom icon on the right of the arrow.

**Comment by ziyoung** [comment]
Set `icon-class`.
