### ISSUE TITLE
Label wrapping in [Feature Request] el-form-item causes layout disorder

### ISSUE THREAD

**Issue by 7boy** [ElemeFE/element#13637]
### Existing Component
是

### Component Name
el-form-item

### Description
el-form-item中 label内容过长会导致换行而引起布局错乱
建议将label的行高改小，垂直居中

**Comment by ziyoung** [comment]
设置 label-width 来解决吧。

**Comment by 7boy** [comment]
> 设置 label-width 来解决吧。

那太麻烦了，我自己写了一套样式来覆盖。实现了不管几行文字都垂直居中
