### ISSUE TITLE
Can the automatic creation option of [Feature Request] select control increase the success of event control creation?

### ISSUE THREAD

**Issue by flowbywind** [ElemeFE/element#13631]
### Existing Component
是

### Component Name
select

### Description
现有select组件自动创建选项 不能加条件判断 直接就创建成功了 想着通过创建的时候 增加事件控制 里面有逻辑判断是否可以增加成功

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by ziyoung** [comment]
这个功能优先级很低，我们暂时没有计划去实现该功能。
