### ISSUE TITLE
[Bug Report] el-menu in router mode should expose router-links so that users can "Open Link in New Tab"

### ISSUE THREAD

**Issue by freeman-g** [ElemeFE/element#13635]
### Element UI version
2.4.11

### OS/Browsers version
Windows 10 / Version 70.0.3538.102 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/fuyrvn6L/2/](https://jsfiddle.net/fuyrvn6L/2/)

### Steps to reproduce
See the reproduction link. A normal router-link places an anchor on the DOM and then users can Ctrl click or right click to open link in a new tab. Unfortunately, with the el-menu, this does not work.

Note: I have also tried placing a router-link inside the el-menu, like this `<el-menu><router-link>click me</router-link></el-menu>`. This is not ideal either though because then a user has to click on the words themselves and not overall menu item.

### What is Expected?
I expect el-menu in router mode to expose a router-link/anchor

### What is actually happening?
pure javascript is being used to perform a router.push

**Comment by island205** [comment]
Received, we see how to support
