### ISSUE TITLE
[Feature Request] form validate Unit test

### ISSUE THREAD

**Issue by mazeteam** [ElemeFE/element#13639]
### Existing Component
Yes

### Component Name
el-form

### Description
Can you provide one example case how to unit test the function?

because I try to use jest fake the validate function

always say this.$refs[formName].validate is not a function,

just want to test the code after the "other code"

thanks

this.$refs[formName].validate((valid) => { 
if (!valid) {
console.error("err");
}

//other code
.......
.......
})

**Comment by ziyoung** [comment]
Use `find` method. https://vue-test-utils.vuejs.org/api/wrapper/#find-selector

```js
wrapper.find({ ref: 'myForm' }).trigger('click')
```

**Comment by mazeteam** [comment]
I try to trigger click but will receive undefined?
I look at your test case .. but I still get the error is "this.$refs[formName].validate is not a function,"
I try to follow your code, but will get undefined?

<template>

<el-form :rules="rules" ref="dataForm" :model="d">
        <el-form-item label="firstname" prop="firstname">
          <el-input v-model="d.firstname"></el-input>
        </el-form-item>
    <el-button  type="primary" @click.native="testUpdate()" id="btn-update">confirm</el-button>
</el-form>
</template>



methods {
testUpdate() {

this.$refs[formName].validate((valid) => {
if (!valid) {
console.error("err");
}

//other code
.......
.......
})

}
}

**Comment by 4lp** [comment]
Can we reopen this issue? I'm having the same problem in my unit tests

**Comment by 4lp** [comment]
I was having the same issue in my unit tests using the `shallowMount` method from `vue-test-utils` - I resolved it by using `mount` instead.
