### ISSUE TITLE
In the latest edition of Bug Report, when the `data'attribute changes, the highlighted rows are out of order

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#13643]
### Element UI version
2.4.11

### OS/Browsers version
ubuntu 18.04

### Vue version
2.5.18-beta.0

### Reproduction Link
[http://jsfiddle.net/mnr0e2ef/4/](http://jsfiddle.net/mnr0e2ef/4/)

### Steps to reproduce
步骤：

- 选中第二行

- 点Add按钮

- 结果高亮虽然保持了,但是不是之前的第二条数据了

- #3023 只解决了一种特殊情况,就是下一次的数据只是上一次数据基础上,追加了数据的情况.
如果数据是去后台筛选,或者服务端排序后,当前行就乱了
通过调试:

1. 数据变化时,出发了updateCurrentRow
2. updateCurrentRow设置了currentRow
3. 'store.states.currentRow'被触发:
var newRow = rows[data.indexOf(newVal)];
寻找新行,但是此时rows还是老的tr标签集合,还没有更新为最新数据,如果数据是上述所说,那么newRow的索引位置就很可能不对了.
很抱歉,能力有限,无法提供pull
@Leopoldthecoder

### What is Expected?
正确的保持选中行

### What is actually happening?
没能正确的保持选中行

**Comment by ziyoung** [comment]
@elfman table hightlight 行计算有问题。大佬看一下。

**Comment by lerit** [comment]
咋关了呢?@ziyoung

**Comment by elfman** [comment]
@ziyoung
https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-body.js#L106-L140
 是这里的watcher引起的，实际在store的currentRow是正确的。这里的两个watcher我觉得都可以去掉，非必要的情况下不应直接改变dom的，会引起不必要的重绘和性能问题，上面的hoverRow可以直接在`getRowClass`里改变

**Comment by zzzgit** [comment]
这个提交可能有问题。
我的项目用的是2.6.0版本，现在table有问题，如果把光标放在table上，然后用滚轮滚动页面，比较卡。

回退到2月1日发布的2.5.4版本，则没有问题。

这期间，只有两个3个commit针对table组件做了修改。

我怀疑引入问题的，是这个commit。


@island205 @elfman

**Comment by zzzgit** [comment]
要重现这个问题，需要有很复杂的table，里面装一些小组件

**Comment by zzmikl** [comment]
https://github.com/ElemeFE/element/commit/a54802c71a8e1922087d3f364b139749da70af74#diff-9b450c00d0a9dec0ffad5a3176972e40    
这次问题的修复导致table 开销会很大  也会导致span-methods 部分bug 例如在span-methods 中使用了外部的一些变量做层级辅助合并的情况

**Comment by ziyoung** [comment]
@elfman 目前的修改让 table 的性能变差。抽象了一个简单的 demo https://jsfiddle.net/oe2b4hqt/

**Comment by TaylerTao** [comment]
2.5.4版本中，每页500条的table很流畅；2.6.0之后就很卡

**Comment by zzzgit** [comment]
哈哈哈，我是最先發現這個問題的，但是後來我優化了自己的代碼，問題沒法重現了
他們叫我提供demo，我提供不出來
