### ISSUE TITLE
[Feature Request] Multi-check box radio box sets the type function of the default selected value asymmetrically

### ISSUE THREAD

**Issue by qylcx7758** [ElemeFE/element#13649]
### Existing Component
是

### Component Name
  \<el-table-column type="selection" >\</el-table-column>

### Description
- 框架允许为多选框这些设置选中时的默认类型，假设这一个表单中需要发送的值是一个数字，那么是通过类似`active-value` 的属性，实现选中多选框就能直接发送数字；
- 但是当做一些修改功能时，例如接收到后台传来的值是该数字，但是多选框上面的`active-value` 这些属性却无法识别为布尔值，变成勾选中的状态，必须先将后台传过来的值做转换；
- 然后因为读取传过来需要先转换值，可能在一系列常规的转换操作后，发现还不如在保存的时候，直接对多选框的默认布尔值类型的value直接做判断，转成数字来的方便。

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
