### ISSUE TITLE
[Bug Report] NavMenu Navigation Menu Bar is not fully displayed when the menu list is large

### ISSUE THREAD

**Issue by zhaojinxiong** [ElemeFE/element#13641]
### Element UI version
2.4.11

### OS/Browsers version
Chrome版本 70.0.3538.102

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/zhaojx/eywraw8t/488112/](https://jsfiddle.net/zhaojx/eywraw8t/488112/)

### Steps to reproduce
NavMenu 导航菜单栏 收起时当菜单列表很多的时候会展示不全

### What is Expected?
期待给菜单栏加个滚动

### What is actually happening?
菜单多级导致 有些显示不全

**Comment by georgyfarniev** [comment]
Please fix reproduction link

**Comment by zhaojinxiong** [comment]
https://jsfiddle.net/zhaojx/eywraw8t/488112/

**Comment by zhaojinxiong** [comment]
> Please fix reproduction link

https://jsfiddle.net/zhaojx/eywraw8t/488112/

**Comment by island205** [comment]
add to product backlog
