### ISSUE TITLE
Can [Feature Request] Popover dock HTML and triggered HTML be separated

### ISSUE THREAD

**Issue by BillionChen** [ElemeFE/element#13645]
### Existing Component
是

### Component Name
Popover

### Description
when i use Popover Component, i need Popover fixed by outter HTML but trigger by its innerHTML

我在使用弹出框时，需要让弹出框停靠在一个稍微大的区域旁边，点击其中较小区域时，弹出框显示。

当前需求：我有一个按钮，左边是可点击其他操作部分，右边有下拉箭头，点击箭头弹出弹出框
如果我用trigger="click" 则不能实现该需求，整个按钮都是触发区域，
如果用trigger="manual" 则不能在点击弹出框外部时自动收起弹出框

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by ziyoung** [comment]
推荐你使用 vue-portal 来实现该功能。
