### ISSUE TITLE
[Bug Report] Cascader cascade selector made an error after specifying props

### ISSUE THREAD

**Issue by jiafulu** [ElemeFE/element#13654]
### Element UI version
2.4.11

### OS/Browsers version
版本 70.0.3538.110（正式版本） window10  /（64 位）

### Vue version
2.5.17

### Reproduction Link
[https://codepen.io/jiafu/project/editor/ZJKWRK](https://codepen.io/jiafu/project/editor/ZJKWRK)

### Steps to reproduce
例子用的是官网Cascader 级联选择器中最后一个，加了点条件，可以看重现连接（codepen的）
条件： 1. filterable  2. :props="{ value: 'label' }"
输入 选择项 【 一致】   搜索后无法选中

### What is Expected?
1. filterable  2. :props="{ value: 'label' }"
希望选中的值与显示的一致
即 显示  【指南 / 设计原则 / 一致】
值  【 ['指南', '设计原则', '一致'] 】

### What is actually happening?
指定了 :props="{ value: 'label' }" 后出错

**Comment by elfman** [comment]
label属性在组件内会被转化，所以不能将`value`设置为`label`

**Comment by elfman** [comment]
`label`在`Cascade`组件内部会被转变，不能将其作为`value`的对应的属性。
