### ISSUE TITLE
[Bug Report] el-switch inside el-transfer scoped slot will trigger the checkbox when clicked

### ISSUE THREAD

**Issue by wangjunji** [ElemeFE/element#13655]
### Element UI version
2.4.11

### OS/Browsers version
Mac OSX

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7056/](https://jsfiddle.net/mmx38qxw/7056/)

### Steps to reproduce
el-switch inside el-transfer scoped slot will trigger the checkbox when clicked

### What is Expected?
el-switch inside el-transfer scoped slot won't trigger the checkbox when clicked on the switch

### What is actually happening?
el-switch inside el-transfer scoped slot will trigger the checkbox when clicked

**Comment by ziyoung** [comment]
You can block click event of Switch.
