### ISSUE TITLE
The date component displays the dates of two months at a time

### ISSUE THREAD

**Issue by tiajslwm** [ElemeFE/element#13668]
### Existing Component
否

### Component Name
一次显示多个月的时间

### Description
我们是做机票网站的，目前的日期组件无法满足一次显示两个月日期，只有范围选择，希望能早日开发

**Comment by tiajslwm** [comment]
我想知道你们有开发的意向吗

**Comment by tiajslwm** [comment]
所有机票网站都是选择两个月的，这功能我们行业很受欢迎的，希望你们早日开发谢谢

**Comment by ziyoung** [comment]
在下一个版本中，我们会把日历组件单独拆分，用户可以基于该组件自行实现该功能。
