### ISSUE TITLE
Can support customRender like ant-design table within row-header cell?

### ISSUE THREAD

**Issue by vuchan** [ElemeFE/element#13666]
### Element UI version
2.4.11

### OS/Browsers version
Chrome LTS

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://vuecomponent.github.io/ant-design-vue/components/table-cn/#components-table-demo-editable-rows](https://vuecomponent.github.io/ant-design-vue/components/table-cn/#components-table-demo-editable-rows)

### Steps to reproduce
i ever written a tree-table use `el-table` component, but i found one thing is `el-table-column` has no any custom render method with row-header cell, it means i cannot show diff header type between `select` and `expand` in [one column](http://element-cn.eleme.io/#/zh-CN/component/table#table-column-attributes).

### What is Expected?
希望一列里，可以存在两个 table-column-type

### What is actually happening?
目前并不存在这样的功能

**Comment by vuchan** [comment]
最后再看代码的时候找到了 solt header, 之前看文档不够仔细，多有打扰。

[Source Code](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-column.js#L298)
[Document](http://element-cn.eleme.io/#/zh-CN/component/table#table-column-scoped-slot)
```js
<el-table-column>
  <template name="header" slot-scope="{ row }">
    {{ row[rowKey] }}
  </template>
</el-table-column>
```

**Comment by zhangnan000** [comment]
我在使用时，发现slot header无法有效的将dom挂载，element-ui使用的2.4.8，请问你有遇到过吗

**Comment by vuchan** [comment]
I found those code at [here](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-column.js#L452), hope it can help.

```js
    if (this.$scopedSlots.header) {
      if (this.type === 'selection') {
        console.warn('[Element Warn][TableColumn]Selection column doesn\'t allow to set scoped-slot header.');
      } else {
        this.columnConfig.renderHeader = (h, scope) => this.$scopedSlots.header(scope);
      }
    }
```

**Comment by vxhly** [comment]
如今 vue 的最新版本中不再支持 slot-scope ,更加推荐使用 v-slot，那么在未来的迭代当中，v-slot 会不会被使用到，或者说也像 render-header 一样出一个 render-cell来自定义表格的单元格内容呢
