### ISSUE TITLE
[Bug Report] tree get checked Nodes bug

### ISSUE THREAD

**Issue by felixfujing** [ElemeFE/element#13661]
### Element UI version
2.4.11

### OS/Browsers version
win7/谷歌浏览器

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、通过文本框搜索树节点完成以后
2、勾选树节点的复选框，会把隐藏掉的节点也默认勾选上

### What is Expected?
理论上应该只勾选显示的节点

### What is actually happening?
隐藏的和显示的都会勾上

**Comment by ziyoung** [comment]
是的，会把所有选中的节点（包括隐藏的）返回。你自己过滤一下。
