### ISSUE TITLE
[Feature Request] Able to specify direction(up/down) for vertical slider

### ISSUE THREAD

**Issue by uniquejava** [ElemeFE/element#13672]
### Existing Component
Yes

### Component Name
slider

### Description
I'd like to leverage vertical slider as some fancy scroll bar (to measure minutes passed in an event)  However, currently the vertical slider always starts from bottom(I scroll up and the value increases), how can I let it start from top, so that when i scroll down the minutes increase,  e.g: I want the top is 0 (minute), the bottom is 60(minutes).

I tried to set its initial value as 60.  The slider now starts from top, but the style is incorrect, also it has has some bugs, for example,  the starting tooltip is incorrect (expect 0, but it's 60)

I tried to use css `transform: rotate(-180deg)` ,  I am too naive, the scrolling is awkward.

so, could we add some property like `direction=up` and `direction=down` for this vertical slider component.

Thank you.

**Comment by uniquejava** [comment]
The following is the current effect I implemented, I am able to modify the css and initial value for slider to be 60! but it feels quite awkward. (I want to the initial value to be 0 and it starts from top.)

![feature-request](https://user-images.githubusercontent.com/1049271/49526127-2618df00-f8ea-11e8-85c0-366004e7823a.jpg)

ありがとうございます。
谢谢!
Thank you.

**Comment by ziyoung** [comment]
pr welcome
