### ISSUE TITLE
[Feature Request] recommends adding onChoose events to el-upload

### ISSUE THREAD

**Issue by charmfocus** [ElemeFE/element#13670]
### Existing Component
是

### Component Name
el-upload

### Description
建议给el-upload增加onChoose事件.
当选中要上传的文件后的事件钩子,以处理选中的文件数量是多少个,从而得知什么时候所有文件上传成功!

**Comment by ziyoung** [comment]
> 什么时候所有文件上传成功

通过 onChange 与 onSuccess 配置来实现该功能。

**Comment by charmfocus** [comment]
如果自定义了http-request,则无法触发onSuccess事件,无法判断什么时候所有文件上传成功,如果有了onChoose事件,我们自定义的http-request事件中就可以处理了.

**Comment by charmfocus** [comment]
> > 什么时候所有文件上传成功
> 
> 通过 onChange 与 onSuccess 配置来实现该功能。
> 我们暂时不打算支持该功能。
如果自定义了http-request,则无法触发onSuccess事件,无法判断什么时候所有文件上传成功,如果有了onChoose事件,我们自定义的http-request事件中就可以处理了.

**Comment by charmfocus** [comment]
> > 什么时候所有文件上传成功
> 
> 通过 onChange 与 onSuccess 配置来实现该功能。
> 我们暂时不打算支持该功能。

如果自定义了http-request,则无法触发onSuccess事件,无法判断什么时候所有文件上传成功,如果有了onChoose事件,我们自定义的http-request事件中就可以处理了.
