### ISSUE TITLE
[Bug Report] Suggestion on TimePicker

### ISSUE THREAD

**Issue by kshiw** [ElemeFE/element#13676]
### Element UI version
2.4.11

### OS/Browsers version
windows 10

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://jsfiddle.net/kshiw/chpj6drf/](https://jsfiddle.net/kshiw/chpj6drf/)

### Steps to reproduce
当要改变时间选择器的值，会出现前面日期不能大于后面日期，这在用户体验上来说不是很好；
假设程序运行时，设置时间区间为09:00 - 09:10；
危害：当新用户使用产品时会被误导9点往后时间不可以选择

### What is Expected?
开始时间都可以被选择，然后根据前面选择的时间，结束时间再计算，希望加个可配置属性满足这个需要

### What is actually happening?
当用户要修改9点到10点，必须把后面时间9点调成比10点还往后的时间，前面的开始时间才能选择9点往后

**Comment by island205** [comment]
Sorry, we have no plan to support this.
