### ISSUE TITLE
[Bug Report] DatePicker parse error

### ISSUE THREAD

**Issue by fakaka** [ElemeFE/element#13682]
### Element UI version
2.4.11

### OS/Browsers version
Windows 10 / Chrome 70

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://jsfiddle.net/vsmj012/nfyxm42u/1/](https://jsfiddle.net/vsmj012/nfyxm42u/1/)

### Steps to reproduce
1. 设置 DatePicker 的 format 为 "yyyy年MM月dd日HH时mm分ss秒"
2. 选择后头部显示的名称不对 `2018年12月28秒 日00时00分00秒`

![image](https://user-images.githubusercontent.com/12379312/49577676-e6520600-f982-11e8-8d66-0ac13a0b7308.png)

### What is Expected?
选择后头部显示的名称正确

### What is actually happening?
选择后头部显示的名称不对

**Comment by fakaka** [comment]
`packages\date-picker\src\util\index.js`  line 262, 269

``` js 
export const extractDateFormat = function(format) {
  return format
    .replace(/\W?m{1,2}|\W?ZZ/g, '')
    .replace(/\W?h{1,2}|\W?s{1,3}|\W?a/gi, '')
    .trim();
};

export const extractTimeFormat = function(format) {
  return format
    .replace(/\W?D{1,2}|\W?Do|\W?d{1,4}|\W?M{1,4}|\W?y{2,4}/g, '')
    .trim();
};
```

``` sh
> 'yyyy年MM月dd日HH时mm分ss秒'.replace(/\W?m{1,2}|\W?ZZ/g, '').replace(/\W?h{1,2}|\W?s{1,3}|\W?a/gi, '').trim();
< "yyyy年MM月dd秒"
```

``` sh
> 'yyyy年MM月dd日HH时mm分ss秒'.replace(/\W?D{1,2}|\W?Do|\W?d{1,4}|\W?M{1,4}|\W?y{2,4}/g, '')
< "日HH时mm分ss秒"
```

**Comment by DelingAlieZ10** [comment]
使用deepseek 优化正则如下
var extractDateFormat = exports.extractDateFormat = function extractDateFormat(format) {
  return format.replace(/\s*[hH]{1,2}:\d{2}(?::\d{2,3})?(?:\s*[aApP][mM])?\s*$/gi, '').trim();
};
