### ISSUE TITLE
没有动画效果吗？目前看到只有 一个 loading

### ISSUE THREAD

**Issue by istommao** [ElemeFE/element#1368]

**Comment by furybean** [comment]
你说的动画效果指定是？感觉 loading 算不上 UI 中的动画效果？

**Comment by istommao** [comment]
fadein fadeout 这类的

**Comment by reverland** [comment]
这里有些能用

https://github.com/ElemeFE/element/blob/27affb22c0b5535cb0d31dc1fb4c0c33c5c3044c/packages/theme-default/src/common/transition.css

**Comment by istommao** [comment]
好的谢谢
