### ISSUE TITLE
[Bug Report] tree control, after searching for a node, select the parent node of the search node, and select all the child nodes (including those not searched) under the parent node.

### ISSUE THREAD

**Issue by sunjunwu** [ElemeFE/element#13692]
### Element UI version
2.4.11

### OS/Browsers version
chrome 

### Vue version
2.5.12

### Reproduction Link
[https://jsfiddle.net/M_sun/zpc2e57r/5/](https://jsfiddle.net/M_sun/zpc2e57r/5/)

### Steps to reproduce
1、搜索一个节点后
2、选中该搜索节点的父级节点
3、会选中该父级节点下所有的子节点(包括未搜索的节点)

### What is Expected?
搜索节点后，选中节点应只选中搜索后的节点

### What is actually happening?
搜索节点后，选中节点应只选中搜索后的节点

**Comment by island205** [comment]
Sorry, we have no plan to support this.
