### ISSUE TITLE
[Bug Report] Tree tree control draggingNode.parent

### ISSUE THREAD

**Issue by Hannicke** [ElemeFE/element#13694]
### Element UI version
2.4.11

### OS/Browsers version
windows 10 / chrome 70.0.3538.110

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7074/](https://jsfiddle.net/mmx38qxw/7074/)

### Steps to reproduce
拖动某节点

### What is Expected?
希望可以获取到该节点所离开时的parent.data

### What is actually happening?
draggingNode.parent= null

**Comment by ziyoung** [comment]
监听 node-drag-start 事件 https://jsfiddle.net/mmx38qxw/7075/
