### ISSUE TITLE
[Feature Request] How to bind events to elementUI component in JSX?

### ISSUE THREAD

**Issue by wqcstrong** [ElemeFE/element#13691]
### Existing Component
Yes

### Component Name
el-button

### Description
There will be an error when I tried to bind `click` event to elementUI component in JSX.
For example:

```
export default class someComponent extends Vue {
        someMethod = () => {

        }
        render(h) {
                return (
                       ...
                       <el-button onClick={this.someMethod}>Click ME!</el-button>
                       ....
                )
        }
}
```
And the error is:  `Invalid handler for event "click": got undefined`.

I also had tried to use `on-click`, and fails.

PLEASE!

**Comment by ziyoung** [comment]
Use `Vue.extend` or `Vue.component` https://cn.vuejs.org/v2/api/#Vue-extend

**Comment by wqcstrong** [comment]
@ziyoung 不能在<el-xxx> 组件上绑定吗？

**Comment by wqcstrong** [comment]
@ziyoung 不能elementUI的组件上绑定吗
