### ISSUE TITLE
[Bug Report] Radio button  doesn't change color when it is disabled if set change fill and text-color in radio-group

### ISSUE THREAD

**Issue by justlp** [ElemeFE/element#13695]
### Element UI version
2.4.11

### OS/Browsers version
Chrome

### Vue version
2.5.18-beta.0

### Reproduction Link
[https://jsfiddle.net/just_lp/3mtoxyfn/9/](https://jsfiddle.net/just_lp/3mtoxyfn/9/)

### Steps to reproduce
1. Set color in 'fill' and 'text-color' properties at 'radio-group'
2. Set ":disabled='true'" at radio-button

### What is Expected?
Button's color change if it disabled.

### What is actually happening?
Button's color doesn't change.

**Comment by elfman** [comment]
you have changed the default fill color, so the default disabled radio style is properly not you want.  
You can change the `fill` color when you found the radio value is disabled.
