### ISSUE TITLE
datepicker的input最好设成readonly。

### ISSUE THREAD

**Issue by ibufu** [ElemeFE/element#137]
一个小建议，datepicker的input最好设成readonly。因为现在在input里输东西会出现意想不到的事情。

**Comment by fishpaw** [comment]
@ibufu ，「可控」是 Element 的一大设计原则，所以我们对于 datepicker 的设计初衷，就是既能够方便地选择，也能够直接快捷地输入。但就目前的公开版本而言，输入体验做得确实不够好，这一点日后会进一步调校优化。

**Comment by henryzp** [comment]
@ibufu ，我个人觉得没有必要。。输东西，就让用户自己去输好了。在提交的时候，判断下是否为正确的日期格式即可。

**Comment by QingWei-Li** [comment]
@henryzp 格式化每一次用户输入都会在 format，还有其实是可以输入

**Comment by ibufu** [comment]
我也支持做成可输入的，只是现在输入后，组件会错误地设置成其它日期

**Comment by spademan** [comment]
@ibufu 我都是自己设置成 readonly
