### ISSUE TITLE
[Bug Report] Chrome 70 or more, there will be problems with scrollbars in dialog

### ISSUE THREAD

**Issue by shady-xia** [ElemeFE/element#13708]
### Element UI version
2.4.11

### OS/Browsers version
windows 7、chrome 71.0.3578.80

### Vue version
2.5.19

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
需要满足的条件
1、分辨率较低的屏幕，比如在控制面板-显示中将外观设置为125%的1920x1080的设备或更低
2、chrome 70及以上

在dialog中包含滚动条时，滚动条内部的内容不会被展示出来，但是如果缩放页面到一定程度，就会展示出来

### What is Expected?
内容能被展示出来
在升级chrome到70之前，展示一直是正常的，升级了之后就有了这个问题，我不知道是否是chrome的问题，在issue里也看到了相关的问题。我试了很多的情况，大概是有overflow属性的就出现该问题，同时该问题疑似也和positions:relative有关，不知chrome官方做了哪些变更。

### What is actually happening?
在dialog中包含滚动条时，滚动条内部的内容不会被展示出来

无缩放的情况，此时滚动条内部的内容展示不出来：
![tim 20181210155839](https://user-images.githubusercontent.com/20945955/49718259-7a58f180-fc51-11e8-9962-53c8e414404b.png)

![tim 20181210160508](https://user-images.githubusercontent.com/20945955/49718564-66fa5600-fc52-11e8-82a6-76a5494ffc79.png)

缩放到90%的情况，此时展示正常：
![tim 20181210160031](https://user-images.githubusercontent.com/20945955/49718340-b2f8cb00-fc51-11e8-90f7-d63cda1366e7.png)

![tim 20181210160523](https://user-images.githubusercontent.com/20945955/49718565-66fa5600-fc52-11e8-906d-015f09e42a99.png)

**Comment by yeomanyang** [comment]
遇到了同样的问题，但是在safari上无法复现？

**Comment by shady-xia** [comment]
> 遇到了同样的问题，但是在safari上无法复现？

我目前只在chrome70和71上发现了这个问题，火狐是正常的，我觉得应该是chrome的问题
https://developers.google.com/web/updates/2018/09/chrome-70-deps-rems 下面的评论中有人提到类似的问题

**Comment by ziyoung** [comment]
如果页面开始是 100%还会存在这个问题吗？

**Comment by shady-xia** [comment]
在正常的1920x1080，浏览器100%没这个问题；如果windows将外观显示设置为125%的中等布局，浏览器是初始100%也会有这个问题，和分辨率有关。
我觉得这应该是新版chrome的bug，我通过将append-to-body和modal-append-to-body都设为true暂时解决了这个问题。
