### ISSUE TITLE
[Feature Request] recommends adding onChoose or onSelect events to el-upload

### ISSUE THREAD

**Issue by charmfocus** [ElemeFE/element#13704]
### Existing Component
是

### Component Name
el-upload

### Description
在自定义http-request事件中需要得知选中的文件是什么,有多少个,进而进行后续逻辑处理.
比如在自定义http-request中需要知道什么时候所有文件处理完成.
而在文件选择器中,文件选中时应该是要有一个回调事件的,这应该是很正常的需求,请添加此功能,谢谢~

**Comment by charmfocus** [comment]
如果自定义了http-request,则无法触发onSuccess事件,无法判断什么时候所有文件上传成功,如果有了onChoose事件,我们自定义的http-request事件中就可以处理了.

**Comment by qbob** [comment]
我也遇到同类问题：自定义http-request实现上传，无法触发onSuccess事件，多选文件上传无法知道是否全部上传成功

**Comment by chinahuarvin** [comment]
如何获取选择文件个数，需要做一些处理，自定义了http-request,onScussess 无法触发

**Comment by charmfocus** [comment]
> @charmfocus @qbob @chinahuarvin 自定义了http-request，所有上传的过程就是由你们自己控制了，组件内怎么知道你们什么时候上传完成？又怎么知道何时触发`onSuccess`？你们自己应该很容易知道什么时候上传完成吧，再自己手动触发不就行了吗？

在自定义了http-request后,当多选文件时,http-request是单个文件处理的回调,也就是说一次选了几个文件,就回调几次,我是不知道当时一次选择了几个的,需要知道这个数字,是需要在选择时进行回调处理

**Comment by charmfocus** [comment]
> @charmfocus
> 
> > 而在文件选择器中,文件选中时应该是要有一个回调事件的,这应该是很正常的需求,请添加此功能,谢谢~
> 
> `on-change`事件不行吗？

on-change应该也是单文件事件回调,也无法得知一次选择了几个文件

**Comment by charmfocus** [comment]
@elfman 
回调就是在源码https://github.com/ElemeFE/element/blob/16311d1e32f27d9a949e5924ceefd20e1726eee4/packages/upload/src/upload.vue#L62-L67
中`this.uploadFiles(files)`之前加入`this.onChoose && this.onChoose(files);`这样的逻辑

**Comment by charmfocus** [comment]
@elfman 少改了一个
        element/types/upload.d.ts
      文件,未添加on-file语法提示

**Comment by neatstudio** [comment]
好象没有 :on-file 事件啊。无法触发。。这个例子里有https://github.com/elfman/element/blob/a7990c7cb67f7230264222e696da77b566591906/examples/docs/en-US/upload.md，但实际中无效（使用了自定义http-request）
