### ISSUE TITLE
[Bug Report] el-option render failed when undefined Array in v-for loop

### ISSUE THREAD

**Issue by kum1ko** [ElemeFE/element#13709]
### Element UI version
2.4.9

### OS/Browsers version
Windows 10 / Chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/m7860gx9/19/](https://jsfiddle.net/m7860gx9/19/)

### Steps to reproduce
Line 8: Replace "validValue" to "validValue.someProps"

### What is Expected?
No error, show a el-select component on the result area

### What is actually happening?
Traversing an attribute with a value of undefined will result in an render error, but will work fine on other tabs, such as "<span v-for='i in value.undefinedProp'"></span>

**Comment by ziyoung** [comment]
I think it's not a bug.
I try to compile this template by using `Vue.compile`. There's no difference between them.
```js
Vue.compile(`<div>
  <span v-for="i in validValue.someProps">{{ i }}</span>
        <el-select v-model="value">
            <el-option v-for="(item, i) in validValue.someProps">
            </el-option>
        </el-select>
</div>`)

// render
function anonymous() {
  with (this) {
    return _c(
      "div",
      [
        _l(validValue.someProps, function(i) {
          return _c("span", [_v(_s(i))]);
        }),
        _c(
          "el-select",
          {
            model: {
              value: value,
              callback: function($$v) {
                value = $$v;
              },
              expression: "value"
            }
          },
          _l(validValue.someProps, function(item, i) {
            return _c("el-option");
          })
        )
      ],
      2
    );
  }
}
```

**Comment by ziyoung** [comment]
Delete `el-select` and it works fine. https://jsfiddle.net/m7860gx9/22/
I suggest you ask Vue developers for more help.
