### ISSUE TITLE
[Bug Report] Two Paginations with same current page

### ISSUE THREAD

**Issue by aalasolutions** [ElemeFE/element#13712]
### Element UI version
2.4.11

### OS/Browsers version
Chrome latest, Mac Mojave 

### Vue version
2.5.19

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7087/](https://jsfiddle.net/mmx38qxw/7087/)

### Steps to reproduce
Added pagination on top of table and on bottom of table, when server responded, i updated the current page field. but in pagination it is not updating. If I use the top one. bottom pagination dont update. and if I use bottom, top didnt updated.

### What is Expected?
Current Page is a variable, and if that get changed. The pagination selected page should also update

### What is actually happening?
Both pagination are using same variables, but on change event, when I click a page number on one pagination, 2nd is not updating

**Comment by ziyoung** [comment]
`:current-page` but not `:current_page` https://jsfiddle.net/mmx38qxw/7094/
