### ISSUE TITLE
[Bug Report] I need the el-upload upload component to change the sorting function, preferably drag and drop. (I need the el-upload upload component to have the ability to change the sort, preferably drag and drop.)

### ISSUE THREAD

**Issue by BaYunmo-Lry** [ElemeFE/element#13719]
### Element UI version
2.4.11

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Existing components do not have the ability to change sorting.（现有的组件不具备更改排序这个功能）

### What is Expected?
Have the ability to drag and drop changes.(拥有拖拽更改排序的功能)

### What is actually happening?
Existing components do not have the ability to change sorting.（现有的组件不具备更改排序这个功能）

**Comment by elfman** [comment]
你这issue选择类型了，这属于`Feature Request`，而不是`Bug Report`

**Comment by BaYunmo-Lry** [comment]
> 你这问题选择类型了，这属于`Feature Request`，而不是`Bug Report`

我不太熟悉操作。。。

**Comment by ziyoung** [comment]
基于 sortable.js 自行实现吧。
