### ISSUE TITLE
[Feature Request] Z-index Manager

### ISSUE THREAD

**Issue by Richard-Choooou** [ElemeFE/element#13710]
### Existing Component
否

### Component Name
z-index

### Description
是否可以将popup z-index管理暴露接口给用户调用，每次调用可以获取到当前的可用层级，这样就不用担心用户的页面元素覆盖组件或者被组件覆盖。

**Comment by ziyoung** [comment]
我们倾向于提供一个组件专门来实现这个功能。组件的设计方案还在构思中，请继续关注。
