### ISSUE TITLE
[Bug Report] Dropdown bug

### ISSUE THREAD

**Issue by Maadtin** [ElemeFE/element#13715]
### Element UI version
2.4.11

### OS/Browsers version
Chrome 70

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Using dropdown from example

### What is Expected?
The dropdown to work

### What is actually happening?
Dropdown is giving a lot of console errors "Error in mounted hook: "TypeError: Cannot read property '0' of undefined" and the dropdown icon is displaying several times on the screen.

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
