### ISSUE TITLE
[Bug Report] Using v-model in v-for, the el-switch/el-select style is not updated

### ISSUE THREAD

**Issue by chen2aaron** [ElemeFE/element#13720]
### Element UI version
2.4.11

### OS/Browsers version
MacOS 10.12.6 / Chrome 70.0

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7097/](https://jsfiddle.net/mmx38qxw/7097/)

### Steps to reproduce
Click the Change button, the watch listens to the change of rawOptions, and the form is rendered.

When I click the el-switch or el-select input box, the style did not change. But when I type any character in the target input box, the style changes. 

I am confused and hope to get answers. Thank you.

### What is Expected?
when I click the el-switch or el-select input box, the style change

### What is actually happening?
when I click the el-switch or el-select input box, the style did not change

**Comment by elfman** [comment]
你这是对Vue不熟悉，Vue无法监听对象新添加的属性，所以不会在新属性改变后立即更新页面。在你的例子里，你应该在`validateForm.options`内预先添加所需要的属性或者使用`Vue.$set`方法进行赋值，https://jsfiddle.net/mmx38qxw/7100/

**Comment by chen2aaron** [comment]
哇～ 谢谢大佬解惑，看了下文档大概了解了。
https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
