### ISSUE TITLE
[Bug Report] autocomplete can not work with textarea

### ISSUE THREAD

**Issue by laomu1988** [ElemeFE/element#13724]
### Element UI version
2.4.11

### OS/Browsers version
mac/chrome70

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/nepdtzo4/](https://jsfiddle.net/nepdtzo4/)

### Steps to reproduce
click textarea

### What is Expected?
show suggestion

### What is actually happening?
show nothing

**Comment by LilyWakana** [comment]
autocomplete内部处理逻辑没有考虑到实际输入框是textarea的情况，其实控制台报错了。

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
