### ISSUE TITLE
[Bug Report] [Debug Report] the menu will cover the input tag when Browser height is reduced to a certain height in ElSelect Component

### ISSUE THREAD

**Issue by jan-wong** [ElemeFE/element#13726]
### Element UI version
2.4.11

### OS/Browsers version
all

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7106/](https://jsfiddle.net/mmx38qxw/7106/)

### Steps to reproduce
Make the page height smaller

### What is Expected?
the menu will autoscroll when browser height is reduced to a certain height

### What is actually happening?
the menu will cover the input tag when Browser height is reduced to a certain height in ElSelect Component

**Comment by island205** [comment]
pr welcome
