### ISSUE TITLE
[Bug Report] el-step component change Process-Status property is invalid

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#13723]
### Element UI version
2.4.11

### OS/Browsers version
windows 7 64位 旗舰版/ Chrome 版本 71.0.3578.80 （64 位）

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/p2ec8Lxf/1/](https://jsfiddle.net/p2ec8Lxf/1/)

### Steps to reproduce
点击页面中的 改变processStatus 按钮

### What is Expected?
步骤3的图标和样式应该和步骤一和步骤二的图标和样式一致，变成success状态

### What is actually happening?
步骤3的图标和样式未发生任何变化

**Comment by island205** [comment]
你看下文档 http://element.eleme.io/#/zh-CN/component/steps#steps-attributes，应该用 active 控制步骤
