### ISSUE TITLE
The show-overflow-tooltip property of the [Bug Report] table has a bug on the full screen and the content is beyond the screen.

### ISSUE THREAD

**Issue by Mrli2016** [ElemeFE/element#13735]
### Element UI version
2.4.11

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7109/](https://jsfiddle.net/mmx38qxw/7109/)

### Steps to reproduce
table组件的Table-column-item设置show-overflow-tooltip属性时，如果提示的文字过长时，左边的内容部分无法查看。

### What is Expected?
能够完整展示提示内容，最好能够实现tooltip的其他属性设置。

### What is actually happening?
部分内容无法显示

**Comment by island205** [comment]
Sorry, we have no plan to support this.

tooltip 从交互体验上并不支持展示太长的文本。
