### ISSUE TITLE
Default-expand-all of [Bug Report] el-tree cannot be set dynamically

### ISSUE THREAD

**Issue by jianhunxia** [ElemeFE/element#13734]
### Element UI version
2.4.8

### OS/Browsers version
window10 chrome V70.0.3538.67

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/jianhunxia/xdpzgrfc/](https://jsfiddle.net/jianhunxia/xdpzgrfc/)

### Steps to reproduce
1、选中展开
2、取消展开
3、树都没有响应，不能动态设置折叠和展开。

### What is Expected?
希望能设置为动态的，因为目前的解决方式都是通过遍历设置每个节点的展开属性，非常不好用。目前解决方法如下：
      for (var i = 0; i < this.$refs.treeControl.store._getAllNodes().length; i  ) {
        this.$refs.treeControl.store._getAllNodes()[i].expanded = val
      }

### What is actually happening?
动态设置无响应。

**Comment by ziyoung** [comment]
default-expand-all 属性不支持这样的功能。手动操作数据来实现吧。后续可能会开放这类的工具函数。
