### ISSUE TITLE
[Bug Report] Table dynamic settings max-height and table-column fixed mix will report errors in the console

### ISSUE THREAD

**Issue by CielNonam** [ElemeFE/element#13731]
### Element UI version
2.4.11

### OS/Browsers version
windows 7 / Google Chrome 70.0.3538.110

### Vue version
2.5.21

### Reproduction Link
[www.github.com](www.github.com)

### Steps to reproduce
在table的column里面设置了fixed之后，table中的去这么设置“ :max-height=“ ‘500’ ” ”会报错误：
Error in render: "TypeError: Cannot read property 'length' of null"
但是效果max-height的效果会成功的展示出来
红色警告很刺眼，麻烦解决一下

### What is Expected?
table 动态设置max-height 与table-column中fixed 混用会在控制台不报错

### What is actually happening?
在table的column里面设置了fixed之后，table中的去这么设置“ :max-height=“ ‘500’ ” ”会报错误：
Error in render: "TypeError: Cannot read property 'length' of null"

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
