### ISSUE TITLE
[Feature Request] wants TableColumn's sort-orders attribute to support sortable as custom as well

### ISSUE THREAD

**Issue by joenil** [ElemeFE/element#13732]
### Existing Component
是

### Component Name
ElTableColumn

### Description
表格需要支持后端排序，但是后端接口只有两种排序：降序和升序（值为0和1），目前排序控件没法在两个值之间轮换（多了一个null），希望sortable为custome能够同样支持sort-orders

**Comment by liuchuzhang** [comment]
在表格上给他一个默认排序 `default-sort` ，然后给 `:sort-orders="['ascending','descending']"` ，当你监听 `sort-change` 就只有两种情况了。这些[文档](http://element-cn.eleme.io/#/zh-CN/component/table#pai-xu)上都有。

**Comment by joenil** [comment]
@liuchuzhang https://jsfiddle.net/13dhew78/1/ 不可以。

**Comment by joenil** [comment]
![image](https://user-images.githubusercontent.com/11400674/49867563-db491b00-fe45-11e8-92c2-d7199cd24ce3.png)
你们的文档。@liuchuzhang

**Comment by liuchuzhang** [comment]
是可以的。 `sort-orders` 这个是 table-column 的属性。
https://jsfiddle.net/13dhew78/5/ 在你的例子上改了一下

**Comment by ziyoung** [comment]
@liuchuzhang thanks.

**Comment by RookieLittleFatty** [comment]
![image](https://user-images.githubusercontent.com/32049377/82184692-a2568500-991a-11ea-9465-fa99586299ba.png)
设置了之后，点击三角符号，仍然会出现null的情况
