### ISSUE TITLE
[Bug Report] date-picker type="week" value-format 不可用

### ISSUE THREAD

**Issue by lianmt** [ElemeFE/element#13746]
### Element UI version
2.4.11

### OS/Browsers version
10.14.1

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/lianmt/mmx38qxw/7112/](https://jsfiddle.net/lianmt/mmx38qxw/7112/)

### Steps to reproduce
use date-picker type="week"

### What is Expected?
use date-picker type="week"

### What is actually happening?
use date-picker type="week"

![](https://user-images.githubusercontent.com/20921259/49872808-2f0f3080-fe55-11e8-9b40-36dae1d9d7bb.png)

**Comment by wacky6** [comment]
value-format 不支持 WW， 看文档

**Comment by lianmt** [comment]
> value-format 不支持 WW， 看文档

能举个例子吗，都试过了，没有找到正确的方法
