### ISSUE TITLE
[Bug Report] el-select with remote-method cannot remove selected label

### ISSUE THREAD

**Issue by al002** [ElemeFE/element#13741]
### Element UI version
2.4.11

### OS/Browsers version
macOS 10.4.1 Chrome  71.0.3578.80

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/63b971u5/](https://jsfiddle.net/63b971u5/)

### Steps to reproduce
1. enter keyword in input
2. select any option
3. click input again, it should be select label text
4. use backspace delete label
5. click outside, make input blur

### What is Expected?
 label is empty string, and call remote method

### What is actually happening?
label still same as previous

**Comment by elfman** [comment]
you can use `clearable` attribute to remove the label

**Comment by al002** [comment]
I'm using `clearable` now. but in this situation, `selectedLabel` same as `query` variable, won't call remote method, it is considered as a feature?

**Comment by island205** [comment]
pr welcome
