### ISSUE TITLE
[Feature Request] Can DateTime Picker's disabled Date be limited to time and seconds?

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/element#13759]
### Existing Component
是

### Component Name
DateTimePicker

### Description
DateTimePicker的disabledDate能限制到时分秒吗？目前看来只能限制年月日

**Comment by wacky6** [comment]
No. checking `30 * 24 * 3600 === 2592000` (or `24*3600 === 86400` time instances when time is changed are too expensive. Use selectableRange.

And, date is date as the name suggests.

**Comment by MaJiaXuan** [comment]
@wacky6  有没有例子？

**Comment by qappleh** [comment]
> 编号检查`30 * 24 * 3600 === 2592000`（或`24*3600 === 86400`时间更改的时间实例太贵。使用selectableRange。
> 
> 而且，日期是顾名思义的日期。

<el-date-picker                 
            v-model="form.planTime"
            type="datetime"
            :picker-options="{selectableRange: '09:00:00 - 20:30:00'}">
</el-date-picker>
我在el-date-picker上加这个selectableRange不起作用啊

**Comment by 378406712** [comment]
> > 编号检查`30 * 24 * 3600 === 2592000`（或`24*3600 === 86400`时间更改的时间实例太贵。使用selectableRange。
> > 而且，日期是顾名思义的日期。
> 
> 我在el-date-picker上加这个selectableRange不起作用啊

computed: {
      pickerOptions(){
        return {
          // 日期选择限制
          disabledDate(time) {
            return time.getTime() > Date.now();
          },
          // 时间选择限制
          selectableRange: "10:00:00 - 23:59:59"
        }
      },
    }
  };

**Comment by simplefeel** [comment]
> > 编号检查`30 * 24 * 3600 === 2592000`（或`24*3600 === 86400`时间更改的时间实例太贵。使用selectableRange。
> > 而且，日期是顾名思义的日期。
> 
> 我在el-date-picker上加这个selectableRange不起作用啊

更新element-ui到最新版

**Comment by mengriri** [comment]
![image](https://github.com/ElemeFE/element/assets/83011631/cb31d762-523d-4d94-9ce0-9a82167ad1e4)
这里秒级禁用没有加上class

**Comment by mengriri** [comment]
![image](https://github.com/ElemeFE/element/assets/83011631/568b9fb1-b97d-46f5-b6cc-b130cd35634a)
这里的样式不对
