### ISSUE TITLE
Is it normal for the Popover button in [Bug Report] table to trigger the filter and method bound in table data every click?

### ISSUE THREAD

**Issue by Rickykurt** [ElemeFE/element#13755]
### Element UI version
2.4.11

### OS/Browsers version
macOS High Sierra 10.13.6 / Google Chrome 70.0.3538.110 / Firefox 63.0.3

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7115/](https://jsfiddle.net/mmx38qxw/7115/)
![ele](https://user-images.githubusercontent.com/1176984/49976785-61687d00-ff7e-11e8-8041-cdbd8520a29d.gif)

### Steps to reproduce
1.点击右侧删除按钮
2.查看控制台
3.每次点击删除按钮和popover中的按钮，都会触发 filters 中的 filterAddress 和 methods 中的 filterDate，而且是输出所有数据的。

### What is Expected?
点击删除按钮时不要触发filters中和methods中的方法

### What is actually happening?
点击删除按钮时触发了filters中和methods中的方法

**Comment by wacky6** [comment]
这是正常的视图更新。
