### ISSUE TITLE
[Bug Report] Setting default-sort to Table triggers sort-change events directly

### ISSUE THREAD

**Issue by Dinrer** [ElemeFE/element#13750]
### Element UI version
2.4.11

### OS/Browsers version
win10/chrome 70.0.3538.77

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/Dingii/ej0fbrsv/1/](https://jsfiddle.net/Dingii/ej0fbrsv/1/)

### Steps to reproduce
给Table设置default-sort后会直接触发sort-change事件。
设置默认排序不应该触发sort-change事件，如果要触发建议在返回参数中加以区分是默认触发还是点击触发的

### What is Expected?
设置默认排序不触发sort-change事件，或者在返回参数中加以区分是默认触发还是点击触发的

### What is actually happening?
直接触发sort-change事件，无法区分是默认值触发的还是点击触发的

**Comment by WormGirl** [comment]
我也是，远端排序会导致同时发多个请求
