### ISSUE TITLE
[Bug Report] toggleRowSelection doesn't work using reserved row selection after data changes

### ISSUE THREAD

**Issue by MarvinXu** [ElemeFE/element#13772]
### Element UI version
2.4.11

### OS/Browsers version
win7 / chrome71

### Vue version
2.5.21

### Reproduction Link
[https://codesandbox.io/s/r70818o344](https://codesandbox.io/s/r70818o344)

### Steps to reproduce
1. select some row in page1
2. toggle between pages and then toggle back to page1
3. click close button on tags below

### What is Expected?
toggle corresponding row selection

### What is actually happening?
cannot toggle row selection

**Comment by maimai123** [comment]
please fix this bug

**Comment by PengJack** [comment]
这个 api 确实没设计好，主要是因为传递的第一个参数是个对象，属于引用类型，地址变化了后调用该方法就会有问题，可以这样解决：

![image](https://user-images.githubusercontent.com/13834609/157848024-a28f89b0-4fe9-4dcb-b1f7-549de4dd0924.png)
![image](https://user-images.githubusercontent.com/13834609/157848054-bacc27b0-4a7d-46f8-970e-cbac8ceffc4d.png)

**Comment by shady-xia** [comment]
> 这个 api 确实没设计好，主要是因为传递的第一个参数是个对象，属于引用类型，地址变化了后调用该方法就会有问题，可以这样解决：
> 
> ![image](https://user-images.githubusercontent.com/13834609/157848024-a28f89b0-4fe9-4dcb-b1f7-549de4dd0924.png) ![image](https://user-images.githubusercontent.com/13834609/157848054-bacc27b0-4a7d-46f8-970e-cbac8ceffc4d.png)

It works! you save my ass!
