### ISSUE TITLE
[Feature Request] How to send additional parameters to on-success callback of Upload component?

### ISSUE THREAD

**Issue by tiny09** [ElemeFE/element#13776]
### Existing Component
是

### Component Name
Upload

### Description
I am working on a project, where there is a scenario I need to use a v-for loop to render Upload component, and I want to send additional parameters to on-success callback to write different codes for corresponding for-loop element. The code I write is as follows, and I want to send additional "v.key" to on-success callback. How could I do that? Thanks a lot.
<img width="362" alt="upload" src="https://user-images.githubusercontent.com/27919695/50039973-a8d23480-0076-11e9-86aa-ea0258ebd2aa.png">

**Comment by tiny09** [comment]
<img width="362" alt="upload" src="https://user-images.githubusercontent.com/27919695/50039952-598c0400-0076-11e9-863b-3352d150ea29.png">

**Comment by HelenDias** [comment]
Hi! 
How you fixed this? I'm with the same problem.
