### ISSUE TITLE
[Bug Report] When the key of data contains dot sign, it will display blank

### ISSUE THREAD

**Issue by elephantme** [ElemeFE/element#13775]
### Element UI version
2.4.11

### OS/Browsers version
mac/chrome

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/b86znuhq/](https://jsfiddle.net/b86znuhq/)

### Steps to reproduce
1. 将官方demo中的日期所对应的key由'date'改为'date.test'
2. 渲染结果为空白

### What is Expected?
正常渲染出结果

### What is actually happening?
渲染结果为空白

**Comment by elfman** [comment]
键名不能包含小数点，`date.test`是指`date`的子属性`test`，对应的结构是{ date: { test: xxx } }，建议使用其它分隔符
