### ISSUE TITLE
[Feature Request] Can InputNumber support add prefixes and suffixes?

### ISSUE THREAD

**Issue by jianhao** [ElemeFE/element#13777]
### Existing Component
是

### Component Name
InputNumber

### Description
Can you provide a prefix or suffix attribute for a counter so that some number, such as percentage or currency, becomes particularly convenient? I currently complete this function by packaging the components myself, although I can do it, but it is particularly inconvenient, so I beg the big guys to add this function for ordinary developers, please.

![demo](https://user-images.githubusercontent.com/30502487/50040390-75df6f00-007d-11e9-85a2-063b6e8dacb7.gif)

**Comment by oliverbenns** [comment]
Why would this have been added feature been added to inputs and not number inputs?

**Comment by arslanyunus** [comment]
+1

**Comment by songStar0904** [comment]
+2
