### ISSUE TITLE
嵌套dialog时出现问题

### ISSUE THREAD

**Issue by wanghaolu** [ElemeFE/element#1378]
### ElementUI version

1.0.2
### OS/Browers version

chrome 54
### Vue version

2.1.3
### Reproduction Link

http://jsfiddle.net/vk08n9xp/
### Steps to reproduce
在一个dialog中嵌套一个dialog，当嵌套的dialog显示出来后界面样式就出错了
### What is Expected?
可以把dialog做来和嵌套就好了。
本来不需要嵌套dialog的，由于没有tree select组件就自己实现了一个用dialog来弹出选择框，刚好又是在一个dialog里面再弹就遇到这个问题了
tree select 的需求已经在 https://github.com/ElemeFE/element/issues/1377 里面提出来了，希望开发组能考虑下，或者提供一个通用组件，我们可以根据自己需求来自定义选择框的样式和内容

**Comment by wanghaolu** [comment]
#1377

**Comment by Leopoldthecoder** [comment]
如果是为了模拟 TreeSelect，先看看能不能避免嵌套 Dialog 吧。
