### ISSUE TITLE
[Bug Report] Using the checkbox group's fill property doesn't change the checkbox color

### ISSUE THREAD

**Issue by jimenezmaximiliano** [ElemeFE/element#13798]
### Element UI version
2.4.11

### OS/Browsers version
macOS mojave / Google Chrome 70.0.3538.110

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/u9sfvL7p/](https://jsfiddle.net/u9sfvL7p/)

### Steps to reproduce
1. Run the fiddle

### What is Expected?
The checkbox box should have a new color (#ff0000)

### What is actually happening?
It uses the default color

**Comment by languanghao** [comment]
`fill` only works for `el-checkbox-button` type checkbox

**Comment by jimenezmaximiliano** [comment]
I didn't get that from the docs. Is there a reason for it not being compatible with el-checkbox?

**Comment by wacky6** [comment]
I've checked the source code. `:fill` only works for el-checkbox-button inside el-checkbox-group. Maybe the english doc needs clarification. 

`:fill` can be made to support el-checkbox, current implementation uses a `<span>` element to show the checked tick, it can accept `background-color`.

**Comment by rowthan** [comment]
希望支持自定义传入color属性改变背景色

**Comment by rowthan** [comment]
```
seriesArray = [{name: '分享量',field: 'a', color: '#6EA3FF', },
  { name: '点赞量',field: 'b',color: '#808CFF',}];

<el-checkbox
  v-for="(item,index) in seriesArray"
  :key="index"
  :label="item.field"
  :style=" `--tooltip-color: ${item.color};` ">
  {{ item.name }}
</el-checkbox>
<style>
    .el-checkbox__input.is-checked .el-checkbox__inner{
        background-color: var(--tooltip-color);
        border-color: var(--tooltip-color);
    }
</style>
```
