### ISSUE TITLE
upload的thumbnail-mode设为true时，不会显示图片列表，只显示当前最后上传的图片

### ISSUE THREAD

**Issue by Robin-front** [ElemeFE/element#138]
### ElementUI version
1.0.0-rc.4

### Vue version
2.0.0-rc.6

### Steps to reproduce
完全使用官网demo的例子
```
<el-upload
          action="/redwood/sys/Common/uploadFile.do?type=1"
          type="drag"
          :thumbnail-mode="true"
          :multiple="true"
          :show-uploadList="true"
          :before-upload="handleBeforeupload"
          :on-preview="handlePreview"
          :on-success="handleSuccess"
          :on-error="handleError"
          :on-remove="handleRemove">
          <i class="el-icon-upload"></i>
          <div class="el-dragger__text">将文件拖到此处，或<em>点击上传</em></div>
          <div class="el-upload__tip" slot="tip">只能上传jpg/png文件，且不超过500kb</div>
</el-upload>
```
### What is Expected?
应该显示已上传的图片列表，并且是缩略图模式
### What is actually happening?
upload的thumbnail-mode设为true时，不会显示图片列表，只显示当前最后上传的图片

**Comment by fishpaw** [comment]
@Robin-front ，你说的应该是说 Upload 的「上传单个图片」的控件吧？该控件确实只支持上传单个图片，所以不会有图片列表，只会显示最近一次上传的图片缩略图。

**Comment by Robin-front** [comment]
@fishpaw 有意向会加上预览图片列表吗

**Comment by Robin-front** [comment]
另外 rc4，会报这个错：
`vue.common.js?e881:2527 [Vue warn]: Duplicate presense of slot "footer" found in the same render tree - this will likely cause render errors. (found in component <el-dialog>)`

**Comment by Leopoldthecoder** [comment]
@Robin-front 关于 `Duplicate presense of slot "footer"` 这个错，请确认你项目的 Vue 版本是 2.0.0-rc.6

**Comment by Robin-front** [comment]
@Leopoldthecoder thx, my faults.

**Comment by fishpaw** [comment]
@Robin-front ，「上传多个图片」的 upload 控件正在进行中，这个控件会有预览图片的列表。

**Comment by Robin-front** [comment]
@fishpaw 静待佳音。：）

**Comment by Duanhaomei** [comment]
没看到有thumbnail-mode这个属性啊
