### ISSUE TITLE
[Bug Report] el-table multilevel header switching, navigation layout disorderly

### ISSUE THREAD

**Issue by 1740380018** [ElemeFE/element#13800]
### Element UI version
2.4.11

### OS/Browsers version
deepin/谷歌70

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/nxyvj5o8/](https://jsfiddle.net/nxyvj5o8/)

### Steps to reproduce
表头从多级表头切换一级表头的时候，就会出现表头显示不全

### What is Expected?
正常显示

### What is actually happening?
表头只显示了前几列，而且高度异常的大

**Comment by elfman** [comment]
表格数据差异那么大为啥不用`v-if`弄两个表格？

**Comment by elfman** [comment]
@1740380018 找到问题根源了，修改column的key就行了，你不能将`index`作为column的key，否则切换后vue发现column的key保持不变就不会重新渲染。将key设置为`key + item.title`，保持切换后key必定不一样就不会出现错误了 https://jsfiddle.net/HarlanLuo/qw6ntgbs/

**Comment by 1740380018** [comment]
@elfman 也就是说每次渲染，保持key跟上次不一致或者说new Date().valueOf()，是吧？

**Comment by 1740380018** [comment]
谢谢，确实可以了 @elfman
