### ISSUE TITLE
[Bug Report] placeholder does not display

### ISSUE THREAD

**Issue by DictatorLee** [ElemeFE/element#13801]
### Element UI version
2.4.1

### OS/Browsers version
360浏览器10  版本号： 10.0.1581.0  内核版本：63.0.3239.132

### Vue version
2.3.3

### Reproduction Link
[https://github.com/ElemeFE/element/issues/10743](https://github.com/ElemeFE/element/issues/10743)

### Steps to reproduce
el-input 中 placeholder 失效，placeholder属性在外层的div上，不在input上
换成2.2.1版本的element就正常了

### What is Expected?
el-input 中 placeholder 失效，placeholder属性在外层的div上，不在input上
换成2.2.1版本的element就正常了

### What is actually happening?
el-input 中 placeholder 失效，placeholder属性在外层的div上，不在input上
换成2.2.1版本的element就正常了

**Comment by sfgn** [comment]
I'm having the same issue on 2.4.11. Looking into the component for el-input, placeholder is not mentioned in the file at all - but it is mentioned in the input.d.ts file.

**Comment by a5740** [comment]
我刚刚解决了这个问题 请将vue 和 Element UI升级到最新版，
我的项目现在是 vue 2.6.8 + element-ui 2.6.1 没问题

update vue and Element UI to the latest version ，my programe vue 2.6.8 + element-ui 2.6.1 now，it's ok

**Comment by AllenField** [comment]
我在开发一个组件，需要使用render方法创建这个组件，而这个组件内部使用了Element-UI的el-input组件。

el-input将inheritAttrs声明为false，接着使用$attrs来获取外界传入的placeholder。

在通过render方法创建el-input的vnode时，如果将placeholder放在被创建的vnode的props中，则placeholder不会被解析到el-input的$attrs中。

只有将placeholder放在被创建的vnode的attrs中时，才能在el-input的$attrs中找到传入的placeholder。

场景复现：https://jsfiddle.net/fubai7/a2znbx94/

Vue Issue：https://github.com/vuejs/vue/issues/10172
