### ISSUE TITLE
Clicking the Caret in a Select should display the options

### ISSUE THREAD

**Issue by mindbits** [ElemeFE/element#1381]
Users expect that clicking the caret opens the select box and displays the options but this does not happen, the caret has no event and the text has to be clicked which is unexpected behaviour for many:

http://element.eleme.io/#/en-US/component/select

http://element.eleme.io/#/en-US/component/pagination

**Comment by Leopoldthecoder** [comment]
It's a known bug (#1220) and fixed in #1253.
