### ISSUE TITLE
[Bug Report] ``this. $refs. upload. submit ()``dosen't work

### ISSUE THREAD

**Issue by Rooaw** [ElemeFE/element#13812]
### Element UI version
2.4.11

### OS/Browsers version
windows chrome

### Vue version
2.5.21

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
1.handleImageAdded 事件被触发
2.触发后调用 文件上传前 的钩子
3.接着调用 this.$refs.upload.submit()

### What is Expected?
调用 this.$refs.upload.submit() 后成功上传到七牛云

### What is actually happening?
没有上传成功，且其他上传钩子函数比如 上传失败上传成功 都没有触发

**Comment by i7eo** [comment]
解决了么？

**Comment by wacky6** [comment]
重现链接呢
