### ISSUE TITLE
[Bug Report] El Upload always sending cookies

### ISSUE THREAD

**Issue by kbedra-tbscg** [ElemeFE/element#13826]
### Element UI version
2.4.11

### OS/Browsers version
Chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/charlie_cheetah/heb1f2wz/](https://jsfiddle.net/charlie_cheetah/heb1f2wz/)

### Steps to reproduce
set cookie
upload file

### What is Expected?
cookies not sent in request

### What is actually happening?
cookies sent in request

**Comment by elfman** [comment]
you can set cookie by passing it to  props `headers`

**Comment by embulakpa** [comment]
> you can set cookie by passing it to props `headers`

The problem is that I don't want them. My current workaround is by passing custom xhr request via `http-request` attribute. But it could be much simpler with `:with-credentials="false"`

**Comment by kbedra-tbscg** [comment]
> you can set cookie by passing it to props `headers`
 
The problem is that I don't want them. My current workaround is by passing custom xhr request via `http-request` attribute. But it could be much simpler with `:with-credentials="false"`

**Comment by elfman** [comment]
`with-credentials` also needs to change http headers, it is duplicate with `headers` in some ways.
I don't think it is necessary to add this prop just for simpler using.

**Comment by kbedra-tbscg** [comment]
> `with-credentials` also needs to change http headers, it is duplicate with `headers` in some ways.
> I don't think it is necessary to add this prop just for simpler using.

So what's the solution here to forbid sending cookies? Put empty object to `headers` prop?

**Comment by elfman** [comment]
Sorry, I made a mistake, please ignore what I said above.
`Upload` use raw `XMLHttpRequest` to send request, you can find the usage of `withCredentials` in the official [document](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials).
Read the note in that document `Note: This never affects same-site requests.`
So this is not bug of ElementUI

**Comment by kbedra-tbscg** [comment]
Thanks for the explanation. So the only way is to use own `http-request` function. This one works for me:
```
uploadRequest(upload) {
	const formData = new FormData(); // Currently empty
	formData.append('file', upload.file, upload.file.filename);
	const requestOptions = {
		method: 'POST',
		credentials: 'omit',
		body: formData,
	}

	return fetch(actionURL, requestOptions)
}
```
