### ISSUE TITLE
[Bug Report] Problems with Table and tooltip

### ISSUE THREAD

**Issue by IrvingZhao** [ElemeFE/element#13824]
### Element UI version
2.4.11

### OS/Browsers version
windows chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7139/](https://jsfiddle.net/mmx38qxw/7139/)

### Steps to reproduce
1. 构建表格，在表格前方或后方 设置固定列
2. 在指定列中，添加 tooltip 组件，并设置为手动展示
3. 悬停指定到指定列上

### What is Expected?
在悬停到列上时，弹出tooltip

### What is actually happening?
在悬停到列上时，tooltip会出现两次

**Comment by IrvingZhao** [comment]
补充，tooltip 相关操作已经在列属性上找到，其他激活区域操作也会有同样问题，望解决

**Comment by ziyoung** [comment]
Duplicate of #13576
