### ISSUE TITLE
[Bug Report] DatePicker (week type) first week of year and last week of year don't display correctly.

### ISSUE THREAD

**Issue by suyi91** [ElemeFE/element#13832]
### Element UI version
2.4.11

### OS/Browsers version
mac os x 10.14.2 / chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7141/](https://jsfiddle.net/mmx38qxw/7141/)

### Steps to reproduce
choose 2018/12/31

![](https://i.loli.net/2018/12/20/5c1b46cd6cb1e.jpg)
![](https://i.loli.net/2018/12/20/5c1b46cd7a7d5.jpg)

### What is Expected?
date-table panel 2018-12:
the last row is active

date-table panel 2019-1:
the first row is active

### What is actually happening?
date-table panel 2018-12:
the last row is active

date-table panel 2019-1:
the first row isn't active

**Comment by suyi91** [comment]
https://github.com/ElemeFE/element/blob/f3bf6ee15832ff55234efd9ddf98d2ea731f7081/packages/date-picker/src/basic/date-table.vue#L324-L325

I think the year check on L325 should be removed.

**Comment by wacky6** [comment]
Then you should make a PR.

Note, the year check should not be removed, but it should handle edge cases like this one.

**Comment by suyi91** [comment]
> Then you should make a PR.
> 
> Note, the year check should not be removed, but it should handle edge cases like this one.

Maybe we should check `newDate` with `this.value`. 
If they are equal, their line should be active.

I'll make a PR soon.

**Comment by wacky6** [comment]
fixed https://github.com/ElemeFE/element/pull/13883
