### ISSUE TITLE
[Feature Request]  Whether Dialog can be dragged with the mouse

### ISSUE THREAD

**Issue by zccccccc** [ElemeFE/element#13831]
### Existing Component
no

### Component Name
Dialog dialog box

### Description
Whether Dialog can be dragged with the mouse

**Comment by wacky6** [comment]
No.

Why it should be draggable. dialog come with modal overlay, you won't be able to interact with other DOM elements when the dialog is open.

**Comment by JackLiuInNC** [comment]
In fact, there will be such a scenario: users need to drag the dialog to see the selection on the original page or the content blocked by the dialog。 If there is no drag function, they can only close the dialog first and then click on the dialog, which is not convenient。@wacky6

**Comment by anrananran** [comment]
@wacky6 “可控 Controllability， 用户决策：根据场景可给予用户操作建议或安全提示，但不能代替用户进行决策；“
