### ISSUE TITLE
[Feature Request] Set the default value, but want the panel to display today

### ISSUE THREAD

**Issue by AyerCai** [ElemeFE/element#13833]
### Existing Component
是

### Component Name
DatePicker

### Description
设置了日期选择组件的 is-model，
default-value就不再生效了，
但是想要面板显示在今日页面而不是当前is-model写入的日期页面，
不知道除了default-value以外还有什么办法能做到。

**Comment by wacky6** [comment]
麻烦给 DEMO。 文档里没有提到过 is-model

**Comment by AyerCai** [comment]
..不好意思 是v-model

**Comment by AyerCai** [comment]
..不好意思 是v-model 现在才看到当时打错了= =

**Comment by wacky6** [comment]
v-model 非空，那么已经选了日期，当然会显示到已经选择的日期。为什么会有需要让日历显示到别的日期的需求

**Comment by AyerCai** [comment]
@wacky6
emmm主要是业务问题吧，你可以看我的demo
当前有一个项目的终止日期，终止日期不能早于当前日期。
项目可以修改，在修改的时候会回显当时选择的终止日期，如果这个人要修改项目终止日期同样不能早于当前日期
假设当时终止日期是去年6月28 所以回显了6月28 但是现在选择需要选择今年2月28号以后的日期，面板显示了去年的就要按好几下到可选日期...
想说有没有单独能操控面板显示日期的方法...

**Comment by wacky6** [comment]
可以hack，直接修改内部面板的状态。 https://jsfiddle.net/zn53ygeq/

注意，以后版本更新可能会导致这个做法失效。
