### ISSUE TITLE
[Bug Report] Collapsed NavMenu item shows outline when focusing

### ISSUE THREAD

**Issue by liuximing2016** [ElemeFE/element#13841]
### Element UI version
2.4.11

### OS/Browsers version
MacOS/Chrome

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/dcmrhqut/](https://jsfiddle.net/dcmrhqut/)

### Steps to reproduce
1. Collapse the menu;
2. Hover on the second or fourth menu item icon;
3. Press down and try to drag the item icon;
4. Outline shows around the item;

### What is Expected?
Outline should not show. It looks weird.

### What is actually happening?
Outline shows.
![image](https://user-images.githubusercontent.com/23612674/50289879-0dd9c000-04a5-11e9-8c49-19e701c3b98f.png)

**Comment by MattMadgex** [comment]
@liuximing2016 - the focus state should not be removed as it is used by people navigating the page with a keyboard (tabbing through buttons). I guess it could have a custom focus style rather than the default browser one.
