### ISSUE TITLE
[Bug Report] icon 类名下面有“x”会被转义成字体图标

### ISSUE THREAD

**Issue by xushuailing** [ElemeFE/element#13854]
### Element UI version
2.4.11

### OS/Browsers version
mac/Chrome

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/xslmenghuan/nmsLa65x/1/](https://jsfiddle.net/xslmenghuan/nmsLa65x/1/)

### Steps to reproduce
```html
<i class="el-icon-edit"><span>这是一段带x的句子</span></i>
<i class="el-icon-share">xx</i>
```

### What is Expected?
不被改成字体图标

### What is actually happening?
el-icon-* 类名下面只要有x 会被转成字体图标

**Comment by island205** [comment]
```html
<span><i class="el-icon-edit"></i>这是一段带x的句子</span>
```
