### ISSUE TITLE
[Bug Report] Form checks for numbers by entering numbers first, but not by entering letters; 13646

### ISSUE THREAD

**Issue by flyinglove** [ElemeFE/element#13859]
### Element UI version
2.4.11

### OS/Browsers version
mac/chrome 71.0.3578.98

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/my_sunshine/eywraw8t/517555/](https://jsfiddle.net/my_sunshine/eywraw8t/517555/)

### Steps to reproduce
input any string starts with a number

### What is Expected?
show info "年龄必须为数字值"

### What is actually happening?
the info doesn't show, and i can submit successfully.

**Comment by wacky6** [comment]
fiddle 跑不了。更新一下吧

**Comment by flyinglove** [comment]
> fiddle 跑不了。更新一下吧

已经更新

**Comment by languanghao** [comment]
因为`v-model.number` 会自动尝试把你的输入值转换为 `number` 类型，你可以尝试一下：`parseInt('123abc')` 这个结果是 `123`，这个问题我一直觉得是async-validator 这个组件的锅，它对类型判断太严格了，和常见的一些验证组件有一些逻辑上的冲突。

针对年龄的校验，你可以用正则表达式：
```
 {
        message: '必须是一个整数',
        pattern: /^\d+$/,
 };
```

**Comment by flyinglove** [comment]
> 因为`v-model.number` 会自动尝试把你的输入值转换为 `number` 类型，你可以尝试一下：`parseInt('123abc')` 这个结果是 `123`，这个问题我一直觉得是async-validator 这个组件的锅，它对类型判断太严格了，和常见的一些验证组件有一些逻辑上的冲突。

但是上述的正则不是匹配纯数字吗， 如果输入'1a'的话仍然校验不出来, 另外这个demo是我从element官网拷过来的， 但是表现确和官网的不同

**Comment by languanghao** [comment]
> > 因为`v-model.number` 会自动尝试把你的输入值转换为 `number` 类型，你可以尝试一下：`parseInt('123abc')` 这个结果是 `123`，这个问题我一直觉得是async-validator 这个组件的锅，它对类型判断太严格了，和常见的一些验证组件有一些逻辑上的冲突。
> 
> 但是上述的正则不是匹配纯数字吗， 如果输入'1a'的话仍然校验不出来, 另外这个demo是我从element官网拷过来的， 但是表现确和官网的不同

你要把 v-modle.number 后面的 .number 去掉，不要让vue做转换

**Comment by flyinglove** [comment]
> > > 因为`v-model.number` 会自动尝试把你的输入值转换为 `number` 类型，你可以尝试一下：`parseInt('123abc')` 这个结果是 `123`，这个问题我一直觉得是async-validator 这个组件的锅，它对类型判断太严格了，和常见的一些验证组件有一些逻辑上的冲突。
> > 
> > 
> > 但是上述的正则不是匹配纯数字吗， 如果输入'1a'的话仍然校验不出来, 另外这个demo是我从element官网拷过来的， 但是表现确和官网的不同
> 
> 你要把 v-modle.number 后面的 .number 去掉，不要让vue做转换

如果去掉的话我输入的就都是字符串了， 上面那个正则/^\d+$/貌似无法正常匹配到， https://jsfiddle.net/my_sunshine/d94o8fp2/3/

**Comment by languanghao** [comment]
> > > > 因为`v-model.number` 会自动尝试把你的输入值转换为 `number` 类型，你可以尝试一下：`parseInt('123abc')` 这个结果是 `123`，这个问题我一直觉得是async-validator 这个组件的锅，它对类型判断太严格了，和常见的一些验证组件有一些逻辑上的冲突。
> > > 
> > > 
> > > 但是上述的正则不是匹配纯数字吗， 如果输入'1a'的话仍然校验不出来, 另外这个demo是我从element官网拷过来的， 但是表现确和官网的不同
> > 
> > 
> > 你要把 v-modle.number 后面的 .number 去掉，不要让vue做转换
> 
> 如果去掉的话我输入的就都是字符串了， 上面那个正则/^\d+$/貌似无法正常匹配到， https://jsfiddle.net/my_sunshine/d94o8fp2/3/

这个是正确的做法：https://jsfiddle.net/k7q0drxt/

你两个地方写错了
1. 就是要让这个type是string，PS：我一直觉得这个就是async-validator 的锅，这个库本身有个bug，一直没解决 [BUG](https://github.com/yiminghe/async-validator/issues/127)
2. 是 `pattern: /^\d+$/`，不是 `rule: /^\d+$/`

` { type: 'string', message: '年龄必须为数字值', pattern: /^\d+$/}`

**Comment by jingshenchen** [comment]
> > > > > 因为`v-model.number` 会自动尝试把你的输入值转换为 `number` 类型，你可以尝试一下：`parseInt('123abc')` 这个结果是 `123`，这个问题我一直觉得是async-validator 这个组件的锅，它对类型判断太严格了，和常见的一些验证组件有一些逻辑上的冲突。
> > > > 
> > > > 
> > > > 但是上述的正则不是匹配纯数字吗， 如果输入'1a'的话仍然校验不出来, 另外这个demo是我从element官网拷过来的， 但是表现确和官网的不同
> > > 
> > > 
> > > 你要把 v-modle.number 后面的 .number 去掉，不要让vue做转换
> > 
> > 
> > 如果去掉的话我输入的就都是字符串了， 上面那个正则/^\d+$/貌似无法正常匹配到， https://jsfiddle.net/my_sunshine/d94o8fp2/3/
> 
> 这个是正确的做法：https://jsfiddle.net/k7q0drxt/
> 
> 你两个地方写错了
> 
> 1. 就是要让这个type是string，PS：我一直觉得这个就是async-validator 的锅，这个库本身有个bug，一直没解决 [BUG](https://github.com/yiminghe/async-validator/issues/127)
> 2. 是 `pattern: /^\d+$/`，不是 `rule: /^\d+$/`
> 
> ` { type: 'string', message: '年龄必须为数字值', pattern: /^\d+$/}`

这个好像只能校验整数，0.1这样就不行了

**Comment by languanghao** [comment]
正则表达式改成： `/^-?\d+\.?\d*$/`

**Comment by wangrr02** [comment]
事实上这个bug已经被async-validator修复，https://github.com/yiminghe/async-validator/issues/127，不知道element-ui有没更新async-validator？我觉得可以通过更新async-validator版本来修复这个问题

**Comment by csvwolf** [comment]
Duplicated #18120
