### ISSUE TITLE
[Bug Report] el-steps show wrong number with V-for

### ISSUE THREAD

**Issue by LzxHahaha** [ElemeFE/element#13862]
### Element UI version
2.4.11

### OS/Browsers version
MacOS 10.14 / Chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/6vo248st/](https://jsfiddle.net/6vo248st/)

### Steps to reproduce
在el-steps中间用v-for动态渲染，序号顺序错误

### What is Expected?
中间的序号正确排序

### What is actually happening?
中间序号错误

**Comment by wacky6** [comment]
不能重现。
v-for请写:key https://vuejs.org/v2/guide/list.html#key

**Comment by LzxHahaha** [comment]
https://jsfiddle.net/6vo248st/1/

示例已更新，在中间的循环上加上key圆圈中的序号依旧不对

![](https://haitao.nos.netease.com/6309f176-3444-4a17-a405-9c813114e420_1105_192.png)

**Comment by gaochunxiang** [comment]
请问，后来这个怎么解决的？

**Comment by LzxHahaha** [comment]
> 请问，后来这个怎么解决的？

在`el-steps`上加个key，修改里面的数量时同时修改key来强制重建元素

**Comment by gaochunxiang** [comment]
谢谢，用这个方法解决我的问题了！
