### ISSUE TITLE
[Bug Report] The subtag attribute (pointer-events: none) of a tag in el-tooltip does not work and can still jump

### ISSUE THREAD

**Issue by WisperDin** [ElemeFE/element#13869]
### Element UI version
2.4.11

### OS/Browsers version
chrome 69.0

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7192/](https://jsfiddle.net/mmx38qxw/7192/)

### Steps to reproduce
```html
<el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
        <div style="height: 100px;width: 200px;background-color: blue">
            <a href="http://www.cn.bing.com" style="pointer-events: none">
                <p style="pointer-events: none">lzy ppp</p>
            </a>
        </div>
      </el-tooltip>
```

### What is Expected?
`<p style="pointer-events: none">lzy ppp</p>`
this tag can't be click

### What is actually happening?
`<p style="pointer-events: none">lzy ppp</p>`
this tag can be click and jump

**Comment by pengliheng** [comment]
this bug confuse me so much.
### safari browser
![image](https://user-images.githubusercontent.com/14355994/67466480-bafb0700-f679-11e9-936c-bc823adbdead.png)
