### ISSUE TITLE
The formatter requirement in [Feature Request] el-table-column makes Axios request and returns the value. The request succeeds, but the page is not displayed.

### ISSUE THREAD

**Issue by wzwdev** [ElemeFE/element#13863]
### Existing Component
是

### Component Name
el-table

### Description
我有一个el-table，其中有一列 el-table-column，这个column中prop='org_id'，我想通过:formatter转换为org_name，但是要通过axios请求RestAPI（通过日志发现确实是

调用 了API且成功了）,但页面上不显示。怎么都不生效，该如何处理

**Comment by wacky6** [comment]
formatter 必须同步返回结果。请不要做异步操作。要用API就在把数据给table之前处理好
