### ISSUE TITLE
[Bug Report] table column (type = expand) bug

### ISSUE THREAD

**Issue by Venus-WXP** [ElemeFE/element#13868]
### Element UI version
2.4.11

### OS/Browsers version
MacOSMojave10.14.2/Chrome71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/venuswxp/mmx38qxw/7185/](https://jsfiddle.net/venuswxp/mmx38qxw/7185/)

### Steps to reproduce
点击最左侧的展开箭头，由于高度不够完全展示，所以出现滚动条，但是表头出现对齐错乱的bug，可以多点几次展开收缩，bug更明显
注意：如果没有上述现象，将浏览器的缩放比调小或者调大会出现此问题

### What is Expected?
出现滚动条，但是表头排版不会错乱

### What is actually happening?
出现滚动条，但是表头排版出现严重错乱

**Comment by JiYJCoder** [comment]
同有这个Bug.2.61都没解决.

**Comment by edwards19900128** [comment]
> 同有这个Bug.2.61都没解决.

解决了么 兄弟

**Comment by louie-liang** [comment]
这个bug 还么解决呢  目前版本2.10.1了
