### ISSUE TITLE
[Feature Request] Please add a slot at the top of the dialog, and so do the bottom.

### ISSUE THREAD

**Issue by flyinglove** [ElemeFE/element#13878]
### Existing Component
是

### Component Name
dialog

### Description
there are some time we will need to add some warning info to the dialog at the top and the bottom of it. But in the current dialog, there is only one slot 'title'  for the purpose of adding a title.

**Comment by wacky6** [comment]
现在的 title footer slot 不能满足需求？画个图吧

**Comment by flyinglove** [comment]
> 现在的 title footer slot 不能满足需求？画个图吧

就像这种弹窗
![image](https://user-images.githubusercontent.com/12018559/50432942-2b2ce500-0910-11e9-8637-87dc5df34e24.png)
