### ISSUE TITLE
How does el-table-column prop use Vue global filter

### ISSUE THREAD

**Issue by tracker1999** [ElemeFE/element#13877]
### Existing Component
Yes

### Component Name
el-table-column

### Description
el-table-column prop如何使用vue全局filter

**Comment by tracker1999** [comment]
:prop="'timestamp' | formatDate"

不生效，filter收到的参数是【timestamp】

<template scope="scope">{{scope.row.timestamp | formatDate}}</template> 

生效，但要使用Slot，是否有其他更好的方法

**Comment by island205** [comment]
vue prop don't support filter probably https://vuejs.org/v2/guide/filters.html, issue closed

**Comment by tracker1999** [comment]
formatDate is a vue global filter.
<el-table-column :prop="timestamp| formatDate"></el-table-column>
<el-table-column :prop="'timestamp'| formatDate"></el-table-column>
The above two ways of writing do not working.

<el-table-column label="time">
  <template slot-scope="scope">{{scope.row.timestamp| formatDate}}</template>
</el-table-column>
The above is working, but must use template and solt-scope.

**Comment by tracker1999** [comment]
https://github.com/ElemeFE/element/issues/10689
the same issuse.
