### ISSUE TITLE
[Bug Report] Table clearSort() doesn't work on custom sort.

### ISSUE THREAD

**Issue by Holybasil** [ElemeFE/element#13873]
### Element UI version
2.4.11

### OS/Browsers version
71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/Holybasil/pqkn05s6/18/](https://jsfiddle.net/Holybasil/pqkn05s6/18/)

### Steps to reproduce
See jsfiddle and try to sort the two columns.

### What is Expected?
clearSort() could have the consistent performance in default sort and custom sort.

### What is actually happening?
clearSort()  is not friendly to custom sort.

**Comment by ziyoung** [comment]
#15439
