### ISSUE TITLE
[Feature Request] upload component adds a hook set to cover

### ISSUE THREAD

**Issue by winter-ice** [ElemeFE/element#13879]
### Existing Component
是

### Component Name
upload

### Description
希望能增加一个设为封面的钩子

**Comment by island205** [comment]
我不明白你的需求，可以提供更详细的信息么？

**Comment by island205** [comment]
你可以基于现有组件实现

**Comment by winter-ice** [comment]
现有组件没有这个位置没有slot把

**Comment by AlexZhong22c** [comment]
没必要加slot。你用默认的slot传遮罩进去，对遮罩用绝对定位之类的盖住它后面的元素就行了。

一般来说公司里面都会做这种组件封装。 @winter-ice
