### ISSUE TITLE
Dialog :close called multiple times and even when opening the dialog

### ISSUE THREAD

**Issue by Chalkin** [ElemeFE/element#1388]
### ElementUI version
Same as ElementUi Docs (Using the dialog jsfiddle as template)

### OS/Browers version
MacOS Sierra, Chrome newest

### Vue version
Same as ElementUi Docs (Using the dialog jsfiddle as template)

### Reproduction Link
[jsfiddle](http://jsfiddle.net/37fnu47e/)

### Steps to reproduce
open dialog via link

### What is Expected?
Close event should be called only once as soon as I click the X but not before and not multiple times

### What is actually happening?
Close event is called multiple times and also when opening the dialog.

**Comment by Leopoldthecoder** [comment]
Instead of `:close="testIt()"`, try `@close="testIt"`.
`close` is an event, so you should use `v-on`, not `v-bind`. And the parentheses are not necessary.

**Comment by Chalkin** [comment]
Oh, my fault. Works like a charm with @close - thanks @Leopoldthecoder 

this issue can be closed
