### ISSUE TITLE
[Bug Report] The first column of the table shows an exception with fixed columns and grouping head

### ISSUE THREAD

**Issue by suguoyao** [ElemeFE/element#13887]
### Element UI version
2.4.11

### OS/Browsers version
macOS/Chrome 71.0.3578.98

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/suguoyao/fc80jaqg/](https://jsfiddle.net/suguoyao/fc80jaqg/)

### Steps to reproduce
I used grouping table head with fixed columns.
See jsfiddle and try to horizontal scroll. 

### What is Expected?
The first column is displayed normally

### What is actually happening?
You will find that the first column has an exception which is shows incomplete when Initialization or horizontal scrolling.

**Comment by PeanutWatson** [comment]
看了一下，这种双表头的表格固定列需要将两个表头的width/min-width设置一致, 这样就能解决这个问题。
`<el-table-column label="项目" align="center" fixed min-width="100">
        <el-table-column prop="exhibitName" label="展会" min-width="100" align="center"></el-table-column>
      </el-table-column>`

这样子是否还需要改组件源代码提pr？

**Comment by suguoyao** [comment]
@PeanutWatson 谢谢，你这样可以 👍 
看看是否能考虑在组件里添加这种情况的处理
