### ISSUE TITLE
[Feature Request] Select component can't find the result. Can you not clear select value by clicking on other parts of the mouse?

### ISSUE THREAD

**Issue by gu12** [ElemeFE/element#13888]
### Existing Component
是

### Component Name
select

### Description
select组件搜索不到结果，鼠标点击其他地方能不能不清除select value

**Comment by wacky6** [comment]
给个demo

**Comment by gu12** [comment]
额 大佬 demo我暂时没有 就是我希望能不能在select搜索 匹配不到数据时，鼠标点击其他地方 输入框内的内容不清空  就是那个clickoutside 事件，改源码我又怕出bug，所以希望以后可以增加这个功能或者设置成一个属性，谢谢。

**Comment by wacky6** [comment]
意思是保留用户输入的内容？但是为什么要保留呢

**Comment by gu12** [comment]
嗯 额 是产品要求的 不过我觉得当我输入一个很长的地址的时候 如果因为最后几个字导致搜索不到 clickoutside 而清空的话  等会就需要再输入一遍 稍显麻烦

**Comment by suguoyao** [comment]
> 嗯 额 是产品要求的 不过我觉得当我输入一个很长的地址的时候 如果因为最后几个字导致搜索不到 clickoutside 而清空的话 等会就需要再输入一遍 稍显麻烦

select在搜索时，下拉框会实时匹配并显示，这个时候已经可以明确知道要选哪个了，我认为没必要加这个功能。而且假如按你这个要求的话，假如不清空并且下拉数据里并没有匹配到数据，用户还会以为已经选中了。

**Comment by gu12** [comment]
> > 嗯 额 是产品要求的 不过我觉得当我输入一个很长的地址的时候 如果因为最后几个字导致搜索不到 clickoutside 而清空的话 等会就需要再输入一遍 稍显麻烦
> 
> select在搜索时，下拉框会实时匹配并显示，这个时候已经可以明确知道要选哪个了，我认为没必要加这个功能。而且假如按你这个要求的话，假如不清空并且下拉数据里并没有匹配到数据，用户还会以为已经选中了。

我觉得可以设为属性 让开发者自行选择

**Comment by suguoyao** [comment]
> > > 嗯 额 是产品要求的 不过我觉得当我输入一个很长的地址的时候 如果因为最后几个字导致搜索不到 clickoutside 而清空的话 等会就需要再输入一遍 稍显麻烦
> > 
> > 
> > select在搜索时，下拉框会实时匹配并显示，这个时候已经可以明确知道要选哪个了，我认为没必要加这个功能。而且假如按你这个要求的话，假如不清空并且下拉数据里并没有匹配到数据，用户还会以为已经选中了。
> 
> 我觉得可以设为属性 让开发者自行选择

不如加点可选择的彩蛋吧😆
