### ISSUE TITLE
[Bug Report] when i use element tree,if i check the child and the child has only one ,then the parent will be checked

### ISSUE THREAD

**Issue by darkhaloWu** [ElemeFE/element#13886]
### Element UI version
2.4.11

### OS/Browsers version
windows

### Vue version
2.5.0

### Reproduction Link
[http://github.eleme.io/#/zh-CN/component/](http://github.eleme.io/#/zh-CN/component/)

### Steps to reproduce
a tree has only one child ,then will be

### What is Expected?
when the child is checked,the parentNode will be only halfChecked,only the parent can choose all the child , the child should not affect the parentNode,

### What is actually happening?
parentNode has only one child  ,we check the child ,  then parentNode will be checked

**Comment by elfman** [comment]
This is not bug.
`parent checked  = all children are checked`, no matter how it comes
