### ISSUE TITLE
[Feature Request] The el-select need attribute placement

### ISSUE THREAD

**Issue by tomieric** [ElemeFE/element#13881]
### Existing Component
是

### Component Name
el-select

### Description
[https://github.com/ElemeFE/element/blob/dev/packages/select/src/select-dropdown.vue#L21](https://github.com/ElemeFE/element/blob/dev/packages/select/src/select-dropdown.vue#L21)

In `select-dropdown`, the placement attribute is already available.

why does el-select not add `placement` attribute, we can control the direction of `select-dropdown` arrow

**Comment by ziyoung** [comment]
@tomieric 请提供该属性的使用场景？如果 placement 是 left 或者 right，UI 岂不是非常奇怪？

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/14037#issuecomment-463897344

**Comment by vvasilev-** [comment]
Hi @ziyoung,

Here is an example of such use case:

![image](https://user-images.githubusercontent.com/1783033/52849161-0fc4a600-3119-11e9-84c9-0eee8797043d.png)

Hope that is enough to add this feature to the select component. :smile:
