### ISSUE TITLE
[Bug Report] About time picker: sometimes need the start time to be greater than the end time

### ISSUE THREAD

**Issue by Evacaca** [ElemeFE/element#13891]
### Element UI version
2.4.11

### OS/Browsers version
chrome v71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/kywp8d79/7/](https://jsfiddle.net/kywp8d79/7/)

### Steps to reproduce
1. visit https://jsfiddle.net/kywp8d79/7/
2. select start time like 23:00:00
3. select end time less than the start time like 8:00:00

### What is Expected?
the end time 8:00:00 can be chosen

### What is actually happening?
the selection of 8:00:00 including others less than the start time is disabled

**Comment by elfman** [comment]
StartTime greater than endTime in a same component seems very strange without other hits.
In your case, I think you can use two TimePicker or one DateTimePicker.

**Comment by wacky6** [comment]
You need to explain why you want to do this. We won't support this usage unless there are compelling reasons.

**Comment by 150148313** [comment]
时分秒和年月日又不一样，22:00-8:00  这样的时间段不是很常见吗
