### ISSUE TITLE
[Feature Request] Cascader 级联选择器实现“父级和子级都可选，hover展开下级，click触发change事件”

### ISSUE THREAD

**Issue by tk103331** [ElemeFE/element#13898]
### Existing Component
Yes

### Component Name
Cascader 级联选择器

### Description
我想使用Cascader 级联选择器达到如下效果：

父级和子级都可选，hover展开下级，但只在click时触发change事件

我使用了change-on-select实现父级和子级都可选，使用了expand-trigger="hover"实现hover展开下级，但是也默认触发了change事件（因为change-on-select），能不能提供一个选项，可以控制“hover展开下级”时不触发change事件。

**Comment by yantaolu** [comment]
我觉得你这这是正常的交互逻辑，expand-trigger就是控制展开自己菜单的方式，click事件是触发model改变的行为，不能因为expand-trigger设置了hover，然后hover事件就触发了model的改变，另外change-on-select只是控制是否每一级都可以选择，所以我觉得这是个bug，而不应该是新需求，这两个prop均是控制某一个特性

**Comment by nopapername** [comment]
这个问题有解决吗？
