### ISSUE TITLE
rc4,官网demo，固定列和表头，表头不能跟随scroll，rc3无此问题

### ISSUE THREAD

**Issue by Robin-front** [ElemeFE/element#139]
### ElementUI version
1.0.0-rc.4

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.0-rc.6

### Steps to reproduce
具体见： [http://element.eleme.io/#/component/table](http://element.eleme.io/#/component/table) rc3无此问题
### What is Expected?
表头跟随滚动
### What is actually happening?
表头不能跟随滚动， rc3无此问题

**Comment by Leopoldthecoder** [comment]
#121
