### ISSUE TITLE
[Bug Report] Tab underline do not automatically respond to the screen!

### ISSUE THREAD

**Issue by helpceo** [ElemeFE/element#13902]
### Element UI version
2.4.11

### OS/Browsers version
Windows 10   Ubuntu 16.04

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/3wcnybx5/](https://jsfiddle.net/3wcnybx5/)

### Steps to reproduce
Zoom in and out of the browser, you can't change the size!

### What is Expected?
adaptive

### What is actually happening?
maladaptive

**Comment by island205** [comment]
Sorry, we have no plan to support this.
