### ISSUE TITLE
[Feature Request] Unique Field Validation in Dynamic for add and delete From 

### ISSUE THREAD

**Issue by kevinRR** [ElemeFE/element#13904]
### Existing Component
Yes

### Component Name
Form

### Description

Inside Form component in "Delete or add form items dynamically "
Domain0 should not same to the Domain1 those domains should be unique

**Comment by island205** [comment]
more explaination please

**Comment by khemrajregmi** [comment]
@island205  ok i have attached a image then
![component element](https://user-images.githubusercontent.com/20414459/50948452-a1157c80-14ca-11e9-86bf-8036402b4adb.png)

**Comment by khemrajregmi** [comment]
@island205  if there is same text then validation popup like 'please input unique text' similar to this

**Comment by kevinRR** [comment]
@island205 ya this is exactly what i want too

**Comment by island205** [comment]
Sorry, we have no plan to support this at this moment.
