### ISSUE TITLE
Under what circumstances will the function corresponding to the property selectable in the [Feature Request] table component be triggered

### ISSUE THREAD

**Issue by DAHU123** [ElemeFE/element#13909]
### Existing Component
是

### Component Name
table

### Description
selectable这个属性对应的函数  在什么情况下会被触发....我现在想要为表格的row设置选中，然后再禁用，现在没有实现．．．

                let checkedId = this.allChecked;

                if(checkedId.length == 0){
                    row.disabled = false;
                    return true;
                }else{

                    let str = checkedId.join('*');
                    if( str.indexOf(row.id) >= 0 ){
		                this.$refs.attrDomTable.toggleRowSelection(row,true);
		                row.disabled = true;
		                return false;
                    }else{
		                row.disabled = false;
		                return true;
                    }

                }

**Comment by DAHU123** [comment]
假如说checkedId.length = 10，就会引发错误：错误如下
 Maximum call stack size exceeded
求大神支招这个问题应该如何去解决．．．

**Comment by sockball** [comment]
似乎table绑定的data数据发生变化时都会触发
而开启highlight-current-row时 每次单击非高亮行都会触发...
开启highlight-current-row并点击checkbox行为更诡异...🙄

**Comment by ziyoung** [comment]
@DAHU123 补充个完整的例子。

**Comment by nongzhenli** [comment]
你好，请问有解决的吗？

**Comment by DAHU123** [comment]
这个问题用官方提供的那个API没有解决  我是另外写的自己的方式去解决的
