### ISSUE TITLE
[Bug Report] Table Attribute Name contains. Symbol, Data Display Problem

### ISSUE THREAD

**Issue by jiaqizhang77** [ElemeFE/element#13906]
### Element UI version
2.3.9

### OS/Browsers version
win7/chrom 71.0.3578.98

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/1nz3br02/](https://jsfiddle.net/1nz3br02/)

### Steps to reproduce
将属性名中添加 . 符号

### What is Expected?
可以正常显示数据

### What is actually happening?
数据没有被显示

**Comment by ziyoung** [comment]
prop 支持“x.y” 这种取值方式。避免使用特殊字符吧。https://jsfiddle.net/7frj04to/
