### ISSUE TITLE
[Bug Report] form中使用select并设置:popper-append-to-body="false"

### ISSUE THREAD

**Issue by scaryBiaoqing** [ElemeFE/element#13900]
### Element UI version
2.4.11

### OS/Browsers version
windows / chrome 70.0

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/ouwrvfkq/1/](https://jsfiddle.net/ouwrvfkq/1/)

### Steps to reproduce
在form中使用select 并对select设置:popper-append-to-body="false"

### What is Expected?
弹出框不偏移

### What is actually happening?
弹出框左侧偏移5px

**Comment by caokunyu** [comment]
删掉:popper-append-to-body="false"

**Comment by scaryBiaoqing** [comment]
> 删掉:popper-append-to-body="false"

可是由于项目的一些情况不能让他添加在body上

**Comment by caokunyu** [comment]
https://jsfiddle.net/ouwrvfkq/33/

**Comment by upupzealot** [comment]
借宝地提一个很类似的 bug，multiple为 true 的情况下把 popper-append-to-body 设置为 false，会导致每次选择后 dropdown 自动关闭。正常情况下多选时 dropdown 不会关闭
