### ISSUE TITLE
[Bug Report] el-tree filter is abnormal

### ISSUE THREAD

**Issue by elewen** [ElemeFE/element#13905]
### Element UI version
2.4.11

### OS/Browsers version
windows 10、chrome v70.0

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/elewen/neqk8g6b/6/](https://jsfiddle.net/elewen/neqk8g6b/6/)

### Steps to reproduce
1. 打开以上链接（或直接到官方网站查看该bug：http://element-cn.eleme.io/#/zh-CN/component/tree#jie-dian-guo-lu）
2. 在输入框输入关键词“一级”进行搜索
3. 在搜索结果中点击“一级 1”或点击“一级 2”或点击“一级 3”

### What is Expected?
若匹配到的搜索结果存在子节点，应该能正常展开被点击节点的子节点

### What is actually happening?
未展开被点击节点的子节点，匹配到的搜索结果没有子节点

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by LDHgiser** [comment]
This kind of scene is more useful, please support it.
