### ISSUE TITLE
[Bug Report] el-table component adds show-overflow-tooltip, how to style the tooltip here without affecting the global tooltip style

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#13919]
### Element UI version
2.4.11

### OS/Browsers version
windows10/chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/z9yp4nfo/](https://jsfiddle.net/z9yp4nfo/)

### Steps to reproduce
让address栏的数据内容出现省略号（内容过长）时，并且文本是全英文时，tooltip无法换行, 导致tooltip文本无法查看完整，就算为 `el-tooltip__popper` 设置了 `word-break: break-all;`, tooltip的样式也很难看
![image](https://user-images.githubusercontent.com/8147202/50511342-417da100-0ac8-11e9-91ec-978a4f4ac0ec.png)

### What is Expected?
不能设置全局的 `.el-tooltip__popper`，因为项目中弹框也存在 tooltip，每个功能模块想要的 tooltip不一样，这里的tooltip设置样式不会影响全局tooltip的样式

### What is actually happening?
如果文本是全英文时，tooltip无法换行, 导致tooltip文本无法查看完整

**Comment by ziyoung** [comment]
可以通过 scope-slot 来实现该功能。

**Comment by fengyun2** [comment]
@ziyoung 能给个demo？
