### ISSUE TITLE
Can [Feature Request] Table Components Support Search

### ISSUE THREAD

**Issue by wangweiyi1** [ElemeFE/element#13918]
### Existing Component
是

### Component Name
table

### Description
现有的例子中只有一个带搜索的，而且不是表格组件本身的搜索功能，我使用这种方式的搜索后，会跟表格组件的selection功能冲突，当表格在dialog中时，我搜索后选择的行选择状态会消失，希望能给出这种场景下的解决方案，谢谢。

**Comment by island205** [comment]
We will consider to support this.
