### ISSUE TITLE
[Bug Report] table filter failed: there's no proper filter value in filter object which passes into filter change handler.

### ISSUE THREAD

**Issue by lshxq** [ElemeFE/element#13911]
### Element UI version
2.4.11

### OS/Browsers version
mac / chrome

### Vue version
2.5.21

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-store.js](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-store.js)

### Steps to reproduce
provide a template based table column with no 'prop' attribute. provide filters on the column.
el-table-column(label="样本类别", width='100px', column-key="sampleType", :filters="[...any valid filter]")
        template(slot-scope="scope")
                   span {{sampleTypeTranslator(scope.row.sample_type)}}

register filter-change event on table element.

try filter, you'll see the filter change handle called but no filter value passed into it.

### What is Expected?
pass proper filter value to filter change handle. 

### What is actually happening?
no filter value.

By reading source code of filterChange function in table-store.js. The 'property' attribute is need to fill filters object.

      const prop = column.property;
      if (prop) {
        states.filters[column.id] = values;
        filters[column.columnKey || column.id] = values;
      }

but there's no place say the 'property' attribute is a key member to setup filters in official development manual. :)

**Comment by robwatkiss** [comment]
+1

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
