### ISSUE TITLE
建议增加几项功能

### ISSUE THREAD

**Issue by slovebj** [ElemeFE/element#1391]
1.tabs参照b-jui增强，可动态增减tab项，可自动隐藏过多的tab,增加下拉菜单调出隐藏项，添加右键菜单等。
2.dialog弹出层可以调整尺寸和最大化，可以在局部弹出。可参照layer。

**Comment by furybean** [comment]
暂无其他人提出这两个需求，如果需要人数多，后面会考虑。

**Comment by cougarwww** [comment]
tabs功能确实单薄了些，要是做后台应用，或者saas，b-jui的tabs功能确实完善些

**Comment by stanNo1** [comment]
![image](https://cloud.githubusercontent.com/assets/16200523/21539683/0bd20f28-cde4-11e6-828c-846ef2428633.png)
![image](https://cloud.githubusercontent.com/assets/16200523/21539692/1f157b74-cde4-11e6-8ea1-73330cf3c64e.png)
目前我们也有类似tabs自动隐藏，可左右滚动的类似需求，希望能够支持
