### ISSUE TITLE
[Bug Report] el-table组件添加 show-overflow-tooltip，当鼠标移到<td><div  class="cell el-tooltip"></div></td>的边框时，会触发tooltip不断出现消失

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#13917]
### Element UI version
2.4.11

### OS/Browsers version
windows10/chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/ckszf3ym/](https://jsfiddle.net/ckszf3ym/)

### Steps to reproduce
让address栏的数据内容出现省略号（内容过长）时，当鼠标移到<td><div  class="cell el-tooltip"></div></td>的边框时，会触发tooltip不断出现消失
![image](https://user-images.githubusercontent.com/8147202/50510244-f19cdb00-0ac3-11e9-85d6-320a7bacd579.png)

### What is Expected?
当鼠标移到<td><div  class="cell el-tooltip"></div></td>的边框时，只会触发tooltip一次（鼠标移入时出现，移出时消失）

### What is actually happening?
当鼠标移到<td><div  class="cell el-tooltip"></div></td>的边框时，会触发tooltip不断出现消失

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
