### ISSUE TITLE
[Bug Report] Table Component onSortChange event,when recovery Default Should Pass Prop Parameters

### ISSUE THREAD

**Issue by kenziD** [ElemeFE/element#13926]
### Element UI version
2.4.11

### OS/Browsers version
windows/chorme

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7329/](https://jsfiddle.net/mmx38qxw/7329/)

### Steps to reproduce
点击排序按钮，先变成asc,再变成desc,再点一次恢复默认。

### What is Expected?
console中应打印

* "date" "ascending"

* "date" "descending"

* "date" null

### What is actually happening?
console中打印了

* "date" "ascending"

* "date" "descending"

* null" null

**Comment by island205** [comment]
pr welcome
