### ISSUE TITLE
使用el-select 添加  multiple 时  再添加 filterable 属性，控件不停的闪烁，通过检查发现，高度在不停的变化

### ISSUE THREAD

**Issue by lt132618** [ElemeFE/element#13924]

**Comment by 276509842** [comment]
修改：element\packages\select\src\select.vue：   652行

input.style.height = this.selected.length === 0
            ? sizeInMap + 'px'
            : Math.max(
              // tags ? (tags.clientHeight + (tags.clientHeight > sizeInMap ? 6 : 0)) : 0,
              tags ? (tags.getBoundingClientRect().height + (tags.getBoundingClientRect().height > sizeInMap ? 6 : 0)) : 0,
              sizeInMap
            ) + 'px';
