### ISSUE TITLE
Can [Feature Request] upload add a drag sort?

### ISSUE THREAD

**Issue by liyangmsn** [ElemeFE/element#13934]
### Existing Component
Yes

### Component Name
el-upload

### Description
upload能不能加个拖动排序
对已上传的列表拖动排序

**Comment by island205** [comment]
Sorry, we have no plan to support this. You can implement your own file list with drag and drop in the default slot of <el-upload>.

**Comment by iamkun** [comment]
reference #11557

**Comment by cloydlau** [comment]
See https://github.com/cloydlau/faim#faimageupload

**Comment by mymx2** [comment]
额...曲线救国
`<div style="color: #999; font-size: 12px">
  <el-popover placement="top-start" trigger="hover" width="200">
    <vuedraggable v-model="galleryList">
      <transition-group>
        <el-tag v-for="(item, index) in galleryList" :key="item.url" style="margin-right: 5px">
          {{ index }}
        </el-tag>
      </transition-group>
    </vuedraggable>
    <i slot="reference" class="el-icon-setting" />
  </el-popover>
  建议尺寸：800*800像素，最多上传5张
</div>`
