### ISSUE TITLE
upload on-change 突然没有了 file.url

### ISSUE THREAD

**Issue by siberiadev** [ElemeFE/element#13935]
我真的没有时间按照你们的规定写issue，太着急，麻烦你们帮我一下。
我们用upload，然后之前在 on-change 可以获取到 file.url 
然后突然这个参数没有了。就是说file里没有url - 有没有想法？为什么呢？怎么修改呢
多谢。
我这边特别着急，我是俄罗斯的程序员，需要你们的帮忙！谢谢

**Comment by tsurumure** [comment]
一样
