### ISSUE TITLE
[Feature Request] tree table

### ISSUE THREAD

**Issue by SilverLeaves** [ElemeFE/element#13938]
### Existing Component
否

### Component Name
tree table

### Description
树状表格，tree table

**Comment by island205** [comment]
Sorry, we have no plan to support this.

**Comment by SilverLeaves** [comment]
@island205 [vue-ant-design table组件](https://vue.ant.design/components/table-cn/)已经支持table显示tree数据，请再考虑一下。

**Comment by island205** [comment]
@SilverLeaves We would consider this.
