### ISSUE TITLE
[Bug Report] el-step with V-IF gives wrong number

### ISSUE THREAD

**Issue by de1ck** [ElemeFE/element#13931]
### Element UI version
2.4.11

### OS/Browsers version
win 10 / chrome

### Vue version
2.5.21

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/steps/src/step.vue#L27](https://github.com/ElemeFE/element/blob/dev/packages/steps/src/step.vue#L27)

### Steps to reproduce
steps components use v-if or v-show this step number index is  error
   
       <el-steps :space="100" :active="active">
        <el-step
          title="步骤 1"
          process-status="wait"
          v-show="active > 3"
        ></el-step>
        <el-step title="步骤 2"></el-step>
        <el-step title="步骤 3"></el-step>
        <el-step title="步骤 4"></el-step>
        <el-step title="步骤 5"></el-step>
        <el-step title="步骤 6"></el-step>
        <el-step title="步骤 7"></el-step>
      </el-steps>
      <el-button type @click="active > 7 ? (active = 1) : active  "
        >下一步</el-button>

### What is Expected?
number index is correct

### What is actually happening?
number index is error

**Comment by elfman** [comment]
What do you think the correct value should be?

**Comment by de1ck** [comment]
> What do you think the correct value should be?
@elfman 
![image](https://user-images.githubusercontent.com/26627486/50578532-5d8d9380-0e76-11e9-880d-e89d3b4fdbba.png)
![image](https://user-images.githubusercontent.com/26627486/50578537-68e0bf00-0e76-11e9-94c2-d52bf2ab8a52.png)

**Comment by island205** [comment]
pr welcome
