### ISSUE TITLE
Can the [Feature Request] Transfer Shuttle Box Separate the render-content functions of left and right elements

### ISSUE THREAD

**Issue by BillionChen** [ElemeFE/element#13937]
### Existing Component
是

### Component Name
Transfer

### Description
使用穿梭框时，需要在穿梭框右边选中的区域，定义选中元素的属性，对元素对象进行操作

**Comment by elfman** [comment]
`render-content`属性会将`option`作为参数传入，你可以根据value判断选项是否被选中，返回不同的DOM

**Comment by island205** [comment]
plesae provide more explaination for image for your feature request.
