### ISSUE TITLE
建议每个release版本除了源码同时给出编译好的.css和.js文件

### ISSUE THREAD

**Issue by Zhao-github** [ElemeFE/element#1394]
做为一个后端开发者，在对node.js包管理以及前端构建工具不是很了解的情况下，迫切需要编译好的js和css文件！

**Comment by QingWei-Li** [comment]
CDN: https://cdnjs.com/libraries/element-ui
用法: http://element.eleme.io/#/zh-CN/component/installation#hello-world

**Comment by Zhao-github** [comment]
CDN早就开始使用，但是还是希望直接提供下载，毕竟国内的网络环境.....

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/releases
![image](https://cloud.githubusercontent.com/assets/7565692/20645932/0dd9fc94-b4a9-11e6-8ec8-d3832140f124.png)
