### ISSUE TITLE
[Feature Request] Opening and close <el-select> programatically

### ISSUE THREAD

**Issue by anatoly314** [ElemeFE/element#13948]
### Existing Component
Yes

### Component Name
 `<el-select>`

### Description
Sometimes it's required to open and close `<el-select>` programmatically but this feature is absent. For example. Right now I want to make some dom manipulations on a dropdown menu while it's opened. But I on every click it's being closed. `$event.preventDefault` and `$event.stopPropagation` didn't help me. So, I would like to see this feature and if somebody has any advice on how can it be achieved right now, I will more then thankful. 
Thank you very much.

**Comment by Sovai** [comment]
+1

**Comment by 300code** [comment]
el-select__popper  programatically not avialable in element plus and ui also !!! :)
