### ISSUE TITLE
[Bug Report] style error of documentation page for elementUI component

### ISSUE THREAD

**Issue by brospy** [ElemeFE/element#13949]
### Element UI version
2.4.11

### OS/Browsers version
windows10 home/chrome  71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
open devtools on the doc page: http://element-cn.eleme.io/#/zh-CN/component/ with chrome, this style error appears, see screenshot: https://i.loli.net/2019/01/02/5c2b9b402a8e9.jpg.

### What is Expected?
text arranged neatly

### What is actually happening?
it seems like the content in navbar flows to next line but with a transparent background, then the text turns out to be like this in this pic https://i.loli.net/2019/01/02/5c2b9b402a8e9.jpg.

**Comment by elfman** [comment]
can not reproduce in my browser
