### ISSUE TITLE
[Bug Report] Change babelrc 

### ISSUE THREAD

**Issue by zheng1013757145** [ElemeFE/element#13946]
### Element UI version
2.4.11

### OS/Browsers version
window

### Vue version
2.5.21

### Reproduction Link
[https://github.com/babel](https://github.com/babel)

### Steps to reproduce
Otherwise it won’t start.
The error message is: Module build failed: Error: Couldn't find preset "es2015" relative to directory

### What is Expected?
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"],
  "env": {
    "development":{
      "plugins": ["dynamic-import-node"]
    }
  }
}

### What is actually happening?
{
  "presets": [["es2015", { "modules": false }]],
  "plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
}

**Comment by zheng1013757145** [comment]
Should be this

{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime",
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ],
  "env": {
    "development":{
      "plugins": ["dynamic-import-node"]
    }
  }
}

**Comment by island205** [comment]
please try 2.5.x, we have do a lot change in this file.
