### ISSUE TITLE
The [Bug Report] selector component adds remote attributes without the downward arrow

### ISSUE THREAD

**Issue by zfowed** [ElemeFE/element#13947]
### Element UI version
2.4.11

### OS/Browsers version
window 10 / Google Chrome 71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7332/](https://jsfiddle.net/mmx38qxw/7332/)

### Steps to reproduce
选择器组件正常是有向下的箭头
添加 remote 属性就没有了

The selector component normally has a downward arrow
Adding the remote property is gone

### What is Expected?
选择器组件添加 remote 属性就有了向下的箭头

The selector component adds a remote attribute with a downward arrow

### What is actually happening?
选择器组件添加 remote 属性就没有了向下的箭头

The selector component adds the remote property without the down arrow

**Comment by island205** [comment]
交互问题：让用户输入过滤，不是为了让用选。
