### ISSUE TITLE
[Feature Request] Using more semantic element names without the prefix

### ISSUE THREAD

**Issue by douglasg14b** [ElemeFE/element#13953]
### Existing Component
No

### Component Name
N/A

### Description
I'm coming from `iview` where they managed to let you use more readable names for their elements with their [loader](https://www.iviewui.com/docs/guide/iview-loader-en), [repo](https://github.com/iview/iview-loader). Instead of using `el-button`, `el-tab-pane`, `el-tabs`....etc you can use `Button`, `TabPane`, or `Tabs`. Which for many is much more readable as PascalCase than kebab-case, especially with the prefix removed.

Can element add something similar to this, or if one exists already how is it configured?

This looks to be dead simple, it replaces the tag names based on a list of values and that's it.

**Comment by wacky6** [comment]
Only if you import on demand:

```JavaScript
import { Button, Select } from 'element-ui';
Vue.component(WhatEverNameYouWant, Button);
```

or writes jsx:
```jsx
import { Button as MyFancyButton } from 'element-ui';
render() {
    return <MyFancyButton />
}
```

---

There is no plan to support name alias for the whole package.

Vue template derives from HTML, which is **case-insensitive**. Aliasing `<el-input>` to `<Input>` (equivalent to `<input>` [native input element]) is misleading.


If you really want to do this, copy paste the code from `http://element.eleme.io/#/en-US/component/quickstart#on-demand`. Then replace `Vue.use` with the code above.
