### ISSUE TITLE
在form组件中使用select,元素无法垂直排列

### ISSUE THREAD

**Issue by lwhhhh** [ElemeFE/element#1395]
![](http://7xsc9d.com1.z0.glb.clouddn.com/2016-11-27%2013:32:36%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

### ElementUI version
 1.0.0-rc.9 

### OS/Browers version
Linux64/Chrome 54 

### Vue version
2.0.1

    <el-form label-width="80px" v-show="display_select_form">

         <el-form-item>

         <el-select v-model="course_selected" placeholder="请选择课程">

             <el-option v-for="course in course_list" v-bind:value="course" v-bind:key="course">

             </el-option>

         </el-select>

        </el-form-item>

    </el-form>

**Comment by Leopoldthecoder** [comment]
请给出 demo

**Comment by Leopoldthecoder** [comment]
超过七天没有反馈的 issue 我们会先关掉。若能提供 demo，可以重新打开。
