### ISSUE TITLE
👨🏻‍💻👩🏻‍💻欢迎加入 Element 支持交流群 

### ISSUE THREAD

**Issue by iamkun** [ElemeFE/element#13956]
扫描二维码加入 [钉钉](https://www.dingtalk.com/) 讨论组

For users in other languages, please keep using Github issue tracker. 🤟

![wechatimg10 1](https://user-images.githubusercontent.com/17680888/50588415-d9aaca00-0ebc-11e9-92e2-f71960346f85.png)

**Comment by svenjia** [comment]
老弟，来错片场了
