### ISSUE TITLE
[Feature Request] hope'expand'table's cell can be customized.

### ISSUE THREAD

**Issue by flyinglove** [ElemeFE/element#13961]
### Existing Component
是

### Component Name
table

### Description
I am trying to acheive this feature:
1. a table, which last column of each row has three buttons, and each of them is bound to a different function. when i click the last button, the inside table of each row will be expanded or shrinked.
2. at first i am trying to use your 'expand' configuration, but it turns out i can't customize the cell, which always is a default icon, but what i need is three buttons.
3. then i thought of use two el-table-columns, the former one will set the buttons, the latter one which type is 'expand' can be triggerd by a click on the former one, but this need to communciate between brother components.

**Comment by island205** [comment]
pr welcome
