### ISSUE TITLE
[Bug Report] Click on the root element, unable to cancel the full selection, In Tree Components

### ISSUE THREAD

**Issue by chqfly** [ElemeFE/element#13968]
### Element UI version
2.4.11

### OS/Browsers version
macOs 10.14 chrome  71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/m8baw4fz/1/](https://jsfiddle.net/m8baw4fz/1/)

### Steps to reproduce
Click on the root element, unable to cancel the full selection

### What is Expected?
Click on the root element, cancel the full selection

### What is actually happening?
Click on the root element, unable to cancel the full selection

**Comment by island205** [comment]
pr welcome

**Comment by githubyyf** [comment]
我也遇到了相同的问题，

**Comment by githubyyf** [comment]
我是通过<script src="https://cdn.jsdelivr.net/npm/element-ui@2.6.1/lib/index.js"></script>引入的js文件，不知道是不是您的修改还没有？
