### ISSUE TITLE
The min and max of the [Bug Report] input component are not valid

### ISSUE THREAD

**Issue by zbjy** [ElemeFE/element#13967]
### Element UI version
2.4.11

### OS/Browsers version
win 7 / Google Chrome（71.0.3578.98）

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7369/](https://jsfiddle.net/mmx38qxw/7369/)

### Steps to reproduce
针对input组件的number类型设置了min和max值，当点击上下箭头的时候是有效的，但自己输入数值，在失去焦点的时候没有进行最大最小的校验

### What is Expected?
input组件的min和max可以使用

### What is actually happening?
input组件的min和max不生效

**Comment by wacky6** [comment]
用input-number， input本来就不支持number的用法
