### ISSUE TITLE
The [Bug Report] tabs tab cannot modify the current activation tag by the value of V-model

### ISSUE THREAD

**Issue by wangtengfei1002** [ElemeFE/element#13965]
### Element UI version
2.4.11

### OS/Browsers version
win10/chrome71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1 handleClick 方法里 修改tabs v-model绑定的值， 修改后无法更改tabs的标签页

### What is Expected?
tabs v-model绑定的值 可以修改标签激活页

### What is actually happening?
handleClick 方法里 修改tabs v-model绑定的值， 修改后无法根据此行为更改tabs的标签页

**Comment by elfman** [comment]
请提供一个可以复现的demo

**Comment by wangtengfei1002** [comment]
> 请提供一个可以复现的演示
https://jsfiddle.net/api/post/library/pure/   （Tabs 标签页 任意demo在线运行）
在handleClick 方法里  修改 this.activeName = 'first'  但是只能修改一次，之后便不起作用

**Comment by GalinaGao123** [comment]
请问这个解决了吗。我也遇到了

**Comment by uniquejava** [comment]
> 请问这个解决了吗。我也遇到了

同问
