### ISSUE TITLE
[Bug Report] IE10 File Upload Problem

### ISSUE THREAD

**Issue by hqzh** [ElemeFE/element#13974]
### Element UI version
2.4.11

### OS/Browsers version
win10 ie10

### Vue version
2.5.21

### Reproduction Link
[https://github.com/ElemeFE/element/issues/3643](https://github.com/ElemeFE/element/issues/3643)

### Steps to reproduce
https://github.com/ElemeFE/element/issues/3643

### What is Expected?
fixed

### What is actually happening?
no fixed ,

**Comment by island205** [comment]
What is actually happening? Any error message?
