### ISSUE TITLE
[Bug Report] Table expanded row

### ISSUE THREAD

**Issue by yakovlev-valentin** [ElemeFE/element#13972]
### Element UI version
2.4.11

### OS/Browsers version
Linux Mint / Google chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Vue version
2.5.21

### Reproduction Link
[https://github.com/yakovlev-valentin/element-bug](https://github.com/yakovlev-valentin/element-bug)

### Steps to reproduce
1. Try to expand table in the first time. (Empty content)
2. Hide.
3. Expand again (Component loaded)

### What is Expected?
Expected to create a component and showing content in the first time.

### What is actually happening?
Async component rendering show only at secondly expanded table.

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
