### ISSUE TITLE
[Bug Report] upload picture ie10 haven't call uploading and success

### ISSUE THREAD

**Issue by hqzh** [ElemeFE/element#13978]
### Element UI version
2.4.11

### OS/Browsers version
win10 ie10

### Vue version
2.5.21

### Reproduction Link
no

### Steps to reproduce
ready have call,haven't call uploading and success

### What is Expected?
all call

### What is actually happening?
not all call

![_20190104103829](https://user-images.githubusercontent.com/26128706/50671577-bba0af00-100d-11e9-9577-691ba27073d7.png)
![_20190104103921](https://user-images.githubusercontent.com/26128706/50671579-bfcccc80-100d-11e9-9cbd-19cd85040980.png)

**Comment by hqzh** [comment]
@island205

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
