### ISSUE TITLE
[Bug Report] basic el-tabs' indicator line does not display as expect when used as 'card style' el-tabs' children

### ISSUE THREAD

**Issue by hreflee** [ElemeFE/element#13979]
### Element UI version
2.4.11

### OS/Browsers version
MacOS, Chrome 71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/nmzoxp59/3/](https://jsfiddle.net/nmzoxp59/3/)

### Steps to reproduce
basic el-tabs used as 'card style' el-tabs' children

### What is Expected?
the width of indicator line under the active tab should equal the tab label width.

### What is actually happening?
the width of indicator line under the active tab does not equal the tab label width.

**Comment by island205** [comment]
We find it out, because you use tab in tab, cause by style issue. PR welcome
