### ISSUE TITLE
[Bug Report] Table uses inputNumber to listen for changes in inputNumber, and table data does not refresh when the value is undefined

### ISSUE THREAD

**Issue by Zypom** [ElemeFE/element#13981]
### Element UI version
2.4.11

### OS/Browsers version
macOS High Sierra/Google Chrome 版本 71.0.3578.98（正式版本） （64 位）

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/qeko4t8c/10/](https://jsfiddle.net/qeko4t8c/10/)

### Steps to reproduce
监听change事件，假如inputNumber绑定值为undefined，将绑定值变为0，然后Vue.set()刷新Table的数据。

### What is Expected?
假如inputNumber绑定值为undefined，将绑定值变为0

### What is actually happening?
假如inputNumber绑定值为undefined，绑定值没有变为0，还是undefined

**Comment by wacky6** [comment]
先nextTick吧。 https://jsfiddle.net/9gdptcmx/
