### ISSUE TITLE
[Bug Report] Readonly input emit the 'blur' event

### ISSUE THREAD

**Issue by iGarym** [ElemeFE/element#13982]
### Question
It's a feature or a bug?

### Element UI version
2.4.11

### OS/Browsers version
win10  chrome70

### Vue version
2.5.21

### Reproduction Link
[jsfiddle](https://jsfiddle.net/4bL3jx17/1/)

### Steps to reproduce
Click the readonly input component, then click elsewhere. The 'blur' event emitted.

### What is Expected?
Readonly input don't emit the 'blur' event.

### What is actually happening?
Readonly input component emit the 'blur' event.

**Comment by wacky6** [comment]
this is not a bug. native readonly input also emits blur event. https://jsfiddle.net/Lrm17bod/
