### ISSUE TITLE
[Bug Report] NavMenu

### ISSUE THREAD

**Issue by mynameissujie** [ElemeFE/element#13986]
`<!--` generated by https://eleme-issue.surge.sh DO NOT REMOVE -->

### Element UI version
2.4.11

### OS/Browsers version
谷歌浏览器

### Vue version
2.5.21

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
多个navMenu之间 使用default-active时，如果值是相同的 则navMenu之间切换会导致显示问题

### What is Expected?
希望正常切换不同的navMenu的时候选中状态是对的

### What is actually happening?
切换不同的navMenu的时候选中状态是有问题的，在值相同的情况下。

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
