### ISSUE TITLE
[Bug report] [Popover] recommends using input to detect whether Popover is out of focus

### ISSUE THREAD

**Issue by Richard-Choooou** [ElemeFE/element#13997]
### Existing Component
是

### Component Name
Popover

### Description
当popover的属性trigger设置为‘click’后，如果页面上的某个dom阻止了事件冒泡，那么popover组件无法捕获到页面的点击事件，从而导致popover无法关闭，如果用input来检测是否失焦，或者在事件捕获阶段执行隐藏popover比较稳妥

**Comment by iamkun** [comment]
see comment in PR
