### ISSUE TITLE
[Bug Report] Table sets show-summary, sets fixed on left and right columns, and drags and drops fixed columns that cannot scroll horizontally.

### ISSUE THREAD

**Issue by michkish** [ElemeFE/element#13995]
### Element UI version
2.4.11

### OS/Browsers version
Win 7 /Chrome 71.0.3578.98

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/2oqderaw/](https://jsfiddle.net/2oqderaw/)

### Steps to reproduce
详情见 https://jsfiddle.net/2oqderaw/ 。
table设置了show-summary属性以后，在两个已经fixed的日期和操作column下的scrollbar无法拉动。

### What is Expected?
table设置了show-summary属性以后，scrollbar的拖动行为不应该受fixed column干扰。

### What is actually happening?
table设置了show-summary属性以后，在两个已经fixed的日期和操作column下的scrollbar无法拉动。

**Comment by ziyoung** [comment]
Duplicate of #5415
