### ISSUE TITLE
[Bug Report] Prefix slot of el-select is not working correctly

### ISSUE THREAD

**Issue by tigerbook73** [ElemeFE/element#13990]
### Element UI version
2.4.11

### OS/Browsers version
Win10/Firefox

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/qdpc63hw/1/](https://jsfiddle.net/qdpc63hw/1/)

### Steps to reproduce
在el-select中增加prefix slot，增加的内容会和input区域重叠

### What is Expected?
prefix slot中的内容和input字段不重叠，大小对齐

### What is actually happening?
prefix slot中的内容和input字段重叠，大小不对齐

**Comment by island205** [comment]
use `prepend`

**Comment by island205** [comment]
Please write css to fix style issue.

**Comment by Jesean** [comment]
https://www.iviewui.com/components/select
换iview吧，组件比element多，细节比element考虑周到
![image](https://user-images.githubusercontent.com/18478838/67474932-d836d200-f687-11e9-9ba9-6d3d25d42a53.png)

**Comment by timestee** [comment]
> Please write css to fix style issue.

mark下，迄今为止，github上看到的开源工程比较搞笑的回复。。。
