### ISSUE TITLE
[Feature Request] The table component adapts the column width through the content so that the content is not hidden.

### ISSUE THREAD

**Issue by wenjayliu** [ElemeFE/element#13991]
### Existing Component
是

### Component Name
table

## 表格动态获取的文字内容不隐藏也不换行
发现现有的table功能是由表头内容决定列的最小宽度。  
由于表头和表格内容均由后端返回， 在不设置固定列宽或最小列宽的情况下，是否可以增加由内容决定最小列宽，使得文字不换行显示。  

## 原生效果展示：Reproduction Link  
> https://jsfiddle.net/wenjayliu/sb59a6L2/20/

**Comment by island205** [comment]
Sorry, we have no plan to support this.
