### ISSUE TITLE
[Bug Report] [ on component Pagination ] There will be an ellipsis while there is only 8 pages ( when attribute pageCount is set to 8 ).

### ISSUE THREAD

**Issue by daGaiGuanYu** [ElemeFE/element#13999]
### Element UI version
2.4.11

### OS/Browsers version
win10/chrome 71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/gy0318/eywraw8t/536610/](https://jsfiddle.net/gy0318/eywraw8t/536610/)

### Steps to reproduce
click that link and you will see it.

### What is Expected?
An ellipsis should not be displayed while the ellipsis only has one page.

### What is actually happening?
The ellipsis would have only one page while the size of pages is equal to the value of attribute pageCount and the ellipsis is meaningless.

**Comment by island205** [comment]
pr welcome
