### ISSUE TITLE
[Bug Report] Table header horizontal scrollbar not syncing with body horizontal scrollbar

### ISSUE THREAD

**Issue by jrosczyk** [ElemeFE/element#14002]
### Element UI version
2.4.11

### OS/Browsers version
Mac / Safari, Chrome, Firefox

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/b6wsdhoc/](https://jsfiddle.net/b6wsdhoc/)

### Steps to reproduce
1. Go to this jsfiddle: https://jsfiddle.net/b6wsdhoc/
2. Scroll right in the table header using the scrollbar (not a gesture scroll)
3. You will see that the table body does not scroll with the header

### What is Expected?
That the table header horizontal scrollbar syncs with the body scrollbar and the body content moves with the header. The same way that the body scrollbar syncs and moves the header scrollbar. Both ways should be in sync.

### What is actually happening?
The header horizontal scrollbar moves the column header only, not the table body wrapper. Using a touch gesture mouse and swiping does sync both... but when using the scrollbar on header the body doesn't move with it.

**Comment by sstraus** [comment]
Any chance to get it fixed?

**Comment by sandesh-bhoir** [comment]
this issue still persists, is there any update on same..!
