### ISSUE TITLE
[Bug Report] el-dropdown pressing enter will cause the drop-down menu to be withdrawn

### ISSUE THREAD

**Issue by zwmmm** [ElemeFE/element#14007]
### Element UI version
2.4.11

### OS/Browsers version
window 10 / Chrome 70

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7393/](https://jsfiddle.net/mmx38qxw/7393/)

### Steps to reproduce
1.点开下拉菜单
2.按下回车键

### What is Expected?
按回车可以正常触发搜索, 而不是关闭下拉菜单

### What is actually happening?
按回车则关闭下拉菜单

**Comment by zwmmm** [comment]
![image](https://user-images.githubusercontent.com/30194521/50816057-596fe300-135a-11e9-8189-a25431697031.png)

**Comment by zwmmm** [comment]
看了代码 这段代码应该是select组件使用到的, 是否考虑下不在select组件中使用的时候讲快捷键关闭

**Comment by zwmmm** [comment]
![image](https://user-images.githubusercontent.com/30194521/50954657-fca73080-14f1-11e9-95a3-b1c4da582269.png)
暂时的解决办法

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
