### ISSUE TITLE
[Feature Request] Better customization options for font sizes, heights, paddings, etc

### ISSUE THREAD

**Issue by sp00x** [ElemeFE/element#14001]
### Existing Component
Yes

### Component Name
All

### Description
As far as colors go there seems to be customization coverage, but if you want to adjust e.g. font sizes its suddenly turns worse.

There is stuff like `$--font-size-base` which is *14px* by default, but then if you change it .... you'll soon notice that menus, buttons, and this and that still stays 14px - because it's **hard-coded** to 14px in all the .scss files there.

The same goes for header sizes, menu sizes etc. It seems to be hard coded around *60px*, and *20px* is repeated a lot of places for paddings.

And so on...

(I was hoping this would be better in Element that it is in Vuetify, but sadly not...)

Wouldn't it makes sense to just pull all this *14px* and *60px* vars out to the central var.scss file and use it from there? Then customization would actually be possible..

**Comment by island205** [comment]
We will support great theme config funciton in coming future, please waiting for it!
