### ISSUE TITLE
[Feature Request] When all rows are set to non-selectable, the multi-selection header checkbox should be disabled.

### ISSUE THREAD

**Issue by ILTomatoes** [ElemeFE/element#14009]
### Existing Component
是

### Component Name
ElTable

### Description
目前多选表格在 data.length === 0 时，复选列的表头时禁用的。但是当表格的所有行都被禁止勾选时，表头复选框确实可用，并且是全选状态的。这两种情况对于表头复选框来说，都是没有可操作数据的情形。感觉应该统一一下逻辑。

**Comment by angelsunshuli** [comment]
当table中没有数据时，表头的checkbox确实是disabled，但是仍旧可以选择（即仍旧可以添加is-checked），从交互角度看感觉不合理。
