### ISSUE TITLE
[Bug Report] el-input component handleInput error reporting

### ISSUE THREAD

**Issue by weixian5** [ElemeFE/element#14013]
### Element UI version
2.4.11

### OS/Browsers version
mac

### Vue version
2.5.21

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue ](https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue )

### Steps to reproduce
handleInput 方法，里面使用了$refs.input
这个方法被input 和textarea 调用，textarea没有$refs.input 导致报错
缺少判断

### What is Expected?
修复

### What is actually happening?
修复

**Comment by plqin-xiaohao** [comment]
???

关于 `What is Expected?` 你可以再组织一下,  不能理解你的描述

**Comment by wacky6** [comment]
都发现问题了开个pr呗

**Comment by island205** [comment]
fixed in #14143
