### ISSUE TITLE
[Bug Report] Can not close the drop-down box by clicking right arrow icon on Select  Components with "Create new items"

### ISSUE THREAD

**Issue by doudoudzj** [ElemeFE/element#14011]
### Element UI version
2.4.11

### OS/Browsers version
Windows、Mac/Chrome71.0.3578.98

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/rbuk7f50/](https://jsfiddle.net/rbuk7f50/)

### Steps to reproduce
Select  Components with "Create new items":
click the select element, display the drop-down box,but when I click the arrow icon on the right side, I can't close the drop-down box.

### What is Expected?
When I click on the arrow icon on the right, can switch the display of the drop-down box.

### What is actually happening?
Can't close the drop-down box by clicking on the arrow icon on the right，must click on other blanks、element，or click key ESC

**Comment by plqin-xiaohao** [comment]
Because ` filterable `

**Comment by doudoudzj** [comment]
The arrow icon is used to switch the drop-down menu, the `filterable` select should also include this feature.
They have no mutual exclusion.

**Comment by island205** [comment]
pr welcome
