### ISSUE TITLE
[Bug Report] Alert description not formatted correctly when using default slot.

### ISSUE THREAD

**Issue by claviska** [ElemeFE/element#14015]
### Element UI version
2.4.11

### OS/Browsers version
All

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7398/](https://jsfiddle.net/mmx38qxw/7398/)

### Steps to reproduce
Open the fiddle. View the result.

### What is Expected?
[Per the documentation](https://element.eleme.io/#/en-US/component/alert#attributes), when using the default slot in an alert, the content should appear the same as if you were using the description attribute.

### What is actually happening?
When using the default slot, the content is not wrapped in an `el-alert__description` class, so it appears to render incorrectly.

**Comment by plqin-xiaohao** [comment]
so , Is that what you want?

https://jsfiddle.net/qingguipeng/p9ok10hL/

**Comment by claviska** [comment]
Not quite. According to the documentation:

> description | descriptive text. Can also be passed with the default slot

So whether you're using the `description` attribute or the default slot, you should end up with the same markup and appearance. However, here's what it looks like right now:

```vue
  <!-- via attribute -->
  <el-alert
    title="Works"
    description="This one is formatted correctly."
    type="success"
   >
   </el-alert>
  
  <!-- via slot -->
  <el-alert
    title="Whoops"
    type="warning"
  >
    This one is not. When using the default slot for description, the el-alert__description class isn't applied.
  </el-alert>
```

![image](https://user-images.githubusercontent.com/55639/50912411-18caa500-1400-11e9-95f2-28651cf089d4.png)

The problem is that, when using the default slot, you don't get the `el-alert__description` wrapper because it's only applied [if a description attribute is present](https://github.com/ElemeFE/element/blob/dev/packages/alert/src/main.vue#L15).

Currently, the only way to achieve consistent styles when using description as the default slot is to manually insert the wrapper yourself:

```vue
  <!-- workaround -->
  <el-alert
    title="Workaround"
    type="warning"
  >
    <p class="el-alert__description">
      This works around the issue, but you really shouldn't have to add the class yourself.
    </p>
  </el-alert>
```

![image](https://user-images.githubusercontent.com/55639/50912642-9bebfb00-1400-11e9-97c0-631a732c3304.png)

But that feels a bit dirty. It should probably be something like this so the `el-alert__description` wrapper is always applied:

```vue
<p class="el-alert__description">
  <!-- Use description attribute if present -->
  <span v-if="description">{{ description }}</span>

  <!-- Fall back to default slot -->
  <slot v-else></slot>
</p>
```
