### ISSUE TITLE
[Bug Report] v-loading.lock is not compatible with el-dialog

### ISSUE THREAD

**Issue by shellus** [ElemeFE/element#14019]
### Element UI version
2.4.11

### OS/Browsers version
windows 10 last/chrome last

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/shellus/ua2kfyzo/](https://jsfiddle.net/shellus/ua2kfyzo/)

### Steps to reproduce
1. 点击dialog按钮打开dialog框
2. 点击dialog框内的“提交表单” 按钮，此时会开始loading

### What is Expected?
loading 仅覆盖在 dialog框区域

### What is actually happening?
loading 覆盖在整个浏览器窗口

**Comment by bosscheng** [comment]
<div id="app">
  <el-button @click="dialogVisible=true">dialog</el-button>
  <el-dialog title="提示" :visible.sync="dialogVisible" >
    <div v-loading.lock="loading">
      <el-button @click="handleClick">提交表单</el-button>
    </div>
  </el-dialog>
</div>

包裹一层 div 就解决了。

**Comment by shellus** [comment]
在文档没有提到这种hack的情况下，这是一个需要修复的bug发自我的iPhone------------------ Original ------------------From: bosscheng  <notifications@github.com>Date: Wed,Jan 9,2019 10:39 AMTo: ElemeFE/element <element@noreply.github.com>Cc: 娃娃脾气3 <shellus@endaosi.com>, Author <author@noreply.github.com>Subject: Re: [ElemeFE/element] [Bug Report] v-loading.lock is not compatiblewith el-dialog (#14019)
  dialog
  
    
      提交表单
    
  

包裹一层 div 就解决了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ElemeFE/element","title":"ElemeFE/element","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ElemeFE/element"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bosscheng in #14019: \u003cdiv id=\"app\"\u003e\r\n  \u003cel-button @click=\"dialogVisible=true\"\u003edialog\u003c/el-button\u003e\r\n  \u003cel-dialog title=\"提示\" :visible.sync=\"dialogVisible\" \u003e\r\n    \u003cdiv v-loading.lock=\"loading\"\u003e\r\n      \u003cel-button @click=\"handleClick\"\u003e提交表单\u003c/el-button\u003e\r\n    \u003c/div\u003e\r\n  \u003c/el-dialog\u003e\r\n\u003c/div\u003e\r\n\r\n包裹一层 div 就解决了。"}],"action":{"name":"View Issue","url":"https://github.com/ElemeFE/element/issues/14019#issuecomment-452550861"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ElemeFE/element/issues/14019#issuecomment-452550861",
"url": "https://github.com/ElemeFE/element/issues/14019#issuecomment-452550861",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bosscheng** [comment]
@shellus 赞同。

**Comment by island205** [comment]
@hoythan 的说法是对的。

**Comment by uniquejava** [comment]
> 如果只要某部分内容显示 loading 请在内部添加 div。

@hoythan, 请问el-dialog一般都会带slot="footer",  这种情况下 `请在内部添加 div`应该怎么加?

**Comment by hoythan** [comment]
> > 如果只要某部分内容显示 loading 请在内部添加 div。
> 
> @hoythan, @bosscheng 请问el-dialog一般都会带slot="footer", 这种情况下 `请在内部添加 div`应该怎么加? 和作者有相同的疑问我希望loading 在dialog居中显示. (比如提交dialog中的一个表单的时候)
> 
> 搜索关键字dialog loading会发现这个相同的问题报告了好多次. 有没有终极解决方案 比如同样的问题也出现在这个 issue #11495

在 loading 的时候，将footer的按钮disabled 掉是比较常见的做法。
而且如果你要整个dialog，那么dialog上的关闭按钮都无法点击了，如果你接口请求错误或加载时间过久导致无法让 loading false，那么用户将永远无法退出这个dialog。
这本来就是产品或开发的问题。和代码无关。
