### ISSUE TITLE
[Bug Report] form validate message using i18n not working

### ISSUE THREAD

**Issue by zbotvnz** [ElemeFE/element#14016]
rules: {
        diameter: [{ required: true, message: this.$t('table.hair.validate.requiredDiameter'), trigger: 'change' }],
        softness: [{ required: true, message: this.$t('table.hair.validate.requiredSoftness'), trigger: 'change' }],
        colorType: [{ required: true, message: this.$t('table.hair.validate.requiredColorType'), trigger: 'change' }],
        origin: [{ required: true, message: this.$t('table.hair.validate.requiredOrigin'), trigger: 'change' }]
      }

When I change language that is not working, that just changed when refresh page

**Comment by JBtje** [comment]
In release 2.9 you'll be able to use
`...ired: true, message: () => this.$t('table.hair.validate.requiredDiameter'), trig...`

See: https://github.com/yiminghe/async-validator/pull/157

**Comment by keitetran** [comment]
it not working, i was get that mesage 

> function() { return _vm.$lang.t( _vm.$consts.lang.validator.required ) }

**Comment by JBtje** [comment]
> it not working, i was get this mesage
> 
> > function() { return _vm.$lang.t( _vm.$consts.lang.validator.required ) }

That is because Element-ui is STILL using 1.8, not 1.11 of async-validator.....
See #15235

**Comment by keitetran** [comment]
thank you very much. 

https://github.com/ElemeFE/element/pull/15235/files

**Comment by JBtje** [comment]
What I did:
- Install all NPM packages
- Install     github:JBtje/async-validator    This is a build of the latest async-validator and includes the lib folder.
- Remove the folder "async-validator" from node_modules/element-ui/node_modules/async-validator

Build your package. It will now use the latest version of async-validator.
