### ISSUE TITLE
checkbox only pass label, not other value

### ISSUE THREAD

**Issue by yangxiaolin** [ElemeFE/element#14018]
### Existing Component
是

### Component Name
checkbox

### Description
        // i want to pass value for checkbox
        // and when checkbox is checked,
        // will send value to handler
        // but now, checkbox just support send label to handler
        // in most time, label is repeatly
        ```js
          <el-checkbox
            v-for="(item, index) of list"
            :key="index"
            :label="item.name"
            :value="item.value" // checkbox not support pass value
          >
          </el-checkbox>
        ```

[feature is here](https://codesandbox.io/s/2w2xv1q27n)

**Comment by johnny00110** [comment]
Just tried, I thought it would work.

```js
<el-checkbox
  v-for="(item, index) of list"
  :key="index"
  :label="item.value"
  :value="item.value" // checkbox not support pass value
>
  <template slot="default">{{ item.name }}</template>
</el-checkbox>
```

[ref]
https://github.com/ElemeFE/element/blob/master/packages/checkbox/src/checkbox.vue#L51

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by selectfake** [comment]
because label and value is opposite ,u can use like `<el-checkbox :label="{{label}}" name="a">{{value}}</el-checkbox>` ,u  can get label in your array
