### ISSUE TITLE
[Bug Report] Tree control uses el-dropdown as the command of overflow menu click for event bubbles

### ISSUE THREAD

**Issue by wuchubuzai2018** [ElemeFE/element#14021]
### Element UI version
2.3.6

### OS/Browsers version
mac/firefox49

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/7415/](https://jsfiddle.net/mmx38qxw/7415/)

### Steps to reproduce
1、单击每行树节点中的更多按钮，单击dropdown生成的按钮，会触发tree的单击事件，但是我不想触发单击事件

### What is Expected?
1、单击每行树节点中的更多按钮，单击dropdown生成的按钮，会触发tree的单击事件，但是我不想触发单击事件，我是想单击溢出的dropdown菜单，实现对树的操作，不想触发树的单击事件，能否在dropdown组件的command为click时添加一个阻止事件冒泡的设置

### What is actually happening?
1、单击每行树节点中的更多按钮，单击dropdown生成的按钮，会触发tree的单击事件，这个不是我想要的，我想单击dropdown的操作时，不进行事件冒泡

**Comment by plqin-xiaohao** [comment]
look : 

https://jsfiddle.net/qingguipeng/58r6kLgq/

It's a compromise function

**Comment by island205** [comment]
your workaround is ok
