### ISSUE TITLE
[Bug Report] When using V-IF and v-else-if to switch el-table-column in table, it will result in the invalidation of some properties of el-table-column.

### ISSUE THREAD

**Issue by plqin-xiaohao** [ElemeFE/element#14023]
### Element UI version
2.4.11

### OS/Browsers version
Windows 10 / Chrome 63

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/qingguipeng/burjkL9x/](https://jsfiddle.net/qingguipeng/burjkL9x/)

### Steps to reproduce
反复点击按钮 :  `点我` ;

>English: Click the button again and again: `点我 ` 

### What is Expected?
第一个table表格中的 `姓名` 仍然带有 `排序` 的属性 ;

>English: The first table in the table name `姓名` still had a sort properties;

### What is actually happening?
第一个table表格中的 `姓名` 不再带有 `排序` 的属性

>English: The first table in the table name `姓名` no have a sort properties;

**Comment by plqin-xiaohao** [comment]
@element-bot What is the translation API used by the robot? The translation is very accurate

**Comment by plqin-xiaohao** [comment]
@island205 Hi  island205 , I urgently need answers, help me

**Comment by plqin-xiaohao** [comment]
look : 

https://jsfiddle.net/qingguipeng/burjkL9x/4/

I found a new situation :  

In two `el-table-column` contain ` sortable ` , using `v-if/v-else-if` switch `el-table-column`, the `el-table-column` will not be affected;

**Comment by plqin-xiaohao** [comment]
brother, I urgently need a way to achieve my goal, can you provide me with an idea to use first

**Comment by island205** [comment]
sorry i would, but i can't

**Comment by plqin-xiaohao** [comment]
okok,

I use three inches golden tongue persuaded the PM and UI, temporarily for each ` el-table-column` add ` sortable ` ,  elementui engineer, looking forward to you provide a solution as soon as possible ;

🎉 😙 ❤️

**Comment by plqin-xiaohao** [comment]
@goforward01 very good ! nice ~ 🆒 👍

**Comment by plqin-xiaohao** [comment]
> @plqin-xiaohao something wrong with the tag of sortable, try this for temporary solution: change sortable to :sortable="true".
> `https://jsfiddle.net/goforward01/burjkL9x/12/`

At this point, do I need to end the question?

**Comment by goforward01** [comment]
@plqin-xiaohao I don't think so. Still need to waiting for a official solution or a proper fix for this issue. I think maybe something wrong with the function of getHeaderCellClass.

**Comment by plqin-xiaohao** [comment]
> @plqin-xiaohao I don't think so. Still need to waiting for a official solution or a proper fix for this issue. I think maybe something wrong with the function of getHeaderCellClass.

OK

**Comment by ziyoung** [comment]
已无法重现。关闭 issue。https://jsfiddle.net/hcu0w7n6/
