### ISSUE TITLE
[Bug Report] [Table] How to remove class css added in tr tags before

### ISSUE THREAD

**Issue by henrytom1703** [ElemeFE/element#14022]
### Element UI version
2.4.11

### OS/Browsers version
Chrome/71.0.3578.98 Safari/537.36

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/7j8xom93/](https://jsfiddle.net/7j8xom93/)

### Steps to reproduce
1.  use the attribute row-class-name to add the css class to <tr> tags
2.  I have a button remove. When I click on button then all class added before that will be remove

### What is Expected?
All  css class (warning-row, success-row) will be remove when click on remove button
- Or other question:
how to add and remove the class animation in <tr> tags?

### What is actually happening?
I dont know how to remove the class css in <tr> tags

**Comment by island205** [comment]
i wrote a demo https://jsfiddle.net/7j8xom93/18/, did you want swith function like this?

**Comment by henrytom1703** [comment]
Hello @island205 
My issue relate to add and remove css animation. 
Error: I must click 2 times on switch button  then animation will be work
Here my demo.
[https://jsfiddle.net/7j8xom93/20/](https://jsfiddle.net/7j8xom93/20/)

**Comment by island205** [comment]
some solution like _setTimeout_?

**Comment by henrytom1703** [comment]
@island205  How to setTimeout?
Here my example [https://jsfiddle.net/7j8xom93/20/](https://jsfiddle.net/7j8xom93/20/
)

**Comment by island205** [comment]
https://jsfiddle.net/7j8xom93/22/
