### ISSUE TITLE
[Bug Report] Unnecessary usage of getValueByPath in select.vue

### ISSUE THREAD

**Issue by folmert** [ElemeFE/element#14032]
### Element UI version
2.4.11

### OS/Browsers version
any (Windows 10, Linux Ubuntu)

### Vue version
2.5.21

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
select.vue uses this quirky getValueByPath from util.js which seems to work like lodash's get(), but because of that it's impossible to use flattened property names as select's v-model.

Say I keep my models in :
```
data () {
	return {
		models: {'flattenedObject.property': 'something'}
	}
}
```

select.vue will try to unnecessarily translate it to models.flattenedObject.property.

### What is Expected?
When I pass models['flattenedObject.property'] as v-model to ElSelect's multiselect field it should try to access models['flattenedObject.property'], not models.flattenedObject.property.

### What is actually happening?
When I pass models['flattenedObject.property'] as v-model to ElSelect's multiselect field it throws:
```
Error in callback for watcher "value": "TypeError: Cannot read property 'length' of null"
```

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
