### ISSUE TITLE
[Bug Report] Tree demo of render function not work

### ISSUE THREAD

**Issue by zhangchunlin** [ElemeFE/element#14038]
### Element UI version
2.4.11

### OS/Browsers version
ubuntu 18.04/ chrome 70.0

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/764ha3nL/](https://jsfiddle.net/764ha3nL/)

### Steps to reproduce
access https://jsfiddle.net/764ha3nL/

### What is Expected?
The label not empty

### What is actually happening?
the demo cannot display as expected, the label is empty

**Comment by ziyoung** [comment]
jsfiddle 不支持 jsx。请检查一下项目是否正确编译了 render-content。
