### ISSUE TITLE
[Bug Report] open a messageBox, after click confirm open a dialog, the mask will blink

### ISSUE THREAD

**Issue by mengfairy** [ElemeFE/element#14030]
### Element UI version
2.4.11

### OS/Browsers version
maxOS 10.14.2 / Chrome 71

### Vue version
2.5.21

### Reproduction Link
[http://jsfiddle.net/4cq1jm3h/24/](http://jsfiddle.net/4cq1jm3h/24/)

### Steps to reproduce
click button, then click messageBox confirm, the bug will occur

### What is Expected?
mask don't blink

### What is actually happening?
it dose blink

**Comment by plqin-xiaohao** [comment]
emmm , This is a real headache

**Comment by hoythan** [comment]
你应该吧nexttick 改成 setimeout并给300ms的动画关闭时间，就可以完美的解决这个问题。
```
setTimeout(() => {
	          this.dialogVisible = true;
},300)
```

**Comment by mengfairy** [comment]
> 你应该吧nexttick 改成 setimeout并给300ms的动画关闭时间，就可以完美的解决这个问题。
> 
> ```js
> this.$nextTick(() => {
>     this.dialogVisible = true;			
> });
> 
> // 改为=> 
> 
> setTimeout(() => {
>     this.dialogVisible = true;
> }, 300)
> ```

每次出现这种场景都要setTimeout, 我认为这不是一个好的解决办法

**Comment by ziyoung** [comment]
thanks @hoythan
