### ISSUE TITLE
The [Bug Report] table component defines percentage widths using min-width. The inconsistency between the width of the header and the width of the column causes the table to be staggered, and the difference between the width of th and the width of TD is 0.8px.

### ISSUE THREAD

**Issue by csl3505** [ElemeFE/element#14034]
### Element UI version
0.1.0

### OS/Browsers version
win10/chrome

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/zeroChan/jm2sg5yx/4/](https://jsfiddle.net/zeroChan/jm2sg5yx/4/)

### Steps to reproduce
运行代码，调整页面大小

### What is Expected?
调整页面大小，表头与列宽变换要一致

### What is actually happening?
调整页面大小，表头与列宽变换不一致导致表格错位

**Comment by ziyoung** [comment]
这个功能优先级很低，我们暂时没有计划去实现该功能。
