### ISSUE TITLE
[Bug Report] Input cursor height is abnormal on Safari

### ISSUE THREAD

**Issue by suguoyao** [ElemeFE/element#14036]
### Element UI version
2.4.11

### OS/Browsers version
macOS/Safari 10.1 (12603.1.30.0.34)

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/suguoyao/zbvqnue5/](https://jsfiddle.net/suguoyao/zbvqnue5/)

### Steps to reproduce
See jsfiddle on Safari.

### What is Expected?
The height of the cursor is the same as the height of placeholder text. It is normal on Chrome.
![image](https://user-images.githubusercontent.com/16471605/50947814-f5c0f380-14da-11e9-8a28-a6a07ff3a4fd.png)

### What is actually happening?
The height of the cursor is the same as the height of the input box.
![image](https://user-images.githubusercontent.com/16471605/50947789-de820600-14da-11e9-9cb7-0ce8c139bc13.png)

**Comment by ziyoung** [comment]
Sorry, we have no plan to fix this issue.
