### ISSUE TITLE
[Feature Request] Change case sensitiveness of defaultSort easily

### ISSUE THREAD

**Issue by mrmnmly** [ElemeFE/element#14031]
### Existing Component
Yes

### Component Name
el-table

### Description
When using `defaultSort` property on ElementUI's Table component, it always sort uppercase entries first, e.g. for data:

```
[
{id: 1, name: 'Zen'},
{id: 2, name: 'Alan'),
{id: 3, name: 'alex'},
{id: 4, name: 'zoe'}
]
```

When `defaultSort` is set like:

```
:defaultSort="{prop: 'name'}"
```

The output order will be: `[Alan, Zen, alex, zoe]` while I expect `[Alan, alex, Zen, zoe]` - I think this should be easily achievable (e.g. by adding additional param `caseSensitive` or something.

**Comment by plqin-xiaohao** [comment]
You can be sorted according to `id `  ,  or build yourself a new list based on a rule

**Comment by island205** [comment]
Sorry, we have no plan to support this, suggestion same as @plqin-xiaohao
