### ISSUE TITLE
[Bug Report] upload component does not work properly

### ISSUE THREAD

**Issue by felix307253927** [ElemeFE/element#14045]
### Element UI version
2.4.11

### OS/Browsers version
deepin15.8/chrome 71.0.3578.80（正式版本） （64 位）

### Vue version
2.5.21

### Reproduction Link
[https://github.com/ElemeFE/element/issues/14044](https://github.com/ElemeFE/element/issues/14044)

### Steps to reproduce
官网示例中点击 上传按钮没反应

### What is Expected?
弹出文件选择框

### What is actually happening?
无任何反应

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
