### ISSUE TITLE
[Feature Request] el-select component provides a method for manual value-passing search

### ISSUE THREAD

**Issue by winter-ice** [ElemeFE/element#14048]
### Existing Component
是

### Component Name
el-select

### Description
定义了一个远程搜索的select组件，有需求需要手动传值并搜索，也就是通过js给select组件内的input绑定值并执行queryChange

**Comment by winter-ice** [comment]
目前大概是通过以下代码实现的需求：
```
this.$refs.select.focus()
this.$nextTick(() => {
  this.$refs.select.$children[0].currentValue = query
  this.$refs.select.handleQueryChange(query)
})
```

**Comment by island205** [comment]
Sorry, we have no plan to support this.

**Comment by winter-ice** [comment]
看了一下iview好像有`setQuery`这个api，element为什么没有计划加入这个api？
