### ISSUE TITLE
[Table]  无数据时“暂无数据”提示自定义

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#1405]
### ElementUI version
1.0.2

### OS/Browers version
win10/Chrome 54

### Vue version
2.1.3

### What is Expected?
当没有数据时，暂无数据的那个提示希望可以自定义
### What is actually happening?
暂时没有找到自定义接口

**Comment by AaronChen2012** [comment]
emptyText

**Comment by furybean** [comment]
是的，使用 emptyText prop 就可以。
