### ISSUE TITLE
[Feature Request] popper.js adds a new positionFixed property, and the popper.js in the elementUI is a bit old

### ISSUE THREAD

**Issue by hltfe** [ElemeFE/element#14053]
### Existing Component
是

### Component Name
el-select, el-date-picker

### Description
positionFixed 可以让用户根据场景自己选择 弹出层是否fixed

**Comment by hltfe** [comment]
另外, el-select 等组件 对popper 封装的力度太低, 很多功能属性 没有封装到,  比如 hide,  boundariesElement  等, 需要添加这些属性的封装

**Comment by ziyoung** [comment]
refs #11778
