### ISSUE TITLE
[Bug Report] In MacOS, if the table component rolls vertically or horizontally, the border is not beautiful enough.

### ISSUE THREAD

**Issue by QQ34205037** [ElemeFE/element#14052]
### Element UI version
2.4.11

### OS/Browsers version
macOS Mojave 10.14.2 (18C54) / Google Chrome 71.0.3578.98

### Vue version
2.5.21

### Reproduction Link
[https://elementui.github.io](https://elementui.github.io)

### Steps to reproduce
抱歉，请注意：因为重现链接使用ElementUI官网示例即可，所以未另行提供重现链接，请看
http://element-cn.eleme.io/#/zh-CN/component/table

该页面第5个示例：“固定表头”示例
该页面第7个示例：“固定列和表头”示例

### What is Expected?
1.在table示例页面第5个“固定表头”的示例中（表格本身带有边框），希望最后一列（相邻滚动条滑槽）的边框与其他列的边框保持一致：1px。

2.在table示例页面的第7个“固定列和表头”示例中(表格本身不带边框)，希望横向和纵向滚动条在视觉上保持与滚动容器的一体感（容器带边框包裹滚动条），并由容器提供滚动条滑槽（滚动方向上）的上下边框（容器带边框）。

### What is actually happening?
1.示例5：因为mac系统原生滚动条的滑槽本来就是带边框的，与table最后一列的边框重复，导致最后一列的边框看起来是2px,与其他边框的1px有视觉差异。
这个问题在横向滚动条上应该也是存在的，不过横向滚地条上的双边框看起来不那么明显。

2.示例7：横向和纵向滚动条的滑槽没有（滚动方向上的）上下边框，导致视觉上难看，并且滚动条和table看起来不是一体的。

**Comment by island205** [comment]
pr welcome

**Comment by Jialufeng** [comment]
要啥自行车
