### ISSUE TITLE
[Feature Request] Form-Item component provides a attribute for show the description

### ISSUE THREAD

**Issue by suguoyao** [ElemeFE/element#14050]
### Existing Component
Yes

### Component Name
el-form-item

### Description
Is it possible to provide a attribute to show the corresponding el-form-item description?

### What is my expected?
[https://jsfiddle.net/suguoyao/h4zp32fv/](https://jsfiddle.net/suguoyao/h4zp32fv/)

Also, if can provide the ability to change the position of description, it would be great.

**Comment by island205** [comment]
pr welcome
