### ISSUE TITLE
[Bug Report] Tabs not created when el-tab-pane elements are wrapped in a container

### ISSUE THREAD

**Issue by jasperdavis** [ElemeFE/element#14051]
### Element UI version
2.4.8

### OS/Browsers version
ALL

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/10uo4ws3/](https://jsfiddle.net/10uo4ws3/)

### Steps to reproduce
Wrap el-tab-pane elements in a div and they will not be created.

I realise that this is not semantically good markup, but the wrapping div element is being added by our CMS, and is out of our control.
This behavior was introduced in this PR, https://github.com/ElemeFE/element/pull/12846, and this issue was noted as a known side effect.

### What is Expected?
Behavior up until version 2.4.7 would result in the tabs and tab panels being displayed.

### What is actually happening?
From version 2.4.8 onwards tabs and tab panels are NOT displayed.

**Comment by ziyoung** [comment]
@jasperdavis yes. Don't use div to wrap TabPane. But you can use `template` https://jsfiddle.net/jh6dqza2/
