### ISSUE TITLE
[Bug Report] Validations within el-table-column

### ISSUE THREAD

**Issue by PanimalarVadivel** [ElemeFE/element#14058]
### Element UI version
2.4.11

### OS/Browsers version
MacOS Sierra Version 10.12.4/Chrome Version 71.0.3578.98 

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/kadcqr82/](https://jsfiddle.net/kadcqr82/)

### Steps to reproduce
I have something like this

`<el-table-column label="Serial#" width="100"> <template slot-scope="scope"> <el-input v-model="scope.row.serialNumber" size="small"></el-input> </template> </el-table-column>`

Is there a way I could run validation on this el-input field within my table?

I tried using a method like the below, but that could only throw alerts. How can it highlight the field in red and display the error message like a normal el-input field?

@change="validateRequired(items, scope.$index, 'serialNumber')

### What is Expected?
How does validation happen within the input field of the table?

### What is actually happening?
Not sure how the validations work from within the table element. 

If I add 

`<el-table-column label="Serial#" width="100"> 
<template slot-scope="scope"> 
<el-form-item prop="serialNumber" required>
<el-input v-model="scope.row.serialNumber" size="small"></el-input> 
</el-form-item>
</template>
 </el-table-column>` 

The validation errors are thrown even if there is right data in there.

**Comment by xuliangzhan** [comment]
可以参考 [https://github.com/xuliangzhan/vue-element-extends](https://github.com/xuliangzhan/vue-element-extends)

**Comment by ziyoung** [comment]
You also need to use ElForm to wrap Table. A better solution is to create your own component using [async-validator](https://www.npmjs.com/package/async-validator)
