### ISSUE TITLE
[Bug Report] Button Style Error Triggering the $comfirm Method

### ISSUE THREAD

**Issue by GithubCin** [ElemeFE/element#14054]
### Element UI version
2.4.11

### OS/Browsers version
CHROME

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/2kua6s3j/](https://jsfiddle.net/2kua6s3j/)

### Steps to reproduce
点击触发comfirm的按钮后 确认或取消之后 原本的按钮被force focus了 导致div位置就不对的 但整个dom和样式都是没有变化的

### What is Expected?
按钮恢复原状

### What is actually happening?
按钮错位了

**Comment by xuejiangjun** [comment]
感觉是button的active导致的。你只有把el-button换成其他元素咯
![a](https://user-images.githubusercontent.com/16046545/51026908-8fb39980-15ca-11e9-940c-ea5d3d1b2f70.gif)
