### ISSUE TITLE
[Bug Report] The main website is broken - http://element.eleme.io/#/en-US

### ISSUE THREAD

**Issue by marcolarosa** [ElemeFE/element#14065]
### Element UI version
2.4.11

### OS/Browsers version
MacOS / firefox 64.0.2

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
Try to load the website - doesn't work in either firefox or chrome.

### What is Expected?
It loads.

### What is actually happening?
It doesn't load.

<img width="511" alt="screen shot 2019-01-14 at 11 36 06 am" src="https://user-images.githubusercontent.com/2639995/51092895-0af69480-17f1-11e9-85b7-fcb6ec4c81ed.png">

**Comment by xuejiangjun** [comment]
http://element-cn.eleme.io/#/en-US

**Comment by marcolarosa** [comment]
All resolved
