### ISSUE TITLE
[Bug Report] table组件column内容过长时使用:show-overflow-tooltip="true"  内容显示不出来且页面右侧出现持续抖动

### ISSUE THREAD

**Issue by mashuangwei** [ElemeFE/element#14064]
### Element UI version
2.4.11

### OS/Browsers version
win10 chrome71

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/yf15usn0/](https://jsfiddle.net/yf15usn0/)

### Steps to reproduce
1、引入table组件
2、column属性使用:show-overflow-tooltip="true"，即 <el-table-column :show-overflow-tooltip="true" prop="key" label="KEY"/>
3、当content内容比较长时大概有几千个字符或者上万，tooltip显示的内容会有部分被遮挡，包括横向左右两边。另外一个问题，比如table有二十行，鼠标移动第19行触发tooltip，此时页面右侧一直抖动，滚动掉若隐若现，如果鼠标移动到table前几行不会有抖动问题。 和重现连接显示的情况类似。

### What is Expected?
tooltip显示的内容完整不会被遮挡，内容过长时有滚动条

### What is actually happening?
问题一：完全不显示
问题二：一行内容左边和右边内容都有被遮挡
问题三：页面右侧滚动条若隐若现，鼠标不移开的话页面一直抖动

**Comment by xuqingxi** [comment]
你可以主动设置tooltip的样式来进行调整
![image](https://user-images.githubusercontent.com/38125259/51171911-0c0cec00-18ed-11e9-9d4e-0eedd11862a0.png)
不过table下hover状态下无法滑动滚动条，应该有其他解决办法，暂时没想到

**Comment by ziyoung** [comment]
或者使用 table 的展开行http://element-cn.eleme.io/#/zhan-kai-xing

**Comment by shaqueoneal** [comment]
问题没解决，为什么关闭了？不是长短问题，是一直在闪啊

**Comment by shaqueoneal** [comment]
@ziyoung

**Comment by Amosyue** [comment]
这个问题在tooltip内容过多的时候会出现，就算你设置了tooltip 的 max-height会出现滚动条，但是移出后tooltip 就会消失，滚动条下边的内容你是看不到的，

**Comment by raind33** [comment]
这个问题还没解决么

**Comment by HankBass** [comment]
所以这个问题官方没有回复又关闭了是打算不处理了吗？

**Comment by HankBass** [comment]
@ziyoung

**Comment by SoberK** [comment]
最简单的方法：
.el-tooltip__popper{
    margin-left: 20px;
}

**Comment by 1029800858** [comment]
最简单的方法：
.el-tooltip__popper{
margin-left: 20px;
}这种方式没有用，请问现在解决了吗？ 表格中设置这个然后滚动的时候页面就会抖动

**Comment by qq95137** [comment]
这个问题现在还没有解决吗

**Comment by JackSengKing** [comment]
我使用 Popover 弹出框 解决了这个问题，在table中默认的 show-overflow-tooltip 如果tips中字数太多会导致右侧抖动，而使用Popover+滚动条就可以解决这个问题：
![image](https://user-images.githubusercontent.com/29450408/109091799-66c1d480-7750-11eb-9698-415d37ba9e81.png)
 查看效果：

![image](https://user-images.githubusercontent.com/29450408/109092177-0aab8000-7751-11eb-8aa2-188b95047aae.png)

**Comment by Ayana7** [comment]
同样遇到

**Comment by PandyYang** [comment]
没有好的解决方案吗？

**Comment by wiidede** [comment]
我也在列的slot中使用了el-tooltip，然后给popper加了`overflow-y: auto`。

特点就是：
1. 可以判断是否溢出，溢出了才可以显示tooltip
2. 然后还有判断tooltip内容是否溢出，溢出了才可以鼠标进入
3. 禁用了arrow，加了overflow后，样式不对了，感觉有点难箭头样式，就先禁用

如果还要细致一点，可以改一下表格列的样式，让自定义的内容充满整个单元格，这个就和原来表格一样可以在整个单元格的基础上hover。

这是我写的[例子](https://stackblitz.com/edit/vue2-vite-starter-qq72bu?file=src/components/OverflowTooltip.vue)（打开安装element依赖要点时间的哦）

顺便把之前的[博客](https://wiidede.github.io/vue-auto-show-tooltip/)更新一下🤪

**Comment by godmiracle** [comment]
> 博客

抄了用不错，但是小箭头怎么没得了。

**Comment by meitingshuoguo** [comment]
> 我也在列的slot中使用了el-tooltip，然后给popper加了`overflow-y: auto`。
> 
> 特点就是：
> 
> 1. 可以判断是否溢出，溢出了才可以显示tooltip
> 2. 然后还有判断tooltip内容是否溢出，溢出了才可以鼠标进入
> 3. 禁用了arrow，加了overflow后，样式不对了，感觉有点难箭头样式，就先禁用
> 
> 如果还要细致一点，可以改一下表格列的样式，让自定义的内容充满整个单元格，这个就和原来表格一样可以在整个单元格的基础上hover。
> 
> 这是我写的[例子](https://stackblitz.com/edit/vue2-vite-starter-qq72bu?file=src/components/OverflowTooltip.vue)（打开安装element依赖要点时间的哦）
> 
> 顺便把之前的[博客](https://wiidede.github.io/vue-auto-show-tooltip/)更新一下🤪
> 
> ![图片](https://user-images.githubusercontent.com/25472916/176990057-add3ee95-e1c8-4777-96e9-ef7d37041da4.png) ![图片](https://user-images.githubusercontent.com/25472916/176990067-2303ab04-a4d4-4aa8-b079-4a18bc142b04.png)

感谢，我拿来用啦🤪
