### ISSUE TITLE
[Bug Report] placeholder in InputNumber doesn't work when in form has a v-model

### ISSUE THREAD

**Issue by L-x-C** [ElemeFE/element#14068]
### Element UI version
2.4.11

### OS/Browsers version
osx 10.14.2 

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/lxc11235/3gwfp4Lt/](https://jsfiddle.net/lxc11235/3gwfp4Lt/)

### Steps to reproduce
open link

### What is Expected?
when it have a v-model，it should be nothing when initialized

### What is actually happening?
it's 0

**Comment by ziyoung** [comment]
It's intended.
```js
Number('') // 0
```

**Comment by ziyoung** [comment]
A workaround https://jsfiddle.net/y0jwopzf/
