### ISSUE TITLE
[Bug Report] Textarea has shadow on iOS Safari

### ISSUE THREAD

**Issue by ingria** [ElemeFE/element#14062]
### Element UI version
2.4.11

### OS/Browsers version
iOS 12, Safari

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/d84L0vqn/](https://jsfiddle.net/d84L0vqn/)

### Steps to reproduce
Open textarea in safari.

### What is Expected?
![2019-01-12 17-24-56](https://user-images.githubusercontent.com/2178368/51074333-116cfb00-168f-11e9-99d8-5f170e29d594.png)

### What is actually happening?
![photo5319274510735747798](https://user-images.githubusercontent.com/2178368/51074322-e682a700-168e-11e9-9fe1-510587358c84.jpg)

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.

Pr welcome.
