### ISSUE TITLE
[Bug Report] How to - validation on input field within el-table-column 

### ISSUE THREAD

**Issue by PanimalarVadivel** [ElemeFE/element#14061]
### Element UI version
2.4.11

### OS/Browsers version
MacOs Sierra 10.12.4

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/8329p946/](https://jsfiddle.net/8329p946/)

### Steps to reproduce
The same code as https://jsfiddle.net/8329p946/. How do I do the validation of the editable field 'Name' in the table please? 

### What is Expected?
Successful validation on the editable field of the table. 
The validation errors should appear below the input-field, like a regular input field validation would work. The box should turn with red borders in case of errors, and with green borders if the data is valid

### What is actually happening?
No validations possible that would highlight the errors like a normal input-field would work

**Comment by ziyoung** [comment]
Duplicate of #14058
