### ISSUE TITLE
[Bug Report] Dropdown pop-up list is too long to display

### ISSUE THREAD

**Issue by DougFlands** [ElemeFE/element#14069]
### Element UI version
0.1.0

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/vayprkh3/](https://jsfiddle.net/vayprkh3/)

### Steps to reproduce
<el-dropdown-item>项目过多

### What is Expected?
使用滚动条显示更多的项目。
虽然添加CSS能解决，但希望官方能在项目中修复。

### What is actually happening?
多出的项目不显示

**Comment by ziyoung** [comment]
自己加一个 overflow 类吧。不过这样做会让小箭头消失。

**Comment by DougFlands** [comment]
> 自己加一个 overflow 类吧。不过这样做会让小箭头消失。

哪里有个小箭头？
