### ISSUE TITLE
[Bug Report] Use more than one Manual upload functions in single page

### ISSUE THREAD

**Issue by bryanwsh** [ElemeFE/element#14078]
### Element UI version
2.4.11

### OS/Browsers version
windows10 Chrome 71.0.3578.98

### Vue version
2.5.22

### Reproduction Link
[https://github.com/bryanwsh/forelement](https://github.com/bryanwsh/forelement)

### Steps to reproduce
When using more than one Manual upload functions in one page，the upload function does't work properly. 
在同一个页面使用多个手动上传的组件，上传失效，文件无法上传

### What is Expected?
the upload function could work properly

手动上传组件分别生效

### What is actually happening?
can not upload
上传失效，文件无法上传

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
