### ISSUE TITLE
[Bug Report] Table-column Attributes show-overflow-tooltip Display effect bug

### ISSUE THREAD

**Issue by quqiangsheng** [ElemeFE/element#14071]
### Element UI version
2.4.11

### OS/Browsers version
windows10 chrome71.0.3578

### Vue version
2.5.22

### Reproduction Link
[https://panjiachen.github.io/vue-element-admin/#/table/complex-table](https://panjiachen.github.io/vue-element-admin/#/table/complex-table)

### Steps to reproduce
After the show-overflow-tooltip property is opened in some columns with too many words in the table, the text on the left edge of the screen is not fully displayed in the hover prompt window after the full line is filled. It may be that the code has a problem in calculating the distance from the border

### What is Expected?
The text is fully displayed and not truncated

### What is actually happening?
Text to the left of the screen is truncated and incomplete

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
