### ISSUE TITLE
[Feature Request] Moving items in el-transfer with double clicks

### ISSUE THREAD

**Issue by maiolica** [ElemeFE/element#14086]
### Existing Component
Yes

### Component Name
el-transfer

### Description
Would it be possible to move items from one column to the other using a double click as shortcut?

Thanks

**Comment by island205** [comment]
pr welcome

**Comment by ehsanbagherzadegan** [comment]
hi sorry i have quastion im new in vuejs i try fill data using axios from laravel backend but i cant do it if u have sample whit backend data pls send me my code is 
<el-form-item>
                <el-transfer
                  filterable
                  :filter-method="filterMethod"
                  filter-placeholder="State Abbreviations"
                  v-model="value2"
                  :titles="['کلیه سطوح دسترسی','اختصاص یافته']"
                  :props="{
                      key:'name',
                      label: 'description',
                      initial:'name'
                    }"
                  :data="data2">
                </el-transfer>
</el-form-item>    
  export default {
    data(){ 
      return{
            warningAlert : trans('app.warningAlert'),
            failedAlert : trans('app.failedAlert'),
            cancelAlert : trans('app.cancelAlert'),
            noticTxt : trans('app.noticTxt'),
            cancelButtonText : trans('app.cancelButtonText'),
            confirmButtonText : trans('app.confirmButtonText'),
            form: 
            {
              name: '',
              description: '',
              permissions: '',
            },            
            permission_options:[],
            data2: generateData2(),
            value2: [],
            filterMethod(query, item) {
              return item.initial.toLowerCase().indexOf(query.toLowerCase()) > -1;
            }
          };
    },
and loading method is 
loadUserPermission(){
          axios.get("../api/auth/permissions").then(({data})=>(this.permission_options = data.data)).catch(()=>{
            this.$message({
              title: '',
              message: error.respons.data.errors,
              center: true,
              type: 'error'
            });                
          });
