### ISSUE TITLE
[Feature Request] I suggest that the value of Tabs has "sync" feature.

### ISSUE THREAD

**Issue by KuoKongQingYun** [ElemeFE/element#14089]
### Existing Component
是

### Component Name
Tabs

### Description
I suggest that the value of Tabs has "sync" feature like "current-page“ of Pagination.
It will be convenient to watch the current tab.

**Comment by c5ms** [comment]
I agree.
Such as onSortChange can modify to sort.sync.

**Comment by ziyoung** [comment]
Right now value supports `v-model` and we have no plan to support this.
