### ISSUE TITLE
[Bug Report] Dropdown button not properly generated on ButtonGroup

### ISSUE THREAD

**Issue by gabrielboliveira** [ElemeFE/element#14087]
### Element UI version
2.4.11

### OS/Browsers version
macOS Mojave 10.14.2 / Chrome 71

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/jnzvx09w/](https://jsfiddle.net/jnzvx09w/)

### Steps to reproduce
This is related to #12815 and #11963. When you add a `el-dropdown` with a `el-button` inside a `el-button-group`, it's not properly generated. 

### What is Expected?
`el-button` with `dropdown` to be properly generated inside a `el-button-group`

### What is actually happening?
Order is not respected, and also UI doesn't look good
![image](https://user-images.githubusercontent.com/11093090/51195589-867d4200-18d4-11e9-9e5e-acde8cf8a69d.png)

**Comment by iamkun** [comment]
workaround: 
```
.el-dropdown {
    float: left;
}
.el-button-group>.el-dropdown>.el-button {
    border-radius: 0;
}
```
