### ISSUE TITLE
Does [Feature Request] el-table multilevel header have a way to fix the first few columns?

### ISSUE THREAD

**Issue by bufudanqing** [ElemeFE/element#14090]
### Existing Component
是

### Component Name
el-table

### Description
超长的表格，表头是多级的，想要固定前几列，试过在父级el-table-column加fixed，未到达预期，在子级的el-table-column加fixed,也不行，数据渲染异常了，想要固定如图的几列
****
![image](https://user-images.githubusercontent.com/11040182/51221831-158e6680-1976-11e9-9ff0-44552b1099cf.png)

**Comment by island205** [comment]
This is a issue, please provide a valid reproduction link or this issue will be closed directly.
