### ISSUE TITLE
[Feature Request] vue-starter conform elementui

### ISSUE THREAD

**Issue by phoenixtk** [ElemeFE/element#14092]
### Existing Component
否

### Component Name
vue-starter conform elementui

### Description
vue-starter conform elementui ,  isomorphic errors

https://github.com/phoenixtk/vue-starter.git

**Comment by phoenixtk** [comment]
![image](https://user-images.githubusercontent.com/20085025/51223425-acf6b800-197c-11e9-8226-74c2bb304b76.png)
url or f5 errors

**Comment by phoenixtk** [comment]
![image](https://user-images.githubusercontent.com/20085025/51223470-d879a280-197c-11e9-811b-c00ed45b2fa1.png)
url request or f5 errors

**Comment by phoenixtk** [comment]
![image](https://user-images.githubusercontent.com/20085025/51223521-0828aa80-197d-11e9-8304-e6f1b0aed301.png)
router from here

**Comment by phoenixtk** [comment]
![image](https://user-images.githubusercontent.com/20085025/51223768-322e9c80-197e-11e9-913c-eb585a9a5ec0.png)
errors

**Comment by island205** [comment]
- 这个是 issue，不是 feature request
- 看上去不是 element ui 的问题，可能是 webpack loader 配置问题，也可能是其他的，看错误是把 css 当作 js 来解析了
- 可以到 vue-starter 那边去提问题
