### ISSUE TITLE
[Bug Report] <el-transfer> set no-match-text no-data-text does't work

### ISSUE THREAD

**Issue by roseforyou** [ElemeFE/element#14098]
### Element UI version
2.4.11

### OS/Browsers version
window 7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/5gtbuz9k/](https://jsfiddle.net/5gtbuz9k/)

### Steps to reproduce
https://jsfiddle.net/5gtbuz9k/
<el-transfer filterable :filter-method="filterMethod" filter-placeholder="请输入城市拼音" v-model="value2" :data="data2" no-match-text="nomatch" no-data-text="nodata">
  </el-transfer>
set no-match-text  no-data-text doesn't work, 
or set other attrs?
please check it .

### What is Expected?
`<el-transfer> set no-match-text  no-data-text like <el-select>`

### What is actually happening?
when set no-match-text and no-data-text will show default text.

**Comment by ehsanbagherzadegan** [comment]
hi sorry i have quastion im new in vuejs i try fill data using axios from laravel backend but i cant do it if u have sample whit backend data pls send me my code is 
<el-form-item>
                <el-transfer
                  filterable
                  :filter-method="filterMethod"
                  filter-placeholder="State Abbreviations"
                  v-model="value2"
                  :titles="['کلیه سطوح دسترسی','اختصاص یافته']"
                  :props="{
                      key:'name',
                      label: 'description',
                      initial:'name'
                    }"
                  :data="data2">
                </el-transfer>
</el-form-item>    
  export default {
    data(){ 
      return{
            warningAlert : trans('app.warningAlert'),
            failedAlert : trans('app.failedAlert'),
            cancelAlert : trans('app.cancelAlert'),
            noticTxt : trans('app.noticTxt'),
            cancelButtonText : trans('app.cancelButtonText'),
            confirmButtonText : trans('app.confirmButtonText'),
            form: 
            {
              name: '',
              description: '',
              permissions: '',
            },            
            permission_options:[],
            data2: generateData2(),
            value2: [],
            filterMethod(query, item) {
              return item.initial.toLowerCase().indexOf(query.toLowerCase()) > -1;
            }
          };
    },
and loading method is 
loadUserPermission(){
          axios.get("../api/auth/permissions").then(({data})=>(this.permission_options = data.data)).catch(()=>{
            this.$message({
              title: '',
              message: error.respons.data.errors,
              center: true,
              type: 'error'
            });                
          });
