### ISSUE TITLE
[Bug Report] Folding Menu

### ISSUE THREAD

**Issue by RabbDream** [ElemeFE/element#14108]
### Element UI version
2.4.11

### OS/Browsers version
win10/chrome最新版

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.现在菜单组件为可折叠
2.快速点击展开、折叠按钮

### What is Expected?
菜单正在展开时不能进行折叠操作，正在折叠时不能进行展开操作，快速点击不能让菜单宽度突变

### What is actually happening?
菜单正在展开可以折叠，正在折叠可以展开，导致菜单内容消失，快速点击两个按钮时，没有宽度渐变的过程，会直接突变

**Comment by csvwolf** [comment]
Hi, the issue needs Reproduction Link, so we temporarily close it. Add the link if you still want it.
