### ISSUE TITLE
NavMenu导航菜单(default-active当前激活菜单index的问题）

### ISSUE THREAD

**Issue by xiaoyin199** [ElemeFE/element#14100]
1、使用url路径作为index值，来触发导航菜单的选中，即default-active功能
2、通过修改url的路径，左侧导航菜单也会跟着变化，这里是没毛病的
3、假如修改的url路径，是菜单渲染里面没有的index，这个时候左侧导航的选中状态就不变了。理论上如果找不到匹配的，当菜菜单因该是不选中状态呀！

请帮忙解释，或解决 这个问题！感谢！！！

**Comment by drinkingcode** [comment]
> 1、使用url路径作为index值，来触发导航菜单的选中，即default-active功能
> 2、通过修改url的路径，左侧导航菜单也会跟着变化，这里是没毛病的
> 3、假如修改的url路径，是菜单渲染里面没有的index，这个时候左侧导航的选中状态就不变了。理论上如果找不到匹配的，当菜菜单因该是不选中状态呀！
> 
> 请帮忙解释，或解决 这个问题！感谢！！！

我也遇到这个小问题，你解决的思路是啥？

**Comment by drinkingcode** [comment]
我也遇到这个小问题，你解决的思路是啥？
