### ISSUE TITLE
[Bug Report] datePicker component shows wrong date when type is week, format is yyyy-MM-dd

### ISSUE THREAD

**Issue by IChocolateKapa** [ElemeFE/element#14103]
### Element UI version
2.4.9

### OS/Browsers version
Mac OS / 版本 71.0.3578.98（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/f8s46Led/](https://jsfiddle.net/f8s46Led/)

### Steps to reproduce
1.choose date 2018-12-31
2,it just shows 2019-01-03

### What is Expected?
2018-12-31

### What is actually happening?
2019-01-03

**Comment by wacky6** [comment]
This is not a bug, see ISO8601 week date.
