### ISSUE TITLE
点击 timePicker 的清空按钮，其绑定的 data 没有跟随清空

### ISSUE THREAD

**Issue by Visonnn** [ElemeFE/element#1411]
### ElementUI version
1.0.2

### OS/Browers version
Windows 10 / Chrome 56.0.2924.3 dev (64-bit)

### Vue version
2.0.8

### Reproduction Link
https://jsfiddle.net/wxkuang/5Lt1a4sg/5/

### Steps to reproduce
1. 用 JS 给两个 timePicker 绑定的变量赋值
2. 各自点击 timePicker 右侧的 X 清空数据

### What is Expected?
点击 X 清空按钮时，其绑定的数据也被清空

### What is actually happening?
在 devtools 中可以发现绑定的变量没有被清空

**Comment by reverland** [comment]
然而。。。我这里清空了
![screenshot from 2016-11-28 14-41-30](https://cloud.githubusercontent.com/assets/1418726/20672337/dea84d9c-b578-11e6-8422-2ce418a34a64.png)

iceweasel 43.0.4 on debian

**Comment by reverland** [comment]
哦。。好像因为v-model绑定数组成员

**Comment by Visonnn** [comment]
![image](https://cloud.githubusercontent.com/assets/4200907/20673557/7fcec5ce-b5c0-11e6-84c7-ccd9f053f74a.png)

这就尴尬了，今天尝试了三台电脑，都是 Chrome，均能复现，才跑上来提 issue。

您用 iceweasel 可能无法复现。 @reverland

**Comment by reverland** [comment]
@Visonnn 额，我看到了，我随便选择了后绑定就正常了。

看了看，感觉Picker.vue在handleClear时候是不是应该emit('input', null)什么的。

明天有空看看，觉得日期时间范围选择器可能也有类似问题？@kingwl。虽然我们还是1.0.0.。。。

**Comment by baiyaaaaa** [comment]
#1466
