### ISSUE TITLE
[Bug Report] with vue-i18n@6.x internationalization

### ISSUE THREAD

**Issue by hqzh** [ElemeFE/element#14115]
### Element UI version
2.4.11

### OS/Browsers version
Windows  Chrome70

### Vue version
2.5.22

### Reproduction Link
我这里jsfiddle梯子不稳,

### Steps to reproduce
按照官网的配置后,其它的elem组件都能随着this.$i18n.locale的变化生效,就是默认的placeholder不会动态的变更改了变量后而生效,但是在
const i18n = new VueI18n({
  locale: 'cn',    
  messages
})
初始化的时候设置是生效的,

I set config as document in official website , this.$i18n.locale can work , but default placeholder no effect when params change .  Only work when initial loading , 
const i18n = new VueI18n({
locale: 'cn',
messages
})  

When initial loading , this.$i18n.locale  set "cn" , it shows "请选择" , then let this.$i18n.locale = "en" , expect "请选择" translate to english such as "Select" , but it still show "请选择".This bug only occur in default placeholder text
### What is Expected?
change the default placeholder

### What is actually happening?
 No trigger 

![_20190116195608](https://user-images.githubusercontent.com/26128706/51247757-113f6900-19c9-11e9-8900-3e6a16c3fcc5.png)
![_20190117095044](https://user-images.githubusercontent.com/26128706/51290010-6f0d9880-1a3d-11e9-80e3-90de75a822f6.png)
![_20190117095052](https://user-images.githubusercontent.com/26128706/51290017-7634a680-1a3d-11e9-86eb-63230fd985c7.png)
![_20190117095547](https://user-images.githubusercontent.com/26128706/51290214-26a2aa80-1a3e-11e9-955f-ae66a103ccce.png)

**Comment by white112** [comment]
@hqzh Can you change issue description in English?
It will take some time to understand.
Thanks

**Comment by hqzh** [comment]
@white112 Very happy to receive your attention,I translated it.
