### ISSUE TITLE
[Bug Report] el-pagination component :when use the attr pager-count ,vue will give a warning

### ISSUE THREAD

**Issue by xuqingxi** [ElemeFE/element#14114]
### Element UI version
2.4.11

### OS/Browsers version
Google Chrome version 71.0.3578.98

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
just use the attr :pager-count='5' in el-pagination component

### What is Expected?
handle the warning

### What is actually happening?
it makes a warning in the console which is given by vue
![image](https://user-images.githubusercontent.com/38125259/51240550-e5b38300-19b6-11e9-8fff-af8fa6a883ca.png)

**Comment by ohhoney1** [comment]
is `page-count`，not `pager-count` @xuqingxi

**Comment by xuqingxi** [comment]
@ohhoney1 
![image](https://user-images.githubusercontent.com/38125259/51241461-d33a4900-19b8-11e9-9a3b-58a887d9eeb6.png)

**Comment by ohhoney1** [comment]
@xuqingxi sorry，我看错了。你仔细看下文档：`大于等于5且小于等于21的奇数`。3 是非法的

**Comment by xuqingxi** [comment]
@ohhoney1 没仔细看，因为3也能实现，谢谢了

**Comment by ShawshankLin** [comment]
> @ohhoney1 没仔细看，因为3也能实现，谢谢了

怎么去掉这个警告呢？

**Comment by ohhoney1** [comment]
> > @ohhoney1 没仔细看，因为3也能实现，谢谢了
> 
> 怎么去掉这个警告呢？
```
pagerCount: {
    type: Number,
    validator(value) {
      return (value | 0) === value && value > 4 && value < 22 && (value % 2) === 1;
    },
    default: 7
}
```
这是源码，传入3的话的，vue的props校验没通过，才会出现的警告

**Comment by ShawshankLin** [comment]
> > > @ohhoney1 没仔细看，因为3也能实现，谢谢了
> > 
> > 
> > 怎么去掉这个警告呢？
> 
> ```
> pagerCount: {
>     type: Number,
>     validator(value) {
>       return (value | 0) === value && value > 4 && value < 22 && (value % 2) === 1;
>     },
>     default: 7
> }
> ```
> 这是源码，传入3的话的，vue的props校验没通过，才会出现的警告

可以去掉这个限制或者这个警告吗，，设置这个的目的是？

**Comment by ohhoney1** [comment]
@ShawshankLin 你可以读下源码，很简单。尝试提个PR：允许3个分页按钮

**Comment by ShawshankLin** [comment]
> @ShawshankLin 你可以读下源码，很简单。尝试提个PR：允许3个分页按钮

Thanks
