### ISSUE TITLE
el-checkbox 和el-radio点击之后v-model值不会变化

### ISSUE THREAD

**Issue by loong-moon** [ElemeFE/element#1412]

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by loong-moon** [comment]
就是很正常的使用，其他地方都没问题，只有这两个组件不能双向绑定。
我尝试直接改data值页面也会有变化，但是点击组件，data中的值不会有变化
但是data值直接绑定input就是正常的
会不会是我把单页面应用改成多页面应用的原因？
![image](https://cloud.githubusercontent.com/assets/24216623/20657672/a3f37e0c-b572-11e6-8b9c-b8c4508bbd07.png)

<el-checkbox v-model="checked" >备选项</el-checkbox>{{checked}}
<input type="checkbox" v-model="rememberAccount">{{rememberAccount}}

checked:true,
rememberAccount:true,

**Comment by loong-moon** [comment]
![image](https://cloud.githubusercontent.com/assets/24216623/20657897/63c1b928-b574-11e6-8acb-0ec880f78815.png)

**Comment by loong-moon** [comment]
还有个情况是在IE和火狐上是可以点的  谷歌上不可以点

**Comment by loong-moon** [comment]
用法就是直接按照官网的写的，其他地方都没问题，只有这两个组件不能双向绑定。
我尝试直接改data值页面也会有变化，但是点击组件，data中的值不会有变化
但是data值直接绑定input就是正常的

<div>   <el-checkbox v-model="checked" >备选项</el-checkbox>{{checked}}   <input type="checkbox" v-model="rememberAccount">{{rememberAccount}}</div>

rememberAccount:true,checked:true,

还有个情况是在IE和火狐上是可以点的  谷歌上不可以点
2016-11-28 

15123339284 



发件人：杨奕 <notifications@github.com>
发送时间：2016-11-28 13:51
主题：Re: [ElemeFE/element] el-checkbox 和el-radio点击之后v-model值不会变化 (#1412)
收件人："ElemeFE/element"<element@noreply.github.com>
抄送："loong-moon"<15123339284@139.com>,"Author"<author@noreply.github.com>

请提供 demo

**Comment by reverland** [comment]
在data中声明了么

**Comment by loong-moon** [comment]
声明了 而且我用组件方式写（data方法返回值）和页面方式写（data值）都不行 
不过只是谷歌上的问题  IE和火狐都是正常的

2016-11-28 

15123339284 



发件人：Liu Yuyang <notifications@github.com>
发送时间：2016-11-28 14:51
主题：Re: [ElemeFE/element] el-checkbox 和el-radio点击之后v-model值不会变化 (#1412)
收件人："ElemeFE/element"<element@noreply.github.com>
抄送："loong-moon"<15123339284@139.com>,"Author"<author@noreply.github.com>

在data中声明了么

**Comment by loong-moon** [comment]
`<template>

    <el-form :model="userModel" label-width="120px" style="width: 75%;">
        <el-form-item label="姓名：" prop="userName">
            <el-input v-model="userModel.userName" placeholder="请输入姓名"></el-input>
        </el-form-item>
        <el-form-item label="性别：" prop="sex">
            <el-radio-group v-model="userModel.sex">
                <el-radio label="1">男</el-radio>
                <el-radio label="2">女</el-radio>
            </el-radio-group>
        </el-form-item>
        <el-form-item label="用户类型：" prop="userType">
            <el-radio-group v-model="userModel.userType">
                <el-radio label="1">个人</el-radio>
                <el-radio label="2">企业</el-radio>
            </el-radio-group>
        </el-form-item>
        <el-form-item label="手机号码：" prop="mobile">
            <el-input v-model="userModel.mobile" placeholder="请输入手机号码"></el-input>
        </el-form-item>
        <el-form-item label="邮箱：" prop="email">
            <el-input v-model="userModel.email" placeholder="请输入邮箱"></el-input>
        </el-form-item>
        <el-form-item label="电话：">
            <el-input v-model="userModel.telephone" placeholder="请输入电话"></el-input>
        </el-form-item>
        <el-form-item label="公司：">
            <el-input v-model="userModel.company" placeholder="请输入公司名称"></el-input>
        </el-form-item>
        <el-form-item label="行业：">
            <el-select v-model="userModel.industry" placeholder="请选择行业">
                <el-option label="互联网" value="1"></el-option>
                <el-option label="金融" value="2"></el-option>
            </el-select>
        </el-form-item>
        <el-form-item label="其他行业：">
            <el-select v-model="userModel.otherindustry" placeholder="请选择行业">
                <el-option label="互联网" value="1"></el-option>
                <el-option label="金融" value="2"></el-option>
            </el-select>
        </el-form-item>
        <el-form-item label="秘钥：">
            <el-input v-model="userModel.secretKey" placeholder="请输入秘钥"></el-input>
        </el-form-item>
        <el-form-item>
            <el-button class="btn-small" type="info" @click="edit">修改</el-button>
        </el-form-item>
    </el-form>

</template>
<style>

    label{font-weight: 400;}

</style>
<script>

    export default{
        data(){
            return{
                userModel: {
                    userId:'',
                    userName:'',
                    sex:'1',
                    userType:'1',
                    mobile: '',
                    email: '',
                    telephone: '',
                    company: '',
                    industry: '1',
                    otherindustry: '2',
                    secretKey:''
                }
            }
        },
        methods:{
            edit:function () {

            }
        }
    }
</script>`
贴个完整的组件 也是里面的userModel.sex不能变化  但是在谷歌和IE上是可以变化的

**Comment by Leopoldthecoder** [comment]
上面这段代码是能正常工作的：http://jsfiddle.net/leopoldthecuber/8v13ajps/，需要看看是不是被其他地方影响到了。

**Comment by reverland** [comment]
在chrome那个vue调试工具里看看，检查下是不是哪里对usermodel做了奇怪的事情。。

**Comment by loong-moon** [comment]
发现只在开发环境中有问题   部署到iis中就可以正常  
到现在都不知道是什么原因造成的 node？webpack？gulp？

2016-11-30 

15123339284 



发件人：Liu Yuyang <notifications@github.com>
发送时间：2016-11-28 22:30
主题：Re: [ElemeFE/element] el-checkbox 和el-radio点击之后v-model值不会变化 (#1412)
收件人："ElemeFE/element"<element@noreply.github.com>
抄送："loong-moon"<15123339284@139.com>,"Author"<author@noreply.github.com>

在chrome那个vue调试工具里看看，检查下是不是哪里对usermodel做了奇怪的事情。。

**Comment by beinecke** [comment]
我也曾经遇到类似的问题，后来发现是开发环境的broswer-sync影响了chrome，当时不只element-ui有这个问题，Ant Design也有同样的问题。如果你也用了broswer-sync，可以换掉试试

**Comment by baiyaaaaa** [comment]
今天会发新版本，对checkbox-group和radio-group的一些修正。可以用新版试试

**Comment by loong-moon** [comment]
我用了新版本，el-checkbox已经正常了，但是el-radio还是有问题，请问你是element团队的么 如果是的话，期待能解决剩下的问题

2016-12-05 

15123339284 



发件人：baiyaaaaa <notifications@github.com>
发送时间：2016-12-02 12:37
主题：Re: [ElemeFE/element] el-checkbox 和el-radio点击之后v-model值不会变化 (#1412)
收件人："ElemeFE/element"<element@noreply.github.com>
抄送："loong-moon"<15123339284@139.com>,"Author"<author@noreply.github.com>

今天会发新版本，对checkbox-group和radio-group的一些修正。可以用新版试试

**Comment by loong-moon** [comment]
请问用什么换掉比较好

2016-12-07 

15123339284 



发件人：beinecke <notifications@github.com>
发送时间：2016-12-01 14:27
主题：Re: [ElemeFE/element] el-checkbox 和el-radio点击之后v-model值不会变化 (#1412)
收件人："ElemeFE/element"<element@noreply.github.com>
抄送："loong-moon"<15123339284@139.com>,"Author"<author@noreply.github.com>

我也曾经遇到类似的问题，后来发现是开发环境的broswer-sync影响了chrome，当时不只element-ui有这个问题，Ant Design也有同样的问题。如果你也用了broswer-sync，可以换掉试试

**Comment by AtticusLv** [comment]
请问这个问题解决了吗？我在chrome浏览器下，webpack-dev-server，使用el-radio，双向绑定v-model出现同样的问题
