### ISSUE TITLE
[Bug Report] in Slider, if the value of max is too large(like 10000000), the browser will crash

### ISSUE THREAD

**Issue by KarthusLorin** [ElemeFE/element#14132]
### Element UI version
2.4.11

### OS/Browsers version
osx/chrome 71

### Vue version
2.6.0-beta.1

### Reproduction Link
[https://jsfiddle.net/KarthusLorin/25uwnk6c/4/](https://jsfiddle.net/KarthusLorin/25uwnk6c/4/)

### Steps to reproduce
change the value of max to 10000000

### What is Expected?
the browser can run

### What is actually happening?
in Slider, if the value of max is too large(like 10000000), the browser will crash

**Comment by KarthusLorin** [comment]
i have pull request [#14133](https://github.com/ElemeFE/element/pull/14133) to fix this bug

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
