### ISSUE TITLE
Dialog 组件自定义样式

### ISSUE THREAD

**Issue by chs97** [ElemeFE/element#1413]
Dialog 怎么取消 body的 padding  自定义class 好像不起作用  还有怎么取消宽度自适应。我页面有一个 min-width

**Comment by Leopoldthecoder** [comment]
「取消 body的 padding」可以用 `lock-scroll` 属性，赋值为 `false` 即可。「取消宽度自适应」覆盖 CSS 即可。

**Comment by chs97** [comment]
啊 我说的是 el-dialog__body 。。

**Comment by Leopoldthecoder** [comment]
参考 http://jsfiddle.net/leopoldthecuber/mw8m9631/

**Comment by chs97** [comment]
OK 谢了。。我在机子上没效果，，代码在jsfiddle上有效果。可能哪里出问题了。。我自己检查一下。
