### ISSUE TITLE
[Bug Report] uses textarea to report exceptions when entering

### ISSUE THREAD

**Issue by shaonianzhentan** [ElemeFE/element#14138]
### Element UI version
2.4.11

### OS/Browsers version
Windows10/Chrome版本71.0.3578.98（正式版本） （64 位）

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/cp5bvrf2/9/](https://jsfiddle.net/cp5bvrf2/9/)

### Steps to reproduce
打开官网使用2.4.11的版本
http://element-cn.eleme.io/#/zh-CN/component/input
在文本域里输入文字，代码会报错

### What is Expected?
不报错

### What is actually happening?
vue.runtime.min.js:6 TypeError: Cannot set property 'value' of undefined

![image](https://user-images.githubusercontent.com/5294022/51362572-2cb48c00-1b0f-11e9-8152-78b34666c5ce.png)
![image](https://user-images.githubusercontent.com/5294022/51362587-3a6a1180-1b0f-11e9-8f6f-0a556fa8eb7a.png)

**Comment by island205** [comment]
fixed in #14143
