### ISSUE TITLE
[Bug Report] Table column disorder

### ISSUE THREAD

**Issue by howiefh** [ElemeFE/element#14150]
### Element UI version
2.4.11

### OS/Browsers version
windows/71.0.3578.98 64位

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/jyLcmgxe/](https://jsfiddle.net/jyLcmgxe/)

### Steps to reproduce
对 el-table, el-table-column 进行了封装， el-table 引入外部封装的el-table-column 时，列顺序会错乱，如链接https://jsfiddle.net/jyLcmgxe/ 一级标题对应的第一列（id）和二级标题对应的第一列（date）都变为了最后一列。

### What is Expected?
希望表格展示时列顺序任何情况下都不会错乱

### What is actually happening?
表格展示时列顺序会错乱

**Comment by island205** [comment]
We will consider to provide columns prop to `el-table`
