### ISSUE TITLE
[Feature Request] Control dropdown visibility programmatically

### ISSUE THREAD

**Issue by DmitryLobachov** [ElemeFE/element#14152]
### Existing Component
Yes

### Component Name
Dropdown <el-dropdown>

### Description
Possibility to control dropdown visibility programmatically via model (or visibility prop). It's needed in cases when dropdown content is full screen (for example on mobile devices) and it's not possible to click outside to close it.

**Comment by nicooprat** [comment]
We can do this by calling the `.hide()` method, here's an example of closing a dropdown when changing route:

```vue
<template>
  <el-dropdown ref="menu">...</el-dropdown>
</template>

<script>
export default  {
  watch: {
    $route() {
      this.refs.menu.hide()
    }
  }
}
</script>
```

Agree that a more native way of doing it would be better though.
