### ISSUE TITLE
[Table] 是否可以提供 sort-change 与 filter-change 事件

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1415]
在复杂场景下，el-table是要和el-Pagination一起配合使用的，那么我们就需要自己处理排序和过滤。这种场景下table自身的排序和过滤就没有意义了。所以请考虑为el-table添加props用于禁用自己的排序和过滤逻辑，而只把排序和过滤条件通过事件传出，供使用者自己处理。

**Comment by Lee2011** [comment]
+1

**Comment by xierenyuan** [comment]
+1

**Comment by furybean** [comment]
@njleonzhang sort-change 事件应该一直可以用？

**Comment by njleonzhang** [comment]
@furybean 对于Sort来说，已经有解决方案了，就是sortable='custom'. 
对于filter-change，可以考虑添加类似的功能。

真正项目中table组件基本是和paganition一起用的，所以一定是要考虑这样的场景的。不分页的table是学生写demo玩的。。。。。

**Comment by furybean** [comment]
在计划中，与 #1230 重复了，请关注 1230 的进展。
