### ISSUE TITLE
[Feature Request] Single file upload, cannot be automatically replaced when repeated selection

### ISSUE THREAD

**Issue by zhaofy** [ElemeFE/element#14169]
### Existing Component
是

### Component Name
upload

### Description
手动上传，设置limit为1，选择一个文件，再选另一个文件，不能自动替换当前文件，目前是必须手动删除。
或者能否提供将文件加入上传队列 和 从队列中删除的方法？

**Comment by suguoyao** [comment]
同需要这个需求！
