### ISSUE TITLE
基础多选组件能否增加一个“全选”的功能？

### ISSUE THREAD

**Issue by zhuyunhe** [ElemeFE/element#1417]
点击“全部“，自动选择下拉多选框中的所有选项
![image](https://cloud.githubusercontent.com/assets/10432640/20658787/64af8f58-b57a-11e6-99cc-cd94c717323c.png)

**Comment by Leopoldthecoder** [comment]
这个应该不会加，可以自己在 `change` 事件回调中处理。比如判断如果当前选择了「全部」的值，就把绑定值赋值为所有选项组成的数组。
