### ISSUE TITLE
【求助】Menu的 index or route，嵌入thinkjs之后，无法实现router-view跳转

### ISSUE THREAD

**Issue by jiangchengshi2016** [ElemeFE/element#1418]
### ElementUI version
"element-ui": "^1.0.2"

### OS/Browers version
chrome

### Vue version
"vue": "^2.1.0",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.3",

### Reproduction Link
https://git.oschina.net/jiangchengshi/wedding.git

### Steps to reproduce
代码位于 front下面， admin相关：
菜单item设置了 :router="true"，单独vue-cli项目可以路由跳转到 router-view，但是整合项目之后，就没有任何反应，

**Comment by jiangchengshi2016** [comment]
没人解决吗？

**Comment by jiangchengshi2016** [comment]
我找到问题了。

**Comment by wushuang5112** [comment]
哥，你找到问题把它说出来呀！！！
