### ISSUE TITLE
Error in calculating function

### ISSUE THREAD

**Issue by qie12138** [ElemeFE/element#14189]
### Element UI version
2.4.11

### OS/Browsers version
Centos

### Vue version
2.6.0-beta.1

### Reproduction Link
[https://github.com/ElemeFE/element/blob/4b84b5946a2d44ffce3619d7d662ff8bd59435ba/packages/date-picker/src/util/index.js#L49](https://github.com/ElemeFE/element/blob/4b84b5946a2d44ffce3619d7d662ff8bd59435ba/packages/date-picker/src/util/index.js#L49)

### Steps to reproduce
master 分支的
/packages/date-picker/src/util/index.js#L49

export const getDayCountOfMonth = function(year, month) {
    if (month === 3 || month === 5 || month === 8 || month === 10) {
      return 30;
    }
  
    if (month === 1) {
      if (year % 4 === 0 && year % 100 !== 0 || year % 400 === 0) {
        return 29;
      } else {
        return 28;
      }
    }
  
    return 31;
  };
// 2月出现31日
console.log(getDayCountOfMonth(2018, 2))

### What is Expected?
2月28

### What is actually happening?
2月31

**Comment by luy19** [comment]
In js zero indicates the first month of the year.
