### ISSUE TITLE
[Bug Report] Bug el-input type=number，光标上移

### ISSUE THREAD

**Issue by miuqiang** [ElemeFE/element#14188]
### Element UI version
2.4.11

### OS/Browsers version
windows7 / 搜狗浏览器 7.5.5.25447

### Vue version
2.6.0-beta.1

### Reproduction Link
[https://jsfiddle.net/wLpmeycn/](https://jsfiddle.net/wLpmeycn/)

### Steps to reproduce
1、输入字符串即可重现

### What is Expected?
光标不上移

### What is actually happening?
光标上移

**Comment by ntnyq** [comment]
去掉 `.el-input__inner` 上的 `line-height` 属性

**Comment by ziyoung** [comment]
> 去掉 `.el-input__inner` 上的 `line-height` 属性

可行。
