### ISSUE TITLE
[Bug Report] Switch `inactive-value` can not set to empty string

### ISSUE THREAD

**Issue by ansonhorse** [ElemeFE/element#14186]
### Element UI version
2.4.11

### OS/Browsers version
macOS 10.14.2
Chrome 71.0.3578.98

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/1k0yLhm3/](https://jsfiddle.net/1k0yLhm3/)
```html
<template>
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui@2.4.11/lib/index.js"></script>
<div id="app">
<template>
  <el-switch
    v-model="value"
    :active-value="activeValue"
    :inactive-value="inactiveValue"
    @change="onChange"
    ></el-switch>
    <h1>current value: {{ value }}</h1>
</template>
</div>
</template>
<script>
var Main = {
    data() {
      return {
      	value: '',
      	activeValue: 'arrived',
        inactiveValue: ''
      }
    },
    methods: {
      onChange(v) {
      	console.log('current value:', v)
      }
    }
  };
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')
</script>
```

### Steps to reproduce
https://jsfiddle.net/1k0yLhm3/

### What is Expected?
`value` should be an empty string when is inactive, and should be `arrived` when is active.

### What is actually happening?
The value of `value` is `true` when is inactive.

**Comment by 1269879928** [comment]
nothing to do

**Comment by topoadmin** [comment]
'' replace null

**Comment by ansonhorse** [comment]
set `inactive-value` to `null` is fine
