### ISSUE TITLE
notification需要一个初始值

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#1419]
notification有时会挡住一些按钮 又感觉没办法hack的样子。。。

**Comment by Leopoldthecoder** [comment]
具体场景是？感觉按钮需要显示在 Notification 之上的情况不多

**Comment by reverland** [comment]
@Leopoldthecoder 实际是想定义距离视口上缘的距离，我们那里有个退出按钮。。。

**Comment by Leopoldthecoder** [comment]
@reverland 这个功能 @Kingwl 已经提了 PR 了。
