### ISSUE TITLE
[Bug Report] elementUI table component expand-change event, requesting data from server when expanding, view cannot be refreshed immediately

### ISSUE THREAD

**Issue by Even-Lau** [ElemeFE/element#14198]
### Element UI version
2.4.11

### OS/Browsers version
chrome 71.0.3578.98

### Vue version
2.6.0-beta.1

### Reproduction Link
[https://www.http://jsfiddle.net/](https://www.http://jsfiddle.net/)

### Steps to reproduce
该折叠table位于dialog里面，

### What is Expected?
视图立刻刷新

### What is actually happening?
视图无法立刻刷新，必须点击多次。或者点击下一个，上一个中的视图才会更新

**Comment by huangyujun** [comment]
我是这么解决的
在从接口获取了数据后，设置table的展开状态为 false， 再设置为 true 就解决了。
```
this.$refs.expandTable.toggleRowExpansion(_row, false);
this.$refs.expandTable.toggleRowExpansion(_row, true);
```
