### ISSUE TITLE
[Feature Request] Suport Wappalyzer

### ISSUE THREAD

**Issue by island205** [ElemeFE/element#14202]
### Existing Component
NO

### Component Name
GLOBAL

### Description
Export some global message for Wappalyzer detech.

**Comment by afc163** [comment]
https://www.wappalyzer.com/technologies/ant-design

**Comment by afc163** [comment]
可以参考 antd 的做法，直接探测 `ant-*` 的类名：https://github.com/AliasIO/Wappalyzer/pull/1928

**Comment by iamkun** [comment]
PR https://github.com/AliasIO/Wappalyzer/pull/2609

**Comment by island205** [comment]
反正听天由命了。
