### ISSUE TITLE
[Bug Report] 2.5.0 Release Error - ELEMENT.locale is not a function

### ISSUE THREAD

**Issue by JamesBrightley** [ElemeFE/element#14216]
### Element UI version
2.5.0

### OS/Browsers version
Windows 1- Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/6z7t5auj/](https://jsfiddle.net/6z7t5auj/)

### Steps to reproduce
when attempting to set the locale my CDN

<script src="//unpkg.com/vue"></script>
<script src="//unpkg.com/element-ui"></script>
<script src="//unpkg.com/element-ui/lib/umd/locale/en.js"></script>

<script>
  ELEMENT.locale(ELEMENT.lang.en)
</script>

### What is Expected?
Element works

### What is actually happening?
Script error causing other items to fail

**Comment by Kireeti-K** [comment]
I also face the same issue

**Comment by Jeffery-Young** [comment]
I use element-ui with wabpack. new version 2.5.0 cause a js error and block other scripts.
rollback to 2.4.11 is OK.
may 2.5.0 has some unknow bugs?
hope to fix it.

**Comment by kooohei** [comment]
ELEMENT.locale -> ELEMENT.default.locale

**Comment by island205** [comment]
fixing

**Comment by iamkun** [comment]
fixed in 2.5.1
