### ISSUE TITLE
[BUG] windows 下 el-table 组件在调整 chrome 浏览器宽度至出现右侧滚动条的临界点时，bodyWidth 无限计算导致表格产生滚动

### ISSUE THREAD

**Issue by Nicksapp** [ElemeFE/element#14213]
![](https://haitao.nos.netease.com/6cfc8293-61ff-4b85-8d5a-cb2a9cc58056_1160_190.jpg)

[BUG] windows 下 el-table 组件在调整 chrome 浏览器宽度至出现右侧滚动条的临界点时，bodyWidth 无限计算导致表格产生滚动

**Comment by MEEllis** [comment]
> ![](https://camo.githubusercontent.com/7b700f8b4223d3982c616f52988480a002b939fa/68747470733a2f2f68616974616f2e6e6f732e6e6574656173652e636f6d2f36636663383239332d363166662d346238352d386435612d6362326139636335383035365f313136305f3139302e6a7067)
> 
> [BUG] windows 下 el-table 组件在调整 chrome 浏览器宽度至出现右侧滚动条的临界点时，bodyWidth 无限计算导致表格产生滚动

出现这种情况，是你table容器的样式存在问题。尝试一下把外容器的     overflow: hidden;
