### ISSUE TITLE
[Bug Report] DatePicker 日期选择器 在 value-formater="timestamp" 模式下返回的时间戳结果不正确

### ISSUE THREAD

**Issue by ShenQingchuan** [ElemeFE/element#14226]
### Element UI version
2.5.0

### OS/Browsers version
版本 71.0.3578.98（正式版本）Built on Ubuntu , running on Ubuntu 18.04 （64 位）

### Vue version
2.6.0-beta.2

### Reproduction Link
[https://jsfiddle.net/02gnzo8y/3/](https://jsfiddle.net/02gnzo8y/3/)

### Steps to reproduce
Step 1. 点击我的范例中的  DatePicker 日期选择器 组件

Step 2. 随便选择任何一个日期，然后会得到 时间戳的结果

Step 3. 去任何一个可以转换时间戳的转换器里 都会发现时间戳并不是我选择的那个日期：

例如：我选择了我的生日 1999年11月6日
           时间戳的返回结果是： 941817600000

然而 941817600000 => 31815-01-06 00:00:00
    但       941817600 => 1999-11-06 00:00:00

___________=> 综上所述：该组件在【时间戳结果显示模式】下的问题就是  多了 3个0 。

>> # 重要提示！  这个组件就是我从 官网文档  http://element.eleme.io/#/zh-CN/component/date-picker 上面 照抄复制过来的！
     这个时间戳的显示错误在官网文档的 组件显示范例  也同样出现了！

>> # 重要提示！  并不是说我只测试了 1999年11月6日，我反复测试了很多个日期，结果都显示返回的时间戳 真的多了 3个0

< 这个问题其实我觉得看上去不大... 但就是感觉这个错误也太坑了... 是不该犯的错误呀 23333>

### What is Expected?
期待返回正常的时间戳结果。

例如：我选择了我的生日 1999年11月6日
           时间戳的返回结果是： 941817600000

                然而 941817600000 => 31815-01-06 00:00:00
    但正确的应该是 941817600 => 1999-11-06 00:00:00

### What is actually happening?
例如：我选择了我的生日 1999年11月6日
           时间戳的返回结果是： 941817600000

然而 941817600000 => 31815-01-06 00:00:00  结果并不正确

**Comment by studentmain** [comment]
JS的时间戳是毫秒单位的。

```
root@us:~# node
> new Date(941817600000)
1999-11-05T16:00:00.000Z
>
```

**Comment by ooing** [comment]
那如何使用时间戳  并不需要那么精确（不需要毫秒）
