### ISSUE TITLE
[Feature Request] has just released version 2.5.0 without merging timeline components

### ISSUE THREAD

**Issue by talentant** [ElemeFE/element#14221]
### Existing Component
否

### Component Name
timeline

### Description
分支：https://github.com/ElemeFE/element/tree/next
PR：https://github.com/ElemeFE/element/pull/11736

**Comment by island205** [comment]
could you please submit an PR to dev branch?

**Comment by talentant** [comment]
Sorry, I noticed that branch `next` cannot automatically merge into `dev`, and I may not be able to handle these conflicts.

**Comment by island205** [comment]
ok, let me try.
