### ISSUE TITLE
[Bug Report] change event on el-input can't be triggered when value is changed

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#14225]
### Element UI version
2.5.0

### OS/Browsers version
win7

### Vue version
2.6.0-beta.2

### Reproduction Link
[https://jsfiddle.net/jonkee/6anL4o91/4/](https://jsfiddle.net/jonkee/6anL4o91/4/)

### Steps to reproduce
1. input something in the input field
2. nothing will happen
3. blur the input field 
4. `alert` then will be triggered

### What is Expected?
`alert` should immediately be triggered after the value is changed

### What is actually happening?
.

**Comment by wacky6** [comment]
Trigger on blur is the correct behavior. Use @input event if you want immediate trigger.

**Comment by HKskn** [comment]
@wacky6 I think it is not logical, it has already blur event

**Comment by wacky6** [comment]
If you think it is not logical, read the W3C HTML spec on input element’s change event.

**Comment by wacky6** [comment]
See https://html.spec.whatwg.org/multipage/indices.html#event-change . The key is "when the user **commits** a value change". It does not say *whenever the value changes*.

This is how native input element works. https://jsfiddle.net/m9dswx0y/ Element's `change` event merely wraps around the native change event.

FYI: for programatic change + user interaction, use vue's watch; In Element `input` event is emitted whenever the components want to update the underlying model's value.

If you still think this is not logical, feel free to fork and publish your own element-ui. Or convince W3C committee to fix the definition of change event.

:)

**Comment by HKskn** [comment]
Thanks for the detailed descriptions. I've already used vue's watch.
