### ISSUE TITLE
[Bug Report] Unexpected token export in nuxtjs

### ISSUE THREAD

**Issue by mcmc4519** [ElemeFE/element#14229]
### Element UI version
2.5.1

### OS/Browsers version
linux, windows10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/none/](https://jsfiddle.net/none/)

### Steps to reproduce
install nuxtjs
include element-ui 2.5.1 
use select component 

You can see error on my page: https://test.tronsmart.ee/
 http://prntscr.com/mcgv1a
And on  https://tronsmart.ee/ all is fine, because element-ui is 2.4.11

### What is Expected?
-

### What is actually happening?
I have been update element-ui from 2.4.11 to 2.5.1 and got error

**Comment by meliksu** [comment]
+1

**Comment by Aksem** [comment]
Is it only with 2.5.1 version of element-ui? I've created new project with `create-nuxt-app`(with 'element-ui' as custom UI framework), element-ui 2.4.11 was installed by default, but I got the same error.

**Comment by mcmc4519** [comment]
> Is it only with 2.5.1 version of element-ui? I've created new project with `create-nuxt-app`(with 'element-ui' as custom UI framework), element-ui 2.4.11 was installed by default, but I got the same error.

Yes, on my PC it's only on > 2.4.11 version.
If I'm install element-ui@2.4.11, all is ok.

**Comment by Aksem** [comment]
Yes, you're right. It was my mistake(I had 2.4.11 in package.json, but 2.5.1 installed). With 2.4.11 it works well.
+1 for error in 2.5.1.

**Comment by carlwangx** [comment]
+1 for error in 2.5.1

**Comment by island205** [comment]
get it, fixing

**Comment by zhichaofu** [comment]
在2.4.11版本也遇到这个问题了：element-ui/lib/select.js:195:18

**Comment by island205** [comment]
@zhichaofu 不可能，你检查一下版本是否真的对。
