### ISSUE TITLE
tree组件的问题

### ISSUE THREAD

**Issue by amin168** [ElemeFE/element#1422]
tree有没有接口给某一个节点的设置未勾选状态吗。
例如原本节点1的checked未true，我要点击一个按钮手动的给这个节点1的checked设置为false，
目前貌似这个组件没有这种方法

**Comment by furybean** [comment]
@amin168 已经提供了 setChecked 方法，你可以试用下。

**Comment by amin168** [comment]
@furybean 已经OK了

**Comment by mqliutie** [comment]
@furybean 第一个参数为 key/ data data的格式是什么样的?
我设置的是 [key1,key2] 这种格式不生效 但是设置某个key是生效的
