### ISSUE TITLE
[Bug Report] upgraded to version 2.5.1, tabs default style, small blue bar under label disappeared

### ISSUE THREAD

**Issue by dieslrae** [ElemeFE/element#14236]
### Element UI version
2.5.1

### OS/Browsers version
chrome

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/xLvsywor/](https://jsfiddle.net/xLvsywor/)

### Steps to reproduce
like the code

### What is Expected?
recovery the small blue bar under label

### What is actually happening?
the small blue bar under label disappeared

**Comment by sds0917** [comment]
修改packages/tabs/src/tab-bar.vue文件中下面代码就ok了。
![_20190128154518](https://user-images.githubusercontent.com/7779851/51821309-b5070e00-2313-11e9-8247-fc5b3b1f01cd.png)

**Comment by iamkun** [comment]
@sds0917 PR #14240  我把判断移到后面了
