### ISSUE TITLE
[Bug Report] Data inside paginator slot not update correctly

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#14237]
### Element UI version
2.5.2

### OS/Browsers version
MacOs 10.14.1 / Chrome 71.0.3578.98 (Official Build) (64-bit)

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/3c6wmojg/1/](https://jsfiddle.net/3c6wmojg/1/)

### Steps to reproduce
Data inside slot not update correctly when data updated.

### What is Expected?
Total page number inside slot should same as above.

### What is actually happening?
Total page number inside slot not updating.

**Comment by kfeng0806** [comment]
This problem since version after 2.4.1

**Comment by kfeng0806** [comment]
Vue 2.6 use `v-slot` can fix this
```javascript
<el-pagination>
    <template v-slot>{{ data }}</template>
</el-pagination>
```

**Comment by fanmzdj** [comment]
感谢。我也遇到了同样的问题，

**Comment by cjjlovedsn** [comment]
今天升级了版本也遇到这个问题了。暂时用下面的方法解决了一下
```
<el-pagination custom-prop="text">
  <v-text/>
</el-pagination>
```
定义一个组件包装一下，通过$parent访问到pagination组件上的属性
```
export default {
  name: 'v-text',
  render (h) {
    return this.$parent.$parent.$attrs.customProp
  }
}
