### ISSUE TITLE
[Bug Report] Vue CLI 3 tree/menu fold/unfold no transition

### ISSUE THREAD

**Issue by baoanj** [ElemeFE/element#14247]
### Element UI version
2.5.2

### OS/Browsers version
normal

### Vue version
2.5.2

### Reproduction Link
[https://github.com/alibaba/ice/tree/master/vue-materials/scaffolds/admin-lite](https://github.com/alibaba/ice/tree/master/vue-materials/scaffolds/admin-lite)

### Steps to reproduce
Import element-ui entirely in Vue CLI 3 project, and use el-tree or el-menu. No transition when trying to fold or unfold.

### What is Expected?
Have a transition when trying to fold or unfold.

### What is actually happening?
No transition when trying to fold or unfold.

**Comment by Ttou** [comment]
same problem

**Comment by Eflet** [comment]
same problem

**Comment by Eflet** [comment]
I find 2.4.11 version is OK, but when update to 2.5.2, the transition was gone

**Comment by Chastrlove** [comment]
same problem

**Comment by devforma** [comment]
same problem

**Comment by KevinPan** [comment]
same problem
下拉折叠动效没有了

**Comment by mybolide** [comment]
vue 2.5.17 element-ui：2.4.11也没有效果

**Comment by mybolide** [comment]
> ![kapture 2019-01-31 at 11 27 25](https://user-images.githubusercontent.com/12947422/52028785-4ca27180-254b-11e9-8ce8-8d7d7996a6f5.gif)
> 
> @baoanj @Ttou @KevinPan @mybolide
> 在我本地试了一下，不能重现。请确认该问题是否存在？
> 如果存在，请给出了一个最小化可重现问题的 demo。推荐使用 https://codesandbox.io

刚群里了解下说是已知bug 会在2.6.0版本解决
   @ziyoung ![image](https://user-images.githubusercontent.com/13502882/52029037-8627ac80-254c-11e9-9efe-d5eeb251abb6.png)

**Comment by island205** [comment]
please upgrade to element#2.5.4, this problem is fixed.
