### ISSUE TITLE
[Bug Report] $prompt Input Validation Information Repeated Pop-up after Entering

### ISSUE THREAD

**Issue by netcore-jroger** [ElemeFE/element#14241]
### Element UI version
2.4.11

### OS/Browsers version
Ubuntu 18.04/Version 71.0.3578.98 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/JRoger/0Lr2z75t/15/](http://jsfiddle.net/JRoger/0Lr2z75t/15/)

### Steps to reproduce
1. 文本框中输入任意内容
2. 按回车
3. 弹出$prompt验证对话框
4. 输入12345678912，按回车，会再次弹出$prompt对话框

### What is Expected?
弹出$prompt对话框输入内容按回车后不管验证成功还是失败，都不再弹出$prompt对话框

### What is actually happening?
弹出$prompt对话框输入内容按回车后不管验证成功还是失败会再次弹出$prompt对话框

**Comment by netcore-jroger** [comment]
@island205 暂时按你给的方法用 `@keydown.enter.native` 来处理了。已确认只会弹一次。谢谢！

**Comment by netcore-jroger** [comment]
用 `@keyup.enter.native` 确实是个 bug 。这个 issue 我就不关了，一般你们的 changelog 我都会看的，等你们修复了我再来关了。

**Comment by liupl** [comment]
把组件里的`keydown`事件全都替换成`keyup`貌似是一个不错的选择

**Comment by zowiegong** [comment]
试试在 prompt 的输入框中输入完内容后**长按**回车然后松开。

prompt 中 input 的触发条件是 `@keydown.enter.native`
但是 demo 中外部的 input 触发条件是 `@keyup.enter.native`
实际可能是 enter、up 中间的时差导致这里出现的问题，这里可能不是一个 Bug。

**Comment by a631807682** [comment]
这是一个`bug`，打开`MessageBox`会`focus`到`button`上，而`enter`实际上触发的是`button click`（[message-box/src/main.vue#L72][code] 组件的`keydown/keyup`是不会执行的），结果将导致关闭`MessageBox`并把`focus`重置到`input`上，此时用户还没有松开键盘，所以触发`input keyup/keydown`，所有`MessageBox`都存在同样的问题。

[code]: https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.vue#L72

**Comment by adjkldd** [comment]
get fixed by this pull request https://github.com/ElemeFE/element/pull/18022.  Check and review with your pleasure.

**Comment by adjkldd** [comment]
According to this [Vue.js guide](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components), it does not recommend to use `native` modifier on component.

**Comment by netcore-jroger** [comment]
已经用react去了。再见vue.js

**Comment by Hchenxiao** [comment]
这个bug还没有修复？

**Comment by netcore-jroger** [comment]
> 这个bug还没有修复？

用 React.js 吧。Ant.design
