### ISSUE TITLE
[Feature Request] Simpler on-demand in-component import

### ISSUE THREAD

**Issue by nicooprat** [ElemeFE/element#14246]
### Existing Component
Yes

### Component Name
All

### Description
Hi there, here's the docs for on-demand components imports:

```js
import Vue from 'vue';
import { Button, Select } from 'element-ui';

Vue.component(Button.name, Button);
Vue.component(Select.name, Select);
```

I don't want to register components globally, but locally in each of my own components, so I have to do it like this:

```js
import { Select, Option } from 'element-ui'

export default {
  components: {
    [Select.name]: Select,
    [Option.name]: Option,
  },
}
```

Is there any way to avoid using this "hack" `[Select.name]: Select`? It doesn't work without it, as Vue is looking for a `<select>` component instead of `<el-select>`.

Thanks.

**Comment by georgyfarniev** [comment]
What if you try` import { Button as ElButton, Option as ElOption } from 'element-ui'; `?

**Comment by nicooprat** [comment]
Just tried, I thought it would work even if it's still some extra code:

```js
import { Select as ElSelect, Option as ElOption } from 'element-ui'

export default {
  components: {
    ElSelect,
    ElOption,
  },
}
```

But I'm getting this error: `Cannot find module 'element-ui/lib/theme-chalk/el-option.css'`.
