### ISSUE TITLE
[select]多选框 想通过change事件控制选项数量，出现问题

### ISSUE THREAD

**Issue by Ganother** [ElemeFE/element#1425]
### ElementUI version
1.0.2

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.3

### Reproduction Link

[https://jsfiddle.net/Ganother/b3swyth1/](https://jsfiddle.net/Ganother/b3swyth1/)
### Steps to reproduce
点击选项，超过三个后，改变绑定的数组（v-model）长度，选项处表现正确，结果处表现不正确。
### What is Expected?
超过三个后再点击不会再添加选项
### What is actually happening?
结果处的值和v-model绑定的不一样，而且再次点击选项后，是以结果处的值为基础进行添加删除的，描述不太清晰，麻烦看下上面的链接

**Comment by Leopoldthecoder** [comment]
是 bug。目前正在对 Select 进行重构，重构后的版本已经没有这个 bug 了，会随下个版本发布。

另外，下个版本也许会加入限制多选数目的功能：#1325。

**Comment by Leopoldthecoder** [comment]
Fixed in #1401
