### ISSUE TITLE
[Bug Report] datetimepick component type = datetime, setting format to display errors

### ISSUE THREAD

**Issue by vtejuf** [ElemeFE/element#14258]
### Element UI version
2.5.2

### OS/Browsers version
win7 / chrome 68.0.3440.75

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/vtejuf/wgmxpL8j/](https://jsfiddle.net/vtejuf/wgmxpL8j/)

### Steps to reproduce
给datetimepick组件设置format属性，值为‘yyyy-MM-dd HH:mm:ss’
点击input，弹出popover，选一个日期

set datetimepick attr 'format=yyyy-MM-dd HH:mm:ss'
open popover & select one date

### What is Expected?
popover的date input显示 yyyy-MM-dd 
date input in popover display 'yyyy-MM-dd'

### What is actually happening?
popover的date input显示 yyyy-MM-dd :mm:ss
date input in popover display 'yyyy-MM-dd :mm:ss'

**Comment by wacky6** [comment]
你format写的 `yyyy-MM-dd HH:00:00`

**Comment by vtejuf** [comment]
> 你format写的 `yyyy-MM-dd HH:00:00`

是的，弹窗的第一个input多显示了分、秒位，两个input分别显示了
2019-02-19:00:00 和 00:00:00
应该是 2019-02-19 和 00:00:00 ？
你看我的用例

**Comment by vtejuf** [comment]
> 你format写的 `yyyy-MM-dd HH:00:00`

这样阿，我以为支持固定时间的，为限制值为整点，给了分、秒位固定值
