### ISSUE TITLE
[Bug Report] DatePicker 日期选择器"type=week"，自定义value-format后，选择跨月份的周报错

### ISSUE THREAD

**Issue by sjueshang** [ElemeFE/element#14267]
### Element UI version
2.5.2

### OS/Browsers version
win7 x64 / chrome 71.0.3578.98

### Vue version
2.6.0-beta.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
<el-date-picker v-model="value3" type="week" format="yyyy 第 WW 周" placeholder="选择周" value-format="yyyy-MM-dd">
    </el-date-picker>

### What is Expected?
实现前提：value-format="yyyy-MM-dd";
实现行为：1号不是第一天，即周天，选择包含1号的周，就会出现异常;
希望：希望改进，方便用户吧。值格式为默认的，倒是不会有异常

### What is actually happening?
无

**Comment by wacky6** [comment]
fiddle 链接错了。请更新
