### ISSUE TITLE
Under [Bug Report] Firefox and ie, the el-table component flickers from hidden to displayed

### ISSUE THREAD

**Issue by francecil** [ElemeFE/element#14263]
### Element UI version
2.4.11

### OS/Browsers version
win7/Firefox 64.0、win7/ie

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/r2f1nu9s/2/](https://jsfiddle.net/r2f1nu9s/2/)

### Steps to reproduce
火狐浏览器下

由首页teb切换角色管理tab

### What is Expected?
和chrome表现一样，table不会布局闪烁

### What is actually happening?
table布局会闪一下

**Comment by Francecil** [comment]
分析：未配置的tab控件，采用v-show的做法去控制各个tab的显示，即给内容应用了`display：none`

在ie和火狐下，el-table控件会闪烁下然后正常

el-tab-pane 有个lazy属性延迟渲染，估计是初次渲染用的v-if，后面用的v-show,这样做初始不会闪烁 但后面还是会闪烁。

目前的做法是给每个有el-table的el-tab-pane下面内容加一个`v-if="activeName==='tabPaneName'"`的判断，每次都重新渲染。

但由于每次都重新渲染，每次都会进行表格数据的请求，

**Comment by Francecil** [comment]
利用el-tab-pane的lazy属性，和table的$ready属性解决。。
但感觉有点hack
https://jsfiddle.net/r2f1nu9s/3/
