### ISSUE TITLE
[Bug Report] <el-select>@blur event did not respond

### ISSUE THREAD

**Issue by zeakhold** [ElemeFE/element#14260]
### Element UI version
2.5.2

### OS/Browsers version
MAC/Chrome 71

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/Zeakhold/f24nxwb1/45/](https://jsfiddle.net/Zeakhold/f24nxwb1/45/)

### Steps to reproduce
As the JSFiddle link above.
如上JSFiddle。

### What is Expected?
Expect @blur event works fine.
期望 blur 事件失焦响应正常。

### What is actually happening?
But the @blur event doesn't work.
 实际 blur 事件失焦响应不正常。

**Comment by tglazar** [comment]
There's a typo in @visible-chage on demo - should be @visible-change

**Comment by zeakhold** [comment]
@tglazar  Thanks, @visible-change works fine.
