### ISSUE TITLE
[Feature Request] Option/ Prop to highlight first item by default

### ISSUE THREAD

**Issue by YamenSharaf** [ElemeFE/element#14270]
### Existing Component
Yes

### Component Name
Autocomplete

### Description
Sometimes you wanna give users speedier selection of remote search items by letting them hit enter to quickly select the first result. Currently, there are no props that provide/expose this behavior.

**Comment by YamenSharaf** [comment]
I have made a PR here to address/ fix this issue by using a prop `highlight-first-item`, which is false by default and thus backward compatible.

https://github.com/ElemeFE/element/pull/14269

**Comment by sharjeel619** [comment]
@YamenSharaf Please let me know when this change is published. I need this in my project and can't seem to do it manually.

**Comment by YamenSharaf** [comment]
> @YamenSharaf Please let me know when this change is published. I need this in my project and can't seem to do it manually.

@sharjeel619 Make sure to subscribe to the PR I made here: https://github.com/ElemeFE/element/pull/14269

**Comment by sharjeel619** [comment]
@YamenSharaf I did, Thanks.

**Comment by wacky6** [comment]
Merged.

Should be published in 2.6.0 (scheduled for end of Feb).
