### ISSUE TITLE
[Bug Report] CDN Reference and Reference through Package Inport

### ISSUE THREAD

**Issue by mybolide** [ElemeFE/element#14272]
### Element UI version
2.5.2

### OS/Browsers version
MACOS/Chrome

### Vue version
2.5.21

### Reproduction Link
[http://没法通过jsfiddle复现](http://没法通过jsfiddle复现)

### Steps to reproduce
最近碰到一个问题，element ui如果按照 cnd方式引用 NavMenu 点击收起或者展开有动画效果，但是如果用import 进去的就没有展开收起的动画效果，<transform>组件也是这样的，

### What is Expected?
CDN方式和import方式一样能正常展示动画效果

### What is actually happening?
不能展示动画效果

**Comment by ziyoung** [comment]
Duplicate of #14247
