### ISSUE TITLE
[Bug Report] Checkbox with border has too much margin

### ISSUE THREAD

**Issue by aaronfulkerson** [ElemeFE/element#14283]
### Element UI version
2.5.3

### OS/Browsers version
chrome 72/windows 10

### Vue version
2.6.0-beta.3

### Reproduction Link
https://element.eleme.io/#/en-US/component/checkbox#with-borders/

### Steps to reproduce
Use checkboxes with borders

### What is Expected?
to have the correct amount of margin

### What is actually happening?
they have the INCORRECT amount of margin

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by aaronfulkerson** [comment]
Just look at the checkbox with borders in the reproduction link I sent. The margins are too large! It used to be much smaller.
