### ISSUE TITLE
功能建议：允许 tab 的 label 使用自定义 HTML

### ISSUE THREAD

**Issue by stackia** [ElemeFE/element#1428]
### ElementUI version
1.0.2

### OS/Browers version
Windows 10 / Chrome 54

### Vue version
2.1.0

### What is Expected?

![image](https://cloud.githubusercontent.com/assets/5107241/20663762/9e5fe46e-b593-11e6-921c-1a984209faa2.png)

目前 tab 的标题文字只能使用 `<el-tab-pane label="文字" ...` 这种形式来指定，是否可以允许使用自定义HTML？例如使用 `<template slot="label">标题</template>` 这种形式来指定标题。

我需要实现在标题上显示 badge 的效果，发现目前暂时没有办法实现。

**Comment by soliury** [comment]
+1

**Comment by soliury** [comment]
希望能添加，这个功能还蛮常见的

**Comment by soliury** [comment]
已实现该功能，稍后考虑提个pr

**Comment by Leopoldthecoder** [comment]
Fixed in #1191

**Comment by StringKe** [comment]
@Leopoldthecoder 自定义 label 后更新数据无法渲染dom https://jsfiddle.net/StringKE/dk43Lb7h/8/
