### ISSUE TITLE
[Bug Report] Empty text on table are not getting translated

### ISSUE THREAD

**Issue by calebeaires** [ElemeFE/element#14296]
### Element UI version
2.5.3

### OS/Browsers version
Chrome 70

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Import locale when importing Element entirely.

```typescript
// ELEMENT-UI
import ElementUI from "element-ui";
import "@/styles/normalize.scss";
import "@/styles/element-variables.scss";
import locale from "element-ui/lib/locale/lang/pt-br";

Vue.use(ElementUI, { locale });
```

### What is Expected?
jsFiddle is working but when I load the locale directly from node_modules, it does not work.

### What is actually happening?
Import locale when importing Element entirely does not translate an empty text. On element-ui version 2.4, it was working, but after an upgrade, don't.

<img width="788" alt="screen shot 2019-02-01 at 14 51 39" src="https://user-images.githubusercontent.com/794195/52138418-420fd700-2634-11e9-858f-c57805578e80.png">

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
