### ISSUE TITLE
[Feature Request] Add a Contrast Ratio to Color Picker 

### ISSUE THREAD

**Issue by elise-lcdb** [ElemeFE/element#14294]
### Existing Component
Yes

### Component Name
Color Picker 

### Description
Would it be possible to add a contrast ratio to the color picker? For example, if the color picker is used to change the color of a text it takes into consideration the background color and says if it is has a good contrast ratio or not

**Comment by wacky6** [comment]
You should deal with contrast ratio in your application. We won't add such feature to color picker itself, since color picker does not know the background color.
