### ISSUE TITLE
[Bug Report] ElTabs TabsNav `scrollToActiveTab` method broken for vertical tabs

### ISSUE THREAD

**Issue by dragosbodin** [ElemeFE/element#14292]
### Element UI version
2.5.4

### OS/Browsers version
All

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/otzLqu50/](https://jsfiddle.net/otzLqu50/)

### Steps to reproduce
1. Create an ElTabs instance with the prop `tab-position` set to `left` or `right`.
2. Set the height of the tabs so that scrolling becomes enabled.
3. Click on the down arrow to scroll through the vertical tabs.
4. Click on one of the tabs.

### What is Expected?
Tab navigation should remain in place and open the click tab's contents.

### What is actually happening?
The clicked tab's contents are opened, but the tab navigation incorrectly calculates the offset for the `scrollToActiveTab` method and scrolls to the top.

**Comment by fatpandaria** [comment]
I also found this bug recently on element 2.5.4,after I rolled back the element version to 2.4.5,it's normal again.But this bug still needs to be fixed.

**Comment by fatpandaria** [comment]
But for your demo in jsf,after the step 4,it looks normal, only if I click the up button,the tab will scroll to the top ,where the tab1 locates, which is for sure unexpected.I don't know whether there is other people like me.

**Comment by dragosbodin** [comment]
Even with version 2.4.5 that method is not functioning properly. If you have a partially visible tab pane and click it it doesn't scroll to completely reveal the click tab like it does on horizontal ones.

**Comment by dragosbodin** [comment]
By the way, the current workaround I'm using is to monkey-patch the method so that it returns if `$parent.tabPosition` is set to `left` or `right`.

**Comment by fatpandaria** [comment]
Yes,you are right,it's a compromising way to use 2.4.5 ,for my project it's good enough though.
