### ISSUE TITLE
can't resolve the popper.js.

### ISSUE THREAD

**Issue by zhcsyncer** [ElemeFE/element#143]
### ElementUI version 
1.0.0-rc.4

### What is Expected?

![image](https://cloud.githubusercontent.com/assets/13214840/18806833/ea8cc6d8-826a-11e6-873a-b8fe2b90bf7b.png)

And

### What is actually happening?

![image](https://cloud.githubusercontent.com/assets/13214840/18806864/6c9b6e18-826b-11e6-8b07-f79b3d6e9af3.png)

**Comment by QingWei-Li** [comment]
抱歉，现在先引入全部组件吧或者手动修改下这个路径，改成  `./popper`
