### ISSUE TITLE
功能建议：Table组件增加transition支持

### ISSUE THREAD

**Issue by Fsoya** [ElemeFE/element#1430]
### ElementUI version
1.0.2

### Vue version
2.1.0

### What is Expected?
Table组件增加transition支持及loading设置用于换页加载时的平滑过渡

**Comment by furybean** [comment]
看不太懂，Table 添加 transition 的支持是什么概念。

**Comment by Fsoya** [comment]
table配合翻页组件时增加翻页效果设置

**Comment by furybean** [comment]
可以试试 v-loading，感觉可以满足你的需求。

**Comment by Fsoya** [comment]
嗯 v-loading 可以 但是想精细做到控制到 tr 的 进入移除的效果
我先摸索摸索 
谢谢

**Comment by Wolferring** [comment]
插入，删除行的动画呢？可以加入么

**Comment by Leexiaop** [comment]
嗯，快两年了

**Comment by 57ggfk** [comment]
我也需要，现在2020年快过完了，依然没有提供

**Comment by Mumusen** [comment]
21年了，哈哈哈 有实现思路吗？
