### ISSUE TITLE
[Bug Report] DatePicker el-date-picker

### ISSUE THREAD

**Issue by yun313350095** [ElemeFE/element#14300]
### Element UI version
2.5.4

### OS/Browsers version
Mac OS Chrome

### Vue version
2.6.0-beta.3

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
日期和时间范围组件的时候, picker-options并不能用小时作为计算单位.

### What is Expected?
希望可以固定时间范围范围一样.使用 :picker-options="{start: '08:00',step: '00:60', end: '18:00' }"
以每小时作为计算单位.

### What is actually happening?
可以准确到分钟. 没有办法固定时间

**Comment by wacky6** [comment]
用selectableRange

**Comment by yun313350095** [comment]
用selectableRange 并不能按照小时进行计算 `el-date-picker`
