### ISSUE TITLE
[Bug Report] Firefox: Tooltip hover not working when inside a button

### ISSUE THREAD

**Issue by pmochine** [ElemeFE/element#14305]
### Element UI version
2.5.4

### OS/Browsers version
65 Firefox

### Vue version
2.6.2

### Reproduction Link
[https://jsfiddle.net/g2auekhv/1/](https://jsfiddle.net/g2auekhv/1/)

### Steps to reproduce
Please visit the link with Firefox. Hover tooltip does not work (with other browser it's working). Only when inside a button

### What is Expected?
To hover text

### What is actually happening?
Nothing

**Comment by pmochine** [comment]
Update: Not an issue in element, tried another package and the problem is still there.

So maybe it's a problem of Popper.js? (not sure though, but I still let this issue open, maybe someone has an idea)

**Comment by iamkun** [comment]
Thanks
