### ISSUE TITLE
[Feature Request] Allow filter method to take over transfer data completely

### ISSUE THREAD

**Issue by albru123** [ElemeFE/element#14307]
### Existing Component
Yes

### Component Name
Transfer

### Description
Currently custom filtering in transfer component works by checking each item against search query and returning true or false. For more advanced filtering I think there should be a way of calling the filter function once for all data items and the ouput would be an array of matched items in desired order (for example by hit probability).

I tried filtering and ordering the data object itself, but this approach is not currently possible because the custom filtering function is not called when there are no data items to check against.

Also in case this advanced filtering gets implemented, the left and right transfer item arrays should have their own order, so the search ordering is separated for left and right panels.

**Comment by iamkun** [comment]
Please provide an example with more detail.
