### ISSUE TITLE
[Feature Request] Select all option for multiple el-select

### ISSUE THREAD

**Issue by thukuwanjiku** [ElemeFE/element#14308]
### Existing Component
Yes

### Component Name
el-select

### Description
I could not find an option, or slot to allow selecting all options in a multiple el-select. It'd would be convenient if you can add a 'select-all' option/prop that allows all options in the select to be selected at once.

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.

**Comment by evilsideburns** [comment]
+1 on this.

is there a reason there's no plan to support it?

**Comment by Kris55501** [comment]
+1

**Comment by vikashpisces** [comment]
It's one of the demanding feature that every dropdown should have. It would be great if it can be included in your road map, or atleast can someone guide how to achieve this request with any customization option please.
