### ISSUE TITLE
[Bug Report] Table: Row click/cell click called even when event was already handled by component inside cell

### ISSUE THREAD

**Issue by fabioanderegg** [ElemeFE/element#14301]
### Element UI version
2.5.4

### OS/Browsers version
Internet Explorer 11/Safari

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Lbdpxmae/](https://jsfiddle.net/Lbdpxmae/)

### Steps to reproduce
* Have a component inside a el-table-column (e.g. checkbox or button)
* Implement @row-click or @cell-click on el-table
* Click on button or checkbox
* row-click and cell-click events should not be fired

### What is Expected?
When the component inside the cell handles the event, the cell-click or row-click event should not be fired, or if fired then consistently over multiple browsers.

### What is actually happening?
The event is triggered anyway. When using a checkbox component, the row-click/cell-click event is fired twice. When using the row-click event to change the state that is also used in the checkbox (see jsfiddle example above), the checkbox example still works fine in Firefox and Chrome, but this is by accident. The row-click event is fired twice before firing the checkbox change event:
rowClick2019-02-04T15:18:38.552Z show:44:6
rowClick2019-02-04T15:18:38.555Z show:44:6
checkboxChange2019-02-04T15:18:38.556Z

On Safari and Internet Explorer, the events are interleaved and clicks on the checkbox do not change the state:
[Log] rowClick2019-02-04T15:19:48.542Z (_display, line 44)
[Log] checkboxChange2019-02-04T15:19:48.542Z (_display, line 48)
[Log] rowClick2019-02-04T15:19:48.542Z (_display, line 44)

**Comment by fabioanderegg** [comment]
Workaround for button: Use .stop modifier like so:
`<el-button @click.stop="buttonClick">Button</el-button>`.

I have not found a similar workaround for the checkbox because the native events are not exposed. If the checkbox has the same functionality as the row-click (like in my jsfiddle example), you can do preventDefault() in the row-click event handler:
```
rowClick(row, event) {
  event.preventDefault();
  ....
}
```
This way the click will never register on the checkbox.

**Comment by danikristiansen** [comment]
@click.native.stop works on checkboxes

**Comment by iamkun** [comment]
> @click.native.stop works on checkboxes

@danikristiansen  Thanks
