### ISSUE TITLE
[Bug Report] v-model.trim cannot enter spaces normally

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#14312]
### Element UI version
2.5.4

### OS/Browsers version
mac

### Vue version
2.6.3

### Reproduction Link
[https://jsfiddle.net/tadp9c0b/](https://jsfiddle.net/tadp9c0b/)

### Steps to reproduce
第一个输入框 <el-input> 输入几个字符再输入空格，空格无法输入

第二个原生input 正常输入空格

### What is Expected?
<el-input>在v-model.trim下正常输入空格

### What is actually happening?
<el-input v-model.trim="input"></el-input> 无法直接输入空格

**Comment by wacky6** [comment]
https://vuejs.org/v2/guide/forms.html#trim

**Comment by ac88** [comment]
@wacky6  文档只是说明trim去掉首尾空格，上面jsfiddle的例子是 2个不同input 交互上的差异啊

**Comment by falstack** [comment]
I have same issue

**Comment by georgyfarniev** [comment]
We have same problem, this is very critical for people using element!

**Comment by Deeeeeee** [comment]
I have same issue

**Comment by georgyfarniev** [comment]
@Deeeeeee please read docs. It’s clearly says now that modifiers isn’t supported
