### ISSUE TITLE
[Bug Report] v-model.number cannot enter letters properly

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#14315]
### Element UI version
2.5.4

### OS/Browsers version
mac

### Vue version
2.6.3

### Reproduction Link
[https://jsfiddle.net/L8fs3nek/](https://jsfiddle.net/L8fs3nek/)

### Steps to reproduce
第一个输入框 <el-input> 输入数字后再输入字母，字母无法键入

第二个原生input .输入数字再输入字母，字母正常键入

### What is Expected?
<el-input v-model.number>下数字 字母组合正常输入，字母不被强制阻挡

### What is actually happening?
<el-input v-model.number> 输入数字后再输入字母，字母无法键入,影响交互体验

**Comment by ac88** [comment]
类似问题 https://github.com/ElemeFE/element/issues/14312

**Comment by wacky6** [comment]
不改。`.number` 自行封装 @input 事件和 ：value

**Comment by ac88** [comment]
建议在el-input doc注明不推荐使用v-model modifiers的.number 和.trim
