### ISSUE TITLE
[Bug Report] Vue Cli 3 and Element-UI 2.5.4 Vertical NavMenu Transition Problem

### ISSUE THREAD

**Issue by sinbino** [ElemeFE/element#14314]
### Element UI version
2.5.4

### OS/Browsers version
MacOS 10.14.2 / Chrome 72.0.3626.81

### Vue version
2.6.3

### Reproduction Link
[https://github.com/sinbino/element-ui-transition-issue](https://github.com/sinbino/element-ui-transition-issue)

### Steps to reproduce
Create a project with Vue Cli 3.
```
vue cli test-proj
```

Add vue-cli-plugin-element.
```
vue add element
```

Implement view using vertical collapsable navmenu.
(I prepared an example in github.)

It works with development build.
(/dist-dev folder in the repository.)

However, collapse transition animation does not work properly in production build.
(/dist folder in the repository.)

### What is Expected?
The transition animation works correctly in both builds.

### What is actually happening?
It works correctly in development build, but It does not work properly with production build.
It is similar to #14247, but it also occurs in Element-UI 2.5.4.

**Comment by ziyoung** [comment]
![kapture 2019-03-05 at 12 21 34](https://user-images.githubusercontent.com/12947422/53780886-57cd3080-3f41-11e9-8d3f-1f8406d2b560.gif)
it works for me.
