### ISSUE TITLE
[Feature Request] Accessibility: Pagination

### ISSUE THREAD

**Issue by no0dly** [ElemeFE/element#14318]
### Existing Component
Yes

### Component Name
pagination

### Element UI version
2.5.4

### OS/Browsers version
MacOS Mohave / Safari

### Vue version
2.5.21

### Reproduction Link
https://jsfiddle.net/mczs0pda/2/

### Steps to reproduce
Try to tab or use navigation arrows

### What is Expected?
User should be able to navigate the pagination component using the keyboard. 
Using arrow keys should let the user move between page numbers, enter/space keys should trigger page change.

### What is actually happening?
Pagination is not accessible via keyboard.

**Comment by iamkun** [comment]
pr welcome
