### ISSUE TITLE
Browsersync 开发环境下 chrome 单选复选框有冲突

### ISSUE THREAD

**Issue by x4storm** [ElemeFE/element#1431]
### ElementUI version

1.0.2

### OS/Browers version

macOs/Chrome54
### Vue version

2.1.3

### Reproduction Link

无法网络再现

### Steps to reproduce
因为有一些文件不适合用webpack打包。选择了gulp+webpack的方式。最后用browsersync实时监听开发。
在 chrome 中 单选/复选框点击无效。在 Safari中可以点击。不经过browsersync运行可以点击。
### What is Expected?
希望能告知能否解决这个问题。

**Comment by Leopoldthecoder** [comment]
和 #1106 重复。可能是 browser-sync 的问题，我们这边暂时没有精力研究。
