### ISSUE TITLE
[Feature Request] value of clearable el-select should be set to null instead of empty string

### ISSUE THREAD

**Issue by aaronfulkerson** [ElemeFE/element#14322]
### Existing Component
Yes

### Component Name
el-select

### Description
Since the value of el-select can be string or number, the value should be set to null when it is cleared. This makes more sense than setting the value to an empty string when it is cleared.

**Comment by iamkun** [comment]
pr welcomed

**Comment by jri** [comment]
This "feature request" is a breaking change!

According to npm's semantic versioning policy Element UI 2.7.1 is supposed to be released as 3.0.0 instead. Merging this patch have created a rather annoying situation as version 2.7.1 now possibly breaks thousands of production installations unless package locking is applied.

**Comment by zccSxx** [comment]
这个改动导致了我们线上接口提交数据异常，而且因为用到地方太多，我都不知道该如何下手解决

**Comment by iamkun** [comment]
@zccSxx 已经 revert 了 下周 2.9.0 会发布

**Comment by jri** [comment]
I'm curious: what would be English translation of recent comments?

**Comment by iamkun** [comment]
We've reverted the change related to this issue and will release 2.9.0 in a week.

**Comment by jri** [comment]
Thank you for translation!

**Comment by iamkun** [comment]
@aaronfulkerson we will add it in 3.0

**Comment by winkay** [comment]
Unbelievable

**Comment by K-walker** [comment]
建议 el-select 的 clear 方法应该返回被清除的值，跟remote-tag 方法类似
