### ISSUE TITLE
[Feature Request] Drag and drop between different tables

### ISSUE THREAD

**Issue by hellomp** [ElemeFE/element#14323]
### Existing Component
Yes

### Component Name
El-Table

### Description
I've managed (based on previous issues) to create tables based on a data property using v-for directive and, with SortableJS, drag rows and change their order inside a table. But I can't figure out how to drag a row into another table and reflect that change in my data property. Here's what I've done so far: https://jsfiddle.net/marcosx/2pk8Lev0/20/

Thanks in advance!

**Comment by iamkun** [comment]
This is not a bug related to Element.

**Comment by ziyoung** [comment]
```js
Sortable.create(tables[i], () => {}) // maybe you need change your code
```
