### ISSUE TITLE
[Bug Report] Paging Component [Additional Functions] Code Samples Show Problems

### ISSUE THREAD

**Issue by sunny920406** [ElemeFE/element#14328]
### Element UI version
2.5.4

### OS/Browsers version
Google Chrome 69.0

### Vue version
2.6.5

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
点击【附加功能】下面的【显示代码】,可以看到代码显示在了左边

### What is Expected?
代码片段在组件的正下方

### What is actually happening?
代码片段偏移到了左侧

**Comment by ziyoung** [comment]
fixed
