### ISSUE TITLE
dropdown位置问题

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#1433]
您好，目前dropdown的位置是通过计算出来，直接入在body下面，
一旦窗口大小改变，位置就会出错，并且在根目录下，也不好控制了

bootstrap的实现方式是将他们放在一块，这样的话，元素相邻也好定位
不知道element ui这么设计是有特别的考虑吗

![image](https://cloud.githubusercontent.com/assets/13325335/20664894/349e0326-b598-11e6-9901-e450b912044e.png)

**Comment by Leopoldthecoder** [comment]
这个并不是位置出错。我们采用了 [Popper.js](https://popper.js.org) 来控制这些弹出类的菜单，它能够保证在 resize 或滚动的时候弹出层可见区域最大化。

关于控制，我们后面会为这些弹出层提供自定义类名的功能。

**Comment by fewiki** [comment]
非常感谢，期待ing
