### ISSUE TITLE
[Bug Report] DatePicker

### ISSUE THREAD

**Issue by 4lQuiorrA** [ElemeFE/element#14336]
### Element UI version
2.0.11

### OS/Browsers version
window10

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/z7va2pmw/2/](https://jsfiddle.net/z7va2pmw/2/)

### Steps to reproduce
This is a question of presentation.

### What is Expected?
this icon will on left

### What is actually happening?
but in my project ,on right?!!!

**Comment by ziyoung** [comment]
check your CSS.
