### ISSUE TITLE
[Bug Report] v-model.number cannot enter decimal points

### ISSUE THREAD

**Issue by lmwdtzs** [ElemeFE/element#14330]
### Element UI version
2.5.4

### OS/Browsers version
win7 64位;Chrome v70.0.3538.110

### Vue version
2.6.5

### Reproduction Link
[https://jsfiddle.net/lmwdtzs/eL6k0387/1/](https://jsfiddle.net/lmwdtzs/eL6k0387/1/)

### Steps to reproduce
第一个el-input，输入数字后，无法在数字末尾输入小数点，只能在数字中间输入小数点
第二个原生input，可以正常输入小数点

### What is Expected?
el-input的v-model.number可以正常输入小数点

### What is actually happening?
数字末尾无法输入小数点，只能在数字中间输入小数点，影响体验且用户一般无法发现如何输入小数点

**Comment by lmwdtzs** [comment]
element-ui@2.4.10还是正常的，新版会有这个问题

**Comment by xiongsongsong** [comment]
我也遇到了，正准备提issue。

**Comment by wacky6** [comment]
请不要在el-input的v-model上用修饰符（包括lazy、number、trim）

要实现功能请自行处理input事件

**Comment by xiongsongsong** [comment]
@wacky6 那为什么以前可以用？为什么除了bug文档也没有说明？

**Comment by xiongsongsong** [comment]
v-model.number是vue自带的功能，并且这个这在两年内一直稳定，用的好好的，突然就被 @wacky6 说不要用。
[image](https://user-images.githubusercontent.com/342509/52935962-ce8cfa00-3395-11e9-8d38-ebac5fa2a07d.png)

**Comment by goforward01** [comment]
遇到同样的问题，带有number修饰的组件，升级完之后突然发现无法输入小数点

**Comment by xinlv123** [comment]
Same issues here! Hope this will be fixed soon.

**Comment by lyc2014** [comment]
把type设置为number就可以输入了，<el-input type="number" v-model.number=""></el-input>

**Comment by FoooooooF** [comment]
可以使用回2.3.7版本

**Comment by sandeshgb** [comment]
`<el-input
                v-model="postForm.minimumAmount"
                name="minimumAmount"
                required
                placeholder="Minimum Amount"
                type="number"
                step="0.01"
              />` worked for me even for decimal

**Comment by C-Powers** [comment]
@sandeshgb that works, kinda, but it'll add browser validation into the mix as well, and will apply browser styles to the input.

**Comment by syd192** [comment]
<el-input type="number" v-model.number="inputVal"></el-input>

set type && .number is OK🙆

**Comment by Owen-igaw** [comment]
v2.13.0 has same issue!
When typing the the decimal point number values equal to zero like `0.0`, `0.00`,
the v-model value is changed to `0`.

Because of this issue, the way to type numbers like `0.001` is too complex. (should type the zero between the first not zero value and float point, `0.1` => `0.001`)

**Comment by ytw0728** [comment]
v2.13.0 has same issue!
When typing the the decimal point number values equal to zero like 0.0, 0.00,
the v-model value is changed to 0.

Because of this issue, the way to type numbers like 0.001 is too complex. (should type the zero between the first not zero value and float point, 0.1 => 0.001)

**Comment by angrilove** [comment]
Why cannot support v-model modifer?

**Comment by hjj5258** [comment]
在框架迁移1.x 到2.x 中 应说明情况，更新日志并没有说明这一点。

**Comment by fanchong02** [comment]
降级到较近的老版本~

**Comment by rexSurprise** [comment]
可以直接   `<el-input type="number" v-model.number="amount"></el-input>` 
但是在电脑端会出现一个加减的箭头，这个可以用css去掉
```css
input[type="number"]::-webkit-inner-spin-button{
  display: none!important;
}
```

**Comment by Laciniata** [comment]
> 可以直接 `<el-input type="number" v-model.number="amount"></el-input>`
> 但是在电脑端会出现一个加减的箭头，这个可以用css去掉
> 
> ```css
> input[type="number"]::-webkit-inner-spin-button{
>   display: none!important;
> }
> ```

@rexSurprise 如果放在<style scoped>中会不生效，有没有对应的修改方式来去掉箭头呢？

**Comment by a1156883061** [comment]
> > 可以直接 `<el-input type="number" v-model.number="amount"></el-input>`
> > 但是在电脑端会出现一个加减的箭头，这个可以用css去掉
> > ```css
> > input[type="number"]::-webkit-inner-spin-button{
> >   display: none!important;
> > }
> > ```
> 
> @rexSurprise 如果放在<style scoped>中会不生效，有没有对应的修改方式来去掉箭头呢？

`input`在`el-input`内部，去除箭头，需要用深层访问符修改`input`的样式
```
.el-input /deep/ input::-webkit-inner-spin-button {
  display: none !important;
}
```
