### ISSUE TITLE
[Bug Report] inputNumber value

### ISSUE THREAD

**Issue by jzawer** [ElemeFE/element#14337]
### Element UI version
2.4.9

### OS/Browsers version
windows chrome 72

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/p6w52e8h/](https://jsfiddle.net/p6w52e8h/)

### Steps to reproduce
set input number value to null

### What is Expected?
same as undefined value, when set value to null, input is empty.

### What is actually happening?
value is set to default

**Comment by ziyoung** [comment]
Duplicate of #11980
