### ISSUE TITLE
How do buttons in NavMenu actively lose their selected state

### ISSUE THREAD

**Issue by ruofee** [ElemeFE/element#14333]
### Existing Component
是

### Component Name
NavMenu

### Description
根据官方文档, NavMenu组件的default-active为当前激活菜单的index, 因此我进行以下操作:
```
computed: {
  defaultActive() {
    return this.$route.meta.index;
  }
};
```
然后进行模板编辑: 
```vue
<el-menu :default-active="defaultActive">;
```
并在router.js中将每个可以通过点击菜单进行跳转的路由的meta添加index属性;
之后我点击菜单跳转页面, 菜单中的按钮显示被选中状态(高亮), 但是当我从该页面路由跳转到某个meta.index为undefined的页面时, 菜单中的按钮的被选中状态并没有消失, 通过vue开发者工具查看NavMenu, 发现default-active属性确实已经为undefined了

请问有方法主动去除菜单按钮的被选中状态吗?

**Comment by littleluckly** [comment]
我也发现这个问题了，不知道怎么解决。就是当default-active的值如果没有匹配到index，上一次选中高亮状态仍然存在

**Comment by ziyoung** [comment]
跟这个 pr 有关系 #13298 解决方案是重置 menu 的 activeIndex 为空。
https://jsfiddle.net/y5w1L2tf/
