### ISSUE TITLE
[Bug Report] el-input component always displays undefined input when unbound V-model

### ISSUE THREAD

**Issue by changexbc** [ElemeFE/element#14332]
### Element UI version
2.5.4

### OS/Browsers version
macOS 10.14.2 / Chrome 71.0.3578.98

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/sgweya7r/](https://jsfiddle.net/sgweya7r/)

### Steps to reproduce
在el-input组件中输入内容

### What is Expected?
可以正常输入内容并可通过@input事件监听到变化

### What is actually happening?
无法输入内容

**Comment by changexbc** [comment]
@wacky6 虽然不显示undefined了，但是在不绑定v-model的情况下依然无法输入内容，这是出于什么考虑故意这样设计的吗

**Comment by wacky6** [comment]
受控组件。以前不绑定能输入其实是实现上的问题。

**Comment by changexbc** [comment]
在`handleInput`的时候，执行了`this.$emit('input', event.target.value);`，为什么不是`this.input=event.target.value`而是`this.input=this.value`呢？
组件内的input在props没有传入disabled的情况下是不是保持可输入比较合理？

https://jsfiddle.net/n2zrvsu9/2/

比如有上面这种情况，其中el-input仅仅只是用于输入内容，然后通过@input接受输入的字符串再进行翻译就会出现问题。目前el-input组件必须绑定v-model才可以输入内容的情况下，就无法满足这类不需要绑定v-model的情况。

而2.4.11版本就不存在这个问题 https://jsfiddle.net/n2zrvsu9/3/

**Comment by wacky6** [comment]
所谓受控组件的意思是DOM的状态总会保持和组件状态一致。input的状态由v-model/value控制，input事件处理函数没改value，那么input的状态没有改变，所以显示的东西也不会变。

**Comment by changexbc** [comment]
好吧，那看来我不能通过el-input来处理这种情况了。

**Comment by wacky6** [comment]
处理当然是可以的。 https://jsfiddle.net/dn4xk0s6/  加个v-model保持输入框状态就行了

**Comment by changexbc** [comment]
在存在多个这种el-input或者是遍历数组生成的时候，这不是一个好的解决方案。。

**Comment by wacky6** [comment]
那就自行封装一个带状态的。
