### ISSUE TITLE
[Feature Request] el-pagination - define a parameter determines whether to immediately change the number of pages when selected a new pagesize. 

### ISSUE THREAD

**Issue by qiangbro** [ElemeFE/element#14349]
### Existing Component
是

### Component Name
el-pagination

### Description
目前的情况是，当调整每页显示条数时，分页数量会立即产生变化，这样就会导致一个问题：
当@size-change 事件触发时，可能会紧接着自动触发@current-change事件，导致同时触发两次对后台api的调用。
所以，希望element团队可以为el-pagination添加一个可配置的参数，用来控制当调整每页显示条数时，分页数量是否会立即产生变化。
从而当@size-change 事件触发时，不会紧接着自动触发@current-change事件。

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
