### ISSUE TITLE
The tree component's bug

### ISSUE THREAD

**Issue by hnxydingchen** [ElemeFE/element#14341]
### Element UI version
2.5.4

### OS/Browsers version
chrome 版本 74.0.3702.0（正式版本）canary （64 位）

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/np84ru15/1/](https://jsfiddle.net/np84ru15/1/)

### Steps to reproduce
1、check the node
2、expand the node
3、the node which we clicked has been not checked ( All of this things is just has been  appeared at the first time , It may be because of lazy loading )

### What is Expected?
1、check the node
2、expand the node
3、the node which we clicked is also has been checked

### What is actually happening?
the node which we clicked has been not checked

**Comment by zhusipu** [comment]
Which engineer can quickly fix this problem, anxious, thanks

**Comment by ziyoung** [comment]
更新一下例子https://jsfiddle.net/60v412zt/ 例子中的 Math.random 太迷惑人了。😰

**Comment by ziyoung** [comment]
pr #13349 导致的。

**Comment by hnxydingchen** [comment]
> pr #13349 导致的。

thanks~~
