### ISSUE TITLE
[Bug Report] [dropdown] .elm property doesn't exist in slots in mounted hook

### ISSUE THREAD

**Issue by krnan9525** [ElemeFE/element#14345]
### Element UI version
2.5.4

### OS/Browsers version
MacOS

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/ywpe913h/5/](https://jsfiddle.net/ywpe913h/5/)

### Steps to reproduce
__only tested on dropdown but potentially can happen to other components__

When migrate to the new Vue slot Syntax, eg. `#slot-name={ scopedVariables }`, this error popped up.
Please also refer to this link: 
https://github.com/vuejs/vue/issues/5427
.elm shouldn't be used here.

This is kind of important since the old slot, scoped-slot syntax will not be supported anymore in vue 3.0 

### What is Expected?
No console error and drop down work as expected.

### What is actually happening?
Console errored and dropdown not working.

**Comment by krnan9525** [comment]
This might happen to the other ones with renderer function and slots.

Thanks!

**Comment by ziyoung** [comment]
Use new v-slot syntax.

```diff
+ <template v-slot:dropdown>
+   <el-dropdown-menu>
- <el-dropdown-menu slot="dropdown">
```
