### ISSUE TITLE
[Bug Report] Can't set the width of the Switch

### ISSUE THREAD

**Issue by TGuoW** [ElemeFE/element#14346]
### Element UI version
2.5.4

### OS/Browsers version
win10 / chorme71

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/wf4o6amz/1/](https://jsfiddle.net/wf4o6amz/1/)

### Steps to reproduce
Click the button

### What is Expected?
The width of the switch component becomes 80.

### What is actually happening?
The width of the switch component has not changed.

**Comment by ziyoung** [comment]
Right now width is not reactive. You can use two Switch.
