### ISSUE TITLE
[Bug Report] When the V-model of `el-input [type = textarea] `contains a trim modifier, it cannot change lanes by return.

### ISSUE THREAD

**Issue by mu-yu** [ElemeFE/element#14353]
### Element UI version
2.5.4

### OS/Browsers version
win10 / chrome 72

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/3y9kor1e/](https://jsfiddle.net/3y9kor1e/)

### Steps to reproduce
在最新版 element-ui（2.5.4）的 `el-iuput[type=textarea]`中，当`v-model`有trim修饰符时，且光标在末尾时，无法通过按回车来换行，换成 2.4.11 这个版本就没有问题

### What is Expected?
可以正确的换行

### What is actually happening?
无法通过回车换行

**Comment by wacky6** [comment]
Input 为受控组件，它总会显示 Vue 绑定值。

通常情况下，应当处理 input 事件，并更新组件的绑定值（或使用v-model）。否则，输入框内显示的值将不会改变。

不支持 v-model 修饰符。

**Comment by mu-yu** [comment]
`el-input` 竟然不支持 `v-model` 带修饰符…好吧……

**Comment by zLinz** [comment]
EMMMMMMMM， 同样的问题
