### ISSUE TITLE
【input icon】希望添加input icon鼠标移过提示信息

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#1435]
### ElementUI version
1.0.2

### OS/Browers version
win10/Chrome 53

### Vue version
2.1.3

### What is Expected?
希望能够添加input后icon鼠标移过的提示信息，也即title属性
### What is actually happening?
在文档中没有找到添加的方法

**Comment by Leopoldthecoder** [comment]
这个近期应该不会加。建议自己 hack 一下，比如给 icon 的 HTML 节点添加 `mouseenter` 和 `mouseleave` 事件。
