### ISSUE TITLE
[Bug Report] Tabs custom label cannot be modified immediately after changing label

### ISSUE THREAD

**Issue by xiaoniezi** [ElemeFE/element#14351]
### Element UI version
2.5.4

### OS/Browsers version
window 10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xiaoniezi/gvn0ur3x/](https://jsfiddle.net/xiaoniezi/gvn0ur3x/)

### Steps to reproduce
1.tab自定义label

2.延迟修改label的内容

3.点击tab

### What is Expected?
可以立即触发label相应的内容

### What is actually happening?
需要点击tab才会触发

**Comment by hjw2016** [comment]
在官方没有解决这个bug前，可以用this.$refs.tabs.$children[0].$forceUpdate()去强制更新

**Comment by bsott** [comment]
I think it is still not working

https://jsfiddle.net/moraxphs/
vs
https://jsfiddle.net/nrfdgbtm/

**Comment by ls917643551** [comment]
在我的项目中 Element 2.7.0 里依然存在这个问题，等待新版本

**Comment by bbbford** [comment]
It appears that this bug has re-surfaced. I am using version 2.8.2 and am experiencing this bug. It was fixed in prior versions.

**Comment by bsott** [comment]
Actually, version 2.8.2 seems to be working:

https://jsfiddle.net/90fat8xd/1/
