### ISSUE TITLE
[Feature Request] MessageBox, closeOnPressEscape: ESC trigger action: "cancel"/"close"

### ISSUE THREAD

**Issue by tolmachevfa** [ElemeFE/element#14366]
### Existing Component
Yes

### Component Name
MessageBox

### Description
closeOnPressEscape now gives the answer "cancel", from the name it is expected to get "close".
It would be nice to be able to get the answer "close" too.

**Comment by iamkun** [comment]
Reasonable suggestion. But this would be a breaking change,

Move to 3.0.0 for more discussion.
