### ISSUE TITLE
When an el-table is embedded in the [Bug Report] field set element, the width of the el-table element increases indefinitely and is not caused by the user's own js.

### ISSUE THREAD

**Issue by OPQAI** [ElemeFE/element#14365]
### Element UI version
0.1.0

### OS/Browsers version
win7, chrome

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/6nwycqfr/1/](https://jsfiddle.net/6nwycqfr/1/)

### Steps to reproduce
在fieldset元素中嵌入一个el-table表格，然后这个el-table表格的宽度会无限增长。

示例在 https://jsfiddle.net/6nwycqfr/1/中，
当你点击左边的按钮时，会切换下面的fieldset元素的一个类'fix-bug'，之后下面的那个el-table表格的宽度会无限增长，导致底部的横向滚动条会不断增长。
但当你点击按钮为fieldset元素添加一个类'fix-bug'，el-table表格的宽度就不会无限增长了。

### What is Expected?
在fieldset元素中嵌入一个el-table表格，然后这个el-table表格的宽度不要无限增长。

### What is actually happening?
在fieldset元素中嵌入一个el-table表格，然后这个el-table表格的宽度会无限增长。

**Comment by iamkun** [comment]
use `div` or pr welcomed
