### ISSUE TITLE
自定义验证时，form-item内部的自定义组件中的select存在suffix时，会增加一个结果反馈图标，form的status-icon属性无效

### ISSUE THREAD

**Issue by zh263808335** [ElemeFE/element#14367]
BUGGER
目前使用的版本为2.4.11
[自定义验证时，form-item内部的自定义组件中（el-dialog）的select存在suffix时，会增加一个结果反馈图标，form的status-icon属性无效]
参见图片：
https://share.weiyun.com/5NJ3Zsu

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
