### ISSUE TITLE
[Bug Report] Input-number component cannot be in uncontrolled state

### ISSUE THREAD

**Issue by agileago** [ElemeFE/element#14369]
### Element UI version
2.5.4

### OS/Browsers version
mac

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/e04pzkd7/1/](https://jsfiddle.net/e04pzkd7/1/)

### Steps to reproduce
默认值12  输入框应该一直步进向上加，但加到13就不加了

### What is Expected?
假如没有v-model，应该处于非受控状态，用户可以自由加减

### What is actually happening?
既没有处于受控状态，也没有处于非受控状态

**Comment by wacky6** [comment]
这是历史遗留问题。组件状态会处于受控状态。以后修。

**Comment by liupl** [comment]
是不是因为使用`v-bind`绑定的值为单向绑定，组件无法触发`input`事件改变父组件的`value`值
![image](https://user-images.githubusercontent.com/23089279/53064020-3c096980-3501-11e9-891d-50ddf699f239.png)

**Comment by iamkun** [comment]
waiting PR merged
