### ISSUE TITLE
[Bug Report] When the shuttle box is nested in the multiple-box group, the full-selected state of the shuttle box will be confused after operation.

### ISSUE THREAD

**Issue by Heroor** [ElemeFE/element#14364]
### Element UI version
2.5.4

### OS/Browsers version
macos 10.14.2/chrome 71.0.3578.98

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/8oa30kzs/](https://jsfiddle.net/8oa30kzs/)

### Steps to reproduce
左边穿梭框全选
全部移动至右边后，全选还是勾选状态

### What is Expected?
期待穿梭框全选且移动后，全选状态为未勾选

### What is actually happening?
穿梭框全选且移动后，全选状态还是已勾选

**Comment by iamkun** [comment]
https://jsfiddle.net/52qu9v1r/ is recommended.
