### ISSUE TITLE
[Bug Report] How extends component?

### ISSUE THREAD

**Issue by makenskiy** [ElemeFE/element#14379]
### Element UI version
2.5.4

### OS/Browsers version
Linux, Ubuntu, Google Chrome 71.0.3578.98

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/m4jtwxu1/](https://jsfiddle.net/m4jtwxu1/)

### Steps to reproduce
Hi. I need help. I extends component "picker" for edit template. How i can do it?

I make new custom component: 

```
<template>
	<div class="c-el-date-picker">
               <!-- this default template -->
		<el-input
			class="el-date-editor"
			:class="'el-date-editor--'   type"
			:readonly="!editable || readonly || type === 'dates'"
			:disabled="pickerDisabled"
			:size="pickerSize"
			:name="name"
			v-bind="firstInputId"
			v-if="!ranged"
			v-clickoutside="handleClose"
			:placeholder="placeholder"
			@focus="handleFocus"
			@keydown.native="handleKeydown"
			:value="displayValue"
			@input="value => userInput = value"
			@change="handleChange"
			@mouseenter.native="handleMouseEnter"
			@mouseleave.native="showClose = false"
			:validateEvent="false"
			ref="reference">
			<i slot="prefix"
				class="el-input__icon"
				:class="triggerClass"
				@click="handleFocus">
			</i>
			<i slot="suffix"
				class="el-input__icon"
				@click="handleClickIcon"
				:class="[showClose ? ''   clearIcon : '']"
				v-if="haveTrigger">
			</i>
		</el-input>
		<div
			class="el-date-editor el-range-editor el-input__inner"
			:class="[
				'el-date-editor--'   type,
				pickerSize ? `el-range-editor--${ pickerSize }` : '',
				pickerDisabled ? 'is-disabled' : '',
				pickerVisible ? 'is-active' : ''
			]"
			@click="handleRangeClick"
			@mouseenter="handleMouseEnter"
			@mouseleave="showClose = false"
			@keydown="handleKeydown"
			ref="reference"
			v-clickoutside="handleClose"
			v-else>
			<i :class="['el-input__icon', 'el-range__icon', triggerClass]"></i>
			<input
				autocomplete="off"
				:placeholder="startPlaceholder"
				:value="displayValue && displayValue[0]"
				:disabled="pickerDisabled"
				v-bind="firstInputId"
				:readonly="!editable || readonly"
				:name="name && name[0]"
				@input="handleStartInput"
				@change="handleStartChange"
				@focus="handleFocus"
				class="el-range-input">
			<slot name="range-separator">
				<span class="el-range-separator">{{ rangeSeparator }}</span>
			</slot>
			<input
				autocomplete="off"
				:placeholder="endPlaceholder"
				:value="displayValue && displayValue[1]"
				:disabled="pickerDisabled"
				v-bind="secondInputId"
				:readonly="!editable || readonly"
				:name="name && name[1]"
				@input="handleEndInput"
				@change="handleEndChange"
				@focus="handleFocus"
				class="el-range-input">
			<i
				@click="handleClickIcon"
				v-if="haveTrigger"
				:class="[showClose ? ''   clearIcon : '']"
				class="el-input__icon el-range__close-icon">
			</i>
		</div>
	</div>
</template>

<script>
	import picker from 'element-ui/packages/date-picker/src/picker.vue'

	export default {
		extends: picker
	}
</script>
```

call my page:
```
<template>
	<div class="c-el-date-picker">
		<custom-date-picker
			v-model="value1"
      type="date"
      placeholder="Pick a day"
		></custom-date-picker>
	</div>
</template>

<script>
import CustomDatePicker from './CustomDatePicker'
export default {
		components: {
			CustomDatePicker
		},
		data() {
			return {
				value1: null
			}
		},
		watch: {
			value1(value) {
				console.log('value', value)
			}
		}
	}
</script>
```

### What is Expected?
I want template without input (range date picker)

### What is actually happening?
Error:
```
1841 TypeError: Cannot read property 'indexOf' of undefined
    at VueComponent.ranged (picker.vue?8577:451)
```

This str
```
computed: {
    ranged() {
      return this.type.indexOf('range') > -1;
    },
```
https://yadi.sk/i/bwIQBceiTDIzYw

**Comment by makenskiy** [comment]
I see source, and make as

CustomDatePicker.vue
```
<template>
<div class="c-el-date-picker">....</div>
</template>
<script>
	import Picker from 'element-ui/packages/date-picker/src/picker'
	import DatePanel from 'element-ui/packages/date-picker/src/panel/date'
	import DateRangePanel from 'element-ui/packages/date-picker/src/panel/date-range'

	const getPanel = function(type) {
		if (type === 'daterange' || type === 'datetimerange') {
			return DateRangePanel
		}
		return DatePanel
	}

	export default {
		mixins: [Picker],
		props: {
			type: {
				type: String,
				default: 'date'
			},
			timeArrowControl: Boolean
		},

		watch: {
			type(type) {
				if (this.picker) {
					this.unmountPicker()
					this.panel = getPanel(type)
					this.mountPicker()
				} else {
					this.panel = getPanel(type)
				}
			}
		},

		created() {
			this.panel = getPanel(this.type)
		}
	}
</script>
```

My page
```
<template>
	<div class="c-el-date-picker">
		<custom-date-picker
			v-model="value1"
      type="date"
      placeholder="Pick a day"
		></custom-date-picker>
	</div>
</template>

<script>
	import CustomDatePicker from './CustomDatePicker'

export default {
		components: {
			CustomDatePicker
		},
		data() {
			return {
				value1: null
			}
		},
		watch: {
			value1(value) {
				console.log('value', value)
			}
		}
	}
</script>
```

I's not work. This error

 error  in ./node_modules/element-ui/packages/scrollbar/src/main.js

Module parse failed: Unexpected token (65:6)
You may need an appropriate loader to handle this file type.
|     }, this.$slots.default);
|     const wrap = (
|       <div
|         ref="wrap"
|         style={ style }


I think this jsx. Install https://github.com/vuejs/babel-plugin-transform-vue-jsx, but not work. I can not understand anything :(

**Comment by wacky6** [comment]
A word of caution: try not to use internal modules:

* we officially won't support it. you are on your own if you encounter problems.
* we may change its interface (props / data) implementation without notice. your code may break when we release a new version.

---

From the error message, you may want to check element's webpack configuration.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by plqin-xiaohao** [comment]
@makenskiy 

very good !

you solved my problem !!

**Comment by klren0312** [comment]
来一波`vue-cli3`的 `vue.config.js`配置
```javascript
const path = require('path')

module.exports = {
  chainWebpack: config => {
    config.module
      .rule('thejs')
      .test(/\.js$/)
      .include
        .add(path.resolve('src'))
        .add(path.resolve('node_modules/element-ui/packages'))
        .end()
      .use('babel-loader')
        .loader('babel-loader')
        .end()
  }
}
```

**Comment by nongzhenli** [comment]
> 来一波`vue-cli3`的 `vue.config.js`配置
> 
> ```js
> const path = require('path')
> 
> module.exports = {
>   chainWebpack: config => {
>     config.module
>       .rule('thejs')
>       .test(/\.js$/)
>       .include
>         .add(path.resolve('src'))
>         .add(path.resolve('node_modules/element-ui/packages'))
>         .end()
>       .use('babel-loader')
>         .loader('babel-loader')
>         .end()
>   }
> }
> ```

哈哈，谢谢！正好是我需要的

**Comment by Gz921** [comment]
> 来一波`vue-cli3`的 `vue.config.js`配置
> 
> ```js
> const path = require('path')
> 
> module.exports = {
>   chainWebpack: config => {
>     config.module
>       .rule('thejs')
>       .test(/\.js$/)
>       .include
>         .add(path.resolve('src'))
>         .add(path.resolve('node_modules/element-ui/packages'))
>         .end()
>       .use('babel-loader')
>         .loader('babel-loader')
>         .end()
>   }
> }
> ```

请问.rule('thejs')  thejs是什么？

**Comment by klren0312** [comment]
> > 来一波`vue-cli3`的 `vue.config.js`配置
> > ```js
> > const path = require('path')
> > 
> > module.exports = {
> >   chainWebpack: config => {
> >     config.module
> >       .rule('thejs')
> >       .test(/\.js$/)
> >       .include
> >         .add(path.resolve('src'))
> >         .add(path.resolve('node_modules/element-ui/packages'))
> >         .end()
> >       .use('babel-loader')
> >         .loader('babel-loader')
> >         .end()
> >   }
> > }
> > ```
> 
> 请问.rule('thejs') thejs是什么？

# 只是个命名, 可改

**Comment by wydingez** [comment]
> 来一波`vue-cli3`的 `vue.config.js`配置
> 
> ```js
> const path = require('path')
> 
> module.exports = {
>   chainWebpack: config => {
>     config.module
>       .rule('thejs')
>       .test(/\.js$/)
>       .include
>         .add(path.resolve('src'))
>         .add(path.resolve('node_modules/element-ui/packages'))
>         .end()
>       .use('babel-loader')
>         .loader('babel-loader')
>         .end()
>   }
> }
> ```

也可以这样
```js
module.exports = {
    transpileDependencies: [
        'element-ui/packages'
    ]
}
```

**Comment by trry-github** [comment]
> > 来一波`vue-cli3`的 `vue.config.js`配置
> > ```js
> > const path = require('path')
> > 
> > module.exports = {
> >   chainWebpack: config => {
> >     config.module
> >       .rule('thejs')
> >       .test(/\.js$/)
> >       .include
> >         .add(path.resolve('src'))
> >         .add(path.resolve('node_modules/element-ui/packages'))
> >         .end()
> >       .use('babel-loader')
> >         .loader('babel-loader')
> >         .end()
> >   }
> > }
> > ```
> 
> 也可以这样
> 
> ```js
> module.exports = {
>     transpileDependencies: [
>         'element-ui/packages'
>     ]
> }
> ```

改了以后，还是会报错 我引入的时scrollbar组件

**Comment by Guoqi77** [comment]
遇到了同样的报错 vite 如何配置呀

**Comment by LuciferHuang** [comment]
根本原因还是 scrollbar 必须编译后才能使用，所以直接把 scrollbar 也本地化就可以了，是整个 scrollbar 文件夹都放到项目里哦，不需要额外改配置，直接就可以运行
