### ISSUE TITLE
[Bug Report] checkbox: Change events are not triggered when data is manually modified

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#14377]
### Element UI version
2.5.4

### OS/Browsers version
macOS / chrome 版本 72.0.3626.109（正式版本） （64 位）

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/yxn8dkob/1/](https://jsfiddle.net/yxn8dkob/1/)

### Steps to reproduce
手动点击< 选中复选框 B > 按钮， 不会触发change事件（文档中的描述是，当绑定值发生变化时，触发change事件）。

### What is Expected?
可以触发change事件

### What is actually happening?
不会触发change事件

**Comment by liupl** [comment]
文档里写到绑定值变化就会触发change事件，但是测试文件里写手动触发绑定的值改变不会触发change事件才会测试通过

**Comment by liupl** [comment]
it('checkbox-button group change event', done => {
      vm = createVue({
        template: `
        <el-checkbox-group v-model="checkList" @change="onChange">
          <el-checkbox-button label="a" ref="a"></el-checkbox-button>
          <el-checkbox-button label="b" ref="b"></el-checkbox-button>
          <el-checkbox-button label="c" ref="c"></el-checkbox-button>
          <el-checkbox-button label="d" ref="d"></el-checkbox-button>
        </el-checkbox-group>
      `,
        methods: {
          onChange(val) {
            this.data = val;
          }
        },
        data() {
          return {
            data: '',
            checkList: []
          };
        }
      }, true);
      vm.$refs.a.$el.click();
      setTimeout(_ => {
        expect(vm.data).to.deep.equal(['a']);
        vm.checkList = ['b'];
        setTimeout(_ => {
          expect(vm.data).to.deep.equal(['a']);
          done();
        }, 10);
      }, 10);
    });

**Comment by LemonAppleMo** [comment]
嗯嗯 。因为要做一个一键清除筛选项的功能，并且在checkbox-group的change事件中加入了相对应获取数据的逻辑，想的是手动改变数据，会触发change事件，但是发现并没有成功，才发现的这个问题。我看到checkbox-group的change事件是由checkbox-button去触发group的change事件的，所以在手动修改数据的时候才没有触发change事件。
![image](https://user-images.githubusercontent.com/32638462/52988511-82e05c00-343a-11e9-8761-f854f61202e9.png)
其实不是大问题，我自己再触发一下相对应的逻辑即可。

**Comment by LemonAppleMo** [comment]
但是本着严谨的话  还是在group中监听一下value比较好，因为毕竟数据已经发生变化，理应触发change事件。

**Comment by wacky6** [comment]
文档错了。 2.0 以后 change 事件仅在用户与组件交互且修改了组件值的时候触发。

要捕获任何方式的组件值修改，用 Vue 的 watch

**Comment by LemonAppleMo** [comment]
好
