### ISSUE TITLE
[Feature Request] Validation on change should only occur after first blur

### ISSUE THREAD

**Issue by franciscolourenco** [ElemeFE/element#14371]
### Existing Component
Yes

### Component Name
el-input

### Description
When the `trigger` for validation is ` ['blur', 'change']`, the validation should only be triggered on `'change'` after it has been triggered on `'blur'` at least once. Otherwise users start seeing error messages has soon as they start typing their email.

Example on email input : https://element.eleme.io/#/delete-or-add-form-items-dynamically

```vue
:rules="[
      { type: 'email', message: 'Please input correct email address', trigger: ['blur', 'change'] }
]"
```

**Comment by iamkun** [comment]
pr welcomed

**Comment by franciscolourenco** [comment]
Should this issue remain open until a PR is merged?
