### ISSUE TITLE
Options of [Bug Report] el-select cannot be hidden when the mouse scrolls

### ISSUE THREAD

**Issue by sarahMmh** [ElemeFE/element#14376]
### Element UI version
2.5.4

### OS/Browsers version
Chrome／Safari

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/mumuyuexi/fakun29b/](https://jsfiddle.net/mumuyuexi/fakun29b/)

### Steps to reproduce
1、点击下拉框
2、滑动鼠标

### What is Expected?
下拉框能隐藏

### What is actually happening?
下拉框依然显示

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
