### ISSUE TITLE
[Bug Report] "v-model" vs ":value" behaviors

### ISSUE THREAD

**Issue by alexandretperez** [ElemeFE/element#14389]
### Element UI version
2.5.4

### OS/Browsers version
Windows 10 / Chrome 72

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/alexandretperez/sz539f7k](https://jsfiddle.net/alexandretperez/sz539f7k)

### Steps to reproduce
Components seems to work only with "v-model". Setting a :value instead, breaks the component behavior.

If we set :value in el-input, we can't type anything.

If we set :value in el-select, we can't change the selection value. The same applies to el-date-picker.

There are some situations where we use :value instead of v-model as described here #14344

### What is Expected?
The components with :value should allow its value to be changed.

### What is actually happening?
The components ignores or blocks the changes.

**Comment by wacky6** [comment]
This is intentional.

If you do not handle input event, the value you see on page is only kept in DOM, but not saved to Vue component’s state. So you never know the actual state of DOM.

Component will only show the bounded value. This is also called controlled component / single source of truth.
