### ISSUE TITLE
[Feature Request] Update documentation with SCSS On Demand Load

### ISSUE THREAD

**Issue by scriptxotic** [ElemeFE/element#14388]
### Existing Component
Yes

### Component Name
SCSS

### Description
Seems like it's possible to load SCSS on demand with `babel-plugin-component` :

```js
  // in .babelrc or babel.config.js

  plugins: [
    [ "component", {
      libraryName: "element-ui",
      ext: ".scss",
      styleLibraryName: "../packages/theme-chalk/src"
    }]
  ]
```

Should I worry about it to change in any future release ?

Using this trick, it's even possible to use SCSS variable (to change color) [using `data` option of `sass-loader`](https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders)

Is it possible to document it ?

http://element.eleme.io/#/en-US/component/quickstart#import-element

http://element.eleme.io/#/en-US/component/custom-theme#update-scss-variables-in-your-project

Linked issue : #9842

Thanks

**Comment by iamkun** [comment]
This is an advanced usage with https://github.com/ElementUI/babel-plugin-component plugin.

We might don't have to mention this in Element project.

**Comment by franciscolourenco** [comment]
Only found how to do this through here. Was about to open a ticket requesting docs. @scriptxotic is this still working?

**Comment by scriptxotic** [comment]
Yes it might be, as long as they keep the same relative directory for theme-chalk sources:
https://github.com/ElemeFE/element/tree/master/packages/theme-chalk/src
