### ISSUE TITLE
[Bug Report] slot-scope does not update when paginating table

### ISSUE THREAD

**Issue by mikemand** [ElemeFE/element#14383]
### Element UI version
2.5.4

### OS/Browsers version
macOS Mojave Version 10.14.3 (18D109) / Google Chrome Version 71.0.3578.98 (Official Build) (64-bit), but also tested on Windows 10 with Chrome and Edge.

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/cyk3t2ng/28/](https://jsfiddle.net/cyk3t2ng/28/)

### Steps to reproduce
When updating the data bound to a table (usually from pagination), the slot scope doesn't appear to be updated for the first column of the table. If you paginate in my included fiddle, you'll notice that the first column containing a thumbnail is never updated, but the file name (and associated style - folder vs file) in the second column is updated. Likewise, any additional columns (my real table has two more columns, one for a created_at date and another for action buttons) are updated as well.

### What is Expected?
The first column of a table should have its slot scope updated.

### What is actually happening?
The slot scope is not updated so thumbnails, etc. still display the previous page's icons/thumbnails.

**Comment by iamkun** [comment]
Thumbnails look ok on my side. Try update you demo, please.

**Comment by mikemand** [comment]
The demo is using the latest version available since it is pulled from Unpkg's CDN.

If you go to the second page, the top four entries should have thumbnails of IMAGES, but instead, they are like this:

<img width="306" alt="screen shot 2019-03-05 at 9 20 43 am" src="https://user-images.githubusercontent.com/745184/53819945-25fba000-3f28-11e9-8a25-090a71364982.png">

**Comment by nWidart** [comment]
Any update on this @iamcsk ?
