### ISSUE TITLE
[Feature Request] CDN introduces elements to do PC-side projects. When refreshing, there is half a second of page confusion. How to deal with it?

### ISSUE THREAD

**Issue by BruceFeng518** [ElemeFE/element#14387]
### Existing Component
No

### Component Name
no

### Description
cdn 引进element,做PC端项目， 刷新时有半秒时间页面出现错乱，如何处理？

**Comment by advsets** [comment]
Make a state of the loading process，wait until all the resources of the element are loaded before displaying the page

---

做一个加载过程中状态，等待element的全部资源加载完毕再显示页面
