### ISSUE TITLE
[Bug Report] el-select multiple-choice, in the case of many selected items, when the model object is reset to an empty array, a carton appears

### ISSUE THREAD

**Issue by jiaotashidi** [ElemeFE/element#14382]
### Element UI version
2.4.6

### OS/Browsers version
win7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/DAGWJ/yu3kr5gz/8/](https://jsfiddle.net/DAGWJ/yu3kr5gz/8/)

### Steps to reproduce
1: 点击下拉框
2: 点击下拉框的全选按钮（点击后，所有项被选中）
3: 点击清空按钮（此刻出现卡顿，input中所展示的tag形式的已选项，并未立即清空）

### What is Expected?
当步骤三点击清空按钮时，input中所罗列的已选中的项，立即清空

### What is actually happening?
点击清空按钮，input中所展示的tag形式的已选项，并未立即清空, 出现过一会才清空，当选中的数据量大的情况下，会出现该现象，选中的数据量少的情况下不会出现

**Comment by iamkun** [comment]
pr welcomed
