### ISSUE TITLE
[Bug Report] Official consideration: The title of the Dialog component should have the title attribute

### ISSUE THREAD

**Issue by summerhll** [ElemeFE/element#14395]
### Element UI version
2.5.4

### OS/Browsers version
win10 /google浏览器

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
使用element ui 的dialog组件做弹窗，发现dialog的title没有设置title属性。导致当title过长时，用样式设置以省略号方式显示时，用户将看不到完整的title名称。
希望可以在dialog的title上面设置title属性，这样显示省略号时，鼠标移上去能让用户看到完整的title名称。

### What is Expected?
可以在dialog的title上面设置title属性，这样显示省略号时，鼠标移上去能让用户看到完整的title名称。

### What is actually happening?
目前在dialog的title上面没有设置title属性。导致当title过长，用样式设置以省略号方式显示时，用户将看不到完整的title名称。

**Comment by summerhll** [comment]
这个issue没有预览链接。这是个简单呢的组件bug问题，没有提供预览链接。 上面的预览链接是随便写的，不用看了。

**Comment by iamkun** [comment]
pr welcomed
