### ISSUE TITLE
[Bug Report] Version 2.5.0 with trim modifiers can no longer enter spaces when entering

### ISSUE THREAD

**Issue by fengcaian** [ElemeFE/element#14390]
### Element UI version
2.5.4

### OS/Browsers version
windows10/chrome71.0.3578.98

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/can_f/odfqcn6k/2/](https://jsfiddle.net/can_f/odfqcn6k/2/)

### Steps to reproduce
输入框输入中文或英文字符后，无法输入空格。

### What is Expected?
期待像2.4.11版本及其以前那样，在提交表单获取输入值的时候再进行去除空格操作，而不是在输入的时候就进行，因为有些输入内容是需要在文本内容中存在空格的，比如英语句子，或者存在多个搜索条件的时候，考虑用户操作习惯，一般用空格隔开更为方便。

### What is actually happening?
输入的时候已无法输入空格

**Comment by iamkun** [comment]
@wacky6  我们上次改动需要考虑这个情况吗

**Comment by wacky6** [comment]
文档已经加了不支持v-model修饰器了。以后组件都改成受控了， .trim/.number 在change里自行处理。

并且.trim / .number并不保证js拿到的数据一定符合要求，还会让dom与js不一致。

**Comment by iamkun** [comment]
恩 ok

**Comment by fengcaian** [comment]
这个不能向下兼容吗，项目里面用了.trim修饰符的地方得有2000+的地方用到了这个修饰符，改起来太多地方了，而且这个修饰符的表现和vue的表现不一样了，有什么好的办法能解决吗

**Comment by iamkun** [comment]
会在下个大版本重构的 目前请以文档为准吧

**Comment by fengcaian** [comment]
好吧

**Comment by qidaneix** [comment]
1. 应该是小版本向前兼容而不是大版本向前兼容吧。莫非可以从2.x.x版本升级到3.x.x版本？
2. 方便问一下这里为何要如此修改吗？和vue的.trim修饰符的默认表现形式也不一样了
3. 如果没法实现向前兼容的话，有什么解决方案吗？还是只能锁死2.4.x的版本？

**Comment by wacky6** [comment]
change 事件里面处理。trim用string.trim，number用parseFloat/number，可参考vue源码。但为了严谨建议自行封装函数处理无效输入。

就我理解vue文档，修饰符从没说可以用自定义组件上。另外vue的修饰器看起来能工作是因为vue不要求输入框受控（dom状态可以和组件状态不一致）。有兴趣可以在原生输入框上用修饰器，同时看绑定值。也可以试试antd/react里面只绑定value不处理onChange，这种情况下react会拒绝输入的。

另外，modifier并不会强制清除无效值，用户可以在v-model.number的输入框里输入abc，并且js拿到的值也是abc。这看起来不符合把输入转换成数字的逻辑。

但是对于组件来说，允许DOM状态与js状态不一致并不合适。例如不绑定v-model/不处理input事件依然可以往输入框输入内容，这并不合适。这样的情况下js无法确切获知用户看到的内容是什么。

不想改代码，锁2.4。想改：参照第一段。另外，以后所有组件都会往受控的方式上改。

**Comment by qidaneix** [comment]
@wacky6 好的，谢谢回复！
