### ISSUE TITLE
[Bug Report] el-input by Chinese Chinese type input method, will enter into pinyin

### ISSUE THREAD

**Issue by chenchao2016** [ElemeFE/element#14406]
### Element UI version
2.5.4

### OS/Browsers version
Windows 7 /  Chrome/ 39.0.2171.95

### Vue version
2.6.6

### Reproduction Link
[https://codepen.io/chenchao2016/pen/rPPGvM](https://codepen.io/chenchao2016/pen/rPPGvM)

### Steps to reproduce
在低版本Chrome浏览器（39.0）环境下，通过搜狗或者百度输入法在 el-input 输入框中输入汉字。

### What is Expected?
在 el-input 中写入拼音对应的汉字

### What is actually happening?
在 el-input 中写入了输入法拼写的拼音和对应的汉字

**Comment by bxfxf** [comment]
我也遇到了这个问题，2.4.11版本没问题，从2.5.0版本之后就有问题了

**Comment by wacky6** [comment]
试试这个 https://jsfiddle.net/da40mcgq/

**Comment by chenchao2016** [comment]
> 我也遇到了这个问题，2.4.11版本没问题，从2.5.0版本之后就有问题了

是的，需要降版，最新版本会有这个问题

**Comment by iamkun** [comment]
v-model please

**Comment by chenchao2016** [comment]
> v-model please

高版本下的这个问题修复了是吧 ？

**Comment by bxfxf** [comment]
> v-model please

与v-model有关系？使用了v-model，请问有什么需要注意的吗

**Comment by liwenda122** [comment]
WIN10 +IE11下，el-input组件， 微软中文输入法和搜狗输入法都无法正常输入中文
这么随意就关闭bug了？v-model please ？什么鬼
