### ISSUE TITLE
[Bug Report] CSS not fully applied (to fonts at least)

### ISSUE THREAD

**Issue by wsw70** [ElemeFE/element#14403]
### Element UI version
2.5.4

### OS/Browsers version
Chrome 72

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/WoJWoJ/x37ksar2/](https://jsfiddle.net/WoJWoJ/x37ksar2/)

### Steps to reproduce
The basic app linked above displays a named input field

### What is Expected?
That the font used in the description (`label`) follows the typography of Element

### What is actually happening?
The font used is the fallback serif font of the browser

**Comment by iamkun** [comment]
the typography in Element is just a design suggestion instead of a provided font.

**Comment by wsw70** [comment]
@iamkun ok I understand, thanks. Is there a way to force a `font-family` globally, then?
