### ISSUE TITLE
[Bug Report] pagination component 'current-change' event is work failed when I press enter key second time in IE11

### ISSUE THREAD

**Issue by liuqian1996** [ElemeFE/element#14407]
### Element UI version
2.4.9

### OS/Browsers version
windows 10 IE 11

### Vue version
2.5.10

### Reproduction Link
[https://user-images.githubusercontent.com/11707934/52988535-9ee3fd80-343a-11e9-89a4-7325904d0d76.gif](https://user-images.githubusercontent.com/11707934/52988535-9ee3fd80-343a-11e9-89a4-7325904d0d76.gif)

### Steps to reproduce
The first time I type 3, press enter key, I can listen to the currentPage change, the currentPage is 3 now,
then type 1, press enter key, I can not listen to the currentPage change, and type any number of page, the currentPage is always 3.

### What is Expected?
When I type 1, the currentPage should be 1, not 3.

### What is actually happening?
When I type 1, the currentPage is always 3, not 1 I expected.

**Comment by ziyoung** [comment]
not element bug. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15181565/

**Comment by ziyoung** [comment]
Pr welcome

**Comment by liuqian1996** [comment]
@ziyoung Thank you
