### ISSUE TITLE
[Bug Report] Reactivity is broken on tabs label

### ISSUE THREAD

**Issue by invisor** [ElemeFE/element#14404]
### Element UI version
2.5.4

### OS/Browsers version
Windows 10 / Chrome 72.0.3626.109

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/4aLnkqwz/](https://jsfiddle.net/4aLnkqwz/)

### Steps to reproduce
I want to update counter in tabs dynamically but it not works. Just click button from reproduction link

### What is Expected?
The counter in tab label should increase

### What is actually happening?
The counter in tab label not increase

**Comment by invisor** [comment]
Any ideas? Or maybe quick workaround?

**Comment by invisor** [comment]
Simple workaround is add :key parameter to each el-tab-pane. Value of :key is incremented variable

**Comment by ziyoung** [comment]
Duplicate of #14351

**Comment by ziyoung** [comment]
pr #14496
