### ISSUE TITLE
[Bug Report] Tab active bar doesn't resize when tab label changes dynamically

### ISSUE THREAD

**Issue by akki-jat** [ElemeFE/element#14416]
### Element UI version
2.5.4

### OS/Browsers version
Windows 7 / Chrome 72.0.3626.109

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/akki_jat/quce1ntd/2/](https://jsfiddle.net/akki_jat/quce1ntd/2/)

### Steps to reproduce
Just run jsfiddle and observe

### What is Expected?
Resize the tab active bar as label changes dynamically

### What is actually happening?
Tab active bar is not resizing as label changes dynamically

**Comment by jri** [comment]
This is another minimal demo that illustrates that very problem:
https://codepen.io/jri/pen/ZwgYJL

After 3 seconds it changes the label of the first tab dynamically. Element UI does not recalculate the position of the active bar.

Observations:
2.4.11 -- everything works fine
2.5.0 -- no active bar is shown at all
2.5.1 -- no active bar is shown at all
2.5.2 -- no active bar is shown at all
2.5.3 -- active bar is shown, but position is not recalculated
2.5.4 -- active bar is shown, but position is not recalculated

**Comment by jri** [comment]
Update: the problem is still there in 2.6.0 and 2.6.1
