### ISSUE TITLE
Upload upload component problem

### ISSUE THREAD

**Issue by sunershengCS** [ElemeFE/element#14414]
### Existing Component
Yes

### Component Name
el-upload

### Description

在v-for循环，对每个item项都能自定义选择不同的文件，此时我们肯定需要传递item到回调钩子函数中，且能访问原来默认的参数，目前无法这样操作。 比如文件选择改变后的回调事件on-change，目前只能这样   :on-change="handleFileChange"   
      
handleFileChange(file, fileList) {   //  }；

我们希望应该是这样的：
:on-change="handleFileChange(item)"  

handleFileChange(file, fileList,item) {   
   //一些对文件file的处理，比如本地读取文件内容，然后把内容赋给item；
 }；

**Comment by wangyunhang** [comment]
upload 没有选取文件之前的钩子函数吗。

**Comment by flyfly6** [comment]
我也遇到了同样的问题，我是这样处理的
```html
<el-upload :on-change="handleFileChange(item)"></el-upload>
```
```javascript
handleFileChange(file, fileList, item) {
  return function (file, fileList) {
    console.log(file, fileList, item);
    // Some processing of file and item
  }
}
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
