### ISSUE TITLE
[Bug Report] el-table-column rerender issue

### ISSUE THREAD

**Issue by askart** [ElemeFE/element#14417]
### Element UI version
2.4.11

### OS/Browsers version
Google Chrome / 72.0.3626.109 (Official Build) (64-bit)

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/askart/3s4v5nj1/](https://jsfiddle.net/askart/3s4v5nj1/)

### Steps to reproduce
Toggle checkboxes to see changes. In 1st table columns from a to e is ok except c. by clicking c1 or c2 column e will disappear.

### What is Expected?
if you click c1 then c1 should disappear

### What is actually happening?
by clicking c1 disappears e

**Comment by askart** [comment]
i saw source code for [table-column](https://github.com/ElemeFE/element/blob/v2.4.11/packages/table/src/table-column.js), but i coudn't find any difference between normal and nested ElTableColumn.
this is the minimal implementation but without element-ui [codesandbox](https://codesandbox.io/s/6l083pqk1n?fontsize=14&module=%2Fsrc%2FApp.vue)

**Comment by lwxbr** [comment]
I have this problem too, I work with many cruds and I reuse the table component multiple times. When I use a condition to render a column (for example , the column of selection, there are tables that use selection and others that don't), there are times the last column goes to the first. I also saw this behavior in the example you showed.
