### ISSUE TITLE
[Bug Report] el-input-number replicated values are inconsistent with the original values

### ISSUE THREAD

**Issue by Laipt** [ElemeFE/element#14420]
### Element UI version
2.4.11

### OS/Browsers version
Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Lphywe9k/](https://jsfiddle.net/Lphywe9k/)

### Steps to reproduce
在输入框中输入347639489124494888
失去光标后值变成了347639489124494900

### What is Expected?
在输入框中输入347639489124494888
失去光标后值变成了347639489124494888
保持值一致

### What is actually happening?
在输入框中输入347639489124494888
失去光标后值变成了347639489124494900
值发生了改变

**Comment by wacky6** [comment]
浮点数超范围。 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by xianshenglu** [comment]
@wacky6 , I think we need a warning for developer in `el-input-number` component because of the `MAX_SAFE_INTEGER`.

**Comment by wacky6** [comment]
Good point. PR Welcome.
