### ISSUE TITLE
[Bug Report] Support for Component Buried Points

### ISSUE THREAD

**Issue by my9074** [ElemeFE/element#14421]
### Element UI version
2.5.4

### OS/Browsers version
chrome 60 

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/8qacb3n2/1/](https://jsfiddle.net/8qacb3n2/1/)

### Steps to reproduce
由于业务有埋点的需求，且埋点的方案采用通过在 html 标签上自定义 attribute (etc. class-tag="xxx")  的形式采集。但是由于组件 ( etc. tabs, table ) 经过解析后，自定义的 attribute 无法 append 到真实的标签上，导致埋点无法采集。请问有没有方案，类似通过 html 的 data-attribute 这种属性，通过某种逻辑 append 到真实的 dom 元素

![image](https://user-images.githubusercontent.com/4555635/53064124-9a364c80-3501-11e9-891a-f9e10c6332d7.png)

 `class-tag` 没有 append 到真实的 html 标签上。

### What is Expected?
Tabs 等交互组件支持 class ，id 埋点

### What is actually happening?
由于业务有埋点的需求，且埋点的方案采用通过在 html 标签上自定义 attribute (etc. class-tag="xxx")  的形式采集。但是由于组件 ( etc. tabs, table ) 经过解析后，自定义的 attribute 无法 append 到真实的标签上，导致埋点无法采集。请问有没有方案，类似通过 html 的 data-attribute 这种属性，通过某种逻辑 append 到真实的 dom 元素

**Comment by iamkun** [comment]
建议手动调用js埋点
