### ISSUE TITLE
The Select selector jitters when the browser scales over a certain number of rows

### ISSUE THREAD

**Issue by qssjtzj** [ElemeFE/element#14425]
### Element UI version
2.5.4

### OS/Browsers version
win7/ Google Chrome  版本 72.0.3626.109（正式版本） （32 位）

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/qssjtzj/sz8geyth/2/](https://jsfiddle.net/qssjtzj/sz8geyth/2/)

### Steps to reproduce
1、访问https://jsfiddle.net/qssjtzj/sz8geyth/2/
2、浏览器缩放调整到110%
3、Select多选组件选择内容超过4行或6行
4、input框高度出现1像素的抖动

### What is Expected?
浏览器缩放后，组件不出现抖动（组件高度一直变化）

### What is actually happening?
浏览器缩放时Select选择器多选超过4行/6行出现抖动

**Comment by iamkun** [comment]
官方不支持缩放
