### ISSUE TITLE
[Bug Report] When there is a fixed column in the table and the table in the expanded row sets max-height, it cannot slide properly.

### ISSUE THREAD

**Issue by zhangtaoBqteam** [ElemeFE/element#14439]
### Element UI version
0.1.0

### OS/Browsers version
68.0.3440.106

### Vue version
2.6.6

### Reproduction Link
https://jsfiddle.net/eb4o0h7w/

### Steps to reproduce
展开第一行数据，点击展开行下面的表格右侧的下拉条

### What is Expected?
展开行中table的所有数据随下拉条滑动而滑动

### What is actually happening?
展开行中table的商品ID一栏并没有随下拉条进行滑动

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
