### ISSUE TITLE
[Feature Request] DatePicker date selector, how to select a date in a specified date list

### ISSUE THREAD

**Issue by zhangtaoBqteam** [ElemeFE/element#14435]
### Existing Component
是

### Component Name
DatePicker

### Description
现在有一个日期列表，是一个数组，数组中有可以选择的日期，现在我想用DatePicker组件，仅在日期列表中的日期可以选择，其他日期都为disabled，我尝试用过picker-options中的disabledDate，如下所示：
disabledDate: (time) => {
          let date = moment(time.getTime()).format('YYYY-MM-DD')
          return this.avaiableDateList.indexOf(date) === -1;
 }
但是出现了报错，麻烦告知一下这种情况利用DatePicker组件可以实现吗

**Comment by JJLao** [comment]
能提供一下解决办法吗？

**Comment by zhangtaoBqteam** [comment]
> 能提供一下解决办法吗？
availableDateList 是可用的日期列表
disabledDate: (time) => {
          let date = moment(time).format('YYYY-MM-DD')
          return !this.availableDateList.includes(date);
 }

**Comment by JJLao** [comment]
@zhangtaoBqteam 非常感谢！
