### ISSUE TITLE
[Feature Request] Option to use margin instead of padding on tree-nodes

### ISSUE THREAD

**Issue by BlitZz96** [ElemeFE/element#14431]
### Existing Component
Yes

### Component Name
Tree

### Description
When using borders on the tree, the padding creates an unwanted effect where you cannot see the indentation correctly.

On the example below, you see the wanted use case.
`phase 3` is how the tree behaves today using padding. (what I would like to overwrite)
![](https://i.imgur.com/8WBGVqA.png)

### Request:
 Attribute to optionally use margin-left for indentation instead of padding-left
example: 

```HTML
<el-tree data="..." indent-margin ></el-tree>
```

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.

**Comment by BlitZz96** [comment]
Thank you for reviewing.
