### ISSUE TITLE
编译默认主题时报错

### ISSUE THREAD

**Issue by AnewG** [ElemeFE/element#1443]
按照 [自定义主题文档](http://element.eleme.io/#/zh-CN/component/custom-theme) 执行到 编译主题 部分。

执行命令报错

<pre>
build theme font
build element theme

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/Homestead/static/element/element-starter/node_modules/element-theme-default/src/vue-popup/lib/popup.css'
    at Error (native)
</pre>

vue-popup 位于 `/Homestead/static/element/element-starter/node_modules/element-theme-default/node_modules/vue-popup` 中，手动拷贝文件到出错提示目录下编译正常。

请问是bug还是文档有误？

**Comment by Leopoldthecoder** [comment]
按道理 `@import 'vue-popup/lib/popup.css'` 后应该从 node_modules 里找，但是似乎有一些用户用了后文件是从相对路径找的，所以会提示文件不存在。暂时先手动移动一下吧，具体原因我们后面研究一下。
