### ISSUE TITLE
[Bug Report] while using the button group with only one button in plain style, the left and right border is transparent

### ISSUE THREAD

**Issue by VanFangbo** [ElemeFE/element#14436]
### Element UI version
2.5.4

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/1dwjzyu8/](https://jsfiddle.net/1dwjzyu8/)

### Steps to reproduce
1.input a button group and then create a button with 'plain' style

2.the left and right border is transparent

I've checked the css, only one plain button in a button group is the first child and also the last child. So the style set the left and right border color is transparent in 0.5. These two style occur each other to make this wrong style.

So, I suggest the style: .el-button-group .el-button--primary:last-child & .el-button-group .el-button--primary:first-child also set the other border color in the color suit for the button type with '!important'. It will make the button group to show more better. Like this: https://jsfiddle.net/rg2dyhou/1/

### What is Expected?
the only one plain button in a button group has left and right border color

### What is actually happening?
it has only transparent border color

**Comment by iamkun** [comment]
> only one plain button in a button group

Do not do like this
