### ISSUE TITLE
[Bug Report] the scrollbar position of table changed after tab changed

### ISSUE THREAD

**Issue by wuchuanxun** [ElemeFE/element#14433]
### Element UI version
2.5.4

### OS/Browsers version
win10

### Vue version
2.6.5

### Reproduction Link
[https://jsfiddle.net/wuchuanxun/oukqrzhc/7/](https://jsfiddle.net/wuchuanxun/oukqrzhc/7/)

### Steps to reproduce
1. scroll to the end on first tab page
2. switch to the second tab page
3. switch back to the first tab page
4. change element-ui version to 2.0.11 and repeat the steps before

### What is Expected?
table can keep the scrollbar position unchanged

### What is actually happening?
with element-ui version 2.5.4, the scroll bar scroll to the beginning when tabs changed. but there is no problem with element-ui version 2.0.11, the problem may lies in resize-event.js

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
