### ISSUE TITLE
[Bug Report] Cannot load fonts from another parent domain. My CDN is not my domain.

### ISSUE THREAD

**Issue by JessicaSachs** [ElemeFE/element#14446]
### Element UI version
2.5.4

### OS/Browsers version
Chrome latest

### Vue version
2.6.6

### Reproduction Link
This hard to do, because it requires multiple domains

### Steps to reproduce
1. Create a Vue project that uses Element-UI
2. Embed your projects' javascript on another website (this is hard to show in a Github project or fiddle)
3. Fonts are loaded from `anotherWebsite.com/fonts/element-icons.woff`, which does not exist.

Trying to set $--font-path to an absolute url does not fix it, since it's wrapped in a `__webpack_require__` and wants a local file path.

### What is Expected?
I want to be able to hardcode an absolute url to my icon font or to ignore the element-icons file so I can pass my own in.

### What is actually happening?
I am unable to load any fonts because I do not host my CDN on the root domain of the website that's executing Element-UI.

**Comment by iamkun** [comment]
Not sure, maybe `gulp-replace` suits your need.

**Comment by ikasianiuk** [comment]
hi @JessicaSachs. I understand that this issue is quite old, but currently I face the same one. Maybe by any chance you remember if you have resolved it and how?
