### ISSUE TITLE
能否使用requirejs 或dojo 引入element-ui

### ISSUE THREAD

**Issue by binghuan123** [ElemeFE/element#1444]
使用requirejs 引入vuejs使用没有问题，但是引入element-ui一直都报没有注册组件。
是不支持使用requirejs引入么？

**Comment by QingWei-Li** [comment]
打包后是 umd 和 commonjs 两个版本，requirejs 好像只支持 amd？

**Comment by Kingwl** [comment]
有umd版本。。。当然支持amd

**Comment by binghuan123** [comment]
请问怎么获取umd版本，rquirejs配置的时候需要特别注意什么？我使用requirejs能够从服务器端下载到elementui，就是组件不能使用。

**Comment by Geek-Arno** [comment]
能不用@符号吗?   ＭＶＣ的@符号有特殊意义！！！

**Comment by binghuan123** [comment]
@Geek-Arno  @符号是v-on的简写呀，使用v-on，不在cshtml中写@就没事，脚本、模板html文件中写都没事。

**Comment by QingWei-Li** [comment]
@binghuan123 `element-ui/lib/index.js` 就是 umd 的

**Comment by binghuan123** [comment]
@QingWei-Li 我用requirejs引入这个文件以后，一直都提示elementui的组件未注册，不能使用啊。而且这个文件是有从服务器端下载过来的。

**Comment by binghuan123** [comment]
原来是require配置element-ui的时候出的问题，element-ui使用的是具名模块，所以配置的时候name必须和模块里面定义的名字一样。在packages中配置为{
                name : "ELEMENT",
                location :"elementui",
                main : "index"
            }
就可以正常引用了。

**Comment by mydaoyuan** [comment]
require(['vue', 'ELEMENT'], function(Vue, ELEMENT) {
  ELEMENT.install(Vue);
}

必须是要ELEMENT

**Comment by KromaLee** [comment]
requirejs能做到按需引入组件吗?
