### ISSUE TITLE
[Bug Report] Time selector cannot get the time of time panel selection with only value

### ISSUE THREAD

**Issue by HuDaHei** [ElemeFE/element#14440]
### Element UI version
2.5.4

### OS/Browsers version
Windows7/谷歌浏览器版本 71.0.3578.98（正式版本） （64 位）

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/gje4wp8u/1/](https://jsfiddle.net/gje4wp8u/1/)

### Steps to reproduce
点击时间面板的时间 ， 时间日期无法获取

### What is Expected?
通过change事件可以获取时间面板返回的时间

### What is actually happening?
change事件不起作用

**Comment by PeanutWatson** [comment]
I think it is not a bug. Your code on "https://jsfiddle.net/gje4wp8u/1/" binding the data property "value3" by a property named value, should binding by v-model.  like `<el-date-picker
      v-model="value3"
      type="month"
      placeholder="选择周">
    </el-date-picker>`
![image](https://user-images.githubusercontent.com/6223177/53175822-c3e99380-3627-11e9-8c01-adfee5c5751a.png)

**Comment by wacky6** [comment]
See https://github.com/ElemeFE/element/issues/14440#issuecomment-466018880
