### ISSUE TITLE
[Feature Request] Select: preserve placeholder after value was added

### ISSUE THREAD

**Issue by arthabus** [ElemeFE/element#14444]
### Existing Component
Yes

### Component Name
Select with filtering (http://element.eleme.io/#/en-US/component/select)

### Description
Is it possible to add placeholder and to make sure it's showing even after user added values to the select element?

I'm looking to add functionality where user can add people to share their content with, so placeholder goes like "Add more people".
They start to type and they pick a person from a suggested dropdown. Now they can do the same thing again and I want them to still see the "Invite more people" hint next to the selected value.

As an example, here is the Google Drive share function where they have this exact flow:
![screen shot 2019-02-21 at 12 56 49 pm](https://user-images.githubusercontent.com/8145834/53167436-35015a80-35d8-11e9-9eb5-6ba12490288f.png)

How can I to achieve this behavior?

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
