### ISSUE TITLE
[Bug Report] Multi-select table style emptying failed

### ISSUE THREAD

**Issue by weijiyang** [ElemeFE/element#14455]
### Element UI version
2.5.4

### OS/Browsers version
macOS High Sierra 版本 10.13.3 (17D47) / Google Chrome 版本 72.0.3626.109（正式版本）

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/weijiyang/hjc86a5r/138/](https://jsfiddle.net/weijiyang/hjc86a5r/138/)

### Steps to reproduce
Click the Select All button and then call the clearSelection method. The Select All button style is not reset.

### What is Expected?
Restore all button styles to unchecked styles

### What is actually happening?
The selection button style has not changed

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
