### ISSUE TITLE
菜单组件运行有vue的警告

### ISSUE THREAD

**Issue by Leungkingman** [ElemeFE/element#1446]
![qq20161129-1](https://cloud.githubusercontent.com/assets/16955472/20695804/aaa69baa-b629-11e6-9d40-fe0f53019945.png)
![qq20161129-0](https://cloud.githubusercontent.com/assets/16955472/20695816/c1c22656-b629-11e6-85a2-0eb967c6da6e.png)
![qq20161129-2](https://cloud.githubusercontent.com/assets/16955472/20695817/c2d21416-b629-11e6-9ab9-ad6b5ce4cd0b.png)
请问这个问题应该怎么解决？

**Comment by esmeetu** [comment]
`.$mount('App')`这样写对吗？不是`.$mount('#app')`?

**Comment by Leopoldthecoder** [comment]
这是因为你的 components 里有 `Menu`，而它是个原生标签。换个名字就好：
```javascript
components: {
  'el-menu': Menu
}
```

另外，你在入口文件全局引入了 Element，其实不需要在单个页面文件里再引入一遍。
