### ISSUE TITLE
[Feature Request] As of Dart Sass 2.0.0, !global assignments won't be able to

### ISSUE THREAD

**Issue by iTaster** [ElemeFE/element#14465]
### Existing Component
Yes

### Component Name
popper select-dropdown select pagination input

### Description
`69% building 705/715 modules 10 active ...core-js\library\modules\_object-gops.jsDEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$B: null` at the top level.

   ╷
71 │   $B: $namespace '-' $block !global;
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 71:3   b()
    node_modules\element-ui\packages\theme-chalk\src\popper.scss 4:1           @import
    node_modules\element-ui\packages\theme-chalk\src\select-dropdown.scss 3:9  @import
    node_modules\element-ui\packages\theme-chalk\src\select.scss 4:9           @import
    node_modules\element-ui\packages\theme-chalk\src\pagination.scss 4:9       @import
    node_modules\element-ui\packages\theme-chalk\src\index.scss 2:9            @import
    stdin 8:9                                                                  root stylesheet

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$E: null` at the top level.

   ╷
79 │   $E: $element !global;
   │   ^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 79:3  e()
    node_modules\element-ui\packages\theme-chalk\src\input.scss 10:3          @content
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 74:5  b()
    node_modules\element-ui\packages\theme-chalk\src\input.scss 4:1           @import
    node_modules\element-ui\packages\theme-chalk\src\select.scss 5:9          @import
    node_modules\element-ui\packages\theme-chalk\src\pagination.scss 4:9      @import
    node_modules\element-ui\packages\theme-chalk\src\index.scss 2:9           @import
    stdin 8:9                                                                 root stylesheet`

**Comment by evans-kim** [comment]
same here..

DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$E: null` at the top level.

   ╷
79 │   $E: $element !global;
   │   ^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/element-ui/packages/theme-chalk/src/mixins/mixins.scss 79:3  e()

**Comment by manier13579** [comment]
me too
![error screenshot](https://user-images.githubusercontent.com/23184014/53494407-a5c4dd00-3ad8-11e9-8a7f-de06c6fc215e.png)

**Comment by fumeiyu** [comment]
me too ，怎么解决呢

**Comment by Lalrinfela** [comment]
Lets make it work soon!!

**Comment by LAINE001** [comment]
me too , but it does't affect the use of .
