### ISSUE TITLE
[Bug Report] Nuxt Pagination validateState was assigned to but it has no setter

### ISSUE THREAD

**Issue by zek** [ElemeFE/element#14467]
### Element UI version
2.5.4

### OS/Browsers version
Mac OS X / Chrome

### Vue version
2.6.7

### Reproduction Link
[https://github.com/njleonzhang/vue-data-tables/issues/211](https://github.com/njleonzhang/vue-data-tables/issues/211)

### Steps to reproduce
~~~
  <el-pagination layout="prev, pager, next, jumper, sizes, total"></el-pagination>
~~~

### What is Expected?
No warning

### What is actually happening?
[Vue warn]: Computed property "validateState" was assigned to but it has no setter.

found in
<ElInput> at packages/input/src/input.vue
       <Jumper>
         <ElPagination>

**Comment by ziyoung** [comment]
```js
validateState() {
   return this.elFormItem ? this.elFormItem.validateState : '';
}
```
If you don't put ElInput in ElForm, `validateState` will be empty. I think it's not a bug of Element.

**Comment by olaleye247** [comment]
Hello @ziyoung I am getting the same error using element-ui's select component. How do I go about fixing it please.
