### ISSUE TITLE
[Bug Report] el-slider can't work accurately after scaled

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#14476]
### Element UI version
the newest

### OS/Browsers version
all

### Vue version
the newest

### Reproduction Link
https://jsfiddle.net/jonkee/4teugnkf/8/

### Steps to reproduce
1. drag the controller
2. the controller won't follow the cursor, it is always behind the cursor.

### What is Expected?
even it has been scaled, I hope the controller can follow the cursor accurately

**Comment by iamkun** [comment]
the scale is not supported, pr welcomed
