### ISSUE TITLE
[Bug Report] $attrs is readonly. | el-time-picker type="fixed-time"

### ISSUE THREAD

**Issue by t1gu1** [ElemeFE/element#14474]
### Element UI version
2.5.4

### OS/Browsers version
Windows 10, Chrome, Electron

### Vue version
2.6.7

### Reproduction Link
[https://github.com/t1gu1/Electron-Element-UI-VueJs-Nuxt-architecture-style/blob/master/src/renderer/pages/about.vue](https://github.com/t1gu1/Electron-Element-UI-VueJs-Nuxt-architecture-style/blob/master/src/renderer/pages/about.vue)

### Steps to reproduce
git clone: https://github.com/t1gu1/Electron-Element-UI-VueJs-Nuxt-architecture-style
npm install
npm run dev
Go to about page
Use the el-time-picker type="fixed-time" (Time picker)

### What is Expected?
No warning

### What is actually happening?
[Vue warn]: $attrs is readonly.

found in

---> <ElScrollbar>
       <TimeSpinner> at packages/date-picker/src/basic/time-spinner.vue
         <Root>

**Comment by wacky6** [comment]
we don't have `type="fixed-time"`, where do you find such usage?

**Comment by t1gu1** [comment]
Oh, you say true. 😨😅
I just copy paste the code from example on element ui web site.

If find that in the first form code example on this link:
https://element.eleme.io/#/en-US/component/form

![image](https://user-images.githubusercontent.com/12479055/53625681-bf961b00-3bd1-11e9-9d1c-9bb97844b1c9.png)

For me the issue is close.
Thanks

**Comment by wacky6** [comment]
`fixed-time` appears to be typo.

Do you observe this error after removing `type='fixed-time'` ?
