### ISSUE TITLE
[Bug Report] When using tree components, it encountered the wrong problem of dragging level

### ISSUE THREAD

**Issue by xiaoyin199** [ElemeFE/element#14470]
### Element UI version
2.5.4

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/h2vux1e5/1/](https://jsfiddle.net/h2vux1e5/1/)

### Steps to reproduce
节点拖拽操作即可。

### What is Expected?
拖拽后的层级该是多少是多少

### What is actually happening?
例如1层级拖拽的2层架，结果node-drop捕获到的值都还是1，实际上一个是1一个是2了。

**Comment by xiaoyin199** [comment]
没人回答呀

**Comment by ziyoung** [comment]
level 层级在拖拽完成后才会改变。
