### ISSUE TITLE
重置表单出错：Cannot read property 'resetFields' of undefined

### ISSUE THREAD

**Issue by lampo1024** [ElemeFE/element#1447]
### What is actually happening?
重置表单出错：Cannot read property 'resetFields' of undefined,表单是动态创建的，比如：

```
<el-dialog :title="dialogOption.title + dialogOption.block" v-model="dialogOption.visible" size="tiny">
            <el-form ref="formModel" :model="formModel" :rules="rules" label-width="90px">
                <dynamic-form :formModel="formModel" :formFields="formFields" :sources="sources" :rules="rules"></dynamic-form>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button @click.native="handleCancel">取 消</el-button>
                <el-button type="primary" @click.native="submitForm">确 定</el-button>
            </span>
</el-dialog>
```

**Comment by lampo1024** [comment]
刚才又DEGUB了一下，el-dialog组件中动态创建表单元素，如果dialog没有visible出来，
![20161129133112-1](https://cloud.githubusercontent.com/assets/3262079/20697959/76d77e2a-b638-11e6-9ea7-482ffac64122.png)
如果dialog先visible出来，就没有问题，如图：
![20161129133112-2](https://cloud.githubusercontent.com/assets/3262079/20697971/8f2f3512-b638-11e6-9257-19718076e634.png)

**Comment by Leopoldthecoder** [comment]
请给 demo。

**Comment by lampo1024** [comment]
Demo地址:http://jsfiddle.net/yd5gc123/

**Comment by Leopoldthecoder** [comment]
Demo 似乎不太对？Dialog 能弹出，并且代码里没调用 `resetFields`

**Comment by lampo1024** [comment]
@Leopoldthecoder Demo被篡改了？

**Comment by Leopoldthecoder** [comment]
改不了的吧。重新写一个吧。

**Comment by Aprilday** [comment]
是的，我也有这个问题，setTimeout里resetFields一下就没问题，上来直接resetFields就会提示 resetFields not defined.

**Comment by Leopoldthecoder** [comment]
这个 issue 先关掉了。如果能够提供在线 demo，可以再打开。

**Comment by U2Fsd** [comment]
@Leopoldthecoder 
我这边写了个Demo  在点击按钮2  之前  按钮1 会报Cannot read property 'resetFields' of undefined

https://jsfiddle.net/Lucius_Yeh/rapas1pb/

**Comment by jimyong88** [comment]
@U2Fsd 
`
this.$nextTick(()=>{
    this.$refs.ruleForm.resetFields();
 });
`
