### ISSUE TITLE
[Bug Report] Upload File Component Delete Callback Big bug

### ISSUE THREAD

**Issue by javadoge** [ElemeFE/element#14486]
### Element UI version
0.1.0

### OS/Browsers version
win7

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/javadoge/ad4btez2/4/](https://jsfiddle.net/javadoge/ad4btez2/4/)

### Steps to reproduce
读取历史文件记录，同时支持文件上传。
上传新文件后，再操作删除按钮，发现，删除回调方法的 fileList 对象 里面file对象数据格式不一致。

### What is Expected?
删除回调方法  fileList 里面的file对象数据格式一致

### What is actually happening?
删除回调方法  fileList 里面的file对象数据不格式一致。
新上传的文件，删除时，file对象有一个response，而历史数据是纯file对象，没有response

示例数据
2:
busiCode: (...)
fileType: (...)
id: (...)
name: (...)
path: (...)
status: "success"
uid: 1551150023211
url: (...)
__ob__: _e {value: {…}, dep: oe, vmCount: 0}
get busiCode: ƒ ()
set busiCode: ƒ (e)
get fileType: ƒ ()
set fileType: ƒ (e)
get id: ƒ ()
set id: ƒ (e)
get name: ƒ ()
set name: ƒ (e)
get path: ƒ ()
set path: ƒ (e)
get url: ƒ ()
set url: ƒ (e)
__proto__: Object
3:
name: (...)
percentage: (...)
raw: (...)
response: {fileName: "photo.png", code: 0, id: "1337"}
size: (...)
status: (...)
uid: (...)
url: (...)

**Comment by ziyoung** [comment]
这是因为 fileList 前两项已经上传成功了。

**Comment by javadoge** [comment]
是上传成功了，但是这样其它文件操作，还要去判断是上传过的还是刚上传的，感觉比较麻烦，上传的历史文件与刚上传的为什么数据格式不保持一致呢

**Comment by guohuihot** [comment]
多次上传只调用了一次success, fileList里也只有一个里面有response，都没法用了

**Comment by tingwengkei** [comment]
都没有解决问题就close了？？？？？？？
