### ISSUE TITLE
[Bug Report] [Bug Report]'el-time-picker'has a minute style error when the arrow-control property is set, even if the'selectable Range' property is used

### ISSUE THREAD

**Issue by CHANGEX929** [ElemeFE/element#14483]
### Element UI version
0.1.0

### OS/Browsers version
chrome 71.0.3578.98

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/w4p3gn1f/1/](https://jsfiddle.net/w4p3gn1f/1/)

### Steps to reproduce
给el-time-picker组件同时设置arrow-control属性和selectableRange属性
分钟选择器的样式错误，不可选的分钟样式未设置未disabled样式

### What is Expected?
分钟选择器样式为不可选

### What is actually happening?
分钟选择器样式不发生改变

**Comment by CHANGEX929** [comment]
Element UI version=2.5.4

**Comment by iamkun** [comment]
pr welcomed
