### ISSUE TITLE
[Bug Report] After el-tree filtering, the filter condition is cleared and all expansion is not restored.

### ISSUE THREAD

**Issue by AlexZhong22c** [ElemeFE/element#14495]
### Element UI version
2.5.4(这个issue其实和之前的[这个issue](https://github.com/ElemeFE/element/issues/7852)一模一样，只不过是经过fix，到了2.5.4版本还是存在这个问题)

### OS/Browsers version
MacosX 10.12.6 / Chrome

### Vue version
2.5.22

### Reproduction Link
[https://codepen.io/az22c/pen/eXYwgK](https://codepen.io/az22c/pen/eXYwgK)

### Steps to reproduce
在树形结构过滤结点时，清空过滤条件，树形结构的所有结点默认展开了（初始化的时候，是不默认展开的）

### What is Expected?
清空过滤条件，应该要和初始化设置的状态一样，而并非默认展开所有结点

### What is actually happening?
清空过滤条件，默认展开了所有结点

**Comment by AlexZhong22c** [comment]
Old issue doesn't been fixed in Element UI v2.5.4? https://github.com/ElemeFE/element/issues/7852

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.

**Comment by ziyoung** [comment]
子节点只要被匹配到，就会展开。
