### ISSUE TITLE
[Bug Report] [date-range] selecting state should be cleared on button 'clear' clicked

### ISSUE THREAD

**Issue by lianzhao** [ElemeFE/element#14497]
### Element UI version
2.5.4

### OS/Browsers version
macos chrome 72

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/0jh5ewbr/](https://jsfiddle.net/0jh5ewbr/)

### Steps to reproduce
1. click the input to open the date-range selector
2. select start date on the panel (but don't select end date)
3. click 'clear'
4. open the date-range selector again

### What is Expected?
the panel is not in 'selecting' status, `rangeState.selecting` is false

https://github.com/ElemeFE/element/blob/2604c6192f7ec1d8360b4a5c0fc2f447e2df24c1/packages/date-picker/src/panel/date-range.vue#L448

Should do something like `this.rangeState.selecting = false;` here?

### What is actually happening?
the panel is in 'selecting' status, `rangeState.selecting` is true

**Comment by wacky6** [comment]
not reproduced.

![qq20190228-221325](https://user-images.githubusercontent.com/9319556/53562690-26054400-3ba6-11e9-98d4-b60df1de212f.gif)

**Comment by lianzhao** [comment]
![ezgif-4-d4369e13ab35](https://user-images.githubusercontent.com/536786/53580275-332a2f00-3bb6-11e9-94c5-90070be7c15d.gif)
