### ISSUE TITLE
[Bug Report] Table column min-width and width

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#14499]
### Element UI version
2.5.4

### OS/Browsers version
Mac OS, Chrome

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/y59dkswv/](https://jsfiddle.net/y59dkswv/)

### Steps to reproduce
Setting table column width and min-width.

### What is Expected?
If min-width is bigger than width; min-width should be applied.

### What is actually happening?
width is applied. min-width is ignored.

**Comment by ziyoung** [comment]
It's strange. Maybe it's a bug.
