### ISSUE TITLE
表单元素input不能绑定keyup事件

### ISSUE THREAD

**Issue by lampo1024** [ElemeFE/element#1449]
### ElementUI version
 1.0.3 

### What is actually happening?

表单元素input不能绑定keyup等事件

**Comment by ronankim** [comment]
试过`v-on:keyup.enter="doEnter"`不可以

**Comment by lampo1024** [comment]
不可以的，ele官方只提供了click,blur,focus三个事件，完全不能满足需求啊

**Comment by Kingwl** [comment]
请用keyup.native.enter
http://jsfiddle.net/kingwl/zhcchLeq/

**Comment by Leopoldthecoder** [comment]
麻烦提 issue 前读一下 FAQ。
