### ISSUE TITLE
[Bug Report] Popover plus V-model will not be displayed in Table

### ISSUE THREAD

**Issue by lihaotian0607** [ElemeFE/element#14498]
### Element UI version
2.5.4

### OS/Browsers version
Windows NT 10.0 / Chrome 72.0

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/xphyw3L2/](https://jsfiddle.net/xphyw3L2/)

### Steps to reproduce
点击删除本想弹出的 但是无法弹出

### What is Expected?
希望弹出popover

### What is actually happening?
但是没有弹出

**Comment by ziyoung** [comment]
https://jsfiddle.net/q4zxfwod/
