### ISSUE TITLE
Slider组件数值非整

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#1450]
### Reproduction Link
http://jsfiddle.net/erguotou525/tynkpL0n/

### Steps to reproduce
点击加号，到11的时候发现其值为`11.000000000000002`，某些情况下会是`x.99999999999..`

**Comment by Kingwl** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/slider/src/main.vue#L146

这里的浮点运算造成的 然而没什么好的处理方法

**Comment by erguotou520** [comment]
是的，但是对于用户来说这就是Bug

**Comment by Kingwl** [comment]
看他们怎么权衡了

**Comment by Leopoldthecoder** [comment]
Fixed in #1469
