### ISSUE TITLE
[Bug Report] https://elementui.github.io/issue-generator

### ISSUE THREAD

**Issue by EagleWolf** [ElemeFE/element#14504]
### Element UI version
2.5.4

### OS/Browsers version
window10/Chrome版本 71.0.3578.98（正式版本） （64 位）

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/86jvqLba/6/](https://jsfiddle.net/86jvqLba/6/)

### Steps to reproduce
1.NavMenu 导航菜单
2.收起状态
3.放在第一个按钮上面
4.重现内容展示不全

### What is Expected?
列表内容多的情况下出现滚动条，并且top不为负数

### What is actually happening?
top为负数，内容被遮挡住

**Comment by enlicayomer** [comment]
Is there any improvement about this issue ?

![err](https://user-images.githubusercontent.com/19190851/56361540-548bbc80-61f0-11e9-8300-9fcaf3b07d30.png)

**Comment by ziyoung** [comment]
通过 CSS 设置一个最大高度 https://jsfiddle.net/af4s1cmp/
