### ISSUE TITLE
When there is a lot of el-input content under [Bug Report] ie11, the cursor moves to the middle of the content, deletes by delete, and the cursor jumps to the end.

### ISSUE THREAD

**Issue by xvnian** [ElemeFE/element#14501]
### Element UI version
2.5.4

### OS/Browsers version
window7 ie11

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
ie11下el-input内容很多的时候，光标移到内容中间，按delete删除，光标会突然跳到最后面

### What is Expected?
按delete删除，删除后面一个字符

### What is actually happening?
按delete删除，光标会突然跳到最后面

**Comment by wolraich** [comment]
This also happens in Safari 12.0.3 (but not in Chrome)

**Comment by yrq110** [comment]
Maybe you can try to downgrade element-ui version to 2.4.*

**Comment by xvnian** [comment]
> Maybe you can try to downgrade element-ui version to 2.4.*

It's work, thanks

**Comment by wacky6** [comment]
try this fiddle, does it fix the problem? https://jsfiddle.net/da40mcgq/

**Comment by wolraich** [comment]
It works for me, thanks!

**Comment by ColorWolfKing** [comment]
I found that version 2.3.9 was fine and version 2.4.11 had this problem, I tested el-input demo with Safari on the official website.
