### ISSUE TITLE
[Bug Report] el-stpes changes the Process-Status attribute value without any change

### ISSUE THREAD

**Issue by cnscoo** [ElemeFE/element#14502]
### Element UI version
2.5.4

### OS/Browsers version
Microsoft Windows [Version 10.0.17763.316]  - Google Chrome 72.0.3626.109

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/nca8w4v1/](https://jsfiddle.net/nca8w4v1/)

### Steps to reproduce
1. 设置el-steps的当前状态为 processStatus 数据变量，变量默认值为“error"
2. 点击“切换”按钮，改变 processStatus 的值，如果当前为”error“，则更改为”process“，如果为”process“，则改为”error“

### What is Expected?
el-stpes当前步骤的显示状态应该与 proces-status 设置的值相对应

### What is actually happening?
调试模式显示 el-stpes 的 process-status 属性值已改变，但组件显示上没有任何变化

**Comment by sinchang** [comment]
I will work this issue.

**Comment by zhoufanglu** [comment]
我在^2.13.2 中又出现了这个问题
