### ISSUE TITLE
[Feature Request] I have an idea for a Date Picker

### ISSUE THREAD

**Issue by cnsummer** [ElemeFE/element#14500]
### Existing Component
是

### Component Name
DatePicker

### Description
当我使用选择时间范围时，假如说左边选择框与右边的选择框都选取了2月17号，但是转化出来的时间戳并不是我想要的，左边选择框应该时2月17号的开始时间，右边选择框应该时2月17号的结束时间，因为在做后台时大量使用了时间范围查询，这个功能我认为很有必要。，所以我在想是否可以给该组件加一个配置来配置。比如说start,end,now。我的英语并不是很好，这时我用有道翻译的。
---
When I used to choose time range, if say selection box on the left and the right of the checkbox is selected the February 17, but the transformation of the timestamp is not what I want, should select box on the left when the beginning of February 17, the right selection box should be when the end of the time, on February 17, due to the extensive use of the time when doing the background range queries, I think it is necessary to this function. So I was wondering if I could add a configuration to this component to configure it. Start,end,now. My English is not very good, at this time I use youdao translation.

**Comment by wacky6** [comment]
https://jsfiddle.net/c94z7meL/ 看文档。
