### ISSUE TITLE
[Bug Report] Tree disabled checkbox When the first menu is selected by default, you need to double-click the unchecked state

### ISSUE THREAD

**Issue by armor-broken** [ElemeFE/element#14513]
### Element UI version
2.5.4

### OS/Browsers version
windows10/chrome

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/Ruraliu/thx3me5p/](https://jsfiddle.net/Ruraliu/thx3me5p/)

### Steps to reproduce
tree树形控件如链接中含有禁用状态的选中，一级复选框点击一次无法取消，点击两次才能取消

### What is Expected?
一级复选框默认选中，单机即取消所有选中态

### What is actually happening?
需要双击

**Comment by island205** [comment]
pr welcome
