### ISSUE TITLE
[Bug Report] The input component displays the problem in safari. The cursor is too long.

### ISSUE THREAD

**Issue by mannix-lei** [ElemeFE/element#14518]
### Element UI version
2.5.4

### OS/Browsers version
macos/safari 12.0.3 (13606.4.5.3.1)

### Vue version
2.6.7

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
The cursor clicks on the input and the cursor appears too long. The element's official website can be reproduced.

### What is Expected?
add line-height

### What is actually happening?
add line-height

**Comment by island205** [comment]
Sorry, we have no plan to support this.  the workaround is set `line-height` to `1.`
