### ISSUE TITLE
[Bug Report] 2.5.4版本的el-date-picker type="datetime"的时候，小时/分钟/秒，上下滑动有些数字滑动不到，并且卡顿。(查看release是2.4.7版本更新产生的bug)

### ISSUE THREAD

**Issue by RomaYang** [ElemeFE/element#14515]
### Element UI version
2.5.4

### OS/Browsers version
window10/chrome

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element/releases](https://github.com/ElemeFE/element/releases)

### Steps to reproduce
2.5.4版本的el-date-picker type="datetime"的时候，小时/分钟/秒，上下滑动有些数字滑动不到，并且卡顿。(查看release是2.4.7版本更新产生的bug)

### What is Expected?
正常滑动，选择正确时间

### What is actually happening?
2.5.4版本的el-date-picker type="datetime"的时候，小时/分钟/秒，上下滑动有些数字滑动不到，并且卡顿。(查看release是2.4.7版本更新产生的bug)

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
