### ISSUE TITLE
[Bug Report] Component Update Causes Input Component Input State Error

### ISSUE THREAD

**Issue by menyouneko** [ElemeFE/element#14521]
### Element UI version
2.5.4

### OS/Browsers version
MAC OS 10.14.3 / Chrome 72.0.3626.119

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/sheepMieMie/wh0epdmg/3/](https://jsfiddle.net/sheepMieMie/wh0epdmg/3/)

### Steps to reproduce
1、切换为中文输入法，在 Input 组件中输入任意字符；

2、此时保持输入状态，同时触发 DOM 更新（已在 jsfiddle 示例中通过 setTimeout 实现）；

3、Input 中的输入字符会被清空（其实是保持了上一次的 input 值，新的值没有更新到 model 上）。

更多信息：
使用中文输入法时会触发 compositionstart，compositionupdate 事件，正常情况下，输入完成会触发 compositionend 事件，完成整个输入流程。
但是在输入完成前，DOM 有更新的话，会导致 compositionend 事件触发不了，影响后面的 this.$emit('input', value) 执行。

### What is Expected?
DOM 的更新不会影响 Input 组件中文输入时的输入状态。

### What is actually happening?
在 element-ui 2.5.4 版本中，DOM 的更新会导致中文输入时、输入框 compositionend 事件不会触发，从而导致的上述情况；
而在  element-ui 2.4.5 中，则表现正常，可通过 jsfiddle 中切换 ele-ui 的版本来观察。

**Comment by yongquan88** [comment]
遇到相同的问题

**Comment by yepbug** [comment]
似乎源于[这次提交](https://github.com/ElemeFE/element/commit/e2c5573c1f0d31418d8c793e3a00027d9ae61477#diff-e7e796b975dbceb8b89a4d9eb9a533a0)。`composition` 的处理，个人认为不应该交给组件，因为这样的话，中文环境下使用这个组件，就监听不了 `input` 事件了。而且查看了历史提交，为了解决 `composition` 的问题，似乎有些纠结，花了不少精力。

**Comment by menyouneko** [comment]
> 似乎源于[这次提交](https://github.com/ElemeFE/element/commit/e2c5573c1f0d31418d8c793e3a00027d9ae61477#diff-e7e796b975dbceb8b89a4d9eb9a533a0)。`composition` 的处理，个人认为不应该交给组件，因为这样的话，中文环境下使用这个组件，就监听不了 `input` 事件了。而且查看了历史提交，为了解决 `composition` 的问题，似乎有些纠结，花了不少精力。

其实我认为 composition 的处理从代码上看是没大问题的，中文输入完后触发 compositionend，然后再触发 input 的监听事件。这里的主要问题是，DOM 重新渲染后，导致 compositionend 不会触发。因此后续流程都崩了。然而为什么 DOM 重新渲染后不会触发 compositionend，这里我也还没有一个明确的原因。。

**Comment by yepbug** [comment]
> > 似乎源于[这次提交](https://github.com/ElemeFE/element/commit/e2c5573c1f0d31418d8c793e3a00027d9ae61477#diff-e7e796b975dbceb8b89a4d9eb9a533a0)。`composition` 的处理，个人认为不应该交给组件，因为这样的话，中文环境下使用这个组件，就监听不了 `input` 事件了。而且查看了历史提交，为了解决 `composition` 的问题，似乎有些纠结，花了不少精力。
> 
> 其实我认为 composition 的处理从代码上看是没大问题的，中文输入完后触发 compositionend，然后再触发 input 的监听事件。这里的主要问题是，DOM 重新渲染后，导致 compositionend 不会触发。因此后续流程都崩了。然而为什么 DOM 重新渲染后不会触发 compositionend，这里我也还没有一个明确的原因。。

是的，一般情况下不会出现 bug，触发这个 bug 的条件是：input 组件中输入中文的同时，父组件的状态发生改变。
可以分别在 `input` 组件的 `beforeUpdate` 和 `updated` 生命周期中打印 `this.$refs.input.value`。
我的理解是 `input` 的 DOM 重新渲染后，value 值被重置为改变之前的值=》输入法输入的值为空=》compositionend 不触发。
要是 vue 有 `shouldComponentUpdate` 就好了，可以让` input` 组件不去重新渲染。

**Comment by wacky6** [comment]
我在看这个问题。composition事件最早在这里引入 https://github.com/ElemeFE/element/commit/0b7e9dae5cbc572359fd8a8e45d799a1712fe758， 为了处理https://github.com/ElemeFE/element/issues/10516

https://github.com/ElemeFE/element/commit/e2c5573c1f0d31418d8c793e3a00027d9ae61477#diff-e7e796b975dbceb8b89a4d9eb9a533a0 是为了让组件状态受控，

**Comment by wacky6** [comment]
应该是input的render里面绑定了 `:value` 的问题，让组件直接设置原生input的value可以解决。 https://jsfiddle.net/2bv8ro0p/

这个问题确实是我做 https://github.com/ElemeFE/element/commit/e2c5573c1f0d31418d8c793e3a00027d9ae61477 的时候没考虑到
