### ISSUE TITLE
[Bug Report]  Pagination component did not judge the legality of the prop "layout" then vue lib throw error。 分页组件如果传错layout,没有判断TEMPLATE_MAP[compo]是否是undefined存在都会插入到children。

### ISSUE THREAD

**Issue by obadogg** [ElemeFE/element#14524]
### Element UI version
2.5.4

### OS/Browsers version
*/*

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/1dmz79eq/](https://jsfiddle.net/1dmz79eq/)

### Steps to reproduce
<el-pagination
    layout="sprev, pager, next"
    :total="50">
  </el-pagination>

### What is Expected?
Add some compatible processing instead of making Vue throw an exception

### What is actually happening?
throw an exception

**Comment by island205** [comment]
Sorry, we have no plan to support this.
