### ISSUE TITLE
[Bug Report] Pagitation goes to the question of return by return at IE. The first input page number is valid by return, and the second input page number is invalid by return.

### ISSUE THREAD

**Issue by zengweifang** [ElemeFE/element#14527]
### Element UI version
2.5.4

### OS/Browsers version
IE11

### Vue version
2.6.7

### Reproduction Link
[jsfiddle/codepen ](jsfiddle/codepen )

### Steps to reproduce
pagitation前往按会回车在IE的问题，第一次输入页码按回车有效，第二次后输入页码按回车无效

### What is Expected?
pagitation前往按会回车在IE的问题，第一次输入页码按回车有效，第二次后输入页码按回车无效

### What is actually happening?
pagitation前往按会回车在IE的问题，第一次输入页码按回车有效，第二次后输入页码按回车无效

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
