### ISSUE TITLE
Bug in the scrollbar of the [Bug Report] table component

### ISSUE THREAD

**Issue by BrightStarrySky** [ElemeFE/element#14522]
### Element UI version
2.5.4

### OS/Browsers version
mac 10.14.3  浏览器 72.0.3626.119（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/6faxb04r/3/](https://jsfiddle.net/6faxb04r/3/)

### Steps to reproduce
鼠标（从上至下/从下至上）保持无水平位移滑过table组件，一直滑动到底部滚动条出现的位置(注：必须是在table组件初始化后第一次未进行列表的水平滚动下操作时会出现)
table 列表添加了border 属性值后更容易触发此效果, (怀疑border引起的table x轴长度变化会与 overflow-x属性的设置逻辑相关联)
 class 名为  .el-table--scrollable-x .el-table__body-wrapper    的 overflow-x:auto属性会影响问题

### What is Expected?
滚动条正常显示

### What is actually happening?
只要满足触发条件就滚动条就不会消失，除非刷新页面，手动重置.el-table--scrollable-x .el-table__body-wrapper下的 overflow-x:auto也可恢复正常，但是代码上就需要dom 操作

**Comment by zeloat** [comment]
同样的问题
