### ISSUE TITLE
[Bug Report] Component Pagination can't render by @vue/test-utils API  "mount "

### ISSUE THREAD

**Issue by NoobxzZhang** [ElemeFE/element#14529]
### Element UI version
2.5.4

### OS/Browsers version
win 10

### Vue version
2.6.7

### Reproduction Link
sorry for can't offer the [https://jsfiddle.net
but  [https://codesandbox.io/s/nn28lx9r80](https://codesandbox.io/s/nn28lx9r80)

### Steps to reproduce
1. Open codesandbox URL
2. Open the Test Tab

### What is Expected?
mount can render the component Pagination

### What is actually happening?
it can't render

**Comment by island205** [comment]
`Pagination` component is not Element's `Pagination`  component.
