### ISSUE TITLE
[Bug Report] Date Picker When type = week and first DayOfWeek = 3, 2019-01-01 shows Wednesday, not Tuesday.

### ISSUE THREAD

**Issue by xiaoxuefengnian** [ElemeFE/element#14523]
### Element UI version
2.4.11

### OS/Browsers version
chrome

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/wLnje7t1/](https://jsfiddle.net/wLnje7t1/)

### Steps to reproduce
设置 DatePicker，
type = "week"，
picker-options="{firstDayOfWeek: 3}"，
查看日期为2019-01-01时的日期面板

### What is Expected?
2019-01-01显示为周二

### What is actually happening?
2019-01-01显示为周三

**Comment by xiaoxuefengnian** [comment]
![image](https://user-images.githubusercontent.com/8936924/53677631-2f012d00-3cee-11e9-9418-f50def7d00e0.png)

**Comment by fadeds** [comment]
我设置的怎么不生效哦

**Comment by xiaoxuefengnian** [comment]
> 我设置的怎么不生效哦 2.4.11版本的



> 我设置的怎么不生效哦 2.4.11版本的

**Comment by xiaoxuefengnian** [comment]
> 我设置的怎么不生效哦 2.4.11版本的

可以看下 Reproduction Link 里的，目前我只发现2019年1月的有问题，2月以及后面没有问题
1月的，可以注意下2月开头几天
![11](https://user-images.githubusercontent.com/8936924/53793108-2582f980-3f68-11e9-83f0-cd81b82aa872.jpg)
2月的
![2](https://user-images.githubusercontent.com/8936924/53793158-3c295080-3f68-11e9-94c2-5b67e8e33ddf.jpg)

**Comment by sinchang** [comment]
@wacky6 Can I work this issue?

**Comment by wacky6** [comment]
Certainly,  pr welcome
