### ISSUE TITLE
[Feature Request] Tabs Component Optimization Recommendations

### ISSUE THREAD

**Issue by BrightStarrySky** [ElemeFE/element#14520]
### Existing Component
是

### Component Name
Tabs

### Description
希望v-model 绑定的选项卡name数值可以支持number 大部分场景用于切换列表数据是一般使用某个属性值控制  例如  type

**Comment by BrightStarrySky** [comment]
tabs组件，之前写错名字了

**Comment by island205** [comment]
Please provide a example for your feature request, some code please.

**Comment by BrightStarrySky** [comment]
demo-url http://jsrun.net/GwXKp/edit

**Comment by BrightStarrySky** [comment]
@island205
