### ISSUE TITLE
[Bug Report] In complex situations such as router-view, slot, if, slot under el-table, the parent component passes in the slot under el-table-column [Vue warn]: Duplicate keys detected:'el-table_1_column_1'. This may cause an update error. found in - > < ElTable Header >

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#14530]
### Element UI version
2.5.4

### OS/Browsers version
last 2 chrome version

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/panhezeng/xw5k40yq](https://jsfiddle.net/panhezeng/xw5k40yq)

### Steps to reproduce
在非常复杂的cms项目下，在router-view,slot,if多种复杂情况下，el-table下面的slot，父组件通过slot传入el-table-column  [Vue warn]: Duplicate keys detected: 'el-table_1_column_1'. This may cause an update error.  found in  ---> <ElTableHeader>

### What is Expected?
无Vue warn

### What is actually happening?
[Vue warn]: Duplicate keys detected: 'el-table_1_column_1'. This may cause an update error.

found in

---> <ElTableHeader>
       <ElTable> at packages/table/src/table.vue
         <ElTreeTable> at src/ElTreeTable.vue
           <CommonPageList> at src/components/common/Page/List.vue
             <CommonPageContent> at src/components/common/Page/Content.vue
               <Index> at src/components/pages/Organization/index.vue
                 <LayoutBasic> at src/components/layouts/Basic.vue
                   <App> at src/App.vue
                     <Root>

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by xzb1203** [comment]
我也遇到这个问题了
