### ISSUE TITLE
DatePicker 时间控件如何对change事件添加绑定啊

### ISSUE THREAD

**Issue by AppHL** [ElemeFE/element#1453]
如题

**Comment by AppHL** [comment]
我能想到的方法只有利用id或者一些属性，对dom绑定change事件~~

**Comment by AppHL** [comment]
我想到了可以利用watch来监听vm中这个值得变化，不过还是希望能够日后能新增一些事件属性！

**Comment by Leopoldthecoder** [comment]
目前 DatePicker 没有提供 `change` 事件，使用 `watch` 是正确的做法。
