### ISSUE TITLE
[Bug Report] el-tree component shows check box by multiple selection. If a check box is selected in the el-check box-group slot, a check box selection will occur. The check box in tree is affected by el-check-box.

### ISSUE THREAD

**Issue by xuyuqin0123** [ElemeFE/element#14538]
### Element UI version
2.5.4

### OS/Browsers version
win 10

### Vue version
2.6.7

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
无

### What is Expected?
无

### What is actually happening?
无

**Comment by luckyCao** [comment]
can't reproduce

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
