### ISSUE TITLE
[Bug Report] When another component is inserted into the el-table-column slot, the life cycle hook of the component is triggered twice.

### ISSUE THREAD

**Issue by acdseen** [ElemeFE/element#14533]
### Element UI version
2.5.4

### OS/Browsers version
Win 10 / Chrome 67.0.3396.99

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/acdseen/hp34r2jL/](https://jsfiddle.net/acdseen/hp34r2jL/)

### Steps to reproduce
The current situation occurs when the fixed attribute is added to the operation column
1.Click the Edit button ；
2.Rendering Input Box Component  ；
3.Changing the value of the input box component equals the name of the current line ；

### What is Expected?
The value value of the input box component is the name value of the current row  ；

### What is actually happening?
Input box component life cycle hook triggered twice, assignment failed ；

**Comment by jingjingxinshang** [comment]
I also encountered the same problem.

**Comment by ziyoung** [comment]
#10588

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/10588#issuecomment-379460140
