### ISSUE TITLE
[Feature Request] Remove transition of file upload

### ISSUE THREAD

**Issue by YuGe** [ElemeFE/element#14539]
### Existing Component
Yes

### Component Name
Upload

### Description
There is an animation of Upload component when file list is changed. Can we offer an option to remove that animation?

**Comment by island205** [comment]
Sorry, we have no plan to support this.

**Comment by jamalsaidapp07** [comment]
you can disable it by set this in your css

.el-upload-list__item {
        transition: none !important;
    }
