### ISSUE TITLE
[Bug Report] el-dialog make selection in el-table invisible

### ISSUE THREAD

**Issue by zh244135370** [ElemeFE/element#14543]
### Element UI version
2.6.0

### OS/Browsers version
Windows 10

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
使用el-table时，通过row-click和this.$refs.multipleTable.toggleRowSelection(row, true)将某一行设为选中或非选中，然后点击按钮弹出一个el-dialog之后，会导致选中的表格项编程未选中状态。但是实际上，关闭el-dialog之后，再去点这些选项，第一次点从selection中删掉了这个选项，第二次点才重新被选中。也就是说，dialog导致表格的选中不被可见，但是表格实际数据selection是包含这些选项的

### What is Expected?
点击打开el-dialog不会导致表格的多选样式消失

### What is actually happening?
点击打开el-dialog会导致表格的多选样式消失

**Comment by xxh332211** [comment]
遇到同样的问题,为什么close了呢?请问是解决了么?

**Comment by zh244135370** [comment]
> 遇到同样的问题,为什么close了呢?请问是解决了么?

可能是因为异步的问题导致，或者是使用了v-if之类的隐藏了元素导致。现在的解决办法可以用@select-change事件，当本地保存的selection与改变之后的selection不同时，可以将本地保存的selection重新赋给表格，@selection-change="selectChanged"，
selectChanged(selection){
        let _this = this
        if (selection.length !== this.selection.length) {
          _.each(this.selection, function (row) {
            _this.$refs.multipleTable.toggleRowSelection(row, true)
          })
        }
      }

**Comment by xxh332211** [comment]
逻辑上行不通啊,这样的话当需要清空选中的时候,就有逻辑冲突了.仍然会将本地保存的selection赋值给表格,导致无法清除选中

**Comment by zh244135370** [comment]
> 逻辑上行不通啊,这样的话当需要清空选中的时候,就有逻辑冲突了.仍然会将本地保存的selection赋值给表格,导致无法清除选中

嗯，或者在dialog隐藏之后$nextTick将保存的selection保存到table中，弹出期间可能显示的是没有选中。清空似乎会在弹出和消失执行两次，可以在弹出执行一次nextTick，消失的时候在执行一次，这样不会跟全选冲突
this.$nextTick(function () {
          if (this.$refs.multipleTable.selection.length !== this.selection.length) {
            _.each(this.selection, function (row) {
              _this.$refs.multipleTable.toggleRowSelection(row, true)
            })
          }
        })

**Comment by xxh332211** [comment]
Emmmmmm.....好像行不通.
