### ISSUE TITLE
[Bug Report] Windows 7 environment, using IE to open input components, repeated input or modification of content will appear cursor jump

### ISSUE THREAD

**Issue by lmyekong** [ElemeFE/element#14540]
### Element UI version
2.5.4

### OS/Browsers version
window7

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
我访问不了jsfiddle
在input组件反复输入和修改内容，光标跳动

http://element-cn.eleme.io/#/zh-CN/component/input用这个页面在IE下（window7）试一下就知道了

### What is Expected?
光标不跳动

### What is actually happening?
光标会闪跳到最后面，输入的内容不是想要的内容

**Comment by island205** [comment]
IE version?

**Comment by wacky6** [comment]
try this fiddle, does it fix the problem? jsfiddle.net/da40mcgq

**Comment by lmyekong** [comment]
IE10

发送自 Windows 10 版邮件应用

发件人: Zhi Cun
发送时间: 2019年3月5日 12:45
收件人: ElemeFE/element
抄送: zero zhu; Author
主题: Re: [ElemeFE/element] [Bug Report] Windows 7 environment, using IE to open input components, repeated input or modification of content will appear cursor jump (#14540)

IE version?

**Comment by island205** [comment]
Again, @lmyekong Does it fix the problem?  http://jsfiddle.net/da40mcgq
