### ISSUE TITLE
[Date-picker]切换type属性 面板内容不更新 

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1455]
切换type类型 值改变 但是点开的时间选择面板不改变 
https://jsfiddle.net/yelingfeng/p9gLapep/1/
![image](https://cloud.githubusercontent.com/assets/1932350/20700596/3115fe5a-b649-11e6-853e-da652f5bf254.png)

**Comment by Leopoldthecoder** [comment]
DatePicker 不支持动态切换 type。

**Comment by briefness** [comment]
用v-if也是不行的，有什么方法吗
