### ISSUE TITLE
[Bug Report] el-tag form validation problem

### ISSUE THREAD

**Issue by w3cmark** [ElemeFE/element#14559]
### Element UI version
2.6.1

### OS/Browsers version
macOS 10.14.3/chrome 72.0.3626.109

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/c3dqfehb/](https://jsfiddle.net/c3dqfehb/)

### Steps to reproduce
1、form表单使用了el-tag
2、设置el-tag的校验rules
3、添加了一个标签后，表单校验没通过

### What is Expected?
完成正常的表单校验

### What is actually happening?
使用带有校验rules的el-tag，表单校验一直没通过

**Comment by ziyoung** [comment]
写的有问题。rule 中的 prop 要跟 data 相对应。https://jsfiddle.net/cwpysx34/

**Comment by w3cmark** [comment]
> 写的有问题。rule 中的 prop 要跟 data 相对应。https://jsfiddle.net/cwpysx34/

明白。不过你发的修改忘记改html上面的`tag`了。
