### ISSUE TITLE
[Bug Report] <el-timeline> - did you register the component correctly?

### ISSUE THREAD

**Issue by objcxiaobai** [ElemeFE/element#14556]
### Element UI version
2.5.4

### OS/Browsers version
Mac OS / Chrome 72.0

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/64hbf1js/](https://jsfiddle.net/64hbf1js/)

### Steps to reproduce
https://jsfiddle.net/64hbf1js/

### What is Expected?
vue.esm.js? [Vue warn]: Unknown custom element:  ·《el-timeline》 ·- did you register the component correctly? For recursive components, make sure to provide the "name" option.

### What is actually happening?
vue.esm.js? [Vue warn]: Unknown custom element: · 《el-timeline》·  - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by liener** [comment]
这东西是不是在这个版本里没有啊。我这边也遇到这个问题，后来我查element对象里面 我那个版本没有 timeline这个组件。。

**Comment by objcxiaobai** [comment]
> 这东西是不是在这个版本里没有啊。我这边也遇到这个问题，后来我查元素对象里面我那个版本没有时间线这个组件..

没有细看源码..，所以有点懵,有其他方案代替了这个

**Comment by liener** [comment]
那个组件是3月1号最新版的2.6.0才有的 2.5.4应该没有.你可以试着用最新的试试应该就可以。

**Comment by vinayakkulkarni** [comment]
I had the same issue, I had element-ui `2.5.4`, upgraded to `2.6.1` and it works!

**Comment by 3xxx** [comment]
原来是这样啊，确实升级到2.6.1就可以了。
