### ISSUE TITLE
[Bug Report] ElTable component calls row/cell class/style  functions on hover event

### ISSUE THREAD

**Issue by ssadovski007** [ElemeFE/element#14550]
### Element UI version
2.6.0

### OS/Browsers version
Mac OS / Chrome, Firefox

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/jm7ngkeq/5/](https://jsfiddle.net/jm7ngkeq/5/)

### Steps to reproduce
Open Reproduction Link, Open Dev Console (Console tab) and hover over the table component.

Observation: 
element-ui@2.6.0 - :row-class-name=tableRowClassName() function is called on every single hover while :data is not changed
element-ui@2.5.4 - :row-class-name=tableRowClassName() function is called once per row unless :data changed

### What is Expected?
:row-class-name function is called once per row unless :data changed (as in element-ui@2.5.4)

### What is actually happening?
:row-class-name function is called on every single hover action while :data prop is not changed. This causes significant performance degradation of the Table component.

**Comment by ziyoung** [comment]
#14868

**Comment by edum18** [comment]
it still calls multiple times cell style functions on hover, v2.12.0
