### ISSUE TITLE
[Bug Report] Errors are reporting when the form textarea box is newline: Cannot read property'type'of undefined

### ISSUE THREAD

**Issue by hdmy** [ElemeFE/element#14563]
### Element UI version
2.6.0

### OS/Browsers version
Chorme  72.0.3626.119

### Vue version
2.5.18

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
官方网站示例：
http://element-cn.eleme.io/#/zh-CN/component/form

典型表单 - 活动形式 

文本款内换行时，会出现

Uncaught TypeError: Cannot read property 'type' of undefined
    at e.setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)

### What is Expected?
不应该有报错

### What is actually happening?
这里是将textarea当成form表单内普通的input处理，由于field为undefined，导致报错

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by hdmy** [comment]
![image](https://user-images.githubusercontent.com/20206052/54251856-adc65780-4583-11e9-8c50-239663129f58.png)
坐标广州，翻不翻都无法打开jsfiddle.net，直接通过官方表单示例是可以看到的，在文本框内回车换行，控制台会报错

**Comment by ricardosaracino** [comment]
> Issues without a valid reproduction link will be closed directly.

im having the same issue.

**Comment by dreambo8563** [comment]
官网就能复现啊...
