### ISSUE TITLE
[Feature Request] How to async import components

### ISSUE THREAD

**Issue by gaalok** [ElemeFE/element#14566]
### Existing Component
Yes

### Component Name
all

### Description
There are pages A,B,C,D:

pageA and pageB: not use elementUI

pageC and pageD: use elementUI

How can I async import elementUI just when I visit pageC and pageD

----------------------------------------------

假如有ABCD4个页面，其中AB不需要使用elementUI，而CD要，那怎样才能在访问AB时不加载而访问CD时异步加载elementUI呢

**Comment by island205** [comment]
not Element issue, pelase Google for your answer.
