### ISSUE TITLE
[Bug Report] el-input by Chinese type input method, will enter into pinyin, input box component automatically brings out Pinyin when entering Chinese

### ISSUE THREAD

**Issue by liaojw** [ElemeFE/element#14564]
### Element UI version
2.6.1

### OS/Browsers version
XP系统//Chrome49版本

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
el-inpu组件在输入中文时，会自动带出拼音！只有在XP系统，Chrome49环境下会有这个问题！

### What is Expected?
期待能够帮解决！

### What is actually happening?
希望可以解决！

**Comment by liaojw** [comment]
2.4.11及一下版本没有这个问题！

**Comment by wacky6** [comment]
试试这个 https://jsfiddle.net/da40mcgq/
