### ISSUE TITLE
[Bug Report] el-input textarea autosize = true (or {min: 4}) When there is more content, scrollbars still appear

### ISSUE THREAD

**Issue by yflin1** [ElemeFE/element#14561]
### Element UI version
2.5.4

### OS/Browsers version
Chrome 68.0.3423.2（正式版本） （32 位）

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/yflin/0n8xwsqz/5/](https://jsfiddle.net/yflin/0n8xwsqz/5/)

### Steps to reproduce
粘贴15行以上文本内容，时滚动条还是出现了

### What is Expected?
不出现滚动条

### What is actually happening?
出现滚动条

**Comment by yflin1** [comment]
或是设定了 "{ minRows: 8, maxRows 10000 }“，但一次 粘贴一个较大的文本时（几百行），也会出现滚动条

**Comment by luckyCao** [comment]
你的例子无法重现；你看到的滚动条可能是外围元素的滚动条。

**Comment by yflin1** [comment]
后来没找到解决方案




| |
yflin
|
|
邮箱：kubi08@163.com
|
On 05/08/2019 22:08, 饕餮 wrote:

您好，您的问题解决了吗，我也遇到了，windows下滚动条会出现，当粘贴一定行数的时候

**Comment by flyher** [comment]
@luckyCao 
你确定试过？

**Comment by LuoChengIo** [comment]
设置textarea 样式overflow-y: hidden似乎可以解决这个问题

**Comment by flyher** [comment]
看到了之前的留言，算了，正好之前改过，给各位后来的大佬贴一下懒人代码。

`textarea` 样式 `overflow-y: hidden`，调整窗口大小会导致文本超出隐藏了，再加个`onResize`事件。

```js
  mounted() {
    window.addEventListener('resize', this.onResize);
  },
  beforeDestroy() {
    window.removeEventListener('resize', this.onResize);
  },
  methods: {
    onResize() {
      this.$nextTick(function() {
        this.$refs.yourEleRefName.resizeTextarea();
      });
    },
  }
```
