### ISSUE TITLE
[Bug Report] el-button has a redundant css

### ISSUE THREAD

**Issue by Wizzercn** [ElemeFE/element#14567]
### Element UI version
2.6.0

### OS/Browsers version
Windows10  Chrome

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/L9nur4d2/](https://jsfiddle.net/L9nur4d2/)

### Steps to reproduce
make two el-button , find css 

### What is Expected?
`.el-button+.el-button{margin-left:10px}`

### What is actually happening?
`.el-button+.el-button{margin-left:0}`

please delete `margin-left `,it influencing the layout style of old projects ,for upgrade

**Comment by luckyCao** [comment]
your demo can't reproduce it.

**Comment by LemniscateX** [comment]
I face the same issue, redundant interval appears between two consequent buttons.
Console shows that the second button has style like this:
`.el-button+.el-button {
    margin-left: 10px;
}`
