### ISSUE TITLE
select键盘选中值，v-model中无此值

### ISSUE THREAD

**Issue by leegoway** [ElemeFE/element#1456]
### ElementUI version
 1.0.0-rc.8 

### OS/Browers version
macOS/Chrome 53 

### Vue version
2.0.3

### Steps to reproduce
select选择框远程模式，使用键盘上下选择值，并使用enter选中值，但在submit的时候发现model中值为undefined，select的change事件中能接收到选中的值。

### What is Expected?
使用键盘enter选中值后，submit时model中有选中的值

**Comment by Kingwl** [comment]
上个repo吧 我记得没这个问题。。

**Comment by leegoway** [comment]
更新到1.0.3版本解决
