### ISSUE TITLE
[Bug Report] In the IE browser under Windows 7, the paging component input box change event does not trigger.

### ISSUE THREAD

**Issue by zpdf** [ElemeFE/element#14575]
### Element UI version
2.6.1

### OS/Browsers version
window 7/ ie 11

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/rLt6ug0m/4/](https://jsfiddle.net/rLt6ug0m/4/)

### Steps to reproduce
输入框失去焦点的时候，不触发current-change 事件

其他浏览器可以触发，window 10下面的ie也正常触发。

### What is Expected?
 能正常触发

### What is actually happening?
 在window 7的 ie下不触发

**Comment by zpdf** [comment]
input组件在同样环境下，change事件也不触发

**Comment by ziyoung** [comment]
@wacky6 input 的兼容性问题？

**Comment by wacky6** [comment]
2.4 2.5 表现正常吗？

**Comment by zpdf** [comment]
> 2.4 2.5 表现正常吗？

@wacky6  2.4正常 2.5不正常

**Comment by ziyoung** [comment]
@zpdf 稍微修改一下 demo，现在使用 #14572 打包生成的 element-ui。https://jsfiddle.net/cL1h9qpg/ 检查一下现在是否 Windows 下表现正常？

**Comment by zpdf** [comment]
@ziyoung  正常了
