### ISSUE TITLE
[Feature Request] NavMenu's collapse status supports scrolling and height definition

### ISSUE THREAD

**Issue by qiangbro** [ElemeFE/element#14574]
### Existing Component
是

### Component Name
NavMenu

### Description
NavMenu 在收起状态下打开一个菜单，如果菜单内项目数量太多，高度太高，超出屏幕高度的项目会被遮住无法选择。希望可以支持定义菜单高度、支持滚动操作。
![qq 20190305154556](https://user-images.githubusercontent.com/4646469/53789035-6544e380-3f5e-11e9-8431-765fca7aca9c.jpg)

**Comment by liub1934** [comment]
菜单需要一个高度，然后设置`overflow: auto`
https://jsfiddle.net/Lhunocfm/

**Comment by ziyoung** [comment]
> 菜单需要一个高度，然后设置`overflow: auto`
> https://jsfiddle.net/Lhunocfm/

@qiangbro
