### ISSUE TITLE
[Feature Request] el-table-column type="selection"是否也实现数据驱动

### ISSUE THREAD

**Issue by lightning0016** [ElemeFE/element#14585]
### Existing Component
是

### Component Name
el-table-column

### Description
el-table-column的 type="selection"目前是通过函数设置选中通过事件同时选中,是否加上类似prop="_checked",这样才是数据驱动

**Comment by lightning0016** [comment]
iview已经有了:给 data 项设置特殊 key _checked: true 可以默认选中当前项。

**Comment by hoythan** [comment]
iview 这种污染源数据的操作本来就不是什么好事情

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
