### ISSUE TITLE
[Bug Report] Drop-down menus are not supported correctly on the touch device

### ISSUE THREAD

**Issue by WINBIGFOX** [ElemeFE/element#14584]
### Element UI version
2.6.1

### OS/Browsers version
MacOS 10.13.6

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/g67jmn08/1/](https://jsfiddle.net/g67jmn08/1/)

### Steps to reproduce
1. Open the Google-Chrome development tools and start the iPhone-screen view
2. Click/touch with the mouse on the dropdown-menu an select/click on an item

### What is Expected?
After clicking on the item, the menu should close and remain closed

### What is actually happening?
After clicking on the item, the dropdown menu closes, but opens immediately afterwards

![image](https://i.ibb.co/5LByVp9/2019-03-05-20-07-43.gif)

**Comment by lucyhao** [comment]
If you used in mobile , you need to add trigger="click"(mobile don't have this "hover" action. so.....)..
Change your code like this.
`<el-dropdown trigger="click">....<el-dropdown>`

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  FYI: https://github.com/vuejs/awesome-vue#mobile-1
