### ISSUE TITLE
[Feature Request] can add an directive in the el-table, then the el-table's Max height is the free space, the scroll only in the el-table but not all window s

### ISSUE THREAD

**Issue by lxy545480918** [ElemeFE/element#14581]
### Existing Component
是

### Component Name
el-table

### Description
can add an directive in the el-table,then the el-table's max height is the free space, the scroll only in el-table but not all window 能不能在el-table上增加一个指令，根据剩余空间，自动设置最大高度，这样表格不会超出整个页面，滚动条只会出现在表格内部

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
