### ISSUE TITLE
slider 拖动的太快的话，会停在不合适的点上。

### ISSUE THREAD

**Issue by think2011** [ElemeFE/element#1458]
http://element.eleme.io/#/zh-CN/component/slider

例如当前值是50，想要改成100，所以很快的往右拖动，数值会停在85-99之间，就是不到100

如果慢慢的拖动是没有问题的。

**Comment by Leopoldthecoder** [comment]
Fixed in #1478

**Comment by think2011** [comment]
线上看到还是一样，本地升级到1.0.3拖动的时候发现有小数点余数

**Comment by Leopoldthecoder** [comment]
是的，还没发布。

**Comment by think2011** [comment]
👌🏻，我留意一下近期的发布
