### ISSUE TITLE
How does the thead in the table component need to be implemented in a loop?

### ISSUE THREAD

**Issue by qianzhangsheng** [ElemeFE/element#14597]
### Existing Component
是

### Component Name
table

### Description
table组件里的thead里的内容需要循环，现有API貌似无法实现。

thead是日期，tbody是日期对应的数据。

例如：

2018.1 | 2018.2 | 2018.3 | 2018.4

11111  | 22222  | 33333  | 44444

**Comment by ziyoung** [comment]
设置 header slot。
