### ISSUE TITLE
table 表头合并

### ISSUE THREAD

**Issue by mengxianghan** [ElemeFE/element#14599]
如何实现这种风格的表头

![_20190306142010](https://user-images.githubusercontent.com/13127504/53860269-6556e900-401b-11e9-8505-9bf32a3b057a.png)

**Comment by 28builder** [comment]
> 如何实现这种风格的表头
> 
> ![_20190306142010](https://user-images.githubusercontent.com/13127504/53860269-6556e900-401b-11e9-8505-9bf32a3b057a.png)



> Hello, this issue has been closed because it does not conform to our issue requirements. Please submit issues with [issue-generator](https://elementui.github.io/issue-generator/#/en-US). More info can be found in #3693.
同问

**Comment by mengxianghan** [comment]
> > 如何实现这种风格的表头
> > ![_20190306142010](https://user-images.githubusercontent.com/13127504/53860269-6556e900-401b-11e9-8505-9bf32a3b057a.png)
> 
> > Hello, this issue has been closed because it does not conform to our issue requirements. Please submit issues with [issue-generator](https://elementui.github.io/issue-generator/#/en-US). More info can be found in #3693.
> > 同问

This is simulated with div
