### ISSUE TITLE
[Bug Report] In IE 9-11, <el-table/> components have severe rolling carton

### ISSUE THREAD

**Issue by piaojiyin** [ElemeFE/element#14603]
### Element UI version
2.6.1

### OS/Browsers version
win10/IE 9~11

### Vue version
2.6.8

### Reproduction Link
[(github|jsfiddle|codepen|jsbin)]((github|jsfiddle|codepen|jsbin))

### Steps to reproduce
环境：IE 9~11中，
1、<el-table/>组件渲染比如15列30行的数据；
2、<el-table/>设置props中的height属性，如‘500’；
3、在css中设置el-table的border属性如：
.el-table {
  border: 1px solid #eee;
  border-radius: 5px;
}

### What is Expected?
<el-table/>滚动流畅

### What is actually happening?
<el-table/>滚动严重卡顿

**Comment by kemplaw** [comment]
跟楼主同样的问题。

**Comment by kemplaw** [comment]
在chrome浏览器下也是一样的卡顿

**Comment by piaojiyin** [comment]
@kemplaw chrome有轻微卡顿，不明显，目前我临时把border样式去掉了，因为设置el-table的height优先级更高，sad。。

**Comment by ziyoung** [comment]
Duplicate of #14550

**Comment by liy05** [comment]
Border-radius: 5px;  这个css属性引起的，去掉就好了。IE下面的一个BUG。
看这个链接：https://www.grapecity.com/blogs/fix-flexgrid-scroll-performance-in-ie-with-this-one-weird-trick
