### ISSUE TITLE
How does [Feature Request] el-upload echo uploaded files?

### ISSUE THREAD

**Issue by lameone1** [ElemeFE/element#14607]
### Existing Component
是

### Component Name
<el-upload>

### Description
 从后台取已上传的文件{name:'图片'，url：’http://....‘} 放入:file-list="fileList" 怎么样才能回显示呢？

**Comment by TY-LIU** [comment]
```
 this.fileList.push({
        url: `${this.Global.OSS_IMAGE_URL}/${newValue.FullFileNames}`,
        name: `${newValue.FullFileNames}`
 })
```
fileList是一个集合，PUSH就完事了，Upload会自动加上status和uid
