### ISSUE TITLE
[Feature Request] Grouping in el-dropdown-menu

### ISSUE THREAD

**Issue by divyanshu-rawat** [ElemeFE/element#14606]
### Existing Component
Yes

### Component Name
el-dropdown-menu

### Description
Can we have grouping in el-dropdown-menu in the similar manner that we have in el-option-group?

**Comment by divyanshu-rawat** [comment]
@liub1934 it is not a grouping, like we have it here https://jsfiddle.net/api/post/library/pure/.

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
