### ISSUE TITLE
[Feature Request] el-tree If one of the subsets is not selected, the getCheckedKey method cannot get the parent ID

### ISSUE THREAD

**Issue by yaozaiyu** [ElemeFE/element#14616]
### Existing Component
是

### Component Name
el-tree

### Description
el-tree如果子集里面有一个没有选中，getCheckedKeys方法不能获取到父ID

**Comment by hoythan** [comment]
这是正常情况，因为有子级未选中时 父级 Checkbox 的状态是 indeterminate 表示 checkbox 的不确定状态

**Comment by xiaogaofudao** [comment]
如果是这种情况呢，子级全部选中了，我只想获取到父级的id。现在是 父级id 和 子级所有的id 都返回了
