### ISSUE TITLE
[Bug Report] element select uses value-key to set default values, but cannot select candidate values

### ISSUE THREAD

**Issue by anick-xs** [ElemeFE/element#14618]
### Element UI version
2.6.1

### OS/Browsers version
windows

### Vue version
2.6.1

### Reproduction Link
[https://jsfiddle.net/h48wpqu0/](https://jsfiddle.net/h48wpqu0/)

### Steps to reproduce
select组件设置了value-key = 'value',然后组件给默认值却不能选中候选值

### What is Expected?
设置默认值之后能选中候选值

### What is actually happening?
不能选中候选值

**Comment by liub1934** [comment]
```
value: {
          value: '选项1',
          label: '黄金糕'
        }
```

**Comment by IceApriler** [comment]
https://jsfiddle.net/to68kfs1/

el-select v-model="value" 和 el-option :value="item.value" 数据结构需要对应。
