### ISSUE TITLE
[Bug Report] table is not aligned after the width becomes larger (scrollbar disapear) in Chrome

### ISSUE THREAD

**Issue by shywei** [ElemeFE/element#14615]
### Element UI version
2.6.1

### OS/Browsers version
chrome 72.0.3626.109

### Vue version
2.6.8

### Reproduction Link
[https://codepen.io/shywei/pen/oVZvLq](https://codepen.io/shywei/pen/oVZvLq)

### Steps to reproduce
表格左侧有一个可以隐藏/显示的div
表格宽度占满父元素，列宽固定，最后一列只设置最小宽度
纵向和横向滚动条自动根据宽度显示

### What is Expected?
左侧区域显示时，最后一列内容换行，高度不够，滚动条正常显示
左侧区域隐藏时，最后一列无须换行，高度足够，滚动条消失，内容对齐。

### What is actually happening?
左侧区域显示时，最后一列内容换行，高度不够，滚动条正常显示
左侧区域隐藏时，最后一列无须换行，高度足够，滚动条消失，但是表头和内容不对齐。再次显示左侧区域，滚动条也不会再出现了。

**Comment by shywei** [comment]
在Firefox确认如下：
1、表格对齐没问题
2、滚动条不会再出现的问题依旧存在

**Comment by ziyoung** [comment]
width 调低一点正常了。
