### ISSUE TITLE
[select]下拉按钮展开的时候能不能增加默认第一项hover，这样回车就能自动选择

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#1461]
下拉按钮展开的时候能不能增加默认第一项hover，这样回车就能自动选择，不需要再按一下方向键或者移动鼠标了，还是说有现成的解决办法？
![image](https://cloud.githubusercontent.com/assets/12726826/20711650/bac789f2-b67b-11e6-9e17-b905965d5ac1.png)

**Comment by Leopoldthecoder** [comment]
目前的交互设计就是这样，这个应该不会改。

**Comment by esmeetu** [comment]
@lry210  添加一个`prop`:
```html
<el-select v-model="value" placeholder="请选择">
    <el-option v-for="item in options" 
        :label="item.label" 
        :value="item.value" 
        :selected="item.show"></el-option>
</el-select>
```

`data`里：
```js
value: '选项1',
label: '黄金糕',
show: true
```

**Comment by Leopoldthecoder** [comment]
@esmeetu 不建议使用 `selected` 属性。文档上未列出的属性在未来可能会修改。

**Comment by esmeetu** [comment]
@Leopoldthecoder 哦，不过`selected`不是默认`html`属性嘛，应该保持一致吧。

**Comment by Leopoldthecoder** [comment]
@esmeetu 目前是可以用的。但是后面是否保留取决于这个属性是否会对新功能的开发造成比较大的障碍。

**Comment by lry210** [comment]
![image](https://cloud.githubusercontent.com/assets/12726826/20739295/4761837c-b6f4-11e6-8f2a-1d372cab336e.png)
我觉得select，select2这才叫好的交互设计吧？
