### ISSUE TITLE
[Bug Report] el-menu uses routing mode and router-link jump path errors elsewhere in the page

### ISSUE THREAD

**Issue by xuezhimao** [ElemeFE/element#14623]
### Element UI version
2.6.1

### OS/Browsers version
Windows10 / Chrome72

### Vue version
2.6.8

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
尚在开发阶段，未传GitHub，不过问题重现很简单！！！！！！！！！！！！！！！！！！！
1.项目中使用了el-menu组件
2.el-menu组件开启路由模式（vue-cli设置的history模式）
3.el-menu组件外使用router-link to="/path"
4.若此页面此时处于由el-menu跳转的 http://localhost:8080/one 等一级路由下，点击其余的router-link，路由地址变成了 http://localhost:8080/one/path
5.暂时解决方案：在router-link中使用name跳转方式即可（:to="{name: 'path'}"）

6.另外，在使用el-scrollbar的时候，若只改变页面的高度，不改变宽度，不会自动更新滚动条高度，暂时采用手动调用组件update()的方式处理，不过我看element-ui官网的滚动条没有此bug，希望能将该组件使用条件写到文档中:-)

### What is Expected?
 http://localhost:8080/path

### What is actually happening?
 http://localhost:8080/noe/path

**Comment by xuezhimao** [comment]
补充：
3.el-menu组件外使用<router-link to="/path"></router-link>

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
