### ISSUE TITLE
[Bug Report] ElTabs re-rendering issue

### ISSUE THREAD

**Issue by dragosbodin** [ElemeFE/element#14626]
### Element UI version
2.6.1

### OS/Browsers version
macOS Mojave / Chrome 72.0.3626.121

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/6bukv2py/4/](https://jsfiddle.net/6bukv2py/4/)

### Steps to reproduce
1. Click on a switch in the tab-panes not in the tab contents
2. (Optional) Click multiple times
3. Component does not render changes
4. Change the tab and observe the Component re-rendering

### What is Expected?
Should re-render the tab-panes correctly.
This works fine in 2.4.11: https://jsfiddle.net/6bukv2py/5/

### What is actually happening?
The tab-panes are re-rendered when the active tab is changed.

**Comment by lucyhao** [comment]
Maybe what caused this issue is the same with #14601 .. I give a pull request https://github.com/ElemeFE/element/pull/14613 ..
