### ISSUE TITLE
[Feature Request] collapse-tags needs custom words

### ISSUE THREAD

**Issue by xuqingxi** [ElemeFE/element#14622]
### Existing Component
Yes

### Component Name
select 

### Description
select选择器作为多选项，‘+1’的表示法让人以为是重复的选项，希望能自定义文字，至少能改成省略号也好点，类似'...‘

**Comment by island205** [comment]
More detail please.

**Comment by xuqingxi** [comment]
![image](https://user-images.githubusercontent.com/38125259/54094900-001a4380-43df-11e9-92f1-6a11bbaf7bda.png)
希望圈起来的选项文字可以修改，如果内容可以左右滑动，不用收起来，就更好了

**Comment by island205** [comment]
Sorry, we have no plan to support this.
