### ISSUE TITLE
[Bug Report] About input component in safari browser, delete character cursor jump problem

### ISSUE THREAD

**Issue by HaoLJ** [ElemeFE/element#14621]
### Element UI version
2.6.0

### OS/Browsers version
macOS Mojave 10.14.1/  safari 12.0.1 (14606.2.104.1.1)

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
one：Type a character in the input box
two： Type a character in the input box
three：Delete the character

and then The cursor jumps to the end

### What is Expected?
The cursor is positioned at the delete position

### What is actually happening?
The cursor jumps to the end

**Comment by wacky6** [comment]
duplicate of https://github.com/ElemeFE/element/issues/14540
