### ISSUE TITLE
[Bug Report] Switching el-table under template results in data disorder

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/element#14628]
### Issues Title
 [Bug Report] 切换 template 下的 el-table , 却导致数据紊乱

### Element UI version
2.6.1

### OS/Browsers version
版本 71.0.3578.98（正式版本） （Window 64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/qingguipeng/g65xvyts/22/](https://jsfiddle.net/qingguipeng/g65xvyts/22/)

### Steps to reproduce
点击 `切换显示格式` 的按钮 ,

### What is Expected?
显示的数据正常,  且控制台无报错

### What is actually happening?
显示的数据不全, 且控制台报错

**Comment by PLQin** [comment]
怀疑是外层的 `v-if` 的问题 , 

将最外层的 `v-if` 修改为 `v-show` 后, 显示正常 : 

https://jsfiddle.net/qingguipeng/su4wt5kL/

**Comment by PLQin** [comment]
@baiyaaaaa @ziyoung 

Looking forward to replying and solving the problem

**Comment by ziyoung** [comment]
在 table 上添加 key。

**Comment by PLQin** [comment]
> 在 table 上添加 key。

/强 能够解决问题
