### ISSUE TITLE
[Bug Report] Official Web, Rate Component Code Block Displays Exceptions

### ISSUE THREAD

**Issue by zhangshichun** [ElemeFE/element#14638]
### Element UI version
2.6.1

### OS/Browsers version
Chrome 版本 66.0.3359.117（正式版本） （32 位）

### Vue version
2.6.8

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN //填官网链接报错啊我的哥](https://elementui.github.io/issue-generator/#/zh-CN //填官网链接报错啊我的哥)

### Steps to reproduce
展开代码块后，代码块高度为18px，存在纵向滚动条

### What is Expected?
完全展开

### What is actually happening?
只有18px

**Comment by SimonaliaChen** [comment]
Issues without a valid reproduction link will be closed directly.
