### ISSUE TITLE
[Bug Report] elementui el-upload on - ** can not work in Vue JSX render function

### ISSUE THREAD

**Issue by Simple2012hcz** [ElemeFE/element#14635]
### Element UI version
2.6.1

### OS/Browsers version
window10 pro

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1.定义上传组件渲染
getSingUpload(pitem){
            let self = this;
            let res;
            console.log("base url....single...",self.baseUrl);
            res = (
                            <el-tag class="prevar-main-item" span={2} style="background-color:#f4f4f5;text-align:center;">
                                <el-upload 
                                    class="upload-demo"
                                    action={self.baseUrl}
                                    before-remove={self.beforeRemove}
                                    before-upload={self.beforeUpload}
                                    on-success={self.handleUploadSuccess}
                                    multiple={false}
                                    withCredentials={true}
                                    accept="audio/mp3,audio/wav"
                                    auto-upload={true}
                                    file-list={self.fileList}
                                    http-request={self.singleAudioUpload}
                                    >
                                    <i class="el-icon-plus"></i>
                                </el-upload>
                            </el-tag>
                        
            );
            return res;
        }
2.render() 中使用
3.上传文件，http-request中可以得到异常，TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:2:14)

### What is Expected?
文件上传跟template中表现一致，都可以在success时候触发对应的事件

### What is actually happening?
before事件可以触发，on-**不可以触发。应该是跟jsx语法，默认开头on-冲突了。

**Comment by Simple2012hcz** [comment]
myable the reason is babel-preset-jsx ,deal with on-success to be an success event. can not work with elemtn onSuccess

**Comment by xiaodit** [comment]
it works on me
```
{...{
  props: {
    'on-success': () => {}
   }
  }
}}
```

**Comment by Simple2012hcz** [comment]
the config of babel is 
"devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/polyfill": "^7.2.5",
    "@babel/preset-env": "^7.3.1",
    "@vue/babel-helper-vue-jsx-merge-props": "^1.0.0-beta.2",
    "@vue/babel-preset-jsx": "^1.0.0-beta.2",
    "@vue/test-utils": "^1.0.0-beta.29",
    "autoprefixer": "^9.4.6",
    "babel-core": "^7.0.0-bridge.0",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^24.1.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "clean-webpack-plugin": "^1.0.1",
    "css-loader": "^2.1.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^3.0.1",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^24.1.0",
    "jest-serializer-vue": "^2.0.2",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss-loader": "^3.0.0",
    "purify-css": "^1.2.5",
    "sass-loader": "^7.1.0",
    "sass-resources-loader": "^2.0.0",
    "url-loader": "^1.1.2",
    "vue-hot-reload-api": "^2.3.1",
    "vue-jest": "^3.0.3",
    "vue-loader": "^15.6.2",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.5.22",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14",
    "webpack-merge": "^4.2.1"
  },
  "dependencies": {
    "@babel/runtime": "^7.3.1",
    "axios": "^0.18.0",
    "element-ui": "^2.5.2",
    "gojs": "^2.0.3",
    "mockjs": "^1.0.1-beta3",
    "svg-sprite-loader": "^4.1.3",
    "vue": "^2.5.22",
    "vue-router": "^3.0.2",
    "vuex": "^3.1.0"
  },

**Comment by ziyoung** [comment]
> it works on me
> 
> ```
> {...{
>   props: {
>     'on-success': () => {}
>    }
>   }
> }}
> ```

@Simple2012hcz
