### ISSUE TITLE
[Bug Report] el-dropdown nested in el-table can't be expanded or visible

### ISSUE THREAD

**Issue by ntnyq** [ElemeFE/element#14636]
### Element UI version
2.6.1

### OS/Browsers version
MacOS v10.14.3 / Chrome v72.0.3626.119 (Official Build) (64-bit)

### Vue version
2.6.8

### Reproduction Link
[https://codepen.io/ntnyq/pen/jJmGrj](https://codepen.io/ntnyq/pen/jJmGrj)

### Steps to reproduce
Just click the `Dropdown` button

### What is Expected?
The dropdown-list is visible at the bottom-end position of the dropdown button 

### What is actually happening?
It's invisible and has a `display: none` inline style.

**Comment by ziyoung** [comment]
```vue
<el-table-column label="Operations">
       <template slot-scope="scope">
       </template>
</el-table-column>
```

**Comment by molinla** [comment]
确实有效果` <template slot-scope="scope"></template>` 这个格式必须要有才行 也可以把 **slot-scope** 属性替换为 **v-slot** 这样后面的 scope 就可以删除掉
