### ISSUE TITLE
[Bug Report] Something wrong about!!!!!Element.eleme.io!!!

### ISSUE THREAD

**Issue by MaxZzyo** [ElemeFE/element#14634]
### Element UI version
0.1.0

### OS/Browsers version
all system / chrome 72.0.3626.119

### Vue version
2.6.8

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
the form ( https://elementui.github.io/issue-generator/#/zh-CN ) of reporting bugs also has bug! I cannot type links except for github

the real link is http://element-cn.eleme.io/#/zh-CN/component/rate
====bug list====
1. when i click 'expand' to get the sample code, it seems not good as the other components, and just happen in this ' rate ' component 
2. when i change the version of this site to the other version but not 2.6 via the top navigation, i cannot change it back to 2.6 through the top navigation

=== 中文===
https://elementui.github.io/issue-generator/#/zh-CN
这个报错用的网站，重现链接 这一栏，只给输入github的链接，真正下面出bug的页面却输不了

1. http://element-cn.eleme.io/#/zh-CN/component/rate  这个组件页面，点开显示代码，代码会出现在一个小框子里面，没法看到全部，但是可以复制出来

2. 整个组件网站的bug，点击最上面的导航条切换版本，切到2.5或者什么的，只要不是2.6，那你就没办法再通过点击那个版本切换再回到2.6版本了
而且你切换到2.5版本，上面那个版本号也显示的2.6

### What is Expected?
all is well

代码显示正常
切换版本功能正常

### What is actually happening?
somgthing wrong about the sample code
somgthing wrong about changing version of all site
代码显示有问题
切换版本功能有问题

**Comment by ziyoung** [comment]
现在恢复正常了。
