### ISSUE TITLE
这个时间获取到的格式是啥情况

### ISSUE THREAD

**Issue by pjialin** [ElemeFE/element#1463]
<img width="467" alt="qq20161130-0 2x" src="https://cloud.githubusercontent.com/assets/12911871/20717772/982841d2-b691-11e6-93b7-daa8b8343c4f.png">

<img width="326" alt="qq20161130-1 2x" src="https://cloud.githubusercontent.com/assets/12911871/20717774/9be62848-b691-11e6-932c-58f76bf75e87.png">

怎么获取的是这样 2016-11-02T06:37:39.000Z 的格式

**Comment by cycold** [comment]
typeof 下嘛,date  Object 吧

**Comment by pjialin** [comment]
@cycold 嗯，是date对象 有办法让它获取到的是input里的值吗

**Comment by Leopoldthecoder** [comment]
@pjialin 可以自行 format
