### ISSUE TITLE
[Bug Report] Cascader cascade selector options exception

### ISSUE THREAD

**Issue by 150148313** [ElemeFE/element#14639]
### Element UI version
2.6.1

### OS/Browsers version
jsfiddle

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/2rp3qcnt/3/](https://jsfiddle.net/2rp3qcnt/3/)

### Steps to reproduce
options 字段过多出现异常

### What is Expected?
正常联动

### What is actually happening?
options 字段过多出现异常

**Comment by 150148313** [comment]
能撤销吗

**Comment by ziyoung** [comment]
不是 element 的 bug 吧。
