### ISSUE TITLE
[Bug Report] DatePicker ignores firstDayOfWeek

### ISSUE THREAD

**Issue by daniele-orlando** [ElemeFE/element#14647]
### Element UI version
2.6.1

### OS/Browsers version
Chrome 71

### Vue version
2.6.8

### Reproduction Link
[JsFiddle](https://jsfiddle.net/Ltundkx0/3/)

### Steps to reproduce
On Element DatePicker, sets the property `firstDayOfWeek` to any value.

### What is Expected?
First day of week should change.

### What is actually happening?
Nothing happens.

**Comment by gmcinalli** [comment]
@daniele-orlando Look at that: https://jsfiddle.net/v69bxunh/

**Comment by daniele-orlando** [comment]
Thanks @gmcinalli.
