### ISSUE TITLE
[Bug Report] Nested expandable tables with fixed action columns

### ISSUE THREAD

**Issue by Ringhoo** [ElemeFE/element#14646]
### Element UI version
2.6.1

### OS/Browsers version
Windows 10 / Opera

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/98kur1fz/2/](https://jsfiddle.net/98kur1fz/2/)

### Steps to reproduce
see jsfiddle

### What is Expected?
Keep correct layout when expanding rows.

### What is actually happening?
When you use multiple nested expandable tables with FIXED action cols, the action col get messed up when 2  layers expand.

See link, to see what I mean.
https://jsfiddle.net/98kur1fz/2/

Removing the fixed attribute helps, but then its not fixed anymore...

**Comment by goforu** [comment]
The same issue. The expanded row breaks into two scrollable parts.
![image](https://user-images.githubusercontent.com/5236864/54272546-e46d9380-45be-11e9-93c3-739cfecec110.png)

Any workaround?

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by wwervin72** [comment]
is there any solution?
