### ISSUE TITLE
ie浏览器下ie9，ie10，ie11 table全部样式混乱

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1464]
ie浏览器下ie9，ie10，ie11 table全部样式混乱
![image](https://cloud.githubusercontent.com/assets/16740731/20719021/97e8d0b6-b695-11e6-9ad0-19d47177b3aa.png)

**Comment by Leopoldthecoder** [comment]
是指 border？官网上的例子会乱吗？

**Comment by yuanshengchao** [comment]
对的，boder会混乱，而且多选框也会混乱

**Comment by yuanshengchao** [comment]
刚刚在ie中测试就是有问题的，请查看截图。
![image](https://cloud.githubusercontent.com/assets/16740731/20748057/a529fb28-b727-11e6-9e16-fe040d31a28a.png)

**Comment by yuanshengchao** [comment]
请问如何解决，自己重新css？还是有解决方法

**Comment by furybean** [comment]
@yuanshengchao  已经找到原因，新版本会修复。

**Comment by furybean** [comment]
#1522 中的 border-collapse 那一行修复了这个问题。

**Comment by furybean** [comment]
@yuanshengchao  1.0.4 应该修复了这个问题，请测试。

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20858170/9f0e8066-b979-11e6-9af3-6e677ccf4c8f.png)
还是没有完全修改好呀。现在这个版本出现一个很大的bug，就是select组件出现默认的值是lable的值而不是value的值。
![image](https://cloud.githubusercontent.com/assets/16740731/20858177/d0cab084-b979-11e6-97bd-e888eff9af27.png)

**Comment by Leopoldthecoder** [comment]
@yuanshengchao Select 的问题请单独开一个 issue，并提供一下 demo。

**Comment by furybean** [comment]
@yuanshengchao Select 上的问题请另开 issue。图 1 中的问题是使用 1.0.4 版本的效果么？

**Comment by yuanshengchao** [comment]
是的，我就是使用1.0.4版本的问题，当时使用1.0.3的时候也有这个问题，忘记截图说明了

**Comment by yuanshengchao** [comment]
请问1.0.5版本是否已经解决了改兼容问题？

**Comment by Leopoldthecoder** [comment]
checkbox 旁边的省略号可以通过增大这一列的 `width` 解决。表头和内容不对齐的情况，我试了在 IE 9~11 下已经不出现了。如果还有问题，请提供 demo。
