### ISSUE TITLE
Setting a defaultvalue on the datepicker is ignored

### ISSUE THREAD

**Issue by kife-design** [ElemeFE/element#1465]
### ElementUI version
1.0.0-rc.2

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.0-rc.4

### Steps to reproduce
set a defaultvalue "2016" on v-model and pass it to the datepicker with the year format

### What is Expected?
The picker shows the value 2016

### What is actually happening?
The picker is showing the value 1970

**Comment by cycold** [comment]
try setting `type="year"`
```
<el-date-picker v-model="d"  type="year"> </el-date-picker>
```

**Comment by Leopoldthecoder** [comment]
@kife-design Please upgrade Element

**Comment by kife-design** [comment]
After some more research, i found that it is NOT working when the data is passed from a parent component, so the data is passed through a prop.

**Comment by p4m** [comment]
It works fine if the default value is formatted as :default-value (not default-value). The prop in the parent (el-form-item) can stay.

![image](https://user-images.githubusercontent.com/1651685/32051616-9e36477c-ba55-11e7-93a3-98345e563d9a.png)

**Comment by ayophanz** [comment]
not working on me, copy your code @p4m

**Comment by pnk0006** [comment]
[new Date(new Date().getTime() - 3600 * 1000 * 24 * 7), new Date()]
