### ISSUE TITLE
[Feature Request] more official icon or how to merge/build my icons and element-ui icon to a font file.

### ISSUE THREAD

**Issue by xbxbxb007** [ElemeFE/element#14658]
### Existing Component
是

### Component Name
ICON

### Description
More official icon or how to merge/build my icons and element-ui icon in a font file.  For example : log_in, sign_up, log_out, sign_in, password, gift,

**Comment by liub1934** [comment]
You can use iconfont like this `<i class="iconfont icon-collect"></i>`
Demo: [https://jsfiddle.net/cLvf39xg](https://jsfiddle.net/cLvf39xg)

**Comment by ziyoung** [comment]
@liub1934 thanks。
