### ISSUE TITLE
[Feature Request] How to change the el-button's type by javascript , for example , change type="danger" to type="success", it doesn't work , thank you !

### ISSUE THREAD

**Issue by water321** [ElemeFE/element#14659]
### Existing Component
是

### Component Name
el-button

### Description
能否动态改变el-button 的type值，比如初始type="danger"，点击后type值变为 success，试了好多次好像不行，求大牛帮助

<el-button :type="btn_status" @click="onStatus"></el-button>

onStatus() {
                this.btn_status = "success";
            }

**Comment by sinchang** [comment]
example code: https://jsfiddle.net/bkxj20uw/

**Comment by water321** [comment]
thank you , i will try once more
