### ISSUE TITLE
[Bug Report] el-radio-group don't work in JSX

### ISSUE THREAD

**Issue by xiaodit** [ElemeFE/element#14662]
### Element UI version
2.5.4

### OS/Browsers version
Microsoft Windows [版本 10.0.17763.316] / Chrome 72.0.3626.121

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
看这，看这
重现地址是这个: https://codesandbox.io/s/k3qy99mk4r

### What is Expected?
使用JSX的方式
 1. 可以监听事件
 2. 在`el-radio`组件里，如何实现改值属性的值，从而达到双向绑定的效果

### What is actually happening?
使用JSX的方式
 1. 遇到单选框不能监听值的变化事件
 2. 不知道如何在组件内部改变属性的值

**Comment by xiaodit** [comment]
its works lol
```
<el-radio-group
  value={this.radio}
  onChange={v => {
    console.log("value", v);
  }}
>
  <el-radio
    label={1}
    onChange={v => {
      this.radio = 1;
    }}
  >
     备选项
  </el-radio>
</el-radio-group>
```

**Comment by ZTrainWilliams** [comment]
its no works lol
```javascript
<el-radio-group
        value={this.radio}
        onChange={(v) => {
          console.log("value", v);
        }}
      >
        <el-radio-button
          label={1}
          onChange={(v) => {
            this.radio = v;
          }}
        >
          备选项1
        </el-radio-button>
        <el-radio-button
          label={2}
          onChange={(v) => {
            this.radio = v;
          }}
        >
          备选项2
        </el-radio-button>
      </el-radio-group>
```

**Comment by keepAwayFrom404** [comment]
<el-radio-group
  value={this.radio}
  onInput={v => {
    console.log("value", v);
  }}
>
  <el-radio
    label={1}
    onChange={v => {
      this.radio = 1;
    }}
  >
     备选项
  </el-radio>
</el-radio-group>
把onChange换成onInput可以生效（原因未知，可能是jsx监听的原生事件？）
