### ISSUE TITLE
[Bug Report] [Cascader cascade selector] expand-trigger: hover, expansion switch of secondary menu BUG

### ISSUE THREAD

**Issue by showbestriven** [ElemeFE/element#14669]
### Element UI version
2.6.1

### OS/Browsers version
win10/chrome  71.0.3578.98

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/5vwk0j9h/](https://jsfiddle.net/5vwk0j9h/)

### Steps to reproduce
先鼠标移到父级一，
然后再移动到父级二

### What is Expected?
鼠标移动到 父级一， 显示 父级一的子级
然后 鼠标移动到 父级二， 父级一的子级消失

### What is actually happening?
鼠标移动到 父级一， 显示 父级一的子级
然后 鼠标移动到 父级二， 父级一的子级【未消失】

**Comment by SimonaliaChen** [comment]
fixed in #15611
