### ISSUE TITLE
[Bug Report] el-badge element is cut in el-table column

### ISSUE THREAD

**Issue by OliverAndersRWE** [ElemeFE/element#14673]
### Element UI version
2.6.1

### OS/Browsers version
Windows

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/cd48htzw/](https://jsfiddle.net/cd48htzw/)

### Steps to reproduce
https://jsfiddle.net/cd48htzw/

### What is Expected?
the badg shouldn't be cut off

### What is actually happening?
the badge is shown only partially

**Comment by luckyCao** [comment]
add margin in el-badge class can solve your problem
```
.el-badge {
  margin: 20px 0;
}
```
https://jsfiddle.net/96a0twz3/
