### ISSUE TITLE
[Bug Report] Table custom dynamic display header compiled into a static file can not display normally, under NPM run dev normal

### ISSUE THREAD

**Issue by 102010cncger** [ElemeFE/element#14674]
### Element UI version
2.4.3

### OS/Browsers version
windows/chrome

### Vue version
2.3.3

### Reproduction Link
[ https://elementui.github.io/issue-generator]( https://elementui.github.io/issue-generator)

### Steps to reproduce

        <el-table-column v-for="item in features" :label="item.corCase.caseNo" align="center" :key="item.id">
          <el-table-column
            width="250" align="center" :prop="item.id" :key="item.id 'btn'">
            <template slot="header" slot-scope="scope">
              <a type="text" @click="addPrint(item)"><i class="el-icon-printer"></i>{{$t('打印')}}</a>
              <a type="text" @click="addCompare(item)"><i class="el-icon-star-on"></i>{{$t('加入对比')}}
              </a>
              <a type="text" @click="addFavorite(item)"><i
                class="el-icon-star-on"></i>{{$t('加入收藏')}}
              </a>
            </template>
            <template slot-scope="scope">
              {{scope.row[item.id]}}
            </template>
          </el-table-column>
        </el-table-column>
        <el-table-column label="Case10" align="center">
          <el-table-column width="200" align="center" prop="item1">
            <template slot="header" slot-scope="scope">
              <a type="text">打印</a>
              <a type="text">加入对比</a>
              <a type="text">加入收藏</a>
            </template>
          </el-table-column>
        </el-table-column>

### What is Expected?
编译后和npm run dev显示一致

### What is actually happening?
npm run dev正常,编译后表头内容为空

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by tansuomm** [comment]
how to do this;

**Comment by tfeitian** [comment]
I faced the same problem
