### ISSUE TITLE
[Bug Report] async menu & reuse DOM cause activeIndex error

### ISSUE THREAD

**Issue by mydaoyuan** [ElemeFE/element#14670]
### Element UI version
2.6.1

### OS/Browsers version
Mac OS 10.14 / Chrome/72.0.3626.121

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/9hv2skLa/8/](https://jsfiddle.net/9hv2skLa/8/)

### Steps to reproduce

使用。点击路由2，路由1 item 进入了  高亮状态。

--------
当`v-for`渲染 `menu-item`，使用了 `index` 作为 `key`时，`menu-item`会无法触发 `mounted` 钩子导致无法注册自身。

```
  mounted() {
      this.parentMenu.addItem(this);
      this.rootMenu.addItem(this);
  },
```

### What is Expected?
路由2高亮，进入active状态，activeIndex为路由2。

### What is actually happening?
路由1发生了高亮。

**Comment by ziyoung** [comment]
key 设置的不对https://jsfiddle.net/2gahpxt5/

**Comment by mydaoyuan** [comment]
> key 设置的不对https://jsfiddle.net/2gahpxt5/

动态路由里面可能key相同，但是其他属性改变了，`menu-item`源码里面没有 `watch`  而是在生命周期内判断，感觉不妥，而且引发的 `bug` 也比较难寻找，因为 `Chrome`  里面 `vue-tool` 查看数据模型都是正常的，但是表现不正常。
