### ISSUE TITLE
[Bug Report] The column traversed by multi-level header can not get the index of table data in the current cycle, which will lead to a new blank column when the table dynamically adds columns.

### ISSUE THREAD

**Issue by supershuo1** [ElemeFE/element#14681]
### Element UI version
2.6.1

### OS/Browsers version
macOs

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/u7hpg2Lq/1/](https://jsfiddle.net/u7hpg2Lq/1/)

### Steps to reproduce
新建一个带有数组的属性的对象数组
结构为[{name:'a',child:[]},{name:'b',child:[]}]
整个数组为表格要遍历的数据
child为要遍历的列

### What is Expected?
遍历的列可以正确获取到当前遍历的data数据的索引

### What is actually happening?
获取不到索引，会多展示一个空白列

**Comment by shiqian123** [comment]
我也碰到了这个问题

**Comment by shiqian123** [comment]
请问这个问题预计什么时候修复
