### ISSUE TITLE
[Bug Report] Select component cannot display arrow icon when using remote search

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#14689]
### Element UI version
2.6.1

### OS/Browsers version
win10 chrome

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/gjv7560m/](https://jsfiddle.net/gjv7560m/)

### Steps to reproduce
官网代码

### What is Expected?
显示箭头icon

### What is actually happening?
无法显示箭头icon，el-select__caret  icon部分只有  el-icon-   你們代码bug

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by 2yllll** [comment]
@luckyCao ![image](https://user-images.githubusercontent.com/9345667/55953475-c8791280-5c8e-11e9-880d-5c297596c73b.png)
![image](https://user-images.githubusercontent.com/9345667/55953502-de86d300-5c8e-11e9-8f96-2cf1a9b628b7.png)
When using remote and filterable, the suffix icon is empty. This is your code

**Comment by toandd98** [comment]
How to fix it?

**Comment by phamhuy361995** [comment]
> How to fix it?
you should add css to fix it
`.el-select {
  & .el-input .el-select__caret::before {
    content: "\e6e1"
  }

  & .el-input.is-focus .el-select__caret {
    transform: rotateZ(0deg);
  }
}`

**Comment by huangche007** [comment]
this way is useful for me，thx @phamhuy361995
