### ISSUE TITLE
el-date-picker type="year"

### ISSUE THREAD

**Issue by bevig64** [ElemeFE/element#1468]
el-date-picker type="year"的时候
第一次选择年份后再次点击输入框会变成
Thu Jan 01 1970 08:00:02 GMT+0800 (CST)
类似的格式
应该是把选中的年份当成了毫秒 加到了1970 上

**Comment by Leopoldthecoder** [comment]
好像官网文档上没有这个问题，给个 Demo 吧。

**Comment by bevig64** [comment]
http://element.eleme.io/#/zh-CN/component/date-picker
其他日期  年 的组件
第一次选择年份后再次点击输入框后就会变
操作环境是MACos 浏览器是chrome

**Comment by Leopoldthecoder** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10095631/20739515/48956752-b6f6-11e6-805e-66cee3b3413b.gif)

也是 macOS 和 chrome。能否提供一下动图？

**Comment by bevig64** [comment]
![default](https://cloud.githubusercontent.com/assets/9395260/20739989/92f01000-b6fa-11e6-8b8f-1743647edd63.gif)
chrome 54.0.2840.98 (64-bit)
mac 10.12.1 (16B2555)

**Comment by Leopoldthecoder** [comment]
和 #1367 问题一样，但是已经在 #1385 修掉了。清下缓存试试？或者点一下「在线运行」看看。

**Comment by bevig64** [comment]
恩 解决了 更新了就好了
