### ISSUE TITLE
[Bug Report] monthrange on v2.6.1 not work

### ISSUE THREAD

**Issue by tailenderY** [ElemeFE/element#14686]
### Element UI version
2.6.1

### OS/Browsers version
linux/chromium/72.0.3626.121

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
type='monthrange'  , focus , panel didn't show

### What is Expected?
show the monthrange picker panel and work

### What is actually happening?
didn't show the panel

**Comment by tailenderY** [comment]
2.6.1文档有，pr里程碑是2.7

**Comment by tomatosqq** [comment]
https://jsfiddle.net/y2065oh9/ 我这里也无法运行
