### ISSUE TITLE
[Bug Report] el-input can't work with validator inside a dialog

### ISSUE THREAD

**Issue by silentmissile** [ElemeFE/element#14688]
### Element UI version
2.6.1

### OS/Browsers version
windows 10 x64, Chrome 72 x64

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/bjhv5om2/](https://jsfiddle.net/bjhv5om2/)

### Steps to reproduce
click the button, then a parent dialog appear, then click OK, the child dialog would appear

then input and click OK, you will find the problem

### What is Expected?
I hope the validator can restrict the input between 0 to 1, it's float

and reject other inputs

in element-ui-2.4.11 this bug doesn't exist, in newer version until 2.7.0, it exists

### What is actually happening?
it would accept a non digital string, and pass the validator

it can't input float number, the '.' can't be input

**Comment by ziyoung** [comment]
see http://element.eleme.io/#/en-US/component/input#input

**Comment by silentmissile** [comment]
I add

type="number"

in el-input label

then it's resolved
