### ISSUE TITLE
[Bug Report] Select Component Remote Search

### ISSUE THREAD

**Issue by Mikerui** [ElemeFE/element#14687]
### Element UI version
2.6.1

### OS/Browsers version
Google Chrome/ 70.0.3538.110（正式版本） （64 位）

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/dcwun0v9/](https://jsfiddle.net/dcwun0v9/)

### Steps to reproduce
1.选中一个下拉框的数据
2.点击选中的那条，使用中文输入法搜索
3.没有点回车和值到输入框中，远程搜索方法触发了

### What is Expected?
没有点回车和值到输入框中，远程搜索方法不触发了

### What is actually happening?
没有点回车和值到输入框中，远程搜索方法触发了

**Comment by ziyoung** [comment]
无法重现。
