### ISSUE TITLE
[Bug Report] "show-overflow-tooltip" is invalid

### ISSUE THREAD

**Issue by changbingyao** [ElemeFE/element#14684]
### Element UI version
2.4.7

### OS/Browsers version
Google Chrome 72

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/6L2vL94y/7/](https://jsfiddle.net/6L2vL94y/7/)

### Steps to reproduce
<div class="layout">
    <div class="sidebar"></div>
    <div class="container">
         <div class="header"></div>
         <div class="home-container">
               <el-row>
                   <el-table :data="tableData3" tooltip-effect="light" style="width: 100%">
                       <el-table-column type="selection" width="55"></el-table-column>
                       <el-table-column label="日期"  width="120">
                           <template slot-scope="scope">{{ scope.row.date }}</template>
                        </el-table-column>
                        <el-table-column prop="name" label="姓名" width="120"></el-table-column>
                        <el-table-column prop="address" label="地址" width="100" show-overflow-tooltip></el-table-column>
                  </el-table>
              </el-row>
          </div>
     </div>
</div>

According to the above layout， adding “show-overflow-tooltip” attribute to “el-table-column” is invalid!

### What is Expected?
valid

### What is actually happening?
invalid

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
