### ISSUE TITLE
[Bug Report] Custom instructions are normal in version 2.5.17 and abnormal in 2.6.8. 

### ISSUE THREAD

**Issue by lzq920** [ElemeFE/element#14692]
### Element UI version
2.6.1

### OS/Browsers version
chrome 72

### Vue version
2.6.8

### Reproduction Link
[https://codepen.io/lzq920/full/OqOZPG](https://codepen.io/lzq920/full/OqOZPG)

### Steps to reproduce
open menu or close menu

### What is Expected?
If you do not have permissions, the menu does not display and delete dom

### What is actually happening?
all menu display

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
