### ISSUE TITLE
[Bug Report] Date picker automatically bring out start time

### ISSUE THREAD

**Issue by Lecrean** [ElemeFE/element#14695]
### Element UI version
2.4.11

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/6tbvufcz/2/](https://jsfiddle.net/6tbvufcz/2/)

### Steps to reproduce
1.选择一个时间范围
2.再次选择一个时间范围时，只选择一个时间，然后点击空白区域，隐藏日历。
3.再次选择一个时间范围，只选择一个时间

### What is Expected?
第三次选择时间范围的时候，能够正常的选择开始时间和结束时间

### What is actually happening?
第三次选择时间范围时，会将第一次选择的开始时间作为一个节点，选择的另一个时间作为另一个节点

**Comment by Lecrean** [comment]
学习了一波源码，发现data-table只有在点击时，才会切换selecting的状态
![image](https://user-images.githubusercontent.com/30769658/54657097-1329c380-4b03-11e9-8f15-7ba8c5701eb7.png)
如果只是点击其他区域来隐藏picker的话，这个状态是不会被修改的，再次显示picker的时候，选择就会有问题

**Comment by dabiaogedada** [comment]
我也遇到这个问题，修改resetView方法后就可以解决，暂时未发现其它问题
```
resetView: function resetView() {
   ...
  this.rangeState.selecting = false;
}
```

**Comment by Lecrean** [comment]
> 我也遇到这个问题，修改resetView方法后就可以解决，暂时未发现其它问题
> 
> ```
> resetView: function resetView() {
>    ...
>   this.rangeState.selecting = false;
> }
> ```

感谢，这个方法确实有效
