### ISSUE TITLE
[Bug Report] NavMenu component iPad fold state usage exception

### ISSUE THREAD

**Issue by Neverland** [ElemeFE/element#14697]
### Element UI version
2.6.1

### OS/Browsers version
ios12

### Vue version
2.6.8

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/menu/](http://element.eleme.io/#/zh-CN/component/menu/)

### Steps to reproduce
点击菜单项如菜单项1后，菜单消失，然后在弹出。

### What is Expected?
点击菜单项如菜单项1后，菜单消失

### What is actually happening?
点击菜单项如菜单项1后，菜单消失，然后在弹出。

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.
