### ISSUE TITLE
[Feature Request] Timeline

### ISSUE THREAD

**Issue by ldb923** [ElemeFE/element#14699]
### Existing Component
否

### Component Name
Timeline

### Description
Why not make a timeline function? Used to record a step by step process. This is a must-show for a company that has been established for a long time.
Horizontal Portrait One-sided timeline on both sides. I hope that the engineer who is hungry sees my suggestion.

Thank you guys who are Eleme, provide such a good component for our developers to use.  英文不行 just   google translate

**Comment by island205** [comment]
https://deploy-preview-14694--element.netlify.com/#/zh-CN/component/timeline
