### ISSUE TITLE
[Bug Report] Label data in custom tabs cannot be rendered in real time

### ISSUE THREAD

**Issue by StringKe** [ElemeFE/element#14696]
### Element UI version
2.6.1

### OS/Browsers version
Macos / electron

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/StringKE/dk43Lb7h/7/](https://jsfiddle.net/StringKE/dk43Lb7h/7/)

### Steps to reproduce
1. Create a tabs using loops
2. Customize the label in the tab
3. Modify the data bound by label

### What is Expected?
Label binding data can be updated in real time

### What is actually happening?
Label binding data cannot be updated in real time

**Comment by ziyoung** [comment]
Duplicate of #14712
