### ISSUE TITLE
[Feature Request] Tree folding problem

### ISSUE THREAD

**Issue by AngryBirdsFighting** [ElemeFE/element#14705]
### Existing Component
Yes

### Component Name
Tree

### Description
Google Chrome  65.0.3325.181

After setting the ‘default-expanded-keys’ attribute, the tree must be clicked twice to fold. I have seen this problem in the official website demo. How to solve it? ?

**Comment by ziyoung** [comment]
reproduction link http://element.eleme.io/#/en-US/component/tree#default-expanded-and-default-checked

**Comment by ziyoung** [comment]
The bug only appears on the doc website. It works fine in codepen.

**Comment by ziyoung** [comment]
It also works fine in development env.
