### ISSUE TITLE
select远程模式中下拉有选中值情况下，键盘上下去选择值时重新发起了搜索

### ISSUE THREAD

**Issue by leegoway** [ElemeFE/element#1470]
### ElementUI version
1.0.3

### OS/Browers version
macOS/Chrome 53 

### Vue version
2.0.3

### Steps to reproduce
select远程模式，先搜索选中A值，再重新搜索下拉框中有之前选中A值情况下，默认会选中A值，此时可以鼠标选中没任何问题，但如果使用键盘上下键选择，搜索框中就变成搜索A值了而非搜索的条件，又重新发起了一次搜索，其实我的目的只是去从下拉option中选中我想要的值

**Comment by Leopoldthecoder** [comment]
没看懂，麻烦给个 demo，最好再详细描述一下。

**Comment by leegoway** [comment]
**我这里也不是稳定复现，但经常出现。我在这里描述一下：**
有个select远程模式框
    第一次搜索字母A，下拉中有选项EA,FA。此时选中FA。
    第二次搜索字母F，下拉中有选项FA，FF。此时因为有之前选中的项，所以输入框中搜索的F条件变成FA了。到这里还没问题，接下来使用键盘上下按键去浏览选项，就会重新发起一次搜索FA的条件，这不是想要的现象。我只是使用键盘上下按键去浏览选项而已，却又发起了一次搜索FA。

**Comment by Leopoldthecoder** [comment]
试试看 1.0.5 版本还有没有这个问题。

**Comment by Leopoldthecoder** [comment]
超过 7 天没有反馈的 issue 会被关闭。如果需要的话可以重新打开。
