### ISSUE TITLE
[Feature Request] Support blur event as the trigger of the validation for el-cascader component

### ISSUE THREAD

**Issue by xiGUAwanOU** [ElemeFE/element#14702]
### Existing Component
Yes

### Component Name
el-cascader el-form-item

### Description
Currently, the cascader only generates `el.form.change` event for validating, `el.form.blur` is not supported. However, this will cause problem if the value in the cascader is loaded asynchronously after component is created. This will cause the `el.form.change` event being triggered, and thus trigger the validation, and the green border will be shown (or even red border with error message if the loaded value is invalid).

There is a fiddle showing this behaviour: [https://jsfiddle.net/sn1L5867/](https://jsfiddle.net/sn1L5867/)

After asynchronous job is done, the cascader has a green border, because the validation has already been triggered, but the input doesn't have the green border.

It would be great, if the `el.form.blur` event can be dispatched after the `visible-change` event, so that only if the user has closed the cascader menu, the validation event will be triggered.

I've locally prepared a change. If needed, I could create a PR.

**Comment by ziyoung** [comment]
@xiGUAwanOU pr welcome. 👍

**Comment by miaoruifeng** [comment]
Is this a bug？？？
