### ISSUE TITLE
[Bug Report] el-table Loading Affects the Active-color Attribute of el-switch

### ISSUE THREAD

**Issue by MontyMa** [ElemeFE/element#14708]
### Element UI version
2.4.11

### OS/Browsers version
MacOS Mojave 10.14.3 ；Safari 12.0.3 / Google Chrome 70.0.3538.77

### Vue version
2.6.8

### Steps to reproduce
分别把 el-switch 组件 放置到 el-table 上方和下方，并设置el-switch的 active-color 属性，发现写在 el-table 上方的 el-switch 的 active-color 可以正常加载颜色，但是写在 el-table 下方的 el-switch 的 active-color 属性则加载异常。代码如下：
```
<!--可以正常加载 active-color-->
<el-switch
        v-model="showLittle"
        active-color="#DDAA62"
        inactive-color="#50505E"
        active-text="sdfsdf">
</el-switch>
<el-table>
        <el-table-column
          prop="name"
          label="名字"
        />
</el-table>
<!--不能正常加载 active-color-->
<el-switch
        v-model="showLittle"
        active-color="#DDAA62"
        inactive-color="#50505E"
        active-text="sdfsdf">
</el-switch>
```
### What is Expected?
el-table 加载时不阻塞 其他组件样式加载

### What is actually happening?
el-table 加载时阻塞 其他组件样式加载

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
