### ISSUE TITLE
[Bug Report] timepicker changes itself after clicking

### ISSUE THREAD

**Issue by ModyQyW** [ElemeFE/element#14700]
### Element UI version
2.6.1

### OS/Browsers version
Windows 10 Enterprise 2016 LTSB, Chrome 72.0.3626.121 (Official Build) (64-bit)

### Vue version
2.6.8

### Reproduction Link
[https://github.com/ModyQyW/vue-test](https://github.com/ModyQyW/vue-test)

### Steps to reproduce
1. open the reproduction link
2. clone the repository, install dependencies and serve
3. follow the tip and open the website
4. just click

You can also see the gif in README.

I also set a online demo. But then I found it wont happen online. It only happens locally. Check here: https://modyqyw.top/vue-test/dist/#/

### What is Expected?
only shows time picker but not changes the time locally and online

### What is actually happening?
not only shows time picker but also changes the time locally, only shows time picker but not changes the time online

**Comment by ModyQyW** [comment]
Addition:
Node v10.15.3
npm v6.4.1

**Comment by luckyCao** [comment]
can‘t reproduce
