### ISSUE TITLE
[Bug Report] el-dropdown

### ISSUE THREAD

**Issue by yoonasy** [ElemeFE/element#14709]
### Element UI version
2.4.11

### OS/Browsers version
windows    /  73.0.3683.75 (正式版本) （32 位） (cohort: 73_75_Win)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
不能绑定click事件
点击不会触发 
```
<el-dropdown split-button type="primary" @click="handleClick">
  更多菜单
  <el-dropdown-menu slot="dropdown">
    <el-dropdown-item>黄金糕</el-dropdown-item>
    <el-dropdown-item>狮子头</el-dropdown-item>
    <el-dropdown-item>螺蛳粉</el-dropdown-item>
    <el-dropdown-item>双皮奶</el-dropdown-item>
    <el-dropdown-item>蚵仔煎</el-dropdown-item>
  </el-dropdown-menu>
</el-dropdown>
```

http://element-cn.eleme.io/#/zh-CN/component/dropdown

官方文档上提供了此方法~

### What is Expected?
可以正常点击菜单触发点击事件 或传入参数给菜单

### What is actually happening?
不会触发

**Comment by luckyCao** [comment]
[2.4.11](http://element-cn.eleme.io/2.4/#/zh-CN/component/dropdown#hong-fa-dui-xiang) 的例子，第二个菜单绑定了 click 事件，可以触发。
