### ISSUE TITLE
[Feature Request] MenuItem activation state of NavMenu component needs to be cleared when is-activity is not hit

### ISSUE THREAD

**Issue by wxhccc** [ElemeFE/element#14713]
### Existing Component
是

### Component Name
NavMenu

### Description
NavMenu组件的default-active属性变化时，如果值没有匹配上任何MenuItem的index，会被忽略掉，导致之前的标记状态is-active不会更新，从而和路由不匹配（很多路由不会有菜单项，比如个人中心修改密码页面）。希望在下个版本里加个新特性在未匹配的时候清除之前的标记状态，此特性不会对之前版本有什么影响，望采纳，谢谢

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.

**Comment by drinkingcode** [comment]
@wxhccc what's your solution?
