### ISSUE TITLE
[Bug Report] could not open the jsfiddle example in the document

### ISSUE THREAD

**Issue by xsbchen** [ElemeFE/element#14716]
### Element UI version
2.6.1

### OS/Browsers version
macOS/Chrome 73

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
国内电信网络无法访问jsfiddle.net

### What is Expected?
迁移到https://codepen.io

### What is actually happening?
无法访问https://jsfiddle.net

**Comment by ziyoung** [comment]
@xsbchen jsfiddle 被墙了。以后 element-cn 统一使用 jsrun.com

**Comment by xsbchen** [comment]
@ziyoung jsrun.com 是什么来的？

**Comment by ziyoung** [comment]
@xsbchen jsrun.net。本想切换成 jsrun.net 的，但是 jsrun 不支持 post。现在统一换成 codepen 了。#14747
