### ISSUE TITLE
El-table performance issues

### ISSUE THREAD

**Issue by goofying** [ElemeFE/element#14729]
### Existing Component
是

### Component Name
ElTable

### Description
1. ElTable在hover行的时候也会渲染整个表格，在行数比较多的情况下性能极差

**Comment by island205** [comment]
please provide a valid reproduction link in  http://jsrun.net/TwXKp/edit.

**Comment by yangger6** [comment]
http://jsrun.net/KTXKp/play

**Comment by island205** [comment]
@ziyoung

**Comment by ziyoung** [comment]
ref #14729

**Comment by TaylerTao** [comment]
2.5.4版本中，每页500条的table很流畅；2.6.0之后就很卡
