### ISSUE TITLE
[Bug Report] el-input-number not trigger change event under Edge browser.

### ISSUE THREAD

**Issue by jsyzthz** [ElemeFE/element#14725]
### Element UI version
2.6.1

### OS/Browsers version
Win10/ Edge44.17763.1.0

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/ebsvq12z/](https://jsfiddle.net/ebsvq12z/)

### Steps to reproduce
1.open url under Edge(44.17763.1.0)  browser
2.pls manual input the unit price,don't use mouse to click  /- to change the value

### What is Expected?
total value should be calculate automatically

### What is actually happening?
nothing changed

**Comment by jsyzthz** [comment]
element ui v1.4.0 works fine.
demo: https://jsfiddle.net/6tLnvtvz/2/
any update for this?
Thanks!

**Comment by beiding110** [comment]
Yes, when I'm directly input in the input-box, the console will report an error like:
0: Unable to get property 'isPersonal' of undefined or null reference

**Comment by beiding110** [comment]
not sure, but v2.6.3 seems to fixed the problem.

**Comment by jsyzthz** [comment]
Hi @beiding110
Thanks , i check in v2.6.3, it has been fixed. 
https://jsfiddle.net/kw4nyp1d/
