### ISSUE TITLE
[Bug Report] Popover sometimes not works on hover with SSR (Nuxt)

### ISSUE THREAD

**Issue by invisor** [ElemeFE/element#14728]
### Element UI version
2.6.1

### OS/Browsers version
macOS Mojave / Chrome 72.0.3626.121

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/n84p17dL/](https://jsfiddle.net/n84p17dL/)

### Steps to reproduce
REPRODUCTION LINK: https://codesandbox.io/s/381794rw46

Refresh sandbox browser and hover mouse on button. It not works first time always, and may not works several times more

### What is Expected?
Popover should be shown on hover mouse

### What is actually happening?
Hover popover not shows

**Comment by ziyoung** [comment]
@invisor I find it works in jsfiddle. Is this a nuxt bug?

**Comment by invisor** [comment]
@ziyoung no, I believe this is element-ui bug when it working with SSR
