### ISSUE TITLE
[Bug Report] Click on a button other than the menu to trigger the page jump. The active status of the original menu will not disappear.

### ISSUE THREAD

**Issue by ansike** [ElemeFE/element#14723]
### Element UI version
2.6.1

### OS/Browsers version
macos10.14.3 chrome 73.0

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/ansike/wr5xse0L/27/](https://jsfiddle.net/ansike/wr5xse0L/27/)

### Steps to reproduce
1.点击系统管理的系统列表页，内容变化，菜单变红
2.点击系统管理的系统详情页，内容变化，系统列表页恢复，系统详情页菜单变红。
3.点击首页按钮，内容变化，【系统详情页菜单没有恢复！！！】

### What is Expected?
点击菜单以外的的按钮，页面跳转，内容变化，系统详情页菜单恢复。
请确定以下menu.vue中的handleItemClick，updateActiveIndex等方法
activeIndex绝对不能只依赖点击事件来确定
最好重新考虑以下的顺序
var item = this.items[val] || this.items[this.activeIndex] || this.items[this.defaultActive];

### What is actually happening?
点击首页按钮，内容变化，【系统详情页菜单没有恢复！！！】

**Comment by ziyoung** [comment]
“首页”在 menu 中不存在。

**Comment by ansike** [comment]
> “首页”在 menu 中不存在。

可能我的表述有问题，但是你可以进入JSFiddle中点击查看一下

**Comment by Huauauaa** [comment]
el-button也chrome浏览器中也有类似问题,点击之后,离开,还是激活状态,在safari中的行为是正常的
