### ISSUE TITLE
[Bug Report] el-steps dynamic rendering el-step

### ISSUE THREAD

**Issue by sunchenguang** [ElemeFE/element#14720]
### Element UI version
2.6.1

### OS/Browsers version
macos10.14.3  chrome 73.0

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/c745tbos/](https://jsfiddle.net/c745tbos/)

### Steps to reproduce
1. 设置默认items是[]
2. 设置定时器模拟从服务端取数据，重新设置item
3.  重新渲染后发现顶部的序号顺序错误，最后一个el-step的样式错误，没有自动与右边界对齐

### What is Expected?
items动态变化后，el-steps的序号正确，样式正常

### What is actually happening?
items动态变化后，el-steps的序号错误，最后一个el-step的样式异常

**Comment by lucyhao** [comment]
I think this one make sense and can fix your issue..  https://jsfiddle.net/9h81t53p/

**Comment by sunchenguang** [comment]
@lucyhao yes, this way can work normal.  your way is Full update items.

But i want to know if `el-steps` component should solve  `Partial update el-step` problem. 

you can understand what i mean

**Comment by lucyhao** [comment]
maybe not in this version. I saw the sources.. I don't think it has implemented this feature. Seems this isn't any code to detect the <el-step>'s real pos.

**Comment by sunchenguang** [comment]
Because there are ways to solve this problem， just close this issue

**Comment by xujialiang** [comment]
> I think this one make sense and can fix your issue.. https://jsfiddle.net/9h81t53p/

use index, step's sequence is right
