### ISSUE TITLE
[Bug Report] Nuxt icons failing to load: OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by DiegoGallegos4** [ElemeFE/element#14738]
### Element UI version
2.6.1

### OS/Browsers version
Chrome Version 72.0.3626.121

### Vue version
2.6.9

### Reproduction Link
[https://github.com/DiegoGallegos4/element-ui-issue](https://github.com/DiegoGallegos4/element-ui-issue)

### Steps to reproduce
Run :
`yarn generate`

and run as if its going to be server side rendered. 

```
const path = require('path')
const express = require('express')
const app = express()
const { Nuxt } = require('nuxt')
const config = require('./nuxt.config.js')

const nuxt = new Nuxt(config)

app.use('/_nuxt', express.static(path.join(__dirname, '.nuxt', 'dist')))
app.use((req, res) => setTimeout(() => nuxt.render(req, res), 0))

module.exports = app
```

### What is Expected?
To load icons

### What is actually happening?
Element UI cannot load icons on `yarn generate`. Icons are loading ok on development mode. 

Error: 
```
Failed to decode downloaded font: http://localhost:3001/_nuxt/fonts/5534bd3.woff
OTS parsing error: invalid version tag
```

Icons look like boxes.

**Comment by DiegoGallegos4** [comment]
Also getting: 
```
OTS parsing error: sfnt size overflow
OTS parsing error: incorrect entrySelector for table directory
```

**Comment by ziyoung** [comment]
@DiegoGallegos4 please provide a simple demo.
