### ISSUE TITLE
The template of [Bug Report] table column uses components to manipulate row data, which results in multiple tables rendering and affects performance

### ISSUE THREAD

**Issue by nabaonan** [ElemeFE/element#14734]
### Element UI version
2.6.1

### OS/Browsers version
windows 7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xj9qref7/](https://jsfiddle.net/xj9qref7/)
[https://codesandbox.io/s/wn92x0k1kl](https://codesandbox.io/s/wn92x0k1kl)

### Steps to reproduce
在table的column定义时候，使用template  scope-slot传入行对象，给子组件，然后在子组件上用v-model绑定行对象的属性，子组件内通过emit方式更改该属性，导致列表所有行重新渲染

### What is Expected?
不导致所有行重新渲染，只渲染当前行

### What is actually happening?
所有行渲染，影响性能

**Comment by nabaonan** [comment]
大佬们，啥时候帮忙解决一下

**Comment by ziyoung** [comment]
jsfiddle 的例子有问题的呀。更新一下吧。

**Comment by nabaonan** [comment]
> jsfiddle 的例子有问题的呀。更新一下吧。

看codesandbox的那个把，jsfiddle从那上面复制 的

**Comment by ziyoung** [comment]
Duplicate of #14734
