### ISSUE TITLE
[Feature Request] Table component height calculation when there is a horizontal scroll bar and the horizontal scroll bar height is customized

### ISSUE THREAD

**Issue by frljx** [ElemeFE/element#14731]
### Existing Component
Yes

### Component Name
Table

### Description
如题，表格高度看起来总是根据浏览器默认的横向滚动条高度做的计算

**Comment by frljx** [comment]
look like
![image](https://user-images.githubusercontent.com/10876080/54432500-5b905c80-4764-11e9-91fd-e36a265d4465.png)

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
