### ISSUE TITLE
[Feature Request] el-scrollbar event name

### ISSUE THREAD

**Issue by as236676674** [ElemeFE/element#14736]
### Existing Component
是

### Component Name
el-scrollbar

### Description
请问下el-scrollbar这个滚动条组件怎么监听滚动事件 并且取得滚动条滚动的高度 方法名是什么 ？

**Comment by luckyCao** [comment]
el-scrollbar 是一个内部组件，不暴露给用户，如果需要使用 scrollbar 的功能，建议找个第三方组件。

**Comment by prd-tin-dang** [comment]
You can add event listerner by class: el-scrollbar__wrap
mounted() {
// ref=scrollBar
  this.$refs.scrollBar.querySelector('.el-scrollbar__wrap').addEventListener('scroll', () => { // doing thing here} )
}
unmounted() {
  this.$refs.scrollBar.querySelector('.el-scrollbar__wrap').removeEventListener('scroll')
}
