### ISSUE TITLE
Style issues with nesting tabs in [Bug Report] tabs

### ISSUE THREAD

**Issue by LemonAppleMo** [ElemeFE/element#14740]
### Element UI version
2.6.1

### OS/Browsers version
macOS 10.13.6 (17G65) / chrome 72.0.3626.121（正式版本）

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/dzckny9v/](https://jsfiddle.net/dzckny9v/)

### Steps to reproduce
内部tabs的第一个页签与最后一个各多余20px，导致下方active样式出现偏离。

### What is Expected?
可以正常显示

### What is actually happening?
无法正常显示

**Comment by lucyhao** [comment]
Because it used the top class name "el-tabs--border-card".. Can use your own css to cover it..

`
<style>
.my-tabs .el-tabs--top .el-tabs__item.is-top:nth-child(2),
.my-tabs .el-tabs--top .el-tabs__item.is-top:last-child{padding-left:0px !important}
</style>
<div class="my-tabs">
      <el-tabs>
        <el-tab-pane label="用户管理" name="first">用户管理</el-tab-pane>
        <el-tab-pane label="配置管理" name="second">配置管理</el-tab-pane>
        <el-tab-pane label="角色管理" name="third">角色管理</el-tab-pane>
        <el-tab-pane label="定时任务补偿" name="fourth">定时任务补偿</el-tab-pane>
      </el-tabs>
    </div>
   `

**Comment by lucyhao** [comment]
Because it used the top class name "el-tabs--border-card".. Can use your own css to cover it..

`<style>
.my-tabs .el-tabs--top .el-tabs__item.is-top:nth-child(2),
.my-tabs .el-tabs--top .el-tabs__item.is-top:last-child{padding-left:0px !important}
</style>
`

`<div class="my-tabs">
      <el-tabs>
        <el-tab-pane label="用户管理" name="first">用户管理</el-tab-pane>
        <el-tab-pane label="配置管理" name="second">配置管理</el-tab-pane>
        <el-tab-pane label="角色管理" name="third">角色管理</el-tab-pane>
        <el-tab-pane label="定时任务补偿" name="fourth">定时任务补偿</el-tab-pane>
      </el-tabs>
    </div>`

**Comment by LemonAppleMo** [comment]
<style>
.my-tabs .el-tabs--top .el-tabs__item.is-top:nth-child(2){padding-left:0px !important}
.my-tabs .el-tabs--top .el-tabs__item.is-top:last-child{padding-right:0px !important}
</style>
这样应该比较正确。但是我觉得组件之间不应该互相干扰，应该在.el-tabs--top.el-tabs--border-card .el-tabs__item:last-child这里，加一个 > .el-tabs__header 来确保只有border-card的形式下才采用这种样式

**Comment by LemonAppleMo** [comment]
小小的建议

**Comment by lucyhao** [comment]
是的。你说的是对的。。。我只是用第三方开发者的角度，我们能怎么样来暂时fix这个issue. 在从根上解决这个问题，需要开发者来fix它。

**Comment by LemonAppleMo** [comment]
嗯，好的

**Comment by ziyoung** [comment]
不保证在嵌套时样式。建议用户通过覆盖 CSS 解决。
