### ISSUE TITLE
[Feature Request] How to implement cross-tree dragging with tree components

### ISSUE THREAD

**Issue by zhanjunhao** [ElemeFE/element#14756]
### Existing Component
是

### Component Name
Tree 树形控件

### Description
现在有个需求就是A组件是个树形结构 B组件是个API接口模板 数据结构不定也可能是有规律的树形 需要将A组件里头的n个子元素 拖拽至B组件的树形里头 对应映射某个键或值 请问tree组件该如何去实现 跨树拖拽

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
