### ISSUE TITLE
Questions of [Bug Report] el-input after v2.5.0 update

### ISSUE THREAD

**Issue by GavinZhuLei** [ElemeFE/element#14754]
### Element UI version
2.5.0

### OS/Browsers version
mac/chorme

### Vue version
2.6.9

### Reproduction Link
[https://github.com/ElemeFE/element/pull/13471](https://github.com/ElemeFE/element/pull/13471)

### Steps to reproduce
使用插槽向父组件传递slotProps，想在父组件中用el-input绑定修改值时重现

### What is Expected?
在父组件中可以像之前版本一样能够修改该值

### What is actually happening?
无法修改该值

### 示例代码
```html
<span>
  <slot v-bind:blank="model">
    {{ model.abc }}
  </slot>
</span>

<component>
  <template v-slot:default="slotProps">
    {{ slotProps.model.abc }}
    <el-input v-model="slotProps.model.abc"></el-input>
  </template>
</component>
```

**Comment by wacky6** [comment]
Please provide a valid jsfiddle / codepen.

**Comment by robert-moore** [comment]
Running into the same issue after updating to 2.6.4

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
