### ISSUE TITLE
[Bug Report] el-table row-click event fired when a button clicked in a row, two events fired per one user action

### ISSUE THREAD

**Issue by omerciftcibasi** [ElemeFE/element#14752]
### Element UI version
2.6.1

### OS/Browsers version
Chrome 72.0.3626.121 (Resmi Derleme) (64 bit) 

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/4ghose9L/2/](https://jsfiddle.net/4ghose9L/2/)

### Steps to reproduce
- row-click and button click event have different functionality and it is needed to procces only function run per one user action 
row-cliked and button clicked event are fired at same time when user clicks the button.

when cliked a button inside a cell el-table fires row clicked event button cliked event at the same time.

### What is Expected?
only button clicked event needs to be fired.

### What is actually happening?
row clicked and button clicked evens are fired at the same time.

**Comment by wsyxzxs** [comment]
Add @click.stop to the button to prevent bubbles

**Comment by omerciftcibasi** [comment]
@wsyxzxs for the comment and it solves my problem.

**Comment by luckyCao** [comment]
@wsyxzxs thanks

**Comment by PhillippOhlandt** [comment]
Hello, I have a similar issue but with a checkbox. The checkbox just uses a `value` property because the state wether it is checked or not is stored outside. I want to toggle it by clicking the entire row which works fine but when I click directly into the checkbox, I get the `row-click` event twice which checks and unchecks the checkbox.

```
          el-table-column(align="right")
            template(#default="{ row }")
              el-checkbox(:value="isSelected(row)")
```

The solution above does not work for this case. Any ideas?

**Comment by KR34T1V** [comment]
> Hello, I have a similar issue but with a checkbox. The checkbox just uses a `value` property because the state wether it is checked or not is stored outside. I want to toggle it by clicking the entire row which works fine but when I click directly into the checkbox, I get the `row-click` event twice which checks and unchecks the checkbox.
> 
> ```
>           el-table-column(align="right")
>             template(#default="{ row }")
>               el-checkbox(:value="isSelected(row)")
> ```
> 
> The solution above does not work for this case. Any ideas?

Same problem I am having now
