### ISSUE TITLE
[Bug Report] Microsoft's non-English input method causes ElSelect to fail when configuring filterable and clearable

### ISSUE THREAD

**Issue by FlareStone** [ElemeFE/element#14767]
### Element UI version
2.6.1

### OS/Browsers version
Windows 10 / Chrome 72.0.3626.119

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/zhtr888/0xh7pfdg/](https://jsfiddle.net/zhtr888/0xh7pfdg/)

### Steps to reproduce
1.切换到微软中文输入法，在Select中输入任意值，不要点回车或空格
2.移动鼠标，触发mouseenter或mouseleave事件，可以看到输入的内容消失（可能由于showClose重新计算引起ElSelect重新渲染导致）
3.点击Select外使其失去焦点，此时ElSelect中的ElInput的compositionend事件并未触发
4.再次在Select输入任意值，发现过滤功能失效

### What is Expected?
在输入法输入一半时点击Select外面使其失去焦点后，Select的过滤功能仍可以正常工作

### What is actually happening?
在输入法输入一半时点击Select外面使其失去焦点后，Select的过滤功能无法正常工作

**Comment by wacky6** [comment]
fix in https://github.com/ElemeFE/element/pull/14572
