### ISSUE TITLE
[Feature Request] Cascader Cascader Selector Open Custom Search Method

### ISSUE THREAD

**Issue by mamying** [ElemeFE/element#14761]
### Existing Component
是

### Component Name
Cascader 级联选择器

### Description
Cascader 级联选择器 开放自定义搜索方法
如同Select 选择器 一样提供 filter-method 自定义搜索方法
业务实例：省/市/县 级联选择  可以通过拼音来进行搜索

**Comment by ziyoung** [comment]
Duplicate of #13339
