### ISSUE TITLE
table勾选的时候 触发 handleSelectionChange事件如何才能获取 table所在行的序列 index

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#1476]
### ElementUI version

1.0.2
### Vue version

v2.0.3

**Comment by Leopoldthecoder** [comment]
试试这个：http://jsfiddle.net/gsssa39d/

**Comment by liuzhibin123** [comment]
table怎么获取勾选行的dom 呢？
 因为 我想要给所有勾选的行 设置背景颜色。
