### ISSUE TITLE
怎样覆盖原有样式

### ISSUE THREAD

**Issue by chaohuaGH** [ElemeFE/element#1477]
### What is actually happening?
遇到很多次需要修改组件样式的地方，无论加 css, id, !important等都无法修改。
e.g:
el-input的 border-radius就不能覆盖。
请帮我看下这类问题，在不改变index.css的基础上怎么合理的进行处理，谢谢了。

**Comment by ryannan** [comment]
`
.el-input
    input
        border-radius: 50%
`

**Comment by jikkai** [comment]
#377

**Comment by Leopoldthecoder** [comment]
首先，确认你的 CSS 选择器选中了需要修改的元素：http://jsfiddle.net/leopoldthecuber/31vyxpve/ ；

其次，如果是 `scoped` 的问题，请参考楼上的链接。
