### ISSUE TITLE
[Feature Request] Pagination slot内容无法动态更新（虽然可以通过直接操作dom达到更新效果）

### ISSUE THREAD

**Issue by jingxiaotian** [ElemeFE/element#14771]
### Existing Component
是

### Component Name
Pagination

### Description
建议 slot传出一个slot-scope。

**Comment by 2366472758** [comment]
请问你这个问题解决了吗，我也遇到了

**Comment by cjjlovedsn** [comment]
刚刚升级后也是发现的这个问题，给slot组件加个key来重新渲染下组件就好了。

**Comment by youzhiwang** [comment]
> 请问你这个问题解决了吗，我也遇到了

```html
<template #default>
    <span>总共显示{{total}}条数据</span>
</template>
```

**Comment by lyon007** [comment]
你用的是最新版本Vue吧。如果是的话，那这就是Vue的问题，加个v-slot 即可解决。
![image](https://user-images.githubusercontent.com/21033119/56417239-dbf72f80-62c5-11e9-8fe3-d1242f3138c1.png)

**Comment by 6gunner** [comment]
any suggestions? not work by add v-slot;
![image](https://user-images.githubusercontent.com/7445659/57282483-b8165500-70df-11e9-80bd-0d27193f4fd3.png)
