### ISSUE TITLE
[Bug Report] Version 2.5.4 or above, the el-input display under the Chinese input method under Windows is incorrect

### ISSUE THREAD

**Issue by pearlwang1106** [ElemeFE/element#14779]
### Element UI version
2.5.4

### OS/Browsers version
windows

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1. windows 下，新建 vue 项目，引入 上述版本的 ele 组件库
2. 中文输入法下
3. 在输入框中随便输入，如：nihao
4. 按空格或者回车
5. 输入框中内容显示错误，错误情况：nihao你好， 你好你好
6. toB业务没有外网链接，请忽视重现链接

### What is Expected?
展示 你好

### What is actually happening?
nihao你好 或 你好你好

**Comment by xiaoshude** [comment]
这个问题应该 2.5.0及以上的版本都有，原因在2.5.0 input.vue 里移除了IME的检测r，直接使用v2.4.11 即可。

**Comment by xiaoshude** [comment]
https://github.com/ElemeFE/element/pull/14572   这个 pr修复了上面的问题，使用最新版本也行

**Comment by pearlwang1106** [comment]
升级最新版本测试已解决，谢谢
