### ISSUE TITLE
[Feature Request] select data is an attribute that requests to get a V-model binding value for an object. Single selection does not echo

### ISSUE THREAD

**Issue by pingmouren** [ElemeFE/element#14780]
### Existing Component
是

### Component Name
select

### Description
select 数据是请求得到 v-model绑定值为对象的一个属性 单选择未回显

**Comment by zhanjunhao** [comment]
key and value is map。。。

**Comment by pingmouren** [comment]
不是这个问题  就是当select的option循环的数据是后台请求过来的  然后v-model绑定的值是一个对象的一个属性 但是没有定义该属性 当我选择的时候 虽然可以调用到change方法 v-model绑定的对象的属性也会改变 但是select显示框中没有变化 就是没有渲染

**Comment by zhanjunhao** [comment]
你说的没有定义该属性 那就不符合开发规范了 你可以写个函数初始化定义这个值 然后用 set 或 Object.assign() 总之想个办法触发视图更新就好了 我这边用select组件 也是动态获取后台的数据 代码如下
![QQ截图20190321103142](https://user-images.githubusercontent.com/25976993/54730684-243b0900-4bc5-11e9-8b63-d59b067be1f1.png)
![QQ截图20190321103521](https://user-images.githubusercontent.com/25976993/54730688-2a30ea00-4bc5-11e9-8ae4-7e79249b5938.png)
![QQ截图20190321102926](https://user-images.githubusercontent.com/25976993/54730690-2d2bda80-4bc5-11e9-9df8-20f9d85f307e.png)

**Comment by pingmouren** [comment]
ok  我了解了  谢谢

**Comment by zhanjunhao** [comment]
和你这么说吧 我并不需要 额外的change事件 什么 set assgin 去触发视图 更新 这个select组件 本身就是响应式的 v-model本身就是双向绑定的 中间人是modelView view <=> model

**Comment by pingmouren** [comment]
![image](https://user-images.githubusercontent.com/44625220/54730879-39fcfe00-4bc6-11e9-953b-bbdd9cdcf719.png)
![image](https://user-images.githubusercontent.com/44625220/54730891-497c4700-4bc6-11e9-8424-eafc61b389fb.png)
但是我这样写就不能更新 
![image](https://user-images.githubusercontent.com/44625220/54730905-69ac0600-4bc6-11e9-9213-b5904cba044e.png)
这样就可以了

**Comment by pingmouren** [comment]
![image](https://user-images.githubusercontent.com/44625220/54730981-ad067480-4bc6-11e9-840c-0aaa3b33443a.png)

我这样写 定义表单绑定对象 inquiryOneData: { measurementSelect: '' } 可以更新
但是这样inquiryOneData: {}, 就不能更新了
当我触发视图更新的时候值又出来了
就是
![image](https://user-images.githubusercontent.com/44625220/54731011-f22aa680-4bc6-11e9-87ca-2ffd729dfbec.png)
这里没有值

**Comment by zhanjunhao** [comment]
我去大哥 你这里头的属性 肯定要初始化啊 我使用函数去初始化赋值到vue实例里面的data选项里面
![QQ截图20190321105240](https://user-images.githubusercontent.com/25976993/54731143-7c730a80-4bc7-11e9-9743-eb3d1190c885.png)

**Comment by pingmouren** [comment]
哦  谢谢您  主要如果是直接是定义在data中的数据  就不会出现这个现象 我不太明白为什么 麻烦您了 我知道我该怎么做了 给您添麻烦了

**Comment by zhanjunhao** [comment]
因为vue的机制 就是这样啊 如果你不想在data定义可以像我这样 用个函数去初始化在created hook 内 哈哈 不客气 都是开发者 互相帮助

**Comment by zhanjunhao** [comment]
你试想一个属性 未定义 你写在view => 组件这 而不是定义在data选项里头 那module里头根本没改属性 所以vue运行时去找这个属性 去堆内存里头找 假设该 内存X0X1地址下 没该属性 js引擎去解析不到 返回undefined 
![QQ截图20190321110359](https://user-images.githubusercontent.com/25976993/54731475-5cdce180-4bc9-11e9-8f37-798d86158cdc.png)

**Comment by zhanjunhao** [comment]
水平有限 只能给你这么讲 哈哈 简单粗暴。。。

**Comment by zhanjunhao** [comment]
你看下wiki https://cn.vuejs.org/v2/guide/reactivity.html#%E5%A3%B0%E6%98%8E%E5%93%8D%E5%BA%94%E5%BC%8F%E5%B1%9E%E6%80%A7 o(*￣︶￣*)o

**Comment by pingmouren** [comment]
哇  谢谢您  真是太感谢了

**Comment by zhanjunhao** [comment]
没事 不客气
