### ISSUE TITLE
[Bug Report] el-upload adds accept attributes and drag doesn't work

### ISSUE THREAD

**Issue by nicoleymj** [ElemeFE/element#14787]
### Element UI version
2.6.2

### OS/Browsers version
win7/chrome

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/wnga3qhy/](https://jsfiddle.net/wnga3qhy/)

### Steps to reproduce
<el-upload
  class="upload-demo"
  drag
  accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  action="https://jsonplaceholder.typicode.com/posts/"
  multiple>
  <i class="el-icon-upload"></i>
  <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
  <div class="el-upload__tip" slot="tip">只能上传excel文件，且不超过500kb</div>
</el-upload>

### What is Expected?
有accept属性时仍支持drag

### What is actually happening?
drag无效

**Comment by szfdiwang** [comment]
me too

**Comment by TimGrell** [comment]
I have the same problem
