### ISSUE TITLE
Bug Report Digital Type Verification Problem--When the check type of el-input is number, the decimal number cannot be input normally.

### ISSUE THREAD

**Issue by seafly521** [ElemeFE/element#14781]
### Element UI version
2.6.0

### OS/Browsers version
Win10/Chrome70.0.3538.110

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/jieng/6ucwr2v8/1/#&togetherjs=ccCrhJfFgV](https://jsfiddle.net/jieng/6ucwr2v8/1/#&togetherjs=ccCrhJfFgV)

### Steps to reproduce
1.在inpu内输入一个整数，例如123
2.输入小数点(.)，发现无法输入。

### What is Expected?
当el-input的校验类型为number时，可以正常输入小数

### What is actually happening?
当el-input的校验类型为number时，无法正常输入小数

**Comment by guohuihot** [comment]
对对对，最近更新出现的问题
