### ISSUE TITLE
[Bug Report] El-form bound by V-model cannot use form validation

### ISSUE THREAD

**Issue by wb121017405** [ElemeFE/element#14790]
### Element UI version
2.6.2

### OS/Browsers version
windows7/chrome72

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/iceice121/mrs0yhbu/2/](https://jsfiddle.net/iceice121/mrs0yhbu/2/)

### Steps to reproduce
把el-form中的:model 改为v-model

### What is Expected?
输入正确则验证成功

### What is actually happening?
无论怎么输入都是验证错误提示

**Comment by wacky6** [comment]
去学 vue 基础吧。 v-model = `:value + @input`。所以form收到的`:model`是undefined，所以一定会全部error。
