### ISSUE TITLE
el-menu-item-group、el-menu-item传参时报错

### ISSUE THREAD

**Issue by Leungkingman** [ElemeFE/element#1479]
![11](https://cloud.githubusercontent.com/assets/16955472/20747309/99791884-b724-11e6-9820-5f83c0d3280c.png)
在做管理后台的时候需要有3级关联的菜单，左侧菜单用了el-menu-item-group、el-menu-item组件，菜单数据结构如下图：
![66](https://cloud.githubusercontent.com/assets/16955472/20747379/ec9b82ae-b724-11e6-9e23-ee2b4da9da37.png)
在左侧菜单组件中代码如下
![33](https://cloud.githubusercontent.com/assets/16955472/20748191/2f8c3a74-b728-11e6-93c0-c2c8166d5530.png)

遍历menuData这个数组，在父组件以 this.$refs.leftMenu.menuData = this.childMenu 的方式传参（props的方式也试过）。结果报了这个错：

![44](https://cloud.githubusercontent.com/assets/16955472/20748277/7d59cb9a-b728-11e6-818a-b86b0408c0ad.png)

![55](https://cloud.githubusercontent.com/assets/16955472/20748224/4dcf2a50-b728-11e6-97d0-b4e9b3f32792.png)

但是在菜单子组件里面写div来遍历数据的话就没有报错（如图3注释部分）

**Comment by Leopoldthecoder** [comment]
请提供一个在线 demo
