### ISSUE TITLE
table 隐藏标识列id

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1480]
在table表格中，有时候需要将对应的选中的行的唯一id，传输给后台，请问如何在table中将id列进行隐藏，不显示在页面中，但是可以获取对应的id列的数据

**Comment by furybean** [comment]
本来就可以的获取到原始的完整数据，Table 只是对部分数据进行展示。

**Comment by yuanshengchao** [comment]
好的，谢谢
