### ISSUE TITLE
[Bug Report] el-dropdown has a horizontal scroll bar under win7 Chrome

### ISSUE THREAD

**Issue by xsbchen** [ElemeFE/element#14803]
### Element UI version
2.6.3

### OS/Browsers version
win7/chrome 71.0.3578.98

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/ywQwRL?&editable=true](https://codepen.io/anon/pen/ywQwRL?&editable=true)

### Steps to reproduce
hover 到 [更多菜单] 按钮，显示下拉菜单

### What is Expected?
显示的下拉菜单没有横向滚动条

### What is actually happening?
下拉菜单出现横向滚动条
![image](https://user-images.githubusercontent.com/1160705/54798353-56b33780-4c93-11e9-9f86-570f74e2bfb6.png)

**Comment by Kacxxia** [comment]
Seems like .el-dropdown-menu { overflow: auto } makes the little arrow participate in its bfc.
Could try either of following:
- add `:visible-arrow="false"` to `el-dropdown-menu`.
- add CSS .el-dropdown-menu { overflow: initial }. (which might cause children overflow)
- upgrade to v2.8.0 and above. #14907
