### ISSUE TITLE
[Feature Request] Select better user experience when filtering

### ISSUE THREAD

**Issue by ziyoung** [ElemeFE/element#14812]
### Existing Component
是

### Component Name
Select

### Description
Select 过滤模式下，点击，应该清楚 input 中的值

**Comment by winter-ice** [comment]
🤕 这个pr导致我hack方式的`setQuery`又不能用了。。之前是这样写的
```
  setQuery(query) {
      this.options = []
      this.$refs.select.focus()
      this.$refs.select.selectedLabel = query
      this.$refs.select.debouncedOnInputChange()
    },
```
官方不能提供个`setQuery`的 api 么?

**Comment by ibufu** [comment]
@winter-ice setQuery 是干嘛的

**Comment by winter-ice** [comment]
@ibufu 用来传值触发select搜索行为

**Comment by ibufu** [comment]
@winter-ice 能不能详细描述下？

**Comment by winter-ice** [comment]
因为搜索行为整套流程包括了弹出下拉框，搜索，无数据，有数据等等情况，脱离select在外部直接调用搜索方法无法触发这些东西，之前用hack方式大概实现了相关功能，今天更新完又不能用了

**Comment by winter-ice** [comment]
@ibufu 就是现在的select组件只能进行手动输入然后搜索，想要实现传一个值然后自动搜索的功能

**Comment by winter-ice** [comment]
想提PR的，但是select组件的源码我看了两天，感觉自己的能力可能无法胜任，目前select的源码感觉写的有一点点冗余，互相之间关联太多，而且我自己需要用到`setQuery`的时候仅仅是单选模式下，如果提交PR就还得考虑多选模式的情况，对源码的整套设计还是不是很理解，不敢贸然修改

**Comment by winter-ice** [comment]
iview select组件提供了相关API
![image](https://user-images.githubusercontent.com/24680921/56939683-4e74d480-6b3c-11e9-98d1-c2ba6717fb11.png)
