### ISSUE TITLE
[Bug Report] Cascader Cascader Selector Document Display Error

### ISSUE THREAD

**Issue by Nekojita1** [ElemeFE/element#14819]
### Element UI version
2.6.2

### OS/Browsers version
MacOS 10.14.3 / Chrome 72.0.3626.121

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
打开官方文档 - 级联选择器，使用第一个例子进行选择。（jsFiddle 是正常的）

### What is Expected?
正确显示。

### What is actually happening?
显示有重叠。

**Comment by iamkun** [comment]
fixed
