### ISSUE TITLE
[Bug Report] menu-item do not focus when use browsers back nav button

### ISSUE THREAD

**Issue by crackhopper** [ElemeFE/element#14820]
### Element UI version
2.6.3

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/0pegad78/](https://jsfiddle.net/0pegad78/)

### Steps to reproduce
1. click MainPage,  then menu item MainPage is highlighted;
2. click Test, then menu item Test is highlighted;
3. click browser's back button;  then 

    The text of MainPage is active, but the browser does not highlight its background; however, the background of menu item Test remains highlighted
   

### What is Expected?
the background of menu item Mainpage should be highlighted when we navigated back, but not the menu item Test

### What is actually happening?
This is because the menu item Test was still focused when we navigate back.  So shall we focus the menu item automatically when we navigate back?

**Comment by iamkun** [comment]
“the background of menu item Mainpage” is just css `.el-menu-item:hover, .el-menu-item:focus`

**Comment by crackhopper** [comment]
I know the css is `.el-menu-item:hover, .el-menu-item:focus` , but the problem is that **the menu item was not focused automatically when nav back**.  Changing css does not fix the problem.  We want to highlight another item which was not set focused, however this should be set by ElementUI.

although, it can be worked around.

**Comment by crackhopper** [comment]
Please check the problem patiently.

**Comment by iamkun** [comment]
Yes, however, the menu item was highlighted automatically when nav back and forward, just without the hover CSS style.

**Comment by crackhopper** [comment]
first click,
![step1](https://i.ibb.co/YjZrJHB/frame2.png)
second click,
![step2](https://i.ibb.co/NCPVRyL/frame3.png)
navigate back,
![step3](https://i.ibb.co/1KW1cjh/frame5.png)

as you can see, Mainpage is activated by set color blue, but not highlighted
![prob](https://i.ibb.co/hWqvGn3/problem.png)

Or this only happend in chrome on Ubuntu? I have not tested it on Windows.

**Comment by tanhaican** [comment]
I'm meeting the same issue
