### ISSUE TITLE
[Bug Report] el-table-column width issue

### ISSUE THREAD

**Issue by askart** [ElemeFE/element#14822]
### Element UI version
2.4.11

### OS/Browsers version
Google Chrome 73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/askart/to2nm4cv/3/](https://jsfiddle.net/askart/to2nm4cv/3/)

### Steps to reproduce
zoom in or zoom out browser to see that content inside el-table-column with fixed width overflows

### What is Expected?
content inside el-table-column with fixed width does not overflow

### What is actually happening?
content inside el-table-column with fixed width overflows

**Comment by iamkun** [comment]
Can you provide a screenshot of the expected result, please?

**Comment by askart** [comment]
![80-percent-zoom](https://user-images.githubusercontent.com/3787305/55774236-24d50a00-5ab6-11e9-8ce4-8554f5ee4bde.png)

**Comment by askart** [comment]
![100-percent-zoom](https://user-images.githubusercontent.com/3787305/55774307-5ea61080-5ab6-11e9-97f5-ce1c2ed9cfb0.png)
^ expected

**Comment by askart** [comment]
> Can you provide a screenshot of the expected result, please?

i've posted screenshots

**Comment by askart** [comment]
so, how to solve this issue?
