### ISSUE TITLE
[Feature Request] el-tree, props'child ren can't accept function?

### ISSUE THREAD

**Issue by uCloudCastle** [ElemeFE/element#14827]
### Existing Component
是

### Component Name
el-tree

### Description
2.1.0版本可以通过function定义el-tree的子级，最新的版本这样写会报错：
defaultProps: {
	children: this.childrenFunc,
	label: 'name'
},

childrenFunc(data, node) {
      if (data.children && data.children.length > 0) {
        return data.children
      } else if (data.permission && data.permission.length > 0) {
        return data.permission
      }
},
类似的需求在新版本如何处理呢？感谢！

**Comment by iamkun** [comment]
you can use `render-content`
