### ISSUE TITLE
[Bug Report] Type Incompatibility Error in the Typeescript Project

### ISSUE THREAD

**Issue by SilverLeaves** [ElemeFE/element#14823]
### Element UI version
2.6.3

### OS/Browsers version
firexfox最新版

### Vue version
2.6.10

### Reproduction Link
[https://void.github.void/void](https://void.github.void/void)

### Steps to reproduce
在ts vue项目中，在.ts文件中引入element，然后build

import Vue from "vue";
import Element from "element-ui";
import "element-ui/lib/theme-chalk/index.css";

Vue.use(Element);

### What is Expected?
build通过

## 报错

 error  in C:/Users/MI/Documents/GitHub/vue-ts-admin-tamplate/node_modules/element-ui/types/message-box.d.ts

ERROR in C:/Users/MI/Documents/GitHub/vue-ts-admin-tamplate/node_modules/element-ui/types/message-box.d.ts
171:5 Subsequent property declarations must have the same type.  Property '$confirm' must be of type '(modalOptios: ModalOptions) => ModalConfirm', but here has type 'ElMessageBoxShortcutMethod'.
    169 | 
    170 |     /** Show a confirm message box */
  > 171 |     $confirm: ElMessageBoxShortcutMethod
        |     ^
    172 | 
    173 |     /** Show a prompt message box */
    174 |     $prompt: ElMessageBoxShortcutMethod

ERROR in C:/Users/MI/Documents/GitHub/vue-ts-admin-tamplate/node_modules/element-ui/types/message.d.ts
73:5 Subsequent property declarations must have the same type.  Property '$message' must
be of type 'Message', but here has type 'ElMessage'.
    71 |   interface Vue {
    72 |   /** Used to show feedback after an activity. The difference with Notification
is that the latter is often used to show a system level passive notification. */
  > 73 |     $message: ElMessage
       |     ^
    74 |   }
    75 | }
    76 |

**Comment by SilverLeaves** [comment]
![图片](https://user-images.githubusercontent.com/31165554/54890400-2dd5b100-4ee4-11e9-8451-079411b21a7d.png)

**Comment by luckyCao** [comment]
建议检查下项目 ts 配置，或者提供一个能复现的链接

**Comment by kalicki** [comment]
> ![图片](https://user-images.githubusercontent.com/31165554/54890400-2dd5b100-4ee4-11e9-8451-079411b21a7d.png)

How you fixed?

**Comment by kalicki** [comment]
Up?

**Comment by dkddkk** [comment]
问题发生在新版的vue/cli上，同时安装element-ui，ant-design-vue，就会报这种错误，如果能解决，请告知。
ERROR in E:/work/js/rwsk/node_modules/ant-design-vue/types/modal.d.ts
297:5 Subsequent property declarations must have the same type.  Property '$confirm' must be of type 'ElMessageBoxShortcutMethod', but here has type '(modalOptios: ModalOptions) => ModalConfirm'.
    295 |     $error: (modalOptios: ModalOptions) => ModalConfirm;
    296 |     $warning: (modalOptios: ModalOptions) => ModalConfirm;
  > 297 |     $confirm: (modalOptios: ModalOptions) => ModalConfirm;

**Comment by mengera88** [comment]
同样出现了这个问题，有没有大佬解决一下

**Comment by yingyuk** [comment]
Duplicate of #https://github.com/youzan/vant/issues/3324
