### ISSUE TITLE
table 组件formatter属性

### ISSUE THREAD

**Issue by aiying323** [ElemeFE/element#14828]
在引入elementui 使用table组件中el-table-column的formatter属性时候（传入一个方法），发现hover行效果也能触发该方法。而在elementUI 源码的开发模式下却无法重现。只在数据加载的时候渲染了一次。两边的代码是一样的

**Comment by HyperClockUp** [comment]
我也遇到了同样的问题，我在表格中传入某列的值为用函数获取某个时间点距离现在的时间，结果发现mouseenter也能触发这个事件，这就导致了我该列的时间一直在改变
