### ISSUE TITLE
【input】 icon属性和slot=append不能同时显示

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#1483]
### ElementUI version
1.0.3

### OS/Browers version
win10/Chrome 53

### Vue version
2.1.3

### What is Expected?
当同时设置icon和slot=append时，icon显示在slot=append按钮的左侧
### What is actually happening?
slot=append的按钮会覆盖icon属性加入的图标

**Comment by QingWei-Li** [comment]
是的，写 append 就是自定义那部分的内容
