### ISSUE TITLE
[Feature Request] wanna a hook like before-upload in upload

### ISSUE THREAD

**Issue by simonAndSakura** [ElemeFE/element#14830]
### Existing Component
是

### Component Name
upload

### Description
we need to check file size and file type before user upload files, but before-upload prop works only when auto-upload prop is true. so we hope upload component has a new hook before user change file.like this:

in template:

```
<el-upload :before-change="onBeforeChange"><el-upload>
```

and in script:
```
onBeforeChange (file, fileList) {

    const isLt2M = file.size / 1024 / 1024 < 2;

    if (!isLt2M)  this.$message.error('file can not greater than 2MB!');

    return isLt2M;

}
```
when return false, element-ui should abort changing file.

**Comment by de1ck** [comment]
you can do :
```
onChange(file, fileList) {
        if (file.size > 1024 * 1024 * this.size) {
          this.$message.error(`file can not be greater than  ${this.size}MB!`)
          fileList.pop()
        }
      }
```

**Comment by simonAndSakura** [comment]
@de1ck yes, I thought so before, but this function is hard to reuse with unknown size limit. I must code this function every `.vue` file.

**Comment by simonAndSakura** [comment]
I realized that my expecting is hard to reuse too, damn

**Comment by simonAndSakura** [comment]
maybe upload needs a prop named `limitSize` or sth. else, LOL

**Comment by de1ck** [comment]
> @de1ck yes, I thought so before, but this function is hard to reuse with unknown size limit. :（

some tips might help you:
 
```
<el-upload ref="upload" :auto-upload="false"  :on-change="onChange" :limit-size="2"><el-upload>
```
```
onChange(file, fileList) {
       const size = this.$refs.upload.$attrs['limit-size']
        if (file.size > 1024 * 1024 * this.size) {
          this.$message.error(`file can not be greater than  ${this.size}MB!`)
          fileList.pop()
        }
      }
```

**Comment by luckyCao** [comment]
@de1ck thanks

**Comment by wudidehuangtiandi** [comment]
> you can do :
> 
> ```
> <el-upload :auto-upload="false"  :on-change="onChange"><el-upload>
> ```
> 
> ```
> onChange(file, fileList) {
>         if (file.size > 1024 * 1024 * this.size) {
>           this.$message.error(`file can not be greater than  ${this.size}MB!`)
>           fileList.pop()
>         }
>       }
> ```

niubbbbbbbbbbbbbbbbbbbbbbbbb
