### ISSUE TITLE
[Bug Report] In the keep-active caching page, the Dropdown drop-down menu and Tree tree controls do not respond to click events.

### ISSUE THREAD

**Issue by hlbj105** [ElemeFE/element#14837]
### Element UI version
2.6.3

### OS/Browsers version
deepin15.9.2/ 360Linux版10.0.1008.0

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
In keep-active caching pages, what happens when the drop-down menu of element-ui and the click event of Tree tree control do not respond?

在keep-active缓存页面中，element-ui的Dropdown下拉菜单和Tree 树形控件的点击事件有时候点击没反应是什么情况？

### What is Expected?
好麻烦

### What is actually happening?
能正常点击

**Comment by hlbj105** [comment]
![image](https://user-images.githubusercontent.com/16408650/54980669-4d9ecf00-4fe1-11e9-9370-ad7971e8c938.png)
![image](https://user-images.githubusercontent.com/16408650/54980683-57283700-4fe1-11e9-8485-da16c157bd60.png)
![image](https://user-images.githubusercontent.com/16408650/54980691-5e4f4500-4fe1-11e9-9141-e104b8ed0c69.png)
有时候正常，有时候报上面那个错

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
