### ISSUE TITLE
When [Bug Report] el-input changes the type type, the assignment is unsuccessful (Assignment is unsuccessful when changing the type)

### ISSUE THREAD

**Issue by fanzhch** [ElemeFE/element#14835]
### Element UI version
2.6.3

### OS/Browsers version
win10/Chrome72

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/oVVBgK?&editable=true](https://codepen.io/anon/pen/oVVBgK?&editable=true)

### Steps to reproduce
1.加载页面时，显示 input 控件（The input control is displayed when the page is loaded）
2. 输入值 helloword （input value ： helloword ）
2.点击 “改变类型” 按钮， 触发类型变化为 ‘ textarea’ , 组件的值为空，不是 helloword （Click the "Change Type" button and the trigger type changes to 
 ‘textarea ’，the value of the component is empty, not ‘helloword’）

### What is Expected?
改变类型时， 原来的值(helloword)应该带过来 (When changing the type, the original value (helloword) should be brought over.)

### What is actually happening?
改变组件类型 时，组件的值为空 (When changing the component type, the value of the component is empty)

**Comment by luckyCao** [comment]
Already fix this issue on version 2.7.2 ([#14889](https://github.com/ElemeFE/element/pull/14889/files)), upgrade element can solve your problem.
