### ISSUE TITLE
[Feature Request] Export components along with default export

### ISSUE THREAD

**Issue by dobromir-hristov** [ElemeFE/element#14839]
### Existing Component
No

### Component Name
All

### Description
It would be pretty useful if we could have components exported along with default exports in the end `lib` packages. The refactor needed is mostly to add the exports, and should not cause any breaking changes when used with a bundler (ESM or CJS). It would however cause issues with UMD in browser ENV, which I think is used now?

This could then be used for async loading said components. 

`date-picker` for example can be loaded only when your app needs it (as its kind of big).

**Comment by wacky6** [comment]
http://element.eleme.io/#/en-US/component/quickstart#on-demand

**Comment by dobromir-hristov** [comment]
Wonder if that will work for Async loading. Will give it a go and let you know.

**Comment by wacky6** [comment]
async import is provided by webpack. I guess you need to write some wrapper code.

**Comment by dobromir-hristov** [comment]
Alright, so the files inside the `lib` folder do export a component, so you technically can import them one by one, without even the `babel-plugin-component`. 

I just saw it actually is exporting the component, but just adds an `install` method to it, so it can be used with `Vue.use`. 

### So for anyone looking into this.

```js
import { Dialog } from 'element-ui'
// is the same as the one below when using the babel-plugin-component.
import Dialog from 'element-ui/lib/dialog'
```
This allows you to dynamically import as well:
```js
const Dialog = () => import('element-ui/lib/dialog')
Vue.component('ElDialog', Dialog)
```
