### ISSUE TITLE
[Feature Request] ztree default-checked-keys bind data, update data, ztree unchanged

### ISSUE THREAD

**Issue by elearic** [ElemeFE/element#14838]
### Existing Component
是

### Component Name
ztree

### Description
vue 组件里定了 selectArea属性绑定ztree的default-checked-keys ,自定义全选方法，每次调用全选方法时，都要先在全选方法内部把绑定的selectArea赋个空数组，再去往selectArea里push数据，ztree选中状态才能变化。
问题：为啥要每次selectArea 赋空值再push数据，才能生效

**Comment by iamkun** [comment]
what is a ztree component?

**Comment by elearic** [comment]
擦 这就关了
