### ISSUE TITLE
[Bug Report] el-popover can be closed only when its trigger button is clicked, otherwise not. 

### ISSUE THREAD

**Issue by Yohei1127** [ElemeFE/element#14836]
### Element UI version
2.4.11

### OS/Browsers version
iPad/12.1.1

### Vue version
2.6.10

### Reproduction Link
[https://github.com/Yohei1127/inspection-elPopover](https://github.com/Yohei1127/inspection-elPopover)

### Steps to reproduce
use iPad or iPad simulator via X-code.
Click a button to open popover and try to close it to touch its surroundings.

### What is Expected?
The popover can be closed even when its used on iPad and iPhone.

### What is actually happening?
After you click a button to open a popover and then try to close it by touching not button, normally it can be closed on web(browsers). However, when you try it on iPad, it cannot be closed otherwise you touched the button again.

**Comment by Yohei1127** [comment]
![Simulator_Screen_Shot_-_iPad_Pro__12_9-inch__-_2019-03-25_at_18_12_26](https://user-images.githubusercontent.com/32973388/54907821-cfcbbc80-4f29-11e9-94f2-809a66489e2f.png)

**Comment by iamkun** [comment]
Element is designed for desktop. It's not compatible with mobile devices. FYI: https://github.com/vuejs/awesome-vue#mobile-1
