### ISSUE TITLE
tab关闭时消除tab中的值会同时消除两个tab标签

### ISSUE THREAD

**Issue by lodamemory** [ElemeFE/element#1484]
### ElementUI version

1.0.3
### OS/Browers version

chrome
### Vue version

 2.0.0
### Reproduction Link

测试 代码 http://jsfiddle.net/ur9rsukg/2/
### What is Expected?
想要关闭标签时把标签中的值也消除
### What is actually happening?
我remove-click事件触发时去消除this.tabs中的值，但是如果不是从最后一个开始关闭，从中间关闭一个时会顺带关闭后面的一个。

**Comment by baiyaaaaa** [comment]
在用法上不建议使用数组对tab-pane进行比遍历，目前会导致一些奇怪的问题

**Comment by lodamemory** [comment]
@baiyaaaaa 那有什么解决方案么？

**Comment by baiyaaaaa** [comment]
@lodamemory 不要直接修改绑定的tab list

**Comment by newlife** [comment]
这个功能还有很又意义的，建议支持

**Comment by lodamemory** [comment]
@baiyaaaaa 这样我就没法控制tab的动态增加删除了啊？这样关了不好吧，可能不是bug，但是也可以做一个类似优化，我觉得一般固定tab肯定没动态tab用的多

**Comment by frontoldman** [comment]
repeat的时候，如果使用删除钩子删除数组的一项，会删除两项，目前看是无解的

所以我的解决办法是在updated函数里面查找元素给每个tab header里面插入一个删除icon的dom

再去绑定事件，删除数组一项

有点累啊
