### ISSUE TITLE
[Bug Report] el-tabs label slot 双向绑定data内容更改后不会自动渲染

### ISSUE THREAD

**Issue by dawnfrost** [ElemeFE/element#14842]
### Element UI version
2.6.3

### OS/Browsers version
Win10/ Chrome 73.0.3683.86

### Vue version
2.5.16

### Reproduction Link
[https://codepen.io/dawnfrost/pen/NJmjdK](https://codepen.io/dawnfrost/pen/NJmjdK)

### Steps to reproduce
1.点击change按钮
2.vue内部data中labelText变更
3.所属tab标签标题未刷新（此为bug所在）
4.点击标签后才可以刷新为新内容

### What is Expected?
点击change按钮，标签应该立即刷新为绑定的data值，这个行为在element 2.5之前的版本中是正常的

### What is actually happening?
点击change按钮，所属tab标签标题未刷新，点击标签后才可以刷新为新内容

**Comment by ziyoung** [comment]
Duplicate of #14712
