### ISSUE TITLE
[Bug Report] el-date-picker sets default-value only to the year and month, and the day cannot be highlighted

### ISSUE THREAD

**Issue by carmeloZhang** [ElemeFE/element#14841]
### Element UI version
2.6.3

### OS/Browsers version
Firefox 65.0.1 (64 bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/48ehxz9n/](https://jsfiddle.net/48ehxz9n/)

### Steps to reproduce
by using :default- value attribute ,the drop-down box can locate to 2019-02 ,and the expected date is not highlighted

### What is Expected?
the date from my example "2019-02-22" ,"22" should be highlighted 

### What is actually happening?
none of dates in Feb are highlighted

**Comment by wacky6** [comment]
It is intentional. It is confusing when today and default date are on the same month.

If you need to highlight default date, add your own css. The date has `default` class name.

**Comment by liwanchong04719** [comment]
> It is intentional. It is confusing when today and default date are on the same month.
> 
> If you need to highlight default date, add your own css. The date has `default` class name.

if  I set the default value , why not highligt the default, make the today normal
