### ISSUE TITLE
[Feature Request] 是否能提供禁用所有动画的选项

### ISSUE THREAD

**Issue by liwenda122** [ElemeFE/element#14845]
### Existing Component
是

### Component Name
所有

### Description
你们的elment-ui 非常棒，但是在IE系列浏览器上性能非常差（管理系统中最重要的 tree, table. tab 性能都很差），经查一个普通页面vue-component-xx-transition就有1000多个，能否提供一个参数 禁用所有动画？

**Comment by iamkun** [comment]
pr welcomed
