### ISSUE TITLE
[Bug Report] After reset form, input, select, date picker can't use

### ISSUE THREAD

**Issue by zhousheng1114** [ElemeFE/element#14851]
### Element UI version
2.6.3

### OS/Browsers version
windows10 ,chrome 73.0.3683.86（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/cqev3mua/3/](https://jsfiddle.net/cqev3mua/3/)

### Steps to reproduce
1.fill in form
2.click reset button
3.try fill in again. input , select,datepicker element can not input value

### What is Expected?
after reset form,input ,select,datepicker can work

### What is actually happening?
after reset form,input ,select,datepicker can't use

**Comment by iamkun** [comment]
return {
      staffInfo: {
      staff_current_worktime: null
      }
    }
