### ISSUE TITLE
[Bug Report] el-tree memory leak problem

### ISSUE THREAD

**Issue by superchangme** [ElemeFE/element#14858]
### Element UI version
2.6.3

### OS/Browsers version
win7 / ie11

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/superchangme/z9rswmtp](https://jsfiddle.net/superchangme/z9rswmtp)

### Steps to reproduce
1.使用ie11浏览器打开链接，同时打开任务管理观察iexplore.exe内存变化
2.点击页面中的添加树按钮一次，观察内存增长30MB左右
3.点击多次添加树按钮，观察内存持续增长
4.点击删除树按钮，观察内存并未减少
5.关闭页面，不退出ie浏览器内存依然没有减少。

### What is Expected?
希望el-tree销毁时，内存会减少

### What is actually happening?
怀疑ie下el-tree存在内存泄漏，请解决

**Comment by superchangme** [comment]
请回复，急！~~~

**Comment by cfangxx** [comment]
急呀  怎么办

**Comment by superchangme** [comment]
在elTree 代码里发现了多处this.$on监听事件方法，却没有看到相应的$off代码，怀疑和事件未解绑有关。

**Comment by superchangme** [comment]
this.$watch(`node.data.${childrenKey}`, () => {
        this.node.updateChildren();
      });

这段在tree-node实例里的watch也没有手动销毁

**Comment by superchangme** [comment]
尝试把watch和监听去掉后，也没有明显改善。
