### ISSUE TITLE
[Bug Report] Aside does not work if put under a header

### ISSUE THREAD

**Issue by whitecat** [ElemeFE/element#14852]
### Element UI version
2.6.3

### OS/Browsers version
OSX 10.14.3/ Firefox 64 / Chrome 73 

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/GeaJMw](https://codepen.io/anon/pen/GeaJMw)

### Steps to reproduce
Create Header and Aside how the documentation shows on `https://element.eleme.io/2.6/#/en-US/component/container`. 
<el-container>
  <el-header>Header</el-header>
  <el-container>
    <el-aside width="200px">Aside</el-aside>
    <el-main>Main</el-main>
  </el-container>
</el-container>

### What is Expected?
The header and aside are supposed to stay fixed on page while the main content scrolls

### What is actually happening?
The header and aside scroll with the main content

**Comment by iamkun** [comment]
Please double check the demo code.

**Comment by whitecat** [comment]
Please re-open the bug, as the demo code demonstrates exactly the problem that is happening. If you use chrome 73 and chrome 72 there are 2 very different behaviors. You can see that the header and the aside are not fixed any more using any operating system and (Firefox 64 or Chrome 73). The header and aside scroll with the rest of the page when they should be fixed. If you use Chrome 72 and before they are fixed.
