### ISSUE TITLE
[Bug Report] [Bug Report] el-popover effects the selection in the el-table

### ISSUE THREAD

**Issue by Nolin-Lin** [ElemeFE/element#14867]
### Element UI version
2.6.3

### OS/Browsers version
mac

### Vue version
2.5.17

### Reproduction Link
[https://codepen.io/anon/pen/GeaYXP?&editable=true](https://codepen.io/anon/pen/GeaYXP?&editable=true)

### Steps to reproduce
先选择表格的selection，然后去点击el-popover 会把已选择的 selection 取消掉

### What is Expected?
希望不会取消掉已选择的selection

### What is actually happening?
会取消已选择的selection

**Comment by ziyoung** [comment]
@Nolin-Lin 不是 bug。把传入的 data 作为 computed 值。https://codepen.io/ziyoung/pen/jRBNVa
