### ISSUE TITLE
When [Bug Report] el-select opens multiple and filter, the visual area of the search area is very small

### ISSUE THREAD

**Issue by ckang1229** [ElemeFE/element#14864]
### Element UI version
2.6.3

### OS/Browsers version
windows / chrome 73

### Vue version
2.6.10

### Reproduction Link
[https://jsbin.com/xeloriwaze/1/edit?html,output](https://jsbin.com/xeloriwaze/1/edit?html,output)

### Steps to reproduce
使用el-select 开启multiple 与 filterable 功能 并选中项。使选中项的长度微小于select框的长度。获取焦点进行搜索

### What is Expected?
当搜索内容过多时 搜索区域换行

### What is actually happening?
当搜索内容过多时 搜索区域不换行 导致搜索区域的可视区域过小 看不见搜索内容

**Comment by iamkun** [comment]
pr welcomed
