### ISSUE TITLE
[Bug Report] Carousel Street Lamp Playing Sequence

### ISSUE THREAD

**Issue by XiaoLongRenMengXin** [ElemeFE/element#14861]
### Element UI version
2.6.3

### OS/Browsers version
谷歌73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/pen/?&editable=true](https://codepen.io/pen/?&editable=true)

### Steps to reproduce
将循环次数修改为2时,循环播放效果出现左右滑动的效果,而不是顺序循环滑动

### What is Expected?
无论循环次数为多少都顺序播放,当点击左侧按钮向前翻页,点击右侧按钮向后翻页,自动播放顺序执行。

### What is actually happening?
当轮播图片只有两张时,当点击左侧按钮向前翻页,“再次点击,则会向后翻页”

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by syd192** [comment]
https://codepen.io/anon/pen/joboJv?&editable=true

问题
