### ISSUE TITLE
[Bug Report] type is the input of number. It can't input decimal point normally and follow the value of 0, such as 0.01, 0.003, etc.

### ISSUE THREAD

**Issue by w3cmark** [ElemeFE/element#14862]
### Element UI version
2.6.3

### OS/Browsers version
max ox / chrome 72.0.3626.121

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/MxdqwB?editors=1010#anon-login](https://codepen.io/anon/pen/MxdqwB?editors=1010#anon-login)

### Steps to reproduce
在类型为number的input输入框，输入浮点数时，当紧跟着小数点后的数字是0时

### What is Expected?
能够正常输入各种浮点数

### What is actually happening?
当输完小数点后，再输入第二个0时会之间把小数点删除。

**Comment by lllllllqw** [comment]
I meet this bug too...

**Comment by luckyCao** [comment]
不支持 v-model 修饰符，`v-model.number="ruleForm.name"` 改成 `v-model="ruleForm.name"`能解决你的问题。
http://element-cn.eleme.io/#/zh-CN/component/input#input-shu-ru-kuang

**Comment by w3cmark** [comment]
改成`v-model="ruleForm.name"`虽然可以正常输入，但值就不是number类型，而是string类型，当校验规则要求是number类型时，会校验不通过

**Comment by luckyCao** [comment]
我看一下这个问题，可以先用 [自定义校验规则](http://element.eleme.io/#/zh-CN/component/form#zi-ding-yi-xiao-yan-gui-ze) 解决你的问题。
