### ISSUE TITLE
[Bug Report] The horizontal scroll bar of the table cannot be dragged

### ISSUE THREAD

**Issue by Monine** [ElemeFE/element#14860]
### Element UI version
2.6.3

### OS/Browsers version
Windows / Chrome 72.0.3626.121

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/Monine/pen/aMrjdY](https://codepen.io/Monine/pen/aMrjdY)

### Steps to reproduce
使用官网 Table 表格 > 表尾合计行 例子
1. 给第一个 el-table-column 元素添加 fixed 属性
2. 修改 width 值为 1800
在浏览器宽度小于 1800px 的情况下，第一个 table 会产生横向滚动条，但鼠标无法拖动。

Use the official website Table table > table total line example
1. Add the fixed attribute to the first el-table-column element
2. Modify the width value to 1800
In the case where the browser width is less than 1800px, the first table will produce a horizontal scroll bar, but the mouse cannot be dragged.

### What is Expected?
表格的横向滚动条可以拖动

The horizontal scroll bar of the table can be dragged

### What is actually happening?
表格的横向滚动条无法拖动

The horizontal scroll bar of the table cannot be dragged

**Comment by Monine** [comment]
因为 `.el-table__fixed` 元素层级在 `.el-table__body-wrapper` 元素之上，定高覆盖，鼠标无法点击点击到 `.el-table__body-wrapper` 元素的横向滚动条。

**Comment by ziyoung** [comment]
类似的 issue #5415

**Comment by iamkun** [comment]
已知问题
