### ISSUE TITLE
[BUG]el-row's property align

### ISSUE THREAD

**Issue by dsonet** [ElemeFE/element#1487]
### ElementUI version
1.0.0-3

align 	flex 布局下的垂直排列方式	string	top/middle/bottom	top

既然是垂直对齐，应该用 valign 属性才对。

**Comment by Leopoldthecoder** [comment]
`align` 属性对应的 CSS 规则是 `align-items`，本身描述的就是内容沿副轴的对齐行为。

另外，API 会尽量保持稳定，不到万不得已不会修改。
