### ISSUE TITLE
The slot of [Feature Request] Popover adds popover's display state parameters for different content processing

### ISSUE THREAD

**Issue by Lynn-cc** [ElemeFE/element#14877]
### Existing Component
是

### Component Name
popover

### Description
使用场景是：
需要在table的表头支持日期范围筛选，由于没有现成的组件，所以利用了表格的header的slot，放入了popover组件，内部使用datePicker，而为了和table的其他的自带filter筛选展示效果一致，需要在展开popover的时候，th标题后的箭头在展开/收起filter时，分别是向上/向下的。这点在popover的slot里无法判断，求支持。

**Comment by iamkun** [comment]
pr welcomed
