### ISSUE TITLE
[Bug Report] [El Collapse]: When the el-table is embedded, expand the el-collapse, and the height will have a bounce.

### ISSUE THREAD

**Issue by fxxjdedd** [ElemeFE/element#14876]
### Element UI version
2.6.3

### OS/Browsers version
版本 72.0.3626.81（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/fxxjdedd-the-encoder/pen/LaKJpo](https://codepen.io/fxxjdedd-the-encoder/pen/LaKJpo)

### Steps to reproduce
点击el-collapse

### What is Expected?
高度不会发生弹跳

### What is actually happening?
高度会有一个弹跳

**Comment by iamkun** [comment]
没看出来 高度会有一个弹跳，请更新 demo

**Comment by fxxjdedd** [comment]
> 没看出来 高度会有一个弹跳，请更新 demo

好的，我增加了el-table的行数，现在可以观察一下视图区域右边的滚动条，切换collpase的展开关闭时，滚动条会出现一个“弹跳”

**Comment by SwordSealCity** [comment]
我的也会出现
