### ISSUE TITLE
[Bug Report] tag close button disappear

### ISSUE THREAD

**Issue by inkroom** [ElemeFE/element#14870]
### Element UI version
2.6.3

### OS/Browsers version
deepin15.9.2/firefox 66

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/inkroom/pen/QoRJXq](https://codepen.io/inkroom/pen/QoRJXq)

### Steps to reproduce
使用v-text或者v-html绑定tag内容

### What is Expected?
tag关闭按钮正常显示

### What is actually happening?
只有直接在标签内绑定内容方可正常显示关闭按钮；
使用v-text以及v-html无法显示关闭按钮

**Comment by iamkun** [comment]
Pass as slot will be fine.

**Comment by island205** [comment]
https://codepen.io/island205/pen/WWogqZ
