### ISSUE TITLE
[Bug Report] tree-table feedback on related issues

### ISSUE THREAD

**Issue by sds0917** [ElemeFE/element#14884]
### Element UI version
2.7.0

### OS/Browsers version
Windows10  Chrome/73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
[http://jsfiddle.net/sds0917/k4tvg9zw/15/embedded/](http://jsfiddle.net/sds0917/k4tvg9zw/15/embedded/)

### Steps to reproduce
1、树形表格设置default-expand-all属性，表格渲染完后行错乱；
![image](https://user-images.githubusercontent.com/7779851/55137097-093f3a80-516b-11e9-8249-9275bcfc8703.png)
2、用以下数据，排序后层级错乱
![image](https://user-images.githubusercontent.com/7779851/55137194-502d3000-516b-11e9-97c2-53f921bc19ca.png)
[{id:1,date:"2016-05-02",name:"王小虎",address:"上海市普陀区金沙江路 1518 弄"},{id:2,date:"2016-05-04",name:"王小虎",address:"上海市普陀区金沙江路 1517 弄",children:[{id:21,date:"2016-05-04",name:"王小虎 children",address:"上海市普陀区金沙江路 1517 弄"}]},{id:3,date:"2016-05-01",name:"王小虎",address:"上海市普陀区金沙江路 1519 弄",children:[{id:31,date:"2016-05-04",name:"王小虎 children",address:"上海市普陀区金沙江路 1517 弄",children:[{id:311,date:"2016-05-04",name:"王小虎 children",address:"上海市普陀区金沙江路 1517 弄"},{id:312,date:"2016-05-04",name:"王小虎 children",address:"上海市普陀区金沙江路 1517 弄"}]}]},{id:4,date:"2016-05-03",name:"王小虎",address:"上海市普陀区金沙江路 1516 弄"}]

### What is Expected?
1、展开正常
2、排序后层级正常

### What is actually happening?
1、展开不正常
2、排序后层级不正常

**Comment by DoubleRayWang** [comment]
同样遇到这个问题，default-expand-all应该是只针对type="expand" 的 Column 有效，建议增加设置tree-table的默认展开与否。

**Comment by ziyoung** [comment]
fixed #14935
