### ISSUE TITLE
[Bug Report] inline-style in element-ui conflicts with "unsafe-inline" CSP policy

### ISSUE THREAD

**Issue by vanhumbeecka** [ElemeFE/element#14887]
### Element UI version
2.7.0

### OS/Browsers version
Mac OS High Sierra - Google Chrome

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/9wyp53dm/](https://jsfiddle.net/9wyp53dm/)

### Steps to reproduce
- Start a project with Vue CLI 3. This will contain a 'yarn build' script which triggers 'vue-cli-script build'
- Add CSP headers in "index.html" of the form: "style-src: 'self' " ( so WITHOUT 'unsafe-inline') 
- Run "NODE_ENV=production yarn build" with element-ui included in sources
- The production build will include a "chuck-vendor.js" file, also containing the element-ui output
- In this "chunck-vendor.js" file, there will be a line containing inline-styles ("... setAttribute("style", ,s ";" $) ")
 (This can be found in the element-ui files 'input > src > calcTextareaHeight.js' line 70: "hiddenTextarea.setAttribute('style', `${contextStyle};${HIDDEN_STYLE}`);")
 (This line are UNSAFE_INLINE styles. CSP headers will not allow this.)
- Serve your "dist" folder with "serve -s dist" command
- Google Chrome signals CSP problems with unsafe-inline styles

### What is Expected?
To be able to build for production without unsafe-inline styles so I can use CSP directives.

### What is actually happening?
CSP directives are blocking the production build because there is unsafe-inline style from element-ui sources.

**Comment by wacky6** [comment]
We won't fix it.

Inline css is required for some functions. (e.g. textarea auto resize, dialog popup overlay, loading overlay).

**Comment by vanhumbeecka** [comment]
Ok, too bad. Gotta find another way then.

**Comment by franciscolourenco** [comment]
This plugin is not affected by this problem and works better than the Element UI version. Maybe it could be integrated. https://www.npmjs.com/package/vue-textarea-autosize
