### ISSUE TITLE
[Bug Report] select 组件 slot=“empty” 使用时会导致loading无法触发

### ISSUE THREAD

**Issue by winter-ice** [ElemeFE/element#14888]
### Element UI version
2.7.0

### OS/Browsers version
chrome 73

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/rgta8jvo/1/](https://jsfiddle.net/rgta8jvo/1/)

### Steps to reproduce
用slot定义empty时就会出现

### What is Expected?
定义了empty slot后依然可以正确触发loading状态

### What is actually happening?
无法触发loading状态

**Comment by elfman** [comment]
Select组件的`loading`是由prop定义的，所以你可以知道是否正在loading，在loading状态修改empty的内容就行啦
https://jsfiddle.net/HarlanLuo/e4qnwsuf/

**Comment by winter-ice** [comment]
@elfman 这样使用是否与最初这个pr提交时的用法有所违背？pr一开始应该是没想要涉及到loading状态的吧，文档中也没有提及，是暂时使用这种用法，还是以后也需要使用这种用法？

**Comment by elfman** [comment]
如果你觉得有必要修改的话，pr welcome
