### ISSUE TITLE
Can [Feature Request] Increase tree-select components

### ISSUE THREAD

**Issue by myadomin** [ElemeFE/element#14885]
### Existing Component
否

### Component Name
tree-select

### Description
类似antdesign的tree-select组件，能完成下拉列表选择树形数据等，参考https://ant.design/components/tree-select-cn/。

**Comment by myadomin** [comment]
see

**Comment by sds0917** [comment]
el-dropdown、el-input、el-tree可以组合成那个组件

**Comment by zhuangxiaohui** [comment]
已经有了，可能要重构层的代码，不然层的兼容性有问题
https://github.com/ElemeFE/element/tree/29e76cda035bb8a951e6792a33ba4ff5056515a0/packages/tree-select

**Comment by ayiaq1** [comment]
https://github.com/ayiaq1/el-tree-select

**Comment by sds0917** [comment]
https://vue.ant.design/components/tree-select

**Comment by tiny09** [comment]
> 已经有了，可能要重构层的代码，不然层的兼容性有问题
> https://github.com/ElemeFE/element/tree/29e76cda035bb8a951e6792a33ba4ff5056515a0/packages/tree-select

想请问下，该版本的tree-select好像不支持async search ？有开发计划吗

**Comment by tiny09** [comment]
> > 已经有了，可能要重构层的代码，不然层的兼容性有问题
> > https://github.com/ElemeFE/element/tree/29e76cda035bb8a951e6792a33ba4ff5056515a0/packages/tree-select
> 
> 想请问下，该版本的tree-select好像不支持async search ？有开发计划吗

而且现在版本是有bug的，搜索框里面删除tag，tree dropdown中的勾选状态没有同步

**Comment by tiny09** [comment]
@ziyoung 请问 treeselect 有合并时间点吗

**Comment by ziyoung** [comment]
> @ziyoung 请问 treeselect 有合并时间点吗

我们想对 tree 有一个重构。目前的 tree 已经不太好维护了。所以 tree-select 往后推了。

**Comment by jaihao** [comment]
的确需要的这个组件，使用的场景还是比较多的、期待近期可以实现、或者下个小版本中看到它现身
