### ISSUE TITLE
[Bug Report] Pagination Paging Component slot data is not updated

### ISSUE THREAD

**Issue by naifen00** [ElemeFE/element#14894]
### Element UI version
2.5.0

### OS/Browsers version
Mac 10.14.3 (18D109) / Chrome 73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/bZXMOo?&editable=true](https://codepen.io/anon/pen/bZXMOo?&editable=true)

### Steps to reproduce
需求自定义total 例如"共100条订单"

```
<el-pagination
  small
  layout="slot, total, prev, pager, next"
  :total="count">
  <span>共{{ count }}条订单</span>
</el-pagination>  
```
```
{
  data() {
    return {
      count: 50,
    };
  },
  methods: {
    changeCount() {
      this.count   ;
    },
  }
}
```

### What is Expected?
期望修改count时，插槽数据也会同步更新

### What is actually happening?
2.4.11 没毛病

https://codepen.io/anon/pen/RdXypN?&editable=true

2.5.0  插槽数据没有更新

https://codepen.io/anon/pen/bZXMOo?&editable=true

**Comment by zhuangxiaohui** [comment]
是vue 2.6.10 后的问题，我也被这个不够搞了半天，加个v-solt就好了
![image](https://user-images.githubusercontent.com/5791725/55207505-6099e500-5215-11e9-9623-c1cf63b5b6b5.png)

**Comment by naifen00** [comment]
> 是vue 2.6.10 后的问题，我也被这个不够搞了半天，加个v-solt就好了
> ![image](https://user-images.githubusercontent.com/5791725/55207505-6099e500-5215-11e9-9623-c1cf63b5b6b5.png)

果然可以了，之前遇到的table header插槽问题也一起解决了
