### ISSUE TITLE
[Bug Report] tree-table unable to delete child.

### ISSUE THREAD

**Issue by xlz26296** [ElemeFE/element#14896]
### Element UI version
2.7.0

### OS/Browsers version
谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/oVKyRe?&editable=true](https://codepen.io/anon/pen/oVKyRe?&editable=true)

### Steps to reproduce
删除树子节点后表格显示没变化

### What is Expected?
删除后正确显示数据

### What is actually happening?
删除后无法正确显示数据

**Comment by xlz26296** [comment]
希望树表格能支持数据同步，data中子节点增删后也能保持正确渲染

**Comment by ziyoung** [comment]
Duplicate of #14998
