### ISSUE TITLE
[Bug Report] @open="handleOpen" dosen't work, so as handleClose

### ISSUE THREAD

**Issue by LycheeHe** [ElemeFE/element#14897]
### Element UI version
2.7.0

### OS/Browsers version
chrome 73

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/hpdfzu7j/](https://jsfiddle.net/hpdfzu7j/)

### Steps to reproduce
write html -> write methods

### What is Expected?
before the submenu open, i think element-ui framework will trigger open event to execute handleOpen function. So as handleClose. Function handleSelect is executed when user select menu item.

### What is actually happening?
handleOpen and handleClose is not executed.

**Comment by iamkun** [comment]
please check the document and use `menu-trigger`
