### ISSUE TITLE
Router property of [Bug Report] navMenu component error prompt of tslink in TSX development

### ISSUE THREAD

**Issue by yif2012** [ElemeFE/element#14895]
### Element UI version
2.6.3

### OS/Browsers version
win7/谷歌

### Vue version
2.6.10

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
tsx语法render函数中 <Menu router></Menu>  使用此属性时tslint报错提示router属性必须是VueRouter类型或者是undefined类型，在声明文件中也无法覆盖这个描述 typescript版本3.3.4  tslint版本5.4

### What is Expected?
tsx语法render函数中 <Menu router></Menu>  使用此属性时tslint报错提示router属性必须是VueRouter类型或者是undefined类型，在声明文件中也无法覆盖这个描述 typescript版本3.3.4  tslint版本5.4

### What is actually happening?
tsx语法render函数中 <Menu router></Menu>  使用此属性时tslint报错提示router属性必须是VueRouter类型或者是undefined类型，在声明文件中也无法覆盖这个描述 typescript版本3.3.4  tslint版本5.4

**Comment by iamkun** [comment]
Looks fine : router: boolean
