### ISSUE TITLE
The [Bug Report] component Table dynamically changes hasChildren to false when using the Tree structure, and the on the table column does not refresh to disappear

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#14899]
### Element UI version
2.7.0

### OS/Browsers version
win10 , chrome 版本 73.0.3683.86（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
组件 Table ，在使用Tree结构时，动态改变hasChildren为false，table 列上的→不会刷新为消失

### What is Expected?
在动态改变hasChildren后，表格能即刻刷新状态

### What is actually happening?
在动态改变hasChildren后，表格未刷新状态

**Comment by yinjunonly** [comment]
https://jsfiddle.net 无法访问，则未提供重现地址

**Comment by iamkun** [comment]
先试试 https://codepen.io
