### ISSUE TITLE
Bug Report Table

### ISSUE THREAD

**Issue by irron** [ElemeFE/element#14904]
### Element UI version
2.7.0

### OS/Browsers version
windows7  chrome72s

### Vue version
2.5.21

### Reproduction Link
[https://codepen.io/anon/pen/bZXyYK?&editable=true](https://codepen.io/anon/pen/bZXyYK?&editable=true)

### Steps to reproduce
1.官网的树形表格Demo 加上default-expand-all='true'
2.出现表格显示错乱

### What is Expected?
1.使用default-expand-all="true"后可以初始展开全部行，显示不错乱
2.数据重新加载后可停留当前展开行

### What is actually happening?
1.使用展开所有行后显示错乱，
2.重新加载数据后行自行收起

**Comment by xiaogaofudao** [comment]
我也遇到了同样的问题，
i have meet this problem also

**Comment by xiaogaofudao** [comment]
https://codepen.io/anon/pen/VNZZva?&editable=true#anon-login

**Comment by ziyoung** [comment]
收到。
