### ISSUE TITLE
[Bug Report] After el-select adds the filterable attribute, click the icon can show drop-down menu ,but click the icon again can not  to close the drop-down menu.

### ISSUE THREAD

**Issue by hsingyin** [ElemeFE/element#14906]
### Element UI version
2.7.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/hsingyin/pen/moNYLq](https://codepen.io/hsingyin/pen/moNYLq)

### Steps to reproduce
After el-select adds the filterable attribute, click the icon can show drop-down menu and click the icon again 

### What is Expected?
After el-select adds the filterable attribute, click the icon can show drop-down menu , click the icon again can  close the drop-down menu.

### What is actually happening?
After el-select adds the filterable attribute, click the icon can show drop-down menu ,but click the icon again can not  to close the drop-down menu.

**Comment by hsingyin** [comment]
**Browsers version:**
Google Chrome
 73.0.3683.86

**Comment by iamkun** [comment]
this is a designed feature
