### ISSUE TITLE
[Bug Report] tree-table How to cancel tree render.

### ISSUE THREAD

**Issue by xlz26296** [ElemeFE/element#14905]
### Element UI version
2.7.0

### OS/Browsers version
Google Chrome

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/vPowem?&editable=true](https://codepen.io/anon/pen/vPowem?&editable=true)

### Steps to reproduce
非树结构的数据中带有children字段，直接报错了
Error: if there's nested data, rowKey is required.

### What is Expected?
非树结构的数据中带有children字段，希望能关闭树渲染方式

### What is actually happening?
非树结构的数据中带有children字段，直接报错了

**Comment by xiaoqi0912** [comment]
官方文档还没给出回复, 可以先给children 改个名字

**Comment by caoyang1203** [comment]
/**
          * element 2.7 中的 table 组件会自动探测数据中 children 字段，如果有会按照 tree 的方式去渲染
          * 这里我们不需要渲染成 tree 的方式，但是官方还未提供取消 tree 渲染的方式
          * 所以这里手动将数据中的 children 字段改为了 childrens，这样 element 就不会当做 tree 的方式去渲染了
        * 后期官方应该会提供取消按照默认字段 children 进行 tree 渲染的功能
      */
       data.forEach(item => {
         item.childrens = item.children
         delete item.children
       })

**Comment by xlz26296** [comment]
是可以换字段解决，但是原有的项目中很多表格带有 children 字段，如果要改动涉及比较多，只能先不升级了

**Comment by x-song** [comment]
请问下2.0以上哪个版本是没有这个问题的，试过2.5.4版本还是会存在这问题

**Comment by iamkun** [comment]
#14910

**Comment by chenbigui** [comment]
官网这个功能兼容是很好的；但是向下兼容也需要，至少需要一个开关，如果关闭，就不需要使用官网的树；这个还请尽快更新

**Comment by minteliuwm** [comment]
> 请问下2.0以上哪个版本是没有这个问题的，试过2.5.4版本还是会存在这问题

你看看是不是npm install的时候安装的版本不是2.5.4，我之前2.5.4没问题，然后今天把node_modules目录删了，重新install就出问题了，最后发现安装的是2.7.2版本的。。
