### ISSUE TITLE
[Bug Report] element-variables.scss custom dialog background color is invalid

### ISSUE THREAD

**Issue by 86driver** [ElemeFE/element#14918]
### Element UI version
2.7.0

### OS/Browsers version
win 10 chrome

### Vue version
2.6.10

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
按照官网提供的自定义主题方法
创建 element-variables.scss文件并引入
示例：
$--dialog-background-color: red    // 无效
查看源码在element-ui\packages\theme-chalk\src/dialog.scss发现
@include b(dialog)下面background的属性值是@color-white  改为$--dialog-background-color之后
就可以生效了  这是不是一个bug

### What is Expected?
期待可以直接通过设置$--dialog-background-color 改变对话框背景颜色

### What is actually happening?
在element-variables.scss文件中设置 $--dialog-background-color无效

**Comment by HACKHNATON01** [comment]
Bug elemsnt
