### ISSUE TITLE
[Feature Request] How to set the el-tree's row height?

### ISSUE THREAD

**Issue by water321** [ElemeFE/element#14917]
### Existing Component
是

### Component Name
el-tree

### Description
How to set the el-tree 's row height ? I want to add a button to the el-tree's every row, and the button's type="success", the button's size="mini", but the el-tree's  is to narrow to contain the button
thank u
<el-tree :data="dataTable" show-checkbox node-key="id" default-expand-all :expand-on-click-node="false"  ref="tree">
            <span class="custom-tree-node" slot-scope="{ node, data }">
                <span>{{ node.label }}</span>
                <el-button type="text" size="mini" @click="() => remove(node, data)">
                    Delete
                </el-button>
                <el-button type="warning" size="mini">B</el-button>
                <el-button type="success" size="mini">T</el-button>
            </span>
        </el-tree>

**Comment by iamkun** [comment]
override style `.el-tree-node__content`, please.
