### ISSUE TITLE
[Feature Request] Trigger collapse by clicking on arrow icon/button

### ISSUE THREAD

**Issue by japhfortin** [ElemeFE/element#14936]
### Existing Component
Yes

### Component Name
collapse

### Description
Hi,
I think it would be good if we can have some option to allow the user to only trigger the collapse by clicking the arrow icon/button instead of the entire header.

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.

**Comment by luck2011** [comment]
Yes, users need this feature when they have title slots on Collapse!
They donot want the title contents trigger the collapse event.
