### ISSUE TITLE
element - table问题

### ISSUE THREAD

**Issue by aisagacious** [ElemeFE/element#14930]
![image](https://user-images.githubusercontent.com/29672261/55370764-2fc7f180-552e-11e9-8d7a-913c3f7dbd2f.png)

**Comment by aisagacious** [comment]
请教一下 什么问题 之前都没出现过这个

**Comment by Zper** [comment]
我也很苦恼，el-table组件貌似监听data里面的数据了，如果里面有字段是children的话，默认你那个是嵌套数据，直接让你加上row-key改成树状图了

**Comment by xlz26296** [comment]
我也是一样的问题，data带有children字段就被报错，好像文档中也没有参数可以关闭树渲染，只能用回到2.6

**Comment by PengSama** [comment]
这个树形表格问题很大，只要data里有树形结构就会渲染成树形表格，没有参数能关闭这个树形渲染。
下面这个例子，不想使用树形表格，想自己构建层级。很苦恼。
https://codepen.io/SAMAPENG/pen/ROPWVp

**Comment by aisagacious** [comment]
之前写list有children没问题 
今天无意中看到报错了 "element-ui": "^2.4.5"  测试还问我代码怎么回事 
表格只需要一层结构 所以我把children筛选不要了

**Comment by iamkun** [comment]
#14910
