### ISSUE TITLE
自定义样式中loading动画中圆圈出现断断续续的情况

### ISSUE THREAD

**Issue by michaellyu** [ElemeFE/element#1493]
这是我使用的版本：
"element-ui": "1.0.3"
"element-theme": "0.2.0"
"element-theme-default": "1.0.3"
我仅仅只更改了主色，另外我使用的babel component方式手动引入组件的方式，而就在这样的方式中，我发现我生成的样式中loading（svg）动画出现了异常，动画中的圈会断断续续的，我不知道问题出在哪里。
![custom-theme-loading](https://cloud.githubusercontent.com/assets/13607563/20786158/570a2928-b7df-11e6-9a9c-9f28c1bdf75a.png)
![custom-theme-loading 2](https://cloud.githubusercontent.com/assets/13607563/20786210/96108fd6-b7df-11e6-9693-35f7245dd796.png)
![custom-theme-loading 3](https://cloud.githubusercontent.com/assets/13607563/20786249/c7c9c52e-b7df-11e6-93fd-af6b8ad39ddf.png)

**Comment by Leopoldthecoder** [comment]
不修改颜色会有这个问题吗？

**Comment by michaellyu** [comment]
@Leopoldthecoder 
我重新生成一次theme，这次没有更改主颜色值，不过loading样子还是断断续续的，下面是我在windows 10电脑上生成的命令。
```bash
$ "et -c ./src/styles/element-variables.css -o ./src/styles/element-theme -m"

\ build element theme[13:32:06] gulp-cssmin: Skipping unsupported css element-icons.eot
| build element theme[13:32:06] gulp-cssmin: Skipping unsupported css element-icons.svg
[13:32:06] gulp-cssmin: Skipping unsupported css element-icons.ttf
[13:32:06] gulp-cssmin: Skipping unsupported css element-icons.woff
√ build theme font
√ build element theme

Done in 8.79s.
```

**Comment by Leopoldthecoder** [comment]
试试看升级到 1.0.8 还有没有这个问题。

**Comment by michaellyu** [comment]
@Leopoldthecoder 
新的版本确实没有这个问题了，不过我不知道问题究竟出在哪个环节上，有同样问题的朋友可以参考下我升级后使用的版本：
element-ui: 1.0.8
element-theme: 0.2.0
element-theme-default: 1.0.8
