### ISSUE TITLE
Nodes that click el-tree when [Bug Report] Popover expands will not be hidden

### ISSUE THREAD

**Issue by WTFAYM** [ElemeFE/element#14934]
### Element UI version
2.7.0

### OS/Browsers version
win10/Chrome  版本 73.0.3683.86（64 位）

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/NmPVZw?&editable=true](https://codepen.io/anon/pen/NmPVZw?&editable=true)

### Steps to reproduce
1.给app添加display：flex；样式
2.点击展开popover。
3.点击tree的节点

### What is Expected?
展开的popover隐藏

### What is actually happening?
展开的popover没有隐藏

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by GQxQD** [comment]
https://codepen.io/gqxqd/pen/NmbBRJ
