### ISSUE TITLE
[Feature Request] What are the differences between Process-Status and finish-status?

### ISSUE THREAD

**Issue by JackZhouMine** [ElemeFE/element#14937]
### Existing Component
是

### Component Name
Step

### Description
Hi,what are diffence betweetn `process-status="success"` and `finish-status="success"`?

`process-status`  和 `finish-status` 有什么不同呢？
最后一步就在所有步骤里面，那么执行到最后一步，就是当成步骤，当前步骤成功，这时就是最后一步成功，没有执行到最后一步，它就是处于等待状态。
为何要单独设置最后一步的状态呢？能举一个使用场景吗？

**Comment by iamkun** [comment]
please our docs
