### ISSUE TITLE
The tree function of the [Bug Report] table component hides the child nodes of the tree when new nodes are added, as shown in the figure.

### ISSUE THREAD

**Issue by baimoer** [ElemeFE/element#14933]
### Element UI version
2.7.0

### OS/Browsers version
win10/chrome71

### Vue version
2.6.10

### Reproduction Link
[https://user-images.githubusercontent.com/18377791/55374933-d2876c80-553c-11e9-866c-fc4304908286.gif](https://user-images.githubusercontent.com/18377791/55374933-d2876c80-553c-11e9-866c-fc4304908286.gif)

### Steps to reproduce
创建一个table组件，使用树表格，使用element 2.7.0，在新增树节点时，已展开的树，会直接关闭掉。详情见下在的gif图
https://user-images.githubusercontent.com/18377791/55374933-d2876c80-553c-11e9-866c-fc4304908286.gif

### What is Expected?
期待的行为：新增节点后，原来展开的树，依然展开，不需要合起来

### What is actually happening?
实际行为：新增节点时，已展开的内容会关闭掉

**Comment by baimoer** [comment]
![a](https://user-images.githubusercontent.com/18377791/55375150-9f91a880-553d-11e9-8d84-2677e1fdba56.gif)

**Comment by hytcwangkai** [comment]
知道怎么默认展开树嘛，大佬

**Comment by yifire** [comment]
展开树的子节点，如何自定义操作的按钮？
Expand the child nodes of the tree, how to customize the button of the operation？

**Comment by ziyoung** [comment]
see #15170

**Comment by ziyoung** [comment]
2.9 会支持该功能。
