### ISSUE TITLE
When the disabled attribute value of the [Bug Report] el-select component changes, the size attribute fails

### ISSUE THREAD

**Issue by Sean-214** [ElemeFE/element#14949]
### Element UI version
2.6.1

### OS/Browsers version
win10

### Vue version
2.6.6

### Reproduction Link
[https://codepen.io/sean-214/pen/QPjJbg](https://codepen.io/sean-214/pen/QPjJbg)

### Steps to reproduce
el-select在el-form中时，el-form和el-form-item不设置size属性，el-select设置属性 :disabled="x" 和 size="small"，使x值变化 x=!x

但是在el-form或el-form-item设置size="small"后不会出现这个问题

### What is Expected?
el-select大小不变

### What is actually happening?
el-select变大，size="small"无效

**Comment by iamkun** [comment]
在 el-form 中的内部组件高度会从 el-form 中读取，所以请设置在 el-form 上
