### ISSUE TITLE
[Feature Request] data-time-picker  可以控制 “此刻” 功能 的回调吗？

### ISSUE THREAD

**Issue by Palenew** [ElemeFE/element#14953]
### Existing Component
是

### Component Name
Date-time-picker

### Description
“此刻”功能可以选择是不是使用，或者可以自定义回调的内容。
因为做到一个跨时区的需求，此刻的结果不符合需求定义，希望可以能有自定义的回调可以用。

**Comment by crazy-zuo** [comment]
看了源码，发现datatimepicker好像不能限制秒根本不提供这个函数

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
