### ISSUE TITLE
upload组件，添加before-upload钩子函数导致报错

### ISSUE THREAD

**Issue by CharkeyQK** [ElemeFE/element#1495]
### ElementUI version
1.0.3

### OS/Browers version
Chrome 54

### Vue version
2.0.3

### Steps to reproduce
使用 [Upload 上传](http://element.eleme.io/#/zh-CN/component/upload) 的第一个例子，添加钩子函数before-upload，在函数中不对 file 做任何操作，仅设置 loading 显示，这样会导致报错：“element-ui.common.js?a187:18623 Uncaught TypeError: Cannot set property 'percentage' of undefined(…)” 

### What is Expected?
element 未升级到 1.0.3 之前是 ok 的

**Comment by baiyaaaaa** [comment]
你的before-upload有返回值么

**Comment by CharkeyQK** [comment]
需要return file是吗？之前没返回没报错，以为不需要。

2016年12月1日 +0800 19:01 baiyaaaaa <notifications@github.com>，写道：

**Comment by CharkeyQK** [comment]
```
<el-upload :style="uploaderStyle" :action="fileUploadUrl" v-if="uploadVisible" v-loading="uploadingVisible" :before-upload="beforeFileUpload"
```

```
beforeFileUpload(file) {
    // 加上这句，报错
    this.uploadingVisible = true;
    // 只有这句，不抱错
    return file;
},
```

如我前面说的，没更新到2.0.3不会出现这个问题。

**Comment by baiyaaaaa** [comment]
麻烦给一个在线重现的例子吧

**Comment by CharkeyQK** [comment]
我刚才在其他工程重试了，没重现出来。然后我在有问题的地方upload配置了1.0.3 upload 的新 API（新增 Upload 默认已上传的文件列表 API）：:default-file-list="defaultFileList"；错误不会有了。

Chrome console 的错误位置是：element-ui.common.js?a187:18623
```
handleProgress: function handleProgress(ev, file) {
    var _file = this.getFile(file);
    _file.percentage = ev.percent || 0;
    },
```

因为问题没重现出来，我也只能提供这么多信息，感谢你。
