### ISSUE TITLE
[Bug Report] Order Bug

### ISSUE THREAD

**Issue by classic-o** [ElemeFE/element#14962]
### Element UI version
2.6.3

### OS/Browsers version
win 10 / Chrome 73

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/xLqezond/2/](https://jsfiddle.net/xLqezond/2/)

### Steps to reproduce
Open Reproduction Link

### What is Expected?
Column sorted in descending order provided :default-sort
C, b, A

### What is actually happening?
Return b, C, A

**Comment by iamkun** [comment]
['A', 'b', 'C'].sort()

**Comment by classic-o** [comment]
Yes, but I need alphabetical sorting. Is it possible to sorting during lowercase   and display the original in the table?
