### ISSUE TITLE
[Bug Report] tabs tab label content modification does not refresh

### ISSUE THREAD

**Issue by dawnfrost** [ElemeFE/element#14979]
### Element UI version
2.7.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/dawnfrost/pen/NJmjdK](https://codepen.io/dawnfrost/pen/NJmjdK)

### Steps to reproduce
点击change，标签页标题不刷新，checkbox状态不正常

### What is Expected?
标签页标题应该随data更新

### What is actually happening?
标签页标题不随data更新

**Comment by luckyCao** [comment]
我们没有侦测标签页的变化，暂时不考虑这样做

**Comment by island205** [comment]
@luckyCao 这算不算是 Tab 的 bug，感觉应该变化才对？
