### ISSUE TITLE
The binding value of the header slot of [Bug Report] Table cannot be changed dynamically

### ISSUE THREAD

**Issue by pz25925** [ElemeFE/element#14971]
### Element UI version
2.7.2

### OS/Browsers version
window / chrome

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/axvXzy?&editable=true](https://codepen.io/anon/pen/axvXzy?&editable=true)

### Steps to reproduce
1. 初始化表格.
2. 表格存在 header 插槽, 绑定一个默认值.
3. 动态更改 header 插槽绑定的值.

### What is Expected?
1. header 插槽绑定的值动态变更

### What is actually happening?
1. header 插槽绑定的值没有变更

**Comment by iamkun** [comment]
will fix this in the future
