### ISSUE TITLE
[Bug Report] JSX mode pagination slot is a button': load'unable to update (in JSX mode, pagination uses button as slot, loading changes, button does not change)

### ISSUE THREAD

**Issue by hn4930** [ElemeFE/element#14974]
### Element UI version
2.7.2

### OS/Browsers version
windows 10 / chrome 73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/1npvLmc0/7/](https://jsfiddle.net/1npvLmc0/7/)

### Steps to reproduce
JSX模式下，pagination使用button作为slot，loading改变，button没有变化

### What is Expected?
JSX模式下，pagination使用button作为slot，loading改变，button应该进入loading状态

### What is actually happening?
loading改变，button没有进入loading状态

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by lyon007** [comment]
look this  #14771
