### ISSUE TITLE
[Bug Report] el-table'row mouseenter event trigger all entire of table re-render, declining performance.

### ISSUE THREAD

**Issue by breath-co2** [ElemeFE/element#14981]
### Element UI version
2.7.2

### OS/Browsers version
mac  10.14.3/ chrome 74.0.3729.40

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/jonwang/8eawyn0j/](https://jsfiddle.net/jonwang/8eawyn0j/)

### Steps to reproduce
如演示所示，给 <el-table-column> 设置一个 :formatter 渲染事件，例如：
```js
<el-table-column
  prop="name"
  :formatter="formatter"
  label="姓名"
  width="180">
</el-table-column>
```
formatter 方法增加一个 console.log('...') ，然后用鼠标在表格上下移动，打开控制台会发现有大量的 log 输出。
把对应行 tr.el-table__row 的 mouseenter 事件强行移除则不会再触发所有行执行 formatter() ，说明是此事件导致。

另外：我给 el-table 加了一个 @cell-mouse-enter="mouseEnter" 事件并阻止冒泡，也不起作用，如下：
```js
mouseEnter(row, column, cell, event) {
  event.stopPropagation();
  event.preventDefault();
  return false;
}
```

-----------
please see https://jsfiddle.net/jonwang/8eawyn0j/

### What is Expected?
在鼠标移动时不要触发 formatter() 方法或者只触发当前行的事件

### What is actually happening?
触发了所有行的 formatter() 方法，导致 el-table 控件在渲染行数较多的表时性能骤降。

**Comment by ziyoung** [comment]
#14868
