### ISSUE TITLE
[Bug Report] Folding Panel Used in Combination with Table

### ISSUE THREAD

**Issue by HaoranranWang** [ElemeFE/element#14983]
### Element UI version
2.7.2

### OS/Browsers version
win-64/Chrome

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
折叠面板中包含table表格，表格中会合并单元格，当面板关闭再打开时，table中的合并单元格失效了。（暂不能提供链接地址）

### What is Expected?
应该折叠面板打开后table还是之前合并单元格的状态。

### What is actually happening?
打开面板，table表格不在是合并状态

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
