### ISSUE TITLE
Why do all declarations of [Bug Report] file types have to be filled in? This will prompt me to fill in dozens of attributes in the actual operation.

### ISSUE THREAD

**Issue by ivedk123** [ElemeFE/element#14980]
### Element UI version
2.7.2

### OS/Browsers version
无关

### Vue version
2.6.10

### Reproduction Link
[https://github.com/ElemeFE/element/tree/dev/types](https://github.com/ElemeFE/element/tree/dev/types)

### Steps to reproduce
随便翻一个里面都是用的【key: type】的形式，在TS中这表示是必填的，但是在实际引用使用上，实际需要填写的属性应该只有几个是必填的，其他的都应该是【key?: type】的形式存在不是吗？比如一个Button组件，它应该是不存在必填属性的，都应该是选填属性，这样也会让编辑器结合tslint等工具能够给我很好的提示，而不是满篇的红色波浪线

### What is Expected?
期待对组件的types进行重新梳理，哪些是用户必填的，哪些不是用户必填的，可以的话可以在最外部组件的声明中将JSDoc写好，可以很方便给用户提示的

### What is actually happening?
如描述

**Comment by luckyCao** [comment]
能具体列出来哪些组件有这些问题吗？

**Comment by ivedk123** [comment]
目前我看到的所有声明文件中都是这样的，例如：alert.d.ts | button.d.ts 等
