### ISSUE TITLE
[Bug Report] MessageBox custom content

### ISSUE THREAD

**Issue by sHeep1on** [ElemeFE/element#14988]
### Element UI version
2.7.2

### OS/Browsers version
谷歌73.0.3683.86    window

### Vue version
2.6.10

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
在点击确定之前 点击空格，然后手动点击取消或者点击确定，会出现很多提示框，有种关不了的感觉

### What is Expected?
希望不重复出现改弹框

### What is actually happening?
重复出现

**Comment by Nbsaw** [comment]
Reproduce url?

**Comment by sHeep1on** [comment]
> 重现网址？
确定之前，用space空白键，有时候空白键触发不了确定事件，点击取消就会出现会出MessageBox 弹框

$msgbox类型

http://element-cn.eleme.io/#/zh-CN/component/message-box#dan-du-yin-yong
