### ISSUE TITLE
[Feature Request] DatePicker - Week mode: Show Week Numbers on Calendar

### ISSUE THREAD

**Issue by sheadawson** [ElemeFE/element#14999]
### Element UI version
2.4.11

### OS/Browsers version
osx/chrome

### Vue version
2.5.17

### Existing Component
Yes

### Component Name
DatePicker

### Description
It would be great if the Date Picker component showed the week number on the calendar pop up, in a table column to the left of the first day of the week. Currently if a user is choosing a week number (1 - 52) and they know the number they want, they have to guess, choosing weeks based on date until they get the right number. More info and screen shots here https://stackoverflow.com/questions/55526311/how-to-show-week-numbers-on-element-ui-vuejs-datepicker-week-picker-mode

**Comment by ziyoung** [comment]
@wacky6 is it a feature?

**Comment by wacky6** [comment]
Wouldn't this cause trouble with `first-day-of-week` ? The definition for week number could differ from what's shown in the calendar.

**Comment by sheadawson** [comment]
@wacky6 week number would be defined/handled the same way it is for week picker ie. when you configure date picker like:

`<el-date-picker
      v-model="value3"
      type="week"
      format="Week WW"
      placeholder="Pick a week">
    </el-date-picker>`

Code example source: http://element-cn.eleme.io/#/en-US/component/date-picker#other-measurements
