### ISSUE TITLE
[Bug Report] Append/prepend el-select on el-input displays incorrectly

### ISSUE THREAD

**Issue by aaronfulkerson** [ElemeFE/element#14996]
### Element UI version
2.7.2

### OS/Browsers version
Windows 10/Chrome 73

### Vue version
2.6.10

### Reproduction Link
[https://element.eleme.io/#/en-US/component/input#mixed-input](https://element.eleme.io/#/en-US/component/input#mixed-input)

### Steps to reproduce
Append or prepend an el-select to an el-input.

### What is Expected?
I expect the component to display correctly.

### What is actually happening?
The component displays incorrectly. It looks the worst if you append. The only way to fix it is to manually set the width using CSS. This broke starting with version 2.6 of Element. It worked but looked differently in previous versions.

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/57278736-eee96c80-70d9-11e9-9752-83a7f34f1151.png)
I think it's fixed in 2.8

**Comment by luckyCao** [comment]
please provide a demo or a screen short.
