### ISSUE TITLE
Slider可否实现不显示tips

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/element#1499]
当有另外一个变量也受Slider当前值驱动的话(如下图)，这种情况tips是不必要的，
可否实现不显示tips，多谢！

![image](https://cloud.githubusercontent.com/assets/22360070/20789846/ed599ba0-b7f0-11e6-8777-0f7f0d88f158.png)

**Comment by Leopoldthecoder** [comment]
后面会提供给 tooltip 加自定义类名的功能，这样就可以通过 CSS 控制是否显示了。
