### ISSUE TITLE
[Bug Report] Don't remove child's DOM element in element-ui table with children

### ISSUE THREAD

**Issue by malkovDanik** [ElemeFE/element#14998]
### Element UI version
2.7.2

### OS/Browsers version
win10/chrome

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/Danik_codepenIO/pen/gyMQry](https://codepen.io/Danik_codepenIO/pen/gyMQry)

### Steps to reproduce
I have a table with a hierarchical structure.I remove child with array.splice() from table but dom do not re-rendering reactively.
It seems to be an issue with the way element-ui handles data internally. When modifying nested data directly, the table is not getting re-rendered. (But the data was indeed mutated correctly, as could be seen when logging this.tableData after the splice().)

Click button to delete.

### What is Expected?
Remove dom child from table.

### What is actually happening?
It seems to be an issue with the way element-ui handles data internally. When modifying nested data directly, the table is not getting re-rendered. (But the data was indeed mutated correctly, as could be seen when logging this.tableData after the splice().)

**Comment by cangjingge** [comment]
这个bug啥时候能解决呢。会做解决的吧

**Comment by bovenson** [comment]
Here is a hack solution, works fine for me.

1. define el-table element, and add `ref`

```
<el-table
 ref='treeTable'>
</el-table>
````

2. update lazyTreeNodeMap data
```
let table = this.$refs.treeTable;
table.store.states.lazyTreeNodeMap[rowId] = newData;
```

If there is doubt, print `table.store.states.lazyTreeNodeMap`  and take a look.
