### ISSUE TITLE
button 和 input 元素未设置 font-family

### ISSUE THREAD

**Issue by francisfeng** [ElemeFE/element#150]
### ElementUI version
2016/09/26 官网示例的版本

### OS/Browers version
Windows 10/Chrome 53

### Vue version
2.0.0-rc.4 

### What is actually happening?
Chrome 对如 input, textarea, keygen, select, button 这些元素会添加一个 user agent stylesheet，其中的设置了 `font-family` 为 Arial。

在 Windows 上，这些元素的汉字会 fallback 到中易宋体，与整套UI的风格格格不入。

### Suggestion
为这些元素添加 `font-family`，以覆盖浏览器的默认 style。

**Comment by baiyaaaaa** [comment]
一般的做法是给这些元素的相关属性都设为 `inherit` 以保持和全局的字体样式相同，这个应该是由开发者自己来设置的，作为组件库不会做这件事情。
```
button, input, select, textarea {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    color: inherit;
}
```

**Comment by francisfeng** [comment]
不认为这是开发者应该做的事情，事实上，许多对字体不敏感的开发者可能都不会注意到这个问题。

我查看了几个热门 CSS 框架，包括 Bootstrap, Pure.css, Bulma, 甚至最近由国人开发的 mobi.css，都为了这几个元素设置了 font-family.

**Comment by QingWei-Li** [comment]
只要自己引入个 css reset 例如 normalize.css 之类的就好了。我也觉得没必要提供，组件库不应该对全局产生影响
