### ISSUE TITLE
form嵌套导致的bug

### ISSUE THREAD

**Issue by chenweiqun** [ElemeFE/element#1500]
form里面再嵌套form的话会导致bug,场景是这样的,比如我封装了一个组件,是打开一个dialog,然后dialog里面拥有一个form,现在的结构如下
 - form
   - form-item
     - dialog
        - form
          - form-item

这时候,不管怎么设置内层的form-item的label-position都是无效的,而且错误提示也会出现重叠问题,虽然说一般场景是不应该出现form嵌套令一个form的,不过如果某个位于form-item的自定义组件是需要打开dialog,然后dialog里面有form表单的话,就会出现以上的bug了.

这里是错误重现的链接
[链接](http://jsfiddle.net/qq583451067/4qb8Lyss/2/)

似乎是下面form.css这行引起的,不知道为什么这两行是否为了做什么特殊判断
```
.el-form-item .el-form-item{margin-bottom:0}
.el-form-item .el-form-item .el-form-item__content{margin-left:0!important}
```

**Comment by baiyaaaaa** [comment]
样式写法确实有点问题，不过你的dialog完全没必要放在form里面，可以移到最外层
