### ISSUE TITLE
Failure of Placement of [Bug Report] el-autocomplete Component in Textarea Mode

### ISSUE THREAD

**Issue by yissyoo** [ElemeFE/element#15013]
### Element UI version
2.7.2

### OS/Browsers version
WIN10 / CHROME 69

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/xeRjaM](https://codepen.io/anon/pen/xeRjaM)

### Steps to reproduce
设置 el-autocomplete 组件的 placement="top-start" type="textarea"

### What is Expected?
建议框显示在指定的位置

### What is actually happening?
建议框总是显示在下方，而且没有箭头。

**原因分析**  
在 packages/autocomplete/src/autocomplete-suggestions.vue 组件的 mounted 事件中，是这样的：  
```js
this.referenceElm = this.$parent.$refs.input.$refs.input;
```
实际上应该这样  
```js
this.referenceElm = this.$parent.$refs.input.$refs.input || this.$parent.$refs.input.$refs.textarea;  
```

**Comment by luckyCao** [comment]
pr welcome

**Comment by bmdalex** [comment]
@luckyCao the #18478 PR is open for so long but still not merged; why did we close the issue?
