### ISSUE TITLE
Select需求

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#1501]
现在有以下需求
三个Select级联，如果把id做所索引，取其中的name就很麻烦，能否在 change中再返回一个当前点击option的索引index，这样可以很方便取到 列表中的值

如下图所示，为了取得name，现在没有索引，我还得 在list循环查找
如果我把index做为索引，这样取值没问题，但 连续更换上级筛选时，下级v-model都是0，这样会导致，选中的name不会变，而这时list的内容已经变了，这个算不算bug

![image](https://cloud.githubusercontent.com/assets/13325335/20791403/da7dc9aa-b7f7-11e6-9434-165c142856a4.png)

**Comment by Leopoldthecoder** [comment]
「选中的name不会变，而这时list的内容已经变了」请提供一个 demo。

**Comment by Leopoldthecoder** [comment]
超过七天没有反馈的 issue 会被关闭。如果能够重现，可以再打开。
