### ISSUE TITLE
[Feature Request] Table renderer-This may not be a bug or a new requirement, but rather an optimization related one

### ISSUE THREAD

**Issue by jnxey** [ElemeFE/element#15011]
### Existing Component
是

### Component Name
table

### Description
中文：

使用表格时，当鼠标移入移出表格的行时，表格的所有行都将重新渲染（当表格数据稍微复杂时将会严重影响性能），这一表现同样出现在选中当前行与复选框等功能，我不确定是否有对应的使用方法避免这种情况；

暂时为了解决这个问题，我将 【table-body.js】 内的 【store.states.hoverRow】 废弃，在 【tr】 标签添加一个属性标记，在鼠标移入移出时通过之前的属性标记找到相应的标签，直接改变行的背景颜色，配合 【debounce】 效果貌似不错，但我不确定是否会对原有功能造成影响或是有更好的方法；

同时我将 【table-columns.js】 文件的 【forced.selection.renderCell】 内的 【el-checkbox】 的 【value】 设置为 【column.reserveSelection ? store.isSelected(row) : undefined】，这样在一定程度上可以缓解客户端的压力，如果你没有使用 【reserveSelection】 的话，但同样我不确定是否会对原有功能有影响或是有更好的方法；

总之，我建议对表格组件的性能来一次比较显著的优化，或者是新创建一个高性能的表格组件？

英文：

When using the table, when the mouse moves in and out of the table rows, all the rows of the table will be re-rendered (when the table data is a little complex will seriously affect the performance), this performance also appears in the selection of the current row and check box and other functions, I am not sure whether there is a corresponding method to avoid this situation;

Temporarily in order to solve this problem, I abandoned the 【table-body.js 】【 store. States. HoverRow】, the 【tr】 tag to add a property, when the mouse moved or leave to find the corresponding tag by attributes, directly change the background color of the tag, cooperate 【debounce】effect seems to be good, but I'm not sure whether will affect the original function or there is a better way;

At the same time I for 【table-columns. Js file 】 【forced.selection.renderCell 】 in 【 el-checkbox 】 the "value" is set to 【column. reserveSelection? store.isSelected (row) : undefined】, so it can relieve the pressure on the client to some extent, if you are not using 【reserveSelection】, but again I am not sure if it will affect the original function or have a better method;

Overall, do I recommend a significant performance optimization of the table component or creating a new high performance table component?

**Comment by ziyoung** [comment]
fixed in #14868

**Comment by ziyoung** [comment]
相关 pr #15330
