### ISSUE TITLE
[Bug Report] Load MessageBox. confirm to report errors as needed

### ISSUE THREAD

**Issue by DemoHu** [ElemeFE/element#15016]
### Element UI version
2.7.2

### OS/Browsers version
chrome73 

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
根据文档http://element-cn.eleme.io/#/zh-CN/component/quickstart 按需载入
import { MessageBox } from 'element-ui';

Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;

this.$alert(123)  //正常
this.$confirm(message, options) //   Uncaught ReferenceError: _MessageBox is not defined

### What is Expected?
正常使用this.$confirm(message, options) 

### What is actually happening?
this.$confirm(message, options)  控制台报错   Uncaught ReferenceError: _MessageBox is not defined

**Comment by DemoHu** [comment]
按需引入MessageBox后，无法同时使用confirm message等方法

**Comment by luckyCao** [comment]
@DemoHu 试了下没有重现，请提供一个可复现的 demo

**Comment by PanJiaChen** [comment]
https://github.com/ElementUI/babel-plugin-component/issues/31
