### ISSUE TITLE
[Bug Report] Form forms open form validation, which is triggered by default when select opens multiple options

### ISSUE THREAD

**Issue by DemoHu** [ElemeFE/element#15024]
### Element UI version
2.7.2

### OS/Browsers version
chrome73 

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/PgbraV](https://codepen.io/anon/pen/PgbraV)

### Steps to reproduce
from表单中的select组件开启了multiple多选，并且启用了表单验证，一打开就触发了验证规则，出现了红字提示
而不开启multiple多选，就正常

### What is Expected?
和不开启multiple多选一样

### What is actually happening?
打开就触发了验证规则，出现了红字提示

**Comment by masongzhi** [comment]
将 ruleForm 的 `region: ''`改为`region: []`即可

**Comment by DemoHu** [comment]
@masongzhi   谢谢

**Comment by luckyCao** [comment]
@masongzhi 谢谢
