### ISSUE TITLE
[Bug Report] Table component calls `clearFilter` method won' t fire `filter-change` event

### ISSUE THREAD

**Issue by EdgarAllanzp** [ElemeFE/element#15021]
### Element UI version
2.7.2

### OS/Browsers version
Mac OS / Chrome

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/0y19x4oh/](https://jsfiddle.net/0y19x4oh/)

### Steps to reproduce
1. Set any filters.
2. Click the button to clear filters.

### What is Expected?
Call table component `clearFilter` method will fire `filter-change` event.

### What is actually happening?
Call table component `clearFilter` method will not fire `filter-change` event.

**Comment by EdgarAllanzp** [comment]
Relatived issue https://github.com/ElemeFE/element/issues/12391 .

**Comment by EdgarAllanzp** [comment]
https://github.com/ElemeFE/element/commit/d184e9c0b6fcb11f2ea7e43f8e46f7f33563cc67

I found the related commit. Is this a feature?

**Comment by wacky6** [comment]
Depending on how you interpret the word 'change', this can be a bug or feature.

---

My understanding is that 'change'-like events are triggered when:
* it is a result of **user** interaction
* user has **confirm the intention** to change some value.

The above definition is our interpretation of [W3C HTML change event's specification](https://html.spec.whatwg.org/multipage/indices.html#event-change). (Honored by form input components)

Calling `clearFilter` method leads to a **programatic** change. It is may not be a direct user action (e.g. in `setInterval`). So it will not trigger `filter-change` events.

**Comment by EdgarAllanzp** [comment]
I think it 's different from form components case. Besides, `clearSelection` method is also a programatic change,  but `selection-change` event will be triggered, which behave inconsistently.

**Comment by wacky6** [comment]
I think you can make a pr to fix `filter-change`.

Seems more reasonable to call filter-change handler automatically in `clearFilter` method.

**Comment by xiaogaofudao** [comment]
el-table 大数据批量更新会有卡顿。建议加一个 滚动监听事件，返回当前用户视野内的 row-key。用户可以根据这个只更新视野内的数据

**Comment by ziyoung** [comment]
> el-table 大数据批量更新会有卡顿。建议加一个 滚动监听事件，返回当前用户视野内的 row-key。用户可以根据这个只更新视野内的数据

提个 issue 或者在 #15170 中谈论。
