### ISSUE TITLE
[Bug Report] Rate support decimal

### ISSUE THREAD

**Issue by ziyoung** [ElemeFE/element#15033]
### Element UI version
2.7.2

### OS/Browsers version
Max

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/ziyoung/pen/gygwVr?&editable=true](https://codepen.io/ziyoung/pen/gygwVr?&editable=true)

### Steps to reproduce
分数是 `2.7`，显示的却是 `2.5`

### What is Expected?
显示正确的长度

### What is actually happening?
小数位被忽略

**Comment by haoranyu** [comment]
It seems to be a change in expected behavior. The unit test should be changed since expected behavior is different now.

https://github.com/ElemeFE/element/blob/dev/test/unit/specs/rate.spec.js#L184

It should be `40%` instead of `0%` then.
