### ISSUE TITLE
[Feature Request] Please add drawer component! Thanks~

### ISSUE THREAD

**Issue by gudufun** [ElemeFE/element#15030]
### Existing Component
否

### Component Name
Drawer

### Description
Please add drawer component！Thanks~

**Comment by thearabbit** [comment]
+1

**Comment by dargoner** [comment]
+1

**Comment by lx815** [comment]
Sometimes we have to give up elements because of the lack of a common component called drawer components.Therefore, we hope that the authorities can complete this drawer component as soon as possible

**Comment by dargoner** [comment]
+1

**Comment by connecteev** [comment]
+1 I also filed a ticket for this #16343

**Comment by wangqi908** [comment]
+1

**Comment by shecenon** [comment]
+1

**Comment by iamkun** [comment]
done
