### ISSUE TITLE
When the [Bug Report] table component has a tree structure, the sorting does not sort the sub-level, so the corresponding sub-level sorting function should be added.

### ISSUE THREAD

**Issue by leouncle** [ElemeFE/element#15037]
### Element UI version
2.7.2

### OS/Browsers version
win7 / chrome

### Vue version
2.6.10

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
table组件有树形结构时排序没有对子层级排序

### What is Expected?
应该添加对子层级排序的功能

### What is actually happening?
table组件有树形结构时排序没有对子层级排序

**Comment by ziyoung** [comment]
不支持该功能。
