### ISSUE TITLE
[Bug Report] [Feature Request] Can image upload component, request merge

### ISSUE THREAD

**Issue by KeyX-y** [ElemeFE/element#15036]
### Element UI version
2.7.2

### OS/Browsers version
11

### Vue version
2.6.10

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
点击图片上传，多张文件上传

### What is Expected?
多张图片上传时，是否能合并请求，一次上传，减少不必要的请求

### What is actually happening?
多张图片上传，多次请求

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
