### ISSUE TITLE
Questions on New Function Tree Table of el-table

### ISSUE THREAD

**Issue by seadog16** [ElemeFE/element#15034]
### Element UI version
2.7.0

### OS/Browsers version
Max

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/bJgvLz](https://codepen.io/anon/pen/bJgvLz)

### Steps to reproduce
通过修改el-table的height，出现滚动条时，展开树结构是正常的；当height接近数据高度，没有滚动条的时候，展开树结构时并没有自动出现滚动条，因此造成布局缺陷。

### What is Expected?
当height接近数据高度，展开树结构时自动出现滚动条
方案1：展开树时重新计算布局
方案2（推荐）：Table Attributes加多个滚动条开关auto-scroll。默认为true：根据高度自动计算滚动条；为false：永久出现滚动条。

### What is actually happening?
当height接近数据高度，展开树结构时没有出现滚动条

**Comment by cuicc1991** [comment]
我也遇到了这个问题

**Comment by YuThree** [comment]
me too  I found table function name  _updateScrollY_ in code can set height normal

**Comment by ziyoung** [comment]
@seadog16 无法重现。

**Comment by seadog16** [comment]
@ziyoung  怎么无法重现呢？点击展开图标，右边表格的数据被隐藏在表格外面了
