### ISSUE TITLE
[Bug Report] Table Number Sorting Error

### ISSUE THREAD

**Issue by djinzhong** [ElemeFE/element#15046]
### Element UI version
2.7.2

### OS/Browsers version
win10/chrome70.0.3538.110

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/dengjz/pen/LvWYPN](https://codepen.io/dengjz/pen/LvWYPN)

### Steps to reproduce
1.拷贝官方文档代码
2.改动数据分别添加个位数和两位数字符串
3.点击数值3排序（顺序与逆序）

### What is Expected?
期待按数字大小排序，能添加一个自定义排序功能
升序 1 5 6 11 12 22
降序 22 12 11 6 5 1

### What is actually happening?
升序 1 11 12 22 5 6
降序 6 5 22 12 11 1

**Comment by masongzhi** [comment]
不是bug，sortable表现与Array.sort一致，需要加上sort-method属性定义先后顺序
![image](https://user-images.githubusercontent.com/19945145/55863414-0b62b980-5bad-11e9-8648-d8c1cd3e6cb9.png)

**Comment by djinzhong** [comment]
恩恩，谢谢解答！

**Comment by djinzhong** [comment]
能不能给 sort-method 方法添加一个自定义参数作为 key 值 （Function (a, b, key ) ）a, b 只是整个行数据，但是我需要的是针对行中具体变量进行排序，例如：
const sortFenceNumber = function (a, b, key) {
  return a[key] - b[key]
}

**Comment by ziyoung** [comment]
@masongzhi 谢谢大佬的回答。对维护开源有兴趣吗？欢迎联系我。

**Comment by masongzhi** [comment]
@ziyoung 你好，如何联系你
