### ISSUE TITLE
[Bug Report] Dialog Dialog dialog box click on the mask layer will not disappear

### ISSUE THREAD

**Issue by touH** [ElemeFE/element#15043]
### Element UI version
2.7.2

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/touh/pen/eovOmr](https://codepen.io/touh/pen/eovOmr)

### Steps to reproduce
修改dialog弹框的定位，将定位设置到边上，比如：

.el-dialog__wrapper{
  left: 80%
}

### What is Expected?
修复，点击遮罩层，弹框也是被关闭的

### What is actually happening?
修复，点击遮罩层，弹框也是被关闭的

**Comment by luckyCao** [comment]
```
.el-dialog__wrapper{
padding-left: 80%
}
```
可以通过这样的设置达到你想要的效果
