### ISSUE TITLE
使用英文时datepicker面板显示有问题

### ISSUE THREAD

**Issue by plusice** [ElemeFE/element#1504]
### ElementUI version 1.0.3

![image](https://cloud.githubusercontent.com/assets/3931895/20794101/53f71252-b805-11e6-8241-4f970d9a5aa6.png)

看了下代码是将语言包的el.datepicker.year设置成空字符串，但是vue-i18n解析不了。el.datepicker.year填个空格就没问题。

**Comment by QingWei-Li** [comment]
最新版的 vue-i18n 已经修复的这个问题
