### ISSUE TITLE
[Feature Request] The elements of the result set on the right side of el-transfer are saved as objects rather than just an ID

### ISSUE THREAD

**Issue by dielangsea** [ElemeFE/element#15042]
### Existing Component
是

### Component Name
el-transfer 

### Description
在移动元素的时候，有时候需要根据条件过滤一些元素，而结果集中只有一个id，并不能直接拿数据去判断是否能移动，建议结果集存放整个元素对象。

**Comment by luckyCao** [comment]
pr welcome
