### ISSUE TITLE
[Feature Request] I want the element in the form of inline to be vertically centered

### ISSUE THREAD

**Issue by FirstJavaMaster** [ElemeFE/element#15045]
### Existing Component
是

### Component Name
form

### Description
In the inline form, in the vertical direction, the elements are top aligned, When this form and other (vertically centered) elements are placed on one line, it will be ugly. I have to modify other elements for top alignment to stay beautiful. 
I want to know why the line form is not centered by default, and is there any simple way to modify it?

**Comment by FirstJavaMaster** [comment]
I have to use the following method to manually modify css:

```
<style scoped>
  .top-bar-item >>> .el-form-item {
    margin-bottom: 0;
  }
</style>
```

`top-bar-item` is the element class name I used to wrap this subform

**Comment by luckyCao** [comment]
pr welcome
