### ISSUE TITLE
How does [Feature Request] el-upload just call the camera instead of popping up the camera, album, file options for me to choose

### ISSUE THREAD

**Issue by LJYes** [ElemeFE/element#15048]
### Existing Component
是

### Component Name
el-upload

### Description
业务需求：拍照取证功能，只能使用相机功能。

疑问：el-upload如何只调用相机，而不是弹出相机、相册、文件选项让我选择。

**Comment by LJYes** [comment]
类似于 `<input type="file" accept="image/*" capture="camera">`

**Comment by luckyCao** [comment]
可以 mounted 的时候加一下 capture 属性
