### ISSUE TITLE
[Bug Report] el-table tree structure using default-expand-all has bugs

### ISSUE THREAD

**Issue by seadog16** [ElemeFE/element#15057]
### Element UI version
2.7.0

### OS/Browsers version
Max

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/VNpWVr](https://codepen.io/anon/pen/VNpWVr)

### Steps to reproduce
el-table标签使default-expand-all为true

### What is Expected?
渲染树表正常

### What is actually happening?
渲染树表有bug

**Comment by lucasleelz** [comment]
是的，请问`table tree`可以支持全部展开吗？

**Comment by roc2539** [comment]
目前好像是不可以的。

**Comment by lucasleelz** [comment]
坑~

**Comment by ziyoung** [comment]
仔细看一下文档。
![image](https://user-images.githubusercontent.com/12947422/56333321-56d92100-61c6-11e9-8a4f-6094fd6b3ef6.png)
