### ISSUE TITLE
[Bug Report]  Prompt information style problem when clicking slider bar

### ISSUE THREAD

**Issue by moshang-xc** [ElemeFE/element#15063]
### Element UI version
2.7.2

### OS/Browsers version
windows7 / Chrome 72.0.3626.81 (64)

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/moshang/pen/LoEgKj](https://codepen.io/moshang/pen/LoEgKj)

### Steps to reproduce
1. Click on the slider bar
2. View prompts
3. Triangle ectopic

### What is Expected?
The triangle is in the middle of the message

### What is actually happening?
The triangle is in the right of the message
![image](https://user-images.githubusercontent.com/29499430/55929742-a2348200-5c50-11e9-9399-990bf51d2e23.png)

**Comment by luckyCao** [comment]
demo 有问题，请提供一个可复现的 demo

**Comment by moshang-xc** [comment]
https://codepen.io/moshang/pen/LoEgKj
