### ISSUE TITLE
When the tree data of [Feature Request] able component is lazily loaded, it is impossible to distinguish how the child nodes should be mounted separately if there are multiple parent nodes with haschildren attribute true.

### ISSUE THREAD

**Issue by cuicc1991** [ElemeFE/element#15060]
### Existing Component
是

### Component Name
el-table

### Description
When the tree data of able component is lazy to load, it is impossible to distinguish how the child nodes should be mounted separately if there are multiple parent nodes with haschildren attribute of true.

**Comment by cuicc1991** [comment]
尝试着把官方例子里多个上级节点的haschildren属性改为true,懒加载的数据会同时挂载在多个上级级节点，不能做到按层级结构挂载

**Comment by ziyoung** [comment]
load 函数的三个参数 row, treeNode, resolve。使用 treeNode。
