### ISSUE TITLE
[Bug Report] el-input 中用select 启用多选属性，select下拉框报错 Error in render: "TypeError: Cannot read property 'indexOf' of null"

### ISSUE THREAD

**Issue by zhengliwu1989** [ElemeFE/element#15061]
### Element UI version
2.6.3

### OS/Browsers version
谷歌73

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/pen/#/map-mainaaa未保存](https://codepen.io/pen/#/map-mainaaa未保存)

### Steps to reproduce
<div style="margin-top: 15px;">
  <el-input placeholder="请输入内容" v-model="input5" class="input-with-select">
    <el-select v-model="select" slot="prepend" multiple placeholder="请选择">
      <el-option label="餐厅名" value="1"></el-option>
      <el-option label="订单号" value="2"></el-option>
      <el-option label="用户电话" value="3"></el-option>
    </el-select>
    <el-button slot="append" icon="el-icon-search"></el-button>
  </el-input>
</div>

[Vue warn]: Error in render: "TypeError: Cannot read property 'indexOf' of null"

found in

---> <ElOption> at packages/select/src/option.vue
       <ElScrollbar>
         <ElSelectDropdown> at packages/select/src/select-dropdown.vue
           <ElSelect> at packages/select/src/select.vue
             <ElInput> at packages/input/src/input.vue
               <ElCard> at packages/card/src/main.vue
                 <MapMain> at src/views/modules/map-command/map-main.vue
                   <App> at src/App.vue
                     <Root>

### What is Expected?
修复

### What is actually happening?
未修复

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
