### ISSUE TITLE
[Bug Report] table component bug

### ISSUE THREAD

**Issue by 609067409** [ElemeFE/element#15066]
### Element UI version
2.7.2

### OS/Browsers version
win10/谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/609067409/pen/vMmNbW](https://codepen.io/609067409/pen/vMmNbW)

### Steps to reproduce
el-tabel添加show-summary属性， el-table-column添加fixed属性

### What is Expected?
fixed的列不要挡住表格的横向滚动条

### What is actually happening?
fixed的列会挡住表格的横向滚动条

**Comment by seasmiles** [comment]
遇到了类似的问题。表格为空的情况下，固定列覆盖了滚动条不能拖动。
另外合计这个之前就有人提过：https://github.com/ElemeFE/element/issues/5415
两年了也没人处理。

**Comment by 609067409** [comment]
> 遇到了类似的问题。表格为空的情况下，固定列覆盖了滚动条不能拖动。
> 另外合计这个之前就有人提过：#5415
> 两年了也没人处理。

老哥怎么解决啊
