### ISSUE TITLE
[Bug Report] [Bug Report] ElSelect - update  disabled attribute in  select component which is hidden at first will change height.

### ISSUE THREAD

**Issue by ihgSherryLee** [ElemeFE/element#15064]
### Element UI version
2.4.11

### OS/Browsers version
Mac chrome 73.0.3683.86

### Vue version
2.5.21

### Reproduction Link
[https://codepen.io/ihgsherrylee/pen/EJmjzJ](https://codepen.io/ihgsherrylee/pen/EJmjzJ)

### Steps to reproduce
1.use v-show='false' <div> to wrap the <el-select> tag with attribute disabled=true, use css to set input height. (input[type=text] {height: 28px}).

2.change v-show to true. 

3.then change disabled=false.

### What is Expected?
1.the <el-select> tag do not show in the page. 

2.then the disabled <el-select> tag show in the page.

3.then the <el-select> is editable.And won't change its height.

### What is actually happening?
but in the third step, the height change to 40px, using inline style.

Is it a bug or not?

**Comment by luckyCao** [comment]
@ihgSherryLee you can set size="mini" instead of use css to change input height to 28px
