### ISSUE TITLE
[Bug Report] Tree Data and Lazy Loading

### ISSUE THREAD

**Issue by caim18340** [ElemeFE/element#15062]
### Element UI version
2.7.2

### OS/Browsers version
谷歌最新版

### Vue version
2.6.10

### Reproduction Link
[https://github.com/ElemeFE/element/issues](https://github.com/ElemeFE/element/issues)

### Steps to reproduce
<el-table
 :data="getData"
 row-key="key"
 border
 lazy
 :load="load"
@row-click="clickRowHandler"
:row-style="selectedHightlight"
:cell-style="tableRowClassName"
<el-table-column
 v-for="(item,index) in clumns"
:prop="item.field"
:label="item.title"
:width="item.width">
</el-table-column>
</el-table>

<script>
  methods:{
       clickRowHandler(row,column,event){
             向后台发请求获取当前点击行数据，返回的数据里多了当前行的children，而且也有hasChildren为true；
       }，
       load(row,treeNode,resolve){
                 if(resolve){
                     rwsolve([])
               }
       }
    }
</script>

### What is Expected?
当行点击事件时就触发load函数，打开当前行的子集，希望暴露一下Load方法或者resolve方法
而且点击最里面的子集时，不会关闭展开项，只有当点击 > 这个图片时才关闭当前行的子集

### What is actually happening?
只有点击  >  这个图标才触发load函数，才展开子集内容，但当点击子集内容选中时，会自动关闭所有展开项，我看他是触发了getTableTreeData函数把所有的display属性设置为了false才使所有展开项关闭了，即css的display属性变为了none，这是为什么？而且default-expand-all这个属性貌似不支持树形数据，支持的是展开行表格

**Comment by caim18340** [comment]
![vue](https://user-images.githubusercontent.com/44394133/55935738-f21e4380-5c66-11e9-8e07-64868bba5b75.gif)

**Comment by ziyoung** [comment]
`default-expand-all` 是控制展开行的。这个属性很早就有了。Table 组件支持树形数据是 2.7 引入的。不要搞混了。具体的用法请参考文档。

**Comment by ziyoung** [comment]
如果是 issue 的话，提供个正确的链接。
