### ISSUE TITLE
[Bug Report] El-tab-panes content get re-rendered when switching tabs

### ISSUE THREAD

**Issue by kevrousso** [ElemeFE/element#15077]
### Element UI version
2.4.6

### OS/Browsers version
Windows 7 / Chrome 73

### Vue version
2.5.17

### Reproduction Link
https://codesandbox.io/s/m4x609973x

### Steps to reproduce
If you look at the console while switching tabs, you'll notice that the content of each tab-pane get re-rendered
Which is weird because unless I'm mistaken, the tab-panes are rendered once when `lazy` option is off
https://github.com/ElemeFE/element/blob/dev/packages/tabs/src/tab-pane.vue#L5

### What is Expected?
Every tab-pane's content do not re-render when switching tabs.

### What is actually happening?
Every tab-pane's content are re-rendered when switching tabs.

**Comment by kevrousso** [comment]
Note: repro link is a simplified version of my application, and may contain unnecessary stuff, but actually represent the structure it would have in a real scenario.

**Comment by Xiaoxiaoaiya** [comment]
我也遇到了类似的情况，但是只有切换个别选项卡时会重新请求数据并渲染页面

**Comment by ziyoung** [comment]
pr welcome

**Comment by kevrousso** [comment]
Why is it now closed? Is there any fix for this?
