### ISSUE TITLE
[Feature Request] DatePicker - Start selection with year then month then day

### ISSUE THREAD

**Issue by matthias-influry** [ElemeFE/element#15079]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
When using a date-picker, we can start by selection a date, but to change the year / month, you have to click on the header first (twice).
If you use the datepicker to insert a Birthday, it would be really helpful to already start with the Year overview and then move your way downwards.

I looked through the code and figured that within date-picker/src/panel/date.vue there is a function called "showMonthPicker()" and "showYearPicker()" which is called when you click on the respective header.
So maybe either in date-picker.js created hook, after setting the panel, or somewhere else,  one could call the panel function to show a specific view?
This view could be a new property for date-picker, e.g. 
`<el-date-picker view="year">`

I would do a pull request but I am not familiar with editing modules I don't even know how to compile them :-/

**Comment by ziyoung** [comment]
@wacky6 How do you think?

**Comment by ziyoung** [comment]
![Kapture 2019-05-07 at 17 05 23](https://user-images.githubusercontent.com/12947422/57287560-5dcec180-70ea-11e9-8b83-e057664eb6f6.gif)

**Comment by Tofandel** [comment]
Yes but what is asked is to have the default view without clicking..
It's not currently possible

I tried setting `:picker-options="{selectionMode: 'year'}"` but then you cannot select the month and day..

We need an option to set the default view
`:picker-options="{defaultView: 'year'}"` that would set the currentView to year

**Comment by Tofandel** [comment]
PR #18301 fullfills the feature request
