### ISSUE TITLE
[Bug Report] PopupManager's Z-index value cannot be rewritten at initial render (PopupManager's Z-index value, first rendering cannot be changed)

### ISSUE THREAD

**Issue by JeremyWuuuuu** [ElemeFE/element#15074]
### Element UI version
2.7.2

### OS/Browsers version
macOS Mojave 10.14 | Google Chrome 版本 73.0.3683.103（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/9b18thjn/](https://jsfiddle.net/9b18thjn/)

### Steps to reproduce
1. open the DevTool console ( 打开开发者工具的控制台)
2. focus on the element of the content section (在控制台中聚焦在 HTML 展示区域)
3. click "click me" button, observe the z-index value of element which class name equals "v-modal". (点击 "Click Me" 按钮, 然后观察 class 名为 "v-modal" 元素的 z-index 值, 并记录)
4. close the modal (关闭 modal)
5. repeat step 3 , then observe. (重复 第三步)

### What is Expected?
modal's z-index value should be set as props.zIndex when initiated.
modal 的 z-index 值应当为给定的值

### What is actually happening?
 modal's z-index is 2000 when initiated.
modai 的 z-index 值在第一次打开时, 永远为 2000

**Comment by JeremyWuuuuu** [comment]
![image](https://user-images.githubusercontent.com/15975785/55950419-7d0f3600-5c87-11e9-8437-66d4c48f9476.png)
https://github.com/ElemeFE/element/blob/dev/src/utils/popup/popup-manager.js

**Comment by JeremyWuuuuu** [comment]
cc @iamkun

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.

**Comment by luckyCao** [comment]
dialog 文档中没写 z-index 属性，在 popup mixin 里面找到了这个属性，会修复这个问题

**Comment by JeremyWuuuuu** [comment]
这个是一个未公开 API, 目前好像只能在 Vue.prototype.$Element 这个里面来配置初始值, 但是如果有人想用这个 mixin 的话, 可能就会遇到这个问题, 所以我觉得这个 API 还是有必要公开和修复的, 谢谢
