### ISSUE TITLE
The label type of [Bug Report] checkbox can also pass objects. Why is it not mentioned in the official document, just string / number / boolean?

### ISSUE THREAD

**Issue by GitHdu** [ElemeFE/element#15081]
### Element UI version
2.7.2

### OS/Browsers version
latest

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/3395

### Steps to reproduce
无

### What is Expected?
文档缺少object

这里是原文档:

label	选中状态的值（只有在checkbox-group或者绑定对象类型为array时有效）	string / number / boolean	—	—

### What is actually happening?
无

**Comment by ziyoung** [comment]
@GitHdu pr welcome

**Comment by edum18** [comment]
doesnt work to me, the checkbox doesnt check even though the object is added to the v-model

**Comment by GitHdu** [comment]
> doesnt work to me, the checkbox doesnt check, even though the object is added to the v-model

this is  an example
```vue
<template>
  <el-checkbox-group v-model="checkList">
    <el-checkbox v-for="(item) in list" :key="item.id" :label="item" @change="handleChange">{{item.label}}</el-checkbox>
  </el-checkbox-group>
</template>

<script>
  export default {
    data () {
      return {
        checkList: [],
        list: [{id:1, label: 'aaa'},{id:2, label: 'bbb'}]
      };
    },
  methods: {
    handleChange (val) {
      console.log(this.checkList)
    }
  }
  };
</script>
```
