### ISSUE TITLE
[Bug Report] TreeTable in DIalog can't longitudinal sliding!

### ISSUE THREAD

**Issue by superZhouDaLu** [ElemeFE/element#15085]
### Element UI version
2.8.2

### OS/Browsers version
Google

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jianlu/pen/PgjbPr

### Steps to reproduce
Dialog 内 Table 设置固定高度为 300px，首次点击按钮展开表格内的子级菜单不会自动生成纵向滑动模块，保持打开状态关闭 Dialog，再次打开后滚动菜单会被展示出来。

### What is Expected?
首次打开时，展开列表可以正常纵向滑动。

### What is actually happening?
首次打开会因为遮挡无法看到全部数据

**Comment by YuThree** [comment]
table tree is same

**Comment by fqcto** [comment]
I don't quite follow you


------------------ 原始邮件 ------------------
发件人: "YuThree"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 上午9:14
收件人: "ElemeFE/element"<element@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [ElemeFE/element] [Bug Report] TreeTable in DIalog can'tlongitudinal sliding! (#15085)




table tree is same

**Comment by superZhouDaLu** [comment]
@YuThree sry, i don‘t know your means.

**Comment by luckyCao** [comment]
fixed in #15709
