### ISSUE TITLE
[Bug Report] Tree Data and Lazy Load Component Add Subnode to Array Operation Second Push Can't Trigger View Layer Update

### ISSUE THREAD

**Issue by zhanjunhao** [ElemeFE/element#15084]
### Element UI version
2.7.2

### OS/Browsers version
WIN7 旗舰版 Service  Chrome 72.0.3626.96

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/zhanjunhao/pen/JVJRVO

### Steps to reproduce
当点击添加子节点时 第一次可触发view层更新 第二次不管是平级还是子级 使用数组的api push方法 操作data 均无法触发视图更新 但是数据（modal层）是响应式的修改了 可在console.log()查看数据源 删除节点时 子级节点下的项目第一次获取index正常 第二次获取不到相对应的对象 导致index为-1 还请官方研发修复该问题，谢谢！

### What is Expected?
修复该问题 可支持异步第二次操作数据（modal）时 添加子级 删除节点的情况 可触发视图更新 如上所述

### What is actually happening?
修复 在tree-tabel组件 使用push 添加子级 splice删除子节点 递归第二次 无法触发视图更新的问题 
建议：官方研发 可开放对应的 工具类或实例方法 如添加同级 添加子级 删除节点 那就更好不过了

**Comment by ziyoung** [comment]
see #15170
