### ISSUE TITLE
[Feature Request] Table cell width adaptation

### ISSUE THREAD

**Issue by magengxin** [ElemeFE/element#15095]
### Existing Component
是

### Component Name
table

### Description
Application Scenario: In a row of cells, I have two buttons; sometimes a button is displayed when receiving a value, and two buttons are displayed when receiving two values. How can the cell width adapt in this case?
Additional: The header of the cell table is centered and the content align: left is displayed.

https://user-images.githubusercontent.com/23067574/56015054-44746880-5d2a-11e9-8138-43823c84434a.png
https://user-images.githubusercontent.com/23067574/56015337-45f26080-5d2b-11e9-9537-bf15cc674ebf.png

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
