### ISSUE TITLE
[Feature Request] Notification 通知中是否可以添加屏蔽esc键关闭的方法？

### ISSUE THREAD

**Issue by zrygoalone** [ElemeFE/element#15099]
### Existing Component
是

### Component Name
Notification

### Description
Notification 通知中是否可以添加屏蔽esc键关闭的方法？类似于MessageBox中的closeOnPressEscape方法。现在除了修改源码无法通过其他方式屏蔽Notification的esc关闭途径。

**Comment by carpenterzoe** [comment]
臣附议！
I need the same property to prevent closing notification via pressing ESC.
