### ISSUE TITLE
[Bug Report] El table header slot not working when el-column is given via a for loop

### ISSUE THREAD

**Issue by sainathsr** [ElemeFE/element#15106]
### Element UI version
2.7.2

### OS/Browsers version
Mac os X High seira

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/sainathsr/pen/eXqXjW?editors=1111

### Steps to reproduce
Look at the code pen repo . 
When I give a header slot for el-column tag it works
When I try the same via v-for it doesnt work 

### What is Expected?
Same behaviour for both v-for and a plain tag

### What is actually happening?
When using v-for the header slot is not taken

**Comment by ziyoung** [comment]
@sainathsr can't reproduce. Closed.
