### ISSUE TITLE
[Bug Report] el-dropDown component bug

### ISSUE THREAD

**Issue by zhaoyuhang1033** [ElemeFE/element#15100]
![lALPDgQ9qnD55YrNA6jNAjQ_564_936 png_620x10000q90g](https://user-images.githubusercontent.com/36781875/56028202-36cedb00-5d4a-11e9-852b-c931113068bb.jpg)
![lALPDgQ9qnEK1yDNAhXNA1I_850_533 png_620x10000q90g](https://user-images.githubusercontent.com/36781875/56028495-d42a0f00-5d4a-11e9-99ac-980611bbda38.jpg)

### Element UI version
2.6.3

### OS/Browsers version
windows7 

### Vue version
2.5.22

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
el-dropdown 组件状态为下拉时 容器内并无滚动条 上拉时 容器内部有滚动条

### What is Expected?
下拉菜单激活时 无滚动条

### What is actually happening?
当下方空间不够改为上拉时 容器内部有滚动条

**Comment by WytheO** [comment]
Waitting,+1

![image](https://user-images.githubusercontent.com/38578631/56178612-7b51c380-6035-11e9-9814-f628ed8a2ace.png)

![image](https://user-images.githubusercontent.com/38578631/56178620-83a9fe80-6035-11e9-99b3-ba69db404561.png)

**Comment by luckyCao** [comment]
@zhaoyuhang1033 你的 demo 没保存，保存一下
