### ISSUE TITLE
el-input mask feature?

### ISSUE THREAD

**Issue by ozgureffe** [ElemeFE/element#1510]
Is there any feature or plan for input masking?
Something like https://text-mask.github.io/text-mask/ 

`****-****-****-****` (Credit Card Number)
`**/**/****` (Date)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no such plan.

**Comment by codelabstudios** [comment]
I also think this feature would be great. I tried to integrate other packages, but the v-directive doesn't get applied on the input element, but on the wrapper

**Comment by thearabbit** [comment]
👍 , I need too.
have any solve?
