### ISSUE TITLE
[Bug Report] Table alignment on resized column with sorting on Safari

### ISSUE THREAD

**Issue by sstraus** [ElemeFE/element#15102]
### Element UI version
2.7.2

### OS/Browsers version
Safari Any

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
Shrink a column forcing text and header to a smaller size, the content and the width of the header will be different from the width of the column. On Chrome will hellip, on Safari no.

### What is Expected?
Same width for header and column.

### What is actually happening?
the header width is different from the width of the column.

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
