### ISSUE TITLE
[Feature Request] How to/docs on how to update Popper position if in drag window for ElDropdown

### ISSUE THREAD

**Issue by kgrosvenor** [ElemeFE/element#15116]
### Existing Component
Yes

### Component Name
ElDropDown

### Description
How go update Popper position if in drag window for ElDropdown

I can currently for this with el-select, but what would be nice is some documentation on how these kinds of methods work and which components they exist / work with,

The code looks like this

`self.$refs.select.broadcast('ElSelectDropdown', 'updatePopper');`

i would like to update the ElDropDown popper position on window resize and on drag, but the same code as above but for ElDropDown does not work, how can i make it work so my UI doesn't seem buggy :P

Thanks for your awesome work

**Comment by ziyoung** [comment]
Please provide a demo. @kgrosvenor
