### ISSUE TITLE
[Bug Report] Module parse failed: Unexpected token (65:6) in. / node_modules/element-ui/packages/scrollbar/src/main.js

### ISSUE THREAD

**Issue by penggle** [ElemeFE/element#15112]
### Element UI version
2.7.2

### OS/Browsers version
windows10

### Vue version
2.6.6

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce

这是一个编译错误，故无法提供jsfiddle或codepen链接！

这是一个demo项目，采用babel-plugin-component按需加载的方式，代码如下：
(main.js)

import Vue from 'vue';
import { Button, Icon, Message, Input, Select, Option, OptionGroup } from 'element-ui';
import lang from 'element-ui/lib/locale/lang/zh-CN';
import locale from 'element-ui/lib/locale';

// 设置语言
locale.use(lang);

import App from './App.vue';

Vue.config.productionTip = false;
Vue.prototype.$message = Message;

Vue.use(Button);
Vue.use(Icon);
Vue.use(Input);
Vue.use(Select);
Vue.use(Option);
Vue.use(OptionGroup);

new Vue({
    render: h => h(App)
}).$mount('#app');

App.vue里面就一个最简单的<el-select/>组件

编译时出现错误！编译错误堆栈：

ERROR  Failed to compile with 1 errors                                                                                                                  17:48:08
 error  in ./node_modules/element-ui/packages/scrollbar/src/main.js

Module parse failed: Unexpected token (65:6)
You may need an appropriate loader to handle this file type.
|     }, this.$slots.default);
|     const wrap = (
>       <div
|         ref="wrap"
|         style={ style }

 @ ./node_modules/element-ui/packages/scrollbar/index.js 1:0-35 4:0-9 5:16-25 5:32-41 8:15-24
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/element-ui/packages/select/src/select.vue?vue&type=script&lang=js&
 @ ./node_modules/element-ui/packages/select/src/select.vue?vue&type=script&lang=js&
 @ ./node_modules/element-ui/packages/select/src/select.vue
 @ ./node_modules/element-ui/packages/select/index.js
 @ ./src/tutorials/select/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/tutorials/select/main.js

这个问题我看了有好几个人遇到这个问题，并向你们提了issue，但你们却不做解释的关闭了，
事实是确实有很多人遇到这个问题，请问是什么问题呢？

### What is Expected?
期待webpack编译成功

### What is actually happening?
webpack编译报错：

ERROR  Failed to compile with 1 errors                                                                                                                  17:48:08
 error  in ./node_modules/element-ui/packages/scrollbar/src/main.js

Module parse failed: Unexpected token (65:6)
You may need an appropriate loader to handle this file type.
|     }, this.$slots.default);
|     const wrap = (
>       <div
|         ref="wrap"
|         style={ style }

 @ ./node_modules/element-ui/packages/scrollbar/index.js 1:0-35 4:0-9 5:16-25 5:32-41 8:15-24
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/element-ui/packages/select/src/select.vue?vue&type=script&lang=js&
 @ ./node_modules/element-ui/packages/select/src/select.vue?vue&type=script&lang=js&
 @ ./node_modules/element-ui/packages/select/src/select.vue
 @ ./node_modules/element-ui/packages/select/index.js
 @ ./src/tutorials/select/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/tutorials/select/main.js

**Comment by ziyoung** [comment]
@penggle  你可以新建一个仓库，上传到 GitHub，我们来看一下。

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by Tritty** [comment]
我也遇到这个问题了.......

**Comment by tanhernandez** [comment]
Bump to this as well just now :(
Is there a solution for this?

**Comment by mouday** [comment]
我也是
```
import DatePanel from "element-ui/packages/date-picker/src/panel/date.vue";
```
我尝试单独引入一个组件，却报错了

**Comment by Tritty** [comment]
> 我也是
> 
> ```
> import DatePanel from "element-ui/packages/date-picker/src/panel/date.vue";
> ```
> 
> 我尝试单独引入一个组件，却报错了



https://github.com/ElemeFE/element/issues/14379#issuecomment-465025641

我这样解决了

**Comment by Tritty** [comment]
@mouday 
https://github.com/ElemeFE/element/issues/14379#issuecomment-465025641

我这样解决了

**Comment by mouday** [comment]
@Tritty Thank you very much,  i get a correct vue.config.js 

the link is my record about try this

https://pengshiyu.blog.csdn.net/article/details/103932261
