### ISSUE TITLE
[Bug Report] emit an event on el-dropdown-item click not working

### ISSUE THREAD

**Issue by Masber** [ElemeFE/element#15118]
### Element UI version
2.7.2

### OS/Browsers version
mac os

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/masber/pen/gyGPRG?editors=1111

### Steps to reproduce
extend "dropdown list" and click on "Action 1"

### What is Expected?
to print 'event recorded!' in the console

### What is actually happening?
nothing, the event is not sent

**Comment by ziyoung** [comment]
```diff
- new Vue().$mount('#app')
+ new Ctor().$mount('#app')
```

**Comment by ziyoung** [comment]
You also need to use `$on` to add event listener for test evnet.
```js
created() {
   this.$on('test', fn);
}
```
