### ISSUE TITLE
Timeline :reverse Broken

### ISSUE THREAD

**Issue by jason-e-gross** [ElemeFE/element#15110]
### Element UI version
2.7.2

### OS/Browsers version
All

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/xeLZZw?&editable=true

### Steps to reproduce
Create a timeline with timeline-items.     In the body of a timeline item, add a click event on any element.   Even a click.stop event.  When that fires, timeline is sorted back to reverse = false;

### What is Expected?
it to leave the order alone

### What is actually happening?
dunno but I have to do *this* to make it behave:

				Vue.nextTick(function () {
					this.listReverse = !this.listReverse;
					Vue.nextTick(function () {
						this.listReverse = !this.listReverse;
					})
				})

**Comment by ziyoung** [comment]
@jason-e-gross sorry, I don't know what's going wrong. Please update your demo.

**Comment by snachx** [comment]
@ziyoung I have updated the demo, https://codepen.io/anon/pen/GaxgME
1. click "ascending"
2. click any label on the timeline, for example click the "success".

**Comment by ziyoung** [comment]
![Kapture 2019-06-13 at 12 13 34](https://user-images.githubusercontent.com/12947422/59403318-c5a4b600-8dd4-11e9-97bb-a62556baa410.gif)
@snachx now I find it works fine for me. My chrome is  75.0.3770.80.

**Comment by snachx** [comment]
@ziyoung 
Chrome: 75.0.3770.90, Safari 12.1.1 (14607.2.6.1.1)
demo: https://codepen.io/anon/pen/GaxgME
It seems that the bug is still there.
