### ISSUE TITLE
[Feature Request] Select prefix for tags while in multiple and no-collapse mode

### ISSUE THREAD

**Issue by LolliDepp** [ElemeFE/element#15127]
### Existing Component
Yes

### Component Name
Select

### Description
Add a template in the Select multiple AND no-collapse view mode to allow users to inject a custom prefix for each selected item

Prefix for single item is already implemented, multiprefix should work in a similar way.

**Comment by LolliDepp** [comment]
Closed PR because not compatible with Vue 2.5 syntax

**Comment by ziyoung** [comment]
Closed.
