### ISSUE TITLE
[Bug Report] Could not get the uploaded file type

### ISSUE THREAD

**Issue by ferozyj** [ElemeFE/element#15121]
### Element UI version
2.7.2

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/GLMPZN

### Steps to reproduce
打开控制台，上传DOC文件，查看成功信息，type类型为空

### What is Expected?
显示文件的类型

### What is actually happening?
文件的类型为空

**Comment by ferozyj** [comment]
![image](https://user-images.githubusercontent.com/29189291/56123681-83632200-5fa7-11e9-80a5-d6cf2a425fb4.png)
补充图片

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
