### ISSUE TITLE
[Bug Report] el-input with Number Modifiers can't type Decimal include zero

### ISSUE THREAD

**Issue by sunchanglong** [ElemeFE/element#15129]
### Element UI version
2.7.2

### OS/Browsers version
mac chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/sunchanglong/pen/wZqVjx

### Steps to reproduce
<el-input type="number" v-model.number="num"/>  
在输入框内输入 1.0 

### What is Expected?
保留 .0

### What is actually happening?
.0 会丢失

**Comment by zWingz** [comment]
https://codesandbox.io/s/woox9q7zm8

if use `v-model.number` without `type=number` , can't input a `.`, like `1.0`

**Comment by sunchanglong** [comment]
@zWingz your problem is when input `.` will `$emit input event` and cause type  convert. so  `Number('1.')` to  `1`.   
set `type=number` will not `$emit input event` .
so this works as expect.

**Comment by ziyoung** [comment]
https://element.eleme.cn/#/zh-CN/component/input#input-shu-ru-kuang

**Comment by algking** [comment]
是这个道理, 但是用起来不方便呢..v-model.number 方便很多
