### ISSUE TITLE
[Bug Report] label-width="auto" issue an error when go back pages

### ISSUE THREAD

**Issue by fanbinghuadev** [ElemeFE/element#15135]
### Element UI version
2.7.2

### OS/Browsers version
mac os 10.14 (18A391) / chrome  73.0.3683.103

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
1.set label-width="auto" in form-item element in  pageA.
2.navigate from pageB to PagA.
3.go back pageB from PageA.
4.errors will ocurred

### What is Expected?
1. no erros.

### What is actually happening?
1.errors ocurred.

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by 9-lives** [comment]
确实存在

**Comment by codesboy** [comment]
也遇到同样的问题，给Form-Item添加了label-width="auto"属性后，当在进行路由跳转的时候,比如this.$router.push('/xxx')，就会产生报错。删除label-width="auto"属性后，不会再报错。下面是错误的截图：
![QQ20190527-192019](https://user-images.githubusercontent.com/9047357/58416548-8aa44200-80b4-11e9-94cd-0fad0006a604.png)
