### ISSUE TITLE
[Bug Report] Can not be deleted or Input in el--input component 

### ISSUE THREAD

**Issue by alive-z** [ElemeFE/element#15130]
### Element UI version
2.7.2

### OS/Browsers version
Google Chrome 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/qwVggP?&editable=true

### Steps to reproduce
reload

### What is Expected?
can deleted or Input

### What is actually happening?
can not deleted or Input

**Comment by susiwen8** [comment]
@alive-z I don't think this is a bug
https://cn.vuejs.org/v2/api/index.html#Vue-set
according to this you need change your setInput function
`setInput(){
      let that = this;
      setTimeout(function(){
        that.$set(that.a, 'input', '12345')
      },2000);
  }
`

**Comment by ziyoung** [comment]
Thanks @susiwen8

**Comment by alive-z** [comment]
sorry，el-input updated Controlled components. i should define field
