### ISSUE TITLE
取消 el-tree 的点击展开／收缩功能（默认已展开）？

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#1513]
现在可以透过 `:defaultExpandAll="true"`来默认展开，能否进一步禁用掉点击节点时的展开／收缩？

**Comment by furybean** [comment]
1.0.3 中，props 中可以指定 isLeaf 属性到 data 中的一个属性，这样就能控制这个节点是否有展开按钮。

**Comment by wukongtime** [comment]
请问，“props 中可以指定 isLeaf 属性到 data 中的一个属性”，有实际的例子嘛？我在data中加上了isLeaf属性为true，没有作用，展开节点还是存在的。谢谢。

**Comment by wukongtime** [comment]
已解决，如下：
在props中加入isLeaf: 'isLeaf'
```
        defaultProps: {
          children: 'children',
          value: 'value',
          label: 'label',
          isLeaf: 'isLeaf'
        }
```
在children对象中，加入isLeaf: true即可。

再次感谢开发者。

**Comment by yeomanyang** [comment]
@wukongtime @furybean   碰到一样的需求，但是按照你的做法，展开按钮还是出现了，请问是什么原因？
