### ISSUE TITLE
[Bug Report] el-tabs cannot bind data bidirectionally by distributing custom titles through slots

### ISSUE THREAD

**Issue by zqian11** [ElemeFE/element#15138]
### Element UI version
2.7.0

### OS/Browsers version
win7、最新版谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zqian11/pen/qwpBPK

### Steps to reproduce
新标签页中执行方法修改标签页标题，标题无变化；切换标签页后数据刷新。

### What is Expected?
事件执行后标签页标题数据双向绑定，同步修改。

### What is actually happening?
事件执行后标签页标题数据无变化，切换标签页后修改。

**Comment by jonathan82** [comment]
I have this issue too.  Tab title slot doesn't update reactively unless switching to another tab.

**Comment by zqian11** [comment]
> 我也有这个问题。除非切换到另一个选项卡，否则选项卡标题槽不会被动地更新。
我使用elment提供的label，再配合加上slot分发label可以解决这个问题，但我不知道这样对不对。
https://codepen.io/zqian11/pen/oOEvbb

**Comment by NengGe** [comment]
我也是这个问题, http://jsrun.net/PwXKp/edit    2.4.x版本是可以的 很早前提出issue 但是一直没修复...
