### ISSUE TITLE
[Bug Report] webstorm does not recognize elm Tags

### ISSUE THREAD

**Issue by qinkaiyuan** [ElemeFE/element#15132]
### Element UI version
2.4.11

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/13527

### Steps to reproduce
由于element-ui version2 使用了typescript，导致使用全局引入element-ui时webstrom无法识别element标签，从而给出”Unknown html tag el-menu ”警告

### What is Expected?
在webstrom中使用标签能只能补全，并且不会给出“Unknown html tag el-menu ”的警告

### What is actually happening?
希望官网人员不要逃避bug，虽然不是elm的bug，但是也影响了大家使用elm，希望官方能够提供合适的解决办法

webstrom找不到element-ui的vue组件，并且给出警告（不影响实际运行，但确实很不好。）

**Comment by luckyCao** [comment]
![image](https://user-images.githubusercontent.com/10645449/57346998-54ddfe80-7183-11e9-8888-f669d70b47cf.png)
![image](https://user-images.githubusercontent.com/10645449/57346999-54ddfe80-7183-11e9-9e94-40c77046e5c2.png)

使用 el-menu 并没有给出「Unknown html tag el-menu 」的警告

**Comment by qinkaiyuan** [comment]
你用了typescript吗

**Comment by qinkaiyuan** [comment]
我使用了 typescript vue-cli3创建的项目 使用 vue add element添加的elm，依赖中有vue-cli-plugin-element 这个插件

**Comment by Sdoy** [comment]
别用cnpm安装依赖

**Comment by qinkaiyuan** [comment]
我用的是npm，不是cnpm
