### ISSUE TITLE
[Bug Report] Why tabs not  synchronize？

### ISSUE THREAD

**Issue by lilu1814** [ElemeFE/element#15136]
### Element UI version
2.7.2

### OS/Browsers version
chrome 73

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/p2mhu9rv/3/

### Steps to reproduce
https://jsfiddle.net/p2mhu9rv/3/

### What is Expected?
tab value change

### What is actually happening?
tab value not change

**Comment by masongzhi** [comment]
you can change your code like this https://jsfiddle.net/b87ot1wv/1/

because when the `label` change it will emit parent to update, `$slots.label` did not
```js
// tab-pane
watch: {
  label() {
    this.$parent.$emit('tabLabelChanged');
  }
}
```

**Comment by jinwyp** [comment]
I think it is bug 


see below  is not working , slot function is for customize design to show multi value in label.  why we still add ":label="item.count", it is not convenience

```
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui@2.7.2/lib/index.js"></script>
<div id="app">
<template>
  <el-tabs v-model="activeName" @tab-click="handleClick">
    {{list[0]}}
    <el-tab-pane v-for="item in list" :key="item.name" :name="item.name" :label="item.count">
      <span slot="label"><i class="el-icon-date"></i> {{item.count.a}}-{{item.count.b}}</span>
    </el-tab-pane>
   
  </el-tabs>
</template>
</div>


```

below is working , it is not convenience

```
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui@2.7.2/lib/index.js"></script>
<div id="app">
<template>
  <el-tabs v-model="activeName" @tab-click="handleClick">
    {{list[0]}}
    <el-tab-pane v-for="item in list" :key="item.name" :name="item.name" :label="item.count.a">
      <span slot="label"><i class="el-icon-date"></i> {{item.count.a}}-{{item.count.b}}</span>
    </el-tab-pane>
   
  </el-tabs>
</template>
</div>


```

**Comment by masongzhi** [comment]
@jinwyp I agree with you, and this will be a current solution
