### ISSUE TITLE
When [Bug Report] datetime-picker uses the time range selector, it changes V-model to null when it is empty, resulting in error in traversal time

### ISSUE THREAD

**Issue by hevi1991** [ElemeFE/element#15148]
### Element UI version
2.7.2

### OS/Browsers version
MacOS 10.14.4

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
1.写好el-date-picker组件的配置
2.设置完值之后，点击旁边的清除按钮
3.可以看到配置的v-model变成了null

### What is Expected?
清空后变为空数组

### What is actually happening?
清空后为null

**Comment by wacky6** [comment]
这不是bug，设计上空值就是 null。
