### ISSUE TITLE
[Bug Report] the guide for cascader  has a bug

### ISSUE THREAD

**Issue by ydykid** [ElemeFE/element#15145]
### Element UI version
2.7.2

### OS/Browsers version
mac 10.13.3 / firefox 66.0.3

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/PgEgvm?editors=1111

### Steps to reproduce
the guide for  cascader , Dynamically load child options:
the option in handleItemChange function should not be option2
action: select one of the parents, show none child  

### What is Expected?
after select, there should be at least one child

### What is actually happening?
after select, there is none child

**Comment by SimonaliaChen** [comment]
Fixed in 15352
