### ISSUE TITLE
[Bug Report] Cascader, search filterable, set props, select search results and report errors

### ISSUE THREAD

**Issue by anihCevol** [ElemeFE/element#15140]
### Element UI version
2.7.2

### OS/Browsers version
win10/chrome 最新版

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anihcevol/pen/EJoaQJ?editors=1010

### Steps to reproduce
Cascader，可搜索filterable，设置props，选中搜索结果报错，点击下拉，一级一级的操作选择不会报错，是我设置的props不对吗

### What is Expected?
Cascader，可搜索filterable，设置 ‘props’ ，选择搜索结果正常

### What is actually happening?
Cascader，可搜索filterable，设置 ‘props’，选择搜索结果报错

**Comment by SimonaliaChen** [comment]
fixed in #15611
