### ISSUE TITLE
[Bug Report] el-select If you choose to search remotely and focus events, every click on options will trigger the focus event, is it not a problem?

### ISSUE THREAD

**Issue by guoyucloud** [ElemeFE/element#15143]
### Element UI version
2.7.2

### OS/Browsers version
macOS/chrome

### Vue version
2.6.10

### Reproduction Link
codepen

### Steps to reproduce
el-select 如果选择远程搜索与focus事件的时候，每次点击options选项都会出发focus事件，而且无法区分事件来自select的input还是options

### What is Expected?
在远程搜索与focus事件共存的时候，返回值应该区分开是select的input还是options触发的该事件，或者options不应该触发focus事件，否则会感到很奇怪。目前看源码是 远程搜索事件广播出的事件在select中被写成固定广播focus了导致的。

### What is actually happening?
el-select 如果选择远程搜索与focus事件的时候，每次点击options选项都会出发focus事件，而且无法区分事件来自select的input还是options

**Comment by ziyoung** [comment]
不算是 bug。要始终保持 select 中的 input 获得焦点。
