### ISSUE TITLE
A small problem with [Bug Report] Cascader selector

### ISSUE THREAD

**Issue by liub1934** [ElemeFE/element#15147]
### Element UI version
2.7.2

### OS/Browsers version
win10/CHrome 72.0.3626.121

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/qwpzeM

### Steps to reproduce
Cascader选择器的数据将最后一级的children数据设置成空数组，如children: []，选择器会自动生成一个空的一列选择，正常情况下不应该有的。

### What is Expected?
Cascader选择器不应该为空的children生成一项空的选择

### What is actually happening?
Cascader选择器生成了空的一项选择
![image](https://user-images.githubusercontent.com/29849550/56263624-394c7e80-6116-11e9-8407-22982366dc50.png)

**Comment by ziyoung** [comment]
Duplicate of #10027
