### ISSUE TITLE
[Bug Report] Incomplete style when introducing ColorPicker components on demand

### ISSUE THREAD

**Issue by jxbb** [ElemeFE/element#15151]
### Element UI version
2.7.2

### OS/Browsers version
windows 10 / chrome 73

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/bJLNPo

### Steps to reproduce
按续引入ColorPicker组件

### What is Expected?
colorpicker组件正常

### What is actually happening?
功能正常
清空按钮和色值文本框样式错误

经测试需要再引入
import 'element-ui/lib/theme-chalk/Autocomplete.css';
import 'element-ui/lib/theme-chalk/Dropdown.css';

**Comment by luckyCao** [comment]
pr welcome
