### ISSUE TITLE
When the [Bug Report] table is clicked, a misalignment occurs, that is, when the mouse hovers over the cell, the next row of data is displayed.

### ISSUE THREAD

**Issue by hexiaojun5233** [ElemeFE/element#15154]
### Element UI version
2.7.2

### OS/Browsers version
win10专业版/360极速浏览器

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
在element官网中或项目中使用table组件使用单击选中行时，鼠标悬停在一行数据上方时发生选中颜色变化的却是另外一行数据
补充：本人使用两台显示器，一台显示器分辨率1920*1080（以下称为显示器1），另外一台显示器分辨率是1440*900（显示器2）,将element页面拖拽至显示器2上时，选中正常，异常发生在显示器1上边

### What is Expected?
希望能尽快修复这种两种显示器同时使用时出现的bug

### What is actually happening?
element table组件使用单击选中时发生异常，当选中一行时发生了错位现象

**Comment by SimonaliaChen** [comment]
Issues without a valid reproduction link will be closed directly.
