### ISSUE TITLE
A column of el-table-column containing v-show or V-IF triggers its bound function several times when the [Bug Report] el-table component hover has a row of data

### ISSUE THREAD

**Issue by liuchihanxiang** [ElemeFE/element#15155]
### Element UI version
2.7.2

### OS/Browsers version
谷歌

### Vue version
2.6.6

### Reproduction Link
https://codepen.io/liuchihanxiang/pen/ZZrOBW

### Steps to reproduce
鼠标移入表格内 f12可以看到由于hover触发打出的字

### What is Expected?
表格内的v-show 只在开始时触发  hover不触发

### What is actually happening?
每次hover都会触发

**Comment by Wmmm520** [comment]
大佬，我也遇到了这个问题。

**Comment by ziyoung** [comment]
2.8.2 已修复。
