### ISSUE TITLE
<el-input v-on:keydown.enter="addItem"></el-input> 无法绑定按键操作

### ISSUE THREAD

**Issue by liuzhaowei55** [ElemeFE/element#1515]
### ElementUI version 
1.0.3

### OS/Browers version
macOS/Chrome  54.0.2840.98 (64-bit) 

### Vue version
 2.1.0

### 问题
```
<el-input v-on:keydown.enter="addItem"></el-input>
```
 无法绑定按键操作

**Comment by bensonlove** [comment]
v-on:keyup.enter.native
