### ISSUE TITLE
[Bug Report] Image's Orientation about the iPhone

### ISSUE THREAD

**Issue by RicoLiu** [ElemeFE/element#15162]
### Element UI version
2.7.2

### OS/Browsers version
iPone

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/boilerplate/vue

### Steps to reproduce
1.iPhone 调用摄像头竖屏拍照；
2.通过 el-upload 组件进行上传图片；
3.上传后显示在前端的图片会被逆时针旋转90度；

### What is Expected?
上传后显示在前端的图片显示正常

### What is actually happening?
竖屏拍照上传后的图片会被逆时针旋转90度

**Comment by RicoLiu** [comment]
Here is the test image(2448 × 3264):
![IMG_8722](https://user-images.githubusercontent.com/12722992/56332189-ea5c2300-61c1-11e9-819a-e3a514b238cc.JPG)

And here is the upload result:

![QQ20190418100440HD](https://user-images.githubusercontent.com/12722992/56332203-f811a880-61c1-11e9-974d-edb0d7367778.gif)

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
