### ISSUE TITLE
The [Bug Report] el-popover tag does not support ref with capital letters

### ISSUE THREAD

**Issue by Chenxc7** [ElemeFE/element#15169]
### Element UI version
2.7.2

### OS/Browsers version
chorme

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/ZZxYZo

### Steps to reproduce
点击正常弹出和错误弹出两个不同的按钮

### What is Expected?
大小写均可正常调用

### What is actually happening?
包含大写无法调用

**Comment by ziyoung** [comment]
It's not a bug of Element. https://jsfiddle.net/bx0tacqw/
