### ISSUE TITLE
[Bug Report] clear button won't show with hover when option value is undefined

### ISSUE THREAD

**Issue by xianshenglu** [ElemeFE/element#15166]
### Element UI version
2.7.2

### OS/Browsers version
win10/chrome 74.0.3729.75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xianshenglu/pen/yrKLqe?editors=1010

### Steps to reproduce
1. click the input
2. choose [label1]
3. hover mouse to select arrow you will see clear button
4. choose [all] 
5. hover mouse to select arrow

### What is Expected?
clear button should show thought [all] value is undefined.

Logic of whether to show clear button should be 

`isClearButtonHide=!options.some(option=>option.selected)`

not just 

`isClearButtonHide=selectedValue===undefined || selectedValue===null || selectedValue===''`

### What is actually happening?
clear button didn't show because [all] value is undefined

**Comment by xianshenglu** [comment]
related bug https://github.com/ElemeFE/element/issues/11451

**Comment by SimonaliaChen** [comment]
Do not use `value: undefined` , try other meaningful values.
