### ISSUE TITLE
[Bug Report] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by biaoG** [ElemeFE/element#15163]
### Element UI version
2.7.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
重现步骤：
在路由a内，使用el-dialog组件打开一个对话框，通过确定按钮，再次调用MessageBox.alert模态对话框，点击确定关闭alert对话框，再点 取消 关闭dialog对话框，然后切换到路由B，路由B页面有使用DatePicker 日期选择器组件时，则会报异常， RangeError: Maximum call stack size exceeded

### What is Expected?
从路由A切换到路由B页面时，应正常渲染DatePicker 日期选择器组件

### What is actually happening?
没有正常渲染DatePicker 日期选择器组件，报错提示 RangeError: Maximum call stack size exceeded

**Comment by georgyfarniev** [comment]
Please fix codepen link

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
