### ISSUE TITLE
[Feature Request] To use these components not appearing in documents.

### ISSUE THREAD

**Issue by XuXianTao** [ElemeFE/element#15160]
### Existing Component
否

### Component Name
Transfer

### Description
I want to use the TransferPanel in the Transfer. 
But I have to register in throught Transfer like this..
``` ElTransferPanel.js
import {Transfer} from 'element-ui'
const ElTransferPanel = Transfer.components.TransferPanel
ElTransferPanel.name = 'ElTransferPanel'
export default ElTransferPanel
```

I don't know if the subcomponents like ElTransferPanel will change in the future version. So I hope I can use these subcomponents directly.

By the way, seriously, I want to know that will those subcomponents really change the props or data in the different versions.

**Comment by XuXianTao** [comment]
因为想要使用一些组件的子组件，像是穿梭框的列表，虽然可以通过Transfer访问得到，但是不确定在其他版本中会不会有改动。希望能将类似的这种子组件也提供出注册接口和文档说明。

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
