### ISSUE TITLE
[Feature Request] 表头filters，不需要默认添加"全部"选项

### ISSUE THREAD

**Issue by capricorncd** [ElemeFE/element#15172]
### Existing Component
是

### Component Name
ElTableFilterPanel

### Description
表头filters，不需要默认添加"全部"选项
https://github.com/ElemeFE/element/pull/15171

![image](https://user-images.githubusercontent.com/25501698/56346069-e0531800-61f3-11e9-94dc-46657b2cadfc.png)

**Comment by ziyoung** [comment]
提供一个可重现的 demo 链接。

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
