### ISSUE TITLE
[Bug Report] toggle Row Selection can't work for multiple rows.

### ISSUE THREAD

**Issue by bcjohnblue** [ElemeFE/element#15174]
### Element UI version
2.7.2

### OS/Browsers version
Windows 10 Chrome

### Vue version
2.6.6

### Reproduction Link
https://jsfiddle.net/4Lutrdcm/1/

### Steps to reproduce
使用el-table的toggleRowSelection時，我想在使用者按下按鈕後，根據表格資料裡的isCheck去切換被選擇的狀態。由範例可以看到我設定了第二、三列的isCheck 等於 false，但是當第一次按下按鈕後只會取消第二列的選擇狀態，要再按一次才會把第三列的選擇狀態也取消。

### What is Expected?
按下按鈕後應該同時把第二列及第三列的選擇狀態都取消。

### What is actually happening?
只有第二列的選擇狀態被取消，而第三列的狀態要再一次按鈕才會取消。

**Comment by ziyoung** [comment]
https://jsfiddle.net/017mhtyf/ select-change 的回调会调用多次。回调函数的逻辑得再调整一下。
