### ISSUE TITLE
[Bug Report] Смена заголовков при загрузке файла

### ISSUE THREAD

**Issue by azchatlanin** [ElemeFE/element#15177]
### Element UI version
2.7.2

### OS/Browsers version
Версия 73.0.3683.103 (Официальная сборка), (64 бит)

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US

### Steps to reproduce
Установка заголовков происходит при монтировании элемента. 
:headers="{ 'token': token }"

Но что если мне нужно поменять заголовки в before-upload?
this.token = localStorage.getItem("app-token")

Они не меняются. Заголовок остается старым.

### What is Expected?
Чтоб будет установлен новый заголовок

### What is actually happening?
Заголовки не меняются остается старым.

**Comment by georgyfarniev** [comment]
Приветствую. Во-первых, вряд ли кто-то из разрабов знает русский язык, во-вторых, приведите пожалуйста пример кода, который воспроизводит проблему в виде jsfiddle или codepen, быть может я смогу что-то подсказать или понять почему headers не меняются динамически. 

Hello. I don’t think that developers of element knows Russian language. Please provide some example using codepen or jsfiddle that reproduces your issue, so we can figure out why headers not updating reactively.

**Comment by Luummii** [comment]
Добрый день.
Во-первых, вряд ли кто-то из разрабов знает русский язык...
https://github.com/ElemeFE/element/issues/15187
https://github.com/ElemeFE/element/issues/15172
https://github.com/ElemeFE/element/issues/15099
https://github.com/ElemeFE/element/issues/14771
https://github.com/ElemeFE/element/issues/14742
https://github.com/ElemeFE/element/issues/14712

Это ссылки по поводу языка и так ... поверхностно. Из которых вообще не понятно, что там за проблемы и как их решили и чем людям нужно помочь. И гуглтранслит, вот вообще ни как не помогает. Так что уж если решили разрабы общаться не только на английском, не чего мордочку воротить от русского. А вам, с такой учтивостью, буду признателен если возьмете и во всех issues, где присутствует отличный от вашего мира язык, оставить аналогичный комментарий, но с переводом на язык автора этих issues.

По поводу всего остального. Я решил уже это проблему и в моем случае она перестала быть актуальной. И решена именно через computed property.

**Comment by Luummii** [comment]
> Приветствую. Во-первых, вряд ли кто-то из разрабов знает русский язык, во-вторых, приведите пожалуйста пример кода, который воспроизводит проблему в виде jsfiddle или codepen, быть может я смогу что-то подсказать или понять почему headers не меняются динамически.
> 
> Кстати, пробовали завернуть объект headers в computed property?
> 
> Hello. I don’t think that developers of element knows Russian language. Please provide some example using codepen or jsfiddle that reproduces your issue, so we can figure out why headers not updating reactively.
> 
> Have you tried to wrap headers object to computed property?

Добрый день.
Во-первых, вряд ли кто-то из разрабов знает русский язык...
https://github.com/ElemeFE/element/issues/15187
https://github.com/ElemeFE/element/issues/15172
https://github.com/ElemeFE/element/issues/15099
https://github.com/ElemeFE/element/issues/14771
https://github.com/ElemeFE/element/issues/14742
https://github.com/ElemeFE/element/issues/14712

Это ссылки по поводу языка и так ... поверхностно. Из которых вообще не понятно, что там за проблемы и как их решили и чем людям нужно помочь. И гуглтранслит, вот вообще ни как не помогает. Так что уж если решили разрабы общаться не только на английском, не чего мордочку воротить от русского. 

А вам, с такой учтивостью, буду признателен если возьмете и во всех issues, где присутствует отличный от вашего мира язык, оставить аналогичный комментарий, но с переводом на язык автора этих issues.

Ну и самим разрабам это правило тоже объясните. Потому как им это объяснение ну очень нужно. И о необходимости этого объяснения вы можете догадаться, когда нажмете ТУТ на гитхабе в ИХ репозитории кнопку - New issue. 

По поводу всего остального. Я решил уже это проблему и в моем случае она перестала быть актуальной. И решена практически через computed property.
