### ISSUE TITLE
[Feature Request] The complete model of the ElForm binding is passed in when the ElFormItem form is validated

### ISSUE THREAD

**Issue by ooopp7788** [ElemeFE/element#15184]
### Existing Component
是

### Component Name
ElFormItem

### Description
现状是ElFormItem组件中，验证时使用的model是重新创建了一个以prop为key的对象，我们在使用async-validator自定义验证方法validator(rule, value, cb, model)时，参数model和value其实是有一些重复，并且无法使用纯函数做关联验证，必须在Vue data上定义验证函数。如果能够在验证时传入ElForm完整model就太好了，就是不知道会不会对其他功能产生影响。

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
