### ISSUE TITLE
[Bug Report] TimePicker defaults to January 1st when user enters time directly into input with keyboard

### ISSUE THREAD

**Issue by freeman-g** [ElemeFE/element#15180]
### Element UI version
2.7.2

### OS/Browsers version
Chrome 73

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/jRzzxg

### Steps to reproduce
Enter time directly into the input with keyboard, e.g., type "8:00 AM".

Note: when using the dropdown selector with mouse, the date defaults correctly.

### What is Expected?
I expect the date to default to the correct date based on the default-value property

### What is actually happening?
The date is defaulting to January 1st

![image](https://user-images.githubusercontent.com/495886/56367131-8f76fb80-61c2-11e9-882c-f767942c44a5.png)

**Comment by wacky6** [comment]
time-picker does not have default-time attribute. where do you come across such usage?

**Comment by wacky6** [comment]
default-value does not work like it. It only controls the date/time initially shown to the user. It will not affect the emitted value.

IMO, `time-picker` only concerns about time (hour/minute/seconds). If you want to control date, explicitly set date outside time picker. Or use `value-format` to get a time string, which is more sensible.
