### ISSUE TITLE
树形组件更新到新版本报错

### ISSUE THREAD

**Issue by 312798** [ElemeFE/element#15183]
vue.esm.js?ff17:610 [Vue warn]: Error in callback for watcher "data": "Error: if there's nested data, rowKey is required."

Error: if there's nested data, rowKey is required.

**Comment by yanbaodong** [comment]
@@ -13,6 +13,7 @@ export default {
  methods: {
    updateExpandRows() {
      const { data = [], rowKey, defaultExpandAll, expandRows } = this.states;
      if (!data) return;
