### ISSUE TITLE
[improvement]form item label with input

### ISSUE THREAD

**Issue by dsonet** [ElemeFE/element#1518]
### ElementUI version
1.0.3
https://elementui.github.io/dev/dev/#/zh-CN/component/form

### What is Expected?
Hope label can have 'for' attribute or input can wrapped with label, get better accessibility.
### What is actually happening?
All labels are not really related to input.

**Comment by alanaasmaa** [comment]
This would also fix this problem: https://github.com/ElemeFE/element/issues/5398

**Comment by DomenicRoti** [comment]
Is there an example somewhere of how to implement this?
