### ISSUE TITLE
[Bug Report] toggleRowSelection必须要传入完整对象吗？

### ISSUE THREAD

**Issue by wenyiweb** [ElemeFE/element#15187]
### Element UI version
2.7.2

### OS/Browsers version
windows 10 / Chrome73.0.3683.103

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
通过toggleRowSelection设置table行取消选中或者选中，只用id封装了对象，原始table里面一行数据的对象属性有多个。如  tableData = [{id: 1, name: '123', price: 10}, {id: 2, name: '234', price: 10},{id: 3, name: '345', price: 10}]。调用toggleRowSelection({id:1}, false)。无效

### What is Expected?
调用toggleRowSelection({id:1}, false)。应该取消选中

### What is actually happening?
调用toggleRowSelection({id:1}, false)。无效

**Comment by wenyiweb** [comment]
这个只是一个简单的场景描述，真正使用是选中的行现在在el-tag列表中，通过el-tag中删除某一个元素实现table行取消选中。如果每次都要传入完整数据，对后台接口压力太大，需要查询的数据太多

**Comment by Mioooooo** [comment]
你好，我也遇到了这个问题，请问是怎么解决的呢

**Comment by BearXmX** [comment]
哇，这操作也太蠢点了吧，居然传入完整对象，写的人是用屁股在想嘛，头大了
