### ISSUE TITLE
[Bug Report] After ElForm calls resetFields, the first time modification of the form content does not trigger validation (occasional)

### ISSUE THREAD

**Issue by qiangbro** [ElemeFE/element#15181]
### Element UI version
0.1.0

### OS/Browsers version
win7 Google Chrome 73.0.3683.103（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/g6o15s94/

### Steps to reproduce
连点两次重置按钮，然后点文本框，输入u。不触发校验，再输入u，才触发。

以上是官方示例。而在我自己的项目中（不方便公开），点击重置按钮后，第一次修改表单偶尔不触发校验，第二次修改才触发。

### What is Expected?
不论了连续点击几次重置（只要大于或等于一次），然后点文本框，然后输入u，应该立即就会触发表单校验。

### What is actually happening?
点击重置，然后点文本框，然后输入u，不会立即触发表单校验，而是第二次输入u才一定会触发校验

**Comment by qiangbro** [comment]
我阅读了ElForm的源代码，当调用form的resetFields后，formItem的validateDisabled被置为了true，导致el.form.change事件产生时，formItem的第一次validate被跳过。
![image](https://user-images.githubusercontent.com/4646469/56401530-dc72d480-628b-11e9-877f-528e03b297fd.png)

**Comment by qiangbro** [comment]
第二次点击重置，elInput的value值前后一致导致watch 没有被触发，所以没有el.form.change事件传给ElFormItem，使得formItem的validateDisabled保持true。
![image](https://user-images.githubusercontent.com/4646469/56402510-22ca3280-6290-11e9-9415-cd56946a6234.png)

**Comment by qiangbro** [comment]
方案：resetField的初始值还原阶段，应该采用深复制的办法，避免input的watch无法被触发。

![image](https://user-images.githubusercontent.com/4646469/56402873-b94b2380-6291-11e9-8c9b-ab6d3dc17ea4.png)

**Comment by luckyCao** [comment]
#15640

**Comment by luckyCao** [comment]
pr #15640 已经合并
