### ISSUE TITLE
el-upload file raw 

### ISSUE THREAD

**Issue by menciusKael** [ElemeFE/element#15193]
I want to get the file in the on-progress function, And then request the interface , But the format of the argument seems wrong , I've added headers: { "Content-Type": "multipart/form-data" } ,
but it show like this :
![image](https://user-images.githubusercontent.com/29659731/56414413-0e505f00-62bd-11e9-83a2-7db379e2f553.png)

it should be like this :
![image](https://user-images.githubusercontent.com/29659731/56414457-29bb6a00-62bd-11e9-9679-1daffb1539c0.png)
 
how to change it correct

**Comment by hamedbaatour** [comment]
You cannot store an unserializable object in the store (vuex...) that is why you see {uid: 32094} only. the rest of the native File object will get stripped out.
