### ISSUE TITLE
[Feature Request] TreeTable Enhancement

### ISSUE THREAD

**Issue by chao921125** [ElemeFE/element#15191]
### Existing Component
是

### Component Name
Table

### Description
1、自定义图标（Custom icons）
2、开放展开、收缩点击事件（Open and Expand and Shrink Click Events）
3、设置默认展开、收缩（Set default expansion and contraction）
4、复选框功能完善（Complete function of check box）

**Comment by YuThree** [comment]
Open and Expand and Shrink Click Events
Set default expansion and contraction
**Very necessary**！！！

**Comment by YuThree** [comment]
another suggestion is that the height of the table should be adapted to the height of the table when it is expanded 
like the function I found in code is 

> updatescrolly

**Comment by iamkun** [comment]
#15170
