### ISSUE TITLE
How does [Bug Report] element 2.7.2 support the default tree table expansion state?

### ISSUE THREAD

**Issue by qzmly100** [ElemeFE/element#15198]
### Element UI version
2.7.2

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/qzmly100/pen/rbvgWv

### Steps to reproduce
我希望数据渲染后表格可以默认展开 

https://segmentfault.com/q/1010000018929003

### What is Expected?
我希望数据渲染后表格可以默认展开 

https://segmentfault.com/q/1010000018929003

### What is actually happening?
我希望数据渲染后表格可以默认展开 

https://segmentfault.com/q/1010000018929003

**Comment by iamkun** [comment]
#15170
