### ISSUE TITLE
[Feature Request] Recommendations for Paging Components

### ISSUE THREAD

**Issue by zcjm60** [ElemeFE/element#15199]
### Existing Component
是

### Component Name
Pagination 分页组件

### Description
分页组件能否添加配置禁用首页和尾页的选项，就是layout属性添加禁/启动首页尾页的选项,个人qq1157537225

**Comment by haoranyu** [comment]
你是希望在分页组件中添加类似这样的东西吗？

Are you requesting something like the following?

![image](https://user-images.githubusercontent.com/2560088/56485342-3d0d4600-6506-11e9-8467-37b67ace534e.png)

**Comment by zcjm60** [comment]
不是我是希望把最后一页和第一页的按钮干掉
![image](https://user-images.githubusercontent.com/22487059/56486612-c757a900-650a-11e9-986f-1cad5b09f041.png)
![image](https://user-images.githubusercontent.com/22487059/56486633-d5a5c500-650a-11e9-9160-db209cebef65.png)

**Comment by zcjm60** [comment]
> 你是希望在分页组件中添加类似这样的东西吗？
> 
> 你要求的东西如下吗？
> 
> ![图片](https://user-images.githubusercontent.com/2560088/56485342-3d0d4600-6506-11e9-8467-37b67ace534e.png)

不是我是希望把最后一页和第一页的按钮干掉
如下图
![image](https://user-images.githubusercontent.com/22487059/56491113-fe818680-6519-11e9-8f49-3eabc24c5ce3.png)
![image](https://user-images.githubusercontent.com/22487059/56491123-093c1b80-651a-11e9-9b93-9bbe1d921cec.png)

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
