### ISSUE TITLE
建议带有upload的表单验证操作resetFields时候，把cover也删掉

### ISSUE THREAD

**Issue by annieh12** [ElemeFE/element#1520]
### Reproduction Link

我的demo：[http://jsfiddle.net/hxrwith/jfaL2h55/](http://jsfiddle.net/hxrwith/jfaL2h55/)

### What is actually happening?
问题有两个：
1、要是先handleSubmit，出现了错误提示后，再上传图片的话，这个错误提示并没有消失；
2、已经上传图片了，这时候handleReset的话，cover依然存在。

### What is Expected?
1、这个错误提示不知道能不能实时更新，希望能做到实时响应吧；
2、建议带有upload的表单验证操作resetFields时候，把cover也删掉。

**Comment by annieh12** [comment]
@baiyaaaaa 因为现在需要用到这个功能，等不及你们发版了，先冒昧问一下怎么触发onRemove这个行为？因为我需要在resetFields后顺便删除这个cover。

**Comment by baiyaaaaa** [comment]
@annieh12 你可以通过upload实例的clearFiles方法来把当前文件列表清空。

**Comment by annieh12** [comment]
@baiyaaaaa 不是的，resetFields后，当前文件列表也清空了。就差cover没有删掉。

**Comment by baiyaaaaa** [comment]
不会啊，cover显示的就是当前第一个文件，如果当前文件列表为空那就不会显示cover

**Comment by annieh12** [comment]
请问怎么使用呢？http://jsfiddle.net/hxrwith/jfaL2h55/1/  总是报错clearFiles is not a function。
我依然觉得不是当前文件列表的问题。。。。
你可以在我的这个例子里操作一下吗？

**Comment by annieh12** [comment]
我知道怎么做了，谢谢
