### ISSUE TITLE
[Bug Report] el-table tree table automatically shrinks expanded rows after adding new row data to the outermost layer

### ISSUE THREAD

**Issue by Flystaring** [ElemeFE/element#15201]
### Element UI version
2.7.2

### OS/Browsers version
chrome 73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/flystaring-the-sasster/pen/oOMvem

### Steps to reproduce
懒加载树形表格：
Step1： 点开含有子节点的数据行，使节点展开；
Step2：点击按钮，添加新的一行数据

### What is Expected?
结果：数据添加成功，但是原本已经展开的行却收缩，而且再次展开时需要重新请求数据
预期：添加一行后，节点不会自动收缩，
注意：不是使用load属性添加子数据，而是在最外层添加行数据

### What is actually happening?
原因暂时未知

**Comment by ziyoung** [comment]
Duplicate of #15201
