### ISSUE TITLE
[Bug Report] Time control and text control and button display UI asymmetry in one line

### ISSUE THREAD

**Issue by m17319325007** [ElemeFE/element#15204]
### Element UI version
2.7.2

### OS/Browsers version
mac 10.14.2 / chrome 73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
https://user-images.githubusercontent.com/23732011/56480482-db8cad80-64ec-11e9-9f0a-d5eadb161112.png

### Steps to reproduce
https://user-images.githubusercontent.com/23732011/56480482-db8cad80-64ec-11e9-9f0a-d5eadb161112.png

### What is Expected?
https://user-images.githubusercontent.com/23732011/56480482-db8cad80-64ec-11e9-9f0a-d5eadb161112.png  希望能够对齐

### What is actually happening?
https://user-images.githubusercontent.com/23732011/56480482-db8cad80-64ec-11e9-9f0a-d5eadb161112.png

**Comment by luckyCao** [comment]
请提供一个 demo
