### ISSUE TITLE
Can the [Feature Request] Pagination component add pages that support a limited maximum number of skip pages similar to Google's?

### ISSUE THREAD

**Issue by rxliuli** [ElemeFE/element#15203]
### Existing Component
Yes

### Component Name
2.7.2

### Description
Windows10/Chrome 73

# `Pagination` 组件是否可以添加支持类似于 **Google** 的那种有限制最大跳转页数的分页呢？

## 场景

目前遇到的一个问题就是如果允许随意跨页的话，例如从第一页跳转到 10000  页，数据查询会比较慢（MongoDB 要一条条的找过去），有什么好的解决方法么？

下面是 Google 的搜索结果分页，可以看到，Google 只允许用户有限制的跨页跳转

![image](https://user-images.githubusercontent.com/24560368/56480523-0aa31f00-64ed-11e9-9a78-2b42bc3bf11d.png)

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
