### ISSUE TITLE
[Bug Report] Dynamic Edit Tag: TypeError: _this. $refs. saveTagInput is undefined

### ISSUE THREAD

**Issue by Karma1996** [ElemeFE/element#15210]
### Element UI version
2.7.2

### OS/Browsers version
win10 / firefox 66.03(64)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
按需引入Tag组件后，使用动态编辑标签，然后点击“New Tag”终端会报错：TypeError: _this.$refs.saveTagInput is undefined

### What is Expected?
点击“New Tag”能够正确的添加标签。

### What is actually happening?
终端报错，项目停止运行。
![image](https://user-images.githubusercontent.com/37733288/56492111-4eae1800-651d-11e9-8bc5-ae34a96f4482.png)

**Comment by luckyCao** [comment]
请提供一个可复现的 demo
