### ISSUE TITLE
[Feature Request] one thought about togglerowselection function in el-table

### ISSUE THREAD

**Issue by HaiyangZhang1994** [ElemeFE/element#15215]
### Existing Component
Yes

### Component Name
el-table

### Description

I'm using el-table and try to re-check some rows after data is updating, but it doesn't work, I viewed the source code about togglerowselection function and found that you're using indexOf() to determine if row is in the data, it doesn't work when array contains objects, so I fix this by also updating rows, then put them in togglerowselection function. 

I don't know if you meant to do this to keep original data, but using Array.find() might be another way to make this function more convenient. This is only my thought, feel free to contact me if you want.

**Comment by island205** [comment]
pr welcome
