### ISSUE TITLE
[Bug Report] DateTime Picker bug

### ISSUE THREAD

**Issue by huangyusi** [ElemeFE/element#15219]
### Element UI version
2.6.1

### OS/Browsers version
谷歌浏览器

### Vue version
2.7.2

### Reproduction Link
无连接

### Steps to reproduce
在使用DateTimePicker组件的时候，当点击日期时间选择器的时候报错，TypeError: mask.replace is not a function，

### What is Expected?
帮我解决这个问题，使DateTimePicker能使用

### What is actually happening?
帮我解决这个问题，使DateTimePicker能使用

![image](https://user-images.githubusercontent.com/36812714/56547965-6800a400-65b1-11e9-8e57-6d482016f108.png)

**Comment by wacky6** [comment]
请提供重现链接

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by hamzhi** [comment]
I caught the same error
[Vue warn]: Error in render: "TypeError: mask.replace is not a function"

It happened because I had a function in my global mixin there was a function with the same name as the elements component had. It was dateFormat. When I was change the name, problem is gone

**Comment by iAmYuhi** [comment]
所以解决方案到底是什么？
