### ISSUE TITLE
[Bug Report] el-autocomplete setting value property does not take effect

### ISSUE THREAD

**Issue by zbjy** [ElemeFE/element#15225]
### Element UI version
2.7.2

### OS/Browsers version
Google Chrome 版本 71.0.3578.98（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/BEOLEM?&editable=true

### Steps to reproduce
el-autocomplete 设置value属性不生效

### What is Expected?
el-autocomplete 设置value属性生效

### What is actually happening?
el-autocomplete 设置value属性不生效

**Comment by SimonaliaChen** [comment]
`v-model` 和 `value`只能传一个

**Comment by zbjy** [comment]
@SimonaliaChen 2.4.11版本是可以的

**Comment by zbjy** [comment]
> `v-model` 和 `value`只能传一个

 2.4.11版本是可以的

**Comment by songStar0904** [comment]
使用自定义组件v-model 的时候 :value也是失效的 2.12.0 2.11.1 都有这个问题 2.4.11版本没有
