### ISSUE TITLE
[Feature Request] [Popover]: popper-class attribute can receive a Array like v-bind:popper-class="[styleObjectA, styleObjectB]" in vue.js?

### ISSUE THREAD

**Issue by AllenChinese** [ElemeFE/element#15227]
### Existing Component
是

### Component Name
Popover

### Description
Is it possible that popper-class attribute can receive a Array like v-bind:popper-class="[styleObjectA, styleObjectB]" in vue.js？Sometimes we need multiple classes。It can works in ElementUI but throw some errors now。

**Comment by SimonaliaChen** [comment]
目前popper-class只支持字符串，你可以通过空格分隔传入多个类名
