### ISSUE TITLE
[Bug Report] Unknown custom element: <el-scrollbar> on click on filter in table

### ISSUE THREAD

**Issue by benjamin79** [ElemeFE/element#15230]
### Element UI version
2.7.2

### OS/Browsers version
Windows 10 / Chrome 73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
Sorry. Don´t know how to use partitial imports in jsfiddle. 

### Steps to reproduce
import Vue from 'vue';
import {Table,TableColumn} from 'element-ui';

Vue.use(Table);
Vue.use(TableColumn);

Click on  the dropdown arrow to filter a column in a table

Even if importing all possible components the arrow still shows.

### What is Expected?
No error.

### What is actually happening?
[Vue warn]: Unknown custom element: <el-scrollbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by troy351** [comment]
try add this
```javascript
import { Scrollbar } from 'element-ui'
Vue.use(Scrollbar)
```

**Comment by ton77v** [comment]
I'm having the same issue 

> try add this
> 
> ```js
> import { Scrollbar } from 'element-ui'
> Vue.use(Scrollbar)
> ```

importing Scrollbar don't work for me

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by ton77v** [comment]
Created issue with reproduction link here https://github.com/ElemeFE/element/issues/16158
