### ISSUE TITLE
When uploading a file fails, you do not want to delete the failed item directly in the fileList

### ISSUE THREAD

**Issue by hzjjg** [ElemeFE/element#15232]
### Element UI version
2.7.2

### OS/Browsers version
mac && win

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/packages/upload/src/index.vue

### Steps to reproduce
上传文件，上传失败的项会从fileList中被删除。

### What is Expected?
不要直接删除项，我希望在列表中显示他失败的状态，而不是直接消失。

### What is actually happening?
删除失败的项被splice

**Comment by iamkun** [comment]
pr welcomed

**Comment by island205** [comment]
pr welcome
