### ISSUE TITLE
[Feature Request] the extend of i18n

### ISSUE THREAD

**Issue by lianghx-319** [ElemeFE/element#15241]
### Existing Component
Yes

### Component Name
i18n

### Description
When I create a component base on ElementUI, I also want to support i18n with the same style with ElementUI. For example, the use function in /lib/locale, if I make a new lang extend for my component and use(myLangExtend), it will override the old one. And there are more than two components use(aLangExtend), only one can work at a moment. So I suppose to a deepmerge in use function or the order way to support i18n extend.

**Comment by island205** [comment]
please provide a demo about your problem.
