### ISSUE TITLE
[Feature Request] Textarea can not use slot

### ISSUE THREAD

**Issue by bingomvm** [ElemeFE/element#15246]
### Existing Component
是

### Component Name
Input

### Description
Why does Input component not support the use of the slot , when its type is textarea.

**Comment by iamkun** [comment]
请描述具体需求

**Comment by bingomvm** [comment]
主要是想用slot实现textarea的输入文字计数功能，发现最近更新的版本支持了。但是并不是用slot实现的。
为什么el-input的type为textarea不支持slot？想了解下原因。

**Comment by iamkun** [comment]
有需求就会加的
