### ISSUE TITLE
[Bug Report] Cannot scroll by up key or down key when any tab pane is clicked (focus)

### ISSUE THREAD

**Issue by SYJACK7** [ElemeFE/element#15252]
### Element UI version
2.7.2

### OS/Browsers version
Windows 10 / Chrome 70.0.3538.102

### Vue version
2.5.13

### Reproduction Link
https://codepen.io/SYJACK7/pen/GLwOJe

### Steps to reproduce
1,选中一个tab pane
2,使用方向键 向下或向上进行滚动

对照操作：
1，不选中任意tab pane或者 点击空白部分，让tab pane 失焦

### What is Expected?
页面正常向下或向上滚动

### What is actually happening?
页面无法滚动出被选中tabs所在的部分
且tabs随着上下按键的触发不断切换

**Comment by SYJACK7** [comment]
目前采用了如下方法解决这个问题

 let a = document.getElementsByClassName('el-tabs__nav is-top')
 a.forEach(item => {
     item.addEventListener('keydown', (e) => {
        e.stopPropagation()
        return false
   }, true)
})

**Comment by island205** [comment]
Sorry, we have no plan to support this.
