### ISSUE TITLE
[Bug Report] el-upload does not work on Android browsers

### ISSUE THREAD

**Issue by snowdream** [ElemeFE/element#15251]
### Element UI version
2.4.6

### OS/Browsers version
Android/华为浏览器 10.7.2.4045

### Vue version
2.6.9

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
1. In android browser, open the dashboad, use el-upload to upload image.
2. The image does not be selected and uploaded.

### What is Expected?
1. In android browser, open the dashboad, use el-upload to upload image.
2. The image can be selected and uploaded.

### What is actually happening?
1. In android browser, open the dashboad, use el-upload to upload image.
2. The image does not be selected and uploaded.

**Comment by snowdream** [comment]
It seems because "accept="image/jpeg,image/gif,image/png"".
```
        <el-upload
          :on-preview="handlePictureCardPreview"
          :on-remove="handlecheshengRemove"
          :on-success="handlecheshengUploadSuccess"
          :on-error	="handleUploadError"
          :before-remove	="handleBeforeRemove"
          :before-upload="handleBeforeUpload"
          :on-exceed="handleExceed"
          :file-list="cheshengfilelist"
          :action="url"
          :data="cheshengzhaopianData"
          with-credentials
          accept="image/jpeg,image/gif,image/png"
          list-type="picture-card">
          <i class="el-icon-plus"/>
        </el-upload>
``
When i change it to "accept="image/*"", it works.
```
      <el-form-item label="车身照片" prop="cheshengzhaopian">
        <el-upload
          :on-preview="handlePictureCardPreview"
          :on-remove="handlecheshengRemove"
          :on-success="handlecheshengUploadSuccess"
          :on-error	="handleUploadError"
          :before-remove	="handleBeforeRemove"
          :before-upload="handleBeforeUpload"
          :on-exceed="handleExceed"
          :file-list="cheshengfilelist"
          :action="url"
          :data="cheshengzhaopianData"
          with-credentials
          accept="image/*"
          list-type="picture-card">
          <i class="el-icon-plus"/>
        </el-upload>
```
https://yeaseonzhang.github.io/2017/03/06/%E5%BE%AE%E4%BF%A1%E6%B5%8F%E8%A7%88%E5%99%A8Bug/
https://my.oschina.net/u/2306318/blog/1512155
https://www.jianshu.com/p/1ab00ee63925

**Comment by iamkun** [comment]
Element is designed for desktop. It's not compatible with mobile devices. FYI: https://github.com/vuejs/awesome-vue#mobile-1
