### ISSUE TITLE
[Bug Report] Cascader `>` icon no longer appearing in 2.8.0

### ISSUE THREAD

**Issue by oller** [ElemeFE/element#15262]
### Element UI version
2.8.0

### OS/Browsers version
OSX 10.14

### Vue version
2.6.10

### Reproduction Link
https://element.eleme.io/#/en-US/component/cascader#cascader

### Steps to reproduce
Click on the cascader in the docs to expand/open it.

### What is Expected?
the `>` icon to appear right aligned against each item that can be expanded.

### What is actually happening?
the `>` icon, is no longer loading.  suspect this line: https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/cascader.scss#L140 isn't referencing the right character in the icon-font.  not sure if it ought to be fixed here or in the font generation side. 

There may be other instances of icon font characters referenced in the stylesheet that have also changed if the character mapping of the icon font has been altered.

**Comment by ziyoung** [comment]
#15264
