### ISSUE TITLE
[Tree] 希望增加是否通过点击行来展开节点的选项

### ISSUE THREAD

**Issue by wuchuguang** [ElemeFE/element#1526]
el-tree组件，点击父节点的名称（label）会缩展子节点，点击父节点的 > 图标也会缩展。
能不能提供属性，可以关闭 “点击父节点名称缩展”，缩展只能点击 >图标 。

**Comment by wenner** [comment]
十分需要这个需求,而且默认的应该只点击前面的 箭头 才会打开/关闭

现在只能通过写 renderContent , 然后 在tree-node-content 节点上(JSX) 写 onClick={this.onContentClick} , 
然后再 onContentClick 方法中 stopPropagation....

我觉得官方解决这个应该一下下就好了吧...

**Comment by furybean** [comment]
#1805 已经增加。

**Comment by Sinampire** [comment]
您好 element-ui 目前有没有暴露在树已经渲染完毕后 点击按钮控制结点全部展开/折叠的方法？

**Comment by TabCrazy** [comment]
希望能增加一个方法、根据传入data或getNode拿到的node，主动展开树节点，展开的同时如果开启异步获取数据也能异步拿数据。外部某个按钮点击调用此

**Comment by TabCrazy** [comment]
希望能增加一个方法、根据传入data或getNode拿到的node，主动展开树节点，展开的同时如果开启异步获取数据也能异步拿数据。非树上的某按钮点击时候、调用此方法能展开树节点
