### ISSUE TITLE
Can the [Feature Request] calendar component support styling modifications for some special dates?

### ISSUE THREAD

**Issue by wangyibinwangyi** [ElemeFE/element#15279]
### Existing Component
是

### Component Name
DatePicker

### Description
希望日历组件可以允许对一些特殊日期进行样式上的修改，如对20190426这一日标红，或者添加class。
目前日历组件支持禁用某些日期，但是不支持特殊显示某些日期。
或者可以提供对每个日期的dom上标注这一日期的时间戳，以便css可以找到并修改样式。
万分感谢。

**Comment by ziyoung** [comment]
自定义内容 https://element.eleme.cn/#/zh-CN/component/calendar#zi-ding-yi-nei-rong
