### ISSUE TITLE
When the [Bug Report] drop-down box is multiple-selected, the check mark is not displayed after the selected item.

### ISSUE THREAD

**Issue by sds0917** [ElemeFE/element#15275]
### Element UI version
2.8.2

### OS/Browsers version
window10/chrome 74

### Vue version
2.5.16

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
官网上的select多选demo就可以看到此问题。
![微信截图_20190425205056](https://user-images.githubusercontent.com/7779851/56737153-5cbd9c00-679c-11e9-9ca8-18b33f883fae.png)

### What is Expected?
被选中选项后面有对号

### What is actually happening?
被选中选项后面没有对号

**Comment by oller** [comment]
I believe this has already been patched with https://github.com/ElemeFE/element/pull/15264
