### ISSUE TITLE
[Bug Report] el-table set max-height only doesn't work after release-2.8.0

### ISSUE THREAD

**Issue by chenweitech** [ElemeFE/element#15281]
### Element UI version
2.8.0

### OS/Browsers version
All

### Vue version
2.6.10

## Reproduction Link

#14660

### Steps to reproduce
PR[#14660] caused anthor bug - el-table set max-height only doesn't work

### What is Expected?
set max-height can work normally

### What is actually happening?
tables-body height always be 60px

**Comment by GitHanDong** [comment]
我也遇到了同样的问题。
现在还是将版本锁定在2.8.0之前了。
去掉【max-height】会恢复正常。

**Comment by ziyoung** [comment]
这是我测试的 demo。没看出来哪里出问题了。https://jsfiddle.net/djmtapyh/

**Comment by fudax** [comment]
同样的问题，刚想来提issue的就看到首页这个
问题版本：2.8.2
`<el-table :data="filterResult" :max-height="baseHeight - 36" size="small"
……
</el-table>
`

**Comment by fudax** [comment]
`    <div
      class="el-table__body-wrapper"
      ref="bodyWrapper"
      :class="[layout.scrollX ? `is-scrolling-${scrollPosition}` : 'is-scrolling-none']"
      :style="[bodyHeight]">`

**Comment by neostfox** [comment]
"div",
        {
          ref: "bodyWrapper",
          staticClass: "el-table__body-wrapper",
          class: [
            _vm.layout.scrollX
              ? "is-scrolling-" + _vm.scrollPosition
              : "is-scrolling-none"
          ],
          style: [_vm.bodyHeight]
        }
I see  style: [_vm.bodyHeight] in Webpack source

**Comment by fudax** [comment]
先手工在全局的样式里强制修改：
```
.el-table .el-table__body-wrapper {
   max-height: 9999px !important;
}
```
等fix发掉再改回来~

**Comment by chenweitech** [comment]
@ziyoung 直接初始化table组件是正常的，但是如果是异步获取的数据则内容不会撑开父容器，这是我的例子 https://jsfiddle.net/atugsewp/2/

**Comment by ziyoung** [comment]
> @ziyoung 直接初始化table组件是正常的，但是如果是异步获取的数据则内容不会撑开父容器，这是我的例子 https://jsfiddle.net/atugsewp/2/

是 bug。

**Comment by sunxingchen1995** [comment]
也遇到了同样的问题，已经回退锁死版本了，希望尽快解决

**Comment by xiongchengqing** [comment]
什么时候发布新版本解决这个问题呀

**Comment by s12113122** [comment]
同样的问题+1 QQQ

**Comment by Air1996** [comment]
还以为自己代码出问题了 =-=

**Comment by fangwenzheng88** [comment]
我也是，2.8.0版本表格优化还是很不错的，可是这个bug直接退到2.7.2了。

**Comment by ArtlessProgrammer** [comment]
:data=[,,,,,,,,,,,,] 
display:none -> request call back display: ''

**Comment by zdd2018** [comment]
> 我也是，2.8.0版本表格优化还是很不错的，可是这个bug直接退到2.7.2了。

我回退到2.7.2还是有这个问题，不知道为啥

**Comment by caoke** [comment]
> > 我也是，2.8.0版本表格优化还是很不错的，可是这个bug直接退到2.7.2了。
> 
> 我回退到2.7.2还是有这个问题，不知道为啥
回退到2.7.2就没有这个问题了

**Comment by zdd2018** [comment]
> > > 我也是，2.8.0版本表格优化还是很不错的，可是这个错误直接退到2.7.2了。
> > 
> > 
> > 我回退到2.7.2还是有这个问题，知道不为啥
> > 回退到2.7.2就没有这个问题了

我也不知道为啥，之前好好的，把node_modules删了重装就这样了，我的解决办法是把他的样式覆盖
` 
.el-table__body-wrapper.is-scrolling-none{
  max-height:440px;
  overflow-y: auto;
}`

**Comment by luckyCao** [comment]
fixed in #15709
