### ISSUE TITLE
[Bug Report] datetime-picker shows wrong time value when data is like "yyyy-MM-dd"

### ISSUE THREAD

**Issue by heimii** [ElemeFE/element#15285]
### Element UI version
2.4.6

### OS/Browsers version
win10/firefox/chrome

### Vue version
2.5.17

### Reproduction Link
https://github.com/ElemeFE/element/issues/new

### Steps to reproduce
code: 
<el-date-picker v-model="form.payDate" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd HH:mm:ss"  format="yyyy-MM-dd HH:mm:ss" />

form.payDate is: 2019-01-01

display value: 2019-01-01 08:00:00

### What is Expected?
display value: 2019-01-01 00:00:00

### What is actually happening?
display value: 2019-01-01 08:00:00

**Comment by fudax** [comment]
you can use the format "yyyy/MM/dd"
it begins with zero alock
but "yyyy-MM-dd"'s default is just begin with 8 aclock~

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
