### ISSUE TITLE
[Bug Report] icon does not exist in version 2.8.2

### ISSUE THREAD

**Issue by lilu1814** [ElemeFE/element#15287]
### Element UI version
2.8.2

### OS/Browsers version
chrome73

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/wZRRGW?&editable=true

### Steps to reproduce
在element-ui2.8.2版本上写个<i class="el-icon-circle-check-outline"></i>

### What is Expected?
显示icon

### What is actually happening?
没有显示icon

**Comment by susiwen8** [comment]
@lilu1814 2.8.2版本貌似没有这个icon了
https://element.eleme.io/#/zh-CN/component/icon

**Comment by agoni1212** [comment]
`el-icon-circle-check`

**Comment by drugo** [comment]
the new icons exceed the size limit of webpack url-loader .
I think the problem is in file-loader publicPath.

**Comment by jaumesala** [comment]
I had the same problem after upgrading to 2.8.2. Icons were not loading/showing.  
Solved after clean install... 

```sh
rm -rf node_modules/
npm install
```

**Comment by michaeljaekel** [comment]
To me it looks like the generated path to the icon files is wrong.

npm run build generates element-icons.ttf and element-icons.woff
in **dist/static/fonts/** 
but where expected to be loaded from /dist/static/**css/static/**fonts/ which leads to a 404 error while loading the page.
GET [myDomain]/dist/static/css/static/fonts/element-icons.535877f.woff net::ERR_ABORTED 404

**Comment by lilu1814** [comment]
> @lilu1814 2.8.2版本貌似没有这个icon了
> https://element.eleme.io/#/zh-CN/component/icon

**Comment by 86driver** [comment]
> To me it looks like the generated path to the icon files is wrong.
> 
> _npm run build_ generates element-icons.ttf and element-icons.woff
> in **dist/static/fonts/**
> but they are expected to be loaded from /dist/static/**css/static/**fonts/ which leads to a 404 error while loading the page.
> GET [myDomain]/dist/static/css/static/fonts/element-icons.535877f.woff net::ERR_ABORTED 404

so have you solve this problem yet?

**Comment by michaeljaekel** [comment]
As a quick 'n dirty workaround I simply copied the icon files to the expected location at the target server.
This works fine, until I'll update element-ui's version where the error will be fixed.

**Comment by apo2k7** [comment]
Is there any solution to this problem jet? We are running into the same issue after updating from version 2.4.11 to 2.11.1 any help would be appreciated.

**Comment by garyzoar** [comment]
Thnis seems not to be fixed yet!

**Comment by zhoufanglu** [comment]
Has anyone solved it yet? 
el-icon build 404
