### ISSUE TITLE
select的size属性问题

### ISSUE THREAD

**Issue by tonylinyy** [ElemeFE/element#1528]
在1.0.3的时候,如下代码设置了size='small'的时候,可以正常生效,升级到1.0.4以后,设置无效
<el-select v-model="source" size="small" placeholder="来源" @change="sourceChange">
          <el-option
              v-for="item in sourceArr"
              :value="item">
          </el-option>
        </el-select>

**Comment by Leopoldthecoder** [comment]
Select 在目前的设计稿中并没有区分尺寸。1.0.3 代码中的 `size` 属性未在文档中列出，也不鼓励用户使用，因为它仅用于 Pagination 组件中选择每页显示条目数的 Select。如果需要小型 Select，可以通过 CSS 来覆盖样式。

未来有计划支持多种大小的 Select。
