### ISSUE TITLE
[Bug Report] recommends optimizing the value displayed as backfilling when asynchronous backfilling data does not match in el-select

### ISSUE THREAD

**Issue by zqian11** [ElemeFE/element#15283]
### Element UI version
2.8.2

### OS/Browsers version
最新版本

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zqian11/pen/oOJypZ

### Steps to reproduce
el-select中回填数据时，回填的数据与选项列表value未匹配时，此时展示内容为回填的值。

### What is Expected?
希望能增加新的属性，作用于数据回填结果未匹配时el-select选择器框体可以直接展示自定义文字。例如：el-select未匹配时直接在框体中展示【无匹配数据】，类似placeholder效果，且v-model绑定的值置空，因为回填原值无实际意义。

### What is actually happening?
el-select中回填数据时，回填的数据与选项列表value未匹配时，此时展示内容为回填的值。

**Comment by iamkun** [comment]
设计如此 而且这种更改是 breaking change

**Comment by sami6002** [comment]
我也需要这样的功能，如果不匹配的时候显示自定义的文本，而不是value值，你解决了吗？@zqian11
