### ISSUE TITLE
[Feature Request] Can you extract the calendar from the date selector?

### ISSUE THREAD

**Issue by Lymlair** [ElemeFE/element#15284]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
我需要一个日历控件，element里只有通过日期选择器点击来显示，我想把日历的代码提取出来，但我不会找，希望官方能出一个？

**Comment by haoranyu** [comment]
你需要的是不是 https://element.eleme.io/#/zh-CN/component/calendar 这种呢？2.8 里新出的。

Are you requesting for https://element.eleme.io/#/zh-CN/component/calendar which is a new component in Element 2.8.

**Comment by iamkun** [comment]
参考上面回复

**Comment by Lymlair** [comment]
谢谢两位，我都不知道是我没看到还是以前确实没有了… 不过找到了就行，再次感谢
