### ISSUE TITLE
[Bug Report] current-change event trigger bug

### ISSUE THREAD

**Issue by Joyzen** [ElemeFE/element#15289]
### Element UI version
2.8.2

### OS/Browsers version
windows 10 /chrome 73(64bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/joyzen/pen/dLwayM

### Steps to reproduce
1.change the value of page number ,the event 'current-change' won't trigger;

2.change the total from 21 to 20,the current page changed from 5 to 4,but the event 'current-change' didn't trigger;

### What is Expected?
trigger event 'current-change'

### What is actually happening?
didn't trigger

**Comment by Joyzen** [comment]
I found the source below,so my question is should   the event be trigger only in the case of user selected the pagination page number?
![image](https://user-images.githubusercontent.com/18508793/56792261-cc369880-683b-11e9-87ce-61256fc7579e.png)

**Comment by island205** [comment]
Changing `total` pages by programing will not trigger `current-change` event.
