### ISSUE TITLE
[Bug Report] Dialog component in ie11 and below, click Close to flash back

### ISSUE THREAD

**Issue by greatWeber** [ElemeFE/element#15282]
### Element UI version
2.8.2

### OS/Browsers version
ie11,10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/fgqvb10m/
(由于在ie上打不开上面的链接，可以在element官网上看一下bug的情况)

### Steps to reproduce
点击Dialog关闭，等它完全关闭后，有一半机率会突然回闪一下

### What is Expected?
Dialog关闭后，其里面的内容不会突出出现

### What is actually happening?
Dialog关闭后，其里面的内容突出出现

**Comment by island205** [comment]
@greatWeber Could you pelase record a video for this issue?

**Comment by island205** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
