### ISSUE TITLE
[Bug Report] NavMenu can't set the sub-menu expansion event to click when folding. Hover expansion mode is very unfriendly in touch screen devices.

### ISSUE THREAD

**Issue by 2681137811** [ElemeFE/element#15297]
### Element UI version
2.7.2

### OS/Browsers version
chrome73

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io

### Steps to reproduce
在 NavMenu 组件中将 collapse  设为 true，将 menu-trigger 设为 click

### What is Expected?
NavMenu 的 menu-trigger 属性，在 collapse = true 时候也能够生效

### What is actually happening?
NavMenu 的 menu-trigger 属性，在 collapse = true 时候无法生效

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
