### ISSUE TITLE
[Bug Report] Input Input Input Suggestion Displays Exceptions in Data Switching

### ISSUE THREAD

**Issue by LinXingYao** [ElemeFE/element#15308]
### Element UI version
2.8.2

### OS/Browsers version
window

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/VNReWR?&editable=true

### Steps to reproduce
1.在点击输入建议的时候可以正常的出现建议
2.点击lalala，之后再点击输入建议，原来的loadAll的数据会闪一下，再进入loading之后再加载完成loadcnmua的数据

### What is Expected?
不会有闪一下的状况

### What is actually happening?
实际就是loadAll和loadcnmua数据切换的时候，原先的数据都会闪一下，体验不好

**Comment by island205** [comment]
Sorry, we have no plan to fix this, PR welcome
