### ISSUE TITLE
[Feature Request] If Cascader can support remote-method?

### ISSUE THREAD

**Issue by wufeicris** [ElemeFE/element#15301]
### Existing Component
Yes

### Component Name
Cascader

### Description
just like Select component remote-method

**Comment by SimonaliaChen** [comment]
U can pass dynamic data by listening `active-item-change` ![demo](https://element.eleme.io/#/zh-CN/component/cascader#dong-tai-jia-zai-ci-ji-xuan-xiang)
We will add your feature later, please continue to pay attention,  tks.

**Comment by iamkun** [comment]
active-item-change
