### ISSUE TITLE
[Bug Report] table树形数据更新children里面的数据不触发视图更新

### ISSUE THREAD

**Issue by cangjingge** [ElemeFE/element#15302]
### Element UI version
2.8.2

### OS/Browsers version
谷歌73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
初始化数据之后。修改任意二级的数据都不会触发视图更新

### What is Expected?
自动触发视图重新渲染

### What is actually happening?
无法触发子级的model显示

**Comment by zhanjunhao** [comment]
https://github.com/ElemeFE/element/issues/15084 兄弟😄

**Comment by fqcto** [comment]
Hello, my friend,
------------------ 原始邮件 ------------------
发件人: "zhanjunhao"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 上午8:36
收件人: "ElemeFE/element"<element@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [ElemeFE/element] [Bug Report] table树形数据更新children里面的数据不触发视图更新 (#15302)




#15084 兄弟

**Comment by zhanjunhao** [comment]
Your example is empty https://codepen.io/pen

**Comment by ziyoung** [comment]
Duplicate of #14998
