### ISSUE TITLE
Compatibility of [Bug Report] message box on the iPhone X

### ISSUE THREAD

**Issue by emptiness77** [ElemeFE/element#15307]
### Element UI version
2.8.2

### OS/Browsers version
ios12/safari

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/emptiness77/pen/jRJbdP

### Steps to reproduce
在iPhone X自带浏览器中打开页面，点击删除按钮，出现弹窗，再点击确认按钮

### What is Expected?
弹出“删除失败”的确认框，点击确定后弹出框和灰幕都消失

### What is actually happening?
弹出“删除失败”的确认框后马上就自动消失了，但灰幕并没有消失，必须重新刷新页面才能消失

**Comment by iamkun** [comment]
Element is designed for desktop. It's not compatible with mobile devices. FYI: https://github.com/vuejs/awesome-vue#mobile-1
