### ISSUE TITLE
Max-height Failure of [Bug Report] 2.8.2 el-table

### ISSUE THREAD

**Issue by govo** [ElemeFE/element#15310]
### Element UI version
2.8.2

### OS/Browsers version
任何浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/didkobravo/pen/MvMYrV

### Steps to reproduce
使用2.8.2版本的elUI，任何版本的VUE，都可以重现问题，max-height无效。
解决方法：退回2.4.11版本就没问题

### What is Expected?
max-height正常

### What is actually happening?
max-height无效，高度只有一行
注：上面的Reproduction Link乱写的。

**Comment by cjsky666** [comment]
2.7.2 及以下都没问题，因为2.8有一个Bug修复是说保持height和max-height的一致性。结果导致了2.8+的版本全部出现你说的这个问题[https://github.com/ElemeFE/element/pull/14660](url)[https://github.com/ElemeFE/element/issues/15281](url)

**Comment by yangbin932** [comment]
2.8的max-height始终是60px

**Comment by iamkun** [comment]
#15309

**Comment by git9527** [comment]
临时解决方案，覆盖element自带样式

.el-table--scrollable-y .el-table__body-wrapper {
  max-height: inherit !important;
}
