### ISSUE TITLE
el-tabs 在 2.8.2版本中不能使用

### ISSUE THREAD

**Issue by yangzaixiang** [ElemeFE/element#15316]
组件引用之后页面就崩溃掉了， 测试了几小时， 发现el-tab-pane下不能存在元素

**Comment by zealpane** [comment]
我也遇到这个问题了，坑啊

**Comment by SageSanyue** [comment]
https://github.com/ElemeFE/element/issues/15712
you can look this for help
用<el-tabs>出现浏览器阻塞问题是因为项目vue版本过低elment版本过高，降级即可解决问题。
