### ISSUE TITLE
[Bug Report] nuxt uses element-ui2.8 to report errors

### ISSUE THREAD

**Issue by SmluVFpI** [ElemeFE/element#15315]
### Element UI version
2.8.2

### OS/Browsers version
win10 x64 / chrome 73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
1. 使用 create-nuxt-app 命令创建一个初始的 nuxt 应用
2. install 时保证 element-ui 版本大于 2.8.0
3. 运行 yarn dev 命令

### What is Expected?
1. 如果 2.8.0 以上版本不支持 ssr，请明确在文档中提醒。
2. 如果要支持请修复该问题。

### What is actually happening?
出现 HTMLElement is not defined 报错，显然是用了 HTMLElement 导致了 element-ui 不支持 ssr 模式。2.8.0以下的版本不会出现该问题。

**Comment by SimonaliaChen** [comment]
It will be fixed in v2.8.3 #15277
