### ISSUE TITLE
[Bug Report] Table header sort function should not apply on the whole header `TH`

### ISSUE THREAD

**Issue by JerryYuanJ** [ElemeFE/element#15313]
### Element UI version
2.8.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/BEbzRG?editors=1010

### Steps to reproduce
1. add a `sortable` attribute to `el-table-column` 
2. make the col header a scoped one and have another function inside the header
3. click the custom icon and will trigger the sort function which shouldn't be

I check the code and found that header does this: 
```
    handleHeaderClick(event, column) {
      if (!column.filters && column.sortable) {
        this.handleSortClick(event, column);
      } else if (column.filterable && !column.sortable) {
        this.handleFilterClick(event, column);
      }

      this.$parent.$emit('header-click', column, event);
    },
```
The first condition do this trick , if you want I can prepare a PR for it !

### What is Expected?
sort function should only be applied on sort icon instead of the whole `TH` tag

### What is actually happening?
user function will always trigger the sort function if there's one

**Comment by iamkun** [comment]
pr welcomed
