### ISSUE TITLE
After upgrading the Element-UI version 2.8.2, AMD loads the error report

### ISSUE THREAD

**Issue by balac2015** [ElemeFE/element#15318]
### Element UI version
2.8.2

### OS/Browsers version
Chrome/72.0.3626.121

### Vue version
2.1.8

### Reproduction Link
https://codepen.io/balac2015/pen/zXboob?editors=1011

### Steps to reproduce
Element-UI 升级 2.8.2 版本后，AMD 方式正常使用 el-form 组件报错：Uncaught TypeError: Cannot read property 'size' of undefined（可在 console 上面查看）

### What is Expected?
Element-UI v2.8.2版本能够兼容 AMD

### What is actually happening?
Element-UI 升级 2.8.2 版本后，AMD 方式使用 el-form, el-tabs 等组件报错。el-table 组件卡死浏览器

**Comment by powhd** [comment]
I had the same problem.  
version:2.7.2    
El-table component stuck browse

**Comment by island205** [comment]
@balac2015 @powhd upgrade vue to 2.2.0, it works fine https://codepen.io/island205/pen/EzVqxX?editors=1011
