### ISSUE TITLE
[Feature Request] el-table wants to add a tree-like switch and default child data in children and can customize other keys, and tree tables can set tree icons to display in which column

### ISSUE THREAD

**Issue by liuchihanxiang** [ElemeFE/element#15326]
### Existing Component
是

### Component Name
el-table

### Description
1、el-table 希望新增是否为树形的开关，现在是只要有children就默认展示位树形 
2、el-table 树形的子数据在默认在children里面  希望能自定义其他key ，
3、eltable 树形可以设置树形图标显示在第几列

**Comment by iamkun** [comment]
#15170
