### ISSUE TITLE
[Bug Report] el-dialog Title bug

### ISSUE THREAD

**Issue by miko-chen** [ElemeFE/element#15323]
### Element UI version
2.8.2

### OS/Browsers version
Windows 7 Service Pack 1 Build 7601/Google Chrome	73.0.3683.103 (正式版本) （32 位） (cohort: Stable)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mikoChen/pen/ZZPeYe

### Steps to reproduce
1.点击Button按钮
2.调整浏览器宽度，当浏览器宽度较小时（重现代码大致宽度为910以下），弹出el-dialog框的标题，部分文字会超出弹框。简单测试了下，数字会超出，汉字不会，字母没看。
3.第一步与第二步先进行哪个都一样

### What is Expected?
数字能换行

### What is actually happening?
汉字与数字不同行，数字在弹框大小调整后，数字会超出弹框而不会换行

**Comment by island205** [comment]
https://blog.csdn.net/liuyan19891230/article/details/50969393
