### ISSUE TITLE
[Feature Request] Grouping table head-multilevel table head nesting problem

### ISSUE THREAD

**Issue by zhenyuyyk** [ElemeFE/element#15320]
### Existing Component
是

### Component Name
Table-Grouping table head

### Description
现在的多级表头必须嵌套：
![image](https://user-images.githubusercontent.com/35624134/56861793-199b3d00-69d7-11e9-90f5-5c8c32141efa.png)

是否可以非嵌套，类似于这样：
----one----|----one----
----------two-----------
![image](https://user-images.githubusercontent.com/35624134/56861892-076dce80-69d8-11e9-98e6-808f55fb25de.png)

**Comment by iamkun** [comment]
pr welcomed
