### ISSUE TITLE
Does [Feature Request] dropdown consider new design approaches

### ISSUE THREAD

**Issue by DZG-MELODY** [ElemeFE/element#15328]
### Existing Component
是

### Component Name
dropdown

### Description
提出一点个人的意见。在vue升级到2.6之后，由于slot指令的变更，导致dropdown组件在实现上有些不太优雅。dropdown组件dom的相关初始化 initDomOperation方法 放在了dropdown-menu组件中进行。这就要求两个组件强依赖，但dropdown-menu又是以slot的方式进行配置，在vue的设计理念中，slot应该是用户自定义的位置，但目前情况，dropdown-menu必须作为slot才能正常使用，我认为这样会造成使用者的混淆。
我的个人观点：是否可以考虑dropdown-menu组件作为必须的子组件或者不使用slot方式。

**Comment by iamkun** [comment]
pr welcomed
