### ISSUE TITLE
[Feature Request] The value/v-model attribute bind the last level's value

### ISSUE THREAD

**Issue by codesinging** [ElemeFE/element#15327]
### Existing Component
是

### Component Name
Cascader

### Description
Sometimes we have the request that the cascader only bind the last level's value instead of the array of all levels's values, so whether the component can add an attribute to decide the binding value is the last level's value or the array of all levels's value.

**Comment by iamkun** [comment]
请提供一个使用场景，或者自己取一下数组最后一项

**Comment by codesinging** [comment]
编辑新闻表单中选择新闻栏目，需要的是category_id，而不是一个完整的数组，还有类似多级树中需要parent_id。

**Comment by iamkun** [comment]
自己取数组最后一项可以解决吗

**Comment by codesinging** [comment]
自己取当然可以解决，目前是自己又封装一层组件。但是这不是个很常用的需求吗？组件不就是为了更方便使用吗？

**Comment by iamkun** [comment]
感觉返回一个数组会更通用
