### ISSUE TITLE
[Feature Request] Expects calendar components to add click events and bind arrays bidirectionally.

### ISSUE THREAD

**Issue by zbr826858040** [ElemeFE/element#15337]
### Existing Component
是

### Component Name
Calendar calendar

### Description
进阶期望：期望贵团队能在日历的每一天上增加点击事件。能够返回当前日期以这样的“yyyy-MM-dd”格式。
最终期望：如果有可能的话，是否能够绑定一个数组，且点击事件能够返回点的那一天的其他属性。就像table的@current-change事件一样。
数组的格式大概是这样的。dateArr = [{date:"2019-01-01",isWorkDay:false},{date:"2019-01-02",isWorkDay:true},{date:"2019-01-03",isWorkDay:false}];
这样的话，点击事件返回的就是date和isWorkDay了。

**Comment by iamkun** [comment]
pr welcomed

**Comment by ffey** [comment]
这样就关闭啦？
