### ISSUE TITLE
[Bug Report] table filter-value is incorrect

### ISSUE THREAD

**Issue by babysbreath1994** [ElemeFE/element#15338]
### Element UI version
2.8.2

### OS/Browsers version
chrom

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
table filters多选时，
更改选中的值，不点击筛选或重置，点击空白处，filter-value未还原成上次选择的值 

### What is Expected?
在未重新筛选的情况下，关闭浮窗应还原为上次选择的值

### What is actually happening?
值不正确，表格数据与选择的项就对不上了

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
