### ISSUE TITLE
2.8.2版本运行时报错disabled属性报错

### ISSUE THREAD

**Issue by PursuitLife** [ElemeFE/element#15339]
element-ui.common.js?1063:2306 Uncaught TypeError: Cannot read property 'disabled' of null

**Comment by zhangzhenfei** [comment]
我也遇到了这个问题

**Comment by nongzhenli** [comment]
请问解决了嘛？我也遇到这个问题，特别是发现在弹出层应用场景，比如：select 下拉、dialog弹出等，就会发生这个错误！

**Comment by ldc-37** [comment]
在el-dropdown中碰到此问题，其原因可能是没有向dropdown插槽提供内容（文档似乎未说明这个是必须的），导致组件中没有下拉列表的vnode，_应该_影响不大。之所以这么做，是因为部分菜单项无需下拉。。。

**Comment by hardestHu** [comment]
> 请问解决了嘛？我也遇到这个问题，特别是发现在弹出层应用场景，比如：select 下拉、dialog弹出等，就会发生这个错误！
问题解决了吗
