### ISSUE TITLE
[select]更新1.0.4后select的option不能绑定object？

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#1533]
![image](https://cloud.githubusercontent.com/assets/12726826/20857098/266d9780-b95d-11e6-9f99-dbe5f4b61aa6.png)
![image](https://cloud.githubusercontent.com/assets/12726826/20857108/541a3b20-b95d-11e6-9728-54c78c5dfdde.png)
更新1.0.4后select的option不能绑定object？
我整个页面用到select的都报错了，这是怎么回事？

**Comment by Leopoldthecoder** [comment]
我试了一下是可以的：http://jsfiddle.net/Lq0qbjgo/ ，请提供能重现问题的 demo

**Comment by lry210** [comment]
![image](https://cloud.githubusercontent.com/assets/12726826/20857326/eb122a92-b962-11e6-9e03-1698702028ed.png)

@Leopoldthecoder 应该是给他一个初始值时不能是对象的错误，我之前都是这样给初始值都不会报错，1.0.3之前都不会

**Comment by Leopoldthecoder** [comment]
这种情况下，如果需要给初始值的话，可能需要这样写：http://jsfiddle.net/leopoldthecuber/Lq0qbjgo/1/ 。因为按照截图里的写法，`value` 和对应 option 的 `value` 属性其实引用的是两个不同的对象。

试了一下，在 1.0.3 及之前的版本里，按照截图里的写法，输入框里是空的，这也是不对的。

**Comment by lry210** [comment]
![image](https://cloud.githubusercontent.com/assets/12726826/20857673/4221d282-b96e-11e6-830d-65e9d8386a0f.png)
![image](https://cloud.githubusercontent.com/assets/12726826/20857677/5ab11308-b96e-11e6-9f0c-307d96c79029.png)
![image](https://cloud.githubusercontent.com/assets/12726826/20857678/6529e83c-b96e-11e6-8384-08038a07d591.png)
@Leopoldthecoder 发现不设置初始值也会，之前都是这样写的，有啥需要改进的请指教

**Comment by Leopoldthecoder** [comment]
提供一个能重现的 demo 吧

**Comment by lry210** [comment]
![image](https://cloud.githubusercontent.com/assets/12726826/20857992/18203026-b975-11e6-9ac4-0eac7b341d95.png)
我知道问题了，初始化不能是一个空的对象。。。

**Comment by Leopoldthecoder** [comment]
是的，还是按我上面那个 demo 的方法来处理，或者初始化为一个空字符串。我再想想我这边有没有更好的处理办法。

**Comment by lry210** [comment]
![image](https://cloud.githubusercontent.com/assets/12726826/20858169/86009bc2-b979-11e6-879a-293ff8fe8c10.png)

![image](https://cloud.githubusercontent.com/assets/12726826/20858167/800f795e-b979-11e6-8e20-793203fda185.png)
@Leopoldthecoder 之前这样设置初始值都是可以的，不会报错，现在我只能用你们的1.0.3.不升级了，要不整个项目改动好大

**Comment by yuanshengchao** [comment]
这个select在1.0.4版本里出现的bug太大了，1.0.3以前还是好的。

**Comment by Leopoldthecoder** [comment]
@yuanshengchao 请新开一个 issue 并提供 demo。

**Comment by Leopoldthecoder** [comment]
@lry210 可以先锁定 1.0.3，等下个版本。不过仍然不建议这样使用。

**Comment by Leopoldthecoder** [comment]
#1540 修复了初始值为对象时会报错的问题。
