### ISSUE TITLE
[Bug Report] 2.8.2 How to Solve the Problem of Disordered Intranet Deployment Styles

### ISSUE THREAD

**Issue by maokeng** [ElemeFE/element#15336]
### Element UI version
2.8.2

### OS/Browsers version
win10

### Vue version
2.5.17

### Reproduction Link
https://github.com/ElemeFE/element/blob/master/FAQ.md

### Steps to reproduce
2.8.2如何解决在内网部署样式错乱问题，下载项目直接在内网环境运行

### What is Expected?
可在内网运行项目，查看API

### What is actually happening?
可在内网运行项目，查看API

**Comment by iamkun** [comment]
clone 项目 打包即可
