### ISSUE TITLE
[Bug Report] Dialog disable 'close-on-press-escape' when 'modal' attr set as 'false'

### ISSUE THREAD

**Issue by Noctsyndrome** [ElemeFE/element#15342]
### Element UI version
2.8.2

### OS/Browsers version
Win7 / Chrome74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Noctsyndrome/pen/MRxRGv

### Steps to reproduce
1. click btn to call dialog
2. press 'esc'
3. click outside dialog

### What is Expected?
1. when press 'esc', show the close confirm
2. the pattern be consistently, when 'modal' set as 'true', 'close-on-click-modal' & 'close-on-press-escape' should be all working. Then as the 'modal' set as 'false', neither  'close-on-click-modal' & 'close-on-press-escape' should work

### What is actually happening?
1. key press invalid
2. 'close-on-click-modal' & 'close-on-press-escape' works well when 'modal' equals true, but 'close-on-press-escape' when 'modal' equals false

**Comment by iamkun** [comment]
pr welcomed

**Comment by iamkun** [comment]
Related code: src/utils/popup/index.js   L133
```
PopupManager.openModal
```

src/utils/popup/popup-manager.js L185
```
getTopPopup // undefined
```
