### ISSUE TITLE
没有prop属性的el-form-item，resetFields对其不起作用。

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1534]
element-ui version 1.0.4

  <el-form-item label="活动名称" prop="name">
    <el-input v-model="ruleForm.name"></el-input>
  </el-form-item>

没有prop属性的el-form字段，resetField对其不起作用，不会清空改项

而且如果form里的el-form-item prop重复，则resetFiled也失效。
如果form里的el-form-item有一个没有prop，则调用resetFiled，会报错误：
 
![2016-12-03 3 44 01](https://cloud.githubusercontent.com/assets/13174059/20857700/5deb1f7c-b96f-11e6-9b73-b2a7eeb381b2.png)

真实的情况下，不可能所有的输入都要validate的。

**Comment by Leopoldthecoder** [comment]
如果不需要校验，那么不在校验规则里写这个 prop 就可以，和 el-form-item 有没有这个 prop 无关。

`this.$refs.assignForm` 拿不到吗？

**Comment by njleonzhang** [comment]
@Leopoldthecoder Hi 第二个问题我自己搞错了el-dialog显示出来之后this.$refs.assignForm是可以拿到的。

第一个问题如果el-form-item 上不添加prop属性，resetField对其不起作用，不会清空这一项，这个问题是存在的。

**Comment by njleonzhang** [comment]
http://jsfiddle.net/api/post/library/pure/
在你们的官方例子里， 你删除任意el-form-item上得prop属性，则reset就无法清空此列的值。

**Comment by Leopoldthecoder** [comment]
每个 `el-form-item` 都需要一个唯一的 `prop`，这个设计是合理的。

我的意思是，为何不给 `el-form-item` 添加 `prop`？如果仅仅是因为不需要校验某个字段，那么不写校验规则就可以，`prop` 还是需要加上的。

**Comment by baiyaaaaa** [comment]
prop不是el-form-item的必要属性，然是如果需要使用form的resetfields或者validate功能，那就需要有prop属性

**Comment by njleonzhang** [comment]
@baiyaaaaa 是否可以去掉这个限制，有prop的话就resetfield或者对其进行validate，没有就不管？

```
el-form(:model='innerData' label-width="120px" ref="form")
      el-form-item(label='房间位置', prop="building_id")
        room-select(
          type="floor",
          :building-id="innerData.building_id",
          :unit-code="innerData.unit",
          @change="positionChange")
```

比如我有一个自定义组件在form里  它的值需要通过change更新。此时我可能不希望让这个组件绑定一个building_id属性，我希望在submit的时候自己管理这些值。

**Comment by gitWhatever** [comment]
同样遇到这个问题，希望能改善，有时候某些场景表单有非常多的字段，为了resetfield而为每个字段添加props，成本是不是过高了呢，起码resetfield这个方法不应该有这种限制吧。

**Comment by tbphp** [comment]
如果觉得每个字段添加prop过于麻烦，那么就这样处理：
```vue
this.$refs.form.resetfield()
Object.assign(this.form, this.$options.data().form)
```

**Comment by PhoenixMenia** [comment]
遇到了同样的问题，加了prop属性也还是不行

**Comment by feichangtutu** [comment]
遇到了类似的问题，prop对应的名字还必须与form表单对应的变量名字一直resetField才能有效

**Comment by Ale-cc** [comment]
除了上面的props之外，绑定的事件也要注意按照文档的来。
` <el-button @click="resetForm('ruleForm2')">重置</el-button>`
` resetForm(formName) {
        this.$refs[formName].resetFields();
      }`
然鹅，我写
`this.$refs.formName.resetFields()`就会出现某个属性清空不了。

**Comment by procedure-ape** [comment]
@Ale-cc 你这样写的话，不是把formName作为this.$refs的属性使用了么，应该是不行的吧

**Comment by wangwanchao** [comment]
> 如果觉得每个字段添加prop过于麻烦，那么就这样处理：
> 
> ```
> this.$refs.form.resetfield()
> Object.assign(this.form, this.$options.data().form)
> ```

Object.assign太给力了，这算是奇巧淫技了吧
