### ISSUE TITLE
[Bug Report] Closing dialog will flicker under IE browser

### ISSUE THREAD

**Issue by LoneGunnerMe** [ElemeFE/element#15349]
### Element UI version
2.8.2

### OS/Browsers version
IE 11

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/uuname/pen/bJJdvo

### Steps to reproduce
Under IE browser:

Click on the button to open the bullet window
Click "Cancel" or "Confirm" or "X" in the upper right corner.

### What is Expected?
Direct disappearance

### What is actually happening?
When the window disappears, it suddenly appears and then disappears completely.

**Comment by iamkun** [comment]
pr welcomed
