### ISSUE TITLE
Cross-column Width of [Feature Request] Table Cell

### ISSUE THREAD

**Issue by D-D-H** [ElemeFE/element#15358]
### Existing Component
是

### Component Name
el-table

### Description
现象:
一个cell占了两列, 如果第一列设置了 show-overflow-tooltip 同时设置了 宽度, 那么 这个cell 只能显示成一个 cell 的宽度
期望的现象:
一个cell的宽度为两列的宽度, 同时是show-overflow-tooltip的

**Comment by ziyoung** [comment]
补充个 demo http://jsrun.net/ABXKp/edit
