### ISSUE TITLE
[Bug Report] Dialog failed to display the el-image image

### ISSUE THREAD

**Issue by iTaster** [ElemeFE/element#15353]
### Element UI version
2.8.2

### OS/Browsers version
win 10 / chrome 版本 73.0.3683.103（正式版本）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
Dialog failed to display the el-image image

### What is Expected?
Imagescan be loaded

### What is actually happening?
 Images are not loaded

**Comment by SimonaliaChen** [comment]
Issues without a valid reproduction link will be closed directly.
