### ISSUE TITLE
[Feature Request] el-date-picker is longer than el-input, while el-autocomplete is shorter. Was it deliberately designed like this?

### ISSUE THREAD

**Issue by doukai** [ElemeFE/element#15357]
### Existing Component
是

### Component Name
el-date-picker,el-autocomplete

### Description
如题，发现el-date-picker比el-input要长一块，而el-autocomplete则短一些，是刻意这么设计的吗？有没有什么办法能统一同一个form下所有输入控件的长度吗？谢谢

**Comment by iamkun** [comment]
参考 form 的文档 width 都撑满即可
