### ISSUE TITLE
[Feature Request] modify tabs-item's padding cause active-bar's width and transform error

### ISSUE THREAD

**Issue by bibi941** [ElemeFE/element#15355]
### Existing Component
是

### Component Name
tabs

### Description
修改了 tabs 组件下的 tabs item 的 padding 默认为 0 20 (修改为0 15),导致了下方的 active bar(滑条)的位置的宽度计算出错,
查看了一下源码 barStyle有一个 ``` if (sizeName === 'width' && offset !== 0) { offset  += 20;} ``` ,是否有不修改源码,可以设置 padding的方法呢?

**Comment by iamkun** [comment]
pr welcomed

**Comment by liuyongly** [comment]
这个问题还存在呢
