### ISSUE TITLE
[Bug Report] The problem of multiple selection of selected components is in ie10

### ISSUE THREAD

**Issue by yanpengxiang** [ElemeFE/element#15369]
### Element UI version
2.8.2

### OS/Browsers version
ie10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yanpengxiang/pen/LvoGQd

### Steps to reproduce
selelct组件props的multiple为true时，在ie10上选择多个标签不会换行，好像是 packages/select/src/select.vue文件里面的resetInputHeight方法在ie10上的问题

### What is Expected?
在ie10上选择多个标签会换行

### What is actually happening?
在ie10上选择多个标签不会换行

**Comment by qingdengyue** [comment]
![image](https://user-images.githubusercontent.com/3230673/57189454-954e3a00-6f41-11e9-8992-31041c42aa24.png)

https://codepen.io 
IE10 and Edge DONT BE  SUPPORT.So repos doesnt work.

**Comment by iamkun** [comment]
IE 10 can't open codepen - -

**Comment by yanpengxiang** [comment]
> IE 10 can't open codepen - -

Actually, I have fixed this problem locally. 
On ie10，flex attributes cause span tags to fail to wrap
If don't support ie10, I think it's better to tag it in the document
