### ISSUE TITLE
[Feature Request] el-tree table clicks to expand or close a row to return to the status of the current row rowKey and row

### ISSUE THREAD

**Issue by zhixiaotong** [ElemeFE/element#15367]
### Existing Component
是

### Component Name
el-tree

### Description
一、懒加载时增加loading效果。个人也能实现，需要在load方法上加上loading，效果...
二、展开行和关闭行显示不同的icon图标，比如：展开显示文件夹打开的图标，而关闭显示文件夹默认的图标。图标可以通过自定义行内容处理，但无法获取table组件内部的状态，能否增加返回当前的expanded属性？查看过源代码是：store.states.treeData里有，但无法从外部监听。

**Comment by zhixiaotong** [comment]
If you support the expansion or shutdown state, setting different icons separately can solve the above problem.
如果支持展开或关闭状态单独设置不同的icon也能解决上述问题

**Comment by zhixiaotong** [comment]
@iamkun thanks a lot.

**Comment by luckyCao** [comment]
fixed in #15709
