### ISSUE TITLE
[Bug Report] <el-divider> </el-divider> report a error

### ISSUE THREAD

**Issue by NoFacePeace** [ElemeFE/element#15364]
### Element UI version
2.8.2

### OS/Browsers version
windows 10 / chrome 版本 73.0.3683.86（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/

### Steps to reproduce
add tag  <el-divider></el-divider

### What is Expected?
朗读
In line with expectations

### What is actually happening?
朗读
In line with expectations

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
