### ISSUE TITLE
<el-divider></el-divider> 报错

### ISSUE THREAD

**Issue by NoFacePeace** [ElemeFE/element#15363]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <el-divider> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by Lingqinyu** [comment]
我也遇到这个问题了

**Comment by ikitozen** [comment]
upgrading to "element-ui": "^2.8.2" fixed this for me

it also works on issue-tracker's jsfiddle which seems to be at 2.6.2
