### ISSUE TITLE
When [Bug Report] version 2.8.2 is updated, using el-tabs on pages can cause browsers to crash.

### ISSUE THREAD

**Issue by Remondcl** [ElemeFE/element#15366]
### Element UI version
0.1.0

### OS/Browsers version
win7/谷歌

### Vue version
2.5.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
页面使用el-tabs,打开页面

### What is Expected?
正常使用

### What is actually happening?
浏览器奔溃

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
