### ISSUE TITLE
1.0.4 select组件默认值不是不是label的值而是value的值

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1537]
目前的1.0.4版本出现的select v-model的默认显示的值竟然变成了label的值，而不是value的值，一脸的懵逼。
![image](https://cloud.githubusercontent.com/assets/16740731/20858216/d837a9ac-b97a-11e6-92d6-303f33c3e583.png)
![image](https://cloud.githubusercontent.com/assets/16740731/20858217/f5349326-b97a-11e6-8f0a-3a9a1199d77d.png)
代码中的label是绑定的中文，value绑定的是对应的id。最后显示的确实id而不是label

**Comment by Leopoldthecoder** [comment]
试了一下无法重现：http://jsfiddle.net/leopoldthecuber/Ldkg2ohy/

请给出能重现的 demo。

**Comment by yuanshengchao** [comment]
![image](https://cloud.githubusercontent.com/assets/16740731/20858280/79f0c22c-b97d-11e6-81f3-9bcb3f054375.png)
我这边的数据是通过ajax请求获取的。
![image](https://cloud.githubusercontent.com/assets/16740731/20858288/a31638da-b97d-11e6-84d6-a3a535b7c7b9.png)

**Comment by yuanshengchao** [comment]
我只要把版本降到1.0.3就ok。
![image](https://cloud.githubusercontent.com/assets/16740731/20858307/36afa0cc-b97e-11e6-8f1c-aa39ccbab027.png)

**Comment by yuanshengchao** [comment]
编译后就会正常
![image](https://cloud.githubusercontent.com/assets/16740731/20858338/afd5259e-b97e-11e6-873a-300491f4198b.png)

**Comment by yuanshengchao** [comment]
请问这是什么问题？1.0.3以前都是ok的，只有到了1.0.4就bug了

**Comment by Leopoldthecoder** [comment]
确认是 bug。暂时可以先锁定 1.0.3，下个版本修复。

如果确实需要使用 1.0.4，可以暂时把 `self.date_choose = value.DateRangeID;` 改成
```javascript
setTimeout(function() {
  self.date_choose = value.DateRangeID;
}, 0);
```

**Comment by yuanshengchao** [comment]
@Leopoldthecoder 直接把这个放在代码里面，啥都没有了呀？
![image](https://cloud.githubusercontent.com/assets/16740731/20859276/c8bb6710-b994-11e6-8666-bb0c6c6c19f7.png)
![image](https://cloud.githubusercontent.com/assets/16740731/20859287/2fa38624-b995-11e6-8a26-2114e21f2b02.png)

**Comment by Leopoldthecoder** [comment]
Fixed in #1540

**Comment by cesarzheng12** [comment]
2.4.11重现该问题
