### ISSUE TITLE
[Bug Report] Screen Flash When Using the V-Loading Directive

### ISSUE THREAD

**Issue by chriswoodley** [ElemeFE/element#15373]
### Element UI version
2.8.2

### OS/Browsers version
Chrome 73, Firefox 66, macOS High Sierra

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/chriswoodley/e9q7fkj3/26/

### Steps to reproduce
1. Add an element-ui button
2. Place the v-loading directive on the element-ui button component
3. Add a data property called isLoading and set the default to false
4. Add a dynamic disabled attribute to the button to disable the button when this.isLoading is true
5. Create an async method which returns a Promise that resolves in 3 seconds to simulate a fake api call
6. Create a click handler method that sets this.isLoading to true, calls the fake async method, then set this.isLoading back to false when it resolves.
7. Add the click event handler to the button
8. Click the button

### What is Expected?
The loading spinner should appear on the button element when isLoading is set to true. The button should also be disabled. When isLoading is set back to false...the loading spinner should disappear gracefully without screen flash.

### What is actually happening?
The loading spinner does not gracefully disappear. The screen flashes when the spinner disappears.

This only happens when the v-loading directive is placed on an element-ui component with dynamic attributes such as :disabled. This bug is not limited to only the element ui button. This happens on all element ui components using the v-loading directive with dynamic attributes.

**Comment by qingdengyue** [comment]
may be can use loading attribute for Button?

**Comment by iamkun** [comment]
> may be can use loading attribute for Button?

correcct

**Comment by chriswoodley** [comment]
Sorry for the late reply. using the loading attribute for the button element works fine. What are the use cases for the v-loading directive? What elements can/should that be used on?
