### ISSUE TITLE
[Feature Request] Take card header padding as a separate variable in vars

### ISSUE THREAD

**Issue by praveenpuglia** [ElemeFE/element#15375]
### Existing Component
Yes

### Component Name
Card

### Description
I was looking for a way to set the card header and body padding to `1rem` instead of the default px based values.
I was looking through the variables and found this
https://github.com/ElementUI/theme-chalk/blob/master/src/common/var.scss#L767

I checked through 
https://github.com/ElementUI/theme-chalk/blob/master/src/card.scss#L24
and realized that the same variable is used to calculate the padding for header.

Problem is that I can't pass in `rem` value because 1rem -2 would become an invalid value for padding. This is forcing me to use px value.

## Solution
We can create another variable called `$--card-header-padding` and set its value to whatever needs to be default. Example
```scss
$--card-header-padding: 18px 20px !default;
```
and use that variable directory instead of subtracting 2 from it. This way anyone can override the values if they wanted to in whichever unit they prefer.

**Comment by iamkun** [comment]
you could override through custom css.

**Comment by praveenpuglia** [comment]
If I had to do it in custom CSS, why would I come here and ask?

The point I was making is that introducing a variable would make it easy for user to customise for a consumer of element ui and in any CSS unit they want.

**Comment by iamkun** [comment]
We might add more design tokens later.
