### ISSUE TITLE
[Bug Report] $notify element appears under the dialog

### ISSUE THREAD

**Issue by johndcarmichael** [ElemeFE/element#15378]
### Element UI version
2.8.2

### OS/Browsers version
Linux/ Chrome latest

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/g26oqyct/1/   &&   https://jsfiddle.net/g26oqyct/2/

### Steps to reproduce
On link 1:
1 - load the page
2 - quickly press the link on screen to open the dialog before the notify closes

On link 2
1 - load the page
2 - press the link on screen to open the dialog before the notify closes

### What is Expected?
In both instances the notify should appear on top of the dialog.

### What is actually happening?
- In link 1, the notify is behind a dialog overlay.

- In link 2, the notify is again behind the dialog even though this time it is triggered from a child component of the dialog.

**Comment by iamkun** [comment]
the z-index is increased accordingly, pr welcomed
