### ISSUE TITLE
[Bug Report] max-height attribute on table prevents new rows from being added

### ISSUE THREAD

**Issue by nevetsmik** [ElemeFE/element#15371]
### Element UI version
2.8.2

### OS/Browsers version
Version 73.0.3683.103 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/nevetsmik/pen/yrWEoz

### Steps to reproduce
Click on 'Insert' button

### What is Expected?
New rows are added and existing rows remain in the table

### What is actually happening?
New rows are added but existing rows are no longer visible.

**Comment by asselinpaul** [comment]
Experiencing this too. Sticking to 2.7.2 for the time being.

**Comment by ziyoung** [comment]
![Kapture 2019-05-27 at 10 25 38](https://user-images.githubusercontent.com/12947422/58391836-ec8b8a00-8069-11e9-9081-3053fc627180.gif)
I can't reproduce. @nevetsmik

**Comment by nevetsmik** [comment]
Seems to have resolved itself. Will close this issue.

**Comment by asselinpaul** [comment]
The issue is not resolved.

If you change the element version to 2.7.2 in codepen, the correct behavior is exhibited (adding rows does not lead to scrolling being necessary).

**Comment by asselinpaul** [comment]
@ziyoung @nevetsmik so that it respects the `max-height` attribute of the table

**Comment by asselinpaul** [comment]
@nevetsmik can you please reopen — thank you

**Comment by nevetsmik** [comment]
Still has issues. See above from @asselinpaul

**Comment by ziyoung** [comment]
I make a pr to fix this issue.
