### ISSUE TITLE
[Bug Report] el-tree setCurrentKey(null) not work

### ISSUE THREAD

**Issue by JakeLaoyu** [ElemeFE/element#15370]
### Element UI version
2.8.2

### OS/Browsers version
macOS Mojave 10.14.4 / Chrome 74.0.3729.108

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/JakeLaoyu/8p1x6nfh/18/

### Steps to reproduce
https://jsfiddle.net/JakeLaoyu/8p1x6nfh/18/

### What is Expected?
Highlight should be unchecked

### What is actually happening?
Still highlighted

**Comment by JakeLaoyu** [comment]
I downgraded to 2.7.2 to solve

**Comment by OuZuYu** [comment]
me too

**Comment by OuZuYu** [comment]
我也遇到这个问题了，有时有效有时无效！！
