### ISSUE TITLE
[Feature Request] Setting month datepicker starts on

### ISSUE THREAD

**Issue by steveshore** [ElemeFE/element#15380]
### Existing Component
Yes

### Component Name
Datepicker

### Description
Is there a way to get the datepicker to always start on the current date instead of showing the last selected?

I am setting a dynamic mindate and maxdate.

I got it to work, but if the user starts on a month with disabled days that have changed they do not update until the user clicks to a different month and then back.

My issue would be resolved if they just always started on the current month.

Here is my code:
https://codepen.io/anon/pen/rbXjLr

**Comment by wacky6** [comment]
try `default-value`

**Comment by steveshore** [comment]
is this an attirbute?

**Comment by steveshore** [comment]
Thank you for your response, but the `default-value` attribute starts the initial load on a particular date, but if the user selects a different month, subsequent clicks will start on the new month.

I want it to always revert back to the month with the current date.

**Comment by steveshore** [comment]
Is there a way to force the datepicker to refresh?

**Comment by wacky6** [comment]
No in public API. The design is to show user selection (when user has picked a date).

You can modify date panel's internal state (`.picker.date`) when date-picker opens (in `focus` event after a `$nextTick`).

But be warned, we may change internal state implementation, be careful when upgrading between element versions.

**Comment by steveshore** [comment]
I really appreciate your response.

I have put a break point inside a $nextTick inside the focus function, but don't see how to access this. Can you elaborate on how to implement this?

**Comment by wacky6** [comment]
https://jsfiddle.net/byja4rsn/

**Comment by steveshore** [comment]
Thank you!!!
