### ISSUE TITLE
[Bug Report] el-image not use lazy in el-carousel

### ISSUE THREAD

**Issue by violetice** [ElemeFE/element#15381]
### Element UI version
2.8.2

### OS/Browsers version
deepin 15.10 / chrome  73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/arozgB

### Steps to reproduce
el-image in el-carousel use

### What is Expected?
el-image use lazy in el-carousel

### What is actually happening?
el-image not use lazy in el-carousel

**Comment by SimonaliaChen** [comment]
I think It's not an appropriate scenario to use lazy load image.
Lazy load image requires a container whose overflow is auto or scroll and listening scroll event to realize lazy load, but el-carousel has no such property.
Lazy load is more useful in an infinite scroll list.
