### ISSUE TITLE
[Bug Report] Dropdown accessibility - links not clickable via enter

### ISSUE THREAD

**Issue by gogy27** [ElemeFE/element#15386]
### Element UI version
2.8.2

### OS/Browsers version
any

### Vue version
2.6.7

### Reproduction Link
https://jsfiddle.net/39ac8jvo/

### Steps to reproduce
Create `a` tag within `<el-dropdown-item>`

### What is Expected?
Link should be reachable via keyboard. When you hit enter you should be redirected.

### What is actually happening?
Links work only when you click on them with a mouse. When you use keyboard for navigation within dropdown menu and you hit enter dropdown menu just closes itself and nothing happens - no redirection.

**Comment by iamkun** [comment]
pr welcomed
