### ISSUE TITLE
在menu中使用badge出现样式错误

### ISSUE THREAD

**Issue by wanghaolu** [ElemeFE/element#1539]
### ElementUI version

1.0.3
### OS/Browers version

Chrome 55
### Vue version

2.1.3
### What is actually happening?
badge离文字太远了，希望能改进
![default](https://cloud.githubusercontent.com/assets/9586655/20858951/bc41dd24-b98b-11e6-941b-7fa715287983.PNG)

**Comment by baiyaaaaa** [comment]
你是怎么使用的？看下代码
