### ISSUE TITLE
2.8.2版本：el-tab-pane组件内部使用slot时，会造成页面卡死的状态，代码如下

### ISSUE THREAD

**Issue by Mr-Virgo** [ElemeFE/element#15390]
<el-tabs type="border-card" v-model="activeName" @tab-click="handleTabClick">
      <el-tab-pane label="项目审核" name="1">
        <el-badge slot="label" :value="count.projectCount" class="item">
          &nbsp;&nbsp;项目审核&nbsp;&nbsp;
        </el-badge>
      </el-tab-pane>
</el-tabs>

**Comment by SageSanyue** [comment]
https://github.com/ElemeFE/element/issues/15712
you can look this for help
用出现浏览器阻塞问题是因为项目vue版本过低elment版本过高，降级即可解决问题。
