### ISSUE TITLE
[Feature Request] Table table loading data process add loading status animation

### ISSUE THREAD

**Issue by Simingchen** [ElemeFE/element#15396]
### Existing Component
是

### Component Name
table表格

### Description
问题点：请求数据的时候，加载数据时，table直接显示无数据状态，请求数据的过程应该是个加载的一个动画状态在表格内容区，完成数据请求才显示无数据或者数据内容

**Comment by liuchuzhang** [comment]
![image](https://user-images.githubusercontent.com/37723064/57203957-ce8cb580-6fe6-11e9-9ca4-7635012bde84.png)

**Comment by iamkun** [comment]
请参考楼上回答

**Comment by Simingchen** [comment]
Thank U!
