### ISSUE TITLE
How to properly introduce [Feature Request] branching code into your own project

### ISSUE THREAD

**Issue by jumplee** [ElemeFE/element#15406]
### Existing Component
否

### Component Name
全部

### Description
从原项目fork后在本地修改了一下自己的需求，想引入到自己的项目中，发现.gitignore中忽略了lib
用npm install https://github.com/jumplee/element.git 发现lib 并不存在，代码保存

**Comment by SimonaliaChen** [comment]
执行下打包命令就行~
