### ISSUE TITLE
[Bug Report] el-tabs 页面一直阻塞问题

### ISSUE THREAD

**Issue by KimFu2** [ElemeFE/element#15409]
2.8.2版本会出现el-tabs使用出现阻塞。这是我的代码：
`  <el-tabs  value="file">
			    <el-tab-pane label="最新文件" name="file">
			     	<div  v-for="item in files" >
			     		<el-col :span="18">
			    	 			<a @click="dowloadFile($event,item.path)" type="text">{{item.name}}</a>
		    	 			</el-col>
		    	 			<el-col :span="6">
		    	 				{{item.updateTime}}
		    	 			</el-col>
			     	</div>
			    </el-tab-pane>
			    <el-tab-pane label="最新资讯" name="news">
			    		<div  v-for="item in news" >
			     		<el-col :span="18">
			    	 			<a @click="openNews($event,item.href)" type="text">{{item.title}}</a>
		    	 			</el-col>
		    	 			<el-col :span="6">
		    	 				{{item.updateTime}}
		    	 			</el-col>
			     	</div>
			    </el-tab-pane>
			  </el-tabs>`

**Comment by SageSanyue** [comment]
https://github.com/ElemeFE/element/issues/15712
you can look this for help
用<el-tabs>出现浏览器阻塞问题是因为项目vue版本过低elment版本过高，降级即可解决问题。
