### ISSUE TITLE
The filter in the [Feature Request] Table component provides the same way as sort for remote filtering

### ISSUE THREAD

**Issue by winter-ice** [ElemeFE/element#15407]
### Existing Component
是

### Component Name
table

### Description
可使用自定义过滤方式，在表格的filter-change事件返回跟sort-change相同的参数，用于自定义远程过滤，
当前filter提供的filter-method会多次执行，并不适用于远程过滤

**Comment by Lynn-cc** [comment]
I have a similar feature request: I want the filter list could get remote list and show loading to wait, same as the select component.
