### ISSUE TITLE
[Bug Report] MessageBox.alert can be confirmed to close by the enter when mouse hasn't clicked page

### ISSUE THREAD

**Issue by lvjiaxuan** [ElemeFE/element#15401]
### Element UI version
2.8.2

### OS/Browsers version
win 10 / chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lvjiaxuan/pen/OYJNYe

### Steps to reproduce
e:

step 1: open the MessageBox.alert and **do not use the mouse to click after MessageBox opened**.

step 2: click on the enter and MessageBox closes.

step 3: open MessageBox again.

step 4: click anywhere and then can not close the MessageBox by the enter.

c:

步骤 1: 打开MessageBox.alert并且不要产生鼠标点击

步骤 2: 点击回车MessageBox关闭

步骤 3: 重新打开MessageBox.alert

步骤 4: 点击页面任何地方，然后点击回车MessageBox不能关闭

### What is Expected?
e:

The messagebox show same behavior whether the mouse clicks or not.

c:

希望回车行为在产生鼠标点击前后一致

### What is actually happening?
e:

The messagebox's behavior is inconsistent.

c:

回车行为在产生鼠标点击前后不一致

**Comment by LarsKerff** [comment]
I think this behavior works as expected. By default the focus is on the button. As soon as you click your mouse anywhere in the screen, the focus is not on the button anymore.

**Comment by iamkun** [comment]
> I think this behavior works as expected. By default the focus is on the button. As soon as you click your mouse anywhere in the screen, the focus is not on the button anymore.

Correct

**Comment by shenyajun001** [comment]
messageBox弹窗出现后默认聚焦在按钮上，按钮上绑定了keydown.enter事件，所以会出现描述的情况
