### ISSUE TITLE
[Bug Report] No Network Environment Deployment Projects, Style Disorder Problem

### ISSUE THREAD

**Issue by maokeng** [ElemeFE/element#15403]
### Element UI version
2.8.2

### OS/Browsers version
windows10

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/new

### Steps to reproduce
在有网络的设备下载运行element项目,下载依赖之后压缩。导入无网络环境，运行项目，样式丢失，错乱。

### What is Expected?
可在无网络环境运行element 以便查看对应API

### What is actually happening?
可在无网络环境运行element 以便查看对应API

**Comment by iamkun** [comment]
仓库下载 自己打包即可

**Comment by maokeng** [comment]
> 仓库下载 自己打包即可

打包之后全是JS文件怎么部署？

**Comment by maokeng** [comment]
运行是可以运行的，但是样式是错乱的，应用文件是在外网上的，但我是内网办公，请求不到样式文件

**Comment by iamkun** [comment]
麻烦自己改一下源码吧

**Comment by maokeng** [comment]
> 麻烦自己改一下源码吧

很明显能力不到，不然就不会跑这里来提问了
