### ISSUE TITLE
[Bug Report] el-input 当type="textarea"时，无法设置textarea的文字行高line-height

### ISSUE THREAD

**Issue by ferying** [ElemeFE/element#15405]
### Element UI version
2.8.2

### OS/Browsers version
73.0.3683.75（正式版本） （32 位）

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US

### Steps to reproduce
nothing

### What is Expected?
nothing

### What is actually happening?
nothing

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
