### ISSUE TITLE
[Bug Report] ElTooltip tabIndex has no effect

### ISSUE THREAD

**Issue by mamying** [ElemeFE/element#15413]
### Element UI version
0.1.0

### OS/Browsers version
谷歌

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mamying/pen/byGzZP

### Steps to reproduce
该问题我已经在codepen中实现，可以看到 按钮上的tabindex为0，而不是我设置的-1
```js
this.$el.setAttribute('tabindex', 0);
```
改为
```js
this.$el.setAttribute('tabindex', this. tabindex);
```

### What is Expected?
设置tabindex为-1

### What is actually happening?
实际上tabindex还是为0

**Comment by zhaofy** [comment]
同样遇到这个问题，希望尽快处理，谢谢！

**Comment by SimonaliaChen** [comment]
嗯，确实是这个问题~ 麻烦能提个PR嘛
