### ISSUE TITLE
[Bug Report] el-input element in el-form，when set maxlength and show-word-limit,the input element will has blank at the limit info top and bottom

### ISSUE THREAD

**Issue by xiaofengleiyu** [ElemeFE/element#15418]
### Element UI version
2.8.2

### OS/Browsers version
win10 / chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xiaofengleiyu/pen/XwJrMb

### Steps to reproduce
set  maxlength and show-word-limit to the el-input in el-form

### What is Expected?
has no blank at the limit info top and bottom

### What is actually happening?
has blank at the limit info top and bottom

**Comment by iamkun** [comment]
#15359
