### ISSUE TITLE
table 高度不能等于100%

### ISSUE THREAD

**Issue by hellinnocence** [ElemeFE/element#1541]
<el-table :data="data" stripe border height="100%">
    <el-table-column property="date" label="日期" width="180"></el-table-column>
    <el-table-column property="name" label="姓名" width="180"></el-table-column>
    <el-table-column property="address" label="地址"></el-table-column>
</el-table>

**Comment by furybean** [comment]
你可以使用 CSS 控制 Table 的高度，height 属性设置为 auto 就可以。
