### ISSUE TITLE
[Bug Report] command/ctrl   left click nav-menu-item to open a new tab will change the active index of menu

### ISSUE THREAD

**Issue by xijiezhong** [ElemeFE/element#15410]
### Element UI version
2.8.2

### OS/Browsers version
macOS high Sierra 10.13.4/google chrome 73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
https://panjiachen.github.io/vue-element-admin

### Steps to reproduce
command or ctrl   left click nav menu item

### What is Expected?
it should open a new tab and it should not change the old active index nav menu item

### What is actually happening?
it opens a new tab and it changes the old active index nav menu item

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
