### ISSUE TITLE
How does the [Feature Request] select selector automatically empty the part it has entered when it remotely searches for more than one item?

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [ElemeFE/element#15429]
### Existing Component
是

### Component Name
select 选择器

### Description
select 选择器 远程搜索多个时如何自动清空自己已输入的部分

**Comment by SamGenTLEManKaka** [comment]
![image](https://user-images.githubusercontent.com/24671601/57276162-4fc17680-70d3-11e9-9296-f2d56c0935b2.png)
如图我在选择多个时，自己输入的“gl”仍然停留在输入框内，如何自动清除他们？

**Comment by iamkun** [comment]
失焦 或者 按退格键，设计如此
