### ISSUE TITLE
[improvement] offer a better select defaults usage

### ISSUE THREAD

**Issue by dsonet** [ElemeFE/element#1542]
### ElementUI version
1.0.4

### What is Expected?
```
<el-select v-model="value" placeholder="请选择" :options="options"></el-select>
```
We can use select this way as default.
### What is actually happening?
Now we have to repeat the below everywhere:

```
<el-select v-model="value" placeholder="请选择">
   <el-option
       v-for="item in options"
      :label="item.label"
      :value="item.value">
    </el-option>
</el-select>
```

**Comment by Leopoldthecoder** [comment]
I'm afraid what you suggest is less flexible, e.g. it'll be difficult to assign if a specific option is `disabled`, and to apply custom templates for options, you'll probably have to write render functions, which is not as intuitive as writing templates directly.

We'll keep it this way.

**Comment by dsonet** [comment]
I don't mean to replace the current way.

Just add to default slot.

What I mean is use
```
<el-select v-model="value" placeholder="请选择" :options="options"></el-select>
```
just for short as 
```
<el-select v-model="value" placeholder="请选择">
   <el-option
       v-for="item in options"
      :label="item.label"
      :value="item.value">
    </el-option>
</el-select>
```
