### ISSUE TITLE
When [Bug Report] el-table-column uses both V-IF and filter features, when V-IF is set to false, the filter feature does not disappear but goes to the next el-table-column.

### ISSUE THREAD

**Issue by awefeng** [ElemeFE/element#15427]
### Element UI version
2.8.2

### OS/Browsers version
windows 10 / chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/esk3x9b2/3/

### Steps to reproduce
1. 初始化时，机房没有使用filters，集群名称列没有使用filters，集群名称列此时未渲染
2. 由线路管理切换为集群管理的时候，集群名称渲染，却有了一个filters特性(列名后面有filters箭头)
3. 切回线路管理的时候，机房列也有了filters特性
大致原因：原有filters特性的列 "线路"被设置v-if=false后，filters没有跟着消失，而是附着在了后面占据该位置的列上

### What is Expected?
没有使用filters特性的el-table-column，不管渲染或者隐藏，都应保持代码声明的特性行为

### What is actually happening?
没有使用fliters特性的列在v-if切换后有了filters特性，而代码中未声明

**Comment by SimonaliaChen** [comment]
给[el-table-column加个key](https://jsfiddle.net/d6Lpe1sc/)试试~  el-table 在条件渲染的时候diff会有点问题

**Comment by awefeng** [comment]
thank you，我只知道vue在两个节点相同的时候才会复用，为啥这里也有这种问题，请问你说的条件渲染的时候diff会有点问题，是什么问题~

**Comment by guanjunliu** [comment]
遇到了同样的问题，用楼上的方法加上:key="1"解决。但是这个不是个bug么？
