### ISSUE TITLE
[Bug Report] When the "el-input" tag is nested under the "el-form-item" tag, the "show word limit" attribute of "el input" is not displayed correctly.

### ISSUE THREAD

**Issue by lshz0088** [ElemeFE/element#15421]
### Element UI version
2.8.2

### OS/Browsers version
win10/360极速浏览器11.0.2031.0

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lshz0088/pen/qGEMOg

### Element UI version
2.8.2

### OS/Browsers version
win10/360极速浏览器11.0.2031.0

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lshz0088/pen/qGEMOg

### Steps to reproduce
> #### In English:

>> As you can see directly, the container of the character prompt overflows the container where the input is located, causing the upper and lower borders of the input box to be blocked.  
In addition, I provided a button to adjust the size of the input box. You can see that no matter what size, there is a problem.  
In fact, there is a similar problem in textarea, the prompt statement is slightly up.  
I debugged it myself and found that it was due to the inheritance of the "line-height: 40px" attribute of "el-form-item__content" nested under the "el-form-item" tag.  

> #### 中文（In Chinese）：  

>> 直接可以看到，"字符提示"的容器溢出了"input"所在的容器，导致了输入框的上下边框被遮挡。  
另外我提供了调节输入框尺寸的按钮，可以看到无论哪种尺寸均有该问题。  
其实，在textarea中也有类似的问题，提示语句有点略微的上浮。  
我自己调试了下，发现应该是，由于嵌套在"el-form-item"标签下,继承了"el-form-item__content"的"line-height:40px"的属性导致的。

### What is Expected?
>#### In English:

>> Number of words indicated normal

>#### 中文（In Chinese）：

>> 字数提示显示正常

### What is actually happening?
>#### In English:

>> Abnormal display of word number prompt

>#### 中文（In Chinese）：

>> 字数提示显示不正常

### What is Expected?
>#### In English:

>> Number of words indicated normal

>#### 中文（In Chinese）：

>> 字数提示显示正常

### What is actually happening?
>#### In English:

>> Abnormal display of word number prompt

>#### 中文（In Chinese）：

>> 字数提示显示不正常

**Comment by iamkun** [comment]
#15359
