### ISSUE TITLE
[Bug Report] After setting the select component of filterable, default-first-option and multiple-selection, when the matching option is Chinese, the first item cannot be automatically selected.

### ISSUE THREAD

**Issue by xxrt** [ElemeFE/element#15431]
### Element UI version
2.8.2

### OS/Browsers version
windows10 chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/gJbVrp?&editable=true

### Steps to reproduce
输入英文过滤，可以自动选中；
输入中文过滤，无法自动选中；

### What is Expected?
输入中文过滤后，自动选中第一个匹配的选项

### What is actually happening?
输入中文过滤后，无法选中第一个匹配的选项

**Comment by ljjeseller** [comment]
i found this problem also.
