### ISSUE TITLE
[Bug Report] table height not changed when the max-height attribute dynamic change

### ISSUE THREAD

**Issue by zaoyu63** [ElemeFE/element#15436]
### Element UI version
2.8.2

### OS/Browsers version
macos 10.14.4 /Google Chrome 74.0.3729.131（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/KLpKYN?&editable=true#anon-signup

### Steps to reproduce
three button, in order to change maxHeight value.
click button, maxHeight value is changed, but the table height not change
element ui 2.6.3 version is normal

### What is Expected?
chlck button，maxHeight value is changed, the table height will change

### What is actually happening?
chlck button，maxHeight value is changed, but the table height will change

**Comment by EamonZhong** [comment]
遇到了同样的问题

**Comment by guanjunliu** [comment]
Meeting the same problem

**Comment by zzjzz9266a** [comment]
use `style="max-height: 450px;"` instead of `max-height="450"` in el-table tag could solve the problem
