### ISSUE TITLE
[Bug Report] el-link cannot be used and recognized correctly

### ISSUE THREAD

**Issue by Shj451148969** [ElemeFE/element#15432]
### Element UI version
2.8.2

### OS/Browsers version
chrome 73.0.3683.103

### Steps to reproduce
<div>
              <el-link href="https://element.eleme.io" target="_blank">默认链接</el-link>
              <el-link type="primary">主要链接</el-link>
              <el-link type="success">成功链接</el-link>
              <el-link type="warning">警告链接</el-link>
              <el-link type="danger">危险链接</el-link>
              <el-link type="info">信息链接</el-link>
            </div>

### What is Expected?
正常识别

### What is actually happening?
无法被解析成a标签，直接显示el-link

**Comment by qingdengyue** [comment]
reproduce?

**Comment by JeremyWuuuuu** [comment]
This might be caused by not registering `el-link` to current scope, so the current container cannot render `el-link` component, try to register component first. 
refer: https://vuejs.org/v2/guide/components-registration.html#ad

**Comment by mogocat** [comment]
直接粘贴示例代码就没法用

**Comment by pjhartin** [comment]
I've just checked this also and it seems `ElLink` cannot be imported as a single component in the "On demand" scenario. It works when using Full Import setup, but not in "On Demand" there is no way to register the component.

**Comment by zyyettie** [comment]
I've encountered such issue as well.
https://element.eleme.cn/#/zh-CN/component/quickstart
On this page of user guide, I don't see any component mentioned for "link".
Is there any missing or just work like this?
