### ISSUE TITLE
switch bug 当设置active-value="1" inactive-value="0"后

### ISSUE THREAD

**Issue by lafaccia** [ElemeFE/element#15448]
<el-switch width="30" active-value="1" inactive-value="0" v-model="scope.row.status" @change="switchStatus(scope.row.id,scope.row.status)" ></el-switch>
不能正确初始化，而且发现watch中status被switch改变值为0，换成true和false则无问题出现。

**Comment by bluesky628** [comment]
：active-value="1" ：inactive-value="0"
