### ISSUE TITLE
A bug in [Bug Report] el-tabs that gets stuck as soon as you use a browser

### ISSUE THREAD

**Issue by zealpane** [ElemeFE/element#15446]
### Element UI version
2.8.2

### OS/Browsers version
chrome，及其它各种主流浏览器

### Vue version
2.5.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/15316

### Steps to reproduce
<el-tabs v-model="activeName">
          <el-tab-pane label="登录" name="login">
            <user-login/>
          </el-tab-pane>
        </el-tabs>

### What is Expected?
使用方式，其中
            <user-login/>
是一个组件，单独使用没问题，如下放置就浏览器卡死。

<el-tabs v-model="activeName">
          <el-tab-pane label="登录" name="login">
            <user-login/>
          </el-tab-pane>
        </el-tabs>

上面的写法在之前的2.4.11版本中好好的，可是突然就不行了，后来排查了几个小时才发现是这个造成的。使用它和不适用它差距巨大

### What is actually happening?
浏览器因为el-tabs的引用卡死

**Comment by JasonBai007** [comment]
是的，我擦，折腾了我一个多小时，终于定位到这个组件，一旦使用tab组件，浏览器就崩，而且关不掉，CPU使用率大幅攀升，电脑风扇飞速旋转。。。。

**Comment by weer0026** [comment]
我也出现了同样的问题，升级vue版本到2.5.22后解决了，估计是vue的某些bug导致。

**Comment by HiZhaoxiaoyang** [comment]
2.0升级2.9.1报此问题。
