### ISSUE TITLE
[Bug Report] Directive can't get value of element when value is setted with Axios (Promise)

### ISSUE THREAD

**Issue by Denuro** [ElemeFE/element#15443]
### Element UI version
2.8.2

### OS/Browsers version
Linux Mint / Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Denuro/4wxv80fg/11/

### Steps to reproduce
No steps are necessary, error occurs on create, and the problem is outputted to console.

First input (el-input) v-model variable is beeing setted in axios request, and has the problem.
Second input (el-input) v-model variable is beeing setted outside of axios request, during create, and there's no problem.
Third input (html input) v-model variable is beeing seeted in axios request, and there's no problem.

### What is Expected?
When axios request sets the el-input v-model variable, the directive should be able to get the data in the value attribute of the el-input element, just like the input element.

### What is actually happening?
When axios request set the v-model variable, the el-input value element is empty on creation.

**Comment by qingdengyue** [comment]
first,recommand that you can use directie options to  create a  directive. because the lifecycle of directive,you can see [CustomDirective](https://vuejs.org/v2/guide/custom-directive.html),especially **update** and **componentUpdated**. in your reproduction,use **componentUpdated**.after that wrapper all business functions to Vue.nextTick. You will get correct value.

example:
```
Vue.directive('test',{
  componentUpdated(el.binding,vnode,oldVnode){
    Vue.nextTick(()=>{
         // your code
    })
  }
})
```

**Comment by Denuro** [comment]
I was using the [Function Shorthand](https://vuejs.org/v2/guide/custom-directive.html#Function-Shorthand) method of creating a directive just for testing purpose, as it's faster, and to test if the same problem occurs with update (witch it doesn't).

That beeing said, using the Vue.nextTick function to get the value of the input worked!
I did not know about that helper beforehand, so, thank you @qingdengyue, that solved it!
