### ISSUE TITLE
[Bug Report] el-table 使用slot="header"时不添加slot-scope="scope"数据就无法显示

### ISSUE THREAD

**Issue by Denny-coder** [ElemeFE/element#15453]
### Element UI version
2.8.2

### OS/Browsers version
win10/谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/denny-coder/pen/XwbvYB?editors=1010

### Steps to reproduce
添加slot-scope="scope"数据就能显示，不添加slot-scope="scope"数据就无法显示

### What is Expected?
不添加slot-scope="scope"数据也能正常显示

### What is actually happening?
不添加slot-scope="scope"数据就无法显示

**Comment by ziyoung** [comment]
注意 slot 与 scoped-slot 的区别。

**Comment by Denny-coder** [comment]
@ziyoung slot是说明插到哪个位置，scoped-slot是作用域插槽抛出的值，我理解是这样的
https://codepen.io/denny-coder/pen/rNBGvOW?editors=1000

**Comment by AILINGANGEL** [comment]
所以为什么要加slot-scope呢？我不使用组件内部传递出来的值，我就不写slot-scope呀

**Comment by yubaoquan** [comment]
> 所以为什么要加slot-scope呢？我不使用组件内部传递出来的值，我就不写slot-scope呀

@AILINGANGEL 
我也遇到了同样的问题, 不写`slot-scope="scope"`的话, 整个header的slot都渲染不出来. 更奇怪的是, 两个项目都用的同样版本的element-ui 2.12.0, 一个有这个bug, 另一个没有. 怀疑是不是其他依赖不同, 某个依赖里的bug导致的这个问题

代码大概这样

```
<el-table-column
  v-for="(column, index) in columns"
  :key="index"
  :formatter="column.formatter"
  :label="column.label"
  :width="column.width"
>
  <template slot="header">
    <div :class="column.required && 'required'">{{column.label}}</div>
  </template>

  <template slot-scope="scope">
    xxxxx
  </template>
</el-table-column>
```

**Comment by fireswork** [comment]
+ 1 🙋
