### ISSUE TITLE
[Feature Request] add stroke-linecap for progress path

### ISSUE THREAD

**Issue by hanzhangyu** [ElemeFE/element#15467]
### Existing Component
Yes

### Component Name
progress

### Description
It draws the pie chart easily by expose the stroke-linecap props

![WX20190508-195410](https://user-images.githubusercontent.com/19344269/57374336-3e5c9500-71cd-11e9-9665-9fd5f568d8dc.png)
```vue
 <CircleProgress
            type="circle"
            :show-text="false"
            :width="100"
            linecap="butt"
            :stroke-width="50"
            :percentage="30"
            status="success"
    />
```

**Comment by island205** [comment]
Sorry, we have no plan to support this.
