### ISSUE TITLE
[Bug Report] Table's Inverse Sorting Problem Using Tree Data

### ISSUE THREAD

**Issue by czy** [ElemeFE/element#15463]
### Element UI version
2.8.2

### OS/Browsers version
macOS 10.14.4/Chrome 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/KLdMPY

### Steps to reproduce
1. 点击“日期”或“姓名”倒序下三角
2. 点击表格第1, 2, 3行右箭头

### What is Expected?
子节点数据应当在父节点下方展示

### What is actually happening?
第1, 2, 3行的子节点数据出现在父节点上方，而第4行正常展示。

**Comment by ziyoung** [comment]
fixed in 2.9.1
