### ISSUE TITLE
[Bug Report] form property is not valid

### ISSUE THREAD

**Issue by BrightStarrySky** [ElemeFE/element#15478]
### Element UI version
2.8.2

### OS/Browsers version
mac /chrome 版本 74.0.3729.131（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wzs/pen/qGOeVy?&editable=true

### Steps to reproduce
设置属性但是无效果

### What is Expected?
属性能够正常生效

### What is actually happening?
添加属性没有任何反应

**Comment by qingdengyue** [comment]
啥意思？没看明白。
