### ISSUE TITLE
[Bug Report] [el-table] tree sort children lost 

### ISSUE THREAD

**Issue by AirttaryuZCF** [ElemeFE/element#15476]
### Element UI version
2.8.2

### OS/Browsers version
Windows / Chrome 74

### Vue version
2.5.10

### Reproduction Link
https://codepen.io/airttaryuzcf/full/xNwvwP

### Steps to reproduce
1. open node 2,3,4,5,6,7
2. sort by id
3. children in top or bottom  

### What is Expected?
children follow with parent 

### What is actually happening?
children not follow

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
