### ISSUE TITLE
[Bug Report] [el-image] image don't show while add css style { overflow-y: auto }

### ISSUE THREAD

**Issue by AirttaryuZCF** [ElemeFE/element#15477]
### Element UI version
2.8.2

### OS/Browsers version
Windows / Chrome 74

### Vue version
2.5.10

### Reproduction Link
https://codepen.io/airttaryuzcf/full/WBrebj

### Steps to reproduce
1. open the page 
2. cancel the explanatory note of overflow
3. save
4. open page again
5. image disappear

### What is Expected?
image show with lazyload

### What is actually happening?
image disapper

**Comment by SimonaliaChen** [comment]
It's not bug, the lazyload feature requires a scrollable container.

**Comment by 9yues** [comment]
那么如何使用全局 doucment的滚动来触发懒加载
