### ISSUE TITLE
[Bug Report] Multi-level header fixed column, fixed width is incorrect, corresponding cell content disappears

### ISSUE THREAD

**Issue by hgl** [ElemeFE/element#15480]
### Element UI version
2.8.2

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/YbwyRa?&editable=true

### Steps to reproduce
打开重现链接

### What is Expected?
所有单元格有内容显示
横向滚动表格，配送信息整列固定

### What is actually happening?
多级表头对应的单元格内容缺失
横向滚动表格，固定的宽度不正确

**Comment by shaqueoneal** [comment]
any way to work around?

**Comment by Yin-Xie** [comment]
the same to you

**Comment by Lyd1223** [comment]
the same to you

**Comment by SukiYuSijing** [comment]
传说将第一级表头设定固定宽度，以及二级表头也设置固定宽度（二级表头的宽度和等于上一级表头的宽度）可以解决这个问题
