### ISSUE TITLE
[Bug Report] Select Component popup animation exception in Chrome 74

### ISSUE THREAD

**Issue by justyeh** [ElemeFE/element#15484]
### Element UI version
2.8.2

### OS/Browsers version
win7/chrome74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
click the select

### What is Expected?
正常的弹出动画

### What is actually happening?
这个是我在开发时发现的，包括官网也能复现；

表现：下拉框弹出时会反复跳动两次

[![GIF.gif](https://i.loli.net/2019/05/09/5cd3e7d0f1ded.gif)](https://i.loli.net/2019/05/09/5cd3e7d0f1ded.gif)

**Comment by ccy303** [comment]
I know hao to deal it

**Comment by LebronLei** [comment]
i have the same question

**Comment by yangyalu** [comment]
I have the same question

**Comment by yangyalu** [comment]
How to solve it?

**Comment by ChenErik** [comment]
it's maybe chrome bug?

**Comment by island205** [comment]
Duplicate of #15501
