### ISSUE TITLE
[Bug Report] el-input property show-word-limit looks off (border gets disrupted) when inside an el-form

### ISSUE THREAD

**Issue by skalidindi** [ElemeFE/element#15494]
### Element UI version
2.8.2

### OS/Browsers version
Chrome / Version 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/skalidindi/pen/pmgBJv

### Steps to reproduce
See codepen

### What is Expected?
El-input should should look the same as it looks when outside of a form

### What is actually happening?
El-input has its border cut off and looks weird when inside an el-form and the show-word-limit attribute is enabled.

**Comment by SimonaliaChen** [comment]
Duplicated with #15359
