### ISSUE TITLE
[Table]有横向滚动条, 某一列fixed="right"时，横向滚动时表头的文字会显示在滚动条上方

### ISSUE THREAD

**Issue by wanhui046** [ElemeFE/element#1549]

**Comment by wanhui046** [comment]
![image](https://cloud.githubusercontent.com/assets/24378952/20872379/eb321fe2-bad8-11e6-8076-d8f50afb6019.png)

**Comment by Yunkou** [comment]
建议：在fixed 层下面加一层遮罩层，这个bug 是视觉上的。
