### ISSUE TITLE
After setting the HTTP-request parameter for the [Bug Report] upload component, action should not be mandatory

### ISSUE THREAD

**Issue by lyh2668** [ElemeFE/element#15498]
### Element UI version
2.8.2

### OS/Browsers version
所有

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lyh2668/pen/EzKxMy

### Steps to reproduce
使用upload组件的时候，文档中描述http-request可以重写action的行为，但是在填入http-request，并删除action参数时，会报一个action required的warning，显然重写了上传行为以后，action应该不再是一个必填参数。

### What is Expected?
http-request有值且为一个function的情况下，action不应该为一个必填参数

### What is actually happening?
http-request有值且为一个function的情况下，action仍然为一个必填参数，可以填入任意值，但是无意义

**Comment by lwm98** [comment]
同问+1
