### ISSUE TITLE
[Bug Report] Weird jump on dropdown animation in Chrome

### ISSUE THREAD

**Issue by websanova** [ElemeFE/element#15501]
### Element UI version
2.8.2

### OS/Browsers version
Windows Chrome Version 74.0.3729.131 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.com

### Steps to reproduce
Seems to be happening everywhere, can even check the main demo site.

Only chrome, all the dropdowns do this weird bounce. You can see it on your own site (all versions).

https://element.eleme.io/2.8/#/en-US/component/dropdown

### What is Expected?
remove the bounce

### What is actually happening?
weird bounce

**Comment by zuibunan** [comment]
same problem

**Comment by fluentwind** [comment]
same problem
transition 'el-zoom-in-top' triggered twice in Chrome 74
maybe something changed when processing multiple transition in CHROME at
`transition: transform .3s cubic-bezier(.23, 1, .32, 1), opacity .3s cubic-bezier(.23, 1, .32, 1), -webkit-transform .3s cubic-bezier(.23, 1, .32, 1);
  `

**Comment by makaria** [comment]
tried ` .el-zoom-in-top-enter,
.el-zoom-in-top-enter-active {
  transition-property: transform;
} `
The transition doesn't seem to trigger twice any more, but it may not trigger once at all.

**Comment by claviska** [comment]
Can't post a video and GIFs don't have a good enough frame rate to show it properly, but [here's what it looks like in the docs](https://csnl.s3.amazonaws.com/elementui-dropdown-issue.mp4).

**Comment by coffeeyen** [comment]
same problem at chrome v75, I tried element-ui v2.0.11-v2.9.1, it always happened, but is OK with element-ui v1.43

**Comment by edum18** [comment]
+1

**Comment by trananhmanh89** [comment]
+1

**Comment by island205** [comment]
@trananhmanh89 so, issue closed

**Comment by claviska** [comment]
This is indeed fixed in Chrome 76. Any idea what the cause was?

**Comment by island205** [comment]
@claviska We only know ths cause is `scaleY` css animation.

**Comment by Fuphoenixes** [comment]
Is there any way to solve it?

**Comment by minhail** [comment]
@Fuphoenixes 
我比较了别的ui框架，用animation覆盖掉element原有的transition动画，就解决了。
