### ISSUE TITLE
咨询下关于el-tree的问题

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#1550]
### ElementUI version

对于节点可被选择（即 show-checkbox 为 true）的tree，如果子节点没有全部选中，父节点（包括祖宗节点也是）现在的样式是底色蓝，中间横杠的。想问的问题是在获取选中子节点的数据时怎么同时获取父节点（包括祖宗节点）的数据呢。现在通过getCheckedKeys/getCheckedNodes貌似只能获取到选中节点的数据。

**Comment by furybean** [comment]
leafOnly 设置为 false 可以获取到所有选中节点，不过半选不是一种选中状态，他只是被子节点影响的一种状态。

**Comment by kopheece** [comment]
@furybean 现在就是想咨询下 如何获取这些半选状态的数据

**Comment by liuzhibin123** [comment]
我也想获取这些半选状态的数据     求指点

**Comment by hisway** [comment]
曲线解决方案:
采用check-strictly模式，通过 check-change 事件，当子节点改变且为选中时调用setChecked将父节点（通过计算或直接在初始节点中加上父节点id获取）直接设置选中状态，此时就能通过getCheckedKeys/getCheckedNodes获取
见：https://jsfiddle.net/hisway/xrbv65e5/4/
