### ISSUE TITLE
[Bug Report] In elementUI 2.8.X, the data dynamically added in the table is not displayed properly.

### ISSUE THREAD

**Issue by djytwy** [ElemeFE/element#15503]
### Element UI version
2.8.2

### OS/Browsers version
Chrome 73

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/djytwy/pen/rgeWwK

### Steps to reproduce
Initialize the interface. In the mounted() gets the data from the server, it is filled into the table, but the display of the table is not normal, or the height of the initialization, the max-height attribute does not take effect.

### What is Expected?
Like 2.6.X, the table's attribute max-height can take effect.

### What is actually happening?
The max-height attribute does not take effect,in elementUI 2.8.X

**Comment by JBtje** [comment]
just add `height="100vh"` to <el-table

**Comment by djytwy** [comment]
Thank you！
