### ISSUE TITLE
时间选择器的样式是不是出问题了？

### ISSUE THREAD

**Issue by ChenFan452043278** [ElemeFE/element#1551]
![pj 5 t 1mp7vo r u6nyq](https://cloud.githubusercontent.com/assets/22318152/20874156/388e5178-baea-11e6-8ee3-637434fcf73c.png)

好像日期时间选择器里面的时间选择也出问题了。。前两天写的时候还好的  今天再上去看就有问题

**Comment by Leopoldthecoder** [comment]
操作系统和浏览器是？

**Comment by ChenFan452043278** [comment]
win7的，浏览器用了chrome、Firefox都是这样的

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/ElemeFE/element/pull/1577
