### ISSUE TITLE
[Bug Report] Collapse menu sometimes menu name not hidden

### ISSUE THREAD

**Issue by tatc** [ElemeFE/element#15523]
### Element UI version
2.8.2

### OS/Browsers version
Most major browsers

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/tatc-ivc/pen/VOKwXe?&editable=true#0

### Steps to reproduce
Add a label div outside the label el-submenu，
when chick the collapse button，
title of the label el-submenu can not hide.
But do the same thing for labei el-menu-item ,
menu title can hide

### What is Expected?
i hope we can use other label outside <el-submenu></el-submenu> ,
because cycle is always needed.
moreover vue/no-use-v-if-with-v-for ，
so label outside <el-submenu> will inevitably used.

### What is actually happening?
we can use extra tag outer layer in el-submenu tag moreover hide menu name when menu is collapsed

**Comment by haibucuo** [comment]
add css
```css
.el-menu--collapse .el-submenu>.el-submenu__title span
  height: 0;
  width: 0;
  overflow: hidden;
  visibility: hidden;
  display: inline-block;
```
