### ISSUE TITLE
Beginning with version 2.7 of [Bug Report], Cascader cascade selector dynamically loads data, and data is not rendered, as is the case with official examples.

### ISSUE THREAD

**Issue by keep2zero** [ElemeFE/element#15520]
### Element UI version
2.8.2

### OS/Browsers version
mac 10.14.4/chrome 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/keep2zero/pen/RmReVO

### Steps to reproduce
查看 动态加载次级选项

### What is Expected?
数据动态渲染

### What is actually happening?
不渲染数据

**Comment by qingdengyue** [comment]
cc @Leopoldthecoder 官网的文档貌似没有更新，本地运行看到的文档已经没有这个问题了。
