### ISSUE TITLE
[Bug Report] tabular sort bug

### ISSUE THREAD

**Issue by JimboXie** [ElemeFE/element#15530]
### Element UI version
2.8.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://xuliangzhan.github.io/vue-element-extends/#/table/base6

### Steps to reproduce
当表格的排序条件发生变化的时候会触发sort-change事件，但是点击3下排序条件为空的时候 sort-change 返回
{ column: null, prop: null, order: null }
如果多个排序，我该如何确定是哪个排序失效????
点击重现链接点击表头排序，控制台会报错

### What is Expected?
期望在取消排序后将column返回来以来确认是哪列取消了排序

### What is actually happening?
取消排序后将column返回是null，如果是多个同时排序就不能确认是哪个取消了排序

**Comment by ziyoung** [comment]
看一下这个 pr #15012
