### ISSUE TITLE
1.0.4的el-select问题 

### ISSUE THREAD

**Issue by cycold** [ElemeFE/element#1553]
默认值问题已确认: https://github.com/ElemeFE/element/issues/1537

当绑定的model对象中没有提前定义好相应的option字段时,发现选择不了了.但是在1.0.3中是可以选择的. 
当没有提前定义好相应对象的字段时,一般是vue不能在get函数中hook的, 但是可否在触发option选择时,在el-select中this.$set()下呢?

demo: http://codepen.io/cycold/pen/bBvGLY?editors=1010

3.下个版本可以将 https://github.com/ElemeFE/element/pull/1352 合并进来么

**Comment by Leopoldthecoder** [comment]
#1537 的问题下个版本会修掉。

关于绑定值的字段没有提前定义的问题，还是应该由用户来处理。1.0.3 版本虽然可以选择，但是其实绑定值还是空的。

#1352 还有些问题，可能下个版本合不了。
