### ISSUE TITLE
[Bug Report] Found build error when using vuepress, at version：^v2.8.0

### ISSUE THREAD

**Issue by kybetter** [ElemeFE/element#15531]
### Element UI version
2.8.0

### OS/Browsers version
Mac/nodeJS

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/new

### Steps to reproduce
1. upgrade ElementUI version to 2.8.0  (lower version have no this bug).

2. then import ElementUI to `enhanceApp.js`.

```
import 'element-ui/lib/theme-chalk/index.css';
import ElementUI from 'element-ui';

export default ({Vue}) => {
  Vue.use(ElementUI)
}
```

3. run : `vuepress build`

4. found error:
```
ReferenceError: HTMLElement is not defined
```

### What is Expected?
no error

### What is actually happening?
has error

**Comment by anyclub** [comment]
同样的问题
