### ISSUE TITLE
Can we add responsive attributes in [Feature Request] renderContent, such as v-model?

### ISSUE THREAD

**Issue by 5j2f** [ElemeFE/element#15536]
### Existing Component
是

### Component Name
tree

### Description
我用renderContent开发一个用户自定义文件夹 有添加删除编辑文件夹明的功能，在添加的时候用了一个input框里面放了v-mode，在input框里面输入了值，但是却取不到这个值，

**Comment by VanMess** [comment]
可以尝试用 `slot-scope` 代替
