### ISSUE TITLE
[Bug Report] Popover appears again on focused button when return back to window

### ISSUE THREAD

**Issue by isnifer** [ElemeFE/element#15547]
### Element UI version
2.8.2

### OS/Browsers version
macOS Mojave 10.14.4 (18E226) / Chrome 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://element.eleme.io/#/en-US/component/tooltip#more-content

### Steps to reproduce
1. Click on button "Top center"
2. Go to another browser tab
3. Switch back

### What is Expected?
Tooltip is hidden

### What is actually happening?
Tooltip is visible (issue was introduced in [#9990](https://github.com/ElemeFE/element/pull/9990/files#diff-f1cd789cd4bb12c39181f63ca94d0331R129))
![element-ui-tooltip-issue](https://user-images.githubusercontent.com/1788245/57687307-dfbb6f00-7643-11e9-803d-d320c7e3fd87.gif)

1. The worst case when button with the tooltip triggers a Dialog.
![image](https://user-images.githubusercontent.com/1788245/57688209-9409c500-7645-11e9-998d-c7ab18cc620c.png)
2. You switch between tabs
3. And you are getting this tooltip above Dialog:
![image](https://user-images.githubusercontent.com/1788245/57688270-b26fc080-7645-11e9-8f14-c0126f5416ce.png)
Because renders again on focus and gets new zIndex — higher than modal

**Comment by WaSheep** [comment]
Sorry, This is an experimental technology, we have no plan to support this

**Comment by isnifer** [comment]
@WaSheep What are you talking about? The bug is not an experimental technology.
If you don't like my solution — suggest your own.
