### ISSUE TITLE
[Bug Report] el-checkbox cannot remain selected after switching data sources

### ISSUE THREAD

**Issue by sndwow** [ElemeFE/element#15540]
### Element UI version
2.8.2

### OS/Browsers version
win 10 x64 / chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/sndwow/pen/RmoRzG

### Steps to reproduce
1、勾选checkbox
2、点击切换数据源，此时会切换到第二个data
3、再点击一次切换数据源按钮，切换回刚开始的数据
此时可以看到原生的checkbox是勾选状态，而el-checkbox是未勾选状态（但其实是勾选了，只是样式没变化，单击就会发现触发了取消勾选）

### What is Expected?
动态切换数据源后，再次切换回来时 el-checkbox应该和原生的checkbox保持一致的行为

### What is actually happening?
实际上el-checkbox的状态也是勾选，但是ui呈现为未勾选

**Comment by qingdengyue** [comment]
额。这个不建议这么用。
1. v-model 本身的实现就是利用元素的value值，如果元素上再写个:value，就有问题
2.element的checkbox组件，v-model这个值，建议遵循官方文档用Boolean类型。

**Comment by sndwow** [comment]
> 额。这个不建议这么用。
> 
> 1. v-model 本身的实现就是利用元素的value值，如果元素上再写个:value，就有问题
> 2. element的checkbox组件，v-model这个值，建议遵循官方文档用Boolean类型。

那请问下有什么方式可以绑定一个数组中为对象的元素，主要是boolean不满足功能需求

**Comment by qingdengyue** [comment]
给数组中每一个元素增加一个Boolean类型的字段，for循环绑定的时候用这个字段就行。比如，原的内容是:
```
[
  {
       userName:'XXX'
  }
]
```

加一个Boolean的字段如下：

```
[
  {
       userName:'XXX',
       validate: false（默认值，可以根据业务自己设置）
  }
]

```

**Comment by sndwow** [comment]
@qingdengyue 
然而这样v-model不能得到勾选的数组每个元素，只能得到validate结果集

**Comment by qingdengyue** [comment]
对啊，这样数据中就可以根据每个validate的值获取，选中或者未选中的元素了。

**Comment by sndwow** [comment]
@qingdengyue 
这样的话当数据源改变时，需要将数据源和已选的数据循环对比，再将数据源的数据标记为已选或未选。
而原生的checkbox框则不需要重复此操作

**Comment by sndwow** [comment]
况且在给出的链接中，el-input是支持这样的勾选的，只是样式显示有问题，需要点击2次才能恢复正常
