### ISSUE TITLE
[Bug Report] The max-height attribute in the fluid height of the table cannot change the height of the table when the data increases.

### ISSUE THREAD

**Issue by usernameddd** [ElemeFE/element#15546]
### Element UI version
2.8.2

### OS/Browsers version
Google Chrome  版本 74.0.3729.131（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/usernameddd/pen/XwNgOo

### Steps to reproduce
把表中原先定义的数据移除到只剩一条记录时，再点击'添加数据'按钮，向表格中添加数据；此时，表格的高度一直固定在一条数据的高度，同时表格出现滚动条；

### What is Expected?
当把表中原先定义的数据移除到只剩一条记录时，再点击'添加数据'按钮，向表格中添加数据；期待的效果是表格的高度会自动增加直到max-heigt所设定的值为止，高度超过max-height所设定的值之后再出现滚动条

### What is actually happening?
当把表中原先定义的数据移除到只剩一条记录时，再点击'添加数据'按钮，向表格中添加数据；表格的高度一直固定为一行数据的高度并出现滚动条。这样表格的max-height相当于没有起作用。

**Comment by gucg0307** [comment]
静待回复

**Comment by shohei-ot** [comment]
I also encountered the same phenomenon.

**Comment by guanjunliu** [comment]
The same problem. Waiting for the answer.

**Comment by UltramanWeiLai** [comment]
一样碰到了这个问题
我目前是，更新数据的时候手动把.is-scrolling-none的maxHeight给毙掉，希望官方能早点解决这个bug把
this.$nextTick(() => {
     document.querySelector('.is-scrolling-none').style.maxHeight = '';
});

**Comment by zdd2018** [comment]
我是页面加载得时候就是一行的高度，maxHeight没有生效，tab切换其他tab再回来才恢复正常

**Comment by ziyoung** [comment]
Duplicate of #15436
