### ISSUE TITLE
[Bug Report] 2.1.0 upgrade to 2.8.2 Upload component onchange callback, file object lacks URL parameter

### ISSUE THREAD

**Issue by 98DE9E1F** [ElemeFE/element#15558]
### Element UI version
2.8.2

### OS/Browsers version
mac 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/MdJvPx?&editable=true

### Steps to reproduce
升级后缺少字段url

### What is Expected?
升级后缺少字段url

### What is actually happening?
升级后缺少字段url

**Comment by TuffyLiu** [comment]
up
