### ISSUE TITLE
[Bug Report] select control clicks on lost animation

### ISSUE THREAD

**Issue by TY-LIU** [ElemeFE/element#15550]
### Element UI version
2.8.2

### OS/Browsers version
WIN10 64位 / Chrome 74.0.3729.131 (正式版本) （64 位） 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ty-liu/pen/YbpYZp?&editable=true

### Steps to reproduce
官网链接，点击就会发现option闪现，随机丢失动画

### What is Expected?
正常动画

### What is actually happening?
随机丢失动画
![Video_2019-05-14_180247](https://user-images.githubusercontent.com/29595097/57690313-f679ba00-7673-11e9-9634-fb7edf12fdcf.gif)

**Comment by TY-LIU** [comment]
经测试，firefox没有这个问题，最新版的Chrome有

**Comment by LebronLei** [comment]
Same problem ,have you solved it yet?

**Comment by huxuwei** [comment]
遇到同样问题, chrome 72 还是可以的,  chrome 74 出现这种情况
