### ISSUE TITLE
[Bug Report] Searchable Select Component have some question in android pad.

### ISSUE THREAD

**Issue by XuXianTao** [ElemeFE/element#15554]
### Element UI version
2.8.2

### OS/Browsers version
Android 8.0.0 / Chrome 74.0.3729.136

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/GarWJq

### Steps to reproduce
1. Click and focus on the select component.
2. Click the component again to close the drop-down box.

### What is Expected?
1. Click the select component but not focus automatically. And appear the drop-down box.
2. Click the select component again and focus on the input. And appear the virtual keyboard.
3. Click the component again to select or close the drop-down box.

### What is actually happening?
1. Click and focus on the select component. Now the virtual keyboard doesn't appear.
2. Click the component again to close the drop-down box. Then the virtual keyboard flash suddenly and disappear.

**Comment by XuXianTao** [comment]
![ezgif-2-2ec6ef9e1eb3](https://user-images.githubusercontent.com/32198066/57746490-f5906900-7703-11e9-8e03-33dd957f9905.gif)

**Comment by cangyu1993** [comment]
element是pc端ui框架啊，你在m端使用了？

**Comment by XuXianTao** [comment]
嗯。目前在pc端又有适配平板的需求，导致部分问题。orz

**Comment by XuXianTao** [comment]
嗯。目前在pc端又有适配平板的需求，导致部分问题。orz

**Comment by XuXianTao** [comment]
嗯。目前在pc端又有适配平板的需求，导致部分问题。orz

**Comment by cangyu1993** [comment]
m端平板pc三端切换很烦，好像没有完美的兼容方案，你这等于是做自适应了，试试vue-bootstrop

**Comment by XuXianTao** [comment]
嗯。目前项目已经定型，这一块只能自己手动做一下适配了，感谢~
vue-bootstrap等下个项目的时候我会去试试看看
