### ISSUE TITLE
[Bug Report] The default value of show-word-limit in the el-input component in the official document is false, error, and true.

### ISSUE THREAD

**Issue by zhacaigeng** [ElemeFE/element#15569]
### Element UI version
2.8.2

### OS/Browsers version
win 10 x64 / chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
设置

### What is Expected?
show-word-limit添加后，字符限制生效，和设置:show-word-limit=true 效果雷同，所以默认值为true，而非官方文档的默认值为false

### What is actually happening?
Nothing

**Comment by masongzhi** [comment]
添加了`show-word-limit`字段，其值为 true，与`show-word-limit = true`一致，不添加该字段才触发默认值 false
