### ISSUE TITLE
[Bug Report] TimerPicker time range selection restriction is invalid

### ISSUE THREAD

**Issue by twobear** [ElemeFE/element#15563]
### Element UI version
2.8.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/ccbear/xr7ba53h/17/

### Steps to reproduce
直接选择 demo 链接的时间范围进行查看

### What is Expected?
填入 :picker-options="{selectableRange: ['8:30:00 ~ 22:30:00']}"  不应该能选取这个范围之外的数值

### What is actually happening?
完全没有限制

**Comment by qingdengyue** [comment]
你传的格式不对
[TimePicker](https://element.eleme.cn/#/zh-CN/component/time-picker)

```

selectableRange
可选时间段，例如
'18:30:00 - 20:30:00'
或者传入数组
['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']

```

**Comment by twobear** [comment]
> 你传的格式不对
> [TimePicker](https://element.eleme.cn/#/zh-CN/component/time-picker)
> 
> ```
> 
> selectableRange
> 可选时间段，例如
> '18:30:00 - 20:30:00'
> 或者传入数组
> ['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']
> ```

没用的阿，不是格式问题，换个格式还是不行。看过源码这部分处理应该是有问题的
