### ISSUE TITLE
[Bug Report] select and dropdown control clicks on lost animation or jump animation problem in chrome browers sometimes

### ISSUE THREAD

**Issue by LebronLei** [ElemeFE/element#15574]
### Element UI version
2.4.4

### OS/Browsers version
windows 10

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/lebronlei/pen/pmeKLX

### Steps to reproduce
Clicking the click or dropdown box occasionally causes a flashing problem

### What is Expected?
Fix this serious bug in chrome

### What is actually happening?
no jump animation

**Comment by claviska** [comment]
Possible duplicate of #15501

**Comment by websanova** [comment]
Yes, it's duplicate of my issue: https://github.com/ElemeFE/element/issues/15501

**Comment by LebronLei** [comment]
> Possible duplicate of #15501
Thank you , i get it.
