### ISSUE TITLE
[Bug Report] Table components cannot use multiple selection and filtering at the same time

### ISSUE THREAD

**Issue by JerryWang24** [ElemeFE/element#15573]
### Element UI version
2.8.2

### OS/Browsers version
chrome

### Vue version
[2.5.9](url)

### Steps to reproduce
同时使用多选和筛选会报错误
$attrs is readonly.

found in

---> <ElCheckbox> at packages/checkbox/src/checkbox.vue
       <ElCheckboxGroup> at packages/checkbox/src/checkbox-group.vue
         <Root>

### What is Expected?
可以同时存在多选和表头筛选，

### What is actually happening?
不能同时存在多选和表头筛选，

**Comment by masongzhi** [comment]
https://codepen.io/masongzhi123/pen/dEvjBr?&editable=true
试下小 demo 是可以的，若还是不行，请提供重现 demo
