### ISSUE TITLE
[Bug Report] DateTimePicker设置clearable为false，但是日期选择里面“清空”按钮并没有隐藏

### ISSUE THREAD

**Issue by phaibin** [ElemeFE/element#15580]
### Element UI version
2.8.2

### OS/Browsers version
macOS Mojave / Chrome 74.0.3729.157

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/10h37bs5/

### Steps to reproduce
点击输入框选择日期

### What is Expected?
预期没有清空按钮

### What is actually happening?
清空按钮仍然显示

**Comment by masongzhi** [comment]
https://codepen.io/masongzhi123/pen/gJWKXG?&editable=true
jsfiddle 我打开不了，是否传了字符串的 false 属性，上面demo是正常的

**Comment by Jarryham** [comment]
> https://codepen.io/masongzhi123/pen/gJWKXG?&editable=true
> jsfiddle 我打开不了，是否传了字符串的 false 属性，上面demo是正常的

好像把type改为 datetimerange就有问题了

**Comment by masongzhi** [comment]
https://codepen.io/masongzhi123/pen/mYmKjB
也没问题，你对比下

**Comment by Jarryham** [comment]
> https://codepen.io/masongzhi123/pen/mYmKjB
> 也没问题，你对比下

下面的下拉出来那里还有清空，输入框里的消失了是没问题的

**Comment by masongzhi** [comment]
清空和确认这两个按钮是不受 clearable 影响的
```html
<div class="el-picker-panel__footer" v-if="showTime">
    <el-button
        size="mini"
        type="text"
        class="el-picker-panel__link-btn"
        @click="handleClear">
        {{ t('el.datepicker.clear') }}
    </el-button>
    <el-button
        plain
        size="mini"
        class="el-picker-panel__link-btn"
        :disabled="btnDisabled"
        @click="handleConfirm(false)">
        {{ t('el.datepicker.confirm') }}
    </el-button>
</div>
```

**Comment by phaibin** [comment]
输入框里的叉叉确实没有了，但是下面的清空按钮还在，所以看源码就知道肯定是有问题的了

**Comment by Luummii** [comment]
https://github.com/ElemeFE/element/issues/15177

**Comment by quanquan2100** [comment]
我也认为既然 clearable 为 false 那么, 底下不应该显示"清空"

**Comment by a631807682** [comment]
https://github.com/ElemeFE/element/pull/17447

**Comment by Bruce-1988** [comment]
怎样才能把清除按钮去掉啊？

**Comment by DogCQ** [comment]
可以设置 popper-class，通过样式来控制

**Comment by lihuangshuaige** [comment]
没人管啊   现在还有这个问题

**Comment by freemedom** [comment]
element-plus没这个问题了，2还是有

**Comment by freemedom** [comment]
好像是不能scoped
```
        <el-date-picker
          popper-class="el-date-picker-clear"
        />

<style lang="scss">
// 去掉清空按钮
.el-date-picker-clear {
  .el-button--text {
    display: none;
  }
}
</style>

```
