### ISSUE TITLE
[Bug Report] el-checkbox can`t select when set value instance of v-model on el-checkbox-group 

### ISSUE THREAD

**Issue by ganshiqingyuan** [ElemeFE/element#15595]
### Element UI version
2.6.1

### OS/Browsers version
macos chrom

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
<el-checkbox-group 
                :value="myInitData.split(',')"
                @change="selectChange"
                >
                <el-checkbox v-for="(item,index) of myDict" :label="item.dictCode" :key="index">{{item.dictName}}</el-checkbox>
            </el-checkbox-group>

selectChange:function(item){
   myInitData = item.join(",");
}

### What is Expected?
init the select by value and change the data by @change  because our checked saved by xx,xx,xx  not [xx,xx,xx].

### What is actually happening?
when i set value on el-checkbox-group instance of v-model  . i can`t select any checkbox

**Comment by JeremyWuuuuu** [comment]
Please do give a reproduction link use any online editor you like e.g. `codesandbox` `codepen`, `jsbin` and  etc.

**Comment by pujiaxun** [comment]
Same issue.
How can I use `checkbox-group` as a controlled component like the following sample? 

```html
<el-checkbox-group
  :value="myInitData.split(',')"
  @change="selectChange"
>
{{item.dictName}}
</el-checkbox-group>
```

```js
selectChange:function(item){
  myInitData = item.join(",");
}
```

**The `radio-group` can support this, but not `checkbox-group`... It doesn't make sense.**
Please have a look~ 

Thanks
