### ISSUE TITLE
The scroll bar does not display when the [Bug Report] tree table expands

### ISSUE THREAD

**Issue by YuThree** [ElemeFE/element#15592]
### Element UI version
2.8.2

### OS/Browsers version
Win10 / Google Chrome 73.0.3683.103（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yuthree/pen/BeRrKv

### Steps to reproduce
设置一个table高度 在第一层数据小于设置高度 展开时大于设置高度 就可重现

### What is Expected?
展开的时候如果超出高度 显示滚动条
希望：
1.树形数据可以和 type="expand" 的展开行 一样可以设置默认展开项
2.提供如 ‘ expand-change’  的树形数据的展开关闭触发方法

### What is actually happening?
展开的时候没有显示滚动条

**Comment by herojhc** [comment]
我也遇到了...

**Comment by YuThree** [comment]
2.9.1 fixed

**Comment by qwqetyrtue** [comment]
2个方法解决,1,把maxhight设置到小于未展开的时候,2,套个div放外面,用原生的overflow
