### ISSUE TITLE
npm安装直接使用，调用table 控件时，element-ui.common.js 文件中_t() 函数报 undefined

### ISSUE THREAD

**Issue by fuyuanwu** [ElemeFE/element#156]
element-ui.common.js 文件中 _t() 为undefined。  1.0.0-rc.3 版本是没有这个函数的，所以不会报这个错。

### ElementUI version
1.0.0-rc.4 
### Vue version
 2.0.0-rc.4

**Comment by QingWei-Li** [comment]
检查 vue, vue-loader 和 vue-template-compiler 是否是最新版

**Comment by fuyuanwu** [comment]
更新后可用了。更新后的版本是
`
{
    "vue": "2.0.0-rc.7",
    "vue-template-compiler": "^2.0.0-rc.7",
    "vue-loader": "9.5.0"
}
`
