### ISSUE TITLE
[Feature Request] ElUpload: Exposing the internal uploadFiles properties

### ISSUE THREAD

**Issue by fxxjdedd** [ElemeFE/element#15609]
### Existing Component
是

### Component Name
ElUpload

### Description
在开发中，经常需要判断el-upload是否已经添加文件，如果未添加则不允许提交，但是我在目前的组件文档中找不到能直接实现上述需求的方法。

有两种方法可以实现上述需求：

1. 提供一个on-added回调，在用户添加文件后回调
2. 提供一个v-model，把el-upload内部的uploadFiles属性暴露出来，并废弃file_list属性（现在只能通过refs来获取）

以上，辛苦了~

**Comment by hql7** [comment]
无法判断是否选了文件真痛苦
