### ISSUE TITLE
Set max-height instead of height for Tables with fixed header

### ISSUE THREAD

**Issue by HashemQolami** [ElemeFE/element#1560]
### ElementUI version
1.0.4

### OS/Browers version
Ubuntu 16.04 / Chrome 51

### Vue version
2.0.8

### Reproduction Link
http://jsfiddle.net/xL3hw27h/

### Steps to reproduce
1. Click the `Reduce the TableData by: ...` button.
2. Repeat step 1 until the scrollbar disappears.

### What is Expected (better say: desired)?
When the table data is reduced due to filtering, the height of the table should change accordingly. For instance there may be an input which allows the user to filter/search through the table data. In that case the height of the table should get smaller.

### What is actually happening?
The height of the table is (sorta) statically set and it doesn't change when the table data changes. When the table data is reduced, the scrollbar disappears but the height of the table does not change accordingly.

- - -

I looked at the source code, specifically the `height` property. I know what it does and how it does what it does :) but I think a `maxHeight` property would be much helpful, at least in this case.

I ended up with two solutions, either changing the functionality of `height` property so that it would set the `max-height` CSS property of the table rather than the `height` *or* to add a `maxHeight` property for table component so that it does the trick under the hood.

I know we can bind the `height` property dynamically (through `:height`) whenever the data changes but it is not that performant (doing calculations with JS to do a CSS job). IMO it is better to stick with pure CSS properties when possible.

Please let me know what you think so that I can send a PR if you will.

**Comment by HashemQolami** [comment]
@QingWei-Li Shall I send a PR for that?

If so, please let me know which one is more accepted, either adding a `maxHeight` property or changing the `height` prop functionality so that it sets the `max-height` rather than the `height`.

**Comment by furybean** [comment]
@HashemQolami  Sorry to reply late, you can send a PR.
Add a `maxHeight` is more is more appropriate  for this scenario.

**Comment by HashemQolami** [comment]
@furybean Thanks. I am working on it. Will send a PR soon.
One  question: This new feature needs a few changes in the default theme, how should I do the changes?

There is a `theme-default` directory in packages, and also a separate [repository](https://github.com/ElementUI/element-theme) which is used as the source of the custom theme builder.

Which one should be modified?

**Comment by Leopoldthecoder** [comment]
@HashemQolami Please edit the `theme-default` directory of this repo. Once your PR is merged, the separated repo will be updated automatically.
