### ISSUE TITLE
Will the max-height attribute of the [Bug Report] table module be released again

### ISSUE THREAD

**Issue by xuduogui** [ElemeFE/element#15600]
### Element UI version
2.8.2

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/pull/14660

### Steps to reproduce
直接打开链接

### What is Expected?
table模块的max-height属性是否会再次释放出来

### What is actually happening?
table模块的max-height属性被无效了

**Comment by gavin1990** [comment]
bodyHeight returns the default empty height in case of data loading delay.
image
image

**Comment by gavin1990** [comment]
bodyHeight returns the default empty height in case of data loading delay.
![image](https://user-images.githubusercontent.com/3071145/58297979-5dce0180-7e0c-11e9-9620-88cb0dd554e7.png)
![image](https://user-images.githubusercontent.com/3071145/58297981-60305b80-7e0c-11e9-8ff8-391cdbcf1bfd.png)

**Comment by ziyoung** [comment]
Duplicate of #15436
