### ISSUE TITLE
[Bug Report] prompt remove confirmation before upload unacceptable file

### ISSUE THREAD

**Issue by pape2016** [ElemeFE/element#15603]
### Element UI version
2.8.2

### OS/Browsers version
windows10/firefox

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pape2016/pen/WBjYbm

### Steps to reproduce
1. create a el-upload element with before-remove and before-upload, accept property only allow image/jpeg file
2. function beforeRemove will prompt a remove confirmation message before remove a file.
3. function beforeUpload will prompt a message if upload an unacceptable format file.
4. upload an acceptable format file
5. it will prompt a remove confirmation message? then prompt an message to reminder should upload an acceptable format file.

why it prompts a remove confirmation message? don't do any remove operation, just upload an unacceptable format file.

### What is Expected?
should not prompt remove confirmation message when uploading an unacceptable format file.

### What is actually happening?
prompt remove confirmation message when uploading an unacceptable format file.

**Comment by qingdengyue** [comment]
if unacceptable format file , execute removing operator. that's feature?

**Comment by pape2016** [comment]
@qingdengyue  maybe that is the cause, it is unreasonable, user does not remove the pic but upload a pic, Why prompting a remove confirmation message?
