### ISSUE TITLE
MessageBox not responsive (included fix)

### ISSUE THREAD

**Issue by dealloc** [ElemeFE/element#1561]
### ElementUI version
1.0.4

### OS/Browers version
54.0.2840.71 (Official Build) (64-bit) (Linux )

### Vue version
2.0.1

### Steps to reproduce
Just open a messagebox as described in [the docs](http://element.eleme.io/#/en-US/component/message-box#alert).

### What is Expected?
The messagebox should show properly on mobile devices.

### What is actually happening?
The messagebox looks very awkward and sized wrong on mobile devices
![screenshot_20161205-195503](https://cloud.githubusercontent.com/assets/2164354/20897967/c9bcba56-bb24-11e6-8b7f-ce70f8efd852.png)

I found that it is caused by the message body being set to a fixed width. I changed the current value of the width to the max-width and set the width to be 100%; which ends up with something like this:
```css
.el-message-box {
	width: 98%!important;
	max-width: 420px;
}
```

Which results in the dialog looking like this on mobile:
![screenshot_20161205-195758](https://cloud.githubusercontent.com/assets/2164354/20898067/2fbe053a-bb25-11e6-84f2-d474c8f9c6d1.png)

This also doesn't change anything on tablet or desktop view as the width is limited to what it's currently set to when the screen is bigger than the current width.

I tried cloning the repository to see if I could create a PR but so far I have yet to make sense of the CSS files.

**Comment by Leopoldthecoder** [comment]
Element is not meant for mobile devices. Maybe you can try [Mint UI](https://github.com/ElemeFE/mint-ui).

If you want to stick with Element, please override MessageBox's CSS.
