### ISSUE TITLE
[Vue warn]: Failed to resolve directive: loading

### ISSUE THREAD

**Issue by xiaoxing598** [ElemeFE/element#15629]
I am using the load component, follow the example on the documentation and I get an error. Is there a solution released?

```
<div v-loading="loading">
</div>

data() {
      return {
loading: false
}
```

**Comment by avfirsov** [comment]
> I am using the load component, follow the example on the documentation and I get an error. Is there a solution released?
> 
> ```
> <div v-loading="loading">
> </div>
> 
> data() {
>       return {
> loading: false
> }
> ```

Hey, man! You have to do like this in your main.js file to make things work:

import { Loading } from 'element-ui';
Vue.use(Loading);

**Comment by Aniket-Kale** [comment]
> > I am using the load component, follow the example on the documentation and I get an error. Is there a solution released?
> > ```
> > <div v-loading="loading">
> > </div>
> > 
> > data() {
> >       return {
> > loading: false
> > }
> > ```
> 
> Hey, man! You have to do like this in your main.js file to make things work:
> 
> import { Loading } from 'element-ui';
> Vue.use(Loading);

@avfirsov Works for me. Thanks
