### ISSUE TITLE
[table] IE下table中checkbox样式有问题

### ISSUE THREAD

**Issue by chaohuaGH** [ElemeFE/element#1563]
### ElementUI version

[1.0.4]
### What is actually happening?
在IE下每个checkbox右边会出现三个小点
![qq 20161206092424](https://cloud.githubusercontent.com/assets/20752717/20909305/c2b12e06-bb95-11e6-9e26-4e118e237d57.png)

**Comment by Leopoldthecoder** [comment]
把这一列的宽度适当加宽即可。
