### ISSUE TITLE
[Bug Report] el-select with attribute "multiple" can't apply size “mini” when it is in el-form

### ISSUE THREAD

**Issue by fjnty** [ElemeFE/element#15633]
### Element UI version
2.8.2

### OS/Browsers version
win7 chrome74.0

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/fjnty/pen/NVazyp

### Steps to reproduce
<el-form>
<el-form-item>
<el-select
multiple>
<el-option>
</el-option>
</el-select>
<el-form-item>
<el-form>

### What is Expected?
the widget el-select with "mini" size should have smaller height value than normal

### What is actually happening?
the widget el-select with "mini" size have same height value with normal

**Comment by masongzhi** [comment]
https://codepen.io/masongzhi123/pen/GaMLeL

add `size="mini"` to `el-form-item`

**Comment by fjnty** [comment]
Feel like it is a stylesheet scope problem. thanks for the solution!
