### ISSUE TITLE
[Bug Report] ElSelect should not have the prop value required

### ISSUE THREAD

**Issue by Vixys** [ElemeFE/element#15649]
### Element UI version
2.8.2

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/xLgw2sk8/

### Steps to reproduce
Use `el-select` element without specifying any `v-model` or `value`.

### What is Expected?
Work without raising any error or warning in browser console.

### What is actually happening?
A warning is raised in the browser console because the `value` prop is required and is missing.

**Comment by jorgemarcondes** [comment]
Same happens here. I'm using v-model, so is not necessary put value prop.
