### ISSUE TITLE
[Bug Report] Calendar header title

### ISSUE THREAD

**Issue by dmgame** [ElemeFE/element#15645]
### Element UI version
0.1.0

### OS/Browsers version
Windows10 / Chrome version 74.0.3729.157

### Vue version
2.6.6

### Reproduction Link
https://jsfiddle.net/dmgame/gbjmnps1/1/

### Steps to reproduce
1. switch until October month

### What is Expected?
Expected in the title of month "October" 

### What is actually happening?
Actually, we see January in the title

**Comment by ziyoung** [comment]
fixed in 2.9.1
