### ISSUE TITLE
[Feature Request] Calendar events and attributes

### ISSUE THREAD

**Issue by siberiadev** [ElemeFE/element#15656]
### Existing Component
Yes

### Component Name
Calendar

### Description
Hello, thanks for excellent lib))))
Could you tell me when calendar component gonna have more attributes and events?

I'm trying to highlight some dates on calendar from array:

`dates: ['2019-05-26', '2019-06-02']`

then in calendar:

```
<el-calendar v-model="tourCalendar">
    <template v-slot="{date, data}">
        <p :class="[
            data.isSelected ? 'is-selected' : '',
            dates.indexOf(data.day) >= 0?'active':''
        ]" >{{ data.day.split('-')[2] }}</p>
    </template>
</el-calendar>
```

But it doesn't work for me.
Maybe there is a way to do it without any updates of component repo. Please somebody advice me.
Also, it would be magic if I can change title of button in header, for example change "Next month" to chevron-right icon.

Something like:
`<el-calendar prev-month-title="<" next-month-title=">" today-title="Now" />`

And if it possible please add classes to this buttons like el-button__prev-month, el-button__next-month, el-button__today
Maybe somebody needs to overwrite button sizes.
So, I think it would be better to make slot="header" and some methods nextMonth() prevMonth() today() to let everybody to customize header buttons section.
Thanks!

**Comment by ziyoung** [comment]
v-slot:dateCell="{date, data}"
