### ISSUE TITLE
[Tree] 希望增加初始化选中一个节点的 API

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#1565]
有如下需求，
记住一个节点选择，刷新或者下次登录，用记住的数据渲染 当前节点，展示选中状态
不是check，就是选中
没找到相应办法，请大家指导
截图如下： 我想刷新时自动选中下面那个节点（节点id我已经存下来了），不通过点击，

![image](https://cloud.githubusercontent.com/assets/13325335/20911502/5c46abf6-bba3-11e6-814c-3917feaec31d.png)

**Comment by fewiki** [comment]
不行得用jquery了。。。

**Comment by liyanlong** [comment]
保存状态， 不是得用 sessionStorage 或者 localStorage吗

**Comment by fewiki** [comment]
不是，是历史记录，用户下次登录时用，现在存到数据库了
比如这次我选择的是第一级下的第4个子节点，下次登录或者刷新，要自动选中这个节点，节点id已有记好了，但不点击选不中。

之前用angular tree时  （ http://wix.github.io/angular-tree-control/）
 <treecontrol class="tree-light" tree-model="treedata" on-selection="showSelected(node)" selected-node="selected" expanded-nodes="expandedNodes"  options="opts">
     {{node.label}}
 </treecontrol>

这个组件提供了一个 selected-node属性，可以传入要选中的节点，就会自动 选中，期待tree组件也加一个

**Comment by kopheece** [comment]
有这样的接口的，你仔细看看官方文档，

**Comment by furybean** [comment]
@fewiki  #1807 中已经实现。

**Comment by yang0323** [comment]
有两个问题：
1、current-node-key不会影响父层的展开状态（这个可以认为是feature吧...用另一个参数可以展开）
2、只修改了store的currentNode，没有修改tree的currentNode，不过没有找到tree的currentNode在哪里引用了，怀疑是遗留的代码

**Comment by yang0323** [comment]
查了一下记录，是785bed2 这个版本加的，那个时候没有store，使用这个判断选中状态，现在有了store这个应该已经废弃，但是代码里仍然留着
