### ISSUE TITLE
Subitem data addition in the shape of [Bug Report] table tree cannot be displayed properly

### ISSUE THREAD

**Issue by sndwow** [ElemeFE/element#15666]
### Element UI version
2.8.2

### OS/Browsers version
win 10 / chrome 74.0.3729.157 x64

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/sndwow/pen/LoeGYZ

### Steps to reproduce
1、点击新增[追加首行的子项]按钮，对首行数据的子节点新增数据，此时点击展开子项却无法显示新增的数据
2、点击[追加父级]按钮，此时table更新，显示了步奏1中的子项数据
3、点击[追加父级]按钮后，丢失了原来的子项展开状态。

### What is Expected?
1、新增子项数据后，能够立即显示
2、新增数据或子项数据时，应该能够保持原来已展开的状态

### What is actually happening?
1、新增子项数据并没有在table中显示，需要新增父项才能出发table重新渲染
2、新增数据导致原子项的展开状态丢失，全部变为了未展开状态

**Comment by ziyoung** [comment]
fixed in 2.9.1
