### ISSUE TITLE
The horizontal scroll bar of the [Bug Report] table component cannot automatically disappear

### ISSUE THREAD

**Issue by woaixiangbao** [ElemeFE/element#15663]
### Element UI version
2.8.2

### OS/Browsers version
MacBook OS 10.14.5

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1,进入element官网的table组件页面，
2,滚动到“固定列”区域，
3,横向滚动此区域中的表格，hover到表格底部的滚动条部分，使用鼠标点击一下这个滚动条，或者使用鼠标左右拖拽一下，
4，鼠标离开后，这个横向滚动条就不会消失了。

对比一下会更清楚，刷新一下页面重新进来这个部分，使用鼠标滚轮（或者触摸板）使得横向滚动条出现，但是不要点击，然后鼠标离开表格区域，此时横向滚动条会自动消失。
不好的影响：当页面中有其他操作，比如出现一个弹窗时，这个不会自动消失的滚动条会在弹窗之上显示。

### What is Expected?
希望能自动消失横向滚动条

### What is actually happening?
不会自动消失

**Comment by ziyoung** [comment]
代码没保存。点击一下 save。

**Comment by woaixiangbao** [comment]
> 代码没保存。点击一下 save。

我那个codepen不是重点，你去elementUI官网的table页面也是可以复现的，我之所以写了个codepen的demo是因为不写不让提交问题。

**Comment by fantasthu** [comment]
我也遇到这个bug,table的横向滚动条不隐藏,然后有dialog弹框,看着就很明显
