### ISSUE TITLE
select组件 change事件 增加索引需求

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#1567]
现在change事件 只返回了当前的value值，而value值一般是显示名称，这样的话还得循环查找才到找到id
（之前是v-model取id，显示成name，现在这版改了之后，v-model变了）

下一版 有没有  增加 一个索引index参数，这样取值会非常方便，非常感谢

**Comment by Kingwl** [comment]
其实有个findIndex的

**Comment by Leopoldthecoder** [comment]
>现在这版改了之后，v-model变了

这个是 1.0.4 版本的一个 bug，会在 1.0.5 修复。

**Comment by allanruin** [comment]
@Kingwl  mind explain a bit how to use `findIndex` or could you please cite some doc reference? Thank you.
