### ISSUE TITLE
[Bug Report] el-date-picker when type is week, firstDayOfWeek is 1, model value will be Tuesday

### ISSUE THREAD

**Issue by firesh** [ElemeFE/element#15683]
### Element UI version
2.8.2

### OS/Browsers version
MacOS / Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/VOQaWd

### Steps to reproduce
1. select any week
2. check the model value

### What is Expected?
should select Monday

### What is actually happening?
returned Tuesday

**Comment by newdefence** [comment]
遇到同样的问题，好几个版本了，都有一年多了。

**Comment by firesh** [comment]
@ziyoung @luckyCao 这个问题是否为bug？

**Comment by Toukassay** [comment]
Hello, still no fix, right ?
