### ISSUE TITLE
[Bug Report] use keep-alive in router-view el-menu-item active state error

### ISSUE THREAD

**Issue by chengzhixuan** [ElemeFE/element#15680]
### Element UI version
2.8.2

### OS/Browsers version
macos mojave10.14.4/chrome74.0.3729.157

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
在router-view上使用keep-alive时  el-menu 的 el-menu-item会出现选中状态不对的情况
点击左边边的菜单栏el-menu-item 来回点击
https://www.chuanmeidayin.com/dist/index.html#/

### What is Expected?
点击对应的el-menu-item 对应的el-menu-item被选中状态

### What is actually happening?
左边的菜单栏el-menu-item的is-active的选中状态不对,总是慢了一步

**Comment by garyganyang** [comment]
`<template>
  <div id="app" class="app-width">

    <keep-alive>
      <router-view v-if="$route.meta.keepAlive">
      </router-view>
    </keep-alive>

    <router-view v-if="!$route.meta.keepAlive"/>
  </div>
</template>`

当我同意设置了keep-alive之后,  NavMenu 对应的菜单无法选中, 特别是在切换菜单的时候.

**Comment by pccBo-fe** [comment]
+1

**Comment by pccBo-fe** [comment]
在activated下在设置一次activeIndex就可以了
