### ISSUE TITLE
表格table组件 表头可以支持添加一些自定义内容么

### ISSUE THREAD

**Issue by PleaseTryAgain** [ElemeFE/element#1569]
![123](https://cloud.githubusercontent.com/assets/12001845/20914772/b6eb0bf6-bbbc-11e6-8422-c1ef97adcb3f.png)
我想在多表头中加入上图中框着的小图标，而表格的label属性只能传入字符串，不能实现需求。
能不能不限制label的类型，实现自定义

**Comment by Leopoldthecoder** [comment]
可以使用 `el-table-column` 的 `render-header` 属性。

**Comment by PleaseTryAgain** [comment]
关于这个属性官网上并没有给相应的例子，我console出来的内容是
![456](https://cloud.githubusercontent.com/assets/12001845/20916618/a11d9176-bbc7-11e6-98ef-627a8b76bf8f.png)
而且重复出现了三次。h参数不知道是什么 ， {column, $index }参数 好像是第几列和这个表头的对象 

请问能不能给个例子，谢谢了

**Comment by Leopoldthecoder** [comment]
参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) 第三问。

**Comment by Summer-Lin** [comment]
![image](https://user-images.githubusercontent.com/26006995/42359645-cfa23244-8115-11e8-9487-61c3e7f1baaa.png)
![image](https://user-images.githubusercontent.com/26006995/42359653-db64e130-8115-11e8-8469-ab8ad8f8ec5e.png)
![image](https://user-images.githubusercontent.com/26006995/42359658-e4e9bac8-8115-11e8-8dc2-1a8e4dc43939.png)

表头添加了图标和提示。。。

**Comment by shiny** [comment]
补充一个直接用原生 js 的写法

![image](https://user-images.githubusercontent.com/117487/45551457-9de1eb00-b860-11e8-95c3-ac8c4780c0e7.png)
```javascript
showTips(createElement, { column }) {
        return createElement(
          'el-tooltip',
          {            
            attrs: {
              content: column.labelClassName
            },
          },
          [
            createElement('span',  [ 
              column.label,
              ' ',
              createElement('i',  {
                'class': {
                  'el-icon-info': true
                },
              } ) 
            ] ),
          ]
        );
      }
```
效果预览
![image](https://user-images.githubusercontent.com/117487/45551491-b6520580-b860-11e8-9ed4-60e4ac4bad16.png)
