### ISSUE TITLE
Formter triggers twice in [Bug Report] el-table

### ISSUE THREAD

**Issue by WanManito** [ElemeFE/element#15696]
### Element UI version
2.8.2

### OS/Browsers version
谷歌74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
<template>
  <el-table
    :data="tableData"
    height="390">
    <el-table-column
      prop="date"
      label="日期"
      :formatter="formatter"
      width="180">

    </el-table-column>

    
      
      
    
    

  </el-table>
</template>

<script>
  export default {
    name: "tablesss",
    data() {
      return {
        tableData: [
          {
            date: "121232131234",

          }
        ]
      }
    },
    methods: {
      formatter(row, column) {
        console.log("格式化");
        return "124";
      }
    },
    created() {

    }
  }
</script>

<style scoped>

</style>

### What is Expected?
只有一行一列使用格式化方法时，肯定只执行一次格式化

### What is actually happening?
实际上它却执行了两次

**Comment by ivila** [comment]
你是不是有什么列是fixed的？el-table的fixed实现是通过多个table堆叠实现的，所以如果你有存在fixed的column，那就会存在多个table，左边fixed的一个，右边fixed的又一个

**Comment by WanManito** [comment]
> 你是不是有什么列是固定的？EL-表的固定实现是通过多个表堆叠实现的，所以如果你有存在固定的柱，那就会存在多个表，左边固定的一个，右边固定的又一个

并没有，，只有普通的两列，发现有时候它执行了两次

**Comment by ziyoung** [comment]
fixed 2.10
