### ISSUE TITLE
el-date-picker 的 v-model 是否可以设置成字符类型？

### ISSUE THREAD

**Issue by awuliu** [ElemeFE/element#157]
### ElementUI version
1.0.0-rc.4

### OS/Browers version
 win32/Chrome 53 

### Vue version
 2.0.0-rc.6 

### Reproduction Link
[日期测试](https://codepen.io/awuliu/pen/NRjrgx)

### What is Expected?

一般后台传输时会格式化成字符，这样编辑日期时就显示为空了，而且选择日期后 v-model 的值还是 Date 格式，这样保存到服务器还需要重新转换一次，不知道你们是怎么处理这种情况的

**Comment by QingWei-Li** [comment]
合法时间的字符串初始值的问题修复了。

第二个功能不打算加，因为返回的日期字符串要什么格式还需要用户自己指定，那么就还需要一个 format 属性，意义不大。最后发送数据时统一处理一下就好了。

**Comment by awuliu** [comment]
@QingWei-Li 
修复的好快！非常感谢！(-: 

关于第二点，其实日期组件已经有一个 format 属性了，一般情况下提交的值应该是都是以该格式为准的，所以如果可以的话希望以后还是能考虑下统一使用该格式解析和设置对应的 v-model 的值，至于内部可以使用 Date 或 moment 方便时间的计算，只是鄙人拙见!

**Comment by QingWei-Li** [comment]
format 属性只是控制组件上日期的显示格式，返回时间类型适应范围更大些，毕竟有的人想要时间戳右的想要字符串。你可以用 computed 或者 watch 来设置需要的类型

**Comment by awuliu** [comment]
好，非常谢谢！
