### ISSUE TITLE
[Feature Request] Floating labels

### ISSUE THREAD

**Issue by siberiadev** [ElemeFE/element#15706]
### Existing Component
Yes

### Component Name
El-Form

### Description
Hello!
Can you made floating labels for inputs in form?
Floating labels - it's label over inputs, and when user focus on input label goes to the top left corner.

**Comment by huzaifah-ivan** [comment]
+1

**Comment by jonalxh** [comment]
+1

**Comment by sunada-ke** [comment]
+1
