### ISSUE TITLE
[Bug Report] After opening the Dialog, clicking on the browser's return key will result in a cover layer on the page, causing the page to be unable to click.

### ISSUE THREAD

**Issue by beginner-john** [ElemeFE/element#15711]
### Element UI version
2.8.2

### OS/Browsers version
win10/liunx /  Google

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/公司内部使用系统

### Steps to reproduce
在页面上点击打开dialog弹窗,在有弹窗和罩层情况下,点击浏览器的返回键,就会发现罩层还在,页面返回到了上一次点击的页面.并且页面无法点击,只能刷新页面!!  步骤:  打开dialog弹窗 => 点击浏览器返回键
目前是对这个页面 添加浏览器返回键监听事件,在函数中作出处理,参考链接如下:https://blog.csdn.net/bocongbo/article/details/81667054
但是这样需要对每个页面都要处理.这样的方式肯定不对. 

### What is Expected?
如何解决有弹窗返回就会导致不能点击的bug,  或者说是使用dialog的方式不对? 在文档中没有找到对应的解释.

### What is actually happening?
在页面上点击打开dialog弹窗,在有弹窗和罩层情况下,点击浏览器的返回键,就会发现罩层还在,页面返回到了上一次点击的页面.并且页面无法点击,只能刷新页面!!

**Comment by EasonQwQ** [comment]
请问你之后有解决吗？

**Comment by huyong007** [comment]
我今天也被测试提了这个bug,我找到了这个资料还没试[路由守卫](https://jessarcher.com/blog/closing-modals-with-the-back-button-in-a-vue-spa/)

**Comment by huyong007** [comment]
> 请问你之后有解决吗？

[路由守卫](https://router.vuejs.org/guide/advanced/navigation-guards.html)

**Comment by huyong007** [comment]
```js

      :append-to-body="false"
      :destroy-on-close="true"
      :modal-append-to-body="false"
```
