### ISSUE TITLE
HTML comment block displayed in compiled js file.

### ISSUE THREAD

**Issue by lgh06** [ElemeFE/element#1572]
### ElementUI version
1.0.4

### OS/Browers version
macOS 10.11.4/Chrome 55

### Vue version
2.1.0

### Reproduction Link

https://github.com/WeBest-test/testVue/tree/d989ef8c052fb9887aba79a8ee351f34e232a36f/open-lib
### Steps to reproduce

follow the instructions, http://element.eleme.io/#/zh-CN/component/quickstart 
but some HTML comment tag displayed both in dev and production build .

![image](https://cloud.githubusercontent.com/assets/1688639/20916662/d4a9d57c-bbc7-11e6-8e24-2e7d65c30c2d.png)

### What is Expected?
no comment block
### What is actually happening?
donnot know.

**Comment by QingWei-Li** [comment]
This is a feature of Vue 2.0. A placeholder for `v-if`.

**Comment by lgh06** [comment]
I know this feature may not element's fault...i just add an el-button,no ```v-if``` in my code...these tags look ugly... any way to remove them...?thanks...
