### ISSUE TITLE
[Bug Report] Input box cannot be entered after version upgrade

### ISSUE THREAD

**Issue by LxxWL** [ElemeFE/element#15722]
### Element UI version
2.8.2

### OS/Browsers version
window10/Google Chrome  版本 74.0.3729.169（正式版本） （32 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lxxwl/pen/LomGZK?editors=1010

### Steps to reproduce
Input box get focus can't be input

### What is Expected?
Input box input normally

### What is actually happening?
Input box cannot be entered

**Comment by angrybird233** [comment]
I'm also have the same problem, but why ?
