### ISSUE TITLE
[Bug Report] Default expansion solution for tree tables

### ISSUE THREAD

**Issue by chao921125** [ElemeFE/element#15727]
### Element UI version
2.8.2

### OS/Browsers version
windows/chrom

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
Default（默认）

### What is Expected?
Settings can be made by attributes or methods（可以通过属性或者方法设置）

### What is actually happening?
Solution（解决方案）：

Depending on actual needs, put it in the listening event（根据实际需要放到监听事件中）

this.$nextTick(() => {
        const rows = document.querySelectorAll('.el-table__expand-icon')
        console.log(rows)
        rows.forEach((item) => {
          item.click()
        })
      })

**Comment by ziyoung** [comment]
fixed in 2.9.1
