### ISSUE TITLE
[Bug Report] Is it invalid to configure externals?

### ISSUE THREAD

**Issue by hlbj105** [ElemeFE/element#15736]
### Element UI version
2.8.2

### OS/Browsers version
win10，360安全浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen没有连接

### Steps to reproduce
configureWebpack: config => {
    config.name = name
    // config.resolve = {
    //   alias: {
    //     '@': resolve('src')
    //   }
    // }
    config.resolve.alias = {
      '@': resolve('src')
    }
    if (process.env.ENV === 'production') {
      config.externals = {
        'element-ui': 'ELEMENT',
        'axios': 'axios',
        'echarts': 'echarts',
        'vue': 'Vue',
        'vue-router': 'VueRouter',
        'vuex': 'Vuex'
      }
    }
  },
  chainWebpack(config) {
    if (process.env.ENV === 'production') {
      config.plugin('html')
        .tap(args => {
          args[0].cdn = cdn
          return args
        })
    }
}

### What is Expected?
问一下怎么解决？ELEMENT是这个名字吗

### What is actually happening?
问一下怎么解决？ELEMENT是这个名字吗

**Comment by kylin-blue** [comment]
我也遇到同样的问题，版本和你一样，请问这个问题是怎么解决的

**Comment by hlbj105** [comment]
@kylin-blue  我的是由于utils/util.js中import 一个js文件报错，我把它移出去就可以了

**Comment by hlbj105** [comment]
@kylin-blue 好像是可以的，就是这个名字
