### ISSUE TITLE
[Bug Report] Should "v-model" be always included in "el-input"?

### ISSUE THREAD

**Issue by nh0627** [ElemeFE/element#15747]
### Element UI version
2.8.2

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/nh0627/mj41w2ac/3

### Steps to reproduce
If I type anything into el-input without v-model, el-input itself cannot contain any letter.
It seems like el-input always requires a user to declare v-model to use it.

### What is Expected?
A user can use "el-input" without "v-model", in order to available to enter any words even without "v-model".

### What is actually happening?
If there is no "v-model" in "el-input", "el-input" cannot contain any letter.

**Comment by georgyfarniev** [comment]
Why does it make sense to use el-input without value binding?

**Comment by nh0627** [comment]
@georgyfarniev  I mean, I have to render an element with createElement()(https://vuejs.org/v2/guide/render-function.html#createElement-Arguments), but in this case, I cannot use "v-model" as a property of the method. 
Rather than v-model="foo", I have to use other version of syntax, v-bind:value="foo" v-on:input="e => foo = e.target.value", with createElement().

However, el-input seems it does not support v-bind:value="foo" v-on:input="e => foo = e.target.value". 
https://jsfiddle.net/nh0627/mj41w2ac/39/

**Comment by Allenice** [comment]
+ 1, I have a special reason to use.

**Comment by liaoyinglong** [comment]
https://jsfiddle.net/pg4zn0qt/1/

like this?

**Comment by nh0627** [comment]
@liaoyinglong 
Thank you for your answer!
So now, in Element UI, an event($event) of "el-input" is "$event.target.value" in a normal vue app?
Also, why do I have to check a type of input value? Is there any other case than "string" as input value?

**Comment by liaoyinglong** [comment]
@nh0627 

no, just `string`

see the source code 
https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue#L352
https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue#L389


and the `HTMLInputElement` value is also `string`

see  https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L7011

**Comment by nh0627** [comment]
@liaoyinglong Thanks 🙌

**Comment by wacky6** [comment]
`@input` event arg is a string. it differs from native HTML Input Event.

`v-model="value"` is equivalent to `:value="value" @input="handleInput"`

**Comment by watership** [comment]
## Element UI version

2.8.2

## OS/Browsers version

Chrome

## Vue version

2.6.10

`
<template>
    <div>
        <div class="input-wrap">
            <el-input
            class="input-item"
            v-model="inputUsername"
            maxlength="20"
            type="text"
            placeholder="请输入账号">
            </el-input>
        </div>
    </div>
</template>
<script lang="ts">
import { Component, Prop, Vue, Provide, Model } from 'vue-property-decorator'
export default class Login extends Vue {
  inputUsername: string= '333333';
}
</script>
`

Unable to enter
