### ISSUE TITLE
Why doesn't [Feature Request] datepicker have a dateRender-like method that allows you to customize the format of date selection cells?

### ISSUE THREAD

**Issue by sevenCon** [ElemeFE/element#15745]
### Existing Component
Yes

### Component Name
el-datepicker

### Description
why datepicker component do not have a function like dateRender , to customize date grid content?
like follow
![image](https://user-images.githubusercontent.com/13718019/58445739-59695780-8130-11e9-8b79-03a6e1221aac.png)

if so , how do I to add icon or text beside the date grid content ?

**Comment by shady-xia** [comment]
any workaround?
