### ISSUE TITLE
[Bug Report] el-select style dislocation

### ISSUE THREAD

**Issue by sskaps** [ElemeFE/element#15754]
### Element UI version
0.1.0

### OS/Browsers version
window 10 / IE 10/11

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
http://element.eleme.io/#/zh-CN   in this website to select components for select, then to select  el-select component for multiple. (remark: in ie(10/11))

### What is Expected?
resolve style dislocation

### What is actually happening?
display normal

**Comment by cuivip** [comment]
是因为在 packages/theme-chalk/src/select.scss 这文件的 15行 用了ie不兼容的样式吗？
.el-select__tags
    >span {
      display: contents;
    }

我们追查代码发现这个  display:contents 在ie下不支持，会导致下来选择在ie中无法正常显示
