### ISSUE TITLE
[Bug Report] Date Range Picker should not show the month that are not active

### ISSUE THREAD

**Issue by buremba** [ElemeFE/element#15759]
### Element UI version
2.8.2

### OS/Browsers version
Chrome / Mac OS

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/vkg46rfa/

### Steps to reproduce
We do not allow the user to select the date range from the future and we use `disabledDate` to be able to do that. However; `el-date-picker` still shows the next month by default even though none of the days are active in that month. 

### What is Expected?
We should show the previous month if all the values are inactive within a month or provide a way for the user to select the months that are shown in the panel by default.

### What is actually happening?
The component shows the inactive month which is confusing to the end users.

**Comment by wacky6** [comment]
read the doc. use default-value (optionally with unlink-panels) 
https://jsfiddle.net/3jguxhL7/

**Comment by buremba** [comment]
@wacky6  I have read the docs, don't worry. :) It looks like there's a bug which prevents the picker to show the correct months. In my case, when I select the range from the previous month, `default-value` doesn't seem to work. See https://jsfiddle.net/ugmqnapj/
