### ISSUE TITLE
select组件在value=0的时候不显示内容

### ISSUE THREAD

**Issue by featherfly** [ElemeFE/element#1575]
升级到1.0.4出现的这个问题，老版本没这个问题
如果使用绑定语法（数字0）就不显示，使用字面常量则显示出来
&lt;el-option label="代金券" :value="0">&lt;/el-option> 不显示
&lt;el-option label="代金券" value="0">&lt;/el-option> 显示

**Comment by Leopoldthecoder** [comment]
与 #1570 重复。
