### ISSUE TITLE
关于input的slot=“append”内部样式的问题

### ISSUE THREAD

**Issue by AK47-dadada** [ElemeFE/element#15756]
不清楚你们为什么会设置为背景是灰色，如果input框配置slot为append的时候，放入按钮之后还要自己重新写一遍el-input-group__prepend和el-input .el-input-group__append的样式，如果背景色不手动设置为transparent的话，背景永远都是灰色（因为这里已经被覆盖了），建议留一点扩展的余地，这样可能效果会更好一些，slot也会更有意义一点。

**Comment by AK47-dadada** [comment]
搞不懂，建议不听。You guys are a ridiculous team

**Comment by joey998** [comment]
这个确实好烦，是不是你issue格式不对？

**Comment by traceless0929** [comment]
是真的很坑爹
