### ISSUE TITLE
[Bug Report] el-table tree table

### ISSUE THREAD

**Issue by WanManito** [ElemeFE/element#15758]
### Element UI version
2.8.2

### OS/Browsers version
Google Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
设置el-table 树形表格固定高度，，不出现滚动条，而在项目热加载之后或者浏览器右键检查缩小界面窗体才出现，，，，，还有建议树形表格加入默认全部展开或者默认全部折叠，，或者指定关闭与折叠。。。。。

### What is Expected?
设置固定高之后超出高度内容应出现滚动条，，，，期待树形表格加入默认全部展开或者默认全部折叠，，或者指定关闭与折叠。。。。。

### What is actually happening?
未出现滚动条。。。。。。。。。。。。

**Comment by ziyoung** [comment]
fixed in 2.9.1
