### ISSUE TITLE
The last line of the first page rendered incorrectly when the height of the [Bug Report] el-table content exceeded the height set by the table

### ISSUE THREAD

**Issue by middleHallo** [ElemeFE/element#15768]
### Element UI version
2.8.2

### OS/Browsers version
chrome 69.0.3497.81

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/15767

### Steps to reproduce
1、给el-table 的class设置固定高度  height:300px;over-flow:auto；

2、然后内容总高度超过table高度，

3、最后一行渲染出错

### What is Expected?
最后一行只有1条分割线

### What is actually happening?
最后一行只有2条分割线

**Comment by ziyoung** [comment]
试试 2.9.1
