### ISSUE TITLE
[Feature Request] The component of element: the close callback is confused to me

### ISSUE THREAD

**Issue by xuyuntian** [ElemeFE/element#15766]
### Existing Component
是

### Component Name
el-dialog

### Description
This is  some part of demo
```
 <el-button size="mini" @click="preView(scope.row.actualName)">预览</el-button>

<el-dialog :visible.sync="showPreview"  append-to-body :close="close()">
      <video :src="preViewVedio" width="350px" height="250px" controls controlsList="nodownload"></video>
</el-dialog>

close(){
          this.preViewVedio = "";
          window.console.log("closed");
        },
  preView(name){
           window.console.log("open");
           this.showPreview = true;
           this.preViewVedio = this.$common.parseVedio(name);
}
```
when i open the dialog.
which console log are:
```
open
close
close
```
why this element calback colse twice when I open it?

**Comment by xuyuntian** [comment]
我想吐槽这是神吗特性？

**Comment by xuyuntian** [comment]
my version is "element-ui": "^2.4.5", if any heigher version fixed this I will colose this issue.

**Comment by wacky6** [comment]
Why don't you go back and learn vue basics before complaining about what's wrong with element-ui?

`:close="close()"` -> `@close="close"`

**Comment by xuyuntian** [comment]
I got it ,thank you
