### ISSUE TITLE
[Feature Request] el-link loading

### ISSUE THREAD

**Issue by suguoyao** [ElemeFE/element#15763]
### Existing Component
Yes

### Component Name
el-link

### Description
Hi,
Is there a way to set loading attribute to display loading status just like el-button?
Thanks.

**Comment by suguoyao** [comment]
![chrome-capture](https://user-images.githubusercontent.com/16471605/58846113-aa3cfb00-86b0-11e9-8de7-faca48b26bc0.gif)
Hope to achieve the effect like this 😆

**Comment by liub1934** [comment]
Do it like this
https://codepen.io/anon/pen/rgRjZK
