### ISSUE TITLE
el-tab-pane里的loading隐藏问题

### ISSUE THREAD

**Issue by LianyForWeb** [ElemeFE/element#1576]
#非当前页的el-tab-pane的Loading不会隐藏 出现在页面左上角

**Comment by Leopoldthecoder** [comment]
没有重现问题：http://jsfiddle.net/leopoldthecuber/4hz5b0pw/ ，所以请提供 demo

**Comment by Leopoldthecoder** [comment]
超过七天没有反馈的 issue 会被关闭。如果可以提供 demo，请再打开。
