### ISSUE TITLE
[Bug Report] tabel table jitter problem

### ISSUE THREAD

**Issue by Tianyazz** [ElemeFE/element#15771]
### Element UI version
2.8.2

### OS/Browsers version
任何浏览器

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
创建一个表格，浏览器出现滚动条，当浏览器宽度变化到刚好失去滚动条时，表单的宽度计算为失去滚动条后的宽度，此时情况又出现了滚动条，然后又重新计算宽度，得到的宽度又失去滚动条。无限循环，导致页面不停抖动

### What is Expected?
在浏览器宽度在滚动条刚好丢失出现的极限情况下，表单宽度只计算一次，不要抖动

### What is actually happening?
在浏览器宽度在滚动条刚好丢失出现的极限情况下，由于滚动条出现丢失，不停的计算宽度，导致页面不停的抖动

**Comment by zzzgit** [comment]
el-table 中確實有這個問題，我這裡也能重現

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
