### ISSUE TITLE
[Bug Report] sort-method not working in version 2.8.2

### ISSUE THREAD

**Issue by prem-singh-1** [ElemeFE/element#15773]
### Element UI version
2.8.2

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/ympt69o8/1/

### Steps to reproduce
See jsfiddle.

### What is Expected?
Sort should work.

### What is actually happening?
looks like it is using only n-1 comparisons where n is the size of the array.

**Comment by qingdengyue** [comment]
```
 test: function(a,b){
     return a.age-b.age
 }
```

result of test mehod should be a number.
