### ISSUE TITLE
[Bug Report] introduced an error in line 78 of element-ui.d.ts, version 2.9.0

### ISSUE THREAD

**Issue by VirensCn** [ElemeFE/element#15788]
### Element UI version
2.9.0

### OS/Browsers version
Windos10 / chromium 69

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/types/element-ui.d.ts

### Steps to reproduce
使用TS环境

### What is Expected?
https://github.com/ElemeFE/element/blob/dev/types/infiniteScroll.d.ts 中应有ElInfiniteScroll。

### What is actually happening?
ERROR in F:/vue/ccqlk-ludeng/node_modules/element-ui/types/element-ui.d.ts
78:10 Module '"./infiniteScroll"' has no exported member 'ElInfiniteScroll'.
    76 | import { ElImage } from './image'
    77 | import { ElBacktop } from './backtop'
  > 78 | import { ElInfiniteScroll } from './infiniteScroll'
       |          ^
    79 | import { ElPageHeader } from './page-header'
    80 | 
    81 | export interface InstallationOptions {

**Comment by Maple13** [comment]
是的, 我也遇到了

**Comment by Misaka-0x447f** [comment]
This is what exactly I meet.

**Comment by Misaka-0x447f** [comment]
Temporary workaround:
```
/** InfiniteScroll Directive */
export const InfiniteScroll: any;
```
Then:
```
PS> npm i -D patch-package
PS> npx patch-package element-ui
```
And: 
```
package.yaml(?)
script
    postinstall |
        patch-package
```
