### ISSUE TITLE
[Bug Report] 表单设置 label-position="left" 失效

### ISSUE THREAD

**Issue by skyzhao1223** [ElemeFE/element#15781]
### Element UI version
2.8.2

### OS/Browsers version
macOS 10.14.6 Beta (18G29g) / Chrome 74.0.3729.169（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/skyzhao1223/pen/qGJXeM

### Steps to reproduce
在 form 表单上设置 inline 为 true，label-width 为 auto 的时候，如果设置 label-position 为 left 则 left 属性不会生效。

### What is Expected?
相同条件下，设置 label-position 为 left 标签应左对齐

### What is actually happening?
相同条件下，设置 label-position 为 left 标签对齐方式为右对齐

**Comment by junyiz** [comment]
If set to 'left' or 'right', label-width prop is also required

**Comment by skyzhao1223** [comment]
> If set to 'left' or 'right', label-width prop is also required

I've set label-width to 'auto', isn't that being required?

**Comment by gcloutier** [comment]
Element is overriding my prop label-position="left" even tho label-width have been set.
