### ISSUE TITLE
[Bug Report] <el-input v-model.trim="input"> 无法在连续输入时 输入空格

### ISSUE THREAD

**Issue by Deeeeeee** [ElemeFE/element#15789]
### Element UI version
2.8.2

### OS/Browsers version
macOS 10.14.3 / Chrome  74.0.3729.157（正式版本） （64 位）

### Vue version
2.5.3

### Reproduction Link
https://codepen.io/anon/pen/eaPMaN?&editable=true

### Steps to reproduce
连续输入时无法输入空格
造成有空格的字符串无法输入
例如 'vue no.1' 无法正常输入，只能输入成 'vueno.1'
只有将光标移到字符串中间 才能输入空格

### What is Expected?
光标在末尾时可以输入空格

### What is actually happening?
光标在末尾时无法输入空格

**Comment by qingdengyue** [comment]
> v-model.trim

就是这样的啊。

**Comment by Deeeeeee** [comment]
> > v-model.trim
> 
> 就是这样的啊。

2.4 版本 和 2.8.2 版本 交互明显不一样，2.4版本更合理

trim 是去除首尾空格，但应该是在blur 时去除吧。 现在是根本无法输入空格，这应该有本质区别。

**Comment by rlweb** [comment]
I've checked all versions with your code pen down to 2.5 and the trim functionality has not worked since then :/

**Comment by Dragon-Rider** [comment]
这真的是一个问题啊，不该就这么关了 @Deeeeeee

**Comment by Deeeeeee** [comment]
@Dragon-Rider 官方文档有写 在 el-input 中 不支持 .trim 修饰符（虽然旧版可以用，但新版用就有问题）。所以也没办法，我们自己在el-input 的基础上又封装了一层。 其实像 .trim 这么常见的功能 官方应该提供一下的。
![image](https://user-images.githubusercontent.com/14084787/67820816-b610da00-faf5-11e9-8775-2b11ea5dc1a8.png)

**Comment by codingories** [comment]
I find this solution by google. https://github.com/dzc314/v-input-trim/tree/master.
npm: https://www.npmjs.com/package/v-input-trim
