### ISSUE TITLE
[Bug Report] DatePicker 日期选择器， 当 format="yyyy年MM月dd日 HH时mm分" 显示异常

### ISSUE THREAD

**Issue by huanghuixin1** [ElemeFE/element#15791]
### Element UI version
2.9.0

### OS/Browsers version
windows10 / chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/huanghuixin1/pen/pmxVgo

### Steps to reproduce
1.设置 `type='datetime' `   
2.设置 `format=‘yyyy年MM月dd日 HH时mm分'`   
3.随便选择一个日期，此时左上方的日期和时间框将分别显示形如： `2019年05月14日分`、`日 00时00分`   

### What is Expected?
左上方的日期和时间框将分别显示形如： `2019年05月14日`、`00时00分`

### What is actually happening?
将会多出一些多余的字符 如 `日分`

**Comment by huanghuixin1** [comment]
请问当前问题是否为bug？ 还是我自己的问题？

**Comment by willbibi** [comment]
同样遇到类型的问题，
1.设置`type='datetime'`
2.设置`format="yyyy-MM-dd HH:00:00"`
最后日期的时间框就 变成`2019-07-26:00:00`，
看了下fix 代码，extractDateFormat 里正则没有把时间部分过滤

**Comment by zhanggaofengw** [comment]
> 请问当前问题是否为bug？ 还是我自己的问题？
我也遇到这个问题 设置format=‘yyyy年MM月dd日 HH:mm'， 时间框显示‘日 00:00’
这个问题有解决吗

**Comment by wenlisu** [comment]
我也是

**Comment by ysneo** [comment]
这个bug一直有啊，2023还没修复 
😂
