### ISSUE TITLE
[Bug Report] input(type="text") property `show-word-limit` container css height 33px  in small size el-form

### ISSUE THREAD

**Issue by diveDylan** [ElemeFE/element#15795]
### Element UI version
2.8.2

### OS/Browsers version
MACOS

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/dylan921208/pen/NVOLbV?&editable=true

### Steps to reproduce
see as u open the url. make sure type of input is 'text'

### What is Expected?
expected normal css behaviour. span.el-input__suffix height get 32px

### What is actually happening?
span,el-input__suffix  get 33px

**Comment by dylan921208** [comment]
.el-form-item--small .el-input--small .el-input__count-inner {
  height: 29px;
}

**Comment by daibingbing** [comment]
seem to question ,haha
