### ISSUE TITLE
2.9.1 table components set height to 100% cause some problem 

### ISSUE THREAD

**Issue by yklhello** [ElemeFE/element#15806]
### Element UI version
2.9.1

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ykl/pen/eaQWpR

### Steps to reproduce
set height to 100% in component el-table
open any browser to see the height become 100px
surprise~

### What is Expected?
the actual height become 100%

### What is actually happening?
the actual height become 100px

**Comment by Lanseria** [comment]
it also cause. if set table height to `calc(100vh - 260px)`

**Comment by zhangruinian** [comment]
same problem now
I solve it with 
```
<el-table style="height: calc(100vh - 225px); overflow: auto;">
```

**Comment by Yancy1028** [comment]
same problem now
waiting

**Comment by zhangruinian** [comment]
想设置响应式table高度 超过出现滚动条...现在全得修改 郁闷呀

**Comment by zhangruinian** [comment]
之前项目的height:100%全失效了
![image](https://user-images.githubusercontent.com/9652856/58680210-5cb34c00-8399-11e9-8110-8683e09539ea.png)

**Comment by askart** [comment]
using 2.7.2 everything is ok there

**Comment by zhangruinian** [comment]
using 2.9.0 everything is ok there

**Comment by ggwork** [comment]
give the el-table parent node a height, then  give  the el-table a samller height  then set the el-table min-height 100%;
like this  [min-height100%](https://codepen.io/guoxianqiang/pen/OeyBJZ?&editable=true)

**Comment by victorpfm** [comment]
> using 2.9.0 everything is ok there

Downgraded from 2.9.1 to 2.9.0 and it's OK now.

**Comment by ziyoung** [comment]
提了一个 pr #16013  大家可以帮忙 review

**Comment by Zerocjx** [comment]
### Version
```js
"element-ui": "^2.13.1",
"vue": "^2.5.16"
```
### Solution
`height="100%"` works for me
```js
<el-table
    :data="tableData"
    height="100%"
    border
    style="width: 100%">
```

**Comment by Rehtt97** [comment]
> give the el-table parent node a height, then give the el-table a samller height then set the el-table min-height 100%;
> like this [min-height100%](https://codepen.io/guoxianqiang/pen/OeyBJZ?&editable=true)

这个方法有用！
