### ISSUE TITLE
表单验证如何自定义规则？

### ISSUE THREAD

**Issue by Leungkingman** [ElemeFE/element#1580]
rules里面的type属性包括哪些类型？如果要自定义规则该如何扩展？

**Comment by QingWei-Li** [comment]
https://github.com/yiminghe/async-validator

**Comment by liyongleihf2006** [comment]
我这两天也恰好遇到了扩展element-ui表单验证规则的需求，我翻看了下源代码发现官方没有提供自定义验证规则的办法，只能通过将async-validator源代码放到项目中并重构一下el-form-item来实现，我也顺便解决了一下表单输入项验证以前需要trim一下的问题，这是我写的[demo](https://github.com/liyongleihf2006/extended-elementui-validation-demo),具体步骤在readme中有写，希望能够帮助同样有这个需求的同学
