### ISSUE TITLE
[Bug Report] The table children data has changed but the view does not change

### ISSUE THREAD

**Issue by cangjingge** [ElemeFE/element#15800]
### Element UI version
2.9.0

### OS/Browsers version
win10/google  74.0.3729.169  （32 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/cangjingge/pen/gJBqWp

### Steps to reproduce
add a children item to table data

### What is Expected?
The table children data has changed the view can change too

### What is actually happening?
The table children data has changed but the view does not change

**Comment by NO-MAP** [comment]
我也遇到了这个问题，目前通过
 this.tableData = JSON.parse(JSON.stringify(this.tableData)) 
这种方式去重新渲染整个数据

**Comment by qingdengyue** [comment]
cc @NO-MAP @cangjingge 2.9.1已修复 
https://github.com/ElemeFE/element/pull/15803#issuecomment-498097855
