### ISSUE TITLE
[Bug Report] Cannot find name 'PluginObject'.

### ISSUE THREAD

**Issue by malkovDanik** [ElemeFE/element#15802]
### Element UI version
2.9.1

### OS/Browsers version
Chrome/win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Danik_codepenIO/pen/gyMQry

### Steps to reproduce
build 2.9.1

### What is Expected?
no error

### What is actually happening?
Need add to element-ui/types/element-ui.d.ts
import Vue, { PluginObject } from 'vue'

**Comment by zfha** [comment]
Is this fixed?

**Comment by malkovDanik** [comment]
Don't fix in master branch ¯ \ _ (ツ) _ / ¯

**Comment by frederick-wang** [comment]
It's not fixed now.

**Comment by guoooofu** [comment]
It's not fixed

**Comment by xiaoxing598** [comment]
It's not fixed now.

**Comment by xiaoxing598** [comment]
If you want to fix this problem yourself, you can try this:
1. Open the `node_modules/element-ui/types/element-ui.d.ts` file and modify the first line of content
2. `import Vue from 'vue'` is modified to `import Vue, {PluginObject} from 'vue'`

**Comment by zfha** [comment]
> If you want to fix this problem yourself, you can try this:
> 
> 1. Open the `node_modules/element-ui/types/element-ui.d.ts` file and modify the first line of content
> 2. `import Vue from 'vue'` is modified to `import Vue, {PluginObject} from 'vue'`

I do it now. But it will redo when you rerun 'npm install'.

**Comment by xiaoxing598** [comment]
I did not find that the file was re-covered in the hot load mode. This problem will eventually be fixed by the official.

**Comment by malkovDanik** [comment]
@WaSheep when you will merge to master branch??

**Comment by zhongqc** [comment]
When could you release a new version with this issue fixed?

**Comment by ositowang** [comment]
facing the same error here. Is there any update for this bug?

**Comment by mrpinkcat** [comment]
Same error for me

**Comment by XiaYuYing** [comment]
Still got this error after  `npm i` , when i use it in a `ts` project, version: `^2.6.1` and `2.9.1`. 
Is there any solutions or help ?

**Comment by malkovDanik** [comment]
> Still got this error after `npm i` , when i use it in a `ts` project, version: `^2.6.1` and `2.9.1`.
> Is there any solutions or help ?

Use verdaccio
