### ISSUE TITLE
Can [Feature Request] [Form Verification] el-form rules locate el-form-items that failed to validate

### ISSUE THREAD

**Issue by edwards19900128** [ElemeFE/element#15804]
### Existing Component
是

### Component Name
el-form

### Description
使用场景是一个非常长的表单填写，可能出现会需要出现滚动条等，
在rulues验证时候希望能够获取出错的$ref通过scrollIntoView或者直接通过参数定位过去就更好了.

或者还有其他奇淫巧技望交流。

**Comment by lzyllp** [comment]
this.$refs[formName].$el.querySelector('.is-error').scrollIntoView()

**Comment by edwards19900128** [comment]
> this.$refs[formName].$el.querySelector('.is-error').scrollIntoView()

非常有效~感谢大神
