### ISSUE TITLE
[Bug Report] infiniteScroll in official document is not working

### ISSUE THREAD

**Issue by leozzyzheng** [ElemeFE/element#15816]
### Element UI version
2.9.1

### OS/Browsers version
windows7/ chrome 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/mYQpoa

### Steps to reproduce
Run the sample code in offical document site, or directly click the "Try it!" on the document site: https://element.eleme.io/#/en-US/component/infiniteScroll

### What is Expected?
I could see the list and scroll down

### What is actually happening?
Nothing show in screen and there is the error message in console:
```
"[Vue warn]: Error in directive infinite-scroll inserted hook: 'TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.'
```

**Comment by leozzyzheng** [comment]
Any updates?

**Comment by duyngha** [comment]
Got the same issue with infinite scroll component. Anybody can help? Thanks.

**Comment by leozzyzheng** [comment]
Fixed in 2.11.0

**Comment by leozzyzheng** [comment]
See https://github.com/ElemeFE/element/pull/16698/files#diff-27caed56f87e34abfd7561c620d9bcf2R10
just lost `style="overflow:auto"` on `ul` tag, it works in 2.9.1.

**Comment by leozzyzheng** [comment]
#16698
