### ISSUE TITLE
[Bug Report] el-select >In some cases, modifying its disable attribute changes the height style

### ISSUE THREAD

**Issue by Finyu** [ElemeFE/element#15818]
### Element UI version
2.8.2

### OS/Browsers version
window7/Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/PvxQKw?&editable=true

### Steps to reproduce
Add the parent node p to the select component, give it the lineHeight attribute of 50px, and then modify the disable attribute of the select, 

### What is Expected?
Select height unchanged

### What is actually happening?
you will find that the height of the select has changed to 50px,

**Comment by noxxxxxxxx** [comment]
### Element UI version
2.8.2

### OS/Browsers version
window7/Chrome

### Vue version
2.6.10
### Reproduction Link
https://codepen.io/hjoker/pen/PrqRvp

use `size="small"` and `:disabled="test === 1"` in select component , if variable `test` value change in the Promise or setTimeout function, `size="small"` will be useless.

**Comment by ziyoung** [comment]
fixed in #15989
