### ISSUE TITLE
[Feature Request] Table Fixed Column Problem

### ISSUE THREAD

**Issue by yanglei2012** [ElemeFE/element#15812]
### Existing Component
是

### Component Name
table

### Description
1、table 设置总宽度为1000px ;共有10列 每列width设置为90px；
2、那么应该还有100px；element-ui table直接不渲染后面的100px了；
3、但是最后100px其实是存在的。
改进建议：
这种情况下，希望可以做到 正常渲染1000px 后面的100px表头和其他列一样正常渲染。列的分隔线一样渲染。

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
