### ISSUE TITLE
[Bug Report] the select component is selected multiple times and the value binding value is an object, the default value is given, the option value is an empty array, and the input box shows no text, only empty el-tag.

### ISSUE THREAD

**Issue by limianhust** [ElemeFE/element#15824]
### Element UI version
2.9.1

### OS/Browsers version
chrome74.0

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/q7t8epk0/

### Steps to reproduce
链接里已经重现，打开就是。select组件在多选时，且value绑定值为对象时，给value默认值，option值为空数组，输入框没有显示文字，只有空的el-tag。

### What is Expected?
默认值应该显示完整的文字，即label

### What is actually happening?
显示空的el-tag

**Comment by NMNguyen** [comment]
@limianhust 
Are you have a solution to resolve this ???

**Comment by limianhust** [comment]
> @limianhust
> Are you have a solution to resolve this ???

yes,I modified the source code, packaged and compiled before use.

**Comment by NMNguyen** [comment]
> > @limianhust
> > Are you have a solution to resolve this ???
> 
> yes,I modified the source code, packaged and compiled before use.

Thank for your reply.
Can you explain more about "modified the source code", pls?

**Comment by limianhust** [comment]
> > > @limianhust
> > > Are you have a solution to resolve this ???
> > 
> > 
> > yes,I modified the source code, packaged and compiled before use.
> 
> Thank for your reply.
> Can you explain more about "modified the source code", pls?

Select.vue under the packages folder。I can send the folder for Email。please leave Email。

**Comment by NMNguyen** [comment]
> Select.vue under the packages folder。I can send the folder for Email

Please send it to "nguyennguyenit14@gmail.com".
Thks you ^^.

**Comment by limianhust** [comment]
> > Select.vue under the packages folder。I can send the folder for Email
> 
> Please send it to "[nguyennguyenit14@gmail.com](mailto:nguyennguyenit14@gmail.com)".
> Thks you ^^.
sorry,I cannot use my email in my compony ,here is my github modified.
[https://github.com/limianhust/element-UI-BugFix/commit/fe06e06bc6a2cdd9458e5614a14a99500397c208](https://github.com/limianhust/element-UI-BugFix/commit/fe06e06bc6a2cdd9458e5614a14a99500397c208)

**Comment by NMNguyen** [comment]
> > > Select.vue under the packages folder。I can send the folder for Email
> > 
> > 
> > Please send it to "[nguyennguyenit14@gmail.com](mailto:nguyennguyenit14@gmail.com)".
> > Thks you ^^.
> > sorry,I cannot use my email in my compony ,here is my github modified.
> > [limianhust/element-UI-BugFix@fe06e06](https://github.com/limianhust/element-UI-BugFix/commit/fe06e06bc6a2cdd9458e5614a14a99500397c208)

**Comment by NMNguyen** [comment]
> > > Select.vue under the packages folder。I can send the folder for Email
> > 
> > 
> > Please send it to "[nguyennguyenit14@gmail.com](mailto:nguyennguyenit14@gmail.com)".
> > Thks you ^^.
> > sorry,I cannot use my email in my compony ,here is my github modified.
> > [limianhust/element-UI-BugFix@fe06e06](https://github.com/limianhust/element-UI-BugFix/commit/fe06e06bc6a2cdd9458e5614a14a99500397c208)

I have fork "element-ui" to my GitHub and I install it with a github clone link.
But, it not working. Can you help me install it?
<img width="371" alt="Screen Shot 2019-06-17 at 5 08 05 PM" src="https://user-images.githubusercontent.com/30466047/59596742-7e932980-9122-11e9-8ada-1284936a225b.png">

**Comment by limianhust** [comment]
> > > > Select.vue under the packages folder。I can send the folder for Email
> > > 
> > > 
> > > Please send it to "[nguyennguyenit14@gmail.com](mailto:nguyennguyenit14@gmail.com)".
> > > Thks you ^^.
> > > sorry,I cannot use my email in my compony ,here is my github modified.
> > > [limianhust/element-UI-BugFix@fe06e06](https://github.com/limianhust/element-UI-BugFix/commit/fe06e06bc6a2cdd9458e5614a14a99500397c208)
> 
> I have fork "element-ui" to my GitHub and I install it with a github clone link.
> But, it not working. Can you help me install it?
> <img alt="Screen Shot 2019-06-17 at 5 08 05 PM" width="371" src="https://user-images.githubusercontent.com/30466047/59596742-7e932980-9122-11e9-8ada-1284936a225b.png">

npm run dist，and put lib folder into node_modules in element

**Comment by Lynn-cc** [comment]
我有一个临时解决方案，当初始化的时候，把待选列表初始化为和value一样的列表，然后再nextTick设置成空就可以正常显示tag了。
