### ISSUE TITLE
radio-group事件

### ISSUE THREAD

**Issue by xiaofeiapis** [ElemeFE/element#1582]
Radio 单选框组件可否支持click事件：  在绑定值发生改变之前做一些逻辑处理，目前貌似只提供了change

**Comment by QingWei-Li** [comment]
`click.native`

**Comment by xiaofeiapis** [comment]
我的适用场景是点击radio之前进行逻辑判断，满足条件点击选中，不满足的话不选中。
click.native是可以绑定，但是由于radio组件是基于label标签封装的，所以click事件会触发两次，并且不管我在click中是否return掉，当前dadio还是会被选中

**Comment by QingWei-Li** [comment]
prevent？ 麻烦给个 demo

**Comment by xiaofeiapis** [comment]
已解决，在点击事件里面条件不满足的时候，重置了绑定值，多谢
