### ISSUE TITLE
[Bug Report] has just been upgraded to 2.9.1 table height

### ISSUE THREAD

**Issue by ccwud** [ElemeFE/element#15832]
### Element UI version
2.9.1

### OS/Browsers version
win10/Google Chrome74.0.3729.169（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ccwud/pen/wbQQmp

### Steps to reproduce
1.创建一个table 
2. <el-table
      :data="tableData"
      height="75vh">,配置table得高度,然后发现没有用了,
3.我在2.82版本是可以使用得

### What is Expected?
希望table中得height支持得单位有      vh或者%

### What is actually happening?
因为需要不同得显示屏,显示,所有希望支持 这些单位

**Comment by ziyoung** [comment]
see #15806
