### ISSUE TITLE
[Feature Request] suggest remove el-column component, then el-table add a array prop'columns'

### ISSUE THREAD

**Issue by ling1900** [ElemeFE/element#15834]
### Existing Component
是

### Component Name
ELTABLE

### Description
建议移除 ELColumn 组件，而使用 JavaScript 数组的形式来指定列，即给 ELTABLE 添加一个 columns 属性作为列的定义。
这样的好处有：
1，使用 JavaScript 数组方式来定义 columns ，书写上比 html/xml 的标签语言更简洁，且可以利用 JavaScript 的编程能力。
2，用户利用 JavaScript 的编程能力，后续还可以继续对 columns 数组进行变换，从而调整列的顺序，列的可见性等。
3，如果需要对列的单元格进行自定义渲染，则在 el-table 的 default slot 中，书写 <template v-slot:loginName> <template v-slot:userStatus> 。

**Comment by lzyllp** [comment]
定个个数组 用v-for 渲染column组件不是一样？

**Comment by ling1900** [comment]
1，既然已经用数组和 v-for ，那么 el-column 就已经没有存在的意义。这时 el-column 标签本身，已经不含业务定制的信息，既然不含业务定制的信息，为何还要书写？
2，现在 el-column 所做的工作，其实也是收集列信息，并转成列定义对象给到 table store 的 列定义数组。如果一开始就直接使用数组，那么 el-column 所做的工作就可以简化甚至免除。

**Comment by ziyoung** [comment]
Vue 绝大多数情况都推荐使用 template。对一些简单的场景，如果使用配置的话，使用 columns 更方便。

**Comment by winkay** [comment]
意思是类似iView和ant design的table风格？

**Comment by ansonhorse** [comment]
其实不少字段都可以直接配置化渲染，而复杂一点的，可以使用template。
如果el本身就提供这样的支持，实在是一大利好！
