### ISSUE TITLE
[Bug Report] in table components, When the data's parent set'hasChildren: true', the child will not be able to display

### ISSUE THREAD

**Issue by chungkui** [ElemeFE/element#15833]
### Element UI version
2.9.1

### OS/Browsers version
win10/Google Chrome version 74.0.3729.169 (32 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/cangjingge/pen/VOVVBK

### Steps to reproduce
parent setting 'hasChildren:true' 

### What is Expected?
When the data's parent setting 'hasChildren:true' ，the child can show

### What is actually happening?
When the data's parent setting 'hasChildren:true' ，the child will not be able to display

**Comment by lshz0088** [comment]
I also have this problem.

HasChildren property error when lazy loading is not used.

I hope to solve this problem as soon as possible And thank you.

**Comment by justyeh** [comment]
Do not use the hasChildren and children attributes at the same time
in your case,delete hasChildren attributes
