### ISSUE TITLE
[Bug Report] row-style property is invalid at initialization time. elementui 2.9.1 is not fix.

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#15849]
### Element UI version
2.9.1

### OS/Browsers version
MAC OS 10.14 / Google Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/panhezeng/pen/byzBBP

### Steps to reproduce
用官方最基本的示例就能重现。
设置:row-style="getRowStyle"
methods: {
// 每行的样式
getRowStyle({ row }) {
return { display: "none" };
}
}
没有隐藏行。看生成代码， tr上面出现了style，但是值为空。
2.7.0之前的版本是好的。

### What is Expected?
设置:row-style="getRowStyle"
methods: {
// 每行的样式
getRowStyle({ row }) {
return { display: "none" };
}
}
隐藏行

### What is actually happening?
没有隐藏行。

**Comment by yyjjqq94** [comment]
use row-class-name

**Comment by panhezeng** [comment]
> use row-class-name

Thanks，I temporarily use cell-style to achieve the same effect, My situation cannot be in the way of class name.

多谢，我暂时使用cell-style实现相同效果，我那个项目的情况不能用class name的方式，因为不能另外写css文件。

**Comment by pansila** [comment]
我也碰到同样的问题，而且display设为其它值，比如table-row，是可以apply的，似乎就none不行

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/16048#issuecomment-513730705
