### ISSUE TITLE
[Bug Report] custom placeholder [focus & valid]

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [ElemeFE/element#15841]
### Element UI version
2.9.1

### OS/Browsers version
Elementary Os Juno , chromium v73

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mIcHyAmRaNe/f9zkupmx/14/

### Steps to reproduce
- adding a simple el-input with a placeholder,
- then adding this stylesheet 
```
.el-input__inner::placeholder {
  position: absolute;
  top: 0;
  padding: 7px 0 0 13px;
  transition: all 200ms;
  opacity: 0.5;
  color: red;
}
.el-input:focus   .el-input__inner::placeholder,
.el-input:valid   .el-input__inner::placeholder {
  font-size: 75%;
  transform: translate3d(0, -100%, 0);
  opacity: 1;
}
```

### What is Expected?
- floating placeholder ^^
- that the placeholder go up when we select the input box like in this codepen example: https://codepen.io/peiche/pen/xOVpPo (blog post: https://dev.to/peiche/css-only-floating-label-3cp )

### What is actually happening?
nothing worked

but

if i remplace
 ```
.el-input:focus   .el-input__inner::placeholder,
.el-input:valid   .el-input__inner::placeholder
```  
with:
```
.el-input:active .el-input__inner::placeholder
```
and then test it by clicking on the input box it works but it's not what i want, 

what i want is that it works with focus & valid :/

**Comment by Yurich84** [comment]
Does anyone know how solve this problem?
