### ISSUE TITLE
The Height Attribute Problem of [Bug Report] Table

### ISSUE THREAD

**Issue by AiMe1991** [ElemeFE/element#15858]
### Element UI version
2.9.1

### OS/Browsers version
windos10/Google Chrome版本 73.0.3683.86（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/aime1991/pen/arXpyP

### Steps to reproduce
<el-table
    :data="tableData"
    border
    height="100%"
    style="width: 100%">
其中height设置为100%，但是在实际的页面中显示的是100px。
在版本2.5.4中这样设置，在实际页面中显示的是100%。

### What is Expected?
height设置为100%时，在实际页面中应该是 100%；和版本2.5.4保持一直。

### What is actually happening?
height设置为100%时，在实际页面中是100px

**Comment by yuan-xiaogang** [comment]
I also encountered the same problem. Is there a solution?

**Comment by AiMe1991** [comment]
版本降级，降到2.9.0就可以了

**Comment by AiMe1991** [comment]
> I also encountered the same problem. Is there a solution?

版本降级，降到2.9.0就可以了

**Comment by yuan-xiaogang** [comment]
我已经降级处理了，有啥比较实用的锁定版本号的方案？我使用package-lock.json未生效

**Comment by AiMe1991** [comment]
> 我已经降级处理了，有啥比较实用的锁定版本号的方案？我使用package-lock.json未生效

删除package-lock.json，在package.json中这样写"element-ui": "2.9.0", 然后再npm install

**Comment by TY-LIU** [comment]
我刚刚升级也发现这个问题了，
height="100%"会渲染成100px
@ziyoung

**Comment by AiMe1991** [comment]
> 我刚刚升级也发现这个问题了，
> height="100%"会渲染成100px
> @ziyoung

删除package-lock.json，在package.json中这样写"element-ui": "2.9.0", 然后再npm install

**Comment by TY-LIU** [comment]
> > 我刚刚升级也发现这个问题了，
> > height="100%"会渲染成100px
> > @ziyoung
> 
> 删除package-lock.json，在package.json中这样写"element-ui": "2.9.0", 然后再npm install

`npm i element-ui@2.9.0 `
这样写也可以的哟老铁，不用删json文件，重新下所有包太慢了

**Comment by ziyoung** [comment]
类似 issue #15806

**Comment by jinghui70** [comment]
上一个版本的实现是好的：
```
    if (typeof value === 'number') {
      el.style[prop] = value + 'px';

      this.updateElsHeight();
    } else if (typeof value === 'string') {
      el.style[prop] = value;
      this.updateElsHeight();
    }
```

**Comment by ziyoung** [comment]
提了一个 pr #16013 大家可以帮忙 review
