### ISSUE TITLE
[Bug Report] Cascader cascade selector displays values that are not consistent with the actual selected median

### ISSUE THREAD

**Issue by huoerica** [ElemeFE/element#15854]
### Element UI version
2.9.1

### OS/Browsers version
Windows 64

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/huoerica/pen/ZNwLGa

### Steps to reproduce
1，选中 [ "2号厂区", "C区" ]，
2，选中[ "3号厂区", "B区" ]，

### What is Expected?
1，显示[ "2号厂区", "C区" ]，实际[ "2号厂区", "C区" ]
2，显示[ "3号厂区", "B区" ]，实际[ "3号厂区", "B区" ]

### What is actually happening?
1，显示[ "2号厂区", "C区" ]，实际[ "2号厂区", "C区" ]
2，显示[ "2号厂区", "B区" ]，实际[ "3号厂区", "B区" ]

**Comment by jessonxiang** [comment]
我发现只要是同一级上面有相同的value 只会显示第一次出现的value
我做城市选择的时候 选择的 广东省 深圳市 南山区  结果显示的是 黑龙江省 鹤山市 南山区
![image](https://user-images.githubusercontent.com/24713249/58774569-b5325580-85f4-11e9-9eb8-6b62c0a83031.png)

**Comment by thomasschiet** [comment]
The problem only seems to occur when the `value` property of the children is not unique.
