### ISSUE TITLE
[Bug Report] Cascader radio mode model binding assigns values to data elements in a computed attribute setter

### ISSUE THREAD

**Issue by bichengg** [ElemeFE/element#15862]
### Element UI version
2.9.1

### OS/Browsers version
win10 chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/BeMRmg

### Steps to reproduce
Cascader 单选模式下  model绑定以个计算属性 setter里赋值给data里元素, 从二级菜单开始 在选择具体选项时 radio 高亮需要点2下

### What is Expected?
点一下 radio高亮

### What is actually happening?
从二级菜单开始，点2下 radio高亮

**Comment by SimonaliaChen** [comment]
这不是组件的问题，是因为你写的计算属性引起的。
如果想做到demo中的效果，可以使用 `props.emitPath`, 参考 https://codepen.io/simonaliachen/pen/mNwMMG

**Comment by SimonaliaChen** [comment]
这不是组件的问题，是因为你写的计算属性引起的。
如果想做到demo中的效果，可以使用 props.emitPath, 参考 https://codepen.io/simonaliachen/pen/mNwMMG
