### ISSUE TITLE
[Bug Report] table: Multiple select 

### ISSUE THREAD

**Issue by elpsycongroo** [ElemeFE/element#15861]
### Element UI version
2.9.1

### OS/Browsers version
Win10/Chromium 69.0

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/qGgmdX

### Steps to reproduce
1. Bind the 'select' event on a multiple select table.
2. Click the 'TOGGLE!' button, it will call table's function:  'toggleRowSelection()'
3. The function triggers the 'select' event which is not called manually. Because there's an alert dialog showed.

### What is Expected?
The 'select' event only triggers when USER clicks the checkbox in a row in the version 2.6.3.
Any function call (e.g.: toggleRowSelection()) SHOULD NOT trigger this event.

### What is actually happening?
Call MultipleTable's function: 'toggleRowSelection()' will trigger its 'select' event in version 2.9.1.

**Comment by mtlswz** [comment]
我也遇到了 目前只能将版本回退到2.8才能正常
