### ISSUE TITLE
selection-change 获取选中的json数据的id

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1586]
通过selection-change事件来获取选中的数据，但是获取的数据是整个json对象的所有内容，现在只需要获取选中的id，请问如何实现？

**Comment by Kingwl** [comment]
...

**Comment by Leopoldthecoder** [comment]
你所谓的 `id` 是指？

**Comment by yuanshengchao** [comment]
准确来说，是获取选中数据的的某一列的数据

**Comment by yuanshengchao** [comment]
比如官方文档中我只想获取table中select选中的name值到。如下红色部分。
![image](https://cloud.githubusercontent.com/assets/16740731/20956007/41c612be-bc82-11e6-8cec-0164625f596e.png)

**Comment by Leopoldthecoder** [comment]
`val.map(item => item.name)`？

**Comment by ericwangzheng** [comment]
怎么获取选中行的index呢？
