### ISSUE TITLE
Export all types 

### ISSUE THREAD

**Issue by eakarpov** [ElemeFE/element#15878]
### Existing Component
Yes

### Component Name
Every component

### Description
Export all types for manage parameters passed to components. For example, ElTree is exported as ElementUI.Tree, but type TreeNode that is used inside it is not exported and no way to use it in your application to validate params.

**Comment by island205** [comment]
TreeNode first

**Comment by WaSheep** [comment]
related #5934

**Comment by JeremyWuuuuu** [comment]
@eakarpov you can actually importing types by:
```typescript
import { TreeNode } from 'element-ui/types/tree';
```

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
