### ISSUE TITLE
Table translation issue with vue-i18n

### ISSUE THREAD

**Issue by HashemQolami** [ElemeFE/element#1587]
### ElementUI version
1.0.5

### OS/Browers version
Ubuntu 16.04 / Chrome 51

### Vue version
2.1.4

### Reproduction Link
https://jsfiddle.net/9wywequ5/

### Steps to reproduce
Click the `Switch Language` button.

### What is Expected?
Messages should respond to the current locale. In this case the English translation should be displayed.

### What is actually happening?
The `emptyText` message is not responding to the current locale, using `vue-i18n` plugin.

**Comment by Leopoldthecoder** [comment]
Thanks. PR merged.
