### ISSUE TITLE
[Bug Report] Change date type before the date picker popper hides, the layout will be messy.

### ISSUE THREAD

**Issue by JoweiBlog** [ElemeFE/element#15873]
### Element UI version
2.9.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jowei/pen/qGgpjb

### Steps to reproduce
1. Click the `el-date-picker`.

2. Choose another type before the date picker popper hides.

3. Click the `el-date-picker` again, the ui layout will be messy.

### What is Expected?
 The date picker popper should be destoryed, the layout is normal. 

### What is actually happening?
layout confusion.

**Comment by ziyoung** [comment]
You can set key for `el-date-picker`.
```
  <el-date-picker
    v-model="dateVal"
    :type="type"
    :key="type">
  </el-date-picker>
```
