### ISSUE TITLE
[Bug Report] Cascader's lazyload how to dynamic update data?

### ISSUE THREAD

**Issue by Wizzercn** [ElemeFE/element#15874]
### Element UI version
2.9.1

### OS/Browsers version
Windows 10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wizzercn/pen/GazxEJ

### Steps to reproduce
How to update the data of cascade selector dynamically when creating successful or deleting sub-units when managing the organizational tree of a unit, such as creating sub-units for the current unit and selecting parent units through cascade selector?
【请问，在对单位组织树进行管理的时候，比如为当前单位创建子单位，通过级联选择器选择父级单位，如何在创建成功时（或删除子单位）让级联选择器的数据动态更新？】

I don't know who designed the dynamic loading mechanism of cascade selector. Haven't we considered the problem of data updating? Why can't we design a method instead of a data object?
【不知道这个级联选择器动态加载机制是谁设计的，难道没考虑过数据更新问题么，为什么不能设计为方法，而设计为数据对象？】

---------------------------------------------------------------------
https://github.com/Wizzercn/NutzWk/blob/v5.x/wk-app/wk-nb-web-vue/src/main/resources/views/platform/sys/unit/index.html

```
 <el-cascader
                        style="width: 100%"
                        tabindex="1"
                        :options="options"
                        :show-all-levels="false"
                        v-model="parentUnit"
                        :fetch-suggestions="unitQuery"
                        @active-item-change="unitChange"
                        @change="unitChange2"
                        @select="unitSelect"
                        placeholder="不选择则为顶级"
                ></el-cascader>
```

Above is the previous way to load data dynamically. Although the amount of code is large, it can achieve functions somehow.
【上面是之前实现动态加载数据的方式，虽然代码量比较多，但好歹能实现功能。】

### What is Expected?
Please give me a way to update the data without refreshing the page.

### What is actually happening?
I want to update cascading data dynamically.

**Comment by aa43a** [comment]
the same question

**Comment by island205** [comment]
pr welcome

**Comment by Wizzercn** [comment]
@aa43a @island205 
配置options属性，然后将options置空后可以触发 lazyload 重新加载，结贴，撒花。

**Comment by peade** [comment]
> @aa43a @island205
> 配置options属性，然后将options置空后可以触发 lazyload 重新加载，结贴，撒花。

给你点个赞，我查了一天，最后在你这里找到了解决方法！
