### ISSUE TITLE
Formter Method in [Bug Report] el-table

### ISSUE THREAD

**Issue by WanManito** [ElemeFE/element#15871]
### Element UI version
2.9.1

### OS/Browsers version
Google Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
当我只写两列，其中一列使用了formatter方法，在此方法中打印，发现执行两次。。。

### What is Expected?
只执行一次

### What is actually happening?
执行了两次
![image](https://user-images.githubusercontent.com/26118508/58789549-fe000380-8620-11e9-9f62-3e52e1e6dabd.png)

**Comment by WanManito** [comment]
两次打印触发版本是2.8.2，我切换到2.9.1打印了三次。。。

**Comment by ziyoung** [comment]
比 2.8 确实多了不必要的渲染。排查中。

**Comment by ziyoung** [comment]
fixed in 2.10.1

**Comment by DiclZYY** [comment]
> fixed in 2.10.1

You are right,this bug had been triggered when mouse enter or leave the row of table in v2.7.0.
But, column will still render twice in v2.10.1, if you set the column attr 'formatter' like this `fomatterTest(row,column,value,index) {console.log('column value and index, value, index)}`
