### ISSUE TITLE
[Bug Report] el-scrollbar bug

### ISSUE THREAD

**Issue by Sliect** [ElemeFE/element#15879]
### Element UI version
2.4.5

### OS/Browsers version
windows10/chrome73

### Vue version
2.6.10

### Reproduction Link
https://github.com/Sliect/element-bug-scrollbar

### Steps to reproduce
npm i & npm run serve
将滚动条滑倒底部,缩放浏览器
放大 el-scrollbar 元素的高度会导致滑块无法滚动到底部
缩小 el-scrollbar 元素的高度会导致滑块滑倒底部时部分不可见

### What is Expected?
el-scrollbar 正常显示

### What is actually happening?
放大 el-scrollbar 元素的高度会导致滑块无法滚动到底部
缩小 el-scrollbar 元素的高度会导致滑块滑倒底部时部分不可见

**Comment by Lanseria** [comment]
2.8.2 still!

**Comment by Sliect** [comment]
2.9.1 应该也存在这个问题，我用vue-cli3和vue-cli-plugin-element 搭建的，所以element版本较低

**Comment by Sliect** [comment]
还有滚动条在wrap尺寸变化的时候消失/显示也有问题

**Comment by island205** [comment]
Sorry, we have no plan to support this.

**Comment by Sliect** [comment]
通过监听iframe 的resize事件可以解决，已经在垂直方向上通过指令解决以上问题

**Comment by HydrogenPan19** [comment]
写了一个 wrapper 组件，调用 el 内部的方法来处理，比较简洁

https://gist.github.com/HydrogenPan19/2d1fce5a0cb7f2a9af38065721a49ba5

**Comment by Sliect** [comment]
嗯，你这个方法优雅多了！

**Comment by Ray0401** [comment]
> 通过监听iframe 的resize事件可以解决，已经在垂直方向上通过指令解决以上问题

请问你是怎么解决的？
