### ISSUE TITLE
[Bug Report] When the table component el-table-column is fixed, the el-popover V-model in the custom template can't pop up or disappear after popping up.

### ISSUE THREAD

**Issue by liub1934** [ElemeFE/element#15872]
### Element UI version
2.9.1

### OS/Browsers version
win10/Chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/arXqjV

### Steps to reproduce
日期的el-table-column设置了fixed，popover设置了v-model，点击姓名列的按钮，popover无法弹出，在我另一个项目中是弹出后就一闪就没了，目前猜想是设置fixed后生成了多个表格，导致点击按钮后popover弹出，事件又冒泡到下面的按钮，导致popover又消失了。
取消掉fixed后一切正常。

### What is Expected?
popover正确弹出

### What is actually happening?
popover无法弹出

**Comment by island205** [comment]
This is indeed a `el-table`'s bug, because having Shared `visible` data will cause multiple tables  to modify this data with each other. Limited to the current implementation of `el-table`, temporarily unable to repair. Thanks for the feedback.

**Comment by nadirvishun** [comment]
参考这个[el-table中某个el-table-column使用了fixed属性以后，template中的popover不工作？](https://github.com/ElemeFE/element/issues/3332#issuecomment-362213788)，改为触发方式` trigger="manual"`可勉强解决。
