### ISSUE TITLE
[Bug Report] table table is fixed in both horizontal and vertical directions, adding data dynamically. The number of rows in the unfixed position is correct, and the number of rows in the fixed position is missing.

### ISSUE THREAD

**Issue by Wpfsxauer** [ElemeFE/element#15875]
### Element UI version
2.8.2

### OS/Browsers version
 chrome 73.0.3683.86

### Vue version
2.5.22

### Reproduction Link
https://codepen.io/anon/pen/xNMWJB

### Steps to reproduce
table加min-height，然后第一列第二列加fiexd，动态添加数据后，已添加fixed的表格没有正常渲染，而未添加fixed的表格正常渲染，应该是高度不一致导致。导致未添加fiexd的列比已添加fixed的列多一行，从而未添加fixed的列多出纵向滚动条。

### What is Expected?
添加fixed列的数据正常渲染。

### What is actually happening?
添加fixed列的数据未正常渲染（确认高度问题导致，加magintop解决，但是样式会很难看）。

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
