### ISSUE TITLE
[Bug Report] tree-table reload data but all expaned list does not recover  close status，as a direct result of my lazyload data can't reload

### ISSUE THREAD

**Issue by syrxw** [ElemeFE/element#15883]
### Element UI version
2.9.1

### OS/Browsers version
MacOS 10.14.6beta / Chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Jacobwang/pen/XwGdLa

### Steps to reproduce
1. expand a list
2. click the `add` button
3. the `tableData1` data will be reload

### What is Expected?
I want the data to reload when I click the `add` button , the `expanded` `loaded` status can be reset

### What is actually happening?
in the version 2.7.2,it could do what I wanted，but in the version 2.9.1, when i click `add` button,nothing happened to the tree table，this caused my lazy load list to fail to refresh again

**Comment by ziyoung** [comment]
目前会将状态进行一次合并。

**Comment by ziyoung** [comment]
related issue #15201

**Comment by Wizzercn** [comment]
@ziyoung 2.10.0 版本问题并没有得到修复啊？增加或删除子级，treetable并没有更新数据，在2.8.2不存在这个问题，到了2.9.2出现bug有人提这个issue，没得到修复为什么关闭issue？
