### ISSUE TITLE
[Feature Request] Cascader cascade selector gets the selected label value

### ISSUE THREAD

**Issue by linweikang** [ElemeFE/element#15887]
### Existing Component
Yes

### Component Name
2.9.1

### Description
Google浏览器68.0.3440.84

Cascader 级联选择器获取选中的label值得问题，2.7.2版本可以通过this.$refs['cascaderAddr'].currentLabels方法获取，更新后该方法失效。

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by SimonaliaChen** [comment]
`currentLabels` is not public api, u can use `getCheckedNodes` to get the checked labels.
