### ISSUE TITLE
When the [Bug Report] el-select component clicks on a drop-down box, the high probability of a serious jump occurs.

### ISSUE THREAD

**Issue by pengsamkee** [ElemeFE/element#15884]
### Element UI version
2.9.1

### OS/Browsers version
win7专业版sp1 / Google Chrome 版本 74.0.3729.169（正式版本） （64 位）

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/anon/pen/gJEwBX?&editable=true#anon-login

### Steps to reproduce
点击el-select组件，出现下拉框的时候会高概率出现跳动。神奇的是，我提供的codepen的例子并不会出现，但是在官方文档上，也同样出现相同问题，地址是https://element.eleme.cn/#/zh-CN/component/select

### What is Expected?
每次出现的效果一致

### What is actually happening?
有时候正常，有时候会出现跳动

**Comment by island205** [comment]
Duplicate of #15888
