### ISSUE TITLE
[Bug Report] el-select pull-down jitter phenomenon

### ISSUE THREAD

**Issue by liub1934** [ElemeFE/element#15888]
### Element UI version
2.9.1

### OS/Browsers version
win10/Chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/mYoRve

### Steps to reproduce
select有抖动现象，官网的有抖动，codepen中运行却是正常的
![demo26](https://user-images.githubusercontent.com/29849550/58847160-7bc11f00-86b4-11e9-9cac-b30c70d43fa6.gif)
![demo25](https://user-images.githubusercontent.com/29849550/58847164-811e6980-86b4-11e9-93a3-03ef34d6706c.gif)

### What is Expected?
select无抖动

### What is actually happening?
select有抖动

**Comment by pengsamkee** [comment]
我也遇到这个情况了，貌似新版本的浏览器才会出现？

**Comment by zicong-zhang** [comment]
我这也是这个问题
Element-ui：v2.7.2
Chrome: 74.0.3729.169（正式版本） （64 位）

**Comment by pengsamkee** [comment]
更新Chrome之后，各种奇奇怪怪的问题啊

**Comment by infjer** [comment]
+1

Element UI version：2.4.11
OS/Browsers version：MacOs Majove 10.14.5/Chrome 74
Vue version：2.6.10
在正常点击展开select时，有较高概率(约50%)复现。且即使没有发生抖动，往下展开的动画似乎并没有发生，而是直接闪现的。

Element UI version：2.9.1
OS/Browsers version：Win 7
在官网select组件进行测试，搜狗浏览器v7.5及v8.5中几乎无法复现抖动，也能较为容易地看到下拉展开动画；在Chrome 74中，较难复现抖动现象，较高概率能看到下拉展开几乎是瞬间闪现的，无过渡动画效果。

**Comment by PengSama** [comment]
出现同样问题，
chrome 版本 74.0.3729.169（正式版本） （64 位）
element-ui：2.9.1

**Comment by island205** [comment]
This maybe chrome bug

**Comment by pingmalu** [comment]
> This maybe chrome bug

关闭chrome硬件加速后，问题消失

**Comment by eterXing** [comment]
我是重新启动chrome硬件加速就没问题了。。

**Comment by chairui2001** [comment]
经测试，在父级存在overflow时，在会出现该现象，而级联选择器却没有这个问题，求解~

**Comment by huisnotacouncillor** [comment]
关闭chrome硬件加速，浏览器放大到110%， 也会出现抖动， 但是放大到125%， 150%，175%，200%不会出现

chrome 版本 81.0.4044.138（正式版本） （64 位）
element-ui 版本 2.13.1
