### ISSUE TITLE
[Bug Report] DateTime Picker jitter

### ISSUE THREAD

**Issue by WanManito** [ElemeFE/element#15892]
### Element UI version
2.9.1

### OS/Browsers version
Google Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
点击官网的这个组件，大多数的时候出现下滑展开抖动，，极少数平滑向下展开

### What is Expected?
不抖动。。平滑展开

### What is actually happening?
抖动

**Comment by WaSheep** [comment]
Sorry, we have no plan to support this
