### ISSUE TITLE
el-button的loading属性只接受boolean吗?（表达式无法生效）

### ISSUE THREAD

**Issue by 0604hx** [ElemeFE/element#1589]
### ElementUI version
1.0.4

### OS/Browers version
electron 1.4.10 内置Chrome

### Vue version
2.1.1

### Steps to reproduce
el-button定义如下：
``` html
<el-button @click="check($index,row)" size="mini" title="检查一下此主机是否网络连通" :loading="{true:loading}">ping</el-button>
```

### What is Expected?
想要通过`loading`的值来改变button的加载状态

### What is actually happening?
:loading无法实现button状态的维护，提示：
```
[Vue warn]: Invalid prop: type check failed for prop "loading". Expected Boolean, got Object. 
(found in component <ElButton>)
```

**Comment by Kingwl** [comment]
:loading="!!loading"

**Comment by Leopoldthecoder** [comment]
你这种写法是一个对象而不是一个表达式，请参照楼上的写法。或者，如果你的 `loading` 是一个布尔值，那么直接 `:loading="loading"` 也可以。
