### ISSUE TITLE
[Bug Report] Could not show correctly when using Grouping table head

### ISSUE THREAD

**Issue by moonose** [ElemeFE/element#15891]
### Element UI version
2.9.1

### OS/Browsers version
Google Chrome  74.0.3729.169 64bit

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/moonose/pen/oRVBEV

### Steps to reproduce
When I use Grouping table head, the column cannot be shown correctly.
first, I have to set the width for the head,<el-table-column fixed width="400">, or it cannot be shown correctly.
second, if I set the width, the other column which is over width cannot be shown.

### What is Expected?
the column value can be shown correctly

### What is actually happening?
If the column without setting the width for the head, it cannot be shown correctly.
if width is set to be a value, the other column which over the width cannot be shown.

**Comment by ziyoung** [comment]
When I use Vue 2.5.22, the result is different. Could please provide a simple demo? I don't know what's going wrong.

**Comment by ziyoung** [comment]
Don't use table element in table-column component.

**Comment by moonose** [comment]
Is it possible to provide a solution to make elements combine with a table?
