### ISSUE TITLE
求教大神如何在本地搭建element环境（有命令行步骤），谢谢！！！

### ISSUE THREAD

**Issue by zhongxiaopang** [ElemeFE/element#159]
按照官网以及github上的命令行实现报错了！！！急求解决办法！！！
![1](https://cloud.githubusercontent.com/assets/18260026/18859434/94892928-84a6-11e6-9824-6611bf17d2bb.PNG)

**Comment by QingWei-Li** [comment]
git 命令行工具安装了么

**Comment by zhongxiaopang** [comment]
安装了git了，就是想知道项目的目录结构不是有严格要求的吧？还有就是运行npm run bootstrap会报错？不知道具体的步骤很蒙蔽的赶脚！！！

**Comment by QingWei-Li** [comment]
git 有的话就不会报 `Command fail` 了。安装子项目里的依赖是 lerna 做的。有问题的话请到 Gitter 里咨询 http://gitter.im/ElemeFE/element
