### ISSUE TITLE
[Bug Report] target is not existing:.Page-component__scroll

### ISSUE THREAD

**Issue by wangxinqiang** [ElemeFE/element#15909]
### Element UI version
2.9.1

### OS/Browsers version
win10 chrome74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/RmdLYY?editors=1111

### Steps to reproduce
见重现链接 element-ui 2.9.1

### What is Expected?
现在<el-backtop target=".page-component__scroll .el-scrollbar__wrap"></el-backtop>，没法使用

### What is actually happening?
现在<el-backtop target=".page-component__scroll .el-scrollbar__wrap"></el-backtop>，没法使用

**Comment by Loyoan** [comment]
一样的问题。
`[Vue warn]: Error in mounted hook: "Error: target is not existed: .page-component__scroll .el-scrollbar__wrap"`
`Error: target is not existed: .page-component__scroll .el-scrollbar__wrap`

**Comment by mybouhssina** [comment]
problem still here...
