### ISSUE TITLE
[Bug Report] vue-cli3 babel-plugin-component PluginObject < ElInfiniteScroll > Cannot find name'PluginObject'

### ISSUE THREAD

**Issue by lh8725473** [ElemeFE/element#15918]
### Element UI version
2.9.1

### OS/Browsers version
MacOS 10.14.6beta / Chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Jacobwang/pen/XwGdLa

### Steps to reproduce
module.exports = {
  "presets": [
    "@vue/app"
  ],
  "plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
}

### What is Expected?
ERROR in /Users/liuhao/sjdevice/node_modules/element-ui/types/element-ui.d.ts
331:30 Cannot find name 'PluginObject'.
    329 | 
    330 | /** InfiniteScroll Directive */
  > 331 | export const InfiniteScroll: PluginObject<ElInfiniteScroll>;
        |                              ^
    332 | 
    333 | /** PageHeader Component */
    334 | export class PageHeader extends ElPageHeader {}

### What is actually happening?
Cannot find name 'PluginObject'.
注释掉这一行就好了

**Comment by neeeekto** [comment]
As a workaround , add the type Declaration file and attach it to tsconfig
```ts
type PluginFunction<T> = (Vue: any, options?: T) => void;

interface PluginObject<T> {
  install: PluginFunction<T>;
  [key: string]: any;
}
```

**Comment by zhuyunhe** [comment]
> As a workaround , add the type Declaration file and attach it to tsconfig
> 
> ```ts
> type PluginFunction<T> = (Vue: any, options?: T) => void;
> 
> interface PluginObject<T> {
>   install: PluginFunction<T>;
>   [key: string]: any;
> }
> ```

it works, thank u

**Comment by eakarpov** [comment]
Are there any achievements around this?
