### ISSUE TITLE
el-table use current-row-key

### ISSUE THREAD

**Issue by happy0402** [ElemeFE/element#15910]
### Existing Component
Yes

### Component Name
el-table

### Description
I set the attribute of el-table but nothing happened.And I had read source code,there is no place to use this attribute.What is the meaning of this attribute ?

**Comment by ziyoung** [comment]
请提供 demo。

**Comment by happy0402** [comment]
<template>
    <el-table
                ref="table"
                :data="tableData"
		row-key="userId"
                :current-row-key="2"
                stripe
                highlight-current-row>
        <el-table-column
                prop="date"
                label="日期"
                width="180">
        </el-table-column>
        <el-table-column
                prop="name"
                label="姓名"
                width="180">
        </el-table-column>
        <el-table-column
                prop="address"
                label="地址"
                show-overflow-tooltip>
        </el-table-column>
    </el-table>
</template>

<script>
    export default {
        data() {
          return {
            tableData: [{
                date: '2016-05-03',
                userId: 1,
                name: '王小虎',
                address: '上海市普陀区金沙江路 1518 弄'
            }, {
                date: '2016-05-02',
                userId: 2,
                name: '王小虎',
                address: '上海市普陀区金沙江路 1518 弄'
            }, {
                date: '2016-05-04',
                userId: 3,
                name: '王小虎',
                address: '上海市普陀区金沙江路 1518 弄'
            }]
          }
        }
  }
</script>

**Comment by island205** [comment]
@happy0402 https://codepen.io/island205/pen/VONWYd 在这里提供

**Comment by happy0402** [comment]
https://codepen.io/happy0402/pen/ZNNexR 这样给的吗？我只是想问下current-row-key的作用是什么，在highlight-current-row的情况下没有选中行
