### ISSUE TITLE
[Feature Request] Events in which input components are expected to provide keyboard return keys

### ISSUE THREAD

**Issue by zhentonglee** [ElemeFE/element#15911]
### Existing Component
是

### Component Name
el-input

### Description
input组件提供键盘回车键的事件是很有必要的，没有该事件用户体验真的很不好，望接纳。

**Comment by island205** [comment]
你为什么需要需要这个事件？

**Comment by zhentonglee** [comment]
> Why do you need this event?

在pc端，用户输入完文本之后，执行下一步操作时，很自然按回车键来触发下一步的操作，比如：
![image](https://user-images.githubusercontent.com/15976432/58863682-e3439280-86e5-11e9-9c22-1bba3eadc529.png)
不需要点击搜索按钮，直接回车即可。

**Comment by FEjohnny** [comment]
顶一下，貌似现在也还没有
