### ISSUE TITLE
[Bug Report] toggleRowSelection can not select after data initialized

### ISSUE THREAD

**Issue by oyljerry** [ElemeFE/element#15929]
### Element UI version
2.8.0

### OS/Browsers version
Windows 10, Chrome 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/LovLVQ

### Steps to reproduce
1. Load table data in mounted function.
2. Use toggleRowSelection to check some item.

### What is Expected?
The related row selection is checked.

### What is actually happening?
The related row selection is NOT checked.

**Comment by oyljerry** [comment]
Sorry, I should use nextTick to update UI.

**Comment by ArthurAtamuradov** [comment]
> Sorry, I should use nextTick to update UI.
Hi, how did you use that to solve the problem?
