### ISSUE TITLE
[Feature Request] Dark/light Theme switch support

### ISSUE THREAD

**Issue by Janglee123** [ElemeFE/element#15921]
### Existing Component
No

### Component Name
None

### Description
just like other UI libraries, it is nice to have the light/dark theme support.

**Comment by qingdengyue** [comment]
有自定义主题功能  
https://elementui.github.io/theme-chalk-preview/#/zh-CN

**Comment by hamedbaatour** [comment]
@qingdengyue how are we supposed to dynamically swtich back and forth between a light and a dark theme when the user clicks on a switch for example:
![1](https://user-images.githubusercontent.com/5658460/59158072-8cf79a80-8abd-11e9-9740-254be81de768.gif)

is there a way I can have a `element-variables.scss` and another one called `element-dark-variables.scss` and switch dynamically between them?

**Comment by island205** [comment]
Sorry, we have no plan to support this.

有在线主题编辑器：https://element.eleme.cn/#/zh-CN/component/custom-theme
