### ISSUE TITLE
[Feature Request] table 是否可以添加 ”导出EXCEL” 的方法 ？

### ISSUE THREAD

**Issue by xmwgp8** [ElemeFE/element#15930]
### Existing Component
是

### Component Name
TABLE

### Description
table 是否可以添加 ”导出EXCEL” 的方法 ？

**Comment by CarterLi** [comment]
添加excel操作库会显著增加element打包体积，导出excel交给后端做就好了，何况这类情况往往都要考虑分页

**Comment by xmwgp8** [comment]
体积的增加问题，可以按需引用。
添加一个这样的方法，有时候还是会方便很多的，即使简单的把已显示的页面数据导出。
应该还是有很多的场景会用到。

**Comment by shalldie** [comment]
这功能不应该集成到element中，，，

否则接下来还有 `pdf导出`，`转换成图片导出`，`导出要png还要压缩到最小体积` 等奇怪的需求

**Comment by xmwgp8** [comment]
Table 组件，如果能有导出excel ， 这个需求应该是比较普遍的。

**Comment by StephenSeraph** [comment]
我也很想要这个功能，因为几乎所有的项目中，客户都会有这样的要求，但道理上来说，这个确实不属于Element的功能范围。
Element的定位是UI组件库，而导出excel是纯功能性的东西，跟UI没有半毛钱关系。
我这边是我们自己封了一个这样的函数库，有现成的开源库，没啥难度。

**Comment by ziyoung** [comment]
@StephenSeraph 可以把思路分享给大家。😄

**Comment by ShuiPingYang** [comment]
导出数据的功能后台实现更好，几行代码的事情。
