### ISSUE TITLE
[Select]远程搜索时，当value为对象时，选中后视图有bug

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1593]
#### v1.0.5， select组件， 远程搜索时，当value为对象时，选中后视图有bug

> v1.04是没这个问题的

设置了mutiple   [demo1](http://jsfiddle.net/ivan403704409/xkmznhm1/)
没设置mutiple   [demo2](http://jsfiddle.net/ivan403704409/dmgvt11b/)

**Comment by Leopoldthecoder** [comment]
Fixed in #1606
