### ISSUE TITLE
[Feature Request] change `before-upload` behavior

### ISSUE THREAD

**Issue by fisker** [ElemeFE/element#15939]
### Existing Component
是

### Component Name
upload

### Description
I was using a function to prevent upload，code like this

```js
onBeforeUpload() {
  doSomthingBeforeUpload()
  return false
}
```

then one-day `doSomthingBeforeUpload` became a promise

```js
async onBeforeUpload() {
  await doSomthingBeforeUpload()
  return false
}
```

this won't stop the upload, because this function actually resolves with `false`, not rejected, so I have to throw an error in `doSomthingBeforeUpload` or onBeforeUpload.

I read the code https://github.com/ElemeFE/element/blob/1afce457e7a2ab3d5be83d0fc1973722ff6ba87f/packages/upload/src/upload.vue#L93-L111 and know that we thread `Blob` as a new upload file, and other values will upload the original file

Here is my propose: treat Promise&lt;false&gt; as a signal to prevent upload, I think it's better and will not break many use-cases.

If it's ok, I can make a pr to make this change

**Comment by fisker** [comment]
@ziyoung ping

**Comment by island205** [comment]
async onBeforeUpload() {
  await doSomthingBeforeUpload()
  return Promise.reject() // false
}

**Comment by fisker** [comment]
@island205 

island205 I still think my solution makes this much easier to use, image you have more than just a `doSomthingBeforeUpload` function but many lines with return false

Should we at least discuss?
