### ISSUE TITLE
[Bug Report] The height of the Table does not support ‘vh’

### ISSUE THREAD

**Issue by johnlanliu** [ElemeFE/element#15946]
### Element UI version
2.9.1

### OS/Browsers version
Version 65.0.3325.181 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/JohnLan/pen/zQQZqa?&editable=true

### Steps to reproduce
The height of the Table does not support ‘vh’

### What is Expected?
Support vh like the previous version

### What is actually happening?
2.9.1
source code:
packages/table/src/table-layout.js  line:62
el.style[prop] = `${value}px`;

2.8.2
source code:
packages/table/src/table-layout.js  line:67
el.style[prop] = value;

**Comment by ziyoung** [comment]
Duplicate of #15858
