### ISSUE TITLE
[Bug Report] table component expands row function to report props error

### ISSUE THREAD

**Issue by qianzhangsheng** [ElemeFE/element#15947]
### Element UI version
2.6.3

### OS/Browsers version
macOS 10.14.5/chrome 74.0.3729.169

### Vue version
2.5.13

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
就是把官方的例子复制到项目里，就报错了
```
[Vue warn]: Property or method "props" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

### What is Expected?
可以正常显示

### What is actually happening?
报错，无法显示table包括展开项

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
