### ISSUE TITLE
[Feature Request] Diaog adds the destroyOnClose property and destroys subcomponents when dialog closes

### ISSUE THREAD

**Issue by agileago** [ElemeFE/element#15949]
### Existing Component
是

### Component Name
Dialog

### Description
场景： 把表单封装成一个组件(包含dialog), 表单的model是在data里面初始化的，避免修改原始数据，在未点保存的情况下关闭弹窗，下次再打开弹窗时希望是原始数据，等于重新把dialog下面的子组件重新初始化一遍，要不然还要去把 model重新赋一下原始值，清理一下表单校验结果等各种操作，希望增加 destroyOnClose 属性，在弹窗动画关闭后清理掉子组件，打开的时候重新 render子组件， `vue-ant-design`的`modal`组件已实现这个功能， [https://vue.ant.design/components/modal-cn/#API](https://vue.ant.design/components/modal-cn/#API)

**Comment by FlareStone** [comment]
Popover和Tooltip也有同样的问题
