### ISSUE TITLE
[Feature Request] Cascader 级联选择器 checkStrictly 

### ISSUE THREAD

**Issue by 1142338114** [ElemeFE/element#15951]
![image](https://user-images.githubusercontent.com/35951066/59010666-9f2acc00-8864-11e9-9ac7-c05b7f6275eb.png)
![image](https://user-images.githubusercontent.com/35951066/59010694-b49ff600-8864-11e9-8b65-204ec0796121.png)
两个里面都有 当选择下132的emp1005就会选中23432

**Comment by 1142338114** [comment]
![image](https://user-images.githubusercontent.com/35951066/59010740-e913b200-8864-11e9-8f06-97abcc5d5297.png)
选择不了132的emp1005

**Comment by guohuihot** [comment]
这个功能问题很多，都不敢升级，
