### ISSUE TITLE
[Bug Report] Upload component has a space row below the image i upload when i use "picture-card" list type

### ISSUE THREAD

**Issue by tinggg12345** [ElemeFE/element#15954]
### Element UI version
2.9.1

### OS/Browsers version
win10/chrome74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1.Upload a image.
2.A space row will show below the image you upload.
3.Delete the image you upload.
4.The space row gone.

### What is Expected?
Whether I uploaded or not,the component has the same height.

### What is actually happening?
The component got greater height after I upload a image

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
