### ISSUE TITLE
[bug] reserve-selection and row-key func 的功能在新的2.9.1版本失效了

### ISSUE THREAD

**Issue by BanZhuanWang** [ElemeFE/element#15955]

**Comment by ziyoung** [comment]
issue 链接：http://jsrun.net/NeyKp/edit

**Comment by zimuZhao** [comment]
mark

**Comment by xyyVee** [comment]
所以fix的版本是2.10.0 ? 我在2.12.0中好像也不行，跑接口之后set了一个id给表格每一条数据，加了row-key和:reserve-selection="true"，但是分页过后还是没有记住前一页的数据
