### ISSUE TITLE
The page cannot be refreshed after the [Bug Report] tree component modifies the disabled of the node

### ISSUE THREAD

**Issue by djkdeveloper** [ElemeFE/element#15957]
### Element UI version
2.9.1

### OS/Browsers version
mac/74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
总体功能，tree组件中选中的节点只要被选中后下次打开就不能被选中，然后如果删除选中节点对应的数据，则该节点下次又可以被选中
思路：选中节点的时候设置节点的disabled为true
删除节点的时候根据key获得node 然后设置node的disabled为false

### What is Expected?
1.选中的时候设置节点的disabled 为true  下次打开tree 不能选中
2.删除节点对应的数据，下次打开tree的时候节点可以选中

### What is actually happening?
可以正确使用的场景：打开tree选中节点，然后删除节点，在打开tree 看到节点为可选状态
不可以正确使用的场景，打开tree选中节点，然后再打开tree，之前选中的节点不能选中，然后删除节点的数据，再打开tree 看到的节点是不可选状态，但是通过vuex 看数据disabled是false

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
