### ISSUE TITLE
[Bug Report] el-option V-for binds key to NaN, causing a dead cycle

### ISSUE THREAD

**Issue by minikey** [ElemeFE/element#15953]
### Element UI version
2.9.1

### OS/Browsers version
MacOS

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/h3txeyvn/2/

### Steps to reproduce
点击按钮，浏览器就会失去相应

### What is Expected?
能正常渲染页面，但抛出错误

### What is actually happening?
页面出现死循环，浏览器失去响应

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by mjsong07** [comment]
可以给出具体的原因吗？这个问题确实很致命

**Comment by xiachaoxulu** [comment]
看了代码。
主要是在更新vdom树时，比较key  nan不等于man 就会不断创建新的el-option组件  ，删除旧的eloption。  触发更新的原因应该是 option组件往上层select push this 。
