### ISSUE TITLE
[Feature Request] Cascader cascade selector array contains two values that are equally error-prone

### ISSUE THREAD

**Issue by 1142338114** [ElemeFE/element#15952]
### Existing Component
Yes

### Component Name
2.9.1

### Description
谷歌

**Comment by 1142338114** [comment]
![image](https://user-images.githubusercontent.com/35951066/59010873-650dfa00-8865-11e9-9a6e-48192dba383d.png)

**Comment by 1142338114** [comment]
![image](https://user-images.githubusercontent.com/35951066/59010883-70612580-8865-11e9-838c-ba0dfebfa3d5.png)

**Comment by 1142338114** [comment]
当数组里面 23432存在emp1005或者132存在emp1005不能选择 132的emp1005

**Comment by 1142338114** [comment]
两个数组里面都存在一个值的时候 不能选择132的emp1005 props状态为checkStrictly

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
