### ISSUE TITLE
tree组件 选中节点需求

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#1595]
http://wix.github.io/angular-tree-control/ 
angular的这个tree组件很强大，期待element也能加上其中的一些功能
如
 - expanded-nodes 定制需要展开的节点
- selected-node 选中特定的节点
等
非常感谢~~

**Comment by Leopoldthecoder** [comment]
>  定制需要展开的节点
`default-expanded-keys` 属性可以满足这个需求

> 选中特定的节点
`setCheckedNodes` 和 `getCheckedNodes` 方法可以满足这个需求。
