### ISSUE TITLE
[Feature Request] I18N locale type script support

### ISSUE THREAD

**Issue by ositowang** [ElemeFE/element#15965]
### Existing Component
是

### Component Name
i18n

### Description
Hi there, I am currently using some element ui components in my project with typescript. I am applying Internationalization to the whole project. However, when I import the several language support locale into my project. I got the `Element implicitly has an 'any' type because type '{ en: typeof import("element-ui/lib/locale/lang/en");` error. 
I add some simple `d.ts` files by myself trying to workaround it. However, I get more implicit type error later.
Could you officially add some declaration file for the i18n files?

**Comment by ziyoung** [comment]
Right now we have no plan to support this.
