### ISSUE TITLE
[Bug Report] Table multilevel table header columns use fixed, and parent widths are not extended by subset widths

### ISSUE THREAD

**Issue by wuweiping2014** [ElemeFE/element#15962]
### Element UI version
2.9.1

### OS/Browsers version
win7/谷歌浏览器、360浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wuweiping2014/pen/byyoGa

### Steps to reproduce
初始状态，父级列由于使用fixed=“right”被固定在右侧，但只显示最后一个子列，由于父级列没有得到子集列宽度撑起，导致父级列默认只有80px，其它子列被隐藏。

### What is Expected?
父级宽度由子集撑开

### What is actually happening?
父级宽度没有被子集撑开

**Comment by ziyoung** [comment]
Duplicate of #15480

**Comment by hello-lun** [comment]
开发者视而不见的吗？直接无视？
