### ISSUE TITLE
[Bug Report] Project builds are packaged and deployed to the server without loading the resource icon properly. Local development runs normally.

### ISSUE THREAD

**Issue by zhanjunhao** [ElemeFE/element#15966]
### Element UI version
2.9.1

### OS/Browsers version
windows10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhanjunhao/

### Steps to reproduce
任意使用Icon 图标组件 本地开发运行时 正常 项目打包后 无法正常加载icon 字体图标资源 以前2.7.2 版本不会发生该问题

### What is Expected?
解决默认build后 Failed to load resource: net::ERR_FILE_NOT_FOUND  element-icons.535877f.woff:1 element-icons.732389d.ttf:1 导致无法正常显示icon

### What is actually happening?
项目开发完毕 日常打包 不改变build相关配置 如何默认 能正常加载到icon字体图标 资源文件 还请核实该问题 谢谢！

**Comment by cuivip** [comment]
同问?

**Comment by zhanjunhao** [comment]
解决方法：
1、webpack module配置：(build目录下webpack.base.conf.js)

`module: {
    rules: [
      ...(config.dev.useEslint ? [createLintingRule()] : []),
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }`

2、webpack utils.js 修改：（build目录下utils.js）
添加   publicPath: '../../'

`if (options.extract) {
      return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader',
        publicPath: '../../'
      })
    } else {
      return ['vue-style-loader'].concat(loaders)
    }`
