### ISSUE TITLE
[Table] clearSelection 怎么用？

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1596]
需要使用一个重置按钮，将table中修改的select选择恢复到初始选择的状态，请问如何使用。可否给一个demo

**Comment by kopheece** [comment]
![image](https://cloud.githubusercontent.com/assets/23140033/20958942/517e3810-bc93-11e6-92dd-3000da16527c.png)

![Uploading image.png…]()

**Comment by kopheece** [comment]
![image](https://cloud.githubusercontent.com/assets/23140033/20959060/f916630e-bc93-11e6-9b80-c5b19c1a1a49.png)

**Comment by kopheece** [comment]
http://jsfiddle.net/kopheece/6yev1375/

**Comment by yuanshengchao** [comment]
数据从ajax请求来的时候已经有部分选中，重置的时候是恢复到默认选中状态，而不是清空，请问怎么实现呢？

**Comment by yuanshengchao** [comment]
官网说需要配合这个reserve-selection，请问如何配合reserve-selection

**Comment by furybean** [comment]
@yuanshengchao 不是需要配合 reserve-selection，是在使用 reserve-selection 的时候，大部分情况需要使用改方法。
