### ISSUE TITLE
[Bug Report] can't use el-badge and el-popover at the same time

### ISSUE THREAD

**Issue by LangRizkie** [ElemeFE/element#15967]
### Element UI version
0.1.0

### OS/Browsers version
Version 75.0.3770.80 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/jojpVo

### Steps to reproduce
it must be button with badge and show popover on click

### What is Expected?
showing badge icon even using popover

### What is actually happening?
if it's el-popover wraps the badge and button it will show nothing but if it's el-badge wrapping the el-popover it only show the badge

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
