### ISSUE TITLE
[Bug Report] webpack project can not show table, it is an empty table.

### ISSUE THREAD

**Issue by pape2016** [ElemeFE/element#15973]
### Element UI version
2.9.1

### OS/Browsers version
windows 10/ chrome 75.0.3770.80

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
Because the issue is happened for wepack project, so there is not reproduction link.
1. just create a simple project which is not packed by webpack, try the official el-table example, create a html, a js and a css file, it works, the table data is rendered ok.
2. create a project which is packed by webpack, put the official el-table example in the file main.vue, webpack it, and does not see the table in web browser, check the source code of website, the table is there, but it is an empty table. 

### What is Expected?
the table data shows correctly for webpack project

### What is actually happening?
the table data does not show for webpack project

**Comment by pape2016** [comment]
please feel free to check the webpack simple project mytable
[http://123.207.255.31:81/pic/mytable.zip](url)

**Comment by pape2016** [comment]
the project mytable is a simple project to reproduce the issue, you can see the text and button, but can not see the table.
after install the dependencies, modify the file webpack.config.js, change the output folder, then just run webpack to pack it, and then open the web, you will see the reproduction.

**Comment by pape2016** [comment]
I put the reproduction project in github and describe the reproduction steps, please check.

https://github.com/pape2016/mytable

**Comment by ziyoung** [comment]
我使用 cli 建了一个项目，安装最新的 2.9.1 没有问题。非组件库本身问题。检查一下 webpack 配置是否正确。
