### ISSUE TITLE
[Feature Request] Message is displayed in 2.9.1 version in turn. What if you want to overlap the display?

### ISSUE THREAD

**Issue by sscfaith** [ElemeFE/element#15977]
### Existing Component
是

### Component Name
el-message

### Description
Message在2.9.1版本中依次展示，若想重叠显示怎么办？

**Comment by happy0402** [comment]
我现在这个版本（2.8.2）是重叠展示的，我不想重叠展示怎么办T^T

**Comment by iamkun** [comment]
#15639

**Comment by kawakeee** [comment]
you should use closeAll()...
