### ISSUE TITLE
[Bug Report] table's component styles

### ISSUE THREAD

**Issue by RabbDream** [ElemeFE/element#15976]
### Element UI version
2.9.1

### OS/Browsers version
win10/chrome74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
when i use Grouping table head,i found the table header's width isn't equal to the table tbody's width

### What is Expected?
the table header's width is equal to the table tbody's width

### What is actually happening?
the table header's width isn't equal to the table tbody's width

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
