### ISSUE TITLE
[Feature Request] el-carousel transform not in one direction when there are 2 el-carousel-item

### ISSUE THREAD

**Issue by JinchunJiang** [ElemeFE/element#15982]
### Existing Component
是

### Component Name
el-carousel

### Description
when there are two el-carousel-item, it will transform from right to left, and then from left to right.Maybe always transform in one direction(from right to left) is much better?

**Comment by hckang80** [comment]
In general, one direction is better.

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by temberature** [comment]
Could be supported by Merge Request ?
