### ISSUE TITLE
新版本el-dialog里面嵌套el-form-item报错

### ISSUE THREAD

**Issue by loong-moon** [ElemeFE/element#1599]
`<el-dialog title="添加用户" v-model="dialogVisible" size="tiny" :lock-scroll="false">

        <el-form label-position="top" :rules="rules" :model="userModel">
            <el-form-item label="手机号" prop="name">
                <el-input v-model="userModel.mobile" placeholder="请输入手机号"></el-input>
            </el-form-item>
        </el-form>

            <span slot="footer" class="dialog-footer">
                <el-button  @click="dialogVisible = false">取 消</el-button>
                <el-button type="info"   @click.native="dialogVisible = false">确定</el-button>
            </span>
    </el-dialog>`
会报Uncaught (in promise) TypeError: Cannot read property 'value' of undefined错误 然后导致弹框不能操作
如果把el-form-item注释掉就不会报该错误  弹框可以正常关闭

**Comment by Leopoldthecoder** [comment]
文档上也有 Dialog 里嵌套 Form 的例子，是正常的，所以请提供 demo。

**Comment by loong-moon** [comment]
我从新启动后恢复正常了
