### ISSUE TITLE
When [Bug Report] el-table and V-IF are used at the same time, there are rendering errors

### ISSUE THREAD

**Issue by magnww** [ElemeFE/element#15994]
### Element UI version
2.9.1

### OS/Browsers version
Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/gefan/pen/zVYNJY

### Steps to reproduce
点击按钮2
可见table2的第一列被错误渲染为table1的selection列

### What is Expected?
table2的第一列应渲染为姓名列

### What is actually happening?
table2的第一列被错误渲染为table1的selection列

**Comment by qingdengyue** [comment]
给ElTable加个:key

**Comment by magnww** [comment]
加:key可以解决
