### ISSUE TITLE
El-select v-popover: popover1 filterable multiple is used simultaneously and cannot be searched

### ISSUE THREAD

**Issue by GitHdu** [ElemeFE/element#15999]
### Element UI version
2.9.1

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
el-popover trigger="hover"时出现，click正常
https://codepen.io/anon/pen/JQjNxz?editors=1010

### Steps to reproduce
https://codepen.io/anon/pen/JQjNxz?editors=1010

### What is Expected?
多选同时可搜索，并且可以popover

### What is actually happening?
多选，可以popover，但是不能搜索

**Comment by GitHdu** [comment]
重现地址
https://codepen.io/anon/pen/JQjNxz?editors=1010

**Comment by flow-stateM** [comment]
看起来是popover和本身的面板冲突了，把自己的popover去掉就可以了

**Comment by samzeng** [comment]
popover 的 slot 不要绑在 select 组件上，在 select 外层包一个 div 用于绑定 slot 可解决这个问题。
