### ISSUE TITLE
使用laravel-elixir执行gulp命令时遇到了问题

### ISSUE THREAD

**Issue by hangaoyu** [ElemeFE/element#160]
Error: ./~/element-ui/lib/element-ui.common.js
    Module build failed: SyntaxError: 'with' in strict mode (2371:36)

#pacage.json
    {
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "babel-preset-es2015": "6.9.0",
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^2.0.0-rc.7",
    "vue-resource": "^0.9.3"
  },
  "dependencies": {
    "element-ui": "^1.0.0-rc.4",
  
  }
}

**Comment by QingWei-Li** [comment]
你的 babel 怎么配置的，`node_modules/element-ui` 是不是被 babel-loader 处理到了？

**Comment by hangaoyu** [comment]
@QingWei-Li  我是在gulpfile文件中 
     ` elixir(mix => {
          mix.sass('app.scss')
         .rollup('element.js','public/js/element.js');
      });`
  node_modules/laravel-elixir中的.babelrc是
`{ "presets": ["es2015"] }`
这里的配置需要改么，还是说用rollup处理需要配置rollup.config.js吗

**Comment by QingWei-Li** [comment]
额 麻烦提供一个 demo 项目吧

**Comment by csvwolf** [comment]
@hangaoyu 不知道你以前是否使用过 Laravel + Vue，如果没有，可以参考官方文档或者这个教程：<http://laravelacademy.org/post/5656.html>

配置完Laravel的部分，其他部分请参考我们给的demo（是一样的）

**Comment by hangaoyu** [comment]
@csvwolf  我把你提供的laravel5.1+vue的项目git下来配置运行成功后  然后只在main.js中加入了
`import Element from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
Vue.use(Element)`  因为之前mint-ui的项目我也是就加了这些，没有配置别的什么就成功导入了）
然后在这边执行gulp还是会报错
`[Error: ./~/element-ui/lib/element-ui.common.js
Module build failed: SyntaxError: 'with' in strict mode`

**Comment by csvwolf** [comment]
@hangaoyu 查了一下原因，是因为buble的问题，目前已经提了issue给`laravel-elixir-webpack-official`，暂时可以用普通的webpack方式，避开`laravel-elixir`、`laravel-elixir-vue-2`等包。

**Comment by hangaoyu** [comment]
@csvwolf @QingWei-Li 好的 昨天试了webpack挺顺利的 谢谢

**Comment by csvwolf** [comment]
@hangaoyu 刚刚强行覆盖了一波默认配置，这样依旧可以使用`laravel-elixir`系列相关包，但是不是很好地解决方案：

<https://github.com/csvwolf/element-in-laravel>

**Comment by hangaoyu** [comment]
@csvwolf 原来可以这样配置...get

**Comment by csvwolf** [comment]
@hangaoyu 这个方法强行覆盖了配置文件，个人觉得这样并不好，但现行只能这么做了，如果`laravel-elixir-webpack-official`有更新，我们也会更新一下这个demo的，如果没有其他问题就close了。
