### ISSUE TITLE
[Bug Report] Cascader lazyLoad bug

### ISSUE THREAD

**Issue by howiefh** [ElemeFE/element#16001]
### Element UI version
2.9.1

### OS/Browsers version
Windows 10 64位 / Chrome 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/rENmpd

### Steps to reproduce
有时候需要设置Cascader 组件的初始值，所以开始的options会有加载好的一部分数据，但是当点击options中的选项时还是会触发lazyLoad方法，然后就会出现重复的选项。2.9 以前是通过active-item-change事件变更options实现动态加载的，就不会出现这样的问题。

### What is Expected?
options有部分初始值的情况下，希望通过 props.lazyLoad  加载不会有重复项

### What is actually happening?
options有部分初始值的情况下，props.lazyLoad 会出现重复项

**Comment by mattwmj** [comment]
Same problem, no solution or workaround
