### ISSUE TITLE
[Bug Report] Tree Can't  cancel the currently highlighted node

### ISSUE THREAD

**Issue by aiyaoxin01** [ElemeFE/element#16002]
### Element UI version
2.9.1

### OS/Browsers version
win10/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
setCurrentKey(null) , Can't cancel the currently highlighted node

### What is Expected?
setCurrentKey  If null, cancel the currently highlighted node

### What is actually happening?
Can't cancel the currently highlighted node

**Comment by yyjjqq94** [comment]
#15667 
will be fixed in 2.9.2
