### ISSUE TITLE
The radio experience of [Feature Request] cascade selectors is not good

### ISSUE THREAD

**Issue by zhaosanduo** [ElemeFE/element#16009]
### Existing Component
是

### Component Name
级联选择器   cascader

### Description
【级联选择器】-【选择任意一级选项】-【单选模式】下的体验不如以前好，希望能够点击文字 label就选中，而不是选择左侧的圆点，给很多用户造成了困扰，一些电脑盲根本不会用。

**Comment by ldwqh0** [comment]
我这里也发现了类似的问题

**Comment by Mrli2016** [comment]
这个改动简直不是太傻 以前的用户体验多好 这个设计是不是被抽了

**Comment by waveheart** [comment]
太蠢了, 升级了一下element 被用户骂了, 这个改动让这个组件极不好用. 不知道怎么想的.

**Comment by waveheart** [comment]
刚才又试了一个, 那个Radio 单选框是真的难点, 我原来也打魔兽, 星际,dota的了, 这比dota1里面的那个剧毒的模型还难点, 自带林肯啊.

**Comment by 9-lives** [comment]
用 radio，不知道怎么控制允许选择的层级，以前还可以借着 change-on-select 实现
