### ISSUE TITLE
MessageBox 表单验证 model 和 rules 一致 依旧不通过

### ISSUE THREAD

**Issue by cench** [ElemeFE/element#1600]
问题和这个是一样的，但是因为放到线上demo不知为何得不到复现，但是问题确实存在。

问题：
https://github.com/ElemeFE/element/issues/361

即使输入框中存在内容依旧会报错，验证不通过
demo：https://jsfiddle.net/erguotou525/9qc4q0dy/3/

**Comment by Leopoldthecoder** [comment]
正确的用法是：http://jsfiddle.net/leopoldthecuber/zjmLvump/ ，看看用法对不对吧。

**Comment by Aprilday** [comment]
顺着这个说个情况，就是在表单里调用 this.$refs.ruleForm.resetFields() 重置的时候会报错，提示resetFields  not defined

**Comment by Leopoldthecoder** [comment]
@Aprilday 请给 demo

**Comment by cench** [comment]
@Leopoldthecoder 应该是实例表单中 model 和 refs 值相同就有有可能导致model值绑定不上验证不通过
`el-form :model="ruleForm2" :rules="rules2" ref="ruleForm2" `
