### ISSUE TITLE
[Bug Report] switch dialog components in the vue's keep-alive

### ISSUE THREAD

**Issue by waldonUB** [ElemeFE/element#16018]
### Element UI version
2.9.1

### OS/Browsers version
Google Chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/58t4wzkL/4/

### Steps to reproduce
step1:
click the dialog1 button
step2:
click the dialog2 button
step3:
click the dialog1 button

### What is Expected?
Components can switch normally

### What is actually happening?
vue.js:634 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'insert' of undefined"

**Comment by waldonUB** [comment]
我想缓存几个不同业务对话框组件，这样在可以不用每次打开dialog都重新查询一边数据。用popover弹出框就可以正常实现，但是用dialog就会报错。

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/60709214-7e789380-9f42-11e9-83e7-47b9e991b6f5.png)
我们也没看太明白。从报错信息来看，像是 Vue nextTick 中的报错。
