### ISSUE TITLE
alert组件中的内容不能复制吗，好不方便 

### ISSUE THREAD

**Issue by arronf2e** [ElemeFE/element#1601]
### What is actually happening?
alert组件中的内容不能复制吗，好不方便

**Comment by Leopoldthecoder** [comment]
复制里面的文本？我试了可以，如果不行的话请给出 demo

**Comment by jikkai** [comment]
@arronf2e 说的可能是MessageBox？Alert组件是可以复制的
![image](https://cloud.githubusercontent.com/assets/14025786/20961765/7c0a682a-bca1-11e6-9ea8-9573c532820b.png)

**Comment by Leopoldthecoder** [comment]
哦，如果是这样的话，自己覆盖一下 MessageBox 的 `-webkit-user-select` 样式就可以。

**Comment by arronf2e** [comment]
@Leopoldthecoder 确实是MessageBox，我说错了，已解决，谢谢
