### ISSUE TITLE
The table actively triggers the sort function to fail, clearsort has bugs

### ISSUE THREAD

**Issue by flow-stateM** [ElemeFE/element#16016]
### Element UI version
2.9.1

### OS/Browsers version
chrome74

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/anon/pen/JQoJrg

### Steps to reproduce
1.cleartsort后 数据排序正确，但表头图标没有随之清除状态，
2.手动用refs中的实例触发sort无效

### What is Expected?
1.clearsort后表头图标随之变化
2.可以在外部正确触发sort并且表头图标随之变化

### What is actually happening?
1.cleartsort后 数据排序正确，但表头图标没有随之清除状态，
2.手动用refs中的实例触发sort无效

**Comment by yyjjqq94** [comment]
this.$refs.tabletest.sort( "date", "descending" )

**Comment by flow-stateM** [comment]
3q,but the document make me confused,maybe it can be more exact ?
![image](https://user-images.githubusercontent.com/32272054/59334871-009fde80-8d2e-11e9-80c9-cc569349cfdc.png)

**Comment by liuxiaodeng** [comment]
The cleartsort header icon still does not clear.

**Comment by ton77v** [comment]
@liuxiaodeng updating to 2.10.1 fixed the issue for me

**Comment by liuxiaodeng** [comment]
@ton77v  is good
