### ISSUE TITLE
[Feature Request] can CascaderPanel event add check Event?

### ISSUE THREAD

**Issue by confidence68** [ElemeFE/element#16026]
### Existing Component
是

### Component Name
CascaderPanel  

### Description
can CascaderPanel  event add check Attribute?

when Props multiple is true，I want it like tree。When select parent ,I just use parent , when one childen not select ，I want other selected children.

Previously, I used to filter through tree checks to get the selected parent element. At present, CascaderPanel has only one change event, which can not achieve the desired effect.

![QQ截图20190612160737](https://user-images.githubusercontent.com/3736355/59334618-79526b00-8d2d-11e9-97d5-145e4d03928c.png)

**Comment by island205** [comment]
Sorry, we have no plan to support this.
