### ISSUE TITLE
[Bug Report] Trigger mechanism of span-method is unreasonable

### ISSUE THREAD

**Issue by moonose** [ElemeFE/element#16023]
### Element UI version
2.9.1

### OS/Browsers version
Google Chrome 74.0.3729.169 64bit

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/moonose/pen/zVxpmK

### Steps to reproduce
1.bind span-method to a table
2.input some data in the input box

### What is Expected?
span-method will not be triggered.
I think the reasonable mechanism of span-method should be like this:
. the bound table data changed, span-method will be triggered
. other data changed, span-method will not be triggered

### What is actually happening?
span-method will be triggered

**Comment by island205** [comment]
`span-method` is called by `table-body`'s render function with data changing, so it should be used as stateless at present.
