### ISSUE TITLE
[Bug Report] el-tabs css bug

### ISSUE THREAD

**Issue by FBshtml** [ElemeFE/element#16033]
### Element UI version
2.9.1

### OS/Browsers version
win10、最新chrome

### Vue version
2.6.10

### Reproduction Link
https://github.com/FBshtml/demo

### Steps to reproduce
1、安装启动
2、f12打开控制台
3、把控制台调成左右结构，以便于调整浏览器宽度
4、拖动控制台边框，调整页面width，测试tabs的自适应效果
5、反复快速数次执行步骤4，=>{ tabs宽度不再随浏览器宽度变化，页面卡死，浏览器无响应  }

### What is Expected?
padding属性不应该影响到浏览器性能

### What is actually happening?
浏览器卡死，只能用任务管理器重启chrome

**Comment by FBshtml** [comment]
这里只改了一个padding属性
.el-tabs__nav-wrap {
  padding-left: 50px; 
}

**Comment by island205** [comment]
`Tabs` 为了实现显示左右切换 handle 依赖 `wrap` 的宽度计算，padding 样式导致了一个循环调用的 bug，目前没有办法解决，原则就是不能修改 wrap 的 padding 样式。
