### ISSUE TITLE
[Feature Request] 分页栏的“前往___页”中的“前往”二字，应该改成“到第”

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ElemeFE/element#16030]
### Existing Component
是

### Component Name
Pagination 

### Description
分页栏的“前往  X  页”中的“前往”二字，应该改成“到第”，效果如：“到第  X  页”，这样读起来顺口些。

**Comment by waldonUB** [comment]
这个可以自己改的

**Comment by fudax** [comment]
新建assets/locale/cn.js，修改pagination组件的文本：

      pagination: {
        goto: '前往 第',
        pagesize: '条/页',
        total: '共 {total} 条',
        pageClassifier: '页'
      },

入口(main.js)的地方参照element-ui帮助文档国际化部分的说明：
import locale from './assets/locale/cn.js';
Vue.use(ElementUI, { locale });

**Comment by island205** [comment]
@fudax nice explain.
