### ISSUE TITLE
从1.0.1升级后form组件验证时出现的红色边框验证通过后也不消失

### ISSUE THREAD

**Issue by featherfly** [ElemeFE/element#1603]
form组件验证时出现的红色边框验证通过后也不消失

console输出下面的错误信息
directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "error" 
(found in component &lt;ElFormItem>)

**Comment by Leopoldthecoder** [comment]
请给 demo。
