### ISSUE TITLE
[Bug Report] How to keep components in a table from being destroyed when it expands and collapse rows?

### ISSUE THREAD

**Issue by huangliqiao** [ElemeFE/element#16035]
### Element UI version
2.9.1

### OS/Browsers version
chrome 74.0.3729.131

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/anon/pen/ydNPrq

### Steps to reproduce
1、点击展开行
2、再次点击使行收起
3、插入的组件执行destroyed

### What is Expected?
如果插入组件包含大量内容，每次展开都会re-mount导致渲染效率低，是否有办法能让插入的组件不被销毁？

### What is actually happening?
插入的组件被销毁

**Comment by ziyoung** [comment]
这个功能很实用。但是增加这个功能会造成许多的改动。这期不会添加该功能。

**Comment by ziyoung** [comment]
TreeTable 也可以遵循类似的实现形式。
