### ISSUE TITLE
[Bug Report] el-popover not support Vue 2.6.0 v-slot

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#16037]
### Element UI version
2.9.1

### OS/Browsers version
MAC OS 10.14 / Google Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/panhezeng/pen/zVGRVR

### Steps to reproduce
根据vue文档关于具名插槽部分和官方element popover 嵌套信息示例
把
`<el-button slot="reference">click 激活</el-button>`
替换为
`<template v-slot:reference><el-button>click 激活</el-button></template>`
后，
点击按钮没有弹出表格框

v-slot 指令自 Vue 2.6.0 起被引入，提供更好的支持 slot 和 slot-scope 特性的 API 替代方案。v-slot 完整的由来参见这份 RFC。在接下来所有的 2.x 版本中 slot 和 slot-scope 特性仍会被支持，但已经被官方废弃且不会出现在 Vue 3 中。

### What is Expected?
点击按钮弹出表格框

### What is actually happening?
点击按钮没有弹出表格框

**Comment by mkanako** [comment]
遇到同样的问题，最后给button加上v-once就可以了
`<el-button v-once>click 激活</el-button>`
具体我也不太懂为什么，感觉不是element问题，而是Vue的问题

**Comment by NateScarlet** [comment]
> 遇到同样的问题，最后给button加上v-once就可以了
> `<el-button v-once>click 激活</el-button>`
> 具体我也不太懂为什么，感觉不是element问题，而是Vue的问题

用 v-once 就不能动态更新 reference 内容了，而且 slot 语法不需要 v-once 。

**Comment by liuqiang1357** [comment]
我也遇到了，input标签下slot="append"可以正常显示，但换成v-slot:append或#append不能显示

**Comment by island205** [comment]
pr welcome

**Comment by meteorlxy** [comment]
@island205 这个修复了吗？好像没有找到对应 commit 或者 PR
