### ISSUE TITLE
[Bug Report] table的height属性无法使用css样式，例如height="120%"，生成的样式就变成"height:120px"。height="calc(100% - 25px)"，生成的样式为空。之前版本是好的。

### ISSUE THREAD

**Issue by creatworld** [ElemeFE/element#16043]
### Element UI version
2.9.1

### OS/Browsers version
win10/chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
  <el-table height="120%"></el-table>
  <el-table height="calc(100% - 24px)"></el-table>

### What is Expected?
height为String类型时应当正确输出里面的样式

### What is actually happening?
height为String类型时输出的样式时错误的

**Comment by pangao66** [comment]
同遇到这个bug了, height里面不能传 css 单位都会变成px  ,  max-height 也是跟着一样的问题, 2.9.1之前的版本是好的

**Comment by DoubleRayWang** [comment]
同样遇到了这个问题，之前的100%变成了100px

**Comment by ggwork** [comment]
我也遇到同样的问题

**Comment by ggwork** [comment]
给table的父元素一个高度，给table设置一个随便高度，比父元素高度小就可以，然后设置table的min-height为100%  就可以了
[min-height](https://codepen.io/guoxianqiang/pen/OeyBJZ?&editable=true)

**Comment by litao36253** [comment]
我也遇到这个问题了，大神快修复哦

**Comment by litao36253** [comment]
我也遇到这个问题，参考楼上仁兄的方案，暂时升级最新版本用着

**Comment by ziyoung** [comment]
Duplicate of #15806
