### ISSUE TITLE
[Bug Report] 2.9.1 Cascader will not display Level 3 when the ID of Level 2 and Level 3 is the same (previous versions will not). The hock method needs to configure value ='label'in props (because I will not label the same here).

### ISSUE THREAD

**Issue by zhijunw** [ElemeFE/element#16046]
### Element UI version
2.9.1

### OS/Browsers version
WIN

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/WqvggY?&editable=true#anon-login

### Steps to reproduce
      options: [{
        value: '1000',
        label: '1000聚仁时尚销售组织',
        children: [{
          value: '10',
          label: '10直营渠道',
          children: [{
            value: '10',
            label: '10正装'
          }, {
            value: '10',
            label: '20正装'
          }, {
            value: '30',
            label: '30正装'
          }, {
            value: '40',
            label: '40正装'
          }]
        }]
      }],

当这样的数据的时候   由于第二级和第三级的ID 一样  如果在props不进行任何 配置  那么选择之后在页面上都不会显示 如果props  设置 checkStrictly:true 那么只会显示第一项和第二项的数据  这里的hack方法  需要设置value (唯一值)

以前的版本  不会出现这样的问题  我感觉更新之后 可能在功能上面没以前的好用

### What is Expected?
希望不进行设置 props   value值不唯一  也能正常显示

### What is actually happening?
value 值 出现重复 就会不显示

**Comment by Lanseria** [comment]
https://codepen.io/anon/pen/wLyEaN?&editable=true

**Comment by zhijunw** [comment]
打开一直在刷新

**Comment by nealjin** [comment]
今天也遇到这个问题

**Comment by zhijunw** [comment]
2.11 会改
