### ISSUE TITLE
[Bug Report] el-table row-style attribute returns display: none invalid for the first time. This bug will not appear in version 2.6.3, and it will appear in version 2.7.0. It should be related to supporting tree tables.

### ISSUE THREAD

**Issue by chengliangcode** [ElemeFE/element#16048]
### Element UI version
2.7.0

### OS/Browsers version
Google Chrome 74.0.3729.131

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/anon/pen/JQdaYj

### Steps to reproduce
el-table  row-style属性   第一次返回 display:none无效，
我自己的目的也是用element开发可行内编辑的树形表格

### What is Expected?
第一次加载时按条件隐藏行

### What is actually happening?
若果只是返回颜色如color:red 是有效的，diplay则无效，

**Comment by ziyoung** [comment]
例子中的 demo 没有问题。

**Comment by ziyoung** [comment]
#15849

**Comment by pansila** [comment]
问题第一次提出来已经一个多月前了，什么时候能解决呀，卡住项目很久了。

**Comment by pansila** [comment]
单步追踪了下，table在Virtual DOM中生成的时候，style还是对的，可能比对更新的时候丢了，对vue不熟追不下去了。另外style设置成"display: none"和任何其它样式，只有"display: none"会丢失，其它样式还保留着。

**Comment by ziyoung** [comment]
跟 v-show 的实现有关。https://github.com/vuejs/vue/blob/b7c2d9366cf731a1551286b8ac712e6e0905070e/src/platforms/web/runtime/directives/show.js#L13

**Comment by pansila** [comment]
无解？
