### ISSUE TITLE
PluginObject was not introduced in element-ui.d.ts file in [Bug Report] types file

### ISSUE THREAD

**Issue by caiyihua** [ElemeFE/element#16049]
### Element UI version
2.9.1

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
用ts的时候 报错element-ui下types 文件中element-ui.d.ts文件里PluginObject没有引入  打包不成功

### What is Expected?
PluginObject在 element-ui.d.ts文件 头部引入

### What is actually happening?
PluginObject在 element-ui.d.ts文件 头部未引入

**Comment by pumano** [comment]
same for me, my builds are failed now. For workaround I use in tsconfig.json `"skipLibCheck": true` but it should be fixed.

**Comment by e-cloud** [comment]
It's careless since this bug has been existing for more than half a month.

**Comment by Deracination** [comment]
I worked-around by editing node_modules/element-ui/types/element-ui.d.ts and changing line 1 from

`` import Vue from 'vue' ``

to

`` import Vue, { PluginObject } from 'vue' ``

**Comment by tomorrowbye** [comment]
我也遇到了这个问题，没有引入 PluginObject，导致打包失败

**Comment by xiGUAwanOU** [comment]
Problem seems to have been already fixed in version 2.9.2.

**Comment by Armour** [comment]
问题已经在 2.9.2 版本中修复
Confirm this is fixed in 2.9.2, thanks!
