### ISSUE TITLE
[Bug Report] el-date-picker show

### ISSUE THREAD

**Issue by heroHXG** [ElemeFE/element#16042]
### Element UI version
2.9.1

### OS/Browsers version
windows7/chrome11

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
1.enter the link
2.choose the date of birth for the user
3.dateOfBirth has used the "el-date-picker" with type="date"

### What is Expected?
希望时间选择框focus出来的样式是type="year"（这样用户可以快速选择年份），并且这个el-date-picker可以选择yyyy-mm-dd完整时间。

### What is actually happening?
当type="date"时候，用户不知道el-date-picker-header是可以点击的，时间跨度是10年可以快速选择，导致网站遭到很多用户投诉。用户以为只能点击年，月按钮选择日期。

**Comment by wacky6** [comment]
像这样 ？https://github.com/NKMUN/hi.nkmun.cn/blob/master/src/components/form/BirthdayPicker.vue

**Comment by heroHXG** [comment]
> 像这样 ？https://github.com/NKMUN/hi.nkmun.cn/blob/master/src/components/form/BirthdayPicker.vue
很感谢你，但是我的意思是type本来就是date形式，picker选中的时候视图是type=“year”形式，相当于picker的header自动选中了

**Comment by wacky6** [comment]
什么叫选中的时候是type=year。

**Comment by heroHXG** [comment]
就是组件的显示样式改变一下，我可能说的不清楚，这个问题已经解决了，通过dom找到元素节点，在显示的时候改变他的样式。

**Comment by heroHXG** [comment]
<el-form-item label="出生日期" prop="dateOfBirth">
          <el-date-picker v-model="traveler.dateOfBirth" :picker-options="datePickerOptions" type="date"  
                @focus="showYear"   "value-format="yyyy-MM-dd" >
          </el-date-picker>
</el-form-item>  
 showYear(){
            setTimeout(function(){
                let nodeList=document.getElementsByClassName("el-date-picker__header-label")
                nodeList[0].click()
                if(nodeList.length==4){  //页面上有多个datepicker的情况下
                    nodeList[0].click()
                    nodeList[2].click()
                }
            },100)
        },

**Comment by wacky6** [comment]
那就 show 的时候直接改 picker 的 currentView。DOM操作是非常不推荐的。
