### ISSUE TITLE
[Bug Report] Many repetitive styles in index.css generated by the command-line theme tool

### ISSUE THREAD

**Issue by fudax** [ElemeFE/element#16041]
### Element UI version
2.9.1

### OS/Browsers version
windows7 / chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/fudax/pen/dBojdx

### Steps to reproduce
参照官方说明：et -i，然后el -o assets/style/chalk/，得到index.css文件中大量重复样式定义

### What is Expected?
希望在自定义主题中提供一下官方打包去重的方案

### What is actually happening?
index.css文件中大量重复样式定义

**Comment by xilixjd** [comment]
+1

**Comment by island205** [comment]
如果使用自定义主题，不再需要引用原样式文件
