### ISSUE TITLE
Tree form plus multiple selection

### ISSUE THREAD

**Issue by gaodda** [ElemeFE/element#16055]
### Existing Component
否

### Component Name
tree-table-checkBox

### Description
树形表格加多选，父子级关联选择有问题

**Comment by gaodda** [comment]
Tree table plus multiple selection

**Comment by liangzmdev** [comment]
same question

**Comment by reginezhang** [comment]
同 官方什么时候更新鸭

**Comment by linfanboss** [comment]
树形表格应该不需要联动父子的选中状态
