### ISSUE TITLE
The [Bug Report] dialog does not support drag-and-drop

### ISSUE THREAD

**Issue by huangshiqiang** [ElemeFE/element#16053]
### Element UI version
2.8.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
官网Dialog组件，不支持点击标题拖动对话框。不支持拖动调整对话框的大小，不支持设置最大化，最小化按钮

### What is Expected?
官网Dialog组件，不支持点击标题拖动对话框。不支持拖动调整对话框的大小，不支持设置最大化，最小化按钮。
这些功能非常常用，我看很多人提了这个问题，但是都被关闭了。框架默认提供这些功能真的非常有必要，可以提高用户体验，可以参考一下
"layui"，这个对话框做的非常好，非常多人使用。我觉得一个好的产品应该注重细节，希望element团队可以把这些功能集成到框架内部。谢谢！

### What is actually happening?
不支持点击标题拖动对话框。不支持拖动调整对话框的大小，不支持设置最大化，最小化按钮

**Comment by fudax** [comment]
最大化可以这样，不过还是支持楼主的提议：

```html
<el-dialog :fullscreen="maximize">
      <template slot="title">
        <button class="el-dialog__headerbtn" style="right:40px" @click="maximize=!maximize">
          <el-tooltip content="最大化" effect="dark" placement="left">
            <i v-show="maximize==false" class="el-icon-full-screen" style="font-size:14px"></i>
          </el-tooltip>
          <el-tooltip content="还原" effect="dark" placement="left">
            <i v-show="maximize==true" class="el-icon-bottom-left" style="font-size:14px"></i>
          </el-tooltip>
        </button>
      </template>

      ……
</el-dialog>
```

**Comment by zhixueyun9** [comment]
非常希望官方能支持拖动这个功能

**Comment by island205** [comment]
pr welcome

**Comment by koqiui** [comment]
确实，至少对话框得能按header能拖动位置
