### ISSUE TITLE
In the state of [Bug Report] Loading. service, the rendering block of the table will result.

### ISSUE THREAD

**Issue by Dd-ouni** [ElemeFE/element#16050]
### Element UI version
2.9.1

### OS/Browsers version
win7x64/ Google Chrome 73.0.3683.86（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ddouni/pen/vqOvVJ

### Steps to reproduce
在 存在 el-table 的 router-view 的 created生命周期 调用 Loading.service，都会导致 table 无法渲染出来，必须 loading.close() 才会渲染

### What is Expected?
在loading过程， el-table渲染不应该被阻塞。

### What is actually happening?
在loading过程，el-table 并不会被渲染，空无一物。必须等待loading 完毕，才会渲染出来。

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
