### ISSUE TITLE
Does [Feature Request] Cascader Cascader Cascade Selector return methods or attributes of value and label at the same time?

### ISSUE THREAD

**Issue by summer0101** [ElemeFE/element#16059]
### Existing Component
是

### Component Name
Cascader

### Description
Cascader 级联选择器 有没有同时返回 value 和 label的方法或者属性

**Comment by SimonaliaChen** [comment]
可以使用 getCheckedNodes 方法

**Comment by xsteadybcgo** [comment]
getCheckedNodes 不是 tree的 event吗?

**Comment by xsteadybcgo** [comment]
@SimonaliaChen getCheckedNodes 是 tree 的 event

**Comment by SimonaliaChen** [comment]
> @SimonaliaChen getCheckedNodes 是 tree 的 event

cascader 也有该方法，下个版本会补齐文档
