### ISSUE TITLE
[Bug Report] Cascader display label that is clicked, not the label for binded value after prevent set value

### ISSUE THREAD

**Issue by jeange1003** [ElemeFE/element#16069]
### Element UI version
2.9.1

### OS/Browsers version
OSX / Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jeange1003/pen/BgobyX

### Steps to reproduce
select parent -> unselectable

### What is Expected?
DO NOT show "parent / unselectable", just show previous label.

### What is actually happening?
The cascader label displays "parent / unselectable",  but the value of cascader is not "parent / unselectable"

![cascader bug](https://user-images.githubusercontent.com/9626336/59501264-bc4b4480-8ecd-11e9-8ece-5c7bf20aaf06.gif)

**Comment by SimonaliaChen** [comment]
`v-model`, not `:model`
