### ISSUE TITLE
[Bug Report] Not displayed correctly in cascader

### ISSUE THREAD

**Issue by DangoSky** [ElemeFE/element#16068]
### Element UI version
0.1.0

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/DangoSky/7osfp265/1/

### Steps to reproduce
As I tested in jsfiddle, I chose the cascading path normally, but the path shown is not the same as what I chose.  What surprised me even more is that if add a parameter to the third-level data, the results will be displayed normally.

### What is Expected?
Can display the path I chose.
![2](https://user-images.githubusercontent.com/42209399/59499730-92dce980-8eca-11e9-814d-4bb50fe4e072.gif)

### What is actually happening?
Its first and second level data is unchanged, only changed third level data.
![1](https://user-images.githubusercontent.com/42209399/59499736-97090700-8eca-11e9-8b35-24cacf5e24b3.gif)

**Comment by luckyCao** [comment]
#16393
