### ISSUE TITLE
[Bug Report] Vue implements bidirectional binding to VUEX invalidation using get of computational attributes and set

### ISSUE THREAD

**Issue by q820898** [ElemeFE/element#16061]
### Element UI version
2.9.1

### OS/Browsers version
mac chrome最新

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
https://segmentfault.com/q/1010000019477538?_ea=12964625

### What is Expected?
期待可以把表单数据绑定到vuex

### What is actually happening?
不能get

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
