### ISSUE TITLE
[Bug Report] Table height changes to 100px (en: el-table forced the style height 100px)

### ISSUE THREAD

**Issue by zyouzz** [ElemeFE/element#16064]
### Element UI version
0.1.0

### OS/Browsers version
Google Chrome

### Vue version
2.5.20

### Reproduction Link
http://giser.tk/2019/06/14/38442.html

### Steps to reproduce
之前使用2.8.1版本正常，更新版本2.9.1后，

### What is Expected?
表格高度自适应

### What is actually happening?
表格高度都强制设为100px

**Comment by zyouzz** [comment]
Reproduction Link[http://giser.tk/2019/06/14/38442.html](url)

**Comment by libbGit** [comment]
我也遇到这个问题了，:height="100%"  时 默认会转化为100px

**Comment by Mutoumiao** [comment]
同样遇到该问题，并切换回 2.8.2版本，正常

**Comment by BurningBing** [comment]
我也遇到了这个问题，在源码table.js的418行，找到一个方法`parseHeight`,
```
function parseHeight(height) {
  if (typeof height === 'number') {
    return height;
  }
  if (typeof height === 'string') {
    if (/^\d+(?:px)?/.test(height)) {
      return parseInt(height, 10);
    }
    console.warn('[Element Warn][ElTable]invalid height and it will be ignored.');
  }
  return null;
}
```

不是很明白为什么要把所有传过来的height都转成int?

**Comment by ziyoung** [comment]
@BurningBing 提了一个 pr，修复了该问题，你可以 review 一下。
