### ISSUE TITLE
[Feature Request] Lack of splitter components

### ISSUE THREAD

**Issue by huangshiqiang** [ElemeFE/element#16078]
### Existing Component
否

### Component Name
el-splitter

### Description
目前element-ui组件还缺少一个很常用的组件，就是布局窗口的时候，把窗口拆分成几个可拖拽大小的区域。目前市面上比较好用的有jQuery Splitte，github上面也有一些这样的组件，但是存在不少bug，而且集成比较麻烦。如果element原生可以提供就完美了。。

**Comment by island205** [comment]
pr welcome, we will consider your advise.

**Comment by haoranyu** [comment]
@huangshiqiang
