### ISSUE TITLE
[Bug Report] Dynamic props in notify.message's vnode

### ISSUE THREAD

**Issue by qishibo** [ElemeFE/element#16075]
### Element UI version
2.4.11

### OS/Browsers version
linux

### Vue version
2.5.22

### Reproduction Link
https://gist.github.com/qishibo/0eea120c40d58e5e3e955ab25c842866

![image](https://user-images.githubusercontent.com/5136418/59514579-bcf4d280-8eef-11e9-83f9-f40c96adf17a.png)

### Steps to reproduce
the `percentage` prop not changed in the progress component

### What is Expected?
the `percentage` prop changed in the progress component

### What is actually happening?
the `percentage` prop not changed in the progress component

**Comment by lainlee** [comment]
up
same problem

**Comment by zhixinpeng** [comment]
我也遇到这个问题，不知道如何解决

**Comment by qishibo** [comment]
Now I can do it in this way.

```javascript
this.$notify({
  message: h('el-progress', {
    props: {
      percentage: 0,
    },
    ref: 'downloadProgressBar',
  }),
});

this.$set(this.$refs.downloadProgressBar, 'percentage', 99);

```

**Comment by zhixinpeng** [comment]
percentage is a prop, vue  avoid mutating a prop directly

**Comment by tecnoloco** [comment]
The best way I found to do this:

`
this.notificationInstance.$slots.default[0].componentInstance.$data.yourComponentMessageData = "something"
`

**Comment by konglingwen94** [comment]
直接修改`progress`组件内部的`props.percentage`是可以完成进度条的更新，但是`Vue`不推荐这么做，开发环境下会报警告。但是如果父组件是`notification`这种以`API`形式调用渲染的话，我又不知道如何传递`percentage`属性的值给`progress`,目前我知道的方案是在上下文组件内直接以模板的形式调用`progress`组价，然后在动态渲染到`notification`组件内。

**Comment by JianLin176** [comment]
> Now I can do it in this way.
> 
> ```js
> this.$notify({
>   message: h('el-progress', {
>     props: {
>       percentage: 0,
>     },
>     ref: 'downloadProgressBar',
>   }),
> });
> 
> this.$set(this.$refs.downloadProgressBar, 'percentage', 99);
> ```

Sometime i can't get ref through `this.$refs.downloadProgressBar `(undefined).   Have you ever had same problem？
