### ISSUE TITLE
[Bug Report] el-select could not free memory

### ISSUE THREAD

**Issue by QMZhao** [ElemeFE/element#16074]
### Element UI version
2.9.1

### OS/Browsers version
75.0.3770.80（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
https://codepen.io/anon/pen/EBVMRp

### Steps to reproduce
通过点击请求后台的数据渲染到el-select上(最多的数据大概有700条)，重复点击40次左右，会导致内存增加到2G左右且无法释放

### What is Expected?
占用的内存得到释放

### What is actually happening?
路由跳转之后占用的内存依然存在无法释放

![image](https://user-images.githubusercontent.com/35327942/59503580-582b7f00-8ed3-11e9-8eff-223434851d2a.png)

**Comment by Zeus-Iqd** [comment]
@ziyoung 引入新bug了，大佬 。

**Comment by island205** [comment]
@Zeus-Iqd 什么 bug？

**Comment by zh-rocco** [comment]
> @Zeus-Iqd 什么 bug？

和 `filter-method` 冲突; 使用 `filter-method` 动态修改 selectList 模拟拼音搜索时会导致已选中的数据展示异常, [异常原因](https://github.com/ElemeFE/element/blob/dev/packages/select/src/select.vue#L518)
