### ISSUE TITLE
When the final value of Cascader cascade selector is 0, the option cannot be displayed correctly.

### ISSUE THREAD

**Issue by SPARON** [ElemeFE/element#16072]
### Element UI version
0.1.0

### OS/Browsers version
windows10/chrome 74

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/kpauesvj/

### Steps to reproduce
选择A11，或B11

### What is Expected?
选择A11，B11时，值能正常显示

### What is actually happening?
选择A11，B11时，值不能正常显示

**Comment by SPARON** [comment]
各级值相同时会出现这种情况。

**Comment by Zsynuting** [comment]
@SPARON 高层节点不同，低层节点相同会出现这种情况，2.9.1存在这样的问题

**Comment by luckyCao** [comment]
#16393
