### ISSUE TITLE
[Feature Request] Add icon slot for el-button

### ISSUE THREAD

**Issue by stalniy** [ElemeFE/element#16076]
### Existing Component
Yes

### Component Name
button

## Issue

Currently the only way to change icon is to pass a custom class. Sometimes I need to pass `svg` or `img` element but can't. 

So, I suggest to add `icon` slot:

```html
<el-button>
  <img src="path/to/img.png" slot="icon">
  my text
</el-button>
```

## Why is it better?

Currently I can do this:

```html
<el-button>
  <img src="path/to/img.png">
  my text
</el-button>
```

but then I need to align "my text" and img by using additional css and sometimes I need to wrap `my text` in additional <span>

**Comment by libbGit** [comment]
我觉得完全没这个必要， 相反你这是啥吗？  要是button下有slot，谁知道你这个图形，符不符合规范。 icon属性完全足够， 阿里巴巴字体库，一键生成icon，有N个供你选

**Comment by island205** [comment]
Sorry, we have no plan to support this.
