### ISSUE TITLE
[Bug Report] Cascader cascade selector does not fully display drop-down options in IE11

### ISSUE THREAD

**Issue by tower1229** [ElemeFE/element#16080]
### Element UI version
2.9.1

### OS/Browsers version
Windows10/IE11

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/tower1229/pen/JQGMXz

### Steps to reproduce
下拉选项文字显示不全

### What is Expected?
跟chrome一样，尽可能扩展下拉框的宽度，显示更多字符

### What is actually happening?
下拉框宽度塌缩，文字显示不全

**Comment by tower1229** [comment]
![QQ截图20190615144550](https://user-images.githubusercontent.com/4016839/59548123-a6e12380-8f7c-11e9-8190-e390e45583be.png)
IE效果如图

**Comment by tower1229** [comment]
![111](https://user-images.githubusercontent.com/4016839/59548128-c710e280-8f7c-11e9-8aaf-2a42ac60b0d3.png)
Chrome的效果正常

**Comment by lzxil00** [comment]
Same problem, please fix it, thx very much! 🙏
