### ISSUE TITLE
[Bug Report] ElTable is shaking wildly

### ISSUE THREAD

**Issue by rickysang** [ElemeFE/element#16089]
### Element UI version
2.9.1

### OS/Browsers version
Window7 / Chrome 75.0.3770.90

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/ydOvRd

### Steps to reproduce
1. 在Windows系统下打开重现链接
2. 查看表格

### What is Expected?
ElTable没有抖动

### What is actually happening?
表格在某些高度（通常是滚动条即将出现时）下出现抖动，根本停不下来

**Comment by rickysang** [comment]
Attach screenshot for your information
![ElTable shake](https://user-images.githubusercontent.com/19810448/59584583-fc4e3980-9110-11e9-87ad-85971192c73c.gif)

**Comment by happyday517** [comment]
我也遇到了同样的问题

**Comment by njzzz** [comment]
chrome最新版本有这个问题，不知道咋回事
把表格的 border-collapse给改了就好了
.el-table__header,.el-table__body,.el-table__footer{
    border-collapse: collapse!important;
}

**Comment by oulafen** [comment]
我这儿设置border-collapse不管用

后来将表格外层元素的width宽度为减去滚动条的宽度就解决了
类似这样：
<div :style={width: `calc(100% - ${scrollbarWidth})`}>
    <el-table/>
</div>

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/16167#issuecomment-506598890
