### ISSUE TITLE
[Bug Report] Cascader Component Version 2.9 bug

### ISSUE THREAD

**Issue by linvic** [ElemeFE/element#16085]
### Element UI version
2.9.1

### OS/Browsers version
window

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/YoqxRy

### Steps to reproduce
当级联一级和二级值相同时，如 “北京市/北京市” 级联框中显示不了选中值

### What is Expected?
应当在级联框中显示选中的值

### What is actually happening?
级联框中无值显示，但实际数据值已更改

**Comment by zhijunw** [comment]
这个要保证 value 值的唯一性  由于你的value值配置的是name  但是你name是一样的 所以会出错

你也可以 props 里面设置   checkStrictly:true  也可以解决

**Comment by linvic** [comment]
> 这个要保证 value 值的唯一性 由于你的value值配置的是name 但是你name是一样的 所以会出错
> 
> 你也可以 props 里面设置 checkStrictly:true 也可以解决

谢谢，这个在2.8.2版本以下是没有这样的问题的，我想使用 InfiniteScroll 无限滚动组件所以升级了，但是我并不想要checkStrictly:true 的效果，而是希望选中最后一级才显示。

**Comment by zhijunw** [comment]
这是2.9.1的问题    cascader  默认都是选择了最后一级才显示 在页面上的啊
 你也可以 把value 设置成 你optionsData 里面的 唯一性 也可以解决

**Comment by linvic** [comment]
> 这是2.9.1的问题 cascader 默认都是选择了最后一级才显示 在页面上的啊
> 你也可以 把value 设置成 你optionsData 里面的 唯一性 也可以解决

我明白，但是我需求如此，需要的是name值，如果把 value 设置成 id 也是可以解决这个问题的，那这样我就要遍历原数据去取 name 值了，而且反选的时候同样需要再次遍历查id值，这样麻烦了很多。2.8.2版本以下没有这样的问题，所以我说这是一个bug

**Comment by zhijunw** [comment]
嗯  这个功能 还不成熟  你可以先不升级

**Comment by codesboy** [comment]
同样的问题当后端传来的数据格式是下面这种形式的时候，2.8.2以上的版本就会有问题

**Comment by zhijunw** [comment]
可以 试着改 源码    我觉得 下一个版本 应该会解决这方面的问题

**Comment by linvic** [comment]
我又发现一个差异，这样的交互并没有2.8版本好

选择多级选项之后 回显仅一级数据时，子集选项没有清空

图一：2.8版本
![2-8](https://user-images.githubusercontent.com/15717316/60090807-cbf04600-9775-11e9-8910-0289be74b314.gif)
图二： 2.9.2版本，交互并不好
![2-9](https://user-images.githubusercontent.com/15717316/60090814-ce52a000-9775-11e9-8589-9dddd6994ea8.gif)

**Comment by linvic** [comment]
![image](https://user-images.githubusercontent.com/15717316/60146330-ce957e80-97fb-11e9-9d14-97022c66fa85.png)
应该是同一个bug导致

**Comment by zhangchaoxu** [comment]
发现类似问题，在2.8.2+的版本。
在编辑页面，第一次显示的时候正常显示。
后面再显示的时候，Cascader的值已经选中了，但是一直不显示在框内。

**Comment by chenjianan0823** [comment]
我也遇到了类似的问题，不过出现bug的情况不是 (级联一级和二级值相同时，如 “北京市/北京市” ),出现bug的原因很怪异，退回到2.8.2就恢复正常了。

**Comment by zakiFaner** [comment]
同感昨天也碰到了这个问题，头皮发麻。。。而且选择的数据跟展示的数据不一致

**Comment by luckyCao** [comment]
#16324

**Comment by axhello** [comment]
解决了么？最新版本还有这问题啊！

**Comment by linvic** [comment]
> 解决了么？最新版本还有这问题啊！

并没有解决

**Comment by codesboy** [comment]
> 解决了么？最新版本还有这问题啊！

这个问题规划到了2.11.0版本去解决了

**Comment by zhangchaoxu** [comment]
@codesboy 请问，2.11.0发布时间有计划吗？

**Comment by axhello** [comment]
> > 解决了么？最新版本还有这问题啊！
> 
> 这个问题规划到了2.11.0版本去解决了

哦 好吧 谢谢了，现在先降到2.8.2去了，等解决了再升级

**Comment by codesboy** [comment]
> @codesboy 请问，2.11.0发布时间有计划吗？

![image](https://user-images.githubusercontent.com/9047357/61763373-c71bc200-ae07-11e9-8fcd-9ff0d5b2a34f.png)

**Comment by zhangchaoxu** [comment]
感谢，辛苦 @codesboy
