### ISSUE TITLE
[Bug Report] Executes the toggleRowSelection method of the table component, which automatically triggers the @select event

### ISSUE THREAD

**Issue by libbGit** [ElemeFE/element#16090]
### Element UI version
0.1.0

### OS/Browsers version
win10/ chrome 74  /  element 2.9.1

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/libbgit/pen/BgKrxX

### Steps to reproduce
我在vuex中定义一个state， 而在组件中由于编辑时，需要勾选中新建时的table行，所以执行toggleRowSelection，而每执行一次，就触发一次@select事件。 而我的table data是从vuex 的state来的，当点击鼠标勾选时 触发@select，并更新vuex的state。  但是当执行10次toggleRowSelection，@select也执行10次，导致最后的vuex的state 被覆盖了。  

### What is Expected?
执行toggleRowSelection不应该自动触发 @select 和 @selection-change事件

### What is actually happening?
执行toggleRowSelection 却自动触发了  @select 和 @selection-change事件

**Comment by ziyoung** [comment]
fixed in 2.10.0

**Comment by blockmood** [comment]
@ziyoung   我目前是2.12.0的版本，还是会复现这个问题。

**Comment by shivamkumar110** [comment]
@ziyoung  I am currently at version 2.13.0 and can still reproduce this issue.

**Comment by ms314006** [comment]
@ziyoung I am currently at version 2.13.1 and can still reproduce this issue.

**Comment by xtgcs** [comment]
2.13.1还有这个bug
