### ISSUE TITLE
[Bug Report] Because of inheritance of CSS attributes, ElFormItem's internal components are highly enlarged

### ISSUE THREAD

**Issue by fxxjdedd** [ElemeFE/element#16092]
### Element UI version
2.9.1

### OS/Browsers version
版本 74.0.3729.169（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/QXNrpv

### Steps to reproduce
查看 `el-form-item` 内组件的表现

### What is Expected?
他们的line-height最好不要继承自 `el-form-item` ，或者想办法覆盖掉继承的属性，以保证这些组件表现正常

### What is actually happening?
`el-input`, `el-alter`, `el-link` 这三个会因为继承了 `el-form-item` 而表现异常，我没有测试全部组件在 `el-form-item` 的内部行为，但是他们的确也可能存在这个问题

**Comment by island205** [comment]
Sorry, we have no plan to support this now.
