### ISSUE TITLE
动态增减表单项里的prop写法与其他表单的prop不一样，那么使用validateField这个方法怎么传props

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/element#1609]
![image](https://cloud.githubusercontent.com/assets/13248613/20967854/57aaf394-bcbc-11e6-81dc-65ecf83730ed.png)

props这样写 但是我要使用validateField
![image](https://cloud.githubusercontent.com/assets/13248613/20967866/5e3ee382-bcbc-11e6-8f45-d0874758313d.png)

里面的prop怎么写

![image](https://cloud.githubusercontent.com/assets/13248613/20967860/5b0d129c-bcbc-11e6-8489-bcdf9d958ab8.png)
这样写是不对的啊，有什么方法吗

**Comment by baiyaaaaa** [comment]
你这个应该是以前的文档了吧，文档上应该是这么写的
![image](https://cloud.githubusercontent.com/assets/3655403/20976429/7ed37ce0-bcdd-11e6-918b-2ee49fcc1bc7.png)

**Comment by PmcFizz** [comment]
大佬你好 ，我也遇到了差不多的问题,  目前validateField支持多个字段了，  如果我要验证domains这个数组 是要怎么写？
```
$vm0.validateField(['domains.0.value','domains.1.value','domains.2.value','domains.3.value']) 
```
这样写吗？
我用`$vm0.validateField(['domains']) `  无法生效
还望大佬能解惑一下，如果使用validateField校验 动态数组 domains ? @baiyaaaaa
