### ISSUE TITLE
[Bug Report] Selector Fous Method Failure

### ISSUE THREAD

**Issue by Lozvoe** [ElemeFE/element#16094]
### Element UI version
2.9.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lozvoe/pen/LKNJxq?&editable=true

### Steps to reproduce
点击展开按钮

### What is Expected?
出现下拉框

### What is actually happening?
没有出现下拉框 只高亮显示边框

**Comment by island205** [comment]
pr welcome
