### ISSUE TITLE
[Bug Report] 给表格列 Table-column设置为多选框 type='selection' 同时增加 v-if ，checkBox右边会多一个“.”

### ISSUE THREAD

**Issue by paranoidLyy** [ElemeFE/element#16096]
### Element UI version
2.9.1

### OS/Browsers version
macOS 10.13.6

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
给表格列 Table-column设置为多选框 type='selection' 同时增加 v-if ，checkBox右边会多一个“.”

### What is Expected?
checkBox右边没有点

### What is actually happening?
checkBox右边会多一个“.”
![image](https://user-images.githubusercontent.com/39749980/59595135-cc5e6080-9127-11e9-97ec-45bda0b63bb1.png)

**Comment by paranoidLyy** [comment]
2.4.11版本的问题，2.9.1无问题

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
