### ISSUE TITLE
[Feature Request] How to add I18N for datepicker shortcuts?

### ISSUE THREAD

**Issue by ositowang** [ElemeFE/element#16102]
### Existing Component
是

### Component Name
datePicker

### Description
I am working on internationalizing a project built  with element-ui. When I try to add i18n for the datepicker shortcuts, I always get the `TypeError: Cannot read property '_t' of undefined` error no matter I use `this.$t()` or set a getter for the `vue_i18n`
```javascript
//i18n 
{
  //....other things
 "datepickerOptions":{
  "today":"Today"
}


//pickeroptions
{
//....other things
shortcuts: [
      {
        text: this.todayI18n,       //"TypeError: Cannot read property '_t' of undefined"
        onClick(picker: any) {
          const end = new Date();
          const start = new Date();
          picker.$emit("pick", [start, end]);
        },
      ]
}


// component
export default class Component extends Vue {
//....other things
public get todayI18n(){
    return this.$t('datepickerOptions')['today'];
  }
}
```

Is there any way for  configuring the i18n for datepicker shortcuts?

**Comment by ziyoung** [comment]
Please read doc carefully. It's no Element bug
