### ISSUE TITLE
[Bug Report] Dialog control automatically closes if the mouse exceeds the Dialog area when selecting the content of the mouse control

### ISSUE THREAD

**Issue by yanglanlan** [ElemeFE/element#16103]
### Element UI version
2.9.1

### OS/Browsers version
chrome74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yangwenchong/pen/QXEOLY

### Steps to reproduce
1、点击点击打开 Dialog
2、在打开的Dialog试图圈选“”这是一段信息“”
3、鼠标点击“这是一段信息” 并按住,试图圈选内容，按住鼠标并移出Dialog，移出Dialog后释放鼠标按钮，Dialog出现关闭。

### What is Expected?
Dialog关闭是在Dialog区域外点击才关闭。不包括我选择内容时鼠标移出Dialog区域外

### What is actually happening?
内容时鼠标移出Dialog区域外自动关闭。此操作包括输入框内容。对输入框内容进行全选时，如果鼠标移出Dialog区域释放同样存在关闭情况

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
