### ISSUE TITLE
[Bug Report] cascader incorrectly displays the path in the input box

### ISSUE THREAD

**Issue by hoythan** [ElemeFE/element#16106]
### Element UI version
2.9.1

### OS/Browsers version
macos chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/hoythan/pen/pXbLJX

### Steps to reproduce
当你选择
选项 1 > 选项 2 > 所有选项 2
的时候，value 的值是正确的，但是 input 上显示的路径是错误的。

### What is Expected?
应该显示的是 
选项 1 / 选项 2 / 所有选项 2

### What is actually happening?
但实际情况它都会显示第一个选项的子项的第一项
选项 1 / 所有选项 1

**Comment by hoythan** [comment]
另外你们提 bug 的链接的 element 版本只能选择 0.1.0

**Comment by hoythan** [comment]
#16085

如果这是 bug，我可以提交一个修复。
如果认为是合理的设计，请 Close 这个issue。

**Comment by 438345494** [comment]
给你点赞👍

**Comment by island205** [comment]
Duplicate of #16377
