### ISSUE TITLE
[Bug Report] InfiniteScroll naming issues cause InfiniteScroll dependencies not to be found

### ISSUE THREAD

**Issue by btr-wwj** [ElemeFE/element#16101]
### Element UI version
2.9.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
因项目在本地运行时即被发现，所以暂无上线

### Steps to reproduce
升级或安装element-ui2.9.1版本时通过按需引入InfiniteScroll，项目是在本地运行，所以上述链接为官网demo链接，但也发现问题

### What is Expected?
InfiniteScroll可以正常使用，node_module中正确命名需为infinite-scroll

### What is actually happening?
升级或安装完之后运行时发现InfiniteScroll依赖不存在

**Comment by iamkun** [comment]
已修复
