### ISSUE TITLE
功能建议：为 el-tabs 添加 v-model 用法

### ISSUE THREAD

**Issue by stackia** [ElemeFE/element#1610]
### ElementUI version
1.0.5

### OS/Browers version
Windows 10 / Chrome 54

### Vue version
2.1.4

### What is Expected?
希望能够为 el-tabs 加入 v-model 用法以取代目前 active-name 属性。
这样可以通过控制 v-model 变量来指定当前激活的 tab，同时手动选择其他 tab 后能够将当前选中 tab 反馈到变量中。

**Comment by Kingwl** [comment]
感觉没必要。。。。

**Comment by stackia** [comment]
@Kingwl 我觉得还是有一定的好处的：
1. 很多时候需要知道当前选中的 tab，目前只能通过在 tab-click 事件里手动获得
2. 如果 active-name 绑定到变量时，手动点选了其他 tab，会造成外部变量和实际 active-name 不一致情况造成误解

**Comment by Kingwl** [comment]
1.随便一个回调就解决的事情

> 2.文档：`active-name	选中选项卡的 name	strin 	第一个选项卡的 name`

**Comment by stackia** [comment]
@Kingwl 
当然能在 tab-click 里面手动设置，只是啰嗦一些。此外也有一个小问题，现在 tab-click 回调的参数是 Tab 实例，文档没有给 Tab 实例的 API 说明，还得手动 console.log 一下才能知道。

比如你看这两个 issue，都是由于这个不合理的设计造成的疑问/误解：
https://github.com/ElemeFE/element/issues/1147
https://github.com/ElemeFE/element/issues/247

**Comment by wanghaolu** [comment]
这个可以有，既然active-name在官方文档里面的说明是“选中选项卡的 name”，那么在当前选项卡发生变化的时候这个值也应该随着变化，否则就造成了选择项和active-name不对应。我现在也是用tab-click来实现，但总感觉不方便。能用v-model就最好了

**Comment by baiyaaaaa** [comment]
v-model 的用法会在1.1版本中提供支持

**Comment by yuanyuanshen** [comment]
：active-name=“XXX”不就是绑定变量XXX=a,那么当前定位的就是a这个tab页啊，虽然element没有提供，但是这个功能本来就有啊。不要忘了vue他自带的v-bind啊。你说的这个功能完全存在呀

**Comment by stackia** [comment]
@yuanyuanshen 你说的是单向绑定。这个issue讨论的是使用v-model进行双向绑定。vue2.0是已经没有.sync修饰符的，必须通过v-model来双向绑定。
