### ISSUE TITLE
[Feature Request] Please don't add style inside the El self-built tag. The priority is too high to control.

### ISSUE THREAD

**Issue by wheng82** [ElemeFE/element#16105]
### Existing Component
是

### Component Name
el-pagination

### Description
<div class="el-pagination is-background" style="margin-top: 30px;">  源代码中强制加了margin-top  如果我想在表头尾都加分页，这个强制的上面空出30px 就会很不合理，希望能够去除这类的强制控制

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
