### ISSUE TITLE
[Bug Report] InputNumber precision rounded

### ISSUE THREAD

**Issue by noteScript** [ElemeFE/element#16119]
### Element UI version
2.9.1

### OS/Browsers version
Chrome  74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
InputNumber组件内使用的toPrecision方法内使用了toFixed对小数进行了处理，这个导致了处理结果为四舍五入，不符合业务要求。

### What is Expected?
在本次业务中直接截取即可，期待官方能够保留多种截取小数的方案以适应不同的业务场景。

### What is actually happening?
组件中displayValue方法没有使用toPrecision处理？

临时解决方案：

import {InputNumber} from 'element-ui';

InputNumber.methods.toPrecision = function(num,  precision) {
  if (precision === undefined) precision = this.numPrecision;
  return Number(String(num).match(new RegExp(`^\\d (?:\\.\\d{0,${precision}})?`)));
};

InputNumber.computed.displayValue = function() {
  if (this.userInput  !==  null) {
    return this.userInput;
  }
  const currentValue = this.currentValue;
  if (typeof currentValue  ===  'number'  &&  this.precision  !==  undefined) {
    return this.toPrecision(currentValue, this.precision);
  } else {
    return currentValue;
  }
};

Vue.use(InputNumber);

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by watership** [comment]
I have the same problem,  don't need round sometimes.

**Comment by g7tro4w** [comment]
+1 same issue

**Comment by plugn** [comment]
+1 please fix it!

**Comment by lokky2082** [comment]
+1

**Comment by VladFedotov** [comment]
+1

**Comment by Daiver13** [comment]
+1

**Comment by JoyMefisto** [comment]
+1

**Comment by jswxwxf** [comment]
+1

**Comment by jswxwxf** [comment]
最好加一个属性可以不四舍五入

**Comment by zimuZhao** [comment]
+1
