### ISSUE TITLE
[Bug Report] Не рабочий пример и не верная смена знаков

### ISSUE THREAD

**Issue by Luummii** [ElemeFE/element#16113]
### Element UI version
2.9.1

### OS/Browsers version
Version 74.0.3729.169 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
Этот пример не работает
https://codepen.io/pen/?&editable=true

для рейтинга с рожами - https://element.eleme.io/#/en-US/component/rate

### What is Expected?
Если в кастомизированном ретйнге применить disabled, то по умолчанию кастомизация перестает работать и устанавливаются звезды.
Пример, который выше когда почините поставте в компонент disabled.

### What is actually happening?
На самом деле, кастомизированных знаков не видно.

Это для желающих про язык поговорить - https://github.com/ElemeFE/element/issues/15177#issuecomment-485271139

**Comment by iamkun** [comment]
pr welcomed

**Comment by Luummii** [comment]
Почему закрыли?
