### ISSUE TITLE
[Bug Report] Custom theme function bug, element-ui2.9.1 does not exist theme-chalk file

### ISSUE THREAD

**Issue by fengzhineng1** [ElemeFE/element#16111]
### Element UI version
2.9.1

### OS/Browsers version
macOS 10.13.6

### Vue version
2.5.22

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
按照官方文档显示需要引入element-ui的样式，实际上element-ui 2.9.1的packages下没有theme-chalk这个文件

@import "~element-ui/packages/theme-chalk/src/index";

后来使用命令行主题的方式安装了element-theme和element-theme-chalk，没有et的命令可以执行。

### What is Expected?
安装elemnt-ui/packages下存在theme-chalk文件

### What is actually happening?
安装elemnt-ui/packages不存在theme-chalk文件，但是官方文档中引用了不存在的文件

**Comment by iamkun** [comment]
lib/theme-chalk/
Version:
