### ISSUE TITLE
[Bug Report] Table height can only be set with Number?

### ISSUE THREAD

**Issue by BurningBing** [ElemeFE/element#16115]
### Element UI version
2.9.1

### OS/Browsers version
MacOS / Chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
1. I have a div[height: 500px] and put a el-table  in it.
2. Give a height value with '100%'

### What is Expected?
The table height should by the same with it's parent element, 500px

### What is actually happening?
But the height of the table's container is '100px'.
I saw the source file :node_modules/element_ui/lib/table.js, there is a function named 【parseHeight】at line 418. 
```
function parseHeight(height) {
  if (typeof height === 'number') {
    return height;
  }
  if (typeof height === 'string') {
    if (/^\d (?:px)?/.test(height)) {
      return parseInt(height, 10);
    }
    console.warn('[Element Warn][ElTable]invalid height and it will be ignored.');
  }
  return null;
}

```

I do not understand why convert all types to integer ?

**Comment by ziyoung** [comment]
#15858
