### ISSUE TITLE
[Feature Request] Table: selectable

### ISSUE THREAD

**Issue by yyjjqq94** [ElemeFE/element#16117]
### Existing Component
是

### Component Name
Table

### Description
selectable这个属性，感觉不应该提供index这个参数。Table组件提供了排序功能，好几个sort相关属性。这个时候如果根据index判断row是否可选，就有点混乱了。
这两个属性组合有个很明显的问题，比如选中某一行数据，然后排序，根据index认定它是不可选的，这个时候就变成了选中 禁选状态。

**Comment by ziyoung** [comment]
Table 的 rowKey 你可以不指定。当 rowKey 不存在时，会使用 index。历史包袱，到大版本中修复了。
