### ISSUE TITLE
[Bug Report] DatePicker - When opened and input field loses focus, escape key does not dismiss popover

### ISSUE THREAD

**Issue by nick-somebody** [ElemeFE/element#16123]
### Element UI version
2.9.1

### OS/Browsers version
All

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element

### Steps to reproduce
Go to docs site https://element.eleme.io/#/en-US/component/date-picker#datepicker

Click input field for date

Navigate a month

Hit escape key

### What is Expected?
The escape key should always dismiss the popover. I looked at other components where the popover is used and the appropriate field that the popover is attached to retains focus while the popover is open, so escape key always works to dismiss the popover.

### What is actually happening?
When the date picker's input field loses focus, the escape key does not dismiss the popover.

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by nick-somebody** [comment]
@ziyoung The issue can be reproduced on the docs site. It is a valid reproduction link. Please reopen.
