### ISSUE TITLE
[Bug Report] select selector clicks multiple times to select, causing the page to get stuck and refresh automatically

### ISSUE THREAD

**Issue by klosekunhong** [ElemeFE/element#16126]
### Element UI version
2.4.6

### OS/Browsers version
edge

### Vue version
2.5.17

### Reproduction Link
jsfiddle

### Steps to reproduce
反复点击选择框不同选项

### What is Expected?
正常情况下，选择框多次选择则不会造成页面卡住，也不会使页面刷新

### What is actually happening?
多次连续选择后页面会卡住并刷新页面

**Comment by huangwei1226** [comment]
我也遇到这个问题了，困扰了好久，感觉跟滚动条也有关系，如果选择之后滚动会更容易复现，求解决方案

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
