### ISSUE TITLE
[Bug Report] 2.9.1 Packed forms are not displayed and data are not filled

### ISSUE THREAD

**Issue by tomatojacky** [ElemeFE/element#16121]
### Element UI version
2.9.1

### OS/Browsers version
win 10 / chrome 74.0.3729.169（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net

### Steps to reproduce
项目上线一个月，开发，生产一切正常，element-UI版本2.8.2，
中午升级2.9.1之后 ，其它东西都未修改
开发环境 一切正常，打包后页面里所有表格不显示。
控制台无任何异常

### What is Expected?
修复此bug

### What is actually happening?
期待修复此bug

**Comment by fakaka** [comment]
我是在 electron-vue 里面不显示，暂时退回到2.8.2了

**Comment by tomatojacky** [comment]
我回退2.9.0了，暂时将就着用

**Comment by pweasd** [comment]
solution: https://github.com/SimulatedGREG/electron-vue/issues/361

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
