### ISSUE TITLE
[Feature Request] [el-table] 1) Radio mode 2) Check to cancel hook function 3) Display full selection

### ISSUE THREAD

**Issue by edwards19900128** [ElemeFE/element#16129]
### Existing Component
是

### Component Name
el-table

### Description
请教下row type="selection" 情况下，是否可以实现标题三个需求
1）单选模式 
2）选中check取消钩子函数 
3）是否显示全选

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
