### ISSUE TITLE
[Bug Report] The cell-click event can't trigger when i click the select component in the table

### ISSUE THREAD

**Issue by MoonyPoet** [ElemeFE/element#16130]
### Element UI version
2.4.2

### OS/Browsers version
window 10

### Vue version
2.5.2

### Reproduction Link
https://codepen.io/moonypoet/pen/pXEmBO

### Steps to reproduce
Click all cell of the table, and that will show the cell name on the top but cell "test2"

### What is Expected?
Trigger the cell-click event when i click cell "test2"

### What is actually happening?
when i click cell "test2", the cell-click event is not triggered

**Comment by ziyoung** [comment]
ElSelect prevents event propagation.
