### ISSUE TITLE
[Bug Report] Table Component Fixed Background Color Setting Error

### ISSUE THREAD

**Issue by RichardGH** [ElemeFE/element#16133]
### Element UI version
2.9.1

### OS/Browsers version
Windows/Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
1、修改样式文件参数
$--table-border-color: #DDCAB4 !default;

2、使用elTable组件border，并且存在fixed列

样式table.scss中第320行，此处参数设置错误

background-color: $--border-color-lighter;

### What is Expected?
fixed的列最后一行下边框颜色和其他列一致

### What is actually happening?
fixed的列最后一行下边框颜色和其他列不一致

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
