### ISSUE TITLE
Special scenario bugs in [Bug Report] Input component V-model

### ISSUE THREAD

**Issue by xiemms** [ElemeFE/element#16137]
### Element UI version
2.9.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xia_mm/pen/XLNmgW?&editable=true

### Steps to reproduce
1. 输入框输入内容即可

### What is Expected?
输入的内容可同步至data对应的数据中

### What is actually happening?
输入的内容未同步值data中 （因为绑定的为obj.key 的形式绑定到v-model中，data初始化 obj为一个空对象，但是在mounted的时候 设置了 this.obj.key 值, 就出现这个问题了，如何在不修改业务代码逻辑的情况下 兼容这种情况...）

**Comment by Alexeykhr** [comment]
In mounted replace:
```this.input.asd =''```
on
```this.$set(this.input, 'asd', '')```

Also for `input2`

**Comment by xiemms** [comment]
我也知道有办法避免呀。。。 发出来的目的是想看看有没有什么根本的解决方案，理论上来说这是vue的bug。直接用 input是没问题的。

**Comment by Alexeykhr** [comment]
This is related to Vue itself, here's an example without a framework:
https://codepen.io/Alexeykhr/pen/mZLNVM

**Comment by xiemms** [comment]
i know this. but i want to know have any way to solve this problem in vue components. not in business code
