### ISSUE TITLE
[Bug Report] Pagination component can't set currentPage prop except for currentChange hook

### ISSUE THREAD

**Issue by mhy-web** [ElemeFE/element#16132]
### Element UI version
2.4.6

### OS/Browsers version
MacOS 10.14.5 / chrome 75.0.3770.100

### Vue version
2.5.17

### Reproduction Link
https://codesandbox.io/s/vue-template-m38z0

### Steps to reproduce
```
<el-pagination
    :current-page.sync="params.page_index"
    :page-size="params.page_size"
    :total="page.total"
    @current-change="handleCurrentChange"/>

...

data() {
    return {
        params: {
            page_index: 1, // default  value is 1
            page_size: 10
        }
  }
}
computed: {
    ...mapGetters(['cachedRoutes'])
},
mounted() {
    this.getQuery() // call this function when back from other router
},
methods: {
    getQuery() {
        this.params = Object.assign({}, cachedRoutes, {
            page_index: cachedRoutes.page_index // value of page_index form vuex is 2, but show on the page is default form data 
        },
    },
    // save params to vuex , and value of page_index is 2
    setQuery() {
        ...
    },
    handleCurrentChange(val) {
       // only support to set currentPage value by here
       this.params.page_index = val
    }
}
```

### What is Expected?
Expected to set currentPage prop except for other methods

### What is actually happening?
Pagination component can't set currentPage prop except for currentChange hook.
I save some params of search query to vuex , when I back to this page, and get that params from vuex to reset search params. But pagination component can't not set currentpage value by direct assignment. That only support to set currentPage value by currentChange hook

I want to reappear it in code, but it just show in my project, show the picture. 
currentPage:2,  internalCurrentPage: 1:
![](https://upload-images.jianshu.io/upload_images/6719885-745fd3bcb6f70c70.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by webxmsj** [comment]
> ### Element UI version
> 2.4.6
> 
> ### OS/Browsers version
> MacOS 10.14.5 / chrome 75.0.3770.100
> 
> ### Vue version
> 2.5.17
> 
> ### Reproduction Link
> https://codepen.io/pen/?editors=1010
> 
> ### Steps to reproduce
> ```
> <el-pagination
>     :current-page.sync="params.page_index"
>     :page-size="params.page_size"
>     :total="page.total"
>     @current-change="handleCurrentChange"/>
> 
> ...
> 
> data() {
>     return {
>         params: {
>             page_index: 1, // default  value is 1
>             page_size: 10
>         }
>   }
> }
> computed: {
>     ...mapGetters(['cachedRoutes'])
> },
> mounted() {
>     this.getQuery() // call this function when back from other router
> },
> methods: {
>     getQuery() {
>         this.params = Object.assign({}, cachedRoutes, {
>             page_index: cachedRoutes.page_index // value of page_index form vuex is 2, but show on the page is default form data 
>         },
>     },
>     // save params to vuex , and value of page_index is 2
>     setQuery() {
>         ...
>     },
>     handleCurrentChange(val) {
>        // only support to set currentPage value by here
>        this.params.page_index = val
>     }
> }
> ```
> 
> ### What is Expected?
> Expected to set currentPage prop except for other methods
> 
> ### What is actually happening?
> Pagination component can't set currentPage prop except for currentChange hook.
> I save some params of search query to vuex , when I back to this page, and get that params from vuex to reset search params. But pagination component can't not set currentpage value by direct assignment. That only support to set currentPage value by currentChange hook

Why not modify the corresponding data separately, for example:
> ```
> methods: {
>  getQuery() {
>    this.params.page_index = cachedRoutes.page_index
> }
> ```

[codesandbox](https://codesandbox.io/embed/vue-template-wkixk)

**Comment by mhy-web** [comment]
I had found the reason of this problem.
I set currentPage as the value  cahced, at the same time the prop total has't gotten form request and the value of total is default value 0.

**Comment by ziyoung** [comment]
@mhy-web 重新提交个 pr 吧。

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by iamkun** [comment]
麻烦重新提交一份 pr 谢谢
