### ISSUE TITLE
[Feature Request] 在使用el-table组件时，似乎没有根据数据条件来渲染行的显示。

### ISSUE THREAD

**Issue by MaleDeer** [ElemeFE/element#16149]
在使用 el-table 组件时，想根据数据中的 isShow = true，来判断是否渲染该行数据，
但是在查看文档，并没有找到有该实现。

**Comment by Eflet** [comment]
看上去是个vue新手，你这个需求应该是在computed里面自己实现

**Comment by MaleDeer** [comment]
> 看上去是个VUE新手，你这个需求应该是在计算里面自己实现

如果是计算的计算的时候 去实现的话，我勾选项又会出现一些问题。  😭

**Comment by Eflet** [comment]
```
data() {
    return {
      sourceData: [ /* your source data */],
      selectedData: [/* your selected data */]
    }
  },
  computed: {
    componentData() {
      return this.sourceData.filter(d=> ~this.selectedData.indexOf(d.id))
    }
  },
  methods: {
    select(dataID){
      if(~this.selectedData.indexOf(dataID)){
        this.selectedData = this.selectedData.filter(id=>id != dataID)
      }else{
        this.selectedData = [...this.selectedData, dataID]
      }
    }
  }
```
大概这样，不需要isshow，数据源和被选择的数据分开存放，用computed去动态获取哪些要显示

**Comment by MaleDeer** [comment]
> ```
> data() {
>     return {
>       sourceData: [ /* your source data */],
>       selectedData: [/* your selected data */]
>     }
>   },
>   computed: {
>     componentData() {
>       return this.sourceData.filter(d=> ~this.selectedData.indexOf(d.id))
>     }
>   },
>   methods: {
>     select(dataID){
>       if(~this.selectedData.indexOf(dataID)){
>         this.selectedData = this.selectedData.filter(id=>id != dataID)
>       }else{
>         this.selectedData = [...this.selectedData, dataID]
>       }
>     }
>   }
> ```
> 
> 大概这样，不需要isshow，数据源和被选择的数据分开存放，用计算去动态获取哪些要显示



> ```
> data() {
>     return {
>       sourceData: [ /* your source data */],
>       selectedData: [/* your selected data */]
>     }
>   },
>   computed: {
>     componentData() {
>       return this.sourceData.filter(d=> ~this.selectedData.indexOf(d.id))
>     }
>   },
>   methods: {
>     select(dataID){
>       if(~this.selectedData.indexOf(dataID)){
>         this.selectedData = this.selectedData.filter(id=>id != dataID)
>       }else{
>         this.selectedData = [...this.selectedData, dataID]
>       }
>     }
>   }
> ```
> 
> 大概这样，不需要isshow，数据源和被选择的数据分开存放，用computed去动态获取哪些要显示

是我看文档看漏了，文档里面有一个 row-class-name 属性，可以做到我想要的功能。
