### ISSUE TITLE
[Bug Report] menu or text inside Nav Menu Vertical not break into new line if character length more than wrapper width

### ISSUE THREAD

**Issue by michaelchandrag** [ElemeFE/element#16148]
### Element UI version
2.9.1

### OS/Browsers version
Google Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/michaelchandrag/pen/MMbxVd?&editable=true

### Steps to reproduce
Hi,
I create a Nav Menu Vertically using Element UI following this link https://element.eleme.io/#/en-US/component/menu.
However, when i have like a long-text menu, it didnt automatically break into new line or break-word

### What is Expected?
If there are more character on the menu, then it should be break into new line or auto width based on the wrapper content

### What is actually happening?
The word isnt break to a new line, but continously write as inline text

**Comment by ziyoung** [comment]
You can set CSS. Long text is not recommended.
