### ISSUE TITLE
[Bug Report] When the dialog box nests the table, the scroll bar obscures the content on the right side of the table.

### ISSUE THREAD

**Issue by tinggg12345** [ElemeFE/element#16142]
### Element UI version
0.1.0

### OS/Browsers version
win10/Chrome75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/agBaeG?&editable=true

### Steps to reproduce
第一次显示对话框--表格的滚动条有独立的列
隐藏对话框
再次显示对话框--表格的滚动条没有独立的列，表格右侧的文字被遮挡

### What is Expected?
每次显示对话框时表格的滚动条都有独立列而不会挡住表格右侧的内容。

### What is actually happening?
再次显示的对话框里表格的滚动条没有独立的列，表格右侧的文字被遮挡。

**Comment by tinggg12345** [comment]
在dialog上绑定`v-if`来强行重新加载dialog可以解决，但可能会降低dialog的显示速度。

**Comment by ziyoung** [comment]
新款的 Mac 出现这个 bug😅有点奇怪

**Comment by ziyoung** [comment]
![Kapture 2019-07-04 at 15 41 47](https://user-images.githubusercontent.com/12947422/60648328-50c41980-9e72-11e9-9215-e1f9795ed86c.gif)
无法重现。请再确认一下。issue 先关了。
