### ISSUE TITLE
[Bug Report] Table scroll bug when setting height="auto" in flex layout

### ISSUE THREAD

**Issue by shady-xia** [ElemeFE/element#16145]
### Element UI version
2.9.1

### OS/Browsers version
windows

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
我在页面中，用了类似于query form、table这样的布局，
通过使用flex，并在el-table中设置height="auto"，来让页面的滚动条出现在table内部
在2.8.2版本是正常的，但是升级了2.9.1后，73版本chrome滚动条就跑到外面去了，73以下版本chrome没有滚动条了
我看了下渲染的html，没出现 .el-table--scrollable-y，并且 .el-table__body-wrappe r也没有动态的添加height

### What is Expected?
滚动条限制在table内部

### What is actually happening?
滚动条在table外部（chrome73）
没有滚动条（chrome69）

**Comment by shady-xia** [comment]
我看了下源码，问题貌似出在parseHeight()这个方法，
![image](https://user-images.githubusercontent.com/20945955/59818432-7de2d900-9356-11e9-9a22-f0ac65a97610.png)
我height: auto传进来，只能return null，导致setHeight()中的height变成null了

**Comment by ziyoung** [comment]
#15858
