### ISSUE TITLE
[Feature Request] Ability to hide submenu on click away when menu-trigger is "click"

### ISSUE THREAD

**Issue by japhfortin** [ElemeFE/element#16147]
### Existing Component
Yes

### Component Name
NavMenu

### Description
Whenever we set menu-trigger to "click", I think it would be good if we can have an option to hide the submenu on click away. Rather than forcing the user to click the same menu item just to hide the submenu.

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by japhfortin** [comment]
would this suffice? - https://github.com/ElemeFE/element/issues/16491
