### ISSUE TITLE
[Table]如何显示筛选数据？

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1614]
如何将table中的数据筛选出选中的数据呢？

**Comment by Leopoldthecoder** [comment]
没太看懂，能否详细描述？

**Comment by Delicate-lee** [comment]
table 筛选 ，filter-method无法触发，是依赖包版本问题吗？

**Comment by furybean** [comment]
@yuanshengchao 修改 Table 绑定的 data 属性即可。

**Comment by Delicate-lee** [comment]
![element-1](https://cloud.githubusercontent.com/assets/18555584/21037204/edb116d4-be06-11e6-9b80-69d49c0dadba.jpg)
这是例子中样式，点击筛选可以触发filter-method；

![element-2](https://cloud.githubusercontent.com/assets/18555584/21037232/1a87d242-be07-11e6-81f5-ca127abd06da.jpg)
代码应该没错，样式不同，也没法触发filter-method；
我的部分package.json如下：
"element-ui": "^1.0.2",
"vue-loader": "^9.9.5",
"vue": "^2.0.6",
"webpack": "^1.13.3",
有需要限定的版本号吗，谢谢！
@Leopoldthecoder @furybean

**Comment by furybean** [comment]
@Delicate-lee 如果可以使用 jsfiddle 里面重新，请使用该例子重开一个 issue。

**Comment by yuanshengchao** [comment]
如何实现input输入框来对table数据进行筛选呢

**Comment by hunter007** [comment]
追加一个：filter-method不能执行。

"element-ui": "^1.0.7",
"vue": "^2.1.0",
最新chrome

**Comment by hunter007** [comment]
原因找到了！ el-table-column的prop不能少。但这一点文档中没有提及。建议修改文档。

**Comment by tinytonny** [comment]
请问能否hover表头时就能触发显示下拉列表？
