### ISSUE TITLE
[Feature Request] el-table e-tree 10000 rows render slowly

### ISSUE THREAD

**Issue by xiaogaofudao** [ElemeFE/element#16151]
### Existing Component
是

### Component Name
el-table el-tree

### Description
El-table el-tree 10000  rows rendering slowly. I hope you can refer to this react framework to implement large data virtual tables
https://rsuitejs.com/components/table#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%9A%84%E5%A4%A7%E8%A1%A8%E6%A0%BC

**Comment by xiaogaofudao** [comment]
el-select also have the same problem

**Comment by xiaogaofudao** [comment]
感觉这三个组件可以继承一个抽象的基类。实现 虚拟List 只显示加载 用户看到的 dom。

**Comment by ziyoung** [comment]
有类似 issue 了。

**Comment by sundongzi** [comment]
@ziyoung 有什么比较好的解决方案么

**Comment by yinyihui** [comment]
请问一下有没有解决呢，真心慢啊，居然比不上之前用angularjs写得

**Comment by xiaogaofudao** [comment]
和 node-key 没有太大关系。如果不开启懒加载。数据量太多的时候，一次性渲染必然卡顿。只有加入虚拟列表只渲染用户视窗内的 dom 节点可以解决

**Comment by yinyihui** [comment]
> 
> 
> 和 node-key 没有太大关系。如果不开启懒加载。数据量太多的时候，一次性渲染必然卡顿。只有加入虚拟列表只渲染用户视窗内的 dom 节点可以解决

一般情况下如果你的数据量大到一定程度肯定懒加载是最优解，这个阀值我觉得让ui团队提供一下，我个人大概是在1000条不到的数据上面测试这个属性带来了性能提升，当然如果使用虚拟列表那应该会快很多，但是还是建议一次性数据量不要太大。之前antd那边的tree-seletor也有类似的问题，后来也是加入了虚拟化实现性能提升

**Comment by Specialxm** [comment]
https://github.com/foolishchow/element-tree-grid 这个插件可以试试

**Comment by sundongzi** [comment]
@yinyihui 我现在的优化方式是把它做成单例的，每次点击的时候创建。。。

**Comment by yinyihui** [comment]
> 
> 
> @yinyihui 我现在的优化方式是把它做成单例的，每次点击的时候创建。。。

能分享一下吗？

**Comment by shenwzl** [comment]
这个问题，现在又什么好的解决方案吗？
