### ISSUE TITLE
[Feature Request] Can the el-input-number component add a conversion relationship between the binding value and the display value?

### ISSUE THREAD

**Issue by lshz0088** [ElemeFE/element#16152]
### Existing Component
是

### Component Name
el-input-number

### Description
el-input-number 组件，是否可以新增绑定值和显示值的换算关系。

例如：我界面上要显示百分数（10），实际绑定的值是0.1

Can the el-input-number component add a conversion relationship between the binding value and the display value?

For example, I want to display a percentage (10) on my interface, and the actual binding value is 0.1.

**Comment by YangYmimi** [comment]
Such as `https://github.com/vueComponent/ant-design-vue/blob/master/components/input-number/demo/formatter.md`

**Comment by lshz0088** [comment]
嗯 就是差不多这效果，element-ui中是否可以增加该功能
Well, that's about the effect. Is it possible to add this functionality to element-ui?

like this:
https://vue.ant.design/components/input-number/

**Comment by ziyoung** [comment]
现在的 ElInput 与原生 input 差别较大了。再大版本再调整。
