### ISSUE TITLE
可搜索select，如果想修改选项很不方便，需要先删除已经选择的内容

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1616]
看官方的demo，假设已经选择了一个选项，现在要修改选项，点击select，发现没有其他选项，需要先删除当前的内容。这样的使用体验很不好，会让人误任务无法修改选项，建议学下select2，过滤的input单独用一个，不要和select的用一个。
http://jsfiddle.net/api/post/library/pure/

![2016-12-08 9 31 54](https://cloud.githubusercontent.com/assets/13174059/20994079/2f0f0160-bd29-11e6-92e8-5f0a08d842b8.png)

看到一个pr，其实是解决这个问题的。
https://github.com/ElemeFE/element/pull/1302

**Comment by Leopoldthecoder** [comment]
目前的交互设计就是这样，近期应该不会修改。

**Comment by njleonzhang** [comment]
@Leopoldthecoder 这个没法用啊。。。。。。。。
