### ISSUE TITLE
[Bug Report] el-table if height is string type invalid in the new version

### ISSUE THREAD

**Issue by happy0402** [ElemeFE/element#16162]
### Element UI version
2.9.1

### OS/Browsers version
Chrome 版本 73.0.3683.86（正式版本）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/agpQjb

### Steps to reproduce
没有步骤，你就看高度的样式就是错的

### What is Expected?
style="height: 100%"

### What is actually happening?
style="height: 100px"

**Comment by ziyoung** [comment]
#15858
