### ISSUE TITLE
[Bug Report] element UI use es7 api : Array.includes but didn't transpile

### ISSUE THREAD

**Issue by mkanako** [ElemeFE/element#16161]
### Element UI version
2.9.1

### OS/Browsers version
windows7 ie11

### Vue version
2.6.10

### Reproduction Link
https://github.com/mkanako/vue-cli-test

### Steps to reproduce
eg:the el-tag component use Array.includes internally

1.npm run serve

2.open in ie11

3.it will occur error

### What is Expected?
work fine in

`Modern browsers and Internet Explorer 10+ `

and don't need user import Polyfill

### What is actually happening?
occur error in ie

**Comment by mkanako** [comment]
@ziyoung 不止是tag组件，我全局搜索了，还有其他3，4处地方也是用了Array.includes

**Comment by hzsrc** [comment]
avatar也是

**Comment by hzsrc** [comment]
在代码入口中加一句可解决：
````
[].includes(0);  //引入includes避免elemnt-ui部分组件IE报错
````
