### ISSUE TITLE
[Bug Report] When MessageBox is displayed, pressing enter will frequently pop up serious BUG!!!

### ISSUE THREAD

**Issue by 542154968** [ElemeFE/element#16163]
### Element UI version
2.9.1

### OS/Browsers version
火狐67.0.3 (64 位) 谷歌 版本 71.0.3578.98（正式版本） （64 位）

### Vue version
2.6.6

### Reproduction Link
https://codepen.io/anon/pen/dBNQEN?&editable=true

### Steps to reproduce
点击打开Mesage Box
待Message Box打开之后
按着键盘Enter键不松开
会频繁弹出
所有的Message Box都有这个问题

### What is Expected?
按着之后关闭Message Box

### What is actually happening?
会频繁弹出 
甚至遮罩层会把网页遮黑

**Comment by qingdengyue** [comment]
这个是标准行为，Enter会触发Button的Click事件，所以MessageBox就会重复打开，然后因为Enter事件，也会触发MessageBox的确认关闭MessageBox的操作，所以你如果一直按住Enter就会循环上面的过程。现象就是MessageBox一直打开，然后关闭，然后循环。

**Comment by yyjjqq94** [comment]
这个说不上组件bug，自己处理下，阻止默认事件

**Comment by 542154968** [comment]
点击button的时候 button是focus状态的 
而弹窗打开的时候 button是失焦的
弹窗关闭后 button又变为focus状态了
而focus状态下的dom按着enter的时候会触发click
所以就这样了
因为focus的时候没有样式变化  忽视了这点 哈哈
