### ISSUE TITLE
[Bug Report] Error in directive infinite-scroll inserted hook: "TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'."

### ISSUE THREAD

**Issue by langzicx** [ElemeFE/element#16165]
### Element UI version
2.9.1

### OS/Browsers version
Mac  Google

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io

### Steps to reproduce
Error in directive infinite-scroll inserted hook: "TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'."

found in

### What is Expected?
？？？

### What is actually happening?
？？

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
