### ISSUE TITLE
[Bug Report] V2.1.9 Added InfiniteScroll Components Packed CSS and JS File Naming Errors

### ISSUE THREAD

**Issue by liangwei** [ElemeFE/element#16166]
### Element UI version
2.9.1

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
Error reporting after importing InfiniteScroll components

### What is Expected?
- Naming of Separated Substitute Humps

### What is actually happening?
Naming Hump

**Comment by iamkun** [comment]
fixed in current release
