### ISSUE TITLE
Differences between [Bug Report] table event 2.8.2 and 2.9.1

### ISSUE THREAD

**Issue by danchaotaiyang** [ElemeFE/element#16179]
### Element UI version
2.9.1

### OS/Browsers version
Chrome 版本 74.0.3729.169（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
table定义select与select-all事件方法
触发select-all
2.8.2 不会触发select事件
2.9.1 会触发select事件，与select-change效果一样

### What is Expected?
触发select-all事件不触发select事件

### What is actually happening?
触发select-all事件会触发手动事件select

**Comment by ziyoung** [comment]
#15983
