### ISSUE TITLE
[Bug Report] Page Card Dead

### ISSUE THREAD

**Issue by signe5** [ElemeFE/element#16176]
### Element UI version
2.9.0

### OS/Browsers version
74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
我的table页面是嵌套在一个tab里的，我在table添加height或者max-height都会导致当前页面卡死。

### What is Expected?
出现争吵的高度会滚动条

### What is actually happening?
当前页面卡死

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
