### ISSUE TITLE
el-select点击无法收回下拉选项

### ISSUE THREAD

**Issue by lianginet** [ElemeFE/element#1617]
el-select下拉后，再次点击无法收回
![Uploading image.png…]()

**Comment by Kingwl** [comment]
升级到1.04？

**Comment by lianginet** [comment]
@Kingwl 1.0.3 1.0.4 1.0.5 都试过了

**Comment by Leopoldthecoder** [comment]
这是 1.0.3 的 bug，之后的版本已经修复了。如果还有问题，请提供在线 demo。

**Comment by lianginet** [comment]
换到新版本重新编译，已解决。Thank you！
