### ISSUE TITLE
[Bug Report]  El-input cannot enter spaces after using v-model.trim

### ISSUE THREAD

**Issue by jsl6** [ElemeFE/element#16177]
### Element UI version
2.9.1

### OS/Browsers version
Mac chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/zVNgWo

### Steps to reproduce
https://codepen.io/anon/pen/zVNgWo

### What is Expected?
V-model.trim is the same as native input. It can enter spaces and delete the two-headed spaces.

### What is actually happening?
 El-input cannot enter spaces after using v-model.trim

**Comment by rickysang** [comment]
[Input](https://element.eleme.io/#/zh-CN/component/input#input-shu-ru-kuang)
> Input 为受控组件，它总会显示 Vue 绑定值。
> 通常情况下，应当处理 input 事件，并更新组件的绑定值（或使用v-model）。否则，输入框内显示的值将不会改变。
> 不支持 v-model 修饰符。

**Comment by Deeeeeee** [comment]
![image](https://user-images.githubusercontent.com/14084787/83722138-0d1ff400-a66f-11ea-905a-39c89c2886bd.png)
el-input 文档第一条就是 不支持修饰符。（虽然旧的版本 可以这样用，但是新版本.trim 确实会有bug）

建议自己写个全局指令
`
import { DirectiveOptions } from 'vue'

export const trim: DirectiveOptions = {
  inserted(el, binding, vNode) {
    let target = el.getElementsByTagName('input')[0]
    target.onblur = () => {
      vNode.componentInstance.$emit('input', target.value.replace(/^\s+|\s+$/gm, ''))
    }
  }
}
`

用的时候 直接 加上 v-trim 就好了

`
<el-input v-model="" v-trim>
`
