### ISSUE TITLE
[Bug Report] 正常情况下项目中直接安装elementui, el-table里的height参数设为100%可以识别成style="height:100%"，可是如果删除nodemodule后通过package.json重新npm install，就会被识别成style="height:100px"

### ISSUE THREAD

**Issue by zhulu123** [ElemeFE/element#16173]
### Element UI version
2.4.6

### OS/Browsers version
任意版本

### Vue version
2.5.1

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
重现链接为本地ip或后台管理系统链接，无法提供，可根据以下步骤进行重现

1.启动一个vue项目

2.npm i element-ui@2.4.6 -S(此时package.json中有"element-ui": "^2.4.6"),现在在项目中引用el-tabel给它一个height="100%"的属性，他会自动继承父元素高度，浏览器中观察tabel标签，显示table style="height:100%"

3.（出现问题的一步）把node_module文件删掉，重新npm install,打开项目，此时浏览器中的tabel的style就变成了 style="height:100px"。识别height="100%"失效。

（如果第一次使用elementui的时候采用npm i element-ui@2.4.4的方式，不把它写入package.json,删除node_module后重新npm i element-ui@2.4.4就没有问题。）

认为错误的原因是：通过package.json安装elementui会出错（6月前使用还没有问题，最近突然我所有项目重新npm install时均出现这个错误）

### What is Expected?
删除node_module后通过package.json重新npm install elementui能够正常使用（el-tabel的height参数为100%可以识别成style="height:100%"）

### What is actually happening?
重新安装nodemodule后会被识别成style="height:100px"

**Comment by flykarry** [comment]
兄弟，我也是这个问题，怎么解决的？
