### ISSUE TITLE
[Bug Report] Mask Overlay Diaog

### ISSUE THREAD

**Issue by Jarvis2018** [ElemeFE/element#16189]
### Element UI version
2.9.2

### OS/Browsers version
windows/chrome 74

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/oLspz2q0/3/

### Steps to reproduce
将`el-dialog`放在一个“position: fixed”的元素内后，就会复现该情况

### What is Expected?
遮罩层应该在dialog下边

### What is actually happening?
遮罩层在dialog上边

**Comment by ziyoung** [comment]
不是 element 的 bug。

**Comment by ziyoung** [comment]
不要使用 fix 定位。
