### ISSUE TITLE
选中select的一项，然后清空select的options，select里显示之前选中的那一项的value

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1618]
版本1.0.5

![2016-12-08 10 24 32](https://cloud.githubusercontent.com/assets/13174059/20995224/95391654-bd30-11e6-81dd-25ed1b3fbb8b.png)

![2016-12-08 10 24 43](https://cloud.githubusercontent.com/assets/13174059/20995233/9b6ecab4-bd30-11e6-8694-277f7939363b.png)

**Comment by Kingwl** [comment]
新版的没有这个问题

**Comment by njleonzhang** [comment]
@Kingwl  我用的是1.0.5哦

**Comment by Leopoldthecoder** [comment]
对的，是有这个问题。下个版本修复。

**Comment by Aprilday** [comment]
select貌似还有个问题，就是change方法没法触发。http://jsfiddle.net/m66koabc/

**Comment by Leopoldthecoder** [comment]
@Aprilday `:change="changeVal"` 应该改为 `@change="changeVal"`

**Comment by Leopoldthecoder** [comment]
Fixed in #1630
