### ISSUE TITLE
[Bug Report] table component height & max-height set to 100% resolve to 100px problem

### ISSUE THREAD

**Issue by frinder6** [ElemeFE/element#16187]
### Element UI version
2.9.2

### OS/Browsers version
windows/chrome版本 74.0.3729.131（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/frinder6/pen/JQWeaP?&editable=true

### Steps to reproduce
设置table的height="100%"& max-heiht="100%"
之前项目中这样设置是可以的，版本："element-ui": "^2.4.3"

### What is Expected?
正常解析height="100%"& max-heiht="100%"

### What is actually happening?
解析为：height: 100px; max-height: 100px;

**Comment by zyouzz** [comment]
I had reported same BUG,you will see [https://github.com/ElemeFE/element/issues/16064](url)

**Comment by FeatureSpitter** [comment]
> 
> 
> I had reported same BUG,you will see [https://github.com/ElemeFE/element/issues/16064](url)

That link is broken.

Here's the correct link: [https://github.com/ElemeFE/element/issues/16064](https://github.com/ElemeFE/element/issues/16064)

**Comment by ziyoung** [comment]
fixed in 2.10.0

**Comment by ray007** [comment]
Setting `height` to `100%` seems to work, but setting `max-height` to `100%` is buggy in a container with padding like `<el-main>`.
The `div.el-table__body-wrapper` has a too high `max-height` value in that case.
