### ISSUE TITLE
[Bug Report] [Bug Report] tree component uses slot-scope and drop problem

### ISSUE THREAD

**Issue by chenhuiYj** [ElemeFE/element#16188]
### Element UI version
2.4.11

### OS/Browsers version
macOS 10.14.4   chrome 最新版

### Vue version
2.5.22

### Reproduction Link
https://codepen.io/anon/pen/vqxbjP?&editable=true

### Steps to reproduce
1.tree 组件的拖拽，tree-item 使用自定义节点内容的时候（ slot-scope）
2.把被拖拽的tree-item 放进 tree-item 的时候，被放进的tree-item样式没有改变

### What is Expected?
tree-item 使用自定义节点内容的时候（ slot-scope）。拖拽的tree-item 放进 tree-item 的时候，被放进的tree-item文字的样式改变

### What is actually happening?
被放进的tree-item文字的样式没有改变

**Comment by ziyoung** [comment]
无法重现。

**Comment by chenhuiYj** [comment]
<img width="960" alt="WX20190703-165403@2x" src="https://user-images.githubusercontent.com/27403818/60578253-7807e180-9db3-11e9-9224-2081b88ce6aa.png">
<img width="964" alt="WX20190703-165504@2x" src="https://user-images.githubusercontent.com/27403818/60578289-8229e000-9db3-11e9-9c08-e47e5f44e24b.png">

这样的情况

**Comment by akingwangx** [comment]
请问这个问题解决了吗

**Comment by akingwangx** [comment]
> <img alt="WX20190703-165403 @ 2x" width="960" src="https://user-images.githubusercontent.com/27403818/60578253-7807e180-9db3-11e9-9224-2081b88ce6aa.png">
> 
> <img alt="WX20190703-165504 @ 2x" width="964" src="https://user-images.githubusercontent.com/27403818/60578289-8229e000-9db3-11e9-9c08-e47e5f44e24b.png">
> 
> 这样的情况

请问这个问题有你解决了吗。。

**Comment by moyuderen** [comment]
> > <img alt="WX20190703-165403 @ 2x" width="960" src="https://user-images.githubusercontent.com/27403818/60578253-7807e180-9db3-11e9-9224-2081b88ce6aa.png">
> > <img alt="WX20190703-165504 @ 2x" width="964" src="https://user-images.githubusercontent.com/27403818/60578289-8229e000-9db3-11e9-9c08-e47e5f44e24b.png">
> > 这样的情况
> 
> 请问这个问题有你解决了吗。。

遇到了一样的问题，自定义节点，这个样式失效
