### ISSUE TITLE
[Bug Report] Time'el-date-picker'uses': value' to set values, which will result in the selected time can not be rendered, means that is can `t show my choice of new value'.

### ISSUE THREAD

**Issue by peakDragonCheung** [ElemeFE/element#16182]
### Element UI version
2.9.1

### OS/Browsers version
window 10 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/peakdragoncheung/pen/jjBPjL

### Steps to reproduce
1.  not use  v-model -不使用 v-model
2.  use  :value to pass value - 使用 :value 去传值
3. choice your time or date - 再选中时间或者日期
4. unshow my choice value or date - 不显示我选中的值。

### What is Expected?
when i use ': value' to pass value , and i choice time or date ,  after  the  el-date-picker not show my choice value.
使用：value 我选中的日期或者时间，应该被及时的渲染到页面中，

### What is actually happening?
it show blank ，it is null 
时间控件展示空白，没有值。

**Comment by ziyoung** [comment]
不支持这样的用法。

**Comment by peakDragonCheung** [comment]
今天刚刚更新，之前文档明明就写着支持，通过  v-model/value 传值值，
