### ISSUE TITLE
[Bug Report] navMenu Collapse  bug

### ISSUE THREAD

**Issue by neilwong2012** [ElemeFE/element#16199]
### Element UI version
2.9.2

### OS/Browsers version
any

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/bs1gnu7e/2/

### Steps to reproduce
if submenu is too height more than the browser , the submenu's top is a negative number and can't see all the submenu item.

### What is Expected?
when submenu is heighter than brower. the submenu's top and bottom should be 0px and scrollY's value is scroll.

### What is actually happening?
the submenu's top is a negative number and can't see all the submenu item.

**Comment by ziyoung** [comment]
https://jsfiddle.net/d3hrqzms/
