### ISSUE TITLE
[Bug Report] el-tag 在ie11 下提示 对象不支持“includes”属性或方法

### ISSUE THREAD

**Issue by zhanghongke123** [ElemeFE/element#16191]
### Element UI version
2.9.2

### OS/Browsers version
ie11

### Vue version
2.6.10

### Reproduction Link
https://github.com/zhanghongke123/yypt-vue

### Steps to reproduce
使用el-tag 时在ie11中打开提示对象不支持“includes”属性或方法 ，看了一下源码
['dark', 'light', 'plain'].includes('dark')   这个地方提示的，百度上说是arry在ie11 中不支持includes ,建议换成indexOf

### What is Expected?
能够换成ie支持的语法

### What is actually happening?
1

**Comment by ivila** [comment]
indexOf 和 includes是不太一样的，这种问题建议你使用polyfill
可以参考： https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
