### ISSUE TITLE
select 组件，设置了 clearable，当 disabled 为 true 时，依然可以清除内容

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#1619]
emement-ui `1.0.5` 版本

设置了可清除，当 disabled 为 true 时，依然可以清除。既然 disabled 了，不应该允许可操作才对。

![clearable](https://cloud.githubusercontent.com/assets/2276421/20995654/7014b43e-bd33-11e6-8026-b7f6bd1d3e54.png)

可如下修改修正这个问题：

![clearable-code](https://cloud.githubusercontent.com/assets/2276421/20995655/7018aa08-bd33-11e6-8b62-52aff4d782d8.png)

**另外还有几个远程搜索的问题可以讨论优化的地方：**

- 无输入时的请求（如希望获取焦点就能显示一个初始列表）
- 鼠标失去焦点隐藏了输入框，不应该触发请求
- 前后相同关键字，甚至只是获取焦点，也都会触发多次的远程请求，这种请求应该可以避免

对比 select2、chosen 这些成熟的组件，select 组件需要优化的点还是挺多的，加油！

**Comment by Leopoldthecoder** [comment]
感谢建议。`disabled` 的问题下个版本会修复。

关于远程搜索的几个问题：
> 无输入时的请求（如希望获取焦点就能显示一个初始列表）

这个目前在获取焦点时是可以显示初始列表的，只要 `el-option` 不为空。或者你是希望在获取焦点时直接调用一次 `remote-method`？
后面的两个建议之后会考虑。
