### ISSUE TITLE
[Feature Request] Layout container pullable

### ISSUE THREAD

**Issue by huangjiaxiang** [ElemeFE/element#16197]
### Existing Component
是

### Component Name
el-container

### Description
在<el-aside>与<el-main>之间是否能增加宽度拖动的功能

**Comment by huangjiaxiang** [comment]
Can Width Drag be Increased Between <el-aside>and <el-main>?

**Comment by huangjiaxiang** [comment]
Can Width Drag be Increased Between aside and  main?

**Comment by iamkun** [comment]
pr welcomed
