### ISSUE TITLE
theme-default 使用 PostCSS 编写，请问也能支持 scss或者less 版本的吗？毕竟这类实际中较常用

### ISSUE THREAD

**Issue by fuyuanwu** [ElemeFE/element#162]
### ElementUI version
1.0.0-rc.4

**Comment by QingWei-Li** [comment]
打包出来的是 CSS，所以用任何预处理器都没关系的

**Comment by fuyuanwu** [comment]
嗯，兄台说的没错。
可是当需要自定义（或者些微修改一下）控件样式的时候，就只能去编写覆盖样式了。
如果能提供scss或者less版本的话，那就太好了，这样大家可以很方便打包融合到各自项目中去。

**Comment by QingWei-Li** [comment]
嗯，确实是这样。不过我们应该不会考虑去做，毕竟主题是独立出去的，所以开发者可以自己改造一套 scss、less 或者任意版本。

**Comment by dnshi** [comment]
目前我的做法就是覆盖样式。其实很多时候，哪怕用bootstrap，相比直接修改scss或者less文件，直接覆盖样式是最为理想的，否则后期库升级的时候，可能会冲突。

**Comment by reverland** [comment]
我是直接clone一份element，在theme-default的基础上扩展，然后build出来。

感觉，theme-default项目好像是要单独拆出来？

**Comment by 598220654** [comment]
我想问问自定义主题怎么安装,为什么我跟着文档node_modules/.bin/et -i  ,去到这里,他说:'node_modules' 不是内部或外部命令，也不是可运行的程序或批处理文件。我应该从哪里执行命令
