### ISSUE TITLE
How to initialize initial values for remote search of [Bug Report] select

### ISSUE THREAD

**Issue by wcccode** [ElemeFE/element#16207]
### Element UI version
2.9.2

### OS/Browsers version
chrome 69

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/wLegaa

### Steps to reproduce
给select设置初始值，但没有显示实际的label

### What is Expected?
设置value=apple，显示“苹果”

### What is actually happening?
设置value=apple，显示“apple”

**Comment by Eflet** [comment]
我目前项目里面就是一开始就把初始值的 text和label都放option的list里面

**Comment by ziyoung** [comment]
因为你的 options 一开始是空的。

**Comment by Veitor** [comment]
遇到了同样的问题，毕竟是remote远程方式加载的options列表，用户在select框上选择时，可以通过输入各种字符来请求并返回各种的options列表数据。remote的情况下，options本身就是在需要时才会被查询填充的，而并不是一开始就会有数据。
所以当重新进入页面时，如果要做编辑，由于options是空的，之前选择的value会被当作label显示出来吧。。这确实有些蛋疼。。这种remote加载options还有没有更好的其他初始化方式？

目前我只能先把之前选择的values去查询一遍label来初始化options了。
