### ISSUE TITLE
[Bug Report] el-cascader disable status and close button BUG

### ISSUE THREAD

**Issue by wudiyugi** [ElemeFE/element#16209]
### Element UI version
2.9.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues

### Steps to reproduce
props:{  checkStrictly: true, emitPath: false,multiple: true}
1、页面初始化时，若cascader禁用，那么在页面上动态解除禁用后，并不会出现关闭按钮；
2、页面初始化时，若cascader没有禁用，那么在页面上禁用后，关闭按钮也不会消失；

### What is Expected?
关闭按钮和禁用状态应该同步

### What is actually happening?
关闭按钮和禁用状态应不同步

**Comment by qingdengyue** [comment]
啥关闭按钮？提供下复现repo吧

**Comment by wudiyugi** [comment]
> 啥关闭按钮？提供下复现repo吧

https://codepen.io/wudiyugi/pen/bPRZKw
就是选项标签后面的关闭按钮
