### ISSUE TITLE
Submission method in file upload function in [Bug Report] elementui submits an error -- Cannot set property'status'of undefined

### ISSUE THREAD

**Issue by zhujianxiong** [ElemeFE/element#16205]
### Element UI version
2.9.2

### OS/Browsers version
Google浏览器-版本 72.0.3626.121（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1.通过submit方法提交文件，报Cannot set property 'status' of undefined

### What is Expected?
解决通过submit方法提交文件，报Cannot set property 'status' of undefined

### What is actually happening?
解决通过submit方法提交文件，报Cannot set property 'status' of undefined

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
