### ISSUE TITLE
Can [Feature Request] cascade multiselection restrict parent-level full selection and only achieve child-level multiselection?

### ISSUE THREAD

**Issue by abian1** [ElemeFE/element#16217]
### Existing Component
是

### Component Name
el-cascader

### Description
级联多选能否限制父级全选功能，只实现子级多选？

**Comment by abian1** [comment]
ele-multi-cascader组件实现的有，不过依赖的element版本太低，2.4.11

**Comment by iamkun** [comment]
pr welcomed

**Comment by DwadeWoW** [comment]
我现在就是要这个需求
