### ISSUE TITLE
[Bug Report] The slot is used in el-table-column in tree table. If the code contains V-IF v-show, clicking on the switch tree to expand and close triggers the corresponding function of V-IF v-show.

### ISSUE THREAD

**Issue by liuchihanxiang** [ElemeFE/element#16213]
### Element UI version
2.9.2

### OS/Browsers version
window7/谷歌最新

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/liuchihanxiang/pen/MMoPOa

### Steps to reproduce
f12  切换树形菜单展开收起 控制台可看到输出

### What is Expected?
切换树形展开收起时，只是显示隐藏，不触发其他项

### What is actually happening?
切换时触发了slot内v-if v-show等

**Comment by liuchihanxiang** [comment]
这个bug 数据量小一点还好 稍微大点 页面就会很卡很卡

**Comment by ziyoung** [comment]
就是这样的。数据变化，触发 render 更新。
