### ISSUE TITLE
[table]多选表格在初始化时默认选中所有行，可否实现

### ISSUE THREAD

**Issue by ren8179** [ElemeFE/element#1621]

**Comment by Leopoldthecoder** [comment]
可以：http://jsfiddle.net/7zsp121h/

**Comment by zhanyouwei** [comment]
@Leopoldthecoder 这个真的好坑啊，如果这个Table是 在 `mounted` 之后动态渲染出来的呢？为什么不支持初始化选中呢？

**Comment by xiaosongread** [comment]
多选的表格不能默认选中指定的行吗？急急急。。。

**Comment by kungcn** [comment]
我用debugger以后发现，如果是在mounted才动态渲染表格，那么此时应该是无法默认选中的 。
因为此时的this.$refs.XXTable中，data的长度为0(相关数据已取得但未完成赋值，将在下一个周期完成赋值)，而更新Selection方法中，恰恰是需要判断data的长度是否等于0，所以我估计是无法做到的。

![image](https://user-images.githubusercontent.com/12772780/35552364-8fad079e-05ce-11e8-8661-93b89baa94f5.png)

除非可以在获取data数据并待完成表格数据赋值时才调用toggleSelection方法。

**Comment by caoxianwei** [comment]
在mounted时无法调用toggleSelection方法，求解

**Comment by Tang1118** [comment]
watch table绑定的数据 就可以了

```
 watch: {
      docList(val, oldVal) {
        if (val.length !== oldVal.length && oldVal.length === 0) {
          setTimeout(() => {
            this.$refs.multipleTable.toggleRowSelection(this.docList[0]);
          }, 100);
        }
      }
    },
```

**Comment by scutHuqiang** [comment]
是否可以通过nextTick实现？
`created() {
  fetchData(resp => { 
this.avaliableAddress = resp.data
        console.log('created', this.avaliableAddress)
        this.$nextTick(() => {
          this.avaliableAddress.forEach(row => {
            console.log('next', row)
            if(row.isSelected) {
              this.$refs.table1.toggleRowSelection(row);
            }
          })
        })
}`

**Comment by scutHuqiang** [comment]
是否可以通过nextTick实现？
created() 里面，获取到数据后，在this.$nextTick里执行选中操作.
`getAddrList({
        deptId: this.deptId
      }).then(resp => {
        this.avaliableAddress = resp.data
        console.log('created', this.avaliableAddress)
        this.$nextTick(() => {
          this.avaliableAddress.forEach(row => {
            console.log('next', row)
            if(row.isSelected) {
              this.$refs.table1.toggleRowSelection(row);
            }
          })
        })
      }).catch(err => {

      })`

**Comment by scutHuqiang** [comment]
是否可以通过nextTick实现？
created() 里面，获取到数据后，在this.$nextTick里执行选中操作.

```getAddrList({
        deptId: this.deptId
      }).then(resp => {
        this.avaliableAddress = resp.data
        console.log('created', this.avaliableAddress)
        this.$nextTick(() => {
          this.avaliableAddress.forEach(row => {
            console.log('next', row)
            if(row.isSelected) {
              this.$refs.table1.toggleRowSelection(row);
            }
          })
        })
      }).catch(err => {

      })```

**Comment by cysong** [comment]
this.$nextTick(function(){
     this.$refs.multipleTable.toggleRowSelection(this.docList[0]);
})
经测试可用

**Comment by lfjnanjing** [comment]
this.$nextTick(function(){
this.$refs.multipleTable.toggleRowSelection(this.docList[0]);
})
这个可用，具体啥原因，有人能解释吗？
