### ISSUE TITLE
[Bug Report] Date range selection, after selecting the start time and end time, select again, not the end time, click the blank out of focus, expand the default value problem

### ISSUE THREAD

**Issue by kangxiaoxiao** [ElemeFE/element#16222]
### Element UI version
2.9.2

### OS/Browsers version
win7/谷歌浏览器

### Vue version
2.5.2

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1、选择开始时间和结束时间
2、展开时间选择面板，选择开始时间
3、点击空白处，关闭时间选择面板
4、展开时间选择面板
5、minDate为绑定值的开始时间

### What is Expected?
展开时间选择面板，如果开始时间和结束时间都选择了，日期值为绑定的时间。如果只选择了一个时间，日期的第一个时间为之前选中的时间，第二个时间重新选择

### What is actually happening?
minDate为绑定值的开始时间

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by kangxiaoxiao** [comment]
https://codepen.io/kangxiaoxiao/pen/YoJeyG?&editable=true
