### ISSUE TITLE
Can [Feature Request] el-table Tree Table Increase Tree Icons to Display in Columns

### ISSUE THREAD

**Issue by liuchihanxiang** [ElemeFE/element#16229]
### Existing Component
是

### Component Name
el-table

### Description
树形表格的图标，看源码逻辑是由firstDefaultColumnIndex控制，自动计算出第一个type为default的column的列 ，希望增加一个属性可以手动设置第几列，增加灵活性

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by liuchihanxiang** [comment]
我找到方法设置了  有需求的看这里
[https://codepen.io/liuchihanxiang/pen/NQqKvv?&editable=true](https://codepen.io/liuchihanxiang/pen/NQqKvv?&editable=true)
