### ISSUE TITLE
[Bug Report] el-input in the message box's message content

### ISSUE THREAD

**Issue by happy0402** [ElemeFE/element#16238]
### Element UI version
2.10.0

### OS/Browsers version
版本 73.0.3683.86（正式版本） （32 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/XLaQBG

### Steps to reproduce
input some things in the message box's input controller

### What is Expected?
the things can be input;
the el-input can be used totally in the message box

### What is actually happening?
the el-input can't used

**Comment by luguokong** [comment]
你通过ref处理下el-input的input事件，来达到更新的目的

`

      ......
      open() {
        const h = this.$createElement;
        const self = this;
        ......
               message: h('el-input', {
                     .......
                     ref:'abc',
                     on:{
                             input(e){
                                  self.value=e;
                                  self.$refs.abc.value=e;
                              }
                              ......
                     }
                     ......
               })
      }
`

**Comment by happy0402** [comment]
h('el-input', {
                            props:{
                              value: that.value //需注册data: value
                            },
                            on:{
                                input(value){
                                    that.value = value;
                                }
                            }
                        })

我最后这样处理了，官网上没有input事件，原始的input事件不起作用，所以没试出来，感谢上面的代码

**Comment by happy0402** [comment]
`h('el-input', {
                            props:{
                              value: that.value //需注册data: value
                            },
                            on:{
                                input(value){
                                    that.value = value;
                                }
                            }
                        })`
我最后这样处理了，官网上没有input事件，原始的input事件不起作用，所以没试出来，感谢上面的代码

**Comment by happy0402** [comment]
`h('el-input', {

    props:{
          value: that.value //需注册data: value
    },
    on:{
          input(value){
                  that.value = value;
          }
    }
})`
我最后这样处理了，官网上没有input事件，原始的input事件不起作用，所以没试出来，感谢上面的代码
