### ISSUE TITLE
[Bug Report] Cascader 

### ISSUE THREAD

**Issue by myh110** [ElemeFE/element#16230]
### Element UI version
2.10.0

### OS/Browsers version
macos/chrome75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/small_ma/pen/dBzQMK?&editable=true

### Steps to reproduce
When the value value of the node is the same or of different type in the tree data, and when the value type number and string are inconsistent, the selected item will not be displayed in the input, nor will the selected item be displayed in the echo.

### What is Expected?
Look forward to fixing it soon

### What is actually happening?
Look forward to fixing it soon

**Comment by ziyoung** [comment]
#16420
