### ISSUE TITLE
When more than two columns are fixed to the left of the [Bug Report] table, the data is empty and the horizontal scroll bar cannot scroll.

### ISSUE THREAD

**Issue by dakonglongha** [ElemeFE/element#16231]
### Element UI version
2.10.0

### OS/Browsers version
chrome

### Vue version
2.5.3

### Reproduction Link
https://codepen.io/anon/pen/qzXQQJ

### Steps to reproduce
设定左侧固定列大于2列时并且没有数据，此时横向滚动条无法滚动

### What is Expected?
正常滚动

### What is actually happening?
正常滚动

**Comment by ziyoung** [comment]
已知问题了。issue 列表里搜一下。
