### ISSUE TITLE
[Bug Report] Collapse Folding Panel has a table table table table. When the panel is expanded, the page will jitter.

### ISSUE THREAD

**Issue by ltlwill** [ElemeFE/element#16237]
### Element UI version
2.9.2

### OS/Browsers version
windows 10,Google Chrome 版本 75.0.3770.100（正式版本） （32 位）

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
操作系统：windows 10
浏览器：google chrome 版本 75.0.3770.100（正式版本） （32 位）
在Collapse 折叠面板中有table表格，每当展开面板显示面板中的表格后，页面会出现抖动似乎是在不停的计算宽度或高度，当收缩面板后，抖动情况会消失。

### What is Expected?
Collapse 折叠面板 中有table时，展开面板不会出现页面抖动的问题

### What is actually happening?
无

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
