### ISSUE TITLE
The [Feature Request] cascader component optionally chooses any level of option, and then automatically closes or adds a confirmation button.

### ISSUE THREAD

**Issue by lshz0088** [ElemeFE/element#16242]
### Existing Component
是

### Component Name
cascader 

### Description
cascader 组件 单选选择任意一级选项，选择后可否自动关闭层，或者加一个确认按钮。
否则用户必须点旁边空白处才可以关闭，不是很友好。

**Comment by XGPASS** [comment]
对应的选择项，children没有值，就没有下一级，点击选择了就会关闭

**Comment by ziyoung** [comment]
pr welcome

**Comment by xiaoxinlin** [comment]
> 了

选择任意级的时候，并不能保证选中的选项没有children，这时候能否自动关闭弹出层
