### ISSUE TITLE
In the [Bug Report] Form component, the select component changes a value of the form through a change event, causing the input box to be unable to re-enter

### ISSUE THREAD

**Issue by Zypom** [ElemeFE/element#16249]
### Element UI version
2.8.2

### OS/Browsers version
macOS High Sierra10.13,4 / Google Chrome 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zypom/pen/WqZPKY

### Steps to reproduce
在demo里首先选择我方商品，然后在选择属性，此时会将”价格“和”品牌“字段填充，然后继续输入”品牌“字段，出现无法输入的情况，其他字段正常

### What is Expected?
可以继续输入”品牌“字段

### What is actually happening?
无法输入”品牌“字段

**Comment by island205** [comment]
Please submit a clean demo.
