### ISSUE TITLE
[Bug Report] When Table drags and changes column width, the drag and drop style of mouse is lost after clicking and returns to normal cursor.

### ISSUE THREAD

**Issue by xiaoksks** [ElemeFE/element#16243]
### Element UI version
2.10.0

### OS/Browsers version
win10/chrome70

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/GbMgXN

### Steps to reproduce
创建一个表格，设置border为true,可以拖动改变列宽，在表头处左右拖动改变列宽时产生bug

### What is Expected?
拖动改变列宽时，光标维持拖动样式

### What is actually happening?
拖动改变列宽时，光标拖动样式消失，向左拖动时偶尔消失，向右拖动时一定消失

**Comment by ziyoung** [comment]
无法重现。

**Comment by xiaoksks** [comment]
> 无法重现。

![123](https://user-images.githubusercontent.com/22879947/60174444-9a45b080-9843-11e9-830d-4003713546e4.gif)

**Comment by ziyoung** [comment]
在其他的浏览器试了一下，也无法复现。

**Comment by zhangjiancheng** [comment]
2022/4/22　现象依旧存在
重现-参照官网例子
参考URL：[改变列宽时光标样式不正确](https://element.eleme.io/#/zh-CN/component/table#dai-bian-kuang-biao-ge)
