### ISSUE TITLE
使用select  remote  远程搜索时 我选择了一个label input的内容不会自动请空

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#1624]
具体的效果如官网demo
![image](https://cloud.githubusercontent.com/assets/8121621/20998737/f5a9b754-bd4a-11e6-9714-9af3c5ff023f.png)

选择完label 之前input输入的内容不会自动清空

**Comment by Leopoldthecoder** [comment]
就是这样设计的，因为同一个搜索条件，可能需要选择多个选项。
