### ISSUE TITLE
[Bug Report] option style issues

### ISSUE THREAD

**Issue by luocong2016** [ElemeFE/element#16255]
### Element UI version
2.10.0

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/blob/v2.10.0/packages/theme-chalk/src/option.scss

### Steps to reproduce
应用场景：更改 select 中 options 选中的样式
原因：样式覆盖问题，两个样式的优先关系错乱。
方案：只要更改位置就能正确显示

### What is Expected?
期望
&.selected {
      color: $--select-option-selected-font-color;
      font-weight: bold;
}

&.hover, &:hover {
      background-color: $--select-option-hover-background;
}

### What is actually happening?
目前
&.hover, &:hover {
      background-color: $--select-option-hover-background;
}

&.selected {
      color: $--select-option-selected-font-color;
      font-weight: bold;
}

**Comment by luocong2016** [comment]
项目需要更改 select > option 中的 color 就很直观了

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
