### ISSUE TITLE
[Bug Report] input type="number" 使用中文输入法时文本框换行（光标位置偏上）

### ISSUE THREAD

**Issue by GODSEULGI** [ElemeFE/element#16250]
### Element UI version
2.10.0

### OS/Browsers version
macOS Mojave/Chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/s5cpwr0d/

### Steps to reproduce
使用中文输入法输入后space或者enter

### What is Expected?
文本框不会换行（光标位置正确）

### What is actually happening?
文本框换行（光标位置在上）

应该是行高样式问题导致的，目前这样解决了：

.el-input__inner[type="number"] {

  line-height: inherit;

}

**Comment by island205** [comment]
We will fix this issue in next major candidate.

**Comment by varyzheng** [comment]
@GODSEULGI I tried your solution, but it's not worked for me. I fixed it by this way:
`
document.querySelector('#app').addEventListener('input', (e) => {
      const target = e.target
      if (target.className.indexOf('el-input__inner') > -1 && target.type === 'number' && e.data === '' && target.value === '') {
        target.value = 0
        target.value = ''
      }
    })
`

**Comment by CBCzed** [comment]
目前使用了line-height: 1解决了这个问题
