### ISSUE TITLE
[Bug Report] el upload type error

### ISSUE THREAD

**Issue by zhongqc** [ElemeFE/element#16252]
### Element UI version
2.10.0

### OS/Browsers version
mac os 10.14.5/chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhongqc/pen/MMERKv

### Steps to reproduce
1. choose upload image file
2. see the console the file.raw value is undefined

### What is Expected?
the file.raw is ElUploadInternalRawFile object or change the type declare file

### What is actually happening?
the file.raw === undefined

**Comment by luckyCao** [comment]
fixed #16633
