### ISSUE TITLE
[Feature Request] Cascader recommends that when checkStrictly is set to true, it supports not displaying radio boxes and choosing first and second titles by clicking on text.

### ISSUE THREAD

**Issue by ashen9** [ElemeFE/element#16257]
### Existing Component
是

### Component Name
Cascader

### Description
Cascader在checkStrictly设置为true时，建议支持不显示单选框方式，通过点击文字来选择一级和二级标题，通过hover来展开下一级。

**Comment by island205** [comment]
Sorry, we have no plan to support this.
