### ISSUE TITLE
[Bug Report] Dialog auto closed when the left mouse button pressed and release it out of dialog's body

### ISSUE THREAD

**Issue by LeenSamZiv** [ElemeFE/element#16265]
### Element UI version
0.1.0

### OS/Browsers version
Windows 10 / Chromium 77.0.189.3

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator

### Steps to reproduce
Ⅰ Press the left mouse button
Ⅱ Drag mouse out of dialog's body
Ⅲ Release the left mouse button
![](https://files.gitter.im/ElemeFE/element/fubK/q1.gif)

### What is Expected?
dialog not close

### What is actually happening?
dialog closed

**Comment by luckyCao** [comment]
#15000

**Comment by jonathancohen0726** [comment]
I fixed it and proposed a pull request. #16466

**Comment by kongzhexin** [comment]
Please fix it in the next version! thank you! @island205
