### ISSUE TITLE
[Bug Report] When the paging component changes size, when the total number of data is insufficient and page changes are triggered, there will be bugs in combination with common asynchronous code.

### ISSUE THREAD

**Issue by ColinCLL** [ElemeFE/element#16269]
### Element UI version
0.1.0

### OS/Browsers version
win10/谷歌最新版本浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/bPYVZN?&editable=true

### Steps to reproduce
1.打开连接，直接选择修改size,400条/页

2.查看控制台log。

### What is Expected?
模拟了异步请求数据。

应该只请求一次数据。

或者是按照同步的顺序获取数据， 改变size -> 获取数据 -> 改变page ->获取数据

### What is actually happening?
请求了两次数据, 对异步十分不友好。

例子中行为，改变size ->改变page -> 获取page改变的数据 -> 获取size改变的数据
那么最后渲染在网页中的数据并不是正确的数据。

**Comment by ColinCLL** [comment]
目前可以在size-change事件中通过判断 `if(size * (page -1) < total) { getData }` 减少一次请求，绕过这个bug。同样的操作应该可以在组件内部emit这个change事件的时候做。

有空的时候我再看看源码,试试是不是这样能该。

**Comment by island205** [comment]
Sorry, we have no plan to support this.
