### ISSUE TITLE
[Feature Request] wants more components to change

### ISSUE THREAD

**Issue by luocong2016** [ElemeFE/element#16262]
### Existing Component
是

### Component Name
more & more

### Description
radio 组件
1. 希望出现再次点击取消选中值功能，按钮类是实现的

alert 组件
1. 希望后面 x 的关闭按钮可以根据 type 属性来进行颜色调整

dialog 组件
1. 根本不适合项目，一般都会采用 layer 组件可拖拽，可全屏，可放大。
2. 重点是垂直居中不了。
3. 包含关系也不好用，很多情况需要控制某个组件下的弹框。一般多透传样式进去来满足。

InfiniteScroll 组件
1. 可能需要左右滚动事件
2. 触底触顶事件等
3. 滚动条优化

upload 组件
1. 希望添加自定义图片显示列表的作用域插槽
2. 希望添加没有功能的显示，目前默认是 trigger 或 solt 这个很不好用

tree 组件
1. 希望添加 v-modal 快速获取选中值
2. 希望出现单选来实现，z-tree 获取单个选中, 参考: http://www.treejs.cn/v3/demo.php#_204 中 【excheck】Radio勾选操作》radio分组范围

calendar 组件
1. 组件缺少实用性，一般会用于记事标记。 希望实现 FullCalendar 部分功能

需要新增 tree-select 或可自定义的select组件，而不是 option 去创建元素

**Comment by island205** [comment]
请分开提 Feature Request
