### ISSUE TITLE
[Date-picker]日期组件使用上的一点feature

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1626]
## 前言

之前提过一个 #1455 的issues 再type切换的时候只是切换显示值 而不是组件本身的问题。

##  需求

目前我这里使用上是要封装一个datepicker 包括yyyy-MM-dd / yyyy-MM-dd hh:mm:ss / hh:mm:ss 3种格式的需求 
也就是要封装 timepicker /datepicker/ datetimepicker 3种组件的功能 按现状element的粒度 好像没有这个3个组件的整合版 

## 目前做法

1. 通过datetimepicker的type属性进行切换 -》 失败
2. 封装一层通过类型render不同的组件 这种有一定的成本-》 有可行性

## 期望

想问可否计划增加一个复合的 ？或者提供一个属性切换？ 

感谢

**Comment by QingWei-Li** [comment]
为什么不直接 v-if 呢

**Comment by yelingfeng** [comment]
太不优雅了啊

**Comment by yelingfeng** [comment]
算了 我动态组件处理吧

**Comment by briefness** [comment]
v-if 也是不行的，还是有默认行为的

**Comment by rubyisapm** [comment]
v-if实现切换的话 面板能切换的 但是值没有更新 例如从多日切换到多月 显示的还是多日的格式如2018-09-07，但是点开面板已经切换了
