### ISSUE TITLE
[Bug Report] component tabs, set stretch to true, when resize, the location and size of the tabbar is not right

### ISSUE THREAD

**Issue by yj0zhang** [ElemeFE/element#16261]
### Element UI version
2.10.0

### OS/Browsers version
macOS 10.14.5, chrome75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yj0zhang/pen/PrOYpJ?editors=1010

### Steps to reproduce
打开链接，缩放预览窗口大小

### What is Expected?
缩放窗口大小，tabbar位置正确，大小正确

### What is actually happening?
缩放窗口大小，tabbar位置错误，大小错误

**Comment by island205** [comment]
pr welcome
