### ISSUE TITLE
action之后，请求返回失败，然后想继续上传，无法触发submit

### ISSUE THREAD

**Issue by zhangfan19970406** [ElemeFE/element#16288]
上传文件 submit，后端返回成功和失败 ，如果失败，我想保留上传文件然后继续上传，发现无法触发submit

**Comment by pasBone** [comment]
> 上传文件 submit，后端返回成功和失败 ，如果失败，我想保留上传文件然后继续上传，发现无法触发submit

兄弟这个问题解决了吗？
