### ISSUE TITLE
[Bug Report] 非一级子菜单设置popper-append-to-body="true"时,鼠标激活非一级子菜单后移出非一级子菜单范围（未移出一级子菜单范围）会将一级子菜单同时关闭，造成无法继续选择一级子菜单的其它选项。

### ISSUE THREAD

**Issue by 1207934561** [ElemeFE/element#16289]
### Element UI version
2.10.0

### OS/Browsers version
windows7 64位/Chrome 73.0.3683.86 64位

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/1207934561/pen/eweozR

### Steps to reproduce
鼠标移至我的工作台》选项4》鼠标移至选项4的同级其它选项

### What is Expected?
鼠标移至选项4的同级其它选项时应关闭选项4的子菜单，主体一级子菜单依旧显示

### What is actually happening?
在鼠标移至选项4的同级其它选项时主体一级子菜单被一同关闭，造成无法选择其它选项，必须再次激活主体才能显示一级子菜单。

**Comment by island205** [comment]
related: #15391
