### ISSUE TITLE
[Bug Report] Introducing MessageBox error reporting on demand

### ISSUE THREAD

**Issue by EthanLoving** [ElemeFE/element#16299]
### Element UI version
2.10.0

### OS/Browsers version
win7/chrome 73.0.3683.103

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/crystal244236/pen/agEvzd

### Steps to reproduce
基于vue-cli3搭建vue项目并按照element-ui官网按需引入element-ui

### What is Expected?
期待按需引入MessageBox组件

### What is actually happening?
只能引入其中一个。例如：Vue.prototype.$msgbox = MessageBox(正常) ，再引入Vue.prototype.$alert = MessageBox.alert(浏览器报错_MessageBox is not defined)

**Comment by island205** [comment]
Sorry, we have no plan to support this.

**Comment by Yangfan2016** [comment]
Why does is it "MessageBox is not defined"
