### ISSUE TITLE
[Feature Request] el-tree reload data

### ISSUE THREAD

**Issue by broderickwang** [ElemeFE/element#16292]
### Existing Component
是

### Component Name
el-tree

### Description
I have a tree and load data by lazy method,now I have a operation , remove a server data , how can i reload the tree data ?

**Comment by island205** [comment]
https://element.eleme.cn/#/en-US/component/tree#custom-leaf-node-in-lazy-mode resolved?

what is your problem?

**Comment by fengyun2** [comment]
@island205 应该是问后台改变了整个数据，前端有没有办法触发树选择器从第一级开始从新拉取数据吧

**Comment by liuyiliuyi** [comment]
> @island205 应该是问后台改变了整个数据，前端有没有办法触发树选择器从第一级开始从新拉取数据吧

同问。

**Comment by island205** [comment]
重新渲染整个组件不行？

**Comment by fengyun2** [comment]
@island205 官方提供一个这样的接口会比较好咯，当配合radio组件切换条件控制时，需要改变树组件查询条件，每次重新渲染一个很大数据量的树组件会有性能问题。希望官方能够考虑一下。
