### ISSUE TITLE
[Bug Report] The table with fixed columns (including operation buttons) is filtered, and when the operation button is clicked, scope. row contains the data in the row before filtering.

### ISSUE THREAD

**Issue by baooab** [ElemeFE/element#16305]
### Element UI version
2.10.0

### OS/Browsers version
Windows7 / Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhangbao/pen/LKebpK?editors=1010

### Steps to reproduce
1. 进入页面后，点击左上角的按钮，过滤数据
2. 打开控制台，现在分别点击剩下的第一行、第二行的“查看”按钮，在控制台观察打印结果。

发现有不匹配

### What is Expected?
数据过滤后，点击哪一行，控制台就打印哪行的数据记录

### What is actually happening?
打印出来的数据结果有问题。

如果按照我说的步骤来一遍，控制台打印正确、没有错误的话，那么再一次点击左上角按钮，用鼠标分别从第一行点击到第四行，就会发现控制台打印的数据，与点击的当前行的数据是不匹配的

**Comment by luckyCao** [comment]
can't reproduce
