### ISSUE TITLE
[Feature Request] cascade selector

### ISSUE THREAD

**Issue by yuleiQ** [ElemeFE/element#16300]
### Existing Component
Yes

### Component Name
2.10.0

### Description
I hope to have a custom display, not limited to the input box, can be arbitrary such as button, click and pop up menu list.

希望有自定义显示，不局限于input框，可以是任意的如button，点击后弹出menu列表
可参考iview cascader自定义显示https://run.iviewui.com/

**Comment by island205** [comment]
pr welcome
