### ISSUE TITLE
[Bug Report] Broken search in french docs

### ISSUE THREAD

**Issue by j4kim** [ElemeFE/element#16319]
### Element UI version
2.10.0

### OS/Browsers version
Any

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/23wehk4j/

### Steps to reproduce
1. Open french documentation : 
2. Type "Card" (or anything) in the search field
3. Wait forever

### What is Expected?
Find the article needed

### What is actually happening?
Nothing, just a loading wheel.
In the console :
AlgoliaSearchError
Index element-fr does not exist

**Comment by ziyoung** [comment]
We will release 2.10.1 tomorrow. It will be fixed.

**Comment by j4kim** [comment]
Sorry but this is not fixed...
