### ISSUE TITLE
[Feature Request] Is there a place to add global settings to MessageBox?

### ISSUE THREAD

**Issue by hehuangz** [ElemeFE/element#16311]
### Existing Component
是

### Component Name
MessageBox

### Description
hello, I want to set all MessageBox 1500ms display time, and when multiple MessageBox are displayed at the same time, only the last instance is displayed. thanks

**Comment by island205** [comment]
you can use `MessageBox.setDefaults` API.

**Comment by hehuangz** [comment]
sorry, i was write the wrong word
in fact
 I want to set all Message 1500ms display time, and when multiple Message are displayed at the same time, only the last instance is displayed. thanks

Component Name
Message
