### ISSUE TITLE
[Feature Request] dialog provides non-lazy rendering options

### ISSUE THREAD

**Issue by winter-ice** [ElemeFE/element#16313]
### Existing Component
是

### Component Name
el-dialog

### Description
dialog 内容过多时，第一次打开会很慢，大概从触发到打开有一秒多的延时，body中放了很多组件，有一个一定实例化消耗。
不使用懒加载将这个实例化时间放到主页面上，用户感知卡顿会减少。

解决方法：提供一个prop `lazy` 布尔类型，来决定是否使用懒加载

**Comment by island205** [comment]
提供一个 demo，再详细描述一下你的续期。
