### ISSUE TITLE
[Feature Request] el-select does not have an icon and composite input box like el-input

### ISSUE THREAD

**Issue by ztg-zlu** [ElemeFE/element#16314]
### Existing Component
是

### Component Name
el-select

### Description
el-select 没有像 el-input 的带 icon和复合型输入框，可以在el-select前后加图标，加复合型标签的？

**Comment by ztg-zlu** [comment]
我是这样想的，表格上面，做一个搜索，如果el-select也有复合的话，整体的风格是一样的，如果，自己写的话，风格不太，而且复合的字数多少都可以，自己的就要算好宽度了。
![image](https://user-images.githubusercontent.com/26703048/60398738-65609300-9b8e-11e9-955a-a716e5c6246b.png)

**Comment by luckyCao** [comment]
这个自己组合一下吧
