### ISSUE TITLE
[Bug Report] el-date-picker组件的bug。当设置:default-time="['00:00:00', '23:59:59']"并且设置不能选择当前日期以后的时间

### ISSUE THREAD

**Issue by chenyongfei** [ElemeFE/element#16317]
### Element UI version
2.8.2

### OS/Browsers version
OS10.13.6/chrome75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/wLydmd

### Steps to reproduce
html：
              <el-date-picker
                            v-model="filterForm.modifyDatetime"
                            :default-time="['00:00:00', '23:59:59']"
                            type="daterange"
                            :picker-options="pickerOptions"
                            range-separator="至"
                            start-placeholder="开始日期"
                            end-placeholder="结束日期"
                            format="yyyy 年 MM 月 dd 日">
                </el-date-picker>
js： 
           pickerOptions: {
                disabledDate(time) {
                    return time.getTime() >= Date.now();
                }
            }
点击当前的日期   没有反应。不能选择和当前日期相关的时间段。

### What is Expected?
能选择和当前日期相关的时间段。

### What is actually happening?
点击当前的日期   没有反应。不能选择和当前日期相关的时间段。

**Comment by Luummii** [comment]
https://translate.google.com

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
