### ISSUE TITLE
[Feature Request] <el-upload> support user dragging to sort files

### ISSUE THREAD

**Issue by iamlockelightning** [ElemeFE/element#16310]
### Existing Component
是

### Component Name
el-upload

### Description
Is there a way to make pictures in <el-upload> sorted by user dragging (like using vueDraggable)?
There is a similar implementation: https://www.sunzhongwei.com/vue-achieve-upload-photos-and-can-adjust-the-image-sequence . But it shows them in two rows. Actually, I want to drag directly on the pictures (in one row).

**Comment by island205** [comment]
pr welcome

**Comment by cloydlau** [comment]
See https://github.com/cloydlau/faim#faimageupload
