### ISSUE TITLE
[Feature Request] Use elementui for commerce. Is there a copyright issue with fonts?

### ISSUE THREAD

**Issue by gelibin** [ElemeFE/element#16315]
### Existing Component
否

### Component Name
关于版权问题

### Description
element-ui中有使用到微软雅黑字体，这个有关系到字体版权问题，在自己项目中使用el，里面有存在微软雅黑，而项目自己写的文件中没有，这样会不会有字体版权的问题

**Comment by ziyoung** [comment]
自带的字体是图标，从 iconfont 上下载的。不会有版权问题。
