### ISSUE TITLE
[Bug Report] It is recommended to add the official website's effect sample code to the document at the top of the page.

### ISSUE THREAD

**Issue by pruidong** [ElemeFE/element#16312]
### Element UI version
2.10.0

### OS/Browsers version
Windows 7 / Google Chrome canary-dcheck 77.0.3838.1 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pruidong/pen/GbQRwG

### Steps to reproduce
I want to implement a similar return to the top of an official website, but I think it would be convenient for a lot of people to provide a sample code directly in the documentation (https://element.eleme.cn/#/zh-CN/component/backtop). Already implemented: https://codepen.io/pruidong/pen/GbQRwG

### What is Expected?
Add the sample code in the official documentation: https://codepen.io/pruidong/pen/GbQRwG, sorry, I didn't find the github address of element.eleme.cn. I can't submit pr directly to you.

### What is actually happening?
The sample code is missing from the official documentation.

**Comment by island205** [comment]
There is two sample codes in the document https://element.eleme.cn/#/zh-CN/component/backtop
