### ISSUE TITLE
[Bug Report] tooltip“吃掉”循环列表

### ISSUE THREAD

**Issue by huangjunsen** [ElemeFE/element#16318]
### Element UI version
2.8.2

### OS/Browsers version
windows 10 / chrome75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/KjQyoE

### Steps to reproduce
1. 一个数组使用v-for进行遍历，将产生若干个div。
2. 在这些div外层包裹一个el-tooltip，随意设置content和placement。
3. 在结果页面，第一步生成的div将只会出现最后一个。

另外： 目前临时解决办法为遍历的元素外层包裹一个div。
请参考重现链接。

### What is Expected?
el-tooltip中的所有元素，应该按照其默认展示方式展示，无需额外添加包裹部分。

### What is actually happening?
需要额外添加包裹，否则，将只展示最后一个循环的元素。

**Comment by island205** [comment]
Sorry, we have no plan to support this, tooltip must has only one child node.
