### ISSUE TITLE
The load method in [Bug Report] table runs only once?

### ISSUE THREAD

**Issue by zhf0437** [ElemeFE/element#16327]
### Element UI version
2.9.2

### OS/Browsers version
Google Chrome

### Vue version
2.5.20

### Reproduction Link
https://github.com/

### Steps to reproduce
一直

### What is Expected?
可以控制是否需要重新运行load

### What is actually happening?
如果load方法返回的数据是接口请求到的，目前发现点击相同id的load方法只运行一次，再次点击后不会再运行该方法，（也许是我没找到api）如果此时其他人修改了这条数据，那我这边再次展开拿到的数据就不是最新的？

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
