### ISSUE TITLE
[Feature Request] Cascader with default selection, especially when dynamically loaded

### ISSUE THREAD

**Issue by chen-y** [ElemeFE/element#16325]
### Existing Component
是

### Component Name
Cascader

### Description
设置值之后不会默认显示已选则， 特别是在动态加载的时候， 看是否能加一个功能或者设置值自动加载子项，然后显示选择中内容。 不然这个组件在项目中只能作为查询条件， 不能作为信息修改组件来使用。

**Comment by spacecn** [comment]
是啊，动态加载数据下，怎么根据默认值展开对应层级

**Comment by Veyhunk** [comment]
+1
https://github.com/ElemeFE/element/issues/16136
