### ISSUE TITLE
The value of a subset of [Bug Report] cascader is equal to the value of the parent. When the subset is selected, the input box appears empty.

### ISSUE THREAD

**Issue by chengxiaochun** [ElemeFE/element#16324]
### Element UI version
2.10.0

### OS/Browsers version
windows

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/chengxiaochun/pen/qzxJVw

### Steps to reproduce
1、问题：实测2.9.0前版本可以正常选中并显示。 
2、现象前提：options 数据出现某一子集的value等于父级的value，选中该子集时input框显示为空！ 
3、步骤：如链接 https://codepen.io/chengxiaochun/pen/qzxJVw 选中 指南/设计原则/一致性/一致性1 或者选中 指南/导航/侧向导航 时input框显示为空。

### What is Expected?
应该支持父级的value与其中一个子集的value相等，2.9.0前版本是支持的。

### What is actually happening?
父级的value与其中一个子集的value相等时选中后input框显示为空。

**Comment by luckyCao** [comment]
#16393

**Comment by island205** [comment]
fixed in #15935
