### ISSUE TITLE
[Feature Request] The search icon's handle is bit short.

### ISSUE THREAD

**Issue by nh0627** [ElemeFE/element#16321]
### Existing Component
Yes

### Component Name
Icon

### Description
Hi, I have a small request on one of icon components.
We are using the search icon, el-icon-search, but in small size.
So the handle of the icon is not that visible to see that it's a magnifying glass.
Could you get the handle bit longer to recognize it as a magnifying glass?
Thank you!

**Comment by island205** [comment]
Sorry, we have no plan to support this.
