### ISSUE TITLE
[Bug Report] When you open the panel for the first time in the case of `type=dates`, the date is not selected.

### ISSUE THREAD

**Issue by savoygu** [ElemeFE/element#16339]
### Element UI version
2.10.0

### OS/Browsers version
macOS Mojave 10.14.3 / Chrome 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/savoygu/pen/qzoEwK?&editable=true

### Steps to reproduce
Just refresh the page and open the date panel and you will see that `dates` is not selected.

### What is Expected?
Selected

### What is actually happening?
Unselected

### The cause of the problem

[https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/basic/date-table.vue#L194](https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/basic/date-table.vue#L194)

![image](https://user-images.githubusercontent.com/9302866/60432005-ba0a1980-9c33-11e9-8f8a-dcb9c69b9ee0.png)

**Comment by wacky6** [comment]
You should specify `value-format` to use string dates. Or they will be interpreted as UTC-0 timezone.

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
