### ISSUE TITLE
[Feature Request] Could you make multi-sorting for the table component?

### ISSUE THREAD

**Issue by nh0627** [ElemeFE/element#16330]
### Existing Component
Yes

### Component Name
Table

### Description
https://element.eleme.io/#/en-US/component/table#sorting

According to the link, it seems that the sorting only works for one column.
Could you make a multi sorting feature for multiple columns?
For example, sorting a table by date, then name, then address?

Thank you!

**Comment by island205** [comment]
Sorry, we have no plan to support this.
