### ISSUE TITLE
[Feature Request] Could you let us use "event.stopPropagation()" on "el-popover"?

### ISSUE THREAD

**Issue by nh0627** [ElemeFE/element#16335]
### Existing Component
Yes

### Component Name
el-popover

### Description
Hi!

We are using the table-column component with "render-header" attribute to put "pop-over" in a table header.
The thing is, we are also using the sorting feature of table.
When a user clicks a pop-over, it also triggers the sorting feature and both actions (pop-over, sorting) are executed with the "click" event.
Could you let us use "event.stopPropagation()" on "el-popover" by adding an option/attribute or something like that?
If not, is there any way to solve this situation?
We need this feature before we release our product. Please help us😭

Thank you!

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by nh0627** [comment]
@island205 What valid link do you mean?
