### ISSUE TITLE
Can [Bug Report] fix the high consistency of all components, otherwise the page layout may be misaligned due to floating reasons?

### ISSUE THREAD

**Issue by lshz0088** [ElemeFE/element#16338]
### Element UI version
2.10.0

### OS/Browsers version
谷歌

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lshz0088/pen/zVWYoV

### Steps to reproduce
例如：el-switch组件和el-input组件的高度不一致，如果在仅仅使用一个el-row的情况下，不容易排版，需要自己给el-switch添加一个高度。

### What is Expected?
希望所有组件高度保持一致，为了不影响其他已使用的项目，或者搞个全局的属性进行优化也可以。

### What is actually happening?
组件高度不一致，导致排版错乱

**Comment by island205** [comment]
pr welcome
