### ISSUE TITLE
[Feature Request] el-image support preview big picture

### ISSUE THREAD

**Issue by vxhly** [ElemeFE/element#16333]
### Existing Component
是

### Component Name
el-image 

### Description
在业务需求中,向用户呈现的是缩略图形式的图片,但是用户又希望能够预览大图,,现解方案使用插件[vue-photo-preview](https://github.com/826327700/vue-photo-preview),,在此希望未来 el-image 也能集成预览大图的需求

**Comment by island205** [comment]
great idea

**Comment by fakaka** [comment]
可以把 image-viewer 单独暴露出来吗？

**Comment by fakaka** [comment]
还有可不可以鼠标放到按钮上换个颜色？
