### ISSUE TITLE
[Bug Report] The style of the table is abnormal when the height of the table is fixed and the column label is longer than 3 character after updating to 2.10.0

### ISSUE THREAD

**Issue by 484sha** [ElemeFE/element#16349]
### Element UI version
2.10.0

### OS/Browsers version
Google Chrome 74.0.3729.169

### Vue version
2.5.2

### Reproduction Link
https://codepen.io/484sha/pen/mZxzpb

### Steps to reproduce
the style of the table is abnormal when the height of the table is fixed and  the column label is longer than 3 character.
the same code works well in 2.8.2 but not in 2.10.0
![image](https://user-images.githubusercontent.com/31678934/60494258-01021880-9ce1-11e9-80b6-06934226b23b.png)
![image](https://user-images.githubusercontent.com/31678934/60494338-2d1d9980-9ce1-11e9-8f9c-df830e46428d.png)

### What is Expected?
the index column and buttons can display in 2.10.0

### What is actually happening?
the index column and buttons can't display in 2.10.0

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
