### ISSUE TITLE
[Feature Request] Add Drawer component like iViewUI

### ISSUE THREAD

**Issue by connecteev** [ElemeFE/element#16343]
### Existing Component
No

### Component Name
Drawer

### Description
iViewUI has a drawer component which is great for side menus and sidebars.
https://www.iviewui.com/components/drawer-en

Would be great to add this to ElementUI because otherwise we'll need something custom.
Ideally the implementation should have the same options. See 
API https://www.iviewui.com/components/drawer-en#API
Drawer events: https://www.iviewui.com/components/drawer-en#Drawer_events
Drawer slot: https://www.iviewui.com/components/drawer-en#Drawer_slot

**Comment by connecteev** [comment]
Duplicate of #15030
Leaving this open just to get your attention on this request. Thank you!

**Comment by wangqi908** [comment]
感觉抽屉很实用,希望加入

**Comment by island205** [comment]
we will release this component in version 2.12.0
