### ISSUE TITLE
[Bug Report] el-cascader Level 1 child ren is a space-time update problem

### ISSUE THREAD

**Issue by vxhly** [ElemeFE/element#16348]
### Element UI version
2.9.2

### OS/Browsers version
Mac OS/Google Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/vxhly/pen/MMVPgJ

### Steps to reproduce
先选择其他的选项,当cascader有值之后,,,修改其值为 台湾省(该 children 为空),这时候,再次修改时展现的 children 没有更新为空选项 仍然为上一步操作的 children

### What is Expected?
再次选择 children 为空的选项时,再次修改该 children 列表应该更新为空或者不显示,label较长时显示 tooltip

### What is actually happening?
再次选择 children 为空的选项时,再次修改,该 children 列表显示成上一步骤展示的数据,,,,label较长时没有显示 tooltip

**Comment by luckyCao** [comment]
#16399
