### ISSUE TITLE
[Bug Report] Infinite Scroll does not work on Chrome (or any modern browser)

### ISSUE THREAD

**Issue by connecteev** [ElemeFE/element#16344]
### Element UI version
2.10.0

### OS/Browsers version
Mac OS High Sierra / Chrome latest version

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/connecteev/pen/BgrmXP?&editable=true

### Steps to reproduce
The infinite scroll does not work at 
https://codepen.io/connecteev/pen/BgrmXP?&editable=true
This is copied from
https://element.eleme.io/#/en-US/component/infiniteScroll

### What is Expected?
Infinite scroll should work.

### What is actually happening?
Error is seen in console and Infinite scroll does not work.

Error:
```
[Vue warn]: Error in directive infinite-scroll inserted hook: "TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'."

found in

---> <InfiniteScrollExample> at resources/js/components/InfiniteScrollExample.vue
       <App> at resources/js/App.vue
         <Root>
warn @ app.js:90559
logError @ app.js:91818
globalHandleError @ app.js:91813
handleError @ app.js:91773
callHook$1 @ app.js:96594
callInsert @ app.js:96531
wrappedHook @ app.js:92169
invokeWithErrorHandling @ app.js:91788
invoker @ app.js:92109
invokeInsertHook @ app.js:96260
patch @ app.js:96477
Vue._update @ app.js:93865
updateComponent @ app.js:93986
get @ app.js:94397
Watcher @ app.js:94386
mountComponent @ app.js:93993
Vue.$mount @ app.js:98963
Vue.$mount @ app.js:101848
Vue._init @ app.js:94931
Vue @ app.js:94997
(anonymous) @ app.js:7437
__webpack_require__ @ app.js:20
(anonymous) @ app.js:101903
__webpack_require__ @ app.js:20
(anonymous) @ app.js:66
(anonymous) @ app.js:69
app.js:91822 TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at inserted (app.js:51373)
    at callHook$1 (app.js:96592)
    at callInsert (app.js:96531)
    at wrappedHook (app.js:92169)
    at invokeWithErrorHandling (app.js:91788)
    at Object.invoker [as insert] (app.js:92109)
    at invokeInsertHook (app.js:96260)
    at Vue.patch [as __patch__] (app.js:96477)
    at Vue._update (app.js:93865)
    at Vue.updateComponent (app.js:93986)

```

**Comment by Jorian93** [comment]
I meet same error in firefox :


`[Vue warn]: Error in directive infinite-scroll inserted hook: "TypeError: Argument 1 of MutationObserver.observe does not implement interface Node."

found in

---> <Index>
       <AppMain> at src\views\layout\components\AppMain.vue
         <Layout> at src\views\layout\Layout.vue
           <App> at src\App.vue
             <Root> vue.runtime.esm.js:587
TypeError: "Argument 1 of MutationObserver.observe does not implement interface Node."
    inserted element-ui.common.js:38458
    VueJS 13
vue.runtime.esm.js:1737
TypeError: el.getBoundingClientRect is not a function`

**Comment by island205** [comment]
https://codepen.io/island205/pen/xojvGG?&editable=true

checkout this demo
