### ISSUE TITLE
[Feature Request] Selection Box Component can insert any code influence style inside

### ISSUE THREAD

**Issue by satel008** [ElemeFE/element#16346]
### Existing Component
是

### Component Name
择框组件

### Description
复现方法非常简单，copy一段选择框代码，然后在<el-select>标签和<el-option>标签插入任何内容，可以是静态文本或者函数
 <el-select v-model="select" placeholder="请选择" style="width: 100%;"><p v-loading="true"></p>
                <el-option
                  v-for="item in selects"
                  :key="item.value"
                  :label="item.label"
                  :value="item.value">
                </el-option>
              </el-select>
然后就可以看到影响样式了。
建议：
组件在编译的时候忽略掉标签之间的内容。

**Comment by island205** [comment]
Sorry, we have no plan to support this.
