### ISSUE TITLE
[Bug Report] Cascader's style is not available in Custom theme

### ISSUE THREAD

**Issue by JasonLam0990** [ElemeFE/element#16340]
### Element UI version
2.10.0

### OS/Browsers version
macOS 10.14.2 / Google Chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/YouCanTestLocally

### Steps to reproduce
1、Download the custom theme to the local 

2、Use the cascader component，
<el-cascader
    :options="options"
    :show-all-levels="false"
></el-cascader>

3、Click the cascader area, the style of cascader'dropdown is not available, and display a plain style
（点击cascader后，弹出的框框是纯文本，没有出现样式） 

### What is Expected?
I hope it has the style as usual

### What is actually happening?
the style of cascader'dropdown is not available in Custom Theme

**Comment by inikdom** [comment]
I had the same problem, but fixed it by re-generating the custom theme using the given link elementui has (https://elementui.github.io/theme-chalk-preview/#/en-US). 

change theme colour -> download theme.

**Comment by JasonLam0990** [comment]
> I had the same problem, but fixed it by re-generating the custom theme using the given link elementui has (https://elementui.github.io/theme-chalk-preview/#/en-US).
> 
> change theme colour -> download theme.

I have tried this method and Using element-theme before, and after you metioned it, I try again. But all these methods failed to fix it.

**Comment by island205** [comment]
what style of cascader you what to custom?

**Comment by JasonLam0990** [comment]
> what style of cascader you what to custom?

I just want to custom the theme color to the `#00CEB8`.
I download the theme package and put it into the project folder.
and import it by `import './public/#00CEB8/theme/index.css';`
and then I use the el-cascader, it display not as expect.
![屏幕快照 2019-07-04 上午9 40 12](https://user-images.githubusercontent.com/33661451/60634233-d333e580-9e40-11e9-806b-ac2110c7d6e6.png)

---

But if I use `import 'element-ui/lib/theme-chalk/index.css';`
it display as expect, but it isn't the custom theme !
![屏幕快照 2019-07-04 上午9 40 42](https://user-images.githubusercontent.com/33661451/60634324-1d1ccb80-9e41-11e9-88b0-0d75ad264ae8.png)

---

I have tried delete all my style, it still like that - -。
Thank you very much if you can help me fix the bug ~

**Comment by island205** [comment]
have a try our online theme roller https://element.eleme.cn/#/en-US/component/custom-theme#online-theme-roller

**Comment by JasonLam0990** [comment]
最后是通过重装element-ui，就解决了
