### ISSUE TITLE
[Bug Report] Paging Component Causes Browser No Response

### ISSUE THREAD

**Issue by Brian-Tong** [ElemeFE/element#16350]
### Element UI version
2.4.6

### OS/Browsers version
mac 10.14.5/chrome

### Vue version
2.6.0

### Steps to reproduce
     <el-pagination
          @size-change="handleSizeChange"
          @current-change="handleCurrentChange"
          :current-page="currentPage"
          :page-size="pageSize"
          layout=" total,  prev, pager, next"
          :total="total"
        />

 如果这样写 layout=" total,  prev, pager, next,"   会造成浏览器无响应并无错误提示信息

### What is Expected?
如果这不是个列，希望修复；如果是个例，希望给出具体原因或者思路

### What is actually happening?
没有任何错误信息，并会造成浏览器无响应

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
