### ISSUE TITLE
[Feature Request] How to get selectedLabel value from el-select?

### ISSUE THREAD

**Issue by ajithsimon** [ElemeFE/element#16355]
### Existing Component
Yes

### Component Name
el-select

### Description
I have a filter by state dropdown,
`<el-form-item label="State" prop="state">
              <el-select
                v-model="listQuery.state"
                filterable
                placeholder="Select State"
                @change="getCityList"
              >
                <el-option
                  v-for="item in stateList"
                  :key="item.name"
                  :label="item.name"
                  :value="item.code"
                ></el-option>
              </el-select>
            </el-form-item>`

On select I'm sending the code of the state to the api. but Im using closable el-tag to show the state name. There also I'm getting the code, but I want to show the state name instead. Is there anyway to get the key or label of the selected option?
Please help me out from this.

Thanks in advance.

**Comment by island205** [comment]
please provide  a valid reproduction link.
