### ISSUE TITLE
The [Bug Report] tree component needs two clicks to select when it has a disabled node

### ISSUE THREAD

**Issue by pycainiao** [ElemeFE/element#16361]
### Element UI version
2.9.2

### OS/Browsers version
window7 / Chrome：75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/agYMpg?editors=1010

### Steps to reproduce
1，当树树形数据里，子节点有禁用的情况下才会生效，即 disabled: true 的时候
2，第一次对根节点进行全选操作，获取选择的节点后，此时，使用此。$ refs.tree.setCheckedKeys（[]）;进行清空操作后，再对根节点进行选择，第一次会选择不上，需点击第二下操作才能选择上

### What is Expected?
清空已选择的节点后，再次点击，应该马上选择上

### What is actually happening?
清空已选择的节点后，再次点击，第一次点击不能进行全选操作。需要点击第二下

**Comment by luckyCao** [comment]
@pycainiao vue 使用 2.5.17 版本，就不会有这个问题了

**Comment by pycainiao** [comment]
> @pycainiao vue使用2.5.17版本，就不会有这个问题了

还了2.5.17 就会导致新的BUG 出现，重现链接如下：https://codepen.io/anon/pen/gJPVgq?tdsourcetag=s_pctim_aiomsg
重现方式：选中根节点，此时，无法对根节点进行取消选中操作
