### ISSUE TITLE
The V-model of [Bug Report] el-input does not support lazy modifiers

### ISSUE THREAD

**Issue by manaphp** [ElemeFE/element#16371]
### Element UI version
2.10.1

### OS/Browsers version
 windows/chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
一试就知道

### What is Expected?
生效

### What is actually happening?
不生效

**Comment by island205** [comment]
Sorry, we have no plan to support this.

> Input is a controlled component, it always shows Vue binding value.
> 
> Under normal circumstances, input event should be handled. Its handler should update component's binding value (or use v-model). Otherwise, input box's value will not change.
> 
> Do not support v-model modifiers.
