### ISSUE TITLE
[Feature Request] The label of the From item is not aligned when label-position = left & rule = required

### ISSUE THREAD

**Issue by winkay** [ElemeFE/element#16372]
### Existing Component
是

### Component Name
el-form

### Description
当输入框校验规则设置为必需，label-position设置为左对齐，红色 * 标识的表单label文字与非必需的表单label文字没有对齐。
【建议】非必需的表单文字前留出与红色 * 号标识同等宽度的空白，保持文字左对齐。

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
