### ISSUE TITLE
[Bug Report] Cascader cascade selector version 2.9.2 has problems and 2.8.2 performance is inconsistent

### ISSUE THREAD

**Issue by Zeus-Iqd** [ElemeFE/element#16377]
### Element UI version
2.9.2

### OS/Browsers version
macos

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/EBLOzY

### Steps to reproduce
选择普通业务，他会定位到第一个的数据。而2.8.2表现正常. 2.9及已上版本都不正常。

### What is Expected?
恢复2.8.2的正常表现

### What is actually happening?
选择普通业务，他会定位到第一个的数据

**Comment by luckyCao** [comment]
#16393 16393

**Comment by Zeus-Iqd** [comment]
@luckyCao 
大哥请问下，这个在2.10.1的版本上还是没有解决啊！

**Comment by island205** [comment]
fixed in #15935

**Comment by Zeus-Iqd** [comment]
@island205 多谢
