### ISSUE TITLE
[Feature Request] Version 2.10.0 of element-ui, Vue version limitation

### ISSUE THREAD

**Issue by luocong2016** [ElemeFE/element#16375]
### Existing Component
否

### Component Name
all

### Description
element- ui 2.10.0 版本,限制了 vue 版本在 "vue": "2.5.21"。
对 #(v-slot) 的兼容出现问题，为什么会突然限制了 vue 版本呢？

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
