### ISSUE TITLE
[Bug Report] why el-upload delete button display controlled by “disabled” attr.为什么上传组件的删除按钮受disabled控制显示隐藏？

### ISSUE THREAD

**Issue by Nathanlee2010** [ElemeFE/element#16378]
### Element UI version
2.4.11

### OS/Browsers version
win10 / chrome@latest

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/m69vw3cq/4/

### Steps to reproduce
做两次：点击上传选取图片
disabled的值为true
删除按钮变为不可见。

### What is Expected?
element团队好，我是vue   element UI新手。

我期望上传组件在达到上传的数量之后，上传组件变得不可点击，而不是通过limit 和on-exceed来给用户带来挫败感(既然达到了数量限制，为什么还能点击组件选取图片？)。

求助：如何在我本地的项目上，去掉delete按钮的 v-if="!disabled" 属性？

### What is actually happening?
删除按钮受disabled控制

**Comment by a631807682** [comment]
https://element.eleme.cn/#/zh-CN/component/upload#wen-jian-suo-lue-tu

用`scoped-slot`自己定义

**Comment by Nathanlee2010** [comment]
> https://element.eleme.cn/#/zh-CN/component/upload#wen-jian-suo-lue-tu
> 
> 用`scoped-slot`自己定义

非常感谢！太棒了。

btw: 需要升级elment-ui 才能使用<code>file slot</code>
