### ISSUE TITLE
[Bug Report] Table show-summary display bug

### ISSUE THREAD

**Issue by nuliaxiaoheng** [ElemeFE/element#16374]
### Element UI version
2.10.1

### OS/Browsers version
Chrome 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/new

### Steps to reproduce
<el-table
        :data="tableData"
        stripe
        border
        show-summary
        size="small"
        width="100%"
        height="calc(100vh - 203px)"
        :summary-method="getSummaries"
        @row-dblclick="jumpDetail"
        @header-click="openHandelColumn"
        header-cell-class-name="row-class-name"
      >
渲染出来的页面合计行被挤下去了，拉动浏览器抖一下就好了
![image](https://user-images.githubusercontent.com/35363368/60560555-d8325f80-9d82-11e9-94e7-96206f0ab58c.png)
抖动后
![image](https://user-images.githubusercontent.com/35363368/60560599-fb5d0f00-9d82-11e9-868d-d2dff4d3f548.png)

### What is Expected?
直接渲染出来正确的结果

### What is actually happening?
现在渲染的页面底下的合计行没有，需要拉动浏览器抖动一下才会显示出来

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by jekorx** [comment]
@zhanghengGetUp 你好，可以尝试在ajax请求获取完tableData之后调用Table的```doLayout()```方法，可[参照文档](https://element.eleme.cn/#/zh-CN/component/table#table-methods)。
ps：我使用的Element版本是2.14.1
