### ISSUE TITLE
[Bug Report] el-table Infinite jitter

### ISSUE THREAD

**Issue by mouyong** [ElemeFE/element#16370]
### Element UI version
2.4.6

### OS/Browsers version
win10/Google Chrome 已是最新版本 版本 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mouyong/pen/MMGzYr

### Steps to reproduce
编译后，通过对应的路由访问页面

重现链接中是相关的 vue 代码
这是出现问题的 gif 图，
https://files.gitter.im/ElemeFE/element/pChc/aaa.gif

### What is Expected?
表格不抖动

### What is actually happening?
表格无限抖动

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by island205** [comment]
https://github.com/ElemeFE/element/issues/16167#issuecomment-506598890
