### ISSUE TITLE
[Bug Report] When Table sets high and has a fixed column, it will not scroll at the fixed column.

### ISSUE THREAD

**Issue by jcbacc** [ElemeFE/element#16388]
### Element UI version
2.10.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jcbacc/pen/jjKWgN

### Steps to reproduce
滚动列的位置无法拖动滚动条，但只要改变浏览器窗口大小或者不设置height就不会出现这个问题

### What is Expected?
可以拖动滚动条

### What is actually happening?
无法拖动滚动条

**Comment by 1207934561** [comment]
如果是指底部滚动条的话，看你的示例里单元格的宽度没有超出表格的宽度，所以触发不了列的fixed效果。

**Comment by jcbacc** [comment]
具体情况就跟下图一样，设置了hight属性之后fixed固定列无法移动，但只要改变浏览器大小（比如打开控制台），就没问题了。是我的onresize监听跟源码有冲突？
![Image of Yaktocat](https://jcbacc.github.io/gits/ezgif-1-c2b648e94c1b.gif)

**Comment by BLUE-FAT** [comment]
因为fixed列是position:absolute,所以你调整高度他就会覆盖class=el-table__body-wrapper is-scrolling-middle 这个div产生的滚动条。 解决办法就是增加 class=el-table__body-wrapper is-scrolling-middle 这个div的 相同的高度差。

**Comment by jcbacc** [comment]
> 因为fixed列是position:absolute,所以你调整高度他就会覆盖class=el-table__body-wrapper is-scrolling-middle 这个div产生的滚动条。 解决办法就是增加 class=el-table__body-wrapper is-scrolling-middle 这个div的 相同的高度差。

感谢七神

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
