### ISSUE TITLE
When [Bug Report] filter-multiple is true, outsideclick does not trigger the filter-change method

### ISSUE THREAD

**Issue by liwfd** [ElemeFE/element#16384]
### Element UI version
2.10.1

### OS/Browsers version
mac/google chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/api/post/library/pure/

### Steps to reproduce
1、展开表头筛选后勾选某一项点击筛选;
2、展开表头取消步骤1勾选项,不点击筛选直接点击筛选框外部关闭;

### What is Expected?
直接点击外部关闭时希望触发filter-change方法,或者步骤1勾选内容不丢失

### What is actually happening?
直接点击外部关闭时步骤1勾选内容丢失,也没有触发filter-change方法

**Comment by liwfd** [comment]
Reproduction Link
https://jsfiddle.net/uoLt78nh/

**Comment by ziyoung** [comment]
不能完全说是 bug。这种情况有多种解释。

---

![image](https://user-images.githubusercontent.com/12947422/62522720-d9b0e500-b864-11e9-8163-625ac7f2b499.png)


比如你打开一个弹出层，在 input 中填写了一些内容，这时候关闭弹出层（没有点击确定按钮）。当你再次打开的时候，之前填写的值可能依然存在，也可能不存在。

**Comment by liwfd** [comment]
@ziyoung 主要会影响用户体验,薛定谔的猫

**Comment by ziyoung** [comment]
> @ziyoung 主要会影响用户体验,薛定谔的猫

就拿我刚才的例子来说，关闭后清除或者不清楚用户输入的内容，这两种做法都可以（根据实现方式来决定），都能解释的通。
