### ISSUE TITLE
[Bug Report] Table with fixed column has layout break when it is in keep-alive component

### ISSUE THREAD

**Issue by SUPERSUJ** [ElemeFE/element#16382]
### Element UI version
2.10.1

### OS/Browsers version
window 10 / chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/supersuj/pen/YovKNO?editors=1010

### Steps to reproduce
1、click the Go to table-test button.
2、click the Go to Bar button.
3、click the Go to table-test button.

### What is Expected?
![微信截图_20190703165731](https://user-images.githubusercontent.com/20472814/60578542-f5cbed00-9db3-11e9-9c0a-8fbddde1653d.png)

In the middle of the last cell of the fixed column of the table, there should be no such gray line

### What is actually happening?
![微信截图_20190703165925](https://user-images.githubusercontent.com/20472814/60578565-fe242800-9db3-11e9-88e8-7dd1bc52645f.png)

A gray line appears in the middle of the last cell in the fixed column of the table

**Comment by martincarles** [comment]
I can reproduce that.

**Comment by iamkun** [comment]
might be a bug only in windows chrome

**Comment by martincarles** [comment]
@iamkun, I'm using Ubuntu 18.04
