### ISSUE TITLE
[Bug Report] selece component drop-down box text content when echo right alignment

### ISSUE THREAD

**Issue by xiaosongread** [ElemeFE/element#16389]
### Element UI version
2.10.1

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1.下拉选项文字多一点设置的
2.来回多次切换文字多的选项
3.同时的windows/火狐必显，我的mac/chrome，来回一直多次切换选择就复显

### What is Expected?
回显的时候文字左对齐

### What is actually happening?
回显的时候文字右对齐

**Comment by junyiz** [comment]
This is browser behavior, reference [stackoverflow](https://stackoverflow.com/questions/511088/use-javascript-to-place-cursor-at-end-of-text-in-text-input-element)。

**Comment by xiaosongread** [comment]
这是把我的issues关掉了吗？为什么一周了没有回复呢？

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
