### ISSUE TITLE
When [Bug Report] filter-multiple is true, outsideclick does not trigger the filter-change method

### ISSUE THREAD

**Issue by liwfd** [ElemeFE/element#16387]
### Element UI version
2.10.1

### OS/Browsers version
mac/google chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/uoLt78nh/

### Steps to reproduce
1、展开表头筛选后勾选某一项点击筛选;
2、展开表头取消步骤1勾选项,不点击筛选直接点击筛选框外部关闭;

### What is Expected?
直接点击外部关闭时希望触发filter-change方法,或者步骤1勾选内容不丢失

### What is actually happening?
直接点击外部关闭时步骤1勾选内容丢失,也没有触发filter-change方法

**Comment by iamkun** [comment]
重复
