### ISSUE TITLE
[Feature Request] Needs some events of Calendar

### ISSUE THREAD

**Issue by joezhang-sh** [ElemeFE/element#16380]
### Existing Component
Yes

### Component Name
Calendar

### Description
triggers events when clicking the buttons at the upper right corner.  e.g. Next Month is clicked or currentMonthChanged(newMonth)

**Comment by fudax** [comment]
同意，现在用vue-fullcalendar顶替的

**Comment by okool** [comment]
日历就是摆设,没任何功能.

**Comment by ziyoung** [comment]
> 日历就是摆设,没任何功能.

有什么需求就直接来提。

**Comment by luckyCao** [comment]
@fudax 有什么需求可以提出来哦

**Comment by fudax** [comment]
> @fudax 有什么需求可以提出来哦

我2楼的答复，意思就是同楼主意见，需要event如下：
setCurrentDate
onDayChange
onDayClick
slot支持HTML，类似Notification
