### ISSUE TITLE
[Bug Report] Mouse moving quickly from the first-level menu to the second-level menu will cause the second-level menu to close automatically (not necessarily, but with a high frequency)

### ISSUE THREAD

**Issue by canzu** [ElemeFE/element#16394]
### Element UI version
2.10.1

### OS/Browsers version
macOS 10.14.4 / Google Chrome 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/GbGoXd

### Steps to reproduce
鼠标从一级菜单快速移动至二级菜单

### What is Expected?
二级菜单不会自动关闭

### What is actually happening?
鼠标从一级菜单快速移动至二级菜单导致二级菜单自动关闭，无法选择二级菜单内容

**Comment by canzu** [comment]
![Kapture 2019-07-04 at 11 44 28](https://user-images.githubusercontent.com/8034978/60638841-8eb14580-9e52-11e9-89e7-5041129a244c.gif)

**Comment by luckyCao** [comment]
pr welcome

**Comment by canzu** [comment]
seems this commit 6d9529776dc2790e0e80335ade3fea27d0975e8f has fixed this problem.
