### ISSUE TITLE
如何获取el-tree的半选中状态的数据

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#1639]
由于子节点不是全选，所以父节点处于half(半选中)状态，求问：怎么获取这些因为子节点的选中导致父节点（以及祖宗节点）处于半选中状态的数据。

**Comment by Leopoldthecoder** [comment]
参考：http://jsfiddle.net/leopoldthecuber/yu2me25j/

**Comment by kopheece** [comment]
@Leopoldthecoder 十分感谢

**Comment by happyWilliam** [comment]
多谢Leopoldthecoder ，已经可以看到拿到了父节点，但是如何获取父节点的index等属性值呢？
