### ISSUE TITLE
How is the [Bug Report] loading component compatible with ie9, which has no animation effect, or how to customize gif images?

### ISSUE THREAD

**Issue by caim18340** [ElemeFE/element#16405]
### Element UI version
2.10.1

### OS/Browsers version
win/ie9

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
<template>
  <el-table
    v-loading="loading"
    element-loading-text="拼命加载中"
    element-loading-spinner="el-icon-loading"
    element-loading-background="rgba(0, 0, 0, 0.8)"
    :data="tableData"
    style="width: 100%">
    <el-table-column
      prop="date"
      label="日期"
      width="180">
    </el-table-column>
    <el-table-column
      prop="name"
      label="姓名"
      width="180">
    </el-table-column>
    <el-table-column
      prop="address"
      label="地址">
    </el-table-column>
  </el-table>
</template>

<script>
  export default {
    data() {
      return {
        tableData: [{
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }],
        loading: true
      };
    }
  };
</script>

### What is Expected?
希望自定义图片路劲，兼容ie9动画效果

### What is actually happening?
不兼容ie9，不能自定义除icon外的图片

**Comment by iamkun** [comment]
pr welcomed
