### ISSUE TITLE
[Bug Report] [Bug report] <el-input autofocus> attribute ineffective

### ISSUE THREAD

**Issue by gedkirkham** [ElemeFE/element#16417]
### Element UI version
0.1.0

### OS/Browsers version
Firefox - 67.0.4

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/0zLea74f/

### Steps to reproduce
Use <el-input> to create an input element. Add autofocus attribute to that element.

### What is Expected?
Expect element to be focused on load.

### What is actually happening?
Element is not in focus on load.

**Comment by CYan596** [comment]
:autofocus="true"

**Comment by gedkirkham** [comment]
> 
> 
> :autofocus="true"

That fails to work as well.

**Comment by luckyCao** [comment]
@gedkirkham 这是一个原生属性，看起来是浏览器的 bug，你用 fixfox 68.0.1 有问题吗
