### ISSUE TITLE
[Feature Request] Notification component pop-up content, how to add other components?

### ISSUE THREAD

**Issue by liubin595338764** [ElemeFE/element#16416]
### Existing Component
是

### Component Name
Notification 

### Description
Notification 组件弹出的内容里面如何添加放其他组件，请给个例子可以吗？

**Comment by liubin595338764** [comment]
比如我接受到后端的一个通知的时候，用Notification显示一个进行中的loading效果，完成之后关掉这个Notification，用另外一个Notification通知完成。
还有我想用Notification让用户填写姓名、邮箱的小弹窗，两个input的输入框，一个button提交按钮。

**Comment by iamkun** [comment]
pr welcomed
