### ISSUE TITLE
[Bug Report] Cascader is case sensitive, select is not when filterable 

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#16411]
### Element UI version
2.10.1

### OS/Browsers version
Mojave

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
Search something on cascader

### What is Expected?
Cascader search functionality should be case insensitive

### What is actually happening?
Case sensitive

**Comment by junyiz** [comment]
Becase the default search logic is [string includes ](https://github.com/ElemeFE/element/blob/905e812fb5f2c3a259d1199fda0a5c2d58d53720/packages/cascader/src/cascader.vue#L530)
But you can customize search logic by prop filter-method.

**Comment by SimonaliaChen** [comment]
> Becase the default search logic is [string includes ](https://github.com/ElemeFE/element/blob/905e812fb5f2c3a259d1199fda0a5c2d58d53720/packages/cascader/src/cascader.vue#L530)
> But you can customize search logic by prop filter-method.

Exactly
