### ISSUE TITLE
[Bug Report] Chrome will crash when set Table Component 'thead' css 'display' to none

### ISSUE THREAD

**Issue by ustbhuangyi** [ElemeFE/element#16427]
### Element UI version
2.10.1

### OS/Browsers version
MacOS 10.13.6 / Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen >> https://element.eleme.io/#/zh-CN/component/table

### Steps to reproduce
1. Open chrome dev tools
2. Find any element of thead.
3. Add 'display:none' rule for the '.el-table thead' selector.
4. Then Chrome crashed.

PS. The issue link rule is bypassed, because links on official websites can reproduce this problem very well.
The reproduction link is https://element.eleme.io/#/zh-CN/component/table

### What is Expected?
Chrome won't crash,and the table header can be hidden.

### What is actually happening?
Chrome crashed.

**Comment by wkl007** [comment]
Yes, I have the same problem.
