### ISSUE TITLE
Can [Feature Request] Table Components Increase the Form of Table Row Groups?

### ISSUE THREAD

**Issue by lspdou** [ElemeFE/element#16426]
### Existing Component
是

### Component Name
table

### Description
表格组件能增加以下的形式吗？
![微信图片_20190705163031](https://user-images.githubusercontent.com/26620617/60709747-be8c4600-9f43-11e9-9b28-0f0ed8ffec41.png)

**Comment by iamkun** [comment]
please use table custom render
