### ISSUE TITLE
[AutoComplete]远程搜索，输中文的时候每打一个字符就会请求一次

### ISSUE THREAD

**Issue by iNuanfeng** [ElemeFE/element#1642]
现在是每输入一个英文字符就立马去请求远程接口了。
用中文搜索的时候应该等输入完一个字的时候再去请求远程接口获取数据。

**Comment by Kingwl** [comment]
然而el-input的change和input是在一起的。。

**Comment by lyz1990** [comment]
人工干预一下，停止输入一段时间才发请求，比如这样：
```javascript
    _.debounce(
      function () {
        this.fetchPosts()
      },
      300
    )
```

**Comment by QingWei-Li** [comment]
和楼上的一样
官方给的例子是 https://jsbin.com/zefawu/3/edit?html,output
改成 Element 的 http://jsfiddle.net/3bc7qoj6/
