### ISSUE TITLE
Dynamic modification of node-key, props and default-expanded-keys attributes by the [Bug Report] tree component will result in tree not expanding

### ISSUE THREAD

**Issue by justjoker** [ElemeFE/element#16432]
### Element UI version
2.8.2

### OS/Browsers version
MacOS 10.14.5 / Chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/justjoker/pen/ZdMGNp

### Steps to reproduce
在重现链接里 操作选择 新数据 即可重现

### What is Expected?
希望可以在改变新数据的时候 也可以按照新数据 设置的默认展开值 来展开树

### What is actually happening?
实际动态修改后 不能根据新的 默认展开值 展开树

**Comment by luckyCao** [comment]
@justjoker https://codepen.io/luckyCao/pen/jONWopK 这样使用

**Comment by luckyCao** [comment]
数据改变的时候，改变一下 key 属性，让 vue 去重新创建而不是更新组件
