### ISSUE TITLE
[Bug Report] el-calendar is not practical

### ISSUE THREAD

**Issue by richwxd** [ElemeFE/element#16439]
### Element UI version
2.10.1

### OS/Browsers version
Windows 10 / Chrome,Firefox

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
直接打开即可

### What is Expected?
1. 可以自定义按日期，月视图，
2. 可以自由选择年，月
3. 可以传入绑定数据
4. 单元格可以显示自定义内容
5. 单元格可以自设背景色，如某些厂家是单休，通过数据中的属性，如果是休息日，可以动态指定单元格背景色为灰色
6. 点击选中和再次点击取消选中

### What is actually happening?
以上功能一个都没有

**Comment by iamkun** [comment]
pr welcomed
