### ISSUE TITLE
[Bug Report] el-select fetch remote and filter error

### ISSUE THREAD

**Issue by cz4rny** [ElemeFE/element#16434]
### Element UI version
2.10.1

### OS/Browsers version
OSX 10.14.4 Mojave, Chrome Version 75.0.3770.100

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/anon/pen/xoaOja?&editable=true

### Steps to reproduce
1. Input "ala"
2. Delete everything
3. Click outside the dropdown list or press ESC
4. Click again on the input

### What is Expected?
A full list of all the states to choose from

### What is actually happening?
Nothing, i.e. there is no list to choose from. You have to start typing. In order to get the full list of possibilities, you have to type something in and delete it again.

Each time you try this, there's an error in the console:
Uncaught TypeError: c.querySelectorAll is not a function
    at MutationObserver.<anonymous> (content_script_bundle.js:16)
(anonymous)	@	content_script_bundle.js:16
attributes (async)		
addClass	@	vue.js:7878
addTransitionClass	@	vue.js:7995
performLeave	@	vue.js:8342
leave	@	vue.js:8328
update	@	vue.js:8626
callHook$1	@	vue.js:6667
_update	@	vue.js:6596
updateDirectives	@	vue.js:6569
patchVnode	@	vue.js:6303
patch	@	vue.js:6469
Vue._update	@	vue.js:3943
updateComponent	@	vue.js:4061
get	@	vue.js:4472
run	@	vue.js:4547
flushSchedulerQueue	@	vue.js:4305
(anonymous)	@	vue.js:1989
flushCallbacks	@	vue.js:1915
Promise.then (async)		
timerFunc	@	vue.js:1942
nextTick	@	vue.js:1999
queueWatcher	@	vue.js:4397
update	@	vue.js:4537
notify	@	vue.js:745
reactiveSetter	@	vue.js:1070
proxySetter	@	vue.js:4624
(anonymous)	@	pen.js:38
setTimeout (async)		
remoteMethod	@	pen.js:37
handleQueryChange	@	index.js:1
(anonymous)	@	index.js:1
u	@	index.js:1
setTimeout (async)		
(anonymous)	@	index.js:1
invokeWithErrorHandling	@	vue.js:1863
invoker	@	vue.js:2184
original._wrapper	@	vue.js:7541

**Comment by luckyCao** [comment]
Sorry, we have no plan to fix this

**Comment by cz4rny** [comment]
@luckyCao Could you provide any additional context? Like is this the desired behaviour?

**Comment by cz4rny** [comment]
Can I get some context on this, please? As of now this is an obvious bug, because a) the behaviour is wrong b) there are console errors.

The only solution to fix this is to wrap `el-select` with a data downloader so that it filters through a downloaded set of entries. This is essentially re-writing the `remote-data` functionality on our own.
