### ISSUE TITLE
[Bug Report] Custom Table Index List Header Invalid

### ISSUE THREAD

**Issue by Lozvoe** [ElemeFE/element#16438]
### Element UI version
2.10.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lozvoe/pen/bPxxBW

### Steps to reproduce
使用v-slot:header 自定义索引列表头图标，无效!

### What is Expected?
索引列表头图标变为自己定义的

### What is actually happening?
图标无改变 还是#

**Comment by ziyoung** [comment]
index 列的表头是不允许被覆盖。
