### ISSUE TITLE
[Feature Request] el-table-column width

### ISSUE THREAD

**Issue by xuekai-china** [ElemeFE/element#16440]
### Existing Component
是

### Component Name
el-table-column

### Description
el-table-column 的 width 为什么不支持百分比， 而且不设置 width 时为什么默认 80px； 

el-table__header-wrapper 已经继承了上层元素的width：100%，为什么 el-table__header 不继续继承下去，默认把 el-table-column 的 width 等份，而下层的 el-table__header 却是在行内 style 写死 width：80px * el-table-column.length; 

el-table__body-wrapper 同理。

设计模式简直匪夷所示！！！

**Comment by xuekai-china** [comment]
上述有误： el-table-column 的 width 为什么不支持百分比， 而且不设置 width 时 min-width 为什么默认 80px；

**Comment by ziyoung** [comment]
不如先看看这篇文章 https://zhuanlan.zhihu.com/p/33280304  ，了解一下 table 的实现原理。

**Comment by ziyoung** [comment]
这个 feature 我们暂时不打算支持。
