### ISSUE TITLE
[Bug Report] “expand-row-keys” does not work when setting table data asynchronously

### ISSUE THREAD

**Issue by justyeh** [ElemeFE/element#16449]
### Element UI version
2.10.1

### OS/Browsers version
win7

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/pXxaMz

### Steps to reproduce
设置expandRowKeys，ajax获取数据为表格赋值，expandRowKeys无效

### What is Expected?
expand-row-keys设置的行应该正常展开

### What is actually happening?
行没有展开

**Comment by aabc6419tw** [comment]
我也有同樣的問題
