### ISSUE TITLE
[Feature Request] upload component, using scoped-slot to set thumbnail template, the progress bar is not displayed.

### ISSUE THREAD

**Issue by 496044859** [ElemeFE/element#16448]
### Existing Component
是

### Component Name
upload

### Description
upload组件使用 scoped-slot 去设置缩略图模版后，进度条不显示了，不能实时的告诉客户上传进度情况。能否先显示实时进度条，完成上传后再显示定义的缩略图模版？

**Comment by iamkun** [comment]
pr welcomed

**Comment by jhmei** [comment]
me too. How to resolved? @iamkun

**Comment by jhmei** [comment]
![image](https://user-images.githubusercontent.com/29725486/67090440-b0092800-f1dc-11e9-91e3-58f19a7683a5.png)
