### ISSUE TITLE
[Feature Request] a question about import components what you need

### ISSUE THREAD

**Issue by RainedX** [ElemeFE/element#16443]
### Existing Component
否

### Component Name
no

### Description
when you import components what you need, install 'babel-plugin-component' ,and edit .babelrc(babel7.x), you should follow the following configuration:
{
  "plugins": [
     ["component", 
       {
         "libraryName":  "element-ui",
         "styleLibraryName":  "theme-chalk"
    }
  ]
]

The official website should be updated

**Comment by iamkun** [comment]
https://element.eleme.cn/#/zh-CN/component/quickstart#an-xu-yin-ru

**Comment by zhaofy** [comment]
这个issue怎么直接关了呢？
babel 7 如何按需引入，官方文档上建议加上说明，目前的配置在babel 7下直接报错。
