### ISSUE TITLE
[Bug Report] cannot use popper.js option

### ISSUE THREAD

**Issue by adjkldd** [ElemeFE/element#16444]
### Element UI version
2.10.1

### OS/Browsers version
latest

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ldd/pen/BgqQrP

### Steps to reproduce
1. open demo  https://codesandbox.io/s/vue-template-nxk2t
2. click the bottom-right button. Icon not loaded :( 
3. open the console at bottom if not shown
4. You see the error

### What is Expected?
Now, comment below code:

    popperOptions: {
        modifiers: {
          computeStyle: {
            x: "top",
            y: "left"
          }  
        }
    },

Then, click the bottom-right button. Add a fruit, the popover grows down. But it should grow up.
Maybe it's time to update popper.js file in source code.

### What is actually happening?
the popover grows down.

**Comment by iamkun** [comment]
computeStyle is not supported in our current version of popper.js
