### ISSUE TITLE
[Bug Report] table component setCurrent Row not work

### ISSUE THREAD

**Issue by mrzhiin** [ElemeFE/element#16452]
### Element UI version
2.10.1

### OS/Browsers version
Windows 10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/ydRqrM?&editable=true

### Steps to reproduce
1.Click "选中第一行"
2.Click "取消选择"

### What is Expected?
First show highlight then hide highlight

### What is actually happening?
Show highlight then not hide highlight

**Comment by luckyCao** [comment]
https://codepen.io/luckyCao/pen/vomrZE

@mrzhiin 这样改
