### ISSUE TITLE
[Bug Report] Cascader component switches from multi-level to single-level when there are both multi-level and first-level options. The selected state of the parent of the previously selected multi-level option except the last level is not eliminated. The expected result is that only single-level selected state exists.

### ISSUE THREAD

**Issue by liziweiTT** [ElemeFE/element#16468]
### Element UI version
2.9.1

### OS/Browsers version
win7 64位/chrome 73

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/anon/pen/Zdmoby#anon-login

### Steps to reproduce
选择默认click触发子菜单，第一步先选择至最后一级选项（组件-Form-input输入框），再选择单级的选项（资源）

### What is Expected?
当由多级切换到单级时，多级的所有选项的选中状态都要取消，仅保留当前选择的单级选项的选中状态

### What is actually happening?
当由多级切换到单级选项时，多级仅最后一级的选中状态被取消，其父级的选中状态依然存在，且单级选项也是处于选中状态

**Comment by luckyCao** [comment]
@liziweiTT fixed, place upgrade to 2.11.1
