### ISSUE TITLE
[Feature Request] Popover can't support multiple triggers

### ISSUE THREAD

**Issue by odex21** [ElemeFE/element#16462]
### Existing Component
是

### Component Name
Popover 弹出框

### Description
The popover now is only suport single trigger by String.
But I find multiple triggers are supported in Tooltip.js.

https://popper.js.org/tooltip-documentation.html

[options.trigger]  String  'hover focus'

How tooltip is triggered - click, hover, focus, manual. You may pass multiple triggers; separate them with a space. manual cannot be combined with any other trigger.

**Comment by iamkun** [comment]
pr welcomed
