### ISSUE TITLE
table 中的无法进行 select 选中操作 

### ISSUE THREAD

**Issue by mwnubd** [ElemeFE/element#1646]
### ElementUI version
1.0.5

### Vue version
 2.0.0-rc.4 

### Reproduction Link
https://jsfiddle.net/mwnubd/tzcL8uqj/

**Comment by dearbird** [comment]
re-produce on version 1.0.6, please fix it.

**Comment by furybean** [comment]
应该和你的 v-model 设置有关系，例子中用的是 `v-model="value"` ，不过我并找不到 value。

我稍微改了一下，是可以用的：https://jsfiddle.net/tzcL8uqj/1/

**Comment by dearbird** [comment]
是的，我遇到的是另外一个问题，另提issue #1689
