### ISSUE TITLE
The [Bug Report] table component dynamically sets height, and when the height attribute is true and false is cut back, overlapping lines appear on the table.

### ISSUE THREAD

**Issue by curryhh** [ElemeFE/element#16464]
### Element UI version
2.6.1

### OS/Browsers version
PC webkit

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
因为我是动态设置的，当每页显示20的时候才会触发高度，小于20的时候不设置高度，但是table的行内样式还是width: 100%; height: 700px;,要重新加载页面才会刷新回来

### What is Expected?
页数来回切换正常，现在是设置成功，但是当我变回10个/页的情况，height应该是失效的

### What is actually happening?
因为我是动态设置的，当每页显示20的时候才会触发高度，小于20的时候不设置高度，但是table的行内样式还是width: 100%; height: 700px;,要重新加载页面才会刷新回来

![微信图片_20190708195426](https://user-images.githubusercontent.com/22719549/60808773-ade60500-a1bb-11e9-8668-09db707a7590.png)

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
