### ISSUE TITLE
Use of [Bug Report] Calendar Plug-ins

### ISSUE THREAD

**Issue by Flippedzhulinyi** [ElemeFE/element#16461]
### Element UI version
2.10.1

### OS/Browsers version
window10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Flipped/671x3Lvd/1/

### Steps to reproduce
修改日历字体大小，单元格大小，单元格里面的内容会错位

### What is Expected?
修改样式单元格内容不变

### What is actually happening?
修改日历字体大小，单元格大小，单元格里面的内容会错位

**Comment by iamkun** [comment]
not element bug
