### ISSUE TITLE
This. $refs. tree. setCurrentRow (this. list [4]. id);

### ISSUE THREAD

**Issue by ChaseChan** [ElemeFE/element#16469]
### Existing Component
是

### Component Name
el-table

### Description
el-table的setCurrentRow 是否支持高亮树形列表的子选项，并且能定位到该位置

而且现在的setCurrentRow是传当前table行数据，个人认为不是传唯一标志id之类的会不会比较适合。

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
