### ISSUE TITLE
[Bug Report] A small problem - - component - - Dropdown drop-down menu - - trigger mode - - Oyster fry - - icon class name should be el-icon-circle-check

### ISSUE THREAD

**Issue by RyanIPO** [ElemeFE/element#16471]
### Element UI version
2.10.1

### OS/Browsers version
Chrome 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/leeeeeee/pen/RzqJOL

### Steps to reproduce
<el-dropdown-item icon="el-icon-circle-check-outline">蚵仔煎</el-dropdown-item>

修改为

<el-dropdown-item icon="el-icon-circle-check">蚵仔煎</el-dropdown-item>

### What is Expected?
改一下呗，强迫症看着难受

### What is actually happening?
改一下呗，强迫症看着难受

**Comment by iamkun** [comment]
add to 3.0. breaking change
