### ISSUE TITLE
[Bug Report] el-table has the problem of infinite recalculation width under Chrome browser

### ISSUE THREAD

**Issue by jonasyuk** [ElemeFE/element#16470]
### Element UI version
2.10.1

### OS/Browsers version
Window10 / Chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jonasyuk/pen/NZEzNw

### Steps to reproduce
下面这个是重现代码，打开就能看到。 

https://codepen.io/jonasyuk/pen/NZEzNw

### What is Expected?
不应该一直重算宽度导致页面出现抖动。

### What is actually happening?
看了一下源码，感觉问题是出现在el-table里面的bodyWidth计算逻辑在chrome浏览器下不兼容(flex布局下，重现中用了el-container组件)。

**Comment by jonasyuk** [comment]
Currently, we temporary solution is to set the height in the table. 

`<el-table :data="tableData" **height="100%"**>
                                <el-table-column label="ID" prop="id"></el-table-column>
                                <el-table-column label="名字" prop="name"></el-table-column>
                                <el-table-column label="操作" width="150px">
                                    <el-button type="primary" size="mini">编辑</el-button>
                                </el-table-column>
                            </el-table>`


https://codepen.io/jonasyuk/pen/EBOREY

**Comment by kundaneyug** [comment]
> Currently, we temporary solution is to set the height in the table.
> 
> ```
> <el-table :data="tableData" height="100%">
>                                 <el-table-column label="ID" prop="id"></el-table-column>
>                                 <el-table-column label="名字" prop="name"></el-table-column>
>                                 <el-table-column label="操作" width="150px">
>                                     <el-button type="primary" size="mini">编辑</el-button>
>                                 </el-table-column>
>                             </el-table>
> ```
> 
> https://codepen.io/jonasyuk/pen/EBOREY

After adding height property when the table is shown my tab freezes.
after that page goes blank.

I am having issues with table that it is not working at all

**Comment by jonasyuk** [comment]
> > Currently, we temporary solution is to set the height in the table.
> > ```
> > <el-table :data="tableData" height="100%">
> >                                 <el-table-column label="ID" prop="id"></el-table-column>
> >                                 <el-table-column label="名字" prop="name"></el-table-column>
> >                                 <el-table-column label="操作" width="150px">
> >                                     <el-button type="primary" size="mini">编辑</el-button>
> >                                 </el-table-column>
> >                             </el-table>
> > ```
> > 
> > 
> > https://codepen.io/jonasyuk/pen/EBOREY
> 
> After adding height property when the table is shown my tab freezes.
> after that page goes blank.
> 
> I am having issues with table that it is not working at all

i guess your problem is the css usage issue.  Could you provide the sample code to me to check it?

**Comment by asiFeng** [comment]
I got the problem too. When the width fits the screen and it shows. So I set the width of table to 99%!important;  But now the height shows the same peoblems, I don't know how to handle that.

**Comment by iamkun** [comment]
can re-produce.

**Comment by mobizerg** [comment]
I got the same issue... Setting style="width: 99.9% !important;" on <el-table> solves the issue for now.

**Comment by jonnzer** [comment]
> I got the same issue... Setting style="width: 99.9% !important;" on el-table solves the issue for now.

thanks~

**Comment by zeroandnothing** [comment]
.el-table {width: 99.9% !important;}
在缩放窗口还是会达到临界值，依旧无限抖动

**Comment by MrZhongFF** [comment]
和这个问题类似：https://github.com/ElemeFE/element/issues/2716
