### ISSUE TITLE
[Bug Report] 将“tabs”放到“popover”中bar渲染不正确

### ISSUE THREAD

**Issue by yakcodo** [ElemeFE/element#16478]
### Element UI version
2.10.1

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mamying/pen/bPQyra

### Steps to reproduce
将`tabs`放入在`popover`中渲染

### What is Expected?
点击按钮，popover中的`tabs`渲染出来并且高亮的bar 有宽度

### What is actually happening?
点击按钮，popover中的`tabs`渲染并不正确，bar没有宽度

**Comment by luckyCao** [comment]
@mamying  先按照下面这样解决这个问题吧
https://codepen.io/luckyCao/pen/EqXrWL
