### ISSUE TITLE
[Bug Report] NavMenu uses popper-append-to-body scintillation

### ISSUE THREAD

**Issue by topoadmin** [ElemeFE/element#16477]
### Element UI version
2.10.1

### OS/Browsers version
Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/topoadmin/pen/RzqEGO

### Steps to reproduce
el-submenu 浮动到右侧并添加 popper-append-to-body（如果不添加 popper-append-to-body 的话子菜单会出现在页面外面）

### What is Expected?
菜单交互时能正确的打开各个菜单

### What is actually happening?
展开子菜单一没问题，展开第二个的时候就出现闪烁

**Comment by iamkun** [comment]
pr merged
