### ISSUE TITLE
[Feature Request] requires a global approach that opens a new dialog component

### ISSUE THREAD

**Issue by sdwdjzhy** [ElemeFE/element#16479]
### Existing Component
是

### Component Name
Dialog

### Description
我需要一个全局的方法能打开一个新的dialog组件。类似于MessageBox。
例如：this.$dialog(opt)
this.$dialog({
  width:"80%" (或者800px),
  height:"80%" (或者600px),
  title:....
})
可以设置新打开的dialog的高度、宽度。
或者说，设置dialog的内容的高度、宽度

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
