### ISSUE TITLE
[Bug Report] el-input checks trigger style issues with append

### ISSUE THREAD

**Issue by JachinZou** [ElemeFE/element#16475]
### Element UI version
2.9.1

### OS/Browsers version
win7/win10   chrome-74.x正常  chrome-75.x有问题  火狐正常

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jachinzou/pen/rEmPBx

### Steps to reproduce
1.删除input默认值
2.鼠标点击触发blur校验

### What is Expected?
1.校验正常触发
2.样式正常

### What is actually happening?
1.校验正常触发
2.样式不正常

**Comment by JachinZou** [comment]
![image](https://user-images.githubusercontent.com/31199674/60863065-0c5dc280-a252-11e9-94ad-c767990011b8.png)

补充：
1.去掉el-container与el-main没有该问题
2.没有append也没有该问题，但是prepend同样也会造成这个问题
3.必须在单独给el-input设置宽度的情况下才有这个问题
4.在打开浏览器控制台进行样式调试的情况下只要修改任意一属性触发页面重排，样式即恢复正常

望各位大佬帮小弟看看，谢谢！！

**Comment by luckyCao** [comment]
i can't reproduce, pr welcome.
