### ISSUE TITLE
[Bug Report] el-table single selection cancels invalid

### ISSUE THREAD

**Issue by BurningBing** [ElemeFE/element#16476]
### Element UI version
2.10.1

### OS/Browsers version
macos / chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
查看官网示例文档，关于表格单选的介绍，单击某一行可选中行，但点击下方取消选择按钮却没有反应，尝试了2.8.x和2.9.x版本没有问题

### What is Expected?
可取消选择已选中行

### What is actually happening?
无反应

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
