### ISSUE TITLE
#1537 问题在1.0.5上重现

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/element#1648]
https://github.com/ElemeFE/element/issues/1537
![abc](https://cloud.githubusercontent.com/assets/10751521/21040518/69960674-be20-11e6-93f5-683f54d077ca.gif)

**Comment by yeahTibbers** [comment]
![image](https://cloud.githubusercontent.com/assets/10751521/21040578/d7ddaed4-be20-11e6-8ab5-d3fb2dc3b617.png)

**Comment by Leopoldthecoder** [comment]
已知 bug，下个版本修复。
