### ISSUE TITLE
[Bug Report] DatePicker issues with certain display values

### ISSUE THREAD

**Issue by Terrijoo** [ElemeFE/element#16486]
### Element UI version
2.10.1

### OS/Browsers version
Win10 / Chrome v75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Terrijoo/6boy5puf

### Steps to reproduce
Enter the field and type "20190709" and press TAB

### What is Expected?
The value being converted to "2019-07-09"

### What is actually happening?
The value gets deleted.

### Additional Information:
A lot of our customers use it as a "short" way of entering a date on a numpad (german format, and there's no "." on the numpad - so like "09072019" is easier to enter than "09.07.2019")
This seems to have broken on around 2.9.x, since it was still working in 2.8.2.
Working example of 2.8.2:
https://jsfiddle.net/Terrijoo/6boy5puf/2/

This can also be reproduced on the document sites:
https://element.eleme.io/2.8/#/en-US/component/date-picker -- works
https://element.eleme.io/2.9/#/en-US/component/date-picker -- doesn't work

Or am I overseeing a config that enables it again?

**Comment by luckyCao** [comment]
#16713 一样的问题
