### ISSUE TITLE
[Bug Report] Calendar locale

### ISSUE THREAD

**Issue by debnath4u** [ElemeFE/element#16485]
### Element UI version
2.10.1

### OS/Browsers version
Mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
Please open your calendar (https://element.eleme.io/#/en-US/component/calendar) from USA any browser, you will see previous month and next month is not working. Previous month is going to May from July

### What is Expected?
If I am clicking Previous month from India it’s working fine, but it’s not working when it’s from USA. It should be same.

### What is actually happening?
Strange issue, previous and next month is not working from USA country, from India it’s fine. And also day of week is not showing English, though I m using English as default language.

**Comment by gmcinalli** [comment]
Me too.

**Comment by bbbford** [comment]
Same here... previous month/next month do not work and weekdays are displayed in Chinese.

**Comment by ubitoffee** [comment]
I have same issue too.
I set i18n locale but weekdays are displayed in Chinese always in version ^2.10.

It works well in 2.8.

**Comment by roonie007** [comment]
+1

**Comment by KwonHyuck** [comment]
+1

**Comment by yyl1208** [comment]
+1
