### ISSUE TITLE
[Feature Request] Ability to hide submenu on click away when menu-trigger is "click"

### ISSUE THREAD

**Issue by japhfortin** [ElemeFE/element#16491]
### Existing Component
Yes

### Component Name
NavMenu 

### Description
Whenever we set menu-trigger to "click", I think it would be good if we can have an option to hide the submenu on click away. Rather than forcing the user to click the same menu item just to hide the submenu.

Reproduction Link: https://codepen.io/japhfortin/pen/wLRRvb?&editable=true

**Comment by iamkun** [comment]
pr welcomed
