### ISSUE TITLE
The key value of the [Bug Report] select drop-down box is not item. value causes the drop-down box to click again and all the options turn blue

### ISSUE THREAD

**Issue by LiuXiaoLong-v** [ElemeFE/element#16494]
### Element UI version
2.10.1

### OS/Browsers version
window/google浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/liuxiaolong-v/pen/vqvMaM?editors=1111

### Steps to reproduce
1.利用elememt实例搭建下拉框
2.将数组里的value改成value2,:key="item.value"改成:key="item.value2"， :value="item.value" 改成  :value="item"
3.发现点击下拉框发现会全部变蓝

### What is Expected?
下拉框正常显示，点击后文字会变

### What is actually happening?
点击下拉框文字没有改变，全部变蓝，change事假传值是对的

**Comment by luckyCao** [comment]
https://codepen.io/luckyCao/pen/OKmorJ?editors=1111
@LiuXiaoLong-v 这样使用呢
