### ISSUE TITLE
$prompt使用Promise的写法处理回调时，then里如果有执行错误会被吞掉，看不到错误信息

### ISSUE THREAD

**Issue by tobyforever** [ElemeFE/element#1649]
$prompt使用Promise的写法处理回调时，then里如果有执行错误（比如变量undefined之类的）会被吞掉，表现为执行终止但看不到任何报错信息。（改为callback就可以看到报错）

**Comment by Leopoldthecoder** [comment]
试了一下没问题：http://jsfiddle.net/leopoldthecuber/sfr4cdyw/ ，错误会被 `catch` 捕捉到。如果有问题的话，请提供在线 demo。
