### ISSUE TITLE
[Bug Report] InfiniteScroll cant work

### ISSUE THREAD

**Issue by AyerCai** [ElemeFE/element#16507]
### Element UI version
2.10.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/mZvBry

### Steps to reproduce
事实上我使用官方文档中在线运行InfiniteScroll中的codepen样例就无法使用
[Vue warn]: Error in directive infinite-scroll inserted hook: "TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'."

(found in <Root>)
和我在项目中使用错误相同，
按需引用时
import{InfiniteScroll}form'element-ui'
Vue.use(InfiniteScroll)是否足够？

### What is Expected?
可以使用

### What is actually happening?
可以使用

**Comment by AyerCai** [comment]
I found this sample:https://codepen.io/island205/pen/xojvGG?&editable=true
add these styles InfiniteScroll can work in my chrome and IE11,But in IE10 there are some errors:
 “MutationObserver”未定义"

**Comment by LwcReber** [comment]
这个问题，我目前是先 import ele from 'element-ui';  const {InfiniteScroll}  = ele; 这种暴力方式，不知道官方的模块化出现了什么问题

**Comment by dongyanghe** [comment]
安装`mutationobserver-shim`
在对应代码模块代码导入`import 'mutationobserver-shim'`
如果你方便修改element的源代码，则可以在`transfer-panel.vue`文件导入

**Comment by iamkun** [comment]
fixed in 2.11.1

**Comment by luoq366** [comment]
我使用2.13.0，按需引入InfiniteScroll：
import{InfiniteScroll}form'element-ui'
Vue.use(InfiniteScroll)

还是和提问者报相同的错

**Comment by edum18** [comment]
fixed it by adding overflow-y: auto to the element with v-infinite-scroll
