### ISSUE TITLE
带筛选的table，无法触发filter-method？

### ISSUE THREAD

**Issue by Delicate-lee** [ElemeFE/element#1650]
1. jsfiddle里可以出发filter-method，如图
![element-3](https://cloud.githubusercontent.com/assets/18555584/21041176/49da3572-be24-11e6-9375-a5105c1c01ff.jpg)

2.这是本地项目，结果如图
![element-2](https://cloud.githubusercontent.com/assets/18555584/21041190/6b9e5ba2-be24-11e6-83d7-2d0bded45567.jpg)
样式不同，没有筛选 重置按钮，也没法触发filter-method
部分包版本如下
 "element-ui": "^1.0.2", 
"vue-loader": "^9.9.5", 
"vue": "^2.0.6",
 "webpack": "^1.13.3", 
请问是否有限制的包版本，谢谢帮助！
@Leopoldthecoder @furybean

**Comment by Leopoldthecoder** [comment]
整理一个 repo 吧，无法重现的话我们也没办法定位问题。

**Comment by yuzhiquan** [comment]
![image](https://cloud.githubusercontent.com/assets/5193791/21173668/cd3f7664-c213-11e6-9955-1d48b3c2737f.png)
是不是column中没有带prop项，如图
