### ISSUE TITLE
[Bug Report] Cascader Cascader Selector Options Data Source Children displays an exception when there is an item of the same name (label is the same, value is different)

### ISSUE THREAD

**Issue by alwaysBe** [ElemeFE/element#16500]
### Element UI version
2.10.1

### OS/Browsers version
windows10 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/alwaysbe/pen/EBrapQ

### Steps to reproduce
选中[四川/成都市/市辖区]，后表单拿到数据无误，但是选择框中回显的实际为[山东省 / 济南市 / 市辖区]

### What is Expected?
选中[四川/成都市/市辖区]，后表单拿到数据为[四川/成都市/市辖区]，并且选择框回显为[四川/成都市/市辖区]

### What is actually happening?
择框中回显的为[山东省 / 济南市 / 市辖区]

**Comment by a631807682** [comment]
> `<el-cascader v-model="form.regions" placeholder="试试搜索：地址" :options="regions" filterable :props="{value:'label',expandTrigger: 'hover'}"></el-cascader>`

`props.value`值必须唯一

**Comment by alwaysBe** [comment]
in fact,the selected value [Sichuan/Chengdu/Municipal District] and [Shandong Province/Jinan City/Municipal District],only the third part "Municipal District" is the same

**Comment by a631807682** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/cascader-panel/src/store.js#L55

`cascader` match last leve node only,  and i don‘t think is necessary to handle `props.value` to be same .

**Comment by alwaysBe** [comment]
there may some case use `cascader` to select cities, and the city list may have many Municipal District, in fact its belong to different province, and we need to select the province city detail, so the problems out

**Comment by a631807682** [comment]
It's may be a feat which has some way to get the node data, not only `value`, and not to handle same `value`.
So you should create a new issues about this feature.

**Comment by gao1996916** [comment]
你好，这个问题我最近也遇到过了，现在有解决这个问题吗。

**Comment by SimonaliaChen** [comment]
Fixed in #15935
