### ISSUE TITLE
[Feature Request] Required attribute on el-select

### ISSUE THREAD

**Issue by chou666** [ElemeFE/element#16519]
### Existing Component
Yes

### Component Name
el-select

### Description
On a form, I want to have the HTML5 required attribute on el-select attribute to force user to select a value.

                <el-select
                    v-model="form.typeContact"
                    :required="true"
                    class="w-100"
                >
                    <el-option
                        value=""
                        data-l10n-id="contact-type_placeholder"
                    ></el-option>
                    <el-option
                        value="Entreprise"
                        data-l10n-id="contact-type_company"
                    ></el-option>
                </el-select>

**Comment by iamkun** [comment]
pr welcomed
