### ISSUE TITLE
[Feature Request] Ability to toggle AM/PM in the time picker

### ISSUE THREAD

**Issue by mattheyan** [ElemeFE/element#16524]
### Existing Component
Yes

### Component Name
TimePicker

### Description
We're working on incorporating element UI into our existing product. The product's current behavior, which we would like to keep, allows users to toggle a time field between AM and PM. The element time picker doesn't currently support this. Is this something you would consider adding? We would also be able to implement and submit a PR if the team's time is limited and you would be open to accepting a PR.

Thanks,
Bryan

**Comment by iamkun** [comment]
pr welcomed
