### ISSUE TITLE
[Bug Report] InputNumber

### ISSUE THREAD

**Issue by luocong2016** [ElemeFE/element#16526]
### Element UI version
2.10.1

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
源码： this.$emit('input', value)
在封装组件中 @input 被多次触发

### What is Expected?
只希望在 值被改变 或   或 -  这3种情况下被触发，而不是一直触发

### What is actually happening?
this.$emit('input', value) 触发了多次 @input

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
