### ISSUE TITLE
[Bug Report] cascader show error when the value of options is 1

### ISSUE THREAD

**Issue by blanklin030** [ElemeFE/element#16523]
### Element UI version
2.10.1

### OS/Browsers version
chrome 版本 75.0.3770.100（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/blanklin/pen/LKayea

### Steps to reproduce
1、here is the example of error case
options: [{
        value: '1',
        label: '指南',
        children: [{
          value: '1',
          label: '一致'
        }, {
          value: 'fankui',
          label: '反馈'
        }]
      }]
2、if set the  same value，the display box is empty

### What is Expected?
可以设置同样的value，展示框不会为空

### What is actually happening?
设置同样的value后展示框为空

**Comment by luckyCao** [comment]
can not reproduce
