### ISSUE TITLE
[Feature Request] Cascader Unexpected

### ISSUE THREAD

**Issue by liujian891010** [ElemeFE/element#16521]
### Existing Component
是

### Component Name
cascader

### Description
cascader 怎么莫名出现了圆形选择框？我需要原来的版本？如何更改？最新的release也没看见哇~~~~~

**Comment by ivila** [comment]
当你选择change-on-select或者是props.check-strictly的时候才会出那个小圆圈，主要用来区别到底此次点击是为了选择还是展开用的

**Comment by zhou512772511** [comment]
@ivila 请问下怎么修改呢

**Comment by ivila** [comment]
> @ivila 请问下怎么修改呢

你要改什么。。。如果是去掉小圆点的话，原因不都已经知道了么

**Comment by ivila** [comment]
@zhou512772511 你要改什么，如果是去掉小圆点的话，原因不都已经知道了么

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
