### ISSUE TITLE
When [Bug Report] el-table is used in conjunction with keep-alive, when the component is reactivated, the column height using fixed is 17 PX less.

### ISSUE THREAD

**Issue by HuangZhaoPing** [ElemeFE/element#16525]
### Element UI version
2.10.1

### OS/Browsers version
win10 / chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/ZdPxEM

### Steps to reproduce
抱歉用中文，怕用英文描述不清楚

重现步骤：

1、el-table与keep-alive配合使用

2、设置列的fixed为left或者right

3、表格不能出现横向滚动条

4、点击switch两次，重新激活组件

5、fixed列的高度少了17px（滚动条的原因？）

### What is Expected?
高度正确

### What is actually happening?
高度少了17px

**Comment by a1mersnow** [comment]
You can patch the `element-ui.common.js` in `node_modules/element-ui/lib` like this:

From:
```
doLayout: function doLayout() {
  if (this.shouldUpdateHeight) {
    this.layout.updateElsHeight();
  }
  this.layout.updateColumnsWidth();
},
```

To:
```
doLayout: function doLayout() {
  this.layout.updateColumnsWidth();
  if (this.shouldUpdateHeight) {
    this.layout.updateElsHeight();
  }
},
```

Don't know how reliable this method is. I just tested some cases and found it works.
