### ISSUE TITLE
[Bug Report] from async-validator echo inactivation

### ISSUE THREAD

**Issue by webvs2** [ElemeFE/element#16527]
### Element UI version
2.10.1

### OS/Browsers version
 74.0.3729.131

### Vue version
2.6.10

### Reproduction Link
https://github.com/webvs2/resurgence

### Steps to reproduce
动态生成select ，在select对象里面push（{value:'',data:[] }），  验证只要生成的select的vaule一定有值.第一次生成验证正常，第二次失败

### What is Expected?
生成的select的数组对象中的value有值验证，没有则显示错误信息，标志红色

### What is actually happening?
第一次生成select的时候可以验证， 在第二次的时候开始页面错误失活，但是async-validator可以捕捉到错误.

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
