### ISSUE TITLE
[Bug Report] is-success style lose????

### ISSUE THREAD

**Issue by webvs2** [ElemeFE/element#16534]
### Element UI version
2.10.1

### OS/Browsers version
 74.0.3729.131（正式版本） （32 位）

### Vue version
2.6.10

### Reproduction Link
https://github.com/webvs2/resurgence

### Steps to reproduce
from 表单验证后is-success下的el-input__inner丢失？？？没有状态颜色，当前使用2.10版本，在2.6版本里面有，我搜索element/packages/theme-chalk/src/upload.scss没有，我自己加上，不知道是不是丢了，往告知，领导及其残忍，追问不休

### What is Expected?
from 表单验证成功后会有绿色状态告知用户

### What is actually happening?
灰色，用户感知成了无反应

**Comment by JeremyWuuuuu** [comment]
Unless you can provide a fiddle to reproduce this issue, we can not help you.
除非能给出一个可以复现这个问题的样例, 否则我们没有办法给到你帮助

**Comment by webvs2** [comment]
https://github.com/webvs2/element
这里面有两个单文件供你观看，在from输入正确以后的状态改变，您可以下载在本地打开.

**Comment by webvs2** [comment]
https://github.com/webvs2/element
这里面有两个单文件供你观看，在从输入正确以后的状态改变，您可以下载在本地打开。
Here are two single files for you to watch, after the state changes from the correct input, you can download locally open.

**Comment by ivila** [comment]
@webvs2 请注意看2.10.0的更新日志中的非兼容更新部分。解决方案参考https://github.com/ElemeFE/element/pull/16159

**Comment by webvs2** [comment]
好的，十分感谢
