### ISSUE TITLE
[Bug Report] el-date-picker pop-up box location calculation error

### ISSUE THREAD

**Issue by myh6666** [ElemeFE/element#16538]
### Element UI version
0.1.0

### OS/Browsers version
Mac

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/ne9ktapq/1/

### Steps to reproduce
1、切换组件v-if表达式的值
2、点击组件
(type="datetimerange" 时会出现bug)

### What is Expected?
下拉框在正确的位置

### What is actually happening?
下拉框在左上角(left: 0; top: 0)

**Comment by luckyCao** [comment]
```
<div v-if="show" key="0">
      <el-date-picker v-model="time" type="datetimerange" />
</div>
<div v-else key="1">
<el-date-picker v-model="time" type="datetime" />
</div>
```

@myh6666 这样修改，你的例子中因为 `diff` 算法，vue 只会更新 `el-date-picker`，导致了出现问题
