### ISSUE TITLE
主题编辑报错

### ISSUE THREAD

**Issue by yejinjian** [ElemeFE/element#1653]
使用 et 创建主题时出现报错

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/data/app/tt/node_modules/element-theme-default/src/vue-popup/lib/popup.css'
    at Error (native)

**Comment by lanbaba** [comment]
可以试试在node_modules/element-theme-default/src/下新建目录vue-popup/lib/，然后将node_modules/.0.2.12\@vue-popup/lib/popup.css拷贝到新建目录下。

**Comment by Leopoldthecoder** [comment]
请参考楼上给出的方法。或者升级至1.0.6。
