### ISSUE TITLE
[Bug Report] Tabs component cannot locate the current label

### ISSUE THREAD

**Issue by Zypom** [ElemeFE/element#16532]
### Element UI version
2.10.1

### OS/Browsers version
MacOS High Sierra10.13.4/谷歌浏览器 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zypom/pen/QXPWoZ?&editable=true

### Steps to reproduce
当label过多被折叠时，并且tab-position值为left，点击最后一个标签，当前label定位被跳转，

### What is Expected?
不发生跳转

### What is actually happening?
发生跳转

**Comment by SnuggleE** [comment]
i meet the problem，too
