### ISSUE TITLE
[Bug Report] el-select 数据返回之前点击，不关闭下拉框，返回后显示出错

### ISSUE THREAD

**Issue by chun1hao** [ElemeFE/element#16535]
### Element UI version
2.10.1

### OS/Browsers version
windows/chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/bPZXXb

### Steps to reproduce
在数据返回之前点击el-elect 不关闭下拉框

### What is Expected?
数据返回后select 应显示给的value对应的label值

### What is actually happening?
显示value的值

**Comment by iamkun** [comment]
just set value in the next event loop

setTimeout(()=>{
        this.list = this.states.map((item,i) => {
          return { value: i, label: item };
        });
        this.$nextTick(() => {
          this.value = 2
        })
      }, 2000)
