### ISSUE TITLE
[Bug Report] Tree table about default-expand-all unable to bind bidirectionally?

### ISSUE THREAD

**Issue by yimogit** [ElemeFE/element#16545]
### Element UI version
2.10.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/EBJvOW

### Steps to reproduce
update default-expand-all invalid

### What is Expected?
According to the button Fold up and fold up

### What is actually happening?
Nothing was done.

**Comment by iamkun** [comment]
default-expand-all  only works in the first render. please read the doc for another apis
