### ISSUE TITLE
渲染表格时，并不知道所有的prop是什么，有办法动态生成吗？

### ISSUE THREAD

**Issue by ieiayaobb** [ElemeFE/element#1654]
比如我现在想渲染一个mongo的表，因为是schema less的，所以我并不知道会有哪些prop，我想在渲染时能把所有的prop都渲染出来，应该如何做呢？

举个例子：
user表数据是这样的
```
[{
  "id": 1
  "email": "test1@abc.com"
},
{
  "id": 2
  "name": "test2
}]
```
我希望渲染的表格是这样的

| id | email                 | name |
| -- | --------------- | -----  |
|  1  |test1@abc.com |           |
|  2  |                           | test2 |

**Comment by furybean** [comment]
el-table-column v-for="expr" 应该就可以了。

**Comment by ieiayaobb** [comment]
@furybean 好的，非常感谢，我去试一下

**Comment by ieiayaobb** [comment]
@furybean 似乎并不能解决我的问题。貌似还是需要我在后台把表头全部遍历计算生成后才能在前台正确的生成，有办法在你们渲染数据的时候动态生成表头吗？

**Comment by furybean** [comment]
@ieiayaobb 无论什么时机遍历，总是需要知道表头是什么，拿到了表头数组去 v-for 就可以了。
如果你说的不可以指的是这个数据需要在 Ajax 之后才知道，你可以先给这个变量赋值一个 `[]`，在 Ajax 结束时再设置成正确的值。

**Comment by SASUKE40** [comment]
@ieiayaobb 

你可以在template中加上这个
```html
<el-table-column v-for="c in columns" :prop="c" :label="c"></el-table-column>
```

并在获取数据的时候拿第一条数据作为表头属性
```javascript
let firstRow = data.result[0]
this.columns = Object.keys(firstRow)
this.tableData = data.result
```

**Comment by xchz** [comment]
`<el-table-column v-for="currentThead of currentTheadData" :prop='currentThead.prop' :label='currentThead.label' :formatter="currentThead.formatter" width="180">
      </el-table-column>`
动态生成el-table-column，这样如果需要对某个column进行formatter（数据转为button或者icon等，formatter不支持支持插入html），如何才能实现呢？eleme文档写的是Scoped slot方式，但是这种方式好像不太好配合v-for？，请教大家应该如何解决?

**Comment by xchz** [comment]
@QingWei-Li
