### ISSUE TITLE
[Bug Report] After the table is'fixed', the lines will be misaligned when scrolling

### ISSUE THREAD

**Issue by Zhumingtao** [ElemeFE/element#16546]
### Element UI version
2.10.1

### OS/Browsers version
win8

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhumingtao/pen/orOKyw?editors=1111

### Steps to reproduce
拖动表格横线滚动条时

### What is Expected?
表头文字不抖动以及边框不错位

### What is actually happening?
表头文字会抖动以及边框会错位。合计行也一样

**Comment by luckyCao** [comment]
can not reproduce

**Comment by bluegek** [comment]
I also hava the question.
fixed right a column and make the horizontal scroll bar to right.
and then table header and body seam to be wrong.
![image](https://user-images.githubusercontent.com/12539628/62349405-401ac800-b532-11e9-9cec-2e90c0717a55.png)

**Comment by bluegek** [comment]
> I also hava the question.
> fixed right a column and make the horizontal scroll bar to right.
> and then table header and body seam to be wrong.
> ![image](https://user-images.githubusercontent.com/12539628/62349405-401ac800-b532-11e9-9cec-2e90c0717a55.png)

element UI Version 2.10.1 and Version 2.11.1 both hava the question
