### ISSUE TITLE
[Bug Report] Vue cli3 require JS error reporting

### ISSUE THREAD

**Issue by ChinaMars** [ElemeFE/element#16555]
### Element UI version
2.10.1

### OS/Browsers version
macOS 10.13.6 / chrome

### Vue version
2.6.10

### Reproduction Link
![image](https://user-images.githubusercontent.com/29267545/61195128-c3e25100-a6f8-11e9-9407-60b150f499da.png)
![image](https://user-images.githubusercontent.com/29267545/61195147-eaa08780-a6f8-11e9-8937-dcf1763e2ed8.png)

### Steps to reproduce
我打包生成js
![image](https://user-images.githubusercontent.com/29267545/61195162-fc822a80-a6f8-11e9-9e00-ffacfba9d72f.png)

### What is Expected?
没有Cannot read property 'install' of undefined报错

### What is actually happening?
有js报错Cannot read property 'install' of undefined

**Comment by JeremyWuuuuu** [comment]
Unless you can provide a fiddle to reproduce this issue, we can not help you.
除非能给出一个可以复现这个问题的样例, 否则我们没有办法给到你帮助

**Comment by JeremyWuuuuu** [comment]
请确认自己引入 `Element-UI` 的方式是否是 **AMD** 方式, 如果不是请尝试引入采用 **UMD** 方式打包的 `Element-UI`. 这里提供一个关于 [CommonJS/RequireJS/ES Module/UMD](https://www.kancloud.cn/chandler/web_technology/387254) 的链接

**Comment by ChinaMars** [comment]
转成UMD也不行还是报错
![image](https://user-images.githubusercontent.com/29267545/61219401-b8b61200-a746-11e9-8f44-b55385fb598c.png)

![image](https://user-images.githubusercontent.com/29267545/61219333-945a3580-a746-11e9-8f71-bbcb81778b3c.png)
这里为什么会报错：Uncaught TypeError: Cannot read property 'install' of undefined

**Comment by ChinaMars** [comment]
解决了就是这个v大小写造成的。。。。。
