### ISSUE TITLE
[Bug Report] el-select with multiple and filterable property can not be closed by clicking the input area

### ISSUE THREAD

**Issue by Annushkash** [ElemeFE/element#16559]
### Element UI version
2.10.1

### OS/Browsers version
75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/AnnushkaSh/pen/aggoPE

### Steps to reproduce
click on select component and then click on the input area

### What is Expected?
el-select-dropdown component will be closed

### What is actually happening?
el-select-dropdown component is not closing

It's dublicate #12305, and fixed in #12210, but be reproduced again in current version.

**Comment by tangguodada** [comment]
I also have this problem.Is there a solution now?
