### ISSUE TITLE
[Bug Report] Over 2.6.3 version of table component row-style (line style callback method) does not work

### ISSUE THREAD

**Issue by Tangchunhai** [ElemeFE/element#16551]
### Element UI version
2.10.1

### OS/Browsers version
win10/chorme

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/tangchunhai/pen/QXRYVy

### Steps to reproduce
:row-style="showTr"绑定了showTr函数，并且返回了样式，不生效。

### What is Expected?
返回样式生效。

### What is actually happening?
返回样式不生效

**Comment by iamkun** [comment]
Row-style should an object
