### ISSUE TITLE
[Bug Report] Table Selection not working while using custom table header

### ISSUE THREAD

**Issue by imlyrrad** [ElemeFE/element#16557]
### Element UI version
2.10.0

### OS/Browsers version
Chromium 72.0.3626.121

### Vue version
2.5.11

### Reproduction Link
https://codepen.io/anon/pen/gNJNEL

### Steps to reproduce
1. Click Table Selection

### What is Expected?
All Check box should be check

### What is actually happening?
Checkboxes freeze

**Comment by a631807682** [comment]
https://codepen.io/anon/pen/gNJNEL?editors=1010#0

```
    :data="tableData.filter(data => !search || data.name.toLowerCase().includes(search.toLowerCase()))"
```
`tableData.filter` return a new `Array` that can't observe in `vue`.
