### ISSUE TITLE
表单验证model绑定的是一个对象下的某个子对象属性的时候无法验证

### ISSUE THREAD

**Issue by cench** [ElemeFE/element#1655]
> **问题描述：表单绑定的model为对象下子对象属性时验证失败。**

:rules=“f2Rules.kh”

表单绑定的数据v-model为  s2form.kh.name

表单验证属性：prop="name"

数据如下：

`                s2form: {
                    kh: { name:'', tel: '', phone:'', email:'' }
                }
`
规则如下：
`                f2Rules: {
                    kh:{
                        name: [{required: true, message: '必须输入姓名', trigger: 'blur'}]
                    }
                }`

> **只要数据格式为对象下子对象属性的就始终验证失败，尝试过自定义验证同样获取不到输入框value值，目前求解决方案?**

**Comment by baiyaaaaa** [comment]
可以将你的form-item prop属性设置为 'kh.name'

**Comment by xiaoxiath** [comment]
看了下代码，这行有bug：https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L176

只能在el-form-item加对应的rule了
`<el-form-item  :rules="f2Rules.kh.name" prop="s2form.kh.name">`

**Comment by geraldlrh** [comment]
这么通用的问题，官方不解决？？

**Comment by Leopoldthecoder** [comment]
不是可以正常工作吗：https://jsfiddle.net/leopoldthecuber/nrvhb1nc/

**Comment by 52admln** [comment]
It works!

**Comment by Lqshiluo** [comment]
楼上的是怎么解决这个问题的？求告知

**Comment by 52admln** [comment]
@Lqshiluo 见 @baiyaaaaa 的回复。

**Comment by Leotw** [comment]
如果data中定义的数据结构是这样的(组件上最终绑定的是dataForm.name.value)：
`
dataForm:  {
name:  {
       value: ''
    }
}
`
那么rules中需要这样写：
`
rules:  {
  'name.value': {
     { required: true, message: '请输入项目名称', trigger: 'blur' }
  } 
}
`

template需要这么写：
`<el-form-item prop="name.value">`
`<el-input v-model="dataForm.name.value"></el-input>`
`</el-form-item>`

**Comment by hamburgduo** [comment]
@Leotw正解
