### ISSUE TITLE
[Bug Report] select

### ISSUE THREAD

**Issue by yangge0120** [ElemeFE/element#16560]
### Element UI version
2.10.1

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1,在输入框中输入ala,点击箭头下正常选中无问题,
2,删除ala中的最后一个a,点击箭头下正常选中无问题,
3, 当只剩下一个a的时候,点击箭头下,会出现跳跃选中的问题

### What is Expected?
期待输入之后再进行删除之后,点击箭头下键可以正常一个一个的选中,而不是一个跳一个的选中

### What is actually happening?
实际也希望能够正常选择

**Comment by victorting** [comment]
demo链接地址无法正常访问

**Comment by yangge0120** [comment]
打开element官网选择组件select,选择远程搜索select控件在线运行,上述问题就可以复现,请尽快修改

**Comment by ibufu** [comment]
没有复现链接，不能复现

**Comment by victorting** [comment]
> 没有复现链接，不能复现

https://codepen.io/anon/pen/mNdpQe?&editable=true

**Comment by yangge0120** [comment]
https://element.eleme.cn/#/zh-CN/component/select  找到远程搜索即可复现问题

**Comment by ibufu** [comment]
@victorting @yangge0120 还是不能复现，能截一个 gif 吗？

**Comment by yangge0120** [comment]
![bug](https://user-images.githubusercontent.com/31205807/61619920-60c95f00-aca2-11e9-9cfd-574da81c9b21.gif)

**Comment by yangge0120** [comment]
@element-bot

**Comment by yangge0120** [comment]
@element-bot 不给回复了??? 这问题不解决么?

**Comment by victorting** [comment]
> @element-bot 不给回复了??? 这问题不解决么?
这个问题我发现在在el-option v-for遍历的时候去掉key就正常了，这个可能和vue的列表渲染机制有关
https://codepen.io/anon/pen/ymPXpP?editors=1010

**Comment by yangge0120** [comment]
恩,可能跟vue机制有关了  了解了
