### ISSUE TITLE
[Bug Report] Apple Mobile does not pop up the keyboard - select filterable

### ISSUE THREAD

**Issue by sunxyz** [ElemeFE/element#16569]
### Element UI version
2.3.6

### OS/Browsers version
苹果手机微信浏览器

### Vue version
2.5.2

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
点击下拉远程搜索时不弹出键盘

### What is Expected?
点击下拉远程搜索时弹出键盘

### What is actually happening?
点击下拉远程搜索时不弹出键盘

**Comment by iamkun** [comment]
Element is designed for desktop. It's not compatible with mobile devices. FYI: https://github.com/vuejs/awesome-vue#mobile-1
