### ISSUE TITLE
[Feature Request] Form validation error information can be displayed in Tooltip mode

### ISSUE THREAD

**Issue by jiebaiyachi** [ElemeFE/element#16565]
### Existing Component
是

### Component Name
Form 表单

### Description
我们想把页面元素间距改为10px的但是这样会使表单验证错误信息被下方控件遮挡住，并且表单验证错误信息过长也会出现被下方元素遮挡的情况，建议表单验证错误信息可以用Tooltip方式显示。

**Comment by webvs2** [comment]
类似于Tooltip 这样的吗，Form-Item里面有slot errer可以做自定义错误提示，希望有帮助
