### ISSUE TITLE
[Bug Report] Defines the header, and the second assignment header calculates incorrectly

### ISSUE THREAD

**Issue by ALongLi** [ElemeFE/element#16561]
### Element UI version
2.10.1

### OS/Browsers version
win7 /chrome71

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/fillter/pen/JQQdeL

### Steps to reproduce
点击按钮重新赋值表头
多级表头显示错误

### What is Expected?
多级表头表头显示正常

### What is actually happening?
表头合并单元格错误

**Comment by ziyoung** [comment]
不是 bug。el-table-column 的 key 不要设置为 index，设置为 item.prop 一切正常。
