### ISSUE TITLE
[Bug Report] use cascader, if the values selected for the secondary cascade correspond to all the tertiary cascade values, the first secondary cascade value is echoed by default

### ISSUE THREAD

**Issue by quepq** [ElemeFE/element#16564]
### Element UI version
2.10.1

### OS/Browsers version
Google Chrome 版本 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element.git

### Steps to reproduce
cascader 中，不管几个二级级联选择的值对应的三级级联，三级级联值都一样，默认回显二级级联第一个值，而不是选中的二级级联的值。列如:options: [{
value: 'zhinan',
label: '指南',
children: [{
value: 'shejiyuanze',
label: '设计原则',
children: [{
value: 'yizhi',
label: '一致'
}]
}, {
value: 'daohang',
label: '导航',
children: [{
value: 'yizhi',
label: '一致'
}]
}]
}, {
value: 'zujian',
label: '组件',
children: [{
value: 'basic',
label: 'Basic',
children: [{
value: 'layout',
label: 'Layout 布局'
}, {
value: 'color',
label: 'Color 色彩'
}, {
value: 'typography',
label: 'Typography 字体'
}, {
value: 'icon',
label: 'Icon 图标'
}, {
value: 'button',
label: 'Button 按钮'
}]
}, {
value: 'form',
label: 'Form',
children: [{
value: 'radio',
label: 'Radio 单选框'
}, {
value: 'checkbox',
label: 'Checkbox 多选框'
}, {
value: 'input',
label: 'Input 输入框'
}, {
value: 'input-number',
label: 'InputNumber 计数器'
}, {
value: 'select',
label: 'Select 选择器'
}, {
value: 'cascader',
label: 'Cascader 级联选择器'
}, {
value: 'switch',
label: 'Switch 开关'
}, {
value: 'slider',
label: 'Slider 滑块'
}, {
value: 'time-picker',
label: 'TimePicker 时间选择器'
}, {
value: 'date-picker',
label: 'DatePicker 日期选择器'
}, {
value: 'datetime-picker',
label: 'DateTimePicker 日期时间选择器'
}, {
value: 'upload',
label: 'Upload 上传'
}, {
value: 'rate',
label: 'Rate 评分'
}, {
value: 'form',
label: 'Form 表单'
}]
}, {
value: 'data',
label: 'Data',
children: [{
value: 'table',
label: 'Table 表格'
}, {
value: 'tag',
label: 'Tag 标签'
}, {
value: 'progress',
label: 'Progress 进度条'
}, {
value: 'tree',
label: 'Tree 树形控件'
}, {
value: 'pagination',
label: 'Pagination 分页'
}, {
value: 'badge',
label: 'Badge 标记'
}]
}, {
value: 'notice',
label: 'Notice',
children: [{
value: 'alert',
label: 'Alert 警告'
}, {
value: 'loading',
label: 'Loading 加载'
}, {
value: 'message',
label: 'Message 消息提示'
}, {
value: 'message-box',
label: 'MessageBox 弹框'
}, {
value: 'notification',
label: 'Notification 通知'
}]
}, {
value: 'navigation',
label: 'Navigation',
children: [{
value: 'menu',
label: 'NavMenu 导航菜单'
}, {
value: 'tabs',
label: 'Tabs 标签页'
}, {
value: 'breadcrumb',
label: 'Breadcrumb 面包屑'
}, {
value: 'dropdown',
label: 'Dropdown 下拉菜单'
}, {
value: 'steps',
label: 'Steps 步骤条'
}]
}, {
value: 'others',
label: 'Others',
children: [{
value: 'dialog',
label: 'Dialog 对话框'
}, {
value: 'tooltip',
label: 'Tooltip 文字提示'
}, {
value: 'popover',
label: 'Popover 弹出框'
}, {
value: 'card',
label: 'Card 卡片'
}, {
value: 'carousel',
label: 'Carousel 走马灯'
}, {
value: 'collapse',
label: 'Collapse 折叠面板'
}]
}]
}, {
value: 'ziyuan',
label: '资源',
children: [{
value: 'axure',
label: 'Axure Components'
}, {
value: 'sketch',
label: 'Sketch Templates'
}, {
value: 'jiaohu',
label: '组件交互文档'
}]
}]

### What is Expected?
when i use cascader,i can use the same value in two stage and there stage ,echo normal;

### What is actually happening?
when i use cascader,i can use the same value in two stage and there stage ,echo normal;

**Comment by LeeeMooo** [comment]
同样遇到这个BUG,  当三级级联中有相同的value时, 不管选中哪个三级label, 二级级联都默认显示第一个label, 但value其实是正确的.
`{
    value: 'a',
    label: 'testa',
    children: [{
      value: 'b',
      label: 'testb',
      children: [{
        value: 'bb',
        label: 'testbb'
      }]
    }, {
      value: 'c',
      label: 'testc',
      children: [{
        value: 'bb',
        label: 'testcc'
      }]
    }]
  }`
**选择 testa--testc--testcc 显示的是testa--testbb--testbb  value是a--c--bb**

**Comment by egg2** [comment]
同有这个BUG

**Comment by mumuxiaozhu** [comment]
options中的对象value不能相同。因输入框展示的内容是从选择值value（**如果value是数组则取数组的最后一个数值，一般是叶子节点的value**）匹配节点后返回的节点信息中得到的。从flattedNodes（缓存了所有层级的节点）过滤出与该值相同的node，如果有多个相同值会过滤出与选中值相同的第一个存储的node，然后通过该节点的node.getText方法获取回显内容（根据node节点属性pathLabels生成回显文本），找到的节点不对生成的回显文本就错了。
`Children:[{

**Value:'yizhi',**
Label:'Consistent'

]
}, {

Value:'daohang',
Label:'Navigation',

Children:[{
**Value:'yizhi',**

Label:'Consistent'
]`


 `Store.prototype.getNodeByValue = function getNodeByValue(value) {
    if (value) {
      value = Array.isArray(value) ? value[value.length - 1] : value;
      var nodes = this.getFlattedNodes(false, !this.config.lazy).filter(function (node) {
        return node.value === value;
      });
      return nodes && nodes.length ? nodes[0] : null;
    }
    return null;
  };`
原因可参考问题 [https://github.com/ElemeFE/element/issues/16619]

**Comment by egg2** [comment]
> options中的对象值不能相同。因输入框展示的内容是从选择值（**如果值是数组则取数组的最后一个数值，一般是叶子节点的值**）匹配节点后返回的节点信息中得到的。从flattedNodes（缓存了所有层级的节点）过滤出与该值相同的节点，如果有多个相同值会过滤出与选中值相同的第一个存储的节点，然后通过该节点的node.getText方法获取回显内容（根据节点节点属性pathLabels生成回显文本），找到的节点不对生成的回显文本就错了。
> 儿童：[{
> 
> **价值：'yizhi'，**
> 标签：'一致'
> 
> ] 
> }，{
> 
> 价值：'daohang'，
> 标签：'导航'，
> 
> 孩子：[{ 
> **Value：'yizhi'，**
> 
> 标签：'Consistent' 
> ]`
> 
> `Store.prototype.getNodeByValue = function getNodeByValue(value) { if (value) { value = Array.isArray(value) ? value[value.length - 1] : value; var nodes = this.getFlattedNodes(false, !this.config.lazy).filter(function (node) { return node.value === value; }); return nodes && nodes.length ? nodes[0] : null; } return null; };`
> 原因可参考问题[https://github.com/ [/ issues / 16619](https://github.com/ElemeFE/element/issues/16619) ]

是否可以增加一个选项，可以设置从前向后查找，不考虑性能

**Comment by egg2** [comment]
value相同的场景还是很多的

**Comment by SimonaliaChen** [comment]
Fixed in #15935
