### ISSUE TITLE
bug  table 设置highlight-current-row 属性时，删除该条数据，选中状态样式没有去掉

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#1656]
table 设置highlight-current-row 属性时，删除该条数据，选中状态样式没有去掉,不过事件handleCurrentChange是触发了，并且row的值是null了，只是显示上没有清除！

或者有提供清除当前选中行的方法吗？

**Comment by furybean** [comment]
尝试设置一下 row-key，这个和 Vue2 的渲染机制有关系。

**Comment by AaronChen2012** [comment]
谢谢，设置设置了 row-key，问题没有出现了
