### ISSUE TITLE
[Bug Report] [Bug Report]: el-select placeholder internationalization switch not in effect

### ISSUE THREAD

**Issue by keepAwayFrom404** [ElemeFE/element#16578]
### Element UI version
2.10.1

### OS/Browsers version
os10.14.4/google75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/mZZgmO?editors=1010

### Steps to reproduce
1.绑定的placeholder语言切换正常；
2.选择几个选项之后，切换语言，placeholder又出来了，然后再选择，placeholder消失；
3.去除el-select上绑定的placeholder，使用默认的placeholder，切换语言无效。

### What is Expected?
1.绑定的placeholder在语言切换时不应该再次出现
2.使用默认placeholder应该能正常切换语言

### What is actually happening?
绑定的placeholder在切换语言就会出现；默认placeholder切换语言失败

**Comment by iamkun** [comment]
能再详述一下 重现步骤吗 ， 我这点了几下看起来还好

**Comment by keepAwayFrom404** [comment]
> 能再详述一下 重现步骤吗 ， 我这点了几下看起来还好
可以到Reproduction Link查看例子，把el-select绑定的placeholder去掉，会使用默认的“请选择”。这时候再切换中英文无效。

**Comment by iamkun** [comment]
please check https://element.eleme.cn/#/en-US/component/i18n to use locale properly.

**Comment by keepAwayFrom404** [comment]
> please check https://element.eleme.cn/#/en-US/component/i18n to use locale properly.

我本地是引入了国际化的 分页组件国际化也正常显示了的 就select组件没显示

**Comment by xxyuk** [comment]
https://element.eleme.io/#/en-US/component/select

looks fine on official website.

**Comment by buster84** [comment]
I guess this issue was fixed by this https://github.com/ElemeFE/element/pull/17644

**Comment by fyeeme** [comment]
Confirm that this bug is still existed on latest version (2.15.7)

**Comment by fyeeme** [comment]
version: 2.5.17
https://user-images.githubusercontent.com/6078758/149743113-3f3ff3af-a44b-4bd0-9efd-ed707b61357a.mov

**Comment by Donald-Z** [comment]
> 确认此错误在最新版本 (2.15.7) 上仍然存在

请问怎么解决的，我也遇到跟视频中是一个问题，版本2.15.1
