### ISSUE TITLE
[Feature Request] Accessing the rows of an El-Table component using $refs

### ISSUE THREAD

**Issue by mehdibenhac** [ElemeFE/element#16587]
### Existing Component
Yes

### Component Name
Table

### Description
I'm using Element-UI along with VueJS for a project, and I've recently hit a wall.

For the needs of a specific function, I need to access the individual rows of an el-table component, preferably using $refs, but for the life of me I can't figure out how to do it.

Is that possible at all?

**Comment by iamkun** [comment]
you can use $ref to get the whole table element, and use element.queryselectAll() to get the child element you want.
