### ISSUE TITLE
[Bug Report] Executes el-tree.setCurrentKey (null) when no node is selected, and errors are reported

### ISSUE THREAD

**Issue by RockyF** [ElemeFE/element#16589]
### Element UI version
2.10.1

### OS/Browsers version
electron 4.2.4

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/rockyf/pen/WqVqXr?editors=1111

### Steps to reproduce
1. 运行后，直接点按钮，控制台会报错。
2. 选中节点后，点击按钮一次正常，第二次开始点击就会报错

### What is Expected?
即使没有选中节点，setCurrentKey也不应该报错

### What is actually happening?
在没有选中节点的时候执行el-tree.setCurrentKey(null)，会报错

**Comment by xiaogaofudao** [comment]
遇到同样问题。之前的版本是没问题的

**Comment by ziyoung** [comment]
2.11.0 已经修复了。
