### ISSUE TITLE
Potential memory leak in repeat-click directive

### ISSUE THREAD

**Issue by hybridwebdev** [ElemeFE/element#16588]
### Element UI version
2.10.1

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
Use any element that uses the repeat-click directive

### What is Expected?
Directive should unbind event handlers when destroyed

### What is actually happening?
No code exists to remove the event handlers

**Comment by hybridwebdev** [comment]
As stated in ticket, after looking at the code for the repeat-click directive, it's clear you do nothing to unbind event handlers in your repeat-click directive. When any elements are destroyed that use the directive, the directives event handlers are never removed. This is likely going to cause memory leaks. 

Solution would be to remove event handlers on the element destroyed life cycle event.

**Comment by ibufu** [comment]
Please open issues in a correct repo.
