### ISSUE TITLE
[Feature Request] Tree Lazy Loading How to Set Subnode Status (Selected, Semi-Selected and Unselected)

### ISSUE THREAD

**Issue by leaper1** [ElemeFE/element#16582]
### Existing Component
是

### Component Name
Tree

### Description
树组件使用懒加载时，需要根据数据返回字段，来设置子节点的默认状态。比如勾选状态，可以通过设置default-checked-keys 来实现。但是半选状态（HalfChecked）如何实现？并没有default-halfCheck-key，并且方法里也只有getHalfCheckedKeys，而没有set方法

**Comment by iamkun** [comment]
pr welcomed

**Comment by starql** [comment]
@leaper1  半选做出来了吗 ? 求教

**Comment by ViavaCos** [comment]
> @leaper1 半选做出来了吗 ? 求教

@starql 
https://github.com/ElemeFE/element/issues/13500
如果还是不明白，可以百度下ViavaCos，博客园里我写了个demo可供参考
