### ISSUE TITLE
[Feature Request] affix

### ISSUE THREAD

**Issue by vxhly** [ElemeFE/element#16583]
### Existing Component
否

### Component Name
el-affix

### Description
最近想写某个元素吸附于某个地方的功能,寻找了一下文档居然没有类似于 https://vue.ant.design/components/affix-cn/ 这里的组件或者功能,该功能在页面滚动时常常需要用到,因为用户希望某些元素能够固定在可视范围之内,希望官方能够出一个类似于 https://vue.ant.design/components/affix-cn/ 的功能或者组件

在此同时也希望表格的表头也能做到吸附到某个地方的特征

**Comment by island205** [comment]
pr welcome
