### ISSUE TITLE
El-cascader V-model can't use.

### ISSUE THREAD

**Issue by Churchson** [ElemeFE/element#16596]
### Element UI version
0.1.0

### OS/Browsers version
Chrome 75 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/churchson/pen/oKvzjO

### Steps to reproduce
动态加载数据无法设置默认值， v-model 绑定不会触发懒加载

### What is Expected?
可以设置默认值

### What is actually happening?
不过怎么设置都无法使用。 可以直接选，但是要绑定的时候不起作用

**Comment by ziyoung** [comment]
fixed in 2.11.0
