### ISSUE TITLE
[Bug Report] Table with fixed column duplicate the data in the dom

### ISSUE THREAD

**Issue by sigmaadam** [ElemeFE/element#16598]
### Element UI version
2.10.1

### OS/Browsers version
Mac 10.14.5 (18F132)/ Chrome 75.0.3770.100 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/e6osp81f/

### Steps to reproduce
Just add fixed="left" to the first column of the table

### What is Expected?
Table is rendered only once in the dom

### What is actually happening?
Table is rendered twice in dom

**Comment by ziyoung** [comment]
Not a element bug.
