### ISSUE TITLE
[Bug Report] size="small"的el-select动态切换disabled属性，el-select高度会由32px变为40px

### ISSUE THREAD

**Issue by Yunshan-Lew** [ElemeFE/element#16592]
### Element UI version
2.8.2

### OS/Browsers version
Win10 Chrome

### Vue version
2.5.2

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题

### Steps to reproduce
&lt;el-select size="small" :disabled="bool"&gt;&lt;/el-select&gt;，动态变更bool值，el-input高度会由32px变为40px。

### What is Expected?
el-select高度不变

### What is actually happening?
el-select高度会由32px变为40px

**Comment by ibufu** [comment]
https://jsfiddle.net/4v56tz3f/
