### ISSUE TITLE
[Bug Report] delete el-tbale has row, this spanmethod does not function

### ISSUE THREAD

**Issue by agfire** [ElemeFE/element#16591]
### Element UI version
0.1.0

### OS/Browsers version
window

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wgfire/pen/bXbGoN

### Steps to reproduce
页面渲染时 会合并第二列相同的行，但是当删除某一行时，合并算法并没有再次被调用嘛？表格渲染布局错乱，但刷新页面恢复正常。

### What is Expected?
当动态改变表格的行时，合并方法能够再次被调用

### What is actually happening?
改变表格行的数据是，合并方法出现问题

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
