### ISSUE TITLE
表单验证单个字段验证

### ISSUE THREAD

**Issue by x4storm** [ElemeFE/element#1659]
### ElementUI version

1.0.2
### OS/Browers version
macOS/Chrome 54

### Vue version

2.1.3

### Reproduction Link

https://jsfiddle.net/x4storm/d5dofm9c/
### Steps to reproduce
点击验证全部，验证单个，单个异步验证。其结果，api接口不统一。
`validate(cb)` cb 会接受一个代表验证通过的布尔值，为真则通过。

而`validateField(prop, cb)` cb接受的参数又变成nodejs的风格了。验证通过为null，验证不通过，异步为callback里传递的内容，同步为验证的字段信息。

传值为 `null` 则通过， 是自己观察后得出的结论，不知是否是框架原先就这样设置的，所以需要解除疑惑。
### What is Expected?
请问，这两个API参数不统一，是属于原本的设计吗？
如果是，请在文档中明确说明，以免造成误解，担心有坑。

**Comment by baiyaaaaa** [comment]
同步与异步回调参数不统一确实是有问题的，下版本会进行修正。对整个表单进行验证回调参数以布尔值来代表是否通过是设计中的，一般认为整体表单的验证用户只关心最后的结果。

**Comment by x4storm** [comment]
@baiyaaaaa 嗯，单个字段的验证可以加强下。因为存在类似这样的情况：
获取验证码，要对填写手机号的字段进行验证

**Comment by JuanJuanZhang123** [comment]
请问validateField应该怎么判断是否校验通过呢？
