### ISSUE TITLE
多行文本输入框设置autosize最大行数失效

### ISSUE THREAD

**Issue by Andy-Shangsa** [ElemeFE/element#16594]
![image](https://user-images.githubusercontent.com/24542738/61354120-03996c00-a8a4-11e9-8ccd-9d0a129c5d36.png)

此处未设置最大高度，理应：result.maxHeight = `${maxHeight}px`;

**Comment by Andy-Shangsa** [comment]
优化建议

**Comment by ElsaOOo** [comment]
> 优化建议

这明明是一个bug，官方文档演示那里也是有这样的bug。

**Comment by lihuangshuaige** [comment]
修复了吗？
