### ISSUE TITLE
When the height of the [Bug Report] table is 100%, the data is generated dynamically and the summary shows an exception.

### ISSUE THREAD

**Issue by lucid111** [ElemeFE/element#16602]
### Element UI version
2.10.1

### OS/Browsers version
Chrome75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/dxyyRm?editors=1111#anon-login

### Steps to reproduce
1、在console里面输入data()，现象为summary在表格下面被隐藏了
2、改变表格dom大小，summary就出现了

### What is Expected?
生成summary的时候刷新下table_data的高度

### What is actually happening?
改变表格dom大小才会显示正常

**Comment by ziyoung** [comment]
有临时的解决方案，设置数据后手动调用一下 doLayout 方法吧。https://codepen.io/ziyoung/pen/rXYywE?editors=1111

**Comment by lucidwater** [comment]
> 有临时的解决方案，设置数据后手动调用一下的doLayout方法吧。https://codepen.io/ziyoung/pen/rXYywE?editors=1111

OK，thanks

**Comment by zhyf08** [comment]
这个bug确实存在，上面提供的临时解决方案测试可行。

**Comment by nanedo** [comment]
合计行显隐是跟data长度相关联的，但是当table的data长度变化后，组件却没有重新计算布局导致样式错误了
