### ISSUE TITLE
[Bug Report] el-table uses both lazy and default-expanded-keys with bugs

### ISSUE THREAD

**Issue by strongerLi** [ElemeFE/element#16604]
### Element UI version
2.10.1

### OS/Browsers version
window10/ chrom 75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lixq/pen/Jgjjxv

### Steps to reproduce
当我的表格中使用lazy时，同时我的表格一级想默认展开，这时我使用了default-expanded-keys，这个时候如果二级数据中有子集的话，箭头会默认展开，但是并没有load数据，点击箭头的时候，箭头会先收起来，然后瞬间打开并load数据。

### What is Expected?
懒加载的箭头能正常显示并使用

### What is actually happening?
箭头指示错误

**Comment by strongerLi** [comment]
翻译的里面的代码地址写错的！！！
https://codepen.io/lixq/pen/Jgjjxv

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/16926#issuecomment-519035329
