### ISSUE TITLE
[Bug Report] Tree Table Rendering

### ISSUE THREAD

**Issue by wsyxzxs** [ElemeFE/element#16603]
### Element UI version
2.10.1

### OS/Browsers version
windows 10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wsyxzxs/pen/ZgEEqe

### Steps to reproduce
开始我使用的是element-ui 2.8.2版本，获取的数据结构，能正确将数据渲染到列表，此时具有层级表格关系。由于个人将 element-ui 更新至2.10.1 版本后，数据层级格式无法显示，将版本号更新回 2.8.2 版本也不能正确显示层级表格。

### What is Expected?
期望可以指出如何正确实现该功能的效果

### What is actually happening?
静候您的回复

**Comment by ziyoung** [comment]
demo 无法正常运行。

**Comment by wsyxzxs** [comment]
已经解决了，我去掉 tree-props 的配置，数据结构中不用hasParent 、hasChildren 时，能正常显示，不知道为啥
