### ISSUE TITLE
When [Bug Report] el-input does not use value or V-model binding model, the input will be automatically emptied

### ISSUE THREAD

**Issue by GuangMingZ** [ElemeFE/element#16614]
### Element UI version
2.10.1

### OS/Browsers version
Chrome，IE，Firefox

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
进入“在线运行”模式->删除el-input的value或v-model属性->再次在el-input中输入内容，内容将会被自动清空。

### What is Expected?
在输入框中正确显示输入内容

### What is actually happening?
输入框被自动清空

**Comment by ibufu** [comment]
复现链接错误
