### ISSUE TITLE
[Bug Report] Multiselect not functioning when the options value's are objects

### ISSUE THREAD

**Issue by Winston-Guess** [ElemeFE/element#16616]
### Element UI version
2.10.1

### OS/Browsers version
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/0k62y1sr/1/

### Steps to reproduce
Use an el-select component with a `multiple` attribute and options that contain objects as their value.

### What is Expected?
Select-able options are present and when selected form an array of objects as defined by `value` in each option.

### What is actually happening?
No options are available for selection.

**Comment by ibufu** [comment]
https://jsfiddle.net/gdtq30fv/3/
Use element-ui@2.10.1.

**Comment by Winston-Guess** [comment]
> https://jsfiddle.net/gdtq30fv/3/
> Use element-ui@2.10.1.

I applied this change to my component, however it revealed that the issue for me was not only due to using an older version of element-ui. In the latest version I'm still getting an issue when I use a combination of `multiple`, `remote`, and object values along with `value-key` - see: https://jsfiddle.net/315ozLrw/.

The reason for the issue is obvious, there are no options set initially to compare the value to. You could fix this with a hack whereby you set the options from a `map` of the initial values on `mounted` however this is very inelegant and leads to a number of other minor issues. Not sure if I should create a new issue for this?

**Comment by ibufu** [comment]
Try `:key="item.value.test"`

**Comment by Winston-Guess** [comment]
> Try `:key="item.value.test"`
> https://jsfiddle.net/Lhyore9q/2/

That link does not work for me. Just to be clear, the initial selected option `someObject` should be selected at the start. I.e. before any actions are taken the component should like this:

![image](https://user-images.githubusercontent.com/25578697/61937518-556e8000-af8f-11e9-95cd-9a35d246c1a8.png)

**Comment by Winston-Guess** [comment]
Part of the issue with your previous fiddle was that `value` was not an array initially, it should have been `value: [someObject],`. However this does not solve the issue as evidenced in https://jsfiddle.net/5mxLpd7f/

An partial solution is to set `options` equal to all the possible options initially i.e., `this.options = this.list` (see https://jsfiddle.net/5mxLpd7f/1/). However, this is not a real solution since you most likely won't have a full list of the options initially (e.g. the remote method returns only a subset of options if the number of potential options is too large).
