### ISSUE TITLE
When [Bug Report] table expands rows and tree data nesting, the toggle Row Expansion event conflicts and expands rows with high priority. There are differences between the old version 2.8.2 and the new version 2.8.2 table in expanding rows and nesting tree data.

### ISSUE THREAD

**Issue by Fhnandweb** [ElemeFE/element#16612]
### Element UI version
2.10.1

### OS/Browsers version
window10

### Vue version
2.6.10

### Reproduction Link
https://github.com/Fhnandweb/element-ui-table-

### Steps to reproduce
树形table嵌套展开行，调用toggleRowExpansion()冲突，5月份2.8.2版本没问题，现在的2.8.2有冲突

### What is Expected?
树形table和展开行展开的方法做区分，不要共用

### What is actually happening?
解决树形table和展开行的嵌套

**Comment by MatthewLeeOnTheWay** [comment]
same problem likes yours! It also occurs in version 2.9.2 ,but not yet be solved

**Comment by ziyoung** [comment]
内容实现做了区分，请提供可复现的 demo。
