### ISSUE TITLE
[Bug Report]Errors in location and animation occur when el-table is used in conjunction with el-popover or el-collapse-transition

### ISSUE THREAD

**Issue by myh6666** [ElemeFE/element#16615]
### Element UI version
2.10.1

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Loa21j6t/1/

### Steps to reproduce
1、el-table与el-popover配合使用，弹出框出现在上方时，弹出框位置比预期要更偏上。
2、el-table与el-collapse-transition配合使用时，动画会闪一下。
错误原因：当el-table初始渲染时table宽度被固定，导致单元格折行。此时popover与collapse-transition要获取内容高度来设置top与height。之后el-table的宽度会自动撑开，导致内容不再折行，高度变小，引起误差

### What is Expected?
弹出框位置正常，动画不闪

### What is actually happening?
弹出框位置偏上，动画会闪一下

**Comment by ziyoung** [comment]
与 table 的实现有关，table 监听了 resize 事件。
