### ISSUE TITLE
[Bug Report] table shows the row to generate component bugs repeatedly

### ISSUE THREAD

**Issue by luchenzhang** [ElemeFE/element#16611]
### Element UI version
2.10.1

### OS/Browsers version
win10/Google Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/voYObe?editors=1111

### Steps to reproduce
点击展现列，会渲染2次button-counte这个组件，原因：fixed="right"  有这固定列

### What is Expected?
渲染一次组件

### What is actually happening?
渲染2次组件

**Comment by ziyoung** [comment]
与固定列的实现有关，issue列表里搜一下吧。
