### ISSUE TITLE
[Bug Report] tree component disabled node. parent. checked handle parent not checked

### ISSUE THREAD

**Issue by Dd-ouni** [ElemeFE/element#16620]
### Element UI version
2.10.1

### OS/Browsers version
Google Chrome 75 and All

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ddouni/pen/LwYLEy?editors=1010

### Steps to reproduce
展开按需加载的tree node， check父节点，父节点无法被check， 所以子节点也都没被check。 没有子节点的子节点可以check，所有子节点被check之后， 父节点才会被check。

### What is Expected?
check父节点， 选父带子。 通过disabled handle function parent.checked， 来控制 disabled 属性

### What is actually happening?
配置了 disabled  方法后， 
disabled(data, node) {
            if (node.parent.checked) {
              return true;
            }
 }
有子节点的父节点， 无法check

**Comment by Dd-ouni** [comment]
@ziyoung

**Comment by ziyoung** [comment]
disabled | 指定节点选择框是否禁用为节点对象的某个属性值
-- | --

你这样的用法属于非常规用法，不确定是什么原因。
