### ISSUE TITLE
[Feature Request] recommends that the table height be 100% and the content area be overflow-y: Auto

### ISSUE THREAD

**Issue by 720t** [ElemeFE/element#16629]
### Existing Component
是

### Component Name
el-table

### Description
很多时候需求表格高100%,内容区域滚动，但el-talbe只能设置固定高度
建议表格高度可以100%,内容区域可以overflow-y:auto

**Comment by ziyoung** [comment]
@720t 再解释清楚一点？不太明白。

**Comment by 720t** [comment]
> @720t 再解释清楚一点？不太明白。

就是希望可以table整体高度占父元素的100%,tbody区域可以溢出滚动
现在的table是固定的高度,tbody区域溢出滚动
