### ISSUE TITLE
table单元格内容可以不换行，而是出现横向滚动条吗？

### ISSUE THREAD

**Issue by tjz101** [ElemeFE/element#1662]
类似bootstrap的响应式表格，在浏览器缩小时，单元格的内容不换行，而是表格下方出现滚动条来滚动表格。

**Comment by tjz101** [comment]
el-table-column固定width就可以出现横向滚动了

**Comment by Leopoldthecoder** [comment]
看起来问题已经解决了？

**Comment by chping2125** [comment]
每个单元格内的内容都不一定，不确定，无法给出具体 width 的时候呢？这个该怎么解决？给的太大，文字少的时候，留白太多。给的小了就折行了
