### ISSUE TITLE
[Bug Report] Popover nested operation demo set visible to true display errors for arrows and positions

### ISSUE THREAD

**Issue by zhixinpeng** [ElemeFE/element#16625]
### Element UI version
2.10.1

### OS/Browsers version
Chromium 版本 71.0.3543.0（开发者内部版本） （64 位

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhixinpeng/pen/voENGW

### Steps to reproduce
just set visible to true

### What is Expected?
show arrows and correct position

### What is actually happening?
no arrows and wrong position, also can not set ithttps://codepen.io/zhixinpeng/pen/voENGW

**Comment by island205** [comment]
workaround: https://codepen.io/island205/pen/zYOBQeM

**Comment by zhixinpeng** [comment]
I think this explanation is very strange. Why can't I directly pass "visible" to true, instead, it should be changed in mounted? If it is not a BUG, why is there no introduction in the document
