### ISSUE TITLE
[Bug Report] select and other drop-down boxes appear animation jitter under Google Visitor, which can be reproduced stably on the official website.

### ISSUE THREAD

**Issue by Fuphoenixes** [ElemeFE/element#16627]
### Element UI version
2.10.1

### OS/Browsers version
window 7 64位 /  Chrome版本 75.0.3770.80（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://element.eleme.cn/#/zh-CN/component/select

### Steps to reproduce
select下拉框在谷歌游览器下出现动画抖动，官网上就可以稳定复现。
https://element.eleme.cn/#/zh-CN/component/select
点击下拉框，动画明显抖动

### What is Expected?
点击下拉框，动画流畅不要抖动

### What is actually happening?
点击下拉框，动画抖动明显

**Comment by leemoncn** [comment]
same problem

**Comment by island205** [comment]
Duplicate of #15501
