### ISSUE TITLE
[Bug Report] Picture Component Load Failed Test Case Failed

### ISSUE THREAD

**Issue by liruifengv** [ElemeFE/element#16624]
### Element UI version
2.10.1

### OS/Browsers version
windows 10

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element

### Steps to reproduce
在`npm run test`跑单元测试时，我发现图片的load failed的测试用例失败了。
报错 `expect null to.be.exist`
```
  it('load failed', async() => {
    vm = createTest(Image, true);
    await wait();
    const error = vm.$el.querySelector('.el-image__error');
    expect(error).to.be.exist;
  });
```
但是当我如下修改了配置文件，单独跑图片的单测时，它是成功的。
```
const testsContext = require.context('./specs', true, /image\.spec$/);
```

### What is Expected?
无论是单独跑图片的测试，还是所有测试一起跑，测试用例都是成功的。

### What is actually happening?
图片组件load failed的测试用例失败

**Comment by a631807682** [comment]
[unit/specs/image.spec.js#L32](https://github.com/ElemeFE/element/blob/dev/test/unit/specs/image.spec.js#L32)
[avatar.spec.js#L91](https://github.com/ElemeFE/element/blob/dev/test/unit/specs/avatar.spec.js#L91)
The avatar component has the same problem, we not sure how much time it takes to respond, why not use `data-uri` or method like `waitForEvent` instead?

**Comment by ziyoung** [comment]
pr welcome.

**Comment by ziyoung** [comment]
@a631807682 提 pr 吧。

**Comment by a631807682** [comment]
@ziyoung 好的
