### ISSUE TITLE
When using Autocomplete Slots in the [Bug Report] input input box, the style is messy

### ISSUE THREAD

**Issue by lyingfromyou** [ElemeFE/element#16626]
### Element UI version
2.10.1

### OS/Browsers version
win7/Google Chrome 73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lyingfromyou/pen/oKgjoG

### Steps to reproduce
在el-input中添加<template slot="prefix">Http://</template>, 或者 <template slot="suffix">.com</template>, template中的内容跟el-input中的内容大小不一

### What is Expected?
el-input中template中的字体大小和格式跟input中的字体格式一致

### What is actually happening?
实际el-input中template中的字体大小和格式跟input中的字体格式大小不一致

**Comment by island205** [comment]
https://codepen.io/island205/pen/oKWabV
