### ISSUE TITLE
[Bug Report] el-dropdown not support Vue 2.6.0 V-slot

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#16634]
### Element UI version
2.10.1

### OS/Browsers version
MAC OS 10.14 / Google Chrome 74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/panhezeng/pen/dxPpqL

### Steps to reproduce
根据vue文档关于具名插槽部分和官方element Dropdown 下拉菜单示例
把
<el-dropdown-menu slot="dropdown">
替换为
<el-dropdown-menu v-slot:dropdown>
后，
鼠标移到下拉菜单文本时没有弹出下拉框菜单项

v-slot 指令自 Vue 2.6.0 起被引入，提供更好的支持 slot 和 slot-scope 特性的 API 替代方案。v-slot 完整的由来参见这份 RFC。在接下来所有的 2.x 版本中 slot 和 slot-scope 特性仍会被支持，但已经被官方废弃且不会出现在 Vue 3 中。

### What is Expected?
鼠标移到下拉菜单文本时弹出下拉框菜单项

### What is actually happening?
鼠标移到下拉菜单文本时没有弹出下拉框菜单项

**Comment by mamying** [comment]
你的写法错误(https://codepen.io/mamying/pen/VoLGpd)
```
<el-dropdown>
  <span class="el-dropdown-link">
    下拉菜单<i class="el-icon-arrow-down el-icon--right"></i>
  </span>
  <template v-slot:dropdown>
    <el-dropdown-menu>
      <el-dropdown-item>黄金糕</el-dropdown-item>
      <el-dropdown-item>狮子头</el-dropdown-item>
      <el-dropdown-item>螺蛳粉</el-dropdown-item>
      <el-dropdown-item disabled>双皮奶</el-dropdown-item>
      <el-dropdown-item divided>蚵仔煎</el-dropdown-item>
    </el-dropdown-menu>
  </template>
</el-dropdown>
```
官方文档中：https://cn.vuejs.org/v2/api/#v-slot
放在组件上`el-dropdown-menu`的`v-slot`等同于`slot-scope="xxx"`
放在`template`上的`v-slot`等同于`slot="xxx"`

理解官方文档意思就好

**Comment by panhezeng** [comment]
好吧，奇怪没报错，通常在不能使用v-slot的元素使用v-slot语法，vue会报错的，比如div之类的，我以为和el-popover组件一样，就算用template包裹也不行呢，我的错，应该尝试一下用template包裹。
