### ISSUE TITLE
[Bug Report] Setting the fixed and show-summary scroll bars in the table cannot be selected under the fixed column.

### ISSUE THREAD

**Issue by jinyanliang** [ElemeFE/element#16639]
### Element UI version
2.10.1

### OS/Browsers version
Windows10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/swalloxy/cs9d1qg2/7/

### Steps to reproduce
Table has show-summary setting, can not select the scroll bar and drag under the fixed column.
For example: I set fixed on date, can not select scroll bar drag on date.

### What is Expected?
The mouse can scroll anywhere in the scroll bar

### What is actually happening?
When table has show-summary and fixed settings, scroll bar scrolling cannot be selected under the set fixed column. The scroll bar can be selected without setting the fixed column. If the scroll bar length does not exceed the fixed column, the table cannot view the full column.

**Comment by qiugu** [comment]
I also encountered this problem, how to solve it

**Comment by jinyanliang** [comment]
I currently have two ways to solve this problem.
1, through the mouse penetration style.el-table__fixed{pointer-events: none;} (not recommended)
2. By changing the z-index in '.el-table__body-wrapper' to be less than the z-index value in '.el-table__fixed >div'
