### ISSUE TITLE
[Bug Report] When using merged rows, only the first row has a hover effect.

### ISSUE THREAD

**Issue by Leo-LL** [ElemeFE/element#16657]
### Element UI version
2.10.1

### OS/Browsers version
Windows 10 64 位 / Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1. 使用合并行表格
2. 鼠标hover到合并行

### What is Expected?
同合并行应该有相同的hover效果

### What is actually happening?
只有第一行有hover效果

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
