### ISSUE TITLE
建议:tag组件希望可以自定义背景颜色，

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1665]
1.建议tag组件支持自定义背景色
2.建议用tag组件，实现类似checkbox的功能

**Comment by Leopoldthecoder** [comment]
Tag 背景色可以自己通过 CSS 覆盖。「实现类似checkbox的功能」是指？

**Comment by ivan403704409** [comment]
@Leopoldthecoder 
就像这个： [demo](https://ant.design/components/tag/)
需求情景：有时想做像checkbox的多选，但不想要checkbox那样的样式，想要像选标签一样的样式。
