### ISSUE TITLE
[Feature Request] Disable transition (animation) option in checkbox, radio and tree node

### ISSUE THREAD

**Issue by hnviradiya** [ElemeFE/element#16650]
### Existing Component
Yes

### Component Name
Checkbox, Radio & Tree Node

### Description
It would be great if there is a way to disable animation/transition when
-checkbox checked
-radio checked
-tree node expand collapse

this animation feels slow as a user experience and overall application seems slow due to that (this should be on last priority anyway :)).

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by island205** [comment]
overwrite css style

**Comment by lianzhao** [comment]
> overwrite css style

Well, yes of course I can disable transition by css, but the Transition component itself takes time to render. Here's a graph when I try to expand a large tree (with `transition: none !important;`)
![image](https://user-images.githubusercontent.com/536786/62244730-a5779780-b412-11e9-87ef-d18e665c8b50.png)

**Comment by island205** [comment]
@lianzhao Thank for your advice, we have consider this.
