### ISSUE TITLE
[Bug Report] v-model.trim cannot enter spaces correctly

### ISSUE THREAD

**Issue by Viyan-cyc** [ElemeFE/element#16658]
### Element UI version
2.10.1

### OS/Browsers version
Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/viyan-cyc/pen/MNaYLJ?&editable=true

### Steps to reproduce
<el-input v-model.trim="input" placeholder="请输入内容"></el-input> 加上v-model.trim后，没有办法正确输入多个英文单词（每个单词用空格隔开）

### What is Expected?
加了v-model.trim后只是去除首尾空格
输入“ hello world ”时是期待输出为
“hello world”而不是“helloworld”

### What is actually happening?
输入“ hello world ”时输出为“helloworld”，在输入过程中，中间不能加入空格，只有完全输入完毕后，移动光标到hello后才能加入空格

**Comment by wacky6** [comment]
https://element.eleme.io/#/zh-CN/component/input
