### ISSUE TITLE
[Bug Report] Error reporting using slot in el-pagination（<slot>-did you register the component correctly?For recursive components,make sure to provide the "name" option）

### ISSUE THREAD

**Issue by zhangxycg** [ElemeFE/element#16656]
### Element UI version
2.9.2

### OS/Browsers version
windows/ie11

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
unknown custom element:（<slot>-did you register the component correctly?For recursive components,make sure to provide the "name" option）
element 2.4.6版本无此错误

### What is Expected?
可否能够在新版本或者2.9.2版本中解决此问题

### What is actually happening?
unknown custom element:（<slot>-did you register the component correctly?For recursive components,make sure to provide the "name" option）
element 2.4.6版本无此错误

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
