### ISSUE TITLE
[Bug Report] Cascader cascade selector, if all non-first-level directories are the same, the default backfilled data in the first-level directory duplicates

### ISSUE THREAD

**Issue by sxdtyzg** [ElemeFE/element#16651]
### Element UI version
2.10.1

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/KOpWVp?&editable=true#anon-login

### Steps to reproduce
步骤：选择（组件-导航-顶部导航）
数据：使用如果数据可复现
var Main = {
    data() {
      return {
        value: [],
        options: [{
          value: 'zhinan',
          label: '指南',
          children: [{
            value: 'shejiyuanze',
            label: '设计原则',
            children: [{
              value: 'yizhi',
              label: '一致'
            }, {
              value: 'fankui',
              label: '反馈'
            }, {
              value: 'xiaolv',
              label: '效率'
            }, {
              value: 'kekong',
              label: '可控'
            }]
          }, {
            value: 'daohang',
            label: '导航',
            children: [{
              value: 'cexiangdaohang',
              label: '侧向导航'
            }, {
              value: 'dingbudaohang',
              label: '顶部导航'
            }]
          }]
        }, {
          value: 'zujian',
          label: '组件',
          children: [{
            value: 'shejiyuanze',
            label: '设计原则',
            children: [{
              value: 'yizhi',
              label: '一致'
            }, {
              value: 'fankui',
              label: '反馈'
            }, {
              value: 'xiaolv',
              label: '效率'
            }, {
              value: 'kekong',
              label: '可控'
            }]
          }, {
            value: 'daohang',
            label: '导航',
            children: [{
              value: 'cexiangdaohang',
              label: '侧向导航'
            }, {
              value: 'dingbudaohang',
              label: '顶部导航'
            }]
          }]
        }, {
          value: 'ziyuan',
          label: '资源',
          children: [{
            value: 'axure',
            label: 'Axure Components'
          }, {
            value: 'sketch',
            label: 'Sketch Templates'
          }, {
            value: 'jiaohu',
            label: '组件交互文档'
          }]
        }]
      };
    },
    methods: {
      handleChange(value) {
        console.log(value);
      }
    }
  };
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')

### What is Expected?
回填的是（指南-导航-顶部导航）

### What is actually happening?
选择（组件-导航-顶部导航）

**Comment by SimonaliaChen** [comment]
Fixed in #15935
