### ISSUE TITLE
[Bug Report] Cascader, click on the option without child elements, and the child elements of the previous option are displayed on the right.

### ISSUE THREAD

**Issue by Aslantoe** [ElemeFE/element#16665]
### Element UI version
2.10.1

### OS/Browsers version
win10 / Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/aslantoe/pen/jgbqpG

### Steps to reproduce
1、点击一个有子元素的选项。
2、再点击一个没有子元素的选项。

### What is Expected?
右侧框消失

### What is actually happening?
右侧框显示上一个选项的子元素

**Comment by SimonaliaChen** [comment]
样式上已经高亮了当前展开的节点，一定需要右侧列表隐藏吗？

**Comment by Aslantoe** [comment]
需要隐藏右侧列表

**Comment by ziyoung** [comment]
fixed in 2.11.1
