### ISSUE TITLE
[Feature Request] how could i change transfer left button or right button order that determined which is on the top

### ISSUE THREAD

**Issue by yandixuan** [ElemeFE/element#16668]
### Existing Component
Yes

### Component Name
Transfer

### Description
i exactly need right arrow is on the left arrow

**Comment by xrkffgg** [comment]
https://github.com/ElemeFE/element/pull/16568

兄弟，看我提交的  第 5个 commit，我测试是没什么问题，如果他们不加的话，你就看着该吧，其实最简单的就是 把 那个文件的 两个 button 互换个 位置。。。。当然 只是你本地的，别人的下载 UI 还是 默认的

**Comment by yandixuan** [comment]
thanks, 老哥




------------------ 原始邮件 ------------------
发件人: "xrkffgg"<notifications@github.com>; 
发送时间: 2019年7月24日(星期三) 下午5:02
收件人: "ElemeFE/element"<element@noreply.github.com>; 
抄送: "小 燕 几"<451868992@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ElemeFE/element] [Feature Request] how could i change transferleft button or right button order that determined which is on the top (#16668)




#16568
 
兄弟，看我提交的  第 5个 commit，我测试是没什么问题，如果他们不加的话，你就看着该吧，其实最简单的就是 把 那个文件的 两个 button 互换个 位置。。。。当然 只是你本地的，别人的下载 UI 还是 默认的

**Comment by ziyoung** [comment]
pr welcome

**Comment by xrkffgg** [comment]
@ziyoung   
new PR : https://github.com/ElemeFE/element/pull/16834
