### ISSUE TITLE
[Bug Report] rate's value does't support array??(The score-template value of the rate component does not support arrays)

### ISSUE THREAD

**Issue by iamhanson** [ElemeFE/element#16674]
### Element UI version
2.10.1

### OS/Browsers version
谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/iamhanson/pen/XvXJPp

### Steps to reproduce
https://codepen.io/iamhanson/pen/XvXJPp

(如果是常规变量，没有问题，但是如果使用数据，无法正常渲染。之前用的1.x是可以的，后来升级之后遇到了这个问题)

### What is Expected?
display score(显示分数)

### What is actually happening?
variable is shown (显示了变量名)

**Comment by iamhanson** [comment]
waiting

**Comment by qingdengyue** [comment]
这个{value} 里的value是个关键字，不是value那个变量。跟占位符差不多。

**Comment by xrkffgg** [comment]
- `score-template="{value}" `   正常显示  3.7
- `score-template="爱心{value}" `  显示  爱心3.7

明白了吧

**Comment by ziyoung** [comment]
感谢 @qingdengyue @xrkffgg 两位的回答。
