### ISSUE TITLE
[Bug Report] Message Tips Error

### ISSUE THREAD

**Issue by luolong05** [ElemeFE/element#16675]
### Element UI version
2.10.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/luolong05/pen/bXENZX?&editable=true

### Steps to reproduce
1.页面上同时加载两个message消息框，第一个框默认3秒自动消失；第二个框永久显示。
2.第一个框关闭时，第二个框高度自动改变，改变的值为负值，导致弹框显示不全。

### What is Expected?
第一个提示框消失后，第二个提示框位置正常显示。

### What is actually happening?
第二个提示框top设置不对，导致提示框显示了一半。

**Comment by xrkffgg** [comment]
@luolong05 

兄弟，你在第二个里面加一个 `offset: 64,`就行啦

如果有第三个 再加 48*2 +16

查看源码发现：
`48是 这个message 的高度， 16是每次新增 添加的偏移量，`

这里有一个不完美的地方，就是 默认的top 是20 ，每次 添加是 16 。

你的原因是 你同时 触发2个，UI 没有把48加上，默认加了16 ，

增加了 offset: 64 后，1 消失的 时候， 2 距离顶 是 16 

如果 每次 增加是 20  就好了 。。。  或者 默认第一个 顶部 是16 
保持 2个统一，这样 整体的样式是统一的。。。。

如果 eleme 他们 不改的话，

你可以修改 element\packages\message\src\main.js    37 行  默认增加 20   或者   
vue 文件中  verticalOffset  改成 16

**Comment by island205** [comment]
workaround: https://codepen.io/island205/pen/WNexqoz?&editable=true
