### ISSUE TITLE
[Bug Report] setCurrentRow () method cannot cancel the display effect of highlighted rows

### ISSUE THREAD

**Issue by souselesslove** [ElemeFE/element#16670]
### Element UI version
2.10.1

### OS/Browsers version
chrome75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/XvmqmX?&editable=true

### Steps to reproduce
选择第三行，第三行变为高亮，点击取消选择，第三行的高亮显示效果未改变

### What is Expected?
点击取消选择后，第三行的高亮高亮显示效果应取消

### What is actually happening?
。

**Comment by xrkffgg** [comment]
试了一下，官网的例子是有点问题啊。

但是 安装后，在本地测试 是正常的。。。。

**Comment by souselesslove** [comment]
> 试了一下，官网的例子是有点问题啊。
> 
> 但是 安装后，在本地测试 是正常的。。。。

请问你本地是怎么写的代码，可以上传出来看一下？

**Comment by xrkffgg** [comment]
@souselesslove  可能是我看错了，2.9.2 版本的 官网是没问题的 

看更新日志，估计是 这个的原因
https://github.com/ElemeFE/element/pull/15983
