### ISSUE TITLE
[Bug Report] “暂无数据”这四个字是否可以按表格最外面的边框进行相对定位，浮在整个表格之上

### ISSUE THREAD

**Issue by lshz0088** [ElemeFE/element#16677]
### Element UI version
2.10.1

### OS/Browsers version
360极速模式

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lshz0088/pen/YmwyKP

### Steps to reproduce
当没有数据的时候，会显示“暂无数据”
但是当可拖动列很多的时候，暂无数据会被下面的滚动条拖来拖去，体验不是很好，
甚至是拖到看不见为止。

### What is Expected?
相对最外面的div进行相对定位

### What is actually happening?
相对内部可移动div进行相对定位

**Comment by xrkffgg** [comment]
😂😂😂

兄dei，因为你的最右边没有固定，所有你在拖动的时候，`table` 的 width 会进行改变，`x`轴出现了滚动条，你在最右边的操作列加上`fixed="right“`，这样你说的”暂无数据“就不会左右动了

**Comment by lshz0088** [comment]
和fixed="right“啥关系？？？
试试这个：https://codepen.io/lshz0088/pen/YmwyKP

**Comment by zzh3319** [comment]
@lshz0088   这个有什么用？？？
