### ISSUE TITLE
[Bug Report] table sort

### ISSUE THREAD

**Issue by luocong2016** [ElemeFE/element#16684]
### Element UI version
0.1.0

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
姓名字段排序，同名应该不需要排序。

### What is Expected?
中文同名字段不需要排序

### What is actually happening?
不知道具体的排序规则，同名中文字段不是按出现顺序排序的

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
