### ISSUE TITLE
[Bug Report] custom vaildator can not get lastest value when event trigger

### ISSUE THREAD

**Issue by yiptsangkin** [ElemeFE/element#16682]
### Element UI version
2.10.1

### OS/Browsers version
osx/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/JgGXzx?editors=1111

### Steps to reproduce
when the `age` input is blured, the filed's value can not be updated, still be a empty value, it happen when you use loop to render the el-form-item.

### What is Expected?
the value can be updated.

### What is actually happening?
the value can not be updated.

**Comment by xrkffgg** [comment]
@yiptsangkin  你的例子 修改2个地方
### 1.

`<el-input type="text" v-model="ruleForm[item.prop]" autocomplete="off"></el-input>`


### 2.
```
if (!Number.isInteger(+value)) {
    callback(new Error('请输入数字值'));
}
```

### 原因：
- text拼写错误了，而且你要这么写，输入的都是字符串类型。所以在判断类型的时候报错，用`+value`代替`value` 是将字符串转成 数字类型

- 表单的校验是会去校验 你定义的 `ruleForm.pass`  `ruleForm.checkPass`  `ruleForm.age` ，你v-model 的定义写错了

**Comment by yiptsangkin** [comment]
> @yiptsangkin 你的例子 修改2个地方
> 
> ### 1.
> `<el-input type="text" v-model="ruleForm[item.prop]" autocomplete="off"></el-input>`
> 
> ### 2.
> ```
> if (!Number.isInteger(+value)) {
>     callback(new Error('请输入数字值'));
> }
> ```
> 
> ### 原因：
> * text拼写错误了，而且你要这么写，输入的都是字符串类型。所以在判断类型的时候报错，用`+value`代替`value` 是将字符串转成 数字类型
> * 表单的校验是会去校验 你定义的 `ruleForm.pass`  `ruleForm.checkPass`  `ruleForm.age` ，你v-model 的定义写错了

好的，我已经知道怎么处理这个问题了，谢谢
