### ISSUE TITLE
Dialog对话框中的select会随页面滚动走

### ISSUE THREAD

**Issue by clll7** [ElemeFE/element#1668]
打开dialog，再打开select，滚动鼠标滚轮时，select列表会跟随滚动。如图所示，chorme浏览器。

![qq 20161210144752](https://cloud.githubusercontent.com/assets/6949822/21071802/fa5317fc-bee7-11e6-9e01-d331dc5003e9.png)
![qq 20161210144736](https://cloud.githubusercontent.com/assets/6949822/21071801/fa4f6670-bee7-11e6-9b07-c5874bea717a.png)

**Comment by Leopoldthecoder** [comment]
在 macOS 和 Windows 上均无法重现。你打开官方文档就有这个现象吗？

**Comment by clll7** [comment]
是的，估计是我装的浏览器装得有问题，别的电脑没事

**Comment by clll7** [comment]
是的，估计是我装的浏览器装得有问题，别的电脑没事
