### ISSUE TITLE
[Bug Report] When the MessageBox opened ，confirm button is the trigger hover state ，need click page back to normal

### ISSUE THREAD

**Issue by Klaur** [ElemeFE/element#16683]
### Element UI version
2.5.4

### OS/Browsers version
win10 

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/api/post/library/pure/

### Steps to reproduce
the demo of the project home page can be reproduced。

### What is Expected?
MessageBox opened,this confirm (primary) button is normal style

### What is actually happening?
 When opened , confirm (primary) button trigger  hover action

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
