### ISSUE TITLE
[Feature Request] Transfer emits search and scroll events

### ISSUE THREAD

**Issue by fralonra** [ElemeFE/element#16691]
### Existing Component
是

### Component Name
Transfer

### Description
Sometimes we need to fetch data from server dynamically, for example:
1. Entering some keywords in input box then launching a ajax.
1. Fetching data when user scrolling the left panel of the transfer to the bottom (infinite scroll).

For sake of this, I think it would be appreciated that if Transfer can emit two events: **search** and **scroll**, just like what [antd](https://vue.ant.design/components/transfer/#events) has done. With these two events, the cases mentioned above would be easier to handle.

**Comment by fralonra** [comment]
https://github.com/ElemeFE/element/issues/12157 related.

**Comment by island205** [comment]
#12160 PR

**Comment by fralonra** [comment]
> #12160 PR

That's great!

BTW, It would be better if Transfer comes with a `scroll` event.
