### ISSUE TITLE
自定义主题报错

### ISSUE THREAD

**Issue by love-ya** [ElemeFE/element#1669]
### ElementUI version
1.0.6 

### OS/Browers version
 Chrome 54 

### Vue version
 2.1.0 

使用 et 创建主题时出现报错（element-theme-default v1.0.6）
但安装这个后 npm i https://github.com/Molunerfinn/theme-default.git -D可以正常运行

events.js:160
throw er; // Unhandled 'error' event
^
Error: ENOENT: no such file or directory, open '/data/app/tt/node_modules/element-theme-default/src/vue-popup/lib/popup.css'
at Error (native)

**Comment by QingWei-Li** [comment]
重新安装下 `element-theme`，已经更新了 `postcss-salad`
