### ISSUE TITLE
[Bug Report] el-cascader cascade selection display error

### ISSUE THREAD

**Issue by YooLin** [ElemeFE/element#16695]
### Element UI version
2.10.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/jgWLeN?&editable=true

### Steps to reproduce
1.hover 触发子菜单 选择包 / 箱 展示正确
2.hover 触发子菜单 选择个 / 箱 展示错误，仍然展示包 / 箱

### What is Expected?
hover 触发子菜单 选择个 / 箱 展示个 / 箱

### What is actually happening?
hover 触发子菜单 选择个 / 箱 展示包 / 箱

**Comment by vivianus-chan** [comment]
手快保存到问题重现链接：https://codepen.io/vivianus/pen/qebLjR?editors=1111，el-cascader ，lazy动态加载数据怎么设置默认值（回显值），v-model无法触发lazyLoad方法，而且默认值也是请求接口所得，必须先拿到默认值再触发lazyLoad方法，有什么方法可以手动触发的？在线等解决方法，折腾一天了。

**Comment by vivianus-chan** [comment]
手快保存到问题重现链接：https://codepen.io/vivianus/pen/LwGMgj
动态加载lazy数据怎么设置默认值（回显值），v-model无法触发lazyLoad方法，而且默认值也是请求接口所得，必须先拿到默认值再触发lazyLoad方法，有什么方法可以手动触发的？在线等解决方法，折腾一天了。

**Comment by xrkffgg** [comment]
@YooLin 你的原因是因为你的 第二级的 ID 重复了，你将第二级的ID不重复就可以了，或者是你的第二级的ID是 第一级的ID + 现有的序号。

如：
```
options:[
    {
        unitId: 2,
        unitName: '包',
        children: [
            {
	        unitId: 201,
	        unitName: '个'
	    }, 
            {
	        unitId: 202,
	        unitName: '袋',
	    }, 
        ]
    },
    {
        unitId: 1,
        unitName: '个',
        children: [
            {
	        unitId: 101,
	        unitName: '个'
	    }, 
            {
	        unitId: 102,
	        unitName: '袋',
	    }, 
        ]
    },
]
```

**Comment by xrkffgg** [comment]
@vivianus-chan 😂😂😂
我也试了很久，发现真是不行，因为只有在点开下拉框的时候才会动态去加载，反显的场景无法模拟自动去点击那些选项。使用ref直接去设置也不起作用。

想了3种方案吧。

### 1 不使用动态加载

> 演示地址：
https://codepen.io/xrkffgg/pen/aeNpVM?editors=1010


- 在`created`里有一个赋值的过程，这里可以修改为请求后台返回数据
- 这样也有问题，就是如果层级数据多的话，就会很差

### 2 使用多个Select 选择器
新建时候，请求第一级。然后选择第一级后，请求第二级，依次下去。

修改时候，根据具体选择的去请求依次层级显示。

- 性能应该还可以
- 就是会有3个框，不是一次性选择完

### 3 使用tree 组件
- 这个组件接口更多一些
- 可以自己设定默认选中和默认展开的项

**Comment by YooLin** [comment]
> @YooLin 你的原因是因为你的 第二级的 ID 重复了，你将第二级的ID不重复就可以了，或者是你的第二级的ID是 第一级的ID + 现有的序号。
> 
> 如：
> 
> ```
> options:[
>     {
>         unitId: 2,
>         unitName: '包',
>         children: [
>             {
> 	        unitId: 201,
> 	        unitName: '个'
> 	    }, 
>             {
> 	        unitId: 202,
> 	        unitName: '袋',
> 	    }, 
>         ]
>     },
>     {
>         unitId: 1,
>         unitName: '个',
>         children: [
>             {
> 	        unitId: 101,
> 	        unitName: '个'
> 	    }, 
>             {
> 	        unitId: 102,
> 	        unitName: '袋',
> 	    }, 
>         ]
>     },
> ]
> ```

thanks
