### ISSUE TITLE
[Bug Report] Jitter Problem in Pull-Down Ejection

### ISSUE THREAD

**Issue by chairui2001** [ElemeFE/element#16707]
### Element UI version
2.10.1

### OS/Browsers version
WIN 10 / Chrome 75.0.3770.142（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/chairui2001/pen/VoaraJ

### Steps to reproduce
1. 打开官网 https://element.eleme.cn/#/zh-CN/component/select
2. 对 select 组件进行下拉操作
3. 多尝试几次，下拉弹出动画有时会出现上下抖动
4. 其它有下拉动画的组件，有时也会出现该问题
5. 经排除法测试，发现该现象在父级存在 overflow 样式时才会出现

### What is Expected?
下拉动画能正常展现

### What is actually happening?
下拉动画会出现上下抖动

**Comment by island205** [comment]
Duplicate of #15501
