### ISSUE TITLE
[Bug Report] IE In Component el-dialog, el-date-picker disabled

### ISSUE THREAD

**Issue by kompieto** [ElemeFE/element#16706]
### Element UI version
2.10.1

### OS/Browsers version
IE  11 10 9 8

### Vue version
2.6.10

### Reproduction Link
<el-dialog :visible.sync="dialogVisible">
      <div slot="title">会议延期</div>
      <el-form :model="form">
          <el-form-item label="延期时间至" :label-width="dialogFormLabelWidth">
            <el-date-picker
              v-model="delayTime"
              @change="getSTime"
              :picker-options="pickerOptions"
              type="datetime"
              format="yyyy-MM-dd HH:mm">
            </el-date-picker>
          </el-form-item>
      </el-form>
      <div slot="footer" class="dialog-footer">
          <el-button @click="cancleDialog">取 消</el-button>
          <el-button type="primary" @click="submitDialog">确 定</el-button>
      </div>
      
      <div class="dlg-1" v-if="delayTimeTips.shown" style="width: 350px; top: 30%">
        <b class="dlg-text">{{delayTimeTips.text}}</b>
      </div>
    </el-dialog>

### Steps to reproduce
none

### What is Expected?
none

### What is actually happening?
none

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
