### ISSUE TITLE
el-menu导航动态绑定，会报错

### ISSUE THREAD

**Issue by LittleChild** [ElemeFE/element#1670]
hi，很高兴使用上你们提供的UI组件，真的很棒！但是我在使用el-menu的时候发现，如果用v-for循环遍历生成el-menu的时候绑定index，控制台会报错。是我使用的方法有问题么？代码如下：
https://jsfiddle.net/LittleChild/kajf2cx2/

**Comment by Leopoldthecoder** [comment]
`el-submenu` 要求 `index` 参数为字符串类型，而 `:index="index"` 这样绑定的是数字类型。改成 `:index="index + ''"` 就可以。

**Comment by LittleChild** [comment]
谢谢👍

**Comment by taishan802** [comment]
我遇到类似的问题：<el-menu-item v-for="secItem in item.secondNavList" :key="secItem.component" :index="secItem.component" v-show="secItem.hasAuth">{{secItem.name}} </el-menu-item>对这个二级导航条，componet都是string,一直报错vue.esm.js?65d7:576 [Vue warn]: Duplicate keys detected: 'index'. This may cause an update error.，求大神帮忙看看
