### ISSUE TITLE
[Feature Request] DatePicker: prevent auto transform date when input invalid date

### ISSUE THREAD

**Issue by duytung1009** [ElemeFE/element#16708]
### Existing Component
Yes

### Component Name
DatePicker

### Description
When input an invalid date into the datepicker, it will auto transform into a valid date (for example: 2019-30-15 => 2021-06-15). In case we want to show an error when user input an invalid date it's impossible to check (because the input text had been parsed into a valid one).
Could we have an option to disable the auto transform behavior so we can manually check if the input value is invalid. Or may be an option to turn invalid date into an empty string instead of auto transform into a valid date (i think that behavior is more clearly).

**Comment by CuongStf** [comment]
use format and format-value

**Comment by CuongStf** [comment]
and validator for this case (for validate value manually)

**Comment by duytung1009** [comment]
> and validator for this case (for validate value manually)

I have tried to create a custom validator (with trigger='blur') and input invalid date (2019/30/25) but the value return is transformed (2021/06/25). My input already has format and value-format set to yyyy/MM/dd.

**Comment by CuongStf** [comment]
no, you can create validator with value received, split value by '/' and validate them manually

**Comment by duytung1009** [comment]
Well it looked like i can detect it using `@input.native` event and `@focusout.native` event, but implement it into all datepicker in my app is a bit... cumbersome? It would be helpful if the datepicker have an option for it.
![screenshot](https://user-images.githubusercontent.com/14925709/61789396-d1a57e00-ae3e-11e9-895a-9720095bb086.png)

> no, you can create validator with value received, split value by '/' and validate them manually

Can you write an example please, i'm not really cleared on this 😕

**Comment by CuongStf** [comment]
you can read detail about validation in form in document element

**Comment by CuongStf** [comment]
you can get value from user immediately when user change input.

**Comment by duytung1009** [comment]
> you can get value from user immediately when user change input.

I've already tried validation with trigger set at 'blur', 'change' but only get the value that transformed, not the input one

**Comment by CuongStf** [comment]
pls get your code to here

**Comment by duytung1009** [comment]
> pls get your code to here
I make a jsfiddle here 
https://jsfiddle.net/duytung1009/4qkju5de/6/

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
