### ISSUE TITLE
[Bug Report] Version 2.9.2 DatePicker date selector input box does not support formats that separate year, month and day

### ISSUE THREAD

**Issue by kethonC** [ElemeFE/element#16713]
### Element UI version
2.9.2

### OS/Browsers version
win10/chrome-73

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/LwNXzo

### Steps to reproduce
在DatePicker 日期选择器的输入框输入日期年月日用点隔开如 （2019.07.24），按回车键没有反应

### What is Expected?
按回车后选中日期

### What is actually happening?
2.9.2版本按回车键没有反应。在2.8.2及以前版本没有问题

**Comment by jerecui** [comment]
https://github.com/ElemeFE/element/issues/16732

应该是类似的问题，也是 2.9版本以后开始出现问题

https://codepen.io/jerecui/pen/Vobxgg

**Comment by luckyCao** [comment]
#16486

**Comment by danosha** [comment]
Why is this issue closed without an answer? Has anyone solved this problem on their own?
