### ISSUE TITLE
2.10.0 element-ui-common.js Cannot read property 'disabled' of null at VueComponent.hide

### ISSUE THREAD

**Issue by chandero** [ElemeFE/element#16715]
2.10.0 element-ui-common.js Cannot read property 'disabled' of null at VueComponent.hide
Chrome console error
element-ui.common.js:2330 Uncaught TypeError: Cannot read property 'disabled' of null
    at VueComponent.hide (element-ui.common.js:2330)
    at Object.documentHandler (clickoutside.js:39)
    at clickoutside.js:25
    at Array.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (clickoutside.js:24)

Firefox console error
TypeError: this.triggerElm is null[Saber más] element-ui.common.js:2330
hide
element-ui.common.js:2330
hide self-hosted:981:17 createDocumentHandler/<
clickoutside.js:39
./node_modules/element-ui/lib/utils/clickoutside.js/</<
clickoutside.js:25
forEach self-hosted:268:13 ./node_modules/element-ui/lib/utils/clickoutside.js/<
clickoutside.js:24

**Comment by hunkriyaz** [comment]
I am also facing this issue since I updated from 2.10.0 element.

Here is the screenshot:
<img width="968" alt="Screen Shot 2020-01-28 at 12 33 43 PM" src="https://user-images.githubusercontent.com/5946820/73247542-83e14800-41ca-11ea-8b43-1cd39983790e.png">

It is showing everywhere, even if I click to el-card or other elements.

**Comment by Timmmm** [comment]
Same here. The code where it is called is [here](https://github.com/ElemeFE/element/blob/070bf1fd1b4026e9ba2f18395d41f0815540a0cd/packages/dropdown/src/dropdown.vue#L272).

[clickoutside source](https://github.com/ElemeFE/element/blob/f6df39e8c1ff390da0f0df8ea30b07baf5d457f0/src/utils/clickoutside.js)

Can't see anything obviously wrong in the source.

**Comment by Timmmm** [comment]
Ok the issue in my code was that I had an `<el-dropdown>` with no child `<el-dropdown-items>`. Trivial repro: put this in your components:

      <el-dropdown />

**Comment by androidfanatic** [comment]
+1. We were missing a dropdown slot on one of our `el-dropdown` which was resulting in any el-select or dropdown not working on our app.

Adding the following fixed it 

```js
<el-dropdown-menu slot="dropdown" />
```

**Comment by Anyzm** [comment]
hello，is there anyone having solved it？

**Comment by dolphinfine** [comment]
+1.I have add the follow but no work:
`<el-dropdown-menu slot="dropdown" />`

**Comment by maximesahagian** [comment]
Did you find a soluton @dolphinfine ?

**Comment by maximesahagian** [comment]
@androidfanatic I did it, it solved the "disabled" error, but I can't find any el-option in my el-select since there is this error..

**Comment by jeffysam6** [comment]
@maximesahagian  did you find any solution?

**Comment by maximesahagian** [comment]
@jeffysam6 yes, it came from Jquery conflict, I had to remove Jquery from my VueJS app

**Comment by okosowski** [comment]
in my case, the same error was trigger from **el-dropdown** if there was no **el-dropdown-menu** inside
if someone still fighting with this, el-dropdown should be next places to check

**Comment by mshafrizal** [comment]
hello i am facing this issue too, but I didn't have jQuery in my project. Error in every pages

**Comment by tyrw** [comment]
Having the same issue.

Running `2.15.2`, no jQuery.  `slot="dropdown"` does not solve it.

**Comment by tyrw** [comment]
We were conditionally showing a dropdown menu with:

```html
<el-dropdown-menu slot="dropdown" v-if="...">
```

This was causing the element to not be found because it wasn't there. Using `v-show` instead solved this for us:

```html
<el-dropdown-menu slot="dropdown" v-show="...">
```

**Comment by xiaoyao316** [comment]
Have a try everyone!
```import Vue from 'vue';
import App from './App';
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';

ElementUI.Dropdown.methods.hide = function hide() {
  var _this2 = this;

  if (!this.triggerElm || this.triggerElm.disabled) return;
  this.removeTabindex();
  if (this.tabindex >= 0) {
    this.resetTabindex(this.triggerElm);
  }
  clearTimeout(this.timeout);
  this.timeout = setTimeout(function () {
    _this2.visible = false;
  }, this.trigger === 'click' ? 0 : this.hideTimeout);
}

new Vue({
  components: { App },
  template: '<App/>',
}).$mount('#app');
```

**Comment by litoxy** [comment]
> +1. We were missing a dropdown slot on one of our `el-dropdown` which was resulting in any el-select or dropdown not working on our app.
> 
> Adding the following fixed it
> 
> ```js
> <el-dropdown-menu slot="dropdown" />
> ```

the same issue for me ~ thanks

**Comment by szhang6** [comment]
> Ok the issue in my code was that I had an `<el-dropdown>` with no child `<el-dropdown-items>`. Trivial repro: put this in your components:
> 
> ```
>   <el-dropdown />
> ```

Works for me, thanks!

**Comment by Anyzm** [comment]
感谢您的来件，邮件已收到。

**Comment by czh26** [comment]
> 大家都试试吧！
> 
> ```
> import App from './App';
> import ElementUI from 'element-ui';
> import 'element-ui/lib/theme-chalk/index.css';
> 
> ElementUI.Dropdown.methods.hide = function hide() {
>   var _this2 = this;
> 
>   if (!this.triggerElm || this.triggerElm.disabled) return;
>   this.removeTabindex();
>   if (this.tabindex >= 0) {
>     this.resetTabindex(this.triggerElm);
>   }
>   clearTimeout(this.timeout);
>   this.timeout = setTimeout(function () {
>     _this2.visible = false;
>   }, this.trigger === 'click' ? 0 : this.hideTimeout);
> }
> 
> new Vue({
>   components: { App },
>   template: '<App/>',
> }).$mount('#app');
> ```

Thank you very much. It has been resolved

**Comment by Anyzm** [comment]
感谢您的来件，邮件已收到。
