### ISSUE TITLE
[Feature Request] 希望select组件能够支持通过代码直接修改组件的值

### ISSUE THREAD

**Issue by wkstudy** [ElemeFE/element#16712]
### Existing Component
是

### Component Name
Select

### Description
目前只能通过输入框输入来控制select组件的值，我的业务场景比较希望能够支持通过代码直接修改。
具体业务场景为：有两个支持远程搜索的select组件，第二个select组件的结果依赖于第一个select组件的值，那么在修改第一个select组件时，希望第二个select组件框为空（即不要显示上一次的结果）

**Comment by xrkffgg** [comment]
这个。。。
你在修改第一个的时候，把第二个的v-model 设置为 空 不就行了？

**Comment by JeremyWuuuuu** [comment]
You can achieve that by simply put the reset logic in select's `onChange` handler
你可以直接在 Select 的 `onChange` 处理函数里来 **reset** 第二个 select 绑定的值, 会直接体现在 UI 上

**Comment by wkstudy** [comment]
感谢，已经解决了，是我对这个有点不熟悉




------------------ 原始邮件 ------------------
发件人: "xrkffgg"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 上午9:33
收件人: "ElemeFE/element"<element@noreply.github.com>;
抄送: "1346948470"<1346948470@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ElemeFE/element] [Feature Request] 希望select组件能够支持通过代码直接修改组件的值 (#16712)




这个。。。
 你在修改第一个的时候，把第二个的v-model 设置为 空 不就行了？

**Comment by wkstudy** [comment]
感谢   自己对vue还是不够熟悉啊


 
---原始邮件---
发件人: "jeremywu"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 上午10:30
收件人: "ElemeFE/element"<element@noreply.github.com>;
抄送: "wkstudy"<1346948470@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ElemeFE/element] [Feature Request] 希望select组件能够支持通过代码直接修改组件的值 (#16712)



You can achieve that by simply put the reset logic in select's onChange handler
 你可以直接在 Select 的 onChange 处理函数里来 reset 第二个 select 绑定的值, 会直接体现在 UI 上
