### ISSUE TITLE
[Bug Report] Element Tree Data Table Selection Only Selects Parents

### ISSUE THREAD

**Issue by godsmiless** [ElemeFE/element#16711]
### Element UI version
2.10.1

### OS/Browsers version
win10/chrome-75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/bassb/pen/BXjLYv

### Steps to reproduce
1.点击表格头部 全选复选框
2.表格数据只有父级被选中，树形子级未选中

### What is Expected?
1.点击全选后，表格当前分页内所有行都选中
2.选中父级复选框后，该节点子级全部选中，

### What is actually happening?
1.点击全选，只有父级 被选中，子级未选中
2.点击父级复选框，只有当前行选中，该节点下的子级未被选中

**Comment by ziyoung** [comment]
有类似的 issue 了。

**Comment by buyou0821** [comment]
> 有类似的 issue 了。

类似issue地址呢？看到相似的几个都直接被close了

**Comment by 17881055** [comment]
地址呢

**Comment by dawwad** [comment]
Couldn't find the **Similar Issue**, if anyone can help with that? 

or any proposed solution ?
