### ISSUE TITLE
[Feature Request] Too much data is displayed on a single page of a table, and too much DOM on a page leads to delays

### ISSUE THREAD

**Issue by mazhili0321** [ElemeFE/element#16727]
### Existing Component
是

### Component Name
Table

### Description
My table has been paginated, But I need a page to show more than 500 pieces of data, So there will be too many DOMS on the page, causing lags. I hope you can deal with this problem. Thanks!
（我的表格已经分页，但是我需要在一页中展示超过500条的数据，这样由于页面的Dom过多，导致页面卡顿，希望你们能处理一下这个问题，谢谢！）

**Comment by ziyoung** [comment]
有类似的 issue 了。
