### ISSUE TITLE
(3435:3) Please do not use display: contents; if you have grid setting enabled

### ISSUE THREAD

**Issue by cyh41** [ElemeFE/element#16726]
Vue Version: 2.6.10

when I  use  CLI theme tool to build theme.

chrome will warning: Please do not use display: contents; if you have grid setting enabled

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/19506560/61842170-cb101880-aec9-11e9-98aa-b787a7b7237d.png">

**Comment by farcasmihai91** [comment]
Did you manage to figure it out? I have the same warning popping up.
