### ISSUE TITLE
In the [Bug Report] cascade selector, other items are selected at different option levels, and the parent of the current item is still selected.

### ISSUE THREAD

**Issue by wangzl1163** [ElemeFE/element#16724]
### Element UI version
2.10.1

### OS/Browsers version
win10/谷歌73

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/VojPYg

### Steps to reproduce
选择“选项0”-》“选项1”-》“选项3”，切换选择，选择“选项13”，点击展示下拉框，可以看到“选项0”，“选项1”依然被选中

### What is Expected?
切换选项时所有未选中的项清除选中状态，选中状态准确标识在当前选中项

### What is actually happening?
切换选项时父级选项选中状态未清除

**Comment by ziyoung** [comment]
fixed in 2.11.1
