### ISSUE TITLE
[Bug Report] el-form size="mini"的时候，嵌套的el-form-item  margin-bottom 样式异常

### ISSUE THREAD

**Issue by manfwh** [ElemeFE/element#16723]
### Element UI version
2.10.1

### OS/Browsers version
win7 /chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/manfwh/pen/ymJVZV

### Steps to reproduce
el-form size="mini"后el-form-item嵌套el-form-item

### What is Expected?
设置mini后，嵌套el-form-item的下边距跟正常的一样

### What is actually happening?
设置mini后，嵌套的el-form-item比正常的要大一些

**Comment by ziyoung** [comment]
不是 bug，form-item 的嵌套导致的。

**Comment by manfwh** [comment]
正常尺寸的嵌套，那个下边距会覆盖掉，设置了mini后，没有覆盖
![微信截图_20190731163840](https://user-images.githubusercontent.com/23977810/62197247-19358800-b3b2-11e9-9f90-504e5f6cb5c6.png)
