### ISSUE TITLE
[Bug Report] el-cascader dynamically loads lazy data and how to set default values (echo values)

### ISSUE THREAD

**Issue by vivianus-chan** [ElemeFE/element#16722]
### Element UI version
2.10.1

### OS/Browsers version
google75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/vivianus/pen/LwGMgj

### Steps to reproduce
动态加载lazy数据怎么设置默认值（回显值），v-model无法触发lazyLoad方法，而且默认值也是请求接口所得，必须先拿到默认值再触发lazyLoad方法，有什么方法可以手动触发的？

### What is Expected?
数据能回显

### What is actually happening?
数据不能回显

**Comment by hooray** [comment]
方法是对的，但你的 demo 里用的还是 2.10.1 的，先升级版本吧

**Comment by timeLorder** [comment]
我今天试了2.11.0版，发现开启lazy模式后有时能自动触发lazyload方法进行默认值回填，有时不会。我的情况中默认值不是一开始就有的，是从接口里获取的。不知道是什么原因导致的？

**Comment by hooray** [comment]
这个问题我在 #16745 反馈了，暂时还没等到官方回复

**Comment by macarole** [comment]
这个问题有没有解决方案呀？还是说有什么替代方案呢

**Comment by fangpeishi** [comment]
升级到2.12.0  ，测试正常，感谢。

**Comment by RysisLiang** [comment]
已经升级到2.13了，还是没有存在不能回显的问题

**Comment by xyyVee** [comment]
^2.13.0 版本，还是没有这个回显

**Comment by yolofit** [comment]
![image](https://user-images.githubusercontent.com/20294811/106407567-541cee00-6477-11eb-81ed-0b34d5770f2c.png)
![image](https://user-images.githubusercontent.com/20294811/106407591-6565fa80-6477-11eb-92d5-cd31c3b9811e.png)

分析了源码，2.11.0+就支持数据回填了。
但加载的时机不太优雅，见上图watch options的实现
相当于第一次加载且options等于empty才会执行layzload data

故可利用 v-if时不会注册组件的特性，即可解决异步调用数据的时序不对，导致回填失败的问题。
[https://codepen.io/yoloooooh/pen/WNobzEM](https://codepen.io/yoloooooh/pen/WNobzEM)

**Comment by mashirozx** [comment]
2.15.6 版本下 v-model 变化，label text没更新、选择器选择项变化异常的解决办法：在el-cascader上添加 `:key`，当v-model的数据源更新（即更新不是由cascader自身产生的）时，刷新 `:key` 的值以触发组件的强制更新

![image](https://user-images.githubusercontent.com/16148054/134795044-9f62e362-f87b-4485-954f-2fae7bc4c614.png)
![image](https://user-images.githubusercontent.com/16148054/134795056-a9648b59-560c-4529-91de-a43485f1b8d2.png)

其实这应该是一个bug，v-model值的**外生**变化无法触发cascader组件标签的变化

**Comment by star-hs** [comment]
mark
