### ISSUE TITLE
[Bug Report] drop-down box class bugs about size

### ISSUE THREAD

**Issue by luocong2016** [ElemeFE/element#16725]
### Element UI version
2.10.1

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1. 打开网址 https://codepen.io/pen/?&editable=true
2. 在el-select 标签写入size="mini"。如代码： 
```html
<el-select v-model="value" placeholder="请选择" size="mini">
```
3. 可以看到样式 .el-scrollbar__view.el-select-dropdown__list 的下拉框（就是 el-option) 中字体(font-size)并没有跟随 size 变化。

### What is Expected?
el-option 中字体(font-size)跟随 size 变化

### What is actually happening?
el-option 中字体(font-size)并没有跟随 size 变化

**Comment by krnan9525** [comment]
I think the codepen link you provided is wrong

**Comment by luocong2016** [comment]
```html
<el-select v-model="value" placeholder="请选择" size="mini">
```
可以看到样式 .el-scrollbar__view.el-select-dropdown__list 的下拉框（就是 el-option) 中字体(font-size)并没有跟随 size 变化。
