### ISSUE TITLE
[Bug Report] el-image lazy load not work in vue cli 3.0

### ISSUE THREAD

**Issue by SeanSure** [ElemeFE/element#16729]
### Element UI version
2.10.1

### OS/Browsers version
new 

### Vue version
2.6.10

### Reproduction Link
I can't create in jsfiddle

### Steps to reproduce
el-image lazy load not work in vue cli 3.0

### What is Expected?
el-image lazy load can work in vue cli 3.0

### What is actually happening?
el-image lazy load not work in vue cli 3.0

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
