### ISSUE TITLE
[Feature Request] Request to join a Drawer, such as the Drawer in iviewui

### ISSUE THREAD

**Issue by loveXS** [ElemeFE/element#16734]
### Existing Component
否

### Component Name
Drawer

### Description
Elementui does not have drawer components, so I hope you can contribute some money to it

**Comment by JeremyWuuuuu** [comment]
We have already added a `Drawer`, refer to: https://github.com/ElemeFE/element/pull/16577
If you have any bug or question, please feel free to file an issue

**Comment by loveXS** [comment]
Thank you for your hard work.



------------------ 原始邮件 ------------------
发件人: "jeremywu"<notifications@github.com>; 
发送时间: 2019年7月25日(星期四) 下午4:15
收件人: "ElemeFE/element"<element@noreply.github.com>; 
抄送: "ツスピタ"<768484525@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ElemeFE/element] [Feature Request] Request to join a Drawer,such as the Drawer in iviewui (#16734)




We have already added a Drawer, refer to: #16577
 If you have any bug or question, please feel free to file an issue
