### ISSUE TITLE
[Bug Report] el-date-picker type datetime, selection time and seconds can not be clicked, sliding can be, but can not be accurately selected

### ISSUE THREAD

**Issue by htmlzhoyan** [ElemeFE/element#16732]
### Element UI version
2.10.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
拉取el-date-picker组件并选择 type = datetime  后，选择时分秒无法点击选择，滑动是可以，但是无法精确选择。
https://codepen.io/pen/?&editable=true 可以在官网在线运行，查看。

### What is Expected?
选择时分秒时可以点击选择

### What is actually happening?
选择时分秒时无法点击。

**Comment by gentlecoder** [comment]
https://codepen.io/gentlecoder/pen/gVMzpg
可以的呀

**Comment by jerecui** [comment]
> https://codepen.io/gentlecoder/pen/gVMzpg
> 可以的呀
如果value-format 是yyyy-MM-dd'T'HH:mm:ss　则会出现这样的问题。
比如
```javascript
 <el-date-picker v-model="value1" type="datetime" placeholder="选择日期" value-format="yyyy-MM-dd'T'HH:mm:ss">
```
这样是失败的。

2.8.2版本是好的，自 2.9.0 版本开始不支持。

**Comment by htmlzhoyan** [comment]
> https://codepen.io/gentlecoder/pen/gVMzpg
> 可以的呀
我是用谷歌浏览器打开，还是无法点击选择时分秒，只能滑动选择

**Comment by htmlzhoyan** [comment]
> > https://codepen.io/gentlecoder/pen/gVMzpg 
> > 可以的呀
> 
> 如果值格式是YYYY-MM-dd'T'HH：MM：SS则会出现这样的问题。
> 比如
> 
> ```js
>  < el - date - picker v - model = “ value1 ” type = “ datetime ” placeholder = “选择日期” value - format = “ yyyy-MM-dd'T'HH：mm：ss ” >
> ```
> 
> 这样是失败的。
> 
> 2.8.2版本是好的，自2.9.0版本开始不支持。

我的是 value-format="yyyy-MM-dd HH:mm:ss" 时，不过，即使我去掉了，也依旧无法通过点击获取时分秒，我用的是谷歌浏览器打开的，不知道是不是浏览器的问题

**Comment by ziyoung** [comment]
无法重现。

**Comment by jerecui** [comment]
> 无法重现。

https://codepen.io/jerecui/pen/Vobxgg

**Comment by IRoye** [comment]
遇到类似问题了，el-date-picker时间中的hour点击无效。测试环境中一直没有出现，生产环境中出现了。其次，input编辑hour， 编辑完成，最后还是回到编辑前的时间。
这个一般情况下还真的不好重现。
@ziyoung

**Comment by creanme** [comment]
Edge dev 78.0.249.1 版遇到了其它的问题，滚动到23时的时候，会自动回到20时。不过把浏览器分辨率从1920*1080 缩小一些，就正常了。
![2333](https://user-images.githubusercontent.com/11664505/63582410-9a57f780-c5cb-11e9-883a-e61e0ffeb2e9.gif)
