### ISSUE TITLE
树状下拉菜单，或者导航式的下拉菜单

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#1673]
在现有的控件基础上可以组合实现吗？希望增加。

**Comment by Leopoldthecoder** [comment]
类似于这个吗？https://fe-driver.github.io/vue-beauty/#!/components/treeSelect

**Comment by jixzfw** [comment]
是的。
当然，其实想想，单选的需求下，也可以是级联菜单的表现https://fe-driver.github.io/vue-beauty/#!/components/cascader

**Comment by Leopoldthecoder** [comment]
TreeSelect 和 Cascader 分别在 #76 和 #271 中提出，我们会考虑。请关注这两个 issue。

**Comment by fengyun2** [comment]
这个功能2.x版本也还没计划做么？管理后台经常需要用到这个功能。

**Comment by ayiaq1** [comment]
https://github.com/ayiaq1/el-tree-select 刚好3.0版本升级，基于element-ui
