### ISSUE TITLE
[Bug Report] Vue Cli3 import element on demand, failed to import CSS on demand because of only one index.css in download zip

### ISSUE THREAD

**Issue by unssnu** [ElemeFE/element#16741]
### Element UI version
2.10.1

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.6.10

### Reproduction Link
http://www.jsfiddle.com

### Steps to reproduce
In previous version of Online Theme, the CSS in the download theme package was be separated and named based on each component's name.
 
But in the new Online Theme, just one index.css files in the download zip, so import element as on demand will failed to find the CSS module.

Would u please kindly help on this issue? thanks.......

### What is Expected?
CSS  can be import on demand

### What is actually happening?
failed to find the CSS modules

**Comment by ziyoung** [comment]
not element-ui bug.
