### ISSUE TITLE
[Bug Report] el-table fixed column postion error

### ISSUE THREAD

**Issue by chinaxy** [ElemeFE/element#16748]
### Element UI version
2.10.0

### OS/Browsers version
win10 x64 1903 chrome 75 

### Vue version
2.6.10

### Reproduction Link
https://github.com/chinaxy/element-ui-bug-repo

https://codesandbox.io/s/vue-template-jwx5u

### Steps to reproduce
npm i

npm run serve

use chrome to access http://localhost:4000

### What is Expected?
the selection button and data columns in the same line

### What is actually happening?
the selection button and data columns not in the same line

2.9.2 not found this bug

**Comment by ziyoung** [comment]
@chinaxy please use codesandbox or codepen.

**Comment by chinaxy** [comment]
updated reproduction Link @ziyoung
