### ISSUE TITLE
[Bug Report] Version 2.11.0, server rendering window is not defined

### ISSUE THREAD

**Issue by OrangeXC** [ElemeFE/element#16743]
### Element UI version
2.11.0

### OS/Browsers version
Chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://github.com/OrangeXC/n2ex

### Steps to reproduce
1.克隆 https://github.com/OrangeXC/n2ex

2.升级 element-ui 至 2.11.0

3.npm run dev

### What is Expected?
正确渲染网站，因为 2.10.1 完全正常，可以参考

### What is actually happening?
window is not defined

**Comment by iamkun** [comment]
fixed in 2.11.1
