### ISSUE TITLE
[Bug Report] Message message prompt component

### ISSUE THREAD

**Issue by JingGeGe77** [ElemeFE/element#16756]
### Element UI version
2.11.0

### OS/Browsers version
Google Chrome 版本 70.0.3538.77（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jinggege77/pen/KOgZLr?&editable=true

### Steps to reproduce
不断点击打开消息提示，message消息提示会从上往下排列，然后自动依次消失。（element-ui 2.9.2 版本之后会出现这个情况）
之前的版本是后面的消息提示会覆盖前面的消息提示

### What is Expected?
希望有个属性控制是否覆盖还是依次排列显示消息

### What is actually happening?
message消息提示会从上往下排列，然后自动依次消失。

**Comment by 15050050972** [comment]
我遇到了相似的问题
只不过不是完全重叠的，而是这样的，版本2.10.0
![image](https://user-images.githubusercontent.com/23148429/62120654-9995b380-b2f4-11e9-805a-d0a158cab6d8.png)

**Comment by ziyoung** [comment]
相关 pr #15639
