### ISSUE TITLE
When [Bug Report] Cascader switches a parent, if a parent has no subordinate, it still displays the parent of the last switch.

### ISSUE THREAD

**Issue by penjay** [ElemeFE/element#16762]
### Element UI version
2.11.0

### OS/Browsers version
MacOS mojave 10.14.6 / Chrome  75.0.3770.142 x64

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/penjay/pen/xvEJbP

### Steps to reproduce
选择一级a，二级展示为a-1,a-2
选择一级b,  b没有二级，仍显示为a-1,a-2

### What is Expected?
选择一级b,  b没有二级，不弹出下级或二级panel为“暂无数据”

### What is actually happening?
选择一级b,  b没有二级，仍显示为a-1,a-2

**Comment by penjay** [comment]
经过测试，添加leaf属性并按实际设置可以避免此情况，但实际业务中，一般只有使用父级id请求后台才知道下级是否为空。

**Comment by luckyCao** [comment]
@penjay 提供一下可以复现的事例链接，现在页面上这个打开并不是 cascader 的事例

**Comment by uncleLian** [comment]
> 经过测试，添加叶属性并按实际设置可以避免此情况，但实际业务中，一般只有使用父级ID请求后台才知道下级是否为空。

遇到同样问题，但cascader使用hover模式下，你这个方法并没有解决我的问题。hover到没有子节点的元素上，始终显示最后一次拥有子节点的面板。
期待预期：没有子节点的不显示面板
