### ISSUE TITLE
如何得到Dialog的实例？

### ISSUE THREAD

**Issue by dearbird** [ElemeFE/element#1676]
> 此外我们还为 Dialog 实例提供了open和close方法，可以通过调用它们来打开/关闭 Dialog

请问如何得到Dialog的实例？

**Comment by Leopoldthecoder** [comment]
参考 Vue 文档中 `ref` 相关内容：https://vuejs.org/v2/api/#ref

在模板中：
```html
<el-dialog ref="dialog">
```
之后就可以访问到它的实例：
```javascript
this.$refs.dialog.open()
```
