### ISSUE TITLE
[Bug Report] The bug for tree (drag-and-drop problem in tree component lazy mode)

### ISSUE THREAD

**Issue by cjfff** [ElemeFE/element#16765]
### Element UI version
2.10.1

### OS/Browsers version
windcows/chorme/版本 75.0.3770.142（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/anon/pen/zgKbwE

### Steps to reproduce
1. 首先打开上面的官方连接~~
2. 然后点开几个 tree lazy 出节点，再直接拖动到 tree 顶部
3. 此时刚刚拖动的 tree 节点消失了，控制台还出现错误警告

### What is Expected?
1. 跟普通模式一样，正常拖拽......

### What is actually happening?
1. 被拖拽的树节点消失，然后出现了错误警告
2. 报错信息为 
 vue.js:1897 TypeError: Cannot read property 'indexOf' of undefined
    at e.insertChild (index.js:1)
    at e.insertBefore (index.js:1)

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/13080#issuecomment-433780301
