### ISSUE TITLE
[Bug Report] el-table-column is executed many times

### ISSUE THREAD

**Issue by XueMary** [ElemeFE/element#16766]
### Element UI version
2.11.1

### OS/Browsers version
macos chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xuejihong/pen/OKReZJ

### Steps to reproduce
打开控制台查看输出 “多次执行” 文案的次数就可以了

### What is Expected?
期待是输出4次

### What is actually happening?
实际输出了8次

**Comment by ivila** [comment]
@XueMary  因为你有个fixed，el-table的fixed是通过多table来实现的。

**Comment by XueMary** [comment]
> @XueMary 因为你有个fixed，el-table的fixed是通过多table来实现的。

那这样组件就会被加载多个，如果组件内部有setInterver那么期望的结果会超出预期
