### ISSUE TITLE
[Datepicker] Popover with a datepicker, close when selecting a date

### ISSUE THREAD

**Issue by stefanosandes** [ElemeFE/element#1677]
### ElementUI version
1.0.6

### OS/Browers version
Windows/Chrome 55

### Vue version
2.1.4

### Reproduction Link
https://jsfiddle.net/stefanosandes/gmve9d3p/91/

### Steps to reproduce
Select a date in datepicker.
### What is Expected?
Popover should stay open, like when you select an option in el-select
### What is actually happening?
Popover close

**Comment by nightmareT** [comment]
解决了吗 为啥我现在还有这个问题
