### ISSUE TITLE
[Bug Report] el-tree adds multi-level subitems without scrollbars, is it bug or can it be optimized

### ISSUE THREAD

**Issue by parchments** [ElemeFE/element#16771]
### Element UI version
2.11.0

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://element.eleme.cn/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong

### Steps to reproduce
https://element.eleme.cn/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong
不断点击追加按钮时
会溢出

### What is Expected?
有对应优化的行为，例如滚动条或者其他方式

### What is actually happening?
有对应优化的行为，例如滚动条或者其他方式

**Comment by ziyoung** [comment]
无法重现。
