### ISSUE TITLE
[Bug Report] el-drawer's close button has blue border when press it

### ISSUE THREAD

**Issue by laiiihz** [ElemeFE/element#16778]
### Element UI version
2.11.1

### OS/Browsers version
Windows / chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/laiiihz/pen/vogmyy

### Steps to reproduce
After the Drawer is opened, click the close button in the upper right corner, it display a blue border. Other components such as the Dialog's close button do not have a border.

### What is Expected?
After the new component Drawer is opened, click the close button in the upper right corner should have no border.

### What is actually happening?
After the new component Drawer is opened, click the close button in the upper right corner display a blue border.

**Comment by JeremyWuuuuu** [comment]
This was intentional due to the `a11y A.K.A. accessibility`,  try to move the cursor on Github with your tab key, you can also see the highlighted area which indicates where you are focusing.
