### ISSUE TITLE
[Bug Report] Drawer, a new component, has a small problem: the default value of the appendToBody attribute in the document is false, but the default value in the code is true, the modal-append-to-body attribute in the document is not working well, it seems that the props in the code is not received.

### ISSUE THREAD

**Issue by Minions51390** [ElemeFE/element#16783]
### Element UI version
2.11.1

### OS/Browsers version
Chrome 69.0.3497.92

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/minions51390/pen/aepEpj

### Steps to reproduce
点击按钮，设置modal-append-to-body属性为false后发现dom依然被append到了body里面，
这个链接里面我没有设置append-to-body属性，按照文档上说明append-to-body默认值为false，那么drawer的dom应该被append到class名为drawer-wrapper的div下面但是依旧被append到body下面。

### What is Expected?
设置modal-append-to-body属性为false后，dom会被添加到Drawer 的父元素上。
不设置append-to-body属性，dom会被添加到Drawer 的父元素上。

### What is actually happening?
modal-append-to-body属性好像没有生效。
不设置append-to-body属性，dom会被添加body上面。

**Comment by cuevven** [comment]
The modal and modal-append-to-body attributes don't work.

**Comment by ziyoung** [comment]
@JeremyWuuuuu 看一下。

**Comment by JeremyWuuuuu** [comment]
@ziyoung  Got it.

**Comment by JeremyWuuuuu** [comment]
@Minions51390 @cuevven It's a bug, which will be fixed @ next release. I am so sorry for the bug.

**Comment by Minions51390** [comment]
@JeremyWuuuuu 辛苦修复，超喜欢elementUI，很棒很棒的组件库~

**Comment by JeremyWuuuuu** [comment]
@Minions51390 感谢!

**Comment by JeremyWuuuuu** [comment]
#16953 
You can watch this PR to track the process.
PR 已提
