### ISSUE TITLE
[Bug Report] When el-input is used in the el-form and the show-word-limit property is added, the Numbers overflow

### ISSUE THREAD

**Issue by monkeycf** [ElemeFE/element#16784]
### Element UI version
2.8.2

### OS/Browsers version
Window10/Chrome75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/CHENSENRAN/pen/PMWOVv

### Steps to reproduce
在el-form中使用el-input，并且添加 show-word-limit 属性，设置el-input的size属性为mini。

### What is Expected?
统计字数的数字可以正确的显示在文本框内部。

### What is actually happening?
统计字数的数字溢出文本框，并且遮挡文本框边框。

**Comment by LilyWakana** [comment]
这个已经修改了，更新一下版本应该就可以了

**Comment by monkeycf** [comment]
更新到最新版本后，问题解决了。Thank you!
