### ISSUE TITLE
[Feature Request] Tree Data Problem on el-table

### ISSUE THREAD

**Issue by Drheng** [ElemeFE/element#16782]
### Existing Component
是

### Component Name
el-table

### Description
el-table的树形数据，目前默认的展开/收起的切换icon是在默认的第一个type为default的column上。
现有需求需要置于其他列。
希望能够添加table的配置字段，用于配置切换icon的列位置。
若不行，不知能否提供其他解决方案。

**Comment by liuchihanxiang** [comment]
我提了这个需求他们说暂时不打算做这个，不过当前版本是可以实现的，就是你手动把前几列都设置为type不为default，这个是示例  你可以参考下
https://codepen.io/liuchihanxiang/pen/NQqKvv

**Comment by Drheng** [comment]
@liuchihanxiang 谢谢哈。这个方法试过了，一般情况下没问题。
我看了下代码，cell在渲染的时候记录了一个defaultIndex，通过这个下标去实现的icon渲染。
但我这边有动态隐藏/显示列的需求，切换的时候，defaultIndex都不会更新，┑(￣Д ￣)┍。

**Comment by liuchihanxiang** [comment]
@Drheng   源码是firstDefaultColumnIndex决定的第几列  是通过计算属性计算出来的 ，理论上隐藏的话应该会更新吧 ，改变列了应该会重新计算才对呀，回头我试试！！ 其实这个属性我觉得开放出来更好 ，这种需求还是蛮多的。

**Comment by Drheng** [comment]
@liuchihanxiang 嗯，我在dev-tool里调试，隐藏列后columns的数据是变了，但是里面type字段不对。
例如第一列{name: 1, type:index}，第二列{name:2, type:default}。
隐藏第一列columns里只剩下 {name:2, type:index}。有点神奇。
隐藏列我是通过v-if去实现的，不知道换个思路：把el-column-item用v-for遍历出来，改变数据去隐藏列能不能解决。

**Comment by xlz26296** [comment]
@Drheng 如果非要支持列位置你可以看下这个 https://jsrun.pro/B6bKp/edit

**Comment by Drheng** [comment]
@xlz26296 好的谢谢
