### ISSUE TITLE
2.11.0 的Drawer，我建议允许去掉header的部分，不然展开的时候，上面空的太多，只能写一个title，太可惜了！

### ISSUE THREAD

**Issue by LamTech** [ElemeFE/element#16792]
<img width="556" alt="1" src="https://user-images.githubusercontent.com/46949682/62055606-89c39400-b24e-11e9-9130-a2802b2f30d4.png">

如图，那么大的位置，只能写title，太可惜了。

**Comment by JeremyWuuuuu** [comment]
This can be modified by css, you can adjust the margin, padding value yourself. It is a good idea that we leave everything to the user so that they can implementing everything themselves.
这个可以通过 css 来修改 margin/padding. 
但这的确是一个好主意让用户自己来控制里面所展示的内容. 后续会持续跟进

**Comment by LamTech** [comment]
> This can be modified by css, you can adjust the margin, padding value yourself. It is a good idea that we leave everything to the user so that they can implementing everything themselves.
> 这个可以通过 css 来修改 margin/padding.
> 但这的确是一个好主意让用户自己来控制里面所展示的内容. 后续会持续跟进

多谢，我确实就采用了css的方式，间接取消了header。
