### ISSUE TITLE
When the preview of [Bug Report] el-image scales with the direction key_, it is recommended to provide a scrollbar method to shield the page.

### ISSUE THREAD

**Issue by penjay** [ElemeFE/element#16796]
### Element UI version
2.11.1

### OS/Browsers version
macOS mojave

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
el-image 的 preview 在使用方向键↑↓进行缩放时，建议提供屏蔽页面的滚动条方法。

### What is Expected?
使用方向键缩放时页面不会滚动

### What is actually happening?
使用方向键缩放时页面会滚动

**Comment by zuibunan** [comment]
same problem

**Comment by yingc888** [comment]
修改后的2.13版本大图预览不显示，必须先滑动；官网文档中的大图预览示例chrome、IE11都不可预览https://element.eleme.cn/2.13/#/zh-CN/component/image

**Comment by yiling-e0** [comment]
2.13版本大图预览可以esc关闭，再次打开后esc失效
