### ISSUE TITLE
[Bug Report] cascader clearable

### ISSUE THREAD

**Issue by junfachen** [ElemeFE/element#16794]
### Element UI version
2.11.0

### OS/Browsers version
Google Chrome75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1.选择任意选项
2.点击关闭按钮
3.点击选择框

### What is Expected?
控件回滚最初未选择的状态

### What is actually happening?
控件某些样式/值未回滚
多选同理

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
