### ISSUE TITLE
[Bug Report] el-tree - - - checkbox style bug

### ISSUE THREAD

**Issue by liaojw** [ElemeFE/element#16795]
### Element UI version
2.11.1

### OS/Browsers version
Mac OS /Google Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/o31t59sf/

### Steps to reproduce
el-tree组件，复选状态下，复选框与文字之前的空隙没有连，连在一起了！

### What is Expected?
期待出紧急小版本修复！

### What is actually happening?
期待出紧急小版本修复！

**Comment by languanghao** [comment]
```
.el-tree-node__content {
  .el-checkbox {
    margin-right: 8px;
  }
}
```
