### ISSUE TITLE
[Bug Report] el-input location error

### ISSUE THREAD

**Issue by zhiguoxu** [ElemeFE/element#16807]
### Element UI version
2.11.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhiguo/pen/GVWXPR

### Steps to reproduce
   两个 el-input，加了 append slot 之后，位置就会对不齐，如下图
![image](https://user-images.githubusercontent.com/31875256/62124017-cac5b200-b2fb-11e9-83d2-510b5654e375.png)
代码如下
   `<div>
      <el-input value="123" style="width:120px;">
          <el-button slot="append">{</el-button>
      </el-input>
      <el-input style="width:120px;">
        <el-button slot="append">{</el-button>
      </el-input>
    </div>` 

### What is Expected?
希望能对齐两个控件

### What is actually happening?
两个控件上下对不齐

**Comment by krnan9525** [comment]
Just wrap these two elements in a <div> and make it a flexbox.

**Comment by zhiguoxu** [comment]
flex is ok, thanks

**Comment by zhiguoxu** [comment]
ok, thanks!

At 2019-07-30 22:31:21, "Mark Yang" <notifications@github.com> wrote:


Just wrap these two elements in a

and make it a flexbox.
