### ISSUE TITLE
[Bug Report]The add animation of the tag component is invalid

### ISSUE THREAD

**Issue by bot960528** [ElemeFE/element#16801]
### Element UI version
2.11.1

### OS/Browsers version
Google Chrome 版本 75.0.3770.142（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/A3m0n/pen/NQpaxg

### Steps to reproduce
2.11.0 版本，我现在在使用 tag 组件，在看文档的时候，这里：
https://element.eleme.cn/2.11/#/zh-CN/component/tag#dong-tai-bian-ji-biao-qian
动态编辑标签，在删除和添加的时候都有动画效果，但当我自己使用的时候却只有删除标签的时候又动画效果，添加的时候却没有。
在右下角的 codepen 中也是如此。

我复制了文档中的[实例代码](https://codepen.io/A3m0n/pen/NQpaxg)，但是无法完全复现文档中的演示效果。

### What is Expected?
tag 在添加和删除时会有动画效果。

### What is actually happening?
tag 只在删除的时候会有动画效果，在添加的时候没有。

**Comment by monkeycf** [comment]
在Vue@2.6.10中重现了问题，修改Vue版本为2.6.8即可实现期望的效果。
Vue@2.6.8例子：https://codepen.io/CHENSENRAN/pen/JgWqpg

**Comment by bot960528** [comment]
> 在Vue@2.6.10中重现了问题，修改Vue版本为2.6.8即可实现期望的效果。
> Vue@2.6.8例子：https://codepen.io/CHENSENRAN/pen/JgWqpg

谢谢，已经按此方法解决问题！
