### ISSUE TITLE
[Bug Report] Tree tree component is false in accordion, still broadcasts tree-node-expand events, and has performance problems with a large number of nodes

### ISSUE THREAD

**Issue by thesadboy** [ElemeFE/element#16819]
### Element UI version
2.11.1

### OS/Browsers version
Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/packages/tree/src/tree.vue

### Steps to reproduce
渲染一个一级大量节点（如400 ）的树，子级通过远程获取，展开某个节点，会卡死，tree.vue tree-node.vue 文件中，均有该逻辑

### What is Expected?
在accordion为false时，不需要广播tree-node-expand事件

### What is actually happening?
在accordion为false时，广播tree-node-expand事件

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
