### ISSUE TITLE
[Feature Request] el-table sort-change needs to distinguish between user clicks and default-sort

### ISSUE THREAD

**Issue by lightning0016** [ElemeFE/element#16814]
### Existing Component
是

### Component Name
el-table

### Description
对element ui封装后,用户点表头触发sort-change中会执行查询,而default-sort触发sort-change是不需要查询的,缺个prop区分

**Comment by ziyoung** [comment]
@lightning0016 提供一个 demo 描述你的问题。

**Comment by lightning0016** [comment]
这个问题与https://github.com/ElemeFE/element/issues/11966相似,解决其中一个,即可解决项目bug
描述: 
列表显示时不查询,点击排序时,会执行查询,但是如果有默认排序,会触发排序,也就会走查询,因为没法区分.
