### ISSUE TITLE
[Feature Request] checkbox-group value bound object array

### ISSUE THREAD

**Issue by tianyong90** [ElemeFE/element#16812]
### Existing Component
是

### Component Name
checkbox-group

### Description
希望 checkbox-group 能像 el-select 一样使用 v-model 双向绑定对象数组。目前 checkbox-group 虽然可能用对象数组，但似乎是单向绑定。也就是说可以收 checked 状态去修改绑定值，但绑定的值却没法确定复选框的选中状态。
 el-select 中有一个 value-key 属性，感觉 el-checkbox-group 应该也可以实现它。

**Comment by overtrue** [comment]
We also have this request:

https://github.com/ElemeFE/element/issues/10925
https://github.com/ElemeFE/element/issues/5864
https://github.com/ElemeFE/element/issues/9890
https://github.com/ElemeFE/element/issues/6351

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by prd-y-nguyen** [comment]
There's a solution for this, we can create a new component extends from ElCheckBox the code below:
The code below just replace the compare part by lodash isEqual to compare between objects
```
// new-el-checkbox.vue
<script>
import { defineComponent } from '@vue/composition-api'
import { Checkbox } from 'element-ui'
import _isEqual from 'lodash/isEqual'

// Now support array of object by adding _isEqual to compare the values
// Specify the value of checkbox with 'label' prop, not 'value' prop
export default defineComponent({
  extends: Checkbox,
  computed: {
    // eslint-disable-next-line vue/return-in-computed-property
    isChecked() {
      if ({}.toString.call(this.model) === '[object Boolean]') {
        return this.model
      } else if (Array.isArray(this.model)) {
        return this.model.find((item) => _isEqual(item, this.label))
      } else if (this.model !== null && this.model !== undefined) {
        return this.model === this.trueLabel
      }
    },
  },
  methods: {
    addToStore() {
      if (Array.isArray(this.model)) {
        const isExisted = this.model.find((item) => _isEqual(item, this.label))
        if (!isExisted) this.model.push(this.label)
      } else {
        this.model = this.trueLabel || true
      }
    },
  },
})
</script>

```
We now can use it:
```
<el-checkbox-group v-model="selected">
  <new-el-checkbox v-for="item in items" :label="item">
    {{ item.name }}
  </new-el-checkbox>
</el-checkbox-group>
```
**!!! Note that you must override the checkbox label using slot `{{item.name}}` because checkbox has label-based value and it will display the ugly object on the screen**
