### ISSUE TITLE
[Bug Report] Use dynamic Tags (ELTag) in Vue of 2.6.9 version or above, add tags has no dynamic effect.

### ISSUE THREAD

**Issue by monkeycf** [ElemeFE/element#16810]
### Element UI version
2.11.1

### OS/Browsers version
 window10/Chrome75.0

### Vue version
2.6.9

### Reproduction Link
https://codepen.io/CHENSENRAN/pen/NQpZEm

### Steps to reproduce
在2.6.9及以上版本的Vue中使用ElementUI动态编辑标签。(Vue版本2.6.8及以下没有此问题）
Element UI 官方文档链接：https://element.eleme.cn/?#/zh-CN/component/tag#dong-tai-bian-ji-biao-qian

### What is Expected?
在添加关闭标签时，可以有动画效果。

### What is actually happening?
只有关闭标签时有动画效果，在添加标签时没有动画效果。

**Comment by ziyoung** [comment]
这里有一个更简单的例子。https://codepen.io/ziyoung/pen/bXrxMZ
看了一下 changelog 也没啥特别的。我再排查一下。

**Comment by ziyoung** [comment]
跟这个 pr 有关 https://github.com/vuejs/vue/pull/9668
