### ISSUE TITLE
[Bug Report] Fixed column table is not aligned when scrolling.

### ISSUE THREAD

**Issue by Allenice** [ElemeFE/element#16815]
### Element UI version
2.11.1

### OS/Browsers version
mac os 14.4 / chrome 74 

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/allenice/pen/gVWxbQ

### Steps to reproduce
表格第一列固定，设置表格的宽度和高度使其可以垂直滚动。

The first column of the table is fixed, setting the width and height of the table so that it can scroll vertically.

（element ui versin: 2.9.2 ~ 2.11.1 ）

### What is Expected?
滚动的时候，固定列的边框和不固定列的边框应该要对齐

When scrolling, the border of the fixed column and the border of the unfixed column should be aligned

### What is actually happening?
滚动的时候，固定列的边框和不固定列的边框不对齐

When scrolling, the border of the fixed column and the border of the unfixed column are not aligned

**Comment by ziyoung** [comment]
与 table 的固定列实现有关。固定类的滚动会稍微有些延迟。

**Comment by Allenice** [comment]
v2.9.2 之前固定列滚动的时候都不会出现这个问题，2.9.2 之后就出现了，滚动的时候一抖一抖的

**Comment by Allenice** [comment]
这个问题不修复吗？

**Comment by yulin92** [comment]
大哥，这个问题修复了吗
