### ISSUE TITLE
[Bug Report] 2.11.1 bug on ie11

### ISSUE THREAD

**Issue by j5272000** [ElemeFE/element#16822]
### Element UI version
2.11.1

### OS/Browsers version
win10 ie11

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/eqWQWw#anon-signup

### Steps to reproduce
element-ui\src\utils\resize-event.js
这个js中的第7行在ie11中报错：
     for (let entry of entries) {

### What is Expected?
希望处理好

### What is actually happening?
希望处理好

**Comment by j5272000** [comment]
import { addResizeListener, removeResizeListener } from 'element-ui/src/utils/resize-event'
只要引入了这个js，ie11就报错了

**Comment by lianzhao** [comment]
`import { addResizeListener, removeResizeListener } from 'element-ui/lib/utils/resize-event'`
把src改成lib

**Comment by j5272000** [comment]
可以了，多谢
