### ISSUE TITLE
[Feature Request] MessageBox pop-up location suggestion

### ISSUE THREAD

**Issue by TakeEasyBoy** [ElemeFE/element#16820]
### Existing Component
Yes

### Component Name
Message

### Description
v2.11.2 现有逻辑下,如果连续点击按钮触发messagebox,会出现messagebox一直往下重叠;不知是设计如此还是怎样?
![image](https://user-images.githubusercontent.com/31021942/62198071-8dbcf680-b3b3-11e9-8dc4-8ef84f93f7b2.png)

v2.8.2,messagebox只在相同位置出现,并不会按照现有逻辑一直叠加;
![image](https://user-images.githubusercontent.com/31021942/62197969-66fec000-b3b3-11e9-97ba-eef80790fe01.png)
建议:是否可以增加一个option 用来确定messagebox的出现位置,

**Comment by xrkffgg** [comment]
https://github.com/ElemeFE/element/pull/15639
