### ISSUE TITLE
[Bug Report] el-autocomplete trigger-on-focus twice

### ISSUE THREAD

**Issue by obligat** [ElemeFE/element#16825]
### Element UI version
2.11.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/obligat/pen/MNmZEj?&editable=true

### Steps to reproduce
focus 输入框，然后 blur, 然后在 focus, 会先弹一下上一次的搜索list，再 loading，再展示接口返回的。

### What is Expected?
focus 时不弹上一次的 搜索list。
可以参考 http://www.imooc.com/wenda/detail/425383 这篇文章。

### What is actually happening?
 弹了上次的 搜索list。

**Comment by nullptru** [comment]
Pr welcome
