### ISSUE TITLE
希望InputNumber的change回调可以加上oldValue参数

### ISSUE THREAD

**Issue by Tickly** [ElemeFE/element#1682]
### ElementUI version

1.0.5
### OS/Browers version

macOS/Chrome 53
### Vue version

2.1.0
### What is Expected?
希望在InputNumber的回调change里面可以再加上一个之前的值的参数，即 change(oldValue,newValue)
因为有时候需要验证新的值是否被允许，但又不能通过min跟max去限制。
这样在change里面我可以根据newValue去判断是否符合要求，不符合我可以重新设置为oldValue

**Comment by flyingzl** [comment]
两种方法，直接将el-input放在el-form里面，设置校验规则。再者就是如果你想获取old值， 直接watch吧
