### ISSUE TITLE
[Bug Report] dataset in el-button element not effective in some cases

### ISSUE THREAD

**Issue by llqgit** [ElemeFE/element#16836]
### Element UI version
2.11.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/llq/pen/RXgrZY

### Steps to reproduce
1. 点击按钮空白处，能获取到按钮上的 dataset 内容
2. 点击按钮文字处，不能够获取到按钮上的 dataset 内容

问题就在于第 2 点

### What is Expected?
点击按钮文字处（按钮的 child SPAN）也能够获取到按钮上的 dataset

### What is actually happening?
点击按钮文字处，不能够获取到按钮上的 dataset 信息

**Comment by xrkffgg** [comment]
兄弟，你例子 已经找到了 方法解决，可以提个 PR 那😛

**Comment by luckyCao** [comment]
pr welcome
