### ISSUE TITLE
[Bug Report] Optimize the cursor style when the input is readonly

### ISSUE THREAD

**Issue by xrkffgg** [ElemeFE/element#16833]
### Element UI version
2.11.1

### OS/Browsers version
windows/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xrkffgg/pen/OKgPbd?&editable=true

### Steps to reproduce

see it Immediately

直接看到

### What is Expected?

鼠标显示 为 正常 

### What is actually happening?

鼠标显示 为 输入

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.
