### ISSUE TITLE
el-calendar doesn't work well with timezone. 

### ISSUE THREAD

**Issue by moov-nikola** [ElemeFE/element#16835]
https://elementui.github.io/issue-generator does not work. No link can pass "Reproduction Link
"'s validation.

Steps to reproduce:
===============
Set time zone to -7 ( US, Los Angeles )

At local time 10am

Go to https://element.eleme.io/#/en-US/component/calendar

Click "today" on a calendar

What is Expected?
=============
The correct day is highlighted.

What is actually happening?
=====================
The previous day is highlighted.

Analysis:
========
Fundamentally, this is what happened inside https://github.com/ElemeFE/element/blob/dev/src/utils/date.js 

a = new Date("2018-08-01");
Tue Jul 31 2018 17:00:00 GMT-0700 (Pacific Daylight Time)

// then:

a.toString()
"Tue Jul 31 2018 17:00:00 GMT-0700 (Pacific Daylight Time)"

**Comment by C0deZLee** [comment]
Same here, can't believe this is still not solved
