### ISSUE TITLE
[Feature Request] el-calendar has practical value

### ISSUE THREAD

**Issue by richwxd** [ElemeFE/element#16839]
### Existing Component
是

### Component Name
el-calendar

### Description
可以自定义按日期，月视图，
可以自由选择年，月
可以传入绑定数据
单元格可以显示自定义内容
单元格可以自设背景色，如某些厂家是单休，通过数据中的属性，如果是休息日，可以动态指定单元格背景色为灰色
点击选中和再次点击取消选中

**Comment by nullptru** [comment]
Pr welcome
