### ISSUE TITLE
[Feature Request] Remove Input box from slider

### ISSUE THREAD

**Issue by lianzhao** [ElemeFE/element#16837]
### Existing Component
Yes

### Component Name
slider

### Description
The Slider component has an attribute `show-input` to show an input box, which is a "鸡肋" (which means that it is only KIND OF helpful...).

Here are my points:
1. The InputNumber's API was not fully exposed via the Slider's API. For example, user can not set InputNumber's `controls-position` attribute via the Slider's API.
2. If a user want both of Slider & InputNumber, he can just implemented it by himself...

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
