### ISSUE TITLE
[Bug Report] The cursor of the Tree component display inappropriate

### ISSUE THREAD

**Issue by xrkffgg** [ElemeFE/element#16830]
### Element UI version
2.11.1

### OS/Browsers version
windows/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xrkffgg/pen/oKwNaZ

### Steps to reproduce
EN： 

1、Expand all node

2、Mouse movement the last evel

3、You can see it

CN ： 

1、点开所有节点

2、鼠标移动在最后一个层级

3、直接看到了

### What is Expected?
style of the cursor can be consistent

鼠标的样式保持一致

### What is actually happening?
style of the cursor has changes

鼠标的样式发生改变

图例：

![before](https://github.com/xrkffgg/img/blob/master/element/tree-icon.gif?raw=true)

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
