### ISSUE TITLE
[Bug Report] how to implement v-model for el-select in Msgbox

### ISSUE THREAD

**Issue by BigSaltyFish** [ElemeFE/element#16849]
### Element UI version
2.11.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/zuLwa845/1/

### Steps to reproduce
Click the button in the page, then the message box will pop up. Try to select an item.

### What is Expected?
The item should appear in the select box, and be highlighted in the list.

### What is actually happening?
Nothing happened visually. I have checked the value in the vue instance, which prove to be correctly altered. However, the selector doesn't render it.

**Comment by BigSaltyFish** [comment]
This may not be a bug, but i didn't find the way to tackle it in element's doc or vue's doc.

**Comment by plain-wei** [comment]
but el-checkbox works
