### ISSUE TITLE
[Bug Report] el-input-number can't add or subtract correctly in V-for loop

### ISSUE THREAD

**Issue by csl3505** [ElemeFE/element#16840]
### Element UI version
2.11.1

### OS/Browsers version
chrom

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/csl3505/pen/NQgvgZ?&editable=true

### Steps to reproduce
点击输入框的加减按钮

### What is Expected?
可以对列表中的数值进行正确的加减

### What is actually happening?
无法进行正确的加减

**Comment by xrkffgg** [comment]
你的 key 没有设置，而且加到 点击 加号后，就会重复。
如果你想 4 个单独使用，不受影响的话，v-model 定义也区分开来。

nums 数组中，使用对象

**Comment by csl3505** [comment]
> 你的 key 没有设置，而且加到 点击 加号后，就会重复。
> 如果你想 4 个单独使用，不受影响的话，v-model 定义也区分开来。
> 
> nums 数组中，使用对象

谢谢，使用对象就可以了，不用加key也可以。

**Comment by surplus-cat** [comment]
我现在也遇到类似的情况，只不过是基于饿了么再次封装，请问怎么解决的
