### ISSUE TITLE
In [Bug Report] el-form, entering a character in el-input automatically loses focus

### ISSUE THREAD

**Issue by zhijunzhou** [ElemeFE/element#16842]
### Element UI version
2.4.11

### OS/Browsers version
MAC OS 10.13.4

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/zhouzhijun01/wnxcdhk5/13/

### Steps to reproduce
1. 选择奖品算法为阶梯算法
2. 展开”报名人数第1名“
3. 在第一个输入框100后加任意一个数字(或者删除一个数字)
4. 会发现文本框会自动输入焦点

### What is Expected?
期望文本框不要自动失去焦点，例如第二个文本框就不会失去焦点

### What is actually happening?
第一个文本框输入过程中会自动失去焦点，而第二个文本框不会自动失去焦点

**Comment by divasatanica** [comment]
got the same problem.

**Comment by divasatanica** [comment]
@zhijunzhou 

```html
<el-row
    v-for="(litem, idx) in ritem.ladder"
    :key="litem.reach_num + idx"
    :gutter="10">
    <el-col :span="8">
        且学费总金额达
        <el-input
              type="number"
              style="width: 128px;"
              v-if="litem.type"
              v-model.number="litem.reach_num">
```

The key property you bind on <el-row> is changed since you change the number in <el-input> below which cause the loss of the focus on it.

哥们，你在 el-row 绑定的 key 属性是 `Iitem.reach_num + idx` ，下面的数字一变，你这个 key 绑定的值就变了，自然就失去焦点了，你换个不变的 key 值绑定上去
