### ISSUE TITLE
[Bug Report] el-select will show value not label after deleting an item if don't use reserve-keyword 

### ISSUE THREAD

**Issue by bitjjj** [ElemeFE/element#16845]
### Element UI version
2.11.1

### OS/Browsers version
Chrome / 75

### Vue version
2.5.2

### Reproduction Link
https://codepen.io/bitjjj/pen/qejpyx

### Steps to reproduce
1) select some items
2) delete an item

### What is Expected?
select should still show item's label not value

### What is actually happening?
select show item's value after deleting an item

**Comment by durongzhang** [comment]
I also encountered, the original selection data will be cleared
