### ISSUE TITLE
Does anyone have an example of a combination table and a pagination?

### ISSUE THREAD

**Issue by xchz** [ElemeFE/element#1684]
Does anyone have an example of a combination table and a pagination? jsfiddle or repo

**Comment by flyingzl** [comment]
you can see my repository  [here](https://github.com/TCL-MIG-FE/vue-web-spa-startkit/blob/master/resouces/src/components/Table.vue).

**Comment by njleonzhang** [comment]
https://github.com/njleonzhang/vue-data-tables

**Comment by jintangWang** [comment]
@flyingzl 你的例子点击分页条table的数据都不切换
