### ISSUE TITLE
[Bug Report] Dynamic column with scroll bar, header misalignment

### ISSUE THREAD

**Issue by czlh** [ElemeFE/element#16843]
### Element UI version
2.10.1

### OS/Browsers version
windows10 chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/czlh/pen/gVRGPY

### Steps to reproduce
打开链接就行，表头和表格内容错位，有滚动条时比较明显

### What is Expected?
表头和表格对齐

### What is actually happening?
表头和表格错位

**Comment by czlh** [comment]
![image](https://user-images.githubusercontent.com/8635566/62264315-01addc00-b452-11e9-9dae-a5fae4dba2d5.png)

**Comment by czlh** [comment]
![image](https://user-images.githubusercontent.com/8635566/62264800-0b384380-b454-11e9-8ad5-e4ed6bc58f71.png)

**Comment by luochen97** [comment]
我也遇到了，应该是新版本与老版本不兼容，同样求解

**Comment by luochen97** [comment]
我也遇到过这个问题：
1.页面一进来表格会错位，和表格的gutter的display应该为none
2.有横向滚动条的，滚动滚动条也会错位，仔细对比下来是th.gutter的宽度渲染为0px，导致表头宽度比表身宽度大17px导致
3.切换时，表格也会错位，固定列会下移

**Comment by xrkffgg** [comment]
😂😂😂  为啥我看不到

**Comment by czlh** [comment]
> 😂😂😂 为啥我看不到

![image](https://user-images.githubusercontent.com/8635566/62336752-5a3db180-b504-11e9-947f-9fe92b4effb7.png)
要不试试跟我一样的分辨率配置

**Comment by jesse-li** [comment]
同样的问题，2.10，看了下代码应该是数据加载完后，出现了滚动条，table没有执行更新操作，导致head和body的可滚动距离不一致。大家可以在数据加载后手动调下doLayout救下急。

**Comment by luochen97** [comment]
> 看了下代码应该是数据加载完后，出现了滚动条

没有滚动条的也会错乱，都是页面刚进来的时候会出现，还有一种情况就是我们后台管理系统切换标签回来的时候固定列会下移错乱

**Comment by czlh** [comment]
> 同样的问题，2.10，看了下代码应该是数据加载完后，出现了滚动条，table没有执行更新操作，导致head和body的可滚动距离不一致。大家可以在数据加载后手动调下doLayout救下急。

created(){
  this.$nextTick(()=>{
        this.$refs.table.doLayout()
      }) 
  }加了这段，好像没什么效果

**Comment by novbing** [comment]
> 同样的问题，2.10，看了下代码应该是数据加载完后，出现了滚动条，table没有执行更新操作，导致head和body的可滚动距离不一致。大家可以在数据加载后手动调下doLayout救下急。

实测可行

**Comment by fh345392977** [comment]
原来还有`doLayout `这种骚操作

**Comment by ziyoung** [comment]
无法复现。

**Comment by luckyCao** [comment]
Sorry, we have no plan to fix this.

**Comment by ziyoung** [comment]
> 我也遇到过这个问题：
> 1.页面一进来表格会错位，和表格的gutter的display应该为none
> 2.有横向滚动条的，滚动滚动条也会错位，仔细对比下来是th.gutter的宽度渲染为0px，导致表头宽度比表身宽度大17px导致
> 3.切换时，表格也会错位，固定列会下移

@luochen97 #17341 pr 修复了该问题。
