### ISSUE TITLE
The [Feature Request] el-table component wants to add a manual filtering method for Table data

### ISSUE THREAD

**Issue by ihhu** [ElemeFE/element#16855]
### Existing Component
是

### Component Name
el-table

### Description
目前el-table组件筛选过滤功能 只能通过点击 筛选 按钮 来执行 el-table-column组件的 filter-method 方法属性。

虽然可以通过 自定义 table-header 模版 来实现复杂的自定义筛选功能，但似乎只能对 tableData 操作才能达到 筛选过滤 效果。

希望el-table组件 增加 对Table数据 进行筛选过滤的方法，通过调用它能使用 table 内置的数据过滤功能并能触发 执行 el-table-column组件的 filter-method 方法属性及触发el-table组件的filter-change事件。

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
