### ISSUE TITLE
[Bug Report] Locale inconsistencies: When you click 'x' to close the Dialog, it shows non-english characters by default

### ISSUE THREAD

**Issue by connecteev** [ElemeFE/element#16869]
### Element UI version
2.11.1

### OS/Browsers version
Mac, Chrome latest version

### Vue version
2.6.10

### Reproduction Link
https://element.eleme.io/#/en-US/component/dialog

### Steps to reproduce
Go to https://element.eleme.io/#/en-US/component/dialog
Click on the link under "Basic usage". Then click on the 'x' icon.

You are shown "Are you sure to close this dialog?" with buttons in Chinese:
https://prnt.sc/on6k13
The locale should be consistent across all components. 

### What is Expected?
Buttons text should be in English

### What is actually happening?
Buttons text is shown in Chinese

**Comment by luckyCao** [comment]
#17373
