### ISSUE TITLE
When the multiple of [Bug Report] select is true, neither blur nor focus events are triggered

### ISSUE THREAD

**Issue by guaijie** [ElemeFE/element#16860]
### Element UI version
2.11.1

### OS/Browsers version
windows7 / 版本 75.0.3770.142（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/pMwQGY

### Steps to reproduce
1. multiple=true
2. @blur="handleBlur"
3. 让select失去交点
4. 不会触发blur事件
5. select输入框文字被清空，但并未触发input和change事件

![image](https://user-images.githubusercontent.com/30885718/62285828-02159980-b489-11e9-846c-3004751801f7.png)
失去焦点清空搜索文字但没有触发filter-method导致下拉框部分数据丢失
![image](https://user-images.githubusercontent.com/30885718/62286019-6b95a800-b489-11e9-9d19-7eecb6c8579d.png)

### What is Expected?
在multiple为true时触发blur和focus事件

在筛选时，失去焦点内部要触发input和change事件，使得文字因失去交点而被清空时能触发filter-method方法

### What is actually happening?
在multiple为true时无法触发blur和focus事件

在筛选时，失去焦点内部没有触发input和change事件，使得文字因失去交点而被清空时不能触发filter-method方法

**Comment by luckyCao** [comment]
https://element.eleme.cn/#/zh-CN/component/select#methods

blur is a method
