### ISSUE TITLE
Select组件在filterable为true时，选中一条记录后，再次点击select后,能否再次弹出下拉列表，并且将之前选中的高亮？

### ISSUE THREAD

**Issue by flyingzl** [ElemeFE/element#1686]
### ElementUI version
1.0.6

### OS/Browers version
Chrome 55

### Vue version
2.1.3

### Steps to reproduce

Select组件在filterable为true时，选中一条记录后，再次点击select后，由于过滤器存在的原因，点击下拉按钮，下拉列表只有之前选中的那条记录。这个在技术上是合理的，但是对用户来说显得不太友好。

### What is Expected?

再次点击select后, 希望再次弹出下拉列表，并且将之前选中的高亮。这样显得更直观。因为用户访问时， 由于我们会设置Select默认选择第一条记录， 用户并没有做任何搜索操作，对用户来说，不存在过滤的问题，这样更符合用户的期望。

**Comment by Leopoldthecoder** [comment]
近期是收到一些用户反馈 filterable 的 Select 的交互问题，我们会统一修改。

**Comment by baxiaoshi** [comment]
这周会更新么, select框目前没法用, 通过props传递对象，绑定el-select提示undefine

**Comment by Leopoldthecoder** [comment]
@baxiaoshi 请给出能重现问题的 demo

**Comment by baxiaoshi** [comment]
渲染组件：
<compoent :is="step.component" :form="step.form"></compoent>

传递组件
this.form.steps.push({key: Date.now(), value: '', type: '', component: 'TransferFile', form: {name: '', src: '', desc: '', srcFile: '', owner: 'root', group: 'root', mode: '0644', hosts: ''}})

TransferFile组件
props: ['form']

绑定属性
<el-select v-model="form.src"  placeholder="搜索服务器上的文件">
    <el-option v-for="item in fileList" :key="item.key" :label="item.label" :value="item.value">
    </el-option>
</el-select>

TransferFile组件获取绑定的属性值
getFileContent (val) {
    console.log('get File content')
    console.log(this.for
![element-select](https://cloud.githubusercontent.com/assets/11749031/21089400/b69ae544-c072-11e6-8f02-c0562e920a9b.png)
m.src)
}

**Comment by baxiaoshi** [comment]
![select_code](https://cloud.githubusercontent.com/assets/11749031/21089416/d50c9522-c072-11e6-8823-25e3d4370fb6.png)
![element-select](https://cloud.githubusercontent.com/assets/11749031/21089418/d6d5bc26-c072-11e6-9df7-786049aa0b35.png)

**Comment by Leopoldthecoder** [comment]
@baxiaoshi 麻烦给个在线 demo

**Comment by flyingzl** [comment]
@baxiaoshi 麻烦你新开一个issue吧。@Leopoldthecoder 你可以给这个issue打一个tag吧， 是 `feature request`呢 还是`design` 其他呢。。。

**Comment by Leopoldthecoder** [comment]
@flyingzl 不好意思忘记了。1.0.7 已经修改。
