### ISSUE TITLE
[Bug Report] el-date-picker change event doesn't fire

### ISSUE THREAD

**Issue by TomPenguin** [ElemeFE/element#16862]
### Element UI version
2.4.5

### OS/Browsers version
Windows 10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/smokingjet/pen/PMjVwM

### Steps to reproduce
https://codepen.io/smokingjet/pen/PMjVwM

### What is Expected?
change event does fire

### What is actually happening?
change event doesn't fire

**Comment by LilyWakana** [comment]
You need to add an input handler for the second picker like this `onInput(newVal){ this.test = newVal; }`

**Comment by TomPenguin** [comment]
@LilyWakana 
Thanks. Input event does fired.
But I do not see a description of the Input event to the document.

https://element.eleme.io/#/en-US/component/date-picker#datepicker

Is this an official event?

**Comment by LilyWakana** [comment]
It is an event added by  `v-model`.

From the  offical doc of Vue:
> Although a bit magical, v-model is essentially syntax sugar for updating data on user input events, plus special care for some edge cases.

And custom form componentss should emit `input` or `change` to make `v-model` directives work

https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model

**Comment by TomPenguin** [comment]
@LilyWakana 
> And custom form componentss should emit `input` or `change` to make `v-model` directives work
oh, I understand Vue.
It's not Element probrem.

Thank you for your quick reply.
