### ISSUE TITLE
[Feature Request] Add different Dialog / Modal animations / transitions on show / hide

### ISSUE THREAD

**Issue by connecteev** [ElemeFE/element#16871]
### Existing Component
Yes

### Component Name
Dialog

### Description
Add different ways to animate the entry (show) and exit (hide) of the dialog or modal here: https://element.eleme.io/#/en-US/component/dialog

Here are just a few ideas:
1. fade in to show, fade out to hide
2. slide down to show, slide up to hide
3. slide down   fade in, slide up   fade out to hide

All of these are also great:
https://tympanus.net/Development/ModalWindowEffects/
https://joaopereirawd.github.io/animatedModal.js/
Would be amazing to have these as an optional include.

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
