### ISSUE TITLE
[Feature Request] Add different Dialog / Modal triggers

### ISSUE THREAD

**Issue by connecteev** [ElemeFE/element#16870]
### Existing Component
Yes

### Component Name
Dialog

### Description
Add different ways to trigger / launch the dialog or modal here: https://element.eleme.io/#/en-US/component/dialog

1. After 'x' amount of time after page load
2. On scrolling down the page to element with #id
3. On scrolling down the page PAST element with #id
4. On exit intent (trying to navigate away from the browser tab, for example, to close the browser window or go to a different browser tab). Note: Here, we should also allow a "remember selection for X amount of time in hours/days", so that the dialog / modal is not shown again after it was once closed.

**Comment by nullptru** [comment]
Pr welcome

**Comment by connecteev** [comment]
@nullptru I cant do a full PR but I can send a code snippet in vanilla html / js here for these triggers. would that help, and will that be integrated into Element if I spend time to do that?
