### ISSUE TITLE
[Bug Report] Select component blur event triggered incorrectly

### ISSUE THREAD

**Issue by msidolphin** [ElemeFE/element#16872]
### Element UI version
2.11.1

### OS/Browsers version
win7

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/pMwQGY

### Steps to reproduce
1、点击select

2、任意选择一项

3、blur事件被触发

4、点击外部关闭select

5、blur事件未触发

### What is Expected?
3、blur事件不触发

5、blur事件触发

### What is actually happening?
3、blur事件被触发

5、blur事件未触发

**Comment by luckyCao** [comment]
blur is a method
