### ISSUE TITLE
[Bug Report] Cannot enter 0 at the end of a digit with a decimal point in the el-input which type is 'number' and value use v-model.number

### ISSUE THREAD

**Issue by care100** [ElemeFE/element#16873]
### Element UI version
2.11.1

### OS/Browsers version
Mac OS X 10_13_6/Chrome_75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://github.com/care100/element-elInput-bug/blob/master/test-element-ui.html

### Steps to reproduce
Set 'number' as the type of el-input, use v-model.number. Input 1.01 in the el-input. When input 0, the decimal point and 0 will be deleted.

### What is Expected?
Can input 1.01, do not delete decimal point and 0.

### What is actually happening?
Decimal point and 0 will be deleted

**Comment by care100** [comment]
If i want to input 1.01, i can only input 1.1, then left shift cursor, input 0 finally!

**Comment by wacky6** [comment]
https://element.eleme.io/#/zh-CN/component/input#input-shu-ru-kuang
