### ISSUE TITLE
Can [Feature Request] el-select multiple selection support full selection?

### ISSUE THREAD

**Issue by weidongqing** [ElemeFE/element#16876]
### Existing Component
是

### Component Name
el-select

### Description
多选的时候没有全选功能

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.

**Comment by Hsensor** [comment]
哈哈，那我自己实现吧，select 这个组件应该算比较复杂了
clickoutside, emmiter, scrollbar,只看这几个逻辑就能感觉复杂了
