### ISSUE TITLE
form表单中的 label-width 希望能支持 min-width的写法

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#1687]
### ElementUI version

1.0.6
### Vue version

^2.1

**Comment by furybean** [comment]
没看懂，"min-width 的写法" 是什么概念？

**Comment by spademan** [comment]
举个栗子你就明白我的意思了，
现在好像只是支持 label-width写成 固定宽度，假如我的 label 是通过某个数组遍历出来的，那么宽度就不好那个控制了，

**Comment by baiyaaaaa** [comment]
如果灵活性需要这么高的话不建议用 `form-item` 了，而且 `form-item` 很少用在遍历渲染的场景下的吧
