### ISSUE TITLE
[Autocomplete]  远程返回结果必须通过value显示，能否是其他字段？

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1688]
rt

**Comment by yuzhiquan** [comment]
是的，数据是list，里面的每个object必须要有value字段，否则显示为空

**Comment by njleonzhang** [comment]
@yuzhiquan 请问你是考虑修改一下，添加一个字段只是value是什么？否则需要处理后台的数据，每次都要遍历后台数据，并设置一个value值，这样很不方便。

**Comment by yuzhiquan** [comment]
在下并非element开发者，只是之前遇到过类似的问题……

**Comment by njleonzhang** [comment]
@yuzhiquan 那么你是否也觉得不太好。。。。

**Comment by baiyaaaaa** [comment]
现在确实是只能以value作为值来显示

**Comment by njleonzhang** [comment]
@baiyaaaaa feature request

**Comment by ryannan** [comment]
我也遇到了，能不能设置个自定义字段，还有custom-item怎么使用的

**Comment by baiyaaaaa** [comment]
@njleonzhang 你可以用自定义列表项`custom-item`来对列表做不同的展示，但是 value 字段是必须的，需要有一个字段来代表当前项的值

**Comment by njleonzhang** [comment]
@baiyaaaaa 好像已经改了

**Comment by FlappyHeart** [comment]
我也遇到了，请问现在怎么处理这个问题？
