### ISSUE TITLE
[Feature Request] switching animation of'el-tabs/el-tab-pane'content

### ISSUE THREAD

**Issue by LIAOTOW** [ElemeFE/element#16885]
### Existing Component
是

### Component Name
el-tabs/el-tab-pane

### Description
Suggested 'el-tabs/el-tab-pane' to increase the switching animation of the content area  

建议'el-tabs/el-tab-pane'组件增加内容区域的切换动画

**Comment by nullptru** [comment]
Sorry, we have no plan to support this.
