### ISSUE TITLE
[Bug Report] Table not showing up when :data provided

### ISSUE THREAD

**Issue by antarasi** [ElemeFE/element#16888]
### Element UI version
2.10.1

### OS/Browsers version
Electron

### Vue version
2.6.10

### Reproduction Link
https://github.com/antarasi/vue-e

### Steps to reproduce
git clone https://github.com/antarasi/vue-e.git
cd vue-e
yarn
npm run dev

### What is Expected?
Table showing up with columns and rows

### What is actually happening?
When data is provided as parameter, nothing happens. No error, no table

**Comment by antarasi** [comment]
![image](https://user-images.githubusercontent.com/7021775/62376757-b2df6f80-b541-11e9-8213-71c75fcbde7d.png)

**Comment by princeofnubia** [comment]
I am also experiencing this issue in electron

**Comment by kundaneyug** [comment]
I am having similar issue my table with data is not working on new versions unable to release update because of this issue

**Comment by princeofnubia** [comment]
I got the solution!. You need to whitelist element-ui webpack.renderer.config.js like this
 let whiteListedModules = ["vue", "bootstrap-vue", "element-ui"];
It wont give you the problem again. I had that issue with bootstrap vue as well.

**Comment by princeofnubia** [comment]
I have posted the solution. Whitelist element-ui

**Comment by antarasi** [comment]
Works fine now! Thank you @princeofnubia

**Comment by goldengecko** [comment]
I am having this problem too but it's not an Electron project, so I don't have a webpack.renderer.config.js file. How do I fix it in this scenario?

I have narrowed it down to the changes that occurred between v2.9.1 and 2.9.1, and it appears that the render happens once only, before the columns have been calculated, so is rendered with the right number of rows but no columns and therefore no height.
