### ISSUE TITLE
[Bug Report] NavMenu Navigation Menu If there are too many menus, the pop-up menu can't scroll after the state is closed, and can't see the whole menu.

### ISSUE THREAD

**Issue by 635566381** [ElemeFE/element#16883]
### Element UI version
2.11.1

### OS/Browsers version
Google Chrome 版本 75.0.3770.142（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/635566381/pen/BXdPqm

### Steps to reproduce
NavMenu 导航菜单如果菜单过多, 收起状态后的弹出菜单不能滚动, 看不完整

### What is Expected?
收起状态下 弹出的菜单列表可以滚动

### What is actually happening?
收起状态下 弹出的菜单列表不可以滚动, 看不完整, 比如案例中的选项一就点击不到

**Comment by 635566381** [comment]
![Uploading image.png…]()

**Comment by 635566381** [comment]
![image](https://user-images.githubusercontent.com/23730568/62529023-690fc580-b870-11e9-802b-71e8a282b921.png)

**Comment by luckyCao** [comment]
@635566381 这样使用

```
<el-submenu index="1"  :popper-options="options" popper-class="custom-popper">
```
```
data() {
  return {
        isCollapse: true,
        options: {
          modifiers: [
            {
              preventOverflow: {
                boundariesElement: 'window'
              }
            }
          ]
        }
      };
    }
```
```
.custom-popper {
    left: 70px;
}
```
https://codepen.io/luckyCao/pen/VwZxwpN
