### ISSUE TITLE
[Bug Report] el-dialog close bug with modal

### ISSUE THREAD

**Issue by HydrogenPan19** [ElemeFE/element#16887]
### Element UI version
2.11.1

### OS/Browsers version
win10 / chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/WVEBbN

### Steps to reproduce
same as
[#15000](https://github.com/ElemeFE/element/issues/15000#issuecomment-498648554)
#16265 

> **This bug has been fixed in #15544 , but why was it finally revoked?**

### What is Expected?
Do not close the dialog when releasing the mouse outside

### What is actually happening?
The dialog is closed when the mouse is released

**Comment by HydrogenPan19** [comment]
@island205
Could you give me some information?

**Comment by island205** [comment]
Because we revert this PR https://github.com/ElemeFE/element/pull/16201, we don't find a solution yet.

**Comment by HydrogenPan19** [comment]
What problems in  previous pr ?

I  wrote a demo, it may be solved

https://codepen.io/hydrogenpan19/pen/RXQOvR

**Comment by japhfortin** [comment]
Do we have an update about this?

**Comment by bum-hyun** [comment]
Actually, you just change @click.self to mousedown.self.
then it will be solved
