### ISSUE TITLE
[Feature Request] elementui tree cannot automatically upgrade child nodes to parent nodes, resulting in no free dragging

### ISSUE THREAD

**Issue by isanonymous** [ElemeFE/element#16891]
### Existing Component
是

### Component Name
tree

### Description
elementui的树tree不能把叶子节点自动升级成父节点, 导致不能自由拖动
例: 这里不能把`一级01`直接拖动到`一级02`里面
|---ROOT
    |---一级01
        |---二级01-01
        |---二级01-02
    |---一级02

**Comment by luckyCao** [comment]
duplicate
