### ISSUE TITLE
[Bug Report] select often jitters under Chrome

### ISSUE THREAD

**Issue by homeoffriends** [ElemeFE/element#16895]
### Element UI version
2.11.0

### OS/Browsers version
Windows10/Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/homeoffriends/pen/RXjpoK

### Steps to reproduce
在element官网和我们的项目中，展开下拉选项经常会出现抖动，但在上面的“重现链接”中倒没有出现，比较奇怪

### What is Expected?
展开下拉选项时不要出现抖动

### What is actually happening?
展开下拉选项时会出现抖动

**Comment by ziyoung** [comment]
Duplicate of #16786
