### ISSUE TITLE
el-select 无法与vuex协同

### ISSUE THREAD

**Issue by dearbird** [ElemeFE/element#1689]
### ElementUI version

1.0.6
### Vue version

2.1.4
### Reproduction Link

https://jsfiddle.net/wynr3gce/1/

### What is actually happening?
结合vuex使用时， 变量绑定不是 v-model  而是 :value + @change ，change事件无法触发。
el-switch 可以正常触发。

**Comment by Leopoldthecoder** [comment]
参考 #1632
