### ISSUE TITLE
[Bug Report] NormalModule Replacement Plugin in vue.config.js is not working

### ISSUE THREAD

**Issue by byouloh** [ElemeFE/element#16890]
### Element UI version
2.11.0

### OS/Browsers version
Windows 10/Chrome 76.0.3809.87(64bit)

### Vue version
2.6.10

### Steps to reproduce
vue.config.js is followings:

```
const webpack = require('webpack')
const path = require('path');
function resolveSrc(_path) {
  return path.join(__dirname, _path)
}
module.exports = {
  configureWebpack: {
    // Set up all the aliases we use in our app.
    resolve: {
      alias: {
        'src': resolveSrc('src'),
        'assets': resolveSrc('src/assets')
      }
    },
    plugins: [
      new webpack.DefinePlugin({
        '_GRAPHQL_HTTP_ENDPOINT_': JSON.stringify(process.env.GRAPHQL_HTTP_ENDPOINT) || "`${origin}/graphql`",
        '_GRAPHQL_WS_ENDPOINT_': JSON.stringify(process.env.GRAPHQL_WS_ENDPOINT) || "origin.replace('http','ws') '/subscriptions'"
      }),
      // https://element.eleme.cn/#/en-US/component/i18n
      // The Chinese language pack is imported by default, even if you're using another language.
      // But with NormalModuleReplacementPlugin provided by webpack you can replace default locale:
      // webpack.config.js
      new webpack.NormalModuleReplacementPlugin(/element-ui[\/\\]lib[\/\\]locale[\/\\]lang[\/\\]zh-CN/, 'element-ui/lib/locale/lang/en')
    ]
  },
  css: {
    // Enable CSS source maps.
    sourceMap: true
  }
};
```

I want to use English as a default language including library messages.
But before finishing loading the table data, I can see the "暂无数据" message.
My config is something wrong? or is it a bug?

### What is Expected?
I want to use English as a default language including library messages.

### What is actually happening?
But before finishing loading the table data, I can see the "暂无数据" message.
My config is something wrong? or is it a bug?

**Comment by luckyCao** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by byouloh** [comment]
My project with element-ui and vue.config.js has still has chinese default language problem. How can I fix that? Need I use the webpack as your manual?
