### ISSUE TITLE
[Bug Report] el-collapse-transition import with typescript

### ISSUE THREAD

**Issue by vanhumbeecka** [ElemeFE/element#16893]
### Element UI version
2.11.1

### OS/Browsers version
Brave

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/3owghmvs/

### Steps to reproduce
- Start a Vue Typescript project
- DON'T import everything from element with Vue.use(ElementUI), but import seperate elements (see jsfiddle)
- use a ```<el-collapse-transition>``` in a Vue component
- Application throws error saying this component is not registered (which is correct)
- The problem is: You CANNOT import this component in a typescript way, with seperate ElementUI elements installed. (also no TS definition section for this)

### What is Expected?
To be able to register ```<el-collapse-transition>``` component for use in a Vue component.
But the library does not give you a way to do this in a Typescript Seperate ElementUI-components-install application.

### What is actually happening?
Being unable to register this component in a Typescript setup, the browser correclty throws an error saying the component is not registered.

**Comment by luckyCao** [comment]
el-collapse-transition is not an api

**Comment by elijahworkz** [comment]
@vanhumbeecka  in case you're still interested in this here's how:

```
import { CollapseTransition } from 'element-ui';
Vue.component(CollapseTransition.name, CollapseTransition);
```
