### ISSUE TITLE
[Feature Request] When the content is too much, the excess part can not be dragged to display.

### ISSUE THREAD

**Issue by dongshixiao** [ElemeFE/element#16896]
### Existing Component
是

### Component Name
Drawer

### Description
```
<el-drawer  :visible.sync="dialogFormVisible" >
    <ul>
        <li v-for="n in 1000" v-bind:key="n">
            {{ n }}
        </li>
    </ul>
</el-drawer>

<script>
  export default {
    data() {
      return {
        dialogFormVisible: true,
      };
    }
  };
</script>
```
When the number of Li is too large, the latter can not be seen.

**Comment by yestab123** [comment]
I had same problem.

**Comment by xrkffgg** [comment]
兄弟，你可以先在自己项目中 这样修改

```
.el-drawer.ltr, .el-drawer.rtl {
    overflow-y : auto;
}
```

**Comment by dongshixiao** [comment]
> 兄弟，你可以先在自己项目中 这样修改
> 
> ```
> .el-drawer.ltr, .el-drawer.rtl {
>     overflow-y : auto;
> }
> ```

嗯,之前就是改的样式.

**Comment by frank-zx** [comment]
> > 兄弟，你可以先在自己项目中 这样修改
> > ```
> > .el-drawer.ltr, .el-drawer.rtl {
> >     overflow-y : auto;
> > }
> > ```
> 
> 嗯,之前就是改的样式.

我试了没用啊

**Comment by LongLonger** [comment]
> 兄弟，你可以先在自己项目中 这样修改
> 
> ```
> .el-drawer.ltr, .el-drawer.rtl {
>     overflow-y : auto;
> }
> ```

你好，试了没用啊，有别的方法吗

**Comment by LongLonger** [comment]
> 兄弟，你可以先在自己项目中 这样修改
> 
> ```
> .el-drawer.ltr, .el-drawer.rtl {
>     overflow-y : auto;
> }
> ```

你好，试了不起作用啊，能指教一下吗

**Comment by xrkffgg** [comment]
@frank-zx @LongLonger 把你们的定义代码发出来看看

**Comment by LongLonger** [comment]
> @frank-zx @LongLonger 把你们的定义代码发出来看看

![image](https://user-images.githubusercontent.com/12244901/62854567-45da8f80-bd22-11e9-9089-144bd64bef8c.png)

**Comment by xrkffgg** [comment]
@LongLonger 不是在UI里修改，是在你们vue文件中。
在 <style> </style>

注意不能在 scoped 里，不然不起作用，如果只想加在当前文件中，可以定义 id

**Comment by LongLonger** [comment]
> @LongLonger 不是在UI里修改，是在你们vue文件中。
> 在 <style> </style>
> 
> 注意不能在 scoped 里，不然不起作用，如果只想加在当前文件中，可以定义 id

可以了，谢谢老哥

**Comment by dongshixiao** [comment]
> > @LongLonger 不是在UI里修改，是在你们vue文件中。
> > 在 <style> </style>
> > 注意不能在 scoped 里，不然不起作用，如果只想加在当前文件中，可以定义 id
> 
> 可以了，谢谢老哥

是的 在你vue文件style直接写就ok了

**Comment by LongLonger** [comment]
> > > @LongLonger 不是在UI里修改，是在你们vue文件中。
> > > 在 <style> </style>
> > > 注意不能在 scoped 里，不然不起作用，如果只想加在当前文件中，可以定义 id
> > 
> > 
> > 可以了，谢谢老哥
> 
> 是的 在你vue文件style直接写就ok了

谢谢回复

**Comment by luckyCao** [comment]
pr welcome
