### ISSUE TITLE
[Bug Report] Tree select checkbox space

### ISSUE THREAD

**Issue by atilkan** [ElemeFE/element#16905]
### Element UI version
2.11.1

### OS/Browsers version
Chrome OSX

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
Look at checkbox and text space. 

### What is Expected?
It use to have a little space.

### What is actually happening?
Too close to each other.

**Comment by ziyoung** [comment]
fixed in 2.12.0
