### ISSUE TITLE
[Bug Report] The table Sort funtion is not work

### ISSUE THREAD

**Issue by shanxichen** [ElemeFE/element#16901]
### Element UI version
2.9.2

### OS/Browsers version
win 10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/shanxichen/pen/wVPpQx?editors=1011

### Steps to reproduce
click 'sort name' button

### What is Expected?
sort witn name

### What is actually happening?
no

**Comment by victorting** [comment]
刚才看了下table的文档说明，文档中的sort方法是传入prop:string, order:string两个参数, 并不是{prop:string, order: string}, 这是修改后的demo link： https://codepen.io/anon/pen/LweyEb?editors=1011

**Comment by shanxichen** [comment]
看到了，我理解错了。
另外你的这个demo 为啥打开会无限刷新？
