### ISSUE TITLE
DatePicker清除问题

### ISSUE THREAD

**Issue by yulane** [ElemeFE/element#1690]
### ElementUI version

1.0.6
### OS/Browers version

macOS/Chrome 53
### Vue version

2.0.1
### Reproduction Link

http://element.eleme.io/#/zh-CN/component/date-picker
### Steps to reproduce
DatePicker弹出时间选择后，鼠标放到清除icon上面，时间选择范围变成1970.1-1970.2
### What is Expected?
应该只是清除，下面时间范围不变

**Comment by Molunerfinn** [comment]
官方给出的例子里也有这样的错误。当你选择了某些日期之后，然后选择清空，时间选择范围变为1970.1-1970.2
http://jsfiddle.net/api/post/library/pure/

**Comment by ivan403704409** [comment]
遇到同样的问题
[demo](http://jsfiddle.net/ivan403704409/zr76cd3j/)
