### ISSUE TITLE
[Bug Report]  el-calendar  has problems in the West Time Zone

### ISSUE THREAD

**Issue by yyl1208** [ElemeFE/element#16918]
### Element UI version
2.11.1

### OS/Browsers version
win 10 ， Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yyl1208/pen/PMEOmY

### Steps to reproduce
Set time zone to -7 ( US, Los Angeles ) 
Go to https://element.eleme.io/#/en-US/component/calendar
Click "previous month/today" on a calendar

### What is Expected?
The correct day is highlighted.

### What is actually happening?
The wrong day is highlighted.

**Comment by FBshtml** [comment]
这个是没问题的......之前做一个定时显示的通知栏，也这么干过，实际上你调整本地时间到new Date()获取到调整后的最新时间系统大约有1~3分钟的延迟 ，你可以在控制台获取到本地显示的时间后再去点”此刻“就能获取正确时间了

**Comment by yyl1208** [comment]
> 这个是没问题的......之前做一个定时显示的通知栏，也这么干过，实际上你调整本地时间到新日期（）获取到调整后的最新时间系统大约有1~3分钟的延迟，你可以在控制台获取到本地显示的时间后再去点“此刻”就能获取正确时间了

换成西八区，控制台打印得时间是对得，点上个月 日历还是跳到6月30号啊

**Comment by yyl1208** [comment]
https://github.com/ElemeFE/element/issues/16485#issue-465880255 和这个老哥的问题其实一样了

**Comment by yyl1208** [comment]
拉了个dev下来  发现这个分支项目的组件功能是好的，网站和项目中的组件会有问题，应该是还没更新

**Comment by iamkun** [comment]
check #16485
