### ISSUE TITLE
[Feature Request] Diaog Close Method Triggered Repeatedly

### ISSUE THREAD

**Issue by FBshtml** [ElemeFE/element#16912]
### Existing Component
是

### Component Name
dialog

### Description
给dialog组件右上角关闭 ”×“ 绑定close()，同时给绑定底部”关闭“按钮绑定close()，点击“关闭”按钮，close()会被触发两次，希望他们能够互不影响

**Comment by xrkffgg** [comment]
我的理解 close() 是 dialog 关闭时触发的
你不管是以何种方式关闭都会触发
如果你的关闭按钮和 dialog 关闭 需要触发不同的方法
建议分开定义，或者在 close(type) 中 增加参数 区分

**Comment by FBshtml** [comment]
emmm，我明白你的意思
<el-dialog  @close="closeDialog">
        <el-button @click="closeDialog" :before-close="handleClose">关 闭</el-button>
</el-dialog>
before-close以何种方式关闭都会触发我理解
点击 button， closeDialog会被触发两次想不通

**Comment by xrkffgg** [comment]
😂😂😂 兄弟 不要太纠结

**Comment by Sean-214** [comment]
逻辑挺正常的啊。你关闭按钮的click事件是你点关闭按钮的行为。对话框的close事件是对话框关闭时的行为。我猜你的需求是点关闭按钮只关闭对话框，然后在对话框关闭的时候再执行某些逻辑。哪你的关闭按钮只需要visible = false就可以了。这里其实是你自己写重复了。

**Comment by FBshtml** [comment]
真相了，当时visible是上层传下来的，所以没直接赋值false，没想到会出现这个问题
