### ISSUE TITLE
[Bug Report] New version of dropdown component transition jitter

### ISSUE THREAD

**Issue by mengdu** [ElemeFE/element#16910]
### Element UI version
2.11.1

### OS/Browsers version
win x64/chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/mNpWgM

### Steps to reproduce
从文档里看例子，涉及与dropdown有关的都会有弹出时抖动一下。具体的抖动例子，请看 https://element.eleme.io/#/zh-CN/component/dropdown 文档里的例子效果。

### What is Expected?
正常过渡

### What is actually happening?
过渡出现抖动

**Comment by xrkffgg** [comment]
https://github.com/ElemeFE/element/blob/b8e96b35a1243816d65598ac57066333831d085d/packages/dropdown/src/dropdown-menu.vue#L2

你说的 是不是 这个 `el-zoom-in-top` 这个动画的效果呢？

**Comment by mengdu** [comment]
@xrkffgg 没看具体哪里的问题，我项目里跟文档里的例子一样抖动。
https://codepen.io/anon/pen/mNpWgM 这个例子没那么明显。

**Comment by xrkffgg** [comment]
你的是一直都这样，还是某次更新过 element 版本后出现的？

**Comment by mengdu** [comment]
新的项目，添加个动图看看
![test](https://user-images.githubusercontent.com/11366654/62507919-6f824b00-b838-11e9-9be6-de36acab859e.gif)

**Comment by xrkffgg** [comment]
一直盯着看，都看迷糊了。。。。

https://github.com/ElemeFE/element/blob/b8e96b35a1243816d65598ac57066333831d085d/packages/dropdown/src/dropdown.vue#L53

好像是有一个250ms的间隔，不点太快没事吧。。。。
