### ISSUE TITLE
can i use <el-input native-type="number"></el-input>

### ISSUE THREAD

**Issue by GreenMelon** [ElemeFE/element#1692]
当我想要使用 `<input type="number"> `时，我现在只能用 `<el-input-number>`，然后设置 controls 为 false，再在样式表里把 input 元素的宽度设置为父元素尺寸。使用流程略微繁琐。可以支持下面这样的使用方式吗？

1.` <el-input type="number"> `或
2. `<el-input native-type="number"> `

**Comment by baiyaaaaa** [comment]
`<el-input type="number">` 是支持的
