### ISSUE TITLE
[Bug Report] Prevent tabbing/typing while the loading mask is open and constrain tabindex within el-dialog

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#16929]
### Element UI version
2.11.1

### OS/Browsers version
Windows / Chrome -latest

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/LwQybR

### Steps to reproduce
Click the button to open the dialog or the loading animation. Press the Tab key. You can now type in the text-input.

### What is Expected?
When a dialog is open or loading screen is visible, the user should not have access to anything under the mask - tabbing, clicking, typing, etc.

### What is actually happening?
You can tab around and type under the mask.

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
