### ISSUE TITLE
[Feature Request] add a global readonly property for el-form

### ISSUE THREAD

**Issue by achabuhecha** [ElemeFE/element#16923]
### Existing Component
是

### Component Name
el-form

### Description
    中文：可以给它增加一个全局的readonly属性吗？类似于现有的disabled属性，这样的话，进行类似查看详情的时候，就不会显的那么不好看。

    English：Can you add a global readonly property to it? Similar to the existing disabled attribute, it would not look so bad when you look at details like this.

**Comment by xrkffgg** [comment]
好像 只有 input  有 readonly 属性吧   这就尴尬了

**Comment by FBshtml** [comment]
可以自己封装下：当你希望表单只读的时候，给他加一个z-index：999 的透明浮层.....

**Comment by achabuhecha** [comment]
> 好像 只有 input 有 readonly 属性吧 这就尴尬了

**Comment by achabuhecha** [comment]
> 好像 只有 input 有 readonly 属性吧 这就尴尬了

额，倒也是。但是不太好看，试下覆盖层的写法吧

**Comment by xrkffgg** [comment]
@achabuhecha 其实推荐你覆盖 disabled 的样式

可以在指定页面里

将 字的颜色 设置成黑色   背景设置成白的   鼠标 随便你设置   虽然是disabled  其实 看起来 和readonly 一样

**Comment by achabuhecha** [comment]
> @achabuhecha 其实推荐你覆盖 disabled 的样式
> 
> 可以在指定页面里
> 
> 将 字的颜色 设置成黑色 背景设置成白的 鼠标 随便你设置 虽然是disabled 其实 看起来 和readonly 一样

嗯，也是个很好的方法，谢谢，我试一下
