### ISSUE TITLE
[Feature Request] Drawer component supports horizontal or vertical scrolling.

### ISSUE THREAD

**Issue by Y09a** [ElemeFE/element#16937]
### Existing Component
Yes

### Component Name
Drawer

### Description
En. Drawer component needs to support horizontal or vertical scrolling.

CN. 抽屉组件需要支持横纵滚动，我们用期待已久的Drawer组件，替代传统的使用Dialog组件展示详细信息，Drawer用来作为一个承载复杂子组件的容器，我们希望它可以更健壮更圆滑。

**Comment by Y09a** [comment]
This issue has been fixed #16917
https://github.com/ElemeFE/element/pull/16917

**Comment by fudax** [comment]
> This issue has been fixed #16917
> #16917

@ziyoung 
顺道提个建议，请看是否可以采纳：
Dialog和Drawer提供与Notification一样的closeAll方法，因为可能在model模式下，由Notification内容（链接/路由操作）呼起的路由跳转，由于Notification无法确定当前页面的Dialog和Drawer到底是哪个，导致原页面的Dialog和Drawer对新页面body的遮罩，当然，这是个小问题。

**Comment by ziyoung** [comment]
> > This issue has been fixed #16917
> > #16917
> 
> @ziyoung
> 顺道提个建议，请看是否可以采纳：
> Dialog和Drawer提供与Notification一样的closeAll方法，原因：
> 
> 因为可能在model模式下，由Notification内容（链接/路由操作）呼起的路由跳转，由于Notification无法确定当前页面的Dialog和Drawer到底是哪个，导致原页面的Dialog和Drawer对新页面body的遮罩，当然，这是个小问题。

@fudax 新开一个 issue 吧。最好提供一个 demo 链接。
