### ISSUE TITLE
select 怎么设置默认值？

### ISSUE THREAD

**Issue by fandudu** [ElemeFE/element#1693]

**Comment by Leopoldthecoder** [comment]
参考：http://jsfiddle.net/leopoldthecuber/vcgftLvn/

**Comment by fandudu** [comment]
@Leopoldthecoder

**Comment by fandudu** [comment]
multiple 不可以啊

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/vcgftLvn/1/
不行的话给个 demo

**Comment by Leopoldthecoder** [comment]
超过七天没有反馈的 issue 会被关闭。如果可以重现的话，请再次打开。

**Comment by conderpath** [comment]
这个问题解决了吗，我这也是没办法给默认值呢

**Comment by blanklin030** [comment]
@conderpath 
只要把默认值的类型设置为string类型，就可以使用默认值，所以无论从后端还是前端，设置默认值的时候记住是string类型
