### ISSUE TITLE
[Bug Report] Disables form submission issues: Use watch to monitor form and check fields to complete valid variable test without triggering validate first

### ISSUE THREAD

**Issue by wgf4242** [ElemeFE/element#16938]
![录制_2019_08_07_15_52_23_913](https://user-images.githubusercontent.com/3336626/62605150-1562b200-b92c-11e9-9a0b-16d09f301fd1.gif)

### Element UI version
2.11.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
重现链接是这个： https://stackblitz.com/edit/typescript-vuejs-element-3kko7a

1. password 输入2
2. username 输入11
3. username 改为2  // 正常应该能提交的，但是不能

### What is Expected?
期待formvalid = true

### What is actually happening?
formvalid = false

**Comment by ziyoung** [comment]
```
// 添加这个
this.formValid = true;
callback();
```
