### ISSUE TITLE
[Feature Request] El-tree specifies the parent node expands all child nodes

### ISSUE THREAD

**Issue by kwezdj123** [ElemeFE/element#16934]
### Existing Component
是

### Component Name
2.11.1

### Description
Google Chrome
版本 75.0.3770.142（正式版本） （64 位）

**Now all child nodes need to be expanded like this**
![current](https://user-images.githubusercontent.com/24710728/62596111-79c54780-b913-11e9-86d7-aede9dd35c92.gif)

**Comment by kwezdj123** [comment]
**Expectation**
click parent nodes, all children nodes will expand

**Comment by kwezdj123** [comment]
Now the problem I am having is that the id, label, and children of each level may be repeated, so you cannot use `node-key` to expand (multiple nodes will be expanded).

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
