### ISSUE TITLE
[Bug Report] After the remote search of el-select, the previously selected item will change its value if it is not in the latest search list.

### ISSUE THREAD

**Issue by zhangminggeek** [ElemeFE/element#16933]
### Element UI version
2.11.0

### OS/Browsers version
Win10/Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhangminggeek/pen/oKEEVe

### Steps to reproduce
1. 在input中输入值'Utah'
2. 在搜索到的列表中选中一项数据{label: 'Utah', value: 'UtahUtah'}
3. 在input中修改输入值‘Vermont’
4. 搜索列表数据发生改变，选中另一项{label: 'Vermont', value: 'VermontVermont'}，发现选中的数据显示内容'Vermont'变更为'VermontVermont'

### What is Expected?
重新搜索后，原来选中的内容不变

### What is actually happening?
重新搜索后，原来选中的内容发生改变

**Comment by luckyCao** [comment]
已知问题
