### ISSUE TITLE
[Bug Report] Tree component uses insertAfter to report errors when lazy loading

### ISSUE THREAD

**Issue by k-water** [ElemeFE/element#16931]
### Element UI version
2.11.1

### OS/Browsers version
macOS Mojave 10.14.5 / Chrome 75.0.3770.100（正式版本）（64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/water_lin/pen/XvZVBO

### Steps to reproduce
1、打开重现链接 https://codepen.io/water_lin/pen/XvZVBO
2、点击按钮

### What is Expected?
节点被正确插入

### What is actually happening?
insertChild函数报错
TypeError: Cannot read property 'indexOf' of undefined

**Comment by ziyoung** [comment]
不支持的操作。
