### ISSUE TITLE
[Bug Report] change select multiple attributes dynamicly bug

### ISSUE THREAD

**Issue by yuedehuanxiang** [ElemeFE/element#16939]
### Element UI version
2.11.1

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/19o3q57e/2/

### Steps to reproduce
change select multiple property is true dynamicly, i have tried put the select into a <Form> component and use Form-Item Methods
resetField but is also not work ,please hele me 

### What is Expected?
when data is empty array , the ui of select  should be cleared

### What is actually happening?
select  ui showing is not correct

**Comment by luckyCao** [comment]
切换成多选的时候加 key
