### ISSUE TITLE
[Bug Report] el-dialog close bug with modal click

### ISSUE THREAD

**Issue by edgarsilk** [ElemeFE/element#16930]
### Element UI version
2.9.1

### OS/Browsers version
win 8.1 / chrome 75

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/EdgarSilk/pen/mNXqpo?&editable=true

### Steps to reproduce
When mousedown inside dialog and release in modal, dialog will be closed(if using close-on-click-modal).
Similarly when mousedown in modal and release inside dialog, dialog will be closed.

### What is Expected?
close-on-click-modal should work only when mousedown and release both in modal.

### What is actually happening?
mousedown inside dialog and release in modal, or mousedown in modal and release inside dialog, both will close dialog

**Comment by yangxiaoqiao2016** [comment]
You need to set 'close-on-click-modal' property as 'false'.
https://codepen.io/yangxiaoqiao/pen/PMQaKQ

**Comment by HydrogenPan19** [comment]
https://github.com/ElemeFE/element/issues/16887#issuecomment-518063373

They said they don't find a solution yet...
