### ISSUE TITLE
Disabled status of [Bug Report] el-tree, sometimes with problems with dynamic settings

### ISSUE THREAD

**Issue by Mrwgy** [ElemeFE/element#16941]
### Element UI version
2.11.1

### OS/Browsers version
win10/谷歌浏览器  75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mrwgy/pen/KOQxgv?editors=1010

### Steps to reproduce
点击按钮，修改treeData数据的disabled值

### What is Expected?
当treeData的disabled切换为true时，el-tree所有节点禁用，且置灰。
当treeData的disabled为false时，el-tree所有节点可用，且清除置灰样式

### What is actually happening?
当treeData的disabled值由false切换为true时，el-tree所有节点禁用，但是没有置灰。
当treeData的disabled值由true切换为false时，el-tree所有节点仍旧处在禁用状态，并且没有清除置灰样式。只有在节点上手动点击一下，才可以正常使用

**Comment by ziyoung** [comment]
直接修改 data。
