### ISSUE TITLE
[Bug Report] submit failed to submit

### ISSUE THREAD

**Issue by zhujianxiong** [ElemeFE/element#16942]
### Element UI version
2.11.1

### OS/Browsers version
谷歌

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
在项目中使用，第一次提交文件，然后后台返回code为-500失败，当再次点击提交的时候无法在触发on-success或者on-error方法

### What is Expected?
能够解决该问题

### What is actually happening?
在项目中使用，第一次提交文件，然后后台返回code为-500失败，当再次点击提交的时候无法在触发on-success或者on-error方法

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
