### ISSUE TITLE
[Bug Report] When the el-scrollbar is initialized, the keyboard key is invalid.

### ISSUE THREAD

**Issue by guyuECMAScript** [ElemeFE/element#16947]
### Element UI version
2.4.6

### OS/Browsers version
mac os 10.14.5 / Chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://github.com/guyuECMAScript/pbx-home

### Steps to reproduce
1.Enter the page  
2.The page cannot be scrolled using the up/down buttons on the keyboard  
3.Use the mouse to click anywhere on the page  
4.The up/down button takes effect and the page can be scrolled  

### What is Expected?
Can use the up/down button when page initializing

### What is actually happening?
If the mouse does not click on the page, the up/down button will be invalid.

**Comment by ziyoung** [comment]
Please provide a simple demo.
