### ISSUE TITLE
[Bug Report] el-input The placeholder property cannot be set with render

### ISSUE THREAD

**Issue by xlz26296** [ElemeFE/element#16945]
### Element UI version
2.11.0

### OS/Browsers version
win10 / Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/618jcxgt/

### Steps to reproduce
The placeholder property cannot be set with render.

### What is Expected?
The placeholder properties can be set using props.

### What is actually happening?
Can't take effect

**Comment by ziyoung** [comment]
```js
attrs: {
  placeholder: '122222',
},
```
