### ISSUE TITLE
Initialize datepicker with moment.js

### ISSUE THREAD

**Issue by mehranrasulian** [ElemeFE/element#1694]
It seems unnecessary but I want to change the calendar from Gregorian to Jalali using moment.js. That's why I want to initialize the date myself.
Is there any option for this?

**Comment by Leopoldthecoder** [comment]
I'm not quite familiar with Gregorian and Jalali, could you explain their differences and what needs to be altered?

**Comment by mehranrasulian** [comment]
Jalali calendar is in use in Iran and I want to integrate it with `element` date picker.

Here is a moment.js example for Gregorian:
```
moment().format('MMMM Do YYYY, h:mm:ss a'); // December 13th 2016, 7:20:23 pm
// 
```

And for Jalali with help of a third party library:
```
moment().format('jMMMM jDo jYYYY, h:mm:ss a'); // Aazar 23rd 1395, 7:15:25 pm
// 
```

**Comment by Leopoldthecoder** [comment]
So on Element's side, you basically just want to set an initial value for DatePicker? Like [this](http://jsfiddle.net/leopoldthecuber/8aj9wutv/)?

**Comment by mehranrasulian** [comment]
Awesome! This is what I was looking for.
