### ISSUE TITLE
Can the text of the <el-switch> switch component be inside the button?

### ISSUE THREAD

**Issue by 941477276** [ElemeFE/element#16940]
### Existing Component
是

### Component Name
`<el-switch>`

### Description
目前<el-switch>开关组件的active-text、inactive-text是在开关的两侧显示的，这在比较紧凑的布局页面中是无法实现与UI设计稿一致的。所以希望<el-switch>开关组件的active-text、inactive-text能放到开关里面去，如下图
![image](https://user-images.githubusercontent.com/20528541/62606487-ee59af80-b92e-11e9-983f-421368bc1971.png)

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by cloydlau** [comment]
This will do it:

```vue
<template>
  <PopSwitch
    active-text="上架"
    inactive-text="下架"
  />
</template>

<script>
// install 'kikimore' first
import { PopSwitch } from 'kikimore'

export default {
  components: { PopSwitch }
}
</script>
```

Width is self-adapting, document [here](https://github.com/cloydlau/kikimore)

**Comment by wuliupo** [comment]
在 1.x 支持这个功能，element-ui 2.x 和 element-plux 3.x 去掉了 @941477276 
https://element.eleme.cn/1.4/#/zh-CN/component/switch
