### ISSUE TITLE
[Bug Report] show-overflow-tooltip is true. Customize column template. When the cell does not contain icons and other non-text elements, tooltip is displayed when the content is too long and hidden. When the text is just full of cells, small icons are added. The tooltip is not displayed and the text has been truncated.

### ISSUE THREAD

**Issue by Blizzard-liu** [ElemeFE/element#16943]
### Element UI version
2.11.1

### OS/Browsers version
win7/electron

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-column.js

### Steps to reproduce
show-overflow-tooltip 为true ,自定义列模板, 当单元格中不包含图标等其他非文字元素时,当内容过长被隐藏时显示 tooltip,  当文字刚好充满单元格后再加入小图标, tooltip不显示,且文字已被截断
```
 <template slot-scope="scope">
                                <div class="col-position-name">
                                    <img src="@assets/img/common/needle-top.svg" />
                                    <span style="margin-left: 6px; margin-right: 4px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; color: #445571;">当文字刚好充满单元格</span>
                                  
                                        <i  class="el-icon-arrow-down" style="color: #98A9BC"></i>
                                  

                                </div>
                            </template>
```
### What is Expected?
tooltip正常显示

### What is actually happening?
tooltip不正常显示

**Comment by Blizzard-liu** [comment]
[](url)
![image](https://user-images.githubusercontent.com/20244432/62613851-e274ea00-b93c-11e9-9560-a75b371fcd1f.png)

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
