### ISSUE TITLE
[Feature Request] lazyload event on Cascader

### ISSUE THREAD

**Issue by AsurawithCross** [ElemeFE/element#16958]
### Existing Component
Yes

### Component Name
Cascader

### Description
您好 ，我在项目中想使用Cascader的懒加载去实现数据分组的功能，现在是我通过懒加载获取的数据中本身带有着children的数据，但是当我点击的时候，依然是触发回调事件，是否可以支持异步加载一个整体的数据？

**Comment by luckyCao** [comment]
这种场景推荐使用非 lazy 模式
