### ISSUE TITLE
[Bug Report] Drawer drawer component cannot be shut down by ESC

### ISSUE THREAD

**Issue by bei123wang** [ElemeFE/element#16954]
### Element UI version
2.11.1

### OS/Browsers version
win10/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/bei123wang/pen/YmaJmx?&editable=true

### Steps to reproduce
鼠标点击 点我打开按钮  need repro -> 按 esc关闭 

### What is Expected?
close-on-press-escape 为 true
按 esc 能关闭抽屉

### What is actually happening?
close-on-press-escape 为 false
按 esc 只能关闭遮罩层

**Comment by bei123wang** [comment]
先这样解决了，在 created() 里面给Drawer 组件绑定 handleClose 函数
created() {
    let _this = this
    _this.$nextTick(_ => {
      if (!_this.$refs.acountDrawer.handleClose) {
        _this.$refs.acountDrawer.handleClose = function() {
          _this.$refs.acountDrawer.closeDrawer()
        }
      }
    })
  },

**Comment by ziyoung** [comment]
#16953
