### ISSUE TITLE
[Bug Report] dropdown not opening inside a table row

### ISSUE THREAD

**Issue by rameezcubet** [ElemeFE/element#16951]
### Element UI version
2.11.1

### OS/Browsers version
ubuntu

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/cjs1fgbq/

### Steps to reproduce
just add an el-dropdown in  a table row fiddle:https://jsfiddle.net/cjs1fgbq/

### What is Expected?
the dropdown should get opened even inside the table row

### What is actually happening?
the dropdown is not getting opened inside a table row

**Comment by rameezcubet** [comment]
HI... Any update on this?

**Comment by gwwnha** [comment]
same problem

**Comment by rameezcubet** [comment]
@wacky6 could you look into this please if you get some free time, I am stuck with this, I can't use any dropdown in table

**Comment by minosss** [comment]
```html
<el-table-column prop="select" label="下拉">
  <template slot-scope="scope">
    ...
  </template>
</el-table-column>
```

**Comment by rameezcubet** [comment]
Adding `slot-scope="scope"` did the trick, Thanks

**Comment by zhuchongyue** [comment]
why must added   slot-scope="scope",  even not use scope attr.
