### ISSUE TITLE
When [Bug Report] uses Google Translate to translate Web pages into Chinese, the day of the calendar component is abnormal.

### ISSUE THREAD

**Issue by EPSON-LEE** [ElemeFE/element#16965]
### Element UI version
2.11.1

### OS/Browsers version
macOS/Mojave 10.14.5 / 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
jsfiddle 中无法复现

### Steps to reproduce
在element-UI官网的datePicker组件文档， 右键翻译成中文， datePIcker 组件中的数字有些变成中文

### What is Expected?
网页经过翻译后，datePIcker 组件中的数字显示正常

### What is actually happening?
网页经过翻译后，datePIcker 组件中的数字翻译异常

**Comment by wacky6** [comment]
Ask google translate why. :)
