### ISSUE TITLE
When [Feature Request] Cascader is multi-selected, there is currently only an array of parent option values, hoping to provide more parameter configuration

### ISSUE THREAD

**Issue by jaihao** [ElemeFE/element#16963]
### Existing Component
是

### Component Name
Cascader 

### Description
希望通过参数配置、能返回指定的参数对象，比如返回[{ label: a, value: a }]，而不仅仅是各父级选项值组成的数组

**Comment by ivila** [comment]
@jaihao 在新版（忘了具体从哪个版本开始了）的element-ui中，cascader的Props参数中新增了一个emitPath，你看看符不符合你的情况。

**Comment by jaihao** [comment]
@ivila emitPath这个配置最终返回该节点的value值、并不包含lable

**Comment by lcoder** [comment]
建议参考下antd的，配置。那真的照顾开发，找个valueInlabel的配置真的是吐血

**Comment by luckyCao** [comment]
可以再描述清晰一点吗？比如给一个例子

**Comment by lcoder** [comment]
@jaihao 已经说明了，他应该是想:emitPath形如：[ { value: 'xxx' , label: 'aaa' } ]。而不是现在的 [ 'xxx' ]
