### ISSUE TITLE
[Bug Report] [el-upload] Upload data prop doesn't respect array format

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/element#16964]
### Element UI version
2.11.1

### OS/Browsers version
Mac OS 10.14.6 Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/hs94c3wv/2/

### Steps to reproduce
- click " upload"
- open dev console and go to the network tab
- select a random picture
- the form data looks wrong

### What is Expected?
The form data is supposed to be an object with a value of type array `["test", "test2"]`
![image](https://user-images.githubusercontent.com/15679461/62751099-63081900-ba17-11e9-8b37-3499d0d74dbe.png)
![image](https://user-images.githubusercontent.com/15679461/62751088-57b4ed80-ba17-11e9-8799-b5f071e9388f.png)

### What is actually happening?
The form data is stringified to `test, test2`
![image](https://user-images.githubusercontent.com/15679461/62751128-774c1600-ba17-11e9-98d3-00180e249d82.png)

**Comment by ziyoung** [comment]
Use `JSON.stringify`.
