### ISSUE TITLE
[Feature Request] table default selections

### ISSUE THREAD

**Issue by wQueryLoveMm** [ElemeFE/element#16962]
### Existing Component
是

### Component Name
ElTable

### Description
sometime , I want to transfer default selctions to Table , but now, it can not  based on the latest version.
Hoping to add default selection to Table component ☺

**Comment by w3cmark** [comment]
可以顺便增加table disable selections吗？目前表格的多选每条都可以勾选，无法设置某条不能勾选。

**Comment by ziyoung** [comment]
Use toggleRowSelection.

**Comment by wQueryLoveMm** [comment]
1. `toggleRowSelection` can  trigger `selection-change` many times, although it can use some methods to resolve but default props must be the most convenience one.
2. when the tableData change , the all selected items will be clear, so, I must wach the tableData then do the same things the 1 step do.  For one watcher has been used in el-table , my own watcher must use `this.$nextTick` or `setTimeout`. Because el-table `tableData` watcher will always clear all the selections I set in my own  `tableData` watcher. It is really inconvenient.

```javascript
// packages/table/src/table.vue
 data: {
        immediate: true,
        handler(value) {
          this.store.commit('setData', value);
        }
      },
// packages/table/src/store/index.js
if (dataInstanceChanged) {
        this.clearSelection();
      } else {
        this.cleanSelection();
      }

```

Hoping to add default selection props to Table component .

Thanks.

**Comment by AMrainman** [comment]
i hope too

**Comment by robsonsobral** [comment]
To not have this is obstacle. I've to update manually the selection after load data from API, after user move back to previous area/tab/component...
