### ISSUE TITLE
[Feature Request] Add option to allow free typing in 'Time Select Options'

### ISSUE THREAD

**Issue by lwxbr** [ElemeFE/element#16960]
### Existing Component
Yes

### Component Name
TimerPicker: Time Select

### Description
The timer select works properly when you have a start (e.g. 09:00), end (e.g. 17:00), and step(e.g: 00:15).
The problem is when you want to type a value between start and end, for example: 12:07. Why not allow free typing in this case? That is the feature I request.

Reference: https://element.eleme.io/#/en-US/component/time-picker#time-select-options

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
