### ISSUE TITLE
[Feature Request] If I have selected a date, could I don't need two to reselect again;

### ISSUE THREAD

**Issue by e-body** [ElemeFE/element#16974]
### Existing Component
是

### Component Name
el-date-picker

### Description
 I was using el-date-picker,such as ,I've selected a date-range ,'2019-08-08'-'2019-08-09'.The next time I wanna select '2018-08-07 - 2018-08-09',when i select '2018-08-07','2019-08-09' was reset to unselected, so I have to reselect it ;May I don't need to reselect both date ,that is to say ,when i wanna select again,I only need to select '2018-08-07',and the result would be  '2019-08-07-2019-08-09' base  on the last result;

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
