### ISSUE TITLE
[Feature Request] add table download as an excel file

### ISSUE THREAD

**Issue by Siyii** [ElemeFE/element#16978]
### Existing Component
是

### Component Name
el-table

### Description
Recently, i have a need like downloading the whole table data as an excel file,when using table componet,so that users can check data in local excel. I could do this by myself but i am wondering if element-ui can add this new function to table component,that would bring much convenient for us. Thanks for reading~

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
