### ISSUE TITLE
[Bug Report] select with allow-create when create the same value the two same values will disappear

### ISSUE THREAD

**Issue by OuZuYu** [ElemeFE/element#16970]
### Element UI version
2.11.1

### OS/Browsers version
win10 / chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/penguinOu/pen/MNByQV?&editable=true

### Steps to reproduce
link：https://codepen.io/penguinOu/pen/MNByQV?&editable=true

1. Input aaa and press Enter
2. Input aaa and press Enter again
3. These two same values will disappear

![GIF](https://user-images.githubusercontent.com/26338853/62849305-bd53f300-bd11-11e9-8843-86d456e9b1df.gif)

### What is Expected?
The new value replaces the old value   like：https://ant.design/components/select-cn/#components-select-demo-tags

### What is actually happening?
These two same values will disappear

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/16986#issuecomment-526994992
