### ISSUE TITLE
使用input输入框 来对table数据进行模糊搜索

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1697]
在input框中输入对应table某一列的数据值，来对table的数据进行搜索，获取到匹配该字的数据。
请问如何实现

**Comment by jasaec** [comment]
1如果数据不多 且是全量的el- table的数据通过store.getters获取
输入框绑定一个action 向store里存储你要搜索的值传的数据{col: value}
在geterrs 用filter( item => item[col] indexof (vlaue))

或者 用el-table 表头render出一个input框 在本地或store里filter

如果数据量大 且分页获取 还是在后端做吧

**Comment by Leopoldthecoder** [comment]
请参照楼上的方案。使用上有疑问的话，尽量在 Gitter 里问，issue 用来报告 bug 和建议功能。

**Comment by qpxtWhite** [comment]
这种方式有个问题，如果有selection，每次filter都会触发table的selection-change，把selection全置为false
