### ISSUE TITLE
[Bug Report] el-select Jumping to item under cursor, when using Arrow keys 

### ISSUE THREAD

**Issue by fedoseiev** [ElemeFE/element#16981]
### Element UI version
2.11.1

### OS/Browsers version
macOS 10.13.4 / Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/F_E_D/pen/oKMWyr

### Steps to reproduce
1. Open select, put cursor at one of the first rows
2. Start moving down using Arrow Down
3. Proceed to the option that not shown in current view

### What is Expected?
Expecting hovering on next dropdown item

### What is actually happening?
We bounce back to the item that placed under our cursor

**Comment by luckyCao** [comment]
Sorry, we have no plan to fix this.
