### ISSUE TITLE
[Feature Request] Perfect picture preview function

### ISSUE THREAD

**Issue by aiwozhe** [ElemeFE/element#16985]
### Existing Component
Yes

### Component Name
el-image

### Description
当preview-src-list存在src时，点击图片放大定位到src所在的index，将图片设置为当前预览项

**Comment by kuaitukeji** [comment]
el-Image 组件  

支持完成此功能：当preview-src-list存在src时，点击图片放大定位到src所在的index，将图片设置为当前预览项

**Comment by lcb1208** [comment]
组件中有index，不知道为啥作者没暴露出来

**Comment by qdbbm** [comment]
这个问题修复了吗？
