### ISSUE TITLE
[Bug Report] How does el-table-column prop use Vue global filter

### ISSUE THREAD

**Issue by kxion** [ElemeFE/element#16988]
### Element UI version
2.11.1

### OS/Browsers version
mac / chrome

### Vue version
2.6.10

### Reproduction Link
github.com

### Steps to reproduce
<el-table-column :prop="created_on|formatdate" align="center" label="创建时间" width="200"></el-table-column>

### What is Expected?
正常格式化时间

### What is actually happening?
vue.runtime.esm.js?2b0e:619 [Vue warn]: Property or method "created_on" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ArticleList> at src/views/NewsList.vue
       <Index> at src/views/Index.vue
         <App> at src/App.vue
           <Root>

**Comment by rickysang** [comment]
Use `Vue.prototype._f()` to resolve filter and use formatter prop to format value
``` html
<el-table-column prop="create_on" :formatter="(row, column, cell) => _f('formatdate')(cell)" />
```

Or use scoped slot
``` html
<el-table-column>
  <template #default="{ row }">{{ row.create_on | formatdate }}</template>
</el-table-column>
```

**Comment by luckyCao** [comment]
@rickysang thx
