### ISSUE TITLE
[Bug Report] el-table tree structure cannot read table data and update nodes when it is lazy to load

### ISSUE THREAD

**Issue by Churchson** [ElemeFE/element#16982]
### Element UI version
2.11.1

### OS/Browsers version
window 7 / Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/churchson/pen/MNBNWN?editors=0002

### Steps to reproduce
1、运行代码
2、 点击懒加载表格的数据，至少加载一次
3、 点击右侧按钮 【获取数据】
4、查看控制台打印

### What is Expected?
表格的数据读取和显示同步，还有最好可以有树表格的操作接口进行操作

### What is actually happening?
读取数据和表格显示不一致，无法对表格进行操作

**Comment by ziyoung** [comment]
data 是 prop，组件 table 是不会修改 data 的。不支持这样的功能。

**Comment by Churchson** [comment]
@ziyoung 如果无法直接修改 table的data 的话，希望可以提供一个接口直接获取加载后的表格的所有的数据。那就可以根据数据进行修改了

**Comment by Lanseria** [comment]
有其他解决方案吗
