### ISSUE TITLE
[Tble]firefox中表格width无效 

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#1698]
### OS/Browers version
 firfox50.0.2 win10

**Comment by jixzfw** [comment]
<el-table :data="mate.rows" border  @selection-change="handleSelectionChange">
          <el-table-column type="selection" width="50"></el-table-column>
        <template v-for="col of mate.columns">
          <el-table-column :label="col.label" :prop="col.name" :width="col.width">
        </template>
      </el-table>

**Comment by Leopoldthecoder** [comment]
试了一下，是可以的：http://jsfiddle.net/2rqgexhr/
看一下你的用法有没有问题吧。

**Comment by jixzfw** [comment]
F12显示，不同的地方在于 ，不知为什么，我的代码生成的是colgroup，而不是 col ,是不是这个原因？

**Comment by jixzfw** [comment]
重建模块，直接好了
