### ISSUE TITLE
[Bug Report] [Bug Report] When using merged rows, only the first row has a hover effect.

### ISSUE THREAD

**Issue by GQxQD** [ElemeFE/element#16994]
### Element UI version
2.8.2

### OS/Browsers version
Windows 1064 bit/Chrome 75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/gqxqd/pen/VoEgJR?&editable=true

### Steps to reproduce
1. Use merged row tables

2. Mouse hover to merge rows

### What is Expected?
The same merged bank should have the same hover effect

### What is actually happening?
Only the first line has a hover effect

**Comment by luckyCao** [comment]
Sorry, we have no plan to fix this.
