### ISSUE TITLE
[Bug Report] el-table and row-style attribute returning display: none don't work in the first place after component initialized. The bug can't be seen in version 2.6.3, and appear since 2.7.0.

### ISSUE THREAD

**Issue by pansila** [ElemeFE/element#16995]
### Element UI version
2.7.0

### OS/Browsers version
Windows

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/JQdaYj

### Steps to reproduce
el-table row-style属性 第一次返回 display:none无效，
我的目的是用element开发可折叠的树形表格

### What is Expected?
第一次加载时按条件隐藏行

### What is actually happening?
如果只是返回颜色如color:red 是有效的，display: none则无效

这个问题在[16048](https://github.com/ElemeFE/element/issues/16048)中已经被提示是Vue的实现问题，但是没有提供解决方案。但是在2.7.0之前并没有这个问题，故怀疑并不只是Vue单方面的问题，也和element table的实现有关，希望有实际的解决问题的办法。谢谢！

**Comment by Eflet** [comment]
高度设置成0不行么，你可以试下bootstrap的sr-only那个style
不过，不想显示这行的话，为啥不在数据里面暂时去掉这一条呢，为了不重绘么？

**Comment by pansila** [comment]
@Eflet 这个Vue的限制早就有了，但是在Element UI2.6.3还能这么用的，到2.7.0就不行了很奇怪，这种限制让我的代码很别扭。

**Comment by Eflet** [comment]
应该是el-table的tree功能加上去的v-show吧

**Comment by pansila** [comment]
@Eflet 2.7.0引入的tree功能么？那就说得通了

**Comment by linzhi** [comment]
我也遇到了这个问题 明明 return 'display:none' 可是前端还是展示了隐藏的row

**Comment by luckyCao** [comment]
can not reproduce
