### ISSUE TITLE
[Bug Report] Cannot enter time-range ending at midnight

### ISSUE THREAD

**Issue by ray007** [ElemeFE/element#16999]
### Element UI version
2.11.1

### OS/Browsers version
Windows 10 / Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ray007/pen/pMGOWa

### Steps to reproduce
Try to enter time-range ending at midnight

### What is Expected?
Time-range end at "24:00"

### What is actually happening?
Last available value for range-end is "23:59:59"

Note: having to create a code-pen for stuff that can be seen in the official docs is an unnecessary hassle for reporters.

**Comment by xrkffgg** [comment]
The latest time is '23:59:00', and its next is '00:00:00'.

**Comment by ray007** [comment]
> 
> 
> The latest time is '23:59:00', and its next is '00:00:00'.

But you cannot enter it as end-time of a range unless the start-time is "00:00:00" too.
In in 24 hour mode, 24:00 would look a lot better as end time...

**Comment by luckyCao** [comment]
Sorry, we have no plan to fix this.

**Comment by ray007** [comment]
While I have to accept "no plan to fix", it's still a bug. So closing it seems strange...
