### ISSUE TITLE
[Feature Request] el-Image component supports event Click preview maps

### ISSUE THREAD

**Issue by WQone** [ElemeFE/element#16992]
### Existing Component
是

### Component Name
el-Image

### Description
目前的大图预览功能是使用previewSrcList参数，希望能结合上传组件，实现比如点击某个图标去预览大图

**Comment by kuaitukeji** [comment]
el-Image 组件  希望能结合上传组件, 预览图片

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
