### ISSUE TITLE
运行不起来。。。

### ISSUE THREAD

**Issue by yuu2lee4** [ElemeFE/element#17]
win10

一堆依赖没有写到package.json里面。。。在一个一个写入并安装之后。。。终于不再报错。。打开浏览器    输入地址   额  一片空白

**Comment by QingWei-Li** [comment]
我们是用 lerna bootstrap 安装子模块的依赖的，你要执行 `npm run dev` 会去安装依赖 => 安装子模块依赖 => 编译需要的文件 => 运行 webpack

**Comment by yuu2lee4** [comment]
因为我是用cnpm  所以 我把npm run dev 的npm i去掉了 自己用cnpm装了  再运行 npm run dev  ，这样不可以嘛？

**Comment by QingWei-Li** [comment]
哦 估计没触发 postinstall 这个 script?  那你手动执行下 `npm run postinstall` 吧

**Comment by yuu2lee4** [comment]
这个应该是触发过的。。。。。

**Comment by QingWei-Li** [comment]
那你看下页面的 devTools 控制台里报什么错

**Comment by yuu2lee4** [comment]
vue.common.js?d187:2503 [Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build. (found in component <app>)

**Comment by QingWei-Li** [comment]
建议你还是删掉你的 node_modules 重新 `npm run dev` 吧，我们这边试过都没问题的，如果你觉得 npm install 慢的话可以用 https://github.com/cnpm/npminstall 这个

**Comment by yelingfeng** [comment]
win10 确实费劲 我也没起来 一道make命令就挂

**Comment by QingWei-Li** [comment]
win 没有 make 呀，所以文档上说了直接 `npm run dev`

**Comment by yuu2lee4** [comment]
ok了。。。我能说一股浓浓的ant design的相似感么 
![image](https://cloud.githubusercontent.com/assets/8046366/18308497/5629be06-7527-11e6-99ff-bbc97dcdca90.png)

**Comment by QingWei-Li** [comment]
一定是错觉 🌚
