### ISSUE TITLE
[Feature Request] el-dropdown with el-select functionality

### ISSUE THREAD

**Issue by dmitryfar** [ElemeFE/element#17000]
### Existing Component
Yes

### Component Name
dropdown, select

### Description
There is no possible easy way to join dropdown with el-select functionality.
ElSelect doesn't allow use any icon to trigger popup and show filter-input element in header of the popup. With scroller, groups, etc.
ElDropdown doesn't allow grouping and filtering items like it does ElSelect.
It's too hard to extend and easy leverage existed components for that.

**Comment by dmitryfar** [comment]
Example:
![dropdown-select](https://user-images.githubusercontent.com/3054585/62875951-9bb43500-bd2c-11e9-8737-924ba274e445.png)

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
