### ISSUE TITLE
[Bug Report] cannot customize the style of the select drop-down box

### ISSUE THREAD

**Issue by subdance** [ElemeFE/element#17006]
### Element UI version
2.11.1

### OS/Browsers version
macos 10.14.6

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/subdance/pen/MWgavZX?&editable=true

### Steps to reproduce
点开下拉菜单

### What is Expected?
下拉菜单中的item高度被自定义

### What is actually happening?
在select组件下拉菜单中使用了了自定义DOM，插入了一个div。但是在css scoped的情况下无法通过popper class属性结合/deep/来覆盖原生的样式

**Comment by xrkffgg** [comment]
https://codepen.io/xrkffgg/pen/VwZvrvy

在你上面 改动了一下，不知道是不是 你要的效果

**Comment by subdance** [comment]
> https://codepen.io/xrkffgg/pen/VwZvrvy
> 
> 在你上面 改动了一下，不知道是不是 你要的效果

@xrkffgg 谢谢，确实要实现自动高度并不难，但是我想的是可以在保留scoped的情况下使用/deep/覆盖原生样式，像iview那样。就可以毕竟不使用scoped可能会污染样式。

**Comment by xrkffgg** [comment]
@subdance 你可以在前面加上ID，这样 重定义的样式 也只是在当前 页面适用，即 scoped

**Comment by nullptru** [comment]
popper class 使用的类名无法获取 scoped css 的scopeId，因此目前此方法只能使用全局类名...
先关闭了该 Issue
