### ISSUE TITLE
[Feature Request] Can I Change the module "async-validator" as my own fork repository

### ISSUE THREAD

**Issue by Riant** [ElemeFE/element#17001]
### Existing Component
Yes

### Component Name
async-validator

### Description
Because we need to change some lines in async-validator, so I fork it, but can I change it in element-ui dependence version? and how to do that.

I know this should be a webpack point, but I did not get any solution after google, so hope get some help on there.

Thanks.

**Comment by luckyCao** [comment]
Sorry, we have no plan to support this.
