### ISSUE TITLE
How does the [Bug Report] el-tree Load method not execute when checkbox is selected? Load I just want to trigger when the arrow is selected

### ISSUE THREAD

**Issue by comeOutBing** [ElemeFE/element#17015]
### Element UI version
1.4.13

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/comeoutbing/pen/BebVmv

### Steps to reproduce
1.勾选节点，会触发Load绑定的方法

### What is Expected?
1.希望勾选的时候不触发，只有在点击箭头或者点击内容触发（2.0版本已经没有这个问题，但1.0版本存在，请问怎么规避）

### What is actually happening?
勾选时会触发Load绑定的方法

**Comment by luckyCao** [comment]
Sorry, we have no plan to fix this.
