### ISSUE TITLE
[Feature Request] add mousenter event for select mutipile tag

### ISSUE THREAD

**Issue by feaswcy** [ElemeFE/element#17016]
### Existing Component
是

### Component Name
select

### Description
Can you add mouseover Events for multiple select ? 

In some case , user need hover the tag to see more details, 

Or i will copy the file and do it myself...

-----------------------------
能否给select在multiple模式下选择的tag 增加mouseover属性？ 看源码生成的el-tag里没有这个配置，但是有些场景，select下啦的信息是比较复杂的，用户选择之后却只有一个label，希望能增加mouseenter等event，或者官方支持pophover那就更好啦～

**Comment by luckyCao** [comment]
pr welcome
