### ISSUE TITLE
element-ui table tree no getHalf method

### ISSUE THREAD

**Issue by hillboyzone** [ElemeFE/element#17017]
### Element UI version
0.1.0

### OS/Browsers version
win7 / chrome (latest version)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/bassb/pen/BXjLYv

### Steps to reproduce
1. Unchecked the one of sub-item which top parent displays half icon, another sub-parent displays nothings anyway.

### What is Expected?
1. Sub-parent displays half icon as same as top parent's behavior.

### What is actually happening?
1. Top parent displays half icon when checked part of items.
2. Sub-parent displays nothings anyway when  checked part of sub-items.

**Comment by luckyCao** [comment]
已知问题
