### ISSUE TITLE
[Bug Report] when moving the el-slider's slider,the slider's tooltip componenet will have about one pixel offset on vertical

### ISSUE THREAD

**Issue by laiiihz** [ElemeFE/element#17018]
### Element UI version
2.11.1

### OS/Browsers version
windows 10 1903 / chrome  75.0.3770.142

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/laiiihz/pen/ExYPjOa

### Steps to reproduce
moving the el-slider's slider

### What is Expected?
the slider's tooltip should not move on vertical 

### What is actually happening?
the slider's tooltip have about one pixel offset on vertical

**Comment by xrkffgg** [comment]
准确的说 是 2px 
感觉 是因为 tab 切换时，outline 的上下边距 2px
还在找解决办法

**Comment by xrkffgg** [comment]
找到原因了。。。。
@laiiihz 
是因为 dragging 的时候 按钮放大了 1.2 倍，
鼠标放上去的时候，
出现 tooltip 还是按照原来尺寸计算的，
拖动的时候是按照 1.2 倍 ，
去掉 1.2 的放大效果，tooltip 的位置 就不会变动了

要解决的话
看看 让 tooltip 出现的时候 计算上 放大的尺寸 应该就行

我再研究研究

**Comment by laiiihz** [comment]
谢谢回复，我来学习学习 @xrkffgg

**Comment by island205** [comment]
pr welcome
