### ISSUE TITLE
[Feature Request] Requests to enrich support for on-demand references

### ISSUE THREAD

**Issue by XSun771** [ElemeFE/element#17010]
### Existing Component
是

### Component Name
*

### Description
在官方文档的快速上手章节中谈到按需引用，我是打算用这种方法开发的。
但是实际在选择一个组件，比如“NavMenu 导航菜单”组件时，我打开这个组件的页面，却不知道要引入什么东西。
我按照最自然的逻辑，参考之前的指南，这么写：
import "element-ui/lib/theme-chalk/index.css";
import {NavMenu} from 'element-ui';
Vue.componet(NavMenu.name, NavMenu}
然后复制给出的示例中的第一个，报错。
取而代之的，如果我直接全部拿过来用，这么写。
import "element-ui/lib/theme-chalk/index.css";
import ElementUI from "element-ui";
Vue.use(ElementUI);
就没有任何问题了。
那我推测是我漏掉了一些要引入的东西。但是这些东西是什么？该怎么引入？组件的页面上完全没有介绍，我觉得这很不合理。希望能够丰富对此的支持。

**Comment by Eflet** [comment]
那个控件叫Menu，不是NavMenu
import {Menu} from 'element-ui'
