### ISSUE TITLE
el-pagination控件当前页面显示不正确

### ISSUE THREAD

**Issue by kysyuan126** [ElemeFE/element#17024]
当主动点分页条上的页面时，当前页号显示没有问题，但当初始指定页号进入页面时，当前页码指定不正确，但控件内指示内部与外部属性，两个变量不一致，如下图所示。
![image](https://user-images.githubusercontent.com/6134190/62993160-dc28c580-be88-11e9-88df-c95d7829ac6e.png)

**Comment by websmallrabbit** [comment]
同问，
 问题描述：
 分页组件中，我在每页10条数据上， 选择第二页，然后选择每页20条，会以每页20条第一页请求但是，页码还是显示第2页高亮

**Comment by Sopcce** [comment]
i have this bug  

```
 <el-pagination background layout="prev, pager, next" @size-change="handleSizeChange" @current-change="handleCurrentChange" :total="total">
    </el-pagination>
```

total =96 


![image](https://user-images.githubusercontent.com/12589684/86216370-851b0480-bbb0-11ea-9b2e-846302e9d455.png)



我并没有找到解决办法，等我想想怎么处理，设置100 是可以的，

**Comment by zhaosheng808** [comment]
这个问题依然存在！！！2020.11.30 
主动点击的时候没问题 但是初始化设置值的时候就不一致！！！
```
<el-pagination layout="total, prev, pager, next, jumper"
                     @current-change="currentChange"
                     :current-page.sync="page"
                     :page-size="size"
                     :total="total">
</el-pagination>

data(){
  return{
    page: 1,
    size: 10,
  }
}
mounted(){
  this.page = 2;
  // 分页依然显示 第一页
}
```

**Comment by CodeHuai** [comment]
离谱， 昨天是好的，今天就出现这个问题了

**Comment by stephenwong1991** [comment]
目前该问题还存在，我的解决办法是给 el-pagination 组件添加一个 key 但凡非点击改变时，改变 key 值将组件强制 render 这样显示就正常了
