### ISSUE TITLE
[Bug Report] When selecting multiple remote searches, the previous selection shows a problem. I tested the value displayed.

### ISSUE THREAD

**Issue by Zeus-Iqd** [ElemeFE/element#17028]
### Element UI version
2.11.1

### OS/Browsers version
mac/windows

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zeus-iqd/pen/BaBjvYN

### Steps to reproduce
输入a, 选择一个，再输入c,再选择一个，前面的展示有问题。

### What is Expected?
可以正常展示之前选择的。

### What is actually happening?
不能正常展示之前选择的。（我的测试是之前展示的内容为value,而非label）

**Comment by Zeus-Iqd** [comment]
@iamkun

**Comment by Rebecca-z** [comment]
有人解决嘛？遇见同样问题了！

**Comment by ziyoung** [comment]
已知问题。
