### ISSUE TITLE
[Feature Request] el-table tree data shows why the same level is not aligned?

### ISSUE THREAD

**Issue by CarrySun** [ElemeFE/element#17029]
### Existing Component
是

### Component Name
el-table

### Description
el-table 的树形数据展示 同一level不对齐吧 （比较有子节点 和 无子节点的行）

element-ui的 。。。
![WechatIMG10](https://user-images.githubusercontent.com/36665362/63005525-52402300-beaf-11e9-9d9a-a3355ddbce6c.png)
ant design 的 是对齐的
![WechatIMG9](https://user-images.githubusercontent.com/36665362/63005514-4e140580-beaf-11e9-95df-e603d09d3127.png)

-.- 希望重视一下 视觉体验

**Comment by island205** [comment]
pr welcome
