### ISSUE TITLE
[Bug Report] cannot set the default checked value while using multiple and lazy option

### ISSUE THREAD

**Issue by macarole** [ElemeFE/element#17022]
### Element UI version
2.11.1

### OS/Browsers version
windows10 chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/vivianus/pen/LwGMgj

### Steps to reproduce
use the cascader with multiple and lazy option to submit a form,next time open the form to edit, and you'll find you have no ways to initialize that cascader again,so  how to initial the cascader in this case?

### What is Expected?
has the ability to set default checked while using muliple and lazy option,

### What is actually happening?
if i use that cascade with muliple and lazy option in a form,i cannot initialize the cascader in  that form when i enter in 'edit' mode

**Comment by erichmlyh** [comment]
+1 meet the same problem

**Comment by HongHomeDong** [comment]
+1

**Comment by 13632225945** [comment]
+1

**Comment by takahashikazuki** [comment]
+1

**Comment by YUUtan1994** [comment]
Are there other solutions?same problem here.
