### ISSUE TITLE
[Feature Request] How to make height responsive according to data in fixed header table?

### ISSUE THREAD

**Issue by cyh41** [ElemeFE/element#17038]
### Existing Component
是

### Component Name
table

### Description
场景一：如果表格内没有数据的话，则不给高度，默认最小高度                  
场景二：表格数据高度导致超过配置的高度（比如给个500px），则超出滚动条，并且头部固定                  
场景三：如果表格有数据，且数据不超过配置最大高度，则根据数据自适应高度

**Comment by ziyoung** [comment]
Use `max-height`.
