### ISSUE TITLE
异步加载数据导致头部gutter暂时隐藏

### ISSUE THREAD

**Issue by Forx-Js** [ElemeFE/element#17032]
### Element UI version

2.11.1

### OS/Browsers version

Google

### Vue version
2.6.6

### Reproduction Link

https://codepen.io/forx-js/pen/abodxyY

### Steps to reproduce

表格固定高度,**异步**加载数据,使表格出现滚动条,会导致头部中的`.gutter`元素宽度为0,并`display:none`;重新调整尺寸触发dom重绘后恢复正常

### What is Expected?

头部中的`.gutter`元素最初不该消失

### What is actually happening?

在IE浏览器中会导致列与头部对齐效果出现问题

**Comment by han-neil** [comment]
你好，想问一下，你这个问题解决了吗

**Comment by EchoWht** [comment]
这个自动关闭真的是
