### ISSUE TITLE
[Feature Request] Loader as a independent component.

### ISSUE THREAD

**Issue by lwxbr** [ElemeFE/element#17035]
### Existing Component
Yes

### Component Name
Loading

### Description
Loading feature works good in Table and in fullscreen mode. But I want a independent component of loader (like a spinner, a wheel, or simply the text 'Loading...'). That would be useful for many situations out-of-the-box and out of Element UI.

PS.: The infinite scroll component doesn't have a loader component.

**Comment by ziyoung** [comment]
RR welcome.
