### ISSUE TITLE
[Bug Report] El-checkbox's margin is set to 0 in el-tree

### ISSUE THREAD

**Issue by yujinpan** [ElemeFE/element#17034]
### Element UI version
2.11.0

### OS/Browsers version
MacOS 10.14 / Chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yujinpan/pen/oNvbOGa

### Steps to reproduce
Now you can see the problem directly in the official component instance：
https://element.eleme.cn/#/zh-CN/component/tree#ke-xuan-ze

![problem image](https://user-images.githubusercontent.com/20787785/63014488-42c9d580-bec1-11e9-9dd6-677e27cec14f.png)

**Comment by yujinpan** [comment]
`.el-checkbox:last-of-type { margin-right: 0 }` resulting in.

**Comment by VanJunming** [comment]
the version of 2.10.1 has margin-right, but on 2.11.0 disappear 
![image](https://user-images.githubusercontent.com/17316827/63317504-b8142b00-c345-11e9-917a-8d94cce2a14a.png)

**Comment by xiaojueji** [comment]
It looks uncoordinated

**Comment by ziyoung** [comment]
fixed in 2.12.0.
