### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by jinan5694** [ElemeFE/element#1703]
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-32d09315!./~/vue-loader/lib/selector.js?type=styles&index=0!./examples/app.vue
**Module not found: Error: Cannot resolve 'file' or 'directory' ./assets/styles/fonts/assets/styles/fonts/icomoon.eot** in D:\Users\nan.ji\Documents\GitHub\element\examples
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-32d09315!./~/vue-loader/lib/selector.js?type=styles&index=0!./examples/app.vue 6:991-1062 6:1085-1156

运行 npm run dev 报错
已经检查对应目录，能找到字体文件

**Comment by QingWei-Li** [comment]
非 Element 问题，我们没用过 icomoon 的字体，请自行检查文件路径是否引用正确

**Comment by jinan5694** [comment]
element/examples/assets/styles/fonts/
这个目录下有字体和相关的样式文件
