### ISSUE TITLE
[Bug Report] Documentation -  Custom validation rules - Example is wrong

### ISSUE THREAD

**Issue by andrewgrano** [ElemeFE/element#17037]
### Element UI version
0.1.0

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/examples/docs/en-US/form.md#custom-validation-rules

### Steps to reproduce
Look at the example under "Form - Custom validation rules" here: https://element.eleme.io/#/en-US/component/form#custom-validation-rules

See the 3 functions inside of data() called checkAge, validatePass, validatePass2
These functions should not live inside data() and instead should be moved to methods() because you should not put functions inside of data()

Then update these 3 lines inside of the rules object:
validator: this.validatePass instead of validator: validatePass 
validator: this.validatePass2 instead of validator: validatePass2
validator: this.checkAge instead of validator: checkAge

### What is Expected?
see above

### What is actually happening?
see above

**Comment by ziyoung** [comment]
Pr welcome.
