### ISSUE TITLE
[Bug Report] DatePickers and Selects popover didnt collapse on click outside in mobile Safari

### ISSUE THREAD

**Issue by Imabigcookie** [ElemeFE/element#17046]
### Element UI version
2.10.0

### OS/Browsers version
IOS Mobile Safari

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lky5230/pen/WNewoqy?&editable=true

### Steps to reproduce
Open select or datepicker and click outside them

### What is Expected?
Popover must collapse

### What is actually happening?
Nothing

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1
