### ISSUE TITLE
[Bug Report] If el-carousel-item contains <a> , when I press Tab , the first el-carousel-item will offset to the right. It's wrong 

### ISSUE THREAD

**Issue by KINGMJ** [ElemeFE/element#17041]
### Element UI version
2.11.1

### OS/Browsers version
Chrome/Edge/Firefox

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/JerryMei/6ocwej1d/5/

### Steps to reproduce
just press Tab

### What is Expected?
Should nothing happen

### What is actually happening?
The first el-carousel-item offset to the right

**Comment by javanoclaw** [comment]
**使用tabindex**
```
<el-carousel arrow="never" :autoplay="false" indicator-position="none">
  <el-carousel-item>
       这是第一个item
  </el-carousel-item>
   <el-carousel-item>
      这是第二个item
    <el-link type="primary" tabindex="-1">默认链接</el-link>
  </el-carousel-item>
</el-carousel>
```

**Comment by ziyoung** [comment]
@javanoclaw thanks.
