### ISSUE TITLE
[Bug Report] How to render the label of elementui through v-html

### ISSUE THREAD

**Issue by Codezero123** [ElemeFE/element#17048]
### Element UI version
2.11.1

### OS/Browsers version
win10/chrome

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
无

### What is Expected?
vue使用v-html能解析elementui标签

### What is actually happening?
无法正确的解析出来

**Comment by ziyoung** [comment]
建议学习 Vue.js。

**Comment by JonSnow-JY** [comment]
铁子，这个问题解决了吗，我最近也遇到这个问题了
