### ISSUE TITLE
[Bug Report] Screen readers read "readonly" after blurring select component

### ISSUE THREAD

**Issue by tylertrotter** [ElemeFE/element#17050]
### Element UI version
2.11.1

### OS/Browsers version
Windows/Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/tylertrotter/pen/dybMJzq

### Steps to reproduce
With a screen reader such as NVDA running, blur a select element, the screen reader will read "read only" before reading whatever it is focusing on.

### What is Expected?
It would be nice for the screen reader to not say "readonly" since that is completely unhelpful to the user. I'm not sure why the readonly attribute needs to be added to the input since as soon as you focus it you can edit it. If it is unnecessary it would be nice for it to be taken off.

### What is actually happening?
Screen readers will read "read only" when blurring select component.

**Comment by island205** [comment]
pr welcome
