### ISSUE TITLE
[Bug Report] Cascader Multiple Selection does not trigger changes if the child ren field exists but is empty

### ISSUE THREAD

**Issue by grace618** [ElemeFE/element#17059]
### Element UI version
2.11.1

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?editors=1111

### Steps to reproduce
选择第一个cascader ，children字段存在但为空，不会触发变化

### What is Expected?
cascader 多选时如果children字段存在但为空，不会触发变化,这种是合理的吗

### What is actually happening?
cascader 多选时如果children字段存在但为空，不会触发变化,这种是合理的吗

**Comment by SimonaliaChen** [comment]
Issues without a valid reproduction link will be closed directly.
