### ISSUE TITLE
DatePicker 日期比当前选择的小1天？

### ISSUE THREAD

**Issue by CharkeyQK** [ElemeFE/element#1705]
### ElementUI version
1.0.6

### OS/Browers version
Chrome 54

### Vue version
2.0.3

### Steps to reproduce
```
<el-date-picker
      size="small"
      v-model="birthDate"
      type="date"
      placeholder="选择日期">
    </el-date-picker>
```

比如选择 2016-12-14 , 在 chrome console 可以看到实际日期值为 “birthDate: "2016-12-13T16:00:00.000Z"”

**Comment by QingWei-Li** [comment]
那个是 UTC。。。。自己 new Date('2016-12-13T16:00:00.000Z') 就知道了
