### ISSUE TITLE
[Feature Request] date-time-picker is very stuck.

### ISSUE THREAD

**Issue by Lymlair** [ElemeFE/element#17056]
### Existing Component
是

### Component Name
el-date-picker type=datetime

### Description
我在自己的项目引用 el-date-picker type=datetime的时候，点击选择日期和使用时间滚轮都很卡，在官网上体验却不卡，请问有人明白这是为什么吗？（因为很卡我不会翻译成英文，所以就写的中文了，抱歉）

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
