### ISSUE TITLE
[Bug Report] Unlike native select, tabbing out of select menu does not select active option

### ISSUE THREAD

**Issue by tylertrotter** [ElemeFE/element#17051]
### Element UI version
2.11.1

### OS/Browsers version
Windows 10/Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/tylertrotter/pen/xxKVJpO?editors=1111

### Steps to reproduce
Change selected option by pressing up or down arrow when the select component is focused. Now tab away. Note that the selection did not stick. Contrast this to the native select element.

### What is Expected?
The last selected item will be the value of the component when blurred.

### What is actually happening?
The value before expanding the menu is restored as the value of the component.

**Comment by tylertrotter** [comment]
I'm working on a PR for this now.

**Comment by island205** [comment]
pr welcome

**Comment by SatanEnglish** [comment]
@tylertrotter  @island205 
Any news on getting tab to work?
Alternatively any suggestion on work around?
