### ISSUE TITLE
[Feature Request] TimePicker 12hr format

### ISSUE THREAD

**Issue by nchayabutr** [ElemeFE/element#17068]
### Existing Component
Yes

### Component Name
TimePicker (el-time-select)

### Description
Would you please add 12hr format with am/pm for el-time-select. The documentation on your page describes using format="hh:mm:ss A" but I don't think it's been implemented, or has it?

**Comment by island205** [comment]
#16959

**Comment by mattheyan** [comment]
@island205 @iamkun I was able to implemented this, supporting the `format` option in `<el-time-select>`. Since there isn't any overlap with the AM/PM toggle work I'll submit it as a separate PR.
