### ISSUE TITLE
[Bug Report] Table - In certain circumstances, the width of table header gutter  is 0, Causing the table to be misplaced

### ISSUE THREAD

**Issue by Zkangmas** [ElemeFE/element#17060]
### Element UI version
2.11.1

### OS/Browsers version
Windows10 / Chrome76

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zkangmas/pen/YzKqMEJ

### Steps to reproduce
1. table initial data value assigned to []
2. Set the width of each table-column to ensure that the horizontal scrollbar can appear after step 4.
3. Set the height attribute of the table ensures that the vertical scrollbar can appear after step 4.
4. Update the data value of the table in asynchronous mode.
5. Observe the table header gutter

### What is Expected?
The table header gutter can be set width correctly

### What is actually happening?
 The width of table header gutter  is 0

**Comment by liangwenjie08** [comment]
> ### Element UI version
> 2.11.1
> 
> ### OS/Browsers version
> Windows10 / Chrome76
> 
> ### Vue version
> 2.6.10
> 
> ### Reproduction Link
> https://codepen.io/zkangmas/pen/YzKqMEJ
> 
> ### Steps to reproduce
> 1. table initial data value assigned to []
> 2. Set the width of each table-column to ensure that the horizontal scrollbar can appear after step 4.
> 3. Set the height attribute of the table ensures that the vertical scrollbar can appear after step 4.
> 4. Update the data value of the table in asynchronous mode.
> 5. Observe the table header gutter
> 
> ### What is Expected?
> The table header gutter can be set width correctly
> 
> ### What is actually happening?
> The width of table header gutter is 0
Have you solved it?

**Comment by liangwenjie08** [comment]
Have you solved it ?

**Comment by Zkangmas** [comment]
> Have you solved it ?

Need to call the doLayout method when the data is updated.

![image](https://user-images.githubusercontent.com/22407918/63237850-2c7f9900-c276-11e9-8a5c-ece47975ddc1.png)
This code should come back in table.vue

**Comment by xiaogaofudao** [comment]
升级 2.13.0 还是存在表头，表体 边框错位问题
