### ISSUE TITLE
[Bug Report] Cascader cascade selector search for selected data echo error

### ISSUE THREAD

**Issue by 506137411** [ElemeFE/element#17061]
### Element UI version
2.11.1

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/506137411/pen/NWKNVmX

### Steps to reproduce
1.搜索选中第三个资源的某一项
2.重新搜索选中第三个资源的某一项
3.再次打开级联器

### What is Expected?
多次搜索重新打开级联选择器，能够正确显示数据

### What is actually happening?
多次搜索重新打开级联选择器，数据显示错误

**Comment by ziyoung** [comment]
Can't reproduce.
