### ISSUE TITLE
[Bug Report] Text <Input> 's cursor height not correct in Safari

### ISSUE THREAD

**Issue by smoothdvd** [ElemeFE/element#17069]
### Element UI version
2.11.1

### OS/Browsers version
macOS 10.14 and above

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
1. active the text input field
2. the cursor's height is as same as input height

### What is Expected?
Default cursor's appearance need some padding, as same as in Chrome.

### What is actually happening?
Default cursor's appearance without padding on top and bottom

Screenshot of Safari
<img width="203" alt="Screen Shot 2019-08-17 at 10 57 56 AM" src="https://user-images.githubusercontent.com/22420/63205992-7da95480-c0df-11e9-9d72-5ba8a6d311e7.png">

Screenshot of Chrome
<img width="196" alt="Screen Shot 2019-08-17 at 10 57 06 AM" src="https://user-images.githubusercontent.com/22420/63205995-869a2600-c0df-11e9-953e-8b59cd16823c.png">

**Comment by island205** [comment]
pr welcome
