### ISSUE TITLE
[Bug Report] Upload component settings accept = "image / *"; when I drag a file that is not an image, on-change && beforeUpload will not fire

### ISSUE THREAD

**Issue by baymax2** [ElemeFE/element#17062]
### Element UI version
2.11.1

### OS/Browsers version
Mac / Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Baizy/dav76ycw/42/

### Steps to reproduce
step1 : set el-upload accept = "image / *"
step 2: drap a file that is not an image into el-upload 

### What is Expected?
There will be a prompt "Do not support current file format"

### What is actually happening?
Nothing at all

**Comment by iamkun** [comment]
accept="image/x-png,image/gif,image/jpeg"

**Comment by iamkun** [comment]
pr welcomed
