### ISSUE TITLE
[Bug Report] if <el-form>'s attr  "show-message" is "false"  ，'.el-form-item' style should be this: 'margin-bottom:0'.

### ISSUE THREAD

**Issue by Nathanlee2010** [ElemeFE/element#17071]
### Element UI version
2.10.1

### OS/Browsers version
chrome@latest@win10

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/8k2ugnp0/1/

### Steps to reproduce
in version 2.10.1,     its show this:

.el-form-item--mini.el-form-item, .el-form-item--small.el-form-item {
    margin-bottom: 18px;
}

.el-form-item {
    margin-bottom: 22px;
}

its no good for layout.   and i think its used for error message.

### What is Expected?
when :show-message="false"  (on el-form  or el-form-item)

we wish that no margin-bottom:

.el-form-item--mini.el-form-item, .el-form-item--small.el-form-item {
    margin-bottom: 0;
}

.el-form-item {
    margin-bottom: 0;
}

### What is actually happening?
.el-form-item--mini.el-form-item, .el-form-item--small.el-form-item {
    margin-bottom: 18px;
}

.el-form-item {
    margin-bottom: 22px;
}

**Comment by Nathanlee2010** [comment]
![image](https://user-images.githubusercontent.com/20190746/63211345-6f335b00-c128-11e9-8feb-6a63bebcb190.png)
![image](https://user-images.githubusercontent.com/20190746/63211349-78242c80-c128-11e9-9e08-6a458f3360e1.png)

**Comment by wacky6** [comment]
It's not a bug. If you don't want this kind of layout. Override the CSS yourself.
