### ISSUE TITLE
[Bug Report] Table border bug

### ISSUE THREAD

**Issue by NicholasCao** [ElemeFE/element#17085]
### Element UI version
0.1.0

### OS/Browsers version
windows/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
https://element.eleme.cn/#/zh-CN/component/table#dai-bian-kuang-biao-ge

The table header is not aligned with the border of the table content

### What is Expected?
table border align

table 边框对其

### What is actually happening?
The table header is not aligned with the border of the table content

table 表头和表内容的边框没对齐

**Comment by iamkun** [comment]
看起来没问题

**Comment by lizhen789** [comment]
跟我发现的一样，只要给table设置一个margin-top:10px就好了，下边框也会出现，设置一下也好了
