### ISSUE TITLE
[Bug Report] some bug happened after dialog(append-to-body) toggle and v-for data changed

### ISSUE THREAD

**Issue by 643104191** [ElemeFE/element#17083]
### Element UI version
2.8.2

### OS/Browsers version
any

### Vue version
2.6.10

### Reproduction Link
https://github.com/643104191/el-dialog-bug

### Steps to reproduce
1. git clone
2. npm install
3. npm run serve
4. visit url where project running is
5. click "showDialog" button.
6. close dialog.
7. click "changeList" button.
8. click "changeList" button again.

### What is Expected?
page(part of v-for) should be change after v-for data changed

### What is actually happening?
v-for data changed but page(part of v-for) is not change

**Comment by iamkun** [comment]
please provide a demo link with codepen
