### ISSUE TITLE
[Tree] 希望点击左边的三角形不选择树，只用作展开树。

### ISSUE THREAD

**Issue by hlwen** [ElemeFE/element#1708]

**Comment by furybean** [comment]
#1805 已经增加。

**Comment by wenner** [comment]
请问,这个箭头目前只用一个span实现, 能不能外面包裹一层dom , 因为只有一个span的话(而且这个还是实现的箭头),很难定义样式, 比如觉得当前箭头的点击范围太小了...想加大一下..就很难处理了
