### ISSUE TITLE
[Bug Report] Custom headers cannot render dynamic content

### ISSUE THREAD

**Issue by kaysonli** [ElemeFE/element#17086]
### Element UI version
2.11.1

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/kaysonli/pen/MWgjWKq

### Steps to reproduce
1. 使用自定义表头，<template slot="header">{{prop}}</template>
2. 动态改变表头里绑定的数据prop

### What is Expected?
表头会重新渲染

### What is actually happening?
表头没有重新渲染，依然是初次渲染的数据

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/issues/17221#issuecomment-528739957
