### ISSUE TITLE
[Bug Report] Tree data rendered el-table, after full selection, subline checkbox was not selected

### ISSUE THREAD

**Issue by Lysom** [ElemeFE/element#17080]
### Element UI version
2.11.1

### OS/Browsers version
chorme

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
编辑 添加  <el-table-column
      type="selection"
      width="55">
    </el-table-column>

### What is Expected?
期望可以选中子行

### What is actually happening?
并没有选中

**Comment by kaimzhou** [comment]
遇到同样的问题，求解！

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
