### ISSUE TITLE
[Bug Report] el-collapse-transition doesn't work with el-form

### ISSUE THREAD

**Issue by xianshenglu** [ElemeFE/element#17096]
### Element UI version
2.11.1

### OS/Browsers version
win10/chrome75

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/xianshenglu/5eztxnvq/4/

### Steps to reproduce
1. Click the button `Click Me`

### What is Expected?
el-form collapse with a transition

### What is actually happening?
el-form didn't collapse with a transition

Current workarounds are

- Add transition in the `el-form` style.
- Using `div` or move `el-form` into a `div`

However, I think it is a bug of `el-form`.

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by xianshenglu** [comment]
@island205  Sorry for that. Here is the valid link.  https://codepen.io/xianshenglu/pen/zYOEJPE
