### ISSUE TITLE
The sliding header and body parts of the [Bug Report] Table component are obviously disconnected

### ISSUE THREAD

**Issue by Lpeanut** [ElemeFE/element#17090]
### Element UI version
2.11.1

### OS/Browsers version
Mac/Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
https://element.eleme.cn/2.11/#/zh-CN/component/table#gu-ding-lie-he-biao-tou
这个官网Demo 左右滚动的时候 可以非常明显的感觉出来

### What is Expected?
期待header能够丝滑滚动

### What is actually happening?
header与body有明显的脱离

**Comment by iamkun** [comment]
pr welcomed
