### ISSUE TITLE
[Bug Report] v-model of Tabs component miss default value.

### ISSUE THREAD

**Issue by ssshooter** [ElemeFE/element#17097]
### Element UI version
2.10.0

### OS/Browsers version
MacOS

### Vue version
2.6.6

### Reproduction Link
https://codepen.io/ssshooter/pen/MWgjOJq?&editable=true

### Steps to reproduce
just run it

### What is Expected?
The first tab expand.

### What is actually happening?
Nothing expand

**Comment by wacky6** [comment]
看文档 https://element.eleme.io/#/zh-CN/component/tabs#ji-chu-yong-fa

**Comment by ssshooter** [comment]
> 看文档 https://element.eleme.io/#/zh-CN/component/tabs#ji-chu-yong-fa

不传 value 或为空默认第一个选项卡的 name 这么理解对吗？
