### ISSUE TITLE
[Bug Report] Drawer uses Dialog's classnames

### ISSUE THREAD

**Issue by dodas** [ElemeFE/element#17092]
`Drawer` component uses classnames such as `el-dialog__wrapper` and `el-dialog__close`.
These classnames (as name suggests) belong to `Dialog` component and are styled in `packages/theme-chalk/src/dialog.scss`.

Using Drawer without importing Dialog makes it unusable.
Particularly, styles for `.el-dialog__wrapper` are essential for seeing Drawer.

### Element UI version
2.11.1

### OS/Browsers version
N/A

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/dodas/pen/dybpNWY

### Steps to reproduce
1. use element-ui on-demand using babel-plugin-component
2. import just Drawer
3. use Drawer

### What is Expected?
Drawer to be styled.

### What is actually happening?
Drawer is not styled / is not showing.

**Comment by iamkun** [comment]
@JeremyWuuuuu  鸡哥求助

**Comment by JeremyWuuuuu** [comment]
@dodas Hi, I have updated this to `el-drawer`, please refer to the PR here to get more info. It will be merged into master in the next minor version I think. https://github.com/ElemeFE/element/pull/16953

**Comment by iamkun** [comment]
J G N B

**Comment by dodas** [comment]
Thanks, but you should replace `el-dialog__close` too.
