### ISSUE TITLE
NavMenu 导航菜单is-active类没有根据点选的菜单项变化

### ISSUE THREAD

**Issue by icewind7030** [ElemeFE/element#171]
我写了个简单的组件引用了NavMenu组件，并使用了它的vue-router模式，但是发现菜单项的第二项的is-active类有时候会不能成功跟随我选择而变化，需要我二次点击这个菜单项，才会成功获得is-active类，请问这个是我的设置有什么问题吗？
```javascript
<template>
    <header>
      <h1>周报系统</h1>
      <el-menu router default-active="myReport" mode="horizontal" @select="handleselect">
        <el-menu-item index="myReport">我的周报</el-menu-item>
        <el-menu-item index="createReport">创建周报</el-menu-item>
      </el-menu>
    </header>
</template>

<script>
  export default {
    methods: {
      handleselect(index) {
        console.log(index);
      }
    }
  }
</script>
```
![](http://ww1.sinaimg.cn/large/7d25d640jw1f896a9ysarj20v707stad.jpg)

**Comment by baiyaaaaa** [comment]
原因未知，但下个版本对 Navmenu 进行了重构，应该不会再出现这个问题。预计今天会发布。

**Comment by icewind7030** [comment]
好的

**Comment by erguotou520** [comment]
导航菜单的`router`功能并不是真正的`router-link`的功能，当刷新页面后就没有`active`的效果了

**Comment by icewind7030** [comment]
问题是我都没有刷新，只是点击切换到另一个url，`is-active`类也没有跟随变化，需要二次点击这个菜单栏上的链接，`is-active`才会切换到当前正确的链接上

**Comment by Plortinus** [comment]
新版本什么时候发布?

**Comment by baiyaaaaa** [comment]
@Plortinus rc.5 已发布

**Comment by erguotou520** [comment]
@Plortinus 但是现在的`router`属性并不能在页面刷新后继续保留菜单的选中状态啊

**Comment by QingWei-Li** [comment]
如果用 vue-router 的话，我的做法是 `default-active` 设置成 `this.$route.path`

**Comment by erguotou520** [comment]
但如果是嵌套路由的话还是判断不了？

**Comment by icewind7030** [comment]
额，更新了以后我的navMenu点一次链接触发3次console，api有改动？
![](http://ww1.sinaimg.cn/large/7d25d640jw1f8bn7dabytj20po0adq55.jpg)

**Comment by horans** [comment]
@erguotou520 
in template:
`:default-active="prntPath($route.path)"`

in script
`function prntPath(path){
	return path.substring(0, path.lastIndexOf('/'));
}`

**Comment by tuohuang** [comment]
貌似 index用绝对路径的话就不会高亮
