### ISSUE TITLE
[Bug Report] Cascader could not display null value option with emitPath set to false.

### ISSUE THREAD

**Issue by trgoofi** [ElemeFE/element#17106]
### Element UI version
2.11.1

### OS/Browsers version
macOS 10.14 / Chrome 76

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/trgoofi/pen/jONVWxj

### Steps to reproduce
In the first cascader select option `All` this one display `null` value option properly. `{emitPath: true}`

In the second cascader select option `One` or `Two` then select `All`  this time `null` value option `All` could not display. `{emitPath: false}`

### What is Expected?
With `emitPath` set to `false` select `null` value option should display properly.

### What is actually happening?
Select `null` value option could not display.

**Comment by huige222** [comment]
It's not just null, but it happens when value is zero or empty.I think the reason is that `'element-ui/src/utils/util'  isEmpty()` is executed when judging whether to update the text or not.I use value of non-false to solve the problem

**Comment by huige222** [comment]
It's not just null, but it happens when value is zero or empty.I think the reason is that `'element-ui/src/utils/util'  isEmpty()` is executed when judging whether to update the text or not.I use value of non-false to solve the problem
