### ISSUE TITLE
[Bug Report] Select will affect the display of other select content by changing the filter item of el-option through remote-filter

### ISSUE THREAD

**Issue by hoythan** [ElemeFE/element#17109]
### Element UI version
2.11.1

### OS/Browsers version
macOS

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/hoythan/pen/wvwoGya?editors=1010

### Steps to reproduce
数据结构为 [ { code: any, name: any } ]

点击 Add Select ，输入 1，随便选择一个添加，这时候 select 显示的是 name-1-0

再次点击 Add Select，输入 2，随便选择一个添加，这时候之前的一个 select 显示的内容变成了 code-1-0 因为 options 的值被覆盖。

### What is Expected?
select 名称正确的显示

### What is actually happening?
无

**Comment by hoythan** [comment]
我也不知道应该如何解决这个问题了，如果 v-model 和 el-option 是强绑定的状态下，如果 remote 搜索，势必会影响其他的 select 组件。

现在唯一的解决办法是每个 select 都创建一个独立的 list 使用。可能这个方式是正确的使用方法。

但是我认为如果可以，可以在 el-select 上提供一个类似 name 的选项，允许用户自定义如果参数不存在el-options 中的时候如何展示。

**Comment by hoythan** [comment]
或许可以提供一个如果 code 无法在 options 中搜索到的时候，应该从某个地方搜索或提供相关的配置选项。

**Comment by a631807682** [comment]
> 现在唯一的解决办法是每个 select 都创建一个独立的 list 使用，当这个控制很复杂，因为remote-method并不能传递index 等参数。

这其实是可以的 https://codepen.io/a631807682/pen/pozNNWN?editors=1011

同样也可以用`:value`和`@input`加`index`定义自己的逻辑

----
同样，我也认为这是个`bug`，如果我选择的内容更改，我至少需要得到一个通知。因为数据通常来源于接口，因此无法决定数据源是否会有变更。

**Comment by hoythan** [comment]
> > 现在唯一的解决办法是每个 select 都创建一个独立的 list 使用，当这个控制很复杂，因为remote-method并不能传递index 等参数。
> 
> 这其实是可以的 https://codepen.io/a631807682/pen/pozNNWN?editors=1011
> 
> 同样也可以用`:value`和`@input`加`index`定义自己的逻辑
> 
> 同样，我也认为这是个`bug`，如果我选择的内容更改，我至少需要得到一个通知。因为数据通常来源于接口，因此无法决定数据源是否会有变更。

我采用了一个可能更为恰当的方式，写一个隐藏的 option 在列表中，不影响 options 的循环，这样不论数据如何改变，不会影响其他的 select 显示
```
<el-option style="opacity: 0;overflow: hidden;height: 0;width: 0;" v-if="data[index].code" :label="data[index].name" :value="data[index].code" />
<el-option v-for ...
```

**Comment by a631807682** [comment]
> > > 现在唯一的解决办法是每个 select 都创建一个独立的 list 使用，当这个控制很复杂，因为remote-method并不能传递index 等参数。
> > 
> > 
> > 这其实是可以的 [codepen.io/a631807682/pen/pozNNWN?editors=1011](https://codepen.io/a631807682/pen/pozNNWN?editors=1011)
> > 同样也可以用`:value`和`@input`加`index`定义自己的逻辑
> > 同样，我也认为这是个`bug`，如果我选择的内容更改，我至少需要得到一个通知。因为数据通常来源于接口，因此无法决定数据源是否会有变更。
> 
> 我采用了一个可能更为恰当的方式，写一个隐藏的 option 在列表中，不影响 options 的循环，这样不论数据如何改变，不会影响其他的 select 显示，且保证代码受影响范围最小。
> 
> ```
> <el-option style="opacity: 0;overflow: hidden;height: 0;width: 0;" v-if="data[index].code" :label="data[index].name" :value="data[index].code" />
> <el-option v-for ...
> ```

这跟多个`select`没有关系，只有一个也会出现这样的问题。
https://codepen.io/a631807682/pen/dybONKY?&editable=true

**Comment by heroljy** [comment]
focus 时 options 置空，可以保留名称，试下

@focus="handleFocus"

handleFocus() {
  this.options = [];
}
