### ISSUE TITLE
Formmate of [Feature Request] table component returns how HTML strings are formatted to display

### ISSUE THREAD

**Issue by baikaishuixyz** [ElemeFE/element#17103]
### Existing Component
是

### Component Name
table

### Description
使用了table组件的formmater，该函数返回了格式化后的数据，数据内容是html字符串，希望在页面上显示出真实的html元素，但是现在显示的是html字符串

**Comment by wacky6** [comment]
不考虑。存在XSS风险。

要现实html结构，用自定义模版 https://element.eleme.io/#/zh-CN/component/table#zi-ding-yi-lie-mo-ban
