### ISSUE TITLE
[Bug Report] el-table dynamic merging of cells is problematic

### ISSUE THREAD

**Issue by Master-Huang** [ElemeFE/element#17107]
### Element UI version
2.8.2

### OS/Browsers version
win10/chrome 75.0.3770.100

### Vue version
2.5.16

### Reproduction Link
https://codepen.io/master-huang/pen/oNvYxXq?&editable=true

### Steps to reproduce
我需要动态合并行数，可能合并2行，3行，然后我就在数组里面加了个son参数，表示要合并的几行，现在需要一个合并起始行的参数，于是我加了个startIndex，然后每次执行objectSpanMethod方法时，判断startIndex，并根据条件重新赋值，就比如 this.startIndex  = row.son，当在这个方法里面赋值时，每次列表会循环两边调用objectSpanMethod，可以打印下rowIndex，出来的是 0，1，2，3，4，0，1，2，3，4，就像这样，当注释掉this.startIndex  = row.son，打印rowIndex，出来的是 0，1，2，3，4，正常的应该都是执行一遍，现在只要给vue的参数赋值就会执行两遍

### What is Expected?
在objectSpanMethod方法里，给vue的参数赋值，只执行一遍
我现在用其他的方式已经实现了，但是这个执行两遍还是个问题

### What is actually happening?
在objectSpanMethod方法里，给vue的参数赋值，执行了两遍，在vue 外部var 一个变量，在objectSpanMethod方法里赋值，是不会执行两遍的，只有更新vue的参数时，才会执行两遍

**Comment by ziyoung** [comment]
span-method 最好是一个纯函数，不建议在该函数中修改 data 中的数据 。
