### ISSUE TITLE
Problems of [Bug Report] el-menu navigation menu in IE browser

### ISSUE THREAD

**Issue by its-cool** [ElemeFE/element#17116]
### Element UI version
0.1.0

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
在IE浏览器中使用<el-menu></el-menu>标签时，当你点击菜单上面的文字（也就是<span>包裹的label）时不会发生跳转，只有当你点击<span>以外的地方时菜单才会跳转。

### What is Expected?
点击<span>也会跳转

### What is actually happening?
鼠标点击<span>(label)不会跳转

**Comment by its-cool** [comment]
你需要在点击事件后面加上.native修饰符

![image](https://user-images.githubusercontent.com/48171436/63418178-3bf91080-c435-11e9-9687-33ca0f8c9dc0.png)

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
