### ISSUE TITLE
[Bug Report] Select with filterable remote and without multiple, ipad Chrome Browser  will not show Soft keyboard while focus

### ISSUE THREAD

**Issue by maomao0306** [ElemeFE/element#17117]
### Element UI version
2.11.0

### OS/Browsers version
ipad chrome Browser version  76.0.3809.123

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/maomao0306/pen/PoYbbyw?&editable=true

### Steps to reproduce
Open the page, just click on select component on ipad chrome Browser, the software keyboard won't raise.If add the "multiple" property, it works properly.

### What is Expected?
It should raise the software keyboard any time when user clicks the component on  ipad chrome Browser.

### What is actually happening?
click select component on  ipad chrome Browser,  the keyboard won't raise

**Comment by XRFBI** [comment]
I meet the same problem, please check this.

**Comment by simonAndSakura** [comment]
+1， 希望能尽快修复~
our team meet this same problem, hope to repair as soon as possible.

**Comment by coolcorey** [comment]
Oh wow. Now I know how to get the danged keyboard to come up.
