### ISSUE TITLE
[Bug Report] Select selector's multiple function behave weird

### ISSUE THREAD

**Issue by xiaobolove** [ElemeFE/element#17118]
### Element UI version
2.11.1

### OS/Browsers version
windows 8.1 / chrome 75

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/xiaobolove/pen/RwboGzB

### Steps to reproduce
Randomly input a,b,c... then select several items in the list, then you will see some already selected items text missing 

在文本框中输入字母，然后在下拉列表中选择大于3，4项后，之前文本框中已选择的项有些文字丢失了。。

preview:
https://image-static.segmentfault.com/556/403/556403230-5d5cbfe6885d7_articlex

### What is Expected?
all selected items show it's texts

所有选中项文本正常显示

### What is actually happening?
some selected items missing text

有些选中项的文本丢失

**Comment by wacky6** [comment]
remote-method 要保证已选项目仍然在options中

**Comment by xiaobolove** [comment]
> remote-method 要保证已选项目仍然在options中

看了select.vue源码，找到问题所在了，526行：
const label = (!isObject && !isNull && !isUndefined)
          ? value : '';
这儿的判断，当value为对象时，label会赋值为空字符串

远程搜索+多选+value为对象
