### ISSUE TITLE
Problem with the table header filter

### ISSUE THREAD

**Issue by lucianoorsi** [ElemeFE/element#17126]
### Element UI version
2.10.1

### OS/Browsers version
Windows 10 / Chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lucianoorsi/pen/KKPNroQ

### Steps to reproduce
Change slot-scope (vue deprecated) for v-slot in the template input search of the table.

 <template slot="header" slot-scope="scope">
        <el-input
          v-model="search"
          size="mini"
          placeholder="Type to search"/>
      </template>

### What is Expected?
To filter normally

### What is actually happening?
It does not filter well, and also does not appear what one is writing

**Comment by a631807682** [comment]
> It does not filter well, and also does not appear what one is writing

https://codepen.io/a631807682/pen/rNBWoox
any problem?

**Comment by lucianoorsi** [comment]
Now it works perfect.
Thank you
