### ISSUE TITLE
[Bug Report] uploaded excel and  file.type in beforeUpload function is ''

### ISSUE THREAD

**Issue by itheimaxia** [ElemeFE/element#17129]
### Element UI version
2.11.1

### OS/Browsers version
windows10/chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?editors=1111

### Steps to reproduce
1.uploaded excel 
2. file.type in beforeUpload function is ''

### What is Expected?
the file type of XLS  is  'application/vnd.ms-excel';
the file type of XLSX  is  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

### What is actually happening?
the file type is ''

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
