### ISSUE TITLE
[Feature Request] upload component manually uploads files

### ISSUE THREAD

**Issue by zhangchuanbo** [ElemeFE/element#17132]
### Existing Component
是

### Component Name
upload

### Description
在upload组件手动上传文件时，希望给submit()方法一个callback回调，这个回调将在全部文件上传成功之后调用。或者是异步函数submit().then(res={})

**Comment by gongshun** [comment]
你是一个表单有多个文件需要上传是吧，你设置不自动上传，也不用写自定义上传事件，通过this.$refs.poster.uploadFiles[0]拿到文件，文件对象的raw属性放到表单数据中，一起提交

**Comment by island205** [comment]
pr welcome

**Comment by iamkun** [comment]
pr welcomed
