### ISSUE TITLE
form表单阻止默认事件

### ISSUE THREAD

**Issue by Stevenzwzhai** [ElemeFE/element#1713]
项目需要阻止enter提交表单，但是我使用v-on:submit.prevent 根本不起作用，最后使用了原生的onSubmit=“event.preventDefault();”，而且在form标签上无法使用vue绑定事件的方式绑定submit事件，input标签中也是如此

**Comment by Kingwl** [comment]
submit.native.prevent？

**Comment by Leopoldthecoder** [comment]
请参照楼上的方法。

**Comment by Stevenzwzhai** [comment]
好

**Comment by aqbjteddy** [comment]
@Leopoldthecoder 怎么在form上绑定submit事件？
