### ISSUE TITLE
[Feature Request] Select cannot control the direction of Popover pop-up

### ISSUE THREAD

**Issue by hoythan** [ElemeFE/element#17135]
### Existing Component
是

### Component Name
select

### Description
Select 无法强制控制 popover 方向，如果 select 框接近屏幕下方，在 remote 搜索的时候，点击显示 “无数据”时 ，popover 显示在下面，但是一旦有数据就会闪烁到上面，造成非常不好的体验，希望添加一个选项控制 popover 方向，以让他强制显示在上面或其他方向。

**Comment by iamkun** [comment]
pr welcomed
