### ISSUE TITLE
[Feature Request] Please support el-select multiple collapse-tags non-clearable

### ISSUE THREAD

**Issue by bilibiliou** [ElemeFE/element#17136]
### Existing Component
是

### Component Name
el-select

### Description
I cant set :clearable="false" to disable those tags non-clearable
Pls support this feature

e.g : 

<el-select
  multiple
  collapse-tags
  :collapse-tags-close="false"
>

**Comment by bilibiliou** [comment]
Btw, you can communicate with me by chinese

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
