### ISSUE TITLE
[Feature Request] new component - skeleton

### ISSUE THREAD

**Issue by lx815** [ElemeFE/element#17139]
### Existing Component
否

### Component Name
skeleton（骨架屏幕）

### Description
In a real business process, we sometimes have a few seconds of white space on the page when it loads.Or when the user doesn't have access to the page's data, we want the user to see a page's content instead of an entirely white page.So hopefully elementui will officially come up with a skeleton screen component.thank you

**Comment by iamkun** [comment]
pr welcomed
