### ISSUE TITLE
[Bug Report] Required el-form-item properties not updated when using child components

### ISSUE THREAD

**Issue by davidvanvan** [ElemeFE/element#17144]
### Element UI version
0.1.0

### OS/Browsers version
Any OS / Google Chrome Version 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/davidvanvan/pen/qBWRbaO

### Steps to reproduce
Make a regular el-form component with it's :rules="rules".
Create a child component (ex. select-position).
Add the created child component inside a required el-form-item with prop="position_id2" (this prop is used in the form rules).
Create a form validation on submit (actually it's just as in the form validation https://element.eleme.io/#/en-US/component/form#form-events) .
Emit select changes from child to parent component.

### What is Expected?
I expected that the parent component with required el-form-item to be valid (no errors) because there was data emitted from child to parent component

### What is actually happening?
Validation error is showing as such on submit

P.S. - I am Using Element UI version 2.4.6, the Repository Version only have 0.1.0 option, not sure why

**Comment by davidvanvan** [comment]
Some thoughts: 
When I compared these scenarios on non-child components inside el-form-item, the computed property "fieldValue" is updated on change (maybe other event as well) and such, yet when using child-components inside el-form-item, "fieldValue" is not changed or is undefined, this is just my assumption maybe it has something to do with element ui form.validation

**Comment by nullptru** [comment]
Code error.

```
form: {
  /* ... */
  position_id2: ''
},
```
```
updateMe(id) {
   this.form.position_id2 = id
},
```

**Comment by mmdlsu** [comment]
怎么解决的
