### ISSUE TITLE
[Feature Request] Online theme roller generate seperate css files

### ISSUE THREAD

**Issue by xeriuk** [ElemeFE/element#17140]
### Existing Component
No

### Component Name
Online theme roller

### Description
I want to use the generated online theme roller theme in my Nuxt project. I'm using the following setup in my nuxt.config.js

```
plugins: [
    [
        'component',
        {
            libraryName: 'element-ui',
            styleLibraryName: '~/assets/css/element-ui/theme-modual',
        }
    ]
]
```

This way it should load the CSS files on demand for every component. But when I npm run dev my Nuxt project now it can't find the separate CSS files for every component. So I get this warning in my terminal:

`To install them, you can run: npm install --save /assets/css/element-ui/theme-modual/alert.css /assets/css/element-ui/theme-modual/base.css /assets/css/element-ui/theme-modual/button.css /assets/css/element-ui/theme-modual/cascader.css /assets/css/element-ui/theme-modual/checkbox.css /assets/css/element-ui/theme-modual/color-picker.css /assets/css/element-ui/theme-modual/date-picker.css /assets/css/element-ui/theme-modual/dialog.css /assets/css/element-ui/theme-modual/dropdown-item.css /assets/css/element-ui/theme-modual/dropdown-menu.css /assets/css/element-ui/theme-modual/dropdown.css /assets/css/element-ui/theme-modual/form.css /assets/css/element-ui/theme-modual/input.css /assets/css/element-ui/theme-modual/loading.css /assets/css/element-ui/theme-modual/message.css /assets/css/element-ui/theme-modual/radio-button.css /assets/css/element-ui/theme-modual/radio-group.css /assets/css/element-ui/theme-modual/select.css /assets/css/element-ui/theme-modual/slider.css /assets/css/element-ui/theme-modual/switch.css /assets/css/element-ui/theme-modual/tooltip.css`

Of course, npm install won't work. Is it possible the theme roller generated seperate files like theme-chaik? Thanks!

**Comment by unssnu** [comment]
I met the same problem, have no idea with it

**Comment by ngekoding** [comment]
Same problem here, need help.
