### ISSUE TITLE
[Bug Report] el-input triggers the remembered selected option under the Chinese input method, and cannot trigger the bound value after selecting the alternate option.

### ISSUE THREAD

**Issue by vellengs** [ElemeFE/element#17146]
### Element UI version
2.11.1

### OS/Browsers version
Chrome 75

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/vellengs/pen/OJLWggN

### Steps to reproduce
使用中文输入法触发备选项

### What is Expected?
更新绑定值

### What is actually happening?
没有更新绑定值

**Comment by vellengs** [comment]
没人回复吗？

**Comment by nullptru** [comment]
> 没人回复吗？
经查是 Chrome 的 bug 导致 compositionend 事件不被触发.. 之后会考虑 workaround 来修复

**Comment by vellengs** [comment]
vue 的 input 是可以的，是否可以参考下实现？
