### ISSUE TITLE
Property or method "_c" is not defined on the instance

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#1714]
### ElementUI version
1.0.6

### OS/Browers version
 win8/Chrome 55

### Vue version
 2.1.4 

### 解决了_vm._h的问题，_vm._c 又冒出来了

![qq 20161213145513](https://cloud.githubusercontent.com/assets/2288630/21130527/2c55beae-c144-11e6-9dab-da0b869d37a7.png)

### 编译出来的源码
```
module.exports={render:function (){var _vm=this;
var _h=_vm.$createElement;
var _c=_vm._c;
```

### `_vm._c` 是个什么鬼咯

**Comment by zmh7057** [comment]
@zlab   "vue-loader": "10.0.0" 使用这个版本 就 OK 了

**Comment by Leopoldthecoder** [comment]
"vue-template-compiler": "2.1.4"
"vue-loader": "10.0.0"
"vue": "2.1.4"
试试锁定上述版本

**Comment by zengAlex** [comment]
请问为什么会报这个error elbutton 的错 
![image](https://cloud.githubusercontent.com/assets/13888110/21134446/e2c7b192-c158-11e6-90f4-5be41ca3eca0.png)

**Comment by Leopoldthecoder** [comment]
@zengAlex 参照上面锁定一下版本。

**Comment by zengAlex** [comment]
这个 elbutton 也是package.json  里面的版本导致的吗？

**Comment by zengAlex** [comment]
@Leopoldthecoder 锁定了版本后，编译的时候报错了
![image](https://cloud.githubusercontent.com/assets/13888110/21134892/c47e4b04-c15a-11e6-876a-ce7876bcc6db.png)

**Comment by Leopoldthecoder** [comment]
@zengAlex 看上去你并没有锁定，Vue 还是 2.1.5 版本

**Comment by zengAlex** [comment]
@Leopoldthecoder  我在package.json  上，改成了2.1.4的版本，然后再npm install

**Comment by Leopoldthecoder** [comment]
把 `^` 去掉才是锁定

**Comment by zengAlex** [comment]
@Leopoldthecoder   谢谢

**Comment by Leopoldthecoder** [comment]
这个问题先关掉了，可以参照 #1706 处理。

**Comment by zlab** [comment]
"vue-loader" 只能用 "10.0.0"，用 "^10.0.0"，会下载 "10.0.2"  
已解决
