### ISSUE TITLE
[Bug Report] Tree Tree control, multi-check box echo problem

### ISSUE THREAD

**Issue by q304626718** [ElemeFE/element#17141]
### Element UI version
2.11.0

### OS/Browsers version
Google Chrome 版本 73.0.3683.75（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
1.创建Tree 树形控件;
2.设置节点数据
[
  {
    id:1,name:'项1',children:[
      {id:101,name:'项2',children:[
         {id:10101,name:'项3'},
         {id:10102,name:'项4'}
         ]
      }
   ]
  }
]
3.调用方法this.$refs.tree.treeSetCheckedKeys([101], false);。
在check-strictly=false时的情况，选中节点的时候，无效果，节点未选中

### What is Expected?
101节点应该被选中(半选)，上级节点1半选，下级10101,10102节点不选

### What is actually happening?
101节点未被选中，上级节点1未被选中

**Comment by island205** [comment]
Issues without a valid reproduction link will be closed directly.
