### ISSUE TITLE
[Bug Report] el-dialog中嵌套的table，使用fixed="right" 当所有column的宽度之和 < table的宽度时，fixed 区域的高度不正确

### ISSUE THREAD

**Issue by hualvm** [ElemeFE/element#17149]
### Element UI version
2.11.1

### OS/Browsers version
win10 x64 / chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/hualvm/pen/ZEzLJEm

### Steps to reproduce
1、点开重现链接
2、浏览器处于最大化 1920
3、点击对话框，（此时正常）
4、关闭对话框，再次点击打开，（bug出现，看下table右下角多了一条线）
【此bug 出现在2.10.0 以上版本，经测试2.9.2版本是正常的】

### What is Expected?
fiex区域的border-bottom  要与table的边框重叠

### What is actually happening?
不重叠

**Comment by yinboxie** [comment]
我也遇到了类似问题，table左右两边有固定列时， 切换顶部tabs, 再回到当前页时，固定列区域样式有错乱。如下图:
![image](https://user-images.githubusercontent.com/18409728/63998122-fcb47900-cb32-11e9-9af7-7e5578d005a5.png)
测试发现， column 宽度， 使用 width , 将当前页面撑满，并出现滚动条时，就不会出现。
该问题，在2.8.2之前的版本，都没有出现.

**Comment by 1207934561** [comment]
![123](https://user-images.githubusercontent.com/33915384/64139785-ad24c480-ce34-11e9-8955-d087cfa802f2.jpg)
同样遇到了类似的问题，在keep-alive页面中使用表格（表格的高度是动态设置的）开启fixed功能，当页面切换回来之后表格fixed列最下方会多出一条横线，并且会遮挡一部分内容，猜测是表格高度引起的问题？于是尝试手动设置fixed属性，默认设置fixed属性为false，在表格渲染完毕后再设置fixed为“right”，目前表格显示是正常了，但不知道会不会出现其它问题。

**Comment by ziyoung** [comment]
本机上无法出现。录制一段视频吧。看一下你的操作。

**Comment by ziyoung** [comment]
> 我也遇到了类似问题，table左右两边有固定列时， 切换顶部tabs, 再回到当前页时，固定列区域样式有错乱。如下图:
> ![image](https://user-images.githubusercontent.com/18409728/63998122-fcb47900-cb32-11e9-9af7-7e5578d005a5.png)
> 测试发现， column 宽度， 使用 width , 将当前页面撑满，并出现滚动条时，就不会出现。
> 该问题，在2.8.2之前的版本，都没有出现.

@yinboxie 能稳定重现的，新开一个 issue，并提供 demo。

**Comment by yinboxie** [comment]
@ziyoung  请查看该demo  https://github.com/yinboxie/element-UI-table-demo
![image](https://user-images.githubusercontent.com/18409728/64434114-77acff00-d0f2-11e9-85ed-4f0aeae4ffeb.png)

**Comment by WingsLong** [comment]
用了fixed='right'改变窗口大小之后，高度与table高度不一致，必现
![image](https://user-images.githubusercontent.com/22903192/64595943-8b53b080-d3e5-11e9-9088-5b4fde52820d.png)

**Comment by ziyoung** [comment]
> @ziyoung 请查看该demo https://github.com/yinboxie/element-UI-table-demo
> ![image](https://user-images.githubusercontent.com/18409728/64434114-77acff00-d0f2-11e9-85ed-4f0aeae4ffeb.png)

无法重现。
![image](https://user-images.githubusercontent.com/12947422/64675463-d3d2a300-d4a5-11e9-9feb-920c8a6da976.png)

---

如果依旧有问题，新开 issue。

**Comment by ziyoung** [comment]
> 用了fixed='right'改变窗口大小之后，高度与table高度不一致，必现
> ![image](https://user-images.githubusercontent.com/22903192/64595943-8b53b080-d3e5-11e9-9088-5b4fde52820d.png)

还是无法重现。先关闭了。

**Comment by jsdawn** [comment]
我也出现了这个情况 ，缩放浏览器的时候出现

**Comment by jsdawn** [comment]
.el-table__fixed,
    .el-table__fixed-right {
      min-height: 100% !important;
    }
    &.el-table--fit {
      overflow-y: hidden;
    }
    &.el-table--scrollable-x {
      .el-table__fixed,
      .el-table__fixed-right {
        min-height: auto !important;
      }
    }

**Comment by jsdawn** [comment]
我用了以上css 代码覆盖 element 处理的高度问题，以免其卡在宽度临界点来回跳动；
不过这样的弊端是 el-table不能设置固定高度

**Comment by zhanyeye** [comment]
el-table 上加上 `class="tableClass"`
然后添加样式
```
.tableClass {
  /deep/ .el-table__fixed-right {
    height: calc(100% - 11px) !important; //设置高优先，以覆盖内联样式
  }
  /deep/ .el-table__fixed-right::before {
    height: 0px !important; //设置高优先，以覆盖内联样式
  }
}
```

**Comment by dinglittle** [comment]
遇到个诡异的问题 , 当 设置 横向纵向滚动条 宽度不一致时 , 滚动到超出一屏 错位 , 折腾了好久 , 样式排查 总是差 纵向滚动条那个 高度 , 百思不得其解 , 最后 , 横纵滚动条 改成同样 宽度 , 问题解决 /die

**Comment by BeginnerDone** [comment]
2.15版本也有这个问题。你们解决了吗
