### ISSUE TITLE
[Feature Request] strongly recommended to add Excel file export module in Table paging module

### ISSUE THREAD

**Issue by samuel778** [ElemeFE/element#17153]
### Existing Component
否

### Component Name
TableExcelExport

### Description
文件导出的普遍做法：
1、后端直接生成excel文件，
2、提供一个url供前端下载。

直到有一次停车数据的导出数据达到10 万，（后端没有长度限制）用户在前端导的时候，用户等待时间太长（后台直接一个查询读取10几万数据，进行分析，转换成excel文件，），然后刷新页面点了好多次，一个导出直接把系统资源全占满。
主要原因在：
1、从mysql读取10 万的数据，耗时长，主要是数据从数据库到服务器的数据传输耗时长
2、10几万的数据大量消耗服务器资源

后来我对大数据导出，做了优化：
1、引入多线程，分页的方式读取原始数据，转换成excel，存入磁盘。
2、把磁盘上excel进行zip压缩打包下载。

在开发过程中发现：
1、excel渲染跟前端table 分页渲染职责类似，由前端去做更合适。由于后台传前端的数据，前端展示时通常要进行format，而后端在做excel导出时，也需要进行数据format。比如前后端约定，type=1微信，type=2支付宝。这时，增加type=3银联，那么前后端的format方法都需要修改。
2、后端既有提供分页接口，
3、用户对前端文件导出的速度要求并不强烈，甚至一两分钟都可以接受。

于是，我在思考，能否excel导出由前端完成，最终真被我找到了案例，并且让前端同事完成组件开发。现在，我们的excel导出，后端不需要另外出接口，直接用后端提供的分页方法进行。极大的方便开发。
使用到的技术：https://blog.csdn.net/u010427666/article/details/79208145

建议ElementUI增加该工具

**Comment by iamkun** [comment]
pr welcomed
