### ISSUE TITLE
[Bug Report] Multiple clicking confirm button in dialog with a really fast speed will trigger my method many times

### ISSUE THREAD

**Issue by Syntax-J** [ElemeFE/element#17155]
### Element UI version
2.11.1

### OS/Browsers version
5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Syntax-J/pen/QWLdOLE

### Steps to reproduce
1 open chrome devtools console  
2 open the dialog  
3 click 确认/confirm button multiple times in a shot time  
4 it will logs lots of 111111 though the dialog is disappeared  

### What is Expected?
it shoule trigger the method only once

### What is actually happening?
duplicate triggering method

**Comment by iamkun** [comment]
not element bug

**Comment by wjq666666** [comment]
为什么我还有这样的错误呢？
