### ISSUE TITLE
[Feature Request] el-table row-click cannot get row-index

### ISSUE THREAD

**Issue by lxw15337674** [ElemeFE/element#17152]
### Existing Component
Yes

### Component Name
el-table

### Description
el-table点击行不能获取行索引值。
网上的临时解决方案：https://www.cnblogs.com/yangyi9343/p/9295293.html

**Comment by lxw15337674** [comment]
但是网上的解决方案会使row增加value属性，目前我想到的办法是通过row-class-name方法返回index作为每行的class，
```
 tableRowClassName ({row, rowIndex}) {
        return `index:${rowIndex}`;
      },
```
然后在row-click的event参数里获取。

**Comment by iamkun** [comment]
pr welcomed
