### ISSUE TITLE
[Feature Request] Negative numbers in Slider component

### ISSUE THREAD

**Issue by robot-tin** [ElemeFE/element#17158]
### Existing Component
Yes

### Component Name
Slider

### Description
It could be useful if one can use negative numbers too into Slider component, ex:

 [-30] |------------<->---------|[0]|----------------------| [ 30]

**Comment by haoranyu** [comment]
It is already implemented. You can set `:min=-30` and `:max=30` for the intention above.

Check the demo:
https://codepen.io/haoranyu-the-typescripter/pen/ZEzKKbN?&editable=false
