### ISSUE TITLE
[Bug Report] Document improvement of Custom Theme

### ISSUE THREAD

**Issue by jerrybendy** [ElemeFE/element#17154]
### Element UI version
2.11.1

### OS/Browsers version
Any

### Vue version
2.6.10

### Reproduction Link
http://www.github.com

### Steps to reproduce
Null

### What is Expected?
There is a conflict between on demand import and custom theme with `element-variables.scss`.

`On demand import` uses `babel-plugin-component` to import components and styles automatically, and  `element-variables.scss` uses `@import "~element-ui/packages/theme-chalk/src/index";` to import scss files to build. This courses the styles load twice, and every I wrote in `element-variables.scss` are overwritten by the style  `babel-plugin-component` loaded. So  `element-variables.scss` doesn't work anymore when enable `on demand` importing.

I checked the document of  `babel-plugin-component` and find a solution. Changing the `babel.config.js` as below:

```diff
      {
        "libraryName": "element-ui",
- "styleLibraryName": "theme-chalk"
         "style": false
      }
```

### What is actually happening?
Null

**Comment by FredBrock** [comment]
Wow. Thank you so much.
