### ISSUE TITLE
The change event of [Bug Report] input becomes a blur event

### ISSUE THREAD

**Issue by wangcheng1212** [ElemeFE/element#17163]
### Element UI version
2.11.1

### OS/Browsers version
chrome 74.0.3729.131（正式版本)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/marinya/pen/MWgJMyo?&editable=true

### Steps to reproduce
在el-input上面注册change事件,只有失焦的时候才触发

### What is Expected?
期待change是change事件而不时blur

### What is actually happening?
现在是change变成blur

**Comment by wacky6** [comment]
这个change与原生一致。

要所有改变用input事件或者watch.value。需要控制所有交互，用input.native 和 composition{*}.native
