### ISSUE TITLE
[Bug Report] wrap the custom header in el-table with el-popover, and the multi-check box data binding in el-popover is invalid!!!

### ISSUE THREAD

**Issue by DDDenial** [ElemeFE/element#17160]
### Element UI version
2.11.0

### OS/Browsers version
macos 10.14.4 / chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/dddenial/pen/BaBpqRb?editors=1010

### Steps to reproduce
1.点击表头的 “ 姓名 ” 按钮。
2.点击弹出层的“ 复选框 B”。

### What is Expected?
期待多选框 “复选框 B”被选中

### What is actually happening?
多选框 “复选框 B”没有被选中

**Comment by Zq986928835** [comment]
可在表头插槽尝试增加属性 slot-scope，如下
`<template slot="header" slot-scope="scope">`

**Comment by DDDenial** [comment]
亲测，有效

**Comment by DDDenial** [comment]
> 可在表头插槽尝试增加属性 slot-scope，如下
> `<template slot="header" slot-scope="scope">`

亲测，有效

**Comment by ziyoung** [comment]
> 可在表头插槽尝试增加属性 slot-scope，如下
> `<template slot="header" slot-scope="scope">`

thanks.

**Comment by duzhihao-github** [comment]
> 可在表头插槽尝试增加属性slot-scope，如下
> `<template slot="header" slot-scope="scope">`

请问这是什么原理，虚心请教

**Comment by pectinifera** [comment]
> > 可在表头插槽尝试增加属性slot-scope，如下
> > `<template slot="header" slot-scope="scope">`
> 
> 请问这是什么原理，虚心请教

猜测，当前带有scope的属性的模板，大多会涉及到数据的操作，所以进行了双向绑定。如果不带有scope属性，都是单纯的展示项，就省掉了数据双向绑定的步骤。只能说，实际的应用场景五花八门，甚至出现了很多不合理需求，业务上的bug造成了技术上的bug。
