### ISSUE TITLE
The modal of the [Bug Report] Dialog component sometimes takes effect on ie11 and sometimes does not.

### ISSUE THREAD

**Issue by JokerLoLgrey** [ElemeFE/element#17173]
### Element UI version
0.1.0

### OS/Browsers version
ie11

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/JokerYM/pen/MWgpVLr（ie不能跑起来）

### Steps to reproduce
ie打开dialog会先出现modal最高，不能正确显示内部内容

### What is Expected?
ie打开dialog，modal不会遮挡内容显示

### What is actually happening?
ie打开dialog，modal会遮挡内容显示

![image](https://user-images.githubusercontent.com/33446705/63679046-0da77680-c823-11e9-9dd7-324a26316817.png)

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
