### ISSUE TITLE
[Bug Report] PageHeader component failed to respond I18N

### ISSUE THREAD

**Issue by Hill-98** [ElemeFE/element#17171]
### Element UI version
2.11.1

### OS/Browsers version
Windows 10 / Chrome Canary 78

### Vue version
2.6.10

### Reproduction Link
https://github.com/Hill-98/element-issue-pageheader

### Steps to reproduce
切换语言的时候，页头的返回文本并不会更新。

### What is Expected?
页头的返回文本应该响应式更新

### What is actually happening?
页头的返回文本没有响应式更新

**Comment by ziyoung** [comment]
测试了一下，文档站存在该问题。但在项目中，不会存在问题。

**Comment by Hill-98** [comment]
那我上面的那个代码怎么不能响应式更新呢，是哪里写的有问题吗？
