### ISSUE TITLE
[Bug Report] MessageBox Bullet Box (alert, confirm) initially opens with a primary type button with a hover state background color

### ISSUE THREAD

**Issue by Adashuai5** [ElemeFE/element#17178]
### Element UI version
2.11.1

### OS/Browsers version
Windows 10 / Google Chrome 版本 76.0.3809.100（正式版本）（64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/adshuai5/pen/VwZpxKL?editors=1010

### Steps to reproduce
1. 打开重现链接或 [Element-UI 官方链接-MessageBox 弹框章节](https://element.eleme.cn/2.11/#/zh-CN/component/message-box#messagebox-dan-kuang)
2. 点击 ‘点击打开 Message Box’ 按钮
3. 可以看到 确定 按钮样式为 hover 状态（组件默认：background: #66b1ff）
![实际的行为](https://upload-images.jianshu.io/upload_images/7094266-7c721e8c1378285e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### What is Expected?
初始打开基础的模态对话框组件（MessageBox 弹框）时， primary 类型的按钮应该为默认样式状态，而不应是鼠标 hover 时的样式状态（组件默认：background: #66b1ff）。
 ![期待的行为](https://upload-images.jianshu.io/upload_images/7094266-dd7a1b8410162a73.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### What is actually happening?
初始打开基础的（内容为 alert、confirm 时会有，prompt 和其他官方文档示例未出现此 bug）模态对话框组件（MessageBox 弹框）时， primary 类型的按钮应该为鼠标 hover 时的样式状态（组件默认：background-color: #409eff）。 

![实际的行为](https://upload-images.jianshu.io/upload_images/7094266-7c721e8c1378285e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

点击页面或打开开发者模式可以使得按钮恢复正常

**Comment by Adashuai5** [comment]
系统自带的 alert、confirm 似乎本身也有该问题

**Comment by ziyoung** [comment]
@Adashuai5 其实不是 bug。这里是添加了可访问性。dialog 打开后，回车，你会发现 dialog 被关闭了。

**Comment by BNK-ALONG** [comment]
可以给confirm的confirm按钮加:focus覆盖原element的样式。注意:focus的顺序要在:hover之前
