### ISSUE TITLE
[Feature Request] why background color of el-pagination is white instead of transparent

### ISSUE THREAD

**Issue by CNOFNe** [ElemeFE/element#17176]
### Existing Component
是

### Component Name
el-pagination

### Description
I using el-pagination in a dark page，I want to change its background color to transparent。

when i not use props of 'background', the background color of el-pagination is white. 

it looks like this:
![UTOOLS1566806710035.png](https://i.loli.net/2019/08/26/YnjtfmglONRBiCM.png)

my code:
```
<el-pagination
        v-if="isPaging"
        @size-change="handleSizeChange"
        @current-change="handlePageChange"
        :current-page="currentPage"
        :page-sizes="pageSizes"
        :page-size="pageSize"
        :total="totalSize"
        layout="total, sizes, prev, pager, next, jumper"
        class="col-12 d-flex justify-content-end flex-wrap">
</el-pagination>
```
How can I change the background color to transparent

**Comment by ziyoung** [comment]
Overwrite CSS.
