### ISSUE TITLE
[Bug Report] ElForm with JSX get errors

### ISSUE THREAD

**Issue by YuLinXi** [ElemeFE/element#17172]
### Element UI version
2.11.1

### OS/Browsers version
MacOs

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/kj1oaefp/

### Steps to reproduce
初试化后得到[Vue warn]: Invalid handler for event "input": got undefined
1. 在输入框上输入123
2. 点击重置
得到[Element Warn][Form]model is required for resetFields to work.

### What is Expected?
1. 能正确的重置
2. 初始化后无[Vue warn]: Invalid handler for event "input": got undefined报错

### What is actually happening?
1. 初试化后得到[Vue warn]: Invalid handler for event "input": got undefined
2. 点击重置后得到[Element Warn][Form]model is required for resetFields to work.

**Comment by ziyoung** [comment]
打开了这个链接 https://codesandbox.io/embed/vue-template-deokb 没有重现。

**Comment by xxbld** [comment]
@YuLinXi 
![image](https://user-images.githubusercontent.com/13309211/66359656-88c78500-e9aa-11e9-9db0-c4847c260f3d.png)

**Comment by YuLinXi** [comment]
> @YuLinXi
> ![image](https://user-images.githubusercontent.com/13309211/66359656-88c78500-e9aa-11e9-9db0-c4847c260f3d.png)

嗯 已经解决了 3Q

**Comment by lovewmf** [comment]
> > @YuLinXi
> > ![image](https://user-images.githubusercontent.com/13309211/66359656-88c78500-e9aa-11e9-9db0-c4847c260f3d.png)
> 
> 嗯 已经解决了 3Q

怎么解决的方便说一下吗
