### ISSUE TITLE
node7 在通用模版npm install  出现报错

### ISSUE THREAD

**Issue by zengAlex** [ElemeFE/element#1718]
7243 error Darwin 15.6.0
7244 error argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install"
7245 error node v7.0.0
7246 error npm  v3.10.8
7247 error shasum check failed for /var/folders/rz/rl3tdzwd6wj31dh43705_x_80000gn/T/npm-38373-89629f04/registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000597.tgz
7247 error Expected: b52e6cbe9dc83669affb98501629feaee1af6588
7247 error Actual:   8b0003297b531e32de98af0976ddf362dd4cf98c
7247 error From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000597.tgz
7248 error If you need help, you may report this error at:
7248 error     <https://github.com/npm/npm/issues>
7249 verbose exit [ 1, true ]

**Comment by QingWei-Li** [comment]
非 Element 问题，请到 Gitter 里或者 Vue 相关社区咨询
