### ISSUE TITLE
[Feature Request] v-infinite-scroll and el-table cannot fix table head

### ISSUE THREAD

**Issue by Twinkle999** [ElemeFE/element#17182]
### Existing Component
是

### Component Name
v-infinite-scroll    and     el-table

### Description
You use v-infinite-scroll  in out div；You use el-table in inner div；If you want to scroll to bottom to load data, you cannot set el-table height 100% so you cannot fix table head. Can I both scroll to bottom to load data and fix table head? I am looking forward your reply.

**Comment by ziyoung** [comment]
I think you use append slot. https://element.eleme.cn/#/zh-CN/component/table#table-slot
