### ISSUE TITLE
 [Feature Request] Whether the transfer component can provide a list head slot and list footer slot ?

### ISSUE THREAD

**Issue by heyi-let** [ElemeFE/element#17187]
### Existing Component
是

### Component Name
Transfer 穿梭框

### Description
在我们大多数使用穿梭框组件的时候，往往都需要在穿梭框列表中显示多个不同都字段（比较忧伤的是，交互往往会把列表变成一个表格）。我们现在可以通过 render-content 自定义数据项渲染函数简单模拟表格 body，但是对于表格的 head 和分页无能为力。

**Comment by heyi-let** [comment]
Maybe we can also provide a slot so that we can fully customize the list body：
```
  <el-transfer
    v-model="value"
    :props="{
      key: 'value',
      label: 'desc'
    }"
    :data="data">
    <template slot=“list”>
       <el-table> ... </el-table>
    </template>
 </el-transfer>
```

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
