### ISSUE TITLE
[Feature Request] Can't hide the upload box when data length >= limit 

### ISSUE THREAD

**Issue by Hoopex** [ElemeFE/element#17197]
### Existing Component
Yes

### Component Name
el-upload

### Description
<el-upload 
            class="upload-demo" :limit="1">
            <i class="el-icon-upload"></i>
            <div class="el-upload__text">Drop thumbnail here or <em>click to upload</em></div>
          </el-upload>

I can't hide the upload box when data length >= limit and if i try to hide el-upload component it hides the upload box and all files
How i can hide the uploader box only?

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
