### ISSUE TITLE
[Bug Report] ELTree checkbox margin-right not working

### ISSUE THREAD

**Issue by myWsq** [ElemeFE/element#17198]
### Element UI version
2.11.1

### OS/Browsers version
macOS Mojave 10.14.5/Chrome 76

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/amkhsgyj/1/

### Steps to reproduce
@import url("//unpkg.com/element-ui@2.8.2/lib/theme-chalk/index.css");

Change theme version

### What is Expected?
Checkbox margin retrieval

### What is actually happening?
No margin

**Comment by ziyoung** [comment]
I think it's fixed in 2.12.0.
