### ISSUE TITLE
[Feature Request] upload - need to set the post parameters dynamically before uploading

### ISSUE THREAD

**Issue by lively-qcy** [ElemeFE/element#17194]
### Existing Component
是

### Component Name
upload

### Description
      <el-upload class="uploader" drag :show-file-list="false"
        action="http://xxx/import/"
        accept=".xlsx"
        :data="uploadData"
        :before-upload="beforeUpload"
        :on-success="uploadSuccess"
        :on-error="uploadError">

```
data(){
   return {
       uploadData:{}
   }
},
methods:{
   beforeUpload(){
         // do something...
         this.uploadData = {"name":"xiaoqiu"};    // not posted
   }
}
```

When I upload file,`uploadData` was changed, but was not posted because `data` Attribute is not responsive.I want to set the upload params dynamically before uploading,Can it be set by arguments?

for example:

```
beforeUpload(config){
    config.requestData = {"name":"xiaoqiu"} ...
}
```

Thank you !

**Comment by ziyoung** [comment]
Use `http-request`.

**Comment by lively-qcy** [comment]
Overwrite default action,that makes it more complicated ~~~
