### ISSUE TITLE
[Bug Report] Incorrect table column content rendered when columns changed dynamicly

### ISSUE THREAD

**Issue by lianzhao** [ElemeFE/element#17193]
### Element UI version
2.11.1

### OS/Browsers version
mac os 10.14.4   chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/pvgL1d4j/1/

### Steps to reproduce
Click the `show col 1` button

### What is Expected?
Render contents of `col 1`, which should be `0 1`

### What is actually happening?
The header of the column became `col 1` correctly, but the contents were not updated as expected.

Btw, If I change `col 1` to 
```vue
    <el-table-column v-if="visibleCol === 1" label="col1">
      <template #default="{ row }">col-1 row-{{row.id}}</template>
    </el-table-column>
```
Everything works fine.

**Comment by ziyoung** [comment]
Provide key for TableColumn.
