### ISSUE TITLE
Bug Report Select Selector Options Pop-up Location Problem on Mobile True Machine

### ISSUE THREAD

**Issue by javascriptNo1** [ElemeFE/element#17192]
### Element UI version
2.11.1

### OS/Browsers version
苹果，uc,微信

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/BlackRockShooterLove/qansLku4/

### Steps to reproduce
在使用el-select组件时，在页面添加样式  html{ overflow-x: hidden;}后，在手机使用时选项的弹出位置一直在输入框的上方，浏览器的模拟器没有出现此问题，真机上才会

### What is Expected?
与pc端一致

### What is actually happening?
与pc端不一致

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1

**Comment by javascriptNo1** [comment]
> Element is designed for desktop. It's not compatible with mobile devices. You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1

感谢建议，因为项目这边是pc端但是要兼容移动端，所以才希望组件在移动端的表现方式尽量和pc端一致
