### ISSUE TITLE
[Feature Request] DropDownMenu inherit parent's width

### ISSUE THREAD

**Issue by MatanYadaev** [ElemeFE/element#17195]
### Existing Component
Yes

### Component Name
DropDownMenu

### Description
It would nice to have a property that makes the menu of the dropdown 100% width (from the parent's width).

**Comment by ziyoung** [comment]
You can set width by using CSS.

**Comment by MatanYadaev** [comment]
@ziyoung I don't want to set it manually because it has programmatic top, left, right and because I don't know the width of the parent, it will make me use the Dom to get the width, which I don't want

It's kinda a basic feature for a drop-down menu, to fit within his parent width, why did you decide to close the issue?
