### ISSUE TITLE
tabs 标签页不支持v－for ？

### ISSUE THREAD

**Issue by chengkj99** [ElemeFE/element#1720]
<el-tabs type="border-card" class="table-switch">
            <el-tab-pane name="1" v－for＝“val in list-data”>
            </el-tab-pane>
          </el-tabs>

v－for在这里写报错！！！

**Comment by Kingwl** [comment]
'－' -> '-'

**Comment by QingWei-Li** [comment]
感人

**Comment by chengkj99** [comment]
@Kingwl  这里是我写错了，但是不是断字符的问题，但是还是要👍你好眼力啊
