### ISSUE TITLE
DateTimePicker 日期时间选择器

### ISSUE THREAD

**Issue by YangQingRui** [ElemeFE/element#17201]
![image](https://user-images.githubusercontent.com/23182326/63824473-d99a9580-c989-11e9-9b8e-fd7238c7c6bd.png)
DateTimePicker 日期时间选择器  属性 format和value-format皆设置为 yyyy-MM-dd HH 时：
想达到的目的是 只能选择年月日&时
但是如上图所示，在选择时间时，出现了秒

**Comment by Hchunjun** [comment]
请问，后续是怎么实现这个需求的呢？
