### ISSUE TITLE
[Feature Request] Allow users to manually adjust the drawer width

### ISSUE THREAD

**Issue by roelVerdonschot** [ElemeFE/element#17204]
### Existing Component
Yes

### Component Name
Drawer

### Description
With a table or other content in the drawer, it is sometimes easier to view if the user can make the drawer larger and smaller

**Comment by xrkffgg** [comment]
Drawer Attributes `size` ?

**Comment by roelVerdonschot** [comment]
The size prop is fixed. It would be useful if the side of the drawer is draggable to the left and right so the user can adjust size.

**Comment by luckyCao** [comment]
use size prop
