### ISSUE TITLE
[Bug Report] Dropdown drop-down menu cursor moved down to the space between text and pop-up drop-down menu, pop-up drop-down menu disappeared

### ISSUE THREAD

**Issue by zyz** [ElemeFE/element#17217]
### Element UI version
2.11.0

### OS/Browsers version
windows 10 / 火狐 68.0.2

### Vue version
2.5.21

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
忽略上面重现链接，因为使用的是你们官网实例
1.进入网址
https://element.eleme.cn/#/zh-CN/component/dropdown
2.基础用法 光标移到[下拉菜单]，弹出下拉菜单
3.光标下移到[下拉菜单]和弹出下拉菜单间空白处，弹出下拉菜单消失

### What is Expected?
和Select 选择器一样的效果
光标下移到[下拉菜单]和弹出下拉菜单间空白处，弹出下拉菜单不消失

### What is actually happening?
光标下移到[下拉菜单]和弹出下拉菜单间空白处，弹出下拉菜单消失

**Comment by luckyCao** [comment]
我们会在大版本调整这个问题
