### ISSUE TITLE
[Bug Report] el-upload  list-type="picture-card"时，选择完图片后，高度会变化

### ISSUE THREAD

**Issue by penjay** [ElemeFE/element#17215]
### Element UI version
2.11.1

### OS/Browsers version
Osx 10.14.6

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
可以直接在官方示例：照片墙，文件缩略图，用户头像上传中重现

### What is Expected?
el-upload picture-card模式，无论有没有图，其所占用的宽高应保持一致。

### What is actually happening?
高度会变化，当el-upload在el-dialog中时，el-dialog  @open时若初始化图片数据至el-upload，造成el-dialog抖动，即dialog会往下弹一下再还原（通过设置.el-upload-list__item的 transition可以解决部分问题）。
但控制不了el-upload有图片时下方padding？高度的变化，导致表单有些变形。

**Comment by penjay** [comment]
官方示例链接，可关注el-upload下面的空白高度
https://element.eleme.cn/#/zh-CN/component/upload

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by 15738039217** [comment]
I also encountered, almost all versions are like this, there is an extra 20 height at the bottom, the page display is abnormal
