### ISSUE TITLE
[Bug Report] Cascader Expansion Menu bug

### ISSUE THREAD

**Issue by FBshtml** [ElemeFE/element#17216]
### Element UI version
2.11.1

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/fbshtml/pen/PoYjpPw

### Steps to reproduce
1.点击input，展开子菜单，此时选中正常
2.点击切换value
3.点击input展开子菜单，此时选中异常

### What is Expected?
1.点击input，展开子菜单，此时选中正确
2.点击切换value
3.点击input展开子菜单，此时选中正确

### What is actually happening?
1.点击input，展开子菜单，此时选中正常
2.点击切换value
3.点击input展开子菜单，此时选中异常

**Comment by xrkffgg** [comment]
2.10 版本 是正常的

**Comment by xrkffgg** [comment]
https://github.com/ElemeFE/element/pull/16709

这里面 `syncActivePath` 恢复成之前的，可以正常显示了

@SimonaliaChen

**Comment by SimonaliaChen** [comment]
> #16709
> 
> 这里面 `syncActivePath` 恢复成之前的，可以正常显示了
> 
> @SimonaliaChen

抱歉，确实是之前的pr引起的，下个版本修复。
