### ISSUE TITLE
[Feature Request] Reusing component with multiple data in one Vue instance

### ISSUE THREAD

**Issue by momin-ctg** [ElemeFE/element#17228]
### Existing Component
Yes

### Component Name
Select

### Description
Similar components for one page but individual data populate

```
<el-select v-model="values" placeholder="Select Account">
              <el-option
                      v-for="item in optionss"
                      :key="item.values"
                      :label="item.label"
                      :values="item.values">
              </el-option>
 </el-select>
```

```
  <el-select v-model="value" placeholder="Select Account">
              <el-option
                      v-for="item in options"
                      :key="item.value"
                      :label="item.label"
                      :value="item.value">
              </el-option>
</el-select>

```

[Codepen Link](https://codepen.io/momin-ctg/pen/QWLgOpL)

One component works fine but other components select not work, but data populated correctly, Why?

**Comment by LishiJ** [comment]
I think you seem to be wrong.

In first component, the attr should be 'value', not be 'values'

```
<el-select v-model="values" placeholder="Select Account">
              <el-option
                      v-for="item in optionss"
                      :key="item.values"
                      :label="item.label"
                      :value="item.values">
              </el-option>
 </el-select>
```

**Comment by momin-ctg** [comment]
Okay fine ! but on select items will populate, but why are others not working?

**Comment by LishiJ** [comment]
> Okay fine ! but on select items will populate, but why are others not working?



> Okay fine ! but on select items will populate, but why are others not working?

Can you give a minimum reproducible example?

**Comment by momin-ctg** [comment]
Yes! Here is the link 

https://codepen.io/momin-ctg/pen/QWLgOpL
