### ISSUE TITLE
[Bug Report] About Select Components

### ISSUE THREAD

**Issue by Dicky-L** [ElemeFE/element#17225]
### Element UI version
2.4.11

### OS/Browsers version
windows10/edge

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Dicky-L/pen/mdbwMZr?&editable=true

### Steps to reproduce
说明：由于我们的网站还没上线，所以直接提交你们的demo地址：https://element.eleme.cn/#/zh-CN/component/select
步骤：
1.登录完成，打开客服
2.多次选择select框内容，会导致浏览器崩溃，次数不一定，有时候一次就崩溃，有时候重复点击一分钟才会崩溃或浏览器自动刷新，希望大神尽快解决这个问题，谢谢！

### What is Expected?
不再出现这个现象

### What is actually happening?
导致浏览器崩溃

**Comment by ziyoung** [comment]
无法重现。

**Comment by Dicky-L** [comment]
怎么会无法重现？多台设备都有同样问题！！

**Comment by xuleilala** [comment]
> 怎么会无法重现？多台设备都有同样问题！！

我也遇到了这个问题，请问你解决了吗？我这边edge切换10几次就会崩溃
