### ISSUE TITLE
[Feature Request] dispatch function in element/src/mixins/emitter.js

### ISSUE THREAD

**Issue by wxpeanut** [ElemeFE/element#17229]
### Existing Component
是

### Component Name
form input

### Description
parent.$emit.apply(parent, [eventName].concat(params));  加入params是个array类型化 会被打平 取到数组的第一个参数传给$emit

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by orangemio** [comment]
```
this.dispatch('AssetSelect', 'SelectionChange', [{Object1},{Object2}])

    this.$on('SelectionChange', (val) => {
      console.log(val)
    })

最后只会收到{Object1}
```
