### ISSUE TITLE
When the slot of a button is nested in the table header of the [Bug Report] table component, the calculated attribute added to the button does not take effect.

### ISSUE THREAD

**Issue by infjer** [ElemeFE/element#17221]
### Element UI version
2.11.1

### OS/Browsers version
MacOs 10.14.6 / Chrome 76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/7ymbwvkc/

### Steps to reproduce
1. el-table-column添加header的slot，里面放el-button，并且有一个disabled属性，由计算属性控制
2. 点击add，添加一行内容，初始的输入框为空，此时计算属性应返回true，并且使添加按钮禁用
3. 从重现链接里可以看到disabled属性未生效

### What is Expected?
按钮的属性能随内容的变化而动态变化

### What is actually happening?
按钮的属性未随内容的变化而动态变化

**Comment by infjer** [comment]
我在填写这个issue的时候，可能你们正好在更新2.12.0的版本，当时element版本下拉选项只有0.1.0一个。这个问题发生在2.11.1的版本。

**Comment by ziyoung** [comment]
区分出 slot 与 scoped-slot 的区别
```
<template slot='header'  slot-scope='props'>
</template>
```
如果已经使用了 Vue 2.6.x，使用新的 slot 语法吧。

**Comment by infjer** [comment]
感谢指正。是我没有好好读element文档，文档里写了“Table-column Scoped Slot”。
