### ISSUE TITLE
1.0.6版本错误 e._h is not a function

### ISSUE THREAD

**Issue by mark0325** [ElemeFE/element#1722]
把hello word demo直接复制要html问价中 运行是提示错误   e._h is not a function
不仅仅是官方demo报错 http://jsfiddle.net/leopoldthecuber/vcgftLvn/ 也提示同样的错误信息
e._h is not a function

**Comment by Leopoldthecoder** [comment]
和 #1706 是同一个问题，可以先按那里的方法解决。
