### ISSUE TITLE
[Feature Request] vue2.6 or more. Can I use # header instead of slot-scope in the use of named slots?

### ISSUE THREAD

**Issue by BobsLi** [ElemeFE/element#17239]
### Existing Component
是

### Component Name
el-tabel

### Description
在el-table里面自定义表头时，能否将slot-scope换成#header？如果可以，会不会有什么影响
在官方文档自定义表头这个示例中[https://codepen.io/bobsli/pen/rNBwgMR?&editable=true](https://codepen.io/bobsli/pen/rNBwgMR?&editable=true)，
如果slot-scope后面不需要prop参数的时候，将代码改成<template slot="header" slot-scope>，这样会造成那个输入框的输入错误，然而代码改成<template #header>就不会出现该错误

**Comment by a631807682** [comment]
例子中的语法等价于`vue 2.6`语法`v-slot:header="scope"`或`#header="scope"`，`v-slot`是为了代替`slot`/`slot-scope`语法，他们不能一起使用。有没有`scope`只是代表他是不是作用域插槽，如果是，则不会存在在`vm.$slots`里面。

**Comment by BobsLi** [comment]
> 例子中的语法等价于`vue 2.6`语法`v-slot:header="scope"`或`#header="scope"`，`v-slot`是为了代替`slot`/`slot-scope`语法，他们不能一起使用。有没有`scope`只是代表他是不是作用域插槽，如果是，则不会存在在`vm.$slots`里面。

谢谢，这个疑问解决了，那后面那一部分呢，若没有scope（因为有时候不需要组件内部绑定的prop），自定义的输入框双向绑定就出现了问题，输入的时候data值更新了，但是输入框显示没有更新
