### ISSUE TITLE
In the [Bug Report] IE browser, the read-only el-input box can focus and press the backspace page back.

### ISSUE THREAD

**Issue by lky5230** [ElemeFE/element#17231]
### Element UI version
2.12.0

### OS/Browsers version
ie11

### Vue version
2.6.10

### Reproduction Link
没有，jsfiddle 和 codepen 不支持ie11

### Steps to reproduce
1、点击只读的el-input 
2、el-input会聚焦
3、点击backspace，页面会后退

### What is Expected?
不会聚焦

### What is actually happening?
聚焦了，并且按backspace会后退

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.
