### ISSUE TITLE
[Bug Report] The latest version of the Tabs tab component crashes the page

### ISSUE THREAD

**Issue by wuhuisiyue** [ElemeFE/element#17236]
### Element UI version
2.12.0

### OS/Browsers version
Google Chrome 版本 75.0.3770.100（正式版本） （64 位）

### Vue version
2.5.10

### Reproduction Link
https://codepen.io/wangkaimin/pen/BaBZeyZ

### Steps to reproduce
 <el-tabs v-model="activeName" @tab-click="handleClick">
    <el-tab-pane label="用户管理" name="first">用户管理</el-tab-pane>
    <el-tab-pane label="配置管理" name="second">配置管理</el-tab-pane>
    <el-tab-pane label="角色管理" name="third">角色管理</el-tab-pane>
    <el-tab-pane label="定时任务补偿" name="fourth">定时任务补偿</el-tab-pane>
  </el-tabs>
在页面中使用该组件，从另外一个路由跳转到这个页面时，浏览器直接卡死

### What is Expected?
解决el-tabs卡死问题

### What is actually happening?
虽然在opencode里面是没有问题的，但是在实际项目中，无法运行，使用el-tables页面直接卡死

**Comment by xrkffgg** [comment]
卡死的原因是啥？

**Comment by wuhuisiyue** [comment]
不清楚，那个页面删除tabs组件正常运行，恢复就不行了，我用其他项目都是可以的 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：xrkffgg<notifications@github.com>

 
   时间：09:37:20 上午
 
   收信人：ElemeFE/element<element@noreply.github.com>

 
   抄送：王凯民<xxwangkaimin@sina.com>
,Author<author@noreply.github.com>

 
   标题：Re: [ElemeFE/element] [Bug Report] The latest version of the Tabs tab component crashes the page (#17236)
 
   
  卡死的原因是啥？

**Comment by xrkffgg** [comment]
@wuhuisiyue 一般这种轻量的组件 不会对页面造成很大影响的，看看是不是哪里报错了，或者是JS有BUG

**Comment by wuhuisiyue** [comment]
好的，谢谢 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：xrkffgg<notifications@github.com>

 
   时间：10:41:13 上午
 
   收信人：ElemeFE/element<element@noreply.github.com>

 
   抄送：王凯民<xxwangkaimin@sina.com>
,Mention<mention@noreply.github.com>

 
   标题：Re: [ElemeFE/element] [Bug Report] The latest version of the Tabs tab component crashes the page (#17236)
 
   
  @wuhuisiyue 一般这种轻量的组件 不会对页面造成很大影响的，看看是不是哪里报错了，或者是JS有BUG

**Comment by llcat** [comment]
@wuhuisiyue 你找到原因了吗？我发现这个问题是在element 2.8.0之后出现的，当vue版本<=2.5.13时，页面中`el-tab-pane`组件中只要存在元素或文本节点，就会造成页面卡死。我现在是升级vue到2.6.10解决这个问题

**Comment by ziyoung** [comment]
无法重现。

**Comment by wuhuisiyue** [comment]
是的，只有这一个项目有问题 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：hetech<notifications@github.com>

 
   时间：03:37:16 下午
 
   收信人：ElemeFE/element<element@noreply.github.com>

 
   抄送：王凯民<xxwangkaimin@sina.com>
,Mention<mention@noreply.github.com>

 
   标题：Re: [ElemeFE/element] [Bug Report] The latest version of the Tabs tab component crashes the page (#17236)
 
   
  无法重现。

**Comment by wuhuisiyue** [comment]
暂时放弃使用这个，只有这一个项目有问题 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：Pino Yu<notifications@github.com>

 
   时间：11:34:26 下午
 
   收信人：ElemeFE/element<element@noreply.github.com>

 
   抄送：王凯民<xxwangkaimin@sina.com>
,Mention<mention@noreply.github.com>

 
   标题：Re: [ElemeFE/element] [Bug Report] The latest version of the Tabs tab component crashes the page (#17236)
 
   
  @wuhuisiyue 你找到原因了吗？我发现这个问题是在element 2.8.0之后出现的，当vue版本<=2.5.13时，页面中el-tab-pane组件中只要存在元素或文本节点，就会造成页面卡死。我现在是升级vue到2.6.10解决这个问题

**Comment by pfasang** [comment]
Hi @wuhuisiyue , I have same issue. Did you find any solution?

**Comment by pfasang** [comment]
It's happening because infinite loop call update. See https://github.com/ElemeFE/element/pull/17380

**Comment by RookieHao** [comment]
遇到同样的问题，vue版本：2.5.10。element-ui版本：2.12.0.加入tabs,页面就死了，加载不出来。程序崩溃。没有报错。

**Comment by wuhuisiyue** [comment]
看其他人的解决办法好像是外层套个row加col，但是我已经放弃使用这个组件了，直接手写一个切换 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：RookieHao<notifications@github.com>

 
   时间：03:13:42 下午
 
   收信人：ElemeFE/element<element@noreply.github.com>

 
   抄送：王凯民<xxwangkaimin@sina.com>
,Mention<mention@noreply.github.com>

 
   标题：Re: [ElemeFE/element] [Bug Report] The latest version of the Tabs tab component crashes the page (#17236)
 
   
  遇到同样的问题，vue版本：2.5.10。element-ui版本：2.12.0.加入tabs,页面就死了，加载不出来。程序崩溃。没有报错。
