### ISSUE TITLE
[Feature Request] DatePicker - Add option to open it only by mouse click on calendar icon

### ISSUE THREAD

**Issue by jplumez** [ElemeFE/element#17232]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Hi guys,

First, thank you very much for your great work :-)

For one of my project, I need to use a date picker for some fields of my form. But, most of the time, the user will enter the date with the keyboard. It will be only from time to time that they will use the mouse to manually select the date. So I would want the datepicker to stay closed when the input is focused (they go from field to field with the tab button), and only open it when the user click on the calendar icon of the field with the mouse.

I checked the documentation multiple times and tried many ways to do it, but I could not find a way to do that right now (and I want to avoid a dirty hack that would close it with javascript). Did I miss something ? If not, would it be possible to add a parameter on the DatePicker to manage this option ?

Thanks in advance for the time that you'll spend on my request !
Best regards,

**Comment by wacky6** [comment]
Does it really matter ?

**Comment by fatbone008** [comment]
> Does it really matter ?

It matters a lot, my friend. I know it's only a web component lib, but there are increasing number of  web applications run on ipads or any kind of mobile device that support landscape viewport are suitable for date picker component, which means is should awake sort keyboard on these devices.

**Comment by fatbone008** [comment]
Does it have any tricky way we can go around it? It's also pleased to know.

**Comment by wacky6** [comment]
As far as I know, there is no workaround now.

Element is not designed for mobile use. For mobile, shouldn’t native input be used?

**Comment by ziyoung** [comment]
Element is designed for desktop. It's not compatible with mobile devices.  You can use other libraries like [vant](https://github.com/youzan/vant). FYI: https://github.com/vuejs/awesome-vue#mobile-1

**Comment by jplumez** [comment]
@ziyoung @wacky6 
Thanks for taking the time to look at my ticket, though I hoped that there would be a solution :( and my problem is for a desktop web app, I never talked about the mobile version.

**Comment by wacky6** [comment]
If it’s a desktop and user prefers keyboard. They should be able to “tab” through the form. 

The picker pop up will close when input box loses focus. In this case, whether the pop up shows won’t matter.
