### ISSUE TITLE
[Bug Report] Cascader generated Popper DOM is in display: none refresh the coordinate value

### ISSUE THREAD

**Issue by SuperGall** [ElemeFE/element#17244]
### Element UI version
2.12.0

### OS/Browsers version
Chrome 76

### Vue version
2.6.0

### Reproduction Link
https://codepen.io/yoyoka1995/pen/MWgoVJK

### Steps to reproduce
在页面中编写复数Cascader组件，点击Cascader组件，生成对应的Popper DOM，之后再隐藏Popper DOM，并滚动显示区，Popper DOM不停刷新DOM的坐标值，引发重绘，造成严重的掉帧。![avatar](https://images2.imgbox.com/ca/71/U4h0USf2_o.gif)

### What is Expected?
Popper DOM处于display: none的状态下，滚动显示区不刷新DOM坐标值，减少重绘。

### What is actually happening?
Popper DOM处于display: none的状态下，滚动显示区刷新DOM坐标值，复数Popper DOM刷新会造成严重的掉帧。

**Comment by ziyoung** [comment]
项目依赖的 popper 很老了。大版本会优化。
