### ISSUE TITLE
[Bug Report] "current-node-key" in Tree doesn't work when I change the value, CSS doesn't change.

### ISSUE THREAD

**Issue by uu109** [ElemeFE/element#17246]
### Element UI version
2.12.0

### OS/Browsers version
Google Chrome  76.0.3809.132

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/fz6v4kLr/

### Steps to reproduce
1. Bind the "current-node-key" Attributes on Tree components.
2. Change this value.

Now can see, the value already changed, but the node on HTML looks like not has any change, "is-current" class doesn't move to the new current node.

### What is Expected?
The current node should change style when I change the "current-node-key" value.

### What is actually happening?
It doesn't work.
by the way, Is "current-node-key" value should change when I click another node?

**Comment by ziyoung** [comment]
`current-node-key` is not reactive.

**Comment by Yalhu** [comment]
> `current-node-key` is not reactive.
@ziyoung 
Why the current node has been updated, the css doesn't work, like: highlight  ?
And I has to set `oldNode.isCurrent=false; newNode.isCurrent=true` or `tree.setCurrentKey`.
