### ISSUE TITLE
[Bug Report] Table Header and Content Misalignment when Horizontal Scrollbar

### ISSUE THREAD

**Issue by qqcbqqkcel** [ElemeFE/element#17240]
### Element UI version
2.12.0

### OS/Browsers version
win10/chrome 70/76

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/qqcbqqkcel/4xzdscho/15/

### Steps to reproduce
0.需要异步加载数据
1.table需要设置height
2.table需要出现横向滚动条
3.横向滚动到最右

### What is Expected?
消除错位

### What is actually happening?
错位

**Comment by ziyoung** [comment]
无法重现。

**Comment by qqcbqqkcel** [comment]
https://jsfiddle.net/qqcbqqkcel/4xzdscho/20/
@ziyoung 
大佬看看

不知道为什么那个链接变成404了

**Comment by qqcbqqkcel** [comment]
> 无法重现。

https://codepen.io/qqcbqqkcel/pen/oNvGjeW

大佬看看

不知道为什么那个链接变成404了
