### ISSUE TITLE
[Bug Report] Wrong Chinese Official Documents

### ISSUE THREAD

**Issue by MagnetLin** [ElemeFE/element#17243]
### Element UI version
2.11.1

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element

### Steps to reproduce
"使用 el-time-select 标签，分别通过star、end和step指定可选的起始时间、结束时间和步长",这句话里面的star写错了，应该是start

### What is Expected?
使用 el-time-select 标签，分别通过start、end和step指定可选的起始时间、结束时间和步长

### What is actually happening?
使用 el-time-select 标签，分别通过star、end和step指定可选的起始时间、结束时间和步长

**Comment by wacky6** [comment]
fixed in https://github.com/ElemeFE/element/pull/17250
