### ISSUE TITLE
When [Bug Report] Cascader cascade selector selects a search item, the data in the cascade box is not selected synchronously

### ISSUE THREAD

**Issue by wubianluoye** [ElemeFE/element#17241]
### Element UI version
2.12.0

### OS/Browsers version
windows10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wubianluoye/pen/rNBwEqy

### Steps to reproduce
1.首先，要有个带有搜索的级联选择器；
2.先选中一组值；
3.搜索其他值并选中；
4.点击级联选则器，选择器中的级联项未匹配。

### What is Expected?
选中的值与级联中的选项匹配。

### What is actually happening?
级联选择器中的选项与选中的值不匹配。

**Comment by ziyoung** [comment]
无法重现。

**Comment by wubianluoye** [comment]
结果：

------------------ 原始邮件 ------------------
发件人: "hetech"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 下午3:22
收件人: "ElemeFE/element"<element@noreply.github.com>;
抄送: "不赖"<575784835@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ElemeFE/element] When [Bug Report] Cascader cascade selectorselects a search item, the data in the cascade box is not selectedsynchronously (#17241)




无法重现。

**Comment by zgq456** [comment]
in the webpage show above: Https://codepen.io/wubianluoye/pen/rNBwEqy
first , we manually choose 组件/Form/Checkbox， and then we try to search "一致" in the field.  and select "指南/设计原则/一致"， click the input , you fill find the popup still select "组件/Form" 
![微信截图_20200429144748](https://user-images.githubusercontent.com/5786294/80567927-961c8d80-8a28-11ea-84fd-780cce0472a6.png)
