### ISSUE TITLE
[Bug Report] el-progress status will give an alarm if it does not pass values

### ISSUE THREAD

**Issue by Dragon-Rider** [ElemeFE/element#17249]
### Element UI version
2.11.1

### OS/Browsers version
mac/chrome

### Vue version
2.5.21

### Reproduction Link
https://jsfiddle.net/EragonJiang/y2smu1be/2/

### Steps to reproduce
看代码就可以，看console。<el-progress :status="false ? 'success':''" :percentage="100"></el-progress>
注意这里的未false会警告，status这个必须有值，不能为空。
![image](https://user-images.githubusercontent.com/8859216/64013678-ef0eeb80-cb52-11e9-8a6b-aa759188a63e.png)

### What is Expected?
status可以传空或者默认值“—”

### What is actually happening?
会报warning

**Comment by Dragon-Rider** [comment]
<el-progress :status="false ? 'success':''" :percentage="100"></el-progress>

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
