### ISSUE TITLE
[Bug Report] Slider can't set custom marker position

### ISSUE THREAD

**Issue by jokerstudios** [ElemeFE/element#17251]
### Element UI version
2.12.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/bpqa5erm/1/

### Steps to reproduce
1) Add a el-slider.
2) Create computed function for marker
3) Set marker points as variables like this:
```
computed:{
  parameter_custom_input_marker(){
  var min = this.selected_parameter_data.min.toString();
  var max = this.selected_parameter_data.max.toString();
  var min_value= this.selected_parameter_data.min;
            var max_value= this.selected_parameter_data.max;

            return {
                min_value:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', min)
                }, 
                max_value:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', max)
                }
            }
        }
    },
```
### What is Expected?
That the sliders min and max markers take the arguments from the variables min_value and max_value. See below the expected results from vue.js developertools in Chrome
marks:Object
 0:Object 
 100:Object

### What is actually happening?
The slider interprets the values as key-names and doesnt take their values as the key-names. See below the results from vue.js developertools in Chrome
marks:Object
 min_value:Object 
 max_value:Object

**Comment by ziyoung** [comment]
https://element.eleme.cn/2.12/#/en-US/component/slider#show-marks

**Comment by jokerstudios** [comment]
Sorry but I can't find anything in the documentation regarding my issue?
Here is the slider object
`      yaxis: [
        {
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: '#008FFB'
          },
          labels: {
            style: {
              color: '#008FFB',
            }
          },
          title: {
            text: "Income (thousand crores)",
            style: {
              color: '#008FFB',
            }
          },
          tooltip: {
            enabled: true
          }
        },

        {
          seriesName: 'Income',
          opposite: true,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: '#00E396'
          },
          labels: {
            style: {
              color: '#00E396',
            }
          },
          title: {
            text: "Operating Cashflow (thousand crores)",
            style: {
              color: '#00E396',
            }
          },
        },
        {
          seriesName: 'Revenue',
          opposite: true,
          axisTicks: {
            show: true,
          },
          axisBorder: {
            show: true,
            color: '#FEB019'
          },
          labels: {
            style: {
              color: '#FEB019',
            },
          },
          title: {
            text: "Revenue (thousand crores)",
            style: {
              color: '#FEB019',
            }
          }
        },
      ],`

And the slider isn't showing any markers at all.
But if I change the compute function to the following, it works. But i don't want static values.
`computed:{
        parameter_custom_input_marker(){
            var min = this.selected_parameter_data.min.toString();
            var max = this.selected_parameter_data.max.toString();
            var min_value= this.selected_parameter_data.min;
            var max_value= this.selected_parameter_data.max;
            window.console.log(min_value)
            window.console.log(max_value)

            return {
                0:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', min)
                }, 
                100:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', max)
                }
            }
        }
    },`

**Comment by ziyoung** [comment]
Use new ES6 syntax https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names
```js
const min = 0
const max = 100
return {
   [min]: {},
   [max]: {}                
}

```
