### ISSUE TITLE
Under the [Bug Report] flex layout, el-table (fixed column) header and body are misaligned

### ISSUE THREAD

**Issue by 720t** [ElemeFE/element#17258]
### Element UI version
2.12.0

### OS/Browsers version
win10, chrom69.0.349

### Vue version
2.6.10

### Reproduction Link
https://720t.github.io/veea/#/example/table

### Steps to reproduce
- 打开:https://720t.github.io/veea/

   username: admin
   password: 111111

- 打开:示例/表格

- 横向拖动滚动条到最后

  会发现 表格 header 与 body 错位

- 其它说明 
  - v2.7.2版本没有这个问题 
  - v2.12.0有这个问题

### What is Expected?
 header 与 body 位置对齐

### What is actually happening?
 header 与 body 位置没有对齐

**Comment by ziyoung** [comment]
demo 修改了覆盖了滚动条。怀疑是滚动条样式影响的，其提供一个更为简介的 demo。

**Comment by 720t** [comment]
> demo 修改了覆盖了滚动条。怀疑是滚动条样式影响的，其提供一个更为简介的 demo。
兄弟,你这个答案你自己都不服吧,难道说用户不能自定义滚动条了?
而且,就简单的换个 element-ui 版本到 v2.7.2,就没这个问题

别外,加上 show-summary 参数报错:
 [Vue warn]: Error in nextTick: "TypeError: this.$el.querySelectorAll is not a function"

**Comment by ziyoung** [comment]
![image](https://user-images.githubusercontent.com/12947422/64146644-4f9e7100-ce50-11e9-92df-d3e47aa22801.png)

这里错开的宽度大概是一个滚动条宽度。提供一个 codepen 链接吧。

**Comment by ziyoung** [comment]
2.7.2 之后 table 增加了许多新特性，有许多的改动，建议提供一个简洁的 demo 方便我们排查问题。

**Comment by ziyoung** [comment]
没有具体的代码链接，issue 关闭。

**Comment by ziyoung** [comment]
与 issue #17060 类似，可能是一类问题。

**Comment by xiaogaofudao** [comment]
@ziyoung 升级 2.13.0 还是存在表头，表体 边框错位问题

**Comment by xtqjh** [comment]
table 横向滚动时表头明显延时

https://user-images.githubusercontent.com/7663676/171317123-f095c7ed-d3da-45a8-847f-154a959df285.mov
