### ISSUE TITLE
TypeError: _vm._h is not a function after updating element-ui to latest version

### ISSUE THREAD

**Issue by chagamkamalakar** [ElemeFE/element#1725]
I am using it with laravel. everything was working fine , but i did npm update, it started throwing that error

i tried to downgrade element-ui to 1.0.1, still the problem persisists 

any help please?

**Comment by Leopoldthecoder** [comment]
Please lock these dependencies:
"vue-template-compiler": "2.1.4"
"vue-loader": "10.0.0"
"vue": "2.1.4"

The error is caused by Vue 2.1.5 where `_h` is replaced with `_c`. We'll soon publish a new version.

For more information, see #1706

**Comment by chagamkamalakar** [comment]
LinusBorg suggested on https://forum.vuejs.org/t/typeerror--vm--h-is-not-a-function-after-updating-vuejs-2-1-5-from-2-1/4032/3
```
I found this commit1 in Vue which renamed _h to _c, I assume this has something to do with the problem.

But this is not to be considered a breaking change because _h it is not a public API, so 3rd-party plugins/components should not rely on it. If element-ui (and/or others) rely on this internal API, they have to fix it.
```

**Comment by chagamkamalakar** [comment]
the error i have got after locking dependecies 

```
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.4
- vue-template-compiler@2.1.4

```

**Comment by chagamkamalakar** [comment]
i did mistake  vue@2.0.4 instead of 2.1.4 ... now working fine
