### ISSUE TITLE
[Bug Report] TypeError: _this2. $scopedSlots. default is not a function

### ISSUE THREAD

**Issue by qingyulove** [ElemeFE/element#17253]
### Element UI version
2.11.1

### OS/Browsers version
windows10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/k56ftdzw/1/

### Steps to reproduce

1、新建 test.vue文件，并使用rendor函数递归渲染el-table

<script>
    export default {
        data() {
            return {
                list: []
            }
        },
        props : {
            data : {
                type : Array,
                default : () => {
                    return [];
                }
            },
            tableData : {
                type : Array,
                default : () => {
                    return [];
                }
            }
        },
        // 因为表格渲染需要根据菜单节点进行递归渲染, 使用 render 函数代替 html 模板渲染.
        render(createElement) {
            let _this = this;
            const create = (menuNode, createElement) => {
                // 根节点为数组, 直接创建 template 包裹表头
                if(Array.isArray(menuNode)) {
                    return createElement(
                        'el-table', 
                        {
                            props : {
                                data : _this.tableData,
                            },
                            style:{
                                width:"100%",
                            },
                        },
                        [
                            ...menuNode.map(function(item) {
                                return create(item, createElement)
                            })
                            
                        ]
                    );
                }
                // 有子节点, 创建 列 节点
                if(Array.isArray(menuNode.children) && menuNode.children.length > 0) {
                    return createElement(
                        'el-table-column',
                        {
                            props : {
                                label : menuNode.label,
                                prop :  menuNode.prop,
                                key : menuNode.id+menuNode.prop
                            },
                        },
                        [
                            ...menuNode.children.map(function(item) {
                                return create(item, createElement)
                            })
                            
                        ]
                    )
                }
                if(menuNode.slot){
                    return createElement(
                        'el-table-column',
                        {
                            props : {
                                label : menuNode.label,
                                prop :  menuNode.prop,
                                key : menuNode.id+menuNode.prop
                            },
                        },
                        [
                            this.$scopedSlots.default()
                        ]
                    );
                }else{
                    return createElement(
                        'el-table-column',
                        {
                            props : {
                                label : menuNode.label,
                                prop :  menuNode.prop,
                                key : menuNode.id+menuNode.prop
                            },
                        },
                    );
                }
                
            }

            return create(this.data, createElement);
        },
        watch : {
        
        },
        methods : {
        
        }
    }
</script>

2、在store文件中引用test.vue组件

![image](https://user-images.githubusercontent.com/14515520/64058580-c41ea900-cbdf-11e9-9c27-4f9be1df49c6.png)

<script>
import test from './test'
export default {
    data() {
        return {
            headerData:[
                {
                    id:2,
                    label:'配送信息',
                    prop:'send',
                    children:[
                        {
                            id:3,
                            label:'姓名',
                            prop:'name',
                            slot: true
                        },
                        {
                            id:4,
                            label:'地址',
                            prop:'detail',
                            children:[
                                {
                                    id:5,
                                    label:'省份',
                                    prop:'province',
                                },
                                {
                                    id:6,
                                    label:'市区',
                                    prop:'city',
                                },
                                {
                                    id:7,
                                    label:'详细地址',
                                    prop:'address',
                                },
                                {
                                    id:8,
                                    label:'邮编',
                                    prop:'zip',
                                }
                            ]
                        }
                    ],
                }
            ],
            tableData: [{
                date: '2016-05-03',
                name: '王小虎',
                province: '上海',
                city: '普陀区',
                address: '上海市普陀区金沙江路 1518 弄',
                zip: 200333
                }],
            
        }
    },
    components: {
        test,
    },
}
</script>

### What is Expected?
能够正确渲染表格，并且在可以在定义的默认插槽中插入 <p>具名插槽</p>

### What is actually happening?
渲染失败！提示如下：
TypeError: _this2.$scopedSlots.default is not a function
    at create (test.vue?b018:76)
    at eval (test.vue?b018:67)
    at Array.map (<anonymous>)
    at create (test.vue?b018:58)
    at eval (test.vue?b018:48)
    at Array.map (<anonymous>)
    at create (test.vue?b018:38)
    at Proxy.render (test.vue?b018:105)
    at VueComponent.Vue._render (vue.min.js:4385)
    at VueComponent.updateComponent (vue.min.js:2694)

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by wanyibin** [comment]
我也遇到了同样的问题 vue项目 在iview中table组件的render函数中调用定义的方法 报_this2.函数名not function  请问您是怎么解决的
