### ISSUE TITLE
[Feature Request] select change event

### ISSUE THREAD

**Issue by srrgithub** [ElemeFE/element#17252]
### Existing Component
是

### Component Name
el-select

### Description
问题1：select change 返回的只有value， 没有label 的值。

  期望1：新增属性。label-in-value	在返回选项时，是否将 label 和 value 一并返回，默认只返回 value

问题2：回显的问题，如果没有候选项，默认回显value的值，  但是通常value值为id并无显示的意义

  期望2：新增属性label。仅在 remote 模式下，初始化时使用。因为仅通过 value 无法得知选项的 label，需手动设置。

**Comment by ziyoung** [comment]
针对问题1，el-select的行为与原生 select 保持一致。
没明白问题2的描述问题，你可以提供一个详细的demo。
