### ISSUE TITLE
[Bug Report] Conditional Judgment Inadequate

### ISSUE THREAD

**Issue by agamem** [ElemeFE/element#17256]
### Element UI version
2.12.0

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/null

### Steps to reproduce
null

### What is Expected?
null

### What is actually happening?
element/packages/table/src/table-layout.js

Line 100 in 45cb58a

 const headerTrElm = headerWrapper.querySelector('.el-table__header tr'); 

当this.showHeader = false, headerWrapper = undefined 时，100行报错
97 if (this.showHeader && !headerWrapper) return;
98
99 // fix issue (#16956)
100 const headerTrElm = headerWrapper.querySelector('.el-table__header tr');
101 const noneHeader = this.headerDisplayNone(headerTrElm);

**Comment by ziyoung** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by Shuhua95** [comment]
https://codepen.io/shuhua95/pen/QWLqwXv

**Comment by agamem** [comment]
这个issue跟有没有样例有什么关系？
第97行的条件判断，无法保证第100行的headerWrapper是已经被初始化过的。
很明显的逻辑判断不充分啊！

**Comment by ziyoung** [comment]
> 这个issue跟有没有样例有什么关系？
> 第97行的条件判断，无法保证第100行的headerWrapper是已经被初始化过的。
> 很明显的逻辑判断不充分啊！

@agamem 在 #17341 已经修复了。
