### ISSUE TITLE
[Feature Request] Want to add an anchor component

### ISSUE THREAD

**Issue by lshz0088** [ElemeFE/element#17262]
### Existing Component
否

### Component Name
Anchor

### Description
You need to show anchor links that can be jumped on the current page, and jump quickly between anchors.

like this
> https://ant.design/components/anchor-cn/#components-anchor-demo-basic

![image](https://user-images.githubusercontent.com/27722002/64086779-a9c60600-cd6c-11e9-95fa-388c43e1c161.png)

**Comment by ziyoung** [comment]
pr welcome.
