### ISSUE TITLE
[Bug Report] dropdown.d.ts lacks hide-timeout and show-timeout

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#17265]
### Element UI version
2.12.0

### OS/Browsers version
windows10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/w1qxdfrc/1/

### Steps to reproduce
hover link

### What is Expected?
showTimeout,hideTimeout补全

### What is actually happening?
https://github.com/ElemeFE/element/blob/dev/types/dropdown.d.ts 无showTimeout,hideTimeout

**Comment by ziyoung** [comment]
@ac88 pe welcome.
