### ISSUE TITLE
[Feature Request] Input component composite input box supports clearable attribute

### ISSUE THREAD

**Issue by SagaciousLittle** [ElemeFE/element#17268]
### Existing Component
是

### Component Name
Input

### Description
I hope to support this feature, I think this is a commonly used function~
This is my code, only composite components take effect:
```
<el-input v-model="search" clearable class="search">
  <el-button slot="append">search</el-button>
</el-input>
```

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Comment by iamkun** [comment]
Sorry, we have no plan to support this.
