### ISSUE TITLE
[Bug Report] Errors will be reported when using `show-header'to hide the header and `height' or `max-height'to set the height simultaneously in el-table

### ISSUE THREAD

**Issue by sws797** [ElemeFE/element#17272]
### Element UI version
2.12.0

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/w54nto1y/

### Steps to reproduce
在`el-table`标签中同时设置  
`:show-header="false"`  
和  
`max-header="120px"`  
，在console中会有报错  
`[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'querySelector' of undefined"`

### What is Expected?
不报错，隐藏表头时，设置高度不会再减去表头的高度

### What is actually happening?
似乎是因为找不到表头所以报错

**Comment by TinkoLiu** [comment]
Reproduced. Any maintainer?

**Comment by maxired** [comment]
Hi, I am also facing this issue.
the bug is due to this line https://github.com/ElemeFE/element/blob/90c5d74fd3c18f75628fc20cae4cdbad7e1591b8/packages/table/src/table-layout.js#L100

**Comment by asself** [comment]
the same issue faced
