### ISSUE TITLE
[Bug Report] el-popover not support Vue 2.6.0 v-slot, element-ui@2.12.0

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#17274]
### Element UI version
2.12.0

### OS/Browsers version
MAC OS 10.14 / Google Chrome 76

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/panhezeng/pen/zVGRVR

### Steps to reproduce
根据vue文档关于具名插槽部分和官方element popover 嵌套信息示例
把
<el-button slot="reference">click 激活</el-button>
替换为
<template v-slot:reference><el-button>click 激活</el-button></template>
后，
点击按钮没有弹出表格框

v-slot 指令自 Vue 2.6.0 起被引入，提供更好的支持 slot 和 slot-scope 特性的 API 替代方案。v-slot 完整的由来参见这份 RFC。在接下来所有的 2.x 版本中 slot 和 slot-scope 特性仍会被支持，但已经被官方废弃且不会出现在 Vue 3 中。

### What is Expected?
点击按钮弹出表格框

### What is actually happening?
点击按钮没有弹出表格框

**Comment by sigtm** [comment]
I've run into the same problem. Specifically, what appears to happen:

- When using `slot="reference"` the popover is appended to `<body>` as usual
- When using `<template v-slot:reference>` it is rendered in the same parent node as the reference, where it is in the template:

https://github.com/ElemeFE/element/blob/dev/packages/popover/src/main.vue

In my case I can see the popover, but it is placed at `top/left: 0` on top of the reference element, so I had to revert to `slot="reference"` for now.

**Comment by HeWei-imagineer** [comment]
so, can I use v-slot replace slot-scope in element-ui?
