### ISSUE TITLE
[Bug Report] MessageBox自定义内容无法使用i18n翻译

### ISSUE THREAD

**Issue by zhaojh329** [ElemeFE/element#17271]
### Element UI version
2.12.0

### OS/Browsers version
Windows10 / Google Chrome76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/8tqs9hm6/5/

### Steps to reproduce
1、自定义一个Vue组件，在组件里面用到了i18n，例如：
    Vue.component('my-span', {
       template: '<span>{{ $t("hello") }}</span>'
    })
2、使用MessageBox自定义内容，显示这个组件。
      const h = this.$createElement;
      this.$msgbox({
      	title: '消息',
         message: h('button-counter')
      });

### What is Expected?
MessageBox弹框能正常运行，并且翻译正常。

### What is actually happening?
vue.js:9049 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:9058 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
vue.js:634 [Vue warn]: Error in render: "TypeError: Cannot read property '_t' of undefined"

found in

---> <MySpan>
       <Root>
warn @ vue.js:634
logError @ vue.js:1893
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
Vue._render @ vue.js:3547
updateComponent @ vue.js:4061
get @ vue.js:4472
Watcher @ vue.js:4461
mountComponent @ vue.js:4068
Vue.$mount @ vue.js:9038
Vue.$mount @ vue.js:11923
init @ vue.js:3125
createComponent @ vue.js:5967
createElm @ vue.js:5914
createChildren @ vue.js:6042
createElm @ vue.js:5943
updateChildren @ vue.js:6205
patchVnode @ vue.js:6308
updateChildren @ vue.js:6182
patchVnode @ vue.js:6308
updateChildren @ vue.js:6182
patchVnode @ vue.js:6308
patch @ vue.js:6469
Vue._update @ vue.js:3943
updateComponent @ vue.js:4061
get @ vue.js:4472
run @ vue.js:4547
flushSchedulerQueue @ vue.js:4305
(anonymous) @ vue.js:1989
flushCallbacks @ vue.js:1915
Promise.then (async)
timerFunc @ vue.js:1942
nextTick @ vue.js:1999
Vue.$nextTick @ vue.js:3518
handler @ index.js:1
Vue.$watch @ vue.js:4939
createWatcher @ vue.js:4896
initWatch @ vue.js:4875
initState @ vue.js:4641
Vue._init @ vue.js:4994
VueComponent @ vue.js:5141
e @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
open @ (index):58
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
invokeWithErrorHandling @ vue.js:1863
Vue.$emit @ vue.js:3883
handleClick @ index.js:1
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
original._wrapper @ vue.js:7541
vue.js:1897 TypeError: Cannot read property '_t' of undefined
    at Proxy.Vue.$t (vue-i18n.js:183)
    at Proxy.eval (eval at createFunction (vue.js:11628), <anonymous>:3:36)
    at VueComponent.Vue._render (vue.js:3545)
    at VueComponent.updateComponent (vue.js:4061)
    at Watcher.get (vue.js:4472)
    at new Watcher (vue.js:4461)
    at mountComponent (vue.js:4068)
    at VueComponent.Vue.$mount (vue.js:9038)
    at VueComponent.Vue.$mount (vue.js:11923)
    at init (vue.js:3125)
logError @ vue.js:1897
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
Vue._render @ vue.js:3547
updateComponent @ vue.js:4061
get @ vue.js:4472
Watcher @ vue.js:4461
mountComponent @ vue.js:4068
Vue.$mount @ vue.js:9038
Vue.$mount @ vue.js:11923
init @ vue.js:3125
createComponent @ vue.js:5967
createElm @ vue.js:5914
createChildren @ vue.js:6042
createElm @ vue.js:5943
updateChildren @ vue.js:6205
patchVnode @ vue.js:6308
updateChildren @ vue.js:6182
patchVnode @ vue.js:6308
updateChildren @ vue.js:6182
patchVnode @ vue.js:6308
patch @ vue.js:6469
Vue._update @ vue.js:3943
updateComponent @ vue.js:4061
get @ vue.js:4472
run @ vue.js:4547
flushSchedulerQueue @ vue.js:4305
(anonymous) @ vue.js:1989
flushCallbacks @ vue.js:1915
Promise.then (async)
timerFunc @ vue.js:1942
nextTick @ vue.js:1999
Vue.$nextTick @ vue.js:3518
handler @ index.js:1
Vue.$watch @ vue.js:4939
createWatcher @ vue.js:4896
initWatch @ vue.js:4875
initState @ vue.js:4641
Vue._init @ vue.js:4994
VueComponent @ vue.js:5141
e @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
open @ (index):58
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
invokeWithErrorHandling @ vue.js:1863
Vue.$emit @ vue.js:3883
handleClick @ index.js:1
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
original._wrapper @ vue.js:7541

**Comment by wxfred** [comment]
请问，如何解决的呢？

**Comment by jhxxs** [comment]
我也遇到同样的问题了。请问该怎么解决?
