### ISSUE TITLE
[Feature Request] Can't choose ColorPicker language or text in buttons

### ISSUE THREAD

**Issue by RobertoBea** [ElemeFE/element#17286]
### Existing Component
Yes

### Component Name
ColorPicker

### Description
ColorPicker have 2 buttons to accept or decline the color selected, but they are in chinese, it would be great if we can change the text with a property or any other kind of solution

Thanks

**Comment by game09488** [comment]
@RobertoBea I ended up changing it with jQuery

```
$(function() {
   document.querySelector('.el-color-dropdown__link-btn').innerText = 'Clear';
   document.querySelector('.el-color-dropdown__btn').innerText = 'Save';
});
```
