### ISSUE TITLE
[Bug Report] The local image address of the image component failed to load

### ISSUE THREAD

**Issue by lx815** [ElemeFE/element#17294]
### Element UI version
2.12.0

### OS/Browsers version
windows10/Chrome  76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/boilerplate/vue

### Steps to reproduce
    <el-image src="@/assets/img/xxx.png">
      <div slot="error" class="image-slot">
        <i class="el-icon-picture-outline"></i>
      </div>
    </el-image>
    image组件内输入本地路径的图片地址不会加载正确的图片出来

    直接在<img src="../assets/img/index_noData.png" alt="模块暂未开放">标签中输入本地图片地址可以正常显示

### What is Expected?
image组件内输入本地路径的图片地址可以正常加载

### What is actually happening?
image组件内输入本地路径的图片地址不能正常加载

**Comment by xrkffgg** [comment]
😂 Base64 搞起
