### ISSUE TITLE
popover 报错 

### ISSUE THREAD

**Issue by fandudu** [ElemeFE/element#1729]

**Comment by fandudu** [comment]
我的代码：<el-button v-popover:popover>click 激活</el-button>
            <el-popover
            ref="popover"
            placement="right"
            width="400"
            trigger="click">
            <el-table :data="gridData">
              <el-table-column width="150" property="date" label="日期"></el-table-column>
              <el-table-column width="100" property="name" label="姓名"></el-table-column>
              <el-table-column width="300" property="address" label="地址"></el-table-column>
            </el-table>
          </el-popover>
控制台：
![image](https://cloud.githubusercontent.com/assets/15722726/21147402/d580acbe-c18f-11e6-881d-dd182c3e8d7a.png)

**Comment by fandudu** [comment]
![image](https://cloud.githubusercontent.com/assets/15722726/21147442/02f42270-c190-11e6-8681-b1fa4d7cf193.png)

**Comment by QingWei-Li** [comment]
顺序反了，必须先 popover 后才能放 `v-popover`
