### ISSUE TITLE
[Feature Request] Table Multilevel Header, Table Tail Total Row

### ISSUE THREAD

**Issue by jaihao** [ElemeFE/element#17305]
### Existing Component
是

### Component Name
table

### Description
请问table 多级表头的表尾合计行，怎么配置？

**Comment by jaihao** [comment]
![微信截图_20190904095315](https://user-images.githubusercontent.com/26615374/64220232-33a3d980-cefb-11e9-8776-b4bb67dfe17e.png)
 这种格式的

**Comment by jaihao** [comment]
效果如下
![微信截图_20190904102036](https://user-images.githubusercontent.com/26615374/64220986-d52c2a80-cefd-11e9-8c2a-c70d8ba7ad6e.png)

**Comment by AmbitionXiaojun** [comment]
；ll了
