### ISSUE TITLE
table组件中，无数据时，  暂无数据的显示如何去除

### ISSUE THREAD

**Issue by zhoujiamin** [ElemeFE/element#1730]
希望将暂无数据去除

 

### ElementUI version

1.0.6
### OS/Browers version

Chrome 54.0.2840.9
### Vue version

2.1.4
### Steps to reproduce
table组件中，无数据时，  暂无数据的显示如何去除？

### What is Expected?
希望  “暂无数据” 四个字不显示

**Comment by Leopoldthecoder** [comment]
参考：http://jsfiddle.net/leopoldthecuber/oqvsdkq2/
