### ISSUE TITLE
date-picker: Uncaught TypeError: Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/element#1731]
### ElementUI version
1.0.6

### OS/Browers version
Chrome 53

### Vue version
 2.1.4

第一次鼠标滑过日期框内右侧图标必现，设置日期后没再出现
另外不影响使用

![image](https://cloud.githubusercontent.com/assets/22360070/21167462/953f5314-c1e7-11e6-9c3d-d5249dff191a.png)

**Comment by QingWei-Li** [comment]
已经修复在下一版
