### ISSUE TITLE
[Bug Report] el-select cannot correctly display the initial selected option when using the list of objects for remote search

### ISSUE THREAD

**Issue by Lynn-cc** [ElemeFE/element#17322]
### Element UI version
2.12.0

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lynn-cc/pen/xxKPdrm?&editable=true

### Steps to reproduce
设置select为远程搜索，设置option为对象，包含label和value，设置好value-key为value。
select设置初始v-model值，为任意远程可搜索的对象列表。

### What is Expected?
初始对象值列表可以被正确解析和显示成tag格式

### What is actually happening?
初始对象值列表无法正确显示tag的label，是空白tag，新选择了元素之后，才会重渲染为正确的tag的label

**Comment by Lynn-cc** [comment]
I found that only if the items in v-model array shows in the remote search results, the blank tag label would change to be a right tag.

**Comment by kabushikikaisha-akane** [comment]
同样的问题，从2.4.11升级至 2.12后就出现了。

**Comment by twheastasia** [comment]
> I found that only if the items in v-model array shows in the remote search results, the blank tag label would change to be a right tag.

把value默认值设置成这样试试
`value: ['Alabama', 'Alaska']`

**Comment by tomorrowsky** [comment]
遇到同样的问题，请问这个问题解决了吗？
