### ISSUE TITLE
table组件中，无数据时，如何将"暂无数据”更换为图片？或者彻底将el-table__empty-block去除

### ISSUE THREAD

**Issue by zhoujiamin** [ElemeFE/element#1732]
### ElementUI version

1.0.6
### OS/Browers version

Chrome 54.0.2840.9
### Vue version

2.1.4
### Steps to reproduce
table组件中，无数据时，如何将"暂无数据”更换为图片？或者彻底将el-table__empty-block去除
### What is Expected?
当 empty-text=" "为空时，el-table__empty-block还是会出现，
`<el-table
    :data="userList"
    border
    stripe
    empty-text=" "
    style="width: 100%">`
### What is actually happening?
希望实现去除el-table__empty-block的效果

或者

在el-table__empty-block中，填充自己需要的图片

**Comment by Leopoldthecoder** [comment]
可能需要自己操作 DOM 去解决了。我们应该不会提供这样的功能。
