### ISSUE TITLE
[Bug Report] When binds null to el-switch, it automatically converts to false, and when the binding value is undefined, it does not change.

### ISSUE THREAD

**Issue by baooab** [ElemeFE/element#17320]
### Element UI version
2.12.0

### OS/Browsers version
Windows 10 / Chrome 76.0.3809.132（正式版本） （32 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zhangbao/pen/LYPONGq

### Steps to reproduce
直接打开 codepen 就能看见给 el-switch 绑定的 value1（初始值为 null）被修改为 false 了，但绑定的 value2（值为 undefined）没有变。

### What is Expected?
因为 undefined 的是“未定义”的意思，因此如果在 el-switch 上使用，可以修改为默认值 false。如果我绑定的是 null 值，则说明我是故意设置为空值的，无需修改成 false（类似于函数的参数默认值）。

### What is actually happening?
当绑定的值为 undefined 时不变，当绑定的值为 null 时，修改为 false。

**Comment by gotounix** [comment]
@baooab 兄弟你解决了这个问题吗？
