### ISSUE TITLE
[Bug Report] color-picker does not fit in input-append

### ISSUE THREAD

**Issue by ray007** [ElemeFE/element#17337]
### Element UI version
2.12

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ray007/pen/GRKOLXz

### Steps to reproduce
put a el-color-picker into the `append` slot of an `el-input`.

### What is Expected?
input control and color picker fitting seamlessly together

### What is actually happening?
color picker is too high and destroys the geometry

**Comment by xrkffgg** [comment]
`<el-color-picker size="small" slot="append"></el-color-picker>`

try this

**Comment by ray007** [comment]
No, this falls apart if I reduce the size of the input.
Shouldn't input and color-picker of the same size fit together?

**Comment by xrkffgg** [comment]
Oh, if this, that's will depends on the ElemeFE plan.
You can use it like that first.

**Comment by ray007** [comment]
Shouldn't this land on a todo-list instead of just closing the issue?
