### ISSUE TITLE
[Bug Report] datepicker display the wrong value

### ISSUE THREAD

**Issue by dean5277** [ElemeFE/element#17334]
### Element UI version
2.12.0

### OS/Browsers version
win7

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/deancheng/pen/YzKEgzw

### Steps to reproduce
1. set datepicker props format="yyyy-mm-dd HH:mm:ss" 

### What is Expected?
1. display the correct value

### What is actually happening?
the datepicker value display wrong

**Comment by xuelabi123** [comment]
actually it's your fault, bro.
see: format="yyyy-mm-dd HH:mm:ss", it shoud be "yyyy-**M**-dd HH:mm:ss" or "yyyy-**MM**-dd HH:mm:ss"

**Comment by dean5277** [comment]
thanks
