### ISSUE TITLE
[Feature Request] input add IP address type

### ISSUE THREAD

**Issue by xrkffgg** [ElemeFE/element#17336]
### Existing Component
是

### Component Name
Input

### Description
支持IP地址的输入。

类似于：

127.1.1.1

**Comment by tobybowers** [comment]
I've created an IP address input using Element-UI.
Just put the code up and can be found here: https://github.com/tobybowers/element-ui-ipInput
Hope this helps.

**Comment by xrkffgg** [comment]
@tobybowers THX
