### ISSUE TITLE
[Bug Report] datetime-picker can't hide empty button

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#17349]
### Element UI version
2.12.0

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Yuliang-Lee/pen/MWgrOwX?&editable=true

### Steps to reproduce
set clearable to "false"

### What is Expected?
hide "清空” button

### What is actually happening?
still show "清空“

**Comment by xrkffgg** [comment]
兄弟，你对 `clearable` 有误啊

看图：

![](https://github.com/xrkffgg/Kimg/blob/master/element/data-picker-clear.png)

同样可参照 `input`   `select` 中 对  `clearable`  的定义

**Comment by Yuliang-Lee** [comment]
> 兄弟，你对 `clearable` 理解有误啊
> 
> 看图：
> 
> ![](https://github.com/xrkffgg/Kimg/blob/master/element/data-picker-clear.png?raw=true)
> 
> 同样可参照 `input` `select` 中 对 `clearable` 的定义

我看到可以隐藏掉这个地方，那“清空”按钮怎么隐藏掉呢

**Comment by xrkffgg** [comment]
@Yuliang-Lee 看下源码
https://github.com/ElemeFE/element/blob/90c5d74fd3c18f75628fc20cae4cdbad7e1591b8/packages/date-picker/src/panel/date-range.vue#L170

这个地方的 按钮没有单个的定义，所以无法直接单独隐藏
如果你这里 没有用到其他的 el-button text 的

可以增加

.el-button--text{ display: none;}

这样就会隐藏所有的text 的 el-button 的按钮。

或者就是修改自己源码

**Comment by xrkffgg** [comment]
@Yuliang-Lee 
加上这段可以
```
.el-picker-panel {
    .el-button--text{
        display: none !important;
    }
}
```

**Comment by Yuliang-Lee** [comment]
这种方式是能解决，那为什么这个按钮不能通过属性隐藏呢

**Comment by xrkffgg** [comment]
@Yuliang-Lee 
这就要看 ElemeFE 团队的 计划了
或者你自己改源码啊，增加一个属性
