### ISSUE TITLE
[Bug Report] Slider can't set custom marker position Pt2!

### ISSUE THREAD

**Issue by jokerstudios** [ElemeFE/element#17344]
### Element UI version
2.12.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/bpqa5erm/1/

### Steps to reproduce
Since my other issue got closed, I had to open a new one, with the same issue!
I read the documentation, but there is no explanation how to overcome this issue.
Please point to a specific solution if there is one and don't just point to the slider documentation which I read excessively!

Add a el-slider.
Create computed function for marker
Set marker points as variables like this:
```
computed:{
  parameter_custom_input_marker(){
  var min = this.selected_parameter_data.min.toString();
  var max = this.selected_parameter_data.max.toString();
  var min_value= this.selected_parameter_data.min;
            var max_value= this.selected_parameter_data.max;

            return {
                min_value:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', min)
                }, 
                max_value:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', max)
                }
            }
        }
    },
```

this is not working, but if we change the function to static values like the following, it works:
```
computed:{
  parameter_custom_input_marker(){
  var min = this.selected_parameter_data.min.toString();
  var max = this.selected_parameter_data.max.toString();
  var min_value= this.selected_parameter_data.min;
            var max_value= this.selected_parameter_data.max;

            return {
                0:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', min)
                }, 
                100:{
                style: {color: '#FFFFFF'},
                label: this.$createElement('strong', max)
                }
            }
        }
    },
```

### What is Expected?
That the sliders min and max markers take the arguments from the variables min_value and max_value. See below the expected results from vue.js developertools in Chrome
marks:Object
0:Object
100:Object

### What is actually happening?
What is actually happening?
The slider interprets the values as key-names and doesnt take their values as the key-names. It doesn't show any markers!
See below the results from vue.js developertools in Chrome
marks:Object
min_value:Object
max_value:Object

**Comment by SatanEnglish** [comment]
@jokerstudios 

If you want that to work you need to:

1. Parse the min as it's actually seems to be a string.
2. Use [] around the param to make it an attribute.

```
var min_value= parseInt( this.selected_parameter_data.min);

            return {
                [min_value]:{
                style: {
              		color: '#1989FA'
            			},
            				label: this.$createElement('strong', min)
                },
            };
```

**Comment by jokerstudios** [comment]
Thank you soooo much!! It works like a charm
