### ISSUE TITLE
[Table] 希望在 row-click 的时候提供 column 信息。

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1735]
对于特别的列，并不希望他触发行的click事件

```
    el-table(
      ......
      @row-click='handleRowClick',
      @cell-click='handleCellClick')
```

```
  handleCellClick(row, column, cell, event) {
      if (column.property === 'innerRowActions') {
        console.log(column.property)
        event.stopPropagation()
      }
    }
```
这样写并没有用, `row-click`还是会触发

**Comment by kopheece** [comment]
handleCellClick(row, column, cell, event) {
      if (column.property === 'innerRowActions') {
        console.log(column.property)
        return;
      }
    }

**Comment by njleonzhang** [comment]
@kopheece 并没有什么用啊。。。。你这个写法为什么能可以呢？
没有return，函数不就是return么

**Comment by njleonzhang** [comment]
看了下实现，click是绑在tr上的，cell-click触发之后，接着触发row-click。这个就尴尬了啊、。。。
```
    handleClick(event, row) {
      const table = this.$parent;
      const cell = getCell(event);

      if (cell) {
        const column = getColumnByCell(table, cell);
        if (column) {
          table.$emit('cell-click', row, column, cell, event);
        }
      }

      this.store.commit('setCurrentRow', row);

      table.$emit('row-click', row, event);
    },
```

**Comment by furybean** [comment]
@njleonzhang 
做了个事件代理，否则要绑定的事件太多。
我在 row-click 里面把 column 也传入如何？

**Comment by njleonzhang** [comment]
@furybean 恩  把在row-click里面把 column 也传入是能解决问题的，是比现在的方案好，但是最好把这个机制解释一下，因为不看源码，是不会认为这2个事件是绑在一起的。不过是我个人看法啊。能把column传进row-click我就很满足了。现在我用一个标记实现的，比较奇怪。。。

**Comment by furybean** [comment]
@njleonzhang #1808 已添加。

**Comment by njleonzhang** [comment]
@furybean 谢谢
