### ISSUE TITLE
[Bug Report] el-table expand-row-keys not in sync

### ISSUE THREAD

**Issue by matthias-influry** [ElemeFE/element#17356]
### Element UI version
2.12.0

### OS/Browsers version
Chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/afvdghy1/1/

### Steps to reproduce
In the table, click one of the links. On click, it will add the key of the current row to the `expand-row-keys`  array. The row expands as expected.
Click again, and the key will be removed from the array. But - the row is still expanded.

Furthermore, if you use the arrow icons to expand/contract a row, it has no effect on the `expand-row-keys` array.

### What is Expected?
I would expect the array given through expand-row-keys to be the single source of truth for expanded items.
If a key is in the array, the row should be expanded. If a key is not in the array, the row should not be expanded (therefore contracted)

### What is actually happening?
By that, if you expand/contract an item via the arrow keys, I would expect the array to change values accordingly.
But using the arrow icons has no effect on the expand-row-keys array.
By adding a key to the array, I would expect the row to expand (that happens correctly).
By removing an item from the array, I would expect the row to contract (does not happen).

What I want to achieve is to have my own link in one of the columns that can expand/contract the rows.

**Comment by miltonlaufer** [comment]
Same problem here, any solution?

**Comment by caiqichang** [comment]
+1
