### ISSUE TITLE
[Feature Request] table component requests to add export excel functionality

### ISSUE THREAD

**Issue by orchie** [ElemeFE/element#17362]
### Existing Component
是

### Component Name
table

### Description
以前用iview与el对比时 感觉更棒的一点就是iview的table自带导出excel(csv)功能  
当时el没有但觉得这个功能非常常用(毕竟企业里excel是主流) 
没想到过了2年了 el还是没加这个功能 . 虽然通过其他包可以实现 但还是希望el官方能在table上实现这个特性  
感谢!

**Comment by hoythan** [comment]
不希望将 table 组件复杂化，导出功能应该由开发者自行实现。

**Comment by orchie** [comment]
> 不希望将 table 组件复杂化，导出功能应该由开发者自行实现。

好吧,感谢~
