### ISSUE TITLE
[Bug Report] The value of'el-select'changed by javascript, but the hover CSS still exists

### ISSUE THREAD

**Issue by hzmming** [ElemeFE/element#17368]
### Element UI version
2.12.0

### OS/Browsers version
Ubuntu18.04.3 LTS/Chrome76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/hzmming/pen/ZEzrRwX

### Steps to reproduce
1. select any one except the last one '北京烤鸭' within 5 seconds
2. the el-select's value will change by javascript after 5 seconds
3. active the dropdown panel, the previous hover css still exists

### What is Expected?
the dropdown item's hover css should change with v-model's value together

### What is actually happening?
the dropdown item's hover css still exists, though the value of el-select has been changed

**Comment by Linkontoask** [comment]
你可以这样，因为你的value绑定，而不是直接使用label
```javascript
setTimeout(()=>{
  app.value = '选项5'
},5000)
```

**Comment by Linkontoask** [comment]
@element-bot 它这种是使用上的问题，并不是BUG，为什么这种issues不直接关闭呢

**Comment by hzmming** [comment]
> 你可以这样，因为你的value绑定，而不是直接使用label
> 
> ```js
> setTimeout(()=>{
>   app.value = '选项5'
> },5000)
> ```

写在线demo不小心写错了．．．但还是有这问题的，第一次下拉
