### ISSUE TITLE
[Bug Report] The change event does not return the correct value when drag the Slider

### ISSUE THREAD

**Issue by 2ue** [ElemeFE/element#17371]
### Element UI version
0.1.0

### OS/Browsers version
谷歌最新版

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/2ue/pen/QWLQBGM

### Steps to reproduce
1.Drag the Slider forward the appropriate distance
2.Release the slider

### What is Expected?
when drag, the actual position of the current slider is printed, not affected by the value change

### What is actually happening?
What the value value of change returns is not the actual position of the slider, but the value in real time (at this time, the value is affected by the change of other factors, which is inconsistent with the value of the position of the slider).

**Comment by LainNetWork** [comment]
I meet the same bug,too.
另外希望可以加上滑块本身的事件回调

**Comment by mhinton** [comment]
I am using version 2.15.1 of element-ui and this bug still exists.
