### ISSUE TITLE
[Bug Report] cannot trigger @change event when using < el-date-picker />: value as display

### ISSUE THREAD

**Issue by Nekojita1** [ElemeFE/element#17386]
### Element UI version
2.11.1

### OS/Browsers version
Mac OS 10.14.6

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/v0kjp4y1/

### Steps to reproduce
选择 <el-date-picker /> 的值
检查 change 事件

### What is Expected?
应该触发 change 事件

### What is actually happening?
未触发 change 事件

**Comment by 2256184693** [comment]
![Snipaste_2019-10-08_21-30-12](https://user-images.githubusercontent.com/26702624/66399822-daa3f580-ea12-11e9-982e-70866f15fbeb.png)

把change改成input就好了。代码中emit的input事件
