### ISSUE TITLE
The node-expand method under [Feature Request] el-tree obtains the ID in the node, refreshes the page, and the ID under the same node changes.

### ISSUE THREAD

**Issue by atvarcn** [ElemeFE/element#17390]
### Existing Component
Yes

### Component Name
el-tree

### Description
谷歌

**Comment by atvarcn** [comment]
我希望通过 node-expand 获取展开节点的id，存入 loaclstorage 中，然后default-expanded-keys 数组获取 loaclstorage 数据，实现展开的记忆功能，但是每次刷新页面， 同一个node节点下的 id 值会变化，这个是什么原因？为什么会变化？怎么可以让他不变化？

**Comment by llccing** [comment]
选择唯一值时，应该用已有的数据做唯一值吧。给你个demo你看看，是不是符合你需求。

https://codepen.io/llccing/pen/JjPmRmm
