### ISSUE TITLE
[Bug Report] el-tree shows an exception to the child node in lazy loading mode

### ISSUE THREAD

**Issue by QMZhao** [ElemeFE/element#17398]
### Element UI version
2.12.0

### OS/Browsers version
window 7 Chrome 76.0.3809.100（正式版本）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/qmzhao/pen/pozLdpd

### Steps to reproduce
1. el-tree懒加载模式
2. 默认选中子节点的前两个
3. 首次懒加载执行时会把所有子节点都选中

### What is Expected?
只显示默认勾选的节点

### What is actually happening?
懒加载模式下子节点显示错误

**Comment by lizehongss** [comment]
遇到同样的问题，请问现在有好的解决方法吗

**Comment by QMZhao** [comment]
> 遇到同样的问题，请问现在有好的解决方法吗

暂时还没有解决办法，首次懒加载时就会出现这种，第二次就不会了

**Comment by caxerx** [comment]
Same issue

**Comment by LZTWilliam** [comment]
Same issue

**Comment by Sixlty** [comment]
遇到了同样的问题

**Comment by Sixlty** [comment]
遇到了同样的问题在子节点setChecked函数对父节点调用了reInitChecked的时候，**子节点还并未插入父节点中**，所以在判断第二个节点时，父节点的childNodes中只有选中的第一个节点，那么它的all就是true，

**Comment by Sixlty** [comment]
很高兴终于找到组织，一开始以为是自己使用方式不对，调试了很久，发现以下：
在子节点setChecked函数对父节点调用了reInitChecked的时候，当前的子节点还并未插入父节点中，所以在判断第二个节点时，父节点的childNodes中只有选中的第一个节点，那么父节点的all就是true，所以父节点被选中。加载完数据后回调函数判断父节点的选中状况，然后子节点通过循环将全部选中（调用setChecked），此时的setChecked做了某个判断，并不会重新调用reInitChecked，所以不会再更改父节点的选中状态。个人感觉在设计上懒加载就不是和默认选中并用的，当然可能是设计师有更深的考量而我们没有理解到，抑或是我们的使用方法不对而导致这种情况的。
目前想到的解决办法是懒加载函数中，使用nextTick手动回调setCheckedKeys选中子节点。
个人拙见。。

**Comment by yantainxin** [comment]
相同的问题，而且在异步加载树中，在nextTick中手动setCheckedKeys，选中子节点或者清除节点也有问题。例如this.$refs.tree.setCheckedKeys([]);只能清除叶子节点，父节点清除不了。这个问题什么时候能修复呢～
