### ISSUE TITLE
当table固定表头，动态设置table的改变column个数，el-table__body-wrapper高度变低

### ISSUE THREAD

**Issue by iuxw** [ElemeFE/element#17406]
Element UI version
2.12.0

OS/Browsers version
win10,chrome76.0.3809.100

Vue version
2.6.10

Reproduction Link
https://codepen.io/iuxw/pen/MWgGgGy

问题1：当table固定表头，动态改变列，表格el-table__body-wrapper高度有时变低
问题2：当table固定表头，某列fixed，动态改变列，fixed列第一行高度变高

**Comment by Crapulence** [comment]
我也遇到了这个问题
