### ISSUE TITLE
[Bug Report] When table is fixed and table's change column is set dynamically, the height of el-table__body-wrapper decreases.

### ISSUE THREAD

**Issue by iuxw** [ElemeFE/element#17407]
### Element UI version
2.12.0

### OS/Browsers version
win10 chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/iuxw/pen/YzKLKRO

### Steps to reproduce
First, by changing the dynamic column through the check box, the following problems arise:

Question 1: When the table fixes the header and changes the column dynamically, the height of the table el-table__body-wrapper sometimes decreases.

Question 2: When the table fixes the header, a column fixes, and changes the column dynamically, the height of the first row of the fixed column increases.

### What is Expected?
Change table column dynamically and keep the table height unchanged.

### What is actually happening?
Change table column dynamically and table height changes.

**Comment by BenjaminHang** [comment]
you can try to call _doLayout_ method again after render the table.
like this: 
   this.$nextTick(() => {
        this.$refs.table.doLayout();
    });

**Comment by shady-xia** [comment]
> you can try to call _doLayout_ method again after render the table.
> like this:
> this.$nextTick(() => {
> this.$refs.table.doLayout();
> });

thanks , that works
but i wonder what is the cause of this problem?
