### ISSUE TITLE
[Bug Report] Binding value in el-input component

### ISSUE THREAD

**Issue by dima-code-care** [ElemeFE/element#17418]
### Element UI version
2.12.0

### OS/Browsers version
All

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/dima-code-care/pen/PoYebmy?editors=1011

### Steps to reproduce
Bind the value of input as `:value="someProp"` instead of `v-modal`. Just try to input some text and value of the input doesn't change. You also can see the console logs.

### What is Expected?
I need `@change` event for making some custom mutation in the `Vuex`, but I can't catch the change event if I bind value like a `:value="someProp"` instead of using `v-modal`. I expect new value from the change event, but the event doesn't work at all.

### What is actually happening?
The `@change` event doesn't work with `v-bind:value=`

**Comment by wacky6** [comment]
Please handle `@input` event, or use v-model.

**Comment by athrunsun** [comment]
@wacky6 Can you explain why?
