### ISSUE TITLE
[Bug Report] Remote Select cannot be used together with Google Japanese IME tool

### ISSUE THREAD

**Issue by skmtko** [ElemeFE/element#17414]
### Element UI version
2.2.0

### OS/Browsers version
macOS - chrome

### Vue version
2.5.21

### Reproduction Link
https://jsfiddle.net/skmtko/v9rba81s/2/

### Steps to reproduce
1. install Google IME tool (https://www.google.co.jp/ime/)
2. Use Google IME tool
3. Fill in the Select input form
4. I'll be suggested Predictive completion list 
( The message “Select with tab key” is displayed below the list. )
5. click tab

screen shot at step 4
![screen shot at step 4](https://user-images.githubusercontent.com/19340693/64682444-6da54a80-d4bc-11e9-8847-3f9d5a819db8.png)

### What is Expected?
I can usually select the next predictive completion by clicking on tab key.

But change focus to next item, so and I can't fill predictive transform

### What is actually happening?
Clicking the tab key ignores the google IME prediction completion and fires the focus-out event.

Other form components ( Input, Textarea, etc. ) work as expected. This issue can only be reproduced with Select

**Comment by chileap** [comment]
I also have this problem. Anyone can help to answer with this?
