### ISSUE TITLE
[Feature Request] How to customize circle progress component's content?

### ISSUE THREAD

**Issue by aqfrstart** [ElemeFE/element#17421]
### Existing Component
Yes

### Component Name
el-progress

### Description
环形进度条，是否考虑增加slot或者其他方式用于自定义圆环中心内容。

**Comment by fudax** [comment]
<el-progress type="dashboard" :stroke-width="12" :percentage="value" :color="colors" :width="progressWidth" :show-text="false"></el-progress>
<div :style="{margin-top: -1 * (progressWidth / 2 + yourTextHeight) + 'px'}">中心内容</div>
