### ISSUE TITLE
Dialog中内嵌form表单时，打开对话框时在blur条件下触发的校验规则立即生效了？

### ISSUE THREAD

**Issue by wony-zheng** [ElemeFE/element#1742]
如题。

**Comment by perfectyang** [comment]
教你一招，在dialog主体加一个v-if="on" , on = true 或者false

**Comment by wony-zheng** [comment]
可能是对话框内嵌表单可能有bug。同样type=‘url'的设定，在独立页面的表单就可以正常检验，在对话框中一直不通过

**Comment by wony-zheng** [comment]
close掉吧，可能是我打开对话框传入的数值不对。不好意思，现在正常了
