### ISSUE TITLE
组件 el-date-picker 选择时间范围时，如果 加上picker-options，最近的相邻一天不能选择

### ISSUE THREAD

**Issue by afindo0** [ElemeFE/element#17426]
如题
<el-date-picker v-model="updateBeginTime"
                                    type="datetimerange"
                                    range-separator="至"
                                    start-placeholder="开始日期"
                                    end-placeholder="结束日期"
                                    :default-time="['00:00:00', '23:59:59']"
                                    :picker-options="pickerOptions">
我限制了选择范围，今天之后的都禁用。结果， 我选择昨天到今天，最后确定按钮就是不亮，不能确定选择。

**Comment by Yakima-Teng** [comment]
这个问题还存在的

**Comment by Yakima-Teng** [comment]
disabledDate属性中，用来比较的当前时间不要用Date.now()当前时间戳，换成当天的23点59分59秒对应的时间戳就没这个问题了。
