### ISSUE TITLE
[Feature Request] how to support WCAG base on element-ui

### ISSUE THREAD

**Issue by fangdasimon** [ElemeFE/element#17420]
### Existing Component
是

### Component Name
all components

### Description
How does element support accessibility? If you set attributes such as aria to labels inside components, you need to manipulate a lot of dom, whether such behavior is desirable in Vue

**Comment by xkem** [comment]
This issue isn't stale for me. Increasingly more companies require software to be WCAG compliant. If components don't come WCAG compliant out of the box, then we must be able to edit them in an easy enough manner to be compliant.
