### ISSUE TITLE
[Select]样式问题

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#1744]
1.0.4版本
ie 9
select下拉框出滚动条时会自动变成 屏幕宽度

![image](https://cloud.githubusercontent.com/assets/13325335/21171595/1221219e-c208-11e6-8aec-710c6826b365.png)

![image](https://cloud.githubusercontent.com/assets/13325335/21171590/07273922-c208-11e6-9618-775b521af1b9.png)

**Comment by Leopoldthecoder** [comment]
请提供在线 demo。
