### ISSUE TITLE
[Feature Request] Add save icon

### ISSUE THREAD

**Issue by lksnmnn** [ElemeFE/element#17440]
### Existing Component
Yes

### Component Name
Icons

### Description
Hi there,

I am currently building a small application using Element UI. My applictation provides the user the possibility to *save* some data onto the users computer, thus I need a fitting icon for this.

Usually the good old "floppy disc" is used as a save icon, but it is missing from the current icon set. See here for some examples: https://icons8.com/icons/set/save

Could you add it or something similar? _el-icon-save_ would be terrific :)

Cheers and thank you for your work,
L

**Comment by pootzko** [comment]
I find it that so many standard icons are missing that the next project I do in Element, I'll just use a 3rd party icon font. I'm quite liking the framework, but the icon set is pretty small.
