### ISSUE TITLE
[Feature Request] How to listen on event click on "el-card"

### ISSUE THREAD

**Issue by iliakut** [ElemeFE/element#17456]
### Existing Component
Yes

### Component Name
Card

### Description
How to listen on @click event on el-card? 
How to use @click.self.native on el-card?

**Comment by llccing** [comment]
https://codepen.io/llccing/pen/JjPmYOE?editors=1010

```
   show(arg){
      alert('click el-card'+arg)
    },
    innerClick(){
      alert('inner p click')
      
    }

  <el-card @click.native="show(2)">
    <p @click="innerClick">click.native，内部能够触发外层click，且外层自己能够监听click</p>  
  </el-card>

  <el-card @click.native.capture="show(3)">
    <p @click="innerClick">click.native.capture, 外层先捕获事件。</p>  
  </el-card>
```

**Comment by iliakut** [comment]
> https://codepen.io/llccing/pen/JjPmYOE?editors=1010
> 
> ```
>    show(arg){
>       alert('click el-card'+arg)
>     },
>     innerClick(){
>       alert('inner p click')
>       
>     }
> 
>   <el-card @click.native="show(2)">
>     <p @click="innerClick">click.native，内部能够触发外层click，且外层自己能够监听click</p>  
>   </el-card>
> 
>   <el-card @click.native.capture="show(3)">
>     <p @click="innerClick">click.native.capture, 外层先捕获事件。</p>  
>   </el-card>
> ```

@click.native.self doesn't work in example

**Comment by llccing** [comment]
https://codepen.io/llccing/pen/JjPmYOE?editors=1010

although this demo，i change the code.
because you couldn't click .el-card element，so can't emit click event.

**Comment by llccing** [comment]
> > https://codepen.io/llccing/pen/JjPmYOE?editors=1010
> > ```
> >    show(arg){
> >       alert('click el-card'+arg)
> >     },
> >     innerClick(){
> >       alert('inner p click')
> >       
> >     }
> > 
> >   <el-card @click.native="show(2)">
> >     <p @click="innerClick">click.native，内部能够触发外层click，且外层自己能够监听click</p>  
> >   </el-card>
> > 
> >   <el-card @click.native.capture="show(3)">
> >     <p @click="innerClick">click.native.capture, 外层先捕获事件。</p>  
> >   </el-card>
> > ```
> 
> @click.native.self doesn't work in example

https://codepen.io/llccing/pen/JjPmYOE?editors=1010

although this demo，i change the code.
because you couldn't click .el-card element，so can't emit click event.

**Comment by iliakut** [comment]
> > > https://codepen.io/llccing/pen/JjPmYOE?editors=1010
> > > ```
> > >    show(arg){
> > >       alert('click el-card'+arg)
> > >     },
> > >     innerClick(){
> > >       alert('inner p click')
> > >       
> > >     }
> > > 
> > >   <el-card @click.native="show(2)">
> > >     <p @click="innerClick">click.native，内部能够触发外层click，且外层自己能够监听click</p>  
> > >   </el-card>
> > > 
> > >   <el-card @click.native.capture="show(3)">
> > >     <p @click="innerClick">click.native.capture, 外层先捕获事件。</p>  
> > >   </el-card>
> > > ```
> > 
> > 
> > @click.native.self doesn't work in example
> 
> https://codepen.io/llccing/pen/JjPmYOE?editors=1010
> 
> although this demo，i change the code.
> because you couldn't click .el-card element，so can't emit click event.

can I make an event on "el-card__body" somehow? 
not on "el-card is-always-shadow"?

**Comment by llccing** [comment]
> > > > https://codepen.io/llccing/pen/JjPmYOE?editors=1010
> > > > ```
> > > >    show(arg){
> > > >       alert('click el-card'+arg)
> > > >     },
> > > >     innerClick(){
> > > >       alert('inner p click')
> > > >       
> > > >     }
> > > > 
> > > >   <el-card @click.native="show(2)">
> > > >     <p @click="innerClick">click.native，内部能够触发外层click，且外层自己能够监听click</p>  
> > > >   </el-card>
> > > > 
> > > >   <el-card @click.native.capture="show(3)">
> > > >     <p @click="innerClick">click.native.capture, 外层先捕获事件。</p>  
> > > >   </el-card>
> > > > ```
> > > 
> > > 
> > > @click.native.self doesn't work in example
> > 
> > 
> > https://codepen.io/llccing/pen/JjPmYOE?editors=1010
> > although this demo，i change the code.
> > because you couldn't click .el-card element，so can't emit click event.
> 
> can I make an event on "el-card__body" somehow?
> not on "el-card is-always-shadow"

you can change el-card__body style, insert a new div tag then add event.

[https://codepen.io/llccing/pen/LYPqBLw](https://codepen.io/llccing/pen/LYPqBLw)
