### ISSUE TITLE
menu在Vue 2.1.6下报错

### ISSUE THREAD

**Issue by wanghaolu** [ElemeFE/element#1745]
### ElementUI version

1.0.6
### OS/Browers version

windows 10 x64/chrome 55
### Vue version

2.1.6
### Steps to reproduce
1、用vue-cli建立项目
2、进入项目目录运行npm install
3、运行 npm install element-ui --save
4、在main.js中引入elementui
5、在页面中参照官方示例添加menu
6、运行npm run dev
### What is actually happening?
正常情况下应该显示menu，结果出现下图中的错误
![qq 20161214142525](https://cloud.githubusercontent.com/assets/9586655/21171805/34dfb3ca-c209-11e6-97bf-29661fb678ed.png)

**Comment by Leopoldthecoder** [comment]
同 #1706 ，等新版本解决。
