### ISSUE TITLE
[Bug Report] el-table-column still can be selected when there is no data

### ISSUE THREAD

**Issue by weibinzhu** [ElemeFE/element#17455]
### Element UI version
2.12.0

### OS/Browsers version
windows 10 / chrome 76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/qasumv8o/11/

### Steps to reproduce
鼠标移动到表头复选框，点击复选框。

### What is Expected?
鼠标手势应该变成禁用，点击复选框不应该有反应。

### What is actually happening?
虽然鼠标手势变成禁用，但是发现复选框被打上勾。

**Comment by northernCold** [comment]
https://jsfiddle.net/meishiyu/wgx3pv5s/4/
