### ISSUE TITLE
[Bug Report] Textarea's show-word-limit position in the form is abnormal

### ISSUE THREAD

**Issue by Dububao** [ElemeFE/element#17458]
### Element UI version
2.12.0

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/dububao/pen/ExYebYV

### Steps to reproduce
1.在form表单中新增一个el-form-item
2.在el-form-item中增加一个el-input 类型为textarea
3.设置maxlength="100" 和show-word-limit 属性
4.show-word-limit位置显示不正确

### What is Expected?
期待form表单中show-word-limit位置显示正确

### What is actually happening?
期待form表单中show-word-limit位置显示不正确

**Comment by Asa6** [comment]
发现同样了的问题， textarea滚动条显示不正常。有解决方法嘛？

**Comment by hqzh** [comment]
同样问题
