### ISSUE TITLE
[Bug Report] By setting the attribute height of el-table，Incorrect height of content area

### ISSUE THREAD

**Issue by weue** [ElemeFE/element#17465]
### Element UI version
2.12.0

### OS/Browsers version
Chrome/76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/weue/pen/bGbmNdb

### Steps to reproduce
By setting the attribute height of el-table, and setting the attribute v-if of the el-table-column. 

### What is Expected?
Tbody are highly consistent.

### What is actually happening?
Tbody height inconsistency.

**Comment by AAaNEIgeiDEItao** [comment]
appeared the same problem
