### ISSUE TITLE
[Bug Report] Risk to update from  2.7.2 to latest ?

### ISSUE THREAD

**Issue by Afondevi** [ElemeFE/element#17478]
### Element UI version
2.7.2

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US

### Steps to reproduce
I would like to know if I change version from 2.7.2 to latest, I need to change something in my actualy code to continue to work ?
Did you have list of changement needed ?

Thanks a lot 

### What is Expected?
upgrade and do nothing to continue my project word again perfectly :)

### What is actually happening?
Don't know ahah

**Comment by Kacxxia** [comment]
See Detail 
https://github.com/ElemeFE/element/releases
