### ISSUE TITLE
中后台，没有一个最佳实践，很难产品中应用。

### ISSUE THREAD

**Issue by dongfangx** [ElemeFE/element#1748]
最近想使用 Element 来做一个后台，
想做成跟阿里云的控制台一样。
但是Element 没有最佳实践，
我们很难拿到就能使用。

对于你们来说，这些都非常简单，不削去做。
但是对于我们这种小公司来说，没有时间和实力去折腾这块。

我们就想使用dwz,bjui这种，提供一套统一的后台，我们只需要填充数据，调用组件，完成项目。

建议：
提供一套基于 vue + element 的最佳实践，小白拿来，花半个小时看下文档。
一个基本的应用就出来了。

**Comment by dongfangx** [comment]
可以像ant-design 一样
https://ant.design/docs/spec/layout-cn

**Comment by furybean** [comment]
在计划中，本月应该能出一个版本。
在此之前，你可以参考下社区其他同学开源的这个项目：https://github.com/taylorchen709/vueAdmin

**Comment by Zhao-github** [comment]
请问下，最佳实践大概什么时候可以出来呢？

**Comment by onesez** [comment]
再问一下，最佳实践到底什么时候能出来呢？
