### ISSUE TITLE
[Bug Report] el-select clears the disabled el-option under multiple selection

### ISSUE THREAD

**Issue by tangdaohai** [ElemeFE/element#17485]
### Element UI version
2.12.0

### OS/Browsers version
chrome 任意版本

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/tangdaohai/pen/gOYBEGv

### Steps to reproduce
如demo中所展现的， 黄金糕默认被选择，在`el-option`是 `disabled` 状态，但是却可以通过输入框中的 tag 关闭 删除掉，导致无法再选中。

### What is Expected?
已经被选中并且禁用的不应该被删除掉。

### What is actually happening?
已经被选中并且被禁用的 却删除掉了。

**Comment by tangdaohai** [comment]
建议input框中可以支持 slot 功能。这样可以控制自如。
![image](https://user-images.githubusercontent.com/10151071/65226603-bc289980-daf9-11e9-9e30-c0022d56a58e.png)

**Comment by shooke** [comment]
https://www.xingjiehu.com/2019/09/25/ck0yyaq67002w62ommglxhofc/
我也遇到这个问题了，自己又做下封装。这是解决方法和代码

**Comment by zzh3319** [comment]
解决了吗

**Comment by shooke** [comment]
我用自己的方式解决了https://www.xingjiehu.com/2019/09/25/ck2zvjtz50039o3ompiy0qui1/

在 2019-11-18 15:18:56，"zzh3319" <notifications@github.com> 写道：


解决了吗

**Comment by Duo-Huang** [comment]
链接不能访问了
