### ISSUE TITLE
date-picker value格式不清晰

### ISSUE THREAD

**Issue by gugotim** [ElemeFE/element#1749]
```javascript
<el-date-picker v-model="timeRange" type="daterange" />

timeRange: ['2016-10-02', '2016-10-26']
// 或者
timeRange: [new Date('2016-10-02'), new Date('2016-10-26')]
```
都会报以下错误
```javascript
Cannot set property 'value' of undefined
set	
boundFn	
handleMouseEnterIcon
```
到底正确格式是什么？

**Comment by gugotim** [comment]
1.0.7已修复

**Comment by torresyb** [comment]
<el-date-picker
		        v-model="date"
		        type="daterange"
		        placeholder="选择日期">
		      </el-date-picker>
this.date = [new Date('2016-10-02'), new Date('2016-10-26')] （正确）

this.date = ['2016-10-02', '2016-10-26'] （报错）
