### ISSUE TITLE
Npm package `del-cli` does not seem to be compatitable with Windows

### ISSUE THREAD

**Issue by vilic** [ElemeFE/element#175]
It seems that on Windows the default shell will use its built-in `del` command anyway even if there is a `del.cmd` in path.

And for task `dist` this results in:

```text
[build entry] DONE: C:\Projects\element\src\index.js
Could Not Find C:\Projects\element\-f
C:\Projects\element\lib\*, Are you sure (Y/N)?
```

**Comment by QingWei-Li** [comment]
Any idea?

**Comment by vilic** [comment]
Seems that https://github.com/isaacs/rimraf would do the job.
