### ISSUE TITLE
[Tree]如何初始化选中状态？

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#1750]
如何获取tree选中的数据的ID和初始化tree选中状态

**Comment by qfy081** [comment]
用defaultCheckedKeys方法

**Comment by kopheece** [comment]
getCheckedNodes()和setCheckedNodes()

**Comment by yuanshengchao** [comment]
请问如何使用，可否提供一个demo，我这边一直无法正常运行 @kopheece

**Comment by yuanshengchao** [comment]
setCheckedNodes()如何进行设置，没有效果呢

**Comment by yuanshengchao** [comment]
另外请问，如何清空多选框的选择，变成不不选中状态？

**Comment by kopheece** [comment]
http://jsfiddle.net/kopheece/r7Lj912r/

**Comment by kopheece** [comment]
http://jsfiddle.net/kopheece/h2xLcLdo/

**Comment by kopheece** [comment]
上面的demo分别提供通过key和node设置tree选中；以及获取选中的key和node。

**Comment by kopheece** [comment]
http://jsfiddle.net/kopheece/n09uswxm/
这个demo里面包含了清空
