### ISSUE TITLE
[Bug Report] tablt不显示  从1.4.13升级到2.12.0版本后table显示空白

### ISSUE THREAD

**Issue by BLinyun** [ElemeFE/element#17505]
### Element UI version
2.12.0

### OS/Browsers version
win10/编译成桌面文件

### Vue version
2.6.10

### Reproduction Link
<script async src="//jsfiddle.net/2088921671/9ft6kj37/embed/html/dark/"></script>

### Steps to reproduce
从1.4.13升级到2.12.0版本后table显示空白,没有数据时table会显示:暂无数据，有数据就是直接为空白，我复制官网的table案例在项目运行，结果也是为空白

### What is Expected?
请问本地运行环境有哪些需要注意的

### What is actually happening?
请问本地运行环境有哪些需要注意的

**Comment by myaisv** [comment]
2.11.1 遇到了类似问题

**Comment by violinxsc** [comment]
这个bug我也遇到了，真的找了好久这个问题，按道理高版本的应该兼容的，不知道什么原因，希望尽快解决

**Comment by zwdgit** [comment]
遇到了同样的问题，表格头和数据都是空白

**Comment by BLinyun** [comment]
更换到2.6.3版本后又正常显示了，不知道是什么问题

**Comment by mingtaoLee** [comment]
今天升级版本也遇到这个问题，这个怎么解决？

**Comment by Qioxx** [comment]
遇到相同问题，升级到2.12.0版本后table不见了

**Comment by dingdingbai** [comment]
有同样的问题，升级到2.12.0后table显示空白

**Comment by XiaoWinter** [comment]
有同样的问题，我使用了element插件，element的版本为2.4.5

**Comment by smallerbird** [comment]
我也是，什么时候可以解决

**Comment by zervero** [comment]
我也是， 本地环境运行有问题，发布到线上是好的

**Comment by xujiyou** [comment]
2.13.0 也是这个问题，数据为空显示无数据，有一条数据就空白了，没有表头不显示数据

**Comment by charles2hang** [comment]
>鼓捣了一下，以下两种办法可能可行
#### 临时方案
清理`node_modules`，重装依赖（若`cnpm`存在问题换用`npm`），可能要换用前一两版`element-ui`

#### 可能方案
将项目的开发依赖`node-sass`、`sass-loader`分别升至`4.13.0`和`7.3.1`，可能是开发环境下解析css存在问题，可能只是误打误撞，只是一种想法

**Comment by xxxBW** [comment]
同遇到，2.8.2正常，2.8.2以上都不可用

**Comment by code-farmer-i** [comment]
vue 2.6.9，element-ui 2.12.0，表格空白。表头和表体无数据。将vue升级到2.6.11，问题解决，猜测应该是vue 2.6新增插槽语法的向下兼容问题。

**Comment by ConnorLH** [comment]
找到原因了吗？vue 2.6.10 element-ui试了很多个版本还是一样

**Comment by 37687389** [comment]
vue 2.5.17 element 2.6.3 可以使用,试了好几个版本

**Comment by Guovin** [comment]
最新版2.15.7使用dist编译打包，yarn link使用时同样存在此问题，有数据却显示空白，而采用yarn add 安装引用则可以正常显示。

**Comment by TAUnionOtto** [comment]
同样的问题。使用 2.15.3 在本地开发时没有问题，但编译后运行无法渲染 table

降级到 2.8.2 恢复正常

**Comment by WenHaoHub** [comment]
不折腾了兄弟们，用vue cli构建项目吧，别人帮我们优化的好些，不会存在这些兼容问题
