### ISSUE TITLE
[Bug Report] table-column's overflow-tooltip toggles between hide and show when text is too long

### ISSUE THREAD

**Issue by yft** [ElemeFE/element#17511]
### Element UI version
2.12.0

### OS/Browsers version
MacOS 10.14.6 / Chrome 76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yft/pen/BaBGrRY

### Steps to reproduce
1. open the url
2. mouse hovers over the last cell in the first row

### What is Expected?
Allow moue enter overflow-tooltip. When text is too long, user can set tooltip's max-height and overflow, and use mouse wheel to view all content.

### What is actually happening?
Can't show tooltip.

**Comment by deepthan** [comment]
+1

**Comment by ruyuanyuan** [comment]
+1
