### ISSUE TITLE
tabs组件部分属性失效

### ISSUE THREAD

**Issue by pk111and222** [ElemeFE/element#1751]
tabs组建的active-name 绑定值失效了呀~watch根本监听不到，值也没变，但是页面is_active元素却变了。
这个组件 的tab-click事件也在回调中返回了一个错误的tab值。其值直接给的是指向vue的this。

**Comment by Leopoldthecoder** [comment]
请给 demo

**Comment by baiyaaaaa** [comment]
1.active-name的绑定值是单向的，这个并没有什么问题
2.tab-click事件回调的参数是触发点击是件的tab的vue实例，这个返回的实例有错么？有的话麻烦给个在线复现的demo
