### ISSUE TITLE
[bug report] time range component shows bugs

### ISSUE THREAD

**Issue by ZinLiao** [ElemeFE/element#17525]
### Element UI version
2.3.*和最新版本皆能复现

### OS/Browsers version
全平台

### Vue version
0.0.0

### Reproduction Link
直接上官网随便一版本都能复现

### Steps to reproduce
例子：开始时间 08:40，结束时间：09:40
操作：
1、开始范围 “点击”选择一个大于9的时间，如13，注意，是点击，不是滚动到13；
2、结束范围无论点击还是滚动，输入框内的时间，都不会改变，只有点击确认才会改变。

### What is Expected?
上属步骤1完成后，结束范围无论点击还是滚动，输入框内的时间，能跟随操作改变显示

### What is actually happening?
上属步骤1完成后，结束范围无论点击还是滚动，输入框内的时间，都不会改变，只有点击确认才会改变

**Comment by boomler** [comment]
你这里附的链接打开啥也没有。。

**Comment by ZinLiao** [comment]
> 你这里附的链接打开啥也没有。。

直接上官网随便一版本都能复现
