### ISSUE TITLE
[Bug Report] clearable can not completely clear el-cascader`s value. And it will report error when dynamic update options, if selected V-model value is not in this new options.

### ISSUE THREAD

**Issue by nurhier** [ElemeFE/element#17526]
### Element UI version
2.12.0

### OS/Browsers version
window10/chrome 76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/25eoaznL/10/

### Steps to reproduce
1. 打开浏览器开发模式；
2. 级联下拉框选择数据；
3. 清空级联下拉框数据；
4. 再次打开级联下拉框，上次选中的数据根节点显示选中状态；
5. 切换选择下拉框选择为“选择二”，报出[Vue warn]

### What is Expected?
1. 点击级联框清空时，级联框父级选中状态一并清除；
2. 动态更新级联框的options数据时，如果已经选择的值不在新的options数组中，不要报错

### What is actually happening?
1. 清空级联框数据，父级数据依然为选中状态；
2. 动态更新级联框options数据，报错

**Comment by haoranyu** [comment]
The problem still exists in 2.13.0. 

And the PR (https://github.com/ElemeFE/element/pull/17572 ) fixed this problem gracefully.

Accept it?

@iamkun
