### ISSUE TITLE
[Feature Request] recommends that InputNumber increase maxlength, minLength

### ISSUE THREAD

**Issue by fenzaiway** [ElemeFE/element#17532]
### Existing Component
是

### Component Name
InputNumber

### Description
InputNumber  虽然有min,max限制条件，但最多输入字符没有限制，输入完截取感觉不好；
建议input组件增加keyup,keydown事件支持

**Comment by Birnen9** [comment]
非常赞同

**Comment by fenzaiway** [comment]
来信已经收到，谢谢！--by Crazy Chester
