### ISSUE TITLE
[Bug Report] `@input` event just only one character binded.

### ISSUE THREAD

**Issue by lump-igaw** [ElemeFE/element#17537]
![5](https://user-images.githubusercontent.com/45556081/65484019-21ed9a80-ded9-11e9-9445-c4ab7c6ef03a.gif)

### Element UI version
2.12.0

### OS/Browsers version
Windows 10 / Chrome 76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/overlump/pen/KKPJyJx

### Steps to reproduce
any korean or english typing to input.

### What is Expected?
`@input` event bind has well.

### What is actually happening?
`@input` event binding not working.
just only one character binded.

**Comment by yonarbel** [comment]
just add `:value="val"` to your input, and the value will be saved a concatenated with the previous one..
https://codepen.io/yonarbel/pen/MWgdZwr?editors=1111
