### ISSUE TITLE
[Feature Request] Attribute xhr-method for el-upload

### ISSUE THREAD

**Issue by abernov** [ElemeFE/element#17546]
### Existing Component
Yes

### Component Name
el-upload

### Description
I use cloud storage (for example s3.amazonaws.com) which supports only PUT-methos. Please add an attribute that allow customize
xhr.open('post', action, true) to xhr.open('put', action, true).

see file /packages/upload/src/ajax.js  line 70.

**Comment by a631807682** [comment]
use `http-request` attribute to override default xhr behavior.

**Comment by abernov** [comment]
Thanks All works fine!
