### ISSUE TITLE
[Bug Report] Radio Box, Checkbox Binding Value Problem

### ISSUE THREAD

**Issue by cangyu1993** [ElemeFE/element#17547]
### Element UI version
0.1.0

### OS/Browsers version
win10家庭版/谷歌浏览器 77.0.3865.90（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/ovd9jhs2/2/

### Steps to reproduce
赋值即可

### What is Expected?
value / v-model官方文档都说	string / number / boolean

### What is actually happening?
只是认识number类型

![image](https://user-images.githubusercontent.com/42930030/65574681-ac4d0180-dfa0-11e9-9f19-7247df7e1338.png)

![image](https://user-images.githubusercontent.com/42930030/65574711-b969f080-dfa0-11e9-94fe-904a9d60bdab.png)
![image](https://user-images.githubusercontent.com/42930030/65574745-cbe42a00-dfa0-11e9-98a1-67712c97d096.png)

**Comment by boomler** [comment]
没看出来哪里有bug
如果想用字符串的`'1'`
radioGroup那里只需要这样写就好了啊：
```
 <el-radio-group v-model="status">
          <el-radio label="1">待审核</el-radio>
          <el-radio label="2">正常</el-radio>
          <el-radio label="3">禁用</el-radio>
          <el-radio label="4">审核未通过</el-radio>
 </el-radio-group>
```

**Comment by cangyu1993** [comment]
我是直接复制的官网的demo，label只认数字类型
