### ISSUE TITLE
[Bug Report] No option to Set column size of Element-UI table without words breaking to the next line

### ISSUE THREAD

**Issue by rameezcubet** [ElemeFE/element#17556]
### Element UI version
0.1.0

### OS/Browsers version
ubuntu/chromw

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/rameezcubet/pen/QWLoMbr

### Steps to reproduce
Hi 

How do we set column size of Element-UI table without words breaking to the next line?

please check the `address` column in  https://codepen.io/rameezcubet/pen/QWLoMbr

I have `min-width="100"`, so where content is larger than 100px it should expand, but it goes to the next line.

### What is Expected?
All data in a single row without breaking text into the next line. like how intercom application handles this 

![intercom-sample](https://user-images.githubusercontent.com/41043647/65602238-2ab99b80-dfc1-11e9-9edc-bd22b29cd2fb.gif)

### What is actually happening?
I have `min-width="100"`, so where content is larger than 100px it should expand, but it goes to the next line.

**Comment by stranger26** [comment]
I did some testing and find that the min-width will work if the actual content fits in the 100% width of the table (not scrollable on the x-axis). If there are too many columns, as @rameezcubet's example, it will be wrapping the content instead.

Have not look into the code yet.
