### ISSUE TITLE
[Bug Report] Select Searchable When Opening a Dropdown List, the contents of the input box are cleared

### ISSUE THREAD

**Issue by CongAn** [ElemeFE/element#17569]
### Element UI version
2.12.0

### OS/Browsers version
Mac OS X 10_13_6/Chrome/77.0.3865.90

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/congan/pen/gOYyOKP

### Steps to reproduce
element-ui 2.12.0 版本，使用 el-select 可搜索的下拉框，在已有选择的选项时，点击选择输入框出现下拉列表

### What is Expected?
在element-ui 2.4.11版本中表现是正常的，el-select 可搜索的下拉框，在已有选择的选项时，点击选择输入框出现下拉列表时，选择输入框内的文字是当前选择的选项的文字，还能对选择输入框内的文字进行修改再次检索。
期望行为的链接：https://jsfiddle.net/anker/fusbx7cz/

实际应用：用户在修改选项时，只是想从 "AAAAAAAAA1" 的选择修改到  "AAAAAAAAA100"，此时用户点击选择输入框应该保留当前选项的文字，从而修改检索关键字获得新的列表，不需要重新输入。

### What is actually happening?
选择输入框内的文字的文字不见了

**Comment by matteokjh** [comment]
same here, when I want to make a multiple del button to del my selection of table data, I find that when I click the button and my confirm modal shows and the selection list become []. Don't know why...

**Comment by matteokjh** [comment]
My case is https://jsfiddle.net/matteokjh/092bdqg1/65/
finally I solve it by using computed：https://jsfiddle.net/matteokjh/092bdqg1/66/
Don't really know why
