### ISSUE TITLE
[Bug Report] Message Component bug

### ISSUE THREAD

**Issue by nivenice** [ElemeFE/element#17564]
### Element UI version
2.12.0

### OS/Browsers version
win10

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/nivenice/pen/pozYmQb?&editable=true

### Steps to reproduce
在Message/src/main.js中 Message.close方法里通过id寻找instances数组里message实例时 调用了instances.splice（i,1），
所以当下方获取const removedHeight = instances[index].$el.offsetHeight时，
removedHeight变量保存的实例高度不是onClose的Message的实例高度 而是onClose的实例的下一个index的实例 ，
所以当多个Message实例的高度不同时 会发生Top的值错误

### What is Expected?
...

### What is actually happening?
...

**Comment by a631807682** [comment]
PR Welcome
