### ISSUE TITLE
el-input 显示的内容没有始终与绑定的value 一致

### ISSUE THREAD

**Issue by dearbird** [ElemeFE/element#1757]
### ElementUI version

1.0.6
### Reproduction Link

https://jsfiddle.net/wynr3gce/7/

### Steps to reproduce
1. 输入大于100 的数字，input内数值正确设置，
2. 输入小于100 的数字，input内数值错误
### What is Expected?
input 内显示的内容应该始终与设定的value相同

**Comment by baiyaaaaa** [comment]
例子有什么问题？没看出来

**Comment by dearbird** [comment]
@baiyaaaaa 需要对用户数据做过滤，当输入满足条件的时候才真正写到变量中。
例子中，当输入从满足条件变为不满足条件的时候，value并没有变，但是输入框显示的值已经变掉了。
可能需要一种办法，去触发输入框刷新为实际的value

**Comment by baiyaaaaa** [comment]
不赞同，input 内显示的内容应该始终用户输入的内容相同，否则用户无法知道自己输入的是什么

**Comment by dearbird** [comment]
但是总要给个机会，能够触发这个同步吧，比如可以在提示后，恢复到原来的值。

**Comment by QingWei-Li** [comment]
你在试试，现在你的 demo 是正常运行的

**Comment by dearbird** [comment]
还是一样，试了各种情况，感觉是vue本身的行为就是这样的。

**Comment by sjk7524068** [comment]
请问这个问题现在有解决吗
