### ISSUE TITLE
[Bug Report] number type el-input cursor doesn't move to clicked location

### ISSUE THREAD

**Issue by goldengecko** [ElemeFE/element#17575]
### Element UI version
2.12.0

### OS/Browsers version
Chrome/77 (Mac and Windows), Edge Canary/78 (Mac)

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/s5cpwr0d/

### Steps to reproduce
1. Enter a number with several digits
2. Click somewhere in the middle of or at the beginning of the number

### What is Expected?
Cursor goes to the place you clicked

### What is actually happening?
It ends up to the right of where you clicked.

Notes: 
- This works as expected in Firefox.
- It also works as expected for an unstyled plain numeric text input in Chrome.
- The problem is not present in text inputs, but is there for type=number ones

**Comment by huangysss** [comment]
I fixed it by this way
```
.el-input__inner {
    text-align: right;
}
```
