### ISSUE TITLE
[Bug Report] el-select display value instead of label in remote mode

### ISSUE THREAD

**Issue by jmagnoux** [ElemeFE/element#17573]
### Element UI version
2.12.0

### OS/Browsers version
Win10/Ubuntu18.04/Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/8pd6wneo/

### Steps to reproduce
In order to reproduce the bug, you should 
1. first pick a state, any one of them 
2. after that, pick a state which contains a space such as "South Carolina"

### What is Expected?
The oldest selected values should keep the label displayed in the tag (worked like that in 2.10.0)

### What is actually happening?
The oldest selected values are displaying the value in the tag (at least since 2.11.0 and still in 2.12.0)

**Comment by zumoshi** [comment]
Duplicate of #17327
