### ISSUE TITLE
[Feature Request] switch props - width change does not take effect

### ISSUE THREAD

**Issue by xuefeng666** [ElemeFE/element#17589]
### Existing Component
Yes

### Component Name
switch

### Description
switch 属性width，无法进行双向绑定
看了下switch源码中使用 变量 `coreWidth: this.width` 接受了传递进来的 width，导致动态改变width 无法改变switch的宽度

**Comment by island205** [comment]
PR without descriptions and refer relative issues  will be closed directly.
