### ISSUE TITLE
[BUG]当datetimepicker选择了日期并清空后无法再次选择日期

### ISSUE THREAD

**Issue by Molunerfinn** [ElemeFE/element#1758]
### ElementUI version

1.0.7
### OS/Browers version

Windows/Chrome 54
### Vue version

2.1.4
### Reproduction Link

官方示例：
http://element.eleme.io/#/zh-CN/component/datetime-picker#ri-qi-he-shi-jian-fan-wei
### Steps to reproduce
在datetimepicker的日期和时间范围选择器里，当选择了某段时间，然后清空后，再次选择的时候日期范围不显示了，跟被清空了一样。
### What is Expected?
清空后再次选择日期范围应该照常显示。

**Comment by geekdada** [comment]
@baiyaaaaa 这个问题什么时候修复啊？

**Comment by hlgf** [comment]
个人建议把清空图标使用:clearable="false"进行隐藏来解决这个问题
