### ISSUE TITLE
[Bug Report] el-checkbox with on-click event will trigger the click event twice

### ISSUE THREAD

**Issue by Gaarahan** [ElemeFE/element#17583]
### Element UI version
2.12.0

### OS/Browsers version
chrome 76

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Gaarahan/pen/ZEzPZbm?editors=1111

### Steps to reproduce
1. use the simplest el-checkbox demo -> [baseUsage](https://element.eleme.cn/#/en-US/component/checkbox#basic-usage)

2. bind a native click event to the el-checkbox component ( use the native event, just like `dom.onclick`)

3. then click it

### What is Expected?
the code in the callback will be exec, just once
 - `print 'boom' once`

### What is actually happening?
we got two "boom" in the console

**Comment by Linkontoask** [comment]
这不是因为Element而引起的BUG，因为el-checkbox会生成如下的结构

```html
<label id="han" class="el-checkbox is-checked">
  <span class="el-checkbox__input is-checked">
    <span class="el-checkbox__inner"></span>
    <input type="checkbox" aria-hidden="false" class="el-checkbox__original" value="">
  </span>
  <span class="el-checkbox__label">备选项</span>
</label>
```

[在线例子](https://codepen.io/linkontoask/pen/zYOQBVL?editors=1111)
