### ISSUE TITLE
[Bug Report] el-date-picker type is week, parameter setting picker Option's first DayOfWeek is 1, can't be clicked on the first day of the current week

### ISSUE THREAD

**Issue by weizixiao** [ElemeFE/element#17598]
### Element UI version
2.7.2

### OS/Browsers version
all

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/3rmt01fy/

### Steps to reproduce
点击2019-9-30选择，不能选择

### What is Expected?
可以选择当周

### What is actually happening?
--

**Comment by chenweihuan** [comment]
遇到了同样的问题，请问有木有解决方案呀？ @weizixiao

**Comment by bestvow** [comment]
监听 change 事件
在处理函数里接受选中的 date 参数(星期二)
用 moment 或者 dayjs 或者 miment 从 date 参数获取本周开始第一天
复制给 date-picker 绑定的变量
```js
const dayjs = require("dayjs");
const weekday = require("dayjs/plugin/weekday");
dayjs.extend(weekday);
  methods: {
    weekChange(date) {
      this.week = dayjs(date)
        .weekday(1)
        .toDate();
    }
  }
```
