### ISSUE TITLE
[Bug Report] Error in `el-switch` when toggling the value causes it to be destroyed

### ISSUE THREAD

**Issue by mattheyan** [ElemeFE/element#17602]
### Element UI version
2.12.0

### OS/Browsers version
Windows 10 / Google Chrome 77.0.3865.90

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/mattheyan/pen/KKPjNwx

### Steps to reproduce
Place an "<el-switch>" inside of a conditionally rendered region (v-if) that is either directly or indirectly driven by the model value the switch is bound to (v-model), so that when the switch is toggled the switch is destroyed. When the change happens, the switch component uses nextTick to delay updating the checkbox value. However, by the time nextTick fires the component has been destroyed and the input no longer exists, resulting in "TypeError: Cannot set property 'checked' of undefined".

### What is Expected?
The error should not occur. Since the component is destroyed, it should not try to update the checkbox.

### What is actually happening?
The attempt to modify the checkbox value results in an error.

**Comment by mattheyan** [comment]
I can submit a PR for to fix this. In terms of how, I believe I've seen many places in the code base where the existence of a ref is checked before interacting with it, but these may be cases where the ref is optional. In this scenario I could also avoid the error by checking "_isDestroyed" if that would be preferred.

**Comment by lwxbr** [comment]
I had that bug too, it happens when I rerender my el-form using a key:

![image](https://user-images.githubusercontent.com/40926976/67951199-d27e4680-fbc9-11e9-80c5-e5c5231d99fd.png)

**Comment by bittermeatball** [comment]
I'm having the same problem, i wonder if the team has fixed it?
Copying the component seems not to be a great way of doing stuff, guess that'll my final option

**Comment by sonnh58** [comment]
Same problem please fix 2.15.1
