### ISSUE TITLE
el-upload是否可以自定义预览图片的宽高。。

### ISSUE THREAD

**Issue by yeluo0309** [ElemeFE/element#1760]
### Vue version

2.0

### Steps to reproduce
上传图片预览，图片的宽高为固定值。

### What is Expected?
图片预览，图片显示的宽高能否自定义。

**Comment by Leopoldthecoder** [comment]
可以自己写 CSS 覆盖。

**Comment by yeluo0309** [comment]
是的。我现在也是自己写css覆盖。
如果可以的话希望能够给参数让用户自己给值。。

**Comment by 598220654** [comment]
@yeluo0309  我上传多个图片的时候，怎么把icon的图标换成对应图片呢 
![image](https://cloud.githubusercontent.com/assets/15324717/21756058/2116aeea-d657-11e6-8040-48dfd43be3ea.png)
