### ISSUE TITLE
[Bug Report] Error in beforeDestroy hook: 'Error: [ElementForm]unpected width '

### ISSUE THREAD

**Issue by yft** [ElemeFE/element#17617]
### Element UI version
2.12.0

### OS/Browsers version
Windows_NT x64 10.0.18362 / Chrome 75.0.3770.100 64-bit

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yft/pen/rNNNjxg

### Steps to reproduce
Open the [url](https://codepen.io/yft/pen/rNNNjxg).

Possible reason:

When form is `display: none`, `getComputedStyle().width` returns `auto`.

[Why does getComputedStyle return 'auto' for pixels values right after element creation?](https://stackoverflow.com/questions/8628005/why-does-getcomputedstyle-return-auto-for-pixels-values-right-after-element-cr)

### What is Expected?
No error.

### What is actually happening?
Error when destroy.

**Comment by canyuegongzi** [comment]
我也遇到了相同的问题，form组件的label-width设置为auto时。

**Comment by chen950103** [comment]
简单临时解决。有问题的部分 v-show 换成v-if

**Comment by chen950103** [comment]
> 我也遇到了相同的问题，form组件的label-width设置为auto时。

简单临时解决。有问题的部分 v-show 换成v-if

**Comment by DengDongXia** [comment]
@chen950103 改成v-show改为v-if确实没有报错了，请问是为什么呢？原因是？

**Comment by chen950103** [comment]
@DengDongXia  楼主已经说了为什么了。 我没有仔细研究，大概的问题是 被隐藏的Dom的宽度是auto，组件被添加删除处理宽度的时候将auto强制转换成了int 产生了NaN的值。最终组件没法创建和删除。解决的办法是不使用隐藏功能，使用是否渲染组件。规避这个bug。

**Comment by DengDongXia** [comment]
好的，谢谢

**Comment by DengDongXia** [comment]
@chen950103 明白，谢谢

**Comment by ppisecky** [comment]
This needs a fix I believe. According to Sentry we had this error thrown 1000+ times and from what I can gather thanks to the Google translation of the conversation above it's probably because our forms reside in a `<transition>` which changes the display property.

**Comment by maiolica** [comment]
Same here, I've part of the form inside a <el-tab-pane> component.

**Comment by giserzhou1** [comment]
I keep reporting this error when switching back and forth between form pages while jumping multiple subpaths

**Comment by xiaoniezi** [comment]
up

**Comment by guodonglw** [comment]
label-width设为auto，可以省略不写，就可以不报错了，刚刚实践过，默认应该就是auto

**Comment by guodonglw** [comment]
> > 我也遇到了相同的问题，form组件的label-width设置为auto时。
> 
> 简单临时解决。有问题的部分 v-show 换成v-if


> > 我也遇到了相同的问题，form组件的label-width设置为auto时。
> 
> 简单临时解决。有问题的部分 v-show 换成v-if

只需要省略这个设置，去掉label-width="auto"，代码就可以运行正常，默认的效果应该就是auto

**Comment by rayroad** [comment]
> label-width设为auto，可以省略不写，就可以不报错了，刚刚实践过，默认应该就是auto
不写的话默认宽度是80px，我这边的项目需要国际化，有一个inline的表单，切换语言后lablel长度不一样，路由切换后就报错，解决方案是省略不写，然后用css hack了一下
```
.filter >>> .el-form-item__label{
  width: auto!important;
}
```

**Comment by JonasPardon** [comment]
I've been having this issue too for a while, in two projects. Both projects have transitions of the vue router, so that's basically for my entire pages.

**Comment by calali** [comment]
> label-width设为auto，可以省略不写，就可以不报错了，刚刚实践过，默认应该就是auto

有用！:label-width="item.labelWidth || 'auto'"这样写就一直告警，去掉auto，这样写:label-width="item.labelWidth"就好了！

**Comment by liumt1993** [comment]
```scss
.el-form {
  &-item {
    // hack: fix [ElementForm]unexpected width error on el-form-item destroy when label-width="auto"
    &.label-width-auto &__label {
      width: auto !important;
    }
  }
}
```
```html
<-- bad -->
<el-form-item label-width="auto"></el-form-item>

<-- good -->
<el-form-item class="label-width-auto"></el-form-item>
```

**Comment by MuxxiZzzz** [comment]
![image](https://user-images.githubusercontent.com/102722418/234449863-4aa28935-f859-4124-96e4-459a22509bf6.png)

try this

**Comment by VirgoHxy** [comment]
```
// 鸵鸟方案 在vue页面中阻止报错弹出
errorCaptured: (err, vm, info) => {
  // 阻止labelWidth:auto v-show表单 width计算错误
  if (err.message.includes('[ElementForm]unpected width')) {
    return false;
  }
}
```
