### ISSUE TITLE
[Bug Report] Problem with multiple selection table and header filter 

### ISSUE THREAD

**Issue by lucianoorsi** [ElemeFE/element#17616]
### Element UI version
2.12.0

### OS/Browsers version
Windows 10 / Chrome 77.0.3865.90 (Build oficial) (64 bits)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lucianoorsi/pen/oNNNXmX?&editable=true

### Steps to reproduce
Select items from the table and then filter with the header filter.

### What is Expected?
That can be selected and filtered at the same time without losing the selection.

### What is actually happening?
In a table with multiple selection and header filter, when it is filtered, the selection is lost.

**Comment by gfernandez-me** [comment]
+1 same here
