### ISSUE TITLE
el-tree 放在 el-dialog ref无效

### ISSUE THREAD

**Issue by hellinnocence** [ElemeFE/element#1762]
el-tree 放在 el-dialog 
this.$refs.tree 未定义

**Comment by kopheece** [comment]
我这边正好也这样用过  el-tree 放 el-dialog， 没问题

**Comment by Leopoldthecoder** [comment]
@hellinnocence Dialog 打开之后，里面的内容才会渲染，所以可以在 `open` 回调中获取：http://jsfiddle.net/leopoldthecuber/m7bved6e/
