### ISSUE TITLE
[Feater Request] The state of Switch Component could be  able to change async, If yes , it can be  table to show and change the table data state ? 

### ISSUE THREAD

**Issue by mhy-web** [ElemeFE/element#17637]
### Existing Component
是

### Component Name
switch

### Description
[Feater Request] The state of Switch Component could be  able to change async, If yes , it can be use to table to show and change the table data state ? 
switch组件是否可以支持异步，在列表中用来回显和改变数据的状态，需要异步接口修改数据，然后回显

**Comment by gzwgq222** [comment]
是不是想要 根据异步的结果来 决定是否改变 switch 的值 ？而不是一点击就改变 ？
