### ISSUE TITLE
[Feature Request] Vue3 Composition API support?

### ISSUE THREAD

**Issue by georgyfarniev** [ElemeFE/element#17634]
### Existing Component
Yes

### Component Name
All

### Description
Hello, is there any plan for migration to composition API as soon as it releases? I may participate in it.

**Comment by lynzz** [comment]
用 Composition API ，el-table-column 函数类型的属性，会不生效

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment]
Duplicate of #20375
