### ISSUE TITLE
[Feature Request] [Accessibility] Labels aren't linked to their input by default (for -> id)

### ISSUE THREAD

**Issue by nicooprat** [ElemeFE/element#17645]
### Existing Component
Yes

### Component Name
ElFormItem

### Description
Couldn't find anything related to this. We can't click on labels to focus the corresponding input. The `label` has the `for` attribute, but the `input` has no `id`. Here's a typical code found in the [docs](https://element.eleme.io/#/en-US/component/form#validation):

```html
<div class="el-form-item is-required">
	<label for="name" class="el-form-item__label" style="width: 120px;">Activity name</label>
	<div class="el-form-item__content" style="margin-left: 120px;">
		<div class="el-input">
			<input type="text" autocomplete="off" class="el-input__inner" style="background-image: url(...); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
		</div>
	</div>
</div>
```

Looks like we can force the `id` as a simple attribute:

```html
<el-input v-model="form.name" id="name"/>
```

But it should be automatic.

**Comment by cheers-hmm** [comment]
你可以在el-form-item里使用原生label和input标签

**Comment by nicooprat** [comment]
> You can use native label and input tag in el-form-item

I know, thanks. I found a way to manually pass the `id` attribute to every input I have for now: `el-input`, `el-select`, and so on accept it. I just think it could and should be automatic. 

Moreover, the `label` already automatically gets its `for` attribute from the `prop` property, as you can see in the code example above, but it's useless since inputs don't get their own corresponding `id`.

At least the docs should show the proper way to do it manually. It's pretty basic in terms of accessibility.
