### ISSUE TITLE
[feature request] El tabs add event before closed to stop tab remove

### ISSUE THREAD

**Issue by ekoz** [ElemeFE/element#17646]
### Existing Component
是

### Component Name
tabs

### Description
set el-tabs closable, cloud we add some events before closed to stop tab remove, for example, add confirm, if yes then close actived tab, else do noting.
```
        <el-tabs
          v-model="editableTabsValue"
          type="card"
          closable
          :before-close="beforeCloseTab"
          @tab-remove="handleTabRemoved"
        >
```

**Comment by cheers-hmm** [comment]
edit会在remove之前触发,可以先不用注册remove事件,等edit执行后使用自定义方法,利用双向绑定,去掉tabs的其中一个已知值

**Comment by ekoz** [comment]
@cheers-hmm thanks, it works.
