### ISSUE TITLE
select 的model 放在computed中就不能手动触发change事件了吗？

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#1765]
### ElementUI version

1.0.6
### Steps to reproduce
http://jsfiddle.net/rq04dwqv/

**Comment by spademan** [comment]
业务逻辑是支持联动，也支持手动

**Comment by Leopoldthecoder** [comment]
Vue 的机制就是这样：http://jsfiddle.net/leopoldthecuber/rq04dwqv/1/ ，这个例子使用原生 input，rank 的值也是无法改变的。
