### ISSUE TITLE
[Feature Request] Time picker select seconds

### ISSUE THREAD

**Issue by Spoowy** [ElemeFE/element#17655]
### Existing Component
Yes

### Component Name
Timepicker

### Description
How do I create a timepicker format that would allow the user to chose in a range of e.g. 500 seconds like this?

![Bildschirmfoto 2019-10-09 um 12 42 17](https://user-images.githubusercontent.com/6298122/66474956-9c4e1b00-ea92-11e9-97c8-15e47af9f52f.png)

Cheers!

**Comment by cheers-hmm** [comment]
不是很懂你说的,是现在的组件不能选择这样的时间吗

**Comment by Spoowy** [comment]
是的，完全是

还是您知道一个例子？

**Comment by cheers-hmm** [comment]
![image](https://user-images.githubusercontent.com/14694901/66557013-cdf2df00-eb83-11e9-843e-9f289f811086.png)
你应该是没有去掉那个picker-options,
