### ISSUE TITLE
[Feature Request] DatePicker type=daterange, can startDate or endDate be left open?

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [ElemeFE/element#17685]
### Existing Component
Yes

### Component Name
2.12.2

### Description
Debian / Firefox 69.02

In case you want to leave the value of startDate or endDate open, how would it be handled? Since when it is a range type to mark a value, you must select both the start date and the current date, in the picker, otherwise no value is set.

This can be used in case a report with the matching date is needed from a set date to the current date. It only works by selecting both dates as it currently does:
```['2019-01-01', '2019-10-09']```

This is not the most ideal because it forces the user to set both values, when perhaps you should only set startDate and if endDate is not set, you must understand that it is the current date, a value that could be handled maybe it would be:
```['2019-01-01', null]```

 This changes if the coincidence of the determined or minor date is needed, it could be handled as follows:
```[null, '2018-11-30']```

Is there any way to set the value when it is range by selecting only one selection date? It is only startDate or only endDate, indicating that the opposite value is empty

**Comment by EdwinBetanc0urt** [comment]
This PR is related to what I try to explain https://github.com/ElemeFE/element/issues/15474

**Comment by cheers-hmm** [comment]
你可以分开写啊,用两个日期组件

**Comment by EdwinBetanc0urt** [comment]
Greetings, @cheers-hmm there is already the date range component, handles the minDate and maxDate, it would be much more practical to keep it in a single component, also writing two different components to handle start date and end date makes you lose sense of the date range functionality.
