### ISSUE TITLE
[Feature Request] Add a parameter to set when the height of the table is too long (beyond the screen height), the horizontal line scroll bar is fixed at the bottom of the screen (or custom position), when the page scrolls to the bottom, and the scroll bar returns to the bottom of the table.

### ISSUE THREAD

**Issue by 498755303** [ElemeFE/element#17695]
### Existing Component
是

### Component Name
el-table el-scrollbar

### Description
Add a parameter to set when the height of the table is too long (beyond the screen height), the horizontal line scroll bar is fixed at the bottom of the screen (or custom position), when the page scrolls to the bottom, the scroll bar returns to the bottom of the table.

增加一个参数,用于设置当表格高度过长(超过屏幕高度)时,横线滚动条固定显示在屏幕底部(或自定义位置),当页面滚动到底部时,滚动条回归到表格底部

业务场景:当表格高度过长超过了屏幕高度,如果需要横向滚动,每次需要先滚动到页面底部,在滚动横向滚动条,然后回到原位置查看,这样会很麻烦,希望可以在没有滚动到底部的时候,将滚动条放在屏幕底部

**Comment by LinWanCen** [comment]
like the Confluence’s table, `style="position:fixed"` is better than `height` user experience.
https://element.eleme.cn/#/zh-CN/component/table#gu-ding-lie-he-biao-tou
https://element.eleme.cn/#/en-US/component/table#table-with-fixed-header

**Comment by 498755303** [comment]
This is indeed a solution, but when the page content is too long or dynamically generated, the height needs to be dynamically calculated, and double scroll bars (one page, one table) may appear, which is not very good for user experience.
![image](https://user-images.githubusercontent.com/28357943/88501860-48033000-cfff-11ea-804e-79e98ab1a5b3.png)
As shown in the picture, when it is not scrolled to the bottom, a horizontal scroll bar is displayed in the visible area to control horizontal scrolling. The simple header (custom row) is fixed, and the table body is scrolled, so that the user will see the report. More comfortable。I have added this function based on the framework here, but the performance consumption is large, I hope the official can provide built-in functions

**Comment by 498755303** [comment]
> like the Confluence’s table, `style="position:fixed"` is better than `height` user experience.
> https://element.eleme.cn/#/zh-CN/component/table#gu-ding-lie-he-biao-tou
> https://element.eleme.cn/#/en-US/component/table#table-with-fixed-header

This is indeed a solution, but when the page content is too long or dynamically generated, the height needs to be dynamically calculated, and double scroll bars (one page, one table) may appear, which is not very good for user experience.
As shown in the picture, when it is not scrolled to the bottom, a horizontal scroll bar is displayed in the visible area to control horizontal scrolling. The simple header (custom row) is fixed, and the table body is scrolled, so that the user will see the report. More comfortable。I have added this function based on the framework here, but the performance consumption is large, I hope the official can provide built-in functions
![image](https://user-images.githubusercontent.com/28357943/88502119-1b034d00-d000-11ea-983a-ab4e0a8d2220.png)
