### ISSUE TITLE
el-row在vue版本是2.1.6时无法render

### ISSUE THREAD

**Issue by 15921050052** [ElemeFE/element#1769]
### ElementUI version
1.0.2

### OS/Browers version
windows 10 /53.0.2785.116 m

### Vue version
2.1.6

### What is actually happening?

**Comment by Noemi-** [comment]
+1
我也遇到了这个问题，发现是因为vue升级以后内部一个render._h的方法变成了render._c,下降版本到2.1.4就好了

**Comment by Leopoldthecoder** [comment]
Element 升到 1.0.7 就可以。
