### ISSUE TITLE
[Bug Report] ElTable dynamically generates columns, el-table__body-wrapper height calculation error

### ISSUE THREAD

**Issue by dantingx** [ElemeFE/element#17694]
### Element UI version
2.12.0

### OS/Browsers version
macOs 10.15 / Google Chrome 77.0.3865.120（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/dantingx/pen/xxxZObj

### Steps to reproduce
1. 定义div，设定好宽度、高度（生产环境中，是使用百分比设定的）
2. div内，添加el-table标签，style中的宽度、高度使用100%
3. 列使用循环方式添加。动态生成。

### What is Expected?
el-table__body-wrapper高度应该是去除el-table__header-wrapper之后，表格区域的全部高度。滚动条在底部

### What is actually happening?
el-table__body-wrapper比期望的小，滚动条在中部。导致页面显示异常，严重影响客户体验

**Comment by dantingx** [comment]
这个bug貌似没有回复啊

**Comment by shady-xia** [comment]
我也有类似的问题，我是把el-table写在dialog里了，第一次打开dialog时，el-table__body-wrapper的高度是正确的，之后再次打开，el-table__body-wrapper的高度就会小了一点。导致我el-table__body-wrapper与el-pagination之间有空白区域

**Comment by shady-xia** [comment]
我加了doLayout() 之后可以正常工作了

**Comment by dantingx** [comment]
> 我加了doLayout() 之后可以正常工作了

这个方法有时候能解决这个问题，但是如果column动态加载，还是会出现这个问题。
我看了一下源码，它会在列加载之后计算标题行的高度（这个时候，标题行的高度会很高），同时，table内容区域高度为 总高度-标题行高度，然后，会重新调整一下标题行的高度达到正常效果，但是没有再次计算内容区域的高度。

**Comment by shady-xia** [comment]
> > 我加了doLayout() 之后可以正常工作了
> 
> 这个方法有时候能解决这个问题，但是如果column动态加载，还是会出现这个问题。
> 我看了一下源码，它会在列加载之后计算标题行的高度（这个时候，标题行的高度会很高），同时，table内容区域高度为 总高度-标题行高度，然后，会重新调整一下标题行的高度达到正常效果，但是没有再次计算内容区域的高度。

是这个问题

**Comment by xinyang3** [comment]
怎么解决这个问题？ dolayout 计算有问题

**Comment by xinyang3** [comment]
I have a answer, fixed the header_wrapper table header height, use css style, the header header height won't chang;
```
.el-table__header-wrapper {
    height 45px;
}
```
a another method, watch the data who cause the height change, and reset the header height, for example, in avue:
```
mounted () {
      this.$watch(
        () => {
          return this.$refs.crud.$refs.dialogColumn.columnIndex;
        },
        (val) => {
          if (this.$refs.crud.doLayout) {
            this.$refs.crud.$refs.table.$refs.headerWrapper.style.height = '45px';
            this.$refs.crud.$refs.table.doLayout();
          }
        }
      )
   }
```

**Comment by xiao-xiaozi** [comment]
same problem

**Comment by zhukai9527** [comment]
![企业微信截图_20240716102905](https://github.com/user-attachments/assets/c75c74d8-64a9-41bc-a9c2-e93cb74a8870)
这种只能给传固定值，才能解析出准确的高度，无法通过设置“%”，"calcl"的方式设置高度，建议条件判断加个条件支持用户传的值作为高度
