### ISSUE TITLE
[Bug Report] Cascader  scrollbar Incorrect react with filter suggetions

### ISSUE THREAD

**Issue by colinzxz** [ElemeFE/element#17706]
### Element UI version
2.12.0

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/noobxzzhang/pen/BaajgGK

### Steps to reproduce
1. type `at` to filter

### What is Expected?
The scorllbar thumb is not react in right size(lenght). 
can scroll to bottom.

### What is actually happening?
The scorllbar thumb is not react in right size(lenght)

**Comment by edum18** [comment]
same here, in my case it only scrolls to half the content
