### ISSUE TITLE
[Table]在分页情况下，多选状态如何保存？

### ISSUE THREAD

**Issue by featherfly** [ElemeFE/element#1771]
本来是用select 和 select-all事件来保存已选择数据
但是select事件中无法知道当前是选中，还是取消，无法把取消勾选的数据从已选择数据移除
select-all同样在取消选择时，完全不知道取消选择的数据时什么，只能用当前的列表数据（非正常方法）

**Comment by furybean** [comment]
提供了这个功能，reserve-selection，你可以文档上搜一下。

**Comment by yangfandashuaige** [comment]
selection-change
