### ISSUE TITLE
When the drawer opens, a scroll bar flashes.

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ElemeFE/element#17717]
### Element UI version
2.12.0

### OS/Browsers version
win10/chrome 77

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/gh-xiaoxiao/pen/jOOqYVa?&editable=true

### Steps to reproduce
点击 按钮 ，抽屉从右侧滑入

### What is Expected?
干净的出现个窗口

### What is actually happening?
浏览器底部有滚动条闪现

**Comment by plussnld** [comment]
this can be fixed by setting el-drawer__container position to fixed
