### ISSUE TITLE
[Bug Report] While table contains subtables, the highlight on each fixed row will be in a wrong display

### ISSUE THREAD

**Issue by VanJunming** [ElemeFE/element#17740]
### Element UI version
2.12.0

### OS/Browsers version
mozilla/5.0 (macintosh; intel mac os x 10_15_0) applewebkit/537.36 (khtml, like gecko) chrome/77.0.3865.120 safari/537.36

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/9grp5mfk/2/

### Steps to reproduce
1.The main table's each column includes a slot, each slot includes a subtable
2.Set some column fixed left and right
3.Mouse hover on the row, you will see the wrong highlight display on the row

### What is Expected?
The highlight will be right displayed on the row.

### What is actually happening?
The highlight will count the rows in subtable's then add to main table row's order to show.

**Comment by walirt** [comment]
19年的Bug现在还有
