### ISSUE TITLE
[bug report] action link report 503 of El upload component

### ISSUE THREAD

**Issue by Grolia** [ElemeFE/element#17744]
### Element UI version
2.12.0

### OS/Browsers version
chrome 77.0.3865.120

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/kentZhang/t3wbnos4/1/

### Steps to reproduce
用上面重现链接上传文件就可以看到报错了

### What is Expected?
让链接能上传成功

### What is actually happening?
Access to XMLHttpRequest at 'https://jsonplaceholder.typicode.com/posts/' from origin 'https://element.eleme.cn' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by csvwolf** [comment]
this is cors problem, just google it.
