### ISSUE TITLE
文件上传fileList中只显示一个文件

### ISSUE THREAD

**Issue by cench** [ElemeFE/element#1775]
需求是：文件上传的时候只允许一个，所以在上传列中只显示一条上传记录即可，上传后的记录fileList 在beforeUpload中获取不到，所以怎么控制fileList中只显示最新的一条记录？

**Comment by flyingzl** [comment]
@cench  ， 设置 :showUploadList="false" 即可。

**Comment by cench** [comment]
@flyingzl 如果不显示又感觉不大合理，beforUpload的时候试过了

      methods:{
            specialUpBefore(file){
                  this.clearFiles();
          },

报错 clearFiles : not a function，另外上传控件组合到input中 添加验证无效

**Comment by baiyaaaaa** [comment]
目前你可以通过vm.fileList（vm为upload组件实例）来对文件列表进行操作

**Comment by XZZsr** [comment]
我是change钩子的时候调用这个函数，给它的文件列表清空并赋值刚上传的
     

setLogoPath(file){
    this.fileList=[]
    let name=file.name
    let url=file.url
    let obj={
         name: name,
         url: url
   }
   this.fileList.push(obj)
    this.createData.logo=file.response.data.path
}
