### ISSUE TITLE
[Bug Report] el-table can't show-summary with height when async data

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#17763]
### Element UI version
2.12.0

### OS/Browsers version
win10 / chrome 77

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zsedcbm/pen/VwwmvRx

### Steps to reproduce
3 cases

first: 
1. table with height and show-summary and set empty array in start
2. Set a new array of values to the table
3. summary not show

second:
1. table with height and show-summary and set not empty array in start
2. Set a new array of values to the table
3. summary show success

third:
1. table show-summary and without height and set empty array in start
2. Set a new array of values to the table
3. summary show success

### What is Expected?
1. table show-summary and without height and set empty array in start
2. Set a new array of values to the table
3. summary show success

### What is actually happening?
el-table can't show-summary with height when async data

**Comment by zsedcbm** [comment]
1. 当 el-table 设置了height和show-summary时, 初始化的时候如果是空的数组, 后面设置新的数组, 表尾不会显示
2. 当 el-table 设置了height和show-summary时, 初始化的时候如果不是空的数组, 后面设置新的数组, 表尾会显示
3. 当 el-table 设置了show-summary 但是没有设置height时, 初始化的时候如果是空的数组, 后面设置新的数组, 表尾会显示

**Comment by suochencheng** [comment]
tableData: [
                 {
                     
                 }
             ],

**Comment by 0x222fe** [comment]
`<el-table show-summary :height="height" :data="data" v-show="data &&  data.length"></el-table>`
