### ISSUE TITLE
[Bug Report] “justify-content: space-between” doesn't work?

### ISSUE THREAD

**Issue by Joker-VII** [ElemeFE/element#17773]
### Element UI version
2.12.0

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/JokerVII/ywozkv0h/17/

### Steps to reproduce
code:
```
html:
<div id="app">
  <el-form>
    <el-form-item>
      <el-input placeholder="请输入验证码"></el-input>
      <el-button type="primary">获取验证码</el-button>
    </el-form-item>
  </el-form>
</div>

css:
#app {
  width: 300px;
  height: 40.8px;
  border: 1px solid #409EFF;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  .el-form {
    .el-form-item {
      /deep/ .el-form-item__content {
        display: flex;
        justify-content: space-between;
        .el-input {
          width: 165px;
        }
        .el-button {
          width: 115px;
        }
      }
    }
  }
 }
```

### What is Expected?
The el-input will be flush with the main-start edge, and the el-button will be flush with the main-end edge.

### What is actually happening?
“justify-content: space-between” works just like "space-around".

**Comment by Joker-VII** [comment]
![space-between](https://user-images.githubusercontent.com/42445388/67172740-1cf40c00-f3ef-11e9-8af6-a1af0c70a92c.jpg)

**Comment by Joker-VII** [comment]
It's caused by ".el-form-item__content::before" and ".el-form-item__content::after"

**Comment by curryz** [comment]
@Joker-VII could deep compile right?
