### ISSUE TITLE
[Bug Report] DateTime Picker component【当设置日期时间选择器格式为“yyyy-MM-dd HH:mm”时，选择此刻，获取的时间戳包含秒】

### ISSUE THREAD

**Issue by ChenxiangCat** [ElemeFE/element#17789]
### Element UI version
2.12.0

### OS/Browsers version
win10/Google Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1.设置el-date-picker属性
type="datetime"
format="yyyy-MM-dd HH:mm"
value-format="timestamp"
2.选择器选择此刻

### What is Expected?
获得没有秒的时间戳

### What is actually happening?
有秒的时间戳

**Comment by PandaTsui** [comment]
me too ,请问在type="dateTimeRange"的时候，如何调整时分秒 为  小时 + 分钟，以及如何设置step; 做了n种尝试都不能成功。
