### ISSUE TITLE
[bug report] drawer number size is not work

### ISSUE THREAD

**Issue by MoruoFrog** [ElemeFE/element#17784]
### Element UI version
2.12.0

### OS/Browsers version
windows 7

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/moruofrog/pen/KKKNLWy?&editable=true

![bug](https://user-images.githubusercontent.com/20283646/67184707-eaf6a000-f416-11e9-99a6-712977dd3a8c.png)

### Steps to reproduce
点击"点我打开按钮"

### What is Expected?
宽度为1000px

### What is actually happening?
宽度未设置

**Comment by rongxingsun** [comment]
你应该直接写size=‘1000px’，不用冒号的

**Comment by zhyafe** [comment]
文档也不改改，还number 设置px, 误导人
