### ISSUE TITLE
[bug report] v-loading abnormal performance in areas with scroll bars

### ISSUE THREAD

**Issue by zzlit** [ElemeFE/element#17796]
### Element UI version
2.12.0

### OS/Browsers version
Chrome 77.0.3865.120

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/6681/

### Steps to reproduce
打开项目地址，如果打不开可以查看看这个[issue](https://github.com/ElemeFE/element/issues/13125)，点击按钮显示loading，然后滚动可以发现下面没有被loading覆盖。

### What is Expected?
覆盖整个可滚动的区域。

### What is actually happening?
只覆盖了一部分可滚动的区域。

**Comment by Tyrone2333** [comment]
现在还有这个问题,能重新打开一下吗
