### ISSUE TITLE
[Feature Request] date-picker在type="datetimerange"时，可不可以支持使用select time 以及select time的 step功能

### ISSUE THREAD

**Issue by PandaTsui** [ElemeFE/element#17792]
### Existing Component
Yes

### Component Name
 date-picker 

### Description
在使用date-picker，type="datetimerange"时， 时分秒的选择框只能使用“任意的时间范围的时间下拉框（3选）time-picker”，可不可以支持一下“带有step的固定单选模式(time-select)”;

**Comment by WebHero0544** [comment]
是啊，为什么没有给time-picker的功能复用过来
