### ISSUE TITLE
Click twice under [bug report] IOS 13.1.3 to trigger the selected event

### ISSUE THREAD

**Issue by chcchb** [ElemeFE/element#17794]
### Element UI version
2.12.0

### OS/Browsers version
IOS 13.1.3 / 微信浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
1.苹果（IOS13.1.3）手机微信扫码，进入官网的cascader页面，找到任一例子
2.点击出现下拉内容，点击第一次么反应，点击第二次就能触发选中，并出现下一级内容

### What is Expected?
一次选中即可。

### What is actually happening?
一次选中即可。

**Comment by ZhelinCheng** [comment]
#11716

**Comment by lxy030988** [comment]
@ZhelinCheng 我加了这段代码还是无效

**Comment by storyOfBear** [comment]
@ZhelinCheng 我加这段也没效果。。。

**Comment by storyOfBear** [comment]
@lxy030988 可能是配置的位置不对，我本来是放在当前当前视图中，确实没效果，后来放在了app.vue就可以了，你试试看

**Comment by heyzxp** [comment]
好使好使！

**Comment by egerr10** [comment]
> add scss code:
> 
> ```
> .el-scrollbar {
>   > .el-scrollbar__bar {
>     opacity: 1;
>   }
> }
> ```
> 
> can resolve it.
> 
> [Bug Report] a bug with "SELECT" component - need to click twice to chose a option on safari with iOS13 #17716

thank you very much, it helped me

**Comment by Eacolt** [comment]
> @lxy030988 可能是配置的位置不对，我本来是放在当前当前视图中，确实没效果，后来放在了app.vue就可以了，你试试看

我也放到App.vue还是不行，放在哪儿都不行，你代码怎么弄的，我用的elementplus
