### ISSUE TITLE
[bug report] swich lacks the before change function

### ISSUE THREAD

**Issue by onlySparrow** [ElemeFE/element#17791]
### Element UI version
2.12.0

### OS/Browsers version
win10/chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
https://element.eleme.cn/2.3/#/zh-CN/component/switch

### What is Expected?
可以有切换前的事件

### What is actually happening?
暂无此功能

**Comment by gzwgq222** [comment]
是不是想要 根据异步的结果来 决定是否改变 switch 的值 ？而不是一点击就改变 ？
