### ISSUE TITLE
select value 为object时 怎么初始化默认项？

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#1780]
demo:http://jsfiddle.net/vcgftLvn/9/

**Comment by Leopoldthecoder** [comment]
你需要确保引用的是同一个对象：http://jsfiddle.net/leopoldthecuber/vcgftLvn/10/

**Comment by PanJiaChen** [comment]
@Leopoldthecoder 如果是远程搜索 搜索怎么保证同一个对象？

**Comment by Leopoldthecoder** [comment]
那么目前是无法做到的。因为对于一个没有存在于 options 中的 value，Select 是不知道需要把 value 的哪个字段显示出来的（所以你看到的是空白）。

如果 value 的值是字符串或数字，那么 Select 会把它本身显示出来。

**Comment by PanJiaChen** [comment]
@Leopoldthecoder 为什么不能做成像https://github.com/monterail/vue-multiselect/tree/2.0这样
其实不一定要同一对象才能初始化。
vue-multiselect 在传入value的情况下 
![image](https://cloud.githubusercontent.com/assets/8121621/21252680/cc06929c-c393-11e6-994e-f93768cbb941.png)
根据你填写的label把对应的value显示出来就好了

**Comment by van048** [comment]
2.13.2版本后，在el-select元素上加上属性value-key="key"，即可
