### ISSUE TITLE
[bug report] El input component @ change method will not be triggered when it changes, but when it loses focus.

### ISSUE THREAD

**Issue by Llixuanjin** [ElemeFE/element#17811]
### Element UI version
2.12.0

### OS/Browsers version
windos10/chrome 76.0.3809.132（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lixuanjin/pen/zYYZNOe?editors=1111

### Steps to reproduce
添加一个el-input组件
在组件中添加@change方法
修改输入框中的值，change方法没有被触发，
在输入框失去焦点时，触发了change方法

### What is Expected?
修改输入框中的值，change应该触发执行，失去焦点时change不被触发

### What is actually happening?
修改输入框中的值，change没有被触发执行，在失去焦点时触发了change方法

**Comment by gzwgq222** [comment]
### 原生 input 标签的 onchange 事件就是在失焦的时候才触发，所以 el-input change 的表现是正常的。
### 如需在输入改变时做处理，可以使用 input 事件。el-inout 有对外提供这个接口，只是文档上写。
![input](https://upload-images.jianshu.io/upload_images/6078022-b628d4de56877324.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![emit](https://upload-images.jianshu.io/upload_images/6078022-91dddc94591e1bb3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by rodrigore** [comment]
I have this same problem with  el-autocomplete

**Comment by gzwgq222** [comment]
> I have this same problem with el-autocomplete

Use input event

**Comment by rodrigore** [comment]
The value only change when I lose focus of the autocomplete. Not sure how the @input event will work, because I try to change again the value inside of @input and did'nt work.

![ScreenFlow](https://user-images.githubusercontent.com/1557305/68131615-1c359c80-fefc-11e9-97ad-3f187a7ef652.gif)
