### ISSUE TITLE
[Feature Request] Generate web-types for element-ui package for rich code assist in IDE

### ISSUE THREAD

**Issue by piotrtomiak** [ElemeFE/element#17823]
### Existing Component
No

### Component Name
Documentation - web-types

### Description
This is a feature request to include [web-types](https://github.com/JetBrains/web-types) metadata information with `element-ui` library to provide users of WebStorm (and possibly other IDEs in the future) with precise code completion, inspections and documentation for the components.

The best solution would be to generate the file based on existing documentation JSONs during the build process and ship it with the library. This solution has been implemented in `quasar` and `bootstrap-vue` libraries and is being worked on in `vuetify`.

I can work on the transformation code itself, but it would be pretty difficult for me to hook into the build process in the correct place, so I need some help from your side, before I can create a PR for this. Additionally we can generate `web-types` for older versions of library and publish them to `@web-types/` scope so that consumers of older versions of library can also benefit from better code assist.

Here is how code completion will look like with WebStorm 2019.3 and `bootstrap-vue` 2.1.0:

![web-types1](https://user-images.githubusercontent.com/4244523/67289568-1c3aa300-f4df-11e9-9521-5f4ae9f2e9e6.gif)

I think would be a really great help for developers to have such a support for your library.

**Comment by CreeTar** [comment]
still an issue, welcome to 2022

**Comment by linghengqian** [comment]
> still an issue, welcome to 2022

@CreeTar Isn't this problem solved in Element Plus?

**Comment by piotrtomiak** [comment]
For Element-UI the PR is here: https://github.com/ElemeFE/element/pull/22135.

@linghengqian For Element Plus, do you get information about available slots and directives?

**Comment by linghengqian** [comment]
@piotrtomiak 

- FYI, Element Plus Committer mentioned in https://github.com/element-plus/element-plus/issues/2891 that Element Plus generates web types directly through documentation.  

- So once Jetbrains Webstorm prompts a problem, for Element Plus it just needs to update the documentation, like https://github.com/element-plus/element-plus/issues/9492 does.
