### ISSUE TITLE
[bug report] cascade selector children option shown wrong

### ISSUE THREAD

**Issue by mhy-web** [ElemeFE/element#17826]
### Element UI version
2.10.1

### OS/Browsers version
mac os 10.14.5/chrome  77.0.3865.120

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/pen/?editors=1010

### Steps to reproduce
The third option no submenu, when I hover from the second option to the third, the submenu of the second has not disappeared
设置触发方式为hover, 部分数据没有二级菜单时，二级菜单显示的数据是上一个菜单的数据

### What is Expected?
实时显示菜单数据，二级菜单没有数据时显示为空

### What is actually happening?
二级菜单没有数据时，显示的是前一个菜单的数据

**Comment by agreadname** [comment]
https://codepen.io/agreadname/pen/mddOYjr
