### ISSUE TITLE
[Bug Report] el-transfer in el-form-item has incorrect line-height

### ISSUE THREAD

**Issue by MisicDemone** [ElemeFE/element#17835]
### Element UI version
2.12.0

### OS/Browsers version
chrome v77.0.3865.90

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/misic/pen/jOOmEeO?&editable=true

### Steps to reproduce
Put el-transform into el-form-item.

### What is Expected?
Get correct line-height (30px).

### What is actually happening?
Got incorrect line-height from class ".el-form-item__content" (40px).

**Comment by lvhua6352** [comment]
I got the same bug after I upgraded element-ui from 2.9.1 to 2.12.0.

**Comment by sbyps** [comment]
+1
