### ISSUE TITLE
[Bug Report] when the select option is disabled, the selected tag shouldn not have delete operation.

### ISSUE THREAD

**Issue by yimiZSK** [ElemeFE/element#17849]
### Element UI version
2.12.0

### OS/Browsers version
macOS / Chrome/77.0.3865.120

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/51fotjsp/4/

### Steps to reproduce
1、click the drop down box
2、you can't operate 1 and 5 because they are disabled
3、however, you can directly manipulate the selected tag to remove the disabled option.

### What is Expected?
the selected(disabled) tag shouldn not have delete operation.

### What is actually happening?
the selected(disabled) tag have  delete operation.

**Comment by thamibn** [comment]
How did you solve the above i am stuck?

it was gonna be better to be able to disable selected items not onlu the on the list.

**Comment by wxGoldking** [comment]
it was solved in element-plus, but it still was wrong in element. You may use vue's mixins fix it

**Comment by thamibn** [comment]
> it was solved in element-plus, but it still was wrong in element. You may use vue's mixins fix it

Thanks I am using element plus now all good.

**Comment by Half-A-Turnip** [comment]
> How did you solve the above i am stuck?
> 
> it was gonna be better to be able to disable selected items not onlu the on the list.

yes，i use vue's mixins fix it
