### ISSUE TITLE
The tree component of [bug report] has an error in selecting the parent node after filtering.

### ISSUE THREAD

**Issue by luxueyan** [ElemeFE/element#17857]
### Element UI version
2.12.0

### OS/Browsers version
和系统浏览器无关

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xueyan/pen/ZEEKVBg?&editable=true

### Steps to reproduce
tree组件，通过filter函数过滤节点后，选择父节点，调用getCheckedNodes后获取的节点 包含隐藏的节点

### What is Expected?
不应该包含隐藏的节点

### What is actually happening?
包含了隐藏的节点

**Comment by chenhangbin2008** [comment]
@luxueyan 我也遇到了一样的问题，请问你解决了吗？

**Comment by luxueyan** [comment]
可以自己过滤数据，重新渲染树，不过element的树组件性能太低了，上千上万就扛不住了，计划换其他组件或者自己写了
