### ISSUE TITLE
[bug report] official website update log description copy error

### ISSUE THREAD

**Issue by renlixin** [ElemeFE/element#17867]
### Element UI version
2.12.0

### OS/Browsers version
macOs10.14.6 / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
打开官网，点击更新日志，找到 Input 更新文案，第二行：
触发清楚按钮的点击事件 (#16576 by @a631807682)，此处应为清除

### What is Expected?
将描述文案改为清除

### What is actually happening?
不影响行为。

**Comment by a631807682** [comment]
链接是空的更新一下

**Comment by renlixin** [comment]
连接是什么都没有，主要是因为这是官网描述文案的错误，并不是因为代码有误，所以连接里面没有什么可以填的

**Comment by a631807682** [comment]
好的，明白了，`changelog`有错别字是吧，方便的话提个`PR`修复一下。

**Comment by renlixin** [comment]
OK👌

**Comment by gzwgq222** [comment]
> 好的，明白了，`changelog`有错别字是吧，方便的话提个`PR`修复一下。



> 链接是空的更新一下

Travis CI 失败后没有「Restart Build」按钮，导致无法重新触发 CI。贡献文档上说有 「Restart Build」按钮 按钮的。

**Comment by a631807682** [comment]
> > 好的，明白了，`changelog`有错别字是吧，方便的话提个`PR`修复一下。
> 
> > 链接是空的更新一下
> 
> Travis CI 失败后没有「Restart Build」按钮，导致无法重新触发 CI。贡献文档上说有 「Restart Build」按钮。

哪个commit？ `travis ci` 的管理页面上是有按钮的，如果没有你可以`rebase`一下再提交。

**Comment by gzwgq222** [comment]
[commit link](https://travis-ci.org/ElemeFE/element/builds/603164032?utm_source=github_status&utm_medium=notification)
 CI fail 后找了半天没找到，最后只能用重新 commit 的方式触发 CI 了。
「Restart Build」 是不是没开放出来 ？

**Comment by gzwgq222** [comment]
> > > 好的，明白了，`changelog`有错别字是吧，方便的话提个`PR`修复一下。
> > 
> > 
> > > 链接是空的更新一下
> > 
> > 
> > Travis CI 失败后没有「Restart Build」按钮，导致无法重新触发 CI。贡献文档上说有 「Restart Build」按钮。
> 
> 哪个commit？ `travis ci` 的管理页面上是有按钮的，如果没有你可以`rebase`一下再提交。

[commit link](https://travis-ci.org/ElemeFE/element/builds/603164032?utm_source=github_status&utm_medium=notification)
 CI fail 后找了半天没找到，最后只能用重新 commit 的方式触发 CI 了。
「Restart Build」 是不是没开放出来 ？

**Comment by a631807682** [comment]
@gzwgq222 确实没有，但是我不是这个项目的维护团队成员，所以我也没有权限。这项目不知道因为什么原因，或者有什么计划，已经一个多月没人维护（或者执行某些计划），在这个项目重新活跃之前，我不打算再贡献代码，只是刚好这个issue与我某个commit有关所以来看看，因此你可能需要联系这项目的维护团队。

**Comment by gzwgq222** [comment]
@a631807682 我看到你有 Contributor 这个 title 以为你们有个什么群什么的可以反馈下这个问题，pr 反馈太慢了。我也是最近才开始给这个仓库提 pr ，九百多 issues，两百多 pr，看来是有段时间没关这个了。看了下发版时间，大概一两个月更新一次吧。

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/
