### ISSUE TITLE
[Bug Report] el-tree update default-checked-keys but view don't change properly

### ISSUE THREAD

**Issue by Caaalabash** [ElemeFE/element#17864]
### Element UI version
2.12.0

### OS/Browsers version
macos10.14.6  / chrome78

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/caaalabash/pen/gOORKWZ?editors=1111

### Steps to reproduce
1. init data: default-checked-keys = [8]
2. try to update: default-checked-keys = []   or default-checked-keys = [1,2,3]
3. view don't change properly,  key 8 still be checked

### What is Expected?
update default-checked-keys, only the newValue should be checked

````
    data: () => ({
     defaultCheckedKeys: [8]
    }),
    methods: {
      change() {
        console.log(this.$refs['tree'].getCheckedKeys()) // [8]
        this.defaultCheckedKeys = []
        this.$nextTick(() => {
          console.log(this.$refs['tree'].getCheckedKeys()) // [8]
        })
      },
    },
````

### What is actually happening?
oldValue still be checked

**Comment by nile52** [comment]
you should use `setCheckedNodes` to set certain nodes to be checked.
```
        this.$refs.tree.setCheckedNodes([5, 9]);

```

**Comment by Caaalabash** [comment]
@nile52 you are right
