### ISSUE TITLE
How can the [feature request] tree form be expanded and folded dynamically through JavaScript?

### ISSUE THREAD

**Issue by MikuBlog** [ElemeFE/element#17877]
### Existing Component
是

### Component Name
el-table

### Description
希望能够添加方法动态展开与折叠树形表格

**Comment by MikuBlog** [comment]
Now, I can only use V-IF to force the refresh of subcomponents to dynamically expand and collapse the tree list.

**Comment by moabtools** [comment]
How to use V-IF for that?

**Comment by MikuBlog** [comment]
@moabtools 

Define a reactive property, such as isExpanded.

Then force the table to render
```
this.isExpanded = false
this.$nextTick(() => this.isExpanded = true)
```
