### ISSUE TITLE
[Select]multiple情况下更改options数组，显示了 value 而不是label

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1788]
>select组件，在multiple情况下, 更改options数组， 显示了value, 而不是label

[demo](http://jsfiddle.net/ivan403704409/58hdx40c/2/)

**Comment by ivan403704409** [comment]
@Leopoldthecoder  
还是有问题
[demo](http://jsfiddle.net/ivan403704409/xLe58gr7/1/)

**Comment by Leopoldthecoder** [comment]
需要加 `key`：http://jsfiddle.net/xLe58gr7/2/
原因：https://github.com/ElemeFE/element/issues/576
