### ISSUE TITLE
Has [bug report] stopped maintenance?

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#17897]
### Element UI version
2.12.0

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/changes0115/pen/JjjrNeJ

### Steps to reproduce
停止维护了吗？停止维护了吗？停止维护了吗？

### What is Expected?
停止维护了吗？停止维护了吗？

### What is actually happening?
停止维护了吗？停止维护了吗？停止维护了吗？

**Comment by zazzaz** [comment]
YES! 🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉

element-plus/element-plus#147

**Comment by zhouzhongyuan** [comment]
Still under maintenance.
