### ISSUE TITLE
The problem of [bug report] El input under the render function

### ISSUE THREAD

**Issue by rayfalling** [ElemeFE/element#17895]
### Element UI version
2.12.0

### OS/Browsers version
所有/chrome78

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/r14hy5v7/2/

### Steps to reproduce
打开messagebox，输入文字

### What is Expected?
messagebox正常显示输入

### What is actually happening?
输入为空

**Comment by webyangpei** [comment]
遇到了同样的问题

**Comment by webyangpei** [comment]
@wanghaiwei 把messgae的render函数组件 封装成单文件组件，然后引入使。 比如这样 message: h('EnInput，{}).
