### ISSUE TITLE
input输入框maxlength问题

### ISSUE THREAD

**Issue by Plortinus** [ElemeFE/element#179]
### ElementUI version
1.0.0-rc.4

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.0-rc.8

```
<el-form class="login" ref="form" :model="form" label-width="80px" @submit.prevent="onSubmit">
    <el-form-item label="账号">
      <el-input placeholder="请输入手机号码" v-model="form.phone" type="tel" maxlength="11"></el-input>
    </el-form-item>
 </el-form>
```

console里报错:
`[Vue warn]: Invalid prop: type check failed for prop "maxlength". Expected Number, got String. (found in component <ElInput>)`

**Comment by QingWei-Li** [comment]
只接受 Number 类型
```html
<el-input :maxlength="11"></el-input>
```

**Comment by Plortinus** [comment]
`:`这个语法在哪里可以找到参考?

**Comment by QingWei-Li** [comment]
http://rc.vuejs.org/guide/syntax.html#v-bind-Shorthand

**Comment by Plortinus** [comment]
thanks
