### ISSUE TITLE
完美解决万级数据渲染卡顿问题 Perfect solution to the problem of 10000 level data rendering

### ISSUE THREAD

**Issue by livelyPeng** [ElemeFE/element#17905]
### Existing Component
是

### Component Name
table

### Description
https://github.com/livelyPeng/pl-table：

完美解决万级数据渲染卡顿问题
Perfect solution to the problem of 10000 level data rendering

The front-end UI framework uses the element UI, and the project requires at least 1000 pieces of data for a table without paging. At this time, clicking on other DOM operations will cause a jam. If you click the check box

**Comment by 6caiyu6** [comment]
怎么解决的呀？

**Comment by 6caiyu6** [comment]
链接地址打不开诶

**Comment by livelyPeng** [comment]
@6caiyu6 很明显吧https://github.com/livelyPeng/pl-table     吧那个：干掉啊

**Comment by livelyPeng** [comment]
https://github.com/livelyPeng/pl-table




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "6caiyu6"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 下午4:16
收件人: "ElemeFE/element"<element@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ElemeFE/element] 完美解决万级数据渲染卡顿问题 Perfect solution to the problem of 10000 level data rendering (#17905)




链接地址打不开诶
