### ISSUE TITLE
[Bug Report] Use <component :id="'el-radio-group'"> causes exception

### ISSUE THREAD

**Issue by StephenPCG** [ElemeFE/element#17908]
### Element UI version
2.12.0

### OS/Browsers version
macOS 10.15 / Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/stephenpcg/pen/Baawrye

### Steps to reproduce
Open the reproduction link, and open browser developer console.

### What is Expected?
There is no error in developer console.

### What is actually happening?
Error in console:
```
[Vue warn]: Unknown custom element: <component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <ElRadioGroup> at packages/radio/src/radio-group.vue
       <Root>
```

Although it seems everything is still working fine, this exception is annoying.

A little more about why I am using dynamic component in this case, I'm reassembling a component that fetches data via API and render checkbox group or radio group depending on API response data. I found that el-checkbox-group works fine, only el-radio-group throws such exception.

**Comment by ch957869975** [comment]
same situation for me

**Comment by FrostCamelot** [comment]
+1

**Comment by zhouyuan1990** [comment]
+1

**Comment by CongAn** [comment]
+1

**Comment by binBBB** [comment]
+1
