### ISSUE TITLE
[bug report] date picker

### ISSUE THREAD

**Issue by wangshanbo** [ElemeFE/element#17904]
### Element UI version
2.7.0

### OS/Browsers version
所有

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/wangshanbo/18sgky6v/

### Steps to reproduce
el-date-picker组件type选择datetimerange，直接选择时分秒滚动小时，有概率会触发开始时间和结束时间的联动，例如开始时间选择23:00:00结束时间也会变成23:00:00，element2.7.0>2.12.0都会出现这种问题

### What is Expected?
选择开始时间或者结束时间两者应该独立进行时间选择

### What is actually happening?
开始时间和结束时间会出现联动的情况

**Comment by Shhuy** [comment]
Element UI version
2.15.4

OS/Browsers version
所有

Vue version
2.15.4

Reproduction Link
https://element.eleme.cn/#/zh-CN/component/datetime-picker

Steps to reproduce
el-date-picker组件type选择datetimerange，日期选择同一天，选择时分秒滚动小时，有概率会触发开始时间和结束时间的联动

What is Expected?
选择开始时间或者结束时间两者应该独立进行时间选择

What is actually happening?
开始时间和结束时间会出现联动的情况
