### ISSUE TITLE
[Form]提示_this.fields.push is not a function

### ISSUE THREAD

**Issue by stanNo1** [ElemeFE/element#1790]
添加 prop 属性，进行表单验证，提示
element-ui.common.js?27fd:14926Uncaught TypeError: _this.fields.push is not a function
版本：
vue 2.1.6
element 1.0.7

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by stanNo1** [comment]
问题找到了
之前引入第三方（vee-validate）表单验证组件，与element表单验证应该是有冲突
去除vee-validate就没有此问题了
