### ISSUE TITLE
bug: DateTimePicker组件， 当时type是datetimerange时，清空日期后，再选中日期， 然后按确定，显示错误， 清空了value

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#1791]
>DateTimePicker组件， 当时type是datetimerange时，清空日期后，再选中日期， 然后按确定，显示错误， 清空了value
[demo](http://jsfiddle.net/ivan403704409/0jg1d6c7/)

**Comment by szutzy** [comment]
点击确定日期面板业不会消失

**Comment by Leopoldthecoder** [comment]
Fixed in #1766
