### ISSUE TITLE
[Bug Report] cell-mouse-enter and cell-mouse-leave is not valid in summary row

### ISSUE THREAD

**Issue by JingGeGe77** [ElemeFE/element#17919]
### Element UI version
2.12.0

### OS/Browsers version
win 10 pro / Google Chrome 77.0.3865.120 (64bits)

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/jinggege77/pen/yLLPJwb

### Steps to reproduce
It will not  trigger the cell-mouse-enter event  when mouse hover the cell of summary row

### What is Expected?
It can work well in summary row

### What is actually happening?
It can work well in summary row

**Comment by xrkffgg** [comment]
鼠标放到标题的时候，也不触发的

这几个方法应该都只是 对应 table 的 body  

对 header 和 footer 都不起作用

**Comment by xrkffgg** [comment]
@JingGeGe77 看了下源码。

body 是在 td 加上了 on-mouseenter={ ($event) => this.handleCellMouseEnter($event, row) } 用来监控

你可以在 footer 的 td 上 也加上 类似的方法 来监控了

大概率，饿了么团队 不会在 footer 加监控的
