### ISSUE TITLE
[Bug Report] Table with fixed column If you change the width and height of the scrollbar, it will cause problems

### ISSUE THREAD

**Issue by Flying-web** [ElemeFE/element#17917]
### Element UI version
2.12.0

### OS/Browsers version
Mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/crazycity/pen/MWWOaqm?&editable=true

### Steps to reproduce
1. Change scrollbar style  and the height and width are not equal
```
/*scrollbar style*/
div::-webkit-scrollbar,html::-webkit-scrollbar {
  width: 6px;
  height: 18px;
}
```
2. el-table-column has fixed attributes

### What is Expected?
The height of the fixed column is correct

### What is actually happening?
Fixed column is higher than table

**Comment by LittleHChen** [comment]
the same as you

**Comment by LittleHChen** [comment]
may use doLayout  to solve

**Comment by Flying-web** [comment]
@LittleHChen maybe it's better this way: 
`div.el-scrollbar__wrap::-webkit-scrollbar{
  width: 18px;
  height: 18px;
}`
