### ISSUE TITLE
Can the [feature request] El menu component add properties to set the indentation distance?

### ISSUE THREAD

**Issue by bigStuart** [ElemeFE/element#17927]
### Existing Component
Yes

### Component Name
el-menu

### Description
我想修改现在的缩进距离、现在默认20px，可以新增加个属性来自定义设置这个缩进距离吗？

**Comment by xrkffgg** [comment]
顶栏横向2个菜单之间距离，可以修改这个。
```
.el-menu-item {
    padding: 0 20px;
}
```

顶栏点开后纵向2个子菜单距离可以修改这个

```
.el-menu--horizontal .el-menu .el-menu-item, .el-menu--horizontal .el-menu .el-submenu__title {
    padding: 0 10px;
}
```

侧栏2个菜单距离可以修改

```
.el-menu-item {
    height: 56px;
    line-height: 56px;
}
```

以上数值均为默认 CSS

**Comment by bigStuart** [comment]
这样修改在有多个层级时会造成不同层级会并排在一起了、因为这个值本来是动态根据不同层级设置不同值的，如果单纯改css好难实现的。如：我有三个层级、第一层是20、第二层是40、第三层是60这样的
