### ISSUE TITLE
[Feature Request] Dialog close event change to mousedown

### ISSUE THREAD

**Issue by bum-hyun** [ElemeFE/element#17920]
### Existing Component
Yes

### Component Name
dialog

### Description
dialog close event change to mousedown.
A click event is uncomfortable when the mouse accidentally leaves the dialog.

**Comment by xrkffgg** [comment]
You can try this `close-on-click-modal` attribute

**Comment by bum-hyun** [comment]
> You can try this `close-on-click-modal` attribute

I think a modal should have a close function when click a wrapper.
but, that attribute just blocks close function.
