### ISSUE TITLE
Table 能支持 colsSpan 和 rowSpan 单元格合并吗？在数据当中

### ISSUE THREAD

**Issue by forget-chuckie** [ElemeFE/element#1792]
看新版的 table 已经实现了多表头的的功能 ，能不能在数据当中出实现 合并单元格的功能 呢，类似于 jquery-easyui 中的datagird 中的 colspan 和 rowspan? 看官网的 formatter 方法里有 colspan 和 rowspan这两个属性但是设置了之后不生效

**Comment by Leopoldthecoder** [comment]
Duplicate of #670

**Comment by penghongsun** [comment]
希望能支持colsSpan和rowSpan
