### ISSUE TITLE
After the cell is hidden in more than one row in the [bug report] table, set the fixed property. The height of the fixed column is the height before the cell is hidden.

### ISSUE THREAD

**Issue by caihai123** [ElemeFE/element#17957]
### Element UI version
2.12.0

### OS/Browsers version
Chrome 77

### Vue version
2.6.10

### Reproduction Link
https://github.com/caihai123/element-bug/

### Steps to reproduce
在表格中写入大量的文本，css设置为超过多行隐藏，再设置任意一列的fixed属性

### What is Expected?
希望被固定列对应的单元格与当前行的高度一致

### What is actually happening?
实际不一致啊，还是我不能这样操作。

**Comment by wanwan1219** [comment]
The same as you.
