### ISSUE TITLE
[feature request] select when remote search multi select, select some options, change the search criteria, and the previously selected option will become value instead of label

### ISSUE THREAD

**Issue by zhangOking** [ElemeFE/element#17951]
### Existing Component
Yes

### Component Name
2.12.0

### Description
select远程搜索   多选    选中一些选项之后， 更换搜索条件（将会重新遍历options，导致当前选中的选项没有对应的option，所以显示的是value而不是label），这里我做了一些缓存，但是依然有一些问题filterable无法正确的过滤数据，如果我在1000条数据中选中了100条数据，options将会过多，无法第一时间找到我想要的选项

**Comment by zumoshi** [comment]
Duplicate of #17327
