### ISSUE TITLE
请教一下，我的引入方式是否有问题，或者能够直接提供一个，不需要重命名的（不是整个引入的）

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#1795]
import {
	  RadioGroup as ElRadioGroup,
	  RadioButton as ElRadioButton,
	  Form as ElForm,
	  FormItem as ElFormItem,
	  InputNumber as ElInputNumber
	} from 'element-ui'	
每次都需要重命名一下，比较麻烦

**Comment by Leopoldthecoder** [comment]
参照文档的快速上手一节：
```javascript
import { Button, Select } from 'element-ui'

Vue.component(Button.name, Button)
Vue.component(Select.name, Select)
```
