### ISSUE TITLE
There is a problem with show header in the [bug report] table component

### ISSUE THREAD

**Issue by uxo2** [ElemeFE/element#17964]
### Element UI version
2.12.0

### OS/Browsers version
大多数高级版本的浏览器, IE同样效果

### Vue version
2.6.10

### Reproduction Link

https://codepen.io/ziyoung/pen/rRKYpd?editors=1111

### Steps to reproduce

只要在el-table中设置`:show-header="false"`就会出现`querySelector is undefined`的问题

### What is Expected?
no warning, no error

### What is actually happening?

 尝试在其他版本设置依然出现问题.最后重新安装版本依赖,依然出现问题.

**Comment by wond-z** [comment]
遇到类似的问题，我的单独给table设置height是正常的，单独设置show-header也是正常的，当heigh和show-header两个属性同时存在会报querySelector is undefined错误。。。最后使用header-row-style规避解决
