### ISSUE TITLE
[bug report] El pagination uses slot style to affect the style of content in it

### ISSUE THREAD

**Issue by xushuailing** [ElemeFE/element#17968]
### Element UI version
2.12.0

### OS/Browsers version
mac

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/xslmenghuan/Ltn0j9xr/1/

### Steps to reproduce
使用卡槽样式影响里面的样式

### What is Expected?
不影响里面的样式

### What is actually happening?
影响里面的样式

**Comment by kouchao** [comment]
#17971
