### ISSUE TITLE
[Bug Report] el-image perview bug

### ISSUE THREAD

**Issue by uncleLian** [ElemeFE/element#17962]
### Element UI version
2.12.0

### OS/Browsers version
mac chorme 87

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/unclelian/pen/QWWQerN

### Steps to reproduce
1、Click the picture in the table to preview

Causes of bugs: el-table-column use fixed

### What is Expected?
Preview layer is not covered

other: 
1、mask can click to close perview
2、el-image-viewer append to body

### What is actually happening?
Preview layer is covered

other:
1、mask can't click
2、el-image-viewer is in the component

**Comment by csvwolf** [comment]
you can use:

```
.el-table__fixed {
  z-index: 1000;
}
```

to work around now, in the future maybe the feature will be supported
