### ISSUE TITLE
elementUI如何获取el-dialog实例，从而调用close和open方法

### ISSUE THREAD

**Issue by caoqiqi** [ElemeFE/element#1796]

**Comment by Leopoldthecoder** [comment]
请参考 Vue 文档中 `ref` 的[相关内容](https://vuejs.org/v2/api/#ref)

```html
<el-dialog ref="dialog">
...
</el-dialog>
```

```javascript
this.$refs.dialog.open()
```

**Comment by user20161119** [comment]
@Leopoldthecoder 这个貌似还是拿不到dialog实例，请看截图
![image](https://cloud.githubusercontent.com/assets/123967/22970464/3ae440c6-f3ad-11e6-9f7b-3914d0d8170d.png)

**Comment by Leopoldthecoder** [comment]
@user20161119 给 demo

**Comment by user20161119** [comment]
@Leopoldthecoder 谢谢，可以了
