### ISSUE TITLE
el-select 未设置multiple，在输入中文时不能动态回调remote-method

### ISSUE THREAD

**Issue by sqchuan911** [ElemeFE/element#17974]
Element UI version
最新版本以及以前版本

Browsers version
chrome V78.0.3904.87

重现步骤
设置el-select远程搜索功能->去掉多选multiple->切换中文输入法->输入中文->不使用回车选中中文
remote-method回调不执行

期望
可以同设置multiple时有相同的回调

**Comment by dachiyu** [comment]
想问这个问题解决了嘛？遇到了同样的问题，输入”深圳市世“，”世‘不触发remote-method

**Comment by jsoneP** [comment]
我现在 遇到 中文输入法（搜狗）下，比如输入s（此时停留在s的中文选择上），停顿1秒按回车，此时输入框内展示的是英文s，但是此时不会 触发remote-method，不知道为什么，但是如果在英文状态下输入s会立马执行remote-method

**Comment by 12345ZMTHL** [comment]
老哥，你解决了嘛？目前我也是遇到这类问题，使用的是win10自带的中文输入法，输入中文，使用空格可以触发，但是如果是选择输入法中的第二个中文，就不会触发，后续再使用回车键又能触发了

**Comment by jsoneP** [comment]
没解决- -，反正好像原生的select就存在这个问题，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 下午2:37
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"某某"<1355039491@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)





 
老哥，你解决了嘛？目前我也是遇到这类问题，使用的是win10自带的中文输入法，输入中文，使用空格可以触发，但是如果是选择输入法中的第二个中文，就不会触发，后续再使用回车键又能触发了

**Comment by 12345ZMTHL** [comment]
这就难受了呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 下午2:41
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"12345芝麻糖葫芦"<1933275033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)





 没解决- -，反正好像原生的select就存在这个问题， 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月14日(星期一) 下午2:37 
 收件人:&amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"某某"<1355039491@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974) 
 
 
 
 
 
   
 老哥，你解决了嘛？目前我也是遇到这类问题，使用的是win10自带的中文输入法，输入中文，使用空格可以触发，但是如果是选择输入法中的第二个中文，就不会触发，后续再使用回车键又能触发了

**Comment by jsoneP** [comment]
反正我已经离职了，嘻嘻


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 下午2:44
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"某某"<1355039491@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)





 这就难受了呀 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月14日(星期一) 下午2:41 
 收件人:&amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"12345芝麻糖葫芦"<1933275033@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974) 
 
 
 
 
 
  没解决- -，反正好像原生的select就存在这个问题，  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月14日(星期一) 下午2:37  
  收件人:&amp;amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"某某"<1355039491@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)  
   
   
   
   
   
     
  老哥，你解决了嘛？目前我也是遇到这类问题，使用的是win10自带的中文输入法，输入中文，使用空格可以触发，但是如果是选择输入法中的第二个中文，就不会触发，后续再使用回车键又能触发了

**Comment by 12345ZMTHL** [comment]
牛逼，我还在这里挣扎


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 下午2:52
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"12345芝麻糖葫芦"<1933275033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)





 反正我已经离职了，嘻嘻 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月14日(星期一) 下午2:44 
 收件人:&amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"某某"<1355039491@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974) 
 
 
 
 
 
  这就难受了呀  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月14日(星期一) 下午2:41  
  收件人:&amp;amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"12345芝麻糖葫芦"<1933275033@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)  
   
   
   
   
   
   没解决- -，反正好像原生的select就存在这个问题，   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年9月14日(星期一) 下午2:37   
   收件人:&amp;amp;amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"某某"<1355039491@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ElemeFE/element] el-select 未设置multiple，在输入中文时不能动态回调remote-method (#17974)   
     
     
     
     
     
       
   老哥，你解决了嘛？目前我也是遇到这类问题，使用的是win10自带的中文输入法，输入中文，使用空格可以触发，但是如果是选择输入法中的第二个中文，就不会触发，后续再使用回车键又能触发了

**Comment by nadirvishun** [comment]
可能是这个问题：[[select]修复select组件在filterable属性下，使用win10微软中文输入法输入时不触发检索的问题 ](https://github.com/ElemeFE/element/pull/17494)，测试升级到最新版本后解决。
