### ISSUE TITLE
el-select控件在下拉选项很多时会很卡

### ISSUE THREAD

**Issue by yangkaige** [ElemeFE/element#17984]
这个 问题在ie（ie11）下特别明显，我测试了3千多的数据就已经很卡了，点的时候好久才弹出下拉框。
模板代码：
`<el-select
      v-model="value"
      placeholder="请选择"
    >
      <el-option
        v-for="item in cities"
        :key="item.value"
        :label="item.label"
        :value="item.value"
      >
        <span style="float: left">{{ item.label }}</span>
        <span style="float: right; color: #8492a6; font-size: 13px">{{ item.value }}</span>
      </el-option>
    </el-select>`

js代码:

for (let i = 0; i < 3670; i++) {
        this.cities.push({
          value: "GZ" + i,
          label: "目的地" + i
        });
      }

**Comment by wen403** [comment]
真的卡不知道有没有v2版
