### ISSUE TITLE
[Feature Request] Import declaration conflicts with local declaration of 'CascaderProps'.

### ISSUE THREAD

**Issue by liusseu** [ElemeFE/element#17981]
### Existing Component
否

### Component Name
none

### Description
there is a error when i package my project 
ERROR in D:/OperationFront/node_modules/element-ui/types/cascader.d.ts
3:26 Import declaration conflicts with local declaration of 'CascaderProps'.
    1 | import { VNode } from 'vue';
    2 | import { ElementUIComponent, ElementUIComponentSize } from './component'
  > 3 | import { CascaderOption, CascaderProps, CascaderNode } from './cascader-panel';
      |                          ^
    4 |
    5 | export type CascaderOption = CascaderOption
    6 |

 error  in D:/OperationFront/node_modules/element-ui/types/cascader.d.ts

**Comment by li3081934** [comment]
安装3.7以下版本的ts

**Comment by whalezhao** [comment]
遇到同样的问题。

**Comment by liusseu** [comment]
安装3.7以下版本的ts

**Comment by atorscho** [comment]
translation, please?

**Comment by acegank** [comment]
安装3.7以下并没有解决
