### ISSUE TITLE
关于跳版本

### ISSUE THREAD

**Issue by aguegu** [ElemeFE/element#1798]
这次 1.0.7 版本的升级，虽然表面上是为了 vue@2.1.6，但是实际用下来，引入新的 bug 比一点点新特性多很多啊。作为勇敢的拿你们产品投入生产环节开发的同学来说，这样很坑的说。

建议能不能稳定一下特性，先把 bug 都 fix 先。至于 vue@2.1.6，到 1.1.0+ 再考虑支持啊？

比方说，el-date-picker：

1.0.7 无法选择，基本就是废的；
1.0.6 初始值null的话，日前选择框从 1970.1.1 开始选；
我现在退回 1.0.5 了……

**Comment by Leopoldthecoder** [comment]
Bug 的出现其实和兼容 2.1.6 版本的 Vue 无关。除了已知的 DatePicker 外，还发现了什么「新的 bug」？可以直接在新 issue 中提出。

**Comment by aguegu** [comment]
虽然我遇到的 bug 可能和 vue@2.1.6 无关，但是 vue@2.1.6 的升级，会扯到 vue-loader，vue-template-loader 的连带升级啊，升上去降下来都很啰嗦的说……

在我看来，这是一次比较大的变化。

**Comment by aguegu** [comment]
随着版本升级，之前能用的功能反而倒退，这个很郁闷的说。

**Comment by reverland** [comment]
1.0.7无法选择？？我刚升级感觉没啥问题啊。。。不过我的vue锁死在2.1.3了。。

1.0.6如果是时间范围选择我好像已经修过，时间选择本来就没问题吧

**Comment by reverland** [comment]
用在生产环境的表示，每次升级都觉得坑。1.0.1之后就没升过了。。。

**Comment by Leopoldthecoder** [comment]
1.0.7 版本对 Vue 是向下兼容的，不需要升级 Vue 的全家桶。
