### ISSUE TITLE
[Bug Report] Import declaration conflicts with local declaration of 'CascaderProps'.

### ISSUE THREAD

**Issue by liusseu** [ElemeFE/element#17980]
### Element UI version
2.11.1

### OS/Browsers version
windows

### Vue version
2.6.6

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
在使用vue-cli-service build对项目进行打包时。
element-ui 组件报错
ERROR in D:/OperationFront/node_modules/element-ui/types/cascader.d.ts
 Import declaration conflicts with local declaration of 'CascaderProps'.
    1 | import { VNode } from 'vue';
    2 | import { ElementUIComponent, ElementUIComponentSize } from './component'
  > 3 | import { CascaderOption, CascaderProps, CascaderNode } from './cascader-panel';
      |                          ^
    4 |
    5 | export type CascaderOption = CascaderOption
    6 |

 error  in D:/OperationFront/node_modules/element-ui/types/cascader.d.ts

element-ui 版本2.11.1

### What is Expected?
打包成功

### What is actually happening?
报错，
ERROR in D:/OperationFront/node_modules/element-ui/types/cascader.d.ts
 Import declaration conflicts with local declaration of 'CascaderProps'.
    1 | import { VNode } from 'vue';
    2 | import { ElementUIComponent, ElementUIComponentSize } from './component'
  > 3 | import { CascaderOption, CascaderProps, CascaderNode } from './cascader-panel';
      |                          ^
    4 |
    5 | export type CascaderOption = CascaderOption
    6 |

 error  in D:/OperationFront/node_modules/element-ui/types/cascader.d.ts

**Comment by cklwblove** [comment]
问题解决了吗？能否提供下解决方案

**Comment by khoadnguyen** [comment]
I'm having the same issue, is this resolved?

**Comment by liusseu** [comment]
安装3.7以下版本的ts

**Comment by rainywalker** [comment]
When will this be solved?
