### ISSUE TITLE
[bug report] Select selector remote search causes non current values not to be displayed when selecting multiple values

### ISSUE THREAD

**Issue by soulding** [ElemeFE/element#17988]
### Element UI version
2.12.0

### OS/Browsers version
windows/谷歌版本 78.0.3904.17

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/v7rnqbzc/1/

### Steps to reproduce
可在重现链接里选择搜索两个或者以上的值，即可触发bug

### What is Expected?
希望如此https://jsfiddle.net/6mogyv2q/

### What is actually happening?
这是出现目前2.12.0的情况https://jsfiddle.net/v7rnqbzc/1/

**Comment by dushuaihua** [comment]
I also found this issue.
Is it a bug or missing some configs for el-select when use it?

**Comment by dushuaihua** [comment]
Please ref bellow:

![rsbb1121](https://user-images.githubusercontent.com/17045801/68658400-53e1bb80-0570-11ea-8dad-169f94024c35.gif)

![rsbb1122](https://user-images.githubusercontent.com/17045801/68658405-56dcac00-0570-11ea-9a8c-6853204ae279.gif)

**Comment by soulding** [comment]
> 
> 
> Please ref bellow:
> 
> ![rsbb1121](https://user-images.githubusercontent.com/17045801/68658400-53e1bb80-0570-11ea-8dad-169f94024c35.gif)
> 
> ![rsbb1122](https://user-images.githubusercontent.com/17045801/68658405-56dcac00-0570-11ea-9a8c-6853204ae279.gif)
> 
> You can test with the 'value' not equal 'label' content options, then you can reproduce this bug.



> 
> 
> Please ref bellow:
> 
> ![rsbb1121](https://user-images.githubusercontent.com/17045801/68658400-53e1bb80-0570-11ea-8dad-169f94024c35.gif)
> 
> ![rsbb1122](https://user-images.githubusercontent.com/17045801/68658405-56dcac00-0570-11ea-9a8c-6853204ae279.gif)
> 
> You can test with the 'value' not equal 'label' content options, then you can reproduce this bug.
你可参考下，下面是我暂时的解决方案
![图片](https://user-images.githubusercontent.com/18410517/68723450-8da7d600-05f3-11ea-9e87-bda6c031a2f0.png)

**Comment by dushuaihua** [comment]
@soulding 因为是remote的结果，所以你每次this.employeeOptions.push(tmp);之前是不是需要clear一下当前的this.employeeOptions？

**Comment by soulding** [comment]
> 
> 
> @soulding 因为是remote的结果，所以你每次this.employeeOptions.push(tmp);之前是不是需要clear一下当前的this.employeeOptions？

对，是这样的。
