### ISSUE TITLE
[Bug Report] Typescript 3.7 declaration conflicts

### ISSUE THREAD

**Issue by ZanderOlidan** [ElemeFE/element#17994]
### Element UI version
2.10.1

### OS/Browsers version
macOS Mojave

### Vue version
2.6.10

### Reproduction Link
-

### Steps to reproduce

Install Typescript 3.7. Run a project with element ui.

### What is Expected?
To build properly

### What is actually happening?
Running the dev environment breaks on Typescript 3.7 with the error below

```
ERROR in /Users/project/node_modules/element-ui/types/cascader.d.ts(3,10):
3:10 Import declaration conflicts with local declaration of 'CascaderOption'.
    1 | import { VNode } from 'vue';
    2 | import { ElementUIComponent, ElementUIComponentSize } from './component'
  > 3 | import { CascaderOption, CascaderProps, CascaderNode } from './cascader-panel';
      |          ^
    4 |
    5 | export type CascaderOption = CascaderOption
    6 |
ERROR in /Users/project/node_modules/element-ui/types/cascader.d.ts(3,26):
3:26 Import declaration conflicts with local declaration of 'CascaderProps'.
    1 | import { VNode } from 'vue';
    2 | import { ElementUIComponent, ElementUIComponentSize } from './component'
  > 3 | import { CascaderOption, CascaderProps, CascaderNode } from './cascader-panel';
      |                          ^
    4 |
    5 | export type CascaderOption = CascaderOption
    6 |
ERROR in /Users/project/node_modules/element-ui/types/cascader.d.ts(3,41):
3:41 Import declaration conflicts with local declaration of 'CascaderNode'.
    1 | import { VNode } from 'vue';
    2 | import { ElementUIComponent, ElementUIComponentSize } from './component'
  > 3 | import { CascaderOption, CascaderProps, CascaderNode } from './cascader-panel';
      |                                         ^
    4 |
    5 | export type CascaderOption = CascaderOption
    6 |
```

**Comment by smallp** [comment]
Same issue.

**Comment by loca-spirit** [comment]
希望尽快解决

**Comment by salvadordiaz** [comment]
This is easily fixed by changing lines 3 to 9 of `types/cascader.d.ts` to 
```
import { CascaderOption as CascaderOption2, CascaderProps as CascaderProps2, CascaderNode as CascaderNode2 } from './cascader-panel';

export type CascaderOption = CascaderOption2

export type CascaderProps<V, D> = CascaderProps2<V, D>

export type CascaderNode<V, D> = CascaderNode2<V, D>

**Comment by wizardnet972** [comment]
also happens in version 2.12.0

**Comment by teo001** [comment]
@salvadordiaz I solved the problem with you solution:

`import { CascaderOption as CascaderOption2 , CascaderProps as CascaderProps2 , CascaderNode as  CascaderNode} from './cascader-panel';

export type CascaderOption = CascaderOption2

export type CascaderProps<V, D> = CascaderProps2<V, D>

export type CascaderNode<V, D> = CascaderNode2<V, D>
`

Thank you very much!

**Comment by troy351** [comment]
It was fixed here https://github.com/ElemeFE/element/commit/d15b778826870954c7ae0afe54a707d97ae212e9
But no new release yet

**Comment by wizardnet972** [comment]
@troy351 so when please? it's a critical bug

**Comment by troy351** [comment]
I am also wondering





------------------ Original ------------------

**Comment by emretoprak** [comment]
i have same issue

**Comment by troy351** [comment]
@island205 @ziyoung Could you please publish a release for this bug now?

**Comment by lanten** [comment]
我几乎无法开始开发，为什么不发布？没人维护了吗

**Comment by eason-shsf** [comment]
> 我几乎无法开始开发，为什么不发布？没人维护了吗

you could downgrade typescript in your package.json to 3.5.3 until new elementui version released

**Comment by lanten** [comment]
> > 我几乎无法开始开发，为什么不发布？没人维护了吗
> 
> you could downgrade typescript in your package.json to 3.5.3 until new elementui version released

thanks for your reply，I will try this

**Comment by cnjack** [comment]
change typescript version to 3.5.3 works for me, thx~~

wait for new elementui version released😆

**Comment by zhangporco** [comment]
将 typescript 降至3.5.3 确实可以解决，但是不完美啊 😂

**Comment by loca-spirit** [comment]
下个月能解决吗，或者先发个小版本，已经开始用3.7里面的构建特性了。

**Comment by salvadordiaz** [comment]
I just forked the element repo and tagged a "release" of the v2.12.0 with the fix for typescript 3.7 compatibility cherry-picked from the current dev branch. 
If you want to use it in your project while the element team cuts a true release. You can replace the element-ui dependency declaration in your package.json with 

`"element-ui":"https://github.com/hyperlex/element#v2.12.0-tsfix"`

No support will be provided, use it only if your project must be compatible with typescript 3.7 and you absolutely cannot wait for the official release containing the fix.

**Comment by lcoder** [comment]
问下发布了吗，在线等

**Comment by kelvinXueLei** [comment]
问下发布了吗，在线等

**Comment by cnjack** [comment]
问下发布了吗，在线等

**Comment by LLawlight** [comment]
> We will release version 2.13.0 to fix this problem at next Tuesday.

哥，Tuesday了，请问今天几点会发呢

**Comment by island205** [comment]
Element 2.13.0 已发布
