### ISSUE TITLE
建议 Table 组件增加筛选、后端排序的功能

### ISSUE THREAD

**Issue by xnumb** [ElemeFE/element#180]
1.排序仅支持前端排序
2.表头不支持筛选
3.固定一列横向滚动表头不跟随着滚动
4.各种 0 0
之前看过 antd的各种组件 ，其中的table就很完善 但是那个是用react 写的 还是想用vue  所以选择了element 希望能越来越完善

**Comment by QingWei-Li** [comment]
3 已经修过了
4 是什么鬼

**Comment by furybean** [comment]
@QingWei-Li  『排序仅支持前端排序』支持后端排序还是挺容易的，排上日程吧。

**Comment by zhcsyncer** [comment]
讲道理, table 的selection 可否配置禁用.
比如某些数据应业务需求确实需要禁用.
然而应该会影响到多选的状况.

**Comment by fishpaw** [comment]
@zhcsyncer ，你是说整行数据默认禁用么，能否具体描述一下你说的场景？

**Comment by Leopoldthecoder** [comment]
@fishpaw 他的意思是进行选择时（单选或多选），某些行不可被选中

**Comment by fishpaw** [comment]
@xnumb ,「表头筛选」的功能之后会加入

**Comment by zhcsyncer** [comment]
@fishpaw , 如同 @Leopoldthecoder 所说,很多业务场景下,都会有这样的需求,可能特定的数据不允许选中进行某些操作.这样

**Comment by fishpaw** [comment]
@zhcsyncer ，嗯，清楚了。会和团队成员确认这个 feature，如果真的有必要，会在优化交互后添加

**Comment by chachaxw** [comment]
@fishpaw 表格中插入可操作按钮怎么插入的？官方网站也没有一个这样的demo，文档感觉也不太清楚，有点懵逼。
<img width="168" alt="screen shot 2016-10-06 at 21 25 16" src="https://cloud.githubusercontent.com/assets/9986672/19154036/714e7a0a-8c0b-11e6-9d6a-9524363a0a9f.png">

**Comment by Leopoldthecoder** [comment]
@chachaxw 参考 #169

**Comment by perfectyang** [comment]
[
![er](https://cloud.githubusercontent.com/assets/8724828/19154383/df51ab52-8c0c-11e6-9dd8-82e1f5af7367.png)
](url)
固定列和表头，表格里面有换行时，固定列出现问题

**Comment by furybean** [comment]
以上功能 RC8 均已支持。
