### ISSUE TITLE
el-select 远程搜索多选组件显示bug

### ISSUE THREAD

**Issue by shanlanhua** [ElemeFE/element#18002]
版本：2.12.0
问题描述：通过远程搜索选中的的值，在input框内显示value值 不显示label值；
![image](https://user-images.githubusercontent.com/25973551/68520351-d3059400-02d1-11ea-83b1-2685a9c0475f.png)

**Comment by FeiFanLiang** [comment]
同样问题

**Comment by shanlanhua** [comment]
升级版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FeiFanLiang <notifications@github.com&gt;
发送时间: 2020年2月22日 16:57
收件人: ElemeFE/element <element@noreply.github.com&gt;
抄送: shanlanhua <282617964@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ElemeFE/element] el-select 远程搜索多选组件显示bug (#18002)




同样问题
