### ISSUE TITLE
select组件性能优化建议

### ISSUE THREAD

**Issue by ljyf5593** [ElemeFE/element#1802]
select组件性能优化建议：
       当前select组件如果传入的组件非常多（超过1000个）在搜索选择选项的时候性能非常差，尤其是在火狐浏览器下，基本不能使用。主要原因是渲染的dom元素太多。
      优化建议，增加一个最大选项参数，搜索的时候在选项数组中选择，但是渲染到页面中只显示最大选项数个元素，提升性能。

**Comment by Leopoldthecoder** [comment]
这种情况适合远程搜索。
另外，没太明白你所说的「最大选项参数」的机制，如果满足搜索条件的选项有 100 个，而最大选项数为 50 的话如何处理？

**Comment by ljyf5593** [comment]
这样也只显示50个啊，选中一个就再添加一个，就是下拉选项里面始终只有50个。提出这种策略，主要是参考了 select2 和 selectize 这两个插件的实现方式，就是对下拉选项的数量做了控制，不会无限制的渲染dom数量。

**Comment by Leopoldthecoder** [comment]
那么如果我想选的那个选项排在第 60 位的话，不就看不到了？

**Comment by ljyf5593** [comment]
增加输入的内容，让搜索更精准啊，把范围缩小，下拉选项60个，下拉到下面也是挺麻烦的吧。

**Comment by Leopoldthecoder** [comment]
这样的话交互挺奇怪的，建议还是使用远程搜索。
