### ISSUE TITLE
[Bug Report] loading spinner size too large

### ISSUE THREAD

**Issue by swuecho** [ElemeFE/element#18046]
### Element UI version
2.12.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/5qe2tujm/

### Steps to reproduce
open the link and the problem will surface.

### What is Expected?
the spinner should be less than the size of parent button

### What is actually happening?
the spinner is too large

**Comment by hxlyd** [comment]
why don’t use loading property of el-button?

**Comment by swuecho** [comment]
@hxlyd  I did not know it. Thanks
