### ISSUE TITLE
[bug report] After the remote search in the component select changes the search term, the display text of the previously selected option changes from label to value

### ISSUE THREAD

**Issue by fuffcp123** [ElemeFE/element#18047]
### Element UI version
2.12.0

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/fuffcp123/pen/gOOBLgz

### Steps to reproduce
0.准备一个数组，其中分别有label为text0-19和plan20-29且value值与数字序号相同的演示数据。

1.输入搜索关键词，如text，得到搜索结果列表，此时下拉列表显示文字为text0-19。

2.任意选中选项，如text0、text3、text6，此时Select框内显示的文字是text0、text3、text6。

3.点击其他区域或手动退格清空搜索关键词，然后输入plan，选中任意选项，如plan20，此时Select框内的显示文字是0、3、6、plan20，期望结果应为text0、text3、text6、plan20。

4.从步骤2起，退格删除一个标签后也会出现步骤3的结果。

### What is Expected?
在变更搜索关键词并选中其他选项后，之前选中的选项的显示文字应当为label的值。

### What is actually happening?
在变更搜索关键词并选中其他选项后，只有最新搜索结果中的选项显示为label值，其余皆为value的值。

**Comment by zumoshi** [comment]
Duplicate of #17327
