### ISSUE TITLE
NavMenu 组件在启用vue-router 模式后 生成的代码默认生成li 不是a标签

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#1804]
一些跳转的link还是编译为a标签更为的合理，比如用户想右键新开窗口 
生成的代码如图
![image](https://cloud.githubusercontent.com/assets/8121621/21261525/fe2f1982-c3c6-11e6-9a31-7578368557e9.png)

其实可以借鉴vue router的写法
![image](https://cloud.githubusercontent.com/assets/8121621/21261537/19d42588-c3c7-11e6-9a12-a04a2739e240.png)

**Comment by baiyaaaaa** [comment]
首先得话这个是菜单不是单纯的链接，而且在 <li>下面多渲染一层<a>标签会让整个dom tree显得太臃肿

**Comment by PanJiaChen** [comment]
@baiyaaaaa 菜单的意义是什么？不是页面跳转么？可以借鉴https://router.vuejs.org/zh-cn/api/router-link.html 里面的tag 至少增加一个自定义性吧

**Comment by baiyaaaaa** [comment]
将它改为 a 的意义是啥？按照规范 a 标签多层嵌套是不允许的，会导致 href 失效。

**Comment by PanJiaChen** [comment]
还是通过在<el-menu-item>里面嵌套<router-link>来满足需求。
