### ISSUE TITLE
After the [bug report] menu component is encapsulated, infinite recursion will occur under the collapse, resulting in an error report

### ISSUE THREAD

**Issue by FengJing0** [ElemeFE/element#18043]
### Element UI version
2.12.0

### OS/Browsers version
mac/Chrome  78.0.3904.87

### Vue version
2.6.10

### Reproduction Link
https://github.com/FengJing0/element-menu-bug

### Steps to reproduce
将 menu 的 collapse 设为 true 后，鼠标经过 item ，控制台报错。

### What is Expected?
不报错

### What is actually happening?
debugger 发现报错点为
```js
if (this.appendToBody) {
    this.$parent.$el.dispatchEvent(new MouseEvent('mouseenter'));
}
```
因为单独给 menu-item 和 submenu 做了封装，此时的this.$parent.$el还是自身，this.$parent.$parent.$el 才为期望的父组件

**Comment by camoth** [comment]
I have the same problem！

**Comment by zengyuanqiu** [comment]
我也遇到了

**Comment by ssw1992** [comment]
2.5.19还是能重现
![image](https://user-images.githubusercontent.com/24841397/182774867-3c3686f0-692e-42cc-9ba3-778429fc951a.png)
好久了，都没人修了
