### ISSUE TITLE
[bug report] datetimepicker after the custom picker option is less than the current time, the time of the day cannot be selected

### ISSUE THREAD

**Issue by pslean** [ElemeFE/element#18052]
### Element UI version
2.12.0

### OS/Browsers version
MacOS15

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/xptngLvz/1/

### Steps to reproduce
1、打开date picker
2、日期选择明天
3、日期选择今天

### What is Expected?
可以选择今天的日期，因为今天的后面time是大于当前时间的

### What is actually happening?
不能再次选择今天的日期

**Comment by afei1217** [comment]
> Translation of this issue:
> 
> ### Element UI version
> 2.12.0
> 
> ### OS/Browsers version
> MacOS15
> 
> ### Vue version
> 2.6.10
> 
> ### Reproduction Link
> https://jsfiddle.net/xptngLvz/1/
> 
> ###Steps to reproduce
> 
> 1. Open date picker
> 2. Date selection tomorrow
> 3. Date selection today
> 
> ### What is Expected?
> You can choose today's date because the later time of today is greater than the current time
> 
> ### What is actually happening?
> Today's date can't be selected again

您上面的链接 当代码改成如下

**Comment by afei1217** [comment]
> Translation of this issue:
> 
> ### Element UI version
> 2.12.0
> 
> ### OS/Browsers version
> MacOS15
> 
> ### Vue version
> 2.6.10
> 
> ### Reproduction Link
> https://jsfiddle.net/xptngLvz/1/
> 
> ###Steps to reproduce
> 
> 1. Open date picker
> 2. Date selection tomorrow
> 3. Date selection today
> 
> ### What is Expected?
> You can choose today's date because the later time of today is greater than the current time
> 
> ### What is actually happening?
> Today's date can't be selected again

你上面的链接中的代码 改成如下

**Comment by afei1217** [comment]
> Translation of this issue:
> 
> ### Element UI version
> 2.12.0
> 
> ### OS/Browsers version
> MacOS15
> 
> ### Vue version
> 2.6.10
> 
> ### Reproduction Link
> https://jsfiddle.net/xptngLvz/1/
> 
> ###Steps to reproduce
> 
> 1. Open date picker
> 2. Date selection tomorrow
> 3. Date selection today
> 
> ### What is Expected?
> You can choose today's date because the later time of today is greater than the current time
> 
> ### What is actually happening?
> Today's date can't be selected again

您上面的链接 代码改成如下
html:
type="datetimerange"
:default-time="['00:00:00', '23:59:59']"
js: 
pickerOptions: {
    disabledDate(time) {
            return time.getTime() >= Date.now();
     }
}
日期段选择当天的。 确定按钮就不能使用了

**Comment by note520** [comment]
2.13.0、2.13.2 也都有这个问题
