### ISSUE TITLE
[bug report] Select drop-down box position offset

### ISSUE THREAD

**Issue by Sinosaurus** [ElemeFE/element#18051]
### Element UI version
2.12.0

### OS/Browsers version
Chrome  76.0.3809.132

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Sinosaur/faurc5zw/

### Steps to reproduce
1. body 添加 相对定位
2. 父元素添加 margin

### What is Expected?
正常显示，而不是 下拉框偏移位置

### What is actually happening?
popper.js [BUG](https://github.com/FezVrasta/popper.js/issues/618)

**Comment by moeyui1** [comment]
同样的问题

**Comment by kerwin-ly** [comment]
Same here, anyone has solutions for it?
