### ISSUE TITLE
Default active setting of [bug report] menu component

### ISSUE THREAD

**Issue by forget1** [ElemeFE/element#18067]
### Element UI version
2.12.0

### OS/Browsers version
win10/chrome 78

### Vue version
2.5.20

### Reproduction Link
https://github.com/forget1/huji_cms

### Steps to reproduce
构建完成后，在登录位置输入admin（用户名和密码是同一个），之后再导航中随便选择一个，刷新页面，看是否高亮当前路由对应的item

### What is Expected?
在进入main这个路由后，想根据当前的路由高亮对应的item，刷新页面之后也可以高亮

### What is actually happening?
没有效果，并且点击了当前路由对应的item，控制台中会有`NavigationDuplicated`错误

**Comment by xrkffgg** [comment]
自己监控路由的变化，去设置当前的显示

**Comment by forget1** [comment]
那具体应该怎么弄呢？ 我代码里应该有在计算属性里获取this.$route.path了

**Comment by xrkffgg** [comment]
https://cn.vuejs.org/v2/guide/computed.html#%E4%BE%A6%E5%90%AC%E5%99%A8

**Comment by forget1** [comment]
```
computed: {
    defaultActive: function () {
      return this.$route.path.replace('/', '')
    }
  }
```
这段代码我再Main.vue这个文件里有写这个，不加replace的也尝试过，并没有什么变化..

**Comment by xrkffgg** [comment]
watch监控路由啊



------------------ Original ------------------

**Comment by forget1** [comment]
已经好了，谢谢，麻烦您了
