### ISSUE TITLE
[Bug Report] no default value，If two or more items are the same

### ISSUE THREAD

**Issue by chentingjun** [ElemeFE/element#18063]
### Element UI version
2.12.0

### OS/Browsers version
win/chrome 78.0.3904.87

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/chentingjun/pen/rNNqJKe?editors=1111

### Steps to reproduce
有默认值：https://codepen.io/chentingjun/pen/KKKGyVV?editors=1111 
无默认值：https://codepen.io/chentingjun/pen/rNNqJKe?editors=1111

### What is Expected?
修复，名字一样的也可以默认值，能不能内部自己设置一个 无关联的 id， 使不出现以 label 相同时给不了默认值的情况

### What is actually happening?
['北京市', '北京市', '东城区'],
设置组件返回的值是 label , 但仍然能够设置默认值

**Comment by xrkffgg** [comment]
直接自己在 data 里，定义了 id 不就行了
