### ISSUE TITLE
[bug report] cascade multiple selection deletion in disorder

### ISSUE THREAD

**Issue by ldc4** [ElemeFE/element#18071]
### Element UI version
2.11.1

### OS/Browsers version
Mac/Chrome 78.0.3904.87

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/ldc4/wa4om2v8/7/

### Steps to reproduce
删除第二个

### What is Expected?
正常删除掉第二个

### What is actually happening?
删除第二个，但是被删的是第三个

#17662 
cascader级联选择器多选时，若v-model绑定数组与options内选中数组顺序不同，点击删除标签就会删除其他错误的标签，现在cascader级联组件删除是不是用value查找删除，所以一旦顺序不同就会删错。

**Comment by HuberTRoy** [comment]
这种情况处理一下value不是可以吗？

**Comment by ldc4** [comment]
@HuberTRoy 业务层虽然能处理，但是本来是组件的职责（封装公共部分），下放到业务层去处理有点不妥吧。这里反馈个建议。

**Comment by ldc4** [comment]
另外，我实际业务中的options是异步拉取的，如果value要排序，我还得同步等到options有值的时候，才能去排序value。原本options作为一个计算属性就行了，现在被迫搞到生命周期或方法中。
如果每个业务都要做这样的事情，组件封装进去，那么会好用很多。虽然我的业务是处理好了，但是还是希望优化一下这里吧

**Comment by ldc4** [comment]
要是能支持【已选选项值是否按照选项顺序排序】这个属性，就更好了。

**Comment by xrkffgg** [comment]
@ldc4 修改了一下，应该可以修复这个问题，但是不确定 Eleme 团队能否 合并。
你可以把这个 vue 文件单独拿出来，按照我的改动地方修改，然后换个标签单独引用就行。样式通用的。

**Comment by xrkffgg** [comment]
有点问题，我再改一下

**Comment by xrkffgg** [comment]
目前只有在 show-all-levels 为 false 时 才生效

**Comment by xrkffgg** [comment]
因为你代码
`:props="{ multiple: true, checkStrictly: true, emitPath: false }"`
的一些设置，获取到的 tag 的格式不太一样，使用 tag 的方法不太通用，改动还是比较多的。

目前我的那个改动只适应于你的条件

**Comment by ldc4** [comment]
这里调整顺序就行了，牺牲一点性能，封装在组件内。而且为啥多选一定要按照options的顺序。
element用起来，还是有点不顺手。
之前搞react，ant-design那套真的好用太多（实力背书），不知道是不是vue太灵活导致的

**Comment by ldc4** [comment]
这里等后面有空，我看看要怎么改成通用的，至于官方合不合，是另一回事了。毕竟没有这个改动，也不是绕不开这个问题，只是从组件的易用性、合理性出发来考虑的。

- 开源协同，让世界更美好
