### ISSUE TITLE
[Feature Request] Add tooltip for el dropdown item when disabled

### ISSUE THREAD

**Issue by krystian-wolarek** [ElemeFE/element#18075]
### Existing Component
Yes

### Component Name
Dropdown

### Description
It would be great to be able to display tooltip for disabled dropdown item with explanation why this option is disabled.
Other possible solution for dropdown item could be to allow accepting boolean and string for disabled prop. When string is set it will be displayed in tooltip as explanation. tooltip props could be passed in other prop for that.

**Comment by xrkffgg** [comment]
You can use `Popover`

Like this :
https://codepen.io/xrkffgg/pen/oNNJGPz?editors=1111

**Comment by krystian-wolarek** [comment]
I found better workaround for that.

I had to disable item and override styles to allow pinter events, then inside it i had to stop click propagation from inner div, and then override styles for that div with negative margin on sides and additional padding.

Like this: 
https://codepen.io/codeapi/pen/dyyrKeb

**Comment by maurer2** [comment]
Hello, as a workaround, you could add the tooltip component without an icon inside the option that is disabled. Like so

```js
<el-option
                        value="someValue"
                        label=""
                        :disabled="true"
                    >
                        <span>
                            <el-tooltip
                                v-if="true"
                                placement="bottom"
                                :content="Text inside tooltip"
                            >
                                <span class="label">Label</span>
                            </el-tooltip>
                        </span>
                    </el-option>
```
