### ISSUE TITLE
[bug report] when the parent width of El input component is too low, the cursor will disappear

### ISSUE THREAD

**Issue by 150148313** [ElemeFE/element#18081]
### Element UI version
2.7.2

### OS/Browsers version
windows 10/ chrome 74.0.3729.169

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/r68Lw1pj/1/

### Steps to reproduce
 <div style="width: 20px;"><el-input v-model="input"></el-input></div>

### What is Expected?
期望不会消失

### What is actually happening?
光标消失了

**Comment by xrkffgg** [comment]
```
.el-input__inner {
    padding: 0 15px;
}
```

这个 `input` 的输入框，增加了 `padding` 你距离太小的话，就显示不出来的。

你如果要想显示，可以把这个 `padding` 改成 0
