### ISSUE TITLE
[Feature Request] Is this repo no longer in maintenance?

### ISSUE THREAD

**Issue by miccuci** [ElemeFE/element#18089]
### Existing Component
否

### Component Name
Is this repo no longer in maintenance?

### Description
The latest version was released in 2019.08.29.So,is this repo still in maintenance?

elementui最新发布版本是2.12.0，从2019.08.29之后没有再发布新版本，请问现在官方团队还在维护吗，还是说要发布3.0版本了？

**Comment by zazzaz** [comment]
YES! 🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉

element-plus/element-plus#147

**Comment by zhouzhongyuan** [comment]
Still under maintenance.
