### ISSUE TITLE
[Feature Request] Add el-scrollbar to el-table component

### ISSUE THREAD

**Issue by ositowang** [ElemeFE/element#18099]
### Existing Component
是

### Component Name
el-table

### Description
Currently, `el-table` use the unstyled scrollbar. As element-ui has the `el-scrollbar` component, is it possible to add scrollbar to the `el-table` component for consistency?

**Comment by smallsunnyfox** [comment]
In particular, it is necessary to modify the scroll bar style when fixing the header.

**Comment by ositowang** [comment]
@smallsunnyfox Could you give me a little more details on how to fix it? I am currently facing this issue..Thank you.

**Comment by smallsunnyfox** [comment]
> @smallsunnyfox Could you give me a little more details on how to fix it? I am currently facing this issue..Thank you.

Maybe we just need a less ugly scrollbar like el-scrollbar in el-table when the table's header is fixed or in other cases
Maybe [this](https://segmentfault.com/q/1010000016366942?sort=created) can help you
