### ISSUE TITLE
Slider does not fire change event on dragging

### ISSUE THREAD

**Issue by espspinix** [ElemeFE/element#1809]
### ElementUI version
1.0.7 (latest)

### OS/Browers version
macOS
Tested on: Chrome 54 && Firefox 52

### Vue version
2.1.6

### Reproduction Link
https://jsfiddle.net/a2k1nzfu/

### Steps to reproduce
Change value of slider by dragging the slider.

### What is Expected?
Slider should fire change event on each (completed) change. 

### What is actually happening?
Slider does not fire change event. Event is only fired when clicking on slider, but not when dragging.

### How could this be solved?
It seems to me that this is happening because of this code:
https://github.com/ElemeFE/element/blob/dev/packages/slider/src/main.vue#L196
Here a setTimeout is used to asynchronously set dragging to false - later in setPosition the change event is only fired when dragging is false, which probably is not yet true in that moment because of the asynchronous setting of dragging.
As far as I have seen, the setTimeout has been added to fix some other behaviour - unfortunately I don't understand the comment as it is in Chinese.

**Comment by Leopoldthecoder** [comment]
You're right. Fixed in #1810.
