### ISSUE TITLE
下拉框默认值

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#181]
`el-dropdown`下拉框的`icon-separate`属性确定默认值是`false`？为什么我试了发现默认值好像是`true`？还有这个属性真的有必要么？固定下就好了啊感觉

**Comment by erguotou520** [comment]
另外建议下拉框不只是`text`，可以加个`slot`，类似于右上角github的`avatar`下拉可以设置个人信息这样的应用场景

**Comment by csvwolf** [comment]
#183

**Comment by erguotou520** [comment]
虽然rc6做了调整，但是感觉还是不够好用，建议`el-dropdown-link`里的东西可以直接做成`slot`。另外，建议在`el-dropdown`上添加`open-class`和`close-class`或者添加一个`class`这样可以实现更改下拉箭头的功能，比如展开时箭头朝上，收起时箭头朝下。
