### ISSUE TITLE
[bug report] the checkbox component in the table component does not update the style according to the external status

### ISSUE THREAD

**Issue by wangshengkun** [ElemeFE/element#18109]
### Element UI version
2.12.0

### OS/Browsers version
windows10/Google Chrome 78.0.3904.108

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/Gatsby/0fthvjd9/

### Steps to reproduce
1.选中索引为1的checkbox组件
2.点击表头【点击我全选】文本
3.索引为1、2的两个checkbox组件未修正为选中样式
4.打开控制台查看log或Vue-devtool工具，均可发现checkbox组件的checked属性均为true
ps:翻阅以往issue发现相应问题皆与作用域插槽有关，可是此列中已经明确添加了【slot-scope="scope"】属性。

### What is Expected?
checkbox组件的样式随着checked属性的变换而变化。

### What is actually happening?
checkbox组件的样式未跟随checked属性的变换而变化。

**Comment by csvwolf** [comment]
The correct Demo:
https://jsfiddle.net/f6hxLdos/

`checked` only be used when `onCreated`. If you want to change the value, you should use `value` or `v-model`.
