### ISSUE TITLE
[Feature Request] Add image preview to specify start position

### ISSUE THREAD

**Issue by kzone0520** [ElemeFE/element#18101]
### Existing Component
Yes

### Component Name
el-image

### Description
When i render the el-image image list with v-for, whenever i click on an image, the preview always starts with the first image, hope to add the index attribute to specify where the preview starts. [https://jsbin.com/hefepuy/2/edit?html,output]

**Comment by nebulade** [comment]
Same for me, this would be a great improvement

**Comment by kzone0520** [comment]
Have you solved the problem? I regenerate the image array when I click Preview


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Johannes Zellner"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 凌晨1:50
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"Kaizhong.Zheng"<946578749@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] [Feature Request] Add image preview to specify start position (#18101)




Same for me, this would be a great improvement

**Comment by cs1707** [comment]
fixed

**Comment by ahmadshah99** [comment]
@cs1707 how do you specify an index now?
