### ISSUE TITLE
`value` attribute of `el-select` component does not work !

### ISSUE THREAD

**Issue by sentenes-z** [ElemeFE/element#18118]
### Element UI version
2.12.0

### OS/Browsers version
MacOS 10.15.1 / Chrome 78.0.3904.97 （64 位）

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/drpqLf7g/

### Steps to reproduce
Component `el-select`   https://element.eleme.cn/#/en-US/component/select  
Part `Select Attributes`  first line.  
Choose one of `value` and `v-model`, and `required` value of `value` of `props` in `select.vue` file  is `true`.  
But, `value` attribute does not work. You must use the `v-model` attribute to work.  

### What is Expected?
Fix this problem and make the value attribute work

### What is actually happening?
Fix this problem and make the value attribute work

**Comment by maoyuyang** [comment]
see [v-model](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components)
