### ISSUE TITLE
npm run dev 执行报错，下载或者clone后还有其他操作吗？？？

### ISSUE THREAD

**Issue by feifanyajun** [ElemeFE/element#1811]
### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/19487214/21284143/ae583ede-c44d-11e6-8c3b-52dffc9b1cd9.png)

**Comment by coderfe** [comment]
`npm install` 安装依赖呀

**Comment by Leopoldthecoder** [comment]
你具体的操作过程是？为啥需要在 `node_modules` 里 `npm run dev`？

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#开发环境搭建
