### ISSUE TITLE
[bug report] Popover how to prevent bubbling when the trigger type is click

### ISSUE THREAD

**Issue by zhangzhi93** [ElemeFE/element#18113]
### Element UI version
2.12.0

### OS/Browsers version
win10/chrome78

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/n40kc1gt/5/

### Steps to reproduce
点击最后一列有popover的，会触发table上的点击事件

### What is Expected?
当点击popover时，不会触发父节点的点击事件

### What is actually happening?
点击popover之后，会向上触发父节点的点击事件

**Comment by csvwolf** [comment]
Maybe it's a feature request? currently if you want to prevent bubbling, you can use `click.stop` in the button: https://jsfiddle.net/9nLs0k4j/
