### ISSUE TITLE
How to display tooltip

### ISSUE THREAD

**Issue by ChangeMyNewUsername** [ElemeFE/element#18121]
### Existing Component
是

### Component Name
 tooltip

### Description
从隐藏到显示的时间太长，希望快进慢出的效果，即当鼠标进入后瞬间展示窗体，当鼠标离开后缓慢消失，以提高用户体验，感谢大佬开发这么流畅的 ui 框架 --- 百度翻译 --- The time from hiding to displaying is too long. I hope the effect of fast in and slow out, that is, when the mouse enters, the window will be displayed instantly, and when the mouse leaves, it will disappear slowly to improve the user experience. Thank you for developing such a smooth UI framework --- Baidu translation

**Comment by CheneyH** [comment]
disabled设为true即可显示

**Comment by csvwolf** [comment]
https://element.eleme.cn/#/zh-CN/component/tooltip#gao-ji-kuo-zhan 可以使用这个来定制自己的动画效果
