### ISSUE TITLE
el-table报错:  [Vue warn]: Error in watcher "store.states.hoverRow" 

### ISSUE THREAD

**Issue by sinceow** [ElemeFE/element#1812]
```
系统:  WIN 10 x64
浏览器: IE 11 仿 IE 9 报错 (IE 11 不报错) 
Vue: v2.1.6
Element:  v1.0.7
```

使用的是浏览器直接引入 JS 文件再通过 `Vue.use(ELEMENT)` 进行引用.

```
[Vue warn]: Error in watcher "store.states.hoverRow" 
(found in component <table-body>)
```

**Comment by QingWei-Li** [comment]
script 标签引入的话就不需要 use 了

**Comment by rochdev** [comment]
@QingWei-Li I am having the same issue can you provide the resolution in english?

**Comment by rochdev** [comment]
Ok nevermind: it seems that if you add an invalid element to the data array you end up with this error. Sorry about that :)
