### ISSUE TITLE
[bug report] El select under ie11, the input cursor will flash.

### ISSUE THREAD

**Issue by thomasyus** [ElemeFE/element#18127]
### Element UI version
2.12.0

### OS/Browsers version
Windows 10 / IE 11

### Vue version
2.6.10

### Reproduction Link
codepen.io

### Steps to reproduce
打开官网的组件文档：
https://element.ele.me/#/zh-CN/component/select

点击select组件，select在IE11下会有光标闪烁。

### What is Expected?
希望去掉鼠标光标。

提供解决方案如下：
为input 添加 unselectable="on" 可以解决只读的input也会在IE11下获得光标闪烁的问题。建议下版本修复

### What is actually happening?
select在IE11下会获得鼠标光标闪烁

**Comment by cmm-va** [comment]
现在有暂时的解决办法吗
