### ISSUE TITLE
页面设置zoom缩放的时候 table的header和td错位的问题

### ISSUE THREAD

**Issue by souky** [ElemeFE/element#18122]
![深度截图_选择区域_20191120190130](https://user-images.githubusercontent.com/28975794/69233837-9dfa1b00-0bc8-11ea-8eaf-0e763ae05d15.png)
![深度截图_选择区域_20191120190137](https://user-images.githubusercontent.com/28975794/69233853-a94d4680-0bc8-11ea-94af-5fb2bb51acac.png)
![深度截图_选择区域_20191120190146](https://user-images.githubusercontent.com/28975794/69233857-ace0cd80-0bc8-11ea-9e9d-e444dcf55f69.png)
如图所示：td会多出1px左右

**Comment by luocong2016** [comment]
.el-table th.gutter {
    display: table-cell !important;
}

.el-table colgroup.gutter {
    display: table-cell !important;
}

**Comment by luocong2016** [comment]
但是缩放，边框会消失很离奇

**Comment by iiicon** [comment]
我也遇到了这个问题

**Comment by rebider** [comment]
mark

**Comment by zhengmiaohua** [comment]
mark
