### ISSUE TITLE
table组件中使用row-click，三个参数为何都是undefined

### ISSUE THREAD

**Issue by makunsusu** [ElemeFE/element#1813]
**table中定义如下：**
@row-click="rowClick(row, event, column)"
**script方法如下：**
rowClick: function(row, event, column) {
console.log('row clicked')
}

帮忙看下，谢谢。

**Comment by Leopoldthecoder** [comment]
定义时不需要加参数：`@row-click="rowClick"`

**Comment by makunsusu** [comment]
解决了，谢谢
