### ISSUE TITLE
[Bug Report] Theme download archive corrupted, cannot extract files

### ISSUE THREAD

**Issue by foxted** [ElemeFE/element#18144]
### Element UI version
2.12.0

### OS/Browsers version
Mac OS Catalina / Chrome 78.0.3904.97

### Vue version
2.6.10

### Steps to reproduce
- Copy the main theme in the theme generator
- Attempt to download
- Attempt to extract the zip

= zip corrupted, can't extract css

### What is Expected?
Zip can be extracted and css files are accessible.

### What is actually happening?
Zip cannot be extracted and css files are unavailable.

**Comment by csvwolf** [comment]
Check if your unzip software works correctly?( just change to another software to test)

**Comment by foxted** [comment]
The archive was compromised, I had to run `zip -FF theme.zip --out fixed-theme.zip` to fix it.
