### ISSUE TITLE
[bug report] tooltip: route switch, memory leak

### ISSUE THREAD

**Issue by PerttyZhan** [ElemeFE/element#18148]
### Element UI version
2.12.0

### OS/Browsers version
任意版本

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/zhanheng/kqouptxL/8/

### Steps to reproduce
使用tooltip组件时

### What is Expected?
不会泄露当前组件

### What is actually happening?
tooltip在路由切换是，由于内部的foucs事件无法清除，导致组件无法清除，存在内存泄露。
最主要是由于监听foucs事件用的是匿名函数，导致无法清除。

![image](https://user-images.githubusercontent.com/10022074/69326583-014a8280-0c87-11ea-8119-13ac1e425019.png)

![image](https://user-images.githubusercontent.com/10022074/69326558-f5f75700-0c86-11ea-9a94-ee265a7bb437.png)

**Comment by yunrongliu** [comment]
赶紧给老子修

**Comment by AzronChan** [comment]
@PerttyZhan 请问您是怎么排查出这里内存泄漏的，如果把 dom 节点删掉了，在chrome里会把对应的listen事件也给删掉，应该不会导致内存泄漏；

`<button id="del">del</button>

  <script>
    let el = document.createElement("p");
    el.innerHTML = "测试删除节点后是否还存在memory中";
    document.body.appendChild(el);
    document.getElementById("del").onclick = () => {
      document.body.removeChild(el);
      el = null;
    };
  </script>
`
这是我的测试demo，点击 `del` 之后并不会有 detached dom 或者增加的linsten

**Comment by onlyscv** [comment]
我们的表格嵌套了tooltips  刷新 也会导致内存一直涨
