### ISSUE TITLE
上传组件before-upload callback的file变量无法获取uid

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#1814]
上传组件中before-upload的回调无法通过file.uid来获取上传文件uid会得到undefined
但是在on-success之类的callback中的file变量可以获得uid, 目测是缺少个uid的getter?

**Comment by baiyaaaaa** [comment]
before-upload回调里的file对象是 raw file对象，不是upload component 的 fileList 里管理的，只有开始上传后才会在fileList里生成file对象并带有uid
