### ISSUE TITLE
文本输入框的placeholder显示不完整

### ISSUE THREAD

**Issue by jstdoit** [ElemeFE/element#1815]
![image](https://cloud.githubusercontent.com/assets/1089041/21292383/26e0a2d8-c53e-11e6-8c04-8848e6f1c21f.png)

如图，是否是因为line-height导致的问题呢？
环境：360极速模式

**Comment by Yunkou** [comment]
@Leopoldthecoder 

`.el-input__inner`这个class 固定了高度和padding一起使用导致，在chrome 无法复现。
建议：取消 `height: 36px; ` 的使用 ` padding: 9px 10px;` 撑起高度

**Comment by jstdoit** [comment]
@Yunkou 将input设为line-height: 1em;也可以解决，不知为何
