### ISSUE TITLE
[Feature Request] 212 open PRs

### ISSUE THREAD

**Issue by eikebartels** [ElemeFE/element#18151]
### Existing Component
No

### Component Name
Is this repo actually still under development? There are 212 open pull requests

### Description
Is this repo actually still under development? There are 212 open pull requests

**Comment by lujiaxing** [comment]
this project seems alive. But few response for bug fix and pull request. Maybe author only have little time to deal with these stuffs.

**Comment by csvwolf** [comment]
It's said that there will be a big news!

**Comment by eikebartels** [comment]
When? I like big news

**Comment by csvwolf** [comment]
@eikebartels I dont know.... just watching?
