### ISSUE TITLE
[Bug Report] ColorPicker right bar change  error!

### ISSUE THREAD

**Issue by qqlinchaox** [ElemeFE/element#18165]
### Element UI version
2.12.0

### OS/Browsers version
window7/Google Chrome78.0.3904.70

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/lipeijuan/pen/LYYadXW?此链接是随便填的直接官网重现即可

### Steps to reproduce
1使用<el-color-picker v-model="color1"></el-color-picker>组件 2 点击组件 3 在组件中输入值 类似#FFFFFF 然后在右侧的取色条上点击取色 4观察取色值变化

### What is Expected?
取色条能正确取色

### What is actually happening?
一些特殊的值后点击取色条无法获取取色条点击的值

**Comment by pupu0520** [comment]
同样的问题
