### ISSUE TITLE
The [bug report] checkbox group component does not transmit V-model, resulting in page error

### ISSUE THREAD

**Issue by lmjben** [ElemeFE/element#18163]
### Element UI version
2.12.0

### OS/Browsers version
mac/windows

### Vue version
2.6.10

### Reproduction Link
https://lmjben.github.io/element-checkbox-group-issue/

### Steps to reproduce
1、使用 element cdn 方式引入组件库。

```html
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
```

2、使用官方文档中的 checkbox-group 组件进行渲染。

```html
<el-checkbox-group>
  <el-checkbox label="复选框 A"></el-checkbox>
  <el-checkbox label="复选框 B"></el-checkbox>
  <el-checkbox label="复选框 C"></el-checkbox>
  <el-checkbox label="禁用" disabled></el-checkbox>
  <el-checkbox label="选中且禁用" disabled></el-checkbox>
</el-checkbox-group>
```

3、页面报错，无法正常渲染。

4、经发现，此问题是 el-checkbox-group 必须传 v-model 导致，建议在 v-model 等必填字段上，加上更好的错误提示。

### What is Expected?
1、页面不报错。

2、建议在 v-model 等必填字段上，加上更好的错误提示。

### What is actually happening?
1、页面报错。

2、报错提示难以发现具体问题。

**Comment by csvwolf** [comment]
The demo in homepage works well. I think no need to use *required* in the document.
