### ISSUE TITLE
[bug report] some errors about demo in the document

### ISSUE THREAD

**Issue by LeasonX** [ElemeFE/element#18164]
### Element UI version
2.12.0

### OS/Browsers version
Windows Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/leasonx/pen/jOORyPz?&editable=true

### Steps to reproduce
发现两个click的事件名称冲突，导致没有想要表达的效果

### What is Expected?
更新文档，和在线运行实例

### What is actually happening?
方法不同名之后的效果是预期的

**Comment by LeasonX** [comment]
![image](https://user-images.githubusercontent.com/15868922/69417216-2dcbd080-0d53-11ea-8e33-ae094362920b.png)

**Comment by LeasonX** [comment]
![bug](https://user-images.githubusercontent.com/15868922/69417445-a3d03780-0d53-11ea-89fe-5efd966267a8.png)

**Comment by csvwolf** [comment]
Duplicated #17863 .
