### ISSUE TITLE
[Feature Request] Is it possible to create custom button type?

### ISSUE THREAD

**Issue by ajithsimon** [ElemeFE/element#18168]
### Existing Component
Yes

### Component Name
Button

### Description
In my design I have varieties of buttons. So if I can create custom button types and scss for that, It will be more helpful.

Thanks.

**Comment by csvwolf** [comment]
I think you can override the css by yourself?

**Comment by ajithsimon** [comment]
Yes, that I can do. But I just want to know the possibilities.
