### ISSUE TITLE
[Bug Report] Tab in Dialog make my browser crash on close dialog.

### ISSUE THREAD

**Issue by huonsokly** [ElemeFE/element#18170]
### Element UI version
2.12.0

### OS/Browsers version
firefox

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/18169

### Steps to reproduce
no

### What is Expected?
no

### What is actually happening?
no

**Comment by csvwolf** [comment]
Reproduction Link in codepen or jsfiddle is nessary.
