### ISSUE TITLE
[Feature Request] How to set break point into element ui source

### ISSUE THREAD

**Issue by mattwmj** [ElemeFE/element#18176]
### Existing Component
是

### Component Name
el-select

### Description
I am developing with element ui, webpack and chrome.
I want to set break point into el-select source but in chrome source there is only elementui/lib folder, no elementui/src folder.
Please help!

我正在使用element ui、webpack和chrome进行前端开发。
我想在el-select的源码中加断点来debug一个事件，但是chrome的source中只显示element/lib，不显示elementui/src。
请问要怎样配置webpack/chrome来调试源码？

我明白这可能是webpack/chrome相关的问题，但是如果谁有经验的话还请指导。 谢谢！

**Comment by wangdaodao** [comment]
node_modules里面可以找到源码，然后想怎么打点就怎么打点。
