### ISSUE TITLE
[Feature Request] 建议折叠面板的后边 加上文字状态‘展开’和‘收起’

### ISSUE THREAD

**Issue by 1527082499** [ElemeFE/element#18185]
### Existing Component
是

### Component Name
¶ Collapse 折叠面板

### Description
建议折叠面板的后边 加上文字状态‘展开’和‘收起’，，，在面板全部收起时，看到后边的状态文字可以给用户知道这个是有可展开的操作

**Comment by xrkffgg** [comment]
https://github.com/xrkffgg/element/commit/2b1e78fd6234d4b8f73d5110c9dadb7b1c04482d

自己改了一下，你可以直接仿照这个，自己 copy 一份，直接在自己项目中更改使用

自定义一个其他的标签，比如 ell-collapse
