### ISSUE TITLE
[bug report] El table span method causes jitter

### ISSUE THREAD

**Issue by oopscharles** [ElemeFE/element#18183]
### Element UI version
2.11.1

### OS/Browsers version
mac OS 10.15.1/ chrome 78.0.3904.108（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/chengl0417/pen/xxxNYPj

### Steps to reproduce
1. 建立一个 table
2. 使用 span-method 方法合并任意一列,此列使用 template 定义一个 input
3. 修改 input 内部的值，导致表格抖动

### What is Expected?
修改 input 的值，表格不应该抖动

### What is actually happening?
修改 input 的值，表格抖动

**Comment by wangdaodao** [comment]
感觉好像表格合并不对导致的，我用官方的合并demo，加上input，好像就没有问题。https://codepen.io/wangdaodao/pen/abbrYKe

**Comment by oopscharles** [comment]
你输入改变信息也会抖动的，看看你的表头

**Comment by wangdaodao** [comment]
> 
> 
> 你输入改变信息也会抖动的，看看你的表头
> ![image](https://user-images.githubusercontent.com/55755162/69529208-c8721c80-0faa-11ea-8bf5-8aa4bd7aa9b2.png)

我用的火狐浏览器，貌似没问题，谷歌的好像是动的。

![github1.gif](https://i.loli.net/2019/11/26/3kWB9Jp7yXuObsE.gif)

**Comment by oopscharles** [comment]
:key="Math.random()"
我加了这个属性来确保唯一性，你应该没有

**Comment by oopscharles** [comment]
> > 你输入改变信息也会抖动的，看看你的表头
> > ![image](https://user-images.githubusercontent.com/55755162/69529208-c8721c80-0faa-11ea-8bf5-8aa4bd7aa9b2.png)
> 
> 我用的火狐浏览器，貌似没问题，谷歌的好像是动的。但是你第一个demo，火狐也是会动的，所以感觉第一个demo代码有点问题。
> 
> ![github1.gif](https://camo.githubusercontent.com/7871ab64807b45556c6c5da0d09514256b9f22e9/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f32362f336b5742394a70377958754f6273452e676966)

试了下你的代码，在 chrome 中有问题的，火狐正常

**Comment by oopscharles** [comment]
按照 [vue 2.6 最新的插槽语法](https://cn.vuejs.org/v2/guide/components-slots.html#ad)，不会出现该问题，使用旧版默认插槽（具名插槽）的确会导致出现该问题.

最新默认插槽使用不会抖动，代码展示[这里](https://codepen.io/chengl0417/pen/OJVZemy)
