### ISSUE TITLE
[bug report]The display of tag and panel in the input box of  cascade selector is inconsistent

### ISSUE THREAD

**Issue by b-ye** [ElemeFE/element#18198]
### Element UI version
2.12.0

### OS/Browsers version
chrome78

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/YepBug/pen/bGGPpQE?&editable=true

### Steps to reproduce
通过 v-model 为 el-cascader 绑定value 值，通过push方法修改value值

### What is Expected?
级联选择器多选时输入框中tag与panel展示一致

### What is actually happening?
级联选择器多选时输入框中tag与panel展示不一致，panel中展示了应有的变化，但时输入框中tag并无变化

**Comment by kaizi311** [comment]
同问
