### ISSUE TITLE
【bug】el-table 行的双击和单击

### ISSUE THREAD

**Issue by fishcanotfly** [ElemeFE/element#18193]
el-table添加了双击和单击事件（row-click、row-dblclick），每次双击，都会带有两次单击事件，应该把双击和单击区分开，双击是双击，而不能把它单存判断为还单击了两次

**Comment by mynamezhaoyu** [comment]
单击：mousedown, mouseup, click
双击：mousedown, mouseup, click, mousedown, mouseup, click, dblclick
这个其实不是问题。你的双击必然会触发二次单击的操作。解决思路是点击操作增加定时判断。
