### ISSUE TITLE
el-tab-pane does not take into account el-tabs from an other component

### ISSUE THREAD

**Issue by Sancho66** [ElemeFE/element#1819]
Hello Guys , I have a problem with your Tab element. I use your el-tabs in a my main component , but I can not use your el-tab-pane in other component like this :
My main component :

```
<el-tabs type="card" :closable="true">
<el-tab-pane label="User">User</el-tab-pane>
<tab-client name="Nouveau client"></tab-client>
</el-tabs>

```
Note : el-tab-pane "User" is good rendered

My template in tabClient component :

```
<template>
<div>
    <el-tab-pane label="Nouveau client">test</el-tab-pane>
 </div>
</template>
```
Note : The label of the tab is not displayed and is rendered as "```<div class="el-tabs__item is-active"></div>```" without none content.

I thinks el-tab-pane component include in other component does not take in account the el-tabs. Can you fix this issue ?
Thanks

**Comment by baiyaaaaa** [comment]
hi bro, it's not the desirable using way of the tabs component. why do u want to use this？

**Comment by Sancho66** [comment]
Indeed , I can insert my component into the el-tab-pane. 

Other question : is it possible to set "closable" feature only  at one el-tab-pane (and not at all )  ?

Thanks

**Comment by baiyaaaaa** [comment]
is it possible to set "closable" feature only at one el-tab-pane (and not at all ) ? yes, u can.

**Comment by NoahCardoza** [comment]
Out of curiosity why isn't this desirable? I feel that would be much more convenient since you could keep all of the tab configurations in one file. Is there any way around this without having to keep the `el-tabs` and `el-tab-pane` in one component?

**Comment by redoc123** [comment]
Would nt it be much organized if you render tabs in same file and componentize the tab content instead of doing this. 

Sample of what I mean...

```
<el-tabs>
 <el-tab-pane v-for="(tab, index in tabs)" :key="index" :label="tab.label" name="tab.name">
   <component :is="tab.component" @bind="blah">
 </el-tab-pane>
</el-tabs>
```

??

**Comment by Erbenos** [comment]
While proposed way does work, I think it would make sense to add to documentation mention of the fact, that you can't use <el-tab-pane> the way @Sancho66 is introducing.

**Comment by HY0606** [comment]
What did you do about it, buddy @Sancho66

**Comment by funderbenz** [comment]
> <el-tabs>
>  <el-tab-pane v-for="(tab, index in tabs)" :key="index" :label="tab.label" name="tab.name">
>    <component :is="tab.component" @bind="blah">
>  </el-tab-pane>
> </el-tabs>

Thanks man! I wasn't aware of the component tag, this solution works great in my case, where I have some "static" panes, and others dynamic... I will render them like you  suggested.

Vue always amazes me. Every day I discover something new and very useful! 
I think I'm in love :)

**Comment by kevrousso** [comment]
I would also like to be able to wrap the el-tab-pane in it's own component to keep configs in one place. Please reopen! @baiyaaaaa

**Comment by funder7** [comment]
@M1CK431 some time has passed, but I'm pretty sure that setting current-name property was not working right.  Maybe I didn't try to set current-name, but only the v-model on el-tabs, what I remember is that dynamically loaded tabs were not responding to programmatic active tab update! That was in september '19, maybe with newer versions the behaviour is different, idk.

**Comment by Kayeeec** [comment]
> hi bro, it's not the desirable using way of the tabs component. why do u want to use this？

My 2 cents: I have a page that contains few tabs. Each tab contains a table with some data fetched from API. The tab header should contain a badge with the number of rows in its table. If I have the whole tab as a separate component, I can have the data fetching functionality inside that tab component and not in the parent, which is much cleaner design in some cases IMHO. 

Could this issue be reopened?
