### ISSUE TITLE
[Tabs]无法自定义标签样式

### ISSUE THREAD

**Issue by unique542** [ElemeFE/element#1820]
Tab-pane中使用官方文档中提到的label-content无法获取上下文，实现自定义样式，比如我想在某些标签中加入扳手图标，作为修改标记。希望可以在function（h）方法后加入参数，获取：label属性绑定的数据。

**Comment by Fucntion** [comment]
关于tabs的使用问题，我觉得我们需求类似。希望沟通271938312@qq.com

**Comment by unique542** [comment]
@Fucntion 需要和我沟通什么？我觉得我们需要和开发人员沟通吧……

**Comment by baiyaaaaa** [comment]
你的意思是可以在function（h）里加入 tab 的 this 参数么？

**Comment by unique542** [comment]
@baiyaaaaa 不一定要加入this吗，我看一些issues中提到在外层上加入v-model，那可以把这个值当参数传回来吗，实在不行最起码传一个label回来。

**Comment by stackia** [comment]
http://codepen.io/jsq2627/pen/JbxOOo
猜测楼主说的是这种情况。因为没有上下文环境，不能根据 v-for 的内容来确定渲染什么。

**Comment by stackia** [comment]
先提供一个 hack 方法供使用
http://codepen.io/jsq2627/pen/GNzOym

**Comment by baiyaaaaa** [comment]
@unique542 支持了 #1857

**Comment by unique542** [comment]
感谢@stackia 提供的hack方法和@baiyaaaaa的支持
