### ISSUE TITLE
[bug report] El table is hidden by v-show and then displayed. The width property is invalid

### ISSUE THREAD

**Issue by Aprilday** [ElemeFE/element#18210]
### Element UI version
2.2.2

### OS/Browsers version
macOS 10.15.1 / chrome 78

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/aprilday/va7ewmzp/8/

### Steps to reproduce
先点击hide按钮隐藏表格，然后再按show按钮显示表格；

### What is Expected?
表格宽度和隐藏前相同

### What is actually happening?
宽度错乱

**Comment by frknasir** [comment]
Probably the problem is not with el table but with how v-show behaves....substituting v-show with v-if produces the expected behaviour. hope that helps.
