### ISSUE TITLE
[feature request] can the image preview function realize the specified initial location

### ISSUE THREAD

**Issue by xxwangkaimin** [ElemeFE/element#18222]
### Existing Component
是

### Component Name
Image

### Description
当有多个图片进行预览时，总是从第一张开始预览，能否实现一个公共的方法，进行预览图片，可以指定预览的开始位置。类似vant-ui预览图片指定开始位置的功能，参考地址https://youzan.github.io/vant/#/zh-CN/image-preview

**Comment by shenshou** [comment]
+1 一样的需求
