### ISSUE TITLE
[Pagination]建议增加参数，以便样式调整

### ISSUE THREAD

**Issue by wucuida** [ElemeFE/element#1823]
### ElementUI version
1.0

### What is Expected?
希望pagination可以提供固定显示的页数
### What is actually happening?
当数据总数不确定时，有可能只有1页，也有可能有10页，当有10页数据显示时，pagination居中，但当数据只有1页时，整个pagination会偏左，样式难调整。现在默认多于7页隐藏，希望提供参数能更改当页数大于x页时隐藏。

**Comment by Leopoldthecoder** [comment]
想居中的话给 `.el-pagination` 加一条 `text-align: center;` 就可以
