### ISSUE TITLE
[Bug Report] when el-image in  a scrolling div. Left clik the image will lead to the page can't scroll 

### ISSUE THREAD

**Issue by zzxCNCZ** [ElemeFE/element#18234]
### Element UI version
2.13.0

### OS/Browsers version
chrome 78.0.3904.108

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zzxcncz/pen/LYYwOXo

### Steps to reproduce
click the image ,then the page can't scroll

### What is Expected?
click the image ,then the page can scroll

### What is actually happening?
click the image ,then the page can scroll.
i fock the code from the element ui website.The demo of the component in the website can also lead the result. Just click the image ,and chage to other page.Then the other page can't scroll. 
i found the reason is when i click the image in a scrolling div. it will add a css in <body>.the css is over-flow: hidden.

**Comment by zzxCNCZ** [comment]
if i don't need  preview the image, the click handler will also add a body style overflow = 'hidden'.
this will lead to i can't scroll the page.
the el-image's click handler  code.
```
clickHandler() {
        // prevent body scroll
        prevOverflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';
        this.showViewer = true;
      },
```

**Comment by zzxCNCZ** [comment]
i think add the following code  will  handle it
```
    clickHandler () {
      if (this.previewSrcList.length > 0) {
        // prevent body scroll
        prevOverflow = document.body.style.overflow
        document.body.style.overflow = 'hidden'
        this.showViewer = true
      }
    },

```

**Comment by zw8677174** [comment]
I get this problem too. it seems to make image-viewer run. but haven't check for i had not set preview-src-list.

**Comment by ZNspace** [comment]
Also encountered this problem.

**Comment by hooray** [comment]
same problem

**Comment by viulu5824** [comment]
Same problem

**Comment by DevBrent** [comment]
I am finding el-image-viewer to activate when clicking simple el-images without any preview sources causing the body to have overflow: hidden. I found the change was implemented 2 months ago to fix an image-preview bug.

@luckyCao @island205 Please correct this regression. As soon as any image is clicked, we now permanently and irreversibly get a body { overflow: hidden } attribute added breaking page scrolling.... https://codepen.io/zzxcncz/pen/LYYwOXo

**Comment by DevBrent** [comment]
This PR may resolve this bug.....
https://github.com/ElemeFE/element/pull/18416

**Comment by luckyCao** [comment]
#19075

**Comment by cs1707** [comment]
fixed
