### ISSUE TITLE
[bug report] when El image uses large preview mode, if STR does not exist in the list, it will be blank

### ISSUE THREAD

**Issue by dnyz520** [ElemeFE/element#18255]
### Element UI version
2.13.0

### OS/Browsers version
windows7/Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
<div class="demo-image__preview">
  <el-image 
    style="width: 100px; height: 100px"
    :src="url" 
    :preview-src-list="srcList">
  </el-image>
</div>

<script>
  export default {
    data() {
      return {
        url: 'https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg',
        srcList: [
          'https://fuss10.elemecdn.com/8/27/f01c15bb73e1ef3793e64e6b7bbccjpeg.jpeg',
          'https://fuss10.elemecdn.com/1/8e/aeffeb4de74e2fde4bd74fc7b4486jpeg.jpeg'
        ]
      }
    }
  }
</script>

1."url"地址在"srcList"中不存在,在element-ui\packages\image\src\main.vue函数"imageIndex"中简单使用indexOf进行查找,而不进行判断,如果不存在则返回"-1",这谁改的,简直弱智.

前端显示,使用小图的时候肯定是缩略图,实际的大图就是完整尺寸的图,二者地址肯定不一样.

2.大图预览结束后再点一张缩略图,实际显示的是大图预览最后查看的图,而不是实际点开的这张图.

### What is Expected?
1.点击大图预览模式时只需要获取index,对list进行调整就可以.
  if (!Array.isArray(srcList) || !srcList.length) {
    return []
  }

  const before = srcList.slice(index)
  const image = before.concat(srcList.slice(0, index))

2.通过上诉方法,缩略图与点击打开的大图预览完全一致

### What is actually happening?
没有

**Comment by csvwolf** [comment]
Duplicated #18323
