### ISSUE TITLE
[bug report] table setting dynamic height or max height failure

### ISSUE THREAD

**Issue by hanxiaosss** [ElemeFE/element#18267]
### Element UI version
2.9.2

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/hanxiaosss/pen/rNaNVOX?editors=1111

### Steps to reproduce
<el-table :data="table" border style="width: 100%" class="tabTable" :height="tableHeight"></el-table>

mounted() {
 tableHeight: window.innerHeight - x
  },

### What is Expected?
表格高度为新赋值数据

### What is actually happening?
始终为默认初始值

**Comment by jingchenxu** [comment]
可以在table组件的$nextTick中修改表单高度，注意是在table组件的$nextTick @hanxiaosss
