### ISSUE TITLE
[Bug Report]  Text cursor size too large on iOS

### ISSUE THREAD

**Issue by crosskpixel** [ElemeFE/element#18260]
### Element UI version
2.12.0

### OS/Browsers version
iOS 13.1.3 / Safari 

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce

just open the field and notice that the cursor bar is too big

### What is Expected?

make it possible to make this full-size cursor bar size on Apple / iOS devices

### What is actually happening?

Cursor size not suitable for input dimensions

**Comment by csvwolf** [comment]
Element is not a mobile UI framework, so I think no need to fix it?

**Comment by iamkun** [comment]
Element is designed for desktop. It's not compatible with mobile devices. FYI: https://github.com/vuejs/awesome-vue#mobile-1
