### ISSUE TITLE
[bug report] open the drawer title, there will be a focus box by default

### ISSUE THREAD

**Issue by allce231** [ElemeFE/element#18270]
### Element UI version
2.13.0

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/r4g8esm9/

### Steps to reproduce
打开 drawer 标题默认会有一个focus框

### What is Expected?
打开 drawer 标题默认会有一个focus框

### What is actually happening?
打开 drawer 标题默认会有一个focus框

![image](https://user-images.githubusercontent.com/5996940/69939653-615ce680-151b-11ea-8aa8-a3c0cf753562.png)

**Comment by MBearo** [comment]
[link](https://github.com/ElemeFE/element/blob/6ec5f8e900ff698cf30e9479d692784af836a108/packages/drawer/src/main.vue#L137) 
```javascript
this.$nextTick(() => {
  Utils.focusFirstDescendant(this.$refs.drawer);
});
```
 发现把这一行去掉就可以了，但是不知道为什么这么写

**Comment by lowerfish** [comment]
> [link](https://github.com/ElemeFE/element/blob/6ec5f8e900ff698cf30e9479d692784af836a108/packages/drawer/src/main.vue#L137)
> 
> ```js
> this.$nextTick(() => {
>   Utils.focusFirstDescendant(this.$refs.drawer);
> });
> ```
> 
> 发现把这一行去掉就可以了，但是不知道为什么这么写

[这个提交](https://github.com/ElemeFE/element/commit/068b3ad1b0f76233f84ae8fdceecc1dd10c1f25e#diff-469c38047d15e4d4ef12ac90ecb86a7fR136)的锅，解决了一个bug，并生成了一个新的bug。😄

**Comment by MBearo** [comment]
> > [link](https://github.com/ElemeFE/element/blob/6ec5f8e900ff698cf30e9479d692784af836a108/packages/drawer/src/main.vue#L137)
> > ```js
> > this.$nextTick(() => {
> >   Utils.focusFirstDescendant(this.$refs.drawer);
> > });
> > ```
> > 
> > 
> > 发现把这一行去掉就可以了，但是不知道为什么这么写
> 
> [这个提交](https://github.com/ElemeFE/element/commit/068b3ad1b0f76233f84ae8fdceecc1dd10c1f25e#diff-469c38047d15e4d4ef12ac90ecb86a7fR136)的锅，解决了一个bug，并生成了一个新的bug。😄

看起来像是有a11y的需求？

**Comment by qianjin1017** [comment]
.el-drawer > header > span:focus {
  outline-color: white;
}
.el-drawer > header > button:focus {
  outline-color: white;
}
.el-drawer > header > button:hover {
  color: rgb(64, 158, 255);
}

**Comment by skyzhao1223** [comment]
同样遇到此问题，忘修复

**Comment by csxiaoyaojianxian** [comment]
同样遇到此问题，望修复

**Comment by NateScarlet** [comment]
在github上这种没有内容的回复请在一楼用 +1表态代替 issus搜索时还能按表态数排序
回复会给所有订阅者发邮件提醒的

**Comment by MaxsionLiu** [comment]
如果把头部隐藏了 下面有button的话 也会有同样的问题？这个时候怎么改？现在暂时前面加了input 然后设置透明了，有更好的方法吗 大佬 @qianjin1017

**Comment by sunceenjoy** [comment]
span:focus
    pointer-events: none;
    outline: none !important;

**Comment by waiting0729** [comment]
@liushuiyuan001 hi, 我也遇到了相同的问题，头部隐藏了，drawer下面有button，请问你是怎么解决的？

**Comment by he5vely** [comment]
修复了吗?

**Comment by CHENJIAMIAN** [comment]
`
#el-drawer__title > span {
  outline: 0;
}
`

**Comment by cs1707** [comment]
Duplicate of #19902
