### ISSUE TITLE
datetimepicker日期选择不高亮

### ISSUE THREAD

**Issue by reverland** [ElemeFE/element#1827]
### OS/Browers version
macOS/Chrome 54

### Vue version
2.1.3

### Reproduction Link
官网示例

### Steps to reproduce
选择2019年12月某日

### What is Expected?
选中项立即高亮

### What is actually happening?
选中项未高亮，在panel关闭时才高亮

**Comment by reverland** [comment]
好像跨年选择就不高亮了＝ ＝

**Comment by QingWei-Li** [comment]
![image](https://cloud.githubusercontent.com/assets/7565692/21304299/3504b57c-c5ff-11e6-80da-c03827f3fe04.png)
没看懂，我这选择是高亮的（除了已知 bug 无法点击确定）

**Comment by reverland** [comment]
datetimepicker,不是范围选择

**Comment by reverland** [comment]
![screenshot from 2016-12-19 16-59-29](https://cloud.githubusercontent.com/assets/1418726/21306552/8bfb025c-c60c-11e6-9035-844cc671e66d.png)

观望例子，看时间和高亮。

**Comment by reverland** [comment]
时间范围那无法点击确定么。。。你们现在在产品中用element么，感觉好虚。。

**Comment by reverland** [comment]
似乎因为 this,week没更新，导致date-table没有把current类加到选中项上
不确定
