### ISSUE TITLE
[bug report] in Chrome browser, when the drawer is opened, the title will get the focus (blue box will be displayed)

### ISSUE THREAD

**Issue by Sean-214** [ElemeFE/element#18279]
### Element UI version
2.13.0

### OS/Browsers version
Win10 / Chrome v78

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/sean-214/pen/yLyLwvJ

### Steps to reproduce
官网的示例：即可重现，点"点我打开"按钮。

### What is Expected?
标题没有获取焦点时的蓝框

### What is actually happening?
标题有获取焦点时的蓝框

**Comment by MBearo** [comment]
https://github.com/ElemeFE/element/issues/18270 同一个问题

**Comment by pyygithub** [comment]
the same problem

**Comment by qianjin1017** [comment]
同上

**Comment by qianjin1017** [comment]
.el-drawer > header > span:focus {
  outline-color: white;
}
.el-drawer > header > button:focus {
  outline-color: white;
}
.el-drawer > header > button:hover {
  color: rgb(64, 158, 255);
}

**Comment by xiangzi1** [comment]
可以回退到2.12.0版本

**Comment by cs1707** [comment]
Duplicate of #19902

**Comment by cs1707** [comment]
Duplicate of #19902
