### ISSUE TITLE
自定义主题的文档建议修改下

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1828]
1. 文档已经不对了
比如:
```
et -i [可以自定义变量文件目录]
````
实际上et -i后面应该加 [自定义变量文件]，如果是文件夹的话，会报错

```
et -i element-variables.css
```
文件名称还必须是element-variables.css, 否则后面执行et去生成主题时会报错。

<img width="226" alt="2016-12-19 11 18 21" src="https://cloud.githubusercontent.com/assets/13174059/21300200/e8551892-c5dc-11e6-975f-3215222d996c.png">

**Comment by reverland** [comment]
有没有像我一样把theme-default fork出来，然后用webpack来打包。。

**Comment by njleonzhang** [comment]
@reverland 这样比较好啊  交出你的代码吧

**Comment by QingWei-Li** [comment]
不一定要 `element-variables.css` 命名的，可以是任意名字

**Comment by njleonzhang** [comment]
<img width="687" alt="2016-12-19 12 26 19" src="https://cloud.githubusercontent.com/assets/13174059/21301207/61f2fdfa-c5e6-11e6-83be-fb8ac29ff1fd.png">

@QingWei-Li   R U sure？

**Comment by QingWei-Li** [comment]
@njleonzhang `test` 不是文件名，你应该是 `test.css`

**Comment by reverland** [comment]
@njleonzhang fork出来，然后npm install。。。，js里直接引用theme-default/src/index.css就好

当然vue-popup得装上

**Comment by njleonzhang** [comment]
@QingWei-Li  test是文件名， folder被我删了。你们代码里应该写死了`element-variables.css`

<img width="601" alt="2016-12-19 1 38 05" src="https://cloud.githubusercontent.com/assets/13174059/21302285/93eb5ae6-c5f0-11e6-9db8-12aecabe58c8.png">

**Comment by njleonzhang** [comment]
@reverland  哦  明白了

**Comment by QingWei-Li** [comment]
@njleonzhang `et -c test.css`
![image](https://cloud.githubusercontent.com/assets/7565692/21302364/285f1bfe-c5f1-11e6-8160-831f2b4a452b.png)

**Comment by reverland** [comment]
@njleonzhang 还得配postcss-salad。。
