### ISSUE TITLE
[Bug Report] el-image add Animation(transition) does not achieve the desired effect

### ISSUE THREAD

**Issue by afacode** [ElemeFE/element#18280]
### Element UI version
2.4.5

### OS/Browsers version
Darwin chrome 版本 78.0.3904.87（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/afacode/zLd76khp/2/

### Steps to reproduce
el-image 添加transform: scale(1.1)动画，点击图片，切换

### What is Expected?
点击图片预览正常

### What is actually happening?
点击图片无法预览，会有闪烁情况

**Comment by xrkffgg** [comment]
我这里点击正常啊
