### ISSUE TITLE
[bug report] after selecting the El cascade panel, the 2 / 3 panel is not hidden

### ISSUE THREAD

**Issue by yw8820** [ElemeFE/element#18292]
### Element UI version
2.13.0

### OS/Browsers version
谷歌

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
el-cascader-panel 选择完之后，没有隐藏2/3级面板

### What is Expected?
el-cascader-panel 选择完之后，隐藏隐藏2/3级面板

### What is actually happening?
el-cascader-panel 选择完之后，没有隐藏2/3级面板

**Comment by linyq1874** [comment]
同问，目前的项目也是遇到这个问题。
