### ISSUE TITLE
[Feature Request] Add a slot in the nav of tabs

### ISSUE THREAD

**Issue by mickaelchanrion** [ElemeFE/element#18302]
### Existing Component
Yes

### Component Name
Tabs

### Description
It would be very nice to have a slot in the nav of the tabs. So we can add extra content like a menu or a button. I actually need this for a project.
Here is an example: 
https://www.antdv.com/components/tabs/#components-tabs-demo-extra-content

**Comment by mojiQAQ** [comment]
i agree with you.
