### ISSUE TITLE
Default openeds of [bug report] El menu cannot be set to array

### ISSUE THREAD

**Issue by nikoohp** [ElemeFE/element#18309]
### Element UI version
2.13.0

### OS/Browsers version
window 10 / chrome 78.0.3904.108

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/nikoohp/pen/jOEPVQv

### Steps to reproduce
修改default-openeds值的类型为 数组 或 数组字符串

### What is Expected?
default-openeds的值使用数组能展开菜单

### What is actually happening?
将default-openeds的值修改为数组字符串之后，可以展开但是会报：[Vue warn]: Invalid prop: type check failed for prop "defaultOpeneds". Expected Array, got String with value

**Comment by MBearo** [comment]
文档里写明了default-openeds要Array类型

**Comment by nikoohp** [comment]
@MBearo Array  没有默认展开
