### ISSUE TITLE
[Select]增加显示/隐藏事件

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#1831]
在多选模式下，有需求为：选择完成后执行后续动作。

但是现在的 select 组件只有 `change` 事件，该需求即无法简单的实现。
查阅源码，有对 `visible` 的监听。那么如果能够在这里添加一个事件的话就好了。希望考虑一下

![select-visible](https://cloud.githubusercontent.com/assets/2276421/21300928/832522ee-c5e3-11e6-8837-d523a345b7de.png)

**Comment by stackia** [comment]
http://codepen.io/jsq2627/pen/jVdaJX
提供一种临时的解决思路

不过我认为还是为 el-select 加上 on-select 事件比较好

**Comment by renxia** [comment]
@stackia 你的 demo 和我描述的需求不同。我的需求是，多选模式下，在选择完成后，才继续后续操作。
选择完成后的标志就是关闭 dropdown。

你说的 on-select 的示例，change 事件本身就可以满足需求，没有必要再加一个 on-select

**Comment by Leopoldthecoder** [comment]
Added in #1849
