### ISSUE TITLE
Nested input box in [bug report] Popover, traversing output, input focus failure

### ISSUE THREAD

**Issue by Wuboing** [ElemeFE/element#18312]
### Element UI version
2.13.0

### OS/Browsers version
deepin 15.11

### Vue version
2.6.10

### Reproduction Link
 https://elementui.github.io/issue-generator

### Steps to reproduce
将 el-popover插入 el-tree中,为每行做修改编辑,点击修改按钮时,在input中获取焦点时,获取不到,
1.使用自带 autofocus属性只能获取刚刷新的一次,第二次后就会失效;
2.使用ref获取焦点时,直接获取不到焦点
this.$nextTick(function () {
          //DOM 更新了
          this.$refs.inputVal.focus();
        });
可能在popover中回和el-input起冲突

### What is Expected?
解决在el-popover 中 el-input聚焦问题

### What is actually happening?
未解决聚焦问题

**Comment by dabinding** [comment]
You can solve this by adding the following code:
```
this.$nextTick(() => {
          // DOM updated
          this.$refs.forminput.focus()
        })
```
