### ISSUE TITLE
[Bug Report] Popover is not positioned correctly if visible on load

### ISSUE THREAD

**Issue by Tofandel** [ElemeFE/element#18319]
### Element UI version
2.13.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/4zmef6bh/

### Steps to reproduce
Create a popover that is visible by default (by setting `trigger="manual"` and `:value="true"`)

### What is Expected?
The popover should be correctly positioned next to the reference
![image](https://user-images.githubusercontent.com/6115458/70257008-d46b9480-1789-11ea-8026-7f53968e6a96.png)

### What is actually happening?
When the popover loads it is over the reference making it unreadable, instead of being positioned on the right
![image](https://user-images.githubusercontent.com/6115458/70256986-cae22c80-1789-11ea-8625-ed0f254fe46a.png)

**Comment by kanouken** [comment]
` this.$nextTick(()=>{
        this.visible = true
    })` 
it works
