### ISSUE TITLE
[bug report] automatic dropdown of El select in version 2.13.0

### ISSUE THREAD

**Issue by willww64** [ElemeFE/element#18328]
### Element UI version
2.13.0

### OS/Browsers version
Archlinux / Chromium & Firefox

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/willww64/pen/MWYaKKy

### Steps to reproduce
鼠标第一次点击 select，会闪现一下就马上收起，需要再点一下才会展开。然后恢复正常，点一次即可展开，再点一次收起。
但是如果点了其他部分（如 codepen 链接中的空白区域），再去点 select，又会重复第一次点击时的闪现现象。

### What is Expected?
不应该闪现，点一次即展开，无需点两次。

### What is actually happening?
闪现，需点两次。

**Comment by willww64** [comment]
Additional information:
This issue happens only when you click the select box body. It behaves normal when click the arrow icon on the right.

**Comment by willww64** [comment]
Any attention here?

**Comment by stephsavoie** [comment]
Bump.
That would be nice to get this issue solved...

**Comment by xibieni** [comment]
According to the code, add filterable property temporarily.
