### ISSUE TITLE
[bug report] image component cannot preview large image

### ISSUE THREAD

**Issue by liruidong1** [ElemeFE/element#18323]
### Element UI version
2.13.0

### OS/Browsers version
谷歌

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/

### Steps to reproduce
重现链接随便写的，官网也能看到效果 https://element.eleme.cn/#/zh-CN/component/image 官网的组件就能看这个问题，大图预览效果就可以查看到了。

### What is Expected?
大图预览时加载出来大图

### What is actually happening?
大图预览时未加载出大图

**Comment by csvwolf** [comment]
Related: https://github.com/ElemeFE/element/pull/18285/files

**Comment by liamwang** [comment]
Any update on on this? Reverted back to 2.12 for now.

**Comment by luckyCao** [comment]
#18975
