### ISSUE TITLE
[Bug Report] Custom component with el-table-columns: columns are displayed in the wrong order

### ISSUE THREAD

**Issue by ton77v** [ElemeFE/element#18335]
### Element UI version
2.13.0

### OS/Browsers version
Any

### Vue version
2.6.10

### Reproduction Link
http://jsfiddle.net/vbu2he80/7/

### Steps to reproduce
Create a custom component with el-table-columns inside
Add it to a table

### What is Expected?
The columns order is as specified
In the fiddle it should be: Date, Name, Address

### What is actually happening?
The order is different. 
In the fiddle it actually is: Name, Address, Date

Seems there was a similar issue already solved: https://github.com/ElemeFE/element/issues/1638

**Comment by ton77v** [comment]
As temporary solution I've tried this: https://github.com/ElemeFE/element/issues/1638#issuecomment-349989437

But it isn't working also

**Comment by jipengju-GitHub** [comment]
I have the same problem
