### ISSUE TITLE
[bug report] table component fixed column, from the page without horizontal scroll bar to the page with horizontal scroll bar, change the page again so that the scroll bar does not appear. Extra lines appear in the table.

### ISSUE THREAD

**Issue by cpxGithub** [ElemeFE/element#18338]
### Element UI version
2.12.0

### OS/Browsers version
window 10/Google Chrome 71.0.3578.98

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/cpxgithub/pen/gObPPRZ

### Steps to reproduce
1.设置table组件fixed属性，设置表格高度。浏览器全屏显示，整个内容区未出现水平滚动条
2.变化浏览器窗口，使内容区出现水平滚动条（注：要需要一变化马上出现水平滚动条）
3.浏览器全屏显示，内容区水平滚动条消失，表格底部出现多余滚动条
查看源码发现：fixed表格高度由fixedHeight属性设置。通过监听resize事件，控制表格显示大小，当出现水平滚动条时，fixed表格高度等于表格高度减去滚动条高度。而判断是否出现水平滚动条函数（updateColumnsWidth）却是在更新表格高度函数（updateElsHeight）后面执行，导致这种情况出现。修改table.vue组件中函数为：
doLayout() {
        this.layout.updateColumnsWidth();
        if (this.shouldUpdateHeight) {
          this.layout.updateElsHeight();
        }
      },

### What is Expected?
不出现多余线条

### What is actually happening?
出现多余线条

**Comment by gideonpeters** [comment]
any update on this?
