### ISSUE TITLE
Typo in menu.vue

### ISSUE THREAD

**Issue by donlzx** [ElemeFE/element#1833]
### ElementUI version
1.0.7

### Typo in source code

Missing a '$' in [handleSelect() function](https://github.com/ElemeFE/element/blob/master/packages/menu/src/menu.vue#L100) in packages/menu/src/menu.vue

```
if (this.router && route) {
}
```
should be
```
if (this.$router && route) {
}
```

**Comment by baiyaaaaa** [comment]
router是组件参数而不是vue-router里面的注册对象
