### ISSUE TITLE
[bug report] the tree component cannot trigger the 'current change' signal through 'setcurrentnode' or 'setcurrentkey'

### ISSUE THREAD

**Issue by 625781186** [ElemeFE/element#18337]
### Element UI version
2.10.0

### OS/Browsers version
win10/chrome 71

### Vue version
2.6.10

### Steps to reproduce
客户端代码 , 上传太麻烦.

1 .选中子节点 , 顶部按钮是会被禁用 . √
![image](https://user-images.githubusercontent.com/30521429/70397953-7e307700-1a51-11ea-8558-3775adfe33b8.png)

2. 在部件列表 点击顶部 按钮 ,新增子节点  , 同时`setCurrentKey` 为当前子节点 id.
![image](https://user-images.githubusercontent.com/30521429/70397967-93a5a100-1a51-11ea-84ca-ab0e895f884d.png)

通过`getCurrentNode` 发现确实设置了子节点 为当前节点 ; 
但是`current-change ` 信号未发出.

查看源码发现只有鼠标点击的时候才发出.
![image](https://user-images.githubusercontent.com/30521429/70415734-4c8ece80-1a98-11ea-9e42-a13eb591f507.png)

不知道这算不算bug.

### 希望达到的效果:
1. 通过`setCurrentKey`修改当前节点 的时候 旧节点的 `选中` 效果没被修改 , 希望被修改 ;
![image](https://user-images.githubusercontent.com/30521429/70398021-1e869b80-1a52-11ea-912a-6c65a4964d26.png)

2. 发出`current-change` 信号.

-

**Comment by 625781186** [comment]
在 https://github.com/ElemeFE/element/issues/10871

**Comment by 625781186** [comment]
解决办法 :
`$(".is-current").click();`

不过还有bug : 
'setcurrentkey'之后 旧节点还'hover' 着导致 背景色残留.

**Comment by Supertramplee** [comment]
@625781186    你这是把jquery揉进去了嘛？..  
`$(".is-current").click();`

**Comment by 625781186** [comment]
> @625781186 你这是把jquery揉进去了嘛？..
> `$(".is-current").click();`

是的 , 可以用原生js

**Comment by Supertramplee** [comment]
> > @625781186 你这是把jquery揉进去了嘛？..
> > `$(".is-current").click();`
> 
> 是的 , 可以用原生js



> 解决办法 :
> `$(".is-current").click();`
> 
> ### 不过还有bug (可能是客户端(pyqt) bug ) :
> 'setcurrentkey'之后 旧节点还'hover' 着导致 背景色残留.
> 
> ![image](https://user-images.githubusercontent.com/30521429/70415848-8c55b600-1a98-11ea-9163-ca2036935ba5.png)

你看看activeElement， 如果是在树上的话取消一下就不会有这个问题了
`document.activeElement.blur();`
