### ISSUE TITLE
[Bug Report] Disabling option in multiple select does not work

### ISSUE THREAD

**Issue by mPyth** [ElemeFE/element#18346]
### Element UI version
2.13.0

### OS/Browsers version
OS: Windows 10; Browser 1: Firefox 71.0;  Browser 2: Chrome 78.0;

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/hfc3jrg9/1/

### Steps to reproduce
Just run example in reproduction link and click on multiple select and see "Option3" is not disabled.

### What is Expected?
"Option3" in reproduction link should be disabled, but is is not. It should be grayed out and not possible to select, but that's not the case.

### What is actually happening?
"Option3" is not disabled.

**Comment by lynhao** [comment]
try this way， it works
```
    <el-option
      v-for="item in options"
      :key="item.value"
      :label="item.label"
      :value="item.value"
      :disabled="item.label==='Option1'">
    </el-option>
```

**Comment by mPyth** [comment]
it's my mistake - I was pretty sure that I copied example from single select component, but it was not the case.
@lynhao - sorry for disturbing.
