### ISSUE TITLE
bug:1.0.7版本的element的日期选择器的computed触发bug

### ISSUE THREAD

**Issue by LianyForWeb** [ElemeFE/element#1834]
elemen@1.0.7和vue@2.1.6联用时日期选择器会在打开组件和选定日期后时v-model都触发会computed,按道理应该只有选定日期后才会computed吧,没办法只有回滚elemen@1.0.3和vue@2.0.1了

**Comment by furybean** [comment]
没看懂，请提供一个可以重现的用例。

**Comment by stackia** [comment]
@furybean 
```html
<el-date-picker type="daterange" v-model="dateRange"></el-date-picker>
```

```javascript
{
...
  data: { dateRange: [] },
  watch: {
    dateRange () {
      console.log('changed')
    }
  }
...
}
```

我也遇到了类似的问题。上面的代码，只要点击打开日期选择器，无论选不选日期都会立即输出 changed

**Comment by stackia** [comment]
发现如果选了日期，然后点 X 图标清空日期，会触发两次 changed，第一次值为空字符串，第二次为数组 [null, null]

现在目前没有非常可靠的方式在外部检测选择的日期是否发生变化。暂时只能在 watch/computed 函数里面人工检查：
1. 是否为空
2. 是否为 [null, null]
3. 是否和旧的值逻辑相等（newDate.getTime() === oldDate.getTime()）
全部为否时才可以认为选择的日期发生了变化
