### ISSUE TITLE
升级最近版本后 table 表头 border-bottom 消失

### ISSUE THREAD

**Issue by zhangshuaigit123** [ElemeFE/element#18365]
![image](https://user-images.githubusercontent.com/20475096/70590647-4de20780-1c0e-11ea-971d-c46f1e93fa2b.png)
boder 消失

**Comment by lizhen789** [comment]
跟我发现的一样，只要给table设置一个margin-top:10px就好了，下边框也会出现，设置一下也好了

**Comment by yuguaa** [comment]
> 跟我发现的一样，只要给table设置一个margin-top:10px就好了，下边框也会出现，设置一下也好了

LGTM!!!!!!!!!
