### ISSUE TITLE
[Feature Request] Expect to optimize and improve the image preview function

### ISSUE THREAD

**Issue by viulu5824** [ElemeFE/element#18361]
### Existing Component
Yes

### Component Name
2.13.0  el-image组件

### Description
chrome Version 78.0.3904.108

### Current problems

1. If the SRC of the el-image component does not match the preview-src-list item, the preview image will be blank
1.如果el-image组件的src与preview-src-list中不匹配，则预览图像将为空白

2.Clicking el-image, whether or not there is a preview-src-list, causes the body element scrollbar to disappear
2.无论是否有预览preview-src-list，单击el-image都会导致body元素滚动条消失

3.When you click el-image to preview, the preview-src-list always displays the first preview image,it does not display the current
3.点击el-image进行预览时，preview-src-list总是显示第一张预览图片，而不会显示当前点击的图片

### Expect
Images no longer rely on the "preview-src-list" attribute, which makes them difficult to develop, maintain, and actually use.
I want to assign two new properties to el-image: "prev-src" and "prev-group".
"Prev-src" represents the "SRC" attribute of the el-image preview image, and "prev-group" represents the group name of the el-image preview image.
This extensibility is very strong, other preview gallery is also configured in this way
Now the image preview is really hard to use!

el-image预览图片不再依赖"preview-src-list"属性，这样无论开发维护还是实际应用都很困难。
希望能给el-image分配两个新属性：“prev-src”和"prev-group"
“prev-src”代表el-image预览图片的"src"属性,"prev-group"代表el-image预览图片所在分组名称。
这样扩展性很强，其他的预览图片库也大都是这样配置
现在的图片预览实在是太难用了！

**Comment by Joanna0001** [comment]
更新到最新版本2.13.2就好了

**Comment by zazzaz** [comment]
YES! 🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉

element-plus/element-plus#147
