### ISSUE TITLE
[Bug Report] Table: selection position inconsistency

### ISSUE THREAD

**Issue by xrkffgg** [ElemeFE/element#18363]
### Element UI version
2.13.0

### OS/Browsers version
Win10 Chrome78

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xrkffgg/pen/yLyOPvx?editors=1010

### Steps to reproduce
- 打开链接
- 可以发现 表头 和 表内 selection 的位置不对应

### What is Expected?
 selection 的位置 对齐

### What is actually happening?
 selection 的位置 不对齐

**Comment by luyebai** [comment]
type=”index“的列在使用v-if动态展示的时候，隐藏再显示数据就变成空的了。

**Comment by sbyps** [comment]
+1 https://github.com/ElemeFE/element/pull/17284/files 此修改引入

**Comment by CarterLi** [comment]
element里面CSS的优先级特别混乱。他们想把所有复选框的padding改大点，但是表头的样式被覆盖掉了，所以就表头的checkbox的padding小

![image](https://user-images.githubusercontent.com/6134068/77625217-270dce00-6f7e-11ea-9346-ebc5ade80f26.png)

穿梭框的line-height问题类似

**Comment by xrkffgg** [comment]
这玩意好像没人维护了。。。。

**Comment by CarterLi** [comment]
这是我们公司自己维护的仓库，可以看看 https://github.com/EOITek/element

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147
