### ISSUE TITLE
[Bug Report] Popper is invisible when changing the type of DatePicker

### ISSUE THREAD

**Issue by ChenCyl** [ElemeFE/element#18398]
### Element UI version
2.13.0

### OS/Browsers version
Windows 10 / Chrome 版本 78.0.3904.108（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Hitoka/pen/abzZXWy

### Steps to reproduce
Bug 复现步骤：
1. 点击日期选择框，popper 弹出
2. 保持 popper 的显示状态，点击 daterange 切换 el-date-picker 类型
3. 再次点击选择框，popper 不弹出

p.s. popper 定位可能会出错（[#18385](https://github.com/ElemeFE/element/issues/18385)）

### What is Expected?
[ 重现步骤 3 ] 中 popper 正常弹出

### What is actually happening?
[ 重现步骤 3 ] 中 popper 不弹出

**Comment by sunchens** [comment]
同样遇到了，难受

**Comment by sunchens** [comment]
同样遇到了，咋解决么

**Comment by ChenCyl** [comment]
> 同样遇到了，咋解决么

希望对你有帮助 #18388
