### ISSUE TITLE
table组件，固定列后，拖动到最后几列，表头和表格排列错开没对齐

### ISSUE THREAD

**Issue by xLong1029** [ElemeFE/element#18395]
element-ui: 2.12.0
table组件，固定列后，拖动到最后几列，表头和表格排列错开没对齐，任何浏览器都会这样的现象
![TIM截图20191213093407](https://user-images.githubusercontent.com/18066675/70762594-0e412a00-1d8c-11ea-890d-6000d50f3b2d.png)

**Comment by cnvp** [comment]
请问有解决嘛

**Comment by xLong1029** [comment]
> 请问有解决嘛

更新新版element，已修复此bug

**Comment by cnvp** [comment]
好了，感谢
