### ISSUE TITLE
[Bug Report] 点击el-image渲染的图片后将使得页面无法滚动。

### ISSUE THREAD

**Issue by Fr3027** [ElemeFE/element#18393]
### Element UI version
2.13.0

### OS/Browsers version
mac10.15.1/chrome(79.0.3945.79)

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/destiny3027/ve4xyqj0/3/

### Steps to reproduce
单击图片即可。

### What is Expected?
点击图片不会引起右侧滚动条的消失。

### What is actually happening?
点击图片后右侧滚动条消失且无法滚动。

**Comment by liu20115342** [comment]
我也遇到这个问题了，看了下源码，是因为点击图片后会向body增加overflow: hidden，没有不使用增预览功能这会导致页面不滚动，应该判断下preview-srcList是否有值再执行预览，这个地方没做判断，不清楚什么时候修复。
![image](https://user-images.githubusercontent.com/20399192/76736873-a6dbb180-67a2-11ea-932b-e7de972fde47.png)

**Comment by luckyCao** [comment]
#19075
