### ISSUE TITLE
使用dllplugin对element-ui单独打包后，el-table不渲染，tableData数据可以打印出来

### ISSUE THREAD

**Issue by dydoit** [ElemeFE/element#18394]

**Comment by helei2015** [comment]
我也遇到了同样的问题

**Comment by gloxing** [comment]
在 webpack.dll.conf.js 里面加入

resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
        'vue$': 'vue/dist/vue.esm.js',
    }
  },

**Comment by xushuai2** [comment]
> 在 webpack.dll.conf.js 里面加入
> 
> resolve: {
> extensions: ['.js', '.vue', '.json'],
> alias: {
> 'vue$': 'vue/dist/vue.esm.js',
> }
> },

这个 可以解决 问题吗
