### ISSUE TITLE
table 懒加载问题 

### ISSUE THREAD

**Issue by peng2z** [ElemeFE/element#18402]
![image](https://user-images.githubusercontent.com/48242359/70789251-a1e71a80-1dcd-11ea-895a-12dac03fb071.png)
![image](https://user-images.githubusercontent.com/48242359/70789304-b7f4db00-1dcd-11ea-9211-6fd29091487f.png)
![image](https://user-images.githubusercontent.com/48242359/70789357-d529a980-1dcd-11ea-8279-3f512476aafb.png)
table 懒加载 父A数据—>子B数据 然后改数据源 父B数据—>子A数据 重新赋值给table 后 点击父B 懒加载 A 的数据时 报‘Maximum call stack size exceeded’，有没有解决方法

**Comment by lxc455735702** [comment]
@peng2z 有解决吗？

**Comment by Ka-Houl** [comment]
解决了吗
