### ISSUE TITLE
[bug report] collapse embedded table jitters when expanding animation

### ISSUE THREAD

**Issue by jinyang1994** [ElemeFE/element#18405]
### Element UI version
2.13.0

### OS/Browsers version
Windows/ Chrome

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/q31n9ec6/

### Steps to reproduce
具体结构参考重现链接上面例子

### What is Expected?
展开收起动画流畅

### What is actually happening?
目前效果是抖动的效果

**Comment by songxiujin** [comment]
如果el-table-column中内容超出一定长度就会出现该现象(即使展开后显示内容长度并未换行)，为el-table-column设置宽度则动画恢复正常。

**Comment by jinyang1994** [comment]
3列表格的宽度无法确定的情况下怎么办
