### ISSUE TITLE
[Select]远程搜索的数据回填需求

### ISSUE THREAD

**Issue by shortbaby** [ElemeFE/element#1840]
### What is actually happening?
select组件 有考虑过数据回填功能吗？比如有个需求下拉列表项是远程搜索的，但是有可能需要在一开始就在select组件上添加几个已选项，这种数据回填的需求能不能支持？或者有没有一些好的方法

**Comment by Leopoldthecoder** [comment]
给绑定值赋初始值就可以：http://jsfiddle.net/fm2gczvL/

**Comment by shortbaby** [comment]
这个方法不行呀。因为下拉项 一开始 是没有去加载的。是个空数组，所以这样回填显示不出来

**Comment by shortbaby** [comment]
我的 回填值 数组 里面的元素 不是一个字符串 是一个  包含 id  和name属性的 对象。是不是因为这个原因。因为我看源码里面 都是通过 options去filter的 但是这个options 因为没有加载数据 所以为空数组。

**Comment by Leopoldthecoder** [comment]
例子里的下拉项也是空数组，我删掉了一些无关代码：http://jsfiddle.net/fm2gczvL/2/

**Comment by shortbaby** [comment]
哦，好的 我想应该是 我这个 回填的数组里面单项 是一个复杂对象导致无效的吧 我改成字符串试试

**Comment by shortbaby** [comment]
这个好像是 因为版本的原因呢 。。你们是最近更新了吧 我看最新的源码 不一样了

**Comment by Leopoldthecoder** [comment]
是的。

**Comment by lazybios** [comment]
赋初始值的时候，如果value、label不一样怎么去专门设置label？ @Leopoldthecoder
