### ISSUE TITLE
建议 DatePicker 日期选择器返回的值为format格式化后的值

### ISSUE THREAD

**Issue by yeyifen** [ElemeFE/element#1841]
### ElementUI version

1.0.7
### OS/Browers version

macOS chrome 54
### Vue version

2.0.1
### Reproduction Link
官网提供的示例能重现：
http://jsfiddle.net/5sy4eucy/

### Steps to reproduce
点击年，选择 2012
### What is Expected?
预期 value5 的值为 2012（跟周选择一样返回的值就是输入框里显示的值）
### What is actually happening?
实际上value5的值为 2012-01-01T00:00:00.000Z

**Comment by QingWei-Li** [comment]
这个问题 Gitter 里讨论过，`v-model` 的数据是双向绑定的，没办法返回一个 format 的值。只能自己做 format 操作

**Comment by yeyifen** [comment]
如果还需要自己再做次 format 操作的话，感觉就缺少组件的便利性了，能否教下我怎么改，能实现类似周选择的效果，我这边自己改一下好了

**Comment by QingWei-Li** [comment]
不过这问题已经反馈了许多次，我考虑下怎么提供这个功能吧。现在你可以在提交数据前自己处理一下

**Comment by reverland** [comment]
我倒是希望element能依赖moment.js。
我们用的时候实际上外面套了一层把与element绑定的数据转换成unix秒数

**Comment by yeyifen** [comment]
没必要搞那么多依赖吧，一个moment.js 也不小呢。你又在外面套一层感觉失去组件的便利性了，而且组件本身有 format 参数，能直接根据这个format参数返回应该是最方便的

**Comment by reverland** [comment]
@yeyifen 失去组件的便利性是什么意思，我们的api都是unix秒数啊，当然需要转换一层才能便捷啊，
在组件里实现和重新实现moment功能有什么区别，还未必有moment做的好。

如果时间处理很多的话怎么会不用moment这种东西，目前element自己format的时间什么的，那部分代码怎么说，反正我觉得不如引入moment。请参考 https://ant.design/components/date-picker/

ps：如果是webpack2或者rollup打包，moment完全是es6哦，tree shaking什么的不是问题。如果是webpack1，你也可以把不用的locale给排除掉。

**Comment by yeyifen** [comment]
@reverland 使用场景不同吧，估计你需要用到的是精确到时分秒的，而我目前遇到的是只需要选择年度就行，如果传个unix的秒数过来，我们还得再转换他一次，因为做的系统是多语言的，期间又会遇到时区问题，处理起来会比较麻烦。所以如果能返回 format 参数设定的值，对我们来说是最方便的

**Comment by reverland** [comment]
@yeyifen 如果要支持format，希望element能依赖moment，我只有这个观点。

**Comment by yeyifen** [comment]
@reverland 这个组件已经有 format 这个参数的说，只是他返回的数据没有用 format 进行格式化

**Comment by a741841403** [comment]
Sun Jul 30 2017 18:35:06 GMT+0800 (中国标准时间)
绑定到变量的时候，变量最后会获得这个值是什么意思。但是我明明是用的日期选择，不应该是返回的是日期吗

**Comment by Leopoldthecoder** [comment]
@a741841403 这就是一个 Date 对象。

**Comment by cnlinjie** [comment]
同遇到这个问题，需要自己转

**Comment by cnlinjie** [comment]
@reverland  太大了，可以酌情分析源码导入，整个导入太大

**Comment by callnothing** [comment]
这个很蛋疼, 经常忘记把Date对象格式化一下, 导致每次请求的时间少了8个小时, 希望团队能够重视一下这个问题

**Comment by dafeifei0218** [comment]
@cnlinjie 如何转换？

**Comment by ghostcode** [comment]
valueFormat 可以设置
