### ISSUE TITLE
[Bug Report] Cascader default filter method is case sensitive

### ISSUE THREAD

**Issue by macu** [ElemeFE/element#18410]
### Element UI version
2.12.0

### OS/Browsers version
macOS Catalina / Chrome 79

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/macu89/pen/vYEXOEd

### Steps to reproduce
Filtering for options in el-cascader must match option label case exactly, as the default filter method is case sensitive: `node.text.includes` https://github.com/ElemeFE/element/blob/dev/packages/cascader/src/cascader.vue#L537 

### What is Expected?
Filtering should be case insensitive by default. You can get this behaviour by setting a filter method like:
`:filter-method="(n, k) => n.getText(false, null).toLowerCase().indexOf(k.toLowerCase()) >= 0"`

### What is actually happening?
Options are not included in the suggestions if the filter text does not match the case of the node label text exactly

**Comment by repoAlex** [comment]
I would like to suggest this issue,too! 
Could you please offer the attributes to control it? 
Actually, we don't want it to be case sensitive.

**Comment by mohsinahmad** [comment]
> I would like to suggest this issue,too!
> Could you please offer the attributes to control it?
> Actually, we don't want it to be case sensitive.

by using property "filter-method" you can define your method to ignore case sensitivity, you can ignore this.


defind :filter-method="filterOptions:


filterOptions(node, keyword) {
return node.label.toLowerCase().includes(keyword.toLowerCase())
}

**Comment by altynbek07** [comment]
> > I would like to suggest this issue,too!
> > Could you please offer the attributes to control it?
> > Actually, we don't want it to be case sensitive.
> 
> by using property "filter-method" you can define your method to ignore case sensitivity, you can ignore this.
> 
> defind :filter-method="filterOptions:
> 
> filterOptions(node, keyword) {
> return node.label.toLowerCase().includes(keyword.toLowerCase())
> }

or:
```javascript
filterOptions(node, keyword) {
    return node.text.toLowerCase().includes(keyword.toLowerCase())
}
```
