### ISSUE TITLE
[bug report] after El image displays once, the shortcut key of ESC direction key fails?

### ISSUE THREAD

**Issue by Maconzhang** [ElemeFE/element#18415]
### Element UI version
2.13.0

### OS/Browsers version
78.0.3904.108（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
https://codepen.io/maconzhang/pen/vYEXZoL

### Steps to reproduce
Q1:

1.点击第一张图片， 点击方向键esc正常使用

2.最小化隐藏图片之后，再次点击图片 esc 方向键均失效

Q2:

1.点击第一张图片，右键箭头切换到第二张图片，关闭图片

2.再次点击第一张图片，显示为第二张图片

### What is Expected?
Q1: 图片最小化之后 esc 方向键快捷键正常使用

Q2: 图片显示正常的顺序

### What is actually happening?
Q1: 图片最小化之后 esc 方向键快捷键失效

Q2: 图片显示顺序异常

**Comment by John60676** [comment]
plz fix it

**Comment by cs1707** [comment]
Already fixed, please upgrade the latest version
