### ISSUE TITLE
[Bug Report] img preview model postioned relative to the transformed parent element.

### ISSUE THREAD

**Issue by dongsuo** [ElemeFE/element#18419]
### Element UI version
2.13.0

### OS/Browsers version
all modern OS and Browser

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/dongsuo/pen/eYmzdZw

### Steps to reproduce
Put el-image in a transformed parent element, then preview the image.

### What is Expected?
Preview model positioned relative the viewport.

### What is actually happening?
Preview model positioned relative the transformed parent element.

**Comment by vxhly** [comment]
有相同的困扰

示例地址： https://codesandbox.io/s/green-frost-36x5n

期望，预览大图的长款是定位至浏览器的窗口

**Comment by cs1707** [comment]
Already fixed, please upgrade the latest version
