### ISSUE TITLE
[bug report] El input is set to the label of El tabs, and the cursor of any character is moved to the end of input

### ISSUE THREAD

**Issue by 173249672** [ElemeFE/element#18425]
### Element UI version
0.1.0

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/173249672/pen/povNzEM?&editable=true

### Steps to reproduce
在el-input中输入任意字符

### What is Expected?
光标停留在当前位置

### What is actually happening?
光标移动到el-input最后

**Comment by xrkffgg** [comment]
我这里显示 是正常的。。。。。

**Comment by 173249672** [comment]
> 我这里显示是正常的。。。。。

你使用的版本为多少？

**Comment by xrkffgg** [comment]
用谷歌 78
