### ISSUE TITLE
[feature request] want to add a list component

### ISSUE THREAD

**Issue by tucke** [ElemeFE/element#18422]
### Existing Component
否

### Component Name
List 组件

### Description
element ui 现在在国内vue圈内口碑非常好，一般用来开发后台框架非常漂亮和方便，虽然list这种组件其实也不难，但是对于写后台的同学而言，写出的样式非常丑陋，所以希望能增加List组件

**Comment by wangdaodao** [comment]
关键UI方面，列表设计的各种都有，写一个组件，也不一定保证样式就可以直接用，还是项目里面自己去定义比较好。
