### ISSUE TITLE
[bug report] El image big image preview bug

### ISSUE THREAD

**Issue by HenryButterflyZou** [ElemeFE/element#18429]
### Element UI version
2.13.0

### OS/Browsers version
Chrome 77.0.3865.120

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/HenryZou/pen/OJPbVgB?&editable=true

### Steps to reproduce
点击无法显示预览图片，按左右键切换才会显示

### What is Expected?
点击后显示大图

### What is actually happening?
点击后无法显示大图，按左右键切换才会显示

**Comment by ToPeas** [comment]
i have some problem too

**Comment by xwaptx4869** [comment]
我也是。。但我的版本是2.12

**Comment by HenryButterflyZou** [comment]
> 我也是。。但我的版本是2.12

2.12应该不会，2.13版本bug主要出现在大图预览的初始下标，初始下标默认为点击的图片src在preview-src-list中的索引，当原图（缩略图）src不在preview-src-list（清晰图）中时会出现此bug，就如2.13.0的官方示例，目前的解决方式为：不使用缩略图，直接使用清晰图。而2.12的初始下标为0，应该不会出现此bug，请检查一下代码。

**Comment by xwaptx4869** [comment]
` :preview-src-list="imgList" 
   imgList:[this.img]
`
版本确实为2.12，测试环境下出的问题，和官网那个示例一样的问题，我把图片数组加一个src，有了左右按钮，点击一次按钮就出来了。更奇怪的是线上环境也是2.12，没问题。

**Comment by xwaptx4869** [comment]
创建一个新的vue项目，引入2.12版本也会出现此bug

**Comment by yyccQQu** [comment]
elementUI verion: 2.11.0 问题同上

**Comment by xwaptx4869** [comment]
> elementUI verion: 2.11.0 问题同上

楼上给出解决方案了，只好先用都原图，我之前略缩图做了裁剪，初始下标找不到了。

**Comment by yyccQQu** [comment]
> > elementUI verion: 2.11.0 问题同上
> 
> 楼上给出解决方案了，只好先用都原图，我之前略缩图做了裁剪，初始下标找不到了。

谢谢

**Comment by ToPeas** [comment]
> > elementUI verion: 2.11.0 问题同上
> 
> 楼上给出解决方案了，只好先用都原图，我之前略缩图做了裁剪，初始下标找不到了。

我一直都用的是原图，还是会有这个问题

**Comment by Deeplycovered-leaf** [comment]
还有一个bug, 第二次重新打开就不能滚动放大缩小了

**Comment by edum18** [comment]
having the same problem on 2.13.0

**Comment by xueyeguiren** [comment]
缩略图和原图一样可以用

**Comment by jeryqwq** [comment]
https://github.com/ElemeFE/element/pull/18523

**Comment by C-Hungry** [comment]
我碰到了同样的问题，希望官方能够解决下

**Comment by Deeplycovered-leaf** [comment]
> 我碰到了同样的问题，希望官方能够解决下

回退到12版就好了, 等他跟新还是算了, 都三个月没更新了

**Comment by cs1707** [comment]
Already fixed, please upgrade the latest version
