### ISSUE TITLE
[bug report] popconfirm component event naming is not standard

### ISSUE THREAD

**Issue by vajacn** [ElemeFE/element#18434]
### Element UI version
2.13.0

### OS/Browsers version
Windows 10 / Chrome 79

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/vajacn/pen/PowbQLV

### Steps to reproduce
在 el-popconfirm 组件上写 @onConfirm="action"，不会调用 action 方法，把 onConfirm 改成 onconfirm 也是一样的效果。

组件在声明事件时应该用 kebab-case 命名，例如：on-confirm。（我觉得不要用 on 前缀），而且这个方法在文档里没写，看源码时才发现，建议在文档中补充完整。

### What is Expected?
执行 action 方法，在控制台打印 deleted

### What is actually happening?
控制台 Vue 提示如下：
"[Vue tip]: Event 'onconfirm' is emitted in component <ElPopconfirm> at packages/popconfirm/src/main.vue but the handler is registered for 'onConfirm'. Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use 'on-confirm' instead of 'onConfirm'."

**Comment by xrkffgg** [comment]
API 上没有写支持 `onConfirm`  啊

**Comment by vajacn** [comment]
是啊，文档上没写。我是看源码里发现有这个事件的。

```
  methods: {
    confirm() {
      this.visible = false;
      this.$emit('onConfirm');
    },
    cancel() {
      this.visible = false;
      this.$emit('onCancel');
    }
  }
```

如果不用onConfirm这个事件，那如何在点击「确定」按钮时执行需要的操作呢？

**Comment by xrkffgg** [comment]
`@onConfirm="doSome"`

我在本地测试 这个可以的

**Comment by xrkffgg** [comment]
新出的，没用过，才发现文档里竟然没有这一块 😂😂

**Comment by xrkffgg** [comment]
codepen 上会报错，本地测试不会

**Comment by vajacn** [comment]
是的，我在本地测试也能用。不过 Element UI 里其他的事件都是用 kebab-case 格式命名，这也是 Vue.js 的最佳实践，应该保持统一。
总的来说，两点建议：
1、事件名称命名方式保持一致
2、文档上补充事件说明

**Comment by parse-dinghua** [comment]
用cdn模式，一样的错误，popconfirm 基本没有用

**Comment by cmpan** [comment]
popconfirm 没有起到应有的作用，弹出的按钮没法绑定事件

**Comment by Hao-Wu** [comment]
2.13.0
`@onConfirm="doSome"` 确实是work的
上面示例codepen使用了cdn确实是不work的
文档里竟然没有明确的说明`onConfirm`，确实是很不应该的

**Comment by Hao-Wu** [comment]
Fixed in #18324

**Comment by Edge00** [comment]
用 JSX 写的时候必须写 `onOnConfirm` 🤣🤣🤣：
```jsx
<el-popconfirm onOnConfirm={handleConfirm} title="确定删除？">
</el-popconfirm>
```

**Comment by elmtong** [comment]
![](https://ftp.bmp.ovh/imgs/2020/04/c050dd6ec5e78af3.png)
![](https://ftp.bmp.ovh/imgs/2020/04/eccdfa3871ce3c7e.png)
:apple:监听事件要写小驼峰onConfirm！

**Comment by Innei** [comment]
建议在文档中补充这两个事件，
https://element.eleme.io/#/zh-CN/component/popconfirm

**Comment by iamkun** [comment]
Now fixed to the correct 'confirm' and 'cancel' event name in #20240

**Comment by sg552** [comment]
建议修改文档。 https://ant.design/components/popconfirm-cn/

应该用两种方式：

```
<el-popconfirm title="确定吗？" @confirm="to_delete.." >
<el-popconfirm title="确定吗？" on-confirm="to_delete.." >
<el-popconfirm title="确定吗？" onConfirm="to_delete.." >
```
不能简单的写成： 
```
<el-popconfirm title="确定吗？" confirm="to_delete.." >
```
