### ISSUE TITLE
[Bug Report] Warning on official website

### ISSUE THREAD

**Issue by hwGito** [ElemeFE/element#18441]
### Element UI version
2.13.0

### OS/Browsers version
mac os

### Vue version
2.6.11

### Reproduction Link
codepen

### Steps to reproduce
1. 百度搜索 element-ui
2. 出现 "该站点可能受到黑客攻击，部分页面已被非法篡改！"

1. Baidu search element UI
2. Appear "the site may be hacked, some pages have been illegally tampered with! "

### What is Expected?
无 nothing

### What is actually happening?
无 nothing

**Comment by xrkffgg** [comment]
百度 🐂🍺
