### ISSUE TITLE
建议：DateTimePicker组件能否增加一个属性如:selectRange: 7,  在选择日期时，选择范围只可以是在当前日期时间点之后7天，或者在当前日期时间点之前7天

### ISSUE THREAD

**Issue by perfectyang** [ElemeFE/element#1845]
建议：DateTimePicker组件能否增加一个属性如:selectRange: 7,  在选择日期时，选择范围只可以是在当前日期时间点之后7天，或者在当前日期时间点之前7天

**Comment by QingWei-Li** [comment]
有 disabledDate

**Comment by stackia** [comment]
可以用 disabledDate 来实现，也不是非常麻烦的
disabledDate 用起来比较灵活，个人认为不需要单独加入类似 selectrange / max / min 这样的选项
