### ISSUE TITLE
[Bug Report] Popconfirm  events not working

### ISSUE THREAD

**Issue by itsmeJithin** [ElemeFE/element#18456]
### Element UI version
0.1.0

### OS/Browsers version
MacOS Catalina

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/itsmejithin/fx5oq8zk/1/

### Steps to reproduce
include plugin file from the given cdn and initialise Vue js. 
Then include the popconfirm element and listen for the `onConfirm` events
and assign that event to new event handler method. 

### What is Expected?
change the callback event name to `$this.emit('on-confirm)'` this.

### What is actually happening?
HTML doesn't support  Camal case letters as its attributes. so change the event name to lowercase letters or use as hyphen separated words.

**Comment by itsmeJithin** [comment]
Please close this issue after the merge.

**Comment by iamkun** [comment]
Now fixed to the correct 'confirm' and 'cancel' event name in #20240
