### ISSUE TITLE
el-cascader 复选框选择并加上可搜索，ie浏览器回自动展开

### ISSUE THREAD

**Issue by mrluopeijian** [ElemeFE/element#18460]
el-cascader 复选框选择并加上可搜索，ie浏览器回自动展开

**Comment by huangche007** [comment]
@mrluopeijian 老哥，我也遇到这个问题，请问解决了没

**Comment by mrluopeijian** [comment]
> @mrluopeijian老哥，我也遇到这个问题，请问解决了没

解决了

**Comment by huangche007** [comment]
@mrluopeijian 怎么解决的，能否告知下小弟解决办法

**Comment by mrluopeijian** [comment]
默认可搜索的那个属性先为false，然后获取焦点的时候再把它设置为true就可以了

**Comment by mrluopeijian** [comment]
> @mrluopeijian怎么解决的，能否认识下小弟解决办法

默认可搜索的那个属性先为false，然后获取焦点的时候再把它设置为true就可以了

**Comment by huangche007** [comment]
@mrluopeijian ok，谢谢老哥，我试下
