### ISSUE TITLE
[Bug Report] el-select has a drop-down on the ios mobile terminal and the value cannot be selected

### ISSUE THREAD

**Issue by heliu9697** [ElemeFE/element#18464]
### Element UI version
2.12.0

### OS/Browsers version
ios mobile browser

### Vue version
2.6.10

### Reproduction Link
http://codepen.io/pen/define/

### Steps to reproduce
El select is used on the mobile side. In IOS system, a drop-down click cannot select a value, while a double-click can select a value. In Android, it is normal (click to select a value). How to solve it? Thank you!

### What is Expected?
IOS mobile browser can click to check the value in the drop-down box

### What is actually happening?
Drop down box click cannot select value

**Comment by NateScarlet** [comment]
duplicated with https://github.com/ElemeFE/element/issues/17794

**Comment by heliu9697** [comment]
Thank you!
