### ISSUE TITLE
[Feature Request] calender modify title

### ISSUE THREAD

**Issue by DarranFan** [ElemeFE/element#18468]
### Existing Component
是

### Component Name
calender

### Description
eg: how to modify the chinese word which '上个月’  to 'pre'

**Comment by xrkffgg** [comment]
API 上是没有提供自定义修改的，不过查看源码发现是来自于`locale\lang\zh-CN.js` 文件里，你可以去修改下这个文件里的东西

**Comment by DarranFan** [comment]
好的，谢谢
