### ISSUE TITLE
表单里用了datetime后，提交时需手工format么？能不能自动？

### ISSUE THREAD

**Issue by sandysong** [ElemeFE/element#1847]
v1.0.7版本
表单里用到datetime-picker组件，type是datetime，v-model绑定到form.start_time
表单提交时，将form提交，发现没有start_time
提交时手工将form.start_time给format成字符串，可以正常提交

正常用法是这个吗？感觉有点啰嗦，还是我用错了？

**Comment by QingWei-Li** [comment]
是的，需要自己 format

**Comment by zuesgooogle** [comment]
vue 或者 element ui 有提供手动格式化的函数吗？
