### ISSUE TITLE
[Bug Report] click el-image will add "overflow: hidden" to body makes the page unable to scroll

### ISSUE THREAD

**Issue by bijinfeng** [ElemeFE/element#18490]
### Element UI version
2.13.0

### OS/Browsers version
macOS/Chrome79.0.3945.88

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/bijinfeng/pen/mdymBgw

### Steps to reproduce
click el-image element, check body attributes, you will find "overflow: hidden"

### What is Expected?
I think only el-image element has "preview-src-list" attributes，could add "overflow: hidden" to body.

### What is actually happening?
no "preview-src-list" attributes，still have "overflow: hidden" in body

**Comment by liuwujie** [comment]
I actually had the same problem，I haven't found the right solution yet。

**Comment by liuwujie** [comment]
Before the problem is solved,You can set the `body` style to `overflow: auto !important` first

**Comment by suryasoi-ui** [comment]
I am also getting the same problem.

**Comment by wuhuisiyue** [comment]
这个是由于element-ui的Image组件的原因，估计下个版本会解决，暂时可以传个imglist参数过去值是图片的地址

**Comment by jkhmnk** [comment]
我也是遇到这问题，一点击 滚动条就没有了  无了个语

**Comment by yaohw007** [comment]
I actually had the same problem，I haven't found the right solution yet。

**Comment by lalawila** [comment]
同有这问题好久了

**Comment by luckyCao** [comment]
#19075
