### ISSUE TITLE
表格列宽度

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#185]
因为对列宽参数`width`和`min-width`做了`parseInt(arg, 10)`的操作，如果我传入`25%`的话就被计算成了`25px`导致页面出错。是否可以考虑下对百分比参数的支持？

**Comment by furybean** [comment]
那这个 25% 怎么算呢？按照所有列宽的 25%，还是 Table 可见宽度的 25%？

**Comment by erguotou520** [comment]
就是和原生table的概念一样啊，针对所有列宽（除掉多选框）

**Comment by furybean** [comment]
原生的 table 布局有很多问题，甚至在内容不一样的时候，列宽会不一样，所以才有 min-width 和 width 两个属性。
min-width 很难同时支持百分比和数值，我想不到一套严谨的算法可以适用所有场景。

**Comment by erguotou520** [comment]
那如果我要实现4列同宽怎么实现？我想实现列1 20%宽，列2 30%宽，列3 30%宽，列4 20%宽又怎么做？

**Comment by furybean** [comment]
『那如果我要实现4列同宽怎么实现？』
4列同宽应该不需要做什么事情的吧，什么都不设置应该就是 4 列同宽的。

『列1 20%宽，列2 30%宽，列3 30%宽，列4 20%宽又怎么做？』
这个目前应该是无法严格实现，通过 min-width 的不同，剩余的宽度会均分到不同的列。

如果可以提供一个 min-width 同时支持百分比和数值的算法，我会考虑去添加这个功能的。

**Comment by erguotou520** [comment]
个人理解中`min-width`应该是内容显示的最小宽度，当不足时表格可滚动显示。如果设置了`width`那么宽度应该就以`width`来计算，如果`width`的宽度小于`min-width`，那么应该把其它所有列宽都要扩充，试其同时满足`width`和`min-width`。但是这样是不是有些复杂了？是否过度设计？值得思考。

**Comment by furybean** [comment]
在使用 Table 的情况下，大部分情况会有这么两种需求：
- 某些列是固定宽度的，比如就一个性别，可能 40px 已经够了，这时候使用 width 属性。
- 我需要设置某些列的最小宽度，并且希望 Table 在有剩余宽度的时候，可以均分这个宽度给设置了最小宽度的列。

width 和 min-width 适用于这两种需求，可能『均分』这件事并不合适，如果按照 min-width 的设置按比例分，这样就能满足上面的第二个需求。

**Comment by erguotou520** [comment]
OK, got it.

**Comment by Jiang-K-J** [comment]
> 在使用表的情况下，大部分情况都会有这么两种需求：
> 
> * 有些列是固定宽度的，比如就一个性别，可能 40px 已经够了，这个时候使用 width 属性。
> * 我需要设置某些列的最小宽度，并且希望表在有剩余宽度的时候，可以均分这个宽度给设置了最小宽度的列。
> 
> width 和 min-width 适用于这两种需求，可能『均分』这件事不太合适，如果按照 min-width 的设置按比例分配，这样就能满足上面的第二个需求。

有个问题，如果我需要设置某些列的最小宽度(px)，同时希望这些宽度随屏幕宽度变化更宽，也就是说最小宽度用px，宽度用百分比，如果超出了表格宽度，显示滚动条，这个该怎么做
