### ISSUE TITLE
el-row 设置非零 gutter 会出现横向滚动条

### ISSUE THREAD

**Issue by jiayx** [ElemeFE/element#1850]
给 el-row 设置非零的 gutter 会出现横向滚动条
chrome 版本 55.0.2883.95 (64-bit) 
"element-ui": "^1.0.7"

官方示例中也是这样的
http://element.eleme.io/#/zh-CN/component/layout

**Comment by baiyaaaaa** [comment]
操作系统和浏览器是？

**Comment by jiayx** [comment]
macOS 最新版
Chrome 浏览器

**Comment by baiyaaaaa** [comment]
分栏间隔的例子中不就是非零的 gutter么，我这里没有发现有出现滚动条的情况

**Comment by baiyaaaaa** [comment]
应该是你使用<el-row>的外层没有留有足够的padding的原因

**Comment by jiayx** [comment]
@baiyaaaaa 谢谢解答，不过我发现官网的例子在我这里运行就是有横向滚动条的
[https://dn-jiayx.qbox.me/gutter100.png](url)
[https://dn-jiayx.qbox.me/gutter20.png](url)
[https://dn-jiayx.qbox.me/gutter0.png](url)

**Comment by baiyaaaaa** [comment]
对的，这是因为在fiddler中el-row的父级容器没有足够的padding，不影响正常使用，当你使用gutter的时候就需要保证这一点

**Comment by jiayx** [comment]
谢谢

**Comment by raykent92** [comment]
这设定是真的不友好,应该是用css计算首个子容器和最后那个子容器的外边距

**Comment by raykent92** [comment]
![image](https://user-images.githubusercontent.com/13301907/49695118-d7f92980-fbd0-11e8-93e8-9d4820b9e32a.png)
就是这么粗暴直接

**Comment by sinbad9999** [comment]
爱的色放

- [ ]
