### ISSUE TITLE
[bug report] version 2.13 image component large preview bug

### ISSUE THREAD

**Issue by quietdw** [ElemeFE/element#18519]
### Element UI version
2.13.0

### OS/Browsers version
Mac / Google Chrome 78.0.3904.108

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/quietdw/pen/dyPRNmR

### Steps to reproduce
打开链接即可

### What is Expected?
点击图片即可大图预览

### What is actually happening?
点击图片预览失败，需要手动切换一次图片。

**Comment by luckyCao** [comment]
#18975

**Comment by cs1707** [comment]
Already fixed, please upgrade the latest version
