### ISSUE TITLE
Slot footer in [bug report] dialog is not compatible with scopedslots in Vue JSX

### ISSUE THREAD

**Issue by xuanhen2013** [ElemeFE/element#18546]
### Element UI version
2.13.0

### OS/Browsers version
macos 

### Vue version
3.0.0-alpha.0

### Reproduction Link
https://codepen.io/lovejune2014/pen/QWwMMaW

### Steps to reproduce
在使用 JSX 语法的时候，通过 scopedSlots 注册 slots,  dialog footer 使用了判断，必须要多声明一次

### What is Expected?
不需要多一次声明

### What is actually happening?
需要在目录中多写一次

```
// ...
 <el-dialog
  // ...
  scopedSlots={{
          title: () => <div>header</div>,
          footer: () => <div>footer</div>
        }}
>
...
// <div slot="footer" /> 必须声明
</el-dialog>
```
实际上，我必须要多声明一个占位符
`<div slot="footer" />`

**Comment by xuanhen2013** [comment]
https://github.com/ElemeFE/element/blob/466aa288a3/packages/dialog/src/component.vue
```
// 29 行
<div class="el-dialog__footer" v-if="$slots.footer">
          <slot name="footer"></slot>
</div>
```

$slots 应该换成 $scopedSlots

**Comment by leecervan904** [comment]
Same problem, the source code is not compatible for Vue2.6+ version.
