### ISSUE TITLE
DateTimePicker无法单独引入?

### ISSUE THREAD

**Issue by Thstone37** [ElemeFE/element#1854]
![image](https://cloud.githubusercontent.com/assets/11756943/21336362/c70adf64-c69f-11e6-9b11-144d4667a9c9.png)
![image](https://cloud.githubusercontent.com/assets/11756943/21336378/ebf860f8-c69f-11e6-8ab5-139563c2e4ee.png)

**Comment by QingWei-Li** [comment]
没有这个组件，应该是 `DatePicker`，可以通过 https://github.com/ElemeFE/element/blob/dev/components.json 查看所有组件的名字。

**Comment by QingWei-Li** [comment]
u e
