### ISSUE TITLE
[Bug Report] About images Click Image lock scroll bar

### ISSUE THREAD

**Issue by vanness30214** [ElemeFE/element#18567]
### Element UI version
2.13.0

### OS/Browsers version
win10/chorme 79.039

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
After entering the page
 https://element.eleme.cn/#/zh-CN/component/image
, click the picture, and the body will be added with "overflow: hidden;" attribute, and then click the guide menu page at the top of the official website, unable to scroll

### What is Expected?
Lock the scroll bar only when the user needs to open the preview large image and enter the preview SRC list attribute, otherwise the scroll bar cannot be operated after locking

### What is actually happening?
After entering the page, press F12 to see whether the body has been added overflow: hidden; attribute, but this attribute will be added after clicking. After looking at the source code of the component, it is found that the purpose is to click preview to lock the body scroll bar. However, if preview SRC list is not passed, it means that you do not need to implement preview to lock the body scroll bar

**Comment by lxw15337674** [comment]
me too

**Comment by luckyCao** [comment]
#19075
