### ISSUE TITLE
[Bug Report] el-select require two tap to change selection since IOS 13.2.3

### ISSUE THREAD

**Issue by BezMaster** [ElemeFE/element#18584]
### Element UI version
2.13.0

### OS/Browsers version
IOS 13.2.3 / IOS Safari

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/SebastienChesneau/pen/KKwypvM

### Steps to reproduce
Just try to change the selection with a single click

### What is Expected?
A single click change my selection

### What is actually happening?
A single tap/click does not work, we need to click 2 times to validate the selection

**Comment by panda-zhao** [comment]
me too

**Comment by AntonySufer** [comment]
me too

**Comment by NateScarlet** [comment]
Duplicate of #17716

**Comment by lxy030988** [comment]
me too
