### ISSUE TITLE
[bug report] image component does not use default preview to show bug

### ISSUE THREAD

**Issue by maicWorkGithub** [ElemeFE/element#18593]
### Element UI version
2.13.0

### OS/Browsers version
Windows 10 / Chrome 79

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/maicworkgithub/pen/wvBPJMm

### Steps to reproduce
使用dialoag组件预览图片

### What is Expected?
预览之后页面应该复原

### What is actually happening?
body上被添加了overflow:hidden，预览结束之后没有删除。

https://github.com/ElemeFE/element/blob/fcaec91eb9e81dbaa4ee2ec6e013aba5577e019b/packages/image/src/main.vue#L219 在点击的时候被调用，但是 https://github.com/ElemeFE/element/blob/fcaec91eb9e81dbaa4ee2ec6e013aba5577e019b/packages/image/src/main.vue#L225 在预览结束的时候没用调用，所以219行应该加个判断，如果有 preview-src-list 数据绑定再执行class 和样式操作

**Comment by luckyCao** [comment]
#19075

**Comment by cs1707** [comment]
fixed
