### ISSUE TITLE
Tab组件切换动画

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#186]
如题，可以考虑加入tab切换的动画

**Comment by fishpaw** [comment]
@erguotou520 ，基础用法的 Tabs 是有切换动画的，选项卡样式的 Tabs 没有动画，你是希望给选项卡样式的 Tabs 添加动画么？貌似有些困难诶~

**Comment by erguotou520** [comment]
应该是`tab-pane`之间切换的动画，动画应该还是用`transition`做吧

**Comment by fishpaw** [comment]
@erguotou520 对的，选项卡样式的 Tabs 不太可能有像基础用法那样的滑动效果，现在的效果其实是比较合适的

**Comment by Leopoldthecoder** [comment]
@fishpaw ，这位同学的意思是 tab 切换时它的内容的动画，而不是头部导航的动画

**Comment by fishpaw** [comment]
如果是说内容区的切换动效：内容区的视觉面积比较大，信息量比较杂，对动效的选择要微小、自然、迅速。其实很多网站的 tab 切换很直接，就比如 github、gitlab 的页面以及 Dropbox 的设置页面。

**Comment by erguotou520** [comment]
类似于http://cn.vuejs.org/guide/components.html#transition-mode

**Comment by xianfuxing** [comment]
@fishpaw 基础用法的动画怎么实现？
