### ISSUE TITLE
[Bug Report] table-column type="expand" and table :tree-props 冲突

### ISSUE THREAD

**Issue by gMan1990** [ElemeFE/element#18607]
### Element UI version
2.13.0

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

### Vue version
2.6.11

### Steps to reproduce
同时使用`<el-table-column type="expand">`和`<el-table :tree-props="...">`

### What is actually happening?
children行type="expand"行为丢失

----
**Q2: how to remove the header checkbox if column type=selection**

**Comment by xuefei007** [comment]
我也遇到了这个问题，请问你后面怎么解决的

**Comment by gMan1990** [comment]
@xuefei007 换框架 或 不使用 或 等修复
比如iviewui是使用`>`和`+`区分它们两个的

**Comment by xhwgood** [comment]
醉了，46k star的项目咋这个需求都没搞好
