### ISSUE TITLE
[bug report] el-image: preview image not displaying

### ISSUE THREAD

**Issue by kscript** [ElemeFE/element#18602]
### Element UI version
2.13.0

### OS/Browsers version
Win64, Chrome/76.0.3809.132

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/kscript/pen/gObXdJj?&editable=true

### Steps to reproduce
尝试文档给出的例子, 即可复现
https://element.eleme.cn/#/en-US/component/image#image-preview

### What is Expected?
能够正常预览大图

### What is actually happening?
点击图片预览时显示不出大图

**Comment by edum18** [comment]
having the same problem, how did you solve it? My images show up when I click the left or click buttons
