### ISSUE TITLE
希望增加tab的自定义head

### ISSUE THREAD

**Issue by wanghaolu** [ElemeFE/element#1861]
现在的tabs不能自定义tab head的样式，比如加个图标，改个颜色什么的。希望能增加tab head的slot让用户自定义head的样式

**Comment by baiyaaaaa** [comment]
无法提供tab head的自定义，tab 目前可以通过 `label-content` 来自定义选项卡里的内容

**Comment by samon127** [comment]
label-content 被 remove 了 #2064 ，那应该用什么方式来实现呢？

**Comment by samon127** [comment]
label-content has been removed by #2064, any other suggestion?
