### ISSUE TITLE
2.13.0 drawer 打开只有遮罩层，无内容

### ISSUE THREAD

**Issue by fruitGirl** [ElemeFE/element#18612]

**Comment by fruitGirl** [comment]
原因是少了.el-drawer__wrapper这个class的样式

**Comment by zhuzheng314** [comment]
你解决了吗

**Comment by emc2ws** [comment]
add style:
.el-drawer__wrapper {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        overflow: hidden;
        margin: 0;
    }
