### ISSUE TITLE
dialog设置最大高度出现问题，点击瞬间页面向下跳，已上传gif图片

### ISSUE THREAD

**Issue by doudouyoutangtang** [ElemeFE/element#1862]
![gif](https://cloud.githubusercontent.com/assets/21187862/21338591/9b5fd64a-c6b2-11e6-9808-6f8af7794db7.gif)

**Comment by doudouyoutangtang** [comment]
chrom我升级最新的就没事了，之前的chrom版本出现的，哪个版本不知道没有注意

**Comment by Leopoldthecoder** [comment]
其他浏览器有问题吗？
