### ISSUE TITLE
[bug report] when El image is used in El table, there is a problem with the image preview style

### ISSUE THREAD

**Issue by LeeeKevin** [ElemeFE/element#18638]
### Element UI version
2.13.0

### OS/Browsers version
macOS10.13.6/chrome79.0.3945.88

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/viplikaiwen/stam87oe/13/

### Steps to reproduce
<el-table-column label="转账截图" width="120" align="center">
  <template slot-scope="scope">
    <div class="demo-image__preview">
      <el-image
       style="width: 100px; height: auto"
       :src="scope.row.matchVoucher"
       :preview-src-list="scope.row.matchVoucherList">
     </el-image>
    </div>
  </template>
</el-table-column>
在el-table的el-table-column中引入el-image并开启预览功能，从下往上点击图片，发现预览图并没有正常打开，而是越来越大，直至撑爆了整个屏幕

### What is Expected?
发现预览图正常打开，每张预览图的初始大小一致

### What is actually happening?
预览图并无规则的从大到小

**Comment by cs1707** [comment]
fixed
