### ISSUE TITLE
[bug report] Click El image, resulting in page unable to scroll

### ISSUE THREAD

**Issue by hwGito** [ElemeFE/element#18654]
### Element UI version
2.12.0

### OS/Browsers version
macos/Chrome 79.0.3945.88

### Vue version
2.5.20

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
1.创建el-image标签，设置属性，使其在页面显示。
2.点击图片，发现body属性添加了overflow: hidden样式
3.无法滚动

### What is Expected?
none（无）

### What is actually happening?
none（无）

**Comment by Alexeykhr** [comment]
Similiar #18740

**Comment by luckyCao** [comment]
#19075
