### ISSUE TITLE
updateElsHeight可能导致死循环

### ISSUE THREAD

**Issue by SamirGuo** [ElemeFE/element#18673]
https://github.com/ElemeFE/element/blob/6ec5f8e900ff698cf30e9479d692784af836a108/packages/table/src/table-layout.js#L105

**Steps to reproduce**
根据代码所写，在showHeader为true时。这个循环的退出机制一定要等到headerHeight大于2. 如果列是动态生成的，并且table的状态是ready。而数据来源于异步请求，会直接导致死循环。

**What is Expected?**
请考虑如果是否有永远不满足的判断条件的退出机制，比如次数检测？

**What is actually happening?**
导致浏览器死循环卡死

**Comment by qinshenxue** [comment]
可以将slot header 添加一个 min-height:3px来解决
