### ISSUE TITLE
[Feature Request] May Element offer a global register of error or placeholder slot for el-image?

### ISSUE THREAD

**Issue by FrameJ** [ElemeFE/element#18680]
### Existing Component
Yes

### Component Name
el-image

### Description
For now, I need to write error slots every place where I used el-image or build a component by myself. Normally, I prefer to use the same error picture to adapt all images' incorrect load in my web app.

**Comment by ZhangTianCi** [comment]
看一下https://github.com/ElemeFE/element/blob/dev/packages/image/src/main.vue

简单一点，可以用css .el-image__error{.....}来控制一下
复杂一点的话，没有必要吧，毕竟只是一个全局默认图片样式。

**Comment by anrananran** [comment]
可以把elImage再包装一次
