### ISSUE TITLE
建议：dropdown组件添加配置项如notHideWhenClick用于配置当菜单项点击操作后不默认关闭。

### ISSUE THREAD

**Issue by DoubleK2013** [ElemeFE/element#1868]
如有需求
![image](https://cloud.githubusercontent.com/assets/5975017/21341861/a47a4e4c-c6c9-11e6-8524-1478dfbaeb9a.png)
 在菜单项中有复杂交互时并不希望在操作未完成便已关闭了菜单（如点击）

**Comment by baiyaaaaa** [comment]
1.0.9已支持
