### ISSUE TITLE
[Table]希望增加‘自定义列’ 功能建议详情见描述 

### ISSUE THREAD

**Issue by xierenyuan** [ElemeFE/element#1869]
hi,不知你们是否有计划给表格添加如下场景的功能（ps:自定义列）
场景:某些中后台中 列过多 但是很多时候希望使用者可以筛选他只想关注的数据。
很多table 实现的时候自带了一部分功能或者可以通过扩展实现这样一个功能
如这个的列:http://ui-grid.info/docs/#/tutorial/121_grid_menu
实际场景的实现摘取自网络上成型的产品:
![image](https://cloud.githubusercontent.com/assets/7599351/21342066/d9bbee0c-c6ca-11e6-9f2b-70f4e8c2c932.png)
![image](https://cloud.githubusercontent.com/assets/7599351/21342097/07d8f398-c6cb-11e6-950f-1a154ae32e44.png)

**Comment by Leopoldthecoder** [comment]
`el-table-column` 配合 `v-if` 可以实现筛选列的需求，不过近期没有计划将具体的筛选逻辑和交互封装进 Element 内，需要由用户自行编写。
