### ISSUE TITLE
el-input bind to number

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1870]
```  
el-form-item(label='楼层数', prop="floor_count")
        el-input(v-model='innerData.floor_count', auto-complete='off')
```

```
          floor_count: [{
            required: true, type: 'number', message: '请填写楼层数', trigger: 'change'
          }],
```

![05edfccb-5314-4454-b81b-76391370ddd5](https://cloud.githubusercontent.com/assets/13174059/21342420/cbbafdc8-c6cc-11e6-8b23-5f1e8c99f8fa.png)

![46c3ddf8-5a7e-40db-9ecd-57de47397037](https://cloud.githubusercontent.com/assets/13174059/21342435/dc953622-c6cc-11e6-9a47-c32d53334b29.png)

在input里填写数据，model里的数据都是str类型的，el-input上无法绑定类型，validate里也识别不了str是数字

**Comment by kopheece** [comment]
v-model.number

**Comment by njleonzhang** [comment]
@kopheece vue的特性还是element的？

**Comment by njleonzhang** [comment]
另外是否有对validate rule更多详细的说明看了下代码，用的是第三方库 AsyncValidator，按照AsyncValidator的文档，可以这样写，试了一下，会报错。

```
{type: ['string', String, Number], required: true}
```

![2016-12-20 4 28 40](https://cloud.githubusercontent.com/assets/13174059/21343386/67a5419a-c6d1-11e6-98af-06e8d21d6deb.png)

所以应该怎么配validate呢？比如要让这个字段符合正则表达式格式，应该怎么做？

**Comment by baiyaaaaa** [comment]
@kopheece + 1. 验证规则的文档我会单独补一篇

**Comment by kopheece** [comment]
Vue的 
https://vuefe.cn/v2/guide/forms.html#修饰符

**Comment by njleonzhang** [comment]
@kopheece 谢谢。
