### ISSUE TITLE
[Bug Report] el-image perview after close bug

### ISSUE THREAD

**Issue by icerleer** [ElemeFE/element#18713]
### Element UI version
2.13.0

### OS/Browsers version
Window 10 Chrome

### Vue version
2.5.21

### Reproduction Link
https://jsfiddle.net/zq3mfrb5/4/

### Steps to reproduce
el-image 图片组件，点开大图预览后，关闭预览，再打开预览，无法响应键盘和鼠标事件

### What is Expected?
第一次打开可以响应键盘的ESC 和 鼠标滚轮事件

### What is actually happening?
关闭后不再响应 键盘的ESC 和 鼠标滚轮事件， 可能是关闭时调用了 deviceSupportUninstall()， 重新打开没有调用 deviceSupportInstall()

**Comment by leftstyle** [comment]
同样遇到这个问题

**Comment by cs1707** [comment]
Already fixed, please upgrade the latest version
