### ISSUE TITLE
[Bug Report] el-image component has a strange action when I click

### ISSUE THREAD

**Issue by Jinyingyi** [ElemeFE/element#18740]
### Element UI version
2.13.0

### OS/Browsers version
Windows 10/ Google Chrome Version 79.0.3945.117 (Official Build) (64-bit)

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/laojin1105/pen/RwNezmp?editable=true

### Steps to reproduce
click anyone picture which rendered by <el-image>, then body tag will have a new Attribute [style="overflow:hidden"]

### What is Expected?
Do not set "overflow:hidden" to body tag! that behavior not I wanted

### What is actually happening?
When I click a <el-image> element, The body tag will be "overflow: hidden".

**Comment by xiaonuo915** [comment]
I also have this problem.

**Reproduction Link**
https://codepen.io/xiaonuo915/pen/mdJVZZo

**Comment by cjsky666** [comment]
yes , me  too.

**Comment by 54leibo** [comment]
this is a bug, by view source code, when click the img element, it will add 'overflow: hidden;' on the body element
```
...
<img
      v-else
      class="el-image__inner"
      v-bind="$attrs"
      v-on="$listeners"
      @click="clickHandler">
...
clickHandler() {
        // prevent body scroll
        prevOverflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';
        this.showViewer = true;
      }
...
```

**Comment by luckyCao** [comment]
#19075
