### ISSUE TITLE
el-tree组件，清空选中状态时（调用：this.$refs.tree.setCheckedKeys([]);），清不干净

### ISSUE THREAD

**Issue by MShineRay** [ElemeFE/element#18770]
问题描述：
el-tree组件，清空选中状态时（调用：this.$refs.tree.setCheckedKeys([]);），清不干净

复现步骤：
1、选中根节点，全选
2、点击 【清空】按钮，发现有两个节点未清空选中状态

示例：https://codepen.io/mshineray/pen/dyobpRZ

**Comment by zgn466048148** [comment]
i have the same issue 
i want to know how to fix it
it horrible, i event didn't know how could this happen
