### ISSUE TITLE
[Table]怎么设置选中行？

### ISSUE THREAD

**Issue by Exia081** [ElemeFE/element#1878]
refs 组件 id 然后调用里面 Methods似乎不行？

**Comment by Leopoldthecoder** [comment]
单选还是多选？

**Comment by Exia081** [comment]
单选呢

**Comment by h476982844** [comment]
$vm.$refs.你的table.toggleRowSelection(row, true or false)

用这个方法的问题在于，选中后的行不会被塞到table的selection对象中，比如全选时用这个方法去掉一个，表头的对勾不会自动消失。
以及checkbox会触发row上的其它绑定事件，这个冒泡似乎无法简单易懂的阻止。

……因此我正在抛弃el-table，自己写个简单但好用的东西出来。

**Comment by furybean** [comment]
@Exia081 印象中没这个功能，先标一个 FR。

**Comment by Exia081** [comment]
ok
