### ISSUE TITLE
[Feature Request] Add expand and collapse methods to the Tree component.

### ISSUE THREAD

**Issue by linzyjx** [ElemeFE/element#18808]
### Existing Component
是

### Component Name
el-tree

### Description
In custom content for tree nodes, I need to expand and dollapse node with a button. But the document is not given the relevant methods. Hope to give these methods. I hope this can be optimized.

在自定义树节点内容的过程中，我需要一个按钮实现展开和收缩的功能。但是文档中并没有给出相关的方法。希望能够对这个需求进行优化。

**Comment by chend0316** [comment]
This code works.
```
for(let i=0; i<this.$refs.tree.store._getAllNodes().length; i++) {
  this.$refs.tree.store._getAllNodes()[i].expanded = true;
}
```
