### ISSUE TITLE
[Bug Report] [Bug Report] Select:can not toggle dropdown by click toggle icon when filterable

### ISSUE THREAD

**Issue by yyfComeon** [ElemeFE/element#18812]
### Element UI version
2.13.0

### OS/Browsers version
win7/chrome 80.0.3987.106

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/pen/?editors=1111

### Steps to reproduce
el-select当设置filtable时，点击右侧的下拉箭头，菜单会展开，但是再此点击无法收缩回去

### What is Expected?
点击下拉箭头一次切换展开收缩

### What is actually happening?
点击第一次会展开，之后再点击不会收缩回去

**Comment by zxzhgk** [comment]
碰到了同样的问题，官方的示例就有这个问题
