### ISSUE TITLE
[Feature Request] Add infinite scroll to cascader and select component

### ISSUE THREAD

**Issue by leonel1524** [ElemeFE/element#18818]
### Existing Component
Yes

### Component Name
cascader, select, infinite scroll

### Description
Hello everyone, I have tried to use the v-infinite-scroll directive in the cascader component to obtain more values from the server, but it has not been possible.
If someone has managed to unite these functionalities and can help me I will be grateful.

**Comment by Riant** [comment]
I think a pagination like below is a good solution.

![2020-02-22_000052](https://user-images.githubusercontent.com/668285/75050236-923f2d00-5506-11ea-957d-a63e4d83b620.png)

And a custom remote filter will be better.

Of course, you have to rend the selected option(s) as invisible which not in the current page.

Then code almost like below:

``` pug
el-select(v-model='value' :filterable='true'
  :popper-class='optionsCount > optionsPageSize ? "has-pagination" : undefined'
  :remote='true' :remote-method='filterMethod' :loading='loading' loading-text='正在查询...'
)
  el-option(v-for='item in optionsList' :key='item.id' :value='item.id' :label='item.title')
  el-option(v-for='item in offsetItems' v-show='false' :key='item.id' :value='item.id' :label='item.title')
  li.options-pagination(v-if='optionsCount > optionsPageSize')
    el-pagination(small layout='prev, pager, next' :total='optionsCount' :pager-count='5' 
      :page-size='optionsPageSize' :current-page.sync='currentOptionsPage'
    )
```

The offsetItems computed:
```
computed: {
  offsetItems() {
      let res = []
      if (this.optionsCount > this.optionsPageSize && this.selectedItems) {
        res = this.selectedItems.filter(item => !this.optionsList.some(it => it.id === item.id))
      }
      return res
    },
}
```

Wish this is helpful.
