### ISSUE TITLE
Is Element still maintained?

### ISSUE THREAD

**Issue by wirk** [ElemeFE/element#18822]
### Existing Component
Yes

### Component Name
Element

### Description
First off, thank you for creating this feature-rich framework. It has been a pleasure using it in our project. Before an upcoming A11y audit I wanted to submit a few pull requests when I noticed that my issues were already resolved in existing pull requests. Then I noticed that the last activity in the repo was in November :( and now I am wondering if the project has been abandoned?

I would appreciate a short statement regarding the future of Element - will it still be maintained going forward? Are there any particular areas where others can assist?

**Comment by F0rsaken** [comment]
I'm also interested about it. Maybe this project isn't maintained anymore or maybe it's cause of a tough situation in China....

**Comment by become-iron** [comment]
@iamkun @ziyoung 
Could you provide some comments?

**Comment by loiccc** [comment]
Should we switch on Quasar now ?

**Comment by LastImmort** [comment]
> Should we switch on Quasar now ?

I am going to use Quasar if there is no news about Element in march

**Comment by maurer2** [comment]
Hello, are there any news? Thanks

**Comment by kr4ster** [comment]
Just touching-base to keep the issue afloat..

**Comment by maurer2** [comment]
A new version was released yesterday.

**Comment by LastImmort** [comment]
@iamkun Your comments to the issue still will be appreciated

**Comment by loiccc** [comment]
yeaaaahhhhh Element still alive. For how long ?

**Comment by loiccc** [comment]
This year I will switch all my projects on quasar 😢  , sorry dudes but your communication is too weak, not a good sign for the future.

**Comment by zazzaz** [comment]
YES! 🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉

element-plus/element-plus#147
