### ISSUE TITLE
el-tab的pane里的el-table宽度问题

### ISSUE THREAD

**Issue by hustxiaofeng** [ElemeFE/element#1883]
el-tab的pane里的el-table，初始化时的宽度很小，然后会突然铺平，切换的时候有一个抖动的现象

**Comment by Exia081** [comment]
同问

**Comment by hustxiaofeng** [comment]
页面刚打开的一瞬间pane里的表格是这样的
![image](https://cloud.githubusercontent.com/assets/7539662/21349592/b0500530-c6ed-11e6-99ba-b802ced03772.png)
然后因为宽度很小，被挤压了，从而导致出现了浏览器的垂直滚动条，然后又迅速的横向铺平，浏览器垂直滚动条消失，所以页面刚刚打开的一瞬间就会出现滚动条闪现的现象，导致抖动

**Comment by baiyaaaaa** [comment]
因为目前tabs组件的盒模型是 `inline-block` ，宽度是靠tab-header撑开的，但是tab-header的生成又需要tabs组件内部对tab-pane进行处理后才生成，所以中间有个空白期是没有宽度的。1.1后会将tabs组件盒模型修正为`block`。现在暂时的解决方案是，给tabs组件设置一个宽度

**Comment by hustxiaofeng** [comment]
@baiyaaaaa ，恩，pane样式目前确实是inline-block，但是我试了给tabs设置宽度，不论设置固定宽度还是百分比，表格依然会有一个横向铺开的抖动

**Comment by saint3347** [comment]
![table-in-tabs-shake](https://cloud.githubusercontent.com/assets/7347133/21419416/75e24f72-c862-11e6-9882-fc1ac0d74be1.gif)

`.el-tabs {
    display: block;
    width: 940px;
}`
tabs设置了宽度还是会抖动哦。。

**Comment by baiyaaaaa** [comment]
可以试试今天发的1.1.2，问题应该解决了

**Comment by xiaoyanhao** [comment]
@baiyaaaaa 目前版本（1.3.4），每一个tab-pane第一次渲染的时候，table还是有抖动问题。
[https://jsfiddle.net/xiaoyanhao/0112hxfu/](https://jsfiddle.net/xiaoyanhao/0112hxfu/)

**Comment by huaibaomengxiang** [comment]
你们 这个问题解决没有啊

**Comment by huaibaomengxiang** [comment]
@baiyaaaaa 你好,我现在用的2.0.8的版本 还是有这个问题 请问怎么可以解决这个问题

**Comment by naecoo** [comment]
只能暂时加个样式
.el-table__body {
  width: 100% !important;
}

**Comment by gyt95** [comment]
最有效的好像还是
```css
table {
  width: 100% !important;
}
```
