### ISSUE TITLE
使用image组件，当缩略图的路径不在预览图previewSrcList内时，打开预览弹筐第一张图片不会显示。

### ISSUE THREAD

**Issue by wuli-little-frog** [ElemeFE/element#18838]

**Comment by qzmly100** [comment]
应该是版本的问题， @2.12.0正常 2.13不正常

**Comment by wuli-little-frog** [comment]
> 应该是版本的问题， @2.12.0正常 2.13不正常

对的，看了下组件代码，新版的在previewSrcList找了src的索引，为了点开预览打开的是src这张图，如果找不到返回-1就显示不出来图片

**Comment by qzmly100** [comment]
> > 应该是版本的问题， @2.12.0正常 2.13不正常
> 
> 对的，看了下组件代码，新版的在previewSrcList找了src的索引，为了点开预览打开的是src这张图，如果找不到返回-1就显示不出来图片

嗯，用2.12版本吧

**Comment by luckyCao** [comment]
#18975

**Comment by T-1760** [comment]
为啥我的开发和线上cdn引入均是elementui 2.13.0 版本，src链接缩略图（因原图太大）不在previewSrcList中。线下开发板可以预览，而到线上则预览为空。后来看了一下结构，线下开发预览时是直接在body 追加了 el-image-viewer组件其中包含预览地址，而线上cdn的el-image-viewer则是追加在书写 el-image之后且没有图片链接，这emmmm
