### ISSUE TITLE
[Bug Report] format is not working using el-time-select

### ISSUE THREAD

**Issue by punzerkunst** [ElemeFE/element#18847]
### Element UI version
2.12.0

### OS/Browsers version
macOS 10.14.5/Brave 1.2.43

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Ahjit/pen/QWbdGYd

### Steps to reproduce
add format in picker-options

### What is Expected?
Ex. 00:15 AM to 11:45 PM

### What is actually happening?
still in military time

**Comment by malacca** [comment]
format only support `el-time-picker`

https://element.eleme.cn/#/en-US/component/time-picker#time-picker-options

**Comment by punzerkunst** [comment]
Thank you, For now, there's no way to change the format in el-time-select?

**Comment by malacca** [comment]
yes

source:  https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/panel/time-select.vue#L54

maybe can use  https://element.eleme.cn/#/zh-CN/component/select

**Comment by punzerkunst** [comment]
Okay, thank you so much!

**Comment by kissu** [comment]
Hey, I do have the same issue but I do not understand what @malacca showed just above. :sweat_smile: 
Can you explain me how you made it work @punzerkunst ? :smile_cat:
