### ISSUE TITLE
checkbox 的bug描述和修复

### ISSUE THREAD

**Issue by longze** [ElemeFE/element#1886]
用checkbox的时候发现报错，查看了源码发现是下面文件缺少了 “focus”变量的定义
/element/packages/checkbox/src/checkbox.vue
已经提交 pull request 请采纳:
https://github.com/ElemeFE/element/pull/1887
多问一句，下一版npm什么时候发？

**Comment by Leopoldthecoder** [comment]
今天刚发布新版，所以不出意外的话下一版应该需要一周左右。

**Comment by longze** [comment]
我提的PR可以被采纳吗，如果可以我就静等发布了
