### ISSUE TITLE
[Bug Report] When different table components in the same page switch rendering, the selectable configuration uses the selectable of the first rendered table

### ISSUE THREAD

**Issue by veici** [ElemeFE/element#18860]
### Element UI version
2.13.0

### OS/Browsers version
macos 10.15.3 / chrome 80.0.3987.122

### Vue version
3.0.0-alpha.7

### Reproduction Link
https://codepen.io/DoubleK2013/pen/qBdrwLa

### Steps to reproduce
switch tables

### What is Expected?
different tables have different selectable configurations

### What is actually happening?
using the first render configuration

**Comment by liujunchina** [comment]
https://codepen.io/ljj/pen/jObbVdm 
if 的元素添加key

**Comment by veici** [comment]
感谢
