### ISSUE TITLE
[bug report] image component. When previewing a large picture, click the picture for the first time and it will not be displayed. After switching to the next picture, it can be displayed

### ISSUE THREAD

**Issue by miuqiang** [ElemeFE/element#18869]
### Element UI version
2.13.0

### OS/Browsers version
win10 Chrome

### Vue version
3.0.0-alpha.7

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
官网的列子

### What is Expected?
展示

### What is actually happening?
不展示

**Comment by krokodilshnap** [comment]
fix it pleeease...

**Comment by miuqiang** [comment]
image error
