### ISSUE TITLE
[Feature Request] el-table with show-overflow-tooltip, can't copy the content from the tooltips

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/element#18882]
### Existing Component
Yes

### Component Name
El-Table

### Description
El-table with show-overflow-tooltip, can't copy the content from the tooltips.
is the default value from 'enterable' property  false ?

![recode](https://user-images.githubusercontent.com/6183683/75750285-d7f9c200-5d5e-11ea-8942-aca790f23948.gif)

**Comment by yubaoquan** [comment]
Same problem. Will it be fixed?

**Comment by wangliqiang1026** [comment]
Is it resolved?
