### ISSUE TITLE
[Feature Request] Source code of the doc or document scrollbar componant

### ISSUE THREAD

**Issue by flapili** [ElemeFE/element#18893]
### Existing Component
Yes

### Component Name
el-scrollbar

### Description
I'm trying to add a scrollbar to an aside menu with el-scrollbar componant but I have some difficulty due to missing entry in the documentation.
My case is exactly the same as the documentation: a fixed header, a scrollable sidebar menu and a scrollable page then would it be possible to get the source of the documentation to avoid a kind of retro engineering.
this would provide an example to the community but also to element UI.

best regards

**Comment by Littledevil7** [comment]
you should use like this 
![image](https://user-images.githubusercontent.com/44463110/84974751-75360600-b156-11ea-9707-ac35ae66be73.png)
The part indicated by the red arrow is automatically generated, and the part indicated by the yellow arrow is the style you need to configure them manually
![image](https://user-images.githubusercontent.com/44463110/84974564-140e3280-b156-11ea-87cf-9c75f6470364.png)

**Comment by flapili** [comment]
thanks for the help,

I'll try it when I'll have more personal time :)
