### ISSUE TITLE
[Bug Report] Drawer 抽屉 组件的标题在谷歌浏览器中出现了蓝色的外框

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ElemeFE/element#18898]
### Element UI version
2.13.0

### OS/Browsers version
Win10 / Chrome 80

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/gh-xiaoxiao/pen/vYOJbjm

### Steps to reproduce
打开示例，标题出现外边框

### What is Expected?
抽屉组件在所有浏览器中，标题都没有边框

### What is actually happening?
抽屉的标题那里出现了边框

**Comment by hongyuxuan** [comment]
是有这个问题，点一下空白蓝框就没了。感觉是标题被blur了

**Comment by tangyingcai** [comment]
特意去看了源码。组件显示后， focus 定向到当前组件的一个dom上去了.  没测不知道啥用意。。
 watch: {
    visible(val) {
      if (val) {
        this.closed = false;
        this.$emit('open');
        if (this.appendToBody) {
          document.body.appendChild(this.$el);
        }
        this.prevActiveElement = document.activeElement;
        this.$nextTick(() => {
          Utils.focusFirstDescendant(this.$refs.drawer);
        });
      } else {
        if (!this.closed) this.$emit('close');
        this.$nextTick(() => {
          if (this.prevActiveElement) {
            this.prevActiveElement.focus();
          }
        });
      }
    }
  },

**Comment by haojundd** [comment]
![image](https://user-images.githubusercontent.com/38490444/86994386-d5115100-c1d8-11ea-8f44-ef062e5f963c.png)
同问，很奇怪，无法理解为什么要这么设计。。。

**Comment by cs1707** [comment]
Duplicate of #19902
