### ISSUE TITLE
[Bug Report] Can't set text align in el-input tag

### ISSUE THREAD

**Issue by sorawitw** [ElemeFE/element#18905]
### Element UI version
2.13.0

### OS/Browsers version
Windows 10 / Google Chrome 80.0.3987.132

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/sorawitw/pen/KKpvWoy?__cf_chl_jschl_tk__=854d41e3bd4a8bd1fcc513a881fa13116e8e5080-1583374965-0-AbZxGfK4SrlAiTzrnz43W6ZgRX_JFdFJmgl_ciFmfyLjJjJ52HVFR7DgDd7M2Un9ZqyqitEo9ozyuL3rLw8z1_3KrAZtXUXAuirzX9hfWF89DT-r-CueglSl8pC7w2h88S5CKFfjKqU-bZf9nl6CPDo8R9uWHVA8HwOHhoQW5PM3zkiGV5gycp9OL-PLwJBJlqpUH6T4ixiqHGxm8hR0CNwJizp2xTTy_6KGWl-HDpZ6KfeTwlYTYUopFrT_9uJD5dxR9yPGb_i7CANtgRuG2qOM1Z8rvbR1z8cV6xew1fZvmbj0-8zPJmfid0tuTF4QrC3vTts9_3TRgW5QsaNTgiNu7IglRPxceBJl31iKJ_qV

### Steps to reproduce
open link Reproduction Link above and then see result.

### What is Expected?
solution to align text in el-input tag.

### What is actually happening?
Doesn't align text in el-inpu tag

**Comment by chenyunjie1993** [comment]
css add .el-input input {text-align:center}

**Comment by sorawitw** [comment]
Thank you very much. @chenyunjie1993
