### ISSUE TITLE
[Radio] 建议像 Checkbox 一样支持 Object 的绑定

### ISSUE THREAD

**Issue by unknown-coder** [ElemeFE/element#1891]
### ElementUI version

`1.0.6`

### OS/Browers version

`Win10/Chrome 51`

### Vue version

`2.0.7`

### What is Expected?
`label` 属性建议像 Checkbox 一样支持 Object 的绑定

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/9328734/21374444/d225f9a2-c761-11e6-9581-e21d784b5bc2.png)

**Comment by baiyaaaaa** [comment]
请升级到最新版本
