### ISSUE TITLE
对element未来的几个问题

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#1892]
element飞速发展 很强大 也希望element越来越好，你们辛苦了。

看到1.1 要最低兼容vue 2.1.6 有点苦恼啊 

1. 目前vue周边库有的不兼容那么高 让使用中的人 如果遇到bug 必要升级的话  如何升级？

2. 1.1以下的版本后续是否还维护 ？

3. 后续是否有增加colorpicker组件的计划？

**Comment by QingWei-Li** [comment]
1. 不存在说不兼容 2.1.x 的第三方库，目前也就 2.1.5 有一个 break change 需要第三方的组件用最新的 `vue-template-es2015-compiler` 编译一遍就好了

2. 不会

3. maybe

**Comment by yelingfeng** [comment]
感谢回答

**Comment by reverland** [comment]
1.1以下会维护到什么时候，1.1一出就弃了？

**Comment by QingWei-Li** [comment]
@reverland 并不会有大的 break change，升级成本不大

**Comment by reverland** [comment]
@QingWei-Li datepicker这些听说要重设计重构？

**Comment by QingWei-Li** [comment]
@reverland 我也同说了

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/1942 可以到这讨论
