### ISSUE TITLE
分页内容全部靠右, 按理是不是应该清除浮动

### ISSUE THREAD

**Issue by hisland** [ElemeFE/element#1893]
### ElementUI version
1.0.1

### OS/Browers version
macOS/Chrome 55

### Vue version
2.0.5

### What is Expected?
分页内容全部靠右, 按理是不是应该清除浮动?
```js
layout: '->, prev, pager, next'
```

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/417448/21375565/5701c6c2-c769-11e6-9531-aaecded5f805.png)

**Comment by reverland** [comment]
我这里分页都是居中的啊。。。
