### ISSUE TITLE
cascader 文档添加接口请求demo

### ISSUE THREAD

**Issue by tian720097** [ElemeFE/element#18943]
props: {
          lazy: true,
          lazyLoad (node, resolve) {
            const { level } = node;
            setTimeout(() => {
              const nodes = Array.from({ length: level + 1 })
                .map(item => ({
                  value: ++id,
                  label: `选项${id}`,
                  leaf: level >= 2
                }));
              // 通过调用resolve将子节点数据返回，通知组件数据加载完成
              resolve(nodes);
            }, 1000);
          }
        }
地址选择 显示三级菜单的情况比较多，并且一般情况是 接口请求。 你这里不能写请求方法 this 指向不对

**Comment by tianybr** [comment]
使用箭头函数
