### ISSUE TITLE
[Bug Report] el-image preview bug in element-ui@2.13.0

### ISSUE THREAD

**Issue by lisiyizu** [ElemeFE/element#18942]
### Element UI version
2.13.0

### OS/Browsers version
macos 10.15.3

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/lisiyizu/pen/rNVpZWL?&editable=true

### Steps to reproduce
点击预览图片，左右上一张、下一张之后再关闭，然后点击小图片发现和预览大图显示不一致

showcase on gif: 

![el-image-bug](https://user-images.githubusercontent.com/12014252/76302999-f2521380-62fb-11ea-867c-3284d01439ca.gif)

### What is Expected?
点击小图片发现点击小图片发现预览大图显示一致预览大图显示一致

### What is actually happening?
点击小图片发现和预览大图显示不一致

**Comment by toesbieya** [comment]
这个其实没什么问题，因为每一个el-image会有一个自己的预览组件el-image-viewer，它们的activeIndex是各自独立的，想解决的话需要把el-image-viewer写成一个类似message的全局组件

**Comment by lisiyizu** [comment]
你也是牛逼，明显的bug说没什么问题。你能给一个codepen的解决方案。

**Comment by toesbieya** [comment]
行吧~，你说是就是

**Comment by luckyCao** [comment]
#18975
