### ISSUE TITLE
[Bug Report] The Select Component has a problem by value in el-option

### ISSUE THREAD

**Issue by q8874060** [ElemeFE/element#18954]
### Element UI version
2.13.0

### OS/Browsers version
Win10 / Chrome

### Vue version
3.0.0-alpha.7

### Reproduction Link
https://codepen.io/q8874060/pen/qBdxLRR

### Steps to reproduce
select '黄金糕'.
When value binds an object and label binds an attribute in the object, if only one attribute in the object has the same data as the other objects, the select component will assume that the two objects are the same

### What is Expected?
if value is object , filter by label

### What is actually happening?
if value is object , filter by value

**Comment by lisiyizu** [comment]
你就不能说中文吗？

**Comment by q8874060** [comment]
中文描述一下：在select组件中，option遍历了一个对象数组，当option的value值直接绑定整个对象的时候，如果该对象里面有一个不相关的属性与其他对象相同，那么select组件会认为这两个选项是相同的，从而引发问题，详见链接中的例子，黄金糕和双皮奶被当成了同一个选项。

**Comment by q8874060** [comment]
您好：
&nbsp; &nbsp; &nbsp; 非常感谢您查看我的问题，在问题的评论中，我已用中文描述，英语是机翻的，请见谅。
&nbsp; &nbsp; &nbsp; 这里附上问题的中文描述：
&nbsp; &nbsp; &nbsp;&nbsp;在select组件中，option遍历了一个对象数组，当option的value值直接绑定整个对象的时候，如果该对象里面有一个不相关的属性与其他对象相同，那么select组件会认为这两个选项是相同的，从而引发问题，详见链接中的例子，黄金糕和双皮奶被当成了同一个选项，无论选择哪个都会指向双皮奶。
&nbsp; &nbsp; &nbsp; &nbsp;重现链接：https://codepen.io/q8874060/pen/qBdxLRR
—
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lisiyizu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 上午8:50
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"餖你慯訫ヽ"<654188050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] [Bug Report] The Select Component has a problem by value in el-option (#18954)





 
你就不能说中文吗？
