### ISSUE TITLE
Missing API depending on core-js@2

### ISSUE THREAD

**Issue by yejingquan** [ElemeFE/element#18969]
deprecate element-ui@2.13.0 › async-validator@1.8.5 › babel-runtime@6.26.0 › core-js@^2.4.0 core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by xkem** [comment]
This dependancy has caused me to abandon element-ui altogether. I can't user core-js@2.... :(
