### ISSUE TITLE
[Table]在inline-template中无法使用表单控件

### ISSUE THREAD

**Issue by eachmawzw** [ElemeFE/element#1896]
### ElementUI version
1.0.7

### OS/Browers version
Chrome 55.0.2883.87 m

### Vue version
2.1.6

在不使用el-table时，可以通过v-model绑定属性值来实现动态编码，像这样：
`<span>{{ testValue }}</span>
<el-input v-model="testValue"></el-input>`

在使用el-table时，通过v-model绑定属性值没有效果：代码是这样：
`<el-table :data="testForm"><el-table-column  inline-template label="操作" ><div><span>{{ testValue  }}</span><el-input v-model="testValue "></el-input></div></el-table-column></el-table>`

是否有更好的方式，可以实现我需要的功能？

**Comment by QingWei-Li** [comment]
目前由于利用 `inline-template` 实现的自定义模板，内部环境访问到的实例其实是一个 copy 进行赋值操作是无效的，利用 `@input=update($event)` 然后自己定义一个 update 方法来实现绑定值的效果。

`1.1` 后开始支持 Vue 的 Scoped Slots 能更容易且利于理解的实现自定义模板

```html
<el-table :data="testForm">
  <el-table-column label="操作" >
    <template scope="scope">
      <span>{{ scope.testValue }}</span>
      <el-input v-model="scope.testValue "></el-input>
    </template>
  </el-table-column>
</el-table>
```

**Comment by eachmawzw** [comment]
谢谢，问题已解决

**Comment by liujing0628** [comment]
el-table组件中使用el-select组件，el-select无法选中值

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/1942 1.1 发布后请用 scoped slot

**Comment by yyzych** [comment]
这个时候校验怎么加？

**Comment by ShawshankLin** [comment]
动态添加的表格行总包含了select，不能触发选中值，得用事件来触发吗？

**Comment by ShawshankLin** [comment]
@QingWei-Li
