### ISSUE TITLE
Loading组件与table组件一起用的bug?

### ISSUE THREAD

**Issue by seekwe** [ElemeFE/element#1897]
直接看图,
![12](https://cloud.githubusercontent.com/assets/5528581/21377029/228d9950-c775-11e6-953f-38e71d248d76.png)

**Comment by seekwe** [comment]
![22](https://cloud.githubusercontent.com/assets/5528581/21378152/1869c4bc-c77f-11e6-88c0-2b397eb9199e.png)
正确打开方式?

**Comment by chjw8016** [comment]
这个问题我也遇到了

**Comment by Leopoldthecoder** [comment]
不能算是 bug。Table 的右边框和下边框本身就不是 `.el-table` 元素上的（可以看到截图右边框和下边框被设置成了 0）。如果需要在 Loading 时能看到四个边框，可以在 Loading 显示时手动为 `.el-table` 加上右边框和下边框。

**Comment by Plortinus** [comment]
问题+1

**Comment by Plortinus** [comment]
问题+1
