### ISSUE TITLE
[Bug Report] <el-image> with preview only responses to Esc at the first time, then Esc can never close the preview.

### ISSUE THREAD

**Issue by wxiaoguang** [ElemeFE/element#18983]
### Element UI version
2.13.0

### OS/Browsers version
Chrome Latest

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/z7h59uvp/

### Steps to reproduce
1. Click the image
2. See the Preview dialog
3. Press `Esc` to close the Preview dialog
4. Click the image again
5. This time, `Esc` can not close the Preview dialog

(The sample code is the same as the official one: https://element.eleme.cn/#/zh-CN/component/image )

### What is Expected?
`Esc` can always close the Preview dialog

### What is actually happening?
`Esc` can not close the Preview dialog after the first time

**Comment by cs1707** [comment]
Already fixed, please upgrade the latest version
