### ISSUE TITLE
Menu: option `default-active` should respect/update route if router is enabled

### ISSUE THREAD

**Issue by vilic** [ElemeFE/element#190]
Currently `default-active` will neither update the route nor respect current route on load.

**Comment by baiyaaaaa** [comment]
Menu is not only used for router，it should be completed by the user for keeping the api concise.

**Comment by vilic** [comment]
Not only used for router does not mean shouldn't work fully functional with router. The current `router` option and its behavior are a little bit confusing IMO. If the implementation is expensive, I would be totally on your side. But I don't think it is the case.

Anyway, falling back to router-link.
