### ISSUE TITLE
[bug report] drag the slider component outside the critical point and release the mouse. The tooltip prompt does not disappear normally

### ISSUE THREAD

**Issue by Mr-xue** [ElemeFE/element#19008]
### Element UI version
0.1.0

### OS/Browsers version
Win7 / Chrome 79.0.3945.88

### Vue version
2.6.11

### Reproduction Link
None

### Steps to reproduce
在slider组件上拖动滑块至临界点，鼠标继续拖动至组件外边松开，滑块的tooltip弹窗依旧存在，没有消失。官网的事例中也存在此问题

### What is Expected?
在slider组件上拖动滑块至临界点，鼠标继续拖动至组件外边松开，滑块的tooltip弹窗依旧存在，没有消失。官网的事例中也存在此问题

### What is actually happening?
鼠标拖动至组件界外松开后，tooltip应当消失

**Comment by cheng-github** [comment]
Hi, I got this problem too, by reading the source code I found the solution.
First, add a ref property for your slider compnent, like the following,  

`<el-slider
              @change="change"
              ref="timeSlider">
            </el-slider>`

then,  in the change listener of el-slider, do this,

`change(val){
        // 消除可能不会消失的时间弹出
        this.$refs["timeSlider"].$refs["button1"].handleMouseLeave();
        this.$refs["timeSlider"].$refs["button2"].handleMouseLeave();
}`

hope it can help.

**Comment by Mr-xue** [comment]
> Hi, I got this problem too, by reading the source code I found the solution.
> First, add a ref property for your slider compnent, like the following,
> 
> `<el-slider @change="change" ref="timeSlider"> </el-slider>`
> 
> then, in the change listener of el-slider, do this,
> 
> `change(val){ // 消除可能不会消失的时间弹出 this.$refs["timeSlider"].$refs["button1"].handleMouseLeave(); this.$refs["timeSlider"].$refs["button2"].handleMouseLeave(); }`
> 
> hope it can help.

Tks Man~~
This method can solve my problem, but if i use more el-slider components, it's still troublesome.
Hope the team fix this bug quicky.

**Comment by Mr-xue** [comment]
> Hi, I got this problem too, by reading the source code I found the solution.
> First, add a ref property for your slider compnent, like the following,
> 
> `<el-slider @change="change" ref="timeSlider"> </el-slider>`
> 
> then, in the change listener of el-slider, do this,
> 
> `change(val){ // 消除可能不会消失的时间弹出 this.$refs["timeSlider"].$refs["button1"].handleMouseLeave(); this.$refs["timeSlider"].$refs["button2"].handleMouseLeave(); }`
> 
> hope it can help.

Tks Man~~
This mHope the team fix this bug quicky.ethod can solve my problem, but if i use more el-slider components, it's still troublesome.

**Comment by SimonMayerhofer** [comment]
If they should fix that, I suggest to let the issue open
