### ISSUE TITLE
input clearable 显示多个

### ISSUE THREAD

**Issue by zhuweilong** [ElemeFE/element#19006]
<el-popover placement="bottom" width="260" trigger="click" ref="popoverCostomUrl">
           <el-input v-model="costomURL" placeholder="请输入自定义URL" clearable></el-input>
 </el-popover>
当第一次显示input输入内容，出现clearable图标， 但是再次popover显示时， input 输入内容，会出现俩个clearable图标

**Comment by fairyly** [comment]
@zhuweilong 救急的方法：

```
.el-input__suffix i:nth-child(2) {
  display: none;
}
```
