### ISSUE TITLE
关于el-popover组件时show/hide事件触发问题

### ISSUE THREAD

**Issue by weiyujia** [ElemeFE/element#1901]
### ElementUI version
1.0.2

### OS/Browers version
Chrome 54

### Vue version
2.5.1

### Reproduction Link
http://jsfiddle.net/e7duxbyf/

你好，请教个问题。
为什么show/hide事件在初始化的时候就触发了?而不是显示/隐藏的时候触发？
现在我想做的功能是，el-popover显示的时候，要动态的去后台取数据，现在不知道怎么用这个show/hide事件，下面这个例子，两个事件同时触发http://jsfiddle.net/e7duxbyf/

**Comment by QingWei-Li** [comment]
### Events
| 事件名称 | 说明 | 回调参数 |
|---------|--------|---------|
| show | 显示时触发 | — |
| hide | 隐藏时触发 | — |

这是事件，你要用 `@show` 和 `@hide`

**Comment by jiangxiaohui000** [comment]
楼上正解
