### ISSUE TITLE
TypeError: Cannot read property 'reduce' of null

### ISSUE THREAD

**Issue by mbpframework** [ElemeFE/element#19019]
组件版本"vue": "2.6.10","element-ui": "2.13.0".
我使用table的树形方式会出现这个错.使用常规的不会有这个问题.当我将element-ui降级到2.7.2的时候不会出现这个问题,但是expand-row-keys属性无效了.而之前出现脚本错误的时候expand-row-keys属性还是生效的.

**Comment by mbpframework** [comment]
![image](https://user-images.githubusercontent.com/6149683/77192169-180ac400-6b17-11ea-982f-e556c9130e39.png)

**Comment by mbpframework** [comment]
![image](https://user-images.githubusercontent.com/6149683/77193507-51443380-6b19-11ea-941e-24169c0f44b2.png)

**Comment by zxhbloomer** [comment]
请问该问题是如何解决的啊？

**Comment by mbpframework** [comment]
初始值不能写null,给空数据组即可,比如:list:null----> list:[].
