### ISSUE TITLE
DatePicker禁止用户手动输入，在移动端无法弹出选择器

### ISSUE THREAD

**Issue by JinChengJoker** [ElemeFE/element#1902]
### ElementUI version

1.0.8
### OS/Browers version

Chrome
### Vue version

2.0
### What is Expected?
我想禁止用户输入
<el-date-picker v-model="reservation.consultation_date" type="date" placeholder="选择日期" :picker-options="pickerOptions" :editable="false"></el-date-picker>
但是在移动端必须点击input框里的小图标才会弹出选择器
### What is actually happening?
请问有什么解决办法吗？

**Comment by Leopoldthecoder** [comment]
Element 是桌面端组件库，不保证在移动端能够正常工作。
