### ISSUE TITLE
[Bug Report] 将<router-link/>组件作为<el-menu-item/>组件的title插槽时，报错

### ISSUE THREAD

**Issue by github3817** [ElemeFE/element#19026]
### Element UI version
2.13.0

### OS/Browsers version
win0/chrome80

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/ziyoung/pen/rRKYpd

### Steps to reproduce
将在线演示页面HTML做如下修改：
1. 引入vue-router，增加如下script标签
<script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
2. title插槽内增加一个<router-link/>组件，将#app内代码替换成如下
`<el-menu>
  <el-submenu index="1">
    <template slot="title">
      <i class="el-icon-location"></i>
      <span slot="title">导航一</span>
    </template>
  </el-submenu>
  <el-menu-item index="4">
    <i class="el-icon-setting"></i>
    <span slot="title">
      <router-link to="/xxx">导航四</router-link>
    </span>
  </el-menu-item>
</el-menu>`

### What is Expected?
渲染出a标签，点击可以进行跳转或提示路由配置错误。

### What is actually happening?
控制台报错，提示信息如下：
1. [Vue warn]: Error in render: "TypeError: Cannot read property 'resolve' of undefined"
found in

---> <RouterLink>
       <ElMenuItem> at packages/menu/src/menu-item.vue
         <ElMenu> at packages/menu/src/menu.vue
           <Root>

2. TypeError: Cannot read property 'resolve' of undefined
    at Proxy.render (vue-router.js:1064)
    at VueComponent.Vue._render (vue.js:3551)
    at VueComponent.updateComponent (vue.js:4067)
    at Watcher.get (vue.js:4478)
    at new Watcher (vue.js:4467)
    at mountComponent (vue.js:4074)
    at VueComponent.Vue.$mount (vue.js:9044)
    at VueComponent.Vue.$mount (vue.js:11944)
    at init (vue.js:3125)
    at createComponent (vue.js:5973)

**Comment by github3817** [comment]
Steps to reproduce 的2. 代码被吞了，代码如下：
<--! <el-menu>
  <el-submenu index="1">
    <template slot="title">
      <i class="el-icon-location"></i>
      <span slot="title">导航一</span>
    </template>
  </el-submenu>
  <el-menu-item index="4">
    <i class="el-icon-setting"></i>
    <span slot="title">
      <router-link to="/xxx">导航四</router-link>
    </span>
  </el-menu-item>
</el-menu> -->

**Comment by github3817** [comment]
`<el-menu>
  <el-submenu index="1">
    <template slot="title">
      <i class="el-icon-location"></i>
      <span slot="title">导航一</span>
    </template>
  </el-submenu>
  <el-menu-item index="4">
    <i class="el-icon-setting"></i>
    <span slot="title">
      <router-link to="/xxx">导航四</router-link>
    </span>
  </el-menu-item>
</el-menu>`

**Comment by github3817** [comment]
Steps to reproduce的2的代码被吞了，代码如下：
`<el-menu>
  <el-submenu index="1">
    <template slot="title">
      <i class="el-icon-location"></i>
      <span slot="title">导航一</span>
    </template>
  </el-submenu>
  <el-menu-item index="4">
    <i class="el-icon-setting"></i>
    <span slot="title">
      <router-link to="/xxx">导航四</router-link>
    </span>
  </el-menu-item>
</el-menu>`

**Comment by giligiliduang** [comment]
你需要注册VueRouter，把路由挂载到Vue实例上面
