### ISSUE TITLE
NavMenu组件在页面刷新后，没有显示当前enable的页面

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#1903]
RT

**Comment by reverland** [comment]
要手动改的，我们自己封装了下去检测路由变化

**Comment by njleonzhang** [comment]
@reverland 你的意思是 这个逻辑需要自己处理么 ？
我在页面第一次打开的时候，我可以拿到当前的state，但是我要通过哪个api去设置让navMenu变化呢？
我没有看到Api啊  http://element.eleme.io/#/zh-CN/component/menu

**Comment by reverland** [comment]
default-active？

**Comment by njleonzhang** [comment]
@reverland Tnx, I think I am blind.
