### ISSUE TITLE
[bug report] El select as long as the filterable is true, add a pop-up window in the change event, click the pop-up OK button, and select will get the focus again

### ISSUE THREAD

**Issue by MMmaXingXing** [ElemeFE/element#19058]
### Element UI version
2.13.0

### OS/Browsers version
mac/chrome

### Vue version
3.0.0-alpha.10

### Reproduction Link
https://codepen.io/AstarX/pen/qBdQRGP

### Steps to reproduce
改变select的值，点击弹框，select再次弹出

### What is Expected?
select不弹出

### What is actually happening?
选择弹框之后 select的下拉菜单再次被弹出

**Comment by yangguansen** [comment]
> https://codepen.io/AstarX/pen/qBdQRGP

I try this on the site which you provide, but it's ok on my computer(Mac Chrome)

**Comment by scscms** [comment]
原因是el-select反复获取焦点引起，其实你可以使用blur方法让其失去焦点即可。
<el-select ref="s"
......
change() {
this.$nextTick(this.$refs.s.blur)
.....

**Comment by MMmaXingXing** [comment]
Okay, thank you so much!

**Comment by changeLong** [comment]
> 原因是el-select反复获取焦点引起，其实你可以使用blur方法让其失去焦点即可。 <el-select ref="s" ...... change() { this.$nextTick(this.$refs.s.blur) .....

不正常的表现，应该需要彻底处理，得从源码修改这个逻辑
