### ISSUE TITLE
[bug report] the first page is blank by default when the El image label is opened

### ISSUE THREAD

**Issue by syp2850** [ElemeFE/element#19051]
### Element UI version
0.1.0

### OS/Browsers version
mac/chrome

### Vue version
3.0.0-alpha.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
点击图片 默认第一个是空白  

### What is Expected?
默认第一张

### What is actually happening?
默认第一个是空白，如果只传递一张图片，会因为跳转摁钮消失 而无法显示图片

**Comment by scscms** [comment]
这个组件必须吐槽，
```js
data() {
      return {
        url: 'a.jpeg',
        srcList: [
          'a.jpeg', //注意这里！
          'b.jpeg'
        ]
      }
    }
```
只有当srcList第一个元素等于url时才不会空白，这完全是违背缩略图规则！
同时建议添加一个属性配置，可以选择再次点击预览图片时是否应该强制返回第一张图片！

**Comment by haoyaxin** [comment]
![image](https://user-images.githubusercontent.com/12777245/78334467-6b245280-75be-11ea-88a0-f84cd5a12bc6.png)
官网例子可以复现这个bug

**Comment by luckyCao** [comment]
#18975
