### ISSUE TITLE
table组件自定义标题头，使用具名插槽 slot="header" 不法实现el-select数据绑定

### ISSUE THREAD

**Issue by liujiayun0804** [ElemeFE/element#19060]

**Comment by shiyuanping** [comment]
我也遇到同样的问题，请问您解决了吗

**Comment by liujiayun0804** [comment]
都是很久之前的了，有点遗忘了。不过有点印象，你把你那段代码贴给我看看呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 下午3:04
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"刘佳运"<26742310@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] table组件自定义标题头，使用具名插槽 slot="header" 不法实现el-select数据绑定 (#19060)





 
我也遇到同样的问题，请问您解决了吗

**Comment by liujiayun0804** [comment]
> 我也遇到同样的问题，请问您解决了吗

解决了哈，想起了。你用的插槽 是不是  <template slot="header"> 这样写的，这种方式是低版本vue是方式，我们现在基本都用的2.4以上的vue，所有存在兼容性问题哈。

解决方案： 把 <template slot="header"> 改写成 <template #header>

**Comment by shiyuanping** [comment]
element-ui是用最新的2.15.0，使用了里面的自定义表头，然后可以正常显示。但是当我选择下拉项的时候，数据绑定不了；输入框也输入不了值




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 下午3:19
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"925356588"<925356588@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] table组件自定义标题头，使用具名插槽 slot="header" 不法实现el-select数据绑定 (#19060)





 都是很久之前的了，有点遗忘了。不过有点印象，你把你那段代码贴给我看看呢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2021年2月1日(星期一) 下午3:04 
 收件人:&amp;nbsp;"ElemeFE/element"<element@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"刘佳运"<26742310@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ElemeFE/element] table组件自定义标题头，使用具名插槽 slot="header" 不法实现el-select数据绑定 (#19060) 
 
 
 
 
 
   
 我也遇到同样的问题，请问您解决了吗

**Comment by shiyuanping** [comment]
啊啊啊啊啊，解决了！ 太感谢你了！~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 下午3:25
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"925356588"<925356588@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] table组件自定义标题头，使用具名插槽 slot="header" 不法实现el-select数据绑定 (#19060)





  
我也遇到同样的问题，请问您解决了吗
  
解决了哈，想起了。你用的插槽 是不是   这样写的，这种方式是低版本vue是方式，我们现在基本都用的2.4以上的vue，所有存在兼容性问题哈。 

解决方案： 把  改写成 <template #header&gt;

**Comment by liujiayun0804** [comment]
> 啊啊啊啊啊，解决了！ 太感谢你了！~

不用客气
