### ISSUE TITLE
Dialog 的modal、close-on-click-modal、close-on-press-escape设置为false后，还是有遮罩层、点击遮罩层或者按esc都能关闭

### ISSUE THREAD

**Issue by hardweight** [ElemeFE/element#1906]
Dialog 的modal、close-on-click-modal、close-on-press-escape设置为false后，还是有遮罩层、点击遮罩层或者按esc都能关闭

**Comment by Leopoldthecoder** [comment]
请确保写的是 `:modal="false"`，而不是 `modal="false"`

**Comment by xiatiandenixi** [comment]
:modal="false" 写了遮罩层颜色变了 但是页面里的元素还是被一个position：fixed的全屏幕大小的div盖住的
