### ISSUE TITLE
用Element写了一个单页后台，请指点

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#1907]
https://git.oschina.net/bfgdqch/EleAdmin

**Comment by Kingwl** [comment]
什么鬼。、、、

**Comment by furybean** [comment]
@jixzfw 建议把介绍里面的“饿了吗”换成正确的写法“饿了么”。

**Comment by jixzfw** [comment]
@furybean 不好意思，刚改了

**Comment by QingWei-Li** [comment]
👏 欢迎你给 https://github.com/ElementUI/awesome-element 提 PR 以便我们能收录

**Comment by xiaolongyuan** [comment]
不错不错

**Comment by jixzfw** [comment]
@QingWei-Li 狠狠挠头中，不太会git，还不知道在哪里提，提到issues中？
