### ISSUE TITLE
项目中没有使用Node，直接从unpkg引用element-ui和vue，这种情况下如何做国际化

### ISSUE THREAD

**Issue by focusdada** [ElemeFE/element#1909]
## 项目中没有使用Node，直接从unpkg引用element-ui和vue，这种情况下如何做国际化 ##
> 前端知识比较浅，项目中导入的element-ui和vue已经成功跑起来，开发效率也有了很大的提升。现在碰到了国际化的问题，由于项目中未引用Node，这种情况下如何做国际化，盼回复，非常感谢

**Comment by QingWei-Li** [comment]
没有提供多语言文件的 CDN，因为没找到优雅的通过 script 加载语言包的方式。你现在可以将 `locale/`里需要的文件内容复制出来，就像 vue-i18n 那样使用即可

```js
// Copy https://github.com/ElemeFE/element/blob/dev/src/locale/lang/en.js
var en = {
  el: {
    datepicker: {
      now: 'Now',
      today: 'Today',
      cancel: 'Cancel',
      clear: 'Clear',
      confirm: 'OK',
     // ...
    }
  }
};

// 加载英文
ELEMENT.locale(en)
```

**Comment by focusdada** [comment]
@QingWei-Li  Many thanks
