### ISSUE TITLE
http-request上传成功后，修改file-list的值，会导致界面“抖动”

### ISSUE THREAD

**Issue by HoldSkill** [ElemeFE/element#19099]
http-request上传成功后，修改file-list的值，会导致界面“抖动”。
![bug](https://user-images.githubusercontent.com/25190239/78221211-8e36ff80-74f5-11ea-8496-5a0716e3ca9f.gif)

**Comment by HoganGolden** [comment]
@qing8888 请问这个问题解决了吗
