### ISSUE TITLE
[Feature Request] Popconfirm 气泡确认框 文档不完善

### ISSUE THREAD

**Issue by fisher-zh** [ElemeFE/element#19102]
### Existing Component
是

### Component Name
Popconfirm

### Description
Popconfirm 气泡确认框 文档内未描述点击确定后触发的事件 代码中为 onConfirm，希望可以在文档中写明，方便开发者

**Comment by iamkun** [comment]
Now fixed to the correct 'confirm' and 'cancel' event name in #20240
