### ISSUE TITLE
[Bug Report] 2.13.0版本预览图片无法出来

### ISSUE THREAD

**Issue by zhangziyi123** [ElemeFE/element#19117]
### Element UI version
2.13.0

### OS/Browsers version
window10

### Vue version
3.0.0-alpha.11

### Reproduction Link
https://github.com/ElemeFE/element/issues/new

### Steps to reproduce
https://element.eleme.cn/2.13/#/zh-CN/component/image

### What is Expected?
https://element.eleme.cn/2.13/#/zh-CN/component/image

### What is actually happening?
https://element.eleme.cn/2.13/#/zh-CN/component/image

**Comment by luckyCao** [comment]
#18975
