### ISSUE TITLE
element已并入ant design的事实

### ISSUE THREAD

**Issue by kooriookami** [ElemeFE/element#19120]
就ant design最近一次大更新，增加的formModel组件，文档照搬element，几乎一字未改
![image](https://user-images.githubusercontent.com/38392315/78502523-1fc39d00-7794-11ea-82a0-205113f675d9.png)
ant design

![image](https://user-images.githubusercontent.com/38392315/78502528-2520e780-7794-11ea-95e3-29d498fc87b4.png)
element

从源码也能看来，大部分代码是直接从element改过去的
![image](https://user-images.githubusercontent.com/38392315/78502511-0fabbd80-7794-11ea-9933-5611aeec465a.png)
什么意思应该都明白了

**Comment by Kimmyzhao** [comment]
所以以后不会有 element-ui 了么

**Comment by xlz26296** [comment]
为啥不是理解为 ant design 抄 element-ui 😂？

**Comment by Windelight** [comment]
应该就是“实锤”了，在文档首页
‘https://ant.design/docs/spec/introduce-cn’ 里面讲到eleme已经在用了

**Comment by Kimmyzhao** [comment]
> 为啥不是理解为 ant design 抄 element-ui 😂？

太久没动静了

**Comment by sendya** [comment]
我猜你没真正关注过，所以会被表象所骗。
只是真的照抄表单组件，并不是并入 ant design

![image](https://user-images.githubusercontent.com/5404542/78622459-c48acb00-78b7-11ea-9ae8-85f934e5b4d3.png)

**Comment by DiamondYuan** [comment]
ant design 并不是阿里的人维护的。而是由社区用户维护的。

**Comment by kooriookami** [comment]
还是希望element别凉，哪怕换个名字。我个人觉得ui比ant的好看，用起来也更vue

**Comment by zombieJ** [comment]
> ant design 并不是阿里的人维护的。而是由社区用户维护的。

`ant design` => `ant design vue`，大哥别不一小心就造个大新闻哇……

**Comment by chenshuai2144** [comment]
应该改一下标题，我查了文档没发现有这个api，定睛一看是 ant design vue

**Comment by AshoneA** [comment]
搞个大新闻，再把 antd 批评一番，你们呐， naive

**Comment by Looper-01** [comment]
ANTD的态度很好，赞，支持~

**Comment by Amour1688** [comment]
> 搞个大新闻，再把 antd 批评一番，你们呐， naive

将来报道上有偏差你们要负责

**Comment by a631807682** [comment]
并没有所谓的并入，但是饿了么公司是否重新维护这个项目，那是决策的问题。核心维护人员变动几乎是肯定的，但从`commit`历史来看也不是第一次。

好在的是这是一个开源项目，我目前在重构`element`以支持`vue-next`，希望当`element`重新维护的时候不至于落后太多。或者不再维护之后新版本由社区维护。

由于我个人能力有限，进度可能不会很理想，我计划在`alpha`阶段寻求大家的贡献。[ele-next](https://github.com/a631807682/ele-next)

**Comment by Kimmyzhao** [comment]
> 并没有所谓的并入，但是饿了么公司是否重新维护这个项目，那是决策的问题。核心维护人员变动几乎是肯定的，但从`commit`历史来看也不是第一次。
> 
> 好在的是这是一个开源项目，我目前在重构`element`以支持`vue-next`，希望当`element`重新维护的时候不至于落后太多。或者不再维护之后新版本由社区维护。
> 
> 由于我个人能力有限，进度可能不会很理想，我计划在`alpha`阶段寻求大家的贡献。[ele-next](https://github.com/a631807682/ele-next)

可惜我是一个后端开发

**Comment by LTAND** [comment]
可以在vue3时，来一次elementUI重构更新，对vue2版本elementUI维护稳定版，这样或许会更好

**Comment by kooriookami** [comment]
element今天更新了

**Comment by cjsky666** [comment]
哈哈哈哈，社区牛逼！更新了~

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147
