### ISSUE TITLE
[Feature Request] Select with Button instead of Input

### ISSUE THREAD

**Issue by perska124** [ElemeFE/element#19123]
### Existing Component
Yes

### Component Name
El-Select

### Description
Is it or will it be possible to have select functionality on button click?
I would like to have a button with an icon and on click to see selection.

![obraz](https://user-images.githubusercontent.com/9116830/78558948-cc912f00-7813-11ea-83fa-83ea81d408e3.png)

**Comment by CarterLi** [comment]
What's the difference from a normal dropdown?

**Comment by perska124** [comment]
> 
> 
> What's the difference from a normal dropdown?

The difference is multiselection and showing selected item. But now i see that this functionality could be build around dropdown with custom dropdown element and managing selected items by ourselves. I don't know why i was so fixed on select element...
