### ISSUE TITLE
select 能不能同时获取value和label 是不是还没有selected属性？

### ISSUE THREAD

**Issue by kiss-burn** [ElemeFE/element#1914]
场景需要 需要同时获取到value和label 不知有没有方案

**Comment by Leopoldthecoder** [comment]
请具体描述。

**Comment by kiss-burn** [comment]
现在做了一个车辆管理系统，很多地方的车辆信息是通过车牌号对应的ID读取，展示的时候要展示车牌号，现在需要做一个默认选择车辆的功能，比如我现在需要查询车辆基本信息，以及车辆的维护信息。车辆基本信息和车辆维护信息是不同的路由两个选项，当在车辆基本信息的地方选择了一个车牌号的时候（车牌号是select组件 label是车牌号 value是车牌号ID 车辆有关信息通过ID查询），车辆维护信息的查询条件 也会默认是车辆基本信息选择的车牌号。这时候查询的时候需要value（车牌号ID） 展示的时候 需要label（车牌号） 如果不能同时获取value和label 那么我得写个函数每次通过ID去对比出车牌号

**Comment by kiss-burn** [comment]
@Leopoldthecoder 现在做了一个车辆管理系统，很多地方的车辆信息是通过车牌号对应的ID读取，展示的时候要展示车牌号，现在需要做一个默认选择车辆的功能，比如我现在需要查询车辆基本信息，以及车辆的维护信息。车辆基本信息和车辆维护信息是不同的路由两个选项，当在车辆基本信息的地方选择了一个车牌号的时候（车牌号是select组件 label是车牌号 value是车牌号ID 车辆有关信息通过ID查询），车辆维护信息的查询条件 也会默认是车辆基本信息选择的车牌号。这时候查询的时候需要value（车牌号ID） 展示的时候 需要label（车牌号） 如果不能同时获取value和label 那么我得写个函数每次通过ID去对比出车牌号

**Comment by Leopoldthecoder** [comment]
是的，需要自己去找。
