### ISSUE TITLE
[Feature Request] 能否为el-select的自定义默认值添加value和label

### ISSUE THREAD

**Issue by 378406712** [ElemeFE/element#19140]
### Existing Component
是

### Component Name
Select 选择器

### Description
select中默认勾选显示的选项是v-model绑定data下的属性，我data下的填的是中文‘全部日期’，而后端意思是最好传的是‘all’
   <el-select v-model="select" @change="getMedia()">

<el-option label="全部日期" value="全部日期"></el-option>//这条是默认的选项，下面循环的是从后端拿的
                <el-option
                  v-for="(item, index) in DateList"
                  :key="index"
                  :label="item"
                  :value="item"
                >
                </el-option>
</el-select>
data() {
    return {
      select: '全部日期'
}
//小白，求指教

**Comment by 378406712** [comment]
<el-option label="全部日期" value="全部日期"></el-option>
                <el-option
                  v-for="(item, index) in DateList"
                  :key="index"
                  :label="item"
                  :value="item"
                >
                </el-option>

**Comment by 378406712** [comment]
<el-option label="全部日期" value="全部日期"></el-option>
                <el-option
                  v-for="(item, index) in DateList"
           ...
                >
                </el-option>

**Comment by 378406712** [comment]
> ### Existing Component
> 是
> 
> ### Component Name
> Select 选择器
> 
> ### Description
> select中默认勾选显示的选项是v-model绑定data下的属性，我data下的填的是中文‘全部日期’，而后端意思是最好传的是‘all’
> <el-select v-model="select" @change="getMedia()">
> 
> //这条是默认的选项，下面循环的是从后端拿的
> 
> <el-option label="全部日期" value="全部日期"/>

<el-option v-for="(item, index) in DateList"/>
> 
> data() {
> return {
> select: '全部日期'
> }
> //小白，求指教

**Comment by scvzerng** [comment]
你直接
```javascript

<el-select v-model="select" @change="getMedia()">
<el-option label="全部日期" value="all"/>
<el-option v-for="(item, index) in DateList"/>
</el-select>

```
不就好了

**Comment by 378406712** [comment]
> 你直接
> 
> ```js
> <el-select v-model="select" @change="getMedia()">
> <el-option label="全部日期" value="all"/>
> <el-option v-for="(item, index) in DateList"/>
> </el-select>
> ```
> 
> 不就好了

我的意思是下拉菜单中初始化绑定的那个select，我data下绑定的是"全部日期"，显示在下拉框中默认（类似于placeholder）中就是全部日期，打印出的也是"全部日期",但是想要拿到的是all,不知道怎么给。选择第一条我是<el-option label="全部日期" value="all"/>这样写的， 打印出的是all

**Comment by 378406712** [comment]
emmm，好像这个默认值的意义就是placeholder,初始渲染就是给的全部日期，没必要给这个默认值加value

**Comment by scvzerng** [comment]
> > 你直接
> > ```js
> > <el-select v-model="select" @change="getMedia()">
> > <el-option label="全部日期" value="all"/>
> > <el-option v-for="(item, index) in DateList"/>
> > </el-select>
> > ```
> > 
> > 
> > 不就好了
> 
> 我的意思是下拉菜单中初始化绑定的那个select，我data下绑定的是"全部日期"，显示在下拉框中默认（类似于placeholder）中就是全部日期，打印出的也是"全部日期",但是想要拿到的是all,不知道怎么给。选择第一条我是`<el-option label="全部日期" value="all"/>`这样写的， 打印出的是all

对啊 你后端要的不就是all你直接传all不是对的么

**Comment by 378406712** [comment]
> > > 你直接
> > > ```js
> > > <el-select v-model="select" @change="getMedia()">
> > > <el-option label="全部日期" value="all"/>
> > > <el-option v-for="(item, index) in DateList"/>
> > > </el-select>
> > > ```
> > > 
> > > 
> > > 不就好了
> > 
> > 
> > 我的意思是下拉菜单中初始化绑定的那个select，我data下绑定的是"全部日期"，显示在下拉框中默认（类似于placeholder）中就是全部日期，打印出的也是"全部日期",但是想要拿到的是all,不知道怎么给。选择第一条我是`<el-option label="全部日期" value="all"/>`这样写的， 打印出的是all
> 
> 对啊 你后端要的不就是all你直接传all不是对的么

但是我前端初始化时下拉框中想 默认项显示的是 “全部日期”，传给后端的是"all",因为绑定的v-model 绑定的select值只能是"全部日期"/‘all’中的一个，传给后端的也是这两个值中的一个，我的意思是做到分开,前端显示label"全部日期",后端传value值"all",就是option中那样

**Comment by 378406712** [comment]
现在我是，在进入页面，初始化下拉框显示的是"全部日期"el-option的第一条也是label="全部日期" value="全部日期" ,初始化传的是v-model="select"  select:'全部日期',显示在前端和传给后端的都是这个"全部日期"
后端做判断if (date === '全部日期') { //这里想传给的是'all'
    Media.find({ username }, function(err, docs) {
      if (!err) res.send(docs)
    })

**Comment by 378406712** [comment]
就是能否做到，前端v-model绑定的值，显示在前端是中文"全部日期",后端传给的value是"all',初始渲染传的只有一个值，不能做到显示在前端的值跟传给后端的值 不同

**Comment by scvzerng** [comment]
> > > > 你直接
> > > > ```js
> > > > <el-select v-model="select" @change="getMedia()">
> > > > <el-option label="全部日期" value="all"/>
> > > > <el-option v-for="(item, index) in DateList"/>
> > > > </el-select>
> > > > ```
> > > > 
> > > > 
> > > > 不就好了
> > > 
> > > 
> > > 我的意思是下拉菜单中初始化绑定的那个select，我data下绑定的是"全部日期"，显示在下拉框中默认（类似于placeholder）中就是全部日期，打印出的也是"全部日期",但是想要拿到的是all,不知道怎么给。选择第一条我是`<el-option label="全部日期" value="all"/>`这样写的， 打印出的是all
> > 
> > 
> > 对啊 你后端要的不就是all你直接传all不是对的么
> 
> 但是我前端初始化时下拉框中想 默认项显示的是 “全部日期”，传给后端的是"all",因为绑定的v-model 绑定的select值只能是"全部日期"/‘all’中的一个，传给后端的也是这两个值中的一个，我的意思是做到分开,前端显示label"全部日期",后端传value值"all",就是option中那样

https://codepen.io/scvzerng/pen/VwveVRL?editors=1111

**Comment by 378406712** [comment]
> > > > > 你直接
> > > > > ```js
> > > > > <el-select v-model="select" @change="getMedia()">
> > > > > <el-option label="全部日期" value="all"/>
> > > > > <el-option v-for="(item, index) in DateList"/>
> > > > > </el-select>
> > > > > ```
> > > > > 
> > > > > 
> > > > > 不就好了
> > > > 
> > > > 
> > > > 我的意思是下拉菜单中初始化绑定的那个select，我data下绑定的是"全部日期"，显示在下拉框中默认（类似于placeholder）中就是全部日期，打印出的也是"全部日期",但是想要拿到的是all,不知道怎么给。选择第一条我是`<el-option label="全部日期" value="all"/>`这样写的， 打印出的是all
> > > 
> > > 
> > > 对啊 你后端要的不就是all你直接传all不是对的么
> > 
> > 
> > 但是我前端初始化时下拉框中想 默认项显示的是 “全部日期”，传给后端的是"all",因为绑定的v-model 绑定的select值只能是"全部日期"/‘all’中的一个，传给后端的也是这两个值中的一个，我的意思是做到分开,前端显示label"全部日期",后端传value值"all",就是option中那样
> 
> https://codepen.io/scvzerng/pen/VwveVRL?editors=1111

感谢大佬指教，已经做好了，谢谢
