### ISSUE TITLE
[bug report] when the table is fixed and the number of changed columns of the table is set dynamically, the El table alignment body wrapper height is reduced

### ISSUE THREAD

**Issue by kavinluo** [ElemeFE/element#19142]
### Element UI version
2.10.1

### OS/Browsers version
Mac，window，Chrome 80

### Vue version
2.5.3

### Reproduction Link
https://codepen.io/iuxw/pen/MWgGgGy

### Steps to reproduce
Problem 1: when the table has a fixed header and the columns are changed dynamically, the table el-tablearbitration body-wrapper height sometimes gets lower
Problem 2: when a table has a fixed header and a column is fixed, the column changes dynamically, and the first row of the fixed column gets taller

### What is Expected?
When you change the column, the height should not change

### What is actually happening?
Height discrepancy

**Comment by northernCold** [comment]
you can invoke doLayout() after change column，but the table will shake
```
this.$nextTick(() => { this.$refs['table'].doLayout() })
```
e.g https://codepen.io/northernCold/pen/qBOOZwg

**Comment by kavinluo** [comment]
I finally can only pass through in frustration, re-render the table when checking each one
