### ISSUE TITLE
关于tree展开的问题

### ISSUE THREAD

**Issue by jamslee** [ElemeFE/element#1916]
1.能否增加mouseenter/hover展开树的选项，因为很多时候并不知道树的子节点的内容，hover可以快速的打开，然后点击选中

2.能否增加水平展开的选项，显然如果内容很长，垂直展开不是很友好。

盼望恢复（或者我可以通过什么方法在现有的基础上解决）

**Comment by furybean** [comment]
听起来都不像常见的需求，我加个 discussion 标签，看看其他人是不是有类似的需求。

**Comment by jamslee** [comment]
可能我表述的并不是很清楚，我们之前处理树是用的这个http://jqueryui.com/menu/。现在要换ui框架，发现迁移时目前仅此一处，覆盖不到需求

**Comment by furybean** [comment]
@jamslee 这个不是树，是另一种组件，一般叫做 Menu 或者 Cascader。
