### ISSUE TITLE
关于Tab标签页下拉选项的实现？

### ISSUE THREAD

**Issue by yuanyuanshen** [ElemeFE/element#1917]
目前<el-tabs></el-tabs>标签页是一页的切换，想问下怎么实现某个标签页有标签有下拉选项这种呢？

**Comment by baiyaaaaa** [comment]
label-content 属性可以实现自定义的标签页

**Comment by yuanyuanshen** [comment]
有没有demo啊，，文档上没有看到，或者发个地址。谢谢

**Comment by yuanyuanshen** [comment]
哥。。。报错呀。
![错误](http://d3.freep.cn/3tb_161222142856offj580819.png)

**Comment by baiyaaaaa** [comment]
需要BABEL JSX插件的支持， https://github.com/vuejs/babel-plugin-transform-vue-jsx

**Comment by yuanyuanshen** [comment]
能不能说下JSX是干嘛的？为什么需要这插件？我看了一下，我的理解就是把HTML转成js语言添加到对应的位置上，是这样理解么？那对于tabs高级的设置，需要别的插件，感觉官方文档可以加一下。不然想向我这样用的估计会有好多人会问你吧。

**Comment by Leopoldthecoder** [comment]
@yuanyuanshen [FAQ](https://github.com/ElemeFE/element/blob/master/FAQ.md) 第三条。

**Comment by yuanyuanshen** [comment]
这个错误呢，点击事件@不识别啊
![cuowu](http://d2.freep.cn/3tb_161222145758ka2w580819.png)

**Comment by yuanyuanshen** [comment]
谢谢你们了。。终于搞定了。。棒棒哒。还是希望官方文档能有个详细的说明。

**Comment by baiyaaaaa** [comment]
文档稍后会补上

**Comment by baiyaaaaa** [comment]
你的item没有对command赋值当然是undefined了哥

**Comment by yuanyuanshen** [comment]
完全是考验理解能力啊。还有一个问题
!(cuowu)[http://d3.freep.cn/3tb_161222161226spa0580819.png]
右边小三角有hover事件，但是小三角也能点击啊，每次点击页面就会闪一下，感觉是默认事件，我怎么能把默认事件阻止掉。组件是一体的。不知道写在哪里

**Comment by panchengjun** [comment]
![image](https://cloud.githubusercontent.com/assets/17994884/21422348/39804e5c-c872-11e6-9179-821364e58d17.png)
![image](https://cloud.githubusercontent.com/assets/17994884/21422359/461527a0-c872-11e6-83c1-ee159563a37a.png)
没有被执行，log没有打印出来。是什么问题呢？
