### ISSUE TITLE
[Bug Report] <el-input> bug in set new value

### ISSUE THREAD

**Issue by dima-klimenkov** [ElemeFE/element#19188]
### Element UI version
2.13.0

### OS/Browsers version
Chrom 80.0.3987.163, (64 бит)

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/neo2a170/

### Steps to reproduce
When I create 2 'input' components, after entering the value in one input, the value is transferred to the second at the same time. If I understand correctly, this is an error

`<el-input @input="changeName"  size="mini" v-model="meta.alias"></el-input>`				
`<el-input @input="changeAlias"  size="mini" v-model="meta.name"></el-input>`

### What is Expected?
Current input value must be changed

### What is actually happening?
The value is assigned to both the first and second `<el-input>`

**Comment by CarterLi** [comment]
Isn't it because of `v-model="meta.alias"`?

**Comment by dima-klimenkov** [comment]
> Isn't it because of `v-model="meta.alias"`?
No, if exclude object meta, the result remains the same
https://jsfiddle.net/rcfL0dan/

**Comment by CarterLi** [comment]
> > Isn't it because of `v-model="meta.alias"`?
> > No, if exclude object meta, the result remains the same
> > https://jsfiddle.net/rcfL0dan/

`v-model="meta.alias"` will be translated to `:value="meta.alias" @input="val => meta.alias = val"`. Combining with `@input="changeName"` it will be `:value="meta.alias" @input="val => meta.name = meta.alias = val"`

See [doc](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components) for detail

**Comment by dima-klimenkov** [comment]
> > > Isn't it because of `v-model="meta.alias"`?
> > > No, if exclude object meta, the result remains the same
> > > https://jsfiddle.net/rcfL0dan/
> 
> `v-model="meta.alias"` will be translated to `:value="meta.alias" @input="val => meta.alias = val"`. Combining with `@input="changeName"` it will be `:value="meta.alias" @input="val => meta.name = meta.alias = val"`
> 
> Read the doc for detail: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components


Thanks, I understood my mistake. Sorry for disturbing
