### ISSUE TITLE
想问一下，我用element组件 构造一个表单，有时候 勾选一个checkbox 或者 radio， 其他的组件 比如select组件 会有跳动的效果。。问题出在哪？是动画引起的吗

### ISSUE THREAD

**Issue by shortbaby** [ElemeFE/element#1919]

**Comment by kiss-burn** [comment]
我也遇见相同的情况 时间控件选择 会带动select组件变换 但是直接选择select组件不给默认值选中的值不会显示，但是绑定的数据能够获取得到

**Comment by Leopoldthecoder** [comment]
两位请给出在线 demo

**Comment by shortbaby** [comment]
我的项目比较大，我是在一个 dialog里面 有一个form表单，表单里面有很多个输入项，有checkbox由radio还有input和 select ，奇怪的是 当选择radio或者checkbox的时候，其他的select组件的三角形icon会向左跳动一下，但不是所有的select组件都会跳，只有一部分有这样的效果，虽然不影响什么？但是感觉不知道什么原因？在线demo的话，可能需要在https://jsfiddle.net/ 上新创建一个。等我建好了 复现了这个问题 再来提一个issue吧。

**Comment by fangdown** [comment]
我也有这样的问题，在dialog中添加图片上传组件 或者 CheckBox选择时会有这样的抖动

**Comment by ifsmile** [comment]
问题DEMO：
http://jsfiddle.net/0y0jjj4w/

说明：下拉滚动条选择 radio 或 checkbox 或闪烁，去除css中 z-index 后正常。

**Comment by ifsmile** [comment]
奇怪，如果把谷歌更新至最新版本抖动就没了

**Comment by linyif2** [comment]
楼上说的z-index导致的抖动我也遇到过，尤其是如果页面存在滚动悬停的板块上有表单组件的话。
据我本地项目测试除了z-index处理层叠关系的时候在google浏览器上有这种抖动情况以外
还有一个情况，如果组件在position:fixed定位的容器内部，那么他会同时带动页面上的所有position:fixed的元素一起抖...第一次发现的时候我以为眼睛花了...

我用的是Chorme 54.0.2840.71
以上两种情况也不是每次必出现，也许有些触发条件我还没发现，组件包括：select，radio，checkbox，switch

**Comment by HUA616436641** [comment]
我的输入框内容是中文的话就不会抖，是数字的就会抖。。。

**Comment by lu-xu** [comment]
试试 overflow:scroll

**Comment by bierenjiadehaizi** [comment]
我的项目是一个弹框里面有很多多选框 ,我通过css覆盖了el-checkbox-group的属性: font-size: 0 ; 问题解决了.

**Comment by weijiafen** [comment]
是的，我在dialog上使用了radio就出现了抖动现象，chrome62。把dialog的position:absolute属性去除后不会抖动，确认是动画和定位一起出现时导致的bug，但是定位没办法去掉，所以我找到了动画的属性并关闭了动画：.el-radio__inner::after这个属性的transition重写为none就可以了
