### ISSUE TITLE
v2.13.1  failed to build some of .vue file that with jsx syntax

### ISSUE THREAD

**Issue by David-NJ** [ElemeFE/element#19201]
### Element UI version
2.13.1

### OS/Browsers version
Windows10

### Vue version
2.5.21

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
clone version 2.13.1 from github，run "npm install",  run "npm run dist"

got this error:
ERROR in ./packages/transfer/src/transfer-panel.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./packages/transfer/src/transfer-panel.vue?vue&type=script&lang=js&) 91:14
Module parse failed: Unexpected token (91:14)
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           : transfer.$scopedSlots.default
|             ? transfer.$scopedSlots.default({ option: this.option })
>             : <span>{ this.option[panel.labelProp] || this.option[panel.keyProp] }</span>;
|       }
|     }
 @ ./packages/transfer/src/transfer-panel.vue?vue&type=script&lang=js& 1:0-132 1:148-151 1:153-282 1:153-282
 @ ./packages/transfer/src/transfer-panel.vue
 @ ./node_modules/vue-loader/lib??vue-loader-options!./packages/transfer/src/main.vue?vue&type=script&lang=js&
 @ ./packages/transfer/src/main.vue?vue&type=script&lang=js&
 @ ./packages/transfer/src/main.vue
 @ ./packages/transfer/index.js
 @ ./src/index.js
 @ multi ./src/index.js

node version 12.16.2

### What is Expected?
built successfully

### What is actually happening?
failed to built

**Comment by Rainmen-xia** [comment]
same error

**Comment by zhenxin111** [comment]
how fix

**Comment by superMonkey-T** [comment]
Same problem, no solution？
