### ISSUE TITLE
[Feature Request] element will rebuild by vue3.0 in future ,maybe in 4 months

### ISSUE THREAD

**Issue by zjxzjx54** [ElemeFE/element#19228]
### Existing Component
Yes
### Component Name
all components in element-UI

### Description
element will rebuild by vue3.0 in future ,maybe in 4 months?

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment]
Duplicate of #20375
