### ISSUE TITLE
elementUI  无法支持 vue3.0 beta 

### ISSUE THREAD

**Issue by bigbigtime** [ElemeFE/element#19221]
**./plugins/element.js**
以下内容
import Vue from "vue";
import Element from "element-ui";
import "element-ui/lib/theme-chalk/index.css";
Vue.use(Element);

import Vue from "vue"; 无法被找到

**Comment by lvlingjie** [comment]
现在是基于2.0版本的，3.0版本肯定不一样了啊，等新版本吧

**Comment by bigbigtime** [comment]
是的，今天研究了一天，也没办法改发。很想知道什么时候出新版本，可以支持vue3.0 beta版本。
这样就可以开始学习

**Comment by bacy** [comment]
听说负责element-ui的同学离职了，vue3怕是上不了哦

**Comment by liamwang** [comment]
@bacy 真的吗？有点担忧啊element-ui的后续发展啊。

**Comment by ever391** [comment]
看中文的Issues 真爽!

**Comment by bigbigtime** [comment]
啥



---原始邮件---
发件人: "三九"<notifications@github.com&gt;
发送时间: 2020年4月28日(周二) 中午12:26
收件人: "ElemeFE/element"<element@noreply.github.com&gt;;
抄送: "bigbigtime"<409019683@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ElemeFE/element] elementUI  无法支持 vue3.0 beta  (#19221)




 
看中文的Issues 真爽!

**Comment by ever391** [comment]
> 啥
> […](#)
> ---原始邮件--- 发件人: "三九"<notifications@github.com&gt; 发送时间: 2020年4月28日(周二) 中午12:26 收件人: "ElemeFE/element"<element@noreply.github.com&gt;; 抄送: "bigbigtime"<409019683@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [ElemeFE/element] elementUI 无法支持 vue3.0 beta (#19221) 看中文的Issues 真爽! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

之前看issue 都是英文，看着累

**Comment by bigbigtime** [comment]
发个链接看看



---原始邮件---
发件人: "三九"<notifications@github.com&gt;
发送时间: 2020年4月28日(周二) 中午1:29
收件人: "ElemeFE/element"<element@noreply.github.com&gt;;
抄送: "bigbigtime"<409019683@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ElemeFE/element] elementUI  无法支持 vue3.0 beta  (#19221)




  
啥
 …
 ---原始邮件--- 发件人: "三九"<notifications@github.com&gt; 发送时间: 2020年4月28日(周二) 中午12:26 收件人: "ElemeFE/element"<element@noreply.github.com&gt;; 抄送: "bigbigtime"<409019683@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [ElemeFE/element] elementUI 无法支持 vue3.0 beta (#19221) 看中文的Issues 真爽! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
之前看issue 都是英文，看着累

**Comment by bacy** [comment]
> @bacy 真的吗？有点担忧element-ui的后续发展啊。

已经很久没有发版本了。。。隔壁ant-design搞了个大版本

**Comment by bigbigtime** [comment]
负责element-ui的同学离职了？真的假的，好方啊！！vue3岂不是不行了，生态跟不上啊

**Comment by vanoneang** [comment]
有没有官方回复呢？

**Comment by wkl007** [comment]
转ant-design-vue好久了，那边vue 3.0适配也在进行中。

**Comment by wuyongzhi** [comment]
准备搞一个element ui 3.0 的库，大家认为如何

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment]
Duplicate of #20375
