### ISSUE TITLE
[bug report] the El image component cannot use lazy load in ie. the include method is used in tool functions. Ie does not support lazy load

### ISSUE THREAD

**Issue by rudyLittleLove** [ElemeFE/element#19233]
### Element UI version
2.8.2

### OS/Browsers version
windows

### Vue version
3.0.0-beta.3

### Reproduction Link
https://codepen.io/rudyjoy/pen/WNQogEG

### Steps to reproduce
1.在IE中打开 https://element.eleme.cn/#/zh-CN/component/image （elementUI 官方demo）
2.懒加载模块图片无法加载，打开控制台报错
（IE对于codepen不支持，上方codepen在IE内查看提示无法打开，但是打开控制台还是能看到实际el-image 代码报错）

### What is Expected?
elementUI 2.8.2 之后的所有版本，el-image 组件的懒加载功能在 IE 中能正常使用

### What is actually happening?
elementUI 2.8.2 之后的所有版本，Iel-image 组件懒加载功能在IE无法使用，控制台报错 对象不支持“includes”属性或方法
（IE对于codepen不支持，上方codepen在IE内查看提示无法打开，但是打开控制台还是能看到实际el-image 代码报错）

**Comment by cs1707** [comment]
Duplicate of #20463
