### ISSUE TITLE
[Bug Report] Autocomplete input throw error on change event

### ISSUE THREAD

**Issue by daofresh** [ElemeFE/element#19243]
### Element UI version
2.13.1

### OS/Browsers version
Chrome Version 81.0.4044.113 (Official Build) (64-bit) / MacOS 10.15.4

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/daofresh/pen/BaoQgbe?editors=1011

### Steps to reproduce
1. Type something in the autocomplete input
2. Click any option or click outside the input
3. Check the console 

### What is Expected?
No error in the console

### What is actually happening?
Error appears in console

**Comment by litt1e-p** [comment]
same problem

**Comment by TrevorYS** [comment]
same problem, you can change version 2.13.1 to 2.31.0

**Comment by litt1e-p** [comment]
> same problem, you can change version 2.13.1 to 2.31.0

2.31.0 exist?

**Comment by TrevorYS** [comment]
> > same problem, you can change version 2.13.1 to 2.31.0
> 
> 2.31.0 exist?

No. It's normal.

**Comment by LiteSun** [comment]
> > same problem, you can change version 2.13.1 to 2.31.0
> 
> 2.31.0 exist?

you can change `^element-ui: 2.13.0` to `element-ui: 2.13.0` in your package.json file，and delete your local node_moudles and then `npm install `

**Comment by ray007** [comment]
I think this is a consequence of the change to emit a `change` event on clear.

**Comment by nyz123** [comment]
I like react，because it throw event handler

**Comment by nyz123** [comment]
> > > same problem, you can change version 2.13.1 to 2.31.0
> > 
> > 
> > 2.31.0 exist?
> 
> No. It's normal.

太可爱了吧，我真的去install了
![image](https://user-images.githubusercontent.com/16752085/80329771-e6072300-8875-11ea-8f7c-dc8b6fa8bc19.png)

**Comment by nyz123** [comment]
4d前dev分支改了这个问题，不知道啥时候能发版，坐等发版升级

**Comment by TrevorYS** [comment]
> > > > same problem, you can change version 2.13.1 to 2.31.0
> > > 
> > > 
> > > 2.31.0 exist?
> > 
> > 
> > No. It's normal.
> 
> 太可爱了吧，我真的去install了
> ![image](https://user-images.githubusercontent.com/16752085/80329771-e6072300-8875-11ea-8f7c-dc8b6fa8bc19.png)

hahaha. I do apologize, I got mistake. The normal version is 2.13.0.
