### ISSUE TITLE
[Bug]table中show-overflow-tooltip隐藏长度较短时，不显示tip

### ISSUE THREAD

**Issue by chaohuaGH** [ElemeFE/element#1924]
### ElementUI version
1.0.8

### What is actually happening?
![qq 20161222140223](https://cloud.githubusercontent.com/assets/20752717/21416674/bc32a610-c84f-11e6-99b1-3565a85875e5.png)
如图，第一行隐藏较多时，会显示tip,
第二行隐藏较少时，鼠标放上，不显示tip

**Comment by QingWei-Li** [comment]
`show-overflow-tooltip` 的意思就是超过长度才显示。否则用自定义模板功能写 el-tooltip 把内容包起来
