### ISSUE TITLE
能不能在Cascader 多加一个配置，让其可以配置是否只能选择最后一个层级？

### ISSUE THREAD

**Issue by xiatianshitiancai** [ElemeFE/element#19253]

**Comment by xiatianshitiancai** [comment]
我尝试修改了源码，可以实现这种功能，在 props 加入一个配置，并在cascader-node.vue 中加入判断，当没有子节点时即判断是最子节点，就显示checkbox  否则则不显示。

**Comment by Ryoui** [comment]
仅显示最后一级，不是就这样吗

**Comment by xiatianshitiancai** [comment]
我是已经在代码里面实现了。 但是没有pull request

**Comment by micxx** [comment]
不是有自定义显示吗

**Comment by zhaomenglu** [comment]
> 仅显示最后一级，不是就这样吗

应该是希望多选的时候，只能最后一级可选。
