### ISSUE TITLE
[Bug Report] "autocomplete" uses "slot", error in selecting option after search

### ISSUE THREAD

**Issue by mj921** [ElemeFE/element#19260]
### Element UI version
2.13.1

### OS/Browsers version
windows/chrome

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/majie/pen/JjYWKdd

### Steps to reproduce
1. "autocomplete" uses "slot";
2. Search for example "三";
3. Choose an option;

### What is Expected?
The console does not report errors

### What is actually happening?
Console error "TypeError: Cannot read property 'value' of undefined"

**Comment by mj921** [comment]
Error is also reported without 'slot'

**Comment by R4c00n** [comment]
Issue can also be reproduces on the official components page https://element.eleme.io/#/en-US/component/input#autocomplete
