### ISSUE TITLE
table怎么实现表格内行的编辑？

### ISSUE THREAD

**Issue by roughsoft** [ElemeFE/element#1927]
项目需要实现，点击行内数据，然后，可以进行数据的编辑。怎么实现。

**Comment by ifibercc** [comment]
我们也有类似的需求，不过感觉单元格编辑保存时进行验证比较麻烦，所以退一步的方案是监控双击时间，然后弹出prompt()，el提供的prompt支持表单验证等功能，不知可否

**Comment by QingWei-Li** [comment]
重复了 https://github.com/ElemeFE/element/issues/1896
