### ISSUE TITLE
希望element改名meituan-ui

### ISSUE THREAD

**Issue by RekcuFrehtom** [ElemeFE/element#19314]

**Comment by wangyang310** [comment]
我觉得饿了么（拼音：eleme）在取名这件事上是真的牛，能这么巧妙的运用“元素”一词（element）作为自家UI框架的名称，不管是从意义（元素，真的是网页元素啊）还是从字面（饿了么 + nt）上，都是绝配！绝没有比它更合适的词了，你竟然还要建议改名？。。。
