### ISSUE TITLE
[Feature Request] el-image大图预览能否增加点击遮罩关闭大图的功能，关闭按钮也可以明显一点

### ISSUE THREAD

**Issue by tililiu** [ElemeFE/element#19330]
### Existing Component
是

### Component Name
image

### Description
el-image大图预览能否增加点击遮罩关闭大图的功能，关闭按钮也可以明显一点

**Comment by alterhu2020** [comment]
Me too, the right top corner 's close icon is gray, which cause user cannot find the icon sometimes.

**Comment by TY-LIU** [comment]
> Me too, the right top corner 's close icon is gray, which cause user cannot find the icon sometimes.

所以我自己写样式覆盖了，原来灰色变成白色，显眼多了

**Comment by cs1707** [comment]
Already fixed in version 2.15.0
