### ISSUE TITLE
我遇到这样的问题,我尝试给el-checkbox-group使用value来进行数据绑定,但是却出现无法选中的BUG.

### ISSUE THREAD

**Issue by whenTheMorningDark** [ElemeFE/element#19337]
![image](https://user-images.githubusercontent.com/30688843/81150334-4a329100-8fb2-11ea-9f0c-372a7da28331.png)
在官网中可以看到能够使用value来进行数据绑定，下面是我的真实操作。
<el-checkbox-group :value="checkList">
              <el-checkbox :label="1">A</el-checkbox>
              <el-checkbox :label="2">B</el-checkbox>
              <el-checkbox :label="3">C</el-checkbox>
</el-checkbox-group>
data(){
 return {
  checkList: [],
 }
}
但是会出现以下的情况
![image](https://user-images.githubusercontent.com/30688843/81150469-849c2e00-8fb2-11ea-805e-d87594f04c07.png)
无法勾选到的情况。

**Comment by coloz** [comment]
遇到了同样的问题
