### ISSUE TITLE
el-select的el-option过多时会有很明显卡顿

### ISSUE THREAD

**Issue by Henry-nie** [ElemeFE/element#1933]

**Comment by Leopoldthecoder** [comment]
多少条？

**Comment by leftstick** [comment]
Hi @Leopoldthecoder 
譬如这样：[http://jsfiddle.net/leftstick/dkzekawy/](http://jsfiddle.net/leftstick/dkzekawy/)

我的例子是1000条整，已经很卡了，没具体测过到底从多少开始变得卡顿。

大致是因为堆`el-option`新增的`visible`属性的`watch`导致的：[option-96~100](https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue#L96-L100), 每次都触发`updatePopper`，效率骤减

**Comment by Leopoldthecoder** [comment]
@leftstick 看起来是的，我看怎么优化一下。

**Comment by leftstick** [comment]
@Leopoldthecoder 主要就是`filterable`时，几乎没法接受。而实际使用过程中，譬如：地区联动，数据量还是非常容易变大的。谢谢

**Comment by dolphin0618** [comment]
联动切换更新2000个option值，会卡死半分钟。初始化的时候不会卡死只有卡顿

**Comment by fengyun2** [comment]
还没优化好么？
