### ISSUE TITLE
[Bug Report] Drawer 抽屉设置 modal="false" esc关闭无效

### ISSUE THREAD

**Issue by jing16hou** [ElemeFE/element#19338]
### Element UI version
2.13.1

### OS/Browsers version
谷歌最新

### Vue version
3.0.0-beta.9

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
modal="false"

### What is Expected?
设置modal="false" 时也能ESC关闭

### What is actually happening?
设置modal="false" 时也能ESC关闭

**Comment by chwech** [comment]
codepen link demo is empty.

**Comment by jing16hou** [comment]
<img width="1326" alt="WechatIMG816" src="https://user-images.githubusercontent.com/22270945/81776346-3d1d2100-9521-11ea-953e-d5466d8b2327.png">

**Comment by jing16hou** [comment]
设置成遮罩不显示，esc关闭不好使
