### ISSUE TITLE
[Bug Report] 使用el-autocomplete 输入时总会报错

### ISSUE THREAD

**Issue by playjoy** [ElemeFE/element#19382]
### Element UI version
2.13.1

### OS/Browsers version
win10/chrome 68.0.3440.106

### Vue version
2.6.8

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F&__cf_chl_jschl_tk__=48689eb7cfb5837784d81500f2dd7db1df6654df-1589202966-0-AVKmDFLlGkyNxDop74TkGjlLvQUv3h0R81ByGw-uq9wKnLh0-JEw-Mf5Zq19Z6mYneghfGA-YZIjJlA63prDJ0gU-O3bZA92Tmld7ezZJn3e2v356W5_M38cywUSd8tC4NsUEmq0oun1oy-KJNpnRsUunc97-vqHd_U1mDxs7iCe1jBlwbIwpgXGp9NiY2SArYrQNyHbWXjun9co005BCVFb1yu0we23fqGjQu3xROGMZomc3qOSsYfI_EHRxGVUYrU3vOsND0Eso_7OMPJmLbDP3UQuTz0zVqovtubtnmkyu3Jce3gF_C9Bv19ydr_mMAjRNtflpzIwgjlBbVA687eFyJOKTY2Sm6ed2gy3dmSLITacTWaLKZyhleVv7KVivRAFrfL-xf_Md8JjTSa7s6zsh-v4ec4egukuGaq-0Lid4366KYC-3y--zM5O4RYfRrQMMgHSdjQPxAe9Fr_UOfapck1-GSMR2Wn9yVWV3d7O

### Steps to reproduce
输入文字时，虽然功能没问题但控制台报错

### What is Expected?
控制台不

### What is actually happening?
控制台报错

**Comment by welkinwong** [comment]
+1 以前没问题的

**Comment by delbug** [comment]
你们是怎么提交问题的啊？ 我不知道怎么提交

**Comment by hemengke1997** [comment]
我也遇到这个问题了 我尝试给autocomplete添加onchange方法 也不行

**Comment by liyufeng2018** [comment]
在node_modules/element-ui/lib/element-ui.common.js 的第2090行
handleChange: function handleChange(event) {
      this.$emit('change', event.target.value);
    },
这个event的值是输入框的值而不是事件，

**Comment by sxzz** [comment]
代码已经提交到 dev 分支 #19200，但还没有发版，可以先使用 2.13.0 版本
