### ISSUE TITLE
[Bug Report] Autocomplete broken "Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by corysimmons** [ElemeFE/element#19389]
### Element UI version
2.13.1

### OS/Browsers version
OS X 10.15.4 / Chrome 81

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/corysimmons/pen/dyYKqed

### Steps to reproduce
1. Add any text to autocomplete field
2. Unfocus autocomplete field
3. Error is throw

### What is Expected?
Error is not thrown.

### What is actually happening?
Error is thrown.

**Comment by xinlangzi** [comment]
@corysimmons 

I faced  the same challenge.

**Comment by corysimmons** [comment]
It's strange because the component seems to work, but Nuxt throws a hard error.

**Comment by liyufeng2018** [comment]
at node_modules\element-ui\lib\element-ui.common.js    2090th line

handleChange: function handleChange(event) {
      this.$emit('change', event.target.value);
    },
 the event is only string rather than Object
it should be 
handleChange: function handleChange(value) {
      this.$emit('change', value);
    },

**Comment by jbfournot** [comment]
👋🏻@corysimmons
It's already fixed (https://github.com/ElemeFE/element/issues/19243) and will be available on the next release.

**Comment by corysimmons** [comment]
Oof, I should've searched first. Thanks for the update!
