### ISSUE TITLE
el-date-picker组件中某一日期多渲染一个字,某一日期上方多渲染一个字

### ISSUE THREAD

**Issue by Ningqiu1234** [ElemeFE/element#19394]
在vue项目中用的element-ui组件中的el-date-picker，莫名多渲染一个“岁”字，1显示为“1个”。
奇怪的是，同样用的谷歌浏览器同一个版本，却在部分人电脑上出现这个Bug,而且这部分人的电脑上这个Bug偶尔出现偶尔没事。

**Comment by otkHsiao** [comment]
关闭浏览器的自动翻译

**Comment by GuanJdoJ** [comment]
+1
