### ISSUE TITLE
数字验证

### ISSUE THREAD

**Issue by hellinnocence** [ElemeFE/element#1939]
<el-form-item prop="num" v-bind:rules="{ requried: true, type: 'float' }">
  <el-input v-model="model.num"></el-input>
</el-from-item>

输入正确的数字都会提示错误

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by hellinnocence** [comment]
<el-form-item prop="number" v-bind:rules="{ required: true, message: '请输入数字', trigger:'change', type: 'float' }">
  <el-input v-model="model.number"></el-input>
</el-form-item>

**Comment by hellinnocence** [comment]
```
<el-form-item prop="number" v-bind:rules="{ required: true, message: '请输入数字', trigger:'change', type: 'float' }">
  <el-input v-model="model.number"></el-input>
</el-form-item>
```

**Comment by wanghaolu** [comment]
这个问题我也遇到过，用的el-input-number代替才解决了，感觉el-input不支持数字输入样。。。。

**Comment by kopheece** [comment]
<el-input v-model.number="model.number"></el-input>

**Comment by hellinnocence** [comment]
输入框的值没变

**Comment by hellinnocence** [comment]
输入框一样可以随便的输入，取值是数字

**Comment by kopheece** [comment]
建议先看看这个 
https://vuefe.cn/v2/guide/forms.html#number

**Comment by hellinnocence** [comment]
还有一个小问题，输入小数点要点两次才可以

**Comment by hellinnocence** [comment]
输入了数字还是提示‘请输入数字’

**Comment by kopheece** [comment]
`<el-form-item prop="number" v-bind:rules="{ type: 'number', required: true, message: '请输入数字', trigger:'change', type: 'float' }"> <el-input v-model.number="model.number"></el-input> </el-form-item>`

**Comment by kopheece** [comment]
试试把type: 'float'换成 type: 'number'

**Comment by hellinnocence** [comment]
换成number也是一样

**Comment by hellinnocence** [comment]
难道你们不用ElementUI的验证??

**Comment by ryannan** [comment]
不应该是blur嘛

**Comment by hellinnocence** [comment]
@Leopoldthecoder 帮帮忙

**Comment by baiyaaaaa** [comment]
@kopheece 的例子是正确的，如果还是有问题请提供demo

**Comment by Leopoldthecoder** [comment]
正确用法：http://jsfiddle.net/j2fm55bz/

**Comment by hellinnocence** [comment]
有数字验证的demo吗？ @Leopoldthecoder

**Comment by hellinnocence** [comment]
![default](https://cloud.githubusercontent.com/assets/7317266/21563078/f93cbc34-ceb8-11e6-9b04-48ec6dd035fc.PNG)
失去焦点的时候没有处理好

**Comment by 10yung** [comment]
如果是數字，非必填要怎麼處理呢？
{ required: false, type: 'number', message: '请输入活动名称', trigger: 'change' }
這樣行不通，一樣會有 ’请输入活动名称‘ 的error 出現
