### ISSUE TITLE
下拉框页面残留

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#194]
可以从官网文档点击`click`触发的下拉框，保持展开，再切换到其它页面，可以发现展开的下拉框仍在在页面上

**Comment by erguotou520** [comment]
实在是不熟悉PR过程，直接贴上我修改的代码吧`packages/dropdown/src/dropdown-menu.vue`最后一行
```
destroyed() {
  this.$el.remove();
  setTimeout(() => {
    this.popper.destroy();
  }, 300);
}
```
不太清楚为什么要加300秒延迟，个人觉得销毁操作可以放在`beforeDestroy`里做。

**Comment by QingWei-Li** [comment]
fixed in #362

**Comment by honthion** [comment]
你是怎么解决的？
