### ISSUE TITLE
[Tree]希望提供节点拖拽功能

### ISSUE THREAD

**Issue by ifibercc** [ElemeFE/element#1940]
希望可以增加拖拽功能，已经看到issue中有人提到操作按钮了，拖拽的场景：比如使用tree来展现组织机构，有时整个部门或者小组会整体迁移到另一个部门，这时需要对整棵子树进行拖拽至其他树节点。

**Comment by furybean** [comment]
先记一个 FR，还没排上计划。

**Comment by Kingwl** [comment]
@furybean 
话说这个我用drag实现了一下 可以吗

**Comment by hejxing** [comment]
迫切需要该功能！

**Comment by masterzhang** [comment]
确实需要

**Comment by 5j2f** [comment]
迫切需要该功能！

**Comment by yjj5855** [comment]
[参考网上改的，需要的可以看看这个demo](https://yjj5855.github.io/vue2-admin-demo/dist/index.html?#/tree)
源码地址 : https://github.com/yjj5855/vue2-admin-demo/blob/master/src/components/tree-node.vue

**Comment by asea1718** [comment]
真心需要这个功能

**Comment by legendjslc** [comment]
希望有这个功能

**Comment by oychao** [comment]
急需这个功能，不过前两天又看到一个issue，官方说暂时没有这个计划，唉，很急～

**Comment by flopgiggle** [comment]
急需此功能，能考虑开发吗

**Comment by Leopoldthecoder** [comment]
Supported in 2.3.0
