### ISSUE TITLE
[bug report] El drawer size attribute source code conflicts with document type

### ISSUE THREAD

**Issue by Ylushen** [ElemeFE/element#19425]
### Element UI version
2.13.1

### OS/Browsers version
win10 chorme 版本 81.0.4044.138（正式版本） （64 位）

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
文档中有提供Number类型，使用会抛警告

### What is Expected?
填Number属性自动转换为px，跟文档一致

### What is actually happening?
填Number会抛出类型错误警告，也不会被转换为px

**Comment by cs1707** [comment]
Duplicate of #20636
