### ISSUE TITLE
能给导航菜单的select函数怎么用

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#1944]
当前只有  index 和 indexPath 两个参数，动态生成导航菜单的应用中，如何有效使用？
比如，菜单数据：
`
[
  {
    index:1,
    extend:"qqqq",
    children:[
      {
         index:1,
         extend:"ppppp",
      },...
    ]
  },...
]
`

如何在select函数中获取相应的extend的值？

**Comment by baiyaaaaa** [comment]
这属于最佳实践的问题，请移步到 https://gitter.im/ElemeFE/element?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge 讨论
