### ISSUE TITLE
[Bug Report]  Vue3.0 - beta.1  import element error/ Vue3.0 Introducing element error reporting

### ISSUE THREAD

**Issue by StephenYang0406** [ElemeFE/element#19449]
### Element UI version
2.13.2

### OS/Browsers version
chrome 81.0.4044.138

### Vue version
3.0.0-beta.14

### Steps to reproduce
新建vue项目
入口文件main.js引入element2.13.2
启动项目就报错
![image](https://user-images.githubusercontent.com/19260429/82292644-d47ceb00-99dd-11ea-84f4-fd1c71cdae7b.png)
![image](https://user-images.githubusercontent.com/19260429/82292666-de065300-99dd-11ea-9ea5-e5fd20d0f0cc.png)

### What is Expected?
正常使用

### What is actually happening?
报错

**Comment by troy351** [comment]
> A Vue.js **2.0** UI Toolkit for Web

**Comment by StephenYang0406** [comment]
找到个解决办法,大家可以参考下,npm安装的vue依然是3.0,然后cdn引入2.6的vue和element,注意先后顺序,然后现在项目写法依旧是vue3.0,但是可以用element

**Comment by lifedre** [comment]
可以搞个demo不

**Comment by StephenYang0406** [comment]
package.json

index.html



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lifedre"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 中午11:26
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"Stephen"<490276639@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] [Bug Report]  Vue3.0 - beta.1  import element error/ Vue3.0 Introducing element error reporting (#19449)





 
可以搞个demo不

**Comment by lizjiang** [comment]
> 找到个解决办法,大家可以参考下,npm安装的vue依然是3.0,然后cdn引入2.6的vue和element,注意先后顺序,然后现在项目写法依旧是vue3.0,但是可以用element

这样做确实不报错了，但是样式没有加载出来，大神遇到这问题了吗

**Comment by StephenYang0406** [comment]
回退到2.6+composition/api吧,这样用还是需要改element源码,除非轮子都是自己造的,否则还不建议使用3.0,所有第三方库都还没支持3.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 下午5:43
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"Stephen"<490276639@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] [Bug Report]  Vue3.0 - beta.1  import element error/ Vue3.0 Introducing element error reporting (#19449)





  
找到个解决办法,大家可以参考下,npm安装的vue依然是3.0,然后cdn引入2.6的vue和element,注意先后顺序,然后现在项目写法依旧是vue3.0,但是可以用element
  
这样做确实不报错了，但是样式没有加载出来，大神遇到这问题了吗

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment]
Duplicate of #20375
