### ISSUE TITLE
[Bug]1.0.8,Tree node-click无效，控制台提示：event is not defined

### ISSUE THREAD

**Issue by chaohuaGH** [ElemeFE/element#1945]
### What is actually happening?
如题，文档页面（http://element.eleme.io/#/zh-CN/component/tree ）也是如此，请确认

**Comment by Leopoldthecoder** [comment]
未重现：http://jsfiddle.net/n16dLvc0/

**Comment by chaohuaGH** [comment]
@Leopoldthecoder http://element.eleme.io/#/zh-CN/component/tree 基础用法的那个例子，点击节点，控制台会报错：ReferenceError: event is not defined。

**Comment by chaohuaGH** [comment]
@Leopoldthecoder  你的示例也有报错。这个bug不是点不开子节点。而是点击子节点的响应出错。

**Comment by Leopoldthecoder** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10095631/21446393/7ea7dcdc-c900-11e6-93fc-91547fc294ef.gif)
我这里并不会报错

**Comment by chaohuaGH** [comment]
@Leopoldthecoder 
非常抱歉，我对bug定位不准，chrome确实没有问题。
但是firefox有问题。
![bug](https://cloud.githubusercontent.com/assets/20752717/21448079/4099507e-c919-11e6-931b-438062c8469e.png)

我是在项目中发现的，现在回退到1.07在firefox中正常
