### ISSUE TITLE
[Table] 希望有选项可以去掉客户端的sort和filter动作，只触发事件。

### ISSUE THREAD

**Issue by iyjian** [ElemeFE/element#1946]
现在table组件中 sort 和 filter 都是客户端完成的。

在触发sort-change 和 filter-change的同时也在客户端做了sort 和 filter。

希望能有选项去掉客户端的这些动作。

我想包装成一个ajax table的组件。

**Comment by furybean** [comment]
@iyjian 现在都是可以实现的，filter-method 不填入即可触发 filter-change，但是不过滤；sortable 设置为 custom 则不会触发排序逻辑。

**Comment by iyjian** [comment]
@furybean 不好意思哈，没仔细看，哈哈。知道了。 你有做好的包装好的template吗，我还自己在弄呢，想弄个datatable那种样子的。

**Comment by furybean** [comment]
@iyjian 没有。每个 issue 对应一个问题，先关了。
