### ISSUE TITLE
Table bug: 在示例文档中发现的问题

### ISSUE THREAD

**Issue by hejxing** [ElemeFE/element#195]
在示例文档 http://element.eleme.io/#/component/table 固定列表头中发现以下问题：
1.在chrome(53)中发现固定的左列不能随scroll-y滑动;
2.表头不能随scroll-x移动;

兼容性问题：
    firefox49：
         1.上例中scroll-y未出现，与chrome表现不一致;
         2.《单选》,《多选》这两例表格未铺满容器，表头与下方列未对齐
   Edge 中表现与firefox一致。

**Comment by QingWei-Li** [comment]
以及修过了 https://github.com/ElemeFE/element/pull/127

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/121

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/121
