### ISSUE TITLE
radio的text-color设置激活文本颜色无效

### ISSUE THREAD

**Issue by wdsheng0i** [ElemeFE/element#1950]

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/commit/b421556144fd9e17e5b2f2d590a2de6f11c492e7

### Radio-group Attributes
| 参数      | 说明    | 类型      | 可选值       | 默认值   |
|---------- |-------- |---------- |-------------  |-------- |
| size     | Radio 按钮组尺寸   | string  | large, small  |    —     |
| fill  | 按钮激活时的填充色和边框色    | string   | — | #20a0ff   |
| text-color  | 按钮激活时的文本颜色    | string   | — | #ffffff   |

文档错了，这个是 Radio-group 的属性

**Comment by basejs** [comment]
Radio-group设置size也无效啊？默认的radio太大了
