### ISSUE TITLE
el-table组件里使用组件el-select，无法点击获取selected值

### ISSUE THREAD

**Issue by liujing0628** [ElemeFE/element#1951]
### What is actually happening?
简单demo：http://jsfiddle.net/swgezvtj/1/

**Comment by kopheece** [comment]
http://jsfiddle.net/kopheece/ennwwe3d/

**Comment by QingWei-Li** [comment]
可以参考 @kopheece 的做法，以及 https://github.com/ElemeFE/element/issues/1896#issuecomment-268425536

https://github.com/ElemeFE/element/issues/1896
