### ISSUE TITLE
[Bug Report] el-drawer append-to-body attribute The default value is actually true, false in the document

### ISSUE THREAD

**Issue by xu-xiaoqi** [ElemeFE/element#19549]
### Element UI version
2.13.2

### OS/Browsers version
mac 

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
el-drawer append-to-body attribute The default value is actually true, false in the document

### What is Expected?
el-drawer append-to-body attribute  The default value change to false or change the document 

### What is actually happening?
el-drawer append-to-body attribute The default value is actually true, false in the document

**Comment by cs1707** [comment]
The default value has been set to false
