### ISSUE TITLE
toggleRowSelection的用法求助

### ISSUE THREAD

**Issue by wlx200510** [ElemeFE/element#1954]
### ElementUI version
1.0.3

### OS/Browers version
Chrome 53

### Vue version
2.1.0

### Reproduction Link

Table 的多选Checkbox，在加载数据时实现选择制定行 参考了#1003后 使用$nextTick仍无法同步
### What is Expected?
this.$refs.episodeTable.toggleRowSelection(row, true);
如何能实时展现在DOM上

**Comment by wlx200510** [comment]
想要实现的目标是：现在有一个数组，如果这个数组里面有当前列表中的row对应的对象  该行就打钩，反之不打勾，用watch实现

**Comment by wlx200510** [comment]
已经自己解决了

**Comment by InTwoDisease** [comment]
@wlx200510 
你怎么解决的

**Comment by guoyiyuhen** [comment]
同问怎么解决的？

**Comment by HP-jackZhang** [comment]
数据缓存下来应对分页。获取数据后，
  let rows = this.selectDataCache[this.listQuery.index];
            if (rows && rows.length > 0) {
              this.$nextTick(function () {
                /*
                * 找出选中的对应的row
                * */
                let arr = [];
                rows.forEach(row => {
                  const index = this.data.content.findIndex(item => item.id === row.id)
                  arr.push(this.data.content[index])
                });

                arr.forEach(row => {
                  this.$refs.multipleTable && this.$refs.multipleTable.toggleRowSelection(row, true);
                });
              })
            }
