### ISSUE TITLE
请问如何方便的实现一个tree grid

### ISSUE THREAD

**Issue by wenner** [ElemeFE/element#1955]
当前tree只有一个节点label来显示内容 , 每次需要显示其他信息都要使用renderContent来扩展,有没有更好的方式,比如把tree和table结合起来,使用类似    <el-table-column> , 加一个新类型 expander , 作为树的expand节点(箭头)

**Comment by shipengyan** [comment]
+1

**Comment by Leopoldthecoder** [comment]
@jixzfw 实现了树状表格，可以去参考一下：https://git.oschina.net/bfgdqch/EleAdmin

**Comment by jiahui90** [comment]
能不能增加一个treetable的组件

**Comment by fuhongwei041** [comment]
+1

**Comment by fuhongwei041** [comment]
https://www.npmjs.com/package/element-tree-grid
