### ISSUE TITLE
The El Popover in the [bug report] table uses multiple box groups. Multiple boxes cannot be selected

### ISSUE THREAD

**Issue by mengtiantang** [ElemeFE/element#19566]
### Element UI version
2.13.2

### OS/Browsers version
chrome

### Vue version
2.6.1

### Reproduction Link
https://codepen.io/mengtiantang/pen/KKVKLRj

### Steps to reproduce
点击表格操作出现Popover 弹出框，里面的多选框组无法选中

### What is Expected?
根据多选框选中改变表格列的显示隐藏

### What is actually happening?
多选框选中状态无法更改

**Comment by GATING** [comment]
在表头插槽增加属性 `slot-scope` 即可，如下`<template slot="header" slot-scope="scope">`
