### ISSUE TITLE
[feature request] expect El select multi selection mode to support customized display of selected items

### ISSUE THREAD

**Issue by wangwenjie1314** [ElemeFE/element#19578]
### Existing Component
是

### Component Name
el-select

### Description
期望el-select 多选模式支持已选择的项 自定义展示；
目前项目需求需要支持彩色选项和已选择在select框中展示彩色；
![image](https://user-images.githubusercontent.com/4018406/83986911-ff20ea80-a970-11ea-97f5-c850334f0998.png)
![image](https://user-images.githubusercontent.com/4018406/83987507-09dc7f00-a973-11ea-92fc-08a4f6896994.png)

**Comment by a1s** [comment]
Thank you for the patch, @Kellercai!

Unfortunately, it allows to chose only from the four basic colors.

In my project, I need color tags for a wider range of categories, maybe a couple dozens of them.

**Comment by wangwenjie1314** [comment]
由于官方长时间未更新，项目要的急，只好搭建私有化npm，在element2.13.2基础上修改：

- Select
  - 更新

  | 参数      | 说明          | 类型      | 可选值                           | 默认值  |
  |---------- |-------------- |---------- |--------------------------------  |-------- |
  | customClass | 选项的自定义样式，多用于Select选项变色，[多选模式下]选中展示也变色 | string | — | — |
  | customType | [多选模式下]Select选项选中后，基于el-tag提供的几种type改变选中展示 | string | — | 'info' |

```
    <el-option
      v-for="item in options"
      :key="item.value"
      :custom-class="item.customClass"
      :custom-type="item.customType"
      :label="item.label"
      :value="item.value">
    </el-option>

export default {
    data() {
      return {
        options: [{
          value: '选项1',
          label: '黄金糕',
          customClass: 'bg-fff color-blue',
          customType: 'success'
        }, {
          value: '选项2',
          label: '双皮奶',
          customClass: 'bg-blue',
          customType: 'danger'
        }, {
          value: '选项3',
          label: '蚵仔煎',
          customClass: 'bg-gray',
          customType: 'warning'
        }],
      }
    }
  }
```


修改代码截图如下：

![image](https://user-images.githubusercontent.com/4018406/89964930-05d42280-dc7e-11ea-8305-63214241afa1.png)
![image](https://user-images.githubusercontent.com/4018406/89964957-15ec0200-dc7e-11ea-8512-886cc4b1e64a.png)
![image](https://user-images.githubusercontent.com/4018406/89964971-21d7c400-dc7e-11ea-9e48-b8143cf558e7.png)

**Comment by wangwenjie1314** [comment]
![image](https://user-images.githubusercontent.com/4018406/89965058-62cfd880-dc7e-11ea-8710-383e77ffc8ef.png)
![image](https://user-images.githubusercontent.com/4018406/89965058-62cfd880-dc7e-11ea-8710-383e77ffc8ef.png)
