### ISSUE TITLE
[bug report] the El dialog contains input, which will flash when inputting

### ISSUE THREAD

**Issue by trumansdo** [ElemeFE/element#19582]
### Element UI version
2.13.0

### OS/Browsers version
win10/chrome 83

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/trumansdo/pen/MWKwjKv

### Steps to reproduce
在对话框中实现对el-tree的搜索功能，input输入过滤词会让dialog闪屏，同时tree过滤失效。
初步调试原因，在v-model或者watch这种使值update时会触发el-dialog 的重加载。因为去除el-input的v-model，直接输入值，虽然看不到输入关键字，但是可以实现el-tree过滤且不会发生闪屏

### What is Expected?
实现el-tree 搜索，el-dialog 不闪屏

### What is actually happening?
无法实现el-tree 搜索，el-dialog 闪屏

**Comment by Littledevil7** [comment]
you should remove the dialog key,wich will lead dialog update when tree changed every time.
![image](https://user-images.githubusercontent.com/44463110/84218310-bbf58180-ab00-11ea-80c0-bf3bc36b8f89.png)

**Comment by trumansdo** [comment]
@Littledevil7  thk u!  i did not understand attribute "key". it caused me trouble.
