### ISSUE TITLE
[Feature Request] vue 3.0 support

### ISSUE THREAD

**Issue by wxs77577** [ElemeFE/element#19587]
### Existing Component
是

### Component Name
all

### Description
Will element ui support vue.js 3.0?
Element UI 什么时候支持 vue.js 3.0？

**Comment by dmix** [comment]
I understand this is still coming, but just for the record `element-ui` does not yet load with `vue-3.0.0-rc.4` the breaking error are references to `_vue2.default.prototype` as noted here: https://github.com/ElemeFE/element/issues/19449

Not sure if there is any planned work on this. Allegedly vue 3 is maintaining backwards compatibility. All my other vue plugins seem to support it without any problems at the moment after I ported my app to the composition-api. Just waiting out `element-ui`.

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment]
Duplicate of #20375
