### ISSUE TITLE
[feature request] you want to extract the padding left value of navmenu - > menu item into a configurable property

### ISSUE THREAD

**Issue by iwusong** [ElemeFE/element#19590]
### Existing Component
是

### Component Name
NavMenu

### Description
希望可以将NavMenu -> menu-item 的 padding-left 值 抽离成可配置的属性 ，固定的值在缩小导航宽度后太宽了

https://github.com/ElemeFE/element/blob/bf534d977eeecfe0de82397f2598f96f45b7885a/packages/menu/src/menu-item-group.vue#L29

https://github.com/ElemeFE/element/blob/bf534d977eeecfe0de82397f2598f96f45b7885a/packages/menu/src/menu-mixin.js#L25

**Comment by AutismPeople** [comment]
有什么好的解决方案吗？

**Comment by itreetree** [comment]
> 有什么好的解决方案吗？

改成百分比单位
