### ISSUE TITLE
When [bug report] El input type is number, input a number and delete another part, continue to input decimal point, unable to input

### ISSUE THREAD

**Issue by zeyongTsai** [ElemeFE/element#19602]
### Element UI version
2.13.2

### OS/Browsers version
win10/MacOS     Chrome83

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/tsai_snick/pen/WNrQYYq?editable=true%3Dhttps%3A%2F%2Felement.eleme.cn%2F2.13%2F

### Steps to reproduce
1 input    99999999；
2 input    99999999.9；
3 delete  9999999；
4 input    (.) after number；

(.) can not be inputed

### What is Expected?
可以正常输入小数点

### What is actually happening?
这种情况发生在 搜狗输入法中文模式下，英文模式或者 ABC 输入法没有问题，因此猜测是输入法兼容问题

**Comment by Kellercai** [comment]
因为你设置了type=number，而且如果是中文输入的话，应该是句号，而不是小数点吧。

**Comment by zeyongTsai** [comment]
> 因为你设置了type=number，而且如果是中文输入的话，应该是句号，而不是小数点吧。

经过测试（MacOS+搜狗输入法中文模式），是浏览器自身问题：

safari、firefox
在上一个输入了数字接下来输入点（或者说句号），是能够变成为一个小数点的，如果进行了数字的delete操作，然后输入点（或者说句号），则会输入一个句号。

chrome
与上面两个浏览器相同操作下，唯一的不同是： delete数字后再输入点（或者说句号）不让输入。
