### ISSUE TITLE
el-radio-button 指定激活颜色无效

### ISSUE THREAD

**Issue by Gavin-Gong** [ElemeFE/element#1962]
```
  <el-radio-group v-model="radio3">
    <el-radio-button label="上海" fill="#f44336" text-color="#fff"></el-radio-button>
    <el-radio-button label="北京"></el-radio-button>
    <el-radio-button label="广州" :disabled="true"></el-radio-button>
    <el-radio-button label="深圳"></el-radio-button>
  </el-radio-group>
```
[jsfiddle Link](http://jsfiddle.net/Gavin_Gong/p4o1og56/3/)

**Comment by Gavin-Gong** [comment]
另外 -> 默认激活颜色好像是写死在代码里面, 因此不支持自定义主题?

**Comment by Plortinus** [comment]
文档写错了, `fill`和`text-color`是`el-radio-group`的属性，`el-radio-button`里没有这俩属性：
[radio-group.vue](https://github.com/ElemeFE/element/blob/dev/packages/radio/src/radio-group.vue)

[代码演示](http://jsfiddle.net/p4o1og56/6/)

**Comment by Leopoldthecoder** [comment]
Fixed in #1874
