### ISSUE TITLE
树表格展开问题

### ISSUE THREAD

**Issue by f4112cd** [ElemeFE/element#19644]
目前有一个需求就是加载完树表格之后默认展开树表格中的某一行，官方文档中提供了一个expand-row-keys属性来设置需要展开的行，但是这个属性用在树表格中没有作用，只有使用在表格展开行中才有作用。
所以能否提供一个用于默认展开树表格中某一行的属性，或者是原本就提供了只不过我没有找到

**Comment by caiqichang** [comment]
+1
