### ISSUE TITLE
[InputNumber] 在有fixed的table里面，v-model绑定row里面的内容时，change事件触发多次

### ISSUE THREAD

**Issue by kfqkfy** [ElemeFE/element#1964]
```
<template>
  <el-table :data="tableData" border style="width: 100%">
    <el-table-column fixed prop="date" key="data" label="日期" width="150">
    </el-table-column>
    <el-table-column
      inline-template
      prop="aaa"
      key="aaa"
      label="aaa"
      width="180">
      <div>
        <el-input-number v-model="row.zip" size="small" @change="changeNum(row.zip)"></el-input-number>
      </div>
    </el-table-column>
    <el-table-column fixed="right" prop="city" key="city" label="日期" width="150">
    </el-table-column>
  </el-table>
</template>


changeNum(val) {
      	console.log(val)
      }
```

点击InputNumber的加减号，控制台输出3次值，第一次change前的值，后两次change之后的值，在change函数里面加延迟事件就3次全是change之后的值
去掉一个fixed的列就少一个，全部都不是fixed了就只有一次进去了
v-model如果是不是从row里面取的话也只有一次
![image](https://cloud.githubusercontent.com/assets/2724562/21453498/a7bae61a-c94a-11e6-86cb-841021a82fa3.png)
![image](https://cloud.githubusercontent.com/assets/2724562/21453506/beaae834-c94a-11e6-924d-62c3fbd038e2.png)

**Comment by kfqkfy** [comment]
好像是fixed是通过生成多个tablebody实现的，然后每个body里面都有一整套InputNumber，改变一个InputNumber的值改变了v-model的值后把每个body里面对应的那个InputNumber的onchange方法都触发了？

**Comment by baiyaaaaa** [comment]
你都截图了为何不把demo提供以下呢

**Comment by kfqkfy** [comment]
[http://jsfiddle.net/kfqkfy/26fre6cg/](http://jsfiddle.net/kfqkfy/26fre6cg/)

之前一直注册不了。。刚注册了，应该是这么个demo地址吧。。

**Comment by furybean** [comment]
是 InputNumber 的 Bug，change 事件应该是只有用户操作才会触发。

**Comment by furybean** [comment]
@baiyaaaaa @QingWei-Li @Leopoldthecoder InputNumber 作者来领 Bug。

**Comment by kfqkfy** [comment]
@furybean 对，是InputNumber上有问题，照前面修改的，我提的这个问题应该是解决了，但是刚发现了另一个问题，就是如果table里面有InputNumber在那边，然后我刷新下table的数据，InputNumber的onchange也被触发了
