### ISSUE TITLE
[Feature Request] Dialog组件close事件

### ISSUE THREAD

**Issue by lordGuan** [ElemeFE/element#19653]
### Existing Component
是

### Component Name
Dialog

### Description
visible变成false的时候，是否触发close事件能不能提供配置。也许我只是想关闭，但是内部数据要保留，点关闭或者取消才是真正需要关闭，都靠触发close事件是不是太不灵活了

**Comment by kayoch1n** [comment]
我也觉得不应该触发close事件，这个特性可以有么？

**Comment by lordGuan** [comment]
有一说一真的对elementui太失望了，最近一年已经几乎剔除了所有的elementui依赖，希望大家也勤劳一点吧
