### ISSUE TITLE
tab  数量多的时候能不能添加自动滚动功能

### ISSUE THREAD

**Issue by chouxiaozi** [ElemeFE/element#1966]
![image](https://cloud.githubusercontent.com/assets/2462932/21457376/da00d020-c969-11e6-99d6-62c018752969.png)
就像下图一样添加左右滚动的按钮

![image](https://cloud.githubusercontent.com/assets/2462932/21457443/4b959d56-c96a-11e6-86ed-145f79b859c0.png)

**Comment by baiyaaaaa** [comment]
你可以通过样式控制，1.1版本会将 tab组件喝模型修正为 `block`
