### ISSUE TITLE
建议：input增加键盘event

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#1968]
在登录或者表单提交的场景中是否可以为input组建添加键盘event来实现回车提交之类的动作？

**Comment by jikkai** [comment]
参考 FAQ 第一条，原生事件用.native修饰符
```
<el-input @keyup.enter.native="..." />
```

这个问题都快周经了https://github.com/ElemeFE/element/issues?utf8=%E2%9C%93&q=keyup

**Comment by Leopoldthecoder** [comment]
@jikkai 之前是日经，literally
