### ISSUE TITLE
图片上传建议增加裁切功能

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#1969]

**Comment by phycholee** [comment]
借楼。
我建议文件上传可以限制数量，原组件没有找到可以限制。
有一个before-upload接近了，如果function中修改为**function(file,fileList)**就可以根据fileList自行限制数量。

**Comment by Jialufeng** [comment]
借楼，多个上传太麻烦了。
建议增加可以 循环upload

**Comment by baiyaaaaa** [comment]
预计会在1.2.0提供，因为当前版本 upload 设计确实没有考虑到很多方面，Upload 组件将会迎来一个比较大的API更新。

**Comment by gordon8** [comment]
@baiyaaaaa 你好！请问upload组件什么时候会增加图片裁切功能？
