### ISSUE TITLE
希望把基础组件独立出来维护

### ISSUE THREAD

**Issue by djyde** [ElemeFE/element#197]
希望可以像 ant.design 一样，基于一些基础组件（`rc-components`）来做 UI，而不是把 UI 和组件放到一起维护。

比如可以独立出来成为 `vue-components`:

- vue-table
- vue-button
- vue-input
- ...etc

这样来把逻辑和 UI language (stylesheet) 分开来维护会更棒。

**Comment by QingWei-Li** [comment]
现在组件是独立维护的，你可以看 packages 目录，一个组件一个包。只是目前还没有单独发布。
