### ISSUE TITLE
datepicker model上绑定数据时清除日期，model上无法清除

### ISSUE THREAD

**Issue by cench** [ElemeFE/element#1970]
date 的model 默认初始化是有一条后端返回数据的，但是如果点击了右边叉叉删除日期后，model上的数据还是仍然存在，不知道有什么办法可以解决，尝试过改源码去除日期那个叉叉，但是依然没法去除
注意：一旦重新修改一次日期后，点击叉叉删除日期，model上数据是可以删除的

**Comment by QingWei-Li** [comment]
http://jsfiddle.net/oe3ebezf/ 

我这没复现，请提供 demo
