### ISSUE TITLE
[Bug Report] el-image request twice

### ISSUE THREAD

**Issue by zhaoyongsheng1990** [ElemeFE/element#19712]
### Element UI version
2.13.2

### OS/Browsers version
win10 / Chrome

### Vue version
2.5.22

### Reproduction Link
jsfiddle

### Steps to reproduce
step1：open url：
https://element.eleme.cn/#/zh-CN/component/calendar
step2：open dev tools
step3：click  “Image 图片”  on page
you will see send twice request per image

### What is Expected?
send one request per image

### What is actually happening?
send twice request per image

**Comment by zhaoyongsheng1990** [comment]
does anyone encounter this problem？

**Comment by Veitor** [comment]
same problem. 
it work well when using <img> tag.
![image](https://user-images.githubusercontent.com/7483890/89617638-24709d00-d8bd-11ea-9d41-81dd2a10f000.png)
![image](https://user-images.githubusercontent.com/7483890/89617668-33efe600-d8bd-11ea-9dbf-7bc3c88ac306.png)

**Comment by cs1707** [comment]
fixed
