### ISSUE TITLE
[Bug Report] el-time-picker The drop-down selection is inconsistent with the date returned by the text input！！！

### ISSUE THREAD

**Issue by hu949277923** [ElemeFE/element#19713]
### Element UI version
2.13.2

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/billhu/pen/KKVmMPj

### Steps to reproduce
1、下拉选择时间为：10:00:00
2、打开控制台查看日期时间（Tue Jun 23 2020 10:00:00 GMT 0800 (中国标准时间)）
3、手动输入时间为：10:00:00（Wed Jan 01 2020 10:00:00 GMT 0800 (中国标准时间)）
4、打开控制台查看日期时间

### What is Expected?
下拉选择：Tue Jun 23 2020 10:00:00 GMT 0800 (中国标准时间)
手动输入：Tue Jun 23 2020 10:00:00 GMT 0800 (中国标准时间)
不管操作行为如何变化结果应该保持一致！！

### What is actually happening?
年月日不一样，下拉选择为当前时间的年月日，手动输入当前时间的年和1月1日，具体如下：
下拉选择：Tue Jun 23 2020 10:00:00 GMT 0800 (中国标准时间)
手动输入：Wed Jan 01 2020 10:00:00 GMT 0800 (中国标准时间)

**Comment by wangmeijian** [comment]
This is a real problem
