### ISSUE TITLE
ie element-ui/src/utils/util.js SCRIPT1010: 缺少标识符  

### ISSUE THREAD

**Issue by MrYangZC** [ElemeFE/element#19710]
element-ui  2.13.0

ie
![image](https://user-images.githubusercontent.com/29966789/85295923-347e1a00-b4d3-11ea-9a23-3068f811e5bf.png)
element-ui/src/utils/util.js 
缺少一个；
`export function rafThrottle(fn) {
  let locked = false;
  return function(...args) {
    if (locked) return;
    locked = true;
    window.requestAnimationFrame(_ => {
      fn.apply(this, args);
      locked = false;
    });
  };
}
`

**Comment by Dalegac** [comment]
老哥您是如何解决这个问题的呢？
