### ISSUE TITLE
MessageBox 组件在 Chrome 下的出场动画掉帧非常严重

### ISSUE THREAD

**Issue by u3u** [ElemeFE/element#1971]
### ElementUI version
"element-ui": "^1.0.7",

### OS/Browers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

### Vue version
"vue": "^2.1.0",

### Reproduction Link
http://element.eleme.io/#/zh-CN/component/message-box#que-ren-xiao-xi

### Steps to reproduce
1.打开上面的链接
2.反复操作几次打开／关闭
3.肉眼能明显感觉到掉帧 严重的时候和GIF差不多了
绝对不是电脑性能问题 测试在 Safari 下很顺滑 目前也不太清楚是什么原因

### What is Expected?
期望在 Chrome 中的动画效果能和 Safari 一致

**Comment by yeyifen** [comment]
我的环境：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36。。。
试了十几次了，没感觉到会掉帧啊

**Comment by u3u** [comment]
@yeyifen 你的屏幕大小和分辨率是多少 我的屏幕15寸 分辨率 1680 * 1050 掉帧
测试把 Chrome 窗口拉小一点就不会掉帧了

**Comment by HerringtonDarkholme** [comment]
Please make sure you test with all extensions disabled. 

Also, Chrome's developer tools provide informative profiling. That will be useful for issue reporting.
