### ISSUE TITLE
[Table] table组件中如果选中了数据，然后再刷新表格数据，选中的css不会被重置。

### ISSUE THREAD

**Issue by iyjian** [ElemeFE/element#1975]
我用table组件做后台应用的时候发现：
如果选择一条数据，然后我刷新了table数据，这个table selection已经被清空了，但是css效果还是在的，没有同步，

在下面的例子里
+ 点击表格中的第一条数据
+ 点击**重新刷新数据**按钮
会发现被选择的数据已经没有了，但是选中效果还在

[点这里可以测试......](http://jsfiddle.net/iyjian/s2aob7nf/2/ )

**Comment by Leopoldthecoder** [comment]
Fixed in #1977
