### ISSUE TITLE
请问为什么mintUI不更新了啊？？

### ISSUE THREAD

**Issue by MUxiaoshua** [ElemeFE/element#19786]

**Comment by caoyu48** [comment]
mintUI早不更新了 elementUI都没官方的人维护了。。。

**Comment by ouyangshan09** [comment]
凉凉，项目组成员是0

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by zhouzhongyuan** [comment]
Still under maintenance.
