### ISSUE TITLE
图片上传组件，headers参数无法添加请求头

### ISSUE THREAD

**Issue by lewis-geek** [ElemeFE/element#1979]
```html       
   <el-upload
       :headers='uploadHeader'>
       ...
       ...
   </el-upload>
```

```javascript
    uploadHeader: {
       'Content-Type': 'multipart/form-data; boundary=fuckReaquestHeader'
    }
```

发送请求后在Chrome中查看请求头，没有Content-Type

**Comment by lewis-geek** [comment]
服务器处理options请求的问题，和组件无关

**Comment by lewis-geek** [comment]
服务器处理options请求的问题，和组件无关

**Comment by 598220654** [comment]
@lewis-geek 
![image](https://cloud.githubusercontent.com/assets/15324717/21756355/4788145c-d65b-11e6-8c2a-b69018a2d90e.png)
或者怎么获取上传成功对应dom

**Comment by phpstudyer** [comment]
对的,服务端的Access-Control-Allow-Headers必须也加上你的header key
