### ISSUE TITLE
[Bug Report] DatePicker have a issue when i use daterange in mobile screen it should be one page

### ISSUE THREAD

**Issue by AhmedShibob** [ElemeFE/element#19799]
### Element UI version
2.13.2

### OS/Browsers version
Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36"

### Vue version
2.6.9

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.io%2F

### Steps to reproduce
just open it in the mob screen size it will be very bad

### What is Expected?
it shoud be with 2 modes to open in one page in moblie

### What is actually happening?
it's open in 2 pages in mobile and desktop

**Comment by MatanYadaev** [comment]
@AhmedShibob I also have this issue on mobile. Just notice your Codepen link doesn't work

**Comment by AhmedShibob** [comment]
@MatanYadaev 

It's doesn't work in the official website too  https://lusaxweb.github.io/vuesax/components/upload.html
