### ISSUE TITLE
[Bug Report] el-checkbox not working in el-table-column header slot.

### ISSUE THREAD

**Issue by towry** [ElemeFE/element#19792]
### Element UI version
2.13.2

### OS/Browsers version
mac/chrome

### Vue version
3.0.0-beta.18

### Reproduction Link
https://jsfiddle.net/towry/k5ythLqc/1/

### Steps to reproduce
查看: https://jsfiddle.net/towry/k5ythLqc/1/

### What is Expected?
可以正常工作

### What is actually happening?
不工作

**Comment by lkangd** [comment]
vue版本超过 2.6 使用新语法：
```html
      <template v-slot:header>
	<el-checkbox v-model="all" @input="handleInput">全选</el-checkbox>
      </template>
```
或者加个 scope：
```
      <template slot="header" slot-scope="scope">
        <el-checkbox v-model="all">全选</el-checkbox>
      </template>
```

**Comment by towry** [comment]
> vue版本超过 2.6 使用新语法：
> 
> ```
>       <template v-slot:header>
> 	<el-checkbox v-model="all">全选</el-checkbox>
>       </template>
> ```
> 
> 或者加个 scope：
> 
> ```
>       <template slot="header" slot-scope="scope">
>         <el-checkbox v-model="all">全选</el-checkbox>
>       </template>
> ```

Thanks.

**Comment by GFELF** [comment]
> vue版本超过 2.6 使用新语法：
> 
> ```
>       <template v-slot:header>
> 	<el-checkbox v-model="all">全选</el-checkbox>
>       </template>
> ```
> 
> 或者加个 scope：
> 
> ```
>       <template slot="header" slot-scope="scope">
>         <el-checkbox v-model="all">全选</el-checkbox>
>       </template>
> ```

为什么并没有使用到scope中的属性也需要这样做才能实现v-model？
