### ISSUE TITLE
[Bug Report] When the el-upload upload file reaches the limit, do not display the upload box again

### ISSUE THREAD

**Issue by Cat7373** [ElemeFE/element#19797]
### Element UI version
2.13.2

### OS/Browsers version
MacOS 10.15 / Chrome 83

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/p9yb57m4/

### Steps to reproduce
1. Set list-type to picture-card
2. Set limit to 1
3. Upload a file

### What is Expected?
Don't show upload button again

### What is actually happening?
Upload button displayed

**Comment by wangmeijian** [comment]
Self - control display can be hidden
