### ISSUE TITLE
[bug report] the value obtained after setting value format ='yyyy-mm-dd 'with' daterange 'is seriously wrong

### ISSUE THREAD

**Issue by Yee1023** [ElemeFE/element#19795]
### Element UI version
2.13.2

### OS/Browsers version
Mac OS / chorme

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
1、为选择日期范围组件设置value-format='yyyy-MM-DD'。
2、选择日期范围为：2020年7月6日到2020年8月6日（此日期是随意选择到，随便选则任何日期均可复现）。

### What is Expected?
日期组件展示：2020-07-06至2020-08-06

### What is actually happening?
日期组件展示：2020-07-01至2020-08-01（无论选择什么日期，用户只会展示这一对日期）

**Comment by bautd-2046** [comment]
Hi there, i have another issue like this: 
`      <el-form-item label="Pick a range:">
          <el-date-picker
            v-model="formData.loadingDate"
            :clearable="false"
            type="daterange"
            range-separator="〜"
            format="yyyy/MM/dd"
            value-format=" yyyy/MM/dd"
          />
        </el-form-item>`
it didnt work at all, i got an error:
![image](https://user-images.githubusercontent.com/55070445/88648433-2f734280-d0f1-11ea-8fb0-9335781bd53c.png)
can you use `daterange` with `value-format`? Can you show me the way?
