### ISSUE TITLE
多页应用里,如何给NavMenu 导航菜单里的Menu-item添加跳转链接?

### ISSUE THREAD

**Issue by Plortinus** [ElemeFE/element#198]
### ElementUI version
1.0.0-rc.4

难道需要自己用`<a>`标签实现?

**Comment by QingWei-Li** [comment]
文档里有写，有一个 router 属性

**Comment by Plortinus** [comment]
如何用这个`router`是不是得学一下`vue-router`?

**Comment by QingWei-Li** [comment]
否则就自己写个 a 标签

**Comment by mingbai2006** [comment]
@QingWei-Li  这里确实用起来麻烦，建议可以单独关闭某个menu-item的路由跳转。
比如我菜单里有一部分菜单需要跳转的，又有一部分不需要跳转的（比如外链），如果设置了:router="true"的话，就会开启所有menu-item的路由跳转。我确实可以在menu-item里面再写一个a标签，但是点击a标签的时候也会同时触发外面的menu-item的路由，感觉很别扭

**Comment by xuexb** [comment]
> 如果设置了:router="true"的话，就会开启所有menu-item的路由跳转。我确实可以在menu-item里面再写一个a标签，但是点击a标签的时候也会同时触发外面的menu-item的路由，感觉很别扭

我也遇到了, 我是采用笨方法把`index=""`空了...哈哈 @mingbai2006 

并且发现`<el-menu-item...><a>`嵌套的`a`标签不是`block`, 导致点击区域不明显~

**Comment by langgo** [comment]
都写成 index="" 会导致 **多个菜单为激活状态**

一个丑陋的写法是  `index="#xxx" index="#bbb"`

**Comment by WuSht** [comment]
> > 如果设置了:router="true"的话，就会开启所有menu-item的路由跳转。我确实可以在menu-item里面再写一个a标签，但是点击a标签的时候也会同时触发外面的menu-item的路由，感觉很别扭
> 
> 我也遇到了, 我是采用笨方法把`index=""`空了...哈哈 @mingbai2006
> 
> 并且发现`<el-menu-item...><a>`嵌套的`a`标签不是`block`, 导致点击区域不明显~

有发现新的方法么？
