### ISSUE TITLE
在包含el-input-number的el-form里配置rules不生效,无法及时监听用户是否输入，这个能否处理?

### ISSUE THREAD

**Issue by eliya123** [ElemeFE/element#19804]
<el-form-item prop="score" :rules="rule"><el-input-number /></el-form-item>
rules = [{ required: true, message: "请输入", trigger: ["blur", "change"] }]

**Comment by jade-liu** [comment]
> rules = [{ required: true, message: "请输入", trigger: ["blur", "change"] }]

请问这个问题找到解决的办法了吗？

**Comment by eliya123** [comment]
> > rules = [{ required: true, message: "请输入", trigger: ["blur", "change"] }]
> 
> 这个问题找到解决的办法了吗？

这个问题解决了。
我之间在网上查，el-input-number无法监听@input事件，后来自己写的，效果也一样，
我的el-input需要监听的值是表格动态输出的属性，所以我v-model的属性是这样myFrom.tableData[scope.$index]。

使用方式：使用了限制input输入校验和rule校验结合校验方式。
使用代码：你看看下面 对你有没有帮助
<template>里：
<el-input
      @input="inputFilter($event, scope)"
      :key="scope.row.perfKpiName"
      v-model="myFrom.tableData[scope.$index].perfKpiSco"
      autocomplete="off"
></el-input>

methods里写限制input输入校验：
 inputFilter(event, scope) {
      // 正则 input框限制输入数字和小数点，且小数点不超过2位
      const val = event
        .replace(/[^\d^\.]+/g, "")
        .replace(".", "$#$")
        .replace(/\./g, "")
        .replace("$#$", ".")
        .replace(/^\D*(\d*(?:\.\d{0,2})?).*$/g, "$1");
      this.myFrom.tableData[scope.$index].perfKpiSco = val;
 },

computed里：
   getRules() {
      let rules = {};
      this.multipleSelection.forEach(item => {
        rules["tableData[" + item.myId + "].perfKpiSco"] = [
          {
            required: true,
            message: "请输入0~100",
            trigger: ["blur", "change"]
          },
          {
            pattern: this.PATTERN,
            message: "请输入0~100"
          }
        ];
      });
      return rules;
    },
此getRules配置在el-form里
<el-form
    :inline="true"
    :model="myFrom"
    ref="wnForm"
    :rules="getRules"
  >

**Comment by jade-liu** [comment]
> > > rules = [{ required: true, message: "请输入", trigger: ["blur", "change"] }]
> > 
> > 
> > 这个问题找到解决的办法了吗？
> 
> 这个问题解决了。
> 我之间在网上查，el-input-number无法监听@input事件，后来自己写的，效果也一样，
> 我的el-input需要监听的值是表格动态输出的属性，所以我v-model的属性是这样myFrom.tableData[scope.$index]。
> 
> 使用方式：使用了限制input输入校验和rule校验结合校验方式。
> 使用代码：你看看下面 对你有没有帮助
> 里：
> <el-input
> @input="inputFilter($event, scope)"
> :key="scope.row.perfKpiName"
> v-model="myFrom.tableData[scope.$index].perfKpiSco"
> autocomplete="off"
> 
> > 
> 
> methods里写限制input输入校验：
> inputFilter(event, scope) {
> // 正则 input框限制输入数字和小数点，且小数点不超过2位
> const val = event
> .replace(/[^\d^.]+/g, "")
> .replace(".", "$#$")
> .replace(/./g, "")
> .replace("$#$", ".")
> .replace(/^\D*(\d*(?:.\d{0,2})?).*$/g, "$1");
> this.myFrom.tableData[scope.$index].perfKpiSco = val;
> },
> 
> computed里：
> getRules() {
> let rules = {};
> this.multipleSelection.forEach(item => {
> rules["tableData[" + item.myId + "].perfKpiSco"] = [
> {
> required: true,
> message: "请输入0 ~ 100",
> trigger: ["blur", "change"]
> },
> {
> pattern: this.PATTERN,
> message: "请输入0 ~ 100"
> }
> ];
> });
> return rules;
> },
> 此getRules配置在el-form里
> <el-form
> :inline="true"
> :model="myFrom"
> ref="wnForm"
> :rules="getRules"
> 
> >
好的 谢谢啦 可以仔细看看，参考一下
