### ISSUE TITLE
[feature request] wants to add a radio check box focus method to make it focus

### ISSUE THREAD

**Issue by NicCraver** [ElemeFE/element#19806]
### Existing Component
是

### Component Name
 Radio Checkbox

### Description
希望添加 Radio Checkbox focus方法  使其获得焦点
有些场景需要使用回车代替Tab的功能，原生是支持的，希望element也能支持。
也许是我还太菜没想到更优秀的解决方案，有大佬指导怎么解决可以在下面评论，谢谢！

**Comment by GQxQD** [comment]
可以试试这样：
```js
this.$refs.elRadio.$el.focus()
```
