### ISSUE TITLE
upload控件，BeforeUpload方法中异步获取action和data属性需要的值

### ISSUE THREAD

**Issue by ThinkRealize** [ElemeFE/element#1980]
### ElementUI version
1.0.8

### OS/Browers version
 macOS/Chrome 55

### Vue version
2.1.4

在文件选择后，调用beforeUpload方法，在该方法中会异步获取action和data属性需要的值。
<el-upload
  ...
  :action="action"
  :data="uploadData"
>
</el-upload>
beforeUpload(file) {

  ajax(file, (data) => {

     this.action = data.action
     this.uploadData = {policy: data.policy ...}
 })
}
但是设置之后发起上传请求时，设置的data和action数据没有在请求中。该怎么样才能使设置的data和action在请求中？

**Comment by ThinkRealize** [comment]
问题解决  

在beforeUpload() {
  let _self = this
 return new Promise(function (resolve, reject) {
 ajax(file, (data) => {

_self._data.action = data.action
_self._data.uploadData = {policy: data.policy ...}

resolve(true)
})
}
}

**Comment by x4storm** [comment]
@ThinkRealize  我这样做还是不行，上传时，动态设置的数据还没就绪。

**Comment by ThinkRealize** [comment]
@x4storm 是在异步调用成功的回调方法内设置action和data

**Comment by x4storm** [comment]
@ThinkRealize 是啊，但是upload组件上传时取不到数据，在beforeUpload的异步调用里，setTimeout延迟resolve才能成功。

**Comment by qky1412** [comment]
@x4storm 所以问题解决了吗？

**Comment by zxh2013** [comment]
同问？
