### ISSUE TITLE
[bug report] dialog dialog box click occlusion layer close experience is not good

### ISSUE THREAD

**Issue by CherryBoomBoom** [ElemeFE/element#19809]
### Element UI version
2.13.2

### OS/Browsers version
window10/Chrome79.0.3945.88

### Vue version
3.0.0-beta.20

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
鼠标在对话框窗体内按下，在遮挡层外按下

### What is Expected?
不会关闭对话框

### What is actually happening?
会关闭对话框，实际应用的场景是我在对话框中输入了一个表单，之后我想全选清除输入的内容，会下意识鼠标从文本后按下拉到最远端抬起，这时候对话框不在我预期内关闭了

**Comment by jinchou** [comment]
点赞，最近也遇到这个问题，很影响表单录入
