### ISSUE TITLE
[bug report] cascade cascaded lazy loading mode. When resolving, it can only be incremental data, not initialization mode, and the data will be added repeatedly

### ISSUE THREAD

**Issue by Will-yc** [ElemeFE/element#19843]
### Element UI version
2.13.2

### OS/Browsers version
win10/chrome78.0.3904.97

### Vue version
3.0.0-beta.20

### Reproduction Link
https://elementui.github.io/issue-generator # http://hosapi.qizhekeji.com/update/test.html

### Steps to reproduce
1、点击测试按钮
2、清理选择的默认数据
3、再次点击测试按钮
重复以上三步，会发现数据在一直叠加，查看了源码，数据是一直在叠加的，

### What is Expected?
在第三步点击测试按钮时，效果和第一次一样，
如果在子组件中，无法在网络请求中获取最新的数据
期望能给定一个初始化行为的参数，用一个参数来控制是增量还是初始化

### What is actually happening?
在重复以上三步时，每次数据都会出现叠加的情况

**Comment by Littledevil7** [comment]
Please post your code

**Comment by yc825106632** [comment]
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
</head>
<body>
  <div id="app">
    <el-cascader size='mini'  v-model='selText'
			placeholder="测试"
			:props="lazyProps"
			:show-all-levels="false"
			clearable></el-cascader>
			<el-button @click="test" type="primary">主要按钮</el-button>
  </div>
</body>
  
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
		  let that = this
        return { 
			data:[{"pId":0,"children":[{"pId":1,"children":[],"label":"111","value":2,"leaf":true},{"pId":1,"children":[],"label":"112","value":5,"leaf":true}],"label":"上级1","value":1,"leaf":false},{"pId":0,"children":[{"pId":3,"children":[],"label":"2222","value":4,"parentName":"上级2","leaf":true}],"label":"上级2","value":3,"leaf":false},{"pId":0,"children":[],"label":"上级3","value":6,"leaf":true},{"pId":0,"children":[],"label":"上级4","value":7,"leaf":true}],
			selText:[],
			lazyLoadNode:{},
			lazyData:[],
			lazyLoadresolve:{},
			lazyProps: {
			  lazy: true,
			  checkStrictly: true,
			  multiple: true,
			  lazyLoad (node, resolve) {
				const { level } = node;
				that.lazyLoadNode = node
				that.lazyLoadresolve = resolve
				resolve();
				if(level == 'ini' ){
					that.lazyData = that.data.filter(item => {
							item.leaf = item.children.length == 0 ?'leaf':'';
							return item.pId == 0;
					 })
					 resolve(that.lazyData);
				}
			  }
			}
		}
      },
	  methods: {
		test(){
			let that = this
			that.lazyLoadNode.level='ini'
			that.lazyProps.lazyLoad(that.lazyLoadNode,that.lazyLoadresolve)
			that.selText = [[3],[1,5]]
		}
	  }
    })
  </script>
</html>

**Comment by yc825106632** [comment]
`
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
</head>
<body>
  <div id="app">
    <el-cascader size='mini'  v-model='selText'
			placeholder="测试"
			:props="lazyProps"
			:show-all-levels="false"
			clearable></el-cascader>
			<el-button @click="test" type="primary">主要按钮</el-button>
  </div>
</body>
  
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
		  let that = this
        return { 
			data:[{"pId":0,"children":[{"pId":1,"children":[],"label":"111","value":2,"leaf":true},{"pId":1,"children":[],"label":"112","value":5,"leaf":true}],"label":"上级1","value":1,"leaf":false},{"pId":0,"children":[{"pId":3,"children":[],"label":"2222","value":4,"parentName":"上级2","leaf":true}],"label":"上级2","value":3,"leaf":false},{"pId":0,"children":[],"label":"上级3","value":6,"leaf":true},{"pId":0,"children":[],"label":"上级4","value":7,"leaf":true}],
			selText:[],
			lazyLoadNode:{},
			lazyData:[],
			lazyLoadresolve:{},
			lazyProps: {
			  lazy: true,
			  checkStrictly: true,
			  multiple: true,
			  lazyLoad (node, resolve) {
				const { level } = node;
				that.lazyLoadNode = node
				that.lazyLoadresolve = resolve
				resolve();
				if(level == 'ini' ){
					that.lazyData = that.data.filter(item => {
							item.leaf = item.children.length == 0 ?'leaf':'';
							return item.pId == 0;
					 })
					 resolve(that.lazyData);
				}
			  }
			}
		}
      },
	  methods: {
		test(){
			let that = this
			that.lazyLoadNode.level='ini'
			that.lazyProps.lazyLoad(that.lazyLoadNode,that.lazyLoadresolve)
			that.selText = [[3],[1,5]]
		}
	  }
    })
  </script>
</html>`

**Comment by yc825106632** [comment]
代码发布后，html的标签丢失，以下链接就是源码    view-source:http://hosapi.qizhekeji.com/update/test.html

**Comment by yc825106632** [comment]
Code is released, the HTML tag is missing, the following link is the source    view-source:http://hosapi.qizhekeji.com/update/test.html

**Comment by yc825106632** [comment]
[12312](view-source:http://hosapi.qizhekeji.com/update/test.html)

**Comment by yc825106632** [comment]
```  

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <!-- import CSS -->
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
</head>
<body>
  <div id="app">
    <el-cascader size='mini'  v-model='selText'
			placeholder="测试"
			:props="lazyProps"
			:show-all-levels="false"
			clearable></el-cascader>
			<el-button @click="test" type="primary">主要按钮</el-button>
  </div>
</body>
  <!-- import Vue before Element -->
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <!-- import JavaScript -->
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
		  let that = this
        return { 
			data:[{"pId":0,"children":[{"pId":1,"children":[],"label":"111","value":2,"leaf":true},{"pId":1,"children":[],"label":"112","value":5,"leaf":true}],"label":"上级1","value":1,"leaf":false},{"pId":0,"children":[{"pId":3,"children":[],"label":"2222","value":4,"parentName":"上级2","leaf":true}],"label":"上级2","value":3,"leaf":false},{"pId":0,"children":[],"label":"上级3","value":6,"leaf":true},{"pId":0,"children":[],"label":"上级4","value":7,"leaf":true}],
			selText:[],
			lazyLoadNode:{},
			lazyData:[],
			lazyLoadresolve:{},
			lazyProps: {
			  lazy: true,
			  checkStrictly: true,
			  multiple: true,
			  lazyLoad (node, resolve) {
				const { level } = node;
				that.lazyLoadNode = node
				that.lazyLoadresolve = resolve
				resolve();
				if(level == 'ini' ){
					that.lazyData = that.data.filter(item => {
							item.leaf = item.children.length == 0 ?'leaf':'';
							return item.pId == 0;
					 })
					 resolve(that.lazyData);
				}
			  }
			}
		}
      },
	  methods: {
		test(){
			let that = this
			that.lazyLoadNode.level='ini'
			that.lazyProps.lazyLoad(that.lazyLoadNode,that.lazyLoadresolve)
			that.selText = [[3],[1,5]]
		}
	  }
    })
  </script>
</html>

```

**Comment by Will-yc** [comment]
我本地做了调整
cascader_panel.js
 1036行Store.prototype.appendNodes方法中添加 
 if(_this2.config.init){
   _this2.nodes=[]
  }
1400行function resolve(dataList)方法中
添加 _this5.config.init = node.init
test()中添加 that.lazyLoadNode.init=true
这样可以达到预期效果，而且对原有的功能不做修改

**Comment by Will-yc** [comment]
希望下个版本中，能将这个bug修改掉，
