### ISSUE TITLE
table里的数据 不能获取二级的数据 比如获取 row.parentContent.content

### ISSUE THREAD

**Issue by jialuchun** [ElemeFE/element#1984]

**Comment by furybean** [comment]
请提供测试用例。

**Comment by unique542** [comment]
我也遇见了类似的问题，我提供一个demo
http://jsfiddle.net/pq3my2a9/
这个主要是table组件中如果有table嵌套，那么无法获取父级节点上下文

**Comment by unique542** [comment]
@furybean 你看看我这个

**Comment by furybean** [comment]
@unique542 context 设置的有问题，更新了一下：http://jsfiddle.net/pq3my2a9/1/

**Comment by unique542** [comment]
@furybean 依然无法删除
@click.native.prevent="deleteRow($index, rows)"
这个我是想把父的row传递给方法，直接在删除数据中父的child。
设置:context="_self.$parent"之后，$index, rows仍然是子节点的数据，详情请看下面提供的demo
更新了一下：http://jsfiddle.net/pq3my2a9/4/

**Comment by QingWei-Li** [comment]
当前的 column 的实现并没有暴露它的上下文，因此没法获取它的父级元素。同时之前的用法不再推荐使用，等 1.1 发布后用 Scoped slots 定制 column 的内容

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/1942 1.1 发布后请用 scoped slot
