### ISSUE TITLE
upload before-upload file.uid 是undefined

### ISSUE THREAD

**Issue by ThinkRealize** [ElemeFE/element#1985]
### ElementUI version
1.0.8

### OS/Browers version
 macOS/Chrome 55

### Vue version
2.1.4

upload控件，上传文件。在before-upload 方法中回调的file.uid属性是undefined，在on-success 是有的。这是设计上的考虑，还是BUG？

**Comment by baiyaaaaa** [comment]
因为文件上传前是还未放到 fileList 当中的，在此阶段还是一个 raw file 对象，所以没有添加 uid，如果建议增加，你使用的场景是什么？

**Comment by ThinkRealize** [comment]
在before-upload回调方法中，进行异步请求获取OSS的上传token。情趣时要用到uid

**Comment by baiyaaaaa** [comment]
那这个 uid 应该是你的业务需求？好像跟组件里的 uid 没有关系吧

**Comment by ThinkRealize** [comment]
为了直接把组件内的uid设置为业务uid，和组件没有关系

**Comment by JackZong** [comment]
uid 是文件的md5吗
