### ISSUE TITLE
[Bug Report] chrome使用google翻译时显示异常

### ISSUE THREAD

**Issue by undefined9999** [ElemeFE/element#19852]
### Element UI version
2.13.2

### OS/Browsers version
win7/79.0.3945.117（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
进入https://element.eleme.cn/#/zh-CN/component/date-picker随便点击一个日期选择框, 然后使用chrome的google翻译插件翻译为中午, 在日期1后面会出现的'个'字
https://element.eleme.cn/#/zh-CN/component/pagination 分页组件页面, 直接使用chrome的google翻译插件进行翻译会出现汉字 '个'

### What is Expected?
使用google翻译插件翻译, 数字1后面不应该出现汉字 '个'

### What is actually happening?
使用google翻译插件翻译, 数字1后面应该出现汉字 '个', 在日期组件和分页组件都出现了

**Comment by DenghuaCN** [comment]
不是第一次有人提出了这个问题了
