### ISSUE TITLE
el-table 用fixed属性之后column出现错位的情况

### ISSUE THREAD

**Issue by znh-gogo** [ElemeFE/element#19855]
![1594803079(1)](https://user-images.githubusercontent.com/51782185/87525097-9dfcdd00-c6bb-11ea-84f6-8ee762679ae4.png)
这种情况有办法解决么？

**Comment by zhanjunhao** [comment]
兄弟我也遇到这问题 引发了后续很多问题 虽然我用 
`
    renderTableComps() {
      this.tableShowFlag = false;
      this.$nextTick(() => {
        this.tableShowFlag = true;
      })
    },
`
 但是如果你的父组件 那边传递一个data 会导致初始化props的问题 好烦....
