### ISSUE TITLE
dropdown组件中dropdown-menu的定位问题

### ISSUE THREAD

**Issue by unique542** [ElemeFE/element#1986]
![j z lmj i72dwy194_ acqf](https://cloud.githubusercontent.com/assets/9104616/21475480/042683d2-cb67-11e6-9c39-16aecc362a9f.png)
在dropdown组件中，dropdown-menu的定位跟父节点没有右对其，但是我在官方的示例中，看到的样式是右对齐的，请问如何实现？
![image](https://cloud.githubusercontent.com/assets/9104616/21475495/3a8f7384-cb67-11e6-9e5d-4bdf130b7300.png)

**Comment by unique542** [comment]
这个问题会在父节点处于浏览器最右侧时出现，在其他位置的时候就是正常的右对齐。

**Comment by baiyaaaaa** [comment]
可以提供个demo

**Comment by unique542** [comment]
http://jsfiddle.net/sd729qx9/1/
@baiyaaaaa 只要设置body{margin：0}就有问题，这样做全屏的但也应用很丑的诶

**Comment by baiyaaaaa** [comment]
1.1.0+版本已修复此问题
