### ISSUE TITLE
Menu navigation does not jump, but is selected

### ISSUE THREAD

**Issue by wtto00** [ElemeFE/element#19871]
### Element UI version
2.4.5

### OS/Browsers version
win10-wsl-Ubuntu20.04/chrome 83.0.4103.116

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
重现链接：https://codesandbox.io/s/heuristic-benz-bctq8?file=/src/App.vue

上述输入的链接不支持codesandbox，以这个链接为准

1. 首先我在`router/index.js`中重写了`router.push`函数，是为了解决导航菜单重复点击报错的问题
2. 我有需求是：导航前验证是否登录，如果没登陆则不导航（不跳转登录界面），停留在原页面。这个逻辑写在`router/index.js`中的`router.beforeEach`

那么点击上述重现链接中的导航菜单，注意下方的导航内容。

### What is Expected?
当点击导航菜单`管理中心`的时候，由于没有登录，则不会跳转，那么导航菜单就不应该被选中

### What is actually happening?
当点击导航菜单`管理中心`的时候，由于没有登录，则不会跳转，下方的页面内容也显示没有跳转，但是导航菜单却设置了选中状态

**Comment by wtto00** [comment]
> 首先我在`router/index.js`中重写了`router.push`函数，是为了解决导航菜单重复点击报错的问题

如果不重写`router.push`函数，那么导航菜单不会跳转，也不会被选中，是正常的。但是控制台会有报错信息。

不管重不重写的问题，实际的逻辑也应该是：**设置选中状态写在跳转成功的回调函数中**

**Comment by wtto00** [comment]
已提交PR #19872

**Comment by wxs77577** [comment]
@wtto00 抱歉，github没有私信，公司项目技术选型，就在这里问一下了。

1. 请问是否有Roadmap及未来规划。
2. 请问官方是否有计划跟进 `vue 3.0`
3. 请问在 `vue` 和 `react` 中您个人推荐那一个？

期待得到您的回复。

**Comment by wtto00** [comment]
@wxs77577 你怎么发到这里来了，这只是一个bug反馈贴。而且**我不是官方人员呀！**

你可以试下加群，里面应该有官方的人员，这个仓库给人一种没人维护的感觉。

**Comment by wxs77577** [comment]
@wtto00 尴尬。。我看你是这个库的作者。。打扰了

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147
