### ISSUE TITLE
分页功能在调整每页条数时当前页恢复到首页

### ISSUE THREAD

**Issue by Michaelwong0820** [ElemeFE/element#19889]
在使用分页功能，调整每页条数，组件会以当前页进行搜索，实际开发一般在改变页面条数的同时以首页去搜索内容

**Comment by mengbaiai** [comment]
分页组件的目的是可扩展，而不是定制。

**Comment by leixu2txtek** [comment]
属于业务侧功能，可以在 size-change 时设置页码，并不属于组件问题
