### ISSUE TITLE
[bug report] when the drawer component is pulled out, the default focus should be the same as the historical version, and the title should not be selected.

### ISSUE THREAD

**Issue by AnneMin** [ElemeFE/element#19902]
### Element UI version
2.13.2

### OS/Browsers version
MAC OS 版本10.12.6 /Google Chrom 版本 84.0.4147.89

### Vue version
2.6.1

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F2.13%2F

### Steps to reproduce
elementui官网，选择版本2.13.2，找到Drawer 抽屉组件，打开抽屉弹窗，标题默认有蓝色边框，被focus了。

### What is Expected?
纯文字标题，希望标题不被默认选中，span标签和div标签不使用focus属性，效果如历史版本一样。

### What is actually happening?
正常操作浏览官网即可重现。

**Comment by Sapphire2k** [comment]
@AnneMin 看了源码，el-drawer open的时候会自动触发 focusFirstDescendant,

```
aria.Utils.isFocusable = function (element) {
  if (element.tabIndex > 0 || element.tabIndex === 0 && element.getAttribute('tabIndex') !== null) {
    return true;
  }
  ...
};
```
**也就是 把 el-drawer里面的第一个标签加上tabindex="0" 或者 大于0的任意值即可**

**Comment by Aaronliu2016** [comment]
不止标题，drawer打开后点drawer内部空白区域，会focus整个弹出框。历史版本没有这个问题。

**Comment by cs1707** [comment]
Fixed
