### ISSUE TITLE
[Feature Request] Is there a plan for vue3 compatibility and support?

### ISSUE THREAD

**Issue by tobemaster56** [ElemeFE/element#19904]
### Existing Component
否

### Component Name
vue3 compatibility and support

### Description
Element, is it just a maintenance phase now? Do you have plans for compatibility and support of vue3?

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment]
Duplicate of #20375
