### ISSUE TITLE
上传组件 查看图片 按钮如何触发？

### ISSUE THREAD

**Issue by Leungkingman** [ElemeFE/element#1991]
![qq20161226-0](https://cloud.githubusercontent.com/assets/16955472/21477730/92145a62-cb7f-11e6-9fc3-3040da8c9878.png)

如图所示，文档上这个按钮目测没有对应的钩子函数，请问要怎么触发这个按钮的方法呢？

**Comment by baiyaaaaa** [comment]
`on-preview`
