### ISSUE TITLE
Tabs标签组件与Vue的 v-if 结合使用问题

### ISSUE THREAD

**Issue by niyuhan** [ElemeFE/element#19910]
使用Tabs标签时，当有多个tab时（tab内的数据都一样），默认为第一个，第一个中tab-panel中有一个标签使用了v-if控制显示与否，首次进入时，v-if正常，条件为false，隐藏了，这时切换到其他标签，其他标签v-if控制显示的标签显示了出来，并且默认第一个也显示了出来。

首次进入，正常：
![image](https://user-images.githubusercontent.com/29651573/88171048-43322b00-cc51-11ea-820f-fba72ee03225.png)

切换到其他标签（所有标签使用的数据一样，并且操作过程未更改数据），不正常：

![image](https://user-images.githubusercontent.com/29651573/88171130-665cda80-cc51-11ea-8445-9735c964212f.png)

切换回原标签，不正常：
![image](https://user-images.githubusercontent.com/29651573/88171296-a9b74900-cc51-11ea-9538-83609e06c60c.png)

**Comment by bingyuea** [comment]
你可能需要 key
