### ISSUE TITLE
[Feature Request] dialog功能优化

### ISSUE THREAD

**Issue by fmkj-hhh** [ElemeFE/element#19913]
### Existing Component
是

### Component Name
el-dialog

### Description
1、增加高度属性，弹窗的高度内容很高的话，滚动条要在弹窗内显示，这样下面的取消和确定就能一直显示了
2、增加是否拖动的开关，不要使用自定义事件(vue-element-admin)中的方案 使用变量控制是否可拖动
3、增加最大化 最小化 的开关，最小化的功能还是挺实用的
4、增加resize开关 效果和windows的改变窗口大小一样

**Comment by DickyNet** [comment]
支持，我也正想提这些功能改进呢。同时希望抽屉组件也支持拖放功能。

**Comment by 5265liu** [comment]
@fmkj-hhh 你自己封装一下就行了啊，高度那个加个class名字不就行了吗

**Comment by fmkj-hhh** [comment]
> @fmkj-hhh 你自己封装一下就行了啊，高度那个加个class名字不就行了吗

添加class 属性 不够灵活，系统里面会有好多用到弹窗的地方，使用class修改弹窗高度得有好多个class，不方便
如果自己封装dialog，就不能完全继承现有dialog的所有属性，有多少个prop就得封装的时候就得添加多少个prop，这样才能完全支持el-dialog
