### ISSUE TITLE
日期选择器

### ISSUE THREAD

**Issue by frontend-cherry** [ElemeFE/element#19930]
#### 希望能支持多选日期
![image](https://user-images.githubusercontent.com/43592730/88365853-eb630380-cdb9-11ea-9220-a78b3670e914.png)

**Comment by flay-boy** [comment]
有新的进度吗，实现了吗？

**Comment by jstf9673** [comment]
据说element团队不维护了，不知道是不是真的

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147
