### ISSUE TITLE
Bug report el-cascader remove tag is not the one you click

### ISSUE THREAD

**Issue by howsong** [ElemeFE/element#19934]
Element UI version
2.13.1

OS/Browsers version
chrome 版本 84.0.4147.89

Vue version
2.5.21

What is actually happening?
in form edit echo data and el-cascader in  mutiply model, when you remove a tag,
![20200724161326](https://user-images.githubusercontent.com/20580258/88372884-5f58d800-cdc9-11ea-8843-cead18b3f6df.jpg)
  actually the moved one is another.

**Comment by mouday** [comment]
me too...
