### ISSUE TITLE
表格 table 在360浏览器会错位。 chrome  显示是正常的。

### ISSUE THREAD

**Issue by settlerfan** [ElemeFE/element#19939]
![image](https://user-images.githubusercontent.com/47181791/88455360-49214980-cea7-11ea-9574-a1ebd52359d8.png)

![image](https://user-images.githubusercontent.com/47181791/88455343-28f18a80-cea7-11ea-85e5-31e86e8f8e0b.png)

**Comment by FrontDream** [comment]
我在Chrome也有同样的错位
