### ISSUE TITLE
[Feature Request] Disable past dates on datepicker

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [ElemeFE/element#19942]
### Existing Component
Yes

### Component Name
datepicker

### Description
How to disable past dates?

**Comment by flay-boy** [comment]
datepicker has a [PickerOptions] attribute, you can go through prop [pickerOptions] disabled past dates.PickerOptions is a function that has a [disabledDate] attribute.

**Comment by ivanradojevic-web-dev** [comment]
tnx @flay-boy flay-boy 

If anyone needs it:

template:
<el-date-picker
      v-model="form.value1"
      type="daterange"
      start-placeholder="Start date"
      end-placeholder="End date"
      :picker-options = "pickerOptions"  
      >
</el-date-picker>

script/data/return:
pickerOptions: {
                    disabledDate(time) {
                        return time.getTime() < Date.now() - 8.64e7;
                                        }
                            },
