### ISSUE TITLE
[Bug Report] v-model of [time-picker] is inconsistent with what are displayed in the field

### ISSUE THREAD

**Issue by isgfka** [ElemeFE/element#19955]
### Element UI version
2.13.2

### OS/Browsers version
chrome 84.0.4147.89

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/isgfka/pen/RwrmpVb

### Steps to reproduce
1.  type 16:00:00 in the begintime field
2.  type 20:00:00 in the endtime field
3.  click the confirm button

### What is Expected?
begintime and endtime can be successfully changed

### What is actually happening?
nothing happened because the confirm button is disabled

**Comment by gekkonic** [comment]
value-format="yyyy-MM-dd HH:mm:ss"

**Comment by Littledevil7** [comment]
hello you can add one line like this:

**Comment by Littledevil7** [comment]
![image](https://user-images.githubusercontent.com/44463110/89116585-5e5e2f80-d4c8-11ea-871b-8914134ab6bd.png)

**Comment by isgfka** [comment]
> value-format="yyyy-MM-dd HH:mm:ss"

No, Format of time is not what I mean. I mean I can’t change time value when I following these 3 steps. Maybe you can have a try.

**Comment by isgfka** [comment]
> hello you can add one line like this:

As I said above, the key problem is that I can’t successfully change the v-model value when I tried these three steps mentioned above.

**Comment by isgfka** [comment]
> hello you can add one line like this:

Please try to type the time in the fields only by keyboard but not by the scrolling panel

**Comment by Littledevil7** [comment]
i hava change the time ,like this

**Comment by Littledevil7** [comment]
![image](https://user-images.githubusercontent.com/44463110/89137101-615d2c80-d569-11ea-9795-0c9e9d794131.png)
![image](https://user-images.githubusercontent.com/44463110/89137107-66ba7700-d569-11ea-85de-7c16b13bc2be.png)
But the premise is that you should adjust the later available time first, because the previous available time must be less than the later given time

**Comment by isgfka** [comment]
> ![image](https://user-images.githubusercontent.com/44463110/89137101-615d2c80-d569-11ea-9795-0c9e9d794131.png)
> ![image](https://user-images.githubusercontent.com/44463110/89137107-66ba7700-d569-11ea-85de-7c16b13bc2be.png)
> But the premise is that you should adjust the later available time first, because the previous available time must be less than the later given time

Yeah, I totally agree with the premise you said.
But actually there is still a wrong way for users to act like the steps i said and may feel a little confused.
So, the problem probably lies in the user experience of this component.
