### ISSUE TITLE
表单提交键盘触发事件失效问题

### ISSUE THREAD

**Issue by wenzhenxi** [ElemeFE/element#1996]
表单提交键盘触发事件失效问题

使用 <input type="text" @keyup.enter="handleSubmit2"> 可以成功触发回车事件

使用 <el-input type="text" @keyup.enter="handleSubmit2"></el-input> 无法触发回车事件

使用 <el-input type="text" @keyup.enter.native="handleSubmit2"></el-input> 可以成功触发回车事件

**Comment by Leopoldthecoder** [comment]
参考 FAQ 第一条。
