### ISSUE TITLE
[Feature Request] Support for Vue 3

### ISSUE THREAD

**Issue by HassanKrayem** [ElemeFE/element#19964]
### Existing Component
Yes

### Component Name
All Element UI

### Description
Current Version of Element UI 2.13.2 doesn't work on Vue 3 
It is very important for Element UI to be first Library to support Vue 3 and for companies that would like to get benefits of new Vue 3 features

**Comment by Wxh16144** [comment]
还没看到相关计划，感觉element-ui维护有点玄

**Comment by muthu32** [comment]
https://github.com/kkbjs/element3

**Comment by CherryRum** [comment]
看了一下维护人员 已经离职啦

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by zhouzhongyuan** [comment]
![image](https://user-images.githubusercontent.com/717817/102610184-b770ec00-4167-11eb-961b-1a210ec7b634.png)
