### ISSUE TITLE
[Bug Report] This function "this.$refs.tableRefsName.toggleRowSelection" has bugs

### ISSUE THREAD

**Issue by sea13502** [ElemeFE/element#19965]
### Element UI version
2.13.2

### OS/Browsers version
windows

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/sea13502/pen/gOPNWvR?editors=1111

### Steps to reproduce
To select the first column of table.the demand is select one column equals select two column. the end ，receive data is incorrect.

### What is Expected?
get correct selection and coordinate the view

### What is actually happening?
right view but wrong data

**Comment by LiuYnag** [comment]
这个问题什么时候部署的正式版本啊，遇到同样问题了，解决不掉

**Comment by sea13502** [comment]
> 这个问题什么时候部署的正式版本啊，遇到同样问题了，解决不掉

可以从外部解决，外部调用 this.$refs.tableRefsName.toggleRowSelection 的时候使用 this.$nextTick()
