### ISSUE TITLE
Support for Vue 3 是否会随着vue3.x版本更新？

### ISSUE THREAD

**Issue by sunji0peng** [ElemeFE/element#19975]
element UI会不会随着vue3.0正式版发布而更新呢？vue3.0能否兼容使用element ui

**Comment by muthu32** [comment]
It has started by someone else already https://github.com/kkbjs/element3

**Comment by sunji0peng** [comment]
OK,thanks

**Comment by oldfu** [comment]
似乎也不太更新了

**Comment by sunji0peng** [comment]
.......

**Comment by jiumengs** [comment]
希望可以继续更新下去 这么优秀的框架 不支持vue3太可惜了

**Comment by chuxiaoguo** [comment]
不是已经有人在偷偷更新了么！https://github.com/a631807682/ele-next

**Comment by iamkun** [comment]
Of course, there will be a major release after Vue 3.0 release.

**Comment by zazzaz** [comment]
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by sunji0peng** [comment]
thanks

**Comment by samchenws** [comment]
> 当然，在Vue 3.0发布之后将有一个主要版本。

希望能加快vue3的进度，因为vite确实很香，而且这是一个很棒的库，希望不要放弃，加油。
