### ISSUE TITLE
按钮超出隐藏

### ISSUE THREAD

**Issue by zxq08** [ElemeFE/element#19987]
# 首先 https://elementui.github.io/issue-generator 这个链接已经不可访问啦

问题主要：
希望能实现这一一个效果，当按钮列超过一定宽度或个数，能够像文本一样展示为...并添加一个展开icon，点击icon像消息框一样展开被隐藏的按钮
![image](https://user-images.githubusercontent.com/46339071/89104552-b0fa0600-d44c-11ea-8f8f-70ca083da1f1.png)

如图（图中是layui框架实现的效果，可做参考）

**Comment by s0ngyee** [comment]
已经可以访问了，目前暂无计划，可以考虑在业务中自行实现
