### ISSUE TITLE
[Bug Report] el-form 表单验证数字非必填,当填写非数字的情况后this.$refs.formData.validate((valid)=>{//valid is true})

### ISSUE THREAD

**Issue by lyf2nb** [ElemeFE/element#19993]
Element UI version
2.13.0

OS/Browsers version
Google Chrome 84.0.4147.105

Vue version
2.5.17

Reproduction Link
el-form 表单验证数字非必填,当填写非数字的情况后this.$refs.formData.validate((valid)=>{//valid is true})

Steps to reproduce
el-form 表单验证数字非必填,当填写非数字的情况后this.$refs.formData.validate((valid)=>{//valid is true})

What is Expected?
valid 应该是false

What is actually happening?
valid 是true

**Comment by cheers-hmm** [comment]
rules怎么写的
