### ISSUE TITLE
When the [bug report] table has a fixed column, the row height of the unfixed column is changed, and the row height of the fixed column changes asynchronously, and the table is disordered

### ISSUE THREAD

**Issue by czlh** [ElemeFE/element#19996]
### Element UI version
2.13.2

### OS/Browsers version
win10/chrome

### Vue version
3.0.0-rc.5

### Reproduction Link
https://codepen.io/czlh/pen/bGpbwjG?editable=true%3Dhttps%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
1，打开链接
2，鼠标调整表格中textarea的高度
3, 发现表格错乱，固定列（日期）的行高不同步变化

### What is Expected?
表格中textarea的高度改变后，固定列（日期）的行高同步变化

### What is actually happening?
表格中textarea的高度改变后，固定列（日期）的行高没有同步变化，表格错乱

**Comment by gideonpeters** [comment]
Please has this been fixed?
