### ISSUE TITLE
rc.5版本里NavMenu 组件参数 default-active变成了必填值

### ISSUE THREAD

**Issue by Plortinus** [ElemeFE/element#200]
### ElementUI version
1.0.0-rc.5
### OS/Browers version
macOS/Chrome 53
### Vue version
2.0.0-rc.8

如果`default-active`的值是错误的或者没有这个参数,`console`里报错:`Cannot read property 'indexPath' of undefined(…)`

**Comment by isunkui** [comment]
补充遇到的问题：

* 定向访问某个menu 中 url（或刷新当前页面）,会触发重定向到el-menu 的default-active页面
* 设置了unique-opened属性，导致无法展开submenu

**Comment by ScienJus** [comment]
也补充一下遇到的问题：

在NavMenu设置了select事件，点击item后sub-menu会合上。不过active依旧在那里点击的item上。删除select事件就不会出现。

vue@2.0.1 and element-ui@1.0.0-rc.5

**Comment by erguotou520** [comment]
The same question
![image](https://cloud.githubusercontent.com/assets/7945757/19186243/f1d76630-8cb7-11e6-9ce8-c47924d5472a.png)

代码如下
```html
<el-menu class="el-menu" :default-active="$route.path"
      theme="dark" :router="true">
  <el-menu-item index="/users">Users</el-menu-item>
  <el-menu-item index="/things">Things</el-menu-item>
</el-menu>
```

**Comment by saint3347** [comment]
el-menu 不能通过传入 data 动态渲染 el-menu-item吗？
![image](https://cloud.githubusercontent.com/assets/7347133/19229482/7b0cbe6a-8f00-11e6-9405-4fb0fae2295d.png)
然后我也遇到这个问题：
![image](https://cloud.githubusercontent.com/assets/7347133/19229504/aca122c2-8f00-11e6-9cbb-9849957c761f.png)

**Comment by lymanlai** [comment]
升级到rc.8就好了。。。自己调了好久。好郁闷。。
