### ISSUE TITLE
menu-item 绑定了index 但还是报错

### ISSUE THREAD

**Issue by HomyeeKing** [ElemeFE/element#20009]
控制台一直在报menu-item没有index的错，虽然不影响使用但是看着还是很糟心，但是我绑定了index还是报错这就有点难受了
![image](https://user-images.githubusercontent.com/49113249/89481588-ab911880-d7ca-11ea-9dfc-f08bda3a382a.png)

**`:index="nav.title+'' "`也试过，没效果**

![image](https://user-images.githubusercontent.com/49113249/89481606-b9469e00-d7ca-11ea-8de3-96018894c3ed.png)

**Comment by LemonAppleMo** [comment]
submenu这个组件需要给index

https://github.com/ElemeFE/element/blob/dev/packages/menu/src/submenu.vue#L33:L36
