### ISSUE TITLE
[Upload]Upload组件在drag模式下，在部分浏览器弹窗非常缓慢。

### ISSUE THREAD

**Issue by LWFeng** [ElemeFE/element#2000]
开发过程中使用Upload组件。发现使用了type=drag的时候在部分浏览器下。点击弹出选择框时非常缓慢。
 
在window，mac下不同浏览器测试，发现与平台无关，有的弹窗速度正常，有的要等7,8秒甚至10几秒才弹出选择框。直接拖拽图片上传正常，换成type=select的时候是正常的。
    
    Element版本：1.0.4
    
    Vue:  2.0.5

**Comment by Leopoldthecoder** [comment]
升到最新版试试。

**Comment by LWFeng** [comment]
@Leopoldthecoder 可以了，感谢！！！
