### ISSUE TITLE
[Bug Report] Not able to custom style el-select tag

### ISSUE THREAD

**Issue by darrylferdinands** [ElemeFE/element#20010]
### Element UI version
2.13.2

### OS/Browsers version
Mac OS Catalina / Latest Chrome Version 84.0.4147.105

### Vue version
3.0.0-rc.5

### Reproduction Link
https://codepen.io/darrylsteve/pen/WNwNLyB

### Steps to reproduce
Just wanna know how to custom style an el-select tag

### What is Expected?
Custom styling el-select and removing border

### What is actually happening?
el-select does not respond to custom styling when trying to remove the borders

**Comment by LemonAppleMo** [comment]
https://codepen.io/lemonapplemo/pen/JjXjzpP

Because you need to set the border of the input tag.

**Comment by darrylferdinands** [comment]
Thanks. That worked!
