### ISSUE TITLE
[Bug Report] select组件在绑定remote-method时出现下拉选项异常

### ISSUE THREAD

**Issue by Swarz** [ElemeFE/element#20025]
### Element UI version
2.13.2

### OS/Browsers version
win10,  chrome 84.0.4147.105

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/Swarz/pen/RwaPaOO

### Steps to reproduce

1. select①输入无法匹配的值，比如“sdasd”,等待“无匹配数据”出现
2. 点击空白，下拉框隐藏，再次点击select，下拉框出现
 select①下拉框无选项 </p>

select②选择一个值后重复1 2 动作 
select②下拉框最下面多了“无匹配数据”

### What is Expected?
 select①下拉框是全部选项
select②下拉框最下面无“无匹配数据”

### What is actually happening?
 select①下拉框无选项 </p>
select②下拉框最下面多了“无匹配数据”

**Comment by monkey001127** [comment]
官方也有这个问题，可以借助
@visible-change="visibleChange"
在visibleChange事件里调用一下重新查询下拉列表。
this.$refs.select.handleQueryChange()
