### ISSUE TITLE
Select控件multiple模式下，当选择第二个Option时会把第一个Option的显示的Label值变成Value

### ISSUE THREAD

**Issue by focusdada** [ElemeFE/element#2003]
## 问题描述 ##
> Step 1：输入"fo"，选择Option“Focus Xu”，此时Select控件显示正常，详见截图
 
![image](https://cloud.githubusercontent.com/assets/1005475/21489703/76e97552-cc28-11e6-94db-d153a423bf20.png)

> Step 2：输入“Se”，继续选择Option"Seraph Zhao"，测试控件把第一次选择的Focus Xu，自动替换成了L3014（Value值），详见截图
![image](https://cloud.githubusercontent.com/assets/1005475/21489730/bf4d24ba-cc28-11e6-99f3-664828bff7bf.png)

**Comment by focusdada** [comment]
## 代码 ##
![image](https://cloud.githubusercontent.com/assets/1005475/21489796/4cc8b4da-cc29-11e6-9cf5-5451ccb6f71d.png)
![image](https://cloud.githubusercontent.com/assets/1005475/21489800/5a4f0d20-cc29-11e6-88b9-152c68bc1f12.png)

**Comment by Leopoldthecoder** [comment]
Element 版本？

**Comment by Leopoldthecoder** [comment]
确认一下 Element 的版本为最新，如果有问题可以再打开。

**Comment by focusdada** [comment]
不好意思，最近在外地，没有看Issue动态。
我是一个月前从unpkg，下载到本地。查看index.js并没有看到版本信息。
PS:目前elelemnt-ui更新到1.1.2，我发现部分语法有变化，如果我更新的话会有问题吗？
Thanks in advance!

**Comment by Leopoldthecoder** [comment]
担心有兼容问题可以升到 1.0.9
