### ISSUE TITLE
The default value is [Select bug time]

### ISSUE THREAD

**Issue by xlouc** [ElemeFE/element#20038]
### Element UI version
2.13.2

### OS/Browsers version
Mac OS X 10_15_6 / Chrome/84.0.4147.105

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/mamying/pen/QWNjyMr

### Steps to reproduce
如链接：https://codepen.io/mamying/pen/QWNjyMr

### What is Expected?
组件可用

### What is actually happening?
组件不可用

**Comment by xlouc** [comment]
vue version : 2.6.11

**Comment by ChineseEngineer** [comment]
selectableRange: '00:00:00 - 23:59:00' try again

**Comment by xlouc** [comment]
ok， no problem
