### ISSUE TITLE
Pagination 的按钮会造成form 被submit出去

### ISSUE THREAD

**Issue by GniN** [ElemeFE/element#2004]
在el-form 里面放了一个 el-pagination
但pagination的按钮没有加type="button"
换页的时候都会造成form被submit出去

問題Demo如下:
https://jsfiddle.net/m2d9mpcy/1/

**Comment by kopheece** [comment]
这个应该是浏览器的问题，如果没有给button设置type；火狐，谷歌等浏览器会默认自动解析为type="submit"
