### ISSUE TITLE
[Bug Report]  el-date-picker选完日期把日历切到别的页，再打开，还在那页而不是选中日期页？

### ISSUE THREAD

**Issue by zsrzsrzsr-zsr** [ElemeFE/element#20052]
### Element UI version
2.13.2

### OS/Browsers version
Google Chrome  版本 84.0.4147.125（正式版本） （32 位）

### Vue version
3.0.0-rc.5

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F2.13%2F

### Steps to reproduce
选完日期把日历切到别的页，再打开，还在那页而不是选中日期页

### What is Expected?
选完日期把日历切到别的页，再打开，是选中日期页

### What is actually happening?
选完日期把日历切到别的页，再打开，还在那页

**Comment by saonan90077** [comment]
Are you sure that element supports vue3.0.0
