### ISSUE TITLE
el-image如果放在el-dialog里会发生fixed嵌套，会影响显示

### ISSUE THREAD

**Issue by jxy-web** [ElemeFE/element#20072]
![image](https://user-images.githubusercontent.com/42017349/90846421-ad4a0700-e39a-11ea-8f59-854e06253c31.png)
有什么好的解决办法吗？

**Comment by cs1707** [comment]
Duplicate of #19330

**Comment by Vawter-001** [comment]
我是这样做的：
`<el-image :src="value||alt_src" z-index="99999999" :preview-src-list="[value]" class="el-image"></el-image>`
