### ISSUE TITLE
[Bug Report] Unknown custom element: <el-drawer>

### ISSUE THREAD

**Issue by kikaendeavor** [ElemeFE/element#20084]
### Element UI version
2.13.2

### OS/Browsers version
win10 / chrome 84.0.4147.135

### Vue version
2.5.9

### Reproduction Link
https://codepen.io/nolink

### Steps to reproduce
just render <el-drawer>

### What is Expected?
el-drawer could be rended correctly

### What is actually happening?
Unknown custom element: el-drawer - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by xiaotianxia** [comment]
需要升级版本把

**Comment by kikaendeavor** [comment]
@xiaotianxia  几个版本都试过了

已放弃直接使用el-drawer，把el-dialog改了，实现了交互需求
