### ISSUE TITLE
[Bug Report] Element UI Docs Homepage is no longer working

### ISSUE THREAD

**Issue by SayonB** [ElemeFE/element#20086]
I don't know if this is the correct place to post this, but it is a critical error. I've tried on chrome, firefox, and edge.

### Element UI version
2.13.2

### OS/Browsers version
Windows 10, Chrome 84

### Vue version
3.0.0-rc.8

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
Go on the website
https://element.eleme.io/

### What is Expected?
A website that works

### What is actually happening?
A plain white page with this console error

Uncaught ReferenceError: Vue is not defined
    at Object.<anonymous> (docs.0216a22.js:1)
    at G (docs.0216a22.js:1)
    at i (docs.0216a22.js:1)
    at Module.<anonymous> (docs.0216a22.js:1)
    at Module.<anonymous> (docs.0216a22.js:1)
    at G (docs.0216a22.js:1)
    at s (docs.0216a22.js:1)
    at docs.0216a22.js:1
    at docs.0216a22.js:1
(anonymous) @ docs.0216a22.js:1
G @ docs.0216a22.js:1
i @ docs.0216a22.js:1
(anonymous) @ docs.0216a22.js:1
(anonymous) @ docs.0216a22.js:1
G @ docs.0216a22.js:1
s @ docs.0216a22.js:1
(anonymous) @ docs.0216a22.js:1
(anonymous) @ docs.0216a22.js:1

**Comment by SayonB** [comment]
In case anyone else encounters this, the issue is that the website does not work on a VPN.
I'm using NordVPN and the server country was Canada.

**Comment by naliga24** [comment]
I get this also dude, don't know what to do now.

**Comment by DevOrish** [comment]
has anyone found a solution? I cant access it for some reason. Works on my mobile, but not in the browser - also not on incognito.
I do not use VPN or anything....

**Comment by DevOrish** [comment]
> has anyone found a solution? I cant access it for some reason. Works on my mobile, but not in the browser - also not on incognito. I do not use VPN or anything....

1 minutes after writing that reply the website started to work again.
It hasent worked for me for a few months. I did not do anything.
I dont know what sorcery is this
