### ISSUE TITLE
form 与 tab + v-for + dialog 组合使用时无法通过 $refs 办法获得 form 实例

### ISSUE THREAD

**Issue by stackia** [ElemeFE/element#2009]
### ElementUI version
1.0.8

### OS/Browers version
Windows 10/Chrome 55

### Vue version
2.1.7

### Reproduction Link
http://codepen.io/jsq2627/pen/RozRYX

### What is Expected?
请看 codepen 代码中的注释。如何在 submitForm 方法中获得属于对应 tab/dialog 的 el-form 实例？

**Comment by njleonzhang** [comment]
我试了一下可以啊。
```
    submitForm (tab) {
      console.log(this.$refs.forms)
      // 此处如何获得属于 tab 的 el-form 实例？
      // myForm.validate(valid => { ... })
    }
```

**Comment by stackia** [comment]
@njleonzhang 如何识别 this.$refs.forms 中哪一个属于当前 tab？

**Comment by luckymore** [comment]
@stackia  
 加个 this.currentTab ，用 tab-click 更新值不行吗。。。

**Comment by njleonzhang** [comment]
@stackia 并不明白你的问题了。。。

**Comment by stackia** [comment]
此处该怎么调用validate？如何获得codepen实例里面“myForm”（属于当前激活tab里面的那个form）这个对象？

**Comment by njleonzhang** [comment]
哦，原来你有多个form而且ref是一样的，这就尴尬了。给不一样的名字就应该可以了。但是硬是用一样的，应该怎么办呢。。。这好像是一个vue的问题。

@QingWei-Li 求解！！！

另外借楼问个问题。个人觉得vue的组件通过ref去暴露方法，我感觉本身就非常的不优雅。但是公用组件会存在多份实例，所以不好用event bar和flux去实现，我想来想去也没什么好办法，请教有什么更好的选择么？

**Comment by yansenlei** [comment]
如果在el-form上使用了v-for，通过this.$refs[name]获取到的是一个数组，可以通过遍历这个数组获取验证结果

**Comment by NoraGithub** [comment]
为什么关掉？@baiyaaaaa
