### ISSUE TITLE
[Bug Report] dialog 在绑定了close和onclose方法之后

### ISSUE THREAD

**Issue by haozi000005** [ElemeFE/element#20095]
### Element UI version
2.13.2

### OS/Browsers version
Windows 10 / chrome85.0.4183.83

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/goumwdcx/1/

### Steps to reproduce
打开dialog的时候，close事件也被触发了

### What is Expected?
打开dialog的时候，close事件不应该被触发，close事件只有在关闭的时候才触发

### What is actually happening?
打开dialog的时候，close事件也被触发了

**Comment by erjun** [comment]
你代码示例有问题，你现在不是用的事件绑定@，而且传参属性的:，具体为什么传参会触发没具体研究，不过你的使用方法是错的

**Comment by haozi000005** [comment]
> 你代码示例有问题，你现在不是用的事件绑定@，而且传参属性的:，具体为什么传参会触发没具体研究，不过你的使用方法是错的
> 改成这样就ok了https://jsfiddle.net/0u6v8yod/

确实，这样是可以解决了， 谢谢~~~
