### ISSUE TITLE
cdn 模式  el-popconfirm   确认取消不好使

### ISSUE THREAD

**Issue by jmsdqwl** [ElemeFE/element#20118]
<el-popconfirm
                            title="确定删除吗？"
                            @on-confirm="confirm"
                    >

 confirm: function (val) {
                   console.log('aaa')
                }

不起作用

**Comment by shujiawei** [comment]
onConfirm 应该这样写吧

**Comment by jmsdqwl** [comment]
> onConfirm 应该这样写吧

CDN模式下 得像我那么写 VUE自身会有提示

**Comment by pcode** [comment]
确实不好用。编译环境里面是ok的。但是cdn的方式使用的时候，一点儿效果都没有。这个事件就是绑定不上函数。
按照vue的提示信息去改了一个非驼峰方案的名称，然而并无奇效。希望开发团队修改一下，这应该是个bug

**Comment by jmsdqwl** [comment]
你用没用过上传组件里面的 多选上传的功能  第一次上传行  第二次修改他 把文件删除了 就不能再多选了   1次选一个没问题 一多选就不行

**Comment by iamkun** [comment]
Now fixed to the correct 'confirm' and 'cancel' event name in #20240
