### ISSUE TITLE
el-image开启预览，按esc关闭预览后重新打开预览，按esc无响应

### ISSUE THREAD

**Issue by hong3yang** [ElemeFE/element#20121]

**Comment by cs1707** [comment]
你好，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以创建一个 [codepen](https://codepen.io/ziyoung/pen/rRKYpd) 或者提供一个最小化的 GitHub 仓库。 7 天内未跟进的 issue 将会被关闭。
