### ISSUE TITLE
el-image图片预览窗口希望能添加一个属性来控制是否点击遮罩层关闭预览框

### ISSUE THREAD

**Issue by TomSonghang** [ElemeFE/element#20128]
因为前后端没分离,用的CDN引入方式,今天上面需要实现这个(确实是大部分预览的操作);但是因为CDN引入,导致需要改动源码才行,一时半会不知道该怎么办,希望能够添加一个属性控制

**Comment by cs1707** [comment]
Already fixed in version 2.15.0
