### ISSUE TITLE
MessageBox 让confirm的button支持loading

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#2014]
messageBox用于confirm一些重要的事情，比如删除等操作。
按下confirm之后，一般会向后台发一个ajax请求，这时为了避免用户重复点击以及显示一个loading状态，button的loading属性是个不错的选择，但是看了一下现在messagebox并不能支持这个选项。是否考虑添加？或者如果你们已经考虑这个问题了，推荐怎么处理？

**Comment by Kingwl** [comment]
这个feature我有一个疑问
加在哪里 什么时候loading 什么时候去掉loading？
完全没头绪

**Comment by njleonzhang** [comment]
@Kingwl  和el-button的loading一样啊。

**Comment by stackia** [comment]
这个可以有

**Comment by laizquoquyou** [comment]
这个感觉有需要

**Comment by njleonzhang** [comment]
我抽空自己做了一个PR  https://github.com/ElemeFE/element/pull/2128
@QingWei-Li 大神看看行不行。
