### ISSUE TITLE
v1.0.8(vue 2.1.7) select远程搜索，当搜索结果为0的时候，之后再搜索不会显示下拉列表

### ISSUE THREAD

**Issue by jadbin** [ElemeFE/element#2016]
### ElementUI version

1.0.8

### OS/Browers version

macOS/Chrome 54

### Vue version

2.1.7

### Reproduction Link

http://jsfiddle.net/g2Lxcsn4/3/

### Steps to reproduce

先输入一个c，这个时候提示“无数据”
回车删除输入的c，
再输入一个a，不显示下拉列表

### What is Expected?

最后输入a的时候应该显示下拉列表

**Comment by thomasyonug** [comment]
试了一下，没有出现你说的情况

**Comment by jadbin** [comment]
@thomasyonug 不会吧……我用两个电脑都试了，mac和windows的都有问题，一个chrome 54，一个chrome 52

**Comment by jadbin** [comment]
我试了一下vue 2.1.6是没有这个问题的，但是vue切到2.1.7就会有这个问题

**Comment by Leopoldthecoder** [comment]
Vue 2.1.8 也没有这个问题，看起来是 2.1.7 的 bug。
