### ISSUE TITLE
[Bug Report] el-drawer title looks like it is focused by default, and has a blue frame

### ISSUE THREAD

**Issue by jsbay** [ElemeFE/element#20178]
### Element UI version
2.13.2

### OS/Browsers version
macos v10.15.6 / chrome  85.0.4183.102

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/pen/?&editable=true=https%3A%2F%2Felement.eleme.cn%2F

### Steps to reproduce
click button "点我打开"

### What is Expected?
el-drawer title do not surrounded by blue frame

### What is actually happening?
el-drawer title was surrounded by blue frame

In v2.13.2: **not ok**
![](http://img.baymax.club/20200916110304.png)

In v2.12.0: **ok**
![](http://img.baymax.club/20200916110137.jpg)

**Comment by tangyingcai** [comment]
自己修复一下吧。。 
看了下源码，drawer 组件显示后， 调用了：Utils.focusFirstDescendant(this.$refs.drawer); 
通过函数聚焦darwer组件里面的第一个element组件
![image](https://user-images.githubusercontent.com/12555754/93305379-02a9f480-f831-11ea-93a9-5e95d545337a.png)
注释掉这个函数后， 自己编译一个版本吧。。
直接引用编译后的js和css先这么过渡着吧。。

**Comment by jsbay** [comment]
真的没人维护了吗?:sweat_smile:
