### ISSUE TITLE
[Bug Report] 加油，奥力给！

### ISSUE THREAD

**Issue by fujiazhang** [ElemeFE/element#20186]
### Element UI version
2.13.2

### OS/Browsers version
加油，奥力给！

### Vue version
3.0.0-rc.12

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
加油，奥力给！

### What is Expected?
加油，奥力给！

### What is actually happening?
加油，奥力给！

**Comment by javascripet** [comment]
拜托复制粘贴几下毫无美感充满恶俗的网络用语污染环境的事情少做

**Comment by horseson2018** [comment]
去贴吧发这些东西，那里的人挺喜欢这个的
