### ISSUE TITLE
[Feature Request] Compatible with Vue 3?

### ISSUE THREAD

**Issue by frederikhors** [ElemeFE/element#20198]
### Existing Component
No

### Component Name
Vue3

### Description
_I apologize if it is written somewhere and I have not read it, I have searched._

Can I use this project with Vue 3?
Is there a temporary branch of work in progress that I can try?

I need to start a new project and need to find out more before starting.

Thank you.

**Comment by megamaiku** [comment]
https://github.com/ElemeFE/element/issues/20174

**Comment by zazzaz** [comment]
Yes, you can check Element Plus for Vue 3.0 right now. https://github.com/ElemeFE/element/issues/20061
