### ISSUE TITLE
import Element 后编译出错

### ISSUE THREAD

**Issue by HanSon** [ElemeFE/element#202]
import Element from 'element-ui' 之后，gulp编译时报错

Uncaught Error: Module build failed: SyntaxError: 'with' in strict mode

**Comment by QingWei-Li** [comment]
用的 webpack 么？babel-loader 或者 buble-loader 有配置 exclude 么，参考 https://github.com/ElementUI/element-starter/blob/master/webpack.config.js

总之就是不要让这些编译器处理到 element-ui

**Comment by HanSon** [comment]
不知道你是否了解laravel-elixir-vue，用的应该是webpack，不太清楚这种情况要怎么处理，前端有点硬伤。。

**Comment by QingWei-Li** [comment]
@csvwolf 写了个 laravel 的脚手架，你可以参考下
https://github.com/ElementUI/element-in-laravel-starter

**Comment by HanSon** [comment]
@QingWei-Li 感谢！可以了！
