### ISSUE TITLE
会适配vue3吗

### ISSUE THREAD

**Issue by Silentdoer** [ElemeFE/element#20213]
rt

**Comment by devbian** [comment]
https://github.com/ElemeFE/element/issues/20201 
这里

**Comment by zazzaz** [comment]
Element Plus - A Vue.js 3.0 UI library

https://github.com/ElemeFE/element/issues/20061

**Comment by 0xbul1** [comment]
朱昆明确表示项目不会凉。

**Comment by samchenws** [comment]
希望能升级VUE3，很支持这个项目

**Comment by Benleie** [comment]
> 朱昆明确表示项目不会凉。

具体怎么说

**Comment by snowdream** [comment]
element 接下来怎么走？

官方也没有个准信。

**Comment by xxyGoTop** [comment]
这个库没人维护了吧

**Comment by xxyGoTop** [comment]
唉，又要换了

**Comment by zhangli254804018** [comment]
啥时候可以支持vue3.x

**Comment by liubinylx** [comment]
> 朱昆明确表示项目不会凉。

阿里表示不同意

**Comment by zhouzhongyuan** [comment]
![image](https://user-images.githubusercontent.com/717817/102610184-b770ec00-4167-11eb-961b-1a210ec7b634.png)

**Comment by cs1707** [comment]
Duplicate of #20375
