### ISSUE TITLE
popover在table中无效

### ISSUE THREAD

**Issue by HomyeeKing** [ElemeFE/element#20211]
[复现地址](https://codepen.io/HomyeeKing/pen/yLOGydP?editable=true%3Dhttps%3A%2F%2Felement.eleme.cn%2F)

popover在table中hover无效

**Comment by Littledevil7** [comment]
you sholud insert <template slot-scope="scope"></template>,just like this 
![image](https://user-images.githubusercontent.com/44463110/93973572-009ee300-fda7-11ea-906a-1246c8dcd73e.png)

**Comment by HomyeeKing** [comment]
@Littledevil7  功能OK了，但是想知道为什么，只要是自定义都得用slot-scope包裹吗？  为什么能现实button，但是无法popover
