### ISSUE TITLE
Drawer 抽屉 在新版谷歌浏览器 及微信内置浏览器 中显示黑色边框

### ISSUE THREAD

**Issue by willianfu** [ElemeFE/element#20214]
### 谷歌浏览器：

![image](https://user-images.githubusercontent.com/25615627/93958430-0e457000-fd89-11ea-8285-1121221f5e66.png)

![image](https://user-images.githubusercontent.com/25615627/93958441-156c7e00-fd89-11ea-858f-146b3e8f45ca.png)

### 微信浏览器

![image](https://user-images.githubusercontent.com/25615627/93958495-31701f80-fd89-11ea-919b-02a5c691638b.png)

这样好丑啊。。。。以前貌似都没有，感觉就是最近一段时间出来的

**Comment by rolitter** [comment]
这是浏览器focus自带样式.重置一下样式就可以了
![image](https://user-images.githubusercontent.com/27326998/93973493-db11d980-fda6-11ea-835c-fae39d922383.png)
