### ISSUE TITLE
menu设置vue-router时，路由懒加载组件时在第二次路由时组件渲染失败

### ISSUE THREAD

**Issue by beijiaxu** [ElemeFE/element#2022]
如题，第一次进入该路由时，组件可以正常加载，再点击别的路由也正常，再点回刚刚加载的路由组件就不渲染了。我试了下纯原生的vue和vue-router是可以正常使用的，在element-ui下使用原生的router-link标签也无效，使用menu-item下的index也无效。
使用的版本是"element-ui": "1.0.6","vue": "2.1.4","vue-router": "2.1.1"
![qq 20161227181153](https://cloud.githubusercontent.com/assets/13776775/21497497/6b3d69ba-cc60-11e6-9553-9bf236b19b3a.png)
![qq 20161227181159](https://cloud.githubusercontent.com/assets/13776775/21497498/6bd9d354-cc60-11e6-9a80-6bcda7779984.png)
![qq 20161227181139](https://cloud.githubusercontent.com/assets/13776775/21497499/6cb58138-cc60-11e6-8426-25d964d31d01.png)

**Comment by beijiaxu** [comment]
没有人吗，求解啊~~~是bug还是我route用的不对

**Comment by baiyaaaaa** [comment]
你光截图谁知道问题在哪里，能提供个demo?

**Comment by beijiaxu** [comment]
@baiyaaaaa 我把demo上传到了git，麻烦帮忙看一下https://github.com/beijiaxu/vue-test
我之前试了下官方的cli使用倒是没什么问题，而且速度还很快。。。

**Comment by hojas** [comment]
```
const SysRole = r => require(['../sys/role.vue'], r)
```

这样是不行的，得改成这样：

```
const SysRole = r => {
    require(['../sys/role.vue'], r)
}
```

**Comment by beijiaxu** [comment]
@hojas 谢谢！一下就解决了
