### ISSUE TITLE
[Bug Report] dialog 'before-close' is not triggered

### ISSUE THREAD

**Issue by HomyeeKing** [ElemeFE/element#20235]
### Element UI version
2.13.2

### OS/Browsers version
mac  new 

### Vue version
2.5.9

### Reproduction Link
https://jsfiddle.net/homyking/zujLs9co/1/

### Steps to reproduce
click the button , check the console, there's nothing come out

### What is Expected?
when we click the confirm button , we should trigger the "before-close" event firstly , then we close the dialog manually

### What is actually happening?
just close the dialog immediately , not run the console in the "before-close" event

**Comment by tinycold** [comment]
The `before-close` event only be triggered when you click the close icon button on the top right.

If you want to control the dialog visibility, maybe you could call the hook function manually.

eg.
```
    // event handler for before-close
    onBeforeClose(done) {
      if(shouldBeClosed) {
        done()
      }
    },
    closeDialog() {
      // just close it directly
      // this.dialogVisible = false
      
      // call hooks manually
      const done = () => {
        this.dialogVisible = false
      }
      this.onBeforeClose(done)
    },
    confirm() {
      this.closeDialog()
    },
    cancel() {
      this.closeDialog()
    }
```
