### ISSUE TITLE
按需引入组件时，message、notification等会自动弹出？！

### ISSUE THREAD

**Issue by xiaoping6688** [ElemeFE/element#2024]
不想完整引入整个ElementUI，只引入部分组件，babel也配了，但页面刷新后message、notification会自动弹出。。。。其他组件显示没问题。不知什么原因：

import Vue from 'vue'

// 使用element组件库(完整引入)
// import ElementUI from 'element-ui'
// import 'element-ui/lib/theme-default/index.css'
// Vue.use(ElementUI)

// 按需引入
import {
  Row,
  Col,
  Icon,
  Button,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  Input,
  Select,
  Option,
  TimePicker,
  DatePicker,
  Form,
  FormItem,
  Table,
  TableColumn,
  Progress,
  Pagination,
  Alert,
  Loading,
  Message,
  MessageBox,
  Notification,
  Menu,
  Submenu,
  MenuItem,
  Breadcrumb,
  BreadcrumbItem,
  Dialog
} from 'element-ui'

Vue.use(Row)
Vue.use(Col)
Vue.use(Icon)
Vue.use(Button)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)
Vue.use(TimePicker)
Vue.use(DatePicker)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Progress)
Vue.use(Pagination)
Vue.use(Alert)
Vue.use(Loading)
// Vue.component(Message.name, Message)
// Vue.component(MessageBox.name, MessageBox)
// Vue.component(Notification.name, Notification)
Vue.use(Message)
Vue.use(MessageBox)
Vue.use(Notification)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Dialog)

**Comment by Leopoldthecoder** [comment]
它们不需要 `Vue.use`，在用到的地方直接用就可以。

**Comment by renxia** [comment]
参考一下我们的用法，或者官方的 `index.js` 的导出用法：

```js
// 选择性加载全局组件

import Vue from 'vue';

import {
    Alert,
    Breadcrumb,
    BreadcrumbItem,
    Button,
    Card,
    Checkbox,
    CheckboxGroup,
    Col,
    DatePicker,
    Dialog,
    Form,
    FormItem,
    Icon,
    Input,
    Loading,
    Notification,
    Message,
    MessageBox,
    Menu,
    MenuItem,
    Submenu,
    Select,
    Option,
    Radio,
    RadioButton,
    RadioGroup,
    Slider,
    Switch,
    Table,
    TableColumn,
    Tabs,
    TabPane,
    Tag,
    TimePicker,
    Tooltip,
    Pagination,
    Popover
} from 'element-ui';

import compCard from './card';
import customElCard from './card/custom-el-card';

const components = [
    Alert,
    Breadcrumb,
    BreadcrumbItem,
    Button,
    Card,
    Checkbox,
    CheckboxGroup,
    Col,
    DatePicker,
    Dialog,
    Form,
    FormItem,
    Icon,
    Input,
    // Message,
    Menu,
    MenuItem,
    Submenu,
    Select,
    Option,
    Radio,
    RadioButton,
    RadioGroup,
    Slider,
    Switch,
    Table,
    TableColumn,
    Tabs,
    TabPane,
    Tag,
    TimePicker,
    Tooltip,
    Pagination,
    Popover,
    customElCard // 自定义通用 card
];

components.forEach((item) => {
    Vue.component(item.name, item);
});

Vue.use(Loading.directive);
Vue.prototype.$loading = Loading.service;

const MsgBox = MessageBox;
Vue.prototype.$msgbox = MsgBox;
Vue.prototype.$alert = MsgBox.alert;
Vue.prototype.$confirm = MsgBox.confirm;
Vue.prototype.$prompt = MsgBox.prompt;

Vue.prototype.$notify = Notification;
Vue.prototype.$message = Message;
```

**Comment by jarrekk** [comment]
找了好久，单独引用notification的时候还需要`Vue.prototype.$notify = Notification;`，希望文档加上，不要才坑了， 而且推荐引用方法为
```
import { Button, Notification, Row, Col, Collapse, CollapseItem } from 'element-ui'
Vue.component(Button.name, Button)
Vue.component(Notification.name, Notification)
Vue.component(Row.name, Row)
Vue.component(Col.name, Col)
Vue.component(CollapseItem.name, CollapseItem)
Vue.component(Collapse.name, Collapse)
Vue.prototype.$notify = Notification
```

使用`Vue.use(Notification)`也会直接弹出提示框

**Comment by li-xiaojun** [comment]
我也遇到这个问题，搞了我好久，都准备用iView了，突然找到这个网页了

**Comment by dreambe** [comment]
给力！找了好久

**Comment by pzjzeason** [comment]
element-ui 坑太多了

**Comment by zhaoyn7** [comment]
坑！

**Comment by MiaPerry** [comment]
真的牛批，md用了use就直接弹弹弹，我也是醉了，终于解决了哈哈哈

**Comment by xingBaGan** [comment]
要不就统一，要不文档写清楚，这么反直觉用户体验极差>_<
