### ISSUE TITLE
tooltips和dialog问题

### ISSUE THREAD

**Issue by QianZhongWang** [ElemeFE/element#20248]
## Element UI version
2.13.0
## OS/Browsers version
mac  Chrome 85.0.4183.121
## vue version
2.6.10
## problem desc
我在表格的元素上同时绑定了tooltip和点击出现弹窗。当我点击元素出现弹窗，这个时候我点击切换浏览器的窗口，再切换回来，这个时候文字提示会悬浮在我的弹窗上

<img width="1345" alt="截屏2020-09-28 上午10 46 07" src="https://user-images.githubusercontent.com/30616554/94387363-81c9f180-017c-11eb-9f9d-1bea4c13d7d7.png">

**Comment by willaer** [comment]
一、找到出现问题的原因：
el-tooltip 组件里的子容器 点击后会有一个`键盘中tab键的选中状态`。在切换浏览器页面时，这个`tab选中状态`是一直保持的。所有我们取消这个`tab选中状态`就行了。

......
好了，知道是什么样的问题后，就很好解决了。

二、解决问题的方法：
以 el-button 组件为例，为el-button添加click事件，方法名buttonClick。

> `<el-button @click="buttonClick">按钮</el-button>> `
> `  `
> `buttonClick(e){`
 > ` // 这里可以执行业务`
 > ` // ...`
 > `       let target = e.target;`
> `        if(target.nodeName == "SPAN"){`
 > `         target = e.target.parentNode;`
> `        }`
> `        target.blur();`
> `      },`

**Comment by QianZhongWang** [comment]
感谢🙏，问题以解决。
