### ISSUE TITLE
[Bug Report] When I use a form in a drawer, the select selector drop-down box is misshapen, and the first element of the form is automatically focused. (在抽屉中使用表单时，select 选择器 下拉框样式错乱，而且表单第一个元素会自动聚焦。)

### ISSUE THREAD

**Issue by Ever12349** [ElemeFE/element#20249]
### Element UI version
2.13.2

### OS/Browsers version
windows10 1909 / Google Chrome 85.0.4183.121

### Vue version
2.6.11

### Reproduction Link
https://ever12349.github.io/elementDemo/

### Steps to reproduce
Source code address  https://github.com/Ever12349/elementDemo   Project demo  https://ever12349.github.io/elementDemo/

Click the button to open the drawer.

源代码地址 : https://github.com/Ever12349/elementDemo   项目demo  https://ever12349.github.io/elementDemo/
 
点击按钮 打开抽屉。

### What is Expected?
Click the button and the drawer opens normally. I don't want the form elements to focus automatically. 

(点击按钮，抽屉正常打开，我不希望表单元素会自动聚焦。)

### What is actually happening?
Click the button, the drawer opens normally, and then the first element of the form is focused. When the first element of the form is a select selector, the position of its drop-down box will be disordered. 

(点击按钮，抽屉正常打开，然后表单第一个元素聚焦，当表单第一个元素是select选择器时，它的下拉框的位置会错乱。)

**Comment by willaer** [comment]
一、找到出现问题的原因：
el-drawer 组件弹出后，会自动识别 tabindex 比 el-drawer 高1级的子内容，进行‘’tab选择‘’(对按钮、选择框和输入框而言也就是聚焦)。
如果没有设置 tabindex 的子内容会自动识别子内容中 第一个 可进行‘’tab选择‘’(对按钮、选择框和输入框而言也就是聚焦)的子内容。

......
好了，知道是什么样的问题后，就很好解决了。

二、解决问题的方法：
方法1：
先在 el-drawer 组件中加入 tabindex="0" 的属性，然后在 el-form 前加一个空的span标签加入tabindex="1"属性， <span tabindex="1"></span>。

方法2：
在组件 el-drawer 中加入@open事件，open方法中加入异步取消 第一个 可聚焦的DOM。
setTimeout(() => {
   this.$refs.xxx.blur();
}, 0);
注意：千万要加 setTimeout。

**Comment by cs1707** [comment]
Duplicate of #19902
