### ISSUE TITLE
Message 消息提示组件多次展示后不能正常消失问题

### ISSUE THREAD

**Issue by gitWhatever** [ElemeFE/element#2025]
### ElementUI version
1.0.8

### OS/Browers version
macOS/Chrome 53 

### Vue version
2.0.8

#### 同一页面中，Message 消息提示第二次展示就不会消失了，并且永远存在，并且关闭icon点击无反应，情况同样出现在Notification 通知中
![2016-12-27 7 04 55](https://cloud.githubusercontent.com/assets/10512369/21498561/9783a158-cc68-11e6-80d9-65855b7632f7.png)

**Comment by Leopoldthecoder** [comment]
请提供 demo。

**Comment by gitWhatever** [comment]
问题原因找到了，使用时缓存了配置对象，传入的配置对象在第一次使用后被vue转为了 getter/setter，导致第二次传入使用时出现了问题。问题可以closed。
