### ISSUE TITLE
這個2.0為主的還會維護嗎?

### ISSUE THREAD

**Issue by branson-aubix** [ElemeFE/element#20263]
如題
看了更新日誌
上一次維護是5月的時候
請問還有人維護或更新這庫嗎
謝謝

**Comment by ruiaHuang** [comment]
我也想问这个问题，好久都没有更新了，是不是后面不会继续维护了···

**Comment by zazzaz** [comment]
If you like to upgrade to Vue3, simply check Element Plus for Vue 3.0 here https://github.com/ElemeFE/element/issues/20061

**Comment by zhouzhongyuan** [comment]
Still under maintenance.
