### ISSUE TITLE
[table]建议增加row-hover事件

### ISSUE THREAD

**Issue by wucuida** [ElemeFE/element#2028]
### ElementUI version
1.0.0-rc.2 

### OS/Browers version
Chrome 53 

### Vue version
 2.0.0

### What is Expected?
建议增加table对row-hover事件的监听

**Comment by jikkai** [comment]
冒昧地问一下是什么样的场景需要监听列表行的hover事件？

**Comment by wucuida** [comment]
1、我在鼠标滑过某行数据时，我想让此行前面出现一个checkbox,而平时展现时这个checkbox是不显示的。索引想监听一下整行的鼠标滑过。
2、现在全部显示checkbox的table时，我在此table监听select和row-click，点击checkbox时会先执行两遍row-click的执行函数，然后再执行select的执行函数，我不知道这是我使用方法有误还是bug。

**Comment by jikkai** [comment]
@wucuida 
1. 看上去可以用css实现
2. 升级到最新版本试试？

**Comment by owlran** [comment]
Is there any update about row-hover ?
