### ISSUE TITLE
建议 table 增加 table-hover

### ISSUE THREAD

**Issue by amin168** [ElemeFE/element#203]
v1.0.0-rc.5

现在这个版本的table每一行都没有鼠标悬停，建议增加

**Comment by Leopoldthecoder** [comment]
@fishpaw 这个是不是考虑一下？
我个人感觉，不同用户需要的 hover 效果可能差别比较大，似乎不太好提供一个通用的方案。目前如果需要 hover 效果，用户是可以自己添加的。

**Comment by fishpaw** [comment]
@amin168 @Leopoldthecoder ，嗯，hover 效果是得有，就提供一个最基本的 hover 样式就好了。如果用户有进一步的需求，再自己修改就好了。
