### ISSUE TITLE
from表单怎么远程验证？

### ISSUE THREAD

**Issue by accaolei** [ElemeFE/element#2030]
比如创建用户时，验证用户名是否已存在？

**Comment by kopheece** [comment]
自己定义个validator，在里面去做校验。大体如下：
![image](https://cloud.githubusercontent.com/assets/23140033/21502245/775c8fa4-cc89-11e6-9e6d-8e6cafa08802.png)

**Comment by accaolei** [comment]
多谢! @kopheece

**Comment by Whalefallsea** [comment]
我也是这样子做的，但是这样有个问题就是由于那个验证用户名是否已存在是ajax异步的，所以在点击按钮提交时不管用户是否存在都会验证通过
`this.$refs.registerFrom.validate(valid => {
        console.log(valid)
.......`
valid的值为true，即便用户存在。
