### ISSUE TITLE
[Bug Report] 官网地址无法访问——404

### ISSUE THREAD

**Issue by h7ml** [ElemeFE/element#20317]
### Element UI version
2.13.2

### OS/Browsers version
windows

### Vue version
3.0.2

### Reproduction Link
https://github.com/kkbjs/element3

### Steps to reproduce
打开https://element3. vercel .app/ 即可

### What is Expected?
正常访问

### What is actually happening?
404

**Comment by iamkun** [comment]
老哥你是被人骗了吧 https://element.eleme.cn/ 这个才是官网
