### ISSUE TITLE
[Bug Report] 全局修改TableColumn showOverflowTooltip属性无效

### ISSUE THREAD

**Issue by xiuxiuing** [ElemeFE/element#20328]
### Element UI version
2.13.2

### OS/Browsers version
Mac/Chrome

### Vue version
2.6.12

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
在main.js中全局修改TableColumn的属性showOverflowTooltip为true
```
import ElementUI, { Message } from 'element-ui'
//全局修改element默认配置
ElementUI.TableColumn.props.showOverflowTooltip.default=true;
ElementUI.TableColumn.props.minWidth.default='50';
console.log(ElementUI.TableColumn)
Vue.use(ElementUI)
```

### What is Expected?
期望在Table中某列数据过多时显示...，鼠标移动到cell时，展示Tooltip显示内容

### What is actually happening?
实际在Table中某列数据过多时显示...，但是鼠标移动到cell时，不会展示Tooltip

**Comment by hollyyu** [comment]
ElementUI.TableColumn.props.showOverflowTooltip ={type:Boolean, default: true};

**Comment by xiuxiuing** [comment]
> ElementUI.TableColumn.props.showOverflowTooltip ={type:Boolean, default: true};

You are Right，Thank you
