### ISSUE TITLE
制定新主题

### ISSUE THREAD

**Issue by liujinyang1994** [ElemeFE/element#2032]
看了一下theme-ui的自定义主题部分，发现可指定的程度并不是很高，我想知道，除了修改源码外，还有什么方法可以高度自定义

**Comment by QingWei-Li** [comment]
变量全都放出来了还说可定制度不高？

**Comment by wanghaolu** [comment]
@QingWei-Li 发几个官方主题吧

**Comment by jikkai** [comment]
我的个人建议是应该先把组件功能维护好，这个可能才是大家迫切需要的。定制化的主题完全可以交给社区。多套主题会提升维护成本，设计资源也不是随叫随到的，而且这个众口难调的东西现有的定制方案（element-theme）可以做到基本满足定制需求，如果有特殊需求的话样式本身也可以被覆盖（注意下不要被scoped坑了即可）

这里推荐下收录在(awesome-element的文章)[https://github.com/ElementUI/awesome-element#articles]《element-theme-default syntax analysis》

**Comment by QingWei-Li** [comment]
同意 @jikkai 的说法。
根本没精力去做，只能靠社区来实现。

**Comment by liujinyang1994** [comment]
@QingWei-Li  如果说变量都放出来了，我想问一下仅仅Card一个小组件的能否通过变量彻底重新制定。我只是来请教方法，说话攻击性不要那么强。我对饿了么的前端团队的肯定程度是存在的，不然不会使用这套组件库

**Comment by liujinyang1994** [comment]
@jikkai 谢谢你诚恳的回复。
