### ISSUE TITLE
[Bug Report] Image组件报错而且fixed有穿透的问题

### ISSUE THREAD

**Issue by liqin1059** [ElemeFE/element#20334]
### Element UI version
2.13.2

### OS/Browsers version
windows64

### Vue version
2.6.11

### Reproduction Link
https://github.com/ElemeFE/element/issues/new

### Steps to reproduce
vue.esm.js?c0a4:628 [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

found in

---> <ElImageViewer> at packages/image/src/image-viewer.vue

### What is Expected?

      <div class="el-image-viewer__canvas">
        <img
          v-for="(url, i) in urlList"
          v-if="i === index"
          ref="img"
          class="el-image-viewer__img"
          :key="url"
          :src="currentImg"
          :style="imgStyle"
          @load="handleImgLoad"
          @error="handleImgError"
          @mousedown="handleMouseDown">

### What is actually happening?
key改一下

**Comment by cs1707** [comment]
The URL should be unique
