### ISSUE TITLE
[Feature Request] select组件，能不能搞个无限滚动的功能

### ISSUE THREAD

**Issue by xiaoqingb** [ElemeFE/element#20333]
Existing Component
是

Component Name
el-select

Description
需求：

我渲染出来的内容有上百上千个，太多DOM了，能不能搞个无限滚动，就固定显示那几个dom就行了

**Comment by elewen** [comment]
+1

**Comment by zhouzhongyuan** [comment]
For the situation of more than thousands items，I don't recommend you use the `el-select` component.
