### ISSUE TITLE
如果我现在需要集成element到nuxt，我该如何操作呢？

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/element#2034]
如果我现在需要集成element到nuxt，我该如何操作呢？

**Comment by jikkai** [comment]
目前不支持SSR，so……等待1.1.0版本发布，详见#1942

> SSR
> 1.1.0 版本将支持 SSR，届时推荐使用 nuxt 体验。

**Comment by yuchonghua** [comment]
但是1.1.0有点久，那另外方便问下 [mint-ui SSR](https://github.com/ElemeFE/mint-ui/issues/548) 什么时候支持吗

**Comment by HadiChen** [comment]
@jikkai 那  mint-ui SSR 呢

**Comment by Leopoldthecoder** [comment]
Mint UI 不支持 SSR，并且近期没有计划做支持。
Element 1.1 不会太久了。

**Comment by yuchonghua** [comment]
为什么Mint UI 不支持 SSR，如果我需要在nuxt.js中使用，我该如何集成呢？
如果我管理后台一个域名，手机版一个域名，那不是很奇怪吗

**Comment by yuchonghua** [comment]
1.1该如何集成nuxt呢
