### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mahmoudmy** [ElemeFE/element#2037]
Thanks guys, 
That's a really nice project.
Do you have any plan for *RTL* support in css? (for languages like Persian, Arabic, ...)

**Comment by Leopoldthecoder** [comment]
Thanks. 
We don't have plans to add RTL support, but there may be some third party libraries you can use with Element, like [rtlcss](https://github.com/MohammadYounes/rtlcss).

**Comment by MahdiMajidzadeh** [comment]
no plan to add rtl with contribution neither ??

**Comment by osman-mohamad** [comment]
do you have any guides about using element-ui with rtlcss ?

**Comment by KayvanMazaheri** [comment]
Has anyone find a solution for using _Element_ with RTL languages? Any suggestions would be appreciated.
@mahmoudmy @MahdiMajidzadeh @osman-mohamad

**Comment by osman-mohamad** [comment]
@KayvanMazaheri I did found a solution . you can use postcss-loader in your project with postcss `rtlcss` plugin . and it will convert all the styles to rtl .
plus :
```css
body,html {
   direction: ltr
}
``` 
in the App.vue Component style

**Comment by siavash-sajjad** [comment]
@osman-mohamad 
hi my friend
can you help me to add and usage rtlclass to laravel-vue project?

**Comment by osman-mohamad** [comment]
@siavash-sajjad put the repository url here . for me to review it .

**Comment by kooshkestani** [comment]
@Leopoldthecoder hi tree element not support rtl .
how to customize  tree-node.vue 
`      :style="{ 'padding-left': (node.level - 1) * tree.indent + 'px' }">
`to padding-right???

**Comment by moosti** [comment]
+1

**Comment by ghyath5** [comment]
How can I use rtlcss in my nuxtjs project ?
and did you find another way to support RTL in element?

**Comment by kooshkestani** [comment]
https://www.npmjs.com/package/tree-element-ui-rtl

**Comment by saeed-darestany** [comment]
+1

**Comment by hitautodestruct** [comment]
+1

**Comment by realSaeedHassani** [comment]
@Leopoldthecoder  Still have no plans for RTL support?

**Comment by mra-dev** [comment]
It would be so good if had it.

**Comment by mahsamirzapour** [comment]
> Thanks guys, That's a really nice project. Do you have any plan for _RTL_ support in css? (for languages like Persian, Arabic, ...)

Hi homie, just use like this:
html {
direction: rtl;
}
[class*='el-col-'] {
  float: right;
}

**Comment by kriem2000** [comment]
As I saw that the `rtlcss` plugin solved the problem, but not in my application case where i use both rtl and ltr directions so the rtlcss is always converts the styles into rtl regardless of the html dir value, any solution for this issue?

here's my vite.config.js file:

```
import { fileURLToPath, URL } from 'node:url';
import rtlcss from 'rtlcss';
import { defineConfig } from 'vite';
import AutoImport from 'unplugin-auto-import/vite';
import Components from 'unplugin-vue-components/vite';
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers';
import vue from '@vitejs/plugin-vue';
import tailwindcss from 'tailwindcss';


export default defineConfig({
  css: {
    postcss: {
      plugins: [
        rtlcss,
        tailwindcss,
      ],
    },
  },
  plugins: [
    vue(),
    AutoImport({
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      resolvers: [ElementPlusResolver()],
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
});
```
