### ISSUE TITLE
我不明白你们为什么把select remote的时候的向下箭头给隐藏，为了保持识别度，你们也不加个补回的选项，是不是在产品设计上你们也这么专横！

### ISSUE THREAD

**Issue by liedezhangqiu** [ElemeFE/element#20383]

**Comment by maicWorkGithub** [comment]
自己修改一下提个PR啊，这个东西你付费了吗，搞得跟自己是上帝，别人需要为你服务一样

**Comment by liedezhangqiu** [comment]
顾客可不就是上帝，无论是否付费，没有做好服务的打算您干脆就不要做产品了！

**Comment by liedezhangqiu** [comment]
<i class="el-select__caret el-input__icon el-icon-arrow-up"></i>   正确
<i class="el-select__caret el-input__icon el-icon-"></i>    错误

这界面元素渲染肯定是有问题的

**Comment by 9-lives** [comment]
你好，element+ 项目欢迎提 pr.

**Comment by QiZZ121** [comment]
提Issue连规范都不遵守

**Comment by maicWorkGithub** [comment]
无能狂怒，你自己写一个库自己用啊。你叫唤了半天，不还是得忍着？自己又不会改，改了又不会提PR。

@iamkun 黑名单一个

**Comment by shaonianla1997** [comment]
没满足你的需要就成专横了？那以后做开源的如果不想被喷是不是都得找你提需求。少一点抱怨和戾气，没人欠你什么，有时间发牢骚不如看看怎么自己动手实现。

**Comment by xiaowangsmile** [comment]
我怀疑楼主被领导熊了 要不不会这样

**Comment by xlz26296** [comment]
这种垃圾无非就是刷存在感，没必要理会，element 作为 vue 最好的开源组件库之一，本身也在不断完善，又没收你钱，就因为满足不了你需求就在到处乱喷；什么玩意还服务，还让开源项目为你服务，你面子真大，这么叼咋不上天，有本事就自己去写一个

**Comment by heromen** [comment]
@xlz26296 说的真好

**Comment by chunyi-gao** [comment]
你描述现象就可以了，何必掺杂一堆你最恶毒的揣测。
我是实在讨厌你这种人。

**Comment by chengxuzhang** [comment]
可以通过修改样式加上，但是如果加上了清除属性，那个清除图标就不显示了
