### ISSUE TITLE
如何不刷新浏览器切换组件语言

### ISSUE THREAD

**Issue by flybears** [ElemeFE/element#2039]
切换语言时，如何不刷新浏览器动态的切换组件的国家化语言？....聊天室里面问了，没有找到解决的办法，所以到这里来问问，求解决....

**Comment by QingWei-Li** [comment]
官网的例子就已经是满足你的需求了的，如果自己使用上有问题，请提供代码或者项目仓库地址

**Comment by flybears** [comment]
@QingWei-Li 我写了个点击事件...vue的国际化切换过来了...但是element的没有...
handleClick (value) {
        Vue.config.lang = value
        if(value == "en"){
          locale.use(lang)
        }
      }
或者是这种
handleClick (value) {
        Vue.config.lang = value
        if(value == "en"){
          Vue.use(ElementUI, { locale })
        }
      }

都不行....

**Comment by fb783303646** [comment]
官网上国际化问题  怎么模板中使用好像没有 希望可以出一个小白版的案例！最好 可以出一个小案例！给小白使用！（还有一个就是用了你们组件 你们的组件国际化了，用了你们的语言包，我们还想用我们自己的语言包，这两个包怎么整合在一起，或者怎么用自己的语言包）
