### ISSUE TITLE
是否有方法获取该表格所有列？

### ISSUE THREAD

**Issue by suyana** [ElemeFE/element#20392]
el-table的列信息是直接代码写死的。
但用js导出表格时，需要提供列信息。
现有方法要么是用v-for渲染列，要么是2边都要维护，
有没有方法取出table现有列？（PS：不大想用v-for渲染列，有些列需要个性化设置）

**Comment by zhouzhongyuan** [comment]
It's NOT an issue of Element. It is related to JavaScript.
