### ISSUE TITLE
DatePicker的一个计算属性名与最新版本vue 2.1.8 属性名冲突

### ISSUE THREAD

**Issue by wendysun0315** [ElemeFE/element#2040]
DatePicker的一个计算属性名与最新版本vue 2.1.8 属性名冲突
报错如下:
vue.common.js?d589:521 [Vue warn]: existing instance property "haveTrigger" will be overwritten by a computed property with the same name. 
(found in component <ElDatePicker>)

**Comment by QingWei-Li** [comment]
是你自己有一个 haveTrigger 属性吧，你用黑魔法写的？ Vue 内部的属性或方法一定是 `&` 或 `_` 开始的

**Comment by storkyeh** [comment]
我也遇到警告了，Vue2.1.8，警告如下:

![image](https://cloud.githubusercontent.com/assets/3207354/21517299/f117e426-cd18-11e6-813e-4315e1b55e6d.png)

![image](https://cloud.githubusercontent.com/assets/3207354/21517328/2f545026-cd19-11e6-8bf8-e46b5c334cc4.png)

**Comment by storkyeh** [comment]
@QingWei-Li  

[https://jsfiddle.net/mpaczw1L/](https://jsfiddle.net/mpaczw1L/)

![image](https://cloud.githubusercontent.com/assets/3207354/21518024/7f7c7902-cd1e-11e6-872d-dc14be7f3896.png)

**Comment by QingWei-Li** [comment]
@storkyeh 对 已经发现了，正在排查

**Comment by leftstick** [comment]
Good to know.
