### ISSUE TITLE
Progress 进度条 :width 属性不能使用变量

### ISSUE THREAD

**Issue by qihua-1996** [ElemeFE/element#20416]

**Comment by qihua-1996** [comment]
![image](https://user-images.githubusercontent.com/65535620/98628704-26317d00-2352-11eb-9065-d9dd282bc632.png)
会报错这个错误，但是可以正常使用

**Comment by zhan9rq** [comment]
兄弟 报错明显说你这个变量的值不是number类型啊😶

**Comment by qihua-1996** [comment]
我用的就是number类型，你自己试试就知道了，不能写变量，只能写固定数字

**Comment by qihua-1996** [comment]
> 兄弟 报错明显说你这个变量的值不是number类型啊😶
我用的就是number类型，你自己试试就知道了，不能写变量，只能写固定数字

**Comment by qihua-1996** [comment]
> 兄弟 报错明显说你这个变量的值不是number类型啊😶
