### ISSUE TITLE
[Bug Report] when browser hidden/blur , the actived tab still has a strange box shadow

### ISSUE THREAD

**Issue by wmo123** [ElemeFE/element#20433]
### Element UI version
0.1.0

### OS/Browsers version
macOS10.14.6/86.0.4240.193（正式版本） (x86_64)

### Vue version
2.6.10

### Reproduction Link
https://github.com/ElemeFE/element/issues/9981

### Steps to reproduce
1. 打开element官网，切换版本为2.12.0；
2. 找到Tabs标签页组件；
3.选择任意demo，触发el-tab切换，使浏览器失焦或被隐藏；
4.浏览器再次获取焦点，选中的tab出现box-shadow；
5. 切回element为最新版本（2.14.0），重复上述步骤，仍然会出现此现象；

### What is Expected?
浏览器再次获取焦点时，当前选中的tab没有奇怪的样式

### What is actually happening?
浏览器再次获取焦点时，当前选中的tab出现box-shadow

**Comment by JinPengGeng** [comment]
这个是伪元素选择器样式问题，可以自定义覆盖

**Comment by wmo123** [comment]
@JinPengGeng 谢谢回复，我好像没办法在控制台追踪这个样式，因为切回浏览器后，一旦获取焦点，样式就消失了，请问您有什么调试方法吗？

**Comment by wmo123** [comment]
@JinPengGeng 谢谢回复，找到这个样式了。
![image](https://user-images.githubusercontent.com/47963460/99022861-6127f080-259e-11eb-9d65-3624d26d7f70.png)
