### ISSUE TITLE
多选select在表单中，带标签时错位

### ISSUE THREAD

**Issue by AnzerWall** [ElemeFE/element#2044]
如题！

### ElementUI version
1.0.8

### OS/Browers version
Windows 10/Chrome 54.0.2840.71 m

### Vue version
2.1.0

### Reproduction Link
http://codepen.io/anzerwall/pen/WoqPzP

**Comment by Leopoldthecoder** [comment]
如果需要 label 单独显示一行，那么需要在 `el-form` 上加 `label-position="top"`。

**Comment by cmlily8294** [comment]
http://jsfiddle.net/gis_cl/0qxget9h/
我复现了,给select加了宽度……
![image](https://cloud.githubusercontent.com/assets/10285991/21606304/6fdf19e4-d1e9-11e6-9525-c15c7810f7bf.png)
