### ISSUE TITLE
CDN直接引用会有问题！

### ISSUE THREAD

**Issue by WzSepia** [ElemeFE/element#20459]
使用官网提供的CND使用方式：
目前可以通过 unpkg.com/element-plus 获取到最新版本的资源，在页面上引入 js 和 css 文件即可开始使用。
引入样式：
\<link  rel="stylesheet" href="https://unpkg.com/element-plus/lib/theme-chalk/index.css">
引入组件库:
<script src="https://unpkg.com/element-plus/lib/index.js"></script>

与Vue3.0.2版本结合使用；

无法正常展示：

vue@3.0.2:1235 [Vue warn]: Failed to resolve component: el-button 
  at <App>
warn @ vue@3.0.2:1235
vue@3.0.2:1235 [Vue warn]: Failed to resolve component: el-dialog 
  at <App>
warn @ vue@3.0.2:1235
DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/mitt/dist/mitt.es.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://ElementPlus/node_modules/async-validator/dist-web/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by WzSepia** [comment]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport">
		<title></title>
		<link rel="stylesheet" type="text/css" href="https://unpkg.com/element-plus/lib/theme-chalk/index.css">
	</head>
	<body>

		<div id="app">
			<el-button type="primary" @click="visible = true">Button</el-button>
			<el-dialog :visible.sync="visible" title="Hello world">
				<p>Try Element</p>
			</el-dialog>
		</div>

		<script type="text/javascript" src="https://unpkg.com/vue@3.0.2"></script>
		<script type="text/javascript" src="https://unpkg.com/element-plus/lib/index.js"></script>
		<script type="text/javascript">
			var app = Vue.createApp({
				data: function() {
					return {
						visible: false
					}
				}
			});
			app.mount("#app");
		</script>
	</body>
</html>

**Comment by iamkun** [comment]
Hi, you can check the CDN demo code here https://element-plus.org/#/en-US/component/installation

Note, please submit the issue on Element Plus project https://github.com/element-plus/element-plus/issues/new, so that we can reach you faster.

**Comment by coderhsw** [comment]
你好，请问解决了吗
