### ISSUE TITLE
[Bug Report] 官网主题下载压缩包无法解压

### ISSUE THREAD

**Issue by georgezouq** [ElemeFE/element#20478]
### Element UI version
2.14.1

### OS/Browsers version
OSX

### Vue version
2.6.12

### Reproduction Link
https://element.eleme.io/#/en-US/theme

### Steps to reproduce
在官网 -> 主题 -> Download 下载压缩包后，提示压缩包已损毁 无法解压，提示：Error 79 - 不适当的文件类型或格式。

### What is Expected?
可以解压

### What is actually happening?
无法解压

**Comment by georgezouq** [comment]
相似的 Issues #19877

**Comment by 3344567** [comment]
不知道你做了什么操作,我是成功解压了

**Comment by georgezouq** [comment]
@3344567  是mac吗？

**Comment by 3344567** [comment]
win10

**Comment by georgezouq** [comment]
@3344567 我在mac上没法解压

**Comment by 3344567** [comment]
很明显,你的解压软件的问题

**Comment by georgezouq** [comment]
@3344567 mac 自带的解压软件，解压其他的zip包都没问题

**Comment by 3344567** [comment]
碰到这种问题你该思考下吧.win能打开,说明数据没问题,那就只能是你解压软件的问题了.怎么说也是个开发吧

**Comment by georgezouq** [comment]
@3344567 你没看到我引用的两个issues？？ 随便一找就有两个人出现同样问题。找什么自己问题，这个就是无法在mac上解压啊。换软件是最佳解决方案？我用的mac官方的解压工具，你让所有用户都换软件？？

**Comment by georgezouq** [comment]
@3344567 为什么我能解压几乎所有网站下载的zip压缩包 就不能解压这个？ 难道不是这个压缩包出了问题？？

**Comment by georgezouq** [comment]
@3344567 这个功能有问题就要承认问题 想办法解决问题 而不是逃避问题

**Comment by KevenNock** [comment]
人家说的对。肯定不是解压软件问题。只能说你的压缩包兼容性没做好。mac自带的解不开。能说个啥。
