### ISSUE TITLE
新版本按需加载table-culumn解析不出来，没报错

### ISSUE THREAD

**Issue by Ucdit** [ElemeFE/element#20477]
<template>
  <div style="width: 100%;height: 100%;">
    <el-table
      :data="tableData"
      style="width: 100%">
      <el-table-column
        prop="date"
        label="日期"
        width="180">
      </el-table-column>
      <el-table-column
        prop="name"
        label="姓名"
        width="180">
      </el-table-column>
      <el-table-column
        prop="address"
        label="地址">
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
import { Table, TableColumn } from 'element-ui';
import 'element-ui/lib/theme-chalk/table.css'
import 'element-ui/lib/theme-chalk/table-column.css'

export default {
  name: "bm-mtv-table",
  props:{
    
  },
  data () {
    return {
        test: true,
        tableData: [{
            date: '2016-05-02',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1518 弄'
          }, {
            date: '2016-05-04',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1517 弄'
          }, {
            date: '2016-05-01',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1519 弄'
          }, {
            date: '2016-05-03',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1516 弄'
          }]
    }
  },
  components: {
    [Table.name]: Table,
    [TableColumn.name]: TableColumn,
  },
  methods: {
    
  },
}
</script>

**Comment by TY-LIU** [comment]
使用模板提问啊淦！代码也不格式化，就算天王老子来了你这BUG都不会给你修

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.
