### ISSUE TITLE
[Bug Report] Tooltip和MessageBox配合使用异常

### ISSUE THREAD

**Issue by hqzh** [ElemeFE/element#20491]
### Element UI version
2.14.1

### OS/Browsers version
windows10/chrome 版本 87.0.4280.66（正式版本） （64 位）

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/hqzh/pen/GRjRywO

### Steps to reproduce
1、点击打开 Message Box 
2、关闭或取消 Message Box 后Tooltip被自动激活了

### What is Expected?
Tooltip不应该自动激活了

### What is actually happening?
Tooltip自动激活了

**Comment by hqzh** [comment]
机器人都关了。。。加了一个key处理了

**Comment by nolandcheng** [comment]
@hqzh 想请问下具体怎么解决的呢？我加key没有效果
