### ISSUE TITLE
[Bug Report]使用跑马灯组件配合el-image组件的查看大图无法全屏

### ISSUE THREAD

**Issue by HadiChen** [ElemeFE/element#20492]
Element UI version
2.14.1

OS/Browsers version
win10/Google Chrome 86.0.4240.183

Vue version
2.6.10

Reproduction Link
https://codepen.io/hadichen/pen/BaLaYwb

Steps to reproduce
点击图片，弹出打开大图弹窗，弹窗大小被限制于el-carousel-item的大小

What is Expected?
查看大图可以正常全屏，或查看大图可以独立出来组件

What is actually happening？
查看大图弹窗的固定定位属性受到了el-carousel-item的transform属性影响，无法实现全屏

**Comment by Haji0** [comment]
也许你可以尝试着 设置这个属性

` 
.el-carousel__item.is-animating{
    transform: none!important;
  }
`

**Comment by cs1707** [comment]
Duplicate of #19330
