### ISSUE TITLE
date-picker 组件出现两个清除按钮

### ISSUE THREAD

**Issue by 1014156094** [ElemeFE/element#20495]
![image](https://user-images.githubusercontent.com/16074662/100495881-9e89a200-318a-11eb-88d0-1be63781baad.png)
![image](https://user-images.githubusercontent.com/16074662/100495889-ad705480-318a-11eb-9eaa-f6f501dbc4b7.png)
element-ui 版本：v2.14.1

**Comment by s0ngyee** [comment]
你好，能否提供一个能复现的在线demo地址

**Comment by 1014156094** [comment]
我排查了下，是 input 的 clearable 全局设置为 true 导致的，因为 date-picker 本来就有 clearable 了，我现在把 date-picker 的 clearable 隐藏就行。
![image](https://user-images.githubusercontent.com/16074662/103723096-4016d580-500c-11eb-912f-4cc0fae819f1.png)
