### ISSUE TITLE
[Bug Report] 新版本按需加载table-culumn解析不出来，没报错

### ISSUE THREAD

**Issue by Ucdit** [ElemeFE/element#20498]
### Element UI version
2.14.1

### OS/Browsers version
mac/chrome最新版

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/Ucdit/pen/RwGNGRr?editors=1010

### Steps to reproduce
按需加载时最新版本的element-ui，TableColumn渲染不出来

### What is Expected?
按需加载引入时，TableColumn组件能被正常渲染

### What is actually happening?
按需加载引入时，TableColumn组件没被渲染

**Comment by cs1707** [comment]
控制台里面有些报错，建议修复这些错误之后再做尝试。
![image](https://user-images.githubusercontent.com/5404420/102754941-ac58ce80-43a8-11eb-9c31-a445eaf53318.png)
