### ISSUE TITLE
[Bug Report] Drawer 抽屉在某些电脑上卡顿

### ISSUE THREAD

**Issue by jing16hou** [ElemeFE/element#20502]
### Element UI version
2.14.1

### OS/Browsers version
macOS High Sierra  版本10.13.6 /Chrome

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
点击弹窗，打开和关闭时有明显卡顿

### What is Expected?
不卡顿

### What is actually happening?
不卡顿

**Comment by s0ngyee** [comment]
复现链接无效
