### ISSUE TITLE
This relative module was not found:

### ISSUE THREAD

**Issue by amit2k18** [ElemeFE/element#20506]
Getting error while building after integrating Element-Ui with Vue-Typescript application.
ERROR  Failed to compile with 1 errors                                                                                                         

This relative module was not found:
* ./src/normalizeWheel.js in ./node_modules/normalize-wheel/index.js
No type errors found
Version: typescript 3.8.3
Time: 8936ms

**Comment by zhouzhongyuan** [comment]
It is not a problem about ElementUI，it's probably related to your development environment.
