### ISSUE TITLE
el table 再同时使用fixed固定左侧列和合计时横向的滚动条会无效

### ISSUE THREAD

**Issue by GdmnKomo** [ElemeFE/element#20515]
el table 再同时使用fixed固定左侧列和合计时横向的滚动条会无效,前面固定部分的下面的滚动条无法选中和拖动
![image](https://user-images.githubusercontent.com/62534420/100832702-5bd60b80-34a3-11eb-97f5-2401293de1f0.png)

**Comment by thyhates** [comment]
我是通过为类 `el-table__body-wrapper` 添加 `z-index`样式解决的，设置为2就好，目前没发现问题。

**Comment by GdmnKomo** [comment]
@thyhates 谢谢,完美解决了,万分感谢╰(￣▽￣)╮

**Comment by aizhiwei-tal** [comment]
::v-deep .el-table__body-wrapper {
  z-index: 2!important;
}   是这样吗？ 还是不行啊 @thyhates

**Comment by thyhates** [comment]
> ::v-deep .el-table__body-wrapper { z-index: 2!important; } 是这样吗？ 还是不行啊 [@thyhates](https://github.com/thyhates)

我是直接设置的全局样式
```css
.el-table__body-wrapper {
    z-index: 2;
}
```
element版本是2.14.1
然后控制台查看`el-table__body-wrapper ` 类的 `z-index` 属性是否生效，可能被覆盖。
@aizhiwei-tal
