### ISSUE TITLE
[Bug Report] el-tree 在父节点收缩状态下，使用setCheckedKeys选中子节点，无法触发check-change事件

### ISSUE THREAD

**Issue by mf717714** [ElemeFE/element#20520]
### Element UI version
2.14.1

### OS/Browsers version
谷歌

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/mf717714/pen/eYdpGxO

### Steps to reproduce
1，首次在树节点未展开的情况下（即选中的子节点处于未渲染），使用setCheckedKeys()选中子节点，无法触发check-change事件获取子节点的信息
2，如果使用延时，即先展开节点，再进行setCheckedKeys()选中，就可以触发check-change事件获取子节点的信息

### What is Expected?
1，树节点过多，不可能把全部节点先展开，再进行选中。
2，期待不需要展开就可以选中，并且可以触发check-change事件获取子节点的信息

### What is actually happening?
首次在树节点未展开的情况下（即选中的子节点处于未渲染），使用setCheckedKeys()选中子节点，无法触发check-change事件获取子节点的信息

**Comment by ViavaCos** [comment]
为什么要获取子节点信息呢？
感觉没有必要，因为像多级城市选择这样的情况下，你选择父级之后，展开子级也会根据父级的状态去计算子级的状态。

**Comment by 3344567** [comment]
所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息

**Comment by mf717714** [comment]
> @mf717714
> 为什么要获取子节点信息呢？
> 感觉没有必要，因为像多级城市选择这样的情况下，你选择父级之后，展开子级也会根据父级的状态去计算子级的状态。

父子不相关的情况下，回显子节点

**Comment by mf717714** [comment]
> 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息

不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点

**Comment by 3344567** [comment]
> > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> 
> 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点

如果用户只选择了最深层次的节点呢?该怎么显示?

**Comment by ViavaCos** [comment]
> 
> 
> > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> 
> 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点

但是，之所以要使用树形结构正是因为叶子节点和上级存在关联的吧（我的理解..）

**Comment by 3344567** [comment]
> > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> 
> 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点

父子不相关?那叫树?

**Comment by mf717714** [comment]
> > > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> > 
> > 
> > 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点
> 
> 如果用户只选择了最深层次的节点呢?该怎么显示?
现在就是这个问题，你可以看看我那个demo链接

**Comment by mf717714** [comment]
> > > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> > 
> > 
> > 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点
> 
> 但是，之所以要使用树形结构正是因为叶子节点和上级存在关联的吧（我的理解..）

element-ui的树形组件有这个check-strictly（在显示复选框的情况下，是否严格的遵循父子不互相关联的做法）

**Comment by 3344567** [comment]
> > > > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> > > 
> > > 
> > > 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点
> > 
> > 
> > 如果用户只选择了最深层次的节点呢?该怎么显示?
> > 现在就是这个问题，你可以看看我那个demo链接

现在就是这个问题?我是让你描述你的需求

**Comment by mf717714** [comment]
> > > > > 所以在这种情况下,你完全可以通过递归去先完成获取子节点的信息
> > > > 
> > > > 
> > > > 不是要获取子节点信息，是父子不相关的情况下，回显展示已选择的子节点
> > > 
> > > 
> > > 如果用户只选择了最深层次的节点呢?该怎么显示?
> > > 现在就是这个问题，你可以看看我那个demo链接
> 
> 现在就是这个问题?我是让你描述你的需求

注：父页面（table页面），子页面（树页面）
1，从父页面点击一行数据，根据id，在子页面回显树节点（但无法触最深一级change事件，父节点可以触发），并获取已选择的节点信息
2，你可以看下我的demo，查看console输出信息就明白了，点击**未设置延时按钮**只有一条输出信息，刷新页面，点击**延时状态按钮**你会发现输出两个信息

**Comment by 3344567** [comment]
> 如果用户只选择了最深层次的节点呢?该怎么显示

所以我问你如果用户只选择了最深层次的节点呢?该怎么显示

**Comment by VINOlive** [comment]
在树上面添加属性
:render-after-expand="false"
一行代码解决问题
也是找了好久，有时候这个api文档，除了使用者要仔细看之外，官网也可以将那些影响功能性的重点标出来就更好了

**Comment by mf717714** [comment]
> 在树上面添加属性
> :render-after-expand="false"
> 一行代码解决问题
> 也是找了好久，有时候这个api文档，除了使用者要仔细看之外，官网也可以将那些影响功能性的重点标出来就更好了

谢谢

**Comment by hs1pingtang** [comment]
> 在树上面添加属性 :render-after-expand="false" 一行代码解决问题 也是找了好久，有时候这个api文档，除了使用者要仔细看之外，官网也可以将那些影响功能性的重点标出来就更好了

太谢谢你了

**Comment by Blake-CN** [comment]
> 在树上面添加属性 :render-after-expand="false" 一行代码解决问题 也是找了好久，有时候这个api文档，除了使用者要仔细看之外，官网也可以将那些影响功能性的重点标出来就更好了

亲测可行
