### ISSUE TITLE
简单使用el-card 就会警告Invalid VNode type: Symbol(Comment) (symbol) ，且内容slot内容不显示

### ISSUE THREAD

**Issue by z30256238x** [ElemeFE/element#20523]
[Vue warn]: Invalid VNode type: Symbol(Comment) (symbol) 
  at <ElCard class="box-card" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn @ webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:156
[Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol) 
  at <ElCard class="box-card" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
[Vue warn]: resolveComponent can only be used in render() or setup().
warn @ webpack-internal:///./node_modules/_@vue_runtime-core@3.0.4@@vue/runtime-core/dist/runtime-core.esm-bundler.js:159
3webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:156 [Vue warn]: Invalid VNode type: Symbol(Text) (symbol) 
  at <ElCalendar> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

**Comment by aquarmarine** [comment]
解决了吗？

**Comment by cs1707** [comment]
看起来使用了 Vue 3.0 版本，目前 element-ui 暂不支持。

**Comment by zazzaz** [comment]
Hi, please raise your issue to Element Plus for Vue 3.0 https://github.com/element-plus/element-plus/issues/new/choose
