### ISSUE TITLE
el-slider最大值和最小值相等产生的问题

### ISSUE THREAD

**Issue by vincent-scorpio** [ElemeFE/element#20528]
Existing Component
是

Component Name
el-slider

Description
给el-slider设置了最大值100，最小值100，当前值100, 这时候再点击滑动条，会把value的值变成NaN，导致参数出错

**Comment by 3344567** [comment]
你可以尝试disabled

**Comment by s0ngyee** [comment]
> Existing Component
> 是
> 
> Component Name
> el-slider
> 
> Description
> 给el-slider设置了最大值100，最小值100，当前值100, 这时候再点击滑动条，会把value的值变成NaN，导致参数出错

能否提供一下复现demo链接，目前未能复现出该问题。
可从以下链接提issue
https://elementui.github.io/issue-generator

**Comment by likexie** [comment]
目前解决就是使用disablhuhu但是会有一个问题，就是滑块不在最大值而在最小值，这个可以用最小值减去一个数然后再赋值给滑块最大值，然后再禁用
