### ISSUE TITLE
关于日期框中英文翻译没有效果的问题

### ISSUE THREAD

**Issue by Lihongping99** [ElemeFE/element#20524]
核心代码：
import Vue from 'vue'
import ElementUI from 'element-ui'
import enlocale from 'element-ui/lib/locale/lang/en' // lang i18n
import zhlocale from 'element-ui/lib/locale/lang/zh-CN' // lang i18n

切换事件里面：
如果当前是中文，执行Vue.use(ElementUI, { zhlocale })
如果当前是中文，执行Vue.use(ElementUI, { enlocale})

执行完之后，除了日历组件没有效果以外，其他翻译是正常的

**Comment by iamkun** [comment]
你好 能提供一个复现 demo 地址吗？ 检查了一下 calendar 组件貌似没有这个问题

**Comment by Lihongping99** [comment]
是在中英文切换的时候没有效果，初始化的时候是正常的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 晚上7:41
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"李红平"<643171715@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] 关于日期框中英文翻译没有效果的问题 (#20524)





 
你好 能提供一个复现 demo 地址吗？ 检查了一下 calendar 组件貌似没有这个问题

**Comment by iamkun** [comment]
希望你有空能提供一个复现 demo， 不然我们也没办法帮助到你

**Comment by Lihongping99** [comment]
demo已发，运行就能看到，代码路径：src\views\dashboard\index.vue







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 晚上7:41
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"李红平"<643171715@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] 关于日期框中英文翻译没有效果的问题 (#20524)





 
你好 能提供一个复现 demo 地址吗？ 检查了一下 calendar 组件貌似没有这个问题

**Comment by iamkun** [comment]
demo 在哪呢， 或者直接提供一个 github repo 也可以

**Comment by Lihongping99** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 下午4:04
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"李红平"<643171715@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] 关于日期框中英文翻译没有效果的问题 (#20524)





 
demo 在哪呢， 或者直接提供一个 github repo 也可以

**Comment by MySecret** [comment]
> 你好 能提供一个复现 demo 地址吗？ 检查了一下 calendar 组件貌似没有这个问题
我也遇到了这个问题了，具体原因我看了下源代码，是WEEK_DAYS并没有改变。
data(){
return WEEK_DAYS:getI18nSettings().dayNames
}
我的理解是因为这个getI18nSettings在切换语言的时候，并不会重新执行一遍，这个方法在'element-ui/src/utils/date-util'文件里，并没有被监听。

**Comment by Lihongping99** [comment]
demo请见附件，那你最后是怎么处理了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 下午5:46
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"李红平"<643171715@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] 关于日期框中英文翻译没有效果的问题 (#20524)





  
你好 能提供一个复现 demo 地址吗？ 检查了一下 calendar 组件貌似没有这个问题
 我也遇到了这个问题了，具体原因我看了下源代码，是WEEK_DAYS并没有改变。
 data(){
 return WEEK_DAYS:getI18nSettings().dayNames
 }
 我的理解是因为这个getI18nSettings在切换语言的时候，并不会重新执行一遍，这个方法在'element-ui/src/utils/date-util'文件里，并没有被监听。

**Comment by MySecret** [comment]
您好，请您看下我上面的回复。。。感觉是一个bug，帮忙解决下吧

**Comment by Lihongping99** [comment]
我这边也遇到了这个问题，官方还没做出处理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 上午9:16
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"李红平"<643171715@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] 关于日期框中英文翻译没有效果的问题 (#20524)





 
您好，请您看下我上面的回复。。。感觉是一个bug，帮忙解决下吧

**Comment by iamkun** [comment]
please use `vue-i18n`  instead of using code like this 

```
如果当前是中文，执行Vue.use(ElementUI, { zhlocale })
如果当前是中文，执行Vue.use(ElementUI, { enlocale})
```

**Comment by MySecret** [comment]
> please use `vue-i18n` instead of using code like this
> 
> ```
> 如果当前是中文，执行Vue.use(ElementUI, { zhlocale })
> 如果当前是中文，执行Vue.use(ElementUI, { enlocale})
> ```

用的就是i18n，您能看下我给您发的邮件吗，我感觉是您取这个星期头文字的方法的问题，并不是响应式的。或者您看我上面的留言

**Comment by MySecret** [comment]
> > please use `vue-i18n` instead of using code like this
> > ```
> > 如果当前是中文，执行Vue.use(ElementUI, { zhlocale })
> > 如果当前是中文，执行Vue.use(ElementUI, { enlocale})
> > ```
> 
> 用的就是i18n，您能看下我给您发的邮件吗，我感觉是您取这个星期头文字的方法的问题，并不是响应式的。或者您看我上面的留言

切换语言的时候，WEEK_DAYS: getI18nSettings().dayNames这个是否要再次执行下，不然不会给WEEK_DAYS赋值新的值，导致星期文字还是之前的

**Comment by MySecret** [comment]
> 希望你有空能提供一个复现 demo， 不然我们也没办法帮助到你

demo地址：http://45.77.11.4/#/dashboard
您看下，点击右上角切换语言，calendar组件的顶部年月日和上一个月，下一个月，今天是会切换成对应语言，但是星期文字没有变化

**Comment by iamkun** [comment]
fixed in #20758, thanks

**Comment by Lihongping99** [comment]
https://github.com/ElemeFE/element/pull/20758
你看下这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ElemeFE/element"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月6日(星期六) 中午1:09
收件人:&nbsp;"ElemeFE/element"<element@noreply.github.com&gt;;
抄送:&nbsp;"李红平"<643171715@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ElemeFE/element] 关于日期框中英文翻译没有效果的问题 (#20524)





  
希望你有空能提供一个复现 demo， 不然我们也没办法帮助到你
  
demo地址：http://45.77.11.4/#/dashboard
 您看下，点击右上角切换语言，calendar组件的顶部年月日和上一个月，下一个月，今天是会切换成对应语言，但是星期文字没有变化
