### ISSUE TITLE
[Feature Request] checkbox的数据绑定与标签逻辑与其他组件不一致。

### ISSUE THREAD

**Issue by hcfw007** [ElemeFE/element#20545]
### Existing Component
Yes

### Component Name
el-checkbox-group

### Description
el-checkbox的值由label决定，而当值与所需显示内容不一致时，显示内容由slot决定。这与其他组件行为不一致。例如el-option，标签由slot决定，没有slot则为label，而值为value。
用value代表数据值更符合直觉。

**Comment by beliefgp** [comment]
因为 el-checkbox value 已经代表了当前选中的值的含义。
