### ISSUE TITLE
日期选择器Bug

### ISSUE THREAD

**Issue by Dongjianfa** [ElemeFE/element#20549]
![image](https://user-images.githubusercontent.com/29192760/101563266-e79bea80-3a03-11eb-80b0-d8a2c73514be.png)
默认格式yyyy-MM-dd
转为MM-dd格式出现日期没有对应
![image](https://user-images.githubusercontent.com/29192760/101563341-0dc18a80-3a04-11eb-9413-439b1d32a321.png)

**Comment by s0ngyee** [comment]
能否提供一下复现链接
https://elementui.github.io/issue-generator
