### ISSUE TITLE
中文文档中有错误

### ISSUE THREAD

**Issue by helloWordPengDa** [ElemeFE/element#20553]
PopConfirm 气泡确认框中的events 事件都不管用，confirm和cancel应该为onConfirm和onCancel,这个有点坑

**Comment by LanjianNUll** [comment]
2.14.0
2020-10-29

非兼容性更新
事件名称修改为 confirm, cancel (#20240 by @hugiron)

应该看的是最新的文档，然后用的是旧版

**Comment by helloWordPengDa** [comment]
> 2.14.0
> 2020-10-29
> 
> 非兼容性更新
> 事件名称修改为 confirm, cancel (#20240 by @hugiron)
> 
> 应该看的是最新的文档，然后用的是旧版

了解了，非常感谢！！！
