### ISSUE TITLE
[Bug Report] input输入框添加修饰符number后无法输入1.01(2.1.0版本可以输入这类数据)

### ISSUE THREAD

**Issue by MuFeiyan** [ElemeFE/element#20555]
### Element UI version
2.14.1

### OS/Browsers version
windows10/google(87.0.4280.88)

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/mufeiyan/pen/eYddaZg

### Steps to reproduce
输入：1.0

### What is Expected?
输入框显示：1.0

### What is actually happening?
输入框显示：1

**Comment by wu67** [comment]
safari v13.1 上输入数字之后无法输入小数点, 得先把小数当整数输入, 然后移动光标回去才能输入小数点.

chrome dev倒是正常

例子:
step1.  输入`123`
step2. 输入`.`, 无法输入
step3. 输入`4`, 结果为`1234`
step4. 光标左移一位, 输入`.`, 得到`123.4`

**Comment by beliefgp** [comment]
这个是 vue 的 v-model.number 引起的，不是组件问题

**Comment by MuFeiyan** [comment]
> 这个是 vue 的 v-model.number 引起的，不是组件问题

普通的input使用v-model.number是可以输入1.01这类数据的，而且你们2.1.0版本也是可以输入这类数据的，看了下你们的这个组件的源码，问题出在你们监听输入事件时逻辑处理那块
