### ISSUE TITLE
ElPagination

### ISSUE THREAD

**Issue by kim-king-rong** [ElemeFE/element#20566]
Extraneous non-emits event listeners (beforeEnter) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option.

**Comment by CriztianiX** [comment]
Same issue here

**Comment by cs1707** [comment]
It looks like it's using Vue 3.0

**Comment by cs1707** [comment]
Duplicate of #20375

**Comment by iamkun** [comment]
Vue@3.0.5 have fixed this issue, you can upgrade and have a try @kim-king-rong
