### ISSUE TITLE
日期选择器格式format格式为MM月dd日HH时mm分时显示错误

### ISSUE THREAD

**Issue by kcslyb** [ElemeFE/element#20563]

**Comment by kcslyb** [comment]
![image](https://user-images.githubusercontent.com/28124197/101883565-65adec00-3bd2-11eb-8fae-c999862fc670.png)

**Comment by kcslyb** [comment]
format格式为MM月dd日HH时mm分，选择时查看到显示错误
![Uploading image.png…]()

**Comment by cs1707** [comment]
你好，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以创建一个 [codepen](https://codepen.io/ziyoung/pen/rRKYpd) 或者提供一个最小化的 GitHub 仓库。 7 天内未跟进的 issue 将会被关闭。
