### ISSUE TITLE
辣鸡api文档，table组件设置expand-row-keys根本不起作用

### ISSUE THREAD

**Issue by TyncNever** [ElemeFE/element#20560]

**Comment by fallsank** [comment]
既然搜到这个问题，我也回复下吧：
1、首先expand-row-keys属性是Array不是Function
2、该Array里面存放key的字符串，而不是number
PS: 不要动不动就说辣鸡，多查文档，多学知识

**Comment by mmdlsu** [comment]
为啥动态往数组里存放字符串id无效，只有第一次渲染才生效？

**Comment by shssdd** [comment]
才知道expand-row-keys=[‘41’] 数组里面是字符串

**Comment by caiqichang** [comment]
@fallsank 表格数据切换后无效 怎么解决

**Comment by czphappy** [comment]
hahaaaa, it's string that could be put in the expand-row-keys.

**Comment by skylingfly** [comment]
> @fallsank 表格数据更新后无效 怎么解决

我也遇到同样的问题，暂时解决方法  就是+key 每次重新渲染

**Comment by HeZhiMr** [comment]
> 既然搜到这个问题，我也回复下吧： 1、首先expand-row-keys属性是Array不是Function 2、该Array里面存放key的字符串，而不是number PS: 不要动不动就说辣鸡，多查文档，多学知识

可是我的是这么做的，但是也不行啊

**Comment by HeZhiMr** [comment]
> 既然搜到这个问题，我也回复下吧： 1、首先expand-row-keys属性是Array不是Function 2、该Array里面存放key的字符串，而不是number PS: 不要动不动就说辣鸡，多查文档，多学知识

可是真的不行啊
`isFoldTable:{
      handler(val){
        this.$nextTick(()=>{
          console.log("isFoldTable===>>>",val);
          if (val) {
            this.expandRowKeys = []
          }else {
            this.expandRowKeys = this.tableData.map(item=>item.id)
          }
          console.log("isFoldTable2===>>>",this.expandRowKeys);
        })
      },
      immediate:true
    },
    tableData: [{
        id: "1",
        date: '2016-05-02',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1518 弄'
      }, {
        id: "2",
        date: '2016-05-04',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1517 弄'
      }, {
        id: "3",
        date: '2016-05-01',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1519 弄',
        children: [{
            id: "31",
            date: '2016-05-01',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1519 弄'
          }, {
            id: "32",
            date: '2016-05-01',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1519 弄'
        }]
      }, {
        id: "4",
        date: '2016-05-03',
        name: '王小虎',
        address: '上海市普陀区金沙江路 1516 弄'
      }],
    `
    动态展开无效，只有第一次渲染时候可以

**Comment by HeZhiMr** [comment]
> 既然搜到这个问题，我也回复下吧： 1、首先expand-row-keys属性是Array不是Function 2、该Array里面存放key的字符串，而不是number PS: 不要动不动就说辣鸡，多查文档，多学知识

可是真的不行啊,我甚至加了nextTick

```
isFoldTable:{
      handler(val){
        this.$nextTick(()=>{
          if (val) {
            this.expandRowKeys = []
          }else {
            this.expandRowKeys = this.tableData.map(item=>item.id)
          }
        })
      },
      immediate:true
    },
tableData: [{ id: "1", date: '2016-05-02', name: '王小虎', address: '上海市普陀区金沙江路 1518 弄' }, { id: "2", date: '2016-05-04', name: '王小虎', address: '上海市普陀区金沙江路 1517 弄' }, { id: "3", date: '2016-05-01', name: '王小虎', address: '上海市普陀区金沙江路 1519 弄', children: [{ id: "31", date: '2016-05-01', name: '王小虎', address: '上海市普陀区金沙江路 1519 弄' }, { id: "32", date: '2016-05-01', name: '王小虎', address: '上海市普陀区金沙江路 1519 弄' }] }, { id: "4", date: '2016-05-03', name: '王小虎', address: '上海市普陀区金沙江路 1516 弄' }], 
```
动态展开无效，只有第一次渲染时候可以

**Comment by fuxing2024** [comment]
> 既然搜到这个问题，我也回复下吧： 1、首先expand-row-keys属性是Array不是Function 2、该Array里面存放key的字符串，而不是number PS: 不要动不动就说辣鸡，多查文档，多学知识

太牛了大哥，我折腾了半天，结果是应该放字符串
