### ISSUE TITLE
[bug report] El button plain button style bug

### ISSUE THREAD

**Issue by sanpon** [ElemeFE/element#20578]
### Element UI version
2.14.1

### OS/Browsers version
chrome 87.0.4280.88

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/ssw_pawn/zbxh7not/1/

### Steps to reproduce
点击按钮后 按钮被添加了普通非plain的样式 猜测为浏览器缓存 firfox浏览器没有出现该情况 鼠标经过 离开 button都未呈现plain效果

### What is Expected?
点击button 鼠标离开button 呈现plain效果

### What is actually happening?
点击button 鼠标离开button表现为非plain状态的按钮背景色

**Comment by s0ngyee** [comment]
点击按钮后，按钮处于focus状态，展示高亮样式。当鼠标移出时并不会触发按钮的blur，所以仍为高亮样式 by design

**Comment by lollipop7** [comment]
一般在表格删除行时出现这种按钮激活状态仍然不消失的情况，而且是根据当前table的list的index高亮的，请问这种情况怎么解决呢
