### ISSUE TITLE
el-tree组件 id过长回显显示不了

### ISSUE THREAD

**Issue by goutou123** [ElemeFE/element#20570]
![image](https://user-images.githubusercontent.com/49984680/102062055-3647eb00-3e2f-11eb-9a63-16b5b200b5fc.png)
![image](https://user-images.githubusercontent.com/49984680/102062231-67282000-3e2f-11eb-9562-707ec16bde9f.png)
![image](https://user-images.githubusercontent.com/49984680/102062292-7909c300-3e2f-11eb-863b-b0e7f9ef40f9.png)

el-tree组件 回显时调用setCheckedKeys方法，id太长无法进行回显

**Comment by cs1707** [comment]
你好，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以创建一个 [codepen](https://codepen.io/ziyoung/pen/rRKYpd) 或者提供一个最小化的 GitHub 仓库。 7 天内未跟进的 issue 将会被关闭。

**Comment by goutou123** [comment]
`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
</head>
<body>
  <div id="app">
    <el-tree
   ref="tree"
  :data="data"
  show-checkbox
  node-key="id"
  :default-expanded-keys="[2, 3]"
  :default-checked-keys="[5]"
  :props="defaultProps">
</el-tree>
<el-button @click="showData">回显数据</el-button>
  </div>
</body>
  
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
        return  {
          data: [{
          id: 11111111111111111111111111111111111111111111111,
          label: '一级 1',
          children: [{
            id: 11111111111111111111111111111111111111111111114,
            label: '二级 1-1',
            children: [{
              id: 11111111111111111111111111111111111111111111119,
              label: '三级 1-1-1'
            }, {
              id: 111111111111111111111111111111111111111111111110,
              label: '三级 1-1-2'
            }]
          }]
        }, {
          id: 11111111111111111111111111111111111111111111112,
          label: '一级 2',
          children: [{
            id: 11111111111111111111111111111111111111111111115,
            label: '二级 2-1'
          }, {
            id: 11111111111111111111111111111111111111111111116,
            label: '二级 2-2'
          }]
        }, {
          id: 11111111111111111111111111111111111111111111113,
          label: '一级 3',
          children: [{
            id: 11111111111111111111111111111111111111111111117,
            label: '二级 3-1'
          }, {
            id: 11111111111111111111111111111111111111111111118,
            label: '二级 3-2'
          }]
        }],
        defaultProps: {
          children: 'children',
          label: 'label'
        }
        }
      },
      methods: {
        showData(){
          const data = [11111111111111111111111111111111111111111111115,11111111111111111111111111111111111111111111118]
          this.$refs.tree.setCheckedKeys(data)
        }
      }
    })
  </script>
</html>`
如果将数据改短，可以正常显示。

**Comment by beliefgp** [comment]
你这个数字已经超出 js 安全数字范围了 Number.MIN_SAFE_INTEGER，存在数字精度丢失的风险，请转为字符串操作。
