### ISSUE TITLE
[bug report] empty data prompt set by cascade component does not take effect: slot = empty '

### ISSUE THREAD

**Issue by lmfuture** [ElemeFE/element#20613]
### Element UI version
2.14.1

### OS/Browsers version
谷歌

### Vue version
2.6.12

### Reproduction Link
https://github.com/PanJiaChen/vue-element-admin

### Steps to reproduce
234234234

### What is Expected?
21312313

### What is actually happening?
13123123

**Comment by cs1707** [comment]
Duplicate of #20612
