### ISSUE TITLE
[bug report] when you click the El select box, the El Popover will not close

### ISSUE THREAD

**Issue by shujiawei** [ElemeFE/element#20632]
### Element UI version
2.14.1

### OS/Browsers version
window10

### Vue version
2.6.12

### Reproduction Link
https://jsfiddle.net/sk27nx6q/

### Steps to reproduce
先点击el-popover,再点击el-select，el-popver不消失

### What is Expected?
点击el-popover,再点击el-select，el-popver消失

### What is actually happening?
先点击el-popover,再点击el-select，el-popver不消失

**Comment by s0ngyee** [comment]
可通过定义共有父组件的状态进行逻辑控制。组件本身是独立无关联的。
