### ISSUE TITLE
inputnumber设置了max跟min后，实际的值限制了，但是文本框里面的内容没限制

### ISSUE THREAD

**Issue by kfqkfy** [ElemeFE/element#2063]
手动输入文本框里面的内容，可以一直输下去，实际的值是限制了，但是显示的没限制

![image](https://cloud.githubusercontent.com/assets/2724562/21538869/54f7f6f2-cddc-11e6-8e02-df54c6f81625.png)

新版handleBlur这边的相关代码删了？
![image](https://cloud.githubusercontent.com/assets/2724562/21538889/875fa1da-cddc-11e6-85dc-a3b11ef668d1.png)

demo
http://jsfiddle.net/1pbL70p4/

**Comment by baiyaaaaa** [comment]
今天会修复
