### ISSUE TITLE
[Bug Report] component: el-drawer    Type detection fails when the size property is number

### ISSUE THREAD

**Issue by hlfine** [ElemeFE/element#20636]
### Element UI version
2.14.1

### OS/Browsers version
window 

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/hlfine/pen/rNMJpvV

### Steps to reproduce
Click the button

### What is Expected?
The property has been changed successfully and can be used normally

### What is actually happening?
[Vue warn]: Invalid prop: type check failed for prop "size". Expected String with value "300", got Number with value 300.

found in

---> <ElDrawer> at packages/drawer/src/main.vue
       <Root>

**Comment by wupeiwen** [comment]
遇到了同样的问题，将数值300改为字符串"300px"，符合期望成功渲染

**Comment by SimoralX** [comment]
同遇到，传入number不起作用，只能传入 ‘_px’ 或者 ’_%‘ 的string类型。

**Comment by cs1707** [comment]
fixed
