### ISSUE TITLE
[Bug Report] el-calendar The i18n of daynames (date-table  <th>) doesn't work.

### ISSUE THREAD

**Issue by vjguo** [ElemeFE/element#20642]
### Element UI version
2.14.1

### OS/Browsers version
Windows 10 /  Google Chrome 84.0.4147.125

### Vue version
2.6.12

### Steps to reproduce
1. 以zh语言环境打开含有日历组件的画面。此时星期名，年月，上个月，今天，下个月为中文，表现正确。
2. 不重新加载画面，将语言环境动态切换到en。“此时星期名仍是中文“，其他是英文，表现不正确。

### What is Expected?
在动态切换语言环境时，星期名的语言能随之变化。

### What is actually happening?
该组件的星期名只会在初始化时取得当前语言环境的国际化，而不再响应语言环境变化。

**Comment by iamkun** [comment]
Duplicate of #20524
