### ISSUE TITLE
[Bug Report] gyp error when run yarn

### ISSUE THREAD

**Issue by zhaozhongyu** [ElemeFE/element#20651]
### Element UI version
2.14.1

### OS/Browsers version
windows 10

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/zhaozhongyu/pen/YzGLQvb

### Steps to reproduce
local visual studio version: VS2019  Enterprise,
local node version: v14.15.3,
yarn

### What is Expected?
install node_modules success

### What is actually happening?
install node_modules fail

error C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\code\Github\element\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\code\\Github\\element\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Python27\python2.EXE
gyp verb check python version `C:\Python27\python2.EXE -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.15.3
gyp verb command install [ '14.15.3' ]
gyp verb install input version string "14.15.3"
gyp verb install installing version: 14.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.15.3
gyp verb build dir attempting to create "build" dir: C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [
gyp info spawn args   'C:\\code\\Github\\element\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\code\\Github\\element\\node_modules\\gulp-sass\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\code\\Github\\element\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\.node-gyp\\14.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\admin\\.node-gyp\\14.15.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\code\\Github\\element\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\admin\\.node-gyp\\14.15.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\code\\Github\\element\\node_modules\\gulp-sass\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\code\\Github\\element\\node_modules\\gulp-sass\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\admin\.node-gyp\14.15.3
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
��������ʱ��Ϊ 2021/01/05 ���� 5:54:39��
�ڵ� 1 �ϵ���Ŀ��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln��(Ĭ��Ŀ��)��
ValidateSolutionConfiguration:
  �������ɽ���������á�Release|x64����
��Ŀ��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln��(1)���ڽڵ� 1 �����ɡ�C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj��(2) (Ĭ��Ŀ��)��
��Ŀ��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj��(2)���ڽڵ� 1 �����ɡ�C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj��(3) (Ĭ��Ŀ��)��
C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj(21,3): error MSB4019: �Ҳ����������Ŀ��C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\Microsoft\VC\v160\Microsoft.Cpp.Default.props������ȷ�� Import ������C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\Microsoft\VC\v160\\Microsoft.Cpp.Default.props���еı���ʽ��ȷ�����ļ�λ�ڴ����ϡ�
�����������Ŀ��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj��(Ĭ��Ŀ��)�Ĳ��� - ʧ�ܡ�
�����������Ŀ��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj��(Ĭ��Ŀ��)�Ĳ��� - ʧ�ܡ�
�����������Ŀ��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln��(Ĭ��Ŀ��)�Ĳ��� - ʧ�ܡ�

����ʧ�ܡ�

��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.sln��(Ĭ��Ŀ��) (1) ->
��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj.metaproj��(Ĭ��Ŀ��) (2) ->
��C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj��(Ĭ��Ŀ��) (3) ->
  C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass\build\src\libsass.vcxproj(21,3): error MSB4019: �Ҳ����������Ŀ��C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\Microsoft\VC\v160\Microsoft.Cpp.Default.props������ȷ�� Import ������C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\Microsoft\VC\v160\\Microsoft.Cpp.Default.props���еı���ʽ��ȷ�����ļ�λ�ڴ����ϡ�

    0 ������
    1 ������

����ʱ�� 00:00:00.20
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\code\Github\element\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\code\\Github\\element\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\code\Github\element\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by s0ngyee** [comment]
pls check your node-sass and node version. see https://github.com/sass/node-sass

**Comment by zhaozhongyu** [comment]
> pls check your node-sass and node version. see https://github.com/sass/node-sass

I have manually install node-sass@4.14, but it did not work, same error were throw again.
