### ISSUE TITLE
[bug report] when the cascade selector is assigned a value for the second time, the display is correct, but when you click to open the drop-down selector again, the displayed provinces, cities and counties are wrong, or the result of the first assignment.

### ISSUE THREAD

**Issue by citystory** [ElemeFE/element#20654]
### Element UI version
2.14.1

### OS/Browsers version
win10系统/谷歌浏览器版本 87.0.4280.88

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/citystory/pen/MWjGMWe

### Steps to reproduce
重现链接详见：http//jsrun.net/BmIKp。先点击左侧第一个按钮“赋值1”，再点击第二个按钮“赋值2”，然后再点左侧的Cascader组件，弹出的选框内的值是错误的。

### What is Expected?
第二次赋值之后，点击Cascader组件，弹出的选框内的值应该跟第二次赋值的相同，跟未点击Cascader组件时显示的值相同。

### What is actually happening?
第二次赋值之后，点击Cascader组件，弹出的选框内的值是错误的。

**Comment by iamkun** [comment]
fixed
