### ISSUE TITLE
form校验无法使用type:['string', 'number']形式定义

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#2068]
### ElementUI version

1.0.8
### OS/Browers version

Chrome 55
### Vue version

2.1.7
### Steps to reproduce
form的校验规则rule
`rules: {
username: [
{ type: ['string', 'number], 
required: true,
message: '请输入姓名',
trigger: 'blur' 
}
        ]
      }`
不支持这样的type定义，在[https://github.com/tmpfs/async-validate](https://github.com/tmpfs/async-validate)的API中看到了这种用法
另外transform属性经过试验会执行但不会更改实际value的值，不过这个可以用change事件来实现
### What is Expected?
希望可以支持多种类型

**Comment by Leopoldthecoder** [comment]
最新版已支持。
