### ISSUE TITLE
[bug report] bug when the default value of cascade component is integer 0

### ISSUE THREAD

**Issue by luxin88** [ElemeFE/element#20696]
### Element UI version
2.14.1

### OS/Browsers version
Win 10/Chrome 87

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/luxin88/pen/MWjLYpN

### Steps to reproduce
当cascader组件包含value为整数0的item，且给v-model绑定的变量赋值整数0时，无法默认选择value为0的item，且第一次手工选择无效，需要先选择其他value非0项目再重新选择value为0的项目才能正常选中（重现链接中，直接选择Top Level，无法选中）

### What is Expected?
期待v-model为0时默认选中value为0的项目

### What is actually happening?
实际v-model为0时，未选中value为0的项目

**Comment by cs1707** [comment]
Try this `selectVal: [0]`
