### ISSUE TITLE
运行rpm run dist报错

### ISSUE THREAD

**Issue by zuomingcai** [ElemeFE/element#207]
运行rpm run dist报错：
ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: E:\test\node_modules\element-ui\packag
es\pagination\src\pagination.js Unexpected token (47:19)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (47:19)
 ......

**Comment by QingWei-Li** [comment]
什么鬼 你在包里执行 npm run dist 有啥用，你要把项目 clone 下来安装依赖再执行 run dist

**Comment by zuomingcai** [comment]
安装了依赖的

在 2016-10-01 13:53:57，"cinwell.li" <notifications@github.com> 写道：


什么鬼 你在包里执行 npm run dist 有啥用，你要把项目 clone 下来安装依赖再执行 run dist

**Comment by QingWei-Li** [comment]
babel 配置里有加 jsx 的插件呀，你具体是怎么用的？
