### ISSUE TITLE
[TimePicker] Not aligned in Windows

### ISSUE THREAD

**Issue by 214132049** [ElemeFE/element#2071]
### ElementUI version

1.0.9
### OS/Browers version

chrome 55
### Vue version

2.0.0-rc.4
### What is actually happening?
任意时间选择器UI问题，滚动的位置不正确。官方例子有一样的效果

**Comment by stackia** [comment]
楼主描述不清楚，我猜测说的是这个问题
![image](https://cloud.githubusercontent.com/assets/5107241/21559519/8fe579d6-ce88-11e6-8446-3f8958e86575.png)

**Comment by 214132049** [comment]
恩 对的  是这个问题   数字位置不居中

**Comment by 214132049** [comment]
![image](https://cloud.githubusercontent.com/assets/13826913/21629607/e49e9838-d264-11e6-97d0-d1c6a465a0e1.png)

**Comment by 214132049** [comment]
时间点时分秒的值，是上一次停留在蓝色地方的值

**Comment by QingWei-Li** [comment]
没 Windows

谁可以帮忙修复下？

**Comment by PanJiaChen** [comment]
最新chrome mac
官网demo截图
![image](https://cloud.githubusercontent.com/assets/8121621/22773903/8a054aba-eedf-11e6-8a62-bfb8f8d59e61.png)
也是有问题的
