### ISSUE TITLE
Dislocation of El row layout on safari

### ISSUE THREAD

**Issue by 15738039217** [ElemeFE/element#20728]
<el-row :gutter="10">
  <el-col :xs="8" :sm="6" :md="4" :lg="3" :xl="1"><div class="grid-content bg-purple"></div></el-col>
  <el-col :xs="4" :sm="6" :md="8" :lg="9" :xl="11"><div class="grid-content bg-purple-light"></div></el-col>
  <el-col :xs="4" :sm="6" :md="8" :lg="9" :xl="11"><div class="grid-content bg-purple"></div></el-col>
  <el-col :xs="8" :sm="6" :md="4" :lg="3" :xl="1"><div class="grid-content bg-purple-light"></div></el-col>
</el-row>

该代码在safari 浏览器显示换行，其他浏览器显示正常
safari 版本13.1.1 (15609.2.9.1.2)
"element-plus": "^1.0.1-beta.27",

**Comment by cs1707** [comment]
Please create an issue for element-plus here. https://github.com/element-plus/element-plus/issues
