### ISSUE TITLE
[feature request] suggestions on building components through data

### ISSUE THREAD

**Issue by liutao409** [ElemeFE/element#20725]
### Existing Component
是

### Component Name
所有组件

### Description
       我使用vue3 ts element-plus开发系统，开发过程中发现如果通过纯数据化来构建组件（每个组件都只有一个data对象作为输入参数，里面包含这
个组件所需要的属性和方法），将极大的提高开发效率，并和现有的强类型和函数式编程会非常契合，构建组件和开发业务将全部统一变化为对数据的处
理，template的编写也将极大的简化。当然现有的组件构建方式不变，在此基础上封装一套通过数据来构建组件的扩展版本就可以。

        个人的一点不成熟的想法，自己也做了一些封装的尝试，代码量降低到原有的1/3，谢谢回复！

**Comment by cs1707** [comment]
Please create an issue for element-plus here. https://github.com/element-plus/element-plus/issues
