### ISSUE TITLE
[Bug Report] Basic ElementUI app does not start

### ISSUE THREAD

**Issue by tarkhil** [ElemeFE/element#20720]
### Element UI version
2.15.0

### OS/Browsers version
n/a

### Vue version
2.6.12

### Reproduction Link
https://github.com/tarkhil/e18n

### Steps to reproduce
I've just created an app
vue create e18n
cd e18n
vue add i18n
vue add element-ui
npm install --save-dev sass-loader
npm install 
npm run serve

(well, I've also added ru.json to locales and required webpack to ignore temporary Emacs files, but that's not related to an issue)

### What is Expected?
running app

### What is actually happening?
 ERROR  Failed to compile with 1 error                                                                                                                                                           12:04:15 AM

 error  in ./src/styles.scss

Syntax Error: Error: PostCSS received undefined instead of CSS string

 @ ./src/styles.scss 4:14-217 14:3-18:5 15:22-225
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://over.ru:8082&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by cs1707** [comment]
This may not a bug of ElementUI.
