### ISSUE TITLE
自定义主题按需引入 CSS 文件`styleLibraryName`的问题

### ISSUE THREAD

**Issue by luoye-fe** [ElemeFE/element#2074]
官方文档中，按需引入主题样式文件的 `demo` 是：
```json
{
  "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "~theme"
    }
  ]]]
}
```
如果按照这个来的话，会从 `node_modules` 文件夹中找 `theme` 这个文件夹。这样的话按照官方推荐做法很令人迷惑。

暂时是用下面的方法来解决。
```json
{
  "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "~element-ui/../../theme"
    }
  ]]]
}
```

不知是否有更好的方法？或者更新下文档内容。

**Comment by reverland** [comment]
fork theme-default 然后在package.json里写git地址。

这样npm install就好了。。。也可以用这个babel插件

**Comment by luoye-fe** [comment]
@reverland 自定义主题的目的就是能在本项目里直接定制，要是 fork 在别的仓库里修改有点多此一举。

我的意思是官方文档的教程最后一部不是很准确。

**Comment by QingWei-Li** [comment]
有问题请提供 demo 或项目地址，你这样我怎么知道哪里写错了。我本地跑没问题

**Comment by luoye-fe** [comment]
官方文档按需引入css的示例是：
```
```

**Comment by luoye-fe** [comment]
官方文档按需引入css文件的示例是：

```json
"styleLibraryName": "~theme"
```

这样去找 `theme` 文件夹会在 `node_modules` 里找，但是按照教程里来生成的文件夹是在项目根目录，并且说的是 
>指定 styleLibraryName 路径为自定义主题相对于 .babelrc 的路径

只是这么一个小问题而已:joy:

**Comment by luoye-fe** [comment]
:thumbsup:
