### ISSUE TITLE
[Bug Report] Image: preview z-index bug

### ISSUE THREAD

**Issue by lujh1005** [ElemeFE/element#20743]
### Element UI version
2.15.0

### OS/Browsers version
win10

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/lujh1005/pen/bGBdeQa

### Steps to reproduce
el-dialog -> image preview

### What is Expected?
image preview在el-dialog上层

### What is actually happening?
image preview被el-dialog覆盖

**Comment by cs1707** [comment]
Add `z-index` prop to the image as a temporary solution
