### ISSUE TITLE
MessageBox在chrome中的bug，会是因为什么导致的？

### ISSUE THREAD

**Issue by zhangkuiworld** [ElemeFE/element#2079]
### ElementUI version
1.0.5

### OS/Browers version
Chrome 55.0.2883.87

### Vue version
2.0.1

### 这是截图，文字和图片错行了。当然，并不是因为文本太长啊，一个字也这样。当我在自己的电脑上也是同一版本的chrome就没这种问题。区别是我的电脑系统是win10，他是win7,、我的电脑屏幕分辨率比较高，他的比较低。
![image](https://cloud.githubusercontent.com/assets/6340667/21544535/b5ea8e38-ce0a-11e6-8f01-35bbd227fbbe.png)

### What is Expected?
求教开发者，百思不得其解，给点思路……

**Comment by Leopoldthecoder** [comment]
有自己改样式吗？

**Comment by Visonnn** [comment]
如果使用的 element-ui 版本号和 CSS 对不上，就很容易出现这个情况。

**Comment by Leopoldthecoder** [comment]
@zhangkuiworld 参考一下楼上
