### ISSUE TITLE
请问有 RoadMap 吗？

### ISSUE THREAD

**Issue by esr2587758** [ElemeFE/element#208]
早上刷微博发现 vue2.0 发布了，顺着链接发现了这个 element 项目。心中是无比激动的！
虽然对比与 antd 组件还没有那么丰富， 但还是令人欣喜。
那么请问有 roadmap 吗？未来有什么计划？

感谢你们的贡献。

**Comment by fishpaw** [comment]
这个东西应该暂时不会考虑。短时间内的计划是：
1. 稳定目前 Element 版本：修复 bug，优化组件特性，为现有组件增加新特性（所以暂时不会添加新的组件了）
2. 优化网站（element.eleme.io）的功能和使用体验
