### ISSUE TITLE
nuxt.js的element的demo有吗

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/element#2085]
nuxt.js的element的[demo](https://github.com/ElemeFE/element/issues/2034)有吗?
现在好像我集成到nuxt后有bug
找表格里面嵌套按钮没法显示

**Comment by yuchonghua** [comment]
[关于nuxt](https://github.com/ElemeFE/mint-ui/issues/548)

**Comment by QingWei-Li** [comment]
没有，
服务端渲染并不能完全代替客户端渲染

**Comment by yuchonghua** [comment]
直接打开是这样的
![image](https://cloud.githubusercontent.com/assets/17898715/21559053/c5733524-ce7f-11e6-8806-3b792d1acdba.png)
要点击才正常
![image](https://cloud.githubusercontent.com/assets/17898715/21559055/d5cde630-ce7f-11e6-87e9-3117da546f45.png)

**Comment by yuchonghua** [comment]
@QingWei-Li 这个问题我有办法让客户端再渲染一次吗
