### ISSUE TITLE
[Bug Report] :border="false" is not working in Multi-level Header Table

### ISSUE THREAD

**Issue by BoBoooooo** [ElemeFE/element#20862]
### Element UI version
2.15.1

### OS/Browsers version
MacOS/Chrome 89

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/boboooooo/pen/poNMwXa

### Steps to reproduce
多级表头下配置 :border="false"无效

### What is Expected?
多级表头情况下border属性生效可以控制边框是否显示

### What is actually happening?
多级表头下配置 :border="false"无效

**Comment by cs1707** [comment]
After looking at this part of the code, I guess it may have been designed that way on purpose. You can do this by rewriting the css style。
