### ISSUE TITLE
[Bug Report] [Message]Cannot set property 'type' of undefined

### ISSUE THREAD

**Issue by bowencool** [ElemeFE/element#20867]
### Element UI version
2.15.1

### OS/Browsers version
Mac 11.3 / Chrome 89

### Vue version
2.6.12

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/packages/message/src/main.js#L53

### Steps to reproduce
          this.$message.error(error.msg || error.message);
          this.$message.error(error && error.message);
代码里太多这种写法了，经常传进去一个undefined

### What is Expected?
希望有个判空条件

### What is actually happening?
Cannot set property 'type' of undefined

**Comment by cs1707** [comment]
This may not a bug of ElementUI.

**Comment by wangfpp** [comment]
这里是否可以做一个兼容呢？
```javascript
['success', 'warning', 'info', 'error'].forEach(type => {
    Message[type] = options => {
        options = options || "";
        if (typeof options === 'string') {
            options = {
                message: options
            };
        }
        options.type = type;
        return Message(options);
    };
});


```

**Comment by cs1707** [comment]
我是这么认为的：输入一个不合法的值，直接抛错，然后开发去检查自己代码中的错误，作出修复。要不然直接弹一个空白框，也是蛮奇怪的。
不过我看原生的 `alert` 和 antd `message` 也有对 `null`、`undefined` 处理，我看下怎么优化吧。
