### ISSUE TITLE
el-autocomplete 嵌套el-select 样式问题

### ISSUE THREAD

**Issue by zhouhao4221** [ElemeFE/element#2086]
### ElementUI version
 1.1.1

### OS/Browers version
Chrome 55 

### Vue version
2.1.6 

### Steps to reproduce
嵌套进去后select的宽度没有自适应，不知是否为Bug。
在select上增加style（style="min-width:100px"）能够展示正确。
` <el-autocomplete 
              placeholder="请输入内容" 
              v-model="search" 
              :fetch-suggestions="querySearchAsync" 
              @select="handleSelect">
              <el-select v-model="select" slot="prepend" placeholder="全部" >
                <el-option label="全部" value="0"></el-option>
                <el-option label="用户名" value="1"></el-option>
                <el-option label="邮箱" value="2"></el-option>
              </el-select>
              <el-button slot="append" icon="search"></el-button>
            </el-autocomplete>
`
![wx20161230-090134](https://cloud.githubusercontent.com/assets/6303733/21558017/cc27c210-ce6e-11e6-8d66-9d831cc45f23.png)

**Comment by baiyaaaaa** [comment]
select 在作为需要设置宽度input 的 `slot="prepend"` 或者 `slot="append"` 时需要设置宽度才能正确展示

**Comment by zhouhao4221** [comment]
`<el-select v-model="select" slot="prepend" placeholder="全部" >`
已经设置了，自己加宽度也可以正常显示。
我只是做个反馈。
