### ISSUE TITLE
[Bug Report] Show password event move cursor to start of input

### ISSUE THREAD

**Issue by wanwas** [ElemeFE/element#20865]
### Element UI version
2.15.1

### OS/Browsers version
Linux/Google chrome Version 89.0.4389.82

### Vue version
2.6.12

### Reproduction Link
https://jsfiddle.net/wanwas/topz1nhb/

### Steps to reproduce
1. enter something in the field
2. click on show password icon

### What is Expected?
After the click, it appears at the beginning of the input.

### What is actually happening?
After the click, the cursor must remain in place (after the last character entered)

**Comment by xiaofeng-bm** [comment]
you kan see this issues 
https://github.com/ElemeFE/element/issues/18573
