### ISSUE TITLE
1.1.1版, 表格组件报没有注册el-scrollbar组件

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#2087]
os:  win 10, chrome 55

ver: 1.1.1

使用表格组建, 报如下错误:

![image](https://cloud.githubusercontent.com/assets/10840991/21558491/ce74eb36-ce75-11e6-9349-e4716c7240e9.png)

看了下 table.vue, 确实是没有注册.

**Comment by QingWei-Li** [comment]
fixed via #2090 

去掉了虚拟滚动条功能

**Comment by wu933** [comment]
去掉了滚动条功能，那这个报错要怎么解决呢？
