### ISSUE TITLE
级联选择器多选时，value数组顺序必须要和options的数组顺序一致，否则删除一个值时，会出现删除不是它本身的bug，建议改进下这个缺陷

### ISSUE THREAD

**Issue by YuTingtao** [ElemeFE/element#20901]

**Comment by YuTingtao** [comment]
![Uploading snipaste_2021-04-02_18-45-40.png…]()
![Uploading snipaste_2021-04-02_18-45-57.png…]()

**Comment by cs1707** [comment]
Duplicate of #20928

**Comment by YuTingtao** [comment]
请把我这个issue删除吧 @cs1707

**Comment by YuTingtao** [comment]
可以帮忙删掉我发的这个issue吗 @cs1707
