### ISSUE TITLE
[Bug Report] InfiniteScroll not work with an async callback function

### ISSUE THREAD

**Issue by StarkShang** [ElemeFE/element#20900]
Hi, I am using InfiniteScroll directive and find it doesn't work well with an async callback function. An example is posted here, https://codepen.io/starkshang/pen/WNRpQab

I notice that the InfiniteScroll directive will check that whether the callback function is a function before trigger it.
```javascript
// packages > infinite-scroll > src > main.js   line 111
if (shouldTrigger && isFunction(cb)) {
  cb.call(vm);
} else if (observer) {
  observer.disconnect();
  this[scope].observer = null;
}
```
And the function `isFunction` implement as follows,
```
// src > utils > types.js   line 13
export const isFunction = (functionToCheck) => {
  var getType = {};
  return functionToCheck && getType.toString.call(functionToCheck) === '[object Function]';
};
```
For an async callback, it is '[object AsyncFunction]', rather than '[object Function]'. So the InfiniteScroll directive cannot work with async functions directly.

### Element UI version
2.15.1

### OS/Browsers version
Edge

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/starkshang/pen/WNRpQab

### Steps to reproduce
using v-infinite-scroll="load" where load is an async function.

### What is Expected?
An async callback function will be called with v-infinite-scroll directive.

### What is actually happening?
As shown in example, v-infinite-scroll with synchronous function can normally load data, but it doesn't work with async function.

**Comment by holylinyy** [comment]
why close , this Bug not fix at all
