### ISSUE TITLE
[bug report] after setting the height of El input style, the text box cannot adapt to the height

### ISSUE THREAD

**Issue by tomieric** [ElemeFE/element#20919]
### Element UI version
2.15.1

### OS/Browsers version
windows

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/tommyshao/pen/JjEOBXm

### Steps to reproduce
```
<el-input
  type="text"
  placeholder="请输入内容"
  v-model="text"
  maxlength="10"
  show-word-limit
  style="height: 100px"
>
```

### What is Expected?
输入框能自适应style设置高度

### What is actually happening?
文本按自动高度执行，无法自适应容器高度

**Comment by cs1707** [comment]
Setting the `autosize` prop for a textarea type of Input makes the height to automatically adjust based on the content. An options object can be provided to autosize to specify the minimum and maximum number of lines the textarea can automatically adjust.

[https://element.eleme.io/#/en-US/component/input](https://element.eleme.io/#/en-US/component/input)

**Comment by tomieric** [comment]
:bad
