### ISSUE TITLE
[bug report] error in binding object array of check box group

### ISSUE THREAD

**Issue by 1556461835** [ElemeFE/element#20942]
### Element UI version
2.15.1

### OS/Browsers version
window10 

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/1556461835/pen/MWJqEQr

### Steps to reproduce
您好，请查看这篇文章 https://www.cnblogs.com/growupup/p/11755420.html 可以看一下这个博客的解读就明白我遇到的难题了

### What is Expected?
checkBox group 的v-model 可以绑定多个键值对的对象数组

### What is actually happening?
只可以绑定固定数组格式

**Comment by cs1707** [comment]
https://codepen.io/cs1707/pen/qBRJZbY `checkList[check1]`  -> `checkList.check1` or `checkList['check1']`
