### ISSUE TITLE
1.1.1Table组件，官方文档里的示例都没法实现排序效果

### ISSUE THREAD

**Issue by ldllidonglin** [ElemeFE/element#2094]
这是官方文档提供的链接http://jsfiddle.net/api/post/library/pure/
而且我自己开发时，排序也没法使用

**Comment by Leopoldthecoder** [comment]
看了一下，是 Vue 在 2.1.7 里的某些改动导致的。可以先把 Vue 降级到 2.1.6，或者等我们发 1.1.2。

**Comment by QingWei-Li** [comment]
fixed via #2096
