### ISSUE TITLE
为 badge 提供非角标用法

### ISSUE THREAD

**Issue by stackia** [ElemeFE/element#2095]
### ElementUI version
1.1.1

### What is Expected?
现在 badge 默认是固定在元素右上角，作为“上角标”概念来使用的。希望能够提供像 bootstrap badge 相似的显示模式
http://getbootstrap.com/components/#badges
![image](https://cloud.githubusercontent.com/assets/5107241/21559039/6e2e06b8-ce7f-11e6-900d-ea93adeb80e9.png)
![image](https://cloud.githubusercontent.com/assets/5107241/21559043/7a4985ee-ce7f-11e6-964c-1e1d2d4aa322.png)

**Comment by QingWei-Li** [comment]
![image](https://cloud.githubusercontent.com/assets/7565692/21559144/c26c3d42-ce81-11e6-8728-84ce303e5637.png)
