### ISSUE TITLE
[Bug Report] confirm with dangerouslyUseHTMLString=true cannot use like <i />

### ISSUE THREAD

**Issue by sfengx** [ElemeFE/element#20954]
### Element UI version
2.15.1

### OS/Browsers version
chrome 89.0.4389.128

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/sfengx/pen/NWdEMwL

### Steps to reproduce
click button

### What is Expected?
one <i>

### What is actually happening?
two <i>

**Comment by SummerGua** [comment]
Here's the `notification/src/main.vue` source code:
```javascript
<slot>
    <p v-if="!dangerouslyUseHTMLString">{{ message }}</p>
    <p v-else v-html="message"></p>
 </slot>
```
If you use the tag like
```html
<i/>1
```
Its output is
```
1
```
If you use `v-html` like
```html
<template>
    <a v-html="message"></a>
</template>
<script>
...
data() {
    message: '<i/>1'
}
</script>
```
Its output is 
*1*

`v-html` uses `innerHTML`, so when I try it, I find its output is same as `v-html`.
I go to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i) to find the answer, it says
>both the starting and ending tag are mandatory.

DON'T USE `<i/>` SINGLY ANY MORE!!

**Comment by sfengx** [comment]
Thank you for response.
