### ISSUE TITLE
[Bug Report] slider props range and show-input can't coexist?

### ISSUE THREAD

**Issue by zhoufanglu** [ElemeFE/element#20969]
### Element UI version
2.15.1

### OS/Browsers version
window/chrome

### Vue version
2.6.12

### Steps to reproduce
<el-slider
            v-model="totalScore"
            range
            show-input
            :max="100">
 </el-slider>

### What is Expected?
Expect input fields
![@~ $)BWG(E3G }U(@9KAHDL](https://user-images.githubusercontent.com/24451091/116210283-4b397100-a775-11eb-9673-e641f21ecbdb.png)

### What is actually happening?
I can't actually enter

**Comment by zhazhanitian** [comment]
I don't quite understand what your problem is

**Comment by zhoufanglu** [comment]
> I don't quite understand what your problem is

我想range与 show-input共存， 我想要有两个滑块点， 然后两边都有输入框可以输入

**Comment by zhazhanitian** [comment]
> > I don't quite understand what your problem is
> 
> 我想range与 show-input共存， 我想要有两个滑块点， 然后两边都有输入框可以输入

At present, the design is a little difficult to meet your needs, it is estimated that you can only rely on yourself

**Comment by ihoment-amu** [comment]
@zhazhan

**Comment by ihoment-amu** [comment]
@zh

**Comment by ihoment-amu** [comment]
@hex-ci

**Comment by ihoment-amu** [comment]
@m

**Comment by ihoment-amu** [comment]
@54545395373vvvvv2222@@###@$$@$@$
