### ISSUE TITLE
[Feature Request] Select, DatePicker, Tooltip etc. need a property 'modal-append-to-body' to control the Dom's position

### ISSUE THREAD

**Issue by fuybooo** [ElemeFE/element#20972]
### Existing Component
是

### Component Name
Select

### Description
在全屏模式下，无法Select和DatePicker等选择器无法使用，因为其弹出的内容是默认插入到body元素，这会被全屏元素遮挡。若使用:modal-append-to-body="false"，则插入的dom会在全屏的结构内，这样就能显示了。

**Comment by fuybooo** [comment]
全屏时，将body全屏即可

**Comment by Tehsurfer** [comment]
Is this resolved? I'm having the same issue where there is no `append-to-body` attribute for element-ui tooltip.

**Comment by wym90522** [comment]
并未把body全屏，而是把body下的某个div进行了全屏，依然需要一些处理办法
