### ISSUE TITLE
can i close keyboard shortcuts when using radio component 

### ISSUE THREAD

**Issue by liujinxiao** [ElemeFE/element#20997]
can i close keyboard shortcuts when using radio component , thanks

**Comment by liujinxiao** [comment]
请问，使用radio标签时能将左右上下的快捷键切换radio功能关掉吗

**Comment by cs1707** [comment]
This is not a bug of ElementUI. It's the default behavior of browser.  You can try `<el-radio @keydown.native.stop.prevent>`
