### ISSUE TITLE
[Bug Report] '$isServer' error in vite 2.3.2

### ISSUE THREAD

**Issue by qwfy5287** [ElemeFE/element#21005]
### Element UI version
2.15.1

### OS/Browsers version
mac,chrome

### Vue version
2.6.12

### Reproduction Link
https://github.com/qwfy5287/vue-admin-template-vite

### Steps to reproduce
yarn dev

### What is Expected?
not error

### What is actually happening?
Uncaught TypeError: Cannot read property '$isServer' of undefined

**Comment by LauJon** [comment]
我也遇到了这个问题  ，应该是vite不支持require方式，应该用vue3版本  element-plus ，目前不想换element-plus改动太大。不知道官方有没有解决办法，兼容

**Comment by qwfy5287** [comment]
@LauJon 
vite v2.1.5 是可以的，不清楚改了的什么。

**Comment by pasBone** [comment]
有解決办法请踢我一下

**Comment by Rainmen-xia** [comment]
element-ui官方出一个es版本大家就不会这么难受了

**Comment by Yuliang-Lee** [comment]
应该是因为 https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#breaking-changes

**Comment by qwfy5287** [comment]
@LauJon @pasBone @Rainmen-xia @Yuliang-Lee 

找到方法解决了
## 插件
https://github.com/dravenww/esbuild-plugin-vite-element-ui

## 示例
https://github.com/qwfy5287/vite-element-ui-example

**Comment by LauJon** [comment]
> @LauJon @pasBone @Rainmen-xia @Yuliang-Lee
> 
> 找到方法解决了
> 
> ## 插件
> https://github.com/dravenww/esbuild-plugin-vite-element-ui
> 
> ## 示例
> https://github.com/qwfy5287/vite-element-ui-example

没有起作用 更新了最新的Vite 2.3.5也不行

**Comment by qwfy5287** [comment]
> > @LauJon @pasBone @Rainmen-xia @Yuliang-Lee
> > 找到方法解决了
> > ## 插件
> > https://github.com/dravenww/esbuild-plugin-vite-element-ui
> > ## 示例
> > https://github.com/qwfy5287/vite-element-ui-example
> 
> 没有起作用 更新了最新的Vite 2.3.5也不行

我把 vite 锁定在 2.2.4， 大于 2.3.0 的可用 element-ui-es，看下这边

https://github.com/dravenww/esbuild-plugin-vite-element-ui/issues/1

**Comment by lovetingyuan** [comment]
> element-ui官方出一个es版本大家就不会这么难受了

属实拉垮 没人维护了吧

**Comment by qwfy5287** [comment]
新版的vite解决问题了

fix: 升级到 vite v2.3.7, esbuild v0.12.7 for esm compatibility; 去掉 esbuild-plugin-vite-element-ui

示例
https://github.com/qwfy5287/vue-admin-template-vite

**Comment by LauJon** [comment]
@qwfy5287 谢谢分享
