### ISSUE TITLE
The El input component is missing the enter event

### ISSUE THREAD

**Issue by hnpvqve** [ElemeFE/element#21010]
当我们在输入完成时，按回车所执行的事件，一般用在像搜索，登录时，输入完成后按回车，自动执行搜索事件。

**Comment by weidehai** [comment]
![Uploading image.png…]()

**Comment by weidehai** [comment]
![image](https://user-images.githubusercontent.com/25458528/118401734-6541e180-b699-11eb-8fa5-a249a603123a.png)

**Comment by cs1707** [comment]
`@keydown.native.enter="doWhatYouWant"`
