### ISSUE TITLE
[Bug Report] When I use two el-tables in the same component, adding the render-header attribute to the el-table-column of one el-table will affect the other el-table

### ISSUE THREAD

**Issue by qianqikun** [ElemeFE/element#21016]
### Element UI version
2.13.0

### OS/Browsers version
macOS Big Sur 11.1/chrome 90.0.4430.212

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/atom0827/pen/oNZZzgX

### Steps to reproduce
When I use two el-tables in the same component, adding the render-header attribute to the el-table-column of one el-table will affect the other el-table

### What is Expected?
Normally displayed in the list that does not use render-header

### What is actually happening?
When I use two el-tables in the same component, adding the render-header attribute to the el-table-column of one el-table will affect the other el-table

**Comment by JerryYuanJ** [comment]
@qianqikun It just reuses the existing same component. Here're 2 options to solve this:
1. Adding different keys to `el-table` components
2. Move one table to another block, make sure they are not siblings of one same parent.

Hope this can help you.
