### ISSUE TITLE
[bug report] binding model attribute to the form in JSX, reporting invalid handler for event "input": got undefined found in < elform > at packages / form / SRC / form.vue and form validation error.

### ISSUE THREAD

**Issue by jackchoumine** [ElemeFE/element#21013]
### Element UI version
2.15.1

### OS/Browsers version
os: mac os big sur 11.31  chorme:  90.0.4430.212（正式版本） (x86_64)

### Vue version
2.6.12

### Reproduction Link
https://codesandbox.io/s/solitary-platform-82lgm?file=/src/components/MyForm.jsx

### Steps to reproduce

打开项目链接 MyForm.jsx 即可重现

my code:
```js
export default {
  name: 'MyForm',
  data() {
    return {
      innerFormData: { input: '' },
      innerRules: { input: [{ required: true, message: '请输入手机号', trigger: 'blur' }] },
    }
  },
  render() {
    return (
      <div>
        <el-form model={this.innerFormData} rules={this.innerRules}>
              <el-form-item label='单行输入' prop='input'>
                <el-input vModel={this.innerFormData.input} />
              </el-form-item>
        </el-form>
      </div>
    )
  },
}
```
error :
```bash
 Invalid handler for event "input": got undefined

found in

---> <ElForm> at packages/form/src/form.vue
```
and rules dont work.
### What is Expected?
能在 render 函数渲染表单。

### What is actually happening?
 [Vue warn]: Invalid handler for event "input": got undefined

found in

---> <ElForm> at packages/form/src/form.vue

并且验证不生效。

**Comment by cs1707** [comment]
`<el-form model={this.innerFormData} rules={this.innerRules}>` -> `<el-form props={{model: this.innerFormData}} rules={this.innerRules}>` can solve this problem. 
ref: https://github.com/vuejs/jsx/issues/49#issuecomment-472013664
