### ISSUE TITLE
[bug report] rasterization is not easy to use, so that it will not be displayed normally (EL row, El Col)

### ISSUE THREAD

**Issue by popring** [ElemeFE/element#21033]
### Element UI version
2.15.2

### OS/Browsers version
windows/mac 均会出现

### Vue version
2.6.11

### Reproduction Link
https://codesandbox.io/s/elementui-row-col-bujubug-mhbmw?file=/src/components/index.vue

### Steps to reproduce
当超过一行时就会显示有问题（使用flex没有此问题）

### What is Expected?
按照顺序排列下来

### What is actually happening?
第二行的元素似乎多了些 offset（这些我并没有添加）
![image](https://user-images.githubusercontent.com/31247906/119967521-022c4500-bfdf-11eb-9eda-04a287e1b937.png)
Picture text：It seems that the offset is added here (but I did not use the offset)

**Comment by cs1707** [comment]
This is not a bug of element-ui; it occurs because the fourth element is smaller than the previous one, which is the default behavior of `float`. You should set the same height for each element.

**Comment by popring** [comment]
> This is not a bug of element-ui; it occurs because the fourth element is smaller than the previous one, which is the default behavior of `float`. You should set the same height for each element.

Thank you very much for clearing up the confusion.
