### ISSUE TITLE
nuxt.js上使用element1.1.1样式上有bug

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/element#2103]
### ElementUI version
1.1.1

### OS/Browers version
macOS/Chrome 53

### Vue version
2.1.8

**Comment by yuchonghua** [comment]
![image](https://cloud.githubusercontent.com/assets/17898715/21560180/c089fe42-ce95-11e6-921a-dfa2e9c45f40.png)
![image](https://cloud.githubusercontent.com/assets/17898715/21560187/ccb3b9d8-ce95-11e6-955c-5775909d2b02.png)

**Comment by yuchonghua** [comment]
![image](https://cloud.githubusercontent.com/assets/17898715/21560390/8ffdbdb4-ce99-11e6-8719-91f997e42ee3.png)

**Comment by yuchonghua** [comment]
其实我发现不是ssr问题，是本身客户端渲染也有问题

**Comment by QingWei-Li** [comment]
@yuchonghua fixed via https://github.com/ElemeFE/element/pull/2112
