### ISSUE TITLE
【upload】在beforeUpload钩子中，如何重新设置上传的路径与额外的data数据

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#2104]
在目前的组件中，beforeUpload，只有上传文件的数据
目前的场景是这样：
上传的文件的时候，服务器地址是未知的，每次上传文件都要去专门的文件服务器得到上传的地址，然后进行设置。beforeUpload中，去请求上传地址，成功后，设置upload组件的action值，但是发现上传时，action取的还是之前的值，不是当下设置的新值。请问该如何解决？

**Comment by baiyaaaaa** [comment]
把你的Promise resolve 语句放到 vm(upload).$nextTick(); 的回调里
```js
function beforeUpload(file) {
  return new Promise((resolve, reject) => {
    upload.action = 'new action';
    upload.$nextTick(_ => {
      resolve(file);
    });
  });
}
```
试试这样

**Comment by masterzhang** [comment]
但是文档中，不是说`若返回 false 或者 Promise 则停止上传。`
我目前是用heck直接调用组件的post方式

**Comment by hasbug** [comment]
@masterzhang 现在有好的解决办法了吗？

**Comment by ChanSimon** [comment]
@hasbug 我看了很多您对这个话题的回复发现您之前遇到的问题和我现在遇到的大致相同，能请教一下是怎么解决的嘛？
