### ISSUE TITLE
[Bug Report] Select Component does not blur on press of escape key

### ISSUE THREAD

**Issue by smg99** [ElemeFE/element#21051]
### Element UI version
2.15.2

### OS/Browsers version
Chrome Version 91.0.4472.77

### Vue version
2.6.14

### Reproduction Link
codepen.io?https://element.eleme.io/#/en-US/component/select

### Steps to reproduce
Goto https://element.eleme.io/#/en-US/component/select#basic-usage

Select basic dropdown - it will open dropdown
Press escape once - it will close dropdown
Press escape again - nothing happens

### What is Expected?
Goto https://element.eleme.io/#/en-US/component/select#basic-usage

Select basic dropdown - it will open dropdown
Press escape once - it will close dropdown
Press escape again - it should blur select (similar to what is does for other components like input, datepicker, datetime picker)

### What is actually happening?
Goto https://element.eleme.io/#/en-US/component/select#basic-usage

Select basic dropdown - it will open dropdown
Press escape once - it will close dropdown
Press escape again - nothing happens

**Comment by cs1707** [comment]
Default browser behavior
