### ISSUE TITLE
[bug report] is there a bug in the resetfields of the form?

### ISSUE THREAD

**Issue by Aizener** [ElemeFE/element#21072]
### Element UI version
2.15.2

### OS/Browsers version
Google Chrome 版本 91.0.4472.77（正式版本） （64 位）

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/_Cola/pen/XWMyJGE?editors=1111

### Steps to reproduce
关于Form表单的resetFields方法按文档解释应为：对整个表单进行重置，将所有字段值重置为初始值并移除校验结果。
重现步骤：
1. 创建Form表单和Input，并绑定model以及给input双向绑定的值；
2. 使用resetFields之前，重新赋值model（修改引用）；
3. 发现resetFields修改的是重新赋值的model，打印this.$refs.form.model，发现是之前的。
备注：在resetFields外面嵌套一层异步的话，发现就没问题了，这算是Bug？虽然，这个问题，能正合我意，重置表单，但是感觉与文档描述功能不一致。

### What is Expected?
打印的model是原始的，应该resetFields也为原始的。

### What is actually happening?
打印的model是原始的，resetFields是修改之后的。

**Comment by cs1707** [comment]
```
resetForm2() {
    this.user = {
      username: ''
    }
    this.$nextTick(() => {
      this.$refs.form.resetFields()
      console.log(JSON.stringify(this.$refs.form.model))
    })
  }
```
ref: https://cn.vuejs.org/v2/api/#Vue-nextTick
