### ISSUE TITLE
[Bug Report] Unknown custom element with elRadioGroup using component tag

### ISSUE THREAD

**Issue by kooriookami** [ElemeFE/element#21077]
### Element UI version
2.15.2

### OS/Browsers version
chrome91

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/kooriookami/pen/GRWPaLZ

### Steps to reproduce
watch the console, there is an error.
![image](https://user-images.githubusercontent.com/38392315/122160818-32ab2480-cea3-11eb-8209-ccd4431e3f7c.png)

**Comment by wangdaodao** [comment]
https://github.com/ElemeFE/element/pull/20783

**Comment by cs1707** [comment]
fixed
