### ISSUE TITLE
[Bug Report] lazy tree can not relaod non-leaf node data

### ISSUE THREAD

**Issue by yinyihui** [ElemeFE/element#21081]
### Element UI version
2.15.2

### OS/Browsers version
Windows 10

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/yinyihui/pen/oNZmddG

### Steps to reproduce
expand second level node zone

### What is Expected?
expand second level node zone and then we can relaod zone data when now is not empty

### What is actually happening?
expand second level node zone and then cannot relaod zone data when now is not empty

 I read the tree component code and findout the following code in file packages/tree/src/model/node.js:

https://github.com/ElemeFE/element/blob/75290629aec56e685692296bdb9fe8d957a2e832/packages/tree/src/model/node.js#L343

the prop isLeaf is not considering user's isLeaf configuration when lazy loaded with empty children, that is not correct!

**Comment by cs1707** [comment]
Reload is not supported
