### ISSUE TITLE
[bug report] Max height dynamic update table is not displayed

### ISSUE THREAD

**Issue by wxlaionangog** [ElemeFE/element#21086]
### Element UI version
2.15.2

### OS/Browsers version
chrome / ios / edge / android

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/wxlaionangog/pen/wvJOewW

### Steps to reproduce
使用最新版本(2.15.2)element-ui 版本的el-table 设置max-height 为变量动态更新, 表格实际高度已经更新, 但是表格外壳高度没有动态更行max-height 仍为0 导致表格无法正常显示

### What is Expected?
预期el-table max-height 正常生效表格正常展示

### What is actually happening?
实际上max-height 没有动态更新导致表格整体不展示

**Comment by cs1707** [comment]
Try this
```
 this.$nextTick(() => {
      this.tableHeight = window.innerHeight - 36;
 })
```
