### ISSUE TITLE
[form,select]表单验证中select控件的错误提示问题

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#2109]
操作情况如下：
1、select设置filterable和clearable，我开始敲键盘，就出现错误提示，其实这倒是小问题，如图：
![1](https://cloud.githubusercontent.com/assets/12726826/21560687/b4155c76-ce9d-11e6-9728-9a08f32560dd.png)
2、其实我再输入的过程中就会触发change事件，你们的change事件和vue的不一样，vue是失焦后才出发的，demo：https://jsfiddle.net/50wL7mdz/7734/，关键了的来了，我输入“区域一”，下拉选项也有一个“区域一”，“区域一” == “区域一”，我点击下拉中的“区域一”，这时候是不会触发change的，因为还是select中input还是“区域一”这个值，所以还会有错误提示，如图：
![2](https://cloud.githubusercontent.com/assets/12726826/21560726/3933807c-ce9e-11e6-9ed2-79fd686c0b6a.png)
![3](https://cloud.githubusercontent.com/assets/12726826/21560727/3a4f6af2-ce9e-11e6-81f3-e3550e70ae10.png)

希望能修复下，还有如果可以解释下为啥你们的@change和vue的@change为什么不一样那也是非常感谢！
附上demo：http://jsfiddle.net/f98rgbqe/2/

**Comment by Leopoldthecoder** [comment]
已在 #2120 修复。

之前的 Select 的 `change` 事件是由里面的 Input 代理的，那么随着你输入搜索条件，Input 的值不断在变化，也就不断在触发 `change` 事件。

现在改为由 Select 自身触发 `change`，只有当 Select 的值真正发生变化的时候才会触发。
