### ISSUE TITLE
今天（2016-12-30） 新搭建环境 ，el-date-picker

### ISSUE THREAD

**Issue by alvin198761** [ElemeFE/element#2111]
今天新搭建的环境 ，用到了时间控件，但是报错，内容：
vue.common.js?e881:521 [Vue warn]: existing instance property "haveTrigger" will be overwritten by a computed property with the same name. 
(found in component <ElDatePicker>)
我只写一个简单的界面，就一个控件，还是这个错，首先声明，我没有定义  haveTrigger 这个变量，也没有修改他，就是放一个控件而已，我测试了其他几个 时间范围，时间，日期，的控件，都有这个问题，难道是我的版本用的太新？

**Comment by QingWei-Li** [comment]
太旧了
