### ISSUE TITLE
[Bug Report] When there are too many El tabs in the el-tabs component, there is no difference button style between the valid and invalid states when clicking the left and right paging buttons

### ISSUE THREAD

**Issue by jarry-hub** [ElemeFE/element#21116]
### Element UI version
2.15.3

### OS/Browsers version
windows10/Google Chrome  91.0.4472.124

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/jarry-hub/pen/xxdwVPW

### Steps to reproduce
Click the left and right paging buttons of el-tabs to view the button style

### What is Expected?
there is a difference button style between the valid and invalid states when clicking the left and right paging buttons

### What is actually happening?
there is no difference button style between the valid and invalid states when clicking the left and right paging buttons

**Comment by xubiu** [comment]
你把他们的name值给为不一样的就好了
