### ISSUE TITLE
[Bug Report] After the filterable is added to the Select component, the drop-down box cannot be collapsed by clicking the arrow

### ISSUE THREAD

**Issue by water7322** [ElemeFE/element#21117]
### Element UI version
2.15.3

### OS/Browsers version
macOS Catalina 10.15.7 / Chrome 91.0.4472.114

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=12210400-8765-4b0a-9eae-f0086b076687

### Steps to reproduce
Adding filterable to el-select.
Click the expand arrow.
Click the collapse arrow.

### What is Expected?
The drop-down box can be expanded and collapsed

### What is actually happening?
The drop-down box can be expanded, can not be collapsed

**Comment by kuzroman** [comment]
have the same issue
reproduce can in your component guide
https://element.eleme.io/#/en-US/component/select
scroll to - Option filtering
open select options and try to close it clicking by arrow Up
![image](https://user-images.githubusercontent.com/6120821/125245522-57a38380-e2f9-11eb-8f0f-5f67d025e65c.png)
