### ISSUE TITLE
[Bug Report] When the default value of El select is set, the label is displayed as value

### ISSUE THREAD

**Issue by CorgiSYJ** [ElemeFE/element#21130]
### Element UI version
2.15.3

### OS/Browsers version
win10 / chrome

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/CorgiSYJ/pen/GRmqRNL

### Steps to reproduce
When the El select is still loading, click El select and wait for the default value to be displayed. The result shows value instead of label

### What is Expected?
Display label

### What is actually happening?
Display value

**Comment by cs1707** [comment]
use `this.$nextTick` can solve this problem
