### ISSUE TITLE
table控件直接用官方demo样式有问题

### ISSUE THREAD

**Issue by kfqkfy** [ElemeFE/element#2113]
![image](https://cloud.githubusercontent.com/assets/2724562/21561142/a1a4b202-cea3-11e6-944a-38c8ba9b0145.png)

demo
http://jsfiddle.net/bpLhyx5p/

**Comment by QingWei-Li** [comment]
fixed via #2112

**Comment by furybean** [comment]
@QingWei-Li 这个 PR 不是 DatePicker 么？

**Comment by QingWei-Li** [comment]
@furybean 哦 贴错了 #2096

**Comment by luckymore** [comment]
@kfqkfy 
![image](https://cloud.githubusercontent.com/assets/5390013/21561660/8dcf4948-ceaa-11e6-9137-028ce6512dc9.png)
你用的什么浏览器啊，我这chrome正常啊

**Comment by kfqkfy** [comment]
chrome
版本 54.0.2840.98 (64-bit)
@luckymore
