### ISSUE TITLE
[Feature Request] For each component, add a component spin for loading

### ISSUE THREAD

**Issue by zhuxiujia** [ElemeFE/element#21137]
### Existing Component
yes

### Component Name
For each component, add a component spin for loading

### Description
For each component, add a component spin for loading.
Components often load data from the network, including SELECT components, INPUT components, buttons, trees, lists, tables, just about anything

**Comment by cs1707** [comment]
Use custom directive `v-loading`. ref: https://element.eleme.io/#/en-US/component/loading
