### ISSUE TITLE
[bug report] when the form content has no value, when calling the resetfields method of El form, the elements under El form item cannot be entered

### ISSUE THREAD

**Issue by zxyah** [ElemeFE/element#21148]
### Element UI version
2.15.3

### OS/Browsers version
macOS Catalina 10.15.7/chrome 91.0.4472.114

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/zxyah/pen/zYwZNOX?editors=1111

### Steps to reproduce
直接点击重置按钮，表单内的input就不可以输入了。
如果先输入字符，然后在点击重置按钮，是正常的。

### What is Expected?
重置之后，还可以正常输入

### What is actually happening?
直接点击重置按钮，表单内的input就不可以输入了。

**Comment by shaolongwendd01** [comment]
要初始化好的表单数据字段
formVal: {
        userName: '',
        password: ''
},

**Comment by shaolongwendd01** [comment]
要初始化好表单数据字段
formVal: {
  userName: '',
  password: ''
},

**Comment by dongshansheng** [comment]
不初始化字段重置之后，vue2检测form对象的变化了，视图没有更新，提交会提交你按下的第一个字符。
