### ISSUE TITLE
[bug report] El table does not support additional rows

### ISSUE THREAD

**Issue by lijianmincn** [ElemeFE/element#21149]
### Element UI version
2.15.3

### OS/Browsers version
win10

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/ziyoung/pen/rRKYpd/x

### Steps to reproduce
<el-table :data="tableData" style="width: 100%">
 <template>
 <div>这里是需要插入的一行，但是不显示</div>
 </template>

 <el-table-column prop="id" label="序列" width="60"></el-table-column>
 <el-table-column prop="name" label="name"></el-table-column>
 <el-table-column label="图片">
 <template slot-scope="scope">
 <img :src="scope.row.img" alt style="height:80px" />
 </template>
 </el-table-column>
 <el-table-column prop="des" label="描述"></el-table-column>
 <el-table-column prop="color" label="颜色"></el-table-column>
 <el-table-column prop="unit_price" label="单价"></el-table-column>
 <el-table-column prop="discount" label="数量"></el-table-column>
 <el-table-column label="总价"></el-table-column>
 </el-table>

### What is Expected?
可以支持额外添加行，或者对行的控制。如 <table><tr></tr></table>
参考地址：https://zhuanlan.zhihu.com/p/137148688

### What is actually happening?
遍历一行数据，要展示4行，只有一个列值不一样

**Comment by cs1707** [comment]
The el-table does not support this feature. I don't think it is a universal use case.
