### ISSUE TITLE
[Bug Report] change select style

### ISSUE THREAD

**Issue by Richard0323** [ElemeFE/element#21150]
### Element UI version
2.15.3

### OS/Browsers version
chrome 91

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/td231565/pen/QWvpvyG?editors=1111

### Steps to reproduce
modify select class
.el-select {
  border: none;
}

### What is Expected?
the select box has no border

### What is actually happening?
it still has

**Comment by shaolongwendd01** [comment]
使用.el-input__inner {
  border: none;
}

**Comment by shaolongwendd01** [comment]
.el-input__inner {
  border: none;
}

**Comment by Richard0323** [comment]
Thanks!!
