### ISSUE TITLE
[Bug Report]The generated CSS file is generated according to the old version of the CSS file

### ISSUE THREAD

**Issue by Undefined100** [ElemeFE/element#21166]
Element UI version
2.15.3

OS/Browsers version
win10 chrome 88

Vue version
2.6.13

Reproduction Link
https://element.eleme.cn/2.15/#/zh-CN/theme/preview

Steps to reproduce
主题下载，生成的css文件是根据旧版本的css文件来生成

What is Expected?
主题下载生成的css文件，应该根据最新版本的css来生成，最好能选择对应版本来生成

What is actually happening?
主题下载，生成的css文件是根据旧版本的css文件来生成

**Comment by cs1707** [comment]
fixed
