### ISSUE TITLE
中文官方文档-更新日志404

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2116]
uri:  [点我](http://element.eleme.io/zh-CN/component/changelog)

**Comment by lincenying** [comment]
https://github.com/ElemeFE/element/blob/dev/CHANGELOG.zh-CN.md

**Comment by PanJiaChen** [comment]
![image](https://cloud.githubusercontent.com/assets/8121621/21561747/c01cfe76-ceab-11e6-8f56-b2ae9dce613c.png)
我指这里的链接地址写错了。。。

**Comment by lincenying** [comment]
这是在框架里的, 不要用新窗口打开, 直接点击链接

**Comment by Leopoldthecoder** [comment]
是，不要在新窗口打开。
