### ISSUE TITLE
Select component in the [bug report] table does not refresh

### ISSUE THREAD

**Issue by Montaro2017** [ElemeFE/element#21177]
### Element UI version
2.15.3

### OS/Browsers version
Windows 10

### Vue version
2.6.14

### Reproduction Link
https://jsfiddle.net/qor7fcwg/5/

### Steps to reproduce
表格内添加El-Select组件并绑定数据

### What is Expected?
选择选项后表格内Select组件显示选择的值

### What is actually happening?
选择选项后表格内Select组件数据无法正确显示

**Comment by oppnys** [comment]
You can write like this

```
<el-table-column>
    <template slot-scope="{row}">
          <el-select v-model="selectValue">
             <el-option v-for="i in 4" :key="i" :label="'Option'+i" :value="i"></el-option>
          </el-select>
    </template>
</el-table-column>
```

**Comment by Montaro2017** [comment]
> You can write like this
> 
> ```
> <el-table-column>
>     <template slot-scope="{row}">
>           <el-select v-model="selectValue">
>              <el-option v-for="i in 4" :key="i" :label="'Option'+i" :value="i"></el-option>
>           </el-select>
>     </template>
> </el-table-column>
> ```



> 你可以这样写
> 
> ```
> <el-table-column>
>     <template slot-scope="{row}">
>           <el-select v-model="selectValue">
>              <el-option v-for="i in 4" :key="i" :label="'Option'+i" :value="i"></el-option>
>           </el-select>
>     </template>
> </el-table-column>
> ```
Thanks,it works, but if I don't use "row", my editor will prompt me with an error.

**Comment by Montaro2017** [comment]
> You can write like this
> 
> ```
> <el-table-column>
>     <template slot-scope="{row}">
>           <el-select v-model="selectValue">
>              <el-option v-for="i in 4" :key="i" :label="'Option'+i" :value="i"></el-option>
>           </el-select>
>     </template>
> </el-table-column>
> ```

Thanks,It works, but if I don't use "row", my editor will prompt me with an error
