### ISSUE TITLE
[bug report] El cascade when emitpath is set to false. When the current selected content value is 0. Echo content is empty

### ISSUE THREAD

**Issue by menglimu** [ElemeFE/element#21179]
### Element UI version
2.15.3

### OS/Browsers version
win10 / Chrome 91

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/menglimu/pen/QWvOLQR

### Steps to reproduce
选择下拉中的第一个选项 '一致' 时，此时回显为空，选其他值正常

### What is Expected?
回显出 label 一致

### What is actually happening?
回显为空

**Comment by shaolongwendd01** [comment]
value:'0'
