### ISSUE TITLE
[Bug Report] cannot edit el-input in v-for

### ISSUE THREAD

**Issue by icebound47** [ElemeFE/element#21184]
### Element UI version
2.15.3

### OS/Browsers version
macOS Big Sur 11.2.3/Google Chrome 91.0.4472.114

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/icebound47/pen/LYyQGoK

### Steps to reproduce
1. select table data
2. edit el-input
选择表格数据后编辑el-input

### What is Expected?
edit default value in el-input;
可以改变el-input中的默认值

### What is actually happening?
cannot edit default value in el-input;
el-input 的值并不可以编辑，当前绑定的值也没有生成getter、setter
input 的值可以编辑

**Comment by xxl-ghca** [comment]
你这个怕不是个问题，主要是age没有在初识化的时候声明，没有响应化。

**Comment by icebound47** [comment]
> 你怕不是这个问题，主要是年龄没有在初识化的时候声明，没有响应化。

我想说的是，初始化虽然没有声明但是源生的input是可以编辑的，只有el-input不能编辑。


关于初识化声明的问题，有些复杂的业务场景下有些动态数据还是无法声明的，例子中的table数据如果是从后台请求的就无法声明了。
vue的$set 可以生成getter,setter但是如下代码结合示例也是不生效的，这个问题我会反馈到vue
selectData(a) {
      // a.age = 18;
      // this.list.push(a);
      a.age = 18;
      this.$set(this.list, this.list.length, a);
      console.log(this.list);//  a对象中的age并没有被监听
    },

**Comment by icebound47** [comment]
我想说的是，初始化虽然没有声明但是源生的input是可以编辑的，只有el-input不能编辑。




关于初识化声明的问题，有些复杂的业务场景下有些动态数据还是无法声明的，例子中的table数据如果是从后台请求的就无法声明了。
vue的$set 可以生成getter,setter但是如下代码结合示例也是不生效的，这个问题我会反馈到vue
selectData(a) {
&nbsp; &nbsp; &nbsp; // a.age = 18;
&nbsp; &nbsp; &nbsp; // this.list.push(a);
&nbsp; &nbsp; &nbsp; a.age = 18;
&nbsp; &nbsp; &nbsp; this.$set(this.list, this.list.length, a);
&nbsp; &nbsp; &nbsp; console.log(this.list);//&nbsp; a对象中的age并没有被监听
&nbsp; &nbsp; },





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月27日(星期二) 下午2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ElemeFE/element] [Bug Report] cannot edit el-input in v-for (#21184)





 
你这个怕不是个问题，主要是age没有在初识化的时候声明，没有响应化。

**Comment by cs1707** [comment]
use `this.$set(a, 'age', 18)` 

ref: 
* https://codepen.io/cs1707/pen/WNjMpdo
* https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by icebound47** [comment]
Still can't edit value




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月27日(星期二) 晚上7:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ElemeFE/element] [Bug Report] cannot edit el-input in v-for (#21184)





 
use this.$set(a, 'age', 18)
 
ref:
  
https://codepen.io/cs1707/pen/WNjMpdo
 
https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by icebound47** [comment]
> use `this.$set(a, 'age', 18)`
> 
> ref:
> 
> * https://codepen.io/cs1707/pen/WNjMpdo
> * https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

Still can't edit value

**Comment by cs1707** [comment]
use `v-model=` instead of `:value=`
