### ISSUE TITLE
[bug report] quickly switching the v-loading state will trigger the click event of the current element

### ISSUE THREAD

**Issue by LiuYuLu** [ElemeFE/element#21188]
### Element UI version
2.15.3

### OS/Browsers version
Microsoft Edge 版本 92.0.902.55 (官方内部版本) (x86_64)

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/JadeLiu/pen/XWRZObx

### Steps to reproduce
快速切换v-loading状态，会触发当前元素的click事件

### What is Expected?
不要触发click事件

### What is actually happening?
触发click事件

**Comment by wangfpp** [comment]
遇到了给el-button加上v-loading会有事件击穿的情况
```js
<el-button v-loading="true" @click="triiggerEvent"></el-button>
此时triiggerEvent还是可以触发的
```

**Comment by cs1707** [comment]
use `:loading` props
