### ISSUE TITLE
[Bug Report] ElNotification.closeAll() | this.$notify.close() not a function

### ISSUE THREAD

**Issue by thamibn** [ElemeFE/element#21182]
### Element UI version
2.15.3

### OS/Browsers version
chrome

### Vue version
2.6.14

### Reproduction Link
https://codesandbox.io/s/busy-glade-t4x6c?file=/src/App.vue

### Steps to reproduce
creted notifications but cannot close them manually by calling ```ElNotification.closeAll() | this.$notify.close() ```
so this results to same notifications shown multiple times instead of one per time.

### What is Expected?
to close all notifications before showing new ones

### What is actually happening?
throws an error 

Layout.vue?f926:42 Uncaught (in promise) TypeError: this.$notify.close is not a function

**Comment by cs1707** [comment]
For element-plus please submit an issue here https://github.com/element-plus/element-plus/issues
