### ISSUE TITLE
表单验证 不能验证 number,float类型呢。，官方示例也是一样的，type:'number'无法验证

### ISSUE THREAD

**Issue by youthour** [ElemeFE/element#2118]
表单验证 不能验证 number,float类型呢。，官方示例也是一样的，type:'number'无法验证
最新的1.1.1版本也是

**Comment by Leopoldthecoder** [comment]
绑定了你需要验证的字段的 `v-model` 要加 `.number` 修饰符：`v-model.number="someProp"`

**Comment by lincenying** [comment]
建议用正则来判断, 不要直接验证类型, .number 更是不可取, 位数短还可以, 位数长会变成 xxxE, 导致通不过验证
