### ISSUE TITLE
NaviMenu中的select相关方法未定义

### ISSUE THREAD

**Issue by Ka-chanNi** [ElemeFE/element#212]
### ElementUI version
 1.0.0-rc.5

### OS/Browers version
 macOS/Chrome 53 

### Vue version
 2.0.1 

### Steps to reproduce
使用webpack和vue-cli搭建脚手架并导入Element UI，App.vue中使用了官网中的顶栏代码
```html
<el-menu default-active="1" class="el-menu-demo" mode="horizontal" @select="handleselect">
  <el-menu-item index="1">处理中心</el-menu-item>
  <el-submenu index="2">
    <template slot="title">我的工作台</template>
    <el-menu-item index="2-1">选项1</el-menu-item>
    <el-menu-item index="2-2">选项2</el-menu-item>
    <el-menu-item index="2-3">选项3</el-menu-item>
  </el-submenu>
  <el-menu-item index="3">订单管理</el-menu-item>
</el-menu>
```

### What is actually happening?
vue-debugger报错，handleselect未定义。
![image](https://cloud.githubusercontent.com/assets/7496084/19019019/02957af6-88a9-11e6-8cb9-12e681ed5520.png)

**Comment by Leopoldthecoder** [comment]
`handleselect` 需要你自己定义。
