### ISSUE TITLE
[Bug Report] Document content error

### ISSUE THREAD

**Issue by uyoungco** [ElemeFE/element#21215]
### Element UI version
2.13.2

### OS/Browsers version
mac os/11.4

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/

### Steps to reproduce
https://element.eleme.io/#/zh-CN/component/popconfirm

doc
Events
confirm
cancel

code
onConfirm
onCancel

### What is Expected?
none

### What is actually happening?
none

**Comment by maopixin** [comment]
I have the same problem，The document is not as good as Baidu。
