### ISSUE TITLE
表单无法提交

### ISSUE THREAD

**Issue by sandysong** [ElemeFE/element#2121]
之前提的issue被关了，重新提一个
1.0.9及之后版本有问题
1.0.8无问题
可以看下：http://codepen.io/anon/pen/XNvyya

**Comment by baiyaaaaa** [comment]
![image](https://cloud.githubusercontent.com/assets/3655403/21563373/b0512222-cebc-11e6-8cfc-37dfae616bfe.png)
自定义验证通过时也要调用callback
