### ISSUE TITLE
[bug report] too many calculations in the cascaded form cause the scrolling to get stuck

### ISSUE THREAD

**Issue by changeLong** [ElemeFE/element#21223]
### Element UI version
2.15.5

### OS/Browsers version
window10/node 14

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=78731dc4-107d-4c29-9ef3-6286d71da51f

### Steps to reproduce
级联元素插入到body时，就开始监听页面滚动，设置位置，导致页面卡顿

### What is Expected?
级联不展示时，不应该计算级联位置

### What is actually happening?
级联不展示时，计算级联位置，导致页面滚动卡顿

<img src="https://ruqi-img.ruqimobility.com/pic_image/20210812063814__9SJH16OH.gif" />

**Comment by changeLong** [comment]
感激！我之前是在本地二次开发修复了，没想到这么快就有响应了，错过了一个提PR的好机会；

**Comment by XKF** [comment]
Nice！用的旧版本刚想来提这个issue，然后发现官网最新版解决了
