### ISSUE TITLE
希望树形控件能有个方法返回所有的节点

### ISSUE THREAD

**Issue by lijunwan** [ElemeFE/element#2123]
### ElementUI version

1.9.0
### What is Expected?
希望树形控件能有个方法返回所有的节点
### What is actually happening?
我有个需求是要获取被选中的节点和其父节点，虽然通过filter可以实现，但是filter好像会重绘树，然后展开所有节点

**Comment by Leopoldthecoder** [comment]
可以使用 `getCheckedNodes`
