### ISSUE TITLE
[Bug Report] Radio's checked state not reset when go back from history

### ISSUE THREAD

**Issue by wrma** [ElemeFE/element#21247]
### Element UI version
2.15.5

### OS/Browsers version
Chrome 92.0.4515.159(x86_64)

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/wrma/pen/gOWVvgQ

### Steps to reproduce
1. Select any radio-button except the first one
2. Click link
3. Click browser’s back button

### What is Expected?
Radio's checked state reset to the first one

### What is actually happening?
Radio's checked state not reset

**Comment by wrma** [comment]
I find radio-button's active style is depend on the checked state like this:
![image](https://user-images.githubusercontent.com/29309285/130195483-50aac426-e33e-4db3-872d-ee1c03f07a40.png)

but browser will cache the 'checked' status, this solution add `autocomplete="off"` on the input
https://stackoverflow.com/questions/37933043/reset-checkbox-checked-state-go-back-from-history

or can active style becomes data driven instead of relying on the native checked status?

**Comment by lemon-tree-sheng** [comment]
+1
