### ISSUE TITLE
select 组件的clearable 能否传替参数，比如传当前select组件的某个属性

### ISSUE THREAD

**Issue by weiyujia** [ElemeFE/element#2127]
select 组件的clearable 能否传替参数，比如传当前select组件的某个属性？或者将clearable写成一个事件，比如 @clearable ？，直接通过@change监听的话只能拿到一个空值参数，小弟不才，大神们多多指教,

**Comment by Leopoldthecoder** [comment]
可以传递参数，但必须是一个布尔值。

**Comment by weiyujia** [comment]
能不能拿到我清空的那些值啊？因为清空不仅仅只是将值不选中而已，@change 方法里面还有很多逻辑要写，需要某些在select组件里面自己定义的一些属性来处理逻辑。。。。比如我在select组件里绑定了一些自定义属性 :id 之类的，这个id和下拉框是一对多的关系，需要通过这个id来处理业务。。。。。

**Comment by Leopoldthecoder** [comment]
这个需求不应该和 `clearable` 属性结合。可以试试 `watch` 你 Select 的绑定值，然后在回调里处理相关逻辑。
