### ISSUE TITLE
[bug report] description row slot problem

### ISSUE THREAD

**Issue by bukeliyuchenmou** [ElemeFE/element#21285]
### Element UI version
2.15.5

### OS/Browsers version
mac big sur 11.5.2 / Google Chrome 92.0.4515.159

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/bukeliyuchenmou/pen/YzQqgjp

### Steps to reproduce
 ```javascript
 <el-descriptions-item >
                                <div {...{
                                    slot: "label"
                                }}>
                                    121213123
                                </div>
                                {this.list_data[i].create_at_str}
                            </el-descriptions-item>
```

### What is Expected?
我期望他的slot能够出现

### What is actually happening?
没有出现，我阅读完源码后，发现，作者已经把row这个的`props` 和`slot` 的`label` 都过滤完毕了，记录成了一个 `label` ，但是在默认的流程控制中，他却使用了 `item.props.label` , 这样的话如果不是有边框的描述列表和垂直排列的描述列表，他们的el-descriptions-item slot都用不了啦

**Comment by zhuxianbin** [comment]
Solved? ╮(╯▽╰)╭

**Comment by zhuxianbin** [comment]
手动打补丁
在 node_modules\element-ui\lib\descriptions.js 文件中,164行,加入以下代码
```
 if (item.vnode && item.vnode.data.scopedSlots.label) {
    item.label = item.vnode.data.scopedSlots.label();
 }
```

**Comment by ufologist** [comment]
在使用 `Descriptions` Item label slot 时, 只有设置 `Descriptions` 带边框时才会生效

```html
<el-descriptions border>
```

重现示例
https://codepen.io/ufologist/pen/GRvPOZv
