### ISSUE TITLE
[Bug Report] el-timeline timestamp wrong

### ISSUE THREAD

**Issue by WYmindsky** [ElemeFE/element#21294]
### Element UI version
2.15.3

### OS/Browsers version
chrome 70.0.3538.67

### Vue version
2.6.14

### Reproduction Link
http://my.github.com/sign_up_failed

### Steps to reproduce
data() {
      return {
        reverse: true,
        activities: [
          {
          content: '活动按期开始',
          timestamp: '2021-09-02 05:06:34'
        }, 
          {
          content: '活动按期开始',
          timestamp: '2021-09-02 02:07:20'
        }, 
          {
          content: '活动按期开始',
          timestamp: '2021-08-31 08:09:17'
        }, {
          content: '通过审核',
          timestamp: '2021-09-01 11:11:07'
        }, {
          content: '创建成功',
          timestamp: '2021-09-02 03:04:29'
        }]
      };
    }

### What is Expected?
活动按期开始
2021-09-02 05:06:34
创建成功
2021-09-02 03:04:29
活动按期开始
2021-09-02 02:07:20
通过审核
2021-09-01 11:11:07
活动按期开始
2021-08-31 08:09:17

### What is actually happening?
创建成功
2021-09-02 03:04:29
通过审核
2021-09-01 11:11:07
活动按期开始
2021-08-31 08:09:17
活动按期开始
2021-09-02 02:07:20
活动按期开始
2021-09-02 05:06:34

**Comment by liuning0406** [comment]
这个应该是8小时时差的问题，你试下 给组件加个  value-format="yyyy-MM-dd HH:mm:ss" 试试，可能会管用

**Comment by WYmindsky** [comment]
> 这个应该是8小时时差的问题，你试下 给组件加个 value-format="yyyy-MM-dd HH:mm:ss" 试试，可能会管用

我试着在el-timeline和el-timeline-item分别加上这个属性，排列效果没有变化

**Comment by liuning0406** [comment]
这个是你activities的排序问题吧，它是按for循环进行便利的，不会自动排序，因为你2021-08-31 08:09:17 在第三个，所以排序是第三个，你可以试一下重新排序，或者先排序再对activities赋值

**Comment by WYmindsky** [comment]
> 这个是你activities的排序问题吧，它是按for循环进行便利的，不会自动排序，因为你2021-08-31 08:09:17 在第三个，所以排序是第三个，你可以试一下重新排序，或者先排序再对activities赋值

那就是我理解错了，我以为会自动排序呢，多谢。

**Comment by liuning0406** [comment]
互相帮助，应该的
