### ISSUE TITLE
Conflict between vuei18n and vuex-i18n in $t function 

### ISSUE THREAD

**Issue by SaidTayebi** [ElemeFE/element#2129]
Element-UI now supports **vuei18n** and is checking if the function `$t` is used in `/element-ui/src/locale.index.js`
```
export const t = function(path, options) {
  const vuei18n = Object.getPrototypeOf(this || Vue).$t;
  if (typeof vuei18n === 'function') {
    if (!merged) {
      merged = true;
      Vue.locale(
        Vue.config.lang,
        deepmerge(lang, Vue.locale(Vue.config.lang) || {}, { clone: true })
      );
    }
    return vuei18n.apply(this, [path, options]);
  }
  const array = path.split('.');
  let current = lang;

  for (var i = 0, j = array.length; i < j; i++) {
    var property = array[i];
    var value = current[property];
    if (i === j - 1) return format(value, options);
    if (!value) return '';
    current = value;
  }
  return '';
};
```
I'm not using this package but I'm using `vuex-i18n` which also implements the same function `$t` thus this condition `if (typeof vuei18n === 'function')` is true and code inside fails because  it's checking the wrong library.

This causes the error: `TypeError: _vue2.default.locale is not a function` 

I think supporting `vuei18n` should be optionnal and not there by default

### ElementUI version
1.0.9

### Vue version
2.1.6

**Comment by desprit** [comment]
I'm using this exmaple from the docs:

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import Element from 'element-ui'
import enLocale from 'element-ui/lib/locale/lang/en'

Vue.use(VueI18n)
Vue.use(Element)

Vue.config.lang = 'zh-cn'
Vue.locale('en', enLocale)
```

and getting `_vue2.default.locale is not a function`
element-ui: 1.1.6
vue: 2.1.8

Isn't it the right way to do it?

**Comment by Leopoldthecoder** [comment]
@desprit try changing `Vue.config.lang = 'zh-cn'` to `Vue.config.lang = 'en'`

**Comment by desprit** [comment]
@Leopoldthecoder 

Thank you for your response. I was able to make this work. Changed to `Vue.config.lang = 'en'` and also fixed order of commands (I had `Vue.use(VueI18n)` at the bottom).
