### ISSUE TITLE
[Bug Report] The style generated by the online theme roller builder is missing

### ISSUE THREAD

**Issue by Aisen60** [ElemeFE/element#21291]
### Element UI version
2.15.6

### OS/Browsers version
google chrome  92.0.4515.159

### Vue version
2.6.14

### Reproduction Link
https://element.eleme.cn/#/zh-CN/theme

### Steps to reproduce
In the online theme roller, there is no style of skeleton screen in the generated style package

在线主题生成器生成的样式中，缺少`Skeleton 骨架屏` 的样式

### What is Expected?
there should have style of skeleton screen in the generated style package

生成的样式文件中，应该包含`Skeleton 骨架屏` 的样式

### What is actually happening?
there is no style of skeleton screen in the generated style package

生成的样式文件中，缺少`Skeleton 骨架屏` 的样式

**Comment by Aisen60** [comment]
估计和 https://element-api.ele.me/element/theme/updateVariable 这个接口有关系。

应该是后台编译的那一份样式不是最新的

**Comment by cs1707** [comment]
fixed
