### ISSUE TITLE
Upload, When uploading a large file, the server needs to wait for a period of time to receive the file

### ISSUE THREAD

**Issue by Thunder7991** [ElemeFE/element#21309]
The larger the file, the longer the waiting time. When the progress bar is 100%, the server does not immediately receive the file information. It needs to wait for a period of time before it can be received in the background

**Comment by 3344567** [comment]
望知悉，默认情况下，前端获取的是上传进度，而不是服务器接收进度，这不是el的问题，也不是js的问题，你可以对大文件进行切片，来尽可能实现服务器立即接收

**Comment by Thunder7991** [comment]
Thank you very much. This problem has been solved. The reason is the problem of nginx. What happened in the middle is still a little vague. Do you know why?
