### ISSUE TITLE
Grouping input with el-select makes the el-select current value not visible

### ISSUE THREAD

**Issue by yupal** [ElemeFE/element#2130]
Hello,

The issue is visible in a demo page in jsfiddle too: http://jsfiddle.net/yupal/caqLz20z/ 

I think the issue appears because the input with class "el-input__inner" has no width.
I think a  simple solution will be to add a not visible span before the input like:

`<span class="el-input__inner" style="visibility:hidden; height:0px; padding-top:0px; padding-bottom:0px">{{value}}</span>`

**Comment by zoell** [comment]
I added a style to the el-select like this:

```html
<el-input placeholder="Input" v-model="input1">
  <el-select v-model="select1" style="width:100px;" slot="prepend" placeholder="Select">
    <el-option label="XY" value="1"></el-option>
    <el-option label="Z" value="2"></el-option>
  </el-select>
</el-input>
```
http://jsfiddle.net/5vy3g219/1/

**Comment by Leopoldthecoder** [comment]
Since the width of the grouped Select is unknown, we figured the best way is for the users to add their own style like @zoell suggested (but not necessarily an inline style, you can put it in a css file).

@yupal your approach works in some cases, but if the options are long, they may still be truncated. So just write your own style.

**Comment by yupal** [comment]
@Leopoldthecoder - I did not test my suggestion on multiple cases but as soon as it has the same style as the input ( font-size, line-height, paddings, etc ) it should have the same width as the input. Or making the input hidden and using the span as a label for the selected option should work.

The styling solution will work in cases where the select options are known and limited ( e.g. Mr / Miss / Mrs ). If you have the list of states for example the issue you will have to test each one to make sure it fits.

**Comment by Leopoldthecoder** [comment]
@yupal OK, will look into this when I have more time.
