### ISSUE TITLE
拖动滑块组件时不触发事件

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#2131]
滑块组件在按下鼠标拖动时改变了值但是并没有触发其change事件 只有在松开鼠标以后才触发
可能是我对该事件的理解有误, 但是doc里的说明是 "值改变时触发"

浏览器 Chrome 55.0.2883.95
系统环境 OSX 10.12.2

**Comment by Leopoldthecoder** [comment]
似乎是有歧义，我把文档描述改一下。
