### ISSUE TITLE
[Bug Report] El-Menu Item disabled background has !important rule

### ISSUE THREAD

**Issue by vill3t** [ElemeFE/element#21315]
### Element UI version
2.15.6

### OS/Browsers version
Mac OS 11.5.2 / Chrome 93.0.4577.63

### Vue version
2.6.14

### Reproduction Link
https://jsfiddle.net/ka0hx8bq/15/

### Steps to reproduce
Try to change background colour on the disabled menu item by adding this style rule:

el-menu-item.is-disabled {
  background: rebeccapurple;
}

### What is Expected?
Disabled menu item has background colour - rebeccapurple

### What is actually happening?
Disabled menu item has background: none because of the !important rule.

**Comment by cs1707** [comment]
Try
```
.el-menu-item.is-disabled {
    background: rebeccapurple !important;
}
```

**Comment by vill3t** [comment]
Yes it works with !important, my question here is can you guys remove !important rule, or do you need that there for some specific reason?
