### ISSUE TITLE
[bug report] use this link https://element.eleme.cn/#/zh -The theme created by CN / theme / preview lacks the style of some components

### ISSUE THREAD

**Issue by NicholasNap** [ElemeFE/element#21333]
### Element UI version
2.15.6

### OS/Browsers version
Windows 10 / 93.0.4577.82

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/NicholasHwang/project/editor/ApawgN

### Steps to reproduce
1.通过链接 https://element.eleme.cn/#/zh-CN/theme/preview 下载主题；
2.通过代码 <link rel="stylesheet" src="./theme/index.css"> 将主题文件引入html

### What is Expected?
通过 https://element.eleme.cn/#/zh-CN/theme/preview 下载的主题文件，组件的样式能正常显示，例如el-descriptions，el-descriptions-item（目前发现的也只有这两个组件）

### What is actually happening?
通过 https://element.eleme.cn/#/zh-CN/theme/preview 下载的主题文件，组件的样式不能正常显示，例如el-descriptions，el-descriptions-item（目前发现的也只有这两个组件）

**Comment by cs1707** [comment]
Duplicate of #21209
