### ISSUE TITLE
[Bug Report] Table fixed column misalignment when column changed

### ISSUE THREAD

**Issue by litoxy** [ElemeFE/element#21341]
### Element UI version
2.15.6

### OS/Browsers version
chrome

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/litozheng/pen/powZXRY

### Steps to reproduce
1 set column fixed
2 change column 
3 column misalignment 

### What is Expected?
1

### What is actually happening?
column misalignment

**Comment by cs1707** [comment]
`this.$nextTick(() => this.$refs.table.doLayout())` can temporary solve this issue.

**Comment by ben1499** [comment]
doLayout() works sometimes, but this issue is still there in element-ui v2.15.14. Is there any other fix?
