### ISSUE TITLE
[Bug Report] Online Theme Roller" generates custom themes that do not contain new components

### ISSUE THREAD

**Issue by lainbo** [ElemeFE/element#21351]
### Element UI version
2.15.6

### OS/Browsers version
Windows 10/Chrome 94

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/lainbojc/pen/XWgoVgr

### Steps to reproduce
Go to "https://element.eleme.cn/#/zh-CN/theme/preview", adjust the color and click the download button at the top right of the page, the downloaded file, "index.css "The downloaded file does not contain the style of the "el-empty" component.

### What is Expected?
The generated css file contains all the styles of the latest components

### What is actually happening?
Custom themes generated with "Online Theme Roller", css files do not contain styles for new components, such as "el-empty"

**Comment by mulingyuer** [comment]
component <el-descriptions> and no style

**Comment by mulingyuer** [comment]
component **el-descriptions** and no style

**Comment by cs1707** [comment]
fixed
