### ISSUE TITLE
[Bug Report] el-select(multiple) cannot display default multiple selected data well.

### ISSUE THREAD

**Issue by KagenoMoheji** [ElemeFE/element#21362]
### Element UI version
2.15.6

### OS/Browsers version
Windows10,MacOS Catalina / Chrome94.0.4606.61

### Vue version
2.6.11

### Reproduction Link
https://codesandbox.io/s/bug-report-el-select-multipls-cannot-display-default-multiple-selected-data-well-nqbvk?file=/src/components/Issue.vue

### Steps to reproduce
1. Add `el-form` has `el-select`.
2. Set `multiple` into `el-select`.
3. Ready default multiple selected data in data binded to `el-form`.
4. Check that default multiple selected data are not displayed in the `el-select` form.

### What is Expected?
I expect that default multiple selected data can display in `el-select` well.

### What is actually happening?
The default multiple selected data cannot display in `el-select` well.
Sometimes, a not selected data is displayed multiple times, which occurs the error message: "Duplicate keys detected:".

**Comment by niesk** [comment]
In multi selection mode, the binding value is an array composed of the selected option value value.
Therefore, the key code part of your example can be changed toformIssue: 
`formIssue: {
        selectsData: [         
          "hoge@sample.com", 
          "fuga@sample.com"
        ]
      }`

**Comment by KagenoMoheji** [comment]
@niesk 
Oh, your answer solved my issue!
That was a careless mistake. Thank you.
