### ISSUE TITLE
tabs: 初始化时,指示条始终指向第一个

### ISSUE THREAD

**Issue by hisland** [ElemeFE/element#2139]
### ElementUI version
1.1.2

### Vue version
2.1.8

### Reproduction Link
https://jsfiddle.net/gmve9d3p/107/

![image](https://cloud.githubusercontent.com/assets/417448/21578294/ad509eb4-cfb5-11e6-9386-d8a9df9eda88.png)

目测是 tabs.vue: 92行 `getBarStyle` 里面刚开始时 `this.$refs.tabs` 为空所致
```js
mounted: function mounted() {
  this.$forceUpdate();
+ this.$nextTick(function() {
+   this.$forceUpdate();
+ })
},
```
增加这3行,可以得到想要的,但是感觉好怪

**Comment by Kingwl** [comment]
陈年老bug
