### ISSUE TITLE
[Bug Report] Horizontal menu error.

### ISSUE THREAD

**Issue by Edric-Li** [ElemeFE/element#21394]
### Element UI version
2.15.6

### OS/Browsers version
Microsoft Edge Version 94.0.992.50 (Official build) (64-bit)

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/edric-li/pen/vYJKOag

### Steps to reproduce
Open the console 

The following error will appear 
Uncaught RangeError: Maximum call stack size exceeded.

### What is Expected?
No error is expected.

### What is actually happening?
Actually produced an error.

**Comment by Edric-Li** [comment]
Temporary solution:

![image](https://user-images.githubusercontent.com/50992790/137859078-9a92a366-be89-4d8f-834f-c9395a62f1e8.png)

**Comment by ssw1992** [comment]
this bug still work on version 2.15.7
