### ISSUE TITLE
Table 表格中使用 scope报错无法获取变量

### ISSUE THREAD

**Issue by bigrocs** [ElemeFE/element#2141]
`<el-table-column label="日期" width="120">
      <template scope="scope">{{ scope.row.date }}</template>
    </el-table-column>`
报错：
Cannot read property 'date' of undefined

**Comment by Leopoldthecoder** [comment]
请确认 Element 的版本为 1.1.0 或以上，还有问题的话请提供 demo

**Comment by bigrocs** [comment]
谢谢 发现了是 1.0.8好长时间没有实际了。。

**Comment by Mark24Code** [comment]
解决了我的问题
至少需要：
"element-ui": "1.1.2",
"vue": "2.1.8",
"vue-template-compiler":"2.1.8"
