### ISSUE TITLE
[Bug Report] el-tabs   listen oninput event to change value well emit oninut twice

### ISSUE THREAD

**Issue by ehejhrj** [ElemeFE/element#21419]
### Element UI version
2.13.2

### OS/Browsers version
win10/chrome 95.0.4638.54

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/ehejhrj/pen/ZEJyyKy

### Steps to reproduce
click any unselected tab and will see console print twice

### What is Expected?
when modify value emit input once

### What is actually happening?
when modify value emit input twice

**Comment by skarbgud** [comment]
How about this?

https://codepen.io/skarbgud/pen/rNzqgMP?editors=1111

**Comment by skarbgud** [comment]
> What do you think about this?
> 
> https://codepen.io/skarbgud/pen/rNzqgMP?editors=1111

**Comment by ehejhrj** [comment]
> > What do you think about this?
> > https://codepen.io/skarbgud/pen/rNzqgMP?editors=1111

It can work
