### ISSUE TITLE
[Bug Report] DatePicker and DateTimePicker：When the timestamp is 0, the component does not display a value

### ISSUE THREAD

**Issue by gitgjz** [ElemeFE/element#21436]
### Element UI version
2.15.6

### OS/Browsers version
win10/Chrome 94.0.4606.54

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/gitgjz/pen/QWMaNbv

### Steps to reproduce
update the value1 and value2,
value1: 0,
value2: 1,

### What is Expected?
When timestamp is zero，show January 1，1970.

### What is actually happening?
When timestamp is zero，components do not display values.

**Comment by wangdaodao** [comment]
`value / v-model` type is `date(DatePicker) / array(DateRangePicker)`

**Comment by gitgjz** [comment]
> `value / v-model` type is `date(DatePicker) / array(DateRangePicker)`

Thanks ! It would be better if you could support number types. Because timestamps are more commonly used and all number values can be displayed except 0 , at now.
