### ISSUE TITLE
Bug Tab panels closable with named slot

### ISSUE THREAD

**Issue by Sancho66** [ElemeFE/element#2146]
Hello guys , 

I have detected a bug on tabs component.
See JS fiddle : https://jsfiddle.net/wojytw4g/
Close the closable tab and see contents of each tabs. It seems that each tab content is move to the right tab.

Can you fix this ? 
Thank you.

**Comment by baiyaaaaa** [comment]
this's because when u close the closable tab, the tabs will destroy the tab-pane instance manually.Actually the tab-pane number should update by your tab list data.In the next minor version，closing the tab only `$emit` an event but not do anything.
