### ISSUE TITLE
How to pass arguments with Command attribute of DropMenuItem?

### ISSUE THREAD

**Issue by ankyo** [ElemeFE/element#2147]
I use the @click event, but got the MouseEvent arugment only

so, how?

**Comment by Leopoldthecoder** [comment]
Check [this](http://element.eleme.io/#/en-US/component/dropdown#command-event) out.

**Comment by wenner** [comment]
这个问的不是这个意思吧...

目前的操作只能 @command="xxx"
然后xxx method中..只能接受一个参数就是command , 可是如果想传入其他的参数呢??

比如这个下拉菜单是在表格每一行都有,需要传入当前行的data , 那么现在就做不到...

而且如果在el-dropdown-item中加@click也没作用...

如何可以实现这些呢??

**Comment by YaoKaiLun** [comment]
我使用的是非 split-button , 点击菜单项，只能通过 command 进行事件分发，而不能自定义 click 事件，而通过 command ，不能传递参数，也不能获取当前点击的菜单项对象。不知道是不是我操作不当或者没用对方法，求指教！

**Comment by Leopoldthecoder** [comment]
@wenner @YaoKaiLun `el-dropdown-item` 并不是只能通过 `command` 事件进行操作，它完全支持 `click` 事件：http://jsfiddle.net/hxn4pm7o/
需要注意的是，Vue 2.0 中自定义组件的原生事件需要加 `.native` 修饰符（请阅读 [FAQ](https://github.com/ElemeFE/element/blob/master/FAQ.md) 第一条），所以需要写成 `@click.native`，直接 `@click` 肯定是无效的。

**Comment by YaoKaiLun** [comment]
@Leopoldthecoder 非常感谢

**Comment by wenner** [comment]
@Leopoldthecoder 谢谢,没有发现这个.

**Comment by zhangzhongjiang** [comment]
给大佬点赞！@Leopoldthecoder
我正好需要dropitem传递当前行所有数据。

**Comment by xiaonan39** [comment]
How to add click events to split button?
