### ISSUE TITLE
[Bug Report] v2.15.7 el-table use [type="expand"] clashed with "fixed"attribute

### ISSUE THREAD

**Issue by KevinLiu1995** [ElemeFE/element#21483]
### Element UI version
2.15.7

### OS/Browsers version
macOS 12/ Chrome  95.0.4638.69

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/NivekUil/pen/GRvzWqX

### Steps to reproduce
1、add [fixed="left"] or [fixed="right"] to el-table-column（with table type="expand"）
2、open table expand

### What is Expected?
CSS Style display normal like element v2.15.6 or before version

### What is actually happening?
 CSS style disorder

**Comment by satrong** [comment]
+1
