### ISSUE TITLE
[bug report] the theme color download drop-down generated online, and the color value is not replaced

### ISSUE THREAD

**Issue by fengbindev** [ElemeFE/element#21489]
### Element UI version
2.15.7

### OS/Browsers version
win10

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/fengbindev/pen/vYJPyZM

### Steps to reproduce
修改颜色值下载

### What is Expected?
颜色改变

### What is actually happening?
没有改变

**Comment by shenxiang216** [comment]
拖拽上传报错 Uncaught TypeError: this._drop is not a function
    at Object.handleEvent (event.js:510)

**Comment by cs1707** [comment]
fixed
