### ISSUE TITLE
[bug report] multiple scroll bars appear when the header and column of the table are fixed,

### ISSUE THREAD

**Issue by OMOBruce** [ElemeFE/element#21493]
### Element UI version
2.15.7

### OS/Browsers version
mac

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/ziyoung/pen/rRKYpcs

### Steps to reproduce
table修了个寂寞啊？

### What is Expected?
改一改吧大哥们

### What is actually happening?
我不想再测了

**Comment by cheny-github** [comment]
这就是伸手党吗😅😅😅😅😅😅😅😅
