### ISSUE TITLE
怎么循环某个el-table-column中的props，生成一组el-tag

### ISSUE THREAD

**Issue by arronf2e** [ElemeFE/element#2149]
### ElementUI version

1.0.0-rc.7
### OS/Browers version
macOS/Chrome 53

### Vue version

2.0.3
### What is actually happening?
    <el-table-column
	    prop="roles"
	    label="角色"
    	    width="280"
    >
    <el-tag type="primary" v-for="role in roles">{{ role }}</el-tag>
    </el-table-column>
这样做的话只显示了内容，没有tag的样式

**Comment by furybean** [comment]
[FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) 中的第二个问题。

**Comment by arronf2e** [comment]
@furybean  谢谢
