### ISSUE TITLE
select 多选下拉列表

### ISSUE THREAD

**Issue by DevilLeven** [ElemeFE/element#2150]
### ElementUI version
1.1.2

### OS/Browers version
 macOS/Chrome 53 

### Vue version
2.1.8

![image](https://cloud.githubusercontent.com/assets/21081386/21599431/6292381c-d1a7-11e6-85d0-8ab855e827f8.png)

多选下拉列表 有默认值得时候布局异常

**Comment by Leopoldthecoder** [comment]
没有复现：http://jsfiddle.net/6ytc6q1p/ ，请提供的 demo

**Comment by DevilLeven** [comment]
我在demo上 也没发现什么问题，不过我这项目里确实这样，我在看看吧 @Leopoldthecoder

**Comment by DevilLeven** [comment]
我使用了自定义主题 不过觉得不是自定义主题的原因

**Comment by DevilLeven** [comment]
@Leopoldthecoder  问一个问题 在Dialog中加入 表单  safari 浏览中会出现这么一个小人的图片 为什么 怎么去掉。非常感谢！！！！
![image](https://cloud.githubusercontent.com/assets/21081386/21604238/088cde0e-d1dd-11e6-9425-4ffcaf6a4815.png)

**Comment by Leopoldthecoder** [comment]
你装了什么 Safari 插件吧

**Comment by cmlily8294** [comment]
http://jsfiddle.net/gis_cl/0qxget9h/
我复现了，给select加了宽度……
![image](https://cloud.githubusercontent.com/assets/10285991/21606337/a7b21c40-d1e9-11e6-9090-383c4126f2a0.png)
