### ISSUE TITLE
[bug report] inputnumber is in the formitem (bound with non null verification). Manually entering a number will actively trigger the rule and an error will be reported in the verification

### ISSUE THREAD

**Issue by zhangshenghong** [ElemeFE/element#21529]
### Element UI version
2.15.5

### OS/Browsers version
win10,Google Chrome 92.0.4515.131（正式版本） （64 位）

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/zhangshenghong/pen/NWaqNap

### Steps to reproduce
直接输入数字1

### What is Expected?
手动输入不校验出错

### What is actually happening?
手动输入校验出错，离开焦点才取消错误

**Comment by machunyu1995** [comment]
you can add this prop : trigger:'blur'

**Comment by zhangshenghong** [comment]
> you can add this prop : trigger:'blur'

thank you，the problem is solved.
