### ISSUE TITLE
DatePicker doesn't update year properly in this specific case

### ISSUE THREAD

**Issue by Frondor** [ElemeFE/element#2152]
Steps: ![](https://i.gyazo.com/efc68cc3ec68cb96938e63358ac3abea.gif)

Basically, when you go through `Year` (any year) > `December` > `January 1st`, year gets a `1` **appended** instead of **added**.

If you don't switch years, it doesn't happen:
![](https://i.gyazo.com/6948fc6bc6b1a459ec942d9b14e1234b.gif)

**Comment by QingWei-Li** [comment]
What is Element version number?

**Comment by Frondor** [comment]
@QingWei-Li just installed it 1.1.2

**Comment by QingWei-Li** [comment]
![kapture 2017-01-04 at 11 50 56](https://cloud.githubusercontent.com/assets/7565692/21631247/14a6dd6a-d274-11e6-8b84-6dabbd14f361.gif)

http://jsfiddle.net/55ubgyby/

It works. Can you provide a demo?

**Comment by Frondor** [comment]
@QingWei-Li You're selecting `Oct` and then a `Nov`'s day, not `Dec` (december). The problem appears when it calculates the **next year** while in a "month view".

![https://i.gyazo.com/78c300af98874fe060c367cfb0424129.gif](https://i.gyazo.com/78c300af98874fe060c367cfb0424129.gif)
