### ISSUE TITLE
[Bug Report] Error in resetfield field field on document form page of elment UI official website

### ISSUE THREAD

**Issue by banlijun** [ElemeFE/element#21541]
### Element UI version
2.15.7

### OS/Browsers version
Chrome 96

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/assets/editor/iframe/iframeConsoleRunner-d0f3648046d2aaca07bd0037b9e061a26c74a8a999b75672ad6a638cca641472.js

### Steps to reproduce
my code:this.$refs.basicForm.resetField()
result:Error in v-on handler: "TypeError: this.$refs.basicForm.resetField is not a function"

### What is Expected?
code:this.$refs.basicForm.resetFields()

### What is actually happening?
code:this.$refs.basicForm.resetField()

**Comment by toesbieya** [comment]
仿佛在逗我，`resetFields`是`el-form`的方法，`resetField`是`el-form-item`的方法
