### ISSUE TITLE
[Select] 样式问题 ie9下样式问题

### ISSUE THREAD

**Issue by fewiki** [ElemeFE/element#2156]
http://element.eleme.io/#/zh-CN/component/select

![qq 20170103143656](https://cloud.githubusercontent.com/assets/13325335/21601200/4661f4d2-d1c2-11e6-9a7d-c99bb3fc663f.png)

用ie9打开官网的例子，当鼠标移动在列表项上，会出现 撑满整个屏幕
必须用ie9打开才有这个问题，用edge模拟ie9不能重现...
期待能解决下，非常感谢

（我在项目中使用也有这个问题）

**Comment by lwfyiwei** [comment]
我在项目中也有这个问题，这个官方例子比较明显，但凡在IE9下测试过就能发现。

**Comment by fewiki** [comment]
是啊，公司暂时还要兼容ie9，比较苦逼。 
无法想象如果还要兼容6 7 8无法言说的痛苦
赶紧淘汰ie这破玩意吧，一大把的青春都耗在了兼容上面

**Comment by hellinnocence** [comment]
在IE9好多样式都有问题，主要是不支持css3

**Comment by cycold** [comment]
bootstrap4 已经宣布不支持IE9了 
https://blog.getbootstrap.com/
