### ISSUE TITLE
[Bug Report] el-table树表格复选框子节点无法取消选中

### ISSUE THREAD

**Issue by XM2510136957** [ElemeFE/element#21581]
### Element UI version
2.15.7

### OS/Browsers version
 Chrome/96.0.4664.93

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/_xumi/pen/oNGGKEL?editors=1111

### Steps to reproduce
el-table树表格复选框子节点无法取消选中

### What is Expected?
el-table树表格复选框子节点可以取消选中

### What is actually happening?
el-table树表格复选框子节点无法取消选中

![image](https://user-images.githubusercontent.com/18229485/147335055-dfe189c9-b088-4efe-a94e-0b40e673f489.png)

**Comment by zjydipingxian** [comment]
同问，你这边解决了吗？

**Comment by zjydipingxian** [comment]
您这边解决这个问题了吗

**Comment by chgmxx** [comment]
您这边解决这个问题了吗

**Comment by zjydipingxian** [comment]
你好。 我想问一下， 解决这个问题了吗？
