### ISSUE TITLE
表格分页切换高亮显示问题

### ISSUE THREAD

**Issue by mabelyong** [ElemeFE/element#2160]
表格的选中行是高亮状态，点击分页后高亮状态不消失，而且还可以继续选择另外一行成为高亮状态，如果来回切换分页，就可以让整个表格都选成高亮的状态，只有我才遇到这样的问题吗？

**Comment by kopheece** [comment]
楼主现在用的是哪个版本呢
我也遇到了这个问题，我用的是1.0.5版本。不知道后续版本修复了没
看到1.0.9有提到：修复单选的 Table 在数据移除时，高亮状态仍然存在的问题

**Comment by kopheece** [comment]
刚更新到1.1.2版本
测试了下  这个问题已经修复了
