### ISSUE TITLE
[Bug Report] el-table 不显示

### ISSUE THREAD

**Issue by wenzirang** [ElemeFE/element#21662]
### Element UI version
2.15.6

### OS/Browsers version
mac os

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/ziyoung/pen/rRKYpd?editors=1000

### Steps to reproduce
第一步：封装一个vue的业务组件
第二步：在业务组件中局部注册Table和TableColumn组件。并使用
第三步：组件在当前业务组件或包装的组件执行环节中没有任何问题
第四步：将这个业务组件进行打包
第五步：在某个项目中使用这个业务组件
第六步：业务组件中包含的tabel组件不展示，但是html有结构，数据没有渲染出来
第七步： 确保业务组件及项目环境的 vue版本都是一致的

    

### What is Expected?
渲染正常

### What is actually happening?
table组件在子组件中局部注册，渲染不正常，dom节点创建成功但是无数据

**Comment by forwardNow** [comment]
我也遇到相同的问题了，排查了两天发现打包时存在多个 Vue 的包。最终通过去除重复包搞定了：
```js
// webpack.config.js
resolve: {
    alias: {
      'vue': path.resolve(__dirname, '../', 'node_modules', 'vue'),
    },
  },
```

**Comment by dodu2014** [comment]
> 我也遇到相同的问题了，排查了两天发现打包时存在多个 Vue 的包。最终通过去除重复包搞定了：
> 
> ```js
> // webpack.config.js
> resolve: {
>     alias: {
>       'vue': path.resolve(__dirname, '../', 'node_modules', 'vue'),
>     },
>   },
> ```

貌似不行吧，dev 模式就不显示
