### ISSUE TITLE
el-checkbox  -- Bug

### ISSUE THREAD

**Issue by fansenze** [ElemeFE/element#2168]
<img width="1669" alt="1483433788 1" src="https://cloud.githubusercontent.com/assets/18278456/21603166/108f3946-d1d6-11e6-8315-1618e94b8275.png">
<img width="1584" alt="1483433864 1" src="https://cloud.githubusercontent.com/assets/18278456/21603229/856b60dc-d1d6-11e6-8efd-51f4a1c414a3.png">

<el-checkbox>这个组件在表单中的时候，报错 Cannot read property 'value' of undefined

**Comment by baiyaaaaa** [comment]
please follow the issue template
