### ISSUE TITLE
[Bug Report] tabs组件，before-leave属性，在返回一个promise（return一个confirm组件）且被reject时，仍然会进行tab切换。

### ISSUE THREAD

**Issue by Web-Li** [ElemeFE/element#21719]
### Element UI version
2.15.7

### OS/Browsers version
mac chrome

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/ziyoung/pen/LKNBqB

### Steps to reproduce
tabs组件，在before-leave属性的回调函数中返回一个confirm组件（实际是promise），点击confirm组件的取消按钮，tab仍然切换。非promise直接返回boolean是ok的。

### What is Expected?
promise reject后不切换tab

### What is actually happening?
promise reject后依然切换了tab

**Comment by Iloveweb666** [comment]
cancel的回调中再返回个Promise.reject()可以解决
