### ISSUE TITLE
[Bug Report] 由于unpkg.com/vue 现在默认指向的是vue3，导致现在网站的demo均无法运行

### ISSUE THREAD

**Issue by ckvv** [ElemeFE/element#21734]
### Element UI version
2.15.7

### Vue version
2.6.14

### Reproduction Link
https://element.eleme.cn/#/zh-CN/component/installation#hello-world

### Steps to reproduce
*

### What is Expected?
*

### What is actually happening?
*

**Comment by acyza** [comment]
官网上的demo出不来，对新手是真的不友好，我刚开始学的时候，用cdn引入，照着官网，越学越懵。
