### ISSUE TITLE
添加el-button的属性href，使其被渲染成a链接

### ISSUE THREAD

**Issue by saopang** [ElemeFE/element#2179]
因为在firefox和ie里，button里嵌套a链接是不触发的，能不能像https://museui.github.io/#/flatButton 一样在el-button里添加href属性，使其被渲染成a链接，最好是个slot

**Comment by baiyaaaaa** [comment]
为什么要在button里嵌套a链接

**Comment by Kingwl** [comment]
type=text 然后onClick不行么

**Comment by QingWei-Li** [comment]
不考虑

**Comment by 841660202** [comment]
@gengxuelei 你可以考虑，这样你就可以偷懒啦

`
 <a :href="`${动态下载地址}`">
     <el-button type="primary" ><i class="el-icon-download"></i>导出</el-button>
</a>
`
![image](https://user-images.githubusercontent.com/18305361/56188191-6a19ae80-6057-11e9-9b2a-5973109a5b14.png)
