### ISSUE TITLE
form validator中rule动态修改后require=true的前面*号没有消失

### ISSUE THREAD

**Issue by shipengyan** [ElemeFE/element#2181]
![image](https://cloud.githubusercontent.com/assets/1212932/21607231/b1e7e144-d1ef-11e6-855c-ae46b91577e4.png)

### ElementUI version
1.1.2

### OS/Browers version
win7/chrome 55
 macOS/Chrome 53 -->

### Vue version
2.1.6

**Comment by baiyaaaaa** [comment]
目前暂不支持

**Comment by shipengyan** [comment]
@baiyaaaaa 是的

**Comment by blaze0207** [comment]
請問您是如何動態去除rule中的require呢?

為了這問題苦惱許久!!!

**Comment by baiyaaaaa** [comment]
will be fixed in next version
