### ISSUE TITLE
1.1.2 还是无法使用ssr

### ISSUE THREAD

**Issue by pjialin** [ElemeFE/element#2185]
## window is not defined
```
error during render : /
ReferenceError: window is not defined
    at __vue_ssr_bundle__:1033:30


    at __vue_ssr_bundle__:1028:47
    at module.exports (__vue_ssr_bundle__:1050:68)
    at Object.module.exports.module.exports (__vue_ssr_bundle__:1278:37)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.module.exports.Object.defineProperty.value (__vue_ssr_bundle__:237:97)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:1858:63)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at __vue_ssr_bundle__:67:18

```
### ElementUI version
1.1.2

### Vue version
2.1.8

**Comment by reg2005** [comment]
Hi! I'am have solved this problem so:
```javascript
if(typeof document !== 'undefined'){
   Vue.use(ElementUI)
}
```

**Comment by QingWei-Li** [comment]
It should work. @pjialin  Can you provide a reproduction repository?

**Comment by QingWei-Li** [comment]
https://element-ui.gomix.me
https://gomix.com/#!/project/element-ui

It is work.

**Comment by pjialin** [comment]
@reg2005 I tested the method you provided, or will be an error, because as long as I introduced element-ui, and not through Vue.use (element-ui), will be reported window is not defined

**Comment by pjialin** [comment]
@QingWei-Li  I think you are using nuxt.js, I have not tested, I used vue-server-renderer No, I will try to use nuxt

**Comment by pjialin** [comment]
@QingWei-Li  I use nuxt test it, Is can work, thank you ！ I close the..

**Comment by pjialin** [comment]
I use nuxt.js  is can work

**Comment by heimuya** [comment]
find the following code in plugins folder can not work
```javascript
import Vue from 'vue'
import ElementUI from 'element-ui'

Vue.use(ElementUI)
```

but if use require instead of import, it works.
```javascript
import Vue from 'vue'

Vue.use(require('element-ui'))
```
I don't know why
