### ISSUE TITLE
[Bug Report] el-time-picker 时间选择器，is-range   value-format="hh:mm"，时间选择大于12点时，时间显示不对

### ISSUE THREAD

**Issue by fangzhouzhu** [ElemeFE/element#21859]
### Element UI version
2.15.8

### OS/Browsers version
win10/chrome90

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/fangzhouzhu/pen/NWyryyK

### Steps to reproduce
`
<el-time-picker
    is-range
    v-model="value1"
    format="hh:mm"
    range-separator="至"
    start-placeholder="开始时间"
    end-placeholder="结束时间"
    placeholder="选择时间范围">
  </el-time-picker>
`

![image](https://user-images.githubusercontent.com/33620654/167834417-f7662002-5bb5-42a6-8e79-87a9a872f916.png)

### What is Expected?
期待时间正常显示

### What is actually happening?
时间大于12点时，值 = 值-12

**Comment by litterboys** [comment]
这个问题是因为格式化的内容不准确导致的，value-format的（小时）大写的是24小时制 value-format="HH:mm:ss"
