### ISSUE TITLE
Bug on table sortable column

### ISSUE THREAD

**Issue by IgorDePaula** [ElemeFE/element#2187]
### ElementUI version
^1.0.7

### OS/Browers version
ubuntu 15.10 / chrome Version 55.0.2883.87 (64-bit)

### Vue version
^2.0.1

### Steps to reproduce
Put this names on a sortable column [adriano, fábia, fernando], and try ordened it
### What is Expected?
on order I expect order in [adriano, fábia, fernando] and [fernando, fábia, adriano]
### What is actually happening?
Actually happening [adriano, fábia, fernando] => [adriano, fernando, fábia] => [fernando, fábia, adriano]

My language is Brazilian portuguese, my language has some accidents on some letters.

**Comment by Kingwl** [comment]
may need a custom function to compare item?

**Comment by IgorDePaula** [comment]
O don't understand
Em qua, 4 de jan de 2017 às 00:28, kingwl <notifications@github.com>
escreveu:

**Comment by Leopoldthecoder** [comment]
@IgorDePaula You can define your own sorting behavior via `sort-method`, which is an attribute of `table-column`.
