### ISSUE TITLE
1.1.2走马灯基础特效不是无缝滚动

### ISSUE THREAD

**Issue by zxyling** [ElemeFE/element#2189]
1.1.2的走吗灯基础用法里，图片走到最后一张时候不是直接继续下一轮播放，而是拉回第一张之后再进行下一轮播放，请问可以修改成类型卡片化这种无缝播放的效果吗，谢谢

**Comment by Leopoldthecoder** [comment]
近期无计划。

**Comment by Leopoldthecoder** [comment]
Fixed in #2622

**Comment by posrix** [comment]
fixed? try it yourself

**Comment by JoJoChilly** [comment]
Didn't fix it even in http://element.eleme.io/#/zh-CN/component/carousel... When click left arrow there's also posibility that other page flashed in...
