### ISSUE TITLE
how to enable english text for all components ?

### ISSUE THREAD

**Issue by chagamkamalakar** [ElemeFE/element#219]
these components are awesome .. i want to use this components in my project, would somebody suggest me how to enable english as default for all components. that would be of great help.

**Comment by chagamkamalakar** [comment]
i got to know after looking into code , i just need to pass the values to placeholder/other respective properties. Am i right?

**Comment by Leopoldthecoder** [comment]
@chagamkamalakar You're right.
I think you won't be confused if there is an English documentation. For now the documentation is Chinese, but still you can read the demo code which sheds light on how each component is used.

**Comment by chagamkamalakar** [comment]
thank you @Leopoldthecoder
