### ISSUE TITLE
el-select as prepend not showing data

### ISSUE THREAD

**Issue by andreixk** [ElemeFE/element#2190]
### ElementUI version
1.1.2

### OS/Browers version
macOS/Chrome 55

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/6jrbgxz3/
(example link from documentation)

### What is Expected?

The prefixed select component (with slot="prepend") should display the selected value

### What is actually happening?

Regardless of what is selected, the prepend component does not display a value

**Comment by Leopoldthecoder** [comment]
The demo URL is wrong (you need to click the 'Save' button), but I guess it's because the prefixed Select is not wide enough to display your selected option. So just add a `width` on `.el-select` element.

**Comment by andreixk** [comment]
I updated the URL. But I was just pointing out that the jsfiddle example in the documentation (for input component) doesn't actually do what the documentation shows.

**Comment by Leopoldthecoder** [comment]
Fixed example via #2283. 

And, I meant adding a CSS rule `width`, not a prop `:width`.
