### ISSUE TITLE
[Bug Report] 在使用DatePicker组件时，vue会一直提示子组件直接修改父组件传进来的prop数据的警告【Prop being mutated: "placement"】，大致看了下，DatePicker组件在created中直接修改了props里边的placement

### ISSUE THREAD

**Issue by Adophlidu** [ElemeFE/element#21911]
### Element UI version
2.15.9

### OS/Browsers version
chrome：102.0.5005.61（正式版本） (arm64)

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/Adolph_dudu/full/JjpaELd

### Steps to reproduce
正常使用DatePicker组件，控制台就会出现vue给出的直接修改父组件传进来的prop数据的警告信息【请查看浏览器控制台警告信息⚠️】

### What is Expected?
不应该出现警告信息

### What is actually happening?
vue一直提示警告信息

**Comment by Adophlidu** [comment]
这个issue已经有了

**Comment by Wayne-007** [comment]
赶上了个新鲜的bug
