### ISSUE TITLE
[Bug Report] Tree组件在懒加载时，default-checked-keys设置选择前两个时，会把当前层的所有兄弟node选中

### ISSUE THREAD

**Issue by kiss-keray** [ElemeFE/element#21932]
### Element UI version
2.15.7

### OS/Browsers version
macOS 12.4/Chrome 102.0.5005.115

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/kiss-yu/pen/abqxNBe

### Steps to reproduce
1. 将Tree设置为懒加载，被设置default-checked-keys为大于第一级的某级列表的前两个node-key（只要最前面的node-key连选了>=2个都可以）。
2. 展开Tree，会发现预期只选择某层的前两个node，实际会把当前层的全部兄弟node选中
正确的设置默认值：
<img width="1916" alt="正常" src="https://user-images.githubusercontent.com/24504763/174420627-b3d74076-a64d-4dfa-872f-17f1a5beb4e2.png">
错误的设置默认值：实际我只设置了两个node-key，实际把全部的node选中了。
<img width="1916" alt="错误" src="https://user-images.githubusercontent.com/24504763/174420630-8c0dfc70-ac65-44f2-bb29-6870c6a8dabc.png">

### What is Expected?
只选中default-checked-keys设置的node

### What is actually happening?
选中了所有兄弟node

**Comment by kiss-yu** [comment]
2.15.9版本一样存在这个问题
