### ISSUE TITLE
[Feature Request] SCSS modules instead of plain .css files

### ISSUE THREAD

**Issue by Frondor** [ElemeFE/element#2194]
This is a huge feature request. Just like https://github.com/twbs/bootstrap-sass does **[here](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss)**, this way the _import on demand_ becomes more "friendly" and easy to accomplish. Not to mention that projects like [Laravel](https://github.com/laravel/laravel) apps shall see a lot of benefits from this.

Actually, the need of extra webpack configuration to customize the styles is kind of a mess. Laravel user-base find this project really hard to implement on their apps. I strongly believe this is an important feature to work in.

**Comment by liril-net** [comment]
@Frondor Do u mean that u need a scss version of themes?

**Comment by Frondor** [comment]
@liril-net I mean to be able to @import each component's CSS just like https://github.com/twbs/bootstrap-sass does through [this kind of files](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss), so we create our own builds, and also it would be good to override theme `_variables`. Just SASS things.

**Comment by liril-net** [comment]
@Frondor In my opinion, this can be solved by generating styles separately. 

Now it is combined in [https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/index.css](https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/index.css).

However in this way, it is **impossible** to override `_variables` which already processed by `postcss`.

**Comment by Frondor** [comment]
In SCSS there's the `!default` flag which makes really easy to override $variables if you adopt the sass architecture.
Bootstrap, for example, declares its variables like `$brand-primary: #00F !default;` which means the variable won't be used unless it wasn't _previously_ declared.
This way you can have (talking about a build system obviously), let's say a `main.scss` file where you load the components' CSS (on demand) and a variables' file, preceded by your own variables file. 

I can make a visual example of how it may look like, using some build system like Laravel's elixir.

**Comment by liril-net** [comment]
@Frondor I have used SCSS for a while, so i do know what u mean and how great the feature is. 

I quite agree that we should have access to each component's style, so that we can use it on demand. The tool `element-theme` we have now is quite awkward to use, maybe we should introduce something awesome into it. 

However, all these features you have talked about are based SCSS, we need SCSS build system to override **SCSS** variables. So maybe need a SCSS version(or something different) of these components' styles. What we have written now is deeply depended on the PostCSS plugin [postcss-salad](https://github.com/ElemeFE/postcss-salad). It is not difficult for vue to process postcss, in my opinion it maybe a good idea that we just expose original styles to users, and they can process it if needed.

Let's ask @QingWei-Li whether should we implement SCSS version?

**Comment by QingWei-Li** [comment]
1. Actually, we can override variables just like SCSS using poscss-salad.

```css
:root {
  --color-primary: $color-primary!important;
}

@import "element-ui/packages/theme-default/src/index.css";
```
 2. If we need SCSS version, I would like to be able to automatically generate. 

https://github.com/jxnblk/css-scss

**Comment by QingWei-Li** [comment]
@liril-net  Sorry, I have not tested. I just considered whether we could implement a similar tool to generate SCSS version.

**Comment by liril-net** [comment]
@QingWei-Li So should we start another project to do this? It is not difficult to implement such a DSL. 

Do u think that we can simply use `RegExp` to replace things like variables and BEM? I have only explored some of these styles, i think most of them are compatible to SCSS, aren't they?

**Comment by QingWei-Li** [comment]
@liril-net 

https://github.com/ElementUI/theme-default I try to change the configuration using

```json
{
  "browsers": ["ie > 8", "last 2 versions"],
  "features": {
    "sassColor": false,
    "partialImport": false,
    "precss": false,
    "bem": {
      "shortcuts": {
        "component": "b",
        "modifier": "m",
        "descendent": "e"
      },
      "separators": {
        "descendent": "__",
        "modifier": "--"
      }
    }
  }
}
```

We can get "CSS" like

```scss
@charset "UTF-8";
@import "./common/var.css";

.el-tag{

    background-color: var(--tag-fill);

    display: inline-block;

    padding: var(--tag-padding);

    height: 24px;

    line-height: calc(@height - 2);

    font-size: var(--tag-font-size);
   ....
}
```

I think we can write a plugin or directly use `css-scss` to deal with variables. If possible, we can add the feature into the CI that can automatically build and publish SCSS version.

**Comment by QingWei-Li** [comment]
@liril-net 

1. I have no idea. RegExp?
2. Dont worry about BEM, `postcss-salad` has been dealt with.
3. Yes.
4. We do not need to deal with fonts.
5. Create a new project under the ElementUI organization, because the `element-theme-default` has been used [in some projects](https://github.com/search?q=element-theme-default&ref=opensearch&type=Code). the repo will compile and push [automatically via CI](https://github.com/ElemeFE/element/blob/dev/build/deploy-ci.sh).

**Comment by liril-net** [comment]
@QingWei-Li 

Can u create a new project now? I will fork it and try to implement these features.

**Comment by QingWei-Li** [comment]
@liril-net 

Done https://github.com/ElementUI/theme-default-scss

Look forward to your contribution!

**Comment by metamet** [comment]
Implementing SASS would be of great help here and I would be happy to start using Element, but being unable to change the theme variables with ease is a big hindrance. 

I would like to echo that `bootstrap-sass` does it it well and may be a good inspiration.

**Comment by liril-net** [comment]
@metamet We have implemented one version of SCSS at [theme-default-scss](https://github.com/ElementUI/theme-default-scss) which is translated from PostCSS version.

**Comment by whitetrefoil** [comment]
Glad to know the scss version is coming!

Just FYI, in many projects I'm working in, the most difficult problem to replace bootstrap with elementui is also the variables in scss files.  It's usual to share the variables (e.g. colors) between bootstrap's theme and each project's own components / styles, to create maintainable code in a very simple build workflow (e.g. a single webpack rule).

In order to achieve the same result, I'm now have to use a template of variable.scss + a template of element-variables.css + a directory file, then create some additional watch processes beside webpack, use tool like gulp-replace to generate those 2 variable file then build out the styles, then send them to webpack dev server...

**Comment by Frondor** [comment]
@liril-net I little bit of documentation on how to implement and use it would be cool :smile: Although I'm not sure if that project would get the job done :confused:

**Comment by liril-net** [comment]
@Frondor Of course not, they are only used for development, we will publish this library to npm after enough test.

@whitetrefoil 

All you need to do is just download `theme-default-scss` and `import 'theme-default-scss'` in your `.js/vue` or `@import` in your `.scss`.

If you want to try this version now, you should follow these steps:

1. Download [them-default-scss](https://github.com/ElementUI/theme-default-scss).
2. `npm install && npm run build`
3. `import 'theme-defualt-scss(the directory you download)'`

If documentation needed, maybe i will try to generate one.

**Comment by liril-net** [comment]
@metamet We have add `!default` in variables, so you can just override if needed.

**Comment by whitetrefoil** [comment]
Trying to build a workflow around theme-default-scss now~ BTW, will we be able to use just `npm i -S theme-default-scss` then `@import "~theme-default-scss/lib/button` in near future? 🤗

**Comment by liril-net** [comment]
@whitetrefoil Of course, we will publish it to npm.
@QingWei-Li Maybe you should publish it to occupy the name. 😄

**Comment by QingWei-Li** [comment]
@whitetrefoil @Frondor 
`theme-default-scss` is released.

**Comment by Frondor** [comment]
![](http://i.imgur.com/4N9kc9x.jpg)

I'm installing it today! Thank you!

**Comment by qidaneix** [comment]
In my opinion, it would be very nice if element-ui can provide the support of the popular preprocessor like Less, SCSS, Stylus and postcss. Just like awesone-font did, which provide the version of Less and SCSS.

In Chinese: 我觉得吧，要是element-ui可以支持一些主流的css预编译器比如Less，SCSS之类就爽歪歪了，就像awesone-font就提供了对Less和SCSS的支持。因为编译压缩过的css代码真的很难修改以及自定义样式（难道我们的网站都要和饿了么一个风格？），而且.vue文件也对不同的css预编译器提供了支持（`<style lang="scss">`），用起来真的很方便。

谢谢

**Comment by Frondor** [comment]
To be honest, I never used it because it wasn't implemented how I initially proposed. Plus, that repo does not run the latest CSS of this package.

**Comment by diemah77** [comment]
@Frondor So how do you use Element's stylesheet right now? Importing `index.css `in your SCSS index file?

**Comment by Frondor** [comment]
@diemah77 I'm not using this package anymore, sadly. But I used to import only the CSS modules I needed, although I couldn't override any variable like I would if it supported SCSS.

**Comment by diemah77** [comment]
What's your alternative ui lib then?

**Comment by webberwang** [comment]
I agree, the SCSS version should be the default version included with element. Works much simpler across projects and better support overall with SCSS

**Comment by mheras** [comment]
Hello, how can I use `theme-defualt-scss` with Nuxt.js?

**Comment by chmcphoy** [comment]
@mheras For nuxt you'd need the the sass-loader & node-sass webpack loaders as per the [docs](https://nuxtjs.org/faq/pre-processors/) and then create a main.scss file in your assets dir where you can import scss files i.e — `@import 'element-theme-default';`. Then bringing in the main.scss file in your nuxt.config.js should do it. The nuxtjs.org site has a useful sass [setup](https://github.com/nuxt/nuxtjs.org/blob/master/nuxt.config.js) for reference.

**Comment by matthagemann** [comment]
Is traffic being handled intelligently? I'm just checking the network traffic in dev tools and the whole source code bloats up to 1.1M and almost 50,000 lines using SCSS (compared to 100K and 3,000 lines with the conventional CSS import).
