### ISSUE TITLE
[Feature Request] vue2.7版本中，el-table渲染空白

### ISSUE THREAD

**Issue by ZGH0717** [ElemeFE/element#21968]
### Existing Component
是

### Component Name
el-table

### Description
Element UI version
2.15.9

###  OS/Browsers version
window10

### Vue version
2.7.0

### Vite version
2.9.13

### Component Name
Table

### Description
今天vue发布2.7版本后，对现有项目进行升级后，并且本地开发改造成vite作为构建工具，本地开发启动后，发现el table组件渲染空白。

![image](https://user-images.githubusercontent.com/20718604/176906106-849a7270-ac59-4ac3-9842-502573b93d35.png)

**Comment by ldwqh0** [comment]
发现同样的问题，还以后是我的问题，结果一顿追查，查到这里来了，不知道是vue的问题，还是el-table的问题了

**Comment by mannymu** [comment]
同样有问题。准备降级vue到 2.6

**Comment by sh-winter** [comment]
+1

**Comment by newby1** [comment]
+1

**Comment by dimple-smile** [comment]
vue2.6 +1

**Comment by sh-winter** [comment]
> 发现同样的问题，还以后是我的问题，结果一顿追查，查到这里来了，不知道是vue的问题，还是el-table的问题了

我改用了 `iview` 的 `table` 组件，没有发现问题

**Comment by klren0312** [comment]
是我用法不对吗, 我可以啊

```
vue@2.7.0
vite@2.9.13
element-ui@2.15.9
```

![image](https://user-images.githubusercontent.com/10903843/177291588-3b3caf7d-e64f-4275-ac5b-93e27839492e.png)

https://github.com/klren0312/vite_vue2.7/blob/master/src/views/ContentPage.vue

**Comment by dimple-smile** [comment]
> 

好像是服务器打包环境有些问题，还在排查，本地打包不会这样，服务器上docker打包出来就是有问题。

**Comment by ZGH0717** [comment]
我使用@vitejs/plugin-vue2插件解决了此问题。才发现2.7要用专用插件@vitejs/plugin-vue2

**Comment by ZGH0717** [comment]
@vitejs/plugin-vue2插件解决了此问题

**Comment by ldwqh0** [comment]
@ZGH0717 我没有用vite,用的vue-loader，有同样的问题。

**Comment by ZGH0717** [comment]
@ldwqh0 vue-template-compiler是否升级到了2.7版本,可以看vue的[CHANGELOG](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01)，我之前也没发现vite要用[@vitejs/plugin-vue2](https://github.com/vitejs/vite-plugin-vue2).替换之前的[vite-plugin-vue2](https://github.com/underfin/vite-plugin-vue2).

**Comment by ldwqh0** [comment]
@ZGH0717  vue-template-compiler 是一起升级的，

**Comment by lincenying** [comment]
1. 安装  @vitejs/plugin-vue2
2. 在 vite.config.js里, 将 `import { createVuePlugin } from 'vite-plugin-vue2'` 改成 `import createVuePlugin from '@vitejs/plugin-vue2'`
3. 删除`vue-template-compiler`依赖

**Comment by belllee** [comment]
"vue": "2.7.8"
"vue-template-compiler": "2.7.8"
版本是配套的，webpack打包。vue和ElementUI打包成公共依赖，umd格式。应用里静态引入，也出现el-table出现空白的现象。
同步升级到最新的2.7.10后问题依旧。
有遇到这种情况的吗，怎么解决的？谢谢

**Comment by huaKai304** [comment]
> "vue": "2.7.8" "vue-template-compiler": "2.7.8" 版本是配套的，webpack打包。vue和ElementUI打包成公共依赖，umd格式。应用里静态引入，也出现el-table出现空白的现象。 同步升级到最新的2.7.10后问题依旧。 有遇到这种情况的吗，怎么解决的？谢谢

我参考这位解决
[](https://github.com/ElemeFE/element/issues/22102#issuecomment-1225233684)

**Comment by ldwqh0** [comment]
@belllee 
参考这个答案 https://github.com/ElemeFE/element/issues/21984
我就是这么处理的，问题已经解决。
webpack的配置中，添加如下
resolve: {
        alias: {
            vue$: 'vue/dist/vue.esm.js',
        },
    },

**Comment by belllee** [comment]
> ```js
> resolve: {
>     alias: {
>         vue$: 'vue/dist/vue.esm.js',
>     },
> },
> ```

非常感谢，按照这个设置正常了

**Comment by CoderYuanHub** [comment]
> 2\. import createVuePlugin from '@vitejs/plugin-vue2'
这个方法可行

**Comment by CoderYuanHub** [comment]
> 1. 安装  @vitejs/plugin-vue2
> 2. 在 vite.config.js里, 将 `import { createVuePlugin } from 'vite-plugin-vue2'` 改成 `import createVuePlugin from '@vitejs/plugin-vue2'`
> 3. 删除`vue-template-compiler`依赖

这个方法可以

**Comment by jetBn** [comment]
> 1. 安装  @vitejs/plugin-vue2
> 2. 在 vite.config.js里, 将 `import { createVuePlugin } from 'vite-plugin-vue2'` 改成 `import createVuePlugin from '@vitejs/plugin-vue2'`
> 3. 删除`vue-template-compiler`依赖

一定要用@vitejs/plugin-vue2 这个库吗

**Comment by fantasy525** [comment]
@ZGH0717 别关啊,问题没有全部解决呢，我用的就是 @vitejs/plugin-vue2,vue2.7.13 也并没有解决，发现是用了两个不同的vue,一个是自己业务会引入esm版本的vue,一个是element-ui引入了commonjs风格的vue。现在也是啥都没渲染

**Comment by jetBn** [comment]
> @ZGH0717 别关啊,问题没有全部解决呢，我用的就是 @vitejs/plugin-vue2,vue2.7.13 也并没有解决，发现是用了两个不同的vue,一个是自己业务会引入esm版本的vue,一个是element-ui引入了commonjs风格的vue。现在也是啥都没渲染

现在咋解决的？

**Comment by fantasy525** [comment]
> > @ZGH0717 别关啊,问题没有全部解决呢，我用的就是 @vitejs/plugin-vue2,vue2.7.13 也并没有解决，发现是用了两个不同的vue,一个是自己业务会引入esm版本的vue,一个是element-ui引入了commonjs风格的vue。现在也是啥都没渲染
> 
> 现在咋解决的？

@jetBn 已解决，看这个 https://github.com/ElemeFE/element/issues/21984

**Comment by de1ck** [comment]
我是通过添加 vue alias 解决
// vite.config.js
resolve: {
        extensions: ['.js', '.vue', '.jsx', 'tsx', '.json'],
        alias: {
            vue: 'vue/dist/vue.esm.js',
        },
    },

**Comment by fanlun008** [comment]
> 我是通过添加 vue alias 解决
> 
> ```js
> // vite.config.js
> resolve: {
>         extensions: ['.js', '.vue', '.jsx', 'tsx', '.json'],
>         alias: {
>             vue: 'vue/dist/vue.esm.js',
>         },
>     },
> ```

work! ur my hero

**Comment by qiufengming** [comment]
我用vue/cli3初始化的项目，webpack竟然不是webpack4，而是webpack5，然后安装 element-ui 并引用样式却不生效是为啥？

**Comment by Kerlli** [comment]
> > 我是通过添加 vue alias 解决
> > // vite.config.js
> > resolve: {
> >         extensions: ['.js', '.vue', '.jsx', 'tsx', '.json'],
> >         alias: {
> >             vue: 'vue/dist/vue.esm.js',
> >         },
> >     },
> 
> work! ur my hero

This also works for rsbuild, thanks
