### ISSUE TITLE
关于 el-select 有默认值后，设置 filterable 为 true 首次点击其他数据被过滤的问题

### ISSUE THREAD

**Issue by lanjuzi** [ElemeFE/element#2196]
首先 Demo：http://jsfiddle.net/59q6rzcr/1/

然后就是在给 el-select 加上 filterable 后，如果有默认值，在给定默认值后，默认选中项在首次点击的时候会被当作过滤条件，导致误以为只有一个默认选项。

个人认为基于体验来说，默认值不应当作为过滤条件。

**Comment by renxia** [comment]
这个问题我也发现了，之前应该不是这样的，应该修正过来比较好。示例：
https://jsfiddle.net/gmve9d3p/113/

**Comment by xbool** [comment]
@baiyaaaaa , 如果默认值是整数 -1，会报错
```
[Vue warn]: Error in watcher "query" 
(found in component <ElSelect>)
```

**Comment by xbool** [comment]
@baiyaaaaa  还有一个问题是，设置了 filterable 的 select 的右侧箭头是不可点击的 :)

**Comment by Leopoldthecoder** [comment]
@xbool 你的问题请新开一个 issue。
