### ISSUE TITLE
[Bug Report] DatePicke的disabledDate参数问题

### ISSUE THREAD

**Issue by wwg9311** [ElemeFE/element#21966]
### Element UI version
2.13.0

### OS/Browsers version
Window 11 / 

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/wwg9311/pen/zYWxQxG

### Steps to reproduce
设置的禁选时间为当天0点之前，点击当前时间，无反应

### What is Expected?
应该正确选择当前时间点

### What is actually happening?
无反应

**Comment by zhangyupeng233** [comment]
我也遇到了类似的问题, 请问是如何解决的
