### ISSUE TITLE
[table] 组件列属性 show-overflow-tooltip 在 Safari 上无作用

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#2198]
如题，示例参考：

https://jsfiddle.net/gmve9d3p/112/

看了下是使用 col 的方式实现的固定列宽度，但在 Safari 上好像是无效的，仍然被内部 `no-warp` 属性的元素撑开了。
也没想到好的解决方法。
或者所有的 `td >*` 都如 col 上一样强制设置宽度？

**Comment by reverland** [comment]
额。。。jsfiddle在safari下竟然挂了。。

**Comment by Kingwl** [comment]
+1

**Comment by renmingliang** [comment]
https://github.com/ElemeFE/element/issues/10308#issuecomment-686446725
