### ISSUE TITLE
拉取ElementUI源码之后，执行yarn报错，电脑是 Apple M1 Pro

### ISSUE THREAD

**Issue by LauGaHo** [ElemeFE/element#21983]
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
[4/4] 🔨  Building fresh packages...
[1/3] ⠐ fsevents
[2/3] ⠐ node-sass
warning Error running install script for optional dependency: "/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/liujiahao/Documents/MyProject/element/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@14.15.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v83-darwin-x64.tar.gz
node-pre-gyp http 403 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gypgyp  infoinfo  it worked if it ends withit worked if it ends with ok
 ok
gyp gypinfo  infousing  node-gyp@3.8.0
using node-gyp@3.8.0
gyp info using node@14.15.0 | darwin | x64
gyp info using node@14.15.0 | darwin | x64
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gypgyp info using node-gyp@3.8.0
gyp info  usinginfo node@14.15.0 | darwin | x64
 it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | darwin | x64
gyp gypERR! configure error
 ERR! configure error
gyp ERR! stack Error: Can't find Python executable \"python2.7\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR!gyp  stackERR!     at PythonFinder.<anonymous> (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:406:16)
 gypstack  Error: Can't find Python executable \"python2.7\", you can set the PYTHON env variable.
ERR! gypstack      at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:16)
ERR!gyp  stackERR!     at PythonFinder.failNoPython (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:484:19)
 stackgyp     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
 gypERR!  ERR!stack      at PythonFinder.<anonymous> (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:406:16)
stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gypgyp  ERR!ERR!  stackstack     at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:16)
     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gypgyp  ERR!ERR!  stackstack     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gypgyp  ERR!ERR!  Systemstack Darwin 21.5.0
     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! command \"/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node\" \"/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\" \"--python=python2.7\"
gyp ERR! cwd /Users/liujiahao/Documents/MyProject/element/node_modules/fsevents
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gypgyp  ERR!ERR!  not okSystem
 Darwin 21.5.0
gyp ERR! command \"/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node\" \"/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\" \"--python=python2.7\"
gyp ERR! cwd /Users/liujiahao/Documents/MyProject/element/node_modules/fsevents
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node /Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --python=python2.7' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command \"/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node\" \"/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/liujiahao/Documents/MyProject/element/node_modules/fsevents
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node /Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/liujiahao/Documents/MyProject/element/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_ab[-/3] ⠁ waiting...
[2/3] ⠂ node-sass
error /Users/liujiahao/Documents/MyProject/element/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/liujiahao/Documents/MyProject/element/node_modules/node-sass
Output:
Building: /Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node /Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node',
gyp verb cli   '/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2.7" in the PATH
gyp verb `which` failed Error: not found: python2.7
gyp verb `which` failed     at getNotFoundError (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2.7 Error: not found: python2.7
gyp verb `which` failed     at getNotFoundError (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/liujiahao/.nvm/versions/node/v14.15.0/bin/node" "/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/liujiahao/Documents/MyProject/element/node_modules/node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by MinatoHikari** [comment]
intel 也报错

**Comment by LauGaHo** [comment]
> intel 也报错

你的报错原因是什么吗？

**Comment by MinatoHikari** [comment]
> > intel 也报错
> 
> 你的报错原因是什么吗？

重新装了遍依赖，没报错了

**Comment by LauGaHo** [comment]
> > > intel 也报错
> 
> > 
> 
> > 你的报错原因是什么吗？
> 
> 
> 
> 重新装了遍依赖，没报错了

方便加个微信沟通一下吗？Wechat：15820685244

**Comment by LauGaHo** [comment]
> > > intel 也报错
> 
> > 
> 
> > 你的报错原因是什么吗？
> 
> 
> 
> 重新装了遍依赖，没报错了

我当时报错的依赖就是fsevent和node-sass依赖

**Comment by MinatoHikari** [comment]
> > > > intel 也报错
> > 
> > 
> > > 
> > 
> > 
> > > 你的报错原因是什么吗？
> > 
> > 
> > 重新装了遍依赖，没报错了
> 
> 我当时报错的依赖就是fsevent和node-sass依赖

这两个依赖报错是你node-sass的二进制没下载成功，然后会尝试自己编译
看了下你的报错，有个找不到python2.7

**Comment by LauGaHo** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> > > > > intel 也报错
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你的报错原因是什么吗？
> 
> > > 
> 
> > > 
> 
> > > 重新装了遍依赖，没报错了
> 
> > 
> 
> > 我当时报错的依赖就是fsevent和node-sass依赖
> 
> 
> 
> 这两个依赖报错是你node-sass的二进制没下载成功，然后会尝试自己编译
> 
> 看了下你的报错，有个找不到python2.7

是node-sass依赖着python2.7吗？

**Comment by MinatoHikari** [comment]
编译的时候要

**Comment by LauGaHo** [comment]
> 编译的时候要

那我先尝试一下先安装一下python2.7

**Comment by wiirhan** [comment]
把node换成12就好了

**Comment by LauGaHo** [comment]
> 把node换成12就好了

我换成了 node 12 版本，但是还是在同样的报错

**Comment by wiirhan** [comment]
> 

把yarn.lock和node_modules都删了

**Comment by LauGaHo** [comment]
> > 
> 
> 把yarn.lock和node_modules都删了

我这次把yarn.lock删掉了，然后这次报错没有报fsevent的错误，报了 node-sass，我在想，这个node-sass的问题是不是M1芯片的兼容性导致的？报错信息如下：
error /Users/liujiahao/Documents/MyProject/element/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/liujiahao/Documents/MyProject/element/node_modules/node-sass
Output:
Building: /Users/liujiahao/.nvm/versions/node/v12.5.0/bin/node /Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/liujiahao/.nvm/versions/node/v12.5.0/bin/node',
gyp verb cli   '/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.5.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2.7" in the PATH
gyp verb `which` failed Error: not found: python2.7
gyp verb `which` failed     at getNotFoundError (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2.7 Error: not found: python2.7

**Comment by LauGaHo** [comment]
> 
我刚刚尝试了一下分开两个版本来装依赖，再执行那个打包的npm脚本，除了样式的文件，其他都可以打包成功，然后它提示我执行 npm rebuild [node-sass。我按照着来执行，然后就冒出了这个错误了：
[alt](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/bsjTTl.png)

gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/liujiahao/Documents/MyProject/element/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/liujiahao/.nvm/versions/node/v10.13.0/bin/node" "/Users/liujiahao/Documents/MyProject/element/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/liujiahao/Documents/MyProject/element/node_modules/node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1

**Comment by wiirhan** [comment]
> 

没看懂你的问题，你指的哪个打包的npm脚本？为啥你需要本地打包element代码，如果你需要打包过的代码可以下载官方提供的。

**Comment by LauGaHo** [comment]
> > 
> 
> 
> 
> 没看懂你的问题，你指的哪个打包的npm脚本？为啥你需要本地打包element代码，如果你需要打包过的代码可以下载官方提供的。

刚刚所说的是代码没引用node-sass就可以运行，引用到了node-sass的地方就报错

**Comment by LauGaHo** [comment]
> > 
> 
> 
> 
> 没看懂你的问题，你指的哪个打包的npm脚本？为啥你需要本地打包element代码，如果你需要打包过的代码可以下载官方提供的。

不过现在解决了，本质上其实是node-sass需要python2.7，但是python2已经不维护了，不能通过homebrew安装，最后使用了pyenv来装python2.7的环境才成功装上依赖，放弃了5次之后才成功

**Comment by LauGaHo** [comment]
问题已解决，随手Mark一下。

由于在新版的 MacOS上 再也没有预装 Python2，但是 node-sass 这个依赖又是依赖着 Python2，所以就会导致报错的出现。
然后现在也无法通过 Homebrew 无法安装 Python2.7。所以只可以使用迂回的方法实现。

实现方式：①、执行 brew install pyenv。②、通过 pyenv 安装 2.7.18 的Python环境：pyenv install 2.7.18。③、设置对应的环境变量。

具体的实现在此链接中有详细的记录：https://www.wyr.me/post/658

**Comment by LeoWang1991** [comment]
node版本切到11 亲测可行

**Comment by coder-fang** [comment]
> 然后切换到node12版本，再执行yarn
node 切换到10 执行 yarn ，安装依赖没有报错；但是，node切换到12.22.12，执行yarn ，报错 ：
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
[1/2] ⡀ node-sass
error H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\node-sass
Output:
Building: G:\mySoftwares\Node\node.exe H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'G:\\mySoftwares\\Node\\node.exe',
gyp verb cli   'H:\\我的编程学习代码\\我的开源项目\\我参与的开源项目\\element\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.22.12 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:80:29)
gyp verb `which` failed     at H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:89:16
gyp verb `which` failed     at H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:168:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:80:29)
gyp verb `which` failed     at H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\which\which.js:89:16
gyp verb `which` failed     at H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:168:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python G:\mySoftwares\Python3.8.0\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: G:\mySoftwares\Python3.8.0\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "G:\\mySoftwares\\Node\\node.exe" "H:\\我的编程学习代码\\我的开源项目\\我参与的开源项目\\element\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd H:\我的编程学习代码\我的开源项目\我参与的开源项目\element\node_modules\node-sass
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1


> node版本切到11 亲测可行

**Comment by cinyearchan** [comment]
1. 如果装了 pyenv，pyenv 装了 python 2 （例如 2.7.11）python 3 （例如 3.9.7），`pyenv global 2.7.11 3.9.7`
2. nvm 切换到 node 10，我的是 `nvm use 10.15.0`
3. `npm i node-gyp -g`
4. 项目里通过 `yarn` 安装依赖
5. 项目里 `npm rebuild node-sass`

上面一套下来，我的不再报错，另外在项目里 `node -v > .nvmrc` 来指定当前项目使用的 node 版本
