### ISSUE TITLE
 el-upload 组件报 [Vue warn] (Vue 2.1.8)

### ISSUE THREAD

**Issue by k55k32** [ElemeFE/element#2200]
### info
> [Vue warn]: existing instance property "headers" will be overwritten by a computed property with the same name. 
> (found in component <el-upload>)
> [Vue warn]: existing instance property "headers" will be overwritten by a computed property with the same name. 
> (found in component <upload>)

`Vue 2.1.8`
`element-ui 1.1.2`

**Comment by jikkai** [comment]
Close and comment
