### ISSUE TITLE
[table]组件建议单元格可以显示图片

### ISSUE THREAD

**Issue by zh870717** [ElemeFE/element#2201]

**Comment by jikkai** [comment]
这个功能是有的，大致上这样：
```
<el-table-column
      label="image">
      <template scope="scope">
        <img :src="scope.imageSrc" />
      </template>
    </el-table-column>
```

**Comment by sxhjlzl** [comment]
这里的scope="scope" 是什么用法，指的是什么数据

**Comment by QingWei-Li** [comment]
@sxhjlzl 看 vue 文档

**Comment by Keystion** [comment]
根据 Vuejs 的版本更新2.5版本之后`scope`更改成`slot-scope`，我来优化一下 @jikkai 的回答

**低于2.5版本的 Vuejs 用以下代码**

```
<el-table-column` label="image">
  <template scope="scope">
    <img :src="scope.imageSrc" />
  </template>
</el-table-column>
```

**<=2.5版本的Vuejs用以下代码**

```
<el-table-column` label="image">
  <template slot-scope="scope">
    <img :src="scope.imageSrc" />
  </template>
</el-table-column>
```

---

Chrome console warning

[HMR] bundle has 1 warnings

> (Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

**Comment by yanlee26** [comment]
not work yet

**Comment by zhubijia** [comment]
> 根据 Vuejs 的版本更新2.5版本之后`scope`更改成`slot-scope`，我来优化一下 @jikkai 的回答
> 
> **低于2.5版本的 Vuejs 用以下代码**
> 
> ```
> <el-table-column` label="image">
>   <template scope="scope">
>     <img :src="scope.imageSrc" />
>   </template>
> </el-table-column>
> ```
> **<=2.5版本的Vuejs用以下代码**
> 
> ```
> <el-table-column` label="image">
>   <template slot-scope="scope">
>     <img :src="scope.imageSrc" />
>   </template>
> </el-table-column>
> ```
> Chrome console warning
> 
> [HMR] bundle has 1 warnings
> 
> > (Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to  to denote scoped slots.

alt属性好像失效啊
