### ISSUE TITLE
在dialog中使用表单元素或upload组件，在点击的时候页面文字抖动

### ISSUE THREAD

**Issue by fangdown** [ElemeFE/element#2202]
示例：https://jsfiddle.net/vc0wwfz9/1/
点击下拉框
在chrome中会出现文字向右偏移，然后恢复
在Firefox中是正常的
请帮忙检验一下，chrome开发比较多，使用也比较多，这个体验不好

**Comment by Leopoldthecoder** [comment]
升到新版还会这样吗？

**Comment by fangdown** [comment]
Chrome 版本 55.0.2883.87 m 还是这样的

**Comment by jikkai** [comment]
@fangdown External Resources里的vue和elementui资源都换成新版试试看有没有这个问题

**Comment by lichinlichin** [comment]
我也是按钮悬停就抖
