### ISSUE TITLE
documentation: cors issue with upload examples

### ISSUE THREAD

**Issue by jbergstroem** [ElemeFE/element#2205]
Getting Cors Issues with the example file upload at the documentation site using Safari 

### OS/Browers version
macOS 10.2, safari 10/tech preview.

### Vue version
Irrelevant

### Reproduction Link
Visit: http://element.eleme.io/#/en-US/component/upload

### Steps to reproduce
Try using the file upload examples

### What is Expected?
A working example

### What is actually happening?
See screenshot:
<img width="783" alt="screen shot 2017-01-04 at 12 05 51 pm" src="https://cloud.githubusercontent.com/assets/176984/21646758/388770bc-d276-11e6-8363-4a2aa18ccded.png">

**Comment by liril-net** [comment]
@jbergstroem  I can not reproduce your situations, it works fine for me. Maybe u can try it again.

**Comment by jbergstroem** [comment]
@liril-net just to confirm: did you try uploading a file through the examples?

**Comment by liril-net** [comment]
@jbergstroem Yes, i have uploaded an image, everything works fine except the original image can not be loaded at start.
![snip20170105_4](https://cloud.githubusercontent.com/assets/16029685/21667224/11da9a4a-d332-11e6-918e-62166ef18ae9.png)
![snip20170105_3](https://cloud.githubusercontent.com/assets/16029685/21667228/1b27ee22-d332-11e6-8330-619e0fa6a1b7.png)

**Comment by QingWei-Li** [comment]
The POST is missing the `Access-Control-Allow-Origin` header after the OPTIONS. This is a [cors](https://github.com/expressjs/cors) bug https://github.com/expressjs/cors/issues/91 .

[jsonplaceholder](https://github.com/typicode/jsonplaceholder) is online fake REST API server. `cors` is one of its dependencies.
