### ISSUE TITLE
[Bug Report] 官网文档中 codepen里面关于vue的文件引用路径有误，但是我查看github源码的时候，发现链接已经修改了，但是并没有重新发布到官网文档中

### ISSUE THREAD

**Issue by CasualMing** [ElemeFE/element#22062]
### Element UI version
2.15.9

### OS/Browsers version
window10

### Vue version
2.7.8

### Reproduction Link
https://codepen.io/

### Steps to reproduce
官网文档中 codepen里面关于vue的文件引用路径有误，但是我查看github源码的时候，发现链接已经修改了，但是并没有重新发布到官网文档中
官网文档：https://element.eleme.cn/#/zh-CN/

### What is Expected?
可以正常 使用codepen在线查看，期望更新一下国内的

### What is actually happening?
使用codepen 在线查看组件的时候，会提示vue 不存在
![image](https://user-images.githubusercontent.com/40878104/182551300-e74a35dd-2f5b-4387-806b-1ab9fbe069be.png)
![Snipaste_2022-08-03_15-34-26](https://user-images.githubusercontent.com/40878104/182551373-d526c47b-22af-4239-83e8-0466808bd6e7.png)

**Comment by CasualMing** [comment]
> 

并且还有一个问题，readme 中，中国站内文档访问的链接有问题
![image](https://user-images.githubusercontent.com/40878104/182552063-d88f6e84-29f0-4bdc-be90-15f20146e079.png)
国内网站链接跳转的，明明是 https://element.eleme.cn/#/zh-CN 这个，但是readme 中确实往 http://element-cn.eleme.io/ 跳转

**Comment by xinguanhua** [comment]
官网已更新
