### ISSUE TITLE
Pagination 分页在IE9下显示异常

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/element#2209]
### ElementUI version
1.1.2

### OS/Browers version
win7/IE9

### Vue version
2.1.8

以下是官方例子的截图，请帮fix，谢谢！
![image](https://cloud.githubusercontent.com/assets/22360070/21668055/1fbf47d0-d339-11e6-85e5-5ca88fe88cdc.png)

**Comment by Randysheng** [comment]
请问你这个问题解决了吗?
