### ISSUE TITLE
[Feature Request] 分享一个快速查找 icon 名字的工具，希望打开 github 的 discution 功能，可以交流一下嘛

### ISSUE THREAD

**Issue by KyleBing** [ElemeFE/element#22107]
### Existing Component
No

### Component Name
图标查找

### Description
个人一直在用的工具，很好用，所以分享下：
工具地址：
> [https://kylebing.cn/tools/icons/](https://kylebing.cn/tools/icons/)
- 关键字筛选
- 点击直接复制实际的图标全名

![image](https://user-images.githubusercontent.com/12215982/185272165-cc5d76ea-df96-4ab4-9a50-812ee69ec62f.png)

**Comment by crane0** [comment]
确实不错。不过这种功能应该添加到代码中会更好一点吧
