### ISSUE TITLE
[Bug Report] Element Example codepen vue Link error

### ISSUE THREAD

**Issue by de1ck** [ElemeFE/element#22104]
### Element UI version
2.15.9

### OS/Browsers version
mac/chrome

### Vue version
2.7.8

### Reproduction Link
https://codepen.io/de1ck/pen/RwMqVow

### Steps to reproduce
elemenr codepen vue cdn error

### What is Expected?
elemenr codepen vue cdn normal

### What is actually happening?
elemenr codepen vue cdn error

**Comment by crane0** [comment]
element-ui has reached 2.15.9, but the version used on the official website is still 2.15.7.
This bug has been fixed, but the official website has not been updated to the latest version. refer to[#21736](https://github.com/ElemeFE/element/pull/21736)

**Comment by xinguanhua** [comment]
the official website has been updated to the latest version now
