### ISSUE TITLE
[Bug Report] MacBook Pro M1 执行 make dist 卡住，没有反应

### ISSUE THREAD

**Issue by duanhjlt** [ElemeFE/element#22110]
### Element UI version
2.15.9

### OS/Browsers version
MacBook Pro M1

### Vue version
2.7.9

### Reproduction Link
https://github.com/ElemeFE/element

### Steps to reproduce
yarn
yarn dist

### What is Expected?
编译通过

### What is actually happening?
Build completed in 4.594s

Hash: 1e9f8574ddfee33f9f7e
Version: webpack 4.46.0
Time: 4597ms
Built at: 08/20/2022 4:34:50 PM
   Asset     Size  Chunks                    Chunk Names
index.js  568 KiB       0  [emitted]  [big]  app
Entrypoint app [big] = index.js
 [0] external {"root":"Vue","commonjs":"vue","commonjs2":"vue","amd":"vue"} 42 bytes {0} [built]
 [2] ./src/utils/date.js 10.8 KiB {0} [built]
[49] multi ./src/index.js 28 bytes {0} [built]
[50] ./src/utils/popper.js 48.9 KiB {0} [built]
[51] (webpack)/buildin/global.js 472 bytes {0} [built]
[88] ./src/index.js   739 modules 1.2 MiB {0} [built]
     | ./src/index.js 8.53 KiB [built]
     | ./src/locale/index.js 1.17 KiB [built]
     | ./packages/input/index.js 165 bytes [built]
     | ./packages/tag/index.js 153 bytes [built]
     | ./packages/scrollbar/index.js 174 bytes [built]
     | ./packages/select/index.js 161 bytes [built]
     | ./packages/option/index.js 179 bytes [built]
     | ./packages/pagination/index.js 185 bytes [built]
     | ./packages/dialog/index.js 174 bytes [built]
     | ./packages/autocomplete/index.js 207 bytes [built]
     | ./packages/button/index.js 171 bytes [built]
     | ./packages/button-group/index.js 210 bytes [built]
     | ./packages/dropdown/index.js 183 bytes [built]
     | ./packages/dropdown-menu/index.js 218 bytes [built]
     | ./packages/dropdown-item/index.js 218 bytes [built]
     |       725 hidden modules
      83 hidden modules

编译到此，就没有反应了

**Comment by duanhjlt** [comment]
我换了其他的设备也这样了，当前的node版本是16.16.0, 降会到14版本就好了。应该是当前的编译脚本和node不兼容导致的。
有空就修改一下吧

**Comment by xinguanhua** [comment]
build相关问题，建议使用nvm切换到node11，该类问题主要是node-sass版本的问题，后续更新后应该会解决
