### ISSUE TITLE
[Bug Report] 官网在线实例中,所有在线运行的实例无法正常显示,因为引用的是vue3版本的资源

### ISSUE THREAD

**Issue by POKEZHANG** [ElemeFE/element#22131]
### Element UI version
2.15.9

### OS/Browsers version
ALL

### Vue version
2.7.10

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
element ui官网
1.打开任意组件
2.右侧代码下方有在线运行,点击进入

### What is Expected?
在线运行正常显示

### What is actually happening?
实际引用的vue默认版本换成vue3,导致无法展示功能

**Comment by crane0** [comment]
目前 element-ui 已经到2.15.9了，官网使用的还是2.15.7版本。
这个bug已修复，但还没有更新到官网，参考[#21736](https://github.com/ElemeFE/element/pull/21736)

**Comment by xinguanhua** [comment]
感谢反馈，官网已更新
