### ISSUE TITLE
[Bug Report] el-tabs  tab-position="left"时，点击分页后的标签，会回弹到顶部

### ISSUE THREAD

**Issue by dgy20** [ElemeFE/element#22142]
### Element UI version
2.9.2

### OS/Browsers version
Chrome  104.0.5112.102

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/duan1998/pen/NWMxdOj

### Steps to reproduce
 当tab-position="left"时，并且tab过多导致分页后，点击后续分页内的标签时 'transform: translateY()'属性的值会变为0

### What is Expected?
停留在当前位置

### What is actually happening?
 'transform: translateY()'属性的值会变为0

**Comment by xujintai123** [comment]
应该是你自定义样式导致的，如果需要自定义样式的话。看了下2.15.8版本使用你的自定义样式不会出现这个问题，建议升级版本

**Comment by dgy20** [comment]
> 应该是你自定义样式导致的，如果需要自定义样式的话。看了下2.15.8版本使用你的自定义样式不会出现这个问题，建议升级版本

找到原因了，是2.9.2版本的  tab-nav.vue  文件的 scrollToActiveTab  方法内，只处理了水平的情况，
