### ISSUE TITLE
如何全局配置 <message消息提示 > 的显示时间

### ISSUE THREAD

**Issue by hrsnl-darcy** [ElemeFE/element#2215]
如题， 我想在 all vue componet, this.$message[success, warning, error...] 配置一个统一的显示时间

**Comment by Leopoldthecoder** [comment]
自己包一层好了。另：请不要滥用 issue，此类问题应该去 Gitter 讨论。

**Comment by liuz666** [comment]
可以在main.js中对message方法进行重写，message默认挂在了vue原型对象上，所以修改vue.prototype.message方法就可以做到全局配置功能了。
