### ISSUE TITLE
日期时间选择器，选择同一天时，再用鼠标滚轮选择小时区间，两边会互相影响。

### ISSUE THREAD

**Issue by soylinen** [ElemeFE/element#22153]
日期时间选择器，选择同一天时，再用鼠标滚轮选择小时区间，两边选择时分秒的区域会互相影响。前者会趋于00.00.00。后者会趋于23.59.59   有知道如何处理的吗？

可以直接用官网操作，也可复现。
https://element.eleme.cn/#/zh-CN/component/datetime-picker#ri-qi-he-shi-jian-fan-wei

**Comment by 5z5** [comment]
这个设计很好啊，一起变化更有利于选择区间啊，

**Comment by soylinen** [comment]
并不啊，比如我选了今天的 6点05到23点05区间，我先选前面的时间，然后当我选择23点的时候，前面那个6点就已经变了，至于变成几，看你的滚轮操作了多少。

**Comment by 5z5** [comment]
它往大于6的滚就不会呀，往小于6的滚也滚不到23点的



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月19日 18:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ElemeFE/element] 日期时间选择器，选择同一天时，再用鼠标滚轮选择小时区间，两边会互相影响。 (Issue #22153) |

并不啊，比如我选了今天的 6点05到23点05区间，我先选前面的时间，然后当我选择23点的时候，前面那个6点就已经变了，至于变成几，看你的滚轮操作了多少。

**Comment by soylinen** [comment]
> 这个设计很好啊，一起变化更有利于选择区间啊，

哇，刚测试到了。那这个设计的确挺好。有意思
