### ISSUE TITLE
MenuItem not getting active class when using vue-router unless clicked on twice.

### ISSUE THREAD

**Issue by jkehler** [ElemeFE/element#2216]
### ElementUI version
1.1.2

### OS/Browers version
Version 54.0.2840.98 (64-bit)

### Vue version
2.1.0

### Steps to reproduce
Use Menu component with vue-router. I set prop to router="true" and pass in a route object to the MenuItem component. Eg route="{ path: '/users' }".

### What is Expected?
When clicking on a menu entry it should navigate to that route and also mark that route as active.

### What is actually happening?
Clicking on a menu entry successfully navigates to the new route via vue-router but it does not mark the route as active unless I click on the menu entry a 2nd time. On the 2nd click it will then mark the route as active and apply the active class.

**Comment by baiyaaaaa** [comment]
i don't know whether u use the `default-active` prop.  Can u give a demo?

**Comment by torresyb** [comment]
me too

**Comment by baiyaaaaa** [comment]
fix in #2399
