### ISSUE TITLE
[Bug Report] calendar interval  validator error

### ISSUE THREAD

**Issue by llllzw** [ElemeFE/element#22173]
### Element UI version
2.15.10

### OS/Browsers version
win10/edge 100

### Vue version
2.7.10

### Reproduction Link
https://codepen.io/LNoon/pen/MWGQgzR

### Steps to reproduce
set range ['2022-09-26' , '2022-11-06']

### What is Expected?
validate time span

### What is actually happening?
 from 2022-09-26 to 2022-11-06 , it's less than two months ,but get error : [ElementCalendar]start time and end time interval must not exceed two months

**Comment by xujintai123** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/66779465/192712570-5a6ce28e-ab74-4ad6-a985-f47bef5aa780.png">
看样子，内部是根据起始月份和终止月份的 月份跨度来判断的，起始日期为9月的某天的话，终止日期为10月的某天才不会警告。并不是使用天数来判断两个月间隔。

**Comment by llllzw** [comment]
> 
看了下源码确实是这样  感觉是文档描述不清了。      不行的话我用别的日历吧

**Comment by llllzw** [comment]
> <img alt="image" width="1018" src="https://user-images.githubusercontent.com/66779465/192712570-5a6ce28e-ab74-4ad6-a985-f47bef5aa780.png">
> 
> 看样子，内部是根据起始月份和终止月份的 月份跨度来判断的，起始日期为9月的某天的话，终止日期为10月的某天才不会警告。并不是使用天数来判断两个月间隔。 @xinguanhua 这个问题你们期待处理吗


看了下源码确实是这样 感觉是文档描述不清了。 不行的话我用别的日历吧

**Comment by xinguanhua** [comment]
感谢反馈，会优先考虑优化一下文案表述
