### ISSUE TITLE
NavMenu 导航菜单

### ISSUE THREAD

**Issue by youngthinker** [ElemeFE/element#2218]
### ElementUI version

1.0.9
### OS/Browers version

Windows7/Chrome 55
### Vue version

2.4.0
### Steps to reproduce
NavMenu 导航菜单
以JSON的方式载入
### What is Expected?
有一级菜单，二级菜单，三级菜单
如果二级菜单中有包含三级菜单的和不包含三级菜单的
生成的导航不会按照json中的顺序排列

### What is actually happening?
![-1](https://cloud.githubusercontent.com/assets/3690138/21672443/a32ff7bc-d35d-11e6-9711-f98aa1fb29c0.png)
生成的序号没有问题，但是排列有问题

**Comment by baiyaaaaa** [comment]
可以提供下demo么

**Comment by FannieGirl** [comment]
我也遇到了 求救怎么办
列表不会按照返回数据的顺序渲染
