### ISSUE TITLE
[Bug Report] 用vite开发的表格在开发模式不显示，发布版本可以正常显示

### ISSUE THREAD

**Issue by sisisiss** [ElemeFE/element#22190]
### Element UI version
2.15.10

### OS/Browsers version
win10 chrome

### Vue version
2.6.14

### Reproduction Link
https://jsfiddle.net/mmx38qsfxw/

### Steps to reproduce
工程很大，放不到jsfiddle里，用很旧的"element-ui": "^2.0.6"表格能显示，后面的版本都不显示
https://github.com/BigFrontEnd-China/vite-demo 测试可以用这个，插入表格不显示
开发模式不显示表格页面截图：https://suyuan-jtb2.flyinginternet.cn/1.png;打包出来正常的：https://suyuan-jtb2.flyinginternet.cn/2.png

### What is Expected?
表格不显示

### What is actually happening?
不显示没法调试

**Comment by pandeng-wangshufen** [comment]
你好，问题有解决吗？请问除了安装2.0.6的版本，还有其他的方法吗？@sisisiss

**Comment by sisisiss** [comment]
只有低版本的可以用，现在用的node-model也可以，只要安装其它包表格就不显示

**Comment by sisisiss** [comment]
> 你好，问题有解决吗？请问除了安装2.0.6的版本，还有其他的方法吗？@sisisiss
只有低版本的可以用，现在用的node-model也可以，只要安装其它包表格就不显示

**Comment by fantasy525** [comment]
vue2.7使用 element-ui@2.13.1也不展示table,感觉是更新cloumns后没有重新渲染

**Comment by yangweijie** [comment]
我也遇到了这个问题 能修复一下吗？ 不然 要么用旧版本 要么 用element-plus vue3 了 ，主要有些页面是旧版开发的 新项目想哪来用

**Comment by yangweijie** [comment]
试了下2.0.6  也不行 难道vite版本 也要指定某个版本才行

**Comment by chendahao** [comment]
vue 2.6.11  vite 3.1.6 在2.8.2版本table 可以正常显示，不过低版本少了一部分组件
