### ISSUE TITLE
Time&Datepicker: focus issues

### ISSUE THREAD

**Issue by jbergstroem** [ElemeFE/element#222]
### ElementUI version
Current version deployed at http://element.eleme.io/#/component/time-picker

### OS/Browers version
macOS 10.12: Safari, Safari technology preview 13 and Chrome 53.

### Vue version
See above

### Reproduction Link

![](http://i.imgur.com/ErD6r1A.gif)

### Steps to reproduce
Open time/datepicker, move your mouse over elements

### What is Expected?
Clicking on items yields action

### What is actually happening?
The datepicker looses focus and closes.

**Comment by QingWei-Li** [comment]
fixed in https://github.com/ElemeFE/element/issues/210

**Comment by jbergstroem** [comment]
Thanks for your quick response. Sorry -- didn't check master branch before filing the issue.
