### ISSUE TITLE
[Bug Report] el-talbe数据变化，试图不更新，使用计算属性或监听器都无效，包括给el-table加key,并在数据改变时修改key绑定的值也无效，坑真多，无语！！！！！！！！！

### ISSUE THREAD

**Issue by ConstancyMan** [ElemeFE/element#22200]
### Element UI version
2.15.10

### OS/Browsers version
win10

### Vue version
2.7.13

### Reproduction Link
https://github.com/ElemeFE/element/issues/new/choose

### Steps to reproduce
el-talbe数据变化，试图不更新，使用计算属性或监听器都无效，包括给el-table加key,并在数据改变时修改key绑定的值也无效，坑真多，无语！！！！！！！！！

### What is Expected?
当然是数据变化时试图也变化咯

### What is actually happening?
el-talbe数据变化，试图不更新，使用计算属性或监听器都无效，包括给el-table加key,并在数据改变时修改key绑定的值也无效，坑真多，无语！！！！！！！！！

**Comment by pureStyles** [comment]
多说客观的问题，少说主观的

**Comment by pureStyles** [comment]
无语的话就自己创作!

**Comment by yummyo** [comment]
有问题贴个代码，什么都不贴，能解决才见鬼了。

**Comment by xiongzhenggang** [comment]
代码没有，用猜解决吗

**Comment by ConstancyMan** [comment]
自己用强制刷新页面处理了
