### ISSUE TITLE
Popover 可以提供disabled参数支持吗

### ISSUE THREAD

**Issue by zhengjiaqi** [ElemeFE/element#2221]
Tooltip 组件有disabled 参数控制Tooltip 是否可用，Popover组件可以提供类似的参数控制吗

**Comment by QingWei-Li** [comment]
Popover 有提供 `trigger=manual` 选项，可以手动控制 Popover 的出现和隐藏，同样是通过 `v-model`

**Comment by zhengjiaqi** [comment]
我现在的需求是还是通过	click/focus/hover 等方式触发Popover 的出现和隐藏，只是在某些条件下click/focus/hover 这些触发方式失效，类似Tooltip 组件disabled:false的效果，manual应该不能实现这样的效果吧。

**Comment by QingWei-Li** [comment]
Okay

**Comment by reverland** [comment]
可以暂且v-if一波。。。

**Comment by zhengjiaqi** [comment]
<el-popover
  ref="popover1"
  placement="top-start"
  title="标题"
  width="200"
  trigger="hover"
  content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
</el-popover>
<el-button v-popover:popover1>hover 激活</el-button>

如果是这样使用popover，并且只在<el-popover v-if='xxx'></el-popover>上加if的话，当初始的if是false时，v-popover指令会报错。
因为此时的 el-popover 结构并不存在，v-popover指令会去取 ref="popover1" 的这个节点 ，也就是源码的 vnode.context.$refs[binding.arg]  这部分，此时取值是undefind 。
然后 v-popover:popover1这个指令就报错了。
即
bind(el, binding, vnode) {
    vnode.context.$refs[binding.arg].$refs.reference = el;
  }
报错。
所以v-if这个方法现在不能使用。

**Comment by reverland** [comment]
不是v-if popover，是指button。。。
