### ISSUE TITLE
[Bug Report] menu default-active is  not  reactive

### ISSUE THREAD

**Issue by wwhwwhwwh** [ElemeFE/element#22210]
### Element UI version
2.15.10

### OS/Browsers version
Chrome/95.0.4638.69 Safari/537.36

### Vue version
2.7.13

### Reproduction Link
https://codepen.io/wwhwwhwwh/pen/qBKWxxj

### Steps to reproduce
click `change menu` button ,change the  el-menu data  and  default-active

the default-active is change but the menu-item is not highlight

### What is Expected?
menu-item highlight with the  default-active   change 

### What is actually happening?
menu-item is not highlight

**Comment by Jalery521** [comment]
> ### Element UI version
> 2.15.10
> 
> ### OS/Browsers version
> Chrome/95.0.4638.69 Safari/537.36
> 
> ### Vue version
> 2.7.13
> 
> ### Reproduction Link
> https://codepen.io/wwhwwhwwh/pen/qBKWxxj
> 
> ### Steps to reproduce
> click `change menu` button ,change the el-menu data and default-active
> 
> the default-active is change but the menu-item is not highlight
> 
> ### What is Expected?
> menu-item highlight with the default-active change
> 
> ### What is actually happening?
> menu-item is not highlight

`<el-menu-item :key="index"`修改为`<el-menu-item :key="item.index"`

**Comment by wwhwwhwwh** [comment]
is right，thanks
