### ISSUE TITLE
el-date-picker 组件 daterange 模式 change事件触发问题

### ISSUE THREAD

**Issue by k55k32** [ElemeFE/element#2223]
在有默认值的情况下，点击组件框的时候，就会触发change事件
[http://jsfiddle.net/bmgsbhgh/2/](http://jsfiddle.net/bmgsbhgh/2/)
这个应该是要在选择值过后再触发 该事件吧

**Comment by QingWei-Li** [comment]
已知 Bug，修复在 https://github.com/ElemeFE/element/pull/2171
