### ISSUE TITLE
[Bug Report] Theme Chalk library gone from unpkg.com

### ISSUE THREAD

**Issue by alexbet** [ElemeFE/element#22255]
### Element UI version
2.15.11

### OS/Browsers version
Mac Os Ventura

### Vue version
2.7.14

### Reproduction Link
https://jsfiddle.net/r8ofj5eL/

### Steps to reproduce
I was loading the chalk theme from here:
https://unpkg.com/element-ui/lib/theme-chalk/index.css

which redirected to the newest version here:
https://unpkg.com/element-ui@2.15.11/lib/theme-chalk/index.css

Now, this is gone. Why? Why would you delete it from there? 

### What is Expected?
I expect the file to stay on upkg.com

### What is actually happening?
It is gone from unpkg.com

**Comment by xinguanhua** [comment]
try 2.15.12

**Comment by xinguanhua** [comment]
try 2.15.12
