### ISSUE TITLE
[Bug Report] CDN无法使用

### ISSUE THREAD

**Issue by ArvinJr** [ElemeFE/element#22254]
### Element UI version
2.15.11

### OS/Browsers version
所有系统

### Vue version
2.6.14

### Steps to reproduce
北京时间2022/11/15 22时30分，在正常使用过程中突然无法获取到由UNPKG提供的CDN服务
<img width="540" alt="image" src="https://user-images.githubusercontent.com/49033839/201946291-7b150e9e-6e34-44b8-b37d-cfec0b687450.png">

### What is Expected?
恢复正常使用

### What is actually happening?
暂未修复

**Comment by seaperson** [comment]
> ![image](https://user-images.githubusercontent.com/2902730/201950847-6dc693b2-540c-4eaf-a175-37115ffd3cb3.png)

可以指定上个版本https://unpkg.com/element-ui@2.15.10/lib/index.js
今天更新的2.15.11版本cdn上少了lib文件夹- 。-

**Comment by ArvinJr** [comment]
> 

好的，多谢

**Comment by tarteAuxPommes** [comment]
Same here !
I already changed the version but it's not the best option.

**Comment by seaperson** [comment]
> Same here ! I already changed the version but it's not the best option.

Yes!I think this update is so strange.

**Comment by xinguanhua** [comment]
you can try 2.15.12, should has solved this problem
