### ISSUE TITLE
[Bug Report] 2.15.12打包出现css编译错误

### ISSUE THREAD

**Issue by alen256** [ElemeFE/element#22260]
### Element UI version
2.15.12

### OS/Browsers version
MacOS 16

### Vue version
2.7.14

### Reproduction Link
https://github.com/ElemeFE/element

### Steps to reproduce
npm run build

### What is Expected?
打包成功

### What is actually happening?
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...ttom:4px;color:": expected expression (e.g. 1px, bold), was "#00073;font-size:14"
        on line 1 of node_modules/element-ui/lib/theme-chalk/index.css
>> el-statistic .head{margin-bottom:4px;color:#00073;font-size:14px}.el-statist
   ------------------------------------------^

**Comment by webvs2** [comment]
Just a moment, I'll check the problem

**Comment by syrm-ll** [comment]
我也遇到这个问题, 不只是打包 运行时就会报错

临时解决方案: 不要使用 css import , 在 main.js 或其他文件内直接 `import 'element-ui/lib/theme-chalk/index.css'`

**Comment by webvs2** [comment]
@syrm-ll Will be fixed in a minor release, watch for post-release updates

**Comment by webvs2** [comment]
@alen256

**Comment by rss1360855713** [comment]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/69237137/204179825-d38766f2-1266-42af-8321-9da1475ffb8c.png">
