### ISSUE TITLE
[Bug Report] 2.15.12 包含了 "web-types": "./web-types.json" 属性, 但是发布后没有包含 web-types.json 文件 🤣

### ISSUE THREAD

**Issue by syrm-ll** [ElemeFE/element#22261]
### Element UI version
2.15.12

### OS/Browsers version
win11 22621.819 / Edge  107.0.1418.42

### Vue version
2.7.14

### Reproduction Link
https://github.com/ElemeFE/element/blob/dev/package.json#L62

### Steps to reproduce
这是个IDE支持问题, 并非BUG

参考: https://github.com/ElemeFE/element/pull/22135  好像昨天合并到dev 分支的

原提交没有修改 element-ui 的打包配置, 位于仓库根路径的 `web-types.json` 打包时被忽略了, 导致IDE内不仅没有 web-types 的类型增强, 还丢失了原有类型推断, 连组件名称都不提示了

### What is Expected?
package.json 包含 ` "web-types": "./web-types.json"` 属性
element-ui 发包时包含仓库根路径的 web-types.json 文件

### What is actually happening?
仅包含  "web-types" 属性

**Comment by syrm-ll** [comment]
我现在需要手动给  `https://github.com/ElemeFE/element/blob/dev/web-types.json` 下载到 node_modules 下 element-ui 的安装目录 累死了

**Comment by AemonCao** [comment]
原来是这个原因，昨天调整了一下午的IDE设置，硬是没解决这个问题。

> 我现在需要手动给 https://github.com/ElemeFE/element/blob/dev/web-types.json 下载到 node_modules 下 element-ui 的安装目录 累死了

目前安装这个方式暂时解决了，希望官方尽快解决。

**Comment by lyon007** [comment]
> 原来是这个原因，昨天调整了一下午的IDE设置，硬是没解决这个问题。
> 
> > 我现在需要手动给 https://github.com/ElemeFE/element/blob/dev/web-types.json 下载到 node_modules 下 element-ui 的安装目录 累死了
> 
> 目前安装这个方式暂时解决了，希望官方尽快解决。

+1，整半天，差点不自信了

**Comment by moonheart** [comment]
感谢，原来是这个原因。升级了 IDEA 2022.3 发现不能提示了，还以为是 IDEA 的问题。

**Comment by AlanQtten** [comment]
@lyon007 @moonheart element-ui的提示倒是出来了，可是按住alt+左键IDE说不知道该跳转哪里。。。（Cannot find declaration to go to）
我的另外几个项目都有element-ui，我查看了他们的node_modules下面也没有这个web-types.json，可是他们却能正常显示element的提示，按alt+左键也可以正常跳转

**Comment by moonheart** [comment]
@AlanQtten 经过验证，确实是 `2.15.11` 起引入的 `web-types` 导致的问题，即使手动引入 `web-types.json` 也会有 `Cannot find declaration to go to` 的问题。
解决方法是 删除 `node_modules/element-ui/package.json` 中的 `web-type` 字段，删除后功能都恢复正常。

**Comment by AlanQtten** [comment]
@moonheart 请问你的element是什么版本的呢？😂我删了web-types字段，又回到最初的Unknown html tag el-xxx了

**Comment by moonheart** [comment]
@AlanQtten `2.15.11`，移除了 `web-types` 字段，可以正常工作，需要重启 IDEA

**Comment by syrm-ll** [comment]
> @moonheart 请问你的element是什么版本的呢？😂我删了web-types字段，又回到最初的Unknown html tag el-xxx了

.vue template IDE 是当 HTML 解析的, 所以才会有 `Unknown html tag` 警告, 一般我都直接关闭这个检查 没啥意义

`Cannot find declaration to go to` 这个使用 `pnpm` 安装依赖会出现, `npm` 和 `yarn` 没问题

---

`element-ui 2.15.11` (含) 之前,  一直有 `不能识别的 vue 指令` (v-loading) 的问题,  在 JetBrains YouTrack 有很多问题 吵了很久, 最后 <https://github.com/ElemeFE/element/pull/22135> 添加了 `web-types` 类型声明

含有有效 `web-types` 属性的 Vue UI 组件库可以正常提示 (包括 pnpm), 但不保证能跳转到类型声明.

**Comment by ywenhao** [comment]
@webvs2  
2.15.12npm包里面没找到web-types.json文件
