### ISSUE TITLE
[Bug Report] Table表格刷新的时候，expand列会被强制折叠起来，能否保持原有状态不变？

### ISSUE THREAD

**Issue by chenyahui** [ElemeFE/element#22295]
### Element UI version
2.15.12

### OS/Browsers version
macos chrome 107.0.5304.110

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/cyhone/pen/QWxVgjr

### Steps to reproduce
1. 展开表格的第一列
2. 点击刷新，表格的展开内容会被自动收缩

### What is Expected?
表格的展开形式保持原样

### What is actually happening?
展开的内容被强制收缩了

**Comment by Aaron-zon** [comment]
我看示例是重新设置了table的数据源，正常就是应该整块重新渲染，如果单独修改某一个属性则不会整个table重新渲染，我觉得element本身应该没有解决这个问题的功能，可以考虑自己实现吧。

另外我有个疑问，如果数据源中第一列【hi】被选择了，当前为下拉状态，在进行刷新后【hi】整个列都被删除了第一列还要下拉状态么？

**Comment by ecanspace** [comment]
根据你的示例，可以配置 row-key="phone" 属性，告诉 Table 组件根据你的 key 进行渲染

**Comment by chenyahui** [comment]
> 根据你的示例，可以配置 row-key="phone" 属性，告诉 Table 组件按照给定的 key 进行渲染，这样行的状态将被保留，否则一旦数据更新，将被当做新的行进行处理。

@ecanspace 果然可以了，非常感谢
