### ISSUE TITLE
Dialog页面上存在el-radio控件，当出现纵向滚动条时，点击radio按钮画面会闪一下

### ISSUE THREAD

**Issue by 5456435** [ElemeFE/element#223]
### Steps to reproduce
1 创建el-dialog，并且上面有很多的按钮，其中包含el-radio
2 显示dialog后，滑动滚动条到最下面。
3 点击el-radio
### What is Expected?
画面会闪动一下，再回到原来的位置。
### What is actually happening?
画面不闪动。

**Comment by Leopoldthecoder** [comment]
请给出在线 Demo
