### ISSUE TITLE
checkbox选中后样式无任何改变

### ISSUE THREAD

**Issue by SimonLeeee** [ElemeFE/element#2230]
checkbox选中后，
控制台中 ：输出了选中的对象
DOM中   ：添加了 选中的样式 

但是checkbox的框框依然保持未选中的状态

**Comment by cooperding** [comment]
我本地也是这样，无法选中，vue2.1.8，element1.1.2版本

**Comment by cooperding** [comment]
@SimonLeeee   重新引入了下这个 //unpkg.com/element-ui/lib/theme-default/index.css   又可以了，奇怪下载的时候文件和这个样式不一样。

**Comment by baiyaaaaa** [comment]
如果能复现的话可以提供下demo

**Comment by SimonLeeee** [comment]
@cooperding     你的CSS文件是import进来的吗？

@baiyaaaaa  我的css文件并没参与打包， 仅在html用 link标签引用

**Comment by SimonLeeee** [comment]
@baiyaaaaa 我把node_modules删了， 重新installl一次就行了

**Comment by David1119** [comment]
同样出现该问题，不显示对号
