### ISSUE TITLE
el-select multiple with vuex

### ISSUE THREAD

**Issue by jkehler** [ElemeFE/element#2231]
### ElementUI version
1.1.2

### OS/Browers version
Chrome 54

### Vue version
2.1.0

### Steps to reproduce
I am unable to get VueX to work with a multiple el-select component. I've found numerous tickets that referenced #1632 and tried implementing it in my own code. This workaround works fine when multiple is not used. But when using multiple it does not work.

**Comment by Leopoldthecoder** [comment]
Seems working: https://jsfiddle.net/hq4scjto/15/
Please note that the initial `value` should be an array.

**Comment by wilsonIs** [comment]
@Leopoldthecoder  示例中没有执行update函数，并没有触发input事件，而是通过数组直接push进了value中，严格模式下，报错

**Comment by Phillys** [comment]
@Leopoldthecoder this is still an issue as @wilsonIs explains.
The `input` event will never be emitted when using the `multiple` attribute:
https://github.com/ElemeFE/element/blob/dev/packages/select/src/select.vue#L507

This breaks compability with vuex.

**Comment by Leopoldthecoder** [comment]
I'll try to fix this.

**Comment by Phillys** [comment]
Please review my [PR](https://github.com/ElemeFE/element/pull/4226) @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
Fixed in #4226
