### ISSUE TITLE
bug 日期范围选择框，默认赋值后，点X无法清除

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#2232]
版本：1.1.2
bug 日期范围选择框，默认赋值后，点X无法清除，
弹出框选择日期后，是可以清除的

![Uploading image.png…]()

**Comment by QingWei-Li** [comment]
请提供 demo

**Comment by QingWei-Li** [comment]
Thx

这问题修复在 https://github.com/ElemeFE/element/pull/2171 今天会发布新版
