### ISSUE TITLE
[Bug Report] vue2.7使用form表单会报错

### ISSUE THREAD

**Issue by Wuge-Ran** [ElemeFE/element#22324]
### Element UI version
2.15.12

### OS/Browsers version
mac

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/Wuge-Ran/pen/abjOGwe

### Steps to reproduce
<template>
  <div class="create-device-wrapper" style="height: 700px;">
    <el-steps direction="vertical" :active="1">
      <el-step title="连接相机">
        <template slot="description">
          <el-form :model="ruleForm" :rules="rules" ref="ruleForm" label-width="100px" class="demo-ruleForm">
            <el-form-item label="活动名称" prop="name">
              <el-input v-model="ruleForm.name"></el-input>
            </el-form-item>
            
          </el-form>
        </template>
      </el-step>
      <el-step title="相机信息"></el-step>
      <el-step title="完成"></el-step>
    </el-steps>
  </div>
</template>

<script lang="ts" setup>
import { reactive, ref } from 'vue';

const ruleForm = reactive({
  name: '',
  region: '',
  date1: '',
  date2: ''
});

const rules = {
  name: [
    { required: true, message: '请输入活动名称', trigger: 'blur' },
    { min: 3, max: 5, message: '长度在 3 到 5 个字符', trigger: 'blur' }
  ],
  region: [
    { required: true, message: '请选择活动区域', trigger: 'change' }
  ],
  date1: [
    { type: 'date', required: true, message: '请选择日期', trigger: 'change' }
  ],
  date2: [
    { type: 'date', required: true, message: '请选择时间', trigger: 'change' }
  ]
};

</script>

<style lang="scss" scoped>
</style>

### What is Expected?
正常使用

### What is actually happening?
输入会报出Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option.的错误

**Comment by Wuge-Ran** [comment]
使用单个的input是正常的但使用form就会报错

**Comment by Wuge-Ran** [comment]
ref和model命名重复的问题

**Comment by EntrustCC** [comment]
> ref和model命名重复的问题

谢谢

**Comment by shangjundragon** [comment]
> ref和model命名重复的问题

谢谢
