### ISSUE TITLE
[Bug Report] WebStorm使用el-button时候 type 属性提示有问题

### ISSUE THREAD

**Issue by DayangAB** [ElemeFE/element#22339]
### Element UI version
2.15.12

### OS/Browsers version
Windows10 22H2 、Chrome最新版

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/ziyoung/pen/LKNBqB

### Steps to reproduce
输入type的时候，WebStorm 2022.3.1 会自动提示可选项，只有在选 text 的时候，后边会多一个分号，导致最终样式不对；
手动删除，IDE有提示错误，text 不是 type 的有效值。预期值: primary、success、warning、danger、info或text;
<el-button type="text;"

一句话总结：text后边多写了一个分号

### What is Expected?
<el-button type="text"></el-button>

### What is actually happening?
<el-button type="text;"></el-button>

**Comment by OneGIl** [comment]
2.15.13 解决了这个问题~
