### ISSUE TITLE
[Bug Report] statistic 數值計算問題

### ISSUE THREAD

**Issue by MarkGor** [ElemeFE/element#22352]
### Element UI version
2.15.12

### OS/Browsers version
不限

### Vue version
2.7.14

### Steps to reproduce
<statistic group-separator="," :precision="2" :value="1440" />

### What is Expected?
輸出1,440

### What is actually happening?
輸出1,44

**Comment by webvs2** [comment]
Please provide a minimum repetition example

**Comment by MarkGor** [comment]
> Please provide a minimum repetition example

hi,just use:
` <el-statistic group-separator="," :precision="2" :value="1440" ></el-statistic>`

**Comment by webvs2** [comment]
Ok, I'll look at that

**Comment by webvs2** [comment]
> > 请提供最小重复示例
> 
> 嗨，只需使用： ` <el-statistic group-separator="," :precision="2" :value="1440" ></el-statistic>`
> 
> 现在没问题，我在此[提交](https://github.com/ElemeFE/element/commit/fa18776b4b40088e9144d8ea529be73c283bdcd5)中看到修复，谢谢

OK, welcome to ask questions to help improve
