### ISSUE TITLE
[Bug Report] Cascader 级联选择器 部分浏览器选择后页面卡死

### ISSUE THREAD

**Issue by gangweihua** [ElemeFE/element#22358]
### Element UI version
2.15.1

### OS/Browsers version
win10 谷歌 109.0.5414.75

### Vue version
2.7.14

### Reproduction Link
https://github.com/ElemeFE/element/issues/new/choose

### Steps to reproduce
官网使用 Cascader 可搜索组件
点击输入框
输入汉字  一
选中输入框下显示的数据
再点击输入框
浏览器卡死

只有部分电脑浏览器会出现，原因未知

### What is Expected?
正常显示

### What is actually happening?
浏览器卡死

**Comment by ilexwg** [comment]
I have the same problem!

**Comment by polliaC** [comment]
I have the same problem!

**Comment by tianlmn** [comment]
+1，一样的问题。
windows的chrome升级到最新版后，点击cascader后没有弹出下拉框。多点几次后页面卡死。elementui版本2.13.0

**Comment by supperdsj** [comment]
I have the same problem!

**Comment by Harris-peng** [comment]
+1
I have the same problem!

**Comment by ZhangChongLing** [comment]
"element-ui": "2.15.5"，chrome 109.0.5414.120，window 操作系统。have the same problem!

**Comment by mountain410** [comment]
一样的问题，有没有解决办法？不同用户浏览器版本不受控制啊。。

**Comment by ZhangChongLing** [comment]
请放心，您的邮件已收到。

**Comment by xinguanhua** [comment]
升级到chrome最新版本110.0.5481.78即可
