### ISSUE TITLE
element-ui 自定义主题功能现在不能使用

### ISSUE THREAD

**Issue by ZhongHongLi** [ElemeFE/element#22362]
Element UI version
2.15.11

OS/Browsers version
win10 谷歌 

Vue version
2.7.14

Reproduction Link
https://element.eleme.cn/#/zh-CN/theme/preview

Steps to reproduce
查看主题
右侧显示颜色设置请求报错
不能显示右侧的自定义颜色工具

What is Expected?
正常显示右侧选自定义颜色

What is actually happening?
请求报错不能获取数据

**Comment by JohnnyZhang0628** [comment]
+1

**Comment by superbug** [comment]
+1

**Comment by lee259** [comment]
+1

**Comment by xinguanhua** [comment]
已知晓，会尽快修复

**Comment by xinguanhua** [comment]
https://element.eleme.cn/#/zh-CN/theme
从官网进入后，自定义主题功能可以正常使用了

**Comment by weiwentaoya** [comment]
还有人维护吗
