### ISSUE TITLE
[Bug Report] 官网在线运行出bug

### ISSUE THREAD

**Issue by hqj678** [ElemeFE/element#22367]
### Element UI version
2.15.12

### OS/Browsers version
windows10

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/hqj678/pen/yLqxZdB

### Steps to reproduce
https://element.eleme.io/#/zh-CN/component/switch在线运行switch组件时，switch组件在codepen中并没有显示出来，添加文字123显示了，但switch组件没显示

### What is Expected?
https://element.eleme.io/#/zh-CN/component/switch在线运行switch组件时，switch组件在页面显示

### What is actually happening?
https://element.eleme.io/#/zh-CN/component/switch在线运行switch组件时，switch组件在页面不显示

**Comment by admin8756** [comment]
![image](https://user-images.githubusercontent.com/21336637/216940052-6d949185-eb64-42b5-b00d-4812b6ec86eb.png)
![image](https://user-images.githubusercontent.com/21336637/216940026-e4f65dd7-99a8-4918-b29a-7f85d13d043c.png)

把codepan中element的版本的2.15.11改成2.15.12即可运行。

**Comment by xinguanhua** [comment]
问题已修复
