### ISSUE TITLE
[Bug Report] 官网最新版本日志错误

### ISSUE THREAD

**Issue by byFish** [ElemeFE/element#22377]
### Element UI version
2.15.11

### OS/Browsers version
window

### Vue version
2.7.14

### Reproduction Link
https://github.com/ElemeFE/element

### Steps to reproduce
官网最新版本日志错误，目前最新版本为2.15.12。
2.15.11存在重大bug：element-theme-chalk未成功发布。
会导致项目无法运行。

### What is Expected?
更新官网版本日志，显示2.15.12版本。

### What is actually happening?
显示2.15.11版本。

**Comment by webvs2** [comment]
计划近期发布新版

**Comment by xinguanhua** [comment]
问题已修复
