### ISSUE TITLE
[Bug Report] element 文档在codepen上的案例引用的文件地址错误

### ISSUE THREAD

**Issue by NidhoggDJoking** [ElemeFE/element#22371]
### Element UI version
2.10.1

### OS/Browsers version
任意系统版本/浏览器

### Vue version
2.7.14

### Reproduction Link
文档中任意codepen案例地址

### Steps to reproduce
点击文档案例`在线运行`
案例中引用的vue 地址：
```
//unpkg.com/vue/dist/vue.js
```
而该地址不可用，需要每次手动替换，很不方便

ps：包括一些版本的element的css/js也是:例如
```
https://unpkg.com/element-ui@2.15.11/lib/index.js
https://unpkg.com/element-ui@2.15.11/lib/theme-chalk/index.css
```

### What is Expected?
点击文档案例`在线运行` 即可正常运行

### What is actually happening?
点击文档案例`在线运行` 因为地址错误页面无法运行
抛出`Uncaught ReferenceError: Vue is not defined`
需要代码中手动替换对应链接

**Comment by NidhoggDJoking** [comment]
最新的2.15.11 使用的是
```
//unpkg.com/vue/dist/vue.js
```
而老版本（如2.10.1）依旧是使用的是
```
//unpkg.com/vue@2/dist/vue.js
```

**Comment by xinguanhua** [comment]
问题已修复

**Comment by NidhoggDJoking** [comment]
> 
![微信截图_20230213110547](https://user-images.githubusercontent.com/38490462/218361368-5236589a-33c9-4240-9d95-9e00d31e63f7.png)

### It has not been resolved

**Comment by NidhoggDJoking** [comment]
> 问题已修复

It has not been resolved!

```
https://unpkg.com/element-ui@2.15.11/lib/index.js

Cannot find "/lib/index.js" in element-ui@2.15.11

```
