### ISSUE TITLE
[Bug Report] The style of the codepen-operated examples is not normal.

### ISSUE THREAD

**Issue by ryuhangyeong** [ElemeFE/element#22380]
### Element UI version
2.15.12

### OS/Browsers version
window / chrome

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
Link access https://codepen.io/pen

### What is Expected?
normal style

### What is actually happening?
unusual style

You need to change the cdn address to solve the problem!

<img width="905" alt="image" src="https://user-images.githubusercontent.com/27342882/217996224-5971c1eb-311f-4c97-bf35-210e05c4d6d0.png">

**Comment by itsalimanuel** [comment]
@ryuhangyeong, it works fine,I believe that you made some mistakes.

check it here 👍🏻 
https://codepen.io/itsalimanuel/pen/vYaqqLz

You can check the installation 📖 
https://element.eleme.io/#/en-US/component/installation

**Comment by ryuhangyeong** [comment]
@itsalimanuel hello~

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/27342882/218096109-88a28025-24d3-4f07-9543-8a334febded6.png">

I'm running into a problem with the example codepen example in the official docs!

**Comment by itsalimanuel** [comment]
Got it, yeah they have to update many things

https://codepen.io/itsalimanuel/pen/qByzzpK

**Comment by webvs2** [comment]
I think the version of the problem will return to normal after the 12 version.
![1676173227514](https://user-images.githubusercontent.com/30883395/218291930-fc5f8bb1-04d0-4f77-8ad0-77e299ed97bc.jpg)

**Comment by xinguanhua** [comment]
this problem has been fixed by publish 2.15.13
