### ISSUE TITLE
el-scrollbar 似乎是个很有用的组件，目前只被 el-select 内部使用，能有相关文档说明使用方法吗？

### ISSUE THREAD

**Issue by kakera** [ElemeFE/element#2238]
如题

**Comment by QingWei-Li** [comment]
可以自己看源码用，不考虑加文档（虽然组件有暴露出来可以直接用）

**Comment by ohhoney1** [comment]
确实是个不错的组件，之前我还一直在用vue-scrollbar

**Comment by 1541058585** [comment]
如何使用呀？

**Comment by Bekys** [comment]
咋用呀，找了半天，没人说怎么用

**Comment by VIXNESS** [comment]
1. 引入 ``` <el-scrollbar></el-scrollbar> ```
2. 在标签内层的元素设置高度（在外层或el-scrollbar设置高度仍然可用，但是 css不能达到预期效果）
3. 在内层放置足够多的垂直元素

example:
```html
<el-scrollbar>
  <ul style="height: 100px;">
    <li v-for="item in 100" :key="item"> {{item}}</li>
  </ul>
</el-scrollbar>
```

**Comment by chesscai** [comment]
**请问如何监听和获取偏移量？**
``` html
<el-scrollbar>
...
</el-scrollbar>

渲染为：

<div class="el-scrollbar">
  <div class="el-scrollbar__wrap">
    <div class="el-scrollbar__view">...</div>
  </div>
  <div class="el-scrollbar__bar is-horizontal">...</div>
  <div class="el-scrollbar__bar is-vertical">...</div>
</div>
```
看了下源码貌似没有事件相关的事件传递机制。
如何在 el-scrollbar 监听和获取偏移量？

**Comment by iaaronxie** [comment]
好像如下设置是没用的。

```
<el-scrollbar>
  <ul style="height: 100%;">
    <li v-for="item in 100" :key="item"> {{item}}</li>
  </ul>
</el-scrollbar>
```

`height` 设置成 `100%`

**Comment by zboboan** [comment]
按须引入的话，是引入那一个组件呢？

**Comment by ohhoney1** [comment]
> 按须引入的话，是引入那一个组件呢？

```
import { Scrollbar } from 'element-ui'
Vue.use(Scrollbar)
```

**Comment by zboboan** [comment]
> 
> 
> > 按须引入的话，是引入那一个组件呢？
> 
> ```
> import { Scrollbar } from 'element-ui'
> Vue.use(Scrollbar)
> ```

谢谢

**Comment by anybz** [comment]
`<el-menu
            :default-active="activeIndex"
            class="el-menu-demo"
            mode="horizontal"
            active-text-color="#4BAF50"
            :unique-opened="true"
            menu-trigger="hover"
            @select="handleSelect">

              <el-menu-item index="1">
                 <router-link to="home">首页</router-link>
              </el-menu-item>

              <el-submenu index="2" popper-class="school-select">
                <template slot="title">我的工作台</template>
                <el-scrollbar wrap-class="list" wrap-style="color: red;" view-class="view-box" :native="false">
                  <el-menu-item index="2-1">选项1</el-menu-item>
                  <el-menu-item index="2-2">选项2</el-menu-item>
                  <el-menu-item index="2-3">选项3</el-menu-item>
                  <el-submenu index="2-4" :popper-append-to-body="true" popper-class="school-class">
                    <template slot="title">选项4</template>
                    <el-scrollbar wrap-class="list" wrap-style="color: red;" view-class="view-box" :native="false">
                      <el-menu-item index="2-4-1">选项1</el-menu-item>
                      <el-menu-item index="2-4-2">选项2</el-menu-item>
                      <el-menu-item index="2-4-3">选项3</el-menu-item>
                    </el-scrollbar>
                  </el-submenu>
                  <el-menu-item index="2-5">选项5</el-menu-item>
                  <el-menu-item index="2-6">选项6</el-menu-item>
                  <el-menu-item index="2-7">选项7</el-menu-item>
                </el-scrollbar>
              </el-submenu>

              <el-submenu index="3" popper-class="school-select">
                <template slot="title">订单管理</template>
                <el-scrollbar wrap-class="list" wrap-style="color: red;" view-class="view-box" :native="false">
                  <el-menu-item index="3-1"
                                @click="openStudy()">选项1</el-menu-item>
                  <el-menu-item index="3-2">选项2</el-menu-item>
                  <el-menu-item index="3-3">选项3</el-menu-item>
                  <el-submenu index="3-4" :popper-append-to-body="true" popper-class="school-class"
                  >
                    <template slot="title">选项4</template>
                    <el-scrollbar wrap-class="list" wrap-style="color: red;" view-class="view-box" :native="false">
                      <el-menu-item index="3-4-1">选项1</el-menu-item>
                      <el-menu-item index="3-4-2">选项2</el-menu-item>
                      <el-menu-item index="3-4-3">选项3</el-menu-item>
                    </el-scrollbar>
                  </el-submenu>
                </el-scrollbar>
              </el-submenu>
            </el-menu>`
el-menu配合el-scrollbar 使用，鼠标从三级菜单右边移出，二级菜单关不了，hover模式下，open和close事件监听不了，怎么解决？

**Comment by LadenxxxxD** [comment]
```
模块 ""element-ui"" 没有导出的成员 "Scrollbar"。你是想改用 "import Scrollbar from "element-ui"" 吗?ts(2614)
```
去看了node_modules/element-ui/types/element-ui.d.ts，确实没有export，但却可以正常使用，只是ts会报错，很奇怪
