### ISSUE TITLE
Dialog页面，当存在switch控件，并且有滚动条是，画面滑动滚动条很奇怪。

### ISSUE THREAD

**Issue by 5456435** [ElemeFE/element#224]
### Steps to reproduce
1 dialog页面很长，存在滚动条，并且有switch控件。
2 显示dialog后滑动滚动条。

### What is Expected?
除了switch里面那个小按钮自己动，画面上的元素不动。
### What is actually happening?
可以正确滑动滚动条显示元素。

**Comment by Leopoldthecoder** [comment]
我这里无法重现，请给出在线 Demo
