### ISSUE TITLE
单元测试的问题

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#2243]
我想吐槽一下这个
https://github.com/ElemeFE/element/blob/dev/test/unit/specs/table.spec.js#L1338 
所以说...单元测试的bug怎么办🌚

**Comment by QingWei-Li** [comment]
欢迎 PR

**Comment by reverland** [comment]
大佬orz，我们可以给测试写测试啊233

**Comment by Kingwl** [comment]
那给测试的测试的bug怎么办🌚
