### ISSUE TITLE
[Bug Report] el-table cell alignment change to left from center(there is a extra el-table__cell class than before) after upgrade Vue from 2.6.10 to 2.7.14

### ISSUE THREAD

**Issue by z0nka1** [ElemeFE/element#22443]
### Element UI version
0.1.4

### OS/Browsers version
Mac OS Montery

### Vue version
2.7.14

### Reproduction Link
no

### Steps to reproduce
Upgrade Vue from from 2.6.10 to 2.7.14.
BTW, my vue-style-loader version is 4.1.3.

### What is Expected?
el-table cell aligns center

### What is actually happening?
el-table cell aligns left

### pictures before
![20230313112034](https://user-images.githubusercontent.com/24217059/224602914-e5f564fb-42d3-4b6c-9a9f-2aa4444fcb49.jpg)

![20230313112106](https://user-images.githubusercontent.com/24217059/224602926-b677659f-e9d7-4241-b7cf-958415910489.jpg)

![20230313112131](https://user-images.githubusercontent.com/24217059/224602934-38bb7906-c983-43ce-bfff-75cc83af95b9.jpg)

### pictures after
![20230313114120](https://user-images.githubusercontent.com/24217059/224603108-c7a76c3c-9909-4676-8304-b19b1f6a8919.jpg)

![20230313112236](https://user-images.githubusercontent.com/24217059/224602974-9fcb5d83-5ad1-4a7a-9a0c-d5db97780ee7.jpg)

![20230313112250](https://user-images.githubusercontent.com/24217059/224602977-81c6fd6d-430e-4221-9ec6-a1df5881ab53.jpg)

**Comment by webvs2** [comment]
![image](https://user-images.githubusercontent.com/30883395/225484081-406f8583-1d78-4719-af50-82cffb331da0.png)
![image](https://user-images.githubusercontent.com/30883395/225484150-8f670ee1-dc97-4f0d-9fb5-fab38e219168.png)
未复现，建议检查本地代码，关闭issues

**Comment by prof-H3645** [comment]
I encountered the same issue, and it's quite perplexing. Using the same code and the same version of Element-UI, the only difference is that one project uses a pre-installed `node_modules` from someone else, while the other project has dependencies installed by me based on the `package.json`. Why does one version of el-table have the class "el-table__cell" while the other does not?
