### ISSUE TITLE
[Bug Report] table表格，双击空白单元格，下一行第一列单元格里面的文字会被选中

### ISSUE THREAD

**Issue by yin1163385339** [ElemeFE/element#22441]
### Element UI version
2.15.13

### OS/Browsers version
windows/谷歌

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/yin1163385339/pen/rNZpaJo

### Steps to reproduce
双击地址列空白单元格
下一行第一列数据会被选中

### What is Expected?
期待双击地址列空白单元格,下一行第一列的文字不被选中

### What is actually happening?
实际双击地址列空白单元格,下一行第一列的文字被选中

**Comment by webvs2** [comment]
这并不是一个问题，关闭issues

**Comment by yin1163385339** [comment]
这个是属于正常的？
