### ISSUE TITLE
分页组件需要disabled

### ISSUE THREAD

**Issue by think2011** [ElemeFE/element#2244]
以下场景需要：
1. 当用户点击 第一页，ajax开始请求，数据还没有回来
2. 接着用户点击 第二页，ajax开始请求，数据很快就回来并渲染了页面
3. 第一页请求的ajax回来并渲染了页面，但是分页组件显示的当前是第二页

当前解决方案：
把整个页面用 loading 遮住，但是用户体验不好，有时候数据返回的很快，不再优化的话，看起来一闪一闪的
![22](https://cloud.githubusercontent.com/assets/3961388/21705916/02c4716c-d3fe-11e6-8053-e5d47b5526ac.gif)

希望能够有个 disabled，请求完毕后再释放 disabled 

![untitled](https://cloud.githubusercontent.com/assets/3961388/21705901/e5180aa2-d3fd-11e6-99bb-646c7af7fab7.gif)

**Comment by reverland** [comment]
这个问题我采取的方法是把之前的请求给断开，其实就是允许用户不断点击，但后来的请求一定把之前的请求断开。

毕竟，不想因为一个请求跪了分页就不能点了吧。所以不建议在分页组件加disable，更建议让新的用户操作取消冲突的已有操作。

关于实现：jquery里有abort，axios就是很奇怪的promise cancel。。

**Comment by think2011** [comment]
恩，明白了，cancel方案应该是最优的了。因为不想动以前封装的代码，所以就没考虑 @reverland

**Comment by baiyaaaaa** [comment]
我觉得分页组件不需要提供 disabled 啊，有点奇怪
