### ISSUE TITLE
[Bug Report] The color-picker component does not work when changing the color-format parameter

### ISSUE THREAD

**Issue by Essentric** [ElemeFE/element#22484]
### Element UI version
2.15.13

### OS/Browsers version
Windows/Chrome 109

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/essentric/pen/Jjmdavx

### Steps to reproduce
1. Select a different format value
2. Open the color-picker panel

### What is Expected?
When the format value is changed, the Color-Picker panel displays the corresponding color format

### What is actually happening?
When the format value is changed, the color-picker panel always defaults to hex

**Comment by webvs2** [comment]
#22489
