### ISSUE TITLE
Select 组件在v-model有值的时候，显示出来的是ID，不是文字的值。

### ISSUE THREAD

**Issue by xiukun520** [ElemeFE/element#2248]
### Vue version

 <el-select v-model="policeform.department.id" filterable="" clearable remote placeholder="单位较多，输入最少2个字进行查询。" :remote-method="queryDepartment" :loading="loading">
        <el-option v-for="item in depts" :key="item.id" :label="item.name" :value="item.id">
        </el-option>
      </el-select>

showdiag: function(url,entity) {
        this.url = url;
        this.tianjia = true;
        this.policeform={
          'policeNumber': '',
          'policePhone': '',
          'policeIdCard':'',
          'policeOfficePhone':'',
          'name': '',
          'job': '',
          'level': '',
          'department': {
            'id': '',
            'name':''
          }
        };
        if(typeof entity == "object"){
          Object.assign(this.policeform,entity);
          alert(JSON.stringify(this.policeform));
        }  
      }
![image](https://cloud.githubusercontent.com/assets/23646747/21708407/319df0b6-d413-11e6-8331-24cfd389628e.png)
![image](https://cloud.githubusercontent.com/assets/23646747/21708419/4efdb970-d413-11e6-861a-3afbbfffb9c8.png)
当我进行编辑数据的时候，传到弹出框里面的数据显示成了id

**Comment by Leopoldthecoder** [comment]
Element 版本是？

**Comment by xiukun520** [comment]
1.0.7

 

*************************************

姓名：于秀坤

职位： 研发经理

Tel：13256832958
mail: xiukun520@foxmail.com <mailto:xiukun520@foxmail.com> 
青岛宜生活网络科技有限公司

Eshenghuo Network  <https://www.baidu.com/s?wd=Technology&tn=44039180_cpr&fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1dBuj0dm1uhnvw-uA7-m160IAYqnWm3PW64rj0d0AP8IA3qPjfsn1bkrjKxmLKz0ZNzUjdCIZwsrBtEXh9GuA7EQhF9pywdQhPEUiqkIyN1IA-EUBtzP161rH6YnW6> Technology Co.,  <https://www.baidu.com/s?wd=Ltd&tn=44039180_cpr&fenlei=mv6quAkxTZn0IZRqIHckPjm4nH00T1dBuj0dm1uhnvw-uA7-m160IAYqnWm3PW64rj0d0AP8IA3qPjfsn1bkrjKxmLKz0ZNzUjdCIZwsrBtEXh9GuA7EQhF9pywdQhPEUiqkIyN1IA-EUBtzP161rH6YnW6> Ltd.

*************************************

 

发件人: 杨奕 [mailto:notifications@github.com] 
发送时间: 2017年1月6日 13:28
收件人: ElemeFE/element <element@noreply.github.com>
抄送: xiukun520 <xiukun520@foxmail.com>; Author <author@noreply.github.com>
主题: Re: [ElemeFE/element] Select 组件在v-model有值的时候，显示出来的是ID，不是文字的值。 (#2248)

 

Element 版本是？

**Comment by Leopoldthecoder** [comment]
试试 1.0.9 或者 1.1.2，还不行的话请提供在线 demo。

**Comment by lincenying** [comment]
数值型和字符型的原因...

如果v-model的值是数值型的, :value 也必须是数值型的, 字符型同理

我一向都用这种很蛋疼的写法
```
<el-option v-for="(item, index) in express" :label="item" :value="''+index"></el-option>
```

**Comment by Leopoldthecoder** [comment]
@xiukun520 参考下楼上的说法。先关掉了，还有问题的话提供在线 demo。

**Comment by inhere** [comment]
我在 `1.1.2` 也出现这个问题，只有暂时按楼上的

```
... :value="1 * index"></el-option>
```

来统一成 与 `v-model` 一样的数据类型
