### ISSUE TITLE
[Bug Report] transfer穿梭框 底部的slot遮盖住了列表最后一行内容

### ISSUE THREAD

**Issue by zzx769394358** [ElemeFE/element#22481]
### Element UI version
2.15.7

### OS/Browsers version
谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/bofeng/pen/poaEmJY

### Steps to reproduce
<template>

  <div style="text-align: center">
    <el-transfer
      style="text-align: left; display: inline-block"
      v-model="chooseColumn"
      :props="{
        key: 'key',
        label: 'label'
      }"
      :titles="['左列', '右列']"
      :format="{
        noChecked: '${total}',
        hasChecked: '${checked}/${total}'
      }"
      target-order="push"
      :data="allFieldList"
      @right-check-change="choose"
    >
      <el-button class="transfer-footer" slot="right-footer" size="small" @click="handleChange('up')">上移</el-button>
      <el-button class="transfer-footer" slot="right-footer" size="small" @click="handleChange('down')">下移</el-button>
      <el-button class="transfer-footer" slot="right-footer" size="small" @click="handleChange('top')">置顶</el-button>
    </el-transfer>
    <br><br>
  </div>
</template>

 右列 底下的最后一行数据 被button们遮盖了

### What is Expected?
正常显示 右列所有数据

### What is actually happening?
右列 底下的最后一行数据 被button们遮盖了

**Comment by NidhoggDJoking** [comment]
> ### Element UI version
> 2.15.7
> 
> ### OS/Browsers version
> 谷歌浏览器
> 
> ### Vue version
> 2.6.10
> 
> ### Reproduction Link
> https://codepen.io/bofeng/pen/poaEmJY
> 
> ### Steps to reproduce
> 上移 下移 置顶
> 
> 右列 底下的最后一行数据 被button们遮盖了
> 
> ### What is Expected?
> 正常显示 右列所有数据
> 
> ### What is actually happening?
> 右列 底下的最后一行数据 被button们遮盖了

提供的链接是否正确？> https://codepen.io/bofeng/pen/poaEmJY
