### ISSUE TITLE
Message窗口样式问题

### ISSUE THREAD

**Issue by SnuggleE** [ElemeFE/element#2249]
element-ui": "^1.0.3
您好！我再使用element时，信息提示窗口样式莫名的变成了两行以下是问题截图
[问题截图](http://thumbnail0.baidupcs.com/thumbnail/217c24e8189afde129f357414c9ff823?fid=1779431344-250528-339272615214699&time=1483678800&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-kRXyyqy1JvDj3Cn1SvNO5qAMnEU%3d&expires=8h&chkbd=0&chkv=0&dp-logid=129259589336866070&dp-callid=0&size=c10000_u10000&quality=90)

请提供帮助  谢谢！

**Comment by Leopoldthecoder** [comment]
请提供在线 demo。

**Comment by SnuggleE** [comment]
抱歉！刚看到消息。样式出错的原因已经找，webpack打包的时候没有把一个类样式打包进去，
.el-message__img{
        width:40px;
        height:40px;
        position:absolute;
        left:0;
        top:0;
      }
暂时的解决方法是将该样式写在index.html,问题算是得到解决。
不过具体产生的原因，还没有找到，谢谢！
