### ISSUE TITLE
pagination如何取當前所處的頁數？

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#2251]
![image](https://cloud.githubusercontent.com/assets/1060733/21711076/af9fea1e-d427-11e6-9584-f59c2875cfac.png)

在使用pagination的時候，無論我怎麼點擊分頁按鈕，那個currentPage的值都是1，一直不變，氣死我了
這是怎麼回事啊

**Comment by reverland** [comment]
currentpage是prop，所以，手動更新吧。internalCurrentPage都18了

**Comment by QingWei-Li** [comment]
Vue 2 已经没有双向绑定了，所有数据流都是单向的。当前页数是通过事件获取，具体看文档。

**Comment by zzzgit** [comment]
@QingWei-Li 
@reverland 
雙向綁定，把prop的名字寫成value，就可以吧？
我看有些組件庫，就是這樣做的

**Comment by zzzgit** [comment]
![image](https://cloud.githubusercontent.com/assets/1060733/21711485/3efe5982-d42a-11e6-9223-19fde0576d32.png)

為什麼不直接使用currentPage，而要用這個internalCurrentPage來維護當前頁，這個值？
就是為了避免控制台出現warning嗎？
由於有這個watch存在，只要組件外部的變量currentPage發生變化，組件內部的internalCurrentPage會跟著變化，這跟直接使用currentPage來跟蹤和控制頁面跳轉邏輯有什麼區別，何必要添加這個內部變量？

**Comment by reverland** [comment]
感覺，頁面跳轉（currentPage變化）會改變組件狀態（internal），但是反過來未必。

**Comment by reverland** [comment]
實際上一般使用的時候我會把路由加上，讓路由決定currentPage，internal變化觸發路由變化。如果是雙向綁定，好像對我的用法確實沒有意義，就是感覺不是所有人都需要雙向綁定。

拿啥，單項數據流大法好
