### ISSUE TITLE
[Bug Report] el-progress 环形图问题

### ISSUE THREAD

**Issue by biquanzhu** [ElemeFE/element#22524]
### Element UI version
2.15.13

### OS/Browsers version
Chrome 113.0.5672.93（正式版本）

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/dlmd/pen/NWOMMMa

### Steps to reproduce
给 el-progress设置上这些属性： type="circle" :percentage="50" :width="212" stroke-linecap="square" :stroke-width="40"，就会导致环形图的两头是矩形的并且超出了环形图本身的范围

### What is Expected?
按照环形图本身的原型填充，不超出环形图范围

### What is actually happening?
没有达到要求

**Comment by fxzer** [comment]
你可以改用 `stroke-linecap="round"`,可以避免这个问题

**Comment by biquanzhu** [comment]
> 你可以改用 `stroke-linecap="round"`,可以避免这个问题

但是要求的就是 stroke-linecap="square"这种形状
