### ISSUE TITLE
table 表头单元格数量从多到少， 表头不渲染

### ISSUE THREAD

**Issue by ThinkRealize** [ElemeFE/element#2253]
ElementUI version

1.1.2

OS/Browers version

macOS/Chrome 55

Vue version

2.1.8
如果表头单元格数量从2个变为1个可以渲染
DEMO
http://jsfiddle.net/yellowstart/ve7c42bb/9/

**Comment by QingWei-Li** [comment]
不支持动态更新表头

**Comment by ThinkRealize** [comment]
@QingWei-Li  请问以后会不会支持动态更新表头

**Comment by fliu2476** [comment]
@ThinkRealize 我也遇到这个问题了，用一个不怎么优雅的方法解决了。
分享一下：每次更新数据前先用v-if把el-table组件移除，然后数据处理好以后v-if=true。
希望有更好方法的朋友不吝赐教！
