### ISSUE TITLE
[Bug Report] el-autocomplete 添加clearable属性时，使用清除功能以后，input未失去焦点，从新输入查询文本接口请求的返回结果不展示

### ISSUE THREAD

**Issue by maorunjie-2019** [ElemeFE/element#22542]
### Element UI version
2.15.13

### OS/Browsers version
mac/chrome

### Vue version
2.7.14

### Reproduction Link
https://elementui.github.io/issue-generator/#/zh-CN

### Steps to reproduce
xxx

### What is Expected?
展示查询结果

### What is actually happening?
未展示查询结果

**Comment by maorunjie-2019** [comment]
。。

**Comment by gongzizhao** [comment]
hello？ 2.15.14版本依旧有这个问题。这个issue被关闭了 是怎么解决的呀
