### ISSUE TITLE
table 滚动条不能滚动

### ISSUE THREAD

**Issue by gukong** [ElemeFE/element#2255]
http://element.eleme.io/#/zh-CN/component/table
官方Demo，table 横向滚动条不能滚动
不能用鼠标拖动滚动条，用鼠标点击滚动条没有反应

环境：
macOS Sierra（10.12.1 ）
Safari（ 10.0.1）

**Comment by QingWei-Li** [comment]
可以给个 demo 或动图么，我这是正常的
![kapture 2017-01-06 at 17 11 11](https://cloud.githubusercontent.com/assets/7565692/21713091/27f06074-d433-11e6-8d7d-36ca23a5ada9.gif)

**Comment by gukong** [comment]
![image](http://7xtaiq.com1.z0.glb.clouddn.com/table-demo.gif)

1. 我注意到最新的文档已经去掉了virtual-scrollbar（以前我就是用这个来规避问题的），你给的Demo gif 出现了 virtual scrollbar，困惑
2. 我说的是不能用鼠标拖动滚动条（通过触摸板滑动内容是没问题的）
😁

**Comment by QingWei-Li** [comment]
一直没复现这问题，也没其他用户反馈。最近版本还有么 @gukong

**Comment by Leopoldthecoder** [comment]
先关掉了，如果有问题可以再打开。

**Comment by senro** [comment]
mac 下的safari环境，table组件确实是有很多问题的，bug1：表格与表头会错位，bug2：横向滚动条不能滚动。bug1目前分析是由于col里的width属性在mac 下的safari不支持，改成style=“width:xx"即可，你们的编译工具（cooking）老是报错，cooking build不了代码无法测试，希望重视一下这个bug，修改一下table组件，毕竟这个组件还比较常用！谢谢！

**Comment by Kingwl** [comment]
@senro 
bug1：表格与表头会错位 这个问题 @reverland 大佬已经修过了

**Comment by senro** [comment]
刚测了一下，在mac 下的safari，gutter还是有宽度，会导致错位的，版本是1.1.6，我看到gutter新增了一个width：0的样式，但是没有起作用，不知道你们有没有测试一下？
