### ISSUE TITLE
[Bug Report] table，合并 树形数据，样式问题

### ISSUE THREAD

**Issue by wweggplant** [ElemeFE/element#22578]
### Element UI version
2.15.13

### OS/Browsers version
Mac、Chrome 

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/wweggplant/pen/eYQgWzG

### Steps to reproduce
打开链接

### What is Expected?
表单行正常展示

### What is actually happening?
表格行过高

**Comment by care98** [comment]
您好我遇到类似问题，我是在合并列后发现行高变高了。请问您解决了吗
