### ISSUE TITLE
[Feature Request] 项目中有一个页面的表单对象的key是xxx.xxx.xxx形式的，这种情况下form表单标签的prop属性该如何绑定？

### ISSUE THREAD

**Issue by zhao-yangchang** [ElemeFE/element#22573]
### Existing Component
是

### Component Name
el-form-item

### Description
页面的表单对象key是xxx.xxx.xxx，这种形式下form表单标签的prop属性不知道该如何写，试过prop="xxx.xxx.xxx"\prop="'xxx.xxx.xxx'"\prop="['xxx.xxx.xxx']"都会报错‘please transfer a valid prop path to form item!’，是不是key的命名不能带.

表单对象：
```json
{"card.post.address.state":"xxx","card.post.address.country":"xxx","card.post.address.city":"xxx","card.post.address.line1":"xxx","card.post.address.line2":"xxx","card.post.address.zip_code":"xxxx"}
```

**Comment by zhao-yangchang** [comment]
实在没有找到解决方案，前端的.用_代替了。。。

**Comment by kwen94** [comment]
我这边的的key是xxx:xxx，跟你一样的报错，看框架会把prop中的:转为. 
所以:和.应该都有问题
