### ISSUE TITLE
当InputNumber 输入大于最大值或小于最小值时问题

### ISSUE THREAD

**Issue by brucesong08** [ElemeFE/element#2261]
当InputNumber 输入大于最大值或小于最小值时，应该取最小值或最小值，而不是按照字符串那样截取前几个字符。
举例：<el-input-number v-model="num1" @change="handleChange" :min="1" :max="10"></el-input-number>
 输入：32   错误：3   正确：10
 输入：-2   错误：2   正确：1

**Comment by baiyaaaaa** [comment]
#2355
