### ISSUE TITLE
[Bug Report]当表格组件el-table里使用弹出层组件el-popover并在弹出层el-popover组件显示另一个表格的时候会出现行hover效果失效

### ISSUE THREAD

**Issue by loveyyao** [ElemeFE/element#22624]
### Element UI version
2.15.13
### OS/Browsers version
115.0.5790.110
### Vue version
2.7.14
### Reproduction Link
[Reproduction Link](https://codepen.io/loveyyao/pen/QWJJjwP)
### Steps to reproduce
表格组件`el-table`里使用弹出层组件`el-popover`并在弹出层`el-popover`组件显示另一个表格的时候会出现行`hover`效果失效，若存在固定列的情况还会出现`hover`效果错位
### What is Expected?
当表格组件使用弹出层组件去显示另一个表格时，外层的表格行`hover`效果正常
### What is actually happening?
在查看源码时发现，`hover`时，通过 `this.$el.querySelectorAll('.el-table__row')`去获取表格下的行，`el-popover`组件初始化时，弹窗层的内容还存在表格列下，导致`hover`时通过下标去显示`hover`效果错误

**Comment by webvs2** [comment]
I will check the problem

**Comment by webvs2** [comment]
No anomalies found. Can you describe them in detail？🦝

**Comment by wangdaodao** [comment]
> No anomalies found. Can you describe them in detail？🦝

看了下，从第二行开始，表格行划过高亮不正常了。

**Comment by loveyyao** [comment]
> No anomalies found. Can you describe them in detail？🦝
![image](https://github.com/ElemeFE/element/assets/45845997/e7b4321e-0f72-4bd8-85e9-41961e81e0ff)
![image](https://github.com/ElemeFE/element/assets/45845997/67ffbc42-4ebc-4150-9501-a34560219938)
 我在 **el-table**里的某一列，使用了`el-popover`来显示一个表格，行的hover效果有时候失效，有时候错误，需要将`el-popover`里的表格都显示一遍才正常，我猜应该是
![image](https://github.com/ElemeFE/element/assets/45845997/f405f4d7-d7bf-4922-8a99-2555444dc4db)
这段代码存在问题。
通过控制台调试发现`el-popover`初始化的时候内容还是渲染到表格列里面了
![image](https://github.com/ElemeFE/element/assets/45845997/231156df-b3ab-452c-b417-f9db9ecf15fc)

**Comment by loveyyao** [comment]
> 



> > No anomalies found. Can you describe them in detail？🦝
> 
> 看了下，从第二行开始，表格行划过高亮不正常了。
> 
> ![图片](https://user-images.githubusercontent.com/2317442/257397438-b7dec5db-d725-4c0c-8f20-7af4338931b2.png)



> > No anomalies found. Can you describe them in detail？🦝
> 
> 看了下，从第二行开始，表格行划过高亮不正常了。
> 
> ![图片](https://user-images.githubusercontent.com/2317442/257397438-b7dec5db-d725-4c0c-8f20-7af4338931b2.png)

我通过二次封装`el-popover`来避免了这个问题
![image](https://github.com/ElemeFE/element/assets/45845997/ef9521d5-799d-42a5-8939-22f5f3bd2d2d)
添加`v-if`来控制

**Comment by webvs2** [comment]
I am very sorry for such a situation, and I commend you for self-repair. The official can repair the code next time, but the time is difficult to guarantee. For the old element, the update frequency is already very low.

**Comment by webvs2** [comment]
> > 
> 
> > > No anomalies found. Can you describe them in detail？🦝
> > 
> > 
> > 看了下，从第二行开始，表格行划过高亮不正常了。
> > ![图片](https://user-images.githubusercontent.com/2317442/257397438-b7dec5db-d725-4c0c-8f20-7af4338931b2.png)
> 
> 我通过二次封装`el-popover`来避免了这个问题 ![image](https://user-images.githubusercontent.com/45845997/259917477-ef9521d5-799d-42a5-8939-22f5f3bd2d2d.png) 添加`v-if`来控制

[good job](javascript:;)
