### ISSUE TITLE
notification跟message是不是功用有點重複

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#2262]
notification跟message是不是功用有點重複啊？
為什麼你們不搞個bbs，應該花不了多少錢吧？

![image](https://cloud.githubusercontent.com/assets/1060733/21712580/8f2a087e-d430-11e6-938a-972f22769c11.png)

**Comment by QingWei-Li** [comment]
大家都在 Gitter 里

不重复，显示的效果都不一样。以后提问题请到 Gitter 里吧，Issue 还是应该用来提 Bug 和 Feature
