### ISSUE TITLE
[Bug Report] el-table 组件使用 selection 且修改其宽度时，会出现意料之外的省略号。When the el-table component uses selection and changes its width, unexpected ellipses occur.

### ISSUE THREAD

**Issue by 0o23** [ElemeFE/element#22627]
### Element UI version
2.15.6

### OS/Browsers version
Chrome 版本(version) 115.0.5790.114 正式版本(formal version) (arm64)

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/0o23/pen/Jjexovv

### Steps to reproduce
打开本人提供的 codepen 链接后，即可看到表格勾选列的每个勾选框右侧出现了不完整的省略号。
When you open the codepen link I provided, you see an incomplete ellipsis to the right of each checkbox in the checkbox column of the table.

### What is Expected?
不论我对勾选列设置的 width 有多小，勾选列都不会出现省略号。
No matter how small the width of the checked column is, the checked column will not have an ellipsis.

### What is actually happening?
当勾选列的 width 为 30 左右时，会出现意料之外的省略号。 
When the width of the checked column is about 30, unexpected ellipses will appear.

**Comment by 0o23** [comment]
我有办法解决它，但感觉有点必要给官方做个建议

**Comment by Nobodycareszzk** [comment]
当勾选列的 width 为 26 至 41 之间时，好像会出现意料之外的省略号，目前我的做法是将该元素的text-overflow 设置为 clip得以解决。
