### ISSUE TITLE
[Feature Request] A SMALL CODE ERROR

### ISSUE THREAD

**Issue by HawtinZeng** [ElemeFE/element#22620]
### Existing Component
Yes

### Component Name
Radio-group

### Description
I have found Browser automatically implemented arrow keyboard selection for el-radio in a radio group, therefore, we may needn't handleKeydown method in radio-group component,
![image](https://github.com/ElemeFE/element/assets/73981739/d0db6fc6-d945-4731-bec4-90352cf8de5c)

**Comment by webvs2** [comment]
**Browsers are gradually enforcing key events, or properties inherent in html itself. For the radio component, where keyboard events are native to html, try disabling native events to get the desired effect.**
**Is there any problem we can communicate or close the problem**

**Comment by HawtinZeng** [comment]
The last question, where keyboard event is native to radio component, why we disactive native keyboard event instead of disactiving custom event handler?

**Comment by HawtinZeng** [comment]
> The last question, where keyboard event is native to radio component, why we disactive native keyboard event instead of disactiving custom event handler?

I have understood, we must offer consistent experience in compatible and incompatible browsers.

**Comment by HawtinZeng** [comment]
> > The last question, where keyboard event is native to radio component, why we disactive native keyboard event instead of disactiving custom event handler?
> 
> I have understood, we must offer consistent experience in compatible and incompatible browsers.

No, but the native keyboard event behavior is the same as the custom keyboard...
