### ISSUE TITLE
[Feature Request] el-dialog的customClass是否可以支持对象呢？

### ISSUE THREAD

**Issue by loprx** [ElemeFE/element#22638]
### Existing Component
是

### Component Name
el-dialog

### Description
el-dialog的customClass是string类型，是否可以换成对象呢？因为有类似这样的需求
```vue
:custom-class="{'a': true, 'b': exp}"
```

**Comment by loveyyao** [comment]
可以将 `el-dialog`二次封装去实现

**Comment by loprx** [comment]
也可以~
谢谢~
