### ISSUE TITLE
树形控件.带checkbox建议以及bug

### ISSUE THREAD

**Issue by zWingz** [ElemeFE/element#2264]
```
<el-tree
            :data="data"
            :props="props"
            :load="loadNode"
            lazy
            show-checkbox>
        </el-tree>
```

建议:
    第一次点击父节点的checkbox的时候选中并展开子节点没问题,但如果再次点击父节点的checkbox.这时候会完全的把所有子节点都执行一遍load操作,如果子节点带很多层级的话,会导致load很久.建议是展开一层只load当前层级的子节点,而不是继续load子节点的子节点

bug:
    同样场景,第一次点击父节点checkbox选中并展开子节点没问题,后面如果再次点击父节点的checkbox时候,子节点会先收起来,然后在展开,再此点击依然如此.

**Comment by scaleryvan** [comment]
同样的bug，选中父节点checkbox会先收起子节点，然后再展开。
如果设置‘expand-on-click-node’为‘false’,只点击箭头图标展开收起的话，没有此问题，可能是点击checkbox造成了事件冒泡吧。官方文档示例中‘可选择’示例就可复现此bug

**Comment by baiyaaaaa** [comment]
现在点击 checkbox 不会再触发节点的展开收起。
