### ISSUE TITLE
select组件远程搜索，当选中值后，会再发起一次以该值为查询字段的搜索请求，显然这个请求可以节省

### ISSUE THREAD

**Issue by toutouli** [ElemeFE/element#2265]
版本：1.1.2

select组件远程搜索，最终选择选项后，会再发起一次以该选项值为查询字段的搜索，我认为这最后一次的搜索是不必要的，可以节省。

另外能否增加延时参数设置项，可以设置当用户多久没有继续输入才发起查询请求(以判断用户已经完成输入，虽然可以在remote-method里通过节流函数实现，但是还是觉得有点麻烦呢)

**Comment by huangyingjie** [comment]
+1。@toutouli 发给PR吧，更快些

**Comment by jialuchun** [comment]
+1

**Comment by Leopoldthecoder** [comment]
Fixed in #6151
