### ISSUE TITLE
Datepicker is wider since last update

### ISSUE THREAD

**Issue by rvanzon** [ElemeFE/element#2266]
Hi,

I recently updated to 1.1.2 and the datepicker doesn't work correctly anymore using de 24-column grid layout:

![element-ui-datepicker-issue](https://cloud.githubusercontent.com/assets/815029/21714552/edd9744e-d3ff-11e6-8c74-b21c09660101.png)

The problem is also showing up on je JSFidle example on the site (only in Fiddle, not on the site itself as it probably uses an older version of Element UI). Check: http://element.eleme.io/#/en-US/component/form (and click Try it). The dash is very close to the Datepicker:

![element-ui-datepicker-issue2](https://cloud.githubusercontent.com/assets/815029/21714610/48181db6-d400-11e6-9a7c-a1cc00e96d69.png)

**Comment by QingWei-Li** [comment]
You need to write the CSS.

https://github.com/ElemeFE/element/blame/dev/examples/docs/en-US/form.md#L180-L182
```css
.line {
  text-align: center;
}
```
