### ISSUE TITLE
Popover 弹出框在v-for循环中生成多个弹出框时会不正常

### ISSUE THREAD

**Issue by rulelee** [ElemeFE/element#2268]
如题

**Comment by reverland** [comment]
所以你是用的指令呢还是slot呢

**Comment by SeanLeeCai** [comment]
我使用的是slot，但我使用v-for来绑定弹出框也遇到了问题
一个弹出框应该是只能绑定到一个上面吧，如下demo，按钮一和二绑定了同一个弹出框，只有按钮二有
http://jsfiddle.net/0rqukbg3/2/

所以我想要用v-for生成弹出框并绑到相应按钮上去，但v-popover:这个指令应该要怎么和弹出框的ref关联起来呢？
http://jsfiddle.net/0rqukbg3/5/

**Comment by rongjuan** [comment]
<div class="msg-add" v-for="(item, index) in addresses">
        
              <el-popover ref="popover5" placement="top" width="220" v-model="visible2">
                弹出内容！！！
              </el-popover>
        <el-button type="text" v-popover:popover5 icon="edit" class="edit-btn"></el-button>
      </div>

**Comment by GDxin** [comment]
我循环出来的按钮气泡，前两个会弹出，后边的都没反应，是为啥？
<div class="col-sm-12" style="margin-top:10px"  v-for="(item,index) in popoverData" :key="index">
                                    <div class="form-group">
                                       <span>设备-ushvuhcjcids</span><button @click="handler(index)" type="button" class="btn btn-primary btn-xs popover-show"  data-original-title="选择回放时间"
                                       data-container="body" data-toggle="popover" data-html="true" data-placement="right" 
                                       >回放</button>
                                       <span>{{item.channelStatus=='offline'?'离线':'在线'}}</span>
                                    </div>
                                </div>
