### ISSUE TITLE
[Bug Report] table使用vue-clamp，设置操作列固定，点击展开文本后操作列错位

### ISSUE THREAD

**Issue by kaxiluo** [ElemeFE/element#22687]
### Element UI version
2.15.14

### OS/Browsers version
Windows 10 / Microsoft Edge 版本 117.0.2045.31 (正式版本) (64 位)

### Vue version
2.7.14

### Reproduction Link
https://codepen.io/kaxiluo/pen/zYypzdR

### Steps to reproduce
1.打开重新连接

2.点击内容列的展开按钮

### What is Expected?
操作列在文本展开后正常显示

### What is actually happening?
操作列错位

PS:
Element UI 2.15.7 可以正常展示

**Comment by wangdaodao** [comment]
2.15.7正常显示是因为修改了这里：https://github.com/ElemeFE/element/pull/21330

但是导致了其他问题，所以代码回滚了

**Comment by kaxiluo** [comment]
> 2.15.7正常显示是因为修改了这里：#21330
> 
> 但是导致了其他问题，所以代码回滚了

感谢大佬解答

**Comment by kaxiluo** [comment]
一位王姓大哥给我的解决方法：
https://codepen.io/kaxiluo/pen/eYbMdKK

数据驱动视图更新
