### ISSUE TITLE
table 表格 你改动你讲啊，为什么不讲啊 

### ISSUE THREAD

**Issue by InTwoDisease** [ElemeFE/element#2270]
[{
            date: '2016-05-02',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1518 弄'
          }, {
            date: '2016-05-04',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1517 弄'
          }, {
            date: '2016-05-01',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1519 弄'
          }, {
            date: '2016-05-03',
            name: '王小虎',
            address: '上海市普陀区金沙江路 1516 弄'
          }]
这种结构可以
http://jsfiddle.net/0y8vn8jh/

[1,2,3,4,5]
这种不可以。
之前是可以的。你改动为什么不讲啊。线上出bug了你造嘛。
http://jsfiddle.net/8kdkz01z/

**Comment by reverland** [comment]
😭 升级谨慎啊，一般都要锁死版本的。

element-ui虽然1.x.x了，但仍然感觉是testing状态，怀着最大的恶意揣测官方肯定没有用到产品中去

**Comment by jikkai** [comment]
@InTwoDisease 
本着严谨的态度考据了下发现是1.0.0-rc.7 => 1.0.0-rc.8时候被移除掉的功能。
然后特地看了下[rc7的table组件文档](https://github.com/ElemeFE/element/blob/v1.0.0-rc.7/examples/docs/zh-cn/table.md)，似乎没有在文档中声明过`[1,2,3,4,5]`这种用法。

我只能说，使用API也要按照基本法🤣

最后，虽然不是element的维护人员，但也请不要滥用issues

**Comment by yinshipeng** [comment]
上生产要锁死版本的

**Comment by Leopoldthecoder** [comment]
@InTwoDisease Table 从来都没说过可以这么用。
