### ISSUE TITLE
走马灯的无限滚动问题

### ISSUE THREAD

**Issue by lsbrucelincoln** [ElemeFE/element#2271]
先谢谢你们的辛苦付出：）
现在的走马灯从最后一张到第一张的方式是快速滚回到第一张，这样不太符合通常对无限滚动的要求，就是平滑的按照原来方向滚到第一页。本来用的别的插件的，发现element有走马灯之后，感觉很开心，因为可以省下一个依赖包的空间了，就差这一点点差别了。
辛苦了。

**Comment by jikkai** [comment]
#2189

**Comment by QingWei-Li** [comment]
Thx @jikkai

**Comment by Leopoldthecoder** [comment]
Fixed in #2622
