### ISSUE TITLE
element-loading-text能支持动态修改吗？

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#2272]
指令方式v-loading.lock="view_loading" :element-loading-text="view_loading_text"
能支持动态修改吗？

**Comment by Leopoldthecoder** [comment]
不支持。

**Comment by AaronChen2012** [comment]
还是建议能够支持这个属性的修改，内嵌v-loading还是很有用的！

**Comment by Jerenyaoyelu** [comment]
element-loading-**系列是否都不支持动态修改？
