### ISSUE TITLE
[Bug Report] 在el-table 的 header 插槽中使用 el-input 输入延迟

### ISSUE THREAD

**Issue by xing403** [ElemeFE/element#22748]
### Element UI version
2.15.13

### OS/Browsers version
win 10 / google chrome 119.0.6045.160

### Vue version
2.6.11

### Reproduction Link
https://jsfiddle.net/xing403/5tamqpub/158/

### Steps to reproduce
1. 在表格中使用 `header` 插槽 中 有个`el-input` 用于过滤列表信息，每一列会根据选择 tag不同 展示或者隐藏 这一列
2. 当输入时初始化的第一个显示的所有el-input 是正常输入
3. 但当切换 tag 的值时，再次渲染的el-input 输入会出现延迟 例如 输入`123456`(PS：输入比较快，很慢时正常但要非常慢[输入等待 2s 左右]) 实际显示的为 错误显示信息`1`,`12`,`13`,`135`都有可能

### What is Expected?
在tag 切换之后，重新渲染的el-input 再输入不需要有延迟等待，输入不要有延迟（ :( 这是什么原因导致的，能否告诉我这是为什么 ）

### What is actually happening?
当切换 tag 的值时，再次渲染的el-input 输入会出现延迟 例如 输入`123456`(PS：输入比较快，很慢时正常但要非常慢[输入等待 2s 左右]) 实际显示的为 错误信息`1`,`13`,`135`都有可能

**Comment by wangdaodao** [comment]
试试原生input+修饰符。

**Comment by xing403** [comment]
使用原生的也有这个问题的，使用.lazy 显示是正常的了，但触发change 的时候这个问题又出现了
第一次输入`12` 显示值为 `undefined` 再次输入 `456` 显示内容  `12`,再次输入`123` 显示的是`456` 应该是这个lazy 引起的，这种该怎么解决
```html
<template slot="header">
  <input v-model.lazy="filter_condition.name" @change="handleChangeName">
</template>
```

**Comment by xing403** [comment]
使用原生的也有这个问题的，使用.lazy 显示是正常的了，但触发change 的时候这个问题又出现了
第一次输入`12` 显示值为 `undefined` 再次输入 `456` 显示内容  `12`,再次输入`123` 显示的是`456` 应该是这个lazy 引起的，这种该怎么解决
```html
<template slot="header">
  <input v-model.lazy="filter_condition.name" @change="handleChangeName">
</template>
```

**Comment by xing403** [comment]
想到了一种方法，使用路由后面携带参数 `tab`参数 表示需要渲染的指定列，测试了一下，没有出现延迟现象
> 格式：
`http://localhost:3000/table` 默认需要显示的列
`http://localhost:3000/table?tab=name` 需要展示`name`列

**Comment by wangdaodao** [comment]
> 使用原生的也有这个问题的，使用.lazy 显示是正常的了，但触发change 的时候这个问题又出现了 第一次输入`12` 显示值为 `undefined` 再次输入 `456` 显示内容 `12`,再次输入`123` 显示的是`456` 应该是这个lazy 引起的，这种该怎么解决
> 
> ```
> <template slot="header">
>   <input v-model.lazy="filter_condition.name" @change="handleChangeName">
> </template>
> ```

```vue
<template>
  <el-table
    :data="tableData.filter(data => !search || data.name.toLowerCase().includes(search.toLowerCase()))"
    style="width: 100%">
    <el-table-column
      label="Date"
      prop="date">
    </el-table-column>
    <el-table-column
      label="Name"
      prop="name">
    </el-table-column>
    <el-table-column
      align="right">
      <template slot="header" slot-scope="scope">
          <input v-model.lazy="search" @input="handleChangeName">
      </template>
      <template slot-scope="scope">
        <el-button
          size="mini"
          @click="handleEdit(scope.$index, scope.row)">Edit</el-button>
        <el-button
          size="mini"
          type="danger"
          @click="handleDelete(scope.$index, scope.row)">Delete</el-button>
      </template>
    </el-table-column>
  </el-table>
</template>
<script>
export default {
    data() {
      return {
        tableData: [{
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1517 弄'
        }, {
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄'
        }, {
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1516 弄'
        }],
        search: ''
      }
    },
    methods: {
      handleEdit(index, row) {
        console.log(index, row);
      },
      handleDelete(index, row) {
        console.log(index, row);
      },
      handleChangeName(val) {
        console.log(val.target.value)
      }
    }
  }
</script>
```

这么试试呢。

**Comment by xing403** [comment]
试过了，这个table的列初始化是显示出来的，所以输入或者其他都是正常的，实际是table中search的input所在列通过v-if先隐藏，当通过button再次显示这一列时，就出现了这种情况，怀疑是因为组件渲染的问题，可以通过通过请求路由参数的方式指定控制初始化的列项，就可以避免这个问题出现
