### ISSUE TITLE
select选择器BUG

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#2276]
vue  2.1.8
element 1.1.2
select可搜索选择器，设置默认选中值后，第一次点击只会出现默认选中的，要点击第二次才会载入所有的数据。
我直接用的官网例子里的代码测试的。
还请修复下，无法提供测试页，因为网络打不开在线测试的页面。。

**Comment by Leopoldthecoder** [comment]
已在 #2236 修复。
