### ISSUE TITLE
menu-怎么可以手工打开菜单？(暂时用v-if解决了这个问题。)

### ISSUE THREAD

**Issue by sailengsi** [ElemeFE/element#2278]
先复现一下我的问题吧。
线上地址：https://demo.sailengsi.com/sls-admin/vue2/dist/
1，直接登录，在头部会显示两个模块，默认显示功能模块的路由(也就是左侧的菜单)
2，左侧菜单第一个展开，第一个的子菜单高亮，正常没问题
3，当点击演示模块时，演示模块的路由(左侧菜单)渲染成功，但菜单并没有展开，这是问题！！！！！！
通过审查元素发现，虽然没有展开菜单，但第一个菜单的第一个子菜单元素有 is-active 这个class，所以可以证明我default-action匹配的子index是正确的，并且在调试时已  经过  验证。

ps：如果我两个模块下面的菜单数据配置是一模一样的，就ok，配置成不一样的，就出现这个问题了。
ps2:感谢一哥们提议，用v-if。思路是这样：左侧菜单不动态渲染，初始化就全部遍历好，切换模块时，让对应的显示，解决了这个问题。

**Comment by reverland** [comment]
1.1.2？

**Comment by sailengsi** [comment]
用的是vue2，element用npm安装的，默认应该是最新的吧？我忘了看了。。。其实我也建议增加一个手工设置index方法，自动的话，逻辑稍微复杂一点就应付不过来了。
