### ISSUE TITLE
navmenu  控件默认全部展开后，无法单击收回

### ISSUE THREAD

**Issue by kvsl9** [ElemeFE/element#2279]
menu  控件默认全部展开后，无法单击收回
使用属性：default-openeds="[1,2,3]"

### ElementUI version

1.1.2
### OS/Browers version

win10/chrome 55.0.2859.0
### Vue version

2.1.8
### What is actually happening?
Uncaught TypeError: this.openedMenus.splice is not a function
    at VueComponent.closeMenu (index.js:3)
    at VueComponent.boundFn [as closeMenu] (vue.js:129)
    at VueComponent.handleSubmenuClick (index.js:3)
    at VueComponent.boundFn [as handleSubmenuClick] (vue.js:129)
    at VueComponent.handleClick (index.js:3)
    at HTMLDivElement.boundFn (vue.js:130)

**Comment by baiyaaaaa** [comment]
请提供demo

**Comment by kvsl9** [comment]
@QingWei-Li 
问题解决了，:default-openeds需要在冒号,之前的代码没加冒号。
<el-menu theme="light" :default-openeds="['1','2','3']"></el-menu>

**Comment by ChangeZhang** [comment]
@kvsl9 求:default-openeds的用法

**Comment by SageSanyue** [comment]
> @kvsl9 求:default-openeds的用法

:default-openeds="['2','3']"  it works!!

`<el-menu :default-openeds="['2','3']">
<el-menu-item index="1">工作台</el-menu-item>
<el-submenu index="2">导航2</el-submenu>
<el-submenu index="3">导航3</el-submenu>
</el-menu>`
