### ISSUE TITLE
项目中的 examples 目录单独挪出来  无法 cooking watch

### ISSUE THREAD

**Issue by quqiufeng** [ElemeFE/element#228]
git clone 到本地
cd examples
移动和修改对应文件然后  cooking watch  和 cooking build 成功执行
(主要是把相应文件拷贝到examples目录,修改对应文件中需要修改路径的地方)
但是把 examples 目录移动到 /var/www/web 目录下
同样执行 cooking watch 访问 浏览器console 报错 app.js 37 行

eval("/* WEBPACK VAR INJECTION */(function(__dirname) {import Vue from 'vue';\nimport entry from './app';\nimport VueRouter from 'vue-router';\nimport configRouter from './route.config';\nimport Element from 'element-ui';\nimport 'element-ui/lib/theme-default/index.css';\nimport demoBlock from './components/demo-block.vue';\nimport MainFooter from './components/footer.vue';\nimport MainHeader from './components/header.vue';\nimport SideNav from './components/side-nav';\nimport FooterNav from './components/footer-nav';\nVue.use(Element);\nVue.use(VueRouter);\nVue.component('demo-block', demoBlock);\nVue.component('main-footer', MainFooter);\nVue.component('main-header', MainHeader);\nVue.component('side-nav', SideNav);\nVue.component('footer-nav', FooterNav);\nconst router = new VueRouter({\n  mode: 'hash',\n  base: __dirname,\n  routes: configRouter\n});\nnew Vue({\n  render: h => h(entry),\n  router\n}).$mount('#app');\n/* WEBPACK VAR INJECTION */}.call(exports, \"/\"))\n//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9lbnRyeS5qcz8zZjFmIl0sIm5hbWVzIjpbIlZ1ZSIsImVudHJ5IiwiVnVlUm91dGVyIiwiY29uZmlnUm91dGVyIiwiRWxlbWVudCIsImRlbW9CbG9jayIsIk1haW5Gb290ZXIiLCJNYWluSGVhZGVyIiwiU2lkZU5hdiIsIkZvb3Rlck5hdiIsInVzZSIsImNvbXBvbmVudCIsInJvdXRlciIsIm1vZGUiLCJiYXNlIiwiX19kaXJuYW1lIiwicm91dGVzIiwicmVuZGVyIiwiaCIsIiRtb3VudCJdLCJtYXBwaW5ncyI6IkFBQUEsd0RBQU9BLEdBQVAsTUFBZ0IsS0FBaEI7QUFDQSxPQUFPQyxLQUFQLE1BQWtCLE9BQWxCO0FBQ0EsT0FBT0MsU0FBUCxNQUFzQixZQUF0QjtBQUNBLE9BQU9DLFlBQVAsTUFBeUIsZ0JBQXpCO0FBQ0EsT0FBT0MsT0FBUCxNQUFvQixZQUFwQjtBQUNBLE9BQU8sd0NBQVA7QUFDQSxPQUFPQyxTQUFQLE1BQXNCLDZCQUF0QjtBQUNBLE9BQU9DLFVBQVAsTUFBdUIseUJBQXZCO0FBQ0EsT0FBT0MsVUFBUCxNQUF1Qix5QkFBdkI7QUFDQSxPQUFPQyxPQUFQLE1BQW9CLHVCQUFwQjtBQUNBLE9BQU9DLFNBQVAsTUFBc0IseUJBQXRCO0FBQ0FULElBQUlVLEdBQUosQ0FBUU4sT0FBUjtBQUNBSixJQUFJVSxHQUFKLENBQVFSLFNBQVI7QUFDQUYsSUFBSVcsU0FBSixDQUFjLFlBQWQsRUFBNEJOLFNBQTVCO0FBQ0FMLElBQUlXLFNBQUosQ0FBYyxhQUFkLEVBQTZCTCxVQUE3QjtBQUNBTixJQUFJVyxTQUFKLENBQWMsYUFBZCxFQUE2QkosVUFBN0I7QUFDQVAsSUFBSVcsU0FBSixDQUFjLFVBQWQsRUFBMEJILE9BQTFCO0FBQ0FSLElBQUlXLFNBQUosQ0FBYyxZQUFkLEVBQTRCRixTQUE1QjtBQUNBLE1BQU1HLFNBQVMsSUFBSVYsU0FBSixDQUFjO0FBQzNCVyxRQUFNLE1BRHFCO0FBRTNCQyxRQUFNQyxTQUZxQjtBQUczQkMsVUFBUWI7QUFIbUIsQ0FBZCxDQUFmO0FBS0EsSUFBSUgsR0FBSixDQUFRO0FBQ05pQixVQUFRQyxLQUFLQSxFQUFFakIsS0FBRixDQURQO0FBRU5XO0FBRk0sQ0FBUixFQUdHTyxNQUhILENBR1UsTUFIVixFIiwiZmlsZSI6Ijc2LmpzIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IFZ1ZSBmcm9tICd2dWUnO1xuaW1wb3J0IGVudHJ5IGZyb20gJy4vYXBwJztcbmltcG9ydCBWdWVSb3V0ZXIgZnJvbSAndnVlLXJvdXRlcic7XG5pbXBvcnQgY29uZmlnUm91dGVyIGZyb20gJy4vcm91dGUuY29uZmlnJztcbmltcG9ydCBFbGVtZW50IGZyb20gJ2VsZW1lbnQtdWknO1xuaW1wb3J0ICdlbGVtZW50LXVpL2xpYi90aGVtZS1kZWZhdWx0L2luZGV4LmNzcyc7XG5pbXBvcnQgZGVtb0Jsb2NrIGZyb20gJy4vY29tcG9uZW50cy9kZW1vLWJsb2NrLnZ1ZSc7XG5pbXBvcnQgTWFpbkZvb3RlciBmcm9tICcuL2NvbXBvbmVudHMvZm9vdGVyLnZ1ZSc7XG5pbXBvcnQgTWFpbkhlYWRlciBmcm9tICcuL2NvbXBvbmVudHMvaGVhZGVyLnZ1ZSc7XG5pbXBvcnQgU2lkZU5hdiBmcm9tICcuL2NvbXBvbmVudHMvc2lkZS1uYXYnO1xuaW1wb3J0IEZvb3Rlck5hdiBmcm9tICcuL2NvbXBvbmVudHMvZm9vdGVyLW5hdic7XG5WdWUudXNlKEVsZW1lbnQpO1xuVnVlLnVzZShWdWVSb3V0ZXIpO1xuVnVlLmNvbXBvbmVudCgnZGVtby1ibG9jaycsIGRlbW9CbG9jayk7XG5WdWUuY29tcG9uZW50KCdtYWluLWZvb3RlcicsIE1haW5Gb290ZXIpO1xuVnVlLmNvbXBvbmVudCgnbWFpbi1oZWFkZXInLCBNYWluSGVhZGVyKTtcblZ1ZS5jb21wb25lbnQoJ3NpZGUtbmF2JywgU2lkZU5hdik7XG5WdWUuY29tcG9uZW50KCdmb290ZXItbmF2JywgRm9vdGVyTmF2KTtcbmNvbnN0IHJvdXRlciA9IG5ldyBWdWVSb3V0ZXIoe1xuICBtb2RlOiAnaGFzaCcsXG4gIGJhc2U6IF9fZGlybmFtZSxcbiAgcm91dGVzOiBjb25maWdSb3V0ZXJcbn0pO1xubmV3IFZ1ZSh7XG4gIHJlbmRlcjogaCA9PiBoKGVudHJ5KSxcbiAgcm91dGVyXG59KS4kbW91bnQoJyNhcHAnKTtcblxuXG5cbi8qKiBXRUJQQUNLIEZPT1RFUiAqKlxuICoqIC4vZW50cnkuanNcbiAqKi8iXSwic291cmNlUm9vdCI6IiJ9");

定位后是
entry.js 第一行
import Vue from 'vue';
报错

还有什么地方需要修改?

谢谢!

**Comment by Leopoldthecoder** [comment]
只把 examples 移出来？那肯定是不行的，依赖了 element 文件夹里的很多东西

**Comment by QingWei-Li** [comment]
examples 依赖了 src
