### ISSUE TITLE
firstDayOfWeek: 1  不起效果

### ISSUE THREAD

**Issue by arronf2e** [ElemeFE/element#2280]
### ElementUI version

^1.0.0-rc.7
### OS/Browers version

macOS
### Vue version

2.0.3
### Steps to reproduce
    <el-date-picker
	v-model="week"
	v-show = "active == 0"
	type="week"
	placeholder="选择周"
	format="yyyy 第 WW 周"
	:picker-options="pickerOptions">
    </el-date-picker>

    pickerOptions: {
        firstDayOfWeek: 1
    }
### What is Expected?
使用firstDayOfWeek: 1  将周的开始日期设置为周一
### What is actually happening?
没有效果

**Comment by Leopoldthecoder** [comment]
`firstDayOfWeek` 是 1.1.0 版本才支持的功能。请确认 Element 的版本。
