### ISSUE TITLE
[Bug Report] date-picker组件显示异常

### ISSUE THREAD

**Issue by Anakass** [ElemeFE/element#22804]
### Element UI version
2.13.0

### OS/Browsers version
mac chrome

### Vue version
2.6.10

### Steps to reproduce
部分用户在chrome下能复现，无痕模式或者其他浏览器下正常。

### What is Expected?
正常展示日期项

### What is actually happening?
20~24号展示twenty one, twenty two, twenty three, twenty four
![20240201-103511](https://github.com/ElemeFE/element/assets/97978419/d00c9fa0-5129-42a1-a048-75d2a28968e9)

**Comment by samilywang** [comment]
@Anakass 你好，我也碰到了同样的问题，想问下，这个问题的原因是啥，是怎么解决的？
