### ISSUE TITLE
el-rate在线运行看不到效果

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#2281]
谷歌浏览器
官方的el-rate样例在点击在线运行时，在jsfiddle看不到运行结果。

**Comment by Leopoldthecoder** [comment]
具体是哪个例子？如果是「其他 icon」的话，那么是意料中的，因为使用的 icon 并不是 Element 提供的。

**Comment by kopheece** [comment]
@Leopoldthecoder 真巧  我就测试的那个「其他 icon」   还真是
