### ISSUE TITLE
关于v-model.number的问题

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#2282]
demo: http://jsfiddle.net/kopheece/cdsdtLvd/
基于官方的原样例，只是去掉了年龄必须大于18的限制
输入的时候，比如输0，会提示‘’年龄不能为空‘’；在比如输入09，直接变9；
貌似就是不能以0开头，这个问题怎么解决呢；

**Comment by Kingwl** [comment]
那就不number呗

**Comment by baiyaaaaa** [comment]
0开头的本来就不是number

**Comment by kopheece** [comment]
改成不number的形式了，然后再用正则校验是否输入为数字
