### ISSUE TITLE
关于el-rate的disabled使用

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#2284]
demo: http://jsfiddle.net/kopheece/6py2wwr7/
希望的效果是，把demo的运行结果disabled掉，

但在测试中发现，如果直接加入disabled属性 ，效果如下
![image](https://cloud.githubusercontent.com/assets/23140033/21747478/d5967be4-d5a2-11e6-910b-f540e13f044a.png)
也测试过text-template属性，没预期的结果

**Comment by Leopoldthecoder** [comment]
你的预期是什么？

**Comment by kopheece** [comment]
@Leopoldthecoder  demo的运行结果不能在变动  意思是el-rate绑定某个值后，鼠标移动到评分那不在变化。就像官网里面的那个【只读】例子那样的效果

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/6py2wwr7/2/

**Comment by kopheece** [comment]
@Leopoldthecoder 谢谢先  在问下  那第三个灰掉的星不能显示？

**Comment by Leopoldthecoder** [comment]
显示了，只是和背景颜色太相似：http://jsfiddle.net/6py2wwr7/3/

**Comment by kopheece** [comment]
@Leopoldthecoder 看到了 谢谢
