### ISSUE TITLE
[Bug Report] Nested dialog boxes contain tables with checkbox properties set. Selecting a checkbox can cause Google Chrome to crash

### ISSUE THREAD

**Issue by LCSluchaoshun** [ElemeFE/element#22853]
### Element UI version
2.15.14

### OS/Browsers version
macPro / Chrome / 123.0.6312.124

### Vue version
2.7.16

### Reproduction Link
https://codepen.io/luchaoshun/pen/GRLXeWW

### Steps to reproduce
1.open Dialog;
2.open the inner Dialog;
3.Select checkbox ;

### What is Expected?
Browser is normal

### What is actually happening?
Browser crashes!

**Comment by RishyPa** [comment]
Upgrade to version 124 and it's back to normal, but only Edge.
Chrome as in the past

**Comment by LCSluchaoshun** [comment]
How should I be compatible with Chrome browser？

**Comment by LCSluchaoshun** [comment]
Today, I upgraded the version to 125.0.6422.4 (beta) and resolved the issue; Thank you for your help!

**Comment by LCSluchaoshun** [comment]
> 升级到124版本就恢复正常了，但仅限Edge。 Chrome 一如既往

Today, I upgraded the version to 125.0.6422.4 (beta) and resolved the issue; Thank you for your help!
