### ISSUE TITLE
Carousel does not take to next slide using setActiveItem function

### ISSUE THREAD

**Issue by mimani** [ElemeFE/element#2285]
### ElementUI version
1.1.2

### OS/Browers version
JSFiddle, Chrome:  55.0.2883.95

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/wd1a1toh/

### Steps to reproduce
I have buttons to go to next slide and previous slide which does not work on clicking on them

### What is Expected?
On clicking on button carousel should had taken to corresponding slide

### What is actually happening?

>Uncaught TypeError: setActiveItem is not a function

**Comment by Leopoldthecoder** [comment]
Because you never defined `setActiveItem`.
Example: http://jsfiddle.net/wd1a1toh/1/ .
