### ISSUE TITLE
[交互效果]展开子菜单的问题

### ISSUE THREAD

**Issue by neo4dev** [ElemeFE/element#2288]
### Steps to reproduce
http://jsfiddle.net/neo4dev/wqxuxyzm/1/
### What is Expected?
当设置为只展开一个菜单的时候，点击不同菜单应该是很流畅的效果
### What is actually happening?
点击其他菜单时会有闪现，好像是先展开再隐藏之前的效果，频繁点击看着很不流畅

**Comment by reverland** [comment]
#2274
