### ISSUE TITLE
想要树状表格的猿媛们，这里是个参考实现！

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#2289]
https://git.oschina.net/bfgdqch/EleAdmin

刚用Element实现的简单数状表格。

**Comment by QingWei-Li** [comment]
Great 有好东西欢迎提交 PR 到 https://github.com/ElementUI/awesome-element 或者到这个 Issue https://github.com/ElemeFE/element/issues/2254

**Comment by lampo1024** [comment]
@jixzfw good job...
