### ISSUE TITLE
下载最elment最新源码，本地编译打包，发现构建出来的文件，和npm install 构建出来的文件不一样

### ISSUE THREAD

**Issue by wuhaih** [ElemeFE/element#2291]
element 版本：1.0.9

1、webpark dist命令构建后的lib文件夹有文件 element-ui.common 与npm install element-ui 文件夹中的 element-ui.common  不一样，

2、没有构建出来的文件模块

var _autocompleteSuggestions = __webpack_require__(20);

	var _autocompleteSuggestions2 = _interopRequireDefault(_autocompleteSuggestions);

	var _emitter = __webpack_require__(24);

	var _emitter2 = _interopRequireDefault(_emitter);

3、官方是否能给个解释，自行构建出来的文件，替换node_module element-ui  跑不通，

**Comment by QingWei-Li** [comment]
1. 请不要滥用 Issue
2. 有问题请到 Gitter 里问

**Comment by xchz** [comment]
gitter里的问题，讨论，后来的人很难保留和查找吧，在issue里更方便，为啥一定要用gitter？
