### ISSUE TITLE
[Bug Report] edge浏览器样式崩盘，涉及到的有表单，弹窗，按钮等

### ISSUE THREAD

**Issue by SuperLeven** [ElemeFE/element#22910]
### Element UI version
2.15.14

### OS/Browsers version
edge浏览器

### Vue version
2.7.16

### Reproduction Link
https://github.com/company/project/issues/123?desc=因为这个重现链接一直提示不正确，没法了只能随便填一个

### Steps to reproduce
使用Microsoft Edge 浏览器打开：https://element.eleme.cn/#/zh-CN/component/button

### What is Expected?
与谷歌浏览器表现一致

### What is actually happening?
 样式错乱

**Comment by SuperLeven** [comment]
一般人不我告诉他，你们用vue2+elementui写的项目，样式在edge浏览器崩了，当然，我是说在座的各位写的项目，在Edge浏览器中都有同样的问题

**Comment by SuperLeven** [comment]
![Uploading L1VzZXJzL2xldmVuL0xpYnJhcnkvQ29udGFpbmVycy81WlNMMkNKVTJULmNvbS5kaW5ndGFsay5tYWMvRGF0YS9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvRGluZ1RhbGtNYWMvMTk4ODAyOTE1X3YyL0ltYWdlRmlsZXMvMTcxOTk5MDg1NjI0NV9DNDQ3Q0M5NS00NDQ3LTQ1NDYtQjVEMC00MzlFOTMzM0I3RDkucG5n.png…]()

**Comment by SuperLeven** [comment]
![L1VzZXJzL2xldmVuL0xpYnJhcnkvQ29udGFpbmVycy81WlNMMkNKVTJULmNvbS5kaW5ndGFsay5tYWMvRGF0YS9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvRGluZ1RhbGtNYWMvMTk4ODAyOTE1X3YyL0ltYWdlRmlsZXMvMTcxOTk5MDg1NjI0NV9DNDQ3Q0M5NS00NDQ3LTQ1NDYtQjVEMC00MzlFOTMzM0I3RDkucG5n](https://github.com/ElemeFE/element/assets/75765099/be07de7c-a0a0-4873-bb55-e845cc9dcdd9)

**Comment by SuperLeven** [comment]
![image](https://github.com/ElemeFE/element/assets/75765099/02ea16de-1791-4a44-a944-cc79f460a1b8)
当然最火的若依框架也不能幸免

**Comment by SuperLeven** [comment]
![image](https://github.com/ElemeFE/element/assets/75765099/89b3100f-347a-4420-81fd-2388f3122b6f)

**Comment by wangdaodao** [comment]
> 一般人不我告诉他，你们用vue2+elementui写的项目，样式在edge浏览器崩了，当然，我是说在座的各位写的项目，在Edge浏览器中都有同样的问题

![图片](https://github.com/ElemeFE/element/assets/2317442/65675b83-d096-46ff-ade1-15cf678f0d59)

你把浏览器插件全部都停用了，再看看？

**Comment by SuperLeven** [comment]
是我的问题。浏览器插件导致的页面样式错版，我反思
