### ISSUE TITLE
上传组件怎么获取文件列表对应名字dom

### ISSUE THREAD

**Issue by 598220654** [ElemeFE/element#2292]
![image](https://cloud.githubusercontent.com/assets/15324717/21756188/ad520eb2-d658-11e6-8f9a-74dadaab529a.png)
现在有个需求，如果是图片,就把对应的icon换成图片的地址，现在我上传成功或者失败不知道怎么拿到对应dom来修改它们

**Comment by Leopoldthecoder** [comment]
没看懂，自己去操作 DOM 有什么问题？

**Comment by jikkai** [comment]
@598220654 

事实上对这块地方有高度定制的需求的话，可以把原有的`show-upload-list`设置为`false`，然后自己通过`on-remove`和`on-success`两个钩子内的回调参数`fileList`实现一个文件列表。

这么做有个缺点就是会失去上传进度条，得用`on-progress`自行实现一个上传进度条……

这么一想有高度定制的场景完全可以找一个能够做到这些的上传组件顶着，没必要全用element的😂

**Comment by 598220654** [comment]
@jikkai 我看他组件都是一套,所以想用他们上传.以为可以改变样式,只能用他们现有的吧

**Comment by 598220654** [comment]
@jikkai 谢谢,我也只能这样子做呢!

**Comment by chqfly** [comment]
我也有类似的需求，我利用on-success和on-progress实现了上传进度条。 我在on-progress回调里面写了：`handleUploadProgress(event,file,fileList) {
                for(let i = 0, len = fileList.length; i < len; i++) {
                    if(Math.floor(fileList[i].percentage) <90){
                        fileList[i].statusDesc = '文件上传中...';
                    }else{
                        fileList[i].statusDesc = '文件转换中...';
                    }
                }
                this.uploadFileList = fileList;
            },` 但是else里面的代码始终不会被执行，奇怪的是进度条里面又显示了100%. 这是为什么啊？
