### ISSUE TITLE
在Row Attributes中,设置了type=flex,为什么align="middle"没有生效

### ISSUE THREAD

**Issue by hxdhero** [ElemeFE/element#2293]
<el-row type="flex" justify="center" align="middle>

其中justify="center"有效,但是align="middle"无效

**Comment by Leopoldthecoder** [comment]
无法重现：http://jsfiddle.net/1c35v3o0/ ，请提供 demo。

**Comment by hxdhero** [comment]
http://jsfiddle.net/1c35v3o0/1/

请看这里,是不是我什么地方写错了

**Comment by jikkai** [comment]
@hxdhero 这里看也是正常的，能否提供一下浏览器、操作系统、使用的elementui和vue的版本？

**Comment by hxdhero** [comment]
@jikkai @Leopoldthecoder 

浏览器        chrome 版本 55.0.2883.87 (64-bit)
os               Linux Mint 18 Cinnamon 64-bit             Cinnamon版本3.0.6


elementui和vue使用了CDN的地址

https://unpkg.com/element-ui/lib/index.js
https://unpkg.com/vue/dist/vue.js

**Comment by Leopoldthecoder** [comment]
没看出来你的 demo 有什么问题。你希望的效果是？

**Comment by hxdhero** [comment]
@Leopoldthecoder 我希望表单可以在垂直和水平方向居中,显示在屏幕中央,现在缺少垂直方向的居中效果

**Comment by Leopoldthecoder** [comment]
那是因为你的容器没有定高。

**Comment by hxdhero** [comment]
@Leopoldthecoder 明白了,谢谢

**Comment by zjhr** [comment]
@Leopoldthecoder 你好，今天我遇到这个问题，我用的是vue2.5.17，elementui2.4.8，本来想用el-row的垂直排列的，但是发现无效，后来找到了这个issues，你的demo确实显示出来是垂直排列的，把你上面那个demo复制到我的项目，试了一下，居然还是无效的，请问是不是element的bug？

**Comment by canwhite** [comment]
定高也不解决问题，遇到一个类似的错误

**Comment by ZolaSFantasy** [comment]
我也遇到这个问题了，解决了吗，现在

**Comment by ZolaSFantasy** [comment]
> 那是因为你的容器没有定高。

您好，我也遇到了这个问题，
elemrntui  与vue 用的是cdn
os 是windows
浏览器 chrom
定高也没效果

**Comment by ZolaSFantasy** [comment]
> 那是因为你的容器没有定高。

@Leopoldthecoder 
您好，我也遇到了这个问题，
elemrntui 与vue 用的是cdn
os 是windows
浏览器 chrom
定高也没效果

**Comment by Guyiming** [comment]
说不行的, 尝试给<el-row>一个固定的高度再试

**Comment by wushengxin2012** [comment]
> > 那是因为你的容器没有定高。
> 
> @Leopoldthecoder
> 您好，我也遇到了这个问题，
> elemrntui 与vue 用的是cdn
> os 是windows
> 浏览器 chrom
> 定高也没效果

我也遇到了这个问题，但是我发现了问题的原因，希望对你们也有用。
我在 el-row 里面设置了 type="flex" 和 align="middle"。但是没有用是因为，我在这个 el-row 的 el-col 中设置了 行高：min-heigth: 80; 这样。我把 el-col 中的 行高删除掉。然后就可以正常的垂直居中了。
