### ISSUE TITLE
建议下拉菜单增加一个下拉框对齐方式的选项

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#2294]
在用nav的时候，如果菜单比较长，最后一个菜单点开以后的下拉框可能出现在屏幕外围，造成弹出菜单被截断。

可以通过如下css解决这个问题
```
       .el-menu {
            background-color: transparent;
            right: 0 !important;
            left: auto !important;
        }
```

但是如果把上面的css写在组件的 `scoped css` 里面并不能起作用，因为subment并没有继承menu的id，所以感觉这部分做成组件的选项比较好。

“‘下拉菜单”组件也有类似问题

bootstrap的类似功能：http://v3.bootcss.com/components/#dropdowns

**Comment by baiyaaaaa** [comment]
下拉菜单？所以你说的是 Menu 还是 Dropdown 组件

**Comment by languanghao** [comment]
@baiyaaaaa 两个都有，就是点击会出现下拉框的组件都有这个问题，如果下拉框的文字比较长，而且正好这个组件又处于页面边缘，下拉框会超出页面边缘

**Comment by baiyaaaaa** [comment]
dropdown 组件是有对齐选项的，Menu组件的话，水平模式下子菜单宽度是和父级相同的，撑满100%，应该不存在对齐的问题把？

**Comment by languanghao** [comment]
@baiyaaaaa 我写了个例子   http://jsfiddle.net/8dr112ou/

![qq 20170112135906](https://cloud.githubusercontent.com/assets/3765379/21878758/4ed1f93c-d8cf-11e6-872f-ad389b804e0b.png)

我是指下拉框整个框相对于它的父级应该是“右对齐”了，这样可以防止溢出屏幕

**Comment by baiyaaaaa** [comment]
seem feature request as #5441
