### ISSUE TITLE
固定列fixed设置宽度在chrome和IE浏览器下是正常的 但是在firefox下显示不正常？bug？

### ISSUE THREAD

**Issue by hujianjian187** [ElemeFE/element#2296]
如图
![hr6c f1004_ h3 2h1k8rjd](https://cloud.githubusercontent.com/assets/22463383/21756871/83d94768-d661-11e6-8922-48818ac1750b.png)
![v4hnqvurtm0b thyuwu a5m](https://cloud.githubusercontent.com/assets/22463383/21756872/84f8af6c-d661-11e6-842d-4757191b2396.png)

**Comment by hujianjian187** [comment]
</el-table-column>

					    <el-table-column  :context="_self"  align="center" width="145" fixed="right"  label="操作"  >
					      <template scope="scope">
					      	<el-button type="success" @click="handleEdit(scope.$index, scope.row)"     size="small">编辑</el-button>
					      	<el-button type="danger"  @click="handleDelete(scope.$index, scope.row)"   size="small" >删除</el-button>
					      </template>

					    </el-table-column>

**Comment by QingWei-Li** [comment]
估计是滚动条的宽度不一致导致的，宽度设置大一点应该能解决

**Comment by hujianjian187** [comment]
@QingWei-Li   对 宽度大一点是可以解决   但是你们不可以对这个同意设置一下吗？
