### ISSUE TITLE
Table 的多选Checkbox 能否动态设置其disable样式

### ISSUE THREAD

**Issue by wlx200510** [ElemeFE/element#2299]
### What is Expected?
用toggleSelection这个方法选中的行  希望前面的checkbox是选中的置灰状态  禁止取消勾选
### What is actually happening?
目前没有很好的方法来实现

**Comment by Tinysusie** [comment]
你好~ 这个问题解决了么，遇到相同的需求 T.T

**Comment by wlx200510** [comment]
分两步，第一步是用那个form多选控件中标识是否disable的属性，第二步是对这些disable选择的项用代码选中，就行了。

**Comment by Tinysusie** [comment]
@wlx200510 噢！ 谢谢
