### ISSUE TITLE
table存在fixed列时无数据的样式问题

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#2300]
### ElementUI version
1.1.2

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/z52ydbqf/

### What is Expected?
希望能统一样式

### What is actually happening?
当表格设置了fixed的列，但是无数据时，表格下方会有一个放置滚动条的空白区域，非常难看。但是如果表格设置了`max-height`属性，这个问题就没有了。通过查看代码，发现如果设置了 `max-height` ，表格会多一个class叫 `el-table--fluid-height`，fixed的列会多两个样式：

```
.el-table--fluid-height .el-table__fixed, .el-table--fluid-height .el-table__fixed-right {
    bottom: 0;
    overflow: hidden;
}
```

**Comment by hujianjian187** [comment]
对我也是这样的！ 有时候！还有兼容性问题！ 浏览器
