### ISSUE TITLE
bug table增加了default-sort-prop和default-sort-order导致,导致了初始化时也触发了change事件

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#2306]
版本:1.1.3
table应该是加了这两个属性后，导致触发change事件的。

临时解决
handleSortChange(val){
      	let me=this
      	console.log(val)
      	if (val.column){
	      	me.sortValues = {
	      		column:val.column,
				order:val.order,
				prop:val.prop
			}
	      	this.fetchData();
      	}
      },

**Comment by Leopoldthecoder** [comment]
@njleonzhang 有兴趣的话可以来看看。

**Comment by njleonzhang** [comment]
@Leopoldthecoder 我的锅。。回头看看

**Comment by AaronChen2012** [comment]
还有个bug，设置了default-sort-prop 后，点其他列的时候，这个默认的没有清除掉

**Comment by njleonzhang** [comment]
@AaronChen2012 好的，我来看下

**Comment by njleonzhang** [comment]
fixed in https://github.com/ElemeFE/element/pull/2309/commits/22cea4e6c40289d2e51fb82973a82360c3ec1a84

**Comment by pz25925** [comment]
@njleonzhang  @Leopoldthecoder 

2.4.4 版本复现此问题. 

重现步骤: 

1, 设定 :default-sort
2, 设定 @sort-change
3. 初始化加载表格数据
4. getData 方法执行了2次

复现链接:
https://jsfiddle.net/9aL4wozr/4/
