### ISSUE TITLE
el-dialog in el-dialog

### ISSUE THREAD

**Issue by hisland** [ElemeFE/element#2307]
el-dialog 里面再写个 el-dialog, 如链接的示效果 
是否应该把 dialog 像 popover 那样弄出来放 body?

### ElementUI version
1.1.3

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/hisland/jn8dsdeu/1/

![image](https://cloud.githubusercontent.com/assets/417448/21764776/c1eb65a2-d69f-11e6-8d64-1ee1bc1c0d59.png)

**Comment by Leopoldthecoder** [comment]
Dialog 不支持嵌套。两个 Dialog 不要写成父子元素就好。
