### ISSUE TITLE
Feature request: Collapsible navbar menus and collapsible drawar/sidebar 

### ISSUE THREAD

**Issue by otabekgb** [ElemeFE/element#2308]
This is the  main feature missing in element which prevents me from adopting it. It is important for hybrid mobile/desktop responsive web apps.

**Comment by reverland** [comment]
element-ui however may not be responsive...

**Comment by otabekgb** [comment]
@reverland , grid is already responsive

**Comment by reverland** [comment]
No, it is not intended for mobile platform.
As far as I see, the components may not well designed for mobile apps.

You may find mint-ui useful?

**Comment by otabekgb** [comment]
Developing for mobile and desktop separately is a double work, and repeating is cause of most bugs.

**Comment by reverland** [comment]
Not really, you may prefer material-design if you want more than just a PC website.

you should notice that the date-picker, slider, dialog, loading breadcrumbs, select and so on are not designed for mobile platform.

implement a responsive component library is hard, as far as I can see, I don't think element-ui will consider responsive.

**Comment by baiyaaaaa** [comment]
Element is design for backstage management system and have no plan for responsive design. I'm totally agreed with @reverland , implement a  responsive component is not a good idea actually. In  grid, we just provide responsive props to make the flexible layout.
