### ISSUE TITLE
Can't select Checkbox from non-reactive array

### ISSUE THREAD

**Issue by diemah77** [ElemeFE/element#2310]
### ElementUI version
Latest

### Vue version
Latest

### Reproduction Link
http://codepen.io/diemah77/pen/vgNdBa?editors=1010

### Steps to reproduce
I'm trying to display a list of checkboxes from a non-reactive "items" Array set in Vue's created hook.  

### What is expected?
Each selected checkbox shows selected state.

### What is actually happening?
Only the border of the checkbox turns blue without the "checked" icon. The pen also shows native checkbox input example that works.

**Comment by baiyaaaaa** [comment]
it's because the non-reactive "items". You should add a the 'items'  in component data options
