### ISSUE TITLE
Uploder 的钩子能否允许传回自定义参数

### ISSUE THREAD

**Issue by toutouli** [ElemeFE/element#2311]
### ElementUI version
1.1.2

场景是这样的：我在一个页面里使用多个Uploder组件来上传多张图片，
目前只能通过给每个Uploder的on-success钩子绑定一个特定的方法，
代码看起来是这样的，感觉蠢蠢的
```js
idCardSuccess(response, file, fileList){
  this.submiti.idCard=response.data.img
},

bankCardSuccess(response, file, fileList){
  this.submiti.bankCard=response.data.img
}
...
```

如果可以给钩子传自定义参数，那就爽多了
```js
onSuccess(response, file, fileList, key){
  this.submit[key]=response.data.img
},
```

**Comment by baiyaaaaa** [comment]
这个属于最佳实践的问题，可以到giiter询问下

**Comment by johntostring** [comment]
我遇到了同样的问题，然鹅，gitter上有人问了，也根本没人回复，最后我自己想出了这种方式实现：
```
handleSuccess (custom) {
  return (res, file) => {
    custom.fieldA = window.URL.createObjectURL(file.raw)
    console.log('end:', custom)
  }
}
```
custom就是你自定义的参数，**注意如果直接将fieldA作为自定义参数，修改不会生效。**
后入坑的童鞋，如果对你有帮助请给个👍

**Comment by weiwill** [comment]
@johntostring 太厉害了，解决了我的困扰，不过新手不懂原理

**Comment by jaore** [comment]
@johntostring  前面调用是不是:on-success="handleSuccess"？参数要写在哪里呢—.— 恕我愚昧，使用后第一个参数还是用的默认的response

**Comment by chending1994** [comment]
怎么解决的额？

**Comment by chending1994** [comment]
@weiwill 请问怎么解决的额？
