### ISSUE TITLE
Provide a property to center whole Steps component (or do it by default)

### ISSUE THREAD

**Issue by Frondor** [ElemeFE/element#2315]
Actually, `<el-steps align-center>` only aligns the titles, but the whole steps component is left aligned.

![](https://i.gyazo.com/7f83477fa9593a11e527191e44280ce1.png)
As you can see in this example **http://jsfiddle.net/wc1ef0zz/** the `el-step__icon` is left-aligned, so the whole component is turned to the left. It doesn't looks good on certain cases where you need it centered.

A hacky way I'm trying at the moment is `.el-steps.is-horizontal { padding-left: 20% }` but... this is really ugly :smile:

**Comment by chendind** [comment]
有解决方案了么
