### ISSUE TITLE
复合型输入框中左置菜单点击后，菜单内容不能上拉至左置label中

### ISSUE THREAD

**Issue by yew30** [ElemeFE/element#2317]
http://element.eleme.io/#/zh-CN/component/input 中的demo点击后效果正常
官方建立的样本http://jsfiddle.net/api/post/library/pure/ 点击不正常

**Comment by baiyaaaaa** [comment]
demo没保存

**Comment by Leopoldthecoder** [comment]
给 `.el-select` 设个宽度就可以。

现在文档上在线运行已经修复了。
