### ISSUE TITLE
tree基于懒加载的自动刷新

### ISSUE THREAD

**Issue by stanNo1** [ElemeFE/element#2318]
tree组件使用 load方法加载子数据，当tree变更后，如何刷新当前数
没有api，可否增加
O(∩_∩)O谢谢

**Comment by tomieric** [comment]
使用`Tree的Node类方法实现`

每个node节点都可以获取到Node的实例对象

参照[无刷新无限级的tree组件管理实例](https://github.com/Kuaizi-co/TreeManager)
