### ISSUE TITLE
select选择器，在编辑数据的时候，逻辑严重不对

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#2319]
vue  2.1.8
element-ui  1.1.3

我现在做的是省市联动功能，在编辑数据的时候，打开编辑页面，用了select默认选中，初始页面的时候就会触发change事件，这样的问题是，你第一次是没问题了，但是你第二次触发change事件的时候，地级市的select框默认值本来应该清空掉，如果在change里设置先清空再加载，初始页面的时候默认值也没有了，这逻辑晕菜。正确的，初始页面的时候应该不能触发change事件

建议：辛苦各位大大排期 新增一个级联选择器吧，太需要这个了，这个用的地方太多了。。

**Comment by TkJiangBo** [comment]
自己兼容一下呗 我也遇到了 
第一次加载change return false

**Comment by Leopoldthecoder** [comment]
级联选择器已经在计划中了。

**Comment by zhuqueyi** [comment]
有什么兼容方法么，急需解决啊
