### ISSUE TITLE
Button中设置type='text',并且有:loading时,背景不是透明色

### ISSUE THREAD

**Issue by wenner** [ElemeFE/element#2321]
同标题 , 因为一下的css,所以不是透明色
多加一个 .el-button--text:is-loading:before {background:0 0} 的样式就好了

目前的
.el-button--text {
    border: none;
    color: #20a0ff;
    background: 0 0;
    padding-left: 0;
    padding-right: 0;
}

.el-button.is-loading:before {
    pointer-events: none;
    content: '';
    position: absolute;
    left: -1px;
    top: -1px;
    right: -1px;
    bottom: -1px;
    border-radius: inherit;
    background-color: rgba(255,255,255,.35);
}

**Comment by baiyaaaaa** [comment]
type='text'的button和loading状态同时使用是不合理的，我们在设计上就不考虑这种用法
