### ISSUE TITLE
Carousel 走马灯设置autoplay无效

### ISSUE THREAD

**Issue by JaneFeng** [ElemeFE/element#2323]
### ElementUI version
1.1.3

### Vue version
2.1.0

```
<el-carousel :autoplay="false"></el-carousel>
```

设置为false依旧自动播放，修改官网的例子也无效

**Comment by SeanDream** [comment]
同样的问题，求解决

**Comment by IsaacLuo** [comment]
同样的问题，求解决，在用webpack server调试时没问题，但是在webpack build打包后有问题。autoplay=false时走马灯不会停下
