### ISSUE TITLE
Table组件的排序列的排序事件触发范围太小 

### ISSUE THREAD

**Issue by xnumb** [ElemeFE/element#2324]
RT
希望table组件的 排序 功能 的点击范围能是包括column 头的 标题 要不 上下箭头的范围实在是太小

**Comment by xnumb** [comment]
我觉得你说的也不错 毕竟 筛选加 排序 共同出现的情况实在是少 为了这种极少数出现的情况去妥协这么常见的需求的体验 感觉不是很合适 
如果有这种情况 再按现在的方式实现 如果不共存就 都可以 整个 th去作为触发范围 

一点建议 望采纳 谢谢～

**Comment by njleonzhang** [comment]
我之前想改来着，但是考虑table有[筛选](http://element.eleme.io/#/zh-CN/component/table#shai-xuan)的功能，所以也不太好直接设置th作为事件的触发元素。除非里面做个判断，在用户没有用筛选功能的时候，把事件绑到th上。

**Comment by njleonzhang** [comment]
@Leopoldthecoder 你们没空做的话，我有空改一下。:-)

**Comment by njleonzhang** [comment]
现在做成了这样，请大家review：

将sort和filter的点击范围扩大到th标签。

1. 如果th里只有sort, 则点击th等于点击sort的图标，并发送header-click事件。
2. 如果th里只有filter，则点击th等于点击filter, 并发送header-click事件。
3. 如果th既有sort又有filter，则点击th无作用，只发送header-click事件。

**Comment by Kingwl** [comment]
感觉有一种莫名的蛋疼...

**Comment by njleonzhang** [comment]
@Kingwl 啊  什么意思。

**Comment by renxia** [comment]
这个改的有问题啊，人家原来是有上下箭头，代表升/降序，你这改的只有一个 asc 了，箭头的高亮也都没了
@njleonzhang

**Comment by njleonzhang** [comment]
@renxia 啊，已经release了啊。都正常啊。你可以看下。
http://element.eleme.io/#/zh-CN/component/table#pai-xu

**Comment by renxia** [comment]
@njleonzhang 
检查了一下，是设置了 loading 时会失效。示例如下：

http://jsfiddle.net/4r53b7kg/

@QingWei-Li 关那么早干嘛呢

**Comment by QingWei-Li** [comment]
@renxia 没有这样玩的，Table 里不建议嵌套其他内容
