### ISSUE TITLE
NavMenu: passing named route instead of path - is it possible?

### ISSUE THREAD

**Issue by pipejesus** [ElemeFE/element#2331]
### ElementUI version
1.0.3

### Vue version
latest 2.x

Is it possible to pass a 'named route' (of the vue-router) to the NavMenu? I can pass a simple path and it works. I tried passing an object such as {'name':'myNamedRoute'} but with no success. Thanks.

**Comment by pipejesus** [comment]
I'm sorry, i missed that :index is still required and used "route" instead of ":route", here it works:

```
        <el-menu class="el-menu-vertical-demo" theme="dark" :router="true">
          <el-menu-item index="1" :route="{name:'dashboard'}">Dashboard</el-menu-item>
          <el-menu-item index="2" :route="{name:'streams'}">Streams</el-menu-item>
        </el-menu>        
```

**Comment by michaelstrefeler** [comment]
@pipejesus Thank you so much for this solution

**Comment by buzzingcookie** [comment]
Hey, i just encountered this, problem and solved it thanks to your post. But here is the thing, i have the CONTENT and WEBSITE tab, if i refresh the WEBSITE page i still get like active tab the CONTENT one...did you encountered this also? I have everything like yourself with :router="true", i put :route="{ the named route }"....
