### ISSUE TITLE
el-input如何响应v-on:keyup.enter

### ISSUE THREAD

**Issue by cucr** [ElemeFE/element#2333]
vue支持如下写法<input @keyup.enter="submit">
但在
<el-input type="password" v-model="loginForm.password" auto-complete="off" placeholder="密码" @keyup.enter="submit“>是无效的
el-input是否可以提供该支持？

**Comment by baiyaaaaa** [comment]
@keyup.enter.native

**Comment by noprom** [comment]
@baiyaaaaa 
Cool! This works for me!

**Comment by maicss** [comment]
@baiyaaaaa 这个在文档的什么地方写的有? 我没找到, 谢谢

**Comment by Iamlars** [comment]
the better way to support enter to submit a form is set `native-type='submit'` on `el-button` component.

**Comment by thsdeveloper** [comment]
Muito bom isso funciona pra mim. valeu Galera! Viva a comunidade...
<el-input :placeholder="'Comente sobre isso...'" v-model="message" @keyup.enter.native="saveComment"></el-input>

**Comment by leaf-clover** [comment]
<el-input placeholder="请输入内容" v-model="input" clearable size="small" @keyup.enter.native="handleClick">
        </el-input>

Just like this,it's right!!!

**Comment by Eunknight** [comment]
> @baiyaaaaa 这个在文档的什么地方写的有? 我没找到, 谢谢
[Vue官方文档_从 Vue 1.x 迁移_用 v-on 监听原生事件 变更](https://cn.vuejs.org/v2/guide/migration.html#%E7%94%A8-v-on-%E7%9B%91%E5%90%AC%E5%8E%9F%E7%94%9F%E4%BA%8B%E4%BB%B6-%E5%8F%98%E6%9B%B4)

**Comment by WormGirl** [comment]
为什么我不可以，点击enter总是刷新页面，mac上，"element-ui": "^2.4.11","vue": "^2.5.17",

**Comment by LiMengyang990726** [comment]
I write `@keyup.native.enter`, however, it doesn't work as `submit` button did, it refreshes the whole page and didn't create any post request.

**Comment by rupid** [comment]
jsx 语法怎么写呢？

**Comment by polinwei** [comment]
你可以使用 @keypress.enter.native="submitForm('resetPasswordForm')" . Ref: https://polinwei.com/element-ui-prevent-form-submit/

**Comment by mayfly13** [comment]
> I write `@keyup.native.enter`, however, it doesn't work as `submit` button did, it refreshes the whole page and didn't create any post request.

you made a mistake.It shoule be @keyup.enter.native

**Comment by wh2017** [comment]
> @keyup.enter.native

**in JSX**

{...{
        nativeOn: {
              keyup: (e) => {
                     if (e.keyCode === 13) {}
              }
         }
}}
