### ISSUE TITLE
[navMenu 侧栏快速点击]

### ISSUE THREAD

**Issue by OMGVecchio** [ElemeFE/element#2334]
`navMenu` 侧栏模式，快速点击切换菜单项的伸缩之后，菜单项会保持展开状态？

**Comment by njleonzhang** [comment]
我之前想改来着，但是考虑table有[筛选](http://element.eleme.io/#/zh-CN/component/table#shai-xuan)的功能，所以也不太好直接设置th作为事件的触发元素。除非里面做个判断，在用户没有用筛选功能的时候，把事件绑到th上。

**Comment by Leopoldthecoder** [comment]
@njleonzhang 似乎应该回复在 #2324
