### ISSUE TITLE
Table的data中加了一条记录,然后直接current-row-key复制为该记录的Key值,不会选中

### ISSUE THREAD

**Issue by wenner** [ElemeFE/element#2336]
情景是 添加了一条记录 record , 成功后 Table的 data.push(record) , currentRowKey = record.key.

类似这样,可是却不能正常选中高亮
至少也要setTimeout(()=>{this.currentRowKey = record.key} , 0)才生效

请问,这是我使用的问题还是Vue自身机制的问题还是Table的问题呢?

**Comment by QingWei-Li** [comment]
换成 nextTick 就好理解了，因为 push 数据后 DOM 还未更新所以要 nextTick（或者 setimeout 0）
