### ISSUE TITLE
1.1.3版本, 表格组件在某些情况下, 边框会消失

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#2337]
系统MAC, Chrom 54

当表格里有某一列不设置宽度时, 该列之后的所有列, 边框将会出现消失情况...
不是每个表格都会这样, 但是确实会出现...
给`.el-table td, .el-table th`去除`position: relative;`后, 就正常了, 没找出具体原因...

<img width="1293" alt="qq20170111-0 2x" src="https://cloud.githubusercontent.com/assets/10840991/21836191/19bd6ff0-d7fe-11e6-88eb-3c6b37cf015c.png">
<img width="958" alt="qq20170111-1 2x" src="https://cloud.githubusercontent.com/assets/10840991/21836190/19bd4278-d7fe-11e6-9204-0d888b7dcd48.png">

有时也会出现这种情况:
![image](https://cloud.githubusercontent.com/assets/10840991/21836227/5d5d9a0a-d7fe-11e6-9cf5-1b8334f24166.png)

V1.1.2时, 是很正常的...

**Comment by QingWei-Li** [comment]
1.1.3 里并没有改 Table 的样式
![image](https://cloud.githubusercontent.com/assets/7565692/21838575/bcc9edc2-d80d-11e6-831b-f4c9150f09ab.png)

可否给个 demo？

**Comment by Leopoldthecoder** [comment]
感觉是 Chrome 的 bug。其他浏览器有问题吗？

**Comment by lincenying** [comment]
safari 测试是正常的, 可能的确是浏览器的问题, 先关了...

**Comment by jikkai** [comment]
@lincenying 

Chrome 54有很多bug，试试升到55或者Canary(57)看看还有没有这种幺蛾子问题🤣

**Comment by lincenying** [comment]
@jikkai 更新到55, 问题也消失了...看来的确是chrome 54的问题

不过看position: relative;这个样式好像也没啥用, 保险起见还是先改成static
