### ISSUE TITLE
form-item中的prop属性可以直接绑定v-model吗

### ISSUE THREAD

**Issue by beijiaxu** [ElemeFE/element#2338]
不设置prop属性，form.resetFields()就没效果，连着写2个属性感觉有点麻烦~
刚刚又看了下，组件里实现的resetFields()方法里的initialValue是在mounted是赋值的。
我现在是有个按钮点击后会弹出dialog，里面是form表单，2个input和1个tree。我用chrome的vue插件看了下，只有dialog第一次打开，form才会渲染。
如果我第一次打开是编辑按钮的话，mount的时候会调用编辑方法，把当前记录的值赋上去，然后initialValue从初始设置的空字符串变成该记录的值了，resetFields就没效果了。

还有个问题，dialog内的form下loading层浮动的位置有点不对
```
            <el-dialog title="角色管理" v-model="dialogFormVisible" custom-class="role_dialog" ref="dialog">
                <el-form :model="role_form" ref="role_form" v-loading.body="dialogLoading">
                    <el-form-item label="角色名称" prop="role_name">
                        <el-input v-model="role_form.role_name"></el-input>
                    </el-form-item>
                    <el-form-item prop="role_id" style="display: none;">
                        <el-input v-model="role_form.role_id"></el-input>
                    </el-form-item>
                    <el-form-item label="角色菜单" label-width="70px">
                        <el-tree>
                        </el-tree>
                    </el-form-item>
                </el-form>
                <div slot="footer" class="dialog-footer">
                </div>
            </el-dialog>
```
![qq 20170111153916](https://cloud.githubusercontent.com/assets/13776775/21839699/267627a8-d814-11e6-90c9-e6b2c318133d.png)

**Comment by beijiaxu** [comment]
都没人的吗？我提了几次问题都没个正面回复，随便说一句也行啊

我写了个demo，重置表单和loading的问题都在里面，麻烦看下啊
点重置text不重置，select能重置，loading的遮罩下移了，我的项目里是上移了
http://jsfiddle.net/hakLs9ud/

**Comment by Leopoldthecoder** [comment]
重置的问题可以把赋值放在 `nextTick` 里，Loading 的问题可以去掉 `body` 修饰符：http://jsfiddle.net/hakLs9ud/1/

**Comment by beijiaxu** [comment]
@Leopoldthecoder 搞定了，谢谢
