### ISSUE TITLE
bug table 多级标题 切换是 会导致的列不显示

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#2340]
ElementUI version：1.1.3
demo：http://jsrun.net/cPpKp/edit

请多点几次按钮，会出现bug
![image](https://cloud.githubusercontent.com/assets/3069732/21838799/2d82aa9e-d80f-11e6-9740-c0aed2ab05bb.png)
![image](https://cloud.githubusercontent.com/assets/3069732/21838801/34018c82-d80f-11e6-9b43-6a2827f890a8.png)

**Comment by QingWei-Li** [comment]
因为你写死宽度了，都是 180

**Comment by AaronChen2012** [comment]
跟宽度没有关系，我把宽度全去掉了，也不行！

**Comment by AaronChen2012** [comment]
点到最后 
![image](https://cloud.githubusercontent.com/assets/3069732/21840859/b8d87352-d81a-11e6-8ac3-136e23b4699e.png)

**Comment by njleonzhang** [comment]
@AaronChen2012 兼职测试专员啊。。。

**Comment by AaronChen2012** [comment]
没办法啊，项目在用啊

**Comment by QingWei-Li** [comment]
动态切换标题的功能目前没计划做，改动挺大
