### ISSUE TITLE
el-checkbox 点击无反应

### ISSUE THREAD

**Issue by fengxinming** [ElemeFE/element#2342]
vue 版本2.1.6
vuex 版本2.1.1
element-ui 版本1.1.3

用法：在app.js中
import ElementUI from 'element-ui';
Vue.use(ElementUI);

在vue文件
el-checkbox(v-model="checked", checked) 备选项

我用的是pug模板，但是应该不影响

**Comment by baiyaaaaa** [comment]
检查一下绑定值是否 non-reactive ?

**Comment by fengxinming** [comment]
@reverland 还是不行哦

**Comment by fengxinming** [comment]
@baiyaaaaa 在项目里面不好提供代码，但是用法跟官网写的事例一样，在data里面定义属性，然后v-model绑定哦

**Comment by baiyaaaaa** [comment]
@fengxinming 这样的话我们很难确认是否有问题😑，可以在jsfiddler上复现的话最好了
