### ISSUE TITLE
el-upload是否可以自定义是要img标签还是设置div的background图片

### ISSUE THREAD

**Issue by tchaoo** [ElemeFE/element#2344]
用法：在thumbnail-mode图片上传成功之后现在是直接显示img标签；由于图片可能是横长方形、有时候时候是竖长方形，图片很容易变形
建议：将img显示图片那里再加个div的background背景显示；让用户可以自己选择是用img标签还是background

**Comment by baiyaaaaa** [comment]
基于样式的 api 太臃肿了，一般都不会被考虑进组件里，你可以拿到在上传返回的 url 来实现你的需求

**Comment by tchaoo** [comment]
O(∩_∩)O好的 谢谢
