### ISSUE TITLE
使用element-ui 1.0.9,el-dorpdown和el-datepicker报属性重复错误

### ISSUE THREAD

**Issue by wangyahui6** [ElemeFE/element#2346]
使用element-ui 1.0.9,el-dorpdown和el-datepicker报类似的错误，如下：
[Vue warn]: existing instance property "placement" will be overwritten by a computed property with the same name. 
(found in component <ElDropdownMenu>)

[Vue warn]: existing instance property "haveTrigger" will be overwritten by a computed property with the same name. 
(found in component <ElDatePicker>)

**Comment by QingWei-Li** [comment]
1.0.9 不兼容最新版的 Vue，应该是 2.1.5，因为之后的版本会检查重复的属性
