### ISSUE TITLE
能否增加 Sidenav 组件？

### ISSUE THREAD

**Issue by sjm44** [ElemeFE/element#2349]
能否考虑增加 Sidenav 组件？类似[这样](http://materializecss.com/side-nav.html)。

**Comment by reverland** [comment]
这不是navMenu么

**Comment by baiyaaaaa** [comment]
navMenu ？

**Comment by sjm44** [comment]
并不太一样，navMenu主要是菜单导航用。而Sidenav内可以自己添加其它各类信息内容，更多的是作为一种详细信息的展示。可能Sidenav这个名字容易引起误会，被认为只能做导航用。

借用一下worktile的例子，下图中点击具体任务，弹出最右侧的边栏，展示详细内容和操作。

![huaban](https://cloud.githubusercontent.com/assets/4596552/21880436/f69b5956-d8d9-11e6-8625-4bfb7f6e084e.png)

**Comment by colinshen** [comment]
我也需要。不过应该简单的改一下navMenu吧

**Comment by sjm44** [comment]
https://chenz24.github.io/vue-blu/#/components/aside，找到了一个更贴切的例子，不知能否考虑一下？谢谢。
