### ISSUE TITLE
如何引用 Element 默认配色的变量

### ISSUE THREAD

**Issue by Kaijun** [ElemeFE/element#2351]
之前是查到element的默认颜色然后css里写死，后来升级element发现配色会随着版本的变化发生微调。

所以想问下有没有什么比较优雅的办法引用 Element 默认配色的变量？

一定需要使用 element-theme 吗？

**Comment by jikkai** [comment]
是的

**Comment by reverland** [comment]
配色有微调？rebase了这么多次也没看到哪里配色有调。。。

**Comment by reverland** [comment]
记得gitter上@QingWei-Li 认为覆盖是比较好的自定义方式。

但是，作为一个fork了element-theme做了一定魔改的表示，fork再搭配私有npm registry食用也是不错的选择。。。

**Comment by jikkai** [comment]
@reverland 指的应该不是配色本身微调，而是dom嵌套层级改变导致原来覆写的css选择器和新版本element不一致吧。

element-theme其实就是这种类似的问题的解决方案，所以直接用就行了。

当然像@reverland 这样fork自行定制一个也可以，就是会增加一点维护成本😑
