### ISSUE TITLE
firstDayOfWeek: 1 在选择日期范围时不起效果

### ISSUE THREAD

**Issue by changjunhao** [ElemeFE/element#2353]
### ElementUI version
1.1.3

### OS/Browers version
macOS/Chrome 55

### Vue version
2.1.8

**Comment by QingWei-Li** [comment]
http://jsfiddle.net/6y48qg8c/

**Comment by changjunhao** [comment]
<template>
    <el-date-picker v-model="value2" type="daterange" :picker-options="pickerOptions1">
    </el-date-picker>
</template>

**Comment by changjunhao** [comment]
当type="daterange"时

**Comment by frankleja** [comment]
I'm new in Vue and impressed of ElementUI - great work!
![datepicker-daterange-wrong-marks](https://cloud.githubusercontent.com/assets/5411592/22330092/bd4a2060-e3c4-11e6-9cee-f80ce7dde6ef.PNG)

I use a date-picker with firstDayOfWeek: 1 and experience the correct dates shown in input field, but the blue marks in popup window itself is not aware of it. When I click on start date, the next day is marked blue - similar issue with end date. This mark behavior feels strange and there is a mismatch now between text in input field and the blue marked date range in popup.
Is there a chance to improve this fix to a full awareness of firstDayOfWeek.
