### ISSUE TITLE
[el-progress]绑定的是数字，但是老报错，请问是什么原因？

### ISSUE THREAD

**Issue by zh870717** [ElemeFE/element#2360]
![image](https://cloud.githubusercontent.com/assets/14067791/21875799/9706d4a4-d8b9-11e6-850b-91d15b92c9b7.png)
![image](https://cloud.githubusercontent.com/assets/14067791/21875804/a050d08c-d8b9-11e6-9750-a7a1cd1f3c7d.png)
![image](https://cloud.githubusercontent.com/assets/14067791/21875812/a7f5c644-d8b9-11e6-882e-ae758de07889.png)

**Comment by lincenying** [comment]
错误已经写的很清楚了.  percentage需要传入数值型, 但是你传的是字符型

注意 var a = "1"  和 var a = 1 是不同的.

简单的改法就是 :percentage="+revenuePercent"

**Comment by zh870717** [comment]
好的，感谢，解决了！typeof检测的时候是number类型，但是不知道为什么老说我绑的字符串
