### ISSUE TITLE
日期选择器，时间长度限制

### ISSUE THREAD

**Issue by lixingdecai** [ElemeFE/element#2361]
### ElementUI version
1.1.3

### OS/Browers version
macOS/Chrome 55

### Vue version
2.0

### Reproduction Link

无
### Steps to reproduce
无
### What is Expected?
日期选择器：比如我需求是 时间长度范围是小于31天，在我选择了开始日期后，是否能自动做UI层面的控制，禁止选择超过时间长度31天的日期
### What is actually happening?
目前是没有做时间控制的

**Comment by jikkai** [comment]
http://element.eleme.io/#/zh-CN/component/date-picker#picker-options
`disabledDate`里做下判断就行了

**Comment by lixingdecai** [comment]
disabledDate：设置禁用状态，参数为当前日期，要求返回 Boolean。这个方法我看的不是很明白，有具体使用例子么

**Comment by QingWei-Li** [comment]
http://jsfiddle.net/wbnxeoj2/

**Comment by WLyKan** [comment]
@QingWei-Li  这个可以在demo文档里加一个么

**Comment by ijandc** [comment]
@QingWei-Li 这个选项并不能限制时间选择跨度吧？只是显示可以在哪个范围选择的，比如说，限制用户只能选择1月5号到1月21号之间的日期，可以用这个，但是如果想限制用户只能选择10天的日期，随便选择10天，这个并不好使啊

**Comment by ghostcode** [comment]
@ijandc 本来想的是 pickerOptions 里的 disabledDate 和 onPick 配合可以实现，但是第一次选择日期可以限制时间跨度，再选择 onPick 就不触发 disabledDate 了

**Comment by ghostcode** [comment]
@ijandc 我实现了一个，你看看是否满足：示例 https://codepen.io/ghostcode/pen/rNxvdzm  ，相关文章：https://mp.weixin.qq.com/s?__biz=MzA5MDIyNTM3Mw==&mid=2666577475&idx=1&sn=3f9c15979222e7caedc1926cbb5a055f&chksm=8b0af1f1bc7d78e757fb1268259217c45b4d02d187913d0da1b14a80c68994eb0387b1be0ccd&token=1538071566&lang=zh_CN#rd
