### ISSUE TITLE
时间控件，时间样式有问题

### ISSUE THREAD

**Issue by justin107** [ElemeFE/element#2362]
http://element.eleme.io/#/zh-CN/component/datetime-picker
官网地址
选择时间的时候，数字未与：对齐，偏下了

**Comment by QingWei-Li** [comment]
macOS Chrome/Safari 正常

**Comment by jikkai** [comment]
![image](https://cloud.githubusercontent.com/assets/14025786/21880202/917da4b2-d8d8-11e6-8e10-79ac7141c127.png)

说的是这个现象吗？

**Comment by justin107** [comment]
是的，未对齐，错位很明显

**Comment by justin107** [comment]
win10 chrome 54，官网访问

**Comment by jikkai** [comment]
#2071

**Comment by Leopoldthecoder** [comment]
Duplicate. See #2071 for updates.
