### ISSUE TITLE
checkout多选框，可以用button去展示么？目前单选框是可以支持的

### ISSUE THREAD

**Issue by zhoujiamin** [ElemeFE/element#2363]
### ElementUI version

"element-ui": "1.0.6",
### OS/Browers version

Chrome 55
### Vue version

vue": "2.1.4",
### What is Expected?
希望以button的方式支持多选框。

**Comment by baiyaaaaa** [comment]
考虑到这个组件的实用性和使用场景都比较低，暂时不会有这个计划
