### ISSUE TITLE
el-table-column 里面嵌套 switch  和vuex冲突

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#2364]
![qq 20170112133724](https://cloud.githubusercontent.com/assets/16487810/21878290/3d064314-d8cc-11e6-8305-d45f828e065b.png)
![qq 20170112133734](https://cloud.githubusercontent.com/assets/16487810/21878291/3d4ba508-d8cc-11e6-8f5b-3beaa76c22f3.png)
如果表格里面的data是写死的，不会报错，但是如果我通过vuex方法获得一个值设置，如图
![qq 20170112133740](https://cloud.githubusercontent.com/assets/16487810/21878319/6e152e98-d8cc-11e6-8f7f-2560af4ceacf.png)
这样做，直接报下图错误
![qq 20170112133745](https://cloud.githubusercontent.com/assets/16487810/21878327/78d7dbaa-d8cc-11e6-9436-c0760f8827c3.png)
直接去找state里面的值去改了

**Comment by lincenying** [comment]
你直接用vuex的数据去做双向绑定能不出问题吗...这和element没有关系, 你就是直接绑在input上面, 也要报错

**Comment by killdada** [comment]
我在倒数第二张图上在方法里面已经尝试吧data赋值到局部的data里面，然后测试还是报错，
![qq 20170112173744](https://cloud.githubusercontent.com/assets/16487810/21884400/1da62e90-d8ee-11e6-9cfb-b5a7ca191cfc.png)
![qq 20170112173815](https://cloud.githubusercontent.com/assets/16487810/21884401/1dce321e-d8ee-11e6-9091-45f68366a257.png)
重新测试你说的这个问题，在回调里面我设置了一个局部的data 然后双向绑定到input没问题，
但你看我下面那句的尝试还是会出错的

**Comment by killdada** [comment]
测试name的双向绑定没问题，测试下面那行注释的customFieldsData有问题，，

**Comment by killdada** [comment]
也就是说我有尝试放到局部变量里面，没有用el-table-column和switch的测试通过，用了之后失败

**Comment by killdada** [comment]
我再测试了另外一种情况，直接使用switch，如图

![Uploading QQ图片20170112175106.png…]()
这也是没有报错的，但是如果嵌套了表格就报错了，
