### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by manyin** [ElemeFE/element#2368]
> cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8086

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 2.6.32-431.11.22.el6.ucloud.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! element-starter@ dev: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8086`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the element-starter@ dev script 'cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8086'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the element-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8086
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls element-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wwwroot/zuju.la/ui/npm-debug.log

**Comment by manyin** [comment]
不好意思，我是一个后端工程师，现在需要搞一下前端，安装运行的时候出现上面的问题，有人能帮助我吗
我是在centos上搭建我的开发环境。

**Comment by QingWei-Li** [comment]
1. 请不要滥用 Issue，只能提交 Bug 和 Feature，具体参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)
