### ISSUE TITLE
<el-input> keyup and other events

### ISSUE THREAD

**Issue by xiaofan2406** [ElemeFE/element#237]
### ElementUI version
 1.0.0-rc.2 

### Vue version
2.0.1 

How do I get events like `@keyup.enter` to work with `el-input`. It doesn't looks like the events are passed to the `input` element

**Comment by Leopoldthecoder** [comment]
Use `@keyup.native.enter`. It's Vue 2.0 syntax: https://github.com/vuejs/vue/issues/2873#issuecomment-239750394
