### ISSUE TITLE
Upload插件上传会触发两次

### ISSUE THREAD

**Issue by arzcl** [ElemeFE/element#2370]
Upload插件上传会触发两次，第一次传递控制，第二次才会上传数据

**Comment by jikkai** [comment]
OPTIONS预请求？这个不是element的问题，甚至都不是问题……

**Comment by arzcl** [comment]
抱歉，是我没认真看http信息，的确是OPTIONS嗅探...

**Comment by helei2015** [comment]
今天和后台对接，由于element UI上传组件的两次操作问题，导致后台文件服务器直接居然了文件上传！
