### ISSUE TITLE
breadcrumb在控制台出现未定义的push错误

### ISSUE THREAD

**Issue by jiajia-huo** [ElemeFE/element#2375]
index.js:8 Uncaught TypeError: Cannot read property 'push' of undefined
    at HTMLSpanElement.<anonymous> (index.js:8)

**Comment by baiyaaaaa** [comment]
请提供demo

**Comment by jiajia-huo** [comment]
http://element.eleme.io/#/zh-CN/component/breadcrumb     的在线运行    F12打开控制台 点击带有path路径的“首页“   就可以看到错误

**Comment by baiyaaaaa** [comment]
没有看到错误。。。你再确定一下

**Comment by jiajia-huo** [comment]
你邮件是什么  我可以给你发截图   这里没法截图啊

**Comment by jikkai** [comment]
@jiajia-huo 截图解决不了问题，还是提供个浏览器和系统版本以及可复现的demo吧

**Comment by jiajia-huo** [comment]
给baiyyaaaa发gamail邮件了 ，我不知道你说的demo是啥，  还是你没看我的问题 。自己文档的在线运行出现控制台错误，还需要我提供demo？那你能告诉我，我怎么提供demo？
@jikkai

**Comment by baiyaaaaa** [comment]
你直接在这里的输入框里control + v 就可以发截图了

**Comment by jikkai** [comment]
@jiajia-huo

我这边官网文档看下来也是没啥问题的。之所以希望提供一下浏览器版本和系统版本和demo，是为了更快定位问题和解决问题，并不是说我没有看你的提问

PS：github可以直接发截图的

**Comment by jiajia-huo** [comment]
![image](https://cloud.githubusercontent.com/assets/10204631/21928767/a5fadfbe-d9c7-11e6-946c-d6d0b4e8c304.png)

版本 55.0.2883.87 m (64-bit)

**Comment by baiyaaaaa** [comment]
@jiajia-huo 使用 `route` 属性需要在你的项目里使用了 `vue-router` 插件，你的例子里没有使用`vue-router`  所以报错了

**Comment by jiajia-huo** [comment]
这不是我的项目

**Comment by jiajia-huo** [comment]
![image](https://cloud.githubusercontent.com/assets/10204631/21929364/0e974c9e-d9cb-11e6-9899-44f0c200078d.png)
@baiyaaaaa   您很自信啊   这么就给关闭了，是对自己的项目很有信心吗

**Comment by jiajia-huo** [comment]
垃圾

**Comment by jiajia-huo** [comment]
@baiyaaaaa  垃圾
