### ISSUE TITLE
1.1.3版本 upload组件是否已经支持ie9 ？

### ISSUE THREAD

**Issue by xiangwenbin** [ElemeFE/element#2377]
### ElementUI version

1.1.3
### OS/Browers version

ie9 (兼容模式)
### Vue version

2.1.8
### Reproduction Link

http://element.eleme.io/#/zh-CN/component/upload

### Steps to reproduce
在官方例子http://element.eleme.io/#/zh-CN/component/upload  下，使用ie9上传文件会报错，（看了upload源码，应该是加了ie9的支持，但实际还是有问题，请问，该版本是否已经支持，还是在支持计划中？）
### What is actually  @happening?
SCRIPT5007: 无法获取未定义或 null 引用的属性“0”
element-ui.cd5c4ed.js (10,27018

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/1132 重复了
