### ISSUE TITLE
no-static-element-interactions

### ISSUE THREAD

**Issue by hans-lizihan** [ElemeFE/element#238]
同事发现 element 库有很多 `@click` 是直接绑定在 `<li>` `<i>` 等等 element 上面的。

参考这条 react-a11y 的 eslint rule 所有的 event listener 应该绑定在 `<a>` `<button>` 等等 应该用于交互的元素上面。

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md

**Comment by furybean** [comment]
15 天没有反馈的 discussion 给予关闭处理，如果有人需要讨论，可以 open。
