### ISSUE TITLE
横纵导航栏同时存在时候的bug

### ISSUE THREAD

**Issue by cenkai88** [ElemeFE/element#2385]
### ElementUI version
v1.1.3

### OS/Browers version
macOS

### Vue version
2.1.6

当横纵导航栏同时存在，且控制一个路由时，在从横的切换到纵的时候，两个组件defaultActive属性变化都正确，但是横导航栏的样式没有正确切换，原来is-active的li仍然保持is-active。

**Comment by baiyaaaaa** [comment]
看不太懂。。提供一下demo把
