### ISSUE TITLE
按需引入 select 选择器显示不出options数据或显示无数据，全部引入时则正常

### ISSUE THREAD

**Issue by bigggge** [ElemeFE/element#2386]
### ElementUI version
1.1.3

### OS/Browers version
 macOS/Chrome 55 

### Vue version
2.1.0

### Steps to reproduce
```
import {Select} from "element-ui";
Vue.use(Select)
```
### What is actually happening?

按需引入 select 选择器显示不出options数据或显示无数据，全部引入时则正常

**Comment by Leopoldthecoder** [comment]
Pagination?

**Comment by bigggge** [comment]
是Select 上面写错了

**Comment by Leopoldthecoder** [comment]
还需要引入 Option：
```javascript
import { Select, Option } from 'element-ui'
Vue.use(Select)
Vue.use(Option)
```
