### ISSUE TITLE
Module not found: Error: Cannot resolve module 错误

### ISSUE THREAD

**Issue by quqiufeng** [ElemeFE/element#239]
代码是最新版
以 examples 文件夹为蓝本
alias 配置为
项目文件夹下 cooking.conf.js 中 alias 配置为:
alias:{
      src   : path.join(__dirname, 'src'),
      main: path.join(__dirname, 'main')
  }

 my-project 为项目文件夹
 
 my-project\src\icon.json
 my-project\src\dom\class.js
 my-project\main\utils\date.js
 这三个文件是存在的
 
docs 文件夹中

my-project\src\docs\zh-cn\home.md
`<script></script>` 标签中
import { addClass } from 'src/dom/class.js';  //报错

my-project\src\docs\zh-cn\card.md
`<script></script>` 标签中
import dateUtil from 'main/utils/date'         //报错

my-project\src\docs\zh-cn\icon.md
`<script></script>` 标签中
var iconList = require('src/icon.json');         //报错

错误为  Module not found: Error: Cannot resolve module

应该怎么样设置  alias  还是 import 的时候使用相对路径

我已经把examples文件夹独立出来了 这个问题解决了  就可以作为element demo项目给新人参考

**Comment by QingWei-Li** [comment]
example 的 配置文件是 cooking.demo.js

**Comment by quqiufeng** [comment]
嗯  我挪过来了

**Comment by QingWei-Li** [comment]
看起来你这路径没配置对呀，如果 main 和 src 同级的话为啥找 dom 的是 `../` 而找 utils 就变成了 `../../main`

应该是你想对路径没配置对的问题

**Comment by quqiufeng** [comment]
my-project\src\icon.json
my-project\src\dom\class.js
my-project\main\utils\date.js
这三个文件是存在的

main 文件夹 和src 同级
dom 文件夹  在src 文件夹下

**Comment by quqiufeng** [comment]
https://github.com/quqiufeng/element_example  我把examples 剥离出来了  
这个路径问题还是没解决  我暂时用相对路径了

**Comment by QingWei-Li** [comment]
你的 main 是在 src 里的吧？我这边改了后启动正常。
还有 autoprefixer 不需要引入，postcss-salad 已经包含了、cooking-vue 和 cooking-vue2 重复了，只需要安装 vue2

**Comment by quqiufeng** [comment]
谢谢  所有问题都解决了  
感谢各位贡献这么好的项目!
https://github.com/quqiufeng/element_example
