### ISSUE TITLE
nav-menu和vue-router配合使用逻辑上有问题

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#2391]
vue-router针对每个路由都有 `beforeEnter: (to, from, next)` 钩子，如果在这个钩子中不执行 `next()` 则当前路由不会跳转。

`el-menu` 这样配置 `<el-menu :default-active="$route.path" mode="horizontal" :router="true">`

当点击其中一个路由的时候，在 `menu.vue` 的函数 `handleItemClick(item)`中，直接指定了 `this.activedIndex = item.index;`，也就是说，就算启用了 `router` ，仍旧以 `click` 事件为准来改变 `activedIndex `，这就导致了，url没有变，但是nav-menu的选中项变了

**Comment by reverland** [comment]
前一阵阻止路由变化时，发现高亮已经变了就觉得不太对劲。。

**Comment by baiyaaaaa** [comment]
fixed #2399
