### ISSUE TITLE
写在 .vue 中 style 标签中的样式会被覆盖

### ISSUE THREAD

**Issue by zcdll** [ElemeFE/element#2393]
### ElementUI version
1.1.2

### OS/Browers version
Ubuntu Chrome 55.0.2883.87 (64-bit)

### Vue version
2.1.0

写在 .vue 中 style 标签中的样式会被覆盖，只能加 !important 使之生效。

```
<div>
<el-button type="primary" class="submitBtn" @click="submitState">确认</el-button>
</div>

<style>
  .submitBtn{
    float: right;
    margin-right: 200px;
  }
</style>
```

**Comment by QingWei-Li** [comment]
引入样式顺序的问题，确保 Element 的主题文件是在你的组件引入之前加载的

**Comment by zcdll** [comment]
OK，搞定了，谢谢！
