### ISSUE TITLE
timepicker点击不滚动了

### ISSUE THREAD

**Issue by luxueyan** [ElemeFE/element#2397]
### ElementUI version
 1.1.3 

### OS/Browers version
macOS/Chrome/55.0.2883.95

### Vue version
2.1.1 

### What is Expected?
time picker 选择了时间 滚动到正确位置
### What is actually happening?
time picker 选择了时间 不滚动

![image](https://cloud.githubusercontent.com/assets/1555552/21924958/44a48adc-d9b6-11e6-8a37-19a57f030b19.png)

**Comment by QingWei-Li** [comment]
![kapture 2017-01-13 at 17 33 36](https://cloud.githubusercontent.com/assets/7565692/21925000/6f0e80de-d9b6-11e6-8396-e1b75057e932.gif)

**Comment by jikkai** [comment]
碰到过类似情况，说的大概是说类似的这种情况不能选0？
https://codepen.io/jikkai/pen/bgewEW/

---

试了下改成这样好像可以解决
[`time-spinner.vue`](https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/basic/time-spinner.vue#L131-L134)
```javascript
hoursPrivate: '0',
minutesPrivate: '0',
secondsPrivate: '0',
```
或者
```javascript
this[type + 'Private'] = String(value.value >= 0 ? value.value : value);
```

**Comment by luxueyan** [comment]
@jikkai 我是照着demo写的 不止是0点不了，所有的都点不了，时间变了，但是不滚动

**Comment by luxueyan** [comment]
@QingWei-Li  这个文档截图有什么意义吗 我就是按照他写的 只是改了一点颜色值
从1.0版本升级到1.1.3 直接就是这样子了

**Comment by jikkai** [comment]
@luxueyan Vue的版本有更新吗？

**Comment by luxueyan** [comment]
@jikkai  没更新 就更新了 element-ui

**Comment by luxueyan** [comment]
vue 更新到了 2.1.8 也还是这样子 摸不着头脑

**Comment by jikkai** [comment]
element1.1.0之后的版本最低兼容到Vue 2.1.6

**Comment by jikkai** [comment]
那这个可能不是element本身的问题了，给个可复现的demo或者到gitter上 问问吧，估计是用法上有点问题？

@QingWei-Li 那啥，李老师帮忙看下我前面发的那个demo😂

**Comment by luxueyan** [comment]
我用 yarn upgrade 所有 现在这样子了 跑不起来了
![image](https://cloud.githubusercontent.com/assets/1555552/21929320/d8e60b3a-d9ca-11e6-9650-57e162e81842.png)
