### ISSUE TITLE
tree组件快速多次点击后，节点关闭了，子节点还是显示出来了

### ISSUE THREAD

**Issue by yunfeit** [ElemeFE/element#2398]
### Steps to reproduce
tree组件快速多次点击后，节点关闭了，子节点还是显示出来了

**Comment by Kingwl** [comment]
确实 已复现

**Comment by Kingwl** [comment]
http://jsfiddle.net/cc4hjo3d/4/

**Comment by baiyaaaaa** [comment]
#2354 修复了这个bug，可以到dev网站测试下 https://elementui.github.io/dev/1.1/#/zh-CN/component/tree
