### ISSUE TITLE
menu启用router，menue-item的激活状态混乱

### ISSUE THREAD

**Issue by ericwang1902** [ElemeFE/element#2407]
![image](https://cloud.githubusercontent.com/assets/7867163/21953342/15e97176-da6f-11e6-9607-cbe591223901.png)
当我点击“添加菜单”的时候，item高亮还是显示在“修改菜单”上。
下面是我的代码：
![image](https://cloud.githubusercontent.com/assets/7867163/21953345/3c7f649e-da6f-11e6-9e69-0afc175fed04.png)

**Comment by reverland** [comment]
index在路由模式下难道不是路径？

**Comment by ericwang1902** [comment]
不是路径，路径是在route属性里的vue-router对象。

**Comment by languanghao** [comment]
目前，你可以采用这个临时解决方案https://github.com/ElemeFE/element/issues/2391

然后，https://github.com/ElemeFE/element/pull/2399 更完善的PR已经接受了，等下个版本吧

**Comment by baiyaaaaa** [comment]
等新版本把

**Comment by ericwang1902** [comment]
ok，我用结合vue－router的方式实现了。谢谢回复。
