### ISSUE TITLE
Time-picker default format not working

### ISSUE THREAD

**Issue by afucher** [ElemeFE/element#2416]
### ElementUI version
1.1.3

### OS/Browers version
Linux Mint/Chrome 55

### Vue version
2.0.7

### Reproduction Link
https://codepen.io/afucher/pen/qRaELB

### Steps to reproduce
Open the time-picker, select a time and see the value in the input.
### What is Expected?
Default format is HH:mm:ss, so I expected that the value has the seconds value.
### What is actually happening?
Actually he brings just hour and minute value

**Comment by QingWei-Li** [comment]
`TimeSelect` does not have the `format` property.

**Comment by afucher** [comment]
But the [doc](http://element.eleme.io/#/en-US/component/time-picker#attributes) says that it has.

**Comment by QingWei-Li** [comment]
Sorry, The document is incorrect. I will fix it.
