### ISSUE TITLE
按钮组结合Tooltip使用时，按钮组中按钮的样式错乱

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#2423]
### ElementUI version

1.1.3
### Vue version

2.1.8
### Code
```html
<el-button-group class="operation-btn">
  <el-tooltip content="编辑" placement="top">
    <el-button icon="edit" @click="handleEdit"></el-button>
  </el-tooltip>
  <el-tooltip content="编辑" placement="top">
    <el-button icon="setting" @click="handleSetting"></el-button>
  </el-tooltip>
  <el-tooltip content="编辑" placement="top">
    <el-button icon="delete" @click="handleDelete"></el-button>
  </el-tooltip>
</el-button-group>
```
### Steps to reproduce
按钮组结合Tooltip使用时，按钮组中按钮的样式错乱

**Comment by QingWei-Li** [comment]
http://jsfiddle.net/tu63krok/
![image](https://cloud.githubusercontent.com/assets/7565692/21969221/7947d3ca-dbd7-11e6-871c-b06c11001256.png)

正常

**Comment by EdenSpark** [comment]
![image](https://cloud.githubusercontent.com/assets/9413415/21973803/26558e06-dbfe-11e6-9566-d541fb9bef3d.png)
@QingWei-Li 多谢回复:-D 我是指这种按钮组的样式没有了

**Comment by QingWei-Li** [comment]
这样的话目前没办法让 buttonGroup 和 tooltip 结合使用，我重写下 tooltip，放在 1.2 里
