### ISSUE TITLE
InputNumber 计数器 Bug

### ISSUE THREAD

**Issue by yuxiaoqi-seven** [ElemeFE/element#2426]
Version 1.1.3
issue：
1.初始状态下，点击 + 数字无反应
2.手动更改 输入框值之后，点击 +功能恢复 ,但是出现了数值一直在增加

**Comment by baiyaaaaa** [comment]
线上文档没有复现你的问题，请提供demo

**Comment by yuxiaoqi-seven** [comment]
线上文档 没有问题 ，我先看看是不是自己的环境问题

**Comment by Kingwl** [comment]
这bug我记得已经改了

**Comment by yuxiaoqi-seven** [comment]
线上文档 点出bug了  数字一直增加
你们这样操作试试:
1.去除最大值设置
2.左击 + 按住不放，移动到其他地方 或者鼠标转两圈，就会发现问题了

**Comment by baiyaaaaa** [comment]
我测试了一下发现没有这个问题 @yuxiaoqi-seven 是稳定复现的吗

**Comment by yuxiaoqi-seven** [comment]
不是  偶尔出现的 但是多试几次就会出现

**Comment by yuxiaoqi-seven** [comment]
这边问题解决了  v-model 换了个名字

**Comment by yuxiaoqi-seven** [comment]
Thanks

**Comment by SunYuqing** [comment]
我也遇到了这个问题，请问是怎么解决的呢
