### ISSUE TITLE
Tabel设置了default-sort-prop后，第一次加载并没有按照该属性对数据进行排序

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#2427]
### Steps to reproduce

官网例子：http://jsfiddle.net/api/post/library/pure/

### What is Expected?

当设置 `default-sort-prop` 或 `default-sort-order` 后，第一次数据加载前，应该按照该字段对数据进行排序。

### What is actually happening?

当前会出现默认排序列的排序按钮状态变了，但是其实数据并没有排序

**Comment by njleonzhang** [comment]
@languanghao 请用1.1.4试试，注意api有所调整，另外你的repro地址打不开。

**Comment by languanghao** [comment]
@njleonzhang ok，新版本没问题了，那个链接我贴错了，其实就是官网的Table的排序，本身就有问题

这个可以关了

**Comment by njleonzhang** [comment]
@languanghao 那你就关了吧 :)

**Comment by languanghao** [comment]
@njleonzhang 这个我自己可以关的吗，怎么弄

**Comment by njleonzhang** [comment]
啊   你没有close的button么  那算了。
