### ISSUE TITLE
tree ：data值是动态获得，则渲染失败

### ISSUE THREAD

**Issue by weiluxia1988** [ElemeFE/element#243]
<el-tree :data="data" :props="defaultProps"></el-tree>
如果data是动态获得的，不能动态渲染

**Comment by qiaocuixinzhiweini** [comment]
遇到了同样的问题，data通过网络请求回来，赋值后视图没有更新

**Comment by weiluxia1988** [comment]
提供了load方法可以动态数据，但是希望可以通过改变data能直接响应

**Comment by qiaocuixinzhiweini** [comment]
每个节点前希望能够添加一个图标，节点后能够添加操作按钮
