### ISSUE TITLE
select 回填数据

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2433]
在做后台项目时回填数据是一个很常规的需求，
现在有一个select下拉框，如[demo](http://jsfiddle.net/vcgftLvn/18/)

现在我在edit页面想回填之前的结果，该如何是好？在不改变传输结构的情况下。
如[demo](http://jsfiddle.net/vcgftLvn/17/)

**Comment by jikkai** [comment]
v-model赋值为之前选择的内容就可以了。

这个问题不属于element的问题，如果只是寻求使用上的帮助可以到gitter、segmentfault之类的社区提问……

**Comment by PanJiaChen** [comment]
已解决[demo](http://jsfiddle.net/vcgftLvn/19/)
