### ISSUE TITLE
Tree组件，在连续多次点击父节点后，子节点一直显示，无法收起

### ISSUE THREAD

**Issue by scaleryvan** [ElemeFE/element#2436]
### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/tree ，官方示例即可复现bug
### What is Expected?
应保持正常的收起展开
### What is actually happening?
连续多次点击父节点后，子节点一直显示，有收起动作，但立即又展开了

**Comment by Leopoldthecoder** [comment]
已在 #2354 修复。
