### ISSUE TITLE
Dialog BUG，弹框内再点弹框,样式错误。

### ISSUE THREAD

**Issue by zhongmengyuan** [ElemeFE/element#2437]
1.弹框内二级弹框不应该指定一级弹框（当前弹框）为window对象，因为如果二级弹框比一级弹框大，页面将其丑无比，弹框无法使用
2.弹框是否显示（isShow），应该使用v-if 绑定，而不是用过v-show 绑定；因为弹框打开时大多情况需要传入数据再mount

**Comment by Leopoldthecoder** [comment]
1. 不要嵌套使用 Dialog
2. Dialog 的 body 是通过 v-if 控制的。

**Comment by zhongmengyuan** [comment]
1.因为不能嵌套使用Dialog，所以我们只能采用事件驱动的方式打开弹框，但是个人觉得体验不是太好，做得更好一点应该是支持Dialog嵌套的毕竟这是一个很常用的功能。
    2.  您把这个代码拷到你们的dialog里面运行一下，你会发现点击关闭上一层Dialog之后，下一层Dialog的遮罩层就没了。这里你可能会有一个疑问为什么要在弹框外面加一层v-if 呢？因为很多场景下，有的弹框会被很多地方用到，所以就需要把它做成一个组件，使用的时候直接import进来就行了 ，而且每次打开都希望重新执行mounted（初始化发送），所以要使用v-if。

**综上，你们的bug是：二层弹框如果直接通过v-if=“false”销毁后，直接把遮罩层清除了（然而你们的遮罩层是单例的），所以另外一个弹框的遮罩层也没了`**
` <script src="//unpkg.com/vue/dist/vue.js"></script>
 <script src="//unpkg.com/element-ui/lib/index.js"></script>
  <div id="app">
    <el-button type="text" @click="dialogVisible1 = true;dialogVisible2= true;">点击打开 Dialog
    </el-button>
    <div v-if="dialogVisible1==true">
        <el-dialog title="提示" v-model="dialogVisible1" size="small">
            <span>这是一段信息</span>
            <span slot="footer" class="dialog-footer">
                <el-button @click="dialogVisible = false">取 消</el-button>
                <el-button type="primary" @click="dialogVisible2 = true">确 定</el-button>
            </span>
        </el-dialog>
    </div>
</div>
var Main = {
    data() {
        return {
            dialogVisible1: false,
            dialogVisible2: false,
        };
    }
};
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')`

**Comment by Leopoldthecoder** [comment]
你的代码中并没有两个 Dialog。

「不要嵌套使用 Dialog」并不是说页面上不能同时存在多个 Dialog，只是它们在模板中的层级关系不要嵌套而已：http://jsfiddle.net/o8t21h4u/

**Comment by zhongmengyuan** [comment]
直接上代码：刚才代码拷贝的时候出错了，你直接 ：
[http://jsfiddle.net/o8t21h4u/2/](url)

**Comment by zhongmengyuan** [comment]
链接点击跳转不过去，你把链接拷到浏览器打开就行了

**Comment by yuxiaoqi-seven** [comment]
问题的原因是产生遮罩的位置，遮罩是产生在dialog节点 同级的下一个，而且永远只有一个，如果第二个dialog上一级还有一个<div v-if=‘a’> ，当 a=false的时候会将div下面的dialog和遮罩一起去除，这就造成上一个弹出框还在但是遮罩没了的情况 @Leopoldthecoder  不知道我表达明白没有

**Comment by yuxiaoqi-seven** [comment]
问题的原因是产生遮罩的位置，遮罩是产生在dialog节点 同级的下一个，而且永远只有一个，如果第二个dialog上一级还有一个(div v-if='a')，当 a=false的时候会将div下面的dialog和遮罩一起去除，这就造成上一个弹出框还在但是遮罩没了的情况   @Leopoldthecoder 不知道我表达明白没有

**Comment by Leopoldthecoder** [comment]
#2556 
http://jsfiddle.net/o8t21h4u/3/ 修复了这个 demo 的问题。由于涉及到 DOM 结构的改变，属于非兼容性更新，会随 1.2.0 版本中发布。

**Comment by yuxiaoqi-seven** [comment]
thanks

**Comment by zhongmengyuan** [comment]
@jim888666  看我CSDN博客,完美解决弹框嵌套调用以及遮罩层相互影响的问题http://blog.csdn.net/zmy_coder/article/details/78042485
