### ISSUE TITLE
[El-Radio-Group] 应可支持 Boolean 类型

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#2442]
如题，当 label 绑定值未 Boolean 类型时控制台会报错，提示只能为 string 或 nubmer 类型。

![2017-01-17_150315](https://cloud.githubusercontent.com/assets/2276421/22010755/1864bcae-dcc6-11e6-8cef-395e3197daee.png)

演示如下：

http://jsfiddle.net/v3oovr86/1/

希望 prop 校验增加 `Boolean`，即如下图所示。

![el-button-group](https://cloud.githubusercontent.com/assets/2276421/21976759/4904585a-dc0e-11e6-86c4-e43724040fdf.png)

另外，建议 `el-radio-button` 的演示示例，改为 
```
<el-radio-button label="shenzhen">深圳</el-radio-button>
```

这种格式，更易于直观的理解

**Comment by renxia** [comment]
@QingWei-Li 
虽然问题简单，居然没人理，好尴尬

**Comment by QingWei-Li** [comment]
人力有限

**Comment by xofred** [comment]
希望 [单选框的文档](http://element-cn.eleme.io/#/zh-CN/component/radio) 关于 boolean 的用法，可以给出以上 jsfiddle 作为例子
```vue
<template>
                <el-radio-group v-model="fixed">
                    <el-radio-button :label="false">不固定</el-radio-button>
                    <el-radio-button :label="true">固定</el-radio-button>
                    <el-radio-button label="right">右边</el-radio-button>
                </el-radio-group>
</template>
```
