### ISSUE TITLE
时间控件传值为null时时间显示为1970-01-01 08:00:00

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#2443]
### ElementUI version

1.1.3
### Vue version

2.1.8
### Reproduction Link

[http://jsfiddle.net/qcnwaujv/](url)

当传值为null时，时间显示如图
![image](https://cloud.githubusercontent.com/assets/9413415/21976709/0f0666ac-dc0e-11e6-9753-6e6592b4f7c4.png)
### What is Expected?
当传值为null时，能显示placeholder内容

**Comment by Leopoldthecoder** [comment]
试试 1.1.4

**Comment by baiyaaaaa** [comment]
1.1.4已修复

**Comment by reverland** [comment]
好像1.1.3传‘’没有问题。。。

**Comment by Leopoldthecoder** [comment]
@reverland 对，null 才有问题。
