### ISSUE TITLE
1.1.4版本menu启用route模式后，menu-item用route属性的话没有高显显示

### ISSUE THREAD

**Issue by Caijt** [ElemeFE/element#2446]
刚看到更新，好兴奋，结果一更新，真感觉还不如不更新
现在我的menu-item启用route属性的话，点了后不会高亮了，如下图

![_20170116191344](https://cloud.githubusercontent.com/assets/15088550/21980911/fad731f4-dc1f-11e6-9596-dfcf8b4358df.png)

还有个小问题，就是我的页面是用两个menu组件的，然后点第一个menu组件时（menu-item是用index属性的）还会高亮，然后再点第二个menu组件时，第一个menu组件时就不亮的，本来版本不更新时还不会有这个问题
![_20170116191926](https://cloud.githubusercontent.com/assets/15088550/21981053/a734006c-dc20-11e6-968d-8ef88dc251f9.png)

**Comment by Yuliang-Lee** [comment]
是因为这个 https://github.com/ElemeFE/element/pull/2399 更新吧，虽然这个修改能解决一些问题，但是很明显会引入另外的问题，感觉草率的就merge了

**Comment by Caijt** [comment]
重点是没办法自己动态设置menu的index，我想在watch里监视$route的变化，然后再动态地设置menu的index也不行

**Comment by reverland** [comment]
1.1.4？

**Comment by reverland** [comment]
感觉似乎是不该在路由变化的时候强行设置activeIndex。。。

记不清哪个issue里说过这个问题的，我觉得navMenu应该是一个傀儡组件，activeIndex铀外部设置。

比如`/node/node_id/`和`/node/`的情形，还有一些路由的alias关系。目前navMenu的接口都不能得知。

https://github.com/baiyaaaaa/element/commit/48009e21e11c29460c8b5082ac9eed3025c1b666#diff-0b22194e02c76ef0bf29c2475e712f9f 似乎还没什么问题，毕竟还能从外部覆盖。

**Comment by reverland** [comment]
@baiyaaaaa

**Comment by baiyaaaaa** [comment]
@Yuliang-Lee  @Caijt 明天会尽快给出修复版本，抱歉给你们带了问题。你们可以先暂不升级。
@reverland 说的没错，我最初设计的时候也是这个想法。。路由的使用场景很难在一个组件内满足所有的需求，现在考虑 revert 掉这个commit

**Comment by languanghao** [comment]
@baiyaaaaa 能不能考虑这样，如果设置了`router=true`的时候，menu内部全部使用 vue-router 的 `<router-link>`，因为不管怎么处理这个问题，还是要去适应vue-router这种官方组件

**Comment by languanghao** [comment]
@reverland 这些问题vue-router 的 <active-link> 都解决了
