### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by ssyz1988** [ElemeFE/element#2447]
在引入Element之后，Vue.use()的时候报错。

![e8a9417b-9f8c-4944-8b04-dea56890e01c](https://cloud.githubusercontent.com/assets/5425529/21982627/39faa6a6-dc28-11e6-93be-d01b44647978.png)

[Vue warn]: Error when rendering root instance: 
warn @ vue.common.js?e881:521
Vue._render @ vue.common.js?e881:3103
(anonymous) @ vue.common.js?e881:2464
get @ vue.common.js?e881:1661
Watcher @ vue.common.js?e881:1653
Vue._mount @ vue.common.js?e881:2463
(anonymous) @ main.js?3479:15
(anonymous) @ app.js:882
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ app.js:587
__webpack_require__ @ app.js:556
(anonymous) @ app.js:579
(anonymous) @ app.js:582
vue.common.js?e881:1170 Uncaught TypeError: Cannot create property 'function mergeHook(

### ElementUI version
1.1.4

### OS/Browers version
macOS/Chrome 53

### Vue version
2.1.8

**Comment by reverland** [comment]
总感觉，1.0.0好像没支持2.1.6...

**Comment by ssyz1988** [comment]
实际上装的是1.1.4，并不是1.0.0
