### ISSUE TITLE
feature: allow Table filtering with props

### ISSUE THREAD

**Issue by rottmann** [ElemeFE/element#2450]
Currently only the built in Filter-Popup could be used to filter thw rows.

With a callback prop, external sources could be used to filter.

E.g. i have a global input field, which should on change filter the table when i type the chars.

**Comment by njleonzhang** [comment]
@rottmann, refer to this project, you can make it yourself.
https://github.com/njleonzhang/vue-data-tables

**Comment by rottmann** [comment]
:+1:
