### ISSUE TITLE
select下拉框，能不能加个默认选择一个选项，即绑定lable，又绑定value

### ISSUE THREAD

**Issue by liqinhua** [ElemeFE/element#2453]

**Comment by Leopoldthecoder** [comment]
没懂

**Comment by Cecilxx** [comment]
可以啊 通过selected的v-model设置 v-model对应是option的value  例如v-model=1 那么默认选项就是value=1的那一个option项

**Comment by erguotou520** [comment]
楼上+1,issue可关

**Comment by stanNo1** [comment]
如果设置 v-model=1，渲染完成之前显示的是 1，渲染完成才是匹配的option项

**Comment by yijic** [comment]
@Cecilxx 你都没理解他这个到底要什么意思，他这个主要是 value 跟 label 的值不一样，想要设置一个默认的 option 这样来吧这个 option 的 value 绑定到 v-model 的那个变量上，而显示的还是 babel 的值，如果在初始给 v-model 绑定的这个变量赋值上 想要的 value 那么就会导致，Select 初始显示的是 value 的值。然而实际想要的是 label 的值（又不能绑定 label 的值），所以才会提出一个默认选中的 option 让组件内部来把我想要默认选中的这个 option 的 value 绑定到 v-model 的变量上，而初始显示的是 这个 option 的 label 的值。
