### ISSUE TITLE
table的index列翻页显示问题

### ISSUE THREAD

**Issue by ericwang1902** [ElemeFE/element#2454]
请问一下，table的index列可以自定义吗？
比如，我翻到第二页，index应该从11开始，但是现在还是显示的从1开始，可以设置吗？
![image](https://cloud.githubusercontent.com/assets/7867163/22004441/8cb1d716-dc96-11e6-84e5-13c20914c950.png)

**Comment by ericwang1902** [comment]
已解决。

**Comment by ericwang1902** [comment]
我没有使用默认的index了，就是自己构造了编号数据。

**Comment by Leopoldthecoder** [comment]
目前这个需求是需要用户自己处理。

**Comment by yamateH-ch** [comment]
请教大佬，怎么构造的.提供参考下
