### ISSUE TITLE
Table开启Border选项后 在IE11与IE10下样式有轻微异常

### ISSUE THREAD

**Issue by EthianWong** [ElemeFE/element#2457]
### ElementUI version

http://element.eleme.io/ 使用的版本

### OS/Browers version

IE 11 , IE 10
### Vue version

http://element.eleme.io/ 使用的版本

### Reproduction Link

http://element.eleme.io/#/zh-CN/component/table#dai-bian-kuang-biao-ge

### Steps to reproduce
用IE11或IE10 打开 Reproduction Link

### What is Expected?
在谷歌下 开启表格的border 后 样式是正常的 如下
![qq 20170117114101](https://cloud.githubusercontent.com/assets/12590228/22006927/e9e6daae-dca9-11e6-8f5a-daf14814f57f.png)

在IE11和IE10下 开启表格的border 后 样式有略微的异常
![qq 20170117113740](https://cloud.githubusercontent.com/assets/12590228/22006937/09379a4c-dcaa-11e6-94df-b311a0abfa22.png)
类似 表格头 与 表格的行 的宽度无法一致对齐？

### What is actually happening?

**Comment by jikkai** [comment]
当前版本已无此问题。
