### ISSUE TITLE
popover报错

### ISSUE THREAD

**Issue by boboxiao** [ElemeFE/element#246]
报错：Uncaught TypeError: Cannot read property '$refs' of undefined

**Comment by txchen** [comment]
遇到了相同的问题: 

设了 ref="popover1" 以后, 错误变成了

index.js?23bf:164 Uncaught TypeError: Cannot read property '0' of undefined

**Comment by QingWei-Li** [comment]
请给出重现 demo 或代码

**Comment by txchen** [comment]
我这里是用 webpack + partial load:

大致代码如下: 

import Button from 'element-ui/lib/button'
import 'element-ui/lib/theme-default/button.css'
import Popover from 'element-ui/lib/popover'
import 'element-ui/lib/theme-default/popover.css'
Vue.component(Popover.name, Popover)
Vue.component(Button.name, Button)

```html
<template>
  <el-popover
    ref="popover1"
    placement="top-start"
    title="标题"
    width="200"
    trigger="hover"
    content="这是一段容,这是一段容,这是一段容,这是一段容。">
  </el-popover>
  <el-button v-popover:popover1>hover 激活</el-button>
</template>
```

**Comment by QingWei-Li** [comment]
@txchen 我本地用按需加载也是正常的
https://codepen.io/QingWei-Li/pen/gwvyyx

请给出能复现的 demo，不然没法找到问题

**Comment by txchen** [comment]
我把我 app 里的逻辑剥离出来, 单独开了一个 project, 可惜不能 repro 了

https://github.com/txchen/feplay/tree/gh-pages/elementtest

我继续研究一下.

@QingWei-Li 有一个问题: 我想再 table 里的某一列, hover 或者 click 弹出 popover, 请问应该怎么做? 我在`elementtest` 用了 inline-template, 但是只有最后一列可以出 popover.

**Comment by QingWei-Li** [comment]
@txchen 有两种用法，还有一种 slot 的方式，具体参考文档

**Comment by txchen** [comment]
谢谢! slot 方式成功了, 不过还是有问题:
https://github.com/txchen/feplay/commit/6de713d706dcc691e27314c7c8a4f11201a00d44

placement 只能在左或者右, top bottom 就显示不出来了. 貌似 z-index 被 table cell 覆盖住了. 另外行与行之间, popover 出现的位置有偏差. 

![image](https://cloud.githubusercontent.com/assets/713074/19216870/ae7383c6-8d82-11e6-9a16-f93dd82bbd8e.png)
![image](https://cloud.githubusercontent.com/assets/713074/19216871/b47f5484-8d82-11e6-9a9a-1dddfbce4310.png)

**Comment by QingWei-Li** [comment]
@txchen table 样式已经修复了，可以查看 changelog

**Comment by txchen** [comment]
我在本地按照 https://github.com/ElemeFE/element/commit/4b92796d8e1555e368dfbd38fe5aad5686045e8f 修改 node_modules 里的 table.css, 似乎没有变化. 

而且好像这个 commit 也没有调整过 z-index, 遮挡的问题应该还在吧?

**Comment by QingWei-Li** [comment]
@txchen 你用的按需加载？还是引入的是 element-ui/index.css 这个文件？感觉你没正确加载到 table.css 并且改完后要重启下 webpack

**Comment by txchen** [comment]
改的是 element-ui/lib/theme-default/table.css, 人肉 un minify :)
而且重启过了 webpack 了, 可能是 cache 了. 

请问什么时候 release 下一个版本?

**Comment by txchen** [comment]
应该是我之前没改对, 现在好了. 
![image](https://cloud.githubusercontent.com/assets/713074/19216969/e9e4ec52-8d86-11e6-9e9c-73a80093e947.png)

在角上会有 overflow 的问题, 不知道是我没改全还是怎么样? 期待下一个版本

**Comment by zhounewz** [comment]
width属性为什么最小宽度 150px？请问如何做到小于这个宽度的值？

**Comment by qiuyaofan** [comment]
解决了吗 我的macOS/Chrome 57.0.2987.133 (64-bit)也有问题

**Comment by MingNeo** [comment]
的确，popover只要在触发的元素前面，就有一定概率出现这问题。
