### ISSUE TITLE
checkbox model 绑定的值类型为number 时无效？

### ISSUE THREAD

**Issue by cench** [ElemeFE/element#2460]
http://jsfiddle.net/g0a7pfrc/

demo 如上，

model上默认选中状态值为 1 true-label 也为 1，但是没有选中，设置为 “1” 字符串类型时就可以绑定，麻烦看下是否有这个问题

**Comment by erguotou520** [comment]
http://jsfiddle.net/erguotou525/g0a7pfrc/1/

**Comment by lincenying** [comment]
绑定prop时, 前面不加冒号, 类型为字符型...
那么data里的类型也必须是字符型
```javascript
data() {
  return {
    a: '1'
  }
}
```

**Comment by erguotou520** [comment]
issue可以close了
