### ISSUE TITLE
表格expand row的展开收上的动画效果

### ISSUE THREAD

**Issue by reverland** [ElemeFE/element#2462]
类似下图所示，表格行展开合上时加上过渡动画，如navMenu和collapse

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1418726/22010093/fb620ae8-dcc1-11e6-942b-11e1ba1e170f.gif)

**Comment by reverland** [comment]
试着加了下collapse-transition，然后表格挂了 = =

**Comment by QingWei-Li** [comment]
试了下，感觉变卡了。。。

**Comment by baiyaaaaa** [comment]
table本来就很重了，不适合加这个啊。。特别是table里还有嵌套各种组件的情况

**Comment by reverland** [comment]
一个很重的table，机智地套用css直接用table写了个不卡的。。

**Comment by ranransun** [comment]
> 一个很重的table，机智地套用css直接用table写了个不卡的。。
请教一下怎么解决的这个问题

**Comment by ranransun** [comment]
请问下怎么解决的这个问题啊 加动画效果

**Comment by reverland** [comment]
@ranransun 没用element ui的，重新写了个组件套用css
