### ISSUE TITLE
[问题]el-input有没有属性可以设置它在页面初始化完毕后自动获得焦点

### ISSUE THREAD

**Issue by ren8179** [ElemeFE/element#2464]

**Comment by QingWei-Li** [comment]
1. 请不要滥用 Issue，只能提交 Bug 和 Feature，具体参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)

你的问题文档的 API 里都列着的
