### ISSUE TITLE
当 <el-radio-button> 和<el-input-number> 同时使用时,<el-radio-button>在Chrome 中可能需要点击多次才能选中

### ISSUE THREAD

**Issue by hkeyjun** [ElemeFE/element#2465]
### ElementUI version
1.1.2

### OS/Browers version
Windows 10/55.0.2883.87 m (64-bit)

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/hkeyjun/jhud3cdo/

### Steps to reproduce
https://www.screencast.com/t/J5uef2Tp
此bug 只在chrome中出现, 当多次点击`<el-input-number>` 增长/减少 按钮后 可能需要多次点击`<el-radio-button>`才能完成选中.

**Comment by baiyaaaaa** [comment]
fixed in #4217
