### ISSUE TITLE
分组select无法通过表单validate验证，其他类型select可以

### ISSUE THREAD

**Issue by muyuren** [ElemeFE/element#2467]
vue和element均为最新版
关键代码如下：
```
<el-form :model="editForm" label-width="100px" :rules="editFormRules" ref="editForm">
  <el-form-item label="权限" prop='privilegeList'>
    <el-select v-model="editForm.privileges" multiple placeholder="请选择">
      <el-option-group v-for="group in projectPrivileges" :label="group.projectname">
        <el-option v-for="item in group.privilege" :label="item.name" :value="item.priId">
        </el-option>
      </el-option-group>
    </el-select>
  </el-form-item>
</el-form>

```

```
editFormRules: {
  privilegeList: [
    {required: true, message: '请选择权限', trigger: 'change', type: 'array'},
  ]
}
```

**Comment by Leopoldthecoder** [comment]
Select 的绑定值是 `editForm.privileges`，验证的却是 `privilegeList`，自然不能通过。

**Comment by Nbalance** [comment]
请问如果select绑定值没输错，有验证但是就算输入正确的值也依然报错是什么原因

**Comment by Nbalance** [comment]
<el-form-item label="送检单位" prop="searchType2">
        <el-select v-model="searchType2" @change="searchTypeChange2(searchType2)" placeholder="送检单位" class="setWidth">
          <el-option v-for="item in list1" :key="item.id" :label="item.unitName" :value="item.id" type=""></el-option>
        </el-select>
      </el-form-item>

searchType2: [
          { required: true, message: '请输入送检单位', trigger: 'change' }
        ],

**Comment by CYvonne** [comment]
我下拉框用的字符串类型都验证没反应x_x
