### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by caizhiyongjava** [ElemeFE/element#2468]
使用elementui的tooltip，能和表单验证一起用吗，当验证不通过时候，怎么调用设置的tooltip触发显示

**Comment by QingWei-Li** [comment]
1. 请不要滥用 Issue，只能提交 Bug 和 Feature，具体参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)

**Comment by leif0419** [comment]
Tooltip  No prompt
