### ISSUE TITLE
table 表头th的背景色 会覆盖border-right 在IE和firefox 是下的bug

### ISSUE THREAD

**Issue by hujianjian187** [ElemeFE/element#2469]
在chrome下 是正常的 
![1](https://cloud.githubusercontent.com/assets/22463383/22015273/4c016ab0-dcdc-11e6-8b6e-86fd24c243f9.png)

但是在IE11 和 firefox下 显示不出来！ 改了一天不知道该哪里！
![2](https://cloud.githubusercontent.com/assets/22463383/22015302/6da6b56c-dcdc-11e6-92a1-f0003056f917.png)

**Comment by Leopoldthecoder** [comment]
Element 版本是？

**Comment by hujianjian187** [comment]
@Leopoldthecoder  VUE是2.1.8 Element版本是 1.1.3
