### ISSUE TITLE
导航菜单能否支持4级甚至更多的优化呢

### ISSUE THREAD

**Issue by seekwe** [ElemeFE/element#2470]
感觉这种方式似乎更优点
![_20170117174525](https://cloud.githubusercontent.com/assets/5528581/22015382/c6148940-dcdc-11e6-871b-e8acb3722ad7.png)

**Comment by languanghao** [comment]
+1

**Comment by stanNo1** [comment]
+1

**Comment by perfectyang** [comment]
+1

**Comment by fengyun2** [comment]
+1
