### ISSUE TITLE
【建议/农历】日历组件有没有考虑增加农历选项？

### ISSUE THREAD

**Issue by 1847211504** [ElemeFE/element#2471]
在国内的话，农历还是有用的，发现目前日历组件并不支持，不知道后续的版本中有没有支持计划？

有一个 1900-2100区间内的公历、农历互转的农历库 http://www.jjonline.cn/Public/Js/calendar.js ，看起来添加起来好像不难 :)

### ElementUI version
1.1.5

### OS/Browers version
windows server 2008 R2/Chrome 47 内核

### Vue version
 2.1.8

**Comment by QingWei-Li** [comment]
个人感觉用处不大

**Comment by jikkai** [comment]
elementui现在没有日历组件，只有 datepicker 和 timepicker ，没有 calendar

如果有 calendar 的话那我给加一票，考虑到中国传统节假日，农历还是有一定应用场景的。但如果指的是往 datepicker 里添加农历，这个适用场景可能就比较小了，大多数人大概只知道每年农历开始的第一天 😑

**Comment by languanghao** [comment]
@QingWei-Li 感觉蛮好的啊，就在阳历下面加上农历。。。

**Comment by 1847211504** [comment]
嗯，我们的需求里暂时只是 datepicker 。

是这样的，我们这里有活动是按农历月份为周期举行的，所以暂时 datepicker 应该就够了（因为农历里存在闰月，所以无法用单纯的十二个月份来选择），所以想咨询下官方，有没有这方面的打算？如果有我就打算等一等，如果没有正在考虑通过什么方式来做，支持插件还是自己用 element 来扩展一个出来。

@jikkai 说的日历组件是不是类似于 Google Calendar 那样的带日程安排的日历？那个我们系统中以后可能也会用到。

**Comment by jikkai** [comment]
@1847211504 我觉得可以单独把datepicker抽出来做一个第三方的农历日期选择器，最好别改element原来的组件，理由是为了实现一个小众功能让大多数人承担代码容量上和bug风险的增加不太好，当然这也只是个人看法

**Comment by 1847211504** [comment]
@jikkai 是的，我也是这么想的，如果官方没计划支持，那我还是觉得自己照着扩展一个出来比较合适。

**Comment by QingWei-Li** [comment]
嗯 没计划支持
