### ISSUE TITLE
table 自定义列模板 会重复渲染三次

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2475]
ElementUI version  1.1.4 
[demo](http://jsfiddle.net/vcgftLvn/20/)

table 自定义列模板 回重复渲染三次
![image](https://cloud.githubusercontent.com/assets/8121621/22018609/947c96bc-dcea-11e6-9ec0-1d6b47fad333.png)

**Comment by Leopoldthecoder** [comment]
和实现有关，目前可能没什么优化办法。

**Comment by Quincyli666** [comment]
亲测使用固定列可以复现，此问题在2.15.14版本依旧存在。只能放弃使用固定列了（去掉fixed=“left”、fixed=“right”）
