### ISSUE TITLE
单独使用checkbox而不使用checkbox-group时，选中状态变更不会触发表单校验

### ISSUE THREAD

**Issue by yang0323** [ElemeFE/element#2476]
代码里看，change时只触发了
```
this.dispatch('ElCheckboxGroup', 'change', [...]);
```
而没有触发
```
this.dispatch('ElFormItem', 'el.form.change', [...]);
```
这样必须checkbox在group内时，才能借助checkbox-group触发校验，这是出于什么考虑？
使用checkbox组合成其他组件的时候，遇到了这个情况~

**Comment by baiyaaaaa** [comment]
避免多次触发校验

**Comment by yang0323** [comment]
目前这个设计方式，checkbox-group触发一次，不使用checkbox-group就不触发校验
还是有缺陷的
