### ISSUE TITLE
el-select更换数据到空再换到其它数据input的文字显示会出错

### ISSUE THREAD

**Issue by zeromake** [ElemeFE/element#2481]
[demo](https://jsfiddle.net/zvuxu82y/)
效果图
![gif](https://cloud.githubusercontent.com/assets/8318747/22047721/a1d556fe-dd63-11e6-8ac9-e2e6ea28466a.gif)

**Comment by erguotou520** [comment]
我试了下 确实有这个问题 [修改后的demo](https://jsfiddle.net/erguotou525/zvuxu82y/1/)

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/2466/commits/b5d5922709436bf04141846ea3a0dca5e9196422

**Comment by zeromake** [comment]
@Leopoldthecoder 能问下为啥我看不懂到底改了什么？？感觉不是和原来一样的？但是我这边直接改了源码试了却可以了。明明只是filter改成了for来。

**Comment by Leopoldthecoder** [comment]
@zeromake 之前是找第一个符合条件的 option，现在是找最后一个，即最近缓存的

**Comment by zeromake** [comment]
@Leopoldthecoder 谢谢，原来如此。
