### ISSUE TITLE
Icons not showing on chrome or firefox

### ISSUE THREAD

**Issue by jpkontreras** [ElemeFE/element#2483]
### ElementUI version
**1.1.5** 

### OS/Browers version
**Google Chrome	55.0.2883.87, Firefox 50.1.0**

### Vue version
** 2.1.0 **

### Reproduction Link
No way to reproduce

### Steps to reproduce
Install any vue-cli páckages and install

### What is Expected?
To work
### What is actually happening?
. Everything works except icons.

###Obs
vue-cli no webpack.base.js modifications.
added babelRC
added babel-component package

**Comment by Leopoldthecoder** [comment]
Please provide a GitHub repository that can reproduce this issue.

**Comment by xRoker** [comment]
Hi, guys! Same situation here, can't get icons working with Webpack, unless I use the Element starter template. Here is an example repo https://github.com/xRoker/ElementUI-No-Icons

**Comment by xRoker** [comment]
Ok, it was because I used file-loader for woff|woff2|svg , instead of url-loader.

**Comment by mhpm** [comment]
how i fix this issue, please help step by step.. =(
