### ISSUE TITLE
tab自动切换状态异常

### ISSUE THREAD

**Issue by lihonglei7** [ElemeFE/element#2485]
tab标签自动转换后状态没有完全切过去
![aa](https://cloud.githubusercontent.com/assets/24932705/22049664/d0f22c94-dd6f-11e6-8834-4fd3fad11409.png)

**Comment by QingWei-Li** [comment]
麻烦提供可复现问题的 demo

**Comment by lihonglei7** [comment]
好的，我去先写个demo

**Comment by lihonglei7** [comment]
http://element.eleme.io/#/zh-CN/component/tabs
中第一个例子在我的程序中就有这个问题

**Comment by lihonglei7** [comment]
最新版本已经修改了这个问题，感谢您的及时回复。
