### ISSUE TITLE
关于input这种基本表单控件的原生事件

### ISSUE THREAD

**Issue by chenxiao5** [ElemeFE/element#2487]
这种基本表单控件是否可以放开更多的原生事件，例如：keyup

**Comment by jikkai** [comment]
https://github.com/ElemeFE/element/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20keyup

**Comment by erguotou520** [comment]
注意多看看文档
https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components

issue可关
