### ISSUE TITLE
使用tree树形结构时,怎么通过某个字段判断哪些默认勾上哪些默认不勾上,主要是不懂那个node-key的设置?

### ISSUE THREAD

**Issue by jiangyundong1** [ElemeFE/element#2489]

**Comment by amwyyyy** [comment]
默认勾选是default-checked-keys属性，node-key设置节点的值是哪个字段，再用getCheckedKeys获取

**Comment by Leopoldthecoder** [comment]
文档例子更新了，可以参考一下：https://github.com/ElemeFE/element/pull/2713/files#diff-f52977e061ce05f21ebff84c15289101
