### ISSUE TITLE
对于1.1.5版本的menu组件提个小小的建议

### ISSUE THREAD

**Issue by Caijt** [ElemeFE/element#2490]
对于1.1.5版本menu组件更新后，还是达不到我的需求，最后通过修改组件原代码，再配合watch跟beforeRouteEnter达到我的需求。

先说下我的需求
![default](https://cloud.githubusercontent.com/assets/15088550/22051772/99da8380-dd80-11e6-942e-5980d9f266bd.png)
1、主框架组件[admin.vue]：这里面我放了一个顶部主模块菜单menu组件，中间区域放了一个route-view主要用来放下面的menu_content.vue内容框架组件；
2、内容框架组件[menu_content.vue]：我放一个左侧子菜单menu组件，这里的菜单数据是点击顶部主模块菜单后加载的，右边主区域放了一个route-view用来显示我的主内容；

原理是这样的，点击顶部menu主模块菜单后，左侧menu的回钓函数beforeRouteEnter就会执行，我在这里根据所点模块菜单url加载相应的子菜单，然后替换掉左侧menu的菜单数组

**我理想达到的是：**
1、我点不同的主模块菜单后，切换不同的左侧菜单后，那些菜单要跟没点过一样，全部都是折叠的；
2、我在任何地方按F5刷新后，那些menu组件的高亮链接还是对的
3、我直接在URL输入链接后跳转后，menu组件的高亮还得是对的（如果高亮的链接在subMenu里面，那相应的subMenu也得自动打开）

以上3点，都有不同程度无法实现的问题
以上第2、3点，可以在watch里面对$route进行监听，注意必须得用setTimeout，不能用nextTick
```
watch:{
    '$route': {
        immediate: true,
        handler(r) {
            //这里如果不用setTimeout，而用nextTick或直接this.menuIndex=r.path的话，如果菜单刚好在subMenu里面的，它不会自动展开
            setTimeout(()=>{
                //menuIndex是menu组件default-active的绑定值
                this.menuIndex=r.path
            },0)
        }
    }
}
```

**对于第1点**，实在是没有办法，好像有缓存似的，左侧加载不同的子菜单后，再返回之前加载的，那些subMenu还是保持原来的展开状态，而且链接高亮状态还保持着
那只能修改menu的原代码了
1、为了解决menu总是缓存展开状态，我在menu组件里增加一个closeAllMenus方法
```
methods: {
    //折叠所有菜单组
    closeAllMenus:function(){
	this.openedMenus = [];
    },
    ......
}
```
然后在我的menu_content.vue内容框架组件里的beforeRouteEnter里对menu组件执行closeAllMenus方法
```
next(v=>{
    //折叠所有菜单组，得先在el-menu上定义ref
    v.$refs.menu.closeAllMenus()
    //更换菜单数据
    v.menus=menus				
})
```
这样就可以解决切换菜单时，总保持之前的展开状态的问题

还有个问题，就是这个高亮的，左侧切换不同的模块菜单数据后，高亮总是保持在我之前点过的菜单上，一开始很奇怪，因为我都在watch中的$route中对menuIndex值动态修改了

后面看了组件的代码才知道，我修改menuIndex后，组件还得检查一下这个index在menu中是否存在，不存在就return，不执行了，我觉得这样可能不太好，因为有时需要取消高亮也很正常，所以进行以下修改
```
watch: {
    defaultActive: function defaultActive(value) {
        //注释掉原没找到菜单项目就停止执行
        //var item = this.items[value];	      
        //if (!item) return; 	      
        //this.activedIndex = item.index;
	      
        //改成先将value设置成activedIndex，再检查这个菜单存不存在，不存在就return
	this.activedIndex=value;
        var item = this.items[value];	      
        if (!item) return; 	
	this.initOpenedMenu();
    }
}
```

这样修改下来，已经完美地满足我的需求了，希望作者可以在下个版本中这样修改一下

因为我还不太会用git，不懂怎么pull还是push代码，只能通过这种方式向你们建议下

**Comment by Caijt** [comment]
1、如果用```:default-active='$route.path'```的话，菜单如果是subMenu里的，不会自动展会subMenu了
2、如你所说的，我的左侧数据就是点上方的menu后加载的，
你说的我也理解，一开始我也是为我主模块menu（上方的menu）每个菜单创建一个左侧控件，就没第1点的问题，写了两个，发现左侧控件全部代码都一样，只是数据不同，原谅我有点强迫症，我总感觉这样太不舒服，所以一直强迫自己得弄一个控件，来加载不同的数据

我觉得加多个折叠所有菜单的方法也是满好的，再有那个高亮的问题，我觉得有的人确实有手动取消高亮的需求

只是希望作者能接收下，当然不接收也没办法，以后每次升级，我都手动修改下原代码了

**Comment by reverland** [comment]
简要理解是，希望能清空高亮状态？

**Comment by languanghao** [comment]
@Caijt 我还真没发现怎么指定某项展开的，设置`default-openeds`并没有用

**Comment by languanghao** [comment]
@reverland 我猜你在外面加个v-if，然后重复设置一下这个值就清空了

**Comment by Caijt** [comment]
@reverland 对的，再加个折叠所有菜单的方法就完美了

**Comment by Caijt** [comment]
@languanghao 你用我那个方法 setTimeout 里执行就可以自动展开了

**Comment by languanghao** [comment]
@baiyaaaaa `default-openeds`这个是不是文档里没说清楚啊

**Comment by reverland** [comment]
@languanghao 我有次试了试openeds，好像也没用，还以为自己姿势不对。。

**Comment by Caijt** [comment]
另外自己弄了一个可以实现传入数据数组，自动生成无限级子菜单的辅助组件，有需要的同学可以参考下

el-menu-tree.vue
```
<template>
	<el-menu-item :index="menu.path||menu.id.toString()" :route="{path:menu.path}" v-if="typeof(menu.children)=='undefined' || menu.children.length==0">{{menu.text}}</el-menu-item>
	<el-submenu v-else="menu.children.length>0" :index="menu.id.toString()">
    <template slot="title">{{menu.text}}</template>
    <el-menu-tree v-for="m in menu.children" :menu="m"></el-menu-tree>
  </el-submenu>
</template>
<script>
    export default {
        props: {
            menu: {
                default() {
                  return {};
               }
            }
        }
    }
</script>
```

数据结构如下，我是以数据的path为作为el-menu-item的index，id只是在subMenu时作为index使用
```
menus:[
    {
        id:1,
        text:"设备管理",
       children:[
            {id:2,text:"新增设备",path:"/it/equ_add"}
       ]
    },
    {
        id:3,
        text:"合同管理",
        path:"/it/contract"
    }
]
```
使用方法
```
<el-menu ref="menu" :default-active="menuIndex" router>
    <el-menu-tree v-for="m in menus" :menu="m"></el-menu-tree>
</el-menu>
```

**Comment by baiyaaaaa** [comment]
@Caijt 组件状态应该由数据来驱动，高亮菜单项对应的是 `default-active` 属性，展开菜单项对应的是`default-openeds` 属性，对于怎么实现你的业务逻辑就看你怎么对他们对 `$route` 之类的东西进行联动了，目前是`default-openeds`无效么？

**Comment by baiyaaaaa** [comment]
@reverland 我刚试了没问题。。，动态也是可以的

**Comment by Caijt** [comment]
@baiyaaaaa 噢。确实是我大意了，还有个```default-openeds```属性，我在```beforeRouteEnter```里面将 这个数组设置为[]就可以了
但这个高亮的问题，如果我想清空状态的话，我将```default-active```设置为空值并不行，因为我看了原代码里面，是先检查菜单是否存在，只有存在才对activedIndex赋值

**Comment by baiyaaaaa** [comment]
了解，这个确实有这样的需求， 预计会实现在下个版本里，@Caijt

**Comment by Caijt** [comment]
看来我还没习惯新的开发模式（组件状态应该由数据来驱动） 这种新概念，以前用惯了jquery，有的地方还是习惯用传统方法来实现状态的改变

**Comment by languanghao** [comment]
@baiyaaaaa `default-openeds`就是无效的

**Comment by Caijt** [comment]
@languanghao 你应该是页面刷新时无效，我也测试了，必须得在setTimeout里面对 default-openeds 对进操作就有效，没用setTimeout就没效

**Comment by baiyaaaaa** [comment]
#2877 default-active 置空的支持
