### ISSUE TITLE
[select]路由用keep-alive之后，分组select的值会被清掉

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#2494]
路由<router-view>用keep-alive，select的分组再次进路由的时候会被清空，没有分组的select不会，如图，值还在，但是界面上的“根茎”已经显示了
![image](https://cloud.githubusercontent.com/assets/12726826/22053477/db5f4a7e-dd8b-11e6-8d66-968975ec6c0f.png)

这种不会清空
![image](https://cloud.githubusercontent.com/assets/12726826/22053553/5d704d74-dd8c-11e6-9179-4efa2ce8123a.png)

**Comment by Leopoldthecoder** [comment]
试了一下，没有重现。请提供能重现的例子，可以是一个仓库。
