### ISSUE TITLE
el-input--- 1.keyup事件无效2.密码框浏览器不提示记住密码

### ISSUE THREAD

**Issue by fandudu** [ElemeFE/element#2495]

**Comment by QingWei-Li** [comment]
1. 请不要滥用 Issue，只能提交 Bug 和 Feature，具体参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)

---------

麻烦看看 FAQ

**Comment by fandudu** [comment]
不是bug？？？？

**Comment by fandudu** [comment]
@QingWei-Li  我提的这个不是bug？

**Comment by QingWei-Li** [comment]
1. FAQ 第一条就清清楚楚写着 Vue2 里 `native` 的用法
2. 这个是浏览器的行为
