### ISSUE TITLE
collapse-transition展开动画在safari下有闪烁

### ISSUE THREAD

**Issue by reverland** [ElemeFE/element#2498]
### ElementUI version
1.1.5

### OS/Browers version
Safari

### Vue version
2.1.8

### Reproduction Link
官网例子

### Steps to reproduce
点击展开合上vertical的navMenu,Tree,Collapse

### What is Expected?
不出现闪烁

### What is actually happening?
展开项展开后会回到高度为0之后再展开。

https://github.com/ElemeFE/element/blob/5753b452afc5558a7165429c0ed2d9c836fed3f6/src/transitions/collapse-transition.js#L29 把这一行去掉能解决这里的问题，但感觉这个height操作是为了重置回之前的高度？是否应该保留下oldHeight？

@baiyaaaaa

**Comment by reverland** [comment]
还有个问题：https://github.com/ElemeFE/element/blob/5753b452afc5558a7165429c0ed2d9c836fed3f6/src/transitions/collapse-transition.js#L67

如果被包含的是v-if指令的组件，item.data可能是undefined，class也可能没有，也可能之前有。觉得这里判断一下比较好

**Comment by baiyaaaaa** [comment]
都写了这么多了，要不提个 pr 把🌚

**Comment by reverland** [comment]
🌚大佬倒是给些指导啊
