### ISSUE TITLE
 Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors. (found in component <ElSelect>)

### ISSUE THREAD

**Issue by laughmaker** [ElemeFE/element#250]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.1

使用select的时候，代码如下

```
    <el-select v-model="form.sex" value="1" placeholder="请选择" class="worker">
        <el-option label="男" value="1"></el-option>
        <el-option label="女" value="2"></el-option>
    </el-select>
```

最后终端报错
 Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors. (found in component <ElSelect>)

**Comment by Leopoldthecoder** [comment]
确认一下 vue 的版本号吧，如果是 2.0.1 的话应该不会有这个问题：https://jsfiddle.net/wj7kvLnc/

**Comment by laughmaker** [comment]
sorry,后来发觉，是在主页面，使用了el-menu这个控件的原因.
跟这个算是同一个原因：https://github.com/ElemeFE/element/issues/200

**Comment by chachaxw** [comment]
@Leopoldthecoder @laughmaker 我现在用el-table也有会报这个错，我的vue版本为2.0.3最新版本。目前还未发现什么原因

**Comment by Leopoldthecoder** [comment]
@chachaxw 能给个在线 demo 吗？

**Comment by chachaxw** [comment]
现在又没有了，好多坑

**Comment by chachaxw** [comment]
我在刷新页面的时候就会出现这个问题。

**Comment by laughmaker** [comment]
我是因为添加了menu组件出现的，去掉那个组件就不提示了。
现在新版已经没这个提示了啊。

2016-10-18 10:37 GMT+08:00 周伟 <notifications@github.com>:

**Comment by aguegu** [comment]
刷新出现的概率很高。
