### ISSUE TITLE
关于元素class命名的疑问

### ISSUE THREAD

**Issue by tyrion-yu** [ElemeFE/element#251]
### ElementUI version
1.0.0-rc.4

### What is Expected?
class命名的修饰符保持一致的风格。

### What is actually happening?

> dom元素的class的修饰符，在Element中，发现了2种风格；算上mint-ui，发现了第三种。

#### 单横线连接修饰符

修饰一个按钮的特定外观：
`el-button el-button-default`
`el-button el-button-danger`

#### 以`is-`开头，加形容词的方式

修饰一个输入框是不可用的：
`el-input is-disabled`

修饰一个步骤组件表现是水平的：
`el-step is-horizontal`

#### 双横线连接修饰符

按钮部分接近BEM风格，但又不是。在Mint-ui里，又是这样的：
`mint-button mint-button--primary`

**Comment by QingWei-Li** [comment]
混用了 suitcss 和 BEM 而已，对使用上没有影响
