### ISSUE TITLE
steps组件动态添加数据，流程显示文字不自增

### ISSUE THREAD

**Issue by mochenxm** [ElemeFE/element#2512]
### ElementUI version
element-ui@1.0.7

### OS/Browers version
macOS/Chrome 55.0.2883.95 (64-bit)

### Vue version
vue@2.1.6

### Steps to reproduce
<img width="426" alt="2017-01-18 9 12 40" src="https://cloud.githubusercontent.com/assets/19199218/22065362/e30348b6-ddc2-11e6-9785-71bf2eb21728.png">

```javascript
<!--模版-->
<template>
	<div>
		<el-button type="primary" @click="add">默认按钮</el-button>
		<el-steps :space="100" :active="active" finish-status="success">
			<el-step v-for="item in steps" :title="item.title"></el-step>
		</el-steps>
	</div>
</template>
<!--脚本-->
<script>
	export default {
		data: function () {
			return {
				steps: [{
					title: '1111',
				}, {
					title: '222',
				}, {
					title: '333',
				}, ]
			}
		},
		methods: {
			add: function () {
				this.steps.push({
					title: '444'
				})
			}
		}
	}
</script>
```

### What is Expected?
期望动态添加steps节点， 期望流程数是自增的

### What is actually happening?
动态往steps里添加节点，流程不断增加0

**Comment by Leopoldthecoder** [comment]
Fixed in #2523

**Comment by Sijiu** [comment]
能否让直接使得step的icon支持绑定@click 事件，自己按钮老是不能对齐

**Comment by jim888666** [comment]
想知道给步骤条添加图标时，在i标签内为什么添加事件，在页面点击时不触发任何函数？？
