### ISSUE TITLE
Time-picker not updating value with manual change

### ISSUE THREAD

**Issue by afucher** [ElemeFE/element#2514]
### ElementUI version

1.1.5
### OS/Browers version

Linux Mint/Chrome 55
### Vue version

2.1.10
### Reproduction Link

https://codepen.io/afucher/pen/qRaELB
### Steps to reproduce
Select a value in time-picker, after that change the value writing another value in the input of time-picker.
### What is Expected?
That the value of v-model property on component instance changed.
### What is actually happening?
The value of of v-model property on component stay the same, just looked at the next input, it don't change the value

**Comment by Dreamacro** [comment]
Fixed in #6023
