### ISSUE TITLE
DateTimePicker input的时间和面板选择时间不同步

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2515]
当使用DateTimePicker的日期和时间范围时，我改变了input内的日期，但面板的日期不会相对应的改变，导致两者不同步 [demo](http://jsfiddle.net/vcgftLvn/22/)
![demo](https://cloud.githubusercontent.com/assets/8121621/22091151/62dc1636-de30-11e6-9fda-27ee0d78a87f.gif)

**Comment by QingWei-Li** [comment]
其实也不算 bug 吧
最小时间（左边）超过了最大时间（右边），所以就没有变化

**Comment by PanJiaChen** [comment]
我觉得可以像ant学习一下 [url](https://ant.design/components/date-picker-cn/)
加一个校验，不符合条件的不让生效更合理一点

**Comment by csvwolf** [comment]
PR earlier than 2018, closed.
