### ISSUE TITLE
DateTimePicker disabledDate的两个问题

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2516]
[demo](http://jsfiddle.net/vcgftLvn/23/)
1.当我设置了disabledDate，禁止选择当期时间之后的时间，但我从input的框还是能输入未来的时间，所以disabledDate的设置只是相对于面板的？
2.当我设置了disabledDate，禁止选择当期时间之后的时间，但时间选择器还是能任意时间随便选,所以disabledDate的设置只是相对于日期的？时间不能有任何约束么？

**Comment by stillsilly** [comment]
这里的第二个问题后来怎么办的？
只能禁止日期，没法禁止时间（时分秒）吗

**Comment by fantasybei** [comment]
@stillsilly 同问

**Comment by cyy12115021003** [comment]
同问

**Comment by FE92star** [comment]
版本2.13.2目前第二个问题依然存在
