### ISSUE TITLE
MessageBox的message支持html

### ISSUE THREAD

**Issue by hizhengfu** [ElemeFE/element#2517]
在v1.1.5中是不支持html格式，希望能使用v-html来渲染message

**Comment by reverland** [comment]
那個傳vnode的沒有merge麼

**Comment by QingWei-Li** [comment]
MessageBox 的没写，为啥 MessageBox 也需要。。。

**Comment by reverland** [comment]
可能messagebox裏要顯示個圖片，icon什麼的吧

**Comment by Leopoldthecoder** [comment]
不赞成 MessageBox 支持 html，因为它本来就只是为了替换系统的 `alert`，`confirm` 和 `prompt`，是很轻量的。

需要自定义内容的话，应该使用 `Dialog`。

**Comment by sukonzer** [comment]
@Leopoldthecoder dialog不支持多次弹窗，有业务场景是二次弹窗的，需要dialog配合messageBox，而messageBox内需要动态展示一些表单啥的
