### ISSUE TITLE
选择日期范围bug

### ISSUE THREAD

**Issue by tyrion-yu** [ElemeFE/element#252]
### ElementUI version
[官方文档示例的版本](http://element.eleme.io/#/component/date-picker)

### OS/Browers version
Chrome 52

### Vue version
[官方文档示例的版本](http://element.eleme.io/#/component/date-picker)

### Reproduction Link
[官方文档示例的版本](http://element.eleme.io/#/component/date-picker)

### Steps to reproduce
1、选择日期【10月7日】到【10月16日】，完成选择。
2、重新打开日期选择面板，先点击【10月9日】，再点击【10月2日】；
3、选择面板不消失，点击其他早于【10月9日】的日期面板也不消失。

### What is Expected?
打开选择面板，
第一次点击一个日期，该日期高亮；
鼠标浮动到任意一个日期，不论早于该日期还是晚于该日期，区间高亮；
第二次点击，不论早于该日期还是晚于该日期，完成选择。

### What is actually happening?
same to `Steps to reproduce` part.

**Comment by QingWei-Li** [comment]
不是 bug，就这样设计的。可以参考 antd
