### ISSUE TITLE
table的行高度怎么调整？

### ISSUE THREAD

**Issue by dreamrom** [ElemeFE/element#2521]
我期待table的行高度能再小一点，该怎么做呢？或者可以设置个参数size = “small"？

### ElementUI version 
1.1.5

### OS/Browers version

chromium 54
### Vue version
2.1.10

**Comment by jikkai** [comment]
可以用css覆盖样式

**Comment by dreamrom** [comment]
怎么做？是哪个样式？

**Comment by LFHSEU** [comment]
求问，怎么设置行高小一些？

**Comment by q1cha0** [comment]
@dreamrom @LFHSEU   在标签`el-table`中设置id, 然后`#idName table tbody tr { height: ... }` .

**Comment by qiangbro** [comment]
现在el-table 已经支持 size = “small"了

**Comment by CoolMusk** [comment]
<el-table :data="testList" style="width: 100%"  :row-style="{height:'40px'}">

增加   :row-style="{height:'40px'}"

**Comment by charles-chenguojun** [comment]
table高度固定 怎么让row 不自适应高度  给固定高度没效果

**Comment by xumin929** [comment]
设置row-style = "height:0"为最小行高，最小行高是35px 就不能在缩小了，哪位大神还有办法能缩到比35px小一点？

**Comment by thkaw** [comment]
> 
> 
> 设置row-style = "height:0"为最小行高，最小行高是35px 就不能在缩小了，哪位大神还有办法能缩到比35px小一点？

確實...透過這方式沒辦法在更小了

**Comment by JackZhouMine** [comment]
请问找到可行的办法了吗？

**Comment by JackZhouMine** [comment]
解决了：
设置两个类
```js
   :row-class-name="rowClassName"
   :cell-class-name="cellClassName"
```
[element表格设置行高
](https://codepen.io/JackZhouMine/pen/MWWaywK)

**Comment by NoLiuxin** [comment]
> 现在el-table 已经支持 size = “small"了

为什么我在row里面增加
<template slot-scope="scope">
                  <el-button type="text" size="small" @click="handleClickCopy(scope.row)">复制</el-button>
                  <el-button type="text" size="small" @click="handleClickDetails(scope.row)">详情</el-button>
                </template>
el-table 设置 size = “small"就没有作用了？

**Comment by yinjinxiong** [comment]
> table高度固定 怎么让row 不自适应高度 给固定高度没效果

我也遇到这个，设置了高度，row还是自适应了，请问有解决的方法吗？
