### ISSUE TITLE
table 列中做内容筛选是怎么做？input怎么加入column中？

### ISSUE THREAD

**Issue by dreamrom** [ElemeFE/element#2524]
如题？

**Comment by jikkai** [comment]
请仔细阅读 Table 组件的[文档](http://element.eleme.io/#/zh-CN/component/table)。

如果有使用上的问题欢迎来 [Gitter](https://gitter.im/ElemeFE/element) 提问，大家会在有余力的时候给予帮助，issues 还是应该用来提 bug 和 feature 的。
