### ISSUE TITLE
DatePicker选择日期范围 endtime 有bug

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2527]
[demo](http://jsfiddle.net/vcgftLvn/24/)
![image](https://cloud.githubusercontent.com/assets/8121621/22097737/99d4f126-de5d-11e6-94ed-6e24a4f81c90.png)比如现在现在选择了01-01至01-03
而输出的时间戳01-03的时间戳不应该是再加3600*24-1么？这样才更合理，不然理论上上输出的其实是01 02两天 不包含03.
![image](https://cloud.githubusercontent.com/assets/8121621/22097802/f7691a56-de5d-11e6-80a8-d687f2cc3149.png)

**Comment by jikkai** [comment]
感觉这个需求感觉也不合理，如果要的是`new Date(2017, 1, 2, 23, 59, 59, 999)`这样的时间呢，3600 * 24 - 1 不单满足不了还把问题搞复杂了

**Comment by PanJiaChen** [comment]
这是日期选择器，又不是time选择器哪来的这种时间。。。。。

**Comment by jikkai** [comment]
我想表达的是单纯地 -1s 出来的结果不是一天最后的一个时间戳

**Comment by PanJiaChen** [comment]
可能是不合理，但核心点是现在范围选择，包头不包尾，明显是不合理的

**Comment by jikkai** [comment]
还有一种情况是我就是要的结尾全天，不包尾的话也会让问题变得更复杂。现在的这种状况比较折中，用户自行处理一下能符合各种需求。如果单纯地定了结尾一个点都有可能会让各种定制化需求变得难以处理。

再有一点就是考虑到现在已经有些用了这个组件的产品在生产上跑了，贸然改掉造成的breaking changes影响比较大。

上面是我的个人观点，仅供参考

**Comment by gclsoft** [comment]
@jikkai 加个参数,向下兼容

**Comment by gclsoft** [comment]
@PanJiaChen 怎么解决呢?

**Comment by gclsoft** [comment]
:default-time="['00:00:00', '23:59:59']"

**Comment by XueMary** [comment]
> 这是日期选择器，又不是time选择器哪来的这种时间。。。。。

按你这么说, 这个时间选择期表现是不带时分秒的, 也就是 2017-01-01, 拿这个 进 new Data就是这个数有问题吗
