### ISSUE TITLE
el-select 在 multiple 模式下 开启 disable 还是可以输入和选择

### ISSUE THREAD

**Issue by Kaijun** [ElemeFE/element#2528]
### ElementUI version
1.1.5

### OS/Browers version
macOS/Chrome 53 

### Vue version
newest

### Reproduction Link
http://jsfiddle.net/2vx54vcx/

### Steps to reproduce
el-select 在 multiple 模式下 开启 disable 还是可以输入和选择

注意点击 input 主题确实看起来像是已经被 disabled 了

但是点击input前部分，出现 input cursor 后，可以开始点击输入/选择

![image](https://cloud.githubusercontent.com/assets/1693027/22099595/f414ec5a-de66-11e6-85f6-b0bffa9d567d.png)

### What is Expected?
不能输入/不能选择
### What is actually happening?
能输入/能选择

**Comment by Leopoldthecoder** [comment]
Fixed in #2540
