### ISSUE TITLE
Filterable select doesn't react to onpaste event

### ISSUE THREAD

**Issue by lomereiter** [ElemeFE/element#2529]
### Reproduction Link
https://jsfiddle.net/r1eyryq9/1/

### Steps to reproduce

Copy '1' into the clipboard, paste it into a filterable select using mouse

### What is Expected?

Options should be filtered so that only '1' is shown in the list

### What is actually happening?

The option list remains unfiltered

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/2588/commits/2f4d91568704133ebc39f846c191a83ca0b13321
