### ISSUE TITLE
1.关于组件或资源的分类展示2.Sketch显示的问题

### ISSUE THREAD

**Issue by dianxia52** [ElemeFE/element#2532]
1.关于目前展示的组件或资源内容,希望可以根据不同端区分展示,如移动端(APP/H5)或PC端.
2.Sketch显示的问题
**ElementUI version**

1.3

**OS/Sketch version**

macOS/Sketch41.2

**Steps to reproduce**

按钮相关的素材展示,文字显示都换行了

**What is actually happening?**

不换行

**Comment by jikkai** [comment]
element的组件是针对pc端的，不能根据客户端归纳分类吧 🤔

**Comment by Leopoldthecoder** [comment]
我们会反馈给设计师。

**Comment by dianxia52** [comment]
非常感谢...
因为这边工作中涉及到移动端和PC端都会有,所以会有关注 不同端需求,如果不同端都会有设计标准的话帮助会很大.
只是一个不成熟的想法.

非常感谢
