### ISSUE TITLE
【BUG】表单验证，required:true在input-number上无效

### ISSUE THREAD

**Issue by jstdoit** [ElemeFE/element#2534]
在使用`form`的表单验证功能时，将`{required: true, message: '请选择类型', trigger: 'change'}`验证规则应用于`el-input-number`及`el-select`的`value`为整数时，无论是否填值或者选择，该规则均验证无法通过。
![image](https://cloud.githubusercontent.com/assets/1089041/22116692/4b91a226-deac-11e6-809e-11e86d54b109.png)

**Comment by jikkai** [comment]
默认验证的type为string，`el-input-number`的值为number

**Comment by jstdoit** [comment]
@jikkai 那有什么办法处理一下吗？

**Comment by jikkai** [comment]
设置正确的type即可，参考https://github.com/yiminghe/async-validator#type

**Comment by Leopoldthecoder** [comment]
验证规则里加上 `type: 'number'`
