### ISSUE TITLE
Is there an easy way to use utils/date.js helpers with current locale

### ISSUE THREAD

**Issue by purepear** [ElemeFE/element#2535]
I don't want to add moment.js or other libs for simple date parse/format if i already have one in Element..

So i'm able to load it `import dateUtil from 'element-ui/src/utils/date'` but it's not using the locale/i18n. It defaults to english

**Comment by purepear** [comment]
I guess i'm loading it from src.. which means i'm loading it twice... is it exposed somewhere on the compiled build?

**Comment by purepear** [comment]
Well.. i did a quick search in src and... i don't think it's exposed anywhere..
So.. that's becoming more of a question/suggestion to expose it if you think it's worth it..
I'll probably end up adding 100kb because of moment.js for now

**Comment by QingWei-Li** [comment]
`date` helper not depend on `locale/i18n `. You should load it from `element-ui/lib/utils/date`.
