### ISSUE TITLE
Autocomplete input view turns into activation view

### ISSUE THREAD

**Issue by jbergstroem** [ElemeFE/element#2537]
### ElementUI version
1.1.5

### OS/Browers version
macOS 10.2/Safari 10

### Vue version
Part of your documentation: http://element.eleme.io/#/en-US/component/input#autocomplete

### Reproduction Link
![kapture 2017-01-19 at 15 15 43](https://cloud.githubusercontent.com/assets/176984/22119417/516e6d3e-de5a-11e6-9f60-e386b6a86651.gif)

### Steps to reproduce
1. enter input
2. remove input
3. dropdown now shows; acts like an 'activation' input from here on.

### What is Expected?
should only show dropdown on character input.

### What is actually happening?
shows dropdown on activation/focus

**Comment by Leopoldthecoder** [comment]
Fixed in #2674
