### ISSUE TITLE
DatePicker 日期选择器赋值出错问题

### ISSUE THREAD

**Issue by schwann168** [ElemeFE/element#2538]
### ElementUI version
1.1.5

### Vue version
2.1.7

### Reproduction Link
http://jsfiddle.net/vcgftLvn/26/

### What is actually happening?
更新 1.1.5 后，对日期范围选择控件`DatePicker`进行赋值时，出现格式错误：`Error: Invalid Date in fecha.format` ，赋值方式见上面代码链接，此前是可以直接通过 `[ '2017-01-20', '2017-01-22' ]` 这样的日期区间进行赋值。

**Comment by Leopoldthecoder** [comment]
Fixed in #2539
