### ISSUE TITLE
 error  in ./~/element-ui/lib/theme-default/index.css  Module build failed: Unknown word (5:1)

### ISSUE THREAD

**Issue by dawniii** [ElemeFE/element#2541]
`import 'element-ui/lib/theme-default/index.css'`
这一行报错，但是我已经有cssloader了。我是用的vue-cli构建项目，webpack里按照文档配置了 css file loader等。
下面是错误信息：

         ERROR  Failed to compile with 1 errors

         error  in ./~/element-ui/lib/theme-default/index.css

         Module build failed: Unknown word (5:1)

         3 | // load the styles
         4 | var content = require("!!./../../../css-loader/index.js!./index.css");
        > 5 | if(typeof content === 'string') content = [[module.id, content, '']];
         | ^
        6 | // add the styles to the DOM
        7 | var update = require("!./../../../style-loader/addStyles.js")(content, {});
        8 | if(content.locals) module.exports = content.locals;
  

        @ ./~/element-ui/lib/theme-default/index.css 4:14-133 13:2-17:4 14:20-139

**Comment by dawniii** [comment]
问题解决了，less loader里面包含了css loader。等于说加载了两遍

**Comment by pilsoftTeam** [comment]
Could u give the solution to this in english  ? The translation from google doesnt make any sense. Thank u

**Comment by rail44** [comment]
@pilsoftTeam 
I faced same error when I tried to integrate element-ui into project that generated with `vue init webpack ...`
As installation tutorial, I've added configration to `build/webpack.base.conf.js` for working style-loader and css-loader.
However, there is already style-loader setting within `build/utils.js`.
If your issue is occurring by what same of me, you should remove style-loader confguration from `bulid/webpack.base.conf.js` .

**Comment by zhlella** [comment]
我也出现了类似的问题，但是我没有less呀，不知道怎么解决

 error  in ./~/._element-ui@1.3.5@element-ui/lib/theme-default/index.css

Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../._css-loader@0.28.4@css-loader/index.js?
{\"minimize\":false,\"sourceMap\":false}!./index.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../../._vue-style-loader@2.0.5@vue-style-loader/
lib/addStylesClient.js")("6b95fb7d", content, false);

 @ ./~/._element-ui@1.3.5@element-ui/lib/theme-default/index.css 4:14-206 18:2-2
2:4 19:20-212
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

**Comment by bigfacecatkivi** [comment]
我也遇到了同样的问题，你是如何解决的呀

**Comment by bigfacecatkivi** [comment]
我也遇到了同样的问题，你是如何解决的呀？
我最后采用的方法是在index.html里通过这样的方式引入
<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css">
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
还是没办法在main.js里面import

**Comment by darcymzsun** [comment]
是因为新版的vue-loader自带了css-loader,所以把webpack config 里.css的loader删除掉就可以了

**Comment by jstavanja** [comment]
If you encounter an unknown character at 0:1 error, try adding a url-loader to your webpack config.

**Comment by abou7mied** [comment]
I faced the same problem after upgrading from 1.3.7 to 2.0.8. The problem was in **.babelrc** property **styleLibraryName** was **theme-default** I changed it to **theme-chalk**

**Comment by Lqshiluo** [comment]
webpack.dev.conf.js中有
```
module: {
    rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap, usePostCSS: true })
  }
```
把配置项usePostCSS改成false就不会报错了

**Comment by lihancong** [comment]
> Could u give the solution to this in english ? The translation from google doesnt make any sense. Thank u

change：
import 'element-ui/lib/theme-default/index.css'
to
import 'element-ui/lib/theme-chalk/index.css';

**Comment by gyt95** [comment]
webpack.base.conf.js


  //    {
    //      test: /\.css$/,
    //      loader: "style-loader!css-loader"
    //    },
      {
        test: /\.less$/,
        loader: 'style!css!less'
      },

**Comment by MrFive5555** [comment]
vue3.0已经移除webpack了,但是还有这个问题
