### ISSUE TITLE
周日期选择器的相关问题

### ISSUE THREAD

**Issue by Newcandy** [ElemeFE/element#2543]
### ElementUI version
1.1.5及以下。

### What is Expected?
每年的第一周，年数几乎不正确。
另外周日期选择器能支持像日期范围的格式 yyyy-MM-dd至yyyy-MM-dd 吗？
另外日期选择器或者select等能设置默认值吗？

### What is actually happening?
![每年的第一周，年数几乎不正确](https://cloud.githubusercontent.com/assets/9457798/22138647/b7387f52-df1c-11e6-8a71-0450a2fac815.png)

**Comment by QingWei-Li** [comment]
看了下，周的结果都是对的。

**Comment by Newcandy** [comment]
不应该是2014年第53周或者2015年的第1周么。。。
![image](https://cloud.githubusercontent.com/assets/9457798/22194099/29e6e2ae-e17b-11e6-8b9d-31284bbde8e5.png)

**Comment by csvwolf** [comment]
PR earlier than 2018, closed.
