### ISSUE TITLE
All elements should emit focus and blur events

### ISSUE THREAD

**Issue by groenroos** [ElemeFE/element#2544]
### ElementUI version
1.1.5

### OS/Browser version
All

### Vue version
2.1.0

### Reproduction Link
N/A

### Steps to reproduce
N/A

### What is Expected?
All of the elements should emit `focus` and `blur` events the same way as a native control would.

### What is actually happening?
Currently, no events are emitted that would reliably determine when the controls are focused or blurred. The native `focus` and `blur` events are not applicable to all elements, as often the component will return a `div` rather than the `input` that would natively emit them.

**Comment by QingWei-Li** [comment]
>In Vue 2.0, adding native event handlers in custom components requires a .native modifier:
>
> ```html
> <my-component @click.native="handleClick">Click Me</my-component>
> ```
> For the sake of usability, we processed Button so it can listen to click events:
> 
> ```html
> <el-button @click="handleButtonClick">Click Me</el-button>
> ```

https://vuejs.org/v2/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on-changed

**Comment by groenroos** [comment]
Yes, but some Element components such as `el-select` do not emit native `focus` or `blur` events;

    <el select @focus.native="handleFocus"></el-select>

This never fires, as the `focus.native` event handler would attach to the root `div` containing the `el-select` component, instead of the `input` nested within.

I'd like some more consistency; I would like for every Element component to handle `focus` and `blur`, and not just the ones where the root is an element that would natively emit these events.

**Comment by mdocter** [comment]
+1 
Another example is the Autocomplete component. Internally it uses a an `el-input` component which fires the `blur` and `focus` events correctly, but the wrapping `el-autocomplete` doesn't pass these event upwards, so I can't catch them.

**Comment by NiltiakSivad** [comment]
Same thing applies to DatePicker and its inner `el-input`

**Comment by groundc** [comment]
+1

**Comment by mccxiv** [comment]
Any clean workaround for responding to `el-autocomplete`'s `focus` and `blur`?

**Comment by groenroos** [comment]
There seems to be some sort of workaround in #3871, but I can't vouch if that'll work for `el-autocomplete`, and it's quite the dirty kludge anyway.

Hope unified `focus` and `blur` event attributes for all elements are on their way soon!

**Comment by luckymore** [comment]
@groenroos  if they are attached to the `root` div, why it still not trigger when I attach `mouseover` to an `el-menu-item` component.

**Comment by csvwolf** [comment]
PR earlier than 2018, closed.
