### ISSUE TITLE
Dialog中select组件第一次点击时下拉框被遮挡

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#2546]
vue:2.1.10
element:1.1.5

![image](https://cloud.githubusercontent.com/assets/23140033/22141662/0aa32bf4-df2e-11e6-980a-3b1c278ce19e.png)

Dialog中select组件第一次点击时下拉框被遮挡，如上图所示，第二次点击后正常，
有时候第一次点击select下拉框也正常。

下拉框数据都是后台获取

**Comment by Leopoldthecoder** [comment]
无法重现，请提供 demo

**Comment by Leopoldthecoder** [comment]
Fixed in #2577

**Comment by HoffyLee** [comment]
@Leopoldthecoder 你好，可以帮忙看一下 #5051 么？

**Comment by Plortinus** [comment]
好像没有解决呢
