### ISSUE TITLE
tabs标签页是否可添加切换方式的选择

### ISSUE THREAD

**Issue by 214132049** [ElemeFE/element#2547]
### ElementUI version

1.1.5
### OS/Browers version

windows/Chrome 54
### Vue version

2.1.6
### What is Expected?
tabs标签页切换，是否考虑加入鼠标移入切换

**Comment by baiyaaaaa** [comment]
这种交互方式估计不会被采纳

**Comment by 214132049** [comment]
hover交互很常见的啊

**Comment by jikkai** [comment]
觉得hover交互挺奇怪的，能讲讲有什么具体场景吗

**Comment by zzzgit** [comment]
以前我做的一个网站，就是hover

**Comment by zzzgit** [comment]
留个接口出来吧，可以配置如何触发默认click触发

**Comment by AboyL** [comment]
http://xinsheng.huawei.com/cn/index/guest.html
华为心声社区的就是hover的 感觉可以提供一个接口出来

**Comment by phping1** [comment]
同求该功能。

**Comment by wgs147** [comment]
同求该功能

**Comment by qurge** [comment]
大佬实现了吗？
