### ISSUE TITLE
[Form] All form elements should have a focus method

### ISSUE THREAD

**Issue by gil0mendes** [ElemeFE/element#2550]
### ElementUI version
1.1.5

### OS/Browers version
All

### Vue version
2.1.8

### Reproduction Link
N/A

### Steps to reproduce
N/A

### What is Expected?

All of the form elements should have a focus method like the way a native control have.

### What is actually happening?

There is no easy way to focus an form component, right now. We need to play around with the `$vnode` like you can see on the following code:

```javascript
this.$refs.descriptionField.$vnode.elm.querySelector('.el-textarea__inner').focus()
```

This could be simpler as:

```javascript
this.$refs.descriptionField.focus()
```

**Comment by richstandbrook** [comment]
Also see #3871

**Comment by baiyaaaaa** [comment]
#5914
