### ISSUE TITLE
[Bug Report] el-table under embed flex layout grew but didn't shrink while resizing browser

### ISSUE THREAD

**Issue by deangoku** [ElemeFE/element#2552]
### ElementUI version
1.1.5

### OS/Browers version
Windows/Chrome 57

### Vue version
2.1.10

### Steps to reproduce
![code](https://cloud.githubusercontent.com/assets/6375486/22171671/fa0f4df4-dfcd-11e6-9a4c-e7afb0570136.png)

### What is Expected?
the way to get el-table work well under embed flex layout

### What is actually happening?
el-table under embed flex layout grew but didn't shrink while resizing browser

*若英语有误，请直接无视*

**Comment by rochdev** [comment]
I'm facing the same problem

**Comment by rochdev** [comment]
`overflow: hidden` on the flex container seems to help from what I could decipher from #2716

**Comment by Leopoldthecoder** [comment]
`overflow: hidden` is the right answer.
