### ISSUE TITLE
Element imports whole VueJS library whenever a module is imported on demand

### ISSUE THREAD

**Issue by Frondor** [ElemeFE/element#2553]
> ![](https://i.gyazo.com/8b610a325d930254914ff555f116c8a0.png)

In my project, I have 2 files, a `vendor.js` with `vue` + `jQuery` and another `home.js` where I'm simply instantiating vue and using the `Dialog` component like `import { Dialog } from 'element-ui'`.

The problem is that if I import `Dialog` component, it also `require`s the whole Vue.js library in `home.js` file.
If I remove it, then there's no problem.

### Vendor.js
```
window.$ = window.jQuery = require('jquery/dist/jquery.slim');
window.Vue = require('vue');
```
### Home.js
```
require('vue-resource');
Vue.http.interceptors.push((request, next) => {
    request.headers.set('X-CSRF-TOKEN', document.getElementsByName('csrf-token')[0].content);
    next();
});

   const services = new Vue({
       el: '#services',
       components: {
           'feature': require('./components/Feature.vue')
       }
   });
});
```
### /components/Feature.vue
```
<template>
<el-select> bla bla bla </el-select>
</template>
<script>
import { Select } from 'element-ui';

export default {
    props: ['service'],
    components: {
        'el-select': Select
    }
}
</script>
```

My build script comes from [laravel-elixir-vue-2](https://github.com/vuejs/laravel-elixir-vue-2) and my `webpack.config.js` file looks like:
```
var webpack = require("webpack");
const path = require('path');

module.exports = {
    resolveLoader: {
        root: path.join(__dirname, 'node_modules'),
    },
    module: {
        loaders: [
            {
                test: /\.css$/,
                loader: 'style!css'
            }
        ]
    },
	plugins: [
		new webpack.NormalModuleReplacementPlugin(/element-ui[\/\\]lib[\/\\]locale[\/\\]lang[\/\\]zh-CN/, 'element-ui/lib/locale/lang/es')
	]
};
```
--------------------------------
--------------------------------
I'm pretty new at webpack, but I've also noticed that whenever I import a module from `element-ui` it adds an insane amount of modules into the bundled file:
#### Without including `import { Button } from 'element-ui'`
![](https://i.gyazo.com/31e3bbf286489b036fcf2ea73ad7a94f.png)
#### With `import { Button } from 'element-ui'`
![](https://i.gyazo.com/d14d7ddcbdc27e6cece918f2e110e069.png)

This has probably an obvious explanation, I'm more concerned about fixing the double `vue` importing.

**Comment by QingWei-Li** [comment]
Try webpack commonsChunk
https://webpack.js.org/guides/code-splitting-libraries/#commonschunkplugin

**Comment by tripflex** [comment]
This creates all kinds of problems for me when I can't control whether a site is globally including Vue or not.  Not sure why they never gave us a way to disable this. 

Either way I know this is old (im using on an old project), but if anybody for some weird reason needs a solution, I added this to my webpack build process to strip this out of the minified build file.  Not worth spending the time trying to get all dependencies from this old project to work correctly (by just including the source):

```javascript
class RemoveUnwantedCodePlugin {
	apply( compiler ) {
		compiler.hooks.emit.tapAsync( 'RemoveUnwantedCodePlugin', ( compilation, callback ) => {
			// Define the files to be altered
			const filesToChange = ['some_file_element_ui_is_included_in.min.js'];

			filesToChange.forEach( ( file ) => {
				if ( compilation.assets[ file ] ) {
					let contents = compilation.assets[ file ].source();

					contents = contents.replace( /"undefined" != typeof window && window.Vue && .+\(window.Vue\);/g, '' );
					// Update the asset with the modified content
					compilation.assets[ file ] = {
						source: () => contents,
						size  : () => contents.length
					};
				}
			} );

			callback();
		} );
	}
}
```

then just add it as a plugin:

```
// ... other parts of your webpack config

plugins: [
  // ... other plugins
  new RemoveUnwantedCodePlugin(),
  // ... other plugins
],

// ... rest of your webpack config
```
