### ISSUE TITLE
Table在macOS的Safari浏览器中表头和表体不对齐

### ISSUE THREAD

**Issue by akaylh** [ElemeFE/element#2554]
### ElementUI version

官方示例

### OS/Browers version

macOS ，safari 10.0.2

**Comment by jikkai** [comment]
http://element.eleme.io/#/zh-CN/component/table#gu-ding-lie

是说这种情况吗？

![untitled](https://cloud.githubusercontent.com/assets/14025786/22173734/9cd060ae-e006-11e6-8020-a76cf1b7667f.gif)

**Comment by akaylh** [comment]
@jikkai 是的

**Comment by akaylh** [comment]
还有一种情况，没能重现，就是“筛选”和“自定义模板列”那两个示例，不知道是没刷新好，还是什么，出现过几次表头和表体不对齐的情况，但我刚刚再看官方示例又不会了。。。

**Comment by QingWei-Li** [comment]
哪里没对齐了，如果说是内容和表头不同步，那没办法。头部滚动是用 js 计算的。
