### ISSUE TITLE
Table 组件内存泄漏

### ISSUE THREAD

**Issue by whwei** [ElemeFE/element#2555]
### ElementUI version
1.1.5

### OS/Browers version
macOS/Chrome 55

### Vue version
2.1.10

### Reproduction Link
[https://github.com/whwei/element-ui-table-component-memory-leak-demo](https://github.com/whwei/element-ui-table-component-memory-leak-demo)

### Steps to reproduce
1. 打开 `index.html`，页面渲染第一个table
1. 点击 `toggle` 按钮显示第二个空的table
1. 再次点击 `toggle` 按钮重新显示第一个table
1. repeat...

### What is Expected?
内存在适当的时候应该被释放

### What is actually happening?
每次toggle，内存占用持续上升，最后导致页面变慢卡死

**Comment by QingWei-Li** [comment]
没有遇到卡死的情况。v-if 就是会销毁组件。

**Comment by whwei** [comment]
每次销毁后可以在内存快照里看到大量的dom元素没有被释放

**Comment by yeyuqiudeng** [comment]
@QingWei-Li 请问一下，这个有计划什么时候解决吗？

**Comment by QingWei-Li** [comment]
@yeyuqiudeng 无法复现 😂 不知从何下手啊

**Comment by a7270102** [comment]
其他组件也要去看一下，有内存泄漏； 很明显，同一个页面渲染，使用原生的，内存会被释放，使用el组件，会有已经被分离了dom的节点仍然占据内存的情况；
测试场景：
在路由跳转切换视图A,B。 B上直接给el组件渲染，返回A，会有内存占用；使用原生html渲染，返回A内存不会被占用

**Comment by a7270102** [comment]
我也碰到了组件泄漏的问题;场景： A,B页面 通过路由切换视图， 如A-->B.   B页面上使用原生html 构造template，再返回A后，经过CG，内存会和刚开始在A时一样； 若使用EL组件 构造template,返回A后，内存不会释放，经过谷歌的开发者工具查看内存快照对比，很明显有dom未被释放刚好对应el组件； 建议去尝试复现一下
