### ISSUE TITLE
demo 页面404

### ISSUE THREAD

**Issue by limichange** [ElemeFE/element#2557]
> https://github.com/ElemeFE/element/blob/dev/packages/tabs/README.md

http://element-component.github.io/element-tabs

**Comment by Leopoldthecoder** [comment]
地址 deprecated，访问这个链接：http://element.eleme.io/#/zh-CN/component/tabs

**Comment by limichange** [comment]
@Leopoldthecoder 需要帮忙更新吗？

**Comment by Leopoldthecoder** [comment]
谢谢，相关 PR 已经提了：#2345

**Comment by limichange** [comment]
💯
