### ISSUE TITLE
window7 运行 npm run bootstrap,报错，不能运行

### ISSUE THREAD

**Issue by wgq837051** [ElemeFE/element#256]
window7 运行 npm run bootstrap,报错，不能运行, Failed at the element-ui@1.0.0-rc.5 bootstrap script 'npm i && lerna bootstrap'.

**Comment by QingWei-Li** [comment]
请贴出完整的 log

**Comment by wgq837051** [comment]
这是npm-debug  0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\wangguangqing\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@3.10.8
3 info using node@v4.4.7
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle element-ui@1.0.0-rc.5~prebootstrap: element-ui@1.0.0-rc.5
6 silly lifecycle element-ui@1.0.0-rc.5~prebootstrap: no script for prebootstrap, continuing
7 info lifecycle element-ui@1.0.0-rc.5~bootstrap: element-ui@1.0.0-rc.5
8 verbose lifecycle element-ui@1.0.0-rc.5~bootstrap: unsafe-perm in lifecycle true
9 verbose lifecycle element-ui@1.0.0-rc.5~bootstrap: PATH: C:\Users\wangguangqing\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\github\element-master\element-master\node_modules\.bin;C:\Users\wangguangqing\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\bin;C:\Users\wangguangqing\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Java\jdk1.7.0_06\bin;C:\Program Files\Java\jdk1.7.0_06\jre\bin;D:\Program Files\nodejs;C:\Users\wangguangqing\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle element-ui@1.0.0-rc.5~bootstrap: CWD: E:\github\element-master\element-master
11 silly lifecycle element-ui@1.0.0-rc.5~bootstrap: Args: [ '/d /s /c', 'npm i && lerna bootstrap' ]
12 silly lifecycle element-ui@1.0.0-rc.5~bootstrap: Returned: code: 1  signal: null
13 info lifecycle element-ui@1.0.0-rc.5~bootstrap: Failed to exec bootstrap script
14 verbose stack Error: element-ui@1.0.0-rc.5 bootstrap: `npm i && lerna bootstrap`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\wangguangqing\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\wangguangqing\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid element-ui@1.0.0-rc.5
16 verbose cwd E:\github\element-master\element-master
17 error Windows_NT 6.1.7601
18 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wangguangqing\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
19 error node v4.4.7
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error element-ui@1.0.0-rc.5 bootstrap: `npm i && lerna bootstrap`
22 error Exit status 1
23 error Failed at the element-ui@1.0.0-rc.5 bootstrap script 'npm i && lerna bootstrap'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the element-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm i && lerna bootstrap
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs element-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls element-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by QingWei-Li** [comment]
清下 npm 缓存
```shell
npm cache clean
```

**Comment by QingWei-Li** [comment]
有解决问题么
如果没有的话请贴出运行时终端里的信息

**Comment by wgq837051** [comment]
又出现新问题了，
![image](https://cloud.githubusercontent.com/assets/6071212/19295872/083dc09e-906a-11e6-9c74-dfdc4f796b7b.png)
![image](https://cloud.githubusercontent.com/assets/6071212/19295876/0faedb06-906a-11e6-9f08-b7cd21b7924a.png)
不知是不是网络问题。

**Comment by QingWei-Li** [comment]
网络问题

你可以试试 cnpm, npminstall, yarn 等第三方模块管理工具来安装依赖

**Comment by Mwuxiaoyu** [comment]
请问这种问题如何解决？
12 info lifecycle @0.1.13~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: @0.1.13 bootstrap: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @0.1.13
15 verbose cwd /home/wxy/BlockChain/remix
16 verbose Linux 4.15.0-52-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @0.1.13 bootstrap: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the @0.1.13 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
