### ISSUE TITLE
希望table组件提供个方法，当resize时，可以返回resize后列的宽度

### ISSUE THREAD

**Issue by yeyuqiudeng** [ElemeFE/element#2560]
### ElementUI version
1.1.5

### Vue version
2.1.10

### What is Expected?
希望resize后将对应列的宽度返回，以便保存列宽度信息，下次渲染时可以利用保存的信息设置宽度。

**Comment by Leopoldthecoder** [comment]
建议自己通过访问 DOM 来解决这个需求。
