### ISSUE TITLE
Tabs动态增加关闭出现 BUG

### ISSUE THREAD

**Issue by zhguokai** [ElemeFE/element#2562]
### ElementUI version
 1.1.5 

### OS/Browers version
 macOS/Chrome 53 

### Vue version
  2.1.10 

Reproduction Link

http://jsfiddle.net/wcdmh12w/1/

### Steps to reproduce
    
   1. 点击 add 按钮，随机增加 Tab

   2. 点击 tab 的关闭按钮

### What is Expected?
 
   1.点击一次关闭一条 tab，tab 数据清除一条 

### What is actually happening?
   1.实际上 点击关闭时，一资关闭多个 tab，数据清除一条，即 tab 展现数 和 实际数据中不一致

**Comment by emf1002** [comment]
我也发现了，tabs内部自己维护了panes，作为tabs的子组件el-tab-pane，在mounted的时候会把自己插入到父组件tabs.panes数组内，违背了单向数据流，最好应该开放给使用者根据removeTab事件维护tabs

**Comment by baiyaaaaa** [comment]
@emf1002 是的，1.2 会修正这个问题

**Comment by zhguokai** [comment]
1.2 大约什么时间发布
