### ISSUE TITLE
table组件请求能支持固定表尾

### ISSUE THREAD

**Issue by xiongsongsong** [ElemeFE/element#2563]
### ElementUI version
1.1.5

目前Table组件支持固定表头，但不支持固定表尾。
目前有大量需求，需要固定合计行。
![image](https://cloud.githubusercontent.com/assets/342509/22179709/8bf72610-e096-11e6-83a0-bc54fa641930.png)

希望增加支持，感谢。

**Comment by QingWei-Li** [comment]
Duplicate of #1307
