### ISSUE TITLE
能不能加上modal窗口的条件判断钩子  return false的时候就不关闭

### ISSUE THREAD

**Issue by chunmu** [ElemeFE/element#2564]
有需求说是提醒用户是否保存数据  应该要有一个钩子来确定是否关闭modal，如果条件不满足 return false阻止modal关闭  试过close方法  但是它们似乎并没有拦截功能

**Comment by Leopoldthecoder** [comment]
哪个组件？

**Comment by chunmu** [comment]
el-dialog

**Comment by Leopoldthecoder** [comment]
目前可以在 `footer` slot 里的按钮上做这件事，同时禁掉 `show-close` 和 `close-on-click-modal`，防止用户通过点击按钮之外的方式关闭 Dialog。后面会考虑加这样一个钩子。

**Comment by chunmu** [comment]
好的  谢谢
