### ISSUE TITLE
可关闭的标签页tab-remove事件

### ISSUE THREAD

**Issue by xp44mm** [ElemeFE/element#2565]
element实现了可关闭的标签，但是当关闭标签后却没有删除标签对应的数据，需要自己定义删除事件。

比如我想实现这样功能：关闭某标签，删除绑定数组或对象tabs对应的这个标签。这时，无法利用输入参数tab，只能用index，笨方法如下实现：
`<el-tab-pane v-for="(item, index) in tabs" :name="item.name">
            <span slot="label">{{item.title}}<button v-on:click="tabs.splice(index, 1)">X</button></span>`

tab-remove事件，无法使用，因为它只有一个输入参数表示被删除的标签 tab 实例。但是却没有可选的key参数，和可选的index参数。这和vue.js的列表渲染行为不一致。其他导航控件可以举一反三。

**Comment by baiyaaaaa** [comment]
1.2 会修正这个问题，相关pr已提
