### ISSUE TITLE
datepicker选择日期范围问题

### ISSUE THREAD

**Issue by wangyahui6** [ElemeFE/element#2568]
datepicker选择日期范围中的字符默认为-，比如2016-12-26 - 2017-01-10，这个和日期本什么的-冲突，有没有考虑这个字符设置成可配置的

**Comment by PanJiaChen** [comment]
想要自定义，可以自己监听@change事件，包装成想要的数据格式

**Comment by QingWei-Li** [comment]
为啥会冲突，返回的是数据不是一个数组么

**Comment by smile33** [comment]
日期选项，当文本框editable禁止时，日期改变时能否有监听事件？
目前，鼠标移动到日期icon时，还未更改日期，却会触发watch事件；
能否有一个参数可以不启用清除按钮功能（clearable是决定显不显示，但功能依然有效）

**Comment by wangyahui6** [comment]
2016-12-26 - 2017-01-10,是说间隔字符-，和日期的-使同一个字符，容易造成误解
