### ISSUE TITLE
el-dialog  嵌入了 el-slider 

### ISSUE THREAD

**Issue by captainIT** [ElemeFE/element#2573]
### ElementUI version
"version": "1.1.5"

### OS/Browers version
Chrome 53

### Vue version
2.1.0 

### 
我在el-dialog  中嵌入了 el-slider 
然后问题就是当  滑块hover  的时候  el-dialog 的title 和确定和取消按钮的文字 都发生闪动。。

**Comment by erguotou520** [comment]
应该跟我提的是一个原因
#2641

**Comment by Leopoldthecoder** [comment]
@erguotou520 是，但是原因还没找到= =

**Comment by erguotou520** [comment]
讲真，我还是建议使用元素模拟箭头...

**Comment by Leopoldthecoder** [comment]
进展会在 #2461 中更新，这个 issue 先关掉了。
