### ISSUE TITLE
el-table-column 的 :formatter 没有「响应式」

### ISSUE THREAD

**Issue by zhenyong** [ElemeFE/element#2578]
### ElementUI version
1.1.5

### OS/Browers version
 macOS/Chrome 53

### Vue version
2.1.0 

### Reproduction Link
http://jsfiddle.net/feipigzi/0mjz6v8r/1/

### Steps to reproduce
初次渲染后，等两秒（计时器）

### What is Expected?
 formatter 改变后，第一列和第二列的单元格值分别为 'date value 2' 和 'date value 2'

### What is actually happening?
 formatter 改变后，单元格的值无变化

**Comment by QingWei-Li** [comment]
因为你没加 key
http://jsfiddle.net/0mjz6v8r/2/

**Comment by zhenyong** [comment]
@QingWei-Li 

在你的基础上修改 `:key="col"` --> `:key="col.prop"`

http://jsfiddle.net/0mjz6v8r/3/

前两列的单元格数据没有更新，这个情况是合理的吗？
