### ISSUE TITLE
router 切换路由 table组件 body内的宽度 变化的问题

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#258]
如图切换路由时候 table的内容宽度会变化一下
![table](https://cloud.githubusercontent.com/assets/1932350/19210364/acb31e90-8d53-11e6-9119-86670eab5005.gif)

table代码
```javascript```
<div class="el-row">
   <div class="el-col-24">
       <el-table :data="tableData" style="width: 100%">
           <el-table-column  property="date"  label="日期"  width="180"> </el-table-column>
           <el-table-column   property="name"   label="姓名"  width="180"></el-table-column>
           <el-table-column   property="address"  label="地址"></el-table-column>
      </el-table>
  </div>
</div>
```
 路由
```javascript```
<div class="page-container">
   <transition name="fade" mode="out-in">
        <router-view class="view"></router-view>
   </transition>
</div>
```
transition css
```css```
  .fade-enter-active,
 .fade-leave-active {
     transition: all .3s ease;
 }
 
 .fade-enter,
 .fade-leave-active {
     opacity: 0;
 }

```

### ElementUI version
<!-- 1.0.0-rc.5 -->
1.0.0-rc.5

### OS/Browers version
<!-- win10/Chrome 52.0.2743.82 -->
win10/Chrome 52.0.2743.82

### Vue version
<!-- 2.0.0-rc.4 -->
 2.0.0-rc.4 
### Vue-router version
<!-- 2.0.0-rc.5 -->
2.0.0-rc.5

### Reproduction Link
<!-- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug. -->
<!-- https://codepen.io/anon/pen/ozYpNA -->
<!-- https://jsfiddle.net/gmve9d3p/ -->
https://yelingfeng.github.io/v-elementui-quickstart 
### Steps to reproduce

### What is Expected?

### What is actually happening?

**Comment by furybean** [comment]
#363
