### ISSUE TITLE
Maxthon内Popover弹出框hover时无法显示和select箭头图标样式兼容问题

### ISSUE THREAD

**Issue by guyuesha** [ElemeFE/element#2580]
### Reproduction Link
http://element.eleme.io/#/zh-CN/component/popover   
http://element.eleme.io/#/zh-CN/component/select        

### Steps to reproduce
Popover弹出框hover时  
select箭头图标样式

### What is Expected?
Popover弹出框hover时 正确显示弹出框
select箭头图标正常显示

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/15613740/22195485/36afe7e4-e183-11e6-9174-b147e5771aef.png)
![image](https://cloud.githubusercontent.com/assets/15613740/22195502/50e93d18-e183-11e6-8108-b0bca7abbf6c.png)

**Comment by Leopoldthecoder** [comment]
不保证对 Maxthon 的兼容。
