### ISSUE TITLE
对话框内嵌的表格无法拖动列宽

### ISSUE THREAD

**Issue by xp44mm** [ElemeFE/element#2582]
如题，在帮助文档：Others->Dialog->打开嵌套表单的 Dialog这个例子里面，表格的列宽是无法通过拖动调整的。

**Comment by Leopoldthecoder** [comment]
没太明白，你是想打到什么效果？

**Comment by xp44mm** [comment]
表格列宽是可以通过拖动改变的，对话框内嵌套的表格列宽应该也是可以拖动改变的，但是示例中却不能改变表格列宽。

**Comment by erguotou520** [comment]
因为列宽能调的前提是得有边框 `border`属性，而demo里没有，所以不能拖动
issue可关

**Comment by xp44mm** [comment]
知道了
