### ISSUE TITLE
Select组件远程搜索情况下复制到输入框会出现被遮挡的bug

### ISSUE THREAD

**Issue by zhangchen91** [ElemeFE/element#2583]
### ElementUI version
1.1.5

### OS/Browers version
macOS/Chrome 55.0.2883.95 (64-bit) 

### Vue version
2.1.8

### Steps to reproduce
select的组件远程搜索如果input用复制的方式填入值，会被遮挡
### What is Expected?
复制到输入框时input表现正常
### What is actually happening?
![default](https://cloud.githubusercontent.com/assets/1012304/22196132/9234d18a-e186-11e6-9d4e-35d763e6499f.png)

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/2588/commits/2f4d91568704133ebc39f846c191a83ca0b13321
