### ISSUE TITLE
Table 表格   1.能够新增对应排序数据数组 2.函数事件返回值能够新增属性，返回该属性值

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#2585]
关于Table 表格希望新增的几个功能：
1.目前Table Attributes只有一个属性data作为显示的数据显示，排序的时候也是根据data这个数组的数值来排序。但是一般业务显示的数据和实际排序的数据会存在不一致（例如显示的是字符串，排序时是数值），显示数据与排序数据能否区分。
可以类似angular 的smart-table：https://lorenzofox3.github.io/smart-table-website/#section-sort
2.目前对应列内容的字段名prop，都只能传该列单元格的显示值，函数事件返回值都是prop的值，如何附带一些别的信息，例如单元格的状态值之类的

**Comment by Leopoldthecoder** [comment]
- 排序不是只能根据显示的数据，使用 `sort-method` 可以自定义任意的排序逻辑：http://jsfiddle.net/1f512js6/
- 参数 `row` 返回的是整行数据，不只是显示值。

**Comment by kunKun-tx** [comment]
@Leopoldthecoder 可否把`sort-method`这个更新到文档里？文档里没看到，我是搜索了才找到这边的。

@smile33 配合`:formatter` 使用就可以解决显示数据和排序数据不一致的问题，我这个简单的formatter试验下来不影响排序结果  
````
    currencyFormatter: function (row, column) {
      return '$' + Intl.NumberFormat('en-US').format(row.Budget)
    },
````

**Comment by Leopoldthecoder** [comment]
@kunKun-tx 文档里有 `sort-method`，在下方的 API 表格里。

**Comment by kunKun-tx** [comment]
嗯 我看漏了，页面上确实已经有了。

**Comment by 1008611** [comment]
@smile33 i know you mean  , and meet the same problem,just like this
 [http://jsfiddle.net/C__C/hhv54tcp/](url) 
i can not get the item which i want sort by 
@kunKun-tx
