### ISSUE TITLE
DatePicker 日期选择器 1.鼠标移动到日期icon时，还未更改日期，却会触发watch事件 2.能否新增不启用清除功能参数

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#2586]
日期选项，当文本框editable禁止时，日期改变时能否有监听事件？
目前，鼠标移动到日期icon时，还未更改日期，却会触发watch事件；
能否有一个参数可以不启用清除按钮功能（clearable是决定显不显示，但功能依然有效）

**Comment by QingWei-Li** [comment]
1. 有啊，`@input` 和 `@change` 都能用啊
2. 没遇到过，可否给个 demo？ http://jsfiddle.net/cinwell_li/r7anjzn7/

**Comment by smile33** [comment]
第二点，vue版本从2.0.1升级到2.2.4后，就可以了
