### ISSUE TITLE
Table单选如何设置选中项？

### ISSUE THREAD

**Issue by shennwei** [ElemeFE/element#2590]
### ElementUI version

1.1.6
### OS/Browers version

win10/Chrome55
### Vue version

2.1.10
### What is Expected?
Table单选如何设置和获取选中项？

**Comment by erguotou520** [comment]
文档中有写哦 `toggleRowSelection`方法，注意第一个参数为`row`

**Comment by shennwei** [comment]
谢谢，但是如果我直接使用而不是再写成组件的话，获取不到refs，这样就无法调用这个方法了

**Comment by erguotou520** [comment]
什么叫直接使用而不写成组件？

**Comment by shennwei** [comment]
非常感谢，上面的回复请无视，是我没有完全搞懂Vue的子组件索引
