### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by xereda** [ElemeFE/element#2594]
### ElementUI version
1.1.6

### OS/Browers version
macOS Sierra 10.12.2 (16C67) / Chrome Versão 55.0.2883.95 (64-bit)

### Vue version
2.1.0

### Steps to reproduce
Set the location for my plugin instance as "pt-br".

### What is Expected?
Correct translation in field value.

### What is actually happening?

----

Internationalization

Set the location for my plugin instance as "pt-br". However, it does not work on return of value.

Note the content below:

```

  import Vue from 'vue'
  import ElementUI from 'element-ui'
  import locale from 'element-ui/lib/locale/lang/pt-br'
  Vue.use(ElementUI, { locale })

```

![captura de tela 2017-01-24 as 11 37 05](https://cloud.githubusercontent.com/assets/14337850/22250969/38ee1690-e230-11e6-9ea6-f7f000dd8e9d.png)

**Comment by Leopoldthecoder** [comment]
What is the correct translation? Could you paste your code here?
