### ISSUE TITLE
this.$message('hi') 出错了

### ISSUE THREAD

**Issue by cmzz** [ElemeFE/element#2595]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0

引用的代码:
    import Vue from 'vue'
    import Resource from 'vue-resource'
    import Router from 'vue-router'
    import store from './vuex/store'

    import ElementUI from 'element-ui'
    import 'element-ui/lib/theme-default/index.css'

    import App from './App'
    import routes from './routes'

    Vue.use(ElementUI)
    Vue.use(Router)

    const router = new Router({
      scrollBehavior: () => ({ y: 0 }),
      routes
    })

    new Vue({
      router,
      store,
      ...App
    }).$mount('#app')

当调用:
`this.$message('hi')`
出错了。

(program):509 [Vue warn]: Error when rendering root instance: warn @ (program):509
(program):423 TypeError: _vm._v is not a function(…)

**Comment by cmzz** [comment]
"element-ui": "^1.1.6",
    "vue": "2.1.6",
    "vue-electron": "^1.0.0",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.1.0",
    "vue-template-compiler": "^2.1.4",

使用这个半杯配置， 搞定了，指定 vue为2.1.6版。
搞了一夜...

**Comment by QingWei-Li** [comment]
最低兼容2.1.6 😂
