### ISSUE TITLE
Select with grouping hide group labels when filtered

### ISSUE THREAD

**Issue by plrenaudin** [ElemeFE/element#2596]
### ElementUI 
1.1.6

### OS/Browers version
Linux/Chrome 55

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/0yLzr4mb/

### Steps to reproduce
Have a filterable select with grouping
Select an entry (Beijing in this example)
Reopen

### What is Expected?
The list is displayed as it originally was

### What is actually happening?
Option group are not always displayed.
In this example the second option group label is not displayed (City Name)

**Comment by kopheece** [comment]
这个问题确实存在  等1.2版本的级联选择器吧

**Comment by Leopoldthecoder** [comment]
This is by design.
I think this calls for a discussion. We will reevaluate after we have more feedbacks.

**Comment by plrenaudin** [comment]
This is misleading because whenever you've selected an element or you load a form with something already pre-selected, when you open the list, you can't see the groups the options belong to.

**Comment by Leopoldthecoder** [comment]
Ah, sorry I didn't go through the demo carefully.
This is a bug.
