### ISSUE TITLE
Input不支持focus()和blur()等方法

### ISSUE THREAD

**Issue by imyzf** [ElemeFE/element#2597]
### ElementUI version
1.1.5

```html
<template>
  <div>
    <el-input  ref="input"></el-input>
  </div>
</template>
```
直接调用`this.$refs.input.blur()`没有用，因为`this.$refs.input.$el`取到的是外层div，只能用`this.$refs.input.$el.children[1].blur()`这种不规范的方法调用。所以希望Input增加focus()和blur()等方法，可以直接`this.$refs.input.blur()`方式调用。

**Comment by jikkai** [comment]
试下 `this.$el.querySelector('input')`

**Comment by imyzf** [comment]
@jikkai 这种方式方式和`this.$refs.input.$el.children[1].blur()`本质上是一样的，如果有直接的API可以调用，不用关心DOM结构，可能会更好吧

**Comment by erguotou520** [comment]
注意多看看文档，这个是vue的东西 应该用`<el-input @blur.native="blurHandler"></el-input>`
FAQ里也有写哦
issue可关

**Comment by Leopoldthecoder** [comment]
@erguotou520 不是，这里说的是 `focus` 和 `blur` 方法，确实没有提供。`@blur.native` 是回调了。

**Comment by imyzf** [comment]
@Leopoldthecoder 这个feature我自己来加吧，我准备加上focus(), blur(), select()三个原生input方法，春节假期找时间加上去，然后提PR，怎么样

**Comment by Leopoldthecoder** [comment]
@imyzf 可以的，欢迎 PR。

**Comment by erguotou520** [comment]
哦 我一开始没仔细看 理解错了 但是这种解决方法还是比较片面，如果再加其它方法呢？如果其它组件也需要呢？我建议是针对原生元素封装的组件可以在组件内提供`ref=xxx`，这样就可以`this.$refs.input.$refs.input`去调用，一来是上述的问题，二来这种使用的场景较少（应该是比较少吧）

**Comment by imyzf** [comment]
或者是否可以参考`@click.native`这种写法，把原生input通过`this.$refs.input.native`这种方式暴露出来？

**Comment by erguotou520** [comment]
没见过这种写法的

**Comment by jikkai** [comment]
这种手动操作DOM方法的情况不多，推荐自行hack解决，还是避免组件过重吧

**Comment by imyzf** [comment]
好的，谢谢大家
