### ISSUE TITLE
NavMenu在跳转到一个不在menu-item的index中的地址后，仍保留选中状态

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#2600]
### Reproduction Link
https://vf-backend.herokuapp.com

### Steps to reproduce
登录后点击"用户列表"，然后再点击上面的Title，发现"用户列表"仍然高亮

**Comment by baiyaaaaa** [comment]
watch 你的$route.path 建立与 default-active 的映射

**Comment by erguotou520** [comment]
可以看下这个例子 http://jsfiddle.net/z6vxq91q/ 只要跳转到一个不在nav-menu里的路由，就会仍然选中原来的菜单项

**Comment by reverland** [comment]
@erguotou 所以不在的理由怎么处理比较好呢。比如不归入任何navmenu项目中的

**Comment by erguotou520** [comment]
肯定是什么都不选中啊

**Comment by reverland** [comment]
@erguotou520 所以说现在有办法取消选中么。。

**Comment by erguotou520** [comment]
并没有看到，但是这个可以加啊

**Comment by reverland** [comment]
@erguotou520 加啊

**Comment by baiyaaaaa** [comment]
#2877
