### ISSUE TITLE
Internationalization for CDN users

### ISSUE THREAD

**Issue by Nicholas-Fisher** [ElemeFE/element#2604]
It is currently unclear how to set the language for Element UI when using the CDN to import the library.

Is there a way to use the english localization with script tags? Thank you.

**Comment by Lykegenes** [comment]
I'm wondering about this too. Setting the locale in Vue or Vue-I18n seems to have no effect.

**Comment by mmarquez** [comment]
+1 for this enhancement

**Comment by Leopoldthecoder** [comment]
Fixed in #2658
