### ISSUE TITLE
Configurable Breakpoints

### ISSUE THREAD

**Issue by smith64fx** [ElemeFE/element#2605]
Hello friends,
I want to talk about the breakpoints.

For now we have:
```
xs	<768px Responsive columns or column props object	number/object (i.e： {span: 4, offset: 4})	—	—
sm	≥768px Responsive columns or column props object	number/object (i.e： {span: 4, offset: 4})	—	—
md	≥992 Responsive columns or column props object	number/object (i.e： {span: 4, offset: 4})	—	—
lg	≥1200 Responsive columns or column props object	number/object (i.e： {span: 4, offset: 4})	—	—
```

I'd like to config the breakpoints as it's possible in bootstrap.
https://v4-alpha.getbootstrap.com/layout/overview/

```
// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

In bootstrap the "xs" is everything up to 576px, which is better if you want to design also for smart devices.

Right now the smalles breakpoint is 768px, so we are quite limited in designing.

Is there any plan to implement this?

**Comment by AxelTheGerman** [comment]
so you just want to change it to the following
xs <576px
sm >=576px
md >=768px
lg >= 992px
xl >= 1200px

or do you mean by configure, defining the breakpoints yourself? you can still use media queries such as in bootstrap, but they won't affect the predefined xs, md etc breakpoints

**Comment by baiyaaaaa** [comment]
I'm sorry to say that element is not made for mobile devices.

**Comment by rtheunissen** [comment]
> I'm sorry to say that element is not made for mobile devices.

🚪🚶

**Comment by smith64fx** [comment]
@rtheunissen 
![image](https://user-images.githubusercontent.com/3246782/36945137-a8eca4c2-1fa9-11e8-9b31-70bc5e98e988.png)


You can change the breakpoints via the variables. Works like charm!

**Comment by jamesmcintyre** [comment]
For anyone else that comes across this issue: https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/common/var.scss#L865-L892
