### ISSUE TITLE
tree：树形控件  功能建议

### ISSUE THREAD

**Issue by qiaocuixinzhiweini** [ElemeFE/element#261]
![_20161008165204](https://cloud.githubusercontent.com/assets/8213229/19211827/843420ca-8d78-11e6-9960-1f768c1607d0.png)

### What is Expected?
希望能够在每层name前自定义图标，每层树后面可以添加操作按钮，比如：编辑、删除

### What is actually happening?
暂时没有找到可以添加的方法

**Comment by fishpaw** [comment]
1. 嗯，对操作按钮的需求我们之前有考虑到，之后应该会陆续加入。
2. 前面的图标，我们会进一步确认，如果真的有必要，会加入这个特性。

**Comment by furybean** [comment]
已经提供 render-content 属性，会在 rc8发布，参考 #470

**Comment by tolerious** [comment]
同求二级目录后面可以增加图标并且可以响应相应功能。

这功能利国利民啊。

**Comment by tolerious** [comment]
另外最好能够支持二级目录的拖动功能呢。

**Comment by wumaohui** [comment]
您好！是否可以看看你截图的那个组件的源码呢，自己要做一棵树结构的展示，并且只能勾选叶子节点遇到一些问题，想参考一下您的方法

**Comment by weichendahai** [comment]
https://jsfiddle.net/api/post/library/pure/

```
<el-tree :data="data2" :props="defaultProps" show-checkbox="" node-key="id" default-expand-all :expand-on-click-node="false" :render-content="renderContent">
</el-tree>
```
el-tree 添加 :render-content="renderContent" 渲染；列表展示位空了；
示例代码也存在此类问题

**Comment by James-jun06** [comment]
你好，我在element1.2.8，vue2.2.6上使用el-tree的renderContent属性，按文档上写的报如下错，请问什么问题？
in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/corp/bookList.vue
Module build failed: SyntaxError: D:/vue/yqx_neec/src/views/corp/bookList.vue: Unexpected token (353:10)

  351 | 	    renderContent(h, { node, data, store }) {
  352 |         return (
> 353 |           <span>
      |           ^
  354 |             <span>
  355 |               <span>{node.label}</span>
  356 |             </span>

**Comment by James-jun06** [comment]
你好，想问下，tree控件每个node后面用 render-content实现的按钮操作，有属性设置只有在hover状态才出现，在鼠标没移动到该node上时，不显示按钮操作吗

**Comment by CavanLife** [comment]
@weichendahai 需要配置 JSX 环境。终端中执行 `npm install\
  babel-plugin-syntax-jsx\
  babel-plugin-transform-vue-jsx\
  babel-helper-vue-jsx-merge-props\
  babel-preset-es2015\
  --save-dev`
然后 项目中找到.babelrc 文件，增加配置`{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}`

**Comment by jim888666** [comment]
怎么给elementUi tree 控件父节点添加自定义图标呢？？？请发到os-caojm@jsfund.cn 邮箱上，谢谢了！！

**Comment by WBJfounder** [comment]
@fishpaw 你好，想问下，tree控件每个node后面用 render-content实现的按钮操作，有属性设置只有在hover状态才出现，在鼠标没移动到该node上时，不显示按钮操作吗   就是这个人说的问题 有什么好办法吗 还有就是我的tree是动态生成的   我现在需要 要它根据我的操作实时刷新需要怎么做

**Comment by WBJfounder** [comment]
@James-jun06 你的问题解决了吗

**Comment by freedomcly** [comment]
> @fishpaw 你好，想问下，tree控件每个node后面用 render-content实现的按钮操作，有属性设置只有在hover状态才出现，在鼠标没移动到该node上时，不显示按钮操作吗 就是这个人说的问题 有什么好办法吗 还有就是我的tree是动态生成的 我现在需要 要它根据我的操作实时刷新需要怎么做

+1
