### ISSUE TITLE
Tag demo has incorrect animation

### ISSUE THREAD

**Issue by MattRix** [ElemeFE/element#2611]
In [the demo for Tags](http://element.eleme.io/#/en-US/component/tag), "Editing Dynamically", when you remove a tag, the correct item is removed, but the animation always plays on the last item on the list. It looks weird.

**Comment by erguotou520** [comment]
@Leopoldthecoder 目测是key没有设置为tag对象，而是使用的`$index`?

**Comment by Leopoldthecoder** [comment]
@erguotou520 是的。
@MattRix fixed in #2613

**Comment by erguotou520** [comment]
因为我发现这个问题跟我之前自己写的step组件的动效问题一样 😄 
快过年了还在fix bug 辛苦了 👍
