### ISSUE TITLE
Date picker not using the full width

### ISSUE THREAD

**Issue by plrenaudin** [ElemeFE/element#2617]
### ElementUI version
1.1.6

### OS/Browers version
Linux/Chrome55

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/qwyfwqes/2/

### Steps to reproduce
Set a date picker in a full width row

### What is Expected?
The date picker use the full width

### What is actually happening?
The date picker is 193px wide

**Comment by reverland** [comment]
maybe all select/input is inline-block since 1.1.5, so...

**Comment by plrenaudin** [comment]
The issue was already there before 1.1.5

**Comment by Leopoldthecoder** [comment]
This is a breaking change introduced in 1.1.0
> The box models of Input and Select are updated from `block` to `inline-block`
