### ISSUE TITLE
Date Picker show the year selector first?

### ISSUE THREAD

**Issue by robmpreston** [ElemeFE/element#2618]
So I'm using the date picker for 'birth date' on a customer facing site 

It's a little counter intuitive to have it start with the current date / month view. 

What I would like is, much like you can do with the bootstrap datepicker, is when it opens it shows the 'year' selector first, then, month, then day. Is there some way to trigger it to start with the year selection?

**Comment by Leopoldthecoder** [comment]
Sorry, the DatePicker cannot trigger this behavior.
