### ISSUE TITLE
推荐为Notification 通知添加自定义位置的功能

### ISSUE THREAD

**Issue by 2300206764** [ElemeFE/element#2626]
Notification 通知不应该只在右上角出现，屏幕四角和中轴线都是常见的通知位置。

**Comment by Leopoldthecoder** [comment]
中轴线可以使用 Message，其他位置无计划。

**Comment by cody1991** [comment]
希望还是使用 notification ，而不是 message 这种（message的确定，取消按钮可以去掉，但是 右上角的 X 无法去掉，另外也不希望有蒙层），还是希望能有居中显示 notification 这样的

**Comment by yanjingenious** [comment]
我觉得，应该把top不要用style，有时候top的位置不对，在后期完全无法微调
