### ISSUE TITLE
MessageBox优化建议

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#263]
1. `.el-message-box__message p`样式建议添加`word-wrap: break-word;`，原因就是英文没法换行
2. 弹出效果不要用`scale`，否则在弹出时弹出层文字模糊，容易产生眩晕感

**Comment by fishpaw** [comment]
针对第 2 个问题，我们也已经注意到，打算将弹出效果与 dialog 保持一致

**Comment by erguotou520** [comment]
3. 考虑到模态框关闭的途径有很多种，而在窗口关闭后进行重置操作又很常见，所以应该提供类似`before-show`,`on-shown`,`before-hide`,`on-hidden`之类的钩子可以进行自定义操作

**Comment by sandysong** [comment]
钩子+1

**Comment by furybean** [comment]
已改进，等 rc8 发布。
