### ISSUE TITLE
Form Validation Not Working

### ISSUE THREAD

**Issue by arunrreddy** [ElemeFE/element#2631]
### ElementUI version
1.1.5

### OS/Browers version
Chrome 55

### Vue version
2.1.10

### What is Expected?
The function this.$refs[formName].validate(valid => {}); is supposed to check whether the form is valid or not.
### What is actually happening?
The above function is not getting executed at all. I get a loading gif on all my input fields in the form. I did follow the example for form validation from the guide but it isn't working. 

I am trying to validate the whole form.

[test.docx](https://github.com/ElemeFE/element/files/741799/test.docx)

**Comment by SimonHui931208** [comment]
Actually, when we have several form elements to be validated，the function validate(callback(boolean)) does not work fine. The callback may not work. The sample on the official Doc is only hava one form to be validated.
