### ISSUE TITLE
能否给tooltip组件增加一个功能，能选择tooltip上的文字内容

### ISSUE THREAD

**Issue by martinko2009** [ElemeFE/element#2633]
### OS/Browers version

Win7
### Vue version

Vue 2.1.8
### What is Expected?
能否给tooltip增加一个feature，就是当鼠标移动到文字上时，显示tooltip。然后鼠标移动到这个tooltip上时，tooltip不消失，用鼠标可以选择tooltip上的文字。但是当鼠标移动到页面的其他地方，tooltip可以自动消失。就像iview的tooltip那样。

**Comment by martinko2009** [comment]
请问我如何才能下载到包含这个功能的程序呢，谢谢啦

**Comment by QingWei-Li** [comment]
`1.2` 的功能，还没发布
