### ISSUE TITLE
多个Dialog弹出，关闭一个后的body滚动锁定问题

### ISSUE THREAD

**Issue by microboat** [ElemeFE/element#2639]
有多个Dialog弹出后，关闭其中一个，body滚动锁定会失效，请问有办法解决吗？

**Comment by Leopoldthecoder** [comment]
多个 Dialog 是同时弹出的？

**Comment by microboat** [comment]
是的，例如在编辑一个复杂对象的场景下，在一个Dialog中编辑主体信息，这个Dialog中又有一些附加功能按钮，点了以后弹出另外的功能性Dialog。

**Comment by microboat** [comment]
建议在PopManager中判断一下，只有最后一个dialog关闭的情况下才清除body的overflow:hidden

**Comment by Leopoldthecoder** [comment]
如果是点击已有 Dialog 中的按钮之后才弹出其他 Dialog，应该是不会清除 `overflow: hidden` 的。如果有问题请提供 demo。
