### ISSUE TITLE
table 组件有滚动条时，表头列没对齐

### ISSUE THREAD

**Issue by niceue** [ElemeFE/element#264]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
win10/Chrome 53

### Vue version
2.0.1

### Demo:
https://jsfiddle.net/umufLmad/

![qq 20161008180829](https://cloud.githubusercontent.com/assets/1498854/19212374/5955fdba-8d82-11e6-9308-6d94c5baa101.png)

### 表头 th 列和 body 列没有对齐。

原因是表格拉伸了，表头的 最后一列 th 设置的 17px 实际就不是 17px了

所以 `<th class="gutter" style="width: 17px;"></th>` 应该去掉，把 17px 宽度设置到外层 div

**Comment by Leopoldthecoder** [comment]
![clip](https://cloud.githubusercontent.com/assets/10095631/19213995/0ec74a54-8dac-11e6-859c-92e08c83f012.gif)
在 win10/Chrome 53 下，官网上的例子表头列是对齐的。请给出没有对齐的在线 Demo。

**Comment by niceue** [comment]
感谢答复

已经在上面说明中补充了 demo，我发现了关键点是**对每一列都设置宽度**，这样每一列都会自适应。出现滚动条的时候，那个最后面的  17px th 实际上不一定是17px了。

如果采用我上面提供的方式，上面 th 的数量和下面 td 的数量保持一致，所有列宽都通过 colgroup 控制，就不会有问题。

之所以每一列都设置宽度，是因为要适配不同宽度的屏幕，所以列宽会有拉伸

**Comment by furybean** [comment]
#363 使用 TableColumn 的 fixed 属性。

**Comment by yilucongrong** [comment]
你好，这个问题解决了没

**Comment by laibin-wang** [comment]
@yilucongrong 动态列出现表格错位，比如第一次展示20个字段 左右滚动，然后切换展示4个字段这时候水平滚动条消失，表头和列出现错位信息，因为水平滚动没有弄成0，el-table 内部有个18px

**Comment by laibin-wang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
