### ISSUE TITLE
The memory usage keeps growing with setInterval().

### ISSUE THREAD

**Issue by lumicompell** [ElemeFE/element#2640]
### ElementUI version
1.1.6

### OS/Browers version
Chrome 55

### Vue version
2.1.10

### Reproduction Link
http://codepen.io/lumicompell/pen/WRzNxP

### Steps to reproduce
None.
### What is Expected?
It works well when all ElementUI components are removed.
![leak2](https://cloud.githubusercontent.com/assets/11407243/22596402/689ba450-ea66-11e6-99ba-baeafd37a2d4.jpg)

### What is actually happening?
The memory usage keeps growing.
![leak](https://cloud.githubusercontent.com/assets/11407243/22596174/7ac01842-ea65-11e6-8cf8-c58060fe968b.jpg)

**Comment by Xrymz** [comment]
read about garbage collection
http://stackoverflow.com/questions/14034107/does-javascript-setinterval-method-cause-memory-leak
