### ISSUE TITLE
el-input嵌套 el-select不显示绑定的v-model数据。

### ISSUE THREAD

**Issue by bigrocs** [ElemeFE/element#2641]
el-input嵌套 el-select不显示绑定的v-model数据。 数据可以改变但是视图不显示

![qq 20170202144419](https://cloud.githubusercontent.com/assets/15796287/22539609/09522b10-e956-11e6-8e02-46b96c540a2f.png)

![qq 20170202144434](https://cloud.githubusercontent.com/assets/15796287/22539638/39c00966-e956-11e6-9080-d02c192c93e7.png)

**Comment by Leopoldthecoder** [comment]
手动给 `.el-select` 加条 `width` 样式。#2086 #2190

**Comment by bigrocs** [comment]
谢谢

**Comment by krysatl** [comment]
确实有用。但是因为width而不显示数据很怪异啊？
