### ISSUE TITLE
question: button focus

### ISSUE THREAD

**Issue by mitjarobic** [ElemeFE/element#2642]
why does a button stay focused after pressing it? How can i unfocus it?

**Comment by Kingwl** [comment]
this is not a bug

**Comment by mitjarobic** [comment]
how do i unfocus or unclick it without clicking on some other element?

**Comment by connor11528** [comment]
I have the same question. When a user clicks a button I don't want it to stay focused. How can we remove the focus to a button on user click?

**Comment by jhoogeboom** [comment]
This is still the case, anyone has a solution for this?
