### ISSUE TITLE
关于select组件选项多且有默认值时，定位问题

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#2644]
element UI: 1.1.6

demo: http://jsfiddle.net/kopheece/43o0607s/

当select选项多并且有默认值的时候。demo操作如下：
1.第一次点击select组件，出现下拉框，没有定位到默认值的位置；
2.第二次点击select组件，出现下拉框，有定位到默认值的位置；

希望第一次点击的时候也能定位到默认值的位置

**Comment by Leopoldthecoder** [comment]
Fixed in #2699
