### ISSUE TITLE
[vue-component] Error while compiling in tag <script>

### ISSUE THREAD

**Issue by mingliang7** [ElemeFE/element#2645]
I've got the problem like the pic below. Please help thanks you!
![invalid](https://cloud.githubusercontent.com/assets/5500858/22581297/81552296-ea11-11e6-9af3-5a66115866cb.png)

**Comment by QingWei-Li** [comment]
Please tell us what u a using.

**Comment by mingliang7** [comment]
I'm using Meteor(http://meteor.com) as backend and Vue as front end.
i do the following below
- npm install element-ui --save
- npm install vue
- npm install vue-meteor-tracker
- npm install vue-router

**Comment by qingxinkouqi** [comment]
这个问题我也遇到了，问题出现于使用了meteor（nodejs响应式开发框架），为了将vue集成于meteor中，安装了[meteor-vue-component](https://github.com/Akryum/meteor-vue-component)，并根据说明中的[示例](https://github.com/Akryum/meteor-vue2-example)进行了配置，之后在执行meteor程序的时候，在编译阶段报错。

**Comment by alexandesigner** [comment]
I also have this problem [meteor-vue-component](https://github.com/Akryum/meteor-vue-component/issues/116) and also created a simple [Reproduction](https://github.com/alexandesigner/meteor-vue2-issue116)

**Comment by qingxinkouqi** [comment]
I found this problem can be circumvented by setting [Ignore files ](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-component#ignore-files)in the project.
I added the following ` .vueignore` file to my `node_modules` folder
```
element-ui/
```

**Comment by alexandesigner** [comment]
> I added the following .vueignore file to my node_modules folder

Works fine. Thanks!
