### ISSUE TITLE
AutoComplete在input位置绝对时滚动错位的问题

### ISSUE THREAD

**Issue by NadokaCiel** [ElemeFE/element#2648]
在前几次的更新中，AutoComplete的内容从input下方迁移到了body当中。
但是这样的做法其实是默认了该input相对于document位置是固定的
在一些应用场景，如fixed的浮动窗当中的下拉选项，滚动鼠标滚轮会出现下拉框直接上浮的情况。
这是由于fixed元素的位置基于浏览器窗口，而autocomplete目前是基于body的absolute元素，当页面可以上下滚动时，原先两者的相对位置就将失去联系。
除了autocomplete之外，select插件也有类似的问题

**是否考虑加一个配置项，让使用者选择将下拉框放在input之后或者body最下方呢？
或者，用其他的方式来实现autocomplete/select内容和选框元素之间位置的动态关联？**

感谢您的回复O(∩_∩)O。

**Comment by Leopoldthecoder** [comment]
请给出 demo 或者动图。

**Comment by NadokaCiel** [comment]
@Leopoldthecoder 
关于这个bug的demo请看：[这里](http://jsfiddle.net/pk2fr0y3/4/)
似乎是由于我在fixed元素上添加了样式：
overflow: auto;
造成的该问题
去掉以后可以正常工作了
抱歉耽误了您的时间
