### ISSUE TITLE
[MessageBox]调用MessageBox全局方法偶尔会出现弹窗内容未被替换

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#2655]
![image](https://cloud.githubusercontent.com/assets/12726826/22615908/61071b0a-eadb-11e6-8519-3bafeee424ae.png)
路由用的是keep-alive，用这个全局方法弹出MessageBox，有小概率会出现弹窗内容未被替换，比如我先调用$alert，再调用$confirm，还是会弹出$alert这种样式的MessageBox，内容和样式都是之前$alert调用的弹出的那个。
版本1.0.3，这个bug我没法重现，或者提供demo，因为只是小概率，弹窗的样式和内容都没有被替换掉，只是想探讨下为何会发生这种情况？

**Comment by Leopoldthecoder** [comment]
可能就是 #2352 的问题，已在 #2379 修复，可以试试最新版。

**Comment by Kingwl** [comment]
🌚
