### ISSUE TITLE
dynamically changing the type of component <el-date-picker> while the ui remains unchanged

### ISSUE THREAD

**Issue by gemwuu** [ElemeFE/element#2663]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 55

### Vue version
2.1.0

### Reproduction Link
http://jsfiddle.net/8p0rxde7/21/

### Steps to reproduce

1. select a date
2. change the type to month(default is date)
3. try to select a month

### What is Expected?
expecting a dropdown list showing month

### What is actually happening?
the dropdown list is still containing datetime list.

**Comment by QingWei-Li** [comment]
Not yet support, but you can use `v-if`

**Comment by gemwuu** [comment]
already used `v-if` as a workaround, thanks.
