### ISSUE TITLE
Message组件报错

### ISSUE THREAD

**Issue by linfuxiang** [ElemeFE/element#2664]
### ElementUI version

1.1.2
### OS/Browers version

Chrome 53
### Vue version

2.1.0
### Reproduction Link

https://github.com/linfuxiang/vueFoo
### Steps to reproduce
npm install
npm run dev
首页报错，不弹Message提示框

**Comment by Leopoldthecoder** [comment]
只要在你的页面上调用 `vm.$mount` 方法就会报错。应该是 vuex 的使用姿势不太对，不是 Element 的问题。
比如在 `mounted` 里加上下面这段代码：
```javascript
var MyComponent = Vue.extend({
  template: '<div>Hello!</div>'
});
new MyComponent().$mount('#hello');
```
也会报同样的错。注意先引入 Vue，并且在模板上加一个 `#hello` 元素。
