### ISSUE TITLE
input-number 组件在 form-item 中small size表现异常

### ISSUE THREAD

**Issue by woozyking** [ElemeFE/element#2666]
如图显示

![screenshot-localhost 8080-2017-02-04-10-07-33](https://cloud.githubusercontent.com/assets/2837532/22619402/f6dbb902-eac1-11e6-85bb-8e38c82f0162.png)

另外虽然没有文档描述，貌似`mini` size也可以使用，只不过在 `form-item` 有类似问题

**Comment by baiyaaaaa** [comment]
#2675 fix
