### ISSUE TITLE
[Select]组件配合vue-router时，报错:Uncaught TypeError: Cannot read property 'doDestroy' of undefined

### ISSUE THREAD

**Issue by SirM2z** [ElemeFE/element#2668]
Demo: [JSFiddle](https://jsfiddle.net/coolmrz/6zpmmpbe/)

### ElementUI version
1.1.6

### OS/Browers version
Chrome 55

### Vue version
2.1.10

### 重现
![example](http://7xs9eo.com1.z0.glb.clouddn.com/2.gif)

- 点击select组件，当出现下拉框时，先点击空白区域，然后迅速切换路由就导致报错

- 这是我在JSFiddle中尝试重现时，发现只有这样才能报错，但在我的项目中，不需要点击空白区域，切换路由就会报错，报错内容一样

**Comment by Leopoldthecoder** [comment]
Fixed in #2699
