### ISSUE TITLE
time-picker，当鼠标移动到时间选择框上框就隐藏了，无法选择时间

### ISSUE THREAD

**Issue by xing-zhi** [ElemeFE/element#267]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
+ win10/Chrome 53 
+ Debian/Chrome 52

### Vue version
2.0.0-rc.8

### Reproduction Link
http://element.eleme.io/#/component/time-picker
官网示例就存在这个问题

### Steps to reproduce
正常使用即可

### What is Expected?
时间选择框在点击取消或者确定按钮时才隐藏

### What is actually happening?
当鼠标移动到时间选择框上时框就隐藏了，没有办法选择时间

**Comment by QingWei-Li** [comment]
fixed in #210

**Comment by Leopoldthecoder** [comment]
@xing-zhi 请确认和 #210 描述的问题是否一致。我在 win10/Chrome 53 下访问官网没有出现你说的现象。

**Comment by xing-zhi** [comment]
@Leopoldthecoder 不好意思，系统是win8.1，平时在windows下开发的少，没有留意

和[#210](https://github.com/ElemeFE/element/issues/210)描述的不完全一样，不用点击，鼠标移上去就会隐藏

**Comment by erguotou520** [comment]
测试了下，点击icon弹出选择框时会重现上述问题，点击输入框时不存在此问题

**Comment by QingWei-Li** [comment]
已经修复了，应该跟 #210 是同一个 bug 导致的

**Comment by erguotou520** [comment]
官网文档没更新么？我看现在网站示例还都有这个问题

**Comment by QingWei-Li** [comment]
是的没更新，下一版本才可以

**Comment by xing-zhi** [comment]
点输入框确实不存在这个问题

不过时分秒选择任何一个，选择框就隐藏的行为不太好，同时编辑时分秒是存在的

**Comment by Leopoldthecoder** [comment]
@xing-zhi 「时分秒选择任何一个，选择框就隐藏」已经在 #215 修了

**Comment by xing-zhi** [comment]
好的
