### ISSUE TITLE
建议统一packages中各个组件的import和export写法

### ISSUE THREAD

**Issue by hjkcai** [ElemeFE/element#2677]
我在研究如何做到真正的按需引入时（官方提供的按需引入还是会导致许多不必要的代码被引入），尝试直接从`packages`中引入组件：
```javascript
import ElMenuItem from 'element-ui/packages/menu-item'
Vue.use(ElMenuItem)
```

我使用的是webpack@2.2.1，编译没问题，运行时报错：
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
  at Object.<anonymous> (menu-item.vue:16)
```

google后得知，在webpack 2中不允许混用`import`和`module.exports` (https://github.com/webpack/webpack/issues/4039) ，而`menu-item.vue`正是混用了这两个。我的babel设置中关闭了对ES6 module的转码，所以导致了这个问题

所以建议官方能够统一写成ES6的形式，谢谢！

**Comment by baiyaaaaa** [comment]
#2678 fix

**Comment by erguotou520** [comment]
但是`src/index.js`还是混用了啊
