### ISSUE TITLE
table组件的loading设置为false，但是还有loading状态

### ISSUE THREAD

**Issue by pod4g** [ElemeFE/element#2679]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 55

### Vue version
2.1.10

### 背景描述
因为很多视图要用到数据列表，所以基于Table组件封装了一个DataGrid组件，在DataGrid组件的created钩子里，首先设置`this.loading = true`，然后取数据，数据取完，设置`this.loading = false`，但是还是有loading状态

![f16eef29-b357-41a2-908a-4669a11ba111](https://cloud.githubusercontent.com/assets/12889190/22634366/f632ced4-ec63-11e6-9223-9b06d26b7d08.png)

![33ef8050-2af4-4530-b01b-0071be30c642](https://cloud.githubusercontent.com/assets/12889190/22634400/53238fca-ec64-11e6-9d13-b5a5f95c2880.png)

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by pod4g** [comment]
感谢@Leopoldthecoder回复！

知道原因了，应该是异步的问题`Article.getArticles`现在是同步的（因为是mock数据），改为异步就好了。。

```javascript
import articles from '../mocks/articles'
export default class Article {
  static getArticles (query) {
    return new Promise((resolve, reject) => {
      let ret = []
      // 如果有查询条件，就按照查询条件查询，否则就查询全部
      if( query ){
        // 有查询条件，就随机取一些数据，以示区别
        ret = Article.randArray(articles, Math.ceil(Math.random()*20)) 
      } else {
        ret = articles
      }
      // resolve(ret) // 同步的话，loading取消不掉
      setTimeout(() => {  // 改为异步。loading就能去掉了。
        resolve(ret)
      }, 1000)
    })
  }

  static deleteArticle (id) {
    return new Promise((resolve, reject) => {
      resolve('SUCCESS')
    })
  }

  static randArray (data, len) {
    data.sort(function() {
      return Math.random() - 0.5;
    });
    return data.slice(0, len);
  }
}
```

### 查了查vue的文档：

> 可能你还没有注意到，Vue 异步执行 DOM 更新。只要观察到数据变化，Vue 将开启一个队列，并缓冲在同一事件循环中发生的所有数据改变。如果同一个 watcher 被多次触发，只会一次推入到队列中。这种在缓冲时去除重复数据对于避免不必要的计算和 DOM 操作上非常重要。然后，在下一个的事件循环“tick”中，Vue 刷新队列并执行实际（已去重的）工作。Vue 在内部尝试对异步队列使用原生的 Promise.then 和 MutationObserver，如果执行环境不支持，会采用 setTimeout(fn, 0) 代替。
例如，当你设置 vm.someData = 'new value' ，该组件不会立即重新渲染。当刷新队列时，组件会在事件循环队列清空时的下一个“tick”更新。多数情况我们不需要关心这个过程，但是如果你想在 DOM 状态更新后做点什么，这就可能会有些棘手。虽然 Vue.js 通常鼓励开发人员沿着“数据驱动”的方式思考，避免直接接触 DOM，但是有时我们确实要这么做。为了在数据变化之后等待 Vue 完成更新 DOM ，可以在数据变化之后立即使用 Vue.nextTick(callback) 。这样回调函数在 DOM 更新完成后就会调用

https://cn.vuejs.org/v2/guide/reactivity.html

**Comment by Leopoldthecoder** [comment]
`this.loading` 最终是 `false` 吧，控制台最后一个打出来的是 `false`

**Comment by pod4g** [comment]
但是既然是`false`，loading为何还有？

**Comment by Leopoldthecoder** [comment]
试了一下，同步好像也没问题：http://jsfiddle.net/j09wzh29/

**Comment by pod4g** [comment]
多谢回复
