### ISSUE TITLE
Allow specifying tree node padding increment

### ISSUE THREAD

**Issue by binary-koan** [ElemeFE/element#2681]
Since I'm rendering custom nodes with icons in my tree, the default left padding of 16px per level doesn't look good. I'd like to be able to customise this to be based on `rem` units, ideally using CSS, but a Vue property would work too.

### ElementUI version
1.1.6

### OS/Browers version
Linux/Chrome 54 (Electron)

### Vue version
2.1.10

**Comment by Leopoldthecoder** [comment]
Added an `indent` property: https://github.com/ElemeFE/element/pull/2713/files#diff-17d1001f344d2451e2df4708e8623fecR765
