### ISSUE TITLE
Table: Bug in fixed right column.

### ISSUE THREAD

**Issue by liril-net** [ElemeFE/element#2683]
### Reproduction Link
https://jsfiddle.net/gmve9d3p/131/

### Steps to reproduce
1. Nested header
2. Fixed right column

### What is Expected?
1. correct header of fixed height

### What is actually happening?
1. Hidden header

**Comment by Leopoldthecoder** [comment]
好像是引用了老的样式文件。

**Comment by liril-net** [comment]
@Leopoldthecoder 高度问题解决了，现在只有 header 隐藏的问题，应该是计算错误。

**Comment by Leopoldthecoder** [comment]
等你来了可以自己修🙃

**Comment by Kingwl** [comment]
233
