### ISSUE TITLE
[Tree]希望可以定制节点是否可选中

### ISSUE THREAD

**Issue by yang0323** [ElemeFE/element#2687]
非叶子节点不希望被选中，点击非叶子节点仅展开/收起，点击叶子节点可选中
希望能支持这个特性~~有些场景下非叶子节点仅做分组用，选中并没有意义

**Comment by wumaohui** [comment]
非常赞同，而且对于某些特定的父节点的子节点应该有一些可以设置单选，有一些可以设置多选

**Comment by Leopoldthecoder** [comment]
Duplicate of #4767
