### ISSUE TITLE
tabs点击可以自定义触发切换么？

### ISSUE THREAD

**Issue by miaomiaozhou** [ElemeFE/element#2689]
场景描述：
tab点击出现确定框，等用户确定后再切换tab，用户取消后停留在原tab，而不是点击了某个tab立即就切换到某个tab

**Comment by erguotou520** [comment]
目前没有直接提供这样的方法，但是可以hack实现。先备份当前选中的tab，在`@tab-click`事件中将`v-model`绑定的值还原未备份的值，同时存一个`temp`变量表示刚点击欲跳转的tab，然后MessageBox弹框，点击确认后将`v-model`和备份的值同时置为`temp`变量的值，如果是取消则什么都不做，最后关闭弹框。不知道明白了么？

**Comment by baiyaaaaa** [comment]
作为 tab 组件这样使用的场景有点奇怪。。。

**Comment by hanwsscan** [comment]
@miaomiaozhou  最终解决方案是什么？目前也有这个需求....切换标签前需要校验内容是否有保存！
