### ISSUE TITLE
el-switch 建议将值设为自动判断true or false.而不是规定是布尔型.

### ISSUE THREAD

**Issue by zWingz** [ElemeFE/element#2690]
el-switch中props设定为布尔型,如果实际数据为0,1的话,需要进一步转型处理,这种情况可能会多加一个data以及computed或watch来辅助转型.有点不太方便.是否可以根据实际数据自动判断true or false.

或者是否可以自定义true的值和false的值.当前只有true/false的文字text

**Comment by erguotou520** [comment]
这个可以有，参考 https://cn.vuejs.org/v2/guide/forms.html#复选框-1
目前来看，可以使用`@change`事件来实现

**Comment by Kingwl** [comment]
所以为啥不能直接!!呢...

**Comment by zWingz** [comment]
@Kingwl v-model后面不能带运算的吧..所以要用!!的时候应该还要在原数据中进行处理

**Comment by Kingwl** [comment]
@zWingz 哦对。。。。

**Comment by zWingz** [comment]
@Kingwl 对啊.要额外处理

**Comment by Leopoldthecoder** [comment]
考虑给 Switch 添加 `true-value` 和 `false-value`，应该会在 1.3 版本中实现。
