### ISSUE TITLE
Form errors from server 

### ISSUE THREAD

**Issue by aziz19** [ElemeFE/element#2691]
how to handle and display form errors that coming from the server? 

I'm using laravel as backend

**Comment by erguotou520** [comment]
see http://element.eleme.io/#/en-US/component/form#custom-validation-rules

**Comment by axlf** [comment]
I have a related question:

How does the 'error' prop on form-item work?

As I understand, I could add the error prop to the form-item with the desired error message and then the component displays the custom error message.

But that is not working: https://jsfiddle.net/0pheLLyL/2/

Or how should we use the error prop?

**Comment by Leopoldthecoder** [comment]
@axlf I got it to work: https://jsfiddle.net/0pheLLyL/3/
I think it makes sense because in most cases, like when the error message is returned from a HTTP request, it is bound to be async.
@aziz19 my demo may be helpful to your case too.

**Comment by axlf** [comment]
Thank you, that helped a lot. The watcher on the error prop detects only changes. Predefined values will be ignored.

@aziz19 I'm using this in context of laravel - and I use it like this:

```
<el-form-item label="Name" :label-width="formLabelWidth" :error="errors.name" prop="name">
  <el-input v-model="form.name" name="name" auto-complete="off"></el-input>
</el-form-item>
```

`errors.name` will be populated when the server responds with the error code 422...

**Comment by aziz19** [comment]
thats perfect, THANK YOU

**Comment by webberwang** [comment]
I'm using Laravel as well. I opted to not use AJAX because it's less complex. The 

```javascript
<form-register
    action="{{ route('register') }}" 
   name-errors="{{ $errors->first('name') }}"
   email-errors="{{ $errors->first('email') }}"
>
    <div slot="csrf"> {{ csrf_field() }} </div>
</form-register>
```

Is there anyway to update the error without having to set the data in mount() ?


I
