### ISSUE TITLE
filterable 和 带分组的 select 一起用有毒， 分组会消失

### ISSUE THREAD

**Issue by yubo111** [ElemeFE/element#2694]

**Comment by yubo111** [comment]
初始化后选择，完后分组就消失了，而且如果已经选择好，没有光标focus在输入框，我是忠实的饿了么会员，每天都在点餐给我修修吧

**Comment by PanJiaChen** [comment]
#2596 一个问题吧

**Comment by yubo111** [comment]
@PanJiaChen 嗯就是这个输入和分组一起使用会出现

**Comment by Leopoldthecoder** [comment]
已修复，等下个版本吧。

**Comment by yubo111** [comment]
下个版本啥时候啊，方便透露下吗

发自我的 iPhone

在 2017年2月6日，下午9:37，杨奕 <notifications@github.com<mailto:notifications@github.com>> 写道：


已修复，等下个版本吧。

―
