### ISSUE TITLE
upload上传组件怎么传递附加数据？

### ISSUE THREAD

**Issue by ericwang1902** [ElemeFE/element#2695]
我在使用七牛，上传文件的时候，需要附带key和token，怎么构造formdata并把key和token设置进去呢？

**Comment by virusdefender** [comment]
http://element.eleme.io/#/zh-CN/component/upload#attribute

里面的data啊

**Comment by ericwang1902** [comment]
@virusdefender 
不行，我试了，在服务器端获取不到data。
下面是我的代码：
`
<template>
    <div>
        <el-upload action="http://localhost:8085/sysmanage/test" :data="tokenAndKey" multiple="false" type="drag" :thumbnail-mode="true"
            :on-preview="handlePreview" :on-remove="handleRemove" :default-file-list="fileList">
            <i class="el-icon-upload"></i>
            <div class="el-dragger__text">将文件拖到此处，或<em>点击上传</em></div>
            <div class="el-upload__tip" slot="tip">只能上传jpg/png文件，且不超过500kb</div>
        </el-upload>
    </div>
</template>
<script>

export default {
    data () {
        return {
            tokenAndKey:{
                token:"------------------------------------------------------------------------------------------------------------------------------------",
                key:"key"
            }
            ////jsonplaceholder.typicode.com/posts/
        }
    }
    }
</script>
<style>

</style>
`

**Comment by ericwang1902** [comment]
@virusdefender 
你用过吗？

**Comment by baiyaaaaa** [comment]
我这里试过没问题，你可以看浏览器的开发者工具，是有将data数据放到form-data里的

**Comment by ericwang1902** [comment]
@baiyaaaaa 
你服务器端接口是怎么获取到这个值的？
我在req.body,query里面都是空的。

**Comment by virusdefender** [comment]
你F12看下上传的数据，怎么去取数据那是server的问题

**Comment by baiyaaaaa** [comment]
可以转移到 gitter 求助

**Comment by transtone** [comment]
遇到同样的问题，楼主怎么解决的？
