### ISSUE TITLE
Steps 步骤条 动态数据时显示异常

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#2698]
### ElementUI version

1..1.6
### Vue version

2.1.10
### Reproduction Link

http://jsfiddle.net/0bsw8uta/
### Steps to reproduce
动态修改step时，步骤条中数字显示不正确
希望动态生成的step也能正确显示

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/pull/2523

**Comment by QingWei-Li** [comment]
1.2 的 feature 预计下周或者下下周发布
