### ISSUE TITLE
el-col 嵌套<el-form-item>时，<el-form-item>不可编辑

### ISSUE THREAD

**Issue by zhguokai** [ElemeFE/element#2700]
### ElementUI version
 1.1.6

### OS/Browers version
 macOS/Chrome 53

### Vue version
2.1.10

### Reproduction Link
http://jsfiddle.net/w7rhrw2c/
### Steps to reproduce
1.点击打开嵌套表单的 Dialog
2.输入公司/部门名称 
### What is Expected?
获取焦点，输入名称
### What is actually happening?
无法获得焦点

**Comment by baiyaaaaa** [comment]
样式问题，因为 el-col 元素是浮动的，按照你这样使用的话需要在 el-form 中进行清楚浮动

**Comment by zhguokai** [comment]
@baiyaaaaa 

可不以给个例子，我尝试了几种方法不生效呢？
地址：
http://jsfiddle.net/w7rhrw2c/1/

**Comment by orionlu0916** [comment]
So, base on @zhguokai 's code how should I modify the css style to disable the floating attribute for el-form, and make this case works?

**Comment by Leopoldthecoder** [comment]
@orionlu0916 Wrap `<el-col>` inside an `<el-row>`.
