### ISSUE TITLE
Reset fields does not work without validation rules(even empty works)

### ISSUE THREAD

**Issue by sudo-suhas** [ElemeFE/element#2702]
### ElementUI version
1.1.6

### OS/Browsers version
Windows 8/Chrome 56

### Vue version
2.1.10

### Reproduction Link
http://jsfiddle.net/0bsw8uta/1/

### Steps to reproduce
Create any form without validation rules and call resetFields

### What is Expected?
The fields should get reset to empty values

### What is actually happening?
Nothing happens. The reset works only if there are validation rules attached(even empty dummy ones)

**Comment by Leopoldthecoder** [comment]
Validation rules are not required for resetFields to work. You just need to add the `prop` attribute on `el-form-item`: http://jsfiddle.net/0bsw8uta/2/

**Comment by sudo-suhas** [comment]
Thank you. I thought adding prop needed validation rules. If you don't mind me asking, what is the purpose of the prop field?

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L151
https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L24
You can see it for yourself :)
