### ISSUE TITLE
form表单动态插入N行input框后，部分表单验证失效

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#2704]
vue  2.1.6
element-ui  1.1.6

很抱歉，我的网络问题，在线测试的网站打不开。

请看图片

![jdfw](https://cloud.githubusercontent.com/assets/23046680/22679676/d854d944-ed3e-11e6-8168-9c3b00cf73cf.gif)

动态插入几行input框后，原来带 * 号并可以正常验证的，就错位了，验证也失效了。。

**Comment by baiyaaaaa** [comment]
请提供能复现的在线demo
