### ISSUE TITLE
是否考虑做一个可自定义的二级/三级联动的select组件?

### ISSUE THREAD

**Issue by Plortinus** [ElemeFE/element#271]
感觉后台管理系统里面挺常用的.

**Comment by fishpaw** [comment]
多级的选择器确实在后台产品中经常遇到，会考虑的。

**Comment by Plortinus** [comment]
可以参考React Component [Ant Design Cascader级联选择](https://ant.design/components/cascader/)

**Comment by Pixel-Daze** [comment]
级联选中好像暂时没有，目测得手动造一个

**Comment by Plortinus** [comment]
[iview里的级联](https://github.com/iview/iview/tree/master/src/components/cascader)

**Comment by ivan403704409** [comment]
@fishpaw  请问什么时候添加这个级联组件？

**Comment by baiyaaaaa** [comment]
@ivan403704409 v1.2
