### ISSUE TITLE
文档样式优化

### ISSUE THREAD

**Issue by kiancyc** [ElemeFE/element#2710]
我觉得element.io非常不错，文档也比较详细。
只是文档样式太窄了(代码例子这里)，有些比较复杂的例子看起来很累！
能不能把区块调整得宽一点，左右边距少一点

谢谢！

**Comment by Leopoldthecoder** [comment]
是指一行显示不下，需要水平移动滚动条吗？是的话，麻烦告知哪些例子。

**Comment by kiancyc** [comment]
已经有水平滚动啦 但是要拉到最下面才能滚动
比如form组件的自定义校验规则， 代码示例本身就很长 要拉到最下面才能左右滚动，然后滚动完还要拉上去看代码。
能不能把定宽加大一点呢，现在文档页面全屏显示以后其实左右留白很多的。

**Comment by codehackfox** [comment]
左边导航栏最好可以固定

**Comment by Leopoldthecoder** [comment]
@kiancyc 建议自己在看的时候打开控制台，加一条 CSS：
```css
.container, .page-container {
  width: auto;
}
```
因为宽度是我们的设计师定的，现在不太好改。

@codehackfox 有计划。
