### ISSUE TITLE
[MessageBox] 建议支持html

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#2712]
![image](https://cloud.githubusercontent.com/assets/12726826/22686423/15ad0670-ed5f-11e6-8088-a9f52926684a.png)

现在的MessageBox的内容只有message这个参数，这个参数只支持string，能不能提供参数，支持html，
比如： `<i>内容</i>`，这样就可以在MessageBox显示斜体字了

**Comment by kopheece** [comment]
这个可以有

**Comment by jikkai** [comment]
可以用 dialog 组件实现

**Comment by lry210** [comment]
dialog 并没有提供全局方法

**Comment by Leopoldthecoder** [comment]
最初的考虑是，MessageBox 只是用来替代系统自带的 `alert`、`confirm` 和 `prompt`，所以并不支持文本以外的内容。需要自定义内容的话可以使用 Dialog。

但是目前提这个需求的很多，所以有考虑放开这个限制。不过不会通过 `v-html` 去实现，应该还是用 render function。

先加个 discussion 标签。

**Comment by erguotou520** [comment]
或者重新弄个组件？

**Comment by mokaikai** [comment]
dialog + vuex

**Comment by enjoyZhou** [comment]
同求这个功能

**Comment by zelixag** [comment]
同求，dailog太大，而且不是promise

**Comment by fantacytyx** [comment]
@Leopoldthecoder  计划什么时候支持html？

**Comment by Leopoldthecoder** [comment]
已在 #4550 加入，随 1.3.0-beta.3 发布。
