### ISSUE TITLE
JSFiddle examples in the component docs no longer work

### ISSUE THREAD

**Issue by rrunyon** [ElemeFE/element#2718]
Clicking the "Try it!" button results in this console warning:

![screen shot 2017-02-07 at 5 21 56 pm](https://cloud.githubusercontent.com/assets/1772384/22714332/00ba240a-ed5a-11e6-8308-db1efb3b6374.png)

**Comment by Leopoldthecoder** [comment]
Works for me. Could you try again?

**Comment by rrunyon** [comment]
Still having the same issue on Chrome Version 56.0.2924.87 (64-bit). Other teammates reporting the same. Works fine in Safari.

**Comment by mu-yu** [comment]
same issue for me.
Chrome 56.0.2924.87 (正式版本) beta （64 位） win10

**Comment by Leopoldthecoder** [comment]
See #2741
