### ISSUE TITLE
Can't validate nested form objects

### ISSUE THREAD

**Issue by rrunyon** [ElemeFE/element#2719]
### Reproduction Link

http://jsfiddle.net/xkxqw1k6/2/

### What is Expected?
The nested property is validated along with the shallow property.

### What is actually happening?
Only the shallow property is validated.

**Comment by erguotou520** [comment]
Make a litter change: http://jsfiddle.net/erguotou525/xkxqw1k6/3/

**Comment by rrunyon** [comment]
Thanks @erguotou520!
