### ISSUE TITLE
MessageBox内容不能复制

### ISSUE THREAD

**Issue by Kingwl** [ElemeFE/element#2722]
MessageBox弹出来的好像并不能复制的样子
想问一下是出于什么样的考虑呢 或者是个bug?🌚

**Comment by lry210** [comment]
是因为加了这个样式 -webkit-user-select: none;

**Comment by Leopoldthecoder** [comment]
是的。但是想不起来为什么加这个样式了= =

看上去没什么道理，去掉了。
