### ISSUE TITLE
时间控件中清除选中时间问题

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#2724]
用的官网样例：
http://jsfiddle.net/kopheece/ksr4cq15/
操作如下：
1.选择日期中选中某一日期
2.使用键盘上的删除键删除选中的日期（注意：不是直接点击右边的那个X删除操作）
3.这时候点击立即创建，日期这一输入框不会有校验提示，也就是说用这种删除方法并未真正删除日期；此时，若继续点击日期这一输入框，发现还是选中的前面删除的日期，这时候再点这个选中日期是不会在输入框再显示的，若选其他日期，则能正常赋值到输入框中。

**Comment by Borkes** [comment]
跟这个bug没太大关系,避免出现这个bug一般日期最好设置不能输入,而且也不准确,设置 :editable="false"

**Comment by Leopoldthecoder** [comment]
This bug has been fixed.
