### ISSUE TITLE
<el-select>的multiple属性问题：获取该组件的selectedLabel为空，selected和value都有值，是数组，（没有设置multiple属性的话，selectedLabel就是有值的）

### ISSUE THREAD

**Issue by YYmmlin** [ElemeFE/element#2725]
![image](https://cloud.githubusercontent.com/assets/12744546/22726067/3cc5de14-ee0c-11e6-817f-6e18b104cd6d.png)
![image](https://cloud.githubusercontent.com/assets/12744546/22726076/48573c82-ee0c-11e6-8d01-9b2f7be2528f.png)
![image](https://cloud.githubusercontent.com/assets/12744546/22726092/6965972a-ee0c-11e6-93f7-a8fe864eb3a4.png)
![image](https://cloud.githubusercontent.com/assets/12744546/22726105/7b8abc64-ee0c-11e6-8695-3869f10f3e9e.png)

**Comment by Leopoldthecoder** [comment]
没有问题，就是这样实现的。请不要使用组件中未在文档列出的属性和方法。

**Comment by YYmmlin** [comment]
可是我想获取选中的label和value两个值，文档没找到方法

**Comment by Leopoldthecoder** [comment]
根据 value 去数据里找到对应的对象
