### ISSUE TITLE
改变 carousel items 数据后，指示器没有相应地改变，当前索引也不能归0

### ISSUE THREAD

**Issue by arstd** [ElemeFE/element#2727]
### ElementUI version

1.1.6

### OS/Browers version

 macOS/Chrome 56

### Vue version

 2.1.6

### Reproduction Link

https://jsfiddle.net/bcro87or/

### Steps to reproduce
点击Change 切换数据

### What is Expected?
指示器也需要改变，当前索引也应该归0

### What is actually happening?
指示器未变化，索引归0

建议在检测到 items 变化后，更新指示器，索引归 0。
或者
去掉 el-carousel-item 组件，不知是否可行。如：
```html
<el-carousel items="items" item="item">
    <h3>{{item}}</h3>
</el-carousel>
```

**Comment by Leopoldthecoder** [comment]
Fixed in #2775
