### ISSUE TITLE
[build] `npm run dist` error

### ISSUE THREAD

**Issue by gzhaipu** [ElemeFE/element#2729]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 53

### Vue version
2.1.10

### Steps to reproduce
npm run dist

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/3723585/22727654/0308104e-ee15-11e6-8565-f9646bffb778.png)

**Comment by chenmoran** [comment]
我也遇到相同的问题，vue版本是2.1.8。注释掉对应文件中的render(h)中的所有内容后不报错。

**Comment by QingWei-Li** [comment]
1. 确保项目已经完整 clone
2. 推荐用 yarn 安装依赖
3. 请提供完整的报错信息

**Comment by gzhaipu** [comment]
> element-ui@1.1.6 dist /usr/local/lib/node_modules/element-ui
> npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme


> element-ui@1.1.6 clean /usr/local/lib/node_modules/element-ui
> rimraf lib && rimraf packages/*/lib && rimraf test/**/coverage && lerna clean --yes

Lerna v2.0.0-beta.32
Independent Versioning Mode
All clean!

> element-ui@1.1.6 build:file /usr/local/lib/node_modules/element-ui
> node build/bin/iconInit.js & node build/bin/build-entry.js & node build/bin/i18n.js & node build/bin/version.js

[build entry] DONE: /usr/local/lib/node_modules/element-ui/src/index.js
(node:21596) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

> element-ui@1.1.6 lint /usr/local/lib/node_modules/element-ui
> eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet


[cooking@1.4.0] - Loaded success: vue2

[cooking@1.4.0] - Loaded success: vue2

[cooking@1.4.0] - Loaded success: vue2

Build completed in 12.841s

Build completed in 12.976s

Build completed in 13.16s

[cooking@1.4.0] - Child build/cooking.conf.js:
    Time: 13165ms
       Asset    Size  Chunks                    Chunk Names
    index.js  683 kB       0  [emitted]  [big]  app
    
    ERROR in ./packages/table/src/table-column.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-column.js Unexpected token (36:13)
    You may need an appropriate loader to handle this file type.
    |   selection: {
    |     renderHeader: function(h) {
    |       return <el-checkbox
    |         nativeOn-click={ this.toggleAllSelection }
    |         domProps-value={ this.isAllSelected } />;
     @ ./packages/table-column/index.js 1:0-54
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/col/src/col.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/col/src/col.js Unexpected token (64:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <div
    |         class={['el-col', classList]}
    |         style={style}>
     @ ./packages/col/index.js 1:0-30
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/scrollbar/src/main.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/scrollbar/src/main.js Unexpected token (62:6)
    You may need an appropriate loader to handle this file type.
    |     }, this.$slots.default);
    |     const wrap = (
    |       <div
    |         ref="wrap"
    |         style={ style }
     @ ./packages/scrollbar/index.js 1:0-35
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/pagination/src/pagination.js Unexpected token (46:19)
    You may need an appropriate loader to handle this file type.
    | 
    |   render(h) {
    |     let template = <div class='el-pagination'></div>;
    |     const layout = this.layout || '';
    |     if (!layout) return;
     @ ./packages/pagination/index.js 1:0-42
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-body.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-body.js Unexpected token (26:6)
    You may need an appropriate loader to handle this file type.
    |     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
    |     return (
    |       <table
    |         class="el-table__body"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 31:17-40
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-header.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-header.js Unexpected token (76:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <table
    |         class="el-table__header"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 35:19-44
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in index.js from UglifyJs
    SyntaxError: Unexpected token: operator (>) [index.js:299,32]
Child build/cooking.common.js:
    Time: 12976ms
                   Asset    Size  Chunks                    Chunk Names
    element-ui.common.js  529 kB       0  [emitted]  [big]  app
    
    ERROR in ./packages/table/src/table-column.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-column.js Unexpected token (36:13)
    You may need an appropriate loader to handle this file type.
    |   selection: {
    |     renderHeader: function(h) {
    |       return <el-checkbox
    |         nativeOn-click={ this.toggleAllSelection }
    |         domProps-value={ this.isAllSelected } />;
     @ ./packages/table-column/index.js 1:0-54
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/col/src/col.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/col/src/col.js Unexpected token (64:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <div
    |         class={['el-col', classList]}
    |         style={style}>
     @ ./packages/col/index.js 1:0-30
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/scrollbar/src/main.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/scrollbar/src/main.js Unexpected token (62:6)
    You may need an appropriate loader to handle this file type.
    |     }, this.$slots.default);
    |     const wrap = (
    |       <div
    |         ref="wrap"
    |         style={ style }
     @ ./packages/scrollbar/index.js 1:0-35
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/pagination/src/pagination.js Unexpected token (46:19)
    You may need an appropriate loader to handle this file type.
    | 
    |   render(h) {
    |     let template = <div class='el-pagination'></div>;
    |     const layout = this.layout || '';
    |     if (!layout) return;
     @ ./packages/pagination/index.js 1:0-42
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-body.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-body.js Unexpected token (26:6)
    You may need an appropriate loader to handle this file type.
    |     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
    |     return (
    |       <table
    |         class="el-table__body"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 31:17-40
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-header.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-header.js Unexpected token (76:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <table
    |         class="el-table__header"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 35:19-44
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
Child build/cooking.component.js:
    Time: 12826ms
                 Asset     Size  Chunks             Chunk Names
      dropdown-menu.js  5.77 kB      30  [emitted]  dropdown-menu
        date-picker.js  95.9 kB       0  [emitted]  date-picker
             select.js  37.7 kB       2  [emitted]  select
             upload.js  30.6 kB       3  [emitted]  upload
              table.js  41.6 kB       4  [emitted]  table
        time-select.js  30.4 kB       5  [emitted]  time-select
               tree.js  33.9 kB       6  [emitted]  tree
        message-box.js  19.6 kB       7  [emitted]  message-box
            message.js  20.3 kB       8  [emitted]  message
       autocomplete.js    14 kB       9  [emitted]  autocomplete
            loading.js  13.9 kB      10  [emitted]  loading
            popover.js  10.5 kB      11  [emitted]  popover
       notification.js  10.4 kB      12  [emitted]  notification
             slider.js  12.8 kB      13  [emitted]  slider
            submenu.js  10.3 kB      14  [emitted]  submenu
              input.js  13.2 kB      15  [emitted]  input
           dropdown.js  8.32 kB      16  [emitted]  dropdown
           carousel.js  12.8 kB      17  [emitted]  carousel
               tabs.js  10.3 kB      18  [emitted]  tabs
          menu-item.js  7.17 kB      19  [emitted]  menu-item
       input-number.js  10.9 kB      20  [emitted]  input-number
          form-item.js  11.1 kB      21  [emitted]  form-item
      collapse-item.js   6.7 kB      22  [emitted]  collapse-item
            tooltip.js  6.54 kB      23  [emitted]  tooltip
             option.js   8.6 kB      24  [emitted]  option
       option-group.js  6.08 kB      25  [emitted]  option-group
               rate.js  11.7 kB      26  [emitted]  rate
              radio.js  6.83 kB      27  [emitted]  radio
        radio-group.js  5.32 kB      28  [emitted]  radio-group
               menu.js  8.41 kB      29  [emitted]  menu
        time-picker.js  47.8 kB       1  [emitted]  time-picker
      dropdown-item.js  5.42 kB      31  [emitted]  dropdown-item
             dialog.js   7.6 kB      32  [emitted]  dialog
           checkbox.js  9.94 kB      33  [emitted]  checkbox
     checkbox-group.js  5.22 kB      34  [emitted]  checkbox-group
                tag.js  5.18 kB      35  [emitted]  tag
           tab-pane.js  5.52 kB      36  [emitted]  tab-pane
             switch.js   9.1 kB      37  [emitted]  switch
              steps.js  5.26 kB      38  [emitted]  steps
               step.js  8.38 kB      39  [emitted]  step
            spinner.js  5.18 kB      40  [emitted]  spinner
                row.js  5.18 kB      41  [emitted]  row
       radio-button.js  6.53 kB      42  [emitted]  radio-button
           progress.js  8.64 kB      43  [emitted]  progress
    menu-item-group.js  5.39 kB      44  [emitted]  menu-item-group
               icon.js  4.57 kB      45  [emitted]  icon
               form.js  6.36 kB      46  [emitted]  form
           collapse.js  5.84 kB      47  [emitted]  collapse
      carousel-item.js  7.77 kB      48  [emitted]  carousel-item
               card.js  4.82 kB      49  [emitted]  card
             button.js  5.62 kB      50  [emitted]  button
       button-group.js  4.75 kB      51  [emitted]  button-group
         breadcrumb.js  4.66 kB      52  [emitted]  breadcrumb
    breadcrumb-item.js  5.35 kB      53  [emitted]  breadcrumb-item
              badge.js  5.34 kB      54  [emitted]  badge
              alert.js  6.76 kB      55  [emitted]  alert
       table-column.js  3.91 kB      56  [emitted]  table-column
          scrollbar.js  3.74 kB      57  [emitted]  scrollbar
         pagination.js  3.82 kB      58  [emitted]  pagination
                col.js  3.71 kB      59  [emitted]  col
    
    ERROR in ./packages/table/src/table-column.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-column.js Unexpected token (36:13)
    You may need an appropriate loader to handle this file type.
    |   selection: {
    |     renderHeader: function(h) {
    |       return <el-checkbox
    |         nativeOn-click={ this.toggleAllSelection }
    |         domProps-value={ this.isAllSelected } />;
     @ ./packages/table-column/index.js 1:0-54
     @ multi ./packages/table-column/index.js
    
    ERROR in ./packages/col/src/col.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/col/src/col.js Unexpected token (64:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <div
    |         class={['el-col', classList]}
    |         style={style}>
     @ ./packages/col/index.js 1:0-30
     @ multi ./packages/col/index.js
    
    ERROR in ./packages/scrollbar/src/main.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/scrollbar/src/main.js Unexpected token (62:6)
    You may need an appropriate loader to handle this file type.
    |     }, this.$slots.default);
    |     const wrap = (
    |       <div
    |         ref="wrap"
    |         style={ style }
     @ ./packages/scrollbar/index.js 1:0-35
     @ multi ./packages/scrollbar/index.js
    
    ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/pagination/src/pagination.js Unexpected token (46:19)
    You may need an appropriate loader to handle this file type.
    | 
    |   render(h) {
    |     let template = <div class='el-pagination'></div>;
    |     const layout = this.layout || '';
    |     if (!layout) return;
     @ ./packages/pagination/index.js 1:0-42
     @ multi ./packages/pagination/index.js
    
    ERROR in ./packages/table/src/table-body.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-body.js Unexpected token (26:6)
    You may need an appropriate loader to handle this file type.
    |     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
    |     return (
    |       <table
    |         class="el-table__body"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 31:17-40
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ multi ./packages/table/index.js
    
    ERROR in ./packages/table/src/table-header.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-header.js Unexpected token (76:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <table
    |         class="el-table__header"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 35:19-44
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ multi ./packages/table/index.js


npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! element-ui@1.1.6 dist: `npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the element-ui@1.1.6 dist script 'npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the element-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls element-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/element-ui/npm-debug.log

**Comment by gzhaipu** [comment]
`> element-ui@1.1.6 dist /usr/local/lib/node_modules/element-ui
> npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme


> element-ui@1.1.6 clean /usr/local/lib/node_modules/element-ui
> rimraf lib && rimraf packages/*/lib && rimraf test/**/coverage && lerna clean --yes

Lerna v2.0.0-beta.32
Independent Versioning Mode
All clean!

> element-ui@1.1.6 build:file /usr/local/lib/node_modules/element-ui
> node build/bin/iconInit.js & node build/bin/build-entry.js & node build/bin/i18n.js & node build/bin/version.js

[build entry] DONE: /usr/local/lib/node_modules/element-ui/src/index.js
(node:21596) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

> element-ui@1.1.6 lint /usr/local/lib/node_modules/element-ui
> eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet


[cooking@1.4.0] - Loaded success: vue2

[cooking@1.4.0] - Loaded success: vue2

[cooking@1.4.0] - Loaded success: vue2

Build completed in 12.841s

Build completed in 12.976s

Build completed in 13.16s

[cooking@1.4.0] - Child build/cooking.conf.js:
    Time: 13165ms
       Asset    Size  Chunks                    Chunk Names
    index.js  683 kB       0  [emitted]  [big]  app
    
    ERROR in ./packages/table/src/table-column.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-column.js Unexpected token (36:13)
    You may need an appropriate loader to handle this file type.
    |   selection: {
    |     renderHeader: function(h) {
    |       return <el-checkbox
    |         nativeOn-click={ this.toggleAllSelection }
    |         domProps-value={ this.isAllSelected } />;
     @ ./packages/table-column/index.js 1:0-54
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/col/src/col.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/col/src/col.js Unexpected token (64:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <div
    |         class={['el-col', classList]}
    |         style={style}>
     @ ./packages/col/index.js 1:0-30
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/scrollbar/src/main.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/scrollbar/src/main.js Unexpected token (62:6)
    You may need an appropriate loader to handle this file type.
    |     }, this.$slots.default);
    |     const wrap = (
    |       <div
    |         ref="wrap"
    |         style={ style }
     @ ./packages/scrollbar/index.js 1:0-35
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/pagination/src/pagination.js Unexpected token (46:19)
    You may need an appropriate loader to handle this file type.
    | 
    |   render(h) {
    |     let template = <div class='el-pagination'></div>;
    |     const layout = this.layout || '';
    |     if (!layout) return;
     @ ./packages/pagination/index.js 1:0-42
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-body.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-body.js Unexpected token (26:6)
    You may need an appropriate loader to handle this file type.
    |     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
    |     return (
    |       <table
    |         class="el-table__body"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 31:17-40
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-header.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-header.js Unexpected token (76:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <table
    |         class="el-table__header"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 35:19-44
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in index.js from UglifyJs
    SyntaxError: Unexpected token: operator (>) [index.js:299,32]
Child build/cooking.common.js:
    Time: 12976ms
                   Asset    Size  Chunks                    Chunk Names
    element-ui.common.js  529 kB       0  [emitted]  [big]  app
    
    ERROR in ./packages/table/src/table-column.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-column.js Unexpected token (36:13)
    You may need an appropriate loader to handle this file type.
    |   selection: {
    |     renderHeader: function(h) {
    |       return <el-checkbox
    |         nativeOn-click={ this.toggleAllSelection }
    |         domProps-value={ this.isAllSelected } />;
     @ ./packages/table-column/index.js 1:0-54
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/col/src/col.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/col/src/col.js Unexpected token (64:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <div
    |         class={['el-col', classList]}
    |         style={style}>
     @ ./packages/col/index.js 1:0-30
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/scrollbar/src/main.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/scrollbar/src/main.js Unexpected token (62:6)
    You may need an appropriate loader to handle this file type.
    |     }, this.$slots.default);
    |     const wrap = (
    |       <div
    |         ref="wrap"
    |         style={ style }
     @ ./packages/scrollbar/index.js 1:0-35
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/pagination/src/pagination.js Unexpected token (46:19)
    You may need an appropriate loader to handle this file type.
    | 
    |   render(h) {
    |     let template = <div class='el-pagination'></div>;
    |     const layout = this.layout || '';
    |     if (!layout) return;
     @ ./packages/pagination/index.js 1:0-42
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-body.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-body.js Unexpected token (26:6)
    You may need an appropriate loader to handle this file type.
    |     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
    |     return (
    |       <table
    |         class="el-table__body"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 31:17-40
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
    
    ERROR in ./packages/table/src/table-header.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-header.js Unexpected token (76:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <table
    |         class="el-table__header"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 35:19-44
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ ./src/index.js
     @ multi ./src/index.js
Child build/cooking.component.js:
    Time: 12826ms
                 Asset     Size  Chunks             Chunk Names
      dropdown-menu.js  5.77 kB      30  [emitted]  dropdown-menu
        date-picker.js  95.9 kB       0  [emitted]  date-picker
             select.js  37.7 kB       2  [emitted]  select
             upload.js  30.6 kB       3  [emitted]  upload
              table.js  41.6 kB       4  [emitted]  table
        time-select.js  30.4 kB       5  [emitted]  time-select
               tree.js  33.9 kB       6  [emitted]  tree
        message-box.js  19.6 kB       7  [emitted]  message-box
            message.js  20.3 kB       8  [emitted]  message
       autocomplete.js    14 kB       9  [emitted]  autocomplete
            loading.js  13.9 kB      10  [emitted]  loading
            popover.js  10.5 kB      11  [emitted]  popover
       notification.js  10.4 kB      12  [emitted]  notification
             slider.js  12.8 kB      13  [emitted]  slider
            submenu.js  10.3 kB      14  [emitted]  submenu
              input.js  13.2 kB      15  [emitted]  input
           dropdown.js  8.32 kB      16  [emitted]  dropdown
           carousel.js  12.8 kB      17  [emitted]  carousel
               tabs.js  10.3 kB      18  [emitted]  tabs
          menu-item.js  7.17 kB      19  [emitted]  menu-item
       input-number.js  10.9 kB      20  [emitted]  input-number
          form-item.js  11.1 kB      21  [emitted]  form-item
      collapse-item.js   6.7 kB      22  [emitted]  collapse-item
            tooltip.js  6.54 kB      23  [emitted]  tooltip
             option.js   8.6 kB      24  [emitted]  option
       option-group.js  6.08 kB      25  [emitted]  option-group
               rate.js  11.7 kB      26  [emitted]  rate
              radio.js  6.83 kB      27  [emitted]  radio
        radio-group.js  5.32 kB      28  [emitted]  radio-group
               menu.js  8.41 kB      29  [emitted]  menu
        time-picker.js  47.8 kB       1  [emitted]  time-picker
      dropdown-item.js  5.42 kB      31  [emitted]  dropdown-item
             dialog.js   7.6 kB      32  [emitted]  dialog
           checkbox.js  9.94 kB      33  [emitted]  checkbox
     checkbox-group.js  5.22 kB      34  [emitted]  checkbox-group
                tag.js  5.18 kB      35  [emitted]  tag
           tab-pane.js  5.52 kB      36  [emitted]  tab-pane
             switch.js   9.1 kB      37  [emitted]  switch
              steps.js  5.26 kB      38  [emitted]  steps
               step.js  8.38 kB      39  [emitted]  step
            spinner.js  5.18 kB      40  [emitted]  spinner
                row.js  5.18 kB      41  [emitted]  row
       radio-button.js  6.53 kB      42  [emitted]  radio-button
           progress.js  8.64 kB      43  [emitted]  progress
    menu-item-group.js  5.39 kB      44  [emitted]  menu-item-group
               icon.js  4.57 kB      45  [emitted]  icon
               form.js  6.36 kB      46  [emitted]  form
           collapse.js  5.84 kB      47  [emitted]  collapse
      carousel-item.js  7.77 kB      48  [emitted]  carousel-item
               card.js  4.82 kB      49  [emitted]  card
             button.js  5.62 kB      50  [emitted]  button
       button-group.js  4.75 kB      51  [emitted]  button-group
         breadcrumb.js  4.66 kB      52  [emitted]  breadcrumb
    breadcrumb-item.js  5.35 kB      53  [emitted]  breadcrumb-item
              badge.js  5.34 kB      54  [emitted]  badge
              alert.js  6.76 kB      55  [emitted]  alert
       table-column.js  3.91 kB      56  [emitted]  table-column
          scrollbar.js  3.74 kB      57  [emitted]  scrollbar
         pagination.js  3.82 kB      58  [emitted]  pagination
                col.js  3.71 kB      59  [emitted]  col
    
    ERROR in ./packages/table/src/table-column.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-column.js Unexpected token (36:13)
    You may need an appropriate loader to handle this file type.
    |   selection: {
    |     renderHeader: function(h) {
    |       return <el-checkbox
    |         nativeOn-click={ this.toggleAllSelection }
    |         domProps-value={ this.isAllSelected } />;
     @ ./packages/table-column/index.js 1:0-54
     @ multi ./packages/table-column/index.js
    
    ERROR in ./packages/col/src/col.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/col/src/col.js Unexpected token (64:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <div
    |         class={['el-col', classList]}
    |         style={style}>
     @ ./packages/col/index.js 1:0-30
     @ multi ./packages/col/index.js
    
    ERROR in ./packages/scrollbar/src/main.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/scrollbar/src/main.js Unexpected token (62:6)
    You may need an appropriate loader to handle this file type.
    |     }, this.$slots.default);
    |     const wrap = (
    |       <div
    |         ref="wrap"
    |         style={ style }
     @ ./packages/scrollbar/index.js 1:0-35
     @ multi ./packages/scrollbar/index.js
    
    ERROR in ./packages/pagination/src/pagination.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/pagination/src/pagination.js Unexpected token (46:19)
    You may need an appropriate loader to handle this file type.
    | 
    |   render(h) {
    |     let template = <div class='el-pagination'></div>;
    |     const layout = this.layout || '';
    |     if (!layout) return;
     @ ./packages/pagination/index.js 1:0-42
     @ multi ./packages/pagination/index.js
    
    ERROR in ./packages/table/src/table-body.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-body.js Unexpected token (26:6)
    You may need an appropriate loader to handle this file type.
    |     const columnsHidden = this.columns.map((column, index) => this.isColumnHidden(index));
    |     return (
    |       <table
    |         class="el-table__body"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 31:17-40
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ multi ./packages/table/index.js
    
    ERROR in ./packages/table/src/table-header.js
    Module parse failed: /usr/local/lib/node_modules/element-ui/packages/table/src/table-header.js Unexpected token (76:6)
    You may need an appropriate loader to handle this file type.
    | 
    |     return (
    |       <table
    |         class="el-table__header"
    |         cellspacing="0"
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 35:19-44
     @ ./packages/table/src/table.vue
     @ ./packages/table/index.js
     @ multi ./packages/table/index.js


npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! element-ui@1.1.6 dist: `npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the element-ui@1.1.6 dist script 'npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the element-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:theme
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls element-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/element-ui/npm-debug.log
`

**Comment by Leopoldthecoder** [comment]
为什么要在 node_modules 里 build？

**Comment by gzhaipu** [comment]
thanks, that's right.

**Comment by weituotian** [comment]
@gzhaipu what happende? i do not understand how to solve it?
