### ISSUE TITLE
Form中,如果el-form-item没有设置prop,那么validate没任何反应

### ISSUE THREAD

**Issue by wenner** [ElemeFE/element#2731]
一次先把表单放到页面中,没有设置prop , 然后忘记了,然后测试提交的时候 , validate() , 没有反应

然后看了下代码 , fields.foreach() , 如果没有fields , 那么就不会进到函数里面 , 而fields是有prop才会添加到form中....

感觉不够友好...毕竟不算问题

建议将form-item中的prop的属性设置为required(这种不利于测试) , 或者在validate()函数中做个warning输出,valid返回false

**Comment by erguotou520** [comment]
你不设置props我哪知道你要不要验证啊

**Comment by wenner** [comment]
我执行 validate() 总该知道吧

**Comment by erguotou520** [comment]
就是说你执行validate的时候 那么多字段 你不设置props我哪知道你这个字段要不要验证呢

**Comment by wenner** [comment]
恩，是这个意思，我没琢磨过来……😔
