### ISSUE TITLE
[FEATURE REQUEST]: Add visibility options like hide something on small devices

### ISSUE THREAD

**Issue by ndabAP** [ElemeFE/element#2732]
### ElementUI version
1.1.6

### OS/Browers version
Chrome

### Vue version
2.1.10

### Feature request
Please add the posiblity to add visibility options depending on screen size.

### Why is this necessary?
I would like to restructure the navbar components for mobile usage when on mobile. For example show burger menu.

**Comment by Leopoldthecoder** [comment]
I'm sorry but Element is designed for desktop. Usage on mobile devices is not recommended.

Feature requests like this one will be considered, but for now we incline not to add these features. Not at least in the near future.

**Comment by jonny-novikov** [comment]
@Leopoldthecoder @ndabAP Yeap, you are right. But nowadays we have a great range of desktop sizes up to 4K. But you are right in some way - there should be another approach to be applied in such cases.
