### ISSUE TITLE
关于上传组件的一点建议

### ISSUE THREAD

**Issue by qiaoding** [ElemeFE/element#2734]
目前上传在图片模式的大小是固定的，上传图片后对图片的操作项也是固定的三个，使用起来还不是很方便，因此提出以下建议：
1. 图片模式下支持高度和宽度自定义
2. 操作项的文字支持自定义，例如【继续上传】==>【重新上传】
3. 操作项支持可配置，比如不显示【预览】按钮

**Comment by baiyaaaaa** [comment]
可以体验下1.2的版本
