### ISSUE TITLE
[DatePicker] 希望优化一下日期范围选择器的交互体验

### ISSUE THREAD

**Issue by Tobyee** [ElemeFE/element#2735]
### ElementUI version
1.1.6

### What is Expected?

现在日期范围选择器是无法通过点击标题来选择年份和月份的，必须直接编辑 input 的值，或者通过翻页来选择，非常不便。希望优化一下日期范围选择器，使得它能像单个日期选择器那样选择年份和月份，可以参考 [Ant Design UI](https://ant.design/components/date-picker/) 的实现效果，这样的体验才是完美的。

**Comment by lry210** [comment]
试了一下，的确体验很好，+1

**Comment by erguotou520** [comment]
交互越多，代码越多...
