### ISSUE TITLE
vm.$prompt 希望可以支持传递默认的inputValue， 就像系统的window.prompt那样

### ISSUE THREAD

**Issue by mu-yu** [ElemeFE/element#2737]
### ElementUI version
最新版

### OS/Browers version
Chrome

### Vue version
最新版

### Reproduction Link
http://jsfiddle.net/uzm2de29/

### What is Expected?
能正确处理默认的inputValue，就像 `window.prompt('1', '2')`
![image](https://cloud.githubusercontent.com/assets/3822774/22735045/ff4d8c40-ee32-11e6-86e7-ea2e5b41c8a5.png)

**Comment by Leopoldthecoder** [comment]
1.2.0 已支持。
