### ISSUE TITLE
select 的一点小建议

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2738]
尝试了一些主流select插件，在远程搜索或者创建条目这种filterable的select，需要用户输入的情况下，是否应该默认选中第一个option来更合理？用户直接按回车就能选中自己想要的option。

**Comment by erguotou520** [comment]
有点道理，现在可以直接按箭头然后回车

**Comment by PanJiaChen** [comment]
这的确不是一个bug，就是用户体验不太友好，操作不连贯

**Comment by wisewrong** [comment]
为 select 添加 v-model 的时候，可以给变量添加一个默认值 value，就能实现这样的效果了
