### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by stefmajster** [ElemeFE/element#2739]
Is there english version of sketch file? 
<img width="606" alt="screen shot 2017-02-08 at 1 01 00 pm" src="https://cloud.githubusercontent.com/assets/10141585/22736656/8a264908-edff-11e6-8f7e-8af9468cc11d.png">

**Comment by QingWei-Li** [comment]
https://github.com/ElementUI/Resources/blob/master/ElementUIKit_v1_3_EN.sketch
