### ISSUE TITLE
和bootstrp3共用时upload组件出现按钮重复

### ISSUE THREAD

**Issue by Robinson28years** [ElemeFE/element#2740]
### ElementUI version
1.16
![qq 20170208233545](https://cloud.githubusercontent.com/assets/19591259/22744232/be5d9660-ee57-11e6-9f92-cee9f27e1412.jpg)
引入bootstrap3.3.7的css文件后就会出现两个上传按钮，取消引入后，又正常了。
不知道算不算bug
还是本来就不提倡共用

**Comment by Robinson28years** [comment]
是在laravel5.4的blade模版中，使用这个组件就会出现重复。然后我把laravel默认引入的bootstrp3去掉又正常了。

**Comment by Robinson28years** [comment]
![qq 20170209094101](https://cloud.githubusercontent.com/assets/19591259/22765576/0e459bba-eeac-11e6-9b4a-580420ff2374.jpg)
## 这是那个重复的组件对应的html

**Comment by Leopoldthecoder** [comment]
不提倡共用。
