### ISSUE TITLE
[Documentation Bug] JsFiddle links broken after viewing the FORM component page

### ISSUE THREAD

**Issue by chanonroy** [ElemeFE/element#2741]
Hello friends, 

After visiting the /component/form page, Chrome produces this error in the console:

`This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.`

After that, I can't click on any `Try It` JSFIDDLE button and this console error appears: 

`Form submission canceled because the form is not connected`

The issue remains even on browser cache clear and restart. Please advise a fix.

<img width="1312" alt="screen shot 2017-02-08 at 12 41 10 pm" src="https://cloud.githubusercontent.com/assets/16366896/22749625/fcc0b722-edfb-11e6-8742-4a1bf06b3bab.png">

**Comment by chanonroy** [comment]
Initial thought is that the password field on the form page in HTTP instead of HTTPS is making the browser upset.

**Comment by erguotou520** [comment]
The same as #2718 
Refer https://developers.google.com/web/updates/2016/10/avoid-not-secure-warn
@Leopoldthecoder 似乎是页面上有password字段的原因？

**Comment by chanonroy** [comment]
Sorry for repost. @erguotou520 @Leopoldthecoder - would moving the site to HTTPS be a solution?

**Comment by Leopoldthecoder** [comment]
@chanonroy Yes. We'll try to move to HTTPS.

**Comment by Leopoldthecoder** [comment]
Update: http://stackoverflow.com/questions/42053775/getting-error-form-submission-canceled-because-the-form-is-not-connected

Seems the problem can be fixed quite easily.

**Comment by erguotou520** [comment]
Then try it!

**Comment by Leopoldthecoder** [comment]
@erguotou520 I did and it works.

**Comment by Leopoldthecoder** [comment]
The fix will be live with our next release.
