### ISSUE TITLE
tabs标签close时能不能有个“关闭时触发的事件”

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/element#2744]
![image](https://cloud.githubusercontent.com/assets/13248613/22765869/762ca952-eead-11e6-8ac5-8015eb23d36c.png)
现在说关闭就关闭了，没有一点点防备。。我就想问能不能有个gua关闭tabs时触发的事件？不要说关闭就关闭

**Comment by erguotou520** [comment]
用户越多场景越多，越做越复杂...

**Comment by hopkinson** [comment]
@erguotou520 但是tags关闭时也有关闭时触发的事件啊 ，这个tabs一删除也应该有吧

**Comment by erguotou520** [comment]
额，我不是针对这个issue，只是感慨...

**Comment by baiyaaaaa** [comment]
1.2会有一个更新，现在在组件里主动管理tab实例的实现是不妥当的。
