### ISSUE TITLE
development contributing guide的文档打不开

### ISSUE THREAD

**Issue by TingYinHelen** [ElemeFE/element#2746]
我想看一下源码，但是不知道怎么启动项目，然后想看development contributing guide那个文档，报404

**Comment by Leopoldthecoder** [comment]
贡献指南暂时还没合到主分支，直接打开这个就好：https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md

**Comment by TingYinHelen** [comment]
好的，谢谢:)
