### ISSUE TITLE
timepicker样式错乱

### ISSUE THREAD

**Issue by arixse** [ElemeFE/element#2747]
![timepicker](https://cloud.githubusercontent.com/assets/10278192/22770566/69407682-eecc-11e6-8978-57422ba79051.png)

**Comment by QingWei-Li** [comment]
没遇到过
![image](https://cloud.githubusercontent.com/assets/7565692/22773605/fe1ae678-eedd-11e6-871a-8fd809913a6b.png)

**Comment by Leopoldthecoder** [comment]
Windows 上会有这个问题，与 #2071 重复，请关注 #2071
