### ISSUE TITLE
select 组件远程搜索模式下无法使用中文输入法

### ISSUE THREAD

**Issue by nitta-honoka** [ElemeFE/element#275]
### ElementUI version
v1.0.0-rc.5

### OS/Browers version
macOS/Chrome 53

### Vue version 
2.0.0-rc.4

### Reproduction Link
[DEMO 页](http://element.eleme.io/#/component/select)也存在该情况

### What happened?
使用 select 组件远程搜索功能时，如果输入法为简体拼音时无法输入完整中文字符，测试输入法：QQ 简体输入法、macOS 简体输入法

**Comment by erguotou520** [comment]
测试：输入中文可以，但是好像有视觉上的问题，存在显示不全的情况

**Comment by Leopoldthecoder** [comment]
@nitta-honoka 测试了 macOS 简体输入法，确实存在你说的问题，我这边看一下原因
@erguotou520 显示不全的问题跟上面的一起修

**Comment by Leopoldthecoder** [comment]
@nitta-honoka 输入法的问题经确认是 Vue 的一个 bug：https://github.com/vuejs/vue/issues/3894 ，已经修复，但是还未发布。
