### ISSUE TITLE
用loadsh.remove删除table data中的一条记录,界面中没有响应

### ISSUE THREAD

**Issue by wenner** [ElemeFE/element#2752]
### ElementUI version
1.1.6

### OS/Browers version
Win10 , chrome55

### Vue version
2.1.0

### Reproduction Link
http://jsfiddle.net/wenner/2ufvrxyj/

### Steps to reproduce
当时是这样发现这个问题的
EL-Table中 , 删除一条记录 , 删除成功后从 :data 中移除
我一直用的是lodash , _.remove(this.data , record) , record就是点击删除的那个记录 , 可是没有任何错误 , 记录却没有被删除...就是还在页面中 , 可是输出的 data 已经删除了那条记录...左试右试...都有问题

#### 可是 以前一直是这样删除的而且都没问题 , 而且我马上回去测试以前那些没问题的页面 , 同样还是没问题...

我就不知道发生了什么了 , 所以我想测试一下, 就发了这个issue

 打开上面页面 , 这个页面是直接从官方TABLE第一个例子打开的
操作中查看 TABLE 界面的同时 查看 TABLE下的文本记录 , datalength数字 以及 TABLE 上面的SELECT  还有 console.log的记录

#### mounted
1. mounted 会用lodash remove 一条记录 (第一条05-02)  , 界面上并没有反应 **但是console输出的长度已经减少了**
__更新:  如果这时候打开select随便选中一个值,那么 文本,length,select 都会改变 , **但是表格不变**_ _
2. 可是如果拖动中间的分割线改变result窗口的宽度 , 那么界面就会少一条**但表格下的文本记录,length,select都没有变化**
3. 如果把mounted代码中的setTimeout去掉 , 或者把setTimeout的事件设小一点 比如 30 (这个时间我测试了多次,并不一定,可能跟机器,网络等相关????) , 那么就可以看到界面中记录已少了一条了 **但是,表格下面的文本记录以及length并没有改变 , 上面的select中同样也没有改变**

#### button click (这里可以把上面mounted中注释掉)
1. 点击 lodash remove 按钮 通过 _.remove() , 没有变化 , **但是console输出的长度已经减少了**
2. 拖动中间分割线 , 就会减少一条记录 , (文本记录,length,select不变)
3. 如果不拖动分割线 , 直接点击 array splice 按钮 , 会减少两条记录 , **同时文本记录,length,select都减少了两条记录**
4. 如果开始直接点击 array splice, 执行 array.splice() , 界面会直接变化 , 文本 , length , select 都会变化

情况比较多 , 不是很好描述 
array.splice 这种,会直接删除数据并反应到界面上
lodash.remove 会删除数据 , 可是界面并没有响应...(但是,我试验以前别的界面,都是可以的)

所以,想知道这是什么原因...我得哪里写错了么??
1. 为什么mounted中 , setTimeout时间长短 , 界面会有响应呢?
2. 为什么改变了窗口宽度 , TABLE记录会有相应呢?
3. 为什么改变了窗口宽度 , TABLE记录有了响应  , 可是SELECT和文本记录,LENGTH还是没有反应呢??
4. SPLICE后把以前remove的记录也去掉了..

**Comment by wenner** [comment]
更新:
又试了一下 
http://jsfiddle.net/wenner/2ufvrxyj/4/
做了这些更改
1. 在data中加了rnd 
2. 在mounted中_.remove之后 , 更新rnd的值(随机值)
3. 在lodashremove中_.remove之后 , 更新rnd的值(随机值)
4. 在template中显示rnd , {{rnd}}
这样 , 文本列表 , length , select中option , 全部都正常了, 都会跟着remove进行响应
可是 table 就没有响应 , 只有改变窗口宽度才会让table响应

### 另外,如果把上面4去掉, 就是不在html模板中显示rnd , 没有 {{rnd}} , 那么 , 刚才正常的那些又不起作用了

这究竟是什么问题...如何去vue的issue里搜索啊:(

**Comment by erguotou520** [comment]
删除data里的数据用 `data.splice(data.indexOf(scope.row),1)`方法删除

**Comment by mu-yu** [comment]
https://cn.vuejs.org/v2/guide/list.html#注意事项

主要是vue不支持吧……

**Comment by erguotou520** [comment]
不是很清楚，我看了下lodash源码（水平有限）也不是很明白，但是我一般都用splice来删除

**Comment by wenner** [comment]
@mu-yu ....我还一直用这个删除...没用过vue文档里的那个数组变异方法,当时看过那部分文档,因为lodash用的比较熟,一直没有细看.......有点二了..

@erguotou520 ...那以后我也用这个...确保没问题就好了...看有官方的人看到的话能稍微解释一下把..


谢谢啦

**Comment by erguotou520** [comment]
@mu-yu 我是因为看到lodash里的代码似乎也是用的splice所以才没直接下结论...

**Comment by wenner** [comment]
@erguotou520 是的..我昨天翻了下lodash remove的代码 , 最终就是splice , 而关键是数据也改变了 , 就是界面没有响应...
就像以前用ng , 有时候需要用 $apply 或者 $digest 来一下一样

**Comment by QingWei-Li** [comment]
不清楚 lodash 如何做的。还是按照传统的方式弄吧。。

**Comment by gcdd1993** [comment]
@QingWei-Li 我今天也遇到了此问题，使用lodash的remove无法触发Vue视图更新，不知道这篇文章是否能解释这个问题https://juejin.im/post/6844903711571968007
