### ISSUE TITLE
Layout (grid) component col-hidden-* feature suggestion

### ISSUE THREAD

**Issue by jonny-novikov** [ElemeFE/element#2757]
I can't find the default options (props) and css classes for hiding columns with responsive layout.

Example:
 
    <el-row>
        <el-col :lg="18" :md="18" :sm="24">
        </el-col>
        
        <el-col :lg="6" :md="6" :sm="hidden"> 
        </el-col>
    </el-row>

Any suggestions or plans?

**Comment by ndabAP** [comment]
https://github.com/ElemeFE/element/issues/2732

**Comment by Leopoldthecoder** [comment]
See #2732 for updates.

**Comment by dimirc** [comment]
@Leopoldthecoder I read at #2732 that this library isn't intended for mobile and understand and agree with you. But keep in mind that there might be cases that it's not for mobile uses that this classes could be use. Actually I just open #2902 some minutes ago just asking similar as this issue and our use case isn't for mobile but just to be able to show more info for example on bigger screens

**Comment by madisvain** [comment]
Completely agree with dimirc here. It's an extremely useful feature to have.

**Comment by jonny-novikov** [comment]
https://github.com/ElemeFE/element/issues/2732 opened again for discussion
