### ISSUE TITLE
table组件，支持搜索，和子表单，搜索可选远程以及本地的数据加载

### ISSUE THREAD

**Issue by jerry-he** [ElemeFE/element#276]

**Comment by erguotou520** [comment]
每个组件不可能适应所有的场合，如果增加太多的功能，对于其他使用者来说是完全没必要的，这里就存在设计过度的问题了。

**Comment by furybean** [comment]
@jerry-he bootstrapTable 的链接能给一个么？

**Comment by erguotou520** [comment]
应该是这个http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by furybean** [comment]
该 issue 的 feature request 不太明确。子表单的功能和 #961 重复，所以关闭。
