### ISSUE TITLE
关于tree组件中   default-expanded-keys方法的使用方法

### ISSUE THREAD

**Issue by zhanmy** [ElemeFE/element#2762]
请有经验的老师来发下tree组件中 展开指定节点这个方法的使用方式，实在是没搞懂，default-expanded-keys属性给的参数应该怎么写，能否发给demo给我看看， 项目开发中 在线等感激不尽

**Comment by zhanmy** [comment]
已经解决

**Comment by hookehuyr** [comment]
也遇到问题了, 到底应该怎么写呢?

**Comment by Leopoldthecoder** [comment]
参考： https://github.com/ElemeFE/element/pull/2713/files#diff-f52977e061ce05f21ebff84c15289101R366
