### ISSUE TITLE
Elementui  实现在table编辑

### ISSUE THREAD

**Issue by HzqWebSite** [ElemeFE/element#2763]
### What is Expected?
想用elementui实现在table中编辑，请问有没有大神指点该怎么做？

**Comment by erguotou520** [comment]
![image](https://cloud.githubusercontent.com/assets/7945757/22812285/cde9eeb2-ef7e-11e6-8595-be4e8ad66b4e.png)

要的这种功能吧？其实很简单啊，table的data数组里的每个对象加一个`isEditing`标示下，然后用`v-show`控制是显示文字还是输入框

**Comment by Kingwl** [comment]
这玩意貌似不太适合扔到组件库里

**Comment by Leopoldthecoder** [comment]
不会放在组件里，请参照@erguotou520 的方法。

**Comment by justnowanna** [comment]
v-show 写在什么地方？table不是直接绑定的data,不用自己去做v-for么。v-show是写在哪里？

**Comment by erguotou520** [comment]
`el-table-item`的`scoped slot`里

**Comment by justnowanna** [comment]
@erguotou520 就是说不能用`<el-table :data="tableData"></el-table>`绑定数据了，要用v-for来循环`el-table-item`来展示数据了吗？

**Comment by justnowanna** [comment]
@erguotou520 现在官网的示例都是用`el-table-column`,这样要自己来做循环才可以吗？

**Comment by erguotou520** [comment]
非也，你看看[scoped slots](https://vuejs.org/v2/guide/components.html#Scoped-Slots)

**Comment by justnowanna** [comment]
哦。我知道你的意思了。我这里是这样做的动态表头，就像最后的操作这样做的。我大概知道了。谢谢你回复我。
![qq 20170509183411](https://cloud.githubusercontent.com/assets/7813730/25846855/2aecdfbe-34e6-11e7-83fa-9fee7d532920.png)

**Comment by justnowanna** [comment]
@erguotou520

**Comment by liangxinhui** [comment]
非常感谢！

**Comment by Sir0xb** [comment]
Low. 还不如 $context 有个上下文环境来的好用

**Comment by shonve** [comment]
> 哦。我知道你的意思了。我这里是这样做的动态表头，就像最后的操作这样做的。我大概知道了。谢谢你回复我。
> ![qq 20170509183411](https://cloud.githubusercontent.com/assets/7813730/25846855/2aecdfbe-34e6-11e7-83fa-9fee7d532920.png)

你这个图中的写法是什么写法呀，怎么不像普通的html写法

**Comment by justnowanna** [comment]
@shonve Pug，原名Jade

**Comment by shonve** [comment]
@justnowanna 谢谢

**Comment by xuliangzhan** [comment]
可以参考这个 [editable](https://github.com/xuliangzhan/vue-element-extends)
