### ISSUE TITLE
el-radio在vue组件中无法根据prop传递的参数进行初始化

### ISSUE THREAD

**Issue by hyxdppt** [ElemeFE/element#2767]
### Vue version

《el-radio-group v-model="form.isDay"》
如果绑定值form.isDay不是直接在data中赋值，则初始选中效果无法呈现
更多问题陈述/代码展示及代码效果如下：
http://note.youdao.com/noteshare?id=a5c490e5714d8ebcec7cf0f1c738c6fb

**Comment by liril-net** [comment]
额，你这不是 `element-ui` 的问题，建议多看看 `vue`。

**Comment by hyxdppt** [comment]
是element版本没更新  虽然在package.json里配置，但没有删除掉node_modules里面的老版本模版，cnpm install的时候没有更新到element的版本

**Comment by mohong** [comment]
这样的问题该如何解决呢

**Comment by motiandashao** [comment]
谁能提供一个解决办法？

**Comment by mohong** [comment]
@motiandashao 

经过探索，以下是解决办法：

参考文档中的[这个案例](http://element.eleme.io/#/zh-CN/component/radio#dan-xuan-kuang-zu)，并注意：
- 在el-radio-group中绑定v-model (重要！！！)
- 在el-radio中设置好label即可，无需再给每一个el-radio绑定变量

**Comment by motiandashao** [comment]
`<el-radio-group v-model="pageForm.type">
                            <el-radio v-for="item in types" :label="item.id">{{item.title}}</el-radio>
                        </el-radio-group>`
那个简单的没问题，这种动态的还是不行

**Comment by Creabine** [comment]
@motiandashao  @hyxdppt 

遇到这个问题然后解决了，问题在于：v-model="pageForm.type"  和  :label="item.id" 的数据类型不一致，你都改成数字就好了。
