### ISSUE TITLE
Table组件支持Tree

### ISSUE THREAD

**Issue by flybears** [ElemeFE/element#2769]
RT...
看了之前有人提这方面的issue...回复说1.1版本之后会加，看了下更新日志table支持展开行....
想请问下目前支持Tree嵌套吗？

**Comment by Leopoldthecoder** [comment]
展开行具体可以查看文档上的例子：http://element.eleme.io/#/zh-CN/component/table#zhan-kai-xing

是不支持 Tree 嵌套的。

**Comment by dandananddada** [comment]
table什么时候提供tree table组件啊。
