### ISSUE TITLE
Table中动态显示列的时候,宽度出现BUG

### ISSUE THREAD

**Issue by wenner** [ElemeFE/element#2770]
### ElementUI version
1.1.6
### OS/Browers version
Win10 , chrome 55

### Vue version
2.1.0

### Reproduction Link
http://jsfiddle.net/1afd4s7v/14/

### Steps to reproduce
可以直接看例子里面的文字

最后可以正常显示 , 但是并不知道原因...

虽然猜测可能需要类似Vue.set的操作...

求解惑.

==========
###
再次更新:
我以为我解决了...然后发了个Issue , 然后就去改项目里真正table , 然后,就出现问题了...既然用v-bind:width就OK了...可是到了项目里..依然还是这个问题...
是因为table第一个column是 type='index' , 然后 动态的column怎么设置都不行 , 都不行.... index column 怎么设置都不行 ... 
或者随便吧一个列加到 v-for列的前面 .. 就怎么都不行....

**Comment by KwongHing** [comment]
el-table-column 的宽度这样写就没问题   :width="120"，但动态显示列有个问题就是个别列会显示成其它固定列的内容（span显示成其它列的input），解决方法就是固定列放前边.....

**Comment by KwongHing** [comment]
动态显示列有个问题就是个别列会显示成其它固定列的内容（比如动态列的span显示成其它固定列的input），临时解决方法就是固定列放前边.....
