### ISSUE TITLE
el-select scrollbar style bug (firefox)

### ISSUE THREAD

**Issue by tomieric** [ElemeFE/element#2771]
### ElementUI version

`v1.1.6`

### OS/Browers version

`Firfox 50.1.0`

### Vue version

`2.1.0`

### Reproduction Link

[http://element.eleme.io/#/zh-CN/component/select](http://element.eleme.io/#/zh-CN/component/select)

### What is actually happening?

火狐下下拉框有样式问题

![el-select](http://oenwuky9h.bkt.clouddn.com/el-select.png)

使用了`el-scroller` 是否考虑将原生滚动条隐藏？
```
.el-scrollbar__wrap {
  // overflow: scroll;
  overflow: hidden;
}
```

**Comment by renxia** [comment]
应该改为 `auto` 才对。不知道为什么药用 `scroll`

```
.el-scrollbar__wrap {
  overflow: auto;
}
```

**Comment by Leopoldthecoder** [comment]
1.2.1 版本已经修复了。
