### ISSUE TITLE
form表单校验规则

### ISSUE THREAD

**Issue by gloxing** [ElemeFE/element#2772]
http://jsfiddle.net/6mqg3ddb/
require和patten同时出现时，必填的规则不会触发

**Comment by Liupeng8** [comment]
rules: {
        smsPhoneNum: [
          {required: true, message: '发送对象不能为空！', trigger: 'blur'},
          {pattern: /^1[34578]\d{9}(\+1[34578]\d{9})*$/, message: '手机号码格式错误！', trigger: 'blur'}
        ]
      }
我刚用了这个功能，亲测可用

**Comment by gloxing** [comment]
@Liupeng8  原来是写两条可以用，没看到aync-valid和elemen有说明用法，我是写在一起了，怪不得不能用，谢谢了

**Comment by hqzh** [comment]
可以写一起的，下面是校验空格和必填
`  {
              required: true,
              pattern: /\S/,
              message: "请输入导出文件名！",
              trigger: "blur"
            },`
