### ISSUE TITLE
tooltip交互建议

### ISSUE THREAD

**Issue by xilixinluo** [ElemeFE/element#2777]
目前tooltip组件无法复制内容，即使光标在tooltip上，toolTip还是会关闭。
![image](https://cloud.githubusercontent.com/assets/6066509/22859308/58990fd6-f112-11e6-84ef-0248504d60f6.png)
建议完善至可以完成如图所示交互
![image](https://cloud.githubusercontent.com/assets/6066509/22859310/6e8b69ba-f112-11e6-886c-bff3241baa44.png)

**Comment by QingWei-Li** [comment]
1.2 已经支持了，预计这周发布。issue 先关了
