### ISSUE TITLE
npm run dev失败(lerna.json does not exist...)

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#278]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
 window 7 64bit/chrome 53.0.2785.143 m

### Vue version
2.0.0-rc.8

### What is Expected?
npm run dev 成功

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/3336443/19218619/0a935696-8e31-11e6-9581-6ef04bc29b2a.png)

**Comment by QingWei-Li** [comment]
lerna.json 文件还在？

**Comment by changchengqin** [comment]
@QingWei-Li 不在

**Comment by QingWei-Li** [comment]
那你检查下 clone 的代码是否和仓库代码一致

**Comment by changchengqin** [comment]
@QingWei-Li 谢谢
新手失误,
都没有Clone下来,
就直接运行
npm install element-ui@next -S
npm run dev
这两个命令了.
