### ISSUE TITLE
Table sortable不能动态修改？

### ISSUE THREAD

**Issue by OMGVecchio** [ElemeFE/element#2782]
在`el-table-column`中动态绑定`sortable`的值，之后修改该值的时候无法触发筛选项的更新？

**Comment by imac8t** [comment]
确实不能 坐等fix

**Comment by imac8t** [comment]
发现加了key之后正常了？文档找不到这个key的内容

**Comment by imac8t** [comment]
column-key	column 的 key，如果需要使用 filter-change 事件，则需要此属性标识是哪个 column 的筛选条件

应该是这个key吧?

**Comment by OMGVecchio** [comment]
@imac8t 加了key，重新渲染是可以的
> key 的特殊属性主要用在 Vue的虚拟DOM算法，在新旧nodes对比时辨识VNodes。如果不使用key，Vue会使用一种最大限度减少动态元素并且尽可能的尝试修复/再利用相同类型元素的算法。使用key，它会基于key的变化重新排列元素顺序，并且会移除key不存在的元素。

**Comment by imac8t** [comment]
@OMGVecchio ( ╯□╰ ) 谢谢
