### ISSUE TITLE
el-select bug

### ISSUE THREAD

**Issue by pilife** [ElemeFE/element#2784]
### ElementUI version

1.1.6
### Vue version

2.1.10
### What is actually happening?
el-select 只进行 :value="" 绑定值时，@change=“”事件无法触发（只有v-model绑定才会出发）。而vue原生的select是支持只 :value=""的。（因为data刷新时，即使没有改变value，也会触发change事件，所以需要:value绑定用以判断value是否变化，而不是v-model双向绑定）

**Comment by Leopoldthecoder** [comment]
> 因为data刷新时，即使没有改变value，也会触发change事件

有能够重现这个问题的 demo 吗？

**Comment by LianyForWeb** [comment]
我在table组件的template里使用select组件 v-mode监听的是scope的属性 change居然触发了3次

**Comment by hustlzp** [comment]
我这边也没有触发。

```js
<el-select placeholder="请选择藏处" :value="book.get('location').id" @change="changeLocation">
    <el-option v-for="location in locations" :label="location.get('name')" :value="location.id"></el-option>
</el-select>
```

**Comment by Leopoldthecoder** [comment]
@pilife @hustlzp 参考一下 https://github.com/ElemeFE/element/issues/1632#issuecomment-265739660
@LianyForWeb 在 #2955 中修复了。
