### ISSUE TITLE
建议npm发个Beta版！

### ISSUE THREAD

**Issue by ohohco** [ElemeFE/element#2786]
建议针对更新的内容`npm`发布beta版本

**Comment by reverland** [comment]
觉得，如果git仓库包含`lib/`更好，这样直接

      npm install -S git地址

就好了

**Comment by ohohco** [comment]
@reverland 个人觉得 git 没必要包含lib吧，源码还是保持干净比较好！lib本来就是命令生成后的东西！

**Comment by reverland** [comment]
@ohohco npm直接安装方便啊，用unpkg的cdn也方便啊

看vue https://github.com/vuejs/vue/tree/dev/dist

**Comment by QingWei-Li** [comment]
自己 build
