### ISSUE TITLE
Dynamic el-alert component title & description from server

### ISSUE THREAD

**Issue by Ravichandrane** [ElemeFE/element#2787]
Hi, 
I want to know how to render title & description in **el-alert** component that coming from the server?

` <el-alert
    title="error alert"
    type="error"
    description="more text description"
    show-icon>
  </el-alert>
`

Thanks.

**Comment by Leopoldthecoder** [comment]
```html
<el-alert
  :title="myTitle"
  type="error"
  :description="myDescription">
</el-alert>
```

When data is returned from the server, assign the desired title and description to `this.myTitle` and `this.myDescription`.

**Comment by elbsurfer** [comment]
Can I use linebreaks in the description? I tried it with <br/> and \n - both are not working.

**Comment by areisyus** [comment]
> @Leopoldthecoder Can I use linebreaks in the description? I tried it with
> and \n - both are not working.

Did you managed to solve it?
