### ISSUE TITLE
el-autocomplete bug

### ISSUE THREAD

**Issue by alexchetv** [ElemeFE/element#2789]
### ElementUI version
1.1.6

### OS/Browers version
Win7/Chrome 56

### Vue version
2.1.10

### Reproduction Link

http://element.eleme.io/#/en-US/component/input

### Steps to reproduce
Press and hold left mouse button on an item in drop-down list
### What is Expected?
The list remains in place and item could be selected after mouse button release
### What is actually happening?
The list disappears and nothing was selected after mouse button release.

**Comment by baiyaaaaa** [comment]
fix in #5189
