### ISSUE TITLE
[DatePicker] The text of month is overflow in English

### ISSUE THREAD

**Issue by zcyzcy88** [ElemeFE/element#2792]
### ElementUI version
1.1.6

### OS/Browers version
all

### Vue version
2.0

<img width="331" alt="2017-02-13 06_22_04-component _ element - internet explorer" src="https://cloud.githubusercontent.com/assets/15178410/22866711/da2699c6-f1b5-11e6-8e55-7be7e1e9fb93.png">

**Comment by reverland** [comment]
Sep. may better

**Comment by stefanosandes** [comment]
Same problem in portuguese (Brazil).

![chrome_2017-02-13_16-35-06](https://cloud.githubusercontent.com/assets/6722075/22897370/91747ef0-f20a-11e6-9b4c-029543ad3a49.png)

The word "Ano" make no sense here. "2016 Dezembro" or, more formaly, "Dezembro de 2016" sounds better.

**Comment by Leopoldthecoder** [comment]
@stefanosandes `Ano` will be removed in the next release.
