### ISSUE TITLE
npm run build后的js代码内有css的代码，使用的官方vue-cli，按需引入ElementUi.

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#2793]
### ElementUI version

1.1.5
### Vue version

2.1.9

![image](https://cloud.githubusercontent.com/assets/6948367/22868784/935c62f4-f1d4-11e6-8eda-7c74a4100f7f.png)
![image](https://cloud.githubusercontent.com/assets/6948367/22868789/a7b63f72-f1d4-11e6-9bdc-1962b898d627.png)

**Comment by linmodev** [comment]
我也是按需引入的，但是webpack没有帮我找到相应的css，所以没有效果，现在正卡在这呢

**Comment by reverland** [comment]
@linmodev css要单独引入，除非用某babel插件了。

至于lz的按需引入js中有css代码，你用webpack extract text plugins了么

**Comment by linmodev** [comment]
@reverland 对，我的把.vue文件里的css。less单独提取了

**Comment by linmodev** [comment]
@reverland 不好意思，我好想回复错了，不过我也是使用了extract text webpack plugins,另外我的其它配制，和插件也都是按官方走的
##### 以下我的相关webpack配制
```javascript
{
                test: /\.vue$/,
                // use: ['vue-loader'],
                loader: 'vue-loader',
                options: {
                    loaders: {
                        // 对于文件内的css单独提取
                        css: extractCSS.extract({
                            loader: 'css-loader',
                            fallbackLoader: 'vue-style-loader'
                        }),
                        // 对于文件内的less单独提取
                        less: extractCSS.extract({
                            loader: 'css-loader!less-loader',
                            fallbackLoader: 'vue-style-loader'
                        })
                    }
                }
            },
            // 对于单个less文件的提取
            {
                test: /\.less$/,
                use: ['style-loader', 'css-loader', 'postcss-loader', 'less-loader']
            }
```

**Comment by ChangeZhang** [comment]
@reverland 我用的是vue官方的脚用架工具vue-cli。把所有按需引入的都放在main.js中，js文件中有css的代码的问题已经解决了。但是发现.vue文件中用scss写的css,npm run build后没有压缩。。。

**Comment by ChangeZhang** [comment]
![image](https://cloud.githubusercontent.com/assets/6948367/22870711/be170b06-f1e4-11e6-8ffb-0bb897077e36.png)
但是发现.vue文件中用scss自己写的css，npm run build 后没有被压缩。。。。郁闷~~~~

**Comment by reverland** [comment]
@ChangeZhang 

检查webpack的stat看看，看看你给scss的是什么loader。

这有两部分，.vue文件里style标签内的scss和通过js引用的真对scss文件的loader，看看哪里没配好

**Comment by QingWei-Li** [comment]
vue-loader 的问题请到相关仓库提问，也可以参考 https://github.com/ElementUI/element-starter 的配置
