### ISSUE TITLE
table-column组件的属性show-overflow-tooltip是否能同时在对应表头生效?

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#2795]
### What is Expected?
table-column组件的属性show-overflow-tooltip是否能同时在对应表头生效?

**Comment by QingWei-Li** [comment]
不能，不觉得这是个常见需求

**Comment by QingWei-Li** [comment]
可以自己用 renderHeader

**Comment by DylanYang01** [comment]
show-overflow-tooltip弹出的内容  怎么复制啊 现在是无法复制

**Comment by Even-Lau** [comment]
> show-overflow-tooltip弹出的内容 怎么复制啊 现在是无法复制

同问
