### ISSUE TITLE
table sortable不能动态改变

### ISSUE THREAD

**Issue by koalaqinqin** [ElemeFE/element#2798]
table sortable的值为一个变量，这个值改变的时候，sortable的值并不会动态改变

**Comment by liril-net** [comment]
请写一个 demo 重现一下。

**Comment by imac8t** [comment]
@koalaqinqin 确实不能

**Comment by imac8t** [comment]
@koalaqinqin  发现加了key之后正常了？文档找不到这个key的内容

**Comment by koalaqinqin** [comment]
+ `Vue2`采用的`virtual-dom`算法处理`DOM`元素的一些操作，有时你可能碰到此种算法引起的修改数据不生效的情况，可以试试`key`属性强制重新全部更新`DOM`。

    > `key`的特殊属性主要用在`Vue`的`虚拟DOM算法`，在新旧`nodes`对比时辨识`VNodes`。如果不使用`key`，`Vue`会使用一种最大限度减少动态元素并且尽可能的尝试修复/再利用相同类型元素的算法。使用`key`，它会基于`key`的变化重新排列元素顺序，并且会移除`key`不存在的元素

    > 有相同父元素的子元素必须有独特的`key`。重复的`key`会 造成渲染错误。

具体可参考：
[http://cn.vuejs.org/v2/api/#key](url)

**Comment by Bbottle** [comment]
请问下，你们加key值，是在什么地方加的？加的row-key吗？
