### ISSUE TITLE
table组件，增加监听列宽调整的事件

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/element#2799]
### ElementUI version

1.1.6

table组件能否增加一个 Events ？ 用来监听用户手动拖动列的宽度

项目中有个需求，是要同步两个table的列宽

**Comment by liril-net** [comment]
你的意思是，当用户改变外面容器的大小，从而让 `table` 重新自适应的时候，触发一个事件？

**Comment by rossroma** [comment]
不是，当用户调整列宽时，触发一个事件！ @liril-net

**Comment by liril-net** [comment]
@rossroma 现在好像还不支持拖动边框，你的意思是通过 `width` 设置宽度时，修改 `width` 值时触发吗？

**Comment by Leopoldthecoder** [comment]
@liril-net 拖动边框是支持的：http://element.eleme.io/#/zh-CN/component/table#dai-bian-kuang-biao-ge

**Comment by liril-net** [comment]
@Leopoldthecoder 快哭了，我把 `table` 看来一半了，没发现拖动。

**Comment by Leopoldthecoder** [comment]
@liril-net 应该是在这里：https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-header.js#L280

**Comment by furybean** [comment]
@liril-net 看一半就要哭，写的人岂不是哭了一个月 😅
