### ISSUE TITLE
[Tag] Edit Input unwanted space underneath

### ISSUE THREAD

**Issue by zcyzcy88** [ElemeFE/element#2807]
### ElementUI version
1.1.6

### OS/Browers version
non-WebKit browers

### Vue version
2.0

### What is actually happening?
<img width="355" alt="2017-02-13 20_10_57-component _ element - internet explorer" src="https://cloud.githubusercontent.com/assets/15178410/22882934/9389c34e-f228-11e6-8519-79a237cf4967.png">

### What is Expected?
<img width="343" alt="2017-02-13 20_14_46-component _ element - internet explorer" src="https://cloud.githubusercontent.com/assets/15178410/22883028/16c2ae56-f229-11e6-9185-d0185094b604.png">

### Why? How to fix it?
http://stackoverflow.com/questions/17905827/why-does-my-image-have-space-underneath

**Comment by Leopoldthecoder** [comment]
Fixed in #2814
