### ISSUE TITLE
menu组件点击时动态向tabs组件中添加tab

### ISSUE THREAD

**Issue by codepan** [ElemeFE/element#2809]
网站左边使用的是menu组件，想在点击某一个菜单时，右边页面的上部分tabs组件中动态添加一个刚才点击的那个菜单对应的页面，该如何实现！
什么父子组件通信不好使，因为这是两个独立的组件

**Comment by baiyaaaaa** [comment]
请别滥用issue 谢谢，有最佳实践疑问请到 gitter 求助
