### ISSUE TITLE
属性命名建议

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#281]
`RadioButton`,`Radio`,`Option`等组件的`value`值由`label`属性设置，给人感觉很奇怪的样子，建议统一成`value`

**Comment by baiyaaaaa** [comment]
因为 vue2 中只能通过 value 属性实现双向绑定，所以这些组件的绑定值属性名都使用了 value，导致组件的 value 值只能通过别的属性来设置，所以选择了一个比较合乎语义的 `label`.

**Comment by erguotou520** [comment]
OK
