### ISSUE TITLE
[Tag] Edit Input is not auto focus after clicked

### ISSUE THREAD

**Issue by zcyzcy88** [ElemeFE/element#2812]
### ElementUI version
1.1.6

### OS/Browers version
all

### Vue version
2.0

### Steps to reproduce
1. click
2. see the input

### What is Expected?
The input is auto focus

### What is actually happening?
The input is not auto focus, need another click

<img width="354" alt="2017-02-13 21_33_25-component _ element - internet explorer" src="https://cloud.githubusercontent.com/assets/15178410/22885406/464186ec-f234-11e6-83f0-6e11f0ea4c02.png">

**Comment by Leopoldthecoder** [comment]
Already fixed: https://elementui.github.io/dev/dev/#/en-US/component/tag
The main website will be updated with our next release.
