### ISSUE TITLE
Mask on input?

### ISSUE THREAD

**Issue by fscardua** [ElemeFE/element#2813]
Is there any support to create a currency mask on input element?

**Comment by Leopoldthecoder** [comment]
No there isn't.

**Comment by fscardua** [comment]
Ok, it would be nice if this feature is in the next version.
Just suggestion. 
Thanks

**Comment by codelabstudios** [comment]
I also think this feature would be great. I tried to integrate other packages, but the v-directive doesn't get applied on the input element, but on the wrapper
