### ISSUE TITLE
Tree组件的修改建议

### ISSUE THREAD

**Issue by wumaohui** [ElemeFE/element#2815]
希望Tree可以提供处理单个节点的方法，可以根据某些属性控制节点是否可选或单选，也可以显示节点除名字外的其他属性。

**Comment by qwvpn** [comment]
希望在lazy模式下可以自定义:
1.checkbox的状态的三种状态：全部选中，部分选中，未选中。但目前只能定义未选中和未选中状态，不能定义部分选中.
2.希望可以定义节点是否可展开，也就是是否有三角形小标。目前全部默认都会有子节点，即有三角形小标

**Comment by befreeFE** [comment]
建议Tree的checkBox添加单击事件，这样方便实现check-strictly模式下的全选功能。有些场景不会用到checkbox的不确定模式。(需求是子选项选中后父级自动选中，点击父级自动或取消全选子级) [http://fineui.com/demo_mvc/#/demo_mvc/Tree/CheckBoxCheckAll](url)

**Comment by tianxiaofeng747** [comment]
tree  数据量大的时候点击展开节点会比较卡， 请修复。

**Comment by furybean** [comment]
@qwvpn
2.希望可以定义节点是否可展开，也就是是否有三角形小标。目前全部默认都会有子节点，即有三角形小标

使用 props.isLeaf 属性。

@befreeFE  #9730 已经增加 check 事件。

@tianxiaofeng747 请单独开 issue。

@wumaohui render-content 或者 scoped slot 可以定义节点内容。
