### ISSUE TITLE
message传递过程titile丢失

### ISSUE THREAD

**Issue by fyname** [ElemeFE/element#2817]
环境:
vue2.0
element 1.1.6
系统: ie,firefox,chorme
使用组件:
  this.$message({
          message: '用户或密码不能为空!'
        })

期望结果：用户或密码不能为空
实际结果:   ''
message传递过程titile丢失。

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by p2ng** [comment]
@fyname 

http://element.eleme.io/#/zh-CN/component/message
http://element.eleme.io/#/zh-CN/component/notification

message都没有title属性，

**Comment by fyname** [comment]
message: '用户或密码不能为空!'  应该传递‘用户或密码不能为空!’，但是实际上为''
