### ISSUE TITLE
请问有没有考虑在未来支持自适应？

### ISSUE THREAD

**Issue by whxaxes** [ElemeFE/element#2818]
rt

虽然知道有个 mint-ui 可以支持移动端的设备，但是毕竟与 element-ui 是完全不一样的，相当于另一个工程了。

**Comment by Leopoldthecoder** [comment]
暂时不考虑。

**Comment by furybean** [comment]
如果自适应指的是响应式，那应该现在就支持。

**Comment by Leopoldthecoder** [comment]
是的，响应式目前支持。
如果指的是桌面端和移动端共用一套代码，比如侧边栏导航在移动端有抽屉效果，那么是不支持的。
