### ISSUE TITLE
popover在el-table下的表现问题

### ISSUE THREAD

**Issue by NadokaCiel** [ElemeFE/element#2819]
应用场景：
在表格最后一栏使用popover来做操作提示
但是当操作这一栏被固定时，或者表格内有任意列被固定时，popover不能正常弹出了

在el-table-column当中的fixed="right"影响了popover绑定的v-model，在去掉以后可以正常运作
麻烦请教一下这是出于设计的考虑还是bug……谢谢啦

参考demo：
http://jsfiddle.net/f8rqagdm/3/

**Comment by liril-net** [comment]
@NadokaCiel 是不是已经修复？

**Comment by NadokaCiel** [comment]
@liril-net 上述例子在1.2.0中已经可以正常运行啦，辛苦~

**Comment by angeltxwh** [comment]
你的例子并不能成功运行啊？

**Comment by NadokaCiel** [comment]
@liril-net  @angeltxwh 
现在在最新版本里又不行了……是不是这部分的代码有被覆盖？

**Comment by liril-net** [comment]
@NadokaCiel 额，因为目前的解决方案有更大的冲突问题，所以先恢复回去了。

**Comment by juzhishang** [comment]
我们的临时解决方案是再写个组件把popover封装一下，主要是因为popover中有的v-model属性，设置表格操作列固定，实际是又生成了一个表格，然后就冲突了。。。但如果popover里面没有控制关闭的按钮，这种方案也是不行的。那就不设置v-model，关闭通过方法模拟点击= =！

**Comment by eggxfmeng** [comment]
Same issue encountered. The 'v-model' for popover doesn't work when a popover is in a slot-scope of table.

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/f8rqagdm/11/ It works in the latest version.
