### ISSUE TITLE
table 里面 某一列table-column 能否根据 条件/函数返回值 显示/隐藏

### ISSUE THREAD

**Issue by BillionChen** [ElemeFE/element#2820]
table 里面 某一列table-column 能否根据 条件/函数返回值 显示/隐藏

或者说
如何给某一列,整一列的td 加一个class 用table外面的class控制显示隐藏?

api文档里面没有找到这方法

**Comment by kopheece** [comment]
http://jsfiddle.net/kopheece/1zrt5z95/

**Comment by BillionChen** [comment]
万分感谢..还能这样用...

**Comment by pang-y** [comment]
多级表头列 隐藏出错怎么处理
