### ISSUE TITLE
table组件能否像ext那样添加筛选列的功能

### ISSUE THREAD

**Issue by Sweisi** [ElemeFE/element#2821]
[ext表格筛选列](http://examples.sencha.com/extjs/6.2.0/examples/kitchensink/#array-grid)
![image](https://cloud.githubusercontent.com/assets/20529246/22921353/36a6776a-f2d4-11e6-9b42-4a8c4c699c7b.png)

**Comment by Sweisi** [comment]
[n3ui](http://www.n3ui.org/v2.html#n3DataTableDocs)
或者这样也行
![image](https://cloud.githubusercontent.com/assets/20529246/22922474/e8a518d2-f2d8-11e6-9f06-f6902a6141b4.png)

**Comment by Leopoldthecoder** [comment]
这个自己结合一些表单元素就能做到，组件本身不会提供：http://jsfiddle.net/ktttf1x0/
