### ISSUE TITLE
Tabs 标签页建议

### ISSUE THREAD

**Issue by joywen** [ElemeFE/element#2822]
Tab页能实现单个可关闭，而不仅仅是全部可关闭

**Comment by Leopoldthecoder** [comment]
目前版本就支持：http://jsfiddle.net/m3bn134d/

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/vcgftLvn/27/
文档里有写啊
![image](https://cloud.githubusercontent.com/assets/8121621/22922949/917eb944-f2da-11e6-9588-1ec58225e749.png)
