### ISSUE TITLE
你好,请问 el-date-picker 时间控件可以仅仅初始化时间的值吗

### ISSUE THREAD

**Issue by snecker** [ElemeFE/element#2826]
![image](https://cloud.githubusercontent.com/assets/4178594/22957064/e96858be-f360-11e6-8acd-9f567533744e.png)

如图,我想仅仅初始化时间为 00:00:00,而不是当前时间

**Comment by liril-net** [comment]
可以，你绑定的时直接设置。

**Comment by PanJiaChen** [comment]
这样么？
http://jsfiddle.net/20wp38p2/1/

**Comment by Create-Peace** [comment]
我当时是使用@change获取值的，后来不知道怎么回事，每次@change后的方法没有执行？

**Comment by snecker** [comment]
不是,我是希望默认 input是空的,点击之后弹出的datepicker上面的时间是00:00:00,如果设置value,input里面也有值了

**Comment by snecker** [comment]
如果是type=datetimerange的话,日期默认是今天,时间默认的是00:00:00,不是当前时间,不知道datetime是否也能这样设置

**Comment by huicanvie** [comment]
有解决方案了么
