### ISSUE TITLE
clickoutside IE syntax Error

### ISSUE THREAD

**Issue by lichinlichin** [ElemeFE/element#2828]
### ElementUI version
^1.1.6

### OS/Browers version
windows 7/IE10,IE11

### Vue version
2.1.10-rc.4

### Steps to reproduce
I want to use clickoutside
```javascript
import Clickoutside from 'element-ui/src/utils/clickoutside';
```
but in dev mode cause syntax Error in IE
I found that clickoutside.js[es6] didn't transform to es5
I try to add the code below into my .babelrc
```javascript
 "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]]
``` 
my .babelrc
```javascript
"presets": [
    ["es2015", { "modules": false }],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime",
    [
      "component", [
        {
          "libraryName": "element-ui",
          "styleLibraryName": "theme-default"
        }
      ]
    ]
  ],
```
I also npm install the babel-plugin-compontent
but it didn't work.
Is it correct?
### What is Expected?
or how about export the util-file to global?
appreciate for your answer.

**Comment by QingWei-Li** [comment]
You need to load from `lib` folder
```js
import Clickoutside from 'element-ui/lib/utils/clickoutside'
```

**Comment by jingleding** [comment]
我这边在ie下无法运行
使用的是elementui 2.12.0
vue 2.6.10
其他浏览器下是好的
