### ISSUE TITLE
DatePicker 日期选择器选择日期没有触发change事件

### ISSUE THREAD

**Issue by Create-Peace** [ElemeFE/element#2829]
为什么我使用@change时，修改日期后没有触发相关的方法的调用，
```
<el-date-picker
              v-model="choosedTime.timeBeg"
              type="date"
              placeholder="选择日期下限"
              @change="chooseDate"
              :picker-options="pickerOptions0">
            </el-date-picker>
```
```
 methods: {
    chooseDate (val) {
      console.log(val)
    }
}
```

**Comment by lchreal6** [comment]
我也遇到同样的问题 ，请问找到解决方法吗？

**Comment by Leopoldthecoder** [comment]
有问题请提供 demo

**Comment by YYM08103667** [comment]
这里是有的，链接和图片附上，请楼主去看下：http://element.eleme.io/#/zh-CN/
component/date-picker

------------------------------
yym08103667@gmail.com


*发件人：* lchreal6 <notifications@github.com>
*发送时间：* 2017-02-28 10:52
*收件人：* ElemeFE/element <element@noreply.github.com>
*抄送：* Subscribed <subscribed@noreply.github.com>
*主题：* Re: [ElemeFE/element] DatePicker 日期选择器选择日期没有触发change事件 (#2829)

我也遇到同样的问题 ，请问找到解决方法吗？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ElemeFE/element/issues/2829#issuecomment-282926383>,
or mute
the thread

**Comment by XZZsr** [comment]
问题出现在model上，我也遇到了，也说不太明白，这种情况是model

**Comment by callmewhy** [comment]
我也遇到了，官方的源代码，change 不会触发

**Comment by mini-peanut** [comment]
改成@input就可以用了，应该是文档有误

**Comment by mini-peanut** [comment]
@Create-Peace @lchreal6 改成@input就可以了，应该是文档有误

**Comment by MaskHao** [comment]
> @Create-Peace @lchreal6 改成@input就可以了，应该是文档有误

改成input 是触发了事件，也修改了数据，但datePicker组件显示还是原来的值

**Comment by yyccQQu** [comment]
> > @Create-Peace @lchreal6 改成@input就可以了，应该是文档有误
> 
> 改成input 是触发了事件，也修改了数据，但datePicker组件显示还是原来的值
@change => 改成@input就可以了

**Comment by yyccQQu** [comment]
> > @Create-Peace @lchreal6 改成@input就可以了，应该是文档有误
> 
> 改成input 是触发了事件，也修改了数据，但datePicker组件显示还是原来的值

遇到了一样的问题

**Comment by yyccQQu** [comment]
> 有问题请提供 demo

```
<el-date-picker
    class="pull-width"
    v-model="addTime"
    type="datetimerange"
    align="right"
    :start-placeholder="$t('common.startTime')"
    :end-placeholder="$t('common.endTime')"
    format="yyyy-MM-dd HH:mm:ss"
    value-format="timestamp"
    :pickerOptions="pickerOptions"
    @input="changeDate"
    :default-time="['00:00:00', '23:59:59']"
>
</el-date-picker>
// 修改状态的时候 addTime有默认值
addTime： [1581267600000, 1581958799000]
// 重新渲染 addTime 能正确赋值
->
然后 重新选择时间，组件的值不能正确渲染（还是原来的值）
但是提交的时候，上传值是正确的

      changeDate(val){
            // this.addTime = val;
            this.$set(this,'addTime',val)
            console.log(val,'val',this.addTime)
        }



```

**Comment by yyccQQu** [comment]
> > @Create-Peace @lchreal6 改成@input就可以了，应该是文档有误
> 
> 改成input 是触发了事件，也修改了数据，但datePicker组件显示还是原来的值

不能传入obj 对象 只能固定的帮一个数组值

ruleFormTimes:[0,0]

```js
                      <el-date-picker
						class="pull-width"
						v-model="ruleFormTimes"
						type="datetimerange"
						align="right"
						:start-placeholder="$t('common.startTime')"
						:end-placeholder="$t('common.endTime')"
						format="yyyy-MM-dd HH:mm:ss"
						value-format="timestamp"
						:pickerOptions="pickerOptions"
                        :default-time="['00:00:00', '23:59:59']"
					>
					</el-date-picker>
```

**Comment by wuhongru222** [comment]
还没解决么 四年了

**Comment by carolin-violet** [comment]
有时候改变时分秒后无法触发change，这个问题有什么解决方法吗
