### ISSUE TITLE
el-checkbox无法选择

### ISSUE THREAD

**Issue by cshhs** [ElemeFE/element#2831]
el-checkbox在el-checkbox-group包裹下无法选择

**Comment by Leopoldthecoder** [comment]
请给 demo

**Comment by cshhs** [comment]
经过测试发现弹出el-popover 里面的el-checkbox-group里面的el-checkbox-group无法选中

**Comment by cshhs** [comment]
<el-popover
                  ref="popover4"
                  placement="right"
                  width="400"
                  height="150"
                  >
                  <div class="labelHandView">
                  <div class="topView">
                  <div class="topView_Scrol">
                  <el-checkbox-group v-model="labelNameCheckList" @change="change">
                  <el-checkbox v-for="item in labelCheckList" :label="item.label_name">{{item.label_name}}
                  </el-checkbox>
                  </el-checkbox-group>
                  </div>
                  </div>
                  <div class="bottomView">
                  <el-button type="success" style="width: 400px">保存</el-button>
                  </div>
                  </div>
                  </el-popover>

**Comment by cshhs** [comment]
<el-popover
                    ref="popover4"
                    placement="right"
                    width="400"
                    height="150"
                  >
                    <div class="labelHandView">
                      <div class="topView">
                        <div class="topView_Scrol">
                          <el-checkbox-group v-model="labelNameCheckList" @change="change">
                            <el-checkbox v-for="item in labelCheckList" :label="item.label_name">{{item.label_name}}
                            </el-checkbox>
                          </el-checkbox-group>
                        </div>
                      </div>
                      <div class="bottomView">
                        <el-button type="success" style="width: 400px">保存</el-button>
                      </div>
                    </div>
                  </el-popover>

**Comment by Leopoldthecoder** [comment]
无法重现：http://jsfiddle.net/zqqfvczf/

**Comment by leemy9603** [comment]
在本地会有bug，但jsfiddle.net有效果

**Comment by leemy9603** [comment]
我也出现这个问题，在本地会有Bug，但是copy到jsfiddle进行在线演示时没有错误

**Comment by DDDenial** [comment]
我也出现了这个问题？请问你们是怎么解决的？

**Comment by Lokep** [comment]
> 我也出现了这个问题？请问你们是怎么解决的？

虽然已经过去很多年了，还是想问问，这个问题是怎么解决的
