### ISSUE TITLE
input组件图标不能放到左边

### ISSUE THREAD

**Issue by codepan** [ElemeFE/element#2832]
input组件的icon属性设置的图标只能出现在右边，没有提供放在左边的属性

**Comment by kopheece** [comment]
可以的  http://jsfiddle.net/kopheece/93b6861m/

**Comment by walnutzhang** [comment]
@kopheece 通过slot确实可以，题主说的可能是通过 el-input 的 icon 属性设置的。这个好像不能放到左边？

**Comment by QingWei-Li** [comment]
是的，只能通过 solt
