### ISSUE TITLE
tabs中tab bar 采用badge组件，badge组件的值是上一次更新的值。

### ISSUE THREAD

**Issue by wangscu** [ElemeFE/element#2839]
tabs中tab bar 采用badge组件，badge组件的值是上一次更新的值。
例子如下：
http://jsfiddle.net/mncm118z/3/
![image](https://cloud.githubusercontent.com/assets/691378/22963956/fe90651c-f390-11e6-98ca-57b9796b0580.png)

### ElementUI version

1.1.6

### OS/Browers version

macOS/Chrome 54
### Vue version

2.0

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/2843
http://jsfiddle.net/yoko8vxe/3/

**Comment by jiaqizhang77** [comment]
请问这个问题解决了吗？更新value的数据不能更新
