### ISSUE TITLE
radio 无法绑定number

### ISSUE THREAD

**Issue by callmesoul** [ElemeFE/element#2840]
radio 无法绑定number

**Comment by Leopoldthecoder** [comment]
请给 demo

**Comment by bulaye** [comment]
@Leopoldthecoder  radio绑定数字上我发现这样一个问题：对radio绑定数字，model 为radioValue=‘1’，需要是字符串，但是在radio-group中，model为 radioValue2=1，需要是number。不是很统一，不知道设计目的是怎样的。源码radio.vue文件中radio class中有i 'is-checked': model === label,‘===’判断，类型不同则is-ckecked属性不能为true

**Comment by Leopoldthecoder** [comment]
@bulaye 没看懂你的意思，`radio` 和 `radio-group` 都是既可以绑定数字又可以绑定字符串的。

**Comment by bulaye** [comment]
@Leopoldthecoder 又试了一下，发现自己搞错了 只考虑radio绑定数字的情况，如果写 ：label = “3” (label有冒号)则 data中 radiio：1 （number），如果写 label="1"（label前没有冒号）则data中radio：‘1’（string），是不是这样？
