### ISSUE TITLE
[bug] timepicker在选择9,10,11,  19,20,21，凡是10的倍数的临界值是总是取不到正确结果

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#2841]
[bug] timepicker在选择9,10,11,  19,20,21，凡是10的倍数的临界值是总是取不到正确结果

例如我点击分钟里的 29再点30, 30就取不到，还是29
demo:  [官网demo](http://jsfiddle.net/api/post/library/pure/)

**Comment by QingWei-Li** [comment]
没有复现问题，demo 链接是无效的。如果还有问题请重开 issue
