### ISSUE TITLE
el-radio是否可以通过v-for渲染生成？

### ISSUE THREAD

**Issue by radicalviva** [ElemeFE/element#2842]
```
        <el-radio-group v-model="user.is_group">
          <el-radio
            v-for="(item, index) of data_map.is_group_array"
            :label="index">
            </el-radio>
        </el-radio-group>
```
目前我是这样写的，但我的目的是这样的  `item` -> 显示的值 , `index` 选中的值
但是 `el-radio`只有`:label`没有`:value`额。。

**Comment by Leopoldthecoder** [comment]
```html
<el-radio-group v-model="user.is_group">
  <el-radio
    v-for="(item, index) of data_map.is_group_array"
    :label="index">
    {{ item }}
  </el-radio>
</el-radio-group>
```

**Comment by hwb2167sq** [comment]
请我单个的el-radio如何绑定事件

**Comment by hwb2167sq** [comment]
@Leopoldthecoder @radicalviva   请问单个的el-radio如何绑定事件
 <el-table-column  label="默认优先级">
                      <template scope="scope">
                          <el-radio  :label="scope.row.companyCode" model="companyCode" @change="setDefault">默认</el-radio>
                      </template>
                  </el-table-column>

看了文档只能给Radio-group绑定事件，不能给单个的radio绑定事件

**Comment by JH46666** [comment]
<el-form-item label="括展上级："> 
                            <el-radio v-model="addForm.extendSuperType" label="ZUIPIN" @click.native="deleteExtendSuperNo" >醉品</el-radio>
                            <el-radio v-model="addForm.extendSuperType" label="AGENT">代理商</el-radio>                          
                    </el-form-item>

**Comment by kkqqo** [comment]
Correct Answer:
Add an element to the radio label.

```
<el-radio-group v-model="user.is_group">
  <el-radio
    v-for="(item, index) of data_map.is_group_array"
    :label="index">
    <span v-text="item"></span>
  </el-radio>
</el-radio-group>
```
