### ISSUE TITLE
[bug] 表格固定列，会使其他列的事件执行次数增加

### ISSUE THREAD

**Issue by SeaHai** [ElemeFE/element#2844]
如果 Table 表格 中有固定列，则会影响其他列中的事件执行次数，目前测到的是，会使执行次数+1，即有一列固定则+1，左右列均固定，则执行次数+2

### ElementUI version
1.1.6

### OS/Browers version
Mac OS X/Chrome 56

### Vue version
2.1.10

### Reproduction Link
[demo](https://jsfiddle.net/y049dovv/)

### Steps to reproduce

1. 当前 ID 一列为固定列，假设点击第一行状态列的上架，在控制台中将打印两遍此行的状态值。

2. 去掉 ID 列的 html代码中的fixed，在点击上架，则在控制台中只打印一遍状态值。

### What is Expected?
无论是否有固定列，事件都应只执行一次

### What is actually happening?
有一列固定，则事件执行次数+1

**Comment by Leopoldthecoder** [comment]
Fixed in #2950
