### ISSUE TITLE
select组件的选中状态问题

### ISSUE THREAD

**Issue by sandysong** [ElemeFE/element#2847]
select开启了multiple、filterable、remote的情况下，option的选中状态有问题，然而官方文档上的例子中没有问题，猜测是将选中状态记录在了data属性中，而remote-method实际上每次都从后端获取数据更新option list

### ElementUI version
1.1.6

### OS/Browers version
chrome v56

### Vue version
2.1.10

### Reproduction Link
http://jsfiddle.net/tfykcfe8/

### Steps to reproduce
输入任何字符，选择一项，再输入任何字符，可以看到之前选择的选项并没有被选中，可以重复选择，与文档中的示例不符。

**Comment by Leopoldthecoder** [comment]
因为 `value` 绑定的是对象，每次赋值相当于指向了新的对象，所以会选不中。我看看要怎么处理。

目前暂时的办法有：
- `value` 绑定一个 primitive type 的值，比如 `:value="c.id"`，需要的时候通过 id 反查到具体的对象
- 数据量不大的话可以前端筛选

**Comment by Leopoldthecoder** [comment]
1.4.0 加入了 `value-key` 属性，可以解决这个问题：http://jsfiddle.net/tfykcfe8/3/
