### ISSUE TITLE
Does element-ui have a type declaration file（for typescript）?

### ISSUE THREAD

**Issue by toxichl** [ElemeFE/element#2849]
Does element-ui have a type declaration file（dts） for Typescript ? I recently developed a project based on typescript, but using the latest `npm install @ types / element-ui `, But the server returns 404 .

**Comment by jikkai** [comment]
According to this issue #2651, not yet. 😕

**Comment by toxichl** [comment]
I have solved this problem, and there is no use of type declaration file,  the configuration of the project template on the respository  [vue-typescript-template](https://github.com/toxichl/vue-typescript-template-ui)
