### ISSUE TITLE
Here has a bug when I used Promise in Loading component.

### ISSUE THREAD

**Issue by dupeiduo** [ElemeFE/element#2850]
.....
        console.log('1');
        this.loading = true
        Promise.resolve("2").then((n) => {
          this.loading = false
          console.log(n);
        })
.....

the loading would not hide as my respect. 
"webpack": "^1.13.2",
"vuex": "^2.1.1"
"element-ui": "^1.0.8",

**Comment by Leopoldthecoder** [comment]
`Promise.resolve("2")` 会立刻被 resolve，回调会在当前事件循环中调用，需要在回调中 nextTick 一下：
```javascript
Promise.resolve('2').then(n => {
  this.$nextTick(_ => {
    this.loading = false
    console.log(n);
  })
})
```
如果是一个真正异步操作的话就不需要 nextTick 了。

**Comment by furybean** [comment]
“回调会在当前事件循环中调用”，Promise 一定以异步的。

**Comment by Leopoldthecoder** [comment]
@furybean 查了一波查到了[这里](https://github.com/stevekane/promise-it-wont-hurt/pull/13)，所以可能阮老师的教程被误导了。
@dupeiduo 或者用服务的方式调用 Loading：http://jsfiddle.net/bhav0b33/

**Comment by dupeiduo** [comment]
@Leopoldthecoder thk
