### ISSUE TITLE
用 表单限制字符 视图未更新

### ISSUE THREAD

**Issue by Tadini** [ElemeFE/element#2853]
![image](https://cloud.githubusercontent.com/assets/13284174/23005702/8a52bbac-f438-11e6-9e74-6104af8d61bb.png)
```
<el-form-item label="描述" prop="desc">
    <el-input type="textarea" v-model="form.desc" auto-complete="off"></el-input>
</el-form-item>
```
![image](https://cloud.githubusercontent.com/assets/13284174/23005792/199c6326-f439-11e6-9a08-28a688a69306.png)

当文字超过600时， 我截取了描述的值只保留600个字，但视图未更新

**Comment by QingWei-Li** [comment]
Vue 用法问题请到相关社区咨询
