### ISSUE TITLE
dialog中包含form表单时，resetFields()并不能清空表单。

### ISSUE THREAD

**Issue by tingrun919** [ElemeFE/element#2854]
如题。
Demo：http://jsfiddle.net/mnoL1k5d/1/

**Comment by Leopoldthecoder** [comment]
`resetFields` 并不是清空表单，而是重置。和在不在 Dialog 里无关：http://jsfiddle.net/mnoL1k5d/2/

**Comment by z1769057083** [comment]
经本地测试，resetFields只有在添加表单验证时才起作用
