### ISSUE TITLE
upload组件 回调的file属性 不能自定义

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2855]
现在所有的file属性都是不能自定义的
比如我在:before-upload 的时候自定义了file.custome = 'custome';
在:on-success 或者其他的回调中拿不到自定义的属性

https://github.com/ElemeFE/element/blob/dev/packages/upload/src/index.vue#L107

**Comment by baiyaaaaa** [comment]
before-upload中的file是一个raw file 对象，on-success里面是upload自身维护的文件对象，你可以通过file.raw.custome拿到这个属性
