### ISSUE TITLE
编译自定义主题时发生错误

### ISSUE THREAD

**Issue by 644792799** [ElemeFE/element#2856]
**错误如下：**

> build element theme[13:55:23] BrowserslistError in plugin 'run-sequence(build)'
Message:
    Unknown browser query `basedir=`dirname "$0"``
Details:
    browserslist: true
Stack:
BrowserslistError: Unknown browser query `basedir=`dirname "$0"`

**Comment by QingWei-Li** [comment]
工具的问题请到 element-theme 下提问
