### ISSUE TITLE
[bug] el-dialog 嵌套使用时，遮罩层会浮在第一个dialog之上

### ISSUE THREAD

**Issue by ren8179** [ElemeFE/element#2859]
在第一个el-dialog中打开第二个el-dialog，并且都使用遮罩层，关闭第二个el-dialog之后，遮罩层会浮在第一个dialog之上

**Comment by vboyok** [comment]
发现了同样问题

**Comment by Leopoldthecoder** [comment]
为何要嵌套 Dialog？

**Comment by zcyzcy88** [comment]
**DO NOT**:
``` HTML
<el-dialog v-model="visible1" title="1">
    <el-dialog v-model="visible2" title="2"></el-dialog>
</el-dialog>
```

**DO**:
``` HTML
<el-dialog v-model="visible1" title="1"></el-dialog>
<el-dialog v-model="visible2" title="2"></el-dialog>
```

**Comment by vboyok** [comment]
企业管理类系统中很难避免 嵌套 Dialog，
在弹出的一个动态生成的表单编辑界面中动态生成并弹出另一个表单进行编辑，或者弹出另一个列表进行选择，都是很常见的需求

**Comment by Leopoldthecoder** [comment]
@vboyok 参考你楼上的回复。

**Comment by baijie** [comment]
@vboyok 请问你最后是怎么解决的？
怎么把dialog挂载到body上？
每个模块创建的时候 都往body上挂载一个 dialog吗？

**Comment by baijie** [comment]
@zcyzcy88 请问 怎么把Dialog丢到body底部呢；
还要保持通信；便于销毁等问题；

**Comment by zcyzcy88** [comment]
状态管理不是本库的职责

**Comment by baijie** [comment]
@zcyzcy88 我遇到的问题是 我需要嵌套 dialog；
因为我无法解决 才问你 怎么把dialog放到body底部的；

**Comment by trancelover** [comment]
dialog 隶属于单独的组件 而非body 这是很常见的应用场景。建议框架解决。
尤其是已经使用了dialog的项目，由于框架的升级导致不兼容，也很麻烦。

**Comment by vboyok** [comment]
@baijie  没有解决，暂时不用model层

我们的需求：
业务组件：订单列表组件OrderList，内嵌 订单详情组件 OrderDetails ,根据需要用 Dialog 显示，
结构示意为

<OrderList>
  <table></table>
  <el-dialog>
       <OrderDetails><OrderDetails>
  </el-dialog>
<OrderList>
而OrderList组件也可能是通过Dialog显示出来的，比如：

<body>
<InvoiceList>
  <el-dialog>
       <OrderList><OrderList>
  </el-dialog>
</invoiceList>
</body>
业务组件的层级是动态生成的，在不同的业务场景下嵌套关系也不一样，并不能简单的将Dialog打平到一层。
如果Dialog组件支持嵌套，业务组件的实现就很容易了。

**Comment by baijie** [comment]
@vboyok 我改用dialog+iframe来支持

**Comment by vboyok** [comment]
@baijie   iframe里再弹dialog会受限于iframe的边界
