### ISSUE TITLE
例子的JS写成普通的好不，像VUE那样

### ISSUE THREAD

**Issue by ApolloRoad** [ElemeFE/element#286]
` ##<////template>
  <el-radio class="radio" v-model="radio" label="1">备选项</el-radio>
  <el-radio class="radio" v-model="radio" label="2">备选项</el-radio>
<////template>

</////script>
  export default {
    data () {
      return {
        radio: ''
      };
    }
  }
<///script>
#`

例子的JS一定要这样写么，不想搞webpack那些，这样直接放进去就萌逼了好吗？

**Comment by QingWei-Li** [comment]
只是用了 ES6 的语法而已
