### ISSUE TITLE
tree组件 lazy属性的作用

### ISSUE THREAD

**Issue by Baozi2** [ElemeFE/element#2860]
1.1.6版本 -- Tree控件

lazy属性的作用是什么？
为什么设置了lazy之后，load属性对应的处理函数会默认执行一次

**Comment by furybean** [comment]
是在数据量比较大的情况下，不需要一次把所有层级一次加载回来。

**Comment by Baozi2** [comment]
so lazy要配合load一起使用啊  
使用load了不使用lazy没有下拉展开箭头了

**Comment by Baozi2** [comment]
tree控件使用的checkbox 有没有选中事件? 还是check-change就是选中事件？

为什么父节点选中、取消时，子节点的check-change也会触发？
