### ISSUE TITLE
[Bug Report] form.validate不会触发 trigger为: ['change','blur']的验证器

### ISSUE THREAD

**Issue by HyperSimon** [ElemeFE/element#2861]
http://jsfiddle.net/1cm8o39L/2/
如下图所示, 在活动名称项不满足条件的情况下提交，发现并没有触发起验证逻辑
活动名称的验证规则：
![2017-02-16 4 33 03](https://cloud.githubusercontent.com/assets/9377192/23013571/2b1da768-f466-11e6-9b79-d777c9bd57ad.png)

![2017-02-16 4 32 57](https://cloud.githubusercontent.com/assets/9377192/23013572/2b24950a-f466-11e6-9c71-3f5e8e117aa6.png)

**Comment by xjkms** [comment]
是的，我也发现这个问题了，trigger使用数组方式赋值，提交的时候不会验证

**Comment by HyperSimon** [comment]
有任何进展吗？

**Comment by macazy** [comment]
等一个进展

**Comment by Leopoldthecoder** [comment]
Fixed in #10178
