### ISSUE TITLE
想问下表格可有办法实现如图的形式，业务上是有这种需求

### ISSUE THREAD

**Issue by LWFeng** [ElemeFE/element#2862]
想问下表格可有办法实现如下图的形式，业务上是有这种需求
![qq 20170216165214](https://cloud.githubusercontent.com/assets/12045687/23014011/257d27d2-f468-11e6-8f61-6061025a6ad5.png)

**Comment by Leopoldthecoder** [comment]
目前不支持。

**Comment by yeomanyang** [comment]
这个需求感觉还是挺常见的，希望尽快支持哈～谢谢
