### ISSUE TITLE
NavMenu使用路由功能<router-view>内容显示错误

### ISSUE THREAD

**Issue by weitao901127** [ElemeFE/element#2863]
router-view显示的内容为当前组件内容+router-view内容

**Comment by frankleja** [comment]
hello @weitao901127 I want to ask you for help. I want to have different URLs for each menu-item.

I try to get the http://router.vuejs.org/ work together with el-menu but could not sort it out. The elem UI docu mention route attributes (on menu:router and menu-item:route), what my lead to the conclusion, that it is prepared for vue-router, but I did not get it all together in my App.vue file. 

Where to put the router instance?
Is a el-menu@select method needed somehow? 

Do you have an example App.vue from where I can grab it?

**Comment by baiyaaaaa** [comment]
请给出可复现问题的 demo
