### ISSUE TITLE
Esc key in $confirm dialog triggers confirm event

### ISSUE THREAD

**Issue by lcrespom** [ElemeFE/element#2865]
### ElementUI version
1.1.6

### OS/Browers version
Win7 / Chrome 56.0.2924.87

### Vue version
2.1.0

### Reproduction Link
http://jsfiddle.net/6x720ay1/2/

### Steps to reproduce
1. Open the console to see trace messages.
2. Click on delete button, then press the ESC key. Nothing is traced to the console.
3. Click again on delete, then click on "Cancel" button. Console traces "cancel 1".
4. Click again on delete, then press ESC. Console traces "cancel 2".
5. Click again on delete, then click the "Delete" button in the popup. Console traces "delete 3"
6. Now click again on delete, then press ESC. **Console traces "delete 4"**

### What is Expected?
The ESC key should **always** be equivalent to clicking the cancel button.

### What is actually happening?
Pressing the ESC key has different behavior depending on when it is pressed:
1. At first, no callback is issued to the promise: neither then nor catch.
2. After user clicks on some button of the popup, the ESC key will replicate the previous button. That is OK for the cancel button, but terribly wrong for the "Delete" button. A user that presses ESC on a popup definitely does not want to confirm deletion.

Yes of course the workaround is to disable the ESC key via `closeOnPressEscape`, but the correct behavior should be supported.

**Comment by lcrespom** [comment]
I cloned the repo and fixed the bug. Here is how to fix it: in file `packages/message-box/src/main.js`, line 78, after:

```javascript
const showNextMsg = () => {
  if (!instance) {
    initInstance();
  }
```

This line should be added:
```javascript
  instance.action = '';
```

After this change, the bug no longer reproduces.

I could make a PR but I think the fix is so simple it may not be worth. Please provide some feedback... this bug seems small but it could result in unwanted confirmations at runtime, e.g. "Destroy everything?" => user presses ESC but the "confirm" result is returned in the promise.

**Comment by Leopoldthecoder** [comment]
Thanks, you're right. This will be fixed in the next release.

**Comment by lcrespom** [comment]
Thank you. I should have clarified: the fix will result in the ESC key not generating any event at all. 

That is fine, but maybe the promise should fail when the end user closes the message box without confirming. That is the behaviour for the rest of cases: when pressing cancel or the "X" icon at the top right of the message box.

**Comment by Leopoldthecoder** [comment]
Yes, just like clicking the backdrop, pressing the ESC key won't generate any event. We'll reevaluate and see what can be done later.

**Comment by lcrespom** [comment]
Thank you again :-)
