### ISSUE TITLE
tree组件的数据源变化以后，应该保持当前tree的所有节点的状态

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#2866]
### Reproduction Link
http://jsfiddle.net/0trwergf/1/

### Steps to reproduce
1. 打开任意一个节点
2. 选中任意一个节点
3. 点击上方的 **add** 按钮
4. tree重新回到了初始状态，所有选中和打开的节点状态都消失了

### What is Expected?
在tree组件绑定的数据源变化后，还是能够保持节点之前的打开和选中状态 @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/0trwergf/2/

关于这个例子里的用法，可以参考 https://elementui.github.io/dev/dev/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong ，这是新加的文档例子，但还没有合到主分支。
