### ISSUE TITLE
Checkbox可以关闭显示lable而只显示checkbox本身吗？

### ISSUE THREAD

**Issue by cnweibo** [ElemeFE/element#2869]
你好，请问checkbox组件可以关闭显示lable吗？因为我有一个大的矩阵，希望通过这个checkbox组件来实现，其lable值并不重要，我希望只显示checkbox本身，其他功能不变，这个可以做到吗？

**Comment by baiyaaaaa** [comment]
这样只能用样式控制了

**Comment by cnweibo** [comment]
@baiyaaaaa , 那么支持传入特定的class name吗？现在是有一个el-checkbox__label 的css类，但是我还是希望用自己的类不去污染整体css，可以吗？

**Comment by Leopoldthecoder** [comment]
给需要自定义样式的 `<el-checkbox>` 标签加个类名就好。

**Comment by cnweibo** [comment]
我加了class="xx"但是在渲染出来的看不到这个类啊

**Comment by jikkai** [comment]
@cnweibo class 是被加载组件最外层 DOM 上的，不是在 checkbox input 上，请再仔细检查一下

**Comment by cnweibo** [comment]
@jikkai ,哦，知道了

**Comment by lerhxx** [comment]
<el-checkbox>{{undefined}}</el-checkbox>

**Comment by lerhxx** [comment]
&lt;el-checkbox&gt;{{undefined}}&lt;el-checkbox&gt;
