### ISSUE TITLE
table：希望能够支持表头自定义模板

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#287]
![_20161008165204](https://cloud.githubusercontent.com/assets/8213229/19211789/9660c6fa-8d77-11e6-9745-4f3cc8d3553d.png)
table-header不支持自定义模板，比如我想在table-header里添加一个checkbox，或者其它的一些内容，目前的label就不能满足了

**Comment by furybean** [comment]
这个功能可以加。不过你这个界面并不需要用 Table 这个组件，并不适合。

**Comment by jin5354** [comment]
附议一下该提议，现在的表头只能写文本，加一个iconfont都很难。
目前就遇到一个加表头后加iconfont的需求，即使是hack也很费劲的。使用css的::after伪元素挂上去，不能绑事件，很尴尬。

**Comment by furybean** [comment]
#838 已经提供 renderHeader 方法，请使用 1.0.0 版本。
