### ISSUE TITLE
文件上传成功后获得的file对象是个blob类型的文件

### ISSUE THREAD

**Issue by zzf88521** [ElemeFE/element#2876]
这个对象很头疼，怎么传给后台？
目前我只能得到url和大小，文件名等等
请问各位是怎么处理的？

还有一点，官网demo文件上传的地址是： http://jsonplaceholder.typicode.com/posts/
如果换成自己的接口，不知该如何接收并把该文件存入数据库？
API只有一句话，action	必选参数, 上传的地址	string - -

**Comment by zzf88521** [comment]
后台是用C#处理

**Comment by baiyaaaaa** [comment]
这种实践使用问题到 gitter 求助会更快能得到解决，issue 只负责反馈bug和设计问题
