### ISSUE TITLE
el-input组件在使用限定样式作用域（scoped）时，无法修改内部input的样式

### ISSUE THREAD

**Issue by lzl529** [ElemeFE/element#2878]
![image](https://cloud.githubusercontent.com/assets/16254369/23051636/82c7a12c-f505-11e6-8bbb-85503d489e5f.png)

生成后的样式由于后方带有[data-v-845875c4]无法与渲染生成的HTML匹配，导致样式无法生效。

**Comment by zzf88521** [comment]
样式选择器，不用写的那么复杂，你要真想修改样式，加个ID就是了。

**Comment by baiyaaaaa** [comment]
这不是element的问题，vue的设计就是这样

**Comment by lemontree2000** [comment]
@baiyaaaaa 那要怎么改变element 组件的样式？ 我遇到了类似的问题 。 我想改变本组件的样式但是不想改变其他组件

**Comment by Leopoldthecoder** [comment]
给 `el-input` 加个类。

**Comment by lemontree2000** [comment]
@Leopoldthecoder  DOM结构没有input 怎么办 ，列如 el-select 
![image](https://cloud.githubusercontent.com/assets/21957062/23607960/f875a2d0-02a1-11e7-920e-533c25ba12d5.png)

**Comment by Leopoldthecoder** [comment]
那就给 `el-select` 加类，比如 `<el-select class="my"></el-select>`，那么 CSS 里写
```CSS
.my input {
 ...
}
```

**Comment by lemontree2000** [comment]
@Leopoldthecoder 好的， 谢谢
