### ISSUE TITLE
el-dropdown-menu渲染后的定位问题

### ISSUE THREAD

**Issue by lfyfly** [ElemeFE/element#2879]
1. 为什么渲染后el-dropdown的el-dropdown-menu的元素都跑到body标签下了
   而不是在.el-dropdown的div下，
   这样的话一个el-dropdown看起来不是一个整体。

2. 然而下面的写法却令人感觉el-dropdown-menu 是包含在 el-dropdown中的

```
 el-dropdown
    span 标题
    el-dropdown-menu.status(slot="dropdown")
      el-dropdown-item 子标题1
      el-dropdown-item 子标题2
```

**Comment by baiyaaaaa** [comment]
一般下拉的组件放在body处理是比较好的。放在 `.el-dropdown` ，menu的最大自适应宽度是受限制的，还有考虑到一些层级的问题。

**Comment by juceyjing** [comment]
我也遇到了楼上的问题，menu有时不居中，el-dropdown 和el-dropdown -menu 不是父子嵌套的关系，这样要改变menu的定位让它始终居中，该怎样定位呢

**Comment by TencentIT** [comment]
同问

**Comment by chess654321** [comment]
.el-dropdown {
    padding-right: 120px;
}
