### ISSUE TITLE
table 组件 scoped slot 操作指定行数据，不能触发视图更新

### ISSUE THREAD

**Issue by syaka-yin** [ElemeFE/element#2880]
element 一直是我很喜欢的组件库，已经开发了两个公司后台项目了。
针对每一行数据，自定义内容之前用的是  inline-template ，但是现在改成 scoped slot 之后遇到了一些问题。

比如点击按钮，给指定行的数据加上状态，结果数据变化了，但是并没有触发视图更新。
[demo 链接](https://jsfiddle.net/syaka/qdhwnndx/)

点击按钮，给 scope.row 加上了 busy 属性，并赋值为 true，但是并没有将 el-button 更新为 loading 状态。

**Comment by Leopoldthecoder** [comment]
每一行数据中初始没有 `busy` 字段，造成 Vue 无法对其追踪。两个方案：
- 使用 `$set` 注册 `busy`：https://jsfiddle.net/qdhwnndx/1/
- 初始化时加上 `busy`：https://jsfiddle.net/qdhwnndx/2/
