### ISSUE TITLE
Dialog 对话框文字抖动

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#2883]
弹出框里如果有select组件的时候，点开下拉选项，dialog里的文字会抖动，如果有滚动条，抖动更明显

### ElementUI version
1.1.6 

### OS/Browers version
 macOS/Chrome 55

### Vue version
2.1

### Reproduction Link
http://jsfiddle.net/api/post/library/pure/

**Comment by Leopoldthecoder** [comment]
和 #2461 应该是一个问题，目前还没找到原因。请跟踪 #2461 ，如果有线索欢迎提供。
