### ISSUE TITLE
当Select通过:value绑定时，与表单validate验证无法通过

### ISSUE THREAD

**Issue by Chicago555** [ElemeFE/element#2885]
<template>
	<el-dialog 
		title="查看详情" 
		:close-on-click-modal="false"
		:close-on-press-escape="false"
    v-model="openInvoiceDialog" 
    class="detail-dialog invoice-dailog">
    <i class="el-icon-close"
    	@click.stop="closeInvoiceDialog"></i>
    <table >
	  	<tr>
				<td>申请编号</td>
				<td>{{ detailData.number }}</td>
			</tr>
			<tr>
				<td>申请时间</td>
				<td>{{ detailData.create_time | formatTime }}</td>
			</tr>
			<tr>
				<td>申请账户</td>
				<td>{{ detailData.nick_name }}</td>
			</tr>
			<tr>
				<td>发票抬头</td>
				<td>{{ detailData.header }}</td>
			</tr>
			<tr>
				<td>联系人</td>
				<td>{{ detailData.contacts }}</td>
			</tr>
			<tr>
				<td>地址</td>
				<td>{{ detailData.address }}</td>
			</tr>
			<tr>
				<td>手机号</td>
				<td>{{ detailData.mobile }}</td>
			</tr>
			<tr>
				<td>申请金额(元)</td>
				<td>{{ detailData.amount }}</td>
			</tr>
	  </table>

	  <el-form :model="dealForm" :rules="dealRules" ref="dealForm"
      label-position="left">
	  	<el-form-item label="处理结果：" label-width="90px">
	  		<el-select v-if="detailData.status == 'pending'"  placeholder="请选择"
	  		  v-model="dealForm.result">
	  			<el-option
	  			  v-for="item in dealList"
	  			  :label="item.name"
            :value="item.slug">
	  			</el-option>
	  		</el-select>
	  		<p v-else class="deal-result">
          <span v-if=" detailData.status == 'confirmed' ">已开票</span>
          <span v-else>已打回</span>
        </p>
	  	</el-form-item>

	  	<el-form-item  v-if="dealForm.result == 'refused' && detailData.status == 'pending' "
        label="不受理原因：" label-width="98px">
	  		<el-input v-model="dealForm.reason"></el-input> 
	  	</el-form-item>

      <el-form-item class="reasonDisplay"  v-if="detailData.status == 'refused' "
        label="不受理原因：" label-width="98px">
        <p class="deal-reason">{{ detailData.reason }}</p>
      </el-form-item>
	  </el-form>

	  <div slot="footer" class="dialog-footer">
	  	<el-button  v-if="detailData.status == 'pending'" 
        type="success" @click.native.stop="handleSubmit">确认
      </el-button>
      <el-button  v-else 
        type="success" @click.native.prevent="closeInvoiceDialog">确认
      </el-button>
    	<el-button  @click.native.prevent="closeInvoiceDialog">取消
      </el-button>
	  </div>
	</el-dialog>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import { Message } from 'element-ui';
import '../../style/detail-dialog.scss';

export default {
  data() {
    return {
      dealForm: {
        result: '',
        reason: ''
      },
      dealRules: {
        result: [
          { required: true, message: '请选择处理方式', trigger: 'blur' }
        ],
        reason: [
          { required: true, message: '请输入不受理原因', trigger: 'change' }
        ]
      },
    };
  },

  computed: mapGetters({
    'openInvoiceDialog': 'getOpenInvoiceDialog',
    'detailData': 'getDetailData',
    'dealList': 'getDealList'
  }),

  methods: {
    ...mapActions([
      'closeInvoiceDialog'
    ]),

    handleSubmit(ev) {
      // if (this.$data.dealForm.result !== '' || this.$data.dealForm.reason !== '') {
      //   const payload = {
      //     result: this.dealForm.result,
      //     reason: this.dealForm.reason
      //   };  

      //   this.$store.dispatch({
      //     type: 'saveInvoiceDialog',
      //     payload
      //   });
      // }

      this.$refs.dealForm.validate((valid) => {
        if (valid) {
          const payload = {
            result: this.dealForm.result,
            reason: this.dealForm.reason
          };  

          this.$store.dispatch({
            type: 'saveInvoiceDialog',
            payload
          });
        } else {
          this.$message.warning('请检查输入是否正确!');
          return false;
        }
        return false;
      });
    }
  }
};
</script>

**Comment by kopheece** [comment]
少了prop

**Comment by Leopoldthecoder** [comment]
请参考楼上的回复。另外，issue 里代码最好能格式化一下。

**Comment by feichangtutu** [comment]
`	rules:{
				search_val: [
					{ required: true, message: '请输入员工姓名', trigger: 'change' },
					{ max: 20, message: '姓名不能超过20个字符', trigger: 'blur' }
				],
				password: [
					{ required: true, message: '请输入密码', trigger: 'change'},
					{ min:6, max:16 ,message:'密码需为6~16位之间的数字或字母的组合', trigger:'change,blur',
						validator:(rule,value,callback)=>{
							let reg = /^[A-Za-z0-9]+$/
							if(!reg.test(value)){
								return callback(new Error(rule.message))
							}
							return callback()
						}
					}
				],`
当我给一个属性写多条规则时，规则无效，如上，search_val正常校验，password就不会走校验规则，请问是为什么？跟升级2.0有关系么
