### ISSUE TITLE
Dialog设置背景图片,出现时候会有闪烁

### ISSUE THREAD

**Issue by bianchengde** [ElemeFE/element#2889]
用Dialog的custom-class属性设置了样式并添加了背景图，但是当dialog出现的时候会有闪烁,将Dialog的
v-model改为v-show后,弹窗出现不会有闪烁，可是用v-show不知道怎么去关闭弹窗。

**Comment by Leopoldthecoder** [comment]
和 #2461 应该是一个问题，目前还没找到原因。请跟踪 #2461 ，如果有线索欢迎提供。
