### ISSUE TITLE
我只想这样，怎么搞出来，日期选择框

### ISSUE THREAD

**Issue by ApolloRoad** [ElemeFE/element#289]
![qq 20161009180432](https://cloud.githubusercontent.com/assets/5633780/19219643/3ead3ae0-8e4b-11e6-8c96-ab98f2eafe83.png)

**Comment by ApolloRoad** [comment]
js,怎么改

**Comment by ApolloRoad** [comment]
js怎么改，直接拿的官方例子

**Comment by DevilLeven** [comment]
var vm = new Vue({
    data: {
        pickerOptions0: {
            disabledDate(time) {
                return time < Date.now();
            }
        },
        pickerOptions1: {
            shortcuts: [{
                text: '今天',
                onClick(picker) {
                    picker.$emit('pick', new Date());
                }
            }, {
                text: '昨天',
                onClick(picker) {
                    const date = new Date();
                    date.setTime(date.getTime() - 3600 * 1000 * 24);
                    picker.$emit('pick', date);
                }
            }, {
                text: '一周前',
                onClick(picker) {
                    const date = new Date();
                    date.setTime(date.getTime() - 3600 * 1000 * 24 * 7);
                    picker.$emit('pick', date);
                }
            }]
        },
        value1: '',
        value2: '',
    }
})

试试这样吧

**Comment by DevilLeven** [comment]
也就是把官方data() 的返回值 作为你的Vue实例化中data参数

**Comment by ApolloRoad** [comment]
@DevilLeven 谢谢啊
