### ISSUE TITLE
slider组件嵌入到dropdown-menu里拖动异常

### ISSUE THREAD

**Issue by GloriaCHL** [ElemeFE/element#2891]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 55

### Vue version
2.1.10

### What is actually happening?
在el-dropdown-menu中嵌套el-slider，没加show-input参数的时候会出现拖拽不准确的现象，添加了show-input后就拖不动了。

**Comment by Leopoldthecoder** [comment]
先问一下场景是什么？为什么需要在 Dropdown 里放 Slider？

**Comment by GloriaCHL** [comment]
网页场景形形式式各种各样什么样的场景都有可能，我只是刚巧碰上需要这样调用的场景而已。
场景是我在dropdown里放了组表单元素，想用slider来做其中一个元素的调控操作控制其数值大小，然后就发现这个问题。后来把表单删掉排除掉它的影响可能性，只在dropdown里放了个slider测试下问题还是存在。就来这里提下了。

**Comment by Leopoldthecoder** [comment]
没重现出来，请提供 demo：http://jsfiddle.net/bpotgrsp/

**Comment by GloriaCHL** [comment]
看了你的demo没问题后我重新测了下之前的代码发现也没问题了...但明明上周测了几次都拖不动的= =。可能是我项目里别的地方影响到了什么的，现在使用正常了。
真不好意思浪费了你些时间。
