### ISSUE TITLE
[Autocomplete] Hope provide an attribute to disable remote loading placeholder

### ISSUE THREAD

**Issue by zcyzcy88** [ElemeFE/element#2892]
### ElementUI version
1.1.6

### Reproduction Link
http://codepen.io/zcyzcy88/pen/jyRvLP?editors=1010

### Steps to reproduce
If server responses so fast, the loading placeholder flashed.

So I need an attribute to disable remote loading placeholder:
When user type in <input>, just call `fetch-suggestions`, don't update UI with loading placeholder(keep last fetched suggestions).

### What is Expected?
Example from Google Search:
![demo_google](https://cloud.githubusercontent.com/assets/15178410/23067190/1d58ecac-f559-11e6-942c-b89455fcaeb0.gif)

### What is actually happening?
![demo](https://cloud.githubusercontent.com/assets/15178410/23067198/246bc42e-f559-11e6-8795-2a2700e77758.gif)

**Comment by Tronsfey** [comment]
Any progress ?

**Comment by syn-zeta** [comment]
Slightly modifying [the example from the docs](http://element.eleme.io/#/en-US/component/select#remote-search) to remove the loading attribute: https://jsfiddle.net/gdegdm0u/

![input](https://user-images.githubusercontent.com/26761352/27519969-5930b5c4-59b4-11e7-9270-995b161fea50.gif)

@Leopoldthecoder Recommend closing as I think the autocomplete component was replaced by remote select component that does allow control over the loading animation.
