### ISSUE TITLE
在 el-input 里使用中文输入法输入时对 model 对更改问题

### ISSUE THREAD

**Issue by walnutzhang** [ElemeFE/element#2894]
hi,  最近在使用 el-input 时发现一个问题。如果 el-input 使用v-model绑定了某个data值，然后使用中文输入法进行输入，则在选词进入输入框之前就已经触发了对 model 的修改，这个默认行为应该是不太对的。Vue 本身对 input 输入法的处理就是选词输入之后才触发修改。 element 这个是 feature 还是 bug?

**Comment by jikkai** [comment]
当前版本应该已无此问题，如能复现欢迎随时打开 😄
