### ISSUE TITLE
Upload可以携带其他的post参数吗?

### ISSUE THREAD

**Issue by rainwsy** [ElemeFE/element#2895]
比如我要上传到七牛除了提供上传地址，还需要携带像key这样的参数。

**Comment by rainwsy** [comment]
http://element.eleme.io/#/zh-CN/component/upload#attribute

data

已找到

**Comment by transtone** [comment]
楼主可以帮忙给个示例吗，我这里用data不起作用。

**Comment by rainwsy** [comment]
@transtone 
```
            <el-upload
                    action="http://up.qiniu.com/"
                    type="drag"
                    :multiple="true"
                    :on-preview="handlePreview"
                    :on-remove="handleRemove"
                    :on-success="handleSuccess"
                    :on-error="handleError"
                    :default-file-list="fileList"
                    :data="upload_data"
                    accept="audio/*,video/*,image/*"
            >
                <i class="el-icon-upload"></i>
                <div class="el-dragger__text">将文件拖到此处，或<em>点击上传</em></div>
                <div class="el-upload__tip" slot="tip">只能上传jpg/png文件，且不超过5Mb</div>
            </el-upload>
```

**Comment by YYM08103667** [comment]
我也是用了这个组件，是这么写的，但是每次上传都要点击两次才能上传成功，想问下，各位是否遇到过这个情况，是否有个bug呢还是我写的有问题？
<el-upload action="/backend/user/profiles/bankCardPicture"  name="bankCardPicture" :data="userId"
                :before-upload="beforeBankCardPictureUpload" class="upload-demo" :on-error="handleUploadError"
                :with-credentials="true"
                :show-file-list="pictures.bankCardPicture[0].show_file_list"  :on-remove="handleBankCardPictureRemove"
                :on-success="handleBankCardPictureSuccess" :file-list="pictures.bankCardPicture">
            </el-upload>



yym08103667@gmail.com
 
发件人： rainwsy
发送时间： 2017-02-28 01:14
收件人： ElemeFE/element
抄送： Subscribed
主题： Re: [ElemeFE/element] Upload可以携带其他的post参数吗? (#2895)
@transtone
            <el-upload
                    action="http://up.qiniu.com/"
                    type="drag"
                    :multiple="true"
                    :on-preview="handlePreview"
                    :on-remove="handleRemove"
                    :on-success="handleSuccess"
                    :on-error="handleError"
                    :default-file-list="fileList"
                    :data="upload_data"
                    accept="audio/*,video/*,image/*"
            >
                <i class="el-icon-upload"></i>
                <div class="el-dragger__text">将文件拖到此处，或<em>点击上传</em></div>
                <div class="el-upload__tip" slot="tip">只能上传jpg/png文件，且不超过5Mb</div>
            </el-upload>

**Comment by hasbug** [comment]
@transtone 场景和我类似，我是阿里云OSS，这时候需要在上传前先拿到签名串设置进去再传图片，但是呢，因为都是异步，图片就可能在还没设置的时候就上传了。我尝试过不使用自动上传，再通过submit进行上传，可惜，这个上传组件，在before-upload这一步的时候，已经对本次的图片进行配置了参数，我们的参数只有在下一次有效。就坑在这里了

**Comment by rainwsy** [comment]
@hasbug 可以再上传前把参数写在data里

**Comment by hasbug** [comment]
@rainwsy 也是个办法，但我的项目还有个坑，每次上传的图片都需要向后端请求个文件名进行配置（传到阿里云OSS，避免重名覆盖），这个就不知道放哪里处理了。

**Comment by rgbangbang** [comment]
@hasbug 可以在on-change事件里面修改data属性。
<el-upload
           ref="upload"
           class="avatar-uploader"
           action="http://xxxxxx"
           :data="formData"
           :multiple="false"
           :auto-upload="false"
           :name="upload"
           :on-success="handleAvatarSuccess"
           :on-change="handleChange"
           :before-upload="beforeAvatarUpload">
           <el-button slot="trigger" size="small" type="primary">选取文件</el-button>
           <el-button style="margin-left: 10px;" size="small" type="success" @click="submitUpload">上传到服务器</el-button>
         </el-upload>



 handleChange(file, fileList) {
       //选择完文件后的状态
       if (file.status == 'ready') {
          this.formData = {
             path: this.path,
            name: file.name
          }
       }
submitUpload() {
        this.$refs.upload.submit();
      }

    },

**Comment by lkdghzh** [comment]
//防止第一次请求带不上表单其他参数。根据我的经验,QQ群471838073。
```
 this.uploadData = {       
        params
 };
//防止第一次请求带不上表单其他参数
this.$nextTick(() => {
       this.$refs.upload.submit();
});
```

**Comment by pro-xiaoy** [comment]
哪位大佬告诉我，为什么我的el-upload里面的action填写完后台地址，默认发送的请求是get

**Comment by cntaoyu** [comment]
@pro-xiaoy 有demo吗

**Comment by pro-xiaoy** [comment]
@cntaoyu 
我想最恶心的事情就是他莫名其妙的就好了

**Comment by pro-xiaoy** [comment]
@cntaoyu 
![image](https://user-images.githubusercontent.com/24773812/33107968-a29a90b4-cf74-11e7-8486-4964be8b0370.png)
![image](https://user-images.githubusercontent.com/24773812/33107980-ae96f9b6-cf74-11e7-9416-6157be2b687a.png)

**Comment by cntaoyu** [comment]
@pro-xiaoy 不完整看不出来啥问题，你可以看下我的demo :https://zy62.com/upload/

**Comment by pro-xiaoy** [comment]
@cntaoyu thanks you 我好好研究下

**Comment by ployer900** [comment]
在before-upload钩子中请求uploadToken，只需要返回promise就行了。
      
const before = this.beforeUpload(rawFile);
     // 返回promise
      if (before && before.then) {
        before.then(processedFile => {
          const fileType = Object.prototype.toString.call(processedFile);

          if (fileType === '[object File]' || fileType === '[object Blob]') {
            if (fileType === '[object Blob]') {
              processedFile = new File([processedFile], rawFile.name, {
                type: rawFile.type
              });
            }
            for (const p in rawFile) {
              if (rawFile.hasOwnProperty(p)) {
                processedFile[p] = rawFile[p];
              }
            }
            this.post(processedFile);
          } else {
            this.post(rawFile);
          }
        }, () => {
          this.onRemove(null, rawFile);
        });

**Comment by 404cat** [comment]
> @transtone 场景和我类似，我是阿里云OSS，这时候需要在上传前先拿到签名串设置进去再传图片，但是呢，因为都是异步，图片就可能在还没设置的时候就上传了。我尝试过不使用自动上传，再通过submit进行上传，可惜，这个上传组件，在before-upload这一步的时候，这个组件已经对本次的图片进行配置了参数，我们在获取回来设置参数只有在下一次才有效。就坑在这里了

大佬，你这个问题后面怎么解决的呢？我也遇上了相同的问题
