### ISSUE TITLE
Element官方文档 - table组件演示有点问题

### ISSUE THREAD

**Issue by saint3347** [ElemeFE/element#290]
![image](https://cloud.githubusercontent.com/assets/7347133/19221487/07ea5e76-8e77-11e6-8423-28ccb8e079df.png)
点到table组件就有js报错，导致table组件的示例代码无法展开，不能复制。。

另外，vue2.0正式发布了，有一个新项目正准备启动，想用Element来做 ,不知道可不可以呢？

**Comment by saint3347** [comment]
这样提issues会不会被直接关闭掉哦，除了这里还能有什么方式能联系到贵团队哦？thks~~

**Comment by furybean** [comment]
@saint3347 使用的这个 URL 么：http://element.eleme.io/#/component/table，并没有发现有报错。

**Comment by saint3347** [comment]
http://element.eleme.io/#/component/table 直接打开这个链接可以展开演示代码；
![image](https://cloud.githubusercontent.com/assets/7347133/19229356/7ae05402-8eff-11e6-8d02-4ae1b79db036.png)

但是你点一个其他的组件，比如点一下tag组件，再点table组件，table的演示代码就打不开了。。我是这样发现的这个问题。。呵呵

**Comment by csvwolf** [comment]
@saint3347 我尝试了一下你说的「点一下 Tag 后点 Table」，但是无法复现你说的问题

**Comment by saint3347** [comment]
![tablebug](https://cloud.githubusercontent.com/assets/7347133/19232151/cef84fac-8f10-11e6-8a22-0af4e8b171ac.gif)
好像是360极速浏览器的问题，呵呵

**Comment by l1shen** [comment]
同样在360极速浏览器下出现此问题

**Comment by furybean** [comment]
@l1shen Table 正在重构，这个问题已经修复。

**Comment by saint3347** [comment]
O(∩_∩)O~辛苦
