### ISSUE TITLE
table 控件 fixed的样式问题

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#2900]
在table中使用fixed属性，在没有横向的滚动条的时候，固定列出现样式不正常。不同分别率先产生的该问题
![image](https://cloud.githubusercontent.com/assets/16740731/23093935/756449b0-f62a-11e6-9aa0-b03a883f463d.png)

**Comment by furybean** [comment]
2.1.0 中已经无法重现。
先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。
