### ISSUE TITLE
同时执行多个Notification会叠加在一起，没有间隔

### ISSUE THREAD

**Issue by iftrueme** [ElemeFE/element#2901]
同时执行多个Notification会叠加在一起，没有间隔

### ElementUI version
1.1.6

### OS/Browers version
Windows10/Chrome 56

### Vue version
2.1.0

![qq 20170219115711](https://cloud.githubusercontent.com/assets/10379200/23099149/385e5b98-f69b-11e6-8cdc-95631c1f638c.png)

**Comment by languanghao** [comment]
感觉没问题啊，如果要间隔出现就自己弹出的时候控制一下

**Comment by Leopoldthecoder** [comment]
同时执行多个的话，没有时间计算前一个 Notification 的高度，所以会这样。

**Comment by jiaozhouzhou** [comment]
有没有解决的办法
