### ISSUE TITLE
table组件 固定属性fixed和最小高度

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#2903]
table组件使用了fixed属性，同时使用了最小高度来控制table的时候样式混乱
![image](https://cloud.githubusercontent.com/assets/16740731/23101387/63e0517c-f6cd-11e6-940f-d1d7ca9ed9cc.png)
![image](https://cloud.githubusercontent.com/assets/16740731/23101390/7191d3fe-f6cd-11e6-8fb6-46d9a1c9a2bf.png)

**Comment by liril-net** [comment]
能给个 demo 吗？
