### ISSUE TITLE
导航菜单<el-menu>的一个样式问题

### ISSUE THREAD

**Issue by wisewrong** [ElemeFE/element#2911]
导航菜单触发 hover 事件的时候，会出现一条下划线
当鼠标移开，或者菜单被点击后，下划线会消失

但是如果菜单是多级菜单，当点击了子菜单之后，下划线还会继续存在
![default](https://cloud.githubusercontent.com/assets/23471962/23114571/b8bfe2f4-f77a-11e6-8e38-f74225f3b831.png)

**Comment by baiyaaaaa** [comment]
这是设计中的，不是样式问题
