### ISSUE TITLE
[dialog]change事件触发机制有问题

### ISSUE THREAD

**Issue by Tang-RoseChild** [ElemeFE/element#2912]
### Vue version
2.3.1

### Reproduction Link
http://jsfiddle.net/0euej7fL/1/

### Steps to reproduce
点两下<修改表单数据>按钮，会触发表单dialog中Input的change事件

### What is Expected?
表单打开后，修改input里面的值，这个时候才触发。
而不是dialog关闭时也会触发

**Comment by Leopoldthecoder** [comment]
这个是正常的，在 `change` 事件的回调里判断一下当前 Dialog 是否打开就可以。
