### ISSUE TITLE
el-select 多选时取值赋值问题

### ISSUE THREAD

**Issue by MrQiaoXin** [ElemeFE/element#2915]
### ElementUI version

1.1.6
### OS/Browers version

Chrome 

### Vue version

2.1.6

##设计建议
关于select 多选，设默认值数组为选项的label，但是获取value的时候获取到的还是label。
设默认值为value的时候，显示的不是label。
同时，选项中没有选中默认选项。
所以select多选能不能完善一下，或者opine能设置默认选项。

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/vcgftLvn/28/
是这个意思么？

**Comment by MrQiaoXin** [comment]
是啊，原来是我数据类型不一致导致的问题。
我改一下接口返回就可以了。。
非常感谢！

**Comment by chendeting** [comment]
我遇到的问题是表单验证中，如果el-select为多选，即加上multiple属性之后，表单验证会自动触发，我设置是trigger：‘change’,没有做任何操作，跳转路由到表单验证页面，然后就被自动触发了，这个问题有解决的吗

**Comment by JUSTZWH** [comment]
用的是字符串数组，，，
