### ISSUE TITLE
关于任意时间范围的bug

### ISSUE THREAD

**Issue by yangyichen** [ElemeFE/element#2916]
![2017-02-20_20-35-34_](https://cloud.githubusercontent.com/assets/8776272/23125361/495096b6-f7ac-11e6-8b11-d326f194d5d6.gif)
请看上面的gif，不知道是我一个人的问题还是算一个bug？
描述一下：通过不停的点击时间会发现，只有偶数次的才会被选择到，奇数次的不会。时分秒都有这个情况出现。
用的是chrome56

**Comment by yangyichen** [comment]
忘了说了，这是官网上的例子。
http://element.eleme.io/#/zh-CN/component/time-picker
os：win7

**Comment by Leopoldthecoder** [comment]
Fixed in #2884
