### ISSUE TITLE
error to run / start 

### ISSUE THREAD

**Issue by juppdes** [ElemeFE/element#292]
### What is actually happening?

I just clone the package, install and try to run.

I already try do npm cache clean, but error persist.
Please, show me how fix this.

npm-debug:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle element-ui@1.0.0-rc.5~prebootstrap: element-ui@1.0.0-rc.5
6 silly lifecycle element-ui@1.0.0-rc.5~prebootstrap: no script for prebootstrap, continuing
7 info lifecycle element-ui@1.0.0-rc.5~bootstrap: element-ui@1.0.0-rc.5
8 verbose lifecycle element-ui@1.0.0-rc.5~bootstrap: unsafe-perm in lifecycle true
9 verbose lifecycle element-ui@1.0.0-rc.5~bootstrap: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\sistemasweb\element-master\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Users\JuppLu\AppData\Roaming\npm
10 verbose lifecycle element-ui@1.0.0-rc.5~bootstrap: CWD: C:\sistemasweb\element-master
11 silly lifecycle element-ui@1.0.0-rc.5~bootstrap: Args: [ '/d /s /c', 'npm i && lerna bootstrap' ]
12 silly lifecycle element-ui@1.0.0-rc.5~bootstrap: Returned: code: 1  signal: null
13 info lifecycle element-ui@1.0.0-rc.5~bootstrap: Failed to exec bootstrap script
14 verbose stack Error: element-ui@1.0.0-rc.5 bootstrap: `npm i && lerna bootstrap`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid element-ui@1.0.0-rc.5
16 verbose cwd C:\sistemasweb\element-master
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error element-ui@1.0.0-rc.5 bootstrap: `npm i && lerna bootstrap`
22 error Exit status 1
23 error Failed at the element-ui@1.0.0-rc.5 bootstrap script 'npm i && lerna bootstrap'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the element-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm i && lerna bootstrap
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs element-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls element-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by spademan** [comment]
#67

**Comment by QingWei-Li** [comment]
show me terminal info, pls

**Comment by juppdes** [comment]
![terminal](https://cloud.githubusercontent.com/assets/22179665/19236032/8a74edbc-8ecb-11e6-8913-8b78d18ffdb5.jpg)

**Comment by QingWei-Li** [comment]
Do not require the source code.

**Comment by juppdes** [comment]
Thank you friend, was really just that.
