### ISSUE TITLE
el-carousel咨询

### ISSUE THREAD

**Issue by hhkgithub** [ElemeFE/element#2925]
<el-carousel :interval="4000" type="card" height="160px" trigger="click" arrow="always">
            <el-carousel-item v-for="item in products" v-if="item.ProdType == 1">
              <el-card :body-style="{ padding: '0px' }">
                <div class="prodtitle"  @click="goto('1')">
                  <span>{{item.ProdTitle }}</span>
                </div>
                <img :src="item.ProdLocalUrl " width="100px" height="90px">
              </el-card>
            </el-carousel-item>
          </el-carousel>
这样不显示出来啊？products是有对象(vuex里state.products)。去掉el-carousel-item是可以显示的。

**Comment by Leopoldthecoder** [comment]
`products` 是异步获取的吗？

**Comment by JanlyH** [comment]
@Leopoldthecoder 我遇到同样问题，是后台获取了数据后，渲染到页面，全部都不显示
