### ISSUE TITLE
Carousel item not showing(not respond to data source's changing )

### ISSUE THREAD

**Issue by qky1412** [ElemeFE/element#2928]
`<el-carousel type="card" height="360px" >
          <el-carousel-item v-for="banner in banners">
              <h3>{{banner}}</h3>
          </el-carousel-item>
</el-carousel>`
After I fetch the banners from server, the carousel items are not showing, it seems to be that the carousel item number is still 0 which is the default empty array's length. So I try to set the default banner array to, like ["1", "2", "3"], then I fetch 3 banners from server, it rendered as I expected.

**Comment by Leopoldthecoder** [comment]
Already fixed in #2775. Will be released in 1.2.0
