### ISSUE TITLE
根据数组渲染的 tabs 标签页，关闭后没有修改原数组

### ISSUE THREAD

**Issue by wisewrong** [ElemeFE/element#2930]
我的 tabs 标签页是由一个数组 `tabMenu` 渲染的，element 自带的关闭功能，只是关闭了选项卡，而对于 `tabMenu` 这个数组并没有作任何修改。
于是我在 `tab-remove` 事件中，添加 `this.tabMenu.splice(tab.index, 1)` 删除了数组元素。
但是在实际效果中，数组被正确的修改了，但tabs 标签却一下关闭了两个。
![qq 20170221150840](https://cloud.githubusercontent.com/assets/23471962/23154329/3c87d466-f848-11e6-8dc0-4de2b0d9493b.png)

**Comment by baiyaaaaa** [comment]
1.2 会修复这个问题，会更新为不再主动销毁tab实例，由调用者通过数据来控制。近期会发布
