### ISSUE TITLE
对vuex支持不友好

### ISSUE THREAD

**Issue by ayizhi** [ElemeFE/element#2931]
最近公司迁移vue，用到element

发现对vuex并不友好
input组件还好

select组件，不用v－model就无法触发change事件，因为点击选项根本没反应，无法触发change事件，只能有get()/set()来解决

时间选择组件，如果不用v－model，无法获取点击到的日期值，还得用get()/set()

get()/set()这种来出发commit／dispatch来改变vuex中的state虽然可行，但需要大量重复写 变量名对应的get/set方法

**Comment by Leopoldthecoder** [comment]
参考一下 https://github.com/ElemeFE/element/issues/1632#issuecomment-265739660

**Comment by ayizhi** [comment]
谢谢回答，还有就是，对于表单验证，原来的逻辑是点击提交之后，后台返回对应错误的domID，以及错误信息，然后通过jq找到对应id的dom，将报错信息插入进去

想问element有没有对应方法的验证？

换句话说，感觉element的验证是有个管理验证的子组件，每个子组件都有对应的rules字段，然后有专门的validator方法去触发，那么有什么办法在外部（可能是ajax返回或者其他）去触发对应rules字段的报错

**Comment by Leopoldthecoder** [comment]
使用 `error` 属性：http://element.eleme.io/#/zh-CN/component/form#form-item-attributes
参考 http://jsfiddle.net/ttwva9s2/

**Comment by ayizhi** [comment]
好好，还有一个，针对上传文件剪裁如何实现？这个版本没有的话有什么推荐方法

**Comment by IEfucker** [comment]
我也遇到校验的问题，之前有vuex把表单数据map到组件的computed里，比如名为x，为了校验功能在data里加了form.x同名字段，然后x和form.x还要做同步处理，针对一个字段就要写很多代码。
有没有简单点的方法
