### ISSUE TITLE
[tree]请问 render-content 生成的节点 如何绑定方法

### ISSUE THREAD

**Issue by BillionChen** [ElemeFE/element#2933]
![f71f8e24-e46c-4358-946b-d1c562ba08d4](https://cloud.githubusercontent.com/assets/20330619/23157460/5102780c-f856-11e6-921d-34f705aa8b11.png)
![dfe0ef1d-0f5d-4cce-8a49-9c01649867b3](https://cloud.githubusercontent.com/assets/20330619/23157484/69bc36c6-f856-11e6-8623-b12161895bb4.png)

**Comment by BillionChen** [comment]
直接@click="openDialog" 编译不通过
v-on:click 也编译不通过

**Comment by BillionChen** [comment]
![f47b40aa-2c1d-445f-b802-504a6ecb37ac](https://cloud.githubusercontent.com/assets/20330619/23158562/a2a022dc-f85a-11e6-9f5b-d2e299eea374.png)
这样写可以绑定方法,但是渲染dom时,会立即调用一次,
一加载就调用几十次我也是醉了

**Comment by BillionChen** [comment]
![293f5096-485f-484a-ba77-e9f787049b77](https://cloud.githubusercontent.com/assets/20330619/23163157/478ddeea-f86c-11e6-9f3a-4c570b7ac592.png)
恩,再包一层就好了,我自己解决了..

**Comment by Leopoldthecoder** [comment]
在你倒数第二个回复里，`this.openDialog` 后面的括号去掉试试。

**Comment by BillionChen** [comment]
你是对的,但是我要传参还是要按第三个来写.. @Leopoldthecoder
