### ISSUE TITLE
Tabs的label slot不能及时动态更新

### ISSUE THREAD

**Issue by qihuo** [ElemeFE/element#2934]
Tabs里面动态修改tab的label之后，tab标签不能及时更新, 总是跟实际数据晚了一步
https://jsfiddle.net/liangshuai/ee01h7bq/2/

```js
var Main = {
  template: `
<el-tabs type="border-card">
 <el-tab-pane :name="index" v-for="(item, index) in tabs">
     <span slot="label">{{ item.name }}</span>
     <div>
     	{{ item.name }}
      <input type="text" v-model="item.name" name="name"/>
     </div>
  </el-tab-pane>
</el-tabs>
  `,
  data() {
    return {
    	tabs: [
      	{
        	name: 'tab1',
          content: 'Content Tab1'
        },
        {
        	name: 'tab2',
          content: 'Content Tab2'
        },
        {
        	name: 'tab3',
          content: 'Content Tab3'
        }
      ]
    }
  },
}

new Vue({
  el: '#app',
  render: h => h(Main)
})

```

**Comment by baiyaaaaa** [comment]
最新版已修复这个问题

**Comment by liuyingqq123** [comment]
cdn加载的话, 依然存在此问题, slot="label"内的数据, 并不能实时刷新

**Comment by gwh-cpnet** [comment]
问题依然存在，element-ui 2.5.4, vue 2.6.4.

**Comment by gwh-cpnet** [comment]
a work around. add a ref attribute to <el-tabs>, like <el-tabs ref="tabs">

after data updated, run 
```
this.$refs.tabs.$refs.nav.$forceUpdate();
```

**Comment by edum18** [comment]
Problem still remains on the latest version 2.5.4

**Comment by luichooy** [comment]
问题依旧存在
element: 2.6.1
vue: 2.5.2

**Comment by leehavin** [comment]
问题依旧存在
element: 2.6.1
vue: 2.5.22

**Comment by sonofmagic** [comment]
问题依旧存在
element: 2.6.1
Vue.js v2.6.8

**Comment by Yinevg** [comment]
问题依旧存在
element: 2.6.1
Vue.js 2.9.6

**Comment by LittleHChen** [comment]
问题依旧存在
element: 2.6.1
Vue.js 2.9.6

**Comment by LittleHChen** [comment]
i found a simple solution, use "v-if" to update element
like this:
`<el-tab-pane
     v-if="state.update"
>
     <span slot="label">
           <el-checkbox/>{{item.Name}}
     </span>`

`forceRefresh() {
            this.state.update = false;
            this.$nextTick(() => {
                this.state.update = true;
            });
        }`

**Comment by itart-top** [comment]
用错标签了吧？ 原生的input不是响应式的，
把：
 <input type="text" v-model="item.name" name="name"/>
改为：
 <el-input v-model="item.name"></el-input>
就可以了

**Comment by springwang** [comment]
> a work around. add a ref attribute to <el-tabs>, like <el-tabs ref="tabs">
> 
> after data updated, run
> 
> ```
> this.$refs.tabs.$refs.nav.$forceUpdate();
> ```
2.12.0 也没解决，然后用这个forceUpdate也不生效

**Comment by linxingli** [comment]
> 

Thanks, problem solved！
