### ISSUE TITLE
[Docs]打开的新链接都显示404错误

### ISSUE THREAD

**Issue by licdream** [ElemeFE/element#2935]
文档首页，使用鼠标中键或者拖拽链接的方式打开的新链接，都显示github的404页面。

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/issues/2116

**Comment by licdream** [comment]
这样的话，想同时阅读多个部分，还得手动新建窗口输入网址。使用感觉不好，其他开源项目的API文档都没遇到有这样的问题。希望以后能改善一下。

**Comment by QingWei-Li** [comment]
已经更新了，清下浏览器缓存就好了
