### ISSUE TITLE
date-picker日期在可输入时，日期框中有不合法字符

### ISSUE THREAD

**Issue by wgq837051** [ElemeFE/element#2936]
官网上日期实例：
![1](https://cloud.githubusercontent.com/assets/6071212/23158775/5427e72e-f85b-11e6-93fe-390dc6cab8aa.png)
![2](https://cloud.githubusercontent.com/assets/6071212/23158780/5801eef8-f85b-11e6-8987-777f56ba876f.png)
![3](https://cloud.githubusercontent.com/assets/6071212/23158785/5aaf8c82-f85b-11e6-8c05-1795e3f631b7.png)
当日期选择器消失时，日期编辑框中还是有不合法的字符。

**Comment by zWingz** [comment]
我都是设为 editable=false..

**Comment by herrdu** [comment]
<el-date-picker type="date" v-model="formData.cameraTime" format="yyyy-MM-dd" @change="cameraTimeChange" @blur="cameraTimeBlur" placeholder="选择日期" editable=false>

报错
Invalid prop: type check failed for prop "editable". Expected Boolean, got String.

**Comment by herrdu** [comment]
好吧：设置错了...   例子 ： http://jsfiddle.net/n0L6yvrn/
