### ISSUE TITLE
使用ElementUI，如何在table外部获取table选中的行的index？

### ISSUE THREAD

**Issue by 3ccc** [ElemeFE/element#2938]
比如current-change返回的只有currentRow, oldCurrentRow，能否添加currentIndex，oldCurrentIndex

**Comment by liril-net** [comment]
使用 `indexOf` 可以获得对应的 `index` 的。

**Comment by dheart-joe** [comment]
这个回应真心不负责。。。

**Comment by liril-net** [comment]
@dheart-joe 请给一个负责的回应😄
