### ISSUE TITLE
switch 無法正常運作 ( on-text  off-text)

### ISSUE THREAD

**Issue by Bear1110** [ElemeFE/element#2942]
您好 我今天在測試 

```
<el-switch
  v-model="value1"
  on-text=""
  off-text="">
</el-switch>
```

此範例時 這樣可正常執行

可是當我嘗試

```
<el-switch
  v-model="value1"
  on-text="onn"
  off-text="offf">
</el-switch>
```

會出現以下錯誤

![image](https://cloud.githubusercontent.com/assets/14165451/23169386/8ceb14c0-f886-11e6-9ad1-cd093da31585.png)

請無視我劃掉的那一條

請問是為何呢??

謝謝!

**Comment by PanJiaChen** [comment]
你这个是vue版本问题吧。。。element1.10之后vue的最低版本是2.1.6
升级一下vue应该就好了

**Comment by Bear1110** [comment]
喔喔  感謝 我試試看

**Comment by Bear1110** [comment]
我試過裝最新版本的無法!? 2.1.10 (我看檔案編輯日期是 2017/1/18

**Comment by PanJiaChen** [comment]
vue-loader
vue-template-compiler这两个版本对么

**Comment by Bear1110** [comment]
我是直接專案 ( Laravel) 用  CDN 引入的

```
<!-- 引入样式 -->
<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css">
<!-- 引入组件库 -->
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
```

不知道甚麼 vue-loader 跟 vue-template-compiler說...

麻煩妳回答了 謝謝!

**Comment by PanJiaChen** [comment]
http://codepen.io/anon/pen/ygmjmy
我不太能重现你的问题，能贴一个线上代码没。。。

**Comment by Bear1110** [comment]
我再試試看好了 看有沒有辦法找出問題點在哪...謝謝你^^
