### ISSUE TITLE
el-table横向滚动条

### ISSUE THREAD

**Issue by hellinnocence** [ElemeFE/element#2945]
### ElementUI version
1.1.6

### OS/Browers version
IE11 Edge

### Vue version
2.1.8

### Reproduction Link
http://jsfiddle.net/2h5ew8fq/

[2.1.0](http://jsfiddle.net/2h5ew8fq/2/)

### What is actually happening?
在IE11或Edge浏览器，el-table 固定表头会出现横向滚动条，少1px就不会出现滚动条

**Comment by Bimbaloo** [comment]
在chrome上也会有类似的问题。原本的行数较少不出现纵向滚动条，然后一旦数据变化倒是纵向滚动条出现的话，横向也会出现滚动条。但其实根本不需要出现的。

**Comment by lerit** [comment]
expect resolve it

**Comment by blooddrunk** [comment]
Same here with Chrome when `border` property set

**Comment by furybean** [comment]
@hellinnocence 请确认 2.1.0 版本中是否还有问题： http://jsfiddle.net/2h5ew8fq/2/

**Comment by masongzhi** [comment]
可以通过浏览器的 overflow: auto 重新计算宽度，[https://juejin.im/post/5afdb167f265da0b9f408163](https://juejin.im/post/5afdb167f265da0b9f408163)
