### ISSUE TITLE
table 无法出现横向滚动条，导致内容展示不全，另在tab页使用table也有问题

### ISSUE THREAD

**Issue by UtopiaScript** [ElemeFE/element#2951]
- table 无法出现横向滚动条，导致内容展示不全
<img width="920" alt="2017-02-22 1 41 53" src="https://cloud.githubusercontent.com/assets/10824667/23198750/b6035a92-f904-11e6-8936-9fdc9ae432f4.png">

- 另在tab页使用table必须给tab加样式，否则table的宽度一直重新计算并持续增加。
 .el-tabs {
    display: block;
    max-width: 940px;
  }
<img width="417" alt="2017-02-22 1 42 54" src="https://cloud.githubusercontent.com/assets/10824667/23198814/1a7ea756-f905-11e6-8cae-d909427f47fa.png">
<img width="957" alt="2017-02-22 1 43 15" src="https://cloud.githubusercontent.com/assets/10824667/23198821/20e452c6-f905-11e6-8046-a7ebe1d73b69.png">

**Comment by qingqiuerpan** [comment]
你好，我也遇到这个问题了，请问你解决了吗？
