### ISSUE TITLE
Dialog 裡面又有 Dialog 顯示不正確

### ISSUE THREAD

**Issue by GniN** [ElemeFE/element#2958]
### ElementUI version
1.1.6

### OS/Browers version
windows10/Chrome 56 

### Vue version
2.1.6

### Reproduction Link
http://jsfiddle.net/sfyuzavm/1/

### Steps to reproduce
1. 點button 開啟一第層的Dialog
2. 點Dialog 裡面的按鈕開啟第二層的Dialog

### What is Expected?
兩個Dialog應該有各自的mask

### What is actually happening?
第一層Dialog的 mask 消失了

**Comment by Leopoldthecoder** [comment]
在 DOM 结构上两个 Dialog 不要嵌套：http://jsfiddle.net/sfyuzavm/2/
