### ISSUE TITLE
NavMenu 能否添加 disabled 支持

### ISSUE THREAD

**Issue by zhengjiaqi** [ElemeFE/element#2959]
menu-item 源码中支持 disabled 这个props， 但是设置:disabled="true"之后只是给menu-item添加了 is-disabled 这个class而并没有对menu-item绑定的click事件做处理，即此时menu-item还是可点击的，同样el-submenu 也没有支持disabled，可以考虑加入disabled吗，谢谢

**Comment by baiyaaaaa** [comment]
Duplicate of #8770
