### ISSUE TITLE
tooltip弹层为什么不放在body下面，或者是否可以全部放到body下面？

### ISSUE THREAD

**Issue by acelan86** [ElemeFE/element#296]
以tooltip为例，在.vue文件中真正的弹层是放在组件节点下面的，使用ref="popper"来引用
在初始化的时候通过this.$refs.popper传递给new Popper创建，这样的话所有的弹层都在父节点下，会导致在table中弹出的层无法突破z-index的限制被overflow掉，展示不全

```javascript
<x-table-column
        label="姓名"
        sortable
        width="180"
        inline-template>
        <div>
          <x-popover :content="row.address" placement="top" ref="test" trigger="click"></x-popover>
          <span v-popover:test>{{ row.name }}</span>
        </div>
      </x-table-column>
```
看到table中的show-tooltip-when-overflow的做法是手工提取到body中，为什么不把所有的popper都创建到body下面？

**Comment by erguotou520** [comment]
有时候tooltip放在父组件下方是更好的方案，但有时候放在body上更好，可以提供个属性`append-body`来设置最好

**Comment by acelan86** [comment]
：） 也可以，如果是这样的话，那我感觉append-body 默认true 比较常见

**Comment by acelan86** [comment]
这个还是要重提下重要性，没人觉得不合适么？我把日历控件，select等放到table中都不正常，改代码把这些控件的popper放到body下面，需要注意：
1、body的节点在router change的时候需要清除
2、popper的宽度需要重新设置，原来都是100%
3、clickoutside对放到body下面的节点判断有问题，点击popper会回收popper
4、table的一些子组件可以把`@click`都改成`@click.stop`防止意外问题

总感觉整体的具有弹层的组件还不够统一，有点乱的感觉，希望大神组织重构一下~
