### ISSUE TITLE
动态创建的checkbox，选择效果没有了

### ISSUE THREAD

**Issue by 3ccc** [ElemeFE/element#2960]
@Leopoldthecoder  大神，demo在此[点击查看](https://jsfiddle.net/ccc3/zaxab4cr/)

**Comment by Leopoldthecoder** [comment]
请提供一个在线 demo

**Comment by 3ccc** [comment]
https://jsfiddle.net/ccc3/zaxab4cr/

**Comment by 3ccc** [comment]
@Leopoldthecoder  大神，demo在此[点击查看](https://jsfiddle.net/ccc3/zaxab4cr/)

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/zaxab4cr/1/
参考 #2880
