### ISSUE TITLE
上传图片 缩略图 比例(样式)如何设置

### ISSUE THREAD

**Issue by ayizhi** [ElemeFE/element#2966]
上传图片，设置thumbnail-mode为true

上传完成后，缩略图永远都是长方形比例，如何设置这个比例？ 

（外面加了el－col，但是并不能对upload缩略图长度有效控制）

**Comment by baiyaaaaa** [comment]
1.2 的 upload 升级了，thumbnail-mode 被弃用，请自行通过slot显示图片

**Comment by Hideer** [comment]
如何通过slot显示图片@baiyaaaaa 文档中并没有此类具名slot
