### ISSUE TITLE
Tree组件设置default-checked-keys不起作用

### ISSUE THREAD

**Issue by pod4g** [ElemeFE/element#2967]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 56

### Vue version
2.1.10

### Reproduction Link
https://jsfiddle.net/yhmL60mt/1/

### Steps to reproduce
点击`”选中第2个“`按钮

### What is Expected?
Tree的第二个节点，即`“Level one 2”`节点被选中

### What is actually happening?
Tree的第二个节点没有被选中

**Comment by pod4g** [comment]
没人回答吗？

**Comment by Leopoldthecoder** [comment]
应该是 bug，后面会修。

**Comment by Kingwl** [comment]
@Leopoldthecoder close this plz

**Comment by Leopoldthecoder** [comment]
@pod4g It's fixed now. You should use `this.$refs.tree.setCheckedKeys([2])`, which you commented in the demo.

**Comment by guozimo** [comment]
hahha

**Comment by guozimo** [comment]
我也没效果啊
