### ISSUE TITLE
element1.2 upload list-type="picture-card" 和 drag 同时使用

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#2970]
upload 组件drag情况 同时 list-type="picture-card"情况下 upoad__text 不显示  
[demo](http://jsfiddle.net/kLeohzpp/1/)
是不支持一起使用么？

**Comment by baiyaaaaa** [comment]
是的

**Comment by PanJiaChen** [comment]
其实他们功能上并不是冲突的，只 el-upload--picture-card与el-upload-dragger样式上有冲突而已 
加一个简单的判断就行了

**Comment by liril-net** [comment]
移到需求池里了。
