### ISSUE TITLE
date picker (range) format of displayed date miss week day name to get Fri 20. Feb 2017

### ISSUE THREAD

**Issue by frankleja** [ElemeFE/element#2972]
### ElementUI version
1.1.6

### OS/Browers version
Win 7, Chrome, Firefox, 

### Vue version
2.1.10

### Steps to reproduce
<el-date-picker type="daterange" format="dd. MMM yyyy"...
produce a display within input field
27. Mar 2017 - 30. Mar 2017

### What is Expected?
display format of 
**Mon** 27. Mar 2017 - **Thu** 30. Mar 2017

### What is actually happening?
there is no format pattern for the week day name (short or long) documented/supported

**Comment by Leopoldthecoder** [comment]
Now it can be done: https://jsfiddle.net/on1640aj/
We'll add it to the doc soon.
