### ISSUE TITLE
select选择框的name属性获取到的值为label绑定的值，能否获取到对应的value值？

### ISSUE THREAD

**Issue by BingoXiao** [ElemeFE/element#2973]
在select选择框设置name属性，通过表单获取的name属性值为label的绑定值，能否获取select对应的value值？

**Comment by Leopoldthecoder** [comment]
没太理解，能用一个在线 demo 说明吗？

**Comment by AaronChen2012** [comment]
应该说的是label的值吧，this.$refs.xxx.label可以获取到啊
![image](https://cloud.githubusercontent.com/assets/3069732/23246782/f6e134a4-f9d0-11e6-926d-35adf2b2aa53.png)
