### ISSUE TITLE
行内form表单加了label-width后，form-item的content会产生跟label-width一样的左边距

### ISSUE THREAD

**Issue by yeyuqiudeng** [ElemeFE/element#2975]
### ElementUI version
1.2.0

### Browers version
Chrome 56.0.2924.87

### Reproduction Link
http://jsfiddle.net/uzhmLLtk/1/

### What is Expected?
产生合适的边距，另外希望表单元素可以有一致的宽度。
![image](https://cloud.githubusercontent.com/assets/10278227/23218286/dd54b792-f956-11e6-8cae-11da1628cae9.png)

**Comment by kopheece** [comment]
看了你的demo，是因为你用了:inline="true"的属性。
现在select组件的长度不是100%，如果要想对齐input，select组件加个style="width:100%"即可

**Comment by yeyuqiudeng** [comment]
@kopheece 
的确是加了inline后才会有如此的表现，这个应该是bug吧？正常情况下，label和content的margin应该是固定值吧？

**Comment by AaronChen2012** [comment]
临时修改.el-form--inline .el-form-item__content, .el-form--inline .el-form-item__labe{
		display: block !important;
	}

**Comment by Leopoldthecoder** [comment]
Fixed in #2990
