### ISSUE TITLE
[ColorPicker] feature

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#2978]
1. 希望支持手动输入颜色码（最好支持RGBA）
2. 希望支持默认颜色值 在界面里可以选择 ( :defaultColors= ['#ccc','#bbb'] )

参照插件 http://xiaokaike.github.io/vue-color/

**Comment by Leopoldthecoder** [comment]
手动输入颜色值会在后面的版本中加入。
由于颜色选择器在后台系统中其实并不常用，所以我们只会提供最基本的功能。「提供一组默认颜色供用户选择」应该不会做，事实上，这个功能自己实现一下也不复杂。

**Comment by yelingfeng** [comment]
好的 谢谢恢复
