### ISSUE TITLE
CDN方式引入，IE下icon消失

### ISSUE THREAD

**Issue by leexsfe** [ElemeFE/element#2980]
CDN方式引入element-ui，在IE浏览器包括edge，icon图标消失，控制台报错，提示
@font-face 跨源请求失败。资源访问受限。

这种方式怎么解决呢，组件的icon都不见了，自定义起来比较麻烦

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/icon.css 

icon 这个文件一直没动过，能看下报错信息么
