### ISSUE TITLE
tree通过节点过滤把某些节点过滤了，子节点全部过滤之后父节点还有展开按钮

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#2981]
![qq 20170223103633](https://cloud.githubusercontent.com/assets/16487810/23242456/d37ab0ca-f9b3-11e6-9386-b032f3b57554.png)

**Comment by FlappyHeart** [comment]
你把空的children数组去掉试试

**Comment by killdada** [comment]
刚发现不仅仅是这个有问题，http://jsfiddle.net/aehne7bf/ 这个是正常的，
![qq 20170302145927](https://cloud.githubusercontent.com/assets/16487810/23496361/b3aa7758-ff58-11e6-95d6-2eaf2c77c6bb.png)
本地项目下，有问题
![qq 20170302150008](https://cloud.githubusercontent.com/assets/16487810/23496381/ce285fb4-ff58-11e6-83c6-a28d49fcabf5.png)

环境配置  "element-ui": "^1.2.3",   "vue": "^2.1.0",

**Comment by killdada** [comment]
找到了，别人修改了里面的样式，我把其中一个样式去掉就正常了，
