### ISSUE TITLE
dialog的open事件中并不能取道当前dialog中元素

### ISSUE THREAD

**Issue by ayizhi** [ElemeFE/element#2984]
需要在dialog的open事件中获取dialog中的dom元素，但open事件中获取不到，加了个settimeout就可以，看起来open事件触发时dom还未被建立有一定延时

请问如何不用settimeout就能获取元素？有没有对应的回调接口？

**Comment by AaronChen2012** [comment]
open后
this.$nextTick(function () {
//访问dialog中的元素
})

**Comment by Leopoldthecoder** [comment]
Dialog 里的内容是懒加载的，只有当第一次打开它时才会渲染里面的 DOM 结构，所以你说的这个问题是存在的（仅存在于第一次打开时），`setTimeout` 或者楼上说的 `nextTick` 都可以。
