### ISSUE TITLE
Tooltip文字提示在firefox 51下无效

### ISSUE THREAD

**Issue by cdyue** [ElemeFE/element#2985]
Tooltip文字提示在firefox 51下无效，无法显示出来。
系统为macOS，同环境下chrome和safari没有此问题。

**Comment by Leopoldthecoder** [comment]
看了下官方文档是可以正常显示的，请提供有问题的 demo

**Comment by QingWei-Li** [comment]
![image](https://cloud.githubusercontent.com/assets/7565692/23244140/4260f026-f9be-11e6-879f-234d9e4e5fd8.png)

**Comment by cdyue** [comment]
测试过了，之前写法是：
```
<button>
  <el-tooltip>
  </el-tooltip>
</button>
```
现在换了个层次就没问题了。
```
<el-tooltip>
  <button>
  </button>
</el-tooltip>
```
