### ISSUE TITLE
How to set a default highlighted item after tree view created?

### ISSUE THREAD

**Issue by FlappyHeart** [ElemeFE/element#2987]
I have a tree view for some categories, and I want to choose a default item after the tree was created.

What I need is exactly the highlight feature, I don't want to add some checkboxes.

我做了一个树形菜单，现在需要在显示之后，默认高亮一个，表示默认选中。官方文档中没有看到相应功能，我自己也是刚入门，不知道如何实现。

**Comment by Leopoldthecoder** [comment]
参考 http://jsfiddle.net/9jz7endt/

**Comment by FlappyHeart** [comment]
谢谢，我设置node key的时候用了冒号，还是语法不熟悉。
