### ISSUE TITLE
更新为1.2.0后，table在设定固定列时，对不齐了，之前版本没问题的，貌似以前修正过又回去了！

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#2991]
![image](https://cloud.githubusercontent.com/assets/3069732/23247693/6cca0146-f9d6-11e6-8875-47e3a683ba5a.png)

![image](https://cloud.githubusercontent.com/assets/3069732/23247699/788cc202-f9d6-11e6-8f0b-38440e91e69a.png)

**Comment by jumpingfrog0** [comment]
同样的问题。

**Comment by liril-net** [comment]
@AaronChen2012  @jumpingfrog0  能给个 demo吗，我没法重现这个情景

**Comment by Leopoldthecoder** [comment]
@liril-net http://jsfiddle.net/8xgef567/

**Comment by liril-net** [comment]
@Leopoldthecoder 我知道问题在哪了，，

**Comment by DaDaDaDaDaBocai** [comment]
我想问 我现在1.1.6 怎么升级到 1.2.3 啊？ 需要哪些命令？

**Comment by Leopoldthecoder** [comment]
Fixed in 1.2.2

**Comment by GlemonGan** [comment]
1.3.7版本又出现这个问题了
![2017-07-05_16-54-59](https://user-images.githubusercontent.com/28922801/27858870-72507fa6-61a9-11e7-8fff-809849e8c604.png)
![2017-07-05_17-48-45](https://user-images.githubusercontent.com/28922801/27859093-39f34b88-61aa-11e7-9745-a9f69b8012fb.png)
