### ISSUE TITLE
动态添加表单 怎么验证每一个值

### ISSUE THREAD

**Issue by AliceSong1** [ElemeFE/element#2994]
<x-form-item
        v-for="(domain, index) in formData.url"
        :label="'域名' + (index + 1) + '：'"
        :prop="'url.' + index"
        :rules="[
          {
            required: true, message: '域名不能为空', trigger: 'blur'
          },
          {
            validator: (rule, value, callback) => {
              if (value === '') {
                callback(new Error('域名不能为空2'))
              }
              callback()
            }
          },
        ]">
<x-form-item>

这里的value值应该怎么写

**Comment by Leopoldthecoder** [comment]
你好，请使用 gitter 提问，issue 只用于提交 bug 和 feature request，谢谢！
