### ISSUE TITLE
el-carousel #2775在更新1.2.0后使用vuex更新时候仍然存在

### ISSUE THREAD

**Issue by jyyzzjl** [ElemeFE/element#2995]
### ElementUI version

1.2.0

### OS/Browers version

Chrome 
### Vue version

2.1.0
### Steps to reproduce
代码如下,advertList是从后台获取的广告列表，为简化演示，这里显示为初始数字2，从后台获取信息后，更新为4：
`<div>
      <div v-for="item in advertList" >
        {{item}}
      </div>
      <el-carousel>
        <el-carousel-item v-for="item in advertList">
          {{item}}
        </el-carousel-item>
      </el-carousel>
    </div>`

vuex中初始化代码如下：
`const state = {
  advertList:2,
}`
更新数据代码为：
`  [GET_INDEX_MUTATION](state,data){
state.advertList=4;
}`

页面computed中代码为：
    computed: mapState({
      advertList:(state)=>state.index.advertList,
})

实际效果展示，以下代码更新为4个div
     ` <div v-for="item in advertList" >
        {{item}}
      </div>` 
以下代码仍然为2个：
       ` <el-carousel-item v-for="item in advertList">
          {{item}}
        </el-carousel-item>` 

如下图所示：
![image](https://raw.githubusercontent.com/jyyzzjl/vue-zjl/master/static/1.png)
![image](https://raw.githubusercontent.com/jyyzzjl/vue-zjl/master/static/2.png)
![image](https://raw.githubusercontent.com/jyyzzjl/vue-zjl/master/static/3.png)
![image](https://raw.githubusercontent.com/jyyzzjl/vue-zjl/master/static/4.png)

问题更新：
经测试，在页面上只有一个carousel 的时候此问题不会出现，我的页面上谢了两个carousel，第二个items可以正常，第一个会出现此问题

**Comment by Leopoldthecoder** [comment]
最新版已解决。
