### ISSUE TITLE
使用 el-popover 组件报这个错 有遇到吗

### ISSUE THREAD

**Issue by amnsss** [ElemeFE/element#2998]
![image](https://cloud.githubusercontent.com/assets/12807953/23254433/0ba5932c-f9f3-11e6-8d8b-147059db06b4.png)

**Comment by Leopoldthecoder** [comment]
贴一下你的 `funnelList` 组件代码，和项目引入 Element 部分的代码

**Comment by jinjinwa** [comment]
可能是因为你代码顺序问题。

<el-popover
  ref="popover1"
  placement="top-start"
  title="标题"
  width="200"
  trigger="hover"
  content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
</el-popover>
<el-button v-popover:popover1>hover 激活</el-button>

这段代码，button和popover换个顺序，就会报错。

**Comment by hasbug** [comment]
确实是个bug，如果按钮在前面  popover在后面，就会报找不到$ref.奇葩

**Comment by jinglf000** [comment]
@QingWei-Li @hasbug 
这确实是个bug
```
    <el-input icon="caret-bottom"
	v-model="mulit"
	v-popover:popover3
	>
	</el-input>
	<el-popover
	  ref="popover3"
	 width="120"
	v-model="visible"
	>
	    这是一个v-popover的测试
	</el-popover>
```
![image](https://user-images.githubusercontent.com/14195057/30049022-7a5cd8de-924b-11e7-8237-18895b8e47c9.png)
