### ISSUE TITLE
build ERROR

### ISSUE THREAD

**Issue by sqrtqiezi** [ElemeFE/element#3]
下载后执行: npm run dev报错，先是缺了几个个依赖声明：
async-validator
throttle-debounce
wind-dom
babel-helper-vue-jsx-merge-props（这个报 babel-plugin-transform-vue-jsx@3.1.0依赖babel-helper-vue-jsx-merge-props@^2.0.0，但是预装了1.0.1）
babel-preset-es2015
css-loader

手动添加上述包，执行完成npm run dev，然后访问预览页面报如下错误：
`Module build failed: Error: ENOENT: no such file or directory, open '<project-directory>/element/packages/dialog/node_modules/vue-popup/lib/popup.css'`

**Comment by QingWei-Li** [comment]
如果是 windows 下，参考 Makefile 文件里的 shell 脚本，要执行 lerna bootstrap 安装 packages 的依赖，后期会改掉，都放到 npm script 里

**Comment by sqrtqiezi** [comment]
没注意看还有个Makefile，习惯性的先去瞅 package.js 里都有啥。已经将demo运行起来
It works awesome!
