### ISSUE TITLE
el-menu behaviour change

### ISSUE THREAD

**Issue by woshihaoren** [ElemeFE/element#3000]
### ElementUI version
1.2.1

### Vue version
2.1.5

### Reproduction Link
https://github.com/lynzz/element-admin  
这个项目vuejs版本升到2.1.5 就会有这个问题

### Steps to reproduce
vuejs版本是2.1.5或更高，配合vue-router工作时， el-menu 页面效果会改变

当点击el-submenu 下的子item
vuejs 2.1.5以前的版本，页面效果只会发生字体颜色改变
vuejs 2.1.5以后的版本，el-submenu 会有很快的重打开的画面闪一下。

**Comment by baiyaaaaa** [comment]
element 版本是 1.2.1？好像有点老了，更新到最新试试
