### ISSUE TITLE
el-radio-button 换行后左边框消失

### ISSUE THREAD

**Issue by changjunhao** [ElemeFE/element#3005]
### ElementUI version
1.2.1

### OS/Browers version
 macOS/Chrome 56

### Vue version
2.1.10

![img](https://cloud.githubusercontent.com/assets/7688639/23260851/c02afa88-fa0e-11e6-9c95-0cc54599d944.png)

**Comment by Leopoldthecoder** [comment]
感觉这种几十个选项的场景不太适合用 RadioButton 来呈现。

**Comment by changjunhao** [comment]
虽然不是很合适，不过确实很直观，而且这确实是个bug

**Comment by Leopoldthecoder** [comment]
因为 RadioButton 是不考虑换行的。这种场景下如果一定要使用，请自行覆盖 CSS。
