### ISSUE TITLE
Feature Request: User input in cascader option

### ISSUE THREAD

**Issue by Chris0lsen** [ElemeFE/element#3007]
### ElementUI version
1.2.1

### OS/Browers version
Windows 7/Chrome 56

### Vue version
 2.1.10

### Reproduction Link
None - feature request

### Steps to reproduce
```
<template>
  <el-cascader :options="userInputOptions"></el-cascader>
</template>
<script>
  ...
  userInputOptions = [{
     value: 'guide',
          label: 'Guide',
          children: [{
            value: 'disciplines',
            label: 'Disciplines',
            children: [{
              value: /** I'd like to let a user input a value here when guide->disciplines is selected **/,
              label: 'Consistency'
            }]
  }]
  ...
```
### What is Expected?
As a developer, I want to allow a user to input text in the last child of a cascader, and have that text bound to the v-model.

### What is actually happening?
Cascader options cannot contain el-input elements

I'm writing a search tool that lets users dynamically build a query from a table of data, and I want to use a cascader to return an array like ['id', '=', '//some user input']. To my knowledge, this is not currently possible.

I'm new to Vue and ElementUI, so I'm posting this here as an issue instead of making a PR, but I'd be happy to submit a PR if I can hack this functionality together on my own.

EDIT: I forgot to say: Thank you! ElementUI is a great library, especially for someone coming from an angular-material background. Thanks for maintaining this project.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
