### ISSUE TITLE
element.eleme.io   elementUI网站打不开了

### ISSUE THREAD

**Issue by 3ccc** [ElemeFE/element#3009]
[http://element.eleme.io/#/zh-CN](http://element.eleme.io/#/zh-CN)打不开啦

**Comment by jikkai** [comment]
搭个梯子翻一下

**Comment by 3ccc** [comment]
搭梯子也不行，你可试试用chrome的隐身模式打开网页试试，打不开

**Comment by jikkai** [comment]
@3ccc 
![image](https://cloud.githubusercontent.com/assets/14025786/23286310/dacca5e0-fa71-11e6-97a7-7c9ce55add98.png)

**Comment by 3ccc** [comment]
@jikkai  解决了，强行设置了DNS为 8.8.8.8 可以打开了。
