### ISSUE TITLE
用webpack-simple 创建了一个项目，然后安装element-ui并按照文档import element-ui，但是运行的时候提示element-ui.common.js中的window is not defined

### ISSUE THREAD

**Issue by webKity** [ElemeFE/element#301]
用webpack-simple 创建了一个项目，然后安装element-ui并按照文档import element-ui，但是运行的时候提示element-ui.common.js中的window is not defined

**Comment by QingWei-Li** [comment]
https://github.com/ElementUI/element-starter 这个模板是根据 webpack-simple 改的，你试试看

**Comment by webKity** [comment]
谢谢，可以的
