### ISSUE TITLE
form表单验证，修改error值显示错误信息，再调用重置方法，再次修改error值不能显示错误

### ISSUE THREAD

**Issue by yorkexing** [ElemeFE/element#3010]
### Steps to reproduce
1. 绑定一个错误提示信息变量 errormsg
 <el-form-item prop="email" label="邮箱"  :error="errormsg" >
    <el-input v-model="dynamicValidateForm.email"></el-input>
  </el-form-item>

2. 触发某个方法，修改errormsg值
   adderror(){
           this.errormsg = 'xxxxxx';
      }

3. 能够看到界面正常显示，错误提示
4. 调用resetFields重置所有错误。
     resetForm(formName) {
        this.$refs[formName].resetFields();
      },

5.再次触发adderror，显示错误信息
   adderror(){
           this.errormsg = 'xxxxxx';
      }
6. 界面不能正常加载错误信息。

### What is Expected?
希望，再次调用adderror时，能够显示错误。
因为，我是后台验证，错误提示是后台通过的。前台不验证或者前后台都要验证

### What is actually happening?
1. 如果方法是下列方法，重置错误后，再次调用，页面不能加载错误
    adderror(){
           this.errormsg = 'xxxxxx';
      }

2. 如果方法是下列方法，重置错误后，再次调用，页面能加载错误
   adderror(){
           this.errormsg = 'xxxxxx' +　 Math.random();
      }

3. 但是实际运用中，肯定是1里面的方法

**Comment by EvansLyb** [comment]
I think it is what actually happen: https://github.com/ElemeFE/element/issues/2691#issuecomment-278421767
