### ISSUE TITLE
1.2.0 dialog 内容区域无法点击

### ISSUE THREAD

**Issue by Baozi2** [ElemeFE/element#3013]
<img width="956" alt="qq20170224-110558 2x" src="https://cloud.githubusercontent.com/assets/5621510/23288931/6cafb1d2-fa81-11e6-88c5-f9e779fdc7cf.png">

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by bigtrouble** [comment]
或许跟 dialog 父元素的 position 样式有关。

**Comment by fangxingguang** [comment]
测试发现 如果dialog父元素有position: fixed;  会出现截图遮罩层的bug

**Comment by Leopoldthecoder** [comment]
可以通过把 Dialog 的 `model-append-to-body` 设为 `false` 来解决。

**Comment by Baozi2** [comment]
自己的布局中使用了一个 z-index
