### ISSUE TITLE
table组件在使用了fixed时候，行会错乱

### ISSUE THREAD

**Issue by okjesse** [ElemeFE/element#3016]
![1487907662 1](https://cloud.githubusercontent.com/assets/2336187/23289670/4beb37a0-fa86-11e6-8801-db179b83ad7a.png)

**Comment by okjesse** [comment]
在中间某列有换行的情况会出现这个问题

**Comment by QingWei-Li** [comment]
会尽快发一个版本修复这问题

**Comment by Leopoldthecoder** [comment]
Duplicate of #2991
