### ISSUE TITLE
el-cascader node端开发 提示未知的定义元素

### ISSUE THREAD

**Issue by 3ccc** [ElemeFE/element#3017]
node端开发报错：
代码同下面浏览器端的例子
[Vue warn]: Unknown custom element: <el-cascader> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in anonymous component at D:\BusinessSystem\src\pages\test\test.vue)

vue.js?3de6:525 [Vue warn]: v-model is not supported on element type: <el-cascader>. If you are working with contenteditable, it's recommended to wrap a library dedicated for that purpose inside a custom component. 
(found in anonymous component at D:\BusinessSystem\src\pages\test\test.vue)

浏览器端开发是正常的：[https://jsfiddle.net/ccc3/bbgL2d2z/](https://jsfiddle.net/ccc3/bbgL2d2z/)

**Comment by 3ccc** [comment]
node端开发，其他如select input checkbox radio table之类的都是正常的

**Comment by 3ccc** [comment]
哦，是版本问题，我用的是1.1.6

**Comment by Leopoldthecoder** [comment]
Cascader 在 1.2.0 中才加入。

**Comment by yi-ge** [comment]
同样遇到这个问题，已解决，多谢！
