### ISSUE TITLE
v1.2.1 form在使用:inline="true"和el-col后 出现换行bug了

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#3020]
http://jsrun.net/cPpKp/edit
![image](https://cloud.githubusercontent.com/assets/3069732/23291140/09a45ce0-fa91-11e6-85e7-eab6bafbfba3.png)

在1.1.6版本时 ，对content添加 margin-left:label-width ;样式。1.2.1取消了这个样式引起的

**Comment by AaronChen2012** [comment]
这次升级貌似问题比较多，还是降回1.1.6版本了

**Comment by baiyaaaaa** [comment]
不是你说的这个问题，你的例子的问题是el-col的宽度分配太小而导致的换行

**Comment by AaronChen2012** [comment]
之前开发的都是按照官网上的例子做的，所以这次不能自动适应大小了，导致改动很多！！

**Comment by baiyaaaaa** [comment]
最新版已修复此问题
