### ISSUE TITLE
[Bug Report] table当 `data` 属性变化的时候，高亮的行没有保持

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#3023]
http://jsfiddle.net/mnr0e2ef/

步骤：
1.  随意选择一行
2. 点Add按钮
3. 结果高亮行消失

应该在 `data` 变化的时候，执行 `this.store.setCurrentRowKey(this.currentRow)`

@Leopoldthecoder

**Comment by liril-net** [comment]
应该是因为 `currentRow` 不是用索引，而是引用，你改了 `data`，其实就没有对应的那个 `row` 了。

**Comment by languanghao** [comment]
@liril-net 没错，这种估计是为了便利那些不使用`row-key`的场合，但是确实也带来了一些问题

**Comment by liril-net** [comment]
@languanghao 那你可以自己在业务里实现一下相关逻辑😀

**Comment by languanghao** [comment]
@liril-net 嗯，但是自己解决的话，需要给每个table弄个current-row-key，捕获@current-change，watch table data，感觉这里应该能解决一下，之前我跟 @Leopoldthecoder 反应过tree也有类似的问题，然后tree组件已经修正了 😃

**Comment by my9074** [comment]
这个问题解决了么？假如列表定时从后台获取数据，每次都会把当前选中的行取消掉 @languanghao

**Comment by MsMaxine** [comment]
同问，列表定时从后台获取数据，如何保证选中的行不被取消掉，谢谢

**Comment by furybean** [comment]
2.1.0 仍然存在，先标记为 Bug：http://jsfiddle.net/mnr0e2ef/1/

**Comment by languanghao** [comment]
@furybean 请问有啥修复的计划吗？

**Comment by superddr** [comment]
同样有这个问题， 实在不行要转投其他库了。。。。

**Comment by lerit** [comment]
发现并没有解决,当前只解决了一种特殊情况,就是下一次的数据只是上一次数据基础上,追加了数据的情况.
如果数据是去后台筛选,或者服务端排序后,当前行就乱了,这是例子:
