### ISSUE TITLE
el-dialog 和 el-cascader 一起使用 第一次正常，第二次打开el-dialog遮挡了el-cascader选项的内容

### ISSUE THREAD

**Issue by githubjaychen** [ElemeFE/element#3024]
el-dialog 和 el-cascader 一起使用,使用v-model绑定el-dialog的显示隐藏，第一次打开el-dialog，el-cascader显示正常，关闭后再打开，el-dialog 的 z-index增加了，导致 el-cascader 弹出的内容被el-dialog遮挡了

**Comment by mayako21126** [comment]
应该是vue的问题

**Comment by Leopoldthecoder** [comment]
Fixed in #3035
