### ISSUE TITLE
1.2.1 loading组件机制问题

### ISSUE THREAD

**Issue by yiling-e0** [ElemeFE/element#3026]
1.1.6版本时loading组件可以在页面进来时就渲染

而在1.2.0以上版本loading组件却在页面组件显示完成后才fadein出来

**Comment by Leopoldthecoder** [comment]
看上去 1.1.6 的 Loading 也是后面才 fade-in 进来：http://jsfiddle.net/leopoldthecuber/mng575t2/

事实上 1.1.6 到 1.2.0 的过程中没有修改过 Loading。

**Comment by yiling-e0** [comment]
@Leopoldthecoder 抱歉我看错了，是1.0.9的版本与1.2.0的差异   http://element.eleme.io/1.0/#/zh-CN/component/loading官方demo就能对比出来

**Comment by Leopoldthecoder** [comment]
那是因为那时的 Loading 还没有动画
