### ISSUE TITLE
Upload组件在 Chrome 52 以上会卡顿

### ISSUE THREAD

**Issue by ChowSyaka** [ElemeFE/element#303]
请问  上传组件怎么实现第二次上传时覆盖之前的上传记录
当accept为 image/*的时候  打开弹出框比较慢

**Comment by furybean** [comment]
@baiyaaaaa

**Comment by DanielWLam** [comment]
手动设置为image/jpg等，也是慢，是框架原因还是什么原因？之前用Webuploader也有同样情况，但是设置成image/jpg手动指定格式就可以解决，element好像不行

**Comment by DanielWLam** [comment]
看了源码，发现是thumbnail的时候，指定了image/*，导致chrome52以上的浏览器会卡顿

**Comment by saint3347** [comment]
我也碰到这个问题，确实是thumbnail的问题，删掉就不会卡。。

**Comment by baiyaaaaa** [comment]
@saint3347 开发的时候碰到过这个问题，貌似是chrome 在 mac 下的 bug，会很慢么？我这边试下来是会延迟个0.5~1s左右

**Comment by DanielWLam** [comment]
@baiyaaaaa windows和linux都会，是chrome的bug

**Comment by QingWei-Li** [comment]
见 https://github.com/ElemeFE/element/issues/1585#issuecomment-265333203
