### ISSUE TITLE
1.2.1 table 使用loading icon 时的样式问题

### ISSUE THREAD

**Issue by cfking** [ElemeFE/element#3030]
### ElementUI version
1.2.0、1.2.1

### Vue version

2.1.10
### Reproduction Link

http://jsfiddle.net/zqvydbdp/
### What is actually happening?
当:row-class-name和 el-icon name="loading"  搭配使用时样式会错乱，普通icon没有问题，只有loading会出错

**Comment by liril-net** [comment]
没看出问题，，

**Comment by cfking** [comment]
http://jsfiddle.net/api/post/library/pure/ 效果同这个比较，主要是:row-class-name的效果不好了

**Comment by cfking** [comment]
http://jsfiddle.net/zqvydbdp/1/ 效果同这个比较，主要是:row-class-name的效果不好了

**Comment by Leopoldthecoder** [comment]
同没看出问题，@cfking 能贴下截图吗？注明是哪里有问题。

**Comment by cfking** [comment]
![default](https://cloud.githubusercontent.com/assets/25999143/23346075/04c44b98-fcd2-11e6-950e-1b67d4ff169d.png)
![default](https://cloud.githubusercontent.com/assets/25999143/23346079/07c055a8-fcd2-11e6-9840-f56b6dd5c838.png)
@Leopoldthecoder 
chrome 54.0.2840.87 m

**Comment by Leopoldthecoder** [comment]
升级一下浏览器版本试试
