### ISSUE TITLE
table组件中的 el-table-column 在这种情况下面，会报 TypeError: cellChild is null 的错误。

### ISSUE THREAD

**Issue by zb7503** [ElemeFE/element#3036]
table组件中的 el-table-column（在另外的vue文件中，组件形式引用） 在这种情况下面，会报 **TypeError: cellChild is null** 的错误。
element的版本是：1.2.1
代码结构如下：
table 所在代码片段：
```
<el-table :data="dataList" highlight-current-row :border="true">
   <el-table-column prop="column1" label="字段1" width="200" />
   <el-table-column prop="column2" label="字段2" width="300" />
   <el-table-column prop="column3" label="字段3"  />
   <button-column :data="buttonList" />
</el-table>
```

button-column 文件的代码片段：
```
<template>
  <el-table-column label="按钮组" width="200" fixed="right">
    <template scope="scope">
      <el-button v-for="btn in data" type="text">{{btn.text}}</el-button>
    </template>
  </el-table-column>
</template>
```

由于button-column的fixed设置了right，当鼠标从table中的行移动button-column所在的列交界处时候，就报了TypeError: cellChild is null 的错误。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
