### ISSUE TITLE
关于 el-radio-group 增加垂直排列的建议

### ISSUE THREAD

**Issue by liyanlong** [ElemeFE/element#3037]
### ElementUI version

1.2.1

### 建议内容
使用 **`el-radio-group`**, 觉得只能进行水平排列有点单一.  是否可以增加垂直排列

可以尝试加上一个 `type` 来控制..
```vue
<template>
<el-radio-group v-model="selectMod" size="small" type="vertical">
      <el-radio-button label="第一列"></el-radio-button>
      <el-radio-button label="第二列"></el-radio-button>
      <el-radio-button label="第三列"></el-radio-button>
</el-radio-group>
</template>
<script>
export default {
  data () {
    return {
        selectMod: '第一列' 
    }
  }
}
</script>
```

### Exmaple
![image](https://cloud.githubusercontent.com/assets/8005864/23296783/9ac79d3e-fab1-11e6-94b0-d040bc8166d1.png)

**Comment by baiyaaaaa** [comment]
没有太多人有这个需求，可能暂时没有这个计划，你可以用CSS处理。

**Comment by An0nymous0** [comment]
@baiyaaaaa 同求

**Comment by liangklfangl** [comment]
同求

**Comment by Missna** [comment]
可以通过添加div实现垂直排列

`<template>
<el-radio-group v-model="selectMod" size="small" type="vertical">
<div v-for= index of 3>
 <el-radio-button label="第一列"></el-radio-button>
</div>

</el-radio-group>
</template>`

**Comment by ALiangLiang** [comment]
同求

**Comment by bilibiliou** [comment]
真坑，这个需求实现起来这么麻烦吗？

**Comment by popbayun** [comment]
<br/>

**Comment by plumos** [comment]
2020了，这个功能开发出来了吗？

**Comment by flyher** [comment]
`el-checkbox`嵌入个`style="display:block;"`临时解决一下吧。

**Comment by dd1994** [comment]
同求 现在每次都是覆盖样式

**Comment by guominfang** [comment]
@baiyaaaaa 这样样式需求很多人使用吧，希望能打开或者合并

**Comment by yiyiyiqi** [comment]
同求，2022了，需求实现了吗

**Comment by garbage-rubbish** [comment]
可以用div来实现。`<div><el-radio></el-radio></div><div><el-radio></el-radio></div>`

**Comment by ppkliu** [comment]
參考這篇, 手動對齊一下就可以了!
[https://stackoverflow.com/questions/46874662/vertically-aligning-radio-buttons-in-center-aligned-text](https://stackoverflow.com/questions/46874662/vertically-aligning-radio-buttons-in-center-aligned-text)
```

      <div style="text-align: center; display:block;">
        <el-radio-group v-model="myrole" class='radioDiv'>
            <div><el-radio :label="3" >AAAAAAAAAA</el-radio></div>
            <div><el-radio :label="2" >BBBBBBB</el-radio></div>
            <div><el-radio :label="1" >CC</el-radio></div>
            <div><el-radio :label="0" >DDDD</el-radio></div>
        </el-radio-group>
      </div>

/* 這邊放class 的css */
<style scoped>
 .radioDiv {
   margin: 0 auto;
   width: auto;
   text-align: left;
   display: table;
}
</style>
```

**Comment by warren30815** [comment]
A workaround is: 
1. add `style="display: table;"` to el-radio-group
2. wrap each el-radio with `div`

code:
<img width="322" alt="Screen Shot 2022-06-28 at 1 37 55 PM" src="https://user-images.githubusercontent.com/36834814/176101478-325f4456-fe6f-4a10-9078-6b159a2e0c62.png">

result:
![Screen Shot 2022-06-28 at 1 39 47 PM](https://user-images.githubusercontent.com/36834814/176101713-2799003a-361d-4662-a27e-39543eb74b1d.png)

**Comment by jxxl998** [comment]
set style `diaplay: flex;` works either.
