### ISSUE TITLE
ele V2.x建议增加<el-table> 嵌套<el-switch>元素的事件,表格列单个switch事件

### ISSUE THREAD

**Issue by EvanSole** [ElemeFE/element#3038]
```
...
<el-table-column prop="isActive" label="是否可用"  min-width="130" sortable>
      <template scope="scope">
           <el-switch
                  v-model="scope.row.isActive"
                 on-color="#13ce66"
                 off-color="#ff4949"
                  @click.native.change="isActiveSwitch()">
           </el-switch>
        </template>
</el-table-column>
...
```
table列表里使用了一个</el-switch>标签，用来直接激活/取消激活用户，目前change事件无法传递当前行列的信息，滑动全列都触发.如果能单独在列表操作则更好一点.谢谢

**Comment by qpxtWhite** [comment]
我也碰到个类似问题，你试下这样子：
`@change="handleSwitch(scope.$index, $event)">`
`handleSwitch(index, val){
...
}`
我这边好像行了

**Comment by Leopoldthecoder** [comment]
`@click.native.change` 这是什么用法？

**Comment by imac8t** [comment]
@Leopoldthecoder 原生事件

**Comment by EvanSole** [comment]
谢谢 ,  @qpxtWhite 方法可行

**Comment by liliangali** [comment]
![image](https://cloud.githubusercontent.com/assets/18063081/26409576/84f4bfce-40d3-11e7-9391-419b8c3bed87.png)


我的cstatus的值明明都是0啊 为啥打印出来都是1呢，这个问题怎么解决 @qpxtWhite

**Comment by AlenWang** [comment]
@liliangali on-value off-value 是用数字0,1还是字符串0，1？如果是数字的，要这样用的:on-value和:off-value
