### ISSUE TITLE
ColorPicker选择的颜色都变成黑色#000000

### ISSUE THREAD

**Issue by yeyuqiudeng** [ElemeFE/element#3041]
### ElementUI version
1.2.1

### OS/Browers version
macOS/Chrome 56

### Reproduction Link
这是官网的示例：http://jsfiddle.net/tk8psvq5/

![qq20170224-190611-hd](https://cloud.githubusercontent.com/assets/10278227/23301344/6f48c22e-fac4-11e6-8b5d-b1da37aae73c.gif)

**Comment by Leopoldthecoder** [comment]
具体是什么问题？没看出来有错

**Comment by yeyuqiudeng** [comment]
@Leopoldthecoder 
录了个屏

**Comment by Leopoldthecoder** [comment]
奇怪，我在 macOS/Chrome 56 下是正常的：
![untitled](https://cloud.githubusercontent.com/assets/10095631/23302317/40317846-fac9-11e6-9ef5-0c204e5ecc67.gif)

**Comment by yeyuqiudeng** [comment]
奇怪，safari、firefox、和QQ浏览器都可以，就是chrome不行，版本 56.0.2924.87 (64-bit)

**Comment by yeyuqiudeng** [comment]
@Leopoldthecoder sorry，知道原因了，与我安装的扩展有关
