### ISSUE TITLE
1.2.1 tooltip 里面用router-link 报错

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#3042]
![image](https://cloud.githubusercontent.com/assets/8121621/23301275/1cfae6d2-fac4-11e6-9516-cd6284daad93.png)

**Comment by PanJiaChen** [comment]
找到原因了是show-overflow-tooltip 导致的
[demo](http://jsfiddle.net/e1nqh9sk/2/)
去掉show-overflow-tooltip就好了

**Comment by kopheece** [comment]
@QingWei-Li   1.2.4版本   
`<el-table-column label="日期" width="180" show-overflow-tooltip>
     
      <template scope="scope">
          <router-link to="/foo">Go to Foo</router-link>
          <span style="margin-left: 10px">{{ scope.row.date }}</span>
        </template>
    </el-table-column>`

这样写还是报一样的错

**Comment by QingWei-Li** [comment]
抱歉我们没有在文档里注明，tooltip 不支持 router-link，如有需要自行绑定 `$router.push` ，因为要支持的话就不得不改回原来的方式，那样会大幅度降低 tooltip 的性能
