### ISSUE TITLE
New feature request: add some delay before showing the loading animation

### ISSUE THREAD

**Issue by lcrespom** [ElemeFE/element#3043]
The loading animation (http://element.eleme.io/#/en-US/component/loading) is very useful and its directive mode is very convenient.

This is mostly used when triggering an AJAX request, and the icon is hidden when the AJAX response arrives. If the AJAX request takes some time, the user experience is great.

But for waiting times that are below 200 ms, the user sees some flash that quickly appears and disappears. The user experience is quite bad since there is no need to show and then almost immediately hide the loading icon.

A convenient fix is to wait a reasonable short amount of time, e.g. 200 ms, before showing the loading icon. This would avoid the ugly flash for short waiting times. This waiting time could be optional and globally configurable.

**Comment by tuurbo** [comment]
How can you account for unknown connection speeds and latency? If you delayed it 200ms and it took 300ms to load, the user would still see it flash for 100ms, correct?

Wouldn't it be better to (optionally) force the user to see the loading icon a minimum of 500ms or so? If the request took 300ms, they would see the loading icon for an additional 200ms. If it took 2000ms, they would see it 2000ms.

**Comment by lcrespom** [comment]
You are right, but let's take statistics / probability into account:

Assuming the delay before displaying the loading animation is T, a request either takes t < T or t > T. For a good value of T (which can be tuned), the probability of the user seeing the flash is much lower than if the loading animation is displayed right at t = 0.

That could be proven statistically... I have not done that, but I have used this technique in the past (before Vue and Element) and it has worked perfectly fine for me.

**Comment by liril-net** [comment]
Maybe it is a better idea to control this by yourself, you can implement a  debounced method to open loading, cause this is not a common requirement for all users.

**Comment by franciscolourenco** [comment]
This is a common technique and one could argue it should event be enabled by default. I would re-open this issue, to make it at least an option.
