### ISSUE TITLE
input 输入框type为textarea时, 如果输入框的值时已回车开始, 修改不了输入框的值

### ISSUE THREAD

**Issue by evan-li** [ElemeFE/element#3044]
input 输入框type设为为textarea, 当点击回车时,需要清空输入框的值, 如果这时候内容是以回车开始, 就没办法清空输入框的值了

 简单写了一个demo: [https://jsfiddle.net/8489rpzv/4/](https://jsfiddle.net/8489rpzv/4/)

不要纠结于indexOf与lastIndexOf   问题又不是这个

**Comment by PanJiaChen** [comment]
不是很懂到底想要什么效果。。。
是这样子的么https://jsfiddle.net/8489rpzv/5/？

**Comment by evan-li** [comment]
是这个效果, 但是用chagne事件的时候为什么做不到?   这个算是个bug吧

**Comment by Leopoldthecoder** [comment]
#3595 #3762
