### ISSUE TITLE
希望提供设置使标签页页头能自动充满一行的空间

### ISSUE THREAD

**Issue by huhk-sysu** [ElemeFE/element#3045]
现效果：
![image](https://cloud.githubusercontent.com/assets/14769033/23302655/85b22248-faca-11e6-9275-68918e834bf6.png)

目标效果：
![image](https://cloud.githubusercontent.com/assets/14769033/23302931/094ae6ac-facc-11e6-8d28-596e53351519.png)

暂时可以通过设置`flex`的方式实现

**Comment by wacky6** [comment]
大佬们看看这个commit行不行：https://github.com/wacky6/element/commit/73ed584c5e8234aa8f6900b20af6fa5ae87b2a20

DEMO：https://jsfiddle.net/ep8hn01n/

屏幕宽度不够了会转成滚动模式。

**Comment by zzuieliyaoli** [comment]
@wacky6 老铁，你这个 Demo 不对吧 😳，还是我理解有错误。

**Comment by wacky6** [comment]
好像真是我的锅。DEMO链接更新了。
