### ISSUE TITLE
建议换一个表单验证库

### ISSUE THREAD

**Issue by hjkcai** [ElemeFE/element#3046]
`async-validator` 用起来十分蛋疼，文档也不是很看得懂。不如试试 `validate.js`

**Comment by hjkcai** [comment]
`validate.js` 针对的是“表单验证”而 `async-validator` 针对的是“对象验证”。差别就在于，表单数据很多时候都是字符串类型的（比如数字输入框，email输入框）。`validate.js` 的大部分验证都是针对字符串的（比如 `'1.23'` 可以通过数字类型验证），而 `async-validator` 的验证是真的去验证值的类型的（比如 `'1.23'` 不可以通过数字类型验证），所以说它“用起来蛋疼”。

**Comment by mohong** [comment]
蛋疼

**Comment by gengxuelei** [comment]
How to manually trigger a form error？

**Comment by baiyaaaaa** [comment]
we have no plan to change a validator, it will be a major impact to the component.
