### ISSUE TITLE
请问table组件在初始化的时候，能否增加默认选中某些行的属性呢

### ISSUE THREAD

**Issue by okjesse** [ElemeFE/element#3051]
以上~

**Comment by PanJiaChen** [comment]
[demo](http://jsfiddle.net/6yqkx7dt/

**Comment by okjesse** [comment]
@PanJiaChen 我指的是在使用selection这个属性，第一列为checkbox的情况下呢。和你这个不太一样
![1488000199 1](https://cloud.githubusercontent.com/assets/2336187/23328516/9c55bf94-fb5d-11e6-982e-b1ca4c896b22.png)
例如，初始化的时候就选中一些行

**Comment by PanJiaChen** [comment]
[demo](http://jsfiddle.net/6yqkx7dt/1/)

**Comment by okjesse** [comment]
谢啦~学习啦~

**Comment by songzeng2016** [comment]
用这个 row-style
