### ISSUE TITLE
notify通知如何防止无限调用？

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3052]
是否有机制判断，当已经有一个相同的notify的时候，在当前这个notify没有消失前不再触发新的notify？

现在文档中的例子，每次点击都可以出现一个notify，如何避免这个问题呢？

**Comment by Leopoldthecoder** [comment]
有提供 `onClose` 钩子：http://jsfiddle.net/leopoldthecuber/rpjwsuuf/

**Comment by ruofeng086** [comment]
嗯，尝试了onClose，只能手动设置了
