### ISSUE TITLE
select 出现在 dialog上时点击 select ，其他内容会模糊一下。

### ISSUE THREAD

**Issue by cliang0917** [ElemeFE/element#3053]
select 出现在 dialog上时点击 select ，或者选择select项时，其他内容会模糊一下，然后快速恢复。

官方的 dialog 示例也有类似情况。

Chrome 版本 55.0.2883.87 m

IE 11 没问题。

**Comment by Leopoldthecoder** [comment]
同 #2461，进展会在那边更新。
