### ISSUE TITLE
table 某一行属性很长 设置 fixed 行高度撑不起来

### ISSUE THREAD

**Issue by yuanyuanshen** [ElemeFE/element#3056]
![demo](http://sandbox.runjs.cn/uploads/rs/410/cyvsaybm/Snip20170225_1.png)

**Comment by tigerui** [comment]
我也遇到同样问题 
![qq20170225-152218](https://cloud.githubusercontent.com/assets/12542701/23329200/65ca742c-fb6e-11e6-95ac-bad2931de2e6.png)

**Comment by Metrakit** [comment]
Same mistake

**Comment by transtone** [comment]
同样的问题。

**Comment by yuanyuanshen** [comment]
我的windows 的chrome是没有问题的，但是在mac的chrome上显示就乱了。你们的是啥情况？

**Comment by Leopoldthecoder** [comment]
和 #2991 重复，下个版本发布

**Comment by niechengren** [comment]
1.2.6 还存在
