### ISSUE TITLE
upload上传文件，文件名乱码问题

### ISSUE THREAD

**Issue by DaDiaoShuai** [ElemeFE/element#3057]
### upload上传文件，文件名乱码问题

- 文件上传后，页面展示文件名并非所上传文件名

**Comment by baiyaaaaa** [comment]
没有碰到过你说的问题，请提供demo

**Comment by jikkai** [comment]
确认下字符编码是否为 UTF-8，~有一个注意点是 macOS 使用的 Unicode 规范形式是 NFD，Linux 和 Windows 使用的是 NFC，会导致一些组合字出现问题~。这个问题应该不属于 Element，可以来 [gitter](https://gitter.im/ElemeFE/element) 贴上相关截图或者代码询问

**Comment by QingWei-Li** [comment]
upload 并不会处理你的文件

**Comment by DaDiaoShuai** [comment]
@QingWei-Li 蟹蟹，是文件编码的问题 ，我自己的锅 [捂脸]
