### ISSUE TITLE
[Menu]建议导航栏增加属性

### ISSUE THREAD

**Issue by ritksm** [ElemeFE/element#306]
建议可以对el-menu中的el-menu-item增加slot属性，right表示右浮动

且建议增加属性标识是否需要hover效果底下的蓝条

**Comment by saint3347** [comment]
底下有蓝条挺好看的吧，没有的话交互提示就太不明显了

**Comment by ritksm** [comment]
可以有两种提示：
1、如果是菜单，那么显示蓝条border提示
2、如果只是右浮动的用户名链接、登出链接等，用hover高亮文字显示

不知是否可行？这个也可以做成参数吧，比如highlight="text/border"

举例一（方块高亮）：
![image](https://cloud.githubusercontent.com/assets/111809/19260977/b33eba3e-8fc0-11e6-9539-5fd95066994d.png)

举例二（文字高亮）：
![image](https://cloud.githubusercontent.com/assets/111809/19260981/c181b7a4-8fc0-11e6-9da2-73f141e5b2d3.png)
