### ISSUE TITLE
表单动态验证的问题

### ISSUE THREAD

**Issue by radicalviva** [ElemeFE/element#3062]
表单的某个`input text`元素，我需要发起`ajax`到后台去校验是否 合法
并且我想让这个元素的验证在提交的时候才触发
应该写 `trigger: XX` 这个`XX`写什么可以生效，我看了文档只知道`blur change`...
话说，`elm`的内置表单和`async-validator`还是有很大区别吧？

**Comment by baiyaaaaa** [comment]
写个非 blur change 的都可以，例如写个 trigger: submit，但不能为空
