### ISSUE TITLE
使用select和radio，关联数据切换显示的BUG

### ISSUE THREAD

**Issue by jaore** [ElemeFE/element#3066]
这个是[demo](http://flsho.com/)
demo里面有一些说明，愁死了，给select的option加了key还是不行，把for上面的时间绑定到select的change事件还是不行，实在无能为力了，有大神帮忙看看吗，demo用的element文档的CDN

**Comment by PanJiaChen** [comment]
至少用http://jsfiddle.net/或者其他的在线平台吧，你这样谁知道你代码有什么问题。。。。

**Comment by jaore** [comment]
@PanJiaChen  [在线平台](https://jsfiddle.net/mg9a1kyt/) 
放到这上面了，能帮忙看一下吗？谢谢了

**Comment by Leopoldthecoder** [comment]
使用 computed property：https://jsfiddle.net/leopoldthecuber/mg9a1kyt/1/

**Comment by jaore** [comment]
@Leopoldthecoder  感谢帮忙，支付宝捐助了点心意，希望element越来越强大

**Comment by Leopoldthecoder** [comment]
@jaore 感谢
