### ISSUE TITLE
如何点击按钮，然后将某一input框设置autofocus？

### ISSUE THREAD

**Issue by chinavane** [ElemeFE/element#3069]
一个表单里，在最后假设有reset按钮，点击按钮，想让第一个文本框自动聚焦。

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/leopoldthecuber/px6oeunq/

**Comment by yangfan0095** [comment]
如果代码是动态渲染的  在监视数据改变的语句后，加上this.$nextTick(function(){ });
