### ISSUE TITLE
请问element官网是用文档系统(eg..markdown->site)生成的么？bisheng ?

### ISSUE THREAD

**Issue by wangdadou** [ElemeFE/element#3071]

**Comment by liril-net** [comment]
@QingWei-Li 大佬快来解释

**Comment by QingWei-Li** [comment]
谢邀。用的 [vue-markdown-loader](https://github.com/QingWei-Li/vue-markdown-loader)

**Comment by zikuai** [comment]
这些markdown文档又是怎么生成的？ @QingWei-Li

**Comment by Monroe123** [comment]
请问md文件里面的style和script是怎么解析的呢

**Comment by wuyueCreator** [comment]
https://github.com/ElemeFE/element/tree/dev/examples
