### ISSUE TITLE
can't set height attribute as String in table component

### ISSUE THREAD

**Issue by fliu2476** [ElemeFE/element#3073]
#### table component
**version: 1.2.1**
- Table Attributes: Height can't set as String ( table's height will decrease from height(calc(100% - 60px)) to 0px ) 

```vue
<el-table
      :data="newUserData"
      height="tableHeight"
      border
```

```css
.table-wrapper .el-table{
    height: calc(100% - 60px);
```

**Comment by ultraN** [comment]
Have you solve it? I'm suffering this problem as well. I want to make the page responsive rather than fixed 'px'.

**Comment by fliu2476** [comment]
@ultraN it seems that there aren't officials solution, but...
```
.el-table {
        height: calc(100% - 136px)!important;
}
```
anyway, it works for me

**Comment by mcdongWang** [comment]
why close the issue
when use max-height by string 

is also can't seeting the set

and in the source code, i do not find some code to handle the height param by string
