### ISSUE TITLE
拖拽滑块会选中下面的东西

### ISSUE THREAD

**Issue by JavaCS3** [ElemeFE/element#3075]
### ElementUI version
1.2.1

### OS/Browers version
53.0.2785.116 m (64-bit)

### Vue version
2.2.0

### Steps to reproduce
![shot](https://cloud.githubusercontent.com/assets/4168698/23337668/766f52b2-fc30-11e6-9774-a63735a75925.gif)

### What is Expected?
不要选中下面的东西

**Comment by renxia** [comment]
@Leopoldthecoder 
这个问题，阻止 `mousemove` 事件的默认行为就行了，jquery-ui 都是这么干的。
参考如图：

![slider](https://cloud.githubusercontent.com/assets/2276421/23354607/0230ac1a-fd0d-11e6-8344-170dcd9958bb.png)

**Comment by Leopoldthecoder** [comment]
已经改了 #3080
