### ISSUE TITLE
Slider Max 设置过大导致 UI 性能下降

### ISSUE THREAD

**Issue by JavaCS3** [ElemeFE/element#3076]
### ElementUI version
1.2.1
### OS/Browers version
Chrome 53

### Vue version
2.2.0

### Reproduction Link
http://jsfiddle.net/javacs3/2ky89ta1/

### Steps to reproduce
Slider 的 Max设为99999
### What is actually happening?
UI几乎卡死

Profile
![shot](https://cloud.githubusercontent.com/assets/4168698/23337972/56b7fac4-fc39-11e6-961a-6dfdd9aab054.png)

**Comment by Leopoldthecoder** [comment]
1. 首先是因为设置了 `show-stops`，这样会有十万个节点被渲染出来；当滑动滑块时，这些节点全部需要重绘

2. 其次，对于一个需要让用户从十万个数里选一个的场景，我实在不觉得应该用 Slider

**Comment by JavaCS3** [comment]
@Leopoldthecoder 我用Slider是为了让用户选择一个价格区间，用滑块会方便很多

**Comment by Leopoldthecoder** [comment]
这样的话可以设置一个 `step`，十万以内的加个区间以一千为步长应该是可以接受的，不需要精确到个位。
