### ISSUE TITLE
表格头部标题渲染问题，动态加载prop

### ISSUE THREAD

**Issue by zhh419953** [ElemeFE/element#3077]
-  #数据类型是：
![image](https://cloud.githubusercontent.com/assets/14882369/23338135/fcf450ec-fc3c-11e6-841b-a2986b233a5c.png)
  我想 得到的图片结果是这样的：
![image](https://cloud.githubusercontent.com/assets/14882369/23338136/07ff5f4a-fc3d-11e6-9be0-693d2993499c.png)

**Comment by zhh419953** [comment]
![image](https://cloud.githubusercontent.com/assets/14882369/23338141/21ab3086-fc3d-11e6-8180-ee22d54e948f.png)
我这样写并不能生成预期表格出来

**Comment by zhh419953** [comment]
![image](https://cloud.githubusercontent.com/assets/14882369/23338146/41def054-fc3d-11e6-9be7-9385d20cfeb3.png)
我这样写并不能得到预期表格出来

**Comment by PanJiaChen** [comment]
[demo](http://jsfiddle.net/n2u5ejuz/)

**Comment by wulinsheng123** [comment]
你这个并不是动态的啊
