### ISSUE TITLE
固定列和表头，鼠标移动到缝隙的时候 会报错

### ISSUE THREAD

**Issue by baijie** [ElemeFE/element#3083]
### Steps to reproduce
问题：固定列和表头，鼠标移动到缝隙的时候 会报错
代码：
// 判断是否text-overflow, 如果是就显示tooltip
var cellChild = event.target.querySelector('.cell');

this.tooltipDisabled = cellChild.scrollWidth <= cellChild.offsetWidth;
报错：Uncaught TypeError: Cannot read property 'scrollWidth' of null

**Comment by ruofeng086** [comment]
![image](https://cloud.githubusercontent.com/assets/14192308/23395494/e4d1742a-fdc9-11e6-8559-037d10f72e60.png)

+1

**Comment by YzPaul3** [comment]
+1

**Comment by Leopoldthecoder** [comment]
给下 demo
