### ISSUE TITLE
pagination layout 的 total 问题

### ISSUE THREAD

**Issue by transtone** [ElemeFE/element#3088]
今天升级了一下 vue 和 element 到最新版，结果出现了一片这样的提示

<img width="717" alt="2017-02-27 12 44 43" src="https://cloud.githubusercontent.com/assets/46688/23341661/c4af4f4e-fc86-11e6-8bd5-047c97234749.png">

经过长时间排查，发现只要在 pagination 中加入 layout="total"，则会出现此错误提示，同时总条数不显示。而去掉total则正常。

**Comment by jkchao** [comment]
+1

**Comment by lampo1024** [comment]
+1

**Comment by Leopoldthecoder** [comment]
Fixed in #3097
