### ISSUE TITLE
tab键 切换到 el-select 后 输入内容无法发送远端检索的请求，回车键选择option 无法赋值

### ISSUE THREAD

**Issue by xnumb** [ElemeFE/element#309]
### ElementUI version

1.0.0.rc.4
### OS/Browers version

chrome
### Vue version 53

2.0.0
### What is Expected?

需要说明的是我是通过标签全局引入的方式用的
```
<script src="//unpkg.com/vue@2.0.0-rc.6/dist/vue.js"></script>
<script src="//unpkg.com/element-ui@1.0.0-rc.4/lib/index.js"></script>
```

```
el-form
    el-form-item
     some input element
    <el-select>
          v-model="form.add._serv"
          filterable
          remote
          :remote-method="queryServ"
          placeholder="请输入关键词或拼音简写"
          :loading="query.serv.loading">
          <el-option
            v-for="item in query.serv.list"
            :key="item.id"
            :label="item.name"
            :value="item.id">
          </el-option>
        </el-select>
    some input element
```

代码是这样的结构，

bug1

 el-form 里面还有其他的input元素
这时候我输入其他的输入框后，
用tab键 切换到这个el-select 后
直接输入内容无法发送远端桥区数据的请求。 
但是我如果用鼠标点击这个el-select 输入是可以正常发送请求的。

bug2

我用鼠标点击了这个el-select 然后输入检索字符串 远端正常返回数据 出现下拉列表，
这时候可以用上下箭头按键 选择内容 选中后直接用 回车键 选择 被选择的option 的id 没有赋值给 el-select的 v-model 变量
但是用鼠标click 这个option的时候是没问题的

### What is actually happening?

el-select 支持tab切换后检索与 回车键选择 option 并赋值

**Comment by xnumb** [comment]
另外我看了一下 
http://element.eleme.io/#/component/select
这里的远端搜索 里面也是有这个bug的

**Comment by Leopoldthecoder** [comment]
bug1 与 #235 重复，已经在 #240 中修复。

bug2 在 #316 修复。
