### ISSUE TITLE
el-menu-item作为dynamic component时候，hover和active的border-bottom效果缺失

### ISSUE THREAD

**Issue by mayaa6** [ElemeFE/element#3092]
### ElementUI version
1.2.1

### OS/Browers version
windows 10/ Chrome Version 56.0.2924.87

### Vue version
2.1.10

在`el-menu`元素中将el-menu-item作为dynamic components时候，导航元素的hover和active样式中，缺失蓝色的border-bottom

下图中，第一个“控制台”为直接放在el-menu下面的el-menu-item, 第二个的el-menu-item 为 dynamic compoents

![image](https://cloud.githubusercontent.com/assets/3221154/23346214/370f10b4-fcd3-11e6-8161-3bfdce24afa1.png)

![image](https://cloud.githubusercontent.com/assets/3221154/23346216/3cb212e6-fcd3-11e6-95a9-974985635257.png)

**Comment by cddsgtc** [comment]
同求在动态改变mode后，hover的vertical菜单出现子菜单效果消失
