### ISSUE TITLE
el-autocomplete 利用enter选中下拉项之后，页面无故重定向，url里多了一个'?'。

### ISSUE THREAD

**Issue by lanmaomm** [ElemeFE/element#3093]
例：页面链接从http://test.xxx.com/bench/index#/bench 变成了  http://test.xxx.com/bench/index?#/bench

### ElementUI version
1.2.1

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.0

### What is Expected?
希望问题得到解决，或者查出原因是什么

**Comment by Leopoldthecoder** [comment]
出现这个情况的 Autocomplate 是否存在与一个 Form 内部？

**Comment by baiyaaaaa** [comment]
在线文档上没有这个问题，能否提供个demo?在线或者仓库都行

**Comment by lanmaomm** [comment]
确实是存在于一个form内部的@Leopoldthecoder

**Comment by lanmaomm** [comment]
因为是公司的项目，所以不方便把仓库公开@baiyaaaaa

**Comment by Leopoldthecoder** [comment]
那是 `form` 的默认行为，在 `el-form` 标签上加 `@submit.native.prevent`。

**Comment by lanmaomm** [comment]
@Leopoldthecoder 多谢大神
