### ISSUE TITLE
分页组件渲染报错【Vue版本：2.2.1】

### ISSUE THREAD

**Issue by lampo1024** [ElemeFE/element#3095]
### ElementUI version
1.2.1

### OS/Browers version
Windows/Chrome

### Vue version
2.2.1

### What is actually happening?
分页组件渲染报错
当升级Vue到2.2.1版之后，分页组件渲染出错，错误信息：
![pagination-error](https://cloud.githubusercontent.com/assets/3262079/23346937/951134c0-fcd9-11e6-8e7d-e8e0ba8b01cb.png)
渲染后的效果：
![pagination-rendered](https://cloud.githubusercontent.com/assets/3262079/23346967/ae312b90-fcd9-11e6-962d-ddd81b0b17c1.png)
总记录数不能正确渲染出来。

**Comment by Leopoldthecoder** [comment]
Fixed in #3097
