### ISSUE TITLE
Vue2.2 removed hasOwn from Vue.util

### ISSUE THREAD

**Issue by dhcmrlchtdj** [ElemeFE/element#3096]
### ElementUI version
1.2.1

### Vue version
2.2.1

### What is Expected?
https://github.com/vuejs/vue/blob/v2.2.1/src/core/global-api/index.js#L33
Don't use `Vue.util.hasOwn`

### What is actually happening?
https://github.com/ElemeFE/element/blob/dev/src/locale/format.js#L10
https://github.com/ElemeFE/element/search?utf8=%E2%9C%93&q=%22Vue.util%22&type=Code
```javascript
TypeError: hasOwn is not a function
    at eval (eval at ./node_modules/element-ui/lib/locale/format.js
```

**Comment by transtone** [comment]
#3102

**Comment by renxia** [comment]
`vue` 的坑，说删就删了。。
希望可以尽快 release 一个版本

**Comment by baiyaaaaa** [comment]
今天会release
