### ISSUE TITLE
tag标签 为何不提供自定义的事件？

### ISSUE THREAD

**Issue by yansenlei** [ElemeFE/element#3099]

**Comment by yansenlei** [comment]
好吧，自己在遍历中加标签绑定就可以解决。

**Comment by lymne** [comment]
能详细说明一下如何在遍历中标签绑定吗？

**Comment by nyaapass** [comment]
@lymne 
参考这个: [饿了么ui添加事件](http://www.cnblogs.com/zhubei/p/7209764.html)
在自定义事件后面加上 `.native` 就可以了
