### ISSUE TITLE
navMenu router default-active错误

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#3101]
在启用route时，:default-active=“$route.path”，如果设置了router.beforeEach，路由被拦截了，route.path并没有改变，但是菜单却被激活了

**Comment by reverland** [comment]
路由被拦截了，$route.path怎么会变啊

**Comment by zlab** [comment]
所以啊，菜单怎么却被激活了呢

**Comment by whwnow** [comment]
这问题描述挺清晰了，直接被关……

**Comment by zhangshichun** [comment]
我也遇到了同样的问题。
