### ISSUE TITLE
table number排序bug

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3103]
### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/14192308/23348112/3f64d03c-fce2-11e6-8a0f-84cac63eea2e.png)

![image](https://cloud.githubusercontent.com/assets/14192308/23348136/73851e1c-fce2-11e6-8b12-cd403ab4bec9.png)

### What is Expected?

正确的排序应该是77在最底下

### What is actually happening?

77没有排在正确位置。

**Comment by Leopoldthecoder** [comment]
因为是字符串，'248' < '77' === true
