### ISSUE TITLE
upload 组件中 请求一个clearFiles()方法调用例子

### ISSUE THREAD

**Issue by xuyingchuan** [ElemeFE/element#3107]
http://element.eleme.io/#/zh-CN/component/upload

### Steps to reproduce
Methods

方法名	说明	参数
clearFiles	清空已上传的文件列表	—

这个方法如何调用，请求详细一些的文档

**Comment by baiyaaaaa** [comment]
`vm.clearFiles()` vm指向 `upload` 组件的实例

**Comment by xuyingchuan** [comment]
如果我在自己的父组件<uploader>里面想调用<el-upload>方法呢，现在通过this.$refs.elUploader.clearFiles()好像获取不到子组件<el-upload> 有没有什么好的办法

**Comment by xuyingchuan** [comment]
已解决 非常感谢

**Comment by enjoyZhou** [comment]
怎么解决啊?

**Comment by JasinYip** [comment]
文档确实写得很不明确，建议补一下文档和例子

**Comment by JasinYip** [comment]
我来提供一个例子吧：

```vue
<template>
  <div>
    <el-button @click="clearUploadedImage">重新上传</el-button>
    <el-upload ref="upload"></el-upload>
  </div>
</template>

<script>
export default {
  methods: {
    clearUploadedImage () {
      this.$refs.upload.clearFiles();
    },
  }
}
</script>
```

**Comment by yrdkiller** [comment]
使用 auto-upload = false 禁止自动上传文件后，没有办法调用：
this.$refs.upload.submit()
造成无法触发文件上传。
http://element.eleme.io/#/zh-CN/component/upload
文档中给的点击按钮上传示例是错误的，
<el-button style="margin-left: 10px;" size="small" type="success" @click="submitUpload">上传到服务器</el-button>
会提示无法绑定 click事件，而且示例没有给出 submitUpload 的定义。

**Comment by MikeNo007** [comment]
1

**Comment by wuwenrui** [comment]
@JasinYip 你这里不会报错吗？我按照你这么用：this.$refs就是 undefined
除非是clearUploadedImage(this)
然后在方法内部使用这个传递的 this 当做 this 来用
clearUploadedImage (event) {
      event.$refs.upload.clearFiles();
    }

**Comment by JasinYip** [comment]
@wuwenrui 这是 2017 年的贴子了，Vue 都不知道发展了多少代了，不行就再找别的方法吧~

**Comment by wuwenrui** [comment]
@JasinYip 我解决了：这么使用是可以的，通过传递 this 
```vue
<template>
  <div>
    <el-button @click="clearUploadedImage(this)">重新上传</el-button>
    <el-upload ref="upload"></el-upload>
  </div>
</template>

<script>
export default {
  methods: {
    clearUploadedImage (event) {
      event.$refs.upload.clearFiles();
    }
  }
}
</script>
```
