### ISSUE TITLE
1.2.1版本的el-table在flex布局下height会自动收缩

### ISSUE THREAD

**Issue by shennwei** [ElemeFE/element#3108]
### ElementUI version

1.2.1
### OS/Browers version

win10/Chrome55
### Vue version

2.2.1
### Reproduction Link

http://codepen.io/anon/pen/YZXZKB
### What is Expected?
想让el-table填充满父元素
### What is actually happening?
el-table会自动收缩高度

**Comment by lincenying** [comment]
你应该给父元素加100%

**Comment by shennwei** [comment]
你可以试一下，加了仍然是自动收缩

**Comment by lincenying** [comment]
不要在flex的子元素加

**Comment by shennwei** [comment]
可以给个例子吗？

**Comment by lincenying** [comment]
![image](https://cloud.githubusercontent.com/assets/10840991/23355588/65b7f1b8-fd11-11e6-96f7-3a835791d366.png)

**Comment by shennwei** [comment]
我试了还是会啊

**Comment by shennwei** [comment]
这样有另外一个bug，表格内容超过长度之后，不能向下滚动
![image](https://cloud.githubusercontent.com/assets/10250518/23355914/d384af1e-fd12-11e6-8e6f-0b2a583dec71.png)

**Comment by lincenying** [comment]
你表格内容的高度都大于150了, 你给它个150的高度, 能不被截断吗.

**Comment by shennwei** [comment]
那也应该出现滚动条啊，兄弟

**Comment by shennwei** [comment]
但是不会出现滚动条，不能往下拖动啊

**Comment by xiongsongsong** [comment]
我也遇到这个情况，1.2.3，表格会自动搜索高度，不停的循环。

**Comment by xiongsongsong** [comment]
试试```flex:1 1 0;```而不是```flex:auto;```

**Comment by ifibercc** [comment]
@shangkai 同遇到这个问题，不会有滚动条，不过有fixed列的话，出现滚动条只能滚动fixed列，不知官方如何处理
