### ISSUE TITLE
table组件在改变width时会抖动

### ISSUE THREAD

**Issue by xiaoguangma** [ElemeFE/element#3110]
![1](https://cloud.githubusercontent.com/assets/6637227/23353118/c8398ce0-fd05-11e6-8bd5-4aa30e9f17e1.png)
抖动中间过程
![2](https://cloud.githubusercontent.com/assets/6637227/23353122/d4a415f4-fd05-11e6-9108-ada289582a00.png)
页面最终效果
![b](https://cloud.githubusercontent.com/assets/6637227/23352844/6c29e3ba-fd04-11e6-933c-b6fe8f0563ee.gif)
GIF效果
### What is Expected?
table组件在改变width时能够平滑过渡
### What is actually happening?
table组件在改变width时会抖动，不知道是我的代码问题，table组件的问题

**Comment by yiwuyu** [comment]
你是怎么截gif的呢？我们的测试测出了某一个屏幕宽度最大化，pagesize为5条的时候狂抖，我也想截一个

**Comment by xiaoguangma** [comment]
@yiwuyu  工具名LICEcap  关于我的issue有解决方案么
