### ISSUE TITLE
表格type＝"selection"是否可以暴露一个checkbox是否选中的接口

### ISSUE THREAD

**Issue by csywweb** [ElemeFE/element#3112]
### ElementUI version
1.2.0

### Vue version
2.0.0

希望可以给type＝"selection"的表格暴露一个checkbox是否选中的接口

**Comment by PanJiaChen** [comment]
不是有么？
http://jsfiddle.net/n46qcsLp/

**Comment by lincenying** [comment]
他的意思应该是默认选中.

**Comment by PanJiaChen** [comment]
默认选中也可以啊。。
http://jsfiddle.net/6yqkx7dt/1/

**Comment by rossroma** [comment]
当我点击checkbox时，我希望能有一个额外的参数来告诉我，这次点击时选中还是取消选中。我觉得他应该是这个意思吧，这个功能我也挺需要的。 @PanJiaChen

**Comment by csywweb** [comment]
@rossroma 你这个可以监控所有的selection嘛。  这么也可以做到的。

**Comment by csywweb** [comment]
@PanJiaChen 多谢。我关闭issue了。主要对vue不熟悉，看到了那个方法不知道怎么使用。

**Comment by csywweb** [comment]
@PanJiaChen  动态生成的表格，在数据渲染之后调用方法， 并没有效果
```
this.$http.post().then(response => {
      this.tableData = reponse.body.data;
     this.filterData();  //并没有效果  静态的有效果
})
```

**Comment by csywweb** [comment]
@PanJiaChen  动态渲染不能用ref， 那么我应该用什么呢

**Comment by PanJiaChen** [comment]
this.$nextTick(_ => {
       this.filterData()
  });这样应该就好了

**Comment by csywweb** [comment]
@PanJiaChen 多谢帮助。可以了，

**Comment by moonose** [comment]
追问下  @PanJiaChen 大大，如果我要条件显示checkbox 用v-if是不是不可行？

http://jsfiddle.net/6q54y7h1/
