### ISSUE TITLE
table组件能否支持input搜索？

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3113]
能否支持input输入过滤显示？过滤条件跟input的change事件同步，
像截图中的一样，包含到关键字显示，现成有属性能实现吗？
![image](https://cloud.githubusercontent.com/assets/14192308/23356234/0dcfea66-fd14-11e6-96ae-0c2294cc61da.png)

希望实现的效果类似：
https://jbaysolutions.github.io/vue-bootstrap-table/examples/01-basic.html

**Comment by ruofeng086** [comment]
目前使用了input table组件，但还没找到属性可以让input的value过滤列表。

**Comment by Leopoldthecoder** [comment]
「让input的value过滤列表」需要自己编写。

**Comment by ruofeng086** [comment]
能否提供demo或告知思路，Thanks

**Comment by ruofeng086** [comment]
![image](https://cloud.githubusercontent.com/assets/14192308/23388550/d3e222d0-fd9d-11e6-9312-5afa84f8ec4a.png)
参考了vueBootstrapTable，他内部有两层筛选，而table组件没有row，只有column

![image](https://cloud.githubusercontent.com/assets/14192308/23388605/18655774-fd9e-11e6-90bc-d1cea4c71b04.png)

还有，怎么获取当前循环 i 呢？
