### ISSUE TITLE
table 如何手动设置某一行高亮？

### ISSUE THREAD

**Issue by wyjieying** [ElemeFE/element#3115]
table 如何手动设置某一行高亮？ 麻烦给个demo谢谢

**Comment by PanJiaChen** [comment]
#3051

**Comment by wyjieying** [comment]
@PanJiaChen 我是又能支持checkbox的情况又需要可以高亮！！

**Comment by PanJiaChen** [comment]
两个demo都给了，整合一下就好了，而且这是issue 有问题去https://gitter.im/ElemeFE/element提问
