### ISSUE TITLE
checkbox返回value问题，看了#647。 还是没看明白。

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#3116]
v-model 中接收到的checkbox为什么是label的值而不是value的值。
如果要获得value的值除了自己遍历对比，还有什么方法？
貌似大多数应用场景想获取的都应该是id而不是name啊。 没明白这么做的理由。

**Comment by An0nymous0** [comment]
下列是否是正确的写法？
`
<el-checkbox-group v-model="form.type">
      <el-checkbox label="1" value="1" name="type">美食/餐厅线上活动</el-checkbox>
      <el-checkbox label="2" name="type">地推活动</el-checkbox>
      <el-checkbox label="3" name="type">线下主题活动</el-checkbox>
      <el-checkbox label="4" name="type">单纯品牌曝光</el-checkbox>
    </el-checkbox-group>
`

**Comment by Hal-Chen** [comment]
老弟，解决了么
