### ISSUE TITLE
popover内嵌select组件,点击popover空白区域select下拉框不会消失

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#3121]
popover内嵌select组件,点击popover空白区域select下拉框不会消失

### Reproduction Link
http://jsfiddle.net/2p1gom7n/

**Comment by Tronsfey** [comment]
Came across the same issue :)

**Comment by amnsss** [comment]
Came across the same issue :)

**Comment by amnsss** [comment]
这个有啥快速的hack办法吗

**Comment by jack-liyou** [comment]
Came across the same issue :)

**Comment by Leopoldthecoder** [comment]
Fixed in #3451
