### ISSUE TITLE
incorrect behavior in input-number component

### ISSUE THREAD

**Issue by sahand12** [ElemeFE/element#3122]
in increase and decrease methods of the component we want to update 'currentValue' of the component but the code instead is updating 'value' prop. 

`increase () {
    ...
    const newValue = this.value || 0;   // this is a wrong, it must be this.currentValue
    ...
}`

the same is true for decrease() method as well

in line 160 and 167 

### ElementUI version
1.2.1

### OS/Browers version
macOS/Chrome 56

### Steps to reproduce
just create a <el-input-number> component and use it you will see that it does not work.

**Comment by Leopoldthecoder** [comment]
Are you encountering any bug of InputNumber? You could reproduce it [here](http://jsfiddle.net/leopoldthecuber/xh9uLxjj/) if you are.

**Comment by sahand12** [comment]
if you don't include the `value` prop or  equally `v-model` on the <el-input-number> component it would not work correctly. see it for yourself.
http://jsfiddle.net/swt0q9vm/

**Comment by Leopoldthecoder** [comment]
All form component should bind `v-model` or at least `value`. Not just InputNumber.
