### ISSUE TITLE
升级到1.2.1UI和vue2.2.1时，报hasOwn is not a function

### ISSUE THREAD

**Issue by loyin** [ElemeFE/element#3123]
1、升级后报hasOwn is not a function，且调用this.$notify.error时报 hasOwn is not a function。
2、打开对话窗口却没有遮罩层。确认窗口也是无遮罩层。

**Comment by hopkinson** [comment]
@loyin 请问你解决了吗 我也遇到了

**Comment by baiyaaaaa** [comment]
#3097 fixed
