### ISSUE TITLE
Bug? Datepicker. If firstDayOfWeek is not 7, picker highlight wrong date

### ISSUE THREAD

**Issue by grebennikovf** [ElemeFE/element#3126]
Hello!
ElementUI version
1.2.1
Vue version
2.1.8

Problem in datepicker with type=daterange (only).

I set the "firstDayOfWeek" as 1 (monday) and find a problem.
Datepicker highlights days with 1 day offset (if  firstDayOfWeek=2, offset in datepicker grows to 2 days etc.).
But date in input is correct, problem is in visual part of datepicker only.

Is this a my local problem (config and bad code) or bug?

**Screenshot:**
https://yadi.sk/i/HEOJLlj73EkXtg

**My code:**
```
<el-date-picker
                        v-model="form.period"
                        type="daterange"
                        :picker-options="dateRangeOptions1"
                        placeholder="Pick a day">
                </el-date-picker>
```

```
data() {
            return {
                dateRangeOptions1: {
                    firstDayOfWeek: 1,
                },
         }
}
```

**Comment by QingWei-Li** [comment]
It's working for me.

![image](https://cloud.githubusercontent.com/assets/7565692/23396557/54d0003e-fdcf-11e6-928f-cd9d4bdfdd10.png)


http://jsfiddle.net/cinwell_li/0ug0ome5/1/

**Comment by woozyking** [comment]
This can be reproduced if supplied period contains string values which cannot be properly instantiated by `new Date`, for example `new Date('2017-03-01')` would actually yield `Tue Feb 28 2017 19:00:00 GMT-0500 (EST)` (depends on locale, and timezone, etc, but you get the idea); while `new Date('2017-03-01 00:00:00')` would yield `Wed Mar 01 2017 00:00:00 GMT-0500 (EST)`

**Comment by dingsydney** [comment]
I also can reproduce the issue. 
In my case, I set firstDayOfWeek to 3.
if I navigate month to current month, it will select a date different what i click.  that's a week after.
If I navigate to other month, it works properly.
