### ISSUE TITLE
table 组件 show-overflow-tooltip 在safari无效的问题

### ISSUE THREAD

**Issue by liujinyang1994** [ElemeFE/element#3128]
[#2198](https://github.com/ElemeFE/element/issues/2198)在这个issue中，并没有解决。所以我选择重新开一个issue

这个是在Safari的效果
<img width="315" alt="wx20170228-115703 2x" src="https://cloud.githubusercontent.com/assets/15340367/23391071/32793f2c-fdad-11e6-92f5-c43bc67d227d.png">

这个是在Chrome的效果
<img width="315" alt="wx20170228-115703 2x" src="https://cloud.githubusercontent.com/assets/15340367/23391068/2a7dadf8-fdad-11e6-90ba-92f19372b96c.png">

我使用的是 "element-ui": "^1.2.0"

**Comment by reverland** [comment]
贵系统的迷之浏览器

**Comment by liujinyang1994** [comment]
那最后是解决了吗？ @reverland

**Comment by reverland** [comment]
@liujinyang1994 不知道，当时好像修复了。之后没看到这问题。。

**Comment by MIKUScallion** [comment]
The latest version still have this problem. 
In macOS Safari.

**Comment by liujinyang1994** [comment]
@MIKUScallion Such being the case

**Comment by MIKUScallion** [comment]
I think this way will solve it.

Fix table show-overflow-tooltip in safari.  https://github.com/MIKUScallion/element/commit/63e73d6b4ac5179c1e80301d7c3ee17fb192cb11

**Comment by renxia** [comment]
Method of setting width is feasible.
I tried for a long time, There's no better way.

**Comment by renxia** [comment]
@QingWei-Li @reverland @Leopoldthecoder 
不尽快考虑一下这个方案吗，难道你们de产品经理用 Safari 的还没提出意见嘛...  😂

**Comment by reverland** [comment]
我不写前端了。。。＝ ＝

但不知道element怎么回事

**Comment by liujinyang1994** [comment]
这个我真的惊呆了... 这问题看来不打算解决了

**Comment by renxia** [comment]
这个问题比较怪，在某些简单布局情况下，Safari 是没问题的。复杂布局情况下，很容易出现。
解决方法也很简单，只需要给每个 td 加上 col 的宽度就行。
再没人理我要推送 pr 了……

**Comment by Leopoldthecoder** [comment]
来 PR 吧，现在几个人都在忙其他项目。

**Comment by MIKUScallion** [comment]
@renxia, 可以参考我的解决方案。有考虑异步数据和性能问题。目前还遇到的问题是，无法应对用户改变浏览器窗口的情况。

**Comment by renxia** [comment]
@MIKUScallion 
`show-overflow-tooltip` 的实现逻辑因前面的提议(#3478) 已改变，你的修改不再适用
这个问题只需要简单的同步 col 的宽度就行了

**Comment by Leopoldthecoder** [comment]
Fixed in #4157

**Comment by heyunjiang** [comment]
在 safari 依然存在兼容问题，内容长度超出不会有省略。
![image](https://user-images.githubusercontent.com/15085454/81380521-a70e8280-913d-11ea-8ea6-2e0fc6788558.png)

问题现象：在 safari 某一览内容长度过长，使用 show-overflow-tooltip + width 属性，不会出现省略，内容会被撑开；在 chrome 表现没有问题。
elementui 版本：2.6.11.
问题分析：原因是在 safari 下，div.cell 及其父 td 节点宽度，是由设置在 col 上的 width 属性决定，2浏览器的表现，在 show-overflow-tooltip + width 条件下不同
