### ISSUE TITLE
能不能增加一个treetable的组件

### ISSUE THREAD

**Issue by joywen** [ElemeFE/element#3129]
在设置tree是常会附带些说明，还有其他内容，单纯的tree还不够需要treetable可以再行中扩展，列如做权限功能，tree会分配模块，模块里面的具体权限还会使用checkbox,这就需要扩展内容来包这些checkbox

**Comment by rdluck** [comment]
我也有同样的需求，系统可以添加这样的一个组件

**Comment by 646423353** [comment]
我也有同样的需求

**Comment by Leopoldthecoder** [comment]
#1955
