### ISSUE TITLE
table filter 位置偏移

### ISSUE THREAD

**Issue by 214132049** [ElemeFE/element#3132]
### ElementUI version

1.1.6
### OS/Browers version

window7  chrome56
macOs  chrome56
### Vue version

2.1.6
### Reproduction Link

![image](https://cloud.githubusercontent.com/assets/13826913/23393731/da893bb0-fdbf-11e6-8cc0-f67ebe347031.png)

### Steps to reproduce
如图过滤框位置偏移，没有手动改变浏览器窗口大小，有时位置正确，错误概览40%
### What is Expected?
位置正确

**Comment by liril-net** [comment]
Link的位置光放了图

**Comment by 214132049** [comment]
没有Link，放错地方了

**Comment by 214132049** [comment]
@liril-net 通过调试发现位置错误是因为点击展开popper的区域不一样。在popper.js文件中构造函数Popper获得的reference实参不同，如果点击三角reference的值是`<span class="el-table__column-filter-trigger"></span>`;点击除三角之外的地方reference的值是`<th class="el-table_1_column_2 is-leaf"></th>`;因为reference的值不同，导致在`Popper.prototype._getOffsets = function (popper, reference, placement) {{....}`函数中计算popperOffsets.left出现错误。

**Comment by 214132049** [comment]
发现是table-header.js的handleHeaderClick函数问题，column.filters && !column.sortable为真的话，执行this.handleFilterClick(event, column); 但是这里的event是handleHeaderClick的event, 导致filterPanel.cell的值是th，从而导致构造函数Popper实参reference值错误，popper位置错误。

**Comment by arronf2e** [comment]
我也是，有解吗-，-

**Comment by ultraN** [comment]
同样有这个问题，请问怎么解决？

**Comment by ultraN** [comment]
![image](https://cloud.githubusercontent.com/assets/3374628/24437852/461977f6-148f-11e7-822c-3ddc9a6ac021.png)

**Comment by cody1991** [comment]
我也是，请问这个有解决方案吗

**Comment by Leopoldthecoder** [comment]
Please provide a demo.

**Comment by cody1991** [comment]
我现在用了另外一个方法，看了 @214132049 看了源码后的看法，就是让 th 里面的 .cell 撑满整个 th

`
.el-table th {
  padding: 0;
}

.el-table th .cell {
  line-height: 50px;
  height: 50px;
  margin: 0;
  padding: 0 18px;
}`

@arronf2e 看看能不能解决？

当然问题的源头还是要改源码了。。

**Comment by wind928** [comment]
@Leopoldthecoder 如果没点在filter的箭头上，而是点在header上，filter-panel就会错位。官网例子上也可以重现这个问题，点在箭头上和点在header上位置会不同。

一旦popover展开过一次位置就不会再变了，所以要重复尝试的话需要刷新。

**Comment by FezVrasta** [comment]
The bug with Popper.js and tables has been fixed in 1.11.0

**Comment by furybean** [comment]
没有重现案例，做关闭处理。
