### ISSUE TITLE
Carousel 动态产生，第一页什么都没有显示

### ISSUE THREAD

**Issue by alvin198761** [ElemeFE/element#3134]
```html
 <el-carousel :autoplay="false" ref="cardPane">
    <el-carousel-item v-for="card in menus" :name="card.id">
      <div class="app-grid">
        <ul id="appItemUL">
          <AppButton v-for="app in card.apps" :app="app"></AppButton>
        </ul>
      </div>
    </el-carousel-item>
  </el-carousel>
```

上面是问题代码，问题是这样这样：
我动态循环产生页面，然后动态给页面的控件放置按钮，Carousel 默认选中的是第一页，
却没有显示任何内容，我翻到第二页，再返回来，数据就显示了。
我通过调试页面，看到的结果是，所有的 item 都是 dispay:none.
我能确认数据都有了，元素也都加进群了，就是默认什么都显示。
我试了好几种方式，还是不能显示，有点郁闷了，望大神替我解答一下。

**Comment by alvin198761** [comment]
追加环境信息：
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vuex": "^2.1.2",
    "element-ui": "^1.1.6"

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by alvin198761** [comment]
项目地址:
https://github.com/alvin198761/html_js/tree/master/vue_desktop
由于我的app 都是从后端获取的，如果使用前端死数据直接循环，是没有问题的，我说的问题
在 src/components/layout/ContentPanel.vue 下，

**Comment by alvin198761** [comment]
我将版本升级为最新版本 1.2.2，该问题依然存在，希望能解决一下

**Comment by QingWei-Li** [comment]
请提供 demo

**Comment by alvin198761** [comment]
demo 地址 ：https://github.com/alvin198761/html_js/tree/master/vue_desktop 
由于我的app 都是从后端获取的，如果使用前端死数据直接循环，是没有问题的，我说的问题
在 src/components/layout/ContentPanel.vue 下，
项目用的模拟数据， 下载以后 你 npm install ， npm run start  就可以 起来，
浏览器自动打开， 问题页面  src/components/layout/ContentPanel.vue
模拟数据： /mock/fisheye ，数据获取在 src/store/module/fisheye.js
这是一个简单的例子了，都是独立的，你只需要查看这几个地方就可以了，

**Comment by Leopoldthecoder** [comment]
Fixed in #3159
