### ISSUE TITLE
当使用动态路由时，default-active可能不会生效

### ISSUE THREAD

**Issue by xiaoguangma** [ElemeFE/element#3135]
### What is Expected?
当使用动态路由时，default-active不生效
### What is actually happening?
el-menu-item中index="user"   路由中path="/user/:id"  default-active="/user/123"
这时default-active并不能匹配index="user"的菜单

建议el-menu-item能否增加一个参数用来存储路由中的path="/user/:id"  如果设置了此参数default-active和此参数匹配来选中路由

小白一枚，如有不妥欢迎沟通

**Comment by mayaa6** [comment]
可以自己根据`/user/:id`造`/usr`传入el-menu-item中

**Comment by xiaoguangma** [comment]
@mayaa6   感谢回答，但是没看懂啥意思，可以详细描述下么

**Comment by The-Emperor1** [comment]
使用动态路由时，default-active应该也是动态的，但是无论使用computed还是直接:default-active="$route.path"都无效。

**Comment by cdll** [comment]
same issue here

**Comment by 1TCAN** [comment]
same issue here
