### ISSUE TITLE
dialog modal layer disappear with vue 2.2.1 

### ISSUE THREAD

**Issue by Acathur** [ElemeFE/element#3136]
vue 2.2.1
element-ui 1.2.1

**Comment by Leopoldthecoder** [comment]
Will be fixed in 1.2.2

**Comment by transtone** [comment]
not fixed!

**Comment by Leopoldthecoder** [comment]
@transtone I'm sure it's fixed since version 1.2.2

**Comment by pz25925** [comment]
@Leopoldthecoder  happened aigin

**Comment by pz25925** [comment]
@Leopoldthecoder  Happen again with version 1.2.3

**Comment by pz25925** [comment]
@Leopoldthecoder  not fixed!!!!!!!!!!!!!!!!!!!!

1.2.2 and 1.2.3

**Comment by Leopoldthecoder** [comment]
@transtone 试试在 `el-dialog` 标签上加 `:modal-append-to-body="false"`

**Comment by Leopoldthecoder** [comment]
@pz25925 http://jsfiddle.net/leopoldthecuber/4fxfq4km/

**Comment by pz25925** [comment]
tks.  it work

**Comment by trancelover** [comment]
如果你的 dialog 包含在一个  position:relative/absolute 的父层里，
那么 即使它的z-index 比 追加在 body 底部 的 v-modal的z-index 高，

依然会被后面的层挡住。因为这个最后追加的 v-modal 层的z-index 比这个父层的z-index 要高。

```
<div style="position:relative; z-index:99"><el-dialog  > 虽然我的z-index=2001 我仍将被遮挡 </el-dialog></div>
<div class="v-modal" style="z-index:2000"></div>
</body>
```

**Comment by jinkunaier** [comment]
@trancelover 我使用vue2.5.10 ,element-ui 2.0.8 依然还有这个问题。dialog 包含在一个 position:不是static的父层里都会出现这种情况
