### ISSUE TITLE
在单页应用中使用Tree，跳转后内存没有释放

### ISSUE THREAD

**Issue by vincent19376** [ElemeFE/element#3137]
### ElementUI version
1.2.1

### OS/Browers version
Chrome v56

### Vue version
2.1.10

### Reproduction Link
https://github.com/vincent19376/element-starter

### Steps to reproduce
单页应用，在其中一页加载一个较大的多层树，然后跳转到另一张页面，反复几次，内存占用会越来越多。测试显示，加载一个400多节点的树，每次可能要泄露80M内存。

**Comment by xingchch** [comment]
@vincent19376 这个问题你解决了吗？我测试在elementUI 1.3.7/ vue 2.3.4/ router 2.7.0上还是有该问题。
你是如何规避的？

**Comment by vincent19376** [comment]
@xingchch 没有解决，自己重新写了一个树组件。
