### ISSUE TITLE
组件交互文档有NavMenu 导航菜单简洁侧栏但是API说明没有

### ISSUE THREAD

**Issue by BryantWangGitHub** [ElemeFE/element#3139]
### ElementUI version

  1.2.1
### Vue version

2.0
### What is Expected?
    您官网组件交互文档有NavMenu 导航菜单“简洁侧栏”（可以通过点击隐藏导航栏），但是组件API说明没有对应说明
   请问已经开发了没同步API还是此功能还在开发中,感谢

**Comment by Leopoldthecoder** [comment]
尚未开发。
