### ISSUE TITLE
NavMenu的select事件中怎么获取到选中项的文本值？

### ISSUE THREAD

**Issue by saint3347** [ElemeFE/element#314]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
win10/Chrome 53

### Vue version
2.0.0-rc.8

### Reproduction Link

文档上的一个小问题：
![image](https://cloud.githubusercontent.com/assets/7347133/19256321/6ad4e868-8f98-11e6-8ede-d7fefb843061.png)

另外，我在select事件中想拿到选中项的文本值怎么取？
![image](https://cloud.githubusercontent.com/assets/7347133/19256337/95feae84-8f98-11e6-9eda-b0b67c244be9.png)
比如我想取到“客户管理”，拿到值放到面包屑的数组中去

el-menu-item能不能做成动态可配置的？像select选择器的option可以用data赋值一样

**Comment by baiyaaaaa** [comment]
el-menu-item 内容可能不仅是纯文本的，如果你想获取里面的内容可以通过 Menu 组件的实例去访问，Menu 组件实例中维护了一个包含所有的菜单项实例的列表

**Comment by furybean** [comment]
@baiyaaaaa 可以考虑在 select 事件中，把点击的 MenuItem 组件作为第二个参数。

**Comment by acelan86** [comment]
第二个参数需求还有类似radio-group，select等，把vm返回

**Comment by a741841403** [comment]
@furybean 同意。

**Comment by hktalent** [comment]
@saint3347 
document.activeElement.innerText
