### ISSUE TITLE
[breadcrumb] 建议增加无跳转链接时的样式区分

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#3140]
如题，当前 `breadcrumb` 比较简单，无论是否配置了 `to` 或 `repllace` 参数，只有最后一个是灰色，前面的鼠标样式都是手型可点击

一般来说`手型`鼠标样式都应该代表可点击的元素。不可点击的元素应该是正常的 `text` 样式才对。

所以当未设置 `to` 和 `replace` 属性时，应该默认添加一个样式，并定义它与最后一个样式一样更好。

一个兼容性的示例：

http://jsfiddle.net/9bkr82ga/

**Comment by Leopoldthecoder** [comment]
欢迎 PR

**Comment by Leopoldthecoder** [comment]
最新版已做区分。
