### ISSUE TITLE
对话框弹出没有遮罩层？

### ISSUE THREAD

**Issue by shookgao** [ElemeFE/element#3142]
我想问问我用最新的 ElementUI 1.2.1 创建的对话框怎么没有遮罩层，项目用的是 ElementUI 快速上手里面的通用项目模板，使用的例子就是对话框里面的第一个例子，运行后点击弹出对话框，但是没有遮罩！

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/pull/3097
