### ISSUE TITLE
BUG:slider组件在设置show-input 属性后,给定初始值， slider滑块初始长度有问题

### ISSUE THREAD

**Issue by pdap** [ElemeFE/element#3146]
### ElementUI version
1.2.1

### OS/Browers version
macOS/Chrome 53

### Vue version
2.1.10

### Reproduction Link
[http://jsfiddle.net/z6r2vymm/](http://jsfiddle.net/z6r2vymm/)

### Steps to reproduce
官网demo slider组件在设置show-input 属性后slider滑块初始长度有问题
第一步访问官网demo:[http://jsfiddle.net/z6r2vymm/](http://jsfiddle.net/z6r2vymm/)
第二步按照下面的代码设置组件属性和初始值
点击run运行，结果滑块位置为0；
`<el-slider v-model="value6" :min="0.01" :max="1" :step="0.01" show-input>
    </el-slider>`
`    data() {
      return {
        value6: 0.5
      }
    }`
### What is Expected?
滑块位置应该在中间
### What is actually happening?
实际上滑块位置却处在0刻度处

**Comment by Leopoldthecoder** [comment]
Fixed in #3281
