### ISSUE TITLE
组件传参格式的问题

### ISSUE THREAD

**Issue by suzi404** [ElemeFE/element#3149]
在给组件传参的时候，参数的格式与组件指定的格式不同时会报错，虽然不影响运行，但是看着就不舒服。你们内部应该做了这种判断，但是为什么还是抛出错误来？
比如说，navMenu组件的router指定的参数格式是boolean，在写的时候我如果这样写就报错
![image](https://cloud.githubusercontent.com/assets/16069823/23400554/614c46be-fddf-11e6-8470-8caeecc4d9be.png)
提示参数应该是boolean，而不应是字符串。只能改成动态的变量才不报错
![image](https://cloud.githubusercontent.com/assets/16069823/23400885/853a00d8-fde0-11e6-80d7-4e9b8d19a03c.png)

还有些参数假设是要数字，直接这样写就是字符串‘1234’之类的，那就会运行出错。

**Comment by lincenying** [comment]
组件里限制了props的类型, 那么你就只能照着类型传.
