### ISSUE TITLE
loading 不兼容IE9浏览器

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/element#315]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
win7/IE 9 

### Vue version
2.0.0

**Comment by Leopoldthecoder** [comment]
手边没有 win7/IE 9，麻烦详细描述一下现象，如果有报错的话请贴一下错误信息。

**Comment by lwfyiwei** [comment]
我是用IE11仿真IE9
element-ui\packages\loading\src\spinner.js 代码里面使用了
`Element.classList`
我查了下MDN，发现支持IE 10+
[https://developer.mozilla.org/en-US/docs/Web/API/Element/classList](url)

以上内容希望有所帮助

**Comment by lwfyiwei** [comment]
错误截图
![default](https://cloud.githubusercontent.com/assets/22360070/19260827/6517905c-8fbf-11e6-8d72-c2b6886cbe4f.PNG)

**Comment by Leopoldthecoder** [comment]
fixed in #328

**Comment by lwfyiwei** [comment]
Dialog 依赖的 vue-popup也是同样的问题，麻烦也兼容下IE9，多谢

**Comment by Leopoldthecoder** [comment]
vue-popup 也已经升级，Element 的下个版本会使用最新的 vue-popup。

**Comment by bammoo** [comment]
Loading 用了 css animation 在 ie9 下转动失效

**Comment by Leopoldthecoder** [comment]
@bammoo 在 IE 9 下只保证功能，效果可以降级。

**Comment by furybean** [comment]
@Leopoldthecoder 这个功能其实在 IE9 下是失效的，用户并不知道在加载。

**Comment by Leopoldthecoder** [comment]
@furybean 看了一下，在 IE9 下是一个静止的遮罩，是有问题。后面跟据 UED 的新视觉来吧。
