### ISSUE TITLE
checkbox和radio选中动画是不是时间太长了

### ISSUE THREAD

**Issue by FutureElement** [ElemeFE/element#3155]
checkbox和radio选中动画是不是时间太长了，操作不流畅，很不舒服，希望优化下

**Comment by jfb** [comment]
嗯，总感觉卡卡的样子

**Comment by eeeeeLin** [comment]
可以自行调节 timing function 或者 delay time, 动画本身就很众口难调 🤔

**Comment by FutureElement** [comment]
没有看到文档里有这些属性配置呀

**Comment by eeeeeLin** [comment]
这种动画接口很难做吧，比如有些人喜欢用贝塞尔，有些人只喜欢 ease，个人觉得还是自己写样式直接覆盖比较好

**Comment by Leopoldthecoder** [comment]
@eeeeeLin +1

**Comment by FutureElement** [comment]
感谢 @eeeeeLin
