### ISSUE TITLE
按需引入，组件名是怎么找的，往往不知道怎么添加

### ISSUE THREAD

**Issue by BusyHe** [ElemeFE/element#3160]
例如加添面包屑，
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
需要添加两个

**Comment by lincenying** [comment]
看官方的按需引用
http://element.eleme.io/#/zh-CN/component/quickstart

**Comment by BusyHe** [comment]
@lincenying 官方也没说啊
你看
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
这个官方有提到吗？每当报错我才知道还有没添加的组件

**Comment by Leopoldthecoder** [comment]
![image](https://cloud.githubusercontent.com/assets/10095631/23491051/dc15da6a-ff36-11e6-8804-0f404920a6ca.png)
@BusyHe 没太理解你的意思，你楼上链接里的这段说明似乎不符合你的期望？

**Comment by BusyHe** [comment]
@Leopoldthecoder 这个是引入方法，按文档的说我只需要use(Breadcrumb),那BreadcrumbItem我怎么知道还得引入这个，汗。。。

**Comment by Leopoldthecoder** [comment]
这是当然的，既然 `BreadcrumbItem` 是一个自定义标签，那么不引入自然会报错。

**Comment by BusyHe** [comment]
对，文档是不是要说明，或者给出来是不是好一点。

**Comment by lincenying** [comment]
这还要文档给??? 你用了什么el-xxx标签你会不知道吗?
把el-去了, 把后面的改成首字母大写的驼峰, 然后 import {Xxxx} from 'element-ui'
