### ISSUE TITLE
carousel 动态创建，第一页不显示的解决方案

### ISSUE THREAD

**Issue by alvin198761** [ElemeFE/element#3161]
问题已经自行解决，
提的问题被关，我也是醉了，因为这个问题需要几个东西配合才会出bug ,我还特地给了项目地址，
我自己仔细看了一下 carousel的实现代码。
从代码上面看，没有问题，也做了很多测试，证明动态产生的数据是可以显示的，但是我的上面确实不能显示，
我的认为问题的点就那么几个：
1.我的数据是从后台获取的，
2.我的版本不够新，
3.从页面调试来看，页面内容已经产生，但是 所有的item 都是 display:none ，是不是什么属性没有设置
4.动态产生的需要某种消息机制激活一下，重绘页面
对应的尝试
1.我尝试改成前台数据，是可以的，
2.我尝试更新到1.2.2版本，不行
3.我尝试，设置 activeItem ,activeIndex ,或者强制将第一页display 设置为block,各种方式，都不行。
  同时我在 created , mouted ,updated 里面调用 resetItemPosition setActiveItem  也不行
4.我把底下的indicator-position 放开，只要选中底下的任何不是第一个的项，就可以显示了，而且后面操作全部正常。
  在开发模式下，我先把浏览器打开，只要做一下修改，页面自动编译重绘，也会正常显示
我在 mouted 的里面执行了一个延迟的操作，里面就是 setActiveItem(1)，发现居然可以了，
  经过我一番调整，就加了这么一个代码。问题解决。

   updated: function () {
     let _this = this;
      let timer = setInterval(function () {
        _this.$refs.cardPane.resetItemPosition();
        clearInterval(timer)
      }, 100)

carousel.js 中有对 items 的watch 代码，但是 只有一句：  this.setActiveItem(0);
我尝试在created mouted update 使用  setActiveItem(0); 并没有效果，应该是没有触发消息机制。
改成setActiveItem（1）是可以的 ， resetItemPosition()也可以。
不多说。问题解决就好。希望控件能更完善

---以下是我的页面的代码

<template>
  <div id="contentPane" class="contentPane">
    <el-carousel :autoplay="false" ref="cardPane" indicator-position="none">
      <el-carousel-item v-for="card in menus">
        <div class="app-grid">
          <ul>
            <AppButton v-for="app in card.apps" :app="app"></AppButton>
          </ul>
        </div>
      </el-carousel-item>
    </el-carousel>
  </div>
</template>
<script>
  import {mapGetters} from 'vuex';
  import AppButton from './AppButton.vue';
  export default{
    data: function () {
      return {}
    },
    computed: {
      ...mapGetters({
        menus: 'fisheye/_menus'
      })
    },
    components: {
      AppButton
    },
    methods: {},
    mounted: function () {
      this.$store.commit('content/initComponent', this.$refs.cardPane)
    },
//解决办法代码
    updated: function () {
     let _this = this;
      let timer = setInterval(function () {
        _this.$refs.cardPane.resetItemPosition();
        clearInterval(timer)
      }, 100)
    }
  }

**Comment by alvin198761** [comment]
关闭了

**Comment by Leopoldthecoder** [comment]
我在关闭 #3134 时已经回复「Fixed in #3159」。

**Comment by JanlyH** [comment]
@alvin198761 我也碰到和你一样的问题，用了你的方法还是不行，第一页还是不会展示，要点击或者组件自动跳到下一页时才会展示，而且升级到1.2.3问题还是在

**Comment by Leopoldthecoder** [comment]
@JanlyH 等下个版本。

**Comment by alvin198761** [comment]
你把时间拉长点试试，比如你搞个 3000，这是个重绘的问题，我的数据量比较小，所以只需要100毫秒，如果在网络不好的环境下，可能需要改下时间，说到底，这是个蹩脚的解决办法，最好的办法应该是在items 发生变化以后，然后再 repaint 浏览器，

**Comment by hawtim** [comment]
@alvin198761 感谢这么细致的回答，刚好用上了，多谢

**Comment by GaoYuanOnline** [comment]
万分感谢，这么蹩脚的问题真的不好找

**Comment by alvin198761** [comment]
我已经在这个坑上面建了很多东西了，我相信饿了么也想不到我已经把他的东西做成web操作系统了
你们过来看看，我就是在做这个玩儿上面遇到坑的
https://github.com/alvin198761/web-os

**Comment by Kelichao** [comment]
确实可以解决，我并不是以组件形式引入的，通过children然后重置页码发到重绘，注意，这边必须要加定时器才能生效。
setTimeout(() => {
                                        this.$children[1].resetItemPosition();
                                    },100)
