### ISSUE TITLE
如何在tree组件更新之后刷新树？

### ISSUE THREAD

**Issue by SnuggleE** [ElemeFE/element#3162]
在一个单页面应用上，对树的结构进行编辑，添加节点和更改节点名称，需要在添加之后树也可以随之更新，没有发现有关可以实现的接口。

**Comment by johntostring** [comment]
正常情况下，model 变化会触发更新视图，不知道你是什么具体情况。

我在做添加节点时遇到点问题#3156，目前还没有回复。。。

**Comment by SnuggleE** [comment]
我是通过ajax获取树的结构，初始状态传参为0获取根节点，获取到一个数组作为节点内容，点击展开某个节点，再根据该节点的值获取下一级节点。model打印出来是空的。感觉不可思议。https://github.com/johntostring

**Comment by vincent19376** [comment]
是可以获取的，你可以检查下代码，或者试一下this.$forceUpdate
