### ISSUE TITLE
关于 input 如何绑定enter事件

### ISSUE THREAD

**Issue by radicalviva** [ElemeFE/element#3165]
尝试了以下如下代码
```
      <el-input
        class="mobile"
        v-model="mobile"
        placeholder="输入手机号查询"
        @keyup.enter="foo">
      </el-input>
```
无效，按 回车 无效，能有办法生效吗?在guide中的input介绍中没有看到

**Comment by taixw2** [comment]
他们的input组件没有实现keyup事件，

[https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue](https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue)

**Comment by Leopoldthecoder** [comment]
提 issue 前请仔细阅读 FAQ
