### ISSUE TITLE
官网文档链接点击有时候没反应

### ISSUE THREAD

**Issue by accpdyk** [ElemeFE/element#3166]
http://element.eleme.io/1.2/#/en-US/component/button
进如页面，随便点击链接前3下是正常的，在点击链接地址变化，内容不变。

大家都不看文档吗，难道是我浏览器的问题？

谷歌浏览器版本 56.0.2924.87 (64-bit)

**Comment by roybein** [comment]
仍然有问题

**Comment by Leopoldthecoder** [comment]
@roybein 清一下缓存
