### ISSUE TITLE
date-picker控件选择日期后数据绑定异常

### ISSUE THREAD

**Issue by xiaoguangma** [ElemeFE/element#3167]
### What is Expected?
选择日期后date绑定 input显示所选日期
### What is actually happening?
选择日期后date绑定 但input未显示所选日期

其他input控件无此问题
代码链接http://jsfiddle.net/nfgwjcgz/

不知道是否使用方式不当，因为有时候search对象中不希望写很多属性，希望在用的时候在装进去
```
    <el-date-picker
      v-model="search.date"
      type="date"
      placeholder="选择日期">
    </el-date-picker>

    //失败
    data() {
      return {
        search:{}
      };
    }

    //成功
    data() {
      return {
        search:{
          date: null
        }
      };
    }
```

**Comment by PanJiaChen** [comment]
这是vue的机制
https://cn.vuejs.org/v2/guide/reactivity.html

**Comment by Leopoldthecoder** [comment]
@PanJiaChen +1
