### ISSUE TITLE
建议select选择器增加grid模式

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#3169]
目前select选择器的`<slot>`只能自定义每一个选项，如果希望下拉框显示一个完整的grid并没有办法。

虽然可以采用`Popover`实现，但是支持多选什么的又是个问题，建议select组件内直接支持该模式

类似这样的
![image](https://cloud.githubusercontent.com/assets/3765379/23449954/955e08b6-fe93-11e6-928d-9cf1099fe0f2.png)

**Comment by Leopoldthecoder** [comment]
无计划。
