### ISSUE TITLE
input复合型输入框显示异常

### ISSUE THREAD

**Issue by mohong** [ElemeFE/element#3170]
![截图](http://ob9qd20l4.bkt.clouddn.com/input2.jpg)

[文档](http://element.eleme.io/#/zh-CN/component/input#fu-he-xing-shu-ru-kuang)中复合型数据第三个使用时不显示左边的文字，只显示小三角，可下拉，选择完依然不显示文字，控制台无报错信息。

**Comment by Leopoldthecoder** [comment]
参考 #2086

**Comment by mohong** [comment]
谢谢 @Leopoldthecoder
