### ISSUE TITLE
el-tooltip bug

### ISSUE THREAD

**Issue by HadiChen** [ElemeFE/element#3173]
### ElementUI version

1.2.3
### OS/Browers version
macOS/Chrome 53
### Vue version

2.2.1

### Steps to reproduce
基于服务端渲染，刷新页面后在浏览器控制台报错，错误来源于Vue

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/11555571/23451729/2b9a94ae-fe9c-11e6-849d-117dedca2ec4.png)

![image](https://cloud.githubusercontent.com/assets/11555571/23451807/806ba27a-fe9c-11e6-9aa8-1216e7a0d5f6.png)

**Comment by chuangker** [comment]
碰巧，我也遇到这个问题。顺便贴一下吧

### ElementUI version

1.2.3

### OS/Browers version

macOS/Chrome 56

### Vue version

2.1.8

### Steps to reproduce

在开始用 1.2.1 的时候遇到这个错 [#3004](https://github.com/ElemeFE/element/issues/3004)
后来升级 1.2.2 的时候遇到这个错 [#3152](https://github.com/ElemeFE/element/issues/3152)
最后升级到 1.2.3，服务端渲染不报错但 Chrome 控制台开始报错

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/7939566/23502721/bdbc6ef2-ff73-11e6-907f-55d2d997e1cb.png)

同样定位到如下代码
```
// Cannot read property 'toLowerCase' of undefined
function emptyNodeAt (elm) {
  return new VNode(nodeOps.tagName(elm).toLowerCase(), {}, [], undefined, elm)
}
```

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/ElemeFE/element/pull/3214

这回彻底修掉了

**Comment by psychokiller666** [comment]
刚刚遇到了同样的错误

**Comment by chuangker** [comment]
啥时候能发布呀

**Comment by Leopoldthecoder** [comment]
本周
