### ISSUE TITLE
datepicker组件显示框了里 显示时间的格式可以修改么？

### ISSUE THREAD

**Issue by zhoujiamin** [ElemeFE/element#3174]
### What is Expected?
时间段选择:选择后，显示的方式是 2017-01-02- 2017-01-02，
可以修改为2017-01-02至2017-01-02等其他形式么？？

**Comment by jikkai** [comment]
应该是可以的，分隔符有属性`range-separator`控制，默认值是`-`，改成`至`就能实现你说的这个形式了

**Comment by romoo** [comment]
range-separator 不起作用
http://jsfiddle.net/n9modd8e/

**Comment by Leopoldthecoder** [comment]
@romoo 是 bug

**Comment by Leopoldthecoder** [comment]
Fixed in #3378
