### ISSUE TITLE
Pagination 分页 中的 layout="total" 失效

### ISSUE THREAD

**Issue by wisewrong** [ElemeFE/element#3175]
更新到 1.2.1 之后，在 layout 中添加 "total" 属性，并不能显示总条数。控制台也会报错：
![default](https://cloud.githubusercontent.com/assets/23471962/23452157/352cbe00-fe9e-11e6-942b-f64d71b0b876.png)

**Comment by Leopoldthecoder** [comment]
升到 1.2.3 即可。
