### ISSUE TITLE
upload 组件手动上传不可用

### ISSUE THREAD

**Issue by jinjinwa** [ElemeFE/element#3176]
![image](https://cloud.githubusercontent.com/assets/12455937/23455380/58e5164c-feaa-11e6-8438-d711bcb85e4b.png)

官方给出的demo，直接点击在线运行，在jsfiddle中报错，手动添加了submitUpload 方法，this.$refs.upload.submit()后，变的可以运行。

但是复制到项目中，dom都无法正常显示（设置了slot='trigger'的按钮不显示），且设置auto-upload无效。

slot 的定义，不明白，看了源码后，也是懵逼。且部分属性失效。

是官方的bug，还是使用的时候有什么关键地方官方没贴出代码？

以上：希望官方给出一个可运行的，手动上传demo实例

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/cinwell_li/hs2rsv8p/

**Comment by jinjinwa** [comment]
谢谢，这个是选择完文件，自动上传。

**Comment by Leopoldthecoder** [comment]
贴出你的代码。

**Comment by jinjinwa** [comment]
![image](https://cloud.githubusercontent.com/assets/12455937/23458309/b142a0c8-feb6-11e6-989f-59d0b4268133.png)
完整代码如上，复制的官方demo，渲染结果：
1，选取文件按钮不显示。
2，上传到服务器按钮，点击选取本地文件。
3，设置auto-upload ＝false 失效。选择文件后，自动就上传了。

**Comment by Leopoldthecoder** [comment]
看上去你的 Element 并不是最新版，这些 API 都是 1.2.0 以上才有的。

**Comment by jinjinwa** [comment]
我下午感觉可能是版本的问题，然后升级到了1.2.3 。

**Comment by Leopoldthecoder** [comment]
Upload 本身没有问题：http://jsfiddle.net/y67m1wpo/
确认一下你的版本吧。

**Comment by jinjinwa** [comment]
好的，感谢回复🙏 我npm下载的包，整个项目的package.json中，看到版本是1.2.3，在node_modules中找到element－ui，version显示1.1.6...应该是这个问题了。🙏

**Comment by hasbug** [comment]
官网提供的这个是有问题的：http://jsfiddle.net/api/post/library/pure/

**Comment by jinjinwa** [comment]
目前的upoload控制是否允许多文件上传，是通过配置multiple。但只是在上传服务器的时候，做了限制。想实现选取文件的时候，就做限制，比如设置了不允许多文件以后，想选取更多的文件，会替换第一次选取的文件。

**Comment by weimingxinas** [comment]
请问楼主解决了吗？要怎么手动上传啊

**Comment by HongHaiyang** [comment]
> 通过 slot 你可以传入自定义的上传按钮类型和文字提示。可通过设置limit和on-exceed来限制上传文件的个数和定义超出限制时的行为。可通过设置before-remove来阻止文件移除操作。
文档写着可以通过 slot 来自定义上传按钮类型，但是说明文档里并没有各个 slot 代表的含义啊，例子里只有一个 slot=tip 。我想要用自己的按钮来代替，我看文档是没有加上 slot 就行了，但是我也这么做，页面上出现了 “选择文件” “未选择任何文件的” 字样，这个怎么去掉呢？

**Comment by kid1412621** [comment]
@jinjinwa 上传超限时替换第一个,你实现了吗? 我本来想在 on-exceed 这个勾子里实现的,试了下不行
