### ISSUE TITLE
数字类型输入验证好象有问题

### ISSUE THREAD

**Issue by mapdata** [ElemeFE/element#3179]
如果先输入数字，后面紧跟字符，如：12qqq，好像验证仍能通过。

**Comment by Leopoldthecoder** [comment]
Vue 的机制就是这样，实际此时绑定值已经是个纯数字了。

**Comment by luxueyan** [comment]
体验超级不好，如果限制只能输入两位小数怎么做，自己用正则以后，验证类型成了string 每次编辑传进数字 验证又提示不是string类型

**Comment by cheerylong** [comment]
是因为v-model.number会将输入值强转为number导致，数字类型的验证自己实现吧，自带的很坑

**Comment by jackcooper2015** [comment]
解决方案：
`<el-input type="number" v-model.number="price"></el-input> `， type='number'限制只能输入数字，v-model.number输入的字符串转number,很好的解决了这个问题
