### ISSUE TITLE
时间的这个ui没有写好，非常的不好选择，前面的日期还好，主要是后百的时分秒，体验很差.

### ISSUE THREAD

**Issue by Zhi-Peng** [ElemeFE/element#318]
时间的这个ui没有写好，非常的不好选择，前面的日期还好，主要是后百的时分秒，体验很差，

**Comment by reverland** [comment]
我觉得antd这种还好，虽然有时候会出些莫名的问题

bootstrap-datetimepicker那种交互方式，https://github.com/Eonasdan/bootstrap-datetimepicker。还可以复制黏贴

或者my97那种？，http://www.my97.net/

其他的就没见过了

**Comment by autopanda** [comment]
时分秒框出界到选择器的框了，而且时分秒下拉时间的时候最好把滚动条隐藏了。
平台：Windows10 chrome 53

**Comment by QingWei-Li** [comment]
@autopanda 请给截图

**Comment by autopanda** [comment]
![1](https://cloud.githubusercontent.com/assets/21982034/19442605/7248f43a-94bc-11e6-9d44-54e4385bd53c.png)

**Comment by furybean** [comment]
发布者没有再给出反馈，先关了，如果还是有疑问可以 open。

**Comment by guohuihot** [comment]
my97这种才是好的体验
