### ISSUE TITLE
toggleRowSelection方法求指导

### ISSUE THREAD

**Issue by yeluo0309** [ElemeFE/element#3182]
Table 的多选toggleRowSelection方法，
异步加载数据后，一开始是选中的，但是又马上消失。
想请问下这个现象怎么处理。。

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by yeluo0309** [comment]
谢谢已解决。。

**Comment by xu128523** [comment]
@yeluo0309 目前我也遇见这个问题，能提供一下方法吗

**Comment by yeluo0309** [comment]
@xu128523 我这的问题是，异步处理后返回的数据有问题，然后返回的值把之前的值覆盖了。。。

**Comment by twolun** [comment]
@yeluo0309 你怎么解决的，能提供demo吗，谢谢

**Comment by XZZsr** [comment]
这个应该是数据渲染的问题 ，你可以再数据加载好再执行这段代码！
  this.$store.dispatch('adsCarts/get').then(res=>{ 
       this.tableData.forEach((row) => {
            if(row.status == 1){
                  this.$refs.table.toggleRowSelection(row, true);
             }
       });
  })

**Comment by qilanbei** [comment]
@XZZsr 我就是这样做的  还是设置无效 不知道原因。。。。。

**Comment by XZZsr** [comment]
@qilanbei   那估计还是没渲染出来 你可以打印下this.$refs.table 看是否取到，如果没取到dom应该还没渲染完毕或者其他问题，你可以看下Vue.nextTick()
