### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by panayotov** [ElemeFE/element#3183]
Hi;

I'm using **element** with vue-webpack template;
When developing local it all works, but when I try to build for production, the build is broken from what seems to be dependency of the framework:

I get the error "Uncaught ReferenceError: Invalid left-hand side expression in postfix operation" and the stack trace points that the error comes from **async-validator** package, `~/async-validator/lib/util.js:40`;

Does somebody has the same problem? I tried numerous build options, but the build always fails.

**Comment by baiyaaaaa** [comment]
please provide demo
