### ISSUE TITLE
Can't get example run

### ISSUE THREAD

**Issue by bubnenkoff** [ElemeFE/element#3184]
```
import Vue from 'vue'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
import App from './App.vue'

Vue.use(ElementUI)

new Vue({
  el: '#app',
  render: h => h(App)
})
```
error:
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.e.__esModule.default (index.js:2)
    at t (index.js:1)
    at Object.e.__esModule.default (index.js:2)
    at t (index.js:1)
    at Object.e.__esModule.default (index.js:2)
    at t (index.js:1)
    at Object.e.__esModule.default (index.js:2)
    at t (index.js:1)
    at Object.e.__esModule.default (index.js:2)
    at t (index.js:1)
```

```
"dependencies": {
    "element-ui": "^1.2.3",
    "vue": "^2.1.10"
  }
```

**Comment by QingWei-Li** [comment]
Try it https://github.com/ElementUI/element-starter

**Comment by Batur24** [comment]
I had the same problem. After I removed the `<script src="https://unpkg.com/element-ui/lib/index.js"></script>` in the `index.html`, the error is gone. Hope that helps.

**Comment by dcy** [comment]
Hi! I had the same problem, how to fix this?

**Comment by cosileone** [comment]
To fix this issue just import your javascript file for element UI after importing VueJS

**Comment by dsibaja-dnamyc** [comment]
But in the index file there is no inclusion of the VueJs
`<body>
    <noscript>
      <strong>We're sorry but webtoolcenter-fe doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    
  </body>`

so if you put `<script src="https://unpkg.com/element-ui/lib/index.js"></script>` after 'built files will be auto injected' you will get the error. So i don't know how to solve this.
