### ISSUE TITLE
How to insert "<a>" link within el-menu-item?

### ISSUE THREAD

**Issue by romangit** [ElemeFE/element#3186]
Hi! If we look the [NavMenu Doc](http://element.eleme.io/#/en-US/component/menu), there recommend use `<a>` like  `<el-menu-item index="3"><a href="https://www.ele.me" target="_blank">Orders</a></el-menu-item>`, but click event works only in small tag `<a>` area without full `el-menu-item`.

### Reproduction Link
http://jsfiddle.net/romanany/eaf3tc9y/

**Comment by jikkai** [comment]
```css
.el-menu-item a {
  display: block;
}
```

**Comment by romangit** [comment]
That workaround only increase the heigth.

**Comment by Leopoldthecoder** [comment]
@romangit This is really a matter of CSS: http://jsfiddle.net/leopoldthecuber/eaf3tc9y/1/
