### ISSUE TITLE
表格空间show-overflow-tooltip跟select控件混用 页面卡死

### ISSUE THREAD

**Issue by cel533** [ElemeFE/element#3187]
表格控件show-overflow-tooltip跟select控件混用 页面卡死,但是无报错,大概是这样 
 ```
 <el-table-column label="姓名" width="180" show-overflow-tooltip >
      <template scope="scope.row.name">
        <el-select v-model="value" placeholder="请选择">
            <el-option
              v-for="item in options2"
              :label="item.label"
              :value="item.value">
            </el-option>
          </el-select>
      </template>
    </el-table-column>
```

**Comment by cel533** [comment]
<el-table-column label="姓名" width="180" show-overflow-tooltip >
      <template scope="scope.row.name">
        <el-select v-model="value" placeholder="请选择">
            <el-option
              v-for="item in options2"
              :label="item.label"
              :value="item.value">
            </el-option>
          </el-select>
      </template>
    </el-table-column>

**Comment by Leopoldthecoder** [comment]
没重现：http://jsfiddle.net/leopoldthecuber/ohbvk64w/

**Comment by cel533** [comment]
http://jsfiddle.net/y6d47ucb/1/
这个重现了

**Comment by QingWei-Li** [comment]
建议多看看 Vue 文档，哪有 `<template scope="scope.row.name">`  这种写法了

**Comment by cel533** [comment]
不是...实际上是1.2.1的问题,更新了1.2.3就好了,至于写法,那只是伪代码...

**Comment by jiangxianboy** [comment]
对的，楼上说的对，更新到1.2.3就好了。本来我也有这个问题。直接无限加载导致页面无响应
