### ISSUE TITLE
关于pagination组件 重置currentPage 改变内部状态的问题

### ISSUE THREAD

**Issue by mengxiong10** [ElemeFE/element#3188]
初始传入的currentPage = 1, 通过点击组件改变internalCurrentPage = 3
 比如  现在外部的列表变化了,外部需要重置Page = 1, 没有办法了.外部的currentPage 本来还是1 ,变化内部无法响应.
这种情况有什么办法吗

**Comment by haijianyang** [comment]
同问这样的问题，好像只有第一次在外部设置page的值的时候生效，之后再设置就无效了。

**Comment by ygtzz** [comment]
同问，设置currentPage=1分页1不会高亮，求解决方法？

**Comment by Mengxiong10** [comment]
看了源码, 需要设置@current-change="currentPage = arguments[0]",这样内部外部的currentpage就同步了

**Comment by haijianyang** [comment]
重新写了一个分页组件，结合vuex使用，用起来和antd的table差不多。

**Comment by hanemiyaai** [comment]
:current-page 设置的值就设置成通过@current-change去改变的值，再手动设置为1时，就会高亮了。
<el-pagination
	      @size-change="handleSizeChange"
	      @current-change="handleCurrentChange"
	      :current-page="page.currentPage"
	      :page-sizes="[10, 20, 50]"
	      :page-size="10"
	      layout="total, sizes, prev, pager, next, jumper"
	      :total="total">
	    </el-pagination>
data
`data() {
			return {
				condition: {
					queryType: 'phone',
					queryContent: ''
				},
				userInfoList:[],
				total: 100,
				page:{
					currentPage: 1,
					pageSize: 10
				}
			}
		}`

methods中设置的方法：
`handleQuery() {
				let sel = this;
				sel.page.currentPage = 1;
				console.log('查询...');
			},
			handleSizeChange(val) {
      },
      handleCurrentChange(val) {
        this.page.currentPage = val;
      }`

**Comment by huguangju** [comment]
一个临时解决方案, 通过 `ref` 来操作内部属性 `internalCurrentPage`：
```html
<el-pagination ref="pagination"
            small
            layout="prev, pager, next"
            :page-size="pageSize"
            :total="total"
            :current-page="currentPage"
            @current-change="pageChange">
```

```js
export default {
  data: {
    // ...
    currentPage: 1,
    pRef: null
  },
  mounted() {
    this.pRef = this.$refs.pagination
  },
  methods: {
      someMethod() {
        this.pRef.internalCurrentPage = this.currentPage
        // ...
      }
  }
}
```

副作用是会再次触发currentChange事件

**Comment by 857681664** [comment]
加.sync修饰符看看

**Comment by fengyun2** [comment]
加了.sync修饰符没用，请问有谁解决了这个问题么？

**Comment by alvin-xu** [comment]
+1

**Comment by ziyoung** [comment]
@alvin-xu 不太明白你们的意思。写了例子：https://jsfiddle.net/zhiyang/qwsL3g1f/9/ ，不确定是否解决了你们的问题。

**Comment by hardmanhong** [comment]
需求是从编辑页面返回列表页需记住分页，保存再store，返回时设置current-page.sync无效

**Comment by fengyun2** [comment]
这么久了，还没有人处理么？

**Comment by luoye-fe** [comment]
触发条件：

1、`total` 初始化为 0

2、同步操作中改变 `currentPage` 的值

3、异步操作中改变 `total` 的值

4、分页组件拿到不合法的 `currentPage`，将页数改为 1，之后即使 `total` 大于0，也没有重置 `currentPage`

**Comment by luoye-fe** [comment]
https://github.com/ElemeFE/element/blob/c8ce0410f9a2b3d5bdb8027493a42497cc1578f8/packages/pagination/src/pagination.js#L400-L404

主要是这段代码，从逻辑上来讲也没毛病，保证 当前页码 都是合法值，但是上面说的情况就比较尴尬，可以在分页组件上加上 `v-if`，`total` 为 0 时不渲染，有了值之后再进行渲染。

**Comment by xuejiangjun** [comment]
> 触发条件：
> 
> 1、`total` 初始化为 0
> 
> 2、同步操作中改变 `currentPage` 的值
> 
> 3、异步操作中改变 `total` 的值
> 
> 4、分页组件拿到不合法的 `currentPage`，将页数改为 1，之后即使 `total` 大于0，也没有重置 `currentPage`

you should set `total` default value `null` not 0，设置total的初始值为null而不是0 #1153

**Comment by luoye-fe** [comment]
> > 触发条件：
> > 1、`total` 初始化为 0
> > 2、同步操作中改变 `currentPage` 的值
> > 3、异步操作中改变 `total` 的值
> > 4、分页组件拿到不合法的 `currentPage`，将页数改为 1，之后即使 `total` 大于0，也没有重置 `currentPage`
> 
> you should set `total` default value `null` not 0，设置total的初始值为null而不是0 #1153

嗯，THX

**Comment by hehe1111** [comment]
Thx~ 

> [element/packages/pagination/src/pagination.js](https://github.com/ElemeFE/element/blob/c8ce0410f9a2b3d5bdb8027493a42497cc1578f8/packages/pagination/src/pagination.js#L400-L404)
> 
> Lines 400 to 404 in [c8ce041](/ElemeFE/element/commit/c8ce0410f9a2b3d5bdb8027493a42497cc1578f8)
> 
>  if (isNaN(newVal)) { 
>    newVal = oldVal || 1; 
>  } else { 
>    newVal = this.getValidCurrentPage(newVal); 
>  } 
> 主要是这段代码，从逻辑上来讲也没毛病，保证 当前页码 都是合法值，但是上面说的情况就比较尴尬，可以在分页组件上加上 `v-if`，`total` 为 0 时不渲染，有了值之后再进行渲染。

Thx~

**Comment by hexufeng** [comment]
好坑啊，total初始化为0时不渲染，修改了它的状态也不渲染。。。初始值置为null就可以了，这让人难以理解。

**Comment by fangchaolong** [comment]
都发布到了2.11.1版本了还没有解决吗

**Comment by zhangyupeng233** [comment]
搞好久  初始total = null 解决了我的问题  这个bug不修复也该出个提示

**Comment by jay33333** [comment]
$refs 中 把他的internalCurrentPage和lastEmittedPage，都重置相同的值，要不然点击值和lastEmittedPage相同，current-change不会触发

**Comment by Dangdtx** [comment]
<el-pagination
              v-if="total"
              style="margin-left: 59px;"
              :current-page.sync="currentPage"
              @current-change="pageChange"
              layout="prev, pager, next"
              :page-size="pageSize"
              :total="total"
            >
            </el-pagination>
我添加了async之后可以了   你们也试一下看可不可以

**Comment by kaoson** [comment]
> $refs 中 把他的internalCurrentPage和lastEmittedPage，都重置相同的值，要不然点击值和lastEmittedPage相同，current-change不会触发

yes, ok!

**Comment by suedar** [comment]
这个问题又出现了 怎么解决呢
