### ISSUE TITLE
[建议]select组件能否把请求到的数据放到组件内部

### ISSUE THREAD

**Issue by yangyichen** [ElemeFE/element#3190]
最近一直在用这个组件库，为我提供了很多便利，在这边先感谢一下开发人员的付出。

在使用过程中我发现，我的页面需要很多的remoted select框，这不得不让我写很多的数组来让组件中的option绑定model，感觉到不适很方便，所以能不能考虑下默认把数据放到组件内部，有需要的话能绑定vuedata里的数据。

最后再一次感谢你们。

**Comment by Leopoldthecoder** [comment]
无计划。
