### ISSUE TITLE
在 table 中使用 dropdown，如何将当前 row 传予 @command？

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#3194]
```html
<el-table-column
  inline-template
  :context="_self"
  label="操作">
  <template>
    <el-dropdown @command="onOperate">
      <span class="el-dropdown-link">
        操作
      </span>
      <el-dropdown-menu slot="dropdown">
        <el-dropdown-item command="approve">通过</el-dropdown-item>
        <el-dropdown-item command="reject">驳回</el-dropdown-item>
      </el-dropdown-menu>
    </el-dropdown>
  </template>
</el-table-column>
```

![image](https://cloud.githubusercontent.com/assets/8470477/23492672/cd9b34c6-ff40-11e6-874e-d869601ace30.png)

这种用法（在表格中以下拉菜单形式呈现按钮组）如果合理的话，理应能将当前 `row` 传给 `@command` 事件。但 `@command` 默认带上 `command` 字符串，能否也带上 `row`？

**Comment by jasonlam0619** [comment]
Never mind. `@command` is unnecessary. Could totally use `@click` event, but remember to use `.native` flag - that would be `@click.native` on `el-dropdown-item`.

**Comment by feixiaohuijava** [comment]
大佬，怎么解决的啊？
