### ISSUE TITLE
[建议]TimePicker加入点击或拖拽选择时间段..

### ISSUE THREAD

**Issue by michael829** [ElemeFE/element#3196]
目前DatePicker有一个非常实用的功能..就是日期范围选择...这个功能也集成到了DateTimePicker中..那么有没有可能在TimePicker中对起始和结束时间进行一个可视化的拖拽或点选精确时间的操作呢? 目前选择具体的时间需要点击时, 分, 秒三个操作..异常繁琐...希望考虑一下并集成到DateTimePicker中...谢谢..

**Comment by QingWei-Li** [comment]
不考虑
