### ISSUE TITLE
Tree树形菜单怎么固定高度？

### ISSUE THREAD

**Issue by FlappyHeart** [ElemeFE/element#3198]
超出高度能否加上滚动条？菜单太长而且还不想隐藏其他，能不能做个固定高度

**Comment by Leopoldthecoder** [comment]
自己加 CSS 就可以。

**Comment by FlappyHeart** [comment]
谢谢，没想到这么简单。
附上一段代码，其他需要的朋友可以直接用。

```
.scroll-bar{
    min-height: 200px;
    overflow-y: auto;
    max-height: 200px;
}
```

**Comment by linfanboss** [comment]
.scroll-bar{
    min-height: 200px;
    overflow-y: auto;
    max-height: 200px;
}
直接写height：200px；不就行了，为何要min-height，max-height，看不懂
