### ISSUE TITLE
Dialog 对话框 并不能插入echarts图表

### ISSUE THREAD

**Issue by chenyeah** [ElemeFE/element#3200]
Dialog 对话框 并不能插入echarts图表

### ElementUI version
 1.2.3

### OS/Browers version
Chrome 56

### Vue version
 2.0.0

**Comment by PanJiaChen** [comment]
这和element没什么关系吧，你需要在dialog 实例化之后再init echarts 应该就好了
http://jsfiddle.net/ktmL5zmw/
