### ISSUE TITLE
建议：日历组件能否增加自定义元素，例如加入价格之类的

### ISSUE THREAD

**Issue by hasbug** [ElemeFE/element#3203]
RT，这个需求大家应该很容易都会遇到的吧？

**Comment by jikkai** [comment]
是指在 datepicker 上加这种类似的东西吗？
![image](https://cloud.githubusercontent.com/assets/14025786/23541700/ff3f4df8-0023-11e7-97de-8dd7140876b5.png)

**Comment by hasbug** [comment]
@jikkai  对对对，能够自定义？

**Comment by QingWei-Li** [comment]
不考虑
