### ISSUE TITLE
Form-Item的rules自定义验证规则时，value为undefined

### ISSUE THREAD

**Issue by forzalianjunting** [ElemeFE/element#3204]
如下图，自定义规则进行验证时，value打印出来为undefined，无法进行验证

![image](https://cloud.githubusercontent.com/assets/15181706/23498158/4039318e-ff61-11e6-9659-49a9dff5068a.png)
![image](https://cloud.githubusercontent.com/assets/15181706/23498174/55d9ffe6-ff61-11e6-92be-5c032efbb5db.png)
![image](https://cloud.githubusercontent.com/assets/15181706/23498191/62c9ed9c-ff61-11e6-9a75-4194c027036d.png)

**Comment by Leopoldthecoder** [comment]
value 对应的是 `el-form-item` 的 `prop` 绑定的值，这段代码里 `'rebateRate' + addAgreementIndex` 有值吗？正常情况下 `prop` 绑定值应该和表单元素的绑定值（这个例子里的 `agreementItem.rebate_rate`）是一致的。

**Comment by forzalianjunting** [comment]
该表单是动态添加然后遍历出来的，addAgreementIndex是该项的序号，所以是有值的，为了验证，刚才我把prop里的addAgreementIndex去掉，但仍然有问题 @Leopoldthecoder

**Comment by forzalianjunting** [comment]
我直接用自带的验证也是同样的问题 @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
但是你的 `el-input` 并没有绑定到你需要验证的字段上啊

**Comment by xs47968224** [comment]
你如果只需要验证动态增加的那个费率，那很简单
首选你的prop不对，需要写“'表单大数组字段.' + 下标 + '.字段'”
直接在在prop下面的rules这样写
:rules="[{
     validator: (rule, value, callback) => {
         // 这里写判断,value肯定是有值的
          return callback('费率不正确' + value)
     }, trigger: 'blur'
 }]"
但如果你想拿这个value和动态添加的其它字段进行比较，我没找到方法，希望知道的人告知一下
