### ISSUE TITLE
Feature Request - Slider: Non-linear Steps

### ISSUE THREAD

**Issue by Valumard** [ElemeFE/element#3207]
### ElementUI version
 1.2.3

### Vue version
2.1.10

### Feature request
I wish there would be an option to pass the possible values to the slider like an array or so.
[10, 15, 25, 100, 250] and that these are the only valid options you can choose from.

Thanks!

**Comment by Leopoldthecoder** [comment]
Doesn't seem like a common use case. But if you are interested, contributions are always welcome.
