### ISSUE TITLE
NavMenu 导航菜单水平模式 多级菜单支持

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#3208]
# NavMenu 导航菜单 mode="horizontal" 且包含多层子菜单的时候错位
# vertical 模式没有问题

[http://jsfiddle.net/zhanqi/zvceu0bh/](http://jsfiddle.net/zhanqi/zvceu0bh/)

# 为什么多级菜单不能像 Cascader 选择器这样横向展开

[http://jsfiddle.net/zhanqi/86dcLxey/](http://jsfiddle.net/zhanqi/86dcLxey/) 

![right](https://cloud.githubusercontent.com/assets/2288630/23499923/0db64e38-ff69-11e6-81f0-76ee5db59b1a.png)

![wrong](https://cloud.githubusercontent.com/assets/2288630/23499934/139e0b1a-ff69-11e6-824b-570d56905614.png)

**Comment by baiyaaaaa** [comment]
文档上写了多级菜单只对垂直模式有效

**Comment by zlab** [comment]
水平模式多级菜单以后会支持吗

**Comment by zhonggedan** [comment]
@baiyaaaaa  文档上写了吗？ 请指出？
