### ISSUE TITLE
npm run dev 时候报错，我已经安装了 style-loader 等三个。但是依然不行

### ISSUE THREAD

**Issue by dfggking** [ElemeFE/element#3209]
![image](https://cloud.githubusercontent.com/assets/5519945/23500339/a3303f2c-ff6a-11e6-87bf-e21e014dcb29.png)

**Comment by QingWei-Li** [comment]
https://github.com/ElementUI/element-starter

**Comment by dfggking** [comment]
谢谢您的回答。 我这个项目是vue init webpack-simple 创建的，存在这个问题。我后来有创建的vue init webpack结果就可以使用。  虽然现在还不知道问题所在。   我会在测测定位原因。
再次感谢
