### ISSUE TITLE
在使用<el-checkbox-group>的时候，将 v-model的值设置为空数组后，下面的复选按钮仍然为选中状态

### ISSUE THREAD

**Issue by TingYinHelen** [ElemeFE/element#3210]
Hi  contributors~
我在使用`<el-checkbox-group v-model="checkList">`的时候，先我选中了一些选项，然后将checkList设置为空数组，下面的选框还是选择状态呢？我希望`checkList=[]`之后，取消所有的选择，应该怎么做呢

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/LbL2d7a5/ 没啥问题
能提供线上demo么

**Comment by TingYinHelen** [comment]
额，好像可以了，是我自己代码的问题[http://jsfiddle.net/HelenYin/erenudky/4/](url)
