### ISSUE TITLE
form表单自定义动态检验有个疑问

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#3213]
![qq 20170302183957](https://cloud.githubusercontent.com/assets/16487810/23503683/ab2ff566-ff77-11e6-85aa-f15a90ec4bde.png)
![qq 20170302184035](https://cloud.githubusercontent.com/assets/16487810/23503684/ab62a3a8-ff77-11e6-8073-496e57fda33b.png)
当我点击单选按钮的时候，动态改变检验规则，选择制定密码的时候页面输入的规则已经实时更新了出来，显示为
![qq 20170302184320](https://cloud.githubusercontent.com/assets/16487810/23503778/fe68aba6-ff77-11e6-883f-b331777329c3.png)
但是实际的交互情况失去焦点的时候没有触发那个检验，点击保存的时候但是会触发检验，不过体验上差了下，后续的动态改变的检验，trigger没有触发

**Comment by lincenying** [comment]
你干嘛要去改password的验证规则???
直接用v-if判断密码输入框渲染不渲染就行

**Comment by killdada** [comment]
随机密码的时候是非必填的，指定是必填的，所以要改规则，后面自己添加了个blur函数去触发这个字段的校验
