### ISSUE TITLE
多个el-dialog切换，在Firefox下黑背景会有闪白的情况

### ISSUE THREAD

**Issue by Longui** [ElemeFE/element#3224]
应该是动画里面的leave事件引起

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by Longui** [comment]
`<el-button type="text" @click="dialogVisible = true">点击打开 Dialog</el-button>

<el-dialog title="提示" v-model="dialogVisible" size="tiny">
  <span>这是一段信息</span>
  <span slot="footer" class="dialog-footer">
    <el-button @click="dialogVisible = false">取 消</el-button>
    <el-button type="primary" @click="dialogVisible = false;dialogVisible2 = true;">确定并打开另一个</el-button>
  </span>
</el-dialog>

<el-dialog title="提示" v-model="dialogVisible2" size="tiny">
  <span>这是第二段信息</span>
  <span slot="footer" class="dialog-footer">
    <el-button @click="dialogVisible = false">取 消</el-button>
    <el-button type="primary" @click="dialogVisible = false">确 定</el-button>
  </span>
</el-dialog>

<script>
  export default {
    data() {
      return {
        dialogVisible: false,
        dialogVisible2: false
      };
    }
  };
</script>`
