### ISSUE TITLE
input-number样式问题

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#3227]
vue   2.1.8

element-ui   1.2.3

form表单中，使用input-number 底部间距有问题，请看图。
![111](https://cloud.githubusercontent.com/assets/23046680/23536001/fee40dd4-fffc-11e6-8e04-e41c7ad605bc.png)

在线测试地址： http://jsfiddle.net/59cbuvx4/

**Comment by lincenying** [comment]
自己改改样式吧, 把.el-input-number的display属性改成block
