### ISSUE TITLE
el-table Cannot read property 'id' of null     at VueComponent.handleCurrentChange

### ISSUE THREAD

**Issue by ChobitsSP** [ElemeFE/element#3229]
el-table 添加 highlight-current-row 和 current-change 来高亮选中行

之后对高亮数据进行删除 或者对data重新赋值 就会出现
Error in watcher "data" 
(found in component <ElTable>)

**Comment by Leopoldthecoder** [comment]
没重现：http://jsfiddle.net/leopoldthecuber/3a64f2cd/

**Comment by ChobitsSP** [comment]
知道问题了 需要在handleCurrentChange方法里进行空值检测
