### ISSUE TITLE
select组件在filterable为true时，选中一条记录后，在次单击select，下拉列表中就只剩一条选中的记录了

### ISSUE THREAD

**Issue by wgq837051** [ElemeFE/element#323]
select组件在filterable为true时，选中一条记录后，在次单击select，下拉列表中就只剩一条选中的记录了

**Comment by Leopoldthecoder** [comment]
因为是 filterable，下拉列表的备选项总是过滤后的结果。如果想要选中其他项，需要将目前的选中项删除。
