### ISSUE TITLE
IE下 el-form-item 的高度有问题

### ISSUE THREAD

**Issue by hjkcai** [ElemeFE/element#3230]
### ElementUI version
1.2.3

### OS/Browers version
win10 / IE10-11

### Vue version
2.2.1

### Reproduction Link
https://jsfiddle.net/oj2wrwc4/

### What is Expected?
`el-form-item`能根据内容自动调整高度

### What is actually happening?
最下面多出了一小截空白

![screen shot 2017-03-03 at 11 15 13 am](https://cloud.githubusercontent.com/assets/731326/23536829/b30e6944-0002-11e7-900e-96792ae14f0c.png)

**Comment by lincenying** [comment]
这东西, 自己写css覆盖下, 每个人的需求都不一样

**Comment by Leopoldthecoder** [comment]
Fixed in #3265
