### ISSUE TITLE
表格可以导出Excel吗

### ISSUE THREAD

**Issue by SimonZhangITer** [ElemeFE/element#3232]
如题，谢谢！

**Comment by QingWei-Li** [comment]
https://segmentfault.com/a/1190000008060543

**Comment by SimonZhangITer** [comment]
可以提供一下CsvExport的文件链接吗

**Comment by SimonZhangITer** [comment]
@QingWei-Li 你好，可以提供一下CsvExport的文件链接吗

**Comment by Leopoldthecoder** [comment]
@SimonZhangITer 链接里的第一段代码块就是 CsvExport.js。

**Comment by SimonZhangITer** [comment]
@Leopoldthecoder json2csv是这个吗：https://github.com/zemirco/json2csv

**Comment by Leopoldthecoder** [comment]
是

**Comment by SimonZhangITer** [comment]
非常感谢

**Comment by JimmyLincole** [comment]
请教一下：
如何导出 el-table-column :formatter="formatMoney" 之后的数据呢？
原始数据为 `10`，formatMoney 之后是 `$10.00`，有比较多需要格式化的列。

谢谢！！
