### ISSUE TITLE
选择框el-select的内容如果用v-for遍历后，有种情况导致它无法正常验证

### ISSUE THREAD

**Issue by maxwellwei1** [ElemeFE/element#3237]
```
<el-select v-model="form.roleId" placeholder="請選擇角色" >
                    <el-option
                        v-for="item in roles"
                        v-bind:label="item.NameZhtw" 
                        v-bind:value="item.Id">
                    </el-option>
                </el-select>
```

如果 roles的格式如下：[ { Id : 1,  NameZhtw : "name1" } , { Id : 2, NameZhtw : "name2" } ]  这样就不能正常的验证，
必须是[ { Id : “1”,  NameZhtw : "name1" } , { Id : “2”, NameZhtw : "name2" } ]  ，Id的值必须是字符串才可以正常验证

如果是是第一种情况，可以在控制台报个错也行，找问题找了好久。。。
还有那个单选按钮的值，直接用true或者false都不能绑定值，必须要转换成字符串才能正常绑定值，但是控制台也没有提醒

**Comment by lincenying** [comment]
roles 的type默认是字符型, 
另外验证的提示, 只是不要用了产品模式, 控制台都会抛出
```
async-validator: ["tradeNum is required"]
async-validator: ["amount is required"]
```
类似上面的错误

**Comment by maxwellwei1** [comment]
> <el-select v-model="form.roleId" placeholder="請選擇角色" >
>                     <el-option
>                         v-for="item in roles"
>                         v-bind:label="item.NameZhtw" 
>                         v-bind:value="item.Id">
>                     </el-option>
>                 </el-select>

roles 是上面的json数据

**Comment by maxwellwei1** [comment]
`<el-select v-model="form.roleId" placeholder="請選擇角色" >
                    <el-option
                        v-for="item in roles"
                        v-bind:label="item.NameZhtw" 
                        v-bind:value="item.Id">
                    </el-option>
                </el-select>`

roles是上面的json数据

**Comment by lincenying** [comment]
保证form.roleId的类型和item.Id的类型一致, 不要一边是数值型, 一边字符型

**Comment by maxwellwei1** [comment]
form.roleId = 1   这样默认为数值型1， 验证还是有问题

**Comment by lincenying** [comment]
你的validator的rules规则怎么写的.?

**Comment by maxwellwei1** [comment]
@lincenying     谢谢你

html里这样调的：
`<el-form ref="form" :rules="rules" :model="form">`

data里这样写的：
`rules: {
                roleId: [{ required: true, message: '請選擇角色', trigger: 'change' }]
            },`

**Comment by maxwellwei1** [comment]
`<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui/lib/index.js"></script>
<div id="app">
<template>
  <el-form ref="form" :rules="rules" :model="form">
        <el-col>
            <el-form-item prop="roleId">
                <el-select v-model="form.roleId"  placeholder="請選擇角色" >
                    <el-option
                        v-for="item in roles"
                        v-bind:label="item.NameZhtw" 
                        v-bind:value="item.Id">
                    </el-option>
                </el-select>
            </el-form-item>
        </el-col>
    </el-form>
</template>
</div>`

`var Main = {
    data () {
      return {
        form: {
            roleId: "",
        },
        rules: {
          	roleId: [{ required: true, message: '請選擇角色', trigger: 'change' }]
        	},
        roles:[ { Id : 1, NameZhtw : "name1" } , { Id : 2, NameZhtw : "name2" } ],
      };
    }
  }
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')`

**Comment by maxwellwei1** [comment]
[http://jsfiddle.net/tLbsztmn/2/](url)

**Comment by jikkai** [comment]
@maxwellwei1 因为你的`Id`是 `Number` 类型，默认验证的`type`为`string`。所以验证规则需要加上 `type: 'number'`。

```
rules: {
  roleId: [{ required: true, message: '請選擇角色', trigger: 'change', type: 'number' }]
},
```

**Comment by Leopoldthecoder** [comment]
还是因为你的 `Id` 是数字类型的，而校验规则的 `type` 字段默认是 `string`。手动把 `type` 改成 `number` 就好：http://jsfiddle.net/tLbsztmn/3/

**Comment by VaJoy** [comment]
醉了，我在子组件里也出来一样问题，加上type='number'也不行

**Comment by spencer-live** [comment]
@VaJoy 请问这个问题最后怎么解决的? 我也遇到了 T_T

**Comment by konglingwen94** [comment]
我也是遇到了这个问题, 同求
