### ISSUE TITLE
有关于Table组件，当el-table-column组件type="selection"时，怎么手动赋值给checked属性

### ISSUE THREAD

**Issue by haixu777** [ElemeFE/element#324]
单项勾选中时，选中的值自动存入到了handleMultipleSelectionChange的回调里。
当用分页器选择下一页时，发送了请求，table表数据更新了。
如果再回到上一页，选中的值就全消失了。
有什么办法能把handleMultipleSelectionChange回调里的参数返回到上一页的checkbox里呢

**Comment by furybean** [comment]
#517 加了 reserve-selection 的选项，现在可以保存数据变更后的选择了。
