### ISSUE TITLE
日期选择器daterange类型建议添加参数配置可右侧显示当前月而不是默认的左侧

### ISSUE THREAD

**Issue by SuperAL** [ElemeFE/element#3241]
### 应用场景
有时候日期区间选择器用于选择已过去的时间，将来的日期禁止选择，但是当前月默认在左侧，因此必须点击左翻月按钮才可扩大选择区域。

### 期望效果
可通过配置改为右侧显示当前月，左侧显示上一月。

**Comment by SuperAL** [comment]
#7553
Use default-value: https://jsfiddle.net/oo50xmdp/2/
不过上面的方法只能设置初次展开选择器的月份展示，如果用户选择了当前月份的一段时间区间，再次打开，默认当前月份就会显示在左侧；
而我希望的是当前月份的下一个月（用户禁止选择）最好永远不出现在选择器上，默认最后可选的月份为当前月份。

**Comment by csvwolf** [comment]
PR earlier than 2018, closed.
