### ISSUE TITLE
使用ssr nuxt.js，组件Tooltip报错。

### ISSUE THREAD

**Issue by psychokiller666** [ElemeFE/element#3245]
### ElementUI version
1.2.3

### OS/Browers version
macOS/Chrome 56

### Vue version
2.2.1

### What is actually happening?

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 

[nuxt.js] Cannot load components TypeError: Cannot read property 'toLowerCase' of undefined

![](http://p1.bpimg.com/567571/4b547e49cde18cf9.jpg)

**Comment by psychokiller666** [comment]
vue 版本 2.2.1
element ui 版本 1.2.3

**Comment by sora54** [comment]
got same issue...

**Comment by QingWei-Li** [comment]
fixed in 1.2.3

**Comment by ndelvalle** [comment]
I got the same error using element version `1.2.8`, is it fixed for you @psychokiller666?

**Comment by zhanziyang** [comment]
I'm using `1.2.8` and this still occurs.
