### ISSUE TITLE
carousel报错

### ISSUE THREAD

**Issue by rongxingsun** [ElemeFE/element#3247]
走马灯一个只能单独使用，使用多个在npm run时会报错

![image](https://cloud.githubusercontent.com/assets/12825624/23598226/fdc25c02-0273-11e7-9b05-3276278dad60.png)

**Comment by Leopoldthecoder** [comment]
请仔细看报错信息。

**Comment by rongxingsun** [comment]
问题是我什么都没改，只是复制官的基本用法，
