### ISSUE TITLE
table数据刷新的问题。

### ISSUE THREAD

**Issue by crazyleega** [ElemeFE/element#3249]
代码：http://jsfiddle.net/hqw1otj0/4/
场景：当在table列表打开一个窗口修改数据的时候。修改成功后修改tableData里的某个对象
结果：修改成功，但是页面没有刷新数据。

如果是单独的修改  比如说: this.tableData3[0].name = '王大虎' 这样可以刷新数据。
代码：http://jsfiddle.net/hqw1otj0/5/

问题： 请问我们有什么马上刷新table的方式？还是说只能判断数据库修改成功然后自己在修改tableData3的数据？整个对象的修改，如以上代码，没有刷新table。

版本：1.1.6

**Comment by lincenying** [comment]
```javascript
    methods: {
      changeData() {
        this.tableData3.splice(0, 1,  {
          date: '2016-05-11',
          name: '王大虎',
          address: '上海市'
        })
        console.log(this.tableData3);
      }
    },
```
这是vue的问题, 你应该先去看看vue的数据绑定
https://vuefe.cn/v2/guide/reactivity.html

**Comment by crazyleega** [comment]
谢谢你的答复，vue没有看的很仔细。
