### ISSUE TITLE
实现了一个cascader高级功能，送给大家

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#3252]
官方默认值的设置需要整个路径，如[1,12,123];
现在可以只通过 123 来选中，组件自动填满前面的路径，更符合平常选择个栏目什么的，只用自身ID，post时也不是【1，12，123】这种，而是123。
在我的EleAdmin里封装了k-cascader,大家可以去看看

**Comment by jixzfw** [comment]
现在这个选中后的Bug是Element自身cascader的问题，官方更新后就好了。

**Comment by wilsonIs** [comment]
@jixzfw 没见你说的那个k-cascader
