### ISSUE TITLE
tree组件的icon问题

### ISSUE THREAD

**Issue by chinavane** [ElemeFE/element#3254]
```
renderContent (h, { node, data, store }) {
      return (
        <span>
          <i class={data.meta.icon}></i>
          <span>
            <span>{node.label}</span>
          </span>
        </span>
      )
    }
```

我重新渲染了tree组件，新的icon图标也出来了，但是原来的那个箭头还存在，如何去除？

**Comment by Leopoldthecoder** [comment]
renderContent 渲染的是箭头后面的内容。如果确实需要去除箭头，可以通过 CSS 将其隐藏。

**Comment by chinavane** [comment]
我晕，这也行，可以在组件里直接加几个属性吗，showIcon，如果为字符串为显示指定图标，如果为ture/false则默认图标的显示与隐藏。

**Comment by Lancerdxx** [comment]
请问你是怎么做的。是直接在meths里把它加进去吗，为什么我的全是全是错，能帮我一下码
![image](https://cloud.githubusercontent.com/assets/24426941/23639526/3ee7b4c0-0323-11e7-974f-81bdec91d5a2.png)

**Comment by renfan** [comment]
@Lancerdxx 我出现了同样的问题，你解决了吗？

**Comment by docikaci** [comment]
@Leopoldthecoder  这是jsx语法吧，在vue文件里也是报一堆错，和上面兄弟的截图一样， 怎么破？
谢谢 着急~~

**Comment by James-jun06** [comment]
报错见FAQ第三条

**Comment by chinafatboy** [comment]
我也出现了同样的问题，求大神解答一下?上面说的FAQ第三条是在哪里呢？

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/FAQ.md

**Comment by chinafatboy** [comment]
@Leopoldthecoder 非常感谢！

**Comment by zimplexing** [comment]
```
renderTreeContent (h, { node, data }) {
      return h('span', [h('i', {
        'class': {
          'el-icon-star-off': true
        },
        style: {
          'paddingRight': '4px'
        }
      }), h('span', {
        'class': {
          'el-tree-node__label': true
        }
      }, data.name)])
    },
```
使用vue的render函数进行重写
