### ISSUE TITLE
change事件，数据更改了视图不更新

### ISSUE THREAD

**Issue by jaore** [ElemeFE/element#3258]
这里的[在线demo](https://jsfiddle.net/ygg71ydp/5/)是可以正常运行的，
下面的代码是我的一个vue文件，能正常运行而且打印出来的数据也是正常的，但是视图input里面的值没有更改，排除了半天还是没解决，有热心的朋友帮忙看一下吗？

 ![image](http://flsho.com/image/test.jpg)

**Comment by jaore** [comment]
刚刚把代码的<el-input>改成<input>然后赋值用target.value就可以正常视图更新了，真的是蛋疼，本地代码和在线的那个区别是用了路由，心塞...  算了，还是用input不用那个了

**Comment by kfeng0806** [comment]
建议你用watch或者computed

**Comment by zhang156** [comment]
你这个change事件里面的第二个参数很奇怪。。
