### ISSUE TITLE
Uploaders Need A Way to Callback with Raw File data Instead of $POST Via Ajax

### ISSUE THREAD

**Issue by arpowers** [ElemeFE/element#3260]
Hey there, 
Im trying to work with the uploaders but there appears to be no clear way of using them with a Vue callback as opposed to a standard AJAX action URL.... 

IS this possible or can it be added? I'm trying to use Firebase Storage and need to use their API to handle the actual upload, etc..

**Comment by baiyaaaaa** [comment]
U can use the `http-request` prop to do with the raw file as you wish.

**Comment by wuhao5436** [comment]
how can I know the default param of the http-request callback
