### ISSUE TITLE
建议：Table组件增加checkbox的单选控制

### ISSUE THREAD

**Issue by meteorfall** [ElemeFE/element#3264]
Tabel组件有checkbox的选项，默认是多选的。
看示例中单选的实现是通过高亮来完成的。
是否可以考虑增加配置选项，可以控制checkbox出来后是单选还是多选，会更加直观些

**Comment by Leopoldthecoder** [comment]
这个应该不考虑。

如果一定要用 checkbox 来做单选的话：http://jsfiddle.net/leopoldthecuber/16cddb49/
