### ISSUE TITLE
导航栏在未包含的路由下刷新页面出错

### ISSUE THREAD

**Issue by sqchenxiyuan** [ElemeFE/element#3266]
### ElementUI version
1.2.3

### OS/Browers version
win10
chrome 56

### Vue version
vue 2.2.0
vue-router  2.2.1   使用history模式

### What is Expected?

当在导航栏没有配置的vue-router的路由下刷新页面时，导航栏会出错，然后导航栏无法使用

### What is actually happening?

至少不出错吧0、0

**Comment by jikkai** [comment]
请提供引发 bug 的代码或者可复现问题的线上 demo

**Comment by sqchenxiyuan** [comment]
重写了一个demo，然后发现是webpack异步组件请求的问题[手动悲伤]

谢谢啦，我把issue关了
