### ISSUE TITLE
请调整行内表单标签垂直居中

### ISSUE THREAD

**Issue by alosin** [ElemeFE/element#3267]
请调整行内表单标签垂直居中，搞不懂为什么要现在这样显示

**Comment by baiyaaaaa** [comment]
什么意思？不太懂

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
