### ISSUE TITLE
Dialog内再打开一个Dialog 遮罩层错误

### ISSUE THREAD

**Issue by hatunet** [ElemeFE/element#3269]
### ElementUI version
1.2.3

**Comment by jikkai** [comment]
Dialog 组件内不要嵌套 Dialog，详见#2437

**Comment by vboyok** [comment]
建议支持Dialog 嵌套 Dialog

**Comment by jikkai** [comment]
@vboyok 问题不在于支持不支持，而是没有必要。两个平级的 Dialog 组件一样可以实现 Dialog 内再打开一个 Dialog 的需求。还是说有什么特殊需求一定要嵌套完成的吗？

**Comment by vboyok** [comment]
业务组件：订单列表组件OrderList，内嵌 订单详情组件 OrderDetails ,根据需要用 Dialog 显示，
结构示意为
<OrderList>
  <table></table>
  <el-dialog>
       <OrderDetails><OrderDetails>
  </el-dialog>
<OrderList>

而OrderList组件也可能是通过Dialog显示出来的，比如：
<body>
<InvoiceList>
  <el-dialog>
       <OrderList><OrderList>
  </el-dialog>
</invoiceList>
</body>

业务组件的层级是动态生成的，在不同的业务场景下嵌套关系也不一样，并不能简单的将Dialog打平到一层。
如果Dialog组件支持嵌套，业务组件的实现就很容易了。

**Comment by vboyok** [comment]
业务组件：订单列表组件OrderList，内嵌 订单详情组件 OrderDetails ,根据需要用 Dialog 显示，
结构示意为

```
<OrderList>
  <table></table>
  <el-dialog>
       <OrderDetails><OrderDetails>
  </el-dialog>
<OrderList>
```

而OrderList组件也可能是通过Dialog显示出来的，比如：

```
<body>
<InvoiceList>
  <el-dialog>
       <OrderList><OrderList>
  </el-dialog>
</invoiceList>
</body>
```

业务组件的层级是动态生成的，在不同的业务场景下嵌套关系也不一样，并不能简单的将Dialog打平到一层。
如果Dialog组件支持嵌套，业务组件的实现就很容易了。

**Comment by Longui** [comment]
建议增加嵌套！
我在dialog里面使用了自己的一个组件，组件里面使用了dialog，结果就出现组件当中的dialog内容被遮挡的问题。

**Comment by Longui** [comment]
嵌套问题重现，里面没用子组件，不过出现的问题差不多：
http://jsfiddle.net/st1fvyn4/

**Comment by jim888666** [comment]
看了你的博客，不明白怎么用？？
