### ISSUE TITLE
IE9-IE11下报错致无法使用

### ISSUE THREAD

**Issue by francisfeng** [ElemeFE/element#327]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
Windows 10/ Edge 浏览器下的IE模拟

### Vue version
2.0.1

### Reproduction Link

[CodePen](https://codepen.io/QingWei-Li/pen/ozYpNA)

使用 IE11 打开上面链接（Code Pen不支持IE9，但报错信息是和 IE11 一致），浏览器报如下错误：
>
`
SCRIPT5007: 无法获取未定义或 null 引用的属性“toLowerCase”
vue.js (48,24)
`
Vue.js 里的一个`makeMap`函数出错了。

### Steps to reproduce
我的项目里依赖了很多插件，在IE下无法正常工作。逐一卸载插件后，确认是element-ui的问题。具体报错和上面一致。

**Comment by reverland** [comment]
#266 好象是这个

**Comment by Leopoldthecoder** [comment]
@francisfeng 请升级至 1.0.0-rc.6，看看问题还在不在

**Comment by francisfeng** [comment]
升级至 1.0.0-rc.6 后解决问题。
