### ISSUE TITLE
[小BUG]打开2个Dialog，都设置锁定body 滚动，当关掉第二个时，第一个Dialog还在， body 已经解除锁定滚动了

### ISSUE THREAD

**Issue by xuwenhuang** [ElemeFE/element#3270]
打开2个Dialog，都设置锁定body 滚动，当关掉第二个时，第一个Dialog还在 body 已经解除锁定滚动了
BUG重现：
http://jsfiddle.net/egxa68x1/
解决：
ele\src\utils\popup\index.js 约255行
增加!PopupManager.modalDom判断
if (this.modal && this.bodyOverflow !== 'hidden' && !PopupManager.modalDom)

**Comment by clg333zzz** [comment]
如果有多个Dialog，我这边是只在第一个设置lock-scroll，后面所有的都不设置。
这样只会在取消第一个对话框时，body滚动才会出现
