### ISSUE TITLE
日期选择，建议加多本周，本月，本日。

### ISSUE THREAD

**Issue by liqinhua** [ElemeFE/element#3273]

**Comment by liqinhua** [comment]
日期选择，建议加多本周，本月，本日。

**Comment by jikkai** [comment]
如果是说 Datepicker 组件的快捷选项的话，这个可以通过 `picker-options` 的 `shortcuts ` 属性自定义

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
