### ISSUE TITLE
tag组件关闭渐变动画问题

### ISSUE THREAD

**Issue by jinjinwa** [ElemeFE/element#3275]
同时存在多个tag标签，点击tag标签列表考前的关闭，渐变动画还是发生在最后一个。
![tag](https://cloud.githubusercontent.com/assets/12455937/23585081/f8bb1462-01ae-11e7-9946-1db99967420e.gif)

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by jinjinwa** [comment]
已解决，可以关掉issues了。谢谢

**Comment by The-five-stooges** [comment]
怎么解决的能说下吗，谢谢

**Comment by enter3017sky** [comment]
> 已解决，可以关掉issues了。谢谢
請問前輩是如何解決的@@
