### ISSUE TITLE
select组件的下拉框宽度问题

### ISSUE THREAD

**Issue by Galen-Yip** [ElemeFE/element#3283]
https://github.com/ElemeFE/element/blob/dev/packages/select/src/select.vue#L661

单页应用里，一开始找不到该页中的 `reference`，会导致下拉框宽度初始化失败，除非是同步加载组件路由

**Comment by Galen-Yip** [comment]
@QingWei-Li 看下这问题咯

**Comment by Leopoldthecoder** [comment]
请给 demo，可以是一个 GitHub 仓库。
