### ISSUE TITLE
进来瞧瞧关于element ui 表单验证问题

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#3288]
![6nx58kt xhi ltzzrk h](https://cloud.githubusercontent.com/assets/15045200/23594906/b8f1f508-0258-11e7-9af5-13c8e5d8baf7.png)
是这样的 姓名那块prop那样写是可以的 但是密码那里不知道怎么写了 
怎么写进去都不对
![7lpm3bjf n0 u u2frwa9](https://cloud.githubusercontent.com/assets/15045200/23594917/d2cd0f08-0258-11e7-97a7-baf8e49f376f.png)
密码那块我只是多加了一层 多了个User 请问密码那块prop的验证字段该这么写呢 在线等..

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/leopoldthecuber/xh2zx0gb/
