### ISSUE TITLE
How to use 'renderContent' in Tree?

### ISSUE THREAD

**Issue by maskzh** [ElemeFE/element#3289]
### ElementUI version
1.2.1

### Vue version
2.1.10

### What is actually happening?
树组件自定义节点内容使用出错，错误如下：

![image](https://cloud.githubusercontent.com/assets/4187081/23594860/53420ed2-0258-11e7-95e4-daed6ace6632.png)

return 的像 jsx，需要构建工具支持么？

**Comment by Leopoldthecoder** [comment]
FAQ 第三条。

**Comment by Cchenlong** [comment]
Usage

npm install\
  babel-plugin-syntax-jsx\
  babel-plugin-transform-vue-jsx\
  babel-helper-vue-jsx-merge-props\
  --save-dev



In your .babelrc:

{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}
