### ISSUE TITLE
table 中的

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#329]
### ElementUI version

 1.0.0-rc.5
### What is actually happening?
如果cell的值过长换行之后撑大所在行高度，但被固定的列所对应的行 并没有被撑大
![image](https://cloud.githubusercontent.com/assets/6311122/19265564/2e5f00a4-8fd8-11e6-9ac3-ba00cd5fac26.png)

**Comment by Leopoldthecoder** [comment]
duplicate in #180

**Comment by spademan** [comment]
是我同事提的哈哈哈
