### ISSUE TITLE
MessageBox的功能及全局close方法问题

### ISSUE THREAD

**Issue by NadokaCiel** [ElemeFE/element#3292]
1.MessageBox组件，在页面路由发生变化的时候是不会自动关闭的，不知这是否属于设计还是bug……
2.在1的情况下，想通过调用vm.$msgbox的close方法来关闭弹框，会出现以下问题：
·没有生成模态框的情况下，close方法找不到实例instance.value，代码报错。
·生成了模态框的情况下，close方法关闭了弹框，但body的overflow属性，以及插入的遮罩层依旧存在。

**Comment by NadokaCiel** [comment]
[附代码](http://jsfiddle.net/q307yb5y/)
直接点关闭模态框将在console报错，点第三个按钮，close的功能问题

**Comment by Devil-Cong** [comment]
其实这个issue描述得已经很清楚了，并且也附带了demo。有时候没必要那么死扣规范格式。
看过了那么久这个BUG还是存在，按照要求使用 `issue-generator` 重新开了一个 [#5667](https://github.com/ElemeFE/element/issues/5667)
