### ISSUE TITLE
el-input增加id

### ISSUE THREAD

**Issue by mxm145** [ElemeFE/element#3294]
在使用el-input组件时，能否给原始组件input增加id或者class?
源代码这样
![image](https://cloud.githubusercontent.com/assets/869702/23599169/4d4fc0ce-027a-11e7-91d9-3faba8ae0307.png)
因为默认渲染出来的是这样的
![image](https://cloud.githubusercontent.com/assets/869702/23599191/685d0250-027a-11e7-92f0-e1ac65cfb56f.png)
我希望把id="loginPassword"加到input上去，现在是加到外面的div上去了

**Comment by jikkai** [comment]
冒昧问下加 id 是想要做什么呢？如果是想要选取 input 元素的话，可以通过实例对象 vm.$el.querySelector('input') 获取

**Comment by mxm145** [comment]
是一个复制的功能，需要提供目标元素的id，这样直接就能复制内容
现在这样复制内容会增加换行符号

**Comment by mxm145** [comment]
也有其他办法实现，只是没有找到能直接加id的方法，所以来问问

**Comment by baiyaaaaa** [comment]
你可以通过 input.$refs.input来拿到原始组件input，ID只能手动赋值了。没有通过属性添加的办法。
