### ISSUE TITLE
[form]: inline 模式下的 label 样式问题

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#3296]
如题，在 Firefox 下 label 会下沉，示例：

http://jsfiddle.net/95npsp33/

修复方案参考： 调整

 `form.css` 中的 `& .el-form-item__label` 对齐属性

![inline-form-item](https://cloud.githubusercontent.com/assets/2276421/23600341/32397990-0281-11e7-8a5a-618d41772764.png)

**Comment by jikkai** [comment]
可能是 #3218 的那个问题，已经有 PR#3262 修复了，可以验证下看看

**Comment by renxia** [comment]
是一样的，开始时没查到
