### ISSUE TITLE
[el-autocomplete]加了.native修饰符，事件不触发，v-on:blur.native="handleBlur"

### ISSUE THREAD

**Issue by ren8179** [ElemeFE/element#3299]
http://jsfiddle.net/fe2y0qL4/

```
v-on:blur.native="handleBlur"
```

```
handleBlur(){
     console.log('handleBlur');
     this.$message('test blur');
}
```

**Comment by Leopoldthecoder** [comment]
由于 `el-autocomplete` 的最外层元素是 `div` ，所以无法响应 blur 事件。暂时可能需要手动添加事件，比如
```javascript
this.$refs.autocomplete.$el.querySelector('input').addEventListener('blur', handler)
```

后面有计划让 `el-autocomplete` 像 `el-input` 一样将 `blur` 事件 `$emit` 出去。

**Comment by GaoYuanOnline** [comment]
你好，请问我这么写问什么增加不上去呢
`        this.$refs.endRegionComplete[0].$el.querySelector('input').addEventListener('blur', this.regionChange(0));
`
