### ISSUE TITLE
树形控件节点选取

### ISSUE THREAD

**Issue by blanquizel** [ElemeFE/element#330]
### ElementUI version
1.0.0-rc.6

### OS/Browers version
 macOS/Chrome 53 

### Vue version
2.0.0-*

### Reproduction Link
官方文档示例即可
### Steps to reproduce
创建一个含有多个节点的可选择树形控件，点击父节点或是子节点。
### What is Expected?
当点击父节点时，子节点应一并选中;当点击子节点时，如果父节点只有一个子节点，应也选中，如果有多个，则显示“－”
### What is actually happening?
当父子节点均为选中时，点击子节点，没有反应，父子节点均无状态切换；当父子节点均选中时，点击子节点可以正常取消，点击父节点则无反应。

**Comment by blanquizel** [comment]
此外，文档中
1.基础用法中，定义了node-click，但是methods中没有实现；在可选择中，没有定义node-click，但是有实现的方法。
2.Tree的getCheckedNodes方法没有示例。

**Comment by 89lovelc** [comment]
急求

**Comment by QingWei-Li** [comment]
fixed in https://github.com/ElemeFE/element/pull/367

**Comment by furybean** [comment]
Please use [RC7](https://github.com/ElemeFE/element/releases/tag/v1.0.0-rc.7)

**Comment by SidFeng** [comment]
Tree的getCheckedNodes怎么使用？

**Comment by HuangPingP** [comment]
this.$refs.tree.getCheckedNodes会获得相应节点的数据
