### ISSUE TITLE
[建议]form验证使用起来比较麻烦，对特殊类型（数字/日期）支持不太好

### ISSUE THREAD

**Issue by ccfish86** [ElemeFE/element#3301]
推荐集成一个类似vee-validate的验证框架。
虽然vee-validate和element-ui一起用并不冲突。

vee-validate用起来比较方便（如下），其他配置统一定义即可。
**template**
`<el-form-item label="电话号码" :error="errors.first('telephone')">
  <el-input v-model="form.telephone" data-vv-name="telephone" v-validate data-vv-rules="required|numeric|min:11|max:12" ></el-input>
</el-form-item>`
**script**
`this.$validator.validateAll().then(result => {
  if (result) {
    // 业务
  } else {
    this.$toast('请确认画面项目')
  }
})`

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
