### ISSUE TITLE
文档关于按需引入那块，建议写的详细点

### ISSUE THREAD

**Issue by inuyasha2012** [ElemeFE/element#3302]
文档就举了两个例子，还全是component和use方式的引入

事实上看源码，有些组件压根不能用component或use方式引入

例如message，你若Vue.use(message)，初次载入立马弹出消息，$message没有绑定this

看源码，应该是Vue.prototype.$message = Message的方式引入

按这种方式引入的组件还不少

Vue.prototype.$msgbox = MessageBox;
Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;
Vue.prototype.$prompt = MessageBox.prompt;
Vue.prototype.$notify = Notification;
Vue.prototype.$message = Message;

还有Loading组件

正确的按需引入方式应该是

Vue.use(Loading.directive);
Vue.prototype.$loading = Loading.service;

所以，建议更改下文档

**Comment by DanielWLam** [comment]
看了你的说明才用对了Loading，自己研究得搞好久，谢谢了

**Comment by pisse** [comment]
确实按需引入模块例子太少，明明是简单的模块，废了白天都不知道咋用
