### ISSUE TITLE
table的cell-dblclick事件没有触发

### ISSUE THREAD

**Issue by zhangfanwen** [ElemeFE/element#3303]
### ElementUI version
1.2.3

### OS/Browers version
Chrome 56

### Vue version
2.1.0

### Steps to reproduce
1. 在el-table上定义cell-dblclick事件处理
<el-table :data="users" v-on:cell-dblclick="editable" highlight-current-row v-loading="listLoading" style="width: 100%;" >
2. 在回调editable中打印cell
该回调函数没有被调用

### What is Expected?
回调函数被正常调用

**Comment by zhangfanwen** [comment]
so in which release?

**Comment by Leopoldthecoder** [comment]
本周会发一版

**Comment by huerhai** [comment]
原来不是我一个人遇到~
