### ISSUE TITLE
在文件中 upload 的最後一個範例下方methods並沒有實作 submitUpload

### ISSUE THREAD

**Issue by michael50602** [ElemeFE/element#3304]
<el-upload
      class="upload-demo"
      ref="upload"
      action="//jsonplaceholder.typicode.com/posts/"
      :on-preview="handlePreview"
      :on-remove="handleRemove"
      :file-list="fileList"
      :auto-upload="false">
      <el-button slot="trigger" size="small" type="primary">选取文件</el-button>
      /*下面的這個 el-button @click submitUpload method沒有被實作 tag*/ 
     <el-button style="margin-left: 10px;" size="small" type="success" @click="submitUpload">上传到服务器</el-button>
      <div slot="tip" class="el-upload__tip">只能上传jpg/png文件，且不超过500kb</div>
     </el-upload>
     <script>
      export default {
        data() {
          return {
            fileList: [...]
          };
        },
        methods: {
          handleRemove(file, fileList) {
            console.log(file, fileList);
          },
          handlePreview(file) {
            console.log(file);
          }
        }
      }
    </script>

我在套用範例的時候不太知道應該在submitUpload如何實作？
不好意思可以提供完整的範例嗎？
另外我在我的專案中用了attribute auto-upload="false"卻一直還是自動上傳想請問是我哪裡出錯了呢？

**Comment by Leopoldthecoder** [comment]
例子有误，下个版本更新：https://github.com/ElemeFE/element/pull/3255/files
关于 auto-upload，请确认 Element 的版本大于 1.2.0

**Comment by baiyaaaaa** [comment]
out in 1.2.4
