### ISSUE TITLE
Drag to load example in uploader document isn't up to date.

### ISSUE THREAD

**Issue by lordfriend** [ElemeFE/element#3306]
There are a mistake in document of upload.
In **drag to load** example. the attribute `drag` isn't a valid attribute while the API document says it is the `type` property that does this job.

Although the jsfiddle example works well with the `drag=""` attribute but the version 1.1.6 which is I'm using doesn't work.

**Comment by Leopoldthecoder** [comment]
Sorry, the documentation needs an update.

But if you're using 1.1.6, you should refer to the 1.1 docs: http://element.eleme.io/1.1/#/zh-CN/component/upload
