### ISSUE TITLE
el-select的el-option 的容量有多少？超过5000，已经变得很慢，不可接受，超过10000直接卡死了

### ISSUE THREAD

**Issue by Haiyang2017** [ElemeFE/element#3307]
el-select的el-option过多时会有很明显卡顿 #1933
这个问题中的数据量只有几百条，几百条数据量确实还可以。
几千条怎么办呢？
有好的建议吗？

**Comment by jikkai** [comment]
不开玩笑地说，上千条就是软件设计缺陷了

**Comment by Haiyang2017** [comment]
是的呀。也是准备考虑别的方式了，就是想问问这个指标，另外这个el-select，具有搜索功能，数据量大一些，如果不卡顿的话，也没太大问题。

**Comment by kfeng0806** [comment]
可以考虑ajax动态搜索
