### ISSUE TITLE
Popover with callbacks as options like onUpdate not working as expected

### ISSUE THREAD

**Issue by brunogaspar** [ElemeFE/element#3309]
### ElementUI version

1.2.3

### OS/Browers version

Google Chrome Version 56.0.2924.87 (64-bit) but it's not browser related.

### Vue version

2.2.1

### Reproduction Link

https://jsfiddle.net/knabavw0/

### Steps to reproduce

Click on the `Click to activate` button.

### What is Expected?

I was expecting to see on the browser console `Updated` whenever the popover was shown or hidden.

### What is actually happening?

Nothing. The `onUpdate` callback is never being called, while it works perfectly fine on Popper.js vanilla.

**Comment by Leopoldthecoder** [comment]
Fixed in #3991. Please note that the `options` attribute has been renamed to `popper-options`.
