### ISSUE TITLE
tree renderContent中的el-checkbox选不中

### ISSUE THREAD

**Issue by yaojunWang** [ElemeFE/element#3310]
`renderContent(h, { node, data, store }) {`
	`return (`
	`<span>`
		`<span>`
			`<span>{node.data.menuName}</span>`
		`</span>`
		`<span style="float: right; margin-right: 20px">`
			`<el-checkbox-group v-model="checkList">`
			`<el-checkbox on-change= { () => this.powerC(store, data) } label="新增"></el-checkbox>`
			`<el-checkbox on-change= { () => this.powerR(store, data) } label="查询"></el-checkbox>`
			`<el-checkbox on-change= { () => this.powerU(store, data) } label="修改"></el-checkbox>`
			`<el-checkbox on-change= { () => this.powerD(store, data) } label="删除"></el-checkbox>`
			`</el-checkbox-group>`
		`</span>`
	`</span>`
	`);`
`}`

代码如上，点击 checkbox的时候是可以执行对应函数的，就是样式不会变成选中状态.

**Comment by yaojunWang** [comment]
去掉`el-checkbox-group`就好了，不过这样的话初始化值就有点麻烦。

**Comment by Stpcurry30** [comment]
> 去掉`el-checkbox-group`就好了，不过这样的话初始化值就有点麻烦。

我也遇到这个了
