### ISSUE TITLE
el-select  v-model 的一个问题

### ISSUE THREAD

**Issue by yeernet** [ElemeFE/element#3311]
el-select( v-model="form.type" )
 v-model绑定的不是data的直接子对象,而是data的二级子对象时, 通过UI点击改变选项, 变化不会被立刻应用到UI上, 但改变其他data中的对象时, 刚才通过UI点击改变选项反映到UI上了, 这是我使用错误,还是element本身的问题呢?

**Comment by Leopoldthecoder** [comment]
请给 demo

**Comment by yeernet** [comment]
这个问题找了有些时间了,刚才写demo重构时发现这是我们接口不规范造成的, 后端开发者没有遵守约定的规范, 不同的接口中相同的对象用了不同的参数名, 导致遵守规范的前端框架出问题, 不是element的问题, 打扰了
