### ISSUE TITLE
this.$confirm 的确认和取消按钮位置没法交换

### ISSUE THREAD

**Issue by fandudu** [ElemeFE/element#3312]

**Comment by PanJiaChen** [comment]
可以简单的通过css 实现吧
http://jsfiddle.net/coc3p7gr/

**Comment by Crise420WMT** [comment]
are you sure is ok? I can't got it

**Comment by PanJiaChen** [comment]
@Crise420WMT 
update the demo http://jsfiddle.net/coc3p7gr/3/
