### ISSUE TITLE
如何修改组件并看到效果

### ISSUE THREAD

**Issue by SimonZhangITer** [ElemeFE/element#3315]
如题，我已经fork到了我的项目下。

现在想尝试添加一些功能，请问如何修改代码直接可以看到效果？

比如：我修改了packages/table/src/table.vue的代码之后怎么看到效果呢？

谢谢！

**Comment by Leopoldthecoder** [comment]
用 `npm run dist` 自己 build 一份。

**Comment by SimonZhangITer** [comment]
不是很明白 我执行了这个命令之后，在http://localhost:8085/#/zh-CN/component/table页面也没有看到改变。

PS：我是在packages/table/src/table.vue的created方法里加了一句log，但是在控制台没有看到任何输出。

请问如何操作
还请不吝赐教，谢谢！

**Comment by Leopoldthecoder** [comment]
这已经和 Element 无关了，建议自行学习 npm 相关知识。
