### ISSUE TITLE
 row-key 和reserve-selection组合实现下一页多选保留问题

### ISSUE THREAD

**Issue by zhh419953** [ElemeFE/element#3318]
row-key 和reserve-selection组合实现下一页多选保留问题。请问有相关的demo吗？

**Comment by shuangmuyingzi** [comment]
我也想问啊，那个多选假如做相应操作了该怎么去掉

**Comment by Leopoldthecoder** [comment]
#3436

**Comment by shuangmuyingzi** [comment]
比如是冻结全选项目，点击确认冻结或者取消之后把全选的状态去掉，是用clearSelection 吗，话说table Methods 是怎么用的啊？可以有个给个demo吗，谢过
