### ISSUE TITLE
dialog嵌套带 filter 的 table会出现 z-index 错乱

### ISSUE THREAD

**Issue by Sobranier** [ElemeFE/element#3319]
当在 dialog 中设置 table，并且待筛选功能，再次打开 dialog，z-index 会自动增加，但是筛选组件的 z-index 不能自动增加，造成看不到筛选的 filter
<img width="243" alt="2017-03-07 11 43 20" src="https://cloud.githubusercontent.com/assets/7440073/23641048/37564b8c-032c-11e7-8852-369870f31b08.png">

**Comment by trancelover** [comment]
类似的问题也出现在了 dialog 组件中，v-modal 层的 z-index 遮挡住了dialog 的父级组件，导致dialog 框也不可见了。
升级到 1.1.6之后 dialog 只能直接属于  body 元素了。使用大量dialog的老项目改动难度较大。

**Comment by Leopoldthecoder** [comment]
@trancelover 「dialog 只能直接属于 body 元素了」这个改动是 1.2.0 引入的，可以通过 `modal-append-to-body` 关闭。

**Comment by liuhg** [comment]
modal-append-to-body设为false并不能解决这个问题
