### ISSUE TITLE
[Table] Feature request for lazy loading

### ISSUE THREAD

**Issue by inoc603** [ElemeFE/element#332]
当table中数据较多时，页面渲染较慢，不知道是否有计划加入lazy loading功能，或者在固定table高度的时候只渲染可见的rows, 类似 [fixed-data-table](https://github.com/facebook/fixed-data-table)？

另外在行数较多时，固定table高度后，滚动的性能较差，是否能通过上面提到的的方法改善？

**Comment by furybean** [comment]
@inoc603 数据较多的概念是？现代浏览器中，1000条数据的性能还都是可以接受的。

**Comment by inoc603** [comment]
没有专门对不同数据量进行测试，我感到卡顿的时候表里有2000条数据，7列包括selection和一个inline-template的按钮。数据本身的获取和处理因为服务器在一台机器上，时间很短，没有大的影响。

我用的是最新版的chrome，简单地profile了一下，如下图。直观感受是除开页面其他内容，表格里的行大概花了3秒才渲染出来，固定高度时滚动的较慢，有较大延时。

![image](https://cloud.githubusercontent.com/assets/11290006/19296630/93e0b804-906f-11e6-9cbe-81815b8d0a70.png)

**Comment by furybean** [comment]
Table 目前正常重构，目前的版本我测试 7 列 2000 行数据，渲染速度在 1.5s 左右。滚动的卡顿在目前这种结构下是没办法优化的，只能用 fixed-data-table 的方式来优化。

目前大家对高性能的 Table 需求没有那么强烈，这种高性能的 Table 看后续是不是其他人有需求再来决定要不要加进来吧。

**Comment by furybean** [comment]
暂无精力实现，欢迎 PR。
