### ISSUE TITLE
el-table 在flex的子容器里不会自适应

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#3320]
### ElementUI version
1.2.3

### OS/Browers version
macOS/Chrome 56

### Vue version
2.2.1

### Reproduction Link
http://jsfiddle.net/egxa68x1/2/

### Steps to reproduce
打开上面的测试地址, 然后拉动中间的分隔条, 左拉时table的宽度会边大, 但是右拉时不会变小

**Comment by xiongsongsong** [comment]
试```flex:1 1 0;```而不是```flex:auto;```

**Comment by lincenying** [comment]
@xiongsongsong 漂亮...非常感谢...

**Comment by shanlh** [comment]
table外的div加overflow:hidden;就好了

**Comment by adntin** [comment]
这个问题有解决吗？@lincenying

**Comment by lincenying** [comment]
@adntin 看上面 shanlh 的回答...

**Comment by adntin** [comment]
应该在元素 flex: 1 内再加一个样式 overflow: hidden 就可以解决 @lincenying 谢谢

**Comment by dongjianghao** [comment]
使用`overflow:hidden; `有点危险，使用`min-width:0;` 也可以解决这个问题。

**Comment by tiantian010110** [comment]
为什么按照你们的操作都不行？
