### ISSUE TITLE
table 对safari不兼容吗？设置的宽度不能正常显示

### ISSUE THREAD

**Issue by jowang2016** [ElemeFE/element#3322]
设置了 table列的宽度，但是safari中样式显示错误，是不兼容吗？
我的这个问题就是这种情况，ElemeFE/element#2207 但是没有理解她的解决办法，她的colgroup好像是在源码中改的，所以我不知道在页面中应该调用什么命令，这个问题应该是一个bug，我的element table不仅表头和列在safari中不对应，底边滚动条也是失灵的，但是在chrome中一切都正常，，希望能够尽快修补这个bug！

**Comment by hellinnocence** [comment]
IE会出现横向滚动条

**Comment by jowang2016** [comment]
请问这个bug怎么解决啊？？

**Comment by reverland** [comment]
element版本？

**Comment by jowang2016** [comment]
"element-ui": "^1.1.6"

**Comment by jowang2016** [comment]
我安装了最新的 "element-ui": "^1.2.4" 在safari中仍然是那个问题

**Comment by reverland** [comment]
http://jsfiddle.net/xv286s14/2/

你是不是用了show-overflow-tooltip?

**Comment by jowang2016** [comment]
没有使用show-overflow-tooltip

**Comment by reverland** [comment]
@jowang2016 上面链接，假如不用overflow-tooltip是好的？

**Comment by jowang2016** [comment]
我没有用overflow-tooltip，但是也不行啊

**Comment by reverland** [comment]
所以你给个复现链接啊 @jowang2016

**Comment by jowang2016** [comment]
链接的代码看了，不用overflow-tooltip是好的，但是我的代码上没有使用overflow-tooltip，也没有好
我的代码如下
`<el-table
          :data="tableData"
          stripe
          style="width: 100%;font-size: 0.8rem;"
          :default-sort = "{prop: 'ref_date', order: 'descending'}">
          
          <el-table-column
            prop="ref_date"
            label="发布日期"
            sortable
            width="110">
          </el-table-column>
          <el-table-column
            prop="title"
            label="文章标题"
            width="180">
          </el-table-column>
          <el-table-column
            prop="target_user"
            label="推送人数"
            width="110">
          </el-table-column>
          <el-table-column
            prop="int_page_read_user"
            label="阅读人数"
            width="110">
          </el-table-column>
          <el-table-column
            prop="int_page_read_count"
            label="阅读次数"
            width="110">
          </el-table-column>
          <el-table-column
            prop="ori_page_read_user"
            label="原文阅读人数"
            width="120">
          </el-table-column>
          <el-table-column
            prop="ori_page_read_count"
            label="原文阅读次数"
            width="120">
          </el-table-column>
          <el-table-column
            prop="share_user"
            label="分享人数"
            width="110">
          </el-table-column>
          <el-table-column
            prop="share_count"
            label="分享次数"
            width="110">
          </el-table-column>
          <el-table-column
            prop="fav_user"
            label="收藏人数"
            width="110">
          </el-table-column>
          <el-table-column
            prop="fav_count"
            label="收藏次数"
            width="110">
          </el-table-column>
          
        </el-table>`
<img width="586" alt="wx20170320-101330 2x" src="https://cloud.githubusercontent.com/assets/18169317/24087124/ea3f443c-0d55-11e7-8aec-8e072a694730.png">

**Comment by reverland** [comment]
惨，并不知道发生了什么

**Comment by jowang2016** [comment]
难道这不是element自身的bug吗？能不能修复这个bug啊？之前我看到已经修复了，不过很明显bug依然存在，是否能进一步修复呢？

**Comment by reverland** [comment]
这个，首先需要一个复现链接，其次得有人愿意去修，再次愿意修的人能修……

**Comment by liuzhaowei55** [comment]
`width="60"` column这个参数定义的单位是什么啊?总觉得这个地方有问题的

**Comment by jowang2016** [comment]
复现链接？具体是什么？需要我提供吗？

**Comment by reverland** [comment]
@jowang2016 是的

**Comment by jowang2016** [comment]
要提供什么内容？怎样提供？提交到哪里？

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by jowang2016** [comment]
我提的问题就是一个bug呀

**Comment by reverland** [comment]
@jowang2016 按issue规范提

**Comment by avennn** [comment]
问题还没解决？

**Comment by zikuai** [comment]
我也遇到这个问题了，不过只在Safari下出现这个问题，其他浏览器倒是正常

**Comment by qiuyaofan** [comment]
刚遇到，当使用show-overflow-tooltip属性和minwidth在safari会出问题，我判断是safari添加样式代码解决的,然后宽度一定要比设置的表格列宽度小20，140就不行
```
<el-table-column prop="name" label="姓名"  :show-overflow-tooltip="true" width="140">
        <template v-slot="{row}">
          <span :class="{overflow:isSafria}">{{row.name}}</span>
        </template>
</el-table-column>

 computed: {
    isSafria() {
      const ua = navigator.userAgent.toLowerCase()
      return ua.indexOf('safari/') > -1 && ua.indexOf('chrome/') === -1
    }
  }

<style lang="scss">

  .overflow{
    text-overflow: ellipsis;
    width:120px;
    display: block;
    overflow: hidden;
    white-space: nowrap;
  }

</style>
```

**Comment by simon-woo** [comment]
给el-table-column添加了一个min-width解决了
![image](https://user-images.githubusercontent.com/33717252/97556463-7afcfb80-1a14-11eb-8cf7-5fdcb0a5868f.png)

`
<el-table-column
              prop="SameCount"
              label="操作"
              min-width="160"
            >
`
添加后
![image](https://user-images.githubusercontent.com/33717252/97556355-5012a780-1a14-11eb-9e39-c0c93a6474af.png)
