### ISSUE TITLE
使用table和tooltip的时候html标签会被转义，有什么办法可以避免么

### ISSUE THREAD

**Issue by xiaoguangma** [ElemeFE/element#3324]
### What is Expected?
tooltip中文字需要换行所以加了br标签  但是标签被转义了，换行效果没了
table中的a标签也是如此，虽然可以通过cell点击事件模拟

**Comment by lincenying** [comment]
tooltip 的问题看 http://element.eleme.io/#/zh-CN/component/tooltip `更多 Content` 的例子
table中可以使用html标签

**Comment by jikkai** [comment]
文档上有你要的答案。

提供一个最新版本的 Tooltip 组件自定义 content 解决方案，table 就交给你自己探索吧:-)
```vue
<el-tooltip ...>
  <div slot="content">
    <span>水</span><br/>
    <span>水</span><br/>
    <span>水</span>
  </div>

  <a>show tooltip</a>
</el-tooltip>
```

**Comment by yipeck** [comment]
可以试下:
<el-table-column label="地址">
    <template scope="scope">
        <div v-html="scope.row.address"></div>
    </template>
</el-table-column>

**Comment by yipeck** [comment]
这样可以解决：
`<el-table-column label="地址">
      <template scope="scope">
          <div v-html="scope.row.address"></div>
      </div>
</el-table-column>`
