### ISSUE TITLE
请问表格里面如何使用表单验证，如题看图

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#3326]
在线等，急~
求问表格里面如何使用表单验证可以动态添加的...
http://jsfiddle.net/nhykfzLy/

**Comment by lincenying** [comment]
表单验证的值要放在  <el-form :model="editForm", 里的`editForm`里.

**Comment by bihongbin3027** [comment]
我这上面有个例子 你能点进去帮我看下吗

**Comment by bihongbin3027** [comment]
还没解决 哪位朋友有时间帮看下

**Comment by lincenying** [comment]
你这种需求, 没法实现.

**Comment by jikkai** [comment]
@bihongbin3027 
瞄了眼没细看，一个是先把 prop 加上吧，比如姓名字段的 `<el-form-item label="姓名：" prop="name">`。还有一个是被验证的字段必须被`FormItem`组件包裹……问题有点多，不适合在 issue 讨论，建议先修改一下你的例子然后到 gitter 求助。

**Comment by bihongbin3027** [comment]
http://jsfiddle.net/nhykfzLy/3/
我没用el-table再里面使用表单了 我自己写了一个table标签 然后循环里面的tr 现在错误提示出来了 但是输入正确不会消失~

**Comment by bihongbin3027** [comment]
楼上 谢谢你 按照你这样做解决了
