### ISSUE TITLE
请教：Tooltip如何设置鼠标移动到tooltip弹出的内容上，弹出的内容不停留，会自动消失？

### ISSUE THREAD

**Issue by Longui** [ElemeFE/element#3327]
或者说只要鼠标离开，tooltip就隐藏！就算鼠标快速移动到tooltip上，tooltip还是会隐藏!

**Comment by lincenying** [comment]
官方的例子不就可以吗, 200ms内移过去.

**Comment by Longui** [comment]
我就是不想移过去了，还显示

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
