### ISSUE TITLE
el-table-column 如何添加此列的字符过滤器？

### ISSUE THREAD

**Issue by EasonYou** [ElemeFE/element#3329]
### ElementUI version

1.2.2
### OS/Browers version

Windows 10/ Chrome 56
### Vue version

2.2.1
### What is actually happening?
比如有一列性别
数据是0代表男，1代表女
在Vue中可以通过filter来过滤
可是看了文档好像并没有类似的功能
这要如何实现呢

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/gts0wdm1/

**Comment by EasonYou** [comment]
@PanJiaChen  感谢！
