### ISSUE TITLE
el-table-column 多级表头 隐藏列时  会出现渲染出错  怎么解决

### ISSUE THREAD

**Issue by pang-y** [ElemeFE/element#3330]
<el-table-column v-if="todos[10].checked"  label="净利润">
                <el-table-column  prop="date15" label="2014"></el-table-column>
                <el-table-column  prop="date16" label="2015"></el-table-column>
                <el-table-column  prop="date17" label="2016中"></el-table-column>
            </el-table-column>
            <el-table-column v-if="todos[11].checked" class-name="col14" label="利润增长率">
                <el-table-column prop="date18" label="2014"></el-table-column>
                <el-table-column prop="date19" label="2015"></el-table-column>
                <el-table-column prop="date20" label="2016中"></el-table-column>
            </el-table-column>

**Comment by DualWield** [comment]
@QingWei-Li 这个问题怎么说？我也碰到这个问题了

**Comment by DualWield** [comment]
@QingWei-Li 请问这个问题怎么说？我也碰到这个问题了

**Comment by DualWield** [comment]
https://jsfiddle.net/yedL9b8n/1/ 弄一个复现的demo

**Comment by lavyun** [comment]
这个bug会修复吗？我也遇到了，很麻烦，我一直以为是我代码的问题，查了半天的代码。

**Comment by DualWield** [comment]
@QingWei-Li 到时给个说法啊？

**Comment by ekoooo** [comment]
当列的显示状态改变时重新渲染整个表格，请看：https://jsfiddle.net/yedL9b8n/14/
