### ISSUE TITLE
el-table中某个el-table-column使用了fixed属性以后，template中的popover不工作？

### ISSUE THREAD

**Issue by angeltxwh** [ElemeFE/element#3332]
应用场景：
我使用的是1.2.3版本
在表格最后一栏使用popover来做操作提示
但是当操作这一栏被固定时，或者表格内有任意列被固定时，popover不能正常弹出了

在el-table-column当中的fixed="right"影响了popover绑定的v-model，在去掉以后可以正常运作
麻烦请教一下这是出于设计的考虑还是bug……谢谢啦

参考demo：
http://jsfiddle.net/f8rqagdm/3/

**Comment by Onlylonger** [comment]
element-ui@1.2.8
同样问题，求解答

**Comment by eddiebai** [comment]
我遇到了同样的问题

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/leopoldthecuber/f8rqagdm/12/

**Comment by BettyWong256** [comment]
问题原因：table中使用fixed实际上是叠加了一个table，在你点击popover的时候，就会触发table个数次，这个时候就可能会导致浮窗框创建了，然后又被关掉。 比如，你的表格只使用了fixed-left，那么就是两个表格，就会创建两次弹窗，触发v-model两次则依旧为false；如果fixed-left和right同时使用，则会又3个table，那么会创建3个弹窗，v-model触发三次则可以展示

**Comment by basejs** [comment]
同遇到问题，有解决办法么

**Comment by tanweijiu** [comment]
原来我不是唯一一个~~~~额~~~~

**Comment by Rays-wu** [comment]
> 应用场景：
> 我使用的是1.2.3版本
> 在表格最后一栏使用popover来做操作提示
> 但是当操作这一栏被固定时，或者表格内有任意列被固定时，popover不能正常弹出了
> 
> 在el-table-column当中的fixed="right"影响了popover绑定的v-model，在去掉以后可以正常运作
> 麻烦请教一下这是出于设计的考虑还是bug……谢谢啦
> 
> 参考demo：
> http://jsfiddle.net/f8rqagdm/3/
问题有解决方案吗 我看已经closed了

**Comment by jhd2015** [comment]
<el-popover v-model:visible="visible"  manual-mode> manual-mode手动控制popover开关 就可以解决

**Comment by jhd2015** [comment]
<el-popover v-model:visible="visible"  manual-mode> manual-mode手动控制popover开关 就可以解决

**Comment by jhd2015** [comment]
el-popover加上manual-mode 手动控制popover开关 就可以解决

**Comment by ydy0921** [comment]
按照官方【https://github.com/ElemeFE/element/issues/3332#issuecomment-362213788】这个方案，在el-table有多列(指定width)，出现横向滚动条时。这时弹出的popover窗会出现 两个偏移的问题。这个有什么方案解决

**Comment by ydy0921** [comment]
按照官方【https://github.com/ElemeFE/element/issues/3332#issuecomment-362213788】这个方案，在el-table有多列(指定width)，出现横向滚动条时。这时弹出的popover窗会出现 两个偏移的问题。这个有什么方案解决

**Comment by ydy0921** [comment]
按照官方的解决方案，
https://github.com/ElemeFE/element/issues/3332#issuecomment-362213788
在el-table有多列(指定width)，出现横向滚动条时。这时弹出的popover窗会出现 两个偏移的问题。这个有什么方案解决

**Comment by ydy0921** [comment]
按照给出的方案
https://github.com/ElemeFE/element/issues/3332#issuecomment-362213788】
在el-table有多列(指定width)，出现横向滚动条时。这时弹出的popover窗会出现 两个偏移的问题，或在滚动时出现。这个有什么方案解决不
