### ISSUE TITLE
Cascader 级联选择器不支持多选吗

### ISSUE THREAD

**Issue by saybye720** [ElemeFE/element#3333]
Cascader 级联选择器不支持多选吗？

**Comment by Leopoldthecoder** [comment]
不支持。

**Comment by KyoChou** [comment]
...回答的这么干脆. 有什么好的解决方法吗? 或者可以提供一下实现思路?

**Comment by saybye720** [comment]
@KyoChou 可以自己添加个变量用于接收每次Cascader选出来的结果

**Comment by Pearyman** [comment]
感觉这个场景还挺常见的

**Comment by LucasZheng** [comment]
强烈支持这个功能，很多开发场景需要

**Comment by sunchenguang** [comment]
感觉可以考虑增加这个特性，使用场景还是蛮多的吧，又想多选，又想是级联器的外观（用下拉选择的话看不出层级关系，不够清晰）

**Comment by zyqshanshui** [comment]
已有热心的小伙伴贡献了multi-cascader

https://github.com/newPromise/multi-cascader

**Comment by webCoderJ** [comment]
element的大佬们，支持一下把，产品急坏了，没时间开发~

**Comment by webCoderJ** [comment]
https://github.com/webCoderJ/el-multi-cascader  哈哈 还是得靠自己...

**Comment by Charming2015** [comment]
可以试一下这个：https://github.com/Charming2015/el-cascader-multi
基于element-ui的级联多选选择器，友好显示下拉箭头，样式与element一致，支持多选与级联选择器的大部分功能。

**Comment by gongzemin** [comment]
已支持 可通过 props.multiple = true 来开启多选模式
`https://element.eleme.io/#/zh-CN/component/select`
