### ISSUE TITLE
两个日期选择器，选择范围，怎么获取第一个日期选择器的值

### ISSUE THREAD

**Issue by csywweb** [ElemeFE/element#3334]
### ElementUI version
1.1.6

### OS/Browers version
macOS/Chrome 53
### Vue version
2.0.0-rc.4

### Reproduction Link
http://jsfiddle.net/mgvfn0nz/1/

### Steps to reproduce
时间选择，怎么设置第二个选择框的时间可选范围在第一个的日期到今天之间？不想使用那个局部的组件，因为跨度不一定是一个月。

**Comment by csywweb** [comment]
在disabledDate 中， this.$refs 拿不到开始时间input，

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/mgvfn0nz/2/

**Comment by csywweb** [comment]
@PanJiaChen 多谢， 输出了下this，没看到可用的东西。 给力的回复

**Comment by csywweb** [comment]
我之前试过用this.startTime获取第一个选中的时间，可是我报错。下面是我的代码。
![image](https://cloud.githubusercontent.com/assets/3185567/23654383/5b30e97e-036b-11e7-9102-7b46e9995c9c.png)

```
data (){
        return {
            pickerOptions0: {
              disabledDate(time) {
                return time.getTime() > Date.now();
              }
            },
            pickerOptions1: {
              disabledDate(time) {
                  return time.getTime()<this.startTime ||time.getTime() > Date.now();
              }
            },
            startTime:'',
            endTime:'',

        }
    }
```

**Comment by csywweb** [comment]
@PanJiaChen  多谢指点， 学到了。
