### ISSUE TITLE
[layout] 建议添加响应式显示/隐藏

### ISSUE THREAD

**Issue by zcyzcy88** [ElemeFE/element#3338]
### ElementUI version
1.2.3
http://element.eleme.io/#/zh-CN/component/layout#xiang-ying-shi-bu-ju

### What is Expected?
Bootstrap支持在某个viewport显示/隐藏内容 (http://getbootstrap.com/css/#responsive-utilities)
希望eleme也能支持

**Comment by baiyaaaaa** [comment]
下个版本支持将el-col的span 设为0，就可以隐藏了，敬请期待
