### ISSUE TITLE
如何 控制表单中 select 等非 text 组件的宽度

### ISSUE THREAD

**Issue by VolcanoOves** [ElemeFE/element#3340]

**Comment by VolcanoOves** [comment]
我在 input 外面套了一个 el-col 可以控制宽度。但是select这些的宽度怎么改变呢。

**Comment by VolcanoOves** [comment]
还有 InputNumber 的宽度

**Comment by VolcanoOves** [comment]
![image](https://cloud.githubusercontent.com/assets/18513530/23686659/da22f838-03e5-11e7-83c0-50b02ec18ce7.png) ...

**Comment by Leopoldthecoder** [comment]
自己通过 CSS 控制。
