### ISSUE TITLE
select选择器可以制定宽度就好了。。。

### ISSUE THREAD

**Issue by ldp5807279** [ElemeFE/element#3341]

**Comment by renxia** [comment]
简单的 css 样式自己写就是了

http://jsfiddle.net/nzjacrb5/

**Comment by ldp5807279** [comment]
是不是这些组件都可以加class来控制样式？

**Comment by Leopoldthecoder** [comment]
当然

**Comment by ldp5807279** [comment]
厉害了我的哥

**Comment by PLQin** [comment]
`Element-UI` 的 `el-select` 使用的其实是 `input` 标签 , 而 `input` 标签在浏览器中存在一个默认的宽度 , 大约是 **100px** (不同的浏览器表现不同) .

自定义的组件可以通过js来设置 `input `的 `width` 为 `auto` (hack方法)
```
function resizeInput() {
    $(this).attr('size', $(this).val().length);
}

$('input[type="text"]')
    // event handler
    .keyup(resizeInput)
    // resize on page load
    .each(resizeInput);
```  
> 出处 : https://stackoverflow.com/questions/8100770/auto-scaling-inputtype-text-to-width-of-value

---

而`Element-UI` 的 `el-select` 的话不如直接设置它的 `width` ( 如果坚持使用el-select的话 , 也的确别无他法 )  😞
```
<el-select placeholder="请选择" style="width:70%"></el-select>
或者
<el-select placeholder="请选择" style="width:120px"></el-select>
```
