### ISSUE TITLE
组件size=“small”时，组件高度尺寸不一致

### ISSUE THREAD

**Issue by Longui** [ElemeFE/element#3346]
![image](https://cloud.githubusercontent.com/assets/3948211/23689489/f548af4e-03f5-11e7-93a0-c16d76cb89e8.png)

button的size="small"与select的size="small" 高度相差2px
上图左边的是button（因为渲染速度问题，我使用了button来模拟select...），中间的是select

**Comment by Leopoldthecoder** [comment]
2.0 版本已统一。
