### ISSUE TITLE
How to merge cells in a table

### ISSUE THREAD

**Issue by beanLau** [ElemeFE/element#3349]
Invalid colSpan attribute for setting column。
for example：
`<el-table-column prop="fineCar" label="精车" :colspan="2"></el-table-column>`

Who can give me a solution.

**Comment by rshuzz** [comment]
@weitao901127 @QingWei-Li  我也碰到合并单元格的需求，不知道应该如何实现

**Comment by AnyGong** [comment]
现在的项目急需这样的功能，也是常见的功能

**Comment by flyingzl** [comment]
现在element-ui是不支持的，因为优先级较低，后续版本会支持

**Comment by weitao901127** [comment]
HTML tags can be used, for example
```
<td :colspan="val.colSpan" v-if="val.colSpan!=0" :style="{background:val.bg}">
    <div>{{val.data}}</div>
</td>
```

**Comment by rshuzz** [comment]
@weitao901127  surely, but we would like to use as Element components

**Comment by Leopoldthecoder** [comment]
Supported in 2.0: http://element.eleme.io/2.0/#/zh-CN/component/table#he-bing-xing-huo-lie
