### ISSUE TITLE
select性能问题

### ISSUE THREAD

**Issue by xiaoyang4011** [ElemeFE/element#3350]
https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue#L99
hoverItem使用indexOf去计算时，当数据量大的情况下回带来卡顿的情况
建议适应hash或者其他方式解决

**Comment by soliury** [comment]
对，这个问题在数据量大的时候特别卡顿

**Comment by kfeng0806** [comment]
我也出现了 一半在1000个开始就很卡了

**Comment by soliury** [comment]
目前发现一个bug，当vue升级到2.2.0以上时，使用select时，如果数据量大就卡的不行，我的是700条数据，在vue2.1.8上相当流畅，在vue2.2.0上特别卡，几乎是不能用

**Comment by Leopoldthecoder** [comment]
是的，之前优化过 Select，在 Vue 1.x 上不卡了。最近发现 Vue 2.x 又有些卡，原因不明。不过选项太多的话前端做一下过滤吧，几百上千个选项，用户选起来也不方便。

**Comment by reverland** [comment]
select这么多选项好像不太合适。。

**Comment by FAKER-A** [comment]
vue2.3.3,  element-ui1.4.4情况下  数据量300+ 页面就会变的非常卡

**Comment by havefive** [comment]
element-ui 2.4.11,同问

**Comment by FAKER-A** [comment]
> element-ui 2.4.11,同问

老哥这么多的数据使用远程搜索吧
