### ISSUE TITLE
发现el-upload组件的fileList不是双向绑定的？

### ISSUE THREAD

**Issue by angeltxwh** [ElemeFE/element#3353]
貌似file-list输入的这个数组只是用于显示？

当点击上传按钮成功上传一个文件后，el-upload组件并不会更新这个file-list是嘛？

这里是demo（成功上传后fileList没有更新）
https://jsfiddle.net/9swke6oq/

**Comment by baiyaaaaa** [comment]
vue数据流是单向的，prop名不是value的话哪来的双向绑定？

**Comment by angeltxwh** [comment]
@baiyaaaaa  那我应该如何实现上传后自动更新这个file-list啊，用on-success吗？

可是有个问题，我的el-upload是v-for出来的，我也不知道页面上会有多少个el-upload，也没有办法传一个值在on-success的方法中。。。。。

**Comment by lkiarest** [comment]
其实通过操作对象引用的方式是可以实现自动更新的， 只是不太符合单向数据流的设计

**Comment by lkiarest** [comment]
其实通过操作对象引用的方式是可以实现自动更新的， 只是不太符合单向数据流的设计

**Comment by leafiy** [comment]
魔改一下

```
watch:{

uploadFiles(){
    this.$emit('input', whatever)
}
}
```

**Comment by niusz** [comment]
> 貌似file-list输入的这个数组只是用于显示？
> 
> 当点击上传按钮成功上传一个文件后，el-upload组件并不会更新这个file-list是嘛？
> 
> 这里是demo（成功上传后fileList没有更新）
> https://jsfiddle.net/9swke6oq/

请问你后来怎么解决的呢？

**Comment by linglingj0** [comment]
> 

话是这么说😅，但是正常来说，props传入object的时候，子组件修改object内属性，父组件其实可以知道变化。
