### ISSUE TITLE
checkbox组件没有value值，如何实现全选？

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3358]
在循环item中使用checkbox组件，该如何实现全选？没有value属性，不能实现官网例子的多个checkbox使用同一个checkArr

![image](https://cloud.githubusercontent.com/assets/14192308/23698047/115c0d32-0425-11e7-91ab-abf0540b34af.png)

**Comment by ruofeng086** [comment]
使用原生input:checkbox元素实现了全选，但el-checkbox貌似暂时没能实现

[https://jsfiddle.net/ruofeng086/xb04phbr/](url)

**Comment by PanJiaChen** [comment]
是这个意思么？
http://jsfiddle.net/3c3ktwu0/

**Comment by ruofeng086** [comment]
![image](https://cloud.githubusercontent.com/assets/14192308/23702058/9d376464-0434-11e7-8f59-0d0c8d10d337.png)

类似这样的，item这一层是循环的，item内包含checkbox ，和其他元素，el-check-grounp不能进行魂环吧？

[](https://jsfiddle.net/ruofeng086/xb04phbr/)

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/3c3ktwu0/1/
这和你用原生有什么区别么。。。

**Comment by ruofeng086** [comment]
好的，感谢，有一点疑问，el-checkbox-group的v-model挂载那里的呢？每个item里的el-checkbox吗？el-checkbox-group生成的dom元素是div，所以开始没想到还能这么使用，没明白具体实现。

**Comment by ruofeng086** [comment]
还有一个就是，不指定的label就不能实现全选了，有没有不显示label的属性？

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/issues/647

**Comment by ruofeng086** [comment]
Thanks， but this can't resolve problem.
