### ISSUE TITLE
upload的ajax能否使用自己的ajax逻辑呢？

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/element#3359]
### ElementUI version
1.2.3

### OS/Browers version
macOS/Chrome 53 

### What is actually happening?

我比如我希望在上传的时候继承oss或者bos这样百度或者阿里的网盘的时候，或者使用我们公司自己的网盘的时候，需要使用我们自己的上传sdk，这个时候需要提供一个file对象

**Comment by baiyaaaaa** [comment]
暂时还不支持这个功能，后续的版本有计划支持，敬请期待

**Comment by yuchonghua** [comment]
@baiyaaaaa 我能通过pr去给你写这个支持吗

**Comment by baiyaaaaa** [comment]
@yuchonghua  非常欢迎

**Comment by yuchonghua** [comment]
fork是dev分支吗

**Comment by reverland** [comment]
wow，支持手动上传了

**Comment by baiyaaaaa** [comment]
@yuchonghua 是的

**Comment by yuchonghua** [comment]
@baiyaaaaa  https://github.com/ElemeFE/element/pull/3363

**Comment by yuchonghua** [comment]
@liril-net 下一版本大概什么能发布呢？

**Comment by yuchonghua** [comment]
@liril-net https://github.com/ElemeFE/element/pull/3389 已经在这个实现，因为被[pr](https://github.com/ElemeFE/element/pull/3387)
