### ISSUE TITLE
elementui table有没有动态列设置？

### ISSUE THREAD

**Issue by zhangwei900808** [ElemeFE/element#3360]
公司有需求需要设置table的列显示和隐藏，请问下有没有这种功能，如果没有，我该如何修改源码？

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/issues?utf8=%E2%9C%93&q=involves%3APanJiaChen%20

**Comment by PanJiaChen** [comment]
#3077

**Comment by zhangwei900808** [comment]
不是这种，是点击选择列的时候可以弹出一个框，让我自己选择是否显示哪个！而不是代码控制 @PanJiaChen

**Comment by PanJiaChen** [comment]
写了一个简单的例子
具体的自己优化吧
http://jsfiddle.net/n2u5ejuz/1/

**Comment by zhangwei900808** [comment]
@PanJiaChen 对的就是这种效果，但是能不能直接嵌入到el-table-column中呢？不好意思现在才看到回答
![qq 20170309153045](https://cloud.githubusercontent.com/assets/4385154/23740600/51beaa14-04df-11e7-8854-6567bc3a7080.png)

**Comment by PanJiaChen** [comment]
参见
https://github.com/ElemeFE/element/issues/1569

**Comment by zhangwei900808** [comment]
@PanJiaChen 好的，我先试试哈，非常感谢你

**Comment by cuitianze** [comment]
https://github.com/ElemeFE/element/issues/3919

多级表头方便控制么

**Comment by LanmanGuy** [comment]
> 写了一个简单的例子
> 具体的自己优化吧
> http://jsfiddle.net/n2u5ejuz/2/

这个链接访问不了了,方便把代码贴出来么
