### ISSUE TITLE
tabs中el-tab-pane包含v-if指令会导致位置错乱

### ISSUE THREAD

**Issue by sx1989827** [ElemeFE/element#3370]
http://jsfiddle.net/nghz4pgn/

你好 ，在tabs中el-tab-pane包含v-if指令的时候，tab的位置不会按照原先的顺序排列

**Comment by thomasyonug** [comment]
我用最新的dev分支，试了一下，没有这个bug。可能是unpkg上面的库版本有点问题

**Comment by sx1989827** [comment]
公司目前用的就是unpkg上面的库，还请能修复这个问题！

**Comment by thomasyonug** [comment]
我不是管理者。已经加bug标签了，估计马上就解决了

**Comment by sx1989827** [comment]
@liril-net 你好 问一下 这个问题什么时候可以修复~

**Comment by liril-net** [comment]
用 `v-show`，因为 `v-if` 渲染顺序的问题

**Comment by tanhuiya** [comment]
请问这个问题怎么解决的，用v-show代替v-if 会导致其它的bug

**Comment by liril-net** [comment]
什么样的问题？

**Comment by tanhuiya** [comment]
```
<el-tab-pane label="个人信息" name="first">
       <AAA></AAA>
 </el-tab-pane>
 <el-tab-pane v-show="showCourse" label="课程详情" name="second">
       <BBB></BBB>
</el-tab-pane>
```

使用v-show 的话，BBB组件会被渲染到AAA组件下面，也就是第一个tab里

**Comment by tanhuiya** [comment]
@liril-net

**Comment by Leopoldthecoder** [comment]
Fixed in #6066

**Comment by gaopeng0108** [comment]
可以在el-tab-pane的外层包裹一个div标签，将v-if放到div上即可解决位置错乱的问题

**Comment by xiaoqi167** [comment]
试了外层包裹一个DIV标签也是不行，请问现在这个问题解决了吗？

**Comment by xiaoqi167** [comment]
> 我也遇到了相同问题.用v-if 显示会位置会错乱,用v-show没有办法控制达到隐藏tab分页的目的.
已解决

**Comment by hillwah** [comment]
> > 我也遇到了相同问题.用v-if 显示会位置会错乱,用v-show没有办法控制达到隐藏tab分页的目的.
> > 已解决

可怕的“已解决”。是否能分享一下解决方法呢？

**Comment by Liberty666** [comment]
请问

> 
> 
> > > 我也遇到了相同问题.用v-if 显示会位置会错乱,用v-show没有办法控制达到隐藏tab分页的目的.
> > > 已解决
> 
> 可怕的“已解决”。是否能分享一下解决方法呢？

请问这个怎么解决的？

**Comment by reavenlin** [comment]
> 请问
> 
> > > > 我也遇到了相同问题.用v-if 显示会位置会错乱,用v-show没有办法控制达到隐藏tab分页的目的.
> > > > 已解决
> > 
> > 
> > 可怕的“已解决”。是否能分享一下解决方法呢？
> 
> 请问这个怎么解决的？



> 用 `v-show`，因为 `v-if` 渲染顺序的问题

跟v-show, v-if 无关，在v-for 中 :key 使用索引而不要使用元素属性就好了。
