### ISSUE TITLE
[button]单个按钮和按钮组一起排放不对齐

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#3374]
图：![image](https://cloud.githubusercontent.com/assets/12726826/23733586/bf3f6f22-04b4-11e7-9758-1b74364f97f8.png)
demo：
http://jsfiddle.net/n5nLywqp/

**Comment by QingWei-Li** [comment]
手动写样式覆盖下就好了

**Comment by lry210** [comment]
是的，我现在就是样式覆盖，对我而言没什么问题，我只是站在你们产品的角度提意见的，嘻嘻

**Comment by zcyzcy88** [comment]
http://stackoverflow.com/questions/17905827/why-does-my-image-have-space-underneath

**Comment by QingWei-Li** [comment]
嗯 还是手动覆盖吧
