### ISSUE TITLE
<el-table-column></el-table-column> 列标题区域背景色怎么玩

### ISSUE THREAD

**Issue by sunyuanfei** [ElemeFE/element#3375]

**Comment by PanJiaChen** [comment]
加一个class 样式覆盖就好了
http://jsfiddle.net/pmehuuom/1/

**Comment by sunyuanfei** [comment]
全局配置element-ui 我也参照文档class-name 还是没有变
th.date{
        background-color:red;
    }
    th.date div{
        background-color:red;
    }

<el-table border :data="firsts">
                <el-table-column label="变速器描述" class-name='date' align="center" prop="transmission_description"></el-table-column>
                <el-table-column label="波箱型号" align="center" prop="old_transmission"></el-table-column>
                <el-table-column label="油品型号" align="center" prop="new_transmission"></el-table-column>
            </el-table>

**Comment by Even-Lau** [comment]
如果要更改el-table某一行的背景色，该怎么处理

**Comment by PanJiaChen** [comment]
@Even-Lau https://jsfiddle.net/b2p7gfd1/
