### ISSUE TITLE
使用el-submenu中的slot来渲染菜单出现slot重复警告

### ISSUE THREAD

**Issue by xiaoguangma** [ElemeFE/element#3376]
### What is Expected?
使用el-submenu中的slot来渲染菜单出现slot重复警告

代码
         `<el-menu class="el-menu-vertical-demo" unique-opened router :class="{'toggled': sidebarToggled}" :default-active="$route.path">
            <template v-for="(menu, index) in menus">
              <el-submenu :index="index + ''">
                <template slot="title"><i class="el-submenu__icon fa fa-dashboard"></i><span class="el-submenu__name">{{menu.name}}</span></template>
                <el-menu-item v-for="child in menu.children" :index="child.path"><span class="el-menu-item__name">{{child.name}}</span></el-menu-item>
              </el-submenu>
            </template>
          </el-menu>`

firebug控制台输出
[Vue warn]: Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors. 
(found in <ElMenu>)
http://localhost:8080/app.js line 724 > eval
Line 565

[Vue warn]: Duplicate presence of slot "title" found in the same render tree - this will likely cause render errors. 
(found in <ElSubmenu>)
http://localhost:8080/app.js line 724 > eval
Line 565

**Comment by Leopoldthecoder** [comment]
给一下 demo

**Comment by xiaoguangma** [comment]
@Leopoldthecoder  
github地址https://github.com/ElemeFE/element-dashboard
登录之后进入首页（此时不报错）  刷新浏览器后会报错

**Comment by susansjy** [comment]
我也碰到了，很奇怪是在一个特定的页面，刷新后才会出现。

**Comment by xiaoguangma** [comment]
@susansjy  这个问题应该是使用了watch导致的  我的代码加入vuex之后去掉了watch自动解决了
