### ISSUE TITLE
upload上传图片有问题

### ISSUE THREAD

**Issue by unique542** [ElemeFE/element#3379]
问题1：upload手动上传图片，没有预览效果
问题2：多文件上传其实是提交多次，并不是一次提交多个文件
问题3：图片和文件不支持数据流上传
问题4：input[type=file]时，php做为服务器后台，需要name属性，获取文件，现在没有name属性

**Comment by kfeng0806** [comment]
浏览效果你可以自己通过file 的getDataURL方法来获得文件(图片)的blob地址

一般来说ajax上传提交多次是正常的

获取文件要用files

**Comment by kfeng0806** [comment]
补充一下 获取图片blob地址的方式是 
const url = URL.createObjectURL(file)

数据上传你直接post base64 string到服务器也没差 这两张不太好融合

**Comment by maxwelltsai1536** [comment]
upload能不能拓展一下 例如我想在图片下方加一点别的参数 启用/禁用 图片说明 语言之类的呢

**Comment by baiyaaaaa** [comment]
@maxwelltsai1536 你可以自己去处理 fileList

**Comment by baiyaaaaa** [comment]
upload手动上传图片，没有预览效果指的是 list-type="picture" 的模式么？

**Comment by jinjinwa** [comment]
上传图片没有预览效果，指的应该是预览当前选择的图片。
目前没有选择完图片之后的钩子函数，没有办法实现在选择完本地图片之后立即预览

**Comment by 547437352** [comment]
@kfeng0806 请问怎么把file的图片转化成base64呢，我before-upload中输出file发现只有图片的信息，应该怎么操作呢

**Comment by kfeng0806** [comment]
@547437352 那个file应该是file object 直接按照一般js file object的方式操作就可以了

**Comment by baiyaaaaa** [comment]
1. 最新版本已解决
2. 暂时没有考虑支持多文件同时上传的打算
3. 数据流上传不在我们的设计当中
4. 实际上是支持设置 name 属性的
