### ISSUE TITLE
Tree组件能否增加功能

### ISSUE THREAD

**Issue by liuzhibin123** [ElemeFE/element#3381]
我们现在项目需求 。
 要把选中的节点key，跟选中节点的父节点已经以上所有的父节点的key都获取到。

目前贵框架 还没有这个功能。急需你们帮忙解决。

**Comment by meteorfall** [comment]
我觉得可以自己写个搜索树的js函数，就可以得到了。
如果树太大，觉得效率低，需要把父节点路径作为属性预置到节点，就方便了。

**Comment by qwvpn** [comment]
没错还是我。
Tree组件在渲染数据比较多时比较卡，比如城市地区(县级单位)级联，一次性全部渲染操作会有点卡。改为lazy懒加载后，父节点不能预知子节点选中情况，所以父节点选中状态无法确定。
建议在lazy加载tree列表添加以下功能：
1.能通过手动配置节点checkbox状态，未选中，半选中，全选中
2.可手动配置节点下拉展开状态,比如0表示不可展开也就是没有三角形箭头,1表示可以展开

**Comment by liuzhibin123** [comment]
http://jsfiddle.net/leopoldthecuber/yu2me25j/    这个里面有方法   自己按需求  可以获取到，

**Comment by qwvpn** [comment]
@QingWei-Li
看下我的建议啊
