### ISSUE TITLE
列标题背景色、行不需要点击、触摸高亮

### ISSUE THREAD

**Issue by sunyuanfei** [ElemeFE/element#3383]
没有改变 我有参照文档  vue2.0+webpack

<el-table-column label="变速器描述" class-name='date' align="center" prop="transmission_description"></el-table-column>

     th.date{
        background-color:red;
    }
    th.date div{
        background-color:red;
    }

**Comment by Leopoldthecoder** [comment]
给一下 demo

**Comment by sunyuanfei** [comment]
<div class="content">
            <el-table border :data="firsts">
                <el-table-column label="变速器描述" class-name='date' align="center" prop="transmission_description"></el-table-column>
                <el-table-column label="波箱型号" align="center" prop="old_transmission"></el-table-column>
                <el-table-column label="油品型号" align="center" prop="new_transmission"></el-table-column>
            </el-table>
            <el-table border :data="seconds">
                <el-table-column label="换油方式" align="center"prop="change_oil"></el-table-column>
                <el-table-column label="原厂初装用量" align="center" prop="amount_init"></el-table-column>
                <el-table-column label="重力换油分量" align="center" prop="amount_gravity"></el-table-column>
            </el-table>
            <el-table border :data="thirds">
                <el-table-column label="全自动循环换油量" align="center" prop="automatic"></el-table-column>
                <el-table-column label="适用孚罡差速器油" align="center" prop="transfer_gear"></el-table-column>
                <el-table-column label="适用孚罡分动箱油" align="center" prop="differentital_oil"></el-table-column>
            </el-table>
            <el-table border :data="forths">
                <el-table-column label="滤网型号" prop="joint_url">
                    <template scope="scope">
                        <div class="check" @click="imageShow(scope.row.filter_url)">
                            点击查看图片
                        </div>
                    </template>
                </el-table-column>
                <el-table-column label="油底垫型号" prop="filter_url">
                    <template scope="scope">
                        <div class="check" @click="imageShow(scope.row.joint_url)">
                            点击查看图片
                        </div>
                    </template>
                </el-table-column>
                <el-table-column  label="接头型号" prop="oil_url">
                    <template scope="scope">
                        <div class="check" @click="imageShow(scope.row.oil_url)">
                            点击查看图片
                        </div>
                    </template>
                </el-table-column>
            </el-table>
        </div>

**Comment by Leopoldthecoder** [comment]
demo 的意思是使用 jsfiddle 写一个在线例子

**Comment by sunyuanfei** [comment]
不是 我是整个vue项目

**Comment by Leopoldthecoder** [comment]
无法重现的话是没有办法找到问题的。

**Comment by sunyuanfei** [comment]
[huohuasai.zip](https://github.com/ElemeFE/element/files/829930/huohuasai.zip)

**Comment by Leopoldthecoder** [comment]
你压缩包里的这个项目没有使用 Element

**Comment by sunyuanfei** [comment]
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
Vue.use(ElementUI)

**Comment by sunyuanfei** [comment]
"element-ui": "^1.2.3",

**Comment by sunyuanfei** [comment]
![image](https://cloud.githubusercontent.com/assets/7675592/23738622/076961ac-04d5-11e7-8699-ca394ce1c13a.png)

**Comment by sunyuanfei** [comment]
是什么原因导致class-name设置 没有执行

**Comment by sunyuanfei** [comment]
那怎么去掉触摸、点击等事件产生行变色 -----我希望就是数据表格展示不需要行一些事件导致背景色变成你们设置默认的#eef1f6 难道没有属性去除事件响应?

**Comment by sunyuanfei** [comment]
算了 我直接该默认样式表  果然能相信的只有自己
