### ISSUE TITLE
如何添加el-table-column鼠标移动或者点击事件？

### ISSUE THREAD

**Issue by zhangwei900808** [ElemeFE/element#3386]
我想操作表格的表头，现在只有点击事件，但是我想使用鼠标滑动上面就触发事件，这个怎么解决？

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
