### ISSUE TITLE
Nav menu点击菜单标题展开子菜单  然后点击栏目触发原生click事件.当第二次（及多次）点击标题时，会触发下面栏目的绑定事件

### ISSUE THREAD

**Issue by HelTi** [ElemeFE/element#3388]
### ElementUI version
1.2.3

### OS/Browers version

win7 Chrome 56
### Vue version
2.2.1
##无语了，还是给个demo吧

[demo](https://jsfiddle.net/5wc9ajL1/)

**Comment by PanJiaChen** [comment]
触发的原因主要是sub-menu close之后在打开 display状态从none到block
会重新触发你的show动画，所以在动画结束之后移除或者sub-menu close的时候remove 所有的show class就好了

**Comment by HelTi** [comment]
现在解决的办法是 自定义指令
