### ISSUE TITLE
el-tabs组件数据无法更新问题

### ISSUE THREAD

**Issue by pizijun** [ElemeFE/element#339]
1. 使用的技术栈是vue 2.0,vue-router 2.0, vuex 2.0,element-ui 1.0-rc.4，数据是用mockajax模拟的

2. bug复现步骤，可以点击这个链接[http://pizijun.github.io/normandy/dist/index.html#/manage/role](http://pizijun.github.io/normandy/dist/index.html#/manage/role)进行操作 :
  - 进入页面，点击表格中第二行的‘修改角色’按钮
  - 页面跳转并请求tab所需要的数据，点击‘修改应用’按钮后弹框
  - 勾选要改变的数据，点击确定后上面的tab组件数据得到更新，下面的则没有。（note:为了产生对比效果，上面的tab组件是自己实现的一个简单tab组件，下面的是el-tabs）

**Comment by Leopoldthecoder** [comment]
可以看到两者的区别。请提供代码方便我们定位问题， 可以使用 https://jsfiddle.net/gmve9d3p/

**Comment by pizijun** [comment]
https://jsfiddle.net/zejun/m10956fq/15/

**Comment by furybean** [comment]
和 #407 是同一个问题。
