### ISSUE TITLE
关于表单验证问题，我写了个例子，在线等..

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#3390]
http://jsfiddle.net/96bffec2/

这种表单为什么验证不了呢，就算我输入的是正确的值，然后我点按钮，我在输入正确代码加了这个console.log('ok')，但是我实际输入正确的时候，并没有弹出'ok'~
请问该怎么解决呢？

**Comment by Leopoldthecoder** [comment]
你的自定义校验函数里，对于合法的输入值没有调用 callback：http://jsfiddle.net/96bffec2/2/

**Comment by bihongbin3027** [comment]
谢谢 你解决了我的大问题
