### ISSUE TITLE
upload组件的on-progress钩子函数不能获取到完整的上传进度值。

### ISSUE THREAD

**Issue by chqfly** [ElemeFE/element#3392]
### What is actually happening?

我利用on-success和on-progress实现了上传进度条。 我在on-progress回调里面写了：handleUploadProgress(event,file,fileList) { 
     for(let i = 0, len = fileList.length; i < len; i++) {
          if(Math.floor(fileList[i].percentage) <90){ 
                   fileList[i].statusDesc = '文件上传中...'; 
               }else{
                   fileList[i].statusDesc = '文件转换中...';
               }
           } 
           this.uploadFileList = fileList;
 }
但是else里面的代码始终不会被执行，奇怪的是进度条里面又显示了100%. 

这是为什么啊？

**Comment by baiyaaaaa** [comment]
上传太快了吧，你可以设一下浏览器的 throttling 看看

**Comment by lichenhao** [comment]
同样的问题。。获取的progress是100%

**Comment by guohuihot** [comment]
我的也是不执行，好坑

**Comment by Mr-Raindrop** [comment]
file 和fileList中percent永远是100%

**Comment by guohuihot** [comment]
可能是mockjs
