### ISSUE TITLE
表格支持输出html吗？

### ISSUE THREAD

**Issue by milu2003** [ElemeFE/element#3393]
```
<el-table-column :formatter="table_format_html"  prop="html" label="内容" width="auto">
```

就是这个。我想输出html。比如链接什么的，看了文档没发现有相关参数。请指点一下，谢谢。

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/zfn8xusc/

**Comment by milu2003** [comment]
谢谢，我正好也找到了答案。

![image](https://cloud.githubusercontent.com/assets/15957433/23749307/8891544c-0502-11e7-8d4e-edf924c71d56.png)
