### ISSUE TITLE
NavMenu 能否监测url动态触发导航菜单

### ISSUE THREAD

**Issue by lzl529** [ElemeFE/element#3394]
![image](https://cloud.githubusercontent.com/assets/16254369/23748864/5d0c3906-0500-11e7-81cb-32b262f351ad.png)
如果不点击导航菜单上的按钮，在用this.$router.push()改变url的时候可以动态触发导航菜单的active样式么（比如：二级菜单展开）

**Comment by liril-net** [comment]
可以自己实现这个逻辑

**Comment by lzl529** [comment]
额，解决了，通过调用实例里边的open/closeMenu方法和activeIndex属性来实现动态控制，不知道合不合适，效果是实现了。
