### ISSUE TITLE
Feature Request: Param to disable tooltip on Slider

### ISSUE THREAD

**Issue by gabrielboliveira** [ElemeFE/element#3397]
### ElementUI version
1.2.4

### OS/Browsers version
macOS Sierra 10.12.3/Chrome 56

### Vue version
2.2.2

### What is Expected?
Please, add an option to disable the tooltip showing/hiding on the Slider. I think it would be good to have the option to show only the draggable slider, without any other element.

Related to #2316

**Comment by Leopoldthecoder** [comment]
Thanks for contributing.
