### ISSUE TITLE
Upload可否由我们使用者拓展

### ISSUE THREAD

**Issue by maxwelltsai1536** [ElemeFE/element#3398]
我想在Upload的下方加一些额外数据 例如 启用/禁用、排序、图片说明之类的  我们可否在upload放基础之上拓展这个呢 因为现在upload还是挺好用的 只不过我们还需要一些额外的功能 谢谢

**Comment by kfeng0806** [comment]
你完全可以根据各种事件回调的file和filelist来实现你上面所说的功能
你提到的那些功能跟upload该做的事并没有太大关联
