### ISSUE TITLE
el-switch 不更新不在data()中初始化的值

### ISSUE THREAD

**Issue by zdpeitang** [ElemeFE/element#3399]
### ElementUI version

1.2.3

### OS/Browsers version

Ubuntu 16.04, Chrome 56

### Vue version

2.2.2

### Reproduction Link

use computed: http://jsfiddle.net/zjh54jth/
use mounted(): http://jsfiddle.net/wppdrt6c/

### Steps to reproduce
1. 在data()中创建空值
2. 在别处填充空值（例如mounted())，数据为bool型

### What is Expected?
数据可以被el-switch更新

### What is actually happening?
数据不被el-switch更新，但是触发其他更新view的事件可以让view更新

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/wppdrt6c/2/
你这不是element的问题
详细请看https://cn.vuejs.org/v2/guide/reactivity.html

**Comment by Chicago555** [comment]
请问这个问题解决了吗  ？？？
我在vuex里的getter定义它的初始值也会出现问题：点击时出发了Boolean值的改变  但是样式不是正常变化；
