### ISSUE TITLE
表单验证文档

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#340]
表单验证这块在后台还是比较重要的，但是文档对于这块的介绍很少，起码应该有默认验证规则有哪些，如何添加自定义验证（虽然有个简单的例子），服务器端验证怎么做，延迟验证怎么做？如果这些都暂时不在开发计划中，那么如何和现有的整合等等这些问题。

**Comment by lyseky** [comment]
@erguotou520 you can you up

**Comment by furybean** [comment]
@baiyaaaaa

**Comment by acelan86** [comment]
简单看了下源码的部分，基础用的是这个，po主可以先了解下：https://github.com/yiminghe/async-validator
还没开始做表单验证的深入使用，占楼马克

**Comment by reverland** [comment]
话说，用vuex单独做一层来做表单验证好像也不错的样子

**Comment by ty19105** [comment]
表单验证如果有默认数据的话每次都是验证错误，怎么办

**Comment by erguotou520** [comment]
@ty19105 这就需要验证模块具有延迟验证的功能了

**Comment by zengsun** [comment]
我也在看表单验证，但是规则语焉不详！
