### ISSUE TITLE
建议: Upload组件增加并发上传数设置

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#3403]
在http/2.0下多个请求会在一个TCP连接下发送 例如在nginx下默认是一个TCP连接内允许并发128个请求, 浏览器(Chrome为例)的并发连接上限是6个

那么代表当在多选条件下选择上百个文件的话所有请求都会同步发送到服务器,不像http/1.1一个请求一个连接,会被浏览器限制到6个左右, 最近遇到这个问题的结果是选择大量(数百个)文件上传的时服务器内存被一堆并发请求文件塞爆了.... 

希望下个版本可以让upload组件设置一个最大并发上传数限制 并发满的时候后面的文件放在上传队列里等待前面的上传完成了再进行后面的

**Comment by hpyer** [comment]
或者增加一个开关选项，开启后可以支持多个文件在同一个请求中上传～

**Comment by csvwolf** [comment]
Now u can use `http-request` to  custom upload method.
