### ISSUE TITLE
建议：开发一些组件

### ISSUE THREAD

**Issue by rongxingsun** [ElemeFE/element#3404]
建议开发组件
1。Transfer穿梭框
2。Affix图钉
3。BackToTop返回顶部
4。Timeline时间轴
5。LoadingBar加载进度条

**Comment by kfeng0806** [comment]
进度条已经有了吧
返回顶部一行代码的问题没必要组件
穿梭选择也有
总之先看完文档吧

**Comment by rongxingsun** [comment]
穿梭选择没有
加载进度条也没有啊（npropress）
时间轴和affix图钉是确定没有哦

**Comment by kfeng0806** [comment]
ajax进度条两行代码几行css的事这种独立搞个组件没必要吧

**Comment by FlappyHeart** [comment]
**暂时**建议你换个库，或者组合多个库来试试，每个库能覆盖的组件都有限，没法尽如人意。

**Comment by baihe** [comment]
2,3,5 是常见的需求。我们自己用都是直接从iview和vue-beauty等拷贝整合进来的。

**Comment by yugasun** [comment]
@rongxingsun 可以按照 @baihe 说的，从iview的源码中提取timeline, LoadingBar等组件整合，毕竟暂时element-ui还没有，我们暂时也是这么做的。

**Comment by hasbug** [comment]
官方的更新通知用了timeline，何不整合进来？ 其实大家都不愿意在一个项目整合好几个UI库，到时候维护成本大

**Comment by egyptik** [comment]
+1 Would love to have a timeline component as well. I don't speak Chinese, but was thinking it can be based on the 'Steps' component, specifically the 'Vertical step bar'.

**Comment by terehov** [comment]
yes, timeline would be really great!

**Comment by ibufu** [comment]
need timeline.

**Comment by liril-net** [comment]
已移到需求池中。

Moved to product backlog.

**Comment by mvity** [comment]
LoadingBar 确实该加上

**Comment by iamshen** [comment]
建议穿梭框 可以设置 单选、多选的
