### ISSUE TITLE
小bug：Select 选择器-远程搜索-不加multiple-remote-method延迟问题

### ISSUE THREAD

**Issue by littlefire-sheng** [ElemeFE/element#3408]
![image](https://cloud.githubusercontent.com/assets/20022183/23778123/7b7a11ec-0573-11e7-8bb3-b9af8ed19d33.png)
**---Select 选择器-远程搜索-不加multiple-remote-method延迟问题---**
如上图，输入框是空的情况，在中文输入法中，我打个c，然后回车，输入英文c，remote-method方法不会被触发
当输入框是非空的情况，在中文输入法中，我打个c，然后回车，输入英文c，remote-method方法就会被触发

**Comment by Leopoldthecoder** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10095631/23779924/65473fb6-057e-11e7-8adf-1baf425dacc4.gif)
可以试试这个 demo：https://jsfiddle.net/fqtkswne/ 。上面的截图是我这边运行这个 demo 的结果，如果这个 demo 在你那边也有问题，那么应该是输入法的行为不同导致的，不算 Element 的 bug。
