### ISSUE TITLE
form表单验证好像不支持el-form-item 同时验证二个字段吧prop只可以传递一个

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#3409]
![qq 20170310094530](https://cloud.githubusercontent.com/assets/16487810/23778607/27d7f25e-0576-11e7-99fa-6437d1257a7f.png)
如图，一行里面需要验证二个字段值

**Comment by killdada** [comment]
试了下。自定玉验证里面可以判断二个，但是一个没填二个字段都标红了，我修改下样式把

**Comment by Leopoldthecoder** [comment]
是的，如果一定要在同一个 el-form-item 里放多个字段，需要自己 hack 一下。
