### ISSUE TITLE
Tree 组件在Lazy模式下，setCheckedKeys或者setCheckedNodes有Bug

### ISSUE THREAD

**Issue by Molunerfinn** [ElemeFE/element#3410]
### ElementUI version

v1.2.3
### OS/Browsers version

Chrome 56
### Vue version

v2.2.1
### Reproduction Link

https://jsbin.com/nuwiviluhu/edit?html,js,output
### Steps to reproduce
当Lazy模式下，通过setCheckedKeys\Nodes的方法，第一次会让所有的节点都被Checked，再次点击后才正常。
### What is Expected?
应该是设置哪个节点就选中哪个节点。
### What is actually happening?
当Lazy模式下，通过setCheckedKeys\Nodes的方法，第一次会让所有的节点都被Checked，再次点击后才正常。

**Comment by thomasyonug** [comment]
这段代码看的实在头疼，好难修啊，有没有人来解决它。

**Comment by pcloth** [comment]
ElementUI version

v1.2.4
OS/Browsers version

Chrome 56

通过直接html代码调试（官方文档http://element.eleme.io/#/zh-CN/component/tree#shu-jie-dian-de-xuan-ze）
树节点超过10个，用setCheckedKeys或者setCheckedNodes均会定位到10号节点，并选中10号节点。

**Comment by forzalianjunting** [comment]
遇见了同样的问题，请问什么时候能修复这个bug？ @Leopoldthecoder

**Comment by forzalianjunting** [comment]
源码实在有点改不动，哪位大神来处理下这个bug @Leopoldthecoder @QingWei-Li @baiyaaaaa @furybean

**Comment by yangjunjun** [comment]
也遇到这样的问题了， 求修复。

**Comment by Leopoldthecoder** [comment]
已在 1.4.0 修复
