### ISSUE TITLE
多文件上传、不能上传到七牛 -.-

### ISSUE THREAD

**Issue by 794203586** [ElemeFE/element#3412]
多文件上传、不能上传到七牛 -.-

七牛每次上传都需要一个key
但是饿了吗上传控件、不能修改data里的值

**Comment by hasbug** [comment]
哥们，可以做到的，在upload-before里使用Promise去做就行了，这几天我才解决了这个问题

**Comment by 794203586** [comment]
能否。发个代码参考一下

**Comment by kfeng0806** [comment]
@hasbug 能否用这种方法阻塞多选文件上传? 比如选择100个上传同时只传5个 后面的阻塞等待前面的传完再开始

**Comment by qwvpn** [comment]
@kfeng0806 可以设置一个上传队列，首次取出5个上传，后面每次成功一个上传就从队列里取出一个接着上传

**Comment by arzcl** [comment]
可以使用七牛的JSSDK

**Comment by arzcl** [comment]
或者自己在后台写直传

**Comment by wangjunji** [comment]
@794203586 你后来是怎么解决的，碰到了同样的问题，上传单个文件到七牛没有问题，多个文件就不行了，每个文件要携带单独的key
