### ISSUE TITLE
Cascader 级联选择器使用动态加载次级选项的时候能不能传多点参数

### ISSUE THREAD

**Issue by cel533** [ElemeFE/element#3413]
`<el-cascader
  :options="options2"
  @active-item-change="handleItemChange"
  :props="props"
></el-cascader>
handleItemChange(val) {

}
`
只传val太少了,我觉得至少要把选中整个item传进来,不然动态加载还要重新去循环数组然后去改变children

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by gamead** [comment]
至少回答下问题嘛

**Comment by huqiliang** [comment]
@cel533 这问题解决了没？

**Comment by DusuWen** [comment]
同问
