### ISSUE TITLE
如何给table头部加 tooltip

### ISSUE THREAD

**Issue by suhaotian** [ElemeFE/element#3418]
![image](https://cloud.githubusercontent.com/assets/6512574/23785601/7e7f7bfe-05a3-11e7-9b98-17a7809f6613.png)

比如在上面的 **地址** 那里添加一个tooltip，鼠标划过去显示，看了文档，有个 renderHeader 函数，但是怎么组合 tooltip 上去呢

**Comment by FlappyHeart** [comment]
https://gist.github.com/f22ca194b0ed22425ac85f7a2f0778d8

参考这里，我写了个renderheader，你可以去文档里把tooltip元素在这里createElement试一下。

详细文档参考这里https://cn.vuejs.org/v2/guide/render-function.html#createElement-参数

**Comment by suhaotian** [comment]
Nice job

**Comment by kopheece** [comment]
@FlappyHeart 你的这个地址打不开 https://gist.github.com/f22ca194b0ed22425ac85f7a2f0778d8
可以重新给个demo么

**Comment by FlappyHeart** [comment]
哦，gist被墙了吧。我贴关键的过来
```
renderHeader(createElement, { column }) {
            return createElement(
              'el-button', {attrs: {size: 'mini', type: 'primary', icon: 'plus'}, on: {
                  click: this.showForm
              }}
            );
        }
```

**Comment by kopheece** [comment]
@FlappyHeart  谢谢

**Comment by cag2050** [comment]
这个自己写的table头部加popover的例子（使用vue-data-tables插件），地址：https://github.com/cag2050/vue_tables_xlsx_demo/blob/master/src/views/useDataTablesComp.vue
