### ISSUE TITLE
el-table的highlight-current-row属性并没有起作用

### ISSUE THREAD

**Issue by lanmaomm** [ElemeFE/element#3419]
### ElementUI version
1.2.3

### OS/Browsers version
macOS/Chrome 53

### Steps to reproduce
在jsfiddle上直接测试highlight-current-row属性，均没有起作用，以下三种方式都没有让当前行的高亮消失：
 :highlight-current-row="false"
 :highlight-current-row="true"
 highlight-current-row
### What is Expected?
希望能告知解决方案，谢谢！

**Comment by Leopoldthecoder** [comment]
看起来你指的是鼠标 hover 上去之后的效果，而 `highlight-current-row` 指的是是否单选，和 hover 无关。不想要 hover 效果的话可以自己写 CSS 覆盖。

**Comment by qwIvan** [comment]
`highlight-current-row`应该是决定class`current-row`是否高亮的配置。
默认情况下，无论`highlight-current-row`为`true`or`false`都可以单选。
而现在的问题是，无法关闭点击后高亮的效果。

**Comment by rubyisapm** [comment]
属性名确实有误解 +1

**Comment by lovepoem** [comment]
那怎么关闭Table的鼠标悬停效果？

**Comment by matthewmyu** [comment]
四年了 还没人解决吗
