### ISSUE TITLE
Dropdown下拉菜单生命周期问题

### ISSUE THREAD

**Issue by Amastyer** [ElemeFE/element#342]
### ElementUI version
1.0.0-rc.6 

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.1

### Reproduction Link
http://element.eleme.io/#/component/dropdown

### Steps to reproduce
* 打开官方演示站点
* 选择组件菜单，找到下拉菜单演示
* 选择click触发方式的演示，点击展开菜单
* 此时不要收起菜单，点击左边一个链接，跳转到另一路由
* 此时展开的菜单并未被销毁，出现在了屏幕的左上角

### What is Expected?
展开的菜单被销毁

### What is actually happening?
展开的菜单未被销毁

**Comment by erguotou520** [comment]
同#194
