### ISSUE TITLE
table组件在开启border=true的情况下, firefox(版本49)浏览器出现样式问题

### ISSUE THREAD

**Issue by penggle** [ElemeFE/element#3423]
table组件在开启border=true的情况下, firefox(版本49)浏览器出现样式问题
![table](https://cloud.githubusercontent.com/assets/5085704/23788094/09eee7c2-05b0-11e7-9525-2081111c62b5.png)

**Comment by penggle** [comment]
眼睛都找瞎了，终于定位到css问题所在：
.el-table--fit td.gutter, .el-table--fit th.gutter {
	border-width: 0; //其实gutter是个最后的隐藏列,原来是border-right-width: 1px;正是这个引起的问题
}

**Comment by acmeid** [comment]
element-ui 1.2.7 在Safari 10.0.3 (11602.4.8.0.1) 仍有这个问题
