### ISSUE TITLE
 Cascader 级联选择器 change-on-select

### ISSUE THREAD

**Issue by JustPlayN** [ElemeFE/element#3424]
Cascader 级联选择器 change-on-select在数据达到一定量时，比如省市区选择时，设置 change-on-select属性会出现不能选择的情况

**Comment by wilsonIs** [comment]
可以选择，只是组件需要的值是数组，如［广东id,深圳id,南山区id］，另外cascader的1.2.3是有个bug的，你需要升到1.2.4

**Comment by as236676674** [comment]
可以选择 但是选择了下拉框不会消失 这样很蛋疼

**Comment by gypjoy** [comment]
> 可以选择 但是选择了下拉框不会消失 这样很蛋疼

请问下，选择任意级，下拉框不消失的问题，您解决了吗？
