### ISSUE TITLE
关于表单验证的问题 进来瞧瞧~

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#3426]
![3 qp _npmqy4 crz5_88oj](https://cloud.githubusercontent.com/assets/15045200/23788885/7f944276-05b3-11e7-97fc-6d234421160b.png)
我这里验证了input 请问select该怎么验证呢？

**Comment by kfeng0806** [comment]
这个select的值不就是传给input的吗 何必再验证select?

**Comment by bihongbin3027** [comment]
![f8k8 in9w uy t 0mu17](https://cloud.githubusercontent.com/assets/15045200/23790022/4d41b0ec-05b8-11e7-8830-6037b6174a54.png)
不是同一个值啊~

**Comment by bihongbin3027** [comment]
![j acqh 5q6vwc3li7v_rx y](https://cloud.githubusercontent.com/assets/15045200/23790061/7b644246-05b8-11e7-973f-b25a8b314790.png)
还有循环出来的动态的select该如何验证呢

**Comment by bihongbin3027** [comment]
![q w co lvc h gho9mj580](https://cloud.githubusercontent.com/assets/15045200/23790638/00b5ce9a-05bb-11e7-9c53-eab9a70ab611.png)
这样写这个select这块直接消失了
![5b 6 c54pd1 o y7 x 6 s](https://cloud.githubusercontent.com/assets/15045200/23790680/25222d46-05bb-11e7-91da-a4f8bf080ec5.png)

**Comment by bihongbin3027** [comment]
在线等啊 急...

**Comment by kfeng0806** [comment]
这个select只是input组件中的一个slot 用表单验证验证不了值的 你可以用个wachter来观测item的变化再获取Does的值来进行验证之类的操作

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by xs47968224** [comment]
官方使用手册上没有说，动态校验的使用方法，但变通一下，我的解决方案：
https://jsfiddle.net/xs47968224/29n5cdjm/3/#&togetherjs=yKonoBnMgu
