### ISSUE TITLE
el-row和el-col中间加入transition-group后gutter失效

### ISSUE THREAD

**Issue by zdpeitang** [ElemeFE/element#3428]
### ElementUI version

1.2.3

### OS/Browsers version

Ubuntu 16.04, Chrome 56

### Vue version

2.2.2

### Reproduction Link

http://jsfiddle.net/z8t3L1xr/

### Steps to reproduce
在el-col外面加transition-group标签

### What is Expected?
el-col元素间间隔正常

### What is actually happening?
el-col放入tansition-group后间距消失

**Comment by baiyaaaaa** [comment]
This is because transition-group will create a html tag itself.
