### ISSUE TITLE
[bug]dialog中嵌套div标签格式会乱

### ISSUE THREAD

**Issue by FlappyHeart** [ElemeFE/element#3429]
http://jsfiddle.net/liuchunyao90/0t38jL4u/

如果不嵌套div，确定和取消按钮在右下角，如果嵌套一层div，那么会出现在左下角，不明白为什么。

我的需求是组件复用，dialog中的form要拿出来单独做一个文件。form组件中会包含多个标签，所以需要外套一层div，这个有办法解决吗？

**Comment by Leopoldthecoder** [comment]
可以看下 Vue 本身对于这种嵌套的 slot 的处理：https://jsfiddle.net/leopoldthecuber/a8bvzvL3/
其实你这个自己加条 `text-align: right` 就可以：http://jsfiddle.net/leopoldthecuber/0t38jL4u/1/

**Comment by FlappyHeart** [comment]
位置倒是很好调整，但是和其他的元素总是对不齐，每次都要自己试坐标。
