### ISSUE TITLE
icon属性使用自定义图标

### ISSUE THREAD

**Issue by dnshi** [ElemeFE/element#343]
当前存在一个问题就是，icon的属性并不支持外部图标，而element提供的图标较少。
请问，比如在步骤条里，是否可以自定义一些图标或者以后有计划提供相应的接口？谢谢

**Comment by catalsdevelop** [comment]
我也在关注这个问题，现在有一些iconfont，我都是去阿里平台自己打包后使用的，当然也没有太大工作量，只是如果element能提供额外接口就好了。

**Comment by csvwolf** [comment]
#349 

可以使用`slot`自定义图标，本来的样式有点问题，需要人工添加一点`class`，上面的pr修复了这个问题，新版就OK了。

<https://jsfiddle.net/csvwolf/x1uwxjt4/>

**Comment by devrsi0n** [comment]
只有步骤条可以自定义icon么？其他组件也需要的，我试了下把vue-icons这个包放在el-menu-item标签里面，icon是错位的。请问有兼任第三方icon的方案么？

**Comment by QingWei-Li** [comment]
@devrsi0n 
手动改样式，第三方的图标样式跟 Element 内置样式不一定一致

只要是支持 slot 的组件都可以放自定义 icon，可能需要自己手动改下样式

**Comment by GreatQing** [comment]
icon图标的大小可以更改的吗，我想增大整个icon的size，有人知道怎么实现吗

**Comment by PanJiaChen** [comment]
@GreatQing http://jsfiddle.net/cf4wb082/1/
就是一般的iconfont

**Comment by qianlongo** [comment]
@csvwolf https://jsfiddle.net/csvwolf/x1uwxjt4/  404了

**Comment by tylerrrkd** [comment]
@GreatQing `font-size`
