### ISSUE TITLE
v-model.lazy not working on el-input

### ISSUE THREAD

**Issue by macu** [ElemeFE/element#3431]
```
<el-input
	type="textarea"
	autosize
	placeholder="Please input"
	v-model.lazy="textarea">
```

Despite using v-model.**lazy**, my textarea watcher is fired for every keystroke.

**Comment by languanghao** [comment]
use `@change.native='handleValueChange'`

**Comment by codelabstudios** [comment]
That isn't a good solution because you'll need to specific an additional function to handle updating the value.

Still seeing this issue
