### ISSUE TITLE
cascader的默认值是数组，则无法初始化数据值？省市区操作！

### ISSUE THREAD

**Issue by chinavane** [ElemeFE/element#3432]
`<el-cascader size="large" :options="options" v-model="selectedOptions" @change="handleAreaChange"></el-cascader>`

初始化值：
`selectedOptions:[["130000","河北省"],["130300","秦皇岛市"],["130304","北戴河区"]]
`

初始化不了下拉默认数据。

**Comment by Plortinus** [comment]
http://jsfiddle.net/50bvy1rh/

**Comment by Leopoldthecoder** [comment]
其实还是因为默认值和选项引用的不是同一个数组：http://jsfiddle.net/leopoldthecuber/50bvy1rh/1/

目前没有什么好办法，可以把默认值设置为数字或字符串，然后自己映射到对应的数组。
