### ISSUE TITLE
select输入框校验提示文字没有对齐

### ISSUE THREAD

**Issue by FlappyHeart** [ElemeFE/element#3434]
http://jsfiddle.net/liuchunyao90/0au43kbd/6/

为什么select的校验提示文字没有对齐，input的能对齐。

**Comment by lincenying** [comment]
`<el-form-item label="hello:" prop="name">`
=>
`<el-form-item label="hello:" prop="name" label-width="60px">`

**Comment by FlappyHeart** [comment]
谢谢
