### ISSUE TITLE
table在分页的时候附带checkbox功能，当我选中第一页的某些记录，在操作跳转分页后之前选中的就不再起效了？

### ISSUE THREAD

**Issue by chinavane** [ElemeFE/element#3436]
是否可以做到就算是跳转分页，checked的记录也可以记录下去。

**Comment by zhongmengyuan** [comment]
同意，我之前也遇到了这个问题，费了很大波折才实现这个功能。有必要优化一下这个功能

**Comment by Leopoldthecoder** [comment]
使用 `reserve-selection`，文档中有说明：https://jsfiddle.net/leopoldthecuber/76np2879/

**Comment by xyyVee** [comment]
> 使用 `reserve-selection`，文档中有说明：https://jsfiddle.net/leopoldthecuber/76np2879/

想问一下demo是哪个版本的？
