### ISSUE TITLE
Form 表单 label-position可以混合使用吗

### ISSUE THREAD

**Issue by milu2003** [ElemeFE/element#3438]
label-position	表单域标签的位置
目前提供三个right/left/top。这意味每个表单元素都统一。

比如

![image](https://cloud.githubusercontent.com/assets/15957433/23821986/f03a4920-067c-11e7-93dc-feb50eff3333.png)

![image](https://cloud.githubusercontent.com/assets/15957433/23821983/e0d5e048-067c-11e7-92f7-fe64b00a3d02.png)

现在表单已经统一设置了顶部对齐。
但我希望第一个占2行，第二个占1行。也就是第一个top模式，第二个left模式。
所以我觉得label-position这个参数，应该每个Form-Item 也能单独设置。

**Comment by Leopoldthecoder** [comment]
应该不会提供，可以自己写点 CSS 实现。

**Comment by zczjy** [comment]
请问解决了吗

**Comment by milu2003** [comment]
@zczjy 没解决，现在回头看来，我这个需求不算合理，样式最好统一。
一个表单，一个 left，一个top，这个需求本身就存在问题。
实在需要，最好自己写了。

**Comment by zczjy** [comment]
> @zczjy没解决，现在回头看来，我这个需求不算合理，样式最好统一。
> 一个表格，一个左，一个顶，这个需求本身就存在问题。
> 实在需要，最好自己写了。

好的 谢谢 可以用switch的activetext代替不 哈哈这个就看需求了

**Comment by zczjy** [comment]
<el-form-item>
          <el-row >
            <el-col :span="12">标签</el-col>
            <el-col :span="8">
              <el-switch v-model="status"></el-switch>
            </el-col>
          </el-row>
        </el-form-item>
这样可以达到预期效果 @milu2003

**Comment by zczjy** [comment]
` <el-form-item>
          <el-row>
            <el-col :span="12">标签</el-col>
            <el-col :span="8">
              <el-switch v-model="data.options.timestamp">
              </el-switch>
            </el-col>
          </el-row>
        </el-form-item>` @milu2003  我这样设置的  达到预期样式

**Comment by phx98** [comment]
我觉得很合理呀,这样封装组件时会有满满的幸福

**Comment by phx98** [comment]
我觉得很合理呀,这样封装组件时会有满满的幸福
