### ISSUE TITLE
Tabs 标签页 点击有一定的延迟效果，建议去掉。

### ISSUE THREAD

**Issue by milu2003** [ElemeFE/element#3439]
如题。点击之后发现切换有一定的延迟，我不知道是不是设置了时间。比如多少毫秒之后才切换。
我没发现哪里可以设置参数取消。每次点击，感觉好像我的页面很卡一样。感觉有点不舒服，建议去掉。

**Comment by Leopoldthecoder** [comment]
官方文档上并没有延迟。

**Comment by milu2003** [comment]
@Leopoldthecoder 有的。。。难道是我感觉的问题吗

**Comment by milu2003** [comment]
![image](https://cloud.githubusercontent.com/assets/15957433/23822049/13eeb4c6-067f-11e7-8941-a8faeaeb94f2.png)


这个。。切换起来就没那么干脆。

**Comment by milu2003** [comment]
我试了一下bootstrap的感觉。

http://www.runoob.com/try/try.php?filename=bootstrap3-plugin-tab-event

感觉完全不一样嘛
