### ISSUE TITLE
Cascader与table的问题

### ISSUE THREAD

**Issue by chinavane** [ElemeFE/element#3442]
之前的问题
[#3432](https://github.com/ElemeFE/element/issues/3432)

为了选择方便，听取意见将数据修改成字符串形式

`[
  {
    "value": "110000",
    "label": "北京市",
    "children": [
      {
        "value": "110100",
        "label": "北京市市辖区",
        "children": [
          {
            "value": "110101",
            "label": "东城区"
          },
          {
            "value": "110102",
            "label": "西城区"
          },
          {
            "value": "110105",
            "label": "朝阳区"
          },
          {
            "value": "110106",
            "label": "丰台区"
          },
..............
`

那么存到mongo中的数据也成了
["110000","110100","110106"]这样的数据，问题是我要在table列表的时候显示出"北京市/北京市市辖区/丰台区"的文字信息啊。

有些晕了。

**Comment by Leopoldthecoder** [comment]
往后端存之前自己根据 value 的值映射到你需要的数据结构上。

**Comment by chinavane** [comment]
那就是要重新查询了？在change操作的时候是否将当前整个对象返回会比较好呢？这样的话就可以自由拼装数据结构类型了。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
