### ISSUE TITLE
更新远程数据，resetFields怎么使用？

### ISSUE THREAD

**Issue by l4422984** [ElemeFE/element#3446]
更新远程数据的应用。vue组件的data必须是函数，初始值是空的，在created属性中调用远程方法获取老数据，再修改data。

这样resetFields调用的效果就是清空数据（因为data返回的初始值为空）
怎样才能让表单的初始值为远程访问后的数据（让resetFields效果为回到远程的原始值，而不是空值）？？

**Comment by Leopoldthecoder** [comment]
试试用 v-if，让表单在数据返回之后再渲染
