### ISSUE TITLE
Table中，如何在每一行中使用Computed属性

### ISSUE THREAD

**Issue by baiyunchen** [ElemeFE/element#3447]
**需求是这样的：**
一个展示产品列表的页面(使用的是Element的Table)，其中的价格是以文本框展示，并且可以编辑的，当用户手动修改价格时，希望将该文本框的背景色设置为其他颜色来提醒用户。
我在Vue的ISSUE中找到了Vue处理集合中的Computed属性的办法（https://github.com/vuejs/vue/issues/66 ） ，不知道Element中这种该如何实现；

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/6yqkx7dt/4/
是这个意思么？

**Comment by baiyunchen** [comment]
@PanJiaChen 大概是要这个效果，但是我不是特别喜欢用监听事件，手动改DOM的方式来实现，想知道有没有更好的方式用MVVM的方式来搞定他~
