### ISSUE TITLE
树形菜单升级成表格格式的

### ISSUE THREAD

**Issue by lizixu0909** [ElemeFE/element#3449]
可否把树形菜单升级成表格格式的，可以添加自定义的一些标签、比如按钮，也可以显示一些其他属性值，比如资源菜单，可以显示资源的URL、是否禁用等等

**Comment by Leopoldthecoder** [comment]
Tree 的内容是可以自定义的，你说的添加标签、按钮都是可以做到的，文档上有例子。但是不会做成 TreeGrid
