### ISSUE TITLE
this.$notify is not a function

### ISSUE THREAD

**Issue by Frondor** [ElemeFE/element#3450]
Weird thing about it is, it started to crash like this suddenly.

> TypeError: this.$notify is not a function

I load `Notification` on demand like `import { Notification } from 'element-ui'` and then add it as a component
```
components: { Notification },
created () {
   this.$notify({ ... });
}
```

Version: 
* vue@2.2.2
* element-ui@1.2.4

Build system: Laravel-mix

**Comment by Frondor** [comment]
Should have read more carefully the docs, in my approach it wasn't needed to add it as a component, I could simply do something like `Notification.success(options)`

**Comment by rockfang** [comment]
add the folloing code after **import { Notification } from 'element-ui'**
**Vue.prototype.$notify = Notification;**

**Comment by kujiy** [comment]
This thread helped me. Thanks.
```
<script>
    import { Notification } from 'element-ui';

    export default {
        name: "blah",
        data() {
            return { }
        },
        methods: {
           notify: function () {
                   Notification.success({title: "hello", message: "world", type: "success"});
           }
        },
        computed: {
          this.notify();
        },
```

**Comment by Cenlins** [comment]
I'm stuck at the same issue!! can't solve it for 6 hours now,

can anyone please explain in details how we can use this plugin inside a single vue component!!

**Comment by SuroZaqaryan** [comment]
```
import Vue from 'vue'

Vue.notify({
    group: 'foo',
    title: 'Important message',
    text: 'Hello user! This is a notification!'
})
```
