### ISSUE TITLE
el-select v-model="value5" multiple placeholder="请选择" 如果value5为undefind(随后立即被赋值[]),就会无法选择

### ISSUE THREAD

**Issue by snoopy83101** [ElemeFE/element#3452]
el-select v-model="value5" multiple placeholder="请选择" 如果value5为undefind(随后立即被赋值[]),就会无法选择

选择什么都没有反应.

**Comment by Leopoldthecoder** [comment]
请给 demo

**Comment by lincenying** [comment]
带multiple属性, 请保证v-model的初始值是数组, 不然js直接报错, 后面自然不能选择.

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by snoopy83101** [comment]
哦. 也就是说v-model 本来是undefind, 接着被赋值为[], 也是仍然不合要求, 需要在其声明时开始, 一直是数组.

**Comment by snoopy83101** [comment]
@QingWei-Li 
知道了大大,毕竟我刚来, 也是真心准备用咱们的框架做商业项目的. 
多少通融一下表态严肃了哈.   node.js和各种前端框架本来就跟小狗一样的自由..
只要能弄明白事儿俺们开发者就有收获, 做出东西来也给咱们开原生态出一份力不是?
