### ISSUE TITLE
value.getTime is not a function

### ISSUE THREAD

**Issue by chenxiajun** [ElemeFE/element#3453]
TimePicker 时间选择器
`<el-time-picker>
                            v-model="cnode.start_time"
                            :picker-options="{ selectableRange: '00:00:00 - 23:59:59'}"
                            :format="'HH:mm'"
                            placeholder="请选择节目开始时间">
</el-time-picker>`

后台的值：start_time:"2017-03-13 14:23:00"
或者：start_time:1489386180000 都不行。
浏览器报错
TypeError: value.getTime is not a function
    at Object.date [as validator] (eval at <anonymous> (http://127.0.0.1:8010/assets/vendor.js:993:1), <anonymous>:28:45)

**Comment by Leopoldthecoder** [comment]
需要是一个 Date 类型的值。

**Comment by chenxiajun** [comment]
可是我后台传过来的一个数组，怎么
 playbillForm:{
                    playbill_id:'',
                    playbill_name:'',
                    remark:'',
                    node:[{
                        start_time:new Date(),
                        programs:[],
                    }],
                },
this.playbillForm.node = response.body.detail;
很多条，怎么处理

**Comment by Leopoldthecoder** [comment]
map 一下不就搞定了么

**Comment by huhaophp** [comment]
``
