### ISSUE TITLE
建议：是否可以在Starter Kit模板上添加router的配置（虽然很easy）

### ISSUE THREAD

**Issue by gjycdd** [ElemeFE/element#3455]
> 虽然对于我们来说在Starter Kit模板添加vue-router以及配置router很容易，但是考虑到通用模板也就是类似于项目脚手架，那么通用模板的实用性也是需要考虑的，无需配置，开箱即用是不是更好些呢？

> 这个建议只是我个人根据其他脚手架对比后对这个模板体验上的一点小感想，见者轻喷，希望采纳。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
