### ISSUE TITLE
Upload 上传：缺少选择文件后钩子参数配置

### ISSUE THREAD

**Issue by biaomingzhong** [ElemeFE/element#3456]
看例子是没有文件选择后触发的钩子，因为我想在选择的时候修改fileList，实现单文件上传，例子也没有单文件的例子

**Comment by regiondavid** [comment]
也遇到类似问题了，想问下有什么好的解决办法吗。我是想判断用户到底上没上传文件再去选择不同的发送方法去发送文件

**Comment by baiyaaaaa** [comment]
不太理解你们的需求，目前multiple不就是限制多文件单文件上传的参数么

**Comment by regiondavid** [comment]
我们目前的场景是：在发布内容的时候必须携带一个附件（也只能携带一个附件），当用户去更改的时候，不管是修改文章内容文件或者修改附件都可以提交更改。但我们目前的上传方法是文件和文章内容一块传，所以想到了采用分步提交（就是取消自动上传），问题是我想在上传（submit）之前去检查一下它添加的文件的数量去做个限制或者去判断下用户有没有去上传新的文件，但目前没有比较好的解决方法。感觉如果能有个选择文件后的钩子的话我会比较轻松的就可以去判断了。

**Comment by biaomingzhong** [comment]
@baiyaaaaa 那个参数是限制单个文件选择的，多选择几次，默认的预览界面就会有多个文件显示。看了源码，内部实现就是一个数组存储着上传列表，没有作限制

**Comment by fengqi** [comment]
同样有类似需求, 没法限制只能选一个文件, 只能上传一个文件

**Comment by yuweiming2016** [comment]
类似需求，希望选择文件后，有个钩子，能返回被选择的文件，要展示选择文件的本地路径……

**Comment by oooo0oooo0** [comment]
拿不到已选的文件列表，选择文件后也没有钩子，所以实现单文件限制比较麻烦

**Comment by K-walker** [comment]
同样的需求，没有单个文件上传的功能，简直太恶心了，这个需求在日常开发中应该经常用到的，希望官方能给一个解决方案。

**Comment by visionding** [comment]
这个功能有什么进展吗？我也有类似的需求，需要重复提交

**Comment by ziyoung** [comment]
单文件上传的话，把 `limit` 设为 1 就可以了吧。https://jsfiddle.net/zhiyang/tuexd3nL/1/
