### ISSUE TITLE
toast loading

### ISSUE THREAD

**Issue by sunyuanfei** [ElemeFE/element#3457]
刚刚问的 问题还没解决就关了 (⊙﹏⊙)b
我使用vue-toast-mobile version
报一下
ReferenceError: _h is not defined
又看了下issues结果有人跟我出现同样错误
回复是![image](https://cloud.githubusercontent.com/assets/7675592/23843321/049af03e-07f6-11e7-9589-fdbdea936a85.png)
再请教下后台加载loading提示框有什么写

**Comment by QingWei-Li** [comment]
issue 不是拿来问问题的，请遵守 [issue 规范](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md#issue-规范)
