### ISSUE TITLE
求救~有例子，动态的下拉菜单怎么验证表单~

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#3458]
http://jsfiddle.net/e2xg757v/1/
![n l 73ucn xi 4m1w nw4 d](https://cloud.githubusercontent.com/assets/15045200/23843629/48ac7174-07f8-11e7-9a16-8361e8c272e2.png)
在线等，急~

**Comment by bihongbin3027** [comment]
如果item.Frequency值是空的话，就提示让它选一个~

**Comment by bihongbin3027** [comment]
![7ldis5mf9kvoehbq 0c m31](https://cloud.githubusercontent.com/assets/15045200/23843713/bd7bc95a-07f8-11e7-82b7-8c6f734ceb48.png)
验证输入框这样是可以的，验证下拉菜单我外面套一层el-form-item，里面的内容就消失了，啥都没了

**Comment by bihongbin3027** [comment]
有人知道怎么弄吗 帮我下 很急

**Comment by bihongbin3027** [comment]
http://jsfiddle.net/e2xg757v/4/
我改成这样了 但是还有点问题~

**Comment by lincenying** [comment]
http://jsfiddle.net/e2xg757v/5/

**Comment by bihongbin3027** [comment]
非常感谢！！
