### ISSUE TITLE
[Tree]建议添加显示已经选择的项及数量统计的功能

### ISSUE THREAD

**Issue by xing-zhi** [ElemeFE/element#346]
增加一个列表显示已经选择的项并显示数量统计，可以一目了然地看出已经选择的情况。大致如下图所示

![tree-statistic](https://cloud.githubusercontent.com/assets/6940347/19294768/37126f12-9062-11e6-9c2d-3f81a5130fa4.png)

**Comment by Leopoldthecoder** [comment]
可以自己通过 Tree 实例上的 `getCheckedNodes` 来实现。
