### ISSUE TITLE
动态数据源的radio group没办法初始化值

### ISSUE THREAD

**Issue by motiandashao** [ElemeFE/element#3461]
<el-radio-group v-model="pageForm.type">
                            <el-radio label="1">内部</el-radio>
                            <el-radio label="2">外部</el-radio>
                        </el-radio-group>
上边的写法可以默认选中pageForm.type对应的值
<el-radio-group v-model="pageForm.type">
                            <el-radio v-for="item in types" :label="item.id">{{item.title}}</el-radio>
                        </el-radio-group>
这种用法，不管把types数据获取放在create mounted事件中，都无法选中pageForm.type对应的值，并且默认值对应的那个radio不能点击，需要先点击另外一个才行

**Comment by motiandashao** [comment]
```
<el-radio-group v-model="pageForm.type">
                            <el-radio label="1">内部</el-radio>
                            <el-radio label="2">外部</el-radio>
                        </el-radio-group>
```
上边的写法可以默认选中pageForm.type对应的值
```
<el-radio-group v-model="pageForm.type">
                            <el-radio v-for="item in types" :label="item.id">{{item.title}}</el-radio>
                        </el-radio-group>
```
这种用法，不管把types数据获取放在create mounted事件中，都无法选中pageForm.type对应的值，并且默认值对应的那个radio不能点击，需要先点击另外一个才行

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by shuidian** [comment]
我也遇到了类似的问题，请问如何解决的？

**Comment by huqiliang** [comment]
我也遇到了类似的问题，gitter里面也搜不到 请问怎么解决的？

**Comment by SanpLee** [comment]
我也遇到这个问题了，如何解决，没人知道怎么解决这个问题吗？

**Comment by chimpss** [comment]
我也遇到了类似的问题，请问该如何是好
