### ISSUE TITLE
popover和tooltip

### ISSUE THREAD

**Issue by loong-moon** [ElemeFE/element#3463]
popover当用v-popover时报指令错误-copy官网demo到项目中就会出错
![image](https://cloud.githubusercontent.com/assets/24216623/23846466/9308e986-0808-11e7-9f3b-fae16419c7e6.png)

tooltip完全没有作用 - copy官网demo到项目中没有报任何错误，也没起作用

**Comment by lincenying** [comment]
组件use了没有?

**Comment by loong-moon** [comment]
这两个组件要单独use吗

2017-03-13 

15123339284 



发件人：lincenying <notifications@github.com>
发送时间：2017-03-13 16:48
主题：Re: [ElemeFE/element] popover和tooltip (#3463)
收件人："ElemeFE/element"<element@noreply.github.com>
抄送："loong-moon"<15123339284@139.com>,"Author"<author@noreply.github.com>

组件use了没有?

**Comment by loong-moon** [comment]
![image](https://cloud.githubusercontent.com/assets/24216623/23847702/9ef15700-080e-11e7-88b0-fb9a780babb4.png)
![image](https://cloud.githubusercontent.com/assets/24216623/23847734/bd7bcaf2-080e-11e7-838f-2764beda8c59.png)



这两个组件要单独use吗

**Comment by loong-moon** [comment]
![image](https://cloud.githubusercontent.com/assets/24216623/23847807/172caf76-080f-11e7-8172-1d3fab65dfdb.png)
这是项目中的代码

**Comment by lincenying** [comment]
全局引用了, 不需要单独use

http://jsfiddle.net/e2xg757v/6/
测试没有问题.

**Comment by loong-moon** [comment]
我知道官网demo没有问题 但是在我项目中这样用有问题 请问知不知道是什么造成的

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里指处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by yusiwen** [comment]
@loong-moon 
我也遇到同样的问题，请问楼主解决了么？
