### ISSUE TITLE
关于treegrid的需求，请回答下有没有做这个组件的计划

### ISSUE THREAD

**Issue by xiaoguangma** [ElemeFE/element#3464]
### What is Expected?
希望官方能出一个关于treegrid的组件
### What is actually happening?
前面的issue有看到作者推荐了该treegrid的实现
https://git.oschina.net/bfgdqch/EleAdmin
本人也参考这个实现和官方table的实现自己尝试写了一个treegrid的但是着实有些差强人意

比如column自动宽度，以及column内容太长撑开高度等等有一系列不合适的地方

本人前端水平确实略差，所以希望官方可以给我们这些不专注于前端的码农一个treegrid方案，在此谢过了！
如果没有计划麻烦也回复一下

**Comment by QingWei-Li** [comment]
没有
