### ISSUE TITLE
DatePicker第二次初始化NULL值的时候是这样的[0NaN-NaN-NaN]

### ISSUE THREAD

**Issue by lampo1024** [ElemeFE/element#3465]
### Vue version
1.2.4

### What is actually happening?
在日期字段中初始化DatePicker的值，如果第一次的值为日期格式，比如:'2017-03-10'，能正常渲染，如：
```
birthday:"2017-03-10"
```
，但如果再一设置这个DatePicker字段的值为null,则会出现这样的渲染结果：
```
birthday:"0NaN-NaN-NaN"
```

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by lampo1024** [comment]
在实际项目中会出现，但弄成demo重现不了了。

**Comment by An0nymous0** [comment]
@QingWei-Li @lampo1024  也出现了同样的问题
