### ISSUE TITLE
select远程搜索-改进建议

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#3466]
vue 2.1.8
element-ui  1.2.3
最近开发项目用到远程搜索功能，提个建议吧

比如，客户信息数据库上万条数据时，我以手机号码检索时，输入1，肯定是会被全部检索出来，那就是上万条json数据，浏览器直接瞬间卡死，用户体验非常不好。现在只能在后台做限制。

建议：添加一个可以控制每次加载最多多少条数据的，超过就在下拉框下面给一个   更多..   的按钮。

**Comment by qwvpn** [comment]
你服务端控制每次最多返回10条就可以了吧，
这个就是你本地处理的问题了，实际上就算给你一个更多按钮，也不会先一次性加载所有数据，然后在分页加载，不管怎么做都是先分页后加载，而不是先加载后分页

**Comment by liwenda122** [comment]
demo可以，做大型。。。
