### ISSUE TITLE
el-form-item 组件的 label 属性不灵活

### ISSUE THREAD

**Issue by 00ming** [ElemeFE/element#3468]
我看了官方文档，demo中写的 el-form-item 的 label 属性是只能写固定的单行字符串的
```
 <el-form-item label="活动名称">
    <el-input v-model="form.name"></el-input>
  </el-form-item>
```
现在我想实现多行的label，比如
```
 <el-form-item label="活动名称<br>用于识别活动">
    <el-input v-model="form.name"></el-input>
  </el-form-item>
```
这时label会输出

`活动名称<br>用于识别活动`

希望能够改善 label 属性的灵活性，让它能够支持多行label

**Comment by kopheece** [comment]
希望Label能支持slot功能

**Comment by milu2003** [comment]
@kopheece 现在也想加个tooltip，但是不知道加在哪。哪位同志给点意见。

**Comment by kopheece** [comment]
@milu2003 我现在也是有这个需求  目前好像是没办法加

**Comment by fwon** [comment]
+1, 自定插入变量而非固定字符串

**Comment by baiyaaaaa** [comment]
已支持， #4634

**Comment by kopheece** [comment]
@baiyaaaaa   刚测试了下 https://jsfiddle.net/qkx3rtu1/    这个demo是el-input添加width属性；输入框没输入数据，直接点击提交，错误信息位置有问题；
如果去掉el-input添加width属性；因为el-input自带的width:100%，输入框就自动换行了

**Comment by AngeLeeGeek** [comment]
<el-form-item>
  <span slot="label">label：</span>
</el-form-item>

**Comment by KiyomiHan** [comment]
> @baiyaaaaa 刚测试了下 https://jsfiddle.net/qkx3rtu1/ 这个demo是el-input添加width属性；输入框没输入数据，直接点击提交，错误信息位置有问题；
> 如果去掉el-input添加width属性；因为el-input自带的width:100%，输入框就自动换行了

亲测有效

**Comment by geekFeier** [comment]
> `<el-form-item> <span slot="label">label：</span> </el-form-item>`

已解决
