### ISSUE TITLE
SELECT 框在 firefox 与 IE11 下 方向改变

### ISSUE THREAD

**Issue by WindWen** [ElemeFE/element#3469]
### ElementUI version

1.2.4
### OS/Browsers version

Firefox 50.1.0/Internet Explorer11
### Vue version

2.1.6
### Reproduction Link

http://element.eleme.io/#/zh-CN/component/select
### Steps to reproduce
选择案例中的分组
### What is Expected?
在谷歌浏览器中下拉框是在输入框下面的，但是在firefox和ie中会出现如图情况
![image](https://cloud.githubusercontent.com/assets/12590228/23853523/f42b9d5c-0827-11e7-83b0-71c368090bd7.png)

**Comment by reverland** [comment]
因为下面空间小吧

**Comment by WindWen** [comment]
开始也这样以为 但是试了好几次 甚至让上面的空间不够都试过了 适中朝上

**Comment by reverland** [comment]
是啊，第一个会往下，只要滚动了后面都往上。

**Comment by WindWen** [comment]
在谷歌浏览器下如果显示区域不够 下拉菜单就会出现在 输入框的上方OR下方

但是我这里的火狐和IE11 都是 不论显示区域够不够 下拉菜单永远在输入框的上方 并且怎么滚动都恢复不到正常的效果

**Comment by reverland** [comment]
……

**Comment by hcqqch** [comment]
> @reverland 你的问题解决了吗，我的在ie11以下也会出现，所有Popper弹出层都会随着滚动条向上滚动，然后下面的下拉框就看不到了

我遇到同样的问题，请问怎么解决的
