### ISSUE TITLE
Table expand row

### ISSUE THREAD

**Issue by elehaf16** [ElemeFE/element#3476]
On a table when a row is expanded and after the row's content is changed, the row is refresh and the row collapse. Would be nice if it doesn't collapse, if it save the state or to have a method where you can expand a row without clicking.

**Comment by reverland** [comment]
I implement a lighter table with element-ui's css with expand row.

If you need dynamic content in expanded rows, it may be better to use a lighter implementation.

**Comment by rodwin** [comment]
HI @reverland 

can you elaborate on what you mean by use lighter implementation?

I need to call an ajax request on row expand and show result on the expanded row.

Thanks

**Comment by reverland** [comment]
@rodwin I mean, write simple collapse tables by yourself...just use element-ui's css

**Comment by alonesuperman** [comment]
The row was re-render, not the expanded row.
so just set row-key attribute for “in-place patch” (see https://vuejs.org/v2/guide/list.html#Maintaining-State for detail)

**Comment by macarole** [comment]
it doesn't work for me.
