### ISSUE TITLE
如何更改el-table的背景颜色呢？

### ISSUE THREAD

**Issue by dongshimou** [ElemeFE/element#3477]
### ElementUI version
1.2.3

### Vue version
2.X

```
<div style="background-color:red;">
 <el-table ...
</div>
```
这样写无效
在el-table里 :style一个对象也无效，直接写一个style也无效。

请问我应该怎么修改呢？

**Comment by istobran** [comment]
在el-table里加个:style.native=""试试

**Comment by dongshimou** [comment]
@istobran 无效……
我的期望是 header 和 body 的style都改变。

**Comment by lincenying** [comment]
.el-table th {}
.el-table tr {}

写css覆盖, 注意css权重

**Comment by istobran** [comment]
https://jsfiddle.net/fady9wbp/

**Comment by dongshimou** [comment]
thinks.

**Comment by dongshimou** [comment]
出现了一个问题。
如果存在滚动条，然后把第一列设置为fixed的时候

![1](https://cloud.githubusercontent.com/assets/9100799/23884698/41685f98-08a9-11e7-85b4-dfd059119abf.png)

fixed的列怎么才能不显示后面那层的呢？
