### ISSUE TITLE
[el-table] show-overflow-tooltip 性能改进建议

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#3478]
中后台系统中大量数据的表格展示应该是常见的需求。

`show-overflow-tooltip` 属性可以解决文本超长时的问题，但当前是在所有的单元格中插入 `tooltip` 组件包装来简单实现的。

`tooltip` 组件使得 DOM 结构成倍增加，而且每个 `tooltip` 内部都有至少两个监听事件。这对大数据量表格来说性能是可以想象的到的。

实际上，我们只需要把 `tooltip` 改为实时渲染的就好了。下面是我们实现的一种方式，可对比参考。

这里提出来时希望官方在这个配置属性上能作更多的改进考虑。

示例一，设置了 `show-overflow-tooltip` 效果（小心卡死几十秒，这里示例中写了 1000行。实际中50行以上翻页时就会有明显的卡顿）：

http://jsfiddle.net/u36rak6k/

示例二，改进参考：

http://jsfiddle.net/u36rak6k/4/

**Comment by perfectyang** [comment]
我也现在这样的问题，我只好表格行内字超出换行了

**Comment by QingWei-Li** [comment]
果然 就只用一个 tooltip 就够了 😂

**Comment by rossroma** [comment]
现在的tool-tip是不是不能关闭了？

**Comment by Leopoldthecoder** [comment]
@rossroma 是 bug，下版本修复。

**Comment by erguotou520** [comment]
现在还是有多个实例啊
![image](https://cloud.githubusercontent.com/assets/7945757/25035079/e6da4c20-211d-11e7-98c6-22ced432fcb3.png)

**Comment by beipiaolangzi** [comment]
请教一个样式的问题   发现在设置overflow-tootip的表格上  给了一个最大的宽度     但是在单独给其中一列设置el-tootip标签时    会继承overflow-tootip的宽度  如何解决呢

**Comment by Hideer** [comment]
有个小问题`show-overflow-tooltip`属性是如何监听到文字超出的...想模仿做个小功能，卡在了这里..

**Comment by DoubleRayWang** [comment]
> 有个小问题`show-overflow-tooltip`属性是如何监听到文字超出的...想模仿做个小功能，卡在了这里..

同请教。

**Comment by renxia** [comment]
> > 有个小问题`show-overflow-tooltip`属性是如何监听到文字超出的...想模仿做个小功能，卡在了这里..
> 
> 同请教。

https://github.com/ElemeFE/element/blob/2830c0478331543ff51951cad349d66170fd0120/packages/table/src/table-body.js#L243
