### ISSUE TITLE
[TimePicker] 任意时间范围，初始化时间为17年及以后时组件无法正常使用

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#3479]
### ElementUI version

1.2.3
### Vue version

2.2.1
### Reproduction Link

http://jsfiddle.net/vkyntmdv/
### Steps to reproduce
初始化时间改为17年及以后组件无法正常使用
### What is Expected?
希望可以初始化为任意时间组件能够正常使用

**Comment by Leopoldthecoder** [comment]
Fixed in #3721
