### ISSUE TITLE
Customizable table footer for labelled column subtotals and totals

### ISSUE THREAD

**Issue by albert-kam** [ElemeFE/element#3480]
Hi all. 

Does elem-ui table support a customizable multi-row footer ? 

Usually report tables have footer showing subtotals and totals based on columns, along with optional 'labels' beside the subtotal or total number value. 
Or maybe table element has a named slot for footer ? I'm not sure, because i cant see it in the component guide or in table.vue.

Requesting a new feature if it's not already supported.

**Comment by albert-kam** [comment]
Hi im quite new here. Why isnt the original post listed in the issues section ?

**Comment by Leopoldthecoder** [comment]
Duplicate of #3164. 

We are considering adding this feature. Please see #3164 for updates, though you may need Google translate.

**Comment by albert-kam** [comment]
Yay, very good news indeed. Yes i told by vue guys in gitter that 3164 exists, and i voted the feature request already (after a google translation indeed).

Thank you for the great library !

**Comment by douglasg14b** [comment]
Has this been added?

I see that #3164is closed as a duplicate of #2563 which is closed as a duplicate of #1307 which has been closed.

I see a summary row, but not a configurable footer that we can put inputs or buttons into?
