### ISSUE TITLE
Tree组件自定义节点内容功能无法使用

### ISSUE THREAD

**Issue by goforward01** [ElemeFE/element#3481]
### ElementUI version
1.2.4

### OS/Browsers version
Firefox 52.0 & Chrome 53.0

### Vue version
2.x

### Reproduction Link
https://jsfiddle.net/api/post/library/pure/

### Steps to reproduce
直接运行jsfiddle中的例子，例子来自官网文档中关于Tree组件使用的说明。
### What is Expected?
实现自定义添加和删除Tree组件的节点
### What is actually happening?
所有的label消失，renderContent函数貌似不起作用，未出现Append和Delete按钮。

PS:element很棒， 也可能是我哪里操作不对，还请指正~

**Comment by Leopoldthecoder** [comment]
jsfiddle 不支持 jsx，所以这个例子会报错。同样一段代码在实际项目里是可以的。

**Comment by goforward01** [comment]
多谢，自己写了个可以了~

**Comment by huangyanxiong01** [comment]
在vue中写jsx么，怎么配置webpack的babel编译？

**Comment by MoxHotPot** [comment]
请问一下这个问题，最后是怎么解决的

**Comment by goforward01** [comment]
自己看：https://github.com/vuejs/babel-plugin-transform-vue-jsx

**Comment by lucifercha** [comment]
不写jsx tree就没法动态添加了？
