### ISSUE TITLE
日期时间选择器中，日期和时间范围无法快速选择年份和月份吗？

### ISSUE THREAD

**Issue by Peterlhx** [ElemeFE/element#3482]
最近想应用vue.js + element ui对项目重构，但发现element ui的双日历组件并不能快速选择年份和月份，单日历形式下是可以通过点击年或者月进行快速选择的。
![image](https://cloud.githubusercontent.com/assets/11450619/23887879/6d4c0ab8-08bf-11e7-9390-626961add496.png)

**Comment by QingWei-Li** [comment]
不能，暂时不考虑

**Comment by MichaelPan24** [comment]
> 最近想应用vue.js + element ui对项目重构，但发现element ui的双日历组件并不能快速选择年份和月份，单日历形式下是可以通过点击年或者月进行快速选择的。
> ![image](https://cloud.githubusercontent.com/assets/11450619/23887879/6d4c0ab8-08bf-11e7-9390-626961add496.png)

同样这种需求是应该被考虑进去的
