### ISSUE TITLE
<el-table-column fixed="right">中嵌套<el-dialog>，遮罩层会在上方

### ISSUE THREAD

**Issue by zj972** [ElemeFE/element#3483]
![image](https://cloud.githubusercontent.com/assets/14173609/23888366/8d4be36c-08c2-11e7-8f2a-bf621a28b7e2.png)

**Comment by Leopoldthecoder** [comment]
请提供 demo

**Comment by zj972** [comment]
[http://jsfiddle.net/sho9zytw/](url)

**Comment by renxia** [comment]
dialog 不应该放在嵌套组件内，最好与表格同级。
或者设置 `modal-append-to-body="false"`

http://jsfiddle.net/sho9zytw/2/

**Comment by zj972** [comment]
table和dialog两边都不好妥协，最好是可以调整一下样式（并不知道怎么调），或者其他解决方案

**Comment by Leopoldthecoder** [comment]
最好还是应该放在 Table 外面，目前的写法其实一次会打开很多个 Dialog，这应该不是想要的结果。

**Comment by zj972** [comment]
感谢你们的解答，我把dialog放在外面了
http://jsfiddle.net/sho9zytw/4/
