### ISSUE TITLE
[Bug Report] 2个el-table在v-if中切换报错

### ISSUE THREAD

**Issue by caiyg** [ElemeFE/element#3485]
### Element UI version
1.2.4

### OS/Browsers version
win10

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/cyghenry/83zd6tnw/](https://jsfiddle.net/cyghenry/83zd6tnw/)

### Steps to reproduce
在模板和自选评分项中来回切换

### What is Expected?
正常显示table

### What is actually happening?
用vue-devtool看了一下似乎两个table的id是一样的，是否这样在渲染数据的时候因为类型不一样而报错了

**Comment by PanJiaChen** [comment]
自己加一个key吧
https://jsfiddle.net/83zd6tnw/1/

**Comment by caiyg** [comment]
@PanJiaChen 解决了
