### ISSUE TITLE
checkbox  el-checkbox__original 问题

### ISSUE THREAD

**Issue by chao-hua** [ElemeFE/element#3490]
### What is actually happening
在用el-checkbox-group时候，checkbox项很多，出现一个诡异问题。点击第一个有时会勾中同行的最后一个，最后发现是由于el-checkbox__original的绝对定位刚好覆盖在了，第一个checkbox组件的文字上。
这个left:-999px，是否合理。
![error](https://cloud.githubusercontent.com/assets/20752717/23893835/ee29fa76-08da-11e7-9dec-29574456fa84.png)

**Comment by Leopoldthecoder** [comment]
Fixed in #3492
