### ISSUE TITLE
select 组件怎么默认在上层弹出

### ISSUE THREAD

**Issue by xunkeleo** [ElemeFE/element#3493]
如题 select 组件怎么默认在上层弹出
弹框中使用 在底部弹出展示不友好 希望在目标上层弹出

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
