### ISSUE TITLE
请教一个关于input输入后匹配输入建议的问题~有例子~

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#3494]
http://jsfiddle.net/80b7ceph/1/
我现在要达成这样的效果，比如说我在输入框输入‘毒’这个字，然后把这两项都显示在输入框下面~
请问该如何实现，官网例子有点没看明白~

**Comment by bihongbin3027** [comment]
麻烦知道的帮我看下 非常感谢~！

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/leopoldthecuber/80b7ceph/2/
需要注意的是，目前候选项必须要有 `value` 字段。
