### ISSUE TITLE
如何动态控制Table 的列?

### ISSUE THREAD

**Issue by snoopy83101** [ElemeFE/element#3502]
比如, 单击一个按钮, 让table新增一列的例子在http://element.eleme.io/#/zh-CN/component/table
中找不到

**Comment by PanJiaChen** [comment]
有问题先搜搜issue啊
https://github.com/ElemeFE/element/issues/3360

**Comment by snoopy83101** [comment]
@PanJiaChen 
大神您好, 我在打开您的例子http://jsfiddle.net/n2u5ejuz/2/
的时候页面上右侧没有反应, 可以在其他地方看到您的demo吗?

**Comment by snoopy83101** [comment]
![qq 20170315131249](https://cloud.githubusercontent.com/assets/24613784/23934573/3e3e1528-0981-11e7-863d-24f5e999fd29.jpg)
我已经连上美国VPN,仍然是这样.

**Comment by snoopy83101** [comment]
![image](https://cloud.githubusercontent.com/assets/24613784/23934689/01476286-0982-11e7-93a3-bec3ce2b36de.png)
我的浏览器也没有问题, 不知道为何,您的例子真心打不开啊.

**Comment by snoopy83101** [comment]
我知道了. 您的例子的链接是http的, 改成https,即没有问题了. 您是不是要更新一下链接了? 我一开始就是因为打不开您的链接才来问的.

**Comment by PanJiaChen** [comment]
谢谢提醒
