### ISSUE TITLE
日期时间选择器的value没有格式化

### ISSUE THREAD

**Issue by cfking** [ElemeFE/element#3503]
日期时间选择器的value没有格式化，所见与所得不一致，设置了format只对显示有效，是特意这样设置的吗？能否提供一个同时格式化value的方法
![_20170315091628](https://cloud.githubusercontent.com/assets/25999143/23929310/1c1d4a8e-0960-11e7-861e-999b355a6918.png)

http://jsfiddle.net/nbycxvvy/2/

**Comment by Leopoldthecoder** [comment]
是的，format 仅对显示有效。value 的话，可以自己在一个计算属性里对它格式化。
