### ISSUE TITLE
tree的data怎么即时获取？

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3507]
getCheckedNodes() 方法可以获取到被选中的元素，但如果要在页面上即时显示被选中的元素呢？使用computed会报错，直接在模板中 {{$rer.tree.getCheckedNodes()}} 也会报错。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
