### ISSUE TITLE
npm run dist代码构建失败的2个问题

### ISSUE THREAD

**Issue by dongsir** [ElemeFE/element#3508]
### 代码构建失败的2个问题（环境：node v6.10.0）

#### 问题一：

> Lerna v2.0.0-beta.38
Independent Versioning Mode
Lerna version mismatch: The current version of lerna is 2.0.0-beta.38, but the Lerna version in `lerna.json` is 2.0.0-beta.32. You can either run `lerna init` again or install `lerna@2.0.0-beta.32`.

- npm install 安装的lerna的版本是Lerna v2.0.0-beta.38，而不是package.json中的 2.0.0-beta.32。统一改成 2.0.0-beta.38后可解决此问题

#### 问题二：
> /Users/xxx/Dev/Workspace/Vue/element/packages/slider/src/button.vue
  157:10  error  Newline required at end of file but not found  eol-last
/Users/xxx/Dev/Workspace/Vue/element/packages/tabs/src/tab-nav.vue
  174:10  error  Newline required at end of file but not found  eol-last
/Users/xxx/Dev/Workspace/Vue/element/packages/upload/src/upload-dragger.vue
  30:10  error  Newline required at end of file but not found  eol-last
3 problems (3 errors, 0 warnings)

- 这三个文件缺少换行符导致eslint构建不通过，手工处理后，可解决

**Comment by Leopoldthecoder** [comment]
删除 node_modules，重新用 yarn 安装依赖即可。
