### ISSUE TITLE
【bug】safari 下 table 滚动条不能滚动

### ISSUE THREAD

**Issue by littlefire-sheng** [ElemeFE/element#3509]
![2f47d58a-d71e-80a1-d570-45d555e56b4e](https://cloud.githubusercontent.com/assets/20022183/23931289/7025d504-096c-11e7-879f-3509b0745ab4.png)
![image](https://cloud.githubusercontent.com/assets/20022183/23931299/77abc842-096c-11e7-9d4c-b9309cda0c48.png)
直接在苹果电脑上 这个版本的 safari 浏览器 浏览官网 然后两个表格的滚动条都不能滚动

**Comment by littlefire-sheng** [comment]
通过鼠标点击来滚动 滚动不了，滚轮是可以滚动的

**Comment by Leopoldthecoder** [comment]
Duplicate of #3710
