### ISSUE TITLE
MessageBox输入时一直上下跳动

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#351]
### ElementUI version
1.0.0-rc.6

### Vue version
2.0.2

### Reproduction Link
https://jsfiddle.net/erguotou525/5ja86yj9/1/

### Steps to reproduce
点击打开弹出框，随便输入内容，可以发现`el-dialog__wrapper`一直在添加/删除`class`导致弹出框一直闪。貌似和`vue`版本和`element-ui`的版本有关。

**Comment by perfectyang** [comment]
刚试了，是跟vue2.0.2就有问题，2.0.1就没有问题

**Comment by Leopoldthecoder** [comment]
已确认，出现问题的原因是：昨天的 vue-template-compiler 编译出来的包含 v-show 的代码和今天的 vue 2.0.2 不兼容。下次发布新版时使用最新的 vue-template-compiler 编译就不会有问题了。
