### ISSUE TITLE
为何不能一次选择多个文件上传?

### ISSUE THREAD

**Issue by snoopy83101** [ElemeFE/element#3511]
http://element.eleme.io/#/zh-CN/component/upload
中没有提供选择多个文件上传的例子, 下面Attribute 有一个multiple, 也没有用

拖拽上传的例子已经有该参数, 仍然无法选择多个文件

**Comment by pod4g** [comment]
官方给的例子确实是这样的，`drap`组件有`multiple`确无法选择多个文件，但是实际项目中，确没有问题，不信你可以试试。。
下面是我代码：
```html
<el-upload
                action="upfornewcms.php"
                drag
                accept="image/*"
                :before-upload="handleBeforeUpload"
                :on-success="handleSuccess"
                :on-error="handleError"
                multiple
                >
                <i class="el-icon-upload"></i>
                <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
                <div class="el-upload__tip" slot="tip">只能上传jpg/jpeg/png/gif文件，且不超过500kb</div>
              </el-upload>
```

**Comment by Leopoldthecoder** [comment]
因为文档上把 multiple 拼错了……😂

**Comment by Kingwl** [comment]
哈哈哈

**Comment by snoopy83101** [comment]
我也刚刚发现了这个问题. ..额...这我没啥可说的, 没想到我这种萌新也可以找到文档错误.

**Comment by K-walker** [comment]
@Leopoldthecoder  不还意思，multiple 拼对了也还是无效 :multiple="false" 还是能够多选，无法单选，官方栗子就能复现 [Demo](https://jsfiddle.net/w41vc3ro/)

**Comment by K-walker** [comment]
@snoopy83101  你好，请问一下设置：multiple=“false” 还是可以多选文件，这个问题你解决了吗？官方说是单词拼错了，但是拼对了也还是没有任何作用，多选是可以，但是单选就是不行。

**Comment by mboo2005** [comment]
@K-walker multiple值需要boolean格式，这样写试试  <el-upload :multiple="false" >
:multiple 有冒号

**Comment by cloudLiu** [comment]
我的直接写 multiple 这个就可以多选了，接口也调了多次，但是on-success只回调一次，这是为啥呢。我怎么拿到前几次的文件呢。

**Comment by wjy397** [comment]
> 我的直接写 multiple 这个就可以多选了，接口也调了多次，但是on-success只回调一次，这是为啥呢。我怎么拿到前几次的文件呢。

请问怎么解决的 on-success只回调一次的问题

**Comment by adsjkqhaoran** [comment]
> > 我的直接写 multiple 这个就可以多选了，接口也调了多次，但是on-success只回调一次，这是为啥呢。我怎么拿到前几次的文件呢。
> 
> 请问怎么解决的 on-success只回调一次的问题

确实这个问题怎么解决嘛
