### ISSUE TITLE
[Bug Report] InputNumber组件鼠标左右键一起按下会导致值一直自增加

### ISSUE THREAD

**Issue by devrsi0n** [ElemeFE/element#3514]
### Element UI version
1.2.4

### OS/Browsers version
Win7/Chrome 55

### Vue version
2.2.4

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/input-number](http://element.eleme.io/#/zh-CN/component/input-number)

### Steps to reproduce
在 input-number 组件的“+”按钮上面鼠标左右键一起按下会导致组件值一直增加到最大值，且不能再减少。

### What is Expected?
组件值 +1

### What is actually happening?
组件值一直自加至最大值

**Comment by pengchongfu** [comment]
按下左键触发timer，记录下timer的id；同时按下右键生成新的timer，记录下新的timer的id，原来timer并没有被清除。

因此每次生成新的timer前把原来的清除就好。

**Comment by Leopoldthecoder** [comment]
Fixed in #3731
