### ISSUE TITLE
[multiple select option-group]多选的value错误

### ISSUE THREAD

**Issue by dragoncheey** [ElemeFE/element#3518]
### ElementUI version
 1.2.3 

### OS/Browsers version
 windows 10/Chrome 55

### Vue version
 2.0.0-rc.4 

### Steps to reproduce
<el-select v-model="sensors" multiple placeholder="请选择传感器">
                    <el-option-group v-for="group in sensorsOptionList" :label="group.label">
                      <el-option v-for="item in group.options" :label="item.label" :value="item.value" :disabled="item.disabled">
                      </el-option>
                    </el-option-group>
                  </el-select>
其中:sensorsOptionList=[{"label":"仓库1","options":[{"value":10,"label":"1 #"},{"value":11,"label":"2 #"},{"value":12,"label":"3 #"}]},{"label":"仓库2","options":[{"value":13,"label":"4 #"},{"value":14,"label":"5 #"},{"value":15,"label":"6 #"},{"value":16,"label":"7 #"}]},{"label":"仓库3","options":[{"value":17,"label":"8 #"},{"value":18,"label":"9 #"}]},{"label":"仓库4","options":[{"value":19,"label":"10 #"}]}]

选择其中的某些之后，查看debugger的值sensors=[10,12] ，UI显示label内容[1# ,3#]
### What is Expected?
刷新UI，sensors的值为[10,12]，UI显示的不是label内容，而是值[10,12]，改变sensors为[16,17,18],UI显示为[16,17,18]而不是[7#,8#,9#]
![1](https://cloud.githubusercontent.com/assets/20430176/23938879/2348e960-0999-11e7-97d2-f90022ca124b.png)

### What is actually happening?
![2](https://cloud.githubusercontent.com/assets/20430176/23938889/2d5e4b3e-0999-11e7-8bc9-3b808238b9e7.png)

**Comment by Leopoldthecoder** [comment]
提供一下在线 demo

**Comment by dragoncheey** [comment]
项目没上线，没法提供啊。。。

**Comment by dragoncheey** [comment]
我想想办法

**Comment by Leopoldthecoder** [comment]
用 jsfiddle 就可以

**Comment by dragoncheey** [comment]
https://jsfiddle.net/1gd8mv86/1/

日了狗。。。云端同样的代码竟然正常，本地死都不行。郁闷中。尴尬。关闭吧，我自己找找问题

**Comment by Leopoldthecoder** [comment]
嗯，有问题可以再打开。

**Comment by dragoncheey** [comment]
找到原因了。我的sensors=["10","12"]值是string类型，不是number类型
