### ISSUE TITLE
Upload 上传了之后, 图片列表选择一张作为首图的最佳方案是什么?

### ISSUE THREAD

**Issue by snoopy83101** [ElemeFE/element#3519]
Upload 上传了之后, 目前可以做的操作好像只有删除. 是这样吗?

**Comment by maxwelltsai1536** [comment]
你可以自己给图片加排序 第一张作为cover就好了

**Comment by snoopy83101** [comment]
如果想要第二张的话, 目前upload中就不行了吧, 还得绑定其他元素了?

**Comment by MaxwellCai** [comment]
那就排序把把第二张图片排序到第一张 然后他还是封面咯

**Comment by baiyaaaaa** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
