### ISSUE TITLE
日期控件中的周设置从周一开始显示问题

### ISSUE THREAD

**Issue by myMrTan** [ElemeFE/element#3520]
在API里面Attributes中的参数可以直接在标签中进行设置，但是Picker Options中的参数要怎么设置？

**Comment by Leopoldthecoder** [comment]
文档里有表格：
![image](https://cloud.githubusercontent.com/assets/10095631/23978756/ab24cf88-0a30-11e7-98d5-d4c6b60c06db.png)

例子里也有实际代码。
