### ISSUE TITLE
table 在单选情况下的2个疑问

### ISSUE THREAD

**Issue by rhinonan** [ElemeFE/element#3521]
-  table在单选情况下手动设置选中哪一行， 试过了toggleRowSelection [jsfiddle](https://jsfiddle.net/husan/4n7Ly4eg/1/)
-  table在单选情况下，无法设置哪一行无法被选中。多选状态下可以使用reander来确定一个checkbox是否disabled  (想到的办法是可以通过设置一样的禁用的样式来达到灰掉的效果，但是无法阻止鼠标的点击事件。也无法通过toggleRowSelection 来取消选中的状态)

**Comment by Leopoldthecoder** [comment]
目前 toggleRowSelection 仅支持多选，单选模式下手动设置选中行会在以后加入。禁用的问题也会考虑。
