### ISSUE TITLE
[el-tag]使用v-for后样式有误

### ISSUE THREAD

**Issue by yuanmoon** [ElemeFE/element#3522]
问题重现——https://jsfiddle.net/ywh6gyns/3/

问题说明——在el-tag中使用v-for进行循环输出，标签之间间隔消失；不使用v-for进行枚举输出，标签样式正常

**Comment by Leopoldthecoder** [comment]
这个不是 bug：https://jsfiddle.net/leopoldthecuber/ywh6gyns/5/
想要 margin 的话，自己写 CSS 就行。

**Comment by liangxinhui** [comment]
我觉得应该算是bug吧
