### ISSUE TITLE
有两个问题，1.2.0 dialog的遮罩层不显示，升级到1.2.3后显示了，但table的高度会循环收缩，怎么解决

### ISSUE THREAD

**Issue by BusyHe** [ElemeFE/element#3525]

**Comment by Leopoldthecoder** [comment]
可以考虑先把 Vue 降级到 2.1.10。如果不需要使用 Element 1.2 的新功能，那么降级 Element 也可以。

关于 Table 的高度收缩，是否 1.2.0 版本中没有这个问题？

**Comment by BusyHe** [comment]
ok，我都降级了，一切正常了。1.2.0中没有高度收缩这种情况，我设置el-table css的高度100%，然后设置height="auto",

**Comment by Leopoldthecoder** [comment]
好的，我定位一下问题。

**Comment by BusyHe** [comment]
@Leopoldthecoder 麻烦了

**Comment by Leopoldthecoder** [comment]
这个 issue 先关掉了，Table 的问题会在 #3238 同步。

**Comment by BusyHe** [comment]
ok
