### ISSUE TITLE
Notification feature request: Option for Position

### ISSUE THREAD

**Issue by dancampbell691** [ElemeFE/element#3529]
The notification component (http://element.eleme.io/#/en-US/component/notification) can only be offset from the top right corner, as far as I can tell.  Could we, at a minimum, add an option to specify the position as "bottom", then have the offset be from the bottom right?  

For completeness, the jquery-based toastr-js notifier offers the following position options:
Top Right
Bottom Right
Bottom Left
Top Left
Top Full Width
Bottom Full Width
Top Center
Bottom Center

Keep up the great work!  It's fantastic!

**Comment by Leopoldthecoder** [comment]
Open to discussion. We'll reevaluate if this is a popular demand.

**Comment by mcfaddr** [comment]
I agree that this would be a great addition.  My users are conditioned to notifications appearing in the bottom right as well.

**Comment by Leopoldthecoder** [comment]
I'll implement this next week.

**Comment by Leopoldthecoder** [comment]
Added in #6231
