### ISSUE TITLE
此BUG不修复，将成为element遗留的包袱

### ISSUE THREAD

**Issue by chaifu** [ElemeFE/element#3535]
标题说的比较严重，其实也并无道理。
之前提过了一个issues https://github.com/ElemeFE/element/issues/3105  尚未解决。

bug描述：在表格页面（目前是表格）。只要含有弹出（比如tooltip控件/select/日期 等控件）都会出现表格乱晃的问题。 在chrome浏览器，Windows非常明显（mac也有，只是不明显），只要该页面含有表格，并且使用了弹出控件，当页面内容高度正好到达浏览器出现滚动条的时候，鼠标触发这些控件，都会出现页面乱晃问题。
element很多控件都采用此模式，并且很多控件都还有此问题，

**Comment by chaifu** [comment]
其实是先后问题  等待官方解决。某 vue ui，弹出控件模式与element不一样，没有出现这样的问题

**Comment by lincenying** [comment]
mac chrome 56没发现任何问题.

**Comment by chaifu** [comment]
没有发现问题 说明你的页面高度 没有调整对

**Comment by pod4g** [comment]
正常情况下，从来没有遇到过这个问题。
但是看到你的描述，在jsfiddle下试了试，调整页面高度到你截图的哪儿，确实会出现页面左右抖动，用户体验确实不怎么样。
目测是弹窗超出了页面高度，然后右侧出现了滚动条，导致表格向左挤了，然后滚动条一闪就没了，挤压又恢复了，所以导致左右抖动了一下。

**Comment by chaifu** [comment]
我们做的项目中 用到的表格比较多，当然，表格与select框 搭配也是常事情，
经常的遇见这样的问题，案例只是小块区域，当整个页面出现这样的情况 （晃动），确实体验式上怪怪的

**Comment by pod4g** [comment]
你试着从样式上解决这个问题。在body上或你页面的主容器上加上`overflow-y:hidden`试试

**Comment by chaifu** [comment]
个人觉得：在触发时，底层实现是有问题的，默认是先渲染插入dom内容，然后display:none;然后再次显示出来；
对比bootstrap的tooltip的，默认是插入display:none;的dom，然后再显示。同样在body跟节点插入，机制不一样的；
对于别的ui，则实现的原理是在 你模块内插入弹出的内容，比如bootstrap的下拉菜单多选什么的；

**Comment by suzi404** [comment]
uc需要你

**Comment by Leopoldthecoder** [comment]
包袱在 #3565 里卸掉了

**Comment by SidFeng** [comment]
此标题震惊了所有人！

**Comment by 1008611** [comment]
2.0.7版本时候，没出现这个问题。创建新项目，升级版本，遇到了这个问题，刷新数据时候，table抖动~~~
