### ISSUE TITLE
需求：tree组件能获取所有checkbox为indeterminate 的状态

### ISSUE THREAD

**Issue by AnyGong** [ElemeFE/element#3538]
RT

**Comment by Leopoldthecoder** [comment]
后面会考虑。目前可以参考 #1639 来做。

**Comment by AnyGong** [comment]
谢谢！

**Comment by kopheece** [comment]
@Leopoldthecoder  发现一个问题，已官网的【树节点的选择】为例子，比如一开始选中的节点是“三级 1-1-2”，通过#1639 您的例子，同时保存了“三级 1-1-2”和“一级 1，二级 1-1”这些选中的和半选中的节点。然后再次渲染树节点时候，后台传过来的是“三级 1-1-2”和“一级 1，二级 1-1”这些选中和半选中节点的ID数组，通过setCheckedKeys后，变成节点“一级 1”及其下级的所有节点都被选中。
期望选中的只是节点“三级 1-1-2”，节点“一级 1，二级 1-1”半选中，在之前的1.1.5版本是可以的，升级到1.2.4版本后就不行了。

**Comment by kopheece** [comment]
@Leopoldthecoder 今天公司网络打不开jsfiddle，所以上面没能给demo，抱歉

**Comment by kopheece** [comment]
@Leopoldthecoder  demo: https://jsfiddle.net/LL0orcbr/   在通过 通过 node 设置：期望的是“一级 2”是半选中，'二级 2-1'选中，'二级 2-2'不选中

**Comment by Ignorantforce** [comment]
@Leopoldthecoder 8月份了，是否有计划支持 tree indeterminate 状态相关的功能呢？很多时候子节点选中的话，父节点就算indeterminate 也是想获取的（或者回显相关）。
