### ISSUE TITLE
windows7 运行npm dev run有报错，页面打不开

### ISSUE THREAD

**Issue by straff1983** [ElemeFE/element#354]
> element-ui@1.0.0-rc.6 build:file D:\work\element-master
> node build/bin/iconInit.js & node build/bin/build-entry.js

[build entry] DONE: D:\work\element-master\src\index.js

[cooking] - Loaded success: vue2
[cooking] - Loaded success: lint

[cooking] - Loading server...
[cooking] - Listening at http://localhost:8085
Build completed in 1.945s

**ERROR in multi app
Module not found: Error: Cannot resolve module 'eslint-loader' in D:\work\elemen
t-master
 @ multi app
Child html-webpack-plugin for "index.html":**

webpack: bundle is now VALID.

看上面加粗的那部分
用IE打开页面上就显示Cannot GET

**Comment by QingWei-Li** [comment]
请使用 npm 3

**Comment by straff1983** [comment]
你好，我用的是3.10.8，最新的npm安装，已经清空node_modules，还是以下问题：
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\work\\nodejs\\node.exe" "C:\\Users\\Andy\\AppData\\Roaming\\n
pm\\node_modules\\npm\\bin\\npm-cli.js" "install" "element-ui@next" "-S"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install element-ui as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\element-master\npm-debug.log
 
谢谢！

**Comment by Leopoldthecoder** [comment]
@straff1983 你是把 element 的仓库 clone 下来，然后在里面执行了 `npm install element-ui@next -S`？

**Comment by straff1983** [comment]
啊，是的，我也发现了，我现在clone以后直接run dev成功了，非常感谢！

**Comment by straff1983** [comment]
打扰一下，你们都用什么ide开发？谢谢！
