### ISSUE TITLE
[Bug Report]  MessageBox弹出 整个页面 body会多出17像素的右padding值

### ISSUE THREAD

**Issue by baimiaolei** [ElemeFE/element#3541]
### Element UI version
1.2.4

### OS/Browsers version
win10  /chrome 55

### Vue version
2.2.1

### Reproduction Link
[官网也有，只是官网有滚动条 看不出来抖动](官网也有，只是官网有滚动条 看不出来抖动)

### Steps to reproduce
暂无 页面  还没进入生产环境

### What is Expected?
页面不抖动 也没有那个白条，希望能告知怎么改这个

### What is actually happening?
有了白条 页面抖动

**Comment by Leopoldthecoder** [comment]
MessageBox 出现时默认会阻止 body 元素的滚动，如果在它出现前 body 是有滚动条的，那么就会在出现时给 body 加上一个 padding-right，其值等于滚动条的宽度，防止页面抖动，效果可以看 https://jsfiddle.net/leopoldthecuber/Lgw9v9cb/ 。如果不需要这个机制，可以将 `lockScroll` 关闭。

看你的描述，是没有滚动条的时候也会出现 padding-right？如果是的话，请写个 demo。

**Comment by baimiaolei** [comment]
@Leopoldthecoder  是的 我只有中间一点点是滚动的 其他地方都是不动的  我试试这个关闭的 看能不能改好，不行的话 我写个demo  感谢回复

**Comment by baimiaolei** [comment]
@Leopoldthecoder  已解决  感谢

**Comment by suzi404** [comment]
@Leopoldthecoder 我这还是有bug，1.2.5的版本，
我在做的项目里面调用弹窗框，参数都一样的情况下，有时候会出现，body上加了padding-right:17px，但是没有加overflow：hidden。我翻了下源代码，在messagebox.js里，只有移除body上样式的事件，没找到哪里加样式的事件。
我想问下， 有什么判断的情况下是只加padding而不加overflow的？？

**Comment by xiangshichongfeng** [comment]
@baimiaolei ,我也遇到了这个问题，想问下，你这个后来怎么解决的？
