### ISSUE TITLE
在已经使用了本框架的前提下, 如果要在一页中做一个web的bpm流程设计器,最好的技术方案是怎么选型的?

### ISSUE THREAD

**Issue by snoopy83101** [ElemeFE/element#3542]
在已经使用了本框架的前提下, 如果要在一个.vue页面中做一个web的bpm流程设计器,最好的技术方案是怎么选型的?
比如
http://demo.bpmn.io/

![image](https://cloud.githubusercontent.com/assets/24613784/23984694/da7ce43a-0a55-11e7-8780-a5708016c9af.png)

这种的. 但是我们首选框架是vue, 他不像element, 因为跟vue的关系并不密切.

有没有更好的选型推荐呢?

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by snoopy83101** [comment]
@Leopoldthecoder 大神能否私下里指点一下呢? 哪怕是"不清楚"也是我需要的回答之一.

**Comment by chping2125** [comment]
@snoopy83101 有何解决方案
