### ISSUE TITLE
[Feature Request] 功能改进建议: 希望el-table支持拖拽排序

### ISSUE THREAD

**Issue by istobran** [ElemeFE/element#3543]
http://element.eleme.io/#/zh-CN/component/table
看了官方文档之后发现这个表格是按列实现的
这也导致了el-table没办法直接使用vue.draggable和vue-sortable组件库来进行拖拽排序
希望el-table能够实现行的拖拽排序

**Comment by ilvsx** [comment]
+1

**Comment by ilvsx** [comment]
不过目前可以用 https://github.com/RubaXa/Sortable 来做拖拽

```
import Sortable from 'sortablejs'

let el = document.querySelectorAll('.el-table__body-wrapper > table > tbody')[0]
let sortable = Sortable.create(el)
```

**Comment by SidFeng** [comment]
+1 其实只要能让我把属性draggable="true" 加到行上去就可以，目前好像不能单独对行增加属性

**Comment by zzzgit** [comment]
有些公司会有这个需求，希望加上这个功能

**Comment by zzzgit** [comment]
https://github.com/RubaXa/Sortable 拖拽之后，数据模型的顺序并不会跟着变，这是个麻烦事

**Comment by mengyubo** [comment]
同求此问题，拖拽列，并且再次的resize，如果只是拖拽还好，但是还需要再次resize，数据模型并没有跟着变，楼上有解决方案吗，还是换了控件？

**Comment by yobi-maggie** [comment]
同求此功能

**Comment by ark930** [comment]
同求

**Comment by langlong149** [comment]
同求

**Comment by Leopoldthecoder** [comment]
提供一个结合 Sortable 的例子：https://jsfiddle.net/gozhg07a/

关于数据模型，其实 Sortable 提供了 `onEnd` 钩子，上面的例子就是在这个钩子里完成了数据的同步。

**Comment by Andyliwr** [comment]
@Leopoldthecoder 通过splice改变了数组(this.products)，但是页面上表格行的顺序并未刷新的问题该如何解决呢?

**Comment by aweiu** [comment]
@Andyliwr 我目前是调用el-table实例的`$destory`和`$mount`方法实现重绘的。。
更彻底点可通过`v-if`实现重绘

**Comment by BlackEyeByLee** [comment]
跟sortable.js一起玩      
const el = document.querySelectorAll('.el-table__header-wrapper tr')[0]
      this.sortable = Sortable.create(el, {
        filter: '.el-table-column--selection',
        disabled: true, // 禁用
        animation: 180,
        delay: 0,
        setData: function(dataTransfer) {
          dataTransfer.setData('Text', '')
          // to avoid Firefox bug
          // Detail see : https://github.com/RubaXa/Sortable/issues/1012
        },
        onEnd: evt => {
          // 拖动时sortTable改变了el，
          // 手动转换data
          const oldItem = this.dataTheadList[evt.oldIndex]
          this.dataTheadList.splice(evt.oldIndex, 1)
          this.dataTheadList.splice(evt.newIndex, 0, oldItem)
        }
      })

**Comment by BlackEyeByLee** [comment]
用sortable.js其实可以做到列拖动或者行拖动


>         <el-table border max-height="400" :data="tableData" tooltip-effect="dark" size="mini" @row-dblclick="rowDblClick">
          <el-table-column :type='dataTheadList[index] === "selection" ? "selection" : ""' :prop="dataTheadList[index]" show-overflow-tooltip :label='item' v-for="(item, index) in elTheadList" :key="`thead_${index}`">
          </el-table-column>
        </el-table>

>       const el = document.querySelectorAll('.el-table__header-wrapper tr')[0]
      this.sortable = Sortable.create(el, {
        filter: '.el-table-column--selection',
        disabled: true, // 禁用
        animation: 180,
        delay: 0,
        setData: function(dataTransfer) {
          dataTransfer.setData('Text', '')
          // to avoid Firefox bug
          // Detail see : https://github.com/RubaXa/Sortable/issues/1012
        },
        onEnd: evt => {
          // 拖动时sortTable改变了el，
          // 手动转换data
          const oldItem = this.dataTheadList[evt.oldIndex]
          this.dataTheadList.splice(evt.oldIndex, 1)
          this.dataTheadList.splice(evt.newIndex, 0, oldItem)
        }
      })

**Comment by Palenew** [comment]
真的很需要 😂

**Comment by pyuany** [comment]
+1

**Comment by ahDDD** [comment]
在el-dialog中使用, 需要加一个setTimeout才能使用? 这是为何
[jsfiddle](https://jsfiddle.net/gozhg07a/94/)

**Comment by zzzgit** [comment]
nextTick可以嗎

**Comment by appleCXT** [comment]
很需要行拖拽，还有跟后台的数据交互灵活些，用sortablejs onMove无法获取拖拽前节点的数据，不是单单获取节点的html

**Comment by jocabrera** [comment]
@BlackEyeByLee  
Do you have a complete example of how it works by dragging the columns?

**Comment by jocabrera** [comment]
How use Sortable.js with table columns?

**Comment by jocabrera** [comment]
Here is an example of how to drag the columns with Sortable.js

https://jsfiddle.net/gozhg07a/295/

**Comment by c4cat** [comment]
如果发现view无论如何都没有更新, 尝试加上row-key

**Comment by BlackHole1** [comment]
+1 很需要这个功能

**Comment by guokangf** [comment]
@jocabrera 
not column. how to use row

**Comment by jocabrera** [comment]
@guokangf 
using drag and drop in the row. https://jsfiddle.net/gozhg07a/416/

**Comment by Hanzhuo0322** [comment]
附议

**Comment by MohitTilwani15** [comment]
Has anyone tried show and hide columns using checkbox group and also drag and drop. the checkbox group has different checkboxes based on number of columns and toggling checkboxes will show/hide the column and also drag and drop works fine with it?

**Comment by liub1934** [comment]
表格数据没有重绘的加个row-key就行了，row-key和ID一样需要设置唯一的一个字段名

**Comment by Lara-gru** [comment]
Try this https://github.com/WakuwakuP/element-ui-el-table-draggable for el-tabel - drag-n-drop row

**Comment by zymchan** [comment]
> 提供一个结合 Sortable 的例子：https://jsfiddle.net/gozhg07a/
> 
> 关于数据模型，其实 Sortable 提供了 `onEnd` 钩子，上面的例子就是在这个钩子里完成了数据的同步。

这里你使用了钩子  但是还是需要绑定唯一的row-key。能不能不绑定row-key？

**Comment by xxLion** [comment]
> Here is an example of how drag-drop columns with Sortable.js
> 
> https://jsfiddle.net/gozhg07a/295/

hi bro, using drag and drop in the columns,The table will flash.
Look forward to your favourable reply.
demo: https://codepen.io/xxlion/pen/abzjKMg

**Comment by cloydlau** [comment]
Neither row-key nor v-if redraw is effective in v2.13.2. $destroy+$mount is ok but some other issues occured, view is still probably not synchronized with data when appending or deleting of rows. I tried emptying the value before setting it, and it finally worked......

I encapsulated a small component, it's easy and configurable, should meet most needs.  [git link](https://github.com/cloydlau/elastic-list)

我用的v2.13.2版本 row-key和v-if重绘都没有效果...... 用$destroy+$mount有效果 但是产生了其他的问题 比如结合行的添加和删除功能的时候 仍然存在视图不更新的问题。后来采用在赋值之前先清空一次的方式 终于解决了......

封装了个小组件 简单灵活 应该可以覆盖大部分需求 [git地址](https://github.com/cloydlau/elastic-list)

`<ElasticList v-model="value">
      <el-table-column label="a" prop="a"/>
      <el-table-column label="b" prop="b"/>
</ElasticList>`

**Comment by sunmaolin** [comment]
树形表格拖拽排序真的很费脑，看来官方是不考虑这个功能了

**Comment by freemedom** [comment]
我在el-table上使用clone，但是每次clone都会在原table中加入clone出来的el-table无法控制的一行，更新数据后table中仍会保留clone的这一行。（row-key不管用）解决办法是

> 我目前是调用el-table实例的$destory和$mount方法实现重绘的。。
> 更彻底点可通过v-if实现重绘

不过我没理解$mount是怎么用的，我是用的v-if @aweiu
