### ISSUE TITLE
[Bug Report] collapse 折叠面板手风琴模式下 name = 0 时无法关闭

### ISSUE THREAD

**Issue by leezng** [ElemeFE/element#3544]
# [Bug Report] collapse 折叠面板手风琴模式下 name = 0 时无法关闭

使用 `name` 属性定义唯一标识，当 `name = 0` 时，该折叠面板无法关闭，可见 [JSFiddle URL](https://jsfiddle.net/ozjah6qz/)

### ElementUI version
1.2.4

### OS/Browsers version
Windows7 / Chrome 55

### Vue version
2.1.10

下面截取 collapse.vue 的代码，感觉是判断 `this.activeNames[0] &&  ...` 时由于是 `0` 直接 `return false`

```js
methods: {
  setActiveNames(activeNames) {
    activeNames = [].concat(activeNames);
    let value = this.accordion ? activeNames[0] : activeNames;
    this.activeNames = activeNames;
    this.$emit('input', value);
    this.$emit('change', value);
  },
  handleItemClick(item) {
    if (this.accordion) {
      this.setActiveNames(
        this.activeNames[0] &&
        this.activeNames[0] === item.name
        ? '' : item.name
      );
    }
  }
}
```

**Comment by Leopoldthecoder** [comment]
Fixed in #3546

**Comment by reverland** [comment]
其实我想吐槽为啥想不开用0来做name……

**Comment by leezng** [comment]
官方给的例子是用字符串1,2...这样的，一般都是for循环渲染，为了可以马上看到实现的效果，那就很自然而然的用索引去做name，毕竟看效果跟最终使用的值是两回事 @reverland
