### ISSUE TITLE
关于主题的问题，怎么不生效

### ISSUE THREAD

**Issue by cddsgtc** [ElemeFE/element#3545]
本人用vuepack，然后按照教程引入了项目，也能起作用。然后把教程的效果放到一个vue文件里。
但是有个疑问，既然已经有主题了，为什那么还要在教程中的代码中写上style元素

![p1](https://cloud.githubusercontent.com/assets/16315661/23989859/11ae6244-0a6f-11e7-8d51-368c19d90be0.jpg)
但是当我把这些非theme样式去掉后，样式没有了。
所以很奇怪theme为什么没有生效。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by cddsgtc** [comment]
先说声对不起，在这个提问之前，
已经去Gitter里问过了，而且在在issue里搜索过相关issue。
看到，两百多的issue我也犹豫要不要发的。
这次是重试element，上次很多事情没解决，而且文档也有问题。
没办法，删了这个没用的提问吧，我在看看怎么回事。

**Comment by Leopoldthecoder** [comment]
这个 style 标签不用管。
