### ISSUE TITLE
table如何获取key值？

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3548]
![image](https://cloud.githubusercontent.com/assets/14192308/23991852/c2241780-0a75-11e7-9a49-0ce0b6d671a4.png)

参考demo： https://jsfiddle.net/ruofeng086/q00r140y/3/

Thanks you in advance.

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/rkw3skwn/
文档有请仔细阅读
