### ISSUE TITLE
el-input的一个bug

### ISSUE THREAD

**Issue by wilsonhxd1986** [ElemeFE/element#355]
@keyup.enter事件无法触发

**Comment by csvwolf** [comment]
<https://jsfiddle.net/gmve9d3p/> 请根据这个提供一下demo代码

**Comment by acelan86** [comment]
借帖子报个input.vue跟picker.vue在vue 2.0.2下的bug
2.0.2不支持动态input type
所以代码中的
```html
<input :type="type" ..
```
挂了

**Comment by wilsonhxd1986** [comment]
代码如下：现在keyup在input中无效，我现在把它加入到外面的div里头就好了，之前我还手动创建过一个原生的 input是可以用的，但是el-input不行，本机的浏览器是360和遨游
<div id="divSearch" justify="center"  @keyup.enter="search">
    
        <el-row :gutter="0"  align="middle" justify="center">
            <el-col :span="24"   align="middle" justify="center" >
              <img  style=" width:360px;" src="../assets/logo.jpg">
            </el-col>

        </el-row>

        <el-row :gutter="0"  align="middle" justify="center">
            <el-col :span="12" :offset="5"  > 
              <el-input :span="12" @keyup.enter="search" v-model="queryModel" placeholder="请输入姓名、身份证、手机号进行查询"></el-input> 
            </el-col>

            <el-col>
              <el-button type="primary" @click.native.prevent="search">查询</el-button>
            </el-col>
        </el-row>
 
    </div>

**Comment by Leopoldthecoder** [comment]
#320 #64
