### ISSUE TITLE
[Feature Request] 为Tree的节点加入禁止选择的属性

### ISSUE THREAD

**Issue by delowong** [ElemeFE/element#3551]
希望Tree组件可以让部分节点禁止选中，类似select的option组件的disabled属性。

**Comment by kelvinLynn1981** [comment]
支持，急需这个功能。。。

**Comment by tipmao** [comment]
非常有用的功能,  强烈建议支持.

**Comment by wyjieying** [comment]
我也需要这个功能，现在有什么办法吗

**Comment by wxnsmile** [comment]
这个功能实现了吗？

**Comment by clarkdo** [comment]
+1

**Comment by markselby9** [comment]
Please check the PR for setting disabled checkbox in Tree component: https://github.com/ElemeFE/element/pull/5720

**Comment by Leopoldthecoder** [comment]
已在 1.4.0 加入此功能。

**Comment by Psychee** [comment]
可以让整个树都是禁止选中的吗
