### ISSUE TITLE
<el-col> :xs :sm :md :lg 情况下可以隐藏

### ISSUE THREAD

**Issue by psychokiller666** [ElemeFE/element#3553]
### ElementUI version
1.2.4

### OS/Browsers version
macos/chrome56

### Vue version
2.2.2

### Steps to reproduce
<el-col :xs="0" :sm="0" :md="4" :lg="4" class="title">推荐视频</el-col>

### What is Expected?
我希望在:xs和:sm页面宽度的时候，这个<el-col>隐藏，

### What is actually happening?
可是并不能生效。

**Comment by Leopoldthecoder** [comment]
Fixed in #3564
