### ISSUE TITLE
组件的destroyed方法中移除事件的方式是错误的。 

### ISSUE THREAD

**Issue by 374632897** [ElemeFE/element#3555]
### ElementUI version

1.2.4
### OS/Browsers version

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
### Vue version

2.0.0
### Reproduction Link
http://jsbin.com/qukasapuha/6/edit?js,console,output

### Steps to reproduce
DEMO中已有说明
### What is Expected?
在组件销毁的时候能够正常移除元素绑定的事件
### What is actually happening?
并没有移除。

如下代码
[main.vue](https://github.com/ElemeFE/element/blob/dev/packages/popover/src/main.vue#L124-L134)
```js
  destroyed() {
    const reference = this.reference;
    off(reference, 'mouseup');
    off(reference, 'mousedown');
    off(reference, 'focus');
    off(reference, 'blur');
    off(reference, 'mouseleave');
    off(reference, 'mouseenter');
    off(document, 'click', this.handleDocumentClick);
  }
```
[dom.js](https://github.com/ElemeFE/element/blob/dev/src/utils/dom.js#L39-L53)
```js
export const off = (function() {
  if (!isServer && document.removeEventListener) {
    return function(element, event, handler) {
      if (element && event) {
        element.removeEventListener(event, handler, false);
      }
    };
  } else {
    return function(element, event, handler) {
      if (element && event) {
        element.detachEvent('on' + event, handler);
      }
    };
  }
})();
```
实际上，当调用ele.removeEventListener的时候， 至少需要两个参数， 如果没有传递第二个参数(handler)， 将会报错。
![image](https://cloud.githubusercontent.com/assets/15151718/24024797/fae71948-0af0-11e7-8530-f6473946594c.png)
而在`off`方法中， 传递了`handler`， 但是在调用中handler为`undefined`, 所以使得`removeListner`方法最后接收到的参数数量是3， 从而避免了报错， 但是事件并没有被移除。当然， 元素已经被销毁了，而即便是事件正常移除， 监听器真正的被移除也是在下一下垃圾回收当中， 那么这个问题也并不是什么问题了。 这里我只是想提出这种方式的不合理之处而已。

**Comment by Leopoldthecoder** [comment]
Fixed in #3672
