### ISSUE TITLE
没有模态窗口组件吗

### ISSUE THREAD

**Issue by TimuJiang** [ElemeFE/element#3557]
没有模态窗口组件吗

**Comment by roy-lau** [comment]
http://element.eleme.io/#/zh-CN/component/message-box
请认真阅读官网！

**Comment by TimuJiang** [comment]
MessageBox 不能自定义内容啊，能传自定义组件进去么

**Comment by Leopoldthecoder** [comment]
Dialog？

**Comment by TimuJiang** [comment]
好吧。我sb了

**Comment by baihe** [comment]
不知道这个问题算不算常见问题，因为我也是一开始认为是 messagebox，在最初的组件里我是直接基于 messagebox 用 createElement 去模拟 modal 的。
大概是因为，我们对 Modal 的常用场景，更多的是像一个「Box」，而不会联想到「Dialog」。
