### ISSUE TITLE
win10 node v6.7.0 npm  v3.10.3 npm run dev 失败

### ISSUE THREAD

**Issue by CharkeyQK** [ElemeFE/element#356]
> element-ui@1.0.0-rc.6 dev C:\Users\Admin\Desktop\element
> npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p

> element-ui@1.0.0-rc.6 bootstrap C:\Users\Admin\Desktop\element
> npm i && lerna bootstrap

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN element-ui@1.0.0-rc.6 No license field.
Lerna v2.0.0-beta.18
Independent Versioning Mode
Linking all dependencies
...
省略若干行
...
Successfully bootstrapped 38 packages.

> element-ui@1.0.0-rc.6 build:file C:\Users\Admin\Desktop\element
> node build/bin/iconInit.js & node build/bin/build-entry.js

[build entry] DONE: C:\Users\Admin\Desktop\element\src\index.js

[cooking] - cooking is local module. You should use cooking-cli

            npm i cooking-cli -g

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\MyEnv\\nodejs_v6.7.0\\node.exe" "D:\\MyEnv\\nodejs_v6.7.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! element-ui@1.0.0-rc.6 dev: `npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@1.0.0-rc.6 dev script 'npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the element-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls element-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Admin\Desktop\element\npm-debug.log

npm-debug.log的内容如下：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\MyEnv\\nodejs_v6.7.0\\node.exe',
1 verbose cli   'D:\\MyEnv\\nodejs_v6.7.0\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle element-ui@1.0.0-rc.6~predev: element-ui@1.0.0-rc.6
6 silly lifecycle element-ui@1.0.0-rc.6~predev: no script for predev, continuing
7 info lifecycle element-ui@1.0.0-rc.6~dev: element-ui@1.0.0-rc.6
8 verbose lifecycle element-ui@1.0.0-rc.6~dev: unsafe-perm in lifecycle true
9 verbose lifecycle element-ui@1.0.0-rc.6~dev: PATH: D:\MyEnv\nodejs_v6.7.0\node_modules\npm\bin\node-gyp-bin;C:\Users\Admin\Desktop\element\node_modules\.bin;D:\MyEnv\nodejs_v6.7.0;C:\Programs\VanDyke Software\Clients\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\MyEnv\Java\jdk1.8.0_40_x64\bin;D:\MyEnv\Java\jdk1.8.0_40_x64\jre\bin;D:\MyEnv\Git\cmd;D:\MyEnv\Maven\MavenHome\bin;D:\MyEnv\nodejs_v6.7.0\;D:\MyEnv\nodejs_v6.7.0\node_global;D:\Xampp\mysql\bin;C:\Programs\TortoiseSVN\bin;D:\MyEnv\Ant\bin;D:\MyEnv\Gow\bin;D:\Oracle\Middleware\Oracle_Home_12c\wlserver\server\lib;C:\Programs\TortoiseSVN\bin;C:\Programs\Pandoc\;D:\MyEnv\Ruby23-x64\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps
10 verbose lifecycle element-ui@1.0.0-rc.6~dev: CWD: C:\Users\Admin\Desktop\element
11 silly lifecycle element-ui@1.0.0-rc.6~dev: Args: [ '/d /s /c',
11 silly lifecycle   'npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p' ]
12 silly lifecycle element-ui@1.0.0-rc.6~dev: Returned: code: 1  signal: null
13 info lifecycle element-ui@1.0.0-rc.6~dev: Failed to exec dev script
14 verbose stack Error: element-ui@1.0.0-rc.6 dev: `npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\MyEnv\nodejs_v6.7.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\MyEnv\nodejs_v6.7.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid element-ui@1.0.0-rc.6
16 verbose cwd C:\Users\Admin\Desktop\element
17 error Windows_NT 10.0.14393
18 error argv "D:\\MyEnv\\nodejs_v6.7.0\\node.exe" "D:\\MyEnv\\nodejs_v6.7.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error element-ui@1.0.0-rc.6 dev: `npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p`
22 error Exit status 1
23 error Failed at the element-ui@1.0.0-rc.6 dev script 'npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the element-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs element-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls element-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by anshengme** [comment]
把当前用户下的npm路径添加到系统的path中：
```
C:\Users\Administrator\AppData\Roaming\npm
```
然后重启就好了。

**Comment by CharkeyQK** [comment]
GOOD!
现在`npm run dev`成功了
`[cooking] - Loaded success: vue2
[cooking] - Loaded success: lint

[cooking] - Loading server...
[cooking] - Listening at http://localhost:8085
Build completed in 42.194s`

现在出现的问题我看 issue 这边也有提到，我看看去。
template syntax error <input :type="type" v-model="currentValue">:
template syntax error <input :type="editorType" v-model="visualValue">:
