### ISSUE TITLE
不使用构建工具，如何单独使用element的组件，比如table？

### ISSUE THREAD

**Issue by wskhehe** [ElemeFE/element#3560]
从https://unpkg.com/element-ui@1.2.4/lib/ 下载单独的table.js 配合table.css。页面中如何使用？

**Comment by QingWei-Li** [comment]
https://unpkg.com/element-table@1.0.0/

Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
