### ISSUE TITLE
upload组件点击按钮，此时页面会重新渲染。

### ISSUE THREAD

**Issue by xiaohan2013** [ElemeFE/element#3561]
问题如题。

在使用upload组件时，点击上传按钮后选择文件的窗口出来是，会闪现一下然后再显示选择文件的窗口。

在表单里，如果填写的数据还没有提交，而去选择上传文件，这时表单里的数据都没有了。猜测是页面进行了重新渲染。

**Comment by Leopoldthecoder** [comment]
请按照格式提交 iss也、
