### ISSUE TITLE
table fix列显示异常（详情看demo）

### ISSUE THREAD

**Issue by ma-xiao-guang-64** [ElemeFE/element#3562]
### What is actually happening?
table fix列显示异常

http://jsfiddle.net/LdrL8La2/4/

**Comment by Leopoldthecoder** [comment]
没看出来哪里异常

**Comment by xiaoguangma** [comment]
@Leopoldthecoder 

不好意思这个bug没描述清楚     特定的分辨率右侧显示框宽度512PX时候会出问题
![2](https://cloud.githubusercontent.com/assets/6637227/24028376/5acc930c-0b09-11e7-8a7f-4bda9d904948.png)

**Comment by xiaoguangma** [comment]
@Leopoldthecoder   这个BUG会出现在cell设置的表格宽度之和接近需要渲染的table的宽度时

**Comment by xiaoguangma** [comment]
@Leopoldthecoder   麻烦关注一下谢谢

**Comment by furybean** [comment]
与 #8158 重复，请关注 #8158 的进度。
