### ISSUE TITLE
MessageBox中Tooltip定位错误

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#357]
### ElementUI version
1.0.0-rc.6

### Vue version
2.0.2

### Reproduction Link
https://jsfiddle.net/erguotou525/9qc4q0dy/1/

### Steps to reproduce
点击弹出模态框，然后鼠标滑到按钮上，发现`tooltip`定位不对。
发现非模态框中正常，定位使用的是`absolute`，但模态框上用的定位就变成`fixed`了。

**Comment by QingWei-Li** [comment]
vue-popper 重构过后这问题已经修复了，下个版本就好了
