### ISSUE TITLE
Improve Japanese translation

### ISSUE THREAD

**Issue by satotakumi** [ElemeFE/element#3570]
I think Japanese translation can improve as below.

DatePicker and DatePicker months: 
```js
    datepicker: {
      month1: '1月',
      month2: '2月',
      month3: '3月',
      month4: '4月',
      month5: '5月',
      month6: '6月',
      month7: '7月',
      month8: '8月',
      month9: '9月',
      month10: '10月',
      month11: '11月',
      month12: '12月',
      months: {
        jan: '1月',
        feb: '2月',
        mar: '3月',
        apr: '4月',
        may: '5月',
        jun: '6月',
        jul: '7月',
        aug: '8月',
        sep: '9月',
        oct: '10月',
        nov: '11月',
        dec: '12月'
      }
   }
```

colorpicker:
```js
    colorpicker: {
      confirm: 'OK',
      clear: 'クリア'
    },
```

I think alphanumeric(英数字) is common than Chinese numeral(Kansūji, 漢数字) because alphanumeric is using many services, places or apps than Chinese numeral.
Secondly, I think translation of "confirm " is easy to understand "OK" than "はい".
"OK" is really common English in Japan. Everybody (maybe) can understand easily .
Also, Photoshop is using "OK" in colorpicker in Japanese version.

Here is Japanese description about this issue.

Elementの日本語翻訳改善についてのIssueです。
カレンダー部分（DatePicker）の月表記については漢数字（一月…十二月）よりも英数字（1月…12月)のほうがわかりやすいと考えています。一般的に様々なアプリやサービスなどをみても英数字を採用している例が多いかと思います。（偏見かもしれませんが笑）

カラーピッカー（colorpicker）の `confirm` 部分は現在「はい」という翻訳になっていますが、「OK」という翻訳が適しているかと思われます。「確定」や「確認」でもいいかとは思いますが「OK」という言葉は広く認知されておりPhotoshopのカラーピッカーなどでも「OK」が採用されています。

![image](https://cloud.githubusercontent.com/assets/8487270/24033540/c715c05c-0b30-11e7-8534-ac34315fc772.png)

![image](https://cloud.githubusercontent.com/assets/8487270/24033543/cec6b248-0b30-11e7-9a22-2dc4b83338cc.png)
![image](https://cloud.githubusercontent.com/assets/8487270/24033568/ed278b5e-0b30-11e7-9de6-7cf12a94a64b.png)

**Comment by potato4d** [comment]
@satotakumi
カラーピッカー、「OK」の部分ですが、「選択」や「決定」ではいかがでしょうか？

**Comment by jikkai** [comment]
@satotakumi さん、ご指摘ありがとうございます。

まずご指摘の2点に従いpull requestしています。
