### ISSUE TITLE
tree 有children就setCheckedNodes不能设置全选了

### ISSUE THREAD

**Issue by ruofeng086** [ElemeFE/element#3571]
在本地用vue-cli构建的代码，无法正常跑，不能全选，点选择checkbox后，点击全选和删除选择却能清空，在JSFiddle里却能正常，实在看不出问题出在哪，麻烦帮看下
贴上链接：https://jsfiddle.net/ruofeng086/z9xc7f0e/
贴个本地的code：
![image](https://cloud.githubusercontent.com/assets/14192308/24033995/6833ea88-0b2a-11e7-95b8-fe48d7739620.png)

![image](http://a.hiphotos.baidu.com/image/pic/item/77094b36acaf2edda3411217841001e93801939f.jpg)
Thanks you in advance.

---update---
去掉数组内的children全选就正常了。

**Comment by Leopoldthecoder** [comment]
版本问题吧，确保 Element 版本为最新。

**Comment by ruofeng086** [comment]
![image](https://cloud.githubusercontent.com/assets/14192308/24089830/aaa360b8-0d75-11e7-9c4f-253cb957666e.png)

这应该是最新版本的吧？
