### ISSUE TITLE
建议： 增加图片预览弹窗

### ISSUE THREAD

**Issue by skioll** [ElemeFE/element#3572]
图片弹窗在很多 地方都会用到，真心希望element-ui的各位大大可以提供图片弹窗使用。
类似：
![image](https://cloud.githubusercontent.com/assets/18202306/24035475/ac192dfc-0b30-11e7-8dba-9589e03325b1.png)
万分感谢

**Comment by QingWei-Li** [comment]
https://github.com/egoist/zoom-image
