### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by xuyingchuan** [ElemeFE/element#3574]
### ElementUI version
lastest

### OS/Browsers version
 macOS/Chrome 53

### Vue version
 2.0.0-rc.4 

### Steps to reproduce
点击二级菜单 最后一个一级菜单h自动展开
### What is Expected?
![image](https://cloud.githubusercontent.com/assets/8023312/24036398/5757f4f2-0b34-11e7-99de-59c16de0d40d.png)

![image](https://cloud.githubusercontent.com/assets/8023312/24036457/9039630a-0b34-11e7-8f56-f54de6378ebd.png)

 希望最后一个不要自动展开

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/8023312/24036374/3a337824-0b34-11e7-942d-8cf44eed5d6f.png)

**Comment by Leopoldthecoder** [comment]
请提供在线 demo

**Comment by xuyingchuan** [comment]
捂脸2333 index没有加冒号 不好意思哈哈
