### ISSUE TITLE
select绑定选择值后，再次渲染页面后绑定数据异常

### ISSUE THREAD

**Issue by stark-summer** [ElemeFE/element#3579]
element 最近版本：1.2.3
问题描述如下：
html原始代码：
```
<el-form-item label="数据源">
         <el-select id="dsList" name="dsList" v-model="dataSetForm.dsId"
                                               placeholder="请选择数据源">
                    <el-option v-for="curDs in dsList" :label="curDs.name"
                                         :value="curDs.id"></el-option>
           </el-select>       
</el-form-item>
```
页面渲染结果是
![image](https://cloud.githubusercontent.com/assets/3336298/24048486/05e35fbe-0b64-11e7-9303-72f3055a4dd1.png)

这就是我们普通的select下拉框的 内容和值
```
<select id="dsList" name="dsList" v-model="dataSetForm.dsId"
                        placeholder="请选择数据源">
    <option v-for="curDs in dsList":value="curDs.id">{{curDs.name}}</option>
 </select>
```
这两种方式我触发下拉后 都可以获取到 下拉框里面的value(编号id,)，而不是内容(下拉框显示的汉字)，
当我保存数据后，当点击修改后，使用vuejs 数据绑定功能，自动会选中 已经设置的值，但使用element，竟然在下拉框上显示value(编号id,)，如下图：
![image](https://cloud.githubusercontent.com/assets/3336298/24048456/e8f9c74e-0b63-11e7-9c43-c460e790bb8a.png)

但是我使用普通的select下拉框，是可以正常选中的，实现数据正确绑定
如下代码：
```
<select id="dsList" name="dsList" v-model="dataSetForm.dsId"
                        placeholder="请选择数据源">
    <option v-for="curDs in dsList":value="curDs.id">{{curDs.name}}</option>
 </select>
```
显示结果
![image](https://cloud.githubusercontent.com/assets/3336298/24048380/a71a12f2-0b63-11e7-8f97-5f6163760f62.png)

**Comment by lincenying** [comment]
注意类型, 1和"1" 并不一样, 确保v-model里的类型和 :value里的类型一致

**Comment by Leopoldthecoder** [comment]
请参照楼上回复。

**Comment by stark-summer** [comment]
恩 搞定了，非常感谢
