### ISSUE TITLE
element表单验证功能，js代码运行有错

### ISSUE THREAD

**Issue by stark-summer** [ElemeFE/element#3580]
elementjs使用最新版本的

我在js里面增加如下代码：
![image](https://cloud.githubusercontent.com/assets/3336298/24050994/9e0480dc-0b6b-11e7-8529-aac387f73a03.png)

或者
![image](https://cloud.githubusercontent.com/assets/3336298/24051044/c782ae8e-0b6b-11e7-8782-75db36ef620e.png)

我是java web项目，竟然有这种提示，无法正常运行
如果注释掉上述代码，在控制台是可以运行的
![image](https://cloud.githubusercontent.com/assets/3336298/24050794/fa09f098-0b6a-11e7-8279-2d5d12e923fb.png)

**Comment by Leopoldthecoder** [comment]
问题在哪里？这个就是你在代码里 alert 出来的。

**Comment by stark-summer** [comment]
问题是 
```
CommmonData.vmMain.$refs.setExpressionForm.validate(function (result) {
                        if (result) {
                            alert('ok');
                        } else {
                            alert("表达验证不合法");
                        }
                    })
```
我的项目嵌入这段js代码，页面无法正常加载，但去掉这段代码就可以正常加载了，
那个alert不是在代码里面的，是在chrome控制台执行的，你看到图片能有alert 的前提是 我的页面是正常加载的，而页面能正常加载的前提是去掉 上面那段表单验证代码

**Comment by Leopoldthecoder** [comment]
给下重现地址。

**Comment by stark-summer** [comment]
sorry，我现在是开发阶段，刚使用element-UI，我加入表单验证代码，在idea上面就提示如下信息：
![image](https://cloud.githubusercontent.com/assets/3336298/24069915/675c11c0-0bee-11e7-98a2-fc31224db6aa.png)
加上那段表单验证代码后，渲染页面如下结果：
![image](https://cloud.githubusercontent.com/assets/3336298/24069924/ae99c53c-0bee-11e7-87dd-824ec90dddcc.png)
请问是不是这种语法，在java web项目里面不支持呢？但去掉那段代码，页面就可要正常渲染了

**Comment by stark-summer** [comment]
可否加我微信(微信号:stark-summer)，我给你具体说下，我这边使用的场景

**Comment by maxwellwei1** [comment]
看看验证规则

**Comment by stark-summer** [comment]
这个issues 我没有解决，为什么给closed呢？

**Comment by Leopoldthecoder** [comment]
因为没有提供重现。
