### ISSUE TITLE
[DateTimePicker ] :editable=false时插件中的日期和时间输入框仍可输入

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#3587]
### ElementUI version

1.2.4
### Vue version

2.2.4
### Reproduction Link

http://jsfiddle.net/g5xp9Lch/
### What is Expected?
希望 :editable=false 时，插件中的日期和时间输入框也为不可输入状态

**Comment by maxwellwei1** [comment]
可以试试在打开日期控件时，手动给那两个插件中的输入框加上"readonly"
