### ISSUE TITLE
form表单，range 校验失效

### ISSUE THREAD

**Issue by semicoder** [ElemeFE/element#359]
### ElementUI version

1.0.0-rc.6

### OS/Browers version

macOS/Chrome53
### Vue version

2.0.1

### Steps to reproduce
在form表单中使用
{required: true, range: {min: 6, max: 20}, message: '长度不正确', trigger: 'blur'}
range校验不起效果
### What is Expected?
range 校验应该生效

**Comment by baiyaaaaa** [comment]
正确用法： {required: true, min: 6, max: 20, message: '长度不正确', trigger: 'blur'}
