### ISSUE TITLE
select修改选项之后未及时更新所选的值。

### ISSUE THREAD

**Issue by gaoyoubo** [ElemeFE/element#3590]
修改选项之后未及时更新值。
我的版本信息如下：
 "element-ui": "^1.2.4",
    "marked": "^0.3.6",
    "vue": "^2.2.2",
    "vue-resource": "^1.2.1",
    "vue-router": "^2.2.0",
    "wangeditor": "^2.1.23",
    "when": "^3.7.8"

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
