### ISSUE TITLE
tree组件示例中append追加按钮操作，点击以后会触发handleNodeClick事件

### ISSUE THREAD

**Issue by chinavane** [ElemeFE/element#3598]
tree组件，在官方事例中，如果操作renderContent中的append按钮，并且在该示例中添加handleNodeClick事件，那么在点击按钮的之后又会再次触发handleNodeClick节点点击操作，如何可以只触发按钮事件，不触发handleNodeClick事件？

**Comment by chinavane** [comment]
好吧，自问自答一下好了。
在按钮区添加event参数
`<el-button size="small" type="success" on-click={ () => { this.append(store, data, event ); } }>添加</el-button>`
append阻止冒泡一下
```
append(store, data, event) {
...
        event.stopPropagation();
}

```

**Comment by savokiss** [comment]
@chinavane 你在 renderContent 方法中是怎么拿到 event的呢？不然也没法放到button上啊

**Comment by savokiss** [comment]
知道了，直接从 箭头函数中传就可以了，renderContent 里面的 JSX：
```javascript
<el-button size="small" type="success" on-click={ (event) => { this.append(store, data, event ); } }>添加</el-button>
```
