### ISSUE TITLE
[Feature Request] Checkbox Button

### ISSUE THREAD

**Issue by mdartic** [ElemeFE/element#3601]
Like the radio element, in [Button Style](http://element.eleme.io/#/en-US/component/radio#button-style),

It would be useful to have the checkbox element, in the same Button Style.

We need this feature for a project, so if you agree, I'm gonna make a PR to give you our implementation, with specs to test it.

**Comment by Leopoldthecoder** [comment]
Merged. Thanks for contributing.

**Comment by mdartic** [comment]
Thanks to you too
