### ISSUE TITLE
MessageBox中表单验证有误

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#361]
### ElementUI version
1.0.0-rc.6

### Vue version
2.0.2

### Reproduction Link
https://jsfiddle.net/erguotou525/9qc4q0dy/3/

### Steps to reproduce
点击弹出模态框，输入框输入内容，下拉框选择选项，结果都会提示验证错误，是不是因为版本的问题？和#357的原因有关？

**Comment by erguotou520** [comment]
Relate #359

**Comment by baiyaaaaa** [comment]
验证的问题是因为rules和model里的字段没对上

**Comment by erguotou520** [comment]
好吧，看来是一定要一致的，文档上关于这块没有详细说明

**Comment by erguotou520** [comment]
其实一开始我提这个是因为我本地有这样的问题，即使把rules和model里的字段对上也还是会报错，但是用上面的demo没有重现出来

**Comment by cench** [comment]
我也碰到了这个情况，字段相同还是验证不通过？

**Comment by erguotou520** [comment]
不记得当时是什么情况了，应该没有再出现过了，你可否提供下你的代码？ @cench
