### ISSUE TITLE
dialog的遮罩层不能覆盖某些元素

### ISSUE THREAD

**Issue by indooorsman** [ElemeFE/element#3611]
dialog是写在组件内部，而不是body的直接子级元素，很容易出现被组件外部的元素遮挡的情况。。。
请问是否考虑把dialog动态插入body中？

**Comment by indooorsman** [comment]
@Leopoldthecoder  https://jsfiddle.net/noqnvdw0/2/

**Comment by indooorsman** [comment]
@Leopoldthecoder https://jsfiddle.net/noqnvdw0/3/

**Comment by indooorsman** [comment]
@Leopoldthecoder https://jsfiddle.net/noqnvdw0/5/

**Comment by Leopoldthecoder** [comment]
Dialog 作为组件不适合「动态插入body中」，页面上各元素的 z-index 需要用户自己规划一下。
