### ISSUE TITLE
通过et构建主题时出现重复的样式

### ISSUE THREAD

**Issue by esioncao** [ElemeFE/element#3617]
通过et构建主题在theme目录下的index.css文件中出现重复的样式
通过浏览器调试查查看如下图
![image](https://cloud.githubusercontent.com/assets/4424631/24092026/bc1d6846-0d86-11e7-857b-af1efd916770.png)
通过查找文件确实也发现了重复的样式如下图
![image](https://cloud.githubusercontent.com/assets/4424631/24092069/f9fa9918-0d86-11e7-88cc-9dd85d9d5b6e.png)
![image](https://cloud.githubusercontent.com/assets/4424631/24092083/093be580-0d87-11e7-9908-0a0cc029e460.png)
![image](https://cloud.githubusercontent.com/assets/4424631/24092133/476ab58e-0d87-11e7-97d5-1f9c6710fae5.png)

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
