### ISSUE TITLE
[Bug Report] cascader 的props属性 不支持动态更新吗？

### ISSUE THREAD

**Issue by rancongjie** [ElemeFE/element#3620]
### Element UI version
1.2.5

### OS/Browsers version
macOS/chrome

### Vue version
2.2.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/7/](https://jsfiddle.net/pj71jkyw/7/)

### Steps to reproduce
点击换语言 不能切换列表语言，但是选中后点切换语言，可以换语言

### What is Expected?
希望能支持动态改变props

### What is actually happening?
更改props 不能改变列表项

**Comment by Leopoldthecoder** [comment]
We have no plan to support this.
