### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by holidaying** [ElemeFE/element#3621]
https://gitter.im/ElemeFE/element。
![image](https://cloud.githubusercontent.com/assets/12896717/24093576/8501c8b2-0d8f-11e7-85e0-d9bbf6bc920c.png)

 <img src="~examples/assets/images/guide.png" alt="">
1、~代表什么意思
2、为什么图片能直接使用，而我们在项目中需要用require引进来

**Comment by rancongjie** [comment]
webpack 的 alias 别名配置
```
    c: {
        'src': path.join(__dirname, 'src'),
        'assets': path.join(__dirname, 'src/assets')
    },
```

在js 中直接 使用别名，在模板中要加上`~`

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by holidaying** [comment]
把issue关闭了吧
