### ISSUE TITLE
table filter当表格有分页，第一页选择了筛选项后。。。到第二页后筛选项还在，但是数据没有过滤。。。。 希望能加上这个功能。。。谢谢

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#3623]
当表格有分页，第一页选择了筛选项后。。。到第二页后筛选项还在，但是数据没有过滤。。。。
希望能加上这个功能。。。谢谢

### ElementUI version

1.2.5
### Vue version

2.1.9

**Comment by ChangeZhang** [comment]
![test3](https://cloud.githubusercontent.com/assets/6948367/24095664/1d4d2450-0d99-11e7-82be-4af69e406195.gif)

![image](https://cloud.githubusercontent.com/assets/6948367/24095643/0310b390-0d99-11e7-90ba-18f8421facee.png)

**Comment by athena0304** [comment]
请问这个解决了么？我也遇到同样的问题了，当表格有分页的时候，只能筛选当页的数据，怎样才能做到全局筛选数据呢

**Comment by imaemo** [comment]
@athena0304 刚好我最近也遇到了这个问题，table 有一个filter-change事件，在filter-change事件处理方法当中，可以手动filter数据，再返回给table，这样就可以了。

**Comment by athena0304** [comment]
@imaemo 嗯嗯，我后来也是这么做的，感谢您的回答~

**Comment by yangyanan05521** [comment]
@imaemo 我也遇到了同样的问题，请问一下filter-change事件中手动筛选数据，是前端自己写筛选吗，怎么实现原有的table-column上的多选多列筛选？而且我不写filter-method发现那个下拉筛选重置的功能就失效了。期待答复，感激不尽~

**Comment by imaemo** [comment]
@yangyanan05521 不好意思，我才看到提醒。我遇到的场景是这样的
![image](https://user-images.githubusercontent.com/11534313/35714185-2901491c-0806-11e8-8943-93826c0d2e16.png)
在第 filter-change中，有一个参数filter, 它包含了当前要过滤的东西是什么，然后再手动过滤一下。大概的代码如下：
``` javascript
handlerFilterChange(filter) {
var filltered_tags = filter['el-table_1_column_7']; // it is an array
	this.fillteredTags = filltered_tags;
	this.loading = true;

	this.fillteredData = this.searchedData.filter(function (item) {
		var flag = false;
		for (var i in item.tag) {
			if ((filltered_tags.indexOf('added') > -1 )
				|| (filltered_tags.indexOf('update') > -1 )
				|| (filltered_tags.indexOf('deleted') > -1)) {
				flag = true;
			}
		}
		return flag;
	});
}
```
希望能对你有帮助

**Comment by yangyanan05521** [comment]
@imaemo 非常感谢你的回复！

**Comment by LixHu** [comment]
遇到一个问题，用filter-change 然后再走api ，双向绑定好像不行了 ， 数据是获取到，也给this 了

**Comment by lixingyangs** [comment]
very nice

**Comment by yaofengxi** [comment]
> ![test3](https://cloud.githubusercontent.com/assets/6948367/24095664/1d4d2450-0d99-11e7-82be-4af69e406195.gif) [ ![test3](https://cloud.githubusercontent.com/assets/6948367/24095664/1d4d2450-0d99-11e7-82be-4af69e406195.gif) ](https://cloud.githubusercontent.com/assets/6948367/24095664/1d4d2450-0d99-11e7-82be-4af69e406195.gif) [ ](https://cloud.githubusercontent.com/assets/6948367/24095664/1d4d2450-0d99-11e7-82be-4af69e406195.gif)
