### ISSUE TITLE
【BUG】NavMenu导航菜单-保持一个菜单的展开

### ISSUE THREAD

**Issue by p2ng** [ElemeFE/element#3624]
### ElementUI version
1.2.3

### OS/Browsers version
Window7
Chrome56

### Vue version
2.1.0

### Reproduction Link
http://jsfiddle.net/p2ng/mpLv0tkg/

### Steps to reproduce
直接RUN链接的代码，查看F12控制台即可出现问题。
也尝试过，均出现一致异常。但是不影响界面操作!!!
unique-opened = true
uniqueOpened = true

### What is Expected?
...

### What is actually happening?
[Vue warn]: Invalid prop: type check failed for prop "uniqueOpened". Expected Boolean, got String. 
(found in <ElMenu>)

**Comment by Leopoldthecoder** [comment]
报错信息说得很清楚了，这样写的话传入的是一个字符串。`=true` 删掉。
