### ISSUE TITLE
[Bug Report] switch组件状态与change事件中的行为不一致

### ISSUE THREAD

**Issue by Tao-Quixote** [ElemeFE/element#3627]
### Element UI version
1.1.3

### OS/Browsers version
win7/Google Chrome	56.0.2924.87 (正式版本) （32 位）

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/TaoQuixote/5vnx100h/1/](https://jsfiddle.net/TaoQuixote/5vnx100h/1/)

### Steps to reproduce
初始时，switch组件绑定的变量switchData的值为false；
第一次点击switch组件时，switchData的值为true，由于switchData2的值为false，所以重新赋值switchData的值为false
第二次再次点击switch组件时，点击之前switchData的值为false，但是此时点击switch组件，在change事件中switchData的值为false；
根据第一次点击的反应来推测，switch组件应该是根据switchData的当前值取反，但是现在的行为是：switch组件在内部自己维护了一个当前的状态，并根据自己内部维护的状态来更新双向绑定的switchData的值

### What is Expected?
Switch组件应该按照绑定的值来决定自己的表现（on或者off），同时应该有一个事件可以用来中断值的改变，即当条件不符合时可以维持当前的值，而不是点击了就一定要更改这个switch组件绑定数据的值

这个需求来源于：一个switch组件能否更改当前的值，取决于另外一个switch组件的值，如果另外一个switch组件的值为false，则不能更改当前switch组件的值。但是现在switch组件的表现就是：不管另外一个switch组件的值，只要点击当前switch组件就一定会更改当前组件绑定数据的值，且在change事件中修改了当前switch组件绑定的值，但是下次点击依然不会按照修改后的值来决定当前的值。

### What is actually happening?
点击后一定会更改数据的值

### PS
同样是功能差不多的checkbox组件，行为与预期行为一样，表现和行为一致。且可以在change事件中中断绑定值的修改。即如果条件不合适，可在change事件中为checkbox绑定的数据重新赋值，且checkbox的下一次的change事件会根据当前绑定数据的值来做出相应的行为，即如果绑定的值为false，则下一次change事件会修改绑定的数据的值为true；如果绑定的值为true，则下一次change事件会修改绑定的数据的值为false。

### 更新(2017/3/20 20:52)
刚才又确认了一遍，发现在1.1.3版本中，switch组件和checkbox组件的表现不一致；在1.2.4版本中，switch组件和checkbox组件的表现一致，且checkbox组件的表现为1.1.3版本中switch组件的表现。

这里有个困惑的地方是：这两个组件这么设计的原因是什么？为什么点击之后一定要保留点击后处理的结果且在下一次点击中体现，而不是根据绑定数据的值来决定下一次点击做出什么反应？是出于switch和checkbox的语义来考虑的还是没有测试到？求答案。

**Comment by Leopoldthecoder** [comment]
「这个需求来源于：一个switch组件能否更改当前的值，取决于另外一个switch组件的值，如果另外一个switch组件的值为false，则不能更改当前switch组件的值。」看上去更应该使用 `disabled`：https://jsfiddle.net/leopoldthecuber/5vnx100h/4/
