### ISSUE TITLE
upload跨域问题

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#3628]
vue 2.1.8
element-ui  1.2.5

提交图片的时候，跨域情况下，Request Method:OPTIONS，正常不应该是post或get提交么？后台是PHP，已经做了header('Access-Control-Allow-Origin: *')处理，求大神指点，先谢谢了。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by heihei001** [comment]
@Liupeng8 你解决这个问题了吗，我也发现了这种情况，其他的get，post都没有问题，就是上传的时候会出现。
