### ISSUE TITLE
[Bug Report] el-select使用远程搜索时初始值设置的问题

### ISSUE THREAD

**Issue by dqmmpb** [ElemeFE/element#3630]
### Element UI version
1.2.5

### OS/Browsers version
ubuntu/chrome

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/11/](https://jsfiddle.net/pj71jkyw/11/)

### Steps to reproduce
遇到的问题和实例中的略有不同，因为数据是一个{ index: value, name: label}的对象，不是纯字符串，所以select的option中的value和label是不一样的，于是问题就来了， v-model中的值是放index呢还是name呢？

情况1. 如果使用v-model=index，即 value9的初始值使用"1",那么显示的值就是1，而且初始化时的下拉菜单选项是没有的，因为remoteMethod是根据"1"去查询的label，而不是根据"1",对应的label去查询label的列表； 

情况2. 如果使用v-model=name，即value9的初始值使用"Alaska",那么显示的值就是"Alaska",而且下拉菜单的选项是正确的，但这样的话如果这时候键入其他条件，v-model的value9就保存的是index的值了，这又和v-model定义为name相冲突了。

### What is Expected?
这种情况确实比较特殊，请尽快修复

### What is actually happening?
这种情况确实比较特殊，请尽快修复

**Comment by Leopoldthecoder** [comment]
demo 无法执行

**Comment by dqmmpb** [comment]
@Leopoldthecoder  demo 更新了。请看下

**Comment by Leopoldthecoder** [comment]
> 而且初始化时的下拉菜单选项是没有的

demo 中的 `options4` 并没有被初始化，在输入关键字前，它一直是空数组。

**Comment by dqmmpb** [comment]
@Leopoldthecoder  即便对options4进行了初始化。
情况1中，仍然会由于model的改变导致remoteMethod方法被调用1次，而此时的query值为1,同样会导致options4被设置为空数组
https://jsfiddle.net/pj71jkyw/14/

**Comment by yuweiming2016** [comment]
我也遇到同样问题，页面初始化时，会触发一次远程搜索，并且搜索值是select的value，查不出东西来的

**Comment by yuweiming2016** [comment]
建议多一个初始化触发事件，或者让用户选择是否需要初始化

**Comment by githubzhanglei3** [comment]
类型问题，传String 类型就ok

**Comment by s5510886146** [comment]
same issue

**Comment by Leopoldthecoder** [comment]
目前可以正常工作的示例：https://jsfiddle.net/pj71jkyw/416/

在 #6151 优化了逻辑，页面初始化时不会再触发搜索了。

**Comment by SmileYuhao** [comment]
遇到了同样的问题，在您给的链接中，依然发现 初始化的时候调用了两次 `remoteMethod` 方法，以下为console截图 (一次使用value搜索，一次是label)：

<img width="80" alt="screen shot 2017-08-21 at 21 52 49" src="https://user-images.githubusercontent.com/6917105/29535729-437c496c-86bb-11e7-80c0-21fc820aa415.png">

所以想问下，是否有方法在 初始化的时候，不要触发 `remote-method` 呢？

非常感谢 ^^
