### ISSUE TITLE
如何获取cascader组件选中项的label

### ISSUE THREAD

**Issue by nonefirst** [ElemeFE/element#3633]
### Element UI version
1.2.5

### OS/Browsers version
Windows 7/Chrome 56.0.2924.87

### Vue version
2.2.4

### Reproduction Link
[http://jsfiddle.net/api/post/library/pure/](http://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
绑定change事件：@change="addTab，只能获取到选中项的value，无法获取到label

### What is Expected?
能提供一个方法获取label，并在element 官网上给出例子

### What is actually happening?
实际上element的官网上没有相关例子

**Comment by Leopoldthecoder** [comment]
拿到 value 后自己去找到 label。

**Comment by nonefirst** [comment]
好吧~   其实我不喜欢这种方式，循环源数据太坑爹，我本意是想寻找其他方式的解决方案。

**Comment by GreatAuk** [comment]
this.$refs['myCascader'].inputValue
