### ISSUE TITLE
[Feature Request] Table-column如何设置td的背景色？

### ISSUE THREAD

**Issue by 49839013** [ElemeFE/element#3635]
例如
...
 。。el-table-column  prop="test"   label="日期" >   </el-table-column..
...
希望在test等于A的时候td的背景色是黄色
B的时候红色
C的时候蓝色
....有几十种颜色
不知道如何去设置这个，查了很久，发现只有row-class-name去设置一整行，现在需要去设置某一个列
望告知，谢谢。

**Comment by 49839013** [comment]
...el-table-column
           prop="test"
           label="日期" >
         </el-table-column.....

接上面，好像屏蔽掉了代码部分

**Comment by 49839013** [comment]
求指导，坐等。。。

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
