### ISSUE TITLE
[Bug Report] 表格搜索与分页组件

### ISSUE THREAD

**Issue by ALongLi** [ElemeFE/element#3637]
### Element UI version
1.2.2

### OS/Browsers version
win7  chrome55

### Vue version
2.1.10

### Reproduction Link
[无](无)

### Steps to reproduce
进页面ajax获取表格数据，并设置分页

点击搜索重置当前页为第一页，分页重新计算，此时会发两次ajax请求

### What is Expected?
搜索后重置当前页为第一页，只发一次请求

### What is actually happening?
搜索后重置当前页为第一页，会发两次请求

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
