### ISSUE TITLE
DateTimePicker  bug css

### ISSUE THREAD

**Issue by justin107** [ElemeFE/element#3639]
### ElementUI version

官网

### OS/Browsers version

chrome54 win7企业
### Vue version

官网
### Reproduction Link

http://element.eleme.io/#/zh-CN/component/datetime-picker
### Steps to reproduce
![qq 20170321135825](https://cloud.githubusercontent.com/assets/17016557/24134326/83272c94-0e3e-11e7-8ab4-8cad47d8422f.png)

点输入框，滚轮时间，样式错位明显

### What is Expected?

【个人认为】PC端没必要做成如同移动端一样的形式，复杂不说，体验也不一定强，保证手输入时间正确就挺好了，如有可能，最好给方法关闭时间下拉选择这功能更好

大大们辛苦了

**Comment by QingWei-Li** [comment]
![image](https://cloud.githubusercontent.com/assets/7565692/24190947/1db064ba-0f25-11e7-8e17-204e203bf125.png)
没遇到问题

**Comment by justin107** [comment]
静止是好的，但是你滚动下就看的出来了，chrome54  windows环境
