### ISSUE TITLE
[Bug Report] pagination float right style bug in Firefox

### ISSUE THREAD

**Issue by yugasun** [ElemeFE/element#3640]
### Element UI version
1.2.5

### OS/Browsers version
Mac Sierra 10.12.3 / Firefox 51.0.1

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/yugasun/5zo3Lyym/](https://jsfiddle.net/yugasun/5zo3Lyym/)

### Steps to reproduce
使用Firefox浏览器浏览

### What is Expected?
右边的div，设置float:right，后应该是同一行

### What is actually happening?
float:right 的页码div错位到第二行了

**Comment by yugasun** [comment]
目前解决办法是: 将 class `el-pagination`  的 `white-space` 属性设置为 `normal`

**Comment by pengchongfu** [comment]
还可以修改left元素的样式，float: left，但是不怎么好改，需要修改代码

或者将rightWrapper放在前面，将代码template.children.push(rightWrapper);的push改成unshift

**Comment by Leopoldthecoder** [comment]
既然是 firefox 的问题，建议手动覆盖一下样式。

**Comment by yugasun** [comment]
虽然是firefox 的问题，但是觉得element-ui应该考虑进去，不能说 element-ui 团队这个都没在firefox上测试过吧，最起码做到主流浏览器兼容。

**Comment by pengchongfu** [comment]
Fixed in #4756.
