### ISSUE TITLE
[Bug Report] upload组件不兼容IE9。#1132中提到已解决，但是还会出现新的错误。

### ISSUE THREAD

**Issue by Aiyibooo** [ElemeFE/element#3643]
### Element UI version
1.2.5

### OS/Browsers version
WIN7 / IE9

### Vue version
2.1.6

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/upload](http://element.eleme.io/#/zh-CN/component/upload)

### Steps to reproduce
点击上传按钮，选择文件，点击确定，就会出错

### What is Expected?
上传成功

### What is actually happening?
#1132 提到已解决，但是依然会出现下面的错误

_**WIN7 中的 IE9:**_
ReferenceError: “URL”未定义 
SCRIPT5: 拒绝访问。
element.eleme.io, 行1 字符1
![upload-bug](https://cloud.githubusercontent.com/assets/16477682/24137971/2eeca98e-0e51-11e7-8f5b-a4845a1936ae.png)

_**IE11 模拟 IE9:**_
[object Error]{description: "“URL”未定义", message: "“URL”未定义", name: "ReferenceEr...", number: -2146823279}
![upload-bug 2](https://cloud.githubusercontent.com/assets/16477682/24138570/a9be2758-0e53-11e7-8d57-1c1b52e09373.png)

@QingWei-Li @baiyaaaaa

**Comment by weifeiyue** [comment]
同问，是不打算支持IE9吗？

**Comment by yuyuFish** [comment]
同问，是不打算支持IE9吗？

**Comment by HakurouKen** [comment]
IE 9 没有全局的 URL 对象，而且不支持 blob，可以尝试引入 [url-polyfill](https://github.com/github/url-polyfill)，并 hack 掉`URL.createObjectURL`方法

**Comment by Aiyibooo** [comment]
@HakurouKen hack 掉URL.createObjectURL,是直接把createObjectURL这个方法注释掉吗？我试过了，依旧不行，和之前一样的错误。

**Comment by HakurouKen** [comment]
@Aiyibooo  Element 代码内，用到了全局的 URL 对象和 URL.createObjectURL 方法，因为 IE9 不支持 blob，因此这个方法不能（或者说很难）进行 polyfill，需要在引入 polyfill 后，自己 hack 一个方法，比如简单的返回空字符串：
```javascript
URL.createObjectURL = function () {
  return ''
}
URL.revokeObjectURL = function () {}
```

**Comment by suzi404** [comment]
@Aiyibooo 怎么突然没下文了，请问下兼容ie9的问题解决了吗，解决了的话能告诉我是怎么弄的吗？

@HakurouKen 请问下你上面的hack代码要写在哪里呢？

**Comment by czl0705** [comment]
@Aiyibooo @HakurouKen @suzi404 
出现同样问题，请问是怎么解决的！！

**Comment by weifeiyue** [comment]
我想纯前端技术是没办法解决这个问题，需要flash才可以，就看官方是否愿意去兼容ie9了

**Comment by HakurouKen** [comment]
过了 URL Object 这一关，后续还有其它兼容问题，兼容处理还比较复杂，单纯外部 hack 并不能完全解决。目前看来，如果一定要兼容 IE9，最好自己写 upload 控件

**Comment by Aiyibooo** [comment]
@suzi404 @czl0705 
还没有解决...

**Comment by yu530feng** [comment]
最新版ie9上传还是没有解决，难道要等我出手么？

**Comment by fuerpeng** [comment]
保持观望

**Comment by fuerpeng** [comment]
Keep wait and see

**Comment by Plortinus** [comment]
要兼容IE9还是用百度的webuploader吧，IE9是通过flash实现的，然而flash要被废掉了

**Comment by csvwolf** [comment]
We wont support IE9 in later version.(And not support in current version)
