### ISSUE TITLE
Dialog cannot work, it was blocked by "div.v-modal".

### ISSUE THREAD

**Issue by virus-warnning** [ElemeFE/element#3646]
The z-index of div.v-modal > z-index of dialog, but dialog was still blocked due to relative z-index.
This dialog works on 1.1.6.
http://stackoverflow.com/questions/7490146/z-index-relative-or-absolute

### ElementUI version
1.2.5

### OS/Browsers version
macOS/Chrome 57.0.2987.98 (64-bit)

### Vue version
2.1.0

**Comment by virus-warnning** [comment]
![2017-03-21 4 20 58](https://cloud.githubusercontent.com/assets/5044734/24139239/4fd6c8be-0e56-11e7-817f-cd5c8f10c5f4.png)

**Comment by Leopoldthecoder** [comment]
Please post a demo
