### ISSUE TITLE
关于照片墙上传的一些建议

### ISSUE THREAD

**Issue by Whoisfreedom** [ElemeFE/element#3648]
1.用照片墙上传照片before-upload上传失败后会留下一个空白的框，这个框既不能删除也无法修改。
2.file-list也会把没有上传成功的数据保存下来。
3.推荐最好有个参数设置照片墙可放置最多照片张数。

**Comment by lybb123456** [comment]
恩，现在也遇到的这个问题，在限制数量的时候，会留下一个空白的框，影响用户体验
