### ISSUE TITLE
dialog中同时存在<el-form :inline="true"/>(在inline模式下),<el-table/>等组件共存时，会出现放大式抖动问题及严重的样式问题，仅在chrome高版本浏览器中存在

### ISSUE THREAD

**Issue by penggle** [ElemeFE/element#3650]
当dialog组件中含有：查询表单<el-form :inline="true"/>(在inline模式下)，表格组件<el-table/>，分页组件<el-pagination/>的时候，在chrome(v56)浏览器下出现放大式抖动问题，而且对话框中大部分元素(input, button)会出现样式上怪异问题(呈现糊状box-shadow)，以上布局不在dialog中则没有问题！

**Comment by penggle** [comment]
![Uploading dialog.jpg…]()

**Comment by Leopoldthecoder** [comment]
请给 demo

**Comment by niupeinan** [comment]
这个如何解决呀？我也遇到了同样的问题。
