### ISSUE TITLE
[Tree]filter-node-method,初始化后调用过滤函数

### ISSUE THREAD

**Issue by tomieric** [ElemeFE/element#3651]
### Reproduction Link

[http://jsfiddle.net/om0tyycy/](http://jsfiddle.net/om0tyycy/)

### What is  #Expected?

关于 `Tree` 过滤函数的定义，如果有默认的过滤文字，能否在Tree实例化后触发一次过滤函数 `filter`，抑或在`tree.vue`中增加`filter-text`字段，监听其变化可以触发`filter`函数

现在文件暂时使用 `setTimeout` 解决，并不严谨

```
 created () {
    	// 不是很严谨
    	setTimeout(() => {
      	this.$refs.tree2.filter(this.filterText);
      }, 300)
    }
```

**Comment by Leopoldthecoder** [comment]
在 mounted 钩子里执行：http://jsfiddle.net/om0tyycy/1/

**Comment by tomieric** [comment]
额... 可能是我描述的不够清楚，`el-tree` 封装在一个组件内，其中tree的data是从外部传入

请看实例 [http://jsfiddle.net/om0tyycy/2/](http://jsfiddle.net/om0tyycy/2/)

**Comment by Leopoldthecoder** [comment]
自己 nextTick 一下吧：http://jsfiddle.net/leopoldthecuber/om0tyycy/3/

**Comment by tomieric** [comment]
好吧，是我自己犯低级错误了，之前也像你这样写过

```
watch : {
  data: {
     handler(v) {
        this.filterText && this.$refs.tree2.filter(this.filterText);
    },
   immediate: true
  }
}
```

是自己疏忽了 `this.filterText` 是 `0`的情况

**Comment by uneverno** [comment]
刚用Element ui ,请问执行filterText()的时候如何让子节点也显示出来？

**Comment by wq0923** [comment]
> 刚用Element ui ,请问执行filterText()的时候如何让子节点也显示出来？

同问

**Comment by xwj0813** [comment]
刚用Element ui ,请问执行filterText()的时候如何让子节点也显示出来？
同问

**Comment by tomieric** [comment]
> 刚用Element ui ,请问执行filterText()的时候如何让子节点也显示出来？
> 同问

设置 `:default-expand-all="true"` 默认展开吧

**Comment by aisuandebowen** [comment]
> 在 mounted 钩子里执行：http://jsfiddle.net/om0tyycy/1/

你好，链接失效了，可以更新一下demo吗？

**Comment by tomieric** [comment]
> > 在 mounted 钩子里执行：http://jsfiddle.net/om0tyycy/1/
> 
> 你好，链接失效了，可以更新一下demo吗？

[https://codepen.io/tommyshao/pen/GRPvvmd](https://codepen.io/tommyshao/pen/GRPvvmd)
