### ISSUE TITLE
Popover 弹出框在v-for循环中生成多个弹出框时会报错！！！

### ISSUE THREAD

**Issue by rongjuan** [ElemeFE/element#3653]
`
<div class="msg-add" v-for="(item, index) in addresses">
  
        <el-popover ref="popover5" placement="top" width="220" v-model="visible2">
          弹出内容！！！
        </el-popover>
        <el-button type="text" v-popover:popover5 icon="edit" class="edit-btn"></el-button>
</div>

`

**Comment by renxia** [comment]
基本的逻辑理解都有问题啊...
这样来写姿势才对：

```js
<div class="msg-add" v-for="(item, index) in addresses" :key="item">
    <el-popover placement="top" width="220">
        弹出内容！！！
        <el-button type="text" slot="reference" icon="edit" class="edit-btn"></el-button>
    </el-popover>
</div>
```
http://jsfiddle.net/5vjb037h/
