### ISSUE TITLE
DatePicker 

### ISSUE THREAD

**Issue by fengtaijun0507** [ElemeFE/element#3655]
日期选择控件，左侧选择控件左箭头，无法触发事件，经检测
.el-date-range-picker__content.is-right .el-date-range-picker__header div {
    margin-left: 50px;
    margin-right: 50px;
}
而左侧没有
.el-date-range-picker__header div {
    font-size: 14px;
    margin-right: 50px;
}，
是否能及时修改，谢谢

**Comment by Leopoldthecoder** [comment]
问题描述没太看懂，最好附上 demo 详细说明一下。

**Comment by fengtaijun0507** [comment]
<img width="420" alt="wx20170322-002015 2x" src="https://cloud.githubusercontent.com/assets/14059031/24157796/632888aa-0e95-11e7-8860-0c7910a21d5d.png">

图上左侧的箭头点击无法触发事件，通过查看样式，发现右侧箭头按钮处的div的样式为
.el-date-range-picker__content.is-right .el-date-range-picker__header div {
margin-left: 50px;
margin-right: 50px;
}
左侧缺少margin-left: 50px;，本地手动添加margin-left：50px，发现左侧箭头好使了，具体为什么会这样不明确，只是知道这样修改会解决问题，由于使用该组件应用于项目，希望你早点添加这个样式，好在远程更新包，谢谢。。。
