### ISSUE TITLE
[Bug Report] Date Range control doesn't fit on xs (mobile phone) screen

### ISSUE THREAD

**Issue by salgua** [ElemeFE/element#3656]
### Element UI version
1.2.5

### OS/Browsers version
Safari Mobile on IOS10

### Vue version
2.2.4

### Reproduction Link
[http://element.eleme.io/#/en-US/component/date-picker#date-range](http://element.eleme.io/#/en-US/component/date-picker#date-range)

### Steps to reproduce
Go to http://element.eleme.io/#/en-US/component/date-picker#date-range from mobile safari on iOS and use the data-range picker

### What is Expected?
I expect to use the control from mobile

### What is actually happening?
I cannot use the control because it's too big

**Comment by Leopoldthecoder** [comment]
Element does not support mobile devices.

**Comment by gustawdaniel** [comment]
And anyone do not want to fit it? I can't believe that this issue was ignored.
