### ISSUE TITLE
[Bug] Slider is sluggish and jumping when dragging

### ISSUE THREAD

**Issue by gabrielboliveira** [ElemeFE/element#3661]
### ElementUI version
1.2.5

### OS/Browsers version
macOS/Chrome 56 and Safari 10.0.3

### Vue version
2.2.4

### Reproduction Link
http://jsfiddle.net/yko6akym/

### Steps to reproduce
Very big slider (10k px) with very small steps (0.01) and a big max (600)

### What is Expected?
Slider animation should be smooth and not jump around.

### What is actually happening?
When you click it to drag, it jumps a little bit back, it's inconsistent how much it jumps. Example: it's on value 9, when you click and drag it jumps back to ~6 and the mouse is far from the slider button
![mouse-jump](https://cloud.githubusercontent.com/assets/11093090/24158788/0c7d4274-0e3c-11e7-9704-b60b84a1395f.png)

Also, the animation is very sluggish, perhaps using [translate](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate) instead of `width` and `left` should improve performance, because it uses GPU. For this problem, if you agree, I can create a PR to fix the performance.

**Comment by Leopoldthecoder** [comment]
Thanks for fixing this.
