### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by fengtaijun0507** [ElemeFE/element#3662]
![Uploading WX20170322-004335@2x.png…]()
![Uploading WX20170322-010011@2x.png…]()

图上左侧的箭头点击无法触发事件，通过查看样式，发现右侧箭头按钮处的div的样式为
.el-date-range-picker__content.is-right .el-date-range-picker__header div {
margin-left: 50px;
margin-right: 50px;
}
而左侧缺少margin-left: 50px;，本地手动添加margin-left：50px，发现左侧箭头好使了，只是知道这样修改会解决问题，由于使用该组件应用于项目，希望你早点添加这个样式，好在远程更新包，谢谢。。。

**Comment by Leopoldthecoder** [comment]
无法重现问题，请提供 demo

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
