### ISSUE TITLE
[Feature Request] 怎么不起个名字叫 html 之类的。

### ISSUE THREAD

**Issue by name327** [ElemeFE/element#3673]
这个名字重复率有多高，百度搜下就知道了。 起这个名字， 怎么想的哦。

**Comment by QingWei-Li** [comment]
@name327 
您拿好 https://npmjs.com/html-ui
```shell
npm i html-ui
```

![image](https://cloud.githubusercontent.com/assets/7565692/24182171/da124e64-0efa-11e7-8d37-8ee1e66a8c51.png)
