### ISSUE TITLE
button按钮loading建议

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#3674]
vue 2.1.8

element-ui  1.2.5

建议新增按钮在loading状态下，可以指定对应loading文字，这个很实用。

**Comment by QingWei-Li** [comment]
自己照这个写一下
http://element.eleme.io/#/zh-CN/component/button#jia-zai-zhong

Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
