### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by cddsgtc** [ElemeFE/element#3676]
![qq 20170322134514](https://cloud.githubusercontent.com/assets/16315661/24183869/d677d3e0-0f05-11e7-98d3-9df417a96646.jpg)
在该地址http://element.eleme.io/#/zh-CN/component/upload
这个自定义方法应该拼错了吧
中有关钩子函数on-success在文中使用有拼写错误

**Comment by Leopoldthecoder** [comment]
dev 分支已修复。
