### ISSUE TITLE
[Bug Report]日期选择空间删除日期文本后日期并未被清除

### ISSUE THREAD

**Issue by magygt** [ElemeFE/element#3677]
### ElementUI version
1.2.0 

### OS/Browsers version
macOS/Chrome 53

### Vue version
2.2.0

### Reproduction Link
http://element.eleme.io/#/zh-CN/component/date-picker

### Steps to reproduce
选择范围内日期，选择完成后，清空输入框生成的字符

### What is Expected?
选择的日期被清除

### What is actually happening?
之前选择的日期并未被清除

**Comment by Caijt** [comment]
我也是这个问题，手动把日期控件值删除后，不为空的检测失效了，连elementui官网的例子也是如此
http://element.eleme.io/#/zh-CN/component/form
到那个表单验证那里，先选择一个日期，然后手动删除掉它（不是按清空按钮），然后点立即创建，并不会提示为空提醒
