### ISSUE TITLE
Button的Loading状态可以支持与事件绑定吗？

### ISSUE THREAD

**Issue by NadokaCiel** [ElemeFE/element#3685]
最近在项目中遇到了很多异步操作的按钮，需要在操作的途中显示载入样式
但是组件的事件是通过广播的形式触发的，button并不能获取事件执行完毕的结果。
因此页面不同按钮的loading状态需要写很多属性来绑定，在点击事件里来更改

为了解决这个问题我对el-button做了一个简单的封装：
[http://jsfiddle.net/rzozmzn8/3/](http://jsfiddle.net/rzozmzn8/3/)

让button在点击事件完成前后自动进行loading状态的转换
实现的比较粗糙，麻烦参考一下可行性……

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
