### ISSUE TITLE
按需引入时的合并打包问题

### ISSUE THREAD

**Issue by bing1021** [ElemeFE/element#3688]
我使用vue-cli创建的项目，使用了element-ui

在每个组件中按需引入element-ui，在打包时出现重复问题。

比如我有两个组件，均使用了BUTTON,这两个组件都会打包BUTTON的代码。

我想到的办法就是在入口引入所有需要的组件。但是这样在每个组件的编写就很麻烦了。

我什么好的解决方案吗？

**Comment by QingWei-Li** [comment]
webpack 会自动处理的

Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
