### ISSUE TITLE
下拉框和输入框在small大小下，显示不一致！

### ISSUE THREAD

**Issue by git-lt** [ElemeFE/element#369]
![image](https://cloud.githubusercontent.com/assets/8443758/19332423/63549e76-911e-11e6-9c78-c35936697d0b.png)

**Comment by Leopoldthecoder** [comment]
Select 组件没有对外提供 `size` 属性。目前它的 `size=small` 仅用于 Element 内部的 Pagination 组件。如果需要的话，你可以通过覆盖 CSS 样式来控制它的大小。
