### ISSUE TITLE
[Bug Report] upload组件在beforeUpload抛出异常

### ISSUE THREAD

**Issue by radicalviva** [ElemeFE/element#3698]
### Element UI version
1.2.4

### OS/Browsers version
chrome 57.0.2987.98 (64-bit)

### Vue version
2.1.6

### Reproduction Link
[公司后台产品](公司后台产品)

### Steps to reproduce
昨天正常运行，今天去测试，就抛出异常了。
```javascript
    beforeFileUpload: function (file) {
      if (['image/jpeg', 'image/jpg', 'image/png'].indexOf(file.type) == -1) {
        this.showError('请上传jpg, png格式的图片')
        return false
      }
      if (file.size / 1024 / 1024 > 5) {
        this.showError('上传图片大小不能超过5MB')
        return false
      }
      var xmlhttp = new XMLHttpRequest()
      var serverUrl = '/yan/user/user-list/getJsSign'
      xmlhttp.open( "GET", serverUrl, false );
      xmlhttp.send( null );
      var res = eval ("("   xmlhttp.responseText   ")")
      var dir_name = res.dir   this.randomString(10)   this.getSuffix(file.name)
      this.file_url = res.host
      this.file_data = {
        OSSAccessKeyId: res.accessid,
        policy: res.policy,
        signature: res.signature,
        key: dir_name
      }
      file.src_url = '//pic.tugou.com/'   dir_name
      return Promise.resolve(true)
    },
```
在此处抛出错误。
Uncaught SyntaxError: Unexpected token < at Vue$3.beforeFileUpload
at VueComponent.boundFn
at VueComponent.upload

### What is Expected?
希望可以看看是不是 框架更新导致的原因

### What is actually happening?
...

**Comment by kfeng0806** [comment]
你需要babel

**Comment by radicalviva** [comment]
@kfeng0806  我这和babel应该没关系啊，我是直接通过CDN引入 `element-ui` 的 `css` 和 `js`

**Comment by QingWei-Li** [comment]
请给出可复现问题的 demo 不然你让我们怎么解决

**Comment by radicalviva** [comment]
```
          <el-upload
            class="avatar"
            :action="file_url"
            :data="file_data"
            accept="image/jpeg, image/jpg, image/png"
            list-type="picture-card"
            :before-upload="beforeFileUpload"
            :on-preview="handleFilePreview"
            :on-success="handleAvatarSuccess"
            :on-remove="handleAvatarRemove"
            :on-error="handleError">
            <i class="el-icon-plus uploader-icon"></i>
          </el-upload>
```
```
    beforeFileUpload: function (file) {
      if (['image/jpeg', 'image/jpg', 'image/png'].indexOf(file.type) == -1) {
        this.showError('请上传jpg, png格式的图片')
        return false
      }
      if (file.size / 1024 / 1024 > 5) {
        this.showError('上传图片大小不能超过5MB')
        return false
      }
      var xmlhttp = new XMLHttpRequest()
      var serverUrl = '/yan/user/user-list/getJsSign'
      xmlhttp.open( "GET", serverUrl, false );
      xmlhttp.send( null );
      var res = eval ("(" + xmlhttp.responseText + ")")
      var dir_name = res.dir + this.randomString(10) + this.getSuffix(file.name)
      this.file_url = res.host
      this.file_data = {
        OSSAccessKeyId: res.accessid,
        policy: res.policy,
        signature: res.signature,
        key: dir_name
      }
      file.src_url = '//pic.tugou.com/' + dir_name
      return Promise.resolve(true)
    }

    extractKeyList: function (old_arr) {
      var res_arr = []
      old_arr.forEach(function (elem) {
        res_arr.push(elem.raw.src_url)
      })
      return res_arr.join(',')
    },
    handleAvatarSuccess: function (res, file, file_list) {
      this.insp.avatar = this.extractKeyList(file_list)
      $('.avatar>.el-upload--picture-card').fadeOut(200)
    },
    handleAvatarRemove: function (file, file_list) {
      this.insp.avatar = this.extractKeyList(file_list)
      $('.avatar>.el-upload--picture-card').fadeIn(200)
    },
```

**Comment by liuzhibin123** [comment]
<el-upload class="upload-demo"
			v-show="true"
			multiple 
			:show-file-list="true" 
			:action="action" 
			:with-credentials="true" 
			:data="uploadAppend" 
			name="multiFile" 
			:on-remove="handleRemove"
			:before-upload="beforeUpload" 
			:on-progress="progressUpload" 
			:on-success="successUpload" 
			:on-error="errorUpload" 
			ref="upload">
			<el-button icon="upload" type="primary" style="background-color: #fb545b;border:none;">上传</el-button>
		</el-upload>
beforeUpload(file) {
					if(file.size > 50 * 1024 * 1024) {
						this.$message.error('上传文件大小不能超过 50MB!');
						return false
					}
					if(file.name.length > 50) {
						this.$message.error('上传文件名长度不能超过 50');
						return false
					}
					var that = this,
						reader = new FileReader();
					reader.readAsArrayBuffer(file);
					var breadcrumb = that.breadcrumb,id,catalog;
					if(breadcrumb[breadcrumb.length-1].id == 'ss'){
						id = breadcrumb[breadcrumb.length-2].id;
						catalog = breadcrumb[breadcrumb.length-2].name;
					}else{
						id = breadcrumb[breadcrumb.length-1].id;
						catalog = breadcrumb[breadcrumb.length-1].name;
					}
					
					var promise = new Promise(function(resolve, reject) {
						reader.onload = function(e) {
							var bolb = e.target.result;
							var filemd5 = md5(bolb);
							var opt = {
								upload_chunksize: 8388608,
								upload_uuid: -1,
								upload_filemd5: filemd5,
								upload_filename: file.name,
								upload_filesize: file.size,
								_: file.lastModified
							}
							that.$httpExt().get("uploader/init/"+id, opt)
								.then((response) => {
									if(response.hasOwnProperty("msg")){
											reject(file.name)
										that.$message.info({
											title: '异常',
											message: response.msg
										});
									}
									if(response.code==200) {
										that.$store.commit('GET_UPLOADER_STATE', true);
										that.uploadAppend.chunkMD5 = filemd5
										that.uploadAppend.name = file.name
										that.uploadAppend.type = file.type
										that.uploadAppend.lastModifiedDate = file.lastModifiedDate
										that.uploadAppend.size = file.size
										that.uploadAppend.uploadFileId = response.info.id
										that.uploadAppend.uuid = response.info.uuid
										that.uploadAppend.bucketName = response.info.bucketName
										var singleFile = {
											name: file.name,
											size: file.size,
											catalog: catalog,
											state: "准备上传中",
											status: false,
											file: file,
											append: that.uploadAppend
										}
										that.fileDate.push(singleFile)
										
										resolve(file.name)
									}
								}, (response) => {
									reject(response)
									that.$notify.error({
										title: '异常',
										message: response.msg
									});
								})
						}
					})
					return promise
				}

**Comment by liuzhibin123** [comment]
我这个首次上传都会成功 但是第二次上传要是后台验证不通过reject(file.name) 接下来的上传就会有问题
```
<el-upload class="upload-demo"
			v-show="true"
			multiple 
			:show-file-list="true" 
			:action="action" 
			:with-credentials="true" 
			:data="uploadAppend" 
			name="multiFile" 
			:on-remove="handleRemove"
			:before-upload="beforeUpload" 
			:on-progress="progressUpload" 
			:on-success="successUpload" 
			:on-error="errorUpload" 
			ref="upload">
			<el-button icon="upload" type="primary" style="background-color: #fb545b;border:none;">上传</el-button>
		</el-upload>


beforeUpload(file) {
	if(file.size > 50 * 1024 * 1024) {
		this.$message.error('上传文件大小不能超过 50MB!');
		return false
	}
	if(file.name.length > 50) {
		this.$message.error('上传文件名长度不能超过 50');
		return false
	}
	var that = this,
		reader = new FileReader();
	reader.readAsArrayBuffer(file);
	var breadcrumb = that.breadcrumb,id,catalog;
	if(breadcrumb[breadcrumb.length-1].id == 'ss'){
		id = breadcrumb[breadcrumb.length-2].id;
		catalog = breadcrumb[breadcrumb.length-2].name;
	}else{
		id = breadcrumb[breadcrumb.length-1].id;
		catalog = breadcrumb[breadcrumb.length-1].name;
	}
	
	var promise = new Promise(function(resolve, reject) {
		reader.onload = function(e) {
			var bolb = e.target.result;
			var filemd5 = md5(bolb);
			var opt = {
				upload_chunksize: 8388608,
				upload_uuid: -1,
				upload_filemd5: filemd5,
				upload_filename: file.name,
				upload_filesize: file.size,
				_: file.lastModified
			}
			that.$httpExt().get("uploader/init/"+id, opt)
				.then((response) => {
					if(response.hasOwnProperty("msg")){
							reject(file.name)
						that.$message.info({
							title: '异常',
							message: response.msg
						});
						
					}
					if(response.code==200) {
						that.$store.commit('GET_UPLOADER_STATE', true);
						that.uploadAppend.chunkMD5 = filemd5
						that.uploadAppend.name = file.name
						that.uploadAppend.type = file.type
						that.uploadAppend.lastModifiedDate = file.lastModifiedDate
						that.uploadAppend.size = file.size
						that.uploadAppend.uploadFileId = response.info.id
						that.uploadAppend.uuid = response.info.uuid
						that.uploadAppend.bucketName = response.info.bucketName
						var singleFile = {
							name: file.name,
							size: file.size,
							catalog: catalog,
							state: "准备上传中",
							status: false,
							file: file,
							append: that.uploadAppend
						}
						that.fileDate.push(singleFile)
						
						resolve(file.name)
					}
				}, (response) => {
					reject(response)
					that.$notify.error({
						title: '异常',
						message: response.msg
					});
				})
		}
	})
	

	return promise

},
```

**Comment by radicalviva** [comment]
@liuzhibin123  你修改成 同步发起ajax获取签名 试试。  我上面的代码问题是 没有声明这是ajax请求。

**Comment by liuzhibin123** [comment]
@radicalviva 没用 应该我那个获取文件的MD5是异步的。我刚把vuesource换成原生的AJAX（同步）。
当有后台返回校验不成功时，element就会报错。
