### ISSUE TITLE
ie11 行内表单

### ISSUE THREAD

**Issue by bberrydry** [ElemeFE/element#370]
官网demo  win10 ie11

[http://element.eleme.io/#/component/form](http://element.eleme.io/#/component/form)

![image](https://cloud.githubusercontent.com/assets/3782277/19334107/42d86fe8-912c-11e6-95bb-6b134ac5ad89.png)

**Comment by baiyaaaaa** [comment]
通过edge用户代理切换到ie10没有重现这个问题

**Comment by ritksm** [comment]
可以重现

![image](https://cloud.githubusercontent.com/assets/111809/19335724/f8ec4e16-9137-11e6-9f92-02d6c939ac75.png)

**Comment by bberrydry** [comment]
perfect !  3Q ~
