### ISSUE TITLE
[Feature Request] Suport for other icon fonts

### ISSUE THREAD

**Issue by ivoribeiro** [ElemeFE/element#3702]
I would love to use your input icon feature with other icon fonts.
Thanks

**Comment by QingWei-Li** [comment]
[FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md)

> How do I use third-party icon font library with Element?
>
> You just need to modify the class name prefix of the third-party library (see their docs for how to do it), and write some CSS, then you can use them just like you use Element built-in icons. For example, change the prefix to el-icon-my, and then add the following to its CSS:
>
> ```css
> [class^="el-icon-my"], [class*=" el-icon-my"] {
>   font-family:"your-font-family" !important;
>
>  /* The following is based on original CSS rules of third-party library */
>  font-size: inherit;
>  font-style:normal;
>  -webkit-font-smoothing: antialiased;
>  -moz-osx-font-smoothing: grayscale;
>}
>```
