### ISSUE TITLE
[Bug Report] 日期选择器修改年时，月份或者日期被默认选中了

### ISSUE THREAD

**Issue by haoshuaiya** [ElemeFE/element#3705]
### Element UI version
1.2.5

### OS/Browsers version
windows10 / chrome 56

### Vue version
2.2.4

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/date-picker](http://element.eleme.io/#/zh-CN/component/date-picker)

### Steps to reproduce
点击日期选择框，修改年份，存在默认选中的日期或者月份

### What is Expected?
修改年份时，没有默认月份或者日期

### What is actually happening?
会选中默认日期或者月份

**Comment by Leopoldthecoder** [comment]
这不是 bug。有默认会有什么问题？
