### ISSUE TITLE
[Bug Report] table fix列显示异常

### ISSUE THREAD

**Issue by ma-xiao-guang-64** [ElemeFE/element#3708]
### Element UI version
1.2.5

### OS/Browsers version
chrome firefox edge

### Vue version
2.2.4

### Reproduction Link
[ http://jsfiddle.net/LdrL8La2/4/ ]( http://jsfiddle.net/LdrL8La2/4/ )

### Steps to reproduce
这个BUG会出现在设置的min-width之和接近需要渲染的table的宽度时
所以需要作者改一下里面min-width

### What is Expected?
fix列显示正常

### What is actually happening?
fix列显示不正常

![2](https://cloud.githubusercontent.com/assets/6637227/24231833/e0a51c94-0fc1-11e7-98f7-671e2aa7b47f.png)

**Comment by xiaoguangma** [comment]
@Leopoldthecoder

**Comment by ruixiu** [comment]
还是计算高度的时候出现了问题，我的一个例子，正常情况下el-table__fixed对应div的高度应该是80px,在临界的时候算出来的是65px，所以出现了垂直滚动条，望作者尽快修复。

**Comment by lilong7676** [comment]
![image](https://user-images.githubusercontent.com/21004230/29018086-4c40bf04-7b8c-11e7-8058-0f1bceac6e5f.png)
My situation is like you..

**Comment by reclay** [comment]
Same problem, and I made a 'pr'. [#6926](https://github.com/ElemeFE/element/pull/6926)

**Comment by liril-net** [comment]
Fixed in [Carbon](https://github.com/ElemeFE/element/releases/tag/v2.0.0)

**Comment by liujunning** [comment]
这个问题各位解决了吗
