### ISSUE TITLE
[Bug Report] Bug：官网table组件的滚动条（横向和纵向）在mac的Safari浏览器中不能滚动

### ISSUE THREAD

**Issue by AnyGong** [ElemeFE/element#3710]
### Element UI version
1.2.5

### OS/Browsers version
系统：macOS Sireea 10.12.3   Safar浏览器：10.0.3

### Vue version
2.2.1

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/table 官方的table组件只要是带有滚动条，全部失效，无法拖拽。chrome可以](http://element.eleme.io/#/zh-CN/component/table 官方的table组件只要是带有滚动条，全部失效，无法拖拽。chrome可以)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/table 用mac的Safari浏览器打开对带有table的滚动条进行拖拽，发现无法移动

### What is Expected?
正常滚动

### What is actually happening?
无反应

**Comment by jikkai** [comment]
同系统同浏览器没有复现出来……

**Comment by eeeeeLin** [comment]
修改 .el-table__body-wrapper 的 z-index 可以修复，但会有别的影响吗？

**Comment by subo-romens** [comment]
请问下 怎么解决，现在Safari  无法滚动 table  好急呀

**Comment by Leopoldthecoder** [comment]
@subo-romens 先参照你楼上的方法覆盖一下 CSS 试试。

**Comment by subo-romens** [comment]
.el-table__body-wrapper{
  z-index:2
}    是这么设置吗   没效果呀  能给个例子吗  https://jsfiddle.net/yp3kxbkk/2/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/yp3kxbkk/5/

**Comment by subo-romens** [comment]
非常感谢

**Comment by Leopoldthecoder** [comment]
楼上各位能否麻烦再看下这个问题还存在吗？我目前的环境是：
> macOS 10.12.5
Safari 10.1.1

已经没有问题了。

**Comment by AnyGong** [comment]
最新版本，已不存在该问题 @Leopoldthecoder  感谢。不好意思，太久没回复。

**Comment by conantime** [comment]
我这里出现了类似的问题，内部的el-table不会显示不全，而是多了一个overflow 向右的滑动。怎么让其大小和chrome中同步
