### ISSUE TITLE
 [Bug Report] DatePicker 日期选择器”是否显示清除按钮“参数无效

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#3711]
Element UI version：1.2.5
Vue version：2.2.4

日期选择器在下面地址中提到有一个参数：clearable，该参数表示“是否显示清除按钮”，默认为true，即使设置为false，仍然显示清除按钮。该参数设置无效。
http://element.eleme.io/#/zh-CN/component/date-picker

**Comment by jikkai** [comment]
`:clearable="false"`

**Comment by chenshaoli** [comment]
:clearable="false"在chrome44上是没有效果的，高版本试了下是可行的
