### ISSUE TITLE
[Bug Report] 日期选择器参数无效

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#3713]
### Element UI version
1.2.5

### OS/Browsers version
Windows10 / Firefox

### Vue version
2.2.4

### Reproduction Link
[element.eleme.io/#/zh-CN/component/date-picker](element.eleme.io/#/zh-CN/component/date-picker)

### Steps to reproduce
设置日期选择器的参数：clearable、editable为false，这两个参数均无效。类似下面的写法：
<el-date-picker v-if='scope.row.meta.editState' v-model="scope.row.meta.temp.date" type="date" editable=false clearable=false placeholder="选择日期" :picker-options="dateOption"></el-date-picker>

### What is Expected?
1、设置clearable为false应该在选择日期后，无法清除内容。
2、设置editable为false应该禁止键盘输入

### What is actually happening?
1、设置clearable为false仍然可以清除已选定的日期。
2、设置editable为false仍然可以键盘输入。

**Comment by chenli1989** [comment]
参数无效问题解决了吗？
Element UI -V  1.2.8  这问题还是存在
