### ISSUE TITLE
[Bug Report] 在表单中提交el-select元素,后台取到的值是option的label值而不是value值

### ISSUE THREAD

**Issue by LionCoder4ever** [ElemeFE/element#3729]
### Element UI version
1.2.5

### OS/Browsers version
chrome 57.0.2987.98

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/cocoding/b3f4vhfd/](https://jsfiddle.net/cocoding/b3f4vhfd/)

### Steps to reproduce
F12打开调试器，选中双皮奶选项，点击提交按钮

### What is Expected?
提交表单时的 Form Data 为 food:选项2   即option标签的value值

### What is actually happening?
Form Data 为 food:双皮奶 是option标签的label值

**Comment by jikkai** [comment]
这个 input 是用于展示 label 的，所以用原生表单提交时会获取到里面的 label。

个人真心不推荐用这种原生提交表单的方式，建议改成异步提交的方式，或者……创建一个隐藏的 input，name赋值为 food，然后把选中的值绑到这个 input 里去，再用原生提交的方式就能获得 value 了。

**Comment by Lawrence51** [comment]
这个问题现在解决了吗？我也是遇到了这个问题
