### ISSUE TITLE
[Feature Request] el-input复合型输入框能否增加指定默认选中项

### ISSUE THREAD

**Issue by mohong** [ElemeFE/element#3732]
### Existing Component
是

### Component Name
el-input复合型输入框

### Description
el-input复合型输入框的第三个demo中有建议选择项，能否指定一个默认选项，我通过给el-option指定“selected=selected”,并没有起作用。

组件地址：
http://element.eleme.io/#/zh-CN/component/input#fu-he-xing-shu-ru-kuang

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/hatvf5oq/1/

**Comment by mohong** [comment]
@Leopoldthecoder 非常感谢！！！
