### ISSUE TITLE
Uncaught TypeError: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by lihqi** [ElemeFE/element#3733]
表单提交验证需要另外引入 validate 模块么

**Comment by antoniojps** [comment]
I am having this issue, probably my fault, eitherway, I was searching looking for some answers, can anyone translate the solution if there was one? Thank you in advance.

**Comment by Seayon** [comment]
element-ui don't need import validate again, in my project, I just forget to add  `ref="ruleForm"` to my el-form, not it works good.

**Comment by Seayon** [comment]
element-ui doesn't need import validate module again, in my project, I just forget to add ref="ruleForm" to my el-form, not it works good.

**Comment by Seayon** [comment]
element-ui doesn't need import validate module again, in my project, I just forget to add ref="ruleForm" to my el-form, now it works good.
