### ISSUE TITLE
[Bug Report] 当button数量超过一行时，排版不正常

### ISSUE THREAD

**Issue by istobran** [ElemeFE/element#3739]
### Element UI version
1.2.5

### OS/Browsers version
Chrome 56

### Vue version
2.2.5

### Reproduction Link
[http://jsfiddle.net/BangZ/tmkbvr63/2/](http://jsfiddle.net/BangZ/tmkbvr63/2/)

### Steps to reproduce
添加若干个el-button直至超过一行

### What is Expected?
希望排版能够对齐，上下两行之间的按钮有一定间距

### What is actually happening?
从第二行开始最左边没对齐，上下两行之间没有间距

**Comment by Leopoldthecoder** [comment]
参照 #3779，请自行覆盖 CSS。
