### ISSUE TITLE
纵向steps最后一个step溢出

### ISSUE THREAD

**Issue by acelan86** [ElemeFE/element#374]
### ElementUI version
1.0.0-rc.5

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.1

### What is actually happening?
![demo](http://d1.sina.com.cn/d1images/1146B3E6-9FB9-4B37-8C72-50C0F883D720.png)

最后一个setp溢出，因为在step.vue中初始化时候设置了width：0， height：0，只给前面n-1个步骤设置height，导致最后一个step还是初始化的值，初始化值应该设置成'auto'
```javascript
  data() {
    return {
      index: -1,
      style: { width: 'auto', height: 'auto' }, // fixed bug
      lineStyle: { width: 0, height: 0 },
      mainOffset: 0,
      currentStatus: this.status
    };
  }
// ....
// 这里产生了bug
mounted() {
    const parent = this.$parent;
    const space = parent.space
      ? parent.space + 'px'
      : 100 / parent.steps.length + '%';

    if (parent.direction === 'horizontal') {
      this.style = { width: space }; // 水平方向其实也不合理，height：0
      // this.mainOffset = -this.$refs.title.getBoundingClientRect().width / 2 + 16 + 'px';
    } else {
      if (parent.steps[parent.steps.length - 1] !== this) {
        this.style = { height: space }; // 这里
      }
    }

    const unwatch = this.$watch('index', val => {
      this.$watch('$parent.active', this.updateStatus, { immediate: true });
      unwatch();
    });
  }
```

**Comment by QingWei-Li** [comment]
已经修复了，不知道为啥现在设置 `{ width: 0, height: 0 }` 会被正确识别成 0px 了，之前不是这样的。

**Comment by QingWei-Li** [comment]
好像并不需要设置成 `this.style = { width: space, height: 0 };` 

fixed in https://github.com/ElemeFE/element/pull/366/files#diff-fd40886f2b8c2f90093dcfecf0c067baR63

**Comment by acelan86** [comment]
谢谢修复， 好像直接把data中的style变成`style：{}`就OK了，模板里面没用到具体的style width or height

**Comment by QingWei-Li** [comment]
fixed in https://github.com/ElemeFE/element/pull/381/files#diff-fd40886f2b8c2f90093dcfecf0c067baR63

**Comment by acelan86** [comment]
纵向success的icon 样式导致线条偏左， 建议增加样式

```css
.el-step__icon {
     display: block;
}
```

**Comment by QingWei-Li** [comment]
fixed in https://github.com/ElemeFE/element/pull/393
