### ISSUE TITLE
[Bug Report] Select组件创建条目无效

### ISSUE THREAD

**Issue by erjun** [ElemeFE/element#3740]
### Element UI version
1.2.5

### OS/Browsers version
Chrome 56.0.2924.87 (64-bit)

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/r1fw8rno/](https://jsfiddle.net/r1fw8rno/)

### Steps to reproduce
1. 输入内容
2. 选择内容(此时为空)
3. 下拉菜单(此时出现一个空选项)
4. 单击空选项js报错

### What is Expected?
1. 内容不为空
2. js不报错

### What is actually happening?
内容为空
js报错

**Comment by laiyituan** [comment]
[el-select]设置了filterable和allow-create属性，但是没法选中不存在的条目，这个bug还是没有修复啊！

**Comment by geraldlrh** [comment]
遇到同样的问题，修复有时间点吗

**Comment by Leopoldthecoder** [comment]
假期我看看吧。

**Comment by Leopoldthecoder** [comment]
已在 #3984 修复。
是 Vue 2.2.0 的一个改动造成的，和 #3090 的原因一样。具体可参考 https://github.com/vuejs/vue/issues/5001

**Comment by insrv** [comment]
怎么我更新到1.2.7了还是存在这个问题呢

**Comment by Leopoldthecoder** [comment]
@insrv 因为还没有发版。

**Comment by insrv** [comment]
@Leopoldthecoder 哦，这样啊，那我怎么可以解决这个问题呢

**Comment by Leopoldthecoder** [comment]
@insrv 等今天晚些时候发布的 1.2.8

**Comment by insrv** [comment]
@Leopoldthecoder 好的，谢谢

**Comment by imingyu** [comment]
可以使用`el-autocomplete`进行模拟，示例可如下：
https://jsbin.com/woholugowi/edit?html,output

**Comment by insrv** [comment]
@imingyu 谢谢，element已经解决这个问题了
