### ISSUE TITLE
[Feature Request] 建议：1.DateTimePicker 在移动端上无法正常使用，选择器宽度太长，移动设备屏幕小，无法显示完全；2.能否有参数可以设置只需要精确到该小时或者该分钟之类的，后面的置零无法选择 

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#3742]
### Existing Component
是

### Component Name
DateTimePicker

### Description
建议：1.DateTimePicker 在移动端上无法正常使用，选择器宽度太长，移动设备屏幕小，无法显示完全；2.能否有参数可以设置只需要精确到该小时或者该分钟之类的，后面的置零无法选择

**Comment by QingWei-Li** [comment]
1. 不考虑移动设备
2. 设置 format 为 `HH:mm`，如果只精确到 hours，那直接用 select 就好了

**Comment by ShawshankLin** [comment]
> 2\. select

select 是什么？
