### ISSUE TITLE
[Bug Report] upload 组件上传后删除图片 回调的删除方法中传回的fileList中的url会变成blob类型

### ISSUE THREAD

**Issue by zikong** [ElemeFE/element#3744]
### Element UI version
1.2.5

### OS/Browsers version
macOS Sierra / chrome 56.0.2924.87

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/16/](https://jsfiddle.net/pj71jkyw/16/)

### Steps to reproduce
上传图片后再删除图片在回调的删除方法中传回的fileList中的url会变成blob类型

### What is Expected?
在回调的删除方法中传回的fileList中的url都是上传成功后的链接

### What is actually happening?
在回调的删除方法中传回的fileList中的url会变成blob类型

**Comment by baiyaaaaa** [comment]
Upload component can not know what will be response by the server, you can get the url from `file. response`
