### ISSUE TITLE
[Feature Request] 关于表格展开行的一些建议

### ISSUE THREAD

**Issue by zysallen** [ElemeFE/element#3747]
### Existing Component
是

### Component Name
table

### Description
1.建议在表格的expand方法中增加一个参数index，来表示当前行的index

2.建议在表格的属性中增加一个类似于折叠面板的手风琴属性accordion，来达到一次只能展开一行的效果

**Comment by Smith-Curise** [comment]
我也希望这样，让表格一次只能expand一行，最后能够提供个关闭某行expand的方法

**Comment by xtestw** [comment]
我倒是建议设定一个数组控制每一行是否展示

**Comment by zimuqi** [comment]
后面有方法实现控制扩展行的数量么

**Comment by Caraws** [comment]
有办法解决只展开一行的效果么

**Comment by Elaine87** [comment]
可以通过row-key,expand-row-keys 一起控制，能实现一次只展开一行的效果

**Comment by Caraws** [comment]
具体能给个示例吗  非常感谢

**Comment by haocm123** [comment]
在@expand-change 方法中加入下代码可实现一次只能展开一行类似
```
expandedRows.splice(0,expandedRows.length);
expandedRows.push(row);
```

**Comment by phping1** [comment]
通过row-key和expand-row-keys来解决一次只打开一行，关闭其它行的需求，伪代码如下：
1.table绑定事件
`
<el-table highlight-current-row :data="data" class="table" style="width: 100%"
              :row-key="getRowKeys" :expand-row-keys="expands" @expand="queryById">
......
2.在data里添加数据

`
// 要展开的行，数值的元素是row的key值
 expands: [],
`
3.在methods里添加如下方法
`
getRowKeys (row) {
        return row.Id
      },

queryByJobId (row, expandedRows) {
//点击另一行的时候，把expands清空。即可把上一行给关闭，展开当前点击行
              if (row.jobId === this.expands[0]) {
                this.expands = []
              } else {
                this.expands = []
                this.expands.push(row.jobId)
              }
}
`
即可实现需求。

**Comment by JiangXiaoMeng** [comment]
表格导开一个表格做增删改查及分页，主要是子表数据条数不一样后样式会乱的？是什么原因啊？
