### ISSUE TITLE
[Bug Report] popup定位错误

### ISSUE THREAD

**Issue by yangyichen** [ElemeFE/element#3750]
### Element UI version
1.2.5

### OS/Browsers version
win10 /chrome58.0.3026.0

### Vue version
2.2.5

### Reproduction Link
[http://jsfiddle.net/Lme94jk7/1/](http://jsfiddle.net/Lme94jk7/1/)

### Steps to reproduce
当多选框元素通过绝对定位到页面最下方的时候用remote方式加载select，输入关键字a

### What is Expected?
popup定位出现问题，需要往下滚动才能准确定位
![d851d7f0-07f9-11e7-8d94-4da2779c4304](https://cloud.githubusercontent.com/assets/8776272/24287665/6d8eb040-10b5-11e7-8975-8b02aa098101.gif)

### What is actually happening?
popup应该定位到元素上方

**Comment by QingWei-Li** [comment]
就是这样设计的
