### ISSUE TITLE
[Bug Report] 异步请求后，调用弹窗和loading样式冲突，无法锁定body的滚动条

### ISSUE THREAD

**Issue by suzi404** [ElemeFE/element#3756]
### Element UI version
1.2.5

### OS/Browsers version
win7 / chrome

### Vue version
2.2.5

### Reproduction Link
[暂无](暂无)

### Steps to reproduce
见后面

### What is Expected?
弹窗不出现页面抖动

### What is actually happening?

我在另外一个页面issue #3541 中也有提到，但那时还未明白具体原因。

简单的说，就是弹窗（不管是`dialog`或者是`message`等等）调用时，有时会出现只在`body`上加载了`padding-right:17px`而未加上`overflow:hidden`。这就导致了页面会出现滚动条，并且在弹窗开关时，页面会抖动。

今天我才发现是在请求后台后跟拦截器里的loading组件会有样式冲突，再调用弹窗就会出现这种情况，比如：
```
Vue.http.get(url).then((res) => {
                MessageBox.alert(res.errorMsg, '提示', {
                    confirmButtonText: '确定',
                    type:'error'
                })
}
```
@Leopoldthecoder 大神，有时间抓紧修复下吧，我为了解决这个问题，弄了一整天。

**Comment by Leopoldthecoder** [comment]
给个重现 demo，否则很难定位。

**Comment by suzi404** [comment]
最终定位原因是因为弹窗和注入在拦截器loading会有冲突，dome我本地会弄，在jsfiddle上不知道怎么注入拦截器https://jsfiddle.net/manitoS/5Lxn7twL/16/ ，但是代码差不多就是这样

**Comment by Leopoldthecoder** [comment]
弹窗和 Loading 谁先出现的时候会有这个问题？

**Comment by suzi404** [comment]
loading吧，你可以看下上面我给的dome。
那个dome我线下能跑通，线上我不知道怎么拿到vue-resource实例，不知道怎么注入拦截器。

**Comment by Leopoldthecoder** [comment]
可以整理成一个仓库，我克隆下来看看

**Comment by suzi404** [comment]
大哥，代码我都全贴出来了，产生的环境也只是vue,vue-resource以及你们的组件库，你要克隆可以直接去dome里复制，原因我也说了是loding和弹窗同时触发时body上的样式冲突问题。

**Comment by HzLinWeiRan** [comment]
怎么解决的

**Comment by xiangshichongfeng** [comment]
解决了吗？
