### ISSUE TITLE
[Bug Report] el-time-picker is-range初始值设置问题

### ISSUE THREAD

**Issue by x007xyz** [ElemeFE/element#3757]
### Element UI version
1.2.5

### OS/Browsers version
Windows Chrome58

### Vue version
2.2.5

### Reproduction Link
[http://jsfiddle.net/x007xyz/nz15aav3/1/](http://jsfiddle.net/x007xyz/nz15aav3/1/)

### Steps to reproduce
el-time-picker is-range初始值为空数组，[new Date(), new Date()]或者结束时间大于初始时间时，该控件无法正常选择

### What is Expected?
初始值不合法（结束时间大于初始时间、初始值为空数组）会设置为当前时间，应该可以正常使用。

### What is actually happening?
设置为[new Date(), new Date()]即当前时间无法正常使用，但是设置一个比较早的时间又是有效的（如官方案例的设置），还有就是数组只能设置date类型，设置如['2016-09-01 08:40:00', '2016-09-01 08:40:00']也是不可以的。

**Comment by Telanx** [comment]
希望允许初始或者截止时间为空，而不一定要初始或者截止时间全部选中

**Comment by Leopoldthecoder** [comment]
最新版已无此问题。

**Comment by GreatAuk** [comment]
版本 2.4.6 还是有这个问题

**Comment by zxloading** [comment]
版本2.27.0还有这个问题，而且is-range使用picker-options部分参数无效

**Comment by sunshine-snowy** [comment]
怎么解决这个问题
