### ISSUE TITLE
[Bug Report] before-upload添加文件类型校验后，校验失败的文件也出现在文件列表中

### ISSUE THREAD

**Issue by cmlily8294** [ElemeFE/element#3758]
### Element UI version
1.2.5

### OS/Browsers version
macOS／chrome57

### Vue version
2.2.5

### Reproduction Link
[http://jsfiddle.net/mjLpg1bx/](http://jsfiddle.net/mjLpg1bx/)

### Steps to reproduce
上传非图片

### What is Expected?
校验失败后上传列表没有上传失败的文件

### What is actually happening?
校验失败的文件出现在了上传列表中

**Comment by waynehong** [comment]
我也是遇到这个问题，我是在加accept参数来避免这种情况

**Comment by baiyaaaaa** [comment]
It has been fixed, please checkout the lastest relase. If not, you can reopen this issue
