### ISSUE TITLE
【问题】如果国际化表单验证中的message

### ISSUE THREAD

**Issue by xingchch** [ElemeFE/element#3763]
如题

` :rules="[
      { required: true, message: '请输入邮箱地址', trigger: 'blur' },
      { type: 'email', message: '请输入正确的邮箱地址', trigger: 'blur,change' }
    ]"`
像上面的message 如何国际化？

百忙中打扰，还望见谅。

**Comment by xingchch** [comment]
写下解决方案:
localeResource: {
          zh: {
            rules: {
              name: [
                {required: true, message: '请输入园区名称', trigger: 'blur'},
                {min: 1, max: 50, message: '长度在 1 到 50 个字符', trigger: 'change'}
              ]
            }
          },
          en: {
            rules: {
              name: [
                {required: true, message: 'Please Input project name', trigger: 'blur'},
                {min: 1, max: 50, message: 'length 1 - 50 chars', trigger: 'change'}
              ]
          }
        },

**Comment by snow-sprite** [comment]
老铁怎么解决的？

**Comment by snow-sprite** [comment]
@xingchch 老铁怎么解决的？
