### ISSUE TITLE
[Bug Report] 编辑table某条记录，不能同步到视图

### ISSUE THREAD

**Issue by cmlily8294** [ElemeFE/element#3764]
### Element UI version
1.2.5

### OS/Browsers version
macOS／chrome

### Vue version
2.2.5

### Reproduction Link
[http://jsfiddle.net/ppdu3opf/1/](http://jsfiddle.net/ppdu3opf/1/)

### Steps to reproduce
1.点击编辑
2.修改值
3.保存

### What is Expected?
更新table中的记录（1.2.5之前版本可行）

### What is actually happening?
未更新table中的记录

**Comment by lincenying** [comment]
```
//this.tableData[this.currentIndex] = this.model;
this.$set(this.tableData, this.currentIndex, this.model)
```

**Comment by Leopoldthecoder** [comment]
请参照楼上。
