### ISSUE TITLE
el-form-item label 不能改属性

### ISSUE THREAD

**Issue by chrislingxiao** [ElemeFE/element#377]
### ElementUI version
1.0.0-rc.6

### OS/Browers version
 Windows 10/Chrome 53

### Vue version
2.0.1

### What is Expected?
应该可以用css选择label tag来更改属性。
### What is actually happening?
用css 选择label，拿不到element。改用class name，也拿不到element，所以不能设置label的属性。

**Comment by baiyaaaaa** [comment]
看不太明白，“用css 选择label” 是什么意思？

**Comment by jikkai** [comment]
我猜是Scoped CSS的问题？

**Comment by QingWei-Li** [comment]
vue 的 scoped 其实并不好用

**Comment by erguotou520** [comment]
应该是scoped问题，需要覆盖`element`的ui样式的地方就不要写scoped了

**Comment by chrislingxiao** [comment]
不好意思没表达清楚，css选择label就是 （我用的scss）：
`.el-form-item {
    label {
       color: white;
    }
}` 

哦哦，就是说scoped styling 会导致不能覆盖elem的styling啊。我回去试试。

**Comment by chrislingxiao** [comment]
刚刚回来把scoped去掉就可以work了， 确实是这个问题。
是不是应该把这个加到文档里？

**Comment by erguotou520** [comment]
这不是`element-ui`的问题，这个是`vue-loader`的，你可以去看它的文档

**Comment by chrislingxiao** [comment]
恩恩，看到了，那就关这个issue了。

**Comment by ye0101** [comment]
.el-form-item  label { width: 90px !important} 可以使用优先级强制覆盖

**Comment by syt-honey** [comment]
> 应该是scoped问题，需要覆盖`element`的ui样式的地方就不要写scoped了

都去掉scoped就意味着只要别的地方写了同样的组件，那里面的样式就会把之前的覆盖掉。那有没有什么办法不覆盖前面的样式呢？

**Comment by syt-honey** [comment]
> 应该是scoped问题，需要覆盖`element`的ui样式的地方就不要写scoped了

都去掉scoped就意味着只要别的地方写了同样的组件，那里面的样式就会把之前的覆盖掉。那有没有什么办法不覆盖前面的样式呢？ @erguotou520

**Comment by jikkai** [comment]
@syt-honey [深度作用选择器](https://vue-loader.vuejs.org/zh/guide/scoped-css.html#%E6%B7%B1%E5%BA%A6%E4%BD%9C%E7%94%A8%E9%80%89%E6%8B%A9%E5%99%A8)

**Comment by BinghuiXie** [comment]
element支持自定义label覆盖原来的label，可以直接自己写label就好了
