### ISSUE TITLE
[Feature Request] 请给 pagination 翻页事件增加来源

### ISSUE THREAD

**Issue by meathill** [ElemeFE/element#3774]
### Existing Component
是

### Component Name
pagination

### Description
我会侦听 Pagination.@current-change 事件，然后从服务器端取出新一页的数据；并且取出数据总条数，然后赋给 pagination.total，这个时候又会触发一次 @current-change，以至无限循环。建议增加一个事件来源，以便区分。

**Comment by erjun** [comment]
你这个没有代码啊，建议写个jsfiddle。
我也会设置total。。没遇到过你说的bug

**Comment by meathill** [comment]
这个问题的确有些奇怪，我直接通过 jsfiddle 也无法复现，应该和整个环境有关。

代码在 https://github.com/meathill/wp-plugin-weixin/blob/master/app/admin.js#L23-L50，我整理出 fiddle 之前可以先看一下。

这个问题其实不是第一个问题。出现这个问题之前，我的问题是 `this.$refs.pagination.total = response.total_count;` 的时候，组件没有重新渲染，显示的仍然是前后按钮的初始状态。我把组件放到 window 里，然后通过控制台设置 total，就没有问题。后来我加上 setTimeout，解决了前一个问题，开始面对这个问题。

我再想办法抽出来吧。
