### ISSUE TITLE
[Feature Request] Pagination 分页组件, 建议监控点击事件, 而不是当前页变化

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#3775]
### Existing Component
是

### Component Name
Pagination

### Description
我想很多人都有这个需求, 就是一个列表页面, 有分页功能, 但是还有搜索功能
现在的情况是, 当 当前页数不是第1页时, 进行外部条件搜索, 搜索ajax成功后, 肯定需要将当前页数重置为1, 但是因为之前的页数不是1, 导致组件判断页数变化, 所以Pagination组件又重新加载了一次请求.

http://jsfiddle.net/mjLpg1bx/1/

如上面链接, 先点击后面的页数, 然后点搜索, 就会出现两次请求

**Comment by web-surfer** [comment]
Yeah, pagination on tables would be really helpful.

**Comment by erjun** [comment]
是你写的代码有问题，你把 这一行去掉就行了。
this.currentPage1 = page

**Comment by erjun** [comment]
其实你搜索不用调用getdata的，就设置currentPage1=1就行了。

**Comment by lincenying** [comment]
@erjun 这个方法也想到过, 在项目中逻辑比例子复杂很多, 很不好实现, 比如用了vuex

**Comment by erjun** [comment]
@lincenying 我不太明白分页怎么和vuex有关系了。你可以详细说明一下。其实给表格加搜索功能的几乎都有，饿了么公司肯定也有，我也有。可是我们都没遇到问题。。。

**Comment by lincenying** [comment]
我是把page都放在vuex里, 后端会传回来. 要设置currentPage=1. 就得给每个module都设置个重置page的mutations, 感觉很奇怪. 另外搜索条件是放在组件里的, 传给vuex的actions的, 直接改vuex的currentpage, 搜索条件也变不了.

现在暂时是用这方法解决
```javascript
const mixin = {
    data() {
        return {
            lock_search: false,
        }
    },
    methods: {
        async handleCurrentChange(page) {
            if (this.lock_search && page === 1) {
                this.lock_search = false
                return
            }
            await this.init({ ...this.searchForm, page })
        },
        searchSubmit() {
            this.lock_search = true
            this.init(this.searchForm)
        },
        searchReset() {
            Object.keys(this.searchForm).forEach(item => {
                this.searchForm[item] = undefined
            })
            this.lock_search = true
            this.init()
        }
    },
    mounted() {
        this.init(this.searchForm)
    }
}
export default mixin
```

**Comment by AaronChen2012** [comment]
自己在他们的table上封装一个table，然后你的界面上都使用自己的table啊！在你基础的 table中处理啊。
类似handleSizeChange(val) {
      	this.pageSize=val;
      	if (this.pageIndex==1){
      		this.fetchData();
      	}else{
      		this.pageIndex=1;
      	}
      },
      handleCurrentChange(val) {
      	this.pageIndex=val;
      	this.fetchData();
      },

**Comment by erjun** [comment]
@lincenying page也算筛选条件的。为什么page放到vuex？所有module共用一个page？这不更奇怪？
其实封装不是代码越少越好，是逻辑越清晰越好。而且看你的代码init方法是接受page参数的，search的时候传1或者默认就是1就好了呀。至于你说的搜索条件没太听懂。
反正我是建议你把筛选项和page不要放到vuex，就获取数据把数据放到vuex。如果用vuex反而把代码搞的更复杂不如不用。
最后，我看了你的代码也没看出来加了点击事件对你有什么帮助。。。这个你可以也说一下，为什么加了点击事件就帮助你了？

**Comment by lincenying** [comment]
根据建议, 现在改成
```javascript
const mixin = {
    data() {
        return {
            current_page: 1,
        }
    },
    methods: {
        async handleCurrentChange(page) {
            window.scrollTo(0, 0)
            this.$store.commit('loading', true)
            await this.init({ ...this.searchForm, page })
            this.$store.commit('loading', false)
            this.current_page = page
        },
        searchSubmit() {
            if (this.current_page === 1) this.init({ ...this.searchForm })
            else this.current_page = 1
        },
        searchReset() {
            Object.keys(this.searchForm).forEach(item => {
                this.searchForm[item] = undefined
            })
            this.searchSubmit()
        }
    },
    mounted() {
        this.init(this.searchForm)
    },
    watch: {
        '$route' () {
            this.init(this.searchForm)
        }
    }
}

export default mixin
```

用起来也没问题, 先关了吧.
