### ISSUE TITLE
[Feature Request] Tag 标签组件添加的标签超过一行时部分重叠

### ISSUE THREAD

**Issue by DullSky** [ElemeFE/element#3779]
### Existing Component
是

### Component Name
Tag 标签

### Description
![image](https://cloud.githubusercontent.com/assets/15259698/24323876/3d760dce-11b7-11e7-95a0-d9b52011dce2.png)

这个希望官方默认给予适当的margin-top，这样看起来美观一些，而且可以直接拿来就用

**Comment by jikkai** [comment]
每个人的需求都不一样，碰到这种情况可以自行用 css 覆盖样式解决
