### ISSUE TITLE
lockScroll in dialog is cannot work

### ISSUE THREAD

**Issue by yiling-e0** [ElemeFE/element#378]
### ElementUI version
1.0.0-rc.6

### OS/Browers version
win7/Chrome 53

### Vue version
2.0.1

lockScroll in dialog is cannot work

**Comment by Leopoldthecoder** [comment]
文档写错了，应该是 `lock-scroll`。默认值是 `true`，想关掉的话需要
```html
<el-dialog title="xxx" v-model="xxx" :lock-scroll="false">
```
试一下这样行不行
