### ISSUE TITLE
[Bug Report] table 里面嵌套 button，ref="button"，app.$refs.button 应为数组，实际指向最后一个 button 

### ISSUE THREAD

**Issue by meathill** [ElemeFE/element#3783]
### Element UI version
1.2.5

### OS/Browsers version
Chrome 57

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/meathill/50ar5f6o/](https://jsfiddle.net/meathill/50ar5f6o/)

### Steps to reproduce
运行后看下控制台，会输出一个数组，使用 `<li v-for>` 添加的普通 `<button>`，可以通过 `app.$refs.button` 获取到所有 `<button>`。接下来是 undefined，使用 `<el-table>` 和 `<el-button>` 嵌套，只能取到最后一个 `<el-button>`。

### What is Expected?
依据 Vue.js 的官方文档，`ref` 值一样，应该输出为一个数据，包含所有同引用名元素。

### What is actually happening?
使用 `<el-table>` 和 `<el-button>` 嵌套，并指定 `ref` 时，`ref` 指向最后一个 `<el-button>`。

**Comment by Leopoldthecoder** [comment]
并不是 `ref` 值一样就会输出为一个数组，只有当 `ref` 和 `v-for` 搭配使用才会这样。
你的具体场景是什么？是否一定要在 Table 里加 `ref`？

**Comment by meathill** [comment]
是的，我的表格每一行有一个按钮，点击后会请求服务器，所以希望能够 `el-button.loading=true`，我试了 `:loading="scope.row.fetching"` 也不奏效。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/50ar5f6o/1/

你的 fetching 字段在数据对象里有定义吗？

**Comment by meathill** [comment]
应该是没有。所以应该是没预先设置的问题。

那么麻烦给个提示吧，正常 Vue 里如果一个属性没定义是会有提示的。

**Comment by Leopoldthecoder** [comment]
这种情况下，Vue 也不会提示：https://jsfiddle.net/leopoldthecuber/50ar5f6o/2/

**Comment by meathill** [comment]
的确如此，是我误会你们了。

谢谢答疑。
