### ISSUE TITLE
[Bug Report] Datepicker always formats dates in English

### ISSUE THREAD

**Issue by iabdulin** [ElemeFE/element#3786]
### Element UI version
1.2.5

### OS/Browsers version
Mac OS X, Chrome

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/46xbxcz5/2/](https://jsfiddle.net/46xbxcz5/2/)

### Steps to reproduce
1) No locale is imported

2) Datepicker is initialized with format='MMMM yyyy' and type="month".

3) Open Datepicker => see months in default locale

4) Select Month => Datepicker will format the month in English

### What is Expected?
Datepicker should format selected value using the app locale.

### What is actually happening?
Datepicker always formats selected value in English.

![image](https://cloud.githubusercontent.com/assets/622315/24334958/74862482-1231-11e7-8512-6a997234c0e6.png)

**Comment by SasmeitoU** [comment]
Did you fix the issue?

**Comment by iabdulin** [comment]
any updates on this?

**Comment by Leopoldthecoder** [comment]
@QingWei-Li dalao could you look into this?

**Comment by ghosh** [comment]
Same issue here. It is also happening on the most basic version, without any formatting.

**Info**
element-ui: v1.3.7
vue: v2.3.1

**Screenshot**
<img width="302" alt="screen shot 2017-06-20 at 11 43 12 pm" src="https://user-images.githubusercontent.com/4667682/27348685-8c579134-5612-11e7-9fb7-f04615a43fc3.png">

**Comment by Leopoldthecoder** [comment]
Fixed in #5485.

@ghosh Element uses Chinese by default. To use another language, you should configure its i18n.
