### ISSUE TITLE
[Bug Report] Tree组件怎么定义鼠标双击事件

### ISSUE THREAD

**Issue by PolanZ** [ElemeFE/element#3789]
### Element UI version
1.2.5

### OS/Browsers version
all

### Vue version
2.2.5

### Reproduction Link
[none](none)

### Steps to reproduce
无

### What is Expected?
希望能够tree组件上节点添加上鼠标双击事件，因为有个操作是需要双击来执行，
并且双击时其他操作要阻止

### What is actually happening?
希望能够tree组件上节点添加上鼠标双击事件，因为有个操作是需要双击来执行，
并且双击时其他操作要阻止

**Comment by Leopoldthecoder** [comment]
可以通过 `render-content` 传入自定义的渲染函数。
