### ISSUE TITLE
[Bug Report] 表单验证的时候，组件类型是el-select，如果字段类型为Number，验证失败。

### ISSUE THREAD

**Issue by hao3304** [ElemeFE/element#3790]
### Element UI version
1.2.5

### OS/Browsers version
MacOS

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/hao3304/7nhnptsg/1/](https://jsfiddle.net/hao3304/7nhnptsg/1/)

### Steps to reproduce
表单跟示例一样，只是v-model改成了 v-model.number。

### What is Expected?
el-select选择值后，验证成功，不出现提示信息。

### What is actually happening?
出现验证的Message信息。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/7nhnptsg/2/
需要在验证规则里显式注明 type 为 `number`

**Comment by hao3304** [comment]
谢谢，已解决。
