### ISSUE TITLE
select  multiple   validator   保存时自动清空select并执行validator  出现提示

### ISSUE THREAD

**Issue by tiananyang1** [ElemeFE/element#3791]
如下图：
![select](https://cloud.githubusercontent.com/assets/26404911/24339578/25b98f52-12df-11e7-8665-a79197a6d8df.gif)

代码：
**js:**
ruleItem:[{ validator: validateRule, trigger: 'change' }]

var validateRule = (ruleInfo, value, callback)=>{
                if (value.length < 1){
                    callback(new Error('请选择规则'));
                }else{
                    callback();
                }
            };
**html:**
<el-form-item label="规则"  required prop="ruleItem">
            <el-select v-model="form.ruleItem" multiple  placeholder="请选择规则">
                <el-option
                        v-for="item in ruleItems"
                        :label="item.ruleName"
                        :value="item.id">
                </el-option>
            </el-select>
        </el-form-item>

**Comment by qiuyaofan** [comment]
遇到相同问题

**Comment by smphp** [comment]
怕不是傻吧~  这框架真难用
