### ISSUE TITLE
[Bug Report] 选中导航栏三级菜单，重新刷新后，丢失原有信息

### ISSUE THREAD

**Issue by konce** [ElemeFE/element#3792]
### Element UI version
1.2.4

### OS/Browsers version
mac 10.11.4 / chrome  56.0.2924.87

### Vue version
2.2.4

### Reproduction Link
[没有写链接..就是三级导航刷新之后，原来激活信息丢失](没有写链接..就是三级导航刷新之后，原来激活信息丢失)

### Steps to reproduce
1. 用vue-router加element框架搭建简单的路由页面
2. 竖直形状的导航栏有三级菜单
3. 点击其中的一个三级菜单，该菜单被激活
4. 刷新页面，激活的菜单不再显示，需要重新点击

ps: 如果是二级菜单则没有问题

### What is Expected?
三级应该也可以 嵌套递归寻找被点击的index，然后激活

### What is actually happening?
三级菜单点击之后，如果一旦刷新，就会丢失激活信息

**Comment by Leopoldthecoder** [comment]
补一下 demo 吧
