### ISSUE TITLE
[Feature Request] select multiple validator 保存时自动清空select并执行validator 出现提示

### ISSUE THREAD

**Issue by tiananyang1** [ElemeFE/element#3793]
### Existing Component
是

### Component Name
select mutiple

### Description

select multiple validator 保存时自动清空select并执行validator 出现提示

https://cloud.githubusercontent.com/assets/26404911/24339665/c7760fd2-12df-11e7-8b92-35a22648e031.gif
代码：
js:
ruleItem:[{ validator: validateRule, trigger: 'change' }]

var validateRule = (ruleInfo, value, callback)=>{
if (value.length < 1){
callback(new Error('请选择规则'));
}else{
callback();
}
};
html:

**Comment by Leopoldthecoder** [comment]
这不是一个 Feature Request，请选择 Bug Report，并附上重现 demo 重新提交。
