### ISSUE TITLE
select组件被destroy时出现TypeError: Cannot read property '__resizeListeners__' of undefined

### ISSUE THREAD

**Issue by Ryan-PEK** [ElemeFE/element#3797]
### Element UI version
1.2.5

### OS/Browsers version
chrome 57

### Vue version
2.2.6

### Reproduction Link
[无](无)

### Steps to reproduce
子页面使用el-select后，切换到其他子页面，在执行destory时出现如题JS error。
vue.runtime.esm.js:554 [Vue warn]: Error in destroyed hook: 
(found in <ElScrollbar>)
vue.runtime.esm.js:1443 TypeError: Cannot read property '__resizeListeners__' of undefined
    at removeResizeListener (resize-event.js:183)
    at VueComponent.destroyed (scrollbar.js:245)
    at callHook (vue.runtime.esm.js:2269)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js:2091)
    at destroy (vue.runtime.esm.js:2958)
    at invokeDestroyHook (vue.runtime.esm.js:4773)
    at invokeDestroyHook (vue.runtime.esm.js:4778)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:5039)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js:2089)
    at destroy (vue.runtime.esm.js:2958)

### What is Expected?
没有JS Error

### What is actually happening?
出现描述中的error

**Comment by lincenying** [comment]
应该是vue 2.2.6改的https://github.com/vuejs/vue/commit/3209f6f517a4fa44c563cd7cc048fa29be1bc930这个的原因, 

https://github.com/ElemeFE/element/blob/dev/packages/scrollbar/src/main.js#L128
这个应该也有问题.

**Comment by tbphp** [comment]
我也出现同样的问题，select销毁是报同样的错。

**Comment by Rranran** [comment]
+1

**Comment by tbphp** [comment]
[jsfiddle示例](https://jsfiddle.net/rfo70j27/)

这个示例下面el-select隐藏的时候就会报错。
我已经测试过，vue2.2.6才会报错，2.2.5以下没有这个错误。

**Comment by peakcool** [comment]
+1，在被销毁时产生了警告
`[Vue warn]: Error in destroyed hook: 
(found in <ElScrollbar>)
warn @ vue.common.js?e881:560
handleError @ vue.common.js?e881:1445
callHook @ vue.common.js?e881:2277
Vue.$destroy @ vue.common.js?e881:2097
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
invokeDestroyHook @ vue.common.js?e881:4779
invokeDestroyHook @ vue.common.js?e881:4784
patch @ vue.common.js?e881:5045
Vue.$destroy @ vue.common.js?e881:2095
destroy @ vue.common.js?e881:2964
(anonymous) @ vue.common.js?e881:3246
invokeDestroyHook @ vue.common.js?e881:4779
removeVnodes @ vue.common.js?e881:4795
updateChildren @ vue.common.js?e881:4902
patchVnode @ vue.common.js?e881:4936
patch @ vue.common.js?e881:5060
Vue._update @ vue.common.js?e881:2042
updateComponent @ vue.common.js?e881:2158
get @ vue.common.js?e881:2469
run @ vue.common.js?e881:2539
flushSchedulerQueue @ vue.common.js?e881:2331
(anonymous) @ vue.common.js?e881:507
nextTickHandler @ vue.common.js?e881:456
vue.common.js?e881:1449 TypeError: Cannot read property '__resizeListeners__' of undefined`

**Comment by thenCoding** [comment]
+1，同样遇到这个问题.看了半天以为代码哪里没写对，上来一看才发现这是个BUG啊，哈哈.

**Comment by Rranran** [comment]
这个问题还是存在的啊·@Leopoldthecoder

**Comment by Zeno-Code** [comment]
全部更新了一遍,问题依旧

**Comment by pab50** [comment]
This problem still exists for me too

**Comment by Leopoldthecoder** [comment]
抱歉，只修了 Select，没修 Scrollbar。暂时先降级 Vue 吧。

**Comment by An0nymous0** [comment]
@Leopoldthecoder 预计下一版什么时候发布。 vue2.2.5 跟 vue-router 还有内存泄露的情况。

**Comment by bigrocs** [comment]
vue2.2.5  vue-router  和tabs还是会报错

**Comment by QingWei-Li** [comment]
@An0nymous0 @bigrocs 今天吧

**Comment by QingWei-Li** [comment]
@bigrocs 
> vue-router 和tabs还是会报错

哪个 issue？问题是啥

**Comment by bigrocs** [comment]
没有开issue  当我切换路由  或者tabs标签发送http请求是都会报错如下
`[Vue warn]: Error in destroyed hook: `
`TypeError: Cannot read property '__resizeListeners__' of undefined`

**Comment by QingWei-Li** [comment]
@bigrocs 
可否给重现链接？tabs 并没有使用 `resize-event`，也是 select 引起的么？

**Comment by bigrocs** [comment]
@QingWei-Li 
我不确定什么引起的 我先排查下稍后给你答案

**Comment by tbphp** [comment]
@bigrocs 
应该是tabs或者路由切换的时候销毁select销毁，然后导致触发这个bug。
我就是这个情况。
所以还是select的bug。
你可以把页面所有select都删除了，就不会有这个bug了

**Comment by bigrocs** [comment]
@tbphp 
好像不行  我使用table组件的的页面也出现这个情况

**Comment by tbphp** [comment]
@bigrocs 你看你组件里面有没有select比如分页组件里面也有下拉组件。

**Comment by bigrocs** [comment]
@tbphp @QingWei-Li
我吧整个select引用都注释掉一样触发
我的好像是axios.post 访问开始触发这个BUG  奇怪..
然后访问结束在触发一次

**Comment by bigrocs** [comment]
是我错了 。。。  确实是select引起的

**Comment by bigrocs** [comment]
@tbphp @QingWei-Li  
我确定一件事情
pagination 组件也引起了这个BUG

**Comment by HadiChen** [comment]
我也遇到了这个问题，每次页面切换时就会抛错
![image](https://cloud.githubusercontent.com/assets/11555571/24437026/4a4d9a64-1471-11e7-8d2e-ab842c53e79c.png)

**Comment by wkyhy205104** [comment]
我也出现了同样的问题，将select删除后并不会出现该问题，应该是select本身的问题吧，不知道什么时候能够给出解决方案？

**Comment by bigrocs** [comment]
组件 pagination 组件好像也是引用select组件引起的..

**Comment by bigrocs** [comment]
什么时候发布修复版本

**Comment by QingWei-Li** [comment]
`v1.2.7` has been released.

**Comment by TaylerTao** [comment]
感谢！

**Comment by GaoYuanOnline** [comment]
![tim 20170421194607](https://cloud.githubusercontent.com/assets/19809829/25276125/3ba6f57a-26cb-11e7-840f-9007ddbda012.png)
请问该问题现在是如何解决了？
我将vue 2.2.6版本 升到最高，然后elementUi 1.2.7也升级到最高后不可以解决该问题。
将版本降下来后vue是2.2.5也不行。有解决的么

**Comment by Leopoldthecoder** [comment]
@GaoYuanOnline 用 1.2.9

**Comment by GaoYuanOnline** [comment]
@Leopoldthecoder  升级到1.2.9后可以解决该问题，谢谢！

**Comment by vincepeng** [comment]
还是有问题,尝试降级vue为2.2.5也是一样的
![image](https://user-images.githubusercontent.com/3695117/28245264-6658a70c-6a35-11e7-91df-40b81df9525a.png)
![image](https://user-images.githubusercontent.com/3695117/28245267-76ee1d72-6a35-11e7-83ff-0de518f525d4.png)

**Comment by tbphp** [comment]
@vincepeng 这都哪个版本了，你把你的包都`npm-check -u`升级一下，这个问题早就应该不存在了。
