### ISSUE TITLE
[Bug Report] Tree 树形控件 的 自定义节点内容【文档】以及【在线运行】存在bug 无法正常运行

### ISSUE THREAD

**Issue by lcyang987** [ElemeFE/element#3807]
### Element UI version
1.2.5

### OS/Browsers version
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
打开链接地址

### What is Expected?
无法跟文档上的效果一样

### What is actually happening?
文字和按钮都消失了

**Comment by lcyang987** [comment]
https://jsfiddle.net/czLrndmd/ 补充下地址

**Comment by yy0608** [comment]
I met this issue too, cannot solve this problem.
Thank you !

**Comment by yy0608** [comment]
Can you tell me how did you solved?

**Comment by asea1718** [comment]
同样遇到这个问题

**Comment by pihou** [comment]
同样遇到这个问题

**Comment by Leopoldthecoder** [comment]
![image](https://cloud.githubusercontent.com/assets/10095631/25178705/88b63544-2539-11e7-996e-e680f135f7ec.png)

文档上已经写了这个问题的原因。如果看不到的话，可能需要清空一下浏览器缓存。
