### ISSUE TITLE
[Bug Report] Multiple popover v-model to same data object

### ISSUE THREAD

**Issue by getanwar** [ElemeFE/element#3809]
### Element UI version
1.2.5

### OS/Browsers version
Chrome latest

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/3zrh2u9p/](https://jsfiddle.net/3zrh2u9p/)

### Steps to reproduce
Click Button one, then click button two

### What is Expected?
popover should appear on both buttons

### What is actually happening?
I have a table which gets its rows dynamically from the server. I want to have a delete button to show confirmation popover on it before removing each item. but it requires multiple properties to attach with v-model: such as: visible2: false, visible3: false, visi...... But it's not logical that I add multiple properties under my vue data prop because the rows will be loaded from the server dynamically, could be less or more.

Is there any way that I can use the same popover

**Comment by Leopoldthecoder** [comment]
I'm afraid not. You can add a property to each data item after data is returned from the server.
