### ISSUE TITLE
[Bug Report] menu组件加入router属性后控制台报错

### ISSUE THREAD

**Issue by SnailSword** [ElemeFE/element#3812]
### Element UI version
1.2.4

### OS/Browsers version
win10 / chrome 56.0.2924.87

### Vue version
2.1.8

### Reproduction Link
[http://jsfiddle.net/ncnzerg1/](http://jsfiddle.net/ncnzerg1/)

### Steps to reproduce
1.  打开官网提供的[menu组件示例(http://jsfiddle.net/api/post/library/pure/)
2.  在第四行加入 ```router="true"```  或  ```router=true```  或  ```router="false"```属性，见[重现链接](http://jsfiddle.net/ncnzerg1/)

### What is Expected?
控制台无报错

### What is actually happening?
控制台报错

```
[Vue warn]: Invalid prop: type check failed for prop "router". Expected Boolean, got String. 
(found in <ElMenu>)
```

**Comment by animabear** [comment]
Write it like this:
`:router="true"`

**Comment by Leopoldthecoder** [comment]
参考楼上。
