### ISSUE TITLE
[Bug Report] build出来的lib目录下的index.js貌似有问题

### ISSUE THREAD

**Issue by yibuyisheng** [ElemeFE/element#3813]
### Element UI version
1.2.5

### OS/Browsers version
Mac / Chrome 57

### Vue version
2.1.10

### Reproduction Link
[无](无)

### Steps to reproduce
查看`lib/index.js`，位于`c.default.prototype.$isServer,h=`处。

### What is Expected?
没错

### What is actually happening?
抛错：`index.js:2 Uncaught TypeError: Cannot read property 'prototype' of undefined`

![image](https://cloud.githubusercontent.com/assets/2581682/24368931/f6ee3404-1354-11e7-9469-c5695dcc1167.png)

**Comment by Leopoldthecoder** [comment]
需要提供一下具体的报错组件和重现链接，准备好之后请重开一个 issue。
