### ISSUE TITLE
[Feature Request] form-item建议修改,定义这个show-message时增加css

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#3815]
### Existing Component
是

### Component Name
form-item

### Description
类似如下修改：
1.设置为show-message:false时，不需要增加高度
修改如下：
添加css：'is-showmessage':showMessage
.el-form-item .is-showmessage{
margin-bottom: 22px;
}

**Comment by yibuyisheng** [comment]
为啥不是你使用的时候控制呢？在`form-item`上使用`v-if`或`v-show`。

**Comment by AaronChen2012** [comment]
最后能提供这个，因为有些情况下，是不需要这么个高度的！ v-if或v-show 可以解决，但是我觉得不是最好的解决方式

**Comment by AaronChen2012** [comment]
是的，但是至少可以通过 自己 用 .xx .el-form-item .is-showmessage 来重新设置高度

**Comment by Leopoldthecoder** [comment]
目前也可以自己写 CSS 覆盖。

**Comment by AaronChen2012** [comment]
目前是自己加的css来覆盖的，就是比较繁琐了。

**Comment by Leopoldthecoder** [comment]
理解你的意思，我其实试了一下，22 像素的间距其实并不会显得太大；如果确实觉得大，那么究竟多少才合适又是一个众口难调的问题，所以还是自己控制吧。

**Comment by AaronChen2012** [comment]
还是加吧，就两行代码。这样会灵活很多！
