### ISSUE TITLE
[Feature Request] 能否在Cascader改变后既返回value也返回currentLabels??

### ISSUE THREAD

**Issue by Telanx** [ElemeFE/element#3819]
### Existing Component
是

### Component Name
Cascader

### Description
目前Cascader只返回了value，并没有返回currentLabels，希望可以返回那个，因为有的时候会有用

**Comment by AaronChen2012** [comment]
获取显示值，确实是非常必须的！

**Comment by Leopoldthecoder** [comment]
拿到 value 后自己去数据源里找对应的数据项就好。

**Comment by AaronChen2012** [comment]
自己去找也没问题，但是组件中已经处理了，还需要再自己处理一遍，感觉有点不好！

**Comment by Telanx** [comment]
@AaronChen2012 是的，看源码Cascader是有保存currentLabels,但是没有提供一个访问的接口，可能是他们认为这不是一个重要更新，也不想多麻烦。我觉得你真的要获取显示值得话，可以通过$refs来直接访问该Cascader组件，从何可以通过`vm.$refs[关联组件名].currentLabels`获取到.

**Comment by HarryQQ** [comment]
希望能在回调的参数里面加上label,会方便一点。
