### ISSUE TITLE
treetable

### ISSUE THREAD

**Issue by roughsoft** [ElemeFE/element#382]
有一些业务对象，需要结合table组件，tree组件来一起显示，比较直观。
目前怎么样实现这样的嵌套呢？

**Comment by furybean** [comment]
暂时没计划实现 TreeTable，可以考虑左侧放 Tree，点击之后改变右侧的内容。

**Comment by roughsoft** [comment]
谢谢！就是体验差了些。

**Comment by wucangeo** [comment]
@furybean 很多业务需要这么展示，希望考虑，谢谢！
