### ISSUE TITLE
[Bug Report] 建议使用“word-wrap: break-word;"作为table单元格的默认样式

### ISSUE THREAD

**Issue by AnonymousArthur** [ElemeFE/element#3821]
### Element UI version
1.2.5

### OS/Browsers version
MacOS

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/ultraN/xj1nyamy/1/](https://jsfiddle.net/ultraN/xj1nyamy/1/)

### Steps to reproduce
打开jsfiddle即可。

### What is Expected?
表格中的单元格应使用"word-wrap: break-word" CSS 样式以正确排版英文单词。

### What is actually happening?
表格中的单元格未使用"word-wrap: break-word" CSS 样式，以至于英文单词以单个字幕排版，影响美观。虽然可以通过override css来修复，但是这会影响代码美观。

**Comment by manV** [comment]
This is really annoying bug, @ultraN did you find any workaround?

**Comment by ultraN** [comment]
快一年了还是没修复。。。

**Comment by kwatog** [comment]
I'm more concerned on the header. If it's a bit long, it does not display properly. It breaks mid-word. Adding the `overflow-wrap: break-word` and/or `word-wrap:break-word` do not work
