### ISSUE TITLE
[Bug Report] table表格中中含有tiptool插件 会出现样式混合、报错 

### ISSUE THREAD

**Issue by chaifu** [ElemeFE/element#3826]
### Element UI version
1.2.5

### OS/Browsers version
windows chrom

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/ygozf28j/](http://jsfiddle.net/ygozf28j/)

### Steps to reproduce
点击分页第二页
鼠标触发左边的带有tiptool的提示 图标，会出现样式乱，或者会出现页面报错

报错内容：
[Vue warn]: Error in watcher "showPopper"
(found in component )
warn @ vue.js?891f:523
run @ vue.js?891f:1745
flushSchedulerQueue @ vue.js?891f:1543
(anonymous) @ vue.js?891f:475
nextTickHandler @ vue.js?891f:424
vue.js?891f:437 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### What is Expected?
应该正常显示tiptool内容

### What is actually happening?
会报错或者会出现样式乱了

**Comment by QingWei-Li** [comment]
你的 `v-if` 应该写在 `el-tooltip` 上

**Comment by chlab** [comment]
Just stumbled over this problem as well. For non-Chinese speakers: this happens when your `el-tooltip` is wrapped in a container that has a `v-if`. Put the `v-if` on the `el-tooltip`.
