### ISSUE TITLE
[Feature Request] expose row index in table column

### ISSUE THREAD

**Issue by ShaneXie** [ElemeFE/element#3839]
### Existing Component
Yes

### Component Name
el-table, el-table-column

### Description
need get access to current row index in the column component, basicly i want to do is:
```
    <el-table :data="dataArray"
      <el-table-column v-for="(value, key) in dataArray[rowIndex]" :label="key"></el-table-column>
    </el-table>
```

**Comment by Leopoldthecoder** [comment]
We have no plan to support this.
