### ISSUE TITLE
[Bug Report] [Input Number] 手动修改v-model的值input显示值不能同步变化

### ISSUE THREAD

**Issue by EdenSpark** [ElemeFE/element#3841]
### Element UI version
1.2.5

### OS/Browsers version
Chrome 56

### Vue version
2.2.4

### Reproduction Link
[http://jsfiddle.net/w8zLdv3k/](http://jsfiddle.net/w8zLdv3k/)

### Steps to reproduce
watch v-model绑定值的变化，对值做一些处理，比如保留小数位数的处理时，然后将处理后的值重新赋给v-model绑定变量，重新赋的值不能反映到input的显示值上

### What is Expected?
希望能够正确同步显示

### What is actually happening?
input 显示的值不能随v-model的值变化

**Comment by QingWei-Li** [comment]
应该放在 nextTick 里吧？

**Comment by pengchongfu** [comment]
#3595 感觉和这个issue一样的问题。Input Number内部的value和curerntValue不同步。 @QingWei-Li
