### ISSUE TITLE
tree树形控件

### ISSUE THREAD

**Issue by fmshun** [ElemeFE/element#3844]
hello dear,能给tree树形控件加一个node-contextmenu事件吗,急需的,亲,还有table表格右键事件点击背景怎么不高亮呢

**Comment by fmshun** [comment]
hello dear,能给tree树形控件加一个node-contextmenu事件吗,急需的,亲,还有table表格右键事件点击背景怎么不高亮呢

**Comment by PLQin** [comment]
@fmshun 

建议参考: 
[ElementUi] 需要实现 `tree`组件上右键弹出菜单并且 `获得 tree node的id值` - Starch的回答 - SegmentFault
https://segmentfault.com/q/1010000012940760/a-1020000012955488
