### ISSUE TITLE
[Feature Request] tree中是否能设置手动展开某个树节点,手动设置current-node

### ISSUE THREAD

**Issue by BillionChen** [ElemeFE/element#3852]
### Existing Component
是

### Component Name
tree

### Description
场景:
在组织机构中搜索用户

搜索到用户后,再搜索用户所有上级部门,立即展开到该用户的节点并且选中用户

现在好像没有在单选模式下手动选中current-node的api,也没有手动展开某个节点的api

**Comment by BillionChen** [comment]
刚刚发现 
default-expanded-keys 
current-node-key
这两个值, 测试可以手动设置

**Comment by scq000** [comment]
设置了current-node-key 同时也设置了node-key， 发现并没有起作用，不知道是什么原因？

**Comment by 931596973** [comment]
感谢，学到了
