### ISSUE TITLE
[Bug Report] form表单BUG

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#3855]
### Element UI version
1.2.7

### OS/Browsers version
win7/谷歌浏览器

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/q1ykt7f4/](http://jsfiddle.net/q1ykt7f4/)

### Steps to reproduce
当form表单下只有一个input框的时候，选中input框，按回车键，会刷新整个页面

### What is Expected?
不能刷新页面

### What is actually happening?
会刷新整个页面

**Comment by pengchongfu** [comment]
链接贴错了。

**Comment by Liupeng8** [comment]
@pengchongfu  已更新了链接

**Comment by jikkai** [comment]
@Liupeng8 详见#3625
