### ISSUE TITLE
cascader做次级动态加载效果时只能做到第二级吗？

### ISSUE THREAD

**Issue by GloriaCHL** [ElemeFE/element#3860]
我用cascader组件做省市区三级联动，照着官方文档里的来做，只能做到市级动态加载，区县动态加载没出来，点到市级的时候选择就结束了。
行为：
第一次从省级点击选择，触发active-item-change事件，动态加载了市级数据，这步正常；
第二步点击市级数据，下拉框关闭，最后值只有省市，没有触发active-item-change事件，而是直接结束了选择。
请问cascader要做多级联动的动态加载需要怎么做？

**Comment by iceycc** [comment]
有解决方法吗
