### ISSUE TITLE
[Feature Request] tree动态设置defaultExpandAll和lazy属性

### ISSUE THREAD

**Issue by superpig** [ElemeFE/element#3861]
### Existing Component
是

### Component Name
tree

### Description
动态设置defaultExpandAll和lazy属性，它们的值可以随时变化，而不是只能初始化一次

**Comment by superpig** [comment]
现在的解决方法是通过访问$data直接修改：this.$refs.orgTree.$data.store.lazy = false;

**Comment by Leopoldthecoder** [comment]
无计划增加此 feature

**Comment by plusmancn** [comment]
有同样需求
