### ISSUE TITLE
Time Picker 时间选择器 文档报错

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#387]
### 文档报错
* 点击 任意时间点 的输入框，控制台有错误，报错的 url: [http://element.eleme.io/#/component/time-picker](http://element.eleme.io/#/component/time-picker)
* Datetime Picker 日期时间选择器，触发后右边有个莫名其妙的小图标(chrome 浏览器)
![image](https://cloud.githubusercontent.com/assets/10893176/19339599/e8eae95e-9156-11e6-80c1-8b255446ab33.png)
![image](https://cloud.githubusercontent.com/assets/10893176/19339773/ffaca5c8-9157-11e6-9bcc-d6c31d59b74b.png)

### 其他问题

* el-time-select 在v-model默认值为 '' ，动态修改model 的值后，placeholder 提示文字在 `safari` 中，没有消失

![image](https://cloud.githubusercontent.com/assets/10893176/19339740/bb24eda2-9157-11e6-94d5-0dfc2c0c0433.png)

**Comment by QingWei-Li** [comment]
1. 问题已经修复了 fixed in https://github.com/ElemeFE/element/pull/334
2. 可能是网络延迟导致字体文件没有加载正确
3. 可否给复现代码？这里只是用了一个 input 标签，placeholder 和 value 都是原生的

**Comment by ApolloRoad** [comment]
我也想用这个组件，一堆问题。。。

**Comment by isunkui** [comment]
@QingWei-Li  这个应该是 safari 的问题哈，我忘记去看样式了，示例如下，问题我关了哈
[https://jsfiddle.net/isunkui/sh1s4d3w/14/](https://jsfiddle.net/isunkui/sh1s4d3w/14/)
