### ISSUE TITLE
[Feature Request] Make the 'new ticket' link in the placeholder text work

### ISSUE THREAD

**Issue by dsl101** [ElemeFE/element#3872]
### Existing Component
No

### Component Name
none

### Description
When opening a new ticket, the placeholder text says go to this URL:

https://eleme-issue.surge.sh

but that then redirects to:

https://elementui.github.io/issue-generator/#/en-GB

which throws 2 console errors ("RangeError: Maximum call stack size exceeded" and "vue.esm.js:1452 TypeError: Cannot read property 'matched' of undefined"). The correct link appears to be:

https://elementui.github.io/issue-generator/#/en-US

I'm in the UK so perhaps it's a locale issue?

**Comment by Leopoldthecoder** [comment]
It's supposed to be fixed now. Could try again?

**Comment by dsl101** [comment]
Yes, it redirects me to the en-US page now, which is fine.

Thanks

David.
