### ISSUE TITLE
[Bug Report] Element-Datepicker Bug: Arrow functionality to toggle between months

### ISSUE THREAD

**Issue by robfr77** [ElemeFE/element#3873]
### Element UI version
1.2.7

### OS/Browsers version
Windows 10/ Chrome 57

### Vue version
2.2.1

### Reproduction Link
[http://codepen.io/robert77/pen/mWQPge](http://codepen.io/robert77/pen/mWQPge)

### Steps to reproduce
npm i --save-dev element-datepicker
vue-loader in wepback
import DatePicker from 'element-datepicker'
Vue.use(DatePicker);

### What is Expected?
DatePicker works as expected but arrows for switching between months have only part of their CSS but not JS functionality

### What is actually happening?
Updated the component locally (https://www.npmjs.com/package/element-datepicker) to recent commits on https://github.com/ElemeFE/element/tree/master/packages/date-picker but still having same bug

**Comment by Leopoldthecoder** [comment]
A working demo: https://jsfiddle.net/leopoldthecuber/6arc4c66/1/
Please note that you need to import two separate CSS files.

**Comment by robfr77** [comment]
Thank you. The component is also not applying locale settings applied thusly
```
import locale from 'element-ui/lib/locale/lang/en';
Vue.use(DatePicker, { locale });
```

**Comment by Leopoldthecoder** [comment]
Are you using the element-datepicker package or the element-ui package?

**Comment by robfr77** [comment]
I'm using the element-datepicker package and trying to set it up for English without bringing the whole UI library in.

**Comment by robfr77** [comment]
I tried the NormalModuleReplacementPlugin as mentioned in the docs, does this deserve a changed title? Hoping to avoid a manual script

**Comment by Leopoldthecoder** [comment]
You can do that with `vue-i18n`: https://jsfiddle.net/leopoldthecuber/6arc4c66/2/
