### ISSUE TITLE
[Bug Report] 关于嵌套Dialog的异常展示问题

### ISSUE THREAD

**Issue by luoyunjiao** [ElemeFE/element#3874]
### Element UI version
1.2.7

### OS/Browsers version
MacOS  Chrome 56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/luoyunjiao77/pj71jkyw/32/](https://jsfiddle.net/luoyunjiao77/pj71jkyw/32/)

### Steps to reproduce
1. 点击展示外层dialog的button
2. 点击展示内层dialog的button

### What is Expected?
内层dialog框能正常展示

### What is actually happening?
内层dialog框被遮罩覆盖

**Comment by Leopoldthecoder** [comment]
#3499
