### ISSUE TITLE
[Bug Report] Table组件当边框和斑马线（border,stripe）同时存在时，在火狐浏览器中border显示不出来

### ISSUE THREAD

**Issue by essencemike** [ElemeFE/element#3879]
### Element UI version
1.2.7

### OS/Browsers version
Ubuntu 14.04 LTS / Firefox 49.0

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/33/](https://jsfiddle.net/pj71jkyw/33/)

### Steps to reproduce
table组件同时设置border和stripe属性，有斑马线的行border显示不出来

### What is Expected?
当设置border和stripe属性时，斑马线和border同时显示出来

### What is actually happening?
当设置border和stripe属性时，border显示不全

**Comment by essencemike** [comment]
我目前的解决方案是：
```
td {
  background-clip: padding-box;
}
```
给td设置背景裁剪规则来解决FireFox的兼容性问题

**Comment by Leopoldthecoder** [comment]
好像 macOS 下的 FF 没问题。直接给我们提个 PR 吧。
