### ISSUE TITLE
时间日期组件问题很多啊。

### ISSUE THREAD

**Issue by ApolloRoad** [ElemeFE/element#388]
http://element.eleme.io/#/component/datetime-picker
![qq 20161013154209](https://cloud.githubusercontent.com/assets/5633780/19340481/a3fb4a46-915b-11e6-8740-28a4d2ddefc1.png)
左边的基本没反应错乱，右边的也乱，无法选择等。

话说我最想用的就是你们的这个时间日期组件了 ，非常漂亮。

**Comment by QingWei-Li** [comment]
问题已经修复了 fixed in #334
