### ISSUE TITLE
table组件动态调整列顺序时，有<template scope="scope"> 包含 子组件时 报错

### ISSUE THREAD

**Issue by hong1012** [ElemeFE/element#3882]
Element UI version

1.2.3

OS/Browsers version

chrome56

Vue version

2.1.4

使用方法：

  <template v-for="column  in memberSettingColumns" >
          <v-table-column v-if="column.show'   :prop="column.prop" :label="column.label"  >
          </v-table-column>
          <v-table-column v-else-if="column.show && column.prop=='deleted'"  :prop="column.prop" :label="column.label" >
            <template scope="scope">
              <v-switch :value="!scope.row.deleted" @change="changeStatus($event, scope.row)" >
              </v-switch>
            </template>
          </v-table-column>
</template>

报错信息：
动态调整table组件的列顺序，改变 memberSettingColumns时，报错如下：
![image](https://cloud.githubusercontent.com/assets/4018246/24490318/b1e3e3e8-1554-11e7-9d85-da78e3f5461d.png)

**Comment by peterchealse** [comment]
同错。。动态增减colume的时候 如果这个列内容有template 报错。

**Comment by ewfian** [comment]
最后解决了吗？ 好像template无法排序
