### ISSUE TITLE
[Feature Request] 期望日期范围选择控件支持选择月份范围

### ISSUE THREAD

**Issue by schwanncheung** [ElemeFE/element#3885]
### Existing Component
是

### Component Name
DatePicker

### Description
例如，想选择 2017-01至2017-03，当控件 type="daterange"时，能够通过相应的属性，可以让呈现的两个日历面板以 type="month" 的方式呈现。

**Comment by wsyWeb** [comment]
顶一个，太需要了

**Comment by NewRookies** [comment]
顶一个，太需要了

**Comment by topul** [comment]
mark, up

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
