### ISSUE TITLE
[Bug Report] Carousel 组件 initial-index设置失效

### ISSUE THREAD

**Issue by Reson-a** [ElemeFE/element#3886]
### Element UI version
1.2.7

### OS/Browsers version
win10/chrome 52

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/ro2uL277/](http://jsfiddle.net/ro2uL277/)

### Steps to reproduce
正常的轮播 绑定了一个动态的initial-index属性
实际项目中用自定义指令   inserted的时候requestFullScreen展示

### What is Expected?
设置完initial-index之后 
轮播应当以initial-index为当前页进行初始化
就算是初始化之后再滚到initail-index也勉强能够接受

### What is actually happening?
轮播以0的位置被初始化，然后向initial-index的位置滚 然后又强制回滚到0的位置

看了一下源码
在mounted时 $nextTick中设置了 initial-index
同时子组件created时 会debouce一个updateItem方法
在设置完initial-index之后，又执行了updateItem  items被重填，在watch中又强行setActiveItem(0) 然后就变成了上面的鬼样子

目前这么改了暂时应付当前需求……
```js
 watch: {
      items(val) {
        if (val.length > 0) {
          if (this.initialIndex < val.length && this.initialIndex >= 0) {
            this.setActiveItem(this.initialIndex);
          } else this.setActiveItem(0)
        }
      },
}
```

**Comment by CHU295** [comment]
...我看了一上午源码改了一上午都有问题，，果然太菜了。。可以了，谢谢

**Comment by evolutionjay** [comment]
同样失效， 顺路求
**Carousel Methods**
这些方法的demo， vue 文档没写， 网上也不知道怎么搜关键字， 直接一个demo看一眼真的能省很多事。 对于你们来说只是多写几段 demo， 对于学习的人就真的受益很大。

**Comment by Leopoldthecoder** [comment]
Fixed in #5334. Will release in 1.3.7
