### ISSUE TITLE
[Bug Report] Select组件中的change事件不执行

### ISSUE THREAD

**Issue by ummo** [ElemeFE/element#3887]
### Element UI version
1.2.7

### OS/Browsers version
windows7 / chrome 56

### Vue version
2.2.6

### Reproduction Link
不用链接

### Steps to reproduce
我看el-select源码发现handleOptionSelect函数中执行的是this.$emit('input', option.value)。抛出的事件是input，而按照文档应该是change事件，似乎datepicker也有此问题。

### What is Expected?
按照文档执行change事件的回调

### What is actually happening?
目前只能绑定input事件执行回调

**Comment by ummo** [comment]
我知道input事件是发给内部的input框的，然后通过input的value改变出发change事件，但是如果input的v-model绑定的是一个computed方法而不是data中的属性，这个change事件就不能出发，逼我只能接收input事件，这似乎不是很科学

**Comment by Leopoldthecoder** [comment]
一个变量如果是 computed 计算属性，则意味着它的值是完全由其他变量决定的，因此不要将一个计算属性绑定到表单元素上，这样有违「计算属性」的意义。
