### ISSUE TITLE
[Bug Report] table组件内置tooltip组件，结合transition组件报错

### ISSUE THREAD

**Issue by SirM2z** [ElemeFE/element#3888]
### Element UI version
1.2.7

### OS/Browsers version
windows 10 / chrome 56 64-bit

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/coolmrz/dn8x8azz/1/](https://jsfiddle.net/coolmrz/dn8x8azz/1/)

### Steps to reproduce
通过点击table组件中的“去测试2页面”切换路由   控制台就会报错

Uncaught TypeError: Cannot read property 'handleClosePopper' of undefined

调试了下，发现是1.2.7中table-body.js的220行

新添加的这句报错：this.$refs.tooltip.handleClosePopper();

而且现在table内置了tooltip组件，当项目按需引入element-ui时，只引入table组件，没有引入tooltip组件时，会报错，说tooltip组件未注册

这样处理会导致两个组件耦合比较严重吧

### What is Expected?
不报错

### What is actually happening?
报错

**Comment by leo-coco** [comment]
Same issue 

```
vue.common.js:560 [Vue warn]: Unknown custom element: <el-tooltip> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <TableBody>)
```

**Comment by bao2314483** [comment]
请问楼主问题解决了吗?我也出现这个问题

**Comment by SirM2z** [comment]
他们应该解决了，只不过还没发布新版（但为啥把issue关了）

你看看他的commit，应该是缺少声明tooltip组件了

**Comment by Leopoldthecoder** [comment]
等今天的版本吧

**Comment by SirM2z** [comment]
问题并没有解决啊

依然是上边的jsfiddle

版本已经是1.2.8
![](http://7xs9eo.com1.z0.glb.clouddn.com/3.gif)

**Comment by bao2314483** [comment]
问题官方知不知道这个BUG存在呢

**Comment by SirM2z** [comment]
你把代码发出来瞅瞅

**Comment by Leopoldthecoder** [comment]
好像不是每次都会出现，所以疏忽了。已经在 #4085 修复。

**Comment by bao2314483** [comment]
但是我每次跳转都不会报错,只要页面有table,按同级路由跳转就会报错,,我修复代码很简单,在前面if判断是否对象为空,是为空就不执行下去而已

**Comment by bao2314483** [comment]
下个版本能修复这个问题吗

**Comment by oopDaniel** [comment]
Menu-item在collapse模式下有相同的問題

**Comment by ouchsowhat** [comment]
对，按需引入Menu，在设置collapse为true时ElMenuItem也会报el-tooltip未注册的错误。

**Comment by breadadams** [comment]
I'm seeing the same error when trying to collapse an `el-menu` component, with components imported _on demand_. I've included the `Tooltip` component and declared it with the correct name, but still seeing the `Unknown custom element: <el-tooltip>` console error on collapse event

**Comment by xinde** [comment]
collapse为true时，点击el-menu,tooltips失效

**Comment by 641357534** [comment]
我也是el-menu tooltip失效
