### ISSUE TITLE
[Bug Report] tooltip 内部 的button disabled 时，tooltip 无法触发

### ISSUE THREAD

**Issue by Deguang** [ElemeFE/element#3894]
### Element UI version
1.2.3

### OS/Browsers version
macOS

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/2u3gqsub/](https://jsfiddle.net/2u3gqsub/)

### Steps to reproduce
el-button 增加 diabled true， tooltip 无法触发

### What is Expected?
内部 组件 disabled 时，能否不影响外部 的事件触发

### What is actually happening?
外部的 tooltip 不响应

**Comment by pengchongfu** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter On disabled form elements
火狐是支持的。。
