### ISSUE TITLE
[Bug Report] Table内嵌进Dialog中时，筛选下拉被遮挡

### ISSUE THREAD

**Issue by scott-leung** [ElemeFE/element#3896]
### Element UI version
1.2.7

### OS/Browsers version
MacOS 10.12.4/Chrome 56.0.2924.87 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ScottLeung/qq5zq3mk/5/](https://jsfiddle.net/ScottLeung/qq5zq3mk/5/)

### Steps to reproduce
1、打开dialog；
2、用标签筛选第一次后，关闭dialog；
3、再次打开dialog；
4、再次用标签筛选时z-index被盖住，问题重现。

### What is Expected?
无论多少次打开关闭dialog和多次筛选dialog中table的filter，均能正确地显示出dialog和table中的filter。

### What is actually happening?
第一次正常，之后就不行了。

**Comment by scott-leung** [comment]
怎么没人理我这个问题呢😢

**Comment by liyanlong** [comment]
确实会有这个问题.
目前定位的是 `el-table-filter` 的 `z-index` 没有递增， 而 `dialog` 的不断打开，  `z-index` 是会不断的递增的.

**Comment by scott-leung** [comment]
@liyanlong 那请问会在下个版本解决吗？

**Comment by liyanlong** [comment]
@scott-leung  这个有时间可以PR

**Comment by liyanlong** [comment]
@scott-leung v1.2.8 已经修复了这个问题

**Comment by scott-leung** [comment]
@liyanlong 好的，谢谢☺️
