### ISSUE TITLE
[Bug Report] DatePicker Model incorrect value. 

### ISSUE THREAD

**Issue by hunterway55** [ElemeFE/element#3897]
### Element UI version
1.2.7

### OS/Browsers version
OSX 10.11.6 Chrome 57.0

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/Hunterway55/pj71jkyw/34/](https://jsfiddle.net/Hunterway55/pj71jkyw/34/)

### Steps to reproduce
Clicking a date after the current date or any date in the future. Picking April 1st, the model shows 31 March? 

### What is Expected?
The value the date picker is the same as in the model? 

### What is actually happening?
The date picker is displaying the correct date in the date picker box. In the v-model the picker is bound to, the value when evaluated is the previous date?

**Comment by Leopoldthecoder** [comment]
#3814
