### ISSUE TITLE
[Feature Request] diaolog现在不能拖动，项目很多应用需要可拖动的对话框，或者新建一个组件，类似easyui里的window也可以

### ISSUE THREAD

**Issue by zslvue** [ElemeFE/element#3898]
### Existing Component
是

### Component Name
Dialog

### Description
diaolog现在不能拖动，项目很多应用需要可拖动的对话框，或者新建一个组件，类似easyui里的window也可以

**Comment by Leopoldthecoder** [comment]
无计划。
