### ISSUE TITLE
[Bug Report] 页面中有 dropdown 组件时，clickoutside 报错。

### ISSUE THREAD

**Issue by zhaozhe0831** [ElemeFE/element#3901]
### Element UI version
1.2.7

### OS/Browsers version
macOS / Chrome  56.0.2924.87

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
[dropdown 组件](http://element.eleme.io/#/zh-CN/component/dropdown)

启用开发者工具后，通过选取工具选中元素时，报错。

### What is Expected?
修复报错？

### What is actually happening?
待修复？

**Comment by Leopoldthecoder** [comment]
demo 无报错。

**Comment by zhaozhe0831** [comment]
[官网 链接](http://element.eleme.io/#/zh-CN/component/dropdown)
Before
![image](https://cloud.githubusercontent.com/assets/12945873/24535202/35557b8c-1605-11e7-83d3-11c9722f208c.png)
After
![image](https://cloud.githubusercontent.com/assets/12945873/24535213/41e0d07c-1605-11e7-800f-817e97d32196.png)

目测看是官网的 BUG

**Comment by zhaozhe0831** [comment]
在 select 组件中遇到了同样的问题。
[demo](https://jsfiddle.net/vo3h8vgd/)

@Leopoldthecoder 我觉是组件内部的问题。

截图上传不了，网不好。

**Comment by Leopoldthecoder** [comment]
Dropdown 的我这里重现了，Select 是选取哪个元素的时候会报错？

**Comment by baiyaaaaa** [comment]
我这里貌似没有重现

**Comment by zhaozhe0831** [comment]
@baiyaaaaa 先调出开发者工具，刷新页面，选中元素前不要操作页面中的元素，例如 click。
通过  ![image](https://cloud.githubusercontent.com/assets/12945873/25470862/c700efb0-2b56-11e7-9c33-3056e01b045f.png)  来选中 dom 元素。
出问题的点应该是在 clickOutside 上，目前来看不是组件的问题，因为选取任何元素都会报错。
![image](https://cloud.githubusercontent.com/assets/12945873/25470925/1c105054-2b57-11e7-8f8f-ebdd85b55859.png)

**Comment by rossroma** [comment]
我本地也会经常报这个错误，在两种操作下，报错的概率几乎是100%。
一是楼上描述的方法，使用开发工具中的指针选择dom时报错；
二是在项目中引入第三方地图组件，在点击地图时会触发报错。

**Comment by wheato** [comment]
我在项目中引入第三方地图组件，在点击地图时也会触发报错。

**Comment by romoo** [comment]
和 vue-amap 一起使用会，刷新页面，拖动地图会报错。

**Comment by Leopoldthecoder** [comment]
Now it's fixed.
