### ISSUE TITLE
[Bug Report] 页面中 dropdown 组件样式错乱。

### ISSUE THREAD

**Issue by zhaozhe0831** [ElemeFE/element#3902]
### Element UI version
1.2.7

### OS/Browsers version
macOS / Chrome  56.0.2924.87

### Vue version
2.2.6

### Reproduction Link
[demo 已修复](https://jsfiddle.net/3kwn3a23/)

### Steps to reproduce
官方例子，dropdown 不在一行上。

### What is Expected?
.el-button-group .el-button {
    /* float: left; */
    position: relative;
}
注释掉 float: left; 后不会出现这种情况了。

### What is actually happening?
待修复？

**Comment by Leopoldthecoder** [comment]
demo 地址不正确

**Comment by zhaozhe0831** [comment]
demo 已修复 @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
Fixed [here](https://github.com/ElemeFE/element/pull/4851/files#diff-e17a364bbf43a018f167fba79ac48d65R15)
