### ISSUE TITLE
[Feature Request] popover use arg to link button limited usage

### ISSUE THREAD

**Issue by biblesyme** [ElemeFE/element#3907]
### Existing Component
Yes

### Component Name
Popover

### Description
```html
<el-button v-popover:popover2>Click to activate</el-button>
<el-popover
  placement="right"
  title="Title"
  width="200"
  trigger="focus"
  content="this is content, this is content, this is content">
  <el-button slot="reference">Focus to activate</el-button>
</el-popover>
```

use `v-popover:popover2` directive arg to link the Popover make it's impossible to bind Popover dynamically. 

suggest change this way of binding. 
like what i used in my project below:
```javascript
Vue.directive('popoverWDS',{
  bind: function bind(el, binding, vnode) {
      vnode.context.$refs[binding.value][0].$refs.reference = el;
    }
})
```

**Comment by Leopoldthecoder** [comment]
Please elaborate your proposal.

**Comment by nt3478** [comment]
Having the same issue here.  I am using this within an el-table and v-popover loses it's association if the button is dynamically hidden/visible via v-if. 

<el-button v-popover:popover2 v-if="toggleCheck">Click to activate</el-button>

Is it possible to show the popover via @click="someCodetoShow(popover2)" or something similar?

**Comment by Leopoldthecoder** [comment]
@nt3478 yes you can: https://jsfiddle.net/97svreub/

@biblesyme please see if the above demo meets your need. If not, you can reopen this issue.
