### ISSUE TITLE
[Bug Report] NavMenu组件刷新后高亮显示当前状态不见

### ISSUE THREAD

**Issue by DullSky** [ElemeFE/element#3911]
### Element UI version
1.2.7

### OS/Browsers version
win10

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/8xrk1n9f/](https://jsfiddle.net/8xrk1n9f/)

### Steps to reproduce
刷新

### What is Expected?
当前的导航应该高亮

### What is actually happening?
没有高亮，官方vue-router的exact属性，在刷新后仍可定位当前路由的连接并高亮，比如/a/b那么拥有<router-link to="/" exact>连接</router-link>在刷新后应该依然拥有激活状态的标志（添加active-class）

**Comment by VaJoy** [comment]
遇到同样问题

**Comment by Centaur** [comment]
The reproduction link does not contain any ElementUI code

**Comment by baiyaaaaa** [comment]
menu item active state is control by your code instead of el-menu component itself.
