### ISSUE TITLE
[Bug Report] npm install 报错

### ISSUE THREAD

**Issue by blackdog1987** [ElemeFE/element#3913]
### Element UI version
1.2.7

### OS/Browsers version
macOS 10.12.5

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
npm install 报错
node v7.2.1
npm  v3.10.9

### What is Expected?
npm install执行完成 提示success

### What is actually happening?
错误日志：

错误日志：

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.1
npm ERR! npm v3.10.9
npm ERR! path /Users/xxx/git/element/node_modules/babel-core
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access '/Users/xxx/git/element/node_modules/babel-core'
npm ERR! enoent ENOENT: no such file or directory, access '/Users/xxx/git/element/node_modules/babel-core'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

os：mac os

**Comment by Leopoldthecoder** [comment]
你的操作步骤是？

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
