### ISSUE TITLE
[Bug Report] form-item在不同浏览器下高度不同

### ISSUE THREAD

**Issue by haoshuaiya** [ElemeFE/element#3916]
### Element UI version
1.2.7

### OS/Browsers version
win10/Chrome 56 /Firefox 51.0.1 

### Vue version
2.2.6

### Reproduction Link
http://element.eleme.io/#/zh-CN/component/form
### Steps to reproduce
你好，我在项目中发现使用el-form-item的时候，不同浏览器下面的el-form-item的高度不一致，火狐中的间距明显高了许多，导致观感不是很和谐(尤其是做登录框的时候)，同时，我的form也不方便进行定高处理。

### What is Expected?
el-form-item上下间距一致

### What is actually happening?
el-form-item在不同浏览器下间距不一致

**Comment by Leopoldthecoder** [comment]
贴一下截图。

**Comment by haoshuaiya** [comment]
@Leopoldthecoder  我的项目截图
![page](https://cloud.githubusercontent.com/assets/17921713/24536276/f5e46150-160b-11e7-981b-b170605597fa.png)
源码如下:
![image](https://cloud.githubusercontent.com/assets/17921713/24536315/2c9bff00-160c-11e7-9adc-0ccb7d10e730.png)
看了一下官网的form表单，也有这个问题。

**Comment by lincenying** [comment]
把 .el-input__inner 设置成 inline-block
