### ISSUE TITLE
el-table-column 多级表头 隐藏列时 会出现渲染出错 怎么解决?

### ISSUE THREAD

**Issue by DualWield** [ElemeFE/element#3917]
Element UI version

1.2.7

OS/Browsers version

macOS/chrome 版本 56.0.2924.87 (64-bit)

Vue version

2.2.6

Reproduction Link

https://jsfiddle.net/yedL9b8n/1/

Steps to reproduce

jsfiddle里有

What is Expected?

有一列每隔1s显示/隐藏

What is actually happening?

表格乱掉

**Comment by DualWield** [comment]
什么情况。。。我是用issue-generator生成的啊？

**Comment by Leopoldthecoder** [comment]
生成后请不要改动输入框中的内容。
