### ISSUE TITLE
[Bug Report] el-table-column 多级表头 隐藏列时 会出现渲染出错 怎么解决? 

### ISSUE THREAD

**Issue by DualWield** [ElemeFE/element#3919]
### Element UI version
1.2.7

### OS/Browsers version
macOS/chrome 版本 56.0.2924.87 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/yedL9b8n/1/](https://jsfiddle.net/yedL9b8n/1/)

### Steps to reproduce
jsfiddle里有

### What is Expected?
有一列每隔1s显示/隐藏

### What is actually happening?
表格乱掉

**Comment by noonehide** [comment]
我也有这问题，不过是我隐藏一列的时候，实际会隐藏两列。求解决

**Comment by qingwufengyang** [comment]
我也是这个问题，求解决

**Comment by DualWield** [comment]
估计这个bug不好修

**Comment by qingwufengyang** [comment]
那你不用了吗？

**Comment by DualWield** [comment]
@qingwufengyang 要用啊，也很急。。。 
@QingWei-Li 能看下么。。

**Comment by cuitianze** [comment]
也遇到这个bug

**Comment by cuitianze** [comment]
https://github.com/ElemeFE/element/issues/3360

**Comment by sweetXiaoyan** [comment]
我也遇到了这个问题，但是我的不是多表头，控制列的显示隐藏，表格会乱掉，请问有解决方法吗？

**Comment by julytian** [comment]
@sweetXiaoyan , 我参考 #4043 ,直接用v-if控制el-table，更新数据前置为false，更新数据后改成true

**Comment by Leopoldthecoder** [comment]
牵扯到动态显示隐藏的，建议给 `el-table-column` 或 `el-table` 加上 `key`：https://jsfiddle.net/yedL9b8n/13/ 。例子中的 `Math.random()` 只是为了说明效果，实际使用任何唯一性的值都行。

**Comment by MAZHIPENG** [comment]
我的问题和大家差不多 采用v-if之后  部分列的头部消失了 但是列的数据和另外一列共用了一个表头
采用了 Leopoldthecoder的建议 加上key之后问题解决了 谢谢  希望能帮助大家

**Comment by huandie2012** [comment]
我在el-table-column添加了key，但是还是会出现列的数据和另外一列共用了一个表头的问题

**Comment by 3172189228** [comment]
换句话说，需求是数据存在于row内，但在表格上面不显示出来，点击了这一行时，需要使用这一列数据
