### ISSUE TITLE
[Bug Report] table overflow-tooltip显示有问题

### ISSUE THREAD

**Issue by tonytangcn** [ElemeFE/element#3920]
### Element UI version
1.2.7

### OS/Browsers version
latest chrome

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/api/post/library/pure/](http://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
就用官网的例子，在jsfiddle上面，把address改得足够长，address列加上show-overflow-tooltip, 然后把jsFiddle右栏（SCSS那一栏) 往右边拖，直至address出现省略号, 一定要是address那一列多行出现省略号，然后鼠标浮上去，这时可以看到tooltip先在左下角闪烁一下再正常显示在table上面。所以，当tooltip长度达到浏览器客户区长度的时候，如果出现这样的显示错误，在左下角闪烁的一瞬间，浏览器会出现滚动条，然后归位后滚动条消失，假设table有很多行，某人用鼠标在address列上面浮动，看到的结果就是滚动条在浏览器上面跳一跳的，页面也是一跳一跳的。

### What is Expected?
what is expected? 

### What is actually happening?
 What is actually happening? stop asking me this stupid question again as I have already answered

**Comment by tonytangcn** [comment]
![tmp](https://cloud.githubusercontent.com/assets/25765865/24536808/b03e3398-160f-11e7-9f35-e120fcc0881e.png)

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/ElemeFE/element/pull/3883
