### ISSUE TITLE
[Bug Report] el-table 在fit=true，部分列未设置宽度情况下，锁定列样式错误

### ISSUE THREAD

**Issue by zhukaidi** [ElemeFE/element#3922]
### Element UI version
1.2.7

### OS/Browsers version
win10/chrome 57.0.2987.133 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/3ncysgxz/1/](http://jsfiddle.net/3ncysgxz/1/)

### Steps to reproduce
el-table 设置 fit = true
自动撑开的情况下，锁定列会出现样式错误

### What is Expected?
最后一个锁定列存在2个右边框，阴影错位。

### What is actually happening?
最后一个锁定列不会出现2个右边框，阴影不错位。
fit = false 时不会出现这个错误

**Comment by Leopoldthecoder** [comment]
手边没有 windows，请贴一下截图

**Comment by zhukaidi** [comment]
图片上传不了。。。
我上传了我的网盘
这是异常的情况:
http://pan.baidu.com/s/1jINt58y
后来发现当拖拽列宽度，使底部出现滚动条时，异常情况会消失
http://pan.baidu.com/s/1dForQmP

**Comment by furybean** [comment]
2.1.0 中已经无法重现：http://jsfiddle.net/3ncysgxz/2/

先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。
