### ISSUE TITLE
DateTimePicker 选择日期有误

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/element#3923]
Element-ui: 1.2.7
vue: 2.1.1
windows 10 / chrome 55

1.单击input框，弹出日期选择菜单
2.点击“>”进入到下一月份
3.然后随便点击一个日期，月份会自动 +1，比如我选择了4月5号，日期会跳到5月5号

重现链接：官网文档上的demo也有这个bug，http://element.eleme.io/#/zh-CN/component/datetime-picker

**Comment by Leopoldthecoder** [comment]
是 bug，重新打开了。

**Comment by joe223** [comment]
唔，我也遇到了这个问题，加油哇

**Comment by mqliutie** [comment]
@Leopoldthecoder datepicker 的 dateLimit 为什么会触发这么频繁啊。
```
data() {
    let _this = this;
    return {
        dateLimit: {
            disabledDate (time) {
                console.log(123);
                let date = new Date();
                return time.getTime() < date.getTime();
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/11795518/33115293-90e1d842-cf9b-11e7-9eac-a99a0f6b18f1.png)
