### ISSUE TITLE
[Bug Report] table动态生成的列，改变时只有第一个变动的列生效了

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#3928]
### Element UI version
1.2.6

### OS/Browsers version
win10 / chrome 56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/kvq9n96p/1/](https://jsfiddle.net/kvq9n96p/1/)

### Steps to reproduce
点击切换按钮,

### What is Expected?
表格改变为只有"姓名"、“地址”列，去掉“日期‘和”日期2“列

### What is actually happening?
只去掉了”日期“列

**Comment by schwann168** [comment]
请问这个问题已经在修复了吗？这边也刚发现这个问题，或者有没有办法先临时修复的方案？

**Comment by windzxa** [comment]
+1

**Comment by Yuliang-Lee** [comment]
1.2.8以上的版本已经解决了
