### ISSUE TITLE
[Feature Request] table表头中是否可以增加使用slot自定义内容呢

### ISSUE THREAD

**Issue by Rranran** [ElemeFE/element#3929]
### Existing Component
是

### Component Name
Table

### Description
如题 table表头中是否可以增加使用slot自定义内容呢

**Comment by QingWei-Li** [comment]
![image](https://cloud.githubusercontent.com/assets/7565692/24544166/e0a8dc70-1634-11e7-9712-e317d5e4f1a5.png)
