### ISSUE TITLE
表格的show-tooltip-when-overflow功能似乎失效？

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#394]
直接看官网Demo，之前看的时候还是可以的，现在没有`tooltip`了
![overflow](https://cloud.githubusercontent.com/assets/7945757/19342708/83150542-9165-11e6-91ff-2daba9339c2b.png)
是不是因为这次重构`popup`引起的？

**Comment by Leopoldthecoder** [comment]
fixed in #395
