### ISSUE TITLE
[Feature Request] Add ability to close all Messages

### ISSUE THREAD

**Issue by bholz** [ElemeFE/element#3941]
### Existing Component
Yes

### Component Name
Message

### Description
It would be nice to have the ability to close all existing Messages. If you show a message and then something triggers another, more important message to be shown, currently both are shown and will overlap. In most cases you would want to clear out any existing messages and only show the most important one.

**Comment by BigChief45** [comment]
Since this issue was fixed in #3966, I think it can be closed now.

**Comment by edum18** [comment]
To newcomers: you can now call `this.$notify.closeAll();`  to close all messages.
