### ISSUE TITLE
[Bug Report] 表格中无法禁止tooltip，show-overflow-tooltip设置为false也无效

### ISSUE THREAD

**Issue by MrYuJ** [ElemeFE/element#3943]
### Element UI version
1.2.7

### OS/Browsers version
chrome 版本 57.0.2987.133 (64-bit)

### Vue version
2.1.6

### Reproduction Link
[https://jsfiddle.net/yohojf6n/](https://jsfiddle.net/yohojf6n/)

### Steps to reproduce
因为用到表格嵌表单控件，更新了最新版本就有tooltip出来，而且禁止不到
![1491014712 1](https://cloud.githubusercontent.com/assets/12628933/24574695/3c076ed0-16c9-11e7-99ea-727988ce0ba2.jpg)

### What is Expected?
因为文档中默认show-overflow-tooltip就是false，希望没设置为true时tooltip不显示

### What is actually happening?
表格中无法禁止tooltip，show-overflow-tooltip设置为false也无效

**Comment by Leopoldthecoder** [comment]
Fixed in #3883
