### ISSUE TITLE
[Bug Report] DateTimePicker 组件日期选择错误

### ISSUE THREAD

**Issue by istobran** [ElemeFE/element#3945]
### Element UI version
1.2.7

### OS/Browsers version
macOS Sierra 10.12.3/Chrome 57.0.2987.110

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/BangZ/shka5rxj/1/](https://jsfiddle.net/BangZ/shka5rxj/1/)

### Steps to reproduce
1、选中2017年3月31日

2、点击旁边处于灰色状态的 4 月 1 日

![93ce0b0a-5f5b-47c1-91c2-b5ad94508001](https://cloud.githubusercontent.com/assets/7479006/24575122/2673d6b0-16d0-11e7-9a6e-2e1ab3a14129.png)

### What is Expected?
选中的应该是2017年4月1日

### What is actually happening?
选中的是2017年5月1日

**Comment by Leopoldthecoder** [comment]
Duplicate of #3923, fixed in #3935
