### ISSUE TITLE
[Feature Request] Form验证时如果fields为空，调用validate后立刻返回callback

### ISSUE THREAD

**Issue by sunlei33** [ElemeFE/element#3947]
### Existing Component
是

### Component Name
Form

### Description
场景：通过v-if实现的动态的Form，共享同一个submit函数，如果其中一个情况下fields为空，则调用validate不会返回，submit不能得到执行，添加PR[#3944](https://github.com/ElemeFE/element/pull/3944)

期待：Form验证时如果fields为空，调用validate立刻返回callback

P.S. npm run dist做的代码格式检查和travis的配置似乎不同，例如行尾空格，本地通过但travis不能通过，不知能否统一

**Comment by baiyaaaaa** [comment]
merged
