### ISSUE TITLE
[Bug Report] el-dialog中存在checkbox或select，点击checkbox或select，对话框会出现晃动

### ISSUE THREAD

**Issue by zhukaidi** [ElemeFE/element#3949]
### Element UI version
1.2.7

### OS/Browsers version
WIN10/57.0.2987.133 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/sqghggak/](http://jsfiddle.net/sqghggak/)

### Steps to reproduce
http://jsfiddle.net/k47jocdv/

打开对话框
点击对话框中的checkbox或select
观察对话框（标题处会比较明显）出现晃动

在同事mac电脑的chrome同样出现此问题
发现对话框宽度越大，晃动越明显

### What is Expected?
对话框不应该出现晃动情况

### What is actually happening?
对话框出现晃动情况

**Comment by PerseveranceZ** [comment]
+1 我也是这种情况 闪动的还是很明显 仔细看 头晕

**Comment by Leopoldthecoder** [comment]
Duplicate of #2461

**Comment by aaabinbin** [comment]
好像加入一些插件（插件里面也有checkbox或radio）会导致界面一直模糊
