### ISSUE TITLE
[Bug Report] el-upload绑定file-list，并支设置:multiple="true"的情况下，无法获取每个文件上传成功的response

### ISSUE THREAD

**Issue by akumatus** [ElemeFE/element#3954]
### Element UI version
1.2.7

### OS/Browsers version
chrome

### Vue version
2.2.6

### Reproduction Link
[https://elementui.github.io/](https://elementui.github.io/)

### Steps to reproduce
el-upload绑定file-list，并支设置:multiple="true"，上传多个文件。

### What is Expected?
“on-success”事件能被多次触发，每一次上传的response都能够截获。

### What is actually happening?
“on-success”事件只触发了一次，只能截获最后一次上传成功的response。
但对于未绑定file-list的情况下，“on-success”事件能被多次触发，每一次上传的response都能够截获。

**Comment by Leopoldthecoder** [comment]
请给 demo，我本地试了一下是可以的。

**Comment by akumatus** [comment]
非常抱歉，我check了一下发现是因为我改动了filelist的值的原因。

**Comment by MrJoeWhite** [comment]
请问如果业务需要改动filelist，怎么解决这个问题

**Comment by jiebaibai** [comment]
同问，业务需要改动filelist，怎么解决？

**Comment by Rainpia** [comment]
same problem. just use different value, can fix it temporarily.

**Comment by Rainpia** [comment]
seem like file-list value can not change, must be static value.

**Comment by yszzu1** [comment]
![image](https://user-images.githubusercontent.com/13514547/69849301-425e1a80-12b7-11ea-9377-c61b8ebcf1f3.png)
use two <el-upload> element
