### ISSUE TITLE
Element 2.0 版本预览

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#3956]
Element 将于今晚发布 2.0 版本，现在为大家介绍它的新特性。

## 青春版主题
自发布以来，Element 官方只提供了一套主题：theme-default。2.0 版会包含第二套官方主题 theme-youth。我们在 theme-default 的基础上调整了配色、字体大小和内边距，使 UI 充满了青春气息：

![image](https://cloud.githubusercontent.com/assets/10095631/24576966/d8a06390-16f7-11e7-82fd-46f1aa8bd7ec.png)
> 原版 Element

![image](https://cloud.githubusercontent.com/assets/10095631/24576952/7932459a-16f7-11e7-8dae-56fd339d0e3e.png)
> 青春版 Element

## 3D 模式
我们为 2.0 版中的所有组件都添加了 3D 模式，通过属性 `shake-it` 即可打开：

```html
<el-table :data="data" shake-it>
...
</el-table>
```

开启 3D 模式后，组件会随着鼠标的移动进行 3D 旋转，整个页面会随之变得动感起来：
![untitled](https://cloud.githubusercontent.com/assets/10095631/24577049/3ad76a08-16f9-11e7-9ee5-129da174bada.gif)

## 非兼容性更新
Element 2.0 将不再支持 Vue 2.x，相反，它将全面支持 Vue 1.x。因此，如果你使用的是 Vue 2.x，请使用 Element 1.x；如果你使用的是 Vue 1.x，请使用 Element 2.x。

今晚 Element 2.0 见！

**Comment by baiyaaaaa** [comment]
！！！！！！！！！！！！！！！！！！！！！！！！好赞

**Comment by gzlboy** [comment]
很困惑，为何新版反而不支持vue2.x？

**Comment by istobran** [comment]
Element 2.0 将不再支持 Vue 2.x？？？？

**Comment by MrYuJ** [comment]
感觉是愚人节版本

**Comment by gzlboy** [comment]
3D模式虽然很酷，但建议慎用，各种组件是为了业务需要的添加的，比如表格用于分析数据，加入3D模式，晃动会让人注意力分散甚至没法集中，我是没法接受在处理业务的时候其他元素干扰我的注意力的

**Comment by gzlboy** [comment]
@MrYuJ 听你这么一说，感觉被骗了哈哈

**Comment by pengchongfu** [comment]
3d效果满分💯

**Comment by jikkai** [comment]
Aha! 🌚

**Comment by cddsgtc** [comment]
作甚？

**Comment by SirM2z** [comment]
怎么感觉是假的

**Comment by istobran** [comment]
> 感觉是愚人节版本

@MrYuJ  原来如此🌚

**Comment by AnyGong** [comment]
。。。套路太多，防不胜防呀。。。 🌚

**Comment by Leopoldthecoder** [comment]
各位愚人节快乐！

澄清一下：
- 关于主题：虽然「青春版」只是一个玩笑，但是也许在未来的某个版本中，你会发现除 theme-default 之外的第二套主题
- 关于 3D 模式：永远也不会发生
- 关于版本兼容：其实除了 Vue 2.0 外，饿了么的另一个前端团队已经做出了 Element 的 React 实现：https://github.com/eleme/element-react
