### ISSUE TITLE
Element 2.0 Preview

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#3957]
Element 2.0 will be released tonight. Let's now take a look at its new content.

## A younger Element
Since its first release, Element has only one CSS theme: theme-default. With 2.0, it will ship with a brand new theme: theme-youth. We changed the color, font size and padding of theme-default to give you this awesome younger-looking Element:

![image](https://cloud.githubusercontent.com/assets/10095631/24576966/d8a06390-16f7-11e7-82fd-46f1aa8bd7ec.png)
> original Element

![image](https://cloud.githubusercontent.com/assets/10095631/24576952/7932459a-16f7-11e7-8dae-56fd339d0e3e.png)
> younger Element

## 3D mode
We implemented 3D mode for every component in version 2.0. To open it, just add a `shake-it` attribute:

```html
<el-table :data="data" shake-it>
...
</el-table>
```

Once 3D mode is turned on, components will rotate as your mouse moves over them, and the whole page will look more dynamic:
![untitled](https://cloud.githubusercontent.com/assets/10095631/24577049/3ad76a08-16f9-11e7-9ee5-129da174bada.gif)

## Breaking change
Element 2.0 no longer supports Vue 2.x, and it will support Vue 1.x instead. So, if you are using Vue 2.x, please download Element 1.x. If you are using Vue 1.x, please download Element 2.x.

We'll see you tonight in Element 2.0!

**Comment by baiyaaaaa** [comment]
Ohhhhhhhhhhhhhhhh, is amazing~!

**Comment by SuperAL** [comment]
> Element 2.0 no longer supports Vue 2.x, and it will support Vue 1.x instead. So, if you are using Vue 2.x, please download Element 1.x. If you are using Vue 1.x, please download Element 2.x.

I guess I won't need Element 2.0 ……

**Comment by Ca-aC** [comment]
> Element 2.0 no longer supports Vue 2.x, and it will support Vue 1.x instead. So, if you are using Vue 2.x, please download Element 1.x. If you are using Vue 1.x, please download Element 2.x.

no support ever or not just yet?

**Comment by satotakumi** [comment]
This aprilfool's joke cracks me up! 😂  😂  😂  😂  😂  😂  😂  😂  😂  😂

**Comment by Ca-aC** [comment]
Got April fooled:)

**Comment by Leopoldthecoder** [comment]
Hope you enjoy our April Fool's joke!

Just to clarify:
- Theme：Although `theme-younger` is just a joke, you may find another official theme in a feature version
- 3D Mode：It's never gonna happen
- Compatibility：In fact, besides Vue 2.0, another front-end team of our company has implemented Element for React: https://github.com/eleme/element-react
