### ISSUE TITLE
[Bug Report] Table 操作列绑定a标签的href出错

### ISSUE THREAD

**Issue by hjlfmy** [ElemeFE/element#3959]
![Uploading QQ截图20170401172443.png…]()

### Element UI version
1.2.7

### OS/Browsers version
window10

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/wj2hjmhb/1/](https://jsfiddle.net/wj2hjmhb/1/)

### Steps to reproduce
把编辑那里代码改为： <a :href="{{scope.row.name}}">下载</a>，就能重现错误了

### What is Expected?
修复

### What is actually happening?
修复

链接就是官网表格的固定列例子的在线运行按钮，本来想传图片，但是无法上传……

**Comment by Leopoldthecoder** [comment]
demo 链接有误

**Comment by hjlfmy** [comment]
已经更新了链接地址

**Comment by Leopoldthecoder** [comment]
没有 `:href={{ scope.row.name}}` 这种写法，控制台已经报错了。正确写法是 `:href="scope.row.name"`
