### ISSUE TITLE
Message在IE9下报无法获取属性toLowerCase的值，对象为null或未定义

### ISSUE THREAD

**Issue by wgq837051** [ElemeFE/element#396]
很奇怪的一个问题，Message在IE9下报无法获取属性toLowerCase的值，对象为null或未定义，源码中都没有用到toLowerCase，不知怎么发生的。

**Comment by Leopoldthecoder** [comment]
升级至 rc.6 即可。

**Comment by wgq837051** [comment]
我是下载最新的代码，在vue-cli基础上，把项目转起来了，开发指南都能打开，在IE9下都除了message不能运行，其他组件都OK，message的代码肯定是最新的，是不是打包的地方有什么特殊的设置呀。
