### ISSUE TITLE
[Bug Report] el-menu的mode改变，mouseenter事件失效。

### ISSUE THREAD

**Issue by cddsgtc** [ElemeFE/element#3960]
### Element UI version
1.2.7

### OS/Browsers version
win10/ chrome v59

### Vue version
2.2.0

### Reproduction Link
[https://jsfiddle.net/FarmerZ/jdobm749/](https://jsfiddle.net/FarmerZ/jdobm749/1/)

### Steps to reproduce
点击按钮即可看到

### What is Expected?
希望都可以恢复不同mode导航各自独立的本来效果

### What is actually happening?
其次，无论是把mode初始值设置成’vertical'还是'horizontal'，在动态改编成别的都会出现错误。
具体表现是：
1. vertical  --> horizontal ,mouseenter事件失效，而且会出现允许多个子菜单同时存在情况。
![a](https://cloud.githubusercontent.com/assets/16315661/24577550/5e941f82-1702-11e7-82e5-9a1c1207f9be.jpg)

2. horizontal ---> vertical ，vertical导航会继承 horizontal的mouseenter事件等。
![b](https://cloud.githubusercontent.com/assets/16315661/24577551/62fb48f2-1702-11e7-9d5b-2e1697bd029b.jpg)

**Comment by Leopoldthecoder** [comment]
这种还是用 v-if 做切换吧，同一个 el-menu 要切换的话，内部确实不好处理。

**Comment by cddsgtc** [comment]
@Leopoldthecoder 
我本来是那么做的，但是看到angular是一个模板做的两个效果。
你能不能在el-vue模板里做个计算属性，判断本来的mode值。，把二者方法本来就放进去，这样就不会导致单一模板渲染而忽视另外的效果。

**Comment by cddsgtc** [comment]
@Leopoldthecoder 
已解决，用一个key属性就可以了。绑定一个动态的可以。
重现地址：[https://jsfiddle.net/FarmerZ/jdobm749/2/](https://jsfiddle.net/FarmerZ/jdobm749/2/)

**Comment by Leopoldthecoder** [comment]
棒
