### ISSUE TITLE
[Bug Report] 在有fixed的table里面，自定义列模板el-select，v-model绑定row里面的内容时，change事件触发多次

### ISSUE THREAD

**Issue by taoyingqi** [ElemeFE/element#3965]
### Element UI version
1.2.7

### OS/Browsers version
chrome

### Vue version
2.2.6

### Reproduction Link
[https://github.com/taoyingqi/element-demo.git](https://github.com/taoyingqi/element-demo.git)

### Steps to reproduce
![image](http://static.ixzsenior.com/imgs/logo/201704/20170401211350013.png)

操作后，连续触发3次change事件
![image](http://static.ixzsenior.com/imgs/logo/201704/20170401211331013.png)

使用vue devtools查看，发现这里有3个tablebody，去掉两个el-table-column上的fixed，就只触发一次change事件
![image](http://static.ixzsenior.com/imgs/logo/201704/20170401211414014.png)

### What is Expected?
操作后只执行一次change事件

### What is actually happening?
操作后执行多次change事件，受el-table-column上的fixed的影响

**Comment by kbqncf** [comment]
这个我也碰到了
version 1.2.5

暂时避免只能把el-table-column上的fixed去掉

**Comment by Leopoldthecoder** [comment]
目前 Table 的实现无法避免这个问题，只能由用户去想办法 workaround 了。

**Comment by baijunjie** [comment]
无法避免？!-.-

**Comment by grassmu** [comment]
同遇到这个问题，官方有修复这个问题吗？
