### ISSUE TITLE
关于loading的bug

### ISSUE THREAD

**Issue by wilsonhxd1986** [ElemeFE/element#397]
如果页面有滚动条，在使用loading的时候会发生浏览器滚动条消失的bug,测试的浏览器为360

**Comment by Leopoldthecoder** [comment]
不是 bug。大多数情况下，在 loading 出现的时候，应该是阻止用户行为的。如果确实希望在 loading 时允许用户继续滚动页面，我们这边可以加一个开关。

**Comment by furybean** [comment]
@Leopoldthecoder 如果是 fixed，阻止滚动条挺奇怪的。

**Comment by Leopoldthecoder** [comment]
updated in #405
