### ISSUE TITLE
[Bug Report] RadioGroup 改变fill之后 :hover 和 box-shadow的颜色没有变

### ISSUE THREAD

**Issue by SnailSword** [ElemeFE/element#3978]
### Element UI version
1.2.4

### OS/Browsers version
win10 / chrome 56.0.2924.87

### Vue version
2.1.8

### Reproduction Link
[http://jsfiddle.net/ah0vnk23/](http://jsfiddle.net/ah0vnk23/)

### Steps to reproduce
1. 在页面里加入RadioGroup组件
2. 改变fill值

### What is Expected?
未激活状态的按键 :hover 和 激活状态的box-shadow颜色与新设置的值统一。

### What is actually happening?
未激活状态的按键 :hover 和 box-shadow颜色一直是默认的#20a0ff。
![image](https://cloud.githubusercontent.com/assets/19756301/24621790/5bef4458-18d5-11e7-8546-73f37c4bb52d.png)

**Comment by pengchongfu** [comment]
未激活状态的按键 :hover 时的颜色不应该与新设置的值统一吧，fill设置的是背景色 @SnailSword

**Comment by SnailSword** [comment]
个人认为fill值与#20a0ff这个值放一起不太协调的话，未激活状态的按键 :hover 时的颜色与fill值统一看起来好一些~
如果不统一的话，建议默认颜色:hover颜色换成中性一些的颜色。

**Comment by pengchongfu** [comment]
@SnailSword hover的颜色不怎么方便改。。可能得由官方来处理一下
