### ISSUE TITLE
[Bug Report] table表格第一列有section列之后，就出现tooltip异常，新升级版本导致。

### ISSUE THREAD

**Issue by AnyGong** [ElemeFE/element#3979]
### Element UI version
1.2.7

### OS/Browsers version
macOs Sierra / chrome56.0.2924.87 (64-bit)

### Vue version
2.2.2

### Reproduction Link
[http://jsfiddle.net/ogzhdL05/](http://jsfiddle.net/ogzhdL05/)

### Steps to reproduce
鼠标放在第一列的checkbox上，就会出现空的tooltip。现在我的所有线上项目都酱紫了，只能降级了。

### What is Expected?
没有任何的tooltip，木有任何反应。

### What is actually happening?
所有只要第一列带有checkbox，鼠标经过每一行的checkbox，就在上方出现了空的tooltip。

**Comment by Leopoldthecoder** [comment]
已在 #3883 中修复，随下个版本发布。抱歉。

**Comment by AnyGong** [comment]
感谢假日中的回复。辛苦了，给@element group点赞！
