### ISSUE TITLE
[Bug Report] [PR] remove unnecessary declaration 

### ISSUE THREAD

**Issue by nicholaslee119** [ElemeFE/element#3981]
### Element UI version
1.2.7

### OS/Browsers version
Mac

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/element/pull/3980](https://github.com/ElemeFE/element/pull/3980)

### Steps to reproduce
Unit Test

### What is Expected?
Merge

### What is actually happening?
PR

**Comment by Leopoldthecoder** [comment]
Please don't open an issue for things like this.
