### ISSUE TITLE
[Feature Request] Editable table rows

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#3989]
### Existing Component
Yes

### Component Name
el-table

### Description
Being able to edit each individual cell in a row inside a table would be useful.

I've inserted `contenteditable="true"` inside `el-table` tags, but this makes the *entire* table editable (even the column headings), and this isn't exactly what I want.

It would be nice if there was some way to target specific columns that you want users to be allowed to edit.

**Comment by liril-net** [comment]
In my opinion, `table` is used for display data, so it is a better idea to change data outside of table instead of editing `data-view` in table.

**Comment by pangniur** [comment]
我也希望有单元格编辑功能，很多用户应该都需要这个功能。

**Comment by Leopoldthecoder** [comment]
It can be done: https://jsfiddle.net/8329p946/

**Comment by pangniur** [comment]
不够美观啊  不能点击一下输入么 还需要点击按钮输入 ？

**Comment by liril-net** [comment]
@pangniur  这只是个 demo，你可以根据相关逻辑自己来实现你要的功能。

**Comment by Leopoldthecoder** [comment]
@pangniur 你给 span 绑定点击事件不就行了么……

**Comment by HungryBird** [comment]
谁有点击单元格编辑的demo来一个
不要整行的
