### ISSUE TITLE
Dropdown 下拉菜单跟 示例中不一样

### ISSUE THREAD

**Issue by liuzhibin123** [ElemeFE/element#399]
Dropdown 下拉菜单跟 示例中不一样 我是直接把示例中的代码COPY到我的vue组件模板中 如下：
`<template>
	<div>
		<el-dropdown>
  <span class="el-dropdown-link">
    下拉菜单<i class="el-icon-caret-bottom el-icon-right"></i>
  </span>
  <el-dropdown-menu slot="dropdown">
    <el-dropdown-item>黄金糕</el-dropdown-item>
    <el-dropdown-item>狮子头</el-dropdown-item>
    <el-dropdown-item>螺蛳粉</el-dropdown-item>
    <el-dropdown-item>双皮奶</el-dropdown-item>
    <el-dropdown-item>蚵仔煎</el-dropdown-item>
  </el-dropdown-menu>
</el-dropdown>
	</div>
</template>`
出现的效果却是这样
![koyrf_xgw pzi7l9 e z h](https://cloud.githubusercontent.com/assets/20216011/19344311/44e4beb4-916c-11e6-946b-4964bf81f492.png)
![3tx 50 0aa6 1jo razk2j](https://cloud.githubusercontent.com/assets/20216011/19344359/7240af8a-916c-11e6-8bdd-aa3d58568af6.png)

**Comment by erguotou520** [comment]
注意查看下`element-ui`的版本，rc6的时候重构过一次，建议升级下`element-ui`

**Comment by liuzhibin123** [comment]
我是这样的npm install element-ui@next -S  看了下是rc.5 请问怎么升级到 你说的rc6？
 最新版本是多少？

**Comment by baiyaaaaa** [comment]
rc.7

**Comment by erguotou520** [comment]
最新rc7，使用`npm update`更新

**Comment by liuzhibin123** [comment]
npm update element-ui@next 和npm update element-ui 2个都试过 没用无法更新

**Comment by liuzhibin123** [comment]
不好意思 麻烦你了 是我电脑问题  刚重新弄了一次前一个命令又用了
