### ISSUE TITLE
[Feature Request] 分页功能增加跳转按钮

### ISSUE THREAD

**Issue by Benjamin8911** [ElemeFE/element#3999]
### Existing Component
是

### Component Name
Pagination

### Description
能否在分页功能里，新增一个输入页码后可以点击的跳转按钮，当前组件操作实现输入页码跳转是通过回车操作，用户体验不是很好。希望团队能考虑增加分页跳转按钮该功能。谢谢~~

**Comment by tbphp** [comment]
既然输入框需要键盘输入，那么回车不是更方便么？个人感觉回车的用户体验是很好的？

**Comment by lurenhtml5** [comment]
现在的做法就已经很好了，感觉跳转按钮有点多余，个人感觉

**Comment by baiyaaaaa** [comment]
这不是一个便捷的交互方式，应该不会考虑这个功能。谢谢
