### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by quqiufeng** [ElemeFE/element#4]
[cooking] - 插件不存在，自动下载插件: saladcss

[cooking] - 安装插件: saladcss
module.js:327
    throw err;
    ^

Error: Cannot find module '/root/.cooking/node_modules/caniuse-api/generator.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
/root/.cooking
└── postcss-loader@0.9.1  extraneous

**Comment by QingWei-Li** [comment]
请删掉 root/.cooking 目录后重试 应该是权限问题，删掉重新启动

**Comment by quqiufeng** [comment]
没有解决

**Comment by quqiufeng** [comment]
node v4.5.0
npm 3.10.6
git clone git clone https://github.com/ElemeFE/element
cd element
npm run dev

/root/.cooking 目录已经删除

还是报以上错误

**Comment by zhouxinyong** [comment]
```
rm -f node_modules/
sudo npm i
npm run dev
```
这个是成功的，我自己测了。（首先全局安装cooking）

**Comment by tomoyuen** [comment]
windows上解析依赖可能有问题，我通过npm install的时候，makefile执行报错，提示模块找不到，然后通过cnpm install wind-dom throttle-debounce async-validator -D，之后cooking build成功，然后在npm run dev时又报错，提示 `Module build failed: Error: ENOENT: no such file or directory, open 'D:\my\element\packages\dialog\node_modules\vue-popup\lib\popup.css`错误，手动进入目录之后，cnpm install，运行成功

**Comment by quqiufeng** [comment]
都没有用?  难道是最新版本的npm的问题?

**Comment by quqiufeng** [comment]
npm run dev
报错
webpack: wait until bundle finished: /
Child scripts/cooking.demo.js:
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/form/src/form-item.vue
    Module not found: Error: Cannot resolve module 'async-validator' in /home/quqiufeng/element/packages/form/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/form/src/form-item.vue 5:22-48
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/select/src/select.vue
    Module not found: Error: Cannot resolve module 'throttle-debounce/debounce' in /home/quqiufeng/element/packages/select/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/select/src/select.vue 21:16-53
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue
    Module not found: Error: Cannot resolve module 'throttle-debounce/throttle' in /home/quqiufeng/element/packages/table/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 7:16-53
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue
    Module not found: Error: Cannot resolve module 'throttle-debounce/debounce' in /home/quqiufeng/element/packages/table/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 11:16-53
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/input-number/src/input-number.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/event' in /home/quqiufeng/element/packages/input-number/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/input-number/src/input-number.vue 9:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/popover/src/main.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/event' in /home/quqiufeng/element/packages/popover/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/popover/src/main.vue 13:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/slider/src/main.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/style' in /home/quqiufeng/element/packages/slider/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/slider/src/main.vue 13:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/date-picker/src/basic/date-table.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/class' in /home/quqiufeng/element/packages/date-picker/src/basic
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/date-picker/src/basic/date-table.vue 7:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/css-loader!../.cooking/~/postcss-loader!./packages/theme-default/src/index.css
    Module build failed: Error: ENOENT: no such file or directory, open '/home/quqiufeng/element/packages/dialog/node_modules/vue-popup/lib/popup.css'
        at Error (native)
    From previous event:
        at Object.readFile (/home/quqiufeng/.cooking/node_modules/fs-promise/index.js:34:12)
        at /home/quqiufeng/.cooking/node_modules/saladcss-partial-import/index.js:106:14
        at run (/home/quqiufeng/.cooking/node_modules/core-js/modules/es6.promise.js:87:22)
        at /home/quqiufeng/.cooking/node_modules/core-js/modules/es6.promise.js:100:28
        at flush (/home/quqiufeng/.cooking/node_modules/core-js/modules/_microtask.js:18:9)
        at nextTickCallbackWith0Args (node.js:420:9)
        at process._tickCallback (node.js:349:13)
     @ ./packages/theme-default/src/index.css 4:14-191 13:2-17:4 14:20-197
    Child html-webpack-plugin for "index.html":
        
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack: wait until bundle finished: /favicon.ico
Child scripts/cooking.demo.js:
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/input-number/src/input-number.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/event' in /home/quqiufeng/element/packages/input-number/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/input-number/src/input-number.vue 9:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/select/src/select.vue
    Module not found: Error: Cannot resolve module 'throttle-debounce/debounce' in /home/quqiufeng/element/packages/select/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/select/src/select.vue 21:16-53
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue
    Module not found: Error: Cannot resolve module 'throttle-debounce/throttle' in /home/quqiufeng/element/packages/table/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 7:16-53
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue
    Module not found: Error: Cannot resolve module 'throttle-debounce/debounce' in /home/quqiufeng/element/packages/table/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/table/src/table.vue 11:16-53
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/popover/src/main.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/event' in /home/quqiufeng/element/packages/popover/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/popover/src/main.vue 13:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/form/src/form-item.vue
    Module not found: Error: Cannot resolve module 'async-validator' in /home/quqiufeng/element/packages/form/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/form/src/form-item.vue 5:22-48
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/slider/src/main.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/style' in /home/quqiufeng/element/packages/slider/src
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/slider/src/main.vue 13:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/date-picker/src/basic/date-table.vue
    Module not found: Error: Cannot resolve module 'wind-dom/src/class' in /home/quqiufeng/element/packages/date-picker/src/basic
     @ /usr/local/node/lib/~/cooking/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./packages/date-picker/src/basic/date-table.vue 7:13-42
    
    ERROR in /usr/local/node/lib/~/cooking/~/css-loader!../.cooking/~/postcss-loader!./packages/theme-default/src/index.css
    Module build failed: Error: ENOENT: no such file or directory, open '/home/quqiufeng/element/packages/dialog/node_modules/vue-popup/lib/popup.css'
        at Error (native)
    From previous event:
        at Object.readFile (/home/quqiufeng/.cooking/node_modules/fs-promise/index.js:34:12)
        at /home/quqiufeng/.cooking/node_modules/saladcss-partial-import/index.js:106:14
        at run (/home/quqiufeng/.cooking/node_modules/core-js/modules/es6.promise.js:87:22)
        at /home/quqiufeng/.cooking/node_modules/core-js/modules/es6.promise.js:100:28
        at flush (/home/quqiufeng/.cooking/node_modules/core-js/modules/_microtask.js:18:9)
        at nextTickCallbackWith0Args (node.js:420:9)
        at process._tickCallback (node.js:349:13)
     @ ./packages/theme-default/src/index.css 4:14-191 13:2-17:4 14:20-197
    Child html-webpack-plugin for "index.html":
        
webpack: bundle is now VALID.

**Comment by Leopoldthecoder** [comment]
@quqiufeng 请参见文档执行 `make dev` 而不是 `npm run dev`

**Comment by quqiufeng** [comment]
谢谢解决了!

**Comment by peanuts6** [comment]
怎么解决的？ ERROR in /usr/local/node/lib/~/cooking/~/babel-loader!./~/vu

**Comment by shihua-guo** [comment]
@quqiufeng 你是怎么解决的，麻烦说下思路或者解决办法，谢谢

**Comment by geosmart** [comment]
添加 "throttle-debounce": "1.1.0", 到dependency即可
