### ISSUE TITLE
[Bug Report] vertical导航，嵌套`el-submenu`子级导航无法出现导航项bug。

### ISSUE THREAD

**Issue by cddsgtc** [ElemeFE/element#4000]
### Element UI version
1.2.7

### OS/Browsers version
win10/ chrome v59

### Vue version
2.2.0

### Reproduction Link
[https://jsfiddle.net/FarmerZ/jdobm749/3/](https://jsfiddle.net/FarmerZ/jdobm749/3/)

### Steps to reproduce
点击链接，hover菜单三

### What is Expected?
子级嵌套导航能够正确显示其下的导航项。

### What is actually happening?
1. hover导航出现子级嵌套导航。
2. 然后快速把鼠标移到除了第一个导航之外的导航。
3.子级嵌套导航不会出现导航项，而是直接收起。

**Comment by Leopoldthecoder** [comment]
我这没能重现。可以贴个有问题的动图。

**Comment by cddsgtc** [comment]
@Leopoldthecoder 
抱歉，忘了保存了，实际重现地址是这个[https://jsfiddle.net/FarmerZ/jdobm749/3/](https://jsfiddle.net/FarmerZ/jdobm749/3/)

图示：
![nimbus-record-video](https://cloud.githubusercontent.com/assets/16315661/24691944/0e80d882-1a09-11e7-9988-9955f60a0290.gif)

**Comment by Leopoldthecoder** [comment]
内嵌子菜单只支持垂直模式。

**Comment by cddsgtc** [comment]
@Leopoldthecoder 
我想做的是这种效果，也算是很实用吧，希望贵开发组何以考虑到，并实现。
图示：
![nimbus-record-video](https://cloud.githubusercontent.com/assets/16315661/24693531/93c3f25c-1a10-11e7-9aab-8a03963ec8e6.gif)

**Comment by 466035017** [comment]
同样遇到了这样的bug，不知道该怎么解决了

**Comment by focusqfb** [comment]
请问你解决了吗，我现在用的版本一。。遇到了和你一样的问题，不知道如何解决

**Comment by focusqfb** [comment]
@Mying666 @cddsgtc 你们解决了么
