### ISSUE TITLE
[Feature Request] 悬浮触发菜单，菜单打开无延迟&无过渡动画

### ISSUE THREAD

**Issue by zcyzcy88** [ElemeFE/element#4001]
### Existing Component
Yes

### Component Name
Dropdown 和 Select

### Description
如题，请提供选项
例子：http://www.bilibili.com/ranking#!/all/0/0/1/
<img width="311" alt="2017-04-05 13_15_21- - - -bilibili" src="https://cloud.githubusercontent.com/assets/15178410/24690844/28bfa09a-1a02-11e7-821a-ad637fddf214.png">
<img width="161" alt="2017-04-05 13_07_43- - - -bilibili" src="https://cloud.githubusercontent.com/assets/15178410/24690847/2b194198-1a02-11e7-835b-3ca09f78ffa5.png">

**Comment by Leopoldthecoder** [comment]
无计划添加此 API。
