### ISSUE TITLE
[Bug Report] table的table-column使用filtered-value后筛选UI改变，但数据还是原始的

### ISSUE THREAD

**Issue by uedkx** [ElemeFE/element#4005]
### Element UI version
1.2.7

### OS/Browsers version
chrome 57

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ykb4x5sy/](https://jsfiddle.net/ykb4x5sy/)

### Steps to reproduce
demo中加入了filtered-value，筛选项中选中了对应项

### What is Expected?
表格中的数据应该也是显示filtered-value中的项

### What is actually happening?
目前只是表头中筛选UI做了改变，表格数据没有变

**Comment by Leopoldthecoder** [comment]
@liril-net 上次你好像研究过这个属性？

**Comment by Leopoldthecoder** [comment]
Fixed in #4021

**Comment by Lemonjay** [comment]
鸡肋，看了十几条，tmd 没解决方法，全都是搪塞
