### ISSUE TITLE
[Bug Report] el-radio绑定click事件一次点击触发两次回调

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#4007]
### Element UI version
1.2.5

### OS/Browsers version
win10/ chrome 56

### Vue version
2.2.5

### Reproduction Link
[https://jsfiddle.net/wsqrk2ea/1/](https://jsfiddle.net/wsqrk2ea/1/)

### Steps to reproduce
点击radio

### What is Expected?
alert一次

### What is actually happening?
alert了两次

**Comment by hwb2167sq** [comment]
我也遇到了这个问题 ，求帮助

**Comment by Leopoldthecoder** [comment]
这是 `label` 标签的默认行为：https://jsfiddle.net/leopoldthecuber/wsqrk2ea/2/ ，点击这个例子的「备选项」也会 alert 两次。

**Comment by Yuliang-Lee** [comment]
@hwb2167sq @click.prevent 就可以了, http://stackoverflow.com/questions/8238599/jquery-click-fires-twice-when-clicking-on-label

**Comment by hwb2167sq** [comment]
@Yuliang-Lee 谢谢

**Comment by hwb2167sq** [comment]
![image](https://cloud.githubusercontent.com/assets/13146396/24702396/297165bc-1a31-11e7-82d9-5745e3d952fa.png)
我的需求是这样的(点击radio选中默认的) 。但是加上prevent以后 click事件直接不触发了

**Comment by kylesean** [comment]
@hwb2167sq 你好，遇到同样的问题，请问你解决了吗？

**Comment by kylesean** [comment]
@hwb2167sq 用了一个hack方法， @click.prevent不生效。换成  @click.native.prevent 但这时候element组件的选中效果没有，然后将v-model置于切换过来的值，但是样式有一丢丢怪怪的。不知道你们怎么解决的。

**Comment by null2014** [comment]
<el-radio v-model.lazy="dto.biz.numbering" label="1" v-on:click.native.prevent="fn()">A</el-radio>

**Comment by null2014** [comment]
<el-radio v-model.lazy="dto.biz.numbering" label="1" v-on:click.native.prevent="fn()">A</el-radio>

**Comment by null2014** [comment]
`<el-radio v-model.lazy="dto.biz.numbering" label="1" v-on:click.native.prevent="fn()">A</el-radio>`

**Comment by null2014** [comment]
確實效果沒有那麼好

**Comment by edum18** [comment]
got the solution to unselect a radio button with the following code
``` 
<el-radio-group v-model="status">
    <el-radio :label="false"
              @click.native.prevent="customCheckboxClick(false)">
        Option A
    </el-radio>
    <el-radio :label="true"
              @click.native.prevent="customCheckboxClick(true)">
        Option B
    </el-radio>
</el-radio-group>


customCheckboxClick(val) {
    this.status = this.status === val ? null : val;
},

```
