### ISSUE TITLE
[Bug Report] table组件sortable排序问题

### ISSUE THREAD

**Issue by MoxHotPot** [ElemeFE/element#4009]
### Element UI version
1.2.7

### OS/Browsers version
Mac

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
sortable排序后，只是表格的数据展示顺序变换了，数组里的数据顺序没有改变。

### What is Expected?
希望排序后数组里的数据顺序改变。应该怎么，才能让数组里的数据顺序也进行变化

### What is actually happening?
sortable排序后，只是表格的数据展示顺序变换了，数组里的数据顺序没有改变。

**Comment by Leopoldthecoder** [comment]
数据的顺序当然不会变。需要改变的话自己通过 `sort-change` 事件处理。
