### ISSUE TITLE
[Bug Report] 把动态列赋值为空，整个列就出问题了。

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#4014]
### Element UI version
1.2.7

### OS/Browsers version
win10/chrome

### Vue version
2.2.6

### Reproduction Link
[http://jsrun.net/SUkKp/edit](http://jsrun.net/SUkKp/edit)

### Steps to reproduce
点重置按钮

### What is Expected?
不影响其他的列

### What is actually happening?
列不显示了

**Comment by Leopoldthecoder** [comment]
给每个 TableColumn 加上 key 就可以。
