### ISSUE TITLE
[Feature Request] tree的default-checked-keys属性双向绑定

### ISSUE THREAD

**Issue by hongxiangWang** [ElemeFE/element#4015]
### Existing Component
是

### Component Name
tree

### Description
使用default-checked-keys设定默认勾选项后，通过状态或者父组件传值修改default-checked-keys值，view并没有更新，即视图不更新，没有起到双向绑定数据的目的。

**Comment by Leopoldthecoder** [comment]
本来就不是「双向绑定」的，`default-checked-keys` 的 `default` 意思就是「默认」，仅在初次渲染时有效。

**Comment by hongxiangWang** [comment]
那双向绑定有效的属性值有没有

**Comment by Leopoldthecoder** [comment]
没有。之后需要通过 Tree 提供的方法去更改。

**Comment by hongxiangWang** [comment]
非常感谢

**Comment by lx2328** [comment]
我用一个全局Map来保存被勾选的节点，在下一次组件mounted时，把保存的数据赋值给 default-checked-keys ，当保存的数据只有一个时，会出现子节点被勾选，对应的父节点没有被半勾选的状态，当数据超过两个时，是正常的，请问这个问题有什么办法解决吗
