### ISSUE TITLE
[Bug Report]当table组件包含大量事件监听时的性能优化问题

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/element#4022]
### Element UI version
1.2.7

### OS/Browsers version
Chrome 55 / windows 10

### Vue version
2.1.0

### Reproduction Link
[http://jsfiddle.net/rossroma/u36rak6k/7/](http://jsfiddle.net/rossroma/u36rak6k/7/)

### Steps to reproduce
Table组件常用来展示大量的数据，每页显示200-500条，每条有20-40个字段，都是很常见的需求。如果每个字段都是普通的字符串，在渲染和显示的时候问题不大。如果当中包含click、change或mouseover事件时，就会有比较严重的性能问题。
demo中示例可能比较极端，但实际生产环境中，也会有类似数量的事件绑定，绑定的事件越多，卡顿越严重。

### What is Expected?
官方是否有考虑优化一下大量事件监听时的性能问题，比如采用“事件委托” http://www.cnblogs.com/liugang-vip/p/5616484.html

### What is actually happening?
当绑定大量事件时，所有操作都会变卡

**Comment by reusLi** [comment]
### Element UI version

1.2.7

### OS/Browsers version

Chrome 57 / windows 10

### Vue version

2.2.2

### Reproduction Link

https://jsfiddle.net/ReusLi/o4uo0z7j/9/

### Steps to reproduce

input输入 enter键后 无法触发@keyup.enter
发现原因是用了`<el-input @keyup.enter="pushCards"/> `
如果改成普通的`<input     @keyup.enter="pushCards"/>`是没问题的

### What is Expected?

希望得到使用<el-input/>下能够触发@keyup.enter的解决方案.

**Comment by chenmingjia** [comment]
请问你后来是如何解决table层次多深，导致加载慢的问题？

**Comment by rossroma** [comment]
自己重写table组件 @chenmingjia

**Comment by amor520** [comment]
![image](https://user-images.githubusercontent.com/14037268/28866244-e2acac28-77a4-11e7-9d39-829b86046a19.png)
我的有很多inline-template，翻页的时候，会比较卡

**Comment by 269378737** [comment]
有没有人解决了这个问题的

**Comment by fengyun2** [comment]
+1

**Comment by zhoubopro** [comment]
+1

**Comment by iluozhiqiang** [comment]
+1
