### ISSUE TITLE
[Bug Report] <el-input/>标签内无法触发@keyup.enter指令

### ISSUE THREAD

**Issue by reusLi** [ElemeFE/element#4026]
### Element UI version
1.2.7

### OS/Browsers version
Chrome 57 / windows 10

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/ReusLi/o4uo0z7j/9/](https://jsfiddle.net/ReusLi/o4uo0z7j/9/)

### Steps to reproduce
input输入 enter键后 无法触发@keyup.enter
发现原因是用了`<el-input @keyup.enter="pushCards"/> `
如果改成普通的`<input     @keyup.enter="pushCards"/>`是没问题的

### What is Expected?
希望得到使用<el-input/>下能够触发@keyup.enter的解决方案.

### What is actually happening?
<el-input/>下无法触发@keyup.enter

**Comment by Leopoldthecoder** [comment]
请仔细阅读 FAQ

**Comment by PhillippOhlandt** [comment]
@Leopoldthecoder which FAQ? I am missing the keyup events on the input component too.

**Comment by chenqinyang1994** [comment]
@keyup.enter.native="fn"   
add a ".native"   
it is ok!
