### ISSUE TITLE
[Request] Include changes for 1.2.7 in the documentation changelog

### ISSUE THREAD

**Issue by syn-zeta** [ElemeFE/element#4027]
### Existing Component
Yes

### Component Name
CHANGELOG.en-US.md / CHANGELOG.zh-CN.md

### Description
Should the above changelog files be updated to include 1.2.7 changes? http://element.eleme.io/#/en-US/component/changelog currently only lists changes up until 1.2.6.

**Comment by Leopoldthecoder** [comment]
Will be updated later today.
