### ISSUE TITLE
Table中Popover定位会错乱

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#403]
### ElementUI version
1.0.0-rc.6

### Vue version
2.0.2

### Reproduction Link
https://jsfiddle.net/erguotou525/ed385dza/

### Steps to reproduce
第一次鼠标放在链接上，正常，移开，再hover，可以发现错位，而且越是下方的`popover`错位越明显，鼠标向下滚一下，又回来了。

**Comment by QingWei-Li** [comment]
demo 链接好像不太对，你试试 rc7 还有没有问题

**Comment by erguotou520** [comment]
是否与#357一样？

**Comment by erguotou520** [comment]
https://jsfiddle.net/erguotou525/ed385dza/1/

**Comment by QingWei-Li** [comment]
换到 rc7 正常了

**Comment by erguotou520** [comment]
恩，正常了https://jsfiddle.net/erguotou525/ed385dza/2/。刚发布的rc7，之前还没注意到
