### ISSUE TITLE
[Bug Report] transitionend not called when tab is backgrounded 

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#4034]
### Element UI version
1.2.7

### OS/Browsers version
chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/rc14q0km/](https://jsfiddle.net/rc14q0km/)

### Steps to reproduce
点击按钮 之后 切换tab 讲当前tab变为backgrounded 过一段时间再回来查看

### What is Expected?
destroyElement

### What is actually happening?
当tab 在backgrounded 时不会触发transitionend 所以message notification等用到transitionend 来触发destroyElement的都不会触发导致
![image](https://cloud.githubusercontent.com/assets/8121621/24740162/5e4b7f10-1ad2-11e7-8a8f-c1e97c41ada5.png)

相关问题：https://github.com/facebook/react/issues/1326

**Comment by Leopoldthecoder** [comment]
你贴的那个 issue 里好像说是浏览器的问题，试了一下确实是：https://jsfiddle.net/leopoldthecuber/5ee560c3/1/

切换标签的时候 transitionend 是不触发的，所以造成了这个问题。感觉除了用 `setTimeout` 来做 destroyElement 以外没有什么更好的办法了，但是 `setTimeout` 又太脏……

**Comment by PanJiaChen** [comment]
这也不能算游览器的bug，可以理解为理解为游览器的一种优化。
目前大部分的都是加个延迟duration的做法
