### ISSUE TITLE
tree 动态在子节点下面添加数据 没有显示

### ISSUE THREAD

**Issue by 89lovelc** [ElemeFE/element#404]
### OS/Browers version
Chrome 53

### Steps to reproduce
  动态在tree 下面添加一个子节点
### What is Expected?
 动态添加的时候能够渲染出来
### What is actually happening?
 并没有渲染出来

**Comment by furybean** [comment]
能给个例子是如何动态添加的么？代码也可以。

**Comment by 89lovelc** [comment]
比如说 我 在tree的节点上 绑定了一个事件，参数为node。 现在有个按钮就是添加子节点，node.children.push(newNode); 这个方法没有刷新界面。

**Comment by 89lovelc** [comment]
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>tree</title>
    
     <link rel="stylesheet" href="./element-ui/element-ui.min.css">

    
    <script src="http://unpkg.com/vue@2.0.0-rc.6/dist/vue.js"></script>
    <script src="./element-ui/element-ui.min.js"></script>
</head>
<body>
    <div id="app">
        <el-button @click.native="add"> Test</el-button>
        <el-tree :data="data" :props="defaultProps" @node-click="handleNodeClick"></el-tree>
    </div>
<script>
    new Vue({
        el:'#app',
        data: function(){
            return {
                data: [{
                    label: '一级 1',
                    children: [{
                        label: '二级 1-1'
                    }]
                }, {
                    label: '一级 2',
                    children: [{
                        label: '二级 2-1'
                    }, {
                        label: '二级 2-2'
                    }]
                }],
                defaultProps: {
                    children: 'children',
                    label: 'label'
                },
                selectNode:''
            };
        },
        methods: {
            handleNodeClick:function(data){
                this.selectNode = data;
            },
            add:function(){
                //单独一个添加 不渲染界面
                this.selectNode.children.push({
                    label: 'test',
                });
                /*这样可以 但是 并不好
                this.data.push({
                    label: 'test',
                });
                this.selectNode.children.push({
                    label: 'test',
                });
                */


            }
        }
        });

</script>
</body>
</html>

**Comment by 89lovelc** [comment]
`<div id="app">
        <el-button @click.native="add"> Test</el-button>
        <el-tree :data="data" :props="defaultProps" @node-click="handleNodeClick"></el-tree>
    </div>`

` new Vue({
        el:'#app',
        data: function(){
            return {
                data: [{
                    label: '一级 1',
                    children: [{
                        label: '二级 1-1'
                    }]
                }, {
                    label: '一级 2',
                    children: [{
                        label: '二级 2-1'
                    }, {
                        label: '二级 2-2'
                    }]
                }],
                defaultProps: {
                    children: 'children',
                    label: 'label'
                },
                selectNode:''
            };
        },
        methods: {
            handleNodeClick:function(data){
                this.selectNode = data;
            },
            add:function(){
                //单独一个添加 不渲染界面
                this.selectNode.children.push({
                    label: 'test',
                });
                /*这样可以 但是 并不好
                this.data.push({
                    label: 'test',
                });
                this.selectNode.children.push({
                    label: 'test',
                });
                */


            }
        }
        });`

**Comment by furybean** [comment]
已经在 #470 修复，rc8 版本发布会包含。
