### ISSUE TITLE
[Bug Report] table-column多级表头与v-if混用会出现 table列缺失

### ISSUE THREAD

**Issue by SimonLeeee** [ElemeFE/element#4043]
### Element UI version
1.2.7

### OS/Browsers version
win7 / chrome

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/owb1xd1y/2/](http://jsfiddle.net/owb1xd1y/2/)

### Steps to reproduce
1, table-column组件使用多级表头
2, 嵌套的子table-column用v-if进行切换
3, 每切换一次 缺失一列， 直到整个table的列为空.

### What is Expected?
快点修复

### What is actually happening?
快点修复

**Comment by dinggaihua** [comment]
多级表头的情况下，v-for 循环element UI 里的<el-table-column> 当被循环的数据发生改变时 ，没有正常正确循坏变化后的数据

**Comment by AaronChen2012** [comment]
@Leopoldthecoder 目前 针对多级表头，动态调整列的提的人好像挺多的，望能把这个优先级调高点！这个问题我在几个月前提出来过的

**Comment by qianqWang** [comment]
是需要快点解决啊。还有，如果表头是表头，数据是数据就好了。比如这一条数据有30列。但是中间有多级表头。那么这个数据就不能一下子循环30个了。就让el-table-column拆开了。。。

**Comment by qingwufengyang** [comment]
我这里也遇到了，希望赶紧解决

**Comment by xxgo1992** [comment]
有处理方案了吗

**Comment by AaronChen2012** [comment]
table bug 还是挺多的，包括新增的合计，还有动态换列。哎，英文的不高兴提了，将就用吧

**Comment by superpig** [comment]
还么解决吗？

**Comment by fliu2476** [comment]
同遇到问题

**Comment by yangjiecan** [comment]
尴尬了，多级表头重新渲染数据会出现数据丢失

**Comment by zouliming** [comment]
ele1.4.2 同样遇到这样的问题。el-table-column与v-if一起使用的时候，会报错，而且列有时候会出不来。

**Comment by fliu2476** [comment]
@zouliming 
现在的问题是：列由多到少的时候出现无法渲染的bug。
我现在的处理方案是：需要动态更新列，整个重新渲染table组件。

**Comment by zouliming** [comment]
@fliu2476 我还不清楚如何重新渲染table组件，可否告知一下？

**Comment by fliu2476** [comment]
@zouliming 最粗暴的，直接用v-if控制el-table，更新数据前置为false，更新数据后改成true

**Comment by zouliming** [comment]
@fliu2476 谢谢，网上搜了一下其他方法，发现大家都还是挺粗暴的。

**Comment by Leopoldthecoder** [comment]
牵扯到动态显示隐藏的，建议给 el-table-column 或 el-table 加上 key：http://jsfiddle.net/owb1xd1y/7/ 。例子中的 Math.random() 只是为了说明效果，实际使用任何唯一性的值都行。

**Comment by ekoooo** [comment]
当列的显示状态改变时重新渲染整个表格，请看：https://jsfiddle.net/yedL9b8n/14/
