### ISSUE TITLE
[Bug Report] Duplicate declaration "ElTooltip"

### ISSUE THREAD

**Issue by lizhiyao** [ElemeFE/element#4046]
### Element UI version
1.2.7

### OS/Browsers version
macOS 10.12.3  

### Vue version
2.1.8

### Reproduction Link
[https://jsfiddle.net/it's/a/useless/link](https://jsfiddle.net/it's/a/useless/link)

### Steps to reproduce
1. fork 项目
2. 克隆项目到本地
3. npm i
4. npm run dev

### What is Expected?
执行 npm run dev 不报错

### What is actually happening?
ERROR in ./packages/table/src/table-body.js
Module build failed: Duplicate declaration "ElTooltip"

**Comment by pengchongfu** [comment]
ci 竟然没有报错。。
