### ISSUE TITLE
[Bug Report] Menu binding to defaultActive don't update at beginning

### ISSUE THREAD

**Issue by gabrielboliveira** [ElemeFE/element#4048]
### Element UI version
1.2.7

### OS/Browsers version
macOS Sierra 10.12.4 / Chrome 57

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/saetsgzo/](http://jsfiddle.net/saetsgzo/)

### Steps to reproduce
Update menu items (with v-for, for example) and change default-active right after adding/removing items

### What is Expected?
Active menu to be changed

### What is actually happening?
Active menu is not changed. Just as an example, this fiddle works: http://jsfiddle.net/z3wLb2wx/. Setting a timeout to change the default active changes the active item, but if you change right after adding, it does not update.

**Comment by gabrielboliveira** [comment]
I'm not sure if binding to `default-active` is the best approach, perhaps adding a `v-model` so we can directly track which item is active.

**Comment by gabrielboliveira** [comment]
This is probably a duplicate of #2670. Feel free to close if you think so

**Comment by baiyaaaaa** [comment]
your demo is not about menu

**Comment by looneyren** [comment]
need prop "action", data name "actionIndex", but not implement

**Comment by PanJiaChen** [comment]
http://jsfiddle.net/saetsgzo/1/
