### ISSUE TITLE
select选择器创建条目未配置multiple时出bug

### ISSUE THREAD

**Issue by ganpanlin** [ElemeFE/element#4050]
**Element UI version**

1.2.7

OS/Browsers version

Chrome 56

Vue version

2.2.6

Reproduction Link

https://jsfiddle.net/ytmhyneg/

采用一下设置时，下拉框新建选项无法显示值（官网示例，去除multiple ）
```
 <el-select v-model="value10"  filterable="" allow-create placeholder="请选择文章标签">
   <el-option v-for="item in options5" :label="item.label" :value="item.value">
    </el-option>
  </el-select>
```

**Comment by RoamIn** [comment]
The official demo [http://jsfiddle.net/api/post/library/pure/](http://jsfiddle.net/api/post/library/pure/) doesn't work
