### ISSUE TITLE
[Bug Report] select选择器创建条目未配置multiple时出bug 

### ISSUE THREAD

**Issue by ganpanlin** [ElemeFE/element#4051]
### Element UI version
1.2.7

### OS/Browsers version
chrome56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ytmhyneg/](https://jsfiddle.net/ytmhyneg/)

### Steps to reproduce
select 中未配置multiple

1、选中选择器
2、编辑新选项
3、确定新选项

### What is Expected?
发现新选项出现，值出现在待选列表中

### What is actually happening?
4、发现新选项出现，但是值为空，待选列表中出现空选择项

**Comment by Leopoldthecoder** [comment]
已在 #3984 修复
