### ISSUE TITLE
[Bug Report] 表格内有两个动态组件列时无法切换动态组件

### ISSUE THREAD

**Issue by kospot** [ElemeFE/element#4052]
### Element UI version
1.2.7

### Existing Component
是

### Component Name
el-table el-table-column

### Reproduction Link
http://runjs.cn/code/bds1z2ts

### Description
当表格中有两个动态组件时，在1.2.7下无法切换；只有一个的时候可以切换；
在1.2.5下无论一个还是两个都可以切换

**Comment by Leopoldthecoder** [comment]
给每个 `<component>` 和 `<el-table-column>` 加上 `key` 就可以，比如 `:key="Math.random()"`。Math.random() 只是为了说明效果，实际使用任何唯一性的值都行。
