### ISSUE TITLE
[Feature Request] 在JSON Tree下加table expand功能

### ISSUE THREAD

**Issue by snowkirin** [ElemeFE/element#4056]
### Existing Component
Yes

### Component Name
el-table

### Description
目前我所設計的code如下：
JSON 架構

[{
   "id": "1",
   "label": "Label 1",
   "children": [{
      "id": "1-1",
      "label": "Label 1-1"
   }, {
      "id": "1-2",
      "label": "Label 1-2"
   }]
}, {
   "id": "2",
   "label": "Label 2"
}]

在此Tree架構下，我想在擁有children的Object里加expand功能。
我怎樣設計就能體現Expand功能？
目前支持這種架構嗎？ 如果沒有支持，之後有打算支援嗎？

**Comment by Leopoldthecoder** [comment]
「expand功能」具体是指？

**Comment by snowkirin** [comment]
<el-table-column type="expand"></el-table-column>
el-table-coumn Component`s type attribute

**Comment by vipplus** [comment]
![Uploading image.png…]()
就这种树表

**Comment by Leopoldthecoder** [comment]
@vipplus 你的图片没上传完
