### ISSUE TITLE
[Bug Report] 在 el-table-column 里使用 v-for 的问题

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#4057]
### Element UI version
1.2.7

### OS/Browsers version
Mac Chrome 57

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/lincenying/pj71jkyw/41/](https://jsfiddle.net/lincenying/pj71jkyw/41/)

### Steps to reproduce
打开重现链接, 然后依次点击, [数据2] 和 [数据3] 按钮, 然后表格出现列数不对的情况

https://jsfiddle.net/lincenying/pj71jkyw/42/

上面的地址是直接使用原生table, 并没有这个问题.

### What is Expected?
期待和直接使用table的效果一致

### What is actually happening?
改变渲染数据时, 组件的列数错误

**Comment by vipplus** [comment]
table什么时候能支持树状的？

**Comment by dinggaihua** [comment]
多级表头的情况，v-for 循环element UI 里的<el-table-column> 当被循环的数据发生改变时 ，没有正常正确循坏变化后的数据

**Comment by liangxiaojuan** [comment]
我也解决了。

**Comment by liangxiaojuan** [comment]
我也发现了这个问题。

**Comment by yangjiecan** [comment]
是啊，多级表头重新渲染数据就是个大坑啊

**Comment by Leopoldthecoder** [comment]
牵扯到动态显示隐藏的，`key` 的值应该在动态切换前后保持唯一：https://jsfiddle.net/yedL9b8n/13/ 。

**Comment by YoYoLady** [comment]
> 牵涉到动态显示隐藏的，`key` 的值应该在动态切换前后保持唯一：https://jsfiddle.net/yedL9b8n/13/ 。

加上随机数，还是会数据错位

**Comment by isSkyid** [comment]
我也遇到了这个问题，你们解决了吗？
