### ISSUE TITLE
[Bug Report] ie 11 not render icon

### ISSUE THREAD

**Issue by itdepartament** [ElemeFE/element#4058]
### Element UI version
1.2.7

### OS/Browsers version
internrt explorer 11

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
when i place menu in my page http://test.1cv8.moscow/vnedrenie-1c.php
all elem icons not render in ie 11, but all other browser work correct.
i work from CDN

### What is Expected?
no render elem icons in ie11

### What is actually happening?
render elem icons in ie11

**Comment by Leopoldthecoder** [comment]
Can the icons be rendered if you open http://element.eleme.io/ in IE11?

**Comment by itdepartament** [comment]
but why no? font-awesome work correct.

**Comment by Leopoldthecoder** [comment]
![image](https://cloud.githubusercontent.com/assets/10095631/25132777/37f66866-247d-11e7-9006-80397e2cda1a.png)

It works for me. Could you try updating IE11's version?

**Comment by itdepartament** [comment]
no, ie 11 is finally for windows 7 platform, this is very popylar os, for
many users(

18.04.2017 16:24 пользователь "杨奕" <notifications@github.com> написал:

**Comment by itdepartament** [comment]
if this work hard, you can not to do anything.
who need correct, can override symbol in css

2017-04-18 19:13 GMT+03:00 1c <itdepartament@gmail.com>:
