### ISSUE TITLE
[Feature Request] input 增加清除按钮，类似日期选择控件的clearable

### ISSUE THREAD

**Issue by AaronChen2012** [ElemeFE/element#4059]
### Existing Component
是

### Component Name
input

### Description
input 增加清除按钮，类似日期选择控件的clearable，
clearable增加回调事件

**Comment by zhzpeng** [comment]
input 可以用icon来解决清空问题，但是如果配置的append的 slot button，icon会被覆盖掉

**Comment by wzshuang** [comment]
+1

**Comment by Leopoldthecoder** [comment]
> input 可以用icon来解决清空问题，但是如果配置的append的 slot button，icon会被覆盖掉，所以希望增加一个清空的功能

2.0.0 会解决这个问题，所以可以自己配置 icon 来做清空了。
