### ISSUE TITLE
[Feature Request] 标题栏动态生成无法正确作用

### ISSUE THREAD

**Issue by ieiayaobb** [ElemeFE/element#4069]
### Existing Component
是

### Component Name
table

### Description
我的列标题也是动态从后台获取生成的，不能保证比数据先生成，有办法正确渲染吗？
https://jsfiddle.net/ieiayaobb/mcyczfa9/19/

**Comment by Leopoldthecoder** [comment]
`setTimeout` 回调里的 this 指向错误，改成箭头函数就好了。
