### ISSUE TITLE
关于tab-pane绑定数组无法动态更新

### ISSUE THREAD

**Issue by zhengyuxi1991** [ElemeFE/element#407]
```
<el-tabs :closable="true" @tab-click="handleClick" @tab-remove="handleRemove">
  <el-tab-pane v-bind:label="openMenu.displayName" v-for="openMenu in openMenus">
    {{openMenu.name}}
  </el-tab-pane>
</el-tabs>
```

tab-pane如此绑定一个数组后，当数组数量发生变化时，界面没有更新

**Comment by erguotou520** [comment]
最好给出重现的地址啊

**Comment by baiyaaaaa** [comment]
tabs 组件目前确实不支持动态更新

**Comment by lsbrucelincoln** [comment]
同样的问题……果然还不支持，这怎么破

**Comment by baiyaaaaa** [comment]
#812

**Comment by cyclechang** [comment]
已找到方法解决，可以定义一个空数组，动态的往其中push对象
this.editableTabs.push({
          title: 'New Tab',
          name: newTabName,
          content: 'New Tab content'
        });
此方式页面tab会实时刷新
参考官方API：https://element.eleme.cn/#/zh-CN/component/tabs#tabs-biao-qian-ye
自定义增加标签页触发器
