### ISSUE TITLE
[Feature Request] Where can I get the source code of "https://elementui.github.io/theme-preview/#/en-US"??

### ISSUE THREAD

**Issue by lahngp** [ElemeFE/element#4070]
### Existing Component
No

### Component Name
theme

### Description
The theme presented in "https://elementui.github.io/theme-preview/#/en-US" looks nice, I wonder where I can get the source code of this page?

**Comment by Leopoldthecoder** [comment]
Here: https://github.com/ElementUI/theme-preview
