### ISSUE TITLE
[Bug Report] 动态表单验证失效

### ISSUE THREAD

**Issue by NameYoung** [ElemeFE/element#4074]
### Element UI version
1.2.3

### OS/Browsers version
Ubuntu 16.0.4  / chrome Version 57.0.2987

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/NameYoung/bkukcpLb/4/](https://jsfiddle.net/NameYoung/bkukcpLb/4/)

### Steps to reproduce
https://jsfiddle.net/NameYoung/bkukcpLb/4/

* 运行代码
* 输入任意字符，鼠标离开输入框，即可发现错误

### What is Expected?
鼠标离开输入框，验证是否输入为空
若为空，则提示错误信息，
不为空，则不做提示（这个demo,输入不为空，错误提示依然存在）

### What is actually happening?
我没有去研究源码，不确定是不是我使用方法错误，还是数据格式错误，或者是确实存在这个bug。
谢谢～

**Comment by Leopoldthecoder** [comment]
数据格式和用法都有点问题，正确用法：https://jsfiddle.net/bkukcpLb/5/
可以参考下文档上的这个例子：http://element.eleme.io/#/zh-CN/component/form#dong-tai-zeng-jian-biao-dan-xiang

**Comment by NameYoung** [comment]
非常感谢
