### ISSUE TITLE
Table中添加按钮触发事件的问题

### ISSUE THREAD

**Issue by anshengme** [ElemeFE/element#408]
![qq 20161014023823](https://cloud.githubusercontent.com/assets/16428340/19361980/4ff36634-91b7-11e6-8c7e-ce020fdc9bf6.png)

如上图所示，如果在行中添加了按钮，那么按钮绑定的事件，怎么把当前行的数据给传过来，好做处理？

加了这么一列，用于操作当前行的
```
<el-table-column inline-template label="操作" show-tooltip-when-overflow>
             <span>
               <el-button type="primary" size="small">修改</el-button>
               <el-button type="info" size="small">详情</el-button>
               <el-button type="danger" size="small" v-on:click.native="DeleteUser">删除</el-button>
             </span>
</el-table-column>
```
怎么把当前行的值传过来呢？

**Comment by erguotou520** [comment]
文档中已经有写，可以获取到`row`值，比如`<el-button type="primary" @click.native="edit(row.id)">修改</el-button>`

**Comment by Leopoldthecoder** [comment]
楼上说得对
