### ISSUE TITLE
[Feature Request] 由父组件控制dialog的显示和隐藏

### ISSUE THREAD

**Issue by gera2ld** [ElemeFE/element#4082]
### Existing Component
是

### Component Name
dialog

### Description
希望完全由父组件控制dialog的显示和隐藏，关闭时发出事件就好了，让父组件来把`v-model`的值赋为false，这样的好处：
- 保证了数据的单向流动；
- 让父组件可以更加灵活地控制流程，比如：
  - 异步回调之后再选择关闭dialog或者在dialog上显示信息；
  - 在点击遮罩或者按esc关闭时根据当前状态选择是否阻止dialog的关闭。

目前的方案下，如果由内建方法关闭了dialog，则整个过程变得完全不可控，无法阻止，而且`v-model`对应的父组件属性就被修改了。

不是很理解这里为什么要用`v-model`，我觉得用普通的props就好了：`<dialog :visible="visible" @cancel="visible=false">...</dialog>`，代码并没有多多少，流程却清晰和灵活多了。
这块AntDesign的Modal就很好用，希望参考一下。

**Comment by xiachaoxulu** [comment]
比如说alert 组件。 请问，一旦用户通过关闭了按钮，怎么再打开刚才的那个alert呢，

**Comment by jikkai** [comment]
这样做的话是不是按 esc 或者点击 modal 关闭窗口都要用户手动实现一遍了😂？

如果不需要这种功能的话，可以使用 dialog 组件暴露出来的 `open` 和 `close` 方法来操作 dilaog 的显示和隐藏

**Comment by gera2ld** [comment]
抛出一个事件就好了啊，`<dialog @press-esc="close" @backdrop-click="close" @ok="ok">...</dialog>`，这样用户可以很灵活地选择要不要关闭。

其他地方都在努力抛弃双向绑定，因为不好控制，你们却又在这一个地方突然搞出个子组件修改父组件属性来，这样真的好吗？

`open`和`close`并不够啊，比如我希望点击遮罩和按esc和点取消都是一样的效果，先做个判断，再决定是否关闭，这就实现不了了。

**Comment by Leopoldthecoder** [comment]
https://github.com/vuejs/vue/issues/4946 这里有相关讨论。

使用 v-model 绑定开关变量的做法目前看来不会变，后面会考虑加入一个 `beforeClose` 的钩子，这样就可以阻止关闭了。

**Comment by Leopoldthecoder** [comment]
`beforeClose` 已在 #4423 添加。
