### ISSUE TITLE
[Bug Report] el-cascader的change-on-select为true时，由选中多级后，再重新选择只有一级的选项时，当前选中的值数组长度居然不是1

### ISSUE THREAD

**Issue by asea1718** [ElemeFE/element#4086]
### Element UI version
1.2.6

### OS/Browsers version
win10

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/ecoo5vb3/1/](http://jsfiddle.net/ecoo5vb3/1/)

### Steps to reproduce
选完：指南/设计原则/一致，之后，再选则“顶级”的时候，当前值数组长度为2，应该是只有 ['dingji'] 这个数组才对

### What is Expected?
选完：指南/设计原则/一致，之后，再选则“顶级”的时候，当前值数组长度为2，应该是只有 ['dingji'] 这个数组才对

### What is actually happening?
选完：指南/设计原则/一致，之后，再选则“顶级”的时候，当前值数组长度为2，应该是只有 ['dingji'] 这个数组才对

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/leopoldthecuber/ecoo5vb3/2/
没能重现你的问题，直接把当前值显示在页面上，最后是 `[ "dingji" ]`。你说的「当前值数组长度为2」是在哪里看出来的？

**Comment by asea1718** [comment]
哦，我搞错了是1.2.3版本的问题，1.2.6版本没问题，我更新到1.2.6了，这个链接可以看到具体的问题http://jsfiddle.net/ecoo5vb3/4/

**Comment by Leopoldthecoder** [comment]
是的，之前的版本有 bug。
