### ISSUE TITLE
[Feature Request] tooltips是否可以做到不参与鼠标交互？

### ISSUE THREAD

**Issue by andrewjavao** [ElemeFE/element#4087]
### Existing Component
是

### Component Name
ToolTip

### Description
期望达到的效果：tooltip实例在界面中不响应鼠标操作、不会遮挡其他页面的鼠标事件
痛点：
1、表格中的单元格使用tooltip，由于tips遮挡鼠标事件，滚动时就会引起滚动中断，因为tips随着滚动进入了鼠标
2、tips挡住其他控件，比如A组件在上方，B组件在下方，A组件的tips向下时，就必须先把鼠标上移让tips消失，然后避开A组件，才可以去B组件上看B的tips，UE很蛋疼

**Comment by andrewjavao** [comment]
官方例子 ：http://element.eleme.io/#/zh-CN/component/tooltip

**Comment by andrewjavao** [comment]
请问提供了这个功能么？我应该怎么寻找帮助？官方可以给一些建议么？

**Comment by Leopoldthecoder** [comment]
#4210 加了一个属性，可以控制是否在鼠标移动到 tooltip 本身时隐藏 tooltip，应该就能解决你所说的痛点了。
