### ISSUE TITLE
建议添加头部loading的效果

### ISSUE THREAD

**Issue by anshengme** [ElemeFE/element#409]
如题所示，其实就在在切换路由的时候在头部加上一个进度条，看起来也好看些，如图：
![qq 20161014023823](https://cloud.githubusercontent.com/assets/16428340/19362118/f3ab6b14-91b7-11e6-8c78-1e2773c6a96a.png)

**Comment by erguotou520** [comment]
建议你自己加个`NProcess`，可以参考这个`https://github.com/vue-bulma/nprogress`

**Comment by fishpaw** [comment]
这个暂时不会考虑，这说到底，是一种交互方式，甚或是一种设计风格，不能将之分解为基础的设计单元。
但是 loading 这块，目前确实做得比较孱弱，以后还有很大扩展空间。

**Comment by akaylh** [comment]
@anshengme  可以看下https://github.com/BosNaufal/vue2-loading-bar

**Comment by akaylh** [comment]
@anshengme  可以看下https://github.com/BosNaufal/vue2-loading-bar

**Comment by akaylh** [comment]
@anshengme  可以看下https://github.com/BosNaufal/vue2-loading-bar

**Comment by akaylh** [comment]
@anshengme  可以看下https://github.com/BosNaufal/vue2-loading-bar
