### ISSUE TITLE
[Bug Report]  Cannot read property 'handleClosePopper' of undefined

### ISSUE THREAD

**Issue by ayizhi** [ElemeFE/element#4090]
### Element UI version
1.2.8

### OS/Browsers version
chrome最新

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/44/](https://jsfiddle.net/pj71jkyw/44/)

### Steps to reproduce
不稳定复现，报错“Cannot read property 'handleClosePopper' of undefined。
根据官方文档提示，tooltip不应该出现disabled表单元素，所以在switch外加了span。
主要是不稳定复线，对流程也没什么影响，没找到原因，现在只是觉得应该是tooltip造成的，期待解决，或给出一些报这个handleClosePopper错误的原因。

### What is Expected?
不报错

### What is actually happening?
报错

**Comment by pengchongfu** [comment]
感觉这个复现链接完全不能复现。。。Tooltip 组件会在鼠标移开后200ms执行 `handleClosePopper` 函数，会不会是和 v-if 有关。

还有 Tooltip 的 diabled 表单元素是指原生的html元素，Switch组件不需要加 span 的。

**Comment by PanJiaChen** [comment]
https://github.com/ElemeFE/element/pull/4085

**Comment by Leopoldthecoder** [comment]
与 #3888 重复，已在 #4085 修复。

**Comment by schwann168** [comment]
更新 1.2.9 版本后，依然会报类似错误，但错误内容是：
```
TypeError: undefined is not an object (evaluating 'this.$refs.tooltip.handleClosePopper')
```
目前没法复现该问题，只是通过加入错误监控，监控到终端用户会偶发性抛出该错误。
