### ISSUE TITLE
[Bug Report] el-dialog在IE11bug:弹框内容被蒙层遮住，无法操作

### ISSUE THREAD

**Issue by Jianing666** [ElemeFE/element#4091]
### Element UI version
1.2.4

### OS/Browsers version
IE11浏览器

### Vue version
2.2.1

### Steps to reproduce
正常使用的el-dialog编译代码，
在IE11上面点击对话框，对话框内容会被蒙层盖住，有时候点击一次出不来，就再点几次或者换个对话框点，出现频率很高
![qq 20170410142234](https://cloud.githubusercontent.com/assets/22737356/24855616/c3044348-1e14-11e7-9ccf-c77a9f2c1fe3.png)

### What is Expected?
希望能有大神给一个解决办法，项目只允许用IE11浏览器使用，麻烦了！

**Comment by Leopoldthecoder** [comment]
试一下官方文档的 Dialog 有没有这个问题，如果没有问题请提供在线 demo。

**Comment by Jianing666** [comment]
在线demo不方便提供，比较复杂，这个是在一个el-table里面 点击按钮-->弹框出来的时候会这样的

**Comment by Jianing666** [comment]
IE11是不是不支持在线demo测试，我把项目中用到的表格demo从element的例子中直接复制过去，结果是这样的
https://jsfiddle.net/api/post/library/pure/
![qq 20170410181433](https://cloud.githubusercontent.com/assets/22737356/24857071/938b3676-1e19-11e7-8a8e-2efb80604afe.png)

**Comment by Leopoldthecoder** [comment]
可以用其他浏览器编辑好 demo，然后在 IE 11 里打开。
还是需要一个在线 demo，你可以把无关代码删除，保留一个最小可重现问题的版本。

**Comment by Jianing666** [comment]
@Leopoldthecoder  通过子组件实现的通信也可以在线演示吗？弹框是写在子组件里面的，表格在父组件里。我试了简易的在同一个里面没问题， 但我这个项目不是这样的。恕我愚钝，可不可以指导一下

**Comment by Reson-a** [comment]
项目也用了大量的dialog没遇到这个问题
个人习惯弹框尽量写在父组件里
有些东西会导致定位失效，比如transform

**Comment by Jianing666** [comment]
@Reson-a  @Leopoldthecoder 我发现每次点击不同弹框，z-index都在动态累加，并且在开发工具（F12）下，点击DOM资源管理器中元素的标签展开，弹框自己就又正常了，代码中没有任何改变，这个是不是IE的渲染顺序什么影响到了呢？这样的话使用者还是没办法用。。不知道什么原因

**Comment by Leopoldthecoder** [comment]
z-index 动态累加是对的。
「点击DOM资源管理器中元素的标签展开，弹框自己就又正常了」，看上去是浏览器的问题。另外，如果和 #4316 一样，你是把 Dialog 写在 Table 内部的话，建议按我在 #4316 回复的方法处理。

**Comment by Jianing666** [comment]
@Leopoldthecoder 弹框是写在table外面的，问题已经解决了，就是transform的问题，谢谢！

**Comment by yamateH-ch** [comment]
请问怎么解决的啊，我这里也是遇到这样的情况
路由用了
<transition name='fade' mode='out-in'>
	<router-view></router-view>
</transition>
就出现了

**Comment by Jianing666** [comment]
@yamateH-ch 就是把transition去掉了 路由继续用，在IE上就好了

**Comment by yamateH-ch** [comment]
主要事ie也想要这种效果，去掉了就没了有

**Comment by Jianing666** [comment]
这个我就不知道了，试试其他的解决办法，比如在css上面写这种效果呢

**Comment by juny1zhang** [comment]
太厉害了！

**Comment by hnyanzijun** [comment]
我也出现了这样的情况，求解决方案

**Comment by tianxiaofeng747** [comment]
假如dialog的父元素 有定义  position: relative;  overflow:hidden; 的话，而且正好它的父元素不太大，那么在ie11中弹出dialog会有问题 （弹出层不会超过父容器的边界）

**Comment by cfangxx** [comment]
原因是什么?

**Comment by lllllxt** [comment]
给dialog加上` append-to-body` 属性似乎也可以解决这个bug, 懒得一个个加的话, 可以在`Vue.use(Element);`之前加 `Element.Dialog.props.appendToBody.default = true;` , 这样所有el-dialog的append-to-body都默认为true了,  ( 都2021了 还要兼容IE 真**惨💩 )
