### ISSUE TITLE
dialog中的远程获取数据的el-select的option 经常会被挡住

### ISSUE THREAD

**Issue by xnumb** [ElemeFE/element#410]
在dialog中使用表单 其中有el-select 带有远程检索数据的属性 输入字符的时候 在network中能看到有结果 但是 结果不显示 然后我按 方向键 下 按钮 回车 会选中此项 也就是说 划出的option 被挡住了

chrome 53
element rc7
vue 2.0.2

**Comment by xnumb** [comment]
前几个版本貌似没这个问题

**Comment by xnumb** [comment]
好像是我样式覆盖的问题 重新覆盖一下就好了

**Comment by xnumb** [comment]
还是有这个问题 包括 正常的el-select 也是这种情况 只要包含在 dialog中 就基本上会这样

**Comment by QingWei-Li** [comment]
目前 dialog 和弹出层，其实用的都是 vue-popup，那么 zIndex 是自增的，只是 rc7 这版 build 的时候出现问题没发现导致弹出层有可能会被 dialog 覆盖。

**Comment by xnumb** [comment]
谢谢

**Comment by 6gunner** [comment]
所以问题的解决方案是什么？？更新版本？
