### ISSUE TITLE
[Bug Report] datepicker disabledDate这个配置不能动态设置

### ISSUE THREAD

**Issue by huadong1989** [ElemeFE/element#4101]
### Element UI version
1.2.8

### OS/Browsers version
Mac And Windows

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/ho0vppo7/](https://jsfiddle.net/ho0vppo7/)

### Steps to reproduce
默认时间初始化禁用小于2017-04-12的时间，点击更新时间后把警用时间改成小于2017-04-18时间，但再次选择默认时间时还是禁用小于2017-04-12的时间，应该禁用小于2017-04-18的时间

### What is Expected?
禁用时间是可以动态设置的

### What is actually happening?
不能动态设置禁用时间

**Comment by liyangworld** [comment]
改成这样
 var pre_cDate = new Date('2017-04-12');
        var Main = {
            data() {
                return {
                    cDate: pre_cDate,
                    pickerOptions1: {
                        shortcuts: [{
                            text: '今天',
                            onClick(picker) {
                                picker.$emit('pick', new Date());
                            }
                        }, {
                            text: '昨天',
                            onClick(picker) {
                                const date = new Date();
                                date.setTime(date.getTime() - 3600 * 1000 * 24);
                                picker.$emit('pick', date);
                            }
                        }, {
                            text: '一周前',
                            onClick(picker) {
                                const date = new Date();
                                date.setTime(date.getTime() - 3600 * 1000 * 24 * 7);
                                picker.$emit('pick', date);
                            }
                        }]
                    },
                    value1: '',
                    value2: '',
                };
            },
            computed: {
                pickerOptions0: function () {
                    return {
                        disabledDate(time) {
                            console.log('1');
                            return time.getTime() < this.cDate - 8.64e7;
                        }
                    }

                }
            },
            methods: {
                updateDate: function () {
                    this.cDate = new Date('2017-04-18');
                }
            }
        };
        var Ctor = Vue.extend(Main)
        new Ctor().$mount('#app')

**Comment by jinglf000** [comment]
@liyangworld 思路很对，但是这样写仍然是有问题的，返回的`disabledDate` 函数中的 `this`仍然是子组件的`this`；因此需要首先把值计算出来；代码如下：

```
...
 pickerOptions0: function () {
	const dateFlag = this.cDate;
	return {
		disabledDate(time) {
			console.log('1');
			return time.getTime() < dateFlag  - 8.64e7;
		}
	}
}
...
```

**Comment by luchanan** [comment]
@jinglf000 这个disabledDate只有在日期发生改变的时候才会触发，如果值没有发生改变的话，不被触发，请问有没有一种方法可以是点击input框的时候触发disabledDate呢？thanks

**Comment by luchanan** [comment]
已解决

**Comment by belief-cyf** [comment]
https://github.com/ElemeFE/element/issues/2599#issuecomment-441511685
