### ISSUE TITLE
[Feature Request] input输入 enter键后 无法触发@keyup.enter

### ISSUE THREAD

**Issue by oGZo** [ElemeFE/element#4102]
### Existing Component
是

### Component Name
input

### Description
input输入 enter键后 无法触发@keyup.enter
发现原因是用了<el-input @keyup.enter="login"/>
如果改成普通的<input @keyup.enter="login"/>是没问题的

**Comment by Leopoldthecoder** [comment]
这是一个 bug report，请不要因为不想写在线 demo 而强行选择 Feature Request。另外，提 issue 请仔细阅读 FAQ。
