### ISSUE TITLE
[Feature Request] Allow the timepicker to not display seconds and not display the spinner for seconds

### ISSUE THREAD

**Issue by robodude** [ElemeFE/element#4104]
### Existing Component
Yes

### Component Name
DateTimePicker

### Description
The time.vue file has a class called 'has-seconds' which is always true. It would be nice if the format could be passed in to this component via a props from date.vue so that the showSeconds computed could result in false.

Here is the file in question:
https://github.com/ElemeFE/element/blob/eac95e99c48230c31f8953fa464781145a82196a/packages/date-picker/src/panel/time.vue

This could technically be a bug -  as I believe this would have been the original intent behind the 'has-seconds' class.

**Comment by eschmar** [comment]
#3808 duplicate

**Comment by syn-zeta** [comment]
@Leopoldthecoder Recommend closing as it duplicates 3808.
