### ISSUE TITLE
[Bug Report] [docs] 页面被 cache 了，看不到新文档

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#4108]
### Element UI version
1.2.8

### OS/Browsers version
new

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
如题，文档的页面都 cache 了，这是不让我看新文档的节奏....

你们饿了么 m 站的 `pwa` 实践咋地不借鉴来实践一下呢。移调 `applicationCache` 多好

![ele-cache](https://cloud.githubusercontent.com/assets/2276421/24892270/e2da5f10-1ead-11e7-93df-46972d1e2e0d.png)

![ele-version](https://cloud.githubusercontent.com/assets/2276421/24892287/f55ab9be-1ead-11e7-90ea-32828a162aad.png)

### What is Expected?
不缓存页面；
应用 service work 代替 applicationCache

### What is actually happening?
页面缓存，新文档得不到更新

**Comment by AaronChen2012** [comment]
@renxia 怎么解决啊？非要手工刷新下吗？

**Comment by renxia** [comment]
手工刷也不行，可以禁止掉缓存刷一下，再开启。或者清理浏览器所有缓存

**Comment by AaronChen2012** [comment]
@renxia 我这边遇到的问题是Chrome浏览器，每次更新了要用户刷新浏览器，不刷新。必须要手工刷新！比较郁闷，还没想到怎么解决

**Comment by Leopoldthecoder** [comment]
1.2.5 还是 1.2.6 就已经把 applicationCache 去掉了。@AaronChen2012 你清下缓存就行。

**Comment by xiaolongyuan** [comment]
一样的问题
控制台禁用下缓存 再放开好了
