### ISSUE TITLE
[Feature Request] 增加表格头固定属性，而不是依赖height属性

### ISSUE THREAD

**Issue by xunonxyz** [ElemeFE/element#4109]
### Existing Component
是

### Component Name
table

### Description
有些场景需要使表格自适应浏览器高度，也就是表格占据父容器100%的高度，但这个时候无法把表格头设置为固定

**Comment by xunonxyz** [comment]
没有，就是将表格设置成为父容器高度100%的时候如何设置为固定表格头

**Comment by xunonxyz** [comment]
没看代码，不过这个应当是个大众化的需求，让熟悉的人改吧，万一不行再自己动下

**Comment by wfesorg** [comment]
把el-table外面的div设置高度100%就可以满足这个需求

**Comment by mcdongWang** [comment]
max-height 可以设置为 calc(100vh - 200px)

200px 是上下的空白区域

**Comment by wangtjwork** [comment]
请问各位如何将表格设置为父容器高度100%？我不需要固定表格头。试图使用jquery 在css里加height会导致上下滚动条出现在第一列的末尾而且只能调整第一列。父容器目前是position absolute， top和down规定好的。

**Comment by Xiangyun-Xia** [comment]
我给table设置了height=“100%”，使表头固定，又写了style=“height:100%;width:100%”;使表格内容部分能出现滚动条，满足了我的使用场景，不知道有没有解决上面各位的问题。
