### ISSUE TITLE
[Bug Report] Table-column组件中，如何平衡component复用和props-bingding关系

### ISSUE THREAD

**Issue by anhzhi** [ElemeFE/element#4115]
### Element UI version
1.2.8

### OS/Browsers version
Windows

### Vue version
2.1.8

### Reproduction Link
[http://jsfiddle.net/0mjz6v8r/13/](http://jsfiddle.net/0mjz6v8r/13/)

### Steps to reproduce
在某一个action中对table-columns中某一项修改属性formatter
```
          this.colModels[0].formatter = function(){return 'date value2'}
```

### What is Expected?
table-column能够对formatter这个属性进行绑定(can observable)
能够重新渲染table-cell

### What is actually happening?
table-column未能够绑定formatter这个属性，修改formatter之后，不会重新渲染对应的table-cell

**Comment by anhzhi** [comment]
问题： 如何使得 el-table-column 的 :formatter 支持响应式

参考issue: #2578
cinwell.li 给了一个solution: 用key 绑定 col-object
这样 只要对this.columns数组重新Assign，col-object都会改变，
那么Table-column就不会重用，也就是强制重新create

这个成本似乎比较高，如果只是修改column.formatter呢?
参考：http://jsfiddle.net/0mjz6v8r/13/

我看了table-column.js的源码，建议做一个简单的改动
对props中的className，labelClassName，formatter等需要绑定的属性进行watch就可以改善
该组件的props-bingding关系了

PS：将formatter绑定到一个vue实例的method上（包括将闭包绑定到vue实例上），也是可以搞定绑定关系的，这里不做展开

**Comment by furybean** [comment]
在最新版本中依然存在：http://jsfiddle.net/0mjz6v8r/24/

先标记为 Bug。

**Comment by Leopoldthecoder** [comment]
Fixed in #10184
