### ISSUE TITLE
[Feature Request] Add Header

### ISSUE THREAD

**Issue by PhillippOhlandt** [ElemeFE/element#4116]
**Note:** I get a timeout on https://eleme-issue.surge.sh so can't use it.

It would be nice to have a Header component. The closest I can get right now is the [Top Bar](http://element.eleme.io/#/en-US/component/menu) but a real header (e.g. as on your docs) would be nice.

**Comment by PhillippOhlandt** [comment]
You probably should update your issue template with a valid link then ...

**Comment by BigChief45** [comment]
I was thinking just the same thing.

**Comment by Leopoldthecoder** [comment]
Sorry, we'll see what's going on. Meanwhile you can use https://elementui.github.io/issue-generator instead.
