### ISSUE TITLE
[Feature Request] Tabs 动态增减标签页的content可以支持html元素的内容

### ISSUE THREAD

**Issue by maowenjun** [ElemeFE/element#4119]
### Existing Component
是

### Component Name
Tabs标签

### Description
Tabs标签 目前的content的值是字符，但是我们需要每个tab有一个html页面，并且可以新增和关闭。

**Comment by maowenjun** [comment]
http://element.eleme.io/#/zh-CN/component/tabs

**Comment by pengchongfu** [comment]
@maowenjun 不能用 v-html 实现吗？https://jsfiddle.net/bksw3yoc/

**Comment by baiyaaaaa** [comment]
不太理解直接把一大段html放进data里是出于什么样的考虑
