### ISSUE TITLE
Tooltip样式优化建议

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#412]
rc7后更改了popover的实现方式，默认挂载到`body`，但是建议`center`时箭头不要用js去计算，直接css样式控制，否则有时会出现计算差错的情况，如下图
![tooltip](https://cloud.githubusercontent.com/assets/7945757/19373101/f6fe5f42-91f3-11e6-83d7-5f168fd47904.png)
另外，关于`.el-table td .cell`样式里的`line-height:40px;`个人觉得不太好，如果表格内部有很多元素时，每个元素可能都得去修改`line-height`，如果改成`padding`可能会好点。

**Comment by acelan86** [comment]
+1

**Comment by erguotou520** [comment]
同理，`popover`也有这样的问题

**Comment by QingWei-Li** [comment]
1. table 问题会修复，目前正在重构 table
2. 不在中间的问题应该是生命周期顺序的问题导致 arrow 没计算正确，已经修复 https://github.com/ElemeFE/element/pull/442
