### ISSUE TITLE
[Bug Report] Cascader 级联选择器 clerable属性无法清空选项

### ISSUE THREAD

**Issue by Alice2222** [ElemeFE/element#4123]
### Element UI version
1.2.4

### OS/Browsers version
win10*64/chrome 57.0

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/baqep2Lz/1/](http://jsfiddle.net/baqep2Lz/1/)

### Steps to reproduce
点击清空按钮无法清空

### What is Expected?
点击清空按钮清空选项

### What is actually happening?
点击清空按钮无法清空选项

**Comment by Leopoldthecoder** [comment]
与 #4084 重复。
