### ISSUE TITLE
[Feature Request] Add Container Component

### ISSUE THREAD

**Issue by PhillippOhlandt** [ElemeFE/element#4125]
### Existing Component
No

### Component Name
Container

### Description
The existing grid components are very nice. The only thing I miss is a container component to center the whole page and limit to a certain width.

**Comment by BigChief45** [comment]
This should probably be done using the Card component. However, I must say that the Card component has a lot of limitations right now.

**Comment by PhillippOhlandt** [comment]
@BigChief45 semantically, the Card component wouldn't be a good fit.

@element-bot just a basic container, like from [bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_grid.scss#L5-L22) or from your documentation page. Centering the whole content (grid) and providing some margin on mobile if needed.

**Comment by baiyaaaaa** [comment]
@PhillippOhlandt I think the container is just a "class"? So it's not a component

**Comment by BigChief45** [comment]
@PhillippOhlandt Ah I understand what you mean now. And yes, I believe this should be included.

**Comment by baiyaaaaa** [comment]
@BigChief45 @PhillippOhlandt 
```css
.container {
  width: 1100px;
  margin: 0 auto;
}
```
I'm not sure what you mean. 
But if it's just a class like above,
i think it's should be maintain in your project

**Comment by BigChief45** [comment]
@baiyaaaaa Bootstrap and many other frameworks come with classes similar to `container`. This eliminates the need to constantly define it like you did above. I believe this should be included in Element's layout's CSS.

**Comment by Leopoldthecoder** [comment]
@BigChief45 One thing Element is different from Bootstrap is that Element is just a component library, you can see we don't provide any classes.

**Comment by BigChief45** [comment]
@Leopoldthecoder I understand. But this means that additional frameworks will have to be added to a project just to have control of a layout and basic typography styles.

Is there no plan to include these kinds of things into Element?

**Comment by Leopoldthecoder** [comment]
@BigChief45 To have control of a layout is, in my opinion, not too much work, especially when you're already using `el-row` and `el-col`. Like what we discussed in this issue, the container has only two lines of CSS. So no, we have no plan to include such things.

Plus, I think other modern component libraries don't provide these things either. Please let me know if you find some of them do, and I will take a look.
