### ISSUE TITLE
[Bug Report] table array行改变顺序 但是table没有刷新  比如 置顶

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4126]
### Element UI version
1.2.8

### OS/Browsers version
Mac/safari

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/7xqrbyxu/](https://jsfiddle.net/7xqrbyxu/)

### Steps to reproduce
无

### What is Expected?
无

### What is actually happening?
无

**Comment by jwenjian** [comment]
it's not a bug, vue wouldn't know the array changes if you do something like: 
```
someArray[0] = newValue;

```
see this update: https://jsfiddle.net/7xqrbyxu/1/

**Comment by subo-romens** [comment]
谢谢
