### ISSUE TITLE
建议：table增加空数据提示

### ISSUE THREAD

**Issue by acelan86** [ElemeFE/element#413]
table body中建议添加没有数据提示，不然光留一个head感觉坏了一样

**Comment by erguotou520** [comment]
+1
可以配合`v-loading`，应该提供更多的可扩展性，空数据可能是获取数据失败，也可能确实是空数据，表格这块是最复杂的。
现行的方案就是`v-if`，如果为空，显示一个提示类型的元素在页面上

**Comment by acelan86** [comment]
咱俩是组团来给element生🐒的，哈哈哈哈哈

**Comment by fishpaw** [comment]
嗯，确实需要添加一个空数据状态，这是设计上的小疏漏。应该只会提供一个默认状态，更多的拓展性由开发者决定。

**Comment by furybean** [comment]
RC8 已经支持。
