### ISSUE TITLE
发现bug，关于el-dialog对话框与vuex的兼容性问题

### ISSUE THREAD

**Issue by sdlddr** [ElemeFE/element#4133]
el-dialog标签如果封装在子组件中，并且 v-model="dialogVisible"中的dialogVisible是来自于vuex的store的话，那么对话框打开一次再关闭后，第二次就打不开了。这时发现vuex的store.state中，dialogVisible一直为true。
通过打日志时发现，第一次打开前，dialogVisible为false，后面几次点击触发打开对话框事件的按钮，发现
dialogVisible一直为true，而窗口始终没打开

**Comment by insub** [comment]
这不是bug
vuex的store不允许直接修改，所以把dialog组件的store的state绑定到v-model是无效的，因为close触发无法直接修改store中的数据
