### ISSUE TITLE
[Feature Request] [dialog]建议  size 增加大小响应式的动态计算选项

### ISSUE THREAD

**Issue by renxia** [ElemeFE/element#4134]
### Existing Component
是

### Component Name
dialog

### Description
当前 dialog 组件的 size 属性可选值有 `tiny/small/large/full`
但对于各种不同的屏幕宽度来说，没有一种能够在任何页面大小下都合适的方式

不得已我们都是类似这么来做的：

```js
        function calcDialogSize() {
            let size = 'tiny';
            const width = window.innerWidth;

            if (width < 768) {
                 size = 'full';
            } else if (width < 1024) {
                size = 'normal';
            } else if (width < 1500) {
                size = 'small';
            }

            return size;
        }
```

但是每一个地方都这么去写又很麻烦。
所以若能增加一种 `dynamic` 的动态计算类型就好了

**Comment by Leopoldthecoder** [comment]
你觉得怎样的 API 比较合适？

**Comment by renxia** [comment]
基于当前需求，size 属性增加一种如示例计算方式的可选项就好。
其实即使是 tiny和small这样的类型，也应有个最小宽度或 达到阈值使用固定比例（如96%）才合适。否则对于较小的屏幕几乎都挤到一块去了

**Comment by DrunkLife** [comment]
size  接受 string或者 function 两种参数

**Comment by Leopoldthecoder** [comment]
其实可以用 `custom-class` 给 Dialog 一个类名，然后在媒体查询里给这个类写宽度就行。
