### ISSUE TITLE
[Bug Report] when clear datepicker value return to undefined rather than empty string

### ISSUE THREAD

**Issue by horans** [ElemeFE/element#4135]
### Element UI version
1.2.8

### OS/Browsers version
win10(x64)/chrome59(x64)

### Vue version
2.2.6

### Reproduction Link
[http://codepen.io/horan/pen/dWbWZB](http://codepen.io/horan/pen/dWbWZB)

### Steps to reproduce
1. select a date
2. clear the date

### What is Expected?
date value go back to default empty string

### What is actually happening?
date value go to undefined
(not sure if it's intentional)

**Comment by Caijt** [comment]
我也是这个问题，手动把日期控件值删除后，不为空的检测失效了，连elementui官网的例子也是如此
http://element.eleme.io/#/zh-CN/component/form
到那个表单验证那里，先选择一个日期，然后手动删除掉它（不是按清空按钮），然后点立即创建，并不会提示为空提醒
