### ISSUE TITLE
[Bug Report] Having a fixed header on el-table with another fixed expandable subtable el-table results in a loss of hovering behavior and odd offsetting of sub table rows.

### ISSUE THREAD

**Issue by TLX3** [ElemeFE/element#4139]
### Element UI version
1.2.8

### OS/Browsers version
Chrome 57

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/tdl2116/spw5hsga/](https://jsfiddle.net/tdl2116/spw5hsga/)

### Steps to reproduce
Open expandable and notice that when hovering over a cell doesn't result in entire row. Also, when you open multiple expandable rows, the rows start to offset further down.

### What is Expected?
The entire subtable is expected to behave as the larger table with hovering and row alignment.

### What is actually happening?
Hovering over the fixed header column of the subtable doesn't cause the entire row to be hovered. The row elements of the sub tables are out of alignment and worsen as you open more expandable rows.

**Comment by WenqianZhao** [comment]
我是这个issue发起人的同事，这里再用中文详细阐述一下问题所在。我们将el-table作为主表格，使用了固定列和展开行的功能，同时在展开行的内容里放置了另一个子表格（也是el-table）。现在的问题是：（1）将鼠标放置在子表格的某一个单元格上时，并没有选中整个行，而是似乎被固定列的那一条分界线给隔开了。也就是说只能选中某一行的第一列，或者选中某一行除第一列外的所有列。（2）当同时展开多个行时，表格（包括主表格和子表格）被稍稍错开了，错开的位置正是固定列的分界线。
请大家帮忙解决一下这个问题，谢谢！
