### ISSUE TITLE
MessageBox弹出时body上的padding-right

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#414]
是因为当页面有滚动条时避免出现闪动的原因么？但是每个页面的滚动条宽度可能不一致（可自定义），而且有的页面可能没有滚动条呢，这时候页面也会有闪动了

**Comment by Leopoldthecoder** [comment]
是为了避免闪动。在 MessageBox 出现前会自动计算当前页面的滚动条宽度，并将其赋值给 padding-right。如果页面没有滚动条，计算出来的宽度就是 0，此时就不再设置 padding-right。

**Comment by erguotou520** [comment]
我的页面是一个类似于圣杯布局的页面，页面整体占高100%，中间区域可滚动，本不应该加上`padding-right`的，但是我弹出模态框时确实加了

**Comment by Leopoldthecoder** [comment]
好，我看一下

**Comment by Leopoldthecoder** [comment]
fixed in #451
