### ISSUE TITLE
[Feature Request] DatePicker默认值

### ISSUE THREAD

**Issue by wacky6** [ElemeFE/element#4143]
### Existing Component
是

### Component Name
DatePicker

### Description
允许设置DatePicker默认值

期望：空的DatePicker点开时可以指定显示的月份

现在：显示当前月份

场景：现在是4月，活动在7月举行，需要预订酒店。希望DatePicker默认显示在7月方便选入住时间

### Example
```HTML
<el-date-picker
  v-model="value1"
  type="date"
  placeholder="选择日期"
  :picker-options="pickerOptions0"
  :default-date="new Date('2017-07-01')"
/>
```

<img width="309" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9319556/24922763/fd66acb6-1f21-11e7-8d89-2decfdba1376.png">

**Comment by wacky6** [comment]
做了一个简单粗暴的版本：https://github.com/wacky6/element/commit/d61cb4e1c44849a7bcd730d9bac72e2afb05455d

想讨论一下：默认值放pickerOptions里面还是直接作为prop？

**Comment by wacky6** [comment]
另一个实现：https://github.com/wacky6/element/commit/076205173a48256baf27ffab9bbe34ef30505abe

**Comment by Leopoldthecoder** [comment]
本来就支持默认值：https://jsfiddle.net/leopoldthecuber/nawuxvgz/

**Comment by wacky6** [comment]
我的意思是value为空，打开picker的时候，显示指定的月份/日期。
Demo： https://jsfiddle.net/a0hag1cv/

**Comment by Leopoldthecoder** [comment]
哦，理解你的意思了。既然功能已经实现了，那么欢迎可以提个 PR。

**Comment by wacky6** [comment]
嗯。我再考虑考虑有没有更优雅的实现方法。

**Comment by 992forever** [comment]
当type为daterange时，也就是日期为范围时，怎么设置默认值

**Comment by wacky6** [comment]
daterange默认值可以修改`packages/date-picker/src/panel/`里面的相关组件代码。实现思路和date应该是一样的。

**Comment by athena0304** [comment]
daterange默认值是一个数组

**Comment by cassieLuo** [comment]
daterange 能不能默认设置当前月在右边，现在默认是当前月在左边，右边是下一个月

**Comment by wy-ang** [comment]
@wacky6 @992forever 同问如何在type为daterange时，怎么设置默认值，难道说要修改源码？

**Comment by wacky6** [comment]
@wy-ang date-range 要改 panel/date-range 的实现

**Comment by bengirl** [comment]
@cassieLuo 你这个问题搞定了吗？我也想这么弄，也不知道这么搞。

**Comment by mqliutie** [comment]
default-value | 可选，选择器打开时默认显示的时间 | Date | 可被new Date()解析 | —
-- | -- | -- | -- | --

官网上的这种方式无效
