### ISSUE TITLE
[Bug Report] IE9下,table表格出现兼容性错误

### ISSUE THREAD

**Issue by chenyufa** [ElemeFE/element#4145]
### Element UI version
1.2.8

### OS/Browsers version
win7/IE9

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
表格是能够正常显示,但是当鼠标移上table列时,控制台抛出异常
[Vue warn]: Error in watcher "store.states.hoverRow"
(found in component )

我查看了下,估计是IE9不支持hover伪对象,引起的

### What is Expected?
能够正常现实和使用表格

### What is actually happening?
能够正常现实,但是由于抛出异常后 一些点击事件无法正常使用

**Comment by Leopoldthecoder** [comment]
由于未更新 demo 链接，所以先关掉了。
