### ISSUE TITLE
[Bug Report] [AutoComplete] custom-item errorly rendered twice in the dropdown box

### ISSUE THREAD

**Issue by XfLoops** [ElemeFE/element#4147]
### Element UI version
1.2.8

### OS/Browsers version
macOS Sierra

### Vue version
2.1.10

### Reproduction Link
:point_right:  [http://jsfiddle.net/XfLoops/zs6b3ooh/1/](http://jsfiddle.net/XfLoops/zs6b3ooh/1/)

### Steps to reproduce

In using AutoComplete, refer the name of a predefined global component by custom-item

### What is Expected?
the dropdown box would display the reffered component content only ONCE :heavy_check_mark:

### What is actually happening?
the dropdown box would display the customized component content TWICE  :x:

![image](https://cloud.githubusercontent.com/assets/7624050/24941615/60d6d936-1f7e-11e7-8bb6-d1378c438de9.png)

**Comment by Leopoldthecoder** [comment]
那是因为你的 results 有两个元素啊……
```javascript
 var results = [
  { "value": "vue", "link": "https://github.com/vuejs/vue" },
  { "value": "element", "link": "https://github.com/ElemeFE/element" }
]
```
你换成一个试试。
