### ISSUE TITLE
[Bug Report] 使用expand嵌套table时，stripe样式问题

### ISSUE THREAD

**Issue by uedkx** [ElemeFE/element#4150]
### Element UI version
1.2.8

### OS/Browsers version
chrome 58

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/jdfkhqo4/](https://jsfiddle.net/jdfkhqo4/)

### Steps to reproduce
点击箭头展开更多

### What is Expected?
父表格与子表格的:nth-child(2n)应该要区分

### What is actually happening?
样式出现问题

**Comment by uedkx** [comment]
@Leopoldthecoder 现在的Bug是，如果展开父表格的第一行，那:nth-child(2n)匹配的偶数行其实是第一行的子表格，而不是父表格的第二行。

**Comment by Leopoldthecoder** [comment]
Fixed in #4873
