### ISSUE TITLE
[Bug Report] el-tree 无法修改子节点内容

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4151]
### Element UI version
1.2.8

### OS/Browsers version
Mac/safari

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/L25r1smq/2/](https://jsfiddle.net/L25r1smq/2/)

### Steps to reproduce
无

### What is Expected?
无

### What is actually happening?
无

**Comment by pengchongfu** [comment]
控制台在报错啊。。data 之前加 this

**Comment by subo-romens** [comment]
好的谢谢，Demo已经改了 我看好使 但是 我的项目里data 是放在VueX的store里  在VueX新增 和 删除data时 el-tree 都会变   但是如果只是修改Data值的话  el-tree 不会变

**Comment by DivXPro** [comment]
恩，我在使用的时候也存在同样的问题。修改了children中  lable值 但是html不会重新渲染

**Comment by Leopoldthecoder** [comment]
目前看来是没有问题的：https://jsfiddle.net/L25r1smq/3/

@subo-romens @DivXPro 有问题请准备 demo。
