### ISSUE TITLE
动态增减表单项,增加自定义校验规则

### ISSUE THREAD

**Issue by zhaijg** [ElemeFE/element#4152]
动态增减表单项的同时需要增加自定义校验规则,自定义的验证方法总是报 没有方法的错误
 :rules="[{ validator: validateIncomeCompletion, trigger: 'blur' }]">

validateIncomeCompletion是我自定义的验证方法, 不明白validateIncomeCompletion应该写到什么地方

**Comment by yamateH-ch** [comment]
请问上面的兄弟你最后怎么解决的，我也遇到了这类问题

**Comment by songxiaowei112** [comment]
同问，我也遇到了

**Comment by xs47968224** [comment]
官方使用手册上没有说，但变通一下，我的解决方案：
https://jsfiddle.net/xs47968224/29n5cdjm/3/#&togetherjs=yKonoBnMgu
