### ISSUE TITLE
[Feature Request] Add text to the carousel indicator buttons

### ISSUE THREAD

**Issue by paul-blundell** [ElemeFE/element#4153]
### Existing Component
Yes

### Component Name
Carousel

### Description
The small lines under the carousel are buttons, it would be very useful if we could add text to those buttons, a title of the carousel item such as Offers, etc.
See this example:

![screen shot 2017-04-12 at 09 09 34](https://cloud.githubusercontent.com/assets/1451631/24947952/9900ee50-1f60-11e7-9984-93eb4201e256.png)

**Comment by Leopoldthecoder** [comment]
We'd like to keep Carousel simple, so no plan to add this.

**Comment by paul-blundell** [comment]
Unless I'm mistaken, this won't add any extra complexity and would be a completely optional thing.
You can just add a prop to the carousel-item for label and then modify main.vue so when it displays the indicators it adds the value to the button:

`<button class="el-carousel__button">{{ item.label }}</button>`

Or, can you let me know how I can create a carousel similar to the following. Element has so far been fantastic and would prefer to stick with it for this too.

![screenshot 2017-04-17 at 16 42 14](https://cloud.githubusercontent.com/assets/1451631/25094033/1d260dac-238d-11e7-837b-daebd7de1baf.png)

**Comment by chixiaoxiao** [comment]
我也是有碰到这个问题，想要自己设置下面按钮的样式显示效果之类的，横线暂时不太适用，不能和其他的一样自己需要的话，自己编辑一段替换插入嘛？

**Comment by paul-blundell** [comment]
I have submitted a pull request for this, https://github.com/ElemeFE/element/pull/4317

Hopefully the developers will consider it. It would be a completely optional feature.
