### ISSUE TITLE
[Bug Report] tree的"自定义节点内容"在线demo跑不起来

### ISSUE THREAD

**Issue by legendjslc** [ElemeFE/element#4158]
### Element UI version
1.2.8

### OS/Browsers version
WIn10

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/api/post/library/pure/](http://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
打开以下地址即可看到：http://jsfiddle.net/api/post/library/pure/

### What is Expected?
正常显示树节点文字

### What is actually happening?
树节点文字为空

**Comment by legendjslc** [comment]
找到原因了，应该是没有配置jsx的原因。
新的链接： http://jsfiddle.net/e3gu4fg8/
或者从以下网址中跳转过去：
http://element.eleme.io/#/zh-CN/component/tree

这是官方的例子

**Comment by Leopoldthecoder** [comment]
![image](https://cloud.githubusercontent.com/assets/10095631/24987673/cae6c5d8-2033-11e7-8c4e-e0275bafa899.png)
