### ISSUE TITLE
升级element-ui - 1.0.0-rc.7 报错如下，element-ui - 1.0.0-rc.6则不会

### ISSUE THREAD

**Issue by perfectyang** [ElemeFE/element#416]
ElementUI version 1.0.0-rc.7 
Vue 2.0.2 

路由切换时就会出现这种报错，试了几个版本，vue2.0.2 与  ElementUI version _1.0.0-rc.6，不会出现这种问题，刚升级报的错_ 
![image](https://cloud.githubusercontent.com/assets/8724828/19374840/7497867e-9201-11e6-95b7-8258d4c092e8.png)

**Comment by baiyaaaaa** [comment]
麻烦给出重现例子 https://jsfiddle.net/gmve9d3p/

**Comment by chachaxw** [comment]
我的也遇到了这个问题

**Comment by baiyaaaaa** [comment]
#474

**Comment by flyingzl** [comment]
建议同时把 vue等都升级到最新版本(2.0.3)，就没这个问题了

**Comment by chachaxw** [comment]
我的vue已经是2.0.3了，但是还是有那个问题，把transition去掉之后就没了。

**Comment by furybean** [comment]
@chachaxw transition 指的是？

**Comment by QingWei-Li** [comment]
好像 vue-router 的 transition 有问题？https://github.com/ElemeFE/element/issues/429#issuecomment-253974110

**Comment by chachaxw** [comment]
@furybean Vue2中自带的transition组件

**Comment by furybean** [comment]
标有 need repo 标签的 issue，如果 7 天没有收到任何 repo 的步骤或者 Demo，我们会做关闭处理。如果可以重现了，请再打开这个 issue。
