### ISSUE TITLE
[Bug Report] 按下Tab键无法使CheckBox获得焦点

### ISSUE THREAD

**Issue by bluejfox** [ElemeFE/element#4160]
### Element UI version
1.2.8

### OS/Browsers version
macOS Sierra 10.12.3／Chrome 版本 57.0.2987.133 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/32p61df3/1/](http://jsfiddle.net/32p61df3/1/)

### Steps to reproduce
1.点击活动名称输入框
2.按下Tab键

### What is Expected?
CheckBox可以通过按下Tab键获得焦点

### What is actually happening?
按下Tab键后，CheckBox无法获得焦点。

**Comment by ChuckFields** [comment]
@bluejfox  I am having the same issue. This was working not to long ago, but now tabbing skips over checkboxes. I'm trying to figure out when this feature broke. Also, tabbing does not work with switches, although i'm not sure it ever worked. Would be very nice to have. A lot of our users are keyboard crazy.

**Comment by bluejfox** [comment]
@ChuckFields I had been created pull request #4833 .

**Comment by Leopoldthecoder** [comment]
Fixed [here](https://github.com/ElemeFE/element/pull/4851/files#diff-cea6fda7a0a66629400ec8d7d9ad59c1R137)
