### ISSUE TITLE
[Bug Report] 表单验证规则rules的required属性和星号必填标识不能响应变化

### ISSUE THREAD

**Issue by zlab** [ElemeFE/element#4161]
### Element UI version
1.2.8

### OS/Browsers version
Chrome 55

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/zhanqi/tny1m2a0/4/](https://jsfiddle.net/zhanqi/tny1m2a0/4/)

### Steps to reproduce
切换验证规则的required=true，星号必填红色图标不会出现，但是表单验证生效了，
看了form-item的源码，发现星号必填红色图标是在form-item的mounted函数里设置的，所以不能响应

### What is Expected?
切换验证规则的required=true，星号必填红色图标不会出现

### What is actually happening?
切换验证规则的required=true，星号必填红色图标出现

**Comment by scscms** [comment]
将就先用着 [https://jsfiddle.net/tny1m2a0/5/](https://jsfiddle.net/tny1m2a0/5/)

**Comment by baiyaaaaa** [comment]
will be fixed in version 1.3.7
