### ISSUE TITLE
[Bug Report] el-input 的change事件中怎样获取事件对象

### ISSUE THREAD

**Issue by fei316** [ElemeFE/element#4162]
### Element UI version
1.2.8

### OS/Browsers version
chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/yzorykv0/1/](https://jsfiddle.net/yzorykv0/1/)

### Steps to reproduce
直接运行

### What is Expected?
event 为事件对象

### What is actually happening?
event为input输入框的值

**Comment by Leopoldthecoder** [comment]
这是 by design 的，`change` 事件的参数就是绑定值。想要事件对象的话直接 `@change.native`。
