### ISSUE TITLE
[Bug Report] 表单 数字类型验证 不准确

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#4164]
### Element UI version
1.2.8

### OS/Browsers version
Win 10,Chrome 59

### Vue version
2.2.6

### Steps to reproduce
1000asdasdas  数字在前后面字母的 不能检测
v-model.number 转换的时候会把'1000asdasdas' 转成1000

### What is Expected?
检测更准确

### What is actually happening?
检测更准确

**Comment by Leopoldthecoder** [comment]
无重现链接的 issue 会被直接关闭。
