### ISSUE TITLE
[Bug Report] 表单 数字类型验证 不准确

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#4165]
### Element UI version
1.2.8

### OS/Browsers version
Win10 Chrome 59

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/没有。官方文档例子就可以重现了](https://jsfiddle.net/没有。官方文档例子就可以重现了)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/form

 数字类型验证 
输入 1000asdasdas,没有检测到不是数字

v-model.number 转换的时候会把'1000asdasdas' 转成1000

### What is Expected?
检测更完善

### What is actually happening?
输入 1000asdasdas,没有检测到不是数字

**Comment by Leopoldthecoder** [comment]
Vue 的行为就是如此：https://jsfiddle.net/leopoldthecuber/6hvk2qLx/
