### ISSUE TITLE
1.0.0-rc.7 的 date-picker(range) 样式在选择框过小时会出现异常

### ISSUE THREAD

**Issue by francisfeng** [ElemeFE/element#417]
### ElementUI version
1.0.0-rc.7

### OS/Browers version
Windows 10 / Chrome 53

### Vue version
2.0.2

### Reproduction Link
![sp20161014_112907](https://cloud.githubusercontent.com/assets/1040288/19374965/6e5248d4-9202-11e6-8173-7ef1f2180ef6.png)

### Steps to reproduce
日期选择框和`el-picker-panel `元素的宽度是一致的，但当其太小（例图中是400px）而导致`el-picker-panel__body` 的 width 大于父元素`el-picker-panel`时，会出现样式异常。上一个版本没发现这个问题。

**Comment by perfectyang** [comment]
今天刚升级，这版本也发现不少问题啊

**Comment by Leopoldthecoder** [comment]
文档上 demo 是正常的，麻烦给一个可以复现的例子
