### ISSUE TITLE
[Feature Request] Tree 树形控件添加某些节点可以禁止选择的功能

### ISSUE THREAD

**Issue by plilion** [ElemeFE/element#4170]
### Existing Component
是

### Component Name
Tree 树形控件

### Description
Tree 树形控件添加某些节点可以禁止选择的功能

**Comment by plilion** [comment]
[http://element.eleme.io/#/zh-CN/component/tree](http://element.eleme.io/#/zh-CN/component/tree)
就这个组件在有checkbox时 有些可以禁止选择

**Comment by Leopoldthecoder** [comment]
与 #3551 重复。
