### ISSUE TITLE
[Feature Request] pagination 的 total 单位自定义

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#4174]
### Existing Component
是

### Component Name
pagination

### Description
pagination 单位的修改， 例如：我不想 说多少条， 我想说， 多少瓶。。。
<img width="658" alt="wx20170413-145808 2x" src="https://cloud.githubusercontent.com/assets/4468540/24993691/11a709d0-205a-11e7-9742-88a43fd91c00.png">

**Comment by jikkai** [comment]
汉语中对于数据使用的量词就是“条”，这个一般没有自定义的需求，看看有没有什么 hack 的方法

**Comment by QingWei-Li** [comment]
改 i18n

**Comment by evolutionjay** [comment]
不是 i18n ， 
@jikkai 

好像没有，我就算想用css 的 :after { content: ' xxx ' } 也不行 因为已经死了

**Comment by jikkai** [comment]
@evolutionjay 改 i18n 确实是个比较好的方法，参考[文档](http://element.eleme.io/#/zh-CN/component/i18n) ，然后 locale 参照[这个文件](https://github.com/ElemeFE/element/blob/dev/src/locale/lang/zh-CN.js#L69) 按照你的需求改写就行了

**Comment by scscms** [comment]
也不可能整个网站都变成”瓶/页“吧。所以部分页你就另制作语言包放进去。
如果只有个别页，而且不想制作语言包，可更新后自己修改dom节点textContent。
