### ISSUE TITLE
[Bug Report] 导航菜单组件包含默认激活项与默认展开项时所有二级都无法展开缩回

### ISSUE THREAD

**Issue by tom-vision** [ElemeFE/element#4176]
### Element UI version
1.2.8

### OS/Browsers version
Chrome/58.0.3029.19

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/20kvw7qp/](https://jsfiddle.net/20kvw7qp/)

### Steps to reproduce
default-openeds 与 default-active 对 submenu 使用时无法展开与缩回

### What is Expected?
修复该问题

### What is actually happening?
修复该问题

**Comment by Leopoldthecoder** [comment]
目前 submenu 不支持这两个属性。

**Comment by tom-vision** [comment]
是menu不支持这两个属性吧？我是加在menu上的。那default-openeds这个属性怎么使用呢？

**Comment by Leopoldthecoder** [comment]
加在 menu 上是可以的，但是你的 demo 控制台已经报错了。`default-openeds` 需要是一个数组。
