### ISSUE TITLE
[Feature Request] 希望表单组件支持设置name属性

### ISSUE THREAD

**Issue by PanYX** [ElemeFE/element#4177]
### Existing Component
是

### Component Name
Select,Cascader,Slider,TimePicker,DatePicker,DateTimePicker,Rate,ColorPicker

### Description
假设有一个用户配置的动态变化的大表单，把所有data资源提交后台会产生很多冗余的数据，一个个来获取这些字段又太麻烦，在这些场景还是希望通过直接提交form表单来达到从前端提交数据的目的。

因为大部分element组件底层都有原生的控件，如input,select，这个时候要是能够通过给组件设置name属性，给底层如input,select这个原生 组件设置上name属性，再通过提取form表单里有name属性的控件，比如通过FormData，可以很快得到需要传输到后台的数据。

看了一下最终渲染后的DOM结构，已经有一些组件已经可以直接设置name属性去设置底层控件的name属性，如Radio,Input,Switch等一些组件。

希望能增加以上其他组件的name属性的设置支持。

**Comment by Leopoldthecoder** [comment]
是的，这个在计划中。

**Comment by PanYX** [comment]
期待新特性上线，希望element越来越好！

**Comment by VIGDXX** [comment]
@Leopoldthecoder 计划哪个版本发这个新特性。。。我现在被这个 name 搞得想去改 node_modules 里面的源码了。。。
