### ISSUE TITLE
页面结构出来了，但是背景色的类名怎么不起作用，最重要的是为什么第一个<el-row>有默认高的值，721px

### ISSUE THREAD

**Issue by Zhi-Peng** [ElemeFE/element#418]
<div class="">
        <div class="">
            <el-row>
                <el-col :span="16"><div class="grid-content bg-purple">fsd</div></el-col>
                <el-col :span="8"><div class="grid-content bg-purple">fsdfs</div></el-col>
            </el-row>
        </div>

        <div class="">
            <el-row>
                <el-col :span="16"><div class="grid-content bg-purple">fsd</div></el-col>
                <el-col :span="8"><div class="grid-content bg-purple">fsdfs</div></el-col>
            </el-row>
        </div>

        <div class="">
            <el-row>
                <el-col :span="16"><div class="grid-content bg-purple">fsd</div></el-col>
                <el-col :span="8"><div class="grid-content bg-purple">fsdfs</div></el-col>
            </el-row>
        </div>
    </div>

**Comment by baiyaaaaa** [comment]
1. 背景色的类名是文档展示里写的样式
2. el-row默认行高请提供示例重现

**Comment by Zhi-Peng** [comment]
<div>
        <div class="">
            <el-row>
                <el-col :span="16"><div class="grid-content bg-purple-dark">fsd</div></el-col>
                <el-col :span="8"><div class="grid-content bg-purple">fsdfs</div></el-col>
            </el-row>
        </div>

        <div class="">
            <el-row>
                <el-col :span="16"><div class="grid-content bg-purple">fsd</div></el-col>
                <el-col :span="8"><div class="grid-content bg-purple">fsdfs</div></el-col>
            </el-row>
        </div>

        <div class="">
            <el-row>
                <el-col :span="16"><div class="grid-content bg-purple">fsd</div></el-col>
                <el-col :span="8"><div class="grid-content bg-purple">fsdfs</div></el-col>
            </el-row>
        </div>
    </div>

**Comment by Zhi-Peng** [comment]
<div>el-row有默认高度，上面的和下面的用div写的所展示的代码不一样，上面的有默认高度下面div写的没有，好像与el-row的伪元素的display:table有关</div>
<el-row>
  <el-col :span="24"><div class="grid-content bg-purple-dark">dsadsa</div></el-col>
</el-row>
<el-row>
  <el-col :span="24"><div class="grid-content bg-purple-dark">dsadsa</div></el-col>
</el-row>

<div>dsdd</div>
<div>dsdsd</div>
