### ISSUE TITLE
[Bug Report] MessageBox多次调用只弹出最后一个

### ISSUE THREAD

**Issue by rongxingsun** [ElemeFE/element#4181]
### Element UI version
1.2.8

### OS/Browsers version
 Windows 7/ Chrome/57

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/a3ery0wa/3](https://jsfiddle.net/a3ery0wa/3)

### Steps to reproduce
一个函数连续调用MessageBox组件，只弹出最后一个MessageBox

**Comment by rongxingsun** [comment]
没有苹果电脑，也没装黑苹果，所以没试过

**Comment by Leopoldthecoder** [comment]
不算 bug，如果一定要同时弹出多个的话，可以这样：https://jsfiddle.net/leopoldthecuber/w0eg15ug/1/

**Comment by jochenshi** [comment]
在已经生成一个$msgbox的情况下此时再次调用$msgbox是不会弹框的？你们是这么设计的是吗？

**Comment by Leopoldthecoder** [comment]
@jochenshi 是的。这和浏览器的原生行为一致，你可以打开控制台执行以下代码:
```javascript
for (let i = 0; i < 3; i++) { alert('Alert') }
```

**Comment by jochenshi** [comment]
好的，谢谢！

**Comment by ly1989abc** [comment]
@Leopoldthecoder 

> 不算 bug，如果一定要同时弹出多个的话，可以这样：https://jsfiddle.net/leopoldthecuber/w0eg15ug/1/

$msgbox可以这样实现，$message好像不行
