### ISSUE TITLE
[Bug Report] table里添加验证，但是验证错误

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4182]
### Element UI version
1.2.8

### OS/Browsers version
Mac/safari

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/Lut5urLo/3/](https://jsfiddle.net/Lut5urLo/3/)

### Steps to reproduce
第一行的Input 无法验证
新增行的Input验证错误 ，即使添加上数据也提示错误

### What is Expected?
无

### What is actually happening?
无

**Comment by Leopoldthecoder** [comment]
```html
<el-form>
  <el-table>
    <el-table-column>
      <el-form-item>
```
确实无法保证这种结构下还能正常验证。如果一定要使用这种 DOM 结构的话，建议使用其他第三方验证库。
