### ISSUE TITLE
[Bug Report] size-change 改变的时候数据变化了，但是选择一页显示几条数据的没有变化！

### ISSUE THREAD

**Issue by 547437352** [ElemeFE/element#4184]
### Element UI version
1.2.2

### OS/Browsers version
window/谷歌

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
默认一页显示10条，当选择一页显示20条的时候

### What is Expected?
希望数据，变成20条，选择框中选中20条/页，同时页码发生变化

### What is actually happening?
光数据发生了变化，但是选择框中一闪而过20条/页，之后又变成10条/页，页码也没有变化

![qq 20170413165117](https://cloud.githubusercontent.com/assets/13287603/24997642/e792b6f2-2069-11e7-8d51-72230205fcf4.png)
![qq 20170413165131](https://cloud.githubusercontent.com/assets/13287603/24997656/f053793e-2069-11e7-9f9e-d3bac029e60a.png)
![qq 20170413165357](https://cloud.githubusercontent.com/assets/13287603/24997669/fcb2a4de-2069-11e7-9d88-b2384735a172.png)
![qq 20170413165415](https://cloud.githubusercontent.com/assets/13287603/24997683/06b60bba-206a-11e7-822f-60f98d931392.png)

@QingWei-Li

**Comment by 547437352** [comment]
没有

**Comment by Leopoldthecoder** [comment]
没有重现链接的 issue 会被直接关闭
