### ISSUE TITLE
[Feature Request] 功能增加希望form表单的label-position 根据屏幕自动适应

### ISSUE THREAD

**Issue by bigrocs** [ElemeFE/element#4185]
### Existing Component
是

### Component Name
form

### Description
默认设定左或者右时 当切换到小屏幕时能自动把label-position改为top

**Comment by bigrocs** [comment]
http://element.eleme.io/#/zh-CN/component/form

Form Attributes

label-position	表单域标签的位置	string	right/left/top	right

**Comment by scscms** [comment]
自己可监听resize事件，相应修改label-position值。

**Comment by baiyaaaaa** [comment]
I think it should be done in your project control. As a form component, it's not appropriate to do something with layout
