### ISSUE TITLE
[Feature Request] 希望提供交互式控件(如dialog)的生命周期钩子,用于阻止其消失

### ISSUE THREAD

**Issue by funkyLover** [ElemeFE/element#4187]
### Existing Component
Yes

### Component Name
Dialog, etc.

### Description
有时候用户已经关闭了dialog(可以通过右上角的✘,背景mask,或是自己定义的close方法),我们只能接受到close-event,实际上关闭已经无法阻止了(通过watch开关变量只能阻止通过`显示改变开关变量`的方式,而且也不过优雅).例如我希望在关闭前询问用户后再确定是否关闭

**Comment by Leopoldthecoder** [comment]
参考 #4082 ，后续版本中会考虑加入。
