### ISSUE TITLE
[Feature Request] 希望select组件可以增加选中的事件回调，不然操作起来有些不顺手

### ISSUE THREAD

**Issue by tangyue0924** [ElemeFE/element#4189]
### Existing Component
是

### Component Name
Select

### Description
首先。。感谢大神进来看我的ISSUE。。
就像input 中的 autocomplete一样，有一个选中后的回调，便于进行下一步操作，如快捷键操作。。。

现在因为这个问题，项目有些卡住了，希望各位可以加上这个功能。谢谢了！！！

**Comment by tangyue0924** [comment]
http://element.eleme.io/#/zh-CN/component/select

Select Events

**Comment by Leopoldthecoder** [comment]
你的具体需求是？

**Comment by tangyue0924** [comment]
您好，我的需求大概就是：
select选中一个项目后，自动focus到下一个Input中，因为select没有选中后的事件回调，所以这一小功能挺难弄的~谢谢

**Comment by Leopoldthecoder** [comment]
使用 `change` 事件呢？

**Comment by tangyue0924** [comment]
`change` 获取不到event，好多事都做不了啦

**Comment by QingWei-Li** [comment]
`change.native`

**Comment by Leopoldthecoder** [comment]
@QingWei-Li @change.native 应该不行，因为最外层不是 input 标签。

@tangyue0924 https://jsfiddle.net/thj1xhLx/ 这样呢？

**Comment by tangyue0924** [comment]
@Leopoldthecoder 谢谢，可是不行啊，我需要的是键盘事件，option使用 `@keyup.native` 无效啊

**Comment by Leopoldthecoder** [comment]
键盘事件？所以你需要的是敲下回车（而不是鼠标点击）选中选项后的回调？

**Comment by tangyue0924** [comment]
@Leopoldthecoder 是的

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
