### ISSUE TITLE
下拉菜单组件反馈

### ISSUE THREAD

**Issue by yiling-e0** [ElemeFE/element#419]
### ElementUI version
1.0.0-rc.6

### OS/Browers version
win7/Chrome 53

### Vue version
2.0.1

下拉组件响应慢,无论是hover还是click事件响应都有一定延时，
关闭下拉菜单的时候最为明显

**Comment by baiyaaaaa** [comment]
本来设计就是做了延迟处理，鼠标在多个 dropdown hover 时如果没有延迟处理体验很不友好

**Comment by yiling-e0** [comment]
@baiyaaaaa 可否将延迟处理 作为Attributes设置呢？因为关闭的响应延迟太明显了

**Comment by baiyaaaaa** [comment]
不认同下拉的延迟会造成体验上的影响，另外不是所有特性都适合做成可配置的。讨论可以到 https://gitter.im/ElemeFE/element 上
