### ISSUE TITLE
[Feature Request] 当用户选择自动上传为 false 时，用户上传了文件时，能不能添加一个功能，回调我一下下。

### ISSUE THREAD

**Issue by iamnewsea** [ElemeFE/element#4192]
### Existing Component
是

### Component Name
upload

### Description
当用户选择自动上传为 false 时，用户上传了文件时，能不能添加一个功能，回调我一下下。

我要实现：上传文件后，客户端计算文件的MD5, Ajax一次和服务器进行比较， 如果一致，就不用传了。 如果不一致，就上传。
所以想，自动上传设置为flase ， 触发我的事件， 事件里手动上传 。

**Comment by Leopoldthecoder** [comment]
这个功能在计划中了。

**Comment by iamnewsea** [comment]
我已经实现了，给你传上去

**Comment by Leopoldthecoder** [comment]
欢迎 PR

**Comment by yuweiming2016** [comment]
什么版本会发布？

**Comment by yuweiming2016** [comment]
我现在也需要手动上传模式下，选择文件后，做一个回调处理

**Comment by umiyo** [comment]
有没有相关的可用替代方案？

**Comment by holidaying** [comment]
关键是什么时候rp啊，现再急需这个功能，但是又不能改源码

**Comment by baiyaaaaa** [comment]
#4447，1.3 会发布

**Comment by holidaying** [comment]
我靠你们的1.3有吗？5月3号发布的就没有这个，能否效率一点

**Comment by Leopoldthecoder** [comment]
@holidaying 请你注意你的语言，我们并不欠你什么。另外，昨天的版本已经有这个功能了：https://jsfiddle.net/bcyndkdb/ ，反映问题之前先确定问题是否存在。
