### ISSUE TITLE
[Bug Report] Table 组件在 fixed 固定列时出现滚动条临界值 bug

### ISSUE THREAD

**Issue by schwann168** [ElemeFE/element#4197]
### Element UI version
1.2.8

### OS/Browsers version
Mac/chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/bhoy4dez/](https://jsfiddle.net/bhoy4dez/)

### Steps to reproduce
如重现链接如示，将显示窗体宽度调整至986px 左右这个临界值，表格底部滚动条刚好消失的时候，fixed 列出现了滚动条。

另外，发现如果所有的列宽都固定，就有此问题，但不设置列宽由其自动撑开的话，就会引发此问题。

![Table Bug](http://chuantu.biz/t5/64/1492133308x2728309676.png)

### What is Expected?
fixed 列不出现滚动条

### What is actually happening?
fixed 列出现了滚动条

**Comment by Leopoldthecoder** [comment]
和 #3708 重复，后续进展在 #3708 同步。
