### ISSUE TITLE
[Bug Report] 在Safari里 el-dialog 内嵌el-table时  table 无法拖动滚动条

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4199]
### Element UI version
1.2.8

### OS/Browsers version
Sierra10.12.4/safari 10.1

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/yp3kxbkk/2/](https://jsfiddle.net/yp3kxbkk/2/)

### Steps to reproduce
用Safari 打开http://element.eleme.io/1.2/#/zh-CN/component/table  你们的Demo table也无法滚动

### What is Expected?
无

### What is actually happening?
无

**Comment by Leopoldthecoder** [comment]
与 #3710 重复，后续进展会在 #3710 中同步。

**Comment by liuyongjun-s** [comment]
大神们有解决方案了吗
