### ISSUE TITLE
[Feature Request] table 的 clearSelection 和 toggleRowSelection 对单选表格没有作用

### ISSUE THREAD

**Issue by wanganjun** [ElemeFE/element#4201]
### Existing Component
是

### Component Name
Table 表格

### Description
是故意设计成这样的, 还是我的代码有问题?

调用 clearSelection 的代码在 https://jsfiddle.net/yg0qht1o/3/ 这个页面中的 `Babel` 的部分的 28 行

作用一样的代码对多选表格是有效的 (在 https://jsfiddle.net/so8ywd9y/1/ 的 `Babel` 部分的 40 行)

**Comment by wanganjun** [comment]
@element-bot 这个链接是从 element-ui 的官网文档 http://element.eleme.io/1.2/#/zh-CN/component/table#dan-xuan 跳转过去的.......

**Comment by wanganjun** [comment]
@element-bot 搞定了, JSFiddle 这个网站用的不熟, 不知道可以直接保存.
链接已经更新了

**Comment by Leopoldthecoder** [comment]
是的，这两个方法还不支持单选，会在后续版本中加入支持。
