### ISSUE TITLE
[Bug Report] select 选择器远程搜索 清空，选择框宽度会改变

### ISSUE THREAD

**Issue by cyy0418** [ElemeFE/element#4202]
### Element UI version
1.2.8

### OS/Browsers version
macOS 10.12.5 / Chrome 57.0.2987.133 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/1nco9na3/](https://jsfiddle.net/1nco9na3/)

### Steps to reproduce
1、设置select 为远程搜索，且增加可清空属性后，
2、选择某个值后，鼠标移动到选择框，选择框会加宽显示删除按钮
![image](https://cloud.githubusercontent.com/assets/2883079/25031602/9003ad3c-2100-11e7-86f3-db9311e8590c.png)
![image](https://cloud.githubusercontent.com/assets/2883079/25031608/96a96ba4-2100-11e7-8779-2644309e9563.png)
### What is Expected?
输入框宽度不变

### What is actually happening?
输入框宽度改变

**Comment by scscms** [comment]
:clearable="false"
关闭清空按钮将不会改变宽度。

**Comment by Leopoldthecoder** [comment]
@scscms 这应该算是 bug 了，这种情况下需要清空的话就会出现这个问题。

**Comment by scscms** [comment]
那也是布局问题。按清空按钮放里面即可解决。
