### ISSUE TITLE
[Feature Request] 日期选择插件新增 monthrange 选项

### ISSUE THREAD

**Issue by SuperAL** [ElemeFE/element#4204]
### Existing Component
是

### Component Name
DatePicker

### Description
现有的是 日期区间选择（精确到日）和 日期时间区间选择（精确到秒），希望提供精确到月份的区间选择，后台系统需求令人眼花缭乱，感觉这个新选项在某些场景下还是需要的~

**Comment by scscms** [comment]
```
<el-date-picker v-model="value6" format="yyyy-MM" type="daterange" placeholder="选择月份范围">
```
format="yyyy-MM" 格式化一下先用着。

**Comment by niceue** [comment]
同求，跨月份选择，使用 daterange 就很不方便了。
#4859 也有这个需求只不过自动关闭了

**Comment by Leopoldthecoder** [comment]
Generally date range targeted at month or year can be implemented by putting on the page two separate DatePickers representing starting and ending date respectively. So we have no plan to add month and year support in range picking.

**Comment by scscms** [comment]
昨天的问题https://jsfiddle.net/ryukbnj8/ 我找到原因了：当默认值为空时是不成功的。即value: new Date(row[prop]),必须要有值。否则value: row[prop] ? new Date(row[prop]) : '',这样没法赋值成功。

另 ${ v.getFullYear() }-${ ('0' + (v.getMonth() + 1)).slice(-2) }-${ ('0' + v.getDate()).slice(-2) };
可简化为 v.toLocaleDateString().replace(/\b(\d)\b/g,'0$1')

另外，我们的项目里怎么样使用组件内的方法。比如<div v-element-clickoutside="handleClose">，能否提供个简单例子？
还有在创建虚拟dom时是否可使用v-for,v-if之类的？
return h('el-select', {
    props: {
        size:'small',
        placeholder: "请选择",
        value: str
        vFor,vIf ???
    }
}, arr);


guangda1234@126.com

**Comment by Leopoldthecoder** [comment]
@scscms `v-for` 和 `v-if` 在渲染函数中是不支持的：https://vuejs.org/v2/guide/render-function.html#v-if-and-v-for

需要使用 clickoutside 的话，可以
```javascript
  import ClickOutside from 'element-ui/src/utils/clickoutside.js'
  import Vue from 'vue'
  Vue.directive('element-clickoutside', ClickOutside)
```

**Comment by scscms** [comment]
您好，今天有人在 https://gitter.im/ElemeFE/element 提出修了elementUI源码后怎么使用。我知道肯定需要重新再打包，但我发现里面run命令很多。部分我还不明白其意思，能否给我逐一解释下其意思？
"scripts": {
  "bootstrap": "yarn || npm i",//安装依赖
  "build:file": "node build/bin/iconInit.js & node build/bin/build-entry.js & node build/bin/i18n.js & node build/bin/version.js",//构建文件
  "build:theme": "node build/bin/gen-cssfile && gulp build --gulpfile packages/theme-default/gulpfile.js && cp-cli packages/theme-default/lib lib/theme-default",//生成主题
  "build:umd": "node build/bin/build-locale.js",//什么文件？
  "build:utils": "cross-env BABEL_ENV=utils babel src --out-dir lib --ignore src/index.js",
  "clean": "rimraf lib && rimraf packages/*/lib && rimraf test/**/coverage && lerna clean --yes",//清空缓存
  "deploy": "npm run deploy:build && gh-pages -d examples/element-ui --remote eleme && del examples/element-ui",//部署
  "deploy:build": "npm run build:file && cooking build -c build/cooking.demo.js -p && echo element.eleme.io>>examples/element-ui/CNAME",
  "dev": "npm run bootstrap && npm run build:file && cooking watch -c build/cooking.demo.js -p",//debug测试
  "dev:play": "npm run build:file && cross-env PLAY_ENV=true cooking watch -c build/cooking.demo.js -p",
  "dist": "npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:umd && npm run build:theme",//打包。修改源码后应该只执行此命令吧？
  "dist:all": "node build/bin/build-all.js && npm run build:theme",//构建所有代码
  "i18n": "node build/bin/i18n.js",//打包语言包
  "lint": "eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet",
  "pub": "npm run bootstrap && sh build/git-release.sh && sh build/release.sh",//推送代码到git
  "pub:all": "npm run dist:all && lerna publish --skip-git && git commit -am 'publish independent packages' && git push eleme dev",//推送所有代码到git
  "test": "npm run lint && cross-env CI_ENV=/dev/ karma start test/unit/karma.conf.js --single-run",//测试
  "test:watch": "karma start test/unit/karma.conf.js" //热更新测试
},


guangda1234@126.com

**Comment by QingWei-Li** [comment]
@scscms 看 Makefile
