### ISSUE TITLE
[Feature Request] 日期时间区间 选择器 修改修改其中一个时间时，会导致两个时间都需要重新选择

### ISSUE THREAD

**Issue by javasgl** [ElemeFE/element#4209]
### Existing Component
Yes

### Component Name
datetimerange

### Description
日期时间区间 选择器 修改修改其中一个时间时，会导致两个时间都需要重新选择

**Comment by javasgl** [comment]
就是datetime picker这个控件

**Comment by scscms** [comment]
这是操作问题：第一次点击表示选择了一个点，第二次点击表示选择了第二个点，从而形成一个区间选择。当第三次点击表示取消前面选择并重新选择了一个点（回到第一次点击）。否则假如你已经选择1-2到1-5然后你再点1-8。怎么知道你是想要1-2到1-8还是要1-5到1-8呢？

**Comment by javasgl** [comment]
如果已有选择的区间A-B，那么第三次点击应该是修改A保留B， 而不是让A,B都重置了重新选。这样如果以后需要修改 AB中的任何一个的话，就不必两个都重新选了。
