### ISSUE TITLE
select 组件数据更新是出问题

### ISSUE THREAD

**Issue by dyw934854565** [ElemeFE/element#421]
### Steps to reproduce
下拉组件数据unshift的时候label显示错误，可看http://codepen.io/dyw/pen/pEkEaN?editors=1111

**Comment by Leopoldthecoder** [comment]
正如文档中所说，「需要注意的是，如果 el-option 是通过 v-for 指令渲染出来的，此时需要为 el-option 添加 `key` 属性，且其值需具有唯一性」。原因是 Vue 2.0 渲染机制的更新。

在上面的例子中，为你的 el-option 添加 `v-bind:key="item.value"` 即可正常工作。
