### ISSUE TITLE
[Bug Report] table的column添加filters属性，属性值非常多的时候，超出屏幕的这部分无法显示，请问如何解决呢？ 

### ISSUE THREAD

**Issue by iolg** [ElemeFE/element#4215]
### Element UI version
1.2.8

### OS/Browsers version
safari

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/53/](https://jsfiddle.net/pj71jkyw/53/)

### Steps to reproduce
filters数组中添加多个筛选值，导致筛选值超出屏幕范围；此时超出部分就无法点击了

### What is Expected?
筛选值过多时，可以实现滚动效果，使其不超出页面范围

### What is actually happening?
筛选值过多时，超出了页面范围，且超出部分无法选择

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/pj71jkyw/54/
