### ISSUE TITLE
[Bug Report] 为什么不提供upload组件手动选择iframeUpload的方式

### ISSUE THREAD

**Issue by czwaiwai** [ElemeFE/element#4218]
### Element UI version
1.2.8

### OS/Browsers version
win7/ios

### Vue version
2.2.6

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
  const uploadComponent = (typeof FormData !== 'undefined' || this.$isServer)
        ? <upload {...uploadData}>{trigger}</upload>
        : <iframeUpload {...uploadData}>{trigger}</iframeUpload>;

### What is Expected?
希望可以通过props手动切换

### What is actually happening?
不能手动切换

**Comment by baiyaaaaa** [comment]
为什么要手动降级？
