### ISSUE TITLE
想要不显示el-tree的收缩按钮

### ISSUE THREAD

**Issue by yeomanyang** [ElemeFE/element#4224]
```
defaultProps: {
     label: "name",
     children: "menuItemList",
     isLeaf: "isLeaf"
}
this.rfMenusTree = [{
    name: "菜单树（RF）",
    key: 'rf',
    isLeaf: true,
    menuItemList: data.rfMenuTree
}]  
```

已经在props中设置了isLeaf，已经在子节点中设置了 isLeaf: true，但是收缩按钮还是出现了。
是我的用法不对或者说有别的方法可以实现不显示收缩按钮这个需求呢？

**Comment by hawtim** [comment]
请问你解决这个问题了么？ @yeomanyang

**Comment by yeomanyang** [comment]
font{
        line-height: 1.5;
    }


    
并没有解决哦



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年08月2日 15:04，hawtim<notifications@github.com> 写道： 


请问你解决这个问题了么？ @yeomanyang
