### ISSUE TITLE
[Feature Request] 想要不显示el-tree的收缩按钮

### ISSUE THREAD

**Issue by yeomanyang** [ElemeFE/element#4225]
### Existing Component
是

### Component Name
el-tree

### Description
```
defaultProps: {
     label: "name",
     children: "menuItemList",
     isLeaf: "isLeaf"
}

this.rfMenusTree = [{
    name: "菜单树（RF）",
    key: 'rf',
    isLeaf: true,
    menuItemList: data.rfMenuTree
}]  
```
已经在props中设置了isLeaf，已经在子节点中设置了 isLeaf: true，但是收缩按钮还是出现了。
是我的用法不对或者说有别的方法可以实现不显示收缩按钮这个需求呢？

**Comment by yeomanyang** [comment]
不好意思，并没有参考链接哦。如果是我的用法不对请告知，如果用法没问题，我再提供fiddle。谢谢～

**Comment by yeomanyang** [comment]
https://jsfiddle.net/4Lfs73s0/   提供一个fiddle吧

**Comment by baimiaolei** [comment]
@yeomanyang  你最后怎么做了呢？

**Comment by baimiaolei** [comment]
@yeomanyang 你这个问题 后来怎么处理了呢？我现在也遇到这个问题了

**Comment by yeomanyang** [comment]
@baimiaolei  暂时没有解决哦

**Comment by Leopoldthecoder** [comment]
在非 lazy 模式下，对于一个有 children 的节点，收缩按钮总是会显示的。如果只是想隐藏收缩按钮，可以通过覆盖 CSS 来实现；如果需要的是禁掉隐藏功能，目前还没有计划进行支持。
