### ISSUE TITLE
[Request] Standardizing the language used in Issues/Pull Requests/Commits

### ISSUE THREAD

**Issue by syn-zeta** [ElemeFE/element#4227]
### Existing Component
No

### Description
As Vue grows and sees more users in the West, ElementUI will get a chance to do so as well. I'm afraid many more users will face the same issues of language barrier as me and likely other current users/contributors. These go for non-English-speaking users and non-Chinese-speaking users:

- Duplicate issues/pull-requests due to not being able to tell that one already exists but filed in the other language
- Not being able to learn anything from the discussions that go on in issues/PRs that would be very helpful if contributing in the future

I think a start would be to translate all the titles of issues/PRs in English and keeping a copy of them in the original language inside the body. It threw me off the first time I looked at the Issues page, so this should go a long way. Thoughts?

**Comment by BigChief45** [comment]
Agree with this. But I feel this is something that won't happen. The extra work in translating all issues and PRs is just too much. And obviously most of the Chinese users will not want to, and will feel that there is no need to translate the content.

**Comment by Leopoldthecoder** [comment]
This issue leads me [here](https://github.com/ant-design/ant-design/issues/4897).

Ant Design is the best UI kit in the React ecosystem, and it's also created and maintained by a Chinese team. It seems they are starting to reply their issues in English regardless of which language the issue creator used. And for Chines issues, they have a saved reply to encourage using English next time.

Translating all issue/PR titles is indeed too much work. Perhaps we could start by replying issues in English, like what Ant Design is doing. And we have @element-bot , so an auto reply seems easy.

**Comment by BigChief45** [comment]
@Leopoldthecoder I believe this would be great for Element. The international community will also appreciate immensely.

**Comment by syn-zeta** [comment]
I should clarify that I meant the titles of _open_ and new issues, the # of which normally floats around 200. Replying in English will definitely help in the long run, but since the summary of an issue is usually captured in the titles, it would be nice to be able to go through the list of issues and understand the essence without having to open each one of them and going through the replies.

**Comment by Leopoldthecoder** [comment]
@syn-zeta I checked and found that some online translation websites have free APIs. With the bot, it seems possible to have Chinese issues automatically translated.

**Comment by syn-zeta** [comment]
That sounds great! I'm available to help with that if needed.

I was also thinking about how you plan to convey to the other contributors and users to prefer English in these sections.

**Comment by Leopoldthecoder** [comment]
Now our bot can do the translation work: #4400.
Basically it does three things: 
- Change issue title to English
- Leave a comment encouraging using English next time
- Translate issue body and leave another comment

**Comment by syn-zeta** [comment]
Awesome work!

**Comment by syn-zeta** [comment]
Re-opening as I also noticed that Chinese is the predominant language in (Element's Gitter room)[https://gitter.im/ElemeFE/element], and did not want to create another ticket for my suggestion: a new English-exclusive Gitter room.

I've seen quite a few issues here that breach the first bullet of the (contributing guidelines)[https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md], and although the issue creator likely sees the links to SegmentFault and Gitter when (creating an issue)[https://elementui.github.io/issue-generator/#/en-US], the non-Chinese speaking users probably feel helpless to understand what goes on in either of those places, and come here instead.

So, I think it will be helpful in keeping this repository's issue section clear of basic questions from new developers by having a link to the proposed English-only Gitter room in the issue-generator page.

**Comment by syn-zeta** [comment]
[Perfect](https://gitter.im/element-en/Lobby)
