### ISSUE TITLE
dropdown bug

### ISSUE THREAD

**Issue by superhj1987** [ElemeFE/element#423]
### ElementUI version
1.0.0-rc.7

### OS/Browers version
Chrome 53

### Vue version
2.0.1

dropdown引入后渲染不对，报错element-ui.common.js?a187:4843 Uncaught TypeError: Cannot read property '0' of undefined

**Comment by superhj1987** [comment]
。。。。文档竟然偷偷更新了

**Comment by Maadtin** [comment]
how to fix this?
