### ISSUE TITLE
[Feature Request] Support for percent based table-column widths

### ISSUE THREAD

**Issue by syn-zeta** [ElemeFE/element#4234]
### Existing Component
Yes

### Component Name
Table-column

### Description
Currently, the `width` attribute only accepts values in pixels. Passing in % seems to be parsed and interpreted as pixel units: https://jsfiddle.net/upbxbxqL/

`colgroup`'s `col` accepts pixel and percent units, so the implementation would be fairly simple, but allow width-responsive tables.

**Comment by syn-zeta** [comment]
Ah, I seemed to have missed the `min-width` property which can be used instead of % widths.

It worked as expected in most cases that I tested it with, but not in this example (haven't been able to boil it down):

https://jsfiddle.net/pcxfvmkn/
https://jsfiddle.net/pcxfvmkn/1/ (all the widths are divided by 10, which should result in the same layout)

**Comment by syn-zeta** [comment]
I also found out that ratios passed using `min-width` attribute get translated to pixel values, and recalculated if the viewport is resized. This works, but seems a little inefficient as `col` element's `width` attribute can accept values in `%` units natively.

**Comment by r03** [comment]
I think all units should be supported, but col width is deprecated in html 5. Should this be solved with css instead?

**Comment by firesh** [comment]
I need `%` unit width too.

**Comment by furybean** [comment]
Sorry, we have no plan to support this.

**Comment by syn-zeta** [comment]
@furybean The implementation would simply involve passing the prop value directly to `colgroup`'s `col` attribute, which natively supports percent values. Isn't the support here just a simple pass-through with the custom layout switched off?

**Comment by furybean** [comment]
To layout the entire table, I need to calculate table current scroll status .
If width is percentage, I do not know how to calculate the scroll status.
