### ISSUE TITLE
[Feature Request] 优化 TableColumn[type="selection"] 的性能

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4236]
### Element UI version
0.1.0

### OS/Browsers version
windows10 Chrome70

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/8cn0chtk/1/](https://jsfiddle.net/8cn0chtk/1/)

### Steps to reproduce
1.點選table中的CheckBox
2.半天才會反應過來
3.說明table被重新渲染了

### What is Expected?
點選checkbox沒有必要重新渲染整個表單
如果整個表單的計算量比較大，單選操作會比較卡

### What is actually happening?
不用重新渲染

**Comment by zzzgit** [comment]
@element-bot ,沒有試過其他機器

**Comment by lincenying** [comment]
mac chrome 57 上面的例子也很卡.

**Comment by rossroma** [comment]
我也遇到过卡顿的问题，主要是每一行绑定了太多的事件，当加载的数据越多时越卡。我试过每页加载200条数据，直接导致部分同事的Chrome崩溃。后来我删掉了所有的事件绑定，在table的最外层做一个事件委托，才解决了卡顿问题。

**Comment by zzzgit** [comment]
@groenroos ，你這是直接操作DOM嗎

**Comment by houjiazong** [comment]
OSX: 10.13.6

**Comment by houjiazong** [comment]
OSX: 10.13.6
Chrome:  67.0.3396.99
数据超过100条后，点击checkbox大概需要1秒的时间才会有响应

**Comment by fengyun2** [comment]
有人解决这个问题了吗？

**Comment by wukaikailive** [comment]
很老的问题了，建议做一个虚拟滚动优化。类似这种效果https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/fullCols

**Comment by zzzgit** [comment]
> 很老的问题了，建议做一个虚拟滚动优化。类似这种效果https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/fullCols

雖然這是一個廣告，不過值得支持一下，因為這是目前唯一的解決方案
