### ISSUE TITLE
[Bug Report] select无法绑定computed中的变量

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4237]
### Element UI version
1.2.8

### OS/Browsers version
windows10 chrome60

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/fsdq5e5L/1/](https://jsfiddle.net/fsdq5e5L/1/)

### Steps to reproduce
1.在下拉框中选择任意一个选项
2.无法切换

### What is Expected?
可以正常切换

### What is actually happening?
el-select的v-model只能设置成data里面的变量，不能设置成computed里面的变量，不然，就无法切换。
但是，实际上，有时候，需要设置成computed里面的变量。
比如，从父组件外面传入一个prop到子组件，现在直接把el-select的v-model设置成这个prop显然是不行的，因为这样会修改外部变量，这是被vue2禁止的。那么，就需要在computed里面写一个内部的变量，把prop的值复制一份来用。
但是这种情况下，select无法切换。

**Comment by Leopoldthecoder** [comment]
我们来看看 Vue 本身对 computed 的处理：https://jsfiddle.net/leopoldthecuber/fsdq5e5L/2/

**Comment by zzzgit** [comment]
那我这种需求怎么办？
我要设置的v-model，来自父组件传进来的值，如果直接设置这个值，就会报错，组件内部不能修改外部的变量
如何解决？

**Comment by Leopoldthecoder** [comment]
子组件的 data 里加一个变量做 v-model 绑定，watch 一下父组件传进来的值，变化时改变子组件的那个 data。

**Comment by jackzhujie** [comment]
i have the same issues
