### ISSUE TITLE
[Feature Request] More documentation/samples on v-loading dynamic close

### ISSUE THREAD

**Issue by ragamuffinguil** [ElemeFE/element#4239]
### Existing Component
Yes

### Component Name
loading

### Description
Requesting for more documentation/samples on v-loading dynamic close once page and component is rendered please. thanks.

**Comment by ragamuffinguil** [comment]
in this `[page](http://element.eleme.io/#/en-US/component/loading)` i want to make the loading animation automatically close once table is completely rendered.

**Comment by syn-zeta** [comment]
@ragamuffinguil The loading animation can be hidden by setting the `loading` data property to false. If the table data is loaded remotely, you would do that in the response handler. What exactly do you mean by "completely rendered"? Perhaps try the `mounted` or `updated` hook.

**Comment by ragamuffinguil** [comment]
thanks @syn-zeta, i already tried `mounted` but loading animation close faster than component rendered completely.

**Comment by Leopoldthecoder** [comment]
Which component? Please paste your code snippet here.

**Comment by ragamuffinguil** [comment]
@Leopoldthecoder  in element [loading component](http://element.eleme.io/#/en-US/component/loading) in this example [JSfiddle](https://jsfiddle.net/api/post/library/pure/)

**Comment by Leopoldthecoder** [comment]
I meant which component in "loading animation close faster than component rendered completely".

Plus, the fiddle is empty probably because you didn't hit the "Save" button.

**Comment by syn-zeta** [comment]
@ragamuffinguil You could try using [`$nextTick`](https://vuejs.org/v2/api/#Vue-nextTick) or a [`setTimeout()` with a timeout of 0](http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful) to allow the browser to finish rendering before setting `loading` to `false`.

**Comment by ragamuffinguil** [comment]
@Leopoldthecoder in `element table`

**Comment by ragamuffinguil** [comment]
thanks @syn-zeta. but i even also tried `settimeout()` inside `$nextTick` but same result, browser already rendered but table component was still rendering. But if i adjust the timeout value to 3000 it may close the animation timely sometimes.(it depends on the table data count).

Here is my sample code inside my vue component.
`mounted: function() { this.$nextTick(function() { setTimeout(() => { this.loading = false;  }, 3000);  })  }`

**Comment by Fanciervm** [comment]
I had a similar problem. So I used the `Loading.service(options)` instead of the directive.

**Comment by syn-zeta** [comment]
Are you loading the table data via AJAX? 3 seconds is a lot of time to render some static content.

Besides, the JSFiddle link that you've updated does not demonstrate your issue. I've updated it to load some data via AJAX to try and reproduce what I think you're saying, but cannot: https://jsfiddle.net/5o478690/1/
