### ISSUE TITLE
[Feature Request] 'Enter' to behave like 'Tab'

### ISSUE THREAD

**Issue by albert-kam** [ElemeFE/element#4242]
### Existing Component
Yes

### Component Name
Form

### Description
In some cases where users have to input lots of numerical data it's more productive to use 'Enter' key instead of 'Tab' key, as the location of 'Enter' is near in the numpad keyboard.

I have taken a look at something like this http://joelpurra.github.io/plusastab/

I might be just being selfish, but direct support on Element-UI Form element for this feature would be great, as depending on the whole jquery just for this feature seems overkill.

Thank you.

**Comment by Leopoldthecoder** [comment]
This is an edge case so it won't be supported. In fact, it's easy to implement yourself: https://jsfiddle.net/leopoldthecuber/pf53eygj/1/

**Comment by albert-kam** [comment]
Thank you for your clarification and your time on implementing the example.
Using the mounted lifecycle callback is nice.
