### ISSUE TITLE
[Feature Request] 能否给评分组件添加大小属性

### ISSUE THREAD

**Issue by Richardo8** [ElemeFE/element#4245]
### Existing Component
是

### Component Name
Rate

### Description
能否给评分组件添加大小属性，直接控制星星的大小

**Comment by Richardo8** [comment]
http://element.eleme.io/#/zh-CN/component/rate

参考 http://www.sucaihuo.com/jquery/4/481/demo/#size 这个jq的插件可以直接通过修改size设置大小

**Comment by pengchongfu** [comment]
@Richardo8 覆盖一下样式怎么样？覆盖样式也挺简单的。

**Comment by Richardo8** [comment]
@pengchongfu 是可以解决问题 但是组件内部直接设置不是更容易一些吗

**Comment by pengchongfu** [comment]
@Richardo8 嗯，主要是感觉整套组件很少有这么设计的。可能是考虑到 js 里边改 css不是很优雅。。
看看官方怎么考虑吧

**Comment by Leopoldthecoder** [comment]
还是自己覆盖样式吧。每个人都有不同的需求，如果把这些需求都做进来的话，整个库会变得非常臃肿。所以类似这种通过覆盖样式就可以满足的需求，建议还是自行添加。
