### ISSUE TITLE
dialog的z-index与select组件下拉菜单的z-index同值，导致第一次点击时下拉菜单不可见

### ISSUE THREAD

**Issue by kapeter** [ElemeFE/element#4249]
Element UI version

1.2.8

OS/Browsers version

windows 7 / chrome 57.0.2987.133

Vue version

2.1.10

Steps to reproduce

在dialog组件中添加select组件。

.v-modal的z-index为2000，el-select-dropdown的z-index的初始值也为2000，导致第一次点击时下拉菜单不可见。

建议将PopupManager.zIndex设置为高于2000的值。

What is Expected?

点击select组件出现下拉菜单

What is actually happening?

第一次点击时，下拉菜单被遮罩层遮挡，无法显示

**Comment by keysir** [comment]
解决了 element 版本冲突 （项目的 dialog select 组件对应element版本不一致）
PopupManager 有多个 参考这篇帖子的思路 https://www.cnblogs.com/lhfssg/p/13030097.html
