### ISSUE TITLE
建议：把控件的z-index规划一下

### ISSUE THREAD

**Issue by acelan86** [ElemeFE/element#425]
比如
1、普通控件0-100（slider的滑动柄属于这类）
2、组件自身层级需求100-200（表格fixed列）
3、弹出层（popper等）1000-2000（弹出层需要考虑是否在dialog上，dailog的zindex当做画布的起始点）
4、dialog 2000-3000
4、遮罩层（loading等）3000-4000
5、顶级层（信息，notify）9999+

现在又很多层级上的问题

ps：最好形成书面规范，防止自定义组件层级错误

**Comment by QingWei-Li** [comment]
目前 dialog 和弹出层，其实用的都是 vue-popup，那么 zIndex 是自增的，只是 rc7 这版 build 的时候出现问题没发现导致弹出层有可能会被 dialog 覆盖。其实只需要将 message 等顶层组件设置相对较大的 zIndex 就好了

**Comment by acelan86** [comment]
想想感觉楼上说的对，只要vue-popper能实现管理就行，因为不挂在body上的可以通过popper与父节点的zindex继承关系来控制popper的层级

**Comment by DanielWLam** [comment]
这个问题现在有什么文档说明一下吗？

**Comment by xianshenglu** [comment]
https://github.com/ElemeFE/element/issues/8375

我使用了import PopupManager from 'element-ui/lib/utils/popup/popup-manager'可以正常工作，在其他需要设置层叠顺序的组件上设置 
```js
zIndex:PopupManager.nextZIndex()
```
