### ISSUE TITLE
[Bug Report] dialog的z-index与select组件下拉菜单的z-index同值，导致第一次点击时下拉菜单不可见

### ISSUE THREAD

**Issue by kapeter** [ElemeFE/element#4250]
### Element UI version
1.2.8

### OS/Browsers version
windows 7 / chrome 57.0.2987.133

### Vue version
2.2.6

### Steps to reproduce
在dialog组件中添加select组件。

.v-modal的z-index为2000，el-select-dropdown的z-index的初始值也为2000，导致第一次点击时下拉菜单不可见。

建议将PopupManager.zIndex设置为高于2000的值。

### What is Expected?
点击select组件出现下拉菜单

### What is actually happening?
第一次点击时，下拉菜单被遮罩层遮挡，无法显示

**Comment by kapeter** [comment]
没有在macOS试过。

**Comment by Leopoldthecoder** [comment]
没有重现链接的 bug report 会被直接关闭。

**Comment by GloriousFuture** [comment]
@kapeter 请问最后怎么解决的，我也遇到了这个问题

**Comment by qingwufengyang** [comment]
macOS 也是这个问题，好多文本框层级都在Dialog后边，点着有点烦人，请问最后怎么解决的

**Comment by qingwufengyang** [comment]
@kapeter 请问怎么解决的？

**Comment by listen-lee** [comment]
@qingdengyue https://github.com/ElemeFE/element/issues/5221

**Comment by wang22123467469** [comment]
请问这个地方解决了吗，我也是遇到了相关问题

**Comment by qingwufengyang** [comment]
给dialog增加一个固定的z-index
