### ISSUE TITLE
[Feature Request] select中的clearable触发

### ISSUE THREAD

**Issue by kukujbb** [ElemeFE/element#4252]
### Existing Component
是

### Component Name
select

### Description
select中的clearable 能否作为一个方法调用？？

比如在选择地区的时候，在国家，省份，城市三个select中进行筛选，能否在切换国家的时候动态去清空省份以及城市的select??而在进行省份的切换时清空城市的select？

[https://jsfiddle.net/fp8mtkwb/](url)

**Comment by Leopoldthecoder** [comment]
监听国家的 change 事件，然后给省份和城市的绑定值赋值为空即可。
