### ISSUE TITLE
[Bug Report] Table 全选问题

### ISSUE THREAD

**Issue by liujinyang1994** [ElemeFE/element#4255]
### Element UI version
1.2.8

### OS/Browsers version
全部浏览器

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/55/](https://jsfiddle.net/pj71jkyw/55/)

### Steps to reproduce
关于table 组件我有一个问题。
当Table-column type=selection
1. 我数据第一加载时，只有两条，我将两条全部选中。
2. 数据增加了8条后。变为10条时，全选的状态还在。

### What is Expected?
希望是在增加到10条后，全选状态取消，但之前选中的两条还是为选中状态

### What is actually happening?
当加到10条的时候，全选状态还在

**Comment by Leopoldthecoder** [comment]
Demo 代码有错误，`selectItems` 看上去应该是个方法，但是实际上是一个空数组。

**Comment by liujinyang1994** [comment]
@Leopoldthecoder 感谢您的回复。 demo 代码好像是因为资源加载的原因。你可以尝试本地复制一下，代码是可以用的。再次谢谢您的回复

**Comment by liujinyang1994** [comment]
@Leopoldthecoder 我已经把selectItems 修改为items 这样更方便理解

**Comment by liujinyang1994** [comment]
@Leopoldthecoder 抱歉，代码已修改，感觉您的回复

**Comment by Leopoldthecoder** [comment]
- https://jsfiddle.net/pj71jkyw/55/ 这个链接仍然是错误的
- 按照你的代码和描述，我试着写了一个 demo：https://jsfiddle.net/pj71jkyw/62/ ，这个是能正常工作的。

**Comment by Leopoldthecoder** [comment]
还是会报错，看上去 `selectItems` 并没有改

**Comment by liujinyang1994** [comment]
我的问题，可能是修改上去忘记保存了。刚刚测试了一下，这回是好用的

**Comment by liujinyang1994** [comment]
https://jsfiddle.net/pj71jkyw/66/

**Comment by Leopoldthecoder** [comment]
需要加 `row-key`：https://jsfiddle.net/leopoldthecuber/pj71jkyw/78/

可以参考文档上的 `row-key` 属性说明。

**Comment by liujinyang1994** [comment]
感谢，祝Element越办越好 @Leopoldthecoder
