### ISSUE TITLE
[Bug Report] checkbox设置默认值问题

### ISSUE THREAD

**Issue by huangshihao** [ElemeFE/element#4258]
### Element UI version
1.2.8

### OS/Browsers version
Windows 10 / Chrome  57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/HoraceHuang/xu87x9a2/](https://jsfiddle.net/HoraceHuang/xu87x9a2/)

### Steps to reproduce
使用v-for遍历生成的一组checkbox，在设置默认值之后，点选其中一个checkbox

### What is Expected?
使用v-for遍历生成的一组checkbox，在设置默认值之后，点选其中一个checkbox只会改变当前点选的checkbox的状态

### What is actually happening?
使用v-for遍历生成的一组checkbox，在设置默认值之后，点选其中一个checkbox改变了生成的所有checkbox的状态

**Comment by huangshihao** [comment]
mac OS 上也有这个问题

**Comment by Leopoldthecoder** [comment]
不需要给 el-checkbox 设置 `checked`：https://jsfiddle.net/xu87x9a2/1/

**Comment by huangshihao** [comment]
所以设置默认选中的时候只能通过设置el-checkbox-group的model值实现是嘛？

**Comment by huangshihao** [comment]
通过设置el-checkbox-group的model值实现的，但是比较麻烦，因为遍历的checkbox是从后端取的，需要在组件初始化的时候去动态设置一下 model值，谢谢帮助。
