### ISSUE TITLE
[Feature Request] option to make the colorpicker always visible

### ISSUE THREAD

**Issue by SnooHD** [ElemeFE/element#4262]
### Existing Component
Yes

### Component Name
Colorpicker

### Description
I would like to see an extra option through an attribute to always show the colorpicker.

**Comment by SnooHD** [comment]
Right now you can open / close the colorpicker by clicking on the element that holds the current active color. It would like the colorpicker to always be open.

so to always be like this:
![image](https://cloud.githubusercontent.com/assets/14291499/25129115/eec9c682-243c-11e7-9a76-10861992507b.png)

**Comment by Leopoldthecoder** [comment]
We have no plan to implement this feature. But you can contribute if you are interested.
