### ISSUE TITLE
[Bug Report] Cascader的clearable属性，点击事件不起作用

### ISSUE THREAD

**Issue by qingwufengyang** [ElemeFE/element#4265]
### Element UI version
1.2.8

### OS/Browsers version
mac /版本 55.0.2883.95 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
鼠标放上显示删除按钮，但是点击按钮不起作用

### What is Expected?
点击清空文本框内容

### What is actually happening?
点击清空文本框内容

**Comment by pengchongfu** [comment]
#4084 已经修好了

**Comment by qingwufengyang** [comment]
我的现在是1.2.8版本，还是不行

**Comment by pengchongfu** [comment]
1.2.8 还是有 bug 的，等 1.2.9 吧。或者按照那个 commit 覆盖一下css

**Comment by qingwufengyang** [comment]
好的

**Comment by Leopoldthecoder** [comment]
这两天会发布 1.2.9

**Comment by noonehide** [comment]
发布了1.2.9，说是修改好了。但是实际没用啊

**Comment by pengchongfu** [comment]
@noonehide 有用啊 https://jsfiddle.net/12kf9xgu/
