### ISSUE TITLE
[Bug Report] Upload 组件手动上传

### ISSUE THREAD

**Issue by liujinyang1994** [ElemeFE/element#4267]
### Element UI version
1.2.8

### OS/Browsers version
全部浏览器

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/79/](https://jsfiddle.net/pj71jkyw/79/)

### Steps to reproduce
所有情况都是在手动下操作
1. 当我选择一个文件，点击确定
2. 文件出现在文件列表中，但无法删除

### What is Expected?
期待是可以在确认上传前，可以更改想要上传的文件。

### What is actually happening?
文件必须在上传成功后才可以删除

**Comment by Leopoldthecoder** [comment]
1.2.9 应该修了。试试看还有没有问题，没问题的话就关了吧。
