### ISSUE TITLE
el-from 的 resetFields()方法无效

### ISSUE THREAD

**Issue by xjcloudy** [ElemeFE/element#427]
需要实现重置功能。发现有form的resetFields()方法。按照demo上的实例配置。并没有起作用。也没有出错。和demo的区别就在于没有使用rule验证。不知这个方法是否和验证是绑定在一起的？
另。发现resetFields()方法不能重置日期选择控件。demo上也是这样的。麻烦关注一下。谢谢！

**Comment by baiyaaaaa** [comment]
调用 resetFields 方法需要 form-item 组件中配置 prop 属性

**Comment by xjcloudy** [comment]
thx。

**Comment by chachaxw** [comment]
之前也碰到过这个bug，索性直接不用它的重置表单方法，自己写个重置的方法

**Comment by xjcloudy** [comment]
而且，日期控件绑定的属性空值时不能设为null。不然不会显示placeholder。而是显示的19700101.需要使用‘’空字符串作为空值

**Comment by furybean** [comment]
@baiyaaaaa @QingWei-Li 看看 @xjcloudy 反馈的这个问题。

**Comment by lovects** [comment]
我也遇到了，请问目前bug解决了吗？
