### ISSUE TITLE
[Bug Report] 选项卡切换时表格闪动

### ISSUE THREAD

**Issue by galaxycoder** [ElemeFE/element#4270]
### Element UI version
1.2.8

### OS/Browsers version
Mac OS X 10.12/ Chrome 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ewn9d0qm/](https://jsfiddle.net/ewn9d0qm/)

### Steps to reproduce
1. 在选项卡组件中，使用表格组件
2. 在页面首次加载完成后，点击选项卡切换时，表格闪动
3. 切回后不会再次闪动

### What is Expected?
表格不闪动

### What is actually happening?
闪动一次后（猜测 dom 渲染完成后），不会再次闪动

**Comment by Leopoldthecoder** [comment]
已在最新版修复。
