### ISSUE TITLE
[Feature Request] table的align属性

### ISSUE THREAD

**Issue by zhangzhiqiang37** [ElemeFE/element#4272]
### Existing Component
是

### Component Name
table

### Description
是否应该在table组件中添加一个align属性，可以直接设置整个table的对齐方式，table-column的align不填则继承，填了则覆盖table的align属性。如果没有table级别的align，那么想要整个表都是居中对齐，难道还要每个column都写一个align=“center”？

**Comment by Leopoldthecoder** [comment]
无计划增加此 API。
