### ISSUE TITLE
[Feature Request] input 能不能加入一个 keyup.enter事件

### ISSUE THREAD

**Issue by zhuxianbin** [ElemeFE/element#4273]
### Existing Component
是

### Component Name
el-input

### Description
目前无keyup行为,只能使用别的手段,比如 复制组件渲染后的静态结果再使用vue对input的@keyup进行绑定事件,那么如此做 autocomplete等的功能 就无法轻松实现...

**Comment by zhuxianbin** [comment]
https://jsfiddle.net/zhuxianbin/k7s3rtep/1/

**Comment by QingWei-Li** [comment]
[FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)

**Comment by zhuxianbin** [comment]
3Q
