### ISSUE TITLE
[Bug Report] IE下icon图标不显示，IE9-IE11

### ISSUE THREAD

**Issue by galenceme** [ElemeFE/element#4275]
### Element UI version
1.2.8

### OS/Browsers version
Win 10 IE11

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/element/issues/4274](https://github.com/ElemeFE/element/issues/4274)

### Steps to reproduce
使用IE打开element的官网，所有图标都不显示，使用chrome等其他浏览器正常，只是在IE下。

![001](https://cloud.githubusercontent.com/assets/20569168/25120998/bef078e6-2452-11e7-9494-f792f9e2a5c1.png)

-----------------------------------------------------------------------------------------------------------------

![002](https://cloud.githubusercontent.com/assets/20569168/25121011/cec01934-2452-11e7-96c7-9720a8f974d2.png)

-----------------------------------------------------------------------------------------------------------------

![003](https://cloud.githubusercontent.com/assets/20569168/25121029/dd38b372-2452-11e7-9a2d-e729936b025b.png)

### What is Expected?
能够正常显示图标

### What is actually happening?
没有正常显示

**Comment by Leopoldthecoder** [comment]
![image](https://cloud.githubusercontent.com/assets/10095631/25132463/44b492ae-247c-11e7-89c1-5cda164f203b.png)

我这边是正常的，不确定是不是版本的问题，可以升级试试。

**Comment by HereChen** [comment]
确实有这个问题。并且控制台无报错。对比 Chrome，IE 11 下字体图标没有加载。

**Comment by dielangsea** [comment]
我这边在win7上的ie11不正常，但是在win7上的ie10正常

**Comment by ghwyf** [comment]
css3111  https://stackoverflow.com/questions/33023461/ie-11-error-css3111-in-my-own-code-and-google-com-fonts-doesnt-render-any-fon

**Comment by goSunadeod** [comment]
用cdn引用就可以解决，但是这种情况如何解决的呢，https下的ie下不显示icon

**Comment by jerry-f** [comment]
我这边的ie10 不显示图标， 打开官网也是
看有些网站（https://blog.csdn.net/weixin_42204698/article/details/102630225）说可以引入 .eot字体 但是我将官网的字体转为eot字体还是不显示；
![image](https://user-images.githubusercontent.com/30689170/81888712-7ebad400-95d4-11ea-9c5e-2fa4ae4ddf7c.png)
