### ISSUE TITLE
[Bug Report] el-tag 可移除标签无效

### ISSUE THREAD

**Issue by koromon** [ElemeFE/element#4283]
### Element UI version
1.2.8

### OS/Browsers version
mac OS X 10.10 / chrome 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/2zyp3r8L/](https://jsfiddle.net/2zyp3r8L/)

### Steps to reproduce
<el-tag> 组件 closable 属性设置为 true，点击删除标签没有反应

### What is Expected?
点击标签会删除

### What is actually happening?
点击标签无反应

**Comment by Leopoldthecoder** [comment]
删除逻辑需要自己在 `close` 回调里写，参考：http://localhost:8085/#/zh-CN/component/tag#dong-tai-bian-ji-biao-qian
