### ISSUE TITLE
[Bug Report] table列出现错位

### ISSUE THREAD

**Issue by gjycdd** [ElemeFE/element#4284]
### Element UI version
1.2.8

### OS/Browsers version
win10

### Vue version
2.1.8

### Reproduction Link
[https://jsfiddle.net/u877urf2/](https://jsfiddle.net/u877urf2/)

### Steps to reproduce
1.将table底部的滚动条拉到右侧
2.列出现了错位

### What is Expected?
table不会错位

### What is actually happening?
table错位

**Comment by zhaiyy** [comment]
请问是否解决，同出现一样的问题

**Comment by furybean** [comment]
@gjycdd 把版本锁定到 1.2.8，无法重现此问题：https://jsfiddle.net/u877urf2/1/

**Comment by gjycdd** [comment]
这个问题应该是很久以前提的了，得有9-10个月样子了，早就没问题了。现在都2.0了，如果还没修复的话才是比较奇怪。
