### ISSUE TITLE
Fecture Request table 行高与 index 问题

### ISSUE THREAD

**Issue by blankPage0806** [ElemeFE/element#4285]
**Existing Component**
  是
**Component Name**
    table
**Element UI version**
   1.2.8
**OS/Browsers version**
 win 10 chrome
Description:
行高：
可否保持table 行高固定。
[https://jsfiddle.net/api/post/library/pure/](url)
index：
翻页后，index重新计算，可否保持累加。
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by yamateH-ch** [comment]
老铁，请问你怎么实现index不重新计算的问题
