### ISSUE TITLE
el-tree 在el-dialog中抖动

### ISSUE THREAD

**Issue by sdlddr** [ElemeFE/element#4286]
如题，如果使用了checkbox的el-tree是在一个弹出框el-dialog中的话，那么当打开弹出框，进行对el-tree的复选框进行点击操作时，对话框文字、el-tree的每一行文字都会轻微抖动一次，让人看了眼睛花，影响了用户体验。
该问题现象在chrome浏览器上，当页面的垂直滚动条不存在时，就会发生；当页面的垂直滚动条存在后，该现象不再发生。
在其它浏览器上则不存在此问题。

**Comment by Leopoldthecoder** [comment]
Duplicate of #2461
