### ISSUE TITLE
[Feature Request] 在Tree组件中希望加入节点名称过长的解决方案

### ISSUE THREAD

**Issue by hearain** [ElemeFE/element#4287]
### Existing Component
是

### Component Name
Tree

### Description
如果当前节点文字宽度超出了父节点的宽度，会撑破父节点，如果给了overflow auto属性，tree的子节点文字过长会显示不全
希望给出鼠标悬浮显示全部标题文字的Tooltip，或者更优的解决方案，谢谢
![image](https://cloud.githubusercontent.com/assets/9176349/25125018/0470e89e-2460-11e7-9bc6-f5f31b90c4c5.png)
加滚动条真丑。。。。

**Comment by Leopoldthecoder** [comment]
可以自己用 `render-content` 处理。
