### ISSUE TITLE
[Bug Report] DatePicker type是daterange时打开窗口即触发值改变

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#4288]
### Element UI version
1.2.8

### OS/Browsers version
win10/chrome 56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/trgq6f4h/1/](https://jsfiddle.net/trgq6f4h/1/)

### Steps to reproduce
第一次选中日期后, 再次点击选择框,就触发了watch的方法。这个问题类似 https://github.com/ElemeFE/element/issues/1834

### What is Expected?
选择日期之后再触发

### What is actually happening?
没选择就触发了

**Comment by Leopoldthecoder** [comment]
直接使用 change 事件：https://jsfiddle.net/leopoldthecuber/trgq6f4h/3/
