### ISSUE TITLE
升级rc.7，menu导航切换路由报错

### ISSUE THREAD

**Issue by TDiDa** [ElemeFE/element#429]
ElementUI version 1.0.0-rc.7

Vue version 2.0.3 

![image](https://cloud.githubusercontent.com/assets/18672870/19388421/14f2ba94-9252-11e6-95e0-b5db9fa688cc.png)

``
<el-menu mode="vertical" :default-active="path" :router="true">
      <el-submenu index="/Shop">
        <template slot="title"><i class="iconfont">&#xe600</i>店铺</template>
        <el-menu-item index="/Shop" class="el-menu-item" active-class="is-active">店铺列表</el-menu-item>
      </el-submenu>
      <el-submenu index="/User">
        <template slot="title"><i class="iconfont">&#xe605</i>会员</template>
        <el-menu-item index="/User" class="el-menu-item" active-class="is-active">会员列表</el-menu-item>
      </el-submenu>
    </el-menu>
``

**Comment by baiyaaaaa** [comment]
麻烦能在这里重现下吗 https://jsfiddle.net/gmve9d3p/

**Comment by yaomingdan** [comment]
router-view增加keep-alive就不会了，我也是报一样的错误,原因未知

**Comment by perfectyang** [comment]
我的也是，跟路由切换有关系

**Comment by baiyaaaaa** [comment]
http://jsfiddle.net/WhiteCusp/pvyuhfsb/ @yaomingdan @perfectyang 没有报错

**Comment by TDiDa** [comment]
@yaomingdan @perfectyang @baiyaaaaa 
不使用element的menu的路由切换，也是报错，把路由切换的transition去掉就没问题了，不是element的问题，应该是vue自己的问题

**Comment by baiyaaaaa** [comment]
#474

**Comment by baiyaaaaa** [comment]
@TDiDa Hi, 能麻烦你帮忙提供个在线例子么？
