### ISSUE TITLE
[Bug Report] 少数据到多数据的时候报错

### ISSUE THREAD

**Issue by ieiayaobb** [ElemeFE/element#4290]
### Element UI version
1.2.8

### OS/Browsers version
chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ieiayaobb/mcyczfa9/20/](https://jsfiddle.net/ieiayaobb/mcyczfa9/20/)

### Steps to reproduce
等一秒替换数据就会报错

### What is Expected?
不会报错

### What is actually happening?
报错：
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by Leopoldthecoder** [comment]
麻烦精简一下 demo，数据有些杂。

**Comment by ieiayaobb** [comment]
https://jsfiddle.net/ieiayaobb/mcyczfa9/21/
精简了一下，麻烦看一下，早之前的版本没有这个问题

**Comment by Leopoldthecoder** [comment]
因为开始时的数据不合法吧（第一秒里第三列是 undefined），修改一下就不报错了：https://jsfiddle.net/leopoldthecuber/mcyczfa9/22/

**Comment by ieiayaobb** [comment]
多谢，我来检查一下我的数据。顺便问一下，怎么样拿你们的代码做源码依赖？比如我想自己修了bug然后发PR

**Comment by ieiayaobb** [comment]
第一秒里第三列数据是个object({"ddd":"2"})，这样的数据要序列化成字符串才行吗？

**Comment by Leopoldthecoder** [comment]
是的。

关于源码依赖，修改 Element 的代码后执行 npm run dist，然后引用生成的文件即可。
