### ISSUE TITLE
[Feature Request] datetime picker在 Window下 和 mac下时间格式不一致，时间格式受到系统语言设置的影响

### ISSUE THREAD

**Issue by javasgl** [ElemeFE/element#4292]
### Element UI version
1.2.8

### OS/Browsers version
Windows7 / Chrome 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[http://jsbin.com/lafejetiwe/edit?html,output](http://jsbin.com/lafejetiwe/edit?html,output)

### Steps to reproduce
相同代码，在mac 系统和 windows系统下对比看效果。
选择时间后，v-model绑定的值的格式不一致，windows用户，会有 (中国标准时间) 这几个汉字，而mac用户，则不会出现这几个汉字。

### What is Expected?
相同的代码，时间选择后，v-model绑定的值的格式应该是完全一致的，不能因为换了OS而导致值的格式不一致。

### What is actually happening?
实际上是因为date picker控件对时间的格式没有做标准化处理，从而导致在不同的操作系统下，相同日期时间 的格式不一致。
应该将底层v-model绑定的值都统一成一致，避免因操作系统不同而v-model对应的值 不同。
建议 统一成 时间戳，因为时间戳是唯一的数值型的值，是全球通用唯一的。它不会受到 操作系统 和 系统时区 的影响，不会有 东八区 和 格林威治 时间的困扰。

**Comment by javasgl** [comment]
没有在Mac OS 下重现过。我司测试人员 在 Windows 上的浏览器 100%重现，而在Mac os 上 100% 正常。

**Comment by javasgl** [comment]
英文版系统：会显示成 CST
`startTime:Tue, 18 Apr 2017 20:47:45 +0800 (CST)`
`endTime:Sun Apr 30 2017 20:47:45 GMT+0800 (CST)`

而中文版系统：会显示成 中国标准时间
`startTime:Tue, 18 Apr 2017 20:47:45 +0800 (中国标准时间)`
`endTime:Sun Apr 30 2017 20:47:45 GMT+0800 (中国标准时间)`

代码完全是一致的，而因为操作系统的语言设置问题导致获取到值 不一致。
成熟的日期时间控件应该 不受操作系统的种类、版本、语言、时区的影响才对。

**Comment by javasgl** [comment]
![image](https://cloud.githubusercontent.com/assets/5222868/25142800/cb3b4a02-249a-11e7-868d-dbf898195bbf.png)
相同的代码，因系统语言不一样而导致 控件的值不一样，从而导致后端代码解析时间异常。

**Comment by javasgl** [comment]
现在只能在提交给后端服务之前 手动将时间转为 时间戳了。
```
if ((typeof req.startTime) == 'number') {
       req.startTime = req.startTime / 1000;
} else {
     req.startTime = new Date(req.startTime).getTime()/1000;
}
if ((typeof req.endTime) == 'number') {
     req.endTime = req.endTime / 1000;
} else {
      req.endTime = new Date(req.endTime).getTime()/1000;
}
```

**Comment by jikkai** [comment]
各系统浏览器对 Date 实现不同造成的，不算是 Element 的问题吧

**Comment by javasgl** [comment]
但是从 通用组件的设计角度来说，应该屏蔽掉 操作系统、语言、时区的影响来确保组件在任何平台或系统之前表现是一致的。
想想前些年Jquery 之所以流行就是因为 它解决了 很多IE浏览器和其他浏览器的兼容问题，让相同的代码在多数浏览器上的表现时一致的

**Comment by wacky6** [comment]
DatePicker的value是Date对象，如有需要，建议自行格式化成字符串。

**Comment by goodjack** [comment]
最近也遇到了這個問題，很是困擾。
請問這 issue 會解決嗎？？

**Comment by javasgl** [comment]
看样子官方是不打算解决这个问题了
只有自己解决了。

**Comment by javasgl** [comment]
@Leopoldthecoder @QingWei-Li  Consider this issue?

**Comment by jikkai** [comment]
@javasgl 所以说了这个不是 BUG……建议多了解下 JavaScript 的内置 [Date 对象](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

设计上就是返回给用户一个 Date 对象，方便用户对其进行各种操作，如果直接 format 成字符串的话，用户再要进行诸如二次 format、转换时间戳、时区纠偏之类的问题就很难甚至不能操作了。

**Comment by javasgl** [comment]
恩，不是一个bug。 更像是一个 Feature

**Comment by jikkai** [comment]
@javasgl Yep

**Comment by javasgl** [comment]
修改了 issue标题了，以免被误认为是 bug ..... 😂

**Comment by Leopoldthecoder** [comment]
So your request is for us to change v-model to a timestamp?

**Comment by goodjack** [comment]
+1 plz!!!

**Comment by javasgl** [comment]
@Leopoldthecoder  or provide a option like 'dateformat'  to

**Comment by Leopoldthecoder** [comment]
I'm afraid we won't change this. `v-model` of DatePicker will stay a `Date`.

Once you have a date-typed value, you can format it to whatever form you like. If the server requires some certain format, you are free to transform the date before submitting it.

Plus I have something to say about *cross-OS inconsistency*. The value of `v-model` is consistent across different OSs since it's a Date object. The reason you see `中国标准时间` instead of `CST` on Windows is that the displayed text is just a string representation, not the Date object itself. Different OSs/browsers may have different implementations for string representation, but under the hood, they have the same date.

**Comment by jyj1993126** [comment]
One solution : 
```
Date.prototype.yyyymmdd = function () {
    var mm = this.getMonth() + 1; // getMonth() is zero-based
    var dd = this.getDate();

    return [this.getFullYear(),
        (mm > 9 ? '' : '0') + mm,
        (dd > 9 ? '' : '0') + dd
    ].join('-');
};

<el-form-item label="生日">
    <el-date-picker
            :value="form.birthday"
            @input="val => form.birthday = val ? val.yyyymmdd() : ''"
            type="date"
            placeholder="选择日期"
    >
</el-date-picker>
```
while the value changes inside `el-date-picker` , the input event fires.
