### ISSUE TITLE
[Bug Report] Component's loaders in table

### ISSUE THREAD

**Issue by efureev** [ElemeFE/element#4294]
### Element UI version
1.2.8

### OS/Browsers version
Safari

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/83/](https://jsfiddle.net/pj71jkyw/83/)

### Steps to reproduce
https://forum.vuejs.org/t/element-ui-help-to-create-many-loaders-in-tables/9793

**Comment by syn-zeta** [comment]
Please try to describe an issue better. I'm guessing you were after this:

https://jsfiddle.net/pj71jkyw/84/
