### ISSUE TITLE
[Bug Report] 在有文本选中的情况下，Radio Button 单击无效，双击才有效

### ISSUE THREAD

**Issue by 188007803** [ElemeFE/element#4298]
### Element UI version
1.2.8

### OS/Browsers version
win7

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
1、选择Radio Button之外的若干字符，https://jsfiddle.net/pj71jkyw/
2、此时 Radio Button 单击无效，双击才有效。包括在官方示例中。

### What is Expected?
应该单击有效

### What is actually happening?
单击无效，双击有效

**Comment by Leopoldthecoder** [comment]
Fixed in #4217
