### ISSUE TITLE
[Bug Report] 在表单验证里，类型是number的，在我先输入数字然后输字母的也能验证通过，只要开头数字就能验证通过

### ISSUE THREAD

**Issue by YangZhenFang** [ElemeFE/element#4299]
### Element UI version
1.2.8

### OS/Browsers version
macos ／ 谷歌浏览器

### Vue version
2.2.6

### Reproduction Link
https://jsfiddle.net/yvqmjzas/

### Steps to reproduce
在年龄输入框，先输入数字，然后输入字母，验证通过。

### What is Expected?
只有输入数字才能验证通过。

### What is actually happening?
输入数字 字母验证通过。

**Comment by Leopoldthecoder** [comment]
That's how the `.number` modifier works in Vue: https://jsfiddle.net/leopoldthecuber/yvqmjzas/1/
