### ISSUE TITLE
新手问个问题

### ISSUE THREAD

**Issue by liwei1991** [ElemeFE/element#430]
为什么我用的时候控制台总有这些报错信息输出呢
Property or method "handleopen" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
vue.js?b6db:2611 [Vue warn]: Property or method "handleclose" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <hello> at D:\WWW\xms\public\src\components\Hello.vue)

**Comment by baiyaaaaa** [comment]
element 无关问题

**Comment by furybean** [comment]
@liwei1991  意思是 handleopen handleclose 并没有在 实例上 定义，但是在 template 里面引用了。
