### ISSUE TITLE
color picker 颜色拾取错位

### ISSUE THREAD

**Issue by Longui** [ElemeFE/element#4300]
### Element UI version
1.2.8

### OS/Browsers version
win7/chrome 57.0.2987.133/firefox last

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/0okt7mt0/](https://jsfiddle.net/0okt7mt0/)

### Steps to reproduce
color picker组件放进el-form-item就出问题

### What is Expected?
color picker组件放进el-form-item不出问题

### What is actually happening?
等待解决或不使用el-form-item

**Comment by Leopoldthecoder** [comment]
Fixed in #4303
