### ISSUE TITLE
[Feature Request] tree树形控件 选中子节点，可以拿到祖先节点的id

### ISSUE THREAD

**Issue by jialuchun** [ElemeFE/element#4302]
### Existing Component
是

### Component Name
tree树形控件

### Description
tree树形控件 选中子节点，可以拿到祖先节点的id和label？

**Comment by jialuchun** [comment]
http://element.eleme.io/#/zh-CN/component/tree

**Comment by jialuchun** [comment]
选中子节点，可以返回此子节点的id和label祖先节点的id和label？

**Comment by wilsonIs** [comment]
你让后端返回这两个字段不就好了。。。

**Comment by Leopoldthecoder** [comment]
无此计划。这个需求可以通过在数据中遍历查找解决。
