### ISSUE TITLE
[Bug Report] el-steps direction="vertical" 时，设置 center="true"不生效

### ISSUE THREAD

**Issue by gelif** [ElemeFE/element#4306]
### Element UI version
1.2.8

### OS/Browsers version
windows10， chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/4f8y89Ls/](https://jsfiddle.net/4f8y89Ls/)

### Steps to reproduce
打开就可以看到

### What is Expected?
居中

### What is actually happening?
靠左

**Comment by Leopoldthecoder** [comment]
vertical 的 Steps 不支持 center 属性。想居中的话可以这样：https://jsfiddle.net/leopoldthecuber/4f8y89Ls/1/
