### ISSUE TITLE
[Feature Request] tree组件  点击节点展开和折叠问题

### ISSUE THREAD

**Issue by hojit** [ElemeFE/element#4308]
### Existing Component
是

### Component Name
tree

### Description
当show-checkbox为true的时候，点击节点是不会展开或者折叠，必须要点击三角图标
当show-checkbox为false的时候，能否也提供一个属性设置，必须只能点击三角图标展开折叠，而点击树形节点的时候不展开或者折叠呢？

**Comment by Leopoldthecoder** [comment]
无计划增加此 feature
