### ISSUE TITLE
[Feature Request] allow render `message` content as plain html in MessageBox

### ISSUE THREAD

**Issue by ioslh** [ElemeFE/element#4313]
### Existing Component
Yes

### Component Name
message-box

### Description
In some cases it is useful to render some simple rich text in message box, and it is too complex to use a `Dialog` component. 

A use case maybe as follow screenshot:

![](http://oslhtemp.qiniudn.com/17-4-19/27931967-file_1492592242341_10f6b.png)

Advice Change:

// ./packages/message-box/src/main.vue
```
-    <p>{{ message }}</p>
+    <p v-html="message"></p>
```

**Comment by Leopoldthecoder** [comment]
#2712

For some safety concerns, `v-html` may not be the best solution. I plan to implement this feature using render function. Send a PR if you're interested.

**Comment by ioslh** [comment]
Got it, thank you.

**Comment by codelabstudios** [comment]
also looking for this feature, would be nice to render html tags within messages

**Comment by Leopoldthecoder** [comment]
@codelabstudios I have just push #4550. It will be included in 1.3.0-beta.3
