### ISSUE TITLE
[Bug Report] tree 树，通过key获取,全选返回的是从跟节点到子节点，选一个返回的是子节点

### ISSUE THREAD

**Issue by githubjaychen** [ElemeFE/element#4314]
### Element UI version
1.2.8

### OS/Browsers version
Google Chrome 版本 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
https://jsfiddle.net/ruqbw1m5/

### Steps to reproduce
打开浏览器console,选中“三级 1-1-1”，点击通过key获取，得到的数值是[9]，选中 “三级 1-1-1”  “三级 1-1-2“ ，点击key获取，得到的数值是 [1, 4, 9, 10]，所以选中一个获取的值是最后一个节点，选中根节点的全部 获取的是全部节点

### What is Expected?
文档中说的是：getCheckedKeys (leafOnly) 接收一个 boolean 类型的参数，若为 true 则仅返回被选中的叶子节点的 keys，默认值为 false，如果是leafOnly = false，应当返回数值是全部节点值，但是并没有返回

### What is actually happening?
选中全部和单个返回的值不一致

**Comment by githubjaychen** [comment]
已更新链接，其实就是官方的例子

**Comment by Vic-tsunami** [comment]
您说的问题我试了,并没有出现啊

**Comment by Leopoldthecoder** [comment]
`getCheckedKeys` 返回的节点必须是 `checked` 的，即 checkbox 框中有对勾的节点才会被返回。仅选中 `三级 1-1-1` 时，其两个祖先节点（节点 1 和节点 4）的状态不是 `checked`，所以不会被返回，与「选中一个」还是「选中全部」无关。

**Comment by ashinzz** [comment]
父节点非全选状态下getCheckedKeys方法只能得到选中子节点的key，如果我想得到父节点和下面选中的子节点的key呢？建议增加一个方法可以得到非全选状态下的父节点的key，set的时候也能set进去

**Comment by leo-lai** [comment]
@ashinzz 我也是碰到这个需求，有解决方案吗

**Comment by hasbug** [comment]
貌似2.X版本还是没有这个的解决方案，一些曲线救国的  也不大好使。。。

**Comment by kuangshu** [comment]
我也有这个需求，不知道上面各位解决了么？
