### ISSUE TITLE
[Bug Report] 表格里面点击查看按钮，弹出dialog，dialog会被遮罩层遮罩。怎么解决？ 

### ISSUE THREAD

**Issue by DoryDuan** [ElemeFE/element#4316]
### Element UI version
1.2.8

### OS/Browsers version
windows

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/r5t3vcx9/](https://jsfiddle.net/r5t3vcx9/)

### Steps to reproduce
表格里面点击查看按钮，弹出dialog，dialog会被遮罩层遮罩

### What is Expected?
让dialog显示在遮罩层的上面

### What is actually happening?
dialog被遮住了

**Comment by Leopoldthecoder** [comment]
Dialog 写在 Table 外部更合理一些。如果 Dialog 的内容是由 Table 某一行的数据决定的，在点击 Table 的按钮时，将相应行的信息传出来就可以。

**Comment by yuanshengchao** [comment]
你可以查看对应的遮罩的z-index属性，把它设置高点或者设置为！important就好

**Comment by AlenWang** [comment]
@Leopoldthecoder 如果对表格每行中的图片进行预览的dialog，必须放在表格中，这样被挡住的情况怎么处理？
