### ISSUE TITLE
[Bug Report] <el-form>内，使用含有v-if指令的子元素，导致input等表单元素只能输入一个字符

### ISSUE THREAD

**Issue by Astlvk** [ElemeFE/element#4320]
### Element UI version
1.2.8

### OS/Browsers version
Windows10/chrome 57.0.2987.133( 64bit)

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/2fmh7kmq/2/](http://jsfiddle.net/2fmh7kmq/2/)

### Steps to reproduce
\<el-form>内
1. 编写使用v-model绑定的input文本框
2. 在该文本框前后编写含有v-if指令的任意两个元素
3. 令以上两个v-if的值都为false
4. 用该文本框进行输入

### What is Expected?
可以正常输入

### What is actually happening?
初次输入第一个字符后即自动失去焦点，导致只能输入一个字符，无法正常输入。  
再次选中后才恢复正常。  
已测试的文本框、textarea、select元素都会不符合预期的自动失去焦点。  
如果不使用v-model进行绑定则不会有该问题，亦或前后至少有一个v-if为true也不会出现该情况。

详情请看重现链接

**Comment by Astlvk** [comment]
题外话，好奇的尝试用当前的ivew(2.0)进行重现，有同样结果U_U....
[ivew重现](http://jsfiddle.net/2fmh7kmq/3/)

**Comment by pengchongfu** [comment]
@Astlvk 我测试了一个很简单的 demo，貌似和组件库没有关系。只要组件里用了 `<slot></slot>` 并且里边有上述的 `<input v-if="false"/>` 就会这样。

Vue2.2.6 会有这个问题。但是最新的 dev 分支好像并不会有这个问题。

**Comment by Astlvk** [comment]
@pengchongfu 
3Q，编译了下vue dev分支，替换后没有这个问题了。

**Comment by Leopoldthecoder** [comment]
既然不是 Element 的问题，那么这个 issue 先关了。
