### ISSUE TITLE
[Feature Request] massage-box 新增 inputType 提供选择型态

### ISSUE THREAD

**Issue by happyUpset** [ElemeFE/element#4327]
### Existing Component
是

### Component Name
massage-box 

### Description
使用massage-box 时
有时候我会需要只能输入 number 的情况，看是目前并没有办法让我做控制，目前都是text为主。
希望未来能有个像是 inputType 的方法，可以提供修改 <input> 的型态

**Comment by Leopoldthecoder** [comment]
暂无计划，尽量还是保持 MessageBox 的轻量。可以自己操作 DOM 来处理这个需求。
