### ISSUE TITLE
[Feature Request] [Dialog]重要需求：可否设置可拖拽属性？

### ISSUE THREAD

**Issue by guanjianjun** [ElemeFE/element#4330]
### Existing Component
是

### Component Name
dialog

### Description
写对话框打开后，不能拖动，挡住后面的内容。

**Comment by guanjianjun** [comment]
http://element.eleme.io/#/zh-CN/component/dialog

**Comment by baiyaaaaa** [comment]
从交互上讲，这个并不合理，既然弹出了dialog就应该关注在dialog当中进行交互。应该不会考虑这个功能

**Comment by Leopoldthecoder** [comment]
无支持计划。

**Comment by lyon007** [comment]
没有支持就自己写啊

**Comment by fqy110** [comment]
请问这个需求不会加吗，因为在实际业务中，在对话框里填写内容的时候需要参考弹窗背后的页面内容，这个是业务方强烈需求的
