### ISSUE TITLE
[Bug Report] Table 通过数据改变 width和min-width配置  表格会爆掉

### ISSUE THREAD

**Issue by bigrocs** [ElemeFE/element#4331]
### Element UI version
1.2.8

### OS/Browsers version
谷歌IE 都会出现

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/105/](https://jsfiddle.net/pj71jkyw/105/)
[https://jsfiddle.net/pj71jkyw/762/](https://jsfiddle.net/pj71jkyw/762/)

### Steps to reproduce
点击按钮 width配置1 和 width配置2 互相切换  下面表格会爆掉

### What is Expected?
通过数据改变width和min-width时表格不要爆掉

### What is actually happening?
表格会爆掉

**Comment by githubzhanglei3** [comment]
没人解决这个问题吗？ 我也遇到了

**Comment by bigrocs** [comment]
因为源码width 和min-width  是在created中设置的所以  只有在第一次创建组件的时候才能设置  如果第二层使用width就会爆掉
我的临时解决办法是 用if 对组件销毁创建

**Comment by no-simple** [comment]
这几天正被这问题困扰，有合适的解决方子？

**Comment by Bimbaloo** [comment]
我也考虑只能使用ifj进行销毁重新创建，但是这样有完全没有了vue本身的性能上的有点

**Comment by furybean** [comment]
@bigrocs 你例子里面的问题是因为 width 用了 string 类型，换成 Number 就可以解决：https://jsfiddle.net/pj71jkyw/763/

**Comment by Wellaiyo** [comment]
@furybean 呵呵哒

**Comment by bigrocs** [comment]
可能新版本已经不存在这个问题了。  我发布这个问题的时候很早了

**Comment by furybean** [comment]
@bigrocs 新版本存在：https://jsfiddle.net/pj71jkyw/762/

**Comment by bigrocs** [comment]
我到时发布问题的时候都测试过  数据类型不影响这个bug

**Comment by furybean** [comment]
@Wellaiyo 

> 删我评论解决不了任何问题

发表无意义的评论也不会解决任何问题，所以删掉。

> 你不觉得这个设计很蠢吗

是的，很蠢。不知道这样你是否满意了？

**Comment by furybean** [comment]
@Wellaiyo 

> 删我评论解决不了任何问题

发表无意义的评论也不会解决任何问题，所以删掉。

> 你不觉得这个设计很蠢吗

这个不是设计问题，是实现的问题。

**Comment by furybean** [comment]
@bigrocs 应该是你记错了，可以对比下 https://jsfiddle.net/pj71jkyw/765/ 和 https://jsfiddle.net/pj71jkyw/763/

**Comment by bigrocs** [comment]
@furybean 可能是vue更新了版本的问题 当时我所有的数据类型 都试过 确定没有记错

**Comment by furybean** [comment]
2.1.0 版本已修复此问题：https://jsfiddle.net/pj71jkyw/771/
