### ISSUE TITLE
[Bug Report] el-tag用@click绑定点击事件不成功

### ISSUE THREAD

**Issue by no5no6** [ElemeFE/element#4333]
### Element UI version
0.1.0

### OS/Browsers version
chrome 版本 59.0.3067.0

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/LittleChild/bkdd45ff/](https://jsfiddle.net/LittleChild/bkdd45ff/)

### Steps to reproduce
点击tag

### What is Expected?
用@click成功绑定点击事件

### What is actually happening?
@click绑定后没有任何反应

**Comment by Leopoldthecoder** [comment]
提 issue 前请阅读 FAQ。

**Comment by no5no6** [comment]
看到了，谢谢。

**Comment by peterzhanghui** [comment]
怎么解决的
