### ISSUE TITLE
[Feature Request] 上传图片添加限制

### ISSUE THREAD

**Issue by a044161** [ElemeFE/element#4335]
### Existing Component
Yes

### Component Name
http://element.eleme.io/#/zh-CN/component/upload

### Description
上传图片时时常是需要做数量限制处理，并隐藏上传按钮等操作

**Comment by baiyaaaaa** [comment]
参考这个实现 http://element.eleme.io/#/zh-CN/component/upload#shang-chuan-wen-jian-lie-biao-kong-zhi
