### ISSUE TITLE
[Bug Report] 表单验证如果默认绑定值是数字的时候，required验证出错

### ISSUE THREAD

**Issue by webJing** [ElemeFE/element#4338]
### Element UI version
1.2.9

### OS/Browsers version
macOS 10.12.1/chrome 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/jtd1gonn/1//](https://jsfiddle.net/jtd1gonn/1//)

### Steps to reproduce
当input默认有绑定指且为数字，此input有一条required的验证,当鼠标移到input上不编辑然后blur时，会对有默认值的input验证报错。

### What is Expected?
数字也能进行验证通过

### What is actually happening?
有默认值为数字的input报为空的错误

**Comment by lucifercha** [comment]
我也是 console一直提示 xxx is not a string

**Comment by Leopoldthecoder** [comment]
需要显式指定 type: 'number'

**Comment by mosejiang** [comment]
我们也碰到xxx is not a string的问题了，在input上也配置了v-model.number，然后输入了数字，报错，求大神指点
我们外层有一个for
<el-form-item
		            		label = "目标金额 "
		            		:prop="'storeList.' +index + '.targetAmount' "
		            		:rules="[{required: true, message: '金额不能为空' , trigger: 'blur'},
		            			{type:'number', message: '金额必须为数字值', trigger: 'blur'}
			            	]"
		            	>
	            		<el-input 
	            			v-model.number="store.targetAmount" 
	            			:disabled="!store.isChk" 
	            			size ="small"
		            		:maxlength = "5"
	            			class="u-ipt tar-ipt" 
	            			auto-complete="off" 
	            			placeholder="金额">
	            		</el-input>万元
	          		</el-form-item>
