### ISSUE TITLE
Dialog不能触发close回调

### ISSUE THREAD

**Issue by mahavira** [ElemeFE/element#434]
> `<el-dialog v-model="visible" @close="close">
    <p>这是一段信息</p>
</el-dialog>`

其中visible是vuex的state，因为不能直接修改visible，所以当点击右上角X或按下ESC后并没有触发close的回调。

不知道有什么好的解决方法？
或者是否可以在close回调之前添加一个beforeClose来解决这个问题。
问题复现在这里
https://jsfiddle.net/ssjedcw/1e9sm2oo/8/

**Comment by baiyaaaaa** [comment]
组件状态模型完全没必要使用 Vuex 进行管理

**Comment by QingWei-Li** [comment]
@input 啊

**Comment by erguotou520** [comment]
`:value="visible" @input="store.dispatch(xxx)"`类似
