### ISSUE TITLE
[Bug Report] form 校验数字bug

### ISSUE THREAD

**Issue by lucifercha** [ElemeFE/element#4340]
### Element UI version
1.2.5

### OS/Browsers version
win7/chrome 50

### Vue version
2.2.2

### Reproduction Link
https://jsfiddle.net/scu4xw0d/

### Steps to reproduce
不需要重现，官网的例子上就有这个问题

### What is Expected?
正确验证数字

### What is actually happening?
数字验证 aa11验证不通过，如果是11啊啊验证就能通过

**Comment by Leopoldthecoder** [comment]
这就是 Vue 对 `v-model.number` 的处理方式：https://jsfiddle.net/leopoldthecuber/scu4xw0d/1/

**Comment by totzcc** [comment]
我觉得 这个组件可以不使用 ```v-model.number``` 语法啊 直接用 ```v-model``` 不就没这个问题了？
