### ISSUE TITLE
Tree 树形控件Events里关于current-change

### ISSUE THREAD

**Issue by lytdev** [ElemeFE/element#4341]
Element UI version

1.2.9

OS/Browsers version

Google Chrome 版本 57.0.2987.133

Vue version

2.8.1

current-change文档的说明是“当前选中节点变化时触发的事件“，但是使用复选框的时候，切换选中和非选中状态时，并未触发事件，而是点击节点文本的时候触发了事件，效果和node-click是一样的。

请问这个是不是个BUG

**Comment by saonian** [comment]
确实存在
