### ISSUE TITLE
[Bug Report] Events里关于current-change不触发

### ISSUE THREAD

**Issue by lytdev** [ElemeFE/element#4343]
### Element UI version
1.2.9

### OS/Browsers version
Google Chrome 版本 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/liuyuantao/mL3uuw19/1/](https://jsfiddle.net/liuyuantao/mL3uuw19/1/)

### Steps to reproduce
选中复选框或者取消选中复选框的时候并未出发事件，在点击节点文字的时候触发了事件，和node-click一样了

### What is Expected?
选中复选框或者取消选中复选框的时候并未出发事件

### What is actually happening?
在点击节点文字的时候触发了事件，和node-click一样了

**Comment by Leopoldthecoder** [comment]
current-change 是当前高亮行（需要配合 highlight-current 使用）发生变化时的事件。选中复选框或者取消选中复选框触发的事件是 check-change。
