### ISSUE TITLE
[Bug Report] IE11下dialog闪屏

### ISSUE THREAD

**Issue by CaraDelevingne** [ElemeFE/element#4346]
### Element UI version
1.2.9

### OS/Browsers version
win10/chorme57

### Vue version
2.2.6

### Steps to reproduce
IE11下关闭dialog时 , 会出现闪屏 , 然后再关闭

### What is Expected?
正常关闭

### What is actually happening?
dialog闪屏并且dialog中表单的组件赋值失败

**Comment by Leopoldthecoder** [comment]
没有重现链接的 bug report 会被直接关闭。

**Comment by onlymisaky** [comment]
建议使用v-if，在dialog显示时重新渲染
