### ISSUE TITLE
table表格bodyWidth计算问题

### ISSUE THREAD

**Issue by pizijun** [ElemeFE/element#435]
1. 问题复现url：[https://jsfiddle.net/zejun/g6rvneca/3/](https://jsfiddle.net/zejun/g6rvneca/3/)

2. 加载页面时并请求数据，第一个表格的bodyWidth是没问题的，可以正常显示，但后面几个是有问题的，宽度很短。在$calcColumns计算时除第一个表格外其他的table组件的this.$el.clientWidth总返回为0

**Comment by furybean** [comment]
这个问题已经修复，使用 rc7 即可：
```
<script src="//unpkg.com/element-ui@1.0.0-rc.7/lib/index.js"></script>
```
