### ISSUE TITLE
[Feature Request] toolTip组件的200毫秒延迟消失

### ISSUE THREAD

**Issue by Missyanwen** [ElemeFE/element#4351]
### Existing Component
是

### Component Name
toolTip

### Description
这个200毫秒的延迟消失能不能由开发者自己去控制，
有时我不想要200毫秒的延迟
还有那个enterable属性(鼠标是否可进入到 tooltip 中)设为根本没用

**Comment by Missyanwen** [comment]
http://element.eleme.io/#/zh-CN/component/tooltip

**Comment by Leopoldthecoder** [comment]
用 `transition` 属性可以自定义动画。
