### ISSUE TITLE
[Bug Report] el-tag名称过长时，不能完全显示

### ISSUE THREAD

**Issue by AnyGong** [ElemeFE/element#4352]
### Element UI version
1.2.8

### OS/Browsers version
mac chrome57.0

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/Lps85oqw/](http://jsfiddle.net/Lps85oqw/)

### Steps to reproduce
可以直接查看那个第一行的名称

### What is Expected?
可以正常显示

### What is actually happening?
不能正常显示，被截取了。

**Comment by baiyaaaaa** [comment]
你的容器宽度不够，自然就是被截断了，el-table单元格不支持按内容撑开宽度。不是一个bug，先关掉了
