### ISSUE TITLE
[Bug Report] form表单验证必须是number值，非必填blur时候验证不通过

### ISSUE THREAD

**Issue by webJing** [ElemeFE/element#4353]
### Element UI version
1.2.9

### OS/Browsers version
mac

### Vue version
2.2.6

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
type:'number', trigger:'blur',但不是必填项，如果此时先focus再blur，此时input为空，不应该报错，现在会报必须是数字的错误。
空字符串转化为Number不是0吗？为什么验证没有通过

### What is Expected?
验证type是number 的时候，可以为空，验证能通过

### What is actually happening?
验证type是number 的时候，失焦为空的时候，验证失败

**Comment by Leopoldthecoder** [comment]
试了一下：https://jsfiddle.net/leopoldthecuber/3axuwsej/
从这里可以看出，如果绑定值是空字符串，即使有 `.number` 修饰符，它的类型仍然是 string。我又试了一下，虽然不知道为什么，但是如果把绑定值初始化为 null 的话就能通过验证了。

**Comment by webJing** [comment]
@Leopoldthecoder  [https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)  不是设置默认的问题，而是当input有输入再删除，此时input又为空了，还是会报错

**Comment by Leopoldthecoder** [comment]
那就自己 watch 一下吧：https://jsfiddle.net/leopoldthecuber/sksqgcw7/

**Comment by lanpangzhi** [comment]
如果是集合遍历出来的的input 怎么办， 每个都watch吗

**Comment by lanpangzhi** [comment]
transform: Number    参考  https://github.com/yiminghe/async-validator/blob/master/__tests__/number.spec.js
