### ISSUE TITLE
[Feature Request] 文档刊印错误

### ISSUE THREAD

**Issue by fantian007** [ElemeFE/element#4357]
### Existing Component
是

### Component Name
ColorPicker颜色选择器

### Description
ColorPicker颜色选择器组件 ，文档的 Attributes 的 color-format 可选类型是 rgba ，不是 rgb。

**Comment by Leopoldthecoder** [comment]
没有错，就是 rgb，只是如果这时候 show-alpha 为 true，会自动转换为 rgba。
