### ISSUE TITLE
[Bug Report] Datepicker don't take the format for the defualt model

### ISSUE THREAD

**Issue by cpantu** [ElemeFE/element#4358]
### Element UI version
1.2.9

### OS/Browsers version
Ubuntu 16.10 / Chrome 56.0.2924.87 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/Lb82s7de/](https://jsfiddle.net/Lb82s7de/)

### Steps to reproduce
Create an datepicker with a format for example "dd/MM/yyyy"
Set value for the date picker with the format selected for example "10/12/2017"

### What is Expected?
The date picker must show "10/12/2017"

### What is actually happening?
The date picker showns "12/10/2017"

**Comment by Leopoldthecoder** [comment]
Whatever the format is, the value of DatePicker is always a date object, so you should set it to `new Date(2017, 11, 10)`. The format is only for display and the `change` event.
