### ISSUE TITLE
[Bug Report] clickoutside.js?9968:39 Uncaught TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by litszh** [ElemeFE/element#4361]
### Element UI version
1.2.9

### OS/Browsers version
Windows / Chrome Version 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/element/blob/master/src/utils/clickoutside.js](https://github.com/ElemeFE/element/blob/master/src/utils/clickoutside.js)

### Steps to reproduce
If user called stopPropagation on mousedown somehow. There will be an exception in the documentHandler function 
/src/utils/clickoutside.js

### What is Expected?
Should check if the startClick is assigned before using it.

### What is actually happening?
exception

**Comment by Leopoldthecoder** [comment]
Please provide an online demo.

**Comment by sunshineJi** [comment]
+1

**Comment by Leopoldthecoder** [comment]
Fixed in #5384
