### ISSUE TITLE
[Bug Report] 有关Table-column属性fixed固定和type=expand的展现问题。

### ISSUE THREAD

**Issue by scscms** [ElemeFE/element#4367]
### Element UI version
1.2.9

### OS/Browsers version
Firefox

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/rqfe217g/1/](https://jsfiddle.net/rqfe217g/1/)

### Steps to reproduce
当Table中含有fixed属性固定左或右，同时添加有type=expand展开行。我们发现展开行后，行被分割成三部分。当行内内容比较多且出现滚动条时，滚动会发现左中右内容无法对齐。原因是左边fixed表格也复制了一份展开行内容；右边fixed同样也复制了一份展开行内容。

### What is Expected?
建议左右fixed单元格不需要复制展开行内容，直接把单元格背景设置成透明即可（如能同时删除阴影线更佳）。只有中间单元格含有展开行内容。

### What is actually happening?
由fixed引起展开行分割成三个相同的DOM节点，当滚动内容时。展开行内容无法对齐显得怪异。

**Comment by ChangeZhang** [comment]
https://jsfiddle.net/v5n6mywp/ @Leopoldthecoder 大神什么时候能修复啊

**Comment by ChangeZhang** [comment]
@Leopoldthecoder 大神什么时候能修复啊

**Comment by leeqqiang** [comment]
<el-table-column width="48">
</el-table-column>

我在子行里加了个空列就对齐了

**Comment by leeqqiang** [comment]
`<el-table-column width="48">
  </el-table-column>`

**Comment by huashengwang1989** [comment]
试着找个临时的办法，供参考：
https://jsfiddle.net/d004x3pf/
用了vue-resize-directive, 因为要检测窗口resize时表格宽度的变化...

分割成三块问题：CSS里调整z-index解决

扩展航打开后行高问题： 似乎把`type="expand"`的column也变成`fixed`后就没问题了？
（当然箭头会占在最左边）

另外还有个问题是，扩展行里的内容必须得跟着表格横向滚动才能看完。这个我只能通过在expanded row里面添一个wrapper div，然后检测窗口resize和横向滚动的坐标来不停地调整wrapper div的width和margin-left... 不知道有没有更好的解决方法。

期待修复。

**Comment by liril-net** [comment]
你好，因为`expand` 和  `fixed` 都是为了解决信息过多无法完全展示的问题，所以请不要混用，建议你找你们的产品聊一下这个问题。

**Comment by Lynn-cc** [comment]
我用下面这个css处理ok了
```
<style lang="scss" scoped>
// expand里的table有bug
// 会随父table多一个fixed table
// 处理方式：干掉fix-table那个cell里的table（占位不能改，还要加白色底色）
// 并把expand设置右边距，避开那个fixed right列
.expand-div { // 包裹expand内容的div
  margin-right: 120px; // 父级右fix列的宽度
}
/deep/.el-table__fixed-right {
  background-color: #fff;  // 父级fix列的颜色
  .el-table__expanded-cell {
    visibility: hidden;
  }
}
</style>
```

**Comment by dangnaiyin** [comment]
我解决了 [https://blog.csdn.net/weixin_44157964/article/details/120205080](url)

**Comment by Lan-megumi** [comment]
2021年的前来考古
如果有expand里面放了一个组件的兄弟，然后这个组件里面又要做在mounted下面做一些操作（比如调接口）
如果用上面的方式两个实例都会执行一次mounted，
不想有这种体验呢
可以这样写
`
created() {
    const parent = this.$parent
    console.log('' +Math.random() + 'exist !')
    if (parent._props && parent._props.fixed !== undefined) {
      console.log('' + Math.random() + 'destory !')
      this.$destroy()
    }
  },
`

**Comment by sunmaobin** [comment]
**思路：** 只需要让展开列的内容浮动在固定列之上即可。

```html
<el-table-column type="expand">
    <template v-slot="{row}">
        <div style="position: relative;z-index: 4;margin: -6px 0;">
            <!-- 展开内容或组件 -->
        </div>
    </template>
</el-table-column>
````
