### ISSUE TITLE
[Bug Report] Datepicker doesn't open on "Tab" focus

### ISSUE THREAD

**Issue by davidboom95** [ElemeFE/element#4370]
### Element UI version
1.2.9

### OS/Browsers version
Mac OS Sierra Safari  10.0.3

### Vue version
2.2.6

### What is Expected?
I expect Datepicker opens when I do a focus triggered by a TAB

### What is actually happening?
Datepicker doesnt open

**Comment by Leopoldthecoder** [comment]
Bug reports with no reproduction link will be closed directly.
