### ISSUE TITLE
[Bug Report] Carousel走马灯起始页数initial-index属性失效

### ISSUE THREAD

**Issue by CHU295** [ElemeFE/element#4373]
### Element UI version
1.2.9

### OS/Browsers version
win10

### Vue version
2.2.6

### Reproduction Link
http://jsfiddle.net/7wrzc0y9/

### Steps to reproduce
你可以试试你们自己的在线案例，initial-index属性失效

### What is Expected?
修正

### What is actually happening?
http://jsfiddle.net/7wrzc0y9/

**Comment by CHU295** [comment]
新连接更新了

**Comment by CHU295** [comment]
@element-bot 已更新

**Comment by Reson-a** [comment]
这个我之前提过了 #3886
可以参考我的应急方案，动了一点源码

**Comment by evolutionjay** [comment]
1.3.3 同样bug

**Comment by Leopoldthecoder** [comment]
Fixed in #5334. Will release in 1.3.7
