### ISSUE TITLE
綁定數據為number的時候，驗證不準確

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4374]
### Element UI version
1.2.9

### OS/Browsers version
WINDOWS CHROME

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/anatrzo6/](https://jsfiddle.net/anatrzo6/)

### Steps to reproduce
1。點擊輸入框
2。點擊輸入框外面的區域
3。出現驗證錯誤
4。實際上有輸入內容，不該出現驗證失敗的提示

### What is Expected?
應該驗證通過。
現在的行為，只要name是number類型，就會報錯，是string類型，就不會

### What is actually happening?
驗證不通過

**Comment by zzzgit** [comment]
為什麼總是搞個機器人來灌水

**Comment by Leopoldthecoder** [comment]
文档上有专门的数字类型验证的例子，麻烦看一下。
