### ISSUE TITLE
[Feature Request] Notification支持换行吗

### ISSUE THREAD

**Issue by imqishi** [ElemeFE/element#4377]
### Existing Component
是

### Component Name
Notification

### Description
希望能提供类似于把内容以html方式渲染的效果，或者提供一下换行的方法，谢谢

**Comment by Leopoldthecoder** [comment]
参考文档上的第一个例子，你可以自己写 VNode。

**Comment by angeltxwh** [comment]
用Vnode的方法来做的时候，怎样再嵌入el-button并绑定一个click方法？

**Comment by felix9ia** [comment]
overflow-wrap: break-word;
