### ISSUE TITLE
[Bug Report] Tooltip用在输入框上箭头位置不正确

### ISSUE THREAD

**Issue by VincentPat** [ElemeFE/element#4378]
### Element UI version
1.2.9

### OS/Browsers version
Mac OS X EI Captain / Chrome 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/Vincent_Pat/o1rqhb1z/](https://jsfiddle.net/Vincent_Pat/o1rqhb1z/)

### Steps to reproduce
打开网址预览即可：https://jsfiddle.net/Vincent_Pat/o1rqhb1z/

### What is Expected?
箭头出现在左上方

### What is actually happening?
箭头出现在右上方，并超出范围

**Comment by Leopoldthecoder** [comment]
placement 指的是整个 tooltip 的定位，而不是箭头的定位。箭头总是会出现在 reference 元素的中间，由于 tooltip 的宽度达不到 input 宽度的一半，所以箭头就贴到 tooltip 的右边了。

**Comment by yoker** [comment]
@Leopoldthecoder 知道导致的原因，不修改，直接关闭issue。 这样做，不太好吧。

**Comment by zg19990220** [comment]
依托答辩 现在依旧有这个问题
