### ISSUE TITLE
[Bug Report] trigger造成驗證行為不正確

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4380]
### Element UI version
1.2.9

### OS/Browsers version
windows,linux,unix,IOS,android,nokia

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/0onL7m5p/1/](https://jsfiddle.net/0onL7m5p/1/)

### Steps to reproduce
1.鼠標點擊輸入框
2.鼠標點擊輸入框以外的地方
3.驗證不通過，出現紅色提示
4.注釋掉當前規則，并把下面的規則放開
5.重複上面的鼠標操作
6.驗證能通過

### What is Expected?
兩種情況，都能驗證通過

### What is actually happening?
trigger:"blur"，對驗證的行為有影響，如果加了，行為異常，如果不加，則能驗證通過

**Comment by Leopoldthecoder** [comment]
看了一下，没有 `trigger: 'blur'` 的时候不报错其实是不对的，是哪里的问题还没确定。你这里还是需要加 `type: 'number'`。
