### ISSUE TITLE
[Bug Report] upload组件问题

### ISSUE THREAD

**Issue by lzmhlzsd** [ElemeFE/element#4383]
### Element UI version
1.2.9

### OS/Browsers version
mac

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
https://jsfiddle.net/api/post/library/pure/

### What is Expected?
能够多次上传同一个文件

### What is actually happening?
不能多次上传同一个文件

**Comment by jikkai** [comment]
请问为什么要多次上传同一个文件？

**Comment by lzmhlzsd** [comment]
我在通过excel模版导入数据， 文件是上传成功了，但是我的后台需要验证模版数据是正确，如果不正确，就需要修改模版数据后再次上传这个文件。

**Comment by baiyaaaaa** [comment]
不会考虑这个需求，可以寻找另外的组件支持或者自行完成

**Comment by lzmhlzsd** [comment]
我发现element-ui 1.x版本的是可以重复上传的。2.x版本不可以了。

**Comment by Longui** [comment]
是否做一个可重复上传的配置参数？
实际场景中，我上传一个doc或xlsx文档，当我修改文档，重新上传，只能重命名文件或是刷新页面，才能再次上传该文件

**Comment by jinshu** [comment]
element-ui 2.x版本还是有bug的，当list-type为picture时我上传了3个图片，这时候再重复上传我之前上传3个图片的任意2个或1个图片，这时候还是能上传上去的

**Comment by Zeus-Iqd** [comment]
@lzmhlzsd  大佬我和你是相同的业务场景，请问下你是怎么解决这个问题的。submit 只能执行一次
