### ISSUE TITLE
[Feature Request] 在组件中文本赋值的时候不支持三元表达式么？

### ISSUE THREAD

**Issue by shen0834** [ElemeFE/element#4386]
### Existing Component
是

### Component Name
表格等涉及文本相关

### Description
类似表格属性 prop="date?'2017/01/01':'2016-01-01'"，因为vue是支持三元表达式的

**Comment by Leopoldthecoder** [comment]
这是 Bug Report，不是 Feature Request。请不要因为不想写 demo 就选择 Feature Request。

**Comment by jikkai** [comment]
`:prop`
