### ISSUE TITLE
[Feature Request] 表格的show-overflow-tooltip建议支持light主题，现在默认是dark主题，不支持配置

### ISSUE THREAD

**Issue by Undefined123456789** [ElemeFE/element#4389]
### Existing Component
是

### Component Name
Table

### Description
表格的show-overflow-tooltip建议支持light主题，现在默认是dark主题，不支持配置

**Comment by Undefined123456789** [comment]
http://element.eleme.io/#/zh-CN/component/table

**Comment by pengchongfu** [comment]
@Undefined123456789 你说的是这个么 https://jsfiddle.net/se9tLu2z/
Table 组件的 tooltip-effect 属性

**Comment by Leopoldthecoder** [comment]
@Undefined123456789 请参照楼上。
