### ISSUE TITLE
[Bug Report] 用函数去初始化el-table导致的问题

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#4395]
### Element UI version
1.2.9

### OS/Browsers version
mac

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/zpczjl/s2qhjf3j/](https://jsfiddle.net/zpczjl/s2qhjf3j/)

### Steps to reproduce
在重连链接里点击el-table的第一列的任意一个单选框

### What is Expected?
单选框被选中，选中的列的内容出现在页面上。

### What is actually happening?
单选框无法选中

**Comment by njleonzhang** [comment]
在这种使用场景下，对单选框的点击会导致el-table的render函数重新调用，getData被调用生成了新的data，然后又传进了el-table，el-table也就刷新了。

如果在template里不引用multipleSelection，则对单选框的点击机会不会导致getData的调用。
或者用一个变量来初始化el-table（不用函数），也可以解决。https://jsfiddle.net/zpczjl/8340vm0x/

但是问题为什么会出现呢？

**Comment by QingWei-Li** [comment]
值变了触发 dom 更新就重新渲染，Vue 的机制没毛病呀
https://jsfiddle.net/8340vm0x/3/

**Comment by njleonzhang** [comment]
你的意思是multipleSelection是Main组件的data，所以multipleSelection的变化就导致了Main的render的重新调用是吧，所以导致了getData被调用？

**Comment by QingWei-Li** [comment]
施压

**Comment by njleonzhang** [comment]
@QingWei-Li 一言点醒梦中人。。。
