### ISSUE TITLE
[Bug Report] Prev and Next method

### ISSUE THREAD

**Issue by sufita** [ElemeFE/element#4399]
### Element UI version
1.2.9

### OS/Browsers version
Versi 57.0.2987.133 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/element/issues/4398](https://github.com/ElemeFE/element/issues/4398)

### Steps to reproduce

How to use prev and next of layout associated with database?
` <el-pagination
   @current-change="handleCurrentChange"
    :current-page="current_page"
    :page-size="per_page"
    layout="prev, pager, next"
    :total="total">
    </el-pagination>`

`data() {
    return: {
    per_page: null,
    current_page: null,
    total: null,
    next_page_url: null,
        }
}`

### What is Expected?
The quick answer.

### What is actually happening?
Lack of back end documentation.

**Comment by baiyaaaaa** [comment]
I think what u want is `:layout`="computedLayoutString"
