### ISSUE TITLE
[Feature Request] An event for files added

### ISSUE THREAD

**Issue by LeonLiber** [ElemeFE/element#4401]
### Existing Component
Yes

### Component Name
upload

### Description
Sometimes you need to submit a whole form with files and not upload files as they are added.
For that one would use autoUpload=false.

To be able to clear the file list when other files are selected or react to input actions in general - it is useful to have a filesChanged or filesAdded events to the upload.

For example: Since you can't add files to a file input when it is autoUpload=false - I would clear the uploadFiles list everytime files are replaced:

```html
<el-upload :auto-upload="false" :on-files-changed="clearUploadList" ref="uploader"></el-upload>
```

```javascript
function clearUploadList() {
this.$refs.uploader.uploadFiles = [];
}
```

**Comment by baiyaaaaa** [comment]
will be support in 1.3

**Comment by LeonLiber** [comment]
Thank you @baiyaaaaa  :) 
Any workaround in the meantime, clearing the list when new files are selected?
