### ISSUE TITLE
[Feature Request] accordion feature for table expand

### ISSUE THREAD

**Issue by jpkontreras** [ElemeFE/element#4407]
### Existing Component
Yes

### Component Name
table

### Description
should be cool if u guys came up with an accordion feature for table expand. I think that there should be an option for that

**Comment by vipplus** [comment]
table怎么设置默认勾选几行？

**Comment by vipplus** [comment]
table组件默认选中任意行，怎么设置

**Comment by jpkontreras** [comment]
I dont know chinese but seems like you want me to do a PR of the issue. Is this correct?

**Comment by vipplus** [comment]
The table component is selected by default

**Comment by Leopoldthecoder** [comment]
@vipplus Please don't ask questions in irrelavent issues.

**Comment by pilsoftTeam** [comment]
@vipplus you did not quite got my feature request. I just wanna a accordeon feature on expand so when you click it the others collapse

**Comment by baiyaaaaa** [comment]
I think it's not a common requirement

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
