### ISSUE TITLE
[Bug Report] Tree element can't register node which id is 0

### ISSUE THREAD

**Issue by RexSkz** [ElemeFE/element#4409]
### Element UI version
1.2.9

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/8ytu6qor/2/](https://jsfiddle.net/8ytu6qor/2/)

### Steps to reproduce
Simply set a tree node id to number 0 and mark this node as checked.

### What is Expected?
After run `getCheckedKeys` method, the result will contain this node.

### What is actually happening?
The node won't show in the result.

I think [this line](https://github.com/ElemeFE/element/blob/dev/packages/tree/src/model/tree-store.js#L135) causes the bug, the condition returns false when nodeKey is 0.

**Comment by Leopoldthecoder** [comment]
Fixed in #4415
