### ISSUE TITLE
[Bug Report] select error warning is not clear

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4411]
### Element UI version
1.2.9

### OS/Browsers version
所有

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/b6mg7kL6/](https://jsfiddle.net/b6mg7kL6/)

### Steps to reproduce
1.open the console
2.run the code again
3.there will be some errors "Cannot read property 'indexOf' of undefined"
4.remove the multiple attribute from the select tag
5.run again 
6.errors will not occur

### What is Expected?
錯誤的原因是沒有寫v-model在select中，但是提示不明確
https://github.com/ElemeFE/element/blob/b9e3e7faefd296a2be92b73d512cdba1fe71da33/packages/select/src/option.vue#L70
這行代碼直接去取值，沒有做判斷和校驗

### What is actually happening?
nothing

**Comment by Leopoldthecoder** [comment]
Set the `value` prop required in #4423 .
