### ISSUE TITLE
[Bug Report] input under the select does not show the selected items

### ISSUE THREAD

**Issue by bboywulong** [ElemeFE/element#4413]
### Element UI version
1.2.9

### OS/Browsers version
mac os

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/118/](https://jsfiddle.net/pj71jkyw/118/)

### Steps to reproduce
在input中使用select组件,选中项不显示

### What is Expected?
能够正常显示

### What is actually happening?
未正常显示

**Comment by pengchongfu** [comment]
@bboywulong adjust `input` width
```
.el-select .el-input {
  width: 110px;
}
```
https://jsfiddle.net/pj71jkyw/119/
