### ISSUE TITLE
[Bug Report] NavMenu 导航菜单 template slot="title" 结合 Tooltip 文字提示 出现标题字丢失

### ISSUE THREAD

**Issue by yooellie** [ElemeFE/element#4416]
### Element UI version
1.2.9

### OS/Browsers version
 Google Chrome 57.0.2987.133

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/yo0xj2j8/](https://jsfiddle.net/yo0xj2j8/)

### Steps to reproduce
<template slot="title"><el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start"><i class="el-icon-message"></i>导航一</el-tooltip></template>

### What is Expected?
<template slot="title">加入tooltip “导航一”标题字样不消失，鼠标覆盖显示文字提示

### What is actually happening?
<template slot="title">加入tooltip “导航一”标题字样消失，鼠标覆盖icon才显示提示，覆盖el-submenu__title未提示

**Comment by Leopoldthecoder** [comment]
In your demo only the `<i>` tag is parsed as the default slot, so the text behind it is ignored. A working demo: https://jsfiddle.net/yo0xj2j8/1/ .
