### ISSUE TITLE
[Bug Report] router in Menu not work

### ISSUE THREAD

**Issue by sanmen359** [ElemeFE/element#4419]
### Element UI version
1.2.9

### OS/Browsers version
Chrome 50

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/123/](https://jsfiddle.net/pj71jkyw/123/)

### Steps to reproduce
open "https://jsfiddle.net/pj71jkyw/123/" click the"FOO"or "BAR",the  router-view don't refresh

### What is Expected?
open "https://jsfiddle.net/pj71jkyw/123/" click the"FOO"or "BAR",the router-view should refresh and show "foo" or "bar"

### What is actually happening?
open "https://jsfiddle.net/pj71jkyw/123/" click the"FOO"or "BAR",the  router-view don't refresh and no error

**Comment by pengchongfu** [comment]
if you have set prop `index` in `el-menu-item`, you don't need to set `route`
https://jsfiddle.net/pj71jkyw/124/

you can also set prop `route` a object with key `path`, because Element whould handle prop `route` first
https://jsfiddle.net/pj71jkyw/125/
