### ISSUE TITLE
[Bug Report] table module header style is the default bold

### ISSUE THREAD

**Issue by mohong** [ElemeFE/element#4422]
### Element UI version
1.2.4

### OS/Browsers version
windows10 / chrome 版本 57.0.2987.133 (64-bit)

### Vue version
2.2.2

### Reproduction Link
http://ob9qd20l4.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170424170029.jpg

### Steps to reproduce
1. 使用了table表格
2. 表头字体没有像文档上面的一样加粗

### What is Expected?
table表头像文档上面的一样默认加粗

### What is actually happening?
table表头字体没有加粗，跟表内其他行的字体样式一致

**Comment by Leopoldthecoder** [comment]
There is no Table in your reproduction link. Please update it.

**Comment by mohong** [comment]
项目没上线，所以没法提供外链，表格表头现在是图上这个样子了，需要加粗表头字体。
![截图](http://ob9qd20l4.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170424170029.jpg)

**Comment by Leopoldthecoder** [comment]
Element itself does not have `font-weight` for table headers. The bold letters in our documentation is a result of browser's default style. So you can just add your own CSS.

**Comment by mohong** [comment]
OK, thank you !
