### ISSUE TITLE
[Bug Report] table components have a column need to use switch components, change the switch when each row changes

### ISSUE THREAD

**Issue by mohong** [ElemeFE/element#4426]
### Element UI version
1.2.4

### OS/Browsers version
windows10 / chrome 版本 57.0.2987.133 (64-bit)

### Vue version
2.2.2

### Reproduction Link
http://ob9qd20l4.bkt.clouddn.com/transition2.gif

### Steps to reproduce
使用了table组件，其中一列用到了switch组件，代码：
![jietu](http://ob9qd20l4.bkt.clouddn.com/232323.jpg)，

改变了其中的一个switch，其他的状态都改变，结果：
![jietu](http://ob9qd20l4.bkt.clouddn.com/transition2.gif)

### What is Expected?
改变一个switch，只对当前行生效。

### What is actually happening?
改变了一个switch, 对所有行生效

**Comment by Leopoldthecoder** [comment]
Bug reports without a reproduction link will be closed directly.

**Comment by mohong** [comment]
OK, thank you !
