### ISSUE TITLE
[Bug Report] pagination total re assignment, resulting in abnormal pageSize parameters

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4427]
### Element UI version
1.2.9

### OS/Browsers version
所以

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/jyv8k1pm/1/](https://jsfiddle.net/jyv8k1pm/1/)

### Steps to reproduce
1.打开console
2.点选下拉框，选择 200条/页
3.下拉框显示的依然是100条/页
4.控制台应该打印200，实际上打印的是100

### What is Expected?
正确处理pageSize

### What is actually happening?
引起这个bug的原因，是因为handleSizeChange函数中，修改了total的值。
框架没有正确处理好其中的逻辑，导致行为异常

**Comment by Leopoldthecoder** [comment]
It has nothing to do with your updating `this.total`. 

`this.size` will stay the same because there is no two-way binding in Vue 2.0, and you have to manually update `this.size` in the handleSizeChange callback, say `this.size = val`
