### ISSUE TITLE
在日期选择控件中，如何监听其选择日期的点击事件呢？

### ISSUE THREAD

**Issue by chachaxw** [ElemeFE/element#443]
在日期选择控件中，我想通过监听点击事件，来执行一些操作，但是还不知道要怎么样去监听。

**Comment by QingWei-Li** [comment]
`@click.native="xxx"`？

**Comment by chachaxw** [comment]
@QingWei-Li [http://7xqacx.com1.z0.glb.clouddn.com/Screen%20Shot%202016-10-17%20at%2014.40.44.png](url)
比如上图所示，我想要在点击“今天”这个按钮的时候，执行一些操作，该怎么做呢？比如对日期进行处理。

**Comment by QingWei-Li** [comment]
如果是对数据进行操作，可以通过 watch 或 computed 的方式。

不过会考虑增加选中和取消的事件

**Comment by chachaxw** [comment]
我这里有好几个日期选择控件，我想通过其中一个日期控件，点击选择日期后，改变其他日期控件中的值，并反映到日期控件中，怎样用watch来实现呢？

**Comment by QingWei-Li** [comment]
当 date1 更新时会出发 watch，这时候你就能操作 date2 了
```javascript
{
  data() {
    retrun { date1: '', date2: '' }
  },
  watch: {
    date1(val) {
        this.date2 = 'xxx'
    }
  }
}
```

**Comment by QingWei-Li** [comment]
建议还是通过 watch 数据方式
