### ISSUE TITLE
[Feature Request] hope Popover and tooltip open automatic creation and destruction method.

### ISSUE THREAD

**Issue by qianqWang** [ElemeFE/element#4431]
### Existing Component
是

### Component Name
el-popover和el-tooltip

### Description
实际项目中，类似日历的表格会要求实现每个小方框都能够点击展示popover。这在一次性创建大量小方块时因为自动创建了popover，所以导致卡顿。希望提供方法可以实现小方框创建完成后点击小方块时再创建popover。

**Comment by Leopoldthecoder** [comment]
This should be handled in users' end. You can check out #3836 for inspirations.
