### ISSUE TITLE
[Bug Report] tabs switching route is destroyed when [Vue warn]: Error updated hook: (found in <TabNav>) vue.esm.js 65d7:1447 Cannot read property'offsetWidth'of undefined ()... )

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#4434]
### Element UI version
0.1.0

### OS/Browsers version
chrome 53

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/无路由不好提供demo](https://jsfiddle.net/无路由不好提供demo)

### Steps to reproduce
子页面使用el-tabs后，切换到其他子页面，在执行destory时出现如题JS error。

vue.esm.js?65d7:558 **[Vue warn]: Error in updated hook:**
(found in )warn @ vue.esm.js?65d7:558handleError @ vue.esm.js?65d7:1443callHook @ vue.esm.js?65d7:2275flushSchedulerQueue @ vue.esm.js?65d7:2357(anonymous function) @ vue.esm.js?65d7:505nextTickHandler @ vue.esm.js?65d7:454
vue.esm.js?65d7:1447 **TypeError: Cannot read property 'offsetWidth' of undefined(…)** handleError @ vue.esm.js?65d7:1447callHook @ vue.esm.js?65d7:2275flushSchedulerQueue @ vue.esm.js?65d7:2357(anonymous function) @ vue.esm.js?65d7:505nextTickHandler @ vue.esm.js?65d7:454
common.js?bc4d:1403 isDestory-----true

### What is Expected?
没有JS Error

### What is actually happening?
出现描述中的error

**Comment by Leopoldthecoder** [comment]
You **can** use vue-router in JSFiddle. Please update your repro link.

**Comment by lry210** [comment]
May be I wrong，I use keep-alive and  I destroy when activated
http://jsfiddle.net/xgrjzsup/1846/

**Comment by Leopoldthecoder** [comment]
Is there any reason you destroyed the instance in its `activated` hook?

**Comment by lry210** [comment]
@Leopoldthecoder no, thank you

**Comment by poorrigel** [comment]
I met this problem recently, I guess you should do a similar operation with me.Used in the el-tab this component v-if, in fact, should use v-show。
Or you made other related dom operations。
