### ISSUE TITLE
[Bug Report] dialog component  set 'custom-class' prop , Not effective ！

### ISSUE THREAD

**Issue by zhump** [ElemeFE/element#4435]
### Element UI version
1.2.9

### OS/Browsers version
win7/google56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
无

### What is Expected?
在 <style scoped> 的情况下， custom-class 还是能生效

### What is actually happening?
不生效

**Comment by zhump** [comment]
那样中国人看的就费劲了 -。-

**Comment by Leopoldthecoder** [comment]
#377
