### ISSUE TITLE
[Bug Report] The :file-list of the 'Upload' Component isn't Reactive

### ISSUE THREAD

**Issue by kevinheyo** [ElemeFE/element#4440]
### Element UI version
1.2.9

### OS/Browsers version
Chrome 57 / Win 7

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/6kescLuc/1/](https://jsfiddle.net/6kescLuc/1/)

### Steps to reproduce
1. 在 `:file-list` 中指定一個變數  
Assign a variable to `:file-list` attribute

2. 點 Click to upload，上傳任意檔案或圖片  
Click "Click to upload", and upload any files or photos

3. `handleChange(file, fileList)` 可獲得上傳檔案後的最新的 fileList  
We can see the up-to-date file-list in the `handleChange(file, fileList)`

4. 但是，呼叫 `this.fileList` 時，這個清單仍是初始的狀態  
But we still see the file-list same with initial state by calling this.fileList

### What is Expected?
增加一個檔案之後，使用 this.fileList 應該也要能看到最新的檔案清單
We should see the up-to-date file-list by calling this.fileList after uploading a file

### What is actually happening?
this.fileList isn't reactive

**Comment by baiyaaaaa** [comment]
this's not a bug for the upload component.
if you want the fileList become reactive, you can update this.fileList in the upload hook function
