### ISSUE TITLE
[Feature Request] Responsive offset

### ISSUE THREAD

**Issue by PhillippOhlandt** [ElemeFE/element#4442]
### Existing Component
Yes

### Component Name
el-col

### Description
Hey,

`span` and `offset` are working great together, but it seems like there is no option to set a different offset for each breakpoint (`xs`, `sm`, `md`, `lg`).

**Comment by baiyaaaaa** [comment]
I think what u want is `:xs={ span: xx, offset: xx }`.
If not , can u provide a demo to explain more clearly?

**Comment by PhillippOhlandt** [comment]
Will test that out. If that works, I am happy. Haven't seen it mentioned in the docs.

**Comment by QingWei-Li** [comment]
At the end of the page.
![image](https://cloud.githubusercontent.com/assets/7565692/25413237/654dd676-2a5b-11e7-9d5b-f35b6def19e7.png)
