### ISSUE TITLE
[Feature Request] el-upload how to achieve asynchronous file upload

### ISSUE THREAD

**Issue by lksong110** [ElemeFE/element#4443]
### Existing Component
是

### Component Name
el-upload

### Description
el-upload如何实现文件异步上传
How to implement asynchronous file upload

**Comment by lksong110** [comment]
How to implement asynchronous file upload

**Comment by type-of-null** [comment]
I have made an attempt. 

The issue with my implementation is that the **"on-success" hook is called on page load** which is too early. Can anyone help?

`<el-upload
                  ref="upload"
                  class="upload-demo"
                  drag
                  :action="myUrl"
                  :on-preview="handlePreview"
                  :on-remove="handleRemove"
                  :on-success="nextAction()"
                  :auto-upload="false"
                  :with-credentials="true"
               >
                 <i class="el-icon-upload"></i>
                 <div class="el-upload__text">Drop site list here or <em>click to upload</em></div>
                 <div class="el-upload__tip" slot="tip">Excel file with Frame IDs in Col A</div>
               </el-upload>`

And the js method:

`uploadFile: function(){
               this.$refs.upload.submit();
         },`

**Comment by baiyaaaaa** [comment]
无法理解你的问题，上传不就是异步的？
