### ISSUE TITLE
[Bug Report] Dialog within the Table set ref, access to less than table of the DOM

### ISSUE THREAD

**Issue by wyu-prc** [ElemeFE/element#4445]
### Element UI version
1.2.9

### OS/Browsers version
MacOS 10.12.4

### Vue version
2.2.6

### Reproduction Link
[http://codepen.io/anon/pen/QvGbJa?editors=1111](http://codepen.io/anon/pen/QvGbJa?editors=1111)

### Steps to reproduce
<head>
<meta charset="UTF-8">

<link rel="stylesheet" href="https://unpkg.com/element-ui@next/lib/theme-default/index.css">
</head>
<body>
<div id="app">
  <el-button @click.native="openDialog">按钮</el-button>
  <el-dialog v-model="visible" title="Hello world">
    <el-table ref="table1" :data="tableData" stripe border>
      <el-table-column prop="name" label="账 号" width="180"></el-table-column>
    </el-table>
    <p>欢迎使用 Element</p>
  </el-dialog>
</div>
</body>

<script src="https://unpkg.com/vue/dist/vue.js"></script>

<script src="https://unpkg.com/element-ui/lib/index.js"></script>

<script>
  new Vue({
    el: '#app',
    data: function() {
      return {
        visible: false,
        tableData: [{name: 'Test'}]
      }
    },
    methods: {
      openDialog: function() {
        this.visible = true
        console.log(this.$refs['table1'])
      }
    }
  })
</script>

### What is Expected?
this.$refs['table1']
能够获取相应DOM对象

### What is actually happening?
得到的值为undefined

**Comment by Leopoldthecoder** [comment]
The content of Dialog is not rendered before it pops up. So you may have to get the DOM in the next tick: http://jsfiddle.net/7wrzc0y9/1/

**Comment by wyu-prc** [comment]
Thanks a lot!
