### ISSUE TITLE
[Bug Report] Upload 'on-success' firing early

### ISSUE THREAD

**Issue by type-of-null** [ElemeFE/element#4446]
### Element UI version
1.2.9

### OS/Browsers version
Windows 10 / Chrome 57.0 

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/133/](https://jsfiddle.net/pj71jkyw/133/)

### Steps to reproduce
Issue occurs on page load

### What is Expected?
The on-success hook should only be called after the successful upload

### What is actually happening?
The on-success hook is being called when the page loads

**Comment by Leopoldthecoder** [comment]
Don't add the parentheses after the callback name. If you have some other arguments you need to pass to the callback, do it like this: https://jsfiddle.net/pj71jkyw/134/
