### ISSUE TITLE
[Bug Report] el-table's sortable why not synchronization

### ISSUE THREAD

**Issue by scscms** [ElemeFE/element#4451]
### Element UI version
1.2.9

### OS/Browsers version
win7/firefox

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/mq5vhpmy/](https://jsfiddle.net/mq5vhpmy/)

### Steps to reproduce
Switch the sortable value

### What is Expected?
sortable can realize the sort synchronization

### What is actually happening?
can't sync sorting

**Comment by syn-zeta** [comment]
A workaround until someone more knowledgeable comments: https://jsfiddle.net/mq5vhpmy/2/

**Comment by Leopoldthecoder** [comment]
I'm working on it.

**Comment by scscms** [comment]
@syn-zeta 这就很尴尬了，因为是不定行，每行排序模式不一样。
