### ISSUE TITLE
[Feature Request] DatePicker components, how to set the default initialization value

### ISSUE THREAD

**Issue by 992forever** [ElemeFE/element#4452]
### Existing Component
是

### Component Name
DatePicker

### Description
功能中用到了DatePicker，需要把一个日期初始化回填到DatePicker的输入框中。虽然给绑定的变量值设置了初始值，但在输入框中并没有显示。

**Comment by 992forever** [comment]
Function used in the DatePicker, you need to initialize a date backfill to the DatePicker input box. The initial value is set for the bound variable value, but not in the input box.

**Comment by Leopoldthecoder** [comment]
This, in no sense, is a feature request.
