### ISSUE TITLE
[Feature Request] can increase the suspension and re upload function

### ISSUE THREAD

**Issue by liuzhibin123** [ElemeFE/element#4453]
### Existing Component
是

### Component Name
upload

### Description
我要做一个像网盘一样的项目 ，里面需要暂停与开始上传和失败后重新上传功能。有其他思路或插件推荐也行

**Comment by Leopoldthecoder** [comment]
For a cloud storage system, where uploading files can be very complicated, you may need a much powerful uploader than Upload of Element.
