### ISSUE TITLE
MessageBox prompt回调参数

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#446]
### ElementUI version
1.0.0-rc.7

### Vue version
2.0.2

### Reproduction Link
https://jsfiddle.net/erguotou525/xtrk39s0/1/

### Steps to reproduce
点击打开模态框，输入内容，可以看到提示的是个对象而不是`value`值，与文档不符。http://element.eleme.io/#/component/message-box

**Comment by erguotou520** [comment]
另外，关于弹框的弹出效果之前说要改的，不知道什么时候修改呢？ #263 
还有，`prompt`在下次打开时会携带之前的验证状态（如果错误的话），有没有方法可以去掉？

**Comment by Leopoldthecoder** [comment]
第一个问题是文档写错了。

关于弹框的弹出效果，不出意外会在下个版本中修改。「`prompt` 在下次打开时会携带之前的验证状态」在 #452 中修复。

**Comment by erguotou520** [comment]
文档修复后可关闭

**Comment by Leopoldthecoder** [comment]
fixed in #452
