### ISSUE TITLE
[Bug Report] Cosmetic - `el-tooltip` and `show-overflow-tooltip` hover behavior in `el-table`

### ISSUE THREAD

**Issue by syn-zeta** [ElemeFE/element#4462]
### Element UI version
1.2.9

### OS/Browsers version
Mac 10.11 / Chrome 58

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/6mgvmob1/](https://jsfiddle.net/6mgvmob1/)

### Steps to reproduce
Preconditions:
- `el-table`
  - one custom column template that uses `el-tooltip`
  - one column with `show-overflow-tooltip` attribute, and long content so the tooltip would appear

Steps:
- Slide the cursor down over the column that uses `el-tooltip` such that all the tooltips appear. Notice that they all do.
- Slide the cursor down over the column that uses `show-overflow-tooltip` attribute with the same speed as before. Notice that not all the tooltips show up.

### What is Expected?
Similar behavior of `el-tooltip` and `show-overflow-tooltip` upon hover when used in a table.

### What is actually happening?
`show-overflow-tooltip` seems to have a "duration" for which the cursor should remain over the column until the tooltip appears. This delay is not the same delay as `open-delay` attribute of the `el-tooltip`, which displays as long as `mouseenter` was fired on it.

### GIF
![tooltip](https://cloud.githubusercontent.com/assets/26761352/25423758/b254ebd0-2a1a-11e7-8787-f27dca88beb7.gif)

**Comment by Leopoldthecoder** [comment]
I tried the demo and they don't feel quite different on my computer.

But there is a reason if they do behave differently, and you can see for yourself if you open the console. For the custom column, each cell creates a DOM element for the tooltip, but for the built-in `show-overflow-tooltip`, only one DOM is created no matter how many rows you have, and that DOM gets updated each time you mouse moves in another cell. This is to avoid too many DOMs when the table is large.

So, hardly qualifies as a bug.
