### ISSUE TITLE
[Bug Report] Pagination in IE10 can not change the current page using enter key

### ISSUE THREAD

**Issue by even-huang** [ElemeFE/element#4464]
### Element UI version
1.2.9

### OS/Browsers version
IE10

### Vue version
2.2.6

### Reproduction Link
[https://codepen.io/even_huang/pen/XRNPXK](https://codepen.io/even_huang/pen/XRNPXK)

### Steps to reproduce
change the current page in the input, press the enter key

### What is Expected?
current page changes

### What is actually happening?
it didn't work，and when the focus blur , it can work normally

**Comment by Leopoldthecoder** [comment]
Duplicate of #6224
