### ISSUE TITLE
[Feature Request] border-width perfect 0.5px program

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#4465]
### Existing Component
是

### Component Name
element-variables.css

### Description
  custom theme  的  element-variables.css 
把 --border-width-base: 1px;
改成  --border-width-base: 0.01em;

作用：  在 不支持 小于1px 的浏览器上， 依旧是 1px
但是在支持小于1px 的浏览器上，例如最新的  Safari。 支持 border-width:0.5px 就能完美体现出 hairline 的样子。

但是我看了，有些组件的css  border-width 并不是读取这个值。希望加上。
```diff
/* Border
  -------------------------- */
-  --border-width-base: 1px;
+ --border-width-base: 0.01em;
  --border-style-base: solid;
  --border-color-base: var(--color-extra-light-silver);
  --border-color-hover: var(--color-base-silver);
  --border-base: var(--border-width-base) var(--border-style-base) var(--border-color-base);
  --border-radius-base: 6px;
  --dropdown-radius: var(--border-radius-base);
  --border-radius-small: 6px;
  --border-radius-circle: 100%;
```

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
