### ISSUE TITLE
[Bug Report] el-select error when use vue-i18n

### ISSUE THREAD

**Issue by Aiyibooo** [ElemeFE/element#4467]
### Element UI version
1.2.9

### OS/Browsers version
win10 / Chrome 57.0.2987.133 (64-bit) 

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/aiyibooo/jdfq0uyd/](https://jsfiddle.net/aiyibooo/jdfq0uyd/)

### Steps to reproduce
Run

### What is Expected?
no error

### What is actually happening?
The select isn't displayed.

(found in <ElSelect>)
vue.js:1453 TypeError: r.default.locale is not a function

**Comment by pengchongfu** [comment]
@IamFive it seems that it is the problem of vue-i18n, you can use version 5.0.3 #3172
https://jsfiddle.net/jdfq0uyd/1/

**Comment by Aiyibooo** [comment]
@pengchongfu thanks

**Comment by QingWei-Li** [comment]
#4471
