### ISSUE TITLE
[Feature Request] el-select event bubbling

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4468]
### Existing Component
是

### Component Name
el-select

### Description
el-select 的原生事件似乎都被捕获了，
比如，下面代码的focus不会触发，同理，click，blur 等等都无法生效。
```
<el-select v-on:focus="onFocus()"></el-select>
```

**Comment by IamFive** [comment]
event recorded

![image](https://cloud.githubusercontent.com/assets/1578702/25430341/d6ff1886-2aae-11e7-9480-ed3f27dfde29.png)

**Comment by Leopoldthecoder** [comment]
For `click`, you need to add `.native`, like this: `v-on:click.native="onClick"`.

For `blur` and `focus`, because the outmost element of Select is not an input, so currently it does not support these to events. We'll add support in future version.
