### ISSUE TITLE
可移除标签中的$remove已不被2.0支持，建议用splice做删除操作。

### ISSUE THREAD

**Issue by firesheep** [ElemeFE/element#447]
`handleClose(tag) {
        var i = this.tags.indexOf(tag)
		if (i > -1) {
		  this.tags.splice(i, 1)
		}
      }`

**Comment by baiyaaaaa** [comment]
文档代码展示忘了修改，组件内写法没错，不影响使用

**Comment by limichange** [comment]
还没有改过来吗？现在的例子（在线运行）还是错的。
