### ISSUE TITLE
[Feature Request] Select Component remote method not triggered when query is nill

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4470]
### Existing Component
Yes

### Component Name
Select

### Description
As title, Select Component remote method not triggered on first focus. 

I think there should got a option(min-query-lenght) to decide whether to trigger remote method rather ignore by default.

```
<el-select filterable remote :remote-method="loadOptions()" :min-query-length="1"></el-select>
```

In this case, only when user input (query) length is greater than 1, then remote method will be triggered. If we set the value to 0, it will be trigger when mouse up

**Comment by IamFive** [comment]
Hello, is someone following this issue?

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this feature.
