### ISSUE TITLE
How to preload select list

### ISSUE THREAD

**Issue by franc014** [ElemeFE/element#4475]
### Existing Component
Yes

### Component Name
select

### Description
I'm trying to preload a select component with data brought from the server. 
In a form using the select component, which is set as remote searchable. When using as explained in the docs, all is ok. However, if used to preload data brought from the server, to edit purposes, i can not figure it out how to do it. Let's say i have a categories list: 

```
<el-select
                                    v-model="productForm.categories"
                                    multiple
                                    filterable
                                    remote
                                    placeholder="search a category"
                                    :remote-method="searchCategories"
                                    :loading="loading"
                                    no-match-text="No data found"
                                    no-data-text="No data found"
                            >
                                <el-option
                                        v-for="item in filtered_categories"
                                        :key="item.id"
                                        :label="item.name"
                                        :value="item.id">
                                </el-option>
                            </el-select>

```
It's supposed that if i fetch categories from the server and assign to the productForm.categories model, the select component will load the data:

   `  this.productForm.categories = product.categories; `

product is the data brought from the server with the same format applied to the select component: 
   `{id:1, name: 'games']`

However i tried this with no success. If i use the filtered_categories model, it didn't work, too:
`this.filtered_categories = product.categories; `

Is there any ways to preload data on the select component. 
Please your help.

**Comment by Leopoldthecoder** [comment]
This is not a feature request but a usage question, which shouldn't be submitted as an issue (#3693). If you find anything wrong, you can issue a bug report.
