### ISSUE TITLE
[Feature Request] Messagebox adding 'overflow: hidden' to body tag

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#4477]
### Existing Component
Yes

### Component Name
Message-Box

### Description
When opening a message box, the scrollbar on the main window disappears. The following inline style is being added to the body tag:

**style="overflow: hidden; padding-right: 17px;"**

As a result, when you open/close a messagebox, the screen 'pops', and can make the experience weird. I would like a way to remove this added style, and have **overflow** set to **scroll**.

**Comment by Leopoldthecoder** [comment]
Use the `lockScroll` attribute. It's listed in the documentation.
