### ISSUE TITLE
[Bug Report] Form validation multiple triggers

### ISSUE THREAD

**Issue by gengxuelei** [ElemeFE/element#4486]
### Element UI version
1.2.9

### OS/Browsers version
Windows10/Chrome57.0.2987.110

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/gengxuelei/2fmkg0us/](http://jsfiddle.net/gengxuelei/2fmkg0us/)

### Steps to reproduce
foucs the input  then blur the input

### What is Expected?
only blur trigger has been triggered，other two triggers not
```javasciprt
rules2: {
  pass: [{
      validator: checkPassBlur,
      trigger: 'blur'
    },
    {
      validator: checkPassFocus,
      trigger: 'focus'
    },
    {
      validator: checkPassInput,
      trigger: 'input'
    }
  ]
}
```

### What is actually happening?
only blur trigger has been triggered,other two triggers not.

Alternative solutions：
http://jsfiddle.net/gengxuelei/2fmkg0us/1/

Two questions:

1>support multiple triggers;

2>how to tirgger element form error without element's validator ?

**Comment by baiyaaaaa** [comment]
1. Form validation support multiple triggers, just like `trigger: 'blur,change'`, but do not support the focus & input trigger.
2. You can set the error on form-item
![image](https://cloud.githubusercontent.com/assets/3655403/25486771/ca7d06ae-2b94-11e7-833e-787078f47367.png)
