### ISSUE TITLE
[Bug Report] this.$confirm: cancel callback doesn't not triggered when closed by Esc or click on the mask layer

### ISSUE THREAD

**Issue by Riant** [ElemeFE/element#4492]
### Element UI version
1.2.9

### OS/Browsers version
Windows / Chrome56

### Vue version
2.3.0-beta.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/142/](https://jsfiddle.net/pj71jkyw/142/)

### Steps to reproduce
1. click the open confirm button to open the confirm box
2. click on the keyboard on the Esc or pop-up box mask layer

### What is Expected?
Trigger cancel callback like click on the close button and cancel button

### What is actually happening?
No cancel callback is triggered, and no other options can be configured for this action callback

**Comment by Leopoldthecoder** [comment]
Fixed [here](https://github.com/ElemeFE/element/pull/4851/files#diff-27b250184267261d8e837735fd53f227R132)
