### ISSUE TITLE
[Bug Report] upload components how to interact with the back-end, the back-end is how to get uploaded files

### ISSUE THREAD

**Issue by iolg** [ElemeFE/element#4493]
### Element UI version
1.2.9

### OS/Browsers version
chrome

### Vue version
2.3.0-beta.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
上面的链接是无效的
1.使用upload组件，但是不知道后端如何与其交互，action是用自己后端的地址还是？
2.如果action是自己的地址，会提示405错误，如果用案例中的地址，那么后端如何获取文件？

### What is Expected?
希望文档可以详细介绍下如何与后端交互，非文件的表单交互比较容易解决，但是文件交互不太明白，求教

### What is actually happening?
需要上传文件到服务端

**Comment by baiyaaaaa** [comment]
This is not an element's bug or feature request, if u do not know how to complete your  backend server about process file upload, you can check about [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload/wiki) document
