### ISSUE TITLE
[Bug Report] el-select component selection after value has not changed

### ISSUE THREAD

**Issue by zkeyword** [ElemeFE/element#4498]
### Element UI version
1.2.9

### OS/Browsers version
win7

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/ggxajuoc/](https://jsfiddle.net/ggxajuoc/)

### Steps to reproduce
<template>
  <el-select v-model="value" placeholder="请选择">
    <el-option
      v-for="item in options"
      :label="item.label"
      :value="item.value">
    </el-option>
  </el-select>
</template>

<script>
  export default {
    data() {
      return {
        options: [{
          value: '选项1',
          label: '黄金糕'
        }, {
          value: '选项2',
          label: '双皮奶'
        }, {
          value: '选项3',
          label: '蚵仔煎'
        }, {
          value: '选项4',
          label: '龙须面'
        }, {
          value: '选项5',
          label: '北京烤鸭'
        }],
        value: ''
      }
    }
  }
</script>

### What is Expected?
选择后 input的value应显示出来

### What is actually happening?
选择后 input的value没有显示出来

**Comment by lifeishell** [comment]
ran to the same situation. After update to 1.2.9, the el select won't work. I mean, the value is there, just not displayed. same as your example one jsfiddle here:  https://jsfiddle.net/api/post/library/pure/
Just try it.

**Comment by lifeishell** [comment]
Some extra infomations: 
1. Worked well when multiselect is on.
2. Fall back too 1.2.8/7/6, the problem still exstis. I also updated other node_modules, no clue if that will make this issue happen.

**Comment by pengchongfu** [comment]
it seems it is the problem of vue@2.3.0.

you can install vue@2.2.6 temporarily. https://jsfiddle.net/ggxajuoc/1/

**Comment by lifeishell** [comment]
Yes, that fix the issue. When fallback vue, just remember to fallback vue-template-complier eigther.

**Comment by zkeyword** [comment]
vue and vue-template-complier versions are consistent, that fix the issue

**Comment by mehooo** [comment]
vue and vue-template-complier，需要保持一直吗？

**Comment by mehooo** [comment]
@zkeyword 如果vue是2.2.6，是不是vue-template-complier也必须是2.2.6的吗

**Comment by zkeyword** [comment]
@mehooo yes

**Comment by LXMin** [comment]
the same to you ,
i just change the version of vue and vue-template-complier,
i',m waiting for the result

**Comment by LXMin** [comment]
i set the version all of vue and vue-template-complier to 2.2.6,
but it does not work

**Comment by mehooo** [comment]
@LXMin  me too

**Comment by Leopoldthecoder** [comment]
All right, I'm already on it.

**Comment by LXMin** [comment]
hey ,guys ,i have sole the problem, you need to set the package.json ,
like this: 
vue: 2.2.6
not this:
vue:^2.2.6
because the vue@2.3.0 is not suitable for the element@1.2.9
so that we have to drop down the version of vue ,
waiting for the element team to resolve the bug

**Comment by Leopoldthecoder** [comment]
Fixed in 1.3.0-beta.1.

Please note that 1.3.0-beta.1 requires Vue 2.3.x.

**Comment by oufish** [comment]
this is bug,you should use "vue": "2.2.6", not "vue": "^2.2.6",
