### ISSUE TITLE
[Bug Report] el-table selection-change can't trigger

### ISSUE THREAD

**Issue by scscms** [ElemeFE/element#4501]
### Element UI version
0.1.0

### OS/Browsers version
firefox / chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/0h3s4m2m/](https://jsfiddle.net/0h3s4m2m/)

### Steps to reproduce
升级了vue为2.3.0 el-table的selection-change事件只有全选才触发，其他选择不会触发。在vue2.2.6下还是好好的。
Upgrade the vue 2.3.0 el-table selection-change event trigger only when check all, other options will not trigger. and that vue2.2.6 was fine.

### What is Expected?
el-table的selection-change事件正常触发
the selection-change event working

### What is actually happening?
el-table的selection-change事件异常
the selection-change event abnormal

**Comment by scscms** [comment]
请拿一点专业的精神来对待每一位提问题的人!至少要看一下问题才回复。强烈建议中英文双语提问题!

**Comment by Leopoldthecoder** [comment]
@scscms 抱歉，首楼是机器人的自动回复。双语提问题当然欢迎，如果不想看到机器人的回复，可以主楼放英文，下面再以评论的方式贴出中文。

Table 的多选功能在 Vue 2.3.0 下基本瘫痪了，团队会进行修复。

**Comment by Leopoldthecoder** [comment]
Fixed in 1.3.0-beta.1
