### ISSUE TITLE
[Bug Report] Color picker dont fit correctly

### ISSUE THREAD

**Issue by cgarnier** [ElemeFE/element#4503]
### Element UI version
1.2.9

### OS/Browsers version
Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/5rt2rfhq/](https://jsfiddle.net/5rt2rfhq/)

### Steps to reproduce
* put a color picker and a input in the same div
* set display of the div on flex

### What is Expected?
The color picker should looks the same when it is used alone or against other component

### What is actually happening?
Color picker lose its minimal width. It break the appearance of the component.

**Comment by Leopoldthecoder** [comment]
You need to set `flex: 1` for `.el-input`: https://jsfiddle.net/5rt2rfhq/4/

**Comment by cgarnier** [comment]
This is a workarround. Not a fix. Why do you close it ?
