### ISSUE TITLE
[Bug Report] loading component loaded flashing

### ISSUE THREAD

**Issue by gjycdd** [ElemeFE/element#4510]
### Element UI version
1.2.9

### OS/Browsers version
win10 / chrome 58

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/u7at8atx/](https://jsfiddle.net/u7at8atx/)

### Steps to reproduce
1.刷新页面，或者载入页面
2.loading组件在短暂闪烁后显示

### What is Expected?
loading组件刷新或加载闪烁

### What is actually happening?
loading组件刷新或加载不出现闪烁

**Comment by Leopoldthecoder** [comment]
那个不是闪烁，是进入动画的效果。
