### ISSUE TITLE
[Feature Request] MessageBox prompt 输入框增加 type="password"

### ISSUE THREAD

**Issue by j4dream** [ElemeFE/element#4514]
### Existing Component
Yes

### Component Name
MessageBox

### Description
希望 MessageBox prompt 输入框增加 input type 选项。

**Comment by syn-zeta** [comment]
@j4dream Use the [Dialog component](http://element.eleme.io/#/en-US/component/dialog) instead. The MessageBox component is supposed to simulate the browser in-built `alert`, `confirm` and `prompt` methods.

Recommend closing.

**Comment by Leopoldthecoder** [comment]
@syn-zeta +1
@j4dream If you must you MessageBox, you can always set input type by manipulating the input element directly.
