### ISSUE TITLE
[Bug Report] Change page count, always show last page

### ISSUE THREAD

**Issue by savoygu** [ElemeFE/element#4516]
### Element UI version
1.2.9

### OS/Browsers version
Win10 / Chrome 55

### Vue version
2.3.0

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/pagination/src/pagination.js#L323-L331](https://github.com/ElemeFE/element/blob/dev/packages/pagination/src/pagination.js#L323-L331)

```
internalPageCount(newVal) {
      /* istanbul ignore if */
      const oldPage = this.internalCurrentPage;
      if (newVal > 0 && oldPage === 0) {
        this.internalCurrentPage = 1;
      } else if (oldPage > newVal) {
        this.internalCurrentPage = newVal === 0 ? 1 : newVal;
      }
    }
```

### Steps to reproduce
Through the filter conditions, to regain the table data, so that the total number of data reduced, while the total amount of page reduction. This will trigger  https://github.com/ElemeFE/element/blob/dev/packages/pagination/src/pagination.js#L323-L331

### What is Expected?
When switching the total number of page numbers instead of entering the total number of pages, let the current page do not display the last page, but the current page

### What is actually happening?
Whether you do not set currentPage, and the element-pagination show the last page as the current page.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
