### ISSUE TITLE
[Bug Report] Upload file didn't trigger the on-change event when we use element ui with npm

### ISSUE THREAD

**Issue by even-huang** [ElemeFE/element#4524]
### Element UI version
1.2.9

### OS/Browsers version
chrome

### Vue version
2.3.0

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/upload/src/index.vue](https://github.com/ElemeFE/element/blob/dev/packages/upload/src/index.vue)

### Steps to reproduce
use the lastest element in cdn or in npm , can not trigger the on-change event，i find the source code was different from the code in github ( the last line in handleStart method ),  i am not sure if you have fixed this bug and have not released ?

**Comment by Leopoldthecoder** [comment]
We haven't released this yet. Wait another hour please.
