### ISSUE TITLE
[Bug Report] el-table can not checked all

### ISSUE THREAD

**Issue by xujif** [ElemeFE/element#4531]
### Element UI version
1.2.9

### OS/Browsers version
all

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/leopoldthecuber/pj71jkyw/78/](https://jsfiddle.net/leopoldthecuber/pj71jkyw/78/)

### Steps to reproduce
see jsfiddle.

### What is Expected?
click "check all checkbox", the all checkbox will be checked.

### What is actually happening?
click "check all checkbox", the all checkbox will be checked,but not.

**Comment by syn-zeta** [comment]
Refer to the top section of #4505.

**Comment by Leopoldthecoder** [comment]
1.3.0-beta.1 already fixed this.
