### ISSUE TITLE
[Bug Report] Attributes remote or allow-create leads to the invalidation of the focus style of the Select component. ‘远程搜索’和‘创建条目’类型的Select组件，不能正确显示获取焦点时的样式，即蓝色边框。

### ISSUE THREAD

**Issue by shawtung** [ElemeFE/element#4533]
### Element UI version
1.2.9

### OS/Browsers version
chrome 58@macOS 10.12

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/shawtung/so4ubwu9/](https://jsfiddle.net/shawtung/so4ubwu9/)
就是官方文档的demo

### Steps to reproduce
just do some typing to focus the Select.
让Select组件获得输入焦点。

### What is Expected?
the border should be bright blue, just like other type of Select, which should be the correct focus style.
应该像其他类型的Select一样，边框变为亮蓝色。

### What is actually happening?
the focus style isn't applied correctly.
实际上边框还是hover的样式，即深灰色。

**Comment by Leopoldthecoder** [comment]
Fixed in #6151
