### ISSUE TITLE
[Bug Report] PageSize does not show

### ISSUE THREAD

**Issue by Andyczc** [ElemeFE/element#4534]
### Element UI version
1.2.9

### OS/Browsers version
mac / chrome

### Vue version
2.1.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
https://jsfiddle.net/api/post/library/pure/   直接打开

### What is Expected?
无

### What is actually happening?
无

**Comment by gluons** [comment]
I face same issue.

```
Vue: 2.3.0
Element: 1.2.9
```

See my Fiddle: https://jsfiddle.net/illuminator/oeatew52/

**Comment by Leopoldthecoder** [comment]
Ah, the same Select compatibility issue as #4498. Already fixed in 1.3.0-beta.2 .
