### ISSUE TITLE
[Bug Report] v-popover not supporting camel case

### ISSUE THREAD

**Issue by shadeofgod** [ElemeFE/element#4536]
### Element UI version
1.2.9

### OS/Browsers version
macOS 10.12.4/chrome 58.0.3029.81

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/4fpq3L5f/1/](https://jsfiddle.net/4fpq3L5f/1/)

### Steps to reproduce
set the el-popover ref and v-popover under camel case naming convention will not trigger the pop over effect correctly.
It was easy to reproduce this issue and I just made a littile change from a jsfiddle link on official docs, you can check it [here](https://jsfiddle.net/4fpq3L5f/1/)

### What is Expected?
maybe make v-popover just like other directives so we can use it like v-popover="xxxxx" instead of v-popover:xxxx for consistency, and then it could be correctly compiled under camel case naming convention.

### What is actually happening?
not sure about that but I was guessing that the browser turned v-popover:xxxx as an attribute to lower case so it throwed a type error when compiling.

**Comment by Leopoldthecoder** [comment]
For the reference element, it is recommended to use the named slot rather than binding a directive: https://jsfiddle.net/du9aa5ys/

**Comment by shadeofgod** [comment]
yeah there are certain ways to avoid this issue but I think lots of people will just use a directive like the examples in official docs. so imho it would be easy to be trapped by this bug since javascript is heavy camelcase named in most circumstances. 
Anyway its always good to let inexperienced developers know that this directive won't support camelcase.
