### ISSUE TITLE
[Bug Report] The el-select component do not show the selected item.

### ISSUE THREAD

**Issue by gzlock** [ElemeFE/element#4537]
### Element UI version
1.2.9

### OS/Browsers version
Mac Chome 58.0.3029.81 (64-bit)

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/4efvgan2/](https://jsfiddle.net/4efvgan2/)

### Steps to reproduce
* This is Element-UI official jsfiddle el-select demo, I just clicked the save button to create the demo url !
* In my project has the same issue !
The el-select component in basic usage, selecting any option (or has a default value) do not show the selected item.
![record](https://cloud.githubusercontent.com/assets/2311740/25540078/5d869b30-2c7c-11e7-8efd-955c1f33cb6e.gif)

### What is Expected?
The el-select component show selected item.

### What is actually happening?
The el-select component in basic usage, selecting any option (or has a default value) do not show the selected item.

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one. #4498 #4505
