### ISSUE TITLE
[Bug Report] upload component type picture-card with the same image can not be displayed again after uploading upload

### ISSUE THREAD

**Issue by safeie** [ElemeFE/element#4541]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
macos /chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/naxkdkyy/1/](https://jsfiddle.net/naxkdkyy/1/)

### Steps to reproduce
http://element.eleme.io/1.3/#/zh-CN/component/upload

照片墙 演示：

上传多张照片，删除一张，再重新上传这张图片，无法显示。

### What is Expected?
同一张图上传多次可以正常显示，因为你提供了预览和删除的功能，删除后再上传却不能正常显示。

### What is actually happening?
不能正常显示。

**Comment by baiyaaaaa** [comment]
unpkg.com/element-ui/lib/index.js 不会引入为正式发布的beta版本，所以世纪上你的demo使用的还是1.2.9，这个问题已经在1.3.0修复
