### ISSUE TITLE
[Feature Request] Want add the global configure

### ISSUE THREAD

**Issue by dclovec** [ElemeFE/element#4542]
### Existing Component
是

### Component Name
Many like Dialog

### Description
I want config some component's parameters globally to make most of the component customized, but now can't attained.

**Comment by Leopoldthecoder** [comment]
You can wrap Dialog up into your own custom component, register it globally, and use that component instead.

**Comment by dclovec** [comment]
But that is too fussy. And this would be used by many developers.
