### ISSUE TITLE
[Bug Report] inputValue $promp cannot be displayed in the input box

### ISSUE THREAD

**Issue by Focinfi** [ElemeFE/element#4544]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
Mac OS X 10_12_0/Chrome/56.0.2924.87

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/cx3r6vna/](https://jsfiddle.net/cx3r6vna/)

### Steps to reproduce
点击"点击打开 Message Box"

### What is Expected?
输入框显示 “inputValue”

### What is actually happening?
输入框显示 “”

**Comment by Leopoldthecoder** [comment]
In fact, 1.3.0-beta.2 doesn't have this problem: https://jsfiddle.net/cx3r6vna/1/

If you leave out `@beta`, you are actually using 1.2.9, which is not compatible with Vue 2.3.0
