### ISSUE TITLE
[Bug Report] Slider Button Doesn't Move

### ISSUE THREAD

**Issue by codelabstudios** [ElemeFE/element#4548]
### Element UI version
1.2.9

### OS/Browsers version
OSX / Chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/4j6uwecm/)

### Steps to reproduce
When dragging the button on a slider, the button doesn't move.

The 'Try It' example on this page http://element.eleme.io/1.3/#/en-US/component/slider doesn't work.

Screen recording: https://gyazo.com/f78894f36ddde68d5c658a7ce373132e

### What is Expected?
.el-slider__button-wrapper style="left: 0%;" should get updated to like left: 20% (e.g.) so it moves when we drag it.

### What is actually happening?
.el-slider__button-wrapper style="left: 0%;" doesn't get updated, so button is always at front.

https://gyazo.com/96c44f73cb13e256f9f364315c2610eb

**Comment by codelabstudios** [comment]
Updating to 1.3.0-beta.2 fixed the issue. The js fiddle on http://element.eleme.io/1.3/#/en-US/component/slider didn't work because 1.3.0 is still in beta, so the unpkg only picks up 1.2.9.

**Comment by webberwang** [comment]
The desktop mouse drag was fixed, but it doesn't work on mobile with touch. It doesn't seem like the examples work either for touch. That isn't intended behavior?
