### ISSUE TITLE
[Bug Report] Table component error setCurrentRow

### ISSUE THREAD

**Issue by wdnlwzd** [ElemeFE/element#4549]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
win10 chrome

### Vue version
2.3.0

### Reproduction Link
https://jsfiddle.net/vasttian/ntcmLrvp/2/

### Steps to reproduce
直接点击官网table组件，表格单选的在线运行，点击按钮‘选中第二行’，报错。（在官网页面点击可以正常设置第二行选中，但是在jsfiddle 则报错）。

### What is Expected?
能通过setCurrentRow 选中当前行。

### What is actually happening?
Inline Babel script:32 Uncaught TypeError: this.$refs.singleTable.setCurrentRow is not a function

**Comment by wdnlwzd** [comment]
https://jsfiddle.net/vasttian/ntcmLrvp/2/

**Comment by Leopoldthecoder** [comment]
原因和 #4548 一样，现在如果要在 jsfiddle 上看 demo，需要手动指定 @beta：https://jsfiddle.net/ntcmLrvp/3/

**Comment by wdnlwzd** [comment]
请问1.2.8不能正常使用setCurrentRow吗？ 我在1.2.8也同样报错。 @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
setCurrentRow 是 1.3.0 才加入的功能。

**Comment by wdnlwzd** [comment]
那请问1.3.0什么时候会发布到npm上？，现在项目中需要使用setCurrentRow。

**Comment by Leopoldthecoder** [comment]
已经有了
```bash
npm install element-ui@1.3.0-beta.2 -S
```

**Comment by wdnlwzd** [comment]
好的，谢谢！
