### ISSUE TITLE
[Feature Request] Support custom label in form

### ISSUE THREAD

**Issue by breeswish** [ElemeFE/element#4553]
### Existing Component
Yes

### Component Name
el-form-item

### Description
Could you add support for assigning label via slot? For example:

```html
<el-form-item>
    <span slot="label"><i class="el-icon-date"></i> Date</span>
    <el-input v-model="data.date"></el-input>
</el-form-item>
```

**Comment by xxxyangyi** [comment]
<el-select v-model="form.region" placeholder="请选择活动区域">
      <el-option label="区域一" value="shanghai"></el-option>
      <el-option label="区域二" value="beijing"></el-option>
    </el-select>

这段代码 如果 v-model 的值时 Number  类型的，就会出问题值显示不正确

**Comment by baiyaaaaa** [comment]
will be supported in 1.3.0 #4634
