### ISSUE TITLE
[Bug Report] Table w/ multiple select not work

### ISSUE THREAD

**Issue by vukhanhtruong** [ElemeFE/element#4554]
### Element UI version
1.2.9

### OS/Browsers version
Ubuntu 16.04/ Chrome Version 57.0.2987.133 (64-bit)

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/bpq3vtwe/](https://jsfiddle.net/bpq3vtwe/)

### Steps to reproduce
Click to select all checkbox

### What is Expected?
Toggle checked/unchecked all checkbox

### What is actually happening?
No checkbox was checked

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one. #4501 #4505
