### ISSUE TITLE
[Bug Report] El-Select not showing selected option (Vue 2.3.0)

### ISSUE THREAD

**Issue by Phillys** [ElemeFE/element#4556]
### Element UI version
1.2.9

### OS/Browsers version
Linux / Chrome 57 / Firefox 53

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/3nw87sr9/](https://jsfiddle.net/3nw87sr9/)

### Steps to reproduce
Select one option inside el-select.
(Works with Vue.js 2.2.6)

### What is Expected?
Selected option should be showing according to documentation; http://element.eleme.io/#/en-US/component/select#basic-usage

### What is actually happening?
Selected option is not showing.

**Comment by Phillys** [comment]
Tried v1.3.0-beta.2 with Vue 2.3.0 with sucessful results.

When is the stable version of 1.3.0 going to be released?

**Comment by Apoloser** [comment]
Same problem

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one. #4498 #4505
