### ISSUE TITLE
[Bug Report] Checkbox component affects the normal display of the drag and drop element

### ISSUE THREAD

**Issue by yscoder** [ElemeFE/element#4557]
### Element UI version
1.2.8

### OS/Browsers version
Win10 / Chrome 57.0.2987.98

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/9q9fwrc3/1/](https://jsfiddle.net/9q9fwrc3/1/)

### Steps to reproduce
具有相同样式的若干列，都添加了 `draggable` 可拖拽属性，分别进行拖拽操作。

### What is Expected?
拖拽时只影响自身元素。

### What is actually happening?
包含 checkbox 组件的列拖拽时的外观显示为将旁边的元素也拖动了。

个人测试后发现导致出现这种情况的原因是 checkbox 组件中的 input 元素添加了 `left: -999px` 样式，拖拽时的表现与实际的元素位置有关。

**Comment by leslieSie** [comment]
this bug can't reappear on my broswer

**Comment by yscoder** [comment]
This bug does not exist in the latest version
