### ISSUE TITLE
[Bug Report] Table does not Filter

### ISSUE THREAD

**Issue by stangeorge** [ElemeFE/element#4559]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
MacOS Sierra / Chrome60, Firefox53

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/t3kx7ckt/](https://jsfiddle.net/t3kx7ckt/)

### Steps to reproduce
1. Click on "Tag" cell on the table.
2. The Confirm/Reset options show up in Chinese. 
3. Click on any option Home/Office and click the first button 

### What is Expected?
1. Expected Confirm/Reset buttons to be in English. Please let me know if I need to specify language/i-18n options.
2. Expected the table to be filtered based on the selection.

### What is actually happening?
1. Confirm/Reset buttons not showing up in English like in the documentation under the "Filter" section: http://element.eleme.io/1.3/#/en-US/component/table
2. All the rows in the table disappear. It does not filter based on the checkbox.

**Comment by stangeorge** [comment]
I was able to get the labels in englisb by including this in script:
ELEMENT.locale(ELEMENT.lang.en)
and this:
https://unpkg.com/element-ui@1.2.9/lib/umd/locale/en.js

The second issue of not filtering still remains.

**Comment by Leopoldthecoder** [comment]
This is a problem with Element 1.2.9, which is not compatible with Vue 2.3.0.
1.3.0-beta.2 works fine: https://jsfiddle.net/t3kx7ckt/1/ , though the checkbox does not align. I'll fix it.

**Comment by stangeorge** [comment]
Excellent! That fixed it. The checkboxes lineup too. Thanks for the speedy response!
