### ISSUE TITLE
[Feature Request] Add a delay (debounce) to form validation

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#4560]
### Existing Component
Yes

### Component Name
Form

### Description
In the form component, you can add custom validation rules like this (from the documentation):

    rules2: {
          pass: [
            { validator: validaePass, trigger: 'change' }
          ],

Is there any way to add some kind of delay/debounce to the validator?

**Comment by Leopoldthecoder** [comment]
There is no debounce on Element's end, but you can debounce `validaePass` yourself.

**Comment by JohnAlonso** [comment]
For anyone wondering, you can achieve this like this:

Declare debounce function, or install it through npm (lodash etc.)
```JavaScript
export function debounce (func, delay = 500) {
    let timeout

    return function () {
        clearTimeout(timeout)
        timeout = setTimeout(() => { func.apply(this, arguments) }, delay)
    }
}
```
```JavaScript
import { debounce } from 'path/to/file'

const validateAsync = debounce(async (field, callback) => {
    try {
        await // async stuff
        callback()
    } catch (error) {
        callback(new Error(error.data))
    }
})

const asyncValidator = (rule, field, callback) => {
    validateAsync(field, callback)
}
```

Finally add the validator to the rules object

```JavaScript
rules: {
    asyncField: [
      { validator: asyncValidator, trigger: 'change' }
    ]
}
```
