### ISSUE TITLE
[Bug Report] Pagination choose to change the PageSize, the input will not show, and then your own official running link is not displayed

### ISSUE THREAD

**Issue by sonnyshen** [ElemeFE/element#4561]
### Element UI version
1.2.9

### OS/Browsers version
MAC / Chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击调整每页显示条数 选择改变PageSize 100

### What is Expected?
input中请选择placeholder被替换成100

### What is actually happening?
 input中仍然显示placehoder请选择

**Comment by Leopoldthecoder** [comment]
Element 1.2.9 is not compatible with Vue 2.3.0. Please upgrade Element or degrade Vue.

**Comment by sonnyshen** [comment]
@Leopoldthecoder 
打开http://element.eleme.io/#/zh-CN/component/pagination
在线运行里面的pagniation也同样不工作

**Comment by sonnyshen** [comment]
@Leopoldthecoder 
Vue版本降到2.2还是不工作

**Comment by Leopoldthecoder** [comment]
Element 1.2.9 + Vue 2.2.6: https://jsfiddle.net/vss0ho7f/
Element 1.3.0-beta.2 + Vue 2.3.0: https://jsfiddle.net/vss0ho7f/1/
