### ISSUE TITLE
[Feature Request] Progressbar Loading

### ISSUE THREAD

**Issue by thearabbit** [ElemeFE/element#4562]
### Existing Component
No

### Component Name
Progressbar

### Description
I would like to use `Progressbar Loading`.

**Comment by syn-zeta** [comment]
Can you please clarify what you mean? This is what I understood: https://jsfiddle.net/rv1g7ncc/

**Comment by thearabbit** [comment]
Thanks for your reply, It like `nprogress`

**Comment by syn-zeta** [comment]
@thearabbit ElementUI has no knowledge of HTTP requests. It is much easier to use a dedicated progress-bar component that can automatically trigger on HTTP requests from, let's say, `vue-resource` or `axios`. Take a pick: https://github.com/vuejs/awesome-vue#progress-bar
