### ISSUE TITLE
[Feature Request] Dropdown-Menu-Item'command'' s Atrribute string to Modify from string/object

### ISSUE THREAD

**Issue by jixzfw** [ElemeFE/element#4563]
### Existing Component
是

### Component Name
Dropdown-Menu-Item

### Description
下拉菜单的‘command’属性为什么要限制成string,请开放Object

**Comment by jixzfw** [comment]
开放为Object有利于动态生成的菜单执行动作

**Comment by Leopoldthecoder** [comment]
Fixed in #6244
