### ISSUE TITLE
[Bug Report] element select not work with last version vue.js

### ISSUE THREAD

**Issue by itdepartament** [ElemeFE/element#4564]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
any

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/tu4p71q9/](https://jsfiddle.net/tu4p71q9/)

### Steps to reproduce
no choosed any value

### What is Expected?
choosed needed value

### What is actually happening?
not possible choose any.
all work coorect with previous version vue.js is 2.2.6

**Comment by gimyboya** [comment]
@element-bot I confirm this issue as i have the same problem

here is a working example: https://jsfiddle.net/m87d3c3v/

it's basically the exact same first example shown in the official website : http://element.eleme.io/#/en-US/component/select

just expand the code of the first example and click on try it it will take you to the same example which is not working

**The issue:** 

the selected value does not show on the input i have tried to use `:value="value"` and checked whether the `value` property changes it seems that is dose change properly but don't reflect the changes on the input

**Comment by pengchongfu** [comment]
@itdepartament @gimyboya the Element version is 1.2.9 in unpkg.com, which is not compatible with vue@2.3.0

**Comment by gimyboya** [comment]
@pengchongfu it seems to work with vue@2.2.6 
https://jsfiddle.net/m87d3c3v/2/

is there an element version that works with vue@2.3 ?

**Comment by pengchongfu** [comment]
you can see #4498 to get more information. 
Element after 1.3.0-beta.1 works with vue@2.3.0, you can clone the code to build yourself.

**Comment by Leopoldthecoder** [comment]
@itdepartament @gimyboya For Vue 2.3.x, please use Element 1.3.0, which is now in beta:
```
npm i element-ui@beta -S
```

**Comment by itdepartament** [comment]
thank, but i use cdn, need wait ?

2017-05-01 17:17 GMT+03:00 杨奕 <notifications@github.com>:

**Comment by gimyboya** [comment]
@itdepartament you can still change the version you are using even with a cdn

**Comment by itdepartament** [comment]
big thank!

2017-05-01 21:55 GMT+03:00 gimyboya <notifications@github.com>:

**Comment by keevitaja** [comment]
Just for the info. Installing vue 2.3.2 fixed the issue:

```
"element-ui": "^1.2.9",
"vue": "^2.3.2"
```

**Comment by itdepartament** [comment]
big thank!

08.05.2017 12:51 пользователь "Tanel Tammik" <notifications@github.com>
написал:

**Comment by FrankFang** [comment]
Guys, update your element-ui to ^1.3.3

**Comment by itdepartament** [comment]
thank!

15.05.2017 17:31 пользователь "Frank Fang" <notifications@github.com>
написал:

**Comment by waLplanet** [comment]
just change:
//unpkg.com/element-ui/lib/theme-default/index.css
with:
//unpkg.com/element-ui/lib/theme-chalk/index.css

> ### Element UI version
> 1.3.0-beta.2
> 
> ### OS/Browsers version
> any
> 
> ### Vue version
> 2.3.0
> 
> ### Reproduction Link
> https://jsfiddle.net/tu4p71q9/
> 
> ### Steps to reproduce
> no choosed any value
> 
> ### What is Expected?
> choosed needed value
> 
> ### What is actually happening?
> not possible choose any.
> all work coorect with previous version vue.js is 2.2.6

it's not Vue, it's CSS.
just replace:
//unpkg.com/element-ui/lib/theme-default/index.css
with:
//unpkg.com/element-ui/lib/theme-chalk/index.css
