### ISSUE TITLE
[Bug Report] el-select not showing the selected item

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#4565]
### Element UI version
1.2.9

### OS/Browsers version
Windows 10 / Chrome 58.0.3029.81

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/02ce7zpu/](https://jsfiddle.net/02ce7zpu/)

### Steps to reproduce
Select any item in the drop down

### What is Expected?
You should see the selected item where the "Select" text is.

### What is actually happening?
Even with an item selected you still see "Select"

**Comment by ChuckFields** [comment]
This seems to be an issue with Vue 2.3.0 as this is not an issue with Vue 2.2.6
Example using Vue 2.2.6: https://jsfiddle.net/L6h4y3mg/

**Comment by ThomasXuyuntao** [comment]
@ChuckFields  yes, same finding from my side.
it take me almost half day to figure it out :(

**Comment by zkeyword** [comment]
https://github.com/ElemeFE/element/issues/4508

**Comment by Leopoldthecoder** [comment]
Please search before submitting. #4564 #4556 #4537 #4498

**Comment by ChuckFields** [comment]
@Leopoldthecoder  I thought I did a thorough search, however I didn't search for closed issues (which were also duplicates). I'll keep that in mind next time. Also, the task that remained open for this issue [#4508](https://github.com/ElemeFE/element/issues/4508) isn't english which that makes it a bit hard to search for. It seems like that would be persistent problem with this repo. Are there any solutions that you are aware of? I currently use the google translate plugin for chrome, however the 'Translate this page' does not seem to work with github so I have to select paragraphs to translate.
