### ISSUE TITLE
[Bug Report] Checkbox column selection cannot be selected for Table

### ISSUE THREAD

**Issue by schwann168** [ElemeFE/element#4568]
### Element UI version
1.2.9

### OS/Browsers version
Mac OS / Chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/uqL1sg8f/](https://jsfiddle.net/uqL1sg8f/)

### Steps to reproduce
升级 Vue2.3 之后，Table 的 checkbox 列，选择无效，全选也无效。

### What is Expected?
选择有效

### What is actually happening?
无法获取选中行

**Comment by Leopoldthecoder** [comment]
Seriously, search before submitting.

**Comment by galaa2011** [comment]
同问原因啊 ？ 能详细说下嘛

**Comment by schwann168** [comment]
@galaa2011 升级最新版，这个早已经修复了。

**Comment by galaa2011** [comment]
@schwann168 很早fork的，改了很多，升级麻烦。不过问题已经解决了，谢谢！
