### ISSUE TITLE
[Bug Report] The official basic select live demo doesn't work

### ISSUE THREAD

**Issue by RoamIn** [ElemeFE/element#4569]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
chrome  57.0.2987.133

### Vue version
2.3.0

### Reproduction Link
[http://jsfiddle.net/api/post/library/pure/](http://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
- Open  [http://element.eleme.io/#/zh-CN/component/select](http://element.eleme.io/#/zh-CN/component/select)
- Click basic select live demo link [http://jsfiddle.net/api/post/library/pure/](http://jsfiddle.net/api/post/library/pure/)
- Try it, it doesn't show what I selected

### What is Expected?
Show what I selected

> By the way, I don't know the Element UI version

### What is actually happening?
Nothing shows up

**Comment by Yooke** [comment]
It look like same as #4498

**Comment by schwann168** [comment]
Select component has problem too.
https://jsfiddle.net/48v95et6/

**Comment by Leopoldthecoder** [comment]
**Please** search before submitting.

**Comment by RoamIn** [comment]
Anyway, I think the live demo should run well
