### ISSUE TITLE
[Bug Report] The select component didn't show the user's select result 

### ISSUE THREAD

**Issue by ngloom** [ElemeFE/element#4574]
### Element UI version
1.2.9

### OS/Browsers version
Mac 10.11 Chrome 57

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/ngloom/hx1re165/](https://jsfiddle.net/ngloom/hx1re165/)

### Steps to reproduce
just click .

### What is Expected?
select will show user's choise 

### What is actually happening?
always show the no-select-text

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.
