### ISSUE TITLE
[Bug Report] pro, you help document error.

### ISSUE THREAD

**Issue by dandananddada** [ElemeFE/element#4577]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
MacOS Chrome lastest

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
打开即可 http://element.eleme.io/#/zh-CN/component/tag

### What is Expected?
我要看文档！！！

### What is actually happening?
空白页，console报错。

**Comment by Leopoldthecoder** [comment]
Sorry, my mistake.

**Comment by dandananddada** [comment]
Is it ok?
I could not read it as before.

**Comment by dandananddada** [comment]
I found version of english works well. 
Thus i can work through that, Hope you can fix Chinese document these days.

**Comment by Leopoldthecoder** [comment]
Fixed in #4614
