### ISSUE TITLE
table单选某一行BUG

### ISSUE THREAD

**Issue by First-blood** [ElemeFE/element#4580]
官网提供的在线运行 https://jsfiddle.net/api/post/library/pure/ demo直接报错了....能测试后再发出来?

**Comment by liuzhibin123** [comment]
table怎么获取勾选行的dom 呢？
 因为 我想要给所有勾选的行 设置背景颜色。

**Comment by First-blood** [comment]
@linzhibin123 去看1.3.0BT版本的代码 直接拷进编译后的element-ui common.js那个文件直接调用setCureentRow这个方法就行
