### ISSUE TITLE
[Bug Report] IE under the remote selection of autocomplete when you do not fill any content can not be selected

### ISSUE THREAD

**Issue by linxq** [ElemeFE/element#4583]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
windows   IE9 

### Vue version
2.3.0

### Reproduction Link
[ jsfiddle/codepen]( jsfiddle/codepen)

### Steps to reproduce
autocomplete 远程选择时 当不填任何内容时 无法选中， 官方的实例也同样有这个问题

### What is Expected?
autocomplete 远程选择时 当不填任何内容时 无法选中， 官方的实例也同样有这个问题

### What is actually happening?
autocomplete 远程选择时 当不填任何内容时 无法选中， 官方的实例也同样有这个问题

**Comment by Leopoldthecoder** [comment]
Only IE9 has this problem?

**Comment by linxq** [comment]
ie11 has this propblem yet

**Comment by zhuning090** [comment]
同样的情况，在IE11下，不输入查询条件的情况下触发选择无效，麻烦尽快修复，谢谢！

**Comment by slipkinem** [comment]
Why hasn't it been settled？ IE 11 , AutoComplete remote has problem...

**Comment by SlowSoulWen** [comment]
The 2.x version seems to have fixed the problem, have any good ways to fixed the problem in addition to the upgrade？

**Comment by SlowSoulWen** [comment]
问题的原因好像是：在IE浏览器下，input输入框的失焦和聚焦会触发`onChange`事件。这导致了当我们在点击选择下拉选项时，input的失焦会触发`autocomplete.vue`组件中`onChange`事件，进而导致重新查询以及其他一系列问题。在不升级2.X版本的情况下，我的做法是重写这个组件，在onChange方法添加判断：如果值和上一次相比未发生改变，则不执行代码。

**Comment by Leopoldthecoder** [comment]
The current version works fine in IE11.
