### ISSUE TITLE
[Bug Report] Select selector can not display the selected option

### ISSUE THREAD

**Issue by cherislive** [ElemeFE/element#4584]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
Windows/chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
官方示例有同样问题  https://jsfiddle.net/api/post/library/pure/
官方文档显示正常 http://element.eleme.io/1.2/#/zh-CN/component/select

### What is Expected?
如官方文档 能正确显示选中option

### What is actually happening?
Select 选择器 无法正常显示选中option

**Comment by aoiu** [comment]
same problem here

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.
