### ISSUE TITLE
表格组件在刷新的时候，表格无法渲染数据进去？

### ISSUE THREAD

**Issue by chachaxw** [ElemeFE/element#459]
这是什么原因，vuex-devtool显示有数据，自己写的表格组件刷新后也有数据显示，其他相关组件也是这种情况，刷新后就没数据了

**Comment by furybean** [comment]
能给一个重现 Demo 么？并没有其他人反馈有这个问题。

**Comment by chachaxw** [comment]
重现demo也不太方便，可以加你吗？

**Comment by furybean** [comment]
@chachaxw 加我之后，我也只是引导你给出一个可以重现的 Demo。建议简化你的问题，做成一个可以重现这个问题的例子，这样问题才比较好解决。

**Comment by chachaxw** [comment]
我写个简单的demo放到GitHub上，发给你看看吧！

**Comment by furybean** [comment]
@chachaxw 可以用：
- [CodePen](https://codepen.io/anon/pen/ozYpNA)
- [JSFiddle](https://jsfiddle.net/gmve9d3p/)

**Comment by chachaxw** [comment]
写的是单页应用，感觉用那个线上的工具不太好展示。就是正常的数据渲染到表格中，刷新后，就报
```
Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors. 
(found in component <el-table>)
```

**Comment by furybean** [comment]
标有 need repo 标签的 issue，如果 7 天没有收到任何 repo 的步骤或者 Demo，我们会做关闭处理。如果可以重现了，请再打开这个 issue。
