### ISSUE TITLE
[Bug Report] upload组件的on-change方法在添加文件时不能触发，只有在上传成功或失败是可以

### ISSUE THREAD

**Issue by Whalefallsea** [ElemeFE/element#4593]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
chrome 58.0.3029.81 (64-bit)

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/yLsbtony/](https://jsfiddle.net/yLsbtony/)

### Steps to reproduce
官网描述的是 ‘文件状态改变时的钩子，添加文件、上传成功和上传失败时都会被调用’，但是我选取文件时控制台没有log相关信息，而点击上传时才输出信息。是不是我理解错了，选取文件不是添加文件吗？

### What is Expected?
选取文件时返回选择的文件相关信息

### What is actually happening?
只有上传才会返回信息

**Comment by Leopoldthecoder** [comment]
这个问题在 1.3.0-beta.2 里修复了：https://jsfiddle.net/yLsbtony/1/
