### ISSUE TITLE
[Bug Report] Select control options are not selected

### ISSUE THREAD

**Issue by sxhjlzl** [ElemeFE/element#4594]
### Element UI version
1.2.9

### OS/Browsers version
W10  chrome 58.0.3029.81

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/146/](https://jsfiddle.net/pj71jkyw/146/)

### Steps to reproduce
<el-form-item label="在线状态" :label-width="formLabelWidth">
         <el-select v-model="insertForm.isOnline" placeholder="请选状态类型">
                <el-option label="离线" value="1"></el-option>
          </el-select>
 </el-form-item>
点击选择项后，选不中

### What is Expected?
<el-form-item label="在线状态" :label-width="formLabelWidth">
         <el-select v-model="insertForm.isOnline" placeholder="请选状态类型">
                <el-option label="离线" value="1"></el-option>
          </el-select>
 </el-form-item>
点击选择项后，选不中

### What is actually happening?
<el-form-item label="在线状态" :label-width="formLabelWidth">
         <el-select v-model="insertForm.isOnline" placeholder="请选状态类型">
                <el-option label="离线" value="1"></el-option>
          </el-select>
 </el-form-item>
点击选择项后，选不中

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.
