### ISSUE TITLE
[Bug Report] After the last update, the selection of selectors has ceased to work

### ISSUE THREAD

**Issue by iGanzai** [ElemeFE/element#4596]
### Element UI version
1.2.9

### OS/Browsers version
OS X / Google Chrome / 58.0.3029.81

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/nevs6vqz/1/](https://jsfiddle.net/nevs6vqz/1/)

### Steps to reproduce
https://jsfiddle.net/nevs6vqz/1/

### What is Expected?
That the selected field will be displayed as a result

### What is actually happening?
If you select option, the select result remains empty

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.
