### ISSUE TITLE
[Bug Report] 使用select组件，设置为multiple时，将v-model设置为某个计算属性时，无法正确地触发set动作

### ISSUE THREAD

**Issue by mingbai2006** [ElemeFE/element#4597]
### Element UI version
1.2.9

### OS/Browsers version
Chrome57

### Vue version
2.3.1

### Reproduction Link
[https://jsfiddle.net/r19kf686/](https://jsfiddle.net/r19kf686/)

### Steps to reproduce
使用select组件，设置为multiple时，将v-model设置为某个计算属性

### What is Expected?
无法正确地触发set动作，可以看到无法更改value5的值

### What is actually happening?
无法正确地触发set动作，可以看到无法更改value5的值

**Comment by paulvl** [comment]
single select is not working neither

Element UI version **1.2.9**
OS/Browsers version **Firefox 51.0.1**
Vue version **2.3.1**
Reproduction Link [https://jsfiddle.net/9tw07m3s/](https://jsfiddle.net/9tw07m3s/)

**Comment by maverickchangithub** [comment]
mine too...
is this a Vue version problem or what?

**Comment by JsonMa** [comment]
me too!!
this components doesn't work in my project!

**Comment by Leopoldthecoder** [comment]
@paulvl @maverickchangithub @JsonMa please search existing issues, and don't comment on irrelevant ones.

@mingbai2006 1.3.0-beta has fixed this: https://jsfiddle.net/r19kf686/1/
