### ISSUE TITLE
vue@2.3.2 with element1.2.8  , el-select v-model 属性失效 

### ISSUE THREAD

**Issue by yumengyuan0825** [ElemeFE/element#4599]
在最近的项目更新中 使用高版本的vue@2.3.2 再配合 element 时发现el-select组件的v-model无法显式的展示出其值  而无论给v-model 什么值（并且有其对应value的el-option ，正确的数据类型） 其显示的永远式 placehoder 的请选择  怀疑是element-ui 与 vue的高版本搭配出现的问题

**Comment by DonzQ** [comment]
我也遇到同样的问题了的。
