### ISSUE TITLE
[Feature Request]  Table row expand and collapse, automatically

### ISSUE THREAD

**Issue by grafity** [ElemeFE/element#4603]
![screenshot_solicitud](https://cloud.githubusercontent.com/assets/16164097/25630212/a4972ba0-2f6c-11e7-9af0-174874ccaa15.jpg)

When click on edit expand programatically, the row, by code.

When you click Submit, programmatically collapse, the row, using code.

It is possible by code to cause the row to expand and collapse???

Thanks..

**Comment by Leopoldthecoder** [comment]
`toggleRowExpansion` is added in 2.0
