### ISSUE TITLE
[Bug Report] Filter table does not work anymore

### ISSUE THREAD

**Issue by leo-coco** [ElemeFE/element#4604]
### Element UI version
1.2.9

### OS/Browsers version
macOs Sierra

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/zdof7hd4/](https://jsfiddle.net/zdof7hd4/)

### Steps to reproduce
- Click in tag column to filter by tag
- Pick a tag 
- Confirm

### What is Expected?
Table should be filtered by tag
Tag should be correctly selected

### What is actually happening?
Table is empty
Tag is not correctly selected

**Comment by QingWei-Li** [comment]
It is work in `element-ui@1.3.0.beta-2` https://jsfiddle.net/zdof7hd4/1/. The stable version will be released soon.

#4505
