### ISSUE TITLE
[Bug Report] Select Component not work with latest Vue

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4605]
### Element UI version
1.2.9

### OS/Browsers version
Window/Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/6s4bs9rj/](https://jsfiddle.net/6s4bs9rj/)

### Steps to reproduce
Choose any select option

### What is Expected?
Label is shown after choose any option

### What is actually happening?
Label is not shown after choose any option

**Comment by dupeiduo** [comment]
Slider component won't work either.

**Comment by IamFive** [comment]
@dupeiduo  It seems a fixed version Vue is a better practice :)

**Comment by IamFive** [comment]
Tested. Vue@2.2.6 is the last success build for Select Component.

**Comment by jzhangdev** [comment]
+1  Element UI 1.2.8 have same problems

**Comment by Leopoldthecoder** [comment]
Now you can upgrade to Element 1.3.x
