### ISSUE TITLE
[Bug Report] date-picker and time-picker interaction

### ISSUE THREAD

**Issue by fjonas** [ElemeFE/element#4607]
### Element UI version
1.2.6

### OS/Browsers version
OS X/ Chrome latest

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ep8hn01n/](https://jsfiddle.net/ep8hn01n/)

### Steps to reproduce
change value in time-picker(value3), click date-picker and open time-picker in date-picker(value1), the time-picker in date-picker(value1) change value to the same as the other time-picker(value3).

### What is Expected?
make component state isolated.

### What is actually happening?
inner state of time-picker affect date-picker unexpectedly.

**Comment by Dreamacro** [comment]
Fixed in #6090
