### ISSUE TITLE
[Bug Report] select binding attribute is invalid

### ISSUE THREAD

**Issue by CHU295** [ElemeFE/element#4609]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
win10 64

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/qa1jo36y/](https://jsfiddle.net/qa1jo36y/)

### Steps to reproduce
绑定属性无效

### What is Expected?
修复

### What is actually happening?
绑定属性无效，项目崩溃

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.
