### ISSUE TITLE
[Bug Report] [el-input] Mixed input, button style

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#4610]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
chrome 53

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/3xtx6sgx/](url)

### Steps to reproduce
Official website‘s demo will appear，Reproduction Link will not，  Element-theme-default v1.3.0-beta.1 will
![image](https://cloud.githubusercontent.com/assets/12726826/25646733/c8ad4782-2fed-11e7-9032-37437fc7e9e1.png)

### What is Expected?
border is nomal

### What is actually happening?
border is abnormal

**Comment by Leopoldthecoder** [comment]
Fixed in #4614
