### ISSUE TITLE
[Bug Report] table in the Chrome version of the 31.0.1650.63 appears to be not aligned layout situation

### ISSUE THREAD

**Issue by psaren** [ElemeFE/element#4612]
### Element UI version
1.2.9

### OS/Browsers version
windows 10 / Chrome 31.0.1650.63

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/148/](https://jsfiddle.net/pj71jkyw/148/)

### Steps to reproduce
打开链接

### What is Expected?
表格head的线与body的线不对齐

### What is actually happening?
表格head的线与body的线对齐

**Comment by Leopoldthecoder** [comment]
Chrome 31 is too old, so we do not guarantee compatibility.
