### ISSUE TITLE
[Bug Report] photo wall mode, unable to delete photos uploaded

### ISSUE THREAD

**Issue by a044161** [ElemeFE/element#4613]
### Element UI version
1.2.9

### OS/Browsers version
Win10/Chrome 58.0.3029.81

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/149/](https://jsfiddle.net/pj71jkyw/149/)

### Steps to reproduce
上传图片，在uploding是会显示 close的icon，但是hover时却消失了

### What is Expected?
hover过去能够显示 close icon，实现正常删除正在上传中的图片

### What is actually happening?
hover过去close icon 消失，无法删除正在上传的图片

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/151/ 这个例子正常吗？

**Comment by a044161** [comment]
@Leopoldthecoder 并不正常，右上角的图标显隐逻辑有错吧？就是导致无法正常删除正在上传的图片

**Comment by a044161** [comment]
@Leopoldthecoder 而且还无法上传与上一张相同的图片，这个问题貌似有被提交过

**Comment by baiyaaaaa** [comment]
@a044161 1.3.0正式发布后会修复这几个问题
