### ISSUE TITLE
[Bug Report] not full sidebar screen

### ISSUE THREAD

**Issue by pyang30** [ElemeFE/element#4618]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
chrome51

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/e0afe187/](https://jsfiddle.net/e0afe187/)

### Steps to reproduce
侧边栏不是垂直全屏的，只有一小部分

### What is Expected?
希望能在左面上下是通透的。

### What is actually happening?
左面上下不是通透的额

**Comment by pyang30** [comment]
I upated jsfiddle link to  https://jsfiddle.net/e0afe187/

**Comment by Leopoldthecoder** [comment]
This should be handle on the user's end.
