### ISSUE TITLE
Radio组件，label为0时，无法选中

### ISSUE THREAD

**Issue by zhangyanzt** [ElemeFE/element#462]
### ElementUI version
1.0.0-rc.7

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.3

### Steps to reproduce
组件调用方法
`<el-radio class="radio" v-model="radio" :label='0'>0</el-radio>
<el-radio class="radio" v-model="radio" :label='1'>1</el-radio>
<el-radio class="radio" v-model="radio" :label='2'> 3</el-radio>`
### What is Expected?
radio点击被选中。
### What is actually happening?
当label为0时，点击对应的radio无法选中，须点击其他radio后,才能进行选中。

**Comment by baiyaaaaa** [comment]
https://jsfiddle.net/WhiteCusp/gmve9d3p/21/ 试了一下无法复现，请提供在线demo

**Comment by furybean** [comment]
@baiyaaaaa 这个是解决了？
