### ISSUE TITLE
[Bug Report] table in the case of fit=true to change the width of the browser, table will re traverse data  (table 在fit=true的情况下改变浏览器的宽度，table将会重新遍历数据)

### ISSUE THREAD

**Issue by wenjie88** [ElemeFE/element#4621]
### Element UI version
1.2.9

### OS/Browsers version
Chrome 版本 58.0.3029.81

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/wen88/pj71jkyw/160/](https://jsfiddle.net/wen88/pj71jkyw/160/)

### Steps to reproduce
1.改变浏览器的窗口大小，可以观察到table中的随机数一直发生变化
2.点击情况3中的 ‘’点击显示等待动画“按钮，可以看到loading动画的时候，table中的随机数发生了变化

### What is Expected?
1.能不能做到，浏览器的宽度改变，而table不重新遍历数据？
2.能不能做到，loading全屏动画lock的时候，table不重新遍历数据？

### What is actually happening?
1.浏览器的宽度改变，随机数将会发生变化
2.loading全屏动画lock的时候，随机数将会发生变化

**Comment by coolzjy** [comment]
Table 每次 render（会发生在 resize 时）的时候读取数据是正常表现，看起来是你的实现思路有些问题，类似于随机数的数据应该提前放在 row data 中，而不应该使用 formatter 实现。

**Comment by furybean** [comment]
Fixed in #9426.
