### ISSUE TITLE
[Bug Report] [el-date-picker] click input will trigger watch

### ISSUE THREAD

**Issue by lry210** [ElemeFE/element#4624]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
chrome53

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/4turdm1z/](https://jsfiddle.net/4turdm1z/)

### Steps to reproduce
1、pick a range
2、click input （not pick），trigger watch
![image](https://cloud.githubusercontent.com/assets/12726826/25650313/879098be-300e-11e7-80d3-c4946400bd1e.png)

### What is Expected?
trigger watch until change

### What is actually happening?
trigger watch when click

**Comment by wacky6** [comment]
Possible Fix: commit https://github.com/wacky6/element/commit/e209fa2f1c187ed4742c2b1042343b84608730c3

Demo: https://jsfiddle.net/wacky6/wya53tm9/1/

@lry210 Could you verify this problem is solved?

**Comment by Leopoldthecoder** [comment]
@wacky6 Looks it's solved. Could you send us a PR?

**Comment by wacky6** [comment]
Proposed commit: https://github.com/wacky6/element/commit/187cafcf230ac0ad4416f5b5faa92948c2138753

Related PR: https://github.com/ElemeFE/element/pull/4681

**Comment by Leopoldthecoder** [comment]
@wacky6  Thanks!

**Comment by lry210** [comment]
@wacky6 Great，thanks!

**Comment by Leopoldthecoder** [comment]
Fixed in #4837
