### ISSUE TITLE
[Bug Report] El-Select input does not show the label of the selected option

### ISSUE THREAD

**Issue by iraklisg** [ElemeFE/element#4627]
### Element UI version
1.3.0-beta.2

### OS/Browsers version
Version 57.0.2987.98 Built on 8.7, running on Debian 8.7 (64-bit)

### Vue version
2.3.2

### Reproduction Link
[http://jsfiddle.net/j7ob0etn/](http://jsfiddle.net/j7ob0etn/)

### Steps to reproduce
Probably to to [this](https://vuejs.org/v2/guide/list.html#Components-and-v-for) change in Vue 2.0.0 , when I try to use the select component like this 

```
    <el-select v-model="value8" filterable placeholder="Select">
        <el-option
            v-for="item in options8"
            :label="item.label"
            :value="item.value">
        </el-option>
    </el-select>
```
     
I get the following error, while the selected option's label does not shown in select input

>  WARNING in ./ ~ /vue-loader/lib/template-compiler?{"id":"data-v-34a51ef3"}!./~/vue-loader/lib/selector.js?type=template&index=0!./resources/assets/js/contractuals/components/Mycomponent.vue
> (Emitted value instead of an instance of Error) <el-option v-for="item in options8">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
> 

Moreover when I select an option, its label is not shown in the select input

This behavior is reflected in the component's try-it! [jsfiddle](http://jsfiddle.net/j7ob0etn/) provided by Element-ui 

Adding a key option like below, make the warning disapear **but the  selected option's label is still not visible**
```
    <el-select v-model="value8" filterable placeholder="Select">
        <el-option
            v-for="item in options8"
            :key="item.value"
            :label="item.label"
            :value="item.value">
        </el-option>
    </el-select>
```

### What is Expected?
When I select an option, the label of that option to appear in the select input placeholder

### What is actually happening?
The selected option's label is not shown

**Comment by iraklisg** [comment]
fiddle link is updated

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.

**Comment by rshuzz** [comment]
Mine,too. I remembered it worked well last week. I just want to know what happened, how to fix this issue.

**Comment by iraklisg** [comment]
@rshuzz please see issue #4564 
what worked for me was to 
`npm i element-ui@beta -S`

**Comment by FrankFang** [comment]
Guys, update your element-ui to ^1.3.3
