### ISSUE TITLE
element@1.2.9    select组件选不上去值

### ISSUE THREAD

**Issue by hwb2167sq** [ElemeFE/element#4631]
https://jsfiddle.net/5znz9gbq/

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.

**Comment by loanniss** [comment]
你们到底有没有看问题的啊，我在上面找了那么久  都没有看到解决问题的方法！！

**Comment by EasonShen1989** [comment]
我也遇到这个问题，怎么解决啊？
