### ISSUE TITLE
[Bug Report] element-ui@1.2.9   点击select的option ，select框未展示点击的项

### ISSUE THREAD

**Issue by hwb2167sq** [ElemeFE/element#4633]
### Element UI version
1.2.9

### OS/Browsers version
os

### Vue version
2.1.8

### Reproduction Link
[https://jsfiddle.net/5znz9gbq/](https://jsfiddle.net/5znz9gbq/)

### Steps to reproduce
点击select下拉框option 

### What is Expected?
点击的option ，select框显示点击的项

### What is actually happening?
点击的option木有选择在select框里

**Comment by jikkai** [comment]
#4564

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.

**Comment by FrankFang** [comment]
Guys, update your element-ui to ^1.3.3
