### ISSUE TITLE
[Feature Request] Show/Hide el-table-column

### ISSUE THREAD

**Issue by Chris0lsen** [ElemeFE/element#4636]
### Existing Component
Yes

### Component Name
el-table-column

### Description
I'd like to be able to bind an expression to a property (such as :hidden="hideCol" or :visible="showCol") that determines whether a column in an el-table is shown or hidden. I'm currently working around this by creating a new array to pass to :data whenever I need to change which columns are visible, but that ends up resetting all of the column width values.

**Comment by lampo1024** [comment]
这个功能很实用，昨天也是自己处理实现这个功能。希望可以集成到table组件中。

**Comment by renxia** [comment]
you can simply use `v-if` or `v-show`

**Comment by lampo1024** [comment]
具体的功能应该是像这样的：
![22](https://cloud.githubusercontent.com/assets/3262079/25688698/fbc582ee-30b3-11e7-829f-f18f4474b69f.png)
或者：
![33](https://cloud.githubusercontent.com/assets/3262079/25688717/281b1cdc-30b4-11e7-8af4-a09d1df4f8ee.png)

即：可以动态地显示或者隐藏列

**Comment by Leopoldthecoder** [comment]
You can do that with `v-if`

**Comment by martincarles** [comment]
What if I generate my columns with v-for but still want to show/hide some columns in some cases? V-if and v-for don't work well together.
Thanks
