### ISSUE TITLE
[Feature Request] can not let select and autocomplete two components, automatically let the first option after screening highlights?

### ISSUE THREAD

**Issue by tangyue0924** [ElemeFE/element#4637]
### Existing Component
是

### Component Name
Autocomplete,Select

### Description
在第一次选择时，必须按下键盘 ↓ ，才可以选中第一个选项，是否可以默认让第一个高亮，按下enter直接选中第一个？

**Comment by tangyue0924** [comment]
Need your help,Thanks!

**Comment by zhujz** [comment]
同样有这个需求

**Comment by wacky6** [comment]
Try Select's `default-first-option`
