### ISSUE TITLE
拖拽UI

### ISSUE THREAD

**Issue by JasonCSharpCoder** [ElemeFE/element#464]
能不能后续加点拖拽类的控件？

**Comment by JasonCSharpCoder** [comment]
就是类似http://www.dowebok.com/demo/155/index4.html
这样一些拖拽功能的插件

**Comment by furybean** [comment]
我们讨论后暂无计划做这个组件。

**Comment by cag2050** [comment]
@JasonCSharpCoder 最后，这个组件你怎么实现的？

**Comment by JasonCSharpCoder** [comment]
没有在再用Vue 做、、、



在 2017-05-27 13:39:39，"Chen Anguo" <notifications@github.com> 写道：


@JasonCSharpCoder 最后，这个组件你怎么实现的？
