### ISSUE TITLE
upload组件中file-list里文件对象的url字段名希望能改成自定义

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/element#4640]
上传的文件列表, 例如: [{name: 'food.jpeg', url: 'https://fuss10.elemecdn.com/3/63/4e7f3a15429bfda99bce42a18cdd1jpeg.jpeg?imageMogr2/thumbnail/360x360/format/webp/quality/100'}]	array

以上为官方文档file-list的内容，现在的版本是写死字段为url，我们项目中字段名是image_url，而转换来转换去并不优雅，所以希望能提供选项可以自定义file-list中url的字段名

**Comment by jialuchun** [comment]
遇到过 同样的问题 submit 和 fetch时都需要转化……特别麻烦……
