### ISSUE TITLE
[Feature Request] want to be able to customize the URL field of the file-list number in the upload component

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/element#4641]
### Existing Component
是

### Component Name
Upload 上传

### Description
上传的文件列表, 例如: [{name: 'food.jpeg', url: 'https://fuss10.elemecdn.com/3/63/4e7f3a15429bfda99bce42a18cdd1jpeg.jpeg?imageMogr2/thumbnail/360x360/format/webp/quality/100'}]	array

以上为官方文档file-list的内容，现在的版本是写死字段为url，我们项目中字段名是image_url，而转换来转换去并不优雅，所以希望能提供选项可以自定义file-list中url的字段名

**Comment by csvwolf** [comment]
You can use `http-request` to custom the default behavior
