### ISSUE TITLE
[Bug Report] nested Dialog click on the mask layer or ESC when closing Body Scroll Unlock

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [ElemeFE/element#4642]
### Element UI version
1.3.0-beta.3

### OS/Browsers version
Mac/Chrome 58.0.3029.81

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/StrayCat/pj71jkyw/164/](https://jsfiddle.net/StrayCat/pj71jkyw/164/)

### Steps to reproduce
1.打开外层 Dialog

2.通过外层 Dialog 中的按钮打开内层 Dialog

3.点击遮罩层关闭内层 DIalog

4.Body Scroll Unlock!!!

顺便一提:

5.如果设置了:close-on-click-modal="false" :close-on-press-escape="false"

6.通过内层 Dialog 中的"Cancel Button"关闭内层 Dialog(不复现这个问题)

7.但是如果狂点遮罩层之后再进行Step6,该情况也会发生

提供的 Demo 包含了2个问题 删除:close-on-click-modal="false" :close-on-press-escape="false" 可以复现前四步的问题

### What is Expected?
无论点击Dialog 中按钮关闭,还是点击遮罩层关闭内层 Dialog,Body Scroll 都不应该Unlock

### What is actually happening?
点击遮罩层关闭内层 Dialog,then body scroll unlock

**Comment by Leopoldthecoder** [comment]
@BeiKeJieDeLiuLangMao 请确认最新版的 Element 是否还有这个问题。以上 demo 似乎已经无法复现这里描述的问题了。
