### ISSUE TITLE
[Bug Report] attribute: before-close and done (dosen't) work dialog box before-close attribute does not work, done () does not work

### ISSUE THREAD

**Issue by fairyier** [ElemeFE/element#4644]
### Element UI version
1.3.0-beta.3

### OS/Browsers version
win10/google

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击打开dialog---打开对话框----点击确认或者取消按钮，都不会触发:before-close="handleClose"  ，点对话框右上角的关闭可以触发:before-close="handleClose"调用comfirm弹窗，但是点confirm的确认按钮，只关闭confirm弹窗本身，dialog对话框还在，done（）没起作用

### What is Expected?
点击确认或者取消按钮可以触发:before-close="handleClose"    ，点击confirm的确认按钮两个弹窗 都要关闭

### What is actually happening?
点击确认或者取消按钮没触发:before-close="handleClose"    ，点击confirm的确认按钮，只关闭confirm弹窗本身

**Comment by Leopoldthecoder** [comment]
You have total control over the confirm and cancel buttons, so you can do whatever you want in their click handler.

Element 1.3.0 is released, and the `done` method can now close Dialog correctly.
