### ISSUE TITLE
[Bug Report] tag component css mess when used with v-for

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4645]
### Element UI version
1.2.9

### OS/Browsers version
Window/Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/bo85xyas/](https://jsfiddle.net/bo85xyas/)

### Steps to reproduce
Just check the display tags, Maybe the transitions cause the problem

### What is Expected?
should got some px between tags

### What is actually happening?
tags are connected

**Comment by keevitaja** [comment]
Same happens with dynamic tags. Also new tag input gets `width 100%`

![screenshot_2017-05-04_10-24-36](https://cloud.githubusercontent.com/assets/158787/25693807/10810014-30b4-11e7-8893-4c09b524b643.png)


Quick fix:

```
    .el-tag {
        margin-right: 5px;
    }

    .input-new-tag {
        width: auto;
    }
```

**Comment by pengchongfu** [comment]
@IamFive you can remove the space between `el-teg` like this https://jsfiddle.net/bo85xyas/1/.
then define the style.

**Comment by IamFive** [comment]
@pengchongfu  oh.. thx for the information. Should add a default __margin-right__ style  will be cool
