### ISSUE TITLE
[Feature add height to the height of row change can adjust the height of a line, similar to the properties of the table column each in width

### ISSUE THREAD

**Issue by kungcn** [ElemeFE/element#4648]
### Existing Component
否

### Component Name
height

### Description
It takes a long time to use css to change height of each row. That's expensive so I want to have a convenient feature like width in table columns. Thank you~

目前根据已经关闭的issue发现，只能通过覆盖css来实现，而且找到了设置的属性覆盖了半小时还没有成功(可能是我辣鸡的关系)，既然有width的调整那为什么不能再有一个height的调整呢，哇好想哭。迫切希望有该新特性

**Comment by Leopoldthecoder** [comment]
请自行通过 CSS 解决。
