### ISSUE TITLE
[Bug Report] dialog doesn't work in element@1.2.9

### ISSUE THREAD

**Issue by Weiyu-Chen** [ElemeFE/element#4650]
### Element UI version
1.2.9

### OS/Browsers version
chorme 56

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/chenweiyu/xztc2433/](https://jsfiddle.net/chenweiyu/xztc2433/)

### Steps to reproduce
1. enter the jsfiddle of  the dialog example from http://element.eleme.io/#/zh-CN/component/dialog.
2. change the element version.
3. run and find it doesn't work.

### What is Expected?
work normally

### What is actually happening?
can't open dialog.

**Comment by Leopoldthecoder** [comment]
`:visible.sync` is a feature of 1.3.0. See the changelog for details.

**Comment by wanghongrui** [comment]
从哪里获取已经编译好的1.3.0版本。npm上面还没有更新

**Comment by Leopoldthecoder** [comment]
@wanghongrui npm i element-ui@beta
