### ISSUE TITLE
Unknown custom in tree renderContent element: function

### ISSUE THREAD

**Issue by pisse** [ElemeFE/element#4651]
### Element UI version
1.3.0-beta.3

### OS/Browsers version
win7 chrome

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/z5d5tvsc/](http://jsfiddle.net/z5d5tvsc/)

### Steps to reproduce
elementui 为按需引入
tree render-content:

let btn = h('el-button', {
          props: {type: 'success'},
          domProps: {
            innerHTML: '查询'
          }
        })
      return btn

### What is Expected?
渲染出elButton

### What is actually happening?
 Unknown custom element: <el-button> - did you register the component correctly

**Comment by Leopoldthecoder** [comment]
The error message clearly states that you have an unregistered component. I'm afraid it has nothing to do with Tree's render-content, because your JSFiddle works fine.
