### ISSUE TITLE
[Bug Report] 1.2.9 version of the following table, select checkbox is not valid

### ISSUE THREAD

**Issue by enddering** [ElemeFE/element#4654]
### Element UI version
1.2.4

### OS/Browsers version
mac10.12.4／chrome 58.0.3029.81

### Vue version
2.2.4

### Reproduction Link
[https://jsfiddle.net/rhn433vu/1/](https://jsfiddle.net/rhn433vu/1/)

### Steps to reproduce
表格checkbox全选不生效

### What is Expected?
不懂

### What is actually happening?
不懂

**Comment by exonuclease** [comment]
You can use element-ui@1.2.9 with vue@2.2.6 or element-ui@1.3.0 with vue@2.3.2.Vue 2.3 fix v-model checkbox binding with Array index.

**Comment by Leopoldthecoder** [comment]
Please search existing issues before submitting a new one.
