### ISSUE TITLE
[Bug Report] upload component select only one call to on-success

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/element#4655]
### Element UI version
1.3.0-beta.3

### OS/Browsers version
chrome 53

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/rp409zgq/](https://jsfiddle.net/rp409zgq/)

### Steps to reproduce
点击上传，选择2个文件，查看浏览器控制台

### What is Expected?
调用2次on-success方法

### What is actually happening?
只调用1次on-success方法，一个上传成功，另一个正在上传中

**Comment by cntaoyu** [comment]
我也是这样，多选上传只回调了一次on-success，你解决了吗？

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/32927909-3872f3ae-cb8a-11e7-9670-6904a42c6db3.gif)
