### ISSUE TITLE
[Bug Report] Form value binding issue

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4658]
### Element UI version
1.3.0-beta.3

### OS/Browsers version
Window/Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/gmhvrgws/](https://jsfiddle.net/gmhvrgws/)

### Steps to reproduce
Choose option for __el-select__ and original select
el-select's label won't display, original select works as expected.

### What is Expected?
el-select's label displays

### What is actually happening?
el-select's label did not display

**Comment by IamFive** [comment]
If we initial the model data, everything works.

**Comment by Valumard** [comment]
When I change your data to:
`
data() {
      return {
        form: {
         region: ""
        }
      }
    },
`
it works

**Comment by Leopoldthecoder** [comment]
@IamFive Yes: https://vuejs.org/v2/guide/reactivity.html
