### ISSUE TITLE
[Bug Report] Slider-Component unexpected behavior with min value

### ISSUE THREAD

**Issue by Valumard** [ElemeFE/element#4661]
### Element UI version
1.2.9

### OS/Browsers version
Win7/Chrome 59

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/3opLdndp/1/](http://jsfiddle.net/3opLdndp/1/)

### Steps to reproduce
Double Click in the input, type 358 (for example).

### What is Expected?
The displayed value should be 358.

### What is actually happening?
After hitting the 3, the input changes to 10 (min value) and so my value is 1058.
But it doesn't happen every time.

**Comment by pengchongfu** [comment]
@Valumard actually, it is caused by component `InputNumber`.

and I think it is hard to solve...
