### ISSUE TITLE
[Feature Request] el-alert

### ISSUE THREAD

**Issue by SallyOne** [ElemeFE/element#4663]
### Existing Component
Yes

### Component Name
el-alert

### Description
为什么 el-alert的visible 状态写在组件内而不是通过 props 传递

**Comment by Leopoldthecoder** [comment]
The internal `visible` is for closing the instance when the close icon is clicked. If you need to control its visibility programatically, you can use `v-show` or `v-if`.

**Comment by SallyOne** [comment]
@Leopoldthecoder i know, but i think should only one status to control show or hide
