### ISSUE TITLE
[Feature Request] Table total row horizontal scroll bar position display is not good

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4671]
### Existing Component
是

### Component Name
el-table

### Description
https://jsfiddle.net/h1sm1wf6/       希望能把滚动条位置放到合计行下面

**Comment by schwann168** [comment]
这个问题在 UI 上显示不是很好，特别是当有 fixed 固定列时，样式兼容不太好。
如: https://jsfiddle.net/h1sm1wf6/2/

Yeah, the style looks not good in fixed column table.
eg:  https://jsfiddle.net/h1sm1wf6/2/

**Comment by sonnyshen** [comment]
其实还有个问题，就是如果没有触摸板，鼠标没有左右滑动功能的话，横向的滑动条如何显示和让用户可以拖动？就是如果用mac，是有触摸板可以左右滑动的，或者是有的鼠标可以让用户左右滑动，但是现在table的话，无法左右滑动

**Comment by furybean** [comment]
Sorry, we have no plan to support this.
