### ISSUE TITLE
[Bug Report] Switch change event return unexpect 

### ISSUE THREAD

**Issue by zx5435** [ElemeFE/element#4674]
### Element UI version
1.3.0

### OS/Browsers version
all

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
when I set on-value="100" off-value="0"
so I will want get my set when change event, not true/false

### What is Expected?
handleChange(event) {
    this.$emit('change', this.value);
},

### What is actually happening?
handleChange(event) {
    this.$emit('change', event.currentTarget.checked);
},

**Comment by Leopoldthecoder** [comment]
Fixed in #4675
