### ISSUE TITLE
[Bug Date-picker can not V-model bind a null object. date selector cannot bind to an empty object in the Report] use to.

### ISSUE THREAD

**Issue by exonuclease** [ElemeFE/element#4677]
### Element UI version
1.3.0

### OS/Browsers version
Fedora chrome60

### Vue version
2.3.2

### Reproduction Link
[https://github.com/ElementUI/element-starter](https://github.com/ElementUI/element-starter)

### Steps to reproduce
Just use https://github.com/ElementUI/element-starter and update element-ui to1.3.0-beta.3,update vue to 2.3.2,insert a date-picker.Use v-model  to bind it to a null object and click it.

### What is Expected?
输入框为空 可以点开选择

### What is actually happening?
报错 undefind没有replace属性

**Comment by Leopoldthecoder** [comment]
Why do you bind the value to a null object?

**Comment by exonuclease** [comment]
@Leopoldthecoder Initialization.

**Comment by Leopoldthecoder** [comment]
Then don't bind it to a null object. Instead, `''`, `null` and `new Date()` all works.
