### ISSUE TITLE
[Bug Report] total line will not scroll, use the show-overflow-tooltip header row total dislocation

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4679]
### Element UI version
1.3.0-beta.3

### OS/Browsers version
Mac/Safari

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/vf6fruy7/8/](https://jsfiddle.net/vf6fruy7/8/)

### Steps to reproduce
点击查询按钮

### What is Expected?
修复bug

### What is actually happening?
修复bug

**Comment by totomakers** [comment]
Some usefull info for solve 👍 

Error come from : 
 + el-table height attribute, hide scroll of footer
 + missing el-table__footer-wrapper : overflow: auto

Now you can scroll footer too but not link with body
Modify component for handle scroll position (JS required)

I don't know if you can remove body proper (overflow:auto) when you have a footer for only have one scroll \o/

**Comment by subo-romens** [comment]
Thanks  totomakers, I think it's a bug, I don't know if I can fix it, or how can I fix it,

**Comment by Leopoldthecoder** [comment]
Fixed in #4717
