### ISSUE TITLE
[Bug Report] el-autocomplete component input Chinese, enter the second characters when the input box will be cleared

### ISSUE THREAD

**Issue by wyu-prc** [ElemeFE/element#4684]
### Element UI version
1.3.0

### OS/Browsers version
MacOS 10.12.4

### Vue version
2.3.2

### Reproduction Link
[http://codepen.io/anon/pen/zwEwRx](http://codepen.io/anon/pen/zwEwRx)

### Steps to reproduce
在自动完成输入框里输入中文
输入第二个字时整个输入框被清除

### What is Expected?
正常输入中文

### What is actually happening?
第一个字输入正常，后续输入时输入框被清除了

**Comment by Leopoldthecoder** [comment]
Fixed in #4718
