### ISSUE TITLE
[Bug Report] 1.3.0 version, dialog components use: visible.sync, press the ESC button will only cancel the mask layer, dialog is not closed

### ISSUE THREAD

**Issue by Astlvk** [ElemeFE/element#4686]
### Element UI version
1.3.0

### OS/Browsers version
windows10 / chrome 58.0.3029.96 (64-bit)

### Vue version
2.3.2

### Reproduction Link
[http://jsfiddle.net/2fmh7kmq/6/](http://jsfiddle.net/2fmh7kmq/6/)

### Steps to reproduce
dialog组件使用 :visible.sync
开启dialog

### What is Expected?
正常关闭dialog

### What is actually happening?
只取消了遮罩层，dialog未关闭。

**Comment by Leopoldthecoder** [comment]
Fixed in #4706
