### ISSUE TITLE
[Feature Request] DateTimePicker time to select the upper and lower arrow button to select the number

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#4688]
### Existing Component
Yes

### Component Name
DateTimePicker

### Description
DateTimePicker 时间选择增加上下箭头按钮选取数字
现在只能用滚轮选择时间数字，就是默认不开启，至少增加选项可以开启其他方式选取数字，不然在滚轮不能使用的情况下，无法选取数字

**Comment by Leopoldthecoder** [comment]
Duplicate of #3795
