### ISSUE TITLE
[Feature Request] DateTimePicker output data types can now only be date class, can support other types

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#4689]
### Existing Component
Yes

### Component Name
DateTimePicker

### Description
DateTimePicker 输出的数据类型现在只能是date类，能不能支持其他类型，因为组件选择时间后文本框的日期格式看，组件内部应该已经有格式化处理的相关函数了。能不能增加选项配置，输出字符串类型，比如我就想要文本框上面那样的字符串格式日期。不然获得date后，我还有用momentjs做处理

**Comment by wacky6** [comment]
个人觉得不合适。`{Date, Time}Picker`应当能准确并无二义性地表达时间点。

**Comment by panhezeng** [comment]
？可是一般后端输出都是类似YYYY-MM-DD HH:mm:ss的格式字符串，后端也通常就要这样的，而且明明组件文本框上已经是这种格式的字符串了，结果我得到值确实个date类，我还需要做转换，我觉得至少可以增加一个选项配置。

**Comment by Leopoldthecoder** [comment]
Element cannot do everything for you. Keeping the type of DateTimePicker's binding value as `date` makes most sense.

Besides, the parameter in `change` callback is a formatted string if you set its `format`: https://jsfiddle.net/5vw2o7e8/
