### ISSUE TITLE
[Feature Request]add an attribute of the current column to the Table component?

### ISSUE THREAD

**Issue by angeltxwh** [ElemeFE/element#4691]
### Existing Component
是

### Component Name
Table

### Description
因为做报表展示时列很多，我看到现在Table组件只能高亮鼠标所在的行。

为了保证更好的可读性想要增加高亮当前列

不知道是否可以添加？

**Comment by angeltxwh** [comment]
没人处理一下吗

**Comment by Leopoldthecoder** [comment]
无计划支持。
