### ISSUE TITLE
[Bug Report] pagination component page change not effect

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4693]
### Element UI version
1.3.0

### OS/Browsers version
Window/Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/wLycswhc/](https://jsfiddle.net/wLycswhc/)

### Steps to reproduce
click go btn, then click on page size like __3__, then click go btn again.

### What is Expected?
1. click go btn, go to page 5 - right
2. click page size 3, go to page 3 - right
3. click go btn again, nothing changes - wrong

### What is actually happening?
1. click go btn, go to page 5 - right
2. click page size 3, go to page 3 - right
3. click go btn again, go to page 5

**Comment by Leopoldthecoder** [comment]
You need to sync `page.page`: https://jsfiddle.net/wLycswhc/1/
