### ISSUE TITLE
[Bug Report] 100% width for `el-autocomplete` class

### ISSUE THREAD

**Issue by KrishnaPG** [ElemeFE/element#4695]
### Element UI version
1.3.0

### OS/Browsers version
Chrome latest

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/KrishnaPG/pj71jkyw/176/](https://jsfiddle.net/KrishnaPG/pj71jkyw/176/)

### Steps to reproduce
Create an `el-autocomplete` as shown in the fiddle and try to resize the window.

### What is Expected?
Just like the `input` element the `auto-complete` element should resize to fit the parent width 100%

### What is actually happening?
The `el-autocomplete` class is missing the `width:100%` style

**Comment by Leopoldthecoder** [comment]
Generally inputs with a dropdown menu don't have the `width:100%` style because the dropdown menu would seem too wide as it always shares width with the input box.
