### ISSUE TITLE
[Bug Report] Dialog not Centered in IE9 

### ISSUE THREAD

**Issue by daysv** [ElemeFE/element#4702]
### Element UI version
1.3.0

### OS/Browsers version
windows 7 / IE 9

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/sg1pjtrk/](https://jsfiddle.net/sg1pjtrk/)

### Steps to reproduce
Just use <el-dialog> 

### What is Expected?
Dialog appears in the center.

### What is actually happening?
Dialog not Centered in IE9.

**Comment by rhinonan** [comment]
same with me!
