### ISSUE TITLE
[Bug Report] V-model input data changes, input box in the value will not be updated in real time (there will be a chance to refresh)

### ISSUE THREAD

**Issue by zctya** [ElemeFE/element#4704]
### Element UI version
1.3.0

### OS/Browsers version
Chrome 

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/zctya/bjn8b6f7/1/](https://jsfiddle.net/zctya/bjn8b6f7/1/)

### Steps to reproduce
比如这个我需要输入的值不能小于10，input视图中的数值会有几率小于10的值出现，el-input不会总是刷新视图

### What is Expected?
输入小于10的数值，input视图中要显示10

### What is actually happening?
input中出现小于10的数值，而实际不能出现小于10的数值

**Comment by Leopoldthecoder** [comment]
#3595 #3762
