### ISSUE TITLE
can't bind visible of dialog to a computed value

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4708]
### Element UI version
1.3.0

### OS/Browsers version
all

### Vue version
2.3.2

### Reproduction Link
https://github.com/zzzgit/dialogCannotClose

### Steps to reproduce
0.install element v1.3
1.create a child component,`<template><el-dialog :visible.sync="computedVisible"></el-dialog></template>`
2.define a prop `toggle` for the child component
3.define a computed value `computedVisible` based on the prop `toggle`
4.pass prop value to the child component from the parent,like this:`<child :toggle="toggle"><child>`
5.set toggle to true,and make the dialog to show
6.the dialog can not be closed by click

### What is Expected?
close the dialog by click

### What is actually happening?
nothing

**Comment by zzzgit** [comment]
if computed value is not supported in this situation,and directly modifying the value passed from the parent is not allowed
then,what could i do?

**Comment by Leopoldthecoder** [comment]
Please write a demo.

**Comment by zzzgit** [comment]
okay,i will give you a demo repo tomorrow

**Comment by zzzgit** [comment]
https://github.com/zzzgit/dialogCannotClose

**Comment by Leopoldthecoder** [comment]
I sent a PR for a correct usage.

About computed property, you can check this out: https://jsfiddle.net/8vrrebd5/
