### ISSUE TITLE
[Feature Request] The default value of Select can not support the transfer of a label and value array of objects, now only support value single value array

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#4709]
### Existing Component
Yes

### Component Name
Select

### Description
Select默认值能不能支持传一个label和value的对象数组，现在只支持value的单值数组，
我看源码setSelected方法调用getOption方法，
const label = typeof value === 'string' || typeof value === 'number'
          ? value : '';
        let newOption = {
          value: value,
          currentLabel: label
        };
这里能不能改下，
或者暴露cachedOption，让我们能传cachedOption进去。

**Comment by Leopoldthecoder** [comment]
What is your use case?
