### ISSUE TITLE
[Bug Report] For <el-input> the change event is emitted on every keypress

### ISSUE THREAD

**Issue by freeman-g** [ElemeFE/element#4711]
### Element UI version
1.3.0

### OS/Browsers version
Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/zw97tx80/](https://jsfiddle.net/zw97tx80/)

### Steps to reproduce
Enter anything into the input

### What is Expected?
The onchange event should be emitted/triggered when the input looses focus, not as soon as any input is entered

### What is actually happening?
The onchange event is emitted immediately

**Comment by syn-zeta** [comment]
Yes, the regular `onchange` event is fired when a field loses focus, and the regular `oninput` behaves like `@change` of Element, so there is a confusion there. But, the `@change` is more intuitive as evident by the # of views of [this answer](http://stackoverflow.com/questions/6290442/html-input-type-text-onchange-event-not-working).

Try the regular `onblur` or `onfocusout` events instead: https://jsfiddle.net/zw97tx80/1/

**Comment by freeman-g** [comment]
Thanks for getting back to me.

We thought about onblur and onfocusout but those aren't really what we are looking for because those don't mean that the HTML input has actually changed.

We can definitely work around this issue, so it's not critical...but we thought it might make sense for the Element inputs to follow the base HTML paradigms.

**Comment by vipplus** [comment]
keyup event?

**Comment by QingWei-Li** [comment]
@freeman-g Maybe you can use native event `@change.native`

```html
<el-input v-model="input" v-on:change.native="handleChange"></el-input>
```

**Comment by Leopoldthecoder** [comment]
The `change` event serves more like Vue's watch than the native HTML `change`.

@freeman-g Your point makes sense, but it will be a huge break change. So we'll keep it as it is now.

**Comment by freeman-g** [comment]
@Leopoldthecoder - thank you - sounds reasonable
@QingWei-Li using `@change.native` worked perfectly - thank you for the suggestion
