### ISSUE TITLE
[Bug Report] el-switch is always on when created

### ISSUE THREAD

**Issue by jackwangyubo** [ElemeFE/element#4721]
### Element UI version
1.3.0

### OS/Browsers version
chrome58

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/178/](https://jsfiddle.net/pj71jkyw/178/)

### Steps to reproduce
see in jsfiddle

### What is Expected?
v-model work

### What is actually happening?
el-switch is always 'on' when created

**Comment by Leopoldthecoder** [comment]
`0` is a number, but `off-value="0"` means the off value is string `'0'`: https://jsfiddle.net/pj71jkyw/179/
