### ISSUE TITLE
新建vue项目，使用element-ui 中的select组件，无法选中！！

### ISSUE THREAD

**Issue by loanniss** [ElemeFE/element#4722]
新建vue项目，使用element-ui 中的select组件，无法选中！！

**Comment by loanniss** [comment]
你们是统一回答的吗？  醉了

**Comment by Leopoldthecoder** [comment]
这位用户您好，我们认为，使用开源项目遇到问题时的正确姿势是：
- 首先去项目仓库的 issue 里搜索是否有类似问题已经被提出，您如果仔细搜索了，就会找到 #4498 和 #4508 ，从而解决您的问题；
- 如果搜索之后确实没有找到类似结果，可以提交一个新的 issue，同时为了帮助我们快速定位问题，我们要求 issue 是带有重现链接的（如果问题比较简单，可以是一个 JSFiddle demo；如果比较复杂，可以是一个 GitHub 仓库），很遗憾您的这个 issue 没有符合条件，所以被我们的机器人关闭了；
- 具体到您的问题，可以将 Element 的版本升级至 1.3.0，应该就会得到解决。如果还有问题，欢迎给我们提新的 issue，当然，是需要带上重现链接的哦~

最后，祝您使用 Element 愉快。
