### ISSUE TITLE
[Bug Report] Select Dropdown Keyboard Highlighter not working

### ISSUE THREAD

**Issue by mastermoo** [ElemeFE/element#4725]
### Element UI version
1.3.1

### OS/Browsers version
Mac / Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/uxzL83he/](https://jsfiddle.net/uxzL83he/)

### Steps to reproduce
1. Type "o"
2. Wait for auto complete dropdown
3. Hit the [down] key on your keyboard
4. element in dropdown does not get highlighted

### What is Expected?
You should see which element is highlighted, when using "up" and "down" keys.

### What is actually happening?
dropdown elements won't highlight

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/4728/files#diff-714bc47586c25909dcdad45d530b51e2R10
