### ISSUE TITLE
[Bug Report] <ElDialog instance>.open() not working in 1.3.X.

### ISSUE THREAD

**Issue by hafley66** [ElemeFE/element#4726]
### Element UI version
1.3.0

### OS/Browsers version
Mac OSX 10.11.6

### Vue version
2.3.2

### Reproduction Link
[http://jsfiddle.net/cqmb160b/](http://jsfiddle.net/cqmb160b/)

### Steps to reproduce
1. 
```html
<el-dialog ref="dialog">
```
2. 
```javascript
export default {
    methods: { 
        openDialog() { this.$refs.dialog.open() }, 
        closeDialog() { this.$refs.dialog.close() }, 
     }
  }
```
3. 
```html
<el-dialog ...> 
     ... @click="openDialog" ...
</el-dialog>
```
4. Results in fade with no render. 

### What is Expected?
Opening of dialog through API.

### What is actually happening?
It is not rendering, but is fading.

**Comment by paulvl** [comment]
Notification is not working neither

**Comment by Leopoldthecoder** [comment]
@hafley66 I removed `open` and `close` methods in the Dialog doc but forgot to add to the changelog that they are deprecated. Sorry about that. Now you can bing a variable to `visible` and manipulate that variable in `openDialog` and `closeDialog`.

@paulvl How is Notification not working?

**Comment by zzzgit** [comment]
you mean that the two methods will be removed in the future?

**Comment by Leopoldthecoder** [comment]
@zzzgit Yes. This is a compromise. According to my tests, `.sync` and `v-model` do not work well together. If we keep `v-model` compatible, `open` and `close` kinda have to be removed.
