### ISSUE TITLE
[Bug Report] get an error: Unknown custom element: <el-collapse-transition> while importing Menu/Submenu alone rather than importing all

### ISSUE THREAD

**Issue by ryancui-** [ElemeFE/element#4727]
### Element UI version
1.3.0

### OS/Browsers version
WIndows 10/Mac OS, Chrome 58

### Vue version
2.3.2

### Reproduction Link
[https://github.com/ryancui-/vue-transition-issue](https://github.com/ryancui-/vue-transition-issue)

### Steps to reproduce
1. npm i
2. npm run dev
3. visit http://localhost:8086

### What is Expected?
The menu should has a transition effect as in version 1.2.9.

### What is actually happening?
The transition disappeared and an warn message show in the console.

**Comment by Leopoldthecoder** [comment]
Fixed in #4728

**Comment by EmadAdly** [comment]
still problem in
 `"element-ui": "^1.4.0"`
 ` "vue": "^2.3.3"`

**Comment by saenzramiro** [comment]
Same here!

**Comment by orionlu0916** [comment]
same problem in
"element-ui": "^1.4.1"
"vue": "^2.3.3"

**Comment by orionlu0916** [comment]
@EmadAdly, @saenzramiro try to remove "element-ui" in your "node_modules" folder, and reinstall this framework again with `npm install element-ui`

**Comment by EmadAdly** [comment]
thanks
fix it by update element-ui to 1.4.2

**Comment by saenzramiro** [comment]
@orionlu0916 Great! Works now on 1.4.2.

Thank you @Leopoldthecoder and @orionlu0916!
