### ISSUE TITLE
有加入简易数据表格的的打算吗？

### ISSUE THREAD

**Issue by ringcrl** [ElemeFE/element#473]
非常喜欢这一整套框架，觉得用来做后台管理实在太方便太美观了。

可是缺少后台常用的一个功能数据表格。

导致需要引入 vue-admin

https://github.com/fundon/vue-admin

现在已经是饿了么前端的死忠粉，移动端用mint-ui，桌面端用element，已经不想再引入其他东西了

**Comment by furybean** [comment]
指的是这个吗：https://vue-admin.fundon.me/#/tables/basic

**Comment by ringcrl** [comment]
@furybean 

https://vue-admin.fundon.me/#/charts/chartist

指的是这个哦

**Comment by furybean** [comment]
@ringcrl 那你引入这个好像就可以了： https://gionkunz.github.io/chartist-js/
图表和 Element 定位有差距，暂时不考虑做。
