### ISSUE TITLE
[Bug Report] dialog.close doesn't work

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4730]
### Element UI version
1.3.1

### OS/Browsers version
all

### Vue version
2.3.2

### Reproduction Link
[https://github.com/zzzgit/dialogCannotClose](https://github.com/zzzgit/dialogCannotClose)

### Steps to reproduce
1.run the project
2.click on the button
3.the dialog can not been closed

### What is Expected?
no

### What is actually happening?
this is the solution of [this issue](https://github.com/ElemeFE/element/issues/4708),but it does not perfect.

**Comment by Leopoldthecoder** [comment]
#4726
```javascript
btnClick_cb(){
  this.inner_visible = false;
}
```

**Comment by 68zch** [comment]
啥意思啊
