### ISSUE TITLE
[Bug Report] v-loading BUG when use in a component which will be close

### ISSUE THREAD

**Issue by sqchenxiyuan** [ElemeFE/element#4731]
### Element UI version
? - 1.3.1

### OS/Browsers version
win10/chrome56.0

### Vue version
? - 2.3.2

### Reproduction Link
[https://jsfiddle.net/sqchenxiyuan/8a5vkauz/](https://jsfiddle.net/sqchenxiyuan/8a5vkauz/)

### Steps to reproduce
1.点击toB
2.loading结束后  会发现滚动条消失
3.控制台查看样式可发现 loading插件对body的样式的操作没有复原

---
1.click toB
2.after loading you will find the scrollbar disappear
3.open the console     you can see the body's style not restore

### What is Expected?
loading插件对body的样式操作复原
----
the body's style restore

### What is actually happening?
loading插件对body的样式操作没有复原
----
the body's style not restore

**Comment by Leopoldthecoder** [comment]
You can go to `/b` in the next tick: https://jsfiddle.net/8a5vkauz/1/

**Comment by sqchenxiyuan** [comment]
谢谢dalao
希望这个解决方法能写在loading的说明里。。。
不然我们这些初学者很懵逼的啊
