### ISSUE TITLE
select框无法显示label

### ISSUE THREAD

**Issue by xsunday** [ElemeFE/element#4732]
选择select下拉一项数据后，select框没显示选中的文字， 控制台下看到 对应model的值是改变了

**Comment by cench** [comment]
同问 我今天也出现这个问题，不知道是不是跟版本有关 vue 2.2.6    element 1.2.9

**Comment by cench** [comment]
@xsunday  https://jsfiddle.net/61bgzrxx/  更新到 1.3.1 就好了  链接上的版本有这个Bug
