### ISSUE TITLE
chrome 57.0.2987.133 (64-bit)版本 鼠标滚动失灵

### ISSUE THREAD

**Issue by miaosipeng** [ElemeFE/element#4734]
http://element.eleme.io/#/zh-CN/component/installation  页面用chrome 57.0.2987.133 (64-bit)版本打开时，鼠标滚动失灵

**Comment by Leopoldthecoder** [comment]
看看是不是什么浏览器插件影响到了，我们试下来没问题，也没有其他用户反馈这个问题。
