### ISSUE TITLE
[Bug Report] 在disable的button上使用Tooltip失效

### ISSUE THREAD

**Issue by luckyyyyy** [ElemeFE/element#4737]
### Element UI version
1.3.1

### OS/Browsers version
macos / chrome56

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/q95b1mfL/](https://jsfiddle.net/q95b1mfL/)

### Steps to reproduce
见jsfiddle

### What is Expected?
一般情况下 禁用会提示用户禁用的原因 我觉得谁比较合理的

### What is actually happening?
...

**Comment by pengchongfu** [comment]
see [doc](http://element.eleme.io/#/en-US/component/tooltip)

> Disabled form elements are not supported in tooltip, see more information at MDN, please wrap disabled form elements.

wrapper a div like [this](https://jsfiddle.net/q95b1mfL/1/)

**Comment by luckyyyyy** [comment]
@pengchongfu thanks

**Comment by add-goodboy** [comment]
<el-tooltip :disabled="scope.row.attestationStatus == 0 ? true : false" content="只能操作状态值为认证中的用户" placement="top">
            <el-row>
              <el-tooltip content="审核通过" placement="top">
                <el-button type="success" :disabled="scope.row.attestationStatus == 0 ? false : true"
                           size="mini" icon="el-icon-check" circle @click="handleSuccess(scope.row)"></el-button>
              </el-tooltip>
              <el-tooltip content="审核不通过" placement="top">
                <el-button type="danger" :disabled="scope.row.attestationStatus == 0 ? false : true"
                           size="mini" icon="el-icon-close" circle @click="handleClose(scope.row)"></el-button>
              </el-tooltip>
            </el-row>
            </el-tooltip>
在最外层对整个操作按钮进行tooltip包裹,如果按钮是禁用状态将显示最外层,如果条件不满足则将外层tooltip进行disabled(禁用),这样养无论禁用的还是未禁用的按钮tooltip都互不干扰

**Comment by oo10** [comment]
同样遇到，令人疑惑的是，mac上按钮disable并不会导致tooltip失效，仅仅在win上出现该问题。（chrome）
