### ISSUE TITLE
[Bug Report] DatePicker的周视图，在特定顺序的操作后，下拉日历时无法选中当前指定日期所对应的周

### ISSUE THREAD

**Issue by yangguichun** [ElemeFE/element#4738]
### Element UI version
1.3.1

### OS/Browsers version
win10, chrome 58

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/13266839793/95bfghzc/](https://jsfiddle.net/13266839793/95bfghzc/)

### Steps to reproduce
1）点击选择周的datePicker，选择2017-5-21这一周
2）然后点击 Add按钮，调整该datePicker关联的model值为2017-5-1；
3）然后再点开DatePicker的下拉列表，2017-5-1所在周没有高亮，选中的还是2017-5-21号的那一周；

### What is Expected?
在执行上文的第三步时，DatePicker的下拉日历中应该选中2017-5-1的那一周

### What is actually happening?
没有选中2017-5-1的那一周，选中的还是2017-5-21号的那一周；

**Comment by Leopoldthecoder** [comment]
Fixed in #4739
