### ISSUE TITLE
[Feature Request] 1.2.9到1.3.1的升级太多不兼容了吧

### ISSUE THREAD

**Issue by ShiJianwen** [ElemeFE/element#4740]
### Existing Component
是

### Component Name
无

### Description
很多在 1.2.x 用得好好的功能在 1.3.1 里面突然就不管用了，用法和逻辑上的改变都有，次版本升级难道不是要保证向下兼容吗？这样很容易坑到那些只指定主版本的用户吧。

**Comment by Leopoldthecoder** [comment]
请针对具体问题提 issue。
