### ISSUE TITLE
[Feature Request] 请问transfer组件能与tree组合使用吗？

### ISSUE THREAD

**Issue by shuzihao** [ElemeFE/element#4741]
### Existing Component
是

### Component Name
transfer、tree

### Description
由于项目需要在transfer组件里面展示tree组件，不知道elementui支不支持这两个组件组合使用

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
