### ISSUE TITLE
[Bug Report] 带筛选的table，无法触发filter-method

### ISSUE THREAD

**Issue by hfq-pengyuanyuan** [ElemeFE/element#4742]
### Element UI version
1.2.9

### OS/Browsers version
window10 64位/chrome

### Vue version
2.3.2

### Reproduction Link
[http://jsfiddle.net/xhfe0y4o/1/](http://jsfiddle.net/xhfe0y4o/1/)

### Steps to reproduce
点击表头上的标签

### What is Expected?
选中

### What is actually happening?
无法选中

**Comment by Leopoldthecoder** [comment]
Element 1.2.9 与 Vue 2.3.x 不兼容，请升级至 Element 1.3.x

**Comment by hfq-pengyuanyuan** [comment]
谢谢，已解决
