### ISSUE TITLE
[Bug Report] Cannot Use the Up and Down Arrow Keys to Navigate the Options in the Select Dropdown @ 1.3.1

### ISSUE THREAD

**Issue by kevinheyo** [ElemeFE/element#4746]
### Element UI version
1.3.1

### OS/Browsers version
Win 7 / Chrome 58

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/phx291g1/](https://jsfiddle.net/phx291g1/)

### Steps to reproduce
1. Using mouse to click the "Select" component to open the dropdown

2. Try to use the up and down keyboard keys to navigate the options, but failed in element-ui 1.3.1.

　　  ( Success in element-ui 1.2.9 )

Thanks for your attention

### What is Expected?
User can navigate the options just like the element-ui 1.2.9 shows

### What is actually happening?
No response when pressing the up and down keys

**Comment by chikara-chan** [comment]
This has been fixed in #4728.  https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue#L10
