### ISSUE TITLE
[Bug Report] In Cascader, when option has not children, hover it, the option's hide child option one should items

### ISSUE THREAD

**Issue by joneqian** [ElemeFE/element#4749]
### Element UI version
1.3.1

### OS/Browsers version
All

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/qianqing/L4y5mbnr/](https://jsfiddle.net/qianqing/L4y5mbnr/)

### Steps to reproduce
比较复杂，英文不太好，所以用中文，忘见谅！
当一级菜单中，既存在有子菜单又有无子菜单的选项时，当鼠标先移动到有子菜单的选项，然后再移动到无子菜单的选项时，之前的子菜单没有消失，不太符合用户的使用习惯（在expand-trigger="hover"模式下比较明显）

### What is Expected?
比较复杂，英文不太好，所以用中文，忘见谅！
无子菜单时，隐藏子菜单！

### What is actually happening?
比较复杂，英文不太好，所以用中文，忘见谅！
当一级菜单中，既存在有子菜单又有无子菜单的选项时，当鼠标先移动到有子菜单的选项，然后再移动到无子菜单的选项时，之前的子菜单没有消失，不太符合用户的使用习惯（在expand-trigger="hover"模式下比较明显）

**Comment by remones** [comment]
Is there any feedback on this issue? It confused me a lot...

**Comment by madmanAnjun** [comment]
he means , in cascader hover mode, when u hover some menu with children, then second menu is expand , then u hover the other menu without children, the previous menu is not hiding. I encounter the bug at 2.4.7
