### ISSUE TITLE
布局和背景色不好用！

### ISSUE THREAD

**Issue by gthanks** [ElemeFE/element#475]
### ElementUI version
1.0.0-rc.7 

### OS/Browers version
windows7 64bit/firefox 49.0.1/chrome53.0.2785.143 64bit 

### Vue version
2.0.3

### What is actually happening?
布局无法像官方文档中那样的显示，背景颜色也显示不出来，另外字体也不知道如何设置

**Comment by baiyaaaaa** [comment]
背景色是文档例子展示样式。布局无法像官方文档中那样的显示请提供在线demo
