### ISSUE TITLE
[Feature Request] 为 before-upload 属性的函数增加一个回调函数参数

### ISSUE THREAD

**Issue by bestvip** [ElemeFE/element#4751]
### Existing Component
Yes

### Component Name
Upload

### Description
希望能为 before-upload 属性的函数增加一个回调函数参数。
因为我需要先从服务器拉取验证信息，然后才上传图片。
如果没有这个回调函数参数的话，感觉解决不了这个问题。

**Comment by Leopoldthecoder** [comment]
详细描述一下你的场景吧，没有太明白你需要这个回调函数做什么。

**Comment by bestvip** [comment]
我晚上想了一下，发现我想错了。手动上传应该能满足我的需求，给你门添麻烦了。
