### ISSUE TITLE
[Bug Report] el-pagination 在火狐浏览器下的显示差异 El-pagination display differences in Firefox

### ISSUE THREAD

**Issue by divisey** [ElemeFE/element#4752]
### Element UI version
1.3.1

### OS/Browsers version
windows 7 / Mozilla Firefox 53.0.2

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/186/](https://jsfiddle.net/pj71jkyw/186/)

### Steps to reproduce
使用火狐浏览器打开上述链接
open the link with fire fox

### What is Expected?
组件内部应该垂直对齐
Components should be aligned vertically

### What is actually happening?
组件没有垂直对齐
Components is not aligned vertically

**Comment by Leopoldthecoder** [comment]
Fixed in #4756.
