### ISSUE TITLE
[Bug Report] In Checkbox-group, trigger change event before check or uncheck checkbox!

### ISSUE THREAD

**Issue by joneqian** [ElemeFE/element#4753]
### Element UI version
1.3.1

### OS/Browsers version
chrome v42

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
In Checkbox-group, trigger change event before check or uncheck checkbox!

### What is Expected?
In Checkbox-group, trigger change event after check or uncheck checkbox!

### What is actually happening?
In Checkbox-group, trigger change event before check or uncheck checkbox!

**Comment by Leopoldthecoder** [comment]
Closing for invalid demo link.

**Comment by Leopoldthecoder** [comment]
Closing for invalid demo link.
