### ISSUE TITLE
[Bug Report] 在safari下，fix-table 固定列渲染不正确

### ISSUE THREAD

**Issue by 632781460** [ElemeFE/element#4757]
### Element UI version
1.3.1

### OS/Browsers version
safari 最新

### Vue version
2.3.2

### Reproduction Link
[https://codepen.io/anon/pen/PmEwBw](https://codepen.io/anon/pen/PmEwBw)

### Steps to reproduce
1.使用异步数据渲染复杂的表数据，表数据中包含各种标签
2.如果使用了固定列，fix-table的宽度按和固定列宽度按一样，导致safari未按照colgroup渲染

### What is Expected?
div.el_fixed_body-wrapper 的宽度按为 layout.fixedWidth  , table.ex-fixed-table为layout.bodyWidth

### What is actually happening?
div.el_fixed_body-wrapper 的宽度按为 el-fixed-width , table.ex-fixed-table为 layout.fixedWidth

**Comment by Leopoldthecoder** [comment]
Please provide a valid demo.

**Comment by heisjoe** [comment]
我也遇到这样的问题呢。 设置 flex 列不起作用，最后撑开了表格

**Comment by 632781460** [comment]
@Leopoldthecoder https://jsfiddle.net/nmw8Lsd0/22/  
fix-header 中的table就没有完全撑开；在控制台解决这个渲染的问题有2个办法
1，将table的宽度设置为何bodyWidth
2，取消table-layout: fixed， 然后再次勾选，让safari重新渲染

**Comment by Jinrenjie** [comment]
<img width="1201" alt="qq20170515-151912 2x" src="https://cloud.githubusercontent.com/assets/5665135/26046532/ecd0c952-3981-11e7-8eb0-178f3e64b41d.png">
Safari 10.1 下有会出现表头不对齐
