### ISSUE TITLE
[Bug Report] babel-plugin-component throw an error when loading CollapseTransition?

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4758]
### Element UI version
1.3.1

### OS/Browsers version
all

### Vue version
2.3.2

### Reproduction Link
no

### Steps to reproduce
1.load element components on demand
2.`import {Button,Tree,CollapseTransition} from 'element-ui'`
3.an error will been thrown `Cannot find module "element-ui/lib/collapse-transition"`

### What is Expected?
no

### What is actually happening?
no

**Comment by QingWei-Li** [comment]
```js
// fade/zoom 等
import 'element-ui/lib/theme-defaut/base.css';
// collapse 展开折叠
import CollapseTransition from 'element-ui/lib/transitions/collapse-transition';
import Vue from 'vue'

Vue.component(CollapseTransition.name, CollapseTransition)
```
