### ISSUE TITLE
el-upload 设置with-credentials依旧无法跨域

### ISSUE THREAD

**Issue by kiisapo** [ElemeFE/element#4760]
![image](https://cloud.githubusercontent.com/assets/14362152/25832798/745fb1b8-349f-11e7-921d-b6b44c754854.png)

代码如图；

这个接口是需要登录授权后才能上传文件，但是开启with-credentials后cookie依然无法发送到服务器；这个接口通过axios是没有问题的；是我的编码姿势不对吗？请解惑~

![image](https://cloud.githubusercontent.com/assets/14362152/25832893/1d3b8f50-34a0-11e7-8a9d-9b231b91d0c0.png)

![image](https://cloud.githubusercontent.com/assets/14362152/25832943/762a3a8a-34a0-11e7-9598-d2908a27b888.png)

**Comment by dsky1990** [comment]
@kiisapo 解决了吗，我碰到同样的问题

**Comment by dsky1990** [comment]
@Zeus-Iqd 解决了,需要后端协调

**Comment by twodogwang** [comment]
@dsky1990 请问具体需要后端协调啥？我感觉我这里是没有携带cookie去请求

**Comment by dsky1990** [comment]
@twodogwang 后端option解决跨域，前端在上传组件上要配置with-credentials

**Comment by dsky1990** [comment]
@twodogwang 应该不会啊，设置了就会带cookie过去了，你请求的框架用的什么

**Comment by twodogwang** [comment]
@dsky1990 我和提这个issue的楼主是一样的问题，都是用的elementUI的上传组件的时候加上:with-credentials="true"之后请求中还是没有携带cookie

**Comment by twodogwang** [comment]
@kiisapo 你好 请问你后来如何解决这个问题？

**Comment by dsky1990** [comment]
直接`with-credentials`，不要`:with-credentials="true"`

**Comment by twodogwang** [comment]
@dsky1990 没有区别啊..不知道为啥就是带不上cookie，然后后台返回一个新的给我，哎

**Comment by wqzwh** [comment]
我也是遇到这个问题，设置with-credentials这个依然不能带上cookie

**Comment by twodogwang** [comment]
@wqzwh 我记得当时是后端的问题，开发环境有options请求，后端没有给我预检请求通过所以我没携带cookie好像

**Comment by udbmnm** [comment]
不是with-credentials的问题，调试可以看到withCredentials为true，使用自带的上传一直被options，目前通过:http-request解决，ajax.js里面看了也没发现问题，待定位

**Comment by nevermo2013** [comment]
> @dsky1990 大佬解决了吗？遇到同样的问题，请求头的cookie和其他气球的cookie 信息根本不一样

我的也是同样的问题,带上withCredentials之后,sessionid跟之前的不一样,无法通过验证. 请问你解决了吗?

**Comment by Hong-quan-hai** [comment]
session的samesite属性设置为none

**Comment by Marhooo** [comment]
cookie中hostOnly的原因关系

<el-upload>中的action我如果写成127.0.0.1:端口号这种方式，会导致host像下面那样，跟你们出现一样的问题，导致Sec-Fetch-Site: cross-site
![image](https://user-images.githubusercontent.com/15125523/133879158-981ddd29-3eff-4fb2-bee1-17c266119916.png)

解决方法     127.0.0.1:端口号改成localhost:端口号 

![image](https://user-images.githubusercontent.com/15125523/133879355-4129bbf1-ce32-46de-adee-a8a5fab05b89.png)
