### ISSUE TITLE
[Bug Report] Component DatePicker will auto convert to UTC datetime without offset

### ISSUE THREAD

**Issue by IamFive** [ElemeFE/element#4763]
### Element UI version
1.3.1

### OS/Browsers version
Window/Chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/d6qc8fnq/6/](https://jsfiddle.net/d6qc8fnq/6/)

### Steps to reproduce
pick a date like today

### What is Expected?
datepicker value should be exactly today

### What is actually happening?
datepicker value is a datetime of UTC 0. For example, today is 2017-05-09, then the value will auto deduct 8 hour(chinese is UTC 8), and show "2017-05-08T16:00:00.000Z"

**Comment by IamFive** [comment]
Fixed me if this is a feature but not bug.

I think add a new expect-timezone props is a good choice, user-input datetime could be convert to utc-0 first, and then convert to the expect-timezone.

**Comment by IamFive** [comment]
Hello, anyone is following this issue?

**Comment by scscms** [comment]
https://jsfiddle.net/d6qc8fnq/7/
