### ISSUE TITLE
[Feature Request] Tree tree control box can choose to add the function can be disabled

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#4767]
### Existing Component
是

### Component Name
Tree树形控件

### Description
Tree树形控件可选择框加上可禁用的功能，添加disabled-checkbox属性来禁用checkbox的选择，有些场景仅仅需要展示一棵树哪些节点被选中了，而不需要进行操作。希望能加上这个属性

**Comment by clarkdo** [comment]
+1

**Comment by mcdongWang** [comment]
@Leopoldthecoder 请问何时会增加这个功能 我看你只是关闭了相似问题 并没有其他相关处理

**Comment by Leopoldthecoder** [comment]
这里可以讨论一下。@LastHeaven @clarkdo @mcdongWang @markselby9

现在 @mcdongWang @markselby9 都提了 PR 增加这个属性：#5899 #5720 ，但是两者的行为是不一致的。

设想这样一个 Tree：
```
|- parent
   |- child1 // 此节点为 disabled
   |- child2
```
这时用户勾选 parent，child1 是否应该也变为选中状态？
- 按照 #5899 的实现，此时 child1 也会被选中。从 @LastHeaven 的需求来看，整棵树的所有节点都是 disabled 的，但是为了「展示一棵树哪些节点被选中了」，那么需要调用 `setCheckedNodes` 或 `setCheckedKeys` 来选中节点，#5899 的实现能够满足。
- 按照 #5720 的实现，此时 child1 不会被选中。在一些场景下，需要某个节点无论如何也不能被选中，即点击它本身、它的父节点、它的子节点都不能改变它的选中状态，#5720 的实现能够满足。

换句话说，两种实现都有不能满足的场景。归根结底是这样一个问题：设置了 disabled 的节点，还能不能通过点击其父子节点或通过代码来改变它的选中状态？各位可以说说自己的意见。

**Comment by mcdongWang** [comment]
首先, 实在抱歉. 因为我的失误 我的代码只提交了第一个commit 是我的问题, 我会尽快重新更改我的提交.

回到讨论的问题, 关于 disable 属性设置后 是否能通过其父元素被选中等非当前节点操作, 去更改当前节点.
这里可以进行分类讨论.

首先, 我们 要明确 disabled的概念定义 我认为是不可操作 而不是不可选, 也就是说 如果他是默认选中 且 不可点 那么他的值一直都是true

从是否应该区分 展现disable 和 交互disable的维度去看这个问题
* 如果只是为了展现树的节点选中状态 那么, 我认为应该有另一个属性去在当前树全局控制, 通过UI层面去用另一种状态展示 来表达这棵树的仅可读状态 而不是通过disable这个属性来控制 这解决了 @LastHeaven 的问题
* 如果是交互disable 那么还要继续分类去讨论
    * 如果当前节点disable 那么我认为他的所有子节点(其实用后代节点更为准确)应该都是disabled 即使数据上没有设置 我们也应该在处理数据渲染时, 添加上disable属性 也就是说 disable是来控制当前节点的选中状态 是否可以改变 而不是是否可以被选中
    * 如果是选中了当前节点的父节点(其实用祖先节点更为准确), 我们要讨论它的父节点的选中状态是否影响该节点, 我认识是不应该影响, 因为他不可操作, 而不是不可选. 也就是当前节点的值 不能更改 所以存在一种情况, 如果某子节点disable 且当前没有被选中,那么当我们选中其父节点时, 父节点永远是半选状态,因为他的某个子节点不能被操作(在当前情况下 是 不能被选中)

综上所述, 我的观点是 
1. 首先, 要明确 disable 的概念 是不能被选中 还是不能被操作, 这是整个问题讨论的基点
2. 如果disable 是 不能被操作, 那么 交互disable 和 展现 disable 两个问题都可以解决
    1. 当前节点disable 那么他的所有后代节点 都不可操作 保留状态值
    2. 当前节点disable 那么他的祖先元素被选中 它的值不会被改变 保留状态值
        1. 如果当前值 是 disable 且 被选中 那么 不管其他兄弟节点的选中状态 他的祖先节点 应该是半选状态或全选状态 不存在不选状态
        2. 如果当前值 是 disable 且 未被选中 那么 不管其他兄弟节点的选中状态 他的祖先借点 应该是半选状态 或者是 空 不存在全选状态


PS: 补充关于通过代码set的问题
1. 节点有disable属性时, 当前节点不能set
2. 如果需要set, 那么需要提供一个新的方法 setDisabledKeys / setDisabledNodes 先关闭他的disabled状态后 再进行修改, 同时 UI交互上 因为设置了disable状态 也应该有对应的交互

At the end: 想得有点多, 我的代码也没有完全实现, 如果我的方案可以被接受, 我可以抽时间完成以下这个部分的PR

以上观点, 大家可以多多讨论哈, 在家写的, 比较放松, 怕有逻辑漏洞

**Comment by markselby9** [comment]
hi，才看到消息，只能手机回复了。。
1，我理解的disabled应当是加载之后值就不可变了，初始值可以是选中并且disabled，但是之后不应该再可被toggle，包括set value或者点击父节点都不应该改变，否则disable某个节点的意义就非常模糊。这里我是故意这样处理的
2，个人感觉没必要再给一个已经disable的节点去增加额外的api去设置他的value，这会导致不必要的复杂度，也需要额外的参数处理。现有的api应该已经足够应付常用应用场景了
以上。。

**Comment by mcdongWang** [comment]
@markselby9 我们对于disable的定一 应该是一样的

关于 set value的问题 目前我们team也没有太多这样的场景 

所以 我觉得 首先确认了disable的含义 大部分问题就已经解决了

@Leopoldthecoder 你看一下 是否和我们disable在概念上是一致的

**Comment by LastHeaven** [comment]
@mcdongWang @markselby9 @Leopoldthecoder 
我认为disabled属性应该只对用户操作进行限制，不限制js对其的操作，可以通过set来改变其的值。
也就是说设置为disable属性的节点是不能通过界面上的选中来改变其值的，不管是通过选中其父节点还是其本身都不能改变disable属性节点的值，只能通过set value或者改变其绑定的数据来改变，意味着这是可以通过给某个按钮绑定一个事件执行这个set操作来改变这个值。
因为有些场景是可以共用一颗树的，而不是当其值发生改变时去重绘一颗树。
如：
例1.比如为某个用户分配角色时（权限是挂在角色下面的，权限用树表示），需要实时的知道这个角色下有哪些权限，选择角色时，节点的选中项就在实时发生变化。（这里的树可能仅仅就只用作展示）
例2.复杂一点的场景：可能选择角色时，角色下面的部分权限也要用户自己选，这个时候就可能有的角色下面是禁用某些权限的选择，某些权限是靠用户自己去选。（这里的树还用于操作）
为了达到以上的目的，我认为：
1.disable的节点不能通过选择其父节点或本身来改变选中状态。
2.disable的节点可以通过选中的值或其绑定的数据来改变选中状态。
3.（不重要）可以通过js来设置节点是否disable
4.（不重要）禁用父节点后其所有子节点都是禁用状态

**Comment by mcdongWang** [comment]
@Leopoldthecoder 我觉得基本大家对disable的概念达成了共识

目前还有的分歧点:
1. 是否能通过代码set 某个disable节点的值
2. 是否可以通过修改v-model的值 修改某个disable节点的值
3. 是否支持js设置其disabled状态(我认为需要)

**Comment by Dreamacro** [comment]
@mcdongWang @LastHeaven @clarkdo @markselby9

1. 按照 disabled 属性应该只对用户操作进行限制来说, 可以通过代码 set 某个 disable 节点的值
2. 节点的选中值没有暴露在 v-model 当中, 可以使用 `setChecked` 方法改变是否选中

现在初步定下了一个方案:

1. 类似 #5720 的方式, 使用
```javascript
{
    id: 'id',
    label: 'label',
    disabled: true
}
```
来决定是否禁用 checkbox, 同时 disabled  键值会改变 checkbox 是否为 disabled 状态
2. 父元素的选中不影响被 disable 的子元素
```
|- parent
   |- child1 // 此节点为 disabled
   |- child2
```
此时无论 parent 是否选中, 不改变 child1 的值
3. 子元素的选中影响被 disable 的父元素
```
|- parent // 此节点为 disabled
   |- child1
   |- child2
```
若 child1 child2 都选中(无论是否 disabled), 则改变父元素选中状态(即子元素都选中时)

另外目前 #5720 的实现方式会使 `setChecked` 方法失效

**Comment by mcdongWang** [comment]
@Dreamacro 

2: 首先 parent节点不是一个叶子节点 所以 我觉得它的后代中存在disabled节点 并且该节点没有选中 那么parent节点不存在选中状态
3: 我认为 父节点为disabled时 子节点也应该disabled

**Comment by markselby9** [comment]
PR Updated, pls check #5720 .
The setChecked method is now valid to disabled nodes. If the parent node is disabled, but all its active(non-disabled) child nodes are selected, then the disabled parent node's value would also be set to checked. As the screenshot below:

<img width="764" alt="2017-07-19 10 38 09" src="https://user-images.githubusercontent.com/3454734/28348491-db4f033a-6c6f-11e7-9e09-40bdd585b3af.png">

Keep us updated if any further suggestions, thanks!

**Comment by LastHeaven** [comment]
@mcdongWang @markselby9  @clarkdo  @Dreamacro 

2: parent节点主要是用于全选子节点；
disable属性的节点的选中状态不影响父节点的选中状态；
父节点只会改变非disable属性的节点的状态；
当所有非disable属性的节点选中时，父节点应该是全选状态；
当部分非disable属性的节点选中时，父节点应该是部分选择状态；
当非disable属性的节点没有选中时，父节点应该是未选择状态；

3: 父节点为disable时，子节点是否为disable可以由程序员决定而不是控件做出限制。
父节点为disable时，子节点的选中是否会影响父节点的选中状态可以和父节点为非disable时一样。

我觉得合适的选择是父节点为disable时，父节点前面就没有选择框了，这样就不用去考虑父节点的状态变化了。

**Comment by mcdongWang** [comment]
@LastHeaven 

2: 我并不认为 当所有非disable属性的节点选中时，父节点应该是全选状态； 父节点拥有disabled且没被选中的子节点 那么父节点就不是选中状态 只是半选状态  难道disabled子元素 就不是父节点的子元素了么

**Comment by LastHeaven** [comment]
@mcdongWang 
这样的话，如果disable子节点为选中的话，父节点永远都是部分选中状态，不可能变成非选中状态，因为父节点不能改变disable子节点的状态。
那么父节点的选择框失去了其存在的意义。
我所认为的是父节点的选择框是为了方便全选存在的，既然只能控制非disable节点，那么所有非disable节点选中时就是全选状态。

**Comment by mcdongWang** [comment]
@LastHeaven 

父节点的选择框没有失去意义 他的全选按钮控制的是没有被disabled的子元素 但是 他的全选状态 就是 表示他的所有子节点

**Comment by LastHeaven** [comment]
@mcdongWang
在两个disable子元素其中一个选中一个没选中的情况下，父节点永远都是部分选中状态。

**Comment by Dreamacro** [comment]
@markselby9
你目前的 PR 在子元素存在 disabled 并未选中时, 显示的是勾选状态. 按照逻辑的话应该是一个半选中状态.
我这里有个待选方案 #5937

**Comment by mcdongWang** [comment]
@LastHeaven  

对的 就是这个意思

**Comment by LastHeaven** [comment]
@mcdongWang 

```
|- parent
  |- child1 // 此节点为 disabled 选中
  |- child2 // 此节点为 disabled 未选中
  |- child3 // 未选中
  |- child4 // 未选中
```

1.这个时候父节点是什么状态？
2.点击父节点时，子节点的状态是什么样的？父节点的状态？
3.再次点击父节点时，子节点的状态是什么样的？父节点的状态？

**Comment by Dreamacro** [comment]
@LastHeaven

1. 半选中状态
2. child1 child2 不变, 也就是父组件的选中不改变 disabled 的选中, child3 child4 选中, 父组件半选中
3. 同2, child3 child4 未选中, 父组件半选中

具体情况可以看 #5937 , 有什么逻辑上的错误可以指出

**Comment by mcdongWang** [comment]
@LastHeaven 
Dreamacro 跟我的答案一样

**Comment by mcdongWang** [comment]
@Dreamacro  这个问题 会在哪个版本进?

**Comment by Leopoldthecoder** [comment]
@mcdongWang 应该会放在 1.4.0 里。今天发 beta。

**Comment by mcdongWang** [comment]
@Leopoldthecoder 

太棒了 我都准备自己build一个 先用着了 哈哈 那我等 1.4.0吧

**Comment by Leopoldthecoder** [comment]
#5937
