### ISSUE TITLE
[Bug Report] When use that has submenu, I set default-active property, then the hasn't menu been active I menu

### ISSUE THREAD

**Issue by martinko2009** [ElemeFE/element#4770]
### Element UI version
1.3.1

### OS/Browsers version
windows 7 / chrome 56.0.2924.87 / firefox 47.0.2

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/martinko2009/ee6uu6y2/](https://jsfiddle.net/martinko2009/ee6uu6y2/)

### Steps to reproduce
When I set activeIndex to 1，the menu item is active and looks different with others.
When I set activeIndex to 2， the menu item which has submenu is not active and look same as others.

当我设置activeIndex为1的时候，这个菜单选项“处理中心”看上去是蓝色的，是激活状态。

但是当我设置activeIndex为2的时候，菜单项“我的工作台”看上去还是白色的字，没有处于激活状态。

### What is Expected?
I want to make the first class menu item which has submenu look different by setting default-active.

我想将default-active的值，设置为一个一级菜单（包含子菜单）的key值时，这个一级菜单在样式上可以和其他的一级菜单不一样，是处于激活状态的。

### What is actually happening?
I set default-active to the key of the first class menu item which has submenu, but it doesn't look different, not active .

当我将default-active的值设置为一个一级菜单（包含子菜单）的key值时，这个一级菜单样式上看上去没有变化，感觉没有被激活，用户不知道，这个是当前的菜单项。

**Comment by oliviazhangjuan** [comment]
Did you solve the problem?

**Comment by martinko2009** [comment]
no，I didn't solve the problem.

**Comment by sabrinaluo** [comment]
Currently, `submenu` can only be activated when its option get selected. When activated, the font color of submenu is white, but with a blue active bar, and font color of the selected option will be  blue. 

So all you need is to activate the option in submenu.
You can set `activeIndex2: '2-1'`, and it will work. Does this solve your problem?

```
    data() {
      return {
        activeIndex: '1',
        activeIndex2: '2-1'
      };
    },
```

**Comment by martinko2009** [comment]
but I just want to active firstclass menu, not the submenu.

**Comment by Leopoldthecoder** [comment]
> but I just want to active firstclass menu, not the submenu.

There's no way to do this for now.

**Comment by martinko2009** [comment]
Which version the problem will be resolved. Do you have the plan. Thank you.
