### ISSUE TITLE
[Feature Request] Binding a popover trigger to a popover located in parent Vue Component

### ISSUE THREAD

**Issue by andrzejkala** [ElemeFE/element#4771]
### Existing Component
Yes

### Component Name
Popover

### Description
Is there a way to have the `<el-popover>` located in the parent component and the `popover trigger` in a child component?

The idea is to have a list of elements `<elements-list`> that contain a `<el-button>` that trigger showing a popover on `click`. I want to have the `<el-popover>` in the parent component to prevent the creation of 40 popovers on each pagination page and instead have just one in which I can switch up the contents.

**Comment by ar53n** [comment]
this really need feature
