### ISSUE TITLE
[Bug Report] [bug datepicker to set the initial value, validate method console error

### ISSUE THREAD

**Issue by Jim-MK** [ElemeFE/element#4773]
![demo](https://cloud.githubusercontent.com/assets/13947240/25846172/6b1b154a-34e3-11e7-8ace-ec9b936b6f4f.png)

### Element UI version
1.3.1

### OS/Browsers version
window / chrome

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/makai1988/m7ueh059/](https://jsfiddle.net/makai1988/m7ueh059/)

### Steps to reproduce
1.基于官方datepicker示例， 设定日期初始值
2.不选择任何日期，点击验证， NG，并且控制台报错 Uncaught TypeError: e.getTime is not a function
3.选择任意日期，点击验证 OK

### What is Expected?
设定日期初始值

### What is actually happening?
控制台报错

**Comment by wacky6** [comment]
date-picker的数据应该是Date对象

**Comment by Leopoldthecoder** [comment]
@Jim-MK 请参考楼上。

**Comment by Jim-MK** [comment]
thx
