### ISSUE TITLE
[Bug Report] Slow performance on Element Select with large # of items

### ISSUE THREAD

**Issue by dday515** [ElemeFE/element#4778]
### Element UI version
1.3.1

### OS/Browsers version
Windows 10 - All Browswers

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/dday515/pj71jkyw/190/](https://jsfiddle.net/dday515/pj71jkyw/190/)

### Steps to reproduce
Click the "Toggle Element Select". Notice how long it takes for the page to be updated.
Click the "Toggle Standard Select"

Update the test expression of the for loop, changing the 1000 to 100. Re-run the test. 

### What is Expected?
That clicking both the Element Select and the Toggle select would complete in roughly the same amount of time. 

### What is actually happening?
It is taking roughly 3 seconds for the toggle of the element select to process when there are 1000 records in the drop down. 
The Standard Toggle is almost immediate.

(This is obviously a trivial example, but in our application, navigating away from a page that has a select with many items is much slower than pages where they don't exist.

**Comment by Leopoldthecoder** [comment]
I'm aware of this issue. But the current implementation makes it difficult to improve its performance. More info: https://github.com/ElemeFE/element/commit/92b4156aaac573d94bcf35424efbdbb925bae222

**Comment by alanaasmaa** [comment]
I would link the issue to anotherone. #5001

**Comment by jessefalzone** [comment]
This was a major problem for us in 2.3.7 so we had to switch to vue-multiselect.  I understand the current implementation prevents an immediate fix, but will this be addressed in the future?

**Comment by fritx** [comment]
+1 to above, for me, I switched to vue-select and solved as well.

**Comment by dralucindaodonto** [comment]
same here
