### ISSUE TITLE
[Bug Report] form digital type verification logic error, The form type validation logic is incorrect numeric

### ISSUE THREAD

**Issue by totzcc** [ElemeFE/element#4779]
### Element UI version
1.3.1

### OS/Browsers version
Mac OS Chrome 57.0.2987.133 (64-bit) / Safari 10.1 (12603.1.30.0.34)

### Vue version
2.3.3

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/form#shu-zi-lei-xing-yan-zheng](http://element.eleme.io/#/zh-CN/component/form#shu-zi-lei-xing-yan-zheng)

### Steps to reproduce

输入 123abc
input 123abc

### What is Expected?
不通过校验
no pass

### What is actually happening?
通过数字校验
pass

![](http://i1.piimg.com/588926/8afaddf32ca6533c.gif)

**Comment by Leopoldthecoder** [comment]
#4340
