### ISSUE TITLE
url-loader解析字体文件出错

### ISSUE THREAD

**Issue by wangyahui6** [ElemeFE/element#478]
main.js中引入import 'element-ui/lib/theme-default/index.css',webpack打包时出错，提示：
ERROR in ./~/element-ui/lib/theme-default/fonts/element-icons.eot?t=1472440741
Module parse failed: D:\work\abTest_front\node_modules\element-ui\lib\theme-default\fonts\element-icons.eot?t=1472440741 Unexpected character '�' (1:0)

webpack配置如下：
{
			          test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
			          loader: "url",
			          query: {
			            name: '[name].[ext]?[hash]&mimetype=application/font-woff'
			          }
			      },
			      {
			          test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
			          loader: "url",
			          query: {
			            name: '[name].[ext]?[hash]&mimetype=application/font-woff2'
			          }
			      },
			      {
			          test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
			          loader: "url",
			          query: {
			            name: '[name].[ext]?mimetype=application/font-woff2'
			          }
			      },
			      {
			          test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
			          loader: "url",
			          query: {
			            name: '[name].[ext]?mimetype=application/font-woff2'
			          }
			      }

**Comment by QingWei-Li** [comment]
https://github.com/ElementUI/element-starter/blob/master/webpack.config.js#L30-L31
