### ISSUE TITLE
[Feature Request] Radio support in Tree Component

### ISSUE THREAD

**Issue by ChrisShen93** [ElemeFE/element#4781]
### Existing Component
是

### Component Name
Tree

### Description
当前 Tree 组件仅支持CheckBox，希望可以加上对 Radio 的支持，覆盖更多的业务场景
<br />
Currently, the Tree Component only support show checkbox, I hope that you can add radio support to this component, which may cover more scenarios.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
