### ISSUE TITLE
[Bug Report] filters attribute problem [1 if there is a condition without data, all other conditions are invalid, the 2 elastic layer position is not fixed, will drift]

### ISSUE THREAD

**Issue by zctya** [ElemeFE/element#4785]
### Element UI version
1.3.1

### OS/Browsers version
win7 x64

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/zctya/pL0cwd3k/1/](https://jsfiddle.net/zctya/pL0cwd3k/1/)

### Steps to reproduce
table的filters属性问题【1.如果有一个条件无数据，其他条件全部无效，2.弹层位置不固定，会漂移】
1.参照  Reproduction Link，点击过滤条件“李大虎”，table中会显示“暂无数据”，之后，点击“全部”或者“王小虎”，同样显示“暂无数据”，其实应该显示一条数据
2.对有过滤条件的列头处点击，弹层的位置总是在变，希望可以设置固定位置，通过绑定属性啥的
3.另外这个过滤条件的弹层能指定  click或者mouseover之类事件，而不是固定的click操作弹层
### What is Expected?
一个条件无数据，其他条件有数据，应该显示其数据
有过滤条件的弹层，希望能1.固定位置，2.能通过绑定属性动态修改其位置

### What is actually happening?
yes

**Comment by yuanchanglong** [comment]
![qq 20170511150521](https://cloud.githubusercontent.com/assets/15042364/25936663/4c88ec78-365b-11e7-9157-e6bae40b4405.png)

**Comment by yuanchanglong** [comment]
1、筛选框与根组件同级，位置通过JS控制，当表头宽度按照百分比走的时候，定位会出现问题；

2、表头th在Hover时会有高亮效果，由于宽度按照百分比走，表头高亮宽度会比筛选框宽度不一致；

**Comment by yuanchanglong** [comment]
3、期望实现鼠标悬停筛选列的时候自动弹出筛选项列表，并且选中某个筛选项的时候筛选列头能显示筛选项名称：
![image](https://cloud.githubusercontent.com/assets/15042364/25978795/24175d6e-36f7-11e7-9f04-e27830011bc3.png)

**Comment by Leopoldthecoder** [comment]
Please do not change `tableData` in filter method.
