### ISSUE TITLE
[Bug Report] upload组件 list-type="picture-card"  multiple  选择多张图片上传，有一定机率图片自动被删除

### ISSUE THREAD

**Issue by plilion** [ElemeFE/element#4787]
### Element UI version
1.3.1

### OS/Browsers version
chrome 56.0.2924.87 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/plilion/9q8k5kcp/](https://jsfiddle.net/plilion/9q8k5kcp/)

### Steps to reproduce
不停的同时上传多张图片，有一定机率图片自动被删除，选择相同的图片 删除的机率更大

### What is Expected?
上传的图片不被自动清除

### What is actually happening?
选择多张图片同时上传

**Comment by Leopoldthecoder** [comment]
It's not deleted. It's just that upload has failed.

**Comment by forest-green** [comment]
上传多张图片，如果其中一张上传成功，则其他正在上传的图片被隐藏，从控制台看，能够看到这几张图片正在上传中，但是不会及时显示出来，必须要通过刷新页面，上传成功的图片才能全部展示出来
