### ISSUE TITLE
[Bug Report] return a useless DatePicker result

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4788]
### Element UI version
1.3.1

### OS/Browsers version
all

### Vue version
2.3.3

### Reproduction Link
https://jsfiddle.net/x83fuoc2/

### Steps to reproduce
1.click on the date-picker,and select a date
2.we can get a string in the input
3.the content of the input is useless

### What is Expected?
it should be a Date value or a unix date string

### What is actually happening?
useless string for coder like this:
`Tue May 16 2017 00:00:00 GMT+0800 (中国标准时间)`

**Comment by Leopoldthecoder** [comment]
#4689

**Comment by zzzgit** [comment]
这个翻译机器人整天乱翻译
