### ISSUE TITLE
[Feature Request] Text in message pop-ups blurry

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#4789]
### Existing Component
Yes

### Component Name
message

### Description
The text in the message pop-up is... blurry. I believe it has to do with the CSS property `letter-spacing`. When staring at text inside `message` it can be like I am seeing double vision.

It's a small issue, but a bothersome one. Making the text fuzzy/blurry adds nothing beneficial to `message` and only makes the user experience slightly worse.

**Comment by Leopoldthecoder** [comment]
Message itself does not have `letter-spacing` property. See if you have some external styles affecting it.

**Comment by web-surfer** [comment]
`letter-spacing` was just a guess. I've set `letter-spacing` to `0` when targeting `message`, and it sometimes works, and sometimes it doesn't.

But something is making the text inside `message` blurry.

**Comment by Leopoldthecoder** [comment]
On a Mac or Windows machine?

**Comment by web-surfer** [comment]
Windows 7 machine.

Here is an example:
http://imgur.com/a/tyrah

It will sometimes look like the top example (blurry), and sometimes it looks like the bottom example.

Again, this is on the latest Chrome. If you view `message` in Firefox, it _seems_ to be okay.

**Comment by Leopoldthecoder** [comment]
What is your screen resolution?

**Comment by web-surfer** [comment]
Screen resolution is 1920x1080

**Comment by 18115512409** [comment]
在消息层宽度为奇数的时候，就会有这种模糊的问题，还不知道怎么解决
