### ISSUE TITLE
[Bug Report] Input Change event with EL-INPUT element

### ISSUE THREAD

**Issue by BlueBird67** [ElemeFE/element#4794]
### Element UI version
1.3.2

### OS/Browsers version
Windows 10

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/Blbird/bhaLv96q/4/](https://jsfiddle.net/Blbird/bhaLv96q/4/)

### Steps to reproduce
On Native Vuejs input, the method format is forbidding "a..z" chars, allowing only "A..Z" chars. IT is working as expected.

On EL-INPUT, from console logs, method are working well too, but characters are still allowed in the EL-INPUT. 

### What is Expected?
Same behaviour for native input as for EL-INPUT : blocking chars.

### What is actually happening?
Forbidden chars on EL-INPUT are still apearing in the form, It seems like the "this.form.name = str" is not working on EL-INPUT DOM.

**Comment by Leopoldthecoder** [comment]
Wrap it in the next tick: https://jsfiddle.net/bhaLv96q/5/

It's actually not a bug: https://jsfiddle.net/ao4uyadz/
