### ISSUE TITLE
[Bug Report] Slider Drag Does Work for Touch/Mobile

### ISSUE THREAD

**Issue by webberwang** [ElemeFE/element#4795]
### Element UI version
1.3.2

### OS/Browsers version
Safari / CHrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/192/](https://jsfiddle.net/pj71jkyw/192/)

### Steps to reproduce
Any slider component won't work with mobile, need to test using mobile emulator for browser.

User's intuition when they see a slider is to drag it, but it confuses the user because the user doesn't work.

Should this be titled feature request?

### What is Expected?
Slider should move when dragging with touch.

### What is actually happening?
Slider doesn't move when dragging with touch.

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. It's not suitable for mobile devices.

**Comment by KayvanMazaheri** [comment]
@Leopoldthecoder Element's grid layout supports tablets and mobile devices, so why shouldn't the components support them as well?  
If Element is designed for desktop, why it has `xs` and `sm` attributes for `<el-col>` component?

**Comment by chz** [comment]
Please fix this issue
