### ISSUE TITLE
[Feature Request] [functional requirements] Loading increased timeout and reload

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#4796]
### Existing Component
是

### Component Name
Loading

### Description
大多数情况下， loading 是正常的， 但不排除遇到 网络不好的情况， 这时候建议新增一个 timeout 事件，还有 timeout 之后是否 显示 reload 组件的判断，  timeout 返回一个 事件， reload 出 2个按钮，一个是放弃， 一个是 重载， 分别触发对应事件。 我觉得 配合 axios 的 cancelToken 之类的非常完美。

**Comment by Leopoldthecoder** [comment]
无计划。
