### ISSUE TITLE
[Feature Request] el-popover 添加 min-width 属性 | el-popover add "min-width" props 

### ISSUE THREAD

**Issue by sqchenxiyuan** [ElemeFE/element#4797]
### Existing Component
是

### Component Name
el-popover

### Description
目前 el-popover 只支持 对 `width` 设置

elementui 样式设置 `min-width` 为 150px

虽然可以全局修改 `min-width` 但是感觉不是很灵活

可以加一个这个新特性，来控制`min-width`吗

----

now the el-popover only suport  change `width`

but  elementui style defaut set the `min-width:150px`

although can set the global style to change the min-width,but not controlled

can add a new feature to change the min-width?

**Comment by sqchenxiyuan** [comment]
虽然可以使用添加class的方式

但是感觉有点绕   支持了width 来方便开发   也希望  能增加一个 min-width

---
although can resovle by set popper-class

but i feel trouble just set a min-width    

support for the width to facilitate the development of min-width also hope to add a

**Comment by Leopoldthecoder** [comment]
We have no plan to implement this.

As you have noticed, this is what `popper-class` is for. `min-width` is not the only commonly used CSS property on popovers. If we support `min-width`, there is no reason to ignore other properties. But if we support all of them, popover will be too verbose.

**Comment by BinarySky10** [comment]
> We have no plan to implement this.
> 
> As you have noticed, this is what `popper-class` is for. `min-width` is not the only commonly used CSS property on popovers. If we support `min-width`, there is no reason to ignore other properties. But if we support all of them, popover will be too verbose.

pride
