### ISSUE TITLE
win10 npm run dist失败

### ISSUE THREAD

**Issue by pixcai** [ElemeFE/element#480]
node.js version: v4.4.6
npm version: 2.15.5

把仓库clone下来后，执行cnpm install装好所有依赖，运行npm run dist无错误，但是运行出错，因为编译后产生了with语法：

BabelLoaderError: SyntaxError: C:/Users/Administrator/Desktop/Project/element-starter/element/lib/element-ui.common.js: 'with' in strict mode (1000:36)

   998 | /***/ function(module, exports) {
   999 | 
> 1000 | 	module.exports={render:function (){with(this) {
       | 	                                   ^
  1001 | 	  return _h('ul', {
  1002 | 	    staticClass: "el-pager",
  1003 | 	    on: {

![image](https://cloud.githubusercontent.com/assets/11440779/19467162/3a5306ac-9542-11e6-97c4-e5beef620b98.png)

**Comment by QingWei-Li** [comment]
https://github.com/ElementUI/element-starter/blob/master/webpack.config.js#L23

**Comment by pixcai** [comment]
不是element-starter中的问题，element仓库是独立编译的，放在element-starter目录下只是为了看效果。

**Comment by pixcai** [comment]
单独编译element仓库时产生的element-ui.common.js中就已经有with语句了

**Comment by Leopoldthecoder** [comment]
楼上的意思是不要让你的 babel 处理 element-ui.common.js

**Comment by Leopoldthecoder** [comment]
楼上的意思是不要让你的 babel 处理 element-ui.common.js

**Comment by QingWei-Li** [comment]
`with` 是 vue-template-compiler 编译出来的，同时带有 'use strict'（这个是 babel 编译后带的）。所以在用 babel-loader 时不应该让 babel 处理到 element-ui

**Comment by pixcai** [comment]
仓库的编译配置中不是配置好的吗？仓库克隆下来后还要自己配置一遍？

**Comment by pixcai** [comment]
那应该怎么改呢？element这个仓库没有webpack.config.js啊？

**Comment by QingWei-Li** [comment]
你直接把编译后的 element-ui 拷贝到项目的 element 目录下，`exclude: /node_modules/` 这配置肯定无效的，你应该用 `npm install path/your/element-ui` 或者 `npm link path/your/element-ui` 的方式，而不是拷贝一个目录过去。
或者你也可以自己配置 `exclude`，建议熟悉下 webpack loader 的配置

**Comment by pixcai** [comment]
呃，可能我没说明白。上面说的排除node_modules、配置webpack.config.js什么的我没弄明白你们在说什么？在说项目？但是我没建项目，我就克隆仓库然后编译而已。如下：

1、git clone https://github.com/ElemeFE/element.git
2、cd element
3、npm install
4、npm run dist
5、vim lib/element-ui.common.js
在第1000行处得到：
```js
module.exports={render:function (){with(this) {
	 return _h('ul', {
	    staticClass: "el-pager",
	    on: {
	      "click": onPagerClick
	    }
```

**Comment by QingWei-Li** [comment]
1. with 是 vue-loader 编译后的结果 https://www.zhihu.com/question/49929356
2. 我看你的报错是在 element-starter 里引用了 `element` 这个目录，目录里是编译后的 element-ui 项目，由于编译后的结果里同时存在 `use strict` 和 `with` 因此不能让 babel-loader 处理到，因为 with 不能再 strict mode 执行。要么自己更改  element-starter 的 webpack 配置，要么用上面的 link 或者 install 安装 element 到 element-starter

**Comment by pixcai** [comment]
额，忘掉element-starter吧，我后悔不该把element-starter放在问题中。
**这个问题跟element-starter没有任何关系。**

我上面回答的1、2、3、4、5中，你可以看到我**只是编译element**而已，然后**得到的element-ui.common.js就已经有with了**，我不知道错在了哪一步。如果能远程演示就不用这么麻烦了。

**Comment by QingWei-Li** [comment]
如果只是编译 element 的话，最后结果肯定有 with 啊，知乎上面 yyx 不是回答了么，这就是 vue-template-compiler 的实现逻辑啊

**Comment by Leopoldthecoder** [comment]
「得到的element-ui.common.js就已经有with了」这是对的，只要用的是 Vue 2.0，编译出来肯定有 `with`。所以你在刚开始说「执行npm run dist无错误，但是运行出错」，这里的「运行」是用了什么命令？

**Comment by pixcai** [comment]
npm run dev

**Comment by pixcai** [comment]
也就是说，在element这个仓库执行npm run dist得到的element-ui.common.js其实是不能直接执行的？

**Comment by Leopoldthecoder** [comment]
可以执行，只是不要让 babel 处理它。

如果你只是想 npm run dist 一下 element，那么编译出的代码有 `with` 是意料中的。

如果你的目的是「放在element-starter目录下只是为了看效果」，那么需要在你的 element-starter 项目下的 webpack 里排除掉 element-ui.common.js，具体方法上面已经给出。

**Comment by pixcai** [comment]
嗯，懂了
