### ISSUE TITLE
[Bug Report] el-form-item validation rules doesn't work as  expected

### ISSUE THREAD

**Issue by jyjunyz** [ElemeFE/element#4801]
### Element UI version
1.3.1

### OS/Browsers version
macOS 10.12.2   /  chrome 版本 57.0.2987.133 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/jyjunyz/pj71jkyw/195/](https://jsfiddle.net/jyjunyz/pj71jkyw/195/)

### Steps to reproduce
when blur input component, get the error message, 

### What is Expected?
get the input value correctly

### What is actually happening?
the input validation can't get value when input change

**Comment by baiyaaaaa** [comment]
Please use `:model` but not `v-model`, it's an usage bug
![image](https://cloud.githubusercontent.com/assets/3655403/26622169/16373dfc-461c-11e7-90b8-50c03ebdac83.png)

**Comment by jyjunyz** [comment]
@baiyaaaaa 
`v-model ` is  used in version 1.3.1，I know it has changed in  1.3.4, however it's not the reason, I have modified it into `:model` and it also doesn't work

**Comment by leawi** [comment]
Has this been resolved? 
I'm still experiencing it with element-ui@2.4.11 and :model in vue@2.5.22
