### ISSUE TITLE
[Bug Report] dynamic change form item

### ISSUE THREAD

**Issue by yamateH-ch** [ElemeFE/element#4802]
### Element UI version
1.3.2

### OS/Browsers version
win10/chorme

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
点击编辑，编辑一个域名成功后数据没有改变，去掉动态增减表单项的prop属性就可以修改，数据也会变

### What is Expected?
动态增减表单项的prop属性不影响到数据修改

### What is actually happening?
动态增减表单项的prop属性不影响到数据修改

**Comment by Leopoldthecoder** [comment]
Issues with irrelevant demos will be closed directly.
