### ISSUE TITLE
Failed to resolve directive: popover

### ISSUE THREAD

**Issue by ruizhou8888** [ElemeFE/element#4804]
更新版本后 用el-popover组件控制台报错。未更新之前是好的

**Comment by fritx** [comment]
FYI, the following usage works:
(element-ui v1.3.7)

```vue
<el-popover
  placement="left"
  trigger="hover">
  <h1>Hello</h1>
  <div slot="reference"><some-btn></some-btn></div>
</el-popover>
```

**Comment by vivianink** [comment]
更新到2.0版本后遇到了同样的问题，控制台也报了这样的错误:"Failed to resolve directive: popover"。麻烦看一下是什么原因吧~

**Comment by FAKER-A** [comment]
我也遇到了 这样的问题  2.0.3 不知道上面的大兄弟解决了没有

**Comment by nanhapy** [comment]
Came across the same problem in 2.0.4. I put the below codes after `import Element from 'element-ui';` in `index.js`.
```
import directive from 'element-ui/packages/popover/src/directive';
Vue.directive('popover', directive);
```
Then works fine. 
BTW, the @element-bot is not very user-friendly.

**Comment by ray089** [comment]
遇见了同样的报错，用 npm i element-ui -S 解决了

**Comment by liukun** [comment]
Thank @nanhapy ! A simpler way works for me on 2.2:

    import 'element-ui/packages/popover'

**Comment by nimojs** [comment]
@nanhapy  

```js
import directive from 'element-ui/packages/popover/src/directive';
Vue.directive('popover', directive);
```

这有个坑需要注意，一般我们都会 webpack 配置 babel 不编译 node_modules 中的文件

`element-ui/packages/popover/src/directive` 里面有 const 不会被babel编译 然后不支持 const 的浏览器报错了
