### ISSUE TITLE
[Bug Report] selected item cann't show when using el-select

### ISSUE THREAD

**Issue by Simonalia** [ElemeFE/element#4805]
### Element UI version
1.3.2

### OS/Browsers version
Windows 10, Chrome 58.0

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Import el-select and el-option alone,
Click an option

### What is Expected?
selected item show up in the select component

### What is actually happening?
 selected item cann't show.

**Comment by Leopoldthecoder** [comment]
It should work if the versions (Vue and Element) you submitted are correct.
