### ISSUE TITLE
ElOption在数据变更后显示不正确

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#481]
### ElementUI version
1.0.0-rc.7

### Vue version
2.0.0-rc.7

### Reproduction Link
https://jsfiddle.net/erguotou525/kpr7e2az/1/

### Steps to reproduce
点击按钮，可以看到被`splice`的数据仍然显示下下拉框中，但数据是正确的

**Comment by dyw934854565** [comment]
[#421](https://github.com/ElemeFE/element/issues/421)
里面有个回答有用

**Comment by erguotou520** [comment]
OK，是我没注意
