### ISSUE TITLE
[Upload] 文件列表显示流程优化

### ISSUE THREAD

**Issue by liz282907** [ElemeFE/element#482]
背景：组件里面默认文件拖拽上去的时候对fileList遍历发送请求，在每一个file，在执行post函数时才添加到uploadList数组中，而这个时候uploadList组件才会显示。

现在的场景是，点击上传按钮，将文件及其他form信息同时提交。但是由于上述原因，使得在上传完成后才会显示文件列表，而不是先显示列表，然后点击上传再success提示。多文件时不太友好...

因此想问下，可以在upload函数里面将push分离出来不，先更新uploadList列表，然后再遍历post. thx :)

![](http://p1.bqimg.com/567571/4c13966ee6d00e9e.png)

**Comment by reverland** [comment]
这个设计现在是什么状态？

**Comment by baiyaaaaa** [comment]
1.2 将会支持自动上传
