### ISSUE TITLE
[Bug Report] element-ui $msgbox and $alert content bug

### ISSUE THREAD

**Issue by nichengaxiang** [ElemeFE/element#4823]
### Element UI version
1.3.2

### OS/Browsers version
windows 7 / chrome 58.0.3029.96

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/nichengaxiang/6v97bju6/3/](https://jsfiddle.net/nichengaxiang/6v97bju6/3/)

### Steps to reproduce
打开链接即可看到问题

### What is Expected?
正常显示第二个弹框的内容

### What is actually happening?
显示的仍是第一个弹框的内容

**Comment by Leopoldthecoder** [comment]
Fixed [here](https://github.com/ElemeFE/element/pull/4851/files#diff-f67e99c8c1de20ab1f50941f39f8c47bR105)
