### ISSUE TITLE
[Bug Report] pagination paging component

### ISSUE THREAD

**Issue by yehowey** [ElemeFE/element#4827]
### Element UI version
1.3.2

### OS/Browsers version
Google Chrome 58.0.3029.81

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
引入pagination分页组件的时候

### What is Expected?
手动输入页码jumper之后，然后点击prev, pager,或next之后，页码变动，jumper值也跟着变动

### What is actually happening?
手动输入页码jumper之后，然后点击prev, pager,或next之后，页码变动，但是jumper值不变，导致体验上的一种误解

**Comment by zhifeichuan** [comment]
我也遇到了同样的问题，可暂时写个指令解决此问题
`export default {
  install(Vue, option) {
    Vue.directive('initjump', {
      update: function (el, binding) {
        if (binding.value) {
          el.lastChild.children[0].value = binding.value
        }
      }
    })
  }
}
`

**Comment by zhifeichuan** [comment]
使用部分
`<el-pagination
                v-initjump="pageIndex"
                :page-sizes="pagination.pageSizes"
                :page-size="pagination.pageSize"
                :current-page="pageIndex"
                layout="total, sizes, prev, pager, next, jumper"
                :total="pagination.totalNum"
                @current-change="doPageByNum"
                @size-change="doPageBySize"
                >`

**Comment by kfeng0806** [comment]
我也遇到了 1.3.6版本中 希望可以修复

**Comment by Leopoldthecoder** [comment]
Fixed in #5377
