### ISSUE TITLE
The [Bug Report] Cascader cascade selector search function is invalid

### ISSUE THREAD

**Issue by lanmaomm** [ElemeFE/element#4836]
### Element UI version
1.3.2

### OS/Browsers version
chrome 版本 57.0.2987.133

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
在element-ui官方文档最新版（1.3.2）的Cascader 级联选择器用法示例里，按照提示搜索“指南”。

### What is Expected?
选择器能正确的关联到搜索项

### What is actually happening?
搜索行为并无任何反馈

**Comment by Leopoldthecoder** [comment]
Fixed in #4812
