### ISSUE TITLE
[Bug Report] upload automatically upload mode, allowing multiple upload before-upload hook returns false or uploaded successfully

### ISSUE THREAD

**Issue by WLyKan** [ElemeFE/element#4844]
### Element UI version
1.3.1

### OS/Browsers version
5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

### Vue version
2.3.3

### Reproduction Link
[http://jsfiddle.net/p41q54s9/](http://jsfiddle.net/p41q54s9/)

### Steps to reproduce
已经限制了4张，然后不一张一张上传，直接一次上传5张，然后再继续上传

### What is Expected?
应该阻止上传

### What is actually happening?
还可以继续上传

**Comment by WLyKan** [comment]
好像是on-success没有触发，或者说触发了一次sucess

**Comment by baiyaaaaa** [comment]
I can not clear what you want to limit. Your demo is about limiting the size of upload-file insteadof the size. Please checkout your problem.
