### ISSUE TITLE
[Bug Report] Inconsistent hight for InputNumber

### ISSUE THREAD

**Issue by KingMario** [ElemeFE/element#4845]
### Element UI version
1.3.2

### OS/Browsers version
Mac / Chrome latest

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/L7dums73/1/](https://jsfiddle.net/L7dums73/1/)

### Steps to reproduce
run the fiddle

### What is Expected?
same height for all fields

### What is actually happening?
The height for the InputNumber is not as high

**Comment by vipplus** [comment]
https://jsfiddle.net/L7dums73/2/

**Comment by Leopoldthecoder** [comment]
Fixed in #5127. Will be available in the next release.
