### ISSUE TITLE
Loading 加载

### ISSUE THREAD

**Issue by eastian** [ElemeFE/element#4848]
¶ Loading 加载组件中Options中的customClass设置class怎么没有效果？【elment-ui 1.31】

**Comment by SuperAL** [comment]
具体见[文档](http://element.eleme.io/#/zh-CN/component/loading)：
customClass 不能用于指令调用loading的情况，可以用于以服务的方式调用。

---
Loading 还可以以服务的方式调用。引入 Loading 服务：

`import { Loading } from 'element-ui';`

在需要调用时：

`Loading.service(options);`

其中 options 参数为 Loading 的配置项，具体见下表。LoadingService 会返回一个 Loading 实例，可通过调用该实例的 close 方法来关闭它：

```
let loadingInstance = Loading.service(options);
loadingInstance.close();
```
