### ISSUE TITLE
[Feature, Request], about, the, method, setActiveItem, of, el-carousel

### ISSUE THREAD

**Issue by myronBob** [ElemeFE/element#4849]
### Existing Component
是

### Component Name
 el-carousel

### Description
请教一下，setActiveItem 这个方法怎么调用。
我直接根据id获取el-carousel组件，然后调用setActiveItem 这个方法，提示方法不存在

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by evolutionjay** [comment]
同问，请给 demo

**Comment by myronBob** [comment]
已解决，通过延时100多毫秒再调用函数解决。在vue的updated函数里，虽然dom元素已经生成，但页面未完成动画渲染，所以调用setActiveItem函数会失效




发自网易邮箱大师
在2017年05月17日 14:59，Jay 写道：

同问，请给 demo

**Comment by evolutionjay** [comment]
不是吧……用setTimeout这种写法太不负责了吧

**Comment by myronBob** [comment]
我没想到其他办法，要不你上gitter那个聊天室上看一下我给的demo？看看有没有其他方法可以解决的




发自网易邮箱大师
在2017年05月18日 08:51，Jay 写道：

不是吧……用setTimeout这种写法太不负责了吧
