### ISSUE TITLE
table里的data数据会转义，防止XSS，那怎样在table里加button按钮

### ISSUE THREAD

**Issue by dyw934854565** [ElemeFE/element#485]
### What is Expected?
当data里设置的值为'<span>text</span>'，不会解析HTML，而是原样输出，但是我想加一些按钮怎么办
[栗子](http://codepen.io/dyw/pen/yaRJwA?editors=1111)

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/169
