### ISSUE TITLE
[Bug Report] After the  Select component V-model binding, the text box shows the value of the bound data, not the value of the label

### ISSUE THREAD

**Issue by panhezeng** [ElemeFE/element#4854]
### Element UI version
1.3.2

### OS/Browsers version
All

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/panhezeng/29ccndp3/2/](https://jsfiddle.net/panhezeng/29ccndp3/2/)

### Steps to reproduce
在编辑页，有默认的选项值，绑定了默认选项值，文本框没有显示对应的label值，而是显示绑定值。如果用你们的Select组件的基础示例没有问题，因为是option是根据数据生成的，但是如果option是直接在模板上写好的，就不行了，比如你们form表单里面用到了select组件的示例，而实际开发中，多数都是直接在模板上写的，不会专门为每个select去声明个data

### What is Expected?
绑定默认值后，文本框应该显示对应的label值

### What is actually happening?
绑定默认值后，文本框应该显示的是绑定值

**Comment by Leopoldthecoder** [comment]
Please read the Vue docs to get a clearer understanding of data binding: https://jsfiddle.net/29ccndp3/3/
