### ISSUE TITLE
[Bug, Report], el-cascader, s, method,'active-item-change', not, run, at, times, some,...

### ISSUE THREAD

**Issue by wkyhy205104** [ElemeFE/element#4860]
### Element UI version
1.3.3

### OS/Browsers version
chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
like title:
use el-cascader and the datas from async, when at the end level,and the item has no props 'children:[]' (if i add this prop, it where enter next level,it is Inconsistent logic),it dont exe the active-item-change methods;
This should belong to bug?

如题：
使用联级选择器的时候有问题，选择器的数据来自网络请求，当到达最后一级的时候，我没有给它的那一项加children:[]属性，结果选中的时候不执行active-item-change方法,这个应该属于Bug 吧

### What is Expected?
when at the last level, click it and exe the method 'active-item-change'

### What is actually happening?
like title:
use el-cascader and the datas from async, when at the end level,and the item has no props 'children:[]' (if i add this prop, it where enter next level,it is Inconsistent logic),it dont exe the active-item-change methods;
This should belong to bug?

如题：
使用联级选择器的时候有问题，选择器的数据来自网络请求，当到达最后一级的时候，我没有给它的那一项加children:[]属性，结果选中的时候不执行active-item-change方法,这个应该属于Bug 吧

**Comment by Leopoldthecoder** [comment]
@wkyhy205104 See the above comment. Your demo is blank.

**Comment by wkyhy205104** [comment]
you can use official demo and click "江苏"->"南京", click the '南京' has not response. sorry my English is bad

**Comment by wkyhy205104** [comment]
@Leopoldthecoder @element-bot you can use official demo and click "江苏"->"南京", click the '南京' has not response. sorry my English is bad

**Comment by Leopoldthecoder** [comment]
![image](https://cloud.githubusercontent.com/assets/10095631/26045141/4849cba0-397b-11e7-97ca-d66d53430fbc.png)

`active-item-change` only triggers when you click a non-leaf option.

**Comment by wkyhy205104** [comment]
@Leopoldthecoder but the data from interface,if set the props 'true',It seems that the corresponding method cannot be implemented

**Comment by Leopoldthecoder** [comment]
Set what prop to `true`? A demo could help.

**Comment by wkyhy205104** [comment]
https://jsfiddle.net/1t3uda2t/   
i add prop :change-on-select="true" and click ,has no response

**Comment by wkyhy205104** [comment]
@Leopoldthecoder 
https://jsfiddle.net/1t3uda2t/
i add prop :change-on-select="true" and click ,has no response

**Comment by Leopoldthecoder** [comment]
When `change-on-select` is true, options at all levels can be selected, making them all leaf options, so `active-item-change` will not be triggered. In this case, use `change` instead: https://jsfiddle.net/1t3uda2t/1/

**Comment by wkyhy205104** [comment]
@Leopoldthecoder ok,thanks very much
