### ISSUE TITLE
When the [Bug Report] select component implements focus, it does not expand. Interactions like native select elements?

### ISSUE THREAD

**Issue by ac88** [ElemeFE/element#4863]
### Element UI version
1.3.3

### OS/Browsers version
win10 Chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/209/](https://jsfiddle.net/pj71jkyw/209/)

### Steps to reproduce
从input按下键盘tab，让el-select不展开，点击的时候展开关闭

### What is Expected?
提供一个属性设置 ，focus不展开

### What is actually happening?
自己给el-select下的el-input 绑定click事件来触发el-select 的toggleMenu
需要关闭el-select的handleMouseDown
elInput.$off('mousedown.native')
elInput.$el.removeEventListener('mousedown',vm.handleMouseDown)

2种关闭方式都失效
最后选择 elSelect.handleMouseDown = () => {}

**Comment by Leopoldthecoder** [comment]
First of all, this is not a bug. Using internal props / methods to customize component interactions is not recommended, for the DOM structure and props / methods names are subject to change in the future.

> 提供一个属性设置 ，focus不展开
This will not be supported.
