### ISSUE TITLE
[Bug, Report], Only, first, column, displayed, using, grouping,, table, fixed, head

### ISSUE THREAD

**Issue by sourbell** [ElemeFE/element#4864]
### Element UI version
1.3.3

### OS/Browsers version
Sierra 10.12.4/Google Chrome 58.0.3029.81

### Vue version
2.3.3

### Reproduction Link
[https://codepen.io/sourbell/pen/gWKgzM](https://codepen.io/sourbell/pen/gWKgzM)

### Steps to reproduce
When using Grouping table head along with **multiple** fixed columns, only first column will display.

固定列及表头与多级表头同时使用时，如果固定列为**多个**，则只有第一列的值会显示，后面的固定列均显示空白。

### What is Expected?
Display all fixed header & columns.

### What is actually happening?
Only display first fixed column.

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0: https://codepen.io/leopoldthecoder/pen/GMLEdv
