### ISSUE TITLE
The [Bug Report] utils/vue-popover watch attribute causes Vue warn

### ISSUE THREAD

**Issue by andypinet** [ElemeFE/element#4865]
### Element UI version
1.3.3

### OS/Browsers version
mac os 

### Vue version
2.3.3

### Reproduction Link
[https://codepen.io/anon/pen/BRVWNm](https://codepen.io/anon/pen/BRVWNm)

### Steps to reproduce
1. 使用tootlip 设置为手动模式
2. 设置组件value为true

### What is Expected?
期待使用compute prop替换watch属性

### What is actually happening?
使用不推荐的watch 属性

**Comment by Leopoldthecoder** [comment]
I don't quite get what you mean. Please elaborate your problem.

**Comment by andypinet** [comment]
sorry 
![](https://www.zhilizhili.com/bug.png)

**Comment by Leopoldthecoder** [comment]
https://codepen.io/leopoldthecoder/pen/JNZroN
