### ISSUE TITLE
Use JS to change the value in el-input, how to validate the dynamic value in el-input?

### ISSUE THREAD

**Issue by DoryDuan** [ElemeFE/element#4867]
### Element UI version
1.3.3

### OS/Browsers version
google

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/axzL7v19/5/](https://jsfiddle.net/axzL7v19/5/)

### Steps to reproduce
step1:click the button "立即创建"
step2:focus on "菜单"
step3:select "菜单"
The address was filled in the input.But the error infomation didn't disappear.

### What is Expected?
After the address filled in the input, the error infomation should disappear.

### What is actually happening?
 The error infomation didn't disappear.How to make it disappear?

**Comment by DoryDuan** [comment]
Reproduction Link: https://jsfiddle.net/axzL7v19/6/

**Comment by Leopoldthecoder** [comment]
In the validation rule for `address`, change `trigger` to 'change': https://jsfiddle.net/axzL7v19/7/

**Comment by DoryDuan** [comment]
https://jsfiddle.net/axzL7v19/8/
My demand is from other page jump to the form page，and I need to clear the information of the form. So
 I called this.resetForm('ruleForm') in mounted. 
"Step1:click the button" created immediately"
"Step2:focus on" menu"
"Step3:select" menu"
The error information didn't disappear.
