### ISSUE TITLE
The [Bug Report] rendering <el-select>'s <el-option> with V-for causes the component <el-form>'s form validation to always be in error state after it is triggered

### ISSUE THREAD

**Issue by NagiaME** [ElemeFE/element#4872]
### Element UI version
1.3.2

### OS/Browsers version
windows/Chrome&Edge

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/tpum8x04/](https://jsfiddle.net/tpum8x04/)

### Steps to reproduce
<el-form :rule><el-form-item><el-select><el-option v-for=...>

### What is Expected?
用v-for渲染的会导致该组件的表单验证触发后永远处于错误状态

### What is actually happening?
修正v-for渲染的el-select表单验证

**Comment by Leopoldthecoder** [comment]
You should declare its type: https://jsfiddle.net/tpum8x04/2/
