### ISSUE TITLE
[Bug Report] form validate: after called this.resetForm('ruleForm') in mounted, the error information didn't disappear.

### ISSUE THREAD

**Issue by DoryDuan** [ElemeFE/element#4876]
### Element UI version
1.3.3

### OS/Browsers version
Google

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/axzL7v19/8/](https://jsfiddle.net/axzL7v19/8/)

### Steps to reproduce
My demand is from other page jump to the form page，and I need to clear the information of the form. So
I called this.resetForm('ruleForm') in mounted.
"Step1:click the button" created immediately"
"Step2:focus on" menu"
"Step3:select" menu"
The error information didn't disappear.

### What is Expected?
After filled the information in address, the error information should be disappeared.

### What is actually happening?
The error information didn't disappear.

**Comment by alanaasmaa** [comment]
Same here, im using ajax to get Validation rules and after i modified the data vue triggers a change so, all my fields get red. Then i call reset on next tick but errors wont dissapear on input.

**Comment by Leopoldthecoder** [comment]
@baiyaaaaa dalao take a look? Minimal repro: https://jsfiddle.net/axzL7v19/13/

**Comment by baiyaaaaa** [comment]
Actually, It's not a bug, If you set value manually,  you should reset the field munually too.

**Comment by baiyaaaaa** [comment]
It's because the autocomplete model value state4 not nested in the `ruleForm` model. It's not a bug. `resetForm()` Only reset the value in the `model` prop
