### ISSUE TITLE
[Bug Report] Active style issues for tabs components

### ISSUE THREAD

**Issue by qianqWang** [ElemeFE/element#4877]
### Element UI version
1.3.3

### OS/Browsers version
macOS Sierra 10.12.4

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/deocg9f8/](https://jsfiddle.net/deocg9f8/)

### Steps to reproduce
When you click the dropDown menu, and selecting the option, you look the tabs component's active style is not in the correct position

### What is Expected?
the tabs component's active style in the correct position

### What is actually happening?
the tabs component's active style not in the correct position

**Comment by Leopoldthecoder** [comment]
You can avoid this by calling `forceUpdate` in the next tick: https://jsfiddle.net/deocg9f8/2/
