### ISSUE TITLE
The [Feature Request] tabs component suggests opening the right mouse button event

### ISSUE THREAD

**Issue by Esa-i** [ElemeFE/element#4879]
### Existing Component
是

### Component Name
Tabs

### Description
应用场景：为tab添加右键菜单：关闭所有、关闭其他、关闭当前页、刷新等功能，类似浏览器tab页功能

**Comment by Leopoldthecoder** [comment]
Not a common use case. You can add event listeners to DOM elements.

**Comment by ekoz** [comment]
@Esa-i see #14715
