### ISSUE TITLE
[Bug Report] tree tree custom node content online can not run the custom area content display blank

### ISSUE THREAD

**Issue by as236676674** [ElemeFE/element#4881]
### Element UI version
1.3.1

### OS/Browsers version
最新

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击树形自定义节点内容的在线运行 就出现以上问题（源代码复制到页面中也报错）

### What is Expected?
显示正常，不报错

### What is actually happening?
实际在线运行显示不出来 源代码拷贝到项目中报错

**Comment by Leopoldthecoder** [comment]
#5523
