### ISSUE TITLE
tree树形自定义节点内容 源代码拷贝到本地项目中报错（render-content函数报错）

### ISSUE THREAD

**Issue by as236676674** [ElemeFE/element#4883]
tree树形自定义节点内容 源代码拷贝到本地项目中报错（render-content函数报错）

**Comment by harwinvoid** [comment]
遇到了同样的问题

**Comment by harwinvoid** [comment]
we need install `babel-plugin-syntax-jsx` & `babel-plugin-transform-vue-jsx`. And In our `.babelrc` file, we need push `transform-vue-jsx`  to `plugins` array

**Comment by Mr-ou** [comment]
复制官方例子，安装插件之后，不报错了，可是点击append按钮和delete按钮不能添加和删除节点，怎么解决？
