### ISSUE TITLE
[Bug Report] tree tree custom node content source code copied to the local project reported error (render-content function error)

### ISSUE THREAD

**Issue by as236676674** [ElemeFE/element#4884]
### Element UI version
1.3.1

### OS/Browsers version
最新

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
讲自定义树形节点代码拷贝到项目中运行就报错

### What is Expected?
不报错，正常显示

### What is actually happening?
报错 Module build failed: SyntaxError: C:/upms/src/modules/system/views/user/Power.vue: Unexpected token (338:10)

**Comment by Mxsion** [comment]
yep,i got this issue too.

**Comment by renfan** [comment]
```
    renderContent(h, { node, data, store }) {
        return (
          <span>
            <span>
              <span>{node.label}</span>
            </span>
            <span style="float: right; margin-right: 20px">
              <el-button size="mini" on-click={ () => this.append(store, data) }>Append</el-button>
              <el-button size="mini" on-click={ () => this.remove(store, data) }>Delete</el-button>
            </span>
          </span>);
      }
```
这段代码，如果用javascript语法怎么写？或者我在laravel 5.4里面怎么配置vue环境

**Comment by renfan** [comment]
ok，我好像解决了。
`<script type="text/babel">`
然后配置一下jsx
[babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx)
在webpack.mix.js中
```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.css$/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/
            },
        ]
    }
});
```

**Comment by Leopoldthecoder** [comment]
Read the FAQ and get yourself familiar with render functions.
