### ISSUE TITLE
The [Bug Report] Upload component actually sends multiple requests when uploading multiple files

### ISSUE THREAD

**Issue by auturain** [ElemeFE/element#4887]
### Element UI version
1.3.3

### OS/Browsers version
Windows 10/Chrome 58.0.3029.96

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
（jsfiddle我这边访问好慢，请忽略上面的重现链接）
我直接描述吧，很简单的：就是我只用你们官方文档的“手动上传”（http://element.eleme.io/#/zh-CN/component/upload ）样例，用于上传的时候同时提交form信息，但是后来我发现在上传多文件的时候，其实是多次提交（也就是说我要上传N个文件，那么就会提交N次，同时form信息也会重复提交N次）

### What is Expected?
点击上传之后能够一个Content-Type:multipart/form-data的POST请求，将所有的文件和form信息同时提交

### What is actually happening?
N个文件会产生N次请求

**Comment by hpyer** [comment]
我也发现这个问题了，不过感觉这应该不算bug，但是还是希望最好能增加个开关选项，以支持多个文件在一个请求中提交的需求吧

**Comment by baiyaaaaa** [comment]
It's not a bug and we have no plan to implement this feature

**Comment by josewhitetower** [comment]
Is there any way I can access to the list of uploaded files, so I can send them as an array to my https request?

**Comment by jjoao07** [comment]
@josewhitetower can you share your solution, please.

I'm facing the same problem, trying to upload multiple files in one form, but 
I'm ending up making multiple requests, which is not helping with my use case.

`<el-upload
						class="upload-demo"
						drag
						ref="documentForm"
						:action="action"
						:on-preview="handlePreview"
						:on-remove="handleRemove"
						:file-list="fileList"
						:data="form"
						:auto-upload="false"
						:on-progress="onProgress"
						:on-success="onSuccess"
						:on-error="onError">
						<i class="el-icon-upload"></i>
						<div class="el-upload__text">Drop files here or <em>click to upload</em></div>
						<div class="el-upload__tip" slot="tip">jpg/png files with a size less than 500kb</div>
					</el-upload>`

And below is submit method, which is called on form submission

`onSubmit () {
				this.loading = true
				this.$refs.documentForm.data.file_type = this.$refs.documentForm.uploadFiles[0].raw.type
				this.$refs.documentForm.data.file_size = this.$refs.documentForm.uploadFiles[0].raw.size
				this.$refs.documentForm.submit()
			},`

**Comment by liuzhibin123** [comment]
@baiyaaaaa @josewhitetower @auturain   我也面临着同样的问题，试图以一个请求上传多个文件，但
我最终提出了多个请求。想知道 后来你们是怎么解决的，不行的话是不是要换别的上传请求方式了。

**Comment by china-fengguan** [comment]
Using file-list parameter, instead of submitting the upload form, we create a axios function post fileList to back-end, and on-change event can be used to update fileList. FYI.

**Comment by josewhitetower** [comment]
I use Laravel as backend, check the use of the FormData interface.
I have an event listener attached to the click event of the button. I implement all checks and error handling as well. Here the solution I found and works for me
I've implemented it this way:
```
 <el-upload
            drag
            :action="uploadUrl"
            :file-type="'picture'"
            :show-file-list="true"
            :file-list="fileList"           
            :on-preview="onPreview"
            ref="upload"
            :on-change="onChange"
            :on-remove="onRemove"
            multiple
            :auto-upload="false"
            :before-remove="beforeRemove"
        >
            <i class="el-icon-upload"/>
            <div class="el-upload__text">
                Upload</em>
            </div>            
   </el-upload>

export default {
   ...
 methods: {
   ...
   onRequest() { 
           const filesRaw = this.filesToUpload.map(f => f.raw);
                const formData = new FormData();            
                for (const file of filesRaw) {
                    formData.append('files[]', file, file.name)
                }
      
                fetch(this.uploadUrl, {
                    method: 'POST',
                    credentials: "same-origin",
                    body: formData,
                }).then(r => r.json())
                .then(res => this.onSuccess(res))
                .catch(err => this.onError(err));  
        },
    }
}

**Comment by jjoao07** [comment]
Thanks, @josewhitetower, will try to implement your idea, and see where I end up.
