### ISSUE TITLE
[Feature Request] Line break (\n)  support in table cell

### ISSUE THREAD

**Issue by nidin** [ElemeFE/element#4888]
### Existing Component
Yes

### Component Name
table

### Description
There is no way to override table cell style to enable line break in table cell.
Please add line break support in table cell or a way to override cell styles.

**Comment by Leopoldthecoder** [comment]
I think it can be overridden. Please write a demo so that I'll know what goes wrong.

**Comment by nidin** [comment]
Here is the demo 
https://jsfiddle.net/gk7b0Lwb/
documentation says **"class-name"** is class name of cells in the column but **".el-table .cell"** styles in theme overriding given styles.

**Comment by wacky6** [comment]
How about this?

@nidin 

```css
.el-table .line-break .cell {
  white-space: pre;
}
```

**Comment by nidin** [comment]
@wacky6 Perfect, Issue solved.
