### ISSUE TITLE
What can [Bug Report] element do to simplify the modification information?.

### ISSUE THREAD

**Issue by wangyongchao123** [ElemeFE/element#4895]
### Element UI version
1.3.3

### OS/Browsers version
null

### Vue version
2.0

### Reproduction Link
[https://github.com/ElemeFE/element/issues/4894](https://github.com/ElemeFE/element/issues/4894)

### Steps to reproduce
null

### What is Expected?
element点击修改后，本页面抓取信息后将信息显示在本页面弹出的修改表格，在表格里修改完成后，点击完成，完成信息的修改，并将信息显示在原来的界面里。

### What is actually happening?
无法实现此功能。

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
