### ISSUE TITLE
[Bug Report] Change row width table by CSS but with scoped in style tag it is useless

### ISSUE THREAD

**Issue by kungcn** [ElemeFE/element#4897]
### Element UI version
1.3.3

### OS/Browsers version
win10 / Chrome 56

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/210/](https://jsfiddle.net/pj71jkyw/210/)

### Steps to reproduce
1. write down scoped in style tag like <style scoped lang="scss"></style>
2. F12 in Chrome
3. row-class-name like ggg is in HTML element but can not be found in style block.
4. remove scoped in style tag and refresh, re-open ggg shows in style block.

with scoped in style tag:

![2017-05-17_095743](https://cloud.githubusercontent.com/assets/12772780/26135363/9848445c-3ae7-11e7-8ab2-46abbbfb5391.png)

removing scoped in style tag:

![2017-05-17_095723](https://cloud.githubusercontent.com/assets/12772780/26135381/b91ba246-3ae7-11e7-8a5b-adef395c5b14.png)

![2017-05-17_100325](https://cloud.githubusercontent.com/assets/12772780/26135451/23a15020-3ae8-11e7-8b54-d9e851e274da.png)

### What is Expected?
row-class-name can help to change row width in table

### What is actually happening?
row-class-name can not be found in style block when using scoped. remove "scoped" it works.
Maybe it is scoped problem but it is hard to debug.

**Comment by Leopoldthecoder** [comment]
#1477 #377

**Comment by kungcn** [comment]
ok, thx.
