### ISSUE TITLE
[Bug, Report], ie11, this.$msgbox and this.$prompt below use then, and then doesn't work

### ISSUE THREAD

**Issue by bihongbin3027** [ElemeFE/element#4902]
### Element UI version
1.2.3

### OS/Browsers version
ie11

### Vue version
2.2.1

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
在element ui 官网进去“MessageBox 弹框”，当this.$msgbox和this.$prompt使用到then的时候，在ie11下面就报错

### What is Expected?
希望在ie11下面可以正常使用then

### What is actually happening?
希望在ie11下面可以正常使用then

**Comment by SimulatedGREG** [comment]
@bihongbin3027 

IE11 does not have native Promises. You need to include a polyfill to use Promises in IE11. https://github.com/taylorhakes/promise-polyfill
