### ISSUE TITLE
The [Bug Report] DatePicker component displays the corresponding type component by changing the type type, and clicks DatePicker, where the panel displays the exception

### ISSUE THREAD

**Issue by x-fox** [ElemeFE/element#4905]
### Element UI version
1.3.3

### OS/Browsers version
win 7 / chrome 56.0.2924.76

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/hgxt68te/](https://jsfiddle.net/hgxt68te/)

### Steps to reproduce
1、点击周按钮，切换周类型DatePicker，点击日期组件，下拉面板显示异常，边框塌陷
2、再次点击周按钮，再点击日期组件，下拉面板恢复正常显示
3、点击日按钮，切换回日类型DatePicker，点击日期组件，下拉面板同样异常，边框塌陷
4、再次点击日按钮，再点击日期组件，下拉面板恢复正常显示

### What is Expected?
通过外部改变组件type类型和v-if渲染组件时，点击下拉面板显示正常。

### What is actually happening?
通过外部改变组件type类型和v-if渲染组件时，点击下拉面板显示异常，边框塌陷。

**Comment by Leopoldthecoder** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10095631/26478227/6013af1e-41fd-11e7-86ea-b0484abd89e3.gif)

没能重现。贴下截图或者动图吧。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/hgxt68te/1/

**Comment by loopArray** [comment]
并没有看到解决呀，怎么关掉了？

**Comment by wacky6** [comment]
新版本好像修复了

**Comment by cuijiudai** [comment]
新版本好像没修复

**Comment by Shu-Ji** [comment]
2019 新版本没修复。
通过两个控制，我的v-model是共用的，一个是接受单数格式""，一个是数组格式:["", ""]，手动控制太麻烦了，这个date-picker就不能有一个`:destroy-on-close="true"`的设置吗？
