### ISSUE TITLE
[Bug Report] Checkbox can't be disabled in table

### ISSUE THREAD

**Issue by DoryDuan** [ElemeFE/element#4906]
### Element UI version
1.3.3

### OS/Browsers version
google

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Checkbox can't be disabled in table.

### What is Expected?
Checkbox can't be disabled in table

### What is actually happening?
Checkbox can't be disabled in table

**Comment by Leopoldthecoder** [comment]
Closing for invalid demo link. You can reopen this when you have a valid one.
