### ISSUE TITLE
[Bug Report] select with allow-create not show no-data-text prop

### ISSUE THREAD

**Issue by hnujxm** [ElemeFE/element#4907]
### Element UI version
1.3.3

### OS/Browsers version
win10  Google Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[http://jsfiddle.net/Lfx8bwjk/](http://jsfiddle.net/Lfx8bwjk/)

### Steps to reproduce
1,set select component width allow-create prop
2,set options with empty array []
3,click the select component

### What is Expected?
show no-data-text 

### What is actually happening?
not show  no-data-text ,and can not give user friendly tip

**Comment by Leopoldthecoder** [comment]
Fixed in #4977
