### ISSUE TITLE
[Feature Request] Custom template for sum in el-table

### ISSUE THREAD

**Issue by wonyeouuu** [ElemeFE/element#4911]
### Existing Component
Yes

### Component Name
el-table

### Description
Hello!

Glad you added sum row and sum-method in el-table component!

I'm curious about if we can display custom template for sum row.

For now, it returns an array of data displayed at the bottom of the table, maybe we can modify the API let it return an array of render function to render the custom template.
(i.e. similar to defining scopedSlots in el-table-column component.)

Thanks!

**Comment by Leopoldthecoder** [comment]
Sorry, we may not support this. Plus, you can use the `append` slot.
