### ISSUE TITLE
[Feature Request] Want an attribute to setup whether to show Radio/Checkbox‘s label text

### ISSUE THREAD

**Issue by keepmood** [ElemeFE/element#4913]
### Existing Component
Yes

### Component Name
Radio/Checkbox

### Description
Can't use Radio/Checkbox component without label text, it's always setting by :label attribute when you don't need slot content, i think this is a useful feature, what do you think?

BTW, thx for your work, ElementUI awesome!

**Comment by Leopoldthecoder** [comment]
You mean when they are nested inside RadioGroup / CheckboxGroup?

**Comment by keepmood** [comment]
@Leopoldthecoder Yup, i need a radio column without label text. Is there another way, but i don't know?
![wx20170518-143530](https://cloud.githubusercontent.com/assets/6124209/26189482/8b5dd0ae-3bd7-11e7-8665-7658971a9ca6.png)

**Comment by Leopoldthecoder** [comment]
In this case, you don't have to wrap Radios in RadioGroup since there is only one Radio for each row. See the first demo in our docs.

**Comment by keepmood** [comment]
@Leopoldthecoder I'm not using a RadioGroup, it is a single radio in each row, and also i cant't find any Radio demo without label text, i read your source code then find that you always setting label text&value by label attribute, is there an mistake?

![wx20170519-114323](https://cloud.githubusercontent.com/assets/6124209/26232382/750efba0-3c88-11e7-8476-22156990725e.png)

**Comment by Leopoldthecoder** [comment]
My mistake. It seems you have hide the labels using CSS `display: none`.

**Comment by keepmood** [comment]
Okay, but i think :value/:label should be set separately.

Anyway, thx for your reply. 🙂
