### ISSUE TITLE
[Bug Report] 表格的列宽即width属性不能正确地动态响应。特定情况下会导致Mac上的Chrome58必定崩溃。 Dynamically changing the width of columns of a table will lead to unpredictable width value. And in certain case, it will surely lead to a browser crash.

### ISSUE THREAD

**Issue by shawtung** [ElemeFE/element#4914]
### Element UI version
1.3.3

### OS/Browsers version
MacOS 10.12 Chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/k1cy2zsm/](https://jsfiddle.net/k1cy2zsm/)
Page crash in Chrome 58@MacOS 10.12.
Abnormal behavior in other envs I have.

### Steps to reproduce
点击按钮。这会将与第一列宽度动态绑定的属性z.a改为200.
Click the oops button. This will change the property z.a to 200, which binds to the first column width.

### What is Expected?
第一列宽度值应该变为200px。
The first column will expand to 200px in width.

### What is actually happening?
In Chrome 58 on MacOS 10.12, Chrome will crash without fail. 页面必崩
In firefox and Chrome 57, the first column will expand to an extremely large extent in width. 变得超宽。
In Chrome 58 on Windows 10, devtools show "width: 2.001e+08px;", but the element inspection tag hanging above the table tells that the actual width is 33554400. 莫名其妙。

**Comment by xcodebin** [comment]
你少了px，在String(z.a)后面加上+'px'

**Comment by Leopoldthecoder** [comment]
Any particular reason Table is nested in an `inline-block` div?

**Comment by shawtung** [comment]
@Leopoldthecoder No. Maybe it's the diff algorithm in virtual dom that causes the problem. After key attribute applied for every item in v-for, things work well.

**Comment by zhoulaiqing** [comment]
@shawtung 我也遇到了这个问题，你是怎么解决的？

**Comment by hughfenghen** [comment]
@zhoulaiqing 不管react、还是vue，循环时一定要给节点加上**唯一key**。
加上唯一key就搞定了。
