### ISSUE TITLE
[Feature Request] Select component does not auto-select items when typing

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#4916]
### Existing Component
Yes

### Component Name
Select

### Description
I believe this is a FR and not a bug, but I could be wrong.

Here I am comparing Element-UI's select component to the standard html select:
https://jsfiddle.net/hunc7rc3/

When you open each select, type 'b'. You'll notice that the html select will auto-select 'banana'. Nothing happens with Element-UI's select.

**Comment by ChuckFields** [comment]
I just found out about the default-first-option attribute which does exactly this. Closing this issue.

**Comment by ChuckFields** [comment]
Actually, 'default-first-option' only works when used with 'filterable' or 'remote', Reopening this issue.

**Comment by Leopoldthecoder** [comment]
***auto-select items when typing*** is actually not that easy to be handled in our end. However, you can implement this feature like this: https://jsfiddle.net/hunc7rc3/1/

**Comment by StaverDmitry** [comment]
Hi! 
Are there any changes to this since 2017? 
Is it possible to make el-select behave like a regular select when typing without `filterable` or hardcoding it with an event handler?
