### ISSUE TITLE
[Bug Report] Year DatePicker selects wrong year

### ISSUE THREAD

**Issue by Async0x42** [ElemeFE/element#4918]
### Element UI version
1.3.3

### OS/Browsers version
Windows 10, Chrome v59

### Vue version
2.3.3

### Reproduction Link
https://jsfiddle.net/pj71jkyw/213/

### Steps to reproduce
1) Select '2015'

### What is Expected?
'2015' should be selected

### What is actually happening?
'2014' is selected

**Comment by Leopoldthecoder** [comment]
@Async0x42 Does this bug still exist? Because the demo now works fine.

**Comment by Async0x42** [comment]
@Leopoldthecoder Everything is working now, thanks a lot.
