### ISSUE TITLE
[Bug Report] Year DatePicker initializes with 1969

### ISSUE THREAD

**Issue by Async0x42** [ElemeFE/element#4919]
### Element UI version
1.3.3

### OS/Browsers version
Windows 10, Chrome v59

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/211/](https://jsfiddle.net/pj71jkyw/211/)

### Steps to reproduce
Load the jsfiddle

### What is Expected?
'2017' should be selected on initialization

### What is actually happening?
'1969' is selected

**Comment by rongxingsun** [comment]
https://jsfiddle.net/pj71jkyw/212/

**Comment by Async0x42** [comment]
Whoops, that's my bad then. Thanks for the correction.

It does highlight the following issue however: https://github.com/ElemeFE/element/issues/4918
