### ISSUE TITLE
Datepicker is showing Days & month names in chinese,  how can i make that to english?  

### ISSUE THREAD

**Issue by chagamkamalakar** [ElemeFE/element#492]
first of all , element ui is great library, it's saving my day of work. i'm really thankful to the team behind it.

 I am trying to use date picker, the output is as show in below.

![element-ui-datepicker](https://cloud.githubusercontent.com/assets/6966631/19472608/86626cec-9545-11e6-96c8-70af36ff33c4.png)

here bit weird thing i observed related to day , month names
the following things are getting displayed in chinese 
1) month  name
2) current date ( say today is 18, so 18 th is always in chinese )
3) day name

how would i make those things to appear in english?

**Comment by QingWei-Li** [comment]
install `vue-i18n`

demo
```javascript
import Vue from 'vue';
import App from './app';
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-default/index.css';
import i18n from 'vue-i18n';

Vue.use(i18n);
Vue.use(ElementUI);
Vue.config.lang = 'en';
Vue.locale('en', {
  datepicker: {
    now: 'now',
    today: 'today',
    cancel: 'cancel',
    clear: 'clear',
    confirm: 'confirm',
    selectDate: 'selectDate',
    selectTime: 'selectTime',
    startTime: 'startTime',
    endTime: 'endTime',
    year: 'year',
    month: 'Month',
    week: 'week',
    weeks: {
      sun: 'sun',
      mon: 'mon',
      tue: 'tue',
      wed: 'wed',
      thu: 'thu',
      fri: 'fri',
      sat: 'sat'
    },
    months: {
      jan: 'jan',
      feb: 'feb',
      mar: 'mar',
      apr: 'apr',
      may: 'may',
      jun: 'jun',
      jul: 'jul',
      aug: 'aug',
      sep: 'sep',
      oct: 'oct',
      nov: 'nov',
      dec: 'dec'
    }
  }
});

new Vue({ // eslint-disable-line
  el: '#app',
  render: h => h(App)
});
```

**Comment by chagamkamalakar** [comment]
thank you @QingWei-Li  .. it's working  :+1:  :)

**Comment by chagamkamalakar** [comment]
once i upgraded this to 1.0.0.-rc.8 , the display is unexpected , as follows 

![datepicker](https://cloud.githubusercontent.com/assets/6966631/19838297/203b4f4a-9ef2-11e6-9de6-ebffa87a1b5e.png)

**Comment by chagamkamalakar** [comment]
ond some other useful info for the above issue 
![screenshot from 2016-10-30 23 01 52](https://cloud.githubusercontent.com/assets/6966631/19838422/002101ca-9ef5-11e6-8327-5e988da2199e.png)

**Comment by QingWei-Li** [comment]
I updated the filed name. But now, you just import the locale file. Such as

```
import ElementUI from 'element-ui'
import locale from 'element-ui/lib/locale/lang/en'
import Vue from 'vue'

Vue.use(ElementUI, { locale })
```

**Comment by Leopoldthecoder** [comment]
Will add an English documentation on how to apply i18n soon.

**Comment by leo-coco** [comment]
How to use the local if we import component by component ?

This does not work

```
import locale from 'element-ui/lib/locale/lang/en'

import {
    DatePicker,
    TimePicker,
} from 'element-ui'

Vue.use(DatePicker, { locale })
Vue.use(TimePicker, { locale })
```

**Comment by markadrake** [comment]
If we are cherry-picking elements out of the element-ui library to use, such as the date picker, how would we apply localization? This does not seem to work.

```
import Vue from 'vue';
import Question from './Components/form-question.vue';
Vue.use(DatePicker, { locale });
```

**Comment by Gsubha** [comment]
Display  only month name in bootstrap datepicker
 $("#datepicker").datepicker({
            format: "mm",
            startView: "months",
            minViewMode: "months"
        });
To display years in bootstrap datepicker

        $("#datepicker1").datepicker({
            format: "yyyy",
            startView: "years",
            minViewMode: "years"
        });
It works for me

**Comment by gustawdaniel** [comment]
Anyway chinese signs should not be rather default.

**Comment by factreset** [comment]
> Anyway chinese signs should not be rather default.

Guessing 1.4 billion people might disagree

**Comment by nelsonSetyawan09** [comment]
how i can styling datepicker, like background-color, color for the all element like icon, button, text

**Comment by Phumbie** [comment]
> install `vue-i18n`
> 
> demo
> 
> ```js
> import Vue from 'vue';
> import App from './app';
> import ElementUI from 'element-ui';
> import 'element-ui/lib/theme-default/index.css';
> import i18n from 'vue-i18n';
> 
> Vue.use(i18n);
> Vue.use(ElementUI);
> Vue.config.lang = 'en';
> Vue.locale('en', {
>   datepicker: {
>     now: 'now',
>     today: 'today',
>     cancel: 'cancel',
>     clear: 'clear',
>     confirm: 'confirm',
>     selectDate: 'selectDate',
>     selectTime: 'selectTime',
>     startTime: 'startTime',
>     endTime: 'endTime',
>     year: 'year',
>     month: 'Month',
>     week: 'week',
>     weeks: {
>       sun: 'sun',
>       mon: 'mon',
>       tue: 'tue',
>       wed: 'wed',
>       thu: 'thu',
>       fri: 'fri',
>       sat: 'sat'
>     },
>     months: {
>       jan: 'jan',
>       feb: 'feb',
>       mar: 'mar',
>       apr: 'apr',
>       may: 'may',
>       jun: 'jun',
>       jul: 'jul',
>       aug: 'aug',
>       sep: 'sep',
>       oct: 'oct',
>       nov: 'nov',
>       dec: 'dec'
>     }
>   }
> });
> 
> new Vue({ // eslint-disable-line
>   el: '#app',
>   render: h => h(App)
> });
> ```

how would i covert this to nuxt

**Comment by gokhantaskan** [comment]
I use [Vue-i18n](https://kazupon.github.io/vue-i18n/) and here is what I did: 

```js
// App.vue

<script>
import eLocale from "element-ui/lib/locale";
import langEn from "element-ui/lib/locale/lang/en";
import langTr from "element-ui/lib/locale/lang/tr-TR";
...

mounted() {
  ...
  const stateLocale = this.$store.state.locale;
  eLocale.use(stateLocale === "en-US" ? langEn : langTr);
}
```

`this.$store.state.locale` is arranged by i18n and returns "en-US" or "tr-TR", so **you do not have to set locale in `element.js` file.**

**Comment by zaini14** [comment]
You Can Read The DocumentationHere

https://element.eleme.io/#/en-US/component/i18n
just import package and you can use another language

`import lang from 'element-ui/lib/locale/lang/en'
import locale from 'element-ui/lib/locale'

// configure language
locale.use(lang)`

**Comment by antoniosthanasisgit** [comment]
import ElementUI, { DatePicker } from 'element-ui'

Vue.use(ElementUI)
Vue.use(DatePicker)

**Comment by KumarAmitt** [comment]
You can wrap the specific component inside <a-config-provider :locale="enUS"></a-config-provider> and import the locale file from node modules. Please refer the official documentation:
-  [Vue.js](https://arco.design/vue/en-US/docs/i18n)
-  [React.js](https://arco.design/react/en-US/docs/i18n)

Example for Vue.js
```js
<template>
  <a-config-provider :locale="enUS">
    <a-pagination :total="50" show-total show-jumper show-page-size />
  </a-config-provider>
</template>

<script setup>
import enUS from '@arco-design/web-vue/es/locale/lang/en-us';

</script>
```
