### ISSUE TITLE
[Bug Report] Checkbox can't be disabled in the table.

### ISSUE THREAD

**Issue by DoryDuan** [ElemeFE/element#4920]
### Element UI version
1.3.3

### OS/Browsers version
google

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/v9L9f3ks/](https://jsfiddle.net/v9L9f3ks/)

### Steps to reproduce
Is there any way to make a part of checkbox to be disabled in table?

### What is Expected?
Make some of checkbox to be disabled in table.

### What is actually happening?
Checkbox can't be disabled in the table.

**Comment by DoryDuan** [comment]
Solved this problem. There is a selectable attribute in table component.

**Comment by braian125** [comment]
> Solved this problem. There is a selectable attribute in table component.

Hi, @DoryDuan 
Did you find any example of how it can be implemented?
