### ISSUE TITLE
[Feature Request] Cascader dynamic loading back display

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#4922]
### Existing Component
是

### Component Name
Cascader

### Description
在动态加载的情况下，是否可以根据value数组内的内容自动获取多级数据并回显？现在貌似只能手工处理，而且还没有什么省事的办法。

https://jsfiddle.net/jyvssgty/

**Comment by baiyaaaaa** [comment]
不太清楚你的意思，这个不是本来就是要自己处理的吗。你可以再说清楚点嘛？

**Comment by An0nymous0** [comment]
@baiyaaaaa 根据el-cascader中的v-model数组字段自动带出下级。当然这个也可以自己手动处理。

**Comment by blankPage0806** [comment]
动态加载次级项 是否可以加载更多级呢？

**Comment by slipkinem** [comment]
请问这个问题如果手动解决怎么弄？

**Comment by An0nymous0** [comment]
@slipkinem 手动触发一下handleItemChange带出下级。 然后在给次级默认值

**Comment by lmy1991** [comment]
官方给的例子根本不能算是动态加载。
例子给的只是两级，而且下标还是写死的情况下。
那么请问实际使用，四级或者更多的情况下，我的要怎么给我的子级赋值。考虑过么？

**Comment by hanxiaosss** [comment]
手动有比较好的解决方案吗
