### ISSUE TITLE
[Bug Report] Why DatePicker Display Format is always english

### ISSUE THREAD

**Issue by SasmeitoU** [ElemeFE/element#4924]
### Element UI version
1.3.3

### OS/Browsers version
Google Chrome

### Vue version
2.2.2

### Reproduction Link
[https://github.com/ElemeFE/element/issues/3786](https://github.com/ElemeFE/element/issues/3786)

### Steps to reproduce
--

### What is Expected?
Should the date I choose should match what appears in the date column for the language used.

### What is actually happening?
I have followed the steps how to change the language used, I am currently using Indonesian for the date format. For when choosing the date is in accordance with the format of the language used, but after the date in select language format that appear is English? Is there a configuration for the selected language to match the language that appears?

**Comment by mamalat** [comment]
Is this a duplicate?

**Comment by Leopoldthecoder** [comment]
Duplicate indeed.
