### ISSUE TITLE
在v-for中使用el-popover组件的BUG（必现）

### ISSUE THREAD

**Issue by shiyuegongsui** [ElemeFE/element#4926]
列子:
<div v-for="(item,index) in 2">
<el-popover
  ref="popover2"
  placement="bottom"
  title="标题"
  width="200"
  trigger="click"
  content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
</el-popover>
<el-button v-popover:popover2>click 激活</el-button>
</div>

错误：
[Vue warn]: Error in directive popover bind hook: "TypeError: Cannot read property '$refs' of undefined"

TypeError: Cannot read property '$refs' of undefined

**Comment by renruijun** [comment]
你好请问你的问题解决了吗

**Comment by samon127** [comment]
#246 这里有一个解决方案，是不是因为 popover 和 button 的顺序问题~

**Comment by samon127** [comment]
#246 这里的解决方案可以试试，是不是因为 popover 和 button 的顺序问题~
