### ISSUE TITLE
[Bug Report] The dislocation problem of Table components on Safari

### ISSUE THREAD

**Issue by yugasun** [ElemeFE/element#4928]
### Element UI version
1.3.3

### OS/Browsers version
Mac

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/yugasun/ok3543hj/3/](https://jsfiddle.net/yugasun/ok3543hj/3/)

### Steps to reproduce
直接用Safari浏览器打开，就可以发现表头有错位问题。

### What is Expected?
应该和Chrome中一样整齐显示

### What is actually happening?
Safari中却表头错位

**Comment by yugasun** [comment]
难道这个问题，大家都没遇到过吗？没有人回复？

**Comment by kugeliu** [comment]
我也碰到了你这个问题，请问你解决了吗 @yugasun

**Comment by yugasun** [comment]
@kugeliu 还没解决，还好我这是内部项目，可以妥协改需求。。。不过这个Bug是没人管了么。。。

**Comment by baixiaoji** [comment]
所以至今都没有修复咯？
so it's  fixed?

**Comment by hizhengfu** [comment]
2.0问题还是存在

**Comment by GodStream** [comment]
2.0.11，还是存在问题

**Comment by furybean** [comment]
2.1.0 已经无法重现此问题：https://jsfiddle.net/ok3543hj/6/，请确认。

**Comment by furybean** [comment]
先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。
