### ISSUE TITLE
组件 i18n 默认提供

### ISSUE THREAD

**Issue by furybean** [ElemeFE/element#493]
如果要支持英文文档，但是组件还是显示中文，那就并没有意义，列一个列表出来，把组件的 i18n 下个 rc 支持上。

- [x] DatePicker
- [x] Select
- [x] Pagination
- [x] Message Box
- [x] Upload

**Comment by kaminski** [comment]
Lovely work you are doing, thank you very much? 

How could I overcome the i18n issue with e.g. the date-picker component? When change the code in node_modules it seems that webpack disregards it. Could you give me a hint how I can solve this for the time being? Does webpack cache packages or do I need to change the default configuration or command "npm run dev"?
