### ISSUE TITLE
[Bug Report] DateTinePicker format is not taken into the picker itself

### ISSUE THREAD

**Issue by simonfunk** [ElemeFE/element#4931]
### Element UI version
1.3.3

### OS/Browsers version
Windows 10 / Chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/n8kx2xfc/](https://jsfiddle.net/n8kx2xfc/)

### Steps to reproduce
just click in the input field

### What is Expected?
that the given format also shows on the datepicker / timepicker

### What is actually happening?
it just show the english format, the format has only on the input field effect.

**Comment by ChuckFields** [comment]
@simonfunk I have a fix for this, but I want to discuss. In the date picker panel, the time field currently gets formatted with this logic: (Note: this.format is the format you provide to the DateTimePicker, e.g. 'dd/MM/yyy HH:mm:ss' )
```
      timeFormat() {
        if (this.format && this.format.indexOf('ss') === -1) {
          return 'HH:mm';
        } else {
          return 'HH:mm:ss';
        }
      }
```
As you can see, it's just checking for the presence of seconds and returning a hard coded value -I think this is alright. The date field on the other hand is hard coded to always use 'yyyy-MM-dd'. I've changed it to use this computed function:
```
      dateFormat() {
        if (this.format) {
          return this.format.replace('HH:mm', '').replace(':ss', '').trim();
        } else {
          return 'yyyy-MM-dd';
        }
      }
```
If this works for you, I will go ahead and create a pull request.

**Comment by simonfunk** [comment]
Hi ChuckFields

Thanks a lot for picking my feature request up.

Well, yes i guess that would work. But i'm wondering why you don't use the moment.js library in general? that would make it much easier for you, also with handling formats and other time related parts.

Anyway, i'm happy with it :)

Thanks

**Comment by ChuckFields** [comment]
@simonfunk Awesome. It's no problem, I actually needed this bug fixed as well. I agree with you about moment.js. I'm wondering why all of element-ui doesn't use moment.js. We're currently using moment and it seems to play nicely with all of the date/time components. I'm sure it could clean up a lot of code within element.
Anyway, I should have a pull request by tomorrow.

**Comment by simonfunk** [comment]
Great thanks!
I like element really. I will join in and help as soon as i have a little time.

Just an aesthetic thing. i love clean and short codes, so i would do it like:
`dateFormat() {
        return this.format
          ? this.format.replace('HH:mm', '').replace(':ss', '').trim();
          : 'yyyy-MM-dd';
      }`

or for the timeFormat method:

`timeFormat() {
        return this.format && this.format.indexOf('ss') === -1
          ? 'HH:mm';
          : 'HH:mm:ss';
        }
      }`

Thanks again

**Comment by Leopoldthecoder** [comment]
@ChuckFields Glad you are contributing. As for moment.js, we didn't use it because of its size, which is one-third of Element itself.
