### ISSUE TITLE
[Feature Request]: the on-icon-click event bound by click cannot pass arguments

### ISSUE THREAD

**Issue by gooyoung** [ElemeFE/element#4937]
### Existing Component
是

### Component Name
el-input 

### Description

`<el-input size="small"  v-model="scope.row.image" icon="plus" :on-icon-click="addImage"></el-input>`

如果我想给addImage带上scope.$index参数 =》 addImage(scope.$index)。该怎么实现？

**Comment by Leopoldthecoder** [comment]
You can bind `on-icon-click` to a high order function, which takes index as a parameter, and returns the actual callback function.
