### ISSUE TITLE
The [Feature Request] el-table page displays 200 (20 fields or so), renders Caton, and the form drop-down box cannot be clicked at this time (also Caton), or even a page crash

### ISSUE THREAD

**Issue by mackeystar** [ElemeFE/element#4938]
### Existing Component
Yes

### Component Name
el-table

### Description
el-table 一页显示200条（20个字段左右），渲染卡顿，表单下拉框在这个时候无法点击（也是卡顿），甚至是页面崩溃
是否有类似clusterize功能的属性来解决？
window10/chrome版本 58.0.3029.110 (64-bit)

**Comment by Leopoldthecoder** [comment]
We suggest using Pagination when you have more than 50 data items in a single Table.

For performance optimization, Element itself may not include something like clusterize. You can try writing a scroll event handler that dynamically changes table data.
