### ISSUE TITLE
upload只要在table中循环生成. upload的data就传不到服务器端

### ISSUE THREAD

**Issue by snoopy83101** [ElemeFE/element#4940]
https://github.com/ElemeFE/element/issues/3972

与上述连接描述一致, 我就不再按照什么格式了. 这是bug! 重视一下吧 别光知道关问题了. 你要是想关问题, 那么你总能找到理由

**Comment by snoopy83101** [comment]
狂草你们element他妈雪碧. 草你们妈的.

**Comment by dcy0701** [comment]
snoopy83101 别出来丢人现眼了
