### ISSUE TITLE
[Bug Report] VUE single file using the Element-UI components which form, cannot select box (head checkbox) linkage and single checkbox

### ISSUE THREAD

**Issue by tuxknight** [ElemeFE/element#4945]
### Element UI version
1.2.9

### OS/Browsers version
macOS Sierra 10.12 (16A323)/Google Chrome  57.0.2987.133 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://gist.github.com/tuxknight/a86327f65a4fab4b526f92d357f255e9](https://gist.github.com/tuxknight/a86327f65a4fab4b526f92d357f255e9)

### Steps to reproduce
使用单文件组件，在多选表格中，表头的全选框并没有作用。jsfiddle 配置没法重现。我会找时间搭一个可公开访问的示例来重新。

### What is Expected?
选中全选框，各行的 checkbox 自动变成 checked 状态
取消选中全选框，各行的 checkbox 自动变成  unchecked 状态

### What is actually happening?
无论选中全选框还是取消选中全选框，各行的 checkbox 都无相应的动作。

**Comment by Leopoldthecoder** [comment]
If you're using Vue 2.3.x, please make sure to upgrade Element to 1.3.x. This is a compatibility issue.
