### ISSUE TITLE
[Bug Report] IE9-table position float

### ISSUE THREAD

**Issue by nibilin33** [ElemeFE/element#4949]
### Element UI version
1.3.3

### OS/Browsers version
WIN7/IE 9.0.8112.16421

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
1.open the http://element.eleme.io/#/zh-CN/component/table in IE9
2.Zoom the window when the Horizontal scroll bar to be seen, the table height will not be stable.

### What is Expected?
the table's height not changed

### What is actually happening?
the table's height changed

**Comment by Leopoldthecoder** [comment]
It's not recommended to use Element in IE9. Actually we'll remove IE9 from our browser compatibility list soon.
