### ISSUE TITLE
[Bug Report] IE9   el-pager' width unusual blank

### ISSUE THREAD

**Issue by nibilin33** [ElemeFE/element#4950]
### Element UI version
1.3.3

### OS/Browsers version
WIN7/IE 9.0.8112.16421

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
1.open http://element.eleme.io/#/zh-CN/component/pagination in IE9
2.the el-pager's  is too much blank ,the distance between the button and page number is too much.

### What is Expected?
the distance between the button and page number is normal

### What is actually happening?
the distance between the button and page number is not perfect.

**Comment by Leopoldthecoder** [comment]
It's not recommended to use Element in IE9. Actually we'll remove IE9 from our browser compatibility list soon.
