### ISSUE TITLE
[Bug Report] cannot close dialog by default in three ways after calculating the property to display dialog

### ISSUE THREAD

**Issue by mqhe2007** [ElemeFE/element#4955]
### Element UI version
1.2.9

### OS/Browsers version
win10 chrome 58.0.3029.110 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/b77pmk9e/2/](https://jsfiddle.net/b77pmk9e/2/)

### Steps to reproduce
1. 在vuex里添加控制dialog显隐的属性
2. 在组件中通过计算属性控制dialog组建显示
3. 需要通过默认方法关闭dialog失败

### What is Expected?
可以关闭

### What is actually happening?
无法关闭

**Comment by Leopoldthecoder** [comment]
Vuex properties and computed properties cannot be modified in a Vue instance. In this case, create a new prop in `data`, bind that prop to `visible.sync`, and commit a mutation to update Vuex state when Dialog opens / closes.
