### ISSUE TITLE
In the [Bug Report] el-input component, the v-model.lazy modifier does not trigger synchronization in native change as expected

### ISSUE THREAD

**Issue by wpycs** [ElemeFE/element#4956]
### Element UI version
1.3.3

### OS/Browsers version
windows10 opera

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/hgfkq78j/2/](https://jsfiddle.net/hgfkq78j/2/)

### Steps to reproduce
在v-model.lazy绑定的input中输入数据，value值根据输入的数据实时变化

### What is Expected?
vue文档描述
在默认情况下， v-model 在 input 事件中同步输入框的值与数据 (除了 上述 IME 部分)，但你可以添加一个修饰符 lazy ，从而转变为在 change 事件中同步

如第二个input，在原生的change中输入数据，value值在enter或焦点离开时变化

### What is actually happening?
lazy修饰符未生效

**Comment by Mankel** [comment]
Has this issue fixed yet? What is the solution?

**Comment by Mankel** [comment]
Has this issue been fixed yet? What is the solution?

**Comment by wacky6** [comment]
@Leopoldthecoder 

Should we align with native input tag's behavior? 
This should be quite easy to fix.

**Comment by rDr4g0n** [comment]
I have run into this issue recently. If this won't be fixed, does anyone have a workaround for it?

**Comment by wpycs** [comment]
@rDr4g0n you can use the second input example in my link [https://jsfiddle.net/hgfkq78j/2/](url).
or you can write a component to package the el-input

**Comment by csvwolf** [comment]
Suppported.

**Comment by ziyoung** [comment]
已经修复了。https://jsfiddle.net/9qow0514/

**Comment by wpycs** [comment]
> 已经修复了。https://jsfiddle.net/9qow0514/

从给出的例子看未修复，lazy修饰符按照预期（失去焦点后数据同步至vm上）生效

**Comment by davidAlittle** [comment]
This does not work. None of the jsfiddles recognize lazy, and the original fiddle does not work.

**Comment by ziyoung** [comment]
see #14463
