### ISSUE TITLE
[Feature, Request], flex, layout, wrap, capability

### ISSUE THREAD

**Issue by kaijajan** [ElemeFE/element#4958]
### Existing Component
否

### Component Name
el-row

### Description
flex layout does not support wrap attribute, hopefully wrap can be added in the future

**Comment by Leopoldthecoder** [comment]
Please elaborate what *wrap attribute* is.

**Comment by bskimball** [comment]
I think they may have meant adding a wrap attribute for flex-wrap (https://www.w3schools.com/cssref/css3_pr_flex-wrap.asp).

What I do now is this:
```javascript
<el-row type="flex" :gutter="24" style="flex-wrap: wrap;">
    <el-col :sm="24" :md="12">content</el-col>
    <el-col :sm="24" :md="12">content</el-col>
    <el-col :sm="24" :md="12">content</el-col>
    <el-col :sm="24" :md="12">content</el-col>
<el-row>
```  
What would be nice is this:
```javascript
<el-row type="flex" :gutter="24" wrap>
    <el-col :sm="24" :md="12">content</el-col>
    <el-col :sm="24" :md="12">content</el-col>
    <el-col :sm="24" :md="12">content</el-col>
    <el-col :sm="24" :md="12">content</el-col>
<el-row>
```  
|Attribute|Description|Type|Accepted Values|Default|
|---|---|---|---|---|
|wrap|flex-wrap property|boolean or string|true, false, reverse, initial, inherit|false|
