### ISSUE TITLE
 [Feature Request] Why does separate component logic and style?

### ISSUE THREAD

**Issue by iamwelk** [ElemeFE/element#4964]
### Existing Component
No

### Component Name
各个组件

### Description
在element-ui中，将样式文件单独放到了lib/theme-default下面，而没有放到对应组件的vue文件中，请问有什么原因吗？按照vue官方的写法，感觉封装到一起会更好点啊

**Comment by iamwelk** [comment]
在element-ui中，将样式文件单独放到了lib/theme-default下面，而没有放到对应组件的vue文件中，请问有什么原因吗？按照vue官方的写法，感觉封装到一起会更好点啊

**Comment by QingWei-Li** [comment]
因为未来还有其他主题啊
