### ISSUE TITLE
[Bug Report] el-select cannot be scroll in the el-dialog in the chrome45 case

### ISSUE THREAD

**Issue by webJing** [ElemeFE/element#4966]
### Element UI version
1.3.3

### OS/Browsers version
chrome 45

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
在chrome45情况下的 el-dialog 中 的el-select 下拉框不能scroll

### What is Expected?
能解决一下兼容问题吗？ 链接只是一个案例

### What is actually happening?
在chrome45情况下的 el-dialog 中 的el-select 下拉框不能scroll，版本高的情况下不会出现

**Comment by Leopoldthecoder** [comment]
Chrome 45 is kinda obsolete, and we don't have access to it, so compatibility for Chrome 45 is not guaranteed.
