### ISSUE TITLE
[Bug Report] adds style invalidation issues to components within a component

### ISSUE THREAD

**Issue by zhujz** [ElemeFE/element#4967]
### Element UI version
1.3.3

### OS/Browsers version
Mac 10.12.4 / Chrome 58.0.3029.110 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[http://jsfiddle.net/moderate/236aLas2/1/](http://jsfiddle.net/moderate/236aLas2/1/)

### Steps to reproduce
style标签加scoped，input在template中，通过css选择器改变input样式失效

### What is Expected?
style标签加scoped，input在template中，通过css选择器改变input样式有效，编译之后应该是：
.test-success[data-v-53d86f6a] input

### What is actually happening?
style标签加scoped，input在template中，通过css选择器改变input样式失效，实际是这样：
.test-success input[data-v-53d86f6a]

**Comment by Leopoldthecoder** [comment]
#1477 #377
