### ISSUE TITLE
[Feature Request] DateTimePicker formatting of the date and time fields in the picker panel

### ISSUE THREAD

**Issue by ChuckFields** [ElemeFE/element#4968]
### Existing Component
Yes

### Component Name
DateTimePicker 

### Description
Currently, if you assign a format to a date time picker, like for instance "MM/dd/yyyy HH:mm:ss", when you open up the calendar panel to select a date, you'll notice that the date field is always in the format "yyyy-MM-dd". I'd assume that it would be fairly straight forward to intelligently break apart the format property into dateFormat and timeFormat. These 2 derived properties could then be used to format the date and time selector on the calendar panel.

**Comment by Leopoldthecoder** [comment]
Didn't reproduce this: https://jsfiddle.net/y8bpm48p/
