### ISSUE TITLE
[Feature Request] Define the font-size in el-breadcrumb

### ISSUE THREAD

**Issue by sebastienroul** [ElemeFE/element#4970]
### Existing Component
Yes

### Component Name
el-breadcrumb

### Description
It would be a good point IMHO to remove the "font-size=13px" defined on the CSS class .el-breadcrumb.
Let the user set the size via the H1, H2, ...
Example :
`
      <h3>
        <el-breadcrumb separator="/">
          <el-breadcrumb-item :to="{ path: '/item1' }">Level 1</el-breadcrumb-item>
          <el-breadcrumb-item>Level 2</el-breadcrumb-item>
        </el-breadcrumb>
      </h3>
`
It would be very easier for maintenance purpose and also when reading the HTML

I done it by overwriting the CSS : font-size: inherit;

Bye, thks for your great job

**Comment by baiyaaaaa** [comment]
Actually, in most situations breadcrumb use a fixed and small as it fontSize. So we probably not adopt this suggestion
