### ISSUE TITLE
[Bug, Report]table无法设置焦点行（不是选中行）

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#4979]
### Element UI version
1.3.3

### OS/Browsers version
Mac/safari

### Vue version
2.3.3

### Reproduction Link
https://jsfiddle.net/a96enq1u/

### Steps to reproduce
click  选中第二行

### What is Expected?
when I  use  setCurrentRow   table can get  focus,so  I can move row by KeyDow or KeyUp
当我使用setCurrentRow 后 table 能获取焦点 可以通过KeyDow KeyUp 来移动行

### What is actually happening?
when I  use  setCurrentRow   table can get  focus,so  I can move row by KeyDow or KeyUp
当我使用setCurrentRow 后 table 能获取焦点 可以通过KeyDow KeyUp 来移动行

**Comment by Leopoldthecoder** [comment]
Are you trying to highlight different rows by keyboard navigation?
