### ISSUE TITLE
时间范围控件操作问题

### ISSUE THREAD

**Issue by JasonCSharpCoder** [ElemeFE/element#498]
http://element.eleme.io/#/component/datetime-picker
时间范围控件是有错误的

**Comment by furybean** [comment]
怎么重现？我看了下控制台，并没有错。

**Comment by lincenying** [comment]
win7/chrome54

http://element.eleme.io/#/component/datetime-picker
http://element.eleme.io/#/component/date-picker
这两个`选择日期范围`都没法用, 点击日期, 没有反应, 其他不是`选择日期范围`的例子都可以用...

另外一个神奇的问题, 
![1](https://cloud.githubusercontent.com/assets/10840991/19488677/87ad05d0-959a-11e6-9071-7c017fcbe2d1.jpg)
![2](https://cloud.githubusercontent.com/assets/10840991/19488678/87af85f8-959a-11e6-849f-3d9df9e6b947.jpg)

字体竟然会影响到flex布局...

**Comment by pixcai** [comment]
我试了一下，和我提到的datetime溢出#488应该是相同的原因。估计只是在Windows上出现，这个控件的瑕疵太多了。。。

**Comment by pixcai** [comment]
@furybean 我在Win10上试了，上面说的不能点击的问题，确实存在。

**Comment by QingWei-Li** [comment]
点击不能用是啥问题，有报错么

**Comment by pixcai** [comment]
@QingWei-Li 没有报错，就是点击没有反应。
