### ISSUE TITLE
为什么table组件用了很多内置方法

### ISSUE THREAD

**Issue by rachardking** [ElemeFE/element#499]
如题

**Comment by furybean** [comment]
TableColumn 部分的转换确实用了一些内置方法，因为 TableColumn 并不是直接转换成一个组件，而是转换成：表头 + 表格体内每一行的该列的单元格。所以表头的渲染和表格体内单元格的渲染需要由 Table 组件自己完成，这里面牵涉到 context 转换的问题，不得已用了一些内部方法。
