### ISSUE TITLE
nav menu组件的default-active的值没有错，为什么下拉框没有自动展开？

### ISSUE THREAD

**Issue by liubin595338764** [ElemeFE/element#4991]
Vue里面使用element ui的nav menu组件的问题。
default-active的值没有错，为什么下拉框没有自动展开？
上面的一个例子是正常的

<script async src="//jsfiddle.net/liubiner/2swy0e0q/embed/"></script>

**Comment by muzi131313** [comment]
嗨，这个问题后续有解决么？@element-bot
