### ISSUE TITLE
[Bug Report] clicks on buttons to expand tree nodes, sometimes triggering node-click events, and sometimes nothing

### ISSUE THREAD

**Issue by GloriousFuture** [ElemeFE/element#4992]
### Element UI version
1.3.3

### OS/Browsers version
windows 7/ chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/2j5jg6yp/](https://jsfiddle.net/2j5jg6yp/)

### Steps to reproduce
点击 不同展开按钮图标，有时会alert出 数据，有时候正常

### What is Expected?
点击展开按钮图标不会触发node-click事件，即不会弹出数据

### What is actually happening?
点击 展开按钮图标，有时会alert出 数据，有时候正常

**Comment by GloriousFuture** [comment]
没人遇到这种问题么，比如做下拉树的时候？ 点击 图标有时会触发 node-click 事件

**Comment by Leopoldthecoder** [comment]
I did some test clicks in your demo and `node-click` does not trigger when the triangle icon itself is clicked.

**Comment by listen-lee** [comment]
@Leopoldthecoder 
i just try it，it does trigger when the triangle icon itself is clicked 。
windows 7 / chrome 58.0.3029.110 (64-bit)
