### ISSUE TITLE
There is nothing wrong with the default-active value of the [Bug Report] nav menu component. Why is the drop - down box not automatically unfolded?

### ISSUE THREAD

**Issue by liubin595338764** [ElemeFE/element#4993]
### Element UI version
1.3.3

### OS/Browsers version
windows系统  /  chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/liubiner/2swy0e0q/](https://jsfiddle.net/liubiner/2swy0e0q/)

### Steps to reproduce
链接里面有两个列子，第一个列子正常。
第二个例子有问题：
default-active的值没有激活对应index的菜单，下拉框没有自动展开
https://jsfiddle.net/liubiner/2swy0e0q/

### What is Expected?
default-active的值激活对应index的菜单，下拉框自动展开

### What is actually happening?
default-active的值没有激活对应index的菜单，下拉框没有自动展开

**Comment by Leopoldthecoder** [comment]
`default-active` only **activates** (in other words, highlights) the corresponding menu item. It does not expand it.

To expand an item, use `default-openeds`: https://jsfiddle.net/2swy0e0q/3/
