### ISSUE TITLE
[Bug Report]When the paging component switches the page, why does the current page not change in real time?

### ISSUE THREAD

**Issue by chenyeah** [ElemeFE/element#4996]
### Existing Component
Yes

### Component Name
1.3.3

### Description
chrome58

https://jsfiddle.net/2j5jg6yp/1/

**Comment by chenyeah** [comment]
我的页面会变化 我想通过某种方法 把分页按钮还原到第一页

**Comment by chenyeah** [comment]
@Leopoldthecoder need help

**Comment by chenyeah** [comment]
重现步骤 ，不知道是不是Bug https://jsfiddle.net/2j5jg6yp/2/

**Comment by Leopoldthecoder** [comment]
你是需要 `currentpage1` 实时变化？

**Comment by chenyeah** [comment]
按道理 currentpage1 应当实时变化 经常有需要这种获取当前页面的需求

**Comment by Leopoldthecoder** [comment]
如果需要双向绑定，那么应该加上 `.sync` 修饰符。

**Comment by chenyeah** [comment]
文档是才加的吗，以前貌似没看见支持···.sync··· 修饰符。

**Comment by Leopoldthecoder** [comment]
`.sync` 是 Vue 的 2.2 版本中加入的，Element 在 1.3.0 中加入了支持。
