### ISSUE TITLE
element 全局引用出错

### ISSUE THREAD

**Issue by bigezhang** [ElemeFE/element#5]
cooking 创建vue2 项目，
然后npm install element-ui，
main.js 中
```
 import Vue from 'vue'
import Element from 'element-ui'
Vue.use(Element)

```

vue 文件中引入组件出错

**Comment by Leopoldthecoder** [comment]
请提供具体的引入代码和报错信息。

**Comment by bigezhang** [comment]
在main.js 中如下代码，全局引入组件
```
import Vue from 'vue'
import Element from 'element-ui'

Vue.use(Element)
```

而后某个vue 文件中使用<el-button></el-button>,
浏览器报错：
```
vue.common.js?e881:2503[Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build. (found in component <ElButton>)
```
请问是否还要其他配置？

**Comment by Leopoldthecoder** [comment]
请确认一下项目中 element-ui 的版本是 1.0.0-rc.1，如果不是，需要使用
```bash
npm install element-ui@next
```

**Comment by bigezhang** [comment]
可以了。thanks

**Comment by yuemeimei** [comment]
@bigezhang 你是怎么解决的？
![image](https://user-images.githubusercontent.com/23489614/29344364-d06043ac-8269-11e7-8e01-a7a86079a33d.png)
这是我的 报错信息
我的   webpack 还需要配置那些？ 你可以把你的配置发出来么？
![image](https://user-images.githubusercontent.com/23489614/29344378-ec6b1112-8269-11e7-9de1-bbe9f67b3ad7.png)
