### ISSUE TITLE
Element 组件调用 无法正常使用

### ISSUE THREAD

**Issue by xierenyuan** [ElemeFE/element#500]
### ElementUI version

0.2.6
### OS/Browers version

macOS  /53.0.2785.143 (64-bit)
### Vue version

2.0.1
### Steps to reproduce
使用cooking 构建的脚手架 中app.vue 使用如下代码
```html
<div>
        <div>this is template body11</div>
        <el-button type="primary">主要按钮</el-button>
    </div>
``` 
### What is Expected?

正常的显示按钮

### What is actually happening?
现在运行 按钮不显示 控制台中 出现如下错误
![image](https://cloud.githubusercontent.com/assets/7599351/19488109/14eee402-9598-11e6-9472-1b43b670c535.png)
注: 使用vue-cil 构建的以是同样效果  因为第一次使用 还是小白 期望得到你们的回复

**Comment by furybean** [comment]
应该是版本不对，使用这个安装：

```Bash
npm install element-ui@next -S
```
