### ISSUE TITLE
[Feature Request] 怎么设置el-tree加载数据后自动选中第一个节点

### ISSUE THREAD

**Issue by legendjslc** [ElemeFE/element#5007]
### Existing Component
是

### Component Name
tree

### Description
怎么设置el-tree加载数据后自动触发点击第一个节点的事件？
看现在的tree设计，似乎不好实现。
但自动选中某个节点应该是个很常用的功能。

**Comment by chenyeah** [comment]
@legendjslc  看文档 
![image](https://cloud.githubusercontent.com/assets/22478003/26340337/64330de0-3fc0-11e7-869e-bf3ac9a22e53.png)

**Comment by legendjslc** [comment]
好吧，我描述的有点问题，我的意思不是选中，
是树加载后自动触发点击第一个节点的事件。

**Comment by angeltxwh** [comment]
Mark，我也有这个问题，不过我现在的方法是设置了ref，然后直接操作this.refs['yourName']，直接修改内部属性，不知道是否合适

**Comment by Leopoldthecoder** [comment]
是指触发 `node-click`？

**Comment by legendjslc** [comment]
就是触发node-click

**Comment by Kingwl** [comment]
@Leopoldthecoder @QingWei-Li close this plz

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/6zb23pL9/

**Comment by legendjslc** [comment]
@Leopoldthecoder 你这个例子是一开始就有数据，这样做可以。如果数据是ajax加载的，怎么在节点更新完后自动点击第一个节点呢？

**Comment by legendjslc** [comment]
this.$nexttick(function(){
      const firstNode = document.querySelector('.el-tree-node')
      firstNode.click()
});

**Comment by slyang520** [comment]
如果是根据 KEY 来点击呢

**Comment by palmerye** [comment]
> @Leopoldthecoder 你这个例子是一开始就有数据，这样做可以。如果数据是ajax加载的，怎么在节点更新完后自动点击第一个节点呢？

``` javascript
watch: {
    menuData(val) {
        if (val) {
            this.$nextTick(() => {
                document.querySelector('.el-tree-node__content').click()
            })
        }
    }
}
```
