### ISSUE TITLE
[Bug Report] about el-cascader

### ISSUE THREAD

**Issue by wkyhy205104** [ElemeFE/element#5010]
### Element UI version
1.3.3

### OS/Browsers version
chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/sdc8j5ab/](https://jsfiddle.net/sdc8j5ab/)

### Steps to reproduce
when the el-cascader on the right of browser,and use one prop name's 'change-on-select';
click the cascader ,when the right width not enough, the selection area don't left translation.

### What is Expected?
when the right width not enough, the selection area can left translation.

### What is actually happening?
when the right width not enough, the selection area don't left translation.

**Comment by Leopoldthecoder** [comment]
Fixed in #5064
