### ISSUE TITLE
[Bug Report] table loading state does not scroll while scrolling the page and it`s run away

### ISSUE THREAD

**Issue by xcodebin** [ElemeFE/element#5016]
### Element UI version
1.3.3

### OS/Browsers version
win7 64

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/xcodebin/vbpyrsbc/1/#&togetherjs=myJVzp8cR6](https://jsfiddle.net/xcodebin/vbpyrsbc/1/#&togetherjs=myJVzp8cR6)

### Steps to reproduce
no step

### What is Expected?
loading just contain table 

### What is actually happening?
it`s run away .

![9m2c hnuyp1 gb46c b 5n](https://cloud.githubusercontent.com/assets/20456032/26341786/ebea8a7c-3fc7-11e7-9b56-67c39b36e1cf.png)

**Comment by Leopoldthecoder** [comment]
Remove the `body` modifier: https://jsfiddle.net/vbpyrsbc/2/
