### ISSUE TITLE
The [Bug Report] table component will have problems while using V-IF, slot, and template

### ISSUE THREAD

**Issue by DualWield** [ElemeFE/element#5017]
### Element UI version
1.3.3

### OS/Browsers version
macos/chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/szcnr8y9/](https://jsfiddle.net/szcnr8y9/)

### Steps to reproduce
点击toggle按钮

### What is Expected?
日期和姓名 交替出现

### What is actually happening?
只有列头变了，其他内容没变

**Comment by pengchongfu** [comment]
@DualWield it seems that it is the problem of vue `patch`.
how about add a key like [this](https://jsfiddle.net/szcnr8y9/1/)

**Comment by DualWield** [comment]
@pengchongfu Yes, it works for me. Thank you very much!
