### ISSUE TITLE
请问，怎么改变tree选中节点的高亮效果？

### ISSUE THREAD

**Issue by Sher9** [ElemeFE/element#5018]
rt,现在默认选中高亮效果是淡青色，觉得太淡了，想要对效果进行一些自定义。

**Comment by ahuang** [comment]
我实现方案是:  
                @node-drag-enter="handleDragEnter"
                @node-drag-leave="handleDragLevel"
进入目标节点时，添加节点背景色
离开目标节点时，移除节点背景色
