### ISSUE TITLE
[Bug Report] el-dropdown contains el-select, and clicking select option hides el-dropdown

### ISSUE THREAD

**Issue by fastCreator** [ElemeFE/element#5030]
### Element UI version
1.3.4

### OS/Browsers version
chorm

### Vue version
2.3.3

### Reproduction Link
[http://jsfiddle.net/cocosCreator/283fauh2/1/](http://jsfiddle.net/cocosCreator/283fauh2/1/)

### Steps to reproduce
1，点击下拉菜单
2，点击select,
3，结果下拉菜单隐藏了，
期望：不隐藏

### What is Expected?
期待：el-dropdown 包含el-select 点击select option 不会隐藏 el-dropdown

### What is actually happening?
popover  包含el-select 点击select option 是不会隐藏 el-dropdown
 因为popover除了判断组件本身，还判断了slot
this.$el.contains(e.target) ||
 reference.contains(e.target) ||
el-dropdown只判断了组件本身，是否考虑，把子组件也遍历判断

**Comment by Leopoldthecoder** [comment]
Use `hide-on-click`: http://jsfiddle.net/283fauh2/2/
