### ISSUE TITLE
[Bug Report] row-class-name method called multiple times

### ISSUE THREAD

**Issue by vinh123456789** [ElemeFE/element#5032]
### Element UI version
1.3.4

### OS/Browsers version
Windows 10 64bit

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pb66aock/1/](https://jsfiddle.net/pb66aock/1/)

### Steps to reproduce
Create a table with 'row-class-name' attribute, add 'console.log(1)' to 'row-class-name' method

### What is Expected?
console should only log once for each row

### What is actually happening?
console log 4 times for each row

**Comment by Leopoldthecoder** [comment]
Ideally, it should be called only once for each row. But due to the current implementation, multiple calls are inevitable.

**Comment by panghuiaaa** [comment]
目前还存在这样的问题，请问有优化么
