### ISSUE TITLE
[Bug, Report], table, show-summary total

### ISSUE THREAD

**Issue by vipplus** [ElemeFE/element#5034]
### Element UI version
1.3.4

### OS/Browsers version
chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/n5w51uaj/](https://jsfiddle.net/n5w51uaj/)

### Steps to reproduce
fixed column

### What is Expected?
fixed column

### What is actually happening?
fixed column

**Comment by Leopoldthecoder** [comment]
Closing for lack of information.
