### ISSUE TITLE
[Bug Report] input-number formatted values

### ISSUE THREAD

**Issue by vipplus** [ElemeFE/element#5035]
### Element UI version
1.3.4

### OS/Browsers version
chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/x9L4d9h7/](https://jsfiddle.net/x9L4d9h7/)

### Steps to reproduce
将结果四舍五入（toFixed）后，重新显示值

### What is Expected?
将结果四舍五入（toFixed）后，重新显示值

### What is actually happening?
看了input-number的源码，应该是change事件和赋值顺序有问题，和input的顺序不一样

**Comment by wacky6** [comment]
把`v-model`换成`:value`做单向绑定试试。如果有必要可以自己处理input和change事件
https://jsfiddle.net/3rbjfhgr/

**Comment by Leopoldthecoder** [comment]
请参考 #3762 和楼上的回复。
