### ISSUE TITLE
The [Bug Report] call Message.close () does not properly close the Message

### ISSUE THREAD

**Issue by ThinkRealize** [ElemeFE/element#5037]
### Element UI version
1.3.4

### OS/Browsers version
OSX10.10.5 / Chrome 58

### Vue version
2.3.3

### Reproduction Link
[不好意思。使用，import { Message } from 'element-ui';报错，不知道该如果单独引用 。https://jsfiddle.net/oqgkvxju/ ](不好意思。使用，import { Message } from 'element-ui';报错，不知道该如果单独引用 。https://jsfiddle.net/oqgkvxju/ )

### Steps to reproduce
let message = Message('调用')
Message.close(message.id) 关闭 Message。

### What is Expected?
Message 将被关闭。

### What is actually happening?
调用 Message.closeAll 可以正确关闭 Message。调用 Message.close 不能关闭。

Message.close 是直接将 instance 从 instances 中移除。
Message.closeAll 最终调用 instance.close() 关闭 Message。

以下是 Message 的源码

Message.close = function(id, userOnClose) {
for (let i = 0, len = instances.length; i < len; i  ) {
if (id === instances[i].id) {
if (typeof userOnClose === 'function') {
userOnClose(instances[i]);
}
instances.splice(i, 1);
break;
}
}
};

Message.closeAll = function() {
for (let i = instances.length - 1; i >= 0; i--) {
instances[i].close();
}
};

**Comment by jikkai** [comment]
试下来没有问题
[https://jsfiddle.net/oqgkvxju/1/](https://jsfiddle.net/oqgkvxju/1/)

**Comment by Leopoldthecoder** [comment]
@ThinkRealize 请参考楼上的回复整理一个能复现的 demo。

**Comment by ThinkRealize** [comment]
不好意思，我理解错了 Message 的设计意图。关闭组件不是用调用Message.close(id, userOnClose) 。
我将关闭这个 issue。
题外话：Element 设计的真好，我为他的美而心醉。
