### ISSUE TITLE
[Bug Report] 动态切换DatePicker的type时，下拉面板UI出现异常

### ISSUE THREAD

**Issue by Eamonnzhang** [ElemeFE/element#5040]
### Element UI version
1.3.4

### OS/Browsers version
Mac OS 10.12.4 / Chrome  58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/imeamonnzhang/cvdLd69n/](https://jsfiddle.net/imeamonnzhang/cvdLd69n/)

### Steps to reproduce
1.点击日期选择出现下拉框（默认type为date，此时下拉面板正常）
2.直接点击单选按钮为其他任意一个选项（非日），日期下拉面板消失
3.点击日期选择出现下拉框，下拉框宽度不正常

### What is Expected?
通过动态切换type时，datepicker下拉面板能够正常显示

### What is actually happening?
通过动态切换type时，datepicker下拉面板不正常显示
【注意：有一种方式切换是正常的，就是先通过其他方式让日期下拉面板消失（比如随便点击空白处），然后在切换type，这个时候在点击日期下拉框，面板就正常了，如果直接通过切换type来使datepicker消失，下拉面板就不正常】

**Comment by Leopoldthecoder** [comment]
Duplicate of #4905
