### ISSUE TITLE
The drop-down menu cannot be retrieved after the [Bug Report] select component adds the filterable property

### ISSUE THREAD

**Issue by wisewrong** [ElemeFE/element#5044]
### Element UI version
1.2.8

### OS/Browsers version
Win7 / Chrome 58

### Vue version
2.1.10

### Steps to reproduce
创建 <el-select> 组件，并添加 filterable 属性。
点击箭头图标展开下拉菜单，再次点击箭头图标时，无法收起下拉菜单（点击输入框能正常收起）

### What is Expected?
打开下拉菜单后，再次点击箭头图标能收起下拉菜单

### What is actually happening?
打开下拉菜单后，再次点击箭头图标不能收起下拉菜单

**Comment by Leopoldthecoder** [comment]
Fixed in #6151
