### ISSUE TITLE
[Bug Report] element UI DateTimePicker limit time can only be limited to date, can not limit the specific time?

### ISSUE THREAD

**Issue by boychina** [ElemeFE/element#5045]
### Element UI version
1.3.4

### OS/Browsers version
win10/chrome58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
限制DateTimePicker的选择时间为最大为当前时间，日期是做了正确的限制，但是时分秒可以选择到当前时间之后的时间。

### What is Expected?
限制组件时间选择的后时间为当前时间，日期是进行了正确的限制，并且时间也不能选择到未来的时分秒。

### What is actually happening?
日期进行了正确的限制，但是时分秒可以选择到当天未来的时间。

**Comment by wacky6** [comment]
给的jsfiddle好像不太对啊。@boychina

**Comment by Dreamacro** [comment]
Fixed in #6076

**Comment by chenluli** [comment]
请问一下有没有限制时间选择的demo，我目前还是不能限制到时间。

**Comment by koucxz** [comment]
@Dreamacro 请问能否给出一个可以限制小时分钟的demo，仍未找到如何限制

**Comment by ShawshankLin** [comment]
@Dreamacro 请问能否给出一个可以限制小时分钟的demo，仍未找到如何限制

**Comment by Dreamacro** [comment]
@ShawshankLin @koucxz 现在没有办法直接限制 datetimepicker 的时分秒，需要的话可以在提交前对日期进行一次校验

**Comment by ShawshankLin** [comment]
> @ShawshankLin @koucxz 现在没有办法直接限制 datetimepicker 的时分秒，需要的话可以在提交前对日期进行一次校验

比如只要小时不选择分钟不行吗？
