### ISSUE TITLE
[Bug Report] el-autocomplete mouse copy select input is beyond the input box suggestionVisible=false

### ISSUE THREAD

**Issue by Borkes** [ElemeFE/element#5046]
### Element UI version
1.2.8

### OS/Browsers version
windows/chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/g4mssgLh/)

### Steps to reproduce
在el-autocomplete中输入查询字段远程搜索, 然后用鼠标左键复制全选,并放开鼠标左键时鼠标不在输入框内, suggestionVisible由true变成false, 此时再输入,下拉框无法展示远程已返回的数据

### What is Expected?
任何时候,输入搜索字段都应该下拉展示远程返回数据

### What is actually happening?
在el-autocomplete中输入查询字段远程搜索,然后用鼠标左键复制全选,并放开鼠标左键时鼠标不在输入框内, suggestionVisible由true变成false, 此时再输入,下拉框无法展示远程已返回的数据;
element-ui  1.0.5版本测试的时候el-autocomplete获得焦点后suggestionVisible就是true,然后下拉展示数据

**Comment by pengchongfu** [comment]
@Borkes , see #4985 
It was fixed in latest `dev` branch.
