### ISSUE TITLE
BUG: Dialog cannot be closed if computed variable is used for visability

### ISSUE THREAD

**Issue by peiphb02** [ElemeFE/element#5047]
### Element UI version
1.3.4

### OS/Browsers version
Windows / Chrome 57.0.2987.133

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/TSBPhil/pj71jkyw/227/](https://jsfiddle.net/TSBPhil/pj71jkyw/227/)

### Steps to reproduce
1.) Create a dialog
2.) use computed variable for :visible.sync instead of data variable

dialog cannot be closed through "x" or by clicking outside the dialog.
it works if you use data variable instead of computed variable.

### What is Expected?
Dialog should be closed after clicking "X" or by clicking outside the dialog.

### What is actually happening?
Dialog is not closed.

**Comment by Leopoldthecoder** [comment]
#4955 #4708
