### ISSUE TITLE
[Feature, Request], Hope, to, add, form-group, in, ElForm

### ISSUE THREAD

**Issue by ChrisShen93** [ElemeFE/element#5048]
### Existing Component
是

### Component Name
ElForm

### Description
It is very useful to add the feature 'form-group' in the component.

For now, I can only use inline mode as an attribute of el-form. Hope to use inline mode for 'form-group', so that I can make form more flexible.

给ElForm添加 'form-group' 会是一项很有用的特性。
目前，举个例子，如果我想使用行内表单的话，整个form都会变为行内表单的样式。如果可以加上 'form-group'，那么我就可以对每个 'form-group' 指定是否 inline，这会使得我的表单可以设计得更灵活。

**Comment by baiyaaaaa** [comment]
You can implement it in your project easily actually. `el-form` can contain not only the `el-form-item` component.
