### ISSUE TITLE
[Bug Report] table with show-overflow-tooltip cannot display tooltip properly

### ISSUE THREAD

**Issue by wisewrong** [ElemeFE/element#5049]
### Element UI version
1.3.4

### OS/Browsers version
Win7 / Firefox 48.0, IE 11

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/761/](https://jsfiddle.net/pj71jkyw/761/)

### Steps to reproduce
1. 给单元格添加 show-overflow-tooltip 属性
2. 当单元格的字段长度超过宽度，单元格出现省略号;
3. 被隐藏的字段为一个或者两个中文字符；
4. 在 火狐浏览器 和 IE 中无法正常显示 tooltip（谷歌浏览器能正常显示）

### What is Expected?
在 Firefox 和 IE 中也能正常显示

### What is actually happening?
当隐藏的字段为两个字符长度时，hover 无法显示 tooltip

**Comment by muzi131313** [comment]
这个bug什么时候能修复呢？

**Comment by muzi131313** [comment]
看了下源码，是scroll-width和offset-width，没有滚动条下，在chrome和firefox、ie中表现不一样。chrome中是okay的，firefox和ie中两者值一样。

**Comment by SHERlocked93** [comment]
在下在判断cellChild.scrollWidth与cellChild.offsetWidth的地方增加了个判断是否IE的丑陋方法，不过带来的影响就是所有IE设置了show-overflow-tooltip=true的列都会有tooltip，只能算临时办法了...
期待修复啊~
```js
// element-ui > lib > element-ui.common.js 的行8998
var isIE= !!window.ActiveXObject || "ActiveXObject" in window   // 检测是否是IE
if ((0, _dom.hasClass)(cellChild, 'el-tooltip') && (cellChild.scrollWidth > cellChild.offsetWidth || isIE)) {
    ...
}
```

**Comment by haogjin** [comment]
there is another way can resolve this problem.
<template slot-scope="scope">
    <span  @mouseenter="handleShowTooltip($event)">
       <el-tooltip :disabled="showTooltip" :content="scope.row.location" placement="top" :open-delay="300">
            <div  class="tootip-style">{{scope.row.location}}</div>
        </el-tooltip>
    </span>
</template>
<script>
export default {
    data() {
        return {      
            showTooltip:false,
        }
    },
   methods: {
        handleShowTooltip(event){
              let cell = event.target.querySelector('.el-tooltip');
              this.showTooltip = cell.scrollWidth === 	cell.offsetWidth && cell.scrollHeight === cell.offsetHeight;
       }
   }
}
</script>
<style>
    .tootip-style{
        overflow:hidden;
        white-space:nowrap;
        text-overflow:ellipsis;
        -o-text-overflow:ellipsis;
        -icab-text-overflow: ellipsis;
        -khtml-text-overflow: ellipsis;
        -moz-text-overflow: ellipsis;
        -webkit-text-overflow: ellipsis;
    }
</style>
注：
1.直接采用el-tooltip的disable属性 css控制文本过长显示省略号
2.根据长度大小比较判断是否显示tooltip
3.注意采用延时 因为改变过程需要一定的时间 迅速移动的话就会显示有点问题
4.可直接封装成组件

**Comment by iceash** [comment]
提供一个丑陋的解决思路，既然是省略内容过少引起的BUG，那么可以在想要输出的字符串后面加上 &nbsp;&nbsp;

Provide an ugly solution, since it is an error caused by omitting too little content, then you can add ' &nbsp;&nbsp;' after the string you want to output.

**Comment by longchenweb** [comment]
自己写个指令吧，参考：https://www.jianshu.com/p/9ad876e2daa3
但是需要改造下，textSpan.offsetWidth >= el.offsetWidth，加上=，然后把鼠标移入移出事件处理移出来，这段判断放到鼠标移入事件中

`Vue.directive('tip', {
      inserted(el) {
        let $div;
        el.addEventListener('mouseover', e => {
          const curStyle = window.getComputedStyle(el, '') // 获取当前元素的style
          const textSpan = document.createElement('span') // 创建一个容器来记录文字的width
          // 设置新容器的字体样式，确保与当前需要隐藏的样式相同
          textSpan.style.fontSize = curStyle.fontSize
          textSpan.style.fontWeight = curStyle.fontWeight
          textSpan.style.fontFamily = curStyle.fontFamily
          // 将容器插入body，如果不插入，offsetWidth为0
          document.body.appendChild(textSpan)
          // 设置新容器的文字
          textSpan.innerHTML = el.innerText;
          if (textSpan.offsetWidth >= el.offsetWidth) {
            let top = e.clientY - e.offsetY,
                left = e.clientX - e.offsetX + e.target.clientWidth/2;
            $div = document.createElement('div')
            $div.setAttribute('class', 'site-tips')
            $div.setAttribute('style', 'top:' + top + 'px;left:' + left + 'px')
            $div.innerHTML = el.innerText
            document.body.appendChild($div)
          }
          // 移除刚刚创建的记录文字的容器
          document.body.removeChild(textSpan)
        })
        el.addEventListener('mouseout', e => {
          if($div) {
            try {
              document.body.removeChild($div)
            } catch(e) {
            }
          }
        })
      }
    })`
