### ISSUE TITLE
Can [Feature Request] increase the clearable event callback for select?

### ISSUE THREAD

**Issue by Simonalia** [ElemeFE/element#5050]
### Existing Component
是

### Component Name
select

### Description
感谢大神抽出时间看我的问题~做项目遇到了一个小问题。
清空select时，一般会有两种方法：
①用户点击清空按钮
②对select绑定的data赋null或空字符串
而有时候用户点击清空按钮时会触发事件回调，而这个回调只用select提供的change事件没法很好的区分上述两种情况，想问大神有没有什么方法解决

**Comment by Leopoldthecoder** [comment]
Added a new event `clear` in #5112
