### ISSUE TITLE
[Bug Report] in IE9 browser, dialog contains select, second pop-up dialog, click Select, el-select-dropdown will be blocked by dialog

### ISSUE THREAD

**Issue by HoffyLee** [ElemeFE/element#5051]
### Element UI version
1.3.4

### OS/Browsers version
windows 7 / IE9

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/234/](https://jsfiddle.net/pj71jkyw/234/)

### Steps to reproduce
1、打开dialog对话框，点击dialog对话框上的select选择框，正常显示下拉列表，关闭dialog弹层；
2、再次打开dialog对话框，点击dialog对话框上的select选择框，下拉列表被dialog对话框遮挡

### What is Expected?
在IE9浏览器中，每次点击dialog对话框内的select组件，下拉列表都能正常显示

### What is actually happening?
在IE9浏览器中，第二次及以后打开dialog对话框，点击select组件时，下拉列表被遮挡

**Comment by roy-lau** [comment]
@HoffyLee         看这  https://jsfiddle.net/pj71jkyw/234/

**Comment by HoffyLee** [comment]
是改了el-option的value就没有问题了么？我现在IE9打不开链接来看，你可以试一下在IE9打开http://element.eleme.io/#/zh-CN/component/dialog  里面的“打开嵌套表单的dialog”验证一下，谢谢哈

**Comment by roy-lau** [comment]
是value的问题，跟IE没什么关系！

**Comment by HoffyLee** [comment]
感觉不是value的问题，把value换成你那种，下拉菜单还是会被dialog遮挡

**Comment by roy-lau** [comment]
那我就不知道了，IE9我没有！:grimacing:

**Comment by HoffyLee** [comment]
好吧，还是谢谢你了
