### ISSUE TITLE
The use of v-loading on dialog components on [Bug Report] causes dialog to disappear

### ISSUE THREAD

**Issue by plilion** [ElemeFE/element#5052]
### Element UI version
1.3.4

### OS/Browsers version
chrome v56

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/plilion/dkua1pmg/](https://jsfiddle.net/plilion/dkua1pmg/)

### Steps to reproduce
在dialog组件上使用v-loading 
当v-loading 状态为 true 时
会导致 dialog 消失

### What is Expected?
dialog 不会消失 且正确加载loading 状态

### What is actually happening?
在dialog组件上使用v-loading 
当v-loading 状态为 true 时
会导致 dialog 消失

**Comment by Leopoldthecoder** [comment]
In this case, please use loading service instead: https://jsfiddle.net/dkua1pmg/1/ . The outmost tag of `<el-dialog>` is not the dialog body itself.

**Comment by plilion** [comment]
THX
