### ISSUE TITLE
使用el-menu组件做二级菜单时 显示当前 :default-active="onRoutes"

### ISSUE THREAD

**Issue by 422656004** [ElemeFE/element#5059]
computed:{
      onRoutes() {        
        return this.$route.path.replace('/','');
      }
    }

所属的一级菜单会加上 el-submenu is-active is-opened
如果el-menu上面的数据是异步请过过来的时候 所属的一级菜单会加上 el-submenu is-active 但是
is-opened 就不会被加上；不知道如何处理

**Comment by CYvonne** [comment]
我也遇到这个问题，而且在线运行官方例子是没问题的，很奇怪。目前解决方法是再加个default-openeds属性。
