### ISSUE TITLE
[BUG]日期时间组件点击确定后没有将值填入

### ISSUE THREAD

**Issue by pixcai** [ElemeFE/element#506]
现在的日期时间组件可以选中日期，也不会溢出。但是点击确定后，没有将值填入输入框。

另外：
![image](https://cloud.githubusercontent.com/assets/11440779/19507389/19222922-9605-11e6-8baa-a4a1a6aa773b.png)
![image](https://cloud.githubusercontent.com/assets/11440779/19507395/2b7364f6-9605-11e6-8eeb-05196993e225.png)

界面小的话，绝对定位的div块会布局错乱

**Comment by furybean** [comment]
『界面小的话，绝对定位的div块会布局错乱』这是 popper.js 的一个特性，尽量让你看到你的弹出内容，会把弹出内容放到合适的可见区域。

**Comment by QingWei-Li** [comment]
我不确定修复了没有 麻烦你再试试？@pixcai https://elementui.github.io/dev/#/component/datetime-picker

**Comment by pixcai** [comment]
现在可以了。
