### ISSUE TITLE
[Bug Report] auto-complete makes v-model not work

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#5062]
### Element UI version
1.3.4

### OS/Browsers version
all

### Vue version
2.3.3

### Reproduction Link
[https://github.com/zzzgit/dialogCannotClose](https://github.com/zzzgit/dialogCannotClose)

### Steps to reproduce
1.input in the el-input component
2.the model been bound will not been muted correspondingly
3.remove the auto-complete attribute from the child.vue file
4.the model will work correctly

### What is Expected?
no

### What is actually happening?
no

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/6y3sjhn0/
Seems working.
