### ISSUE TITLE
[Bug Report] Select "default-first-option" Not Work with "filterable remote" Attributes, but Success Only with "filterable"

### ISSUE THREAD

**Issue by kevinheyo** [ElemeFE/element#5063]
### Element UI version
1.3.4

### OS/Browsers version
Win 7 / Chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/o4be623j/](https://jsfiddle.net/o4be623j/)

### Steps to reproduce
There are 2 select components in this Jsfiddle.

The left one only contains "filterable" attribute. You can key "A" and press Enter to select the first option.

The right one contains both "filterable" and "remote" attributes, and the "default-first-option" doesn't work !!

### What is Expected?
The Select Component with "filterable" and "remote" attributes should work properly with "default-first-option" attribute.

### What is actually happening?
Can't use enter to select the first option.

**Comment by Leopoldthecoder** [comment]
@wacky6 Is `default-first-option` not supposed to be working with `remote`?

**Comment by wacky6** [comment]
Seems it does not work when drop-down list opens for the first time.
Will look into it.

**Comment by wacky6** [comment]
@kevinheyo 
Please verify: https://jsfiddle.net/4fkLahzf/1/

Forgot to deal with async remote/filter method when I first implemented this feature.

**Comment by kevinheyo** [comment]
@wacky6 
I can select the first option now. Thank you very much!
