### ISSUE TITLE
Incomplete [Feature, Request], el-tree documents

### ISSUE THREAD

**Issue by strongfanfan** [ElemeFE/element#5069]
### Existing Component
是

### Component Name
el-tree

### Description
文档不全，treeStore下编辑节点的方法没有文档说明

**Comment by Leopoldthecoder** [comment]
Are you referring to `append` and `remove` of this example: http://localhost:8085/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong ?
