### ISSUE TITLE
[BUG]日期时间范围选择组件

### ISSUE THREAD

**Issue by DevilLeven** [ElemeFE/element#507]
日期时间范围选择组件 ，在window chrome 浏览器中 日期表格，非常难选中 (date-table.vue)

**Comment by DomenLee** [comment]
这个解决了吗,刚试了下,还是存在该问题

**Comment by furybean** [comment]
@DomenLee 使用开发版本能重现么？ https://elementui.github.io/dev/#/component/datetime-picker

**Comment by DomenLee** [comment]
@furybean 现在很顺畅了, good job
