### ISSUE TITLE
[Bug Report]how to get the ref value in the callback method when unsure of the number of el-upload?

### ISSUE THREAD

**Issue by angeltxwh** [ElemeFE/element#5071]
### Element UI version
1.3.4

### OS/Browsers version
WIN10/CHROME56

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/245/](https://jsfiddle.net/pj71jkyw/245/)

### Steps to reproduce
随便点任意次增加按钮（二三四五次都可以），然后点击任意一个上传组件的上传按钮来上传文件，传完后会在浏览器console打印handler收到的参数，但是这个参数里并没有包括来自于哪个el-upload？

### What is Expected?
期望能识别ref，传进来ref，也好做数据处理

### What is actually happening?
没有传入ref

**Comment by Leopoldthecoder** [comment]
这种情况当然是让 handler 回调接收一个标记是哪个 Upload 的参数：https://jsfiddle.net/pj71jkyw/250/
