### ISSUE TITLE
[Bug Report] el-checkbox-group not working with Vuex

### ISSUE THREAD

**Issue by farcasmihai91** [ElemeFE/element#5073]
### Element UI version
1.3.3

### OS/Browsers version
Windows / Chrome 57.0.2987.133

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/5u6gb339/](https://jsfiddle.net/5u6gb339/)

### Steps to reproduce
Use ```:value``` and ```@change``` on checkbox-group instead of ```v-model```.
See jsfiddle.
You can't use ```v-model``` with Vuex, you need to use ```:value``` and ```@change```, so in conclusion the el-checkbox-group does not work with Vuex.

### What is Expected?
The ```@change``` should be the new values, even if ```:value``` is already set.
```@change``` should trump ```:value``` like it does on the el-input for example.
I have provided in the link to reproduce, how the el-input works in contrast.

### What is actually happening?
The el-checkbox-group. 
```:value``` overwrites ```@input```

Thank you!

**Comment by baiyaaaaa** [comment]
U should use the 'input' event insteadof 'change'
