### ISSUE TITLE
The [Feature Request] form dynamically adds forms (V-model consistent with the form) and how to configure form validation

### ISSUE THREAD

**Issue by hasbug** [ElemeFE/element#5079]
### Existing Component
是

### Component Name
form

### Description
场景如下：
我有个日历，我选择日期范围后会生成多个日期，每个日期配置一个input表单进行填写销售价格。这时候v-model的值是一样的。我写了校验规则是必填。如果我在一开始的rules配置了这个规则，在表单动态生成多个的时候，无论表单是否全部写完正确的价格，都会报值是必填项。prop都一样、v-model也一样，如果我动态生成rules中多个规则和prop一致的时候，也是无法通过校验，这个v-model是必须一致的。

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
