### ISSUE TITLE
After [Feature Request] Table's filters filter, can the meter be displayed as filtered fields?

### ISSUE THREAD

**Issue by rikushikin** [ElemeFE/element#5088]
### Existing Component
Yes

### Component Name
Table-column

### Description
当filter-multiple为false也就是单条过滤的时候，能否设置个prop让表头显示为当前过滤的字段

**Comment by Leopoldthecoder** [comment]
No. If you must, you can try `render-header`, but in this way you'll have to write all filtering code yourself.
