### ISSUE TITLE
[Bug Report], el-form in the v-else branch, does not trigger data validation

### ISSUE THREAD

**Issue by wangjiangman** [ElemeFE/element#5090]
### Element UI version
1.3.4

### OS/Browsers version
Win7 Chorme

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/fiona914/e601d7c3/](https://jsfiddle.net/fiona914/e601d7c3/)

### Steps to reproduce
两个el-form分别处于v-if和v-else分支；
对于v-else分支的el-form绑定rules验证

### What is Expected?
触发验证

### What is actually happening?
验证不触发

**Comment by wangjiangman** [comment]
刚刚进行了验证，发现是blur不触发，但是this.$refs['editForm']是触发验证的。

**Comment by Leopoldthecoder** [comment]
Apparently the `v-else` Form is cached and re-used, so its initiation won't run when `checkView` is changed. Add `key`s to both Forms fixes this: https://jsfiddle.net/e601d7c3/1/

More details can be found here: https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

**Comment by wangjiangman** [comment]
I got it， I should read the Vuejs document more carefully. Thank you !
