### ISSUE TITLE
The values of [Bug, Report], input, currentValue, and value are different, causing the page to display errors

### ISSUE THREAD

**Issue by layne0625** [ElemeFE/element#5092]
### Element UI version
1.2.9

### OS/Browsers version
Chrome

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/layne0625/1k168u90/](https://jsfiddle.net/layne0625/1k168u90/)

### Steps to reproduce
1.先输入数字，然后输入非数字字符，会自动变成0；
2.变成0之后，再次输入非数字时，不会重置成0。
3.打开开发者工具，发现绑定的v-model确实是变成0了，只是currentValue并不是v-model的值了。导致currentValue和v-model的值不同。用原生input是不会有这样的bug

### What is Expected?
变成0之后再次输入非数字字符时也应该置为0

### What is actually happening?
输入非数字字符之后不会变成0

**Comment by pengchongfu** [comment]
@layne0625 https://jsfiddle.net/1k168u90/1/

for more detail you can see #3595

**Comment by Leopoldthecoder** [comment]
Thanks @pengchongfu
