### ISSUE TITLE
Popover优化建议

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/element#510]
在触发方式是：“hover”时
鼠标离开触发弹出框的元素后，弹出框就关闭了，
但，弹出框内有时候会有一些按钮做后续操作，这时就点击不到按钮

可否实现鼠标离开触发元素并进入弹出框内时，弹出框一直保持，鼠标离开弹出框，弹出框关闭

**Comment by QingWei-Li** [comment]
可以到开发版网站上看看有无问题 https://elementui.github.io/dev/
