### ISSUE TITLE
The [Bug Report] Select component fires change events multiple times in a Table component.

### ISSUE THREAD

**Issue by baijunjie** [ElemeFE/element#5100]
### Element UI version
1.3.4

### OS/Browsers version
windows7 / chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/e5e19p8w/](https://jsfiddle.net/e5e19p8w/)

### Steps to reproduce
为 Table 组件添加锁定列后，表格中的 select 组件再每次选择时的 change 事件会触发2次，如果分别为表格添加左右锁定列，则 change 事件会触发3次！

### What is Expected?
 select 组件在每次选择时的 change 事件应该只触发1次。

### What is actually happening?
当表格分别添加了左右锁定列时，select 组件在每次选择时的 change 事件会触发3次。

**Comment by baijunjie** [comment]
不止 change 事件，表单验证也会执行3次！

**Comment by Leopoldthecoder** [comment]
#3965
