### ISSUE TITLE
[Bug Report] [Table] el-table-column label property can't analysis "A.b"  

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#5101]
### Element UI version
1.3.4

### OS/Browsers version
chrome  58.0.3029.110 

### Vue version
2.3.3

### Reproduction Link
[https://codepen.io/anon/pen/BREeyb](https://codepen.io/anon/pen/BREeyb)

### Steps to reproduce
```js 
var Main = {
  template: `
  <el-table   :data="resultData"   stripe    style="width: 100%"    >
              <el-table-column v-for="(item,key,index) in resultData[0]" :prop="key"
                                :label="key">
                </el-table-column>
    </el-table>
  `,
  data(){
    return {
      resultData:[{"firstname":"Hattie","name":"Bond","a.gender":"M","dname":"snoopy","value":"36"},{"firstname":"Daenerys","name":"Targaryen","a.gender":"M","dname":"rex","value":"32"}]
    }
  }
}

new Vue({
  el: '#app',
  render: h => h(Main)
})
```

### What is Expected?
can show "a.gender"  column to 'M'

### What is actually happening?
can not show
![image](https://cloud.githubusercontent.com/assets/1932350/26519081/9a271820-42ee-11e7-9139-88cf4107a8f7.png)

**Comment by Leopoldthecoder** [comment]
This is not a bug. 'a.gender' will work if the data is
```javascript
resultData: [{
  "firstname":"Hattie",
  "name":"Bond",
  "a": {
    "gender":"M"
  },
  "dname":"snoopy",
  "value":"36"
}, {
  "firstname":"Daenerys",
  "name":"Targaryen",
  "a": {
    "gender":"M"
  },
  "dname":"rex",
  "value":"32"
}]
```

When parsing a `prop` with dots, Table will consider it as a nested property rather than a literal one.

**Comment by sash113** [comment]
@Leopoldthecoder 
Maybe it should be implemented as custom column option? Let's say 'allow-dot-prop-name'  ? 
For example this feature implemented in [ag-grid](https://www.ag-grid.com/javascript-grid-properties) as 'suppressFieldDotNotation'

**Comment by dolphinfine** [comment]
可以采取
` <template slot-scope="scope">
       {{scope.row[a.gender]}}
 </template>`
的方式解决这个问题。

**Comment by tonyeggers** [comment]
> @Leopoldthecoder I think this situation is a certain business scenario. Because if the data structure is returned from the backend, the database can store fields with dot.
> 
> If we can add an attribute to el-table-column (eg suppressFieldDotNotation). If true, then dots (eg `a.gender`) in field names are not treated as deep references. Allows you to use dots in your field name if you prefer.

This is it exactly. When working with certain backend platforms (e.g. Salesforce), JSON results can include a period in the property name based on the nature of backend query references. It is dealt with in Javascript by enclosing the property in [] (e.g. a['gender']. We need this type of capability when passing in props for field names.

**Comment by tonyeggers** [comment]
It seems the only workaround is to just rename the field in the array causing the problem. Not really optimal performance-wise, especially for larger tables.

dataTabe.forEach( function(data) {
  data['a-gender'] = data['a.gender'];
  delete data['a.gender'];
});

Then you can use 'a-gender' as a prop for the column.
