### ISSUE TITLE
[Bug, Report], el-select, Component, when, value, is, a, number, validation, will, fail.

### ISSUE THREAD

**Issue by MicyToy** [ElemeFE/element#5102]
### Element UI version
1.3.3

### OS/Browsers version
windows all, chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/jn4u46db/](https://jsfiddle.net/jn4u46db/)

### Steps to reproduce
Select "活动区域"，you will see invalid message "请选择活动区域".

### What is Expected?
el-option support number value

### What is actually happening?
havn't support

similar issue #3470

**Comment by Leopoldthecoder** [comment]
You need to explicitly declare its type as `number`: https://jsfiddle.net/jn4u46db/1/

**Comment by gimyboya** [comment]
@Leopoldthecoder Please add that to the documentation it took me so much time to figure it out because my code seems clean and it was not mentioned in the documentation

**Comment by Leopoldthecoder** [comment]
@gimyboya http://element.eleme.io/#/en-US/component/form#number-validate
