### ISSUE TITLE
[Bug Report] Expression always be true

### ISSUE THREAD

**Issue by chikara-chan** [ElemeFE/element#5104]
### Element UI version
1.3.4

### OS/Browsers version
Chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/table/src/table.vue#L9](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table.vue#L9)

### Steps to reproduce
From my code review

### What is Expected?
Add row transition when data size between 0 and 100

### What is actually happening?
Expression always be true

**Comment by Leopoldthecoder** [comment]
Fixed in #5109
