### ISSUE TITLE
[Bug Report] questions about the time zone of date-picker

### ISSUE THREAD

**Issue by emodo** [ElemeFE/element#5107]
### Element UI version
1.3.1

### OS/Browsers version
Mac / Chrome 58.0.3029.110 (64-bit)

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/emodo/000jy7qm/](https://jsfiddle.net/emodo/000jy7qm/)

### Steps to reproduce
比如说时区设置为日本，选择日期为5月24日，但是转成中国时间变为了23日
很奇怪为什么所有时间变成了0，而没有按照国际标准时间返回

### What is Expected?
期待输出 Wed May 24 2017 09:00:00 GMT 0900 (JST)

### What is actually happening?
实际输出为 Wed May 24 2017 00:00:00 GMT 0900 (JST)

**Comment by smackgg** [comment]
+1

**Comment by emodo** [comment]
#5134

**Comment by Kingwl** [comment]
@Leopoldthecoder 大佬在勤奋的修Bug orz

**Comment by Leopoldthecoder** [comment]
@Kingwl 今天要发版= =

**Comment by emodo** [comment]
@Leopoldthecoder 这个不放到更新日志里吗？
