### ISSUE TITLE
[Bug Report] Bug in el-table sort-method

### ISSUE THREAD

**Issue by glittle** [ElemeFE/element#5117]
### Element UI version
1.3.4

### OS/Browsers version
Chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/2mjjx3n8/1/](https://jsfiddle.net/2mjjx3n8/1/)

### Steps to reproduce
See jsfiddle.

### What is Expected?
Sort should work.

### What is actually happening?
First or last row is not sorted.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/2mjjx3n8/3/

The returned value of `sort-method` is supposed to be a boolean instead of 1, 0 and -1. This is different from `Array.sort`. I'll update the documentation to address this.

**Comment by dmrickey** [comment]
The documentation is still wrong (or wrong again)

**Comment by hcnhatnam** [comment]
Remove immediately this post, please!!!      
test: function(a,b){
        return a.age - b.age;
}
in the current version.
