### ISSUE TITLE
[Feature Request] Pass options to validator

### ISSUE THREAD

**Issue by alanaasmaa** [ElemeFE/element#5119]
### Existing Component
Yes

### Component Name
Form

### Description
It would be nice and very useful to pass options to validator. 

For example i have rule requiredIf and i would like to pass options to this rule. 

I see async-validator supports options but i have no idea how to use this. 

If its possible maybe update documentations that it would be easyer to read.

**Comment by baiyaaaaa** [comment]
Sorry...I can not get your point, what's the "option" slove?

**Comment by DomenicRoti** [comment]
I just want to comment for anyone that stumbles upon this, this appears to be implemented.

It would be nice if this was in the documentation though, since I had no idea I could pass more parameters into the validator.
