### ISSUE TITLE
[Bug Report] Can't load emitterJS with es6 syntax in IE11

### ISSUE THREAD

**Issue by Valumard** [ElemeFE/element#5125]
### Element UI version
1.3.4

### OS/Browsers version
Windows 7 / Internet Explorer 11

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
It's a bit difficult to show it to you.

I build the project with Webpack and use Babel. When I try to load a Chunk in IE, I get the following error:

Syntaxerror: Loading chunk 4 failed.

The IE directs me to the chunk and marks the following code:

`function(e,t,n){"use strict";function r(e,t,n){this.$children.forEach(s=>{var i=s.$options.componentName;i===e?s.$emit.apply(s,[t].concat(n)):r.apply(s,[e,t].concat([n]))})}t.a={methods:{dispatch(e,t,n){for(var r=this.$parent||this.$root,s=r.$options.componentName;r&&(!s||s!==e);)(r=r.$parent)&&(s=r.$options.componentName);r&&r.$emit.apply(r,[t].concat(n))},broadcast(e,t,n){r.call(this,e,t,n)}}}}`

This is code from the emitter.js. IE can't load the '=>' syntax.

### What is Expected?
This is the only appearance of '=>' in the whole source code, as far as I see. Some other parts are in a comment section.
Maybe it is possible, to change that line of code to the older syntax.

### What is actually happening?
See above :)

**Comment by Valumard** [comment]
Hi,

I solved my problem. So for further documentation:
I configured two presets in my .babelrc file. ES2015 and Stage-2. So I took a look at your .babelrc and saw that you use just one preset: vue-app. 
So I changed my presets to vue-app and tadaaa, works like a charm :)

**Comment by yinshipeng** [comment]
怎么解决的？

**Comment by yinshipeng** [comment]
```
{
  "presets": ["vue-app"]
}
```
仍然没有解决

**Comment by Valumard** [comment]
"presets": ["vue-app"] solved it for me.

**Comment by yinshipeng** [comment]
我试了  还是不行阿

**Comment by Valumard** [comment]
Google translate is not a big help when translating your language. So english please :)

**Comment by yinshipeng** [comment]
Ok, I haven't settled the way you said.

**Comment by yinshipeng** [comment]
I'm using the vue-cli init webpack,

**Comment by Valumard** [comment]
Jep I did that to. And in my .babelrc file had the preset "ES2015". Then I changed it to "vue-app" and it works perfectly :)
