### ISSUE TITLE
[Feature Request] Multiple select: minimum limit

### ISSUE THREAD

**Issue by lomereiter** [ElemeFE/element#5126]
### Existing Component
Yes

### Component Name
Select

### Description
It would be nice to have an option to limit the number of selected items from below. I can only think of the use case of 'at least 1', but it should be easy to add for any number (something like `:closable="currentNumItems > minimumNumItems"` in tag rendering)

**Comment by v8xm** [comment]
@lomereiter 
You raised a valuable feature ,  and I met same case before .
The multiply selection limitation always coupling with model and view .
Fortunately with vue.js ,I think we can have a better solution for this .
I am trying to add this feature now .
Thank you.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
