### ISSUE TITLE
组件中的字体的大小以及高度、宽度是否可自定义？

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#513]
### ElementUI version
1.0.0-rc.7
### OS/Browers version
win7/electron v1.4.3
### Vue version
 2.0.0-rc.4 

### Steps to reproduce
组件字体的大小，以及高度、宽度不能设置
### What is Expected?
组件字体的大小，以及高度、宽度能自定义

**Comment by jikkai** [comment]
可以的，参考#377，注意一下scoped问题
