### ISSUE TITLE
[Feature Request] Add "submit" event to forms

### ISSUE THREAD

**Issue by Korri** [ElemeFE/element#5130]
### Existing Component
Yes

### Component Name
ElForm

### Description
Right now there is no clean way to handle form submission without using the button. (This example doesn't trigger if you press the `Enter` key: http://element.eleme.io/#/en-US/component/form#validation). You can bypass that by adding the "submit" type to the button, and expect the browser to trigger the click event.

A much cleaner way would be to propagate the actual `submit` event from the `form` tag to the `el-form`.

So we could do something like that:
```html
<el-form :model="form" :rules="rules" @submit="handleSubmit">...</el-form>
```

**Comment by Leopoldthecoder** [comment]
You have `@submit.native`. https://vuejs.org/v2/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on-changed
