### ISSUE TITLE
[Feature Request] el-autocomplete 获取的数据格式是否只显示属性为value的？不能自定义

### ISSUE THREAD

**Issue by chenyeah** [ElemeFE/element#5136]
### Element UI version
1.3.4

### OS/Browsers version
win 10 /chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/u1eth9gw/1/](https://jsfiddle.net/u1eth9gw/1/)

### Steps to reproduce
获取的数据格式是否只显示属性为```value```的？如果我列表显示属性为```address```的时候我该如何？我没找到任何方法

### What is Expected?
列表显示的自定义

### What is actually happening?
列表显示的必须为属性为```value```

**Comment by cench** [comment]
@chenyeah http://element.eleme.io/#/zh-CN/component/input#zi-ding-yi-mo-ban 使用自定义模板

**Comment by baiyaaaaa** [comment]
This feature will be relase in 1.4.

**Comment by mqliutie** [comment]
现在我数据是这样的
```
[{name:'zhangsan',id:123}]
```
然后提示我 value值 要string 我这是number， 
设置的时候是这样设置的
```
:props="{label:'name',value:'id'}"
```

**Comment by Knight-endless-love** [comment]
@chenyeah 嘿，哥们，这个问题最终是怎么解决的

**Comment by hexb0307** [comment]
可以将后端的数据，copy修改一份，来用for-in将属性名字改一下就好了吧
