### ISSUE TITLE
The [Bug Report] tree component manually sets the current-node-key to no effect

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#5141]
### Element UI version
1.3.4

### OS/Browsers version
mac/chrome (all latest) 

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/63e696bn/](https://jsfiddle.net/63e696bn/)

### Steps to reproduce
在不点击 tree中节点的时候，手动设置高亮是生效的，但是一旦点击了tree节点之后 再手动点击 设置高亮current-node-key值 就不生效了

### What is Expected?
期待任何时候点击 设置current-node-key的值都能成效

### What is actually happening?
点击过tree节点之后就不再生效了

**Comment by Leopoldthecoder** [comment]
You should update `keyNode` when current node changes: https://jsfiddle.net/63e696bn/1/
