### ISSUE TITLE
Tree 中如何重新load某节点下的数据呢

### ISSUE THREAD

**Issue by jave-joe** [ElemeFE/element#5143]
场景是这样，在树的上面加了一些操作按钮，可以新增树的节点，当新增成功以后，想从后台重新加载一次新增节点的父节点，从而能够看到这个节点添加到树里面了。
不知道如何去写呢？

**Comment by microboat** [comment]
let root = this.root
        root.childNodes = []
        this.loadNode(root, data => {
          root.doCreateChildren(data)
        })
