### ISSUE TITLE
The scroll bar cannot drag in the [Bug Report] el-autocomplete drop-down list

### ISSUE THREAD

**Issue by jkby24** [ElemeFE/element#5146]
### Element UI version
1.3.4

### OS/Browsers version
window7/chrome58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/261/](https://jsfiddle.net/pj71jkyw/261/)

### Steps to reproduce
input框聚焦后输入建议中显示滚动条，鼠标移动到滚动条上，往下拖动。

### What is Expected?
列表正常往下滚动

### What is actually happening?
变成选中某个选项，滚动条拖动事件没有触发

**Comment by baiyaaaaa** [comment]
fixed in 1.3.6
