### ISSUE TITLE
[Feature Request] recommends adding -webkit-overflow-scrolling: touch to.El-table__body-wrapper

### ISSUE THREAD

**Issue by Rlilyyy** [ElemeFE/element#5148]
### Existing Component
是

### Component Name
el-table

### Description
iOS 中使用 el-table，横向数据过多时自动变为滚动浏览，但是目前滚动不平滑，建议给 .el-table__body-wrapper 加上 -webkit-overflow-scrolling: touch。

**Comment by Leopoldthecoder** [comment]
Element is not for mobile devices. If you have such needs, you can add it in your end.
