### ISSUE TITLE
[Bug Report]  Keep Alive - Dialog - Error next Tick

### ISSUE THREAD

**Issue by leo-coco** [ElemeFE/element#5150]
### Element UI version
1.3.4

### OS/Browsers version
macOs

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/4fwphqhv/](https://jsfiddle.net/4fwphqhv/)

### Steps to reproduce
1) Click on the button to display the popup

2) Wait for one second

3) Close the popup

4) Click again on the button

### What is Expected?
The popup should be opened again while having kept its previous state thanks to `keep-alive` attribute

### What is actually happening?
This error is shown

> [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'insert' of undefined"
> TypeError: Cannot read property 'insert' of undefined

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/4fwphqhv/3/
