### ISSUE TITLE
[Feature Request] Tabs question

### ISSUE THREAD

**Issue by ellisgl** [ElemeFE/element#5153]
### Existing Component
Yes

### Component Name
tabs

### Description
I would like to do the following:
Close a Tab, but not from the "X" icon in the tab.
Select/Open a tab by an ID.
Lock a tab in place. IE, the First tab should say in the #1 spot when scrolling.
Dynamically add tabs with normal JS, so I can create tabs from Socket.IO.

**Comment by syn-zeta** [comment]
Can you show a fiddle where you've tried to do something from your list?

Here's an example from the docs slightly modified: https://jsfiddle.net/qqknva76/

- You can close a tab in the above fiddle using the buttons.
- You can choose which tab is selected by modifying the value of `editableTabsValue2`.
- Pinning a tab is not a feature, however you can mark one of the tabs as non-closable.
- Look at the implementation of `addTab` in the above fiddle to see how tabs can be dynamically added.

That addresses all your questions. Please open a new ticket if you'd like to request the feature of pinning a tab.

@QingWei-Li Recommend closing this issue.

**Comment by Leopoldthecoder** [comment]
@ellisgl Pinning a tab doesn't seem to be a popular demand, so for now we have no plan to support it.
