### ISSUE TITLE
[Bug Report] about [el-menu] component.

### ISSUE THREAD

**Issue by netcore-jroger** [ElemeFE/element#5157]
### Element UI version
1.3.4

### OS/Browsers version
Windows 10 Pro / Chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/JRoger/94eh8j6a/](https://jsfiddle.net/JRoger/94eh8j6a/)

### Steps to reproduce
I use el-menu component, then I add is-active class to the first el-menu-item. but it does not work well when I click other el-menu-item. it did't auto remove the is-active class from the first el-menu-item. so ... I have to handle it manually.

### What is Expected?
auto remove `is-active` class from the first `el-menu-item` component.

### What is actually happening?
I use el-menu component, then I add is-active class to the first el-menu-item. but it does not work well when I click other el-menu-item. it did't auto remove the is-active class from the first el-menu-item. so ... I have to handle it manually.

**Comment by Leopoldthecoder** [comment]
Why do you try to manage active classes anyway? Element itself pretty much takes care of it: https://jsfiddle.net/94eh8j6a/1/

**Comment by netcore-jroger** [comment]
In fact, my code is not that simple. but I use `vm.$nextTick(callback)` solved the problem.
