### ISSUE TITLE
[Feature Request] need the value  type of datepicker to keep  timestamp always  

### ISSUE THREAD

**Issue by wfesorg** [ElemeFE/element#5159]
### Existing Component
Yes

### Component Name
datepicker

### Description
i bind value like  timestamp to v-model of datepicker,
when datepicker changed,the timestamp changed to date

**Comment by Leopoldthecoder** [comment]
The value of DatePicker is a `Date`, and this will not change. You can convert it to timestamp in your code, i.e. using a computed property.
