### ISSUE TITLE
[Bug Report] el-table component calls summary-method many times when I resize the window

### ISSUE THREAD

**Issue by zipoopiz** [ElemeFE/element#5162]
### Element UI version
1.3.4

### OS/Browsers version
windows7/chrome 58.0.3029.110

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/zipoopiz/7u0smecs/](https://jsfiddle.net/zipoopiz/7u0smecs/)

### Steps to reproduce
1. open console in dev tool
2. resize the window that displays contents
3. there are some log infomations in console

### What is Expected?
el-table component should not call summary-method when resizing the window   

### What is actually happening?
el-table component  call summary-method when resizing the window

**Comment by Leopoldthecoder** [comment]
This is actually inevitable. On resizing, Table has to rearrange its layout, causing all its cells re-rendering, so `summary-method`s are called since they are needed in the course of render.

So, it's not a bug and cannot be avoided for now.
