### ISSUE TITLE
[Bug Report] tree

### ISSUE THREAD

**Issue by AlpherJang** [ElemeFE/element#5163]
### Element UI version
1.3.4

### OS/Browsers version
firefox 53.0.3

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Open firefox
Open http://element.eleme.io/#/zh-CN/component/tree

### What is Expected?
all point‘s button were confused

### What is actually happening?
show same with it showes in Chrome

**Comment by AlpherJang** [comment]
sorry，I forgot，but you can see your documents [http://element.eleme.io/#/zh-CN/component/tree](http://element.eleme.io/#/zh-CN/component/tree) , the problem is same, and jsfiddle can't support JSX

**Comment by pengchongfu** [comment]
this bug is the same as #3640, the solution is add style `white-space: normal` like [this](https://jsfiddle.net/L2z25hjf/)
