### ISSUE TITLE
[Bug Report] Autocomplete delete all selected text and search is invalid

### ISSUE THREAD

**Issue by cench** [ElemeFE/element#5165]
### Element UI version
1.3.4

### OS/Browsers version
win7/chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/1op0rLxc/](https://jsfiddle.net/1op0rLxc/)

### Steps to reproduce
1、Search normally and then select a result

2、In the search box, select the text, and then delete

3、Search failed without triggering

**Detail gif operator example:**
http://code.zhongheyi.com/img/123.gif
![image](http://code.zhongheyi.com/img/123.gif)

### What is Expected?
After deleting the input, the search can continue

### What is actually happening?
Search termination

**Comment by Leopoldthecoder** [comment]
Please try on https://elementui.github.io/dev/dev/#/zh-CN/component/input to see if this problem continues. If not, it will be fixed in our next release.

**Comment by cench** [comment]
@Leopoldthecoder Sorry, The demo on the link page you gave me is OK, but the JSFiddle in demo is also not available, is it because you have not merged into the 1.3.4 version?
you could try it .
https://jsfiddle.net/t0znsjht/

**Comment by baiyaaaaa** [comment]
@cench yes, it will be release in 1.3.5

**Comment by Leopoldthecoder** [comment]
@cench Yes, the link I gave you syncs with our dev branch.
