### ISSUE TITLE
[Bug Report] dynamic add steps has style problems

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#5166]
### Element UI version
1.2.9

### OS/Browsers version
win10/chrome 28

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/862eg21f/](https://jsfiddle.net/862eg21f/)

### Steps to reproduce
now  `el-steps` has three `el-step` , click button add an `el-step`, 

### What is Expected?
one more `el-step` at right position

### What is actually happening?
el-step style has problems

**Comment by Leopoldthecoder** [comment]
Fixed in #5456
