### ISSUE TITLE
When [Bug Report] is first entered in the daterange type DatePicker, the input content is emptied

### ISSUE THREAD

**Issue by Simonalia** [ElemeFE/element#5169]
### Element UI version
1.3.4

### OS/Browsers version
Windows 10/Chrome 58.0

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/xc0saed7/](https://jsfiddle.net/xc0saed7/)

### Steps to reproduce
点击daterange类型的DatePicker，输入内容

### What is Expected?
当输入框失去焦点后，输入内容还在

### What is actually happening?
首次输入，输入内容被清空。再次输入时，输入内容保留。

**Comment by Leopoldthecoder** [comment]
What content did you enter? I tried entering something but didn't reproduce your problem.

**Comment by wacky6** [comment]
@Leopoldthecoder 
Try this: click input, enter "123", click somewhere.

I can only reproduce this problem on first input. Subsequent inputs are not cleared. Below is a gif:
![20170604_231358](https://cloud.githubusercontent.com/assets/9319556/26762863/e1209786-497b-11e7-99c6-a09c366cb694.gif)

**Comment by Simonalia** [comment]
@Leopoldthecoder 
Anything can produce this problem in the daterange type DatePicker, and it's no use to set default-value and default value of [v-model]
Try [this](https://jsfiddle.net/teupfgLt/4/)

**Comment by Dreamacro** [comment]
Fixed in #6021
