### ISSUE TITLE
[Feature Request] Message: support HTML

### ISSUE THREAD

**Issue by egyptik** [ElemeFE/element#5174]
### Existing Component
Yes

### Component Name
Message

### Description
Currently, only `string` type messages are allowed. I need a way to add HTML, in order to make part of the text bold and to include a undo link in success message after a user successfully complete a certain action. I tried using a VNODE, but that doesn't work either. Is there any way to achieve this?

**Comment by wacky6** [comment]
You can use `v-html` to inject raw html. But you need to modify Message's implementation.

Personally, I am against using html directly, since it leads to XSS risks.

**Comment by egyptik** [comment]
The messages are triggered using `this.$message`, not with an html element. So I'm not sure where I would be able to add the `v-html`? Also, can you please elaborate on the XSS risks? I don't see how a simple message component that is in no way connected to the backend would create much of a risk?

**Comment by wacky6** [comment]
$message is a method, it still needs to create and mount vue instance to document to show the message it self. $message is added to Vue.prototype in `build/bin/build-entry.js`

The Message component is defined in `package/message/src/main.vue`. You can have fun with the `<p>` tag inside.

---

As for the XSS issue:

* if the html contains user input, there's XSS risk. eg: `'user input: '+input.value`
* If the html is just a simple string, no problem. eg: `'<b>Bold</b> text'`
