### ISSUE TITLE
[Bug, Report], NPM, run, build, Error

### ISSUE THREAD

**Issue by subo-romens** [ElemeFE/element#5176]
### Element UI version
1.3.4

### OS/Browsers version
Mac/safari

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/xryt9b4j/2/](https://jsfiddle.net/xryt9b4j/2/)

### Steps to reproduce

npm run build  error
ERROR in static/js/vendor.e009106343d3b31cf28f.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/element-ui/packages/col/src/col.js:23,0][static/js/vendor.e009106343d3b31cf28f.js:146795,10].        

用npm run dev  is Ok 

### What is Expected?
修复Bug

### What is actually happening?
修复Bug

**Comment by QingWei-Li** [comment]
1. 不要直接引入未编译的代码
2. 不要乱加与 issue 无关的 demo

**Comment by CodeLookBook** [comment]
I have the same problem. Is there a way to fix it?

**Comment by callnothing** [comment]
I have the same problem.  can somebody fix it?

**Comment by brucehelen** [comment]
I have the same problem

`ERROR in index.js?797e177ae8445502fcbd from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/element-ui/packages/col/src/col.js:23,0][index.js?797e177ae8445502fcbd:3929,10]`

**Comment by legatoo** [comment]
same issue here . any fix?

**Comment by Leopoldthecoder** [comment]
Keep Element from being processed by UglifyJS.

**Comment by jackie19** [comment]
```
module: {
    rules::[
       {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'),resolve('/node_modules/element-ui/src'),resolve('/node_modules/element-ui/packages')]
      },
   ]
}
```

it's works for me.

**Comment by fgcui1204** [comment]
@Leopoldthecoder Thanks, it resolves my problem.

**Comment by callnothing** [comment]
@jackie19 very useful!

**Comment by wuyadream** [comment]
@jackie19 thank you,it's useful!

**Comment by EmraanSiddiqui** [comment]
Same error:
this error is occuring after updating it from older version 1.4.2 to newer version.

What is the real cause?

**Comment by dongxuan** [comment]
not work, any update ??

**Comment by Justysxh** [comment]
@jackie19 work for me too

**Comment by exmozz** [comment]
When I added this line:
`[resolve('src'), resolve('test'),resolve('/node_modules/element-ui/src'),resolve('/node_modules/element-ui/packages')]`
i've got this error:
"resolve is not defined"

**Comment by Daeghun** [comment]
your version of uglify doesn't support es6 and needs to be updated. The latest version could be gained as separate plugin

> webpack =< v3.0.0 currently contains v0.4.6 of this plugin under webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack.optimize.UglifyJsPlugin is scheduled for webpack   v4.0.0

Please refer to https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

Once you will install v1.0.0 you will be able to build it

**Comment by exmozz** [comment]
@Daeghun Thank you, it's helped.

**Comment by Justysxh** [comment]
resolve a function that you need to customize
like this:
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

@exmozz

**Comment by weituotian** [comment]
@Daeghun should every one update the uglify plugins?

**Comment by FAKER-A** [comment]
兄弟，我也遇到这样的问题  ，可以帮下忙嘛 @QingWei-Li

**Comment by weituotian** [comment]
是不是element不能在浏览器用？

**Comment by FAKER-A** [comment]
是在打包的时候出现问题   
![image](https://user-images.githubusercontent.com/25676164/33655793-07bb437c-daaf-11e7-8b7e-60c563283447.png)

**Comment by FAKER-A** [comment]
我看了一下  element  ui 的这个文件语法没有被转换成es5

![image](https://user-images.githubusercontent.com/25676164/33655847-36f0ec6e-daaf-11e7-8e91-39782c588b01.png)

**Comment by FAKER-A** [comment]
我试了上面的方法解决不了  很难过

**Comment by yusphy45** [comment]
我用的webstorm, 直接写一个组件的标签的时候编译器会自动的帮你import某个单独的组件，而且会直接在export default里面的components里添加进去，把这两部分删掉就不会报错了，就是和 @QingWei-Li 说的一样，你引入了未编译的代码，所以才会报这个问题 @FAKER-A

**Comment by feijuncheng** [comment]
我发现我报的错误路径中是_element-ui@2.3.4这样的格式的，后面的版本号码重新install之后可能会改变，没法在babel-loader里面写死，有什么办法吗？

**Comment by shady-xia** [comment]
@yusphy45 我也出现了这个问题，看了你的评论果然是webstorm单独引入了组件，去掉之后就好了，感谢。

**Comment by nosus** [comment]
我的问题是和@yusphy45 一样的，都是webstorm引入了组件的source code造成的，谢谢。不知道为什么 @weituotian 会给 👎 ....

**Comment by momodiy** [comment]
### Provide a solution 
Modifying ` node_modules ` dependence directly.Convert the referenced js code to es5 using [Babel](https://babeljs.io/repl).

### 提供一个解决方案
直接修改 node_modules相关依赖，将依赖的js代码转化为es5。在线转化工具 [Babel](https://babeljs.io/repl).

**Comment by momodiy** [comment]
终于解决了，注意`node_modules`前边没有`/`。
```js
{
    test: /\.js$/,
        use: 'babel-loader',
    // exclude: /node_modules/,
    include: [
        resolve('src'),
        resolve('test'),
        resolve('node_modules/element-ui/src'),
        resolve('node_modules/element-ui/packages'),
        resolve('node_modules/vue-echarts-v3')
    ]
},
```
发现~vue-echarts这个组件也会有这个问题。。。

**Comment by xuweimeng** [comment]
那我没有用element-ui咋搞呢
