### ISSUE TITLE
When the [Feature Request] Select component is set Multiple, the selected item does not automatically fold

### ISSUE THREAD

**Issue by zanpen2000** [ElemeFE/element#5178]
### Existing Component
Yes

### Component Name
Select

### Description
Select组件设置Multiple时，选中多个选项后，如果选项的长度大于Input框的宽度，会自动折行；我的需求是增加一个选项，使其可设置是否自动折行，（折行会撑高Input框影响页面美观），不自动折行的时候，允许用户用鼠标或键盘在input框内左右滚动查看被选项

**Comment by Leopoldthecoder** [comment]
无计划增加此选项。之前有试过，出现滚动条的话会很丑。

**Comment by zanpen2000** [comment]
@Leopoldthecoder 如果不加滚动条呢？
