### ISSUE TITLE
The value given by [Bug Report] color picker does not correspond to the value selected in the component

### ISSUE THREAD

**Issue by gogoJava** [ElemeFE/element#5179]
### Element UI version
1.3.4

### OS/Browsers version
chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pqjbLyqn/](https://jsfiddle.net/pqjbLyqn/)

### Steps to reproduce
ColorPicker 给默认的值，组件里面显示的值不一致

### What is Expected?
ColorPicker 给默认的值，组件里面显示的值应该一致

### What is actually happening?
ColorPicker 给默认的值，组件里面显示的值不一致

**Comment by Leopoldthecoder** [comment]
Fixed in #5183.
