### ISSUE TITLE
The [Bug Report] table component, the stripe property, and the override style cannot be changed

### ISSUE THREAD

**Issue by vipplus** [ElemeFE/element#5180]
### Element UI version
1.3.4

### OS/Browsers version
Mac／chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/qycycw53/](https://jsfiddle.net/qycycw53/)

### Steps to reproduce
重写这个样式
.el-table__row.el-table__row--striped{
    background-color:#e2f0e4;
}
未生效

### What is Expected?
重写样式el-table__row--striped

### What is actually happening?
重写样式el-table__row--striped

**Comment by vipplus** [comment]
找到啦

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/qycycw53/1/
