### ISSUE TITLE
[Feature Request] A way to programatically change the active tab

### ISSUE THREAD

**Issue by farcasmihai91** [ElemeFE/element#5182]
### Existing Component
Yes

### Component Name
el-tabs

### Description
Hello,
I tried programmatically changing the active tab with no luck.
I tried for example  ```this.$parent.$parent.panes[4].active = true```, but this does not work - I am probably trying to do something I should not :).
I inspected the tab-pane element and its children but could not find any way to do this.
Is there a way to do this? 
If not, it would make a great feature!

Thank you!
Awesome library btw <3

**Comment by Leopoldthecoder** [comment]
Of course you can do that: https://jsfiddle.net/b0pa35vv/

**Comment by gmw-web** [comment]
Would be much nicer if there were some methods available, and we could do stuff like...

```
this.$refs['tabs'].nextTab()
this.$refs['tabs'].previousTab()
this.$refs['tabs'].goToTab(_tabName_)
```
