### ISSUE TITLE
[Bug Report] questions about element-ui development

### ISSUE THREAD

**Issue by huangyanxiong01** [ElemeFE/element#5186]
### Element UI version
1.3.5

### OS/Browsers version
Distributor ID:	Ubuntu 
Description:	Ubuntu 16.04.2 LTS 
Release:	16.04 
Codename:	xenial

### Vue version
2.3.3

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
yarn dev

### What is Expected?
怎么实时监听组件的变化

### What is actually happening?
在开发组件时实时监听组件的变化

**Comment by Leopoldthecoder** [comment]
Simply run `npm run dev`. `cooking watch` takes care of that.

**Comment by huangyanxiong01** [comment]
@Leopoldthecoder 我改变packages下面的文件时，并没有监听到变化
