### ISSUE TITLE
[Bug Report] el-tree check-change function, the third parameter is always false, will not be selected according to the subtree of the node changes

### ISSUE THREAD

**Issue by fsy0718** [ElemeFE/element#5187]
### Element UI version
1.3.5

### OS/Browsers version
mac os 10.12.5  chrome 58.0.3029.110

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/fsy0718/xyby6emh/](https://jsfiddle.net/fsy0718/xyby6emh/)

### Steps to reproduce
选择节点 [ 一级1]，可以看见一级1下面所有子节点全部选中,可以在console中看到check-change的句柄函数被调用4次，其中第三个参数全部为false

### What is Expected?
函数调用应该依次为：
1.  data, true, true
2. data,true,true
3. data, true, false,
4. data, true, false

### What is actually happening?
函数实际调用结果为
1.  data, true, false
2. data,true,false
3. data, true, false,
4. data, true, false

**Comment by Leopoldthecoder** [comment]
Ah, the documentation is wrong. In fact, the third parameter indicates if the node is indeterminate. Combined with the second parameter, you'll get a clearer picture of its descendants' states.

I'll update the docs.

**Comment by BigForceTaken** [comment]
麻烦把中文文档也更新一下
