### ISSUE TITLE
[Bug Report] fixed columns has gap in table

### ISSUE THREAD

**Issue by DoryDuan** [ElemeFE/element#5191]
### Element UI version
1.3.5

### OS/Browsers version
google

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/9jhdr3ys/1/](https://jsfiddle.net/9jhdr3ys/1/)

### Steps to reproduce
When the table doesn't has scroll bars, the fixed columns has gap in table.
Please pay attention to name and province.

### What is Expected?
Don't have gap in  the fixed columns.

### What is actually happening?
Have gap in  the fixed columns.

**Comment by demi798** [comment]
我也遇到这个问题了，不过是当屏幕很大的时候，固定在右侧的两列就与原表格分离开了，它们两个中间还有固定列数的空列数，屏幕再大些的话，固定栏和列表的距离会越来越大

**Comment by liril-net** [comment]
Fixed in [Carbon](https://github.com/ElemeFE/element/releases/tag/v2.0.0)
