### ISSUE TITLE
$msgbox  message使用VNODE提示JSON错误

### ISSUE THREAD

**Issue by ysysdzz** [ElemeFE/element#5197]
`
const h = this.$createElement;

		 	app.$msgbox({

				title: '折扣设置',

				message: h('p', null, '内容'),

				showCancelButton: true,

				confirmButtonText: '确定',

				cancelButtonText: '取消',

				beforeClose: function (action, instance, done) {

					done();

				}

			});`

TypeError: Converting circular structure to JSON

**Comment by Alexis374** [comment]
旧版本会遇到这个问题。升级新版就好了

**Comment by forcszhangguoyu** [comment]
要升级到哪个版本？我用的是1.2.9的会出现这个问题

**Comment by ddcouples** [comment]
@Alexis374 如题 1.3.7也会出现这个问题 只有1.4正常，但是如果转成1.4.2版本 里面有好多兼容性的问题 怎么破

**Comment by Alexis374** [comment]
@ddcouples 这就要问开发者了。我也是使用的时候发现的
