### ISSUE TITLE
[Bug Report] date selection controls display time, the browser will appear Caton rolling

### ISSUE THREAD

**Issue by iamwelk** [ElemeFE/element#5198]
### Element UI version
1.3.5

### OS/Browsers version
win7/chrome56

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
不会用fiddle...

### What is Expected?
希望使用datepicker组件的时候，生成的新的dom元素不要单独放到body外面并计算器位置，感觉每次浏览器滚动的时候都要重新计算，会出现卡顿，且这样组件的位置也不好控制

### What is actually happening?
日期选择控件显示出来的时候，浏览器滚动会感觉到明显的卡顿现象

**Comment by Leopoldthecoder** [comment]
We'll keep it as it is.
