### ISSUE TITLE
[Feature Request] Pass datePicker formatted value to validator. 

### ISSUE THREAD

**Issue by alanaasmaa** [ElemeFE/element#5199]
### Existing Component
Yes

### Component Name
Datepicker

### Description
Hello,

I'd like to use datepicker component with custom validator method.
When i access value property from validator i get JS Date String. I can't to custom validations for formatting at all cause of this. Becose i dont know the excact value.

Maybe one option would be that you pass the formatted value into rule object. 

Also it does not complain if format is wrong.

**Comment by Leopoldthecoder** [comment]
> I can't to custom validations for formatting at all cause of this. Becose i dont know the excact value.

What does *exact value* mean? A demo would help a lot.

**Comment by alanaasmaa** [comment]
I'll try to explain better.

So let's say i create a form that includes a datepicker.

```
            <el-date-picker
              v-model.lazy="form.date"
              type="month"
              format="MM/yyyy"
              placeholder="Valitse päivä">
            </el-date-picker>
```

Format here is MM/yyyy.

When i create custom validator for the datepicker and access this value its JS date string
```
export function date(rule, value, callback) {
  console.log(value); // Tue Jun 06 2017 08:57:00 GMT+0300 (Eastern Europe Daylight Time)
  return callback();
}
```

I can't validate format or do anything with format in my validator. Which is in this example (MM/yyyy)
So it would be nice to get the date somehow 06/2017 from validator.

**Comment by Leopoldthecoder** [comment]
When you have a Date object, you can format it to any form you like.

**Comment by alanaasmaa** [comment]
I understand that. But i can't see from validation for example what format is should be. It would help to atleast see MM/yyyy then i could format it myself. 

Also when i Submit the form i have to format the value again.

**Comment by Leopoldthecoder** [comment]
I guess you're using the same validator for several date fields with different formats, so you need to distinguish their formats from one another? Again, a demo would help.

**Comment by alanaasmaa** [comment]
Yes i'm using same validator. 

Here is an demo: https://jsfiddle.net/alanaasmaa/pj71jkyw/283/

So the only workaround is to use multible validators for different formats for now ? Also when i submit my form i have to manually covert formatting.

**Comment by wacky6** [comment]
Seems your demo contains come bugs.

A fixed one: https://jsfiddle.net/pj71jkyw/284/

The `value` argument in validator is a Date object, you can validate it anyway you like.

**Comment by Leopoldthecoder** [comment]
I added a `format` property to each rule, and found that it can be accessed in the validator. So you don't have to write multiple validators: https://jsfiddle.net/pj71jkyw/285/

In the above demo, I also imported fecha and formatted field value.

**Comment by alanaasmaa** [comment]
@wacky6 Thanks :)

@Leopoldthecoder Actually i'm using this same logic allready for parameters.

I just manually format the fields on save, when i think about its acutally pretty useful that the value is always date string behind the scenes.
