### ISSUE TITLE
[Feature, Request], Can select component add new feature that select all option base option on multiple?

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#5200]
### Existing Component
是

### Component Name
Select 选择器

### Description
Select 选择器 在多选的情况下能够添加是否需要全选功能，不需要用户逐个逐个点击选择

**Comment by Leopoldthecoder** [comment]
We won't add this. In fact, you can do this easily on your end: https://jsfiddle.net/z2fbL5d3/
