### ISSUE TITLE
[Feature, Request], Can, tag, component, add, click, event?

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#5201]
### Existing Component
是

### Component Name
Tag 标签 

### Description
Tag 标签 能够添加点击事件

**Comment by Simonalia** [comment]
使用@click.native 详情见 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md)

**Comment by smile33** [comment]
如果给标签添加原生点击事件，同时closable为true（存在可关闭按钮），点击关闭按钮时会触发标签原生点击事件，是否能够有参数控制点击关闭按钮时不触发标签原生点击事件

**Comment by Simonalia** [comment]
给@close事件添加.stop修饰符，阻止事件冒泡 详情见[demo](https://jsfiddle.net/fhy55owd/6/)
