### ISSUE TITLE
When the [Bug Report] DatePicker type is week, there is no synchronous update by highlighting the external change of the value

### ISSUE THREAD

**Issue by shuaibird** [ElemeFE/element#5202]
### Element UI version
1.3.5

### OS/Browsers version
macOS Sierra / Chrome 58.0

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/1e60yds3/](https://jsfiddle.net/1e60yds3/)

### Steps to reproduce
点击日期选择器左边的 NEXT WEEK 按钮

### What is Expected?
data中的date改变，datepicker高亮同步更新

### What is actually happening?
data中的date改变，datepicker高亮没有同步更新

**Comment by wacky6** [comment]
`date` is not reactive, you should assign to `this.date` directly

Example:
```JavaScript
this.date = new Date(this.date.getTime() + 7*24*3600*1000)
```
