### ISSUE TITLE
[Feature Request] Could you supply a ":remote" attribute to component, "Cascader"?

### ISSUE THREAD

**Issue by lisa4930007** [ElemeFE/element#5211]
### Existing Component
Yes

### Component Name
Cascader / Filterable

### Description
I really like your component, Cascader. It's good to use.
But now I get trouble when the original data are numerous.
The page's loading is too heavy.
If there is possible, could you supply the ":remote" feature?
So that we can load the data at any time.
Thank you very much!

(Please ignore my poor English. HaHa)

**Comment by Leopoldthecoder** [comment]
You can use `active-item-change` to have a lazy-load effect.

**Comment by de1ck** [comment]
> You can use `active-item-change` to have a lazy-load effect.

how to use  remote search function ?

**Comment by raisiqueira** [comment]
Hi @Leopoldthecoder Could you share an example of how to use the `active-item-change` prop to have the same lazy-load behavior. I saw in the source that this property is deprecated. Thanks.

https://github.com/ElemeFE/element/blob/dev/packages/cascader-panel/src/cascader-panel.vue#L290

**Comment by Leopoldthecoder** [comment]
Sorry guys, but I have left the team for years, so I don't have a better knowledge than you now.
