### ISSUE TITLE
[Bug Report] in the safari browser, DateTimePicker date time picker, the initial value can not be displayed normally

### ISSUE THREAD

**Issue by smiledy** [ElemeFE/element#5216]
### Element UI version
1.3.5

### OS/Browsers version
Safari

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/hwL3t6cb/](https://jsfiddle.net/hwL3t6cb/)

### Steps to reproduce
打开elementUI DateTimePicker日期时间选择器的菜单，点击第一个在线运行，给value1赋初值则能看到bug重现。

### What is Expected?
希望在safari浏览器下，DateTimePicker日期时间选择器赋初值的情况下能够正确的显示出时间，并且能够改变选择时间

### What is actually happening?
在safari浏览器下，给DateTimePicker日期时间选择器赋初值以后，则不显示时间，并且不能选择改变时间，会报错

**Comment by smiledy** [comment]
https://jsfiddle.net/hwL3t6cb/

**Comment by wacky6** [comment]
You need to set value to something that's accepted by `new Date()`

https://jsfiddle.net/z5kbpkcc/

**Comment by kenberkeley** [comment]
the simplest solution : https://github.com/kenberkeley/fix-date
