### ISSUE TITLE
After the [Bug Report] 1.3.1 version, the time range selects the shadow of the selected days of the control for less than the first day

### ISSUE THREAD

**Issue by xcwang520** [ElemeFE/element#5217]
### Element UI version
1.3.5

### OS/Browsers version
chrome，win10

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/s0meqp1h/](https://jsfiddle.net/s0meqp1h/)

### Steps to reproduce
1：使用选择日期范围控件
2：选一个时间段
3：弹出查看已选的时间，第一天没有阴影标记

PS：图片地址https://cloud.githubusercontent.com/assets/11661628/26783396/85e20152-4a2a-11e7-85f4-e039be955933.png

### What is Expected?
所有已选天数全部有阴影选中状态

### What is actually happening?
第一天没有阴影选中，其他的天数正常

**Comment by fsy0718** [comment]
在[timezone](https://github.com/ElemeFE/element/commit/6563a3a8049cf9c6e395d52cc966b1870797fc15) 这次提交中，随意变更了`clearHours`方法，导致永远不会出现start与end属性，感觉改的好随意

**Comment by Leopoldthecoder** [comment]
Fixed in #5226
