### ISSUE TITLE
[Bug Report] NavMenu submenu retraction method

### ISSUE THREAD

**Issue by dengzw** [ElemeFE/element#5219]
### Element UI version
1.3.5

### OS/Browsers version
all

### Vue version
2.3.3

### Steps to reproduce
1、导航打开一个有二级菜单的菜单后，点击一个一级菜单，打开的二级菜单无法自动收起。例如官网侧栏案例中：点击“菜单二”时“菜单一”不会自动收起
![Uploading image.png…]()

### What is Expected?
1、是否有可手动收起的方法可调用？如果没有，或是是否考虑增加该方法？

### What is actually happening?
点击一个一级菜单，打开的二级菜单无法自动收起

**Comment by Leopoldthecoder** [comment]
Use `unique-opened`.

**Comment by dengzw** [comment]
@Leopoldthecoder 谢谢回复，我试过了； 但是，unique-opened 只能设置多个子菜单中仅有一个子菜单打开，怎么设置当一级菜单选中时关闭所有展开的二级菜单。如下图中点击“菜单二”或者“菜单三”时怎么收起展开的“菜单一”呢？
![1](https://user-images.githubusercontent.com/5534187/26861078-0bba12de-4b74-11e7-8a78-4fd8dea606d4.png)

**Comment by Leopoldthecoder** [comment]
写个 demo 来解释你的意思吧

**Comment by dengzw** [comment]
[https://jsfiddle.net/MirageDeng/zf29nv8h/](url)

**操作步骤：**
第一步：点击“导航一”打开子菜单
第二步：点击"导航二"

**结果：**
“导航一”子菜单不会自动收起

**期望**
点击“导航二”或者“导航三”时，展开的“导航一”能自动收起

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/zf29nv8h/2/

**Comment by caoqiuping** [comment]
有没有方法能阻止二级菜单点开之后，禁止再关闭呢。

**Comment by cher0420** [comment]
unique-opened默认为false,实际效果为只能保持一个子菜单展开，且点击空白处后也会闭合。请问该怎么保持多个子菜单自由展开闭合

**Comment by cher0420** [comment]
2.3.3的版本可实现，之后的版本都无法实现，希望回复
