### ISSUE TITLE
表格固定列和表头,左固定和右固定列出现问题如下

### ISSUE THREAD

**Issue by perfectyang** [ElemeFE/element#522]
element-ui@1.0.0-rc.7 最新添加的表格固定功能

![_p8krs5gm3 6a217k v](https://cloud.githubusercontent.com/assets/8724828/19526862/6e40a1b0-9658-11e6-9add-963333756532.png)

**Comment by furybean** [comment]
换了一种实现方式，性能会差一些，不过再也不会出现这个 Bug 了。

**Comment by furybean** [comment]
RC8 已修复。
