### ISSUE TITLE
[Feature Request] Tree : Inline editing

### ISSUE THREAD

**Issue by rbajaniya** [ElemeFE/element#5223]
### Existing Component
Yes

### Component Name
Tree

### Description
How to append node with put inline text & change text(inline editing)

**Comment by Leopoldthecoder** [comment]
Use `render-content`.

**Comment by rbajaniya** [comment]
I Used render-content but how can possible inline edit

Please refer this image(https://user-images.githubusercontent.com/25998887/26862454-ff25f7be-4b68-11e7-9f6c-b22396069952.png) and you can visit website for more details(https://www.jstree.com/demo/)
