### ISSUE TITLE
When there is a <div> loop in the [Bug Report] table component, the check box column is always in the last column

### ISSUE THREAD

**Issue by yeyifen** [ElemeFE/element#5224]
### Element UI version
1.3.5

### OS/Browsers version
osx 10.11.3/chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/8progxq4/](https://jsfiddle.net/8progxq4/)

### Steps to reproduce
见重现链接，表格生成时复选框列自动跑最后了。
如果将表格里面 for循环的 `<div>`

替换为`<template>` ,则能表现正常，但其他列却无法交换顺序了。

### What is Expected?
期待第一列显示索引列，第二列显示复选框列，其他列按data里的数据顺序排列。
或者提供一个手动渲染表格的方法，让我可以手动执行渲染

### What is actually happening?
复选框列永远在最后一列

**Comment by Leopoldthecoder** [comment]
Please do not open repeated issues.

**Comment by Demon2** [comment]
div标签  换成  template   即可
