### ISSUE TITLE
Disable past dates

### ISSUE THREAD

**Issue by mitajunior** [ElemeFE/element#5225]
How do i disable past dates  in the datepicker?

**Comment by jyjunyz** [comment]
hi，you can add `disabledDate` function in   pickerOptions 
```
 pickerOptions: {
                    disabledDate(time) {
                        return time.getTime() < Date.now() - 8.64e7;
                    }
}
```

**Comment by authlab-frontdev** [comment]
@jyjunyz It was a helpful comment. For those who didn't get what's "8.64e7", it's just the number of milliseconds of a day. We need to subtract the number from current timestamp so that we don't disable "today".

**Comment by MalvinJay** [comment]
@jyjunyz Thanks a lot for the comment. It saved me a lot of time.

**Comment by thamibn** [comment]
@jyjunyz Thanks, this worked like a charm.

and thanks from @authlab-frontdev to explain what 8.64e7 mean.
