### ISSUE TITLE
[Bug Report] Blur event does not work

### ISSUE THREAD

**Issue by leo-coco** [ElemeFE/element#5229]
### Element UI version
1.3.5

### OS/Browsers version
macOS

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/nhg0uqy4/](https://jsfiddle.net/nhg0uqy4/)

### Steps to reproduce
Click on the `input` it is working 
Click on the `el-input` it is not working

### What is Expected?
`blur` function should be triggered

### What is actually happening?
`blur` is not triggered

**Comment by Leopoldthecoder** [comment]
Use `blur` directly. We have exposed the native blur event to you: https://jsfiddle.net/nhg0uqy4/1/

**Comment by fritx** [comment]
@Leopoldthecoder how do I capture the blur event from the `input` inside a `autocomplete`?
i've tried both `blur` and `blur.native` but without success.

**Comment by fritx** [comment]
Just found out `blur.native.capture` works for el-autocomplete, thanks!
