### ISSUE TITLE
The [Bug Report] table component setCurrentRow method repeats the highlighted rows after deleting the table data

### ISSUE THREAD

**Issue by ldp0218** [ElemeFE/element#5236]
### Element UI version
1.3.5

### OS/Browsers version
Google Chrome 版本 58.0.3029.110

### Vue version
2.3.3

### Reproduction Link
https://jsfiddle.net/8gLho1a4/

### Steps to reproduce
1. 从表格底部开始删除数据
2. 那么就会出现显示多条高亮行的情况
3. 前面的高亮行并没有消失

### What is Expected?
设置当前行应该就只有一行是高亮显示的

### What is actually happening?
结果有多行是高亮显示的

**Comment by ldp0218** [comment]
重新更新了Demo地址

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/26864731-376f3ad6-4b8c-11e7-9220-1d23f30f345a.gif)

未能复现。

**Comment by ldp0218** [comment]
你先点击第8条，然后再点击第5条，bug就会出现。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/8gLho1a4/1/ 把高亮操作放在 nextTick 里
