### ISSUE TITLE
树控件的 default-checked-keys这个属性，不是双向数据绑定吗？

### ISSUE THREAD

**Issue by caizhiming8** [ElemeFE/element#5237]
我是在用树控件的default-checked-keys属性时，从后台获取勾选项的数组，把数组传递给default-checked-keys的变量，但是并没有效果。但当我给这个变量默认值的时候，是可以显示默认勾选项的。
所以我想问是我的问题？还是控件的问题？还是控件的这个属性不能数据双向绑定？

**Comment by Leopoldthecoder** [comment]
Please use `getCheckedKeys`. As for `default-checked-keys`, you can know from the property name that it is a **default** value.

**Comment by caizhiming8** [comment]
I said you don't understand.My project background is returned to my data is an array of the default selected tree node.

**Comment by Leopoldthecoder** [comment]
I see. Please open a new issue with a reproduction demo.
