### ISSUE TITLE
[Bug Report] get a wrong date from date-time-picker

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#5239]
### Element UI version
1.3.5

### OS/Browsers version
all

### Vue version
2.3.3

### Reproduction Link
https://jsfiddle.net/qxs3ohe7/

### Steps to reproduce
1.pick a date range 
2.the input will display a wrong string
3.remove `format="yyyy-MM-dd HH:MM:SS"`
4.repeat the same operation above,and you can get a correct result

![image](https://user-images.githubusercontent.com/1060733/26871964-887d7148-4ba7-11e7-8f6c-002d39ae5b17.png)

![image](https://user-images.githubusercontent.com/1060733/26872155-277adcae-4ba8-11e7-9c79-247b51630408.png)

**Comment by wacky6** [comment]
You should use lowercased "mm" and "ss" to format minutes and seconds respectively.
"MM" is for month.

Please check documentation: http://element.eleme.io/#/en-US/component/datetime-picker
