### ISSUE TITLE
[Feature Request] [requirements -Tree] can provide a configuration to control whether the root node is displayed

### ISSUE THREAD

**Issue by netcore-jroger** [ElemeFE/element#5240]
### Existing Component
是

### Component Name
Tree

### Description
是否可以提供一个配置，控制是否显示根节点？

**Comment by Leopoldthecoder** [comment]
What is the use case for this feature?

**Comment by netcore-jroger** [comment]
其中一个组织，管理同级多个组织架构。但这些组织之间没有关系。所以实现时就虚拟了一个。
其实不虚拟也可以实现。只是觉得有这样一个配置项，会比较方便。
