### ISSUE TITLE
[Feature Request] Dialog can you set drag attributes?

### ISSUE THREAD

**Issue by rex-zsd** [ElemeFE/element#5242]
### Existing Component
是

### Component Name
Dialog

### Description
在Dialog中嵌套表单做修改信息功能时，可能需要查看后面的原信息，Dialog会挡住后面的一些内容，希望能够支持对Dialog进行拖拽。

**Comment by liniu** [comment]
可否同时增加 autosize 属性，不然不能自定义大小，tiny/small/large/full 这几个是不够用啊

**Comment by Leopoldthecoder** [comment]
@rex-zsd 可以配合第三方拖拽库使用。
@liniu 可以自己写 CSS 覆盖。

**Comment by jason65** [comment]
什么回答啊！感觉没有任何作用

**Comment by jason65** [comment]
@liniu 可以自己写 CSS 覆盖，把<style scoped>的scoped去掉，在dialog里面加id属性，然后在加css样式

**Comment by bigtrouble** [comment]
@rex-zsd please check
https://github.com/bigtrouble/vue-element-dialog-drag
