### ISSUE TITLE
[Bug Report] main.js调用Vue.use(Message)时，页面刷新会弹出一个空Message

### ISSUE THREAD

**Issue by Deacyn-Dong** [ElemeFE/element#5243]
如题，按需引入element-ui，import {......, Message} from 'element-ui'，调用Vue.use(Message)安装Message插件，页面刷新会自动弹出一个空的默认Messgae。如果单独去掉Vue.use(Message)则正常。

**Comment by Rabbitzzc** [comment]
怎么解决的呀

**Comment by konglingwen94** [comment]
同求呀

**Comment by konglingwen94** [comment]
有说是用 `Vue.component(Message.name,Message)`注册的，但是在使用`this.$message.warning()`的时候报错了，`"TypeError: Cannot read property 'warning' of undefined"`，谁知道要怎么解决吗?

**Comment by konglingwen94** [comment]
@Rabbitzzc 找到解决办法了，这样注册组件就行了 `Vue.prototype.$message=Message`

**Comment by Rabbitzzc** [comment]
> @Rabbitzzc 找到解决办法了，这样注册组件就行了 `Vue.prototype.$message=Message`

没看源码，原因是？？
