### ISSUE TITLE
[Bug Report] Cannot read property 'offsetWidth' of undefined after redirect in created event

### ISSUE THREAD

**Issue by stmn** [ElemeFE/element#5245]
### Element UI version
1.3.5

### OS/Browsers version
OSX/Chrome

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/x3b08b80/3/](https://jsfiddle.net/x3b08b80/3/)

### Steps to reproduce
Just click "GO TO TABS" link. Errors will appear in console.

### What is Expected?
Errors should not appear.

### What is actually happening?
Errors appear.

**Comment by Leopoldthecoder** [comment]
Wrap `this.$router.push("/")` in the next tick: https://jsfiddle.net/x3b08b80/4/
