### ISSUE TITLE
[Feature, Request], want, a, new, to, control, prop, whether, select, change,, its, height, while, multiple

### ISSUE THREAD

**Issue by NadiaSmile** [ElemeFE/element#5247]
### Existing Component
是

### Component Name
elselect

### Description
i am doing a  query page,and i use el-select to achieve multiple choose function. and in one row, i use both el-input  and el-select,when i set select multiple, select and input has different height, which makes the page looks not tidy. especially when the choices need more than one line to show. hence i  want a prop to control the select height, if i set this prop true, the select will not change its height.instead, it will scroll horizontally.

**Comment by Leopoldthecoder** [comment]
You can do that with CSS: https://jsfiddle.net/khq1ga4c/ , though the scrollbar may make it ugly.

**Comment by NadiaSmile** [comment]
i have tried this and it is rather ugly, so i am researching your code and thinking about whether you can solve it.anyway, thank you

At 2017-06-08 12:15:05, "杨奕" <notifications@github.com> wrote:


You can do that with CSS: https://jsfiddle.net/khq1ga4c/ , though the scrollbar may make it ugly.
