### ISSUE TITLE
[Question] is element responsive?

### ISSUE THREAD

**Issue by amesas** [ElemeFE/element#525]
From what I see on the demo site I guess that no.

If not, do you plan to make it responsive? I know there's mint-ui but it's twice the work, and responsive != mobile. Tablets, phablets, vertical monitors, huge monitors, smaller windows, etc...

**Comment by Leopoldthecoder** [comment]
Added in plan.

**Comment by dsonet** [comment]
I guess the fastest way to support responsive is to add CSS helpers for now.

**Comment by amesas** [comment]
A responsive grid + responsive menu + helper classes would cover the most cases.

**Comment by otabekgb** [comment]
I think you already added some responsive grid features. Thats great, thanks a lot. 
Can you document the changes please?
Also what about responsive (collapsing) menus and sidebars?

**Comment by Leopoldthecoder** [comment]
Now we have breakpoints, documented at the bottom of [this page](http://element.eleme.io/#/en-US/component/layout).

Collapsing menus and sidebars still remain to be discussed.

**Comment by azurelogic** [comment]
@Leopoldthecoder Seems like the simplest way to add some of this is to add a string/string array prop to ElCol that lets you set hidden sizes. Alternatively, you could have 4 boolean props, one for each size.

**Comment by AxelTheGerman** [comment]
too bad. I just started to like element. but not responsive is a no-go for me. best of luck!

**Comment by azurelogic** [comment]
@AxelTheGerman I moved over to [Quasar](http://quasar-framework.org/). Very responsive.

**Comment by arturaugusto** [comment]
I was having problems with non responsive behavior on mobile, because I forgot to set the `meta` tag on my index.html:

```
<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
```

Now everything looks much better.
