### ISSUE TITLE
[Bug Report] table components in the safari browser, header and content dislocation, scroll bar, drag the mouse failure

### ISSUE THREAD

**Issue by luciy** [ElemeFE/element#5251]
### Element UI version
1.3.5

### OS/Browsers version
macOS 10.12.5   safari 10.1.1

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/66sq92pt/      https://jsfiddle.net/b896t3hg/](https://jsfiddle.net/66sq92pt/      https://jsfiddle.net/b896t3hg/)

### Steps to reproduce
官方示例中 就存在样式错位以及滚动条无法滚动的情况。

### What is Expected?
样式表现一直，滚动条可以滚动

### What is actually happening?
样式错位，滚动条不能通过鼠标拖动滚动

**Comment by luciy** [comment]
![7e172214-102a-4d7f-b9d3-95de88536d38](https://user-images.githubusercontent.com/5343507/26916005-0f1abdf6-4c5b-11e7-8bf7-cbde82ad1398.png)

**Comment by lincenying** [comment]
这个bug的原因是单元格里的元素设置的宽度 大于 表格的列的宽度, 就会这样...把这个列的宽度调大...
好像只有safari有这个问题.

**Comment by luciy** [comment]
dialog组件中的 嵌套 select 点击 select 窗口抖动的问题可以通过修复 dialog css样式临时解决。
```
.el-dialog {
  position: relative;
  left: auto;
  transform: none;
  margin: 0 auto 50px auto;
}

```

**Comment by luciy** [comment]
safari 滚动条无法滚动问题 可通过修改 table 样式 临时解决
```
.el-table__body-wrapper{
  z-index:2
}

```

**Comment by jiangningning** [comment]
table表头样式的问题解决了？ @luciy

**Comment by kugeliu** [comment]
你们的这个问题解决了吗？我也碰到了。。 @jiangningning @luciy

**Comment by jiangningning** [comment]
@kugeliu 没有

**Comment by a346721573** [comment]
chrome 59 同样存在这个问题。。。 错位的情况啥时候能解决呢？ @luciy 影响较大。。。

**Comment by sunshinefish** [comment]
这个问题解决了吗。。好崩溃啊

**Comment by sunshinefish** [comment]
目前这里先把它置为display none 了。有点崩溃

**Comment by yangchongduo** [comment]
这个问题 官方没有给出方案吗

**Comment by furybean** [comment]
做了最新两个版本的测试，均无法重现此问题：

1.4.2 无法重现此问题：https://jsfiddle.net/b896t3hg/3/
2.1.0 无法重现此问题：https://jsfiddle.net/b896t3hg/4/

先关了，如果在最新版本可以重现，欢迎再开 issue。

**Comment by T-OneSoul** [comment]
解决了吗？我也遇到这问题 了@ @luciy

**Comment by furybean** [comment]
@T-OneSoul 如果是最新版本，欢迎提个 issue。

**Comment by LucasZheng** [comment]
2.2.2版本依然存在这个问题

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/39850973-ca83690a-5446-11e8-91e0-e59c5b59559b.png)
chrome66
element-ui 2.3.7
带边框表格，表头边框错位

**Comment by dborstelmann** [comment]
I am still getting this as well.  Does anyone have a solve?

**Comment by dborstelmann** [comment]
Notice this is because of scrollbars being on

**Comment by XMBLDB** [comment]
<script src="//unpkg.com/element-ui/lib/index.js"></script> 
The same problem.

**Comment by ovo4096** [comment]
```
.el-table {
  &__header-wrapper {
    .has-gutter {
      tr > th.gutter {
        display: table !important;
      }
    }
  }
}
```

我用最新的 2.4.4 版本还是有这个问题，但是我尝试用上面的代码解决了表头不对齐的问题，目前还不知道有啥负影响。

### 没解决之前是这样的
![image](https://user-images.githubusercontent.com/8173064/43094877-b13811aa-8ee6-11e8-9f74-6b15eee0ccef.png)

**Comment by wushanchao** [comment]
style scoped环境使用下面代码
```css
div >>> .el-table th{
    display: table-cell!important;
}
```

**Comment by somosarado** [comment]
Still having this problem with the last version

**Comment by hzsrc** [comment]
2.4.5 版本safari下，仍然对不齐

**Comment by liub1934** [comment]
> .el-table { &__header-wrapper { .has-gutter { tr > th.gutter { display: table !important; } } } }
用来这个有效

**Comment by liub1934** [comment]
```
.el-table {
  &__header-wrapper {
    .has-gutter {
      tr > th.gutter {
        display: table !important;
      }
    }
  }
}
```
楼上的这个代码有效

**Comment by AlexZhong22c** [comment]
还有，如果浏览器被缩放到90%，也会出现楼上 zouhangwithsweet 所截图的那种情况。

**Comment by yyjazsf** [comment]
> ```
> .el-table {
>   &__header-wrapper {
>     .has-gutter {
>       tr > th.gutter {
>         display: table !important;
>       }
>     }
>   }
> }
> ```
> 
> 我用最新的 2.4.4 版本还是有这个问题，但是我尝试用上面的代码解决了表头不对齐的问题，目前还不知道有啥负影响。
> 
> ### 没解决之前是这样的
> ![image](https://user-images.githubusercontent.com/8173064/43094877-b13811aa-8ee6-11e8-9f74-6b15eee0ccef.png)

window 1920*1080 像素，然后推荐放大150% 也会这样，125% 就没事

**Comment by yzhang921** [comment]
貌似把边距设置为0，然后每列的列宽在被挤压的情况下指定列宽可以解决

```
<el-table-column
.....
  :width="c.width"
/>
.el-table .cell, .el-table th div {
    text-overflow: unset;
    padding-left: 0 !important;
    padding-right: 0 !important;
}
```
