### ISSUE TITLE
[Bug Report] Tree render-content custom content not rendered

### ISSUE THREAD

**Issue by Ringes** [ElemeFE/element#5252]
### Element UI version
1.3.5

### OS/Browsers version
Windows 10/ Edge/Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Use ELTree and render-content to render custom content. Only top level element is generated, any inner elements do not appear.

### What is Expected?
`renderNode(h, { node, data, store }) {
    return (
        <span><span>{node.label}</span></span>
      );
  }`

when viewed in dom explorer should have:
       `<span><span>some value</span></span>`

### What is actually happening?
when viewed in dom explorer instead has:
        `<span></span>`

this works correctly:
`<span>{node.label}</span>`

this works partly; the label value is displayed but inner span doesn't:

`<span>{node.label}<span>{node.label}</span></span>`

**Comment by Leopoldthecoder** [comment]
Works fine: https://jsfiddle.net/48ba39sL/ . Please make sure JSX is correctly configured in your project.
