### ISSUE TITLE
[Bug Report] V1.3.5 Switch Component rendered unexpected

### ISSUE THREAD

**Issue by MicyToy** [ElemeFE/element#5256]
### Element UI version
1.3.5

### OS/Browsers version
window all / Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/egh80vk2/1/](https://jsfiddle.net/egh80vk2/1/)

### Steps to reproduce
When value is a number, Switch Component will override `value`，and rendered unexpected.

### What is Expected?
a number `value` should be supported

### What is actually happening?
rendered unexpected， and it is right in v1.3.4

**Comment by wacky6** [comment]
You should use boolean type for value.

**Comment by wacky6** [comment]
You should bind on/off-value using an expression. Your jsfiddle bound a string to on-value/off-value.

```
:on-value="1" :off-value="0"
```

https://jsfiddle.net/7xuztzqt/

**Comment by MicyToy** [comment]
thks, it works.
