### ISSUE TITLE
[Feature Request] i want to judge number(like 1 and 0) with checkbox but only boolean

### ISSUE THREAD

**Issue by WxSwen** [ElemeFE/element#5266]
### Element UI version
1.2.3

### OS/Browsers version
chrome 58.0.3029.110

### Vue version
2.1.9

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
use check with number，no work

### What is Expected?
isChecked: function isChecked() {
if ({}.toString.call(this.model) === '[object Boolean]') {
return this.model;
}

else if(Number.isInteger(this.model)){
	        return this.model === 1;
          }
else if (Array.isArray(this.model)) {
return this.model.indexOf(this.label) > -1;
} else if (this.model !== null && this.model !== undefined) {
return this.model === this.trueLabel;
}
},

just like this ,and i hope to see return its number
or other way to fix it

### What is actually happening?
use check with number，no work

**Comment by Leopoldthecoder** [comment]
Use `true-label` and `false-label`: https://jsfiddle.net/jggwzsyu/
