### ISSUE TITLE
The [Bug Report] date range (el-date-picker) component is not marked on the current date

### ISSUE THREAD

**Issue by vipplus** [ElemeFE/element#5267]
### Element UI version
1.3.5

### OS/Browsers version
Mac/Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
https://jsfiddle.net/8ftva5t4/1/这个是之前的版本是可以支持的。

### What is Expected?
当前日期有标注

### What is actually happening?
当前日期有标注

**Comment by Leopoldthecoder** [comment]
Fixed in #5226
