### ISSUE TITLE
[Bug Report] paging (pagination) component, the data on the FireFox too long, the number of pages behind the box shows incomplete, and other browsers tens of thousands of data also showed incomplete

### ISSUE THREAD

**Issue by vipplus** [ElemeFE/element#5268]
### Element UI version
1.3.5

### OS/Browsers version
Mac/FireFox

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/c1r4oqe9/](https://jsfiddle.net/c1r4oqe9/)

### Steps to reproduce
https://jsfiddle.net/c1r4oqe9/用FireFox打开

### What is Expected?
显示完整页数

### What is actually happening?
显示完整页数

**Comment by Leopoldthecoder** [comment]
For now you can override its width with `!important`: https://jsfiddle.net/c1r4oqe9/1/ .We'll remove the inline `style="width: 30px"` in the next release, so that you don't have to add `important` when overriding.

**Comment by vipplus** [comment]
Thanks
