### ISSUE TITLE
When the [Bug Report] DatePicker is set to daterange, click the start date and the date will not be highlighted

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#5275]
### Element UI version
1.3.5

### OS/Browsers version
mac/chrome 57

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/291/](https://jsfiddle.net/pj71jkyw/291/)

### Steps to reproduce
打开重现链接, 随便点击一个日期为起始日期, 鼠标划开后, 该日期不高亮了, 第二次点击结束日期, 也一样

### What is Expected?
和1.3.4版本一样, 起始/结束日期能高亮显示

### What is actually happening?
起始/结束日期不能高亮显示

1.3.5
![image](https://user-images.githubusercontent.com/10840991/26964278-690e1fec-4d23-11e7-8e94-68a5679f4116.png)

1.3.4
![image](https://user-images.githubusercontent.com/10840991/26964297-7591efbe-4d23-11e7-966a-c264996603c7.png)

**Comment by Leopoldthecoder** [comment]
Fixed in #5226
