### ISSUE TITLE
[Bug, Report], Wrong, display, about, NumberInput, with, slot (prepend, and, append)

### ISSUE THREAD

**Issue by kankk** [ElemeFE/element#5281]
### Element UI version
1.3.5

### OS/Browsers version
Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
```JavaScript
<el-input-number>
  <template slot="prepend">Number:</template>
  <template slot="append">个</template>
</el-input-number>
```

### What is Expected?
Display like <el-input> with slot (prepend or append)

### What is actually happening?
It is not displayed properly. the slot with append will overflow the increase button and decrease button. Btw, it is not normal way to use slot in NumberInput, but I think it will be work after I read the resource. Please feel free to let me know is it the normal way to use slot in NumberInput.

**Comment by Leopoldthecoder** [comment]
Unfortunately slots are not supported in InputNumber. Though the source code has those slots included, they are not ready to ship and not listed on the docs.
