### ISSUE TITLE
[Bug Report] DateTimePicker cannot set default values like yyyy-MM-dd HH

### ISSUE THREAD

**Issue by mingbai2006** [ElemeFE/element#5283]
### Element UI version
1.3.5

### OS/Browsers version
Windows10/Chrome58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/aeet72o1/1/](https://jsfiddle.net/aeet72o1/1/)

### Steps to reproduce
如链接所示，给第一个组件设置‘2017-06-02 12’这种默认值会报错

### What is Expected?
正常工作

### What is actually happening?
报错且默认值没有显示

**Comment by Leopoldthecoder** [comment]
The binding value of `v-model` should always be a Date: https://jsfiddle.net/aeet72o1/3/
