### ISSUE TITLE
The [Feature Request] Table component wants to increase the options for defining cell styles

### ISSUE THREAD

**Issue by mirari** [ElemeFE/element#5287]
### Existing Component
是

### Component Name
Table

### Description
现在只有table的row-class-name属性可以定义行样式，table-column的class-name属性可以定义列样式，但是有时候只需要单独定义某一个单元格。
虽然用<template scope="scope"></template>可以定义单元格的内容，但整个scope都在单元格div内部，会有一个全局样式导致的padding。现在希望在不修改表格全局样式的基础上，对单元格做一些简单的background-color和color的定制，能否提供一个类似row-class-name的属性，传入单元格和行数据等相关参数，用于定义单元格样式呢？

**Comment by Leopoldthecoder** [comment]
Now we have `cell-class-name` in 2.0
