### ISSUE TITLE
[Bug Report] table cancellation problem

### ISSUE THREAD

**Issue by ohhoney1** [ElemeFE/element#5294]
### Element UI version
1.3.6

### OS/Browsers version
win7/chrome59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/cnjs/oz08ggaq/](https://jsfiddle.net/cnjs/oz08ggaq/)

### Steps to reproduce
需求：点击取消排序按钮，操作排序状态。
目前只能通过点击表头出改变排序状态。

### What is Expected?
比如：当前是ascending 排序，上箭头高亮，点击取消排序，期望箭头全变灰。

### What is actually happening?
不能改变箭头的高亮状态。

**Comment by ohhoney1** [comment]
:default-sort="{prop: 'date', order: 'descending'}" 
目前default-sort的键orde只支持descending和ascending，希望能允许传‘’
这样这个iusse就可以fix了

**Comment by lincenying** [comment]
支持下这个, 最近刚好也遇到这个, 不支持外面重置排序

**Comment by liril-net** [comment]
Fixed in [Carbon](https://github.com/ElemeFE/element/releases/tag/v2.0.0). Now you can cancel sort by `clearSort` method
