### ISSUE TITLE
 [Feature Request] Can add right-click menus for tree components?

### ISSUE THREAD

**Issue by edeye** [ElemeFE/element#5298]
### Existing Component
Yes

### Component Name
tree

### Description
能否为树形组件添加右键菜单?

**Comment by PLQin** [comment]
???

**Comment by PLQin** [comment]
@edeye 

建议参考: 
[ElementUi] 需要实现 `tree`组件上右键弹出菜单并且 `获得 tree node的id值` - Starch的回答 - SegmentFault
https://segmentfault.com/q/1010000012940760/a-1020000012955488

**Comment by furybean** [comment]
与 #8950 重复，请关注 #8950 的进度。
