### ISSUE TITLE
[Feature Request] [recommendation] slot adds a container for verifying error information in FormItem!

### ISSUE THREAD

**Issue by michael829** [ElemeFE/element#5299]
### Existing Component
是

### Component Name
Form

### Description
现在的FormItem在添加验证规则后会自动在FormItem的所有元素最后添加一个div.el-form-item__error的容器来显示错误提示信息..但是有时候FormItem中除了Input外还有别的内容..所以希望这个错误提示信息的容器能够自己指定显示在FormItem中具体的某个位置...
希望能追加一个新的slot来装载错误提示信息的DIV..感谢..

**Comment by Leopoldthecoder** [comment]
It's not a common use case, so we have no plan to add this support. You can manipulate DOM directly on your end.

**Comment by Aibric** [comment]
我在FORM 下的input 后面追加了一个hint，当使用rules时，error 信息始终在 form-item 所有标签最后追加。 我想在input 直接显示 error，并非在追加的hint后台显示，当然 input 和 hint 同属于一个 form-item。

不知道表述的是否清楚？

**Comment by michael829** [comment]
@ @Aibric 对的.是这个意思..现在的form-item自定义样式空间太小了..我并不希望rules总是显示在form-item的最后.我希望能够指定容器去显示.这样也方便自定义样式呢..不过看来他们暂时不打算支持这个功能了..
顺便问一下我之前建议在colorpicker中增加输入框的建议不是说会考虑在后面的版本中加入么?都已经过好多个版本了..还没加入呢..虽然我自己用组合组件实现了.但是还是希望在colorpicker中直接就能有这样的功能,省得再去嵌套colorpicker+input了...
