### ISSUE TITLE
There is no response from the [Feature Request] Tooltip call

### ISSUE THREAD

**Issue by nei2000** [ElemeFE/element#5300]
### Existing Component
Yes

### Component Name
Tooltip

### Description
Tooltip调用时没有任何反应
<el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
	<el-button>上左</el-button>
</el-tooltip>
没有其它代码，没反应，求解

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
