### ISSUE TITLE
[Feature Request] el-table Table-column added property show-overflow-tooltip error

### ISSUE THREAD

**Issue by nei2000** [ElemeFE/element#5301]
### Existing Component
Yes

### Component Name
el-table

### Description
el-table Table-column added property show-overflow-tooltip error
Uncaught TypeError: Cannot read property 'style' of undefined

node_modules\element-ui\lib\table.js
tooltip.$refs.popper.style.display = 'none'; Line 1879
The “tooltip.$refs.popper” object is undefined
SOS!!!!!!

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by Hector526** [comment]
我同样遇到了这个问题。

**Comment by nei2000** [comment]
@Hector526 你这个解决了吗？

**Comment by Hector526** [comment]
@nei2000  没有呀。临时用下面方法凑合用的。
<el-table-column  label="更新内容">
            <span :title="row.pkgDes">
                {{ row.pkgDes }}
            </span>
  </el-table-column>

**Comment by Hector526** [comment]
el-table-column inline-template :show-overflow-tooltip="false" label="更新内容">
            span :title="row.pkgDes">
                {{ row.pkgDes }}
            </span
</el-table-column

**Comment by nei2000** [comment]
@Hector526 我没处理，很不爽啊，之前都是可以的，升级版本就不行了，还有就是提交的问题，还都给关闭了，悲剧。

**Comment by nei2000** [comment]
我单独用了tooltip是没有任何效果的。我感觉应该跟这有关系。

**Comment by Leopoldthecoder** [comment]
@nei2000 给 demo

**Comment by Hector526** [comment]
@nei2000  @Leopoldthecoder  鼠标悬停在表格内容时，报错。
`            <el-table :data="tableData" class="table" v-loading="tableLoading" element-loading-text="拼命加载中" border style="width: 100%"
                    :default-sort="{prop: 'createdAt', order: 'descending'}" @sort-change="tableSortChange">
                <el-table-column prop="userName" label="账号" show-overflow-tooltip></el-table-column>
                <el-table-column prop="logIP" label="IP地址"></el-table-column>
                <el-table-column prop="event" label="操作内容" show-overflow-tooltip></el-table-column>
                <el-table-column prop="createdAt" label="操作时间" sortable='custom' :formatter="showReceiveDate"></el-table-column>
            </el-table>`
浏览器报错内容如下：
`element-ui.common.js:8676 Uncaught TypeError: Cannot read property 'style' of undefined
    at VueComponent.handleCellMouseEnter (element-ui.common.js:8676)
    at Proxy.boundFn (vue.js:175)
    at mouseenter (element-ui.common.js:8515)
    at HTMLTableCellElement.invoker (vue.js:1749)`

**Comment by nei2000** [comment]
@Leopoldthecoder 我是在本地调试的如果用远程地址做的是可以的，但用NPM安装的就不行，我还特地把其它代码都去掉就保留VUE+UI试依然一样效果

**Comment by Leopoldthecoder** [comment]
@nei2000 既然这样应该不是 Element 的问题。请确保 Element 和 Vue 的版本均为最新。

**Comment by nei2000** [comment]
本地都是最新版本的，怎么试都没有用。

**Comment by Leopoldthecoder** [comment]
@nei2000 你可以删掉无关代码，然后把仓库放到 GitHub 上我看看

**Comment by nei2000** [comment]
你有QQ吗？我加你

**Comment by nei2000** [comment]
@Leopoldthecoder 你有QQ吗，我加你。

**Comment by nei2000** [comment]
@Leopoldthecoder  https://github.com/nei2000/vuetest  仓库地址你copy下去看看是不是有这种情况！

**Comment by Leopoldthecoder** [comment]
@nei2000 试试把你 web/app.js 第一行的
```javascript
import Vue from 'vue/dist/vue.js'
```
改成
```javascript
import Vue from 'vue'
```

**Comment by Hector526** [comment]
Uncaught [ModJS] Cannot find module `node_modules/vue/dist/vue`

**Comment by nei2000** [comment]
@Hector526 @Leopoldthecoder 把VUE改成import Vue from 'vue'加载，但会报错，需在要webpack.config.js里配置一下这个就可以了。
resolve: {
	alias: { 'vue': 'vue/dist/vue.js' }  
 }
使用tooltips就正常了，谢谢哈
