### ISSUE TITLE
[Bug Report] Tooltip small triangle to take the minimum margin value (0), resulting in display dislocation

### ISSUE THREAD

**Issue by ioslh** [ElemeFE/element#5302]
### Element UI version
1.3.6

### OS/Browsers version
Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/292/](https://jsfiddle.net/pj71jkyw/292/)

### Steps to reproduce
如 jsfiddle 所示

### What is Expected?
小三角位置得体

### What is actually happening?
小三角的最小边距值为 0；
```js
// element-ui/lib/utils/popper.js
sideValue = Math.max(Math.min(popper[len] - arrowSize, sideValue), 0);
```
当取到最小值时，由于 tooltip 默认的 4px `border-radius`，三角显示视觉上会错位，如此图所示：
![img](http://wx1.sinaimg.cn/large/5eeb2608gy1fgg9wbhqcuj20a007gjrb.jpg)

**Comment by Leopoldthecoder** [comment]
Fixed in #5303. Added a 3px minimum offset on both start and end.
