### ISSUE TITLE
[Bug Report] el-dialog @open event can't be triggered

### ISSUE THREAD

**Issue by sizhang** [ElemeFE/element#5304]
### Element UI version
1.3.6

### OS/Browsers version
MacOS Sierra 10.12.5,  Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/295/](https://jsfiddle.net/pj71jkyw/295/)

### Steps to reproduce
all the codes are shown in the jsfiddle.

### What is Expected?
The open callback should be called after the dlg opened

### What is actually happening?
The open callback function is not called

**Comment by Leopoldthecoder** [comment]
`open` and `close` only triggers when the visibility of Dialog changes. For example, if the initial visibility of Dialog is false, which means `dialogVisible` being false in your case, do you expect the `close` event be triggered once it's mounted? I suppose not. Same goes to `open` event when the Dialog is initially visible.

So, if you want the `open` event to be triggered, just change Dialog's visibility: https://jsfiddle.net/pj71jkyw/297/
