### ISSUE TITLE
The [Bug Report] time control binds type to and fro, causing the style to be incorrect

### ISSUE THREAD

**Issue by loopArray** [ElemeFE/element#5305]
### Element UI version
1.3.6

### OS/Browsers version
Windows7/Chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/296/](https://jsfiddle.net/pj71jkyw/296/)

### Steps to reproduce
时间控件的类型是动态切换的，默认情况是date，创建3个按钮分别表示切换天、月、年，初始化后点击月，再点击时间控件是正常的，再点击年后点击时间控件就会出现样式错乱的情况。点击空白区域后再点击时间控件也会正常，但是再次切换其他的类型还是会出现错乱的情况。

### What is Expected?
能正常显示。

### What is actually happening?
样式错乱，对应的时间控件picker-panel没有移动到body下。

**Comment by Leopoldthecoder** [comment]
Duplicate of #4905
