### ISSUE TITLE
官方文档time-picker一处错漏

### ISSUE THREAD

**Issue by csdudu** [ElemeFE/element#5308]
http://element.eleme.io/#/zh-CN/component/time-picker
红线处el-time-picker应为el-time-select，害死人呀。

![20170611092651](https://user-images.githubusercontent.com/5706088/27007538-2b26080e-4e89-11e7-8c3c-5eb0809d7a36.jpg)

**Comment by Leopoldthecoder** [comment]
并没有错，就是 `el-time-picker `: https://jsfiddle.net/cwdqqgL8/
