### ISSUE TITLE
[Bug Report] el-slider display error when enclosed by a el-form-item

### ISSUE THREAD

**Issue by caozhzh** [ElemeFE/element#5309]
### Element UI version
1.3.6

### OS/Browsers version
ubuntu 16.04/google chrome 52.0.2743.116 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/67xu8vfp/](https://jsfiddle.net/67xu8vfp/)

### Steps to reproduce
just in jsfiddle links

### What is Expected?
el-slider display ok when not enclosed by a el-form-item
wish it will ok when enclosed by a el-form-item

### What is actually happening?
el-slider display error when enclosed by a el-form-item

**Comment by Leopoldthecoder** [comment]
Since you're using inline Form, you need to explicitly assign a width to Slider: https://jsfiddle.net/67xu8vfp/1/

**Comment by caozhzh** [comment]
that's ok, thanks!
sorry for my poor css skills.
