### ISSUE TITLE
[Bug Report] The problem with the navigation links

### ISSUE THREAD

**Issue by afuno** [ElemeFE/element#5310]
### Element UI version
1.3.6

### OS/Browsers version
macOS 10.12.5 / Safari 10.1.1

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/298/](https://jsfiddle.net/pj71jkyw/298/)

### Steps to reproduce
How to use links in Element UI? I just added the `<a>` tags.

### What is Expected?
Normal display of links. Normal operation of the links.

### What is actually happening?
The text in the "a" tag has an abnormal color. Also, browser styles are not reset (`a:any-link`, for example).

**Comment by afuno** [comment]
This problem is also reproduced with Vue router:
```
<router-link to="/foo">Go to Foo</router-link>
```

**Comment by Leopoldthecoder** [comment]
Nothing is abnormal, that's how `<a>` looks when there is no reset. By default Element does not include CSS resets, but we provide a reset.css: https://jsfiddle.net/pj71jkyw/299/

**Comment by afuno** [comment]
@Leopoldthecoder This partially solved the problem. Thank you.
But why it is necessary to press only on the text? I mean, why can not I click on the area around the link?

**Comment by Leopoldthecoder** [comment]
Because `<a>` is an inline element. You need to change its display to `block`: https://jsfiddle.net/pj71jkyw/300/

**Comment by afuno** [comment]
@Leopoldthecoder Thank you so much.
