### ISSUE TITLE
The [Bug Report] table specifies Height, and cannot display the total row

### ISSUE THREAD

**Issue by Vurtne-hz** [ElemeFE/element#5315]
### Element UI version
1.3.6

### OS/Browsers version
Win10/Chrome59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/1ft5m1f3/](https://jsfiddle.net/1ft5m1f3/)

### Steps to reproduce
第一次加载完成不显示合计行，点击按钮绑定数据合计行也没有显示

### What is Expected?
点击按钮显示合计行

### What is actually happening?
合计行未显示

**Comment by Leopoldthecoder** [comment]
Fixed in #5318
