### ISSUE TITLE
[Bug Report] table Chinese sorting is incorrect, did not press the phonetic alphabet to order first

### ISSUE THREAD

**Issue by Esa-i** [ElemeFE/element#5316]
### Element UI version
1.3.6

### OS/Browsers version
chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/8hd7Lj68/](https://jsfiddle.net/8hd7Lj68/)

### Steps to reproduce
点击姓名列进行排序，举例升序

### What is Expected?
比小虎、刘小虎、王小虎、章小虎

### What is actually happening?
刘小虎、比小虎、王小虎、章小虎

**Comment by Leopoldthecoder** [comment]
That's how JavaScript sorts Chinese characters:
![image](https://user-images.githubusercontent.com/10095631/27017396-b592aeda-4f5a-11e7-80c5-7fb9bb78f340.png)

You need to write your own sorting method if you wish to sort them by pinyin.
