### ISSUE TITLE
[讨论]如果开启了router模式，是否需要在NavMenu组件初始化时对default-active进行路由跳转

### ISSUE THREAD

**Issue by zhoujiamin** [ElemeFE/element#532]
### ElementUI version
 "element-ui": "^1.0.0-rc.7",

### OS/Browers version
chrome版本 53.0.2785.143 m

### Vue version
 "vue": "^2.0.1",
 "vue-router": "^2.0.0",

### What is Expected?
NavMenu 导航菜单，使用default-active，router,index等属性，实现页面加载后自动进入默认页面
### What is actually happening?
效果没达到,页面加载后，default-active指定的页面的titile会高亮，但是相应路径的页面没有加载

**Comment by devrsi0n** [comment]
我出现这种情况，是哪里配置不对吗？

**Comment by reverland** [comment]
好像navMenu没有路由跳转的功能？用router.go一类的方式跳转？

**Comment by baiyaaaaa** [comment]
@reverland 有路由跳转的功能，需要通过router属性来开启。

**Comment by baiyaaaaa** [comment]
@zhoujiamin 目前确实没做对 default-active 进行 menu 初始化时的跳转功能。一般来说页面加载后的路由应该就是你当前 default-active 所指向的路由吧？很少会通过页面的组件来做二次跳转的
