### ISSUE TITLE
When the [Bug Report] select selector has the empty button, when you open the select drop-down and select the select value, you need to click two

### ISSUE THREAD

**Issue by smiledy** [ElemeFE/element#5323]
### Element UI version
1.3.6

### OS/Browsers version
ipad/ios  safari浏览器

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ptqk67dw/](https://jsfiddle.net/ptqk67dw/)

### Steps to reproduce
直接在ipad 或者 ios 用safrai浏览器打开 带清除按钮的select 需要点击两下才能打开下拉，同时需要点击两下才能选择下拉的值。

### What is Expected?
希望select加上clearable属性以后和在pc端一样流畅，只需要点击一次。

### What is actually happening?
select 加上clearable属性以后，不论时打开下拉选项还是选择选项都需要点击两次。

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop devices, please avoid using it on iOS.
