### ISSUE TITLE
表单验证中，DatePicker事先给定默认值直接提交，表单验证通过，但是控制台会有报错

### ISSUE THREAD

**Issue by wangnamin** [ElemeFE/element#5325]
一、你们好，提交BUG的链接不能用，所以我就在这里提一下我遇到的bug问题。
二、重现地址：https://jsfiddle.net/pj71jkyw/304/
三、步骤：
1.点击重现链接
2.左上角运行（Run）
3.运行以后，在结果界面直接点击提交
4.观察控制台会报错：Uncaught TypeError: t.getTime is not a function，这个错是第二个DatePicker报出来的
 四、期待的行为：在我们的项目中，经常会在表单中用到DatePicker控件，几乎都要设置必填，一般情况下，新添加的表单中选值再保存是没有任何问题的，只是表单也会经常修改，修改都是带有默认值的，如果在修改表单时，不修改日期控件，就无法保存。
希望饿了么的大神们帮忙修复一下，谢谢

**Comment by Leopoldthecoder** [comment]
DatePicker 的值需要是 Date 类型，所以从接口拿到后可能需要转成 Date 格式再绑定到组件上：https://jsfiddle.net/pj71jkyw/305/
