### ISSUE TITLE
[Feature Request] Add menu items that are not links (without index)

### ISSUE THREAD

**Issue by gfigueroa** [ElemeFE/element#5326]
### Existing Component
Yes

### Component Name
menu-item

### Description
I need to add menu items to a menu that are not links and require no index (for example, a search bar). This way they are properly aligned (vertically) in the menu bar and hovering over them does not underline the item.

![menu](https://user-images.githubusercontent.com/1941240/27063646-7577ff1e-5025-11e7-949f-7b0cb79c2579.png)

**Comment by Leopoldthecoder** [comment]
We may not support this. But you can implement it yourself: https://jsfiddle.net/74ayqxrz/
