### ISSUE TITLE
[Bug Report] Combination of dialog and Popover

### ISSUE THREAD

**Issue by qianqWang** [ElemeFE/element#5331]
### Element UI version
1.3.6

### OS/Browsers version
chrome  58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
After opening dialog, click the Edit button to eject popover, then the text box on the popover cannot be entered.

### What is Expected?
The text box on the popover can be entered.

### What is actually happening?
The text box on the popover cannot be entered.

**Comment by Leopoldthecoder** [comment]
Duplicate of #5322

**Comment by qianqWang** [comment]
https://jsfiddle.net/Lh5b4q43/

**Comment by aaabinbin** [comment]
Upgrade ele ui version to 1.3.7~~~
