### ISSUE TITLE
The [Feature Request] input box el-input does not have a built-in readonly state

### ISSUE THREAD

**Issue by dawnfrost** [ElemeFE/element#5333]
### Existing Component
Yes

### Component Name
el-input

### Description
希望能对el-input内置一个readonly状态的样式，现在readonly的输入框只是不能输入内容，但样式上看起来与其他输入框没有区别，使用disabled样式又有点太过了，用户容易感觉有歧义，希望能像bootstrap一样内置一个readonly的样式

**Comment by Leopoldthecoder** [comment]
It can be read only: https://jsfiddle.net/yrybcom6/

Seems we overlooked this when writing the doc. I'll update it.

**Comment by dawnfrost** [comment]
知道能readonly，我说的是在样式上能不能加一个灰色，与非readonly区分开，这样用户一眼看上去就知道哪个框能输入哪个框是只读的，至于disabled因为鼠标指上去会变成一个禁止图标，用户感受不好，所以给readonly加一个灰色的背景色就可以了，可否考虑一下

**Comment by jikkai** [comment]
Hi，很抱歉现在才来跟进这个 issue。我们讨论了以后决定暂时不为 `readonly` 添加样式加以区分，理由有两点：
1. 对于用户区分 Disable 和 ReadOnly 的收益不大，而理解成本又很高
2. readonly input 在多为异步提交表单的今天使用场景比较少
3. 开发者随时可以通过 CSS 覆盖自己想要的 readonly 样式

综上考虑暂不对 readonly input 作调整，后续如有变更我们会在此 issue 继续跟进，感谢您的建议。
