### ISSUE TITLE
[Bug Report] cannot set the table's max-height through the style name

### ISSUE THREAD

**Issue by mcdongWang** [ElemeFE/element#5335]
### Element UI version
1.3.6

### OS/Browsers version
MacOS 10.12 / Chrome 59.0

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/306/](https://jsfiddle.net/pj71jkyw/306/)

### Steps to reproduce
https://jsfiddle.net/pj71jkyw/306/

### What is Expected?
可以识别max-height 的string类型的属性 和 calc属性

### What is actually happening?
没有识别max-height

**Comment by mcdongWang** [comment]
@liril-net 这就是我说的[https://github.com/ElemeFE/element/issues/4976](https://github.com/ElemeFE/element/issues/4976)问题的一部分

**Comment by mcdongWang** [comment]
没人来解答一下么?

**Comment by elfman** [comment]
@mcdongWang 你要使用max-height，可以自己用CSS定义啊，为啥要写到template里？例如
```
  tbody > tr.el-table__row { max-height: calc(100vh - 200px); }
```

**Comment by mcdongWang** [comment]
@elfman 文档里写了支持string啊? 难道不是指定class么

**Comment by furybean** [comment]
@mcdongWang 使用方式有问题，请参考这里：https://jsfiddle.net/pj71jkyw/759/。

**Comment by mcdongWang** [comment]
@furybean 连接404了
