### ISSUE TITLE
Questions about Table-column properties, fixed fixation, and type=expand rendering

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#5340]
### Element UI version
1.3.6

### OS/Browsers version
mac osx

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/v5n6mywp/1/](https://jsfiddle.net/v5n6mywp/1/)

### Steps to reproduce
table表格有expand 和fixed属性时，鼠标hover时，高亮行错误！

### What is Expected?
鼠标hover时，高亮行正确

### What is actually happening?
鼠标hover时，高亮行不正确

**Comment by ChangeZhang** [comment]
issue 好像没人管呀

**Comment by ChangeZhang** [comment]
@Leopoldthecoder

**Comment by ChangeZhang** [comment]
https://jsfiddle.net/v5n6mywp/1/

**Comment by Leopoldthecoder** [comment]
Fixed in #5471
