### ISSUE TITLE
[Bug Report] computing scrollBarWidth make the app too slow

### ISSUE THREAD

**Issue by wisheslee** [ElemeFE/element#5341]
### Element UI version
1.2.8

### OS/Browsers version
maxOS 10.12 /chrome 59

### Vue version
2.2.6

### Reproduction Link
[https://codepen.io/xiongsongsong/project/full/AjOwMV/](https://codepen.io/xiongsongsong/project/full/AjOwMV/)

### Steps to reproduce
just click the delete button left and right to compare the cost of time. when the number of list is more ,the  time is more.

### What is Expected?
the reason i found is /src/utils/scrollbar-width.js(const widthNoScroll = outer.offsetWidth) cost too many time. 
I dont know what can this function(scrollBarWidth) do, because in my opition, it always return 0.
when i let this function return 0 skip the expressions, the app doesn't show any problems and run fast.

### What is actually happening?
the reason i found is /src/utils/scrollbar-width.js(const widthNoScroll = outer.offsetWidth) cost too many time. 
I dont know what can this function(scrollBarWidth) do, because in my opition, it always return 0.
when i let this function return 0 skip the expressions, the app doesn't show any problems and run fast.

**Comment by wacky6** [comment]
@Leopoldthecoder Seems this can solve select's performance issue?

**Comment by Leopoldthecoder** [comment]
@wacky6 Yes, this is at least partly responsible for Select's performance issue.

In scrollbar-width.js we have
```javascript
if (scrollBarWidth !== undefined) return scrollBarWidth;
```
Clearly this line is trying to cache the calculation result, but `scrollBarWidth` is never assigned a value, so it's always undefined. After fixing this, the time consumption drops from ~670ms to ~270ms on my machine.

@wisheslee Thanks for looking into this problem. I'm sending a PR.

**Comment by Leopoldthecoder** [comment]
Fixed in #5359
