### ISSUE TITLE
[Bug Report] DatePicker value error when type="daterange"

### ISSUE THREAD

**Issue by hunter007** [ElemeFE/element#5347]
### Element UI version
1.3.6

### OS/Browsers version
macos 10.12.5 , google chrome 58

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/steven79/6y68dfdf/1/](https://jsfiddle.net/steven79/6y68dfdf/1/)

### Steps to reproduce
直接选择日期范围即可。
例如，选择2017-06-10 - 2017-07-19，value 则显示
value6 is: [ "2017-06-09T16:00:00.000Z", "2017-07-18T16:00:00.000Z" ]
实际少了8小时。很明显是时区问题，但没有从源代码中发现错误。

### What is Expected?
返回正确的Date 对象

### What is actually happening?
因为时区导致偏差

**Comment by wacky6** [comment]
value 是 UTC 时间

**Comment by hunter007** [comment]
传入 onPick()的时间是带时区的，并且正确。但最终结果却错了。是不是中间什么地方做转换的时候没有考虑时区？

**Comment by Leopoldthecoder** [comment]
最终结果没有错，是 UTC，选的时间是东八区，转成 UTC 自然要减八小时。对它进行格式化不受时区影响：https://jsfiddle.net/6y68dfdf/2/

**Comment by guohuihot** [comment]
这8个小时要怎么处理啊，自己解决？
