### ISSUE TITLE
[Feature Request] List Component

### ISSUE THREAD

**Issue by sylouuu** [ElemeFE/element#5350]
### Existing Component
No

### Component Name
List

### Description
Sometimes you need to use a list instead of data table. I didn't find it. I expected something like this: https://material.angularjs.org/latest/demo/list

**Comment by Leopoldthecoder** [comment]
We have no plan to add this.

**Comment by gluons** [comment]
@Leopoldthecoder Why? I need simple list component.
Sometime, I don't need to use table. I have a list. So, it doesn't have any column.

**Comment by mutil** [comment]
It would be nice if the transfer-panel of el-transfer component was extracted into a List component.
