### ISSUE TITLE
[Bug Report] The form generated by using the render function is not validated using the rules property validation

### ISSUE THREAD

**Issue by mqhe2007** [ElemeFE/element#5351]
### Element UI version
1.3.3

### OS/Browsers version
win10, chrome 58.0.3029.110

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/rpk8tsmy/3/](https://jsfiddle.net/rpk8tsmy/3/)

### Steps to reproduce
无需步骤

### What is Expected?
验证规则生效

### What is actually happening?
验证规则不生效

**Comment by Leopoldthecoder** [comment]
You need to add `prop: 'age'` on FormItem: https://jsfiddle.net/rpk8tsmy/4/
