### ISSUE TITLE
[Bug Report] Pagination paging has bug

### ISSUE THREAD

**Issue by neversaysoso** [ElemeFE/element#5352]
### Element UI version
1.3.6

### OS/Browsers version
windows/chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ns6qLgj4/](https://jsfiddle.net/ns6qLgj4/)

### Steps to reproduce
1.在前往（jumper）输入框里输入任意页码后回车
2.点击上一页下一页按钮或者页码按钮切换页面时，输入框的页码数没有改变

### What is Expected?
前往输入框的页码数与页面上的页码一致

### What is actually happening?
1.在前往（jumper）输入框里输入任意页码后回车
2.点击上一页下一页按钮或者页码按钮切换页面时，输入框的页码数没有改变

ps:1.3.x版本之前分页组件没有这个bug，一切正常

**Comment by Leopoldthecoder** [comment]
Fixed in #5377
