### ISSUE TITLE
The is-active problem of [Feature Request] el-menu

### ISSUE THREAD

**Issue by acodercat** [ElemeFE/element#5358]
### Existing Component
否

### Component Name
el-menu

### Description
当从其他页面router.replace到包含el-menu的页面的时候，相应的is-active不会被加载对应路由的菜单上面，而是放到了default-active上面。

**Comment by Leopoldthecoder** [comment]
这是 Bug Report，不是 Feature Request。请不要因为不想写 demo 就选择 Feature Request。

**Comment by acodercat** [comment]
反正你们知道就行了，希望尽快解决

**Comment by acodercat** [comment]
可以这样解决  
data() {
    return {
      default_active: this.$route.name
    }
  }
