### ISSUE TITLE
[Bug Report] el-autocomplete validation has error when selected

### ISSUE THREAD

**Issue by 15088134140** [ElemeFE/element#5362]
### Element UI version
1.3.6

### OS/Browsers version
all

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/qq352593779/6nobn6p9/6/](https://jsfiddle.net/qq352593779/6nobn6p9/6/)

### Steps to reproduce
1、Focus on the input box
2、Select the drop-down values

### What is Expected?
Through the check

### What is actually happening?
Failed to pass the check

**Comment by elfman** [comment]
In [autocomplete.vue](https://github.com/ElemeFE/element/blob/dev/packages/autocomplete/src/autocomplete.vue#L136-L141), if I remove the `setTimeout` method and write `this.isFocus = false;` in function `handleBlur` directly, this bug will be fixed.
But I saw the comment line said the blur event should be triggered before select event, why?

**Comment by baiyaaaaa** [comment]
#5189
