### ISSUE TITLE
在Dialog组件中的下拉框组件、时间组件内容不显示

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#537]
### ElementUI version
1.0.0-rc.7 

### OS/Browers version
win7/Chrome 54.0.2840.59 m

### Vue version
2.0.3

### Reproduction Link

https://codepen.io/anon/pen/jrQKPO

### Steps to reproduce
点击codepen演示页面 **新增** 按钮，在弹出的Dialog表单中，选择 活动区域下拉框表单项 ，下拉框的 Option 列表层 没有显示，再点击一下或者多下 活动区域下拉框表单项 ，才能正确显示出。活动时间表单项亦是如此。

### What is Expected?
选择 活动区域下拉框表单项或活动时间表单项类似组件（内容在多余的层中显示的组件），要能正确正常显示组件中的内容（这里是下拉框组件中Option列表的内容和时间组件中的日历内容）。
（目前第一次选择，下拉框组件Options列表内容、时间组件中的日历内容显示再Dialog组件后面了）

### What is actually happening?
选择 活动区域下拉框表单项和活动时间表单项时，没有可供选择的Options列表或日历时间内容。

**Comment by Leopoldthecoder** [comment]
Duplicate of #410
