### ISSUE TITLE
[Feature, Request], about, Table-column, Attributes, of, type, which,, value, is, index

### ISSUE THREAD

**Issue by cyzeng-Luca** [ElemeFE/element#5370]
### Existing Component
是

### Component Name
Table

### Description
i have a table list and i use the Table-column Attributes of type which value is index,it's no problem when i read first page,the index is 1,2,3,4,5,6.....,but it's reset index when i read the second page,i konw it's normal ,i want to have a way to get the index for changing the value,like starting with 11,12,13,14 not 1 when i read second page

**Comment by Leopoldthecoder** [comment]
In version 2.0 you can customize row indexes using `index`
