### ISSUE TITLE
[Bug Report] Dropdown drop-down menu is too long, display should be incomplete scroll bar!

### ISSUE THREAD

**Issue by hujianjian187** [ElemeFE/element#5371]
### Element UI version
1.1.2

### OS/Browsers version
win7 64bit chrome 59

### Vue version
2.1.8

### Reproduction Link
[https://jsfiddle.net/5acgh6gu/2/](https://jsfiddle.net/5acgh6gu/2/)

### Steps to reproduce
https://jsfiddle.net/5acgh6gu/2/ 点击出现下拉框 显示不全内容

### What is Expected?
解决方案

### What is actually happening?
解决方案

**Comment by Leopoldthecoder** [comment]
You can add some CSS: https://jsfiddle.net/5acgh6gu/3/

Honestly I don't think such a long dropdown list is good practice.

**Comment by hujianjian187** [comment]
@Leopoldthecoder  think you very much! I will always on your side!
