### ISSUE TITLE
[Bug, Report], typing, bug, with, sougou, typewriting, and, typewriting, system

### ISSUE THREAD

**Issue by wilsonIs** [ElemeFE/element#5372]
### Element UI version
1.3.6

### OS/Browsers version
wind10, ie11

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
The Custom template can not type chinese with sougou typeWriting, and can only type one number with system typewriting.
Seen it at 
[element官网-自定义模板](http://element.eleme.io/#/zh-CN/component/input)
The Reproduction Link can not validate http website?

### What is Expected?
Both typewriting can type chinese or english even number.

### What is actually happening?
some typewritings are not supported to type chinese with Custom template.

**Comment by Leopoldthecoder** [comment]
Is this problem only reproducible on IE11?

**Comment by wilsonIs** [comment]
@Leopoldthecoder yes, problem only found on IE11

**Comment by pengyongisme** [comment]
I met the problem, too. How did you solve it?

**Comment by wilsonIs** [comment]
@pengyongisme  没解决，用autocomplete替代

**Comment by csvwolf** [comment]
Issue is earlier than 2018 so I will close the issue. If you have the same problem later, you can post an new issue and refer it.
