### ISSUE TITLE
How does a [Feature Request] el-upload get a change in the status of a file list when auto-upload is false?

### ISSUE THREAD

**Issue by NieShuai** [ElemeFE/element#5373]
### Existing Component
是

### Component Name
el-upload

### Description
在项目中需要手动上传且只能上传一个文件，但是on-progress、on-change、before-upload等钩子都只在正式上传文件时才能触发。那么在auto-upload为false的情况下怎么获取这些状态信息呢？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by NieShuai** [comment]
个人认为可以作为一个新特性提交issue啊，虽然可以通过ref.uploadfiles获取文件列表，但在用户的角度来说，某些时候还是会造成一些困扰的吧。
