### ISSUE TITLE
[Bug Report] BUG: paging control jump page function

### ISSUE THREAD

**Issue by ysyol** [ElemeFE/element#5375]
### Element UI version
1.3.6

### OS/Browsers version
wind10,chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
使用过一次跳页功能后，再切换页面后，跳页输入框内的值不会改变。直接在跳页输入框中回车，无法跳页。
例子：当前处于“第1页“，跳页到第5页。再次切换到第一页，跳页输入框中的值还是5。然后鼠标点击跳页输入框，不修改值，直接回车，无法跳到第5页

### What is Expected?
能跳页

### What is actually happening?
使用过一次跳页功能后，再切换页面后，跳页输入框内的值不会改变。直接在跳页输入框中回车，无法跳页。
例子：当前处于“第1页“，跳页到第5页。再次切换到第一页，跳页输入框中的值还是5。然后鼠标点击跳页输入框，不修改值，直接回车，无法跳到第5页

**Comment by Leopoldthecoder** [comment]
5377
