### ISSUE TITLE
[Bug Report] Pagination组件jumper中页数显示不正确

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#5378]
### Element UI version
1.3.6

### OS/Browsers version
Chrome/58.0.3029.110

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ats9bhd9/](https://jsfiddle.net/ats9bhd9/)

### Steps to reproduce
引入pagination分页组件 并且添加jumper进layout属性，在点击下一页，上一页，或者页数按钮，jumper中的页数显示正常，但是单独在jumper中输入页数回车跳转页面以后，再在该组件中点击上一页，下一页或页数按钮时jumper中的数字不再跟随页数变化改变。

### What is Expected?
点击页数和上一页，下一页时jumper中的数字跟随当前页数改变

### What is actually happening?
在jumper中输入页数跳转以后，再去点击页数和上下一页按钮改变当前页数时，jumper中的数字不再跟随改变。

**Comment by Leopoldthecoder** [comment]
Fixed in #5377
