### ISSUE TITLE
[Bug Report] Dialog not opening if nested in a component (v-if/ v-show)

### ISSUE THREAD

**Issue by leo-coco** [ElemeFE/element#5379]
### Element UI version
1.3.6

### OS/Browsers version
macOS

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/dbg2e9z2/](https://jsfiddle.net/dbg2e9z2/)

### Steps to reproduce
Replace `<popup v-if="showDialog" :show-dialog.sync="showDialog"></popup>` with `<popup v-show="showDialog" :show-dialog.sync="showDialog"></popup>`

Replace `<popup v-if="showDialog" :show-dialog.sync="showDialog"></popup>` with `<popup :show-dialog.sync="showDialog"></popup>`

### What is Expected?
The pop up should open in the two cases

### What is actually happening?
For the first one, the pop up opens but the content is not displayed
For the second case, the pop up is not displayed at all

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/dbg2e9z2/3/

> `:visible.sync="show"`

This `show` never changes to `true` in those two cases. So you need to update it.

**Comment by luckymore** [comment]
@Leopoldthecoder  where is the `visible-change` in documents?
