### ISSUE TITLE
[Feature Request] 通过子节点直接获取子节点对应的父节点或根节点

### ISSUE THREAD

**Issue by caizhiming8** [ElemeFE/element#5381]
### Existing Component
是

### Component Name
tree

### Description
我把check-strictly设置为true，现在勾选子节点和父节点是没有关系的，所以想通过这样勾选了子节点来获取该子节点的父节点或者根节点

**Comment by konnga** [comment]
可以通过node.parent来获取父节点

**Comment by furybean** [comment]
与 #5653 重复。
