### ISSUE TITLE
[Bug Report] tab-pane's closable prop is not working

### ISSUE THREAD

**Issue by francisfeng** [ElemeFE/element#5382]
### Element UI version
1.3.6

### OS/Browsers version
Windows 10 / Chrome 58

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/francisfeng/pj71jkyw/311/](https://jsfiddle.net/francisfeng/pj71jkyw/311/)

### Steps to reproduce
As has been demonstrated in the jsfiddle, the prop in tab-pane is not working. I am aware the tab-pane only emit tab-remove event as it should be. But putting on a closable prop on a tab-pane has no effect whatsoever. Shouldn't it hide the close button when the closable is set to true?

As I looked into the source code, I found out that the computed prop isClosable is not used in [tab-pane.vue](https://github.com/ElemeFE/element/blob/dev/packages/tabs/src/tab-pane.vue). I think there are some sort of bug.

### What is Expected?
the closable prop in a tab-pane correctly hides the close button.

### What is actually happening?
It still show the close button.

**Comment by SquareBeard** [comment]
This is still not working for me with version 2.0.8
Here is a reproduction link: https://jsfiddle.net/p80u3ttc/
