### ISSUE TITLE
[Bug Report] Slider with step=0 causes crash

### ISSUE THREAD

**Issue by jongeyer** [ElemeFE/element#5385]
### Element UI version
1.3.6

### OS/Browsers version
OSX 10.12.5 / Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/r5dwbcw2/](https://jsfiddle.net/r5dwbcw2/)

### Steps to reproduce
- Using Slider component, set 'step' value to 0.
- Load page in browser

### What is Expected?
I suspect there is a division by zero issue happening somewhere.
I understand one would never set the step to 0 deliberately
So I recommend having a catch and throwing a non-fatal error if step == 0.

### What is actually happening?
Browser hangs and then quickly crashes.

**Comment by Leopoldthecoder** [comment]
Fixed in #5439
