### ISSUE TITLE
After the [Bug Report] tree node is filtered, all nodes are expanded by default, causing the default-checked-keys to be invalid

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#5386]
### Element UI version
1.3.6

### OS/Browsers version
wind7旗舰版/ chrome 58.0.3029.110

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/sxq75oyz/1/](https://jsfiddle.net/sxq75oyz/1/)

### Steps to reproduce
当我输入7的时候，会过滤掉id等于7的这个数据，这些都是正常的，但是树结构会默认全部展开。。。

### What is Expected?
当我输入7的时候，会过滤掉id等于7的这个数据，树结构展开可以自己控制。。。现在项目里面有个页面嵌入了二个tree，根据一个tree的选择项过滤掉另外一个tree的数据，不能选择相同的数据，过滤正常，但是节点默认全部展开了，即时在过滤之后重新初始化一次default-checked-keys 也是无效

### What is actually happening?
过滤数据的时候，节点默认全部展开了

**Comment by purpletianjing** [comment]
这个不是默认全部展开，是在filterNode方法中，return 值应该为data.id == value，就是找到value，返回true
