### ISSUE TITLE
In [Bug Report] strict mode, the message component receives the number type parameter error

### ISSUE THREAD

**Issue by liuzheng644607** [ElemeFE/element#5387]
### Element UI version
1.3.4

### OS/Browsers version
MacOS Sierra/Chrome 59.0.3071.86

### Vue version
2.1.0

### Reproduction Link
[https://jsfiddle.net/liuzheng644607/pj71jkyw/313/](https://jsfiddle.net/liuzheng644607/pj71jkyw/313/)

### Steps to reproduce
this.$message.info(4001);  
当参数为数字的时候报错

### What is Expected?
不报错，正常弹出数字

### What is actually happening?
报错

**Comment by Leopoldthecoder** [comment]
Make sure the parameter is a string before passing it to Message.
