### ISSUE TITLE
When using input in [Feature Request] MessageBox custom message, how do I get the value of this input in the confirmation button?

### ISSUE THREAD

**Issue by jsven** [ElemeFE/element#5389]
### Existing Component
是

### Component Name
MessageBox

### Description
MessageBox 自定义消息时 input元素怎么绑定state中的值，  自定义消息时input框如果不能绑定state中的值那在确认按钮中怎么获取这个input的值？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
