### ISSUE TITLE
Select选择器组件、TimePicker组件、DatePicker组件等一些表单组件选择内容层宽度不能自适应

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#539]
### ElementUI version
1.0.0-rc.7

### OS/Browers version
win7/Chrome 

### Vue version
2.0.3

### Reproduction Link
https://codepen.io/anon/pen/jrQKPO

### Steps to reproduce
在不固定表单和相关表单组件的宽度的情况下，Selection选择器组件、TimePicker组件、DataPicker组件等一些表单组件的内容（Options组件列表、日历列表、时分秒选择列表）层，在改变浏览器窗口的大小时，内容层的宽度没有自适应。

### What is Expected?
在改变浏览器窗口的大小时，这些有着内容层的表单组件，内容层能自适应外界宽度的变化。

### What is actually happening?
在改变浏览器窗口的大小时，这些有着内容层的表单组件，内容层没有自适应外界宽度的变化。

**Comment by changchengqin** [comment]
1.0.0-rc.6是ok的

**Comment by Leopoldthecoder** [comment]
Select 组件由于 popper 的重构出现了这个问题，后面会修掉。TimePicker 和 DataPicker 由于自身内容的原因，应该不会做成宽度自适应的。

**Comment by changchengqin** [comment]
@Leopoldthecoder got it!

**Comment by theharveyz** [comment]
@Leopoldthecoder  您好，我现在用的`v1.2.3` 也遇到了select组件不能自适应的问题，请问是还没修复吗？
