### ISSUE TITLE
The [Bug Report] el-input-number component cannot enter a number greater than 1 with decimals. It can only enter decimal numbers less than 1, and use: step=0.01 also has no effect

### ISSUE THREAD

**Issue by niboac** [ElemeFE/element#5392]
### Element UI version
1.3.6

### OS/Browsers version
chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/cLp4ck7q/](https://jsfiddle.net/cLp4ck7q/)

### Steps to reproduce
输入带小数的数字, 比如23.22, .22 会被忽略.

### What is Expected?
能输入23.22

### What is actually happening?
输入23.22 后, 只剩下23这个整数

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/27176819-add408da-51f6-11e7-8f32-39875e306cd1.gif)

Cannot reproduce

**Comment by niboac** [comment]
Don't input so fast, please input number slowly, the point will disappear
![6 -16-2017 11-01-25](https://user-images.githubusercontent.com/4688442/27210191-38cb5e98-5283-11e7-8377-a65df2a9e221.gif)

**Comment by annofy** [comment]
@niboac 这个input-number 似乎对手速有要求，可以使用el-input然后设置type=number来代替

**Comment by syn-zeta** [comment]
@niboac Perhaps the `debounce` attribute is what you're looking for? It will allow you to specify a delay after an input when the component will validate it, and remove the previous input if it makes the number invalid.

I've set the delay to 1 second here: https://jsfiddle.net/cLp4ck7q/1/

Behavior with non-numeric characters:
![input](https://user-images.githubusercontent.com/26761352/27514864-eb1380e4-594a-11e7-97d3-15a3d0e6b3d0.gif)

**Comment by Leopoldthecoder** [comment]
@syn-zeta Exactly.
@niboac Please add `debounce`.

**Comment by anson-GH** [comment]
{ required: true, pattern: /^\d+$/, message: 'Please enter numeric', trigger: 'blur' }

only accept integer
