### ISSUE TITLE
[Bug Report] el-dialog style question.

### ISSUE THREAD

**Issue by langgo** [ElemeFE/element#5394]
### Element UI version
1.3.6

### OS/Browsers version
window7 / chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://github.com/langgo/element-ui-bug](https://github.com/langgo/element-ui-bug)

### Steps to reproduce
运行项目

点击打开 dialog

### What is Expected?
1. el-dialog 的背景变为红色，宽度变为 300px;
2. el-dialog__wrapper 样式保持不变。

### What is actually happening?
1. el-dialog 样式没有发生变化。
2. el-dialog__wrapper 背景变为红色。

# 注意
<style scoped> 时，两个现象都会出现。
<style> 时，2 现象会出现

我认为这个可以算一个bug。

**Comment by langgo** [comment]
可能更好的做法是 尽量增加，而不是修改。

**Comment by Leopoldthecoder** [comment]
不是 bug。之前的 scoped style 其实不能和自定义组件完美搭配，在 `vue-loader` 的 12.2.0 版本中引入了 `>>>` 选择器，现在可以正常工作了：https://github.com/langgo/element-ui-bug/pull/1/files。相关信息：https://github.com/vuejs/vue-loader/releases/tag/v12.2.0

**Comment by langgo** [comment]
感谢!!
