### ISSUE TITLE
[Bug Report] [Tree] lazy loads all child nodes when setting node checked

### ISSUE THREAD

**Issue by Rranran** [ElemeFE/element#5395]
### Element UI version
1.3.6

### OS/Browsers version
win7

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
选中“region1" , 点击左侧三角展开节点

### What is Expected?
选中region1  或 选中region1及其第一层子节点

### What is actually happening?
选中region1 加载了所有子节点

**Comment by ZhanYishu** [comment]
I encounter the problem too when setting the lazy loading but not setting check-strictly of attribute. If I checked the sub node, it will load all the children nodes all the time.

**Comment by Leopoldthecoder** [comment]
Fixed in #5963
