### ISSUE TITLE
[Bug Report] modifies data through JS and should not trigger change events

### ISSUE THREAD

**Issue by lianer** [ElemeFE/element#5400]
### Element UI version
1.3.4

### OS/Browsers version
all

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/318/](https://jsfiddle.net/pj71jkyw/318/)

### Steps to reproduce
点击 日期 1 按钮。

### What is Expected?
期望不触发 change 事件。

### What is actually happening?
触发了 change 事件。

**Comment by Leopoldthecoder** [comment]
See #6011 for details.
