### ISSUE TITLE
[Bug Report] The event on disabled button is still bubbling

### ISSUE THREAD

**Issue by rukey67** [ElemeFE/element#5402]
### Element UI version
1.3.6

### OS/Browsers version
windows 7

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/rukey67/rmuctogx/](https://jsfiddle.net/rukey67/rmuctogx/)

### Steps to reproduce
put a disabled button，then bind a "click" event on the parent node

### What is Expected?
When click the disabled button, the "click" event on parent node won't  be triggered.

### What is actually happening?
When click the disabled button, the "click" event on parent node has been triggered!

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/rmuctogx/3/

**Comment by rukey67** [comment]
Thank you.
But i still think a disabled button need to have its own specific behavior.
