### ISSUE TITLE
[Bug Report] el-select v-for

### ISSUE THREAD

**Issue by Marsovski** [ElemeFE/element#5407]
### Element UI version
1.3.6

### OS/Browsers version
Any

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/Marsovski/xkyu6qe6/](https://jsfiddle.net/Marsovski/xkyu6qe6/)

### Steps to reproduce
Select list not selected automatic

### What is Expected?
Select list automatic

### What is actually happening?
Select list not selected automatic

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/xkyu6qe6/7/
