### ISSUE TITLE
[Feature Request]  How does reset tree? How does a tree change from synchronous to asynchronous, asynchronously to synchronous?

### ISSUE THREAD

**Issue by docikaci** [ElemeFE/element#5409]
### Existing Component
是

### Component Name
tree

### Description
需求是这样的：点击一个添加按钮，从tree上选择某个人， tree是异步加载，问题是tree上面有个搜索框，搜索是后台搜索完，然后全部数据返回，相当于同步加载，（之前的异步tree，此时是同步的）， 不输入关键字 就会回到刚刚的异步tree（同步又转成异步，而且需要重置）
所以需要三个方法： load方法怎么重新调起（非首次进入时） ，重置一个tree，或者销毁tree在重新来一遍？谢谢

**Comment by KTDefTnT** [comment]
所以解决办法是啥啊，我用了两棵树，一棵用来展示搜索，一颗用来热加载，但是展示搜索的树会主动去调用 热加载树的load....

**Comment by docikaci** [comment]
@KTDefTnT  用两个tree，load方法名 不要一致 ，相当于两套，完全不同的容器，不同的方法

**Comment by KTDefTnT** [comment]
我可以加你问下吗

**Comment by KTDefTnT** [comment]
我现在碰到的问题跟你描述的一样，我两个颗树放在不同的div里面，但是我如果搜索的树 也用load 方法的话，那后台一次返回的数据，我必须前端做一个处理，数据特别庞大，没法处理，只能用树的  :data属性直接进行展示， 求解啊

**Comment by KTDefTnT** [comment]
试了两个load使用不同的额方法名，用v-if进行销毁树， 但是搜索树调用的laod方法竟然不是自己的那个，而是 热加载树的 load....

**Comment by MiracleTanC** [comment]
解决了吗,重置 load 方法

**Comment by nekooee** [comment]
I need to "reset method" for the tree draggable. how can I? please help me
