### ISSUE TITLE
el-dialog  弹对话框的这个有问题，老是报错。这个零件已经引入但是报错。Ｗrite里面是我最简洁的代码。

### ISSUE THREAD

**Issue by Zhi-Peng** [ElemeFE/element#541]
<template>
    <el-dialog title="提示" v-model="dialogVisible">
      <span>这是一段信息</span>
      <span slot="footer" class="dialog-footer">
        <el-button @click.native="dialogVisible = false">取 消</el-button>
        <el-button type="primary" @click.native="dialogVisible = false">确 定</el-button>
      </span>
    </el-dialog>
</template>

<script>
    export default {
        data () {
            return {
                dialogVisible: false
            }
        }
    }
</script>

**Comment by Leopoldthecoder** [comment]
代码在哪里？

**Comment by Zhi-Peng** [comment]
<template>
    <el-dialog title="提示" v-model="dialogVisible">
      <span>这是一段信息</span>
      <span slot="footer" class="dialog-footer">
        <el-button @click.native="dialogVisible = false">取 消</el-button>
        <el-button type="primary" @click.native="dialogVisible = false">确 定</el-button>
      </span>
    </el-dialog>
</template>

<script>
    export default {
        data () {
            return {
                dialogVisible: false
            }
        }
    }
</script>
