### ISSUE TITLE
[Bug Report] el-checked-group does not support the select object array way?

### ISSUE THREAD

**Issue by Caraws** [ElemeFE/element#5412]
### Element UI version
1.3.6

### OS/Browsers version
chorme

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/hgm6emvj/](https://jsfiddle.net/hgm6emvj/)

### Steps to reproduce
如链接所示, 传入数组对象

### What is Expected?
希望拿到数组对象里的item, 并且能够全选

### What is actually happening?
无法全选, 是我哪里写错了吗

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/hgm6emvj/1/
