### ISSUE TITLE
The tooltip in the [Bug Report] Table component cannot be selected by the mouse

### ISSUE THREAD

**Issue by baijunjie** [ElemeFE/element#5413]
### Element UI version
1.3.6

### OS/Browsers version
Windows/7, Chrome/53, IE/11

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/0LqtyLrv/](https://jsfiddle.net/0LqtyLrv/)

### Steps to reproduce
使用 Table 的 show-overflow-tooltip，在出现 tooltip 时无法选中其内容。

### What is Expected?
在 Table 中可以实现溢出隐藏多余内容，并显示3点。且在 tooltip 出现时能选中其内容。

### What is actually happening?
使用 Table 的 show-overflow-tooltip
可以实现溢出隐藏多余内容，并显示3点。但是无法选中 tooltip 内容。

在 Table 中直接使用 tooltip
可以选中 tooltip 内容。但是无法实现溢出隐藏多余内容，并显示3点。
而且  tooltip 会始终显示，无法实现只在溢出隐藏时显示  tooltip。

目前在官方文档中只有  show-overflow-tooltip 属性可以使表格实现内容限制在1行，并溢出隐藏显示3点。
没有发现其他属性可以实现仅溢出隐藏显示3点，而不要 tooltip。这直接导致我的需求无法实现。

**Comment by Leopoldthecoder** [comment]
The tooltips in Table are not `enterable`, and we have no plan to add a configuration regarding this. I'm afraid you'll have to implement this on your end.

**Comment by xianshenglu** [comment]
Hope you can support this.
