### ISSUE TITLE
When [Bug Report] before-upload returns false, the on-remove hook function is triggered

### ISSUE THREAD

**Issue by Cc9410** [ElemeFE/element#5419]
### Element UI version
1.3.6

### OS/Browsers version
mac os/chorme 

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ck4mkuso/](https://jsfiddle.net/ck4mkuso/)

### Steps to reproduce
1.成功上传图片后 给test赋值
2.重新上传图片 触发before-upload  test存在 返回false
3.再重新上传图片，上传成功

### What is Expected?
希望before-upload钩子函数返回false后不触发on-remove钩子函数

### What is actually happening?
before-upload钩子函数返回false后触发on-remove钩子函数

**Comment by baiyaaaaa** [comment]
when the before-upload hook function returns false and it will trigger the on-remove hook function, it's design in , not a bug

**Comment by gooqiao** [comment]
@baiyaaaaa 为什么要这么设计呢？不是很理解。毕竟我又不想移除它。
