### ISSUE TITLE
表单组件设置为 small，大小不统一

### ISSUE THREAD

**Issue by changchengqin** [ElemeFE/element#542]
### ElementUI version
1.0.0-rc.7

### OS/Browers version
win7/Chrome 54

### Vue version
2.0.3

### Reproduction Link
https://codepen.io/anon/pen/ALmmvy

### Steps to reproduce
将 input组件、selection组件、按钮组件的size属性都设置为small

### What is Expected?
高度能统一

### What is actually happening?
各组件的高度不一致

**Comment by furybean** [comment]
与 #490 重复，先关了。
