### ISSUE TITLE
[Bug Report] hiddenTextarea packaging compile error

### ISSUE THREAD

**Issue by lh4111** [ElemeFE/element#5420]
### Element UI version
1.3.5

### OS/Browsers version
OS X  10.12  node 7.7.1  Chrome 61

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/none](https://jsfiddle.net/none)

### Steps to reproduce
使用了 TextArea 
npm run build之后出现了
```
ERROR in js/vendor.9e4c866683eec3fc9c15.js from UglifyJs
Unexpected token: name (hiddenTextarea) [js/vendor.9e4c866683eec3fc9c15.js:90587,4]
```
代码压缩失败到时 vendor.js没有被压缩

### What is Expected?
vendor代码正确被压缩

### What is actually happening?
vendor代码没有被压缩

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
