### ISSUE TITLE
[Bug Report] el-input maxlength="44" 必须使用:maxlength

### ISSUE THREAD

**Issue by mykite** [ElemeFE/element#5424]
### Element UI version
1.3.6

### OS/Browsers version
win7/chrome53.0.2774.3 

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
maxlength="4"
[Vue warn]: Invalid prop: type check failed for prop "maxlength". Expected Number, got String.

found in

### What is Expected?
maxlength="4"能直接使用

### What is actually happening?
maxlength="4"不影响功能 console抛错

**Comment by Leopoldthecoder** [comment]
That's how Vue works.

**Comment by tianhongye** [comment]
[Vue warn]: Invalid prop: type check failed for prop "maxlength". Expected Number, got String.

**Comment by Crise420WMT** [comment]
i got the common problem....

**Comment by Yawytya** [comment]
@tianhongye @mykite Mabye you can edit like `:maxlength="42"`

**Comment by leotm** [comment]
I noted this works with `input` of `type="text"`, but not of `type="number"`.

**Comment by yoyo837** [comment]
@leotm Thanks! This note is a great help to me.

@Leopoldthecoder I think it should support `type = "number"`.

**Comment by 343195246** [comment]
@youyou837 我也觉得应该支持 type = "number"
