### ISSUE TITLE
[Feature Request] Upper case input

### ISSUE THREAD

**Issue by Lukino2000** [ElemeFE/element#5425]
### Existing Component
Yes

### Component Name
el-input

### Description
Is there any way to have an UpperCase only input?

**Comment by alanaasmaa** [comment]
Im newbie but yry this.

```
<el-input type="text" :value="customer.name.toUpperCase()" @input="customer.name = $event.target.value.toUpperCase()">
```

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/4qtutonn/ .

Or https://jsfiddle.net/4qtutonn/1/ in @alanaasmaa 's style
