### ISSUE TITLE
How does table append inherit the upper row row?

### ISSUE THREAD

**Issue by luchanan** [ElemeFE/element#5428]
### Element UI version
1.3.6

### OS/Browsers version
win10 chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ivanlu/tx6s9u83/](https://jsfiddle.net/ivanlu/tx6s9u83/)

### Steps to reproduce
table添加了append发现最终生成的是:
```
<table>
  <tbody>
<tr></tr>
<tr></tr>
<tr></tr>
<div>32323</div>
 <tbody>
</table>
```

### What is Expected?
问的是：如何用append最终生成下面这样
```
<table>
  <tbody>
<tr></tr>
<tr></tr>
<tr></tr>
<tr><td>32323</td></tr>
 <tbody>
</table>
```
就是说继承上面的tr里面每个单元格，就是说不用summary-method，但是可达到summary-method这种数据展示

![image](http://7qn7ih.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170617132247.png)

### What is actually happening?
table添加了append发现最终生成的是:
```
<table>
  <tbody>
<tr></tr>
<tr></tr>
<tr></tr>
<div>32323</div>
 <tbody>
</table>
```

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
