### ISSUE TITLE
[Feature Request] table sorted with the integer column

### ISSUE THREAD

**Issue by luguosheng1314** [ElemeFE/element#5429]
### Existing Component
Yes

### Component Name
el-table

### Description
el-table will sorted with the default way ‘string compare’, but  when i want to sort a integer column, it show a unexpected result   for example it will sorted to be  1, 11, 12, 2, 3  and i want 1, 2, 3, 11, 12

**Comment by Leopoldthecoder** [comment]
Use `sort-method`.
