### ISSUE TITLE
The drop-down option for the [Bug Report] Select selector is not positioned to the selected location

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/element#5430]
### Element UI version
1.3.6

### OS/Browsers version
OS X 10.11.6   Chrome  58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/mfnan1x7/](https://jsfiddle.net/mfnan1x7/)

### Steps to reproduce
点击Cascader 级联选择器，Cascader 级联选择器的下拉选项中，没有定位到当前所选项的位置，需要滚动到底部才能看到所选项。
重复点击Select 选择器使其获得焦掉再失去焦点，在第2、4、6、8...次点击Select 选择器的时候，  Select 选择器的下拉选项中没有定位到当前所选项的位置，需要滚动到底部才能看到所选项。

这两个选择器的问题十分相似，所以就一起在这里说了。

### What is Expected?
点击Cascader 级联选择器和点击Select 选择器，下拉选项能够定位到当前所选项的位置。

### What is actually happening?
点击Cascader 级联选择器和点击Select 选择器，下拉选项没有定位到当前所选项的位置。

**Comment by wacky6** [comment]
@Leopoldthecoder

I would like to suggest the use of `scrollIntoView()` for Select and Cascader.

Current implementation uses `getBoundingClientRect()` then computes scrollTop, which seems unnecessarily complicated.

**Comment by Leopoldthecoder** [comment]
@wacky6 Cool, I didn't know about this. I'll see what I can do.

**Comment by Leopoldthecoder** [comment]
@wacky6 Unfortunately `scrollIntoView` may not be the correct solution: https://jsfiddle.net/jowjnsx7/1/

It seems when `scrollIntoView` is called, the browser will scroll every ancestor of the target element until it's positioned at the top of the viewport. I don't if there is a way to scroll only its parent element.

**Comment by wacky6** [comment]
Then we should probably stick with current implementation.

I will look into Select's problem.

**Comment by wacky6** [comment]
@acmeid 

Please verify this fix works: https://jsfiddle.net/5u6dqf02/
Relevant commit: https://github.com/wacky6/element/commit/16c8ca3cb12a666e575d63702b70f1c775d02f5a

**Comment by acmeid** [comment]
@wacky6 非常感谢，示例中的Select没有问题，已修复。但是Cascader...

**Comment by wacky6** [comment]
慢慢来吧。Cascader的实现目前没有这个功能。

**Comment by wacky6** [comment]
@acmeid @Leopoldthecoder  

I've wrote an implementation for Cascader, take a look.

This implementation sets `scrollTop` before transition starts. It solves the flickering problem.

The select on the right is a reference to current implementation.

https://jsfiddle.net/ptq7x7wx/1/

**Comment by wacky6** [comment]
@Leopoldthecoder 

Any thoughts on this new (flicker-free) implementation of Cascader?

Should this be considered for Select and other drop-down menus? Perhaps next major version?

**Comment by Leopoldthecoder** [comment]
@wacky6 Awesome. Could you make a PR?

 If you are interested, Select, Cascader and TimeSelect are the only three components that need this feature. We may start working on the next major version later this month, but PRs on this feature can be made anytime you want.

**Comment by wacky6** [comment]
Great, I will work on that.

**Comment by wacky6** [comment]
@acmeid See: https://github.com/ElemeFE/element/pull/5789

**Comment by acmeid** [comment]
@wacky6 太棒了，希望早点在下个版本看到，谢谢~

**Comment by wacky6** [comment]
PR merged, this issue can be closed now.  😄
