### ISSUE TITLE
[Feature Request] Separate label and value in el-radio-group

### ISSUE THREAD

**Issue by matthiashagemann** [ElemeFE/element#5432]
### Existing Component
Yes

### Component Name
el-radio-group

### Description
It would be beneficial if we could set custom texts for each radio item. Currently, there is no attribute available for custom texts which is why label == text. What if we want to show a different text in the GUI than the label? Something like this:

```
<el-radio-group v-model="city">
  <el-radio-button label="NY">New York</el-radio-button>
</el-radio-group>
```

**Comment by Leopoldthecoder** [comment]
It's supported: https://jsfiddle.net/46ho8wj5/

**Comment by putuoka** [comment]
> It's supported: https://jsfiddle.net/46ho8wj5/

How to use it without using {{ item.alias }} curly brace but binding value ?
for ex:

```
<el-radio-group v-model="radio1">
  <el-radio-button v-for="item in city"  :label="item.name">{{ item.alias }}</el-radio-button>
</el-radio-group>
```
