### ISSUE TITLE
The [Feature Request] dynamically loads the tree to set the leaf node

### ISSUE THREAD

**Issue by lzp3021** [ElemeFE/element#5435]
### Existing Component
Yes

### Component Name
tree

### Description
 官方案例中动态加载树需要点击才知道有没有下级。能不能增加一个属性设置末级节点（叶子节点），即不能再展开

**Comment by hawtim** [comment]
我也有这样的需求，+1
translation
I also have this requirement

**Comment by microboat** [comment]
props里面可以设置一个isLeaf属性的。

**Comment by Leopoldthecoder** [comment]
楼上正解。

**Comment by hawtim** [comment]
@microboat 我在文档里看到的props只能传三个参数。没有找到isLeaf参数，请问你是在哪里设置的？
以及是否是设置了isLeaf属性还需要该节点的children数组不为空才能有效？

**Comment by microboat** [comment]
文档里面好像没写，可以阅读源码看到。这个isLeaf属性的值可以从后台生成。例如后台的数据是[{ID:123,Text:'aaaaa',Children:[],IsLeaf:true}]
在tree的props就写{label:'Text', children:'Children', isLeaf:'IsLeaf'}
这样渲染出来的节点前面就是叶子图标。

**Comment by hawtim** [comment]
@我按照你的写法处理了，但是还是没有效果。请问你的数据是一个节点一个节点异步获取的么？ @microboat
