### ISSUE TITLE
Inner workings of the examples/pages Vue components and templates

### ISSUE THREAD

**Issue by wiinci** [ElemeFE/element#5436]
### Existing Component
Yes

### Component Name
examples/route.config.js

### Description
Hello team,

I’m a big fan of Element UI.

I’m trying to work on a doc generator for my own project and I have followed your build process using vue-markdown-loader and render methods but I cannot get the markdown to render with the Vue component inside the demo-block.

Since I don’t have public access to your examples/pages/en-US folders, it is impossible to know if I’m missing anything in there. Could you please share at least one example from pages so I know what to include in the script and Vue template?

Thanks!

**Comment by Leopoldthecoder** [comment]
The English doc folder is https://github.com/ElemeFE/element/tree/dev/examples/docs/en-US .
