### ISSUE TITLE
[Feature Request] menu-align attribute in el-submenu

### ISSUE THREAD

**Issue by gfigueroa** [ElemeFE/element#5441]
### Existing Component
Yes

### Component Name
el-submenu

### Description
Add a menu-align attribute to the el-submenu as in the el-dropdown component:

![el-submenu](https://user-images.githubusercontent.com/1941240/27261328-8a05f4de-5473-11e7-8093-7e1fcfc7f390.png)

**Comment by conn4575** [comment]
有进展吗，最新的V2.3.7好像还是存在这个问题
