### ISSUE TITLE
[Bug Report] DateTimePicker cannot be required on demand

### ISSUE THREAD

**Issue by chairuosen** [ElemeFE/element#5445]
### Element UI version
1.3.7

### OS/Browsers version
mac 10.10

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/#fake-link](https://jsfiddle.net/pj71jkyw/#fake-link)

### Steps to reproduce
```
import {DateTimePicker} from 'element-ui';
console.log(DateTimePicker) // got undefined
```
and also no DateTimePicker in the bottom list of this page http://element.eleme.io/#/en-US/component/quickstart
so i guess you forgot to export it

### What is Expected?
get component by `import {DateTimePicker} from 'element-ui';`

### What is actually happening?
got undefined

**Comment by Leopoldthecoder** [comment]
DateTimePicker is not a separate component, it's just a type of DatePicker. Import DatePicker and set `type="datetime"`, and you'll get a DateTimePicker.
