### ISSUE TITLE
[Bug Report] Avatar upload not working

### ISSUE THREAD

**Issue by fzs1994** [ElemeFE/element#5446]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 16.04 / Chrom 59

### Vue version
2.3.4

### Reproduction Link
[  https://elementui.github.io/issue-generator](  https://elementui.github.io/issue-generator)

### Steps to reproduce
Get it yourself

### What is Expected?
Solution immediately

### What is actually happening?
Avatar input not working

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
