### ISSUE TITLE
about the "visible-change" i can get the visible?

### ISSUE THREAD

**Issue by chouchou723** [ElemeFE/element#5447]
am i misunderstand this method?
is this a correct usage that i just want to print the 'true' ,when the dropdown appear
' <el-dropdown @visible-change="getData(val)" >'
'methods:{
getData(val){
               console.log(val)
            },
}'

how can i get the parameter?the 'true' and the 'false'
出现则为 true，隐藏则为 false

**Comment by weidadedawei** [comment]
`<el-dropdown  @visible-change="dropdownChange" >`

` methods: {
            dropdownChange(val){
                debugger
                if(val){

                }
            }
        },`
