### ISSUE TITLE
[Bug, Report], about, the, visible-change, I, can't, get, the, result, visible-change's

### ISSUE THREAD

**Issue by chouchou723** [ElemeFE/element#5448]
### Element UI version
1.3.7

### OS/Browsers version
win 10/chrome

### Vue version
2.3.4

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
i want to get the parameter,the 'true' and the 'false'
出现则为 true，隐藏则为 false

### What is Expected?
am i misunderstand this method?
is this a correct usage that i just want to print the 'true' ,when the dropdown appear
' <el-dropdown @visible-change="getData(val)" >'
'methods:{
getData(val){
console.log(val)
},
}'

how can i get the parameter?the 'true' and the 'false'
出现则为 true，隐藏则为 false

### What is actually happening?
i can get the 'true' or 'false'

**Comment by Leopoldthecoder** [comment]
Simply `<el-dropdown @visible-change="getData" >`
