### ISSUE TITLE
Does the [Bug Report] $msgbox not re generate the contents of the frame when calling each other? Will they interfere with each other and retain the last state?

### ISSUE THREAD

**Issue by jochenshi** [ElemeFE/element#5452]
### Element UI version
1.3.6

### OS/Browsers version
win7 64bit /chrome 58.0.3029.110

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/jochenshi/daxm3450/1/](https://jsfiddle.net/jochenshi/daxm3450/1/)

### Steps to reproduce
分别点击handle1, handle2

### What is Expected?
期待每次点击生成的弹框中间各自有各自的状态，按钮的默认点击的次数都为0 ，且不会相互干扰

### What is actually happening?
两者的点击次数会互相影响，互相相加，好像并不是各自生成一个互不干扰的初始状态的弹框

**Comment by Leopoldthecoder** [comment]
It's because Vue automatically caches `text-button` instance. To avoid caching, please add a `key`: https://jsfiddle.net/daxm3450/2/
