### ISSUE TITLE
[Bug Report] [upload] Upload, the, same, file, continuously

### ISSUE THREAD

**Issue by alixez** [ElemeFE/element#5455]
### Element UI version
1.3.7

### OS/Browsers version
chrome 58.0.3029.110

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/3mqj03Lr/](https://jsfiddle.net/3mqj03Lr/)

### Steps to reproduce
在使用upload的手动上传:auto-upload="false"时，连续选取两次相同的文件，第二次不会选取成功；将上一次选取的文件删除后不能再立即选取。

### What is Expected?
是否可以新增一个能多次添加相同文件的属性；删除上一次选取的文件后应该可以再立即选取。

### What is actually happening?
不能多次添加相同文件；删除上一次选取的文件后应该不能再立即选取。

**Comment by Leopoldthecoder** [comment]
Fixed in #5706
