### ISSUE TITLE
MessageBox 弹框 - 确认消息 点开后确定按钮样式不对

### ISSUE THREAD

**Issue by Cheneytt** [ElemeFE/element#5457]
1.点开弹框
![image](https://user-images.githubusercontent.com/18325579/27280711-85bac488-551b-11e7-9697-e2df15102265.png)
2.确定按钮默认样式是被按下的样式，鼠标移入也没有hover事件
![image](https://user-images.githubusercontent.com/18325579/27280733-9ae45888-551b-11e7-8342-f81b7fbf667d.png)
期望：没被按下的样式

**Comment by Pingren** [comment]
I also found this issue today.
