### ISSUE TITLE
Carousel切换时会在切换的过程中短暂的闪现出最后一张图

### ISSUE THREAD

**Issue by ansiz** [ElemeFE/element#5462]
Element UI version

1.3.7

OS/Browsers version

Chrome 59

Vue version

2.3.4

Reproduction Link

https://jsfiddle.net/ta8f5whL/2/

Steps to reproduce

从第三张图切回第二张的过程中，能看到第四张图短暂出现过，从颜色上也能明显看出来往回翻页的时候，最后一张有短暂的闪现。在我提供的重现链接中，仔细观察第二张到第三张图的来回切换，能发现本应只出现两个颜色，实际出现了三个颜色。

What is Expected?

希望翻页时不会闪现最后一张图

What is actually happening?

翻页的时候，最后一张图有短暂的闪现

**Comment by aline2013** [comment]
我也遇到同样的问题，图片首尾切换不会，但是位于中间的都会，demo: https://jsfiddle.net/v8tfttw6/2/

**Comment by ansiz** [comment]
@aline2013 我用swiper替代了这个组件，你可以试试

**Comment by Leopoldthecoder** [comment]
Fixed in #6394
