### ISSUE TITLE
When [Feature Request] introduces components on demand, can the components of the current component be annotated on the component documentation?

### ISSUE THREAD

**Issue by dsky1990** [ElemeFE/element#5465]
### Existing Component
Yes

### Component Name
在按需引入组件的时候能不能在组件文档上注明当前组件依赖的组件

### Description
在按需引入组件的时候能不能在组件文档上注明当前组件依赖的组件，很多组件依赖的组件都不清楚造成报错和花费时间去查找。

**Comment by Leopoldthecoder** [comment]
Element internally takes care of component dependencies so that when you import them, you don't have to care about them. If you run into problems when importing a component, please tell us which component you're using. Maybe we overlooked something.
