### ISSUE TITLE
[Bug Report] In upload component's  on-remove event is executing before. However it should be executed on "X" thumbnail remove icon. I am not able to execute function on-remove event 

### ISSUE THREAD

**Issue by amitneg1** [ElemeFE/element#5469]
### Element UI version
1.3.6

### OS/Browsers version
any

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/bjo73uj8/](https://jsfiddle.net/bjo73uj8/)

### Steps to reproduce
step 1. Here am sending custom param :on-remove="handleRemove('icon')"
step 2. click on thumbnail 'X' icon and see handleRemove function not called.
Step 3. Nothing print in console.log

### What is Expected?
on-remove="handleRemove('icon')" // pass custom parameter and get parameter in function body.

### What is actually happening?
custom parameter is not getting in function body.

**Comment by Leopoldthecoder** [comment]
Since `on-remove` is a prop instead of an event listener, you need to pass to it a function like this: https://jsfiddle.net/bjo73uj8/1/

**Comment by amitneg1** [comment]
Thanks it's working
