### ISSUE TITLE
[Feature Request] wants to select month, range, or year range

### ISSUE THREAD

**Issue by Tickly** [ElemeFE/element#5473]
### Existing Component
是

### Component Name
DatePicker

### Description
不知道现在能不能选择时间范围，但是最小单位是月，或者是年。
如果没有希望能加上这些功能，针对一些报表页面，基本都是按月或者按年的范围去查看。
比如今年的某个季度，或者最近两年。

**Comment by Leopoldthecoder** [comment]
Generally date range targeted at month or year can be implemented by putting on the page two separate DatePickers representing starting and ending date respectively. So we have no plan to add month and year support in range picking.
