### ISSUE TITLE
el-select and el-cascader fixed width

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#5478]
### Element UI version
1.3.7

### OS/Browsers version
Linux Chrome / Firefox - same issue noted on Windows etc.

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/340/](https://jsfiddle.net/pj71jkyw/340/)

### Steps to reproduce
```
  <el-row>
   <h3>
   Should Be Full Width
   </h3>
    <el-col :span="24">
      <el-input placeholder="I'm full width" />
    </el-col>
  </el-row>
  <el-row>
    <el-col :span="24">
      <el-select v-model="form1">
        <el-option label="Low" value="Low"></el-option>
        <el-option label="Medium" value="Medium"></el-option>
        <el-option label="High" value="High"></el-option>
        <el-option label="Critical" value="Critical"></el-option>
      </el-select>
    </el-col>

    <br />

    <h3>Should Be Half Width</h3>
    <el-row>
      <el-col :span="12">
        <el-input placeholder="I'm full width" />
      </el-col>
    </el-row>

    <el-row>
      <el-col :span="12">
        <el-select v-model="form2">
          <el-option label="Low" value="Low"></el-option>
          <el-option label="Medium" value="Medium"></el-option>
          <el-option label="High" value="High"></el-option>
          <el-option label="Critical" value="Critical"></el-option>
        </el-select>
      </el-col>
    </el-row>
```

### What is Expected?
That the component will resize to the space of the surounding container, in the case the `<el-col> `element.

### What is actually happening?
The el-select and el-cascader are staying as fixed width. Which is contrary to the behaviour of all other element-ui components which resize to container widtth.

**Comment by Leopoldthecoder** [comment]
For now you can override Select's style: https://jsfiddle.net/pj71jkyw/341/

We'll see if we should keep form components behave same way in the next major version.
