### ISSUE TITLE
vue升级后el-table-column组件自定义内容失效

### ISSUE THREAD

**Issue by sumWang** [ElemeFE/element#5480]

**Comment by aztack** [comment]
我也遇到了相同问题。但问题应该不在element组件。最终定位到：
![image](https://user-images.githubusercontent.com/782871/27474039-a6a9d9d4-5833-11e7-9b72-34540f7e5098.png)

下面是正确渲染时打的断点
![image](https://user-images.githubusercontent.com/782871/27474025-985c1270-5833-11e7-8400-dedb03f5a938.png)

同一个组件放到不同工程中，工程A可以正常渲染，工程B不可以。
切换了element1.2.9,1.3.6,1.3.7A总是可以，B总是不可以。
应该跟工程配置相关。还在排查中...

**Comment by huqiliang** [comment]
遇到了一样的问题 按你说的vue换成2.2.6后问题消失
