### ISSUE TITLE
[Feature Request] PROPOSAL: when el-table selection changed, update the summary cell

### ISSUE THREAD

**Issue by WLyKan** [ElemeFE/element#5483]
### Existing Component
Yes

### Component Name
el-table

### Description
When show-summary and type="selection" is enabled, the summary should update if the selection-change method is triggered.

**Comment by Leopoldthecoder** [comment]
In this case, you can write your own `summary-method`.

**Comment by WLyKan** [comment]
@Leopoldthecoder I have no idea how to do it,  is there any method to know the selected row status, and rerender the table.
Give me a hint

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gdmzumwq/
