### ISSUE TITLE
[Bug Report] can not pick the last moment of a day 

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#5484]
### Element UI version
1.3.7

### OS/Browsers version
all

### Vue version
2.3.4

### Steps to reproduce
1. select an range on the date-time-picker
2. the result will be like this:
![image](https://user-images.githubusercontent.com/1060733/27365382-6a53401e-5672-11e7-8145-8e1d9e02ca12.png)

### What is Expected?
what i really need is 2017-06-08 00:00:00 - 2017-07-04 59:59:59
could you add an attribute to toggle the default behavior?
or,could you tell me the way to extend the official component?

**Comment by zzzgit** [comment]
if you don't want to add an attribute for this recently,please tell how to extend the official class by myself

**Comment by wacky6** [comment]
Not sure what you are trying to do.

If you only want '00:00:00' and '23:59:59', date-picker seems to be a better choice.

**Comment by Leopoldthecoder** [comment]
Since you're using DateTimePicker, you can choose the time part as you want.
