### ISSUE TITLE
The pop-up box created by [Bug Report] this.$alert will not disappear when the route changes.

### ISSUE THREAD

**Issue by AfterThreeYears** [ElemeFE/element#5489]
### Element UI version
1.3.7

### OS/Browsers version
mac

### Vue version
2.3.4

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/message-box](http://element.eleme.io/#/zh-CN/component/message-box )

### Steps to reproduce
首先点击打开message-box 使用this.$alert创建弹出框，然后点击浏览器的返回按钮，弹窗不消失

### What is Expected?
弹窗消失

### What is actually happening?
因为是快速创建的alert是动态插入的，那么route改变的时候不会销毁动态插入的内容。
是否能够监听hashchange的时候去处理弹窗

**Comment by Leopoldthecoder** [comment]
Added in #6043
