### ISSUE TITLE
[Feature Request] Insert Base64 img tag in table cell

### ISSUE THREAD

**Issue by Fer17** [ElemeFE/element#5496]
### Existing Component
Yes

### Component Name
table

### Description
I'm trying to show a base64 img in a cell table.

In the "html" column:
`<el-table-column prop="graphic" label="Your Image" :formatter="formatter"></el-table-column>`

In the methods:
```
formatter(row, column) {
    if (row.graphic.length>0) {
        return '<img src="'   row.graphic  '">';
    } else {
        return '(none)';
    }
}
```
The row.graphic has value (f.e.): "data:image/jpeg;base64,/9j/4AAQSkZJ......." etc.

But the result is a string (I guess) and in the cell I only can see the `<img src="data:image/jpeg;base64,/9j/4AAQSkZJ...">`

Anything wrong in my aproach? Or any other way avoiding formatters?

Thank you in advance and congrats for such wonderful job. Well done!

**Comment by Fer17** [comment]
Of course the line 

`return '<img src="'   row.graphic  '">';`

must be read as

`return '<img src="' + row.graphic + '">';`

Sorry for the mistake in the code transcription.

**Comment by Leopoldthecoder** [comment]
If you are using `formatter` and trying to return a DOM element, you should use `$createElement`, otherwise it will be treated as a string literal: https://jsfiddle.net/b2oa28mp/ .

And, in this case, I prefer scoped template: https://jsfiddle.net/b2oa28mp/1/ .

**Comment by Fer17** [comment]
Brilliant (and very fast render, by the way).

Thank you!
