### ISSUE TITLE
[Bug Report] build error

### ISSUE THREAD

**Issue by krissss** [ElemeFE/element#5497]
### Element UI version
1.3.7

### OS/Browsers version
win10

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
npm run build
// 去除 webpack 的 UglifyJsPlugin 编译正常

### What is Expected?
build success

### What is actually happening?
ERROR in static/js/vendor.74e75a6a11ba645ad266.js from UglifyJs
Unexpected token: punc (() [static/js/vendor.74e75a6a11ba645ad266.js:126197,10]

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
