### ISSUE TITLE
[Bug Report] how to hide popover？

### ISSUE THREAD

**Issue by jingxiawl** [ElemeFE/element#5499]
### Element UI version
1.3.7

### OS/Browsers version
win7/chrome 58.0.3029.110

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/jingxiawl/evyeh1y0/2/](https://jsfiddle.net/jingxiawl/evyeh1y0/2/)

### Steps to reproduce

1、Loop data, each data has a delete button. 
2、when  I click the  delete button  can pop up popover,
3、how can i close  the popover?

### What is Expected?
click the the OK button or the Cancel button can close the popover

### What is actually happening?

I do not know how to write the close event, the official website through the v-model to control the display, but also a number of data to do so? Is there a way to close directly?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/evyeh1y0/3/

**Comment by jingxiawl** [comment]
Does that mean i have to deal with my data? Can only be achieved through this way? Feeling is not very reasonable, the background back to the data without the field, the front also forced in each plus a field. Hope to have a better way to achieve

**Comment by eidonjoe** [comment]
@Leopoldthecoder 如果触发方式为hover 这种方式还可以满足吗

**Comment by lufli** [comment]
My way might be stupid, but solve my problem quickly.

I just find another element on the DOM and invoke click() method. Then the popover element flur automatically.

https://jsfiddle.net/hpvzqfcs/

**Comment by ngohoangyell** [comment]
You can try this:
```
<i class="fas fa-times float-right" @click="closePopover"></i>

methods: {
  closePopover(event) {
    event.target.parentElement.parentElement.style.display = "none"
  }
}
```

**Comment by lehuuthoct** [comment]
You can do it with Jquery. Below is an example when clicking a button with **@click** event.

```
function confirmAndClose(event) {
  let el = event.toElement.closest('.el-popover');
  $(el).css('display', 'none');
}
```
