### ISSUE TITLE
[Bug Report] 使用v-for 渲染多个表单后，表单验证出现的问题

### ISSUE THREAD

**Issue by liujinyang1994** [ElemeFE/element#5501]
### Element UI version
1.3.7

### OS/Browsers version
Mac/Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/345/](https://jsfiddle.net/pj71jkyw/345/)

### Steps to reproduce
首先我有一个数组，然后数组每一项都是我的表单内容。
我使用`v-for`进行遍历，并且对表单进行验证的设置。

### What is Expected?
我期待的是，每个表单都单独可以进行验证。

### What is actually happening?
但实际上，每个表单都不进行验证了或者是验证的不够准确

**Comment by Leopoldthecoder** [comment]
You need to assign `prop` on `el-form-item`: https://jsfiddle.net/pj71jkyw/346/ .
