### ISSUE TITLE
When the [Bug Report] select selector binds data, the reserved value cannot be displayed intact

### ISSUE THREAD

**Issue by MytLoy** [ElemeFE/element#5506]
### Element UI version
1.3.7

### OS/Browsers version
win10 chrome59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/yg45w5w7/](https://jsfiddle.net/yg45w5w7/)

### Steps to reproduce
在编辑数据时，使用select多选时，之前存储的数据绑定到select多选上无法显示内容，只有一个“X”

### What is Expected?
在编辑数据时，使用select多选时，之前存储的数据绑定到select多选上能够显示内容

### What is actually happening?
select多选不太好用

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/yg45w5w7/1/
