### ISSUE TITLE
Does [Bug Report] Popover not support enterable or Popover's Bug?

### ISSUE THREAD

**Issue by zhujz** [ElemeFE/element#5507]
### Element UI version
1.3.7

### OS/Browsers version
Mac chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/moderate/2pagbLdn/2/](https://jsfiddle.net/moderate/2pagbLdn/2/)

### Steps to reproduce
文档中说：
Popover 的属性与 Tooltip 很类似，它们都是基于Vue-popper开发的，因此对于重复属性，请参考 Tooltip 的文档，在此文档中不做详尽解释。
但实际Popover并没有支持enterable

### What is Expected?
Popover支持enterable

### What is actually happening?
Popover不支持enterable

**Comment by Leopoldthecoder** [comment]
We have no plan to add `enterable` to Popover. Compared to Tooltip, Popover emphasizes on interaction, so it has to be enterable.

**Comment by zhujz** [comment]
https://jsfiddle.net/moderate/2pagbLdn/3/

**Comment by zhujz** [comment]
open-delay在Popover为什么也不支持呢

**Comment by zhujz** [comment]
open-delay在Popover为什么也不支持呢
https://jsfiddle.net/moderate/2pagbLdn/3/

**Comment by Leopoldthecoder** [comment]
> Popover 的属性与 Tooltip 很类似，它们都是基于Vue-popper开发的，因此对于重复属性，请参考 Tooltip 的文档，在此文档中不做详尽解释

澄清一下，这句话其实指的是重复的属性不会给出例子，但是可用的属性都会列在下方的 API 表格中。`enterable` 和 `open-delay` 都是 Tooltip 的特有属性，Popover 并不支持。

后面会考虑给 Popover 加上 `open-delay`。
