### ISSUE TITLE
[Bug Report] npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by koakumaping** [ElemeFE/element#5512]
### Element UI version
1.3.7

### OS/Browsers version
Windows 10 64bit lastet

### Vue version
2.3.4

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
npm i -S element-ui

### What is Expected?
install success.

### What is actually happening?
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-S',
1 verbose cli   'element-ui' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session d9a74b82f1cf4651
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/element-ui 920ms (from cache)
8 silly pacote tag manifest for element-ui@latest fetched in 965ms
9 verbose stack RangeError: Maximum call stack size exceeded
9 verbose stack     at exports.create (C:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (C:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (C:\Program Files\nodejs\node_modules\npm\lib\install\node.js:33:25)
9 verbose stack     at normalizeTree (C:\Program Files\nodejs\node_modules\npm\lib\install.js:377:5)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (C:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (C:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (C:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (C:\Program Files\nodejs\node_modules\npm\lib\install.js:379:19)
10 verbose cwd E:\ct-oa
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "element-ui"
13 verbose node v8.1.2
14 verbose npm  v5.0.3
15 error Maximum call stack size exceeded
16 verbose exit [ 1, true ]

**Comment by jikkai** [comment]
检查下你的网络环境是否正常并再次安装，这个问题不是由 element 本身引发的。
