### ISSUE TITLE
After the [Bug Report] Dialog is nested, the last Dialog layer is not at the top.

### ISSUE THREAD

**Issue by iamnewsea** [ElemeFE/element#5516]
### Element UI version
1.3.7

### OS/Browsers version
Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/9jb68rkq/1/](https://jsfiddle.net/9jb68rkq/1/)

### Steps to reproduce
点：点击打开Dialog
点： 再打开。

### What is Expected?
再打开的Dialog层能在最上面层正常显示出来

### What is actually happening?
再打开的Dialog层的 z-index 不是最大值，被遮罩层盖住 了。

**Comment by Leopoldthecoder** [comment]
Dialog 不支持嵌套。可能会在之后的版本中加入支持。3499
