### ISSUE TITLE
[Bug Report] el-menu default-openeds automatic recovery problem

### ISSUE THREAD

**Issue by zhujz** [ElemeFE/element#5518]
### Element UI version
1.3.7

### OS/Browsers version
Mac chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/moderate/oumgjoxw/1/](https://jsfiddle.net/moderate/oumgjoxw/1/)

### Steps to reproduce
点击导航一，点击选项4，点击选项4的选项1

### What is Expected?
不收回

### What is actually happening?
选项4-选项1自动收回

**Comment by baiyaaaaa** [comment]
I test the problem in a new project, but can not repeat this bug. It seem like just appear in the jsfiddle demo. I can not figure out what wrong in jsfiddle. If you repeat the bug in your project, please reopen it again. Thanks

**Comment by zhujz** [comment]
请再确认一下是否和问题条件一致，一定是我的真实环境出问题我才来提bug的呀

**Comment by Leopoldthecoder** [comment]
@zhujz 我刚新建了一个项目，直接拷贝了你 demo 里的代码，确实没有出现 demo 中的问题。如果在你的项目中有问题，请提供一个最小化的重现，放在 GitHub 上，我们看一下。
