### ISSUE TITLE
[Feature Request] Expand / Collapse methods

### ISSUE THREAD

**Issue by steffanhalv** [ElemeFE/element#5520]
### Existing Component
Yes

### Component Name
Tree

### Description
Should be able to expand and collapse tree manually

**Comment by Leopoldthecoder** [comment]
This does not seem to be a common use case. If you must, you can programatically simulate node click: https://jsfiddle.net/zhqfhfv8/ .

**Comment by Xavier0818** [comment]
version 2.3.9，console.info(document.querySelector('.el-tree-node').click())=>undefined
