### ISSUE TITLE
[Bug, Report], date, range (el-date-picker), component, can, choose, the, date, which, was, disabled (date range components can contain dates that are disabled)

### ISSUE THREAD

**Issue by wkcole** [ElemeFE/element#5521]
### Element UI version
1.3.7

### OS/Browsers version
Windows7 / Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/wayco1994/kpdn303b/5/](https://jsfiddle.net/wayco1994/kpdn303b/5/)

### Steps to reproduce
1. 选择一个包括被禁用日期的时间范围

---

1. choose a date range which include the date been disabled

### What is Expected?
当选择范围包括被禁用的日期时，自动剔除掉被禁用的日期，在`v-model`的数组中push额外的值来显示多段日期；
或者当范围包括被禁用的日期时，只能选择开始日期到选择的范围内第一个被禁用日期的前一天。

---

when the date range include the forbidden date, remove these date, show mutipart date range in the array;
or only save the start day to the the day before the first disabled date in the range

### What is actually happening?
选择的日期范围只考虑了开始日期和结束日期可以是否被禁用，选择的范围内可以有被禁用的日期。

---

i can choose a date range include these forbidden date, wtf... = =!

**Comment by wkcole** [comment]
**bad translate**

**Comment by Crise420WMT** [comment]
yes,i get a common problem,vue ^2.3.0 can't support two-way data-binding....

**Comment by wkcole** [comment]
@Crise420WMT 我们不是一样的问题，这个问题不关双向绑定的事吧，建议你还是开个issue

**Comment by Leopoldthecoder** [comment]
日期范围选择应该不会支持这种场景。建议使用两个单独的 DatePicker 来实现。
