### ISSUE TITLE
[Feature Request] Display datepicker inline without input element 

### ISSUE THREAD

**Issue by oukan** [ElemeFE/element#5528]
### Existing Component
Yes

### Component Name
DatePicker

### Description
When i use the DatePicker, I want display datepicker inline without input element.

Just like http://angular-ui.github.io/bootstrap/versioned-docs/2.4.0/#/datepicker 

How can I do. Thanks

**Comment by Leopoldthecoder** [comment]
Element DatePicker has no such feature.

**Comment by Chinese1904** [comment]
@Leopoldthecoder any plans on adding this in the future? Would love to see this
