### ISSUE TITLE
[Bug, Report], Autocomplete, with, suggestions, bug

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/element#5529]
### Element UI version
1.3.7

### OS/Browsers version
Win 10 Chrome Latest

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/0k579bcr/](https://jsfiddle.net/0k579bcr/)

### Steps to reproduce
在"输入后匹配输入建议"输入“H”或"h"，不会弹出匹配“Hot honey 首尔炸鸡（仙霞路）”
这是因为code里面：
          return (restaurant.value.indexOf(queryString.toLowerCase()) === 0) 无法匹配英文大写字母
应改成
          return (restaurant.value.toLowerCase().indexOf(queryString.toLowerCase()) === 0

### What is Expected?
"输入“H”或"h"，弹出匹配“Hot honey 首尔炸鸡（仙霞路）”

### What is actually happening?
在"输入后匹配输入建议"输入“H”或"h"，不会弹出匹配“Hot honey 首尔炸鸡（仙霞路）”

**Comment by yemadu** [comment]
这块你能够自己进行修改的
案例只是为大家提供一个使用参考哈.

**Comment by Leopoldthecoder** [comment]
楼上+1。匹配逻辑是需要自己实现的，你可以选择是否对大小写敏感。
