### ISSUE TITLE
[Bug Report] multiple targets cannot bind the same Popover at the same time

### ISSUE THREAD

**Issue by Marshane** [ElemeFE/element#5535]
### Element UI version
1.3.4

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/wodw0pyx/](https://jsfiddle.net/wodw0pyx/)

### Steps to reproduce
2个按钮同时绑定同一个popover

### What is Expected?
2个按钮同时绑定同一个popover, 同时生效

### What is actually happening?
2个按钮同时绑定同一个popover, 生效的是最后一个

**Comment by Leopoldthecoder** [comment]
Popover 并不支持同时绑定多个按钮。

**Comment by syn-zeta** [comment]
A hack for future readers: https://jsfiddle.net/hsymu9bk/1/
