### ISSUE TITLE
[Bug Report] el-date-picker对时间验证的问题

### ISSUE THREAD

**Issue by ispwd** [ElemeFE/element#5539]
### Element UI version
1.3.7

### OS/Browsers version
Windows10/Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ispwdz/2mntajpv/](https://jsfiddle.net/ispwdz/2mntajpv/)

### Steps to reproduce
验证表单时对日期时间的验证发生异常，可在控制台查看

### What is Expected?
正确的验证日期时间

### What is actually happening?
无法正常验证，抛出Uncaught TypeError: t.getTime is not a function的异常

**Comment by elfman** [comment]
控制台没有显示错误啊，你设定的是什么值？具体的步骤是什么？

**Comment by ispwd** [comment]
点击提交的时候控制台不报错吗？
不手动设置组件的值，而是通过data给组件绑定好值后，点击提交，调用form表单验证，此时控制台就会出现以下错误，我使用的是Chrome 59.0.3071.109 操作系统是Win10
Uncaught TypeError: t.getTime is not a function
    at Object.s [as validator] (index.js:9)
    at index.js:8
    at n (index.js:9)
    at l (index.js:9)
    at index.js:9
    at Array.forEach (<anonymous>)
    at c (index.js:9)
    at s.validate (index.js:8)
    at VueComponent.validate (index.js:8)
    at VueComponent.boundFn [as validate] (vue.js:169)

**Comment by jikkai** [comment]
@ispwd 默认值使用 Date Object，不要使用 String

**Comment by ispwd** [comment]
@jikkai 哦，是这样啊，但是当我编辑表单时，从服务器返回的数据是json格式的，其中日期是字符串，我如何将其中的所有日期转换为Date Object呢？
目前我是这样做的
row是table中的一行数据
this.form = Object.assign({}, row)
因此出现了该问题，请指导一下我应该如何正确处理数据。

**Comment by jikkai** [comment]
@ispwd 可以借助 momentjs 之类的库对数据进行 format，也可以自行对字符串进行处理

**Comment by ispwd** [comment]
我明白了，问题出在表单效验上，el-date-picker本身支持字符串，也支持date object，但是json中的字符串绑定之后在效验时就不是date object，所以出现了异常。使用momentjs确实可以方便的转换，但是只能手动处理，我需要做如下改进对吗。
// 拷贝表格数据用于编辑
this.form = Object.assign({}, row)
this.form.data = moment(this.form.data)
