### ISSUE TITLE
[Bug Report] column sorting problem, the table header arrow needs only two states

### ISSUE THREAD

**Issue by huangyanxiong01** [ElemeFE/element#5542]
### Element UI version
1.2.8

### OS/Browsers version
ubuntu 16.04

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
no

### What is Expected?
为什么表格头部列排序箭头指示器不是两种状态，还会有不是上下的一种，这种方式很容易误导人

### What is actually happening?
期望只有两种状态

**Comment by Leopoldthecoder** [comment]
Sorting column without a highlighted arrow means the order of that row is restored to its initial state.

**Comment by zhangkun-Jser** [comment]
how to only two states
