### ISSUE TITLE
关于DatePicker 日期选择器格式的问题

### ISSUE THREAD

**Issue by zhangfeixiang** [ElemeFE/element#5549]
在选取一个事件段的时候，值是` 2017-06-21T16:00:00.000Z`格式的。
单独选择一个时间 `Mon Jun 26 2017 11:34:37 GMT+0800 (CST)`
最好是统一为时间戳。
怎么统一返回格式，注意不是展示时的格式化。

**Comment by shuiRong** [comment]
--version  1.0.9
仅仅是“展示”时格式化而已...
