### ISSUE TITLE
Tabs: 卡片化标签页样式疑问

### ISSUE THREAD

**Issue by dnshi** [ElemeFE/element#555]
我发现在Tabs里面，这段[代码](https://github.com/ElemeFE/element/blob/master/packages/theme-default/src/tabs.css#L128)在切换tab的时候，会有少许的移动。请问原本设计的效果是否就是如此的呢？

**Comment by baiyaaaaa** [comment]
感谢提醒，这个代码上的失误导致的，后面会修复这个问题
