### ISSUE TITLE
网站打开太慢

### ISSUE THREAD

**Issue by dai875939260** [ElemeFE/element#5550]
http://element.eleme.io/ 经常打不开

**Comment by callmez** [comment]
这个问题 能不能解决下?   经常性的打开很慢. 饿了么这点资源还是有的吧?

**Comment by huguangju** [comment]
这个站点托管在github pages上的，只是域名指向了 element.eleme.io 而已，有可能是 github 抽风吧

**Comment by webthen** [comment]
+1
