### ISSUE TITLE
[Bug Report] syntax errors using $confirm components in IE browsers

### ISSUE THREAD

**Issue by yuanshengchao** [ElemeFE/element#5555]
### Element UI version
1.3.7

### OS/Browsers version
ie浏览器（11,10,9）

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
在ie浏览器中，使用$confirm组件出现语法错误

### What is Expected?
兼容ie浏览器

### What is actually happening?
出现语法错误啊

**Comment by yuanshengchao** [comment]
http://element.eleme.io/#/zh-CN/component/message-box，ie报错

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/27530232-5cb0184e-5a8a-11e7-9a1e-14203a770a03.png)

请自行引入 Promise 的 polyfill
