### ISSUE TITLE
[Bug Report] tree control issues

### ISSUE THREAD

**Issue by Hareis** [ElemeFE/element#5558]
### Element UI version
1.3.7

### OS/Browsers version
win10 google chrome 58

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击按钮，发现 tree 控件 并没有发生变化

### What is Expected?
改变 show-checkbox 的时候 tree 控件checkbox 能联动

### What is actually happening?
因为业务需要 需要动态控制 tree的 checkbox的可选与不可选
我在改变 show-checkbox 的时候 发现 tree 控件 并没有发生变化

**Comment by Leopoldthecoder** [comment]
This is not supported for now. You can control checkboxes' visibility via CSS, though: https://jsfiddle.net/tvc1p2m2/

**Comment by Hareis** [comment]
@Leopoldthecoder  谢谢 居然是需要自己写css 控制  打死都没想到  非常感谢 困扰我一整个下午

**Comment by Hareis** [comment]
@element-bot  怎么关闭这个问题？
