### ISSUE TITLE
 [Feature Request] el-input: add hint for the length of chars already typed 

### ISSUE THREAD

**Issue by chenyiqiao** [ElemeFE/element#5559]
### Existing Component
Yes

### Component Name
el-input

### Description
When we set a  max length for a `el-input` component, it's better if users know how many chars has been typed and how many positions left. So a hint like `15/30` tells users they can type 15 more chars. And when `currentValue.length > maxLimit`, we may add a warning color to notify users.

You may add two props:

```js
showLengthHint: {
  type: Boolean,
  default: false
},
maxLimit: Number
```

and in the template:

```html
<div class="wrapper">
 <input/>
 <span v-if="showLengthHint && maxLimit > 0">{{currentValue.length}}/({maxLimit}}</span>
</div>
```
in which the span is in the right most of the wrapper(add a wrapper so that the info won't overlap with the append slot content).

**Comment by syn-zeta** [comment]
I think this is a fairly specific request that is easily implemented if needed: https://jsfiddle.net/ozgf5oLa/

Different users would want slightly different behaviors with different format, styling, positioning, and it would be hard to cater to all those needs. I do not think this belongs with the Input component.

**Comment by chenyiqiao** [comment]
yeah I understand. But if there're a lot of forms out there, it's painful to implement the same logic everywhere and pollute the template with `<span>{{ hint }}</span>`.  I may write a component to enhance it.

**Comment by Leopoldthecoder** [comment]
@chenyiqiao Best way is to wrap Input with `<span>{{ hint }}</span>` to another component.
