### ISSUE TITLE
[Bug Report] multi component input in the form of check correct but still error

### ISSUE THREAD

**Issue by devrsi0n** [ElemeFE/element#5562]
### Element UI version
1.3.7

### OS/Browsers version
win7/chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/devrsi0n/vgopy182/](https://jsfiddle.net/devrsi0n/vgopy182/)

### Steps to reproduce
选择活动区域（多选组件）任意选项。

### What is Expected?
表单检验该选项必填，期望选择某些选项之后错误提示消失。

### What is actually happening?
错误一直存在，无论如何都消除不了。

**Comment by Leopoldthecoder** [comment]
The value of multiple Select is an array, so the validator should add `type: 'array'`: https://jsfiddle.net/vgopy182/1/

**Comment by devrsi0n** [comment]
多谢~
