### ISSUE TITLE
[Bug Report] table 组件, <template scope="scope">里的代码修改, 不会热重载

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#5566]
### Element UI version
1.3.7

### OS/Browsers version
MAC, Chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
webpack 2.6.1
```
<el-table-column label="地址">
  <template scope="scope">
    {{ scope.row.address }}
  </template>
</el-table-column>
```
修改`<template scope="scope"></template>`里的代码都无法热重载, 修改其他组件都是正常的, 包括修改`el-table-column`的label属性等

<img width="1048" alt="qq20170627-150154 2x" src="https://user-images.githubusercontent.com/10840991/27574654-d503c434-5b49-11e7-9bf9-a188eb819460.png">

在代码中修改了两个地方

<img width="664" alt="qq20170627-145800 2x" src="https://user-images.githubusercontent.com/10840991/27574693-01f3b0e4-5b4a-11e7-83f6-9d72c6cccc47.png">
<img width="658" alt="qq20170627-145814 2x" src="https://user-images.githubusercontent.com/10840991/27574694-01f48b72-5b4a-11e7-9cc3-9dce53248034.png">

保存后, HMR也触发了.

<img width="493" alt="qq20170627-145959 2x" src="https://user-images.githubusercontent.com/10840991/27574742-27cf3aae-5b4a-11e7-8111-3a17d34a1cd0.png">

修改label成功的刷新了

<img width="541" alt="qq20170627-145941 2x" src="https://user-images.githubusercontent.com/10840991/27574772-39fd73bc-5b4a-11e7-90b0-fb03ea67a147.png">

但是修改`<template scope="scope"></template>`里的代码, 却没有刷新...

### What is Expected?
修改`<template scope="scope"></template>`里的代码也可以热重载

### What is actually happening?
修改`<template scope="scope"></template>`里的代码不可以热重载

**Comment by Leopoldthecoder** [comment]
This seems to be a bug with `scoped template`. Not much we can do here.
