### ISSUE TITLE
[Feature Request] el-table-column append another <td> dom element

### ISSUE THREAD

**Issue by hambb** [ElemeFE/element#5569]
### Existing Component
Yes

### Component Name
el-table-column

### Description
Hi I'm Haein Jung

Use 'el-table', 'el-table-column' draw our service UI

I want to append `td` tag after `el-table-column`.
I try use <template>, but not working ...

it's not "expends" function, but similar UI.
want to be table view likes this,

```
============
A | B | C | D
---------------
  some text
============
A | B | C | D
---------------
  some text
============
```
how can i do?

I love your element ui
thanks :)

(+) use `template` dom tag, it is converting "hidden-columns".
I typed like this,
```
<el-table>
    <el-table-column></el-table-column>
    <template></template>
</el-table>
```

**Comment by hambbjung** [comment]
I use Vue version : 2.3.3
and element-ui version : 1.3.6
with webpack.
thanks!
