### ISSUE TITLE
[Feature, Request], picker's, displayValue data backfill

### ISSUE THREAD

**Issue by Caroline424** [ElemeFE/element#5571]
### Existing Component
Yes

### Component Name
date-picker

### Description
date-picker/picker.vue
#317

the return value of displayValue get() is always a date object, but I don't want that kind of format.
Maybe the displayValue format can be more flexible. I hope to display text in input.
e.g.: display 'last 3 days' in displayValue

can it be like this, before excuting formatter, so that I can display pure text in the input box:

```
    displayValue: {
      get() {
        const value = this.currentValue;
        if (!value) return;

  // == add
        if (typeof value === 'string') {
          return value;
        }
  // == add end

        const formatter = (
          TYPE_VALUE_RESOLVER_MAP[this.type] ||
          TYPE_VALUE_RESOLVER_MAP['default']
        ).formatter;
        const format = DEFAULT_FORMATS[this.type];

        return formatter(value, this.format || format, this.rangeSeparator);
      },
```

**Comment by Leopoldthecoder** [comment]
This doesn't seem to be a common use case. So, sorry.
