### ISSUE TITLE
[Bug, Report], Transfer, Customizable, not, work

### ISSUE THREAD

**Issue by pylixm** [ElemeFE/element#5572]
### Element UI version
1.3.7

### OS/Browsers version
mac 0.12.4 (16E195)   chrome 版本 58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
官方实例即可；

### What is Expected?
展现自定义后的 label  

### What is actually happening?
label 为空

**Comment by pylixm** [comment]
sorry, look this one https://jsfiddle.net/ym0meo07/ .

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ym0meo07/1/

JSFiddle does not support JSX, and the equivalent render function works fine. In your own project, please make sure JSX related dependencies are correctly installed and configured.
