### ISSUE TITLE
[Feature, Request] Can I change button's order of MessageBox?

### ISSUE THREAD

**Issue by fy0** [ElemeFE/element#5576]
### Element UI version  
1.3.7

### Existing Component
yes

### Component Name
MessageBox

### Description
"Cancel" before "Confirm" makes me feel weird. I prefer traditional "Yes/No/Cancel" order.  
Could element-ui give me an option to custom button order? thx.

**Comment by Leopoldthecoder** [comment]
> "Cancel" before "Confirm" makes me feel weird

This is how most, if not all, browsers implement their native `confirm`. Run the following code in your favorite browser:
```javascript
confirm('Are you sure?')
```

That being said, you can revert the buttons' order with CSS: https://jsfiddle.net/fqdc63v8/

**Comment by fy0** [comment]
Thanks for the solution. but i don't agree with it's the most popular order.
As we know, **most** users are windows user and familiar with yes/no/cancel order.
@Leopoldthecoder
