### ISSUE TITLE
[Feature, Request], drag, area, disabled, but, still, shown

### ISSUE THREAD

**Issue by neildchen** [ElemeFE/element#5578]
### Existing Component
Yes

### Component Name
el-upload in el-dialog

### Description
我是個菜鳥請包涵.... 謝謝

在 一個 el-dialog 中 放一個 el-form 如下

```
<el-button style="margin-top: 20px;" type="primary" @click="dialogFormVisible = true">Add Stock</el-button>
    <el-dialog title="Add Stock" v-model="dialogFormVisible">
      <el-form :model="form">
        <el-form-item label="Ticket Number: " :label-width="formLabelWidth">
          <el-input v-model="form.ticketNumber" auto-complete="off"></el-input>
        </el-form-item>
        <el-form-item style="height: 40px;" label="Import: " :label-width="formLabelWidth">
          <el-upload ref="upload" action="https://jsonplaceholder.typicode.com/posts/" :on-preview="handlePreview" :on-remove="handleRemove" :file-list="fileList" :auto-upload="false">
            <el-button slot="trigger" type="primary">Select a zip file from bean_app</el-button>
            <div slot="tip" class="el-upload__tip">ONLY zip files from bean_app will work!</div>
          </el-upload>
        </el-form-item>
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button @click="dialogFormVisible = false">Cancel</el-button>
        <el-button :disabled="disabled" style="margin-left: 10px;" type="success" @click="submitUpload">Execute</el-button>
        <!--<el-button :disabled="disabled" type="primary" @click="submitUpload()">Execute</el-button>-->
      </div>
    </el-dialog>
```
這個 el-upload drag 是 disabled 的, 但是當點擊 el-button 帶出 el-dialog 時, 卻是有 drag area 的 (即虛線圍起來的一個方塊) 

![selection_060](https://user-images.githubusercontent.com/8392135/27584318-19dd6bee-5b6a-11e7-954e-f854c572b0c3.png)

有嘗試給 <el-form-item style="height: 40px;" 但改變的卻是 dialog 的 height.... 

![selection_061](https://user-images.githubusercontent.com/8392135/27584369-54438ef8-5b6a-11e7-87e8-9e19c6d01558.png)

能不能麻煩給些建議? (只想讓 <el-upload 看來就像個按鈕, 不要下面的 drag area 出現...) 感謝您, 謝謝

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by neildchen** [comment]
I am really sorry for not being careful enough by following element's  reporting rule.... I should have provided a link to the code. But when I tried it on jsfiddle and **it is all good there**. 

https://jsfiddle.net/neildchen/toqoscf7/4/

identical code on my project, it shows as:

![selection_062](https://user-images.githubusercontent.com/8392135/27620736-3285d2a0-5bfe-11e7-9863-1c396ac874ec.png)

I am using vue @ 2.3.4, element ui @ 1.3.7 ....

The truth is that I can't reproduce the issue in jsfillde other than in my local project.... I am sorry but I don't know how (I am at very entry-level learning of the front-end) to further investigate the issue. Maybe someone who sees this can point me out some directions? Truely appreciate your help. Thank you.

**Comment by neildchen** [comment]
after all, my colleague helped out that in my .css that has: 

```
.el-upload--text {
    background-color: #fff;
    border: 1px dashed #d9d9d9;
    border-radius: 6px;
    box-sizing: border-box;
    /*width: 360px;
    height: 180px;*/
    text-align: center;
    cursor: pointer;
    position: relative;
    overflow: hidden;
}
```

comment out the width and height properties then the outcome is all as expected. 

https://jsfiddle.net/neildchen/toqoscf7/6/

Though I thought if I do not have the `drag` attribute enabled, then the `.el-upload--text` should not be loaded and in effect.... But I am too junior to tell...,  just want to share with anybody who ever finds this information useful.  Thanks
