### ISSUE TITLE
[Bug, Report], $msgbox, cancel, won't, catch

### ISSUE THREAD

**Issue by yokinzzz** [ElemeFE/element#5584]
### Element UI version
1.3.7

### OS/Browsers version
windows 10 / chrome 59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/yokin/fu10ymoh/](https://jsfiddle.net/yokin/fu10ymoh/)

### Steps to reproduce
open the link

### What is Expected?
显示catch中的内容

### What is actually happening?
显示的仍是then中的内容

**Comment by Leopoldthecoder** [comment]
Fixed in #5658
