### ISSUE TITLE
[Bug, Report], menu, doesn't, get, activated, when, being, clicked, in,, NavMenu, in, router, mode

### ISSUE THREAD

**Issue by xiangnanscu** [ElemeFE/element#5585]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu Server 14.04/Chrome 最新版

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
不好意思, 重现链接实际是:http://httper.cn:8000/admin#/models/user, 但填进去总是被提示不正确.只能填在这里了.
输入账号:nhak5e
密码:111111
点击右侧菜单"全部"或"管理员", 你会发现没有变亮, 需要再点一次才亮.

### What is Expected?
第一次点击菜单就应该变亮

### What is actually happening?
第一次点击菜单没有变亮

**Comment by pronan** [comment]
related code in my project
```
    <el-menu router :default-active="$route.fullPath">
      <el-menu-item :index="deleteFilterPath(field.name)">全部</el-menu-item>
      <el-menu-item v-for="(choice, index) in field.choices" :index="setFilterPath(field.name, choice[0])" :key="index">{{ choice[1] }}</el-menu-item>
    </el-menu>
```

**Comment by wacky6** [comment]
没点亮指什么？

**Comment by xiangnanscu** [comment]
@wacky6 就是指首次点击菜单项,它的html渲染为是`<li class="el-menu-item"`需要第二次点击才会,`<li class="el-menu-item is-active"`.  重现链接, http://httper.cn:8000/admin#/models/user, 
输入账号:nhak5e
密码:111111

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/27812972-3c91bc04-60a5-11e7-9db5-334cabef895e.png)

这个页面似乎并没有用 Element？菜单项没有 `el-menu-item` 类。

**Comment by xiangnanscu** [comment]
@wacky6 不好意思, 刚切换了分支, 现在恢复了

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 不好意思, 刚切换了分支, 现在恢复了

**Comment by Leopoldthecoder** [comment]
@xiangnanscu 整理个在线 demo 吧，贴的代码看不出来问题。

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 我尝试最小化案例,https://jsfiddle.net/pronan/uc2j5s0u/这个, 但是无法重现.  回到我的项目中却仍然要点击两次. 相信你也看到了的.

**Comment by Leopoldthecoder** [comment]
那说明还是你项目中代码的问题，所以你可以把项目放到 GitHub 上来。

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 你好. 我的项目比较庞大. 而且涉及到数据库初始化的一些操作. 能给个私下联系你的方式么. 我直接把项目的在线IDE发给你.

**Comment by Leopoldthecoder** [comment]
不要把整个项目放上来，请精简成可重现的最小版本。

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 最小版本做出来了. https://github.com/xiangnanscu/core-test, 切换到`emb`分支, `npm install && npm run dev` 之后, 点击右侧菜单的`男`或`女`即可, 你会发现需要点两次才行.

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 主要代码在`src/list.vue` 这个文件中

**Comment by Leopoldthecoder** [comment]
控制台的报错已经很明确了：`index` 应该是一个字符串，但是被赋值了一个对象。从代码来看，这个对象是应该赋值到 `route` 属性上的。修改如下：
```html
<el-menu :index="'' + pi" router>
  <el-menu-item v-for="(choice, index) in field.choices" :key="index" 
    :index="'' + index" :route="setFilterPath(field.name, choice[0])">
    {{ choice[1] }}
  </el-menu-item>
</el-menu>
```

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 谢谢. 这样实际上router模式下是以route属性作为跳转依据的, 有两个建议.
1. 文档能否考虑修改下: 将`router | 是否使用 vue-router 的模式，启用该模式会在激活导航时以 index 作为 path 进行路由跳转` 更改为`router | 是否使用 vue-router 的模式，启用该模式会在激活导航时以 index 或route作为 path 进行路由跳转`.
2. 能否直接取消route这个属性, 让index能够接受route对象

**Comment by CoderONER** [comment]
遇到同样的问题 但是把defalut-active 去掉就不会出现点击两次的问题 但是会出现另外一个 。进来页面无法定位某个menu
