### ISSUE TITLE
[Feature Request] el-table question (inner table)

### ISSUE THREAD

**Issue by hambbjung** [ElemeFE/element#5589]
### Existing Component
Yes

### Component Name
el-table

### Description
Hi, I'm Haein jung, 
and use browser : chrome 59.0.3071.104
vue : 2.3.3
element-ui : 1.3.6

When I draw 2-depth table, and each used 'el-table' tag.

I think inner table style is non-border, but isn't working.
I typed like this,
```

<el-table border>
    <el-table-column> <!-- some template --> </el-table-column>
    <el-table-column> <!-- some template --> </el-table-column>
    <el-table-column>
       <template>
            <el-table border="false">
                <el-table-column> <!-- some template --> </el-table-column>
                <el-table-column> <!-- some template --> </el-table-column>
           </el-table>
       <template>
     </el-table-column>
</el-table>

```
Is it BORDER because `el-table` extends upper table styles?
I need some help T_T.

**Comment by Leopoldthecoder** [comment]
Yes, the inner table inherits border style from the outer table. You need to override it: https://jsfiddle.net/8b84mfcb/

**Comment by hambbjung** [comment]
I solved it in this way! Thank you!!
