### ISSUE TITLE
el-switch 无法兼容长文字。并且width 属性无效

### ISSUE THREAD

**Issue by xjcloudy** [ElemeFE/element#559]
[在线演示地址](https://fiddle.jshell.net/xjcloudy/xu3ut31p/)

如图所示：
![image](https://cloud.githubusercontent.com/assets/2074921/19585477/57b0be9e-977f-11e6-925c-377457cfc2e6.png)

width 属性有bug。

**Comment by Leopoldthecoder** [comment]
fixed in #477

**Comment by akaylh** [comment]
补充：设置了width后，控制台显示：
vue.js?3de6:2611[Vue warn]: Invalid prop: type check failed for prop "width". Expected Number, got String. 
(found in component <el-switch>)
但width值就是数值。

**Comment by jikkai** [comment]
@akaylh 非字符串绑定使用动态Props，http://vuejs.org/guide/components.html#Dynamic-Props

⭕<... :width="120">
❌<... width="120">
