### ISSUE TITLE
Range validation failed in [Bug Report] form validation

### ISSUE THREAD

**Issue by RainingNight** [ElemeFE/element#5593]
### Element UI version
1.3.7

### OS/Browsers version
Chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/xLwf06fe/](https://jsfiddle.net/xLwf06fe/)

### Steps to reproduce
运行 jsfiddle ， 输入 2 ，依然提示年龄必须大于1。

### What is Expected?
当输入2时，应该验证通过

### What is actually happening?
验证问题

**Comment by Leopoldthecoder** [comment]
`type: 'number'` also has to be declared in the last rule: https://jsfiddle.net/xLwf06fe/1/ .

A bit weird I admit. I'm not sure if this is caused by `async-validator`.

**Comment by RainingNight** [comment]
It's ok. Thanks!
