### ISSUE TITLE
[Bug Report] dialog does not get form objects without visible coming out

### ISSUE THREAD

**Issue by U2Fsd** [ElemeFE/element#5597]
### Element UI version
1.3.7

### OS/Browsers version
win10/chorme

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/Lucius_Yeh/rapas1pb/](https://jsfiddle.net/Lucius_Yeh/rapas1pb/)

### Steps to reproduce
demo中 点击按钮2 之前 点击按钮1 会报 Cannot read property 'resetFields' of undefined

### What is Expected?
在dialog的visible 属性设置成true前 ，能够得到form对象 可以调用resetFields方法

### What is actually happening?
Cannot read property 'resetFields' of undefined

**Comment by Leopoldthecoder** [comment]
Before the first `open`, the content of Dialog is not rendered, so you cannot manipulate DOM at that moment. Try resetting Form after the Dialog pops up, e.g. in its `open` event handler.

**Comment by U2Fsd** [comment]
@Leopoldthecoder 

Ajax后绑定数据，然后再Dialog render ，这个时候Dialog中Form 第一次绑定的数据 是Ajax获取到的并不是Data中定义的空数据。resetFields方法不能回到空Form的状态了。请问有解决方法吗？

**Comment by Leopoldthecoder** [comment]
`resetFields` 本身就是回到初始状态，而不是空白状态。所以接口数据返回后先不绑定，在本地缓存一下，然后在 Dialog 打开之后再进行数据的绑定。

**Comment by U2Fsd** [comment]
@Leopoldthecoder Thx 😀
