### ISSUE TITLE
Date Picker 日期选择器 有错

### ISSUE THREAD

**Issue by zhuewizz** [ElemeFE/element#56]
### What is actually happening?
(program):2232 [Vue warn]: Trying to access non-existent property "_e" while rendering. Make sure to declare reactive data properties in the data option. (found in root instance)warn @ (program):2232
(program):2232 [Vue warn]: Error when rendering root instance: warn @ (program):2232

**Comment by QingWei-Li** [comment]
请贴出你的能复现问题的代码，以及指明 vue 和 element 的版本，什么都没有是帮不了你的

**Comment by zhuewizz** [comment]
我今天git clone下来，npm run dev 后发现的，没有注意是什么版本

**Comment by QingWei-Li** [comment]
我这边运行正常，DatePicker  没有报错情况

**Comment by yuu2lee4** [comment]
仓库 datetime picker 也报错  win10 64bit

**Comment by Leopoldthecoder** [comment]
我晚上试一下吧

**Comment by Leopoldthecoder** [comment]
@yuu2lee4 我这边试了，机器是 win10 64 位，chrome 52.0 浏览器。刚从仓库拉的代码，执行 `npm run dev`，然后打开 datetime picker 进行操作，没有报错。你现在还会报错吗？如果会，详细的错误信息是？

**Comment by yuu2lee4** [comment]
![image](https://cloud.githubusercontent.com/assets/8046366/18439220/0e3425b4-7937-11e6-8f6a-f03d34c041f8.png)

**Comment by Leopoldthecoder** [comment]
@yuu2lee4 麻烦检查一下你本地 node_modules 里 vue 的版本

**Comment by yuu2lee4** [comment]
依赖里面是rc3   node_modules的版本是rc4

**Comment by QingWei-Li** [comment]
@yuu2lee4 目前不支持 rc4 和 rc5 （有一个 bug 到下一版才修复到），所以请使用 rc3

**Comment by yuu2lee4** [comment]
目前还是有错  已经跟随仓库升到rc6

**Comment by csvwolf** [comment]
@yuu2lee4 错误提示还是这个？

**Comment by yuu2lee4** [comment]
是的。。。。。我是重新clone的仓库

**Comment by QingWei-Li** [comment]
@yuu2lee4 把 packages/date-picker 里的 vue 卸载掉

**Comment by yuu2lee4** [comment]
然而 npm run dev之后 又给装上了

**Comment by QingWei-Li** [comment]
@yuu2lee4 🌚 把 date-picker/package.json 里的 devDpendecies 里的 vue 去掉 最新的 pr 已经改了
