### ISSUE TITLE
[Bug Report] DatePicker 日期选择器, type="week"时，选择每年最后一周出现BUG 

### ISSUE THREAD

**Issue by MichealGeng** [ElemeFE/element#5600]
### Element UI version
1.3.7

### OS/Browsers version
windows /chrome 58

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.选择周DatePicker 控件。
2.选择2014年12月28日，控件上显示2014年第一周。

### What is Expected?
应该显示为2014年最后一周，或2015年第一周

### What is actually happening?
控件上显示2014年第一周

**Comment by Leopoldthecoder** [comment]
Duplicate of #5594
