### ISSUE TITLE
[Feature Request] Label on left-side of Checkbox

### ISSUE THREAD

**Issue by hawkeye64** [ElemeFE/element#5601]
### Existing Component
Yes

### Component Name
Checkbox

### Description
The current option looks like:
>    [X] Label

It'd be nice to have the option for left or right side so the output could be like this:
>    Label [X]

**Comment by Leopoldthecoder** [comment]
This does not seem to be a common use case and you can implement it on your end: https://jsfiddle.net/wd3ekv28/
