### ISSUE TITLE
[Feature Request] multiple selection column using custom data for el-table

### ISSUE THREAD

**Issue by wangtjwork** [ElemeFE/element#5603]
### Existing Component
Yes

### Component Name
el-table-column type="selection"

### Description
Table with pagination have many unexpected behavior when switching between pages, because showing data and backside data are not bound together.

I'm currently working on a multiple selection table. As suggested on the issue, I used reserve-selection and row-key combined. But with this combination, select-all could still only select those rows within the same page. Also it's hard to make some lines checked before table show.

Maybe it makes more sense in this state to have a table selection column that's depend on the data, like passing in a prop with true/false. Then user make changes to select function outside, just like custom sorting. It could just return the row index when clicked.

**Comment by wangtjwork** [comment]
Chinese Version: 

建议增加用户select功能。
    在分页的表格中，由于显示数据和后台数据不完全绑定，很容易出现一些问题。

    我现在在编写一个有多选功能的表格。某个issue中建议用reserve-selection和row-key解决换页时候的选项记忆问题。但我在使用后发现这并不解决全选按钮的一些问题，例如全选按钮还是只能选中所有当前页面的选项，以及如果将当前页面的选项全部选中后，全选按钮就会变为选中，但是其他页面还是未被选上。同时，也很难做对于特定数据的选项默认为选中。

因此，我建议在selection的el-table-column中加入prop功能，从数据中读入一列，并在选中时候返回行数即可，参考自定义的表格排序。

感谢开发人员的辛勤工作。

**Comment by harrydengchao** [comment]
@wangtjwork 正好遇到同样的问题。你解决了吗？
现在的 全选 只能选中当前可见页面，不能对所有页面进行控制。
我尝试了一些方法，但是，都不是很稳定。

**Comment by wangtjwork** [comment]
My updates on the problem:

Added custom select column 'IsSelected'，trigger a hand-written render select function each time I switch page or page size. The function would check the current rows that needs to be selected and set the status to true. I also kept the 'reserve-select' and 'row-key' options because without those two the function won't work. Didn't figure out why but that's weird....

As for select-all I added an additional field for memorizing, setting every row's IsSelected to true or false.

There's still a remaining problem: when all the elements on the current page are selected, the select-all checkbox is automatically set to true even if no other elements are selected at all. Don't think I can do anything about this as there seems to be no method to change that checkbox.

The whole size of the data I need to display is less than 10k, and it's fast enough for my needs.

If you have a better way please post.

Chinese Version:

最终在数据中加入新列‘IsSelected’来做custom select，每一次翻页及调整每页显示时候进行渲染操作，从数据中读入应该渲染成select的row。同时使用reserve-select和row-key。不知为什么不用这两个的时候系统不会渲染。
对全选使用额外变量进行记忆，将数据每一个IsSelected调为true或false达到全选及取消全选。

现在唯一的问题就是当前页全部选中时候，系统的全选会自动打钩。这个应该没什么办法了。

我需要显示的数据不算太多大概不超过一万行因此速度还算不错。

如有更好的方式还请告知。

顺便满地打滚求开发人员注意到这个request。

**Comment by Leopoldthecoder** [comment]
We'll consider this. Now our team doesn't have much manpower on Element, so I'm afraid you'll have to wait a little longer.

**Comment by merfais** [comment]
可以使用`toggleRowSelection`模拟多选的行为，在数据变化时重新选中，示例：
```javascript
  selection.forEach(row => {
    this.$refs.table. toggleRowSelection(row, true)
  })
```
但是这样依旧不能避开翻页时选中的条目无法被再次选中，问题出现在
```javascript
const toggleRowSelection = function(states, row, selected) {
  let changed = false;
  const selection = states.selection;
  const index = selection.indexOf(row);   //这里的diff
  if (typeof selected === 'undefined') {
    if (index === -1) {
      selection.push(row);
      changed = true;
    } else {
      selection.splice(index, 1);
      changed = true;
    }
  } else {
    if (selected && index === -1) {
      selection.push(row);
      changed = true;
    } else if (!selected && index > -1) {
      selection.splice(index, 1);
      changed = true;
    }
  }
  return changed;
};
```
判断条目是否是选中状态用的是Array.prototype.indexOf方法，mdn的描述

> indexOf() compares searchElement to elements of the Array using strict equality (the same method used by the === or triple-equals operator).

因此对于object的对比不是很好的，除非使用的原始对象进行比对才会比对成功，否则均失败

在table-column.js中有这段代码
```javascript
const forced = {
  selection: {
    renderHeader: function(h) {
      return <el-checkbox
        nativeOn-click={ this.toggleAllSelection }
        value={ this.isAllSelected } />;
    },
    renderCell: function(h, { row, column, store, $index }) {
      return <el-checkbox
        value={ store.isSelected(row) }
        disabled={ column.selectable ? !column.selectable.call(null, row, $index) : false }
        on-input={ () => { store.commit('rowSelectedChanged', row); } } />;  // 使用的是row
    },
    sortable: false,
    resizable: false
  },

  // ...
}
```
在table-body.js中
```javascript
<tbody>
  {
    this._l(this.data, (row, $index) =>
      [<tr
        style={ this.rowStyle ? this.getRowStyle(row, $index) : null }
        key={ this.table.rowKey ? this.getKeyOfRow(row, $index) : $index }
        on-dblclick={ ($event) => this.handleDoubleClick($event, row) }
        on-click={ ($event) => this.handleClick($event, row) }
        on-contextmenu={ ($event) => this.handleContextMenu($event, row) }
        on-mouseenter={ _ => this.handleMouseEnter($index) }
        on-mouseleave={ _ => this.handleMouseLeave() }
        class={ [this.getRowClass(row, $index)] }>
        {
          this._l(this.columns, (column, cellIndex) =>
            <td
              class={ [column.id, column.align, column.className || '', columnsHidden[cellIndex] ? 'is-hidden' : '' ] }
              on-mouseenter={ ($event) => this.handleCellMouseEnter($event, row) }
              on-mouseleave={ this.handleCellMouseLeave }>
              { // 这里的row是遍历的data
                column.renderCell.call(this._renderProxy, h, { row, column, $index, store: this.store, _self: this.context || this.table.$vnode.con
              }
            </td>
          )
        }
        {
          !this.fixed && this.layout.scrollY && this.layout.gutterWidth ? <td class="gutter" /> : ''
        }
      </tr>,
        this.store.states.expandRows.indexOf(row) > -1
        ? (<tr>
            <td colspan={ this.columns.length } class="el-table__expanded-cell">
              { this.table.renderExpanded ? this.table.renderExpanded(h, { row, $index, store: this.store }) : ''}
            </td>
          </tr>)
        : ''
      ]
    ).concat(
      this._self.$parent.$slots.append
    ).concat(
      <el-tooltip effect={ this.table.tooltipEffect } placement="top" ref="tooltip" content={ this.tooltipContent }></el-tooltip>
    )
  }
</tbody>
```

table组件对于select功能恰好使用的是objec，所以对于选中功能并不是每次都能工作，能工作恰好只是使用的源数据，如[官网](http://element.eleme.io/#/zh-CN/component/table#duo-xuan)的示例。

猜测官网为什么没有采用`key`的方式，是因为并不能保证所有的情况下传入table的data都包含`key`这个唯一的键，大部分情况下table对row的`key`是无感知的，所以不太可能为了这个功能，要求用户在`data.row`中混入key这个看似无用的值。

那么有没有解决方案呢，个人认为只需修改判断数据是否存在的diff算法即可。由于项目内并未引用lodash库（lodash中有findIndex方法），只能自己写算法。又考虑table.data肯定只会是 plainObject类型，因此可简化为使用 `JSON.stringify`后比对string方可，示例

```javascript
const indexOf = function(arr, value) {
  let index = -1
  if (Array.isArray(arr)){
    arr.forEach(arr, (item, i) => {
      if(JSON.stringify(item) === JSON.stringify(value)) {
        index = i
      }
    })
  }
  return index
}

const toggleRowSelection = function(states, row, selected) {
  let changed = false;
  const selection = states.selection;
  const index = indexOf(selection, row);   //这里使用自定义的indexOf
  if (typeof selected === 'undefined') {
    if (index === -1) {
      selection.push(row);
      changed = true;
    } else {
      selection.splice(index, 1);
      changed = true;
    }
  } else {
    if (selected && index === -1) {
      selection.push(row);
      changed = true;
    } else if (!selected && index > -1) {
      selection.splice(index, 1);
      changed = true;
    }
  }
  return changed;
};
```

**Comment by jnoodle** [comment]
现在还不能支持多列排序，能提升一下这个需求的优先级么？

**Comment by fengyun2** [comment]
同问++
