### ISSUE TITLE
递归select组件无法触发change事件

### ISSUE THREAD

**Issue by grassmu** [ElemeFE/element#5604]
<div class="child-item" v-for="(model,index) in model.children" :key="model.symbol">
            <template v-if="model.children.length > 0">
                <i v-if="index == 0" @click="addChild" :index="index" tag="haschild" class="glyphicon glyphicon-minus-sign"></i>
                <i v-else @click="minusChild" :index="index" tag="haschild" class="glyphicon glyphicon-minus-sign"></i>
                <div class="logic-symbol">
                    <el-select @change="test" clearable v-model="model.symbol" placeholder="请选择逻辑关系">
                        <el-option v-for="(value, key) in condition" :key="key" :label="value" :value="key"></el-option>
                    </el-select>
                </div>
                <child-tree :model="model" :condition="condition" :eventList="eventList"></child-tree>
            </template>
</div>

上述代码里model.children是一个数组，对其进行循环，select组件里的v-model="model.symbol"，在切换后model.symbol的值都已修改，但是就无法触发change=test事件。
请问应该如何修改？

**Comment by chping2125** [comment]
@grassmu 问题解决没？今天遇到了同样的问题。
