### ISSUE TITLE
switch组件的change事件能否阻止切换的操作。

### ISSUE THREAD

**Issue by xjchenhao** [ElemeFE/element#5606]
开发团队你们好。
问题如标题。需求是，在table的list展示中，为了方便快速改变该字段的状态，我们会放一个switch开关。点击的时候，会弹出一个确认操作的提示框（为了防止误操作）。如果，我确实是误操作的话，我希望能够阻止这个切换的操作。
目前看来除了给状态值再重新取反，别无他法，还是我使用的方式不对，求解惑。

**Comment by shomychen** [comment]
我是直接更改了组件的源代码，给它添加一个点击方法然后由它的回调来判断value是否更改，之后再调用change事件

**Comment by wacky6** [comment]
直接用 :value 和 @change / @input

https://jsfiddle.net/zz20q8gn/

**Comment by ycyyf** [comment]
可以在switch组件外层包一个div元素，在这个元素上进行点击的操作逻辑处理，然后对switch组件设置pointer-events: none;
