### ISSUE TITLE
[Bug Report] Remote Search Select Component search again after select one item

### ISSUE THREAD

**Issue by glw119** [ElemeFE/element#5610]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 17.04 / Chromium 58.0.3029.110

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/glw119/e4o27qyd/1/](https://jsfiddle.net/glw119/e4o27qyd/1/)

### Steps to reproduce
1. input some characters like 'a'
2. click any drop-down menu item like 'Alabama'

### What is Expected?
Just calling the remote search function one time, after inputer the character 'a'. Not calling again after selecting some item from drop-down menu

### What is actually happening?
There are two times to calling remote search function, after input character 'a' and select some item.

**Comment by kevinheyo** [comment]
Try this!
https://jsfiddle.net/e4o27qyd/2/

1. Modify  `remote  `to  `:remote="remote"`
2. Add  `@input="handleFreezeRemote"`

**Comment by glw119** [comment]
@kevinheyo thx very much, it's working correctly
