### ISSUE TITLE
[Bug Report] filter-change does not automatically update filtered-value

### ISSUE THREAD

**Issue by frankyeyq** [ElemeFE/element#5612]
### Element UI version
1.3.7

### OS/Browsers version
macOS 10.12.4/Chrome 59.0.3071.109

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/e11274bn/2/](https://jsfiddle.net/e11274bn/2/)

### Steps to reproduce
1.默认使用filtered-value选中公司这个标签
2.点击清空，筛选标签正常渲染
3.点击选中家按钮，筛选标签正常渲染
4.点击筛选中的家，公司，然后点击筛选，filtered-value没有更新，并且再手动更新filter-value无效

### What is Expected?
filtered-value应该在filter-change时，实时更新，并且可以用filter-value控制筛选选项的选中状态

### What is actually happening?
filtered-value在点击筛选之后就无法实现数据双向绑定

**Comment by lzl529** [comment]
i got same issue...

**Comment by athena0304** [comment]
我也遇到了相同的问题，filtered-value根本不生效啊
https://jsfiddle.net/athena0304/xcydoxfr/
filteredValue一直是空的

**Comment by zhouwenbin** [comment]
数据如果是异步的，filtered-value不能过滤数据

**Comment by ttchin** [comment]
也就是说filtered-value只能一开始就设定好，不能在页面渲染后更新？

**Comment by Daker-china** [comment]
设置`el-table`的`ref`为`a` 那么可以这样拿到`filtered-value`
`let columns = this.$refs.a.columns`
`filteredValue = columns[0].filteredValue`
`filteredValue1 = columns[1].filteredValue`
以此类推 ...
@ttchin @zhouwenbin @athena0304 @frankyeyq

**Comment by my9074** [comment]
@zhouwenbin  @ttchin  如果数据是异步的，filtered-value 的问题能解决么？

**Comment by Sinosaurus** [comment]
@zhouwenbin 解决了吗？ 我现在是首次设置` filtered-value` 后，想利用其提供清空筛选`clearFilter`的方式时，无法清除` filtered-value` ，但是我绑定的值已经空了

**Comment by wunianjian** [comment]
还是不行啊…即使按照 @Draco-china 的方法都没用，我在filter-method里加了两行输出：
```
filterMethod: function(value, row, colomn) {
            console.log(value);
            console.log(this.$refs.myTable.columns[2].filteredValue);
            return value == row.emotion;
}
```
然后发现当我用代码去修改filterValue之后，输出了不属于filteredValue的value。
但是如果我手动点击“筛选”，输出的value和filteredValue都是正常的。
也就是说用代码修改filterValue之后，虽然这个值改了，它实际筛选用的却不是这个列表。这是为什么啊？我想知道“筛选”操作到底做了什么？如何用代码执行这个“筛选”操作？

**Comment by podf** [comment]
大家可以在updated() 钩子中重新

**Comment by podf** [comment]
正常情况可以引用table **ref** 来重置 **filteredValue** 。如果你的dom改变后仍需要保持 **filteredValue** 选中，需要在 
 **updated()** 钩子中重新获取 **ref** 引用后在进行过滤回显操作。
