### ISSUE TITLE
The [Bug Report] attribute does not correspond to the data

### ISSUE THREAD

**Issue by renjunqing** [ElemeFE/element#5618]
### Element UI version
1.3.7

### OS/Browsers version
macOS chrome

### Vue version
2.3.4

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
不需要

### What is Expected?
初学element，el-checkbox组件是模板中的label属性与数据对应，而el-select组件是模板中的value属性与数据对应，在el-tabs文档的示例代码中看到的是name属性与数据对应，旁边的说明却是value属性。

### What is actually happening?
啊啊啊，这个能统一下吗？全部用value是不是挺好的~

**Comment by Leopoldthecoder** [comment]
Checkbox 用 `label` 是因为 `value` 被 `v-model` 占用了。现在版本的 Vue 支持了自定义 `v-model` 的变量名，我们后面会统一的。
