### ISSUE TITLE
Is there a way to force the output of a field form inside error?

### ISSUE THREAD

**Issue by xp3310** [ElemeFE/element#5619]
### Existing Component
是

### Component Name
form

### Description
請問有方法可以強制輸出 form 中, 某個 field 的 validate 訊息嗎

文件中有提到
Form-Item Attributes
若 error 有設值 表单域验证错误信息, 设置该值会使表单验证状态变为error，并显示该错误信息

實驗過後卻無此效果

因為我的驗證全部都在後端做驗證
所以會需要後端一次驗證後,
丟回前端, 再根據這些訊息, 去決定我哪些 field 是錯的 以及要顯示什麼訊息

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/v0nkpt2x/
