### ISSUE TITLE
[Feature Request] tabs toggle flashing

### ISSUE THREAD

**Issue by yuri2peter** [ElemeFE/element#5625]
### Existing Component
Yes

### Component Name
Tabs,Table

### Description
场景：使用tabs切换标签页，标签页中渲染了一个表格，表格限制了高度。
现象：刚刚切换到的一瞬间，表格（标签页）高度并不是设定值，随后立即变为正常，造成闪烁的现象。此
现象只在第一次切换到该页时出现。
环境：element-ui 1.3.7，chrome浏览器 58.0.3029.110

**Comment by Leopoldthecoder** [comment]
这是 Bug Report，不是 Feature Request。请不要因为不想写 demo 就选择 Feature Request。

**Comment by yuri2peter** [comment]
sorry，选错了
