### ISSUE TITLE
[Feature, Request], Can, I, put, input, in, the, form?

### ISSUE THREAD

**Issue by vvhl** [ElemeFE/element#5627]
### Existing Component
是

### Component Name
table

### Description
If I put the date component into the table component,they'll have the same 'v-model' so that i can't bind a specific row of data.So is it not supported to use the time component or <input /> in the table?

![image](https://user-images.githubusercontent.com/15726547/27681762-d1e05b1e-5cf2-11e7-8974-d709dab22350.png)

![image](https://user-images.githubusercontent.com/15726547/27681780-dae34bd6-5cf2-11e7-901f-eb89a08c0108.png)

**Comment by wacky6** [comment]
Try binding v-model to `scope.row.switchVal`

**Comment by Sangeliu** [comment]
我现在也遇到这个问题了，按楼上方法解决，但报错，报一个gethours is undefined，搞不定什么情况
