### ISSUE TITLE
[Bug Report] opens the dialog again on the dialog, and the first mask layer disappears, then the second mask layer does not disappear after the second layer dialog is turned off

### ISSUE THREAD

**Issue by danielmlc** [ElemeFE/element#5628]
### Element UI version
1.3.6

### OS/Browsers version
  win7 64位/chrome 57.0.2987.133

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/jusg12Lh/1/](https://jsfiddle.net/jusg12Lh/1/)

### Steps to reproduce
在dialog上再打开一次dialog，第一层遮罩层会消失，然后关闭第二层dialog后，第二层遮罩层不会消失
注意第一个遮罩层配置
:modal-append-to-body="true"
 :close-on-click-modal="false"
第二个遮罩层配置
:modal-append-to-body="false"
  :close-on-click-modal="false"

### What is Expected?

  希望在dialog上再次打开dialog后第一层  的遮罩层都是附加在body上的，第二层的遮罩层附加在第一层的dialog上，两个遮罩层都存在，关闭dialog各自的遮罩层随后消失。

### What is actually happening?
 在dialog上再打开一次dialog，第一层遮罩层会消失，然后关闭第二层dialog后，第二层遮罩层不会消失

**Comment by danielmlc** [comment]
在使用dialog过程中大量应用dialog上弹出dialog这种方式，弹出第二层遮罩层会使第一层遮罩层消失。关闭第二个dialog后，遮罩层不自动消失。

**Comment by Leopoldthecoder** [comment]
#3499
