### ISSUE TITLE
Tabs:tabs标签页，内部有内容时，渲染tab标签时有异常

### ISSUE THREAD

**Issue by xjcloudy** [ElemeFE/element#563]
[在线演示地址](https://fiddle.jshell.net/xjcloudy/xu3ut31p/6/)

我是将 内容放到了 el-tabs 标签内的。声明了2个tab标签。

![image](https://cloud.githubusercontent.com/assets/2074921/19587419/d409c4c0-9790-11e6-9d0c-49d53fa6cc74.png)
但是渲染的结果，确实这样的
![image](https://cloud.githubusercontent.com/assets/2074921/19587437/f26caec8-9790-11e6-940a-c057c99b24e3.png)

![image](https://cloud.githubusercontent.com/assets/2074921/19587451/fdcdffba-9790-11e6-9ca1-45fa9a49e523.png)

如果tab的body 不能放到el-tabs 内，那么应该放到哪里？

version:rc-7

**Comment by baiyaaaaa** [comment]
tab 的 body 内容显示的就是<el-tab-pane>标签内的内容
