### ISSUE TITLE
[Bug Report] fix table align problem

### ISSUE THREAD

**Issue by JMwill** [ElemeFE/element#5634]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 14.04 Chrome Version 59.0.3071.109 ( offical version ) （64 bit）

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/y4aq5m20/](https://jsfiddle.net/y4aq5m20/)

### Steps to reproduce
run page and you will see the problem

### What is Expected?
el-table__fixed-header-wrapper element align the el-table__header-wrapper element and el-table__fixed-body-wrapper element align the el-table__body-wrapper

### What is actually happening?
both header and body are not align

**Comment by Leopoldthecoder** [comment]
I have no access to Ubuntu, so could you upload a screenshot?

**Comment by JMwill** [comment]
![image](https://user-images.githubusercontent.com/11496449/27784084-68fe1f70-600b-11e7-8a0d-9719f4b9233d.png)
Between 姓名 & 省份, more fix header items the gap grows bigger

**Comment by JMwill** [comment]
does anybody give me a hand?

**Comment by furybean** [comment]
最新的 2.1.0 版本已经无法重现此问题：https://jsfiddle.net/y4aq5m20/3/

**Comment by furybean** [comment]
先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。
