### ISSUE TITLE
[Feature Request] switch change event need more params

### ISSUE THREAD

**Issue by imqishi** [ElemeFE/element#5639]
### Existing Component
Yes

### Component Name
Switch

### Description
How can I do this?
One page has multiple card, and every card has a switch,  the cards are genereated by 'v-for' loop. Now I need to recognize which card's switch triggered. I ever use a param to get this but now change event has a fixed param which is new state's bool value. My earlier code is not work any longer.

I try to use @change="switch(new_state, index)" but it does not work...

**Comment by wacky6** [comment]
See: https://jsfiddle.net/okkthab6/
Outputs are in the Console.

```
@change="val => handleChange(val, index)"
```
