### ISSUE TITLE
The horizontal scroll bar appears in the [Bug Report] el-row setting gutter

### ISSUE THREAD

**Issue by hua126mail** [ElemeFE/element#5640]
### Element UI version
1.3.7

### OS/Browsers version
win7 / chrome 59.0

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/jmyw91rz/](https://jsfiddle.net/jmyw91rz/)

### Steps to reproduce
运行后，页面布局会出现横向滚动条

### What is Expected?
不出现滚动条，两侧DOM元素能紧挨浏览器两端。

### What is actually happening?
不出现滚动条。加上：gutter="20"， el-row不需要父级元素处理，两侧DOM元素能紧挨浏览器两端。类似于type="flex" justify="space-between"的效果

**Comment by hua126mail** [comment]
Sorry，the new page is https://jsfiddle.net/jmyw91rz/

**Comment by baiyaaaaa** [comment]
It's not a bug, because the parent of the el-row with gutter should have a half of the gutter width padding at least.

**Comment by clmystes** [comment]
不可以直接取消首尾元素的margin left right吗
