### ISSUE TITLE
[Bug Report], there are multiple el-select in my form, some change events are invalid, and the corresponding values are not changed after the selection

### ISSUE THREAD

**Issue by zhj2159815** [ElemeFE/element#5643]
### Element UI version
1.3.7

### OS/Browsers version
win8/chrome  58.0.3029.81 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
我的表单中，有多个el-select，一些正常，其中有些el-select选择数据后无效，对应的在其他属性改变后才会显示之前选择的数据，使用调试工具，发现对应的el-select的change事件未被调用。element-ui是最新的版本，vue是2.3.3的版本 。

### What is Expected?
正常选择select的选项，对应渲染效果。

### What is actually happening?
但是却没有调用change事件进行改变，但是修改其他字段的时候，对应的该select的数据才会展示出来。

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
