### ISSUE TITLE
The styles that [Bug Report] checkboxgroup loops out and manually join checkboxbutton will have different styles

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#5644]
### Element UI version
1.3.6

### OS/Browsers version
windows 7

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/3fnzgo14/](https://jsfiddle.net/3fnzgo14/)

### Steps to reproduce
通过v-for在checkbox-group中循环出的的button
手动加入的button

### What is Expected?
通过v-for循环出的的button和手动加入的，能有一样的间距效果

### What is actually happening?
两种方式，前者没有间距，后者有间距

**Comment by wacky6** [comment]
More likely to be a HTML issue.
The space you see is caused by newline and space.

![image](https://user-images.githubusercontent.com/9319556/27736757-24420d36-5dd8-11e7-8f46-c5d86ed904bc.png)

**Comment by Leopoldthecoder** [comment]
@wacky6 Exactly.
