### ISSUE TITLE
el-date-picker 组件value不能绑定

### ISSUE THREAD

**Issue by Qcc** [ElemeFE/element#5660]
Element UI version

1.3.7

OS/Browsers version

Windows 7 / chrom 59.0

Vue version

2.3.4

Reproduction Link

https://jsfiddle.net/1pyt95sw/

What is actually happening?
这段代码运行正常，但是el-date-picker组件的value绑定不正常，控件内不能正常显示以选取的日期。

**Comment by Leopoldthecoder** [comment]
要 `$set` 一下，直接赋值不是 reactive 的：https://jsfiddle.net/1pyt95sw/1/ 。详见 https://vuejs.org/v2/guide/reactivity.html

**Comment by Qcc** [comment]
问题解决了，感谢！！。。
