### ISSUE TITLE
[Feature Request] Add an extra event for el-dialog's hide method

### ISSUE THREAD

**Issue by KagamiChan** [ElemeFE/element#5665]
### Existing Component
Yes

### Component Name
el-dialog

### Description
Hi,

Without the v-model sugar in JSX mode, the event for clicking on close button or outer model is a little difficult to handle. 

The component does emit 2 events, but to close the dialog I have to write something like `onVisible-change={(e) => !e && (this.showModal = false)}`. Could we have another more direct and more readable event for it? I'm willing to help if I know which event name is available.

**Comment by Leopoldthecoder** [comment]
I personally feel adding a new event just for JSX cases seems a little verbose, since there is already `visible-change` to handle visibility.

**Comment by KagamiChan** [comment]
@Leopoldthecoder Thanks for your reply. To explain, with JSX on should write `onVisible-change`, which is less intuitive and somewhat awkward compared to other APIs (native event names don't contain hyphens, and for users don't know how jsx syntaxes are transformed, they may think of `onVisibleChange` or something else).

Besides, I just want to handle the case of clicking on outer modal area or on the close icon, with this API I have to check the event value.

Anyway this API already works for me, I just asking for a more "sweet" API :-)

**Comment by KagamiChan** [comment]
Found out that `on-visible-change` also works, closing this
