### ISSUE TITLE
The function of [Bug Report] MessageBox and the global close method

### ISSUE THREAD

**Issue by Devil-Cong** [ElemeFE/element#5667]
### Element UI version
1.3.4

### OS/Browsers version
window7 chrome  58.2.3029.81

### Vue version
2.3.3

### Reproduction Link
[http://jsfiddle.net/q307yb5y/1/](http://jsfiddle.net/q307yb5y/1/)

### Steps to reproduce
点击【点击打开并关闭 Message Box】即可重现BUG

### What is Expected?
Message Box 出现，并且2秒后自动关闭

### What is actually happening?
Message Box 出现，2秒后Message Box 关闭，但其【遮罩层】并没有关闭，body的overflow属性也没恢复

**Comment by Leopoldthecoder** [comment]
This is not a bug. We haven't implemented `close` method for MessageBox, so please don't use it.

**Comment by antfu** [comment]
Is there anyway to close a MessageBox programmatically? Also if the `close` isn't implemented what's the reason to have it?
