### ISSUE TITLE
Can [Feature Request] Table trigger the expansion of expand by other identifiers?

### ISSUE THREAD

**Issue by lilijialiang** [ElemeFE/element#5668]
### Existing Component
Yes

### Component Name
Table

### Description
通过对文档的了解，Table 的 expand 功能，仅能通过 type="expand" 作为触发器，而且并不能控制 expand 那列的图标等等，请问能否通过其他元素（ 例如: el-button 等 ）作为触发器？

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this feature.

**Comment by 2015-lizaiyang** [comment]
做了这个功能，应该给外界用户提供一个自定义操作接口。不然这个项目就有多了个约束。

**Comment by dongdongtian** [comment]
> Sorry, we have no plan to add this feature.

When type=expand, can you control the expand icon as you control other columns?
