### ISSUE TITLE
[Bug Report] inputs require two clicks instead of one to enter text on tablets/mobiles

### ISSUE THREAD

**Issue by DamienFF** [ElemeFE/element#5675]
### Element UI version
1.3.7

### OS/Browsers version
ios safari and ios chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
demo website: http://element.eleme.io/#/en-US/component/input

### What is Expected?
Singe click should enable entering text.
=> Elementui is the only vuejs library requiring two clicks.
While it is clear that elementui is not a mobile library it is expected a normal browsing experience on mobiles/tablets since it is nowadays the most frequent way of browsing the web.

### What is actually happening?
The first click focus the input and the second one allows entering text.

**Comment by wacky6** [comment]
Can't reproduce on my iPhone. Keyboard pops up normally after one click.
