### ISSUE TITLE
[Bug, Report], $confirm (),.Then (),.Cathch () browser, JS, down compatible error (Promise)?

### ISSUE THREAD

**Issue by NagiaME** [ElemeFE/element#5676]
### Element UI version
1.3.7

### OS/Browsers version
ALL / IE11|10|9 | Chrome49 | FireFox45

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/tacnbwn7/3/](https://jsfiddle.net/tacnbwn7/3/)

### Steps to reproduce
To view the jsfiddle demo in IE11|10|9 | Chrome49 | FireFox45

### What is Expected?
 IE11|10|9 | Chrome49 | FireFox45 Promise down？

### What is actually happening?
跪请认真点，清掉大材小用Promise，感谢

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/27812837-65fa7294-60a4-11e7-90f9-49a3d67be255.png)

Those browsers do not support Promise natively, so you need to import a polyfill. And if you prefer, you can always use a `callback`
