### ISSUE TITLE
The [Bug Report] cannot dynamically change the el-col span property, which dynamically changes the width of the el-col

### ISSUE THREAD

**Issue by JerryChin** [ElemeFE/element#5677]
### Element UI version
1.3.7

### OS/Browsers version
Windows 7

### Vue version
2.2.1

### Reproduction Link
[https://jsfiddle.net/ct6jp8gk/](https://jsfiddle.net/ct6jp8gk/)

### Steps to reproduce
直接点击jsfiddle运行出现的开关，el-col　没有任何变化。

### What is Expected?
el-col span宽度变为 12。

### What is actually happening?
el-col span宽度保持不变。

**Comment by Leopoldthecoder** [comment]
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "span"
```

The error pretty much explains why it doesn't work. You should not mutate an inner `prop` directly. Correct usage: https://jsfiddle.net/ct6jp8gk/1/ . For more information: https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow
