### ISSUE TITLE
[Alert] 组件的 description属性 不支持多行显示

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#568]
有时候希望 tips 换行显示多行内容，目前 el-alert 是没办法做到的

**Comment by Leopoldthecoder** [comment]
是指希望传 HTML 模板进去？

**Comment by isunkui** [comment]
@Leopoldthecoder 是的，目前是通过属性传值的，导致没办法自定义样式

**Comment by Leopoldthecoder** [comment]
样式是可以自定义的，只不过通过属性传进去之后是放在一个 `span` 里，没有办法显示多行。

**Comment by Leopoldthecoder** [comment]
@zifeixu85 考虑一下 Alert 要不要支持多行文本？

**Comment by fishpaw** [comment]
@zifeixu85 ，我觉得可以放开这里的限制，可以显示多行，但需要统一不同行数下的视觉和显示规则。
