### ISSUE TITLE
[Bug Report] el-button bind the same event when use v-if

### ISSUE THREAD

**Issue by linkhong** [ElemeFE/element#5682]
### Element UI version
1.3.7

### OS/Browsers version
safari 10.1.1 (12603.2.4) / chrome  59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/af5eL34u/](https://jsfiddle.net/af5eL34u/)

### Steps to reproduce
use v-if with the same condition variable, and the el-buttons place in the same DOM level
1. click button1
2. click toggle
3. click button2

### What is Expected?
the 'say' method only triggered when click button1, not button2

### What is actually happening?
button1 and button2 both trigger the 'say' method

**Comment by Leopoldthecoder** [comment]
You should use `key` in this case to avoid Vue reusing existing Button: https://jsfiddle.net/af5eL34u/1/ . More info: https://vuejs.org/v2/api/#key .
