### ISSUE TITLE
vaidation will not been triggered when keydown is ocured

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#5683]
### Element UI version
1.3.7

### OS/Browsers version
all

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/L5ogkg2j/1/](https://jsfiddle.net/L5ogkg2j/1/)

### Steps to reproduce
1. click on the input
2. validation will not been triggered
3. comment line 13,and then uncomment line 14
4. blur the input
5. validation will be triggered

### What is Expected?
other events including customer events should been supported

**Comment by zzzgit** [comment]
what is your opinion

**Comment by Leopoldthecoder** [comment]
Because there is no `click` trigger. If you are trying to validate the form (or a form item) when the input is clicked, you can do that in the input's click callback.

**Comment by zzzgit** [comment]
is there some problem to make element support ambitious event
