### ISSUE TITLE
[Feature Request] Using vue-sortable with el-table?

### ISSUE THREAD

**Issue by pranav-smpx** [ElemeFE/element#5684]
### Existing Component
Yes

### Component Name
El-Table

### Description
Basically the title. Is it possible to use el-table with vue-sortable or sortable? I am looking for ways to rearrange the rows of table through drag and drop.

Thanks!

**Comment by mmarquez** [comment]
I've done a little test, but ended using a simple <table>.
But I'm using Vue.Draggable instead.

**Comment by EmilyRosina** [comment]
We're wanting to use Element but need some way of dragging the rows of a table so to allow reordering.
We're at a midway stop now as element doesn't have this built in, however vue-draggable and vue-sortable go someway to providing this functionality. Just how we combine it all is hurting my head a bit, as Element markup only specifies columns, not rows..

Help! Anyone found a fix?

**Comment by helios741** [comment]
@EmilyRosina Hello，i met the same problem as you, do you have a solution? thanks

**Comment by steffanhalv** [comment]
Me to, I tried with vuedraggable:

```
<draggable
        v-model="items"
        @end=""
        :options="{draggable: 'tr', scroll: true, group: {name: 'items', pull: 'clone', put: false}}">
        <el-table
            ref="items"
            @selection-change="selection"
            :data="items">
            <el-table-column
              fixed
              type="selection"
              width="40">
            </el-table-column>
          <el-table-column
              label="Name">
            <template slot-scope="scope">
              <el-input
                v-model="scope.row.name"
                placeholder="Name"></el-input>
            </template>
          </el-table-column>
        </el-table>
</draggable>
```

But it does not work..

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gozhg07a/1/ Note that `row-key` is necessary to get a correct row order.

**Comment by blackmiaool** [comment]
I wrote a component that can make el-table sortable without row-key.

https://gist.github.com/blackmiaool/ccb74bc87eeeb71c864aeceaf197bdb4

**Comment by jggj21** [comment]
Alguno puede ayudarme, necesito aplicarlo para arrastrar pero en base a toda la columna, así como este ejemplo: https://sortablejs.github.io/Vue.Draggable/#/table-column-example, pero estoy trabajdndo con element- ui-el-table-draggable https://github.com/WakuwakuP/element-ui-el-table-draggable

**Comment by dnkTin** [comment]
> Can any one help me, I need to apply it to drag but based on the whole column as well as this example: https://sortablejs.github.io/Vue.Draggable/#/table-column-example, but I am working with element- ui -el-table-draggable https://github.com/WakuwakuP/element-ui-el-table-draggable

I think you can drag the header (th tag) of the table. On the ```onEnd``` method of sortablejs, the data of table can be reordered - in this case reorder the key in each object - based on the index (newIndex and oldIndex) passing to the ```onEnd``` method.

**Comment by cloydlau** [comment]
Neither row-key nor v-if redraw is effective in v2.13.2. $destroy+$mount is ok but some other issues occured, view is still probably not synchronized with data when appending or deleting of rows. I tried emptying the value before setting it, and it finally worked......

I encapsulated a small component, it's easy and configurable, should meet most needs.  [git link](https://github.com/cloydlau/elastic-list)

我用的v2.13.2版本 row-key和v-if重绘都没有效果...... 用$destroy+$mount有效果 但是产生了其他的问题 比如结合行的添加和删除功能的时候 仍然存在视图不更新的问题。后来采用在赋值之前先清空一次的方式 终于解决了......

封装了个小组件 简单灵活 应该可以覆盖大部分需求 [git地址](https://github.com/cloydlau/elastic-list)

npm i elastic-list / yarn add elastic-list

```
<ElasticList v-model="value">
  <el-table-column label="a" prop="a"/>
  <el-table-column label="b" prop="b"/>
</ElasticList>
```
