### ISSUE TITLE
[Feature Request] Ajax call on table row expand and display data on expanded row

### ISSUE THREAD

**Issue by rodwin** [ElemeFE/element#5687]
### Existing Component
Yes

### Component Name
table

### Description
I am trying to call an ajax to display a list of item when a row is expanded. I can already call the ajax using the expand event but im stuck on displaying it in the expanded row.

Thanks

**Comment by Leopoldthecoder** [comment]
An example: https://jsfiddle.net/7g3fgLgq/

**Comment by rodwin** [comment]
Thanks @Leopoldthecoder
