### ISSUE TITLE
[Feature, Request], elementUI, table, component, expands, cannot, immediately,, refresh, the, UI

### ISSUE THREAD

**Issue by eason1999** [ElemeFE/element#5690]
### Existing Component
是

### Component Name
el-table

### Description
When the elementUI table component expands the row data changes, it cannot immediately refresh the UI, changing the size of the browser window to refresh，Why???

**Comment by Leopoldthecoder** [comment]
This is not a feature request. If you're issuing a bug, please prepare an online demo. Words cannot help us locate the problem.
