### ISSUE TITLE
[Bug Report] el-dialog uses multiple select drop-down components in form, some of which have no effect.

### ISSUE THREAD

**Issue by zhj2159815** [ElemeFE/element#5692]
### Element UI version
1.3.7

### OS/Browsers version
Win8/Chrome 58.0.3029.81 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://codepen.io/zhj2159815/pen/XgZBmj](https://codepen.io/zhj2159815/pen/XgZBmj)

### Steps to reproduce
1、点击新增按钮，选择上级，加盟等级，选择后，对应选择下拉框中没有具体的选中项的效果。

### What is Expected?
正常应该显示具体选中的下拉项。

看了下底层的代码和调试情况，没有触发相应的value改变事件，看了下底层实现代码，有使用dispatch，是否跟 vue2.0以上的 禁用 dispatch有关系。

### What is actually happening?
没有显示具体选中的下拉项。

**Comment by Leopoldthecoder** [comment]
Change line 90 form
```JS
this.join = {};
```
to
```JS
this.join = {
  parent: ''
};
```
