### ISSUE TITLE
[Feature Request] Open up an uploader from a menu item

### ISSUE THREAD

**Issue by cantao** [ElemeFE/element#5693]
### Existing Component
Yes

### Component Name
el-upload, el-menu-item

### Description
I am trying to open an upload dialog with a click on a menu item (https://jsfiddle.net/4xerguk9/5/).

It works, but the menu item gets a shorter clickable gray area.

Is it an issue, or am I doing something very wrong?

Thanks a lot,
Cantão.

**Comment by Leopoldthecoder** [comment]
Simply override its style: https://jsfiddle.net/4xerguk9/6/

**Comment by cantao** [comment]
Genius! I have tried this, but I am completely new to web technologies in general (my background is in numerical simulation). I tried no disable all styles for el-upload in the hope that the el-menu-item style would override it, but it didn't work.

Thank you very much!
