### ISSUE TITLE
How does [Feature Request] use badge tags in the Tabs tab so that prompt information is displayed on the tag page?

### ISSUE THREAD

**Issue by wangyongchao123** [ElemeFE/element#5697]
### Existing Component
是

### Component Name
badge and tabs

### Description
怎样将badge标记用在Tabs 标签页中，使提示信息显示在标签页中

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
