### ISSUE TITLE
The [Feature Request] table component, the prop property of the el-table-column, can support the filter?

### ISSUE THREAD

**Issue by wxxcarl** [ElemeFE/element#5701]
### Existing Component
No

### Component Name
-

### Description
我现在是这么实现的：

`<el-table-column label="时间"  align="center">
			    <template  scope="scope">
			        {{scope.row.targetTime | dateFormat}}
			    </template>
			</el-table-column>`

能不能更简单一点，如下：
`<el-table-column prop="targetTime | dateFormat" label="时间"  align="center"></el-table-column>`

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
