### ISSUE TITLE
[Bug Report] about el-steps 

### ISSUE THREAD

**Issue by cyzeng-Luca** [ElemeFE/element#5703]
### Element UI version
1.3.7

### OS/Browsers version
window 7

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/while_own/1wmoefnf/](https://jsfiddle.net/while_own/1wmoefnf/)

### Steps to reproduce
i set active is 2 but the status is error.it show a red half line.

### What is Expected?
when ths step is error, it should stop.

### What is actually happening?
if it's ok,how can i do it ? thanks

**Comment by Leopoldthecoder** [comment]
> when the step is error, it should stop.

You mean when the status of a step is `error`, clicking the `next` button should do nothing? Just handle this in the `next` method, since you're the one who wrote that method after all.

**Comment by wacky6** [comment]
@Leopoldthecoder I think he wants to talk about this:

![image](https://user-images.githubusercontent.com/9319556/27858909-9cb232c6-61a9-11e7-9a5a-d9486bb67521.png)

Seems to be bug?

**Comment by cyzeng-Luca** [comment]
@Leopoldthecoder @wacky6       i mean it  with  wacky6 ,how can i remove the red line ,when step is error

**Comment by wacky6** [comment]
For a quick fix, override relevant css: https://jsfiddle.net/geab1hy2/

A proper fix needs to restructure current style implementation. @Leopoldthecoder What do you think?

**Comment by Leopoldthecoder** [comment]
@wacky6 I checked the design resource, and it turns out you're right.

But why is style implementation restructure is needed? For me it seems your quick fix is working fine.

**Comment by wacky6** [comment]
On my first glance, I found some duplicated style entry. Please forgive my sometimes perfectionist ego.

![image](https://user-images.githubusercontent.com/9319556/27861228-84a848f6-61b2-11e7-8544-92752432859d.png)

---

I think the problem is related to `<i class="el-step__line-inner">`. A patch to `calcProgress()` method should solve it:

The `step` for error/warning should be `0` (or whatever stated in design documents).  I can make a PR if the design can be provided.

I am not certain why `border-color / border-width` is used for the colored line. I would use a `div` instead.

**Comment by wacky6** [comment]
In current implementation:

`50% width, 1px border` renders a width of `1 + 34 + 1 px`, as shown in the box model:

![image](https://user-images.githubusercontent.com/9319556/27862196-af7be07a-61b6-11e7-9ec9-816983c43711.png)

However, step line div is 68px, the rendered progress line is not exact "50%" width.

**Comment by cyzeng-Luca** [comment]
it's very useful for me , and make it in my items,at the same time,i use nextTick to make it length 100% after DOM ,like this 
![image](https://user-images.githubusercontent.com/25954683/27864172-11560d08-61c0-11e7-81e0-903e2f7baf0e.png)
if the line lenght design by ourselves,it would be better. 
best wish to elementUI better and better.

**Comment by wacky6** [comment]
@Leopoldthecoder I suggest reopen this issue.

**Comment by Leopoldthecoder** [comment]
![steps](https://user-images.githubusercontent.com/10095631/27907046-8ec5e598-6278-11e7-92bf-82dd88432857.png)

Oh, sorry I forgot about this one. As for `1 + 34 + 1 px` not being exactly half of `68px`, it's not a big problem, so you can keep it as is for now.

**Comment by wacky6** [comment]
Fix the 50% width/height problem with `box-sizing: border-box`, PR: https://github.com/ElemeFE/element/pull/5738

---

Fix the error step behavior: https://jsfiddle.net/8d0j0vx6/1/

Modification: https://github.com/wacky6/element/commit/d30c2829350915389c79d95d4ef2a5421bf19bf1

Advancing active step beyond error step is considered to be undefined.

@cyzeng-Luca Please help with testing.

**Comment by Leopoldthecoder** [comment]
@wacky6 The error step fix seems working, so could you send a PR?
