### ISSUE TITLE
[Bug Report] Table组件的筛选功能无法国际化

### ISSUE THREAD

**Issue by SteveCruise** [ElemeFE/element#5705]
### Element UI version
1.3.7

### OS/Browsers version
chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
运行一下，点击“标签”， 里面有“筛选”和“重置”，两个字段只能是中文，无法自设，以便于修改为英文

### What is Expected?
“标签”里面有“筛选”和“重置”，两个字段只能是中文，无法自设，以便于修改为英文

### What is actually happening?
“标签”里面有“筛选”和“重置”，两个字段只能是中文，无法自设，以便于修改为英文

**Comment by SteveCruise** [comment]
链接给错了，用这个https://jsfiddle.net/7zzzqrdv/

**Comment by Leopoldthecoder** [comment]
You don't have to set them yourself because our i18n already takes care of them. Setting up i18n to English will resolve this.

**Comment by SteveCruise** [comment]
谢谢谢谢！
