### ISSUE TITLE
组件table 里 column 的prop 是不支持 prop[index].prop 这样的格式的吧！

### ISSUE THREAD

**Issue by icssjs** [ElemeFE/element#5707]
好像是不支持的，我在util.js里找到 getValueByPath 这个方法 感觉写得不太好阿！

**Comment by Leopoldthecoder** [comment]
用点号连接：`prop.index.prop`

**Comment by icssjs** [comment]
还有这个姿势。我还重新了一个方法，我在column 的attr formatter 里能调用talbes 的方法吗，不然取当前 cell 的值好麻烦
