### ISSUE TITLE
[Bug Report] two layer loop nested form elements, edit the latter element, delete the previous elements will lead to the value of the latter element reset

### ISSUE THREAD

**Issue by SuperAL** [ElemeFE/element#5708]
### Element UI version
1.3.7

### OS/Browsers version
win7 chrome最新版

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/Alexee/h9xL99pe/](https://jsfiddle.net/Alexee/h9xL99pe/)

### Steps to reproduce
1. 添加步骤
2.上下选择不一样的步骤
3. 操作下面步骤的输入框或者checkbox，然后删除上面的步骤，下面的修改会被重置

### What is Expected?
已经修改的表单值不被重置

### What is actually happening?
位于数组后方已经修改的表单值会被重置，已经使用原生vue测试过，非vue的问题

**Comment by Leopoldthecoder** [comment]
The demo seems a little verbose and your description is kinda vague, so I don't quite get what your problem is. Please elaborate the problem and prepare a clearer demo.

**Comment by SuperAL** [comment]
the demo clearly demonstrates the problem，
1. you dynamicly add step（click ‘添加步骤’），
2. at step2  you then select different option，edit the input or checkbox below，
3. then delete the step1，you will find that everything you edit on step2 reset to the default value.

**Comment by Leopoldthecoder** [comment]
This is caused by Select emitting `change` event whenever its value changes. Ideally `change` event doesn't fire when the value updates programmatically, which will solve this problem here. We'll work on that in the next major version.

**Comment by baiyaaaaa** [comment]
This problem is because your loop without the `key` prop, please checkout the fixed demo here.https://jsfiddle.net/h9xL99pe/8/
