### ISSUE TITLE
[Bug Report] The link in the Changelog file don't correctly render on final Changelog page

### ISSUE THREAD

**Issue by yangzj1992** [ElemeFE/element#5710]
### Element UI version
1.3.7

### OS/Browsers version
MacOS/Chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/yangzj1992/pj71jkyw/349/](https://jsfiddle.net/yangzj1992/pj71jkyw/349/)

### Steps to reproduce
The link in the Changelog file don't correctly render on final Changelog page.

### What is Expected?
Render "scoped slots" link correctly

### What is actually happening?
Not render "scoped slots" link

**Comment by Leopoldthecoder** [comment]
I'm not sure I understand this. Could you elaborate which changelog link and what scoped slot?

**Comment by yangzj1992** [comment]
Look at [jsfiddle](https://jsfiddle.net/yangzj1992/pj71jkyw/349/) link. I think it's pretty clear to show Changelog 1.1.0 has an error.. And there also have screen capture for the markdown file.

**Comment by Leopoldthecoder** [comment]
Fixed in #5725
