### ISSUE TITLE
[Bug Report] table-column uses the render function to add tooltip, but does not prompt for text

### ISSUE THREAD

**Issue by tmyeahsing** [ElemeFE/element#5711]
### Element UI version
1.3.7

### OS/Browsers version
win7/ chrome 59.0.3071.115（正式版本） （32 位）

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/ce5wwodq/](https://jsfiddle.net/ce5wwodq/)

### Steps to reproduce
在table外面放置一个el-tooltip
在table-column里面使用render-header调用appendTip方法，appendTip方法为表头添加一个tooltip

### What is Expected?
两个tooltip都可以正常工作，即鼠标滑过会提示tip文字

### What is actually happening?
只有表格外的tooltip正常，表头的不正常

**Comment by Leopoldthecoder** [comment]
For the record: https://jsfiddle.net/ce5wwodq/1/

It has to be a bug of Tooltip itself. I'll come back later.

**Comment by pengchongfu** [comment]
after debugging for a long time, I found the code `placement: 'top-center'` was wrong :(

we should use `top` to instead of `top-center`

https://jsfiddle.net/ce5wwodq/2/

**Comment by tmyeahsing** [comment]
haha, sorry for my mistake

**Comment by Leopoldthecoder** [comment]
@pengchongfu OMG...
