### ISSUE TITLE
[Bug Report] el-table-column unusual behavior with v-if or v-show

### ISSUE THREAD

**Issue by wangtjwork** [ElemeFE/element#5712]
### Element UI version
1.3.7

### OS/Browsers version
win 10/ chrome 58.0.3029.110

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/co8c0sk4/](https://jsfiddle.net/co8c0sk4/)

### Steps to reproduce
Click on the change button twice will make the table appear broken.

If v-if changed to v-show, the columns will not be hidden, and clicking on the button will not do anything.

### What is Expected?
Clicking on the change button will be able to show between Address and Name.

### What is actually happening?
Clicking on the change button will break the table. It doesn't matter if I use v-show or v-if, it simply won't work.

**Comment by pranav-smpx** [comment]
A similar problem happens if you try to dynamically change the width of some column.

**Comment by wangtjwork** [comment]
I tried to control el-table itself using v-if and v-else-if. Still no use when changed. Looks like there's something dynamic going on behind the back that's preventing it from switching.

**Comment by Leopoldthecoder** [comment]
You need to add `key`: https://jsfiddle.net/co8c0sk4/7/

**Comment by MightyCoffeeMachine** [comment]
Doesn't work with v-show...my table is pretty big, i would like to avoid to rerender everything... :(
