### ISSUE TITLE
[Feature Request] 缺少通过压缩包引入element-ui的方式

### ISSUE THREAD

**Issue by SteveCruise** [ElemeFE/element#5713]
### Existing Component
否

### Component Name
element-ui

### Description
vue可以下载vue.min.js来本地引入。element-ui缺少这种方式。在本地调试时，每次刷新页面都有一秒的延迟，就在于从cdn下载element-ui（含国际化）。
而从webpack那种方式会导致打包后的js文件超过1Mb大小。希望可以通过element-ui.min.css和element-ui.min.js来本地引入，有利于本地开发测试。

**Comment by SteveCruise** [comment]
从cdn下载后本地引入会导致icon无法显示。

**Comment by duuliy** [comment]
请问您是怎么做的cdn  国际化
