### ISSUE TITLE
[Bug Report] Time select alignment not working

### ISSUE THREAD

**Issue by adrian999999** [ElemeFE/element#5716]
### Element UI version
1.3.7

### OS/Browsers version
Any

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/hohouoer/2/](https://jsfiddle.net/hohouoer/2/)

### Steps to reproduce
when align set to center it does not set input to center

### What is Expected?
Center the input value

### What is actually happening?
value is not centered regardless of the align value

**Comment by Leopoldthecoder** [comment]
`align` refers to the alignment of the dropdown menu: https://jsfiddle.net/d21qfrg1/
