### ISSUE TITLE
[Bug Report] Time select time format

### ISSUE THREAD

**Issue by adrian999999** [ElemeFE/element#5718]
### Element UI version
1.3.7

### OS/Browsers version
Any

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/hohouoer/3/](https://jsfiddle.net/hohouoer/3/)

### Steps to reproduce
Time select format does not work for time select

### What is Expected?
Input value should format according to `format` setting

### What is actually happening?
Time select always show time format in `HH:mm` style

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/27893541-db05c012-6238-11e7-94a7-1176b805e25a.png)

`format` is only available for TimePicker.
