### ISSUE TITLE
[Bug Report] The table width is not normal in tabs 

### ISSUE THREAD

**Issue by yuri2peter** [ElemeFE/element#5722]
### Element UI version
1.3.7

### OS/Browsers version
Chrome 58.0.3029

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/co8c0sk4/3/](https://jsfiddle.net/co8c0sk4/3/)

### Steps to reproduce
Switch to tag one and observe carefully.

### What is Expected?
When the tabs are switched, the table can be displayed normally.

### What is actually happening?
The initial width of the table is 80px, returning to normal at the instant of the switching tag, so that flicker can be observed.

**Comment by yuri2peter** [comment]
Well, is anybody home?

**Comment by Leopoldthecoder** [comment]
Fixed in #5722
