### ISSUE TITLE
[Bug Report] Table filters fail after inserting new rows. (表格中插入新数据后，过滤器会失效)

### ISSUE THREAD

**Issue by laobubu** [ElemeFE/element#5724]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 14.04 / Chromium 58

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/xgyz9wex/](https://jsfiddle.net/xgyz9wex/)

### Steps to reproduce
1. User filters out some rows.
2. Program inserts new rows.

### What is Expected?
After inserting new rows, filtered rows shall still be invisible.

### What is actually happening?
After inserting new rows, all rows (including filtered-out rows) appear.

**Comment by Aysnine** [comment]
have any progress?
