### ISSUE TITLE
After the [Bug Report] Table is fixed, the shadow of the fixed column does not disappear and the style looks bad when the screen is wide enough

### ISSUE THREAD

**Issue by ting570732** [ElemeFE/element#5727]
### Element UI version
1.3.7

### OS/Browsers version
Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://github.com/ElementUI](https://github.com/ElementUI)

### Steps to reproduce
1.在官方例子中，找到表格固定列的例子；
2.使用浏览器开发人员工具增大表格外部的容器宽度，当滑动列的内容足够展示得下时，滑动阴影仍然不消失。AntDesign是没有这个问题的。

### What is Expected?
Table固定列后，在屏幕够宽的情况下，固定列的阴影不消失，不美观。
后来查看了AntDesign的样式，发现AntDesign是没有这个问题的。
请采纳尽快修改！谢谢！

### What is actually happening?
项目着急用。

**Comment by Leopoldthecoder** [comment]
在下个大版本中，固定列只会在其他列被滚动时才显示阴影。
