### ISSUE TITLE
[Bug Report] Cascader hover selection problem

### ISSUE THREAD

**Issue by xkrabb** [ElemeFE/element#5730]
### Element UI version
1.3.7

### OS/Browsers version
mac/chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
重现链接是没有，官网链接上的例子就有问题，http://element.eleme.io/#/zh-CN/component/cascader
官网提供的Cascader组件第二个用例hover触发子菜单，快速hover并选中末尾选项，偶现选项跳选情况，change-on-select为false也会出现上一级菜单被选中情况。

### What is Expected?
排查偶现问题

### What is actually happening?
快速选中后偶尔出现值自行跳窜

**Comment by Dreamacro** [comment]
Fixed in #6189
