### ISSUE TITLE
 [Bug Report] Conflict between rowClick and check box events in table component

### ISSUE THREAD

**Issue by chenhangbin** [ElemeFE/element#5731]
### Element UI version
1.3.7

### OS/Browsers version
Chrome 57.0.2987.133

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
<el-table :data="serverlist" highlight-current-row v-loading="listLoading"  @row-click="rowClick" style="width: 100%;font-size: 12px;"  height="400">
			<el-table-column type="selection" width="55" fixed></el-table-column>
</el-table>
table组件如果定义了 rowClick 又加了 type="selection"，复选框，会向上冒泡

### What is Expected?
建议提供参数可以阻止

### What is actually happening?
现在点击多选框直接执行了rowClick的事件

**Comment by furybean** [comment]
@chenhangbin 
Duplicate with #7326. Please track that issue.
