### ISSUE TITLE
[Feature Request] How to change the activeIndex in NavMenu?

### ISSUE THREAD

**Issue by CoolAndCold** [ElemeFE/element#5736]
### Existing Component
Yes

### Component Name
NavMenu

### Description
1. I wanner change the highlight state of nav-menu-item in nav-menu,but can't find a method or property to change it.

2. I read the source code and find the activeIndex is a private property.

3. Could Da Shen Men give a way to resolve it or make 'activeIndex' public? 

4. Thanks very much!Ci Zhi Jing Li~😂

**Comment by Leopoldthecoder** [comment]
You can use `activedIndex` to change the highlighted menu item: https://jsfiddle.net/kfL3L4pL/

**Comment by webMagicX** [comment]
default-openeds & default-active 只在菜单初始化化的时候发生了改变，如果能够动态监听并改变菜单状态就好了；现在使用 activeIndex & openedMenus 来完成这个功能，但这毕竟没有对外形成文档。

**Comment by webMagicX** [comment]
default-active & default-openeds 只在菜单初始化化的时候发生了改变，如果能够动态监听并改变菜单状态就好了；现在使用 activeIndex & openedMenus 来完成这个功能，但这毕竟没有对外形成文档。
