### ISSUE TITLE
[Bug Report] Selects don't open correctly when placed inside sticky blocks that are at the bottom of the viewport with Chrome

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#5737]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 17.04, Chrome 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/yosn38tq/](https://jsfiddle.net/yosn38tq/)

### Steps to reproduce
Place a select or paginator with built-in select within a sticky container (position: sticky) and place the container at the bottom of the viewport (bottom: 0).
Open the select.

### What is Expected?
The select should open upward as it does when placed in a non-sticky container when there is not enough room below the element

### What is actually happening?
The select opens downward and the options are invisible in Chrome. The error does *not* occur with Firefox 54.0.

**Comment by Leopoldthecoder** [comment]
It seems Chrome has fixed this.
