### ISSUE TITLE
[Bug Report] On demand not working for CSS

### ISSUE THREAD

**Issue by gijo-varghese** [ElemeFE/element#5740]
### Element UI version
1.3.7

### OS/Browsers version
Windows, latest Chrome

### Vue version
2.3.4

### Reproduction Link
Its under 'build'

### Steps to reproduce
.babelrc
```
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
```

### What is Expected?
On demand for CSS file too after building. Right now everything is inside

### What is actually happening?
I only 2-3 components inside Element. I've edited the babelrc file to load only the components I need. The js file after building looks fine. However, the CSS file contains everything.

**Comment by Leopoldthecoder** [comment]
I just tested this and it works fine. If you haven't solved this, give us a GitHub repo.
