### ISSUE TITLE
[Bug Report] 日期选择器 type="daterange" 怎么给一个默认值？

### ISSUE THREAD

**Issue by hujianjian187** [ElemeFE/element#5744]
### Element UI version
1.1.2

### OS/Browsers version
chrome59

### Vue version
2.1.8

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/355/](https://jsfiddle.net/pj71jkyw/355/)

### Steps to reproduce
让日期有个默认值

### What is Expected?
求回答 解决！

### What is actually happening?
求回答 解决！

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/356/

**Comment by hujianjian187** [comment]
@Leopoldthecoder   think you!
