### ISSUE TITLE
[Bug Report] Element UI causing Vue Dev Tools to crash

### ISSUE THREAD

**Issue by luon08** [ElemeFE/element#5745]
### Element UI version
1.3.7

### OS/Browsers version
WIN10 / Chrome 59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
1.use many el tag in template
2.open vue devtool
3.When trigger Element UI event, large quantity of events causing Vue Dev Tools to crash

### What is Expected?
Vue Dev Tools work fine, memory not leak

### What is actually happening?
 Vue Dev Tools crash because too many events cause memory leak

**Comment by rhinonan** [comment]
1.use just one el-dialog
2.open vue devtool
3.When change dialogVisible to ture, and if dev tool is open, page crash

**Element UI version** 
1.4.1

**OS/Browsers version** 
WIN10/ Chrome58.0.3029.110

**Vue version** 
2.4.2

**Vue.js devtools** 
3.1.6

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/29748348-c7f038e4-8b47-11e7-94b0-e1325a895d87.png)
For the Dialog, I switched its visibility to `true` and three events are emitted. The dev tool is still functioning.

![image](https://user-images.githubusercontent.com/10095631/29748353-d9a71026-8b47-11e7-9c80-469070d4876c.png)
For the Tag, I created 1000 Tags and closed one of them, only one event is emitted. The dev tool is still functioning.

@luon08 @rhinonan If you're encountering dev tool crash, please at least provide a reproduction link, which saves time for us all.

Closing this for lack of reproduction.

**Comment by feichao** [comment]
the right way is here: https://github.com/vuejs/vue-devtools/issues/377
