### ISSUE TITLE
The [Bug Report] Select selector drop-down box scroll bar is not in the right position.

### ISSUE THREAD

**Issue by jin9999** [ElemeFE/element#5747]
### Element UI version
1.3.7

### OS/Browsers version
chrome

### Vue version
2.3.4

### Reproduction Link
[https://github.com/ElemeFE/element/issues/5746](https://github.com/ElemeFE/element/issues/5746)

### Steps to reproduce
当下拉框值很多出现滚动条时.
选择最后一个值.
然后选择重新选择，下拉框显示的值是第一个，但滚动条却是滚动到底部的状态。

### What is Expected?
滚动条应该是在顶部，或者默认展示值是在底部。

### What is actually happening?
默认值是第一个开始，滚动条却在底部。

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
