### ISSUE TITLE
Can [Feature Request] datepicker support inline mode?

### ISSUE THREAD

**Issue by iamwelk** [ElemeFE/element#5749]
### Existing Component
是

### Component Name
datepicker

### Description
能否像https://github.com/charliekassel/vuejs-datepicker 这个组件一样支持line模式？

**Comment by iamwelk** [comment]
![image](https://user-images.githubusercontent.com/6983075/27945534-02bc3e3c-6320-11e7-8ce6-b4a5e6a9e1e4.png)

**Comment by ugrupp** [comment]
I would also be very much interested in this!

**Comment by coderdiaz** [comment]
:+1:

**Comment by jstdoit** [comment]
+1

**Comment by shingo0620** [comment]
+1

**Comment by antonreshetov** [comment]
+100

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
