### ISSUE TITLE
用了el-select报错，提示NotFoundError: Node was not found。

### ISSUE THREAD

**Issue by kinghulu** [ElemeFE/element#575]
###用了el-select报错，提示NotFoundError: Node was not found。
删了这个组件页面就正常了。求指点啊

**Comment by Leopoldthecoder** [comment]
请提供在线 demo

**Comment by kinghulu** [comment]
项目源码:[https://github.com/kinghulu/vueElementDemo](url)，引用el-select文件在src/admin/studentAdd.vue。我换成原生select也好使。
demo预览地址：[](http://yaohuitao.com/t/vueElement/#/admin/studentAdd)。（如果不报错，点几次左侧菜单就报错了。）
感谢~

**Comment by Leopoldthecoder** [comment]
Fixed in #617
