### ISSUE TITLE
Datepicker is not selected

### ISSUE THREAD

**Issue by eason1999** [ElemeFE/element#5754]
### Element UI version
1.3.5

### OS/Browsers version
win7/Chrome 59.0.3071.115

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure](https://jsfiddle.net/api/post/library/pure)

### Steps to reproduce
step1：<script src="//unpkg.com/element-ui@1.3.5/lib/index.js"></script>版本为1.3.5时，无法显示选中状态切不可显示‘今天’字样；
step2：<script src="//unpkg.com/element-ui@1.3.7/lib/index.js"></script>版本为1.3.7时，可以正常显示选中状态和‘今天’字样；

### What is Expected?
低版本1.3.5可显示选中状态和‘今天’字样；

### What is actually happening?
低版本1.3.5可显示选中状态和‘今天’字样；

**Comment by Leopoldthecoder** [comment]
The bug is fixed in 1.3.6. And there is no way to publish another 1.3.5.
