### ISSUE TITLE
[Bug Report] 'fiterable' is not work when using "Dynamically load child options" of Cascader component

### ISSUE THREAD

**Issue by sandysong** [ElemeFE/element#5755]
### Element UI version
1.3.7

### OS/Browsers version
osx/chrome

### Vue version
2.3.4

### Reproduction Link
[http://jsfiddle.net/8gtzodwb/](http://jsfiddle.net/8gtzodwb/)

### Steps to reproduce
just look into the link: http://jsfiddle.net/8gtzodwb/
when search keyword "江苏" in Cascader , it returns nothing

### What is Expected?
return '江苏'

### What is actually happening?
return nothing

**Comment by Dreamacro** [comment]
在没有 `change-on-select` 的情况下，`filterable` 不能响应带有子元素的项，在这里就是不需要 `cities` 这个 key，或者你可以加上 `change-on-select` 响应任意一级菜单的选项。

http://jsfiddle.net/8gtzodwb/2/
