### ISSUE TITLE
how to transmit parameter when using the function of onClose notification

### ISSUE THREAD

**Issue by Luffyying** [ElemeFE/element#5758]
the hint is following:
[Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context. at Function.remoteFunction (<anonymous>:2:14)

**Comment by fergardi** [comment]
@Luffyying in case you are still wondering, the trick is using closures or binding functions, like this:

```js
Notification.warning({
  title: 'title',
  message: 'message',
  duration: 0,
  onClose: this.foo.bind(null, 'text')
})
```
