### ISSUE TITLE
根据变化的vuex数据，循环生成Menu-Item，第一次点击个别Menu-Item时，个别Menu-Item未出现选中状态，activedIndex=““

### ISSUE THREAD

**Issue by hwyw** [ElemeFE/element#5761]
点击导航栏，根据导航不同生成不同数据存入vuex,然后侧边栏读取vuex数据，然后循环生成Menu-Item，

切换导航时候出现bug（注：全程没有报错）：
如果el-menu 加router属性或者el-menu 不加router属性而是在el-menu外层加router-link 都会出现个别路由需要点击两次才能出现选中状态，
监视el-menu状态，单击第一次activedIndex=““，单击第二次出现选中状态activedIndex=“xxx“

如果el-menu 不加router属性、el-menu外层页不加router-link，此时选中状态正常，但是路由组建不会切换，不会加载,尝试自定义事件也不行

如果el-menu 不加router属性 在el-menu内层加router-link，可以实现选中状态正常，切换组建正常，但是此组建失去意义了

**Comment by guohuihot** [comment]
问题解决了吗，我也有类似的问题

**Comment by CoderONER** [comment]
希望可以完善一下文档～～   很多人都遇到这个问题

**Comment by guohuihot** [comment]
需要注意的是`activedIndex="1"`那个`1`一定要是字符串，如果是数字我去可以这样写`activedIndex="1 + ''"`这是一个小坑

**Comment by phping1** [comment]
遇到同样的问题

**Comment by taishan802** [comment]
我遇到类似的问题：<el-menu-item v-for="secItem in item.secondNavList" :key="secItem.component" :index="secItem.component" v-show="secItem.hasAuth">{{secItem.name}} </el-menu-item>对这个二级导航条，componet都是string,一直报错vue.esm.js?65d7:576 [Vue warn]: Duplicate keys detected: 'index'. This may cause an update error.，求大神帮忙看看

**Comment by skjgithub950423** [comment]
出现了同样的问题 至今没有解决
