### ISSUE TITLE
[Bug, Report], checked, value, didn't, when, remove, change, a, checked, option,, in, checkbox, group, component

### ISSUE THREAD

**Issue by simphp** [ElemeFE/element#5762]
### Element UI version
1.3.7

### OS/Browsers version
macOS 10.12.5, Chrome 版本 61.0.3141.7（正式版本）dev （64 位）

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/esinger/2wat1wbu/1/](https://jsfiddle.net/esinger/2wat1wbu/1/)

### Steps to reproduce
1. 创建一个checkbox组件
2. 选中一个选项A
3. 动态移除这个选项A

### What is Expected?
v-model绑定的选中的值更新，去除已经移除的选项对应的值

### What is actually happening?
v-model绑定的选中的值没有变化

**Comment by baiyaaaaa** [comment]
U should update the binding by yourself when u remove a checobox, we haven't watch the model. It's not a bug
