### ISSUE TITLE
[Bug Report] Selector 切换multiple 时有bug

### ISSUE THREAD

**Issue by ivan403704409** [ElemeFE/element#5763]
### Element UI version
1.3.7

### OS/Browsers version
mac os/Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/jzvgnk0m/](https://jsfiddle.net/jzvgnk0m/)

### Steps to reproduce
在连接处直接切换单选，多选即可复现
1.multiple 为false，且selector的value不为空
2.切换mutiple为true, 并给selector重新赋值

### What is Expected?
正常显示选项

### What is actually happening?
> 显示有bug
![](https://github.com/ivan403704409/bug-img/blob/master/element-ui-table-bug2.png?raw=true)

**Comment by Leopoldthecoder** [comment]
`multiple` is not responsive, please use `v-if` instead: https://jsfiddle.net/jzvgnk0m/1/
