### ISSUE TITLE
[Bug Report], when two groups of Radio or two groups of Switch are together, the second group will not be able to render the normal render. Requires the first set of triggers

### ISSUE THREAD

**Issue by leer561** [ElemeFE/element#5764]
### Element UI version
1.3.7

### OS/Browsers version
chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/6fmwah8n/](https://jsfiddle.net/6fmwah8n/)

### Steps to reproduce
当第一排选中是，第二排选择后，无法正常渲染

### What is Expected?
完成正常渲染

### What is actually happening?
当第一排选中是，第二排选择后，无法正常渲染

**Comment by Leopoldthecoder** [comment]
`radio1` is not registered: https://jsfiddle.net/6fmwah8n/1/

**Comment by leer561** [comment]
thanks
