### ISSUE TITLE
[Bug Report] i can not select an option of the select

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#5768]
### Element UI version
1.3.7

### OS/Browsers version
all

### Vue version
2.3.4

### Reproduction Link
[here](https://jsfiddle.net/5rwz2yzv/)

### Steps to reproduce
1. try to select an option
2. no one can be selected
3. modify line 21 to: `id:0`
4. try again
5. options can be selected now

### What is Expected?
give me an error in the console,tell me what is missing in the code
and why the component can not response to the user action?

**Comment by wacky6** [comment]
You have found out what's missing:
```
modify line 21 to: id:0
```

**Comment by Leopoldthecoder** [comment]
Please read this: https://vuejs.org/v2/guide/reactivity.html

**Comment by zzzgit** [comment]
is there a way to give more info in the console in this situation?
