### ISSUE TITLE
[Feature Request] Color picker Auto Change

### ISSUE THREAD

**Issue by omarsedki** [ElemeFE/element#5769]
I am opening an issue for :Element UI
 Issue Type: Feature Request
 Issue Title: Color picker Auto Change
Existing component?Yes
 Component Name: Color picker

 Issue Description:
I need the color change without selecting ok in the color picker and keep open to reselect another color. Because people want to see the effect of the colors. 
Here icon Matrix generator  (  http://iconmatrix.livegap.com ) i created   made by elementui . Everything is perfect only the color picker not working as i want.
What i want is like i made with jquery color picker.
Test from here :  
 http://charts.livegap.com/app.php

**Comment by wacky6** [comment]
So you want to get the color value in real-time?

**Comment by omarsedki** [comment]
Yes.

**Comment by wacky6** [comment]
If you don't want to wait for formal implementation of this feature, watch color picker's `displayedColor`. https://jsfiddle.net/sy3pru4v/ (subject to changes in future releases)

@Leopoldthecoder What's your opinion on this feature? Add an event to emit `displayedColor`, or add an option to toggle input event's emission behavior?

**Comment by omarsedki** [comment]
Thanks.  i think  watch displayedColor will solve the issue. But if there are many pick color .how to know the active one to change .

**Comment by omarsedki** [comment]
Also . If you will add as feature . Add option to auto hide when user click outside the picker panel without to click ok or cancel. Will make color picker more usefull.
Thanks

**Comment by Leopoldthecoder** [comment]
@wacky6 I'm inclined to emitting an event. #5775

@omarsedki You can assign different `ref`s to them: https://jsfiddle.net/sy3pru4v/1/
> Add option to auto hide when user click outside the picker panel without to click ok or cancel

That's already how ColorPicker works now.
