### ISSUE TITLE
The [Bug Report] el-table component attempts to perform screen adaptation when the width is stretched (the width cannot be reduced by self adaption)

### ISSUE THREAD

**Issue by BigMeat233** [ElemeFE/element#5779]
### Element UI version
1.3.7

### OS/Browsers version
MacOS 10.12.5/Chrome 59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/c52dboet/5/](https://jsfiddle.net/c52dboet/5/)

### Steps to reproduce
1. 点击'变'按钮，左侧div宽度缩减导致el-table宽度拉伸。
2. 再次点击'变'按钮，观察左侧div及el-table的宽度变化。

### What is Expected?
再次点击'变'按钮后，左侧div宽度增加，el-table宽度缩减。

### What is actually happening?
再次点击‘变’按钮时无变化，在chrome浏览器中实际运行项目时表现为左侧div将右侧el-table挤出容器

**Comment by liril-net** [comment]
Simliar to #7149
