### ISSUE TITLE
[Bug Report] loading status of a button got werid when using 'v-loading' instead of ':loading'

### ISSUE THREAD

**Issue by Mxsion** [ElemeFE/element#5781]
### Element UI version
1.3.7

### OS/Browsers version
59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
https://jsfiddle.net/3t119pqe/

### Steps to reproduce
It will become big when using a 'v-loading' in a button instead of ':loading'. yeah ! It`s not a
big deal.

### What is Expected?
button`s loading style got nomal style

### What is actually happening?
button`s loading style get weird

**Comment by Mxsion** [comment]
![image](https://user-images.githubusercontent.com/17025045/28013173-c460a704-659a-11e7-809e-9134de51556f.png)

**Comment by Leopoldthecoder** [comment]
The size of the spinner is constant. So please avoid using `v-loding` on small components.

**Comment by xianshenglu** [comment]
why not supporting size param? or support size auto adjust according to the component's size? @Leopoldthecoder
