### ISSUE TITLE
[Bug Report] icon component initial  value is not right when  allowHalf=true

### ISSUE THREAD

**Issue by savoygu** [ElemeFE/element#5782]
### Element UI version
1.3.7

### OS/Browsers version
win 10 / chrome 60

### Vue version
2.3.4

### Reproduction Link
[http://jsbin.com/xoyeseq/edit?html,css,js,output](http://jsbin.com/xoyeseq/edit?html,css,js,output)

### Steps to reproduce
when the this.value = 3.7 ( this.value >= 3.5 && this.value < 4 )，the component show just three smile face

### What is Expected?
should be 3.5 face (^_^)

### What is actually happening?
just 3 face

**Comment by Leopoldthecoder** [comment]
Fixed in #5785
