### ISSUE TITLE
[Bug Report] Select Component doesn't highlight the main input box if you use the component via arrow

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#5783]
### Element UI version
1.3.7

### OS/Browsers version
Current Chrome OS

### Vue version
2.3.4

### Reproduction Link
https://jsfiddle.net/80e88f6u/

### Steps to reproduce
If you select the dropdown using the arrow, the main input box doesn't highlight (it doesn't get a blue border)... where-as if you use the dropdown anywhere else, the input box will highlight.

![Alt Text](http://i.makeagif.com/media/7-10-2017/W7AWH3.gif)

### What is Expected?
The entire select box should highlight (blue border), regardless of whether you use the arrow or not to drop-down the select options.

### What is actually happening?
The select box will not highlight in a blue border if you use the arrow to drop-down.

**Comment by Leopoldthecoder** [comment]
Fixed in #6151
