### ISSUE TITLE
[Bug Report] In the icon component, when set to max = 10, the text is displayed incorrectly

### ISSUE THREAD

**Issue by savoygu** [ElemeFE/element#5784]
### Element UI version
1.3.7

### OS/Browsers version
win 10 / chrome 60

### Vue version
2.3.4

### Reproduction Link
[http://jsbin.com/xoyeseq/edit?html,css,js,output](http://jsbin.com/xoyeseq/edit?html,css,js,output)

### Steps to reproduce
Move the mouse over the smiley icon and watch the changes to the text on the right

### What is Expected?
the text on the right should be ordinary

### What is actually happening?
the result is satisfied

**Comment by Leopoldthecoder** [comment]
```JS
data () {
  return {
    value: 5
  }
}
```

`value` is `5`, so the displayed text is the 4th element in the text array, which is `一般`. I don't see anything wrong here.

**Comment by savoygu** [comment]
i mean, when i set ` :max=10`, i have to set `:texts` to 10 levels( the texts array length must be 10 ), just like:

```
:texts=['level1', 'level1', 'level2', 'level2',  'level3', 'level3',  'level4', 'level4',  'level5', 'level5']
``` 

if set `:max=15`... , the texts's length must be consistent with max value(although these are not common). if i  can set `:texts=['level1', 'level2',  'level3',  'level4', 'level5' ]`, this will be better, I provided a comparison example: 

http://jsbin.com/xoyeseq/edit?html,css,js,output
