### ISSUE TITLE
[Bug Report] checkbox单独使用时，无法在勾选的时候触发validate的验证方法

### ISSUE THREAD

**Issue by lainlee** [ElemeFE/element#5787]
### Element UI version
1.3.7

### OS/Browsers version
window 10 / chrome 59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/z65dzy9k/1/](https://jsfiddle.net/z65dzy9k/1/)

### Steps to reproduce
勾选 【接受协议】 复选框，应该进行验证，实际并没有

### What is Expected?
如果没有勾选（值为false），应该提示错误，否则，隐藏错误

### What is actually happening?
不论是否勾选，都没有提示错误，并且实际上没有走到validator验证器里，可能是触发change事件但是没有调用validator，

用@change绑定方法的话却可以看到变化

---
看了下代码，发现只有是group的checkbox的时候才进行了字段验证，是否应该在单独使用checkbox的时候也加上验证呢

**Comment by baiyaaaaa** [comment]
从设计上来看我们没有给单独的 checkbox 或者 radio 验证的理由，既然是单独使用还要勾上，为何不强制就默认勾上呢? 所以我们认为单独的 checkbox 或者 radio 是没必要做验证的。

**Comment by horans** [comment]
try to use `true` as default value: 

    rule: {
      term: [{ pattern: /^(true)$/, message: 'agree to continue', trigger: 'blur' }]
    }
