### ISSUE TITLE
[Feature Request] Improved data table features

### ISSUE THREAD

**Issue by feribg** [ElemeFE/element#5788]
### Existing Component
Yes

### Component Name
table

### Description
I'm trying to find a way to hide/show data table columns dynamically and insert new columns programatically, but I cant seem to find that anywhere in the documentation so I was wondering if those features are available or if there was a fairly easy workaround for them. I guess just hacking the css display properties can work for hide/show columns, but adding new columns and binding the data seems more troublesome. Thanks!

**Comment by Leopoldthecoder** [comment]
Try `v-if`: https://jsfiddle.net/mqvh8owx/

**Comment by lxzxl** [comment]
@Leopoldthecoder Thanks for your suggestion, but the `v-if` is not working well in my case. I modified you demo a little and please click the toggle button for more than twice, you'll see the problem. https://jsfiddle.net/lxz222/mqvh8owx/1/
