### ISSUE TITLE
[建议]Upload组件增加 autoUpload 属性

### ISSUE THREAD

**Issue by amin168** [ElemeFE/element#579]
建议添加一个autoUpload的配置，是否自动upload，或者添加一个方法触发upload

**Comment by erguotou520** [comment]
我现在都是`before-upload`里返回`false`

**Comment by xierenyuan** [comment]
我以是

**Comment by reverland** [comment]
支持啊

https://css-tricks.com/examples/DragAndDropFileUploading/

**Comment by baiyaaaaa** [comment]
will be released in 1.2, #2827
