### ISSUE TITLE
[Feature Request] recommends adding button, the input box, and other slot that need icon components

### ISSUE THREAD

**Issue by hezhongfeng** [ElemeFE/element#5793]
### Existing Component
Yes

### Component Name
el-button、el-input等

### Description
目前只有Steps 步骤条自定义图标可以通过 slot 方式写入
由于引入第三方图标库很不方便，例如`Material Icons`并不是完全使用class确定图标，所以如果可以使用slot分发的话，使用什么图标都是很方便的

**Comment by gnhuy91** [comment]
Agreed, I also need icon slot for custom svg icons.

**Comment by AshwinTayson** [comment]
Any updates on this? Need slot to change icon for dropdowns too.

**Comment by wood-push-melon** [comment]
any update on this? I think this is very useful.

**Comment by Leopoldthecoder** [comment]
Version 2.0 supports `slot="icon"`.

**Comment by jpokrzyk** [comment]
@Leopoldthecoder You sure about the icon slot? I don't see it anywhere in the button code, only a default slot: https://github.com/ElemeFE/element/blob/dev/packages/button/src/button.vue#L21

I would also like an icon slot for a button icon. I'm also fine doing the PR for this unless it's already in some branch that I haven't noticed. Should this get re-opened or should it get tracked a different way?

**Comment by tylertrotter** [comment]
I like where the OP is going with this, but I would like to see slots available wherever icons are used. For example, I am trying to use inline SVGs so each icon is its own component. The way the prefix and suffix slots work in the input component is great, but, for example, I can't insert my icons into the date picker.

Is this on the road map, or would you consider a pull request to provide this functionality?
