### ISSUE TITLE
页面包含多个upload组件时，怎么去拿success回调的数据与当前操作的元素进行关联

### ISSUE THREAD

**Issue by alexzaolin** [ElemeFE/element#5794]
一般来说，我们要进行关联的话，可能会这样写   @click="someFun(data)";
但是在upload的success的回调里面，如果我加入其他参数，那么本该有的filelist就没有了。这个问题该如何解决呢

**Comment by ziqink** [comment]
@alexzaolin 我也遇到这个问题。 请问你有办法解决吗

**Comment by alexzaolin** [comment]
@ziqink 恩，二次封装了一下，我简单的写了一下，可以解决这个问题http://www.cnblogs.com/AlexBlogs/p/7150532.html

**Comment by Zeus-Iqd** [comment]
我也是这个问题，谢谢了老铁

**Comment by galan99** [comment]
我也遇到这个问题了，怎么解决
