### ISSUE TITLE
After the [Bug Report] Upload component disabled property is set to true, the deleted button is visible and operable

### ISSUE THREAD

**Issue by TonyLuo** [ElemeFE/element#5799]
### Element UI version
1.3.7

### OS/Browsers version
MacOS

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
N/A

### What is Expected?
N/A

### What is actually happening?
N/A

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by showonne** [comment]
遇到了同样的问题，重现链接： https://jsfiddle.net/pj71jkyw/372/

**Comment by Leopoldthecoder** [comment]
@TonyLuo @showonne Fixed in #5841
