### ISSUE TITLE
表格有错位吧老铁

### ISSUE THREAD

**Issue by a346721573** [ElemeFE/element#5803]
如图，莫名出现横向纵向滚动条，而且一拖动横向就错位了，是我配置有问题吗
![image](https://user-images.githubusercontent.com/14291277/28058689-f614e896-6653-11e7-9e36-eccc5c0ccfc1.png)

**Comment by cuihj** [comment]
@a346721573  我出现和你一样的情况，你解决了吗？我发现列少没事

**Comment by a346721573** [comment]
@cuihj 还没有哦
