### ISSUE TITLE
[Bug Report] input number validation does not work correctly

### ISSUE THREAD

**Issue by reclay** [ElemeFE/element#5805]
### Element UI version
1.3.7

### OS/Browsers version
chrome 59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/sudwbp8x/](https://jsfiddle.net/sudwbp8x/)

### Steps to reproduce
在数字类型验证的输入框输入以数字开头的字符串。
如：9fasjlkfaskf

### What is Expected?
应被验证为字符串，报类型错误。

### What is actually happening?
被验证为数字，未报类型错误。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/sudwbp8x/1/ 因为 Vue 在这种情况下会自动处理你的输入，进行验证的已经是被处理后的值了。
和 Element 无关。
