### ISSUE TITLE
[Bug Report] table component style bug

### ISSUE THREAD

**Issue by lzmhlzsd** [ElemeFE/element#5806]
### Element UI version
1.3.7

### OS/Browsers version
chrome,safari

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/360/](https://jsfiddle.net/pj71jkyw/360/)

### Steps to reproduce
在safari浏览器发现table的head部分，出现表格不对齐的问题。看了一下，在safari里面样式 
th.gutter{width:0px}  
无效，可能是已经定义了背景。所以还是保留了默认15px的宽度，导致样式布局不对齐。目前在不改源码的情况下我写了个 
 .gutter[style="width: 0px;"]{
    background: none;
}

### What is Expected?
表格标题部分能对齐

### What is actually happening?
表格标题部分不对齐

**Comment by imkiven** [comment]
遇到同样的问题

**Comment by Leopoldthecoder** [comment]
Duplicate of #4928
