### ISSUE TITLE
[Bug, Report], element, select, issue

### ISSUE THREAD

**Issue by iamMarkchu** [ElemeFE/element#5809]
### Element UI version
1.3.7

### OS/Browsers version
windows 7 / chrome 55.0.2883.87

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/chukui/sp08h6aw/6/](https://jsfiddle.net/chukui/sp08h6aw/6/)

### Steps to reproduce
1. 点击编辑
2. 弹出框里面的select选择器不能选择

### What is Expected?
可以选择

### What is actually happening?
不能选择

**Comment by Leopoldthecoder** [comment]
Change line 39 from 
```JS
this.cronForm.AlertUsers = this.selectData.map(item => {
  return item
})
```
to
```JS
this.$set(this.cronForm, 'AlertUsers', this.selectData.map(item => {
  return item
}))
```

Please read https://vuejs.org/v2/guide/reactivity.html

**Comment by iamMarkchu** [comment]
ok, thx a lot !
