### ISSUE TITLE
The [Bug Report] <el-autocomplete> component could not use Sogou input method in Chinese IE 11

### ISSUE THREAD

**Issue by wisewrong** [ElemeFE/element#5813]
### Element UI version
1.3.7

### OS/Browsers version
Win7 / IE11

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/368/](https://jsfiddle.net/pj71jkyw/368/)

### Steps to reproduce
1. 使用 IE11；
2. 选择搜狗输入法；
3. 在 <el-autocomplete> 中输入中文。

如果上面的项目链接无法在 IE11 中打开，可以在 IE11 中查看官方文档的示例 “带输入建议的输入框”
http://element.eleme.io/#/zh-CN/component/input

### What is Expected?
在 IE11 中能正常使用 <el-autocomplete> 组件

### What is actually happening?
IE11 中 <el-autocomplete> 组件不支持搜狗输入的中文输入

**Comment by yamateH-ch** [comment]
遇到同样的问题，+1

**Comment by An0nymous0** [comment]
+1

**Comment by GuoYanfang** [comment]
+1

**Comment by BusyHe** [comment]
+1

**Comment by NoCat** [comment]
chrome 55 也出现同样的情况

**Comment by rennai** [comment]
+1

**Comment by buhanqiu** [comment]
遇到一样的问题,求解
