### ISSUE TITLE
The [Feature Request] table component adds display / hidden column functionality

### ISSUE THREAD

**Issue by ymsh** [ElemeFE/element#5814]
### Existing Component
Yes

### Component Name
el-table

### Description
表格列数太多时，希望在el-table-column增加是否显示列属性。
由此可以默认显示某些列，再由用户根据自己的需要通过下拉框勾需要显示的列。
可参考bootstrap-table

**Comment by Leopoldthecoder** [comment]
Try `v-if`: https://jsfiddle.net/mqvh8owx/
