### ISSUE TITLE
[Feature, Request] Input with icon support hidden when the input is not focusing

### ISSUE THREAD

**Issue by laoxubuer** [ElemeFE/element#5821]
### Existing Component
是

### Component Name
Input

### Description
the icon in el-input component now is always visible,but I want to hide the icon at first, and only if the input is focusing, show the icon.

for instance, I add a delete icon like el-icon-circle-cross to the input, when I click this icon, the value will be clear.But the requirement is showing icon only if focusing.

![tim 20170712141530](https://user-images.githubusercontent.com/7135991/28104320-03f2177c-670d-11e7-9bca-4dfcda428cca.png)

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/7aLtuq4b/

**Comment by laoxubuer** [comment]
@Leopoldthecoder Thank u for your reply.

I viewed your jsFiddle, there is a problem that when i click the icon, the blur event is triggered so that I can't trigger 'on-icon-click' event, so I add a 300ms duration to CSS transition,It works.
 
This is my jsFiddle [https://jsfiddle.net/cheerxl/3c7v18ry/11/](https://jsfiddle.net/cheerxl/3c7v18ry/11/)

Originally, I created a signle component named clearInput, and use it in the el-form-item, add a ref to it, the hide & show methods is all managed in itself, including the 300ms delay (actually I use setTimeOut), 
so that I don't need write the logic again and again, just like the picture below:

![ddddd](https://user-images.githubusercontent.com/7135991/28194385-82836d92-6876-11e7-8d5a-5c8320ec873d.png)


But the two manners above are not elegent & neat， I think a add a prop to to determine fixed or visible&clickable only if focusing it better.

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/28195232-b433b130-687b-11e7-8c8a-6f01f0435891.gif)

It seems you don't have to add that 300ms transition. As you can see in the gif, I commented `transition: all 300ms` and the `on-icon-click` still works. Actually, the icon itself already has a transition of 300ms: https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/input.css#L50

**Comment by laoxubuer** [comment]
Thank u, I see it :-D
