### ISSUE TITLE
[Bug Report] upload 组件在 :auto-upload="false"的情况下 同一文件选择后删除再重新选择不生效（不能重复选择同一文件）

### ISSUE THREAD

**Issue by LianyForWeb** [ElemeFE/element#5822]
### Element UI version
1.3.7

### OS/Browsers version
Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pLu4j6qt/5/](https://jsfiddle.net/pLu4j6qt/5/)

### Steps to reproduce
1 选择一文件 
2 删除该文件
3 重新选择该文件

### What is Expected?
能被选择

### What is actually happening?
第二次选择不生效

**Comment by Leopoldthecoder** [comment]
Fixed in #5706.

**Comment by liwenda122** [comment]
fixed个毛， IE10下还是不行。自测不严谨呀。
chrome ,FF, IE11 (作者的改法)
this.$refs.input.value =null
IE10及以下：
1.input type=file 外层套个form
2.this.$refs.inputFileForm.reset() 
此方法在chrome 下也适用，代价就是要多套个form
