### ISSUE TITLE
[Bug Report] How Could I bind data to Radio in  Tree  Component's RenderContent Function

### ISSUE THREAD

**Issue by MicyToy** [ElemeFE/element#5824]
### Element UI version
1.3.7

### OS/Browsers version
Window all / Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/2jskyuh7/](https://jsfiddle.net/2jskyuh7/)

### Steps to reproduce
I want to put a Radio in Tree Componet, but I don not know how to bind data to Radio.
And `label` displayed after slots.default, when I use
```
scopedSlots:{
       default:props => h('span',  "Finished")
}
```

### What is Expected?
I want to put a Radio in Tree Componet, but I don not know how to bind data to Radio

### What is actually happening?
I want to put a Radio in Tree Componet, but I don not know how to bind data to Radio

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by MicyToy** [comment]
@Leopoldthecoder 但是我上面的代码为什么不正常？是我写法问题，还是Radio有问题
