### ISSUE TITLE
[Bug Report] DatePicker shows German "Jahr" after the year which is unneeded

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#5825]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 17.04, Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/hLjebshf/](https://jsfiddle.net/hLjebshf/)

### Steps to reproduce
1. Set the locale to German
2. Add a DatePicker element
3. Click on the DatePicker element to pick a date

### What is Expected?
As in English, only the year number and the month should be visible

### What is actually happening?
Not only the year is visible, but the German translation of the word year ("Jahr") is appended to the years

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/src/locale/lang/de.js#L22

Please try removing this line locally and see if everything is fine. If it helps, you can submit a PR.
