### ISSUE TITLE
[Bug Report] Memory leak (detached DOM tree) when add click event to el-button

### ISSUE THREAD

**Issue by xingchch** [ElemeFE/element#5826]
### Element UI version
1.3.7

### OS/Browsers version
win7 / chrome58

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/ska4oboj/35/](https://jsfiddle.net/ska4oboj/35/)

### Steps to reproduce
1. click world
2. take a memory snapshots in devtools
3.click hello
4. take a memory snapshots in devtools
5.compare snapshots generated from 4 and 2. and found Detached Dom(el-button)

### What is Expected?
I had patched following patch into my project, https://github.com/bartsidee/vue/commit/30c986c2266fca92c5aa635189fd09be87de02d5
and verified that  with normal div it do not have this issue,  momory released totally after switch router.

### What is actually happening?
Detached element DOM cause  memory leak

**Comment by xingchch** [comment]
Does anyone works on this issue? verified on vue 2.4.1 , stll exist.

**Comment by skortabeast** [comment]
this problem resolve https://vuejs.org/v2/cookbook/avoiding-memory-leaks.html but how create element object
