### ISSUE TITLE
[Bug Report] Cascader sets parent value if mouse moved during slide-up transition and expand-trigger hover

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#5827]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 17.04, Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/vjyxhxgy/](https://jsfiddle.net/vjyxhxgy/)

### Steps to reproduce
1. Create a Cascader element with children that does not allow selecting parents (default) and that expands children on hover instead of click (`expand-trigger="hover"`).
2. Select a child element and during the slide-up transition after clicking a child, move the mouse to the left over a parent element

### What is Expected?
The Cascader should set the value of the item clicked

### What is actually happening?
The Cascader sets the value of the last item hovered

**Comment by smares** [comment]
After playing around more with the element, the bug only occurs if `expand-trigger` is set to `hover`. It does not happen with it's set to `click`.

**Comment by xjkms** [comment]
I have to say that got the same bug.

**Comment by Dreamacro** [comment]
Fixed in #6189
