### ISSUE TITLE
[Bug Report] messageBox encountered strange problems in the new version of chrome

### ISSUE THREAD

**Issue by asmodai1985** [ElemeFE/element#5832]
### Element UI version
1.3.7

### OS/Browsers version
chrome 61.0.3153.0（正式版本）dev （64 位）

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
仅在chrome中发现此问题，不确定其它版本是否存在该问题(firefox无此问题)。
独立测试时正常，只有在未知情况下才会发生该情况，所以不能提供jsfiddle。但发现官网的演示页面也存在相同问题，所以将此问题提交上来。

重现步骤：

1、打开 messageBox文档页 [http://element.eleme.io/#/zh-CN/component/message-box](url)

2、下拉到自定义栏目，点击 “点击打开 Message Box”

### What is Expected?
正常出现提示框

### What is actually happening?
出现如下图所示问题：出现信息框，但在疯狂闪烁两次后只能看到按钮，文字被隐藏。

![qq 20170713142514](https://user-images.githubusercontent.com/6767187/28153283-35258f34-67d7-11e7-8048-f56845d3cd26.jpg)

个人的解决方案：
虽然未能发现原因，但提供一个本人使用的补丁方案

``` 
.el-message-box{
  overflow: unset;
}
 ```

**Comment by Leopoldthecoder** [comment]
未遇到此问题，也没有其他用户报告类似情况，请检查是否由浏览器插件导致。
