### ISSUE TITLE
[Bug Report] The form control appears flash screen in the 360 browser

### ISSUE THREAD

**Issue by liangjw** [ElemeFE/element#5833]
### Element UI version
1.3.1

### OS/Browsers version
360

### Vue version
2.1.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
重现链接是假的，我输入我的项目链接一直提示错误。使用360浏览器直接打开http://element.eleme.io/#/zh-CN/component/form即可重现！

### What is Expected?
无闪屏

### What is actually happening?
闪屏

**Comment by baiyaaaaa** [comment]
360 浏览器有 bug
