### ISSUE TITLE
[Bug Report] the data was duplicated when I add an empty row to the head of a table where I used el-input in

### ISSUE THREAD

**Issue by zipoopiz** [ElemeFE/element#5835]
### Element UI version
1.3.7

### OS/Browsers version
windows 7/chrome 58

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/5k3z8Lkq/1/](https://jsfiddle.net/5k3z8Lkq/1/)

### Steps to reproduce
Type something in the empty el-input component of the first row of the table and you will see what you typed is duplicated in the new empty row。
（But if I listen to the native change event instead of change event of el-input，everything is ok. Look at this link: [https://jsfiddle.net/5k3z8Lkq/2/](https://jsfiddle.net/5k3z8Lkq/2/)) 

### What is Expected?
what you typed is not duplicated in the new empty row

### What is actually happening?
what you typed is duplicated in the new empty row

**Comment by Leopoldthecoder** [comment]
You need to add a `key`: https://jsfiddle.net/5k3z8Lkq/3/
