### ISSUE TITLE
After the [Bug Report] el-dialog pops up, press tab to switch the focus to the outside of the pop-up layer

### ISSUE THREAD

**Issue by Comup-X** [ElemeFE/element#5838]
### Element UI version
1.3.7

### OS/Browsers version
Win10/Chrome59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/jaoochnL/1/](https://jsfiddle.net/jaoochnL/1/)

### Steps to reproduce
1.点击 打开嵌套表格的 Dialog
2.多按几次Tab切换焦点
3.焦点会切换到 Dialog外面去

### What is Expected?
焦点仅在Dialog内切换

### What is actually happening?
焦点会在全网页切换

**Comment by Comup-X** [comment]
@element-bot 已经改了

**Comment by Comup-X** [comment]
没人处理啊？

**Comment by Leopoldthecoder** [comment]
参考 https://github.com/ElemeFE/element/pull/5336，目前没有好的方式兼顾两边，暂时只能选 lesser of two evils 了
