### ISSUE TITLE
bootstrap3 modal 调用Date Picker 日期选择器 会被遮挡

### ISSUE THREAD

**Issue by missy0u** [ElemeFE/element#584]
查看了一下 datepicker z-index:1000开始递增，而bootstrap3 modal的z-index:1050

![ele](https://cloud.githubusercontent.com/assets/3926664/19616430/55109940-9845-11e6-94ed-22075d9425c3.png)

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/ElemeFE/element/pull/664/files#diff-cb3efcfdf157956fce0480ea920e5e5cR3
