### ISSUE TITLE
[Bug Report] cannot update the display of the form of a certain item in error under special circumstances

### ISSUE THREAD

**Issue by xiangnanscu** [ElemeFE/element#5844]
### Element UI version
1.3.7

### OS/Browsers version
windows 10/ chrome 54

### Vue version
2.4.1

### Reproduction Link
[https://github.com/xiangnanscu/core-test/tree/form](https://github.com/xiangnanscu/core-test/tree/form)

### Steps to reproduce
依次点击: 
1.提交
2.获取验证码(此时错误会更新)
3.提交
4.获取验证码 (此时错误不会更新)

### What is Expected?
第二次点击获取验证码的时候应该显示错误"请先输手机号"

### What is actually happening?
没有这样显示

**Comment by xiangnanscu** [comment]
为节约时间, 这里贴上主要代码
```
<template>
  <el-form :model="formData" :rules="rules" ref="registerForm" label-position="right" label-width="6em">
    <el-alert v-if="errors.__all" :title="errors.__all" type="error" :closable="false"></el-alert>
    <el-form-item label="手机号" prop="phone" :error="errors.phone">
      <el-input v-model="formData.phone" auto-complete="off" placeholder="请输入11位手机号"></el-input>
    </el-form-item>
    <el-form-item label="验证码" prop="code" :error="errors.code">
      <el-row>
        <el-col :span="12">
          <el-input v-model="formData.code" auto-complete="off" width="50px"></el-input>
        </el-col>
        <el-col :span="12">
          <el-button type="primary" @click="sendCode" style="margin-left:8px">
            获取验证码
          </el-button>
        </el-col>
      </el-row>
      <div v-if="codeValid && !errors.code" class="el-form-item__error" style="color:green">验证码已发送, 请注意查看手机</div>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="submitForm">
        提交
      </el-button>
    </el-form-item>
  </el-form>
</template>

<script>

export default {
  computed: {

  },
  data() {
    return {
      codeValid: false,
      errors: {
        phone: '',
        code: '',
      },
      formData: {
        phone: '',
        code: '',
      },
      rules: {
        phone: [
          { required: true, message: '必须提供11位手机号',  },
          { pattern: /^\d{11}$/,  message: '请输入11位数字手机号', trigger: 'blur' },
        ],
        code: [
          { required: true, message: '必须提供验证码', trigger: 'blur' },
          { pattern: /^\d{6}$/,  message: '请输入6位数字验证码', trigger: 'blur' },
        ],
      }
    };
  },
  methods: {
    submitForm() {
      this.$refs.registerForm.validate((valid) => {
        if (valid) {
            setTimeout(() => {
                this.errors = {phone: '无效手机号'}
            }, 1000)
        } else {
          return false;
        }
      });
    },
    sendCode() {
      var phone = this.formData.phone
      if (!/^\d{11}$/.test(phone)) {
        this.errors.code = '请先输手机号'
        return
      }
      setTimeout(()=>{
        this.errors = {code: '无效验证码'}
      }, 1000)
    },
  },
}
</script>

```

**Comment by Leopoldthecoder** [comment]
不建议 `rules` 和 `error` 混在一起使用。如果一定要用的话，可以这样绕一下：https://jsfiddle.net/aew4kxdz/ （40 行至 43 行）

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 其实我也不想混用, 但是似乎没有办法可以直接操作form内建的errors状态(就我所知,似乎只能通过validate方法产生, 通过提交合法的输入消除)

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 请教一下, 在表单提交之后, 后端可能还会返回一个出错信息对象, 比如`{phone: '又一个出错', code: '再一个错误'}`, 那么, 用这个出错对象来触发form的错误渲染的正确姿势是什么呢? element form 支持这样做吗?

**Comment by Leopoldthecoder** [comment]
还是通过给 `this.errors` 赋值来实现。事实上 `error` 属性就是为后端返回的出错信息设计的，在你的例子里，「请先输手机号」这个错误其实可以用自定义校验规则来产生，而不是使用 `error` 属性。

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 但是直接赋值`this.errors`的话有这个bug: 在你输入了前端合法的数据后, 比如phone:13508198877, code:111111, 然后首次点击"提交"会如期返回`无效手机号`, 紧接着再点击"提交", phone错误信息就消失了. 但实际上期望的是后端再次返回一个出错对象, element应该渲染相同的错误.

```
    submitForm() {
      this.$refs.registerForm.validate((valid) => {
        if (valid) {
          setTimeout(() => {
            this.errors = {phone: '无效手机号'}
          }, 1000)
        } else {
          return false;
        }
      });
    },
```

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 刚测试了下, 如果清空rules就完全正常了. 这样的话是不是意味着如果我想渲染来自后端的错误, 就不能直接同时使用rules了? 如果一定要用的话, 就需要按照你之前的那个绕过技巧来?

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 我又进行了另外一个测试, 在混用的情况下, 如果某个字段比如phone后端返回的错误信息和上次不一样, 那么element会渲染出来. 如果和上次一样, 那么就会有之前提到的bug

**Comment by Leopoldthecoder** [comment]
不是 bug，因为内部是 watch 了 `error`，所以它发生变化才会渲染出来。
```JS
   submitForm() {
      this.$refs.registerForm.validate((valid) => {
        if (valid) {
          this.errors = {phone: ''}
          setTimeout(() => {
            this.errors = {phone: '无效手机号'}
          }, 1000)
        } else {
          return false;
        }
      });
    },
```
所以你前端验证通过之后把 `this.errors.phone` 置空，然后再根据后端的返回重新赋值就可以了。

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 好的. 感谢指点.  建议, 当error没有发生变化的时候, 不要清空之前的错误显示就更好了.

**Comment by Leopoldthecoder** [comment]
错误被清空只是因为你的 `rules` 校验被通过了。

试想这样一个场景：用户输入了一个合法的手机号，点击提交，`rules` 校验通过，这时没有错误信息。数据提交给服务器后，后端返回了一个错误，你通过 `error` 展示出来。这时用户输入 **另一个** 合法的手机号，点击提交，此时因为手机号格式是合法的，`rules` 校验通过，所以错误信息是应该被清空的（因为前端此时并不知道这个手机号能否通过服务器的校验）。

**Comment by xiangnanscu** [comment]
@Leopoldthecoder 第二次提交的时候, rules校验通过,错误信息清空, 但1秒后`this.errors = {phone: '无效手机号'}`使得错误信息又被赋值,  此时应像第一次提交那样渲染相同错误信息的吧?

此外rules和errors混用应该是不可避免的吧? rules渲染前端的错误(比如正则不匹配之类的), errors负责渲染后端返回的错误. 那么除了你提到的那个绕过技巧之外, 可以从设计层面解决这个问题吗? 即:errors.phone既然有值, 那么对应的错误就应该显示出来. 如果赋值之前要先置空, 总觉得有些不够优雅.
