### ISSUE TITLE
时间选择器 datetimerange 格式 bug

### ISSUE THREAD

**Issue by hj2060** [ElemeFE/element#5845]
时间选择器类型 为 datetimerange时
设置format 为 yyyy-MM-dd HH:mm
选择时仍然可以选择秒这一列  只是选择完毕后不在输入框中显示秒
还有在外侧设置禁止清空 clearable=false  那么弹出选择时间窗之后 清空按钮也不应该出现了吧？ 现在时间窗用户仍然可以再 里面清空掉时间

**Comment by hongz1125** [comment]
我也有这个问题！！！
