### ISSUE TITLE
[Bug Report] Pagination page number display problem

### ISSUE THREAD

**Issue by forleve** [ElemeFE/element#5852]
### Element UI version
1.3.7

### OS/Browsers version
Windows Chrome 59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/ffdaz176/](https://jsfiddle.net/ffdaz176/)

### Steps to reproduce
1 大于7页时的效果中，选择第97页

### What is Expected?
99页和100页是连续的页码，中间不应该出现“...“按钮

### What is actually happening?
99页和100页中间出现"..."按钮

**Comment by forleve** [comment]
@element-bot update the link

**Comment by Leopoldthecoder** [comment]
Fixed in #5861
