### ISSUE TITLE
[Bug Report] Transfer component size (width/height) cannot be modified

### ISSUE THREAD

**Issue by bizarte** [ElemeFE/element#5854]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu/Chrome

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/ym0meo07/](https://jsfiddle.net/ym0meo07/)

### Steps to reproduce
I am using the transfer box in my project but it seems that the height/width are not configurable. In the document http://element.eleme.io/#/zh-CN/component/transfer
, I didn't find the parameter for modifying the element size.

I also checked the iView Transfer which happened to have the feature of adding style to the Transfer box (https://www.iviewui.com/components/transfer   using list-style). I chose elementui between the two when I started my project and I would prefer keep only one UI library if possible.

### What is Expected?
I want to modify the Transfer box size.
1. Is there a hidden way to configure the size?
2. If not, any ideas on how to work this around?

### What is actually happening?
I didn't find the parameter for modifying the element size.

**Comment by Leopoldthecoder** [comment]
When it comes to changing component's styles, we recommend overriding their CSS directly: https://jsfiddle.net/ym0meo07/2/ .
