### ISSUE TITLE
How does the [Feature Request] global method this.$loading (options) shut down?

### ISSUE THREAD

**Issue by qq157788394** [ElemeFE/element#5857]
### Existing Component
是

### Component Name
loading

### Description
完整引入了 Element，现在在页面里面可以用全局方法this.$loading(options)拉起loading，有没有全局关闭的方法？

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/28203231-629a144c-68ab-11e7-804d-3d1d04a2ee8d.png)

**Comment by zjlovezj** [comment]
Please allow me to be more specific:
``js
this.$loading().close(); // close a global loading instance
``
