### ISSUE TITLE
[Bug Report] selector multiple-limit problem

### ISSUE THREAD

**Issue by ganpanlin** [ElemeFE/element#5858]
### Element UI version
1.3.7

### OS/Browsers version
版本 59.0.3071.115（正式版本） （64 位）

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/L86gsLd3/](https://jsfiddle.net/L86gsLd3/)

### Steps to reproduce
在默认案例中加入
multiple-limit="1" 选项

### What is Expected?
运行无报错，无警告
选择只能选择一项，多项不能选择

### What is actually happening?
选择只能选择一项，多项不能选择
运行无报错，Vue报出警告
[Vue warn]: Invalid prop: type check failed for prop "multipleLimit". Expected Number, got String.

对于该属性  是使用"multiple-limit"还是":multiple-limit"无明确样例，
但使用multiple-limit=“limit”数据时，无法进行选择
data:{limit:1}

而直接使用 multiple-limit=“1” 时，可使用，但存在警告

改为":multiple-limit"方式后，配置可用

对此配置的检查是否可以严格一点

**Comment by languanghao** [comment]
multiple-limit="1"前面加个 : ，你这里是要传递一个JavaScript的值props，不是字符串

**Comment by Leopoldthecoder** [comment]
使用 Element 前请阅读 Vue 文档。

**Comment by rool80** [comment]
I have the same problem :(
multiple-limit=1 or multiple-limit="1" <- i get warn: Invalid prop: type check failed for prop "multipleLimit". Expected Number, got String.

What I'm doing wrong?
thx for help
