### ISSUE TITLE
[Bug, Report], V-for (el-form-item), rules, only show the scarlet letter, but not back

### ISSUE THREAD

**Issue by WrenchDE** [ElemeFE/element#5860]
### Element UI version
1.3.7

### OS/Browsers version
os10.12.5/chrome 59.0.3071.115

### Vue version
2.4.1

### Reproduction Link
[https://github.com/ElemeFE/element/issues/5859](https://github.com/ElemeFE/element/issues/5859)

### Steps to reproduce
<template>
    <div>
<el-form :model="ruleForm" :rules="rules" :ref="ruleForm" label-width="100px" class="demo-ruleForm">
  
  <el-form-item label="活动名称" prop="name">
    <el-input v-model="ruleForm.name"></el-input>
  </el-form-item>
  <el-form-item label="起始值" prop="region">
    <el-input v-model="ruleForm.region"></el-input>
  </el-form-item>
  <el-form-item label="结束值" prop="desc">
    <el-input type="input" v-model="ruleForm.desc"></el-input>
  </el-form-item>

 <el-form-item :label="x.label" v-for="(x, index) in momo.shuju" :key="index" :prop="x.props">
    <el-input v-model="x.model"></el-input>
  </el-form-item>

  <el-form-item>
    <el-button type="primary" @click="submitForm('ruleForm')">立即创建</el-button>
    <el-button @click="resetForm('ruleForm')">重置</el-button>
  </el-form-item>
</el-form>
    </div>
</template>
<script>
  export default {
    data () {
      return {
        ruleForm: {},
        rules: {
          name: [
            { required: true, message: '请输入活动名称', trigger: 'blur' },
            { min: 3, max: 5, message: '长度在 3 到 5 个字符', trigger: 'blur' }
          ],
          region: [
            { required: true, message: '请选择活动区域', trigger: 'change' }
          ],
          desc: [
            { required: true, message: '请填写活动形式', trigger: 'blur' }
          ]
        },
        momo: {
          shuju: [
            { props: 'name', label: '活动名称', placeholder: '请输入活动名称', model: '', select: false, content: [] },
            { props: 'region', label: '起始值', placeholder: '请输入起始值', model: '', select: false, content: [] },
            { props: 'desc', label: '结束值', placeholder: '请输入结束值', model: '', select: false, content: [] }
          ]
        }
      }
    },
    methods: {
      submitForm (formName) {
        this.$refs[formName].validate((valid) => {
          if (valid) {
            alert('submit!')
          } else {
            console.log('error submit!!')
            return false
          }
        })
      },
      resetForm (formName) {
        this.$refs[formName].resetFields()
      }
    }
  }
</script>

### What is Expected?
预期v-for (el-form-item)  的rules 可以正确判断

### What is actually happening?
前三个是 静态的

后3个是动态的

执行完三个静态的  动态的那个rules就能用了

现在 刷新后试试 直接用动态的 rule就失效

然后再点静态的

然后动态的规则就能用

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
