### ISSUE TITLE
[Bug Report] The display problem of the Select selector binding object

### ISSUE THREAD

**Issue by liys7788** [ElemeFE/element#5862]
### Element UI version
1.3.7

### OS/Browsers version
Win10 / Chrome 58.0.3029.110 (64-bit)

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/9zbx1e6c/12/](https://jsfiddle.net/9zbx1e6c/12/)

### Steps to reproduce
Run OK in jsfiddle,
In contrast, when the select selector binds String and Object

### What is Expected?
When the select selector binds V-model to an object, the value in the object can be displayed normally,
Like binding String
Thanks in advance :)

### What is actually happening?
When the select selector binds V-model to an object, the value in the object is not loaded

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/9zbx1e6c/14/

When an object is bound to `v-model`, make sure it points to the same object as one of the options because `{ a: 1 } !== { a: 1 }`.
