### ISSUE TITLE
[Feature Request] How to fork element UI Repo.

### ISSUE THREAD

**Issue by nwinnrer** [ElemeFE/element#5867]
### Existing Component
Yes

### Component Name
elment-ui

### Description
As a developer who needs to fork element UI to fit my requirements, what is the best way to fork the project?

Is this a correct solution?
```
npm install git https://github.com/hagcin/element.git -S
and remove "/lib/" folder from .gitignore
```
or is there a better way to do this? ( might make fore nice information in the FAQ)

Thanks for making a truly great UI library!

**Comment by Leopoldthecoder** [comment]
Yes, that is the correct solution.
