### ISSUE TITLE
[Bug Report] Vue v2.4.1 give an error in upload component

### ISSUE THREAD

**Issue by kevinongko** [ElemeFE/element#5868]
After updating Vue to 2.4.1 the upload component show error in console when uploading a file.

### Element UI version
1.3.7

### OS/Browsers version
macOS sierra 10.12.5 / Chrome Version 59.0.3071.115

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/KevinOngko/pj71jkyw/375/](https://jsfiddle.net/KevinOngko/pj71jkyw/375/)

### Steps to reproduce
Upload an image

### What is Expected?
no error in console.

### What is actually happening?
console show 
`[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.`

**Comment by Leopoldthecoder** [comment]
Fixed in #5872
