### ISSUE TITLE
使用dialog对话框时 body元素会加上padding-right:17px

### ISSUE THREAD

**Issue by NotGeekAtAll** [ElemeFE/element#587]
当dialog对话框打开的时候会出现这个问题，导致页面右部整体出现空白，这个长度难道是滚动条的长度吗，如何解决.
![pic](http://p1.bqimg.com/4851/0ba8e67e4ce78a75.png)

**Comment by Leopoldthecoder** [comment]
是的。不需要的话可以将 `lock-scroll` 属性赋值为 `false`。

**Comment by NotGeekAtAll** [comment]
@Leopoldthecoder 谢谢 当时看到了这个属性 不过我以为是body的上下滚动  element很给力 ！

**Comment by lincenying** [comment]
这个是防止滚动条消失后, 整体内容右移...

**Comment by Kaijun** [comment]
@Leopoldthecoder 是否可以做成不设置的话，自动判断页面高度/是否有scrollbar，按需padding?

**Comment by Kaijun** [comment]
@Leopoldthecoder 测了下 RC9好像是自动的，但是行为是相反的。。。没有scrollbar的时候是加padding, 有的时候却是不加padding

===
有scrollbar:

![screen shot 2016-11-11 at 11 49 46 am](https://cloud.githubusercontent.com/assets/1693027/20203749/0a829520-a805-11e6-953f-81585405e08d.png)

===
没scrollbar:

![screen shot 2016-11-11 at 11 50 01 am](https://cloud.githubusercontent.com/assets/1693027/20203758/1cc67bc0-a805-11e6-876f-aa2f974fac36.png)

**Comment by Kaijun** [comment]
@Leopoldthecoder 由于 dialog 使用了 vue-popup, 然而 vue-popup 是压缩过的，无法直接设debugger定位问题。看了下源码, 然后定位了下问题, 发现
```
let bodyHasOverflow = document.body.clientHeight < document.body.scrollHeight;
```
然而我Body没有设置100%... 所以clientHeight一直比scrollHeight小...

**Comment by Leopoldthecoder** [comment]
@Kaijun 试试 1.0.1 版本还有没有这个问题。
