### ISSUE TITLE
The select exception is used in [Bug Report] table (with V-IF)

### ISSUE THREAD

**Issue by XinHuaLuFang** [ElemeFE/element#5870]
### Element UI version
1.3.7

### OS/Browsers version
all

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/xhlf/dyufqmr1/](https://jsfiddle.net/xhlf/dyufqmr1/)

### Steps to reproduce
在表格第一行第二列选择select，label不改变，点击“修改dom”按钮，该select显示的label才发生改变。

### What is Expected?
select选择后显示正确的label

### What is actually happening?
select显示的label和value不匹配

**Comment by Leopoldthecoder** [comment]
修改 54 行：https://jsfiddle.net/dyufqmr1/1/
请阅读 Vue 文档 https://vuejs.org/v2/guide/reactivity.html
