### ISSUE TITLE
[Bug Report] el-time-picker" does not emit "change" when attribute "editable" is true and time is manually entered

### ISSUE THREAD

**Issue by hawkeye64** [ElemeFE/element#5874]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 16.04.2 / Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/Hawkeye64/21agx8aw/1/](https://jsfiddle.net/Hawkeye64/21agx8aw/1/)

### Steps to reproduce
Manually enter a value for the first time picker and then tab to the second time picker.
In the console, notice that no "change" was emitted.
The second time picker has a "minTime" set to value1.
The drop down for the second time picker does not have the minTime set from the first time picker.

### What is Expected?
Make sure Chrome Console is open.

When the attribute "editable" is true (default) that when a user types in a value that matches one of the selectable values and tabs, then that value will automatically be selected and a "change" emit occurs. You would be able to verify this happens in the console with the console.log() output.
Also, if the user types in a value that doesn't match one of the selectable parameters, when they tab, it would clear the editable area as leaving it there is misleading. (for example: the user types "1800" instead of "18:00" and then tabs, the bad value stays)

### What is actually happening?
No "change" signal is emitted when a user manually enters a value when the "editable" value is set to true.

**Comment by hawkeye64** [comment]
Note: The expected behaviour works for el-date-picker. el-time-picker should be the same.

**Comment by Dreamacro** [comment]
Fixed in #6023

**Comment by evgencode** [comment]
Still `@change` doesn't work on el-date-picker when is specified `:value="value"` (not v-model)
