### ISSUE TITLE
[Bug Report] warns of using upload components in vue@2.4.1

### ISSUE THREAD

**Issue by atzcl** [ElemeFE/element#5876]
### Element UI version
1.3.7

### OS/Browsers version
OSX 10_12_5/Chrome_59.0.3071.115

### Vue version
2.4.1

### Reproduction Link
[使用官网的例子](https://jsfiddle.net/k4meLhjb)

### Steps to reproduce
可以打开官网的例子，打开控制台查看Console

### What is Expected?
不出现任何警告或错误

### What is actually happening?
在最新的vue 2.4.1版本中，使用upload组件并转入列表数据后，出现
```
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
```
警告

**Comment by Leopoldthecoder** [comment]
Duplicate of #5868
