### ISSUE TITLE
[Bug Report] upload component file-list bug

### ISSUE THREAD

**Issue by stanNo1** [ElemeFE/element#5879]
**Element UI version**

1.3.7

**OS/Browsers version**

chrome

**Vue version**

2.4.1

**Reproduction Link**

https://jsfiddle.net/stanzhou/2Ljwug4h/

**What is actually happening?**

提示
vue.js:465 [Vue warn]: Avoid using non-primitive value as key, use string/number value instead
初步定为是由于file-list引起的，如果未定义file-list或show-file-list=false，不会出现此问题。这个问题应该是vue新的版本引起的。

**Comment by LypGitHub** [comment]
hey, I found that bug might be because the key in the upload list component is the file object
