### ISSUE TITLE
The [Bug Report] table does not make the extended content scroll around the table while using extended rows and fixed columns

### ISSUE THREAD

**Issue by dingyiming** [ElemeFE/element#5882]
### Element UI version
1.3.7

### OS/Browsers version
windows 10 / chrome 59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/ykop80ao/](https://jsfiddle.net/ykop80ao/)

### Steps to reproduce
在表格中，同时使用 固定列 加 扩展行，目前只能让扩展行的内容随，表格一起滚动，便导致内容错乱，

### What is Expected?
在表格中，同时使用 固定列 加 扩展行，让扩展行的内容不随表格左右滚动

### What is actually happening?
在表格中，同时使用 固定列 加 扩展行，目前只能让扩展行的内容随，表格一起滚动，便导致内容错乱，

**Comment by talski** [comment]
Table with fixed column and header does not scroll when hover a fixed column, any news?

**Comment by biggu0** [comment]
+1

**Comment by Leopoldthecoder** [comment]
从设计上来说，扩展行和固定列都是为了解决数据项内容过多的问题。在使用时，请选择其中一种方案。
