### ISSUE TITLE
[Bug Report] After the opens the totals and fixed columns, the table displays an exception

### ISSUE THREAD

**Issue by zhukaidi** [ElemeFE/element#5886]
### Element UI version
1.3.7

### OS/Browsers version
window 10 64bit/chrome  59.0.3071.115

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/kyhatz9w/1/](https://jsfiddle.net/kyhatz9w/1/)

### Steps to reproduce
对表格设置高度，宽度，固定列，合计行，表格布局出现异常

### What is Expected?
合计信息显示不错位，使横向滚动条能够完整显示，固定列的合计信息不遮挡滚动条。

### What is actually happening?
固定列的合计信息，向上偏移，挡住横向滚动条

**Comment by rossroma** [comment]
固定列遮挡滚动条的问题，有计划解决吗？

**Comment by Leopoldthecoder** [comment]
@rossroma Table 的问题接下来几周会集中解决。

**Comment by AprilXtt** [comment]
这个issue是不是还没有解决呀

**Comment by furybean** [comment]
与 #6157 重复，请关注 #6157 的进度。
