### ISSUE TITLE
When [Bug Report] uses multilevel tables and fixed columns, the data is hidden incorrectly

### ISSUE THREAD

**Issue by zhukaidi** [ElemeFE/element#5887]
### Element UI version
1.3.7

### OS/Browsers version
windows 10 64bit / chrome 59.0.3071.115

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/24ssct0c/1/](https://jsfiddle.net/24ssct0c/1/)

### Steps to reproduce
有上下2个表格：第一个表格左右的固定列，为多级表头；第二个表格相对第一个表格近取消了固定列的设置，其余均相同，做对比使用。
发现固定列后，左侧固定的第二列没有显示数据；右侧固定列，顶端列标题无法显示，第一列数据也无法显示。
拖动固定列边缘，调整列宽，表格布局会异常，固定的宽度没有随列的宽度改变。

### What is Expected?
表格内的数据能够完整显示；
调整固定列的宽度，表格布局不出现异常情况，固定宽度随列的宽度改变而改变。

### What is actually happening?
发现固定列后，左侧固定的第二列没有显示数据；右侧固定列，顶端列标题无法显示，第一列数据也无法显示。
拖动固定列边缘，调整列宽，表格布局会异常，固定的宽度没有随列的宽度改变。

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0: https://jsfiddle.net/24ssct0c/3/
