### ISSUE TITLE
[Feature Request] collapsed inline menu

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#5890]
### Existing Component
是

### Component Name
NavMenu

### Description

l thik `collapsed inline menu` is necessary .  Also we can hack by overwrite css , but it is dirty and defective . like this 

![nav-demo](https://user-images.githubusercontent.com/8121621/28257978-1c8b0882-6b01-11e7-8062-d8ea5ed8b6fe.gif)

we can overwrite css but like sub-menu expands event we can’t stop , so it will has some bug .

I  sincerely wish the official to do this , like [ant](https://ant.design/components/menu/#components-menu-demo-inline-collapsed)

**Comment by Leopoldthecoder** [comment]
Added in #5941
