### ISSUE TITLE
[Bug Report] Vue's 'Avoid using non-primitive value as key' warning in Select with multiple (el-tag inside)

### ISSUE THREAD

**Issue by shawtung** [ElemeFE/element#5894]
### Element UI version
1.3.7

### OS/Browsers version
mac os x 10.12 / chrome 59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/shawtung/4jaqvvhs/](https://jsfiddle.net/shawtung/4jaqvvhs/)

### Steps to reproduce
(set the :value of el-opition to item instead of item.name, then run the script)
select an option
then the error appears in the console

### What is Expected?
no error
:key of the el-tag list should be the index, instead of the item.value

### What is actually happening?
errors output.

**Comment by Leopoldthecoder** [comment]
Fixed in #5897
