### ISSUE TITLE
[Bug Report] 当datepicker的align设置为center时，会导致datepicker没有被挂载到body上，并样式错误

### ISSUE THREAD

**Issue by languid** [ElemeFE/element#5896]
### Element UI version
1.3.7

### OS/Browsers version
windows10 专业版/ chrome 59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/languid/uaks758z/](https://jsfiddle.net/languid/uaks758z/)

### Steps to reproduce
任意地方使用el-date-picker组件，并设置 align="center"，点击即可

### What is Expected?
el-picker-panel渲染在body下，并样式正确

### What is actually happening?
被渲染在了 el-input内，

**Comment by Leopoldthecoder** [comment]
Fixed in #5955
