### ISSUE TITLE
[Feature Request] 建议增加From校验提示文字位置选项

### ISSUE THREAD

**Issue by szm1002** [ElemeFE/element#5898]
### Existing Component
是

### Component Name
Form表单

### Description
现有校验规则文字提示仅支持在输入框下面显示，若From表单项离的太近，校验文字会被遮盖。希望能够增加可选项，选择将校验文字提示显示在输入框的后面。
PS.试过自己修改css，但dom中有一个`<br>`标签强制校验文字换行了，遂未成功。
![image](https://user-images.githubusercontent.com/10546694/28262047-373661dc-6b14-11e7-9382-68412f07bbda.png)

**Comment by wacky6** [comment]
你是不是改过css了。。原生的文字位置是没有问题的啊。。

**Comment by szm1002** [comment]
@wacky6 没有改CSS。因为页面表单很复杂，我在一个父 `el-form-item` 里嵌了几个子 `el-form-item`，它们的上下间距就变得很小，造成了文字被覆盖。可以通过手动设置CSS增加子 `el-form-item` 的 `margin` 让文字显示出来，但那样造成父 `el-form-item` 占据的空间太大，整个页面不协调。所以提议增加校验文字提示的位置配置项。

**Comment by wacky6** [comment]
form-item 不能嵌套的吧？

**Comment by Leopoldthecoder** [comment]
@szm1002 给个 demo 吧

**Comment by szm1002** [comment]
@wacky6 @Leopoldthecoder 
demo: https://jsfiddle.net/x40y1fc1/

![image](https://user-images.githubusercontent.com/10546694/28303259-c7086d86-6bc4-11e7-929a-1572d2631da2.png)

**Comment by wacky6** [comment]
@Leopoldthecoder 有必要让 form-item 可以嵌套使用么？

**Comment by Leopoldthecoder** [comment]
是可以嵌套的，我们自己写项目也经常用到。只是如果一个 FormItem 里嵌套了多个 FormItem 的话，需要自己覆盖下样式：https://jsfiddle.net/x40y1fc1/1/

**Comment by wacky6** [comment]
感觉可以把这个样式合进来。

**Comment by szm1002** [comment]
@Leopoldthecoder 嗯这个办法我在之前提到了。
![image](https://user-images.githubusercontent.com/10546694/28350442-913f3330-6c7b-11e7-8ebf-3f1749c2fdb9.png)
但在有些场景下间距太大影响页面协调性，所以还是建议增加一个配置项，可以选择文字的位置。甚至是把多余的 `br` 标签去除也好，我们就可以自己写样式让文字跟在输入框后面了。

**Comment by wacky6** [comment]
@szm1002 我随便写了一个： https://jsfiddle.net/9gsu3ue6/

我这里没看到`<br>`标签啊。

**Comment by szm1002** [comment]
@wacky6 。。。看了一下我的代码，是我自己逗比了，`<br>`标签是我自己写的。sorry。。close吧

**Comment by shen-lan** [comment]
请问 提示文字如何放在右侧
