### ISSUE TITLE
[Bug Report] official Dialog first: the before-close example doesn't work

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#5901]
### Element UI version
1.3.7

### OS/Browsers version
mac/chrome

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/51g42wpt/](https://jsfiddle.net/51g42wpt/)

### Steps to reproduce
官方Dialog第一个:before-close示例不起作用

### What is Expected?
官方Dialog第一个:before-close示例不起作用

### What is actually happening?
官方Dialog第一个:before-close示例起作用

**Comment by Leopoldthecoder** [comment]
`before-close` 仅在点击关闭按钮或遮罩时起作用。footer slot 按钮如果需要的话可以直接在点击事件里写。
