### ISSUE TITLE
[Bug Report] <el-form> supports no onsubmit hook

### ISSUE THREAD

**Issue by kkinder** [ElemeFE/element#5907]
### Element UI version
1.3.7

### OS/Browsers version
N/A

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/378/](https://jsfiddle.net/pj71jkyw/378/)

### Steps to reproduce
Attempt to submit form without use of a button.

### What is Expected?
@submit should trigger

### What is actually happening?
@submit does not trigger

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/FAQ.md

**Comment by kkinder** [comment]
Unfortunately, I think you're misunderstanding.

It might be easier if I just show you the code:

https://github.com/ElemeFE/element/pull/5920

You want hitting enter/return in a form to validate the form, just like if you click the button. So for example, you'd want to be able to write this:

    <el-form @submit="send">
        ...
        <el-button @click="send">Send</button>
    </el-form>

The form's submit handler and the button's click handler should do the same thing.
