### ISSUE TITLE
How does [Feature Request] get the current highlight node of tree, and then dynamically set the new node highlight?

### ISSUE THREAD

**Issue by docikaci** [ElemeFE/element#5909]
### Existing Component
是

### Component Name
tree

### Description
需求是这样的：
用户选中tree上 任意一个节点，在页面里有两个按钮， 上一位，下一位，   希望可以获取tree node的当前高亮的节点， 然后自动定位到下一位，或者上一位！   无需CheckBox，只是选中高亮

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/arhv1ucf/1/

**Comment by docikaci** [comment]
@Leopoldthecoder   hi 请问下，现在下一个的id是根据当前currentkey生成的一个， 假如ID没有规律，怎么获取下一个id呢？  要根据当前的currentKey，然后遍历整个treeData，找到下一个key吗？ 还是有其它思路，  非常感谢

**Comment by Leopoldthecoder** [comment]
可以在开始的时候遍历 treeData，生成一个记录各个节点前后信息的对象。之后点击按钮就不用遍历了。

**Comment by docikaci** [comment]
@Leopoldthecoder 这个方案好， 我try一下，  谢谢 谢谢！！
