### ISSUE TITLE
select组件的filter-method方法调用示例

### ISSUE THREAD

**Issue by xiangpaopao** [ElemeFE/element#591]
我在给搜索框添加拼音检索的功能，能否描述filter-method方法如何调用

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gbw1jLd4/

大体是这样，具体的逻辑请自行添加。

**Comment by xiangpaopao** [comment]
thanks

**Comment by biosrs** [comment]
@Leopoldthecoder 问个问题,也不知道怎么重开此issue, 就是说select组件在可以手动输入搜索(包括自定义filter)的时候,如果输入一个词比如"双皮奶"然后按backspace键一个一个删光的时候,options仍然只有"双皮奶",就是说删光的时候没有最后调用filter方法.
