### ISSUE TITLE
[Feature, Request], hightlight, a, tree, node, whene, initialize.

### ISSUE THREAD

**Issue by believeZJP** [ElemeFE/element#5911]
### Existing Component
是

### Component Name
tree

### Description
when init a tree component, sometimes need to highlight first node ,but there is no a param to config this.

**Comment by Leopoldthecoder** [comment]
Use `current-node-key`: https://jsfiddle.net/arhv1ucf/

**Comment by believeZJP** [comment]
OK! use label，but current-node-key feel like use key

**Comment by Leopoldthecoder** [comment]
I was just being lazy, of course you can use a real key instead of labels.

**Comment by believeZJP** [comment]
I used node-key="id" current-node-key="1" or  node-key="id" current-node-key=1 ,but it's not working.

**Comment by Leopoldthecoder** [comment]
Please write a demo.

**Comment by believeZJP** [comment]
http://jsrun.net/gcYKp demo is here.

**Comment by believeZJP** [comment]
https://jsfiddle.net/u2xucnwz/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/u2xucnwz/1/
`current-node-key="1"` should be `:current-node-key="1"`

**Comment by believeZJP** [comment]
OK! It's working now, thank you very much~~
