### ISSUE TITLE
 [Bug Report] The transform function of the async-validator won't write back its return value to the formData

### ISSUE THREAD

**Issue by xiangnanscu** [ElemeFE/element#5919]
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu14.04/chrome 59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/pronan/dr2t6ny7/](https://jsfiddle.net/pronan/dr2t6ny7/)

### Steps to reproduce
输入数字100, 点提交

### What is Expected?
显示"number"

### What is actually happening?
显示"string"

**Comment by xiangnanscu** [comment]
按async-validator的文档, transform应该是要回写值到source的.
https://github.com/yiminghe/async-validator#transform

**Comment by Leopoldthecoder** [comment]
Use `v-model.number`: https://jsfiddle.net/dr2t6ny7/2/
