### ISSUE TITLE
[Bug Report] select multiple default value

### ISSUE THREAD

**Issue by falstack** [ElemeFE/element#5924]
### Element UI version
1.3.7

### OS/Browsers version
mac / chrome

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/rk38c6n1/](https://jsfiddle.net/rk38c6n1/)

### Steps to reproduce
https://jsfiddle.net/rk38c6n1/

### What is Expected?
https://jsfiddle.net/rk38c6n1/

### What is actually happening?
https://jsfiddle.net/rk38c6n1/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/rk38c6n1/1/

**Comment by falstack** [comment]
@Leopoldthecoder 

thank you! :D
