### ISSUE TITLE
el-table默认高亮第一行出错

### ISSUE THREAD

**Issue by ilongdao** [ElemeFE/element#5925]
我在获取到table 的数据时使用了this.currentRow = table[0];或者this.$refs.singleTable.setCurrentRow(table[0]);时前一种无反应后一种直接弹nan;在想是不是要等数据加载到dom里面后再才能执行，想咨询一下直接在获取到table数据时就默认第一行高亮的正确写法，谢谢

**Comment by web-oop** [comment]
我也遇到这个问题 ，获取数据之后执行这一段代码setFirstRow(row) {this.$refs.bookTable.setCurrentRow(row);}  参数row是tabledata[0] 但是第一行不会出现高亮。

**Comment by ZhBano** [comment]
updated() {
    this.$refs.singleTable.setCurrentRow(this.list[0])
  },
可以试一下
