### ISSUE TITLE
[Bug Report] beforeFileUpload return false causes other file uploads to be interrupted

### ISSUE THREAD

**Issue by cherislive** [ElemeFE/element#5927]
### Element UI version
1.3.7

### OS/Browsers version
Windows

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/dqwkbzgu/1/](https://jsfiddle.net/dqwkbzgu/1/)

### Steps to reproduce
el-upload 组件 如果有正在上传的文件 before-upload 中return false导致正在上传的文件中断
A、B、C文件正在上传状态 这个时候上传D文件，D文件不符合规则并return false 这个时候ABC文件中断了

### What is Expected?
ABC文件正常上传

### What is actually happening?
ABC文件无法正常上传

**Comment by stanNo1** [comment]
我也很纠结这个问题，官方文档上before-uplaod注明只要一个文件retuan false，此次上传应该整个都会停止（其他文件也不会上传）。但是感觉不太合理，不知道有什么好的方法可以解决这个问题。
