### ISSUE TITLE
[enhancement]long press input number's trigger button

### ISSUE THREAD

**Issue by dsonet** [ElemeFE/element#593]
### ElementUI version
1.0.0-rc.7

### OS/Browers version
any

### What is Expected?

when long press the input number's trigger button, it's better to repeat the action like every half seconds(or a configurable value).

### What is actually happening?
Nothing happened after long press the minus or plus button.

**Comment by Leopoldthecoder** [comment]
Input number already has such feature. Working example: http://element.eleme.io/#/component/input-number .

If it doesn't work for you, please provide a demo.
