### ISSUE TITLE
Tree组件怎么改变选中和hover的样式，重写css不起作用

### ISSUE THREAD

**Issue by wengxuan** [ElemeFE/element#5930]
template

    <el-tree :data="deviceName" :props="deviceProps" accordion @node-click="capacityNodeClick"
     node-key="id" :default-expanded-keys="[1]" :default-checked-keys="[1]" highlight-current></el-tree>

style

    .is-current .el-tree-node__content{
        background: none !important;
        color: #318EEC !important;
    }
    .el-tree .el-tree-node:hover {
        background: #2db7f5 !important;
    }

**Comment by somedayiamold** [comment]
2.0.10版本试下这个
.el-tree--highlight-current .el-tree-node.is-current > .el-tree-node__content {
        background-color: #409EFF;
}
