### ISSUE TITLE
[Bug Report] Cannot set v-loading on a Dialog component

### ISSUE THREAD

**Issue by sunnylost** [ElemeFE/element#5931]
### Element UI version
1.3.7

### OS/Browsers version
Mac / Chrome 61

### Vue version
2.3.3

### Reproduction Link
[http://jsfiddle.net/pj71jkyw/385/](http://jsfiddle.net/pj71jkyw/385/)

### Steps to reproduce
add "v-loading" on a <el-dialog> tag

### What is Expected?
loading mask should cover dialog

### What is actually happening?
dialog is disappeared, because its position had been set to "relative".

At element/packages/loading/src/directive.js, line 32:

```javascript
el.originalPosition = el.style.position;
```

In most cases, "position" was being set by css file instead of inline, so "el.style.position" would return blank string.

line 60:

```javascript
if (el.originalPosition !== 'absolute') {
```
Dialog's "position" was "fixed", is this should be considered?

**Comment by Leopoldthecoder** [comment]
This is a valid issue and we'll fix it. But for Dialog, it is recommended to use loading as a service: http://jsfiddle.net/pj71jkyw/471/ . Because the outmost element of Dialog is a fullscreen wrapper, the loading mask will cover the whole screen if you're using it as a directive.
