### ISSUE TITLE
The [Bug Report] table component cannot display the value of the boolean type (prop is the key of the attribute, and the key corresponds to Boolean)

### ISSUE THREAD

**Issue by yuyue94** [ElemeFE/element#5933]
### Element UI version
1.3.7

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/yuyue94/j767z6nb/](https://jsfiddle.net/yuyue94/j767z6nb/)

### Steps to reproduce
看重现链接

### What is Expected?
<el-table-column prop="finished"></el-table-column>当data中finished对应的值为boolean类型时，应该能够显示数据

### What is actually happening?
没有显示数据，只能用<template scope="scope">{{ scope.row.finished }}</templete>来代替

**Comment by liril-net** [comment]
@yuyue94 因为 `boolean` 值本身就不应当被渲染，建议你先进行数据转换，或者模板来转换成字符串渲染。

**Comment by ozanmuyes** [comment]
Translation of @liril-net's answer:

Because the boolean value itself should not be rendered, it is recommended that you first convert the data or template to a string rendering.
