### ISSUE TITLE
[Bug Report] table width error when using table in tabs

### ISSUE THREAD

**Issue by stanJ** [ElemeFE/element#5935]
### Element UI version
1.3.7

### OS/Browsers version
win7/chrome59

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/stanJ/yns9mvod/3/](https://jsfiddle.net/stanJ/yns9mvod/3/)

### Steps to reproduce
1. switch tabs first time, the width of table is right.
2. click refresh button, then switch to another tab, the width of table is not right.

### What is Expected?
the width of table is 100%

### What is actually happening?
the width of table is not 100%

**Comment by Leopoldthecoder** [comment]
需要用 `key` 来强制渲染一个新的 Table：https://jsfiddle.net/yns9mvod/4/

**Comment by stanJ** [comment]
谢啦
