### ISSUE TITLE
[Bug Report] Multiple Select delay on large tables

### ISSUE THREAD

**Issue by ppietris** [ElemeFE/element#5940]
### Element UI version
1.3.7

### OS/Browsers version
Windows 10 / Chrome 59

### Vue version
2.4.1

### Reproduction Link
[http://jsfiddle.net/tzpf1x8k/](http://jsfiddle.net/tzpf1x8k/)

### Steps to reproduce
Try to select multiple/all table rows

### What is Expected?
Faster selection

### What is actually happening?
Selection process has great delay

**Comment by Leopoldthecoder** [comment]
I think it's better to use pagination when you have this many rows.
