### ISSUE TITLE
[Bug Report] popup-manager causes "Added non-passive event listener to a scroll-blocking event" violation in Chrome

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#5942]
### Element UI version
1.3.7

### OS/Browsers version
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/257d2gu2/](https://jsfiddle.net/257d2gu2/)

### Steps to reproduce
1. Add a message box or any other element that uses the popup-manager.js
2. Trigger the popup

### What is Expected?
No warning should be visible in the console

### What is actually happening?
"Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive." displayed in console

**Comment by Leopoldthecoder** [comment]
I have tried adding `{ passive: false }` [here](https://github.com/ElemeFE/element/blob/dev/src/utils/popup/popup-manager.js#L19) (`passive` has to be false as we're actually calling `event.preventDefault` in the event handler), but the warning still shows. So let's just ignore it.
