### ISSUE TITLE
[Bug Report] Number Validation sees "55retwerterwt" as a valid number

### ISSUE THREAD

**Issue by nwinnrer** [ElemeFE/element#5943]
### Element UI version
1.3.7

### OS/Browsers version
chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/1x78c6at/](https://jsfiddle.net/1x78c6at/)

### Steps to reproduce
type this value in field in provider link: 44fgsdgdfs

### What is Expected?
Should not validate as success because 44fgsdgdfs it is not a number

### What is actually happening?
does validate as success

**Comment by nwinnrer** [comment]
What a response time! https://jsfiddle.net/1x78c6at/

**Comment by nwinnrer** [comment]
updated.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/1x78c6at/2/

Typing 44fgsdgdfs and you'll see actually `numberValidateForm.age` is converted to 44. So it passes validation.

**Comment by 610076912** [comment]
是被转换为44了，但是逻辑上不应该是通过验证的啊！获取到的数据没有错，但是在展示上通过会给用户造成也允许填写非数字类型的错觉。
