### ISSUE TITLE
[Feature Request] Accessibiilty: Select component should be accessible by the keyboard

### ISSUE THREAD

**Issue by jesca** [ElemeFE/element#5946]
### Existing Component
Yes

### Component Name
Select

### Description
Select component should be accessible by the keyboard. This includes:

Escape should close the dropdown and focus should be reset to the select element
Upon selecting by the keyboard (clicking enter), focus should be reset to the select element
A focused select element should have a clear visible focus outline (or change or border color).. something to differentiate it from being non-focused

**Comment by Leopoldthecoder** [comment]
Duplicate of #9456
