### ISSUE TITLE
建议 Table 增加排序事件

### ISSUE THREAD

**Issue by taojs** [ElemeFE/element#595]
可以为表格做一个排序事件吗，点击的时候发起异步请求

**Comment by jin5354** [comment]
附议

**Comment by fishpaw** [comment]
现在的表头是有排序功能的，详见：http://element.eleme.io/#/component/table 的最后一个控件

**Comment by jin5354** [comment]
@fishpaw  这个排序只是本页数据排序。我们提议加入的是全表格排序，需要重新发请求的。

**Comment by furybean** [comment]
RC8 已经支持。
