### ISSUE TITLE
[Feature Request] select the maximum and minimum values when the calendar is set to type='daterange'support settings. Not in this section are disabled off

### ISSUE THREAD

**Issue by proshuai** [ElemeFE/element#5953]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
like this:
<el-date-picker v-model="value1" type="daterange" align="right" placeholder="选择日期范围" format="yyyy/MM/dd"  minDate="毫秒数" maxDate="毫秒数"></el-date-picker>

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/zsk8nsrh/

**Comment by proshuai** [comment]
@Leopoldthecoder 3Q.希望库的文档能再详细点。。已经做出来这么完美的库了，为什么文档写的那么简单呢

**Comment by Leopoldthecoder** [comment]
@proshuai 在下一个大版本里会把文档做得更全面。不过就 `disabledDate` 而言，DatePicker 的第一个例子就有介绍。

**Comment by proshuai** [comment]
@Leopoldthecoder 那个看到了，就是不知道怎么一次性设置最大最小值。。期待下个版本

**Comment by proshuai** [comment]
@Leopoldthecoder 在不在？

**Comment by sunxia628** [comment]
按照文档例子设置了然而并没有什么效果？

**Comment by sunxia628** [comment]
disabledDate如何设置daterange格式的时间禁用，文档上的例子不工作
