### ISSUE TITLE
[Bug Report] Form component cannot be verified in some case

### ISSUE THREAD

**Issue by wayne-chan** [ElemeFE/element#5957]
### Element UI version
1.3.7

### OS/Browsers version
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/mvrbfbsh/](https://jsfiddle.net/mvrbfbsh/)

### Steps to reproduce
bind input data with an object's attribute, like: v-model="form.object.data"

### What is Expected?
input validation is working fine

### What is actually happening?
Vilidation always return error

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mvrbfbsh/1/
