### ISSUE TITLE
[Bug Report] NavMenu broken in 1.4.0-beta.1

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#5966]
### Element UI version
1.4.0-beta.1

### OS/Browsers version
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/2fwn5qq1/](https://jsfiddle.net/2fwn5qq1/)

### Steps to reproduce
Add a NavMenu element and open the page

### What is Expected?
The NavMenu should appear

### What is actually happening?
Errors "Avoid using non-primitive value as key, use string/number value instead." and "Error in created hook: "TypeError: Cannot read property 'addItem' of undefined"" displayed in the console and the NavMenu does not appear

**Comment by Leopoldthecoder** [comment]
Thanks for your quick feedback.

In 1.4.0 we added a `key`, which is a Boolean, to Menu. That's why the warning comes out. It seems next Vue version will support Boolean typed `key`s: https://github.com/vuejs/vue/pull/6127 , but still we'll convert it to a string/number.

**Comment by Leopoldthecoder** [comment]
Oh, also this bug is related to https://github.com/vuejs/vue/issues/6093

**Comment by Leopoldthecoder** [comment]
Fixed in #5970
