### ISSUE TITLE
('' || time)是什么意思？是bug吗

### ISSUE THREAD

**Issue by lgl1993** [ElemeFE/element#5972]
我在看time-select.vue的代码时看到这么一段代码，('' || time).split(':')，这段有什么用吗？不是一直等于time.split吗？

**Comment by Leopoldthecoder** [comment]
@QingWei-Li 来解释一下你的神奇代码

**Comment by lgl1993** [comment]
跪求，坐等！

**Comment by QingWei-Li** [comment]
找不到源头了 我看旧仓库是 @baiyaaaaa 这段代码是弄的 🌚 改了吧 是 bug

**Comment by lgl1993** [comment]
非常感谢！饿了么大前端同学们！
