### ISSUE TITLE
[Bug Report] [table bug] the colum's order is wrong

### ISSUE THREAD

**Issue by narutowyh** [ElemeFE/element#5974]
### Element UI version
1.4.0-beta.1

### OS/Browsers version
all browser

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/393/](https://jsfiddle.net/pj71jkyw/393/)

### Steps to reproduce
https://jsfiddle.net/pj71jkyw/393/

### What is Expected?
the col's order is right

### What is actually happening?
first col appears at the last table-head

**Comment by Leopoldthecoder** [comment]
Duplicate of #4057
