### ISSUE TITLE
[Feature Request] DatePicker type adds ten-days units

### ISSUE THREAD

**Issue by Sijiu** [ElemeFE/element#5977]
### Existing Component
是

### Component Name
DatePicker

### Description
&nbsp;&nbsp;&nbsp;&nbsp;建议type可选值中可以添加 ten-days(旬)，选择时有类似日期单位：周。那样选定当前旬(每月的前中后10天)，面板显示”2017-7月-中旬“这样。
&nbsp;&nbsp;&nbsp;&nbsp;ps: 或者有没有可以自己添加的方式，每次都能选定一个旬 的日期。并且选择框显示”2017-7月-中旬“这样。用daterange没能实现，望点拨一二。

**Comment by Leopoldthecoder** [comment]
Sorry we have no plan to support this.

**Comment by Hew007** [comment]
同样的需求
