### ISSUE TITLE
[Feature Request] [el-upload] components can also clean up previously selected files before uploading them

### ISSUE THREAD

**Issue by chenhuiYj** [ElemeFE/element#5981]
### Existing Component
Yes

### Component Name
1.3.7

### Description
chrome 59.0.3071.115

我的需求就是只能选择一个文件，虽然设置multiple可以起到些作用，但是如果用户选择了一个文件，再选择一个文件，这样在文件列表那里还有有两个文件，所以就希望在上传文件之前，也应该可以清除之前已经选择的文件！

**Comment by K-walker** [comment]
同问 :multiple="false" 无效 ，并不能单选文件,这是官方 [Demo问题复现](https://jsfiddle.net/w41vc3ro/)

**Comment by K-walker** [comment]
@chenhuiYj  自己把源码下载下来改吧，我自己就是这么干的，加了个single属性，来设置是否是单选

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/7xv9nLr3/
