### ISSUE TITLE
In [Bug Report] datePicker, when type is week, the value of V-model is the second day of the week, not the first day

### ISSUE THREAD

**Issue by zWingz** [ElemeFE/element#5990]
### Element UI version
1.4.0

### OS/Browsers version
ubuntu14, chrome59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/396/](https://jsfiddle.net/pj71jkyw/396/)

### Steps to reproduce
选择时候console控制台为该周第二天.

### What is Expected?
希望返回为该周第一天

### What is actually happening?
返回该周第二天

**Comment by mario56** [comment]
@zWingz 因为你设置了 firstDayOfWeek 为 1，起始为每周1， 返回的都是这周的UI 上显示的第二个。也可以说是返回的是周几(firstDayOfWeek+1)。设置为1 返回的就是周二，设置为2 返回的就是周三。可以建议element 增加一个返回具体周几的设置

**Comment by Dreamacro** [comment]
Fixed in #6038

**Comment by chen4342024** [comment]
周选择的时候设置firstDayOfWeek为1 ， 然后format='yyyy-MM-dd' ， 结果开始时间为周二。请问要怎么设置才能够日历是以周一开头，然后返回的开始时间也为周一呢

**Comment by linzhi** [comment]
@chen4342024  这个问题解决没啊，我也是这个需求

**Comment by chen4342024** [comment]
> @chen4342024 这个问题解决没啊，我也是这个需求

忘记了，太久了
