### ISSUE TITLE
[Bug Report] While form reset, el-input focus failed

### ISSUE THREAD

**Issue by gjycdd** [ElemeFE/element#5999]
### Element UI version
1.2.8

### OS/Browsers version
Chrome Version 59 / win10 -64-bit

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/9o5L8vhr/](https://jsfiddle.net/9o5L8vhr/)

### Steps to reproduce
1.when onload, you can see that el-input autofocus   (success)
2.click Button(Reset)
3.than you see!!! wtf?！！ where is my autofoucs  (faild)

### What is Expected?
After Reset, el-input can also autofocus

### What is actually happening?
After Reset, el-input can not autofocus anyway

**Comment by Leopoldthecoder** [comment]
You can see how `autofocus` works with this demo (without Vue and Element): https://jsfiddle.net/9o5L8vhr/1/

`autofocus` means the element should be automatically focused **after the page loaded**, which is a one-time deal. It cannot restore focus after some other element is focused.
