### ISSUE TITLE
[Feature Request] dateTimeRange component added to select the whole point

### ISSUE THREAD

**Issue by DanielWLam** [ElemeFE/element#6002]
### Existing Component
是

### Component Name
Datepicker

### Description
目前的选择时间精确到秒，但是没有更粗的粒度，希望可以控制时间的筛选粒度，时分秒，谢谢！

**Comment by Leopoldthecoder** [comment]
Now you can disable seconds using format: https://jsfiddle.net/exyzbd3u/ . Sorry we have no plan to disable minutes.

**Comment by YanCoding** [comment]
@Leopoldthecoder I can't disable seconds when type is datetimerange. Example: https://jsfiddle.net/3dfgzqx3/

**Comment by DanielWLam** [comment]
Exactly like YanCoding memtioned, format attribute doesn't work when type if datetimeranger. @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@YanCoding @DanielWLam 
We'll work on it.

**Comment by Dreamacro** [comment]
Added in #6052
