### ISSUE TITLE
[Bug Report] when the table has a total function, if there is a horizontal scroll bar, the total display is not friendly

### ISSUE THREAD

**Issue by lavyun** [ElemeFE/element#6003]
### Element UI version
1.4.0

### OS/Browsers version
All

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/L5dtygjz/](https://jsfiddle.net/L5dtygjz/)

### Steps to reproduce
https://jsfiddle.net/L5dtygjz/

### What is Expected?
如果这不是一个bug，希望合计项随着表格的body一起滚动

### What is actually happening?
合计项被滚动条分开了

**Comment by furybean** [comment]
在需要 Body 可以垂直滚动的情况下，目前只能设计成这样。

先关闭了，如果你有更好的方案，欢迎开 Pull Request。
