### ISSUE TITLE
[Bug Report] Not allowing action buttons in single select table

### ISSUE THREAD

**Issue by basitsattar** [ElemeFE/element#6004]
### Element UI version
1.4.0

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Make a single selection table and add current-change action. Now make a column and add action buttons like edit or delete. Clicking on action buttons will call the method specified in current-change of table instead of method associated with that action.

### What is Expected?
In a single select table where you want to handle row selection. if you have also have actions in that row like edit and delete buttons, they should work and clicking on action buttons should call the method for that action.

### What is actually happening?
In a single select table where you want to handle row selection. if you have also have actions in that row like edit and delete buttons, they don't work and clicking on action buttons call the method for row selection instead of that action.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
