### ISSUE TITLE
[Bug, Report], V-for, rendering, el-form, form validation, fail forever

### ISSUE THREAD

**Issue by DanielWLam** [ElemeFE/element#6005]
### Element UI version
1.4.0

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/b8110wnf/](https://jsfiddle.net/b8110wnf/)

### Steps to reproduce
1. 输入内容
2. 使输入框是去焦点就能触发

### What is Expected?
表单验证通过

### What is actually happening?
永远无法通过

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/b8110wnf/1/
