### ISSUE TITLE
[Bug Report] there is a problem with the NavMenu animation

### ISSUE THREAD

**Issue by GreatAuk** [ElemeFE/element#6009]
### Element UI version
1.4.0

### OS/Browsers version
win 10 Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
placeholder

### What is Expected?
placeholder

### What is actually happening?
placeholder

**Comment by baiyaaaaa** [comment]
your demo not saved
