### ISSUE TITLE
[Feature Request] modify / unify change events for form components

### ISSUE THREAD

**Issue by wacky6** [ElemeFE/element#6011]
听说要有大版本，赶紧跑来搞事情。

### Component Name
表单输入相关组件

### Description
根据 WHATWG 对 change 事件的描述，统一 change 事件的发射行为。[WHATWG HTML Standard](https://html.spec.whatwg.org/multipage/input.html#common-input-element-events)

> When the input and change events apply, the events are fired to indicate that the user has interacted with the control.

> The change event fires when the value is committed, if that makes sense for the control, or else when the control loses focus. In all cases, the input event comes before the corresponding change event (if any).

简单的说，input 和 change 应仅在用户与组件交互时才会发射，通过 JS 脚本修改控件的 value 不会触发。

考虑 vue 的特点和 input、change 的习惯用法：input 事件用于 v-model 同步，在表单组件值发生改变时都可以发射。change 应在用户对控件进行操作，并且改变了值的情况下才会发射。但目前实现的 change 事件前述行为有差异。

目前，部分组件只要 value 发生变化就会发射 change 事件：通过程序改变 value 也会触发事件，而非 **仅在用户与组件交互时**。

目前发现的待修正的组件（留着追踪进度）：

- [x] radio：不发射 change 事件；而原生input[type=radio]会发射，PR https://github.com/ElemeFE/element/pull/6348
- [x] radio-group：等同于 watch(value)，PR https://github.com/ElemeFE/element/pull/6348
- [x] input：change 等同于 input；而原生的 change 仅在 blur 时发射
- [x] input-number：同上
- [x] select：等同于 watch(value)，PR https://github.com/ElemeFE/element/pull/5360
- [x] slider：等同于 watch(value)，PR https://github.com/ElemeFE/element/pull/6374
- [x] {date, time}-picker、time-select：等同于 watch(value)
- [x] rate：等同于 watch(value)，PR https://github.com/ElemeFE/element/pull/6295
- [x] checkbox / checkbox-group：PR https://github.com/ElemeFE/element/pull/6356

待新增 change 事件：
- [x] pagination：新增 change 反应用户操作 -> current-change

### Expected
仅在用户与组件交互时发射 change，通过JS程序修改 value 时不会发射change；此修改为 breaking change。

相关 issue 和 PR ：
https://github.com/ElemeFE/element/pull/5360
https://github.com/ElemeFE/element/issues/5951
https://github.com/ElemeFE/element/issues/5874
https://github.com/ElemeFE/element/issues/5400
https://github.com/ElemeFE/element/issues/6179

**Comment by wacky6** [comment]
@Leopoldthecoder 这个建议carbon考虑一下

**Comment by Leopoldthecoder** [comment]
@wacky6 会的。

另外，目前的 `change` 事件应该还会继续保留（可能要换个名字）。虽然等同于 watch，但是对于 `v-for` 出来的组件，要一个个添加 watch 不是很方便（我能想到的比较简单的方式是循环调用 `vm.$watch`，但是没有监听 `change` 直观）。

**Comment by wacky6** [comment]
我觉得表单类组件的 `@change` 和原生尽量接近比较好。

等同于 watch 的 change 现在有什么需求嘛？我觉得直接 `@input` 也能满足吧。

**Comment by AlenQi** [comment]
I think #6011 is very necessary

**Comment by Leopoldthecoder** [comment]
Rate: #6295

**Comment by Leopoldthecoder** [comment]
@wacky6 Input 和 InputNumber 的 `change` 目前已经是只响应用户交互了，和原生的区别在于原生的仅在 blur 时触发。
「随改随触发」这个行为打算保留，应该「blur 才触发」能覆盖更多的场景。看了下 React 下原生的 `change` 事件就是随改随触发的。

**Comment by wacky6** [comment]
随改随触发 可以直接 `@input`，让 change 提供一样的功能感觉重复了。change 的语义我觉得是用户**确定**输入结果后才应该触发（Input丢失焦点）。

我更倾向于和原生行为保持一致。

Input change：blur 触发
InputNumber change：blur、+-按钮、键盘上下键 触发
