### ISSUE TITLE
[Bug, Report], about, of, default-checked-keys, problems

### ISSUE THREAD

**Issue by lx2328** [ElemeFE/element#6016]
### Element UI version
1.4.0

### OS/Browsers version
Win7 / Firefox 54.0.1

### Vue version
2.4.2

### Reproduction Link
https://jsfiddle.net/7jpj4js4/9/

### Steps to reproduce
我用一个全局Map来保存被勾选的节点，在下一次组件mounted时，把保存的数据赋值给 default-checked-keys ，当保存的数据只有一个时，会出现子节点被勾选，对应的父节点没有被半勾选的状态，当数据超过两个时，是正常的

### What is Expected?
子节点被勾选，对应的父节点也应该被半勾选，不管默认勾选的子节点有几个。

### What is actually happening?
保存的数据只有一个时，子节点被勾选，对应的父节点没有被半勾选。

**Comment by lx2328** [comment]
![izde 2 jg99zy gq oexp](https://user-images.githubusercontent.com/23550512/28506442-1cb2365c-705e-11e7-9a9c-77d6630e273b.png)

**Comment by Leopoldthecoder** [comment]
请准备一个能重现问题的 demo。

**Comment by lx2328** [comment]
不知道什么原因，demo上无法重现，但是我的项目里确实存在那个bug

**Comment by Leopoldthecoder** [comment]
可以把你的项目精简一下，去除无关代码，然后发到 GitHub 上来我们看看。
