### ISSUE TITLE
[Bug Report] Select the parent node sub-node pop-up rendering animation on a Tree component

### ISSUE THREAD

**Issue by feverdestiny** [ElemeFE/element#6017]
### Element UI version
1.4.0

### OS/Browsers version
Windows 7 / Chrome 59.0.3071.86

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/w4km6z6L/](https://jsfiddle.net/w4km6z6L/)

### Steps to reproduce
我使用官方案列，在树折叠时我点击父节点复选框，他会有一个自动弹出子节点选中的动画，这个问题在element UI 1.3.7版本中是不存在的。我发现通过使用‘expand-on-click-node’属性可以避免这个问题。

http://opdagg4vz.bkt.clouddn.com/bug.gif

### What is Expected?
选中父节点会选中子节点，但不会展现子节点弹出动画

### What is actually happening?
选中父节点，会弹出渲染子节点动画

**Comment by Leopoldthecoder** [comment]
@Dreamacro could you take a look?

**Comment by Leopoldthecoder** [comment]
Fixed in #6029
