### ISSUE TITLE
[Bug Report] menu collapse

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#6028]
### Element UI version
1.4.0

### OS/Browsers version
mac

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/PanJiaChen/qshzarqn/1/](https://jsfiddle.net/PanJiaChen/qshzarqn/1/)

### Steps to reproduce
当 `collapse=true` 的时候  default-active 的路径为一个多级嵌套的 会默认展开 这交互不太正确吧

### What is Expected?
不会默认展开

### What is actually happening?
默认展开了 多级nav

**Comment by PanJiaChen** [comment]
@baiyaaaaa

**Comment by Leopoldthecoder** [comment]
Fixed in #6111

**Comment by PanJiaChen** [comment]
@baiyaaaaa 1.4.1还是有点小问题，我展开情况下 expand  了 一个group 收起来的时候 也应该收起
所以不应该只在` initOpenedMenu` 的时候判断。
[demo](https://jsfiddle.net/PanJiaChen/qshzarqn/3/)

**Comment by Leopoldthecoder** [comment]
@PanJiaChen Fixed in #6200
