### ISSUE TITLE
[Bug, Report], can, not, select, the, right, nodes, tree, in

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#6031]
### Element UI version
1.4.0

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/xp7gptyy/2/](https://jsfiddle.net/xp7gptyy/2/)

### Steps to reproduce
1. check `二级1-1`
2. check the top level node `测试文字`

### What is Expected?
all the nodes should been selected

### What is actually happening?
wrong behavior like this: 

![image](https://user-images.githubusercontent.com/1060733/28511988-6f0217a0-7082-11e7-9f12-b705947f1a59.png)

**Comment by Leopoldthecoder** [comment]
Fixed in #6034
