### ISSUE TITLE
[Bug Report] Select filter-method cannot be used

### ISSUE THREAD

**Issue by mirari** [ElemeFE/element#6035]
### Element UI version
1.4.0

### OS/Browsers version
WIn10/Chrome59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/sgrrt9ue/](https://jsfiddle.net/sgrrt9ue/)

### Steps to reproduce
为select组件配置filter-method

### What is Expected?
传入参数为当前输入框关键字，以及当前处理的菜单项。
返回true表示匹配。

### What is actually happening?
传入参数只有当前输入框关键字，没有其他参数。
返回任意值都对列表没有任何影响。

**Comment by Leopoldthecoder** [comment]
你需要在 `filter-method` 里操作 options：https://jsfiddle.net/sgrrt9ue/1/
