### ISSUE TITLE
日期选择器format数据格式

### ISSUE THREAD

**Issue by yiling-e0** [ElemeFE/element#604]
### ElementUI version
1.0.0-rc.7

### Vue version
2.0.1

日期选择器view显示的是2016-10-24，在数据存的却是Mon Oct 24 2016 11:18:05 GMT+0800 (中国标准时间)

这个是需要手动格式日期吗？

**Comment by furybean** [comment]
数据应该是 Date 类型的？

**Comment by yiling-e0** [comment]
@furybean 恩，是需要自己转换成yyyy-MM-dd？  还是有attr可以设置么

**Comment by yiling-e0** [comment]
@furybean  这个感觉不是question应该算质疑，视图和数据不统一

**Comment by QingWei-Li** [comment]
返回的就是时间类型，自己处理时间格式
