### ISSUE TITLE
[Feature Request] Attribute name for datepicker

### ISSUE THREAD

**Issue by LusenkoSasha** [ElemeFE/element#6045]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
How to add the name attribute for el-date-picker?

About the attribute nothing is said in the documentation.

**Comment by wacky6** [comment]
What are you trying to accomplish? Can you be more specific? Which HTML node do you want to add name attribute to?

**Comment by johnheiner** [comment]
@wacky6 
The actual input needs to be able to have a name attribute:
```
<input autocomplete="off" placeholder="Pick a day" type="text" rows="2" class="el-input__inner">
```
Tried binding but name attribute only gets applied to outer div wrapper which doesn't make sense for form submission or validation:
```
<el-date-picker v-bind:name="date_start" v-model="value" type="date" placeholder="Pick a day" format="MM/dd/yyyy"></el-date-picker>
```
results in:
```
<div class="el-date-editor el-input el-date-editor--date" name="date_start" value="2018-10-31" required="required" id="id_date_start">...
```

**Comment by wacky6** [comment]
I think it will be easy to add `name` for data-picker.
What do you expect for ranged date-picker? It has two input fields.

**Comment by johnheiner** [comment]
For ranges, I'd expect to have the ability to pass name attribute to the 'start' and 'end' inputs.

**Comment by wacky6** [comment]
`name` for date-picker is added in 2.0

I will add support for array `name`

**Comment by Leopoldthecoder** [comment]
Thanks guys, PRs merged.
