### ISSUE TITLE
[Bug Report] [Bug Report] When the optional tree is three levels and there is a peripheral node is not checked, the root node is not checked, the abolition of the child node check effect is not canceled

### ISSUE THREAD

**Issue by wutaisu** [ElemeFE/element#6053]
### Element UI version
1.4.0

### OS/Browsers version
window 10 / chrome 59.0.3071.109

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/sezfm267/](https://jsfiddle.net/sezfm267/)

### Steps to reproduce
勾选根节点，取消一个末梢节点选中状态，再点击根节点，再次点击根节点半选中状态消失，此时点击根节点无法勾选。

### What is Expected?
当为三层级树时，子节点存在未勾选时：
点击根节点勾选框，根节点被勾选上，且其下所有子节点勾选上。

### What is actually happening?
当为三层级树时，子节点存在未勾选时：
点击根节点的勾选框，根节点半选中状态不变，而是将末梢节点都选中，同时取消了之前存在未勾选子节点的二级父节点半选中状态。
再次点击根节点的勾选框，根节点半选中状态取消，所有二级节点选中状态被取消，
再次点击根节点的勾选框，无反应。

**Comment by Leopoldthecoder** [comment]
Fixed in #6034

**Comment by timelyportfolio** [comment]
Thank you so much for reporting and fixing.  I was having a very difficult time with this.
