### ISSUE TITLE
在Dialog的v-model中绑定vuex里的state.visiable时，无法使用title区域的小叉关闭

### ISSUE THREAD

**Issue by SkyLin0909** [ElemeFE/element#6055]
`<el-button type="success" @click="$store.dispatch('handleOpen',true)">添加管理员</el-button>`
`<el-dialog title="编辑用户" v-model="formVisible">
       <div slot="footer" class="dialog-footer">
            <el-button @click="$store.dispatch('handleCancel',false)">取 消</el-button>
            <el-button type="primary" @click="updateUserMsg">保 存</el-button>
        </div>
 </el-dialog>`
以上为兄弟组件，`state: {
        formVisible: false
    },

    mutations: {
        CHANGE_formVisible: (state, bool) => {
            state.formVisible = bool
        },
    },

    actions: {
        //显示表单
        handleOpen({commit}, bool) {
            commit('CHANGE_formVisible',bool)
        },

        //取消表单
        handleCancel({commit},bool) {
            commit('CHANGE_formVisible',bool)
        }

    }`
但是无法使用组件自带的show-close，关闭对话框了，以及ESC,和点击遮罩区域都无法关闭

**Comment by AlenQi** [comment]
@SkyLin0909 你需要将`formVisible`本地化，或者在`before-close`这个钩子里面修改`formVisible`的值
