### ISSUE TITLE
[Feature Request] El-Table support table auto layout without `table-layout:fixed`?

### ISSUE THREAD

**Issue by earlymeme** [ElemeFE/element#6056]
### Existing Component
是

### Component Name
El-Table

### Description
ElTable internal layout use the `table-layout:fixed` to implement. Is there any way to support internal table to use `table-layout:auto` css property. I had digged into the el-table source code ,and found that it required to define at least one column a width. Would you support me to define none width for the column , then the table fall back to table auto layout.

ElTable内部布局是使用table的fixed布局来实现的，有没有办法支持表格自动布局呢？我看内部实现必须至少定义一列宽度。如果我不给所有列定义宽度（最小宽度），让table就使用自动布局（交给浏览器去做），这样做可以吗？

**Comment by furybean** [comment]
Sorry, we have no plan to support this.
