### ISSUE TITLE
form label-width does not work for form-item without label

### ISSUE THREAD

**Issue by ray-guo** [ElemeFE/element#6059]
I noticed the recent changes about file "form-item.vue". There may be an error in the below inserted line: 

`if (!label && !this.labelWidth) return ret;`

I guess a condition "this.form.labelWidth" is forgotten, and so, it causes item style "margin-left" missing in the button line such as OK/Cancel/Submit buttons (without label property) , as a result, UI-layout is changed too. Therefore, I should check all the codes for above form-item and add label-width property for each of them. A big project, Eh?!

**Comment by jialuchun** [comment]
+1 遇到同样的问题 求解决方法

**Comment by Leopoldthecoder** [comment]
@ray-guo @jialuchun Will be fixed in 1.4.1
