### ISSUE TITLE
table表格如何正确获取当前row值

### ISSUE THREAD

**Issue by OYsun** [ElemeFE/element#606]
### 我在学习的时候遇到一个问题，就是table实现查删增改功能，通过inline-template添加操作按钮，但是如何正确把当前行的值传过来呢？
```html
        <el-table-column inline-template label="操作">
           <el-button-group>
             <el-button type="info" icon="edit" size="small"></el-button>
             <el-button type="danger" icon="delete" size="small" @click.native='deleteSelectTable(row)'></el-button>
           </el-button-group>
       </el-table-column>

```
```javascript
  methods: {
      deleteSelectTable(row){
        this.tableData.splice(row,1)
        // console.log(row);
      }
```
console.log(row)能打印出选中当前row的对象，但是无论点哪个都是删除第一行
```javascript·
methods: {
      deleteSelectTable(row){
          let index = this.tableData.indexOf(row)
          console.log(index);
      }
    }
```
点哪个按钮都是打印出-1，也就是按钮无法索引到当前行。(┬＿┬)
认真看了文档和其它issue #408  #562 没有找到答案
-----------------------------------
另外，能否在https://github.com/ElemeFE/element/blob/master/examples/docs/zh-cn/table.md
文档中写一个类似的小demo演示呢，毕竟表格查删增改功能是很常见的需求。

**Comment by furybean** [comment]
哪个版本？

**Comment by OYsun** [comment]
### ElementUI version
  "element-ui": "^1.0.0-rc.7",

### OS/Browers version
 macOS/Chrome 53 

### Vue version
  "vue": "^2.0.1"

@furybean

**Comment by furybean** [comment]
@OYsun 之前版本有个设计失误，把用户返回的数据改了。 master 里面的代码应该已经没这个问题了，rc8 我们应该会在周五发布。

**Comment by OYsun** [comment]
@furybean 刚才我把代码改成
```javascript
 methods: {
      deleteSelectTable(row){
        this.tableData.splice(row.id,1)
        // console.log(row);
      }
``
发现console可以打印出选中的row.id，但是点击按钮有时候可以删除当前row，有时候却失效了。这是为什么呢◔ ‸◔?

Reproduction Link

http://web-oysun.cn/Bug-repro/

Reproduction code

https://github.com/OYsun/Bug-repro/blob/gh-pages/index.html

**Comment by Smallpath** [comment]
+1

**Comment by furybean** [comment]
@OYsun 这个例子是因为你漏了一个 id 为 2 的记录，我试一下 indexOf 的问题。

**Comment by OYsun** [comment]
额，复制json数据粗心了，数据修正了，问题依然存在。

**Comment by saint3347** [comment]
![image](https://cloud.githubusercontent.com/assets/7347133/19669988/512ae7ec-9a96-11e6-98c8-f28bd61d086e.png)
我是根据自定义的name属性删除的，还是跟pagination组件一起用，可以成功删除

**Comment by saint3347** [comment]
版本是![image](https://cloud.githubusercontent.com/assets/7347133/19670041/ba72a2ee-9a96-11e6-9363-82915181456e.png)

**Comment by furybean** [comment]
@OYsun 这个是之前这一行导致的：https://github.com/ElemeFE/element/pull/363/files#diff-2464594c163d1fc8302357129290d3d2L378

这个问题已经修复，会在 rc8 发出。

**Comment by OYsun** [comment]
@furybean  :+1:  :rose:

**Comment by spademan** [comment]
估计 rc8之前只能给row中的obj做一个唯一表示，然后删除的时候 
遍历
```
handleDel(row) {
  tableData.map((item, index) => {
    if(item.id == row.id) {
       tableData.splice(index, 1)
    }
  }) 
}
````

**Comment by mqliutie** [comment]
`onRowClick` 能不能获取当前行的`index`啊

**Comment by loszer** [comment]
`scope.row.$index`
