### ISSUE TITLE
When [Bug Report] el-table adds border-radius, there is no overflow, and the arc edge is virtual

### ISSUE THREAD

**Issue by DanielWLam** [ElemeFE/element#6061]
### Element UI version
1.4.0

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/vs9853ut/](https://jsfiddle.net/vs9853ut/)

### Steps to reproduce
可看jsfiddle， 表格的右上角，左下角以及右下角均有发虚现象

### What is Expected?
正确的border-radius表现

### What is actually happening?
错误的border-radius表现

**Comment by BaffinLee** [comment]
# 说明

我可尝试解释这个问题，但我没有很好的解决方案

# 问题的原因

你看到的表格四边：
其中上边和左边是 `.el-table`控制的；
右边是`.el-table:after`控制的（stripe类型的表格每个`td` `th`也控制右边）；
下边是每个`td` `th`控制的

因为左上两边在同一元素上，左上角`border-radius`显示正常；
其余三角因边处于不同元素，`border-radius`显示不正常；

**Comment by Leopoldthecoder** [comment]
目前的实现不支持自定义圆角。
