### ISSUE TITLE
[Feature Request] Add prepend slot to table component

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#6063]
### Existing Component
Yes

### Component Name
Table

### Description
Sometimes it would be nice to have a prepend slot available for the table component so that you can have a row with input elements as cells to add data to the table. The prepended slot should be placed under the column headers, but before the actual data rows.

**Comment by simonbrunel** [comment]
That would also allow to display a progress bar when fetching data remotely, similar to [Vuetify data table `progress` slot](https://vuetifyjs.com/en/components/data-tables#examples), which, in some cases, fits better than the central spinner on white overlay.

![vuetify-table-loading-bar](https://user-images.githubusercontent.com/3874900/45929545-a074cc80-bf53-11e8-8529-11ae6dae83e7.gif)

**Comment by martincarles** [comment]
Any update on this issue ? That would be awesome to make every cell in the table dynamic.
