### ISSUE TITLE
el-select Selecting multiple values when :key is not value

### ISSUE THREAD

**Issue by vitaoloureiro** [ElemeFE/element#6065]
### Element UI version
1.4.0

### OS/Browsers version
Chrome 9.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/vitaoloureiro/8xsghcd0/](https://jsfiddle.net/vitaoloureiro/8xsghcd0/)

### Steps to reproduce
Lets say i have a object: [{value: 'item1',  label: 'Item 1'}, {value: 'item2',  label: 'Item 2'} ]
Using in a el-select works fine
<el-option v-for="item in options" :key="item.value" :label="item.label" :value="item">

But if my object doesn't have a 'value' key , when i select one item, i've got all options selected.
 [{id: 'item1',  label: 'Item 1'}, {id: 'item2',  label: 'Item 2'} ]
<el-option v-for="item in options" :key="item.id" :label="item.label" :value="item">

I've tried the value-key option but can't figure out where and how do i have to use.

### What is Expected?
A single select

### What is actually happening?
Multiple select

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/8xsghcd0/1/

Add it on `<el-select>` and set it to a key name.
