### ISSUE TITLE
The [Feature Request] date-picker/time-picker panel width is mandatory in line with the width of the input box

### ISSUE THREAD

**Issue by kevin70** [ElemeFE/element#6069]
### Existing Component
Yes

### Component Name
date-picke

### Description
date-picker/time-picker 面板宽度强制与输入框宽度一致
仔细找一下没有发现有相关可以修改的地方, 目前只能调整input本身的宽度
期望可以做成由用户选择(配置).
十分感谢!

**Comment by Leopoldthecoder** [comment]
并没有和输入框宽度一致，而是一个固定的宽度。不准备做成可配置的。

**Comment by kevin70** [comment]
@Leopoldthecoder https://jsfiddle.net/npv0856r/ 我写了一个示例. 你指的固定是指输入框的宽度是固定的, 而不是面板的宽度固定, 这点上我发现只有 element-ui 设计上是不一样的, 我期望可以调整 input 的宽度而不影响面板的美观.

**Comment by dragoncz** [comment]
@Leopoldthecoder 遇到了同样的问题。

如果手动调整了 DatePicker 输入框的宽度，比如设置为100%，从而和其它输入框保持一致并对齐：

```javascript
<el-date-picker type="datetimerange" placeholder="选择日期" style="width: 100%;">
</el-date-picker>
```

那么弹出来的选择面板宽度会跟随手动设定的宽度，导致很多情况下过宽而不美观。比如：

![screen shot 2017-12-20 at 3 47 10 pm](https://user-images.githubusercontent.com/375203/34196479-3fae186a-e59d-11e7-9a30-38bc67deb9cc.png)


希望能选择面板的宽度独立，不跟随 DatePicker 输入框的设定宽度变化。

**Comment by kid1412621** [comment]
不解为啥默认的宽度不同...这不是增加难度吗
