### ISSUE TITLE
NavMenu在router状态下，submune的menu item能跳转但不render

### ISSUE THREAD

**Issue by gyc1299339354** [ElemeFE/element#607]
### ElementUI version

1.0.0-rc.4
### OS/Browers version

macOS/Chrome 47
### Vue version

2.0.1

### What is actually happening?
如题~。~

**Comment by WangShayne** [comment]
目测路由配置错了

**Comment by jikkai** [comment]
能不能把错误信息之类的发一下？

**Comment by gyc1299339354** [comment]
@jikkai 木有报错，只是那个想要router的那个模块不出现

**Comment by gyc1299339354** [comment]
@WangShayne 目测对了~我直接改了自己之前定义好的路由配置，导致main.js中new Router给配置时候拿不到component......@_@
Thank you guys

**Comment by baiyaaaaa** [comment]
另外一点，为啥不适用最新版本233
