### ISSUE TITLE
 [Feature Request] Chinese input method with search input, not words will activate the search

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#6070]
### Element UI version
1.4.0

### OS/Browsers version
任何系统

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/8oc2ownk/](https://jsfiddle.net/8oc2ownk/)

### Steps to reproduce
使用中文输入法 输入【饿了么】，在未选择你好之前搜索框会进行搜索【e'le'me】。

### What is Expected?
不搜索输入法未选择之前的行为

### What is actually happening?
搜索错误

**Comment by BaffinLee** [comment]
我测试好像没问题，输入法选好了才触发

**Comment by Leopoldthecoder** [comment]
@An0nymous0 我试下来并没有这个问题，代码里也处理了这种情况。有问题的话请贴一下动图。

**Comment by csvwolf** [comment]
Long time no response. Closed the issue. Please reopen it or create a new issue if you have the same question now.
