### ISSUE TITLE
[Bug Report] Multiple NavMenus won't be reactive on same routes.

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#6075]
### Element UI version
0.1.0

### OS/Browsers version
macOS Sierra 10.12.5 / Chrome 59.0.3071.115

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
If there's multiple NavMenus in the page (typically a horizontal header and a vertical sidebar) with both in router mode, when click a menu-item on either, the other one won't be reactive - that means the relative menu-item won't be highlighted.

Say you click some "homepage" item with an index "/homepage" on the header, the one with that exact same index ("/homepage") on the sidebar won't be highlighted, as expected.

Note that my local project already uses vue-router and everything needed.

### What is Expected?
Menu items with same index/path in multiple navmenus with router mode, should be reactively highlighted when redirected.

### What is actually happening?
The opposite, obviously.

**Comment by baiyaaaaa** [comment]
Navmenu component  would not reactive with the router change itself, you should do that manual.
