### ISSUE TITLE
[Bug, Report], upload, disabled, bug

### ISSUE THREAD

**Issue by stanNo1** [ElemeFE/element#6079]
### Element UI version
1.4.0

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/stanzhou/jzfp0jzm/](https://jsfiddle.net/stanzhou/jzfp0jzm/)

### Steps to reproduce
N/A

### What is Expected?
disabled 时删除按钮不可见不可操作

### What is actually happening?
disabled 时删除按钮仍可见并可操作
list-type="picture-card"删除按钮倒是不可见不可操作

**Comment by Leopoldthecoder** [comment]
Fixed in #6091
