### ISSUE TITLE
Does the [Feature Request] table component support table-tree???

### ISSUE THREAD

**Issue by CoderONER** [ElemeFE/element#6081]
### Existing Component
是

### Component Name
table

### Description
  table组件支不支持table-tree 那种 展开 和 收起的功能～～～～   希望解答～～

**Comment by Leopoldthecoder** [comment]
不支持。

**Comment by CoderONER** [comment]
@Leopoldthecoder 可以用扩展的方法  或者自定义template的方法写吗 ？？？
