### ISSUE TITLE
[Feature Request] manually sets a tree node as the leaf node

### ISSUE THREAD

**Issue by fnll** [ElemeFE/element#6082]
### Existing Component
Yes

### Component Name
Tree

### Description
在 lazy 模式下，后端传回了 file 和 dir 两种类型节点。希望能手动的将类型为 file 的节点设置为叶子节点。

**Comment by Dreamacro** [comment]
可以在 `props` 里加入 `isLeaf` 属性，当 data 里包含 `isLeaf: true` 时，会被当做叶子节点

例子：https://jsfiddle.net/ba4jqfet/1/

**Comment by fnll** [comment]
`isLeaf`没问题。但在`props`里加入`showCheckBox`或者`show-checbox`属性，再通过`data`来控制是否展示`checkbox`似乎不行。

**Comment by Dreamacro** [comment]
@fnll 对的, 现在没办法做到同时具有 checkbox 和非 checkbox 的.

**Comment by minzheng1988** [comment]
@Dreamacro 用data来控制是否显示checkbox的需求，还是有的，不知道能否加支持一下
