### ISSUE TITLE
[Bug Report] dynamic binding on radio V-model

### ISSUE THREAD

**Issue by lllito** [ElemeFE/element#6084]
### Element UI version
1.4.0

### OS/Browsers version
MAC OS /Chrome

### Vue version
2.4.2

### Reproduction Link
[http://jsbin.com/caqidef/3/edit?html,css,js,console](http://jsbin.com/caqidef/3/edit?html,css,js,console)

### Steps to reproduce
http://jsbin.com/caqidef/3/edit?html,css,js,console

### What is Expected?
radio不能选中

### What is actually happening?
希望选中

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/xj1r8n96/ 需要 `$set` 一下。请阅读 https://vuejs.org/v2/guide/reactivity.html

**Comment by lllito** [comment]
大感谢 @Leopoldthecoder
