### ISSUE TITLE
[Bug Report] Form component cannot be verified in some case with requires type is `number`

### ISSUE THREAD

**Issue by hojas** [ElemeFE/element#6086]
### Element UI version
1.4.0

### OS/Browsers version
Chrome 59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/7vgcLLsr/](https://jsfiddle.net/7vgcLLsr/)

### Steps to reproduce
bind input data with an object's attribute, like: v-model="form.data"

### What is Expected?
input validation is working fine

### What is actually happening?
Vilidation always return error

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/7vgcLLsr/1/
