### ISSUE TITLE
Official examples of [Bug Report] el-checkbox are chrome, 44.0.2403.155m, and BUG

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#6092]
### Element UI version
1.4.0

### OS/Browsers version
windows chrome 44.0.2403.155m

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/LLxzgkc1/](https://jsfiddle.net/LLxzgkc1/)

### Steps to reproduce
el-checkbox  官方示例（indeterminate 状态）在chrome 44.0.2403.155m上，当上海，北京，广州，深圳四个全选后，上面的全选状态不会变。看着好像是反了

### What is Expected?
el-checkbox  官方示例（indeterminate 状态）在chrome 44.0.2403.155m上，当上海，北京，广州，深圳四个全选后，上面的全选状态不会变。看着好像是反了

### What is actually happening?
el-checkbox  官方示例（indeterminate 状态）在chrome 44.0.2403.155m上，当上海，北京，广州，深圳四个全选后，上面的全选状态显示正确

**Comment by Leopoldthecoder** [comment]
Chrome 44 有点老了，或许是浏览器自身的 bug。另外我们也不保证能完全兼容 Chrome 44。
