### ISSUE TITLE
[Bug Report] Should open the popover only if the trigger is still hovered

### ISSUE THREAD

**Issue by valerymelou** [ElemeFE/element#6100]
### Element UI version
1.4.0

### OS/Browsers version
Debian Testing

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/407/](https://jsfiddle.net/pj71jkyw/407/)

### Steps to reproduce
Create a popover that should open on hover with a big open delay like 1000ms.

Hover the trigger and put the mouse pointer anywhere else but on the trigger.

### What is Expected?
The popover should not after show after the delay, since the trigger is not hovered anymore.

### What is actually happening?
The popover is shown after the delay, even though the trigger is not hovered anymore.

**Comment by Leopoldthecoder** [comment]
Fixed in #6058
