### ISSUE TITLE
[Bug Report] cascader dynamically loads the secondary. After the last level is selected, the current value is re selected and the last level is retained

### ISSUE THREAD

**Issue by Caraws** [ElemeFE/element#6106]
### Element UI version
1.4.0

### OS/Browsers version
windows10/chrome

### Vue version
2.4.2

### Reproduction Link
[https://github.com/ElemeFE/element/issues/new](https://github.com/ElemeFE/element/issues/new)

### Steps to reproduce
1. change事件动态加载最后一级并选中

![img](http://orf90agxq.bkt.clouddn.com/GitHubQQ%E6%88%AA%E5%9B%BE20170727094652.png)
![img](http://orf90agxq.bkt.clouddn.com/GitHubQQ%E6%88%AA%E5%9B%BE20170727094720.png)

2. 重新选择

![img](http://orf90agxq.bkt.clouddn.com/GitHubQQ%E6%88%AA%E5%9B%BE20170727094739.png)
![img](http://orf90agxq.bkt.clouddn.com/GitHubQQ%E6%88%AA%E5%9B%BE20170727094802.png)

### What is Expected?
期望重新选择时能够获取到正确的当前值并正常动态加载

### What is actually happening?
获取到了上一次的最后一位当前值

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
