### ISSUE TITLE
[Bug Report] Tree Component check-strictly=true select parent node faild

### ISSUE THREAD

**Issue by k55k32** [ElemeFE/element#6109]
### Element UI version
1.4.0

### OS/Browsers version
Chrome 56

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/fxa075uL/](https://jsfiddle.net/fxa075uL/)

### Steps to reproduce
checked all children node except they parent.
then you can't select the parent node.

### What is Expected?
the parent node can be checked when i checked all children node

### What is actually happening?
the parent node can't be checked when i checked all children node

**Comment by Leopoldthecoder** [comment]
Fixed in #6034. Will be available this week.
