### ISSUE TITLE
The [Bug Report] select component is wider than the other input components in the inline form

### ISSUE THREAD

**Issue by stayfool** [ElemeFE/element#6110]
### Element UI version
1.4.0

### OS/Browsers version
win7, chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
使用一个select组件和一个input组件比较即可，select组件的宽度是217px,input组件是192px

### What is Expected?
select组件在表单中和其他input组件宽度一致

### What is actually happening?
select组件在表单中和其他input组件宽度不一致

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/qp8bc5qw/
默认情况下 Input 是撑满容器的。如果在你的页面上 Input 是 192 px，可以看看是不是被自定义样式影响到了（或者容器本身就是这么宽？）。如果有自定义样式，其实可以直接把它的宽度设为你想要的值。

**Comment by stayfool** [comment]
@Leopoldthecoder 没有任何自定义样式

**Comment by stayfool** [comment]
@element-bot  https://jsfiddle.net/skf4fhwu/

**Comment by stayfool** [comment]
@Leopoldthecoder 我是在INLINE表单里面
