### ISSUE TITLE
[Bug Report] NavMenu

### ISSUE THREAD

**Issue by 1578388951** [ElemeFE/element#6114]
### Element UI version
1.4.0

### OS/Browsers version
win7

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/8e62puu5/](https://jsfiddle.net/8e62puu5/)

### Steps to reproduce
点击导航

### What is Expected?
Can the child navigation navigation tower level 1 level down?

### What is actually happening?
You can only push it down

**Comment by Leopoldthecoder** [comment]
I don't quite understand this issue. Please be more specific. You can use Chinese if you prefer.

**Comment by DvJin** [comment]
I created a collapsable navMenu by following the Element UI document，but there was no effect. Who can guide me a little bit~~ 
<template>
  <div class="wrapper">
    
    <el-radio-group v-model="isCollapse" style="margin-bottom: 20px;">
      <el-radio-button :label="false">Open</el-radio-button>
      <el-radio-button :label="true">Close</el-radio-button>
    </el-radio-group>

    
    <el-menu class="el-menu-vertical-demo" :collapse="isCollapse">
      <el-submenu index="1">
        <template slot="title">
          <i class="el-icon-message"></i>
          <span slot="title">Menu One</span>
        </template>
        <el-menu-item-group>
          <span slot="title">Group One</span>
          <el-menu-item index="1-1">Opt 1</el-menu-item>
          <el-menu-item index="1-2">Opt 2</el-menu-item>
        </el-menu-item-group>
        <el-menu-item-group title="Group Two">
          <el-menu-item index="1-3">Opt 3</el-menu-item>
        </el-menu-item-group>
        <el-submenu index="1-4">
          <span slot="title">Opt 4</span>
          <el-menu-item index="1-4-1">Opt 4-1</el-menu-item>
        </el-submenu>
      </el-submenu>
      <el-menu-item index="2">
        <i class="el-icon-menu"></i>
        <span slot="title">Menu Two</span>
      </el-menu-item>
      <el-menu-item index="3">
        <i class="el-icon-setting"></i>
        <span slot="title">Menu Three</span>
      </el-menu-item>
    </el-menu>
</div>
</template>

<script>
  //import NProgress from 'nprogress'
  export default {
    data() {
      return {
        isCollapse: false
      };
    },
    methods: {
      handleOpen(key, keyPath) {
        console.log(key, keyPath);
      },
      handleClose(key, keyPath) {
        console.log(key, keyPath);
      }
    }
  }
</script>

**Comment by DvJin** [comment]
I has created a collapsable navMenu via following the Documents in ElementUI official website, but there was no effect. Did I code wrong or missed something?
```
<template>
  <div class="wrapper">
    <!-- CONTROLLER BTNs -->
    <el-radio-group v-model="isCollapse" style="margin-bottom: 20px;">
      <el-radio-button :label="false">Open</el-radio-button>
      <el-radio-button :label="true">Close</el-radio-button>
    </el-radio-group>

    <!-- MENUS -->
    <el-menu class="el-menu-vertical-demo" :collapse="isCollapse">
      <el-submenu index="1">
        <template slot="title">
          <i class="el-icon-message"></i>
          <span slot="title">Menu One</span>
        </template>
        <el-menu-item-group>
          <span slot="title">Group One</span>
          <el-menu-item index="1-1">Opt 1</el-menu-item>
          <el-menu-item index="1-2">Opt 2</el-menu-item>
        </el-menu-item-group>
        <el-menu-item-group title="Group Two">
          <el-menu-item index="1-3">Opt 3</el-menu-item>
        </el-menu-item-group>
        <el-submenu index="1-4">
          <span slot="title">Opt 4</span>
          <el-menu-item index="1-4-1">Opt 4-1</el-menu-item>
        </el-submenu>
      </el-submenu>
      <el-menu-item index="2">
        <i class="el-icon-menu"></i>
        <span slot="title">Menu Two</span>
      </el-menu-item>
      <el-menu-item index="3">
        <i class="el-icon-setting"></i>
        <span slot="title">Menu Three</span>
      </el-menu-item>
    </el-menu>
</div>
</template>

<script>
  //import NProgress from 'nprogress'
  export default {
    data() {
      return {
        isCollapse: false
      };
    },
    methods: {
      handleOpen(key, keyPath) {
        console.log(key, keyPath);
      },
      handleClose(key, keyPath) {
        console.log(key, keyPath);
      }
    }
  }
</script>
```
