### ISSUE TITLE
[Bug Report] a tree whose check-strictly is true cannot check the node whose children's checkboxs all disabled

### ISSUE THREAD

**Issue by aoiu** [ElemeFE/element#6118]
### Element UI version
1.4.0

### OS/Browsers version
WIN 7 / chrome 62

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/aoiu/pj71jkyw/410/](https://jsfiddle.net/aoiu/pj71jkyw/410/)

### Steps to reproduce
1. create a el-tree with prop check-strictly is true
2. a node in the tree whose children all cannot be checked
3. the parent node cannot be checked too

一棵遵循父子节点互不关联的树，某个节点的子节点全都disable了，那这个节点也无法被勾选了，期望是可以勾选的

### What is Expected?
the node in a 'check-strictly' tree whose children are all disabled can be checked

### What is actually happening?
the node in a 'check-strictly' tree whose children are all disabled cannot be checked

**Comment by mcdongWang** [comment]
当前节点的子节点都disabled, 那么就代表它没有被操作的意义啊

**Comment by aoiu** [comment]
已经设置了check-strictly说明父子节点没有严格关联，就算子节点都不能勾选，勾选父节点本身也是有意义的
