### ISSUE TITLE
[Feature Request] cascader support group list / cascade selector supports packet functionality

### ISSUE THREAD

**Issue by mcdongWang** [ElemeFE/element#6119]
### Existing Component
Yes

### Component Name
cascader

### Description
It is desirable to support the grouping function in the cascade selector component, similar to the selector
希望能在级联选择器组件中支持分组功能, 类似于选择器

**Comment by mcdongWang** [comment]
@Leopoldthecoder 

麻烦回复一下 这个需求是否在近期开发计划中

**Comment by mcdongWang** [comment]
我们现在的级联选择器 是实现了层级的概念 我觉得 层级 和 分组概念还是应该区分开的

举一个 实际需求的例子:

热门城市(组名)
    北京
    上海
全部城市(组名)
    中国
        河北
            石家庄

北京 在数据上 属于 三级 但是他想在第一级 显示
这个时候 层级 和 分组 的概念就可以区分开了
我的三级热门选择 提到了 一级去显示  那么 就需要用分组来区分开  去告诉用户 北京 上海 和 中国 不同级 只是在同一层展示而已

层级选项的拍平操作 在产品设计上 还是挺常见的

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
