### ISSUE TITLE
 可以增加个spin加载组件吗？

### ISSUE THREAD

**Issue by tolerious** [ElemeFE/element#612]
类似于这种的:
<img width="576" alt="2016-10-24 15 03 20" src="https://cloud.githubusercontent.com/assets/2922120/19636305/1a7f91b6-99fb-11e6-99e6-92c81a5abbc4.png">

**Comment by jikkai** [comment]
加载组件现在有[loading](http://element.eleme.io/#/component/loading)

**Comment by tolerious** [comment]
@jikkai  是的， 想要个那种转圈圈的loading，只能是自己改了咯、

**Comment by QingWei-Li** [comment]
那个就是个 icon 吧。。。

**Comment by Leopoldthecoder** [comment]
目前 Loading 里的不是 icon。Loading 的视觉后面会修改。

**Comment by tolerious** [comment]
OK

**Comment by Leopoldthecoder** [comment]
spin 组件应该不会加了。
