### ISSUE TITLE
[Feature Request] Vue component

### ISSUE THREAD

**Issue by LusenkoSasha** [ElemeFE/element#6120]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Why do not changes appear in the VUE components? I can remove the entire picker.vue and everything works as it worked. Why can not I add my class or date-type to the input?
![image](https://user-images.githubusercontent.com/27783985/28662067-80d13916-72c1-11e7-966d-72f2ca5151b3.png)

**Comment by Leopoldthecoder** [comment]
You're editing source file in node_modules. That's why.

You need to learn the basics of `npm`.

**Comment by LusenkoSasha** [comment]
And where do I need to edit to change the component vue?

**Comment by LusenkoSasha** [comment]
pllzzz
