### ISSUE TITLE
Does the allow-create property of the [Feature Request] el-select have a corresponding method to monitor the user's choice of the options that he created?

### ISSUE THREAD

**Issue by yobi-maggie** [ElemeFE/element#6122]
### Existing Component
Yes

### Component Name
el-select

### Description
rt  el-select  的allow-create属性有没有对应的方法可以监测用户选择的是自己创建的选项？

**Comment by yobi-maggie** [comment]
Does the allow-create property of the [Feature Request] el-select have a corresponding method to monitor the user's choice of the options that he created?

**Comment by Leopoldthecoder** [comment]
似乎在 change 回调里做个判断就可以？因为已有的 options 是可以访问到的。

**Comment by renxia** [comment]
@Leopoldthecoder 
change 的回调参数能不能在第二个参数返回 oldVal 呢
有时候需要对新的值和旧的值与其他条件作关联验证，这时候处理起来就很麻烦

**Comment by yobi-maggie** [comment]
@Leopoldthecoder   目前是用这个方法实现的
