### ISSUE TITLE
When [Bug Report] Dialog is nested with a custom component, $refs does not take the scope of the component

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#6123]
### Element UI version
1.4.0

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/411/](https://jsfiddle.net/pj71jkyw/411/)

### Steps to reproduce
如果第一次先点击 ‘点击测试’按钮，。浏览器不会弹出 ‘1’， 而如果先点击 ‘点击打开Dialog’后再点击 ‘点击测试’按钮，。浏览器会弹出 ‘1’。有什么办法可以解决这个问题吗？？？

### What is Expected?
Dialog 内嵌套一个自定义组件时$refs取不到组件的作用域

### What is actually happening?
Dialog 内嵌套一个自定义组件时无论打没打开过Dialog都能用$refs取到内嵌组件的作用域

**Comment by Leopoldthecoder** [comment]
和自定义组件无关。Dialog 的内容是懒加载的，在第一次打开之前，其内容不会被渲染。

**Comment by ChangeZhang** [comment]
@Leopoldthecoder 有办法能取消这个懒加载吗？？？

**Comment by Leopoldthecoder** [comment]
你的需求是什么？

**Comment by ChangeZhang** [comment]
@Leopoldthecoder Dialog内嵌套一个自定义组件时无论打没打开过Dialog都能用$refs取到内嵌组件的作用域

**Comment by ChangeZhang** [comment]
@Leopoldthecoder https://jsfiddle.net/pj71jkyw/411/ 我不打开Dialog 点击测试也能弹出1

**Comment by Leopoldthecoder** [comment]
我是说你的具体场景是什么，为什么需要在不打开  Dialog 的情况下获取内部组件。

**Comment by ChangeZhang** [comment]
因为我在Dialog内放了一个区域选择的组件，有回显，可删除。
![image](https://user-images.githubusercontent.com/6948367/28670992-b883b18a-730d-11e7-9a8e-e761ebaa66da.png)
当有回显值刷新进来时，这个时候我放在Dialog内组件没有渲染，所以找不到方法。当点击弹出一次Dialog后就一切正常，回显值和弹窗内的值能同步了。。。
不知道说清楚没。。。希望大神能帮我看看。谢谢了

**Comment by ChangeZhang** [comment]
晕~ 不能放GIF了？

**Comment by ChangeZhang** [comment]
![image](https://user-images.githubusercontent.com/6948367/28671155-3715b0d4-730e-11e7-8791-668022558be1.png)

**Comment by ChangeZhang** [comment]
[http://i4.eiimg.com/1949/e2a5c605edfdde2d.gif](url)

**Comment by ChangeZhang** [comment]
http://i4.eiimg.com/1949/e2a5c605edfdde2d.gif  大神打开这个链接看一下

**Comment by Leopoldthecoder** [comment]
在删除标签的时候不要立刻操作 Dialog 里的 Tree，而是在 Dialog 的 `open` 回调里做这件事。

**Comment by ChangeZhang** [comment]
好的，明白了，谢谢你

**Comment by xieerduos** [comment]
> 

+1

应该来个参数，取消懒渲染


场景：我隐藏一个dialog，里面有一些逻辑和外部组件逻辑强绑定，编辑的情况下，并不打开dialog，但是有没有渲染dom就很尴尬，获取不到值

**Comment by xieerduos** [comment]
根据源码，取消懒渲染方法如下：

```js
<template>
     <div>
          <el-dialog ref="dialog"></el-dialog>
     <div>
</template>

 mounted() {
  try {
            let dialogRef = this.$refs['dialog'];
            dialogRef.rendered = true;
            dialogRef.key++;
            dialogRef = null;
        } catch (error) {
            console.error(error);
        }
 
 }
```

**Comment by xieerduos** [comment]
> 根据源码，取消懒渲染方法如下：
> 
> ```js
> <template>
>      <div>
>           <el-dialog ref="dialog"></el-dialog>
>      <div>
> </template>
> 
>  mounted() {
>   try {
>             let dialogRef = this.$refs['dialog'];
>             dialogRef.rendered = true;
>             dialogRef.key++;
>             dialogRef = null;
>         } catch (error) {
>             console.error(error);
>         }
>  
>  }
> ```

![image](https://user-images.githubusercontent.com/35284871/187397899-7c57d096-88d9-4509-a048-86c6c42f5086.png)
