### ISSUE TITLE
[Bug Report] el-date-picker , I want to change the "type" attribute in the "shortcut" panel, I tried a lot of ways but that does not work, even error.

### ISSUE THREAD

**Issue by tianwang8090** [ElemeFE/element#6129]
### Element UI version
1.4.1

### OS/Browsers version
windows 10 /chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/5q05639j/3/](https://jsfiddle.net/5q05639j/3/)

### Steps to reproduce
click the date-picker,then click the shortcut panel to change the type of the picker, you'll see the error

### What is Expected?
change the type normally

### What is actually happening?
now it's wrong

**Comment by Leopoldthecoder** [comment]
`type` is not responsive. Use `v-if` instead.
