### ISSUE TITLE
select 组件如何设置默认值？

### ISSUE THREAD

**Issue by saint3347** [ElemeFE/element#613]
### Vue version

hello, 现在有这样一个需求，通过vue-router的param传递一个默认的值过来，但是elment的select组件好像没有提供默认取值的属性或者方法吧？请赐教。。

**Comment by jikkai** [comment]
把v-model的值改成传递过来的值就行了

**Comment by woodytang** [comment]
如果v-model 是在一个循环中 ，怎么改？
