### ISSUE TITLE
[Bug Report] form表单中的“数字类型验证”无法校验以数字开头的字符串

### ISSUE THREAD

**Issue by liqunx** [ElemeFE/element#6132]
### Element UI version
1.4.0

### OS/Browsers version
windows 10/Chrome

### Vue version
2.4.2

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/form](http://element.eleme.io/#/zh-CN/component/form)

### Steps to reproduce

* 在官网给出的demo即可重现，输入以数字开头的字符串，则可以跳过`type:"number"`的校验；

* 猜测原因：

    1.` v-model `处加上 `.number` 的修饰符实则是把字符串强转为数字`parseInt方法`再与model绑定

### What is Expected?
传入类似`111abcfoo`等字符串，应该判定为非数字类型，然后报错

### What is actually happening?
并无报错，直接跳过number验证

**Comment by smackgg** [comment]
你可以直接把 input 的 type 写成 number。这样就不会出现你的问题了。

**Comment by Leopoldthecoder** [comment]
#6681 3179

**Comment by jackcooper2015** [comment]
`<el-input type="number"  v-model.number="price"></el-input>` ， type='number'限制只能输入数字，v-model.number输入的字符串转number,很好的解决了这个问题
