### ISSUE TITLE
应用 popper的组件，在IE9下，当页面中有滚动条时，浮层的位置都不正确

### ISSUE THREAD

**Issue by wgq837051** [ElemeFE/element#614]
应用 popper的组件，在IE9下，当页面中有滚动条时，浮层的位置都不正确，如tooltip,select

**Comment by QingWei-Li** [comment]
可以截个动图么

**Comment by wgq837051** [comment]
滚动条不滚动 
![image](https://cloud.githubusercontent.com/assets/6071212/19638993/f213e142-9a08-11e6-9d7f-1ed86b7241cd.png)
滚动条，滚动 
![image](https://cloud.githubusercontent.com/assets/6071212/19639036/2c25d890-9a09-11e6-9e37-708f0f57adde.png)

**Comment by wgq837051** [comment]
官网的实例，IE9浏览器就能看到效果

**Comment by QingWei-Li** [comment]
你到开发版的官网上看看还有类似问题没 https://elementui.github.io/dev/#/component/select

**Comment by wgq837051** [comment]
还是有哦。

**Comment by QingWei-Li** [comment]
麻烦提供 gif 或者视频。我这边用 IE 11 仿真模式重现不了

**Comment by wgq837051** [comment]
![select2](https://cloud.githubusercontent.com/assets/6071212/19922502/d970fc44-a11d-11e6-8277-92bafd064889.png)
上图下拉选项框正确，页面滚动条没有滚动  
![select2](https://cloud.githubusercontent.com/assets/6071212/19922566/1fe17b36-a11e-11e6-8fa1-70cc27ef389c.png)
第二章图，页面滚动条滚动，下拉选项框就想上偏移一段位置显示了。

**Comment by wgq837051** [comment]
![select2](https://cloud.githubusercontent.com/assets/6071212/19922618/68ab394c-a11e-11e6-9fcb-95ed6752b91a.png)
上图下拉选项框正确，页面滚动条没有滚动
![select3](https://cloud.githubusercontent.com/assets/6071212/19922638/7f80779a-a11e-11e6-8d42-b1f8b2394dfe.png)
上图页面滚动向下滚动一段距离，下拉选项框的位置就向上移动了一段距离，显示就不正确了

**Comment by QingWei-Li** [comment]
这个是特性，为了尽可能保证弹出框在可视范围内，它会随着滚动条滚动调整自身位置

**Comment by wgq837051** [comment]
1. 上面的第二张图是我先滚动滚动条，在单击select的input，其下拉选项框位置就不正确了，这肯定不合理了，下拉选项框完全在input下面能显示，没必要调整自身位置
2. 在chorme中，调整下拉选项框的位置，也是要么在input下面，要么在input的上面，不能把input给盖住呀。

**Comment by baiyaaaaa** [comment]
#842

**Comment by Leopoldthecoder** [comment]
Fixed in #842

**Comment by Toxicant2** [comment]
问题解决了吗。我也遇见了
