### ISSUE TITLE
[Bug, Report], if, only, on, in, el-form, when, press, enter, on, el-input, will, submit, el-input, and, refresh, page

### ISSUE THREAD

**Issue by freefcw** [ElemeFE/element#6140]
### Element UI version
1.3.7

### OS/Browsers version
macOs 10.12 / Chrome 59

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/yk8hxu8d/1/](https://jsfiddle.net/yk8hxu8d/1/)

### Steps to reproduce
in this link, only one el-input in el-form

https://jsfiddle.net/yk8hxu8d/1/

press enter on input, will submit 

in this link:

https://jsfiddle.net/yk8hxu8d/

press enter on any input, won't submit anything

### What is Expected?
press enter on el-input when only one el-input in el-form, will not submit form 

在el-form中只有一个el-input的时候，在el-input里面按下enter，不会产生任何意外的行为，可以响应@keyup.enter.native事件

### What is actually happening?
press enter on el-input when only one el-input in el-form, will submit form 

在el-form中只有一个el-input的时候，在el-input里面按下enter，虽然响应了@keyup.enter.native事件，但表单提交了，影响整个事件

**Comment by freefcw** [comment]
FAQ里面，没有想要的解释，请给一个合理的解释

**Comment by Leopoldthecoder** [comment]
抱歉，命中了机器人的关键词被关闭了。我在你新开的 issue 里回复你。
