### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by Liupeng8** [ElemeFE/element#6145]
### Element UI version
1.4.1

### OS/Browsers version
win7/谷歌59

### Vue version
2.4.2

### Reproduction Link
[https://github.com/ryancui-/vue-transition-issue](https://github.com/ryancui-/vue-transition-issue)

### Steps to reproduce
npm
npm run dev
http://localhost:8080

### What is Expected?
不知是不是BUG，1.3版本正常，也尝试将vue版本升级到2.4.2，还是报错，我还试过在一个新的vue组件里直接放官方的demo代码，也是一样，只要一用el-menu就报错，另外奇怪的是，他报错但是使用没一点问题，请大神指点。

### What is actually happening?
[Vue warn]: Unknown custom element: <el-menu-collapse-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <ElMenu>
       <ElRow>
         <Index> at f:\schoolerp\src\renderer\components\main\Index.vue
           <AppMain> at f:\schoolerp\src\renderer\App_Main.vue
             <Root>
warn
(unknown) [Vue warn]: Unknown custom element: <el-menu-collapse-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <ElMenu>
       <MyIndex> at f:\schoolerp\src\renderer\components\mine\MyIndex.vue
         <ElTabPane>
           <ElTabs>
             <ElRow>
               <Index> at f:\schoolerp\src\renderer\components\main\Index.vue
                 <AppMain> at f:\schoolerp\src\renderer\App_Main.vue
                   <Root>

**Comment by Leopoldthecoder** [comment]
链接无效。

我本地新建项目试了一下，Vue 2.4.2 搭配 Element 1.4.1 不会出现这个问题。请在你的项目目录下执行 `npm ls vue` 和 `npm ls element-ui`，看看两者的版本对不对。

**Comment by Liupeng8** [comment]
@Leopoldthecoder 版本肯定是最新的，我再检查下吧，谢谢你
