### ISSUE TITLE
When the model in [Bug Report] select is empty, the option with the median option of 0 is selected

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#6147]
### Element UI version
1.4.1

### OS/Browsers version
windows 10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/z8435og7/](https://jsfiddle.net/z8435og7/)

### Steps to reproduce
初始打开复现链接，即可

### What is Expected?
null的时候，为未选中状态

### What is actually happening?
null的值被指向了选项中value等于0的项

**Comment by lerit** [comment]
it work fine in version 1.3.7

**Comment by wacky6** [comment]
@lerit replace `null` with `''`

@Leopoldthecoder does this have something to do with the newly added `value-key` feature?

**Comment by Leopoldthecoder** [comment]
@wacky6 Yes. I'm on it.

**Comment by Leopoldthecoder** [comment]
Fixed in #6143
