### ISSUE TITLE
The [Bug Report] NavMenu menu shows half Chinese when it is retracted and then completely retracted

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#6152]
### Element UI version
1.4.1

### OS/Browsers version
osx

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/veghwzvd/](https://jsfiddle.net/veghwzvd/)

### Steps to reproduce
来回点击收起和展开就会发现样式有些问题。

### What is Expected?
完美收起

### What is actually happening?
先显示一半文字

**Comment by Leopoldthecoder** [comment]
Fixed in #6153
