### ISSUE TITLE
In [Bug Report] webpack mode, the el-menu nested el-col at the upper level causes the menu link to fail

### ISSUE THREAD

**Issue by zhxluo** [ElemeFE/element#6156]
### Element UI version
1.4.1

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[http://jsfiddle.net/aoo5vjvt/](http://jsfiddle.net/aoo5vjvt/)

### Steps to reproduce
如http://jsfiddle.net/aoo5vjvt/
中代码所示，类似的代码使用webpack方式实现，el-col中的菜单链接不可点击

### What is Expected?
el-col中的菜单链接可点击

### What is actually happening?
el-col中的菜单链接不可点击

**Comment by Leopoldthecoder** [comment]
请把可复现 bug 的项目放到 GitHub 上，我们看看。

**Comment by zhxluo** [comment]
https://github.com/zhxluo/bugreport

**Comment by Leopoldthecoder** [comment]
`el-col` 需要包裹在 `el-row` 里。
