### ISSUE TITLE
[Bug Report] When table fixed columns and aggregate rows exist at the same time, the height of the fixed region is inconsistent with the table height

### ISSUE THREAD

**Issue by Esa-i** [ElemeFE/element#6157]
### Element UI version
1.4.1

### OS/Browsers version
win7/chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/5rpjsak7/](https://jsfiddle.net/5rpjsak7/)

2.1.0：https://jsfiddle.net/5rpjsak7/1/

### Steps to reproduce
打开链接即可重现

### What is Expected?
固定区域与表格区域展示协调

### What is actually happening?
固定区域高度与表格高度不一致，导致展示不协调

**Comment by singone** [comment]
存在相同的问题， 固定的列和其他列高度不一致

**Comment by chendayang** [comment]
i have this problem too

**Comment by ceciliaY** [comment]
不知道是否能帮助到你，但我在遇到这个问题的时候是这么解决的：给这个table一个自定义的class,通过DOM查看固定列的class name ,然后用deep属性就可以覆盖fixed属性的内联样式，使用自定义的样式解决这个问题了。

**Comment by huhongliang** [comment]
固定列其实是浮在上层的另一个表格，把表格外层包裹的div定位bottom值改成0，我是通过外部import导入样式文件强改的，
.el-table__fixed-right{
    bottom:0px !important;
}
我看到@furybean给了一个例子 https://jsfiddle.net/mwk2d3yh/4/   但是用到我的文件上还是老样子 调试发现例子bottom也是0，样式是可以看了不过滚动条滑到固定列的地方在点击无法滑动，因为固定列层级不一样
