### ISSUE TITLE
menu-item的route 跳转逻辑错误

### ISSUE THREAD

**Issue by leonwa** [ElemeFE/element#616]
### ElementUI version
 1.0.0-rc.2 

### Vue version
2.0.0-rc.4

### Steps to reproduce
定义el-menu-item， 定义了route对象
`<el-menu-item v-else :index="menu.id" :route="menu" >`
点击菜单
### What is Expected?
点击是应该跳转
### What is actually happening?
并没跳转
看了一下代码，
menu.vue -> handleSelect(index, indexPath, route)  跳转前检查了 this.router 对象， 实际应为 this.$router

**Comment by baiyaaaaa** [comment]
请使用最新版本

**Comment by leonwa** [comment]
说的就是你们现在的源码， 看看这里element/packages/menu/src/menu.vue

**Comment by leonwa** [comment]
```
      handleSelect(index, indexPath, route, instance) {
        this.activeIndex = index;
        this.$emit('select', index, indexPath, instance);
        if (this.mode === 'horizontal') {
          this.broadcast('submenu', 'item-select', [index, indexPath]);
          this.openedMenus = [];
        } else {
          this.openActiveItemMenus();
        }
        if (this.router && route) {
          this.$router.push(route);
        }
      },
```

注意 这段， this.router应该是this.$router
        if (this.router && route) {
          this.$router.push(route);
        }

**Comment by baiyaaaaa** [comment]
@leonwa  this.router 指的是组件是否开启了 router 模式而不是判断是否有使用 vue-router ，不过这里确实应该加一个控制台警告，感谢
