### ISSUE TITLE
Can the [Feature Request] DatePicker date picker set multiple non optional date ranges?

### ISSUE THREAD

**Issue by hasbug** [ElemeFE/element#6160]
### Existing Component
是

### Component Name
DatePicker 

### Description
我的需求有点坑，选择时间范围并设置价格，可以设置很多个时间段再给后端一起提交。
这时候，我如果第一次选择了2017/04/01-2017/05/02   ，然后第二次选择的时候，我希望这个已经选过的时间不可选，第三次一样，曾经选择过的时间都使用disabledDate来设置其不可选，可以实现吗？  求助，谢谢。

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
