### ISSUE TITLE
[Bug Report] input:textarea autosize cannot be displayed properly

### ISSUE THREAD

**Issue by xinx1n** [ElemeFE/element#6162]
### Element UI version
1.4.1

### OS/Browsers version
macOS chrome 

### Vue version
2.4.2

### Reproduction Link
[http://output.jsbin.com/vazuqaq/1](http://output.jsbin.com/vazuqaq/1)

### Steps to reproduce
input 组件，设置 autosize，v-show=false，默认有内容
那么在用 v-show 改为 true 的时候，input 显示了，但是并没有 autosize，
我现在暂时改用 v-if 了，但是我的实际中是 tab 的切换，用 v-if 明显不太合适，
希望能解决这个问题

### What is Expected?
能正确 autosize

### What is actually happening?
不能 autosize，而是会出现滚动，只有改变 textarea 内容的时候才会 autosize

**Comment by alongchengtian0** [comment]
Version 0.1.0 ?

**Comment by xinx1n** [comment]
已修改 element-ui version，issue-generator 的版本只有一个 0.1.0，生成以后我忘记修改了……

**Comment by qingdengyue** [comment]
1.为 input type=textarea 增加ref。比如ref='userInfo'
2.在v-show的值发生变化时，调用this.$refs.userInfo.resizeTextarea()

**Comment by Leopoldthecoder** [comment]
@xinx1n 参照楼上处理。

因为当 `v-show` 隐藏时，实际上 textarea 多了一条 `display: none`，此时通过 JS 是无法知道它的宽和高的。

**Comment by jiaoHsiung** [comment]
@qingdengyue 我现在遇到一种情况：textarea用了autoresize的时候，textarea的高度有3000多px，但我重新改变textarea的内容后（内容一致），高度又变成了100多px，用你的方法是管用的，但是我想知道为什么这个高度是3000多px，改变后相差太多。
