### ISSUE TITLE
The [Bug Report] multilevel header controls the column rendering when it is rendered wrong

### ISSUE THREAD

**Issue by lavyun** [ElemeFE/element#6163]
### Element UI version
1.4.1

### OS/Browsers version
windows 10 / chrome 58 

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/xne5gkdh/1/](https://jsfiddle.net/xne5gkdh/1/)

### Steps to reproduce
通过控制数据条件渲染含多级表头的表格columns就会有问题

### What is Expected?
通过控制数据能正常的条件渲染含多级表头的表格columns

### What is actually happening?
通过控制数据不能正常的条件渲染含多级表头的表格columns

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/xne5gkdh/4/
牵扯到动态显示隐藏的，建议给 el-table-column 或 el-table 加上 key。例子中的 Math.random() 只是为了说明效果，实际使用任何唯一性的值都行。
