### ISSUE TITLE
[Bug Report] el-select with  disabled and multiple setting,remove item icon still display

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#6164]
### Element UI version
1.4.1

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/3cjk7ezh/](https://jsfiddle.net/3cjk7ezh/)

### Steps to reproduce
open the Reproduction Link,the bug will show immediately

### What is Expected?
el-select with  disabled and multiple setting,do not display remove item icon

### What is actually happening?
the remove item icon still display

**Comment by Leopoldthecoder** [comment]
Fixed in #6143.
