### ISSUE TITLE
[Feature, Request], autocomplete, can't, set, the, Input, props,, maxLength, and, minLength

### ISSUE THREAD

**Issue by singone** [ElemeFE/element#6170]
### Existing Component
Yes

### Component Name
autocomplete

### Description
autocomplete 不能设置maxlength 和minlength。

**Comment by lbineau** [comment]
Any news about this issue?

**Comment by chenyiqiao** [comment]
need it @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
Supported in https://github.com/ElemeFE/element/pull/8859
