### ISSUE TITLE
[Bug Report] programming mode, set the value of el-switch can not be synchronized to its generated HTML form input control

### ISSUE THREAD

**Issue by zxz054321** [ElemeFE/element#6176]
### Element UI version
1.4.1

### OS/Browsers version
Ubuntu 16.04 /  Firefox 54.0

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/zj3tt3o0/2/](https://jsfiddle.net/zj3tt3o0/2/)

### Steps to reproduce

1. 页面加载完成，data函数中this.form.delivery的初始值是为false；
2. mounted()函数中将this.form.delivery更改为true，更改有反映到UI上；
3. 点击按钮提交表单。

### What is Expected?
el-switch所生成的checkbox input的值应为on

### What is actually happening?
el-switch所生成的checkbox input的值并没有同步更新为on，其值只有通过鼠标点击才会更新到input上

**Comment by Leopoldthecoder** [comment]
为何要去取 input 的值？

**Comment by zxz054321** [comment]
@Leopoldthecoder 在做SPA的时候大家会在vue中用axios之类的库跟API通讯，此时这个bug无影响。但如果vue仅仅负责view渲染，表单依旧采用传统的form GET/POST跳转提交到服务端，input的值就很重要了。

**Comment by openks** [comment]
@zxz054321 我刚看了下你的demo试了下 可以取到值 且为on啊
我直接打开页面搜索`el-switch__input`找到这个对象 添加id
然后根据id 获取对象查看值为on
下载源代码到本地，服务器打开查看值也是on
![image](https://user-images.githubusercontent.com/4387721/28807269-3c64125e-763a-11e7-9352-34de1e1c709f.png)

**Comment by zxz054321** [comment]
@openks JS输出有值不等于HTTP请求里有，抓包HTTP请求：

A 直接点击按钮而不点el-switch，HTTP请求参数里没有delivery
![image](https://user-images.githubusercontent.com/7540550/28807524-92b38dba-76a8-11e7-8641-321dddc567da.png)

B 点击两次el-switch使其关闭再开启，再点击按钮提交表单，HTTP请求参数里才有delivery
![image](https://user-images.githubusercontent.com/7540550/28807570-c7fd628e-76a8-11e7-8df8-ec743f93ae71.png)

**Comment by wacky6** [comment]
input checkbox 应该用 `checked` 而不是value

**Comment by openks** [comment]
@zxz054321  可能跟这个 #6011 有关

**Comment by zxz054321** [comment]
@wacky6 是的，但是通过js设置model值时，el-switch不会将更改同步到checked属性上，目前只能手动 `this.$refs.switch.$el.getElementsByTagName('input')[0].checked=true`

**Comment by wacky6** [comment]
修复PR https://github.com/ElemeFE/element/pull/6205
