### ISSUE TITLE
The [Feature Request] $msgbox $prompt supports multiple input boxes

### ISSUE THREAD

**Issue by jslixiaolin** [ElemeFE/element#6182]
### Existing Component
Yes

### Component Name
MessageBox

### Description
现有的$prompt只能在弹窗中显示一项输入(email)，有什么办法能够显示多项输入，如在弹窗中让用户输入：邮箱、姓名，并且邮箱支持正则验证

**Comment by wacky6** [comment]
You should write your own el-dialog for this kind of work.
