### ISSUE TITLE
[Bug Report] the el-table width become wider and wider

### ISSUE THREAD

**Issue by Clmystes** [ElemeFE/element#6184]
### Element UI version
1.4.0

### OS/Browsers version
  window 10 / Chrome 58 In some notebooks ( Known: acer ) 

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
1. create a el-table
2. use min-width or do not fix width of the column
3. do not fix  the wrapper element's width
4. the el-table width will become wider and wider, cause the scroll bar
> in this issue(https://github.com/ElemeFE/element/issues/1196), the last person to comment maybe have the problem also

### What is Expected?
the table should have suitable width in the screen and do not cause the scroll bar

### What is actually happening?
cause the scroll bar

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by zhuyunhe** [comment]
这样问题有解决方法啊，经常出现啊

**Comment by allenwelsh** [comment]
i do well work when i delete border props

**Comment by grasshopperL** [comment]
> 这个问题有解决方法啊，经常出现啊

How to deal with it

**Comment by grasshopperL** [comment]
> 这个问题有解决方法啊，经常出现啊

emmm, How to deal with it

**Comment by davestewart** [comment]
We just got the same issue.

It appears that some kind of JS is updating the `style.width` and the table animates wider and wider forever!

**Comment by davestewart** [comment]
The issue happened to us when an Element UI table was in a non-Element UI layout.

We fixed the issue by using Element UI `el-row` and `el-col`.

**Comment by ftom2** [comment]
We are still experiencing this issue, wrapping it in `el-row` does not help :(

**Comment by davestewart** [comment]
@ftom2 did you try `el-row` **and** `el-col` together ?

**Comment by ftom2** [comment]
@davestewart yes, it didn't help. Eventually I created a directive that calculates the parent width and applies it to the table, but it's hacky.

Another solution we found is to give the table a width of 99%, but that might not fit all cases.
It's a weird bug.
