### ISSUE TITLE
el-time-picker select value error: TypeError: value.getTime is not a function

### ISSUE THREAD

**Issue by wangwei123** [ElemeFE/element#6185]
el-time-picker select value error: TypeError: value.getTime is not a function

**Comment by yanlee26** [comment]
what???

**Comment by webspilka** [comment]
I have same problem when use vuex store and save store to localstore

```js
typeof $vm0.$store.state.steps.form.passport.date // get "object"

// but after save state to localstorage and load it from there, I get

typeof $vm0.$store.state.steps.form.passport.date // get 'string'

```

I fixit with 
```js
passportDate: {
        get () {
          var storeDate = this.$store.state.steps.form.passport.date;
          if (storeDate) {
            // if !empty string
            return new Date(storeDate);
          }else{
            // if empty string
            return '';
          }
        },
}
```

**Comment by wacky6** [comment]
This is a recurring issue. Please refer to [Date Formats](http://element.eleme.io/#/en-US/component/date-picker#date-formats) section.

In short, if you want to use string to store date, you must specify `value-format`. Also, `localStorage` and `sessionStorage` [**always store strings**](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem)
