### ISSUE TITLE
[Feature Request] Dynamic commands on dropdown items

### ISSUE THREAD

**Issue by mayakokits** [ElemeFE/element#6186]
### Existing Component
Yes

### Component Name
Dropdown

### Description
I need multiple dropdowns inside a `v-for` list, each of them containing a *Duplicate* and a *Remove* action. So I need to be able to pass the action type as well as the list index to the handler, like:
```
<ul>
  <li v-for="(item, $index) in items">
    {{ item.name }}
    <el-dropdown split-button @click="editItem($index)" @command="handleAction">
      Edit
      <el-dropdown-menu slot="dropdown">
        <el-dropdown-item :command="{action: 'duplicateItem', index: $index}">Duplicate</el-dropdown-item>
        <el-dropdown-item :command="{action: 'removeItem', index: $index}">Delete</el-dropdown-item>
      </el-dropdown-menu>
    </el-dropdown>
  </li>
</ul>
```
At the moment, this is impossible because the `command` prop expects a string.
If I could just use a click handler on the dropdown item I would simply do something like `@click="duplicateItem($index)"`.
Please enable this important functionality either one way or the other!

**Comment by Leopoldthecoder** [comment]
Actually you can use the click event:
```html
<el-dropdown-item @click.native="duplicateItem($index)">Duplicate</el-dropdown-item>
```

The `.native` is required. More info can be found in [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) and Vue [docs](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components).

**Comment by mayakokits** [comment]
cool, thanks! didn't know this :-)
