### ISSUE TITLE
[Feature Request] Create an element for links

### ISSUE THREAD

**Issue by jmaister** [ElemeFE/element#6187]
### Existing Component
No

### Component Name
el-link

### Description
Create an element for links to get consistent styling for the A elements.

**Comment by Leopoldthecoder** [comment]
We may not add a component just to style the `<a>` element, but we do have a resetting CSS included: https://unpkg.com/element-ui@1.4.1/lib/theme-default/reset.css

**Comment by jmaister** [comment]
So, how can I get a consistent styling with the rest of elements?

![image](https://user-images.githubusercontent.com/374021/28844002-210fb76c-76fb-11e7-8321-ceaff516a1a0.png)
