### ISSUE TITLE
[Feature Request] The Form do not provide the input type of the file upload， Will you consider adding this feature?

### ISSUE THREAD

**Issue by niices** [ElemeFE/element#6188]
### Existing Component
是

### Component Name
Form

### Description
The  Form do not provide a file upload type input tag， Will you consider adding this feature?
Form表单没有提供file上传类型的input标签，会考虑开发吗？

**Comment by niices** [comment]
![image](https://user-images.githubusercontent.com/8327775/28805359-1312db3a-769c-11e7-9f0e-f7d98816f5fe.png)

**Comment by Leopoldthecoder** [comment]
请使用 Upload 组件。Input 组件不会对 `type="file"` 提供额外的支持了，虽然现在可以这么用。
