### ISSUE TITLE
[Bug Report] Property or method "resetForm" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by gimyboya** [ElemeFE/element#6190]
### Element UI version
1.4.1

### OS/Browsers version
Microsoft Windows [Version 10.0.15063] / Version 60.0.3089.0 (Developer Build) (32-bit)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/gimyboya/pj71jkyw/419/](https://jsfiddle.net/gimyboya/pj71jkyw/419/)

### Steps to reproduce
file the form or don't (up to you)
click on reset button

### What is Expected?
form reset

### What is actually happening?
form don't reset and it throws an error to the console
Property or method "resetForm" is not defined on the instance but referenced during render.

**Comment by Leopoldthecoder** [comment]
Because you don't have `resetForm` in your `methods`. Please read Vue docs first.
