### ISSUE TITLE
[Feature Request] make el-table's sort-method's implementation consistent with Array.sort

### ISSUE THREAD

**Issue by francisfeng** [ElemeFE/element#6191]
### Existing Component
Yes

### Component Name
el-table

### Description
The `sort-method` is implemented with `Array.sort`, but not the same. While `Array.sort`'s `compareFunction` return `-1`, `0` and `1`, the `sort-method` simply return `true` or `false`. 

It's perfectly fine when you use it to sort an array with not duplicate keys.

But it would cause an unstable sorting result when you use it to sort an array which may have the same sorting key.

For a broader scenery, I think `sort-method` should be consistent with `Array.sort`.

**Comment by Leopoldthecoder** [comment]
This will be considered in the next major version. #6444

**Comment by leeqqiang** [comment]
不支持0 排好顺序放进去 显示的好崩溃
