### ISSUE TITLE
[Bug Report] el-table

### ISSUE THREAD

**Issue by believeZJP** [ElemeFE/element#6196]
### Element UI version
1.4.1

### OS/Browsers version
any

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/believezjp/e09ddxum/](https://jsfiddle.net/believezjp/e09ddxum/)

### Steps to reproduce
when created a table ,default set a row highlight.
but it not worked.

### What is Expected?
a row is selected default

### What is actually happening?
nothing selected.

**Comment by Leopoldthecoder** [comment]
Use `mounted` instead of `created`. Please refer to Vue docs for their differences.

**Comment by believeZJP** [comment]
thank you very much~~~
