### ISSUE TITLE
[Bug Report] Button doesn't work in table expand mode

### ISSUE THREAD

**Issue by wayne-chan** [ElemeFE/element#6197]
### Element UI version
1.4.1

### OS/Browsers version
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/6tqah66x/2/](https://jsfiddle.net/6tqah66x/2/)

### Steps to reproduce
add a button in table expand area, bind click event with the button

### What is Expected?
click event will be triggered

### What is actually happening?
click event doesn't trigger

**Comment by Leopoldthecoder** [comment]
Replace `@clicked` with `@click`.
