### ISSUE TITLE
入门文档是不是漏了什么步骤？报错不能运行了。

### ISSUE THREAD

**Issue by diguage** [ElemeFE/element#620]
按照这个教程 <http://element.eleme.io/#/component/quickstart> 来做，还是整出来一些问题：

```
ERROR in ./~/element-ui/lib/theme-default/index.css
Module parse failed: /Path/to/vuejs-simple-demos/node_modules/element-ui/lib/theme-default/index.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
```

请问，文档中，是不是漏了一些什么步骤？

我的项目：<https://github.com/diguage/vuejs-simple-demos>

**Comment by Leopoldthecoder** [comment]
请参考 FAQ 的第四条。

**Comment by akaylh** [comment]
1、安装bootstrap
2、安装style-loader
3、在webpack.config.js中加入      { test: /\.css$/, loader: "style!css" },

**Comment by diguage** [comment]
@Leopoldthecoder  既然都知道这是个坑了，为啥不修正一下文档呢？很明显，修正一下文档就能解决的问题，为啥还要让大家查来查去呢？

**Comment by furybean** [comment]
@diguage 快速入门目前是不够全面，我们近期会更新，多谢建议。

**Comment by diguage** [comment]
@furybean 我们公司最近要上Vue.js，是不是使用这个UI库还不确定。祝你们发展的越来越好！

**Comment by fengqijie** [comment]
@diguage 您好，请问您是怎么解决这个问题的，我也遇到了这个问题
