### ISSUE TITLE
[Bug Report] tooltip slot cannot include el-button-group?

### ISSUE THREAD

**Issue by agileago** [ElemeFE/element#6203]
### Element UI version
1.4.1

### OS/Browsers version
Mac OS X 10_12_5/Chrome/59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/agileago/pz1aL8vc/](https://jsfiddle.net/agileago/pz1aL8vc/)

### Steps to reproduce
tooltip内容包含el-button-group组件就会引起vue报警告
```
You may have an infinite update loop in a component render function.

found in

---> <ElButtonGroup>
       <Root>
```
但把 el-button-group换成 <div class="el-button-group"></div> 就没问题, 难道tooltip不支持自定义组件嵌套？

### What is Expected?
tooltip不会报循环的警告

### What is actually happening?
tootip会引起警告

**Comment by Leopoldthecoder** [comment]
Tooltip 里不应该放带有交互的内容，它仅用来展示一段文字提示。这个需求应该用 Popover：https://jsfiddle.net/pz1aL8vc/2/
