### ISSUE TITLE
input DatePicker 等组件，在初始化时，如何才能不触发change事件呢？

### ISSUE THREAD

**Issue by wangdongwu** [ElemeFE/element#6206]

**Comment by wacky6** [comment]
https://github.com/ElemeFE/element/issues/6011

**Comment by wangdongwu** [comment]
@wacky6  通过prop传过来的默认数据，希望不触发change事件，而在用户真实选择时间时才触发change，这种场景怎么解决呢

**Comment by wangdongwu** [comment]
<date-picker
                            v-model="detail.gmtStart"
                            type="datetime"
                            align="right"
                            @change="updateApp"
                            placeholder="选择上线时间">
                    >
                </date-picker>比如这样，初始化值，希望不触发change

**Comment by wacky6** [comment]
下个大版本应该会解决。
现在解决的话要监听内部面板的 pick 事件。

**Comment by wangdongwu** [comment]
@wacky6  怎么监控到呢？目前只暴露了change事件

**Comment by wangdongwu** [comment]
` <date-picker
                            v-model="detail.gmtStart"
                            type="datetime"
                            align="right"
                            @change="updateApp"
                            @pick="pickchange"
                            placeholder="选择上线时间">
                    >
                </date-picker>`这样监控不到

**Comment by wacky6** [comment]
date-picker 的 picker 的 pick事件，不急着用或者可以接受替代方案的话，建议等大版本吧。

**Comment by baiducctv5** [comment]
@wacky6 2.0是不是也没更新进来。
目前项目用到了 select 的远程搜索，也出现了赋值过程中触发 change 的问题
麻烦问一下，有何规避这个问题的方案建议么？

**Comment by Leopoldthecoder** [comment]
@baiducctv5 有问题请提供 demo。

**Comment by MissCuriosity** [comment]
这个问题解决了吗
