### ISSUE TITLE
[Bug Report] highlight-current-row highlight the wrong row

### ISSUE THREAD

**Issue by chhpt** [ElemeFE/element#6211]
### Element UI version
1.4.0

### OS/Browsers version
macOS 10.12.6/Chrome 59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/chhpt/p9z1a5cb/1/](https://jsfiddle.net/chhpt/p9z1a5cb/1/)

### Steps to reproduce
click the row of the table, after some clicks, it will highlight the wrong row

### What is Expected?
Explain the wrong reason. I think it may because that I generate some same objects with the same dep.id, but I'm not sure and I don't exactly understand the reason. How cloud I fix it.

### What is actually happening?
explain the reason

**Comment by Leopoldthecoder** [comment]
Before being pushed to `fileList`, the object needs to be copied so that elements in `fileList` are referring to different objects: https://jsfiddle.net/p9z1a5cb/2/
