### ISSUE TITLE
[Bug Report] el-input-number change event always get the last time value.an

### ISSUE THREAD

**Issue by believeZJP** [ElemeFE/element#6213]
### Element UI version
1.4.1

### OS/Browsers version
any

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/believezjp/6tLnvtvz/1/](https://jsfiddle.net/believezjp/6tLnvtvz/1/)

### Steps to reproduce
click the plus btn,
but the total is still 0,when click next time,total last time value.

### What is Expected?
get the correct total.

### What is actually happening?
click the plus btn,
but the total is still 0,when click next time,total last time value.

**Comment by wacky6** [comment]
change is emitted before vue instance data update.

**Comment by believeZJP** [comment]
how can I get the correct result? thanks for your reply.

**Comment by Leopoldthecoder** [comment]
Wrap the event handler inside `$nextTick`: https://jsfiddle.net/6tLnvtvz/2/ .

**Comment by Cuilz** [comment]
@wacky6 why design this way.  el-input, el-select etc change event is emiited after vue instance data update.

**Comment by wacky6** [comment]
@Leopoldthecoder See @Cuilz 's comment.

I played with native input, in change event, the modified value can be retrieved.

https://jsfiddle.net/7n035m3x/2/

**Comment by Leopoldthecoder** [comment]
@wacky6 Looks like InputNumber is an exception because Input and Select are acting correctly:
- Input https://jsfiddle.net/awnamjbh/
- Select https://jsfiddle.net/1vsqne9b/

Actually in InputNumber, the order of `input` and `change` events should be reversed. Now they are
```JS
this.$emit('change', newVal, oldVal);
this.$emit('input', newVal);
```
I'll fix it.

**Comment by kinqsley** [comment]
Any update on this?
