### ISSUE TITLE
<el-input-number> doesn't bind name attribute to the generated <input>

### ISSUE THREAD

**Issue by zxz054321** [ElemeFE/element#6215]
### Element UI version
1.4.1

### OS/Browsers version
Ubuntu 16.04 /  Firefox 54.0

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/0cparv8h/1/](https://jsfiddle.net/0cparv8h/1/)

### Steps to reproduce

1. Set the `name` attribute of `<el-input-number>` to `interval`
2. Click `<el-button>` to submit the form

### What is Expected?

- The `name` attribute of the `<input>` generated by `<el-input-number>` is `interval`
- The `name` parameter should be included in the HTTP request body

### What is actually happening?

- The `name` attribute of the `div.el-input-number` is `interval`
- There is no `name` parameter in the HTTP request body

**Comment by Leopoldthecoder** [comment]
Fixed in #6042
