### ISSUE TITLE
The [Bug Report] select component does not display correctly when value is the option of number 0

### ISSUE THREAD

**Issue by ZHocean123** [ElemeFE/element#6220]
### Element UI version
1.4.1

### OS/Browsers version
MacOS 10.12.6／chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/oLn53ahx/](https://jsfiddle.net/oLn53ahx/)

### Steps to reproduce
1.select的v-model为null或者undefined
2.存在value为数字0的option

### What is Expected?
value为数字0的option被错误的显示在select中，而不是显示placeholer

### What is actually happening?
el-select组件的 getOption 方法中

          const type = typeof value;

          const isObject = type !== 'string' && type !== 'number' && type !== 'boolean';

          const isEqual = isObject
            ? getValueByPath(cachedOption.value, this.valueKey) === getValueByPath(value, this.valueKey)
            : cachedOption.value === value;

当value为null或者undefined时，走入了getValueByPath的分支，

getValueByPath(0,'value')与getValueByPath(null,'value')的值又刚好都为null，

所以相等关系的判断不正确，导致显示异常

**Comment by wacky6** [comment]
能开个 pr 吗？ isObject 修一下就可以了。 :)

**Comment by Leopoldthecoder** [comment]
@ZHocean123 @wacky6 
#6143 已经修了，等下个版本。
