### ISSUE TITLE
[Bug Report] [Pagination paging function] IE9~IE11, enter the page number in the input box, carriage return, paging does not work (do not page)

### ISSUE THREAD

**Issue by meahu** [ElemeFE/element#6224]
【Pagination 分页功能】IE9~IE11，在输入框输入页数，回车，分页不起效果（不翻页）

### Element UI version
1.4.1

### OS/Browsers version
IE9~IE11

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/（请忽略）](https://jsfiddle.net/pj71jkyw/（请忽略）)

### Steps to reproduce
打开element的分页功能，直接测试就可以了
http://element.eleme.io/#/zh-CN/component/pagination

### What is Expected?
正常翻页

### What is actually happening?
在输入框输入页数，回车，分页不起效果（不翻页）

**Comment by Leopoldthecoder** [comment]
Fixed in #6306
