### ISSUE TITLE
[Bug Report] Bug in el-select when el-option bind a object to value

### ISSUE THREAD

**Issue by ahDDD** [ElemeFE/element#6226]
### Element UI version
1.4.1

### OS/Browsers version
Deepin 15.4 / Chrome 59.0.3071.86

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/d3ddd/wak3r6gd/](https://jsfiddle.net/d3ddd/wak3r6gd/)

### Steps to reproduce
Just open the jsfiddle(https://jsfiddle.net/d3ddd/wak3r6gd/) site you will see it

### What is Expected?
Be normal

### What is actually happening?
Can't select the value what i want to choice, It will select all when i once click any of them

**Comment by wacky6** [comment]
https://jsfiddle.net/wak3r6gd/1/

You need to use `value-key`, it's a incompatible change in 1.4.x. See select's documentation for details.

**Comment by ahDDD** [comment]
Thanks a lot
