### ISSUE TITLE
[Feature Request] NavMenu navigation menu shrinks when the scrollbar bars the submenu

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#6227]
### Existing Component
是

### Component Name
NavMenu 导航菜单

### Description
菜单过多时会开启纵向滚动条，但是菜单收缩之后如果触发子菜单显示会自动撑出横向滚动条，是否有办法让菜单同时开启纵向滚动条，同时子菜单正常显示漂浮在外。我并不精通css只是觉得应该处理子菜单的样式就可以解决了。
https://jsfiddle.net/f55dpcLv/3/

**Comment by Leopoldthecoder** [comment]
目前看来没什么好办法，只能在收起时取消 `overflow-y: auto` 了
