### ISSUE TITLE
[Feature Request] Layout layout samples or components

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#6228]
### Existing Component
是

### Component Name
Layout

### Description
看了下ant.design框架中的布局部分，觉得蛮不错的。 我们饿了么是否也可以借鉴一套。
https://ant.design/components/layout-cn/#components-layout-demo-top
常用后台布局，面包屑和汉堡折叠菜单等，常用布局示例，我看貌似有一部分还做了响应式的布局组件Layout.Sider。
如果Layout功能更丰富，文档更全面的话，我觉得完全可以替代https://github.com/ElemeFE/element-dashboard
只是建议。

**Comment by Leopoldthecoder** [comment]
在下一个大版本中会考虑加入这些。
