### ISSUE TITLE
There is a problem with using formatter in [Bug Report] table components using data forEach el-table-column

### ISSUE THREAD

**Issue by icssjs** [ElemeFE/element#6232]
### Element UI version
1.4.1

### OS/Browsers version
chrome last

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/h7owr8b4/3/](https://jsfiddle.net/h7owr8b4/3/)

### Steps to reproduce
见链接

### What is Expected?
换表头之后，formatter 应该会被清空

### What is actually happening?
动态更换表头的时候 formatter属性不会更改

**Comment by Leopoldthecoder** [comment]
用 index 作为 `key` 并不合适，因为它不具有唯一性（切换表头前后 index 是不变的）。使用一个真正具有唯一性的值作为 `key` 即可：https://jsfiddle.net/h7owr8b4/4/ 。例子中的 `Date.now()` 可更换为其他唯一性标识。
