### ISSUE TITLE
[Feature, Request] Expand Tree node programmatically

### ISSUE THREAD

**Issue by fnll** [ElemeFE/element#6233]
### Existing Component
是

### Component Name
Tree

### Description
Hey, guys. I have some problems synchronizing two different file trees while I didn't find function that can be used. Is here any workaround to expend the tree node programmatically? Or can I call the `render-content` manually?

**Comment by Leopoldthecoder** [comment]
Could you write a demo to demonstrate your needs? I'm not sure what you're trying to do.

**Comment by CinKon** [comment]
Have a look at my fiddle I used for #6234 : https://jsfiddle.net/CinKon/pj71jkyw/433/
You can use `default-expanded-keys` for dynamically expand node-elements.

**Comment by fnll** [comment]
Image a tree with only one node and a button which will load some data when clicked. Tree is OK and data is OK. The problem is how can the tree transform those data, create nodes, and expand to the right level ? (data may contains many levels)

**Comment by fnll** [comment]
Thx @CinKon. That did solve some of my problems. But It seams that I have to expand the tree without knowing keys

**Comment by CinKon** [comment]
Don't you have id's in the data you recieve after loading? You can use these as node-keys (I do the same here)

**Comment by fnll** [comment]
Loading data action is triggered by clicking a button rather than clicking a tree node. So tree have no idea data is loaded and no tree node will be created. Now what I'm trying to do is find a way to load/renderContent/expand tree node without manipulating tree itself.

**Comment by sharonlx** [comment]
@CinKon i tried code at https://jsfiddle.net/CinKon/pj71jkyw/433/, i does not work when click "Close all expanded", the tree is not collapse reactivly.

**Comment by CinKon** [comment]
That's what the issue #6234 is for ;)
