### ISSUE TITLE
[Bug Report] Tree-Component doesn't collapse on prop-change from store to empty values

### ISSUE THREAD

**Issue by CinKon** [ElemeFE/element#6234]
### Element UI version
1.4.1

### OS/Browsers version
macOS 10.12.6, Opera 46.0.2597.57

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/CinKon/pj71jkyw/433/](https://jsfiddle.net/CinKon/pj71jkyw/433/)

### Steps to reproduce
Use Tree-Component
Use vuex-states for `default-expanded-keys` and `current-node-key`
Set `default-expanded-keys = []`
Set `current-node-key = 0` (or something to disable)

### What is Expected?
I want the Tree-Component to recognize and react to changes in the following properties to empty values: `default-expanded-keys` and `current-node-key`.
The tree then should collapse all open nodes and set all nodes to inactive.

### What is actually happening?
At the moment, it doesn't do anything on change of these props.

**Comment by CinKon** [comment]
Current workaround:

```javascript
      this.$refs.tree.store.currentNode = null

      Object.keys(this.$refs.tree.store.nodesMap).map((key, index) => {
        this.$refs.tree.store.nodesMap[key].checked = false
        this.$refs.tree.store.nodesMap[key].expanded = false
      })
```

**Comment by ke1vin1993** [comment]
@CinKon That doesn't work

**Comment by CinKon** [comment]
Do you mean the workaround? Well, it did 1 1/2 years ago, haven't worked with it since...

**Comment by dj12djdjs** [comment]
@ke1vinn This worked for me
        Object.keys(this.$refs.tree.store.nodesMap).forEach(key => {
          if (!this.defaultExpandedKeys.includes(key)) {
            this.$refs.tree.store.nodesMap[key].expanded = false
          }
        })
