### ISSUE TITLE
[Feature Request] Carousel content band?

### ISSUE THREAD

**Issue by arjanski** [ElemeFE/element#6245]
### Existing Component
Yes

### Component Name
Carousel

### Description
Hey Element team,

First of all, thank you and congrats on your great work!

I would like to implement a carousel "content band", equivalent to carousels used by Netflix or Spotify, where the cards are horizontal, same size, and come with a spacing between them. My question is: Can this be done with the existing carousel component? If not, I would love to see this implemented as another variation.

Thank you

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to implement this feature.
