### ISSUE TITLE
[Feature Request] Disable el-transfer auto-sort on both lists

### ISSUE THREAD

**Issue by Paul-Kijtapart** [ElemeFE/element#6246]
### Existing Component
Yes

### Component Name
Transfer

### Description
When a user move an item between the two lists, both lists would try to sort the order of the items after each move action.

Requested feature:
- add an attribute on the el-transfer that disable the auto-sort on either or both lists.
- e.g. <el-transfer :sortable="false" ...otherOptions > </el-transfer>

JS fiddle:
https://jsfiddle.net/coolbean/n4bsm0w8/

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this feature.
