### ISSUE TITLE
[Bug Report] After the Tree component uses store to add and delete nodes, the component's data source Data has not changed

### ISSUE THREAD

**Issue by svscon** [ElemeFE/element#6247]
### Element UI version
1.4.1

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
https://jsfiddle.net/chhpt/5htk0jfr/3/

### Steps to reproduce
Tree组件使用store添加删除节点后组件的数据源Data没有变化

### What is Expected?
增加获取Tree所有节点的json数据的方法

### What is actually happening?
使用jsfiddle看不出来，需要在vue调试工具下能看到

**Comment by chhpt** [comment]
I have the same problem. And this is the reproduction link:
https://jsfiddle.net/chhpt/5htk0jfr/3/
I used the demo form the document of tree. When I delete some nodes, the data didn't change. It could be a big problem for me. How to solve it?
