### ISSUE TITLE
[Bug Report] Input-Autocomplete should hide suggestions when losing focus via Tab

### ISSUE THREAD

**Issue by iabdulin** [ElemeFE/element#6249]
### Element UI version
1.4.1

### OS/Browsers version
Mac / Latest Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/435/](https://jsfiddle.net/pj71jkyw/435/)

### Steps to reproduce
1) Click on the input. Suggestions are displayed.
2) Press tab
3) Input lost focus, but suggestions are still visible

### What is Expected?
Suggestions should dissappear when the input loses focus via tab

### What is actually happening?
Suggestions are still visible when the input loses focus via tab

**Comment by Leopoldthecoder** [comment]
Fixed in #6256
