### ISSUE TITLE
建议区分一下npmjs上的两个库

### ISSUE THREAD

**Issue by ieiayaobb** [ElemeFE/element#625]
被你们npmjs上的另一个版本坑了一天，图标能显示，按钮怎么都显示不出效果。
结果仔细看了你们在npmjs上的两个库。发现版本不一样，才最终定位到问题。
建议在文档里注明一下。

**Comment by hbrls** [comment]
我一般看 https://github.com/ElemeFE/element/releases

**Comment by furybean** [comment]
@ieiayaobb 另一个版本指的是？

**Comment by ieiayaobb** [comment]
@furybean https://www.npmjs.com/package/element-ui
不知道这个是不是用在vue1上的

**Comment by erguotou520** [comment]
不就只有这一个包么

**Comment by furybean** [comment]
后面文档会做更新，1.0 也会近期发布，发布后应该不会再出现类似的问题。
