### ISSUE TITLE
[Feature Request] DatePicker component resetView

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#6250]
### Existing Component
Yes

### Component Name
DatePicker

### Description
日期选择我想实现以下功能
1. 有开始日期 - 结束日期两个日期组件
2. 可以只选择开始日期或者结束日期
3. 开始日期选择后结束日期只能选择开始时间90后内的时间，结束时间亦然。
https://jsfiddle.net/x5nak7k3/
请看下这个链接，功能都已能实现。唯一有一个问题是：
当我刷新页面进来，第一次选择好开始日期再选择结束日期 这个时候功能是正常的，但是当我再重新选择结束时间，再去看开始时间时时间显示不对，当我在开始时间上切换一下月份啥的，功能就正常了。
datepicker怎么做到已渲染的组件resetView...

不知道说清楚没。。。。。麻烦大神了 
https://jsfiddle.net/x5nak7k3/

**Comment by Leopoldthecoder** [comment]
不用创建 `startTime` 和 `endTime`，直接用 `value1` 和 `value2` 就行：https://jsfiddle.net/x5nak7k3/1/ 。

**Comment by ChangeZhang** [comment]
非常感谢
