### ISSUE TITLE
[Bug Report] slider component problem, when the window changes size, slider also changes the width, when the mouse drags, the slip dot does not synchronize with the mouse.

### ISSUE THREAD

**Issue by jin9999** [ElemeFE/element#6252]
### Element UI version
1.4.1

### OS/Browsers version
win7/chrome

### Vue version
2.4.2

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/slider](http://element.eleme.io/#/zh-CN/component/slider)
基础用法->显示代码->在线运行
### Steps to reproduce
组件有format-tooltip属性。
1.改变组件窗口大小，引起slider组件宽度改变。
2.鼠标拖动滑点，滑点跟鼠标指针不同步，有距离。（窗口变化越明显，距离越明显）

### What is Expected?
改变后，滑点跟鼠标指针同步

### What is actually happening?
滑点跟鼠标指针不同步

**Comment by Leopoldthecoder** [comment]
Fixed in #6263
