### ISSUE TITLE
The [Bug Report] select component does not have the correct scroll bar position.

### ISSUE THREAD

**Issue by jin9999** [ElemeFE/element#6255]
### Element UI version
1.4.1

### OS/Browsers version
win7/chrome

### Vue version
2.4.2

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/select](http://element.eleme.io/#/zh-CN/component/select)
分组例子可重现。

### Steps to reproduce
1.点击选择框，滚动鼠标，让下拉框滚动到最底部。
2.选择“上海”。
3.再次点击下拉框，滚动条仍然显示在底部，但向上滚动鼠标滚动条不会向上滚动，因为列表值已经是在顶部了。向下滚动是有效的。说明滚动条位置是不正确的。

### What is Expected?
滚动条能正确的显示位置。

### What is actually happening?
滚动条位置不正确。

**Comment by Leopoldthecoder** [comment]
请更新 demo 链接。

**Comment by qingdengyue** [comment]
#6271

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/commit/6a99f03e1f014a4dbff884b477a59de90bba3e79#diff-77681c030d3f0bb43a843a628ce7018cR421
