### ISSUE TITLE
datepicker( daterange type) not working inside bootstrap modal after upgrading from 1.0.0-rc.5

### ISSUE THREAD

**Issue by chagamkamalakar** [ElemeFE/element#626]
i am trying to use daterange date picker, it's showing in bootstrap modal.
then i tried to downgrade to  1.0.0-rc.5, it's displayed , but the problem  reported ealier  https://github.com/ElemeFE/element/issues/492 , comming up again.

**Comment by QingWei-Li** [comment]
Is covered by bootstrap modal? likes https://github.com/ElemeFE/element/issues/584

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/ElemeFE/element/pull/664/files#diff-cb3efcfdf157956fce0480ea920e5e5cR3
