### ISSUE TITLE
The [Bug Report] if there is an overflow css the  el-menu component collapsed does not show the child menu when mouse hover 

### ISSUE THREAD

**Issue by jerry9022** [ElemeFE/element#6260]
Element UI version

1.4.1

OS/Browsers version

mac/chrome

Vue version

2.4.2

Reproduction Link

https://jsfiddle.net/7mmn4ra5/

Steps to reproduce

1.使用el-menu组件作为左侧菜单栏，使用了overflow-y:auto样式，使菜单过长时显示滚动条。
2.当点击折叠el-menu后，鼠标移到图标菜单上时，有子菜单显示不出来子菜单浮动窗。
3.去掉overflow-y:auto样式就可以显示出来子菜单浮动窗，但是过长的菜单就显示不出来。

What is Expected?

有overflow样式时折叠菜单不能正确的显示子菜单浮动层。

What is actually happening?

有overflow样式时期望折叠菜单也能显示子菜单浮动层。

**Comment by 641357534** [comment]
您好  请问这个问题解决了吗 ？是怎么解决的呢  ？能否给我说下
