### ISSUE TITLE
[Bug Report] double scroll div box caused the el-select dropdown menu position invalid

### ISSUE THREAD

**Issue by luguosheng1314** [ElemeFE/element#6271]
### Element UI version
1.2.0

### OS/Browsers version
chrome

### Vue version
2.1.0

### Reproduction Link
[https://jsfiddle.net/hrw1m7yq/](https://jsfiddle.net/hrw1m7yq/)

### Steps to reproduce
click the el-select component to show menu  and then rolling the div scrollbar

### What is Expected?
the menu would move with the el-select

### What is actually happening?
the menu can not  move with the el-select

**Comment by qingdengyue** [comment]
Like HTML [select](http://www.w3school.com.cn/tiy/t.asp?f=html_select) .It should close the dropdown list when click the ScrollBar. That is a good way.

**Comment by luguosheng1314** [comment]
if user use touch mouse in mac  to roll the div scrollbar, this appearance looks strange
