### ISSUE TITLE
The contents in [Bug Report] el-popover content are too long and cannot be filled automatically after setting the width

### ISSUE THREAD

**Issue by mashpolo** [ElemeFE/element#6272]
### Element UI version
1.4.1

### OS/Browsers version
osx 10.12/chrome 59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/mashpolo/d182j0z1/](https://jsfiddle.net/mashpolo/d182j0z1/)

### Steps to reproduce
chrome下打开无法换行

### What is Expected?
设置width后，应该自动换行

### What is actually happening?
chrome浏览器下长度太长情况下，无法换行。

firefox下正常

**Comment by Leopoldthecoder** [comment]
自己加个样式就行： https://jsfiddle.net/d182j0z1/1/
