### ISSUE TITLE
[Bug Report] el-table would rendered three time in every update, so it's slow

### ISSUE THREAD

**Issue by XGHeaven** [ElemeFE/element#6276]
### Element UI version
1.4.1

### OS/Browsers version
Macos

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/XGHeaven/qwnm2xbq/](https://jsfiddle.net/XGHeaven/qwnm2xbq/)

### Steps to reproduce
use formatter to see how times table render runs.
please see reproduction link.
you can see 12 `Called` text under table. because there have four rows of table, and one row format(render) three times.

### What is Expected?
I expect only call one time of render function.

### What is actually happening?
And now, three times called of render function.
Whatever the first render or update render, it always render three times.

**Comment by dongsuju** [comment]
I also encountered this problem.

**Comment by hkongm** [comment]
同样碰到这个问题了
the same!
