### ISSUE TITLE
Button in table cell

### ISSUE THREAD

**Issue by Lukino2000** [ElemeFE/element#628]
is it possible inserting an el-button in an el-column element?
if yes can you provide a sample url?

thanks

**Comment by jikkai** [comment]
#169
May be attributes `inline-template` can help you

https://github.com/ElemeFE/element/blob/EnglishDocs/examples/docs/en-us/table.md#multiple-select

**Comment by Leopoldthecoder** [comment]
@Lukino2000 See the url above.

Basically you can
```html
<el-table-column
  inline-template
  label="Operations">
  <el-button type="primary" @click.native="edit(row)">Edit</el-button>
</el-table-column>
```

**Comment by maurer2** [comment]
c and wonder why this doesn't work anymore. At some point `inline-template` was removed (https://github.com/ElemeFE/element/pull/2154) in favour of slots. Here is a working version for newer ElementUI versions. `slot-scope="props"` also works instead of `slot-scope="scope"`

```
<el-table-column>
    <template slot-scope="scope">
        <el-button
            type="primary"
            native-type="button"
            @click="handleClick"
        >
            Button text
        </el-button>
    </template>
</el-table-column>

```
