### ISSUE TITLE
[Feature Request] Utility classes for screen breakpoints

### ISSUE THREAD

**Issue by jmaister** [ElemeFE/element#6281]
### Existing Component
No

### Component Name
CSS classes

### Description
Add utility CSS classes with the same media queries than the el-col and el-row:

xs, sm, md, xl

**Comment by Leopoldthecoder** [comment]
You mean like [this](https://jsfiddle.net/Lqcc2exg/)?

**Comment by smares** [comment]
What I do miss are classes like hidden-sm-and-down, hidden-lg-only, etc. coming from Vuetify (https://vuetifyjs.com/layout/display)

**Comment by jmaister** [comment]
@Leopoldthecoder Thouse classes are only for el-col. I mean classes for adding to any other element like:

    <div class="xs sm">show in small devices</div>
    <div class="md lg">show in big devices</div>

**Comment by Leopoldthecoder** [comment]
We did what @smares proposed in #7541
