### ISSUE TITLE
Will [Feature Request] possibly support mobile terminal interaction in the future?

### ISSUE THREAD

**Issue by tmyeahsing** [ElemeFE/element#6283]
### Existing Component
是

### Component Name
tab,slider

### Description
比如支持移动端的tab使用手势切换,slider组件在移动端的正常使用。
或者是否有比较好的方案来整合这些功能。

**Comment by tmyeahsing** [comment]
Will Element-mobile bepossible？（@..@）

**Comment by qingdengyue** [comment]
[Mint-UI](https://mint-ui.github.io/#!/zh-cn) 参考一下

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop, so we have no plan to support mobile devices.
