### ISSUE TITLE
[Bug Report] when use zoom css property, the options of select widget can not locationed correctly

### ISSUE THREAD

**Issue by sweetOranges** [ElemeFE/element#6288]
### Element UI version
1.4.1

### OS/Browsers version
windows 7/ chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/3azybg5h/](https://jsfiddle.net/3azybg5h/)

### Steps to reproduce
use zoom css property on body element

### What is Expected?
the options of select widget locationed correctly

### What is actually happening?
the options of select widget can not  locationed correctly

**Comment by Leopoldthecoder** [comment]
Use `transform` instead. `zoom` may affect the calculation of dropdown menu's positioning.

**Comment by sweetOranges** [comment]
@Leopoldthecoder do you mean  use scale property? but i found scale property can not work as zoom property

**Comment by sweetOranges** [comment]
@Leopoldthecoder you can see is article [zoom-vs-scale-in-css3](https://stackoverflow.com/questions/26488960/zoom-vs-scale-in-css3)

the most important thing is when i use scale property, both side of page have a space
