### ISSUE TITLE
[Bug Report] loading mask block my dialog

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#6289]
### Element UI version
1.4.1

### OS/Browsers version
win 10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/c1tqdLnw/1/](https://jsfiddle.net/c1tqdLnw/1/)

### Steps to reproduce
open https://jsfiddle.net/c1tqdLnw/1/, click the button

### What is Expected?
the loading mask not block my dialog.

### What is actually happening?
the loading mask block my dialog.
i know the problem is because the loading mask has a large zindex.
but because i not use v-loading.body,so i think it should not block all element,
it should only bolck it self

**Comment by qingdengyue** [comment]
what is self ?

**Comment by lerit** [comment]
i mean it should only block the element where the v-loading directive place.

**Comment by qingdengyue** [comment]
There's 'target' in Loading Options.You can have a try.

**Comment by lerit** [comment]
@qingdengyue 
thanks,i try the target option,but still not work.
https://jsfiddle.net/c1tqdLnw/2/

**Comment by qingdengyue** [comment]
'loadingDiv' div need z-index.set 100 or other valid number

**Comment by Leopoldthecoder** [comment]
@lerit You can override z-index of `.el-loading-mask`.
