### ISSUE TITLE
The, [Bug, Report], select, component, wider, than, the, is, other, input, components,, in, the, inline, form#6110

### ISSUE THREAD

**Issue by stayfool** [ElemeFE/element#6294]
### Element UI version
1.4.0

### OS/Browsers version
win7, chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/skf4fhwu/](https://jsfiddle.net/skf4fhwu/)

### Steps to reproduce
使用一个select组件和一个input组件比较即可，select组件的宽度是217px,input组件是192px

### What is Expected?
select组件在表单中和其他input组件宽度一致

### What is actually happening?
select组件在表单中和其他input组件宽度不一致

#6110

**Comment by cdoer** [comment]
你直接指定宽度不就行了？

**Comment by stayfool** [comment]
@cdoer 制定宽度后自适应怎么办？

**Comment by stayfool** [comment]
我看了一下，data-picker组件里面直接指定了input宽度为193px，select组件没有指定，可以通过同样的手段来限制select组件的宽度以保持和其他组件宽度一致

**Comment by Leopoldthecoder** [comment]
Input 和 Select 都没有指定宽度，Select 更宽是因为右边有个箭头图标。请自行指定宽度，有响应式需求的可以写媒体查询。
