### ISSUE TITLE
[Bug, Report], Loopholes, of, preventOverflow, method, in, popper.js

### ISSUE THREAD

**Issue by mygaochunming** [ElemeFE/element#6299]
### Element UI version
1.4.1

### OS/Browsers version
windows 10 / chrome  59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
当popper的reference标签在body有纵向滚动条的时候，popper表现与期望不一致。

经测试，问题代码：

 bottom: function() {
                var top = popper.top;
                if (popper.bottom > data.boundaries.bottom) {
                    top = Math.min(popper.top, data.boundaries.bottom - popper.height);
                }
                return { top: top };
            }

修改为：

 bottom: function() {
                var top = popper.top;
                if (popper.bottom-root.ducument.body.scrollTop > data.boundaries.bottom) {
                    top = Math.min(popper.top, data.boundaries.bottom - popper.height);
                }
                return { top: top };
            }

就OK了，但是本人对html这块不熟，所以不清楚有没有其他的情况，或者这样修改会不会带来其他的问题，所以没有提交pull-request

### What is Expected?
It can perform as I want

### What is actually happening?
It don't

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
