### ISSUE TITLE
[Bug Report] How set default value in date picker ?

### ISSUE THREAD

**Issue by lfaveur** [ElemeFE/element#6304]
### Element UI version
1.4.1

### OS/Browsers version
Ubuntu 16.04

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/garlacour/4xfyfn1t/1/](https://jsfiddle.net/garlacour/4xfyfn1t/1/)

### Steps to reproduce
I use moment to have dates object, thats why i added it in the fiddle, what is the way to have default value please please ?

### What is Expected?
the default value must be in the input

### What is actually happening?
The dates value is not in the input :/

**Comment by Leopoldthecoder** [comment]
The default value should be an array: https://jsfiddle.net/4xfyfn1t/3/

**Comment by lfaveur** [comment]
thank for your help
