### ISSUE TITLE
[Bug Report] <UploadList inside render(h) function not working

### ISSUE THREAD

**Issue by amitneg1** [ElemeFE/element#6320]
### Element UI version
1.4.1

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/439/](https://jsfiddle.net/pj71jkyw/439/)

### Steps to reproduce
I am using upload component in my project but am getting error in render(h) function as following:
  render(h) {
    var uploadList;

    if (this.showFileList) {
      uploadList = (
        <UploadList
          disabled={this.disabled}
          listType={this.listType}
          files={this.uploadFiles}
          on-remove={this.handleRemove}
          handlePreview={this.onPreview}>
        </UploadList>
      )
    }

my cli showing error "unexpected token" here at <UploadList> tab . I think it is not understating how to render uploadList object with custom HTML tag.

### What is Expected?
my cli showing error "unexpected token" here at <UploadList> tab . I think it is not understating how to render uploadList object with custom HTML tag.

It should render template of uploadList.

### What is actually happening?
my cli showing error "unexpected token" here at <UploadList> tab . I think it is not understating how to render uploadList object with custom HTML tag.

**Comment by Leopoldthecoder** [comment]
`babel-plugin-transform-vue-jsx` is required when writing render functions in JSX.

**Comment by amitneg1** [comment]
Thanks Leopoldthecoder it's works again thanks for sharing knowledge
