### ISSUE TITLE
[Feature Request] component names?

### ISSUE THREAD

**Issue by dcsan** [ElemeFE/element#6322]
### Existing Component
Yes

### Component Name
Layout

### Description
This UI library is too large to import "whole" but the component imports aren't documented.

It would be great to add a page to the docs for this

For example the Layout (Table?)
http://element.eleme.io/#/en-US/component/layout

I tried `import Table  from 'element-ui`
as well as `Layout`

but still get:
Unknown custom element: <el-col>

**Comment by Leopoldthecoder** [comment]
http://element.eleme.io/#/en-US/component/quickstart#on-demand

**Comment by dcsan** [comment]
thanks.
it's still a little hard to know which names. for example el-row or Row ?
looking through the packages helps though.
