### ISSUE TITLE
Changes in the value of the [Bug Report] el-tree show-checkbox cannot be synchronized to the el-tree-node show-checkbox

### ISSUE THREAD

**Issue by lynzz** [ElemeFE/element#6324]
### Element UI version
1.3.6

### OS/Browsers version
macOS Sierra 10.12.4 / Chrome 59.0.3071.115

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/lynzz/qx8eortn/1/](https://jsfiddle.net/lynzz/qx8eortn/1/)

### Steps to reproduce
1. 点击 单选，树依然显示  checkbox

### What is Expected?
1. 点击 单选，树不显示 checkbox
2. 点击 多选，树显示 checkbox

我这有一个场景，树是一个页面左侧菜单，它会根据不同的路由页面，来决定，菜单树是单选或多选

### What is actually happening?
1. 点击 单选，树依然显示  checkbox

**Comment by Leopoldthecoder** [comment]
`showCheckbox` 并不是 responsive 的，所以这个需求只能通过 `v-if` 来切换。

**Comment by lynzz** [comment]
@Leopoldthecoder  https://jsfiddle.net/lynzz/qx8eortn/2/   通过 v-if  按理是可以，但没生效

**Comment by Leopoldthecoder** [comment]
需要加 `key`：https://jsfiddle.net/qx8eortn/3/

**Comment by lynzz** [comment]
@Leopoldthecoder   明白了，谢谢

**Comment by zhenizhui** [comment]
> 需要加 `key`：https://jsfiddle.net/qx8eortn/3/

请教一下，为啥加了`key`就可以了？

**Comment by Leopoldthecoder** [comment]
@zhenizhui https://cn.vuejs.org/v2/api/index.html#key
> 如果不使用 key，Vue 会使用一种最大限度减少动态元素并且尽可能的尝试修复/再利用相同类型元素的算法。使用 key，它会基于 key 的变化重新排列元素顺序，并且会移除 key 不存在的元素。

> 它也可以用于强制替换元素/组件而不是重复使用它。

**Comment by zhenizhui** [comment]
> @zhenizhui https://cn.vuejs.org/v2/api/index.html#key
> 
> > 如果不使用 key，Vue 会使用一种最大限度减少动态元素并且尽可能的尝试修复/再利用相同类型元素的算法。使用 key，它会基于 key 的变化重新排列元素顺序，并且会移除 key 不存在的元素。
> 
> > 它也可以用于强制替换元素/组件而不是重复使用它。

好的，谢谢🙏
