### ISSUE TITLE
[Bug Report] Call `this.$notify()` twice continuously

### ISSUE THREAD

**Issue by JustClear** [ElemeFE/element#6327]
### Element UI version
1.4.1

### OS/Browsers version
Mac OS Version 10.11.5 (15F34) and Chrome Version 60.0.3112.90 (Official Build) (64-bit)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/ru678763/2/](https://jsfiddle.net/ru678763/2/)

### Steps to reproduce
Inevitable, just call `this.$notify()` twice continuously.

### What is Expected?
Positioning correctly, just like call only once.

### What is actually happening?
The notify box positioning abnormality and overlap.

**Comment by Leopoldthecoder** [comment]
Wrap the second call in `$nextTick`: https://jsfiddle.net/ru678763/3/ .

The second Notification needs to know how tall the first one is in order to decide its positioning.

**Comment by JustClear** [comment]
Ohhh, Thanks.
