### ISSUE TITLE
官方网站组件中的dialog示例内的select第一次点击时无法显示，第三次点击后可正常显示

### ISSUE THREAD

**Issue by ruanjf** [ElemeFE/element#633]
### OS/Browers version
macOS/Chrome 53

### Reproduction Link
http://element.eleme.io/#/component/dialog

### Steps to reproduce
点击 “打开嵌套表单的 Dialog”  ->  点击 “请选择活动区域”（第一次点击无法显示，第三次点击正确显示）

### What is Expected?
估计是select的z-index设置和dialog的z-index大小不对应问题

**Comment by ruanjf** [comment]
![image](https://cloud.githubusercontent.com/assets/509251/19672889/1bc365a4-9aad-11e6-829b-c97ef0381a46.png)

**Comment by Leopoldthecoder** [comment]
Duplicate of #410

**Comment by furybean** [comment]
@ruanjf 我们的开发版在这里：http://elementui.github.io/dev/#/component/dialog

**Comment by ruanjf** [comment]
抱歉忘了先搜issues

**Comment by 6gunner** [comment]
所以问题的解决方案是什么？
