### ISSUE TITLE
[Bug Report] erases all node values in the @check-change listener event, while some values can be checked

### ISSUE THREAD

**Issue by showbestriven** [ElemeFE/element#6333]
### Element UI version
1.4.1

### OS/Browsers version
chrom58.0.3013.3

### Vue version
2.4.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
                    <el-tree
                        :data="regions"
                        :props="props"
                        node-key="id"
                        show-checkbox
                        check-strictly
                        ref="tree"
                        @check-change="handleCheckChange"
                        @node-click="handleNodeClick"
                        :render-content="renderContent"
                        style="padding:10px;">
                    </el-tree>
        vm.regions = [{"id":24,"name":"总公司","children":[{"id":15,"name":"事业五部","children":[{"id":15,"name":"张小三","mobile":"13411780155"}]},{"id":14,"name":"事业二部","children":[]},{"id":12,"name":"事业一部","children":[{"id":16,"name":"霍山项目部","children":[{"id":20,"name":"环城局","children":[]},{"id":19,"name":"清扫保洁部","children":[]},{"id":17,"name":"霍山项目经理","children":[]},{"id":22,"name":"垃圾清运部","children":[{"id":27,"name":"韦琪","mobile":"13713941700"},{"id":8,"name":"令狐冲","mobile":"15549448435"}]},{"id":23,"name":"综合巡查","children":[]},{"id":26,"name":"清扫保洁二班","children":[{"id":13,"name":"陈宗胜","mobile":"15156956732"}]},{"id":25,"name":"清扫保洁一班","children":[{"id":14,"name":"倪克淑","mobile":"13470858719"},{"id":27,"name":"韦琪","mobile":"13713941700"}]},{"id":1,"name":"超级管理员","mobile":"15968157138"}]},{"id":27,"name":"佛山项目部","children":[]},{"id":18,"name":"事业一部负责人","children":[{"id":26,"name":"文清","mobile":"13714253669"}]},{"id":25,"name":"蒋松","mobile":"13113113113"},{"id":16,"name":"项阳","mobile":"13965462881"},{"id":1,"name":"超级管理员","mobile":"15968157138"}]}]}]
 handleCheckChange(data, checked, indeterminate) {
            console.log(222)
            this.resetChecked()
        },

### What is Expected?
期待可以在change事件中根绝条件清除掉所有选中状态  （ps;业务目的 实现 部门不可选中 员工可以选中 员工可以实现 单选 和多选 两种情况）

### What is actually happening?
 但是实际上确实可以选中
当点击某些选项前面的选择框时 仍然可以选中
![image](https://user-images.githubusercontent.com/25165547/29011525-51d2db8a-7b66-11e7-8533-ea0b5861a44a.png)

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
