### ISSUE TITLE
[Bug Report] table sets the height to fix the head problem

### ISSUE THREAD

**Issue by imkiven** [ElemeFE/element#6334]
### Element UI version
1.4.1

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
在div中包括table组件，在monut时设置组件的高度，不生效

### What is Expected?
在div中包括table组件，在monut时设置组件的高度生效

### What is actually happening?
在div中包括table组件，在monut时设置组件的高度，不生效

**Comment by imkiven** [comment]
官方demo的height属性是写死的，想动态设置，不生效

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
