### ISSUE TITLE
The [Bug Report] el-table dynamic setting is highly invalid

### ISSUE THREAD

**Issue by imkiven** [ElemeFE/element#6337]
### Element UI version
1.4.1

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/imkiven/63zevav7/2/](https://jsfiddle.net/imkiven/63zevav7/2/)

### Steps to reproduce
在组件上设置table 的height 属性，生效
在mounted中动态设置无效

### What is Expected?
在mounted中动态设置tabel height属相生效

### What is actually happening?
在mounted中动态设置tabel height属相无效，只能在组件中设置固定高度

**Comment by Leopoldthecoder** [comment]
```JS
mounted: function(){
  this.refs.table.height=200
}
```

- First of all, `refs` should be `$refs`. You can see the error printed in console.
- Second of all, directly mutating a component's prop is forbidden. If you change `refs` to `$refs`, you can see another error in the console.
- The right way to do this: https://jsfiddle.net/63zevav7/3/

**Comment by imkiven** [comment]
@Leopoldthecoder 如果table是几个组件中的一个子组件，那就无法使用this.height，请问这样的话如何获取到table组件，并设置高度
