### ISSUE TITLE
[Feature Request] Material icon

### ISSUE THREAD

**Issue by LusenkoSasha** [ElemeFE/element#6338]
### Existing Component
Yes

### Component Name
Icon

### Description
You have very few icons to use. How do I use the material icon from Google?

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/FAQ.md The 4th question.

**Comment by theharshin** [comment]
Sorry to start the conversation again but I can't find 4th question on FAQs related to this?! Any help?
