### ISSUE TITLE
[Bug, Report], upload, component, with, drag, doesn't, work

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#6340]
### Element UI version
1.4.1

### OS/Browsers version
windows 7专业版 / chrome  60.0.3112.90（正式版本） （32 位）

### Vue version
2.4.2

### Reproduction Link
[http://jsfiddle.net/leopoldthecuber/zj305kno/1/](http://jsfiddle.net/leopoldthecuber/zj305kno/1/)

### Steps to reproduce
1.el-upload 组件设置drag的情况下，点击上传文件
2.弹出文件窗口，手动拖曳文件到指定区域
3.此时文件窗口没有关闭，手动点击取消按钮（不是关闭按钮）
(官网提供的例子也存在此问题)

### What is Expected?
文件拖曳到指定区域后，文件上传成，文件窗口自动关闭

### What is actually happening?
1.Chrome浏览器在完成文件拖曳，手动关闭文件窗口后，出现卡死现象
2.firefox/IE 则在拖曳文件到指定区域时，出现禁止icon，无法拖曳文件
3.Opera功能正常
PS: 组件设置drag的情况下，弹出文件窗口时，若不拖曳文件，直接选择文件上传，则功能正常

**Comment by qingdengyue** [comment]
拖拽和打开文件窗口上传是两个独立的操作 应该没有关联关系吧~

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/29053912-71ecee50-7c25-11e7-9072-c98b3612bd73.gif)

并且并没有重现，先关掉了。

**Comment by avilang** [comment]
这个问题我也很解决，我自己写的上传插件，也有一样的问题，感觉是浏览器的问题

**Comment by avilang** [comment]
这个问题我也很纠结，我自己写的上传插件，也有一样的问题，感觉是浏览器的问题
