### ISSUE TITLE
[Feature Request] SCSS instead of CSS based styling 

### ISSUE THREAD

**Issue by wguldin** [ElemeFE/element#6342]
### Existing Component
No

### Component Name
n/a

### Description
Hi, 

I'm a UX Designer who works with scss. I saw an earlier issue about possibly converting element to use scss instead of css alone, as the build process and theming for element is a little cumbersome at the moment. 

Is there still interest in this? I might be willing to look at such a project, but want to make sure it is something others want still.

**Comment by syn-zeta** [comment]
[Element's default theme](https://github.com/ElementUI/theme-default/) is written using PostCSS with a particular plugin called [postcss-salad](https://github.com/ElementUI/theme-default/blob/master/package.json#L32) that is basically a "salad" of bunch of other parsers and plugins. One of those in particular is [postcss-scss](https://github.com/ElemeFE/postcss-salad/blob/master/package.json#L30).

So, to answer your question, Element's theme is already written in SCSS. What you may be working with is the processed or compiled version of it, I'm assuming.

**Comment by Leopoldthecoder** [comment]
Actually we're working on a new theme using pure SCSS already.

**Comment by wguldin** [comment]
I actually ended up porting the files, but it isn't a super sustainable solution, so that's great to hear. Thanks!
