### ISSUE TITLE
[Bug Report] header style after fixing head and height

### ISSUE THREAD

**Issue by imkiven** [ElemeFE/element#6344]
### Element UI version
1.4.1

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/imkiven/63zevav7/4/](https://jsfiddle.net/imkiven/63zevav7/4/)

### Steps to reproduce
设置固定高度，设置fixed列，发现表头后面会多一个gutter元素

### What is Expected?
设置固定高度，设置fixed列，正常显示

### What is actually happening?
设置固定高度，设置fixed列，发现表头后面会多一个gutter元素

**Comment by qingdengyue** [comment]
通过你上面的链接测试了一下，无论有没有fixed属性，gutter元素会一直存在，主要是为了补偿滚动条的宽度。

**Comment by Leopoldthecoder** [comment]
@imkiven 看起来和 #5806 是一个问题？

**Comment by imkiven** [comment]
@Leopoldthecoder 如何解决这个问题

**Comment by Leopoldthecoder** [comment]
如果是一个问题的话，请关注 #5806 ，后面会修。
