### ISSUE TITLE
[Bug Report] Checkbox group not reactive to object array.

### ISSUE THREAD

**Issue by jasonlam0619** [ElemeFE/element#6351]
### Element UI version
1.4.1

### OS/Browsers version
macOS Sierra, Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/yqnLqw4r/1/](https://jsfiddle.net/yqnLqw4r/1/)

### Steps to reproduce
What you see is what you get.

### What is Expected?
The related checkboxes should be automatically checked according to the binded `selectedColumns` array.

### What is actually happening?
They are not checked initially. Also, if you try to check those which should be checked, you'll find they act funny.

**Comment by Leopoldthecoder** [comment]
The `label` (and ultimately elements in the `selectedColumns` array) should be a primitive value: https://jsfiddle.net/yqnLqw4r/2/ .
