### ISSUE TITLE
[Bug Report] el-table' sort-method is invalid in custom column templates

### ISSUE THREAD

**Issue by lonly197** [ElemeFE/element#6353]
### Element UI version
1.4.1

### OS/Browsers version
Chrome 59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/lonly/0aof99z7/](https://jsfiddle.net/lonly/0aof99z7/)

### Steps to reproduce
el-table' sort-method is invalid in custom column templates

### What is Expected?
el-table' sort-method is invalid in custom column templates

### What is actually happening?
el-table' sort-method is invalid in custom column templates

**Comment by Leopoldthecoder** [comment]
As a workaround, you can add `prop` to `<el-table-column>`: https://jsfiddle.net/0aof99z7/1/ . We'll fix it later.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/6349/files#diff-9cb0575a7b0cf4669671ce0485f25c49R24
