### ISSUE TITLE
[Bug Report] The autofocus attr on el-autocomplete component didn't work

### ISSUE THREAD

**Issue by lndj** [ElemeFE/element#6354]
### Element UI version
1.4.1

### OS/Browsers version
macOS 10.12.5 / chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pwmwjncz/](https://jsfiddle.net/pwmwjncz/)

### Steps to reproduce
Just visit  https://jsfiddle.net/pwmwjncz/

### What is Expected?
Autofocus

### What is actually happening?
not.

**Comment by Leopoldthecoder** [comment]
Fixed in #6358
