### ISSUE TITLE
The [Bug Report] Silder slider component causes the slider to automatically jump to the minimum when you click the slider

### ISSUE THREAD

**Issue by jxytb** [ElemeFE/element#6357]
### Element UI version
1.4.1

### OS/Browsers version
windows10 Firefox Chrome IE10

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/446/](https://jsfiddle.net/pj71jkyw/446/)

### Steps to reproduce
当Silder滑块组件初始化时被赋予了初始值之后，直接单击滑块组件上的按钮，会直接导致滑块跳到最小值的位置，如果是range模式，两个按钮都会发生这种问题，这个官网样例上也能重现这个问题的。http://element.eleme.io/#/zh-CN/component/slider

### What is Expected?
不应该跳到最小值

### What is actually happening?
滑块按钮跳到最小值

**Comment by Leopoldthecoder** [comment]
Fixed in #6359
