### ISSUE TITLE
[Feature Request] Pass extra data on el-select remote-method

### ISSUE THREAD

**Issue by kszyrvercobrador** [ElemeFE/element#6361]
### Existing Component
Yes

### Component Name
el-select

### Description
Hi,
Thanks for the great library.

From the existing el-select component, it would be better if we can pass other data to remote-method. This would be very helpful when using el-select on dynamic data. 

for example,

```
<div v-for="(attr,index) in attrbutes">
    <el-select
        v-model="attr.id"
        multiple
        filterable
        remote
        placeholder="Please enter a keyword"
        :remote-method="remoteMethod($searckey,index)"
        :loading="loading">
            <el-option
                v-for="item in attr.items"
                :key="item.value"
                :label="item.label"
                :value="item.value">
            </el-option>
    </el-select>
<div>
```

Once we search, It's really hard for us to know which el-select does the search. 
In addition, I think it is the best way to manipulate data for which we want to use it.

Thanks :)

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/9kocfaq1/

**Comment by kszyrvercobrador** [comment]
Thanks :) I will try this.
