### ISSUE TITLE
[Bug Report] when import all the components in the way of load-on-demand, the size of packaged file is larger.

### ISSUE THREAD

**Issue by Weiyu-Chen** [ElemeFE/element#6362]
### Element UI version
1.2.9

### OS/Browsers version
win7

### Vue version
2.2.6

### Reproduction Link
no link

### Steps to reproduce
```
import Vue from 'vue'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
Vue.use(ElementUI)	
```
import element-ui directly, the size of packaged file is **628kb**.

```
import {Pagination,Dialog,Autocomplete,Dropdown,DropdownMenu,DropdownItem,Menu,
Submenu,MenuItem,MenuItemGroup,Input,InputNumber,Radio,RadioGroup,RadioButton,
Checkbox,CheckboxGroup,Switch,Select,Option,OptionGroup,Button,ButtonGroup,Table,
TableColumn,DatePicker,TimeSelect,TimePicker,Popover,Tooltip,Breadcrumb,
BreadcrumbItem,Form,FormItem,Tabs,TabPane,Tag,Tree,Alert,Slider,Icon,Row,Col,
Upload,Progress,Spinner,Badge,Card,Rate,Steps,Step,Carousel,Scrollbar,
CarouselItem,Collapse,CollapseItem,Cascader,ColorPicker,Loading,MessageBox,
Message,Notification
} from 'element-ui'

Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Autocomplete)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Input)
Vue.use(InputNumber)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(RadioButton)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Switch)
Vue.use(Select)
Vue.use(Option)
Vue.use(OptionGroup)
Vue.use(Button)
Vue.use(ButtonGroup)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(DatePicker)
Vue.use(TimeSelect)
Vue.use(TimePicker)
Vue.use(Popover)
Vue.use(Tooltip)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Tag)
Vue.use(Tree)
Vue.use(Alert)
Vue.use(Slider)
Vue.use(Icon)
Vue.use(Row)
Vue.use(Col)
Vue.use(Upload)
Vue.use(Progress)
Vue.use(Spinner)
Vue.use(Badge)
Vue.use(Card)
Vue.use(Rate)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Carousel)
Vue.use(Scrollbar)
Vue.use(CarouselItem)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Cascader)
Vue.use(ColorPicker)

Vue.use(Loading.directive)

Vue.prototype.$loading = Loading.service
Vue.prototype.$msgbox = MessageBox
Vue.prototype.$alert = MessageBox.alert
Vue.prototype.$confirm = MessageBox.confirm
Vue.prototype.$prompt = MessageBox.prompt
Vue.prototype.$notify = Notification
Vue.prototype.$message = Message
```
However, the packaged file is **809kb** in the way of load-on-demand.

My .babelrc is like that:
```
{
  "presets": [
      ["es2015", { "modules": false }],
      "stage-0"
  ],
  "plugins": [
    "transform-vue-jsx",
    ["transform-runtime",
      {
        "polyfill": false,c
        "regenerator": true
      }
    ],
    ["component", [
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-default"
       }
    ]]  
  ],
```
the version of  "babel-plugin-component": "^0.10.0",

### What is Expected?
the size of two way should be almost equal.

### What is actually happening?
The latter one is larger about 180kb  than the former one.

**Comment by lucassmacedo** [comment]
same issue

**Comment by lucassmacedo** [comment]
he duplicate the size of file

**Comment by Leopoldthecoder** [comment]
@Weiyu-Chen @lucassmacedo 

I started a new project and didn't reproduce this problem: https://github.com/Leopoldthecoder/element-packed-size . The two approaches can be found in `full_import` and `on_demand` respectively. You can try cloning this repo and run `npm run build` in each folder, and the result would be:
- fully import
```bash
static/js/vendor.35650c93596b209ed4d2.js     558 kB
```
- import on demand
```bash
static/js/vendor.486de78d945efef46c50.js     569 kB
```

**Comment by lucassmacedo** [comment]
@Leopoldthecoder i using on demand and i have a theme localy.. 
import '../theme/index.css'

**Comment by Weiyu-Chen** [comment]
@Leopoldthecoder  I reproduce this problem. 
[https://github.com/Weiyu-Chen/test_element_import](https://github.com/Weiyu-Chen/test_element_import)
Is there a webpack plugin cause that issue?



![img](http://wx3.sinaimg.cn/mw690/7239f9degy1fidw1bdgsej211606g0sz.jpg)

**Comment by Leopoldthecoder** [comment]
@lucassmacedo babel-plugin-component doesn't work with local CSS file. In this case, you need to import components like this:
```JS
import Button from 'element-ui/lib/button'
```

And import your style file:
```JS
import '../theme/index.css'
```

Then babel-plugin-component can be removed from your dependencies.

**Comment by Leopoldthecoder** [comment]
@Weiyu-Chen I'm guessing you have babel-plugin-component configs in your fully import `.babelrc`, which is not necessary. Removing it will give you a `main.js` almost same size as when you import on demand.

I'm still looking into what caused this. But generally importing on demand doesn't bloat bundled file size this much.

**Comment by Weiyu-Chen** [comment]
Setting the babel-plugin-component configs or not makes no diffenrent in full import project. 
The problem is the on-demand import , which turn out a larger one than full import.  

What's more , I found the **same problem** in your element-starter project. You can reproduce it in [https://github.com/Weiyu-Chen/test-element-starter](https://github.com/Weiyu-Chen/test-element-starter)

![image](https://user-images.githubusercontent.com/13402013/30250519-53700440-9682-11e7-9eb8-281a1b81df91.png)

**Comment by fengyun2** [comment]
请问这个问题有人解决了么？

**Comment by vnayak-bhatt** [comment]
any update?

**Comment by tripflex** [comment]
Yes I can confirm this is still an issue ... the docs for on demand importing are super outdated as well, being as though babel has had many changes since.

**Comment by tripflex** [comment]
@SunshowerC can you re-open this since stable bot closed it
