### ISSUE TITLE
jsx 语法 select 组件无法触发 this.$emit('input',val) ,

### ISSUE THREAD

**Issue by yanghuilong** [ElemeFE/element#6369]
`render (h) {
      const _self = this
      if (!this.rowDffData) {
        return
      }
      return (
        <div>
        {
          this.rowDffData.map(function (item) {
            return (<div class="row">
              {
                item.map(itemDff => {
                  return (<div class="col-md-6">
                    <form class="form-horizontal">
                      <div class="form-group">
                        <label class="col-sm-5 control-label">{itemDff.dispalyName}</label>
                        <div class="col-sm-7">
                          {itemDff.fieldType === 'Select' ? <select style="width:100%" class="form-control"></select> : ``}
                          {itemDff.fieldType === 'Select2' ? <el-select style="width:100%" onHandleOptionClick={($event) => _self.onSelectedEvent($event)} value={_self.productSample.test}>
                            <el-option value='12' label="21" key="12"/>
                            <el-option value='121' label="121" key="121"/>
                            <el-option value='122' label="122" key="122"/>
                          </el-select> : ``}
                        </div>
                      </div>
                    </form>
                  </div>)
                })
              }
            </div>)
          })
        }
        </div>
      )
    },`

**Comment by githubxiaowen** [comment]
Vue在JSX语法中不支持内置的指令、不支持传递事件参数，你可以用指令对象或者vnode指令数据格式

```js
const directives = [
  { name: 'my-dir', value: 123, modifiers: { abc: true } }
]
return <div {...{ directives }}/>
```
[参考](https://github.com/vuejs/babel-plugin-transform-vue-jsx)
