### ISSUE TITLE
[Feature Request] How to update data in table?

### ISSUE THREAD

**Issue by hzxie** [ElemeFE/element#6371]
### Existing Component
Yes

### Component Name
table

### Description
I'm new to Vue.js and Element UI.
I wonder following questions:

### How to update data in Vue?

```
export default {
      data() {
        return {
          tableData: [{}]
        }
     }
}
```
How can I change the value of tableData?

And how to load tableData with an async request?

**Comment by hzxie** [comment]
Ref: https://segmentfault.com/q/1010000007746117

**Comment by hzxie** [comment]
How can I access the variable: `tableData`?
I cannot find it in `this` variable.

**Comment by Leopoldthecoder** [comment]
Please read Vue docs thoroughly before using it in an actual project.

**Comment by hzxie** [comment]
Ref:
https://github.com/appbone/element-ui-admin/blob/master/src/event/list.vue
