### ISSUE TITLE
[Feature Request] is it possible to use collapse-transition on elTable row expand?

### ISSUE THREAD

**Issue by Spiritized** [ElemeFE/element#6380]
### Existing Component
Yes

### Component Name
elTable

### Description
is it possible to use collapse-transition on elTable row expand? I recognized that table renders a new row after "expand" event emitting(in order to handle expanded behavior). This makes impossible to specify conditional rendering transition in template.

Unfortunately, i can't use elCollapse component, since i need functionality of table columns.

Can you suggest me how can i make it possible?

**Comment by furybean** [comment]
Sorry, we have no plan to support this.
