### ISSUE TITLE
[Bug Report] ElTimePicker component value

### ISSUE THREAD

**Issue by iwebnaut** [ElemeFE/element#6381]
### Element UI version
1.4.2

### OS/Browsers version
win 10 / Chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/zfary5dL/](https://jsfiddle.net/zfary5dL/)

### Steps to reproduce
Select date time with element datetime picker

### What is Expected?
I would like  this what users sees in the datetime picker componet "2017-08-10 15:50:00", instead of "2017-08-10T13:50:00.000Z" to be sent to the server.

### What is actually happening?
when I inspect with vue debug the value is showed: currentValue:"2017-08-10T13:50:00.000Z"

Instead of "2017-08-10 15:50:00" being sent to server, "2017-08-10T13:50:00.000Z" is sent to server.

**Comment by Leopoldthecoder** [comment]
The value of DateTimePicker is a [Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). You can format it to whatever form you like before sending it to the server.
