### ISSUE TITLE
[Bug, Report], The, upload, icon, set, to, top

### ISSUE THREAD

**Issue by lybc** [ElemeFE/element#6382]
### Element UI version
1.4.2

### OS/Browsers version
windows / 版本 60.0.3112.78（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/447/](https://jsfiddle.net/pj71jkyw/447/)

### Steps to reproduce
On my machine, the Uploader component in the official document demonstrates this problem
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
    <!-- 引入样式 -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css">
</head>
<body>
    <div id="app">

        <el-upload action="https://jsonplaceholder.typicode.com/posts/" list-type="picture-card">
            <i class="el-icon-plus"></i>
        </el-upload>
        <el-dialog  size="tiny">
            <img width="100%" src="" alt="">
        </el-dialog>
      </div>
</body>
  <!-- 先引入 Vue -->
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <!-- 引入组件库 -->
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
        return { visible: false }
      }
    })
  </script>
</html>
```

### What is Expected?
The icon is vertically centered

### What is actually happening?
The icon is set to top

In my project: 
![image](https://user-images.githubusercontent.com/9601872/29132430-c9efc594-7d62-11e7-8d5a-d3980715bd54.png)

use the single file test demo:
![image](https://user-images.githubusercontent.com/9601872/29132499-faabba62-7d62-11e7-82bb-36b704dc2715.png)

**Comment by qingdengyue** [comment]
Cant be reproduced~
![image](https://user-images.githubusercontent.com/3230673/29149941-ec9d5e7a-7da9-11e7-8e8f-302053414c43.png)

Version Chrome 60.0.3112.90 (64)

**Comment by leezng** [comment]
Do not use `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`, use html5  standard`<!DOCTYPE html>`.

**Comment by Leopoldthecoder** [comment]
@lybc Please refer to the above solution.

**Comment by lybc** [comment]
Thank you!!!!

**Comment by cchenggit** [comment]
I have met the same problem with official example. and I found it is caused by css class [class^=el-icon-plus]   line-height: 1;
 so overwrite this line-height with !important  and  fix my problem.
