### ISSUE TITLE
The form item loaded by [Bug Report] through V-IF cannot trigger validation

### ISSUE THREAD

**Issue by wangjunji** [ElemeFE/element#6385]
### Element UI version
1.3.7

### OS/Browsers version
Mac / Chrome 60

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/rodcboku/2/](https://jsfiddle.net/rodcboku/2/)

### Steps to reproduce
将长表单拆通过v-if控制分多步完成，第一步表单字段验证正常，第二步只有第一个字段能触发blur验证

### What is Expected?
通过v-if后加载的表单项正常触发验证

### What is actually happening?
非初始加载的el-form-item只有第一个表单项能触发验证

**Comment by wangjunji** [comment]
自己解决了，还是要仔细看文档啊

> Vue 会尽可能高效地渲染元素，通常会复用已有元素而不是从头开始渲染
> 这样也不总是符合实际需求，所以 Vue 为你提供了一种方式来声明“这两个元素是完全独立的——不要复用它们”。只需添加一个具有唯一值的 key 属性即可

所以给每个el-form-item加上唯一的key就好了

**Comment by llt22** [comment]
> 自己解决了，还是要仔细看文档啊
> 
> > Vue 会尽可能高效地渲染元素，通常会复用已有元素而不是从头开始渲染
> > 这样也不总是符合实际需求，所以 Vue 为你提供了一种方式来声明“这两个元素是完全独立的——不要复用它们”。只需添加一个具有唯一值的 key 属性即可
> 
> 所以给每个el-form-item加上唯一的key就好了

非常感谢，我遇到同样的问题，差点搞奔溃我
