### ISSUE TITLE
[Feature Request] el-upload component close tag display problem

### ISSUE THREAD

**Issue by codeInCat** [ElemeFE/element#6386]
### Existing Component
是

### Component Name
el-upload

### Description
手动上传时,选择完文件以后,当鼠标浮动到文件上方时,删除按钮不显示,只有上传操作完成后才能正常显示,和官方文档的代码对比后发现,el-icon-close出现在了label标签内部,但是官方文档的例子el-icon-close出现在了label标签外部,请问怎么解决这个问题

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
