### ISSUE TITLE
[Feature, Request], Should, return, Cascader's, labels, and, values

### ISSUE THREAD

**Issue by niboac** [ElemeFE/element#6387]
### Existing Component
是

### Component Name
Cascader

### Description
我在做省市区级联选择的时候, 用了Cascader选择器, 目前Cascader在选择完成之后返回了一个value的数组, 比如[0,0,1], 但某些时候还想得到它的label数组, 比如 ['北京','东城区','某某镇'], 希望能够把他们都返回出来.

**Comment by Leopoldthecoder** [comment]
We have no plan to support this. You can have a computed property to do this.
