### ISSUE TITLE
[Bug Report] pass custom prop object from upload component to inner nested component

### ISSUE THREAD

**Issue by amitneg1** [ElemeFE/element#6398]
### Element UI version
1.4.2

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/451/](https://jsfiddle.net/pj71jkyw/451/)

### Steps to reproduce
I have passed an :demo="group" prop from custom-el-upload component.
                  <custom-el-upload
                    ref="assetUploadRef"
                    :http-request="(opts) => {uploadAssets(opts)}"
                    action="/"
                    :on-preview="handlePictureCardPreview"
                    :on-remove="handleAssetRemove"
                    :on-change="(file, fileList) => {assetChangeHandler(file, fileList, 'assetUploadRef')}"
                    :auto-upload="true"
                    :file-list="Array.isArray(group.assets) ? group.assets : []"
                    :show-file-list="true"
                    list-type="picture-card"
                    with-credentials
                    accept=".jpg, .gif, .png, .jpeg"
                    multiple
                    :show-preview="showAssetPreview"
                    :demo="group"
                    >

But this group object is getting undefined in upload-list.vue component
  props: {
    demo: Object
  },

### What is Expected?
I want this :demo prop in nested upload-list.vue component.

### What is actually happening?
getting undefined demo prop

**Comment by Leopoldthecoder** [comment]
This doesn't seem to be an Element bug and your demo is broken.

**Comment by qingdengyue** [comment]
custom-el-upload ? custom component?  
[Vue Prop](https://cn.vuejs.org/v2/guide/components.html#Prop)

**Comment by amitneg1** [comment]
I meant that I want to pass an object from el-upload component and will use that object in upload-list.vue component. I have passed object but when i did console.log that in upload.list.vue component getting undefined.

I know fiddle is braking because i didn't put other el-upload files as dependency. That fiddle was just to show you data obj and template.

**Comment by Leopoldthecoder** [comment]
Then we cannot locate the problem. A valid reproduction is required.

**Comment by amitneg1** [comment]
Sorry for providing incomplete fiddle to reproduce issue. But anyhow i got the solution for same. Let me share what was issue. I was not passing prop correctly.
