### ISSUE TITLE
[Feature Request] Make clearable work for multi select

### ISSUE THREAD

**Issue by sruffing** [ElemeFE/element#6399]
### Existing Component
Yes

### Component Name
Select

### Description
There should be a convenient way to clear all of the selections on a single multiple select box at one time without having to build an additional component box. The single select already has this functionality. Forms that combine several of the single and multiple select become inconsistent if one has the clearable feature and the other does not.

`<el-select v-model="model" multiple clearable placeholder="Select"/>`

**Comment by qingdengyue** [comment]
@Leopoldthecoder I'm not sure if it's a problem or just special when that is multiple~

**Comment by sruffing** [comment]
It's specifically coded to be disabled, but I don't see a reason why it should be. I filed it as a feature request instead of a bug as a result. Multiple can be cleared by clicking each of the options but a quick clear for 5+ options is more ideal.

`let criteria = this.clearable &&
          !this.disabled &&
          this.inputHovering &&
          !this.multiple &&
          this.value !== undefined &&
          this.value !== '';
        return criteria ? 'circle-close is-show-close' : (this.remote && this.filterable ? '' : 'caret-top');`

**Comment by SimplyCorey** [comment]
I am also looking for this feature to be added if at all possible.

**Comment by tmas** [comment]
+1
This is a very useful feature - with large numbers of select options, users often complain about having to deselect every option manually.
