### ISSUE TITLE
[Bug Report] input component, el-autocomplete drop-down selection does not support IE9~11, input box input Chinese, submit to the background is garbled

### ISSUE THREAD

**Issue by licjing** [ElemeFE/element#6400]
### Element UI version
1.4.2

### OS/Browsers version
win10 / ie9~ie11

### Vue version
2.3.4

### Reproduction Link
http://element.eleme.io/#/zh-CN/component/input

### Steps to reproduce
1.输入搜索条件（中文）
2.选择下拉框

### What is Expected?
后台接收输入的中文
可以选中下拉框选中的值

### What is actually happening?
后台接收乱码
没有选中

**Comment by qingdengyue** [comment]
可以通过开发工具查看，发往后台的HTTP请求中携带的参数是否是乱码。以确定是否是element-ui的问题~

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
