### ISSUE TITLE
[Bug Report] 1.4.2 Uglify error

### ISSUE THREAD

**Issue by ryatziv** [ElemeFE/element#6403]
### Element UI version
1.4.2

### OS/Browsers version
Chrome

### Vue version
2.4.2

### Reproduction Link
n/a

### Steps to reproduce
webpack-cli based project, newest version produces Uglify error.

`ERROR in static/js/vendor.864b8c7a0146c714115b.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/element-ui/src/mixins/emitter.js:2,0]`

### What is Expected?
Webpack build with no error

### What is actually happening?
Webpack produces error

**Comment by yourlin** [comment]
How did you solove this porblem?

**Comment by DanielWLam** [comment]
```js
ERROR in static/js/vendor.3c7bcdb24ebbd7ee7abd.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/element-ui/src/utils/merge.js:2,0][static/js/vendor.3c7bcdb24ebbd7ee7abd.js:91400,11]  
```js

I still come across this problem:(

**Comment by srzyhead** [comment]
`
ERROR in static/js/vendor.39efa2bc9b3ea7f885f5.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/element-ui/src/utils/merge.js:2,0][static/js/vendor.39efa2bc9b3ea7f885f5.js:29619,11]
`

**Comment by srzyhead** [comment]
```

ERROR in static/js/vendor.39efa2bc9b3ea7f885f5.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/element-ui/src/utils/merge.js:2,0][static/js/vendor.39efa2bc9b3ea7f885f5.js:29619,11]
```
I come across this problem too ...

**Comment by itimor** [comment]
so do i

**Comment by gen4sp** [comment]
any ideas? I faced the same thing
```
ERROR in static/js/1.b1648b2f48e0defe38c3.js from UglifyJs
Unexpected token: operator (>) [./~/element-ui/src/mixins/emitter.js:2,0][static/js/1.b1648b2f48e0defe38c3.js:5603,32]
```

**Comment by michaelbukachi** [comment]
Any ideas to fix this?

**Comment by captyoungkyu** [comment]
```
ERROR in static/js/vendor.86f09157676c7e44ca78.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/element-ui/src/utils/merge.js:2,0][static/js/vendor.86f09157676c7e44ca78.js:33933,11]
```

**Comment by nosus** [comment]
I met the similar problem and it's because the uglifyjs plugin used by webpack 3( version 0.4.6) doesn't support es6. if you are using webpack 3, upgrade to webpack 4 or replace the uglifyjs plugin of webpacck 3 to use the latest version will solve the problem.

**Comment by denbka** [comment]
в build/webpack.base.conf.js в rules добавьте
`
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/element-ui'),
        ]
      },
`
