### ISSUE TITLE
[Bug Report] Dialog property "modal-append-to-body" only appends the mask to body, but not the Dialog itself

### ISSUE THREAD

**Issue by JoeyGH** [ElemeFE/element#6404]
### Element UI version
1.4.2

### OS/Browsers version
Arch Linux / Vivaldi 1.10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/dpwpyymf/](https://jsfiddle.net/dpwpyymf/)

### Steps to reproduce
The "modal-append-to-body" property is already set to TRUE by default, but even if I set it myself like in example below, it makes no difference.

`<el-dialog title="Tips" :modal-append-to-body="true" :visible.sync="dialogVisible" size="tiny">...</el-dialog>`

### What is Expected?
I expect both MASK

`<div class="v-modal" style="z-index: 2002;"></div> `

and DIALOG wrapper

`<div class="el-dialog__wrapper" style="z-index: 2003;">...</div> `

to be appended to the BODY element.

### What is actually happening?
Only MASK is being appended to BODY element, while DIALOG wrapper stays inside the parent, where it was declared (see image bellow).

![example](https://user-images.githubusercontent.com/1660786/29195507-26c215a2-7e2f-11e7-9f36-f573f34509b2.png)

**Comment by Leopoldthecoder** [comment]
See https://github.com/ElemeFE/element/issues/3770#issuecomment-318801854
