### ISSUE TITLE
Can the [Feature Request] table support drag and drop operations?

### ISSUE THREAD

**Issue by 404157386** [ElemeFE/element#6407]
### Existing Component
是

### Component Name
el-table

### Description
我的需求是：在PC端可以拖动表格的行，来调整排序。html5已经有成熟的drag事件。
现有的el-table不支持拖放操作，而且不能在生成的行，自己绑定拖放事件操作。
建议改进。

**Comment by Leopoldthecoder** [comment]
Duplicate of #3543
