### ISSUE TITLE
[Bug Report] upload component upload button, set disabled to true, but the style has changed, but still can click and upload

### ISSUE THREAD

**Issue by zhou0818** [ElemeFE/element#6409]
### Element UI version
1.4.2

### OS/Browsers version
windows10，chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/ayatxqn0/](https://jsfiddle.net/ayatxqn0/)

### Steps to reproduce
el-upload下的el-button,设置了<el-button>的:disabled="true",样式改变了，但是仍然可以点击并上传

### What is Expected?
设置:disabled="true"按钮不可用

### What is actually happening?
设置:disabled="true"按钮仍然可用，只是样式改变

**Comment by Leopoldthecoder** [comment]
Fixed in #6421. But it's better to add `disabled` on Upload as well.

**Comment by yinwanli** [comment]
chrome 70下upload控件里面的el-button设置disabled属性为true，居然还可以点击。jsfiddle里面的例子也是这种情况，但是在firefox下面就是正常的，不可以点击。

**Comment by yuanyuan1991** [comment]
请问这个bug最后怎么处理了？？因为需求不能在el-upload上面加disabled , 因为想正常删除下面的资源，只是禁用按钮不能点击

**Comment by weiq** [comment]
按钮加上这个样式试试
```
    height: 0px;
    user-select: none;
    pointer-events: none;
```
