### ISSUE TITLE
[Feature Request] Select or insert by pressing specific key

### ISSUE THREAD

**Issue by RexSkz** [ElemeFE/element#6411]
### Existing Component
Yes

### Component Name
Select, Input

### Description
In some applications, when you type something in autocomplete input box, you can easily **type `enter` to select the first proposed item, or type `,` or `space` to enter the first proposed tag**. It's quite useful, hope Element UI support this feature, maybe an attribute `default-enter-keycode` is ok. Thanks!

**Comment by wacky6** [comment]
Check Select's `default-first-option`

**Comment by wacky6** [comment]
autocomplete does not have that.

**Comment by wacky6** [comment]
@Leopoldthecoder should we add `default-first-option` to autocomplete?

**Comment by wacky6** [comment]
@RexSkz A rather naive implementation: https://jsfiddle.net/jjr4r54u/
@Leopoldthecoder May be we should unify this dropdown's style with select's

**Comment by RexSkz** [comment]
@wacky6 Your code works well, `v-model` has changed even if my input don't fully match the options.
Though it looks a bit weird to use `select` as `autocomplete`... Nevermind~ 😂

**Comment by wacky6** [comment]
Well. This feature needs more refinement before entering mainline.

**Comment by wacky6** [comment]
@Leopoldthecoder Any thoughts on this feature for autoselect?

**Comment by wacky6** [comment]
@Leopoldthecoder Necessary to use select's dropdown style? Or stick with current ones?
