### ISSUE TITLE
el-table fixed="right" 导致右边固定样式错位

### ISSUE THREAD

**Issue by idujiayou** [ElemeFE/element#6413]
![1](https://user-images.githubusercontent.com/16297776/29203426-5224919c-7ea3-11e7-8cb9-bbf66199ee0d.png)
![2](https://user-images.githubusercontent.com/16297776/29203427-5444d842-7ea3-11e7-8832-746b253c744e.png)
![3](https://user-images.githubusercontent.com/16297776/29203430-557eba52-7ea3-11e7-897a-e288c3206b3d.png)

经过实验把 el-table__fixed-body-wrapper下的table的宽度和el-table__body-wrapper  @下的table设置成一样就不会有偏差

![4](https://user-images.githubusercontent.com/16297776/29203520-12b96d38-7ea4-11e7-8f87-b4331e36db5a.png)

**Comment by lovelyJason** [comment]
这个layout.rightFixedWidth哪里来的
