### ISSUE TITLE
[Bug Report], There is a problem in table components using data forEach el-table-column

### ISSUE THREAD

**Issue by wwwwwwcccccc** [ElemeFE/element#6414]
### Element UI version
1.4.2

### OS/Browsers version
chrome last

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/Wangchen/pen/eERPaY](https://codepen.io/Wangchen/pen/eERPaY)

### Steps to reproduce
在表格列的数据没有嵌套的时候，和期望一样删除正常。但是，当表格列的数据有嵌套时，数据删除是正常的，但是表格渲染会出错

### What is Expected?
表格里面的列是动态生成的，当列数组数据删除一个时，希望视图上也能删除一列

### What is actually happening?
在表格列的数据没有嵌套的时候，和期望一样删除正常。但是，当表格列的数据有嵌套时，数据删除是正常的，但是表格渲染会出错，删除了多列和固定列

**Comment by wwwwwwcccccc** [comment]
解决了，，，给每个<el-table-column>加了 :key=“Math.random()”的属性，就可以了，奇怪。

**Comment by Leopoldthecoder** [comment]
https://cn.vuejs.org/v2/api/#key
