### ISSUE TITLE
[Bug Report] flashing happened when use el-radio under a box display fixed

### ISSUE THREAD

**Issue by xingbofeng** [ElemeFE/element#6415]
### Element UI version
1.4.2

### OS/Browsers version
Windows 7 / QQ Browser 9.6.3

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/FE_Encounter/pen/Nvgeoj](https://codepen.io/FE_Encounter/pen/Nvgeoj)

### Steps to reproduce
1. Scroll to the bottom
2. choose one item
3. choose another item

### What is Expected?
radio display normal without flashing, but not.

### What is actually happening?
when choose one item, radio will flashing.

**Comment by Leopoldthecoder** [comment]
是否仅能在 QQ 浏览器中重现？

**Comment by xingbofeng** [comment]
@Leopoldthecoder Yes, it will happen under QQ Browser, I fix this bug just now, and I will open a pull request.

**Comment by zhuxianbin** [comment]
另外,如果table 设置了 fixed后, dialog显示的mark 会闪一下,fixed的col下始终会有一条白色底边

**Comment by Bimbaloo** [comment]
@Leopoldthecoder 在chrome  66.0.3359.181版本上同样出现该问题。（Element UI version 2.3.9；Vue version：2.5.16）
奇怪的一点：在dev阶段没有这个问题，在build阶段会存在。（webapck打包）
