### ISSUE TITLE
The key name of the options data of [Bug Report] [Bug Report]Cascader is value, displaying error

### ISSUE THREAD

**Issue by liaoyinglong** [ElemeFE/element#6416]
### Element UI version
1.4.2

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/79akd7rs/1/](https://jsfiddle.net/79akd7rs/1/)

### Steps to reproduce
```javascript
// 需要展示的数据：
 options2: [{
          value: '江苏',
          code:1,
          cities: []
        }, {
          value: '浙江',
          code:2,
          cities: []
        }]
// props
  props: {
          value: 'code',
          label:'value',
          children: 'cities'
        },
```

### What is Expected?
预期展示的数据是  options2里面value的值

### What is actually happening?
实际展示的数据是 options2里面的code的值，并且无法进行点击加载

**Comment by Leopoldthecoder** [comment]
Fixed in #6433
