### ISSUE TITLE
[Bug Report] lockScroll BUG

### ISSUE THREAD

**Issue by zuibunan** [ElemeFE/element#6417]
### Element UI version
1.4.2

### OS/Browsers version
win10 chrome61

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/453/](https://jsfiddle.net/pj71jkyw/453/)

### Steps to reproduce
css将body的overflow-y设为scroll，body一直有滚动条
调起弹出框，body由于overflow被js设为了hidden，导致页面滚动
```
  let bodyHasOverflow = document.documentElement.clientHeight < document.body.scrollHeight;
  if (scrollBarWidth > 0 && bodyHasOverflow) {
     document.body.style.paddingRight = scrollBarWidth   'px';
  }
  document.body.style.overflow = 'hidden';
```
如上，没有考虑css将body的overflow-y设为scroll的情况，应该加上
getComputedStyle(document.body).overflowY === `overflow`

### What is Expected?
页面不要抖动

### What is actually happening?
页面抖动了

**Comment by Leopoldthecoder** [comment]
Fixed in #6434
