### ISSUE TITLE
[Bug Report] Switch Component Bug

### ISSUE THREAD

**Issue by stephencode** [ElemeFE/element#6418]
### Element UI version
1.4.1

### OS/Browsers version
Mac OSX / Chrome 60.0.3112.90

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/_stephen/dybzuk67/1/](https://jsfiddle.net/_stephen/dybzuk67/1/)

### Steps to reproduce
1. Set the attributes like this:
```javascript
<el-switch
  prop="is_published"
  v-model="value"
  on-value=1
  off-value=0>
</el-switch>
```

2. Set the data like this:
```javascript
data() {
  return {
    value: 1,
  };
},
```

### What is Expected?
The official document says these two attributes support numeric/string types, but actually it's not work.

### What is actually happening?
Only when the type is a boolean, it can work.

**Comment by Leopoldthecoder** [comment]
`on-value=1` means `on-value` is string `'1'`. Correction: https://jsfiddle.net/leopoldthecuber/dybzuk67/2/
