### ISSUE TITLE
请问v-for生成的el-autocomplete组件 select事件触发时，要如何确定当前是哪个item？

### ISSUE THREAD

**Issue by akebe** [ElemeFE/element#6419]
我把el-autocomplete用作关键字商品ajax搜索选择器，然后写了一个采购单提交页面。
因为设计允许同时提交多单，所以用v-for渲染panel 每个panel里面都有一个el-autocomplete，我的设想是对应的el-autocomplete搜索选择的商品归类于对应的采购单，可是select事件不能传递自已的参数，要如何知道当前是哪个panel的el-autocomplete触发的select呢？

**Comment by akebe** [comment]
其实解决方式很简单，你们在组件上定义一个el_key的props，在回调的最后一个参数加上el_key，问题关闭了，估计没人看得见吧

**Comment by yangmingkun187** [comment]
正好做到这样的需求，看了下源码，autocomplete并不支持对select自定义参数，提供一种解决思路：
在el-autocomplete上 :index="index" 绑定v-for的index，然后在custom-item中render时获取并赋值给item,这样在@select的回调函数中的item就有index值了
``` javascript
 Vue.component( 'my-custom-item', {
        functional: true,
        render: function ( h, ctx ) {
            // 获取绑在el-autocomplete上的index（string类型），并赋值给props.item
            ctx.props.item.index = ctx.parent.parent.$el.attributes.index.value
            var item = ctx.props.item;
            return h( 'li', ctx.data, [ item.name ] );
        },
        props: {
            item: { type: Object, required: true }
        }
    } );
```
另提issue前，好好看看提issue的规范，方便你我他
