### ISSUE TITLE
[Feature Request] Drag-n-drop trees?

### ISSUE THREAD

**Issue by lk-geimfari** [ElemeFE/element#6424]
### Existing Component
Yes

### Component Name
drag-n-drop tree

### Description

It would be cool to be able to create drag-n-drop trees (with automatically node updates), like in example below:

![](https://raw.githubusercontent.com/shuiRong/vue-drag-tree/master/static/vue-drag-tree2.gif)

**Comment by Leopoldthecoder** [comment]
Duplicate of #1940

**Comment by lk-geimfari** [comment]
@Leopoldthecoder Well, so what's your decision? In #1940 i don't find nothing about decision.
