### ISSUE TITLE
[Bug Report] layout problem of <el-select>

### ISSUE THREAD

**Issue by zxz054321** [ElemeFE/element#6429]
### Element UI version
1.4.2

### OS/Browsers version
Ubuntu 16.04 /  Firefox 54.0

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/q5s5g0y3/1/](https://jsfiddle.net/q5s5g0y3/1/)

### Steps to reproduce

Just run the code.

### What is Expected?
The `el-select`'s width should be 100%

### What is actually happening?
The `el-select` displays as a inline component

**Comment by Leopoldthecoder** [comment]
This is by design. A `width: 100%` Select would seem too long. But you can set its style if you want: https://jsfiddle.net/q5s5g0y3/2/
