### ISSUE TITLE
[Bug Report] 字体样式突然取不到了，403错误

### ISSUE THREAD

**Issue by xiaofengleiyu** [ElemeFE/element#6431]
### Element UI version
1.4.2

### OS/Browsers version
谷歌

### Vue version
2.4.2

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
1

### What is Expected?
字体样式突然取不到了，403错误，希望解决

### What is actually happening?
字体样式突然取不到了，403错误

**Comment by Leopoldthecoder** [comment]
unpkg 出问题了，先换 jsdelivr 吧：https://jsfiddle.net/epsbetx9/

**Comment by wuyang158158** [comment]
我这也是显示不出来了

**Comment by zixuzhang** [comment]
mee too

**Comment by ysfscream** [comment]
jsdelivr 和 unpkg 上的样式版本不一样？
