### ISSUE TITLE
[Bug Report] el-input-number sets min=0, unable to type 0.1

### ISSUE THREAD

**Issue by hrsnl-darcy** [ElemeFE/element#6435]
### Element UI version
1.2.9

### OS/Browsers version
windows/chrome latest

### Vue version
2.4.2

### Reproduction Link
https://jsfiddle.net/s6kthjsa/

### Steps to reproduce
1. set el-input-number min = 1
2. 输入0. 时被自动输化为了0，这导致不易输入0.1

### What is Expected?
应该来说， 在输入值=min时， 不应该设置为min, 而应该设置为去掉非法字符即可

### What is actually happening?
结果就是min=0时不易输入小数

**Comment by Leopoldthecoder** [comment]
加一下 `debounce`：https://jsfiddle.net/s6kthjsa/1/
