### ISSUE TITLE
[Feature, Request], select, or, datepick, can, use, with, a,, text, as, input, group?

### ISSUE THREAD

**Issue by LifeFly** [ElemeFE/element#6436]
### Existing Component
是

### Component Name
select or datepick

### Description
 input can use input group with  <template slot="append">example</template> ,
how to use select or datepick  with a text   as input group?

**Comment by Leopoldthecoder** [comment]
I'm sorry I don't quite understand what you mean. You can use Chinese.

**Comment by LifeFly** [comment]
下拉框和日期选择器 能不能像输入框那样和一个前置文本组成一个input group  ，效果就像
`  <el-input placeholder="请输入内容" v-model="input4">
    <template slot="append">.com</template>
  </el-input>`一样，多谢

**Comment by Leopoldthecoder** [comment]
无计划增加此功能。可以自己通过 CSS 实现。
