### ISSUE TITLE
npm run dist报错eslint-plugin-vue 找不到

### ISSUE THREAD

**Issue by cnweibo** [ElemeFE/element#644]
PS C:\Users\Administrator\devenvironment\Code\element> npm run dist

> element-ui@1.0.0-rc.7 dist C:\Users\Administrator\devenvironment\Code\element
> npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.compon
ent.js -p && npm run build:utils && npm run build:theme

> element-ui@1.0.0-rc.7 clean C:\Users\Administrator\devenvironment\Code\element
> rimraf lib && rimraf packages/*/lib

> element-ui@1.0.0-rc.7 build:file C:\Users\Administrator\devenvironment\Code\element
> node build/bin/iconInit.js & node build/bin/build-entry.js

[build entry] DONE: C:\Users\Administrator\devenvironment\Code\element\src\index.js

> element-ui@1.0.0-rc.7 lint C:\Users\Administrator\devenvironment\Code\element
> eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-vue". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-vue is also installed globally. A globally-installed ESLint cannot find a l
ocally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-vue@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

**Comment by cnweibo** [comment]
自己手工安装解决，最好在官方库中增加依赖，自动安装

**Comment by QingWei-Li** [comment]
本来就是自动安装.....

**Comment by cnweibo** [comment]
那我很奇怪，我的就是按照官方走的啊，为啥就没有安装呢

**Comment by QingWei-Li** [comment]
检查下 npm 版本是不是 >= 3, 鉴于你前面有出现安装完运行出错，建议你删掉 node_modules 重新安装。`eslint-plugin-vue` 是放在 `cooking-lint` 依赖里的，如果是 npm 3 并且正确安装，由于依赖目录平级的特性，你的 node_modules 里一定能找到 `eslint-plugin-vue` 这个包，不然连 `eslint` 这个指令都找不到才对
