### ISSUE TITLE
[Bug Report] el-col: <el-col :span="0"> cant't get the 'el-col-0' class name

### ISSUE THREAD

**Issue by laomao800** [ElemeFE/element#6440]
### Element UI version
1.4.2

### OS/Browsers version
mac chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/tkz7rkry/](https://jsfiddle.net/tkz7rkry/)

### Steps to reproduce
```
<el-row>
  <el-col :span="0"></el-col>
</el-row>
```

### What is Expected?
get `<div class="el-col el-col-0">`

### What is actually happening?
only get `<div class="el-col">`

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0.
