### ISSUE TITLE
[Bug Report] Sort table bug

### ISSUE THREAD

**Issue by wangfengming** [ElemeFE/element#6444]
### Element UI version
1.4.1

### OS/Browsers version
all

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/Wangfengming/ngdwetb0/](https://jsfiddle.net/Wangfengming/ngdwetb0/)

### Steps to reproduce
按 index 倒序排序

### What is Expected?
数字按 3 3 2 2 1 1 的顺序出现

### What is actually happening?
顺序按照 1 2 3 1 2 3 的顺序出现

**Comment by wangfengming** [comment]
![image](https://user-images.githubusercontent.com/11853824/29246270-da2fcec4-8026-11e7-84f5-572dd1c3600c.png)
排序不能boolean给出顺序，应该用整数负数和0给出顺序

另外，感觉用 underscore/lodash 的方式排序会好些。
element ui 的排序
https://github.com/ElemeFE/element/blob/dev/packages/table/src/util.js#L30
![image](https://user-images.githubusercontent.com/11853824/29246288-22a36d82-8027-11e7-99df-c8a4d293c543.png)
lodash 的排序
https://github.com/lodash/lodash/blob/master/.internal/baseOrderBy.js#L14
出于两方面考虑：
1. 快排是不稳定的排序，某些浏览器的排序（以前的chrome）就是快排算法
2. 获取待比较对象(a, b)的某个值（getValueByPath）可能是一个比较耗时的操作，在排序过程中，对同一个对象可能会多次调用该操作的

**Comment by wangfengming** [comment]
```javascript
  return array.slice().sort(sortMethod ? function(a, b) {
    return sortMethod(a, b) ? order : -order;
  } : function(a, b) {
    if (sortKey !== '$key') {
      if (isObject(a) && '$value' in a) a = a.$value;
      if (isObject(b) && '$value' in b) b = b.$value;
    }
    a = isObject(a) ? getValueByPath(a, sortKey) : a;
    b = isObject(b) ? getValueByPath(b, sortKey) : b;
    return a === b ? 0 : a > b ? order : -order;
  });
```

我觉得这段代码可以替换成（以前没人提过这个问题，应该是没有用sort-method，这个直接换成 sort-by可好？sortBy 返回一个 value，后面将按这个 value 的大小进行排序）

```javascript
  var getKey = function (value, index) {
    if (sortBy) return sortBy(value, index)
    if (sortKey !== '$key') {
      if (isObject(value) && '$value' in value) return value.$value;
    }
    return isObject(value) ? getValueByPath(value, sortKey) : value;
  };
  var compare = function (a, b) {
    if (a.key < b.key) return -1;
    if (a.key > b.key) return 1;
    return a.index - b.index;
  };
  array.map(function (value, index) {
    return {value: value, index: index, key: getKey(value, index)}
  }).sort(function (a, b) {
    return order * compare(a, b)
  }).map(function (item) {
    return item.value;
  });
```

**Comment by wangfengming** [comment]
奇怪 jsfiddle 中将排序函数改成后面的，就可以按照预期的来了，这是为什么呢？
```javascript
    	sortIndex: function (a, b) {
      	return a.index - b.index
      }
```
改成 
```javascript
    	sortIndex: function (a, b) {
      	return a.index > b.index
      }
```
既然文档上说返回 boolean，那么 true 代表什么顺序，false 又代表什么顺序呢？

**Comment by Weiting-Zhang** [comment]
我认为原因是由于 JavaScript 的**隐式类型转换**,发生了`Boolean(number)`，这个转换函数对于数字 0 返回的是 false，对于正负数都是true，所以会出现bug。例如这里
`return 1 - 2` 计算结果是 -1 而返回的 boolean 被转换为 true
而 `return 1 < 2` 的返回结果是  false，就可以正常排序了。

**Comment by Weiting-Zhang** [comment]
```
 return array.slice().sort(sortMethod ? function(a, b) {
    return sortMethod(a, b) ? order : -order;
  }
```
改为

```
 return array.slice().sort(sortMethod ? function(a, b) {
    return (sortMethod(a, b) > 0)  ? order : -order;
  }
```

**Comment by wangfengming** [comment]
@Weiting-Zhang 不是的，他们官方文档里说的是返回boolean，不是number
http://element.eleme.io/#/zh-CN/component/table （Table-column Attributes sort-method）
可问题是，从来没有见过用boolean来排序的api

Array.prototype.sort 排序回调是返回number
> - If compareFunction(a, b) is less than 0, sort a to an index lower than b, i.e. a comes first.
> - If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements. Note: the ECMAscript standard does not guarantee this behaviour, and thus not all browsers (e.g. Mozilla versions dating back to at least 2003) respect this.
> - If compareFunction(a, b) is greater than 0, sort b to a lower index than a.
> - compareFunction(a, b) must always return the same value when given a specific pair of elements a and b as its two arguments. If inconsistent results are returned then the sort order is undefined.
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

underscore/lodash 会按照指定的值进行排序
https://lodash.com/docs/4.17.4#sortBy

**Comment by wangfengming** [comment]
@Weiting-Zhang 另一个问题就是关于 Array.prototype.sort 的稳定性
MDN 上第一句话就说明了这点

> The sort() method sorts the elements of an array in place and returns the array. **The sort is not necessarily [stable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability)**. The default sort order is according to string Unicode code points.

另外见 stackoverflow
https://stackoverflow.com/a/3027715

**Comment by Weiting-Zhang** [comment]
@wangfengming ，可能刚才我表达的不准确。`array.slice.sort()`  的确是根据数值排序的。这里的 bug 在于我们要根据用户定义的排序函数 `sortMethod` 来给出真正排序需要的 sortOrder，预期是这个 `sortMethod`  计算结果如果大于 0 ，那么 `return sortMethod(a, b) ? order : -order` 的返回数值是 `order`，也就是前面定义的 `order = 1` (假如没有 reverse 的话)，假如计算结果小于等于 0，`return sortMethod(a, b) ? order : -order`  返回的就是 -1。而由于我前面提到的 JavaScript 的隐式类型转换，在执行  `return sortMethod(a, b) ? order : -order` 时，当 `sortMethod` 函数的返回结果是负数时，我们会错误的把真正的 sortOrder 赋值为 1。
如果我们不能强制要求用户定义的比较函数的返回结果必须是布尔值的话，就会出现这种 bug。

**Comment by wangfengming** [comment]
@Weiting-Zhang 我知道你的表述，可是把 0 当成 false 是不对的，sort 回调的返回值含义

- -1 表示如果 a 在 b 的后面，需要交换 a b，确保 a 在 b 的前面
- 0 表示两个元组不交换
- 1 表示如果 a 在 b 的前面，需要交换 a b，确保 a 在 b 的后面

所以 a b 顺序应该有三种情况
- a 需要在 b 的前面
- a b的顺序无关紧要 （稳定排序会保留原本的顺序，不稳定排序如快排会为了算法效率而忽视其原本顺序）
- a 需要在 b 的后面

而 boolean 仅能表示出两种情况，忽视了 a b 相等的情况

**Comment by wacky6** [comment]
@Leopoldthecoder 大版本要不要考虑这个？

**Comment by wacky6** [comment]
boolean 下 a、b 相等 可以等价于 `pred(a,b) === pred(b,a) === false`

**Comment by wangfengming** [comment]
@wacky6 没太理解你说的
a、b 相等 等价于 `pred(a,b) === pred(b,a) === false` 的话
a > b 或者 a < b 的话 `pred(a, b)` `pred(b, a)` 是什么呢？

**Comment by aolose** [comment]
刚刚踩这个坑 建议兼容处理吧, 比如
```
const r = sortMethod(a, b) 
return r > 0 ? order  : r !== 0 ? -order : 0
```
