### ISSUE TITLE
[Feature Request] Fullscreen overlay navigation

### ISSUE THREAD

**Issue by isometriq** [ElemeFE/element#6447]
### Existing Component
Yes

### Component Name
el-menu

### Description
It would be amazing if the menu could also be displayed in a fullscreen overlay. It could be also a separate component.

Here are rough examples:
- https://www.w3schools.com/howto/howto_js_fullscreen_overlay.asp
- https://codepen.io/KingKabir/pen/QyPwgG
- https://tympanus.net/Development/FullscreenOverlayStyles/

I don't have examples for this, but the menu items could be also displayed as squares with text and icon. Sub items could make a drawer open while in fullscreen.

I would see styling like the fullscreen loading:
https://elementui.github.io/dev/master/#/en-US/component/loading

Other thoughts:
- Hamburger icon would trigger the menu
- "X" or escape key allows to close the menu
- search box for searching?
- hotkey to open menu and arrows to navigate?

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
