### ISSUE TITLE
[Bug Report] incorrect select if :value is object

### ISSUE THREAD

**Issue by Gemorroj** [ElemeFE/element#6448]
### Element UI version
1.4.2

### OS/Browsers version
Any

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/nxq6brbo/2/](https://jsfiddle.net/nxq6brbo/2/)

### Steps to reproduce
create select component and set :value option as object.
click to select 2 times.
works correctly with elementui 1.3.x versions

### What is Expected?
correct works

### What is actually happening?
Selects all elements

**Comment by wacky6** [comment]
https://jsfiddle.net/vuz5td5k/

There is an incompatible change in 1.4.x, refer to Select's `value-key` option. http://element.eleme.io/#/en-US/component/select
