### ISSUE TITLE
[Bug Report] Message Box title has bug

### ISSUE THREAD

**Issue by wangfengming** [ElemeFE/element#6452]
### Element UI version
1.4.2

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/Wangfengming/dcnLg1k3/1/](https://jsfiddle.net/Wangfengming/dcnLg1k3/1/)

### Steps to reproduce
click button alert1 -> close alert message box -> click button alert2

### What is Expected?
the second alert should not has a title

### What is actually happening?
the second alert has a title same to the first one

**Comment by wangfengming** [comment]
https://github.com/ElemeFE/element/blob/dev/src/utils/merge.js#L7
title 的 default 值是 undefined，merge options时不会merge过去
```javascript
      if (source.hasOwnProperty(prop)) {
        let value = source[prop];
        if (value !== undefined) {
          target[prop] = value;
        }
      }
```
Message Box 是单例，所有的 data 都可能一直保留着

https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.js#L84
在 showNextMsg 时，将 options merge 到 instance 上，此时 options 中没有title，故instance.title保留了上一次给的值
```javascript
      for (let prop in options) {
        if (options.hasOwnProperty(prop)) {
          instance[prop] = options[prop];
        }
      }
```

**Comment by wangfengming** [comment]
感觉这个 merge 中的 `if (value !== undefined)` 可以去掉的，观察了merge的6处引用，应该没啥问题
![image](https://user-images.githubusercontent.com/11853824/29255901-47398ddc-80d8-11e7-8e2b-edee139971b7.png)

**Comment by wangfengming** [comment]
然后没有引用 merge 的地方应该根据其具体含义决定使用哪个吧？

**Comment by Leopoldthecoder** [comment]
Fixed in #6572
