### ISSUE TITLE
[Feature Request] Component Names

### ISSUE THREAD

**Issue by dcsan** [ElemeFE/element#6453]
### Existing Component
Yes

### Component Name
Collapse

### Description
how do I find out the names of what needs to be included for each component?
adding the needed requirements to the docs page would be very helpful.

eg Table also needs Column (or TableColumn rather)

trying now to get `el-collapse` to work.
What is the required import? I tried

```
import { Collapse } from 'element-ui'
Vue.use(Collapse) 
```

```
[Vue warn]: Property or method "handleChange" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
[Vue warn]: Invalid handler for event "change": got undefined
[Vue warn]: Unknown custom element: <el-collapse-item> 
```

oh, it also needs CollapseItem 
https://github.com/ElemeFE/element/blob/dev/components.json

**Comment by dcsan** [comment]
update: even with the two components included, I still get this error below
Is this a method I need to implement myself, or is it part of another component I need to include for Collapse to work?

```
[Vue warn]: Property or method "handleChange" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

**Comment by dcsan** [comment]
```
    <el-collapse v-model="activeNames" @change="handleChange">
      <el-collapse-item title="API output" name="api_output">
        <pre>
{{item}}
        </pre>
      </el-collapse-item>
      <LinkButton label='api output' v-bind:link='apilink'/>
    </el-collapse>
```

and main.js
```
import {
  ...
  Collapse, CollapseItem
 } from 'element-ui'

Vue.use(Collapse)
Vue.use(CollapseItem)
```

**Comment by Leopoldthecoder** [comment]
You didn't define `handleChange` in the `methods`. Please read the Vue docs before using Element.
