### ISSUE TITLE
[Feature Request] Date Picker with keyboard shortcut

### ISSUE THREAD

**Issue by matth3wga0** [ElemeFE/element#6455]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Originally requested at `element-react`, DatePicker should have keyboard shortcuts like arrow directions and Enter keypress.

Ref: https://github.com/eleme/element-react/issues/548

**Comment by Leopoldthecoder** [comment]
#6131. This feature will be available in the next major version.
