### ISSUE TITLE
[Feature Request] Add a hook before node-click

### ISSUE THREAD

**Issue by tony-cn** [ElemeFE/element#6461]
### Existing Component
Yes

### Component Name
tree

### Description
How can I stop the default event when click a tree node?

**Comment by Leopoldthecoder** [comment]
What default behavior are you trying to prevent?

**Comment by tony-cn** [comment]
I want to prevent the 'current-change' event to ensure the current node won't change.

**Comment by Leopoldthecoder** [comment]
In the next major version we'll have `setCurrentNode` method, so you can reset current node to the previous one in the `current-change` event.

We may not implement a  before click hook.

**Comment by Renhj90520** [comment]
@Leopoldthecoder   Hi, I'm using the el-table component, and I think it has the same problem, there is a button column in my table, when I click one button it also triggers the current-change event, and if I call the method setCurrentRow in current-change handler, it triggers the current-change recursively, and throws the error: Error in event handler for "current-change": "RangeError: Maximum call stack size exceeded". If there is a way to prevent current-change when I click the button.
