### ISSUE TITLE
[Bug Report] 403 message, failed to load resource

### ISSUE THREAD

**Issue by Brbb** [ElemeFE/element#6462]
### Element UI version
1.4.2

### OS/Browsers version
OS X Sierra, Chrome 60.x

### Vue version
2.4.2

### Reproduction Link
[https://brbb.github.io/graphql-rover/](https://brbb.github.io/graphql-rover/)

### Steps to reproduce
Just load the page and check the search bar icon and the console.

### What is Expected?
The searchbar displays the search icon and no 403 error in the console log

### What is actually happening?
Failed to load resource: the server responded with a status of 403 (): element-icons.woff
Failed to load resource: the server responded with a status of 403 (): element-icons.tff
OR
https://unpkg.com/element-ui@1.4.2/lib/theme-default/fonts/element-icons.woff?t=1472440741 index.js:3

**Comment by qingdengyue** [comment]
#6431

**Comment by Brbb** [comment]
I don't read Chinese, what does it mean? Is it an actual solution?

**Comment by jackiegit888** [comment]
I also encountered this problem, could anybody help for it?

**Comment by Brbb** [comment]
I'm pointing at https://cdn.jsdelivr.net/npm/element-ui@1.4.2/lib/index.js now and it seems to work, do the same for the CSS

`@import url("https://cdn.jsdelivr.net/npm/element-ui@1.4.2/lib/theme-default/index.css");`

**Comment by jackiegit888** [comment]
Thanks. It works.@Brbb

**Comment by jimaek** [comment]
Just wanted to let you know that if you have questions about jsDelivr you can let me know. We designed the service to be production ready and its currently in use by large corporations, so you don't have to worry about such breaking changes or bugs.

Plus we have servers in mainland China and a valid ICP license.

**Comment by Leopoldthecoder** [comment]
Apparently unpkg has now stopped supporting query parameters: https://github.com/unpkg/unpkg-website/issues/51 . Don't know if they'll change it back.

Switching to jsDelivr is a good idea. We'll consider to do that as well.

Closing for this is not an Element bug.
