### ISSUE TITLE
[Bug Report] dynamic display of el-menu in el-menu-item, resulting in defaut-active can not work properly

### ISSUE THREAD

**Issue by 632781460** [ElemeFE/element#6466]
### Element UI version
1.4.2

### OS/Browsers version
mac os

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/gmve9d3p/158/](https://jsfiddle.net/gmve9d3p/158/)

### Steps to reproduce
jsfiddle已注释

### What is Expected?
菜单3 被default-active被激活

### What is actually happening?
菜单3 无法被default-active被激活

**Comment by Leopoldthecoder** [comment]
`default-active` 指的是默认选中项，仅在 Menu 渲染时生效，并不是响应式的。如果 `default-active` 需要改变的话，可以在它改变之后重新渲染一下 Menu。

**Comment by 632781460** [comment]
这个我找出了解决方案，只要item3上加上key 保证vue重用 item3这个el-menu-item
[修改后的方案](https://jsfiddle.net/gmve9d3p/159/)

另外从源码看起来，这个就是响应式的，并且效果上确实也是这样，如果不是，请去掉watch default-active

**Comment by shiny** [comment]
我的menu-item index 是动态的，也有同样的问题，加 :key 后也解决了。
