### ISSUE TITLE
checkbox-group和checkbox能支持值取值于value而不是label值吗？

### ISSUE THREAD

**Issue by cnweibo** [ElemeFE/element#647]
有什么办法让checkbox和checkbox-group组件的model和value而不是label值绑定呢？
你比如说下面的，我希望checkList的值是[0,2]这样的值，而不是["复选框A"]这样的值

```
<checkbox-group v-model="checkList">
          <checkbox class="checkbox" label="复选框 A" value="0"></checkbox>
          <checkbox class="checkbox" label="复选框 B" value="1"></checkbox>
          <checkbox class="checkbox" label="复选框 C" value="2"></checkbox>
          <checkbox class="checkbox" label="禁用" disabled></checkbox>
          <checkbox class="checkbox" label="选中且禁用" disabled></checkbox>
</checkbox-group>
```

**Comment by baiyaaaaa** [comment]
你理解错了，checkbox 的 value属性是它的绑定值，而 value 才是这个 checkbox 本身的值。

**Comment by cnweibo** [comment]
我的意思是我不希望看到checkList的值当选中或者不选中对应选项时值是[1 , 2 ]这样的value，而不是label的值["复选框A"]

**Comment by jikkai** [comment]
看下设置`true-label`和`false-label`能不能解决你的问题？

**Comment by wgq837051** [comment]
`<el-checkbox-group v-model="customCheckList">
    <el-checkbox class="checkbox"  true-label="1" false-label=""  label="复选框 A"></el-checkbox>
    <el-checkbox class="checkbox"  true-label="2" false-label="" label="复选框 B"></el-checkbox>
    <el-checkbox class="checkbox"  true-label="3" false-label="" label="复选框 C"></el-checkbox>
    <el-checkbox class="checkbox"  true-label="4" false-label="" label="禁用" disabled></el-checkbox>
    <el-checkbox class="checkbox"  true-label="5" false-label="" label="选中且禁用" disabled></el-checkbox>
  </el-checkbox-group>`
 customCheckList: ['2','5'],
设置true-label与false-label，在el-checkbox-group中不好使。

**Comment by baiyaaaaa** [comment]
理论上来说，true-label 和 false-label 不应该使用在这种场景下。checkbox-group 应该是使用在对多个选项进行选择的情况，true-label 和 false-label 是对单个 checkbox 是否勾选传输绑定不同值的场景。

**Comment by javasgl** [comment]
同样的问题, @cnweibo  这个最终有解决方案么？

**Comment by darkmirrors** [comment]
<el-checkbox-group v-model="pushGalleryInfo.cdi">
  <el-checkbox
    v-for="item in originalCdi"
    :label="item.value"
    name="cdi">
    {{item.label}}
  </el-checkbox>
</el-checkbox-group>

**Comment by darkmirrors** [comment]
`<el-checkbox-group v-model="pushGalleryInfo.cdi">
  <el-checkbox
    v-for="item in originalCdi"
    :label="item.value"
    name="cdi">
    {{item.label}}
  </el-checkbox>
</el-checkbox-group>`

**Comment by helloAwei** [comment]
```
<el-checkbox-group v-model="status">
    <el-checkbox 
        v-for="(value, key) in statusList"
        :key="key"
        :label="key"
    >
        {{ value }}
    </el-checkbox>
</el-checkbox-group>
```
`label` 绑定选中值，展示的`value`放在标签中。

**Comment by uniquejava** [comment]
这个label和value有点烧脑.极大地颠覆了我的认知 😭

**Comment by jiajunlin** [comment]
感觉文档写的不清晰

**Comment by leozzyzheng** [comment]
我也觉得文档写的很含糊，一会用label来表示显示文本，一会label又是绑定值

**Comment by JankinWang** [comment]
`
<el-checkbox :label='item.id'><i></i></el-checkbox>
`
我是这样写的 只要 el-checkbox 标签内有内容 就不显示 :label绑定数据了.

**Comment by printjs** [comment]
> 理论上来说，true-label 和 false-label 不应该使用在这种场景下。checkbox-group 应该是使用在对多个选项进行选择的情况，true-label 和 false-label 是对单个 checkbox 是否勾选传输绑定不同值的场景。

看了你的回答，简直就是再冒皮皮

**Comment by bin-dogami** [comment]
这个 绑定的值是 label 简单是反人类，你们开发的时候都不实际情况来么? 你既然有 label 又有 value，为啥默认要用 label 做为值，没有 value 的时候才用 label 做值，有value 肯定是value。搞的我真难受

**Comment by PoppingJ32** [comment]
可是为什么checkboxGroup一定要绑定label它才会正常，我只写value就不正常，我根本就不想要label显示出来，可是又不能隐藏只能用CSS，好矛盾

**Comment by Mr54233** [comment]
为啥不能和select一样value绑在key上，lable就绑在lable上
