### ISSUE TITLE
The [Bug Report] el-form-item sets the prop error: please, transfer, a, valid, prop, path, to, item, form!

### ISSUE THREAD

**Issue by gdutwyg** [ElemeFE/element#6472]
### Element UI version
1.4.1

### OS/Browsers version
win10 / chrome60

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/d3bem3br/](https://jsfiddle.net/d3bem3br/)

### Steps to reproduce
运行该段代码，直接报错
 `please transfer a valid prop path to form item!`

### What is Expected?
可以正常校验成功

### What is actually happening?
直接报错
 `please transfer a valid prop path to form item!`

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/d3bem3br/1/

**Comment by hoalby** [comment]
https://jsfiddle.net/AlbyHo/anjo7aea/5/
@element-bot @Leopoldthecoder 请问这怎么回事？
