### ISSUE TITLE
After the [Bug Report] Autocomplete leaves the focus through the custom button, the drop-down box is not hidden

### ISSUE THREAD

**Issue by tangyue0924** [ElemeFE/element#6476]
### Element UI version
1.4.2

### OS/Browsers version
Chrome latest

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/51nafvf1/](https://jsfiddle.net/51nafvf1/)

### Steps to reproduce
在一个autocomplete通过回车键离开焦点进入下一个表单控件后,autocomplete的下拉框不会隐藏,而1.4.0以前的版本不会有此问题

### What is Expected?
任何离开焦点的行为都可以隐藏下拉框

### What is actually happening?
下拉框并未隐藏

**Comment by tangyue0924** [comment]
@et

**Comment by ziyoung** [comment]
@tangyue0924 1.4 版本已经不维护了。你可以使用最新版的 element-ui 的 [autocomplete](http://element-cn.eleme.io/#/zh-CN/component/input#dai-shu-ru-jian-yi)。
