### ISSUE TITLE
[Bug Report] 周选择 加个 format="yyyy-MM-dd" 开始时间不对

### ISSUE THREAD

**Issue by suptwo** [ElemeFE/element#6477]
![time](https://user-images.githubusercontent.com/12033906/29268010-ad74232e-811d-11e7-8a7c-04a88a6a957e.png)

### Element UI version
1.4.2

### OS/Browsers version
谷歌 60.0

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/liujin/erL6m8mv/](https://jsfiddle.net/liujin/erL6m8mv/)

### Steps to reproduce
在组件   <el-date-picker  v-model="monthValue" type="week" format="yyyy-MM-dd" :picker-options="weekOptions" placeholder="选择周"></el-date-picker>

加一个 format="yyyy-MM-dd"  选择之后开始时间比实际多一天

比如选择了 2017-08-13至2017-08-19 显示的是 2017-08-14 比实际多一天

### What is Expected?
比如选择了 2017-08-13至2017-08-19 显示的是 2017-08-14 比实际多一天

### What is actually happening?
在组件   <el-date-picker  v-model="monthValue" type="week" format="yyyy-MM-dd" :picker-options="weekOptions" placeholder="选择周"></el-date-picker>
加一个 format="yyyy-MM-dd"  选择之后开始时间比实际多一天

**Comment by suptwo** [comment]
希望加这个功能 
![image](https://user-images.githubusercontent.com/12033906/29268507-9f56ba7a-811f-11e7-93fe-a401d8ff2263.png)

**Comment by Leopoldthecoder** [comment]
Duplicate of #5990
