### ISSUE TITLE
[Bug Report] Popover is not working on el-radio-button

### ISSUE THREAD

**Issue by zuoez02** [ElemeFE/element#6478]
### Element UI version
1.4.2

### OS/Browsers version
macOS Sierra 10.12.6 / Chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/luto/nzx88c6w/](https://jsfiddle.net/luto/nzx88c6w/)

### Steps to reproduce
1. Create a popover element
2. Create an el-radio-group
3. Create two el-radio-button and bind popover on the second one.
4. Click the second button but no popover appear

### What is Expected?
1. Show the popover

### What is actually happening?
2. No popover appear

**Comment by zuoez02** [comment]
When I select the word on the radio button,  the popover appear.

**Comment by Leopoldthecoder** [comment]
You have its `v-model` set to `false`. Removing it will work: https://jsfiddle.net/nzx88c6w/1/

**Comment by zuoez02** [comment]
@Leopoldthecoder Sorry for my bad example, I want to set trigger to 'click' and it doesn't work.

**Comment by wacky6** [comment]
@Leopoldthecoder click is emitted twice: https://jsfiddle.net/ks58gm0o/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ks58gm0o/1/ Please try to avoid setting trigger to `'click'` on Radio or RadioButton.
