### ISSUE TITLE
[Bug Report] In the case of single page application, the message box will not disappear when the message box is opened and the user clicks the back or forward button to switch the route

### ISSUE THREAD

**Issue by FE-runner** [ElemeFE/element#6479]
### Element UI version
1.4.2

### OS/Browsers version
mac/chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
any single page application

### What is Expected?
disappear

### What is actually happening?
show

**Comment by Leopoldthecoder** [comment]
#6043 added `closeOnHashChange` attribute. It'll come with the next major version.
