### ISSUE TITLE
[Feature Request] IE9 loading adds loading GIF (demote processing)

### ISSUE THREAD

**Issue by hxlniada** [ElemeFE/element#6482]
### Existing Component
是

### Component Name
v-loading

### Description
ie9下不支持animaiton，导致所有的loading动画在ie9下都不转动，这已经是严重的影响体验的问题了，希望能在ie9下提供一个loading的gif图或者用其他方式降级处理下

**Comment by Leopoldthecoder** [comment]
It's not recommended to use Element in IE9. Actually we'll remove IE9 from our browser compatibility list soon.

**Comment by hxlniada** [comment]
@Leopoldthecoder I'm really regret to use this project. I feel that you guys will stop maintaining this project sometime in the future.

**Comment by hxlniada** [comment]
不兼容IE9？我是相当怀疑你们是不是自己压根就不在实际中使用这个项目。
不兼容IE9那得多奔放，是限定基于elementui只能做内部系统么？而且还是那种咱么说好只能用某几个浏览器的内部系统？
不兼容IE9，而且感觉你们是相当抵触在现在这个项目里添加新feature的。
唉，什么情况，就是用错工具了。
你们这么搞下去，我好几个项目得重做。
这坑爹

**Comment by hxlniada** [comment]
你不想加，你可以要求我提pr啊，干嘛关关issue关这么快，你们内部根据解决issue数算kpi的么？
