### ISSUE TITLE
Datepicker and Timepicker

### ISSUE THREAD

**Issue by steffanhalv** [ElemeFE/element#6483]
### Existing Component
Yes

### Component Name
date-time-picker

### Description
If I have one date picker and one time picker using same model, timepicker will act as a datepicker but it should still work as a timepicker which its not.

I dont want to use datetime picker as it doesnt automatically close on date selection (and shouldnt).

**Comment by Leopoldthecoder** [comment]
Using one model for both pickers actually sounds a little strange to me. Having a computed property that takes date and time and formats them to a date time value will work.
