### ISSUE TITLE
[Bug Report] Drag slider in tab component other than the first tab cause bug

### ISSUE THREAD

**Issue by mmyjona** [ElemeFE/element#6485]
### Element UI version
1.4.2

### OS/Browsers version
windows chrome 62

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/hs25vjd0/](https://jsfiddle.net/hs25vjd0/)

### Steps to reproduce
click third tab
drag slider handler

### What is Expected?
smooth drag

### What is actually happening?
either min or max when dragging

**Comment by Leopoldthecoder** [comment]
Fixed in #6593
