### ISSUE TITLE
[Feature Request] Custom event triggers for improved validation of autocomplete fields

### ISSUE THREAD

**Issue by hagcin** [ElemeFE/element#6488]
### Existing Component
Yes

### Component Name
el-autocomplete, el-form, el-form-tem

### Description
If a user types: "hello" in an auto complete field, and then selects "hello world", the value in in the validation method on blur is "hello", because value at the time of the blur event is "hello", not "hello world". This makes it hard to validate auto complete fields on blur, and instead you have to validate them on form submit. If we could run validation on a custom events it would then be possible to write rules like this.   { required: true, message: 'Please input a destination', trigger: 'selected' }, or  { required: true, message: 'Please input a destination', trigger: this.destinationFieldSelected },

**Comment by Leopoldthecoder** [comment]
You can use `trigger: 'change'` in this case. We have no plan to support custom triggers.

**Comment by hagcin** [comment]
The problem with trigger:change it creates a less than ideal user experience, because the app is validating the input as the user is typing. it makes the user think they are doing the wrong thing and it slows them down even though they are just typing. It is better to validate after the user has finished making a selection.  It would be nice if auto complete fields to be validated like all the other fields triggered on some kind of event that would catch what the user selected.  Right now my work around is to validate every time the user clicks outside any of the elements in auto complete.

**Comment by Leopoldthecoder** [comment]
We'll see if we can get blur to work.

**Comment by ffxsam** [comment]
Agree with @hagcin. Showing user error messages while they're still typing is bad user experience. It would be great if we had the option to validate on blur instead of on change—and if this fix could be backported to Element 1.x.

Thank you!
