### ISSUE TITLE
[Bug Report] Uploader Component Drag in more than two files will make chrome crash 

### ISSUE THREAD

**Issue by junnanzhang** [ElemeFE/element#6490]
### Element UI version
1.3.2

### OS/Browsers version
window7 chrome 59

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1. open file upload folder.
2. drag file into the uploader, click somewhere else (none upload folder)
3. uploader another file again
4. close the upload folder 

### What is Expected?
chrome should not crash

### What is actually happening?
chrome crashed

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly. You can reopen this when you have a valid one.
