### ISSUE TITLE
[Bug Report] e-tag and e-input auto submit

### ISSUE THREAD

**Issue by thandonguocmo2020** [ElemeFE/element#6493]
### Element UI version
1.4.2

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/hoanghiep/orgswrtf/2/](https://jsfiddle.net/hoanghiep/orgswrtf/2/)

### Steps to reproduce
1. You just run it.
2. Add a new tag and try several times

### What is Expected?
how to fix error auto submit reload page.  {"error": "Please use POST request"} 

### What is actually happening?
I can not combine el-form-items with other el-input.
When you enter enter it automatically send form when not enough information

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/orgswrtf/3/

**Comment by thandonguocmo2020** [comment]
thanks your @Leopoldthecoder

**Comment by suiwenfeng** [comment]
`<el-form @submit.prevent.native="checkEnter">`

**Comment by amey91** [comment]
If you want to call specific functions rather than ignore the input completely, use 

`<el-input @keyup.enter.native="someAction()"></el-input>`

**Comment by polinwei** [comment]
You can use `@keypress.enter.native="submitForm('resetPasswordForm')"` , Ref: https://polinwei.com/element-ui-prevent-form-submit/
