### ISSUE TITLE
[Feature, Request], When, will, tree, component, call, load, method, exactly?

### ISSUE THREAD

**Issue by fnll** [ElemeFE/element#6495]
### Existing Component
是

### Component Name
Tree

### Description
There is a file tree, and a button. When the button is clicked, it will trigger filter. But I found it strange that my tree called load method each time the `filter` method was invoked while I did not expect it at all. So what's the exact time that `load` will called?

**Comment by Leopoldthecoder** [comment]
这是 Bug Report，不是 Feature Request。请不要因为不想写 demo 就选择 Feature Request。
