### ISSUE TITLE
[Bug Report] TimePicker BUG

### ISSUE THREAD

**Issue by shimanxiang** [ElemeFE/element#6498]
### Element UI version
1.4.2

### OS/Browsers version
windows10 /chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/swustsmx/qnu2my69/4/](https://jsfiddle.net/swustsmx/qnu2my69/4/)

### Steps to reproduce
点击按钮->改变开始时间的值->关闭模态框->点击按钮->鼠标foucs开始时间

### What is Expected?
时间值不应该发生改变

### What is actually happening?
时间发生了改变，设置默认时间失败

**Comment by Leopoldthecoder** [comment]
Fixed in #6023
