### ISSUE TITLE
[Bug Report] 1.4.2 version et-table, after setting up height, sets the display:none in the parent container; then binds the new value to the et-table of the data; the parent container cancels display:none, and et-table is invisible

### ISSUE THREAD

**Issue by vboyok** [ElemeFE/element#6500]
### Element UI version
1.4.2

### OS/Browsers version
win10 / 60.0.3112.90

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pf19gnjz/1/](https://jsfiddle.net/pf19gnjz/1/)

### Steps to reproduce
定击重现链接( https://jsfiddle.net/pf19gnjz/3/ )中的setData按钮

### What is Expected?
et-table显示正确的数据

### What is actually happening?
et-table没有显示，
此时收缩窗口，或者从新设置et-table数据源，则恢复显示

此前版本正常

**Comment by qingdengyue** [comment]
这种场景建议用v-if

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0: https://jsfiddle.net/pf19gnjz/5/
