### ISSUE TITLE
The [Bug Report] folding two level menu does not determine the height of the judgment, resulting in truncation of the #6486

### ISSUE THREAD

**Issue by hitripod** [ElemeFE/element#6501]
### Element UI version
1.4.2

### OS/Browsers version
Chrome 60.0.3112.90

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/t01f0z7t/](https://jsfiddle.net/t01f0z7t/)

### Steps to reproduce
NavMenu 导航菜单的折叠元件二级菜单不会判断判断高度导致截断，可重现的代码：https://jsfiddle.net/t01f0z7t/

### What is Expected?
会根据浏览器视窗高度自动判断往上或是往下展开，如果高度不够应该要有 overflow:scroll 的行为。

### What is actually happening?
永远往下展开，截断发生。

**Comment by baiyaaaaa** [comment]
the latest version of element-ui has resolved this problem
