### ISSUE TITLE
[Feature Request] radio's selection function

### ISSUE THREAD

**Issue by mengyubo** [ElemeFE/element#6504]
### Existing Component
Yes

### Component Name
radio

### Description
建议radio单选框，增加取消功能，应用场景非常多！
比如默认不选中的情况，你勾选后无法取消，特别难用

**Comment by qingdengyue** [comment]
所以还有个复选框嘛~   
Radio 标准的HTML Radio也是这个样子

**Comment by mengyubo** [comment]
标准要是好用，就不用组件了，需求是存在的，复选框单选行为太怪异

**Comment by maple326** [comment]
> 标准要是好用，就不用组件了，需求是存在的，复选框单选行为太怪异

最近项目中也遇到这个需求，已找到解决方法。监听el-radio的原生click事件，事件会触发两次，判断事件参数e.target.nodeName==='INPUT'时，将v-model绑定的value值设置为相反状态的值

**Comment by loca-spirit** [comment]
> > 标准要是好用，就不用组件了，需求是存在的，复选框单选行为太怪异
> 
> 最近项目中也遇到这个需求，已找到解决方法。监听el-radio的原生click事件，事件会触发两次，判断事件参数e.target.nodeName==='INPUT'时，将v-model绑定的value值设置为相反状态的值

如果能内置到组件的cancelable就完美了。
