### ISSUE TITLE
[Feature, Request], More, APIs, For, <el-autocomplete>, custom-item

### ISSUE THREAD

**Issue by zxz054321** [ElemeFE/element#6505]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
`custom-item` 属性有很多尴尬的地方：

1. 不能控制 `<el-autocomplete>` 的显示隐藏，点击后无法通过自动或编程方式收回 `suggestions`
2. 无法触发 `<el-autocomplete>` 的 `select` 事件

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/c79bfhna/1/ 未能重现。如果有问题请提供 demo。

**Comment by zxz054321** [comment]
似乎custom-item的组件只能使用render函数，才有效
