### ISSUE TITLE
[Bug Report] Icons don't work

### ISSUE THREAD

**Issue by Konstantin910716** [ElemeFE/element#6507]
### Element UI version
1.4.2

### OS/Browsers version
Windows 10, Chrome Version 60.0.3112.101 

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/70xk7myc/)

### Steps to reproduce
Create some icon or button with icon

### What is Expected?
Expected to show icon

### What is actually happening?
Instead of icon it shows cube

**Comment by Konstantin910716** [comment]
Done

**Comment by thandonguocmo2020** [comment]
icon is name class  : class="name icon"

**Comment by Konstantin910716** [comment]
What it means? I didn't get. 
I'm creating icons like that - <i class="el-icon-edit"></i>
Or buttons with icon like that - <el-button type="primary" icon="search">Search</el-button>
this is even on home page of this component - http://element.eleme.io/#/en-US/component/icon
but it doesn't work at all, it doesn't work since yesterday

**Comment by thandonguocmo2020** [comment]
Just assign the class name to el-icon-iconName.
it is class name in css with font-icon in css file.

**Comment by Konstantin910716** [comment]
like that? 
`<i class="el-icon-edit"></i>`
if not can you provide an example please?

**Comment by thandonguocmo2020** [comment]
it have. https://jsfiddle.net not found by "f12" not load file css in server. 
uri : @import url("//unpkg.com/element-ui@1.4.2/lib/theme-default/index.css"); not load.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/6462

**Comment by thandonguocmo2020** [comment]
@Leopoldthecoder  your can help me. how to using event change in el-select.

**Comment by Konstantin910716** [comment]
@Leopoldthecoder it helps, thank you very much
