### ISSUE TITLE
[Feature Request] el-table provides the dom of the real display cell.

### ISSUE THREAD

**Issue by ThinkRealize** [ElemeFE/element#6510]
### Existing Component
是

### Component Name
el-table

### Description
我写了一个指令，需要得到 el-table-column  slot 内的 dom 元素。我在指令的 inserted 钩子函数内获取到 el 并存储。但是 table 的 fixed 属性启用后，会有多份一样的 el-table-column，有些是显示有些不显示。那么我怎么获取到真正显示的el-table-column  slot  内的 dom 元素。以下是我的指令使用时的代码

            <el-table-column label="左眼视力"
              align="center"
              width="180">
              <template scope="scope">
                <p v-switch-display-child:display="{scope, order: 2}">{{scope.row.visionLeft}}</p>
                <el-input-number v-switch-display-child:occultation="{scope, order: 2}"
                  v-model="scope.row.visionLeft"
                  size="small"
                  :controls="false"></el-input-number>
              </template>
            </el-table-column>

**Comment by Leopoldthecoder** [comment]
由于 Table 对于固定列的实现正是渲染出一个相同的列，所以这里可能需要自己绕一下。这个指令是做什么的？需求具体是怎样？

**Comment by ThinkRealize** [comment]
@Leopoldthecoder 需求是这样的。在表格单元格内放置一个输入框 和一个显示输入框内容的文本行，一行可能会有多个这样的单元格。开始时文本行显示，输入框隐藏，当点击文本行时显示该行输入框，隐藏该行文本行。然后通过 tab 键在输入框内切换焦点，当焦点在一行中最后一个输入框时隐藏该行输入框显示该行文本行并且显示下一行的输入框且焦点要在下一行第一个输入框。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/g0b7dsxn/ 一个参考。
