### ISSUE TITLE
[Bug Report] table in dialog, when multiple columns have fixed properties, the CSS style problem occurs

### ISSUE THREAD

**Issue by wwwwwwcccccc** [ElemeFE/element#6512]
### Element UI version
1.4.2

### OS/Browsers version
chrome last

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/Wangchen/pen/eERPaY](https://codepen.io/Wangchen/pen/eERPaY)

### Steps to reproduce
在dialog中的表格，当多列使用fixed属性固定时，在最后一列的右边，与非固定的列之间有小的间隔。

### What is Expected?
在dialog中的表格里面，当有多列fixed时，表格样式正常

### What is actually happening?
在dialog中的表格里面，当有多列fixed时，表格最后的一个固定列，样式出现异常

**Comment by wwwwwwcccccc** [comment]
有谁能回答下吗

**Comment by furybean** [comment]
@wwwwwwcccccc 你的例子里面并没有看到 Dialog，请问如何重现？
