### ISSUE TITLE
[Feature Reqeust]can custom debounce value

### ISSUE THREAD

**Issue by dsonet** [ElemeFE/element#6518]
### Existing Component
Yes

### Component Name
 el-select

### Description
In version 1.4.2, el-select can't set custom debounce value but others can.

**Comment by Leopoldthecoder** [comment]
What is custom value?

**Comment by dsonet** [comment]
@Leopoldthecoder  the debounce is a fixed value for now.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this API.

**Comment by jonathanpmartins** [comment]
this sucks! Why can I not control the time that the remote-method takes to be dispatched?
