### ISSUE TITLE
Select组件 在 Dialog 中， 样式显示有问题。

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#652]
### ElementUI version
1.0.0-rc.7

### Vue version
2.0.1

### Reproduction Link
[https://jsfiddle.net/vc0wwfz9/1/](https://jsfiddle.net/vc0wwfz9/1/)

![image](https://cloud.githubusercontent.com/assets/10893176/19713413/82d421b8-9b78-11e6-9b44-3cefcc056cba.png)

**Comment by Leopoldthecoder** [comment]
Duplicate of #410
