### ISSUE TITLE
[Bug Report], NavMenu, horizontal mode, collapse, true, the mouse moves quickly, causing the menu to be retracted

### ISSUE THREAD

**Issue by zxjava** [ElemeFE/element#6520]
### Element UI version
1.4.2

### OS/Browsers version
chrome 60.0.3112.101 （64 位）

### Vue version
2.1.0

### Reproduction Link
[https://jsfiddle.net/m2s8ejyz/](https://jsfiddle.net/m2s8ejyz/)

### Steps to reproduce
当菜单为horizontal模式并且collapse为true的时候 ，比如有三级菜单{A1,children:[ {B1},{B2,children:[C1]} ]}，当鼠标在弹出的二级菜单上从B2和B1之间快速移动时，如果B2的子菜单C1还未弹出来（子菜单弹出有第一定的延时），且鼠标已经移至B1，则整个菜单就会收起。

### What is Expected?
无论鼠标如何移动，只要还在菜单上，菜单都不应该收起。而且子菜单的弹出有略微的延时，最好可以设置延时时间。

### What is actually happening?
无论鼠标如何移动，只要还在菜单上，菜单都不应该收起。

**Comment by xiaoqi-rimix** [comment]
After reading the source code, it is found that there are settimeout(300ms) behavior in handleMouseenter () and handleMouseleave ()

And the problem will recur When the menu for the isCollapse mode  , closed

**Comment by hanyuhh** [comment]
有什么好的解决方案么，改动源码？

**Comment by Leopoldthecoder** [comment]
Fixed in #7579
