### ISSUE TITLE
[Bug Report] pop-up component removed from the scroll bar, resulting in changes in view

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#6524]
### Element UI version
1.4.2

### OS/Browsers version
osx10 chrome56

### Vue version
2.4.2

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
这个是一个别人的项目，但是和我反馈的bug一致
点击页面的  edit 按钮， 然后触发弹窗  整个页面会丢掉原来的滚动条
页面头部的admin 按钮也会发生偏移

### What is Expected?
当弹窗触发的时候，保留之前原有的滚动条， 没有滚动条就不管它， 避免版式因此发生偏移

### What is actually happening?
弹窗触发， 页面版式会发生偏移

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
