### ISSUE TITLE
[Bug Report] Too many events are emited when `el-select`'s option changed

### ISSUE THREAD

**Issue by RexSkz** [ElemeFE/element#6527]
### Element UI version
1.4.2

### OS/Browsers version
All

### Vue version
2.4.2

### Reproduction Link
[https://gist.github.com/RexSkz/1220589c5425cb16306050b812511d0a](https://gist.github.com/RexSkz/1220589c5425cb16306050b812511d0a)

### Steps to reproduce
1. Download `el-option-test.html` in the link and open it in browser.
2. Hit F12 and switch to Vue panel (You may have to enable `Vue.js devtools` for `file` protocol).
3. Click the button in webpage.
4. Watch events in Vue panel.

### What is Expected?
Act as normaml.

### What is actually happening?
There're too many `resetIndex` events emitted (More than 900 events while there're only 30 `el-options` per `el-select`, time complexity is probably O(n^2)), may cause some performance issue.

 ![Screenshots](https://dn-coding-net-production-pp.qbox.me/b8af9f29-7705-4df0-a0e6-7a965b513239.png)

Better not emit too many events, because some website may use `el-select` for "country" or "city" selection, it'll be far more than 30 `el-options` in this case.

P.S. I can't figure out how to solve this problem by now, but it's worth to do some work in it.

**Comment by wacky6** [comment]
@Leopoldthecoder Wasn't this fixed in https://github.com/ElemeFE/element/pull/6151/ ?

**Comment by RexSkz** [comment]
@wacky6 I didn't notice the issue #5790 , making a duplicate issue is my fault...

But `resetIndex` is still there. See: https://github.com/ElemeFE/element/blob/dev/packages/select/src/select.vue#L630 and https://github.com/ElemeFE/element/blob/dev/packages/select/src/option.vue#L161 . I don't know if this function is necessary, but it wasn't fully removed in #6151 .

**Comment by wacky6** [comment]
A naive solution is to remove events and operate on el-option's `this.parent` directly.

Should not be a big trouble, since these two components are tightly coupled anyway.

**Comment by RexSkz** [comment]
This problem also appears when the page which contains `el-select` is removed (for instance, if router changes).

**Comment by wacky6** [comment]
Actually, onOptionDestroy is emitted whenever a el-option is deleted, which triggers resetIndex on all remaining el-options. So there's a cascading effect

**Comment by wacky6** [comment]
Naive fix: https://github.com/wacky6/element/commit/d21a2938a275162af39365db0e11dcdaccc33fb6

Passes all tests, not sure if anything else is broken.
Built element-ui bundle: https://wacky6.github.io/js-bin/element/select-remove-reset-index.js

**Comment by Leopoldthecoder** [comment]
That fix will be shipped in version 2.0 (merged into the `carbon` branch).

**Comment by wacky6** [comment]
I just checked carbon's implementation, still too many onOptionDestroy events, 25 emissions for 5 options.

**Comment by wacky6** [comment]
I think it's ok to change `this.dispatch('ElSelect', 'onOptionDestroy', ...),` to `this.parent.onOptionDestroy(...)`. Then the onOptionDestroy event can be removed completely.

**Comment by wacky6** [comment]
I think its ok to change `this.$dispatch('onOptionDestroy')` to a call to `this.select.onOptionDestroy()` in el-option. Then remove `onOptionDestroy` event completely.

Not sure why so many beforeDestroy hooks are called.

**Comment by RexSkz** [comment]
Thanks, I'm waiting for element-ui 2.0~

**Comment by Leopoldthecoder** [comment]
Here it comes: #6576
