### ISSUE TITLE
[Feature Request] on tree control problems

### ISSUE THREAD

**Issue by stillsilly** [ElemeFE/element#6532]
### Existing Component
是

### Component Name
tree

### Description
1，现在是点击之后checkbox立即会变成‘选中’/'非选中'状态，想让它在ajax请求成功后再改变，要怎么实现？  
2，我需要对选项的选中、取消发请求给后台，现在监听值的变化只有@check-change这个事件，选中一级菜单，二三级选项值的改变都会触发这个事件，点一次按钮 函数会调用很多次，…… 有什么办法只监听我点击的那个值的变化吗，或者现在的check-change事件怎样才能判断出它是直接由我点击触发的、还是间接触发的？  
3，为什么节点的选中/非选中不根据数据的值判断，比如<el-tree :checked="isChecked"> </el-tree>，感觉default-checked-keys和setCheckedKeys用着不方便

**Comment by stillsilly** [comment]
![](https://sfault-image.b0.upaiyun.com/260/885/2608854917-59940f8c5934a_articlex)  
想在点击一级目录和二级目录的时候把数据汇总，只发一个请求（而不是发很多个三级选项的小请求）

**Comment by furybean** [comment]
对于问题 2，已经增加了 check 事件。#9730
