### ISSUE TITLE
[Bug Report] The check box can't be checked when all of it's child nodes has disabled

### ISSUE THREAD

**Issue by tony-cn** [ElemeFE/element#6533]
### Element UI version
1.4.2

### OS/Browsers version
win7 / chrome 57

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/PaDaker/7gwh2eyd/](https://jsfiddle.net/PaDaker/7gwh2eyd/)

### Steps to reproduce
Click the check box of node 3-1-1 after disable all child nodes of node 3-1-1.

### What is Expected?
When check the node '3-1-1',the check box will be checked.

### What is actually happening?
When check the node '3-1-1',the check box won't be checked.

**Comment by Leopoldthecoder** [comment]
This is intended. See #4767
