### ISSUE TITLE
[Bug Report] Can not set the 12-hour time format in DateTimePicker

### ISSUE THREAD

**Issue by forevist** [ElemeFE/element#6537]
### Element UI version
1.4.2

### OS/Browsers version
Win10 / Chrome version 60.0.3112.90

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Set fromat 'dd-MM-yyyy HH:mm a'
and try chose some date range

### What is Expected?
i expect result like "16-08-2017 06:19 pm"

### What is actually happening?
Actually look at the console, and you will see critical error: "TypeError: Cannot read property '0' of undefined"

because in "https://github.com/ElemeFE/element/blob/463607f40be6238e1e08caa1e5ddcae90ccb7478/src/utils/date.js#L251"

in fecha.format function (line 251)
we could see:    
var i18n = i18nSettings || fecha.i18n;

but in i18nSettings 

"https://github.com/ElemeFE/element/blob/463607f40be6238e1e08caa1e5ddcae90ccb7478/packages/date-picker/src/util/index.js#L6"

settings doesn't have amPm to convert like in code 

(https://github.com/ElemeFE/element/blob/463607f40be6238e1e08caa1e5ddcae90ccb7478/src/utils/date.js#L206):

a: [word, function (d, v, i18n) {
      var val = v.toLowerCase();
      if (val === i18n.amPm[0]) {
        d.isPm = false;
      } else if (val === i18n.amPm[1]) {
        d.isPm = true;
      }
    }],

**Comment by Leopoldthecoder** [comment]
Fixed in #6574
