### ISSUE TITLE
[Bug Report] Table in expand-row does not render when the row expand at first time

### ISSUE THREAD

**Issue by lzq4047** [ElemeFE/element#6538]
### Element UI version
1.4.2

### OS/Browsers version
Chrome 60.0.3112.90(64bit)

### Vue version
2.4.2

### Reproduction Link
[1.4.2](https://jsfiddle.net/czybdaht/)
[2.1.0](https://jsfiddle.net/czybdaht/2/)

### Steps to reproduce
1.Place a new table in expand-row
2.Click icon of expanding to expand this row

### What is Expected?
Render the table in expand-row when the first click

### What is actually happening?
Do not render the table in expand-row

**Comment by furybean** [comment]
此问题属于使用方法有误，你应该使用 scope slot 来实现此功能。

1.4.2 更新后的版本为：https://jsfiddle.net/czybdaht/4/
2.1.0 更新后的版本为：https://jsfiddle.net/czybdaht/3/

**Comment by ShawshankLin** [comment]
@furybean 
可以使用render方式吗，比如像这样的写法
{
type: 'expand',
width: 30,
render: (h, params) => {
return h('div', [
h(
'div',
{
style: {
backgroundColor: 'rgba(0, 220, 255, 0.35)',
'word-wrap': 'break-word'
}
},
'标题：' + params.row.title
),
h(
'div',
{
style: {
backgroundColor: '#ffbc0061',
'word-wrap': 'break-word'
}
},
'内容：' + params.row.content
)
])
}
},
