### ISSUE TITLE
The [Feature Request] el-dialog Title cannot be dynamically set

### ISSUE THREAD

**Issue by 404157386** [ElemeFE/element#6540]
### Existing Component
是

### Component Name
el-dialog

### Description
el-dialog的title, 只能绑定文本, 无法动态传入设置。文档里面写可以通过slot设置，但是没有具体实例。如何才能动态设置标题？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by 404157386** [comment]
这个的确是feature吧，对话框的title没有办法动态修改。而且我也搜索过了，找不到类似的issue。

**Comment by Leopoldthecoder** [comment]
「不能动态修改」是一个 bug，你应该写一个 demo
