### ISSUE TITLE
[Feature, Request], how, to, add, new, row, for, table?

### ISSUE THREAD

**Issue by proshuai** [ElemeFE/element#6543]
### Existing Component
是

### Component Name
table

### Description
when i click add new row of the button, i wish the new row or every col is a input, and  the operate column is confirm and cancel.

**Comment by proshuai** [comment]
![image](https://user-images.githubusercontent.com/13295895/29399429-c9590c18-835b-11e7-9fcc-038f65df7101.png)
like this

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by proshuai** [comment]
@Leopoldthecoder 冤枉了。。。我是按标准来提的。。。不知道怎么就成这样了
