### ISSUE TITLE
[Feature Request] How to upload media file mp4 or .wmv with el-upload

### ISSUE THREAD

**Issue by thandonguocmo2020** [ElemeFE/element#6545]
### Existing Component
Yes

### Component Name
 el-upload

### Description

I did not find a tutorial about uploading video files

**Comment by Leopoldthecoder** [comment]
Upload doesn't care what file type you're uploading. You can upload whatever file you want.

**Comment by thandonguocmo2020** [comment]
Your help ! Configure how to only be allowed to upload a file. I want to prevent second file upload or have errors occured.

**Comment by thandonguocmo2020** [comment]
A silly question but i am new ! Thanks your
