### ISSUE TITLE
The [Feature Request] DateTimePicker date time picker component is not compatible. The safari 10.1.2 version cannot be selected

### ISSUE THREAD

**Issue by Cherbim1992** [ElemeFE/element#6546]
### Existing Component
是

### Component Name
DateTimePicker 日期时间选择器

### Description
在更新element 3.10.10版本后 DateTimePicker 不兼容 safari 在safari浏览器中 无法选中 打开插件 不能赋值  在其他浏览器是可以的 不知道大家是不是有同样的问题

**Comment by Leopoldthecoder** [comment]
Element does not have a `3.10.10` version, and issues without a reproduction link will be closed directly.
