### ISSUE TITLE
【特性需求】复合型输入框如何后置两个按钮 ？

### ISSUE THREAD

**Issue by SteveCruise** [ElemeFE/element#6547]
### Existing Component
是

### Component Name
el-input

### Description
复合型输入框目前只能前置和后置一个组件，如何后置两个按钮呢？
比如聊天输入框，后置两个按钮，一个发送，一个清除。这种场景如何实现呢？

**Comment by Leopoldthecoder** [comment]
请自行通过 CSS 实现。

**Comment by SteveCruise** [comment]
这。。。。。。。。。。。。。。我要是会的话。。。。。。。。。。。。。。还会用element ui么
