### ISSUE TITLE
[Feature Request] adds a row to the table

### ISSUE THREAD

**Issue by proshuai** [ElemeFE/element#6549]
### Existing Component
是

### Component Name
table

### Description
当点击新增按钮时，在表格顶部插入一行，此行的每个td为一个可以编辑的input，最后一列为确定和取消按钮。

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
