### ISSUE TITLE
[el-radio-group]:radio-group的change事件传递的参数与文档不一致

### ISSUE THREAD

**Issue by xjcloudy** [ElemeFE/element#655]
文档上说。change事件会传递一个参数，为选中的 Radio label 值。
但是实际应用中发现。并没有传递。
![image](https://cloud.githubusercontent.com/assets/2074921/19718191/da5e0340-9b96-11e6-9661-0522ba37669c.png)

![image](https://cloud.githubusercontent.com/assets/2074921/19718175/c8704c06-9b96-11e6-9489-d498a0e41fb8.png)

version:rc7

**Comment by jikkai** [comment]
使用`@change`取代原生的`@change.native`事件

**Comment by xjcloudy** [comment]
thx @jikkai  确实是这样的

**Comment by SilkYer** [comment]
@jikkai 你好，测试了一下 ，<el-checkbox>能用@change，但是<el-radio>居然要用native修饰，element文档上写着checkbox和radio都能用change呀 并没有提到需要.native 花了大力气才发现要加修饰符。。而且还是radio才要加native而checkbox却不需要？？

**Comment by SilkYer** [comment]
@jikkai 你好，测试了一下 ，el-checkbox能用@change，但是el-radio居然要用native修饰，element文档上写着checkbox和radio都能用change呀 并没有提到需要.native 花了大力气才发现要加修饰符。。而且还是radio才要加native而checkbox却不需要？？

**Comment by Leopoldthecoder** [comment]
@SilkYer 有问题请开新 issue，并提供 demo。
