### ISSUE TITLE
[Feature Request] Slot for column-header customisation

### ISSUE THREAD

**Issue by eddow** [ElemeFE/element#6550]
### Existing Component
Yes

### Component Name
table-column

### Description
I saw many discussions about having custom headers in columns and a generic solution exists with the `renderHeader` property of the `<el-table-column>` component.

Though, the whole is still a little bit tricky to get working and I was wondering if it would be a huge change (hint: I had a quick look and it seemed short, that is why I ask) to add a named slot in `el-table-column` to describe the header - indeed, exactly like it is done for the cell content.

```
<el-table-column ...>
 <template slot="header" scope="column">
  ...
 </template>
 <template scope="row">
  ...
 </template>
</el-table-column>
```

It can of course be done beside the `renderHeader` property even if both cannot be used at the same time. I think this would highly facilitate custom usage of the `el-table` element

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this.
