### ISSUE TITLE
The summary-method method of the [Bug Report] Table component will be called many times

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/element#6552]
### Element UI version
1.4.2

### OS/Browsers version
macOS X 10.12

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/tjom473L/1/](https://jsfiddle.net/tjom473L/1/)

### Steps to reproduce
1.打开重现链接，然后打开浏览器的控制台
2.刷新页面，查看控制台输出，这时会显示 summary-method 方法被触发的次数

### What is Expected?
该方法被调用一次即可

### What is actually happening?
经实际测试，该方法被触发的次数为 table行数的3-5倍，当数据量比较多时，会有性能问题

**Comment by Leopoldthecoder** [comment]
Duplicate of #6276
