### ISSUE TITLE
[Bug Report] sets check-strictly to true, dynamically loading the node of the tree, and the selected state of the node is incorrect

### ISSUE THREAD

**Issue by DreamTear** [ElemeFE/element#6553]
### Element UI version
1.4.2

### OS/Browsers version
win10/chrome 60.0.3112.101（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/7j58b42k/](https://jsfiddle.net/7j58b42k/)

### Steps to reproduce
1、展开region1（不要选中，因为这里要展示对父节点和子节点的影响）
2、选中zone1；
3、点击展开zone1节点，发现子节点是选中的状态，父节点状态也发生了变化（期望状态是不选中的，因为设置了check-strictly为true）

### What is Expected?
期待节点能够根据check-strictly的设置来进行选择父节点或子节点

### What is actually happening?
动态获取树的时候，当前节点会影响父子节点的选中状态

**Comment by Leopoldthecoder** [comment]
This is already fixed and will be included in the next major version.

**Comment by zw900420** [comment]
@Leopoldthecoder  this bug is not fixed in version 1.4.3?  I updated to 1.4.3 this bug is still in
