### ISSUE TITLE
[Bug Report] Error document el-upload  attribute show-upload-list not found. 

### ISSUE THREAD

**Issue by thandonguocmo2020** [ElemeFE/element#6558]
### Element UI version
1.4.2

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/hoanghiep/cwucaq61/](https://jsfiddle.net/hoanghiep/cwucaq61/)

### Steps to reproduce
document write show-upload-list set value true and false.
in when using is :show-file-list="false"

### What is Expected?
fix or write document

### What is actually happening?
fix or write document Attributes show show-upload-list

**Comment by Leopoldthecoder** [comment]
Fixed in #6567
