### ISSUE TITLE
select里的option不能随数组更改而改变

### ISSUE THREAD

**Issue by 472643931** [ElemeFE/element#656]
### ElementUI version
1.0.0-rc.7 

### OS/Browers version
Chrome 53

### Vue version
 2.0.3

### Steps to reproduce
```js
        <el-col :span="4">
            <el-select v-model="province" >
              <el-option v-for="item in provincedata" :label="item.name" :value="item">
              </el-option>
            </el-select>
          </el-col>
          {{ province.sub |json }}
          <el-col :span="4">
            <el-select v-model="city" >
              <el-option v-for="item in province.sub" :label="item.name" :value="item">
              </el-option>
            </el-select>
          </el-col>
```

### What is Expected?
select级联
### What is actually happening?
province是改变了，但是在el-option中没有重新渲染

**Comment by jikkai** [comment]
`v-for`渲染出来的列表需要带上`key`属性，且`key`属性具有唯一性

参考：http://element.eleme.io/#/component/select
远程搜索：
……需要注意的是，如果`el-option`是通过`v-for`指令渲染出来的，此时需要为`el-option`添加`key`属性，且其值需具有唯一性……

**Comment by Leopoldthecoder** [comment]
@472643931 请参照楼上的方法。
