### ISSUE TITLE
[Bug Report] select exists bug, select is located at top time, and there is bug

### ISSUE THREAD

**Issue by dsky1990** [ElemeFE/element#6561]
### Element UI version
1.4.2

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[github.com](github.com)

### Steps to reproduce
select存在bug，select位于顶部时间，存在bug

### What is Expected?
select存在bug，select位于顶部时间，存在bug

### What is actually happening?
select存在bug，select位于顶部时间，存在bug

**Comment by dsky1990** [comment]
图片如下
![image](https://user-images.githubusercontent.com/1579516/29409523-2b0c7d5a-837f-11e7-933f-f8bb8d198685.png)

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
