### ISSUE TITLE
[Bug, Report], Switch, component, on-value, only, work, as, string, value.,, Failed, in, number, type

### ISSUE THREAD

**Issue by yorkane** [ElemeFE/element#6564]
### Element UI version
1.4.2

### OS/Browsers version
Win10/Chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/cs92cdye/4/](https://jsfiddle.net/cs92cdye/4/)

### Steps to reproduce
//offical site code demo below, 官方代码实例如下，将on-value 修改为数字1
@import url("//unpkg.com/element-ui@1.4.2/lib/theme-default/index.css");
<script src="//unpkg.com/vue/dist/vue.js"></script> 
<script src="//unpkg.com/element-ui@1.4.2/lib/index.js"></script>
<div id="app">
<el-tooltip :content="'Switch value: '   value3" placement="top">
  <el-switch v-model="value3" on-color="#13ce66" off-color="#ff4949" on-value="1" off-value="0">
  </el-switch>
</el-tooltip>
{{value3}}
</div>
{{value3}}
var Main = {
    data() {
      return {
        value3: 1
      }
    }
  };
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')

### What is Expected?
Show switch at [" ON "] mode 显示switch 在 ON的状态

### What is actually happening?
Switch at [" OFF "] mode

**Comment by wacky6** [comment]
You need to use `:on-value='1'` to bind a number. Please read vue documentation.

**Comment by yorkane** [comment]
Thanks you! Solved my problem.

I have to read more about vue~~~
