### ISSUE TITLE
When the [Bug Report] pop-up component is triggered, the scroll bar is removed, resulting in changes in view

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#6566]
### Element UI version
1.4.2

### OS/Browsers version
chrome55

### Vue version
2.4.2

### Reproduction Link
[https://luosijie.github.io/vue-manager/#/editable-table](https://luosijie.github.io/vue-manager/#/editable-table)

### Steps to reproduce
这个是一个别人的项目，但是和我反馈的bug一致
点击页面的 edit 按钮， 然后触发弹窗 整个页面会丢掉原来的滚动条
页面头部的admin 按钮也会发生偏移
之前提过issue 链接放错了

### What is Expected?
当弹窗触发的时候，保留之前原有的滚动条， 没有滚动条就不管它， 避免版式因此发生偏移

### What is actually happening?
弹窗触发， 页面版式会发生偏移

**Comment by Leopoldthecoder** [comment]
把 `lock-scroll` 关掉就行。

**Comment by wonderFF** [comment]
尴尬。。
