### ISSUE TITLE
[Bug Report] when I use setCheckedKeys method,all  leafnode which parent should be check are checked

### ISSUE THREAD

**Issue by 32167t** [ElemeFE/element#6570]
### Element UI version
1.4.2

### OS/Browsers version
WIN10/chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/h4zhwuue/1/](https://jsfiddle.net/h4zhwuue/1/)

### Steps to reproduce
1.decalre  a tree,
2.call setCheckedKeys with node key one of tree's parent node,
3.you can find all leaf-node are checked

### What is Expected?
only parent is checked

### What is actually happening?
parent-node and all leaf-node are both checked

**Comment by Leopoldthecoder** [comment]
Use `check-strictly`: https://jsfiddle.net/h4zhwuue/2/
