### ISSUE TITLE
The [Bug Report] el-table v-loading state opens the el-dialog Z-index problem

### ISSUE THREAD

**Issue by ms2146** [ElemeFE/element#6579]
### Element UI version
1.4.2

### OS/Browsers version
win7/chrome 59.0.3071.86

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/vynp2e2b/](https://jsfiddle.net/vynp2e2b/)

### Steps to reproduce
demo链接中点击打开Dialog按钮

### What is Expected?
el-dialog 的弹出层应在el-loading-mask之上

### What is actually happening?
el-loading-mask在el-dialog 的弹出层之上

**Comment by Leopoldthecoder** [comment]
这种情况需要自己覆盖下样式，https://jsfiddle.net/vynp2e2b/4/

**Comment by Korri** [comment]
Ran into the same issue today, any reason this `z-index: 1000;` is not the default?

**Comment by Leopoldthecoder** [comment]
@Korri Because there are scenarios where Loading needs to go above Dialog, e.g. when some operations in a Dialog triggers a Loading (maybe a fullscreen one).

It's difficult, if not impossible, for us to decide which one should be on top. So you may have to handle it yourself.
