### ISSUE TITLE
In [Bug Report] tree lazy mode, get the first child node under the parent node

### ISSUE THREAD

**Issue by fei316** [ElemeFE/element#6583]
### Element UI version
1.4.2

### OS/Browsers version
win7/chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
layz模式下 在页面初始化完成后 点击第一级的父节点，这时下级的子节点也被选中了 但是取获取不到

### What is Expected?
layz模式下 在页面初始化完成后 点击第一级的父节点，获取到所有选中的子节点

### What is actually happening?
实际在check-change 事件中只能获取到被选中的父节点

**Comment by Leopoldthecoder** [comment]
`check-change` 表示某个节点的选中状态发生了变化，且仅响应用户交互。可以在它的回调里通过 `getCheckedNodes` 获取所有选中节点（可能需要 setTimeout）。
