### ISSUE TITLE
[Feature Request] A tags input component

### ISSUE THREAD

**Issue by cgarnier** [ElemeFE/element#6585]
### Existing Component
No

### Component Name
ElTags

### Description
Add a component to handle tags into a form.
A list of tag with a button to add more tag.
Should looks to this el-tag example: http://element.eleme.io/#/en-US/component/tag#edit-dynamically

**Comment by Leopoldthecoder** [comment]
We have no plan to add a component for this.

**Comment by cgarnier** [comment]
hey,
I m pretty sure i m not the only one that need this component.
Some other ui libs already have it.
Like angular materials chips: https://material.angularjs.org/latest/demo/chips
