### ISSUE TITLE
[Feature Request] el-table 中 expand 事件参数问题

### ISSUE THREAD

**Issue by Zohar727** [ElemeFE/element#6592]
### Existing Component
是

### Component Name
el-table

### Description
我在官方文档看到expand有两个参数row,expanded，可是在绑定expand事件时 @expand = expandChange(row, expanded)，会提示row和expanded not defined

**Comment by muzi131313** [comment]
嗨，添加expand属性是在
````
<el-table-column type="expand">
</el-table-column>
````
中，expand事件添加是在
````
<el-table @expand="addressExpand">
</el-table>
````
事件是：
````
addressExpand(row, expanded) {
        this.log(row, expanded);
},
````
官方的文档，没有详细说明，还以为事件是绑定在el-table-column上呢
