### ISSUE TITLE
[Bug Report] table max-height can't turn higher from short

### ISSUE THREAD

**Issue by snowheaven1995** [ElemeFE/element#6594]
### Element UI version
1.4.2

### OS/Browsers version
Macos10.12.6 /firefxox 55.0.2 

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
set table attribute max-height be a variable like '  :max-height="adjustHeight" ' adjustHeight  is change by  browser height , then adjust browser height , turn height browser shorter than table height ,and then,turn it back,make browser height more than table height, you will see this bug, this table height will stay in the shortest height

### What is Expected?
turn table max height higher from short with adjust browser height.

### What is actually happening?
table max height stay in shortest height

**Comment by Leopoldthecoder** [comment]
@snowheaven1995 Your demo is black.

**Comment by qpxtWhite** [comment]
I update the demo
https://jsfiddle.net/whitewang/goy7tf23/
If anyone can take a look
The 'decrease button' works well but the 'increase button' not work

**Comment by liril-net** [comment]
Fixed in [Carbon](https://github.com/ElemeFE/element/releases/tag/v2.0.0)
