### ISSUE TITLE
[Feature Request] tree components do very well. Can the node property be published in the document?

### ISSUE THREAD

**Issue by dongsuju** [ElemeFE/element#6597]
### Existing Component
Yes

### Component Name
tree

### Description
tree组件做的很不错的，node属性可以在文档中公开一下吗？哪些是我们可以使用的，在后续版本中不会去掉的。谢谢

**Comment by Leopoldthecoder** [comment]
Fixed in #6601

**Comment by Leopoldthecoder** [comment]
我们会在下一个大版本中评估。
