### ISSUE TITLE
When the [Bug Report] Dialog title is empty, the CSS problem

### ISSUE THREAD

**Issue by nicolegithub** [ElemeFE/element#6598]
### Element UI version
1.4.2

### OS/Browsers version
all

### Vue version
2.4.2

### Steps to reproduce
Dialog 标题为空的时候

### What is Expected?
内容的padding-top 不要挡住关闭按钮

### What is actually happening?
dialog 的header 高不见了，导致内容的padding-top挤了上去挡住 x 按钮
解决：
dialog.css    和 index.css 文件    .el-dialog__header  加个 overflow:hidden 或其他方式清除浮动

**Comment by Leopoldthecoder** [comment]
Fixed in #6601
