### ISSUE TITLE
message-box Uncaught (in promise) cancel

### ISSUE THREAD

**Issue by Hero-or-Zero** [ElemeFE/element#6599]
customization's message-box click 'Cancal' throw error : `Uncaught (in promise) cancel`

**Comment by CntChen** [comment]
The **default callback**  of message-box is a Promise, and will emit `Promise.reject` for `cancel` event, take a look at [this source code][source code].
So the best practice is customizing your callback event.
```
this.$msgbox({
  message: 'moonlight',
 showCancelButton: true,
  callback: () => {},
});
```

[source code]: https://github.com/ElemeFE/element/blob/v1.4.4/packages/message-box/src/main.js#L57
