### ISSUE TITLE
select选择器, 控制大量警告

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#66]
git clone仓库后, npm run dev, 在select组件里, 点任何select, 都报大量类似`[Vue warn]: Duplicate presense of slot "default" found in the same render tree - this will likely cause render errors. (found in component <ElSelect>)`的警告.

**Comment by QingWei-Li** [comment]
目前 Vue rc4 和 rc5 都有一个 bug 导致这些问题，所以 package.json 里说定了 vue 的版本是 rc3
但是你这个应该是高版本的 vue 导致的

**Comment by lincenying** [comment]
谢谢解答...
因为安装完后, dev时报vue和vue-template-compiler版本不符, 所以就把vue升到了rc5

**Comment by QingWei-Li** [comment]
这三个全都锁定版本了啊，为啥还会版本不符。。。
```json
   "vue": "2.0.0-rc.3",
    "vue-loader": "9.3.2",
    "vue-template-compiler": "2.0.0-rc.3"
```

**Comment by dingyiming** [comment]
我也有遇到，原来是vue的问题

**Comment by lincenying** [comment]
vue-loader 9.3.2里的依赖中, vue-template-compiler 是 rc.5版本

**Comment by Leopoldthecoder** [comment]
@lincenying @dingyiming 重新拉一下代码吧，已经升级到 Vue rc.6 了。
