### ISSUE TITLE
button 组件 上怎么添加点击事件，

### ISSUE THREAD

**Issue by changmingdeng** [ElemeFE/element#660]
`<el-button type="primary">主要按钮</el-button>`

  这个上面怎么加事件

`<el-button  v-on:click="todo" type="primary">`

这样加事件点击没反应，，，求救

**Comment by Leopoldthecoder** [comment]
提交 issue 前请务必查看 FAQ：https://github.com/ElemeFE/element/blob/master/FAQ.md。
