### ISSUE TITLE
[Bug Report] Timepicker don't work with moment js

### ISSUE THREAD

**Issue by lfaveur** [ElemeFE/element#6607]
### Element UI version
1.4.2

### OS/Browsers version
Ubuntu 16.04

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/garlacour/etnnmw98/](https://jsfiddle.net/garlacour/etnnmw98/)

### Steps to reproduce
I use moment to have dates object, thats why i added it in the fiddle

### What is Expected?
i have not the select box to choose time when i use moment

### What is actually happening?
I can't choose the time when i use moment, is it supported or I did something wrong ? because moment work with dateRange picker (https://jsfiddle.net/garlacour/4xfyfn1t/8/)...

**Comment by Leopoldthecoder** [comment]
You need to convert the moment object to a date object: https://jsfiddle.net/etnnmw98/1/ . TimePicker executes some date instance methods upon initiation.
