### ISSUE TITLE
[Feature Request] Input Mask

### ISSUE THREAD

**Issue by gimyboya** [ElemeFE/element#6608]
### Existing Component
Yes

### Component Name
Input, InputNumber

### Description
it would be awesome to have a directive for masking an input [Demo](https://vuejs-tips.github.io/vue-the-mask/)
this repo maybe helpful as a [start](https://github.com/insin/inputmask-core)

**Comment by thearabbit** [comment]
+1

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this.

**Comment by UknowHui** [comment]
+1

**Comment by smartfox87** [comment]
+1
