### ISSUE TITLE
[Feature, Request], How, to, add, title, property, to, el-input, component?

### ISSUE THREAD

**Issue by gemmi** [ElemeFE/element#6609]
### Existing Component
是

### Component Name
el-input

### Description
windows/chrome60.0
failed to add title to el-input component like this:
<el-input  title = "myname" v-model="myname" placeholder="please input your name"></el-input>
'myname' is displayed as a string but not a variable expected.

**Comment by Leopoldthecoder** [comment]
You need to add `:` before `title`. Please read the Vue documentation before using Element.
