### ISSUE TITLE
树形控件

### ISSUE THREAD

**Issue by tworain666** [ElemeFE/element#661]
elementUI的树形控件里面怎么获取已经选中的数组？我看API里面有提供一个getCheckedNodes可是不知道怎么使用？
![image](https://cloud.githubusercontent.com/assets/23076951/19725639/539fc992-9bb9-11e6-8620-0affdb9bf113.png)

**Comment by Leopoldthecoder** [comment]
在 Tree 的实例上调用。比如模板里：
```html
<el-tree ref="tree"></el-tree>
```
那么可以
```javascript
this.$refs.tree.getCheckedNodes()
```

**Comment by jinjinwa** [comment]
tree放在弹出框中，弹框是隐藏状态，这个时候调用 this.$refs.tree.setCheckedKeys 会提示为定义。有什么解决方案么。同样表单放在隐藏的弹框中，调用 this.$refs.xxx 也会报错。
