### ISSUE TITLE
[Feature, Request], No, input, events, been, fired, when, have, I, just, typed,, in, the, input, box

### ISSUE THREAD

**Issue by futurexiong** [ElemeFE/element#6611]
### Existing Component
是

### Component Name
Time-Picker

### Description
Time Picker provides editable and clearable attributes, when I just type time string in input box, no input or change event fires, means the bind value has not been updated, I have to use the scroll panel to select the time

**Comment by wacky6** [comment]
Please provide a reproduction link.

**Comment by futurexiong** [comment]
手动在输入框里输入时间没有触发原生input和change事件更新v-model绑定的值，2.4.2版本，这个不需要链接展示吧？还是说我有什么属性用错了？

**Comment by wacky6** [comment]
你用了element那是组件的input和change，你说的原生指什么？

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
