### ISSUE TITLE
[Bug Report] type enter in input triggers native form submit event in el-form

### ISSUE THREAD

**Issue by jimliang** [ElemeFE/element#6614]
### Element UI version
1.4.2

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/jimliang/pj71jkyw/472/](https://jsfiddle.net/jimliang/pj71jkyw/472/)

### Steps to reproduce
type enter in input and page will be refresh

### What is Expected?
do nothing

### What is actually happening?
 page will be refresh

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/473/
