### ISSUE TITLE
[Feature Request] Wish a beautiful scrollbar for table

### ISSUE THREAD

**Issue by stevobm** [ElemeFE/element#6618]
### Existing Component
No

### Component Name
scrollbar

### Description
I note that there is a beautiful scrollbar in component such as the dropdown of an autocomplete input. So why not develop a same scrollbar for the table component? Or is it a good idea to provide a standalone scrollbar component such like the "perfect-scrollbar"(http://noraesae.github.io/perfect-scrollbar/)?

**Comment by imkiven** [comment]
+1

**Comment by Leopoldthecoder** [comment]
Table alone may consume a great deal of computing resources, adding the scrollbar component, which listens to some frequently triggered events, can lead to serious performance issues. So we'll probably keep it as is.

**Comment by stevobm** [comment]
We still wish an optional "elegant" scrollbar is supported, which could be enabled when the amount of data is small. Since our theme is customized now, my workmates have to add the scrollbar manually, which may result in more bugs and worse experience.
