### ISSUE TITLE
The rendering of [Feature Request] paging components on Firefox

### ISSUE THREAD

**Issue by zylbiubiubiu** [ElemeFE/element#6622]
### Existing Component
是

### Component Name
el-pagination__editor

### Description
[http://ondc8g8tu.bkt.clouddn.com/17-8-22/91745689.jpg](url)
如图，多了两个小按钮一样的东西，我发现是input标签中的 type = "number" 属性搞的鬼，可否帮忙更改为text属性？
具体文件在pagination.js文件中。

**Comment by Leopoldthecoder** [comment]
Fixed in #6623

**Comment by chendayang** [comment]
in element2.0.2, it still have two small buttons in firefox,  then i checked the dom, find that:
the type of input, is still  number, not text

**Comment by Leopoldthecoder** [comment]
@chendayang It'll be fixed in 2.0.4
