### ISSUE TITLE
[Bug Report], when you control form items with V-IF, reset the form Cannot read property'indexOf'of undefined

### ISSUE THREAD

**Issue by QianWenW** [ElemeFE/element#6628]
### Element UI version
1.4.2

### OS/Browsers version
windows 10/ chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/0omanze0/](https://jsfiddle.net/0omanze0/)

### Steps to reproduce
1.点击隐藏
2.点击重置

### What is Expected?
能够重置

### What is actually happening?
报错

**Comment by Leopoldthecoder** [comment]
需要加 `prop`：https://jsfiddle.net/0omanze0/1/

**Comment by QianWenW** [comment]
加了prop的话，提交表单的时候还是回去验证这个字段，如果这个时候添加了其他的验证就会验证不通过
