### ISSUE TITLE
[Bug Report] [Bug Report] InputNumber When size = small, the button's position is not normal

### ISSUE THREAD

**Issue by chinaxy** [ElemeFE/element#6629]
### Element UI version
1.4.2

### OS/Browsers version
WIn10 1704 Chrome 60 Firefox 55 Edge IE11

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/uwvqsuuL/](https://jsfiddle.net/uwvqsuuL/)

### Steps to reproduce
https://jsfiddle.net/uwvqsuuL/

### What is Expected?
When size = small, the button's position is not normal

### What is actually happening?
*

**Comment by wacky6** [comment]
@Leopoldthecoder 
![image](https://user-images.githubusercontent.com/9319556/29553005-eb46461a-875c-11e7-80f6-a116a3ba02e5.png)

Can fix the problem, not sure if this is a good idea.

**Comment by Leopoldthecoder** [comment]
Fixed in #6634
