### ISSUE TITLE
[Feature, Request], dynamic, action, attr, in, upload, component

### ISSUE THREAD

**Issue by YUFENGWANG** [ElemeFE/element#6630]
### Existing Component
是

### Component Name
upload

### Description
Can action attribute be modified when uploading file using upload component? I need to upload files with upload component, but I want to dynamic change the action url , cause there are extra query params I need to append to the url, such as `http://test.server/post?tag=xxx`, the value of tag is dynamic added.

**Comment by YUFENGWANG** [comment]
what the heck is this freaking bot ? translate my question totally wrong... not intelligence enough.

**Comment by Leopoldthecoder** [comment]
Use a variable: https://jsfiddle.net/rz814e42/
