### ISSUE TITLE
[Feature Request] How can i set default datas for table filter ?

### ISSUE THREAD

**Issue by SimonLeeee** [ElemeFE/element#6633]
### Existing Component
Yes

### Component Name
Table

### Description
I want to filter table datas when it loaded.
So I need to set default datas in table filter.
Is any ways can do that ?

**Comment by JamesCrann** [comment]
Perhaps change the filter property to take an extra 'selected' option : Array[{ text, value, selected}] ?

**Comment by liril-net** [comment]
You can set `filtered-value` of `el-table-column` which is an array of filters' value
