### ISSUE TITLE
vuejs+jsx+element:在树形控件中加select下拉框，选择相应值后框中未取到

### ISSUE THREAD

**Issue by jessica127** [ElemeFE/element#6635]
renderAddRole(h, { node, data, store }) {
      console.log("node=%o data=%o store=%o",node,data,store);
      if(node.level == 1){
        return (
          <span>
            <span>
              <span>{node.label}</span>
            </span>
          </span>
        );
      }
      return (
        <span>
          <span>
            <span>{node.label}</span>
          </span>
          <span style="margin-left: 20px">
            <el-select value={this.addStaffForm.staffRole} placeholder="请选择角色" size="mini" style={{color: '#ff0000', fontSize: '14px'}} on-change={this.aaselect}>
              {this.rolelist.map((roleOption) => <el-option label={roleOption.label} value={roleOption.value}></el-option>)}
            </el-select>
          </span>
        </span>
      );  
    },

**Comment by domsgit** [comment]
在父组件监听函数中重新触发一次更新操作就可以回显了。比如简单粗暴地：
`this.addStaffForm = JSON.parse(JSON.stringify(this.addStaffForm))`
