### ISSUE TITLE
[Bug Report], when the table has fixed, slot has bug

### ISSUE THREAD

**Issue by imkiven** [ElemeFE/element#6642]
### Element UI version
1.4.1

### OS/Browsers version
Win10 Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/8mvnsa22/1/](https://jsfiddle.net/8mvnsa22/1/)

### Steps to reproduce
表格无fixed的时候无bug，
当fixed的时候，slot部分会有问题，
同时是当数据是动态获取的时候，会出现左侧fixed部分不显示，被slot覆盖

### What is Expected?
fixed的时候，slot能正常显示，不影响fixed部分

### What is actually happening?
fixed的时候，slot不能正常显示，并且当数据动态获取的时候，fixed部分显示不了

**Comment by imkiven** [comment]
当数据动态获取的时候，slot部分这么显示

**Comment by GalacticWeb** [comment]
+1!

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0: https://jsfiddle.net/8mvnsa22/7/
