### ISSUE TITLE
How is the column el-table-column of [Feature Request] table component type='selection'set disabled?

### ISSUE THREAD

**Issue by kangming007** [ElemeFE/element#6646]
### Existing Component
是

### Component Name
table

### Description
table组件的el-table-column  type=‘selection‘ 的这一列怎么设置禁用  使复选框默认不能被勾选 我按照el-button组件 加上disabled 这个属性 没有生效  正确的方式应该怎么设置求告知

**Comment by James-jun06** [comment]
type=''selection‘有一个方法可以的selectable，如下：
<el-table-column type="selection" width="55" :selectable="selectFun">
selectFun中返回false就是不能被勾选的行

**Comment by wuyuedefeng** [comment]
怎样根据当前行的数据禁止是否可以勾选呢，你这样设置，看起来只能写死返回 true，false,没啥意义，为什么不能在template中设置呢

**Comment by OlabodeAbesin** [comment]
A proper translation of this feature.
Reason: I stumbled on this page when i was trying to select all rows and pass the data.

By using this attribute, :selectable="YourFunction", you are able to know when the select all button is marked.
