### ISSUE TITLE
[Bug, Report], table, expand-row-keys, is, not, work

### ISSUE THREAD

**Issue by jinan5694** [ElemeFE/element#6649]
### Element UI version
1.4.2

### OS/Browsers version
win8/chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/jinan5694/hpqvyL4v/2/](https://jsfiddle.net/jinan5694/hpqvyL4v/2/)

### Steps to reproduce
no need
不需要重现

### What is Expected?
the first and second row of the table expanded.
第一和第二行展开（expandedRow 中的行展开）

### What is actually happening?
no row expanded.
没有行展开

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0: https://jsfiddle.net/hpqvyL4v/10/

**Comment by industral** [comment]
Doesn't work with async data https://jsfiddle.net/hpqvyL4v/36/

**Comment by wd4219** [comment]
同问

**Comment by wd4219** [comment]
you can use v-if on the el-table，delay table render

**Comment by FreezingRiver** [comment]
> Doesn't work with async data https://jsfiddle.net/hpqvyL4v/36/

you need add 'default-expand-all' attribute
