### ISSUE TITLE
本地build 运行npm run dist后lib文件夹替换官方lib文件夹后出错

### ISSUE THREAD

**Issue by cnweibo** [ElemeFE/element#665]
我希望基于element做下些许改动匹配自己的需要，我做了以下工作：
1.在我的vue项目中 npm install element-ui@next -S
2. 运行element ui官方测试代码到我的项目中
`
import Vue from 'vue'
import { Radio } from 'element-ui'
import { Checkbox } from 'element-ui'
import { CheckboxGroup } from 'element-ui'

new Vue({
el: '#app',
components: {
KRadio:Radio, KCheckbox: Checkbox, KCheckboxGroup:CheckboxGroup
},
data: function () {
return {
radio: '',
checked: true,
checkList: ['选中且禁用','复选框 A']
}
}
})
`
3.由于我发现了一个bug，也被element团队解决，见： https://github.com/ElemeFE/element/issues/634
但是你们计划放到rc.8版本中，我由于等不及，需要尽快引入你们的bugfix，所以决定自己编译包含你们的bugfix的element生产版本，所以我做了以下操作：
 3.1 clone了element.git后，安装依赖，运行npm run dist
 3.2 随后替换生成的lib文件夹到第一步中的node_modules/element-ui目录
4. 运行我自己的构建环境npm run dev(基于vue-cli做的脚手架)，但是却开始出现下面的错误（注意：从element官方 npm install时不会出现这个错误）
·
ERROR in ./~/element-ui/lib/element-ui.common.js
Module not found: Error: Can't resolve 'element-ui/lib/mixins/emitter' in 'C:\Users\Administrator\devenvironment\Code\newkidsitfromscratch\resources\assets\js\vueapp\node_modules\element-ui\lib'
 @ ./~/element-ui/lib/element-ui.common.js 1818:18-58
 @ ./src/fetest.js
 @ multi fetest
·
说是emitter找不到，我看了下重新生成的lib目录，确实不存在mixin目录

请问是不是构建有问题？还是其他问题？

一句话：我希望做本地build，并且启用它（使用import { Checkbox } from 'element-ui'这种模式）

这个困扰我一天了，多谢澄清解决
谢谢~！

**Comment by QingWei-Li** [comment]
感谢提醒，是 bug

执行 `npm run dist` 时候会去执行，`npm run build:utils`，这里是会编译 `src/` 目录下的文件，但是漏掉了 mixins 目录，你可以把 `build:utils` script 改成

```
babel src --out-dir lib --ignore index.js
```

**Comment by cnweibo** [comment]
@QingWei-Li ok, 按照你的建议修改后运行npm run dist出现以下错误
`
C:\Users\Administrator\devenvironment\Code\element\build\cooking.demo.js
  4:5  error  'Components' is assigned a value but never used  no-unused-vars
`
我现在暂时把lint这个脚本任务注释掉了，现在可以工作了, #634 这个fix已经有了，现在可以工作了~~

希望能够尽快把这个bug也解决，并且出官方的rc.8版本

谢谢你们的努力！

**Comment by QingWei-Li** [comment]
那个只是个 lint 而已，已经有人修了 https://github.com/ElemeFE/element/pull/654

**Comment by cnweibo** [comment]
@QingWei-Li , 不好意思，这个本地npm run dist然后覆盖lib到我自己的node_modules/element-ui/lib 目录后，貌似是可以工作了，但是css好像没有加载进来，是什么原因？组件都长的很丑陋

**Comment by QingWei-Li** [comment]
有 `lib/theme-default` 目录么，执行 `npm run dev` 启动后组件显示正常么？控制台有无报错？组件长啥样了？

**Comment by cnweibo** [comment]
有lib/theme-default目录的，在element开发库的地方执行npm run dev可以启动， http://localhost:8085/#/正常显示，功能也正常，控制台无报错，组件长的就是原生的checkbox+label的模样，黑色的。

**Comment by QingWei-Li** [comment]
我明白了，你没有引入样式。

如果需要自动引入样式需要配置 `babel-plugin-compnent` 一起使用

**Comment by cnweibo** [comment]
修改.babelrc后`{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime",["component", [
              {
                "libraryName": "element-ui",
                "styleLibraryName": "theme-default"
              }
            ]]],
  "comments": false
}`
css可以了，但是貌似 #634 这个fix没有了，checkbox group中的checkbox无法选中，不知道是什么原因
还有什么建议吗？

**Comment by QingWei-Li** [comment]
不清楚你怎么用的。。。我这边本地 build 后，到新建的项目下执行
```shell
npm install /Users/我的项目目录/Documents/projects/eleme/element
```

然后写
```javascript
import Vue from 'vue'
import { CheckboxGroup, Checkbox } from 'element-ui'
import App from './App.vue'

Vue.use(Checkbox)
Vue.use(CheckboxGroup)

new Vue({
  el: '#app',
  render: h => h(App)
})
```
使用正常
![image](https://cloud.githubusercontent.com/assets/7565692/19734010/83fd4758-9bd8-11e6-8c45-c072260a1ae1.png)

**Comment by cnweibo** [comment]
我是直接copy lib来覆盖的，可能有部分功能是没有加进去的，我再试试，非常感谢，晚安！

**Comment by cnweibo** [comment]
@QingWei-Li ,  你的代码中使用的是 Vue.use的方式来应用的，这种情况下是ok的。
`    import { Radio } from 'element-ui'
    import { Checkbox } from 'element-ui'
    import { CheckboxGroup } from 'element-ui'
    import Vue from 'vue'
    Vue.use( Checkbox )
    Vue.use( CheckboxGroup )`
但是我的代码是通过local component方式来引入对应的component defination的，却不能工作啊，是bug吗？还是element-ui必须通过这种方式来引用？？
`
import { Checkbox } from 'element-ui'
    import { CheckboxGroup } from 'element-ui'
    export default {
        components: {
           KRadio:Radio, KCheckbox: Checkbox, KCheckboxGroup:CheckboxGroup
        }
}
`
