### ISSUE TITLE
[Bug Report] ElTableFooter fails to render when any column value has more than 20 decimal numbers

### ISSUE THREAD

**Issue by aarongarvey** [ElemeFE/element#6650]
### Element UI version
1.4.2

### OS/Browsers version
Windows 10/Chrome 60.0.3112.101 (Official Build) (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/474/](https://jsfiddle.net/pj71jkyw/474/)

### Steps to reproduce
Click Run on the jsfiddle, but basically all you need is a summary value with more than 20 decimal places

### What is Expected?
The footer of the table should render 'Total' on the left, and the sum of the currency values on the right.

### What is actually happening?
The footer is blank and an error is thrown:

[Vue warn]: Error in render function: "RangeError: toFixed() digits argument must be between 0 and 20"

found in

---> <ElTableFooter>
       <ElTable>
         <Root>
warn @ VM76 vue.js:485
handleError @ VM76 vue.js:568
Vue._render @ VM76 vue.js:4125
updateComponent @ VM76 vue.js:2542
get @ VM76 vue.js:2883
run @ VM76 vue.js:2960
flushSchedulerQueue @ VM76 vue.js:2728
(anonymous) @ VM76 vue.js:707
nextTickHandler @ VM76 vue.js:654
Promise resolved (async)
timerFunc @ VM76 vue.js:669
queueNextTick @ VM76 vue.js:717
queueWatcher @ VM76 vue.js:2815
update @ VM76 vue.js:2950
notify @ VM76 vue.js:784
reactiveSetter @ VM76 vue.js:1006
h.updateColumns @ index.js:formatted:7453
doLayout @ index.js:formatted:7106
boundFn @ VM76 vue.js:189
(anonymous) @ index.js:formatted:7120
s @ index.js:formatted:3697
setTimeout (async)
s @ index.js:formatted:3707
h.scheduleLayout @ index.js:formatted:7557
insertColumn @ index.js:formatted:7391
h.commit @ index.js:formatted:7586
mounted @ index.js:formatted:9589
callHook @ VM76 vue.js:2669
insert @ VM76 vue.js:3524
invokeInsertHook @ VM76 vue.js:5460
patch @ VM76 vue.js:5630
Vue._update @ VM76 vue.js:2418
updateComponent @ VM76 vue.js:2542
get @ VM76 vue.js:2883
Watcher @ VM76 vue.js:2872
mountComponent @ VM76 vue.js:2546
Vue$3.$mount @ VM76 vue.js:7854
Vue$3.$mount @ VM76 vue.js:10057
(anonymous) @ Inline Babel script:38
run @ VM75 babel.js:60802
check @ VM75 babel.js:60868
loadScripts @ VM75 babel.js:60909
runScripts @ VM75 babel.js:60936
transformScriptTags @ VM75 babel.js:324
VM76 vue.js:572 RangeError: toFixed() digits argument must be between 0 and 20
    at Number.toFixed (<anonymous>)
    at index.js:formatted:8922
    at Array.reduce (<anonymous>)
    at index.js:formatted:8920
    at Array.forEach (<anonymous>)
    at Proxy.render (index.js:formatted:8904)
    at VueComponent.Vue._render (VM76 vue.js:4123)
    at VueComponent.updateComponent (VM76 vue.js:2542)
    at Watcher.get (VM76 vue.js:2883)
    at Watcher.run (VM76 vue.js:2960)

**Comment by Leopoldthecoder** [comment]
Fixed in #6660
