### ISSUE TITLE
[Bug Report] element-ui problem 

### ISSUE THREAD

**Issue by wuguanyu** [ElemeFE/element#6653]
### Element UI version
1.2.4

### OS/Browsers version
google

### Vue version
2.2.4

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
I use e-dialog tag in my children component, when I click the close tag. the dialog is not disappear,
I don't know why exsits this problem, who can help me solve problem 

### What is Expected?
I hope it is can disappear when I click the close tag

### What is actually happening?
It not disappear

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
