### ISSUE TITLE
[Bug Report] Carousel toggle button type problem

### ISSUE THREAD

**Issue by jun601011814** [ElemeFE/element#6654]
### Element UI version
1.4.2

### OS/Browsers version
Chrome 59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/dd29mu6f/](https://jsfiddle.net/dd29mu6f/)

### Steps to reproduce
1. 将carousel插件嵌套在form插件里面使用，点击指示器、上下页等按钮
2. 页面发生了页面跳转
（找到的原因是这些按钮没有指定type="button"，默认触发了form的提交，导致页面跳转）

### What is Expected?
希望点击指示器等按钮不会跳转链接

### What is actually happening?
点击指示器页面发生了跳转

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/dd29mu6f/1/
