### ISSUE TITLE
[Feature Request] 需要获取 "Slider 滑块" 的点击事件

### ISSUE THREAD

**Issue by llwslc** [ElemeFE/element#6661]
### Existing Component
是

### Component Name
Slider 滑块

### Description
我将"滑块"用作播放器的进度条, 每次拖动滑块的时候, 只会发送 change 事件, 而随着进度条在播放, 也会不断发送 change 事件, 我需要区分是用户拖动导致 change 事件还是数据绑定导致 change 事件, 所以需要"滑块"组件能发送 click 事件.

![image](https://user-images.githubusercontent.com/5865414/29611904-ffe3289c-8831-11e7-9e34-85f942393410.png)

**Comment by Leopoldthecoder** [comment]
下个大版本中 `change` 事件将仅响应用户交互。
