### ISSUE TITLE
[Bug Report] Unable to load Switch component on-demand

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#6662]
### Element UI version
1.4.2

### OS/Browsers version
Edge 15

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Following the Quick Start Guide on how to use on-demand loading of components, everything works fine except for the Switch component. Even though I am importing it along with other components (`import {..., Switch, ...} from 'element-ui'`) and instructing Vue to use it via `Vue.use(Switch)`, I get an error. Unfortunately I cannot provide a reproduction link because this is related to bundling via webpack.

### What is Expected?
Like with every other component in my project, the Switch element should appear on the page.

### What is actually happening?

> [Vue warn]: Unknown custom element: `<el-switch>` - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by Leopoldthecoder** [comment]
You can create a GitHub repo for this and give us the repo link.

**Comment by smares** [comment]
Nevermind, I just deleted the reference to Switch, typed it in again, recompiled, and it suddenly works.
