### ISSUE TITLE
[Bug Report] Input keypress.enter not work

### ISSUE THREAD

**Issue by hbicexp** [ElemeFE/element#6664]
### Element UI version
1.4.2

### OS/Browsers version
Windows Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/478/](https://jsfiddle.net/pj71jkyw/478/)

### Steps to reproduce
Press enter when input was focused.

### What is Expected?
Alert when enter pressed.

### What is actually happening?
input works fine but element-input wasn't.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/479/

https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components

**Comment by hbicexp** [comment]
Thanks a lot, and sorry for my useless issue.
