### ISSUE TITLE
[Feature, Request], drag, and, drop, sorting, components

### ISSUE THREAD

**Issue by cdw-me** [ElemeFE/element#6668]
### Existing Component
否

### Component Name
dragSort

### Description
Recommends adding drag and drop sorting components.
Function:drag/drop/shift up/shift down/to top/to bottom

**Comment by Leopoldthecoder** [comment]
We have no plan to add this.

**Comment by c5ms** [comment]
We need to "maximize", "minimize", "drag" these features,
whether it can be dragged and sorted.
By the way, yesterday completely modified the whole theme, found that many variables have not been used. For example, input height does not affect daterange
