### ISSUE TITLE
[Bug Report] Form validation doesn't work when using `el-input` component with 'on-icon-click' property[urgent]

### ISSUE THREAD

**Issue by LucasZheng** [ElemeFE/element#6669]
### Element UI version
1.4.2

### OS/Browsers version
chrome 60

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/ymh9La71/](https://jsfiddle.net/ymh9La71/)

### Steps to reproduce
1. Add `el-input` component  in `el-form` component
2. Add `:on-icon-click="submitForm('ruleForm')"` property in above `el-input` component

### What is Expected?
`el-form` work correctly.

### What is actually happening?
`el-form` doesn't work after add the `:on-icon-click="submitForm('ruleForm')"` in `el-input` component. It can't get the `ruleForm` ref and raise `Cannot read property 'validate' of undefined"` error.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ymh9La71/1/
