### ISSUE TITLE
[Bug Report] Slider in collapse component other than the active panels can't smooth drag

### ISSUE THREAD

**Issue by Tenderfeel** [ElemeFE/element#6672]
### Element UI version
1.4.2

### OS/Browsers version
Mac os sierra(10.12.6) Chrome(60)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/hvzeote0/3/](https://jsfiddle.net/hvzeote0/3/)

### Steps to reproduce
1. click collapse panel #2 or #3
2. drag the button of slider 

### What is Expected?
slider works properly

### What is actually happening?
slider does not work

**Comment by Leopoldthecoder** [comment]
Fixed in #6593
