### ISSUE TITLE
[Bug Report] el-input描述错误并且类型为数字时能输入字母‘e’

### ISSUE THREAD

**Issue by SteveCruise** [ElemeFE/element#6674]
### Element UI version
1.4.2

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/no-path](https://jsfiddle.net/no-path)

### Steps to reproduce
1 打开el-input
2 看最下面属性
3 type 的可选值不止text/textarea，我知道的就还有password，number

### What is Expected?
还有password，number

### What is actually happening?
没有password，number

**Comment by SteveCruise** [comment]
还有就是css样式并没有讲解，没有单独使用的情况是吧

**Comment by SteveCruise** [comment]
还有还有就是el-autocomplete无法指定type=number

**Comment by SteveCruise** [comment]
还有还有还有就是类型为number时能够输入字母‘e’
https://jsfiddle.net/tosbva3b/

**Comment by gdutwyg** [comment]
如果要求只能输入数字的话，你可以用el-input-number

**Comment by SteveCruise** [comment]
谢谢谢谢，@gdutwyg，但是带建议选项比较重要，el-autocomplete更符合

**Comment by SteveCruise** [comment]
el-time-picker is-range 时间范围无法选到次日

**Comment by Leopoldthecoder** [comment]
不要在一个 issue 里描述多个问题。

**Comment by SteveCruise** [comment]
@Leopoldthecoder 霸气
