### ISSUE TITLE
[Bug Report] Cannot import a single element

### ISSUE THREAD

**Issue by DmacMcgreg** [ElemeFE/element#6678]
### Element UI version
1.4.2

### OS/Browsers version
Windows / Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/no-path](https://jsfiddle.net/no-path)

### Steps to reproduce
The element library itself is quite huge.
I'd like to import just 2 components.
So far, I've done the following:

```
import ('element-ui/lib/theme-default/base.css')
import ('element-ui/lib/theme-default/collapse.css')
import ('element-ui/lib/theme-default/collapse-item.css')
import ('element-ui/lib/transitions/collapse-transition')

Vue.component(
    'el-collapse',
    () => import(/* webpackChunkName: "element-collapse" */'element-ui/packages/collapse/index')
)
Vue.component(
    'el-collapse-item',
    () => import(/* webpackChunkName: "element-collapse-item" */'element-ui/packages/collapse-item/index?chunk=element-collapse-item')
)
```

### What is Expected?
I expect the Collapse to show up with animations when I collapse it

### What is actually happening?
The collapse shows up, but there is no animation.

If I do import {Collapse, CollapseItem} from 'element-ui'
it will work, but it is importing the entire element-ui into my build...

**Comment by Leopoldthecoder** [comment]
Search for `On demand` on [this page](http://element.eleme.io/#/en-US/component/quickstart).
