### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =>  是什麼問題

### ISSUE THREAD

**Issue by sansanboy** [ElemeFE/element#668]
var Main = {template: `<el-card>请更新 Vue 和 Element 的版本号</e-card>`}

new Vue({
  el: '#app',
   render: h => h(Main)
})
</script>

**Comment by furybean** [comment]
应该是你用的浏览器并不支持箭头函数，改成这样试试：

```
new Vue({
el: '#app',
render: function(h) { return h(Main) }
})
```

另外，此类问题建议使用 [gitter](https://gitter.im/ElemeFE/element)，Issue 用来报告 Bug 和提 Feature。
