### ISSUE TITLE
Question: how to filter tree nodes and show their child nodes?

### ISSUE THREAD

**Issue by Weiyu-Chen** [ElemeFE/element#6681]
### Element UI version
1.2.9

### OS/Browsers version
Win7 / Chrome 60

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/chenweiyu/poen2uhu/](https://jsfiddle.net/chenweiyu/poen2uhu/)

### Steps to reproduce
as the above link show.

### What is Expected?
when  filtering tree , the child nodes of the filtered node should be appeared.
（筛选树节点时，筛选出的节点的子节点应该呈现出来）
### What is actually happening?
when  filtering tree , the child nodes of the filtered node will be disappeared.
（筛选树节点时，筛选出的节点的子节点没有了）

**Comment by furybean** [comment]
设计如此：子节点并没有命中筛选条件，所以是不可见的。
