### ISSUE TITLE
[Bug Report] tree component 1, level 2 data, dynamic add third data display error

### ISSUE THREAD

**Issue by liaoyinglong** [ElemeFE/element#6683]
### Element UI version
1.4.2

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/487/](https://jsfiddle.net/pj71jkyw/487/)

### Steps to reproduce
点击自定义的时候会从后台加载数据，当点击了一个自定义的时候能加载成功并显示出来，但是在点击另外一个自定义的时候却显示不出来了，通过vue-devtool的查看data里面的数据源是可以看到数据已经加载成功，就是无法映射到view层

### What is Expected?
点击特定按钮实现动态加载数据并展示。

### What is actually happening?
只有点击第一次才能正确展示，点击第二个按钮无法展示特定数据

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/489/

**Comment by liaoyinglong** [comment]
@Leopoldthecoder 
十分感谢，没有考虑到引用类型数据的问题。
