### ISSUE TITLE
[Bug Report] When use <el-slider> in <el-popver> the slider is dosen't work!

### ISSUE THREAD

**Issue by akai007** [ElemeFE/element#6691]
### Element UI version
1.4.2

### OS/Browsers version
MaxOs/Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/akai007/q1mrohw2/1/](https://jsfiddle.net/akai007/q1mrohw2/1/)

### Steps to reproduce
click button and then move the slider. 

### What is Expected?
Can change the slider

### What is actually happening?
Only can change it to Min Or Max value

**Comment by Leopoldthecoder** [comment]
Fixed in #6593
