### ISSUE TITLE
[Bug, Report], cascader, broken, if, mutate, the, argument,'active-item-change', of

### ISSUE THREAD

**Issue by JJPandari** [ElemeFE/element#6692]
### Element UI version
1.3.7

### OS/Browsers version
Google Chrome	60.0.3112.101 (正式版本) （64 位） 修订版本	1f3c0cf4b3083dfbe4da434af1726820cf384ce3-refs/branch-heads/3112@{#723} 操作系统	Mac OS X 10.12.4

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/u46afdc9/](https://jsfiddle.net/u46afdc9/)

### Steps to reproduce
Added a `val.pop()`, val is the arg of the handler of `active-item-change`. Use the cascader, the level 1 menu won't get focus while you click. It seems they are somehow rerendered.

### What is Expected?
Level 1 menu in the cascader gain focus and show level 2 items.

### What is actually happening?
Level 1 items won't gain focus.

**Comment by Leopoldthecoder** [comment]
By calling `val.pop()` you're actually mutating the very data inside the ElCascader component since `val` is an array. You should avoid doing this.
