### ISSUE TITLE
[Bug Report] TimePicker选择框滚动问题

### ISSUE THREAD

**Issue by zuopengcy** [ElemeFE/element#6695]
### Element UI version
1.4.2

### OS/Browsers version
Win7/Chrome 58.0.3029.110 (64-bit)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/493/](https://jsfiddle.net/pj71jkyw/493/)

### Steps to reproduce
1. 点开时间选择框
2. 滚动小时列至23时

### What is Expected?
滚动到底部时，会停留在23时

### What is actually happening?
时间列自动回退到了0时，23时很难被选中

**Comment by Leopoldthecoder** [comment]
Fixed in #6719
