### ISSUE TITLE
 [Bug Report] After the tree component operates data in the event node-click, the accordion fails

### ISSUE THREAD

**Issue by hua126mail** [ElemeFE/element#6699]
### Element UI version
1.4.3

### OS/Browsers version
win7/ chrome 59.0.3071.86

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/s54mg535/](https://jsfiddle.net/s54mg535/)

### Steps to reproduce
点击【本地简历】文字，其他同级节点没有被收回

### What is Expected?
手风琴模式，点击某一级节点后，其他同级节点应该会被收回

### What is actually happening?
demo中，有时会正常，有时不会

**Comment by qingdengyue** [comment]
复现不了......

**Comment by hua126mail** [comment]
@qingdengyue 加载完成后，先点击【本地简历0】，同级的【渠道简历0】没有被折叠

**Comment by furybean** [comment]
2.0.11 中同样存在，先标记下来。

**Comment by qingdengyue** [comment]
Fixed: #9611

**Comment by elfman** [comment]
这个应该是使用方法的问题，把`:default-expanded-keys="[9]"`修改为使用data内的数据就没再出现这个问题了。https://jsfiddle.net/s54mg535/3/
原因应该是Tree在重绘时`defaultExpandedKeys`重新生成了一个数组，值发生了变化，触发了监听器，然后将该数组内的node重新展开了一遍。看起来就像没折叠一样。

**Comment by Leopoldthecoder** [comment]
关于 @elfman 说的，可以参考 https://github.com/vuejs/vue/issues/4060

**Comment by elfman** [comment]
这里有个疑问，`defaultExpandedKeys`照这名字应该是只在初始化的时候起作用，后续再改变不应该再影响node的状态了吧，为啥还要继续监听？
