### ISSUE TITLE
[Table] 希望支持 rowSpan colSpan

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#670]
### What is Expected?

希望能支持 类似的 rowSpan colSpan

**Comment by Eamonnzhang** [comment]
+1

**Comment by odayou** [comment]
+1
合并行这种场景还是比较常见的.
官方忙不过来，有没有大神贡献下这个特性

**Comment by Aibric** [comment]
+1

**Comment by geraldlrh** [comment]
+1

**Comment by YeZhiqiuSev** [comment]
+1

**Comment by mahuaide** [comment]
+1

**Comment by Demon1110** [comment]
+1

**Comment by lynzz** [comment]
+1

**Comment by RainingNight** [comment]
+99

**Comment by forleve** [comment]
Hope support soon.

**Comment by scq000** [comment]
+1

**Comment by isting** [comment]
+666

**Comment by blogrocks** [comment]
+999

**Comment by scq000** [comment]
由于目前还不支持这个功能，所以我改了它的源码，能实现自己想要的需求。有需要的，可以拿去参考一下:[https://github.com/scq000/vue-element-enhanced-table](https://github.com/scq000/vue-element-enhanced-table)

**Comment by JinboMa** [comment]
`<template lang="pug">
el-table.my-table(
  :border="showBorder",
  :show-header="showHeader",
  :data="tableData",
  :style="tableStyle.style",
  :height="tableStyle.height",
  :max-height="tableStyle['max-height']",
  @selection-change="handleSelect")
  //- 选中
  el-table-column(v-if="showSelect",type="selection",width="50")
  //- 序列
  el-table-column(v-if="showIndex",type="index",width="60",label="#",align="center")
  //- 有slotName的列
  el-table-column(
    v-for="row in titleData",
    v-if="row.slotName",
    :key="row.prop",
    :prop="row.prop",
    :label="$t(row.label)",
    :width="row.width",
    :min-width="row['min-width']",
    :show-overflow-tooltip="row.tooltip",
    :align="row.align || 'center'",
    :sortable="row.sortable")
    template(scope="scope",v-if="row.slotName")
      slot(:name="row.slotName",:row="scope.row")
  //- 普通列
  el-table-column(
    v-else,
    :prop="row.prop",
    :label="$t(row.label)",
    :width="row.width",
    :min-width="row['min-width']",
    :show-overflow-tooltip="row.tooltip",
    :align="row.align || 'center'",
    :sortable="row.sortable")
    //- 可能的多级表头
    template(v-if="row.children")
      //- 有slotName
      el-table-column(
        :show-overflow-tooltip="row.tooltip",
        v-for="sub in row.children",
        :key="sub.prop",
        v-if="sub.slotName",
        :align="sub.align || 'center'",
        :label="$t(sub.label)",
        :width="sub.width",
        :min-width="sub['min-width']")
        template(scope="scope",v-if="sub.slotName")
          slot(:name="sub.slotName",:row="scope.row")
      //- 普通列
      el-table-column(
        :show-overflow-tooltip="row.tooltip",
        v-else,
        :align="sub.align || 'center'",
        :prop="sub.prop",
        :label="$t(sub.label)",
        :width="sub.width",
        :min-width="sub['min-width']")
  //- 操作列，默认有edit，remove两种
  el-table-column(v-if="isEdit || isRemove",:label="$t('operate')",width="120",fixed="right",align="center")
    template(scope="scope")
      //- 编辑按钮
      el-button(
        v-if="isEdit && rowEdit(scope.$index, tableData)",
        @click.native.prevent="editCb(scope.$index, tableData)",
        type="text",size="small") {{$t(editSpan)}}
      //- 删除按钮
      el-button(
        v-if="isRemove && rowRemove(scope.$index, tableData)",
        @click.native.prevent="removeCb(scope.$index, tableData)",
        type="text",size="small") {{$t(removeSpan)}}
</template>

<script>
export default {
  // props
  props: {
    showBorder: {
      type: Boolean,
      default: true
    },
    showHeader: {
      type: Boolean,
      default: true
    },
    gridArr: {
      type: Array,
      default: () => []
    },
    tableData: {
      type: Array,
      default: () => []
    },
    titleData: {
      type: Array,
      default: () => []
    },
    showIndex: {
      type: Boolean,
      default: false
    },
    showSelect: {
      type: Boolean,
      default: false
    },
    tableStyle: {
      type: Object,
      default: () => {
        return {
          style: {
            width: '100%'
          },
          'max-height': 600
        }
      }
    },
    isEdit: {
      type: Boolean,
      default: false
    },
    editSpan: {
      type: String,
      default: 'edit'
    },
    removeSpan: {
      type: String,
      default: 'remove'
    },
    isRemove: {
      type: Boolean,
      default: false
    },
    editCb: {
      type: Function,
      default: (index, roles) => {

      }
    },
    removeCb: {
      type: Function,
      default: (index, roles) => {

      }
    },
    rowEdit: {
      type: Function,
      default: (index, roles) => {
        return true
      }
    },
    rowRemove: {
      type: Function,
      default: (index, roles) => {
        return true
      }
    },
    handleSelect: {
      type: Function,
      default: (rows) => {
      }
    }
  },
  // methods
  methods: {
    // 合并单元格
    SpanGrid (tabObj, cellindex = 0, beginRow = 0) {
      if (!tabObj) return false

      let i, j
      let intSpan
      let strTemp

      for (i = beginRow; i < tabObj.rows.length; i++) {
        intSpan = 1
        strTemp = tabObj.rows[i].cells[cellindex].innerText

        for (j = i + 1; j < tabObj.rows.length; j++) {
          if (strTemp === tabObj.rows[j].cells[cellindex].innerText) {
            intSpan++
            tabObj.rows[i].cells[cellindex].rowSpan = intSpan
            tabObj.rows[j].cells[cellindex].classList.add('hide')
          } else { break }
        }
      }

      i = j - 1
    },
    // 重置被合并的单元格
    resetGrid (tabObj) {
      if (!tabObj) return false

      for (let row of tabObj.rows) {
        for (let cell of row.cells) {
          cell.rowSpan = 1
          cell.classList.remove('hide')
        }
      }
    },
    // 合并element表格的单元格
    colspan (gridArr) {
      this.$nextTick(function () {
        let tableEl = this.$el.querySelector('.el-table__body-wrapper table')

        this.resetGrid(tableEl)

        gridArr.forEach(i => { this.SpanGrid(tableEl, i) })
      })
    }
  },
  // 生命周期
  mounted () {
    this.colspan(this.gridArr)
  },
  // watch
  watch: {
    'tableData': {
      handler () { this.colspan(this.gridArr) },
      deep: true
    },
    'titleData': {
      handler () { this.colspan(this.gridArr) },
      deep: true
    }
  }
}
</script>

<my-table :tableData="tableData" :titleData="titleData" :gridArr="[0,2,3]"></my-table>
`

这是我自己写的一个table组件，这种可以根据内容，相同并且相邻的单元格竖排合并。

**Comment by syn-zeta** [comment]
There is [another related ticket](https://github.com/ElemeFE/element/issues/3349) that is tagged "in plan." Would the feature, how it is currently planned, provide the ability to do something like the following? Perhaps passing in an attribute (render function) to the Table component that will be called for every row, and allow the user to modify the row (change td/append or prepend another row). If this is not how it is currently planned, would another feature request for this be acceptable?

![image](https://user-images.githubusercontent.com/26761352/30984458-36027794-a442-11e7-9c47-b1ad65a3f733.png)

**Comment by huangshuwei** [comment]
我自己写了一个基于vue2.x 的table组件，目前已支持 colSpan 和 rowSpan,感兴趣的可以看下:
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-cell-merge

**Comment by Leopoldthecoder** [comment]
Added in 2.0: http://element.eleme.io/2.0/#/zh-CN/component/table#he-bing-xing-huo-lie

**Comment by syn-zeta** [comment]
@Leopoldthecoder Would you mind if I created another feature request to have a way to insert divider rows for grouping the data, something similar to the table in my previous comment above? The way it is implemented in 2.0 would require the divider row to be present in the bound data itself, but there may be instances where that would not be semantically correct.

**Comment by Leopoldthecoder** [comment]
@syn-zeta Having something like divider rows seems a little verbose to me, since ultimately it renders a full-span row that can be done with the current implementation.

**Comment by syn-zeta** [comment]
@Leopoldthecoder Right, it can be done with the current implementation, but that would require the "grouping criteria" to be part of the data itself. So, the date would exist as the serial number property in the above image, which seems like a hack. Perhaps a generic way to group data may be useful to enough users in the future to consider this.

**Comment by ablikim915** [comment]
我再合并行列上遇到问题了 哪位可以帮我看下问题？ #10702

**Comment by snowdream** [comment]
+1

**Comment by mhy-web** [comment]
文档中目前支持的合并单元格仅支持数组元素对象中全是基本类型的情况，多层数组嵌套类型数据的单元格拆分场景建议支持一下，目前业务中该类问题都是通过嵌套一个el-table解决的，但是边距边框处理与element原生的样式没有很好的兼容
