### ISSUE TITLE
[Bug Report] Upload Plugin Bug: Cannot reach onSuccess callback when manually set file-list, Error:"Cannot set property 'status' of null" 

### ISSUE THREAD

**Issue by wangjunji** [ElemeFE/element#6700]
### Element UI version
1.4.3

### OS/Browsers version
OSX / Chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/9w4xqtov/](https://jsfiddle.net/9w4xqtov/)

### Steps to reproduce

1. set file-list to show a list of already-uploaded images ( for user to view or remove )
2. multiple = true , auto-upload = false
3. set an before-upload function to fetch Qiniu OSS token from backend and  assign it to upload data
4. set an on-success function to get repsonse from Qiniu server
5. call $refs.Upload.submit() to manually upload images

The upload component can successfully upload images to Qiniu cloud but cannot receive response in onSuccess function. However, it works well when not manually setting the file-list prop.

The console shows the error: "Cannot set property 'status' of null" 

```
handleProgress: function handleProgress(ev, rawFile) {
	      var file = this.getFile(rawFile);
	      this.onProgress(ev, file, this.uploadFiles);
	      file.status = 'uploading';            // this line causes the error
	      file.percentage = ev.percent || 0;
	    }
```

I set some breakpoints and  find that " var file = this.getFile(rawFile);" returns null
However, before manually uploading the images, in chrome vue dev-tools , I find  that the "uploadFiles" array contains the newly-upload image and its status is 'ready' while the already-uploaded images' status is 'success'

### What is Expected?
To receive response from OSS server in onSuccess function

### What is actually happening?
The uploading process hangs up in handleProgess function

**Comment by qingdengyue** [comment]
empty ? https://jsfiddle.net/ad4jtw32/

**Comment by wangjunji** [comment]
@qingdengyue [https://jsfiddle.net/9w4xqtov/]( https://jsfiddle.net/9w4xqtov/) Updated.  The snippet just show the basic logic of how to reproducing the bug but cannot actually run. It has to communicate with server side

**Comment by qingdengyue** [comment]
https://jsfiddle.net/9w4xqtov/  is incompleted.Please show all  methods or what you want to do.Because it can't be reproducted(Except for action parameter).

**Comment by wangjunji** [comment]
I've found the cause of the bug.

Here is the simplified snippet of my code.

```
export default {
    data(){
        form:{
            ...
        },
        imageList:[]
    }
    created(){
        this.fetchData();
    }
    methods:{
       fetchData(){
            // fetch form and uploaded image data from server
            // this.form = ...
            // this.imageList = ...
       },
       handleSubmit(){
            // update form data
            updateUser(this.form).then(res=>{
                   // upload new image to OSS after update the database
                   this.$refs.upload.submit();
                  // I want to  refresh the form data and imageList  after submit the form , this line cause the error
                   this.fetchData();
            }).catch(err=>{
                   console.log(err);
            });
       },
       handleUploadSuccess(res,file,fileList){
          ...
      }
   }
}
```


I call fetchData() function immediately after manually submit the upload plugin which makes the imageList variable reassigned before  receiving the onSuccess callback from the OSS server and thus cause the error

I just move the fetchData() to the onSuccess callback and everything works well.

**Comment by Desdesdesgo** [comment]
here is the solution:
modify the source code 
file: 'upload/src/index.vue'
change to :
`    watch: {
        fileList: {
            immediate: true,
            handler(fileList) {

                this.uploadFiles =  [...fileList.map(item => {
                    item.uid = item.uid || (Date.now() + this.tempIndex++);
                    item.status = 'success';
                    return item;
                }),...this.uploadFiles.filter(item=>{return item.status=='uploading' || item.status=='ready'})];
            }
        }
    },`

**Comment by mgbq** [comment]
same error use this.$refs.upload.clearFiles()
