### ISSUE TITLE
<el-menu-item> warning when using :index="item.id"

### ISSUE THREAD

**Issue by patricktsg** [ElemeFE/element#6701]
### Existing Component
Yes

### Component Name
menu

### Description
<el-menu-item v-for="category in categories" :key="category.id" :index="category.id">{{category.name}}</el-menu-item> 

Works fine (have to use :index and not index) but console logs warnings that it expected a string not number.

**Comment by Leopoldthecoder** [comment]
Please read the Vue docs before using Element. This is not a bug.
