### ISSUE TITLE
[Bug Report] Autocomplete component does not work on andrios os.

### ISSUE THREAD

**Issue by hagcin** [ElemeFE/element#6702]
### Element UI version
1.4.3

### OS/Browsers version
andriod marshmellow (6.0) / firefox, and chrome (tablet)

### Vue version
2.3.4

### Reproduction Link
https://jsfiddle.net/swc5vem8/

### Steps to reproduce
start typing vue, or vuex. Notice that no suggestion list pops up. If you leave the input and come back, it will pop up.  if you use the delete key  the suggestion list will stay open. But it closes as soon as you try to type anything into the field.

### What is Expected?
suggestion list should show when user starts typing.

### What is actually happening?
suggestion list goes away on auto-complete component when user starts to type.

**Comment by hagcin** [comment]
https://jsfiddle.net/swc5vem8/  (updated the link but it is the same as the default example)

**Comment by Leopoldthecoder** [comment]
Element is only for desktop. It's not compatible with mobile devices.

**Comment by hagcin** [comment]
That seems an unusual position to take for a UI framework in 2017. What is the long term goal of element, is it to support mobile and you just need help to make that happen, or is the framework forever going to be a desktop only framework? (trying to know, so I can either help you guys get your mobile game together or bail on this framework)

**Comment by Erbenos** [comment]
Even not considering "mobile" only - it doesn't work on any touch input device. I do realize that maintaining such a large framework isn't easy so I hope you are open to "mobile" targetted PR's.
