### ISSUE TITLE
[Bug Report]  Set attribute sortable=“true”  or ”false“  on  <el-table-column>, but it's useless

### ISSUE THREAD

**Issue by Lutreer** [ElemeFE/element#6710]
### Element UI version
1.4.2

### OS/Browsers version
mac os 10.12.6 / chrome 60.0.3112.101（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/494/](https://jsfiddle.net/pj71jkyw/494/)

### Steps to reproduce
分别点击日期、姓名和年龄的排序。(To click the title(日期，姓名，年龄) for sort)

### What is Expected?
1、点击年龄（sortable 没有设置任何值）和姓名（sortable=“true”）是这两列可以排序。
2、因为日期的sortable=“false”,所以该列不应该能排序，且！不该显示可排序的icon

### What is actually happening?
1、点击年龄（sortable 没有设置任何值）可以正常排序，姓名（sortable=“true”）无法排序。
2、因为日期的sortable=“false”,所以该列不应该能排序，该列不可以排序，但是显示了排序的icon。

**Comment by Leopoldthecoder** [comment]
It should be `:sortable="false"`. Please read the Vue docs before using Element.

**Comment by Lutreer** [comment]
oh, so stupid, please delete this issue 😓

**Comment by Lutreer** [comment]
oh, no, so stupid!!! Please delete this issue 😓

**Comment by wxhthx** [comment]
@Lutreer the exist docs described not correctly, which says just add "sortable" can do it but actually it doesn't.u must use :sortable="true" to solve it
