### ISSUE TITLE
[Feature Request] How to use filtered-value when using render-header

### ISSUE THREAD

**Issue by rodrigore** [ElemeFE/element#6714]
### Existing Component
Yes

### Component Name
Table

### Description
Hi, i was wondering how can I use the filtered-value when using a render-header. I want to filter using an input but i have no idea how to use the filtered-value property with the render-header.

I have this code:

``` javascript

            renderHeader: function(h, {column, $index}) {
                return h('div', { class: 'el-input', style: 'width:90%' }, [
                    h('div', null), h('el-input', {
                        props: {
                            placeholder: column.label
                        },
                        on: {
                            input(e) {
                                // somehow filter the data and use filteredValue
                            }
                        }
                    })
                ]);
            },


```

**Comment by syn-zeta** [comment]
Issues section is not intended for general questions. Please use Element's Gitter IM rooms, and users will be able to assist you there. Links are available at: https://github.com/ElemeFE/element#element

![image](https://user-images.githubusercontent.com/26761352/29992878-332f7a54-8f5b-11e7-924e-6ddcfda31292.png)

For your particular question, though, please provide more context when you post on Gitter.

@Leopoldthecoder @QingWei-Li Recommend closing.
