### ISSUE TITLE
[Bug Report] in some scenarios, the el-input input is particularly slow

### ISSUE THREAD

**Issue by vincepeng** [ElemeFE/element#6715]
### Element UI version
1.4.2

### OS/Browsers version
macos

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
内网地址,无法提供重现地址
较多el-input,某些场景下,会造成input的输入特别卡顿.

### What is Expected?
输入流程

### What is actually happening?
输入特别卡顿,看性能测试,主要花在在刷新doc上面.
特别地,本地启动无法重现,部署到服务器上面才会出现.
据说老版本会出现这个[问题](https://github.com/ElemeFE/element/pull/5359),升级后还是有这个问题.

![image](https://user-images.githubusercontent.com/3695117/29752382-655bf356-8b8f-11e7-8832-5119ba8ef86d.png)

**Comment by Leopoldthecoder** [comment]
没有重现是无法定位问题的。另外，#5359 处理的是 Select 的问题，和 Input 无关。
