### ISSUE TITLE
The [Bug Report] el-menu-item is-active does not really implement the response to routing hash

### ISSUE THREAD

**Issue by ZhongyiChen** [ElemeFE/element#6718]
### Element UI version
1.4.2

### OS/Browsers version
Windows / Chrome 51.0.2704.106 m (64-bit)

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/xiaochennihao/Lk0cks74/](https://jsfiddle.net/xiaochennihao/Lk0cks74/)

### Steps to reproduce
打开重现链接，点击“关于”，然后在弹窗中选择“继续留在当前页面”，会发现，会发现，“关于”处于了激活状态

### What is Expected?
在弹窗中选择“继续留在当前页面”，menu-item的激活状态不应当改变

### What is actually happening?
点击到的那个menu-item会处于激活状态，而没有响应路由hash的状态

**Comment by baiyaaaaa** [comment]
#9675
