### ISSUE TITLE
I hope the tree component can add this feature

### ISSUE THREAD

**Issue by Timson020** [ElemeFE/element#672]
可以通过一个属性来控制，当点击level===-1的时候，下面层级展开到 level===need
or
点击level === num 下面的层级展开到 level===need
默认就是不展开跨level的

### ElementUI version

1.0.0-rc.7
### OS/Browers version

macOS
### Vue version

2.1.0beta5

**Comment by baiyaaaaa** [comment]
哪个组件？

**Comment by furybean** [comment]
没太看懂，是 Tree 需要 API 控制某些节点的展开与关闭吗？

**Comment by Timson020** [comment]
是的

**Comment by furybean** [comment]
1.0.1 提供了 defaultExpandedKeys autoExpandParent 属性，应该可见解决你这个问题。
