### ISSUE TITLE
el-tooltip 如何鼠标离开立即消失？

### ISSUE THREAD

**Issue by ayiaq1** [ElemeFE/element#6720]
el-tooltip 如何鼠标离开立即消失？

**Comment by 577675603** [comment]
我也遇到了这个问题，还没有解决啊

**Comment by qq850980232** [comment]
this.debounceClose = debounce(200, () => this.handleClosePopper());   把组件中得200时间改成0

**Comment by fengdanbailu** [comment]
> 

提出这个问题的人很多，但好像并没有人做更改。

**Comment by X1996X** [comment]
我用自定义指令做的
tooltipHide: {
    inserted: function (el) {
      const tooltipId = el.attributes['aria-describedby'].nodeValue;
      el.immediateHide = () => {
        const tooltipEl = document.getElementById(tooltipId);
        tooltipEl.style.display = 'none';
      };
      el.addEventListener('mouseleave', el.immediateHide);
    },
  },
使用
 <el-tooltip v-tooltip-hide>
