### ISSUE TITLE
[Feature Request] How to use v-popover:value  with Vue render

### ISSUE THREAD

**Issue by fxxjdedd** [ElemeFE/element#6726]
### Existing Component
Yes

### Component Name
ELPopover

### Description
How to use v-popover:value  with Vue render?
I use :
const iconButton = createElement('button', {
        props: {
          'v-popover': {
            default: 'myPopover'
          }
        }
      })
but it doesn't work

**Comment by Leopoldthecoder** [comment]
Why not read the Vue docs? https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth
