### ISSUE TITLE
[Bug Report] element/src/mixins/emitter.js has not been compiled before publishing to npm 

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#6728]
### Element UI version
1.4.3

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
there is no link

### Steps to reproduce
1. use `webpack` and `babel` to compile the project 
2. open it in `IE11`
3. error in console

### What is Expected?
![image](https://user-images.githubusercontent.com/1060733/29763455-b4ba4c06-8c05-11e7-9b23-3cb08d8a8f04.png)

### What is actually happening?
`IE11` is not supported,because arrow function is used by [emitter.js](https://github.com/ElemeFE/element/blob/dev/src/mixins/emitter.js#L2)

**Comment by Leopoldthecoder** [comment]
This is hardly true. You can check [this](https://unpkg.com/element-ui@1.4.3/lib/element-ui.common.js) out.

**Comment by spx443812507** [comment]
@Leopoldthecoder 
latest element-ui work with vue-cli 3.0 , after i build prod, only emitter.js file not compiled to es5 syntax, so i need add transpileDependencies: ['element-ui'] into vue.config.js, is that reasonable？
