### ISSUE TITLE
table 表头不响应横向滚动事件

### ISSUE THREAD

**Issue by jin5354** [ElemeFE/element#673]
### ElementUI version

1.0.0-rc.7
### OS/Browers version

macOS/Chrome 54
### Vue version

2.0.3
### Reproduction Link

https://jsfiddle.net/fe0v1ob9/
### Steps to reproduce

很宽，产生了横向滚动条的表格
rmbp下，触摸板双指左右滑动。
### What is Expected?

在整个表格区域均可横向滚动
### What is actually happening?

在表格主体可横向滚动，在表头不可横向滚动

**Comment by furybean** [comment]
没太看懂，是需要类似固定功能么？
如果是按照『在表格主体可横向滚动，在表头不可横向滚动』，这个岂不是会错位？

**Comment by furybean** [comment]
Sorry，刚刚看错了。
我好像没办法重现，我使用 Chrome 54，整个表格都是可以滚动的。

**Comment by jin5354** [comment]
@furybean 
用同事电脑试了试，可以复现问题，macOS/Chrome 54 macOS/Safari 10.0 都是这样。

**Comment by furybean** [comment]
@jin5354 去 gitter 里面问了一圈，同事试了试，都不能重现。
我们明天就发 rc8 了，要不明天发了你试试 rc8？

**Comment by jin5354** [comment]
@furybean 好的，现在的表格条目很多时横向滚动似乎也有性能问题。明天我更到rc8再试一试，之后再反馈。

**Comment by furybean** [comment]
@jin5354 你现在可以用 rc.8 试一试是否还有这个问题。

**Comment by jin5354** [comment]
@furybean 更新到 rc.8 问题还是存在。表头部分不能滚动，录了段视频： http://v.youku.com/v_show/id_XMTc4MTg2MTUxMg==.html

macOS 10.12 chrome 54 vue 2.0.3 ElementUI 1.0.0-rc8

**Comment by furybean** [comment]
@jin5354 Okay，一直理解错意思了。我尝试去实现一下。
