### ISSUE TITLE
[Bug Report] about el-dropdown: I can't click on other areas to close the drop-down box in ios.

### ISSUE THREAD

**Issue by KrisMai** [ElemeFE/element#6730]
### Element UI version
1.4.2

### OS/Browsers version
IOS 10.3.3 / Safari

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/KrisMai/hw4nj71L/](https://jsfiddle.net/KrisMai/hw4nj71L/)

### Steps to reproduce
用ios系统自带的safari浏览器打开http://element.eleme.io/#/zh-CN/component/dropdown ，点击dropdown组件弹出下拉框，然后点击其他区域无法关闭下拉框。（用jsfiddle无法模拟出该情况，须在真实环境中测试，如用官网中的dropdown组件进行测试会出现该情况）

### What is Expected?
点击其他区域应关闭下拉框。

### What is actually happening?
在ios系统中无法点击其他区域关闭下拉框。

**Comment by Leopoldthecoder** [comment]
Element 仅支持桌面端浏览器。请避免在移动端项目中使用 Element。

**Comment by KrisMai** [comment]
并不是移动端项目才会在移动端浏览器浏览，现在的移动设备这么发达，PC端的网页难免会用到移动设备浏览，在安卓系统的设备是可以正常关闭，在ios中则不行，现在我司整个项目都使用了element的组件，更改为其他UI组件也十分不便，希望能改进这个问题。

**Comment by KrisMai** [comment]
您好，我想并不是移动端项目才会在移动端浏览器浏览，现在的移动设备这么发达，PC端的网页难免会用到移动设备浏览，在安卓系统的设备是可以正常关闭，在ios中则不行，现在我司整个项目都使用了element的组件，更改为其他UI组件也十分不便，希望能改进这个问题。
