### ISSUE TITLE
[Bug Report] Why can't table-column use "v-if" anymore?

### ISSUE THREAD

**Issue by tonytangcn** [ElemeFE/element#6731]
### Element UI version
1.4.3

### OS/Browsers version
win10/chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/c5fa7cq1/11/](https://jsfiddle.net/c5fa7cq1/11/)

### Steps to reproduce
I could still use v-if in table-column in version 1.35, but after I updated to the latest version, my table cannot render normally since I used "v-if" in some of the columns

### What is Expected?
What is Expected?

### What is actually happening?
What is actually happening?

**Comment by Leopoldthecoder** [comment]
You demo works fine to me.

**Comment by tonytangcn** [comment]
sorry, i made a mistake of demonstrating, my problem actually is I have a component with 3 children A, B, C ; A, B, C are using a same template which contains an element-table, but I'm using v-if="routeName == A (or B or C)" in the columns in order to show specific columns in different routers, so by this means it doesn't work in latest version but still works in version 1.35.

**Comment by Leopoldthecoder** [comment]
So where is your demo?

**Comment by tonytangcn** [comment]
here is the demo: [https://jsfiddle.net/cfpeng/95ba3eq5/8/](url)
first click "Go to Foo", the router links to '/foo', you would see two columns in the table,  then click "Go to Bar",  it seems right at the moment, but then click "Go to Foo" again, you would see one column missing, thanks

**Comment by Leopoldthecoder** [comment]
This is a bug. We'll fix it in the coming weeks.

But 1.3.5 seems to not work either: https://jsfiddle.net/95ba3eq5/13/

**Comment by tonytangcn** [comment]
thanks, by the way, in this link you could see some error details in the browser's console panel:  https://jsfiddle.net/cfpeng/95ba3eq5/

**Comment by Oscar-ren** [comment]
hi, I found the latest version 1.4.4 also have this bug.
and when use template tag with the v-if directives, there won't be work too.
there is the demo: https://jsfiddle.net/msndbade/

**Comment by PanJiaChen** [comment]
https://jsfiddle.net/msndbade/1/

l think add a key solve all problem

**Comment by Oscar-ren** [comment]
year, add key solve the el-table-column v-if problem, but when add v-if on the template tag, there still won't be work 

demo: https://jsfiddle.net/bd1wy60m/

**Comment by Leopoldthecoder** [comment]
@Oscar-ren That's because `<template>` doesn't support `key`s.
