### ISSUE TITLE
[Bug, Report] Table  cell missing when the content was created by vue.createElement

### ISSUE THREAD

**Issue by maplewizard** [ElemeFE/element#6732]
### Element UI version
1.4.3

### OS/Browsers version
deepin/Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/uL3Lvak1/](https://jsfiddle.net/uL3Lvak1/)

### Steps to reproduce
open the link, no other operation needed.

### What is Expected?
All rows in column "姓名" should have value. 

### What is actually happening?
Two rows have content while others are empty.

**Comment by Leopoldthecoder** [comment]
Why are you trying to assign the `name` field to a VNode?

**Comment by maplewizard** [comment]
@Leopoldthecoder  I want to set the field different colors by font tag  amd make it clickable. This is the way that I found that could do that. Is there any way suggested that can make it with different color and clickable?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/uL3Lvak1/1/

**Comment by maplewizard** [comment]
@Leopoldthecoder Thanks for your code, but I want to add the tag dynamically in a function. if I just use string concatenation of the tag and my content, the tag will be converted into normal string and cannot work.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/uL3Lvak1/2/
