### ISSUE TITLE
[Bug Report] form items dynamically binding edit data

### ISSUE THREAD

**Issue by isnur** [ElemeFE/element#6733]
### Element UI version
1.4.3

### OS/Browsers version
windows 7

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/isnur/6zsttrtq/](https://jsfiddle.net/isnur/6zsttrtq/)

### Steps to reproduce
1. click edit in row.
2. edit value Email and Domain0/Domain1
3. click cancel

### What is Expected?
Table data not change while typing edit domain and close edit popup.

### What is actually happening?
Table data change while domain in editing (binding)
after click cancel Table data changed.

**Comment by Leopoldthecoder** [comment]
The `domains` field is an array, so `dynamicValidateForm` still points to the same reference as the original `tableData` even if you use `Object.assign`. This is basic JavaScript.

**Comment by isnur** [comment]
@Leopoldthecoder ok thanks. I have resolved this.
 `this.dynamicValidateForm = JSON.parse(JSON.stringify(row));`
