### ISSUE TITLE
The [Bug Report] el-dropdown drop-down menu cannot be centered

### ISSUE THREAD

**Issue by webJing** [ElemeFE/element#6735]
![dropdown1](https://user-images.githubusercontent.com/14087071/29768401-a819e2be-8c18-11e7-9a22-0ae3addd9680.png)
![dropdown2](https://user-images.githubusercontent.com/14087071/29768402-a81e29c8-8c18-11e7-8d98-b24975267db4.png)
![dropdown1](https://user-images.githubusercontent.com/14087071/29768416-b07e3374-8c18-11e7-954a-a63d89a1bbaa.png)

### Element UI version
1.4.3

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/fhs78bq5/](https://jsfiddle.net/fhs78bq5/)

### Steps to reproduce
点击dropdown出现下拉菜单的时候，el-dropdown-item 的文字不居中，而且下拉菜单相对于收缩的标题不居中

### What is Expected?
期待点击dropdown出现下拉菜单的时候，el-dropdown-item 的文字居中，而且下拉菜单相对于收缩的标题居中

### What is actually happening?
实际不居中

**Comment by Leopoldthecoder** [comment]
希望文字居中的话可以自己覆盖下样式。

下个大版本中会加入菜单相对于标题的位置配置。

**Comment by thevirtualsystems** [comment]
> 希望文字居中的话可以自己覆盖下样式。
> 
> 下个大版本中会加入菜单相对于标题的位置配置。

现在是2024-9-21，我没有看到更新了这个配置
