### ISSUE TITLE
[Bug, Report], The, tag, el-select, change, event, was, triggered, by, the, data, model, loaded, or,, data, model, of, order, changed, array., in

### ISSUE THREAD

**Issue by Nunchakus888** [ElemeFE/element#6737]
### Element UI version
1.4.3

### OS/Browsers version
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

### Vue version
2.4.2

### Reproduction Link
[https://nunchakus888.github.io/commodityyyyyy/commodity-edit.html](https://nunchakus888.github.io/commodityyyyyy/commodity-edit.html)

### Steps to reproduce
િ🙄ી
1.页面底部有属性下拉框，选中填写完整
2.再增加一条，重复步骤1
3.重复步骤2（代码中@change后手动清空对应的value值）
然后会发现第2或3的select change事件会被触发。
事实上此时只是改变了绑定对象所在数组的顺序，而对象本身是没有改变的，却仍然触发了onchange事件。
此问题再el-table的自定义模版中使用el-select也会出现，原生select则没有问题。

### What is Expected?
Only itself data model changed and trigger the event of change.

### What is actually happening?
The tag of el-select change event was triggered by the data model loaded or data model order changed in array.

**Comment by Leopoldthecoder** [comment]
下个大版本中的 change 事件将仅响应用户交互。https://github.com/ElemeFE/element/issues/6011
