### ISSUE TITLE
[Feature Request] Table column with very long label

### ISSUE THREAD

**Issue by jongeyer** [ElemeFE/element#6743]
### Existing Component
Yes

### Component Name
el-table-column

### Description
I need to handle cases where the table column label is very long, so the label is not wrapped.
https://jsfiddle.net/L1gb9ddg/

While I can truncate the label, in that case I'd like to show a tooltip of the full label text -- this could just be a title attribute, or a popover. But really I'm not sure what is the best solution.

**Comment by Leopoldthecoder** [comment]
In this case the best solution may be `render-header`. And for the tooltip part, you can check out our `show-overflow-tooltip` implementation for reference.
