### ISSUE TITLE
[Bug Report] There are gaps between checkbox buttons when using checkbox group 

### ISSUE THREAD

**Issue by luon08** [ElemeFE/element#6745]
### Element UI version
1.4.3

### OS/Browsers version
WIN7 / All Browser

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/509/](https://jsfiddle.net/pj71jkyw/509/)

### Steps to reproduce
1. not use v-for to create checkbox button
2. gaps appear

### What is Expected?
no gaps between buttons

### What is actually happening?
gaps between buttons

**Comment by Leopoldthecoder** [comment]
For now you can add `font-size: 0`: https://jsfiddle.net/pj71jkyw/510/ . I'll add it to the CheckboxGroup style later.
