### ISSUE TITLE
[Bug Report] select

### ISSUE THREAD

**Issue by hz91213** [ElemeFE/element#6747]
### Element UI version
1.4.3

### OS/Browsers version
chrome 59.0.3071.115

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/hxr05z10/1/      https://jsfiddle.net/hxr05z10/2/](https://jsfiddle.net/hxr05z10/1/      https://jsfiddle.net/hxr05z10/2/)

### Steps to reproduce
在线运行，给数组value:[]添加数据

### What is Expected?
正确展示数据

### What is actually happening?
数据错误

**Comment by Leopoldthecoder** [comment]
正确用法：https://jsfiddle.net/hxr05z10/3/ 。数组中的元素应该是 `<el-option>` 中 `value` 字段的值。

**Comment by hz91213** [comment]
@Leopoldthecoder 多谢，那我把数据处理下再添加进去
