### ISSUE TITLE
[Feature Request] recommends adding regular check functions in the input input box

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#6750]
### Existing Component
是

### Component Name
el-input

### Description
当前input 输入没有做限制， 可输入非法字符等， 建议通过 传入的 正则 对用户的输入进行限制 例如 正则 限定输入为 数字， 用户输入其他无反应。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this.
