### ISSUE TITLE
[Bug Report] Disabled dropdown button can still trigger dropdown menu in firefox

### ISSUE THREAD

**Issue by zdpeitang** [ElemeFE/element#6752]
### Element UI version
1.4.3

### OS/Browsers version
Firefox 55

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/516/](https://jsfiddle.net/pj71jkyw/516/)

### Steps to reproduce
1. Add dropdown menu as described in the document.
2. Disable dropdown button.
3. Mouseover dropdown button.

### What is Expected?
Dropdown menu should not be shown.

### What is actually happening?
Dropdown menu is still triggered in firefox, not shown in chrome.

**Comment by Leopoldthecoder** [comment]
Seems this is because FireFox handles mouse events on disabled buttons differently from Chrome: https://jsfiddle.net/e1a8094s/1/ . This is not an Element bug.

**Comment by zdpeitang** [comment]
Sorry but is it purposed that a dropdown menu should be triggered when the button is disabled?

I found something on [Firefox compatibility document](https://www.fxsitecompat.com/en-CA/docs/2016/disabled-form-controls-now-trigger-mouseover-and-similar-mouse-events/):

> In order to make sure your code always works as expected, you might want to explicitly check the disabled property of the target element in your event handler.

**Comment by Leopoldthecoder** [comment]
It's actually kinda tricky because the triggering element is passed via slot. I guess the most we could do is #6762. A little hacky, but works.
