### ISSUE TITLE
[Bug, Report], error, in, add, dynamic,, form, item (error adding form field dynamically)

### ISSUE THREAD

**Issue by iamhanson** [ElemeFE/element#6755]
### Element UI version
1.4.3

### OS/Browsers version
现代浏览器

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/iamhanson/L0gtv73h/3/](https://jsfiddle.net/iamhanson/L0gtv73h/3/)

### Steps to reproduce
动态增加表单的项，然后表单项增加了，但是下拉框、复选框、单选按钮等无法选择或者勾选

### What is Expected?
动态的增加一个表单的字段，比如增加性别选择的单选框，实现动态增加字段

### What is actually happening?
字段增加之后，无法操作，选择，勾选等都无法操作

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/L0gtv73h/4/
Please read the Vue docs before using Element.

**Comment by spx443812507** [comment]
@Leopoldthecoder hi, can i optimize your demo with [https://vuejs.org/v2/guide/components.html#Dynamic-Components](url)
