### ISSUE TITLE
[Bug Report] when tree first load the children not work (tree asynchronous data loading, and when node.level ===0 has a default child node at the current node, why not load and expand it)?

### ISSUE THREAD

**Issue by angusjiang** [ElemeFE/element#6759]
### Element UI version
1.4.3

### OS/Browsers version
window 10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/s5xycwo7/](https://jsfiddle.net/s5xycwo7/)

### Steps to reproduce
https://jsfiddle.net/s5xycwo7/

### What is Expected?
当node.level的时候默认展示前几级

### What is actually happening?
tree load 默认只可以有一级展示，每次加载也只是一级

**Comment by angusjiang** [comment]
当异步加载子节点数据的时候，每次也只能加载一级数据
https://jsfiddle.net/s5xycwo7/2/

子节点每次加载一级数据没什么问题，可是初始化的一级节点，默认应该至少展开一级，否者太难看，需要也至少先加载一级数据。

**Comment by angusjiang** [comment]
@Leopoldthecoder

**Comment by furybean** [comment]
@angusjiang 「默认应该至少展开一级」指的是初始化的时候展开到第二级？

**Comment by angusjiang** [comment]
@furybean  需要依次展开一系列结点

**Comment by furybean** [comment]
@angusjiang [当node.level的时候默认展示前几级] 这句话是什么意思？

**Comment by angusjiang** [comment]
异步请求的时候，默认只加载了第一级，之后需要点击才可以展开第二级，但是我需要在加载完根级之后再自动展开第二级第三级一直到第n级，default-expanded-keys 目前只支持展开同级的，所以我用定时器一次次的改变default-expanded-keys 来展开多级
