### ISSUE TITLE
[Feature, Request], Add, accordion, style, to, Table's, expand

### ISSUE THREAD

**Issue by maplewizard** [ElemeFE/element#6760]
### Existing Component
是

### Component Name
el-table-column 

### Description
when use el-table-column expand, I want that when one row is expanded, other rows will be cllapsed automatically. Could you please add this feature?

**Comment by Leopoldthecoder** [comment]
We have no plan to support this.

**Comment by maplewizard** [comment]
@Leopoldthecoder is there any method to collapse the rows by code?

**Comment by Leopoldthecoder** [comment]
Currently not. But we are likely to add such a method in the next major version.

**Comment by maplewizard** [comment]
@Leopoldthecoder When will the next major version be released as planed?

**Comment by Leopoldthecoder** [comment]
We're still at an early stage. More info will be revealed when we come close to its release.

**Comment by wh1100717** [comment]
@maplewizard 

```
<template>
  <el-table @expand="handleRowExpand">
  </el-table>
</template>

<script>
export default {
  methods: {
    handleRowExpand (row, expanded) {
      if (!expanded) return
      $('.el-table__expand-icon.el-table__expand-icon--expanded').click()
    }
  }
}
</script>
```

Before next major version releasing, u can listen `expand` event.
folding all expanded element before target one expand

**Comment by feichangtutu** [comment]
Is there any improvement for the expand ? I also hope 

> when use el-table-column expand, I want that when one row is expanded, other rows will be cllapsed automatically. 

@Leopoldthecoder

**Comment by feichangtutu** [comment]
I know how to solve this problem use 
```
 :row-key="getRowKey"
  :expand-row-keys="expand_keys"
```
step1: add expanded-row-keys to table attribute
```
     <el-table
          :data="tableData5"
          class="divide-top"
          style="width: 100%"
          :header-row-class-name="tableHeaderClassName"
          :row-class-name="tableRowClassName"
          :cell-class-name="cellClassName"
          @expand-change="test"
          :row-key="getRowKey"
          :expand-row-keys="expand_keys"
          @row-click="rowClick"
        >
```
step2： add expand_keys
```
  data() {
  	return {
      expand_id: 0,
      expand_keys:[],
...
```
add methods:
```
  getRowKey(row){
      return row.id;
    },
    rowClick(row, event, column) {
      this.expand_id = row.id
      this.expand_keys = []
      this.expand_keys.push(row.id)
    }
```
then the expaned rows will controlled by clicked row.
ALSO, you can add
```
  this.expand_keys = []
      this.expand_keys.push(row.id)
```
into @expand-change function

**Comment by thunderrun** [comment]
simpler in v2.7
```html
<el-table @expand-change="onExpandChange" />
```

```javascript
onExpandChange(row, expandedRows) {
    expandedRows.shift();
},
```
