### ISSUE TITLE
[Feature Request] How can I use el-table with dynamic data which have mutable columns?

### ISSUE THREAD

**Issue by caronyan** [ElemeFE/element#6763]
### Existing Component
Yes

### Component Name
el-table

### Description
In my case, my table columns depend on a date range, and it is mutable so that it is difficult to bind column prop in advance.

For example, I search for 30 days and backend return some results as a array, I have no keys to bind and prop dose not support array index.

I tried to naming a key to each column, but as mentioned before, column data is mutable, I don't know how many keys will be returned from API, so it is also hard to define a table template before request.

So is there an elegant solution for this question?

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
