### ISSUE TITLE
[Bug Report] After the is set disabledDate, the month view is all disabled and cannot be selected

### ISSUE THREAD

**Issue by douxc** [ElemeFE/element#6764]
### Element UI version
1.4.3

### OS/Browsers version
windows 10 / Chrome 59.0.3071.115（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/8xy5jck6/4/](https://jsfiddle.net/8xy5jck6/4/)

### Steps to reproduce
1. 设置disabledDate 规则为 date.getTime() >= Date.now() - 8.64e7;
2. 点击选择框，打开日期选择；
3. 点击顶部‘年份’进入年份选择；
4. 选择年份后进入月份选择
此时所有的月份均是禁用状态

### What is Expected?
可以根据规则正常选择月份

### What is actually happening?
无法正常选择月份

**Comment by qingdengyue** [comment]
#6768

**Comment by evanyangg** [comment]
set the disabledDate rules for date.getTime () (8.64e7) - > = Date.now;
@qingdengyue 
知道如何自定义这个规则么
假设我自己一个时间区域 让这个区域不可用, 该如何设置呢

**Comment by douxc** [comment]
@evanyangg disabledDate 是个回调函数，传递过来的参数就是日期（date）。直接计算这个日期然后和你的时间区域比对，判断返回true还是false

**Comment by Leopoldthecoder** [comment]
Fixed in #6768

**Comment by 450671491** [comment]
怎样禁用数组里每一个单独的时间？能不能传一个要禁用的时间数组来禁用？
