### ISSUE TITLE
The text of the [Bug Report] progress component is not clear

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#6767]
### Element UI version
1.4.3

### OS/Browsers version
chrome最新版本

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/w4jqnwa7/](https://jsfiddle.net/w4jqnwa7/)

### Steps to reproduce
打开链接就能看到， 3.12% 的进度条文字被 进度条截成了两段

### What is Expected?
当比率小于一个值的时候， 进度条文字出现在进度条的右边， 不是进度条的内部

### What is actually happening?
 3.12% 的进度条文字被 进度条截成了两段

**Comment by qingdengyue** [comment]
![image](https://user-images.githubusercontent.com/3230673/29858152-af833484-8d8e-11e7-8a77-f26053d8788f.png)
这貌似不是个问题~
