### ISSUE TITLE
popover 组件 error

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/element#677]
![image](https://cloud.githubusercontent.com/assets/1932350/19760368/1141bfb4-9c64-11e6-9847-a28d8cd7ab62.png)

### ElementUI version
1.0.0-rc.7

### OS/Browers version
macOS/Chrome 53 

### Vue version
2.0.3 

### Reproduction Link
https://jsfiddle.net/yelingfeng/5u16k232/

**Comment by yelingfeng** [comment]
<el-popover> 顺序在上面就不报错了。。。

**Comment by QingWei-Li** [comment]
拿不到 popover，我暂时也没有好的解决方法，这和 Vue 的渲染顺序有关。尽可能按照先定义 popover 然后再使用的顺序调用吧。推荐用 `slot` 的方式插入。

```javascript
<el-popover
  placement="right"
  title="标题"
  width="200"
  trigger="focus"
  content="这是一段容,这是一段容,这是一段容,这是一段容。">
  <el-button slot="reference">focus 激活</el-button>
</el-popover>
```
