### ISSUE TITLE
The length limit required for the [Feature Request] input component box

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#6770]
### Existing Component
是

### Component Name
input

### Description
目前 input 组件通过 maxlength 来控制最大长度， 可是英文 和中文的长度是不一样的,  建议通过增加 maxbyte 属性来控制字节数， 如果能加入 正则 来阻止用户非法输入就更好了

**Comment by qingdengyue** [comment]
input 的maxlength属性  中英文都是一样的。
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
