### ISSUE TITLE
[Feature, Request], remote-select's, default, value, problem

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#6771]
### Existing Component
是

### Component Name
select

### Description
remote类型的select组件，设置默认值时通过数组传递，但是目前只能传递 [str, str, str, ...] 这样的，导致组件的 value 和 label 是一样的，但是在搜索选择之后的 change 事件中传递的选中值数组里面，已有的默认值是label，而新选的值是 value， 造成了不一致性。
希望默认值可以传非简单字符串类型的值，可以传对象比如 `{ label: '', value: '' }` 这样的

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
