### ISSUE TITLE
[Bug Report] using Tabs components can cause browser crashes.

### ISSUE THREAD

**Issue by zhengshui** [ElemeFE/element#6773]
### Element UI version
1.3.7

### OS/Browsers version
window 64

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/3a2ama5n/1/](https://jsfiddle.net/3a2ama5n/1/)

### Steps to reproduce
使用el-tabs组件时，如果它前一个兄弟元素的设置style="width: 100%;float:left",会导致浏览器崩溃。

![image](https://user-images.githubusercontent.com/8155297/29863790-514dfccc-8da3-11e7-93b1-55a6a8303dbf.png)

![image](https://user-images.githubusercontent.com/8155297/29863859-78445664-8da3-11e7-9eee-e70858893f0c.png)

### What is Expected?
不会崩溃

### What is actually happening?
浏览器崩溃

**Comment by qingdengyue** [comment]
https://jsfiddle.net/follow_your_heart/222e8d1d/3/ 
no reproduction~

**Comment by zhengshui** [comment]
你随便在div里面加点内容试试eg：`<div style="width:100%;float:left">a</div>`

**Comment by zhengshui** [comment]
在使用element + vue 的过程中已经碰过两次浏览器崩溃的情况了，具体原因还没有找到。随便想请教一下，类似的浏览器崩溃问题，有没有什么好的方法去定位和解决。

**Comment by wacky6** [comment]
Reproduced in 1.4.3

**Comment by wacky6** [comment]
Reproduced in 1.4.3

**Comment by qingdengyue** [comment]
fixed #6886

**Comment by furybean** [comment]
因为这个修复被 Merge，此 issue 关闭。
