### ISSUE TITLE
[Bug Report] A long table can cause a delay in triggering of other components

### ISSUE THREAD

**Issue by FE-runner** [ElemeFE/element#6776]
### Element UI version
1.4.3

### OS/Browsers version
Chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/twtrqfv7/2/](https://jsfiddle.net/twtrqfv7/2/)

### Steps to reproduce
改变表格的长度 点击selector观察下拉框显示

### What is Expected?
不会影响其他组件的操作

### What is actually happening?
会影响

**Comment by Leopoldthecoder** [comment]
页面上元素太多，请用分页解决。
