### ISSUE TITLE
[Bug Report] 怎么让datePicker v-model所绑定的值转换成“yy-mm-dd”格式的，而不是UTC格式

### ISSUE THREAD

**Issue by minororange** [ElemeFE/element#6777]
### Element UI version
1.4.3

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/q6em1cfy/](https://jsfiddle.net/q6em1cfy/)

### Steps to reproduce
选择完时间后，v-model所绑定的值是UTC格式，而不是input框中的值。

### What is Expected?
所见即所得，而并非：显示的是“yy-mm-dd”，拿到的却是UTC。看了官方文档，没有看到 el-date-picker 中有相关的设置选项。

### What is actually happening?
选择完时间后，v-model所绑定的值是UTC格式，而不是input框中的值。

**Comment by Leopoldthecoder** [comment]
绑定值是 Date 对象，需要自己转换。
