### ISSUE TITLE
[Bug Report] form element V-model dynamic values, validation is always through

### ISSUE THREAD

**Issue by kongjiea** [ElemeFE/element#6779]
### Element UI version
1.4.3

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/gr6uvu6x/](https://jsfiddle.net/gr6uvu6x/)

### Steps to reproduce
输入框输入值以后，失去焦点，总是验证显示错误，其实非空就应该验证正确

### What is Expected?
只做了非空验证，输入框输入任何东西，失去焦点，验证都应该是 验证ok

### What is actually happening?
输入框输入值以后，失去焦点，总是验证显示错误，其实非空就应该验证正确

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gr6uvu6x/1/
