### ISSUE TITLE
[Bug Report] fixed head table cannot set height to 100%

### ISSUE THREAD

**Issue by maplewizard** [ElemeFE/element#6781]
### Element UI version
1.4.3

### OS/Browsers version
windows10/chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/54arxpq5/](https://jsfiddle.net/54arxpq5/)

### Steps to reproduce
When height was set to 100% the head fix function not work.

### What is Expected?
the table should be fill the whole window, and the table is fixed

### What is actually happening?
The table head is not fixed any more, it seems only support a given pixel number. But when we work in different environments, the window's size changes and setting height according to portion is important and wide used. Could you please fix this bug for portion input?

**Comment by maplewizard** [comment]
Hi, @Leopoldthecoder is there any idea related to this issue?

**Comment by furybean** [comment]
@maplewizard 
这个是你对 height="100%" 的理解有误，目前的实现逻辑是这样：
1. 只要 height 不是数字，则认为 height 受控于外部样式，这个值没有任何意义。
2. 你需要通过外部样式设置 100%。

解决问题很简单，style 里面加上 `height:100%` 就可以，在线链接： https://jsfiddle.net/54arxpq5/7/

近期这个问题会解决，可以关注下这个 issue：#8896。@maplewizard 
这个是你对 height="100%" 的理解有误，目前的实现逻辑是这样：
1. 只要 height 不是数字，则认为 height 受控于外部样式，这个值没有任何意义。
2. 你需要通过外部样式设置 100%。

解决问题很简单，style 里面加上 `height:100%` 就可以，在线链接： https://jsfiddle.net/54arxpq5/7/

近期这个问题会解决，可以关注下这个 issue：#8896。
