### ISSUE TITLE
[Bug Report] Min/max on input (type="number") doesn't work

### ISSUE THREAD

**Issue by amorriscode** [ElemeFE/element#6782]
### Element UI version
1.4.3

### OS/Browsers version
macOs Sierra 10.12.6 / Chrome Version 60.0.3112.101

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/522/](https://jsfiddle.net/pj71jkyw/522/)

### Steps to reproduce
1. Put an `<el-input type="number" :min="0" :max="100"></el-input>` somewhere
2. Put in a number higher than 100

### What is Expected?
You should not be able to put in a number higher than 100 when the max is set to 100.

### What is actually happening?
You can put in a number higher than 100 when the max is set to 100.

**Comment by amorriscode** [comment]
I think this could actually be closed; the issue is min/max doesn't validate unless you do HTML5 form submission. Perhaps we could have a min/max rule for validation (that doesn't require HTML5 form submission)?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/525/
