### ISSUE TITLE
[Issue] vue-wizard-form step validation on v-for

### ISSUE THREAD

**Issue by vhs1092** [ElemeFE/element#6783]
### Existing Component
Yes

### Component Name
validation

### Description
I am working with vue-form-wizard plugin by https://github.com/cristijora/vue-form-wizard but I am having trouble with v-for, when I set the attribute "prop" with the "option" It validates all the radio inputs but is not validating correctly.

I figured out that I need to set the prop attr like prop="test.option" where test is my array, but since it is a loop the array name is on the key but I am not able to do this with vue prop="key.option"

https://jsfiddle.net/bt5dhqtf/900/

**Comment by Leopoldthecoder** [comment]
Take a look at http://element.eleme.io/#/en-US/component/form#delete-or-add-form-items-dynamically
