### ISSUE TITLE
[Feature, Request], cascader, cascading selector components, hover expand, click Select

### ISSUE THREAD

**Issue by SuperAL** [ElemeFE/element#6785]
### Existing Component
Yes

### Component Name
el-cascader

### Description
同时开启change-on-select 和 expand-trigger="hover" 选项后，希望得到hover展开、用click选中的功能。要不然监听 change 事件就会一直在hover展开时触发。
希望可以增加 change-on-click 选项 或者 click 事件（原有的是 change 事件）

**Comment by nicowenterodt** [comment]
This would be very useful indeed.

**Comment by xianshenglu** [comment]
I think this is a bug of `change-on-select` when `expand-trigger="hover"`.
