### ISSUE TITLE
The data in the [Bug Report] window affects the data

### ISSUE THREAD

**Issue by willbefine** [ElemeFE/element#6786]
### Element UI version
1.4.2

### OS/Browsers version
win 7 版本  chrome 58.0.3029.110 (64-bit) 

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/523/](https://jsfiddle.net/pj71jkyw/523/)

### Steps to reproduce
1 、点击编辑按钮，打开编辑弹窗；
2、选择天数，金额会随之变化；
3、不点击确定按钮，点击其它地方或者点击关闭叉号，金额发生了变化；

1, click the Edit button, open the edit window;
2, select the number of days, the amount will change;
3, do not click the OK button, click on other places or click to close the fork, the original amount has changed;

### What is Expected?
弹窗里的数据无论怎么编辑，再未点确定保存前，都不影响原数据。

The data in the window no matter how to edit, and then no point to determine the preservation before, does not affect the original data.

### What is actually happening?
只要弹窗里的数据发生变化，原数据也会变化

As long as the data in the window changes, the original data will change

**Comment by Leopoldthecoder** [comment]
引用的是同一个对象，自然会同步。

**Comment by willbefine** [comment]
怎么样才能达到预期的效果？
