### ISSUE TITLE
IE9 input不显示placeholder

### ISSUE THREAD

**Issue by cpwpioneer** [ElemeFE/element#6787]
Element UI version

1.4.3

OS/Browsers version

windows7/IE9

Vue version

2.4.2

Reproduction Link

https://jsfiddle.net/api/post/library/pure/

Steps to reproduce

使用ie9打开https://jsfiddle.net/api/post/library/pure/ 即可重现

What is Expected?

正常显示显示placeholder

What is actually happening?

不显示placeholder

**Comment by liwenda122** [comment]
自己写一个 透明div v-if = 'showPlaceholder'
mounted
blur
focus
时做判断 控制 showPlaceholder =true/false 即可
