### ISSUE TITLE
[Bug Report] IE9 input does not display placeholder

### ISSUE THREAD

**Issue by cpwpioneer** [ElemeFE/element#6788]
### Element UI version
1.4.3

### OS/Browsers version
windows7/IE9

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
使用ie9打开https://jsfiddle.net/api/post/library/pure/ 即可重现

### What is Expected?
正常显示显示placeholder

### What is actually happening?
不显示placeholder

**Comment by cpwpioneer** [comment]
please open the URL： http://element.eleme.io/#/zh-CN/component/input   with IE9

**Comment by smares** [comment]
Element uses the `placeholder` attribute of `input` and that is only supported in IE 10 upwards: https://www.w3schools.com/tags/att_input_placeholder.asp

**Comment by syn-zeta** [comment]
@Leopoldthecoder @QingWei-Li Recommend closing.
