### ISSUE TITLE
[Bug, Report], select, and datepicker, similar selection controls, cannot validate form validation with blur events

### ISSUE THREAD

**Issue by kongjiea** [ElemeFE/element#6790]
### Element UI version
1.4.3

### OS/Browsers version
谷歌浏览器

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/52apj8jb/1/](https://jsfiddle.net/52apj8jb/1/)

### Steps to reproduce
前置条件blur事件进行非空验证，  
操作方式1：点击select表单，不选择东西， blur失去焦点    没有验证提示
操作方式2：点击提交表单，出现验证提示， 对select选择一个选项，blur失去焦点，没有再次验证ok

### What is Expected?
操作方式1：点击select表单，不选择东西， blur失去焦点       【应该提示非空验证的提示内容】
操作方式2：点击提交表单，出现验证提示， 对select选择一个选项，blur失去焦点，【应该隐藏错误的提示内容】

### What is actually happening?
前置条件blur事件进行非空验证，  
操作方式1：点击select表单，不选择东西， blur失去焦点    没有验证提示
操作方式2：点击提交表单，出现验证提示， 对select选择一个选项，blur失去焦点，没有再次验证ok

**Comment by Leopoldthecoder** [comment]
Select 目前仅支持 `change` 验证。

**Comment by Masber** [comment]
Why select only supports change verification? Is this intentional? what is the reason for this?

thank you
