### ISSUE TITLE
[Bug, Report], Error, in, directive, bind, hook, Popover, TypeError:, Cannnot, read,, property,'$refs', of, undefined

### ISSUE THREAD

**Issue by FrankKelur** [ElemeFE/element#6795]
### Element UI version
1.4.3

### OS/Browsers version
win10/ chrome last version

### Vue version
2.4.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
In el-transfer render-content function

createElement('i', {
  directives: [{
    name: 'popover',
    arg: 'popoverImg'
  }]
})

### What is Expected?
期望点击el-transfer 中 i 弹出弹框

### What is actually happening?
Error in directive popover bind hook TypeError: Cannnot read property '$refs' of undefined

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
