### ISSUE TITLE
[Bug Report] repeats the call on the formatter method of the table column

### ISSUE THREAD

**Issue by pucong** [ElemeFE/element#6796]
### Element UI version
1.4.3

### OS/Browsers version
谷歌浏览器 60.0.3112.113

### Vue version
2.4.2

### Steps to reproduce
  <el-table
    :data="tableData"
    stripe
    style="width: 100%">
    <el-table-column
      prop="date"
      label="日期"
      width="180" :formatter="stateFormatter">
    </el-table-column>
  </el-table>
表格会重复调用 stateFormatter的函数

### What is Expected?
表格一行会只调用 一次stateFormatter函数

### What is actually happening?
多次调用formatter

**Comment by Leopoldthecoder** [comment]
Duplicate of #6276

**Comment by hkongm** [comment]
打算修么？
