### ISSUE TITLE
求问，有没有人遇到过两个子组件中的两个table共享父组件的数据，子组件请求父组件更新数据后，另外一个组件没有渲染出来更新的数据……

### ISSUE THREAD

**Issue by zhangyile** [ElemeFE/element#6799]
如题：

问题是这样的，第一次渲染的时候都是正常的，我先点击用户管理标签，然后再点击用户组管理的标签，然后点击刷新（请求父组件更新一下数据），然后再点击用户管理标签，发现用户管理标签中的table没有显示出来，我点一下刷新后，就可以显示出来，但是再跳转到用户标签的时候，用户标签的table又显示不出来了。。。。。
困扰了我两天了，求大神解救一下我。。。。。

代码很简单的。。。
看下面代码应该会更清楚我要表达的东西吧。。。。。

父组件：
```
<template>
  <el-tabs v-model="activeName">
    <el-tab-pane label="用户管理" name="one">
      <usertable  :users="users" @toFresh="freshAll"></usertable>
    </el-tab-pane>
    <el-tab-pane label="用户组管理" name="two">
      <grouptable :groups="groups" @toFresh="freshAll"></grouptable>
    </el-tab-pane>
  </el-tabs>
</template>
<script>
  import usertable from './UserTable'
  import grouptable from './GroupTable'
  export default {
    data() {
      return {
        activeName: 'one',
        users: [],
        groups: [],
      };
    },
    components:{
      usertable,
      grouptable,
    },
    created(){
      this.freshAll()
    },
    methods: {
      freshAll(){
        this.groups = [{name:'groups'}]
        this.users = [{name:'users'}]
      }
    }
  };
</script>```

用户管理组件：
```<template>
<div>
  <h3>用户管理</h3>
  <el-button @click="toFresh()"> 刷 新</el-button>
  <el-table :data="users">

    <el-table-column
      prop="name"
      label="姓名">
    </el-table-column>

  </el-table>
</div>
</template>

<script>
  export default{ 
    props:{
      users: Array
    },
    methods:{
      toFresh(){
        this.$emit('toFresh')
      },
    },
  }
</script>
```

用户组管理组件：
```
<template>
<div>
  <h3>用户组管理</h3>


  <el-button @click="toFresh()"> 刷 新</el-button>


  <el-table :data="groups">
    <el-table-column
      prop="name"
      label="组名"
      width="100">
    </el-table-column>
  </el-table>
</div>
</template>

<script>
  export default{ 
    props:{
      groups: Array
    },
    methods:{
      toFresh(){
        this.$emit('toFresh')
      },
    }
  }
</script>
```

**Comment by JinboMa** [comment]
我也碰到了同样的问题。。。。

**Comment by yhhwpp** [comment]
最好贴个`jsfiddle`地址

**Comment by idujiayou** [comment]
this.groups = [{name:'groups'}]
 this.users = [{name:'users'}]
你可以尝试使用 数组操作  如push splice 
我怀疑是 这样直接赋值 导致的

**Comment by JinboMa** [comment]
<template>
  <el-tabs v-model="activeName">
    <el-tab-pane label="用户管理" name="one">
      <usertable  :users="users" @toFresh="freshAll" v-if="activeName==='one'"></usertable>
    </el-tab-pane>
    <el-tab-pane label="用户组管理" name="two">
      <grouptable :groups="groups" @toFresh="freshAll" v-if="activeName==='two'"></grouptable>
    </el-tab-pane>
  </el-tabs>
</template>
把两个table加上v-if，这样table会在tab改变时触发table重新渲染，这样就不会消失了，消失的原因是因为el-table上加了el-table-hidden类，但为什么会加上不清楚。

**Comment by zhangyile** [comment]
https://jsfiddle.net/Zhangyile/a366xkzm/
@yhhwpp

**Comment by yhhwpp** [comment]
@zhangyile 我通过调试证明，组件已经渲染出来数据了，只是由于`tab`内容`el-table--hidden`导致隐藏的

**Comment by imyundong** [comment]
@zhangyile 在你的jsfiddle上没有复现问题，可是在项目上遇到了，除了用v-if，还有别的办法吗？

**Comment by focusqfb** [comment]
我也遇到这个问题，加上v-if也不行啊。。。你解决了吗

**Comment by guokangf** [comment]
@imyundong @focusqfb @zhangyile 同问题, 查看tag中代码 是因为isHidden属性 输出自己table中的clientWidth是有值的. 不明白为什么为加上隐藏的类名. 你们如何解决了 v-if 不行

**Comment by zhangyile** [comment]
@guokangf 你用的是哪个版本？有demo吗？我的那个问题复现不了了。。。

**Comment by guokangf** [comment]
我用的是1.42  我写过demo 实现不了 只有在现在项目 里面会有. 我看了源码. 它里面的setData的时候会检测 执行那个方法.  我的解决方案就是 加一个数据 再删了 就没问题了
