### ISSUE TITLE
[Feature Request] tree组件使用load函数时，提前判断子节点是否为叶子节点

### ISSUE THREAD

**Issue by geraldlrh** [ElemeFE/element#6800]
现在只支持点击的时候才去判断是否还有下层数据，导致一开始下拉按钮是可见的，如果没下层数据了，点了一下按钮消失了，用户体验很不好。事实上接口能在获取子节点的时候，就可以判断是否为叶子节点。

**Comment by 811722066** [comment]
请问这个问题解决了吗？？
