### ISSUE TITLE
When using the load function, the [Feature Request] tree component determines whether the child node is a leaf node in advance

### ISSUE THREAD

**Issue by geraldlrh** [ElemeFE/element#6801]
### Existing Component
Yes

### Component Name
tree

### Description
现在只支持点击的时候才去判断是否还有下层数据，导致一开始下拉按钮是可见的；如果没下层数据了，点了一下按钮消失了，用户体验很不好。事实上接口能在获取子节点的时候，就可以判断是否为叶子节点，从而不显示下拉按钮。希望resolve可以支持是否叶子节点，比如resolve([{ isLeaf: true }])

**Comment by Leopoldthecoder** [comment]
下个大版本已增加支持，请等待发布。
