### ISSUE TITLE
[Bug Report] Date reset problem in el-date-picker when type is daterange

### ISSUE THREAD

**Issue by IridescentMia** [ElemeFE/element#6802]
### Element UI version
1.4.3

### OS/Browsers version
windows 7 / chrome 60.0.3112.113

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/IridescentMia/p9xm1thn/](https://jsfiddle.net/IridescentMia/p9xm1thn/)

### Steps to reproduce
1. the first initDate function with annotation works well

2. the second initDate function doesn't work

### What is Expected?
Date reset when click on the button RESET DATE

### What is actually happening?
Date reset fail

**Comment by huguangju** [comment]
This is not the problem of Element UI, is the reason Vue's responsive mechanism, it is recommended to look at the document: [Reactivity in Depth](https://vuejs.org/v2/guide/reactivity.html) and [List Rendering](https://vuejs.org/v2/guide/list.html#Caveats).

> Due to limitations in JavaScript, Vue `cannot` detect the following changes to an array:
> 1. When you directly set an item with the index, e.g. `vm.items[indexOfItem] = newValue`
> 2. When you modify the length of the array, e.g. `vm.items.length = newLength`

In `initData`, the following ways to achieve your purpose:

1. Use `this.$set` or `Vue.set`

```js
this.$set(this.timerange, 0, '2017-08-20')
this.$set(this.timerange, 1, '2017-08-31')
```

2. Override the value of `this.timerange`

```js
this.timerange = ['2017-08-20', '2017-08-31'];
```
