### ISSUE TITLE
[Bug Report] can not add maxLength in autocomplete

### ISSUE THREAD

**Issue by dsky1990** [ElemeFE/element#6804]
### Element UI version
1.4.3

### OS/Browsers version
chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/xu572ysd/](https://jsfiddle.net/xu572ysd/)

### Steps to reproduce
enter the word 

### What is Expected?
less then 11 words can enter

### What is actually happening?
more then 11 words can enter

**Comment by Leopoldthecoder** [comment]
Autocomplete doesn't support `maxlength`.

**Comment by dsky1990** [comment]
what if i want？how to slove it？ I don't think it's good way to just can prop some property , but it can get more property  in fact

**Comment by dsky1990** [comment]
@Leopoldthecoder
