### ISSUE TITLE
[Feature Request] How re use part of DatePicker component

### ISSUE THREAD

**Issue by newbie78** [ElemeFE/element#6805]
### Existing Component
Yes

### Component Name
DatePicker

### Description
How do I use element-ui/packages/date-picker/src/panel/date.vue as a separate component. I need to show the calendar in a specific block on the page.
```
import DatePanel from 'element-ui/packages/date-picker/src/panel/date'
Vue.component('el-date-panel', DatePanel)
```
does not work for me
i'm novice in vue and node, please help

i'm need something like this: http://geoffzhu.cn/vue-event-calendar/
but by the Element components

tnx!

**Comment by Leopoldthecoder** [comment]
We have no plan to provide an inline Datepicker.

**Comment by newbie78** [comment]
It's sad. But thanks for the answer!

**Comment by syn-zeta** [comment]
@Leopoldthecoder Is there any particular reason? I can't imagine that implementing the option would be too difficult; I can work on a PR if needed. This seems to be a basic functionality provided by most other datepicker libraries, likely because it is often used.

If you think that there wouldn't be enough user interest, then maybe we can update the title to `[Feature Request] Inline DatePicker component` and keep this ticket open for a bit to see if there's any activity here.

**Comment by syn-zeta** [comment]
Some response from the maintainers will be greatly appreciated here.
@Leopoldthecoder @QingWei-Li @baiyaaaaa

**Comment by antonVl** [comment]
I have usercase to show inline date picker without any animation like simple div. It will be fine if you implement this feature.

**Comment by japhfortin** [comment]
Ff

**Comment by buremba** [comment]
Any future plans on this issue as it's been more than 2 years?

**Comment by japhfortin** [comment]
+1

**Comment by arthabus** [comment]
+1

**Comment by milostimotic** [comment]
+1

**Comment by Hunlongyu** [comment]
Plz support inline picker!!

**Comment by phonginx** [comment]
+1

**Comment by Hunlongyu** [comment]
+ 1

**Comment by buremba** [comment]
+1

**Comment by a-kriya** [comment]
I'd suggest moving on. These two seem promising, and provide what you're looking for:
https://buefy.org/documentation/datetimepicker/#inline
https://bootstrap-vue.org/docs/components/calendar#overview

**Comment by arthabus** [comment]
@a-kriya shipping yet another framework with the source code just to be able to use what's already present in the current one doesn't look very efficient. Lot's of people seem to need it and assuming this library still maintained, it would be really helpful if the team could consider the demand and to add the "inline" option to the existing picker.

**Comment by a-kriya** [comment]
@arthabus I thought it was clear that this library isn't actively maintained, and by moving on, I meant that the other two frameworks can be used instead (for new projects). For existing projects, standalone components (or a fork) are an option:

https://www.npmjs.com/package/vuejs-datepicker
https://vcalendar.io/

**Comment by buremba** [comment]
There is also an attempt to maintain a new fork (https://github.com/EOITek/element) but it doesn't seem to be active anymore. We use 10+ components from this library and I suspect that many others also do the same as this library has great coverage. It would be great if the maintainers are willing to create a poll and let other core maintainers take the decisions.

P.S: For example, we use week and year selector as well which is not available in most of the alternatives. VCalendar itself is 250kb minified and bigger than the bundled version of this library.

**Comment by a-kriya** [comment]
The core maintainers of this library are/were employees of Ele.me. It just looks like they've pulled resources from it.

If you really need an inline Element picker, then you'll likely have to fork and implement it yourself. Just saying that bumping this ticket is not gonna do much when the only maintainer who'd responded and closed this isn't even with Ele.me anymore.

**Comment by buremba** [comment]
TBH, I use CSS and invoke the JS internally as a workaround and it works even if it's nasty. I even created an issue and put a bounty on it (https://github.com/ElemeFE/element/issues/18175) but the core maintainers don't that they will rewrite the date picker logic so we need to wait for some time. It's been a long time though, we should probably create a fork in a near feature if the maintainers are not interested in it. 

I see that you're one of the core maintainers of the library that you shared and that's reasonable for you to share your library here in this case. However; our app extensively uses Element and the app bundle is almost 2.5MB minified so we're conservative adding a new library and the switching cost is too high at the moment.

**Comment by a-kriya** [comment]
That's one way to do it. But I think Element has been bloated for a long time now (as it tried to cater to everyone) and maintaining a fork of it may be more trouble than worth (as evident with the fork that you shared above). For an enterprise project, we've kept it pinned to v2.3.6.

By the way, I've just contributed to Buefy, as I'd contributed to Element.

**Comment by arthabus** [comment]
>a-kriya  I thought it was clear that this library isn't actively maintained...

@a-kriya That's a bad news... Maybe it would make sense to indicate that in the readme then? Might be helpful for newcomers and for those who was hoping for fixes.

**Comment by a-kriya** [comment]
@arthabus Probably, but I'm just a user (and a small-time contributor), so that is not really up to me. The frequency of commits and releases, along with the # of open issues/PRs and activity within them is a good indicator of how a project is maintained, and this one hasn't been doing well with any of those for a while.

**Comment by hieunguyenbellface** [comment]
+1

**Comment by commonpike** [comment]
+1

**Comment by Sovai** [comment]
+1

**Comment by Sovai** [comment]
+1

**Comment by SaadRegal** [comment]
+1

**Comment by alexanderkraemer** [comment]
+1

**Comment by vildanbina** [comment]
If something new desn't made. You can see below example to do inline date-picker component:

```
<style>
  .inline-datepicker {
    position: static !important;
    display: block !important;
    opacity: 1 !important;
    transform: none !important;
  }
  
  .inline-datepicker .el-popper__arrow {
    display: none;
  }
</style>

<template>
    <el-date-picker
        popper-class="inline-datepicker"
        :teleported="false"
        style="display: none!important"
    />
</template>
```
