### ISSUE TITLE
[Bug Report] pagination pagesize binding in jumper

### ISSUE THREAD

**Issue by StevenYuysy** [ElemeFE/element#6809]
### Element UI version
1.4.3

### OS/Browsers version
MacOS / Chrome 

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/532/](https://jsfiddle.net/pj71jkyw/532/)

### Steps to reproduce
- 点击 5
- 删掉 `jumper` 里面的 5
- 点击前进

### What is Expected?
- 此时应该是 6

### What is actually happening?
- 跳回第一页

**Comment by Leopoldthecoder** [comment]
> 点击前进

哪里有「前进」？

**Comment by StevenYuysy** [comment]
next

**Comment by huguangju** [comment]
@StevenYuysy 删除jumper中的数字后，当前页跳到第1页并不是点击next直接导致的，而是jumper失焦后其值此时为空字符串，应用值到internalCurrentPage前会校验设置的页码，部分源码如下，会被设置为1：

```js
getValidCurrentPage(value) {
      value = parseInt(value, 10);
      // ...
      if (resetValue === undefined && isNaN(value)) {
        resetValue = 1; // here
      } else if (resetValue === 0) {
        resetValue = 1;
      }
      return resetValue === undefined ? value : resetValue;
    }
  }
```

**Comment by StevenYuysy** [comment]
@huguangju 
junmper 失焦时 `innerCurrentPage ` 被设置为 0，但是实际上，失焦的时候，页面没有发生跳转， `innerCurrentPage` 不应该会发生变化。

**Comment by huguangju** [comment]
@StevenYuysy `innerCurrentPage` 不会被设置为 0的。不过这里似乎存在问题，正常情况下，在 jumper
 中输入页码后，仅应在按下回车键再作跳转比较合理。例如，我想跳到第20页，输完之后改变了主意想先直接点到第二页看看，目前的情况就是：当点击第二页时，会首先跳到第20页（若pageCount小于20则跳到pageCount），然后才会跳到第二页，也就是说 `@current-change` 会执行两次。
