### ISSUE TITLE
tag出错

### ISSUE THREAD

**Issue by dyw934854565** [ElemeFE/element#681]
### Steps to reproduce
tag标签数组变化的时候报错
简单的看了一下，没找出问题，只好求助各位大神了。
数组不是该切换自如么，换到长度大于1就出问题了
[栗子](http://codepen.io/dyw/pen/WGWBwr?editors=1111)

**Comment by QingWei-Li** [comment]
你用了 `v-for`, 那么需要用 `key` 来做优化
```javascript
<el-tag v-for="(key, index) in list" :key="index"></el-tag>
```

**Comment by dyw934854565** [comment]
老是忘记这一茬，谢谢啦，老大哥
