### ISSUE TITLE
[Bug Report] packs element-ui collapse-transition using webpack and fails

### ISSUE THREAD

**Issue by idujiayou** [ElemeFE/element#6811]
### Element UI version
1.4.3

### OS/Browsers version
all

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
1. 引入 import ElementUI from 'element-ui/src/index
2. webpack 版本 2.2.1   vue 版本 2.4.2
3. .babelrc
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2",
    "es2015",
    "flow-vue"
  ],
  "plugins": ["transform-runtime", "transform-vue-jsx", "transform-flow-strip-types"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}，
4. 进入源码  src/transitions/collapse-transition  调试下面代码 发现Transition的方法都行挂在prototype下面 无法枚举 导致h('transition', data, children); 中on无法获取对应方法
export default {
  name: 'ElCollapseTransition',
  functional: true,
  render(h, { children }) {
    const data = {
      on: new Transition()
    };

    return h('transition', data, children);
  }
};

### What is Expected?
在使用webpack打包下 collapse-transition能正常执行

### What is actually happening?
collapse-transition失效

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by xianghongai** [comment]
就直接关了？

**Comment by xianghongai** [comment]
原因是打包造成的，可能会出现在“魔改” Element UI 的场景中。
将 Class 语法改成 Prototype 语法，能“暂时”修复这个问题。
