### ISSUE TITLE
When [Bug Report] uses pattern for form validation, when it is filled correctly, there will be a success and then a failure

### ISSUE THREAD

**Issue by milo-wjh** [ElemeFE/element#6812]
### Element UI version
1.3.7

### OS/Browsers version
win10

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/8mwj5g7u/1/](https://jsfiddle.net/8mwj5g7u/1/)

### Steps to reproduce
1、input中填写符合正则的手机号码
2、blur后验证成功，没有提示错误
3、再次focus，不修改，或者修改为一个还是正确的手机号码
4、blur后，出现错误信息，
5、使用$ref.formname.validate也会出现这种情况

### What is Expected?
使用pattern进行验证确保准确性，不要出现一次成功，再一次失败的情况

### What is actually happening?
符合parttern的数据在不同次数的验证下 出现不同的结果

**Comment by Leopoldthecoder** [comment]
Remove the `g` flag: https://jsfiddle.net/8mwj5g7u/2/

I tested validating this pattern without Element and it still exists. So it's actually an `async-validator` bug. You can issue this at https://github.com/yiminghe/async-validator if you're interested.

**Comment by milo-wjh** [comment]
thank you
