### ISSUE TITLE
[Bug Report] When I use <el-switch> in <el-table><el-table-column> <template scope="scope">  It can not init success!!!

### ISSUE THREAD

**Issue by akai007** [ElemeFE/element#6817]
### Element UI version
1.4.3

### OS/Browsers version
Mac os / Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/akai007/56t4416t/](https://jsfiddle.net/akai007/56t4416t/)

### Steps to reproduce
open jsfiddle link see table

### What is Expected?
switch can init

### What is actually happening?
switch can't init

**Comment by Leopoldthecoder** [comment]
You don't have `status` field in your table data.

**Comment by Le-coder** [comment]
do you fix it?
