### ISSUE TITLE
[Feature, Request], Support, function, as, filter, value, in, attribute, table-column

### ISSUE THREAD

**Issue by bokeyy** [ElemeFE/element#6818]
### Existing Component
是

### Component Name
table-column

### Description
The filters attribute in table-column components is Array format, which is used to filter table data. 

A valid filters attribute example: Array[{ text:'one', value: 1 }, { text: 'two', value: 2 }] .

Need to support function as value.

Consider a value which can be a number from 1 to 10 , when we need a filters attribute like:
[
{text: 'great than 5'},
{text: 'less than 6'}
]

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ebxmbzvj/
