### ISSUE TITLE
[Bug Report] Datepicker range. Some table cells don't change color on hover.

### ISSUE THREAD

**Issue by sozzzzz** [ElemeFE/element#6822]
### Element UI version
1.4.3

### OS/Browsers version
Win10 / Chrome60.0.3112.113 / Firefox 55.0.3

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/trw7obw2/](https://jsfiddle.net/trw7obw2/)

### Steps to reproduce
Try to chose date range e.g. from 1th to 31th of October 2017. 
Try to chose date range e.g. from 1th to 31th of March 2017. 

### What is Expected?
Cells with 30th and 31th should change color on mouse over.
Cells from 27th to 31th should change color on hover.

### What is actually happening?
Cells with 30th and 31th don't change color on mouse over.
Cells from 27th to 31th don't change color on hover.

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/29995515-76d6bce6-901d-11e7-9705-2c17fa236dd1.gif)

Can't reproduce this.

**Comment by sozzzzz** [comment]
![datepicker](https://user-images.githubusercontent.com/22654540/30031609-83cd91f6-9192-11e7-9268-f96ed1c28ed8.gif)
Also checked on MacOS. There is the same situation.

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/30032016-4003897e-91c6-11e7-8df7-473ca2b394b4.gif)

还是没能重现
