### ISSUE TITLE
[Feature Request] upload offers more customization options

### ISSUE THREAD

**Issue by maicss** [ElemeFE/element#6823]
### Existing Component
是

### Component Name
upload

### Description
1，增加文件选择按钮外置的选项。现在只能自己添加一个按钮，然后点击的时候document.query('input[type=file]'])，这样多个upload的时候就挂掉了，因为你们把input[type=file]内置了，不能添加自定义标示。

2，增加自定义预览图大小的选项。现在想修改预览图大小的时候，只能靠hack全局的css class来实现

**Comment by maicss** [comment]
外面的按钮其实就是需要暴露那个点击事件的钩子而已，然后需要给每个初始化的upload组件定义一个不同的标示就可以了。

**Comment by Leopoldthecoder** [comment]
We have no plan to support this.
