### ISSUE TITLE
Table组件不支持远程排序

### ISSUE THREAD

**Issue by baiqb** [ElemeFE/element#683]
### ElementUI version

1.0.0-rc.5
### OS/Browers version

Chrome54
### Vue version

2.0.1
### Steps to reproduce
Table组件 el-table-column 支持本地排序，但不支持远程排序，这样只能排序当前页的数据
建议添加remoteSort属性，用于设置是远程排序还是本地排序，远程排序时，触发事件：包含排序字段及排序方式（升序、降序、默认）

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/issues/595 rc8 将支持

**Comment by furybean** [comment]
关闭原因是和 #595 重复。
