### ISSUE TITLE
[Feature Request] Hide on Media Size based on settings in el-col media queries

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#6830]
### Existing Component
Yes

### Component Name
el-col

### Description

When specifying `:sm="6"` or `:md="12"` for example, then `:lg="0"` should **hide** the `el-col`, or have some other means of hiding or showing items based on screen size. Somewhat like Bootstrap's `hide-on-sm-down` etc.

**Example:**
https://jsfiddle.net/pj71jkyw/497/

**Comment by Leopoldthecoder** [comment]
Fixed in #7541
