### ISSUE TITLE
[Bug, Report], DatePicker, use, picker-options, month, disabled

### ISSUE THREAD

**Issue by lhajh** [ElemeFE/element#6834]
### Element UI version
1.4.3

### OS/Browsers version
WIN7 / chrome60

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/533/](https://jsfiddle.net/pj71jkyw/533/)

### Steps to reproduce
现在升级有一个很大的bug，http://element.eleme.io/#/zh-CN/component/date-picker#xuan-ze-ri
当做了限制后，先点年

![](https://i.imgur.com/l1xqums.png)

再选择2017

![](https://i.imgur.com/ZBySAEl.png)

所有月份都不能点击了

![](https://i.imgur.com/8615TrS.png)
![](https://i.imgur.com/5jgBBXn.png)

### What is Expected?
选择年后，月份也可以选择

### What is actually happening?
选择年后，所有月份都不能选择

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/6768

**Comment by yingjunX** [comment]
我遇到了同样的问题，请问有知道的吗？
