### ISSUE TITLE
[Bug Report] Popover is invalid in the step bar

### ISSUE THREAD

**Issue by wucuida** [ElemeFE/element#6840]
### Element UI version
1.4.3

### OS/Browsers version
win8.1/chrome 版本 60.0.3112.113（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/wucd/zm9qj1av/](https://jsfiddle.net/wucd/zm9qj1av/)

### Steps to reproduce
在步骤条组件中，以在<el-step></el-step>中使用Popover 弹出框， 

### What is Expected?
正常弹出内容

### What is actually happening?
报错：vue.js:485 [Vue warn]: Error in directive popover bind hook: "TypeError: Cannot read property '$refs' of undefined"

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/zm9qj1av/1/

**Comment by samon127** [comment]
#246 这里的解决方案可以试试，是不是因为 popover 和 button 的顺序问题~
