### ISSUE TITLE
Select [Bug Report] asynchronous loading component tree

### ISSUE THREAD

**Issue by xxholly32** [ElemeFE/element#6841]
### Element UI version
1.4.3

### OS/Browsers version
win10/chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/xxholly32/y96q9f9f/](https://jsfiddle.net/xxholly32/y96q9f9f/)

### Steps to reproduce
1、进入可选择树
2、第一层region1展开，出现加载圈，（没问题）
3、再全选region1节点，下面的zone都出现加载圈
4、项目中节点会异步加载，某一层节点多会导致全选会发多个请求

### What is Expected?
无法判断loadData到底是展开，还是多选出现的，如果checkStrictly修改无法联动节点，希望能够区分事件或者加 treestore参数

### What is actually happening?
多选父节点，子节点过多，子节点又是异步加载，会触发多次请求，影响页面性能

**Comment by Leopoldthecoder** [comment]
在下一个大版本中，全选父节点不会再加载子节点了。请耐心等待。

**Comment by xxholly32** [comment]
这个问题已经在2.0.0版本中解决了
[#6257](https://github.com/ElemeFE/element/pull/6257)
