### ISSUE TITLE
[Bug Report] el-elect fires remoteMethod even though the v-model id doesn't match any value of el-options

### ISSUE THREAD

**Issue by lsycxyj** [ElemeFE/element#6845]
### Element UI version
1.4.1

### OS/Browsers version
Any

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
My computer was blocked by GFW. Codes are here.
```html
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui/lib/index.js"></script>
<div id="app">
  <el-select v-model="input" remoteMethod="log"></el-select>
</div>
```

```css
@import url("//unpkg.com/element-ui/lib/theme-default/index.css");
```

```JS
var Main = {
  data() {
    return {
      input: 5
    }
  },
  methods: {log(){ console.log('fired') }}
}
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')
```
### What is Expected?
5 should not be shown and remoteMethod should not be fired.

### What is actually happening?
5 was shown and remoteMethod was fired.

**Comment by Leopoldthecoder** [comment]
If you don't want 5 to be shown, you can avoid initializing `input`. Assign `input` after you have the corresponding option. `remote-method` behavior will be updated in the next major version, and it will not fire on initialization.

**Comment by lsycxyj** [comment]
@Leopoldthecoder When will the next major version will be released?
