### ISSUE TITLE
最近一次更新的“修复 DatePicker 的月视图错误计算禁用日期的问题，#6363”，我以前的代码反而出错了呢？

### ISSUE THREAD

**Issue by michaelzhouh** [ElemeFE/element#6846]
我以前的代码都是OK的，最近更新了一次element-ui，月份试图的禁用就失效了，以前是对的。现在是所有月份都是 灰色了，不能选择。
`<el-date-picker type="month" :picker-options="pickerOptionsBegin"`
下面是计算属性：
`pickerOptionsBegin () {
        return {
          firstDayOfWeek: 1,
          disabledDate(time) {
            let begin = new Date(2015, 0, 1);
            let end = new Date();
            return time.getTime() < begin.getTime() || time.getTime() > end.getTime();
          }
        }
      }`

非常希望能解决，不胜感激。

**Comment by yingjunX** [comment]
这个很明显就是一个大Bug啊，很多人都遇到了
