### ISSUE TITLE
[Bug Report] why the disabledDate is not about type of month ?

### ISSUE THREAD

**Issue by wjf444128852** [ElemeFE/element#6851]
### Element UI version
1.4.3

### OS/Browsers version
chrome last version

### Vue version
2.4.2

### Reproduction Link
[ https://jsfiddle.net/f2n5tspw/5/]( https://jsfiddle.net/f2n5tspw/5/)

### Steps to reproduce
see here  https://jsfiddle.net/f2n5tspw/5/

### What is Expected?
disabledDate  was not correct about type of month!

### What is actually happening?
it was correct ,when i move the application to anther floder and install it was not correct about type of month

**Comment by huguangju** [comment]
Fixed in #6768

**Comment by wjf444128852** [comment]
@huguangju TKS
