### ISSUE TITLE
The [Feature Request] Tree component adds the data collection function of the selected node (parent node, child node)

### ISSUE THREAD

**Issue by 1657413883** [ElemeFE/element#6859]
### Existing Component
是

### Component Name
Tree组件

### Description
Tree组件不仅仅用于UI展示.
实际应用中, 需要自动收集所有勾选的节点的数据, 常见的如Id, Value.

**Comment by Leopoldthecoder** [comment]
You can access tree node data in `check-change` event (or other events you see fit).
