### ISSUE TITLE
After [Bug Report] el-date-picker hits, all the months are gray and cannot be clicked Sos.

### ISSUE THREAD

**Issue by michaelzhouh** [ElemeFE/element#6861]
### Element UI version
1.4.3

### OS/Browsers version
google chrome 60.0.3112.78（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/540/](https://jsfiddle.net/pj71jkyw/540/)

### Steps to reproduce
1.4.1版本我这段代码是OK的，只能选择2015到现在的日期。
更新到1.4.3版，点击了年，所有月份都是灰色，不能点击。

### What is Expected?
1.4.1版本我这段代码是OK的，只能选择2015到现在的日期。

### What is actually happening?
更新到1.4.3版，点击了年，所有月份都是灰色，不能点击。

**Comment by Leopoldthecoder** [comment]
Fixed in #6768
