### ISSUE TITLE
[Feature Request] render function should be supported as well as Notification

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#6865]
### Existing Component
Yes

### Component Name
Notification

### Description
![image](https://user-images.githubusercontent.com/1060733/30052106-0ce876da-9257-11e7-98a8-750497ac297a.png)

![image](https://user-images.githubusercontent.com/1060733/30052143-23ea8710-9257-11e7-90bc-5d06b7421847.png)

`message: function(h){return h(sth.)}` should be used instead of directly call the h function
because it is strange to define `const h = this.$createElement` at the beginning

**Comment by Leopoldthecoder** [comment]
This makes little difference, so we have no plan to support this.
