### ISSUE TITLE
How is [Feature Request] set so that text in `el-radio` can be copied?

### ISSUE THREAD

**Issue by minororange** [ElemeFE/element#6867]
### Existing Component
是

### Component Name
el-radio

### Description
目前用的`el-radio`标签，标签中有`div`、`p`等标签，但是里面的文本内容都无法复制，小弟我对前端css和html都不是太熟，求大佬解惑，谢谢了

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
