### ISSUE TITLE
[Feature Request] NavMenu multi-level

### ISSUE THREAD

**Issue by kolesoffac** [ElemeFE/element#6870]
### Existing Component
Yes

### Component Name
NavMenu

### Description
Is there plan for add multi-level of NavMenu? No flat - http://element.eleme.io/#/en-US/component/menu#side-bar . I would like hierarchically.

**Comment by Leopoldthecoder** [comment]
You mean in horizontal mode?

**Comment by kolesoffac** [comment]
Without difference horizontal or vertical, but now more interest vertical mode.

**Comment by Leopoldthecoder** [comment]
Vertical Menu already supports multi-level. And if you prefer popup menu items, you can use `collapse`.

**Comment by kolesoffac** [comment]
![image](https://user-images.githubusercontent.com/11459507/30098969-c9f91780-92ec-11e7-8b01-4e090b438507.png)
This is possible?
