### ISSUE TITLE
Search for exceptions under [Bug Report] Cascader configuration props

### ISSUE THREAD

**Issue by leopard7777777** [ElemeFE/element#6878]
### Element UI version
1.4.4

### OS/Browsers version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/d1m244yL/](https://jsfiddle.net/d1m244yL/)

### Steps to reproduce
同时设置props和filterable

### What is Expected?
可以搜索出结果

### What is actually happening?
搜索结果全为蓝色

**Comment by Leopoldthecoder** [comment]
Fixed in #7225
