### ISSUE TITLE
When the [Bug Report] table is sorted, the checkbox selected state is not synchronized

### ISSUE THREAD

**Issue by kongjiea** [ElemeFE/element#6882]
### Element UI version
1.4.4

### OS/Browsers version
谷歌

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/545/](https://jsfiddle.net/pj71jkyw/545/)

### Steps to reproduce
1、选中第一行的checkbox， 
2、点击第一列的排序，升序、降序都点一下，针对第一列进行排序
问题：发现 第四个也会被选中，而且不能取消选中

### What is Expected?
应该正常排序，无关的checkbox不会被选中

### What is actually happening?
1、选中第一行的checkbox， 
2、点击第一列的排序，升序、降序都点一下，针对第一列进行排序
问题：发现 第四个也会被选中，而且不能取消选中

**Comment by Leopoldthecoder** [comment]
例子写得有问题，控制台有十个报错。处理掉报错之后是没问题的：https://jsfiddle.net/pj71jkyw/557/
