### ISSUE TITLE
[Bug, Report], table, nested, in, Popover, display, blank

### ISSUE THREAD

**Issue by spx443812507** [ElemeFE/element#6884]
### Element UI version
1.4.4

### OS/Browsers version
osx

### Vue version
2.3.0

### Reproduction Link
[http://jsfiddle.net/hqw1otj0/7/](http://jsfiddle.net/hqw1otj0/7/)

### Steps to reproduce
hover the speaker column in table, and speaker table display, then click "change Data" button
hover the speaker, the speaker table display blank
hover演讲嘉宾列出现popover，popover中嵌套表格，当刷新数据后表格不显示

### What is Expected?
speaker table in popover display correct

### What is actually happening?
speaker table in popover display blank

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/hqw1otj0/9/ 可以加个 `key`。不一定得是一个随机数，任何能确保唯一性的值都可以。
