### ISSUE TITLE
[Bug Report] Autocomplete props not working

### ISSUE THREAD

**Issue by venzeles** [ElemeFE/element#6889]
### Element UI version
1.4.4

### OS/Browsers version
Windows 10, Google Chrome 60.0.3112.113

### Vue version
2.4.2

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
https://codepen.io/venzeles/pen/WEBGZX

### What is Expected?
1) Enter the data and see the desired list of values.
2) Choose from the list of the desired and see the label in the field.

### What is actually happening?
1) Enter the data and see the desired list of values.
2) Choose from the list of the desired and see the value in the field.

**Comment by spx443812507** [comment]
in my opnion, filterable el-select is more suitable in your scene , the value of props of autocomplete input is what actually display in field

**Comment by EverCurse** [comment]
same as me，the options are all display

**Comment by Leopoldthecoder** [comment]
Fixed in #7206
