### ISSUE TITLE
Cannot read property 'indexPath'  

### ISSUE THREAD

**Issue by git-lt** [ElemeFE/element#689]
**Uncaught TypeError: Cannot read property 'indexPath' of undefined**

菜单是用数据循环出来的，在菜单第一次初始化的时候报这个错，以后触发 select 事件不会报错

```javascript
  <el-menu default-active="currMenuKey" id="nav-menu" theme="dark" @select="updateMenu" :router="useRoute">
      <el-menu-item v-for="item in menus" :index="item.path" :class="{'is-active':currMenuKey==item.key}"><span class="nav-link"><i class="iconfont">&#xe696;</i> {{item.name}} </span></el-menu-item>
    </el-menu>
```
![image](https://cloud.githubusercontent.com/assets/8443758/19772340/7491e3da-9c98-11e6-9b1d-9b139b86abb5.png)

**Comment by QingWei-Li** [comment]
fixed in https://github.com/ElemeFE/element/pull/456
