### ISSUE TITLE
[Bug, Report], Some, forms, may, the, validation, while, there, skip, are, two, or,, more, forms, in, el-step

### ISSUE THREAD

**Issue by Tangchen2016** [ElemeFE/element#6890]
### Element UI version
1.4.4

### OS/Browsers version
chrome 60.0.3112.78（正式版本）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/552/](https://jsfiddle.net/pj71jkyw/552/)

### Steps to reproduce
while active is 1 in el-step, it shows the first form group. In this form group,  we just validate the second form.
Then active is 2, it shows the second form group. Just the second validtion of form works, it skip the validation in first form.

### What is Expected?
In the second form group, we expect the two validation can works.

### What is actually happening?
It just validate the second form and skip the first in the second form group.

**Comment by spx443812507** [comment]
use v-show

**Comment by Tangchen2016** [comment]
It works. Thank you very much.
