### ISSUE TITLE
[Bug Report] hides div in the table (tab switching scenario). When the height is added to the table, the width of the table is not adaptive, and a resize method is desired

### ISSUE THREAD

**Issue by WormGirl** [ElemeFE/element#6895]
### Element UI version
0.1.0

### OS/Browsers version
chrome最新

### Vue version
2.4.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
1

### What is Expected?
1

### What is actually happening?
1

![rtx](https://user-images.githubusercontent.com/16078260/30143599-4a24f15a-93b9-11e7-8fb2-c5da758b5476.png)
![388d53fd-9a37-4eaa-be7d-6507a6c41a75](https://user-images.githubusercontent.com/16078260/30143604-4daabe7c-93b9-11e7-9d75-56c2755abdd6.png)

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by xiaoxiaoxiaxia** [comment]
你好，也遇到了类似问题，你怎么解决的

**Comment by WormGirl** [comment]
深拷贝table值，触发table更新就会resize,但是如果有fixed最后一列会有滚动条被遮住的情况document.querySelectorAll(".el-table__fixed-right")[index].style.right = "17px";
document.querySelectorAll(".el-table__fixed-right-patch")[index].style.width = "17px";这样就可以了  
但这只能是hack，不能算解决方法，先这样，后面在提交个完整issue.

**Comment by xiaoxiaoxiaxia** [comment]
好的，多谢，我也试试。
