### ISSUE TITLE
穿梭框 :render-content="renderFunc 渲染不成功"

### ISSUE THREAD

**Issue by 942031216** [ElemeFE/element#6896]
![image](https://user-images.githubusercontent.com/30147760/30143996-2db1d9d2-93bb-11e7-8fd2-3e7b87c8094f.png)

from组件的 :render-content="renderFunc 渲染不成功"  官网上的事例也不成功

**Comment by 942031216** [comment]
谢谢

**Comment by outman0503** [comment]
我也遇到这个问题   element ui 穿梭框这个不知道是谁做的   简直是个坑   自定义渲染函数是个bug  添加的时候还自动排序   写这么烂  你不上传也行  用了之后  bug这么多   误导大众

**Comment by LakesCode** [comment]
```
renderFunc(h, option) {
  return h(
    'span', {
      domProps: {
        innerHTML: option.key + ' - ' +option.label
      },
    }
  )
}
```
