### ISSUE TITLE
[Bug Report], el-input, v-model.trim Chinese input, the first pinyin can not enter

### ISSUE THREAD

**Issue by weiweiwang** [ElemeFE/element#6897]
### Element UI version
1.4.4

### OS/Browsers version
win 7/chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/4rzb21fa/](https://jsfiddle.net/4rzb21fa/)

### Steps to reproduce
1. el-input v-model 绑定 .trim修饰符时，如果先输入空格再输入中文（拼音）空格确认，只有首字母会进去；再次输入才能正常输入
2. 添加原生input v-model.trim 作为对比，无上述问题
补充： 在不使用.trim修饰符时，如果el-input 绑定一change事件也能出现步骤1 里的问题，但只限于部分用户，我这边没能稳定复现

### What is Expected?
能通过拼音正常输入中文，至少与原生input行为保持一致

### What is actually happening?
任意中文输入法（试了百度、搜狗），输入空格、拼音‘nihao’，只有字符‘n’输入进去

**Comment by qingdengyue** [comment]
https://jsfiddle.net/4rzb21fa/ No reproduction~

**Comment by weiweiwang** [comment]
[el-input.mov.zip](https://github.com/ElemeFE/element/files/1286992/el-input.mov.zip)

试了4台不同型号的电脑都能稳定重现，附 mac上录制的视频，输入前记得先输入空格
