### ISSUE TITLE
 [Bug Report]dialog组件的transform会影响dialog中元素border

### ISSUE THREAD

**Issue by zctya** [ElemeFE/element#6899]
### Element UI version
1.4.4
### OS/Browsers version
win7
### Vue version
2.4.2
### Reproduction Link
[https://jsfiddle.net/87zd8uq5/](https://jsfiddle.net/87zd8uq5/)

### Steps to reproduce
div的border为1的时候，会受 transform 的影响，border-left和border-right比border-top、border-bottom要粗一些

![20170907114938](https://user-images.githubusercontent.com/10741844/30145355-5d840bc8-93c3-11e7-9bdb-da0d30554b2f.png)

### What is actually happening?
100%

**Comment by Leopoldthecoder** [comment]
在下一个大版本中，Dialog 的定位方式将不再使用 `transform`，这个问题就会得到解决。
