### ISSUE TITLE
[Bug Report] mobile UC browser is not compatible with element UI

### ISSUE THREAD

**Issue by hua2buxie** [ElemeFE/element#6903]
### Element UI version
1.4.4

### OS/Browsers version
UC手机浏览器 V11.6.6最新版

### Vue version
2.4.2

### Reproduction Link
[https://github.com/ElemeFE/element/issues/6902](https://github.com/ElemeFE/element/issues/6902)

### Steps to reproduce
在手机自带浏览器，QQ浏览器，QQ内置浏览器，微信内置浏览器都支持element ui，但是在UC里面，不能渲染出效果。比如顶部菜单栏，其他手机浏览器正常，但是UC渲染不出来

### What is Expected?
正常的菜单栏（我拷贝的elementui官网的demo）

### What is actually happening?
只有文字。其他什么都没得。

**Comment by Leopoldthecoder** [comment]
Element 仅适用于桌面端，请不要在移动端使用。
