### ISSUE TITLE
el-table-column 中width为computed时table的width会变得很大

### ISSUE THREAD

**Issue by Ge-Ge** [ElemeFE/element#6904]
`<el-table-column label="操作" align="left"  :width="width">`
当变量width变化，table的width就会变得很大
`<table cellspacing="0" cellpadding="0" border="0" class="el-table__header" style="width: 455400px;"></table>`

**Comment by PleaseTryAgain** [comment]
我也遇到这个问题了，你怎么解决的？ @Ge-Ge
