### ISSUE TITLE
[Bug Report] current-node-key ID is invalid at 0

### ISSUE THREAD

**Issue by scq000** [ElemeFE/element#6909]
### Element UI version
1.4.4

### OS/Browsers version
chrome 60

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/scq000/pen/eEaxza](https://codepen.io/scq000/pen/eEaxza)

### Steps to reproduce
想实现在默认渲染的时候就高亮某个节点。
代码像这样：
```
  <el-tree :data="data" :props="defaultProps" :current-node-key="0" node-key="id" highlight-current default-expand-all>
  </el-tree>
```

而需要默认高亮的节点是
```
{
    label: '全部分类',
    id: 0,
}
```

### What is Expected?
希望能处理一下这个特殊情况。

### What is actually happening?
没有高亮id为0的节点

**Comment by Leopoldthecoder** [comment]
Fixed in #6917
