### ISSUE TITLE
[Feature Request] "Transfer 穿梭框"右侧列表希望可以和 change 事件中的 value 数组, 顺序保持一致

### ISSUE THREAD

**Issue by llwslc** [ElemeFE/element#6910]
### Existing Component
是

### Component Name
Transfer 穿梭框

### Description
右侧列表的顺序总是和左侧列表的添加顺序一致, 希望可以提供参数, 使其按照左侧列表点击顺序, 就是 change 事件中的 value 数组顺序一致.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this.

**Comment by llwslc** [comment]
左侧饭店菜单, 右侧客户已点菜单, 已点菜的显示顺序和饭店菜单的顺序必须保持一致这样合适么...

**Comment by llwslc** [comment]
![image](https://user-images.githubusercontent.com/5865414/30197609-537c34e2-949b-11e7-9526-7da412dfd8d6.png)

value 代码赋值[3, 2, 1], 右侧列表显示 1, 2, 3... 这样不合适吧?

**Comment by outman0503** [comment]
我也遇到了这个问题,穿梭框的意义就在于能让用户自主选择顺序,但element ui里面的穿梭框选择到右边后之后就自动按照左边排序，和bug一样,,第一次见穿梭框自动排序的。当时做的时候没注意看,现在因为需求
都得改,希望element ui团队能重视一下这个问题

**Comment by Will233** [comment]
希望能改进一下这个功能

**Comment by 191824852** [comment]
有其他解决方案吗？

**Comment by Will233** [comment]
自己的解决方案，仅供参考
https://segmentfault.com/a/1190000012610355
