### ISSUE TITLE
请问怎样让example能够run起来

### ISSUE THREAD

**Issue by winnieBear** [ElemeFE/element#692]
按照文档指示`npm run bootstrap` ，可是script没有对应`bootstrap`的配置，怎样才能run起来？
还有那个layout，copy了示例的代码，可是没有看到效果，怎样设置才能看到效果？

总的来说，你们做了一件很棒的事情，但是，新手根本不知道怎么开始，满心欢喜的鼓捣半天，结果一个基本的demo都run不起来实在让人灰心。

**Comment by jikkai** [comment]
运行`npm run dev`

**Comment by Leopoldthecoder** [comment]
别灰心，上手文档即将更新 :)

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/blob/master/examples/docs/zh-cn/quickstart.md

文档已更新

**Comment by jerryyan1990** [comment]
@QingWei-Li **page not found**  hehe~

**Comment by Leopoldthecoder** [comment]
@jerryyan1990 直接看文档就行：http://element.eleme.io/#/zh-CN/component/quickstart 。另外上面的链接已经更新了。
