### ISSUE TITLE
[Feature Request] Select input with no over flow 

### ISSUE THREAD

**Issue by nathiboat** [ElemeFE/element#6922]
### Existing Component
Yes

### Component Name
el-select

### Description
Hi, 
refer to this image : http://prntscr.com/giaqcn
when multiple is add it allow us to have many value of selected  we may need limit the height of input or we have to disable el-select__tags-text. 
I also keen on if we can have some thing as same as when you do filter on table column components 

Regards

**Comment by Leopoldthecoder** [comment]
Something like this may help: https://jsfiddle.net/z9v9mooz/ .
