### ISSUE TITLE
[Bug Report] Table column width is not computed correctly when `scrollY` is false

### ISSUE THREAD

**Issue by reclay** [ElemeFE/element#6924]
### Element UI version
1.4.4

### OS/Browsers version
chrome 61

### Vue version
2.4.0

### Reproduction Link
[https://jsfiddle.net/m8ch4vhj/](https://jsfiddle.net/m8ch4vhj/)

### Steps to reproduce
This issue is caused by `table-layout.js` which did not take into account the situation of `scrollY`
![image](https://user-images.githubusercontent.com/14367118/30194836-2681ffe8-9488-11e7-804d-aaa14526f4d8.png)

### What is Expected?
    let totalFlexWidth = bodyWidth - bodyMinWidth;
    totalFlexWidth -= this.scrollY ? this.gutterWidth : 0;

### What is actually happening?
    const totalFlexWidth = bodyWidth - this.gutterWidth - bodyMinWidth;

**Comment by liril-net** [comment]
Fixed in [Carbon](https://github.com/ElemeFE/element/releases/tag/v2.0.0)
