### ISSUE TITLE
When [Bug, Report], INPUT components, or other forms components are disabled after disabled, does rule not automatically fail validation?

### ISSUE THREAD

**Issue by wangjl6** [ElemeFE/element#6927]
### Element UI version
1.4.4

### OS/Browsers version
谷歌

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
点击提交

### What is Expected?
1、INPUT组件或其他表单组件在disabled禁用后rule验证就不应该对已经禁用的组件生效，不然还得自己去设置空校验  很麻烦。

### What is actually happening?
1、禁用后的组件rule校验依然存在  必须手动去设置空校验
2、number的校验规则有bug   开头输入数字后再输入字母居然校验通过

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
