### ISSUE TITLE
[Bug Report] required validation bug, numeric types are considered null values of strings

### ISSUE THREAD

**Issue by maple-leaf** [ElemeFE/element#6930]
### Element UI version
1.4.4

### OS/Browsers version
Mac 版本 60.0.3112.113（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/maple-leaf/pen/oerpGO](https://codepen.io/maple-leaf/pen/oerpGO)

### Steps to reproduce
1，demo内点验证
2，输入值
3，再次点验证
4，number的验证除非再rule的required内写上类型`type: number`,否则一直required验证失败

### What is Expected?
number的required验证需要正常。因为rule还有专门的type验证，再required内有type的限制很奇怪。

### What is actually happening?
number的required验证一直失败。

**Comment by maple-leaf** [comment]
另关于rule的所有类型的文档不清晰。And there's not a clear document about rule.

**Comment by Leopoldthecoder** [comment]
这是 `async-validator` 的用法：https://github.com/yiminghe/async-validator#type

**Comment by maple-leaf** [comment]
但是我认为required对类型的验证和type两个规则重复且冲突了。改掉可能更好
