### ISSUE TITLE
[Bug Report] form digital checksum problem

### ISSUE THREAD

**Issue by ellisonLou** [ElemeFE/element#6933]
### Element UI version
1.4.3

### OS/Browsers version
chrome 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/nctoa90v/1/](https://jsfiddle.net/nctoa90v/1/)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/form
校验数字Bug

### What is Expected?
数字校验成功。

### What is actually happening?
校验数字，输入 123abc 可以通过， 只要前面带数字，就都能通过。

**Comment by Leopoldthecoder** [comment]
That's how Vue works: https://jsfiddle.net/nctoa90v/2/

**Comment by wycfcqt** [comment]
我的写法的确也是`<el-input v-model.number="age" auto-complete="off"></el-input>`，但是结果仍然和问题描述一致，[jsfiddle](https://jsfiddle.net/nctoa90v/6/)的写法也是如此，不过结果同样不正确@Leopoldthecoder
