### ISSUE TITLE
Can [Feature Request] add a parameter bomb to the iframe's parent window for Dialog?

### ISSUE THREAD

**Issue by deeplyloving** [ElemeFE/element#6936]
### Existing Component
是

### Component Name
el-dialog

### Description
能不能给Dialog添加一个参数   弹在 iframe的父窗口 
原因: 传统开发的时候 引入 vue.js element.js  可能用到iframe子页面的方式.    el-dialog弹框目前只针对当前dom    导致 遮罩层 无法全屏

**Comment by Leopoldthecoder** [comment]
We have no plan to support this.
