### ISSUE TITLE
text will be selected after click on switch

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#6938]
### Element UI version
1.4.4

### OS/Browsers version
windows10 Chrome70

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/jonkee/9cz5t7tc/1/](https://jsfiddle.net/jonkee/9cz5t7tc/1/)

### Steps to reproduce
1. click on the switcher
2. the text `ON` `OFF` will be highlighted after click

### What is Expected?
it should not be highlighted

**Comment by Leopoldthecoder** [comment]
You can add `user-select`: https://jsfiddle.net/9cz5t7tc/2/ . Note that this will cause a bug in certain browsers. That's why we didn't add this in Switch's style file.
