### ISSUE TITLE
autofocus totally not work in el-input

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#6939]
### Element UI version
1.4.4

### OS/Browsers version
windows10 Chrome70

### Vue version
2.4.2

### Reproduction Link
https://jsfiddle.net/jonkee/eukxnrum/](https://jsfiddle.net/jonkee/eukxnrum/)

### Steps to reproduce
1. move the cursor into the input
2. it will not auto focus

### What is Expected?
auto focus

**Comment by Leopoldthecoder** [comment]
`autofocus` means that the element should be automatically focused after the page loaded. It has nothing to do with cursor moving into the input.
