### ISSUE TITLE
[Bug Report] tooltip mouseenter event overlay

### ISSUE THREAD

**Issue by jxnuGBk** [ElemeFE/element#6943]
### Element UI version
1.4.4

### OS/Browsers version
win7/chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/o71z5fx1/](https://jsfiddle.net/o71z5fx1/)

### Steps to reproduce
https://jsfiddle.net/o71z5fx1/

### What is Expected?
每次render不必要叠加事件

### What is actually happening?
每次render事件都被添加到数组中了

**Comment by Leopoldthecoder** [comment]
Fixed in #6972
