### ISSUE TITLE
[Bug Report] Radio Group size, fill and text-color attributes not working

### ISSUE THREAD

**Issue by valuppo** [ElemeFE/element#6946]
### Element UI version
1.4.4

### OS/Browsers version
Ubuntu 16.04 / Google Chrome Version 58.0.3029.110 (64-bit)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/ub0fx7ky/1/](https://jsfiddle.net/ub0fx7ky/1/)

### Steps to reproduce
just add size="small" text-color="#000000" fill="#000000" attributes to el-radio-group element

### What is Expected?
radio button inside radio group become smaller and fill and text color should be black

### What is actually happening?
nothing happened

**Comment by Leopoldthecoder** [comment]
These two attributes only affect RadioButtons: https://jsfiddle.net/ub0fx7ky/2/
