### ISSUE TITLE
[Bug Report] DatePicker changes V-model to trigger component display

### ISSUE THREAD

**Issue by DanielWLam** [ElemeFE/element#6948]
### Element UI version
1.4.4

### OS/Browsers version
win10， chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/xj80vxsr/](https://jsfiddle.net/xj80vxsr/)

### Steps to reproduce
1、点击日期组件
2、点击按钮

### What is Expected?
点击按钮不会触发日期组件出现，而是直接改变v-model的值

### What is actually happening?
修改v-model导致picker出现

**Comment by wmada** [comment]
I hava met the same question. 
I tried a lot and found that when clicking out site, `handleClose` function worked but the input component status is still 'focused'. When I change the value of the V-model, the watcher of value in date-range.vue will work and show the pickerpanel.
I add a variable and bind a click.native event on the input element to fix this, but it's actually a temporary solution.

**Comment by wacky6** [comment]
Fixed in 2.0, Closing this issue.
