### ISSUE TITLE
[Feature Request] in tree components, no setDisabled event existl

### ISSUE THREAD

**Issue by believeZJP** [ElemeFE/element#6950]
### Existing Component
Yes

### Component Name
tree

### Description
 when I want to click a node ,then set the children disabled,
but there is no setDisabled event to use.
Looking forward to your help~~

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/wbccyxy5/

**Comment by believeZJP** [comment]
I change the event to check-change, sometimes the first node can't be selected. 

https://jsfiddle.net/wbccyxy5/1/
