### ISSUE TITLE
How does the [Feature Request] TimePicker selector select the 22:00 - 02:00 time?

### ISSUE THREAD

**Issue by wardenGfs** [ElemeFE/element#6952]
### Existing Component
是

### Component Name
TimePicker

### Description
在选择商家运营时间的时候，会有这样的场景，比如一些夜宵店烧烤店，他们的运营时间是晚上10点到凌晨2点，这样的时间段使用TimePicker组件不被允许选择

**Comment by Leopoldthecoder** [comment]
这种场景适合使用 `el-time-select`（文档中的第三个例子）
