### ISSUE TITLE
[Bug Report] Tree in lazy mode, set child node 'default-checked-keys', display wrong

### ISSUE THREAD

**Issue by AloVulpix** [ElemeFE/element#6953]
### Element UI version
1.4.1

### OS/Browsers version
Chrome 57.0.2987.98 (64-bit)

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/png26am9/9/](https://jsfiddle.net/png26am9/9/)

### Steps to reproduce
1. tree data is : [{
          id: 1,
          label: '1st 1',
          children: [{
            id: 4,
            label: '2nd 1-1',
            children: [{
              id: 9,
              label: '3rd 1-1-1'
            }, {
              id: 10,
              label: '3rd 1-1-2'
            }]
          }]
        }, {
          id: 2,
          label: '1st 2',
          children: [{
            id: 5,
            label: '2nd 2-1'
          }, {
            id: 6,
            label: '2nd 2-2'
          }]
        }]

and set :default-checked-keys="[6, 4]"

2. then expand node

### What is Expected?
I set 'default-checked-keys=[6, 9]', so the expected result is: 
1. Parent nodes are not partial selection after component initial
2. After expand '1st 1' and '2nd 1-1', all parent node selected. (The expected display is only '3rd 1-1-1' selected, '1st 1' and '2nd 1-1' partial selection)
3. After expand '1st 2', parent node don't show reaction, and expand '2nd 2-1', it's correct.

### What is actually happening?
1. Parent nodes should be partial selection after component initial  
2. After expand parent node, both parent node and child node should display in expection
3. After expand parent node, both parent node and child node should display in expection

**Comment by itimor** [comment]
我也遇到了，显示是错误的，或是没有效果

**Comment by Leopoldthecoder** [comment]
The expected behavior No.2 and No.3 are fulfilled in 2.2.0: https://jsfiddle.net/leopoldthecuber/ms2mak5d/3/

For behavior No.1, since you are passing the complete data to the component, what's the purpose of turning on the `lazy` mode?

**Comment by ziyoung** [comment]
User Elememt v2.
