### ISSUE TITLE
[Feature, Request], table selection and expand can't set render-header

### ISSUE THREAD

**Issue by Oscar-ren** [ElemeFE/element#6956]
### Existing Component
是

### Component Name
table

### Description
when to use table component and set the table-column type as 'selection' or 'expand', the render-header event will non't be execute.
sometime i wan't to change the selection header, such as "all select" other than the select box.

**Comment by Leopoldthecoder** [comment]
Using `render-header` means you'll have to take care of all the interactions yourself.
