### ISSUE TITLE
[Feature Request] How can I update node name?

### ISSUE THREAD

**Issue by kseni22** [ElemeFE/element#6964]
### Existing Component
Yes

### Component Name
el-tree

### Description
Hi!
If I want to append or remove node I can use self-named tree function. But if I want to update node name, for example, what should I do?

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
