### ISSUE TITLE
el-col layout breakpoints different than bootstrap breakpoints

### ISSUE THREAD

**Issue by akoutmos** [ElemeFE/element#6967]
The docs say that the layout breakpoints mirror bootstraps. But for xs it doesn't appear to do so.

When doing something like <el-col :xs="{span: 18, offset: 3}">, the media query max-width for element-ui is 768px while max-width for bootstrap is 767px

https://github.com/ElemeFE/element/blob/24cd59ff7f6a90eeab1b1dfb0af880f6251b8a50/packages/theme-default/src/col.css#L29

https://github.com/twbs/bootstrap/blob/v3-dev/dist/css/bootstrap.css#L6570

**Comment by rtheunissen** [comment]
It would be nice to now what the outcome was here @element-bot and @akoutmos. Are they supposed to be the same, and they aren't? We currently can't use bootstrap grid and element layout at the same time because they break at different widths.

**Comment by vgavro** [comment]
I guess this is related, https://github.com/ElemeFE/element/issues/10180
if you translate from chinese what @Leopoldthecoder said:
"Element does not support mobile devices, so screens that are smaller than 768 pixels are not an Element's fit.". That's sad, but I guess this is official element-ui developers answer. I'm sure it should be documented in Layout chapter.

**Comment by Leopoldthecoder** [comment]
The breakpoints are SCSS variables, so they can be reset to whatever value you see fit.

**Comment by akoutmos** [comment]
I've worked around the breakpoint miss-match by doing just as you mentioned @Leopoldthecoder. My question was more which is correct, the code or the documentation? If the code is correct, the then docs should be updated as the breakpoints don't mirror Bootstrap's breakpoints exactly. If the docs are correct then the code should be fixed.

**Comment by wldrve** [comment]
> The breakpoints are SCSS variables, so they can be reset to whatever value you see fit.

I'm using LESS in multiple instances where I also use Element Plus. Is it possible to change the breakpoints with LESS or simply with css in :root? Thanks!
