### ISSUE TITLE
[Bug Report] NavMenu cannot be turned off

### ISSUE THREAD

**Issue by momodexuyuan** [ElemeFE/element#6971]
### Element UI version
2.4.2

### OS/Browsers version
ios9/safari和微信浏览器

### Vue version
v2.3.4

### Reproduction Link
[https://jsfiddle.net/momodexuyuan/90h0Low3/](https://jsfiddle.net/momodexuyuan/90h0Low3/)

### Steps to reproduce
navMenu组件，当menu-trigger设置为hover，点开后，ios9/10的浏览器下都无法都关闭下拉菜单。

### What is Expected?
点击任何空白处能关闭。

### What is actually happening?
无法关闭

**Comment by Leopoldthecoder** [comment]
Element 仅支持桌面端浏览器，请勿用在移动端。
