### ISSUE TITLE
[Bug Report] the modal is over(& above) the dialog when use the flexbox layout

### ISSUE THREAD

**Issue by qidaneix** [ElemeFE/element#6974]
### Element UI version
1.4.4

### OS/Browsers version
windows 7/google chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/xiaodabao/pj71jkyw/560/](https://jsfiddle.net/xiaodabao/pj71jkyw/560/)

### Steps to reproduce
click the button "show dialog"

### What is Expected?
the modal is under the dialog

### What is actually happening?
the modal is over(& above) the dialog

**Comment by Leopoldthecoder** [comment]
This is because the Dialog is nested in a container with `z-index` equals to `1`. Either remove `z-index: 1` of the container, or wait for Element's next major version in which Dialog has a new attribute `append-to-body` that appends the Dialog element directly to `body`.

**Comment by qidaneix** [comment]
May I ask when the next major version of Element come? @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
We don't have a release date yet, but we're hoping to get it done in a month or so.
