### ISSUE TITLE
[Bug, Report], el-dropdown, doesn't, work, on, mobile, browsers

### ISSUE THREAD

**Issue by aleksejevski** [ElemeFE/element#6975]
### Element UI version
1.4.4

### OS/Browsers version
Android 7.1.1

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/69co9wy9/](https://jsfiddle.net/69co9wy9/)

### Steps to reproduce
Click a el-dropdown to open the drop-down menu on a mobile device.

在移动设备上点开 el-dropdown 来打开菜单

### What is Expected?
It works just like on PC.

行为应该与PC端一样

### What is actually happening?
el-dropdown never works on Android's default browser. A smartisan, a OnePlus and a Huawei Honor phone was tested.
However, on Chrome, it works when and only when setting trigger as 'click'. It neither works when the trigger is 'hover'.

el-dropdown 在 Android 的默认浏览器无法工作，已经试过一台锤子、1 和华为荣耀，都不行。
然而，在 Chrome 里，把 trigger 设置为 “click” 的时候就可以正确打开菜单了，但在“hover”的时候仍然没有响应。

**Comment by Leopoldthecoder** [comment]
Element 仅支持桌面端，请勿在移动端使用。
