### ISSUE TITLE
[Feature, Request], When, to, support, Vue, 2.4.x

### ISSUE THREAD

**Issue by Oscar-ren** [ElemeFE/element#6976]
### Existing Component
否

### Component Name
no

### Description
I wan't to use the vue 2.4.x syntax on element component.

But I see the element@1.4.4 dependencies vue@2.3.0.

thanks.

**Comment by Leopoldthecoder** [comment]
You can use Vue 2.4.x syntax.

**Comment by Oscar-ren** [comment]
sorry, i use the `v-on={}` syntax in the table component , but didn't take effect.

you can see: https://jsfiddle.net/2yevmqwj/
when i select the checkbox, the`handleSelectionChange` function doesn't execute.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/2yevmqwj/1/

**Comment by Oscar-ren** [comment]
oh, my mistake, thanks very much.
