### ISSUE TITLE
[Feature Request] Does Element have a plan to develop an Angular version?

### ISSUE THREAD

**Issue by baiyunchen** [ElemeFE/element#6979]
### Existing Component
No

### Component Name
Angular

### Description
Element is the perfect control I've ever seen. But unfortunately, he did not have an angular version, do not know if there are plans to develop angualr version?

**Comment by Leopoldthecoder** [comment]
https://github.com/eleme/element-angular I think this is still in an early stage, you can watch this repo to get latest news.
