### ISSUE TITLE
[Bug Report] form validation (custom or writing rules) does not take effect

### ISSUE THREAD

**Issue by wycfcqt** [ElemeFE/element#6986]
### Element UI version
1.4.4

### OS/Browsers version
windows7 旗舰版 sp1/google chrome 59.0.3071.115 (正式版本) （64 位）

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/nw13ozq1/](https://jsfiddle.net/nw13ozq1/)

### Steps to reproduce
1. 表单元素数字类型验证，通过写自定义函数验证

2. 输入纯数字能通过验证（例如：`22`），再次输入非数字（例如：`22aab`），同样通过了验证

### What is Expected?
能对数字类型做出全面的正确验证，例如：`22aab`应该验证不通过

### What is actually happening?
对`22aab`做出了错误的验证，即验证被通过了

**Comment by Leopoldthecoder** [comment]
#6933

**Comment by wycfcqt** [comment]
我的写法的确也是`<el-input v-model.number="age" auto-complete="off"></el-input>`，但是结果仍然和问题描述一致，[jsfiddle](https://jsfiddle.net/nctoa90v/6/)的写法也是如此，不过结果同样不正确@Leopoldthecoder
