### ISSUE TITLE
[Bug Report] check-change add set children disabled . It not worked 

### ISSUE THREAD

**Issue by believeZJP** [ElemeFE/element#6987]
### Element UI version
1.4.4

### OS/Browsers version
any

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/wbccyxy5/5/](https://jsfiddle.net/wbccyxy5/5/)

### Steps to reproduce
details in the link.

# the first node can't be checked,
 and the children can't be set disabled.

According to the console.log info ,the check-change event triggered twice.

It seems like the set method triggered check-change event.

How can I disable checkbox in the check-change event?

### What is Expected?
check the first node, and children node set disabled.

### What is actually happening?
check the first node, and children node can't set disabled.

**Comment by furybean** [comment]
例子实现有问题，没有判断 data.children 是否为空，更新后的例子如下：https://jsfiddle.net/wbccyxy5/6/
