### ISSUE TITLE
[Bug, Report], Transfer, incompatible, with, el-form-item

### ISSUE THREAD

**Issue by ssshooter** [ElemeFE/element#6988]
### Element UI version
1.4.4

### OS/Browsers version
Chrome

### Vue version
2.4.2

### Reproduction Link
`
<el-form-item label="角色权限">
        <el-transfer filterable :titles="['待添加权限','已添加权限']" v-model="addedPermission" :data="templateData">
        </el-transfer>
</el-form-item>
`

### What is Expected?
![image](https://user-images.githubusercontent.com/13051472/30358909-0b2e8fea-987a-11e7-9a60-bd5f72fdfefc.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/13051472/30358916-16380c2c-987a-11e7-95d5-46b69e2507bd.png)

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
