### ISSUE TITLE
The [Feature Request] Table table sets the row height and the upper and lower margins of each row

### ISSUE THREAD

**Issue by lmxiels** [ElemeFE/element#6997]
### Existing Component
Yes

### Component Name
Table

### Description
Table表格,每一行的行高和上下边距设置问题，在编辑器中设置成功，代码移动到工程中无效

.mytable td ,.mytable th {
height:15px !important;
font-size:10px;
font-bold:normal;
line-height:normal;
}

.mytable th .cell{
font-weight:normal;
background-color:red;
}

在实际的代码中无法生效，官方能不能提供一下设置列表每行高度的方法，还有单元格内的上下左右边距。

What is Expected?

希望能不能有官方提供的一些写法，能够比较有效的应用于表格行高和cell单元格大小设置，网络上暂时没有找到有效的方式

What is actually happening?

现在上述代码在测试连接测试正常，到实际项目中无法生效。所以能提高官方的设置样式的方法不。

**Comment by Leopoldthecoder** [comment]
看下样式有没有被覆盖吧。没有什么统一的方法，自己写 CSS 覆盖就行。
