### ISSUE TITLE
[Bug Report] MessageBox will not automatically turn off after routing

### ISSUE THREAD

**Issue by 1165506270** [ElemeFE/element#6999]
### Element UI version
1.4.4

### OS/Browsers version
Windows10 / Google Chrome 60.0.3112.78

### Vue version
2.4.3

### Reproduction Link
http://element.eleme.io/#/zh-CN/component/message-box

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/message-box 在该页面浏览其他组件页面，到MessageBox页面打开一个MessageBox，后按浏览器的后退，该MessageBox不会被关闭

### What is Expected?
MessageBox会被关闭

### What is actually happening?
MessageBox不会被关闭

**Comment by Leopoldthecoder** [comment]
下个大版本中会加入 `closeOnHashChange` 属性。

**Comment by yoyo837** [comment]
@Leopoldthecoder 想确认一下，在下个大版本中加入closeOnHashChange是指2.x吗？1.x并不修复此问题是吧？
Thanks！

**Comment by Leopoldthecoder** [comment]
@yoyo837 是的
