### ISSUE TITLE
select支持自行输入的内容

### ISSUE THREAD

**Issue by wsyWeb** [ElemeFE/element#700]

**Comment by jikkai** [comment]
能否详细描述下问题？

**Comment by wsyWeb** [comment]
就是select可以支持我自己输入的内容，即使select下拉框中没有；然后我发现一个BUG，多选多了之后，样式有问题
![image](https://cloud.githubusercontent.com/assets/17327031/19803313/85e5ca14-9d3a-11e6-9682-2395a12f707f.png)

**Comment by wsyWeb** [comment]
还有弹出窗口模糊问题

![image](https://cloud.githubusercontent.com/assets/17327031/19803553/fbfaac50-9d3b-11e6-9950-812c96ec1a62.png)
因为有个transform3d的属性，现在我的解决方法是把弹窗的高度写死了，希望你们能有更好的解决方法，谢谢

**Comment by Leopoldthecoder** [comment]
1、Select 支持自行输入的内容，后面会考虑；
2、多选多了之后样式的问题请给出在线 demo；
3、弹出窗口模糊的问题已修复，请升级至 rc.8。

**Comment by Leopoldthecoder** [comment]
第一个问题 #782 再次提出，先关闭这个 issue 了。
