### ISSUE TITLE
[Feature Request] Carousel: when the lantern is 2 pages, jump from 2 to 1 the animation is reversed to jump over, can be changed to normal?

### ISSUE THREAD

**Issue by th720309** [ElemeFE/element#7001]
### Existing Component
Yes

### Component Name
Carousel 走马灯

### Description
Carousel 走马灯：当页数为2时，跳转动画从2到1是倒着跳过去的，可以改成正常的吗？

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
