### ISSUE TITLE
[Feature, Request], Select, a, row, in, a, table,, and, delete, it

### ISSUE THREAD

**Issue by stevobm** [ElemeFE/element#7002]
### Existing Component
是

### Component Name
Table

### Description
Sometimes we wish to select a row in a table and delete it, but it seems to be difficult to do this in Element UI. 

We tried to find a method or event that could give us the index of the selected row in table, but we only got the content of the row(an object) instead, which did little help for us to delete it. 

So, could Element UI provide the index of the selected row as a parameter of the methods or callbacks(e.g, current-change, selection-change)?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ezhr8jyx/
