### ISSUE TITLE
[Feature Request] Stacked Progressbar

### ISSUE THREAD

**Issue by sudo-shubham** [ElemeFE/element#7004]
### Existing Component
Yes

### Component Name
Progress

### Description
Multiple stacks of progress in single bar.

Such as https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_progressbar6&stacked=h.

**Comment by Leopoldthecoder** [comment]
We have no plan to add this.

**Comment by mschlitz-trux** [comment]
Are there any plans to reconsider this feature request? It's a shame it is not supported.

**Comment by Drumstix42** [comment]
Are there any plans to reconsider this feature request? It's a shame it is not supported.
