### ISSUE TITLE
[Bug Report] Transfer set style dislocation

### ISSUE THREAD

**Issue by feverdestiny** [ElemeFE/element#7008]
### Element UI version
1.4.4

### OS/Browsers version
win7 64x  Chrome 60.0.3112.113

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/feverDestiny/xm1gkt1v/](https://jsfiddle.net/feverDestiny/xm1gkt1v/)

### Steps to reproduce
当Transfer或者在外部容器设置style="text-align:center"时。Transfer居中严重变形

### What is Expected?
Transfer居中后应显示完整信息，而不会压缩内容信息
如Tree组件https://jsfiddle.net/feverDestiny/3qdqpbLf/

### What is actually happening?
Transfer居中后显示文本信息严重变形

**Comment by Leopoldthecoder** [comment]
设置 `style="text-align:center"` 希望达到的效果是让 Transfer 整体在其容器中居中吗？如果不是，具体期望哪些元素居中？

**Comment by feverdestiny** [comment]
@Leopoldthecoder 是的，外部设置样式控制不用考虑。只要处理好Transfer组件内的正常居中就好

**Comment by Leopoldthecoder** [comment]
Transfer 组件内的正常居中是指什么？
如果是要 Transfer 整体在其容器中居中，那么是可以做到的；如果是要各个选项在面板中居中，那么是不支持的。

**Comment by feverdestiny** [comment]
@Leopoldthecoder 如果内部无法实现居中也可以 ，只要外部能通过text-align设置居中显示正常，具体效果如https://jsfiddle.net/feverDestiny/xm1gkt1v/1/，我通过使用固定width和margin：0 auto实现。理论上tex-align:center实现效果应该如案列显示效果相同

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/xm1gkt1v/2/
