### ISSUE TITLE
[Bug Report] DateTimePicker manual input date interactive recommendations

### ISSUE THREAD

**Issue by jzz4012650** [ElemeFE/element#7010]
### Element UI version
1.4.1

### OS/Browsers version
macOS Sierra 10.12.6 (16G29) ／ Chrome 60.0.3112.113

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/562/](https://jsfiddle.net/pj71jkyw/562/)

### Steps to reproduce
1. 点击输入框，弹出日期时间范围选择器
2. 在起始“Date”输入框输入2017-08-03
3. 点击或按tab使焦点移到右边的起始“Time”输入框
4. 刚才输入的起始“Date”立马变成了当前日期，同时起始与结束输入框都被填入当前日期跟时间

### What is Expected?
两种可接受的结果：
1. 焦点聚焦到第一个“Date”输入框时就填入当前日期与时间，而不是要聚焦到第二个”Time“输入框时才触发
2. 聚焦到第二个”Time“输入框时能保持刚才输入的日期，除非输入的日期格式有误

### What is actually happening?
见上述第4步

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0
