### ISSUE TITLE
[Feature Request] More info and details on Validation

### ISSUE THREAD

**Issue by dobromir-hristov** [ElemeFE/element#7012]
### Existing Component
No

### Component Name
Form Inputs

### Description
Is there a sane way to use another validation plugin, like Vuelidate for example, while still showing error messages and so on to Inputs?
I am asking because I couldnt find an easy way to check if a certain field is passing a certain rule.

If this can be done with the integrated Async-validator, please tell me. Also properties like `touched`, `dirty` etc are not present as well.

**Comment by tomhuntley** [comment]
It would be great if element could include similar functions to vuelidate (or maybe integrate it). Here's my solution to getting vuelidate work with Element if you are having issues. 

Set up your vuelidate operations as normal:

```
validations: {
      user: {
        email: {
          email,
          required
        }
      }
    },
```

Create a computed property (not really necessary but I think this makes it a bit clearer):

```
computed: {
      validEmail (){
        return this.$v.user.email.email === true && this.$v.user.email.required === true;
      }
    },
```

Then as per the docs, add a custom validator, making sure to add the functions into the data property:

```
data () {
      var validateEmail = (rule, value, callback) => {
        if (!this.validEmail){
          callback(new Error("Please enter a valid email."))
        } else {
          callback()
        }
      };
      return {
        rules: {
          email: [
            {
              validator: validateEmail, trigger: 'blur'
            }
          ]
        }
      }
    }
```

**Comment by dobromir-hristov** [comment]
After the form field I would go insane hah, This is too much boilerplate.

**Comment by tomhuntley** [comment]
Yeah it's definitely not pretty :) - a proper integration with vuelidate would be really useful.

**Comment by bdeo** [comment]
I agree. This is something necessary. This needs better validation or a way to natively integrate with Vuelidate.

**Comment by caraffa** [comment]
As of today, for me current async_validator functionality is quite decent. What IMO is really missing is the presence of $dirty, $pristine and $valid flags in forms/forms-items like in vuelidate.
In my opinion this would be a most wanted feature (Or may be there's a way to achieve that that I'm not aware of?)
