### ISSUE TITLE
[Bug Report] Why remove the files immediately after uploading unsuccessfully

### ISSUE THREAD

**Issue by Lutreer** [ElemeFE/element#7013]
### Element UI version
1.4.4

### OS/Browsers version
any

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/563/](https://jsfiddle.net/pj71jkyw/563/)

### Steps to reproduce
为了模拟上传失败，写了个假的url，选择文件后点击长传，上传失败的文件直接被移除文件列表了。
The action url is useless， so it will be failing，but the file was removed after failing.

### What is Expected?
保留上传失败的文件

### What is actually happening?
上传失败的文件直接被移除文件列表

**Comment by Leopoldthecoder** [comment]
上传成功的文件才会出现在文件列表中。

**Comment by Lutreer** [comment]
怎么把上传失败的留下

**Comment by Leopoldthecoder** [comment]
不支持。

**Comment by Lutreer** [comment]
6得很
