### ISSUE TITLE
If the [Bug Report] input component does not bind model, the value cannot be reached with ref

### ISSUE THREAD

**Issue by pod4g** [ElemeFE/element#7015]
### Element UI version
1.4.4

### OS/Browsers version
macOS sierra 10.12.6

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/ss3r0bfo/](https://jsfiddle.net/ss3r0bfo/)

### Steps to reproduce
没有绑定`v-model`的`input`组件，动态绑定`ref`值，假设指定为`input`，然后在输入框中填写任意值，然后使用`this.$ref.input.value`取值，取到的值为`undefined`

### What is Expected?
即使没有绑定`v-model`，使用dom操作也应该能取到`input`组件的`value`值

### What is actually happening?
没有取到`input`组件的`value`值

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ss3r0bfo/1/

**Comment by pod4g** [comment]
@Leopoldthecoder 好的，谢谢了。感觉是比较trick的解决方案（出现了丑陋的原生dom方法）。。希望能修复这个问题。
