### ISSUE TITLE
The [Feature Request] button disables the tooltip component and the dialog component is disabled by force

### ISSUE THREAD

**Issue by icuke** [ElemeFE/element#7016]
### Existing Component
Yes

### Component Name
tooltip, dialog, button

### Description
按钮禁用状态下,tooltip 组件与dialog 组件强制 disabled , 无法显示信息

**Comment by Leopoldthecoder** [comment]
这个只能通过外面加一层元素来解决：https://jsfiddle.net/hwrgpnmg/，disabled 的按钮在 Chrome 里就是不响应 mouse 事件的：https://jsfiddle.net/adw8jab9/ ，但是在 Firefox 下可以响应。
