### ISSUE TITLE
There is a problem with dynamic binding for [Bug Report] el-checkbox

### ISSUE THREAD

**Issue by MissCuriosity** [ElemeFE/element#7020]
### Element UI version
1.4.4

### OS/Browsers version
windows，谷歌

### Vue version
2.4.3

### Reproduction Link
[ https://jsfiddle.net/MissCuriosity/dt23e6qo/]( https://jsfiddle.net/MissCuriosity/dt23e6qo/)

### Steps to reproduce
选中1，再选中2，取消选中2，在点击1，此时会发现checkbox仍然为选中状态

### What is Expected?
选中状态即选中，非选中状态即非选中

### What is actually happening?
checkbox选中状态错误

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/dt23e6qo/1/
