### ISSUE TITLE
[Feature Request] el-select data changes, the selected value remains unchanged

### ISSUE THREAD

**Issue by duchaopaopao** [ElemeFE/element#7021]
### Existing Component
是

### Component Name
el-select

### Description
场景为当前el-select的数据因为联动而改变后，其选中值没有变化，难道当前选中值不应该清空吗？或者是我没有找到方法？

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by jeffmobiles** [comment]
这个issues关闭的太不负责了吧。 
场景: 一个业务数据，数组形式， list = [ {a:2,b:'day',c:'day',d:'rate'} ....] 这样的数组形式。
用table展示, b,c,d都是el-select来绑定,  b 和c 是联动的, 
 b 可选范围:[ 'day','year','month'....]  , c和b的可选范围是一样的，只不过label不一样, value一样. 

加上在list 某 index, 上,即table 某一行上,   选择 b的select 控件下拉框，根本就触发不了change事件.

这个select控件不支持 更新list某index上的某个数据的话， 为什么直接关掉这个issue呢。
