### ISSUE TITLE
[Bug Report] el-select boolean invalid prop

### ISSUE THREAD

**Issue by Phillys** [ElemeFE/element#7024]
### Element UI version
1.4.4

### OS/Browsers version
Chrome 60.0

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/566/](https://jsfiddle.net/pj71jkyw/566/)

### Steps to reproduce
Use a boolean as the value for el-option in el-select.

### What is Expected?
No invalid prop warning.

### What is actually happening?
This throws an invalid prop warning in the console since el-select depends on el-input to show the label. El-input wants a String or Number as the value.

```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, Number, got Boolean.

found in

---> <ElInput>
       <ElSelect>
         <Root>
```

**Comment by Leopoldthecoder** [comment]
Fixed in #7030
