### ISSUE TITLE
The [Bug Report] DateTimePicker date time picker time selection cancel function does not cancel

### ISSUE THREAD

**Issue by fujunchun** [ElemeFE/element#7025]
### Element UI version
1.4.4

### OS/Browsers version
win10 / chrome 60

### Vue version
2.4.3

### Reproduction Link
[datetime-picker](http://element.eleme.io/#/zh-CN/component/datetime-picker)

### Steps to reproduce
1. 点开DateTimePicker 日期时间选择器
2. 滑动时间 08:00:00，点击确定
3. 滑动时间 09:00:00 点击取消

### What is Expected?
点击取消后时间为 08:00:00

### What is actually happening?
时间为 09:00:00
取消无效，功能同确定

**Comment by fujunchun** [comment]
![element-issue](https://user-images.githubusercontent.com/8685450/30422907-dd61837e-9973-11e7-943f-155624f18af7.png)

**Comment by Leopoldthecoder** [comment]
Fixed in #7028
