### ISSUE TITLE
[Feature, Request], table, cell-click, how, to, get, the, $index, cell

### ISSUE THREAD

**Issue by Oscar-ren** [ElemeFE/element#7031]
### Existing Component
是

### Component Name
table

### Description
how can i get the index of the click cell.
```javascript
@cell-click (row, column, cell, event)
```
how about add $index or scope param for cell-click

thanks

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/smfcyd9e/

**Comment by pavinthan** [comment]
@Leopoldthecoder It's give rowIndex, how can we get call index

**Comment by letsbug** [comment]
> https://jsfiddle.net/smfcyd9e/

This method only get the location of metadata, can not get the sorted node location!

**Comment by chaserstrong** [comment]
> https://jsfiddle.net/smfcyd9e/

Can you show me the code. I can't get the page.
