### ISSUE TITLE
When [Bug Report] el-select is called out by extends, it will be wrong in firefox.

### ISSUE THREAD

**Issue by wuchuguang** [ElemeFE/element#7034]
### Element UI version
1.4.4

### OS/Browsers version
linux/firefox5.5

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/mznk94kf/](https://jsfiddle.net/mznk94kf/)

### Steps to reproduce
用element-ui npm install 方式的会报错。但用jsfiddle不会报错。报错。

callback for watcher "options"  app.js%20line%202003%20%3E%20eval:84:5
errorHandler: TypeError: this.cb.call is not a function
导致无法选中。

### What is Expected?
期待回应可能出现问题点。

### What is actually happening?
谢谢

**Comment by Leopoldthecoder** [comment]
请把出现问题的项目精简一下放到 GitHub 上来。
