### ISSUE TITLE
[Bug Report] field's order effect  is not attained in el-table-column

### ISSUE THREAD

**Issue by otherlite** [ElemeFE/element#7035]
### Element UI version
1.4.4

### OS/Browsers version
mac 10.12.6 / chrome 60.0.3112.113(64)

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/zx1p4sxf/3/](https://jsfiddle.net/zx1p4sxf/3/)

### Steps to reproduce
click 'reverse' button

### What is Expected?
the field 'date' and 'name' are going to trade position

### What is actually happening?
position as before

**Comment by Leopoldthecoder** [comment]
In this case, `el-table-column` needs to be keyed: https://jsfiddle.net/zx1p4sxf/4/
