### ISSUE TITLE
[Bug Report] Unexpected Token Operator emitter.js 

### ISSUE THREAD

**Issue by jpkontreras** [ElemeFE/element#7036]
### Element UI version
1.4.4

### OS/Browsers version
WIN 10 / CHROME 

### Vue version
2.4.4

### Reproduction Link
[jsfiddle.net](jsfiddle.net)

### Steps to reproduce
cant be reproduced on fiddles

### What is Expected?
To build

### What is actually happening?
Not building : Unexpected token: operator (>) [./node_modules/element-ui/src/mixins/emitter.js:2,0][\js\app.js:84441,32]

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly. A reproduction link can be a GitHub repo.

**Comment by jpkontreras** [comment]
@ryan-kite 
For what i remember you should not import single components to your files.. You have to import the whole library

**Comment by bigcui** [comment]
{
                test: /\.js$/,
                loader: 'babel-loader',
                include: [ resolve('src'),
                    resolve('node_modules/iview/src/'), resolve('test')]
            }
