### ISSUE TITLE
[Bug Report] Popover does not show in table

### ISSUE THREAD

**Issue by Darkbish** [ElemeFE/element#7038]
### Element UI version
1.4.4

### OS/Browsers version
win 10 build 1703 / chrome 60.0.3112.113

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/zhmkgj0q/](https://jsfiddle.net/zhmkgj0q/)

### Steps to reproduce
The popover shows when I comment the code

> 
```
<template slot="operate" scope="item">
  <el-popover placement="top" trigger="click" v-model="visible[item.row.id]">
    <p>Do you sure to delete this item ?</p>
    <el-button size="mini" type="danger" slot="reference">delete</el-button>
  </el-popover>
</template>
```
popover shows, jsfiddle [https://jsfiddle.net/zhmkgj0q/1/](https://jsfiddle.net/zhmkgj0q/1/)

I'm not sure this is a bug of Element-UI or scope slot cause this problem. There's someone help me to solve this problem ? Thanks.

### What is Expected?
The popover in el-table-column scoped slot should show when v-model changed.

### What is actually happening?
The popover does not show.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/zhmkgj0q/2/

**Comment by Darkbish** [comment]
@Leopoldthecoder Can you tell me which place you edited, thx?

**Comment by Leopoldthecoder** [comment]
I removed `v-model`

**Comment by chenyiqiao** [comment]
@Leopoldthecoder  You cannot control the visibility of popover without v-model.
