### ISSUE TITLE
[Bug Report] tree components, in individual cases, check for logical errors

### ISSUE THREAD

**Issue by languanghao** [ElemeFE/element#7040]
### Element UI version
1.4.4

### OS/Browsers version
Chrome 59

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/L3mm88q3/1/](https://jsfiddle.net/L3mm88q3/1/)

### Steps to reproduce
点击 “一级2” 节点，可以正常勾选所有子节点，但是再次点击 “一级2” 节点，不能正常取消选择。

### What is Expected?
当第二次点击 “一级2” 节点的时候，能够取消选中  “一级2” 节点以及该节点的所有子节点

### What is actually happening?
第二次点击 点击 “一级2” 节点，什么都没有发生

**Comment by v8xm** [comment]
无法复现。点击了好几次都没问题啊。

**Comment by languanghao** [comment]
@v8xm 你先勾选根节点，然后再点根节点的复选框能取消复选吗？我试了好几次都不行啊

**Comment by Dreamacro** [comment]
与 #12656 重复
