### ISSUE TITLE
The [Bug Report] form verifies errors in reporting is, not, a, string because of data types

### ISSUE THREAD

**Issue by xyDiva** [ElemeFE/element#7043]
### Element UI version
1.2.9

### OS/Browsers version
win 10 / chrome 60.0.3112.113

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
多选框选择任意一项值

### What is Expected?
验证通过

### What is actually happening?
验证不通过

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by xyDiva** [comment]
更新了链接。
