### ISSUE TITLE
After [Bug Report] el-select sets the filterable property, click the small triangle and cannot pull down the drop-down menu

### ISSUE THREAD

**Issue by xing-zhi** [ElemeFE/element#7045]
### Element UI version
1.4.4

### OS/Browsers version
win8.1/chrome59, Debian8/chrome59

### Vue version
2.4.4

### Reproduction Link
[https://codepen.io/xingzhi/pen/bodgJL](https://codepen.io/xingzhi/pen/bodgJL)

### Steps to reproduce
设置filterable属性的el-select在展开状态下点击小三角

### What is Expected?
设置filterable属性后，点击小三角既可以展开下拉菜单，也可以收起下拉菜单

### What is actually happening?
设置filterable属性后，点击小三角可以展开下拉菜单，但无法收起下拉菜单

**Comment by Leopoldthecoder** [comment]
会在下个大版本中修复。
