### ISSUE TITLE
[Bug Report] radio selected status rounded display problem

### ISSUE THREAD

**Issue by GyuanHFUT** [ElemeFE/element#7052]
### Element UI version
1.4.4

### OS/Browsers version
win7/chrome/ie11

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
忽略重现链接,直接http://element.eleme.io/#/zh-CN/component/radio
官网可以看到,在ie11选中内圆右下角是方形的.且在chrome下缩小后圆心会产生偏移变形.

### What is Expected?
圆心在任何状态下保持一致.

### What is actually happening?
圆心在任何状态下保持一致.

**Comment by Leopoldthecoder** [comment]
浏览器渲染问题，Radio 圆心就是一个 `border-radius` 和 `transform`。
