### ISSUE TITLE
In [Bug Report] el-input, enter the key to jump page bug

### ISSUE THREAD

**Issue by maxiye** [ElemeFE/element#7053]
### Element UI version
1.4.4

### OS/Browsers version
chrom 61

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
http://element.eleme.io/1.4/#/zh-CN/component/form
请忽略重现链接，具体可在**element官网教程form表单模块中，数字类型验证的年龄输入框中按回车，即会发送跳转。**
表单只有一个或者两个input，输入框中键入回车后页面会发生跳转，跳转路径为原路径#前加一个?号。

### What is Expected?
输入回车应无任何动作

### What is actually happening?
页面发送跳转

**Comment by Leopoldthecoder** [comment]
这是浏览器的默认行为：https://jsfiddle.net/1ypzmcfb/

可以通过在 Form 上加事件监听阻止：
```html
<el-from @submit.native.prevent>
```

**Comment by maxiye** [comment]
感谢解答
