### ISSUE TITLE
[Bug, Report], How, do, I, add, clickevent, to,, the, <el-step>, component?

### ISSUE THREAD

**Issue by 610076912** [ElemeFE/element#7058]
### Element UI version
1.4.3

### OS/Browsers version
chrome 60.0.3112.113（正式版本）

### Vue version
2.4.4

### Reproduction Link
[https://github.com/ElemeFE/element/issues/4072](https://github.com/ElemeFE/element/issues/4072)

### Steps to reproduce
。

### What is Expected?
I can add events to step component

### What is actually happening?
I can`t add events to step component

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
