### ISSUE TITLE
Does the [Feature Request] Upload support the maximum number of files?

### ISSUE THREAD

**Issue by Darkbish** [ElemeFE/element#7062]
### Existing Component
是

### Component Name
Upload

### Description
希望 upload 组件可以支持最大文件数量，如果已经达到最大文件数量后，隐藏选择文件的按钮，删除文件后，显示选择文件按钮

**Comment by Leopoldthecoder** [comment]
这些都可以在 `on-change` 或 `on-success` 钩子中完成。
