### ISSUE TITLE
[Bug Report] Table filter bug

### ISSUE THREAD

**Issue by fjc0k** [ElemeFE/element#7066]
### Element UI version
1.4.4

### OS/Browsers version
win8 / chrome61

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/Lqmr1bzc/](https://jsfiddle.net/Lqmr1bzc/)

### Steps to reproduce
点击`审核状态`出现筛选框，点击`待审核`，筛选框消失，再点击`审核状态`打开筛选框。

### What is Expected?
应只有`待审核`为激活状态。

### What is actually happening?
然而，`全部`和`待审核`都为激活状态。

**Comment by Leopoldthecoder** [comment]
Fixed in #7069
