### ISSUE TITLE
[Bug Report] table: change tableData after filtered some data, the wrong  result really confused me.

### ISSUE THREAD

**Issue by georgehpj** [ElemeFE/element#7067]
### Element UI version
1.4.4

### OS/Browsers version
macOs

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/georgehpj/p44sdr0x/](https://jsfiddle.net/georgehpj/p44sdr0x/)
[https://jsfiddle.net/georgehpj/p44sdr0x/1/](https://jsfiddle.net/georgehpj/p44sdr0x/1/)

### Steps to reproduce
先过滤性别，然后分两种情况：
1. 点“刷新数据”，直接修改的tableData，性别过滤状态还在，但数据没有根据过滤条件筛选。然后再点按年龄排序，展示出来的是旧数据。

2. 点“重置table刷新数据，后端过滤”（因为没找到重置过滤或者排序的方法，直接把table卸了重新渲染来实现的重置状态，这个例子中通过提供的filterChange来实现后端数据过滤）；然后过滤性别，再点年龄排序，展示出来的是未过滤的所有数据。

### What is Expected?
1.在直接修改tableData的情况下，数据需要根据过滤条件筛选；排序结果展示新的tableData数据。
2.在重置table修改tableData，且通过后端实现数据过滤的情况下，先过滤，后排序，结果应该是对过滤后的数据进行的排序。

### What is actually happening?
1.在直接修改tableData的情况下，数据未根据过滤条件筛选；排序结果展示旧的tableData数据。
2.在重置table修改tableData，且通过后端实现数据过滤的情况下，先过滤，后排序，结果对过滤前的数据进行的排序。

**Comment by liril-net** [comment]
@georgehpj 问题1 下个版本已解决，问题2 因为你的例子是 `v-if` 实现的重置，相关的列将销毁然后重新渲染，导致旧有列的过滤、排序信息会丢失。能详细讲解一下你使用 `v-if` 的具体场景吗？

**Comment by georgehpj** [comment]
在变更查询条件后重新向后端发请求获取数据时，之前的过滤条件和排序对于新的数据来说可能并没有意义，所以存在重新查询时需要重置表头的过滤和排序状态的情况。但是我没找到重置表头状态的api，所以目前看起来只能用这种方式实现了，不过还是有点儿问题，就是问题2里出现的bug。

**Comment by liril-net** [comment]
@georgehpj 好滴，第一个问题下个版本会提供对应的 `api`，第二个问题应该也解决掉了。

**Comment by yangyanan05521** [comment]
@georgehpj 麻烦请教下，你是如何重置过滤的，我是想不点重置按钮，可以达到重置效果（包括：不显示蓝色的列的样式，和里面的勾选）？非常感谢！！

**Comment by georgehpj** [comment]
@yangyanan05521 1.X版本里没有重置过滤的api，是通过v-if 和 nextTick实现的，先把整个表destroy掉，再重新实例化出来。2.X版本提供了clearFilter方法。

**Comment by yangyanan05521** [comment]
@georgehpj 我明白了，真的非常感谢你的回复！！
