### ISSUE TITLE
[Feature Request] There are more cascading cascades, which may account for more than half of the screen. Are there any other cascading displays?

### ISSUE THREAD

**Issue by Denny-coder** [ElemeFE/element#7070]
### Existing Component
Yes

### Component Name
Cascader

### Description
Cascading multiple, occupying too many screens, can be like a tree?

**Comment by Leopoldthecoder** [comment]
没懂什么意思，目前 Cascader 没有多选模式。可以用中文描述一下。

**Comment by Denny-coder** [comment]
https://lanux.github.io/Vue-Admin/#/sys/resource   这个页面的父级的那种效果怎么实现？

**Comment by Leopoldthecoder** [comment]
这是一个树选择器，Element 目前没有这个组件，你可以看一下 @lanux 的实现：https://github.com/lanux/Vue-Admin/blob/master/src/components/selectTree.vue
