### ISSUE TITLE
The [Bug Report] card type carousel causes the entire page jitter

### ISSUE THREAD

**Issue by SamanthaLor** [ElemeFE/element#7074]
### Element UI version
1.4.3

### OS/Browsers version
win10/qqbrowser/chorme 60.0.3112.113

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
https://jsfiddle.net/api/post/library/pure/

### What is Expected?
页面能够正常渲染，但不引起抖动发生

### What is actually happening?
2秒抖动一次，包含文字都重新渲染，忽大忽小问题

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
