### ISSUE TITLE
[Feature Request], please add a @select event /Please, add, a, event, @select, to, the, el-select, component for the el-select component

### ISSUE THREAD

**Issue by lemontree2000** [ElemeFE/element#7075]
### Existing Component
是/yes

### Component Name
el-select

### Description
请为el-select组件添加一个@select 事件，选中获取改行的所有数据。 因为当前change事件只有一个回调参数，不能满足复杂的业务场景。

Please add a @select event to the el-select component and select all data that gets this row as callback parameters. Because the current change event has only one callback parameter, it does not satisfy the complex business scenarios.

**Comment by Leopoldthecoder** [comment]
用回调的参数遍历 options 就可以找到对应 option 的全部数据。
