### ISSUE TITLE
[Feature Request] asks for additional notify document cases

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#7080]
### Existing Component
是

### Component Name
notify

### Description
在文档的 message 接口仅仅是简单的说能用 render 函数返回一个 vNode，确实，对于你们这些高手来说这不难理解，但是考虑到用的人的平均水平， 你不可能让他判断他是 vue 能力不足 还是 文档不充分，所以希望加入 挂在 component 到 vNode 的案例。
例如我写了一个: [jsfiddle.net](https://jsfiddle.net/evolutionjay/3b4aus9d/8/)

**Comment by evolutionjay** [comment]
顺便， 发现当多个 notify 同时出现， 然后中间有一个的容器 改变了 notify 的高度的时候， 会造成错乱，建议加入一个全局 notify 位置 update 的方法供开发者调用。

**Comment by Leopoldthecoder** [comment]
It's not our job to teach people how to use Vue.
