### ISSUE TITLE
[Bug Report] Form validator, 'space' passed 'required' rule

### ISSUE THREAD

**Issue by leoz2z** [ElemeFE/element#7083]
### Element UI version
1.4.4

### OS/Browsers version
chrome 60

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/567/](https://jsfiddle.net/pj71jkyw/567/)

### Steps to reproduce
focus a required input or textarea

press keyboard 'space bar'

### What is Expected?
'space' shouldn't break 'required' rule

### What is actually happening?
'space' passed 'required' rule

**Comment by Leopoldthecoder** [comment]
You can add a `pattern` to test against spaces. https://github.com/yiminghe/async-validator
