### ISSUE TITLE
[Bug Report] Dropdown does not react as expected

### ISSUE THREAD

**Issue by stevobm** [ElemeFE/element#7087]
### Element UI version
1.4.2

### OS/Browsers version
Win7/Chrome v61

### Vue version
2.3.3

### Reproduction Link
[https://codepen.io/stevobm/pen/PJPLzo](https://codepen.io/stevobm/pen/PJPLzo)

### Steps to reproduce
First, click the right button of the "Menu" button to show the dropdown menu.
Second, click the left button of the "Menu" button.

### What is Expected?
The dropdown menu hides  automatically, like bellow:
Bootstrap Dropdown: https://codepen.io/stevobm/pen/veNQBP
Ant Design DropDown: https://codepen.io/stevobm/pen/dVYgEg

### What is actually happening?
The dropdown menu doesn't hide automatically.

**Comment by Leopoldthecoder** [comment]
Fixed in #7089
