### ISSUE TITLE
[Feature Request] el-switch cannot specify on-value under JSX

### ISSUE THREAD

**Issue by wuchuguang** [ElemeFE/element#7091]
### Existing Component
是

### Component Name
el-switch

### Description
el-switch无法在jsx下指定on-value
因为on-开头是事件

**Comment by wuchuguang** [comment]
有什么解决方案吗？

**Comment by Leopoldthecoder** [comment]
2.0 版本把 Switch 里 `on-` 开头的一系列属性名改为 `active-` 了，具体请参照 2.0 的更新日志。

**Comment by wangzongxu** [comment]
凑 掉坑了
