### ISSUE TITLE
[Feature Request] Error Bags after form validation / Ability to trigger custom errors ( potentially coming from a server side validation)

### ISSUE THREAD

**Issue by yannick-yeboue-fm** [ElemeFE/element#7093]
### Existing Component
Yes

### Component Name
Form

### Description
1) Is it possible to get a list of all errors generated after a form validation (this.form.$errors) ? like an ErrorBag in ( Vee-Validate)

2) How does this form validation work if I need to create custom (nested) components using the Element UI components. ( Do I validate these nested components individually ? Or Is there a way for transferring validation errors between my custom child components and the parent component ? )

3) How do I handle and trigger form validation errors that may require some server-side implementation ? ( for example if a user enters an email that is already taken and I want to display an error saying "this email address is already in use ?" in the same location where the email field error is supposed to appear

**Comment by Leopoldthecoder** [comment]
Issues are not for usage questions. Please ask them in Gitter.
