### ISSUE TITLE
[Feature Request] An ability to hide "remove" icon or an ability to prevent removing individual files

### ISSUE THREAD

**Issue by teamyudin** [ElemeFE/element#7095]
### Existing Component
Yes

### Component Name
Upload

### Description
Trying to figure out a way to hide "el-icon-close" for individual files. The only option I see is to find a list item by file name, and hide the icon from there, but that wont work with duplicate file names.

**Comment by Leopoldthecoder** [comment]
You can add `display: none` to the close icons.

**Comment by teamyudin** [comment]
Like I mentioned in the descriptions: How can it be done with duplicate file names?

[https://jsfiddle.net/x20e4upf/](url)

**Comment by Leopoldthecoder** [comment]
Your fiddle has three files, which icon(s) do you wish to hide?

**Comment by teamyudin** [comment]
For example: hide remove from: fileList[1] only. In the fiddle, file list is static, in reality I have a dynamic list, where each file has "removable" attribute. File name and URL's can be duplicated.

**Comment by Leopoldthecoder** [comment]
Then I guess you'll have to play with DOM a little bit: https://jsfiddle.net/x20e4upf/1/ . If the file list is  dynamic, you can simply watch it.
