### ISSUE TITLE
can import el select

### ISSUE THREAD

**Issue by nicqchen01** [ElemeFE/element#7096]
### Element UI version
1.4.4

### OS/Browsers version
windows 10

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
import ElSelect from "../../node_modules/element-ui/packages/select/src/select.vue";

### What is Expected?
worked

### What is actually happening?
  [265] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
  [266] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
  [267] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js 52 bytes {0} [built]
       253 hidden modules

ERROR in ./~/element-ui/packages/input/index.js
Module not found: Error: Can't resolve './src/input' in 'C:\workspace\Lusen_GamePlatform\Lusen_Game_Web\node_modules\element-ui\packages\input'
 @ ./~/element-ui/packages/input/index.js 1:0-34
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/element-ui/packages/select/src/select.vue
 @ ./~/element-ui/packages/select/src/select.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/component/AppConfig.vue
 @ ./src/component/AppConfig.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./~/element-ui/packages/tag/index.js
Module not found: Error: Can't resolve './src/tag' in 'C:\workspace\Lusen_GamePlatform\Lusen_Game_Web\node_modules\element-ui\packages\tag'
 @ ./~/element-ui/packages/tag/index.js 1:0-30
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/element-ui/packages/select/src/select.vue
 @ ./~/element-ui/packages/select/src/select.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/component/AppConfig.vue
 @ ./src/component/AppConfig.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./~/element-ui/packages/scrollbar/src/main.js
Module parse failed: C:\workspace\Lusen_GamePlatform\Lusen_Game_Web\node_modules\element-ui\packages\scrollbar\src\main.js Unexpected token (65:6)
You may need an appropriate loader to handle this file type.
|     }, this.$slots.default);
|     const wrap = (
|       <div
|         ref="wrap"
|         style={ style }
 @ ./~/element-ui/packages/scrollbar/index.js 1:0-35
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/element-ui/packages/select/src/select.vue
 @ ./~/element-ui/packages/select/src/select.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/component/AppConfig.vue
 @ ./src/component/AppConfig.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by Leopoldthecoder** [comment]
Read the documentation for how to import components.
