### ISSUE TITLE
[Bug Report] el-tab-pane v-show not taking effect

### ISSUE THREAD

**Issue by runjia1987** [ElemeFE/element#7100]
### Element UI version
1.4.3

### OS/Browsers version
Ubuntu 16.04 Chrome  58.0.3029.81 x64

### Vue version
2.4.2

### Reproduction Link
[http://jsfiddle.net/smwnf4nm/1/](http://jsfiddle.net/smwnf4nm/1/)

### Steps to reproduce
run

### What is Expected?
third pane be hidden.

### What is actually happening?
third pane is not hidden when v-show returns false.

**Comment by Leopoldthecoder** [comment]
Just like `el-table-column`, you need to use `v-if` to control `el-tab-pane`'s visibility.

**Comment by HJWAJ** [comment]
@Leopoldthecoder Hi, I'm new to Vue and ElementUI. After I use `v-if`, I got error in console, which shows `[Vue warn]: Duplicate keys detected: 'tab-7'. This may cause an update error.` As I use el-tab in many places, these errors disturb me from my normal debug. Could you plz give some suggestions?

**Comment by remones** [comment]
Thanks for your work about Element, but I think it's better if there are some docs about this on the official website.😄 @Leopoldthecoder

**Comment by wenweih** [comment]
@HJWAJ is there any solution?

**Comment by Lesty612** [comment]
> @Leopoldthecoder Hi, I'm new to Vue and ElementUI. After I use `v-if`, I got error in console, which shows `[Vue warn]: Duplicate keys detected: 'tab-7'. This may cause an update error.` As I use el-tab in many places, these errors disturb me from my normal debug. Could you plz give some suggestions?

You need to add a **unique** `key` attribute to `el-table-column` where you use `v-if`
