### ISSUE TITLE
How does [Feature Request] facilitate access to the currently selected label value of the component?

### ISSUE THREAD

**Issue by duchaopaopao** [ElemeFE/element#7104]
### Existing Component
是

### Component Name
el-select

### Description
场景如下，如何方便的获取城市名字，不要说去通过val去循环数组了https://jsfiddle.net/mznk94kf/5/

**Comment by Leopoldthecoder** [comment]
就是要遍历数组：https://jsfiddle.net/mznk94kf/6/
