### ISSUE TITLE
[Bug Report] Table component doesn't work while using "v-if" with grouping table column  

### ISSUE THREAD

**Issue by smile33** [ElemeFE/element#7107]
### Element UI version
1.4.4

### OS/Browsers version
window 7/ chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/mqvh8owx/5/](https://jsfiddle.net/mqvh8owx/5/)

### Steps to reproduce
Click a button to change a variable that control the column of grouping table head to show or not. 

### What is Expected?
The column of grouping table head will be showed or disappeared by using "v-if"

### What is actually happening?
The column of grouping table head was disappeared while using "v-if"

**Comment by Leopoldthecoder** [comment]
`el-table-column` should be `key`ed: https://jsfiddle.net/mqvh8owx/7/ . The `Math.random()` is just for demonstration, you can use any key that is unique throughout the columns.

**Comment by smile33** [comment]
It's ok now,thank you
