### ISSUE TITLE
How do I add csrf-token to the upload component?

### ISSUE THREAD

**Issue by BadTudou** [ElemeFE/element#7110]
When I use the component of upload, I added an input box whose name is **authenticity_token**, but I can not get the value of **authenticity_token**.
`
<el-upload
  class="upload-demo"
  drag
  action="<%= action %>"
  multiple>
  <i class="el-icon-upload"></i>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
  <div class="el-upload__tip" slot="tip"><%= explain %></div>
</el-upload>
`

`
Processing by ClippingController#upload as */*
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x00007febe2c0fbb8 @tempfile=#<Tempfile:/var/folders/f7/ql6g9dbd52ndbyznm3n71q8h0000gn/T/RackMultipart20170919-13721-9m8ttw.txt>, @original_filename="demo.txt", @content_type="text/plain", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"demo.txt\"\r\nContent-Type: text/plain\r\n">}
`

**Comment by euperia** [comment]
Here's how I handled the CSRF token:
```
<el-upload ref="uploader" :before-upload="beforeUpload">

...
beforeUpload() {
    const csrf = document.querySelector('meta[name="csrf-token"]').content;
    this.$refs.uploader.headers['X-CSRF-TOKEN'] = csrf
}
```
