### ISSUE TITLE
[Feature, Request], DateTimePicker, plugin, is, hard, to, use

### ISSUE THREAD

**Issue by boolBit** [ElemeFE/element#7113]
### Existing Component
是

### Component Name
DateTimePicker 

### Description
now i'm use datetimePicker. but if i want to change time，it's must click confirm button， it could be changed when click the time。
also because it‘s hard to use， if i directly change the time use keyboard， but the real model is not change， its display time not equals the real time。
datePicker is easy to use， hope can change just like java datepicker plugin， thanks

**Comment by Leopoldthecoder** [comment]
We have no plan to change its interaction behavior.
