### ISSUE TITLE
[Bug Report] message message prompt component

### ISSUE THREAD

**Issue by huangweihaili123** [ElemeFE/element#7117]
### Element UI version
1.4.4

### OS/Browsers version
Browser

### Vue version
2.4.4

### Reproduction Link
[https://github.com/ElemeFE/element/issues?page=2&q=message&utf8=%E2%9C%93](https://github.com/ElemeFE/element/issues?page=2&q=message&utf8=%E2%9C%93)

### Steps to reproduce
this.$message({
showClose: true,
message:'5秒后跳转',
duration: 3000,
type: 'success',
});
5秒怎么变成动态的，就是倒计时那种的5，4，3，2，1，实现不了

### What is Expected?
this.$message({
showClose: true,
message:'5秒后跳转',
duration: 3000,
type: 'success',
});
5秒怎么变成动态的，就是倒计时那种的5，4，3，2，1，实现不了

### What is actually happening?
  this.$message({
                    showClose: true,
                    message: this.renderVNode(5),
                    duration: 3000,
                    type: 'success',
                  });
renderVNode(data){
            let time=data
           setInterval(()=>{
            if(time!=0){
              time--
              return <span>{time}</span>
            }
          },1000);

        }

**Comment by Leopoldthecoder** [comment]
It's not supported, but you can always manipulate DOM: https://jsfiddle.net/g0Lyt8dL/

**Comment by huangweihaili123** [comment]
Thank you
