### ISSUE TITLE
[Bug Report] remote search

### ISSUE THREAD

**Issue by huangweihaili123** [ElemeFE/element#7119]
### Element UI version
1.4.4

### OS/Browsers version
 Browser 

### Vue version
2.4.4

### Reproduction Link
[https://github.com/ElemeFE/element/issues/7117](https://github.com/ElemeFE/element/issues/7117)

### Steps to reproduce
远程搜索的select组件在选中值后又会以这个值做为搜索条件远程搜索

### What is Expected?
怎么去掉之前的那个值

### What is actually happening?
远程搜索的select组件在选中值后又会以这个值做为搜索条件远程搜索

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by huangweihaili123** [comment]
#7119
