### ISSUE TITLE
[Feature Request] because the vendor.js days after the package are large, I want to introduce elementUI's CDN resources into the Vue, but I also want to continue using the vue-cli development model. What should I do?

### ISSUE THREAD

**Issue by zhuqitao** [ElemeFE/element#7121]
### Existing Component
No

### Component Name
not some component. I'm only ask some question.

### Description
因为打包之后的vendor.js天大，所以我想在vue中引入elementUI的cdn资源，但是还想继续使用vue-cli的开发模式，应该怎么做？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
