### ISSUE TITLE
The [Bug Report] Tree defaultProp children uses the Function console to report errors

### ISSUE THREAD

**Issue by zjpzjp** [ElemeFE/element#7124]
### Element UI version
1.4.4

### OS/Browsers version
win7/chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/g9v6opf5/3/](https://jsfiddle.net/g9v6opf5/3/)

### Steps to reproduce
Tree控件 props中children
由于数据结构需要，所以子集得chilren 不固定；
使用function 功能实现了 但是控制台会报错，例子如下：

### What is Expected?
控制台不抱错

### What is actually happening?
[Vue warn]: Failed watching path: "node.data.(data, node) => data.children ? data.children : data.childrenxxx" Watcher only accepts simple dot-delimited paths. For full control, use a function instead.

found in

---> <ElTreeNode>
       <ElTree>
         <Root>

**Comment by Leopoldthecoder** [comment]
`props` 属性不接受函数作为它的值。对于字段名不确定的数据，请自行格式化。

**Comment by gorghoa** [comment]
@Leopoldthecoder,

from the doc, `children` should be able to handle a function. (And, as a matter of fact, it does).

![image](https://user-images.githubusercontent.com/662768/37342976-7e875f14-26c6-11e8-856a-db1808a26567.png)

http://element.eleme.io/1.4/#/en-US/component/tree

But, it still triggers this kind of errors in console:

![image](https://user-images.githubusercontent.com/662768/37343068-b2dcb890-26c6-11e8-815e-2efc9ea77905.png)
