### ISSUE TITLE
[Feature Request] Add ability to set width of calendar popup

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#7128]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Currently, the DatePicker calendar popup has the same width as the input it is opened from. It would be nice if the width could be set via a property to limit the width in case the input is very wide. Overriding the width now requires styling `.el-picker-panel` and giving it an `!important` width. Moreover, with scoped styles, one needs to use `/deep/` or `>>>`

https://jsfiddle.net/qzjm9a9g/

**Comment by Leopoldthecoder** [comment]
DatePicker will have a fixed width in the next major version.
