### ISSUE TITLE
[Bug Report] Press enter in a form with only one input field will trigger browser redirect

### ISSUE THREAD

**Issue by JavaCS3** [ElemeFE/element#7135]
### Element UI version
1.4.4

### OS/Browsers version
Chrome/60.0.3112.113

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/mm99jvfg/](https://jsfiddle.net/mm99jvfg/)

### Steps to reproduce
focus on input field then press ENTER key

### What is Expected?
no action or at least submit form without redirect

### What is actually happening?
browser navigate to http://<domain>/?#/

![bug](https://user-images.githubusercontent.com/4168698/30646792-bd11ae5e-9e4c-11e7-9353-b46cdedc4d59.gif)

**Comment by smares** [comment]
That is because the underlying form element is submitted. You can catch that using `@submit.native.stop.prevent` and a custom `submit` handler.

https://jsfiddle.net/vhgda6md/
