### ISSUE TITLE
关于 Transfer 穿梭框   filter-method  事件资讯

### ISSUE THREAD

**Issue by zhang2017wei** [ElemeFE/element#7139]
hello:
        我现在在使用你们的element.ui,对于Transfer 穿梭框这个功能里面的  filter-method   有些不懂，我的页面最开始是完成了，现在想自定义一个搜索方法，
![image](https://user-images.githubusercontent.com/29528417/30675251-10d7d2e2-9eb2-11e7-8fa5-ac1d0ff26d7e.png)
![image](https://user-images.githubusercontent.com/29528417/30675263-210a3fc4-9eb2-11e7-8424-c869a1ffcbc1.png)刷新页面的时候在控制台看到了问题的触发，但是
![image](https://user-images.githubusercontent.com/29528417/30675308-4df84f44-9eb2-11e7-90a2-87b47045384a.png)这个页面的数据却渲染不出来了，并且我在上面搜索框进行输入时也触发不了我绑定的事件，请问一下是怎么回事，谢谢

**Comment by ale-batt** [comment]
same issue..
