### ISSUE TITLE
rc8 table show-tooltip-when-overflow属性失效

### ISSUE THREAD

**Issue by yuu2lee4** [ElemeFE/element#714]
升级到rc8后table show-tooltip-when-overflow属性失效

**Comment by devrsi0n** [comment]
我也是，=.=

**Comment by QingWei-Li** [comment]
先自己改样式覆盖吧。。。fixed in https://github.com/ElemeFE/element/pull/717

**Comment by yuu2lee4** [comment]
@QingWei-Li   改了没用  我们应该改lib下面的吧  但是lib下面的是编译后的。。。。

**Comment by QingWei-Li** [comment]
不，我说的是自己写 CSS，我刚才提的 PR 也就是改了改样式

**Comment by yuu2lee4** [comment]
额  好吧。。。

**Comment by yuu2lee4** [comment]
行了 就是tooltip的宽度不对  左边有一个字被遮挡了
win10 chrome55

**Comment by QingWei-Li** [comment]
@yuu2lee4 给的 demo 或者截个图？

**Comment by yuu2lee4** [comment]
![image](https://cloud.githubusercontent.com/assets/8046366/19827934/742e816a-9deb-11e6-8f21-4be44ad7080b.png)

**Comment by QingWei-Li** [comment]
给 .el-tooltip__popper 加个最大宽度吧
