### ISSUE TITLE
[Bug Report] Slider component slider click back bug

### ISSUE THREAD

**Issue by zhaozhe0831** [ElemeFE/element#7145]
### Element UI version
1.3.6

### OS/Browsers version
mac os 10.12 / Chrome 60

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/b8f7pstr/](https://jsfiddle.net/b8f7pstr/)

### Steps to reproduce
在间断点模式下，点击调整滑块位置时，滑块移动，再次点击滑块，滑块会返回。

### What is Expected?
不清楚是否是这样设计的，如果不是这样设计的，实际上是个比较严重的 bug。

### What is actually happening?
点击后，无任何反应。

**Comment by zhaozhe0831** [comment]
![bug1](https://user-images.githubusercontent.com/12945873/30639403-4b84b2ce-9e31-11e7-96a8-b9ac2d0cecf2.gif)

**Comment by Leopoldthecoder** [comment]
在 macOS 10.12 / Chrome 60 下未能复现。你换台机器能够复现吗？

**Comment by zhaozhe0831** [comment]
可以多尝试几次，我这两台 mac 都出现了，gif 是截的官网的图。也就是说，访问官网就可以复现这个问题。

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/30679215-837a73b4-9eca-11e7-9fcd-a8a117b695e9.png)

请确认出现问题的官网版本是否为 1.4.4

**Comment by zhaozhe0831** [comment]
是 1.4.4。复现问题 需要先拖动一次滑块后，再通过点击灰色点，选择滑块位置，即可触发问题。

**Comment by zhaozhe0831** [comment]
![bug](https://user-images.githubusercontent.com/12945873/30680017-d9fef5fc-9ecf-11e7-9d70-f0d3e2971556.gif)

**Comment by Leopoldthecoder** [comment]
OK，我复现了。

**Comment by zhaozhe0831** [comment]
Thank you !

**Comment by Leopoldthecoder** [comment]
Fixed in #7190
