### ISSUE TITLE
[Feature Request] Can cascader support for revealing more than the current selected menu's value ?

### ISSUE THREAD

**Issue by richardyou** [ElemeFE/element#7146]
### Existing Component
Yes

### Component Name
el-cascader

### Description
When I use cascader,I keep many options in menu and it's submenu, like id,label,name etc.Hope the change event can expose the menu itself, more than the selected menu's value.
just copied element's fiddle link
https://jsfiddle.net/api/post/library/pure/

**Comment by richardyou** [comment]
@element-bot 
Hi,when i new issue ,I didn't find the jsfiddle option,maybe I didn't notice it. Anyway,it's a feature request issue,so I just copied element's jsfiddle page in my issue detail.
Best regards!

**Comment by Leopoldthecoder** [comment]
We have no plan to support this. You can traverse the source data to get the corresponding menu items.
