### ISSUE TITLE
[Feature Request] expects to support a copy of the date sheet of the date panel in the custom date component

### ISSUE THREAD

**Issue by JanlyH** [ElemeFE/element#7148]
### Existing Component
是

### Component Name
DatePicker

### Description
希望能支持自定义日期组件中的日期面板的某天的文案，这样可以预设某个特定的节日的文案，例如今天是中秋节（2017.10.04），我预设了2017.10.04这个日期显示的文案是"中秋"，而不是"4"

**Comment by Leopoldthecoder** [comment]
无计划。
