### ISSUE TITLE
[Bug Report] table changes again when the parent class container width becomes larger and cannot accommodate the container width

### ISSUE THREAD

**Issue by lyh2668** [ElemeFE/element#7149]
### Element UI version
1.4.4

### OS/Browsers version
 Chrome 60.0.3112.113

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/lyh2668/x5dkasx3/10/#](https://jsfiddle.net/lyh2668/x5dkasx3/10/#)

### Steps to reproduce
1. 在左侧给上一个menu菜单组件，并设置collapse属性
2. 右侧table，父类width: 100％
3. 点击按钮收缩menu，table的宽度将会自适应地增大
4. 再次点击按钮展开menu，table的宽度将不会发生变化，并且撑开父类容器

### What is Expected?
table不应该撑开父类容器的尺寸

### What is actually happening?
table不应该撑开父类容器的尺寸

**Comment by elfman** [comment]
@lyh2668 我在Chrome上没有重现你描述的bug啊

**Comment by lyh2668** [comment]
@elfman Demo当中可演示复线，在menu展开的时候右侧的table宽度充满右边栏屏幕，menu收拢再展开就会将table挤出屏幕，我的chrome版本上面有些，系统是OSX10.11

**Comment by fuqihan** [comment]
@lyh2668 你好，我也是卡在这个问题上了，试过给el-table margin-right: -1px;他会渐渐变回正常，但是效果特别差，感觉只能用js计算宽度了

**Comment by fuqihan** [comment]
@lyh2668 
你好，我的和你是一样的问题，我是给el-table position: absolute;right: 0  使他不在往右边挤，再给
*::-webkit-scrollbar {
      display: none;
    }
使效果看上去不是那么生硬，但是效果会是在震动，有什么好的改进可以交流下吗，谢谢

**Comment by lyh2668** [comment]
@fuqihan 我采用的方法是这样的，通过watch去监控宽度变化，然后再去修改他的style样式，并且加上匹配的动画效果，但是由于有延时的感觉，相同的动画效果仍然不能很同步，所以我的方案在收拢的时候同样会有一些抖动，不过抖动在能接受的范围之内，不妨试试。

**Comment by liril-net** [comment]
你好，这个不是 `Table` 本身的问题，而是因为，`flex: 1` 和 `width: 100%` 会导致没有实际的宽度。如果你想实现相应的效果，建议你使用其它布局方式。

**Comment by lyh2668** [comment]
@liril-net 能否提供一个解决方案？我尝试过很多方式都存在这个问题。

**Comment by liril-net** [comment]
使用 `absolute` 布局，`left` 根据左侧的大小进行改变。
