### ISSUE TITLE
[Feature Request] Accept values over 100% for progress bars

### ISSUE THREAD

**Issue by pierre-moire** [ElemeFE/element#7150]
### Existing Component
Yes

### Component Name
Progress

### Description
Sometimes a value over 100% makes sense (e.g: target achievement) but if we try to set one over 100 for the Progress element, it triggers an error.

The component works already as we could expect apart from this error: 
- value appears correct 
- bar is set at its maximum and doesn't span outside its limits

Can we just remove the limit of 100 for percentage's accepted values ?

**Comment by wacky6** [comment]
Can you give a more detailed scenario / example?

**Comment by pierre-moire** [comment]
I would like to have the ability to have this without triggering errors : 
![image](https://user-images.githubusercontent.com/2143238/30691232-698c6604-9ec7-11e7-8aba-ecf40c03ea1b.png)

Currently if I provide 300 to percentage, this error appear : 
![image](https://user-images.githubusercontent.com/2143238/30691298-992e3f04-9ec7-11e7-8f36-222e8cbc173d.png)

A value over 100% is possible in a lot of cases. Here are some examples : 
- you have a target and you outperform your target
- a budget has been defined and you are over it
- a system load that goes over it's limits

**Comment by qifenshu** [comment]
maybe someone thought its a bug,but i think we shold do something like this:
always set 100 as max num, the the coder use math to cover the progress num  like"3*80%=240%",then show a text-label over the bar.

**Comment by wacky6** [comment]
I think for these scenarios, you should write a wrapper component for el-progress, or a separate component without using el-progress. The word "progress" does not make semantic sense for these scenarios. A progress bar that can go beyond 100% may seem weird to many people.
