### ISSUE TITLE
[Bug Report] DatePicker doesn't update underlying input name and value

### ISSUE THREAD

**Issue by Novarg** [ElemeFE/element#7151]
### Element UI version
1.4.4

### OS/Browsers version
any

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/p0p4vLor/4/](https://jsfiddle.net/p0p4vLor/4/)

### Steps to reproduce
Set name attribute for el-date-picker.
Pick any date.

### What is Expected?
Expected that underlying input will get correct name attribute and its value will be updated when you pick up new date so you can submit form via browser.

### What is actually happening?
Currently no way to set name and value attributes of input field, this makes datepicker impossible to use in standard form submission process.

**Comment by Leopoldthecoder** [comment]
`name` will be supported in the next major version: #6042
