### ISSUE TITLE
[Feature Request] Filtering Select

### ISSUE THREAD

**Issue by serak** [ElemeFE/element#7155]
### Existing Component
Yes

### Component Name
Select

### Description
The select should autocomplete the typed word. eg https://dojotoolkit.org/reference-guide/1.10/dijit/form/FilteringSelect.html

**Comment by Leopoldthecoder** [comment]
Try `<el-autocomplete>`

**Comment by serak** [comment]
how could i participate in developing that feature, and make it available for all
