### ISSUE TITLE
[Bug Report] table in the set maxHeight and Height, the last column is set to fixed, the last second columns are not aligned vertical lines

### ISSUE THREAD

**Issue by pucong** [ElemeFE/element#7158]
### Element UI version
1.4.4

### OS/Browsers version
windows10，谷歌浏览器版本 56.0.2924.87

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/nLLm1kby/](https://jsfiddle.net/nLLm1kby/)

### Steps to reproduce
运行查看倒数第二列，竖线样式没有对齐

### What is Expected?
运行查看倒数第二列竖线对齐

### What is actually happening?
运行查看倒数第二列，竖线样式没有对齐

**Comment by liril-net** [comment]
Fixed in [Carbon](https://github.com/ElemeFE/element/releases/tag/v2.0.0)

**Comment by jiangshunxin** [comment]
@liril-net 您好，这个修复包含的是所有版本吗？
