### ISSUE TITLE
[Feature Request] Replace properties with attributes for cleaner looking markup

### ISSUE THREAD

**Issue by snarlynarwhal** [ElemeFE/element#7160]
### Existing Component
Yes

### Component Name
Layout -> Responsive Layout (can be applicable to other components/properties)

### Description
Instead of writing:
```
<el-row :gutter="10">
  <el-col :xs="8" :md="{span: 4, offset: 4}"><div class="grid-content bg-purple"></div></el-col>
</el-row>
```
I would like to write:
```
<el-row gutter10>
  <el-col xs8 md4 offset-md4><div class="grid-content bg-purple"></div></el-col>
</el-row>
```
It looks much cleaner. :)

**Comment by Leopoldthecoder** [comment]
We have no plan to support this.

**Comment by snarlynarwhal** [comment]
Oh darn.. If the reason for not wanting to support it is it being very low priority, I can do it and make a PR if you would like. Or do you just not want this feature at all?

**Comment by Leopoldthecoder** [comment]
If you're comfortable with Vue, the current syntax is pretty straightforward. Plus, implementing such feature may be too redundant.

**Comment by snarlynarwhal** [comment]
Okay, I see. Thanks for the reply!
