### ISSUE TITLE
[Feature Request] Add end to end tests using Cypress

### ISSUE THREAD

**Issue by bahmutov** [ElemeFE/element#7162]
### Existing Component
Yes

### Component Name
All

### Description
Hi everyone,

What do you plan to do for E2E testing? Can I propose using https://www.cypress.io/ that is going to be open sourced soon and thus is a good match for this open source project?

I took liberty of writing a few tests against the demo site and you can see the tests in https://github.com/bahmutov/element-e2e-tests repo. 

![cypress-runner](https://user-images.githubusercontent.com/2212006/30727145-5e4f43be-9f1d-11e7-8fa0-34c6c2b4cd61.png)

The testing tool itself is a dev dependency, works on Mac and CI (Windows is coming) and you can just keep it running as you work with the code. A typical test for a form for example looks a lot like Mocha/Jasmine unit test

https://github.com/bahmutov/element-e2e-tests/blob/master/cypress/integration/steps-spec.js

There is huge number of commands and assertions included, plus the docs at https://docs.cypress.io are really good.

I setup CI on Circle, but any CI would work. We also have free dashboard for OSS projects which can store screenshots / test results / video recording of runs. For this project it is at https://dashboard.cypress.io/#/projects/a9vb8w/runs Videos of runs is really useful to debug failing CI tests

Let me know if this is something the project needs. The tests could be part of this repo or some separate repo, whatever makes sense for you. We at Cypress would be happy to promote our free (and soon OSS) tool by helping people start E2E testing for Vue.js projects.

**Comment by Leopoldthecoder** [comment]
Hi @bahmutov 

First I'd like to address my thanks to you for writing demo tests for Element.

E2E testing would be a good thing for this project, and Cypress seems to be a great tool to do that. Unfortunately our team is focusing on adding features and fixing bugs for the time being (and in the near future), so we don't really have a schedule for E2E testings.

We'll definitely consider this when the timing is right, and I'll let you know if we decide to add E2E testing.

**Comment by bahmutov** [comment]
Thanks @Leopoldthecoder for taking a look at this so quickly, appreciate this. Any time you want to start the process, either let me know or just grab the code from the example repo, and I would be happy to work more on this (writing tests, help with CI, etc)
