### ISSUE TITLE
[Bug Report] pagination input box part of the browser, there is no jump problem

### ISSUE THREAD

**Issue by fluteweng** [ElemeFE/element#7165]
### Element UI version
1.4.4

### OS/Browsers version
win7/360安全浏览器8.1

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/c25mhsyc/12/](https://jsfiddle.net/c25mhsyc/12/)

### Steps to reproduce
初次生成页面时，点击第三或者第二页，然后选中输入框中页码替换页码为1（输入页码与第一次进入页面的初始页码相同）即可复现不跳转。
when the first time page appeared, click a another paganation button jump to the other page,then dubble click the  number input in the end of paganation or any other ways to select the page number in the input, enter the same  page number as the first time page created to replace the number in the input(not to delete the old number,use replace function to enter the page number),the scene will repeat 

### What is Expected?
paganation应该跳转至输入的页码页
paganation shuld jump to the number which i entered

### What is actually happening?
paganation页码没有做任何跳转行为
paganation do nothing about the page jump

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/31583201-fd57a442-b15b-11e7-827d-05a7fe095bef.gif)

Cannot reproduce this.

**Comment by fluteweng** [comment]
Sorry for that mistake！ this is the reproduce gif 
![in_360](https://user-images.githubusercontent.com/13166102/31922461-92aa722a-b8a7-11e7-8487-d5d05e774e42.gif)

**Comment by fluteweng** [comment]
@Leopoldthecoder
