### ISSUE TITLE
[Bug Report] <el-table-column v-for=""><el-table-column></el-table-column></el-table-column> 和被重新赋值的 data 属性一起使用的时候，渲染结果不正确

### ISSUE THREAD

**Issue by wanganjun** [ElemeFE/element#7168]
### Element UI version
1.4.4

### OS/Browsers version
macOS 10.12.6 / Safari 10.1.2

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/Ljtbqfrg/2/](https://jsfiddle.net/Ljtbqfrg/2/)

### Steps to reproduce
点击一次“切换表格数据”按钮，渲染结果正确。
在点击一次“切换表格数据”按钮，渲染结果出现错误

### What is Expected?
点击“切换表格数据”按钮的作用是对表格的 data 属性重新赋值。
因为数据的不同，表格应该显示的列的数量会改变。
当需要显示的列的数量变化时，需要保证渲染结果的正确。

### What is actually happening?
当需要显示的列数增加时，渲染正常。
当需要显示的列数减少时，某些应该显示出来的列永久性的消失了。

**Comment by Leopoldthecoder** [comment]
`el-table-column` should be keyed: https://jsfiddle.net/Ljtbqfrg/3/ . The `Math.random()` is just for demonstration, you can use any key that is unique throughout the columns.

**Comment by eidonjoe** [comment]
当我在 https://jsfiddle.net/fLtkr2d0/2/ `v-for`遍历`el-table-column`用循环项及index组合作为`key`赋值给`el-table-column`,还是出现了题目所提到的问题, 我认为在这一次渲染里面`key`已经唯一了, 需要每次渲染都要对`key`赋予一个唯一值吗? 这里有点疑惑.

**Comment by wanganjun** [comment]
@eidonjoe 我现在的做法是一次渲染内的不同位置的 key 不一样，两次数据不同的渲染内相同位置的 key 不一样，两次数据相同的渲染内的相同位置的 key 一样。这样是没有问题的
