### ISSUE TITLE
[Feature, Request], The picture was submitted, but the user gave up submitting the form and the picture became junk

### ISSUE THREAD

**Issue by Denny-coder** [ElemeFE/element#7172]
### Existing Component
Yes

### Component Name
el-upload

### Description
element的图片上传是直接上传，越过了表单提交，如果用户上传完并不提交表单，那么这个已经上传的图片就成为垃圾文件,如何解决呢？

**Comment by Leopoldthecoder** [comment]
使用手动上传，文档中最后一个例子。
