### ISSUE TITLE
[Bug, Report], Tree, Component, bug

### ISSUE THREAD

**Issue by uliian** [ElemeFE/element#7176]
### Element UI version
1.4.4

### OS/Browsers version
windows10/chrome61.0.3163.91

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/573/](https://jsfiddle.net/pj71jkyw/573/)

### Steps to reproduce
点击按钮点我触发bug，查看chrome控制台

### What is Expected?
我输入了7个ID作为已选key，应该输出7个已选key

### What is actually happening?
丢了一个已选key

**Comment by Leopoldthecoder** [comment]
正确的行为是：
- 对于父节点 A，若它的子节点全部都是 disabled，那么 A 是无法被选中的
- 但是如果设置了 `check-strictly` 属性，那么是不会检查 A 的子节点是否全部都是 disabled 的

目前的版本不满足上述的第二条，是个 bug，已在 https://github.com/ElemeFE/element/commit/41c19249abd00d6d8be6ce0143450c3f83333958#diff-9bab772c3bf098fa1edf869272b0addbR294 修复，随下一个大版本发布。
