### ISSUE TITLE
[Bug Report], when input adds icon and adds a click event, and then disables input, icon will still be clicked and triggered

### ISSUE THREAD

**Issue by FAKER-A** [ElemeFE/element#7177]
### Element UI version
1.4.4

### OS/Browsers version
win10/google61

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/575/](https://jsfiddle.net/pj71jkyw/575/)

### Steps to reproduce
直接点击icon

### What is Expected?
当input被禁用过后，点击icon不会触发其点击事件

### What is actually happening?
点击icon会触发其点击事件

**Comment by Leopoldthecoder** [comment]
Input 是否被禁用和 icon 被点击后是否需要触发事件并不一定是对等的。这种情况请在点击回调中处理。
