### ISSUE TITLE
[Bug Report] Popovers don't work with elements that are not visible on initial page load via v-if

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#7181]
### Element UI version
1.4.4

### OS/Browsers version
All

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/bnvystdw/](https://jsfiddle.net/bnvystdw/)

### Steps to reproduce
It appears that if an element containing a popover is not rendered on initial page load because it's excluded via `v-if`, it won't show the popover when it's later added to DOM.

1. Create a popover and give it a ref
2. Place a button and have it reference the popover, but also bind it to a condition via `v-if` that is `false` on mount
3. Make the condition return `true` thus enabling the button
4. Attempt to trigger the popover

It is possible to circumvent this by hiding the activators with `v-show` instead of `v-if`.

### What is Expected?
The popover should trigger

### What is actually happening?
The popover is not triggered

**Comment by smares** [comment]
I think what I am looking for is using a `manual` trigger and a custom property as popover `v-model`.

**Comment by Tofandel** [comment]
That is still a bug, the events being added on mounted to the reference but with a v-if, the reference doesn't exist when it is mounted

The events should be reloaded everytime the component is updated rather than on mount
