### ISSUE TITLE
[Bug Report] Bug in el-select when multiple is toggled

### ISSUE THREAD

**Issue by dinony** [ElemeFE/element#7183]
### Element UI version
1.4.4

### OS/Browsers version
macOS Sierra 10.12.6 / Firefox 55.0.3

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/dinony/kk9rrc30/](https://jsfiddle.net/dinony/kk9rrc30/)

### Steps to reproduce
First issue:
1. Open jsfiddle
2. Click on 'Allow multiple' checkbox
3. Observe that input element and el-tag are overlapping

Second issue:
1. Open jsfiddle
2. Click on 'Allow multiple' checkbox
3. Click on select component to see option and choose option: 'very long option that causes overflow when displayed as el-tag'

### What is Expected?
First issue:
It is expected that el-tag is displayed and the input is resetted.

Second issue:
It is expected that the tag does not overflow.

### What is actually happening?
First issue:
The input is still displayed resulting in a visual overlap of input and el-tag component.

Second issue:
Long tag name results in overflow.

**Comment by Leopoldthecoder** [comment]
Select doesn't support dynamic `multiple`. For the long tag, you can add `overflow: auto` to `.el-select__tags`.

**Comment by dinony** [comment]
Hi, thanks for your response and for your work!
I've updated the [fiddle](https://jsfiddle.net/dinony/ntqso2pf/) to not use dynamic multiple property. Repeat the steps I've described for issue 1 and observe that there is still the problem. This might be due to vdom. Also, this solution, besides not solving the issue, forces the consumer to duplicate html, so a dynamic multiple feature would actually be nice. Do you have any advice on how I could solve this issue?

Your suggestion to solve the second issue, solves the overflow but still has other issues. Repeat the steps I've described for issue 2 and observe that the long option cannot be cleared anymore via the el-tag, since the 'x' button is hidden. I'm sure that this issue will be encountered also by other users of your library. An individual solution delegates the task to solve this issue on all users, who are affected by this, therefore, I would suggest to think about an option to handle this issue. E.g. there could be a word limit option with overflow ellipsis. Or the select component could be dynamically sized. What do you think about this?

**Comment by Leopoldthecoder** [comment]
For the first problem, you can add `key` to both Selects to force a re-render.

The second one can be solved by adding your own CSS.

https://jsfiddle.net/ntqso2pf/8/

**Comment by dinony** [comment]
Thanks for the hint with key! But the code duplication is still obvious. 
To the second problem: sure, but that will be re-implemented by all users that are affected by this issue.
