### ISSUE TITLE
input-number 输入一个数字后 后面的字符就不受限了。

### ISSUE THREAD

**Issue by chs97** [ElemeFE/element#719]
如题。如何让input-number 或者 Input受限于数字？

**Comment by jikkai** [comment]
@baiyaaaaa 这个可能是个bug，官网example可以复现出来，rc8的InputNumber在数字后面输入非数字也可以
![image](https://cloud.githubusercontent.com/assets/14025786/19834536/6d538ea4-9e9e-11e6-8c10-f03a9898df00.png)

**Comment by baiyaaaaa** [comment]
@chs97 @jikkai 现在的input-number输入字符后并没有改变这个绑定值，不算是个bug。这个特点是经过考虑的，由于允许输入小数的情况，好像还没有办法直接限制为只能输入数字，例如，输入 `1.`的时候这个小数的中间状态不是整形，但你不能阻止别人不能输入，否则就没办法输入小数了 。

**Comment by chs97** [comment]
@baiyaaaaa 谢谢，这样的话，如果那个地方必须填数字，金额保留2个小数，有什么比较好的办法没？

**Comment by baiyaaaaa** [comment]
@chs97 input-number 估计没有办法替你做太多事情，保留几位小数这种校验逻辑只能由调用者去做了。关于上面提到的，目前如果 input-number 输入了一个非整形类型的值是无效的，其绑定值还是上一个有效的值，最好的情况只能是，在输入框失焦的时候组件将输入框内显示的值重置最近一个有效值。目前不会自动重置，下一个版本会优化这个体验

**Comment by chs97** [comment]
@baiyaaaaa 好的，谢谢。

**Comment by chs97** [comment]
大概可以 每次改变数据用一个正则去匹配，失败就还原改变之前的状态。
