### ISSUE TITLE
[Bug Report] Using Ionicons in Element UI

### ISSUE THREAD

**Issue by tehg00se** [ElemeFE/element#7191]
### Element UI version
1.4.5

### OS/Browsers version
OSX Sierra / Chrome 60.0.3112.113

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/6yjhm9su/1/](https://jsfiddle.net/6yjhm9su/1/)

### Steps to reproduce
-  Added custom CSS included at the bottom of http://element.eleme.io/#/en-US/component/icon
-  Added Ionicons to SCSS (they work in a regular i tag)
-  Referenced Ionicons as font-family in CSS (correctly pathed and referenced)
-  Assigned Icon to <el-icon> element
-  Code in browser is <i class="el-icon-undefined" icon="ion-ios-home"></i>

### What is Expected?
For the el-icon to return one of the Ionicons.

### What is actually happening?
The el-icon is returning el-icon-undefined.

**Comment by Leopoldthecoder** [comment]
Actually that part of documentation is for icon attributes. If you're using icons in a slot, you don't have to do any extra setup: https://jsfiddle.net/6yjhm9su/2/
