### ISSUE TITLE
The [Bug Report] DateTimePicker date time picker did not display as expected

### ISSUE THREAD

**Issue by lilong7676** [ElemeFE/element#7192]
### Element UI version
1.4.5

### OS/Browsers version
windows 10 /chrome 61

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/lilong7676/pj71jkyw/577/](https://jsfiddle.net/lilong7676/pj71jkyw/577/)

### Steps to reproduce
1.点击input。
2.直接点击日期时间选择器的确定按钮。
3.再次点击input, 更改一下选择器的时间（注意不要更改日期）， 然后点击确定。

### What is Expected?
input输入框内的时间变化。

### What is actually happening?
input输入框内的时间没有变化。

**Comment by Leopoldthecoder** [comment]
已在下个大版本中修复，请等待发布。

**Comment by SidKwok** [comment]
你在选择了时间的之后是不是忘了按确定了？

**Comment by lilong7676** [comment]
不是的 ，点了确定 ，时间仍然没变化。
