### ISSUE TITLE
[Feature, Request], el-select, support, multi, select, text

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#7197]
### Existing Component
是

### Component Name
el-select

### Description
select 组件多选状态，选择了多个选项是，不展示 tag ，而是展示选中了 xx  个这种形式，类似 http://davidstutz.github.io/bootstrap-multiselect/ 选择多个后显示 ` x selected` 这样
![image](https://user-images.githubusercontent.com/6936358/30796089-2906fd08-a203-11e7-9946-45bb7f7c4b9b.png)
like: https://monterail.github.io/vue-multiselect/
使用场景是：需要多选选择框，但是由于布局需要高度必须固定显示一行的高度。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by Yuliang-Lee** [comment]
@Leopoldthecoder 请问能否给一份 el-select 组件的 common2 规范编译过后的源码，我自己修改？

**Comment by Yuliang-Lee** [comment]
Ps: Feature implement in v2.0.5 (https://github.com/ElemeFE/element/issues/8190)
