### ISSUE TITLE
[Bug Report] DateTimePicker bug

### ISSUE THREAD

**Issue by wq599263163** [ElemeFE/element#7200]
### Element UI version
1.4.5

### OS/Browsers version
6.0

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
先选择好时间日期，然后再打开单独改时间，不会触发change 事件

### What is Expected?
改变时间应该触发的

### What is actually happening?
改变时间不触发

**Comment by Leopoldthecoder** [comment]
点击「确定」后会触发。
