### ISSUE TITLE
[Bug Report] upload plug-in, delete the picture before adding the confirmation, whether to delete the pop-up, can not prevent the deletion

### ISSUE THREAD

**Issue by kongjiea** [ElemeFE/element#7204]
### Element UI version
1.4.4

### OS/Browsers version
谷歌

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/578/](https://jsfiddle.net/pj71jkyw/578/)

### Steps to reproduce
点击删除图片，有一个确认弹窗，选择确认才删除图片

### What is Expected?
确认弹窗 点击确认才删除图片，取消是不删除图片的

### What is actually happening?
点击取消也删除了图片

**Comment by Leopoldthecoder** [comment]
`on-remove` 本身就是在删除文件后才触发。

**Comment by kongjiea** [comment]
能否增加一个先触发事件，再删除的钩子么？

**Comment by kongjiea** [comment]
@Leopoldthecoder 能否增加一个先触发事件，再删除的钩子么？

**Comment by zhuangsheng** [comment]
支持增加删除前确认动作

**Comment by xiaoniezi** [comment]
up up up
