### ISSUE TITLE
[Bug Report] About el-table,How do I make table height display as a percentage?

### ISSUE THREAD

**Issue by zhaipanyu** [ElemeFE/element#7205]
### Element UI version
1.4.5

### OS/Browsers version
10.10.5

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/54arxpq5/](https://jsfiddle.net/54arxpq5/)

### Steps to reproduce
https://jsfiddle.net/54arxpq5/

### What is Expected?
像max-height="580"高度会设死,.怎么使表格高度跟随屏幕的百分比,比如max-height="80%".那表格高度就是父控件的80%高度

### What is actually happening?
不同分辨率的屏幕高度表格不统一.影响布局

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/54arxpq5/1/ 用 CSS 解决。

**Comment by zhaipanyu** [comment]
thank you so much  ,解决了我的表格随屏幕不同分辨率自适应百分比的高度的需求
