### ISSUE TITLE
MessageBox的alert、confirm里的按钮没有自动获得焦点

### ISSUE THREAD

**Issue by terranc** [ElemeFE/element#721]
在浏览器里alert、confirm等弹出框里的主按钮会自动获得焦点，其后的操作可以『回车』、『空格』触发，这样会加快很多操作效率，比如删除多个而无批量删除的场景下，就不必鼠标频繁左右移动了。
而现在element里没有实现，导致习惯『空格』的我。。。。

**Comment by baiyaaaaa** [comment]
fixed in #728

**Comment by Leopoldthecoder** [comment]
已添加。

**Comment by meiliTang** [comment]
怎么去掉这个自动获取焦点呢
