### ISSUE TITLE
[Feature Request] use all variables from date.vue object through date-picker opt

### ISSUE THREAD

**Issue by newbie78** [ElemeFE/element#7212]
### Existing Component
Yes

### Component Name
date-picker

### Description
i set :picker-options="{ firstDayOfWeek: 1, year: '1980' }" but after a second selection it is reset to 1980 even if another one is selected. Can I somehow turn off the reset to the default value of pickerOptions?
Why :picker-options reset any second?

tnx

**Comment by Leopoldthecoder** [comment]
I don't think I understand this. `picker-option` doesn't support a `year` field.

**Comment by wacky6** [comment]
@Leopoldthecoder Internally, date-picker copies all properties in `picker-option` to underlying panel.

See `updatePicker` in `picker.vue`.

**Comment by Leopoldthecoder** [comment]
Yes, but properties not listed on the docs are not supposed to be used in `picker-option`.

**Comment by newbie78** [comment]
yes, they are not in the documentation, but it would be very convenient to use them

**Comment by wacky6** [comment]
You can get picker instance through `picker` property on the component. Of course you can play with it if that makes you happy. 😄 

I am reworking on *-picker's internal implementation. You may be able to control picker's behavior through a few props in element 2.0.

**Comment by newbie78** [comment]
thank you very much!
for vuejs the best set of components from you =)

**Comment by newbie78** [comment]
I do not understand how to connect the date-picker sources to the project to experiment with the settings.
if I do import DatePicker from 'element-ui/packages/date-picker/index'
I get the error: https://yadi.sk/i/WYUFroeb3P6nNK
how to do it right?

**Comment by Leopoldthecoder** [comment]
You need to set up JSX support for your project. See the 3rd question of [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md).

**Comment by newbie78** [comment]
i'm install plugins: https://yadi.sk/i/DuXdNbJu3P7oP4
set the babelrc:
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": [
    ["component", [
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]],
    "transform-runtime",
    "transform-vue-jsx"
  ],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
```
but got the same error again.

**Comment by wacky6** [comment]
If you just want to play with DatePicker:
1. `yarn dev` in element's folder,
2. play with `examples/docs/en-US/date-picker.md`, modify the code inside.
3. refresh the page

**Comment by wacky6** [comment]
You may also want to have a look at import on demand section: http://element.eleme.io/2.0/#/en-US/component/quickstart
