### ISSUE TITLE
[Feature, Request], el-table, summary-method cannot add components

### ISSUE THREAD

**Issue by wushi-777** [ElemeFE/element#7214]
### Existing Component
Yes

### Component Name
Table

### Description
在使用总计时, 需要在总计行的某一列中引入el-select组件，根据选择对总计值做重算。

如：在总计行加入一个可选择币种的列，选择不同的币种，总计金额发生相应的变化。　

目前在官方文档中没有发现有相关用法的介绍，尝试在summary-method中return相关内容，显示为纯文本格式。

**Comment by Leopoldthecoder** [comment]
不支持这种用法，建议将 Select 放在表格外部。

**Comment by renjunlincn** [comment]
我应该遇到了类似的问题，el-input 可以使summary重新计算，el-checkbox改变数据后summary不能重新计算。我解决的办法就是在el-checkbox的change事件中对table的data重新赋值。
