### ISSUE TITLE
一个版本错误？el-row和el-col失效的问题

### ISSUE THREAD

**Issue by ukhack** [ElemeFE/element#7215]
直接在页面引用了最新的index.js和index.css
<head><link rel="stylesheet" href="css/index.css"/></head>
` 
	<body>
		<el-row>
			<el-col :span="12">
				<div class="grid-content bg-purple"></div>
			</el-col>
			<el-col :span="12">
				<div class="grid-content bg-purple-light"></div>
			</el-col>
		</el-row>
		<style>
			.el-row {
				margin-bottom: 20px;
				&:last-child {
					margin-bottom: 0;
				}
			}
			
			.el-col {
				border-radius: 4px;
			}
			
			.bg-purple-dark {
				background: #99a9bf;
			}
			
			.bg-purple {
				background: #d3dce6;
			}
			
			.bg-purple-light {
				background: #e5e9f2;
			}
			
			.grid-content {
				border-radius: 4px;
				min-height: 36px;
			}
			
			.row-bg {
				padding: 10px 0;
				background-color: #f9fafc;
			}
		</style>
		<script type="text/javascript" src="js/vue.js"></script>
		<script type="text/javascript" src="js/index.js"></script>
	</body>`
直接拷贝了你们layout的文档，但是ele-col居然是换行的？？在doc官网点击在线运行，页面也是换行的。

**Comment by shauvet** [comment]
这个问题我也遇到了，从1.4升到2.0就这样，题主解决了没
