### ISSUE TITLE
The [Bug Report] cascader component searches for exceptions when the 1.4.3 version appears in the props non default value, and the 1.4.5 version still has the problem

### ISSUE THREAD

**Issue by povs2012** [ElemeFE/element#7218]
### Element UI version
1.4.3

### OS/Browsers version
win7/Chrome 60.0.3112.113

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/skovd94z/3/](https://jsfiddle.net/skovd94z/3/)

### Steps to reproduce
1、使用官方的cascader测试用例，设置props为非默认值，如{value: 'id', label: 'name'}
2、在cascader搜索框内输入关键字检索

### What is Expected?
检索过滤出过滤后的数据

### What is actually happening?
过滤后的数据被蓝色背景覆盖，无法查看

**Comment by Leopoldthecoder** [comment]
Fixed in #7225
