### ISSUE TITLE
Table-column Attributes中的selectable怎么写呢

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#722]
### OS/Browers version

Chrome 53
### Vue version

2.0.3
### What is actually happening?

仅对 type=selection 的列有效，类型为 Function，Function 的返回值用来决定这一行的 CheckBox 是否可以勾选。
官方文档这么写，那这个function该怎么写，返回什么值能让这一行的CheckBox 勾选

**Comment by Leopoldthecoder** [comment]
写了个 [例子](https://jsfiddle.net/leopoldthecuber/gmve9d3p/40/)，可以参考一下。

**Comment by kopheece** [comment]
谢谢 Leopoldthecoder！ 如何点击一行（不是CheckBox列） 使改行被选中呢

**Comment by kopheece** [comment]
@Leopoldthecoder 如何点击一行（不是CheckBox列） 使改行被选中呢或者是选中，点击改行就取消选中

**Comment by Leopoldthecoder** [comment]
可以在 `cell-click` 事件回调中改变该行的 `$selected`

**Comment by kopheece** [comment]
@Leopoldthecoder 谢谢 
在测试中发现个另外的问题，可以帮忙看看么。
[https://codepen.io/kophhece/pen/jMjBRB](url)这边是链接
现在点击任一行，可以实现选中或者取消选中，但是最左边的CheckBox现在却选择不了（意思是：比如方框想打勾选中，却点不了）

**Comment by Leopoldthecoder** [comment]
https://codepen.io/anon/pen/rMEmwq?editors=1111
作一个判断就好，45 行。

**Comment by kopheece** [comment]
@Leopoldthecoder 谢谢 刚在你给的例子中  发现个问题，必现的 
操作如下：
重新进入https://codepen.io/anon/pen/rMEmwq?editors=1111
然后一次点击4行数据（不是点每行前面的checkbox，比如点击第二列 第三列的），此时4行数据全部选中，
然后此时在随机点击任一行第一列的checkbox，看打印出来的multipleSelection变为空，按理来说，应该得有另外三行的数据。
重新进入这个页面，按照以上操作就会出现这个问题，如果没重新进入或者没刷新，按照上述的步骤操作第二遍就不会出现问题。

**Comment by Leopoldthecoder** [comment]
https://codepen.io/leopoldthecoder/pen/jMjXpr
修改了 `cellClick` 方法。按之前的思路可能不太好实现，需要调用 `Table` 内部的一些方法。

**Comment by kopheece** [comment]
@Leopoldthecoder 赞 十分感谢大神

**Comment by kopheece** [comment]
@Leopoldthecoder 在问下  在rc8中 show-tooltip-when-overflow貌似不起作用 
例子 ：http://codepen.io/kophhece/pen/jMjBRB

**Comment by Leopoldthecoder** [comment]
是的，已知 bug，在 #717 中修复了，随下个版本发布。

**Comment by FAKER-A** [comment]
大神  我想请教一下  如果一个表格的数据是 [1,2,3,4,5,6]  我想让[3,4]这两条数据不可以被选择我该怎么写呢 @Leopoldthecoder
