### ISSUE TITLE
The [Bug Report] Tree control, the current-change event, is the same as node-click

### ISSUE THREAD

**Issue by K-walker** [ElemeFE/element#7220]
### Element UI version
1.4.5

### OS/Browsers version
win7 / chrome 50 

### Vue version
2.4.4

### Reproduction Link
[Demo](https://jsfiddle.net/2c3vkzyw/)

### Steps to reproduce
单击node结点（不点击checkbox）发现current-change事件被调用，感觉跟node-click事件效果一样，而官方API上是这样介绍的：当前选中结点变化时触发的事件。按照我的理解，不应该是点击当前结点的checkbox才会触发这个事件吗？

### What is Expected?
点击node结点不触发current-change事件，当点击结点的checkbox时才触发

### What is actually happening?
点击结点current-click触发，点击checkbox没有触发

**Comment by Leopoldthecoder** [comment]
`current-change` 指的是当前高亮的节点，和是否展开无关。点击 checkbox 触发的是 `check-change` 事件。

**Comment by K-walker** [comment]
@Leopoldthecoder 谢谢，个人觉得这个API上的解释有点让人产生模糊，我觉得可以稍微修改一下文档。望采纳。
