### ISSUE TITLE
[Feature, Request], In vue's plugin, MessageBox can't create custom html of content

### ISSUE THREAD

**Issue by wxy678** [ElemeFE/element#7222]
### Existing Component
Yes

### Component Name
MessageBox

### Description
在通过install方法编写的Vue插件中，使用$msgbox自定义html内容时，message的类型为VNode，而Vue.prototype.$createElement实例是不存在的。
请教如何在插件中，使用Vue.prototype.$msgbox自定义html内容？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
