### ISSUE TITLE
The disable function of the [Bug Report] tree component is not working properly

### ISSUE THREAD

**Issue by dohkoxiaozu** [ElemeFE/element#7223]
### Element UI version
1.4.5

### OS/Browsers version
win7 / Chrome 55

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/vitorDeng/67zgbzp8/](https://jsfiddle.net/vitorDeng/67zgbzp8/)

### Steps to reproduce
无

### What is Expected?
...

### What is actually happening?
无

**Comment by Leopoldthecoder** [comment]
Fixed in #7226
