### ISSUE TITLE
[Feature Request] Require Splitter 

### ISSUE THREAD

**Issue by hnviradiya** [ElemeFE/element#7230]
### Existing Component
No

### Component Name
Splitter

### Description
We require one important component. That is splitter as it is a basic need.

We can take inspiration from following as splitter is part of their apache license.
http://demos.telerik.com/kendo-ui/splitter/index

Refer following for licensing.
https://github.com/telerik/kendo-ui-core

I can help if we are willing to implement this.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to add this.
