### ISSUE TITLE
[Bug Report] DateTimePicker brokes if *{box-sizing: border-box}

### ISSUE THREAD

**Issue by FrankFang** [ElemeFE/element#7232]
### Element UI version
1.3.3

### OS/Browsers version
macOS / Chrome 60

### Vue version
2.4.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/580/](https://jsfiddle.net/pj71jkyw/580/)

### Steps to reproduce
1. click in the input
2. select a time
3. see the bug

### What is Expected?
Perfect UI

### What is actually happening?
Broken UI

![image](https://user-images.githubusercontent.com/839559/30874159-238d2828-a322-11e7-92e4-a8dfe2cfe5f9.png)

**Comment by furybean** [comment]
@FrankFang Sorry, we don't have plan to support this recently.
