### ISSUE TITLE
文档左侧目录和右侧内容的滚动条建议分开滚动

### ISSUE THREAD

**Issue by hzsrc** [ElemeFE/element#7234]
http://element.eleme.io这个地址的文档，每次左侧点击一个目录菜单，都会滚动到页面顶端，如果想看下一个目录菜单的内容，必须滚动页面半天才找得到，体验很不好。建议左右2个滚动条，各管各的。

**Comment by wacky6** [comment]
建议 open。 这个 feature 可以有

**Comment by Leopoldthecoder** [comment]
有有有，昨天刚跟设计师说这个，下一个大版本就这么改。

**Comment by mu-yu** [comment]
http://element.eleme.io 的文档是不是该更新下了…现在还是1.2.3…

**Comment by Leopoldthecoder** [comment]
@mu-yu 清下缓存。

**Comment by Leopoldthecoder** [comment]
文档两个部分分别滚动的需求已在 #7281 实现，会随 2.0 的第一个 alpha 版本上线。

**Comment by mu-yu** [comment]
这个缓存牛逼了…Ctrl+F5都清不了…还得开发者工具Application->Clear storage才行。终于看到更新的文档了……
