### ISSUE TITLE
Element 2.0 即将到来

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7236]
今天，我们很高兴地宣布 Element 2.0 即将到来。

2.0 版本的更新内容会在今后的一段时间内陆续公开。今天首先来聊一聊 2.0 的版本代号和新主题。

细心的你可能已经注意到了，从 Element 1.0 开始，每个 minor 版本都会有一个版本代号，它们是：

- [1.0.0 Hydrogen](https://github.com/ElemeFE/element/releases/tag/v1.0.0)
- [1.1.0 Helium](https://github.com/ElemeFE/element/releases/tag/v1.1.0)
- [1.2.0 Lithium](https://github.com/ElemeFE/element/releases/tag/v1.2.0)
- [1.3.0 Beryllium](https://github.com/ElemeFE/element/releases/tag/v1.3.0)
- [1.4.0 Boron](https://github.com/ElemeFE/element/releases/tag/v1.4.0)

目前的五个版本代号是元素周期表中的前五个化学元素名。因此，2.0 版本的代号就是第六个元素：

![main](https://user-images.githubusercontent.com/10095631/30895083-76060d3c-a30d-11e7-8e0c-c7f04049b63d.png)

##

配合 2.0 版本，我们重新设计了一套全新主题：`theme-chalk`，中文名为白垩。作为预览，以下是白垩中时间范围选择的 DatePicker 组件：

![image](https://user-images.githubusercontent.com/10095631/30895331-2b9eafa4-a30f-11e7-98d9-43da273a0689.png)

##

我们很快会发布 2.0 的第一个 alpha 版本，届时会公布更多信息，敬请期待。

**Comment by shangxinbo** [comment]
看到这种命名方式就有种恶心的感觉

**Comment by Nick-Tsao** [comment]
跟我念 白(bai) 垩(e) 白鹅 白鹅

**Comment by 892390760** [comment]
外卖厂以食物命名比较有特色，哈哈哈

**Comment by lojzes** [comment]
太激动了，赶紧到来哦！

**Comment by cliveli** [comment]
同位素怎么办？

**Comment by shirenjiuhao** [comment]
鸡动啦，哈哈哈。现在1.x的版本用的还不错

**Comment by littleLane** [comment]
持续关注中。。。

**Comment by leimingzhang** [comment]
还是白色的？

**Comment by michaelzx** [comment]
有时间表吗？

**Comment by mdaima** [comment]
期待

**Comment by cajan** [comment]
明明可以水果命名非要周期表，能不能有个个性~~

**Comment by Ppsj** [comment]
可喜可贺。1.X用的很不错。然后如果有加强表格的方面就可以借鉴一下咯~

**Comment by JohnnyLuv** [comment]
所以饿厂套件的结束就是周期表的尽头~=-=

**Comment by bobiscool** [comment]
cool

**Comment by chikara-chan** [comment]
congratulation

**Comment by FightingDao** [comment]
饿厂有意思

**Comment by rhinonan** [comment]
很好~

**Comment by MissCuriosity** [comment]
之前发现了一个checkbox的bug，不知道2.0里修复了没有

**Comment by Scent-of-a-Woman** [comment]
厉害了  就是标签名很恶心

**Comment by PanJiaChen** [comment]
到头来只给了一张2.0截图 :weary:

**Comment by wangkang666** [comment]
以后用vue首选element

**Comment by DC-Setsuna** [comment]
一定要加强TABLE呀啊啊啊啊

**Comment by fishpaw** [comment]
祝贺，感觉后续版本可以用食物中的营养元素命名，这样和「饿了么」有关联，而且和「Element」这个词本身也有联系。

**Comment by zouyongjian** [comment]
这命名。。

**Comment by yesvods** [comment]
食物名称可以找SuperFood呀，随机出称心的版本代号~ https://github.com/yesvods/superfood

**Comment by AdaBlog** [comment]
期待期待，加一点滚动条的个性设置吧

**Comment by liunewshine** [comment]
1.0的真的很丑,比iview丑很多,不得不覆写n多css,期待2.0界面能好些

**Comment by Becavalier** [comment]
Cool!

**Comment by qinouz** [comment]
cool

**Comment by ibufu** [comment]
iview 也没好看到哪里去

**Comment by xuelong1993** [comment]
1.0的真的很丑,时间空间更是难用，尤其是时分秒的滑动选择  还有select的异步加载使用功能不好用 等等等

**Comment by whcrow** [comment]
建议用食物命名。

**Comment by lxmbetterman** [comment]
什么时候文档可用啊？

**Comment by YongX** [comment]
据说 2.0 还会补全控件的可访问性 💃 🎉

**Comment by zexiplus** [comment]
凑个热闹，希望新版可定制程度更高

**Comment by uxclouder** [comment]
快发布吧

**Comment by xiaoxiaojx** [comment]
很好， 但是我用ANTD

**Comment by ibufu** [comment]
👏👏👏👏👏👏👏👏

**Comment by tangxiangmin** [comment]
小板凳围观

**Comment by llpgy0724** [comment]
加油，你们太棒了

**Comment by JanlyH** [comment]
期待

**Comment by mzy1205** [comment]
666

**Comment by moonou** [comment]
期待，好像前几天打开element.io弹出过carbon这张图

**Comment by mirari** [comment]
日期选择器什么时候可以加上多选功能，现在只能单选或按范围选

**Comment by justyeh** [comment]
颜色用的太淡，圆角也用的太多了！

**Comment by xiaoxiaojx** [comment]
COOL, if i use vue

**Comment by lyh2668** [comment]
鹅厂....所以叫白鹅？

**Comment by funlake** [comment]
开源需要更多掌声，那些吹毛求疵的，你们是每天都贡献了代码还是怎么滴？

**Comment by qiuguixin** [comment]
评论是湿湿的

**Comment by wangqi0716** [comment]
不知道与1.4是否兼容？

**Comment by zhongyue2332** [comment]
希望能添加返回顶部，块级按钮
还有轮播图效果太少，loading状态太少
表单元素的那些size能否改成size=[height,width]自定义宽高？

**Comment by dachengzi000** [comment]
屌屌的

**Comment by GlemonGan** [comment]
难道跟我一样也做过仳学科代表

**Comment by qiuguixin** [comment]
table 富文本 模态框 常用layout 这些都可以参考下antd

**Comment by GlemonGan** [comment]
难道跟我一样也做过化学科代表

**Comment by liunewshine** [comment]
希望改进动画效果,在高分屏比如4k显示器下,动画会很卡. 但是jquery的动画在4k下就不卡

**Comment by GlemonGan** [comment]
希望新版本table能少点bug，现在用得很痛苦！

**Comment by rumAfor** [comment]
咩咩咩

**Comment by 2ming** [comment]
吓我一跳，文档网站弹了个大红框，我还以为中毒了

**Comment by Osirisblue** [comment]
难道大家没有发现，名称element本身就是“元素”，“元素周期表：element table”，用元素命名版本号不就是理所当然的咯。

**Comment by overflow-x** [comment]
支持

**Comment by Cyclone77** [comment]
支持一波 谢谢这么给力的框架

**Comment by ZHENGGEGE** [comment]
支持

**Comment by Cc9410** [comment]
emmmmmmmmmmmm
这个命名文案真的太中二了。。
为什么要这个名字。。。

**Comment by xnumb** [comment]
yeah!

**Comment by AlenQi** [comment]
啥时候出？

**Comment by yeesunday** [comment]
希望能同步更新一下 Sketch UI Kit~

**Comment by WormGirl** [comment]
中文文档官网进不去吖
![image](https://user-images.githubusercontent.com/16078260/30901841-e4ee2b38-a39b-11e7-83ae-d28019dff1f7.png)

**Comment by WormGirl** [comment]
是缓存的问题  版本迭代的问题  要清缓存才行呢

**Comment by Gxuebin** [comment]
好呀好呀

**Comment by atzcl** [comment]
的确好看多了，期待期待~

**Comment by KuiShang** [comment]
能出一个源码解读的文章吗

**Comment by lilong7676** [comment]
加油加油~~~~~~~~~~~~

**Comment by ai406136** [comment]
666以前的文档会保留吗

**Comment by GaoLoo** [comment]
开源不容易，加油

**Comment by zhuss** [comment]
必须附和一下了

**Comment by 1562428495** [comment]
最近碰到一个问题，在el-table上覆盖一个半透明的div，但是table的下边框和有边框却显示白线，请问如何消除，有没有同伴碰到类似问题，求告知
![default](https://user-images.githubusercontent.com/10626297/30903970-1077ec4c-a3a3-11e7-8df2-b634d293f5d7.png)

**Comment by penggy** [comment]
我去, Issue 被这么用, 它同意了么?

**Comment by ricosmall** [comment]
看了新的时间控件图片，感觉有戏！

**Comment by 1562428495** [comment]
最近碰到一个问题，在el-table上覆盖一个半透明的div，但是table的下边框和有边框却显示白线，请问如何消除， @Leopoldthecoder
![Uploading 边框.png…]()

**Comment by zuluoaaa** [comment]
很棒！

**Comment by Fox-Valentin** [comment]
白垩...恐龙在哪里？

**Comment by 1562428495** [comment]
最近碰到一个问题，在el-table上覆盖一个半透明的div，但是table的下边框和有边框却显示白线，请问如何消除， @Leopoldthecoder
![default](https://user-images.githubusercontent.com/10626297/30904744-6a86f280-a3a5-11e7-99c8-127c91450457.png)

**Comment by tylerdong** [comment]
为啥不是包子，饺子，小笼包，小龙虾

**Comment by Tronsfey** [comment]
赞一个，比较关心2.0版本的api会不会有很多的breaking change从而造成升级困难

**Comment by ssshooter** [comment]
哇厉害了！

**Comment by baixiyang** [comment]
哇厉害了，希望支持多级谈窗。

**Comment by HanleyTang** [comment]
希望可以直接提供一套 后台管理模板，直接基于模板框架来开发。

**Comment by binlaniua** [comment]
对啊对啊，用菜名最版本多有特色

**Comment by FAKER-A** [comment]
带劲

**Comment by Acathur** [comment]
支持用菜名命名版本代号

**Comment by lxchuan12** [comment]
cool～持续关注～

**Comment by liuzhe9581** [comment]
期待tree支持单选和默认高亮

**Comment by mamachengcheng** [comment]
帅，希望早点出来～

**Comment by sqchenxiyuan** [comment]
帅帅的~~~

**Comment by EmKs** [comment]
厉害了，难怪这几天官网一直弹窗，刚才又弹出了一个coming

**Comment by bhaltair** [comment]
终于更新了

**Comment by SteveCruise** [comment]
我想知道对于饿了么有什么好处

**Comment by Henry-boter** [comment]
我就想问移动端优化如何？

**Comment by CPK1021** [comment]
组件做的不错，不过你们的APP超级会员真是垃圾，欺诈消费者，一生黑

**Comment by Coande** [comment]
难怪这几天弹个CARBON出来，当时还不知道CARBON什么鬼~~

**Comment by Mirror198829** [comment]
期待期待，有了element 开发效率杠杠的

**Comment by hezhongfeng** [comment]
@cajan 
老哥，你说要个性，然后还让人用食物啥的命名，我知道安卓都把甜点用的差不多了吧？

**Comment by c5ms** [comment]
很好的事情,为什么我开心不起来.

> 能0成本移植 1.4x么

**Comment by wjtGitHub** [comment]
我就问API会不会大改

**Comment by 47018222w8** [comment]
后端用的很嗨,期待~

**Comment by RCJ1993** [comment]
66的

**Comment by AlenWang** [comment]
@1562428495 你应该是重置了.v-modal这个样式了，看一下它的z-index

**Comment by AlenWang** [comment]
刚好要开始重构项目，快点公布吧

**Comment by AlenWang** [comment]
http://element.eleme.io/#官网在火狐浏览器有bug，现在是在发版吗？

**Comment by AlenWang** [comment]
![image](https://user-images.githubusercontent.com/12652985/30946425-96d1167c-a436-11e7-9c74-57976b431450.png)

**Comment by Erin-mm** [comment]
怪不得今天早上怎么都登不上网站……

**Comment by xinde** [comment]
网站打开好慢，希望能大部分兼容1.0

**Comment by 1562428495** [comment]
@AlenWang 非常感谢，我改了table的z-index就可以了

**Comment by AlenWang** [comment]
@1562428495 不客气，最近刚好帮别人排查过这个问题

**Comment by DanielWLam** [comment]
日期组件，左边和右边能不能独立一下，不要点左边，右边也跟着翻页

**Comment by cuihj** [comment]
希望兼容1.0

**Comment by zhixinpeng** [comment]
现在的版本真的一堆问题，有点不想用了，希望2能更给力点

**Comment by bangbang93** [comment]
中国人都是活的元素周期表，所以用元素周期表命名也能算食物吧【x

**Comment by licaikai** [comment]
满心期待，希望早点出来。----铁粉一枚

**Comment by ADgirl** [comment]
mint-ui能和element-ui这么好就行了，特别是文档。。。。

**Comment by mason-meng** [comment]
el-input 没有 绑键盘事件，不知道2.0补上了没

**Comment by mason-meng** [comment]
dialog应该添加一个配置项，是否在body中插入，遇到多模块的到时候，dialog总是有心无力

**Comment by waningflow** [comment]
元素周期表我背的可熟了

**Comment by GitXiaoLei** [comment]
good!

**Comment by hujz** [comment]
感谢分享，我希望使用起来更简单，不要那么打包什么的，小公司没专业前端

**Comment by pingcoolflag** [comment]
良心企业，赞！

**Comment by xiangshijian** [comment]
良心产品，不错

**Comment by anlovedota1** [comment]
先期待一波

**Comment by kouseisama** [comment]
牛逼

**Comment by 461255824** [comment]
快  快 快点发

**Comment by reverland** [comment]
Glad to hear about that!

**Comment by xyDiva** [comment]
期待！

@reverland 眼熟你哈哈

**Comment by qw789** [comment]
今天上不了官网了吗？

**Comment by fliu2476** [comment]
支持

**Comment by yuuk** [comment]
支持~

**Comment by dddreee** [comment]
感谢开源，加油！

**Comment by vincentotsai** [comment]
希望能贡献自己的知识

**Comment by Gnywin** [comment]
白饿鸡？ 希望这个版本问题少一点 嘿嘿嘿

**Comment by scscms** [comment]
**广东人民发来贺电！**

**Comment by ensean** [comment]
我居然还能背出来  碳氮氧氟氖，钠镁铝硅磷。。。

**Comment by MoveZZG** [comment]
好危险，差点就错过了

**Comment by srw962** [comment]
希望加上tree-grid。另外table把分页相关的元素集成进去

**Comment by xjx972709517** [comment]
日期选择还好，一旦用的是日期时间选择，就比较麻烦了，还需要自己重新写一个，还有时间范围选择也是如此，操作不简洁，界面也不够好看

**Comment by gelif** [comment]
求行内编辑功能

**Comment by gelif** [comment]
求弹层可移动功能

**Comment by Ka1evi** [comment]
网站访问速度太慢了，半天加载不出来有时候还会访问失败。

**Comment by sndwow** [comment]
激动，样式上能兼容ie10就好了，比如复选框打钩后，在IE上√的方向会垂直翻转。

**Comment by webfrontzhifei** [comment]
大版本，应该有什么大的改变吧，

**Comment by 1011cat** [comment]
希望能加上一个自定义右键菜单.

**Comment by RCJ1993** [comment]
为什么我的邮箱被轰炸了，所以到底什么时候出

**Comment by daiing** [comment]
关键是兼容1.0吗

**Comment by qq157788394** [comment]
跟1.X兼容么？

**Comment by zeerain** [comment]
兼容不兼容1.0啊？

**Comment by chping2125** [comment]
来个 feature list 呗

**Comment by XiaoNode** [comment]
用vue.js第一个UI套件就是element-ui，很好用，感觉很好，感谢你们的付出

**Comment by lodamemory** [comment]
很期待

**Comment by istobran** [comment]
这次不是愚人节了，期待哦👏👏👏

**Comment by gmaso** [comment]
大概啥时发2.0正式版哦？要新做个后台系统，来得及就可以直接上新了

**Comment by xiechao1211** [comment]
期待！

**Comment by limianhust** [comment]
现在用的感觉挺好的，要是表格功能再强大一点就更好了，比如表格可编辑之类的

**Comment by aixwlove** [comment]
考化学 还要考语文

**Comment by gaoj87** [comment]
期待 😄

**Comment by yinay** [comment]
饿了吗？，也白饿...哈哈.

**Comment by ttop5** [comment]
嘤嘤嘤~

**Comment by iamgrf** [comment]
好嘞

**Comment by AtticusLv** [comment]
刚从1.3升级到1.4就发现格式有不兼容。。。吓的赶紧降回去了

**Comment by lszxlong** [comment]
赞

**Comment by hjb510** [comment]
大哥说话不说重点,出了界面没有别的了吗?

**Comment by chenjink674** [comment]
最好的ui框架

**Comment by sRect** [comment]
非常期待

**Comment by fgcui1204** [comment]
这么框架好火呀，期待2.0.x

**Comment by kaiye** [comment]
请问新版本有没有类似 Semantic UI 的响应式 table？
https://semantic-ui.com/collections/table.html

**Comment by shjszwh** [comment]
舌尖上的微量元素表吗？

**Comment by PanJiaChen** [comment]
提前跑了一下 `carbon` 分支的代码，纯交互或者体验上来说并没觉得有很惊艳或者有很大的改变，新主题 `theme-chalk` 也没有特别的优雅。之前的一些痛点如 `table` 的问题感觉也并没有完全得到解决。不过当然具体的细节还是要等官方发布版本再来定夺。

**Comment by tigerui** [comment]
@PanJiaChen  老铁，截个图撒

**Comment by HejinYo** [comment]
弹出层太难用了，不是响应式的，按比例缩放很难看；遮罩也是牛逼到了1万，其他弹出层都是2000起累加，完全没有考虑使用其他组件的感受啊，弹出层状态下用其他的通知插件就在遮罩下面。。。希望这个版本加强吧，因为很多问题，所以主要用了iview弹出层和输入组件，用了el的表格

**Comment by falost** [comment]
北京程序猿发来贺涵

**Comment by evolutionjay** [comment]
协议还是 MIT 吗?

**Comment by tjfy1992** [comment]
震惊！！！某外卖大厂公然在产品中添加元素周期表！！！原因居然如此可怕...

**Comment by kem709394** [comment]
good！！！

**Comment by jsonpeter** [comment]
消息一发布，成都就发生5.4级地震了

**Comment by xue8710** [comment]
元素size最好能自定义，不然太大了，支持你们

**Comment by calamus0427** [comment]
时间选择器的daterange，起止日期只能是间隔一个月的哦，选择起/止则时间会一起变化

**Comment by wcgh** [comment]
element-ui/lib/theme-default/index.css 新版本里没有?

**Comment by ysfscream** [comment]
推荐用食物命名 😀

**Comment by Ignorantforce** [comment]
tree半选状态这块支持还很坑，希望能解决

**Comment by shjszwh** [comment]
舌尖上的元素周期表。原谅我的剧透。
