### ISSUE TITLE
Element 2.0 is coming soon

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7237]
Today we're excited to announce that Element 2.0 is coming soon.

More info about version 2.0 will be revealed in the coming weeks. Today let's take a look at the code name of version 2.0 and a new theme.

You may have noticed that from Element 1.0, each minor version has a code name:

- [1.0.0 Hydrogen](https://github.com/ElemeFE/element/releases/tag/v1.0.0)
- [1.1.0 Helium](https://github.com/ElemeFE/element/releases/tag/v1.1.0)
- [1.2.0 Lithium](https://github.com/ElemeFE/element/releases/tag/v1.2.0)
- [1.3.0 Beryllium](https://github.com/ElemeFE/element/releases/tag/v1.3.0)
- [1.4.0 Boron](https://github.com/ElemeFE/element/releases/tag/v1.4.0)

The current five code names are the first five element names in the periodic table. So, naturally the code name of Element 2.0 is the sixth element:

![main](https://user-images.githubusercontent.com/10095631/30895083-76060d3c-a30d-11e7-8e0c-c7f04049b63d.png)

##

In 2.0 we have designed a new theme: `theme-chalk`. As a preview, here's what range typed DatePicker looks like in `theme-chalk`:

![image](https://user-images.githubusercontent.com/10095631/30895391-925f2156-a30f-11e7-8a60-a7e437aa5792.png)

##

We'll release the first alpha of 2.0 very soon. So stay tuned.

**Comment by focusdada** [comment]
Look forward to CARBON!!!!

**Comment by shangxinbo** [comment]
the name make me sick! glade but uncomfortable!

**Comment by ole3021** [comment]
Looking for element-react v2.0

**Comment by Lalrinfela** [comment]
Very much looking forward to Element. Probably one of the best framework now days. Cheers!

**Comment by x4storm** [comment]
E.M.T

**Comment by gongpeione** [comment]
Awesome

**Comment by thearabbit** [comment]
👍

**Comment by SiddiquiImran** [comment]
👍

**Comment by bcsthecoder** [comment]
Looking forward.

**Comment by gassio** [comment]
Great news!
Looking forward for mobile support.

**Comment by vtimofeev** [comment]
Cool !!!

**Comment by RxAssim** [comment]
Cool guys ! Keep it up !!

**Comment by allfreelancers** [comment]
good news!

**Comment by luisv1308** [comment]
Great!

**Comment by foxted** [comment]
Awesome, the new theme looks promising!

**Comment by tomoki7** [comment]
YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY!!!!!!!!!

**Comment by blackinitial** [comment]
awesome, it's good news

**Comment by reverland** [comment]
Cheers

**Comment by kengres** [comment]
we love it already

**Comment by vincentotsai** [comment]
This is the most elegant framework i have ever used. Keep up the good work, bring  us more surprise!!

**Comment by islamjaidul** [comment]
Please make all the components faster then previous version. Specially slider component

**Comment by FalkoJoseph** [comment]
Looking forward! We're using Element. 👍

**Comment by webkitten** [comment]
Greate job!

**Comment by SiddiquiImran** [comment]
What is tentative release date ??

**Comment by dbilovd** [comment]
How can one contribute?

**Comment by sayedrafeeq** [comment]
Awesome, it's great news.

**Comment by gustavoquinalha** [comment]
Yeahh good news!

**Comment by SherlockStd** [comment]
Yeaaaaaaaaaaaaaaaah !!!!!!!!!!

**Comment by CamiloEspinoza** [comment]
Great News!!

**Comment by israeleriston** [comment]
yeeeaaaaaaaaaaaaaaaaah!!!

**Comment by saenzramiro** [comment]
Awesome!

**Comment by thearabbit** [comment]
could I see new feature/changelog?

**Comment by lucduong** [comment]
Awesome!

**Comment by newbie78** [comment]
Good News!

**Comment by stanNo1** [comment]
helllo word~

**Comment by Mark-L6n** [comment]
Will this version support responsive design?

**Comment by gluons** [comment]
> "the name makes me sick! glade but uncomfortable!"

But it makes me zinc. 😛

**Comment by neorganic** [comment]
When will Element UI support mobile devices ? (be responsive at least) ?
