### ISSUE TITLE
DatePicker shortcuts click events don't trigger onPick function

### ISSUE THREAD

**Issue by ParkerFiend** [ElemeFE/element#7238]
### Element UI version
1.4.5

### OS/Browsers version
windows x64/chrome 61.0.3163.79

### Vue version
2.4.0

### Reproduction Link
[https://codepen.io/ParkerFiend/pen/WZpOma](https://codepen.io/ParkerFiend/pen/WZpOma)

### Steps to reproduce
click the shortcuts

### What is Expected?
onPick event trigger

### What is actually happening?
nothing happened

**Comment by syn-zeta** [comment]
Are you noticing any errors in the JavaScript console when clicking on the shortcuts? Not reproducible on Win7 Chrome Version 61.0.3163.100 (32-bit):

![7238](https://user-images.githubusercontent.com/26761352/30987062-8410c456-a44a-11e7-8d6b-44a79052293d.gif)

**Comment by ParkerFiend** [comment]
Sorry, I see nothing on my console. 
Do you mean the onPick function is designed to be ignored when clicking on the shortcuts?

**Comment by syn-zeta** [comment]
@ParkerFiend Never mind, I misunderstood the issue. This does seem like a bug as the documentation for `onPick` states that it is
> a callback that triggers when the seleted [selected] date is changed

Although that can be interpreted in a way to not make it a bug depending on what is meant by "selected." For now, if you would like to trigger a method when the shortcuts are clicked, you [could use the `@change` event on the component](https://codepen.io/anon/pen/gGRvpd).

**Comment by ParkerFiend** [comment]
@syn-zeta Thanks, I will use the `@change` to replace this method. 
By the way, should I close this issue?

**Comment by syn-zeta** [comment]
@ParkerFiend Let's ask a maintainer what they think about the wording in the documentation for ranged type datepicker's `onPick` attribute.

@Leopoldthecoder

**Comment by furybean** [comment]
@syn-zeta is right. You should use change event when you want to watch value change.

**Comment by ImArtur** [comment]
Horrible documentation about the picker, Use change event..

**Comment by syn-zeta** [comment]
@ImArtur Would you like to submit a PR to clarify it?
