### ISSUE TITLE
[Feature Request] expects Popover to support multiple references

### ISSUE THREAD

**Issue by Syes-K** [ElemeFE/element#7239]
### Existing Component
是

### Component Name
popover

### Description
 &lt;el-popover  ref="popover1" placement="top-start" title="标题" width="200" trigger="hover" content="this is content">&lt;/el-popover>

&lt;button v-popover:popover1>btn1&lt;/button>

&lt;button v-popover:popover1>btn2&lt;/button>

只在第2个button上起作用

export default {

       bind(el, binding, vnode) {

              vnode.context.$refs[binding.arg].$refs.reference = el;

       }

};

reference 是否能够改为一个数组，而不是一个对象呢

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by syn-zeta** [comment]
A hack for future readers: https://jsfiddle.net/hsymu9bk/1/

**Comment by yiwuyu** [comment]
@syn-zeta good job
