### ISSUE TITLE
[Bug Report] Cascader cascade selector, after setting props, search problem

### ISSUE THREAD

**Issue by hongxiangWang** [ElemeFE/element#7240]
### Element UI version
1.4.5

### OS/Browsers version
macOS10.12.6/11.0

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/ipop/eu7ra98v/2/](https://jsfiddle.net/ipop/eu7ra98v/2/)

### Steps to reproduce
现在为bug状态，输入关键字搜索，搜索结果不正常，
恢复正常步骤：去掉props 或者 props = {
                    label: "label",
                    value: "value",
                }

### What is Expected?
修复

### What is actually happening?
不知道该怎么修复

**Comment by Leopoldthecoder** [comment]
已经修复这个问题，今天晚些时候会发布。
