### ISSUE TITLE
After the [Feature Request] Cascader cascade selector sets the change-on-select, you can click any parent option to put the column in full

### ISSUE THREAD

**Issue by hongxiangWang** [ElemeFE/element#7242]
### Existing Component
是

### Component Name
Cascade

### Description
现阶段Cascader 级联选择器设置change-on-select后，点击任意一级父选项，change事件是有反馈，但希望能够，点击任意一级父选项，将展开列收起来，或者有什么close()方法

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
