### ISSUE TITLE
Does the callback of the [Feature Request] Cascader change event return object?

### ISSUE THREAD

**Issue by hongxiangWang** [ElemeFE/element#7244]
### Existing Component
是

### Component Name
Cascade

### Description
Cascader change事件的callback 是否能够返回object，这样好取对象的值。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by leekafai** [comment]
@hongxiangWang 可以在value绑定的值中设置data键来保存这个对象的自身。我在这个data键中保存了对象自身以及他在数组中的index，在动态加载下一级时可以很方便地添加children
