### ISSUE TITLE
[Bug Report] Invalid prop: type check failed for prop "width". Expected Number, got String

### ISSUE THREAD

**Issue by avinash-mishra** [ElemeFE/element#7248]
### Element UI version
1.4.6

### OS/Browsers version
Ubuntu 16.04/ Chrome version 60

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/avi_02/dtkLj6ep/](https://jsfiddle.net/avi_02/dtkLj6ep/)

### Steps to reproduce
Check console output of inspect element. 
https://jsfiddle.net/avi_02/dtkLj6ep/

### What is Expected?
Should be able to provide width with an integer value. 

### What is actually happening?
Invalid prop: type check failed for prop "width". Expected Number, got String

**Comment by Leopoldthecoder** [comment]
You need to add a colon: https://jsfiddle.net/leopoldthecuber/dtkLj6ep/3/

**Comment by avinash-mishra** [comment]
Thanks
