### ISSUE TITLE
[Question] How to select  between date on daterange using e2e test.

### ISSUE THREAD

**Issue by guruparanun** [ElemeFE/element#7249]
### Existing Component
Yes

### Component Name
DateRange

### Description
I am a e2e tester. and i have no idea about how to click select date when attibute 'editable' is false.
Please suggest a way how can i select between date on daterange when attibute 'editable' is false.
Or other way.

Thank in advance.

**Comment by Leopoldthecoder** [comment]
Do you mean to open the dropdown when `editable` is false? I think clicking the icon will do the job.

![image](https://user-images.githubusercontent.com/10095631/30947021-f7e296b2-a3cc-11e7-81b3-511ff67adca7.png)
