### ISSUE TITLE
select销毁时，消耗性能大，为什么页面跳转时会去销毁select？

### ISSUE THREAD

**Issue by tuotuogenjudi** [ElemeFE/element#7255]
# select销毁时，消耗性能大

页面1有select有大量的值，当跳转其它页面时，devTools会产生大量的resetIndex和destroyOption，造成页面卡吨5-6s,cpu飙升到100%，请问element UI select为什么会卡，win7系统，4G内存，chrome 60，vue2.4.4；

**Comment by Leopoldthecoder** [comment]
这个问题会在 2.0 中得到解决。
