### ISSUE TITLE
[Bug Report] the change event of el-select is different from native select

### ISSUE THREAD

**Issue by qidaneix** [ElemeFE/element#7257]
### Element UI version
1.4.6

### OS/Browsers version
windows/chrome 60

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/xiaodabao/5w1z0eya/5/](https://jsfiddle.net/xiaodabao/5w1z0eya/5/)

### Steps to reproduce
对于select选择框，有时需要在js中做重置v-model的值的操作，但是在js中改变v-model绑定的属性的值的时候，el-select的change命令也会被触发，而原生的select的change命令则不会。
请问如何解决？谢谢

### What is Expected?
在js中改变值不会触发change命令

### What is actually happening?
在js中改变值触发了change命令

**Comment by wacky6** [comment]
Should be fixed in element 2.0, see https://github.com/ElemeFE/element/pull/5360

**Comment by qidaneix** [comment]
@wacky6 1.x版本有办法fix吗？

**Comment by Leopoldthecoder** [comment]
1.x 不会做这个修改了，因为属于非兼容性的改动。你可以用一个 flag 来控制是否执行相关代码。
