### ISSUE TITLE
[Bug Report] in Dialog the attribute :modal-append-to-body="true" is not append modal to body element. Modal element always stay inside Dialog's parent element.

### ISSUE THREAD

**Issue by maqrat** [ElemeFE/element#7259]
### Element UI version
1.4.4

### OS/Browsers version
Cromium Version 61.0.3163.79 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Vue version
2.4.4

### Reproduction Link
[https://codepen.io/maqrat/pen/NapJWj](https://codepen.io/maqrat/pen/NapJWj)

### Steps to reproduce
click on el-button  'click to open the Dialog'
  

### What is Expected?
Element with class="el-dialog__wrapper" is append to body element somewhere near of element with class="v-modal".

### What is actually happening?
Modal element with class="el-dialog__wrapper" is always stay inside Dialog's parent element.

**Comment by Leopoldthecoder** [comment]
`modal-append-to-body` means to append the backdrop to body, not the Dialog itself. Admittedly the name is confusing and misleading, we'll see if we're going to change it in Element 2.0.

Speaking of Element 2.0, we'll have another prop `append-to-body` that does just what you need.
