### ISSUE TITLE
When [Bug, Report], select enters new values, you cannot press enter or select new input to display in the select box

### ISSUE THREAD

**Issue by tuotuogenjudi** [ElemeFE/element#7262]
### Element UI version
1.4.6

### OS/Browsers version
mac air / chrome 63.0

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/zuorui/rggdnao4/](https://jsfiddle.net/zuorui/rggdnao4/)

### Steps to reproduce
可输入的select, 当输入下拉框不存在的值的时候，必须按enter键，或者选择输入的值才能显示到select中，否则，数据会变为之前的值；顺便说一下，我现在用的是filter-method，勉强实现，但是这个方法消耗性能很大，在devTools中产生大量resetIndex和destroyOption；

### What is Expected?
在select中输入值时，当输入框失去焦点的时候也能赋值

### What is actually happening?
在select中输入新值时，输入框失去焦点的时候不能赋值

**Comment by Leopoldthecoder** [comment]
你的 demo 404 了

**Comment by tuotuogenjudi** [comment]
@Leopoldthecoder ，demo恢复了，https://jsfiddle.net/zuorui/rggdnao4/

**Comment by Leopoldthecoder** [comment]
Select 是需要一个明确的确认动作的，如果你需要在 blur 时选中值，可能 `<el-autocomplete>` 更适合。

**Comment by uniquejava** [comment]
终于找到相关的issue了, 

我的理解: 如果加了`allow-create`就是让el-select 兼具input和select两种控件的功能,  那么用户就会把它当成input来用, 如果在input中输入了值, 按tab切到下一个控件, 输入的值应该是需要保留的.

@Leopoldthecoder 是否考虑, 当allow-create为true的时候tab键默认也触发确认动作.

用这个控件的用户(allow-create)不约而同地对tab丢掉输入文本的行为感到surprise.
