### ISSUE TITLE
[Feature Request] el-upload requirements recommendation

### ISSUE THREAD

**Issue by K-walker** [ElemeFE/element#7265]
### Existing Component
否

### Component Name
el-upload

### Description
目前的 el-upload 组件，能不能提供一个属性，可以让每次选择的文件总是覆盖上次选择的文件，而不是出现多个，实现单个文件上传。目前好像没有这个功能。因为在平时，单个文件上传还是用的很多的。

**Comment by cepljxiongjun** [comment]
beforeAvatarUpload 可以限制上传数，单个可以删除重新上传

**Comment by K-walker** [comment]
@cepljxiongjun  文档里没有这个属性啊，具体怎样使用，下面列表只会出现一个吗？

**Comment by K-walker** [comment]
@cepljxiongjun  我自己改了下源码，添加了一个single属性，来控制是否是单文件上传，哈哈

**Comment by cepljxiongjun** [comment]
https://jsfiddle.net/kk3m04dg/12/ 大概是这样子

**Comment by K-walker** [comment]
@cepljxiongjun  但是用户体验不是很好啊，这个还要手动去删除，我们需求是主动覆盖的
