### ISSUE TITLE
[Bug Report]Select can't be dismissed by ESC key

### ISSUE THREAD

**Issue by fantasybei** [ElemeFE/element#7270]
### Element UI version
1.4.5

### OS/Browsers version
macOS 10.12. 6/Chrome 61.0.3163.100

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/fantasybei/ov1qpwgk/1/](https://jsfiddle.net/fantasybei/ov1qpwgk/1/)

### Steps to reproduce
click in the middle of the select control to activate the select option and then press esc on keyboard, the options will disappear.
But when you click on the down icon on the right side to activate the option, then press esc will not make the options disappear

### What is Expected?
the options of the select will disappear when options is activated by pressing  the down icon

### What is actually happening?
the options of the select doesn't disappear when options is activated by pressing  the down icon

**Comment by Leopoldthecoder** [comment]
This has been fixed in the 2.0 branch.
