### ISSUE TITLE
The form validation of [Bug Report] form verifies that resetFields () resets the form without entering the form, and then this.$refs[formName].validate appears wrong and then chooses select. The first time the wrong message is chosen, it doesn't go away

### ISSUE THREAD

**Issue by shoung6** [ElemeFE/element#7272]
### Element UI version
1.4.6

### OS/Browsers version
win10

### Vue version
2.4.4

### Reproduction Link
[http://element.eleme.io/#/zh-CN/component/form](http://element.eleme.io/#/zh-CN/component/form)

### Steps to reproduce
重现链接里的官方示例的表单验证部分做如下操作
1.没有操作表单的情况下点击重置。
2.点击立即创建，活动区域出现‘请选择活动区域’的报错。
3.活动区域选择区域一，‘请选择活动区域’的报错不消失。
4.第二次选择活动区域，报错就消失了。

### What is Expected?
第一次选中活动区域后报错信息就消失

### What is actually happening?
第一次选中活动区域后报错信息没有消失

**Comment by tylerdong** [comment]
@element-bot 我也遇到这个问题

**Comment by kure2** [comment]
我也遇到这样的情况了

**Comment by wacky6** [comment]
@Leopoldthecoder 可能和 https://github.com/ElemeFE/element/issues/6011 有关？

FormItem 的 validateDisabled 是用来做什么的？感觉 https://github.com/ElemeFE/element/issues/6011 做完以后可以去掉？

**Comment by shoung6** [comment]
2.0也还有这个问题

**Comment by wacky6** [comment]
@shoung6 能给个2.0的复现链接吗？

**Comment by Leopoldthecoder** [comment]
Fixed in #7744
