### ISSUE TITLE
[Bug Report] EL-select search error in IE10

### ISSUE THREAD

**Issue by TIANTIANKUTAO** [ElemeFE/element#7285]
### Element UI version
1.2.9

### OS/Browsers version
IE10

### Vue version
2.4.4

### Reproduction Link
[https://github.com/ElemeFE/element/issues/7284](https://github.com/ElemeFE/element/issues/7284)

### Steps to reproduce
select选择框在有默认id（该默认值在列表中没有对应id和值）， 初始化的时候，第一次点击，会出现无匹配数据，第二次点击会出现列表 底部出现无匹配数据。IE情况下存在。谷歌则直接出现第二次的那种情况。

### What is Expected?
select选择框在有默认id（该默认值在列表中没有对应id和值）， 初始化的时候，第一次点击，会出现无匹配数据，第二次点击会出现列表 底部出现无匹配数据。IE情况下存在。谷歌则直接出现第二次的那种情况。

### What is actually happening?
是的

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
