### ISSUE TITLE
pagination  bug!!!

### ISSUE THREAD

**Issue by yuu2lee4** [ElemeFE/element#729]
当pagesizes选一个更大的数的时候 分页相应减少，这时候可能currenpage就变了，但是current-change并没有触发

**Comment by yuu2lee4** [comment]
或者size-change触发的时候  就算currenpage也跟着变了 不触发current-change也行 但是size-change的时候最好同时把currentPage也传回来

**Comment by QingWei-Li** [comment]
官网上的例子是触发的
![image](https://cloud.githubusercontent.com/assets/7565692/19835387/fadffe80-9ebf-11e6-8778-ee2f02dc2251.png)

麻烦给个例子？

**Comment by yuu2lee4** [comment]
你用最后那个完整功能的 你先选择300条 页码选择2  然后选择400条 然后页码就只剩1了对吧 但是并没有触发current-change  也就无所获取当前页码了。。。最好是size-change的时候同时把currentPage也传回来。。。

**Comment by yuu2lee4** [comment]
rc9  啥时候能发
![image](https://cloud.githubusercontent.com/assets/8046366/19835456/47a0ff24-9ec2-11e6-94d5-afcd8f4258a4.png)
