### ISSUE TITLE
el-pagination在vue2.4.4里无法正常使用，请帮忙看看什么问题

### ISSUE THREAD

**Issue by haiyupeter** [ElemeFE/element#7293]
<el-pagination @current-change="handleCurrentChange" :current-page.sync="1" :page-size="10" layout="total, prev, pager, next" :total="totalCount"></el-pagination>

**Comment by hexufeng** [comment]
无法正常使用是什么意思？ 是否这个问题： https://github.com/ElemeFE/element/issues/3188
