### ISSUE TITLE
When the collapse of [Bug Report] el-menu is true, click el-menu, and the tooltips is invalid

### ISSUE THREAD

**Issue by xinde** [ElemeFE/element#7296]
### Element UI version
1.4.6

### OS/Browsers version
win10

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/6f8p4odd/](https://jsfiddle.net/6f8p4odd/)

### Steps to reproduce
以上重现链接是官网demo,没有问题，试了下，线上重现不了，不知道咋回事，但是我本地用vue-cli生成的项目，就会出现 el-menu的collapse为true时，点击el-menu,tooltips失效

### What is Expected?
el-menu的collapse为true时，点击el-menu,tooltips有效

### What is actually happening?
el-menu的collapse为true时，点击el-menu,tooltips失效

**Comment by xinde** [comment]
![222](https://user-images.githubusercontent.com/1617414/31041617-ea72d15e-a5ca-11e7-93ca-085187a5b590.png)

**Comment by xinde** [comment]
![image](https://user-images.githubusercontent.com/1617414/31041682-115997ac-a5cc-11e7-8576-da0322640809.png)

怕是因为别的东西影响了，去掉其他重试还是这样

**Comment by Leopoldthecoder** [comment]
你使用的是 1.4.5 版本，这个版本中 Tooltip 有 bug，已在 1.4.6 中解决。升级到最新版就可以了。

**Comment by xinde** [comment]
升级后解决了，谢谢

**Comment by 641357534** [comment]
请问你是怎么解决的 ？我升级了最新版本菜单收缩后还是没有tooltip提示
