### ISSUE TITLE
Element 2.0.0-alpha.1 已发布 🎉

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7304]
### 更新日志

https://github.com/ElemeFE/element/releases/tag/v2.0.0-alpha.1

### 文档

http://element.eleme.io/2.0/#/zh-CN/component/installation

### 安装

```bash
npm install element-ui@next
```

```JS
import Vue from 'vue'
import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'

Vue.use(Element)
```

### 说明

`2.0.0-alpha.1` 版本包含了新主题的全部内容，欢迎各位安装预览。由于目前处于 alpha 阶段，所以不建议直接用在生产中。

`2.0.0-alpha.1` 并未包含全部的功能更新，部分组件（如 Table）仍在升级之中。接下来我们会继续强化组件功能，请大家耐心等待。

### 版本迁移

如果需要从 1.4 版本迁移到 2.0.0-alpha.1，请对照更新日志中的「非兼容性更新」部分进行修改。在 2.0.0 正式版发布时，我们希望能够提供一个迁移工具，方便各位迁移代码。

**Comment by hezhongfeng** [comment]
666
这么快就发了

**Comment by Jemair** [comment]
前排

**Comment by fallowu** [comment]
前排

**Comment by yelingfeng** [comment]
棒棒哒

**Comment by Trycle00** [comment]
巧了巧了。刚用着1就出2.

**Comment by jieblog** [comment]
哇 table 组件增强啦

**Comment by yoyo837** [comment]
1.x是否还会少量推出几个bugfix版本？

**Comment by fallowu** [comment]
没看到树形table

**Comment by Joshwoooooooooooooooooooooooooooooooong** [comment]
色调有点偏深啊

**Comment by nooldey** [comment]
2.0版的配色没有1.0+的好看啊，求维持原来的配色

**Comment by lk20072342** [comment]
Nice

**Comment by zhzpeng** [comment]
666

**Comment by Shruan** [comment]
前排

**Comment by Shruan** [comment]
发现2.0的居然没有适配手机

**Comment by dingyiming** [comment]
NICE,来看看，目前主用iview

**Comment by LiuXuFei** [comment]
很不错，使用中

**Comment by Deacyn-Dong** [comment]
点赞，这个主题看着蛮舒服的

**Comment by Janyet-Lee** [comment]
前排点赞

**Comment by RobertM574** [comment]
希望可以支持树形组件的拖拽功能，以及 两颗树的拖拽😀😀😀

**Comment by charmingoh** [comment]
颜色有点淡，感觉没有之前的好看

**Comment by yzsunlei** [comment]
厉害了，感觉UI变得细腻了，怎么还是没有可以拖拽的组件，不开心了

**Comment by yzsunlei** [comment]
可以弄几套完整的页面布局实例吗

**Comment by yzsunlei** [comment]
再点赞一次，哈哈

**Comment by chenjink674** [comment]
666,辛苦,强力支持~~

**Comment by niices** [comment]
还是更喜欢以前那种方方正正带点阴影的设计
比如这种- -
![image](https://user-images.githubusercontent.com/8327775/31052485-b26122da-a64b-11e7-9697-d635aab428c7.png)
这也是我坚持用element而不是iview的原因

**Comment by herechc** [comment]
棒棒哒

**Comment by lxchuan12** [comment]
cool~够迅速~点赞~

**Comment by getfirendsbyid** [comment]
不错，我喜欢

**Comment by yzsunlei** [comment]
色调方面最好不要改动太大

**Comment by tumobi** [comment]
希望出一个后台管理系统的基本框架

**Comment by yzsunlei** [comment]
@tumobi 非常赞同，我也提过了，哈哈

**Comment by shengjies** [comment]
刚准备学1，就出2了

**Comment by michaelzx** [comment]
希望样式上能继承1的优点，今天看了下2.0分页的组件。这个样式真是感觉有点……
不知道是不是2.0的网站的字体问题，看着莫名的有些不舒服
![image](https://user-images.githubusercontent.com/1799421/31083719-0ab50f52-a758-11e7-98d9-15e43c55af9f.png)

![image](https://user-images.githubusercontent.com/1799421/31083698-fe215e62-a757-11e7-8e4f-fa574842f793.png)

**Comment by yoyoping** [comment]
正在用1.4呢，新版本的确改了之前一些不合理的，很期待，希望正式发版的时候能提供一个好的迁移方式！！！

**Comment by KumaCool** [comment]
这是逼着我黄金周加班呀...＿|￣|○

**Comment by wmui** [comment]
留个名，支持一下

**Comment by EvanLiu2968** [comment]
功能上的改进很好，样式的修改怎么感觉还不如1.4了呢？

**Comment by LinShouGui** [comment]
厉害了大饿了么

**Comment by conanliuhuan** [comment]
# 求设计师改稿
浅蓝色为什么那么灰？按钮的蓝色完全就是白蒙蒙的呀，好难看……表格的样式也是白花花的。
2.0相比1.4来说增加了很多细节，这是值得肯定的。但希望可以继承一些1.4的样式，感觉2.0的部分设计不如1.4好

**Comment by wacky6** [comment]
我觉得1.0 的 theme-default 还可以抢救一下。

**Comment by Leopoldthecoder** [comment]
跟各位道个歉，由于我们的疏忽，目前主题的主色是错误的（应为 `#409EFF`，实为 `#69B3FF`），会在下个版本修复。

除此之外，白垩主题应该不会再有大的改动。关于 1.0 版本的 `theme-default`，如果各位的需求强烈，我们后面也会考虑。

**Comment by paiqiuafan** [comment]
東西好用

**Comment by iMaxSys** [comment]
支持外卖厂

**Comment by conanliuhuan** [comment]
自从用了element，外卖都再也不用美*了。良心外卖厂俘获了代码狗的心

**Comment by sndwow** [comment]
感觉1.4的样式好看多了，特别是通知组件。。

**Comment by ukhack** [comment]
之前不是说在2.0版本加入类似bootStrap的visible-xs、visible-sm、hidden-xs、hidden-sm这样的功能么？挺需要的，比较好几家Vue UI组件，目前都没有实现。希望element是第一家

**Comment by Y-Young** [comment]
新主题有点太冷淡了，还是喜欢现在的theme-default配色，Message组件也还是现在的好看，另外2.0貌似对手机的适配不如1.4了

**Comment by sailstar** [comment]
希望增加表格树，太需要了。

**Comment by dj20150624** [comment]
table表格的样式还有待优化，没有1.x系列的样式好看

**Comment by yiwuyu** [comment]
很多默认尺寸都太大了！

**Comment by cycold** [comment]
感觉
很多默认尺寸都太大了！
很多默认尺寸都太大了！
很多默认尺寸都太大了！
table 行默认高度可否调小一点 后台 都希望尽可能有多的空间来展示信息
按钮的默认尺寸 也大了 

最后特别感谢 感谢 感谢  饿了么推出这套UI框架 
外卖一直都用饿了么

**Comment by conanliuhuan** [comment]
不再支持IE9了吗？IE9打不开2.0的文档页面了，一片空

**Comment by zopk** [comment]
站好队！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
-> queqe

**Comment by RCJ1993** [comment]
过完国庆感觉世界都变了，看了下文档，改变好像没有想象中的多，不过已经很好了，希望在下个项目中用到

**Comment by 18055975947** [comment]
分页组件好坑啊。还希望改稿

**Comment by dj20150624** [comment]
Icon的图标觉得应该在添加一下实际应用的就更好了，就不用再使用其它的第三方的图标了

**Comment by kenberkeley** [comment]
为什么 iView 看起来比较精致？是因为小字体。。。所以建议 Element 也可以像 Ant Design 那样，小字体。。。

**Comment by CoderONER** [comment]
版本更新了那些内容～ 。是你们发了我没有看到 ？  还是你们没有发啊 ？？

**Comment by uncleLian** [comment]
增加了不少功能，但默认颜色没有以前好看吖，好像过于朴素了？

**Comment by Nunchakus888** [comment]
漂亮多了😄，功能更全了😄，点赞👍

**Comment by For-me** [comment]
求设计师再改改分页组件。。。跟1.4相比差太多。。

**Comment by hasbug** [comment]
元素变大  感觉有点粗糙。 同意上面几位朋友的看法，确实太大了。

**Comment by xunjianxiang** [comment]
设计师换人了吗？还是说设计师一直惦记十一黄金周呢？
![image](https://user-images.githubusercontent.com/12422146/31329041-caea680e-ac9d-11e7-978e-07b382eba560.png)
圆角取消掉这一点很符合预期，但是高亮颜色换为土豪金有点没法接受啊~~~

![image](https://user-images.githubusercontent.com/12422146/31329078-fd993776-ac9d-11e7-93d9-0151cf696427.png)
还有就是这个垂直方向的导航菜单，子菜单选中时，父级菜单并没有实现高亮

**Comment by a346721573** [comment]
很多默认尺寸都太大了！ 总要手动用小号。 树组件能支持单选吗

**Comment by rossroma** [comment]
table组件在Safari下依旧有兼容问题，没希望了吗？

**Comment by littleLane** [comment]
速度够快，节后上班第一天就关注，大大的惊喜

**Comment by Jokelu** [comment]
弹出框为什么不能拖动,希望dialog能拖动

**Comment by baoxianggao** [comment]
分页的样式改的也太坑了吧，希望能改回1.4的样式

**Comment by kenberkeley** [comment]
希望 Element 修改元素默认大小的童鞋，请点一下下方的大拇指

**Comment by webjiandong** [comment]
喜欢那个滚动条，能加上吗？

**Comment by YuJiusihuanian** [comment]
希望增加table可编辑状态，自增行列，可编辑状态，元素有些变大了，感觉粗糙了，还有出现Injection "elFormItem" not found问题

**Comment by WormGirl** [comment]
感觉没有之前的好看，是不是性能加强了，样式粗糙了，只是大概看了下样子，还没实际用，希望越做越好，加油加油

**Comment by spademan** [comment]
只想安静的使用1.x

**Comment by oufish** [comment]
希望有treeGrid。加油加油

**Comment by guoxianglian** [comment]
目前我个人封装了一个vue表格分组的组件，有需要可以联系我

**Comment by guoxianglian** [comment]
感觉element2样式没有1.4好看

**Comment by gaoj87** [comment]
theme-default 表示还可以抢救下

**Comment by IIInsomnia** [comment]
icon太少了；对话框能不能好看点，标题要是能支持icon就好了

**Comment by haosiguang** [comment]
input搜索按钮建议放右边

**Comment by haosiguang** [comment]
从1.46迁移到2.0，控制台出现“[Vue warn]: Injection "elFormItem" not found”警告，求解决

**Comment by haosiguang** [comment]
select下拉框多选情况下，能否支持全选功能，求支持

**Comment by fwchen** [comment]
从1.46迁移到2.0，控制台出现“[Vue warn]: Injection "elFormItem" not found”警告，求解决
 +1

**Comment by sRect** [comment]
table组件展开列的没有

**Comment by Leopoldthecoder** [comment]
> [Vue warn]: Injection "elFormItem" not found

这个问题请参考 https://github.com/vuejs/vue/pull/6322 。目前这个 PR 已经合并，看上去会随 Vue 2.5 发布，届时我们会跟进。

**Comment by ptians5119** [comment]
一个小问题，用到dropmenu，设置trigger=‘click’无效，最后跑到源文件里去修改才生效..

**Comment by kaileer** [comment]
Popover 那个框框像傻大个似得

**Comment by tuotuogenjudi** [comment]
[Vue warn]: Injection "elFormItem" not found

这个问题升级了vue2.5.2依旧还有这个错误
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@tuotuogenjudi 等我们发新版

**Comment by reatang** [comment]
希望能把UI做的纤细一点，现在的太粗犷了。

**Comment by afocus** [comment]
能不能默认的尺寸小一点啊 大的有点过头了

**Comment by Kelier** [comment]
Congratulations!🐵

**Comment by Leopoldthecoder** [comment]
如果觉得默认尺寸太大，现在可以方便地修改组件的默认尺寸了：https://github.com/ElemeFE/element/releases/tag/v2.0.0-alpha.3

**Comment by a346721573** [comment]
@Leopoldthecoder 点个赞，很理想。

**Comment by jean-lee** [comment]
小而精悍，细腻感来吧

**Comment by dongfangx** [comment]
666,一直在使用，希望增加table组件功能

**Comment by HoHoibin** [comment]
感觉新版的Notification没有1.4版本的好看啊

**Comment by liuzhaowei55** [comment]
* table 组件的默认行高太高了
* vue-cli 打包时，对布局容器 header，main 的 style padding 设置会被默认值覆盖，而开发模式下不会
* 希望所有的组件尺寸都可以再稍微小一点，紧凑点，会更精致把

**Comment by Kaijun** [comment]
请问新的主题是不是出自薛大师之手？感觉非常像！ 😄

**Comment by Leopoldthecoder** [comment]
@Kaijun 是的，看上去是你的前同事

**Comment by Kaijun** [comment]
@Leopoldthecoder 哈哈 一看设计风格就猜到是他啦 🤣

**Comment by Solliu** [comment]
@Kaijun 厉害厉害

**Comment by Kaijun** [comment]
@Solliu 没想到去了贵司 😆

**Comment by zhongzm** [comment]
[Vue warn]: Injection "elFormItem" not found
@Leopoldthecoder 这个错误大概什么时候发新版

**Comment by Leopoldthecoder** [comment]
@zhongzm 把 Vue 升到 2.5.2

**Comment by yeomanyang** [comment]
有迁移工具了么～～
