### ISSUE TITLE
Element 2.0.0-alpha.1 released 🎉

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7305]
### Changelog

https://github.com/ElemeFE/element/releases/tag/v2.0.0-alpha.1

### Documentation

http://element.eleme.io/2.0/#/en-US/component/installation

### Installation

```bash
npm install element-ui@next
```

```JS
import Vue from 'vue'
import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'

Vue.use(Element)
```

### Tips

`theme-chalk` is included in ` 2.0.0-alpha.1 `, feel free to try it out. It is not recommended to use this version in production though, because it's still in alpha stage.

Some components (e.g. Table) are still being upgraded, and we'll ship them in future releases. Thank you for your patience.

### Migration

If you wish to migrate from 1.4 to 2.0.0-alpha.1, please refer to the 'Breaking changes' section in changelog. When the final 2.0.0 version is released, we hope to be able to provide a migration tool for your convenience (fingers crossed).

**Comment by wvllvw** [comment]
thanks for the awesome work, please can you tell me how to migrate from version 1.4 to 2

**Comment by Leopoldthecoder** [comment]
@wvllvw Updated.

**Comment by wvllvw** [comment]
@Leopoldthecoder thank you brother, You're doing a great job.
my question isn't clear what I mean is updating Element in webpack

**Comment by Leopoldthecoder** [comment]
@wvllvw Basically you don't need to change anything in webpack config. Just uninstall 1.4 and install 2.0.0-alpha.1 (remember the `next` tag), and import `theme-chalk` instead of `theme-default`.

**Comment by takerushi** [comment]
Nice work!!!

**Comment by zzzgit** [comment]
validation related functionalities are still not good enough,`async-validation` should be gave up

**Comment by Chinese1904** [comment]
I am experiencing what seems like styling issues when pulling in only `npm i element-datepicker -S` and then importing the styles obviously `import 'element-ui/lib/theme-chalk/index.css'`.

Can anyone confirm datepicker is not working by itself with 2.0 alpha?

**Comment by doramart** [comment]
2.0单独引用 input 会报下面的错
`
[Vue warn]: Injection "elFormItem" not found

found in

---> <ElInput>
       <Root>
`
on-icon-click 属性失效
另外，单独引用下拉菜单也会报错。

**Comment by Leopoldthecoder** [comment]
@doramart 
- Input 的问题请参考 #7344 
- `on-icon-click` 已被移除，请参考更新日志
- Dropdown 的问题已经在 #7322 修复

**Comment by Leopoldthecoder** [comment]
@Chinese1904 We haven't updated the standalone packages. We'll do that when we come to the final release of 2.0.0.

**Comment by doramart** [comment]
![image](https://user-images.githubusercontent.com/11911066/31209109-6742eba8-a9bb-11e7-8b9f-0b706038e381.png)

message弹窗报错

**Comment by santiblanko** [comment]
Also in cards

**Comment by Chinese1904** [comment]
@Leopoldthecoder quick question, it seems like standalone packages have not been updated yet. Any eta on those? Thanks so much!
