### ISSUE TITLE
The start and stop dates for [Bug, Report], daterange, and datetimerange can only be chosen one month apart, as well as daterange validation rules

### ISSUE THREAD

**Issue by calamus0427** [ElemeFE/element#7310]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Chrome

### Vue version
2.4.4

### Reproduction Link
https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1.daterange  和 datetimerange 的起止日期只能选择相隔一个月的，修改终止日期，开始日期也会跟着变动为前一个月的，反之相同情况
2.daterange的表单为空验证规则是怎样的？有默认的type类型吗？还是只能通过自定义的方式

### What is Expected?
时间应该可以自由选择，二者没有关系

### What is actually happening?
时间应该可以自由选择，二者没有关系

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/31062102-b7211490-a6ed-11e7-905a-af9259c375b5.gif)
