### ISSUE TITLE
The [Bug, Report]table, type=, and expand menus are listed as fixed, and the unfolded menu contents overlap and show transparently in the fixed column

### ISSUE THREAD

**Issue by calamus0427** [ElemeFE/element#7311]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Chrome

### Vue version
2.4.4及以前的

### Reproduction Link
[https://jsfiddle.net/c7sguu2c/3/](https://jsfiddle.net/c7sguu2c/3/)

### Steps to reproduce
table type="expand" 菜单有列为fixed时展开菜单内容会重叠透明的展示在fixed那一列

### What is Expected?
1.fixed时折叠菜单内容和fixed那一列的边界线不应该重叠展示了
2.建议菜单的打开可以单列打开而不是整行添加，而且可以撑大当前行内容，尝试过通过折叠菜单的方式添加到table，但是也会导致未读fixed列没有被撑起，而且样式太丑，建议增加这样的组件功能

### What is actually happening?
1.table type="expand" 菜单有列为fixed时展开菜单内容会重叠透明的展示在fixed那一列
2.用折叠菜单的方式添加到table，fixed列的行没有被撑起而是跟没有打开折叠菜单一样的展示

**Comment by galipmedia** [comment]
You can make it look correct using z-index I have added one css class here ... 
https://jsfiddle.net/galipmedia/c7sguu2c/24/

**Comment by furybean** [comment]
这是实现的时候就考虑到的问题，当时的实现就决定了 type="expand" 无法与锁定列一块使用。

完整回答见这里：https://github.com/ElemeFE/element/issues/8994
