### ISSUE TITLE
Table表格动态列抛异常Error in render function: "TypeError: _self.$scopedSlots.default is not a function"

### ISSUE THREAD

**Issue by JesseHu1520** [ElemeFE/element#7312]
`<div class="msg_table">
                
                <el-table :data="msgList" border style="width: 100%;">
                    <el-table-column prop="name" label="短信名称"></el-table-column>
                    <el-table-column prop="content" label="正文"></el-table-column>
                    <el-table-column prop="addTime" label="创建日期"></el-table-column>
                    <el-table-column label="用户选择" v-if="type != 3">
                        <template scope="scope">
                            <span v-if="scope.row.userSelectType==1">用户标签</span>
                            <span v-if="scope.row.userSelectType==2">自定义名单</span>
                        </template>
                    </el-table-column>
                    <el-table-column prop="name" label="用户名单" v-if="type == 3">
                        <template scope="scope">
                            <a>发送成功名单</a>
                            <p>发送成功短信数：{{scope.row.sentUserCount}}</p>
                        </template>
                    </el-table-column>
                    <el-table-column prop="preSendTime" label="预设发送时间"></el-table-column>
                    <el-table-column prop="name" label="预览" v-if="type==0">
                        <template scope="scope">
                            <el-button>预览</el-button>
                        </template>
                    </el-table-column>
                    <el-table-column prop="name" label="已发送" v-if="type==1">
                        <template scope="scope">
                            {{scope.row.sentUserCount}}/{{scope.row.selectedUserCount}}
                        </template>
                    </el-table-column>
                    <el-table-column prop="completeTime" label="完成时间" v-if="type==3"></el-table-column>
                    <el-table-column label="操作" v-if="type != 3">
                        <template scope="scope">
                            <el-button v-if="type==0">编辑</el-button>
                            <el-button v-if="type==1">结束</el-button>
                        </template>
                    </el-table-column>
                </el-table>

            </div>`

**Comment by aflext** [comment]
最新版本也有这样的问题，怎么解决？

**Comment by wang22123467469** [comment]
请问解决了吗

**Comment by Cc9410** [comment]
https://forum.vuejs.org/t/weird-vuejs-error-with-elementui-table--self-scopedslots-default-is-not-a-function/12933

**Comment by zowiegong** [comment]
> you can add a key props to table like this:
> `<el-table key='aTable' v-if="firstTabActive"></el-table>`

**Comment by 1078559858** [comment]
> https://forum.vuejs.org/t/weird-vuejs-error-with-elementui-table--self-scopedslots-default-is-not-a-function/12933

完美解决！ 使用v-show代替v-if
