### ISSUE TITLE
[Feature Request] Make el-table-column width size proportional to its content

### ISSUE THREAD

**Issue by alvarolemos** [ElemeFE/element#7317]
### Existing Component
Yes

### Component Name
el-table-column

### Description
I'm working on a system that has lots of CRUD tables and I'd like their column width to be variable. Specifically, their width should fit its content. Right now, the Table-Column Attributes available doesn't support that. All the examples on the documentation uses hard-coded width, witch we rather not do in that particular project.

Is there something we are missing or this is not possible with the current API. And if it isn't, would you mind to make it possible?

Thanks in advance,

Álvaro

**Comment by huziyang410** [comment]
I have the same demand.

**Comment by ihoment-amu** [comment]
yeah , i think it 's fit of  the table attributes not working by the way. or fit isn't working depend on column's content.

**Comment by vgavro** [comment]
here is related issue with material-ui, I believe problems discussed there are same.
https://github.com/mui-org/material-ui/issues/1911

**Comment by furybean** [comment]
Sorry, we have no plan to support this.

**Comment by furybean** [comment]
Sorry, we have no plan to support this.

**Comment by atilkan** [comment]
@alvarolemos 
I needed something similar. A hacky way to do this. 

```
<el-table-column 
v-for="(item, index) in fields" 
:min-width="item.name.length * 6 + 50 + 'px'">
```

**Comment by mnm1001** [comment]
[ex-table-column](https://github.com/mnm1001/ex-table-column) can automatically adjust column width according to content.

Hope this can help you.

**Comment by valentinMERCIER** [comment]
No plan for re-opening this issue ?

**Comment by nicholasoxford** [comment]
Would love to have this

**Comment by astoliarov** [comment]
+1
This would be nice

**Comment by syJSdev** [comment]
+1

**Comment by cameron0myers** [comment]
Would be nice.

**Comment by BrandonMendoza** [comment]
Would be nice.

**Comment by alexanderkraemer** [comment]
Hey guys, I solved it by doing the following:
`<el-table-column v-if="assigneesWidth" :width="assigneesWidth">`

   ```
   getAssigneesWidth() {
      let maxWidth = 0
      this.rows.forEach(t => {
        if (t.content.length > maxWidth) {
          maxWidth = t.content.length
        }
      })
      // adding 20px width for padding
      this.assigneesWidth = (maxWidth + 20).toString() + 'px'
    },
```

I also had a watcher on the rows variable, so everytime this changed, i recalculated the width of the column.

**Comment by eloise-mcintyre** [comment]
This would be a great addition

**Comment by litoxy** [comment]
> This would be a great addition

I calc the header field width and 

> Hey guys, I solved it by doing the following:
> `<el-table-column v-if="contentWidth" :width="contentWidth">`
> 
> ```
> getContentWidth() {
>    let maxWidth = 0
>    this.rows.forEach(t => {
>      if (t.content.length > maxWidth) {
>        maxWidth = t.content.length
>      }
>    })
>    // adding 20px width for padding
>    this.contentWidth = (maxWidth + 20).toString() + 'px'
>  },
> ```
> 
> I also had a watcher on the rows variable, so everytime this changed, i recalculated the width of the column.

I did the same. But if the content is html, it will belch

**Comment by mygitnote** [comment]
it`s so bad.

**Comment by wll8** [comment]
Please use this UI library: https://www.antdv.com/components/table/

**Comment by jvalrog** [comment]
bad framework is bad

**Comment by vildanbina** [comment]
+1

**Comment by vildanbina** [comment]
2024 is starting and there is still no solution 😆

**Comment by FeiYanLeung** [comment]
```vue
<el-table-column  
  v-for="..."
  :key="..."
  :min-width="getColumnMinWidth('<column-label.text>')" />
```

```javascript
const V_CANVAS = document.createElement('canvas')
const V_CANVAS_CTX = V_CANVAS.getContext('2d')
V_CANVAS_CTX.font = '14px bold Helvetica Neue'

// It is also possible to add custom spacing
const V_CST_S_WIDTH = 0

export default {
    methods: {
        getColumnMinWidth(rawText = '', minWidth = 150){
            const textWidth = V_CST_S_WIDTH + V_CANVAS_CTX?.measureText(rawText)?.width 
            return (textWidth > minWidth ? textWidth : minWidth) + 'px'
       }  
   }
}
```
