### ISSUE TITLE
[Bug Report] this.domNode.setAttribute warning when trying to use el-menu with mode="horizontal"

### ISSUE THREAD

**Issue by ircop** [ElemeFE/element#7320]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Firefox 56.0 (32-bit), Windows 10 x86_64

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/L3hoynze/](https://jsfiddle.net/L3hoynze/)

### Steps to reproduce
Just see element's example: there is error in console

This is happens only if mode="horizontal" is set

[Vue warn]: Error in mounted hook: "TypeError: this.domNode.setAttribute is not a function"

found in

---> <ElMenu>
       <Settings2> at resources/assets/js/components/pages/Settings2.vue
         <ElMain>
           <ElContainer>... (1 recursive calls)
             <Root>

### What is Expected?
Clear JS without warnings

### What is actually happening?
JS warnings

**Comment by Leopoldthecoder** [comment]
Fixed in #7321

**Comment by ircop** [comment]
Thanks!
