### ISSUE TITLE
[Bug Report] Warning when using this.$confirm

### ISSUE THREAD

**Issue by ircop** [ElemeFE/element#7324]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Firefox 56.0 (32-bit) ; win10 x86_64

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/ftr4tu8q/](https://jsfiddle.net/ftr4tu8q/)

### Steps to reproduce
Reproductable in documentation example.

When opening dialog box, Vue warning is thrown: [Vue warn]: Injection "elFormItem" not found

### What is Expected?
Clearly working code without warnings

### What is actually happening?
Vuejs varnings

**Comment by Leopoldthecoder** [comment]
I'm afraid we'll have to wait for Vue to merge [this PR](https://github.com/vuejs/vue/pull/6322).

For now please ignore that warning, or downgrade Vue to 2.3.x.

**Comment by Chinese1904** [comment]
It seems merged and it's still happening on 2.5.2?
