### ISSUE TITLE
Does the [Feature Request] navigation component provide a way to support expansion and contraction of navigation bars?

### ISSUE THREAD

**Issue by rianran1993** [ElemeFE/element#7325]
### Existing Component
是

### Component Name
el-menu

### Description
导航组件能否提供一个方法支持展开和收缩导航栏,用编程方法来展开和收缩

**Comment by hanyuhh** [comment]
https://jsfiddle.net/uc906r7v/     el-menu bug 当鼠标快速把第一个打开的时候，从选项四划过选择选项1，el-menu 会突然消失，请问是因为 setTimeOut是原因么
