### ISSUE TITLE
[Feature Request] Allow keyboard-based tag addition

### ISSUE THREAD

**Issue by ffxsam** [ElemeFE/element#7328]
### Existing Component
Yes

### Component Name
Tag

### Description
It would be great to be able to add tags by using the keyboard only. E.g.:

1. Type "new"
2. Hit enter or comma.
3. "new" tag is added. Input field is still focused.
4. Type "sale item".
5. Hit enter or comma.
6. "sale item" tag is added.

This way, the user doesn't have to use the mouse to click "New Tag" every single time.

**Comment by Leopoldthecoder** [comment]
Actually you can modify that example with what we already have to implement your proposal.

**Comment by ffxsam** [comment]
@Leopoldthecoder Sorry, I'm not sure what that means. Are you saying there's some way to put tags inside an `<el-input>`?

**Comment by Leopoldthecoder** [comment]
@ffxsam Did you mean something like this? https://jsfiddle.net/leopoldthecuber/5rgnsg5r/

**Comment by ffxsam** [comment]
No, like this: https://ant.design/components/select/

(see the "Tags" example)

![licecap](https://user-images.githubusercontent.com/12532733/31062464-6d12114e-a6f0-11e7-8071-9580a40d5e09.gif)

**Comment by ffxsam** [comment]
Element's `<el-select>` with `allow-create` is similar. Except I can't hit enter, I have to click to choose the new item I'm typing.

**Comment by Leopoldthecoder** [comment]
Oh, I guess you need the `default-first-option` flag: https://jsfiddle.net/leopoldthecuber/rw43L0a9/

**Comment by ffxsam** [comment]
Ah, perfect! thanks! And great job on 2.0!

**Comment by ffxsam** [comment]
@Leopoldthecoder Just realized there's apparently a bug in this. (is it fixed in 2.0 maybe?)
 See below

![screencap](https://user-images.githubusercontent.com/12532733/31684265-bd59c010-b344-11e7-957f-6555a9ee43ac.gif)

**Comment by wacky6** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
This is actually by design. Suppose you want to select everyone named Jack from the list. You type 'Jack' and select the first one, and before you click the second Jack, the input clears and the list resets. You end up having to type 'Jack' each time you select a person.

That being said, there's still room for improvement. It seems to make sense to clear the input if there's only one matching option.

**Comment by ffxsam** [comment]
My personal take from a UX perspective is that it's not common behavior for dropdown menus. I can see the advantage for doing quick selections, but I think it should be an option.

**Comment by Leopoldthecoder** [comment]
I'm adding a new prop `reserve-keyword` to Select in Element 2.0. When set to false, the input will clear after selecting an option.

**Comment by ffxsam** [comment]
Awesome! Much appreciated
