### ISSUE TITLE
[Feature Request] How i catch the dom of row table to make effect transition?

### ISSUE THREAD

**Issue by blackinitial** [ElemeFE/element#7329]
### Existing Component
Yes

### Component Name
table

### Description
i make click 'choose' button in row, if clicked i catch dom of row and make move to bottom transition, how to select the dom of row? and how to get data in scope table-column?

**Comment by Leopoldthecoder** [comment]
You can try something like this: https://jsfiddle.net/leopoldthecuber/n9vvt1qr/

**Comment by blackinitial** [comment]
that's very helpful
