### ISSUE TITLE
[Bug Report] Checkbox value is null when sending form to Laravel

### ISSUE THREAD

**Issue by kamil-kielar** [ElemeFE/element#7335]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Chrome (Version 61.0.3163.100)

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/589/](https://jsfiddle.net/pj71jkyw/589/)

### Steps to reproduce
It happen when the form is submitted to Laravel framework.

### What is Expected?
I am experiencing a very strange issue with form submission when i am using Element UI framework.

I ve got checkbox:

  <el-checkbox v-model="checked" name="option" :value="checked">Option Selected</el-checkbox>
My Vue JS looks like:

 export default {

    data() {
        return {
            checked: false,
        };
    }
};

### What is actually happening?
When i am sending a form using Laravel the option in response is null.

Response:

    array:3 [▼
    "_token" => "TOKEN"
    "name" => "fgdjdgfhj"
    "option" => null
    ]
Default bootstrap checkbox, and hidden inputs works. Did any of you had similar problem?

I would like to mention the value is actually changing in Vue Dev tools but its not passing through laravel response.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
