### ISSUE TITLE
[Bug Report] Vue warn]: The data property "visibleArrow" is already declared as a prop. Use prop default value instead.

### ISSUE THREAD

**Issue by alexdee2007** [ElemeFE/element#7338]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Windows 7 Professional / Google Chrome 61.0.3163.100

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/m1ozezrc/](https://jsfiddle.net/m1ozezrc/)

### Steps to reproduce
Run the application and see console.

### What is Expected?
no errors or warn in console

### What is actually happening?
in console appears:

[Vue warn]: The data property "visibleArrow" is already declared as a prop. Use prop default value instead.
found in <ElDropdownMenu><ElDropdown>....

In file element-ui\packages\dropdown\src\dropdown-menu.vue passing a prop named "visibleArrow" (from mixins Popper) and using it to set the data properties of the Vue component. 
In mixins Popper "visibleArrow" is already declared as a prop, and this caused conflicting property name.

**Comment by Leopoldthecoder** [comment]
Fixed in #7322
