### ISSUE TITLE
[Feature Request] Make use of the right side space of Tab component

### ISSUE THREAD

**Issue by Centaur** [ElemeFE/element#7342]
### Existing Component
Yes

### Component Name
Tab

### Description
We just need one more slot, and can put components such as Breadcrumb, NavMenu, Dropdown, Search Form, etc. there.

See [the sementic-ui example](https://semantic-ui.com/collections/menu.html#tabular)

**Comment by wacky6** [comment]
Why not wrap tabs in div with flex style. Then you can put everything next to it.

**Comment by Centaur** [comment]
Unbelievable, have you guys even click the link I provided and tried to understand what I have suggested?  What is the reason that this issue is closed, when @wacky6's suggestion did not address the problem at all ?
