### ISSUE TITLE
[Bug Report] v-if does not work correctly in table

### ISSUE THREAD

**Issue by s2dent** [ElemeFE/element#7344]
### Element UI version
1.4.6

### OS/Browsers version
windows 7 64bit / chrome 59.0.3071.115

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/xbxtzL1o/1/](https://jsfiddle.net/xbxtzL1o/1/)

### Steps to reproduce
Use checkboxes to hide/unhide columns

### What is Expected?
v-if not working correctly with grouping table head

### What is actually happening?
Broken table layout

**Comment by julytian** [comment]
@s2dent ,you can use different key in every column, just like this.  https://jsfiddle.net/zd8vmos5/

**Comment by s2dent** [comment]
This solves the problem. Thank you so much!
