### ISSUE TITLE
[Bug Report] Select not clearing the placeholder.

### ISSUE THREAD

**Issue by ardian-c** [ElemeFE/element#7347]
### Element UI version
0.1.0

### OS/Browsers version
Windows 10/ Chrome 61.03

### Vue version
2.4.4

### Reproduction Link
[http://jsfiddle.com](http://jsfiddle.com)

### Steps to reproduce
I have an VueJs with Vuex application. When clearing the state, the field model is reset to null but the placeholder text still remains visible. The effect I want to achieve when clearing the fields is that of clicking the clear button, when making the select `clearable`. Is there a way to achieve this, as it is annoying to see the placeholder after model related to field is emptied. 

### What is Expected?
Select field label needs to be cleared when model is emptied, so no labels to be shown in that field, instead I need the default "Select" label to be shown.

### What is actually happening?
It shows the same option even after model is empty, the Shadow DOM has the same value. I want to achieve same effect as clicking the `clear` button when field is `clearable`.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly. You can create a repo on GitHub if it is not reproducible on JSFiddle.
