### ISSUE TITLE
[Feature Request] Form validation status

### ISSUE THREAD

**Issue by cgarnier** [ElemeFE/element#7348]
### Existing Component
Yes

### Component Name
Form

### Description
Hello,
When validation takes time, the user can make other actions (like saving)  before the model has been updated. Is it possible to get the validation status of the form ?

**Comment by Leopoldthecoder** [comment]
Are you validating the form on the server side?

**Comment by cgarnier** [comment]
Yes I do the both. But during the validation process on front side, if the
validation take time, the model can remain at the last value (Wich is a
correct value). So the guy click save, it re save the last value and there
is no way to know it.
It can append on slow computer when the validation of a field is slow.
For instance, I m validating a json textarea with a json schéma.

**Comment by cgarnier** [comment]
I can no more reproduce it. I think i mess with something.
