### ISSUE TITLE
表格有reload功能么？

### ISSUE THREAD

**Issue by kopheece** [ElemeFE/element#735]
### ElementUI version

1.0.0-rc.8
### OS/Browers version

Chrome 53
### Vue version

2.0.3
### What is actually happening?

貌似没看到表格的reload功能（用于重新加载远程数据）？

**Comment by isunkui** [comment]
自己写一个 刷新按钮 调用获取数据接口就可以做到的啊

**Comment by furybean** [comment]
是的，Table 本身不做数据加载，也就不存在 reload 的问题。
