### ISSUE TITLE
[Bug Report] El-buttons ignore disabled attribute

### ISSUE THREAD

**Issue by Nickolay9x** [ElemeFE/element#7350]
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Windows 10, Mozilla Firefox

### Vue version
2.4.4

### Reproduction Link
[jsfiddle.net/aa4xv7j1/1/](https://jsfiddle.net/aa4xv7j1/1/)

### Steps to reproduce
Create el-button with :disabled true or false. Then click on them.
Create simple button with the same attributes and click on them.

### What is Expected?
If you click enabled button you'll see alert. If you click disabled button you'll see nothing.

### What is actually happening?
I've seen only style changes. All el-buttons emitted click event and ignored disabled attribute. But simple buttons works correct.

**Comment by Leopoldthecoder** [comment]
Ah, thanks for reporting, fixed in #7352.
