### ISSUE TITLE
[Bug Report] Upload component does not show file names when using manual HTTP handler

### ISSUE THREAD

**Issue by mach-kernel** [ElemeFE/element#7356]
### Element UI version
1.4.6

### OS/Browsers version
OS X 10.11 / Chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/597/](https://jsfiddle.net/pj71jkyw/597/)

### Steps to reproduce
Implement a custom HTTP handler as per the documentation
Push the file to the list of files

### What is Expected?
The file name shows up once it is pushed to the list of files

### What is actually happening?
The file name does not show up. I have to do the spread + merge operation as shown in the fiddle.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/990/
