### ISSUE TITLE
[Feature Request] Ordering of tabs

### ISSUE THREAD

**Issue by foxted** [ElemeFE/element#7364]
### Existing Component
Yes

### Component Name
Tabs

### Description
I have been trying to create tabs based on list of resources received from the server, which have sequential IDs. The problem is, the tab panes seem to be ordered based on their label. It would be nice to be able to specify the order of the tab pane, like `:order=1` to manually order them.

**Comment by Leopoldthecoder** [comment]
You need to order the array before passing it to Tabs: https://jsfiddle.net/leopoldthecuber/h83d2rqa/

**Comment by foxted** [comment]
My array was ordered. There was another limitation: `<el-tab-pane>` must be immediate children of `<el-tabs>` for the order to be respected. I had my `<el-tab-pane>` encapsulated in another `<div>`. Manually control the order would be better to customize the template more.
