### ISSUE TITLE
[Feature Request] Floating Labels

### ISSUE THREAD

**Issue by DomenicRoti** [ElemeFE/element#7365]
### Existing Component
Yes

### Component Name
Input

### Description
In the Sketch files it shows inputs with "floating labels", however I can't find any documentation on this.  Is this implemented, if not it would be a great feature.

I'm attaching a screenshot of the input, it was listed under "Special Usuage"

![image](https://user-images.githubusercontent.com/1099200/31241208-7480dcbc-a9c0-11e7-9e9f-122faee22235.png)

**Comment by gramlin** [comment]
Been looking for a floating-label for element. I've been toying around with this;
https://github.com/bkzl/vue-float-label
which works fine for Input, not at all for el-select and date...

**Comment by wacky6** [comment]
select and date are wrapped in `<div>`, you may need to modify `vue-float-label` to get is working with them.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
