### ISSUE TITLE
[Feature Request] Add footer slot for cards

### ISSUE THREAD

**Issue by ircop** [ElemeFE/element#7372]
### Existing Component
Yes

### Component Name
el-cadr

### Description
It would be great, if el-card has `footer` slot - for submit/cancel buttons, etc.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can already add submit/cancel buttons in the default slot.

**Comment by tnerbovik** [comment]
@ircop it is easy to make your own based on the original

https://jsfiddle.net/tnerbovik/Ln1ajwv5/1/
