### ISSUE TITLE
[Bug Report] select remote, when option's value is object, cannot display the label correctly

### ISSUE THREAD

**Issue by mingbai2006** [ElemeFE/element#7373]
### Element UI version
1.4.6

### OS/Browsers version
Windows 10/Chrome 61

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/gh1f1tx2/3/](https://jsfiddle.net/gh1f1tx2/3/)

### Steps to reproduce
select remote ，当option的value是object时，无法正确地显示label

### What is Expected?
显示label

### What is actually happening?
label没有显示

**Comment by Leopoldthecoder** [comment]
不是 bug，初始状态下 `options4` 为空，虽然 `value9` 有值，但是组件并不知道要拿这个对象的哪个字段显示在输入框内。只有组件的 `label` 属性有了明确的值（即 `options4` 有对应于 `value9` 中对象的选项）时才能显示。建议初始化一下 `options4`。
