### ISSUE TITLE
[Bug Report] Submit Form behavior cannot prevent with 1 input form

### ISSUE THREAD

**Issue by hckhanh** [ElemeFE/element#7376]
### Element UI version
1.4.6

### OS/Browsers version
Windows 10

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/zdmfm43k/](https://jsfiddle.net/zdmfm43k/)

### Steps to reproduce
1. Create a el-form with 2 el-form-item (1 el-input and 1 el-button)
2. Select el-input
3. Press enter.

### What is Expected?
The submit action should not be triggered

### What is actually happening?
The native submit action is triggered and cannot be prevented or stopped
You can see it in Number Validate example here:
http://element.eleme.io/?#/en-US/component/form

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/zdmfm43k/1/

**Comment by seqid** [comment]
`<el-form :inline="true" @submit.native.prevent>`
