### ISSUE TITLE
[Bug Report] ERROR in static/js/vendor.0a24f6378ca6d110025f.js from UglifyJs Unexpected token: punc (() [./~/element-ui/packages/col/src/col.js:23,0]

### ISSUE THREAD

**Issue by TonyLuo** [ElemeFE/element#7377]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
Mac OS/Chrome

### Vue version
2.4.4

### Reproduction Link
[https://elementui.github.io](https://elementui.github.io)

### Steps to reproduce
 run the build command : npm run build

### What is Expected?
no error

### What is actually happening?
ERROR in static/js/vendor.0a24f6378ca6d110025f.js from UglifyJs
Unexpected token: punc (() [./~/element-ui/packages/col/src/col.js:23,0]

**Comment by Leopoldthecoder** [comment]
#5176
