### ISSUE TITLE
[Feature Request]  Control the Data Transfer Direction in Transfer Component

### ISSUE THREAD

**Issue by sureshbala** [ElemeFE/element#7379]
### Existing Component
Yes

### Component Name
Transfer

### Description
Currently the Transfer Component offers both Left To Right & Right To Left transfers. In case of Data transfer required in only one direction, the Transfer Component doesn't help as there is no option to control the data flow.

**Comment by wacky6** [comment]
Right now, you can hide the buttons. But I am not sure where such feature can be used in real world.
https://jsfiddle.net/96z773b7/

What if user makes mistakes and there is no way for reverting a transfer action?

**Comment by sureshbala** [comment]
Thank you @wacky6 

Yeah, I could do that. But given the number of Element UI Components, building a unidirectional Transfer component did not take much time. 

In the case where I do not need a transfer from Right To Left, hiding the button does the job but having a checkbox for the items in the Right section might confuse the users. So, I have gone ahead and built a small component that suits my requirement, screenshot attached.
<img width="960" alt="screen shot 2017-10-10 at 1 04 10 am" src="https://user-images.githubusercontent.com/2164198/31355340-6f5faca0-ad57-11e7-9aae-654ce09f8bb9.png">

And regarding the requirement, I am working on an app where an user adds his/her Facebook pages to a custom Dashboard. But moving the same from the Dashboard away is more like deleting them from the Dashboard. As deleting involves deleting other dependencies with the user consent, handling it separately gives me more control.

**Comment by Leopoldthecoder** [comment]
@sureshbala This does not seem to be a common feature, so we are not going to support it. For your specific requirement, you can hide the buttons and checkboxes in the right panel using CSS.
