### ISSUE TITLE
使用vuex input控件 无法使用defaultValue

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#738]
### ElementUI version

rc.8
### Vue version

2.0.3
### Vuex version
2.0.0
### What is Expected?
如何向 redux那样 更新input值 如果绑定了 vuex

**Comment by baiyaaaaa** [comment]
input 组件好像没有 defaultValue 属性

**Comment by spademan** [comment]
vuex的 v-model写法 能解决 

https://vuefe.cn/vuex/mutations.html
