### ISSUE TITLE
[Feature Request] Click whole row to expand the row

### ISSUE THREAD

**Issue by qhbhq** [ElemeFE/element#7385]
### Existing Component
Yes

### Component Name
Table

### Description
https://jsfiddle.net/3xpeqp8d/1/
This is my now solution when i want to click whole row to expand the row, so hope the table component can have a config option.

**Comment by blackinitial** [comment]
i also want this feature, and i want to remove the column of icon expand, but i don't know

**Comment by Leopoldthecoder** [comment]
You'll be able to programmatically expand and hide rows in 2.0.0.
