### ISSUE TITLE
[Bug Report] Autocomplete component grouping display options

### ISSUE THREAD

**Issue by zhangya5847** [ElemeFE/element#7388]
### Element UI version
1.4.6

### OS/Browsers version
mac/chrome latest version

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/zhangya/sra4b5cq/2/](https://jsfiddle.net/zhangya/sra4b5cq/2/)

### Steps to reproduce
autocomplete 的选项能够分组显示。自定义模版，数据是数组嵌套数组。点击选项之后获得的item不是该选项的item，而是这个选项所在分组的item。

### What is Expected?
能够准确获得点击选项的item。

### What is actually happening?
获得的是该选项所在组的item。

**Comment by Leopoldthecoder** [comment]
Autocomplete 不支持分组。其实你的例子里不使用 `select` 事件，直接用 li 元素的点击事件就可以得到想要的结果：https://jsfiddle.net/sra4b5cq/3/

**Comment by zhangya5847** [comment]
变了数据结构，实现了分组显示，[https://jsfiddle.net/zhangya/L54nravo/2/](url)，仅供参考，PS：增加了搜索关键词高亮的效果
