### ISSUE TITLE
[Bug Report] calls Notification many times, and the tooltip overlaps

### ISSUE THREAD

**Issue by BiggerCheng** [ElemeFE/element#7389]
### Element UI version
1.4.4

### OS/Browsers version
deepin 15.4.1（linux 4.9.0）

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net](https://jsfiddle.net)

### Steps to reproduce
单独引用Notification时，多次调用Notification.warning 会导致提示框重叠，
多次调用 this.$notify 时 提示框不会重叠

### What is Expected?
提示框不重叠

### What is actually happening?
提示框重叠

**Comment by Leopoldthecoder** [comment]
同时调用多个的话，没有时间计算前一个 Notification 的高度，所以会这样。建议加个延时。

**Comment by BiggerCheng** [comment]
加了延迟还是会重叠

**Comment by BiggerCheng** [comment]
找到原因了，是我这边调用出现了问题

**Comment by alexd2580** [comment]
> 找到原因了，是我这边调用出现了问题

How did you fix this issue?
