### ISSUE TITLE
[Bug Report] [css] el-dropdown split-button looks messy

### ISSUE THREAD

**Issue by ircop** [ElemeFE/element#7395]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
FF 52.4.0

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/269zpr96/](https://jsfiddle.net/269zpr96/)

### Steps to reproduce
Create el-dropdown split-button

### What is Expected?
Button looks like in Docs example

### What is actually happening?
Button has whiite 1px border in it's left part:

https://i.imgur.com/iyenoFk.png

**Comment by Leopoldthecoder** [comment]
I can't reproduce this in FireFox. You can check if some other styles are affecting Dropdown, because it seems other users are not reporting the same issue.
