### ISSUE TITLE
The [Bug Report] [Bug, the Report] table bug:table-colum V-IF attribute causes the table width to be recalculated

### ISSUE THREAD

**Issue by 1847211504** [ElemeFE/element#7398]
### Element UI version
1.4.6

### OS/Browsers version
windows server 2016/chrome 42.0.2311.152

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/1847211504/b1tdquf9/5/](https://jsfiddle.net/1847211504/b1tdquf9/5/)

### Steps to reproduce
点击 demo 中的 Toggle 按钮可以看到 table 的 width 被重新计算了，每次都会增加一点宽度，导致最后 table 爆宽。

请多次点击 Toggle 按钮查看效果

### What is Expected?
1. 可以通过 v-if 或者 v-show 来控制 column 的显示。
2. 可以调整 table 的宽度。

在我们目前的系统中，表格1 和 表格2 是并列的，表格2 作为 表格1 的子列表出现
平时 表格2 为隐藏状态，点击 表格1 某一行时，加载子数据，通过 表格2 来展现。

### What is actually happening?
1. 通过 v-if 控制多列显示，目前会造成 table 的宽度大的离谱。
2. 无法动态调整 table 的宽度，比如 点击 表格1 某行，表格2 展现子数据，此时 表格1 隐藏多余列，调整宽度到最小，以展现 表格2 的数据。

**Comment by Leopoldthecoder** [comment]
牵扯到动态显示隐藏的，建议给 el-table-column 或 el-table 加上 key：https://jsfiddle.net/leopoldthecuber/b1tdquf9/6/ 。例子中的 Math.random() 只是为了说明效果，实际使用任何唯一性的值都行。
