### ISSUE TITLE
The [Bug Report] upload component calls action to upload multiple files at a time

### ISSUE THREAD

**Issue by vurtnr** [ElemeFE/element#7399]
### Element UI version
1.4.6

### OS/Browsers version
macOS Sierra / chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
您好。参考了upload组件中的手动上传demo，添加了多选属性，通过F12查看network时发现选择三个文件上传之后，调用了三次指定的action，想请问有没有办法只调用一次action上传所有选择的文件

### What is Expected?
调用一次action，上传所有文件

### What is actually happening?
上传几个文件调用几次action

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
