### ISSUE TITLE
[Feature Request] Add Custom Class To Table Header Row

### ISSUE THREAD

**Issue by sureshbala** [ElemeFE/element#7400]
### Existing Component
Yes

### Component Name
Table

### Description
Though there's an option to add a custom class to the table rows, the same option is not available for Table Header Row. Of course this can be achieved by adding a custom class to the table itself and writing css by chaining the respective classes. But having an option to add a Custom Class to Table Header Row would help.

**Comment by Leopoldthecoder** [comment]
Now we have `header-row-class-name` in 2.0

**Comment by feichangtutu** [comment]
header-row-class-name这个怎么用啊？？？
`	<el-table ref="singleTable" 
				  :data="tableData" 
				  style="width: 100%" 
				  v-loading.body="loading" 
				  element-loading-text="加载中"
				  @row-click="rowClick"
	:header-row-class-name='test'
		>`
`	test({row, rowIndex}){
				console.log(row,1)//  row is undefined
				console.log(rowIndex,2)
//				row.setAttribute('class','red')
			},`
