### ISSUE TITLE
[Bug Report] render-header column titles are rendered many times

### ISSUE THREAD

**Issue by hl33886** [ElemeFE/element#7402]
### Element UI version
1.4.6

### OS/Browsers version
window10

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/602/](https://jsfiddle.net/pj71jkyw/602/)

### Steps to reproduce
渲染多遍

### What is Expected?
只渲染 增加的那一列标题

### What is actually happening?
增加一列  表头全部渲染一遍

**Comment by Leopoldthecoder** [comment]
目前的实现无法避免渲染多次。
