### ISSUE TITLE
[Feature Request] TreeStore API

### ISSUE THREAD

**Issue by chlshown** [ElemeFE/element#7404]
### Existing Component
是

### Component Name
Tree

### Description
是否能在文档中添加TreeStore的api说明，在目前网站上的例子只看到了append和remove，不知道是否有edit之类的方法，谢谢

**Comment by Leopoldthecoder** [comment]
我们会在 2.0 的文档中考虑的。

**Comment by c5ms** [comment]
@Leopoldthecoder  very thanks. is any plan to support isLeaf property ?

**Comment by Leopoldthecoder** [comment]
@c5ms Check out the "Custom leaf node in lazy mode" example in the 2.0 doc.
