### ISSUE TITLE
 [Bug Report] When the visible property of the <el-dialog> is set without the.Sync modifier, the closing fork on the upper right corner of the dialog is invalid

### ISSUE THREAD

**Issue by qidaneix** [ElemeFE/element#7406]
### Element UI version
1.4.6

### OS/Browsers version
windows 7/chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/xiaodabao/ph15ksbc/3/](https://jsfiddle.net/xiaodabao/ph15ksbc/3/)

### Steps to reproduce
点击按钮，再点击dialog的×

### What is Expected?
弹窗关闭

### What is actually happening?
弹窗未能关闭

**Comment by wacky6** [comment]
设计上就是这样的。

**Comment by qidaneix** [comment]
有什么办法可以解决吗，因为有时候这个:visible的属性值可能是从父组件props传递来的，加上.sync属性的话vue会报错。
或许隐藏组件的关闭按钮，自定义一个关闭按钮是个选择？

**Comment by qidaneix** [comment]
问题解决了，通过隐藏关闭按钮然后自定义关闭按钮的方式。
@wacky6 谢谢

**Comment by Q10Viking** [comment]
看你的例子，当你点击关闭按钮时，没有改变`dialogTableVisible`的值，它仍然时true,这时否需要使用`.sync`,来更新值。

[https://jsfiddle.net/j9tka548/](https://jsfiddle.net/j9tka548/)
