### ISSUE TITLE
[Bug Report] Input type textarea append slot bug

### ISSUE THREAD

**Issue by zont** [ElemeFE/element#7409]
### Element UI version
1.4.6

### OS/Browsers version
all

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/bgn34nL0/](https://jsfiddle.net/bgn34nL0/)

### Steps to reproduce
Add slot="append" to input type textarea

### What is Expected?
Append slot content

### What is actually happening?
Nothing

**Comment by Leopoldthecoder** [comment]
The append slot is only meant for inputs, not textareas.

**Comment by zont** [comment]
But why?
