### ISSUE TITLE
dialog中 select 下拉框 z-index属性问题

### ISSUE THREAD

**Issue by RuroniKenshin** [ElemeFE/element#7410]
当在dialog 中使用select 或 timepicker 这种弹框性组件的时候 首次打开弹框会出现 select下拉框在dialog下面的情况 ，原因可能是  父页面与dialig弹框使用的不是同一个PopupManager，请问该问题如何解决

**Comment by PmcFizz** [comment]
I want know do you have solve this z-index problem?

**Comment by chenyi5266** [comment]
+1

**Comment by my9074** [comment]
+1
