### ISSUE TITLE
table组件的标题和内容左右对不齐

### ISSUE THREAD

**Issue by yanjb** [ElemeFE/element#7414]
element-ui 1.3.7
safari 11.0

查看 Table 组件，第2列之后的标题和内容错位了。

<img width="858" alt="qq20171010-175408 2x" src="https://user-images.githubusercontent.com/4134839/31380496-2bb681c0-ad77-11e7-9bae-622ace709255.png">

**Comment by yinshipeng** [comment]
请问解决了没？

**Comment by enyyongyang** [comment]
我知道了        width: "160"   yes 
                       width: "150"  no
要设置除以2还是偶数的宽度就不会错位了，
机智的我
