### ISSUE TITLE
[Feature Request] Column Selection

### ISSUE THREAD

**Issue by kavalcante** [ElemeFE/element#7416]
### Existing Component
Yes

### Component Name
el-table

### Description
Today is only possible select the entire row, is possible to create a ColumnSelection as well? Is that a way to select all values from a specific column today?

**Comment by syn-zeta** [comment]
No, there's no way to select a column in the Table component. Seems like you have a very specific use case, and this can be rather hard to implement, I think. Have you come across any library or framework that provide this functionality? I'm afraid the only options would be to implement a custom table from scratch, or try to hack the Table component to get what you need.

@Leopoldthecoder

**Comment by kavalcante** [comment]
Thanks for you reply @syn-zeta I made in a traditional table using @click in each TD. Works fine for me. I will close that issue now.

**Comment by syn-zeta** [comment]
> traditional table using @click in each TD.
Hope you're using event delegation (listening to a click on table instead of every td).
