### ISSUE TITLE
[Feature Request] How to add a directive to a table row

### ISSUE THREAD

**Issue by JJPandari** [ElemeFE/element#7420]
### Existing Component
Yes

### Component Name
el-table

### Description
*I'm trying to* use [vue2-dragula](https://github.com/kristianmandrup/vue2-dragula) to add drag&drop effects to my `el-table`, which requires adding a directive like `v-dragula="colOne"` to the rows I want dragged.  

*AFAIK*, I have to add the directive in the template (rather than hack it by adding it later to the generated dom), and since `el-table` has its rows all abstracted away in the `el-table-column`s, this is not achievable, neatly or hackily.  

*The closest I can get* is to use `el-table-column`'s slot to add some component in the table cell, and add my directive to that component, but this makes one table cell draggable, while I want a whole row to be draggable.

**Comment by JJPandari** [comment]
Got around it by manually constructing `table`s with `element-ui`'s class to retain same style. Also vue2-dragula seems not mature enough so I fell back to dragula instead. Changing the view-model after dragging is a bit tricky but I barely did it.

**Comment by kramer99** [comment]
@JJPandari Could you post the code you used to achieve this? I'm trying to do the exact same thing.

**Comment by JJPandari** [comment]
@kramer99 

```html
<div class="el-table__body-wrapper">
  <table cellspacing="0" cellpadding="0" border="0" class="el-table__body" style="width: 100%;">
    <colgroup>
      <col name="el-table_1_column_1" width="80">
      <col name="el-table_1_column_2">
    </colgroup>
    <tbody ref="table-body-wrapper">
      <tr class="el-table__row" v-for="row of apples" draggable="true" :key="row.id" :apple-id="row.id">
        <td class="el-table_1_column_1">
          <div class="cell">{{row.color}}</div>
        </td>
        <td class="el-table_1_column_2">
          <div class="cell">{{row.size}}</div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

......

<script>
watch: {
  apples() {
    this.$nextTick(() => {
      const $wrapper = this.$refs['table-body-wrapper'];
      this.dragula && this.dragula.destroy();
      this.dragula = dragula([document.querySelector('tbody')], {
        // use this option so the mirror is in the tbody and properly styled
        mirrorContainer: $wrapper
      });
      // adjust the vm after drop
      this.dragula.on('drop', (el, target, source, sibling) => {
        const rows = [].filter.call($wrapper.children, a => !a.classList.contains('gu-mirror'));
        const newAppleArr = [];

        for(const row of rows) {
          newAppleArr.push(
            this.appleMap.get(Number(row.getAttribute('apple-id')))
          );
        }

        this.apples = newAppleArr;
      });
    });
  }
},
computed: {
  appleMap() {
    return new Map(this.apples.map(a => [a.id, a]));
  }
},
</script>
```

**Comment by kramer99** [comment]
Thanks, really appreciate this!
