### ISSUE TITLE
[Bug Report] How to validation if form dynamic?

### ISSUE THREAD

**Issue by blackinitial** [ElemeFE/element#7421]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
OS: Linux Mint 18 64 bit, Browser : Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/604/](https://jsfiddle.net/pj71jkyw/604/)

### Steps to reproduce
fix the validation with dynamic form

### What is Expected?
submit run perfect with validation in dynamic form, (rules can dynamic according to the number of passenger)

### What is actually happening?
validation can't run perfectly, i can't to fix this

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/605/ I only modified the first form item. You can do the same to the rest of them.

**Comment by blackinitial** [comment]
@Leopoldthecoder  hmm, modified in prop, but still the validation can't run if rules not dynamic as well. how this? https://jsfiddle.net/blackinitial/pj71jkyw/606/
