### ISSUE TITLE
[Feature Request] Add a new props "rule-name" rather than use 'prop' for el-form-item to get form rules

### ISSUE THREAD

**Issue by abc126** [ElemeFE/element#7422]
### Existing Component
是

### Component Name
el-form-item

### Description
Currently the ElFormItem uses "prop" to get both form rules and form model to validate

code in form-item.vue:
formRules = formRules  ? formRules[this.prop] : []; // not the exact code in form-item.vue
fieldValue = getPropByPath(model, prop).v // not the exact code in form-item.vue

i suggest add a new param: rule-name to indicate the form rules,
and the former param "prop" will be only used to get the form model value.
so we can apply one rule to many fields

if that suggest is accepted, i can make a PR

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
