### ISSUE TITLE
[Feature Request] Add functionality to add form validation translations

### ISSUE THREAD

**Issue by TMantas** [ElemeFE/element#7426]
### Existing Component
Yes

### Component Name
Form

### Description
Element UI uses [async-validator](https://github.com/yiminghe/async-validator) to validate forms. It has l18n functionality but the problem is that the is no way (or I couldn't find a way) to add form validation translations to Element UI.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can update the validation message based on the current language, though.
