### ISSUE TITLE
The [Feature Request] routine Table is rendered as a table element

### ISSUE THREAD

**Issue by qidaizhe11** [ElemeFE/element#7429]
### Existing Component
是

### Component Name
Table

### Description
当前el-table组件实现为table-header与table-body分别渲染一个完整table元素，由于二者分处两个table元素，在打印表格时，无法利用表格头（thead）自动复制到每一页的特性，如下图：

![tim 20171011151106](https://user-images.githubusercontent.com/5690905/31427414-bc70d1ac-ae99-11e7-9eb4-393feb6ce867.png)

建议后续版本迭代考虑加上判断，只在固定表头/多级表头等复杂情况下将table-header/table-body渲染为完整table元素，其他普通表格，整个el-table渲染为一个标准的table元素：
```html
<table>  // el-table
  <colgroup></colgroup>
  <thead></thead>  // table-header
  <tbody></tbody>  // table-body
</table>
```

以支持普通表格打印时表格头可自动复制至每一页的期望效果：

![tim 20171011151153](https://user-images.githubusercontent.com/5690905/31427418-c1372bd2-ae99-11e7-82a1-edfd7b740393.png)

谢谢！

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
