### ISSUE TITLE
[Bug Report] is this bug or feature? When there's only one  el-form-item in el-form, when you press the Enter key, the page will be refreshed automatically

### ISSUE THREAD

**Issue by stillsilly** [ElemeFE/element#7433]
### Element UI version
1.4.6

### OS/Browsers version
win7

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/vfnqn3yo/3/](https://jsfiddle.net/vfnqn3yo/3/)

### Steps to reproduce
1，在输入框中输入任意文字，
2，敲回车键

### What is Expected?
不要有反应

### What is actually happening?
在普通html文件中，页面会刷新，
在jsfiddle里是给jsfiddle的后台发了个莫名其妙的get请求

**Comment by JJPandari** [comment]
From [The Enter Key should Submit Forms, Stop Suppressing it](https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/)(he quoted the following form whatwg spec):  

> If the form has no submit button, then the implicit submission mechanism must do nothing if the form has more than one field that blocks implicit submission, and must submit the form element from the form element itself otherwise.  

*In short*, having only one input in the form behaves the same as having a `submit` button in the form: when you hit enter in the input, the form submits.  
简而言之，form里只有一个input时，情况和form里有一个`submit`按钮一样：在input里按回车会提交form。
