### ISSUE TITLE
The [Bug Report] NavMenu navigation menu state has not changed during the routing jump

### ISSUE THREAD

**Issue by Niefee** [ElemeFE/element#7435]
### Element UI version
1.4.6

### OS/Browsers version
window chrome 61

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/niefee/ey37a10s/](https://jsfiddle.net/niefee/ey37a10s/)

### Steps to reproduce
在页面内跳转到导航菜单的某个路由，但active选项没有改变，只有点击导航菜单active才会改变。如示例，在about点击路由跳转到home路由，导航菜单字体颜色没有改变

### What is Expected?
点击跳转回home路由的时候，home的颜色变蓝，about变回黑色

### What is actually happening?
暂时的效果是点击路由导航菜单颜色没有改变

**Comment by galipmedia** [comment]
I fixed this in this fiddle... https://jsfiddle.net/galipmedia/rfg5tuy3/1/

**Comment by Niefee** [comment]
@gabrielboliveira thinks,This is what I want.
