### ISSUE TITLE
The [Feature Request] table adds column merge functionality

### ISSUE THREAD

**Issue by LunchFood** [ElemeFE/element#7437]
### Existing Component
Yes

### Component Name
Table 表格

### Description
希望增加一个表格功能，表格具有 多级表头 和 列合并的功能

**Comment by LunchFood** [comment]
![qq 20171011174012](https://user-images.githubusercontent.com/22734894/31433243-4c00f156-aeab-11e7-8dd2-1b5d2aafffbf.png)

**Comment by liaoyinglong** [comment]
http://element.eleme.io/2.0/#/zh-CN/component/table#duo-ji-biao-tou

多级表头看 2.0版本有了，合并列的话暂时没看到

**Comment by LunchFood** [comment]
多级表头我知道，只是希望有个能实现 多级表头 和列合并同时存在的表格，并且表头固定

**Comment by Leopoldthecoder** [comment]
合并行、合并列的功能会在 2.0 中加入。
