### ISSUE TITLE
[Bug Report] DatePicker-selection does not work as intended when in Amrerica/Chicago timezone

### ISSUE THREAD

**Issue by manV** [ElemeFE/element#7443]
### Element UI version
1.4.6

### OS/Browsers version
Ubuntu 16.04/firefox 56.0 and chrome 61.0.3163.100

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1. change the timezone to America/Chicago
2. open jsfiddle link
3. try to select date range 12 Nov 2017 to 25 Nov 2017.

### What is Expected?
First and Last selected dates should be highlighted correctly.

### What is actually happening?
First and Last selected dates are not highlighted correctly
Here is the screen shot link-https://i.imgur.com/WliiLx4.png

**Comment by wacky6** [comment]
I am aware of this DST highlight issue. But may take some time before it's fixed, because I'm prep for final exams.

**Comment by Leopoldthecoder** [comment]
@wacky6 I think #7599 fixes this?

**Comment by wacky6** [comment]
Yes.

**Comment by manV** [comment]
Will this be released on 1.4.x?

**Comment by wacky6** [comment]
Will be release on 2.0
