### ISSUE TITLE
[Feature Request] Cascader cascading selector scroll bar beautification

### ISSUE THREAD

**Issue by JiejiaH** [ElemeFE/element#7445]
### Existing Component
是

### Component Name
Cascader

### Description
级联选择器弹出框目前用的是overflow: auto,如果内容多出现滚动条的话, 会很丑, 尤其是两级菜单中间夹着一个原生的滚动条的话, 更丑.  能不能做成和Select选择器组件弹出框那样的模拟的滚动条.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
