### ISSUE TITLE
[Bug Report] view is not changed with modern Data changed

### ISSUE THREAD

**Issue by cyzeng-Luca** [ElemeFE/element#7447]
### Element UI version
1.4.6

### OS/Browsers version
window chrome@latest

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/while_own/nwvr7wut/6/](https://jsfiddle.net/while_own/nwvr7wut/6/)

### Steps to reproduce
1. change the price 30.25680-30.25689(i keep four decimal);
2. the 30.25680-30.25684 is not work, the 30.25685-30.25689 is normal;
3. i debugger it, i find the modern data is changed,but it is not work when i input 30.25680-30.25684;
4. i try to use vm.$forceUpdate ,but it is not work;

### What is Expected?
the same as i input 30.25685-30.25689

### What is actually happening?
change to 30.25680-30.25684,not work

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/nwvr7wut/9/
