### ISSUE TITLE
[Bug Report] official upload demo, click Cancel and then upload, upload, operation several times, chrome Caton problems

### ISSUE THREAD

**Issue by killdada** [ElemeFE/element#7448]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
win7/版本 61.0.3163.100（正式版本） （32 位）

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击上传点击取消，再点击上传点击取消，重复几次chrome环境下打开上传界面卡顿。

### What is Expected?
上传弹窗不卡顿，

### What is actually happening?
上传弹窗不卡顿，

**Comment by killdada** [comment]
https://jsfiddle.net/x9qzfupL/

**Comment by Leopoldthecoder** [comment]
测试了 1.4.6 和 2.0.0-alpha.2，在 Mac 和 Windows 的 Chrome 里重复三十次，均未出现卡顿情况。建议检查是否被某个浏览器插件影响到了。
