### ISSUE TITLE
[Bug Report] el-form-item number check is not correct

### ISSUE THREAD

**Issue by MayWu91** [ElemeFE/element#7460]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
Google Chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/bvnahncn/](https://jsfiddle.net/bvnahncn/)

### Steps to reproduce
once you input a number beginning
no matter what kind of type the next char you input (like 3dasdfasd)
the check will passed

### What is Expected?
the label show warning color
checked failed

### What is actually happening?
it passed

**Comment by Leopoldthecoder** [comment]
Duplicate of #5943
