### ISSUE TITLE
[Bug Report] The input-box of 'el-pagination' haven't self-adaption

### ISSUE THREAD

**Issue by Joshwoooooooooooooooooooooooooooooooong** [ElemeFE/element#7463]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
chrome Version 61.0.3163.100（Official Build） （64-bit）

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/g2cpk26o/](https://jsfiddle.net/g2cpk26o/)

### Steps to reproduce
just use it, it happened

### What is Expected?
when I input a number to input-box which will self-adaption

### What is actually happening?
the style of .el-pagination__editor.el-input set the width is 50px cause the input-box cannot self-adaption

**Comment by Leopoldthecoder** [comment]
Yes, the input box will not be 'self-adaption'. If you think it's not wide enough, you can override its CSS.

**Comment by Joshwoooooooooooooooooooooooooooooooong** [comment]
sorry,I lacked an other question.
when I using Pagination, and injected all Element component, the console always throw an error:
`[Vue warn]:  Injection "elFormItem" not found`
the reproduction link is same to the issue.
can u tell me how to resolve it?

**Comment by Joshwoooooooooooooooooooooooooooooooong** [comment]
@Leopoldthecoder sorry,I lacked an other question.
when I using Pagination, and injected all Element component, the console always throw an error:
[Vue warn]: Injection "elFormItem" not found
the reproduction link is same to the issue.
can u tell me how to resolve it?

**Comment by Leopoldthecoder** [comment]
https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#inject-with-default-values

Vue has just released 2.5.0 which solves this problem. Please wait for our next release.
