### ISSUE TITLE
When [Bug Report] pagination sets the number of bars displayed on each page, the event triggers a problem

### ISSUE THREAD

**Issue by proshuai** [ElemeFE/element#7464]
### Element UI version
1.4.6

### OS/Browsers version
mac

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/General_Lee/pj71jkyw/610/](https://jsfiddle.net/General_Lee/pj71jkyw/610/)

### Steps to reproduce
当每页条数改变时，currentPage也会跟着改变，会触发两次接口请求
比如：总共180条数据，每页50条，总共有4页，当你选到第3页的时候，改变每页显示100条，则会触发一次接口，同事currentPage也会改变，会再次触发一次接口。
多测试几次，就不触发current-change事件了

### What is Expected?
变换每一页显示的条数时，要么一直触发current-change事件，要么就不触发current-change事件。怎么一会触发，一会不触发

### What is actually happening?
事件触发错乱

**Comment by wacky6** [comment]
重现链接似乎不太对？检查一下吧

**Comment by proshuai** [comment]
可以关闭这个问题了。已经解决
![image](https://user-images.githubusercontent.com/13295895/31532576-bb5b86d4-afb3-11e7-8b88-7ea2862649f7.png)
