### ISSUE TITLE
Can the drop-down box elements of the [Feature Request] Select component be configured to be generated into a select element or a sibling directory?

### ISSUE THREAD

**Issue by mirari** [ElemeFE/element#7468]
### Existing Component
是

### Component Name
Select

### Description
使用全屏API将指定元素设置为全屏后，其内部的select组件在点击后本应弹出的下拉框无法被看到。
因为el-select-dropdown元素并非位于全屏元素内部，而是body的子节点。
而Dialog组件都是可以保持自身位置在声明时所在的元素下的，没有这个问题。
希望select和message组件都可以增加一个配置项，用于指定el-select-dropdown或el-message-box__wrapper弹出时是挂载到body下还是select父元素或者是自行指定元素。

**Comment by wacky6** [comment]
Can you provide a demo?

**Comment by mirari** [comment]
[http://jsfiddle.net/mirari/k2dxam5h/](demo)

**Comment by wacky6** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
I'll look into it later this week.
