### ISSUE TITLE
table组件的一个需求或者说需要考虑的问题

### ISSUE THREAD

**Issue by cgkoreyoshi** [ElemeFE/element#747]
使用table组件时，需考虑各种屏幕分辨率下适配，目前列宽度控制只有width属性可以使用，这个其实是固定宽度，没有设置宽度的列在小屏幕下会被无限缩小，如果所有列都设置了width，那么大屏下表格右边会空出很多出来，是否可以考虑设计min-width这样的属性来做自适应?

**Comment by furybean** [comment]
之前忘记加这个属性的文档了，刚刚加上。#750

**Comment by cgkoreyoshi** [comment]
max-width有考虑加么

**Comment by furybean** [comment]
@cgkoreyoshi 在什么场景下会有使用 max-width 的需求？如果合理，后面会考虑加。

**Comment by cgkoreyoshi** [comment]
@furybean 有这样的一种场景：某列的数据是一段很长的文字，然后表格本身TR是定高的，如果评论文字过多，则使用...来展示，这时希望能设置一个最宽的宽度。

**Comment by SuperAL** [comment]
@furybean 使用场景：列内容文字过长，希望可以设置一个 max-width，这样内容过长时我可以自己有处理方式：省略号或者使用tooltip组件显示其余内容，列内容过短时也不至于右侧太空，宽度根据内容长度自适应（因为我目前是设置 width 固定宽度的，文字内容自然是左对齐，一列内容都不长时右侧显得过于空）。
