### ISSUE TITLE
When [Bug Report] forms validation, the page has just been loaded and has not been selected to verify it

### ISSUE THREAD

**Issue by wardenGfs** [ElemeFE/element#7470]
### Element UI version
1.2.8

### OS/Browsers version
macOS high sierra

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
编辑页面的时候   需要反显之前的东西  这个时候表单还没加载完，就报验证错误了
在项目里面，重现链接暂无

### What is Expected?
当我点击的时候才去验证，表单刚加载的时候不去验证

### What is actually happening?
直接一进来就验证报错了

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly. You can minify your project and create a GitHub repo for it.
