### ISSUE TITLE
In [Bug Report] form validation, you can only enter numeric validation bug

### ISSUE THREAD

**Issue by 610076912** [ElemeFE/element#7471]
### Element UI version
1.4.6

### OS/Browsers version
win 10， chrome 版本 61.0.3163.100（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/qjwns7op/](https://jsfiddle.net/qjwns7op/)

### Steps to reproduce
先输入数字，在数字后输入非数类型还是可以通过验证

### What is Expected?
只要输入的类型中有非数字类型，就可以触发规则验证。

### What is actually happening?
先输入数字，在数字后输入非数类型不会触发规则验证。因为在<el-input>双向绑定时用了 number修饰符，这个修饰符导致在数字后面输入非数字类型，绑定的变量不会发生改变，所以不能触发规则的验证，导致出现了本bug。

**Comment by 610076912** [comment]
新发布的版本中这个问题依然存在。

**Comment by Leopoldthecoder** [comment]
Duplicate of #5943
