### ISSUE TITLE
[Bug Report] el-date-picker cannot be used in 360 security browser

### ISSUE THREAD

**Issue by shiyuegongsui** [ElemeFE/element#7473]
### Element UI version
1.4.6

### OS/Browsers version
win10 / 360浏览器9.1.0.356

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/612/](https://jsfiddle.net/pj71jkyw/612/)

### Steps to reproduce
点击时间控件，无法点击弹出的日期

### What is Expected?
可以点击

### What is actually happening?
无法点击

**Comment by shiyuegongsui** [comment]
那这不是很不科学吗。其他控件都可以，唯独这个不行。

**Comment by Leopoldthecoder** [comment]
有动图吗？

**Comment by alextzh** [comment]
确实不好使

**Comment by lincenying** [comment]
chrome 57 也不行.

**Comment by Leopoldthecoder** [comment]
后续进展在 #7539 更新
