### ISSUE TITLE
[Bug Report] checkbox not work in vue@2.5.0

### ISSUE THREAD

**Issue by STLighter** [ElemeFE/element#7474]
### Element UI version
1.4.6

### OS/Browsers version
windows 7 / chorme 61

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/ST_Lighter/ag57mce0/](https://jsfiddle.net/ST_Lighter/ag57mce0/)

### Steps to reproduce
click checkbox

### What is Expected?
to be not checked

### What is actually happening?
still checked

**Comment by weiziqing** [comment]
I have the same problem . 
when I used 2.4.0 version of Vue,it could work.

**Comment by Leopoldthecoder** [comment]
Upgrading Vue to 2.5.2 fixes this: https://jsfiddle.net/ag57mce0/1/
