### ISSUE TITLE
[Bug Report] use option-group and input to check, the group line will no hide

### ISSUE THREAD

**Issue by WxSwen** [ElemeFE/element#7475]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
chrome

### Vue version
2.5.0

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
option-group 组件使用 filterable 会出现分组横线不消失的情况

### What is Expected?
使用option-group 组件  手动输入查询 无分组横线

### What is actually happening?
使用option-group 组件  手动输入查询 有分组横线

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8184/commits/2db923e421e44c6c1d2481ea2026bb735ed33f34
