### ISSUE TITLE
[Bug Report] Radio button group fails using vue 2.5.0

### ISSUE THREAD

**Issue by KKRainbow** [ElemeFE/element#7477]
### Element UI version
1.4.6

### OS/Browsers version
Arch Linux/ Chromium 61.0.3163.100

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/sunsijie/pgn7gyu9/#&togetherjs=smS20MqksL](https://jsfiddle.net/sunsijie/pgn7gyu9/#&togetherjs=smS20MqksL)

### Steps to reproduce
just click it

### What is Expected?
only one should be highlighted

### What is actually happening?
every item clicked is highlighted

**Comment by KagamiChan** [comment]
Same here.

A thing to note:
If you import directly from source (with webpack), that said, use `import ElRadioButton from 'element-ui/packages/radio-button'` and use it in your template, the component will work again.
So this bug seems to a regression on vue's side

**Comment by KagamiChan** [comment]
posted a issue in vue vuejs/vue#6803

it is to be fixed in vue's next patch version

**Comment by Leopoldthecoder** [comment]
@KagamiChan Thanks for boiling it down.

**Comment by Leopoldthecoder** [comment]
Upgrading Vue to 2.5.2 fixes this: https://jsfiddle.net/pgn7gyu9/1/
