### ISSUE TITLE
After the [Bug Report] introduces the third party icon library, the default icon is displayed as a block

### ISSUE THREAD

**Issue by nicky-lau** [ElemeFE/element#7478]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
win7/chrome 61.0.3163.100（正式版本） （32 位）

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce

[class^="el-icon"], [class*=" el-icon"] {
  font-family:"iconfont" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

按照文档做了这一步 之后，elementUI 自带的icon就不能正常显示了

### What is Expected?
正常显示elementUI自带的Icon

### What is actually happening?
显示为空心方块

**Comment by Leopoldthecoder** [comment]
In 2.0.0 you don't have to do anything to make third party icons work. We'll remove that part from 2.0 docs.
