### ISSUE TITLE
upload 的 accept 属性，文档说明有错误。

### ISSUE THREAD

**Issue by aguegu** [ElemeFE/element#748]
https://github.com/ElemeFE/element/blob/master/packages/upload/src/index.vue#L178

这行导致当 “thumbnail-mode” 为 true 时，accept 失效。

而文档里写的是 “拖拽文件上传时不受此参数影响”，而是不是缩略图模式和拖拽并没有直接关系。

**Comment by furybean** [comment]
Closed via #754
