### ISSUE TITLE
[Bug Report] Unable to focus Switch component

### ISSUE THREAD

**Issue by breadadams** [ElemeFE/element#7481]
### Element UI version
1.4.6

### OS/Browsers version
Chrome Version 61.0.3163.100

### Vue version
2.5.1

### Reproduction Link
[https://jsfiddle.net/breadadams/wm3w5baw/2/](https://jsfiddle.net/breadadams/wm3w5baw/2/)

### Steps to reproduce
Click the _Apply focus to switch_ button (this tries to apply `.focus()` on the `Switch`'s input $ref)

If you enable the _show css solution_ Switch you'll see it working, I've added a CSS solution for this in there.

### What is Expected?
Focus should be set on the `<input>`

### What is actually happening?
It doesn't get set because the `<input>` has a `display:none;` style property.

**Comment by breadadams** [comment]
I've got a fix for this ready to commit/PR, @Leopoldthecoder, however I'm thinking maybe it'd be best to add a new prop to `Switch`.

Something like `allow-focus` (default `false`, to not alter any current usage of the field).

**Comment by Leopoldthecoder** [comment]
In 2.0.0 we'll have a `focus` method (not released yet) for Switch. When called, the inner input element will be focused and an outline will appear around the Switch, just like what you did with `.el-switch__core`.

We'll probably leave 1.x as is. Actually many form components in 1.x can not be focused, and this situation will get improved in 2.0.

Feel free to reopen this issue if you have a different opinion.

**Comment by breadadams** [comment]
Hey @Leopoldthecoder - that's good to hear re. v2, however I think this feature **should** be implemented in the latest release too. Not all projects using `element` will be able to be updated to v2 (unless it's planned to be a seamless update?) & due to the alpha stage I'm still using the latest release on _new_ projects.

As for the other 1.x components I've been working with quite a few of the _form_ components and applying focus hasn't been much of an issue, but where I see any such problems I will try and get a PR in where possible.

I can't re-open the issue but if you do, I'll sort a proper proposal of a _fix_ and you can review it better there

**Comment by Leopoldthecoder** [comment]
@breadadams OK, please send a PR to the `dev` branch. Your fix in the fiddle looks good, and that's pretty much what we have done in 2.0.

**Comment by breadadams** [comment]
Just realised styling isn't handled directly in `element` - should I do this in a separate PR on [theme-default](https://github.com/ElementUI/theme-default)? That seems better than inline styles @Leopoldthecoder, right?

**Comment by Leopoldthecoder** [comment]
Oh, the styling is here: https://github.com/ElemeFE/element/blob/dev/packages/theme-default/src/switch.css .
