### ISSUE TITLE
多选框组，el-checkbox-group，重新勾选时不希望数组顺序被打乱

### ISSUE THREAD

**Issue by vxhly** [ElemeFE/element#7484]
```html
<el-checkbox-group
   class="checkbox-group"
    flex="wrap:wrap"
    v-model="paymentsMetricsSelect">
    <el-checkbox
       v-for="(item, index) in paymentsMetrics"
       :label="item"
        :key="index">
           {{ item }}
         </el-checkbox>
  </el-checkbox-group>
```

绑定了两个数组，paymentsMetricsSelect 这个数组是被选中的值，paymentsMetrics 这个数组是渲染 el-checkbox-group 组件的数组，当我勾选的时候 paymentsMetricsSelect 这个数组是通过 push 进来的，顺序与 paymentsMetrics 这个的顺序不一致，我不希望它的顺序被打乱，有没有解决方案

**Comment by 527604382** [comment]
sortcheckedCities(originArr, choosedArr) {

  return choosedArr.sort((a, b) => {

    return originArr.indexOf(a) - originArr.indexOf(b)
  })
}

**Comment by 651584008** [comment]
我也觉得应该要有个选择。。
