### ISSUE TITLE
[Bug Report] 2.0.0-alpha.2 version > rate component > Read-only

### ISSUE THREAD

**Issue by jialuchun** [ElemeFE/element#7488]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
mac

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/44o6tarp/](https://jsfiddle.net/44o6tarp/)

### Steps to reproduce
clicking read-only will appear outside the border
【2.0.0-alpha.2 版本 点击 只读 Rate 评分会出现外边框】

### What is Expected?
read-only rate component does not appear outside the border

### What is actually happening?
clicking read-only will appear outside the border

**Comment by Leopoldthecoder** [comment]
This will be fixed in the next release.
