### ISSUE TITLE
在表单验证那一块  只要某个方法里面有this.$refs[formName].resetFields(); 就获取不到表单的数据

### ISSUE THREAD

**Issue by Faithree** [ElemeFE/element#7492]
http://element.eleme.io/#/zh-CN/component/form

![image](https://user-images.githubusercontent.com/21101396/31583063-17bc7776-b1c6-11e7-894e-e8b2430644e5.png)

假如我想要重置表单之前，想拿到已经填写的数据，要怎么操作？

**Comment by 729504321** [comment]
hi,这个怎么解决的

**Comment by wj19960923** [comment]
我也遇到了
