### ISSUE TITLE
[Feature Request] Clear select component programmatically

### ISSUE THREAD

**Issue by allesan** [ElemeFE/element#7495]
### Existing Component
Yes

### Component Name
el-select

### Description
If I'm not mistaken, there is no way to clear, or reset el-select component to its placeholder from within parent component.
I have one el-select that when selected should reset other el-select to placeholder.

**Comment by syn-zeta** [comment]
Not a way that Element provides, but it can be done: https://jsfiddle.net/kaynsat1/

Hopefully, we'll see more programmatic control in Element 2 and onwards.

@Leopoldthecoder Recommend closing.

**Comment by Leopoldthecoder** [comment]
This can be done by reassigning the binding value: https://jsfiddle.net/kaynsat1/1/ .

**Comment by syn-zeta** [comment]
Yep, that is much better. The example in my previous comment assumed that the clearer does not know the model a select is bound to, but if that is not the case, then clearing the binding value is the proper way.
