### ISSUE TITLE
[Feature Request] NavMenu Top bar fixed

### ISSUE THREAD

**Issue by Tazeg** [ElemeFE/element#7496]
### Existing Component
Yes

### Component Name
NavMenu Top bar

### Description
How to fix the NavMenu Top bar on top of the page, when the content has a vertical scrollbar ?

**Comment by syn-zeta** [comment]
This can be achieved with some simple CSS styling: https://jsfiddle.net/ske704da/

I'm thinking it is not part of NavMenu as users will have specific requirements of how it should work/behave.
