### ISSUE TITLE
[Bug Report] Collapse NavMenu:when collapse menu, then expand it, should remember previous state

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#7497]
### Element UI version
1.4.6

### OS/Browsers version
mac

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/oy9grwuj/](https://jsfiddle.net/oy9grwuj/)

### Steps to reproduce
1、展开左侧导航栏
2、点击某个多级导航下的选项查看对应的页面
3、点击左上角的icon隐藏左侧导航栏
4、再点击左上角的icon展开左侧导航栏

### What is Expected?
左侧导航栏保持之前选择某个多级导航栏选项的状态及样式

### What is actually happening?
重新展开左侧导航栏时，多级导航栏全部处于折叠状态

**Comment by baiyaaaaa** [comment]
更新到最新版本，该问题已修复

**Comment by PanJiaChen** [comment]
@baiyaaaaa 并没有啊。
重新步骤：
选择导航一里面的任何一个子菜单，之后收起菜单，再展开菜单。并没有记住之前展开项。
[online demo](https://jsfiddle.net/9prca0us/)

原因:https://github.com/ElemeFE/element/pull/6200

**Comment by squallliu** [comment]
确实有问题，如果只是展开菜单并没有选中一个菜单项的时候，展开状态丢失
