### ISSUE TITLE
考虑让 <el-col> 默认使用 border-box？

### ISSUE THREAD

**Issue by lujjjh** [ElemeFE/element#75]
默认主题里 `<el-row>` 是使用 border-box 的，`<el-col>` 却还是 content-box。导致为 `<el-row>` 设置非零的 `gutter` 属性后排版不正常的情况。有些奇怪，不知道是不是有意为之？

In the default theme, the `<el-row>` element uses border-box while the `<el-col>` element uses content-box, which results in some layout issues when the `gutter` attribute of the `<el-row>` element is nonzero. It is a bit strange and I wonder if it is designed to be like that.

**Comment by baiyaaaaa** [comment]
@lujjjh 确实是失误，Grid 组件文档上显示正常因为文档样式的问题。没注意到
