### ISSUE TITLE
The problem of [Bug Report] about circular el-breadcrumb-item stuck

### ISSUE THREAD

**Issue by lovezhao311** [ElemeFE/element#7500]
### Element UI version
1.4.6

### OS/Browsers version
win

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/5smroc5y/3/](https://jsfiddle.net/5smroc5y/3/)

### Steps to reproduce
更改一下input的值就知道了
每次updated事件更改一次 el-breadcrumb-item的数据

### What is Expected?
每次updated事件更改一次 el-breadcrumb-item的数据

### What is actually happening?
每次updated事件后就卡死了

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/5smroc5y/4/

与 Element 无关，在 `updated` 里对数据重新赋值会再次触发 `updated` 钩子。Vue 文档中 `updated` 部分专门提到：
> you should avoid changing state inside the hook

**Comment by lovezhao311** [comment]
@Leopoldthecoder  那不是死循环了？
