### ISSUE TITLE
[Bug Report] el-menu hover fast switching, leading to el-menu flash back

### ISSUE THREAD

**Issue by hanyuhh** [ElemeFE/element#7510]
### Element UI version
1.4.7

### OS/Browsers version
chrome   60.0.3

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/uc906r7v/](https://jsfiddle.net/uc906r7v/)

### Steps to reproduce
鼠标从选项4（没有展开时） 快速滑动到 选项1 ，el-menu 闪退

### What is Expected?
bug 修复

### What is actually happening?
鼠标从选项4（没有展开时） 快速滑动到 选项1 ，el-menu 闪退

**Comment by Leopoldthecoder** [comment]
Duplicate of #6520

**Comment by hanyuhh** [comment]
是直接改element-ui lib  中的 subMenus.js setTimeOut 时间改为0 么？

**Comment by Leopoldthecoder** [comment]
请等待我们修复

**Comment by hanyuhh** [comment]
好的，谢谢啦
