### ISSUE TITLE
[Bug Report] Set menu item active by index from method

### ISSUE THREAD

**Issue by steffanhalv** [ElemeFE/element#7514]
### Element UI version
1.4.7

### OS/Browsers version
Latest chrome

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/pj71jkyw/619/

### Steps to reproduce
Create menu item and try to set menu item active by index and ref

### What is Expected?
Menu item should be set by index

### What is actually happening?
Nothing

**Comment by Leopoldthecoder** [comment]
You can set `activeIndex`: https://jsfiddle.net/pj71jkyw/621/ .

**Comment by steffanhalv** [comment]
Ah, thank you
