### ISSUE TITLE
[Feature Request] increases the switch to control whether the Messagebox.prompt component triggers the confirm event when it hits the enter

### ISSUE THREAD

**Issue by Tronsfey** [ElemeFE/element#7516]
### Existing Component
是

### Component Name
Messagebox

### Description
在使用Message.prompt获取用户输入的时候，使用拼音输入法输入类似‘容器pro探针’这种内容的时候，由于大部分人习惯不切换输入法直接敲完‘pro’之后再回车获取pro的英文输入，但这时候Messagebox的confirm事件已经被触发（见代码:https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.vue#L18）
这样直接导致了用户输入的意外中断，用户体验欠佳。

**Comment by Leopoldthecoder** [comment]
Fixed in #7534. Now hitting enter while compositing Chinese characters will not trigger confirm.
