### ISSUE TITLE
[Bug Report] datetimerange doesn't show end time date's active indicator

### ISSUE THREAD

**Issue by alashow** [ElemeFE/element#7519]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
osx / chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/fm71Lvsd/](https://jsfiddle.net/fm71Lvsd/)

### Steps to reproduce
Select start date
Select end date from second panel (days later than 6th of the month).

### What is Expected?
End date indicator

### What is actually happening?
No indicator

**Comment by wacky6** [comment]
Does your timezone made a switch from or to Day Saving Time? If so: https://github.com/ElemeFE/element/issues/7443

**Comment by alashow** [comment]
Oh, right, my timezone is also America/Chicago. Tried changing to other timezone and it worked properly.
