### ISSUE TITLE
[Bug Report] Dialog Title Slot need to swap with Close Button position

### ISSUE THREAD

**Issue by yockii** [ElemeFE/element#7525]
### Element UI version
1.4.7

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/vt2esjvo/1/](https://jsfiddle.net/vt2esjvo/1/)

### Steps to reproduce
关闭按钮位置在title之下，明显不协调

### What is Expected?
位置对调，关闭按钮正确出现在右上方

### What is actually happening?
无

**Comment by huguangju** [comment]
不是Bug。

div是块级元素，换成span之类的行内元素就行了。
```js
<span slot="title">title title title</span>
```

或者设置div样式为 `display: inline-block;`。
