### ISSUE TITLE
[Bug Report] select tag by election in optional state to the optional state label options for the style of deformation

### ISSUE THREAD

**Issue by cwc845982120** [ElemeFE/element#7526]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
Google Chrome版本 61.0.3163.100（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
1.select标签多选 原先为不可选状态 disabled为true
2.使之变为可选；
3.标签选项尽可能多的时候 就会出现样式错位的情况

### What is Expected?
select标签多选 在由不可选状态变为可选状态时select标签内的选项样式正确

### What is actually happening?
select标签多选 在由不可选状态变为可选状态时select标签内的选项样式错位

**Comment by Leopoldthecoder** [comment]
Fixed in #7534
