### ISSUE TITLE
[1.0.0-rc.8] table 组件列宽不能自适应

### ISSUE THREAD

**Issue by niceue** [ElemeFE/element#753]
### ElementUI version
1.0.0-rc.8

### OS/Browers version
win10/Chrome 53

### Vue version
2.0.3

### Reproduction Link
https://jsfiddle.net/niceue/jd89oerx/

### Steps to reproduce
全部列都设置宽度，table 设置 `style="width:100%"`

### What is Expected?
所有列根据宽度比例自适应

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/1498854/19847649/5e21f7aa-9f83-11e6-8a4a-fc1a96df1671.png)

另外如果留一列不设置宽度是可以撑满宽度，但是只有一列自适应比较难看，不协调

**Comment by cgkoreyoshi** [comment]
min-width可以用了

**Comment by furybean** [comment]
这是刻意这么做的，把 width 和 min-width 做了区分。width 就是期望的宽度，min-width 是会均分剩余的空间的。你全部替换为 min-width 即可满足你的需求。

**Comment by niceue** [comment]
@cgkoreyoshi
哦，`min-width` 确实生效了。
我还不知道这个属性，因为官方文档没有说明，release 里面也没有说明  
![image](https://cloud.githubusercontent.com/assets/1498854/19848222/f1fa6540-9f86-11e6-99c0-40462bd354ca.png)

**Comment by furybean** [comment]
@niceue 这个是从 rc1 就存在的属性，被遗漏了，刚刚已经合并。

我们的开发版会编译到这个地址：https://elementui.github.io/dev/#/component/table

element.eleme.io 用的是最新的稳定版。

**Comment by huoguozhang** [comment]
其他设为min-width,一项不设
