### ISSUE TITLE
[Bug Report] horizental scrollbar appears in table component when table size changes

### ISSUE THREAD

**Issue by hchaojie** [ElemeFE/element#7530]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
windows10 / chrome 61, edge 40

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/tk76u3um/](https://jsfiddle.net/tk76u3um/)

### Steps to reproduce
1. open https://jsfiddle.net/tk76u3um/
2. drag the editor splitter left and right to resize the result window, see how the inner table component changes
if you drag the splitter right, the horizental scrollbar will apear. it's ugly and annoying.
this issue is very common and can be easily reproduced for an admin-template site, see this related issue:
https://github.com/PanJiaChen/vue-element-admin/issues/247#issuecomment-337097296

### What is Expected?
no scrollbar blinking during drag

### What is actually happening?
scrollbar appears during drag

**Comment by DimitrisNL** [comment]
Have this problem also. Would like an workaround!

**Comment by PanJiaChen** [comment]
I think it caused by the code of
```css
.el-table__body-wrapper {
    overflow: auto;
}
```
but you can't simply remove it, In some cases it is necessary, i think solved by the official is the best. And l find  [ant](https://ant.design/components/table-cn/) has hacked it.
