### ISSUE TITLE
[Bug Report] NavMenu navigation menu component two Bug

### ISSUE THREAD

**Issue by Undefined123456789** [ElemeFE/element#7536]
### Element UI version
1.4.7

### OS/Browsers version
win10

### Vue version
2.5.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
当菜单collapse=false，为收缩状态时，并且自己菜单都是el-submenu（也就是子级菜单都有子菜单的时候）会出现以下两个问题：
①菜单面板的宽度没有自适应宽度，会出现菜单文字被箭头挡住的问题；
②在同级的el-submenu菜单上，鼠标来回移动，菜单面板会被关闭的问题；
请修复，祝element-ui越来越好！

### What is Expected?
当菜单collapse=false，为收缩状态时，并且自己菜单都是el-submenu（也就是子级菜单都有子菜单的时候）会出现以下两个问题：
①菜单面板的宽度没有自适应宽度，不会出现菜单文字被箭头挡住的问题；
②在同级的el-submenu菜单上，鼠标来回移动，菜单面板不会被关闭；

### What is actually happening?
当菜单collapse=false，为收缩状态时，并且自己菜单都是el-submenu（也就是子级菜单都有子菜单的时候）会出现以下两个问题：
①菜单面板的宽度没有自适应宽度，会出现菜单文字被箭头挡住；
②在同级的el-submenu菜单上，鼠标来回移动，菜单面板会被关闭；

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
