### ISSUE TITLE
Carousel 是否可用考虑添加一个 loop 属性

### ISSUE THREAD

**Issue by xunjianxiang** [ElemeFE/element#7538]
Carousel 是否可用考虑添加一个 loop 属性，很多场景下，需要禁止循环播放，期望可用添加一个 loop 属性，增加这个组件的灵活性。

**Comment by huguangju** [comment]
不是有 `autoplay` 么

**Comment by xunjianxiang** [comment]
autoplay 是自动播放，而我设想的 loop 是是否可用循环，也就是说是否可用从最后一张图片切换到第一章图片。
这个 loop 属性应该是在 autoplay 为 false 的时候启用。
