### ISSUE TITLE
[Bug Report] DatePicker daterange mode, chrome 57 can not choose the date

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#7539]
### Element UI version
1.4.7

### OS/Browsers version
win10/chrome 57

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/e6jvgge8/](https://jsfiddle.net/e6jvgge8/)

### Steps to reproduce
点击日期框, 弹出控件后, 无法选择日期

### What is Expected?
可以正常选择日期

### What is actually happening?
部分浏览器不能选择日期, chrome 61, 64 / safari 11下测试正常

**Comment by Leopoldthecoder** [comment]
有动图吗？

**Comment by lincenying** [comment]
![gif](https://user-images.githubusercontent.com/10840991/31655182-a9e5435e-b35a-11e7-85cf-bfc625390135.gif)

**Comment by lincenying** [comment]
点很多下才会突然有用

**Comment by Leopoldthecoder** [comment]
能否帮忙验证下 2.0 里的 DatePicker 是否正常？https://jsfiddle.net/e6jvgge8/1/

**Comment by ZhongyiChen** [comment]
@Leopoldthecoder 您好，我的Chrome版本是 56.0.2924.87 (64-bit)，对ele2.0的DatePicker也是不可以选择的

**Comment by lincenying** [comment]
@Leopoldthecoder  在chrome 57和1.4.7下一样的问题, 要点很多次, 才突然有用...

**Comment by lyixuan** [comment]
DatePicker daterange 在 QQ 浏览器9.6.4 ， win8 有同样的问题

**Comment by crper** [comment]
我也遇到了这样的问题;

win 10 : 360 ,chrome 57 个别低一些的版本,QQ 全军覆没;

chrome 61 和 firefox 正常;


```json

 "dependencies": {
    "axios": "^0.16.2",
    "element-ui": "^1.4.7",
    "es6-promise": "^4.1.1",
    "fastclick": "^1.0.6",
    "lodash": "^4.17.4",
    "moment": "^2.19.1",
    "normalize.css": "^7.0.0",
    "qs": "^6.5.1",
    "vue": "^2.5.2",
    "vue-router": "^2.8.1"
  }

```

**Comment by zsedcbm** [comment]
同样不能用,更奇葩的是,在同一个浏览器(360极速浏览器9,chrome内核55 )下,
我下载的vue-element-admin 项目中引用的是element-ui:'1.4.2' 在这个里面是可以正常使用 date-picker
后来我创建了一个单独的页面,却不能正常使用,下面的代码还是从官网直接复制过来的.

`
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css">
</head>
<body>
  <div id="app">
  	    <el-date-picker
      v-model="value6"
      type="daterange"
      placeholder="选择日期范围">
    </el-date-picker>
    <el-button @click="visible = true">按钮</el-button>
    <el-dialog v-model="visible" title="Hello world">
      <p>欢迎使用 Element</p>
    </el-dialog>
  </div>
</body>
  
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
        return { visible: false,value6:'' }
      }
    })
  </script>
</html>
`

**Comment by zsedcbm** [comment]
找到问题了,貌似是vue的bug吧,我把vue的版本修改为 2.4.2 就能够正常选择了.

**Comment by zsedcbm** [comment]
@Leopoldthecoder  我把vue版本换成2.4.4版本可以正常选择日期范围
换成最新的2.5.2版本不能正常运行.

**Comment by lazy1993** [comment]
在dialog里面的datepicker第一次能用，取消之后就再也不能用了。
原因是dialog的遮罩层的z-index在弹窗再次打开后会设置的比datapicker的z-index高。
这应该是bug吧、、、

**Comment by zcweng** [comment]
我也遇到同样的问题了，能弹出选择日期框，点不了

"vue": "^2.5.2",
"element-ui": "^1.4.8",
浏览器：360安全浏览器

**Comment by Leopoldthecoder** [comment]
在[这个 commit](https://github.com/ElemeFE/element/pull/7838/commits/9a43d8a008cdd0465a33e5f947e3aaf506794b28) 里绕了一下，现在使用上没问题了。等这些浏览器升级内核之后会把这段代码去掉。
