### ISSUE TITLE
[Feature Request] Form inputs and submit event

### ISSUE THREAD

**Issue by apexJCL** [ElemeFE/element#7544]
### Existing Component
Yes

### Component Name
Form

### Description
Scenario:
Login form, filling username then password

Expected behaviour:
Pressing enter triggers the submit action of the form

Current behaviour:
Nothing happens

**Comment by Leopoldthecoder** [comment]
You need to listen to the key events of `<el-input>`

**Comment by apexJCL** [comment]
How?
I've tried with @keyup, but it doesn't trigger. If you mean to use the @change event, wouldn't it be too "verbose"?

**Comment by Leopoldthecoder** [comment]
Check out the first question of https://github.com/ElemeFE/element/blob/dev/FAQ.md
