### ISSUE TITLE
[Bug Report] size='mini' does not work when Select set multiple and filterable

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#7549]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
Windows10/Chrome  60.0.3112.113

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/rh7q6ego/](https://jsfiddle.net/rh7q6ego/)

### Steps to reproduce
no

### What is Expected?
normal mini size

### What is actually happening?
bigger

**Comment by Leopoldthecoder** [comment]
Fixed in #7559
