### ISSUE TITLE
[Bug Report] prop "icon" of "autocomplete" is not working in version ^2.0

### ISSUE THREAD

**Issue by phuocnt0612** [ElemeFE/element#7550]
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
Ubuntu 16.04/Chrome 60.0.3112.113

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/622/](https://jsfiddle.net/pj71jkyw/622/)

### Steps to reproduce
None

### What is Expected?
The presence of search icon

### What is actually happening?
None icon is displayed

**Comment by Leopoldthecoder** [comment]
Yes, I also noticed this bug yesterday. In 2.0, `icon` and `on-icon-click` of Autocomplete are removed, so to add an icon you need to use prefix or suffix slot (not released yet).

I have updated the [release note](https://github.com/ElemeFE/element/releases/tag/v2.0.0-alpha.1).
