### ISSUE TITLE
[Bug Report] set `max` greater than `min` for Slider, the page will not respond.

### ISSUE THREAD

**Issue by hujiulong** [ElemeFE/element#7551]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
OS X / Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/ftovqchL/1/](https://jsfiddle.net/ftovqchL/1/)

### Steps to reproduce
1. add a `Slider` component
2. set `min` value greater than `max`

the page will not be able to respond

### What is Expected?
just log an warning

### What is actually happening?
the page will not be able to respond

**Comment by hujiulong** [comment]
当给Slider组件的min设置一个大于max的值，页面就直接崩了。
在jsfiddle都不太好写例子，因为一运行页面就动不了了，所以只好先注释掉。

挺严重的问题，请尽快修复.

**Comment by Leopoldthecoder** [comment]
这个还是用户自己控制吧。

**Comment by hujiulong** [comment]
可以用户自己控制，但是只要这样设置一个值页面就会崩溃
