### ISSUE TITLE
[Bug Report] radio not working in dialog

### ISSUE THREAD

**Issue by morning-king** [ElemeFE/element#7563]
### Element UI version
1.4.7

### OS/Browsers version
mac os x

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/51jfymxf/](https://jsfiddle.net/51jfymxf/)

### Steps to reproduce
1. click form diaolog;
2. click radio ,not working

### What is Expected?
radio is checked

### What is actually happening?
radio is not checked

**Comment by pengyongisme** [comment]
I met this question too
