### ISSUE TITLE
[Bug Report] Table component scroll bar exception problem

### ISSUE THREAD

**Issue by wwwwwwcccccc** [ElemeFE/element#7564]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
chrome last

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/Wangchen/pen/eERPaY](https://codepen.io/Wangchen/pen/eERPaY)

### Steps to reproduce
当表格的列数过多并且添加有总计属性，出现水平滚动时，滚动条发生错位。

### What is Expected?
滚动条出现在表格的底部（footer部分），而不是body部分

### What is actually happening?
滚动条出现在表格的中部（body部分），而不是footer部分

**Comment by furybean** [comment]
@wwwwwwcccccc  我验证了下，这个问题在最新版本已经修复了：https://codepen.io/anon/pen/rpqYWV

**Comment by furybean** [comment]
@wwwwwwcccccc 我测试下来是的

**Comment by wwwwwwcccccc** [comment]
@furybean   
希望官方有时间可以更新下这个问题。
https://codepen.io/Wangchen/pen/eERPaY

**Comment by furybean** [comment]
@wwwwwwcccccc 
我说的是错位问题。如果你指的是「滚动条出现在表格的底部（footer部分），而不是body部分」，这个短时间内尚无计划。
