### ISSUE TITLE
[Bug Report] Sub tabs does'nt work fine in a tab

### ISSUE THREAD

**Issue by lfaveur** [ElemeFE/element#7565]
### Element UI version
1.4.7

### OS/Browsers version
Ubuntu

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/garlacour/6nemn8aa/](https://jsfiddle.net/garlacour/6nemn8aa/)

### Steps to reproduce
I do a simple tabs, in the first tab i put 2 others tabs

### What is Expected?
the first sub tab have to be set to active

### What is actually happening?
active don't work fine when i use sub tabs. The CSS style is not set correctly I dont know why ... :/ Thanks for any help

**Comment by Leopoldthecoder** [comment]
There is no `toto` in `data`: https://jsfiddle.net/6nemn8aa/1/

**Comment by lfaveur** [comment]
Thx
