### ISSUE TITLE
[Feature Request] adds the function of closing all tabs in Tabs

### ISSUE THREAD

**Issue by merlin95X** [ElemeFE/element#7568]
### Existing Component
是

### Component Name
Tabs

### Description
Tabs标签页过多的话一个个关起来很麻烦，希望能提供关闭所有标签页的功能。

**Comment by Leopoldthecoder** [comment]
你可以直接操作数组：https://jsfiddle.net/kLcx1cgs/

**Comment by merlin95X** [comment]
emmm...remove all的功能能不能放在tab页签里，所以我才提的feature request.

**Comment by Leopoldthecoder** [comment]
可能不是一个很普遍的需求，所以暂时不会增加支持。倒是可以用 CSS 来达成：https://jsfiddle.net/kLcx1cgs/2/

**Comment by merlin95X** [comment]
好的，谢啦
