### ISSUE TITLE
[Bug Report] MessageBox.confirm triggers the cancel event when the button is clicked on the upper right corner, which is not usually expected by the user, and the user's expectation is only to close the frame.

### ISSUE THREAD

**Issue by hungenqianqiu** [ElemeFE/element#7574]
### Element UI version
1.4.6

### OS/Browsers version
各种版本

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Lfz450vs/1/](https://jsfiddle.net/Lfz450vs/1/)

### Steps to reproduce
调用实例的$confirm方法，会出现一个弹窗；点击弹窗右上角的叉号，会触发cancel事件

### What is Expected?
点击右上角叉号，仅仅需要关闭弹窗即可

### What is actually happening?
不仅关闭的弹窗，还触发了取消事件，和点击取消按钮行为重叠

**Comment by hungenqianqiu** [comment]
这个bug什么时候能修复呢？

**Comment by Leopoldthecoder** [comment]
不是 bug，关闭弹窗等同于取消。未有其他用户对这一行为提出异议，如果你确实需要区分关闭按钮和取消按钮，请考虑自行实现一个类似组件。
