### ISSUE TITLE
[交互优化]  el-input 组件Input Events应该添加keypress

### ISSUE THREAD

**Issue by eltonchan** [ElemeFE/element#7575]
现在如果要触发键盘事件 还需要自己去封装一层，是否考虑可以给el-input组件开放keypress事件。毕竟Enter提交的场景是很常见的。

**Comment by Leopoldthecoder** [comment]
不需要，你应该是没有加 `native` 修饰符：`<el-input @keyup.native.enter="xxx" />`

**Comment by eltonchan** [comment]
确实可以，之前没有想到这样使用。还有 blur focus 事件 可以用 @blur.native.capture

**Comment by Andyliwr** [comment]
@Leopoldthecoder 为什么我el-button加上了native还是不行？
