### ISSUE TITLE
[Bug Report], when the header is dynamically obtained, the sorting method sort-method can not achieve the specific column sorting function.

### ISSUE THREAD

**Issue by 1008611** [ElemeFE/element#7578]
### Element UI version
1.4.2

### OS/Browsers version
Chrome

### Vue version
2.4.2

### Reproduction Link
[http://jsfiddle.net/C__C/hhv54tcp/](http://jsfiddle.net/C__C/hhv54tcp/)

### Steps to reproduce
当表格的表头是动态获取的时候，使用sort-method方法时候，不能获取到具体列的相关数据（获取的是整个table数据），所以无法具体到相应列进行排序。

### What is Expected?
可以添加个相应列的参数，排序时候有个标识。

### What is actually happening?
只返回了个 a,b. Function(a, b)

**Comment by Leopoldthecoder** [comment]
http://jsfiddle.net/hhv54tcp/3/
