### ISSUE TITLE
[Feature Request] [Layout - Col Attributes] Add support for extra large (xl) screens

### ISSUE THREAD

**Issue by Elfayer** [ElemeFE/element#7581]
### Existing Component
Yes

### Component Name
el-col

### Description
I use 2560x1440px screen at work. These screens are more and more common.

I would require a way to set `el-col` size above the current limitation:
xs > sm > md > lg > **xl** *(missing)*

As an example: Vuetify has this separator on their grid system: https://vuetifyjs.com/layout/grid

But I 100% prefer to use ElementUI =)

Would it  be possible to add this feature?

**Comment by Leopoldthecoder** [comment]
In version 2.0 we'll have a new breakpoint `xl` for screens wider than 1920px. Besides, all the breakpoints are SCSS variables, so you can reset them to whatever screen widths you see fit.
