### ISSUE TITLE
[Feature Request] How does the form <el-form-item> verify that the <el-upload> uploaded file is

### ISSUE THREAD

**Issue by frontng** [ElemeFE/element#7582]
### Existing Component
是

### Component Name
<el-upload>

### Description
How does the form <el-form-item> verify that the <el-upload> file is uploaded

**Comment by creativemind1** [comment]
Any update on this? I'm also in need of this feature.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/k2om0b28/
