### ISSUE TITLE
el-input change 事件失效

### ISSUE THREAD

**Issue by Whalefallsea** [ElemeFE/element#7592]
`<el-input placeholder="请输入邮箱地址" type="text" v-model="" @keyup.enter.native="loginAction()" @change="change"></el-input>`
使用change监听时，input框的值改变不能触发change事件，但是这时如果是input输入框失焦确能触发事件。
总的来说就是change事件只在input值改变并且失去焦点的时候才会触发，其它情况不触发事件。

**Comment by Whalefallsea** [comment]
补充版本信息："element-ui": "2.0.0-alpha.3", "vue": "2.5.2",

**Comment by Leopoldthecoder** [comment]
请参考这个版本的更新日志。

**Comment by Whalefallsea** [comment]
感谢你的回答！！

**Comment by WLyKan** [comment]
经常忘记，这里记录下。

> change 事件现在仅在输入框失去焦点或用户按下回车时触发，与原生 input 元素一致。如果需要实时响应用户的输入，可以使用 input 事件

**Comment by feifei511** [comment]
请教一个  elementUI 的问题. form 表单 的 input 输入框. 只输入一个数字或字母 就自己 失去焦点了.
`<el-form :model="tarnshisForm" :rules="tarnshisrules" ref="tarnshisForm" label-width="80px" :label-position="CM_FORM.CM_COL_ALIGN">
            
            <el-row :gutter="10">
                <el-col :span="colWidth">
                    <el-form-item label="开始时间" prop="startDate">
                    <el-date-picker v-model="tarnshisForm.startDate" type="date" value-format="yyyyMMdd" placeholder="请选择开始日期" :clearable="true" style="width:80%;" size="small"></el-date-picker>
                    </el-form-item>
                </el-col>
                <el-col :span="colWidth">
                    <el-form-item label="至" prop="endDate">
                    <el-date-picker v-model="tarnshisForm.endDate" type="date" value-format="yyyyMMdd" placeholder="请选择结束日期" :clearable="true" style="width:80%;" size="small"></el-date-picker>
                </el-form-item>
                </el-col>
                <el-col :span="colWidth">
                <el-form-item label="密码" prop="goToPassWord">
                    <el-input  v-model="tarnshisForm.goToPassWord" size="small" :clearable="true" placeholder="请输入密码"  style="width:80%"></el-input> 
                </el-form-item>
                </el-col>
                <el-col :span="colWidth">
                <el-form-item label="查询级别" prop="usersSelect">
                    <el-select size="small" v-model="tarnshisForm.usersSelect" @change="changeLevel($event)" style=" width:80%">
                    <el-option label="用户级" value="1"></el-option>
                    <el-option label="账户级" value="0"></el-option>
                    
                    </el-select>
                </el-form-item>
                </el-col>
            </el-row>
            <div style="text-align:center;">
                <el-button size="small" type="primary" @click="extractPassWorld">提取密码</el-button>
                <el-button size="small" type="primary" @click="tarnshisFormQuer('tarnshisForm')">查询</el-button>
            </div>
        </el-form>`

**Comment by kuige** [comment]
> 经常忘记，这里记录下。
> 
> > change 事件现在仅在输入框失去焦点或用户按下回车时触发，与原生 input 元素一致。如果需要实时响应用户的输入，可以使用 input 事件

文档里面竟然没写 input 事件。。
<img width="796" alt="image" src="https://user-images.githubusercontent.com/8212800/46912401-2b6f4280-cfa7-11e8-8048-1290a6dcf6a9.png">

**Comment by feifei511** [comment]
这个问题解决了,我用到方法是, 在生命周期 mounted 中, 用 this.$set() 的方法, 写表单元素的验证,再用 this.$nextTick, 来保证加载时不验证.具体解决方法如下:
this.$set(this.rules, "telNum", [
{
required: true,
trigger: "blur",
validator: (rule, value, callback) = {
if (!value) {
callback(new Error("请输入正确的号码"));
} else if (!BillingCommon.regPhone(value)) {
callback(new Error("请输入正确的11位手机号码"));
} else {
callback();
}
}
}
]);
this.$nextTick(function() {
this.$refs["ruleForm"].resetFields();
});


原始邮件
发件人:sangenotifications@github.com
收件人:ElemeFE/elementelement@noreply.github.com
抄送:刘祎飞wdlcfeixiang@163.com; Commentcomment@noreply.github.com
发送时间:2018年10月14日(周日) 11:51
主题:Re: [ElemeFE/element] el-input change 事件失效 (#7592)


经常忘记，这里记录下。
change 事件现在仅在输入框失去焦点或用户按下回车时触发，与原生 input 元素一致。如果需要实时响应用户的输入，可以使用 input 事件
文档里面竟然没写 input 事件。。

**Comment by upupzealot** [comment]
@Leopoldthecoder 麻烦在文档里更新一下。要不是搜到了这个 issue，甚至都不知道有 input 事件

**Comment by mdzz1** [comment]
el-input-number 也有同样的问题  在输入框里面改变值  blur 值才会生效

**Comment by ChaoyueZhao** [comment]
更新 input 事件 +1
