### ISSUE TITLE
[Bug Report] append slot leads to the disappearance of fixed column

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#7594]
### Element UI version
1.4.7

### OS/Browsers version
mac os

### Vue version
2.5.2

### Reproduction Link
[http://jsfiddle.net/zpczjl/4ctx4kr5/](http://jsfiddle.net/zpczjl/4ctx4kr5/)

### Steps to reproduce
1. 点击toggle data的按钮
2. 数据被清空，表格没数据了
3. 再次点击按钮
4. 数据被重置，但是fixed colum里的内容消失

### What is Expected?
数据被重置，但是fixed colum里的内容正常显示

### What is actually happening?
数据被重置，但是fixed colum里的内容消失

**Comment by Leopoldthecoder** [comment]
重现链接好像不太对，里面没有 append slot，请核实。

**Comment by njleonzhang** [comment]
@Leopoldthecoder 更新了请查看

**Comment by Leopoldthecoder** [comment]
Fixed in #7590

**Comment by njleonzhang** [comment]
will release with next version?

**Comment by Leopoldthecoder** [comment]
This fix is released with 2.0.0-beta.1. Is it possible for you to upgrade Element to 2.0 in vue-data-tables?

**Comment by njleonzhang** [comment]
Sure, It's in beta now, will support ASAP.  :)
