### ISSUE TITLE
[Bug Report] Table header align not working

### ISSUE THREAD

**Issue by tridcatij** [ElemeFE/element#7597]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
Ubuntu 17

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/632/](https://jsfiddle.net/pj71jkyw/632/)

### Steps to reproduce
Use ***theme-chalk/index.css*** and add ***align*** and(or) ***header-align*** props to the <el-table-column> and set it to the 'right' or 'center'

### What is Expected?
Header aligning

### What is actually happening?
Aligning is not working. 

To solve it we need to change this
```
.el-table td.is-left, .el-table th {
    text-align: left;
}

.el-table td.is-center, .el-table th {
    text-align: center;
}

.el-table td.is-right, .el-table th {
    text-align: right;
}
```

to this:
```
.el-table td.is-left, .el-table th.is-left {
    text-align: left;
}

.el-table td.is-center, .el-table th.is-center {
    text-align: center;
}

.el-table td.is-right, .el-table th.is-right {
    text-align: right;
}
```

**Comment by Leopoldthecoder** [comment]
Fixed in #7590
