### ISSUE TITLE
有计划做走马灯和树选择器么

### ISSUE THREAD

**Issue by yuu2lee4** [ElemeFE/element#76]
有计划做走马灯和树选择器么

**Comment by zifeixu85** [comment]
树形控件已经有了，走马灯已经在计划中。

**Comment by furybean** [comment]
@zifeixu85 这个同学应该指的是 Select 打开的内容是一棵树，可以通过树来勾选数据。

**Comment by wilsonIs** [comment]
同感，项目中有此需求，选中的可以在select中显示el-tags

**Comment by jinjinwa** [comment]
关于tree select 官方有计划做么？

**Comment by dandananddada** [comment]
解决了么？

**Comment by blooddrunk** [comment]
tree select +1

**Comment by mrdream24** [comment]
tree select +2

**Comment by CrazyWisdom** [comment]
tree select +3

**Comment by ttop5** [comment]
tree select +4

**Comment by lampo1024** [comment]
tree select +5

**Comment by linda8167** [comment]
tree select +6

**Comment by brightWeen** [comment]
tree select +7
交互可以参考 https://ant.design/components/tree-select/

**Comment by fengyun2** [comment]
tree select +8

**Comment by axhello** [comment]
tree select +9

**Comment by qinshenxue** [comment]
可以考虑用 el-popover + el-input 来实现 tree-select
```js
<template>
    <div class="v-tree-select">
        <el-popover
                ref="popover"
                placement="bottom"
                popper-class="v-tree-select-popover"
                trigger="click" :visible-arrow="false" :width="width">
            <el-tree :data="data"
                     :props="defaultProps"
                     :expand-on-click-node=false
                     @node-click="handleNodeClick"></el-tree>
            <el-input slot="reference" ref="ipt" v-model="selectedNodeLabel"></el-input>
        </el-popover>
    </div>
</template>

<script>
    export default {
        name: "v-tree-select",
        data() {
            return {
                selectedNodeLabel: null,
                width: 0,
                data: [{
                    label: '一级 1',
                    children: [{
                        label: '二级 1-1',
                        children: [{
                            label: '三级 1-1-1'
                        }]
                    }]
                }, {
                    label: '一级 2',
                    children: [{
                        label: '二级 2-1',
                        children: [{
                            label: '三级 2-1-1'
                        }]
                    }, {
                        label: '二级 2-2',
                        children: [{
                            label: '三级 2-2-1'
                        }]
                    }]
                }, {
                    label: '一级 3',
                    children: [{
                        label: '二级 3-1',
                        children: [{
                            label: '三级 3-1-1'
                        }]
                    }, {
                        label: '二级 3-2',
                        children: [{
                            label: '三级 3-2-1'
                        }]
                    }]
                }],
                defaultProps: {
                    children: 'children',
                    label: 'label'
                }

            }
        },
        mounted() {
            this.width = this.$refs.ipt.$el.offsetWidth
        },
        methods: {
            handleNodeClick(data) {
                this.selectedNodeLabel = data.label
                this.$refs.popover.handleBlur()
            }
        }
    }
</script>

<style lang="less">
    .v-tree-select-popover.el-popper[x-placement^=bottom] {
        margin-top: 0;
    }

    .v-tree-select-popover.el-popper[x-placement^=top] {
        margin-bottom: 0;
    }
</style>
```

**Comment by zouzonghua** [comment]
tree select +10 & tree table +1

**Comment by shidianxia** [comment]
建议加入规划

**Comment by libo9527** [comment]
tree select +11

**Comment by ayiaq1** [comment]
https://github.com/ayiaq1/el-tree-select

**Comment by Blacktodreamlight** [comment]
tree select +12

**Comment by dengdengdengpan** [comment]
tree select +13

**Comment by MarshallLu** [comment]
tree select +14

**Comment by anna647** [comment]
tree select +15

**Comment by cdoer** [comment]
tree select +16

**Comment by wangdaodao** [comment]
可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select

**Comment by cdoer** [comment]
> 
> 
> 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select

考虑开源没有

**Comment by wangdaodao** [comment]
> 
> 
> > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> 
> 考虑开源没有

公司内部使用的，所以代码没开源，但是外部也可以用。

**Comment by cdoer** [comment]
> 
> 
> > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > 
> > 
> > 考虑开源没有
> 
> 公司内部使用的，所以代码没开源，但是外部也可以用。

开源一个tree-select就行了  我的哥   我们用elementui   全部替换成你们的代价也大

**Comment by cdoer** [comment]
> 
> 
> > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > 
> > 
> > 考虑开源没有
> 
> 公司内部使用的，所以代码没开源，但是外部也可以用。

或者单独打包发布tree-select

**Comment by wangdaodao** [comment]
> 
> 
> > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > 
> > > 
> > > 考虑开源没有
> > 
> > 
> > 公司内部使用的，所以代码没开源，但是外部也可以用。
> 
> 或者单独打包发布tree-select



> 
> 
> > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > 
> > > 
> > > 考虑开源没有
> > 
> > 
> > 公司内部使用的，所以代码没开源，但是外部也可以用。
> 
> 开源一个tree-select就行了 我的哥 我们用elementui 全部替换成你们的代价也大

这就是element-ui，只不过当时饿了么团队不维护，我自己fork一份后开始维护的，用法完全一样，标签和属性都没变。我们公司内部系统好多也是用的element-ui，没啥迁移成本。

**Comment by wangdaodao** [comment]
> 
> 
> > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > 
> > > 
> > > 考虑开源没有
> > 
> > 
> > 公司内部使用的，所以代码没开源，但是外部也可以用。
> 
> 或者单独打包发布tree-select

还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。

**Comment by cdoer** [comment]
> 
> 
> > > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > > 
> > > > 
> > > > 考虑开源没有
> > > 
> > > 
> > > 公司内部使用的，所以代码没开源，但是外部也可以用。
> > 
> > 
> > 或者单独打包发布tree-select
> 
> 还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。

你们的 TreeSelect 有点问题,自定义props label属性为name  开启filterable会报错,应该是检索还是使用label这个属性  而不是props设置的name

**Comment by wangdaodao** [comment]
> 
> 
> > > > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > > > 
> > > > > 
> > > > > 考虑开源没有
> > > > 
> > > > 
> > > > 公司内部使用的，所以代码没开源，但是外部也可以用。
> > > 
> > > 
> > > 或者单独打包发布tree-select
> > 
> > 
> > 还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。
> 
> 你们的 TreeSelect 有点问题,自定义props label属性为name 开启filterable会报错,应该是检索还是使用label这个属性 而不是props设置的name

感谢提醒，已经修复，待测试完毕后发布。

**Comment by cdoer** [comment]
> 
> 
> > > > > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > > > > 
> > > > > > 
> > > > > > 考虑开源没有
> > > > > 
> > > > > 
> > > > > 公司内部使用的，所以代码没开源，但是外部也可以用。
> > > > 
> > > > 
> > > > 或者单独打包发布tree-select
> > > 
> > > 
> > > 还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。
> > 
> > 
> > 你们的 TreeSelect 有点问题,自定义props label属性为name 开启filterable会报错,应该是检索还是使用label这个属性 而不是props设置的name
> 
> 感谢提醒，已经修复，待测试完毕后发布。

开源TreeSelect怎么样  利用开源社区帮你们公司打磨产品  手动狗头

**Comment by wangdaodao** [comment]
> 
> 
> > > > > > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > > > > > 
> > > > > > > 
> > > > > > > 考虑开源没有
> > > > > > 
> > > > > > 
> > > > > > 公司内部使用的，所以代码没开源，但是外部也可以用。
> > > > > 
> > > > > 
> > > > > 或者单独打包发布tree-select
> > > > 
> > > > 
> > > > 还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。
> > > 
> > > 
> > > 你们的 TreeSelect 有点问题,自定义props label属性为name 开启filterable会报错,应该是检索还是使用label这个属性 而不是props设置的name
> > 
> > 
> > 感谢提醒，已经修复，待测试完毕后发布。
> 
> 开源TreeSelect怎么样 利用开源社区帮你们公司打磨产品 手动狗头

其实之前代码是开源的，后来因为各种原因只能删除代码，但是npm包一直都在所以就这么维护着。后面试试看能不能把源码提交到element-ui上，让社区维护吧。如果单独把下拉树拿出来，有点费劲，因为这个组件就是 `el-input + el-tag + el-tooltip + el-popover + el-tree + el-scrollbar` 拼凑出来的，还是依赖element-ui。

**Comment by cdoer** [comment]
> 
> 
> > > > > > > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 考虑开源没有
> > > > > > > 
> > > > > > > 
> > > > > > > 公司内部使用的，所以代码没开源，但是外部也可以用。
> > > > > > 
> > > > > > 
> > > > > > 或者单独打包发布tree-select
> > > > > 
> > > > > 
> > > > > 还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。
> > > > 
> > > > 
> > > > 你们的 TreeSelect 有点问题,自定义props label属性为name 开启filterable会报错,应该是检索还是使用label这个属性 而不是props设置的name
> > > 
> > > 
> > > 感谢提醒，已经修复，待测试完毕后发布。
> > 
> > 
> > 开源TreeSelect怎么样 利用开源社区帮你们公司打磨产品 手动狗头
> 
> 其实之前代码是开源的，后来因为各种原因只能删除代码。后面试试看能不能把源码提交到element-ui上，让社区维护吧。如果单独把下拉树拿出来，有点费劲，因为这个组件就是 `el-input + el-tag + el-tooltip + el-popover + el-tree + el-scrollbar` 拼凑出来的，还是依赖element-ui。

兄弟 TreeSelect的源码能不能发我下,我想改改,支持的事件太少  我想把tree的一些事件弄出来  我将在源码注明是你的代码

**Comment by cdoer** [comment]
> 
> 
> > > > > > > > > 可以试试看，https://wangdaodao.gitee.io/element-gui/#/component/tree-select
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 考虑开源没有
> > > > > > > 
> > > > > > > 
> > > > > > > 公司内部使用的，所以代码没开源，但是外部也可以用。
> > > > > > 
> > > > > > 
> > > > > > 或者单独打包发布tree-select
> > > > > 
> > > > > 
> > > > > 还有，就是不要指望开源的产品能一直维护，最好自己拿源码，自己改改，把被动变主动。
> > > > 
> > > > 
> > > > 你们的 TreeSelect 有点问题,自定义props label属性为name 开启filterable会报错,应该是检索还是使用label这个属性 而不是props设置的name
> > > 
> > > 
> > > 感谢提醒，已经修复，待测试完毕后发布。
> > 
> > 
> > 开源TreeSelect怎么样 利用开源社区帮你们公司打磨产品 手动狗头
> 
> 其实之前代码是开源的，后来因为各种原因只能删除代码。后面试试看能不能把源码提交到element-ui上，让社区维护吧。如果单独把下拉树拿出来，有点费劲，因为这个组件就是 `el-input + el-tag + el-tooltip + el-popover + el-tree + el-scrollbar` 拼凑出来的，还是依赖element-ui。
我的邮箱  1249492252@qq.com
