### ISSUE TITLE
[Bug Report] Cannot display key value of object in autocomplete

### ISSUE THREAD

**Issue by takotuesday** [ElemeFE/element#7600]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
Windows 10, Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/sp1mt722/](https://jsfiddle.net/sp1mt722/)

### Steps to reproduce
Add props object to autocomplete

### What is Expected?
Autocomplete would display the 'link' property when selected.

### What is actually happening?
Autocomplete is displaying the 'value' property

**Comment by Leopoldthecoder** [comment]
You misspelled the word `props`: https://jsfiddle.net/sp1mt722/1/

**Comment by takotuesday** [comment]
@Leopoldthecoder apologies for the typo, but I believe my issue was not addressed. See this fiddle:

https://jsfiddle.net/sp1mt722/1/


Once a link object is selected, the field displays '[object Object]' instead of the label which is link.

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/31851537-4881925e-b62d-11e7-8785-0fefa13aaa30.gif)

Didn't reproduce it.
