### ISSUE TITLE
[Bug Report] The check all operation doesn't work in checkbox

### ISSUE THREAD

**Issue by Li-Alex** [ElemeFE/element#7601]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/ujwvdy6g/](https://jsfiddle.net/ujwvdy6g/)

### Steps to reproduce
just click the check-all button

### What is Expected?
All the checkbox will be checked

### What is actually happening?
error console,  Error in event handler for "change": "TypeError: Cannot read property 'checked' of undefined"

**Comment by Li-Alex** [comment]
It seems that checkbox-button component has emited 2 params, model and event. So the handle method in jsfiddle should be `handleCheckAllChange(val, event)`, and then it works.

**Comment by Leopoldthecoder** [comment]
Thanks for the heads-up, I'll fix the example.
