### ISSUE TITLE
[Bug Report] cascader and form collocation appear, prompt does not disappear

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/element#7606]
### Element UI version
1.4.7

### OS/Browsers version
Google Chrome 版本 61.0.3163.100（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/acmemca/Lsbtonsa/1/](https://jsfiddle.net/acmemca/Lsbtonsa/1/)

### Steps to reproduce
cascader与form搭配使用，cascader没有默认值；
点击提交，执行检验，显示提示语，选择地址后，提示语没有消失。

### What is Expected?
cascader与form搭配使用，cascader没有默认值；
点击提交，执行检验，显示提示语，选择地址后，提示语消失。

### What is actually happening?
cascader与form搭配使用，cascader没有默认值；
点击提交，执行检验，显示提示语，选择地址后，提示语没有消失。

**Comment by Leopoldthecoder** [comment]
The value of Cascader is an array, so you should declare it in the rules: https://jsfiddle.net/Lsbtonsa/2/

**Comment by acmeid** [comment]
Thanks.

**Comment by shguanbin** [comment]
增加了props 依旧报错！
