### ISSUE TITLE
[Bug Report] Inconsistent getCheckedNodes() on deselection of a parent

### ISSUE THREAD

**Issue by Elfayer** [ElemeFE/element#7609]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
Windows 7 / Chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/frtjsbLu/](https://jsfiddle.net/frtjsbLu/)

### Steps to reproduce
- Deselect 'Phone'
- Deselect 'Computer'

### What is Expected?
The `this.selectedCategories` to be empty.

### What is actually happening?
`this.selectedCategories` is equal to `[ { "id": 2, "label": "Laptop" }, { "id": 3, "label": "Desktop" } ]`

`this.$refs.tree.getCheckedNodes()` is inconsistent.

**Comment by Leopoldthecoder** [comment]
Fixed in #7813
