### ISSUE TITLE
[Bug Report] el-table the same CSS style show un-same view

### ISSUE THREAD

**Issue by chqdwolf** [ElemeFE/element#7611]
### Element UI version
2.0.0-alpha.3

### OS/Browsers version
Google Chrome 版本 61.0.3163.100（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/0wbn1302/2/ https://jsfiddle.net/8qj01w0q/1/](https://jsfiddle.net/0wbn1302/2/ https://jsfiddle.net/8qj01w0q/1/)

### Steps to reproduce
相同的CSS样式控制在不同版本下显示的效果不同。

### What is Expected?
相同的CSS样式控制在不同版本下显示的效果不同。

### What is actually happening?
相同的CSS样式控制在不同版本下显示的效果不同。

**Comment by Leopoldthecoder** [comment]
主题已经更新了，现在的 Table 会带有 padding。
