### ISSUE TITLE
Element 2.0.0-beta.1 已发布 🎉

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7612]
更新日志：https://github.com/ElemeFE/element/releases/tag/v2.0.0-beta.1

从 Beta 版本开始，我们鼓励各位用户开始在项目中使用 Element 2.0，也希望大家向我们及时反馈遇到的问题。

Element 2.0 截止目前的全部改动可以点击[这里](https://gist.github.com/Leopoldthecoder/2e4e60617933494d983432f7021c1ea0)查看。

**Comment by yoyo837** [comment]
出第一个正式版我就升级上来

**Comment by Lubyam** [comment]
正在学习 新技能

**Comment by sndwow** [comment]
支持

**Comment by ymsh** [comment]
[Vue warn]: Injection "elFormItem" not found
我的表单全报这样的错误，请问我要怎么处理？？？已升级到2.0beta1

**Comment by Leopoldthecoder** [comment]
@ymsh 确保你的 Vue 和 Element 都是最新版。

**Comment by ymsh** [comment]
@Leopoldthecoder 
我的vue是2.3.3版本，需要升级到哪个版本比较好？？

**Comment by Leopoldthecoder** [comment]
@ymsh 2.5.2

**Comment by BruceFan-FS71** [comment]
强烈支持

**Comment by ymsh** [comment]
@Leopoldthecoder 谢谢，更新到vue2.5.2，问题已解决

**Comment by xf123456** [comment]
element官网访问好卡吖

**Comment by liuzhaozhao** [comment]
支持，支持，强烈支持

**Comment by xuelabi123** [comment]
up！什么时候发正式版吖

**Comment by ukhack** [comment]
我抢先体验了。可是项目报错：Failed to compile with 1 errors
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'element-ui/lib/theme-default/index.css'
```
我的main.js代码:
```
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
Vue.use(ElementUI)
```
是不是你们没有把element-ui中旧依赖删除？

**Comment by zhaonan420** [comment]
#### 分页样式变化挺大的呀

`1.47` 
![1](https://user-images.githubusercontent.com/23193223/31850778-220f1e12-b68b-11e7-8fb7-4c883576e460.png)

`2.0`
![2](https://user-images.githubusercontent.com/23193223/31850782-2fb8ffb0-b68b-11e7-8257-9019ecf62cb7.png)

**Comment by LoverMaker** [comment]
不敢升2.0了，这样式也太丑了吧，越来越丑了，哎。

**Comment by julytian** [comment]
@Leopoldthecoder Transfer 穿梭框的输入框与文字样式位置有点错乱了

**Comment by dcxy0** [comment]
啥时候能支持一下移动端就好了

**Comment by yoyoping** [comment]
请问下  直接把vue和element 通过npm升上去就可以了吗

**Comment by zuibunan** [comment]
官网滚动条太细了，有时候想拖动滚动条往下看说明，选不中滚动条

**Comment by conanguyw** [comment]
daterange之类的日期范围选择的控件有问题啊，选不了

**Comment by lhy666** [comment]
确实整理来说组件可用性更高了，但是样式真的有点变丑了。。还有点小建议就是既然导航菜单都给了当前激活菜单的文字颜色，就能顺便给个当前激活菜单的背景颜色嘛 @Leopoldthecoder

**Comment by GitHub-Leon** [comment]
请问，怎么我的EL UI升级到1.3.7后，就无法升级了呢？

**Comment by GitHub-Leon** [comment]
npm u element-ui 执行后，版本依然是V1.3.7 @Leopoldthecoder

**Comment by yoyo837** [comment]
直接改package.json, 然后npm i/yarn 一下

**Comment by GitHub-Leon** [comment]
@yoyo837 我试试看，p.json里面改版本号，对么？

**Comment by GitHub-Leon** [comment]
@lhy666 你说的这个命令@next是指对应的版本号吧？

**Comment by lhy666** [comment]
不用，我这句话你直接复制就好了，官方提供的。
![default](https://user-images.githubusercontent.com/30484206/31871075-55b363fe-b7e4-11e7-9fa6-c1085a29a90d.png)

**Comment by GitHub-Leon** [comment]
@lhy666 这样会不会更新到2.0了呢？

**Comment by GitHub-Leon** [comment]
@lhy666 这是2.0的更新命令呀？

**Comment by lhy666** [comment]
就是更新到2.0啊。。。不然直接修改packjson把，也可以的。另外推荐yarn

**Comment by GitHub-Leon** [comment]
@yoyo837 我的json文件里面是1.4.6，但是main.js里面console出来的version是1.3.7，是怎么回事呢？

**Comment by GitHub-Leon** [comment]
@lhy666 我的json文件里面是1.4.6，但是main.js里面console出来的version是1.3.7，是怎么回事呢？

**Comment by yoyo837** [comment]
@GitHub-Leon 建议私聊，5秒一个email全部都跟着响。

**Comment by GitHub-Leon** [comment]
![image](https://user-images.githubusercontent.com/19281752/31871173-13d97300-b7e5-11e7-88fa-111531209247.png)
![image](https://user-images.githubusercontent.com/19281752/31871195-337f2dee-b7e5-11e7-84c8-475905b445fb.png)

**Comment by GitHub-Leon** [comment]
@yoyo837 sorry，打扰到你了，我很抱歉

**Comment by GodStream** [comment]
2.0部分组件点击后会出现闪现蓝边，是什么情况？

![image](https://user-images.githubusercontent.com/23089466/31871365-42bbf592-b779-11e7-9dca-c37f08cf477f.png)
@Leopoldthecoder

**Comment by SteveCruise** [comment]
等正式版再说吧，alpha版时试了一下，布局都变得不正常了

**Comment by WALLE729** [comment]
树形控件问题有点多，建议做例子的时候，层级深一些

**Comment by Noemi-** [comment]
大概啥时候有正式版哇～ 要上新项目了，想用2.0又担心正式版改动太大

**Comment by penghang** [comment]
现在还不敢直接使用，自己玩玩熟悉一下还可以，类似要修复的地方太多，用在项目中风险较大
![image](https://user-images.githubusercontent.com/7846319/31926837-b366d492-b8c3-11e7-8273-2c1d660436bb.png)

**Comment by Leopoldthecoder** [comment]
如果官网访问速度慢的话，可以尝试一下 http://element-cn.eleme.io/ 。这个站点部署在国内，理论上大陆用户的访问速度会快一些。

**Comment by Ansel** [comment]
table组件官方网站例子在Safari 11.0上表头和表格内容上下不对齐，在chrome上显示正常。应该是遗留的bug吧

**Comment by jinzhiwen** [comment]
如果导航菜单的<el-menu-item>嵌套一个<router-link> 那么就会出现这种情况：点击某菜单选项，先加载路由，样式（字体颜色等）没有变化，再次点击该菜单才会出现样式变化。难道不能使用router-link这个形式的路由么？

**Comment by jinzhiwen** [comment]
如果导航菜单的el-menu-item嵌套一个router-link 那么就会出现这种情况：点击某菜单选项，先加载路由，样式（选中效果的字体颜色等）却没有变化，再次点击该菜单才会出现样式变化。难道此处不能使用router-link这个形式的路由么？

**Comment by milixie** [comment]
![image](https://user-images.githubusercontent.com/21941529/31976123-26d51902-b8fb-11e7-825d-08008f65a3ef.png)
cuo'we错位了

**Comment by hunter007** [comment]
项目已经用1.0系列上线很长时间了，坚持在element出新版本的时候更新，这样做，是兼容最新版本需要的努力最小的。但看了2.0之后，真不敢升级。不是因为难度，而是做相关的修复工作量太大，公司根本不给这些时间。非常希望像以前一样，逐步升级，最后过度到2.0。

**Comment by yoyo837** [comment]
能做逐步升级必然无法实现结构性的改变，版本号永远会是1.x

**Comment by kevinlincg** [comment]
希望能搭配 admin模版一起推出

**Comment by wangtifang** [comment]
表格组件希望新增一个tree-table组件。可以有父子级关系的那种！

**Comment by xiefei6688** [comment]
如何设置Table 表格单个单元格背景色

**Comment by baicoding** [comment]
1.el-container布局在火狐下el-main不能自动出现垂直滚动条。
2.求教：table组件如何设置高度为100%时，固定表头啊？

**Comment by techzealot** [comment]
希望能保留以前的分页样式，感觉现在的样式体验不太好，页码很难看清楚，选中的页码和未选中的区分度太小了@Leopoldthecoder

**Comment by baicoding** [comment]
@Leopoldthecoder 
1.建议el-input等组件能注入style到原始的input中去，这样能实现字符的大小写等控制。
2.el-input-number组件不显示按钮（controls=false）的时候，样式有点奇怪，数值显示在中间了，左右会留有空边
