### ISSUE TITLE
Element 2.0.0-beta.1 released🎉 

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7613]
Changelog：https://github.com/ElemeFE/element/releases/tag/v2.0.0-beta.1

As of today, we encourage developers to start upgrading Element to 2.0. And if you see any bug or
 problem, please file an issue.

Up until now, all changes of Element 2.0 can be found [here](https://gist.github.com/Leopoldthecoder/2e4e60617933494d983432f7021c1ea0).

**Comment by alashow** [comment]
`Cannot read property 'clientHeight' of undefined`
I have this warning, but I cannot reproduce it.

```javascript
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clientHeight' of undefined"

found in

---> <ElSelect>
       <ElRow>
```
Vue `2.5.2`
Element` v2.0.0-beta.1`

**Comment by Leopoldthecoder** [comment]
@alashow Could you minify your project and push it to a GitHub repo?

**Comment by sebastiaanluca** [comment]
Quick question: can I use the previous theme in combination with Element 2.0 or does the new theme contain certain new required styles?

**Comment by bitjjj** [comment]
@alashow Set disabled to select in a dialog, this warn will show

**Comment by alashow** [comment]
@Leopoldthedecoder sorry, I was busy.

@bitjjj yes, I think I was disabling select while loading data.

**Comment by feusebio** [comment]
`vue.esm.js?efeb:571 [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clientHeight' of undefined"

found in

---> <ElSelect>
       <ElFormItem>
         <ElCol>
           <ElRow>
             <ElForm>`
I reproduced this warning when a use an event button to enable the inputs Select that was initial state disable.

**Comment by Leopoldthecoder** [comment]
The `clientHeight` error of Select will be fixed in the next release.
