### ISSUE TITLE
[Bug Report] The ‘transfer’ style is not correct on demand

### ISSUE THREAD

**Issue by miyalee** [ElemeFE/element#7616]
### Element UI version
1.4.6

### OS/Browsers version
Google Chrome 版本 61.0.3163.100（正式版本） （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

``` javascript
import { 
    ...
    Transfer } from 'element-ui'

...
Vue.component(Transfer.name, Transfer)
```

<el-transfer v-model="value1" :data="data"></el-transfer>

### What is Expected?
穿梭框的列表项每个独占一行，穿梭按钮对齐

### What is actually happening?
穿梭框的列表项显示为inline-block，穿梭按钮有奇怪的margin

<img width="513" alt="2017-10-20 4 29 10" src="https://user-images.githubusercontent.com/18900447/31815108-536c12ca-b551-11e7-9a94-3517fd7f0f74.png">
<img width="186" alt="2017-10-20 4 50 41" src="https://user-images.githubusercontent.com/18900447/31815133-6fd21dd8-b551-11e7-828e-88ca7e03d3a3.png">
<img width="160" alt="2017-10-20 4 51 46" src="https://user-images.githubusercontent.com/18900447/31815143-744e60ba-b551-11e7-8b48-1eaedf2c75b4.png">

transfer的样式被checkbox覆盖

**Comment by Leopoldthecoder** [comment]
按照你的代码实际测试了一下，没有重现这个问题。请精简你的项目，将最小可重现版本上传到 GitHub，并重新打开这个 issue。

**Comment by weilao** [comment]
跟按需引入的顺序有关，如果 Transfer 先引入则正常， Transfer 最后引入则样式错误。
