### ISSUE TITLE
There is a problem with using [Bug Report] el-aside and el-menu (collapse=true)

### ISSUE THREAD

**Issue by x1aohe** [ElemeFE/element#7619]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
macbook/chrome 62

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/ojdsd9c6/2/](https://jsfiddle.net/ojdsd9c6/2/)

### Steps to reproduce
把鼠标放在菜单上

### What is Expected?
出现完整的子菜单

### What is actually happening?
出现的子菜单不全

**Comment by Leopoldthecoder** [comment]
这种情况请覆盖一下默认样式：https://jsfiddle.net/ojdsd9c6/3/
```css
.el-aside {
  overflow: visible;
}
```

**Comment by fangxingguang** [comment]
菜单比较多时，希望出现滚动条，必须要设置overflow: auto，这时候如何处理？ @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
x 和 y 两个方向分别设置吧

**Comment by mu-yu** [comment]
> The computed values of ‘overflow-x’ and ‘overflow-y’ are the same as their specified values, except that some combinations with ‘visible’ are not possible: if one is specified as ‘visible’ and the other is ‘scroll’ or ‘auto’, then ‘visible’ is set to ‘auto’.
根据w3c的规范，x,y设置不同的值，如果有一个是`visible`是会有问题的…见[这里](https://www.w3.org/TR/css3-box/#overflow0)和[这里](https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue)

所以要处理这个问题不仅仅要设置 `el-aside` 的 overflow，里面的 `el-menu` 的也要做一定的hack…
希望官方能有封装的更完善的解决方案。@Leopoldthecoder

**Comment by mmfjx** [comment]
碰到类似问题，设置overflow为auto，collapse为true的状态下，子菜单展示不出来
