### ISSUE TITLE
when message box recive a wrong agrument and then I get back this big error message

### ISSUE THREAD

**Issue by lazy1993** [ElemeFE/element#7620]
版本："element-ui": "^2.0.0-alpha.2",
描述：给消息盒子传了一个错误的参数（我传了一个error对象），结果不能正确的报错
结果：控制台报错：

> vue.esm.js?d871:476 [Vue warn]: data functions should return an object:
> https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function
> 
> (found in <Root>)

希望：即使给消息盒子传了错误的参数，也能正确的报错，并且输出调用栈或者出错位置信息。
（由于没有位置信息，我调了2天才找到、、、）

**Comment by psi-4ward** [comment]
Same here.

seems its of https://github.com/ElemeFE/element/blob/dev/packages/message/src/main.js#L26
