### ISSUE TITLE
[Bug Report] Unable to set id attribute of el-input to link with for attribute in el-form-item

### ISSUE THREAD

**Issue by pushchris** [ElemeFE/element#7622]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
macOS 10.13 / Chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/634/](https://jsfiddle.net/pj71jkyw/634/)

### Steps to reproduce
Create an el-input item. Setting the id of it will set the outer element instead of the inner element. When creating an el-input inside of an el-form-item the label is not attached to the input item therefore making it unusable on accessibility devices. 

### What is Expected?
For there to be a way to set the id attribute of an el-input component

### What is actually happening?
There is currently no way of doing so

**Comment by Leopoldthecoder** [comment]
Fixed in #6049
