### ISSUE TITLE
[Bug Report] A bug of this.$notify

### ISSUE THREAD

**Issue by Comup-X** [ElemeFE/element#7625]
### Element UI version
1.4.7

### OS/Browsers version
win10 chrome63

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/635/](https://jsfiddle.net/pj71jkyw/635/)

### Steps to reproduce
just open this https://jsfiddle.net/pj71jkyw/635/

### What is Expected?
you should know 

### What is actually happening?
you should know

**Comment by Comup-X** [comment]
for(let i=0;i<10;i++){
                    this.$notify({
                        title: '标题名称',
                        message: h('i', { style: 'color: teal'}, '这是提示文案这是提示文案这是提示文案这是提示文案这是提示文案这是提示文案这是提示文案这是提示文案')
                    });
                }

**Comment by Comup-X** [comment]
效果有问题

**Comment by Comup-X** [comment]
#7624

**Comment by Comup-X** [comment]
https://jsfiddle.net/pj71jkyw/638/

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/641/

在计算出上一个 Notification 的高度之后，下一个 Notification 才能确定自己的位置，这是需要时间的。因此需要加个延时。
