### ISSUE TITLE
[Bug Report] $msgbox can't show icon when set type as 'info' and 'error' cause by new Icon class name

### ISSUE THREAD

**Issue by BruceFan-FS71** [ElemeFE/element#7626]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
MacOS 10.13 / Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/27rqpL5a/3/](https://jsfiddle.net/27rqpL5a/3/)

### Steps to reproduce
this.$msgbox({
    title: 'Tips',
    message: 'This is a message cause by info,
    type: 'info'
});

this.$msgbox({
    title: 'Tips',
    message: 'This is a message cause by error,
    type: 'error'
});

### What is Expected?
Show the info icon or error icon on MessageBox.

### What is actually happening?
The related icon is blank.

**Comment by Leopoldthecoder** [comment]
Fixed in #7632
