### ISSUE TITLE
[Bug Report] el-aside and collapsed vertical NavMenu in version 2.0.0-beta.1

### ISSUE THREAD

**Issue by mklemenz** [ElemeFE/element#7627]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
any

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/1po3ccdz/](https://jsfiddle.net/1po3ccdz/)

### Steps to reproduce
* use vertical el-menu inside el-aside width="auto"
* add menu and submenu items
* set 'collapse' property to 'true'

### What is Expected?
* on collapse, el-aside should resize (ok so far)
* on menu hover, the submenu should be displayed

### What is actually happening?
submenu stays hidden

**Comment by Leopoldthecoder** [comment]
You may need to override its style in this case: https://jsfiddle.net/1po3ccdz/1/
```css
.el-aside {
  overflow: visible;
}
