### ISSUE TITLE
[Bug Report] forms verify asynchronous checksum problem

### ISSUE THREAD

**Issue by Whalefallsea** [ElemeFE/element#7629]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
Chrome 62.0.3202.62

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/p6phbg2p/](https://jsfiddle.net/p6phbg2p/)

### Steps to reproduce
输入密码，再次输入密码，上面验证通过，输入年龄，验证规则里年龄必须大于18，并且使用settimeout模拟异步。输入小于18的数字。

### What is Expected?
validate方法验证结果由于年龄小于18，应该是不能通过，表单不能被提交才对。

### What is actually happening?
虽然页面显示的效果是验证不通过，但是实际上valid的值是true，表单被提交。

**Comment by Leopoldthecoder** [comment]
Form does not support async validation for now. I'll edit the example on documentation to eliminate confusion.

**Comment by Whalefallsea** [comment]
@Leopoldthecoder ok,thanks!

**Comment by bitjjj** [comment]
@Leopoldthecoder waiting for updating document. Thanks

**Comment by Leopoldthecoder** [comment]
Fixed in #7774
