### ISSUE TITLE
[Bug Report] Wrong button size in round buttons

### ISSUE THREAD

**Issue by Allenice** [ElemeFE/element#7633]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
Chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/1pg6x0z6/](https://jsfiddle.net/1pg6x0z6/)

### Steps to reproduce
view: http://element.eleme.io/2.0/#/zh-CN/component/button#bu-tong-chi-cun

### What is Expected?
  Different buttons size should have different sizes

### What is actually happening?
  Different buttons size should have the same sizes

**Comment by Leopoldthecoder** [comment]
Fixed in #7634
