### ISSUE TITLE
[Feature Request] The size of element

### ISSUE THREAD

**Issue by sonmunehiro** [ElemeFE/element#7635]
### Existing Component
Yes

### Component Name
el-elemnt

### Description
In v 2.0.0, the size of "mini" is bigger than "small" in v 1.4 

Is it possible to reduce the size?

大的有点夸张

**Comment by Leopoldthecoder** [comment]
2.0 的 mini 和 1.x 的 small 应该是一样高的，都是 28px。不过 1.x 各组件的尺寸并不统一，不排除个别组件的 small 不是 28px。
2.0 的尺寸不会再变了。
