### ISSUE TITLE
[Feature Request] An encrypted messagebox-prompt is required when input a password.

### ISSUE THREAD

**Issue by K-Wen** [ElemeFE/element#7636]
### Existing Component
Yes

### Component Name
MessageBox

### Description
When use MessageBox-Prompt, I want an attribute to use type = 'password' input. 

Such as 'inputType', when inputType = true, prompt's input is encrypted，otherwise, input is normal.

Sorry if I don't make it clear,  my English is really poor.

**Comment by Leopoldthecoder** [comment]
MessageBox will have an `inputType` prop in the next 2.0 release.
