### ISSUE TITLE
Form [Bug Report] 1. Table data binding in TimePicker, TimePicker data after the data binding has not been updated in the 2. Table to Switch per line, delete operation, each row of the Switch will be re rendering

### ISSUE THREAD

**Issue by Rickykurt** [ElemeFE/element#7637]
### Element UI version
1.4.7

### OS/Browsers version
macOS High Sierra / Google Chrome 62.0.3202.62

### Vue version
2.5.2

### Reproduction Link
[http://jsfiddle.net/chromeos/vrz0p87d/](http://jsfiddle.net/chromeos/vrz0p87d/)

### Steps to reproduce
问题1. Table 中的数据绑定 Form 中的 TimePicker ，TimePicker中的数据在选择后，未被更新
1. 点击 Table 中的第一行后面的 修改 按钮 （也就是6:00对应的行）
2. 在弹出的窗口中，点击 TimePicker 
3. 点击 TimePicker 下拉菜单中的取消或者确定
4. 点击弹窗中的确定
5. 点击 Table 中的第二行后面的 修改 按钮 （也就是11:00对应的行）
6. 此时 TimePicker input 中的数据是正确的，但单击 TimePicker 后下拉菜单中默认高亮显示的时间是 6:00 也就是第一次点击第一行后面 修改 按钮后执行的结果

问题2. Table 中的数据绑定到每行的 Switch 中，删除操作时，每行的 Switch 都会被重新渲染
1. 点击 Table 中的第一行后面的 删除 按钮 （也就是6:00对应的行）
2. 提示的弹窗中点击 确定 
3. 第一行被删除，但是后面几行的 switch 动画都会再执行一次

### What is Expected?
问题1. Table 中的数据绑定 Form 中的 TimePicker ，TimePicker中的数据在选择后，未被更新
1. 点击 Table 中的第一行后面的 修改 按钮 （也就是6:00对应的行）
2. 在弹出的窗口中，点击 TimePicker ，此时展示下拉菜单是默认高亮显示 6:00
3. 点击 TimePicker 下拉菜单中的取消或者确定
4. 点击弹窗中的确定
5. 点击 Table 中的第二行后面的 修改 按钮 （也就是11:00对应的行）
6. 单击 TimePicker 后下拉菜单中默认高亮显示的时间是11:00 

问题2. Table 中的数据绑定到每行的 Switch 中，删除操作时，每行的 Switch 都会被重新渲染
1. 点击 Table 中的第一行后面的 删除 按钮 （也就是6:00对应的行）
2. 提示的弹窗中点击 确定 
3. 第一行被删除，但是后面几行的 switch 动画都不应再执行

### What is actually happening?
问题1. Table 中的数据绑定 Form 中的 TimePicker ，TimePicker中的数据在选择后，未被更新
1. 点击 Table 中的第一行后面的 修改 按钮 （也就是6:00对应的行）
2. 在弹出的窗口中，点击 TimePicker 
3. 点击 TimePicker 下拉菜单中的取消或者确定
4. 点击弹窗中的确定
5. 点击 Table 中的第二行后面的 修改 按钮 （也就是11:00对应的行）
6. 此时 TimePicker input 中的数据是正确的，但单击 TimePicker 后下拉菜单中默认高亮显示的时间是 6:00 也就是第一次点击第一行后面 修改 按钮后执行的结果

问题2. Table 中的数据绑定到每行的 Switch 中，删除操作时，每行的 Switch 都会被重新渲染
1. 点击 Table 中的第一行后面的 删除 按钮 （也就是6:00对应的行）
2. 提示的弹窗中点击 确定 
3. 第一行被删除，但是后面几行的 switch 动画都会再执行一次

**Comment by Leopoldthecoder** [comment]
第一个问题已在 2.0 修复：http://jsfiddle.net/vrz0p87d/2/
第二个问题其实并不是由于重新渲染，而恰恰是因为 Vue 复用了已有的 `<tr>`，导致会有一个动画。如果觉得不能接受，可以自行覆盖一下 Switch 的 transition CSS，不过这样正常切换 Switch 也就没有动画了。

**Comment by Rickykurt** [comment]
@Leopoldthecoder 请问第一个问题的修复会合并到1.x版本中么？目前在生产环境上已有1.x的代码。

**Comment by Leopoldthecoder** [comment]
@Rickykurt 抱歉，由于这个修复牵涉到一些底层的改动，所以应该不会合并到 1.x 里了。
