### ISSUE TITLE
[Bug Report] checkbox indeterminate state

### ISSUE THREAD

**Issue by proshuai** [ElemeFE/element#7641]
### Element UI version
1.4.7

### OS/Browsers version
mac chrome

### Vue version
2.4.3

### Reproduction Link
[https://jsfiddle.net/General_Lee/t4ay70qo/](https://jsfiddle.net/General_Lee/t4ay70qo/)

### Steps to reproduce
1、当默认checkedCities为['上海', '北京', '广州', '深圳']，执行一下。全选前面的图标是减号，但是自己默认选全部的时候是对号
2、当默认checkedCities为[]，执行。全选前面的也是减号。
这两种是不是有种冲突？

### What is Expected?
1、当默认checkedCities为['上海', '北京', '广州', '深圳']，执行一下。全选前面的图标应该是加号

### What is actually happening?
实际都是减号

**Comment by proshuai** [comment]
https://jsfiddle.net/General_Lee/t4ay70qo/

**Comment by Leopoldthecoder** [comment]
「全选」和下面的 CheckboxGroup 并不是关联的，它们之间的关系需要自己手动处理。
