### ISSUE TITLE
[Bug Report] NavMenu displays an exception in the Container container when it folds

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#7643]
### Element UI version
2.0-beta1

### OS/Browsers version
win10 x64/chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/aft99yd9/](https://jsfiddle.net/aft99yd9/)

### Steps to reproduce
no

### What is Expected?
展开层在aside外浮动

### What is actually happening?
展开层在aside内浮动

**Comment by Leopoldthecoder** [comment]
这种情况请覆盖 CSS：https://jsfiddle.net/aft99yd9/1/

**Comment by wtry** [comment]
@Leopoldthecoder aside 折叠收起后，右侧main部分不会自适应
