### ISSUE TITLE
[Bug Report] Select size inconsistency problem

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#7644]
### Element UI version
2.0-beta1

### OS/Browsers version
win10 x64/chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/g6g6xdxc/](https://jsfiddle.net/g6g6xdxc/)

### Steps to reproduce
Select选择多个值

### What is Expected?
Select能够与其他input保持一致大小
Select多选时可以通过下拉菜单清除选择项

### What is actually happening?
Select的宽度是固定的，导致与input的宽度不一致
Select多选时，如果超过宽度会自动增加高度，也会导致和同一行的input高度不一致

**Comment by Leopoldthecoder** [comment]
Select 默认是内联元素，如果需要撑满容器可以设置为 `display: block`。

目前没有计划对自动增加高度这一行为进行改变。
