### ISSUE TITLE
[Feature Request] option rightClosed for component date-picker with type datetimerange

### ISSUE THREAD

**Issue by nighca** [ElemeFE/element#7646]
### Existing Component
是

### Component Name
date-picker

### Description
Hi, when we use date-picker with type `datetimerange` to choose a time range, it always confuses users in this way: they select date 01-01 to 01-02, and they got a range from 01-01 00:00 to 01-02 00:00.

The component implies that I've selected two days, while I got only one day long range. In most times, we want 01-01 00:00 to 01-02 23:59 when we select 01-01 to 01-02.

I suggest we add a option (for example, `rightClosed`, defaults to `false`) for date-picker to let it behaves as I described above. If you agree, I will create a pull request for that.

**Comment by Leopoldthecoder** [comment]
@wacky6 What do you think?

**Comment by nighca** [comment]
@wacky6 It's not about the use case to choose `01-01 00:00` - `01-02 23:59`, but the default behavior on date-select for `datetimerange`.

We want to select a date-time range, while it's more reasonable to use the end (instead of the beginning) of the end date as default for end-users. You may not agree with the **more reasonable** part, but it will be better for developers being able to control this default behavior.

**Comment by wacky6** [comment]
Add an option to control left and right panel's default time to pickerOptions?

**Comment by wacky6** [comment]
@Leopoldthecoder 

May also consider https://github.com/ElemeFE/element/issues/7618 , it's possible to not reset time to `00:00:00` when a date is picked (use `modifyDate` in `handleRangePick`)

**Comment by nighca** [comment]
@wacky6 I agree not to reset time on date-select. It's also how antd [behaves](https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date).

Then it will be possible to control the time with initial time value.

**Comment by wacky6** [comment]
I prefer to use a separate pickerOption (maybe `default-time` ?) for `daterange` panel to set the time after date pick:

* If this option is not set, do not reset time
* If this option is set, reset time to this value.
* Should be an array, for left and right panels respectively (User may want `01-01 06:00` - `01-02 18:00` ?)

@Leopoldthecoder What do you think?

**Comment by nighca** [comment]
Any ideas? @Leopoldthecoder

**Comment by Yuliang-Lee** [comment]
Has any plan to solve this issue?

**Comment by nighca** [comment]
@Leopoldthecoder @wacky6 Any ideas about this? If we reach an agreement about the solution, I'll provide a PR for it.

**Comment by wacky6** [comment]
Thanks for contributing.
I think you can PR a default-time in pickerOption for now.

* Remember to write tests.
* There should be a few edge cases.
  * May have to do fallbacks if used with a weird selectableRange combination.
  * Work properly/reasonably in daytime saving? (On the day of switching to/from DST)
* Should have a default value that is consistent with current picker behavior. ['00:00:00', '00:00:00'] perhaps?
* Do not reset time if set to null/undefined
* May need to further discuss the property name of this feature.

There are helper functions in date-picker's util, try to reuse them.

These are what I can thought of at the moment, please comment below for more ideas.

**Comment by nighca** [comment]
@wacky6 Sure, thx.

**Comment by Leopoldthecoder** [comment]
PR merged. This feature will be included in the next minor version.
