### ISSUE TITLE
Does the title of [Feature Request] table component alone add tooltip text prompt?

### ISSUE THREAD

**Issue by Donng** [ElemeFE/element#7650]
### Existing Component
是

### Component Name
table

### Description
希望在table组件的标题添加一个 ？  图标，实现标题的提示功能，在文档中没有发现可以添加此功能的位置。

**Comment by Leopoldthecoder** [comment]
是指表头？请使用 `render-header` 属性。对用法有疑问请参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md)。
