### ISSUE TITLE
[Feature Request] Pass click event object to input-number @input handler

### ISSUE THREAD

**Issue by saalihou** [ElemeFE/element#7654]
### Existing Component
Yes

### Component Name
el-input-number

### Description
Hello,

It would be great if we could access the event generated from clicking on the increase/decrease buttons in <el-input-number> @input handler as I am in a situation where I need to call .stopPropagation() on it.
Currently the event is lost from here: https://github.com/ElemeFE/element/blob/dev/packages/input-number/src/input-number.vue#L67

Thank you.

**Comment by wacky6** [comment]
Do you mean something like this: https://jsfiddle.net/221t5rv4/1/

**Comment by saalihou** [comment]
Oh indeed, this works too! Thank you a lot. Closing.
