### ISSUE TITLE
[Bug Report] incorrect name of icon el-icon-moblie-phone

### ISSUE THREAD

**Issue by yariksav** [ElemeFE/element#7655]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
OSX / Chrome

### Vue version
2.5.2

### What is Expected?
name: el-icon-mobile-phone

### What is actually happening?
Incorrect name of icon

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/commit/14ecf86c5532765638d7d8c0635988880dfe8ee8
