### ISSUE TITLE
[Feature Request] Display property of selected object in Auto Complete

### ISSUE THREAD

**Issue by johncade** [ElemeFE/element#7657]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
If autocomplete is using a list of objects as the values to search through, and on select, the entire object is selected, autocomplete cannot display a property on that object. What's strange is you can use `props` to give the label for searching through the list of objects, but if you are selecting the entire object instead of a value from within the object, `el-autocomplete` cannot display the given label, and instead displays `[object Object]`.

https://jsfiddle.net/gtzvdppw/1/

**Comment by Leopoldthecoder** [comment]
This is because the binding value `state1` is an object. Unlike Select, Autocomplete is essentially an input box, so its binding value should be a string: https://jsfiddle.net/gtzvdppw/2/
