### ISSUE TITLE
[Bug Report] Select breaks when selecting an object

### ISSUE THREAD

**Issue by johncade** [ElemeFE/element#7658]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
macOS, windows / Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/fmpc17h7/2/](https://jsfiddle.net/fmpc17h7/2/)

### Steps to reproduce
Create a `el-select` with an array of objects for options. Set the value of the the `el-option` to the selected object.

### What is Expected?
Will display the label for the selected object

### What is actually happening?
The appropriate object is selected, but the select field displays the incorrect object's key value.

**Comment by Leopoldthecoder** [comment]
Use the `value-key` prop: https://jsfiddle.net/fmpc17h7/3/
