### ISSUE TITLE
[Bug Report] date picker el-button unregistered issue

### ISSUE THREAD

**Issue by wanying1804** [ElemeFE/element#7659]
### Element UI version

2.0.0-beta

### OS/Browsers version

Chrome

### Existing Component
Yes

### Component Name
Date picker

### Description
when I click on date picker, I got error saying `Unknown custom element: <el-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.` I looked at the source code and found the el-button is not imported to date picker. Could you pls fix it? Thanks!

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/commit/6e65590775ab104e0c9eaf71ace213c89660192a
