### ISSUE TITLE
[Bug Report] Select multiple does not clear query string after selection

### ISSUE THREAD

**Issue by johncade** [ElemeFE/element#7660]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
windows 10 /chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/y17we1be/1/](https://jsfiddle.net/y17we1be/1/)

### Steps to reproduce
Create a select with filtering and multiple enabled
Type in a string, select any value from the list

### What is Expected?
The value is selected, and the query string is cleared so that it is an empty string

### What is actually happening?
The query string maintains the query that was there previous to the select. This is not how a select with filtering and multiple should behave.

**Comment by Leopoldthecoder** [comment]
Your demo uses version 1.4.7 while the actual 2.0.0-beta.1 behaves correctly: https://jsfiddle.net/y17we1be/2/

**Comment by johncade** [comment]
@leopoldthecoder thanks!
