### ISSUE TITLE
The data source of [Bug Report] table is the calculated attribute, and when you hide it, modifying the data source will cause the table to be unable to display

### ISSUE THREAD

**Issue by penghang** [ElemeFE/element#7662]
### Element UI version
1.4.7

### OS/Browsers version
win8.1 x64/chrome 60

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/4v7fkdkL/1/](https://jsfiddle.net/4v7fkdkL/1/)

### Steps to reproduce
1、打开嵌有table的dialog
2、关闭dialog
3、修改table的数据源
4、再次打开dialog

### What is Expected?
table正常显示

### What is actually happening?
table无法显示

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0: https://jsfiddle.net/4v7fkdkL/2/

**Comment by penghang** [comment]
升级2.0了一下，样式问题很多，比如穿梭框的文字和checkbox不对齐，table内嵌tag后高度太高。虽然可以修复，但是要修复的地方过多。时间上来不及了。我还是先通过其它方式处理吧。
能否问一下1.4.7是否到此为止不再维护了？ @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
这个问题的修复也同时会体现在 1.4.8 里，预计本周发布。
