### ISSUE TITLE
[Vue warn]: $attrs is readonly $listeners is readonly.

### ISSUE THREAD

**Issue by fanwei1991** [ElemeFE/element#7664]
![image](https://user-images.githubusercontent.com/20528597/31921509-634a0152-b835-11e7-9633-e662c7100d82.png)

![image](https://user-images.githubusercontent.com/20528597/31921493-454f0666-b835-11e7-94d4-329562ecc3fc.png)
执行上面的方法就会报出下面两个警告，但代码能够正常运行。
![image](https://user-images.githubusercontent.com/20528597/31921563-a98e5096-b835-11e7-8609-3720916de030.png)

**Comment by dancampbell691** [comment]
I have the same problem.  Up to 1.4.8, it would still work, even though it spewed errors.  As of 1.4.8, I no longer get a confirm box.  Hopefully, @fanwei1991 will resubmit.  If not, I will attempt to do so when I return to the office Wednesday.

**Comment by fanwei1991** [comment]
@dancampbell691  Vue updated to the latest version of the problem after the solution
