### ISSUE TITLE
Whether to open the checkbox to disable [Feature Request] options can form in the future

### ISSUE THREAD

**Issue by ukhack** [ElemeFE/element#7668]
### Existing Component
Yes

### Component Name
el-table

### Description
`<el-table-column type="selection" width="23" :disabled="disable"></el-table-column>`无效。
目前我是否有替代方案？指定某些框不能选定

**Comment by Leopoldthecoder** [comment]
请仔细阅读文档，使用 `selectable` 属性。

**Comment by lixing0323** [comment]
@Leopoldthecoder ，如果只禁用表头的全选checkbox？

**Comment by ettingshausen** [comment]
> @Leopoldthecoder ，如果只禁用表头的全选checkbox？

同问，表头的checkbox怎么禁用？
<img width="239" alt="Snipaste_2019-09-07_18-00-33" src="https://user-images.githubusercontent.com/9806325/64473439-6cf97500-d199-11e9-94dd-94bd0747b5c5.png">
