### ISSUE TITLE
[Feature Request] recommends adding right-click menu events for table component header

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#7673]
### Existing Component
是

### Component Name
el-table

### Description
计划实现动态显示表格列,右键表头显示菜单所有列,可选显示部分列,目前表头部分无右键菜单事件,只能在外部另外增加选择控件.感觉这样比较不方便,影响一些布局.

**Comment by Leopoldthecoder** [comment]
如果对表头有自定义需求，建议使用 `render-header` 属性。
