### ISSUE TITLE
The problem of [Bug Report] navigation and Container container connection

### ISSUE THREAD

**Issue by bboywulong** [ElemeFE/element#7676]
### Element UI version
0.1.0

### OS/Browsers version
macOS

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/ohv6ohg2/1/](https://jsfiddle.net/ohv6ohg2/1/)

### Steps to reproduce
当导航为折叠状态时,弹出的子菜单会被container容器遮挡,加入层级关系也没用

### What is Expected?
子菜单不被遮挡

### What is actually happening?
子菜单被遮挡

**Comment by Leopoldthecoder** [comment]
这种情况需要自己加一条样式：
```css
.el-aside {
  overflow: visible;
}
```
https://jsfiddle.net/ohv6ohg2/2/
