### ISSUE TITLE
[Feature Request] Hope to add some new NavMenu Attributes

### ISSUE THREAD

**Issue by simphp** [ElemeFE/element#7686]
### Existing Component
是

### Component Name
NavMenu

### Description
Component el-menu now has background-color, text-color, active-text-color attributes.
Hope to add some new attributes:
active-background-color
hover-background-color
hover-text-color

el-submenu now has the same background-color attribute as el-menu, should be set different background-color attribute,  even other attributes like text-color

**Comment by yangjunjun** [comment]
支持， 现在 el-menu-item 的  `hoverBackground` 是根据 el-menu 的 `background-color ` 根据 内置的 mixColor 函数生成的，但是很多情况生成的颜色不合理，而且因为 内联样式，导致也无法自己写样式来覆盖。希望能让用户自己添加所需要的样式。

**Comment by PanJiaChen** [comment]
@Leopoldthecoder 刚升级@2.0 就遇到了这个痛点，用自定义取代了默认主题，但可定制性不太够，尤其是 `submenu` 和 `menu` 一个颜色有点丑和区分度不够。。。

**Comment by Leopoldthecoder** [comment]
各位觉得怎样自定义 Menu 的样式比较合适？
- 直接用 CSS 覆盖
  - 优点：可控性最高
  - 缺点：需要梳理清楚各种状态下对应的类名

- Element 提供全套和颜色有关的 API，如文字颜色、hover 文字颜色、激活文字颜色、hover 激活文字颜色、背景色、hover 背景色、激活背景色、hover 激活背景色，如果要区分 Menu 和 SubMenu，则需要乘以二
  - 优点：可以直接赋值，无需处理各种类名
  - 缺点：API 过于冗余

- 使用目前已有的三个颜色相关 API
  - 优点：介于前两者
  - 缺点：计算出来的颜色可能不太美观

- 除了目前的默认样式外，Element 再内置一套 Menu 样式，像 1.x 一样
  - 优点：最简单
  - 缺点：只能二选一，不适合更加个性化的需求

**Comment by PanJiaChen** [comment]
个人还是倾向于默认提供主题的方式，如果对样式要较高需求的用户基本都会去使用自定义主题了，所以也不存在目前的问题。
没有了默认主题让我这种没太多的审美的用户很为难 :weary:

**Comment by wacky6** [comment]
CSS吧。

**Comment by troy351** [comment]
css覆盖

**Comment by scutHuqiang** [comment]
> Hope to add some new attributes:
Active-background-color
Hover-background-color
Hover-text-color

支持，有同样的需求

**Comment by evolutionjay** [comment]
<img width="666" alt="qq20180613-154552 2x" src="https://user-images.githubusercontent.com/4468540/41337361-98c1eb62-6f21-11e8-9572-a17827c80792.png">
@furybean 
hey , 看这里,  element-ui : 2.4.1

**Comment by evolutionjay** [comment]
支持第一条, CSS 覆盖, 反正有 element-theme , 写在 scss 文件里面让我们自己生成吧.

**Comment by anming-john** [comment]
现在还有结果吗， 现在看还是要通过important 的形式进行强制覆盖， 非常不美观啊！
