### ISSUE TITLE
[Bug Report] $attrs is readonly $listeners is readonly

### ISSUE THREAD

**Issue by fanwei1991** [ElemeFE/element#7690]
### Element UI version
1.4.7

### OS/Browsers version
mac/chrome

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element/issues/7664](https://github.com/ElemeFE/element/issues/7664)

### Steps to reproduce
开发环境，表格中的按钮点击时调用this. $confirm() 时，vue会报错：“$attrs is readonly 和 $listeners is readonly”；

### What is Expected?
控制台不会弹出错误警告。

### What is actually happening?
控制台有$attrs is readonly ，$listeners is readonly 两个错误警告，关闭的时候也会出现

**Comment by fanwei1991** [comment]
vue 更新到2.52版本之后没有出现此问题

**Comment by JingLiii** [comment]
我把Vue升级到了2.5.7依旧有这个问题

**Comment by aleksejevski** [comment]
It doesn't work on Vue 2.5.7
But it works again with 2.5.8

**Comment by wangduanduan** [comment]
i came upon a this issue too, because i use webpack DllPlugin, after i remove webpack DllPlugin, the issue resolved. 

so may be the issue is not caused by Vue version, but some tools like webpack.

you can also see https://forum.vuejs.org/t/vue-warn-attrs-is-readonly/18053/8

**Comment by MissCuriosity** [comment]
马克一下，我也碰到这个问题了

**Comment by woodghost** [comment]
The same issue here!

**Comment by fengbjhqs** [comment]
element-ui@2.0.8 也遇到这个问题

**Comment by Wangwenhan** [comment]
When I use webpack dllplugin, I also encountered this problem，but later solved。
If you fill in the entry in webpack.dll.config.js is 'vue/dist/vue.esm.js', You need to import the same name in the JS project entry file。
example：
import Vue from 'vue/dist/vue.esm.js'

**Comment by kgrosvenor** [comment]
Getting this too, anyone know why? Is the logic modifying value props also?

**Comment by wanwan1521** [comment]
I've updated it to the latest version of the problem that still appears, and I haven't installed webpack dllplugin, a project built in electron-vue.   Sorry, English is not very good

**Comment by Lighfer** [comment]
I meet this issue too,  finally I found a solution, in your webpack.render.config.js:
```
let whiteListedModules = ['vue'];
```
change to
```
let whiteListedModules = ['vue', 'element-ui'];
```
It's works for me.

**Comment by wanwan1521** [comment]
The project is over. BUG, I didn't repair it.

**Comment by wanwan1521** [comment]
Thank you very much. Electro-vue is now finished. I'm not responsible for fixing the bug. The bug has been fixed by someone else

**Comment by yeyan1996** [comment]
l have update Vue to 2.5.22,this problem seem not  be appeared

**Comment by misterpancn** [comment]
The same issue here, which is vue@2.6.6 & iview@3.2.2. Using this method to solve the problem
> ```
> let whiteListedModules = ['vue'];
> ```
> change to
> 
> ```
> let whiteListedModules = ['vue', 'element-ui'];
> ```

**Comment by ezenwankwogabriel** [comment]
@misterpancn  please where is the whiteListedModules located, cant find it in my build folder

**Comment by misterpancn** [comment]
@ezenwankwogabriel I created the project using vue-cli, and the whiteListedModules variable is located in the webpack configuration file webpack.renderer.config.js, I hope to help you.

**Comment by hale1106** [comment]
原因是引入了多个vue的ui库造成的，类似element-ui,iview,vuetify的，解决方案是在webpack.renderer.config.js中把这些库都加入whiteListedModules，如let whiteListedModules = ['vue','element-ui','vuetify']

**Comment by dacuotecuo** [comment]
> I use electron-vue and meet this issue too, there is a solution works for me, in webpack.render.config.js:
> 
> ```
> let whiteListedModules = ['vue'];
> ```
> 
> change to
> 
> ```
> let whiteListedModules = ['vue', 'element-ui'];
> ```

it works well

**Comment by freedomTT** [comment]
please , where is the webpack.renderer.config.js , building project by @vue-cli3 , I can't find webpack.renderer.config.js file.

**Comment by garbage-rubbish** [comment]
> I use electron-vue and meet this issue too, there is a solution works for me, in webpack.render.config.js:
> 
> ```
> let whiteListedModules = ['vue'];
> ```
> 
> change to
> 
> ```
> let whiteListedModules = ['vue', 'element-ui'];
> ```

thanks!!

**Comment by chenjianan0823** [comment]
> 原因是引入了多个vue的ui库造成的，类似element-ui,iview,vuetify的，解决方案是在webpack.renderer.config.js中把这些库都加入whiteListedModules，如let whiteListedModules = ['vue','element-ui','vuetify']

nice
