### ISSUE TITLE
how can table column with :formatter create a new line with "<br>" or "/n"

### ISSUE THREAD

**Issue by youyouliangshao** [ElemeFE/element#7698]
<el-table-column
        prop="modelObjects"
        label="查询对象信息"
    :formatter="formatObj"
        >
            //格式化对象列表
            formatObj(row, column, cellValue){
                let html='';
                let objStr=JSON.parse(cellValue)
                for(let i=0;i<objStr.length; i++){
                    html+=objStr[i].riskModelObjectName+':'+objStr[i].params+'<br>';
                }
                return html;
            },

//it does not work ,how to solve with new line

**Comment by happymzw** [comment]
问一下这个问题解决了没？

**Comment by youyouliangshao** [comment]
formatter不支持换行转译，换方法了，用template+{{function}},放外部函数处理的换行
