### ISSUE TITLE
[Bug Report] size="mini"时 Input 符合输入框样式异常

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#7709]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
window10 x64/chrome 61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/8jm08t21/](https://jsfiddle.net/8jm08t21/)

### Steps to reproduce
无

### What is Expected?
Input内的select和button按钮居中

### What is actually happening?
按钮顶部对齐

**Comment by Leopoldthecoder** [comment]
Fixed in #7702
