### ISSUE TITLE
Element示例如何动态注册路由呢，比如从列表页面传参跳转到对应的表单页面？

### ISSUE THREAD

**Issue by lampo1024** [ElemeFE/element#771]
### ElementUI version
1.0.0-rc.2

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.0-rc.4

### What is Expected?
Element示例如何动态注册路由呢，比如从列表页面传参跳转到对应的表单页面？
示例中的路由都是写在路由表中的，如果像我这种情况，事先没有为表单页面注册路由要如何处理呢？

**Comment by QingWei-Li** [comment]
这个请看 vue-router 的文档，可以传参数的
http://router.vuejs.org/zh-cn/essentials/dynamic-matching.html
