### ISSUE TITLE
[Bug Report] navigation menu component NavMenu, mode is horizontal, there will be a Bug

### ISSUE THREAD

**Issue by Undefined123456789** [ElemeFE/element#7710]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
win10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Undefined100/vpxfvnqv/2/](https://jsfiddle.net/Undefined100/vpxfvnqv/2/)

### Steps to reproduce
导航菜单组件NavMenu，mode为horizontal时，当子菜单同时有el-submenu、el-menu-item时会出现样式问题，当子菜单只有el-submenu时，样式也会有问题，望修复，祝element-ui越来越好！

### What is Expected?
导航菜单组件NavMenu，mode为horizontal时，当子菜单同时有el-submenu、el-menu-item时不会出现样式问题，当子菜单只有el-submenu时，样式也不会有问题！

### What is actually happening?
导航菜单组件NavMenu，mode为horizontal时，当子菜单同时有el-submenu、el-menu-item时会出现样式问题，当子菜单只有el-submenu时，样式也会有问题！

**Comment by Leopoldthecoder** [comment]
水平模式的 NavMenu 最多仅支持二级菜单。
