### ISSUE TITLE
[Bug Report] multi tree close cascade, such as A node all disabled, A cannot select

### ISSUE THREAD

**Issue by lynzz** [ElemeFE/element#7713]
### Element UI version
1.4.8

### OS/Browsers version
61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/qaund6aa/](https://jsfiddle.net/qaund6aa/)

### Steps to reproduce
1.  勾选 二级 2-1
2.  查看 二级 2-1 不会被勾选

### What is Expected?
1.  勾选 二级 2-1
2.  二级 2-1 能被勾选

### What is actually happening?
1.  勾选 二级 2-1
2.  二级 2-1 未并勾选

**Comment by Leopoldthecoder** [comment]
This is fixed in version 2.0. The fix may not be merged to 1.x because it uses another implementation.
