### ISSUE TITLE
[Bug Report] loading frame is not adaptive container

### ISSUE THREAD

**Issue by tym1193** [ElemeFE/element#7714]
### Element UI version
1.4.8

### OS/Browsers version
win10/Chrome 60.0.3112.101

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Lma32ca9/](https://jsfiddle.net/Lma32ca9/)

### Steps to reproduce
等待loading层出现，拖拽使窗口放大

### What is Expected?
loading框遮罩层自适应容器尺寸变化

### What is actually happening?
loading框遮罩层未自适应容器尺寸变化

**Comment by Leopoldthecoder** [comment]
Avoid using the `body` modifier when you're expecting viewport resize: https://jsfiddle.net/Lma32ca9/1/
