### ISSUE TITLE
[Feature Request] tree supports horizontal display

### ISSUE THREAD

**Issue by yiwuyu** [ElemeFE/element#7718]
### Existing Component
是

### Component Name
Tree

### Description
希望一些最终子节点可以横向展示而不是垂直展示
如
```javascript
 [x] 一级
    [x] 二级-1
       [x] 叶子 [x] 叶子 [x]叶子
    [x] 二级-2

```
当前遇到的难点：
使用renderContent方法自定义的叶子checkbox 和tree的checkbox 实现indeterminate 和 checked 关联有难度

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
