### ISSUE TITLE
The [Bug Report] component of tree, dynamic loading level, select the first sub node, returns the node does not contain its child nodes in check-change method

### ISSUE THREAD

**Issue by Angelsindevil** [ElemeFE/element#7719]
### Element UI version
1.4.7

### OS/Browsers version
mac

### Vue version
2.3.3

### Reproduction Link
[https://codepen.io/zhengxiaowen/pen/wrLbQw?editors=1111](https://codepen.io/zhengxiaowen/pen/wrLbQw?editors=1111)

### Steps to reproduce
官网demo，Tree 树形控件->可选择的demo中，页面加载完后，在没有展开节点的情况下，第一次选中节点region1，在check-change的方法中console的结果是没有包含下级节点的相关信息（此时没有选中该级节点的子节点并没有调用该方法）。但是我取消选中节点region1时，在check-change的方法中是包含了该节点以及它所有子节点的信息（它的子节点是调用了该方法的）。再次选中的时候，与期望的结果是相同的，此时选中了节点region1的所有子节点

### What is Expected?
页面加载完成后，没有展开该节点之前。第一次选中节点region1时，在check-change的方法中应该要包含该节点以及它所有子节点的信息（它的子节点应该调用该方法的）。

### What is actually happening?
页面加载完成后，没有展开该节点之前。第一次选中节点region1时，在check-change的方法中没有包含该节点以及它所有子节点的信息。

**Comment by Leopoldthecoder** [comment]
选中某个节点会立刻触发 `check-change` 事件，同时开始加载它的子节点。但由于加载是异步的，所以
 `check-change` 事件被触发时还无法获得它的子节点。取消选择和再次选择时，加载方法执行完毕，所以能够在子节点上同时触发 `check-change`。

这一行为已经在 2.0 中修正，仅勾选 checkbox 不再加载子节点了：https://jsfiddle.net/3wu0yms4/
