### ISSUE TITLE
[Bug Report] [Vue warn]: Error in nextTick: "TypeError: e.$refs.tags is undefined"

### ISSUE THREAD

**Issue by alexdee2007** [ElemeFE/element#7721]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
Windows 7 Professional / Google Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/gv0mfogo/](https://jsfiddle.net/gv0mfogo/)

### Steps to reproduce
Run the application, click button "Click me" and see console.

### What is Expected?
no errors or warn in console

### What is actually happening?
When click button (change disable prop) in console appears:

[Vue warn]: Error in nextTick: "TypeError: e.$refs.tags is undefined"

found in

---> <ElSelect>

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0.0-rc.1
