### ISSUE TITLE
[Feature Request]'s default import of typescript

### ISSUE THREAD

**Issue by wangyi7099** [ElemeFE/element#7723]
### Existing Component
No

### Component Name
ELement

### Description
请问下 能不能再element 的 types/index.d.ts.里面设置个默认导出 就是export default ... 要不
import * as element from 'element-ui' 这种方式导入 还得as 一下 感觉太麻烦了= = 人家vue的就是默认导出了vue........

**Comment by Leopoldthecoder** [comment]
#7740
