### ISSUE TITLE
[Bug Report] Clearing daterange launch an error when "value-format" prop is set

### ISSUE THREAD

**Issue by ReynerHL** [ElemeFE/element#7730]
### Element UI version
2.0.0-rc.1

### OS/Browsers version
WIndows 10. Google Chrome is up to date Version 62.0.3202.62 (Official Build) (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/reynerhl/h4xpo5p5/](https://jsfiddle.net/reynerhl/h4xpo5p5/)

### Steps to reproduce
Using the fiddle you provide in the documentation page (https://jsfiddle.net/api/post/library/pure/) I've set this prop in my own fiddle and when we try to clear the component we got an error.

### What is Expected?
After setting this prop, the bound model should be set just to null.

### What is actually happening?
It launches an error.

**Comment by ReynerHL** [comment]
Well, I've updated the fiddle (it really works, I don't no why "you" (automatically?) said I forgot to save it ). Anyway, here you have an updated url:
https://jsfiddle.net/reynerhl/h4xpo5p5/1/

**Comment by wacky6** [comment]
see: https://github.com/ElemeFE/element/pull/7745
