### ISSUE TITLE
[Feature Request] How to make row table if click show expand?

### ISSUE THREAD

**Issue by blackinitial** [ElemeFE/element#7736]
### Existing Component
Yes

### Component Name
table

### Description
I want to make the table if click the row show the expand. and column to show the expand ( > ) disappear. how to implemetation?

**Comment by Leopoldthecoder** [comment]
In 2.0 you can expand or collapse rows programmatically. You can hide the expand icon using CSS.

**Comment by allesan** [comment]
Can you please provide an example for this?
