### ISSUE TITLE
[Feature Request] Container layout container, if you can increase support drag, change the size of the sidebar container function will be better

### ISSUE THREAD

**Issue by wcx88** [ElemeFE/element#7739]
### Existing Component
是

### Component Name
Container 布局容器

### Description
Container 布局容器如果能增加支持拖动改变侧边栏容器大小功能会更好，侧边栏容器需要改变大小的情况相对多。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
