### ISSUE TITLE
引入bootstrap样式之后，table表格中如果设置了fixed固定列，样式会变形

### ISSUE THREAD

**Issue by zhangliang2008v** [ElemeFE/element#775]
### ElementUI version
1.0.0-rc.8 

### OS/Browers version
 win10/Chrome 53

### Vue version
2.0.3

### Reproduction Link
https://jsfiddle.net/fe0v1ob9/3/

### What is actually happening?
引入bootstrap样式之后，table表格中如果设置了fixed固定列，样式会变形，如下图
![image](https://cloud.githubusercontent.com/assets/6396617/19885515/f5ab8164-a059-11e6-9f99-f3940f447289.png)

**Comment by furybean** [comment]
closed via #780.
