### ISSUE TITLE
Element 2.0 正式发布

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7755]
Element 2.0 已经在今天上午发布正式版，官网也同步更新为默认显示 2.0 版本的文档（当然，你仍然可以从下拉菜单中选择查看 1.x 版本的文档）。另外，最近收到一些大陆用户反馈官网加载慢的问题，随着 2.0 版本的上线，你也可以访问部署在国内的 http://element-cn.eleme.io ，未来它会与 http://element.eleme.io 保持同步。

##

Element 2.0 一共积累了 210 个 commit，包含了 90 多项新增功能和优化，大致分为以下几个部分：

### 组件功能

- 首先，我们提升了 Element 的易用性。比如在 1.x 版本中，如果需要改变组件的默认尺寸，只能在每个组件上添加 size 属性，而现在我们支持了尺寸的全局设置，用一行代码就可以改变所有组件的默认尺寸；主题采用 SCSS 编写，因此 SCSS 用户能够很容易地修改样式变量，从而达到自定义主题的效果。同时，我们还为部分组件增加了一些方法，方便用户通过代码控制组件的行为，增强了组件的可控性，比如 Menu 的 `open` 和 `close` 方法可以打开和关闭子菜单、Table 的 `toggleRowExpansion` 方法可以展开或关闭扩展行等
- 其次，我们对用户呼声比较高的需求提供了支持，比如 Dialog 支持嵌套书写、Table 支持合并单元格、MessageBox 支持渲染 HTML 字符串等
- 再次，组件的 API 得到了丰富，因此能够适应更多的业务场景，比如 Notification 支持配置出现位置、Loading 支持自定义图标等
- 最后，我们还修正了 1.x 中一些功能设计不合理的地方，并且提高了部分 API 的一致性，比如表单组件的 change 事件现在仅响应用户交互，与原生事件保持了一致

具体的改动请参考[更新日志](http://element-cn.eleme.io/2.0/#/zh-CN/component/changelog)。

### 新主题

2.0 版本包含了一套全新的主题：`theme-chalk`。这套视觉背后有着怎样的设计理念呢？负责 `theme-chalk` 的设计师@NicoHsueh 这样说：

*经过重新设计的 Element 2.0，符合当前设计趋势，适应当前时代审美。摒弃多余的设计修饰，坚持「少即是多」的设计原则。比如，高分屏普及的当下，我们让组件的整体比 1.x「大」了一圈，这样阅读体验会更加友好。与此同时，在默认组件尺寸的基础上，我们也提供了多种不同尺寸，以适应大家的不同需求。*

*另外，保持组件的一致性，在设计中克制、严谨地使用数值，也是 2.0 贯穿始终的原则。比如我们先定义了按钮的四种默认高度（`40px`、`36px`、`32px`、`28px`）；此后输入框、选择器等其他组件都与之保持高度上的统一。无法保持统一的，如 Table 的行高，也会保持一个公差为 4 的等差数列关系。这使得基于 Element 2.0  的设计产出能保证高度的严谨性。*

*总体来说，2.0 与 1.x 相比较，会显得更加的现代、更加的友好。*

### 可访问性

我们还在 2.0 版本中提升了组件的可访问性。以下是负责这方面工作的@maranran 为大家带来的介绍：

*可访问性是指页面上的组件、行为和 DOM 结构具有语义化和可操作性，使得 AT 设备可以正确地传达页面信息给残障人士，包括盲人、肢体残疾和认知残疾等。*
 
*Element 作为基础组件库，封装了底层的 DOM 结构，在 2.0 版本里，我们在可访问性方面做了一些基础工作来提升残障人士理解和操作组件的能力，同时方便 Web 开发者在自己的项目中开展可访问性工作。*

*我们所做的工作包括提升组件的键盘可操作性和语义化两个方面：键盘可操作性使得残障人士可以通过键盘导航到可交互组件然后使用 left、right、up、down、enter、esc 等键进行组件交互；语义化方面则是通过使用 WAI-ARIA 技术为组件添加 roles、states、properties 等属性，使得 UA 和 AT 能够正确地传达组件的语义。*

### 文档

2.0 的官网和文档也进行了相应的升级，比如提供了搜索功能、左侧导航栏独立滚动等，能够方便各位用户查阅。

##

Element 2.0 的主要贡献者为（按照首字母顺序）：@baiyaaaaa @Dreamacro @Leopoldthecoder @liril-net @maranran @wacky6 @waynecz 。此外，有不少社区用户为 2.0 提出了建议，在此对他们表示感谢。

2.0 版本的发布标志着 Element 进入了一个新的时代，同时也意味着 1.x 版本将进入维护模式，我们会在 2017 年 12 月 01 日之前继续为其提供支持。

欢迎大家在项目中使用 Element 2.0，希望各位能够喜欢。

**Comment by liril-net** [comment]
`cn` 站访问真快

**Comment by oufish** [comment]
访问快捷。棒棒哒

**Comment by Wolfshell** [comment]
给你们打call! 想马上把项目移植到2.0 ：）

**Comment by tjfy1992** [comment]
前排

**Comment by Chips04** [comment]
怎么迁移

**Comment by fakership** [comment]
棒棒哒

**Comment by zhengshuai666** [comment]
给你们打call!

**Comment by zjweedsMine** [comment]
饿了么大前端666 啊，给你们打call

**Comment by jinjinwa** [comment]
请问1系列的可以平滑迁移到2.0么

**Comment by ajluo** [comment]
请问有没有 1.x 迁移指南 ？？

**Comment by CodeDreamfy** [comment]
赞一个~~~

**Comment by lhy666** [comment]
真的有没有迁移指南。。来一个

**Comment by anick-xs** [comment]
赞赞赞

**Comment by tangxiangmin** [comment]
嘿嘿嘿，项目开个分支，准备升级

**Comment by wangzhiwei3919** [comment]
看着很好玩的样子。

**Comment by blaze87** [comment]
分页组件谁负责的 为何样式丑的一比

**Comment by skyshirt** [comment]
期待迁移文档

**Comment by Jevirs** [comment]
主题色切还不错，不过active时透底啦
![image](https://user-images.githubusercontent.com/8214869/32092470-46a53474-bb2b-11e7-9603-e816c0da55bc.png)

**Comment by Colco** [comment]
前排，dialog终于解决了。舒服...

**Comment by uxclouder** [comment]
请问资源什么时候可以下载

**Comment by uxclouder** [comment]
请问资源什么时候可以下载

**Comment by uxclouder** [comment]
![default](https://user-images.githubusercontent.com/32321910/32093482-0112a082-bb2f-11e7-8110-a496151d2aed.png)

**Comment by AngeLeeGeek** [comment]
6666

**Comment by joyc-fe** [comment]
ui风格很清爽啊

**Comment by Gxuebin** [comment]
Table 导出Excel

**Comment by EternalChildren** [comment]
我只想吐槽input为什么取消change实时，如果现在想做文档能清晰点嘛 onchange事件如何绑定到input上

**Comment by beanlee** [comment]
打call！ 可以考虑把自己的小系统折腾升级啦！

**Comment by nicejade** [comment]
嗯，NICE；考虑要把下个人作品 [NICE LLINKS](https://nicelinks.site/) 升级下，顺便为 `Element-UI ` 手动打 Call。

**Comment by amin168** [comment]
打call！

**Comment by gaoyoubo** [comment]
贺电

**Comment by Ansel** [comment]
因为表格在Safari 11中的显示问题 通过Safari特定的hack解决的不彻底 昨天就把1.4.8的给升级到2.0 rc-1版本了 基本上就是样式变化挺大的 不过改吧改吧就行了 功能越来越丰富了 大大提升了开发效率 灰常给力 不过现在的表格表头和内容的列对照的还不是特别齐 如果有些列设置了width 表格内容的列显示在Safari 11上会有那么1px的对不齐 不过还好 不是特别明显

**Comment by mrsensen** [comment]
能出css版本吗 不要vue

**Comment by LifeFly** [comment]
el-table 加上 border属性后 会出现横向滚动条

**Comment by colin1suntao** [comment]
点个赞

**Comment by tangdaohai** [comment]
赞一个，走你

**Comment by superpig** [comment]
求Tree组件支持拖拽功能

**Comment by yuyixxy** [comment]
赞

**Comment by mysmalldream** [comment]
upload组件支持批量上传文件了吗,大神们

**Comment by xuyingchuan** [comment]
所以是赶在前端交流会强行上线一波 666

**Comment by cangxin** [comment]
求1.0迁徙指南。手动打call

**Comment by LoverMaker** [comment]
分页组件真丑！

**Comment by mengdu** [comment]
文档，点击展开代码，应该在上面也给个按钮关闭啊，不然每次拉到下面关闭

**Comment by wps213thb186** [comment]
终于来了！！！

**Comment by wps213thb186** [comment]
正式版终于来了，想请问下什么时候能上V2.0的设计资源呢~~~

**Comment by 52linyuepeng** [comment]
棒！

**Comment by LingHS** [comment]
首页的随鼠标倾斜的特效是怎么写的

**Comment by YJ-H** [comment]
同求迁移指南

**Comment by limeng0403** [comment]
迁移指南

**Comment by mopetite** [comment]
急求迁移工具~~~

**Comment by akebe** [comment]
分页和Message想用1.4样式怎么办

**Comment by merlin95X** [comment]
#6801有解决嘛？

**Comment by haiyupeter** [comment]
迁移指南，什么时候出来

**Comment by gaoyu0165** [comment]
迁移的坑会不会很多...

**Comment by nch14** [comment]
666，良心饿了么

**Comment by techzealot** [comment]
受不了分页组件

**Comment by SteveCruise** [comment]
alpha用了一次，问题很多，目测还要改200个bug

**Comment by shenzhirong** [comment]
分页组件真的不太好看 ，能换回原来的吗

**Comment by StephenSeraph** [comment]
新版很多组件比之前合理多了，很多之前强行改的class可以删掉了。
另外，国内站点好评！我之前在本地搭的`gh-pages`可以退役了

**Comment by renxia** [comment]
提的建议都支持了
给 @wacky6 点个赞

**Comment by TingYinHelen** [comment]
现在还不敢迁移呢，怎么迁移

**Comment by ireeoome** [comment]
1.x迁移指南有吗？

**Comment by renxia** [comment]
@TingYinHelen @ireeoome 
不兼容的更新都会有警告了
可以参考 2.0 不兼容更新部分的内容，直接迁移，看浏览器 console 警告去修改就是

大概会包括这些：
```
icon:

icon="plus" => icon="el-icon-plus"

template:

scope="scoped" => slot-scope="scoped"

dialog:

dialog size 取消，用width/fullscreen

switch:

on/off- => active/inactive
```

**Comment by linjohn527** [comment]
分页组件真心丑

**Comment by 156063436** [comment]
为什么，element使用表格的时候，title的文本是居左，而list的文本居中？

**Comment by 156063436** [comment]
@Leopoldthecoder

**Comment by wangchenhao** [comment]
1.X版本还会持续维护嘛。

**Comment by yobi-maggie** [comment]
同问如何迁移  现在发现更新版本之后   整体的样式都改变了  不知道怎么弄回去   现在太丑了

**Comment by lhy666** [comment]
upload组件在chrome浏览器上点击的时候会出现蓝色的边框。。。这个解决一下啊之前在测试版本就这样。 @Leopoldthecoder

**Comment by wjtGitHub** [comment]
@Leopoldthecoder ，我就弱弱的问一下是否支持ts？

**Comment by maranran** [comment]
好的, 收到 @Leopoldthecoder @lhy666

**Comment by TingYinHelen** [comment]
谢谢你@renxia

**Comment by psychokiller666** [comment]
线上项目已更新 2.0.1

http://www.ontheroadstore.com/

**Comment by hhy107107** [comment]
怎么迁移怎么迁移怎么迁移怎么迁移怎么迁移怎么迁移

**Comment by webkong** [comment]
项目用2.0beta开发的，正式版之后感觉非常棒呀，尤其是官网速度明显提升。

**Comment by Superkimi** [comment]
求迁移指南

**Comment by Superkimi** [comment]
还是会报这个警告  Injection "elFormItem" not found  Injection "elForm" not found  怎么解决？

**Comment by gmaso** [comment]
牛，近期有个新界面争取用上

**Comment by lhy666** [comment]
把vue升级到最新 @gmaso

**Comment by shanchunfeng** [comment]
好像有个bug没有解决啊，body{position: relative; margin: 0 auto;}, select, datepicker 的弹出框偏移了body的margin。偏移量(document.clientWidth - body.offsetWidth)/2

**Comment by eddiebai** [comment]
@blaze87 你丫不会自己改下样式？瞧把你惯的

**Comment by shanchunfeng** [comment]
不行啊，修改的是style.left

**Comment by shanchunfeng** [comment]
帮忙看一下吧

**Comment by 00ming** [comment]
打call! 这个很nice~

**Comment by jjl666** [comment]
@blaze87 是不是2，你自己加啊，想弄成什么样弄成什么样

**Comment by shanchunfeng** [comment]
而且，使用了两个以上的el-date-picker， datepicker会出现两个以上的<div>,但只用到最后面一下

**Comment by leiwensu** [comment]
安装了2.0.1版本后，报错：
 ERROR  Failed to compile with 1 errors                           
This dependency was not found:
* element-ui/lib/theme-default/index.css in ./src/main.js
To install it, you can run: npm install --save element-ui/lib/theme-default/inde
x.css

**Comment by fengxianqi** [comment]
凑凑热闹，赞赞赞，项目准备使用

**Comment by shanchunfeng** [comment]
可以修改bablerc文件
官方文档

{ "presets": [ ["es2015", { "modules": false }] ], "plugins": [["component", [ { "libraryName": "element-ui", "styleLibraryName": "theme-chalk" } ]]] }



shancf@sh-jcpp.com
 
发件人： 雷文秀
发送时间： 2017-10-31 18:44
收件人： ElemeFE/element
抄送： shanchunfeng; Comment
主题： Re: [ElemeFE/element] Element 2.0 正式发布 (#7755)
安装了2.0.1版本后，报错：
ERROR Failed to compile with 1 errors
This dependency was not found:
element-ui/lib/theme-default/index.css in ./src/main.js
To install it, you can run: npm install --save element-ui/lib/theme-default/inde
x.css

**Comment by 1peng** [comment]
分页组件 估计是实习生设计的

**Comment by leiwensu** [comment]
@shanchunfeng 谢谢解答，已解决

**Comment by wps213thb186** [comment]
期待设计资源的更新~~~~~

**Comment by aeolusheath** [comment]
big thanks

**Comment by achenjs** [comment]
前排留坑~  牛逼牛逼

**Comment by yobi-maggie** [comment]
@1peng 为什么实习生躺枪。。。。。

**Comment by YuanWing** [comment]
上传组件感觉就有好几个Bug(最新版本):
`list-type="picture-card"`的时候，鼠标移上去，右上角的 `X` 不会出现；
鼠标点击后，右上角的 `勾` 隐藏了，其他没有任何状态；
设置 `disabled=true` 之后`list-type="picture-card"`鼠标移上去，右上角的 `X` 也不会出现；
正常设置 `disabled=true` 后，应该也是应该支持删除的吧，现在是还是能用 `delete健` 删除；

**Comment by Leopoldthecoder** [comment]
@YuanWing 其他几个问题都已经在 2.0.2 修复；`disabled=true` 仍能删除的问题会在下个版本修复。

**Comment by deepkolos** [comment]
可用性的那里大赞!!

**Comment by IdenPin** [comment]
好期待，希望不久后我们项目也能用上。

**Comment by machao1990** [comment]
赞

**Comment by plhwang** [comment]
为什么这个主题让人的感觉是蒙上了一层灰？是因为秋天到了有雾霾吗？

**Comment by 156063436** [comment]
清空树的时候，如果选择了树的子级，清空不了😂

只能清空父节点啊～～～ 

这个怎么解决？？？
@Leopoldthecoder

**Comment by tingyuguanhe** [comment]
求Injection "elFormItem" not found Injection "elForm" not found 怎么解决？

**Comment by Chips04** [comment]
@tingyuguanhe 升级vue版本 再问自杀 element-ui2.0依赖vue2.5.2

**Comment by YuanWing** [comment]
@Leopoldthecoder `el-date-picker`组件，如果是可编辑的，使用键盘的`Backspace`删除，对应的`model`值没有更新哟

**Comment by Superkimi** [comment]
为什么升级了后 图标就乱了 el-icon-edit的图标但是显示出来是el-icon-plus的样子？这是为什么？

**Comment by CaiKaiKai** [comment]
nice~

**Comment by lhy666** [comment]
能不能把选项卡组件出一个间距属性，不然可用性太低了 @Leopoldthecoder

**Comment by lhy666** [comment]
就比如让选项卡们平分一块区域，或者可以让一个选项在左面，一个选项卡在右面

**Comment by SpringLIAO** [comment]
样式处理工具为什么要从postcss-salad改为scss？scss 3.4相较与之前的postcss-salad有什么好处？

**Comment by albedel** [comment]
求NavMenu 导航菜单支持tree的树形结构展示，不然每次自己写递归展示每层的数据很麻烦

**Comment by wufeng110226** [comment]
厉害了。希望出一个1.x迁移文档

**Comment by UnlimitedGalaxy** [comment]
点赞，少即多

**Comment by williamjie** [comment]
棒棒的

**Comment by dylan-chen** [comment]
表单验证能验证二级对象了么。。。

**Comment by imjohnny** [comment]
试用了2.0.3，发现里面的icon都乱套了。

**Comment by aflext** [comment]
![image](https://user-images.githubusercontent.com/3211461/32443817-4f6c5e58-c33b-11e7-8944-bdb6ee8d7aec.png)
最新版（"element-ui": "^2.0.3"）表格一直报这个错误，你们都没有吗？

**Comment by chentiewei** [comment]
求1.0x迁移指南！！！！！！

**Comment by wangzongxu** [comment]
大赞 Element

**Comment by bookldk** [comment]
分页真心难看,
Table 排序 的图标也太难看了,能自定义吗,为什么不用1.4.9的那种图标
就这二点就想放弃2.0,

**Comment by dandanlinpu** [comment]
打call，真的很良心的团队！

**Comment by ericliudexin** [comment]
Table在v-show的状态下，非常耗CPU，由于是隐藏，clientwidth一直是0，element一直在监测，只有显示过后才不再触发。新版比旧版好了一点，但没有根本解决，只是做了一个延时。希望重新修改这个解决方案。

**Comment by xumqfaith** [comment]
在用¶ Input 输入框组件的时候一直报错：vue.esm.js?71e4:479 [Vue warn]: Injection "elFormItem" not found
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
已经import引入，并且已经Vue.use(ElementUI)

**Comment by Ansel** [comment]
@xumqfaith 升级你的vue到最新版就好了

**Comment by mengdu** [comment]
`"element-ui": "^2.0.3"`版本表格为何不支持响应式了么

**Comment by jjl666** [comment]
el-table-column 的width属性为什么不支持百分比？

**Comment by ChangeZhang** [comment]
没有1.x 升级到2.x的升级指南吗？有点不太敢动啊~~~~

**Comment by jweboy** [comment]
@Chips04  我用的是nuxt@1.0.0-rc11 也遇到了这个问题,有什么好的解决方案吗？

**Comment by liwenda122** [comment]
select 组件做的太差了，分页功能没有；多选时如果支持搜索，高度居然会自己撑开，巨丑
