### ISSUE TITLE
Element 2.0 available now

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#7756]
Element 2.0 was released this morning, and together the website has been updated to display 2.0 documentations by default (and, of course, you can still select the 1.x version docs from the dropdown menu).

## 

Element 2.0 has 210 commits, including more than 90 new functions and optimizations. They can be roughly categorized as follows:

### Component functions
- First of all, we improved usability. Here's some examples: in 1.x, if you need to change the default size of components, you'll have to add the `size` attribute on each component. Now you can configure the default size for all components with just one line of code. Another example is that the new theme is written in SCSS, so SCSS users can easily modify style variables to get a custom theme. At the same time, we also added some methods for components, so that you can programmatically trigger some behavior of the components. For example we added `open` and `close` methods for Menu to open and close SubMenus, and now Table has a `toggleRowExpansion` method that is used to expand or collapse expandable rows

- Second, we now support some of the popular demands our users have been asking. To name a few, now Dialog can be nested in template, Table supports rowspan and colspan, and MessageBox can render HTML strings

- Third, we enriched component APIs, so they can be used in a wider business scenario. For example, now you can configure which corner of the screen Notification pops up, and use custom icon in Loading

- Last but not least, we corrected some bad design in 1.x, and improved API consistency. One big change is that the `change` event of form components now only triggers on user interaction, keeping it consistent with native `change` event

Please refer to the [changelog](http://element.eleme.io/2.0/#/en-US/component/changelog) for details.

### New theme

Element 2.0 has a new theme: `theme-chalk`. What is the design principle of this theme? Let's hear what our designer @NicoHsueh has to say:

*In line with current design trends, the redesigned Element 2.0 adapts to the current aesthetic. To abandon redundant design modification, we adhere to the "less is more" design principle. For example, with more and more high-res screens, we make Element "bigger" than 1.x, so the reading experience will be more friendly. At the same time, besides the default component size, we also provide a variety of sizes to accommodate different needs.*

*In addition, keeping the consistency of components is also a principle when we design 2.0. For example, we first defined the four heights of Button (`40 px`, `36 px`, `32 px`, `28 px`); after that, Input, Select and other components are then maintained with the exact same heights. This enables the design output based on Element 2.0 to ensure a high degree of unity.*

*In general, 2.0 is more modern and friendly than 1.x.*

### Accessibility

We also improved accessibility of components in version 2.0. The following is from @maranran, who is responsible for this work:

*Accessibility means that the components, behaviors, and DOM structures on the page are semantically correct, so that AT devices can convey page information to people with disabilities, including the blind, physical disability, and cognitive disability.*

*As a UI library of basic components, Element encapsulates the underlying DOM structure. In the 2.0 version, we have done some basic work in accessibility to help people with disabilities to understand the page and interact with it. At the same time, we have made it easier for developers to keep improving accessibility in their projects.*

*What we have done includes two parts: increasing operability of keyboard, and improving semantics of the components. Keyboard operability allows people with disabilities to navigate to each component using keyboard and interact with them using left, right, up, down, enter, esc, etc. When it comes to semantics, we used the WAI-ARIA technology to add roles, states, properties for different components, so that UA and AT can correctly convey the semantics of components.*

### Documentation
The 2.0 website and documentations have also been upgraded, and hopefully you will find them easier to use.

##

The main contributors of Element 2.0 are (in alphabetical order) : @baiyaaaaa @dreamacro @leopoldthecoder @liril-net @maranran @wacky6 @waynecz. In addition, there are many community users who have made suggestions for 2.0, and we are grateful to them.

The release of version 2.0 marks a new era for Element, and it also means that the 1.x version goes into maintenance mode. We will continue to support it until December 01, 2017.

We hope you enjoy Element 2.0.

**Comment by AndyRightNow** [comment]
@Leopoldthecoder

One problem though, is that those CDN links on [The Installation Page](http://element.eleme.io/1.4/#/en-US/component/installation) still don't have version numbers.
![image](https://user-images.githubusercontent.com/11091064/32096427-01c949c2-bb39-11e7-89de-15df214532fd.png)

Therefore all previous apps using the links without version numbers will fail hard because all resources will link to `2.0` instead of the versions before.

I suggest adding version numbers to the CDN links on that page.

**Comment by Leopoldthecoder** [comment]
@AndyRightNow will do

**Comment by dsonet** [comment]
Hey, what's new there that only supported on IE 10+ but instead IE9+? Is there anyway to support IE9 as usual?
Since I want upgrade to the element v2 gracefully, thanks.

**Comment by apexJCL** [comment]
It truly it's a beautiful theme, cheers on the upgrade!

**Comment by EdibleArchaeologist** [comment]
Thank you! I'm trying to update from npm and it is still tagged as 1.4.8 although it says 2.0.0 is available on NPM. Do you have a timeline for when 2.0 will be available via NPM?

**Comment by liril-net** [comment]
@EdibleArchaeologist Have u locked version of `element-ui`? It is available now

**Comment by EdibleArchaeologist** [comment]
Thanks @liril-net , I realized my json.lock file was preventing me from updating a major version, so I was able to override and get 2.0! It's great thank you so much.

**Comment by rDr4g0n** [comment]
Is these a migration guide or something to help in estimation of level of effort migrating from 1.x to 2.x?

**Comment by chlab** [comment]
Thank you so much for this! The components of Element UI I have used so far have proved great quality. I will most likely be using this for a customer portal shortly and am looking forward to working with Element 2.0 in more depth.

If you already have the new sketch files for Element 2.0 - our designer would love them :)

Keep up the great work and let me know if I can help.

**Comment by adavie1** [comment]
Have looked around but can't seem to find what I need to change in my code to migrate from **1.4.X** to **2.0.X**.

I'm using `npm/yarn`. I've upgraded` element-ui` to `2.0.5`, downloaded element-theme.

My app runs, but clearly it's not finding the CSS.

My init code looks like this:
```
import Vue from 'vue'
import moment from 'moment'

// import 'element-ui/lib/theme-default/index.css' -- needed for element 1.4.X

import VueI18n from 'vue-i18n'
import Element from 'element-ui'
import enLocale from 'element-ui/lib/locale/lang/en'

Vue.use(VueI18n)
Vue.use(Element)

Vue.config.lang = 'en'
Vue.locale('en', enLocale)
```
**What I get under v2**:
![image](https://user-images.githubusercontent.com/3030402/32986444-9436a856-cd0c-11e7-862c-32e8197639c3.png)

**What 1.4 looked like**:
![image](https://user-images.githubusercontent.com/3030402/32986449-a55e9fbc-cd0c-11e7-90fb-5bed660d0a3e.png)


Any pointers would be great. Thanks in advance.

**Comment by Leopoldthecoder** [comment]
@adavie1

**Comment by Leopoldthecoder** [comment]
@adavie1 
import 'element-ui/lib/theme-chalk/index.css

**Comment by adavie1** [comment]
Thanks @Leopoldthecoder that did the trick - now I need to migrate components and a few layout issues & stuff. I like the cleaner look of **chalk**, great work!
