### ISSUE TITLE
[Feature Request] How to use valueKey?

### ISSUE THREAD

**Issue by wsw70** [ElemeFE/element#7763]
### Existing Component
Yes

### Component Name
Input

### Description
I would like to use `valueKey` in an Autocomplete Input to show specific elements of the object I am suggesting.

To start with - [the example ](http://element.eleme.io/2.0/#/en-US/component/input#autocomplete) works fine, it suggests an Array of Objects, with keys `value` and `link`. If I build the suggestions to follow that scheme (using the default `value` as the key and displaying its value) it still works.

The suggestions I generate though an external search:

```
[
  {'firstname': 'john', 'lastname': 'brown'},
  {'firstname': 'mary', 'lastname': 'doe'}
]
```

I transform them into

```
[
  {'value': 'john', 'link': {'firstname': 'john', 'lastname': 'brown'}},
  {'value': 'mary', 'link': {'firstname': 'mary', 'lastname': 'doe'}}
]
```

which I pass to the autocomplete input. **This works fine**.

When I finally pick an element, I end however with, say, ` {'value': 'john', 'link': {'firstname': 'john', 'lastname': 'brown'}}`. This is not exactly what i want, I would prefer to have just the content of `link`.

So I tried to use `valueKey` in my `el-autocomplete`:

```
<el-autocomplete
    v-model="suggestedName" 
    class="inline-input" 
    :fetch-suggestions="querySearch" 
    placeholder="Add New User" 
    :trigger-on-focus="false" 
    @select="handleSelect" 
    :valueKey="firstname">
```

and passed them in the callback the bare Array I get from the external search:

```
[
  {'firstname': 'john', 'lastname': 'brown'},
  {'firstname': 'mary', 'lastname': 'doe'}
]
```

My expectation was that `firstname` would be used to display the suggestions. This does not make a lot of sense, though, as `firstname` is unknown to `data()`. 

**What should I do to use the `firstaname` of the Object I pass as suggestion (in an Array of similar Objects) so that it is displayed as a suggestion?**

**Comment by Leopoldthecoder** [comment]
In this case, `value-key` does not need `:` because `firstname` is a string literal instead of a variable.

**Comment by wsw70** [comment]
@Leopoldthecoder: Thank you - I also literally realized a few seconds ago that the next example will probably be a good fit for me: http://element.eleme.io/2.0/#/en-US/component/input#custom-template. And by the way, THANK YOU for this excellent library - I am rewriting my application based on it as it perfectly fits my needs.

**Comment by aierong** [comment]
value-key="firstname"
