### ISSUE TITLE
[Bug Report] cannot verify deep attributes

### ISSUE THREAD

**Issue by zyip** [ElemeFE/element#7764]
### Element UI version
2.0.0-rc.1

### OS/Browsers version
chrome, opera

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/cqvg6nzr/3/](https://jsfiddle.net/cqvg6nzr/3/)

### Steps to reproduce
以下代码片段中的age无法验证  , prop="children.name"不被识别 
 // tpl code
 <el-form-item label="活动名称" prop="children.name">
    <el-input v-model="ruleForm.name"></el-input>
  </el-form-item>
// js, vue data field
data() {
      return {
        ruleForm: {
          name: '',
          children: {
          	age: 0 // how to validate deep level property
          }
        },
        rules: {
          name: [
            { required: true, type:'number', message: '请输入活动名称', trigger: 'blur' },
            { min: 3, max: 5, message: '长度在 3 到 5 个字符', trigger: 'blur' }
          ],
          children: {
          age: [
            { required: true, message: '请选择活动区域', trigger: 'change' }
          ]}
        }
      };
    },

### What is Expected?
 prop="children.name" 不识别
 <el-form-item label="活动名称" prop="children.name">
    <el-input v-model="ruleForm.name"></el-input>
  </el-form-item>

### What is actually happening?
prop="children.name" 可以识别

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/cqvg6nzr/4/
