### ISSUE TITLE
[Feature Request] Allow users to access event object from 'expand' event of el-table.

### ISSUE THREAD

**Issue by Paul-Kijtapart** [ElemeFE/element#7767]
### Existing Component
Yes

### Component Name
Element Table (el-table)

### Description
Goal: I want to access event object of the expand event to perform stopPropagation().

What I have on the table:
I registered two event 'row-click' and 'expand' on the element 'el-table'.
When a user clicks the expand icon, expandHandler will be triggered following by rowClickHandler, which is to be expected. However, I want to trigger expandHandler only

What I tried:
I tried to '@expand.stop.prevent' on the table element, which results in $event not having stopPropgation().
I tried passing $event object to expandHandler to manually call 'event.stopPropagation()', but $event ends up being rowObject.
I also tried '@expand.native.stop', which results in expandHandler not being called at all.

Help:
Is there a workaround for this? 

Any help is appreciated.

**Comment by Leopoldthecoder** [comment]
A flag could help: https://jsfiddle.net/jo2qve84/
