### ISSUE TITLE
[Bug Report] 2.0.0-rc.1 Table fail when nested property is null

### ISSUE THREAD

**Issue by rodrigore** [ElemeFE/element#7769]
### Element UI version
2.0.0-rc.1

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/656/](https://jsfiddle.net/pj71jkyw/656/)

### Steps to reproduce
Enter to the jsfiddle (https://jsfiddle.net/pj71jkyw/656/) and the data will not display because the nested property 'country' is null.

In previous version this example work. Checkout this jsfiddle https://jsfiddle.net/pj71jkyw/655/

### What is Expected?
When a nested property is null it expected that will not display the column such as previous version  (https://jsfiddle.net/pj71jkyw/655/), but now it fails all the component

### What is actually happening?
The table is not render

**Comment by Leopoldthecoder** [comment]
Fixed in #7772
