### ISSUE TITLE
[Bug Report] Input input box, remote search, input English search invalid

### ISSUE THREAD

**Issue by Cindy017** [ElemeFE/element#7771]
### Element UI version
2.0.0-rc.1

### OS/Browsers version
谷歌  版本 58.0.3029.110

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
在 input输入框输入h或者H，没有检索结果，demo里数据是有含H字母开头的

### What is Expected?
支持忽略字母大小写可模糊搜索出对应的数据

### What is actually happening?
字符搜索不支持

**Comment by Leopoldthecoder** [comment]
搜索方法是需要用户自己写的，是否忽略大小写是由你决定的。另外，我们例子里输入 h 是有结果的：
![image](https://user-images.githubusercontent.com/10095631/32084380-5e444f54-ba8e-11e7-96d4-e986cccb2add.png)

**Comment by Cindy017** [comment]
all right
