### ISSUE TITLE
[Feature Request] Allow user to remove the second column in the datetimerange date picker

### ISSUE THREAD

**Issue by mhyleomak** [ElemeFE/element#7780]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
In the datetime date picker, the second column can be removed by setting the format without 'ss', however, in the datetimerange date picker, the second column in the time picker can not be removed.

I would like to request a new feature to allow user to remove the second column in the datetimerange date picker by setting the format without 'ss'

Thanks!

**Comment by Leopoldthecoder** [comment]
You mean the third column, right?

**Comment by mhyleomak** [comment]
Yes, sorry for the mistake

**Comment by iTaster** [comment]
官方文档有格式化日期 value-format="yyyy-MM-dd"，看文档可好

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/kd62219w/

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/kd62219w/

```html
    <!-- remove second column by format option -->
    <el-date-picker format="yyyy-MM" v-model="value3" type="datetimerange" range-separator="To" start-placeholder="Start date" end-placeholder="End date">
    </el-date-picker>
```
