### ISSUE TITLE
[Bug Report]: the latest NPM package in el-table-column: index specifies that the method has no effect

### ISSUE THREAD

**Issue by cuijiudai** [ElemeFE/element#7781]
### Element UI version
2.0.0-beta.1

### OS/Browsers version
mac  / chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/npm没有链接](https://jsfiddle.net/npm没有链接)

### Steps to reproduce
最新 npm 包里的 el-table-column  设置type="index" :index="someMethod" , someMethod没有作用，只有 type="index" 的效果。

### What is Expected?
 :index="someMethod" 可以自定义index顺序

### What is actually happening?
 :index="someMethod" 没有作用

**Comment by Leopoldthecoder** [comment]
这是 2.0.0-rc.1 版本才加入的功能。
