### ISSUE TITLE
[Feature Request] [InputNumber] Add mouse wheel event support

### ISSUE THREAD

**Issue by Elfayer** [ElemeFE/element#7782]
### Existing Component
Yes

### Component Name
el-input-number

### Description
Would be awesome to have the mouse wheel event supported for input.
On `mouseover` on input number, allow to use mouse wheel to increase or decrease input value.

**Comment by Leopoldthecoder** [comment]
Seems it can already be done: https://jsfiddle.net/3cdxv147/

**Comment by xianshenglu** [comment]
Actually, this is browser default behavior. You don't have to do anything if you use `el-input[type=number]`. 

https://jsfiddle.net/xianshenglu/cgtm7kfn/4/

https://stackoverflow.com/questions/9712295/disable-scrolling-on-input-type-number/20838527

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

@Elfayer
