### ISSUE TITLE
[Bug Report] 2 DateTimePicker time cannot roll

### ISSUE THREAD

**Issue by DanielWLam** [ElemeFE/element#7783]
### Element UI version
2.0.0

### OS/Browsers version
WIN10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw   http://element.eleme.io/#/zh-CN/component/datetime-picker](https://jsfiddle.net/pj71jkyw   http://element.eleme.io/#/zh-CN/component/datetime-picker)

### Steps to reproduce
time无法滚动，直接看官网例子就行了

### What is Expected?
可以滚动选择

### What is actually happening?
无法滚动

**Comment by Leopoldthecoder** [comment]
浏览器是？

**Comment by DanielWLam** [comment]
@Leopoldthecoder Chrome61, win10

**Comment by Leopoldthecoder** [comment]
Fixed in #7811
