### ISSUE TITLE
2.0的分页样式太丑了   还好忍住没升级

### ISSUE THREAD

**Issue by blaze87** [ElemeFE/element#7788]
2.0的分页样式太丑了   还好忍住没升级

**Comment by heihei001** [comment]
大兄弟，设计师原话：摒弃多余的设计修饰，坚持「少即是多」的设计原则

**Comment by eddiebai** [comment]
@blaze87 惯的你丫的

**Comment by blaze87** [comment]
@heihei001 呵呵 为何react和angular版本的样式和之前1.X的样式相同？难道不是同一个人设计？还是设计理念不同？ @eddiebai  ？？

**Comment by blaze87** [comment]
@eddiebai 你没被惯  ？不能各抒己见？
