### ISSUE TITLE
[Bug Report] Transfer does not display content after using render-content

### ISSUE THREAD

**Issue by lzp3021** [ElemeFE/element#7789]
### Element UI version
1.4.8

### OS/Browsers version
win7/chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
直接访问

### What is Expected?
Transfer 使用render-content后内容正常展示

### What is actually happening?
Transfer 使用render-content后不展示内容

**Comment by Leopoldthecoder** [comment]
请参考 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md) 第三条。
