### ISSUE TITLE
[Bug Report] The actual style of el-radio-button looks different from the style in the document

### ISSUE THREAD

**Issue by Darkphooo** [ElemeFE/element#7791]
### Element UI version
2.0.0

### OS/Browsers version
Win10 1709 / Chrome 62.0.3202.62, Firefox Quantum 57.0b6

### Vue version
2.5.2

### Reproduction Link
[http://jsfiddle.net/g1w5kq62/](http://jsfiddle.net/g1w5kq62/)

### Steps to reproduce
Use tag el-radio's button style el-radio-button in the tag el-radio-group.

### What is Expected?
Wish to see the same style like the style in the document, the radio buttons are connected to each other without space.

### What is actually happening?
There are spaces between each radio button.

**Comment by Leopoldthecoder** [comment]
Fixed in #7793
