### ISSUE TITLE
[Bug Report] The overflow property of body elements cannot be correctly handled after the loading component triggers full page loading

### ISSUE THREAD

**Issue by yangjunjun** [ElemeFE/element#7792]
### Element UI version
2.0.0

### OS/Browsers version
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

### Vue version
2.5.2

### Reproduction Link
[http://element-cn.eleme.io/#/zh-CN](http://element-cn.eleme.io/#/zh-CN)

### Steps to reproduce
1.  到 文档组件页面（ http://element-cn.eleme.io/#/zh-CN/component/loading ) 触发 “整页加载" 操作
2.  跳转到 文档首页 （http://element-cn.eleme.io/#/zh-CN）

### What is Expected?
首页会有垂直滚动条

### What is actually happening?
首页没有垂直滚动条

**Comment by yangjunjun** [comment]
有一个解决思路供参考：
1.  定义一个 class ，比如叫 
```
.loading-active {
  overflow: hidden;
  position: relative;
}
```
2.  当在 loading 开始时在 body 元素添加这个 loading-active, loading 结束时候 去掉  loading-active. 这样就不会影响 body 原来的样式。

**Comment by Leopoldthecoder** [comment]
@yangjunjun 是的，这种处理方式比现在的好，我来改一下。

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/7891/commits/18140339dfadb163ab608080b1f21d1e57c085f7
