### ISSUE TITLE
[Feature Request] V2.0 Pagination components can be designed according to antd component style?

### ISSUE THREAD

**Issue by zhouxinyong** [ElemeFE/element#7796]
### Existing Component
是

### Component Name
Pagination

### Description
Pagination components can be designed according to antd component style, our group has always felt that the new Pagination component is ugly (not yet 1.x version of the good-looking), it is recommended to refer to antd paging component style to design.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
