### ISSUE TITLE
[Feature Request] Element UI V2是否适合开发能支持移动和PC两端的响应式网站***前台***呢

### ISSUE THREAD

**Issue by lichnow** [ElemeFE/element#7797]
### Existing Component
是

### Component Name
Framework

### Description
我现在的项目前台使用的是`vue-ssr` + `mdbootstrap`开发的，后台使用的`vuetify`,由于mdbootstrap等了很久一直没出vue库，全是自己封装很乱，而vuetify则全部使用stylus来构建样式，其它设计人员很不好读，所以一直在等element ui的v2版本,打算前后台全用element ui这一套系统重构，一个是sass非常通用改起来简单，第二个是UI自带就很炫,第三个当然是中文支持很好

现在的问题是element ui 2.0版本适合开发响应式的网站前台吗？尤其是响应式的前台。因为在el1.0的时候看到用el开发的项目基本都是中后台管理程序。而我现在最想要的是一套库既搞定了后台，还可以前台普通网站也支持比较好。移动网站(直接基于PC的响应式)，PC网站前台，网站后台这三端用element ui这一套库搞定可以吗？是否移动端还要去搞element的兄弟产品mint-ui,网站前台还要去搞veu-material或者其它库呢?

**Comment by lichnow** [comment]
@element-bot 已经用中文了，因为在issue的创建页面看到你们推荐用英文。。。在线等回复，嘿嘿😯

**Comment by Leopoldthecoder** [comment]
如果你的项目需要适配移动端，那么不建议使用 Element。视觉上不会有大问题，但是一些组件的交互不适合移动端。
