### ISSUE TITLE
table组件使用上遇到的bug

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#78]
> 目前已从 vue-desktop 迁移到了 element，遇到下面一些问题.

### Element version
1.0.0-rc.3

### table组件遇到的问题：
1. 当数据量展示的高度过多，出现竖向滚动条时，导致table表格出现横向滚动条，之前在vue-desktop中也遇到类似的问题，解决办法是data数据改变后，重新计算一遍calcColumns。
    ![qq20160918-1](https://cloud.githubusercontent.com/assets/10893176/18615740/dda78586-7de0-11e6-8e34-2c6fcf348c32.png)
    > 同理在dialog中嵌套表格也存在上面的问题1。

    > 在dialog中嵌套table组件时，有这么一种需求，为table设置自定义高度700时固定表头，当数据量只有一条(或者很少时)，此时我希望得到结果是，tabel的body组件高度是max-height: 700，而不是固定死的高度700，导致dialog高度非常大，影响美观。

2. 带border属性的table在safari浏览器中，边框线没对齐

3. 建议：table组件能否添加一个子组件用于设置，当表格数据为0时，自定义展示数据为空的默认样式；目前自定义为空的组件必须放于table父组件外才能实现，当设置了height属性时，就会导致`user-table-null`组件显示在最底下，必须动态判断设置height属性，使用上感觉很别扭.

``` html
<!-- 目前实现的效果 -->
<el-table :data="data">
    ***
</el-table>
<user-table-null :data="data"></user-table-null>

<!-- 期待的效果 -->
<el-table :data="data">
    <el-table-null>
        <user-define-null></user-define-null>
    </el-table-null>
    ***
</el-table>
```

**Comment by isunkui** [comment]
补充：垂直NavMenu组件的下拉交互动画效果，感觉很别扭，修改成初始在右边，点击展开朝下效果更好点。

**Comment by isunkui** [comment]
table组件，可以考虑添加居中对齐的样式吗，目前默认的左对齐，对有些表格的数据展示，感觉不是那么美观，自定义父组件重写覆盖了原来的样式，希望组件默认支持该功能

**Comment by isunkui** [comment]
@QingWei-Li  rc.4  TableColum: fix first calc columns 这个问题依旧没有修复

**Comment by isunkui** [comment]
@QingWei-Li  补充一点，我的表格数据渲染是从 vuex 里面获取的，初始渲染 获取到的 data 可能是个空数组，异步数据加载完成后会导致表格的数据重新渲染一遍，这时候页面的可视高度是不可控的，所以产生了问题一。

**Comment by QingWei-Li** [comment]
那你在 table.vue 385 行加一个 `this.$nextTick(_ => this.doRender());` 试试看，可以的话提个 pr

**Comment by isunkui** [comment]
nice，正常了

**Comment by qiaocuixinzhiweini** [comment]
table-header不支持自定义模板，比如我想在table-header里添加一个checkbox，或者其它的一些内容，目前的label就不能满足了

**Comment by furybean** [comment]
@isunkui 目前应该只剩下一个空状态的问题，和 #413 重复，先关了。

**Comment by baixiaoji** [comment]
@isunkui   所以Safari边框线没对齐是怎么样解决的？
