### ISSUE TITLE
[Feature Request] Directly select datetime shortcuts via typing the shortcut name

### ISSUE THREAD

**Issue by spaceywolfi** [ElemeFE/element#7801]
### Existing Component
Yes

### Component Name
DateTimePicker

### Description
I would like to be able to directly select a datetime shortcut by simply writing the shortcut such as 'today', 'yesterday', 'tomorrow', 'in x days', etc.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by spaceywolfi** [comment]
@Leopoldthecoder could you give a reason why you do not want to support this?
