### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by dnoodles** [ElemeFE/element#7803]
### Existing Component
Yes

### Component Name
Input

### Description
Please add more documentation or add a link to the documentation in forms regarding rules.  I spent a lot of time trying to figure out rules because it is not mentioned in the input component section just to find out it is only for forms.

Just a mention of "rules" would be helpful in the Input documentation to point users to the forms portion.

**Comment by Leopoldthecoder** [comment]
We'll consider this. At the same time, you can try the search field in 2.0 documentation.
