### ISSUE TITLE
[Bug Report] Time picker not respecting time format settings

### ISSUE THREAD

**Issue by owenconti** [ElemeFE/element#7804]
### Element UI version
2.0.0

### OS/Browsers version
OSX 10.13 Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/s79vb808/1/](https://jsfiddle.net/s79vb808/1/)

### Steps to reproduce
Set the 'format' options to 'hh:mm':

```
<el-time-picker
  v-model="value1"
  format="hh:mm a"
  :picker-options="{
    format: 'hh:mm a'
  }"
  placeholder="Select time"
/>
```

### What is Expected?
The time-picker component respects and uses the passed-in format option(s).

### What is actually happening?
When you set the time-picker format to 'hh:mm a', the format 'HH:mm' is used. I could not find a way to get 12-hour time to work at all.

**Comment by navmed** [comment]
Running in to the same problem.

**Comment by wacky6** [comment]
AM/PM support was added in https://github.com/ElemeFE/element/releases/tag/v2.0.8

Please check element-ui's version.

**Comment by navmed** [comment]
My apologies, looks like I was referring to the wrong control, I was actually referring to the time-select. Here's the jsfiddle: https://jsfiddle.net/uvjk9w81/5/. Should I create a new bug report?

**Comment by wacky6** [comment]
Time select is different from {Time, Date, DateTime} Picker. It's internal implementation is different. Right now it does not support AM/PM. 

PR welcome though. You can also hack a time-select with el-select.

**Comment by navmed** [comment]
Thank you Jiewei!

**Comment by krisanalfa** [comment]
> I know this is old. I don't think this is a bug, but I am running into the seconds not being respected.
> 
> ```
> <el-time-select v-model="timeSelected" :picker-options="{
>                 format: 'HH:mm:ss',
>                 start: '08:10',
>                 step: '00:15',
>                 end: '18:30'
>             }" placeholder="Select time">
> 			</el-time-select>
> ```
> 
> It just shows hours and mins. This is it inside a small project. https://codepen.io/chri_del/pen/qJQKLY?editors=1000
> What am I doing wrong here?

`el-time-select` does not support custom formatting, use `el-time-picker` instead (which is lame)
