### ISSUE TITLE
[Bug Report] Programmatic change to Slider's v-model does not trigger @change

### ISSUE THREAD

**Issue by jongeyer** [ElemeFE/element#7809]
### Element UI version
2.0.0

### OS/Browsers version
OSX 10.12.6 / Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/ff72zcnn/2/](https://jsfiddle.net/ff72zcnn/2/)

### Steps to reproduce
Setup a programmatic change to the slider's v-model data, listen to @change handler.

### What is Expected?
Programmatic change should trigger @change

### What is actually happening?
Not triggered.
Trigger only occurs for direct manipulation of slider (drag-n-drop or input box).

**Comment by Leopoldthecoder** [comment]
Yes, this is a breaking change of 2.0:
> `change` event of form components and `current-change` event of Pagination now only trigger on user interaction

https://github.com/ElemeFE/element/releases/tag/v2.0.0
