### ISSUE TITLE
[Bug Report] Mouse on the button, press the right button will appear BUG

### ISSUE THREAD

**Issue by zaxlct** [ElemeFE/element#7816]
### Element UI version
2.0.1 or 1.x

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
The mouse on the button, press the right button after the number will automatically increase 10 times

鼠标放到按钮上，按下右键后数字会自动增加10次。

### What is Expected?
The mouse on the button, press the right button after the number will automatically increase 10 times

鼠标放到按钮上，按下右键后数字会自动增加10次。

### What is actually happening?
The mouse on the button, press the right button after the number will automatically increase 10 times

鼠标放到按钮上，按下右键后数字会自动增加10次。

**Comment by Leopoldthecoder** [comment]
Fixed in #7817
