### ISSUE TITLE
[Bug Report] Form: The verification result not wait for asynchronous verification to complete

### ISSUE THREAD

**Issue by Allenice** [ElemeFE/element#7818]
### Element UI version
2.0.1

### OS/Browsers version
All

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/tb4wpus9/1/](https://jsfiddle.net/tb4wpus9/1/)

### Steps to reproduce
view: https://jsfiddle.net/tb4wpus9/1/

### What is Expected?
The verification result should wait for asynchronous verification to complete

### What is actually happening?
The verification result not wait for asynchronous verification to complete

**Comment by Allenice** [comment]
PR: https://github.com/ElemeFE/element/pull/7774

**Comment by Leopoldthecoder** [comment]
Thanks for your PR.
