### ISSUE TITLE
[Select] auto create, inline edit, drag & drop order

### ISSUE THREAD

**Issue by gendalf** [ElemeFE/element#782]
Please add support for 
   - auto create items in single / multiple mode
   - inline edit like tags in multiple mode 
   - reorder via drag & drop in multiple mode ( http://jsfiddle.net/rwone/q84VX/4/ )

Like https://selectize.github.io/selectize.js/ 

請添加支持
    - 在單/多模式下自動創建項目
    - 內聯編輯像多個模式下的標籤
    - 通過拖放在多種模式下重新排序。

喜歡https://selectize.github.io/selectize.js/

**Comment by Leopoldthecoder** [comment]
- auto created is added in #1401 
- we have no plan to add inline edit and drag & drop
