### ISSUE TITLE
[Bug Report] el-table high cpu/memory leak

### ISSUE THREAD

**Issue by purepear** [ElemeFE/element#7820]
### Element UI version
2.0.1

### OS/Browsers version
macOS 10.12.6 / Chrome 62 / Firefox 56

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/9d7e2nsy/1/](https://jsfiddle.net/9d7e2nsy/1/)

### Steps to reproduce
Click on Show/Hide button few times (even one is enough). 
Open Chorme Task Manager and see cpu usage getting constant high.

### What is Expected?
CPU usage for the tab should be near 0 when not interacting.

### What is actually happening?
I think that when el-table component is destroyed it fires timers constantly.
CPU usage is high.. depending on how many times you clicked the button

**Comment by purepear** [comment]
If i add keep-alive(not destroying the components) CPU is ok
```
<keep-alive>
  <router-view></router-view>
</keep-alive>
```

So the bug happens only when the router destroys a component containing `el-table`

**Comment by purepear** [comment]
Here's another example without vue-router https://jsfiddle.net/ojc5Lf83/2/

**Comment by Yifei022** [comment]
+1, 
1.4.7 works fine,
1.4.8 has the same problem

**Comment by purepear** [comment]
I believe the problem comes from:
https://github.com/ElemeFE/element/commit/664f89308680af774551e828e4dae99e14b17527#diff-2464594c163d1fc8302357129290d3d2

**Comment by Leopoldthecoder** [comment]
@purepear Yes, we're on it.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/pull/7899/commits/8ec55ddf69ca0c34a32e1d27e99fda968a16eaba fixes this, but we'll keep looking for a nicer implementation.

**Comment by jri** [comment]
1.4.9 still has the problem
1.4.7 works fine

**Comment by jri** [comment]
1.4.10 still has the problem.

Will it be fixed in 1.x ?
Should this ticket be reopened?

**Comment by imingyu** [comment]
I have the same problem
v1.4.10

**Comment by lynzz** [comment]
I have the same problem
v1.4.10

**Comment by Leopoldthecoder** [comment]
1.4.11 fixes this.

**Comment by jri** [comment]
Confirmed, in 1.4.11 CPU usage is lowered again.
Thank you for fixing!

**Comment by NoahCardoza** [comment]
Still seems to be a problem in 2.0.0-rc.1

**Comment by kkinder** [comment]
I suggest reopening this issue. It is a problem again in 2.x.
