### ISSUE TITLE
[Bug Report] el-table infinity width bug

### ISSUE THREAD

**Issue by yariksav** [ElemeFE/element#7823]
### Element UI version
2.0.1

### OS/Browsers version
MAC OS / Chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/kmns6yz6/5/](https://jsfiddle.net/kmns6yz6/5/)

### Steps to reproduce
if two el-tables has v-if and switch between them, end one of them has a expand column:
After switch - width of table sets to infinity 4.01808e+06px;
`<table cellspacing="0" cellpadding="0" border="0" class="el-table__body" style="width: 4.01808e+06px;"><colgroup><col name="el-table_1_column_1" width="48"><col name="el-table_1_column_2" width="180"><col name="el-table_1_column_3" width="80"></colgroup><tbody><!----></tbody></table>`

### What is Expected?
Correct width of table

### What is actually happening?
Something wrong with calculating width in table-layout.js > fixedWidth

**Comment by Leopoldthecoder** [comment]
Adding a `key` to them helps: https://jsfiddle.net/kmns6yz6/6/

**Comment by yariksav** [comment]
Thanx

**Comment by Leopoldthecoder** [comment]
Not quite qualifies as a bug. It's just that the implementation of Table is a little hacky, so we may need to ask Vue to re-render it. Actually we recommend our users to add a `key` on `el-table` or `el-table-column` when they are used with `v-if`.

**Comment by PleaseTryAgain** [comment]
key is not use to me version1.0.5 . It is because version is too low? how can I fix it @Leopoldthecoder
