### ISSUE TITLE
[Feature Request] NavMenu导航菜单右侧border白边

### ISSUE THREAD

**Issue by d9577** [ElemeFE/element#7826]
### Existing Component
Yes

### Component Name
el-menu

### Description
使用el-menu,mode=vertical时，样式中会有border-right: 1px solid #e6e6e6; 这会导致菜单的右边有一条白线，当菜单右边的布局背景不是白色的话，el-menu和右边的布局之间就会有一条白线，希望能修改一下

**Comment by Leopoldthecoder** [comment]
这个自己覆盖一下 CSS 吧，如果默认没有边框的话，白色背景下看起来就会有些奇怪。
