### ISSUE TITLE
table的远程搜索 sortable="custom" 没办法给多列设置么？ 点了其他列 当前列的排序没了

### ISSUE THREAD

**Issue by heymalio** [ElemeFE/element#783]
![image](https://cloud.githubusercontent.com/assets/4131895/19913860/3158ac3c-a0e1-11e6-9f3d-ee7bdef9f776.png)

**Comment by furybean** [comment]
没怎么见过可以两列排序的 Table 组件，大家可以讨论下，看看这个需求是不是很普遍。

**Comment by furybean** [comment]
看起来不是一个很常见的需求，先关闭了，如果讨论的人多再 open。

**Comment by chaohuaGH** [comment]
@furybean 我觉得这个还是挺常用的一个功能，刚好我也遇到了这样的需求，希望能够加上。

**Comment by TFous** [comment]
@furybean 我也有这种多列排序的需求，多一个功能，给人选择

**Comment by isLooge** [comment]
@furybean  我也支持增加多列排序的功能，很多时候需要基于已排序的列来进行进一步的排序

**Comment by WenJimmy** [comment]
@furybean  我也有多列排序的需求，基于已排序条件再进行另一条件的排序

**Comment by wishflyer** [comment]
@furybean 我也有多列排序的需求，希望能够给于增强！谢谢！

**Comment by limengfan** [comment]
@furybean 我也有多列排序的需求，希望考虑，谢谢！

**Comment by yelqgd** [comment]
@furybean 我也有多列排序的需求，希望考虑，谢谢！
