### ISSUE TITLE
[Bug Report] table component, when the global has a custom scroll bar style, in the safari will appear in the header of gutter width 0 invalid

### ISSUE THREAD

**Issue by anyisky** [ElemeFE/element#7832]
### Element UI version
1.4.8

### OS/Browsers version
mac/safari 10.1.2

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/f73z74d1/](https://jsfiddle.net/f73z74d1/)

### Steps to reproduce
用safari浏览器打开：https://jsfiddle.net/f73z74d1/ 
即可重现

### What is Expected?
希望和chrome下保持一致，表头不发生错位

### What is actually happening?
safari中根据table总宽，再分配到每个td的时候，会差了自定义滚动条的宽度值，导致表头中最后一个th 的width = 0 失效了，组件中设置gutter的th width 0 时，需要设置成display:none

**Comment by furybean** [comment]
Fixed in #9327 for 2.x.
If you need to fix this issue on 1.x, PR is welcome.
