### ISSUE TITLE
[Bug Report] table components, under Safari, when tbody can scroll, there will be a table header dislocation after the scroll bar appears

### ISSUE THREAD

**Issue by anyisky** [ElemeFE/element#7833]
### Element UI version
1.4.8

### OS/Browsers version
mac/safari 10.1.2

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/659/](https://jsfiddle.net/pj71jkyw/659/)

### Steps to reproduce
用safari打开：https://jsfiddle.net/pj71jkyw/659/
即可复现

### What is Expected?
期望和再chrome中一样，始终保持对齐

### What is actually happening?
当tbody可以滚动时，表头和下面内容区会出现1px偏差，有时数据异步回来的话，内容区会撑大td，text-overflow 失效

**Comment by Leopoldthecoder** [comment]
Fixed in #9327
