### ISSUE TITLE
[Bug Report] Form form validation successful color Don't agree

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#7836]
### Element UI version
2.0.1

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/3Ljqaz06/2/](https://jsfiddle.net/3Ljqaz06/2/)

### Steps to reproduce
修改 > 获取数据 > 赋值 > 验证表单颜色不一致

### What is Expected?
外边框颜色一致，或者form标注为修改表单则首次不验证表单,想办法在修改业务的表单上做一次统一验证或不验证。

### What is actually happening?
不一致

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/7838/commits/0707a49b69dee357b84fff3bc3a378fc759f479f

**Comment by An0nymous0** [comment]
@Leopoldthecoder 是延迟1秒验证么？

**Comment by Leopoldthecoder** [comment]
不是，那只是文档上的例子。具体修改是这个文件：https://github.com/ElemeFE/element/commit/0707a49b69dee357b84fff3bc3a378fc759f479f#diff-980f0d07f78cd22e40c7a938744bb8a4

**Comment by An0nymous0** [comment]
@Leopoldthecoder 大概什么时间会发布下一个版本，目前迁移2.0版本只遇到了两个问题，除了这个还遇到一个异步验证会被通过的问题我看有提交解决
https://github.com/ElemeFE/element/commit/468124f9568b16d9cd90d38182a2fe3fcd47032a

**Comment by Leopoldthecoder** [comment]
本周三下班前发布 2.0.2

**Comment by An0nymous0** [comment]
@Leopoldthecoder 谢谢，element框架做的真的很好，给我们这帮主开发后台兼写前台的人省了很多时间。只是这次改版样式有点小怪异嘿嘿。

**Comment by Leopoldthecoder** [comment]
具体是指？

**Comment by An0nymous0** [comment]
比如说一个[选项卡样式的tabs]里面是一个[按钮样式的Radio]下面是一个表格，会感觉很空旷，布局很混乱，1.X版本的起码看起来是一块一块的。都有下边框，表格也有表头配色很鲜明。**_我之前看了theme-chalk主题的设计理念和介绍_**，2.X整体感觉都从简了。 并且感觉整体样式间距之类的偏大。都是手动加上small|mini之类的样式看着还好一些 ，改成2.X版本都得手动加boder，调大小。不知道这样的设计理念是否对小屏友好，我是13存的MBPR，确实很简单但是感觉又太简单。**我是外行，不知道描述的清不清楚，不太懂设计，只是从直觉上感觉是这样，问了几个同事也都有同样的感觉。**
