### ISSUE TITLE
Bug of [Bug Report] time selector

### ISSUE THREAD

**Issue by xiaolieask** [ElemeFE/element#7846]
### Element UI version
1.4.8

### OS/Browsers version
PC下面的360安全浏览器下面的急速模式下的错误

### Vue version
2.5.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/en-US](https://elementui.github.io/issue-generator/#/en-US)

### Steps to reproduce
link？？？？你直接去你官网，选中1.4.8，时间区域的那个选择器的在线运行，或者2.0的那个，全炸了，还tmb的要老夫来教你们怎么做吗?

### What is Expected?
link？？？？你直接去你官网，选中1.4.8，时间区域的那个选择器的在线运行，或者2.0的那个，全炸了，还tmb的要老夫来教你们怎么做吗?

### What is actually happening?
link？？？？你直接去你官网，选中1.4.8，时间区域的那个选择器的在线运行，或者2.0的那个，全炸了，还tmb的要老夫来教你们怎么做吗?

**Comment by Leopoldthecoder** [comment]
Duplicate of #7539. Please search existing issues before submitting a new one.
