### ISSUE TITLE
[Bug Report] Uncaught TypeError: Cannot read property 'firstElementChild' of undefined

### ISSUE THREAD

**Issue by maggiehe** [ElemeFE/element#7849]
### Element UI version
1.4.3

### OS/Browsers version
macOS/Chrome61

### Vue version
2.4.2

### Description

when I quickly add/remove element, an error is thrown.

```
(unknown) Uncaught TypeError: Cannot read property 'firstElementChild' of undefined
    at resetTrigger (eval at <anonymous> (index.js:261), <anonymous>:56:28)
    at HTMLDivElement.eval (eval at <anonymous> (index.js:261), <anonymous>:169:13)
```

There is a related issue in `src/utils/resize-event.js`, which is modified from  `javascript-detect-element-resize`, a library that is no longer maintained.

[https://github.com/sdecima/javascript-detect-element-resize/issues/42](https://github.com/sdecima/javascript-detect-element-resize/issues/42)

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
