### ISSUE TITLE
 遇到bug  切换路由的时候 有时候会报错 ？DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by naihe138** [ElemeFE/element#785]
遇到bug  切换路由的时候 有时候会报错 ？DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

求大神解答

**Comment by reverland** [comment]
#474 ?

**Comment by QingWei-Li** [comment]
rc8？

**Comment by QingWei-Li** [comment]
长期不回复的 issue 我们将关闭，如果问题没有修复请重新开 issue
