### ISSUE TITLE
[Bug Report] Can not delete the uploaded item when set list-type as`picture-card`

### ISSUE THREAD

**Issue by xinz** [ElemeFE/element#7855]
### Element UI version
2.0.1

### OS/Browsers version
macOS 10.12.4 / Firefox 56.0.2, Chorme 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[http://element-cn.eleme.io/2.0/#/en-US/component/upload#photo-wall](http://element-cn.eleme.io/2.0/#/en-US/component/upload#photo-wall)

### Steps to reproduce
When set `list-type` as `picture-card`, after the uploaded successfully, we can not find the delete operation icon when hover on it.

### What is Expected?
There should be a way to remove the uploaded item.

### What is actually happening?
We can not find a way to remove the uploaded item.

**Comment by Leopoldthecoder** [comment]
Fixed in #7857
