### ISSUE TITLE
[Feature Request] need a mean to unselect a radio button

### ISSUE THREAD

**Issue by FranckFreiburger** [ElemeFE/element#7856]
### Existing Component
Yes

### Component Name
Radio / RadioGroup

### Description
I need to unselect all `Radio` from a `RadioGroup` to represent the "`null`" value (for a database query for example).
Currently, even using `@change`, I am not able to unselect a radio. My only option is to add an additional radio (with `null` label), but I think this is not the best solution for end-users.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/5wc28v7y/

**Comment by FranckFreiburger** [comment]
Thanks, for the reply.
The idea of my feature request is just to avoid an additional element to unselect radios.

**Comment by Leopoldthecoder** [comment]
Radios cannot be unselected by design:
> It is possible that initially none of the radio buttons in a group are selected. This unselected state cannot be restored by interacting with the radio button widget, though it may be possible through other user interface elements.

So `other user interface elements` seems to be necessary.

**Comment by FranckFreiburger** [comment]
I understand that element semantics should be respected.
However the following trick with native radio is quite useful:

```vue
<template v-for="(option, index) in options">
	<input
		type="radio"
		v-model="model"
		:value="option.value"
		@click="handleUnselect(index)"
	></input>{{option.text}}
	...

```
```js
...
methods: {
	handleUnselect(index) {

		if ( !this.notnull && this.options[index].value === this.model )
			this.model = null;
	}
}

```

**Comment by Leopoldthecoder** [comment]
If you're OK with some hacking: https://jsfiddle.net/5wc28v7y/1/

**Comment by FranckFreiburger** [comment]
Oh, thanks a lot for the `.native` trick, you make my day !

**Comment by Leopoldthecoder** [comment]
No problem. You may be interested in taking a look at [this](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components).
