### ISSUE TITLE
[Bug Report] Input Height not resetting when cleared value of multiple select mini size

### ISSUE THREAD

**Issue by alexdee2007** [ElemeFE/element#7861]
### Element UI version
2.0.1

### OS/Browsers version
Windows 7 Professional / Google Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mnkwLumv/](https://jsfiddle.net/mnkwLumv/)

### Steps to reproduce
Run the application, click button "Click me" and see what happened.

### What is Expected?
Reset Input Height  when value cleared 

### What is actually happening?
Input Height not resetting

**Comment by Leopoldthecoder** [comment]
Fixed in #7872
