### ISSUE TITLE
[Bug Report] CND import link for version 1.4.8 and below is broken

### ISSUE THREAD

**Issue by ArnoBuschmann** [ElemeFE/element#7868]
### Element UI version
1.4.8

### OS/Browsers version
Linux, Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/664/](https://jsfiddle.net/pj71jkyw/664/)

### Steps to reproduce
When implementing the download link for the Elemen-UI-CSS file for version 1.4.8 and below as described here:

http://element-cn.eleme.io/1.4/#/en-US/component/installation

The link is broken and throws an error message:

```Cannot find module "/lib/theme-default/index.css" in package element-ui@2.0.1```

### What is Expected?
It is expected to download the actual CSS file.

### What is actually happening?
 I have a running website, that is depending on the Element-UI-CSS file, which breaks now, because the file is not available.

**Comment by ryantbrown** [comment]
Yep this is currently breaking our production app

**Comment by Leopoldthecoder** [comment]
You need to specify Element version in the link:
```
unpkg.com/element-ui@1.4.8/lib/index.js
unpkg.com/element-ui@1.4.8/lib/theme-default/index.css
```

[unpkg](https://unpkg.com/#/) will redirect to the latest version if not specified.

**Comment by ArnoBuschmann** [comment]
@Leopoldthecoder thanks for your quick reply. Yes, it is automatically forwarding to:
```https://unpkg.com/element-ui@2.0.1/lib/theme-default/index.css```
But that there the problem is still as described and you get a
```Cannot find module "/lib/theme-default/index.css" in package element-ui@2.0.1```
And since in the documentation the version is not specified:
http://element-cn.eleme.io/1.4/#/en-US/component/installation
all production versions which were running with that link before, are now breaking.
Could be, this behaviour is intentional, but then it maybe makes sense to describe that in the documentation, even if it is unfortunate, that production versions which were installed as per the documentation instructions are breaking without notice right now.

This is just a hint or an idea to reduce problems :)

**Comment by Leopoldthecoder** [comment]
@ArnoBuschmann Yes, I'm adding some tips regarding CDN version in the 1.x docs.
