### ISSUE TITLE
[Bug Report] Select selector (create new items) click cursor little right, drop-down items  cannot open.

### ISSUE THREAD

**Issue by cdw-me** [ElemeFE/element#7870]
### Element UI version
2.0.1

### OS/Browsers version
windows 10 / chrome 62.0.3202.75 （64 bit）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/666/](https://jsfiddle.net/pj71jkyw/666/)

### Steps to reproduce
Repeat click select selector (create new items) cursor little right, drop-down items cannot open.

### What is Expected?
Drop-down items toggle display.

### What is actually happening?
Drop-down items flashing.

**Comment by Leopoldthecoder** [comment]
Sorry I could understand your English. You can use Chinese if you prefer.

**Comment by cdw-me** [comment]
点击可创建条目的select选择器这时会出现光标下拉条目也会打开，再重复点击光标偏右一点位置，下拉条目关闭后，无法再次打开。

**Comment by Leopoldthecoder** [comment]
试了几次没能重现，能贴张动图吗？

**Comment by cdw-me** [comment]
刚才重试了一下,bug出现在鼠标移动到select框当鼠标指针变成 大写i 的时候,点击后下拉列表不显示.鼠标按下不松开下拉列表显示,放开鼠标下拉列表随之消失.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/7899/commits/e169cdaaa0f5108acdb40034497aa89890a35fe5
