### ISSUE TITLE
日期范围 360急速模式完全选择不了

### ISSUE THREAD

**Issue by 1317250030** [ElemeFE/element#7871]
![image](https://user-images.githubusercontent.com/14797360/32204827-a0fe010a-be26-11e7-970a-0e74d4e54f0b.png)

DateTimePicker 日期时间选择器
DatePicker 日期选择器
360急速模式完全选择不了
IE11是可以的

**Comment by icarusion** [comment]
https://github.com/ElemeFE/element/issues/7539#issuecomment-340364193
