### ISSUE TITLE
[Bug Report] date range 360 haste mode completely can not choose

### ISSUE THREAD

**Issue by 1317250030** [ElemeFE/element#7873]
### Element UI version
2.0.1

### OS/Browsers version
360急速模式 win10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/t05pcfo6/](https://jsfiddle.net/t05pcfo6/)

### Steps to reproduce
下载 360安全浏览器9 内核版本是9.1.0.385

### What is Expected?
能选择正常

### What is actually happening?
选择不了还有点击错误的情况  比如我点的是10月1日 但它的焦点缺落在 10月6号上
还有就是IE11是正常的
谷歌浏览器也正常

**Comment by Leopoldthecoder** [comment]
Duplicate of #7539. Please wait for our next release.
