### ISSUE TITLE
[Feature Request] force the scroll bar to show for table

### ISSUE THREAD

**Issue by ensean** [ElemeFE/element#7874]
### Existing Component
Yes

### Component Name
Table

### Description
The scroll bar of the table is not shown when no scroll action is performed, so it's difficult for the user to know that there are more rows than currently shown in the table. If we can force the scroll bar shown by default when there are more rows, it's would be nice for the users.

**Comment by ensean** [comment]
BTW, I am using  v1.4.8

**Comment by Leopoldthecoder** [comment]
Table uses system scrollbar. So if the system setting says scrollbar only appears when scrolling, there's not much we can do.

**Comment by ensean** [comment]
Regarding
>Table uses system scrollbar. So if the system setting says scrollbar only appears when scrolling, there's not much we can do.
It's it possible to put some kind of tip, such as scroll to read more rows, at the bottom of the table to let the user know that there more rows than he currently see.

**Comment by Leopoldthecoder** [comment]
I think should be handled by the developers.

**Comment by ensean** [comment]
Got it, thanks .
