### ISSUE TITLE
When the [Bug Report] component exists both fixed column and total row, the horizontal scroll bar will cause the pattern dislocation

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#7875]
### Element UI version
2.0.1

### OS/Browsers version
Windows / Firefox 56

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/dgkgwkm9/1/](https://jsfiddle.net/dgkgwkm9/1/)

### Steps to reproduce
1、新增表格组件
2、启用合计行（show-summary）
3、将表格中的一些列设置为固定（fixed）
4、设置表格列的宽度，使表格出现横向滚动条
5、在Windows系统中，由于横向滚动条有高度，因此表格出现错位

### What is Expected?
合计行固定的部分和横向滚动的部分应该对齐

### What is actually happening?
合计行下方出现了错位的情况

**Comment by Leopoldthecoder** [comment]
Duplicate of #5415
