### ISSUE TITLE
[Feature Request] out of box dashboard

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#7878]
### Existing Component
否

### Component Name
dashboard

### Description
1.http://pro.ant.design/

2.https://iview.github.io/iview-admin/#/form/workflow

我们有这方面的计划么,期待。

**Comment by Leopoldthecoder** [comment]
团队在短期内没有这方面的计划，不过社区里已经有比较成熟的产品了：https://github.com/PanJiaChen/vue-element-admin
