### ISSUE TITLE
[Bug Report] steps Vertical step bars icon width err

### ISSUE THREAD

**Issue by DestinyHunter** [ElemeFE/element#7880]
### Element UI version
2.0.1

### OS/Browsers version
win10/chrome61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/dgkgwkm9/4/](https://jsfiddle.net/dgkgwkm9/4/)

### Steps to reproduce
```
<el-steps direction="vertical" :active="1" space="60px">
    <el-step title="步骤 1" icon="el-icon-edit"></el-step>
    <el-step title="步骤 2" icon="el-icon-edit"></el-step>
    <el-step title="步骤 3" icon="el-icon-edit" description="这是一段很长很长很长的描述性文字"></el-step>
  </el-steps>
```

### What is Expected?
```
&.is-vertical {
    .el-step__icon {
      &.is-icon {
        width: 24px;
      }
    }
  }
```

### What is actually happening?
```
&.is-vertical {
    .el-step__icon {
      &.is-icon {
        width: 40px;
      }
    }
  }
```

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/7891/commits/66a7323804b53d09b207dc273eeef4ce78704d1e
