### ISSUE TITLE
[Bug Report] Remote Select malfunction on select

### ISSUE THREAD

**Issue by johncade** [ElemeFE/element#7881]
### Element UI version
2.0.1

### OS/Browsers version
windows/chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/vzo1h1t4/](https://jsfiddle.net/vzo1h1t4/)

### Steps to reproduce
Use a list of objects that do not have the `value` / `label` keys that are in the example.
Use a search term that will show multiple values in the drop down
Select a value

### What is Expected?
The appropriate value is selected

### What is actually happening?
A value other than the intended value is selected

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/vzo1h1t4/1/
> If the binding value of Select is an object, make sure to assign value-key as its unique identity key name.
