### ISSUE TITLE
[Bug Report] Select is not displaying default value

### ISSUE THREAD

**Issue by johncade** [ElemeFE/element#7882]
### Element UI version
2.0.1

### OS/Browsers version
windows/chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/jnkah8Lv/1/](https://jsfiddle.net/jnkah8Lv/1/)

### Steps to reproduce
Use a list of objects that do not have the `value` / `label` keys that are in the example.
Have a preset value for the select model that has the same properties as the objects in the list

### What is Expected?
The preset value's designated (label) property value should be displayed in the select

### What is actually happening?
The placeholder is displayed in the select

**Comment by Leopoldthecoder** [comment]
- Use `value-key`
- `this.options4` should be initialized

https://jsfiddle.net/jnkah8Lv/2/
