### ISSUE TITLE
[Bug Report] Default theme css - cannot find module

### ISSUE THREAD

**Issue by maxxdev** [ElemeFE/element#7884]
### Element UI version
2.0.1

### OS/Browsers version
Google Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/r7qwke1f/38/](https://jsfiddle.net/r7qwke1f/38/)

### Steps to reproduce
Try to Include CSS <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css"> to html

### What is Expected?
success loaded css

### What is actually happening?
Getting error: "unpkg.com/element-ui@2.0.1/lib/theme-default/index.css Failed to load resource: the server responded with a status of 404 ()"

**Comment by wacky6** [comment]
2.0 theme file changed to `theme-chalk`

**Comment by Leopoldthecoder** [comment]
#7868
