### ISSUE TITLE
[Feature Request] tre control set expand-on-click-node optimization

### ISSUE THREAD

**Issue by mjyg** [ElemeFE/element#7887]
### Existing Component
是

### Component Name
tree

### Description
在设置expand-on-click-node为false时，点击箭头展开父节点，点击范围太小，比较难点中，体验太差，希望可以优化这一点。

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/pull/7891/commits/77d70251a35f4483f8204b8c7e809fd7c5b49619 扩大了点击热区。
