### ISSUE TITLE
[Feature Request] el-carousel Height Self-Adaption

### ISSUE THREAD

**Issue by dizys** [ElemeFE/element#7889]
### Existing Component
是

### Component Name
Carousel

### Description
I've got images shown in the Carousel component.
This Carousel should be as wide as the client window, and the images inside as well, which means the style for the image element is like 'width: 100%. But when the client window's width changes, the height of the images also changes to keep the height/width ratio still. But el-carousel doesn't seem to have the ability to change its height according to its content. Instead, the height parameter for Carousel is fixed. It would be a great feature to make Carousel's height self-adaptable.

**Comment by xiaomingTang** [comment]
There is a same trouble with me, did you resolve it?

**Comment by heikezy** [comment]
I eventually use vue-awesome-swiper as the carousel instead. It works pretty well for my project.

https://github.com/surmon-china/vue-awesome-swiper

**Comment by xiaomingTang** [comment]
@heikezy thank you, a cool and useful component it is!
