### ISSUE TITLE
每次进入页面，该页面的Popover组件就会快速闪现一下并消失，同时控制台会报一个Vue warn警告

### ISSUE THREAD

**Issue by wukongtime** [ElemeFE/element#789]
### ElementUI version
1.0.0-rc.8

### OS/Browers version
macOS/Chrome 53 & Firefox 49

### Vue version
 2.0.0-rc.4

### What is actually happening?
如果我的项目上的某个页面中有Popover组件，那么在加载该页面时，Popover会快速闪一下。chrome和firefox都会有该问题。代码如下：
‘’‘
<el-popover placement="bottom" width="300" trigger="click" v-model="selconditions">
<el-button type="primary" slot="reference">筛选条件</el-button>
</el-popover>
’‘’
我尝试在mounted时，将this.selconditions = false，并没有什么作用。报错信息如下：
vue.common.js?5ddb:2611 [Vue warn]: Invalid prop: type check failed for prop "value". Expected Boolean, got Array. 
(found in component <el-popover>)
具体问题动图如下：
![](http://oe5jwakw8.bkt.clouddn.com/GIF.gif)
如果图挂了，请看如下链接：http://oe5jwakw8.bkt.clouddn.com/GIF.gif
非常感谢。

**Comment by Leopoldthecoder** [comment]
`this.selconditions` 的初始值看上去是一个数组？

**Comment by wukongtime** [comment]
非常感谢，selconditions给了[]的初始值。
