### ISSUE TITLE
DateTimePicker with Internationalization

### ISSUE THREAD

**Issue by skiller008** [ElemeFE/element#7890]
**Existing Component**

是

**Component Name**

DateTimePicker with Internationalization

**Version**

1.4.6

**Description**

1.DateTimePicker 的 pickerOptions.shortcuts[i].text属性只支持字符串，使用vue-i18n实现国际化需要初始化后额外替换shortcuts的配置。
2.使用element ui的国际化时，日期选择区的语言无法切换。
如：
页面载入配置为'zhCN'时，日期显示为“2017 年 10 月”，星期标题显示为“日 一 二 三 四 五 六”，切换语言为"en"，日期显示及星期标题仍保持不变。
页面载入配置为"en"时，日期显示为“2017 Oct”, 星期标题显示为“Sun Mon Tue Wed Thu Fri Sat”，切换语言为“zhCN”，日期显示及星期标题仍保持不变。

注：使用CDN接入，没有使用NPM以及没有搭建前端工程。

**Comment by duuliy** [comment]
请问下  您  cdn里面是没有提供locale 方法的   cdn  国际化最后是怎么解决的

**Comment by duuliy** [comment]
Vue.use(ELEMENT,{
  i18n: (key, value) => i18n.t(key, value)
});

Injecting ele custom method dependency into Vue

**Comment by duuliy** [comment]
Vue.use(ELEMENT,{
i18n: (key, value) => i18n.t(key, value)
});

Injecting ele custom method dependency into Vue

@skiller008
