### ISSUE TITLE
When the [Bug Report] global configuration size is medium, the paging component's input frame size is incorrect

### ISSUE THREAD

**Issue by liekkas3175** [ElemeFE/element#7896]
### Element UI version
2.0.1

### OS/Browsers version
windows / chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/o7xpvrq1/1/](https://jsfiddle.net/o7xpvrq1/1/)

### Steps to reproduce
打开运行即可重现，https://jsfiddle.net/o7xpvrq1/1/

### What is Expected?
前往输入框的大小应该与分页页码保持一致

### What is actually happening?
明显与分页组件整体大小不一致

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/7899/commits/a93e04206be8e4ac35b50cf85afb28fd29cfa8a6
