### ISSUE TITLE
[Bug Report] [Bug Report] DatePicker type="datetimerange" , set editable false is not work

### ISSUE THREAD

**Issue by w514986768** [ElemeFE/element#7904]
### Element UI version
2.0.2

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
[http://jsfiddle.net/pj71jkyw/673/](http://jsfiddle.net/pj71jkyw/673/)

### Steps to reproduce
DatePicker type="datetimerange" 设置editable=false

### What is Expected?
不能再日期选择范围框输入值

### What is actually happening?
依然可以输入值

**Comment by Leopoldthecoder** [comment]
Fixed in #7922
