### ISSUE TITLE
[Bug Report] Cannot find module "/lib/theme-default/index.css" in package element-ui@2.0.2

### ISSUE THREAD

**Issue by lucho99** [ElemeFE/element#7906]
### Element UI version
2.0.2

### OS/Browsers version
MacOS/ Chrome  61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Open dev tools and you'll notice -> GET https://unpkg.com/element-ui@2.0.2/lib/theme-default/index.css net::ERR_ABORTED

### What is Expected?
GET https://unpkg.com/element-ui@2.0.2/lib/theme-default/index.css should load. Tried older version of the library but problem stills.

### What is actually happening?
GET https://unpkg.com/element-ui@2.0.2/lib/theme-default/index.css net::ERR_ABORTED
Cannot find module "/lib/theme-default/index.css" in package element-ui@2.0.2

**Comment by psychokiller666** [comment]
import 'element-ui/lib/**theme-chalk**/index.css'

**Comment by lucho99** [comment]
Thanks @psychokiller666 , that worked.

**Comment by rodchencko** [comment]
Hello, I need a backup from "theme-defult" file (//unpkg.com/element-ui/lib/theme-default/index.css). Where can I get it? Theme Chalk has some changes that crash my app.

Any help is appreciated.
