### ISSUE TITLE
[Bug Report] When I delete the column which is fixed, the Element UI delete the unfixed column too

### ISSUE THREAD

**Issue by tczhangzhi** [ElemeFE/element#7908]
### Element UI version
2.0.2

### OS/Browsers version
Mac OS

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/tczhangzhi/n2ytg1zc/](https://jsfiddle.net/tczhangzhi/n2ytg1zc/)

### Steps to reproduce
Click the button named "Change"

### What is Expected?
It should delete the column named "index" only

### What is actually happening?
It also hide the column named "Date"
Maybe the 'is-hidden' class causes this question, which is related to the columns in 'table-store.js'

**Comment by furybean** [comment]
I find this issue is already fixed some days ago: #9188. Please wait next release.
