### ISSUE TITLE
[Bug Report] Radio component attribute "label" should be named "value".

### ISSUE THREAD

**Issue by pokluda** [ElemeFE/element#7910]
### Element UI version
2.0.2

### OS/Browsers version
any

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/678/](https://jsfiddle.net/pj71jkyw/678/)

### Steps to reproduce
1. use radio component
2. wonder why the value attribute is called "label"

### What is Expected?
"label" attribute of the Radio component should be named "value". (take Select component for example)

### What is actually happening?
you might know what I mean by now.

**Comment by wacky6** [comment]
'value' is a vue convention used to bind component value by v-model

**Comment by Leopoldthecoder** [comment]
Yes, what @wacky6 said is the reason we used `label` in the first place.

Vue 2.2 introduced a feature allowing us to customize variable name used by v-model: https://vuejs.org/v2/guide/components.html#Customizing-Component-v-model . So when developing Element 2.0 we actually considered changing `label` to `value`, and using another variable (`model` or something) in v-model. But there are cases where you can't use v-model directly:

- component value is stored inside Vuex state
- you're writing JSX

In these cases you'll have to write something like this
```html
<el-radio :value="radioValue" :model="componentValue" @input="onInput"></el-radio
```
while other form components look like this
```html
<el-input :value="componentValue" @input="onInput"></el-input>
```
This results in a inconsistency of what `value` means between Radio and other form components.

So as a trade-off, we decided to keep `label`.

**Comment by pokluda** [comment]
@Leopoldthecoder: thanks for the full explanation, appreciate it. Makes sense in this case, I'll still love Vue the same :)
