### ISSUE TITLE
[Bug Report] Message resets scroll

### ISSUE THREAD

**Issue by francoislevesque** [ElemeFE/element#7911]
### Element UI version
2.0.2

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/gmve9d3p/183/](https://jsfiddle.net/gmve9d3p/183/)

### Steps to reproduce
1. Open a message
2. Scroll to the bottom
3. When the message closes, the scroll resets

### What is Expected?
The scrolling should not be affected. The scroll should not reset.

### What is actually happening?
The scroll is reset when the message closes.

**Comment by Leopoldthecoder** [comment]
Fixed in #7942
