### ISSUE TITLE
[Feature Request] $message call mode

### ISSUE THREAD

**Issue by kiyonlin** [ElemeFE/element#7914]
### Existing Component
Yes

### Component Name
Message

### Description
个人感觉：
第一：调用方式不统一；
第二：传入对象的方式不是很优雅

建议success和warning的调用方式也统一成链式调用。

      open() {
        this.$message('这是一条消息提示');
      },
      open2() {
        this.$message({
          message: '恭喜你，这是一条成功消息',
          type: 'success'
        });
      },

      open3() {
        this.$message({
          message: '警告哦，这是一条警告消息',
          type: 'warning'
        });
      },

      open4() {
        this.$message.error('错了哦，这是一条错误消息');
      }

**Comment by Leopoldthecoder** [comment]
> 我们也为每个 type 定义了各自的方法，如 `Message.success(options)`

都可以链式调用。
