### ISSUE TITLE
[Feature Request] can the filter capabilities of Table support backend filtering?

### ISSUE THREAD

**Issue by ukhack** [ElemeFE/element#7918]
### Existing Component
Yes

### Component Name
el-table

### Description
目前排序加入了后端排序的支持。但是筛选我看了一下，还不支持后端的筛选呢。
可不可以像排序那样加入一个字段(custom)，然后有它的话就用回调函数从后端取数据，重新赋值。

**Comment by goodwong** [comment]
el-table组件有filter-change事件，根据返回的filter数据做后端筛选。
记得给column设置column-key
