### ISSUE TITLE
[Bug Report] form item border color problem using validator

### ISSUE THREAD

**Issue by bitjjj** [ElemeFE/element#7921]
### Element UI version
2.0.2

### OS/Browsers version
Chrome 62

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/bitjjj/3hLkzfbo/](https://jsfiddle.net/bitjjj/3hLkzfbo/)

### Steps to reproduce
1. 在活动名称输入框输入6个以上字符
2. 输入框颜色会变色，并提示错误信息
3. 按delete键删除字符到4个
4. 错误信息消失，但是输入框颜色没有恢复默认颜色，仍然提示错误

### What is Expected?
输入框边框颜色在输入内容正确之后恢复默认颜色

### What is actually happening?
输入框边框颜色在输入内容正确之后颜色仍然显示错误信息的颜色

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/32258704-0f0303a0-bef7-11e7-995b-225266655b93.gif)

没能重现

**Comment by bitjjj** [comment]
![wx20171101-131734](https://user-images.githubusercontent.com/3096226/32261109-5e7233d8-bf07-11e7-8fee-174bb1a4979e.png)

@Leopoldthecoder 正确输入后，边框仍然保持这个颜色，这不是bug吗？

**Comment by Leopoldthecoder** [comment]
`#FA5555` 和 `#67C23A` 对于非红绿色盲来说没什么区分难度吧。后面会考虑提供一个选项，禁止在边框颜色体现校验结果。
