### ISSUE TITLE
[Feature Request] trouble DatePicker type add new monthrange type, single frame select month range

### ISSUE THREAD

**Issue by ewgcat** [ElemeFE/element#7925]
### Existing Component
Yes

### Component Name
DatePicker

### Description
麻烦type 新增monthrange 类型，单框选择月份范围

**Comment by ewgcat** [comment]
感谢大牛

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can implement this by putting two month-typed DatePickers on the page.
