### ISSUE TITLE
[Bug Report] PopperJS is not a constructor

### ISSUE THREAD

**Issue by haoxl3** [ElemeFE/element#7928]
### Element UI version
2.0.0

### OS/Browsers version
win7/chrome 55.0.2883.75m

### Vue version
2.5.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
1.因项目需要不是采用npm install element-ui将其注入到项目中的，而是把所有组件源码拷到项目中再暴露出去。如：
const install = function(Vue,options){
     Object.keys(components).forEach(key=> Vue.component(key,components[key]))
}
export{ install}
install里面为各种element-ui组件
2.现在我想使用el-color-picker这个组件，我在一个.vue文件中按官网正确写完后运行时报错说PopperJS is not a constructor。请问这是什么原因导致的？

### What is Expected?
期待所有组件可以正确使用即可，当我用官网推荐的写法引入那些组件时是可以正常使用的，但项目要求那样写

### What is actually happening?
实际有许多组件都不能正常使用，经常报PopperJS is not a constructor

**Comment by Leopoldthecoder** [comment]
自己看一下 src/utils/popper.js 有没有正确引入。

**Comment by zhanghao-zhoushan** [comment]
find `element-ui/utils/vue-popper.js`.

 There's a problem with this code.

`require('./popper')` 

maybe you change  `.babelrc` stage

```
import Vue from 'vue';
import {
  PopupManager
} from 'element-ui/src/utils/popup';

// 
// const PopperJS = Vue.prototype.$isServer ? function () { } : require('./popper');
// you need  use es6 import it
 import PopperJS from './popper.js' 

```

change `./popper.js` export method

```
function popper() {
// ......
}
var popper = popper();

export default popper;
```

or

you can to update `popper.js`

but use method has difference

**Comment by chencanbin** [comment]
请问这个问题需要如何解决？

**Comment by kim-jeongki** [comment]
You must config in babel-loader exclude options below code
```js
rules: [
    {
        loader: 'babel-loader',
        include: [ __dirname + '/src/, __dirname + '../node_modules/element-ui/src/utils'],
        // exclude elemet-ui umd modules ref by https://github.com/ElemeFE/element/blob/4b3edc13abbac373d58503f9bc5223a7853d6df0/build/config.js
        exclude: /node_modules\/element-ui\/src\/(utils\/popper\.js|utils\/date.\js)/
   }, ...
```

**Comment by Glenfiddish** [comment]
@kim-jeongki thanks a lot, it works. It seem that recompile of the utils file occur an Error.
