### ISSUE TITLE
The table component adds border properties and generates a horizontal scroll bar

### ISSUE THREAD

**Issue by brett25** [ElemeFE/element#7929]
Element UI version

2.0.1

OS/Browsers version

win10 / google 56.0.2924.87

Vue version

2.5.2

Reproduction Link

none

Steps to reproduce

 <el-table
      :data="roleList"
      border
      style="width: 100%"
      >
  <el-table-column
        prop="name"
        label="角色名"
        sortable
        :width="150">
      </el-table-column>
   <el-table-column
        label="类型"
        :width="150">
        <template slot-scope="scope">
          {{ roleTypeCol(scope.row) }}
          </template>
    </el-table-column>
  <el-table-column label="操作">
        <template slot-scope="scope">
            ...
       </template>
</el-table-column>
</el-table>

What is Expected?

when adding border properties ,no horizontal scroll bar

What is actually happening?
generates a horizontal scroll bar

**Comment by VinceBassman** [comment]
Hi brett, could you solve this issue? I have the same problem but I am not able to reproduce it in fiddle...

**Comment by SuperAL** [comment]
@VinceBassman 
Try this: 
```css
.el-table__body-wrapper table {
    display: block;
}
```
