### ISSUE TITLE
[Bug Report] table asc/desc icon is not clear

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#7930]
### Element UI version
1.4.9

### OS/Browsers version
all

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/zpczjl/8snu8ow7/](https://jsfiddle.net/zpczjl/8snu8ow7/)

### Steps to reproduce
The asc and desc icon is too small and the default color is light. It's hard for me to distinct which column is in sort, and it's in desc or asc.

### What is Expected?
rt

### What is actually happening?
rt

**Comment by pushchris** [comment]
Very much agree with this. The icons are small and too close in color to be able to tell the difference. People with color blindness will additionally never be able to tell the difference

**Comment by Leopoldthecoder** [comment]
I have talked with our designer about this and we'll replace them.

**Comment by njleonzhang** [comment]
@Leopoldthecoder Tnx, it is great!

**Comment by Leopoldthecoder** [comment]
Old school sorting arrows are brought back in #8190.

**Comment by Erdboden** [comment]
@Leopoldthecoder providing a column with sort and filter make the icons overlap

https://jsfiddle.net/3dg2vok7/

**Comment by Leopoldthecoder** [comment]
@Erdboden I'll fix it.
