### ISSUE TITLE
[Feature Request] upload photo wall inside the ring progress adjustment size

### ISSUE THREAD

**Issue by Fancyhr** [ElemeFE/element#7933]
### Existing Component
Yes

### Component Name
upload 照片墙

### Description
element-ui v2.0.2、vue v2.5.2
现在照片墙是可以调整大小的，但是里面的圆环进度是不会自动跟着变

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by zwmmm** [comment]
解决了么 这个问题
