### ISSUE TITLE
The [Bug Report] Upload component on-preview event is unresponsive and cannot be previewed

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#7935]
### Element UI version
2.0.2

### OS/Browsers version
win10/chrom61.0.3163.100（正式版本）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/zqj5ztvw/](https://jsfiddle.net/zqj5ztvw/)

### Steps to reproduce
点击选择文件 > 上传文件 > 上传成功 > 点击预览

### What is Expected?
打开预览dialog并看到已上传的图片

### What is actually happening?
无响应

**Comment by Leopoldthecoder** [comment]
Dialog 已经不支持 `v-model` 了，用 `:visible.sync`
