### ISSUE TITLE
[Bug Report] How to set the number as the value of the switch components

### ISSUE THREAD

**Issue by hoanghiep1x0** [ElemeFE/element#7937]
### Element UI version
2.0.2

### OS/Browsers version
chrome 64

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/hoanghiep/z97te3z7/](https://jsfiddle.net/hoanghiep/z97te3z7/2/)

### Steps to reproduce
run demo

### What is Expected?
can set value to number

### What is actually happening?
Value does not work

**Comment by Leopoldthecoder** [comment]
In 2.0 `on-*` and `off-*` attributes are renamed: https://jsfiddle.net/z97te3z7/3/ . See the changelog for more details.
