### ISSUE TITLE
ie Dialog close twinkle

### ISSUE THREAD

**Issue by tr2333** [ElemeFE/element#7938]
Element UI version

2.0.2

OS/Browsers version

win10/IE 11

Vue version

2.5.2

Reproduction Link

http://element-cn.eleme.io/2.0/#/zh-CN/component/dialog

Steps to reproduce

打开Dialog并关闭

What is Expected?

正常关闭

What is actually happening?

几率性出现弹窗闪烁

**Comment by Zhu-Pc** [comment]
I also encountered this problem but  I'I'm going to give up IE.
