### ISSUE TITLE
[Bug Report] 表单验证数字类型输入“数字 其他字符”依然能验证通过，如“123abc”

### ISSUE THREAD

**Issue by luozhihua** [ElemeFE/element#7945]
### Element UI version
1.4.9

### OS/Browsers version
Mac 和 Windows， Chrome 最新版

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/xk8o00a2/1/](https://jsfiddle.net/xk8o00a2/1/)

### Steps to reproduce
1. 在输入框中输入字符：“123abc” 或 “456万元”
2.  点击【提交】按钮后输入框变绿，提示“Submit!”

下面两个链接都是ElementUI 官网上的数字验证 DEMO，同样有问题（
http://element-cn.eleme.io/#/zh-CN/component/form#shu-zi-lei-xing-yan-zheng
https://jsfiddle.net/xk8o00a2/1/

### What is Expected?
在输入框中输入字符“123abc” 或 “456万元”时，验证不通过，输入框变红色！

### What is actually happening?
在输入框中输入字符“123abc” 或 “456万元”时，验证通过，输入框变绿！

**Comment by Leopoldthecoder** [comment]
因为输入 `123abc` 的时候，Vue 会帮你转成 `123`：https://jsfiddle.net/xk8o00a2/3/
如果想对用户有个提示，可以稍微 hack 一下：https://jsfiddle.net/xk8o00a2/2/
