### ISSUE TITLE
[Bug Report] table出现水平滚动条 滚不动且错位

### ISSUE THREAD

**Issue by treasureDouDou** [ElemeFE/element#7948]
### Element UI version
2.0.2

### OS/Browsers version
win10

### Vue version
2.5.2

### Steps to reproduce
el-table-column 加上 fixed="left"属性，X轴缩小浏览器窗口，出现X轴滚动条，但是滚不动，且与固定列错位。
如不加上fixed="left"，X轴缩小浏览器窗口，出现X轴滚动条，但也滚不动

### What is Expected?
不要滚不动的滚动条不要错位

### What is actually happening?
错位，滚动条滚不动
![qq 20171101195754](https://user-images.githubusercontent.com/21187862/32275163-1ccd3c64-bf45-11e7-983c-e7f43086d421.png)

**Comment by pz25925** [comment]
2.0.3 版本
同样出现这个问题

**Comment by momodexuyuan** [comment]
2.0.5 同样问题

**Comment by treasureDouDou** [comment]
@momodexuyuan  @pz25925  已解决，单独拖table组件放在src里面，改源码，改了就正常了

**Comment by treasureDouDou** [comment]
![image](https://user-images.githubusercontent.com/21187862/33008892-e4ba4de2-ce0f-11e7-9c14-625c8141fc20.png)
![image](https://user-images.githubusercontent.com/21187862/33008934-055e573c-ce10-11e7-8d53-8d4ba8b1a2d6.png)

![image](https://user-images.githubusercontent.com/21187862/33009015-47c754a2-ce10-11e7-9964-65b793322c0c.png)

**Comment by treasureDouDou** [comment]
拖出来的table,里面src路径换成lib已经编译的问题，不然打包报编译错误

**Comment by pz25925** [comment]
@treasureDouDou 

我是修改了默认样式修复的. 但是不知道原理...

![image](https://user-images.githubusercontent.com/12759499/33009763-c82fd752-ce12-11e7-9b9e-be6c1736fca8.png)

**Comment by treasureDouDou** [comment]
@pz25925 我是动态加入数据导致的。官网组件，动态加入数据并不会再次初始化。当缩放窗口就会初始化布局。动态加入数据加上css布局，这就导致了bug,滚动条错位。我的数据如下图
![image](https://user-images.githubusercontent.com/21187862/33009885-36715b14-ce13-11e7-85b8-a27a3ea9fc95.png)

**Comment by momodexuyuan** [comment]
@treasureDouDou 我的也是动态添加数据。根据你的思路，我用另外的方法解决了。2.0.5更新支持了表格doLayout()。在动态添加数据后，执行一次doLayout就好了。
```JavaScript
this.data.push({
  id: 1,
  name: 'joker'
})

this.$nextTick(() => {
      this.$refs.testTable.doLayout()
})
```

**Comment by treasureDouDou** [comment]
@momodexuyuan 版本更新太快了,没多少天，没注意这些，我是2.02的版本

**Comment by weifeiyue** [comment]
@treasureDouDou @momodexuyuan 你们如何解决这个问题？
![image](https://raw.githubusercontent.com/weifeiyue/screenshot/master/table-bug.gif)

**Comment by momodexuyuan** [comment]
@weifeiyue 监听窗口大小变化，然后重新渲染表格

**Comment by treasureDouDou** [comment]
@weifeiyue 方法1，监听窗口，重新布局。方法二，改源码。我用的第二个，因为很多地方会用这玩意

**Comment by weifeiyue** [comment]
@momodexuyuan  @treasureDouDou  谢谢，怎么官方不解决:joy:

**Comment by weifeiyue** [comment]
@Leopoldthecoder 麻烦验证一下这个是否为bug？

**Comment by coyi-zdy** [comment]
@pz25925  你弄懂这个overLay的属性的作用了吗？我的理解是它忽略了scroll的高宽，我这边的业务场景用你说的这个解决了问题，尽量没去重写组件。。。也只是在chrome上用。所以满足，赞一个。

**Comment by StephenSeraph** [comment]
+1

**Comment by mmfjx** [comment]
+1
