### ISSUE TITLE
firefox下button组件样式不一致

### ISSUE THREAD

**Issue by reverland** [ElemeFE/element#795]
在firefox下，按钮中文字位置偏下

![screenshot from 2016-11-02 23-48-11](https://cloud.githubusercontent.com/assets/1418726/19935975/efe799c2-a156-11e6-9334-a6d4d399fa16.png)

同样在chromium下

![screenshot from 2016-11-02 23-50-25](https://cloud.githubusercontent.com/assets/1418726/19936050/3659e0b8-a157-11e6-8502-58b052e1edbe.png)

### ElementUI version
1.0.0-rc.8

### OS/Browers version
Linux/firefox 49

**Comment by reverland** [comment]
顺便，slider
![screenshot from 2016-11-02 23-53-59](https://cloud.githubusercontent.com/assets/1418726/19936283/f5eaa336-a157-11e6-8b9b-7d4117ccf27f.png)

**Comment by Leopoldthecoder** [comment]
这是官方文档上的例子吗？我这边用 firefox 49 是正常的

**Comment by reverland** [comment]
是官方文档上的例子，ubuntu 16.04 64-bit/ Firefox 49.

额。。奇怪

**Comment by Leopoldthecoder** [comment]
看来是系统的原因……Slider 按钮的样式作了修改，等 rc.9 出来了可以再试试

**Comment by reverland** [comment]
mac下firefox 49也没问题，感觉，和字体有点关系。

或者linux下什么插件扩展可能吧，我回去再看看

**Comment by reverland** [comment]
slider在mac下的firefox也没看到问题。。。

**Comment by reverland** [comment]
是不是这里的定位都和字体有关系...

**Comment by reverland** [comment]
囧，似乎真是操作系统特有的。把firefox -safe-mode启动都会不对

**Comment by Leopoldthecoder** [comment]
在 rc.9 下试试 Button 和 Slider？

**Comment by furybean** [comment]
7 日无反馈的 issue 会被关闭，如果觉得有必要，可以重新打开。
