### ISSUE TITLE
[Bug Report] table with fixed header will widen table Infinitely and automatically

### ISSUE THREAD

**Issue by xutyne** [ElemeFE/element#7950]
### Element UI version
2.0.2

### OS/Browsers version
macbook Chrome 61.0.3163.100

### Vue version
2.5.2

### Steps to reproduce
设置table height 属性 700 ，table父容器 高度超过 700 时，就会自动加宽（style 中的 width 不断加大）

### What is Expected?
fix bug  

### What is actually happening?
talbe 宽度不断加宽
##  result
![mnxypfvbk0](https://user-images.githubusercontent.com/11693456/32276701-e5d3ee90-bedd-11e7-89d9-790f981a218c.gif)
## code
<img width="633" alt="template" src="https://user-images.githubusercontent.com/11693456/32276710-ed51fbf8-bedd-11e7-80db-2fbcd69b9b72.png">
<img width="543" alt="script" src="https://user-images.githubusercontent.com/11693456/32276719-f31a17aa-bedd-11e7-9859-12e93eb88f21.png">

希望快点修个版本出来，期待2.0release

**Comment by pfpGit** [comment]
我也出现同样的问题，临时解决办法是：

1、给header,body添加样式100%!important；

2、给每一列添加宽度属性

代码如下：

`<style>
.el-table__header,
.el-table__body {
  width: 100%!important;
}
</style>
<template>
<el-table :data="tableData">
  <el-table-column prop="date" label="日期" width="180">
  </el-table-column>
  <el-table-column prop="name" label="姓名" width="180">
  </el-table-column>
  <el-table-column prop="address" label="地址" width="180">
  </el-table-column>
</el-table>
</template>`

**Comment by TAKA-KII** [comment]
I have problem likely to this problem.
My problem by vue-data-tables, el-table add parameter border:false don't moving

I identified the cause
.resize-triggers, .resize-triggers > div, .contract-trigger:before
width:100%
but, I do not know who setting ResizeListener (by Chart.js ?)

**Comment by furybean** [comment]
@TAKA-KII @pfpGit @xutyne is there anyone provide a demo to reproduce this issue?

**Comment by furybean** [comment]
与 #2716 重复，请关注 #2716 的进度。
