### ISSUE TITLE
[Bug Report] Form with single input element submits itself

### ISSUE THREAD

**Issue by apexJCL** [ElemeFE/element#7951]
### Element UI version
1.4.9

### OS/Browsers version
ArchLinux

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/apexjcl/czdny1nu/](https://jsfiddle.net/apexjcl/czdny1nu/)

### Steps to reproduce
Just type anything (or not) into the input and press enter.

### What is Expected?
That form does not submit

### What is actually happening?
The form submit event is triggered, and even using the `@submit` on the form, it gets ignored

**Comment by Leopoldthecoder** [comment]
This is the default behavior of browsers:
- when you have only one input: https://jsfiddle.net/rswut6kk/
- when you have more than one inputs: https://jsfiddle.net/rswut6kk/1/

To prevent this, add `@submit.native.prevent` on `<el-form>`: https://jsfiddle.net/yk8hxu8d/3/

**Comment by kevrousso** [comment]
This would be a good thing to add up in the docs... been searching for this for quite some time.
