### ISSUE TITLE
[Feature Request] [SCSS] Please add more variables to be customized in the main scss file

### ISSUE THREAD

**Issue by kevinheyo** [ElemeFE/element#7952]
### Existing Component
Yes

### Component Name
SCSS Customization

### Description
Doc:  http://element.eleme.io/#/en-US/component/custom-theme

To customize variables just in the main scss file is more fluently and maintainable than building the theme outside from the project!

Variables like:
- $--select-tag-color
  - the default is $--color-white, and it's vary hard to see the tag text...

**Comment by Leopoldthecoder** [comment]
You'll be able to customize all variables in the next release.

By the way, `$--select-tag-color` is actually a mistake.
