### ISSUE TITLE
[Bug Report] el-tabs in electron-vue causes the page to be stuck and cannot enter.

### ISSUE THREAD

**Issue by JingchaoZhao** [ElemeFE/element#7953]
### Element UI version
0.1.0

### OS/Browsers version
win 10， electron打包的chrome。

### Vue version
2.3.3

### Reproduction Link
[打包成app，无链接。  https://elementui.github.io/issue-generator/#/zh-CN ](打包成app，无链接。  https://elementui.github.io/issue-generator/#/zh-CN )

### Steps to reproduce
1. 使用electron-vue 新建一个项目；
2. 引用 element-ui库；写一个测试component，只包含 el-tabs， 为该component设置一个router；
3. 使用npm run build 生成exe；
4. 运行改exe，点击那个测试component的路由；
5. 路由未跳转，页面卡死。

### What is Expected?
正常展示el-tabs页面。

### What is actually happening?
页面卡死，无法进行后续任何操作。
特别说明：
1. npm run dev时，有可能行为正常，run build时会卡死；
2. 使用v-if=“false”, 先进入页面，再修改为true，展示el-tabs会正常展示。

**Comment by geraldlrh** [comment]
这个 tabs 卡死的问题一直存在，没计划解决？网上一堆讨论帖：
https://segmentfault.com/q/1010000009857163
https://my.oschina.net/itence/blog/1538348

**Comment by Leopoldthecoder** [comment]
看了一下，以上链接包括这个 issue 都没有提供重现链接（重现链接不一定要用 jsfiddle 或者 codepen，可以是一个整理好的 GitHub 仓库）。关闭本 issue。

**Comment by guohuihot** [comment]
好奇怪，我发现一个页面用两个tabs，如果class相同就卡死

**Comment by HiZhaoxiaoyang** [comment]
ele么八十八亿傲娇啊，提个问题要填半天模板，然后就不回复也不改。

**Comment by HiZhaoxiaoyang** [comment]
没人调试源码找问题？
创建el-tab-pane组件时this.calcPaneInstances.bind(null, true))会初始话让强制刷新为true， 在vue实例的插槽中如果没有做重置插槽默认的操作，就会反复更新实例导致函数死循环
