### ISSUE TITLE
[Bug Report] el-input autofocus not working with SPA

### ISSUE THREAD

**Issue by darwinluague** [ElemeFE/element#7958]
### Element UI version
2.0.2

### OS/Browsers version
windows / Chrome 62.0.3202.75

### Vue version
2.5.2

### Reproduction Link
[http://jsfiddle.net/ds1p271e/1/](http://jsfiddle.net/ds1p271e/1/)

### Steps to reproduce
Navigate page using vue router

### What is Expected?
el-input autofocus should work when navigating page using vue router

### What is actually happening?
el-input autofocus not working when navigating page using vue router

**Comment by Leopoldthecoder** [comment]
`<el-input>` passes `autofocus` attribute directly to its inner native input element. If `autofocus` works in native inputs, it should work with `<el-input>` as well.

Unfortunately, your example wouldn't work with native inputs: https://jsfiddle.net/ds1p271e/2/ . So you need to find a way to make native inputs work, and apply that to `<el-input>`.

**Comment by darwinluague** [comment]
I figured it how to make it work using directives: http://jsfiddle.net/ds1p271e/4/

It would be nice if this will be included out of the box in the `autofocus` attribute of the `<el-input>` component.
