### ISSUE TITLE
[Question] How to set default value of select Component and Still be able to change its value from other option?

### ISSUE THREAD

**Issue by gkumar77** [ElemeFE/element#7961]
I have two select component, one for selecting layout and depending upon the value selected, I give different option in second select component.

```
 <el-form-item label="Page Layout">
   <el-select  v-model="form.Layout" @change="layoutChange()" placeholder="Please select Layout">
      <el-option
         v-for="item in form.layoutsOption"
         :key="item.value"
         :label="item.label"
         :value="item.value">
      </el-option>
   </el-select>
</el-form-item>

   <div v-for='(n,index) in partialsList'>
      <el-form-item :label="n ">
         <el-select v-model="form.parent_id[n]" placeholder="Please select " >
            <el-option  v-for="item in AllData[index]" 
               :key="item.value"
               :label="item.label"
               :value="item"
               :disabled="item.disabled">
            </el-option>
         </el-select>
      </el-form-item>
   </div>
```
Here : 
form.Layout is string,
form.layoutsOption is array getting data from JSON .
partialList is a array which contains multiple suboption to be selected in our selected Layout.
form.parent_id is used to store the selected value in array(Because there are multiple Suboption.
 AllData is a array which upon Layout selection sets its option .

Now, let me tell you the flow as how things happen.
![image](https://user-images.githubusercontent.com/26710557/32311045-76619cbc-bfbc-11e7-82db-36d0d5b4aa2a.png)

Step 1:
![image](https://user-images.githubusercontent.com/26710557/32310900-9d1ac082-bfbb-11e7-8db6-402218ea31da.png)
![image](https://user-images.githubusercontent.com/26710557/32310913-bb9cae26-bfbb-11e7-9fba-3fa27a037722.png)

Step 2:
![image](https://user-images.githubusercontent.com/26710557/32311137-e46f1f54-bfbc-11e7-947e-92fd53f803e1.png)

OR
![image](https://user-images.githubusercontent.com/26710557/32310964-094bc044-bfbc-11e7-8847-7d5b29659312.png)

Step 3:
![image](https://user-images.githubusercontent.com/26710557/32310984-190fd4b6-bfbc-11e7-9f1b-0f7c666efca5.png)

Finally,
![image](https://user-images.githubusercontent.com/26710557/32311100-afff124c-bfbc-11e7-9f0a-1b8d930ea047.png)

first a select component asking to select a layout. Then as soon as layout is selected , multiple sub select component appear and these are the option of that layout which are required for my further process.

So, my required is such that i need those sub option selection select component to have a inherit default value in every layout i select. If not default then the first option in that selection to be selected automatically.
Lets just say that i need default option to be selected implicitly. By which if user want default he will just save without having to select default again and aganin.

The way i did, doesnt allow them to change value, 
![image](https://user-images.githubusercontent.com/26710557/32311215-5617a57c-bfbd-11e7-970d-81306dc7e250.png)

they remain same even if a explicitly want to change the option.

P.S
A lengthy question, but i would appreciate the help, and tell me know if you are not able to understand the requirement of my question.
Thank you.

**Comment by gkumar77** [comment]
Oh com 'on man!!!
Help me out here.

**Comment by hunkriyaz** [comment]
anybody has any solution of this, instead of using `value-key`, can we do it?

**Comment by Sundered0** [comment]
> 
> 
> anybody has any solution of this, instead of using `value-key`, can we do it?

set option you need into value
