### ISSUE TITLE
[Bug Report] When the initial variable of the Select selector component is null, the unmatched data will be displayed at the bottom of the options list

### ISSUE THREAD

**Issue by Darkphooo** [ElemeFE/element#7962]
### Element UI version
2.0.2

### OS/Browsers version
Chrome 62.0.3202.62, Firefox Quantum 57.0b13

### Vue version
2.5.2

### Reproduction Link
[http://jsfiddle.net/darkphooo/sscyvnw4/1/](http://jsfiddle.net/darkphooo/sscyvnw4/1/)

### Steps to reproduce
将Select的属性filterable设置为true，再将Select绑定的变量初始值设为null

### What is Expected?
点击展开的选择器列表应该只有data中定义的选项

### What is actually happening?
点击展开选择器时，列表最下方会出现'无匹配数据'

**Comment by Leopoldthecoder** [comment]
Fixed in #7984
