### ISSUE TITLE
El-steps (direction= vertical), the last step max-width error

### ISSUE THREAD

**Issue by lcw2004** [ElemeFE/element#7963]
### Element UI version
2.0.2

### OS/Browsers version
Windows10 / Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/hzfpyvg6/72/](https://jsfiddle.net/hzfpyvg6/72/)

### Steps to reproduce
1. 代码如下：
```
    <el-steps direction="vertical" :active="1">
        <el-step title="步骤 1"></el-step>
        <el-step title="步骤 2"></el-step>
        <el-step title="步骤 3"></el-step>
        <el-step title="步骤 4"></el-step>
        <el-step title="步骤 5"></el-step>
        <el-step title="步骤 6"></el-step>
        <el-step title="步骤 7"></el-step>
        <el-step title="步骤 8"></el-step>
        <el-step title="步骤 9"></el-step>
        <el-step title="步骤 10"></el-step>
    </el-steps>
```

2. 官方的示例里面只有3步，因此显示正常。只需要多加几个步骤，最后一个步骤就会显示错误。
![image](https://user-images.githubusercontent.com/4246920/32311595-67de4f1a-bfd4-11e7-9043-1928eeae81d0.png)

### What is Expected?
渲染出来之后，最后一个el-step跟前面的el-step一样正常显示的。

### What is actually happening?
渲染出来之后，最后一个el-step的max-width: 属性的值为：100% / 10（即：10%），宽度不够导致"步骤 10"几个字显示出来是竖着显示的，前面的el-step是正常显示的。

**Comment by Leopoldthecoder** [comment]
Fixed in #7980
