### ISSUE TITLE
[Bug Report] element-ui.common.js send error message, a lot of actions will trigger

### ISSUE THREAD

**Issue by huanglei579** [ElemeFE/element#7970]
### Element UI version
1.4.7

### OS/Browsers version
mac OS /google

### Vue version
2.2.6

### Reproduction Link
[https://github.com/huanglei579](https://github.com/huanglei579)

### Steps to reproduce
every action

### What is Expected?
don't send error message 

### What is actually happening?
element-ui.common.js send Uncaught TypeError: Cannot read property 'disabled' of in project , a lot of actions will trigger

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

Hint: upgrade Vue to 2.5.2 might help.
