### ISSUE TITLE
[Bug Report] Select with multiple, filterable & default-first-option attributes, not showing drop-down options when press tab

### ISSUE THREAD

**Issue by kevinheyo** [ElemeFE/element#7972]
### Element UI version
2.0.2

### OS/Browsers version
Chrome 62

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/scb6s2y5/7/](https://jsfiddle.net/scb6s2y5/7/)

### Steps to reproduce
1. Make sure your screen cursor is put on the "Start Point"

2. Press "tab" button, and the cursor go to the "Multiple Select"

3. Keyin "op" to trigger the filter function, but the select drop-down forget to display

But if you use the mouse to click it, it's all fine!

### What is Expected?
After pressing tab button and key the keyword to filter the options, the select drop-down is disappeared.

### What is actually happening?
Work safe and sound!

**Comment by Leopoldthecoder** [comment]
Fixed in #7984
