### ISSUE TITLE
[Feature Request] Allow user to customise the text on the button in timePicker, DatePicker and DateTimePicker

### ISSUE THREAD

**Issue by mhyleomak** [ElemeFE/element#7974]
### Existing Component
Yes

### Component Name
timePicker, DatePicker and DateTimePicker

### Description
Sometimes I would like to use different words on the button, the only way I can achieve this is modify the DOM element using javaScript. 

So, I would like to request a new feature that provide user more freedom on customising these buttons, such as their text, display them or not, the event on the buttons, etc... 

Thanks!

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

Button texts are controlled by your i18n config, so you can add a new i18n config file to customize them.
