### ISSUE TITLE
[Bug Report] el-select through the code change selected value does not trigger the change event

### ISSUE THREAD

**Issue by Vurtne-hz** [ElemeFE/element#7975]
### Element UI version
2.0.2

### OS/Browsers version
Win10/Chrome59

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mwog3zj3/](https://jsfiddle.net/mwog3zj3/)

### Steps to reproduce
点击绑定按钮改变选中值，change事件不执行

### What is Expected?
点击按钮执行change

### What is actually happening?
未执行change，在1.4.9中是可以执行的

**Comment by wacky6** [comment]
This is intentional in 2.0. See changelog
