### ISSUE TITLE
[Bug Report] The 'menu-item' component used an 'el-tooltip' component which hasn't been registered correctly

### ISSUE THREAD

**Issue by InfiniteSword** [ElemeFE/element#7982]
### Element UI version
1.4.9

### OS/Browsers version
chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element/blob/88868eebf73f4ba7ada80e203789d3808fa05d01/packages/menu/src/menu-item.vue#L16-L24](https://github.com/ElemeFE/element/blob/88868eebf73f4ba7ada80e203789d3808fa05d01/packages/menu/src/menu-item.vue#L16-L24)

### Steps to reproduce
If I use the menu component only:
``` javascript
import {  Menu, MenuItem } from "element-ui";
Vue.component(Menu.name, Menu);
Vue.component(MenuItem.name, MenuItem);
```
I will get this error : Unknown custom element: <el-tooltip>

### What is Expected?
no errors or warns

### What is actually happening?
got an warn said: Unknown custom element: <el-tooltip> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by Leopoldthecoder** [comment]
Fixed in #7996
