### ISSUE TITLE
Remove [Bug Report] tree updateKeyChildren array method of component method leads to subscript out of range

### ISSUE THREAD

**Issue by zhangyaoFkr** [ElemeFE/element#7983]
### Element UI version
2.0.0-rc.1

### OS/Browsers version
win7 chrome63

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/myprojectisdevelopingcantsupporttoreappearfornowthankyou/](https://jsfiddle.net/myprojectisdevelopingcantsupporttoreappearfornowthankyou/)

### Steps to reproduce
tree组件updateKeyChildren方法
在数组中使用remove方法 数组长度减少 但是下标一直增加 最后当下标大于数组长度时 产生越界错误
看一下代码就知道了 element-ui.common.js  line:19676-19688
  TreeStore.prototype.updateChildren = function updateChildren(key, data) {
    var node = this.nodesMap[key];
    if (!node) return;
    var childNodes = node.childNodes;
    for (var i = 0, j = childNodes.length; i < j; i  ) {
      var child = childNodes[i];
      this.remove(child.data);
    }
    for (var _i = 0, _j = data.length; _i < _j; _i  ) {
      var _child = data[_i];
      this.append(_child, node.data);
    }
  };

### What is Expected?
updateKeyChildren方法可以根据key正确的更新子节点

### What is actually happening?
updateKeyChildren方法报错

**Comment by Leopoldthecoder** [comment]
Fixed in 2.0.4
