### ISSUE TITLE
[Feature Request] Pagination page input, real-time event current-change?

### ISSUE THREAD

**Issue by db-murphy** [ElemeFE/element#7986]
### Existing Component
是

### Component Name
Pagination

### Description
Pagination页码输入时，会实时触发current-change事件，每change一次就会触发一次，这样会造成接口频繁调用，我记得上一个版本的element-ui是在用户在触发blur的时候才会触发current-change，有什么办法解决这个问题么？

**Comment by Leopoldthecoder** [comment]
This is unintentional. Fixed in https://github.com/ElemeFE/element/pull/7995/commits/44991d598345c2e21f926e09c48b8a559f8dd7a5

**Comment by db-murphy** [comment]
@Leopoldthecoder  再问个问题，我现在在开发过程中需要用到element-ui，但这个bug修复还没有更新到npm，我需要怎么解决这个问题？把项目element down下来，自己build一个js，替换掉node_modules里的js？

**Comment by Leopoldthecoder** [comment]
可以这样处理。等我们发布后再替换回来。

**Comment by db-murphy** [comment]
@Leopoldthecoder  你们下一个版本大概什么时候发布？

**Comment by db-murphy** [comment]
@Leopoldthecoder  额  貌似这个问题已经更新到最新版本了，但发现有问题，还不能这么改，貌似Pagination组件里的这个页码输入框用的是ElInput，这样修改change事件，会导致所有用到ElInput的地方都变成了blur的时候才触发change

**Comment by db-murphy** [comment]
@Leopoldthecoder  建议加一个配置项

**Comment by Leopoldthecoder** [comment]
2.0 里 Input 的 change 事件已经修改为和原生行为一致，请参考非兼容性更新。
