### ISSUE TITLE
[Bug Report] el-slider knob does not work on iOS

### ISSUE THREAD

**Issue by yene** [ElemeFE/element#7988]
### Element UI version
2.0.2

### OS/Browsers version
Safari on iOS

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/2034p35n/](https://jsfiddle.net/2034p35n/)

### Steps to reproduce
* Open page with el-slider component on iPad or iPhone
* Start dragging the el-slider knob

### What is Expected?
Slider knob should signal that it was pressed, and the user should be able to drag it around.

For reference it works with the native HTML5 input range.

### What is actually happening?
Nothing, unable to drag knob on iPhone or iPad.

It works on desktop.

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop. Please avoid using it on mobile devices.
