### ISSUE TITLE
[Bug Report] ELDialog layout broken on scrolling in 2.0.2

### ISSUE THREAD

**Issue by yorkane** [ElemeFE/element#7989]
### Element UI version
2.0.2

### OS/Browsers version
Win10/Chromium53.0.2785.104 (QQ browser) | (Chrome 61.0.3163.91 is OK)

### Vue version
2.5.2

### Steps to reproduce
Create a ELDialog, Place multiple components, and make it too high to scroll. 
Add an ElSWitch or ElSelect component
Open the dialog
change the switch or  select component
Scroll to end

![20171102223621](https://user-images.githubusercontent.com/11476816/32332246-f4d54950-c01f-11e7-8f8b-e4903f053202.jpg)

### What is Expected?
Layout remain unchanged

### What is actually happening?
Broken

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
