### ISSUE TITLE
[Bug Report] Tooltip not shown for disabled buttons

### ISSUE THREAD

**Issue by Addvilz** [ElemeFE/element#7990]
### Element UI version
2.0.0-rc.1

### OS/Browsers version
Chrome latest

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/688/](https://jsfiddle.net/pj71jkyw/688/)

### Steps to reproduce
1. Wrap a button in tooltip.
2. Disable button with :disabled

### What is Expected?
Tooltip is shown on hover

### What is actually happening?
Tooltip is not shown on hover

**Comment by Leopoldthecoder** [comment]
Disabled form elements are not supported for Tooltip, more information can be found at [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter). You need to wrap the disabled form element with a container element for Tooltip to work.
