### ISSUE TITLE
safari下table标题栏的class="gutter"宽度bug

### ISSUE THREAD

**Issue by TDiDa** [ElemeFE/element#80]
``
    <th class="gutter" style="width: 0px;"></th>
``

![image](https://cloud.githubusercontent.com/assets/18672870/18620844/161a554e-7e4d-11e6-83d8-9357b35d24af.png)

**Comment by cismous** [comment]
这个问题修复了吗，官方的demo样式，在safari还是出现了这个问题 @QingWei-Li
