### ISSUE TITLE
[Feature Request] Can not listen form onsubmit event?

### ISSUE THREAD

**Issue by medz** [ElemeFE/element#8000]
### Existing Component
Yes

### Component Name
el-form

### Description
I encountered a problem using the el-form build build form, when the user input is completed press Enter, automatically submitted. The I want to try to intercept this behavior, I try to monitor the onsubmit form event, but failed, and I did not find the amount from the document description.

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/32359961-933b62e8-c08c-11e7-8795-a7cc69883179.png)

https://github.com/ElemeFE/element/blob/dev/FAQ.md

**Comment by medz** [comment]
😅

**Comment by medz** [comment]
@Leopoldthecoder Thanks.
