### ISSUE TITLE
[Bug Report] Why datepicker popup shown on left top of screen

### ISSUE THREAD

**Issue by h4wldev** [ElemeFE/element#8004]
### Element UI version
2.0.2

### OS/Browsers version
Mac OS / Chrome 61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/694/](https://jsfiddle.net/pj71jkyw/694/)

### Steps to reproduce
1. Click Datepicker(daterange) and select dates
2. Click 'Change' button
3. Click Datepicker(week)
4. Datepicker popup shown on left top of screen

### What is Expected?
Popup must be shown below input area. even if its parent element change.

### What is actually happening?
Datepicker popup shown on left top of screen, when change datepicker parent element. is it error? or my fault?

**Comment by lincenying** [comment]
<el-date-picker type="daterange" :key="1" />
<el-date-picker type="week" :key="2" />

add key

**Comment by h4wldev** [comment]
@lincenying Thx. can you tell me any idea for this image popup shown center of input?
![image](https://user-images.githubusercontent.com/14465407/32362497-31ec9a54-c0ad-11e7-9bc5-14b5e89d82cc.png)

**Comment by h4wldev** [comment]
@lincenying Nevermind, it problem shown because chrome dev tool. Thx your favor
