### ISSUE TITLE
[Feature Request] I want to add more than one Summary row

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#8007]
### Existing Component
是

### Component Name
el-table

### Description
I have a demand that requires two lines of total, one row is all data summary, and one row is the checked data summary. now the component has only one Summary row.

**Comment by ForeverCSY** [comment]
请问你有解决这个问题吗，我这边也需求2行的合计

**Comment by zsedcbm** [comment]
@ForeverCSY  这个问题其实很简单, table插件里面提供了一个 append的slot,你用那个作合计的就可以了

**Comment by ForeverCSY** [comment]
用append也可以做到像合计一样的每列一一对应吗？

**Comment by zsedcbm** [comment]
@ForeverCSY 我又试了一下,1.4.8版本的append是直接追加到当前内容table里面的,所以直接tr可以,但是2.0版本的element 是后追加的一个div,暂时没法搞到一一对应.
https://jsfiddle.net/zpm7gL0g/

**Comment by ForeverCSY** [comment]
@zsedcbm 2.0版本，我append进去一个新的table，然后让body隐藏，header里面放合计的内容，可以做到一一对应，不过宽度得写死

**Comment by zsedcbm** [comment]
@ForeverCSY  那就简单粗暴点,使用jquery 直接修改dom
https://jsfiddle.net/oksL2401/1/
