### ISSUE TITLE
Select 重置後再選定無效

### ISSUE THREAD

**Issue by Nununene** [ElemeFE/element#801]
```
// Vue (pug)
      el-select(
        v-model='formData.to',
        placeholder='placeholder 1'
      )
        el-option(:label='item.value', :value='item.value', v-for='item in detailArray')

// Code
  data() {
    return {
      formData: {
        from: '',
        to: '',
      },
    }
  },
  methods: {
    resetFormData() {
      this.formData = {};
    },
  }
```

### ElementUI version
1.0.0-rc.8

### OS/Browers version
Windows Firefox developer edition

### Vue version
2.0.3

### Steps to reproduce
先隨意選一個選項，然後執行 resetFormData() 之後
第一次select雖可以重置，但之後再選都無法使用
點選時 this.formData 並不會變動
其後使用 resetFormData() 也無法再對其重置
PS: select再點選時 this.formData之值(formData.to) 也不會變動

另外測試
如果情況如下
```
data() {
  return {
    stringOne = '';
  }
}
```
el-select的v-model是設定像這樣
`v-model='stringOne'`
而 reset 時是像這樣
`this.stringOne = '';`
會正常!

### What is Expected?
直接 formData = {} 之後也可以正常運作

### What is actually happening?
formData = {} 之後不正常

**Comment by aguegu** [comment]
同在坑中

**Comment by Leopoldthecoder** [comment]
两位请看这个例子：https://jsfiddle.net/leopoldthecuber/kat5ptky/ ，先在输入框中输入一段字符，可以看到 `formData.to` 的更新，然后点击 reset 按钮，再在输入框中输入时，`formData.to` 也不再变化了。

这个例子没有使用 Element，因此是和 Vue 的数据绑定机制有关。正确的 `resetFormData` 应该是
```javascript
  resetFormData() {
    this.formData = {
      from: '',
      to: ''
    };
  }
```

**Comment by aguegu** [comment]
@Leopoldthecoder 这个例子说明不了什么问题，我们说的是<el-select>啊

**Comment by baiyaaaaa** [comment]
@Nununene 如果你是这么重置的话需要这么写
resetFormData() {
      this.formData = {
          to: ''
     };
 },

**Comment by aiqin-bao** [comment]
解决了吗？？？
