### ISSUE TITLE
Uncaught [ModJS] Cannot find module `element-ui/lib/theme-default/index.css`

### ISSUE THREAD

**Issue by swanghao** [ElemeFE/element#8016]
请教下我项目原先用的是1点几的低版本现在更新到2.0版本报这个错误是怎么回事呢？

**Comment by chang0022** [comment]
![image](https://user-images.githubusercontent.com/6067222/33472185-0e195238-d6ac-11e7-8e86-631a439800fa.png)
@swanghao 2.0版本换了 `theme-chalk` 不是 `theme-default`
