### ISSUE TITLE
[Bug Report] date assignment error

### ISSUE THREAD

**Issue by haoshuaiya** [ElemeFE/element#8017]
### Element UI version
1.4.9

### OS/Browsers version
windows 10

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/tduyr6d1/1/](https://jsfiddle.net/tduyr6d1/1/)

### Steps to reproduce
选择一个日期

### What is Expected?
选中日期，得到正确的日期值

### What is actually happening?
选中日期后得到的值是错误的，会比当前日期滞后一天

**Comment by Leopoldthecoder** [comment]
没有错误，得到的值是 Date 对象：https://jsfiddle.net/tduyr6d1/2/

建议阅读 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
