### ISSUE TITLE
Set the default-active [Bug Report] encountered a bug navigation menu

### ISSUE THREAD

**Issue by Angelsindevil** [ElemeFE/element#8019]
### Element UI version
2.0.3

### OS/Browsers version
10.12.6

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/zhengxiaowen/pen/MOKZaN](https://codepen.io/zhengxiaowen/pen/MOKZaN)

### Steps to reproduce
在我给出的demo中，页面刷新，展开导航菜单项2，此时再在下拉框中选中之前的默认值，此时不会展开菜单项1。选中其他值时，选中和展开情况正常。
（补充说明：导航菜单 当有设置属性default-active（例：1-1 菜单项第一组第一个数据），页面首次加载时。任意展开其他菜单项组，再重新设置default-active为初始值，此时不会展开菜单项第一组。设置为其他值展开与选中情况正常。）

### What is Expected?
此时再在下拉框中选中之前的默认值，此时应该也能展开菜单项1

### What is actually happening?
此时再在下拉框中选中之前的默认值，此时不能展开菜单项1

**Comment by Leopoldthecoder** [comment]
凡是 `default-` 开头的 API，均为「默认」的含义，仅在组件首次加载时生效。

**Comment by Angelsindevil** [comment]
@Leopoldthecoder 谢谢～
