### ISSUE TITLE
[Bug Report] Error date-picker validation and select validation after reset form.

### ISSUE THREAD

**Issue by dingyi1993** [ElemeFE/element#8026]
### Element UI version
2.0.3

### OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/dingyi1993/v7cnokfo/2/](https://jsfiddle.net/dingyi1993/v7cnokfo/2/)

### Steps to reproduce
1. click the activity date input field and blur without choosing.
2. click the reset button.
3. choose a activity region.
4. repeat step 1.
5. repeat step 1 again.

### What is Expected?
after step 1: the activity date input field's validation status should not have any change.(because of the trigger: 'change' configuration)
after step 3: the activity region selection should be valid(green border).
after step 5: the same as after step 1.

### What is actually happening?
after step 1: the activity date input field is invalid.
after step 3: the activity region selection's validation status didn't have any change.
after step 5: the same as after step 1.

**Comment by Maksimenka** [comment]
Same problem. Need hotfix.
