### ISSUE TITLE
[Bug Report] Elements resize issue

### ISSUE THREAD

**Issue by oleynikd** [ElemeFE/element#8039]
### Element UI version
2.0.3

### OS/Browsers version
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/dkqqc6sp/](https://jsfiddle.net/dkqqc6sp/)

### Steps to reproduce
Try to increase the width of the window. Inner container resize as desired.
Try to decrease the width of the window. Inner container does not resize.

### What is Expected?
Normal resizing both ways

### What is actually happening?
Resizes only when increasing width but stops resizing when decreasing

**Comment by oleynikd** [comment]
Sorry, new link:
https://jsfiddle.net/dkqqc6sp/

**Comment by oleynikd** [comment]
OK, this is happening because an initial setting on flex items is `min-width: auto`. Setting `min-width: 0` for `.el-container` fixes this issue.

**Comment by Leopoldthecoder** [comment]
Fixed in #8042
