### ISSUE TITLE
[Bug Report] 复合型输入框下按下tab键无法选择下一输入框问题（需点击两次）

### ISSUE THREAD

**Issue by heimuya** [ElemeFE/element#8040]
Element UI version

2.0.1

OS/Browsers version

macOS Sierra 10.12.3／Chrome 版本 57.0.2987.133 (64-bit)

Vue version

2.5.2

Steps to reproduce

1.选择多个复合型输入框组件（可用prepend slot），构建一个form表单
2.在前一个输入框下按下Tab键

What is Expected?

下一个复合型输入框组件可以通过按下Tab键获得焦点

What is actually happening?

按下Tab键后，下一个组件的prepend前置内容获得焦点，但是input输入框需要点击第二下才能获取焦点。

possible reason?

复合型输入框的前置或者后置内容div块添加了“tabindex”属性，可能导致首次tab键操作聚焦在前置或后置内容上。

**Comment by Liuhuifeng** [comment]
这个issue为什么关闭？有解决吗？

复合型Input中非表单元素的prepend, appened确实影响了Tab键切换焦点。
