### ISSUE TITLE
The upper level node of [Bug Report] tree component selects all the underlying nodes by default

### ISSUE THREAD

**Issue by merlin95X** [ElemeFE/element#8044]
### Element UI version
1.4.9 & 1.3.7

### OS/Browsers version
win 7&chrome 59

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/f2trponc/](https://jsfiddle.net/f2trponc/)

### Steps to reproduce
https://jsfiddle.net/wc1ys3s4/     (没问题的版本，1.3.7；2.0.x版本没有这个问题)   
https://jsfiddle.net/f2trponc/        (有问题的版本，1.4.9；1.2.x版本也有这个问题)

### What is Expected?
在加入check-strictly后首先选中上级节点后点击展开下层节点（这里是根节点），下层节点展开后应该为未选中状态

### What is actually happening?
为选中状态，不管传回的数据什么样都是全部下层节点被选中。

**Comment by Leopoldthecoder** [comment]
由于涉及到一个比较底层的改动，修复的话会引入一些非兼容性更新，所以不好将改动合并到 1.x 版本中。

如果对这个问题比较介意的话，建议升级至 2.0 版。

**Comment by merlin95X** [comment]
好的，现在先用1.3版本，等公司同步2.0.x版本
