### ISSUE TITLE
[Bug Report] The 'size' of checkbox is not work when nested in a form.

### ISSUE THREAD

**Issue by DarcyAnn** [ElemeFE/element#8054]
### Element UI version
2.0.3

### OS/Browsers version
Any

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/DarcyAn/ymdfej4x/](https://jsfiddle.net/DarcyAn/ymdfej4x/)

### Steps to reproduce
See the reproduction link:
When a checkbox is nested in a form like my example, the size is not work.

### What is Expected?
The size is work.

### What is actually happening?
The size is not work.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8100/commits/2fccc30f0402ec0ceb8886f07bc0092921bb92a1
