### ISSUE TITLE
[Feature Request] Table `sortable` support `sort-ignorecase`

### ISSUE THREAD

**Issue by wangfengming** [ElemeFE/element#8055]
### Existing Component
Yes

### Component Name
Table

### Description
It would be great if support `sort-ignorecase`. If ok, i can create a pr. :-)

**Comment by liril-net** [comment]
You can use `sort-method` for a common usage

**Comment by wangfengming** [comment]
@liril-net 

This is true.
I can use `sort-method`,
```javascript
sortMethod(a, b) {
  a = a.toLowerCase()
  b = b.toLowerCase()
  if (a < b) return -1
  if (a > b) return 1
  return 0
}
```
or I can use `sort-by`.
```javascript
sortBy(item) {
  return item.name.toLowerCase()
}
```
But it would be much convenient if I can use `sort-ignorecase`.

Anyway, thank you for your quick reply.
