### ISSUE TITLE
[Bug Report] Date picker is not showing at all, and has console errors

### ISSUE THREAD

**Issue by tanhernandez** [ElemeFE/element#8057]
### Element UI version
2.0.3

### OS/Browsers version
Google Chrome

### Vue version
2.5.3

### Reproduction Link
[ https://jsfiddle.net/pj71jkyw/]( https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Use vue 2.5.3 with vue-template-compiler 2.5.3, and then use Element UI 2.0.3

### What is Expected?
Should show the date picker popup

### What is actually happening?
Date picker popup is not showing, and prints the following errors in the console

1.) TypeError: Cannot read property 'replace' of undefined

2.) [Vue warn]: Error in callback for watcher "pickerVisible": "HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method."

3.) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

---

I have noticed that the error is not happening in Element UI 2.0.2 (because I reverted back and I had no issues). The problem occurs only in 2.0.3

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
