### ISSUE TITLE
select 的change事件参数可否增加变化之前的值？

### ISSUE THREAD

**Issue by Noemi-** [ElemeFE/element#806]

**Comment by Leopoldthecoder** [comment]
具体场景是什么？感觉可以通过 `watch` 绑定的变量来实现

**Comment by Noemi-** [comment]
@Leopoldthecoder 场景是判断是不是第一次初始化，第一次的话有一些操作可以省略～

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/xxdej1jp/
这个 demo 模拟了异步初始化的情况，可以通过 watch 来实现
