### ISSUE TITLE
[Bug Report] The el-form rules has changed when switching routes

### ISSUE THREAD

**Issue by yoyo837** [ElemeFE/element#8060]
### Element UI version
2.0.3

### OS/Browsers version
Win 10 latest 64bit / Chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://github.com/yoyo837/elform-rules-ssr.git](https://github.com/yoyo837/elform-rules-ssr.git)

branch: element-ui-2.x

### Steps to reproduce
Step：
1.open a page/route A.
2.`router.push` another page/route B. `el-form` in B with `rules`
3.Form validation automatically triggered. when I debug it, it was found that the watch's(el-form) rules in triggered

1.打开一个页面
2.从此页面路由到另一个含有表单的页面
3.表单页面默认会验证一次，>>>**从el-form中的watch rules里触发**.<<<

不知道是否与ssr有关，但是直接刷新表单页面并不会发生这种情况。
（Translate from Google）

### What is Expected?
Forms are not verified by default when coming from one route to another.
进入页面表单默认不执行验证

### What is actually happening?
Forms are verified by default when coming from one route to another
路由过来的页面表单直接自动执行验证了，从el-form中的watch rules里触发.

**Comment by yoyo837** [comment]
1.4.x before upgrading 2.x has the same problem.
升级2.x之前的1.4.x也有相同的情况。

**Comment by badpunman** [comment]
https://github.com/ElemeFE/element/pull/8141

I came accross the same issue through another means. Pull request adds a parameter to disable the watcher.

**Comment by yoyo837** [comment]
Using the Quick Start demo(vue init), the same problem does not occur in non-SSR cases, both hash mode and history mode.

我使用vue init 创建的默认项目使用element-ui制作一个含表单验证的新页面，从helloword页面链接(route-link)过去，不会自动触发一次验证.

**Comment by yoyo837** [comment]
Emergency solution: https://github.com/ElemeFE/element/issues/3240#issuecomment-284315608
