### ISSUE TITLE
[Bug Report] adjusts the form of the fixed column

### ISSUE THREAD

**Issue by scq000** [ElemeFE/element#8061]
### Element UI version
2.0.3

### OS/Browsers version
mac/chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
固定列的时候，调整最后一列的列宽。拖动最后一列的右侧线。

### What is Expected?
禁止调整列宽的时候，最后一列的右侧线可拖动

### What is actually happening?
固定列的时候，调整最后一列的列宽。会产生意想不到的效果。

**Comment by scq000** [comment]
![image](https://user-images.githubusercontent.com/12999391/32435438-e2e8268c-c31b-11e7-91a0-a761591f2bbf.png)

**Comment by furybean** [comment]
@scq000 没看懂这个 issue，请确认是否与 #8158 是同一个问题。
