### ISSUE TITLE
[Bug Report] Customize font location

### ISSUE THREAD

**Issue by nWidart** [ElemeFE/element#8062]
### Element UI version
2.0.3

### OS/Browsers version
Mac/Chrome 61

### Vue version
2.5.3

### Steps to reproduce
Require fonts outside of root `/fonts/` directory

### What is Expected?
Ability to require fonts at a different location

### What is actually happening?
Is it possible to require fonts from a different location?

The fonts are loaded from 
```
/fonts/vendor/element-ui/lib/theme-chalk/element-icons.woff?9b70ee41d12a1cf127400d23534f7efc 
```

However in my current project they live in 
```
/content/themes/projectname/fonts/vendor/element-ui/lib/theme-chalk/element-icons.woff?9b70ee41d12a1cf127400d23534f7efc
```

Is it possible to customize this setting?

Thanks

**Comment by Leopoldthecoder** [comment]
`$--font-path` is a SCSS variable, so you can customize it. http://element-cn.eleme.io/2.0/#/en-US/component/custom-theme#update-scss-variables-in-your-project

**Comment by nWidart** [comment]
Hello,

I tried changing that scss variable yes, but it does not change where element-ui loads the fonts.

**Comment by Leopoldthecoder** [comment]
I tested this again and it worked. Have you tried to customize other variables and see if they work? If not, it's likely that your variable file is not correctly configured.

**Comment by nWidart** [comment]
Hello,

It was my mistake, I had the font path overwritten, but I was still including the compiled css. By of course, including the sass, it worked as expected

``` css
$--font-path: '/content/themes/projectname/dist/fonts/vendor/element-ui/lib/theme-chalk/';

@import "~element-ui/packages/theme-chalk/src/index";
```

Sorry for the trouble.

Thanks!

**Comment by Adham2023** [comment]
> 

It does not work for me, please help me on this regard.
