### ISSUE TITLE
[Bug Report] 在TypeScript2.6.1中无法以import { xxx } from "element-ui"方式按需引入

### ISSUE THREAD

**Issue by StingGao** [ElemeFE/element#8068]
### Element UI version
2.0.3

### OS/Browsers version
macOS / Chrome / TypeScript 2.6.1

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
TypeScript (2.6.1) 中以import { xxx } from "element-ui"方式按需引入，提示Module '"/element-ui/types/index"' has no exported member 'xxx'.

### What is Expected?
期望增强ElementUI对于ts的兼容性。

### What is actually happening?
目前仅能通过// @ts-ignore方式屏蔽ts错误提示

**Comment by Leopoldthecoder** [comment]
@hjkcai Could you take a look at this?

**Comment by hjkcai** [comment]
element-ui默认是用了打包好的版本，通过这种语法也是没办法按需引入的😂这个怕是没办法…除非手动引入src里面的东西，这个方法也是可与的

**Comment by StingGao** [comment]
@hjkcai 好吧😂 之前不用ts的时候习惯用import解构结合babel的插件按需引入，不过现在不用修改只是添加一个// @ts-ignore屏蔽错误抛出 也是没毛病。

**Comment by hjkcai** [comment]
@StingGao 等下一次release吧😂应该能彻底解决这个问题了，不用加 `@ts-ignore` 也行

**Comment by hjkcai** [comment]
@StingGao 找到按需引入方法了。首先按照普通 js 的按需引入方法去配置 babel，然后在 tsconfig.json 里面的 `compilerOptions` 里加一个 `"module": "es2015"` 或者 `"module": "esnext"` 的选项。记得在 webpack 里面配好 loader，让 ts 文件有经过 babel-loader 处理一次。

先这样试试，不行的话把 `webpack.base.conf.js` 内容贴上来

@Leopoldthecoder 感觉要在教程里面加入 ts 相关的教程才行😂我明天出个 PR 解决一下这个 issue 提出的问题吧

**Comment by hjkcai** [comment]
@shhdgit 不同的 `element-ui` 版本是会有不同的，你看看 `node_modules/element-ui/lib` 下是不是真的有 `theme-chalk` 的文件夹。如果没有，看看是不是有 `theme-default` 文件夹，有的话，在 `.babelrc` 里面把 `styleLibraryName` 改成 `theme-default`

如果还是不行

1. 贴上 `index.ts` 的代码
2. 贴上 `element-ui` 的版本
3. 通过 npm 安装 `raw-loader`，在 `src` 里新建一个 `test.js`，把 webpack 的 entry 改成 `test.js`，运行后贴上控制台的输出

`test.js` 内容：

```javascript
/* eslint-disable */
console.log(require('raw-loader!./index.ts'))
```

**Comment by shhdgit** [comment]
@hjkcai theme-chalk是有的

1.index.ts
```js
 // @ts-ignore
import { Button } from 'element-ui'
import Vue from 'vue'

import App from '@/App.vue'
import router from '@/router'
import httpPlugin from '@/service/httpPlugin'
import vuexStore from '@/store'

import './assets/icons/iconfont.js'
import './assets/styles/functional.styl'
import './assets/styles/reset.styl'

Vue.use(httpPlugin)
Vue.use(Button)

const app = new Vue({
  render: h => h(App),
  router,
  store: vuexStore,
})

document.addEventListener('DOMContentLoaded', () => {
  app.$mount('#app')
})

// service worker
// if (window.location.protocol === 'https:' && navigator.serviceWorker) {
//   navigator.serviceWorker.register('/service-worker.js')
// }

```

2.package.json
```json
"dependencies": {
    "axios": "^0.17.0",
    "element-ui": "^2.0.4",
    "vue": "^2.5.3",
    "vue-class-component": "^6.1.0",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  }
```

3.控制台的输出：
```
import _default3 from 'element-ui/lib/theme-chalk/button.css';
import _default2 from 'element-ui/lib/theme-chalk/base.css';
import _default from 'element-ui/lib/button';

import Vue from 'vue'; // @ts-ignore

import App from '@/App.vue';
import router from '@/router';
import httpPlugin from '@/service/httpPlugin';
import vuexStore from '@/store';
import './assets/icons/iconfont.js';
import './assets/styles/functional.styl';
import './assets/styles/reset.styl';
Vue.use(httpPlugin);
Vue.use(_default);
var app = new Vue({
    render: function render(h) {
        return h(App);
    },
    router: router,
    store: vuexStore
});
document.addEventListener('DOMContentLoaded', function () {
    app.$mount('#app');
});
// service worker
// if (window.location.protocol === 'https:' && navigator.serviceWorker) {
//   navigator.serviceWorker.register('/service-worker.js')
// }
```

**Comment by hjkcai** [comment]
@shhdgit 看起来并没有什么错…这就很神奇了，再确定一下 `node_modules/element-ui/lib/theme-chalk` 里面有没有 `button.css` 和 `base.css`，webpack配置里面有没有把 `element-ui` 解析成别的东西，还可以把 `node_modules` 删了重新安装试试…

这个已经跟 TypeScript 没关系了，是 webpack 模块解析那里的问题

**Comment by shhdgit** [comment]
@hjkcai 搞定了，多加了一层stylus-loader崩了，具体原因还不太清楚。正常css多被stylus-loader处理一波应该是没问题的呀...
十分感谢提供思路！ts+vue终于整完了，真是长须一口气😂老哥有什么合适交流的平台吗

**Comment by njleonzhang** [comment]
求ts的配置文档。

**Comment by shihua-guo** [comment]
在1.4.12版本中是否支持tc，按需引入呢？我更新了1.4.12，仍然无法按需引入。

**Comment by aristotll** [comment]
感觉这个问题还是没解决 同最新版本了 用的是 ts2.7(对就那个号称兼容 esModule default 的那个版本
`import { ElAlert } from "element-ui";`
Error:
> Error:(9, 10) TS2305: Module '"/node_modules/element-ui/types/index"' has no exported member 'ElAlert'.

**Comment by Dragon-Rider** [comment]
我用的最新的typescript 3.6.2解决了问题
