### ISSUE TITLE
多个form存在一个页面，共用一个校验规则的时候 that.$refs.demoForm只会识别最后一个 ？

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#807]
### ElementUI version

rc.8
### Vue version

2.0.3
### Steps to reproduce

所有表单都公用一个rules  
并且表单平行存在，不互相包含

对 blur或者是change的时候 都能起到校验作用

就是在我们 sumbit的时候 that.$refs.demoForm 回调的过程 只会识别 最后一个 前面的都不会检查检验了

求解决方案（form表单的布局不想改变了，中间相差一万个div）

**Comment by Leopoldthecoder** [comment]
这些 Form 都指定了同一个 `ref="demoForm"`？

**Comment by baiyaaaaa** [comment]
所有的 form 都公用一个rules理论上是没问题的，能否再清晰描述一下问题？

**Comment by spademan** [comment]
@Leopoldthecoder @baiyaaaaa 是的 同一个ref 也同一个rules

**Comment by Leopoldthecoder** [comment]
如果不是用 `v-for` 渲染出来的话，多个元素是不能共用同一个 `ref` 的。需要给不同的 form 分别设定不同的 `ref`。

**Comment by spademan** [comment]
为什么v-for可以呢？（没测试不知道是不是真的可以，在v-for中）

**Comment by yoyo837** [comment]
@spademan v-for出来的this.$refs['demoForm']会是一个数组
