### ISSUE TITLE
[Bug Report] Auto-check for default value of Element Table Multiple select not working.

### ISSUE THREAD

**Issue by ragamuffinguil** [ElemeFE/element#8071]
### Element UI version
2.0.3

### OS/Browsers version
Google Chrome Latest

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/66s1rLpq/](https://jsfiddle.net/66s1rLpq/)

### Steps to reproduce
Default data of mutipleselection must be auto check in the table also

### What is Expected?
first data of the table must be selected

### What is actually happening?
autocheck is not happening

**Comment by Leopoldthecoder** [comment]
Table itself doesn't know the existence of `multipleSelection` (there is nowhere to pass `multipleSelection` to `<el-table>`). So to init Table's checkboxes, you can simply execute `toggleRowSelection` when it's loaded.
