### ISSUE TITLE
Spanish documentation

### ISSUE THREAD

**Issue by Leopoldthecoder** [ElemeFE/element#8074]
Recently we have been exchanging ideas with a Spanish developer (@Gonzalo2310) about translating Element docs into Spanish. As Element 2.0 is finally released, we are now ready for Spanish docs.

Since no one in our team speaks Spanish, we'll need the community's help. As of today, if you are interested in the idea and confident of your Spanish, you can contribute to the newly created `es-doc` branch: https://github.com/ElemeFE/element/tree/es-doc/examples .

The workflow is:
- Check the todo list below
- Claim one or more files by leaving a comment, then I'll move the file(s) to the working-in-progress category
- Send a PR to the `es-doc` branch, and I'll move the file(s) to the finished category after the PR is merged

## 

### Todo

Cleared!

##

### Working in Progress

Cleared!

##

### Finished

- [alert](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/alert.md)
- [badge](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/badge.md)
- [breadcrumb](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/breadcrumb.md)
- [button](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/button.md)
- [card](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/card.md)
- [carousel](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/carousel.md)
- [color](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/color.md)
- [checkbox](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/checkbox.md)
- [collapse](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/collapse.md)
- [color-picker](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/color-picker.md)
- [container](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/container.md)
- [custom-theme](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/custom-theme.md)
- [switch](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/switch.md)
- [upload](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/upload.md)
- [installation](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/installation.md)
- [layout](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/layout.md)
- [menu](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/menu.md)
- [loading](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/loading.md)
- [quickstart](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/quickstart.md)
- [radio](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/radio.md)
- [rate](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/rate.md)
- [message-box](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/message-box.md)
- [message](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/message.md)
- [tabs](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/tabs.md)
- [time-picker](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/time-picker.md)
- [tooltip](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/tooltip.md)
- [table](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/table.md)
- [transfer](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/transfer.md)
- [transition](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/transition.md)
- [tree](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/tree.md)
- [component](https://github.com/ElemeFE/element/blob/es-doc/examples/i18n/component.json)
- [title](https://github.com/ElemeFE/element/blob/es-doc/examples/i18n/title.json)
- [page](https://github.com/ElemeFE/element/blob/es-doc/examples/i18n/page.json)
- [cascader](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/cascader.md)
- [dropdown](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/dropdown.md)
- [form](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/form.md)
- [i18n](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/i18n.md)
- [icon](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/icon.md)
- [input-number](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/input-number.md)
- [input](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/input.md)
- [select](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/select.md)
- [slider](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/slider.md)
- [steps](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/steps.md)
- [pagination](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/pagination.md)
- [popover](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/popover.md)
- [progress](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/progress.md)
- [date-picker](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/date-picker.md)
- [datetime-picker](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/datetime-picker.md)
- [dialog](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/dialog.md)
- [notification](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/notification.md)
- [tag](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/tag.md)
- [typography](https://github.com/ElemeFE/element/blob/es-doc/examples/docs/es/typography.md)

##

Discussions should be focused on Spanish docs. Off-topic comments will be deleted.

**Comment by SantiagoGdaR** [comment]
I'm ready to take the first 5 [alert, badge, breadcrumb, and button]

**Comment by Gonzalo2310** [comment]
Then I'll proceed to the next 3. [card, carousel and cascader]

**Comment by fedegar33** [comment]
I´ll take the next 3 (checkbox, collapse and color-picker)

**Comment by coderdiaz** [comment]
I'll take the next 3 (color, container, custom-theme)

**Comment by carmencitaqiu** [comment]
I'll take the next 3(date-picker,datetime-picker,dialog)

**Comment by Leopoldthecoder** [comment]
@SantiagoGdaR @Gonzalo2310 @fedegar33 @coderdiaz @carmencitaqiu Thanks.

**Comment by Gonzalo2310** [comment]
next 3 (dropdown, form, i18n)

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 Moved to WIP.

**Comment by coderdiaz** [comment]
next 3 (upload, table, loading)

**Comment by Gonzalo2310** [comment]
next 3 (icon input-number input)

**Comment by Leopoldthecoder** [comment]
Upload, Table, Loading, Icon, InputNumber and Input are moved to WIP.

**Comment by Gonzalo2310** [comment]
cascader, dropdown, i18n, form is finished

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 Don't worry, I'll move them when the PR is merged.

**Comment by ProgramerGuy** [comment]
Hi, I would like to help with the translate, I'll take the Switch page for begin and help you guys.

**Comment by Leopoldthecoder** [comment]
@ProgramerGuy Switch is now moved to Finished.

**Comment by sigfriedCub1990** [comment]
Hello there, I'll take installation, layout and menu.

**Comment by Leopoldthecoder** [comment]
@sigfriedCub1990 Installation, Layout and Menu are moved to WIP.

**Comment by ProgramerGuy** [comment]
Perfect, I'll take messagebox, message and notification to continue :D

**Comment by Leopoldthecoder** [comment]
@ProgramerGuy Updated.

**Comment by kikoseijo** [comment]
I can help, whats left?

**Comment by Gonzalo2310** [comment]
@kikoseijo At the top of this issue is a list.
Beware of what they have been recently selected and have not yet moved from the list.
Thank you

**Comment by sigfriedCub1990** [comment]
Pagination, popover and progress are my next choice :).

**Comment by Leopoldthecoder** [comment]
@sigfriedCub1990 Pagination, Popover and Progress are moved to WIP.

We're half way there. You guys are amazing!

**Comment by sigfriedCub1990** [comment]
I'll take quickstart, ratio and rate

**Comment by Leopoldthecoder** [comment]
@sigfriedCub1990 Quickstart, Radio and Rate are moved to WIP.

**Comment by Gonzalo2310** [comment]
next 3 (select, slider and steps)

**Comment by coderdiaz** [comment]
next 3 website pages (component, title, page)

**Comment by ProgramerGuy** [comment]
message-box is done

**Comment by yodebian** [comment]
form and table :D

**Comment by coderdiaz** [comment]
@yodebian table is in progress

**Comment by Leopoldthecoder** [comment]
Updated.

**Comment by josewhitetower** [comment]
I'll take tag and typography

**Comment by Leopoldthecoder** [comment]
@josewhitetower Tag and Typography are moved to WIP.

**Comment by thechosenjuan** [comment]
I'll take the next 3 (tabs, time-picker, tooltip)

**Comment by lesterbx** [comment]
Hi, i'm taking transfer, transition and tree

**Comment by thechosenjuan** [comment]
How are you guys translating things like input, placeholder, etc.?

**Comment by josewhitetower** [comment]
I don't think so, the element's names stay as they are. I try to make the explanations as clear as possible

**Comment by Gonzalo2310** [comment]
@thechosenjuan I think that things like input, placeholder, etc. are no longer words in English but computer terms. I don't know if it would be logical to translate them

**Comment by thechosenjuan** [comment]
Got it! I will leave as they are then. Thank you @Gonzalo2310

**Comment by Leopoldthecoder** [comment]
Updated.

Now the todo list is cleared!

**Comment by adavie1** [comment]
Count  me in! If you want some Q&A etc. I'm actually Mexican despite appearances! 

From a quick glance most components done. @Leopoldthecoder let me know where I can chip in.

**Comment by Leopoldthecoder** [comment]
@adavie1 Thanks. If you are interested, you can help translate our [FAQ](https://github.com/ElemeFE/element/blob/es-doc/FAQ.md) and [contributing guide](https://github.com/ElemeFE/element/blob/es-doc/.github/CONTRIBUTING.en-US.md) to Spanish.

**Comment by adavie1** [comment]
@Leopoldthecoder will do. Thanks for letting me contribute.

**Comment by stellamiranda** [comment]
Hi @Leopoldthecoder ! 

I would like to help translating to Spanish these 3 files: `typography`, `tag` and `notification`

Spanish is my native language :)

**Comment by Leopoldthecoder** [comment]
@josewhitetower Are you still interested in translating Tag and Typography? It's OK if you're busy with something else, then we could ask @stellamiranda for her help.

Also, @ProgramerGuy how about Notification?

No pressure guys, just a bit curious.

**Comment by josewhitetower** [comment]
Bad timing sorry, give @stellamiranda and @ProgramerGuy  green light, I might check the translations later..

**Comment by Leopoldthecoder** [comment]
@stellamiranda Hi, could you help us with Tag and Typography?

**Comment by stellamiranda** [comment]
@Leopoldthecoder Yes, work in progress :)

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder Can I help you with anything else?

**Comment by adavie1** [comment]
@Leopoldthecoder:  what @Gonzalo2310  said! :-) Anything else you need?

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 @adavie1 I think DatePicker, DatetimePicker, Dialog and Notification are open again since our volunteers are either too busy or non-native speaker. Perhaps each of you can take two of them?

Plus, we'll need an overall review after all individual files are finished.

**Comment by carmencitaqiu** [comment]
@Leopoldthecoder I have finished the translation of DatePicker,DatetimePicker,and I have commited a pull request No.#8206.Since the pull request are still open,is there any questions about this pr?

**Comment by Leopoldthecoder** [comment]
@carmencitaqiu I left some comments https://github.com/ElemeFE/element/pull/8206#pullrequestreview-77793561

**Comment by carmencitaqiu** [comment]
@Leopoldthecoder I will modify the problems as soon as possible

**Comment by Gonzalo2310** [comment]
@ProgramerGuy @Leopoldthecoder I'll do notification. ok?

**Comment by Gonzalo2310** [comment]
notification done

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 @adavie1 DatePicker, DatetimePicker and Dialog are done. Could you review them since they're translated by a non-native speaker?

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder Yes!!

**Comment by Gonzalo2310** [comment]
I am very grateful for the work of all those who have collaborated.
I didn't think so many people would add up.
I thought it would be a tedious job for months but it's been a little light and fast.
Thank you all for your efforts and especially @Leopoldthecoder for your constant dedication to this project.

**Comment by adavie1** [comment]
@Leopoldthecoder of course! @Gonzalo2310 Cual harás?

**Comment by Gonzalo2310** [comment]
@adavie1 Sorry. DatePicker, DatetimePicker and Dialog Fixed and uploaded already

**Comment by adavie1** [comment]
Great. I can go get a coffee then! :-D

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 It seems we can start the overall review now. Since the purpose of this review is to unify the docs' logic and wording, I think it should involve only one or two people. Let me know if you need anyone's help, or you can directly ping them here.

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder I start from 25/11 and publish progress. For now I can move forward without involving anyone else. If I see any delays, I'll let you know. ok?

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 Sounds good to me.

**Comment by lmatab** [comment]
Sounds great, how could I participate in the translation?

**Comment by coderdiaz** [comment]
Status for tag and typography? @Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@coderdiaz I'm not sure if @stellamiranda has started.

@stellamiranda Hi, could you update your progress here?

**Comment by Gonzalo2310** [comment]
Only missing tag and typography

**Comment by Leopoldthecoder** [comment]
I'm afraid we'll have to find another person for Tag and Typography. Any volunteer?

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder I'll bring it up in a few minutes. I'll do it right now. It's already checked.

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder I don't know if I've done it right... as usual. :(

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder we will create CHANGELOG.es-ES.md?

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 It's good to have a Spanish changelog, but my concern is that it may not get updated in time. When a new version is released, we'll wait for the community to update the changelog, so there'll be a few days when the changelog doesn't reflect the latest changes.

This problem also affects component docs. Since we rely on the community to update the docs, there will always be some delay.

Do you have any idea to solve this?

**Comment by Gonzalo2310** [comment]
I think that if at first the news is in English one day or two will not affect the community but I don't know if that's extra work for you.

**Comment by Gonzalo2310** [comment]
I'm using CodeRelease.io to control repository changes. 
What do you need to be calm (mail, to use some software?). I take care of any future changes

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 Sounds good to me. Then please translate the changelog. We can release the docs when the changelog is done.

Thank you.

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder  You'll have it today.

**Comment by Gonzalo2310** [comment]
It cost me more than I thought, but that's it. Let's publish!!!

**Comment by Leopoldthecoder** [comment]
@Gonzalo2310 Thanks. It will be published next week.

**Comment by Leopoldthecoder** [comment]
Hi everyone! Thank you all for helping us with the Spanish documentation. I'm glad to say that it will be released tomorrow (actually it's now running perfectly on my computer).

Gracias, amigos!
