### ISSUE TITLE
bug,el-select

### ISSUE THREAD

**Issue by baofengqqwwff** [ElemeFE/element#8075]
引入el-select的时候报错，

 error  in ./node_modules/element-ui/packages/scrollbar/src/main.js

Module parse failed: Unexpected token (64:4)
You may need an appropriate loader to handle this file type.
|       ref: 'resize'
|     }, this.$slots.default),
|     const wrap = (
|       <div
|         ref="wrap"

 @ ./node_modules/element-ui/packages/scrollbar/index.js 1:0-35
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?typ
e=script&index=0&bustCache!./node_modules/element-ui/packages/select/src/select.
vue
 @ ./node_modules/element-ui/packages/select/src/select.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?typ
e=script&index=0&bustCache!./src/components/index.vue
 @ ./src/components/index.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

终止批处理操作吗(Y/N)?
^C

**Comment by penggle** [comment]
我也遇到了这个问题
