### ISSUE TITLE
关于上传组件的文件列表"按delete键可删除"可否删除

### ISSUE THREAD

**Issue by juffyduan** [ElemeFE/element#8076]
![image](https://user-images.githubusercontent.com/11515538/32479764-676ee454-c3c6-11e7-8101-bca805516d77.png)
如图，上传组件中的文件列表中默认有个“按delete键可删除”文字，放在这里很不协调，也很丑，能不能不要这个，蟹蟹

**Comment by Leopoldthecoder** [comment]
可以用 CSS 隐藏。

**Comment by juffyduan** [comment]
@Leopoldthecoder 嗯，我目前就是这么做的
