### ISSUE TITLE
[Bug Report] After el-table-column set show-overflow-tooltip, the safari browser displays the table line is not neat

### ISSUE THREAD

**Issue by seamanm** [ElemeFE/element#8078]
### Element UI version
2.0.3

### OS/Browsers version
mac 10.13 safari 版本 11.0 (13604.1.38.1.6)

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/uu1985/pj71jkyw/700/](https://jsfiddle.net/uu1985/pj71jkyw/700/)

### Steps to reproduce
<template>
  <el-table
    :data="tableData"
    border
    style="width: 100%">
    <el-table-column
      prop="date" show-overflow-tooltip
      label="日期"
      width="180">
    </el-table-column>
    <el-table-column
      prop="name"
      label="姓名" show-overflow-tooltip
      width="180">
    </el-table-column>
    <el-table-column
      prop="address"
      label="地址">
    </el-table-column>
  </el-table>
</template>

<script>
  export default {
    data() {
      return {
        tableData: [{
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1517 弄'
        }, {
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄'
        }, {
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1516 弄'
        }]
      }
    }
  }
</script>

### What is Expected?
表格边框线条对齐

### What is actually happening?
表格边框线条扭曲。https://jsfiddle.net/uu1985/pj71jkyw/700/这个网站看不见线条。

**Comment by Leopoldthecoder** [comment]
有截图吗？

**Comment by seamanm** [comment]
![54293c39-6a70-433b-a98a-2bc4a12f9c17](https://user-images.githubusercontent.com/20679488/32494762-e336c21e-c3fd-11e7-9222-930f85f3647d.png)

**Comment by furybean** [comment]
@seamanm  Duplicate with #8768. Please keep track that issue.
