### ISSUE TITLE
多选表格中的checkbox能否提供阻止冒泡？

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/element#808]
首先我点击表格行会触发row-click某个事件，但是勾选行内的checkbox时候，也会触发row-click事件，应该怎么处理？
![image](https://cloud.githubusercontent.com/assets/13248613/19962008/93e20ca8-a1f0-11e6-8825-969ab4292446.png)

**Comment by newlife** [comment]
求问，这个怎么处理的，，，

**Comment by 540240126** [comment]
同求 @hopkinson ,请问你怎么解决的?

**Comment by 540240126** [comment]
@Leopoldthecoder 求解，急求各位大佬

**Comment by hopkinson** [comment]
@540240126 
  handleRowClick(row, event, column) {
      if (event.target.nodeName !== 'INPUT' && event.target.className !== 'el-checkbox__inner') {
       


      }
    },

**Comment by 540240126** [comment]
这也是个办法哈哈，多谢大佬

**Comment by P3T3R-Z** [comment]
.prevent.stop
