### ISSUE TITLE
[Feature Request] [new features] tree control el-tree adds node-hover event

### ISSUE THREAD

**Issue by PilgrimErick** [ElemeFE/element#8084]
### Existing Component
是

### Component Name
el-tree 树形控件

### Description
![p 4krmenn 5 an g4sx u](https://user-images.githubusercontent.com/25657710/32487592-1034fc9a-c3e5-11e7-8c75-8de5462347a2.png)

如图，项目需求需要鼠标在树节点上悬浮时，显示额外的内容，查阅了文档，未发现有悬浮事件，希望能加上。

**Comment by PilgrimErick** [comment]
如果有方法可以通过传递$treeNodeId参数来删除data对应项数据，从而引起视图更新将节点删除，就更好了！~~

**Comment by liaoyinglong** [comment]
这个需求。。完全可以通过css来实现。。

另外可以通过直接操作源数据来删除节点也是未尝不可。。
