### ISSUE TITLE
[Feature Request] multi selector displays the contents of improvement

### ISSUE THREAD

**Issue by seamanm** [ElemeFE/element#8086]
### Existing Component
Yes

### Component Name
Select

### Description
选择器多选的时候，比如选择了10个或者20个item，边框会被撑得很大导致页面布局不协调。是否可以增加一个设置，比如当前有50个选项，用户选择了30个，就在文本框显示30/50即可，不需要把用户所选的都呈现出来。内容太多了。

**Comment by Leopoldthecoder** [comment]
I added an attribute `collapse-tags` in https://github.com/ElemeFE/element/pull/8190/commits/d99d3b34b53d94db0d9d0cf8506faa6ff0598585 .

![image](https://user-images.githubusercontent.com/10095631/32699172-263fb40c-c7ec-11e7-9777-87148b99d878.png)
