### ISSUE TITLE
[Bug Report] Get error when execute "npm run lint" command

### ISSUE THREAD

**Issue by hxshandle** [ElemeFE/element#8087]
### Element UI version
2.0.3

### OS/Browsers version
WIndows 10

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
1. git clone latest element-ui
2. npm install
3. npm run lint

### What is Expected?
should pass the lint.

### What is actually happening?
git the error listed below:

$ npm run lint

> element-ui@2.0.3 lint J:\github\element
> eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet

J:\github\element\build\salad.config.json
  2:13  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)

npm ERR! Windows_NT 10.0.15063

npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"

npm ERR! node v7.10.0

npm ERR! npm  v4.2.0

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! element-ui@2.0.3 lint: `eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the element-ui@2.0.3 lint script 'eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the element-ui package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet

npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs element-ui

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls element-ui

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by hxshandle** [comment]
One more thing, when I execute "**./node_modules/.bin/eslint src/**/* test/**/* packages/**/*.{js,vue} build/**/* --quiet**" it passed, but failed in "**npm run lint**" anyone can help?
-Handle

**Comment by zzzgit** [comment]
I have got the same problem when I tried to fork it and pack it

**Comment by Leopoldthecoder** [comment]
Fixed in #7869

**Comment by zzzgit** [comment]
it's a quick response man
