### ISSUE TITLE
[Bug Report] IE under the date control, through the event of the new date value, corresponding to the display value of the control does not update the problem

### ISSUE THREAD

**Issue by Dason1986** [ElemeFE/element#8097]
### Element UI version
2.0.1

### OS/Browsers version
win10 / ie11

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/dason/dpeL8Lwh/](https://jsfiddle.net/dason/dpeL8Lwh/)

### Steps to reproduce
1 通过data 方法 初始化日期值
2 通过按钮事件，把日期值清付空‘’

如点击日期控件后，再离开控件。显示日期就为空了

### What is Expected?
日期控件显示日期值得到更新

### What is actually happening?
日期控件显示日期并没有清空，值还存在

**Comment by Dason1986** [comment]
https://jsfiddle.net/dason/ygns8r8s/
如果日期控件【el-date-picker】存在 【placeholder】标记
则显示值更新失败

**Comment by Leopoldthecoder** [comment]
Fixed in #9325.
