### ISSUE TITLE
[Feature Request] recommends adding components

### ISSUE THREAD

**Issue by jiankian** [ElemeFE/element#8099]
### Existing Component
否

### Component Name
多联级选择器、还有富文本编辑器、时间轴

### Description
React有现成的，Vue没有发现：
http://uxco.re/components/cascade-multi-select/
http://uxco.re/components/tinymce/
http://uxco.re/components/timeline/

**Comment by Leopoldthecoder** [comment]
多联级选择器会考虑，后两者无计划。
