### ISSUE TITLE
[Bug Report] when el-input in el-form press enter cause page reload

### ISSUE THREAD

**Issue by luon08** [ElemeFE/element#8101]
### Element UI version
2.0.3

### OS/Browsers version
Win7/ All Browser

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/704/](https://jsfiddle.net/pj71jkyw/704/)

### Steps to reproduce
1.key in any word
2.press enter
3.page will reload

### What is Expected?
page not reload

### What is actually happening?
page reloaded

**Comment by luon08** [comment]
@submit.native.prevent
can stop reload
but  @keyup.enter event not working in 2.0.3

**Comment by Leopoldthecoder** [comment]
Read the first question in [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md)

**Comment by ruanhuhu** [comment]
The submit is always fired on keydown. So use keydown instead of keyup.
[Prevent form submitting when pressing enter from a text input, using Vue.js
](https://stackoverflow.com/questions/31070479/prevent-form-submitting-when-pressing-enter-from-a-text-input-using-vue-js)
