### ISSUE TITLE
The config option of [Bug Report] element-theme2.0.0 is invalid, resulting in a program error

### ISSUE THREAD

**Issue by hzsrc** [ElemeFE/element#8103]
### Element UI version
2.0.3

### OS/Browsers version
win7/chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
var builder = require('element-theme');

	// build
	builder.run({
		config: './src/assets/css/element-theme/theme-element-variables.scss',
		out: './src/assets/css/element-theme/dist',
		minimize: true
	}, cb);

### What is Expected?
根据config的路径，来生成theme

### What is actually happening?
报错了。经查发现是elemeht-theme/lib/task.js这句代码：
  fs.writeFileSync(varsPath, fs.readFileSync(path.resolve(process.cwd(), config.config)), 'utf-8')
直接用的是默认的路径config.config，而不是opts.config，导致找不到文件。

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElementUI/element-theme/pull/38
