### ISSUE TITLE
[Bug Report] layout container table component is not self compatible

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#8108]
### Element UI version
2.0.3

### OS/Browsers version
osx

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/zx3pcqm5/](https://jsfiddle.net/zx3pcqm5/)

### Steps to reproduce
收起 --> 展开
el-main 区域因为 el-table 宽度没有自兼容 宽度会>100%

### What is Expected?
右侧宽度始终100%

### What is actually happening?
宽度被撑开

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8042

**Comment by An0nymous0** [comment]
@Leopoldthecoder THX,刚刚用width: .001%;临时解决了下。
