### ISSUE TITLE
[Bug Report] tooltip render

### ISSUE THREAD

**Issue by Cecilxx** [ElemeFE/element#8111]
### Element UI version
2.0.3

### OS/Browsers version
mac chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/cecil_jser/rqd8L3wy/](https://jsfiddle.net/cecil_jser/rqd8L3wy/)

### Steps to reproduce

1. 引入tooltip（按需加载、全局引入都试过）
2. 调用 <el-tooltip>
`<el-tooltip>鼠标移入到这</el-tooltip>`
`<el-tooltip><span>鼠标移入到这</span></el-tooltip>`

### What is Expected?
两种写法都能正常渲染

### What is actually happening?
第一种写法不能渲染，第二种写法正常渲染。

### 可能原因
一开始以为是vue版本问题，自己写了个组件试了下slot 不加外层标签也是可以渲染的。然后看了下element代码，好像是el-tooltip会渲染两次，第一次渲染vnode正常，第二次渲染会改变vnode，猜测是重新包装了一下，添加了tag等属性，改变了text， text为undefined，所有导致node节点没有渲染出来。

**Comment by Leopoldthecoder** [comment]
不是 bug，目前的实现要求必须包一层。

**Comment by PanJiaChen** [comment]
个人觉得应该在文档上标注一下，我前面也是看了源码才发现的。
