### ISSUE TITLE
[Bug Report] form with existed data causing wrong validation

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#8112]
### Element UI version
2.0.3

### OS/Browsers version
WIndows 10 / Chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/5ygmhrsz/](https://jsfiddle.net/5ygmhrsz/)

### Steps to reproduce
run the jsfiddle demo

click the input to focus then click outside to blur.
shows the error `please input a number`. But there did has a number `100`

### What is Expected?
 no error shows

### What is actually happening?
error shows

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/5ygmhrsz/1/
