### ISSUE TITLE
[Feature Request] Customize select component input

### ISSUE THREAD

**Issue by ProgLan** [ElemeFE/element#8115]
### Existing Component
Yes

### Component Name
select

### Description
When there are many tags inside the multiple select component, its height is not fixed, which will affect the page layout.

Proposed to provide a slot to customize the select component's input. Attach an customized multiple select component.
![multiple-selector](https://user-images.githubusercontent.com/11963229/32577491-f6538620-c48e-11e7-8ae3-90210027283e.PNG)

**Comment by Leopoldthecoder** [comment]
I added an attribute `collapse-tags` in https://github.com/ElemeFE/element/pull/8190/commits/d99d3b34b53d94db0d9d0cf8506faa6ff0598585 .

![image](https://user-images.githubusercontent.com/10095631/32699172-263fb40c-c7ec-11e7-9777-87148b99d878.png)
