### ISSUE TITLE
[Bug Report] Menu error: Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/element#8116]
### Element UI version
2.0.3

### OS/Browsers version
Mac OS, Chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/gmve9d3p/186/](https://jsfiddle.net/gmve9d3p/186/)

### Steps to reproduce
1. Open the jsfiddle or even the demo page: http://element.eleme.io/#/zh-CN/component/menu
2. Go to the Collapse Menu
3. Open up the console
4. Collapse the menu and try to hover over the icon or menu item during the transition
5. Errors in console

### What is Expected?
No error message

### What is actually happening?
Error message:
```
    Uncaught TypeError: Cannot read property 'style' of undefined
        at a.handleTitleMouseleave (element-ui.ee7d501.js:1)
        at n (vue.runtime.min.js:6)
        at e (vue.runtime.min.js:6)
        at HTMLDivElement.t._withTask.t._withTask (vue.runtime.min.js:6)
```

The error is at
```javascript
handleTitleMouseenter: function() {
    ("horizontal" !== this.mode || this.rootMenu.backgroundColor) && (this.$refs["submenu-title"].style.backgroundColor = this.rootMenu.hoverBackground)
},
handleTitleMouseleave: function() {
     ("horizontal" !== this.mode || this.rootMenu.backgroundColor) && (this.$refs["submenu-title"].style.backgroundColor = this.rootMenu.backgroundColor || "")
}
```

`this.$refs["submenu-title"]` is somehow is null during the transition

**Comment by WangHansen** [comment]
### Element UI version
2.0.3

### OS/Browsers version
Mac OS, Chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/gmve9d3p/186/](https://jsfiddle.net/gmve9d3p/186/)

### Steps to reproduce
1. 用jsfiddle或者直接打开讲解menu的界面： http://element.eleme.io/#/zh-CN/component/menu
2. 找到可折叠的menu
3. 打开Chrome console
4. 点击折叠或者展开，在动画进行的过程中用鼠标滑过图标或者菜单里面的项目
5. 可以看到console报错

### What is Expected?
不报错

### What is actually happening?
错误信息：
```
    Uncaught TypeError: Cannot read property 'style' of undefined
        at a.handleTitleMouseleave (element-ui.ee7d501.js:1)
        at n (vue.runtime.min.js:6)
        at e (vue.runtime.min.js:6)
        at HTMLDivElement.t._withTask.t._withTask (vue.runtime.min.js:6)
```

错误位置
```javascript
handleTitleMouseenter: function() {
    ("horizontal" !== this.mode || this.rootMenu.backgroundColor) && (this.$refs["submenu-title"].style.backgroundColor = this.rootMenu.hoverBackground)
},
handleTitleMouseleave: function() {
     ("horizontal" !== this.mode || this.rootMenu.backgroundColor) && (this.$refs["submenu-title"].style.backgroundColor = this.rootMenu.backgroundColor || "")
}
```

`this.$refs["submenu-title"]` 被显示为null

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8100/commits/d56a3b5e9359e1c1c29b28f61829e5c75c862bcf
