### ISSUE TITLE
[BUG]Table在从来没有显示过的情况下，非常耗CPU

### ISSUE THREAD

**Issue by ericliudexin** [ElemeFE/element#8120]
当table从来没有显示过的情况下，发现element不停在监测。
当显示过后就不会了。由于项目中很多使用了Tab来展示，这个问题就变得非常明显。
![image](https://user-images.githubusercontent.com/3488156/32586073-a2443d74-c53b-11e7-8571-5bf585c9113a.png)

对比了上一版本的代码，这个问题没有根本解决，而是做了延时，有了一定的优化。但当keepalive了路由，隐藏的table很多的时候，cup又上去了。

希望能够真正解决这个问题

**Comment by Leopoldthecoder** [comment]
@liril-net 来看看
