### ISSUE TITLE
[Question] table-slot

### ISSUE THREAD

**Issue by kolesoffac** [ElemeFE/element#8128]
### Existing Component
Yes

### Component Name
el-table

### Description
Explain the use of [table-slot](http://element-cn.eleme.io/1.4/#/en-US/component/table#table-slot), please. I want implement infinity scroll.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/pj71jkyw/708/

**Comment by kolesoffac** [comment]
Need tbody make scrollable, but not whole grid. And where use table-slot? Thanks

**Comment by Leopoldthecoder** [comment]
Sorry for the mistake. A valid example: https://jsfiddle.net/4ez4j2j4/1/

**Comment by kolesoffac** [comment]
Many thanks!
