### ISSUE TITLE
In on-error callback of [Bug Report] Upload component, the original error information returned by server can not be obtained

### ISSUE THREAD

**Issue by yikuo123** [ElemeFE/element#8130]
### Element UI version
1.4.6

### OS/Browsers version
Chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/713/](https://jsfiddle.net/pj71jkyw/713/)

### Steps to reproduce
1.将action地址设置为https://chaoshensu.oss-cn-hangzhou.aliyuncs.com/
2.等待服务器返回出错
3.on-error回调被执行，获取error.message

### What is Expected?
获取error的结果为：

```xml

<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Invalid according to Policy: Policy Condition failed: ["eq", "$key", "config/watermark"]</Message>
  <RequestId>5A041737F9C7D3AB4EBFDC36</RequestId>
  <HostId>chaoshensu.oss-cn-hangzhou.aliyuncs.com</HostId>
</Error>

```

没有前面的“403 ”

### What is actually happening?
结果为：

```xml

403 <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Invalid according to Policy: Policy Condition failed: ["eq", "$key", "config/watermark"]</Message>
  <RequestId>5A041737F9C7D3AB4EBFDC36</RequestId>
  <HostId>chaoshensu.oss-cn-hangzhou.aliyuncs.com</HostId>
</Error>

```
比服务器返回的结果多了“403 ”

**Comment by yikuo123** [comment]
另外还发现，如果action设置为一个不可达的地址，onerror回调传入的error是一个ProgressEvent对象

**Comment by Leopoldthecoder** [comment]
This is on purpose. This is the only way to know the error code in onError callback. You can use a RegExp to filter it.

**Comment by yikuo123** [comment]
@Leopoldthecoder  error对象不是还有一个status对象吗，我看那里面就是状态码呢

**Comment by Leopoldthecoder** [comment]
Oh yes. Then I'll remove it from error.message.

**Comment by youyouliangshao** [comment]
dose it solved?
