### ISSUE TITLE
[Bug Report] [Select && MessageBox] @visible-change use with this.$alert will appear bug

### ISSUE THREAD

**Issue by ruiyong-lee** [ElemeFE/element#8133]
### Element UI version
2.0.3

### OS/Browsers version
win10 / chrome 59 or 64

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/546k5tw9/](https://jsfiddle.net/546k5tw9/)

### Steps to reproduce
click el-select, trigger @visible-change and than show messagebox, when close messagebox, el-select's options and messagebox cant't close, trigger @visible-change again and again

### What is Expected?
el-select's options and messagebox will close and not  trigger @visible-change again

### What is actually happening?
el-select's options and messagebox cant't close, trigger @visible-change again and again

**Comment by Leopoldthecoder** [comment]
Select 在展开的状态下，如果点击了屏幕上的其他区域，会收起 Select。所以例子里在点击 MessageBox 的按钮后，Select 会关闭下拉框，然后焦点会由 MessageBox 的按钮回到 Select，再次触发 Select 的 focus 事件，从而展开下拉框，触发 `visible-change`。

可以添加一个 flag 来解决：https://jsfiddle.net/546k5tw9/2/
