### ISSUE TITLE
[Bug Report] Datepicker shown in incorrect position

### ISSUE THREAD

**Issue by ASnow** [ElemeFE/element#8139]
### Element UI version
2.0.3

### OS/Browsers version
Mac, Chrome last

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/br7dwh8g/1/](https://jsfiddle.net/br7dwh8g/1/)

### Steps to reproduce
1. Click on datepicker
2. Wait picker shown
3. Close picker
4. Click toggle
5. Click on range picker
6. Wait range shown

### What is Expected?
Popper shown after element

### What is actually happening?
Popper shown at top left conner of the screen

**Comment by Leopoldthecoder** [comment]
You need to add `key`s to them to force a re-render.
