### ISSUE TITLE
[Bug Report] el-tag comp bug:after triggering the `close` event, the `el-tag` click event is also triggered!

### ISSUE THREAD

**Issue by huangshuwei** [ElemeFE/element#8145]
### Element UI version
2.0.3

### OS/Browsers version
window10/chrome 61.0.3163.100

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/huangsw/59099nan/](https://jsfiddle.net/huangsw/59099nan/)

### Steps to reproduce
just click close icon

### What is Expected?
I want to only trigger close callback

### What is actually happening?
el-tag click native event also triggered

> el-tag comp should @click.stop to prevent bubbles

**Comment by huangshuwei** [comment]
el-tag comp should @click.stop to prevent bubbles

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/59099nan/1/

**Comment by huangshuwei** [comment]
THX
