### ISSUE TITLE
[Bug Report] Loading service singleton?

### ISSUE THREAD

**Issue by HeartUnchange** [ElemeFE/element#8146]
### Element UI version
2.0.3

### OS/Browsers version
win10/chrome 62.0.3202.89 (正式版本) （64 位） (cohort: 62_89_win)

### Vue version
2.5.2

### Reproduction Link
[https://github.com/HeartUnchange/4Issue/tree/master/elementUI/Loading-service-singleton](https://github.com/HeartUnchange/4Issue/tree/master/elementUI/Loading-service-singleton)

### Steps to reproduce
抱歉，刚接触，不知道怎么用 jsfiddle 呈现，就缩减了一下放在[GitHub : Loading-service-singleton](https://github.com/HeartUnchange/4Issue/tree/master/elementUI/Loading-service-singleton)里了。
下载，构建，打开浏览器，访问 http://127.0.0.1:8010/。

tr: It is difficult for me to reproduce this in jsfiddle , so I provide a mini-project which stored in [GitHub : Loading-service-singleton](https://github.com/HeartUnchange/4Issue/tree/master/elementUI/Loading-service-singleton).

```
git clone https://github.com/HeartUnchange/4Issue.git
cd ./4Issue/elementUI/Loading-service-singleton
npm install && npm run dev
```
open ```http://127.0.0.1:8010/``` in your browser.
### What is Expected?

> 以服务的方式调用的全屏 Loading 是单例的

在```router.afterEach```中调用```loadingInstance.close();```应该关闭了才对，结果并没有。猜测是：并不是单例。
tr: Fullscreen-loading when is used as a service  should be closed after calling ```loadingInstance.close();``` in ```router.afterEach```, but it doesn't work.

### What is actually happening?
全屏 Loading 并没有关闭。
tr: ```loadingInstance.close();``` not close all fullscreen-loading-service instance.

~~如果repo贡献者里没有友人，下次就不作死翻英文了。

**Comment by Leopoldthecoder** [comment]
关闭需要是异步的：https://github.com/HeartUnchange/4Issue/pull/1
