### ISSUE TITLE
[Feature Request] el-table may need a method to prevent the selection change when the user clicked another row.

### ISSUE THREAD

**Issue by K-Wen** [ElemeFE/element#8147]
### Existing Component
Yes

### Component Name
el-table

### Description
Just like the method in NSTableView of Cocoa:
`- (BOOL)selectionShouldChangeInTableView:(NSTableView *)tableView;`
called whenever the user is about to change the selection. Return NO to prevent the selection from being changed at that time.

Currently, for a single select el-table, it will chang selection when the user click another row no matter whether he/she really wants it change or not.

For example:
An el-table in the left and every table row means a details view in the right. I modified some info in the details view but not save, and then I clicked another row, here I want to show a confirm of "Unsaved changs will lost", if the user clicked cancel, selection will keep and nothing will happen, but now el-table changes selection to the new clicked row immediately.
Waiting for your reply !

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/zwyqa7v7/1/
