### ISSUE TITLE
tabs标签嵌套tab-position问题

### ISSUE THREAD

**Issue by ahtZzz-xiao** [ElemeFE/element#8150]
tabs嵌套使用的时候，最外层设置tab-position='left'，里面所有的tabs标签都默认为tab-position='left'
![image](https://user-images.githubusercontent.com/32116884/32641435-dcee816e-c608-11e7-8dee-54a3161cd07e.png)

**Comment by ThoughtZer** [comment]
@ahtZzz-xiao 你好，我也遇到相同的问题。不知道你怎么解决的呢
