### ISSUE TITLE
[Bug Report] el-select report bug

### ISSUE THREAD

**Issue by korewayume** [ElemeFE/element#8151]
### Element UI version
1.4.9

### OS/Browsers version
macOS

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/xt2jjuvr/](https://jsfiddle.net/xt2jjuvr/)

### Steps to reproduce
console report an error when click the enable radio

### What is Expected?
Don't cause an error

### What is actually happening?
It cause an error

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8018
