### ISSUE TITLE
[Bug Report] Message-box test problem

### ISSUE THREAD

**Issue by fjy5314** [ElemeFE/element#8157]
### Element UI version
2.0.3

### OS/Browsers version
win10/chrome

### Vue version
2.4.2

### Steps to reproduce
  

> const msgbox = document.querySelector('.el-message-box__wrapper');
        expect(msgbox.__vue__.$parent.visible).to.true;
        expect(msgbox.querySelector('.el-message-box__title').textContent).to.equal('删除区域');
        expect(msgbox.querySelector('.el-message-box__message')
          .querySelector('p').textContent).to.equal('区域一旦删除，即不可恢复！');
        expect(msgbox.querySelector('.el-message-box__btns button').textContent).to.equal('\n          取消\n        ');
        expect(msgbox.querySelector('.el-message-box__btns button.el-button--primary').textContent).to.equal('\n          确定\n        ');
        msgbox.__vue__.$parent.close();
        wrapper.vm.$nextTick(_ => {
           expect(msgbox.__vue__.$parent.visible).to.false;
          done();
        })

运行到msgbox.__vue__.$parent.close(); 这行 出现
TypeError: Cannot read property 'closeDialog' of undefined 错误

### What is Expected?
不会出现closeDialog错误

### What is actually happening?
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'closeDialog' of undefined"

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
