### ISSUE TITLE
[Bug Report] Select component in multiple filterable mode -> focus issue

### ISSUE THREAD

**Issue by slinardi** [ElemeFE/element#8164]
### Element UI version
2.0.4

### OS/Browsers version
Chrome 62.0.3202.89, Firefox 56.0.2

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/z5wn4e5x/](https://jsfiddle.net/z5wn4e5x/)

### Steps to reproduce
One step only: try click on select component but directly to inner input element for filtering.
(when cursor from pointer changes to text, approx. within chars "Sel").

### What is Expected?
Clicking everywhere on select component should open drodpdown and focus inner input to start typing.

### What is actually happening?
When you click directly on .el-select__input (inner input for entering text), select component briefly gain focus and immediately loses focus.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8184/commits/2db923e421e44c6c1d2481ea2026bb735ed33f34
