### ISSUE TITLE
[Bug Report] Select in filterable and grouping mode is keeping group dividers when filter is applied

### ISSUE THREAD

**Issue by stefanosandes** [ElemeFE/element#8165]
### Element UI version
2.0.4

### OS/Browsers version
MacOS / Firefox / Chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/kLxs1wh0/1/](https://jsfiddle.net/kLxs1wh0/1/)

### Steps to reproduce
1 - Click on the select.
2 - Type "Bruno".

### What is Expected?
Only the item and his group must be visible

### What is actually happening?
Other hidden groups dividers keep visible (lines)

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8184/commits/2db923e421e44c6c1d2481ea2026bb735ed33f34
