### ISSUE TITLE
[Bug Report] slot append in component table

### ISSUE THREAD

**Issue by bapa92** [ElemeFE/element#8166]
### Element UI version
2.0.4

### OS/Browsers version
windows chrome

### Vue version
2.5.3

### Reproduction Link
[https://codepen.io/bapa92/pen/MOpmRM](https://codepen.io/bapa92/pen/MOpmRM)

### Steps to reproduce
need repro

### What is Expected?
What worked in version 1

### What is actually happening?
In version element 1 it ok, but in 2 scope is in new div outside the table.
https://cl.ly/2n0C2r3p331C

**Comment by Leopoldthecoder** [comment]
Yes, this is a breaking change in 2.0. See the changelog for more info.

> `append` slot is moved outside the `<tbody>` element to avoid multiple rendering

**Comment by liubaiye** [comment]
If you have solved this bug, please leave a message

thank you

**Comment by bapa92** [comment]
Unfortunately, I could not solve this problem.
