### ISSUE TITLE
[Bug Report] Client memory consumption is serious, UI Caton

### ISSUE THREAD

**Issue by iovvo** [ElemeFE/element#8170]
![a1](https://user-images.githubusercontent.com/19567397/32673658-f7254f9a-c68a-11e7-8fde-7c8bc3ebd0a0.png)
![a2](https://user-images.githubusercontent.com/19567397/32673660-f7565c02-c68a-11e7-9351-c2b9fce04e4c.png)
![a3](https://user-images.githubusercontent.com/19567397/32673661-f785b484-c68a-11e7-8e79-1416f65301da.png)
![a4](https://user-images.githubusercontent.com/19567397/32673662-f7b54c4e-c68a-11e7-882d-1ac98251729b.png)

### Element UI version
2.0.4

### OS/Browsers version
Window 7 x64 / Chrome 62.0.3202.62（正式版本） （32 位）

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/726/](https://jsfiddle.net/pj71jkyw/726/)

### Steps to reproduce
开发环境：Windows 7 x64，Vue 2.5.3，Webpack 2.7.0 or 3.8.1，Element-UI 1.49 up to 2.0.4
实际情况：我们有一个单页面的应用, 类似一个数据管理系统，大量的数据、列表、表单操作，我们将表单、列表放在了一个弹出的Dialog内，不知道为什么，发现我们的页面运行起来会越来的越慢，因为我们在Dialog中需要watch我们的数据ID变化来进行列表数据的加载，我尝试通过Chrome的Performance进行分析，发现了一些问题，我不知道该如何将截图与Performance的Data提交给你们分析，请求你们的协助。

### What is Expected?
希望可以得到你们的帮助，我的邮箱：iogroup@163.com，非常感谢！

### What is actually happening?
我们的页面性能变得很低，以致客户无法正常的使用。

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8351
