### ISSUE TITLE
[Bug Report] [el-table]  el-table-column use fixed="right"

### ISSUE THREAD

**Issue by ruiyong-lee** [ElemeFE/element#8172]
### Element UI version
2.0.4

### OS/Browsers version
win10 / chrome 64

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/gvm36yr0/2/](https://jsfiddle.net/gvm36yr0/2/)

### Steps to reproduce
el-table-column use fixed="right".
When there is no scrollbar in the table, no box-shadow in left, box-shadow in right.

### What is Expected?
no box-shadow in right.

### What is actually happening?
box-shadow in right.

**Comment by 13062761769** [comment]
table表格我一次性隐藏几列之后 表格无法正常显示出现拉伸不显示效果。（ps:正常条件渲染5列 我满足一定条件的时候隐藏三列 表格无法正常显示）

**Comment by julytian** [comment]
@13062761769 , 每一列加个 :key="Math.random()" 试下

**Comment by yeshengfei** [comment]
@ruiyong-lee I met the same display issue as u.  There is box shadow in right with no horizontal scroll.

element-ui @ 2.0.9

**Comment by Leopoldthecoder** [comment]
Fixed in #9327
