### ISSUE TITLE
[Bug Report] el-form should auto fix label width instead of asking users to specify label width.

### ISSUE THREAD

**Issue by ashishdoneriya** [ElemeFE/element#8174]
### Element UI version
2.0.4

### OS/Browsers version
Ubuntu 14.04

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/zf02ge44/1/](https://jsfiddle.net/zf02ge44/1/)

### Steps to reproduce
1. Create el-form
2. create el-form-item inside of el-form and specify label
3. create el-input inside of el-form-item
that's it

### What is Expected?
el-form should auto fix label width instead of asking users to specify label width and it should leave some space for labels also (like in tables we don't have to specify width for each column). This is helpful in case labels are dynamic (dynamic forms)

### What is actually happening?
In el-form If I do not specify label-width attribute then the el-input uses all the width available and make label weird.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by ashishdoneriya** [comment]
In English language it means that based on the project's current architecture there is no proper way to implement this. Alas I have to do in the old fashioned way (<table></table>)
