### ISSUE TITLE
[Bug Report] date-picker BUG, when type is datetimerange

### ISSUE THREAD

**Issue by gogoJava** [ElemeFE/element#8179]
### Element UI version
2.0.4

### OS/Browsers version
win10 / chrome 64

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/reoogn8m/](https://jsfiddle.net/reoogn8m/)

### Steps to reproduce
1、Select start time (时间选择，不是日期选择)
2、Select the end of time, with the same start time
3、Again select the end time, the rolling time after the choice of time has not changed, and can not confirm the error

### What is Expected?
Be able to choose correctly

### What is actually happening?
Can't choose right

**Comment by Leopoldthecoder** [comment]
请用中文描述，没太看得懂你的英语。

**Comment by gogoJava** [comment]
我想用中文的。。。问题就是选择开始时间，然后再选结束时间，结束时间更开始时间一样的时候确认之后，再选择结束时间，更改时间不会变化，并且输入框那里的时间没有变化，点确认也没有反应，js报错了

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/32717694-8fa553b2-c895-11e7-8778-038a7b5018e3.gif)

没重现出来，不知道是不是符合你的描述。最好上传一张动图。

**Comment by gogoJava** [comment]
动图不知道怎么搞，你选下面那个有快捷键的，你可以试试没有默认值的情况，确实是存在bug的

**Comment by harry-igaw** [comment]
I faced same issue

This issue occurs when you select 'start date' only and 'end time' is selected('end time' is not selected)
however, when you select 'start date', the calendar is displayed as if 'start time' and 'end date' and 'end time' are selected.

So, I tried to solve this problem in the following way.
When 'start date' is selected, disable 'end time' DOM field and guide the user to select 'end date'.
and If you select end date, enable 'end time' DOM field.

[video](https://youtu.be/q5BDYGpptoQ)

this is my code (.vue)
`template`
```html
....
<el-tooltip
  :value="isVisibleTooltip"
  :manual="true"
  effect="dark"
  content="Please select 'End date'"
  placement="left-end">
  <el-date-picker
    v-model="time"
    ref="datePicker"
    type="datetimerange"
    range-separator="To"
    format="yyyy-MM-dd HH:mm"
    start-placeholder="Start date"
    end-placeholder="End date">
  </el-date-picker>
</el-tooltip>
....
```

`javascript`
```javascript
....
data() {
  return {
    datePicker: null,
    startDateSelected: false,
    pickerVisible: false,
  };
},
computed: {
  isVisibleTooltip() {
    // if user select only 'start date' and picker is visible, show the tooltip
    // then user can notify that 'end date' must be selected
    return this.startDateSelected && this.pickerVisible;
  },
},
watch: {
  isVisibleTooltip(isVisible) {
    if (isVisible) {
      const endTimeInputComponent = this.datePicker.picker.$refs.maxInput;
      // disable Dom element(input)
      endTimeInputComponent.$refs.input.disabled = true;
      // add class .is-disabled Dom element(div - root element of component)
      endTimeInputComponent.$el.classList.add('is-disabled');
    } else {
      const endTimeInputComponent = this.datePicker.picker.$refs.maxInput;
      endTimeInputComponent.$refs.input.disabled = false;
      endTimeInputComponent.$el.classList.remove('is-disabled');
    }
  },
},
mounted() {
  this.datePicker = this.$refs.datePicker;
  // mount picker component in date-time-picker component by force
  this.datePicker.mountPicker();
  // watch the property 'selecting' of rangeState of picker
  // when user select the calendar, 'selecting' is changed (if user select only 'start date', then 'selecting' is true)
  this.$watch('$refs.datePicker.picker.rangeState.selecting', (isSelected) => {
    this.startDateSelected = isSelected;
  });
  // watch the property 'visible' of picker (this is for showing tooltip)
  this.$watch('$refs.datePicker.picker.visible', (visible) => {
    this.pickerVisible = visible;
  });
},
....
```

The DateTimePicker component has a component called picker internally.
The picker component is mounted when the user first clicks on 'start date' or 'end date' of the DateTimePicker.
If you do not mount the picker component by force, you can not watch the properties of the picker.

**Comment by renaudham** [comment]
Hello

what is the status on this bug?

It's 6 months ago and I need to know if somebody is working on debuging before being able to use El Ui on my on real client projects, and not only testing....


Thanks

**Comment by Guziq** [comment]
Any progress?

**Comment by jbh342156** [comment]
我也遇到这个问题,解决了吗?
