### ISSUE TITLE
Can components be built in advance in [Feature Request] el-dialog?

### ISSUE THREAD

**Issue by mmd0308** [ElemeFE/element#8181]
### Existing Component
Yes

### Component Name
dialog components

### Description
            <el-dialog  
            :visible.sync="dialogMenuVisible" 
            width='15%'
            ref="dialog"
            title="选择资源"
            >
                <role-menu ref="roleMenuCom" :roleId="roleToMenuId" @roleMenuCancle="roleMenuCancle" ></role-menu>
            </el-dialog>

这种写法,使用 this.$refs.roleMenuCom.getTree();调用子模版的方法是不行的,因为role-menu的组建还没有初始化.如何在父亲标签调用el-dialog中的子组建中的方法?

**Comment by Leopoldthecoder** [comment]
在 Dialog 的 `open` 回调里操作 DOM。

**Comment by mmd0308** [comment]
<el-dialog  
                :visible.sync="dialogMenuVisible" 
                width='15%'
                title="选择资源"
                @open="menuDialogOpen"
                >
                    <role-menu ref="roleMenuCom" :roleId="roleToMenuId" @roleMenuCancle="roleMenuCancle" ></role-menu>
                </el-dialog>


      menuDialogOpen() {
        this.$refs.roleMenuCom.getTree();
      },

这样还是不行的,open会调的时候,里面的components组建还没有初始化完成.

**Comment by tonychen0716** [comment]
解决了吗？
