### ISSUE TITLE
[Feature Request] Can components be built in advance in [Feature Request] el-dialog?

### ISSUE THREAD

**Issue by mmd0308** [ElemeFE/element#8182]
### Existing Component
Yes

### Component Name
el-dialog components

### Description
            <el-dialog  
            :visible.sync="dialogMenuVisible" 
            width='15%'
            title="选择资源"
            @open="menuDialogOpen"
            >
                <role-menu ref="roleMenuCom" :roleId="roleToMenuId" @roleMenuCancle="roleMenuCancle" ></role-menu>
            </el-dialog>

  menuDialogOpen() {
    this.$refs.roleMenuCom.getTree();
  },

这样还是不行的,open会调的时候,里面的components组建还没有初始化完成.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
