### ISSUE TITLE
[Bug Report] Popover doesn't show on first click

### ISSUE THREAD

**Issue by rbao** [ElemeFE/element#8186]
### Element UI version
2.0.4

### OS/Browsers version
macOS 10.15 / Chrome 61

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/t7m8n8yf/](https://jsfiddle.net/t7m8n8yf/)

### Steps to reproduce
Click on the button with popover and notice the popover doesn't show up on first click. Only after the second click the popover show up.

### What is Expected?
The popover show up on first click

### What is actually happening?
The popover show up on second click

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8188
