### ISSUE TITLE
[Bug Report] cascade selection under dynamic loading level, the first level to search through filterable

### ISSUE THREAD

**Issue by gwcai** [ElemeFE/element#8200]
### Element UI version
2.0.4

### OS/Browsers version
chrome 56

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/jzfewhqc/](https://jsfiddle.net/jzfewhqc/)

### Steps to reproduce
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui@1.4.9/lib/index.js"></script>
<div id="app">
<el-cascader :options="options2" @active-item-change="handleItemChange" :props="props" filterable></el-cascader>
</div>

### What is Expected?
第一级可以搜索

### What is actually happening?
搜索不到结果

**Comment by Leopoldthecoder** [comment]
初始化时第一级节点的子节点为 []，在 `change-on-select` 为 `false` 时（默认情况），这一级是没有可以被选中的项的，因此不会被搜索出来。

**Comment by gwcai** [comment]
change-on-select 与active-item-change是冲突的，那就没办法喽？

**Comment by laosandegudai** [comment]
这个冲突如何解决？用了异步加载就没办法选择父目录了。有木有子项单击事件？
