### ISSUE TITLE
that.$message和dialog共存的时候，显示层问题

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#821]
### ElementUI version

rc.8
### Vue version

2.0.3
### Steps to reproduce
1、页面中 先调起 dialog  然后 点击一个按钮触发that.$message  （这时候 message 显示是没有什么问题的）
2、关闭了dialog （这时候message 可能关了也可能 没关 ，不过没所谓）
3、再次调起 dialog   这时候 触发 message， message 会在遮罩层后面 

刷新页面一切又恢复正常， 

可以结论为： 第一次调用dialog的时候 message的z-index应该是计算对了，在不刷新的情况下 第二次调起dialog，message的 z-index计算有问题

**Comment by jin5354** [comment]
el-dialog 的 z-index 会递增，而 el-message 的 z-index 始终为 2000，导致这个问题

**Comment by Leopoldthecoder** [comment]
Fixed in #828
