### ISSUE TITLE
[Bug Report] Select component to set the width，Drop-down arrow misplaced

### ISSUE THREAD

**Issue by a573367014** [ElemeFE/element#8210]
### Element UI version
2.0.4

### OS/Browsers version
window7/chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/ckjezpoa/](https://jsfiddle.net/ckjezpoa/)

### Steps to reproduce
click select

**Comment by Leopoldthecoder** [comment]
请使用 CSS 覆盖：https://jsfiddle.net/ckjezpoa/1/
