### ISSUE TITLE
[Feature Request] summary can add custom style and function

### ISSUE THREAD

**Issue by luon08** [ElemeFE/element#8215]
### Existing Component
Yes

### Component Name
el-table

### Description
summary text can't add any custom style and function
like alignment, color change, fontsize change...etc

add custom style function would be helpful

**Comment by Leopoldthecoder** [comment]
You can customize its style using CSS.

**Comment by luon08** [comment]
but i want determine when minus give some css
when positive give some css

using css can't do this

**Comment by Leopoldthecoder** [comment]
Then you can use the `footer` slot.

**Comment by luon08** [comment]
I only saw there are append slot in el-table document
Not saw any thing likr footer slot

Can u give me any sample for how to use footer slot in el-table,thx

**Comment by Leopoldthecoder** [comment]
Sorry, I meant the `append` slot.
