### ISSUE TITLE
Table 表格组件如何支持rowspan colspan？

### ISSUE THREAD

**Issue by Noemi-** [ElemeFE/element#822]
### Reproduction Link

看了docs貌似没有提到rowspan的支持，在table组件的el-table-column标签里添加rowspan也是无效的。
现在elementui的table组件支持rowspan嘛？如果不支持，以后会考虑支持嘛？

**Comment by furybean** [comment]
可能会，不过目前来看优先级不高。

**Comment by user20161119** [comment]
@furybean 优先级要高啊，挺常见的啊

**Comment by lnxueyu** [comment]
为什么还没有支持呢
