### ISSUE TITLE
element2.0.4，官网demo中，Tree 树形控件，data为空数组时，chrome控制台报错

### ISSUE THREAD

**Issue by xyhxyw** [ElemeFE/element#8224]
版本：element-ui2.0.4
chrome：61
直接运行官网demo，设置data为[]，控制台报错。
![1](https://user-images.githubusercontent.com/2510538/32728757-7f5df17c-c8bc-11e7-8cf1-c32bf89daab6.png)

**Comment by PLQin** [comment]
原来这些问题是这样直接关闭的, 关闭问题真是简单
