### ISSUE TITLE
[Bug Report] DateTimePicker: Error in render: "TypeError: this.date is undefined"

### ISSUE THREAD

**Issue by badcom** [ElemeFE/element#8226]
### Element UI version
2.0.4

### OS/Browsers version
Windows 10 Home / Firefox 56.0.2

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/732/](https://jsfiddle.net/pj71jkyw/732/)

### Steps to reproduce
Open console log and click on the input field to open the DateTimePicker

### What is Expected?
Receive no error message

### What is actually happening?
[Vue warn]: Error in render: "TypeError: this.date is undefined"

found in

---> <TimeSpinner>
       <TimePicker>
         <Root>

Also, on my project I'm getting this another error, but I'm unable to replicate it in the jsfiddle:

[Vue warn]: Error in render: "TypeError: Cannot read property 'getHours' of undefined"

found in

---> <TimeSpinner>
       <TimePicker>
         <Root>

**Comment by wacky6** [comment]
Bounded value must be Date object.
Or, use `value-format`
