### ISSUE TITLE
[Bug Report] folding menu in the folded state, the display submenu is blocked

### ISSUE THREAD

**Issue by kiyonlin** [ElemeFE/element#8232]
### Element UI version
2.0.4

### OS/Browsers version
macOS10.12.6 ／ Google Chrome 61.0.3163.100 (Official Build) (64-bit)

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/tg45ao2s/](https://jsfiddle.net/tg45ao2s/)

### Steps to reproduce
查看jsfiddle

### What is Expected?
折叠菜单在折叠状态下，子菜单应该在最上层显示

### What is actually happening?
折叠菜单在折叠状态下，显示的子菜单被遮挡

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/tg45ao2s/1/

**Comment by kiyonlin** [comment]
把菜单封装到自定义组件中时，在el-aside上添加collasped样式无法解决问题

<el-aside class="collasped">
      <aside-menu></aside-menu>
</el-aside>

**Comment by kiyonlin** [comment]
@Leopoldthecoder @element-bot 👆

**Comment by Leopoldthecoder** [comment]
demo?

**Comment by kiyonlin** [comment]
已解决，忘记加样式了
