### ISSUE TITLE
[Feature Request] Looking to be a Sponsor

### ISSUE THREAD

**Issue by gdi2290** [ElemeFE/element#8233]
### Existing Component
No

### Component Name
N/A

### Description
Hi, I'm looking to become a sponsor and would like to talk with the team behind Element UI (It's not clear who the team is)

**Comment by Leopoldthecoder** [comment]
Does [OpenCollective](https://opencollective.com/element#sponsor) make sense to you? Or you can email me at yi.shyang@ele.me

**Comment by gdi2290** [comment]
awesome, I'll email you
