### ISSUE TITLE
[Feature Request] Allow not to import icon font

### ISSUE THREAD

**Issue by worudso** [ElemeFE/element#8235]
### Existing Component
Yes

### Component Name
Icon

### Description
I want to use third party icons(font awesome, glyphicons, etc) instead of element ui icons. I'm not saying I want to use both of them at the same time, but only third party. But, even in this case, I need to specify --font-path(I'm using a custom theme) and let the font files included in my build.
I suggest that when --font-path is not declared or other variable, for example, --disable-icon is set, the scss does not import font and get rid of them from build process.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. Since many Element components are using the built-in icons, removing them entirely would break these components.

**Comment by gerardojbaez** [comment]
This would be something helpful.
