### ISSUE TITLE
[Bug Report] Cascader: `active-item-change` event triggered two times

### ISSUE THREAD

**Issue by XBT1** [ElemeFE/element#8240]
### Element UI version
2.0.4

### OS/Browsers version
macOS / Chrome 61

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/w7spb7fq/](https://jsfiddle.net/w7spb7fq/)

### Steps to reproduce
在 `Cascader` 中选择一项，打开 `Console` 会看到两次结果

### What is Expected?
`active-item-change` 事件只触发一次

### What is actually happening?
`active-item-change` 事件触发两次。原因是 https://github.com/ElemeFE/element/blob/ed511e92195d9d3638aab3130f2684de3af27e33/packages/cascader/src/menu.vue#L231 这里绑定了 `focus` 和 `mouseenter` 造成的两次 `emit`

**Comment by leeziiAtCn** [comment]
+1

**Comment by leeziiAtCn** [comment]
@XBT1  我临时退回了2.0.2 规避掉了这个bug

**Comment by yoyo837** [comment]
I have the same problem. 2.0.4

**Comment by yoyo837** [comment]
@leeziiAtCn 我在handleItemChange里加了缓存控制，每一级本来就要异步加载，这样也同时解决了触发两次的问题

**Comment by XBT1** [comment]
@leeziiAtCn 看起来是 2.0.4 出现的问题。

**Comment by XBT1** [comment]
@yoyo837 我是因为要做**异步加载**和**选择即改变**，而官方并不同时支持这两种模式，所以我在 `active-item-change` 做判断如果点击的是 `active` 选项就关闭，如果点击的是非 `active` 选项就异步加载。而触发两次就很尴尬了。。。

**Comment by yoyo837** [comment]
@XBT1 应该自己加代码能解决，不过官方修复、甚至直接提供你这种场景的支持是首选。

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8283
