### ISSUE TITLE
[Bug Report] el-menu-item can not display in collapse(&&vertical) mode, when it wrapped in a div which strict the width

### ISSUE THREAD

**Issue by qidaneix** [ElemeFE/element#8241]
### Element UI version
2.0.4

### OS/Browsers version
window7 / chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/xiaodabao/4tfyhgpg/4/](https://jsfiddle.net/xiaodabao/4tfyhgpg/4/)

### Steps to reproduce
hover any icon

### What is Expected?
the el-menu-item should display normal.

### What is actually happening?
but it did not, it in the wrapped div

**Comment by qidaneix** [comment]
就是说，如果给了一个限定宽度的父容器的话，在收起状态的导航菜单的子菜单没法正常显示，不知道有没有什么好办法解决这个问题

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/4tfyhgpg/6/

**Comment by qidaneix** [comment]
@Leopoldthecoder 
哥呀，我这个overflow-y得加啊，因为加一个包裹容器的目的就是想让导航菜单在里面可以竖直方向滚动（而不是溢出）。
加上overflow-y目测不好使：
[https://jsfiddle.net/xiaodabao/4tfyhgpg/7/](https://jsfiddle.net/xiaodabao/4tfyhgpg/7/)

**Comment by Leopoldthecoder** [comment]
加 `overflow-y: auto` 的话 `overflow-x: visible` 就无效了，和 BFC 有关。

感觉也没什么好办法，菜单在 collapse 的时候下还需要滚动吗？一般来讲 collaspe 的话会比展开的时候短很多。这样的话可以只在展开时给 `overflow-y: auto`。

**Comment by qidaneix** [comment]
@Leopoldthecoder 
嗯，从bfc的角度来说，确实是没法实现了。
我们这个ERP项目有400个路由，所以一级目录也有40来个，一个屏幕是真的放不下，不得不滚动啊。
看来得牺牲一点用户体验了。
谢谢奕哥
