### ISSUE TITLE
[Feature Request] highlight DateTimePicker's selected shortcut

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#8243]
### Existing Component
是

### Component Name
DateTimePicker

### Description
when DateTimePicker has shortcuts and selected one of them, the selected shortcut add some style responsive for convenience user quickly recognize which time range selected.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by Yuliang-Lee** [comment]
can I implement this self and pr?
