### ISSUE TITLE
select 里面的v-model不同步更新

### ISSUE THREAD

**Issue by yobi-maggie** [ElemeFE/element#8246]
问题背景：
   el-select在el-table的其中一列里面， tableData的初始化数据里存在abstract_meta_dimension_id属性，在下拉框中选则时会触发change  但页面不显示（即不回传） 求大神提示大概会是什么原因呢？ 

代码如下：
<el-table-column label="标准维度">
                <template scope="scope">
                    <div v-if="isEdit && scope.row.field_type.indexOf('d') > -1">
                        <el-select v-model="scope.row.abstract_meta_dimension_id" @change="changeDimension(scope.row)" style="width: 130px;">
                            <el-option v-for="dim in bd_dimensions" :value="dim.dim_code" :label="dim.dim_name" :key="dim.dim_code"></el-option>
                        </el-select>
                    </div>
                    <div v-else>
                        {{isMultiProduct ? scope.row.abstract_meta_dimension_id : scope.row.meta_dimension_id}}
                    </div>
                </template>
            </el-table-column>

**Comment by Thyiad** [comment]
me to, some times it doesn't change text
