### ISSUE TITLE
vue.js:437 [Vue warn]: You may have an infinite update loop in a component render function.

### ISSUE THREAD

**Issue by jiahuamld** [ElemeFE/element#8247]
在使用table 的时候 最简单的官网例子 报错 去掉没有问题

我使用node进行渲染 前端直出 
 使用    "express": "~4.15.2", * Vue.js v2.3.2 element-ui 2.0
控制台警告
<img width="1553" alt="4aa256fa-5452-4d00-a34c-f099202df1f8" src="https://user-images.githubusercontent.com/11866846/32764819-3a3be98a-c8cd-11e7-850a-3d00847eff4e.png">

**Comment by jiahuamld** [comment]
![](https://user-images.githubusercontent.com/11866846/32764819-3a3be98a-c8cd-11e7-850a-3d00847eff4e.png)

**Comment by joyc-fe** [comment]
@jiahuamld  升级vue到2.5.0 即可

![image](https://user-images.githubusercontent.com/19755534/32767161-c90d33d0-c8d7-11e7-9f66-5e5aef17034c.png)
 
vue-router + element-ui  2.0.4 发生这个问题， table 渲染出问题，  没有其他任何嵌套或组合，最简单的demo， 准备去掉router 试试

![image](https://user-images.githubusercontent.com/19755534/32767342-8f24518e-c8d8-11e7-87f9-e277bc397e6e.png)
去掉router也不起效.

升级vue和ele-ui依赖版本一致， 问题解决了。。。。

@element-bot  这个问题即使低版本vue也应该友好提示吧
