### ISSUE TITLE
[Bug Report] vue.js:564 [Vue warn]: You may have an infinite update loop in a component render function.  (found in <Transition>)

### ISSUE THREAD

**Issue by Shafley** [ElemeFE/element#8251]
### Element UI version
2.0.4

### OS/Browsers version
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
I use el-table in template, after compiled, Chrome  console many error : 
vue.js:564 [Vue warn]: You may have an infinite update loop in a component render function.  (found in <Transition>)

### What is Expected?
No error

### What is actually happening?
Many errors

**Comment by zyp40627730** [comment]
你好大兄弟，饿了么UI 2.0 需要vue 2.5.2 及以上 吧vue升级下就能解决

**Comment by allanwxl** [comment]
Please update your vue version to 2.5.2

**Comment by Shafley** [comment]
Thx😶

**Comment by Axighi** [comment]
从elemntUI 1.3.7 升级到2.0.8, hover el-tooltip等组件就会报这个wanrning.将Vue升级到2.5.2, 2.5.13后问题依然存在.

**Comment by charleiWang** [comment]
thanks!
