### ISSUE TITLE
[Bug Report] Spacebar key on input tag inside Tree node stop working since v2.0.4 and accessibility changes

### ISSUE THREAD

**Issue by robertocastro** [ElemeFE/element#8255]
### Element UI version
2.0.4

### OS/Browsers version
Ubuntu 16.04 LTS / Chromium 62.0.3202.75

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/robertocastroroy/pj71jkyw/737/](https://jsfiddle.net/robertocastroroy/pj71jkyw/737/)

### Steps to reproduce
For some reason I need an el-input tag inside custom node content, rendering it with a render function.

### What is Expected?
When I type some text on input all characters are displayed.

### What is actually happening?
Space character is not displaying anymore due to some 'stopPropagation' and 'preventDefault' in Tree component since accessibility changes.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8281
