### ISSUE TITLE
[Bug Report] Popover pop-up box click triggers bug

### ISSUE THREAD

**Issue by Whalefallsea** [ElemeFE/element#8259]
### Element UI version
2.0.4

### OS/Browsers version
Chrome 62.0.3202.62（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/0wg44cez/](https://jsfiddle.net/0wg44cez/)

### Steps to reproduce
1、单击按钮，弹框一闪而过，如果继续单击则可以正常弹出弹框。
2、点击页面其他位置，按钮失去焦点，这时又会出现 1 的现象。

### What is Expected?
第一次单击按钮弹框应该会正常弹出。

### What is actually happening?
弹框弹出又马上消失，很像双击行为。如果保持按钮焦点状态，则单击会正常弹出弹框。如果按钮失去焦点后再单击，则会又会出现弹出又消失的现象。

**Comment by Leopoldthecoder** [comment]
Duplicate of #8186
