### ISSUE TITLE
[Bug Report] custom folding board cannot display icons

### ISSUE THREAD

**Issue by dahaiai** [ElemeFE/element#8263]
### Element UI version
2.0.4

### OS/Browsers version
windows10

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
自定义折叠板不能显示图标

### What is Expected?
自定义折叠板不能显示图标

### What is actually happening?
自定义折叠板不能显示图标

**Comment by Leopoldthecoder** [comment]
可以显示。

如果你指的是文档上的最后一个例子，是因为例子里的图标类名写错了，接下来会改掉。
