### ISSUE TITLE
[Bug Report] Tabs using CPU when component in backgroud pane

### ISSUE THREAD

**Issue by stefanosandes** [ElemeFE/element#8266]
### Element UI version
1.4.10

### OS/Browsers version
macOS High Sierra / Chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/stefanosandes/3r5umcmy/1/](https://jsfiddle.net/stefanosandes/3r5umcmy/1/)

### Steps to reproduce
1 - Open repro link
2 - Open Chrome Task manager
3 - Look the CPU column (it keep above 9)
4 - Comment or remove the table inside the second tab-pane
5 - Run fiddle again
6 - Look the CPU column (it keep between 0 and 1)

### What is Expected?
No extra CPU consumption when component is in background.

### What is actually happening?
Extra CPU consumption when component in background tab-pane. Comsuption may be highest depending the component complexit in background tab.

**Comment by Erdboden** [comment]
I also get strange behaviour from tabs in combination with tables. https://github.com/ElemeFE/element/issues/8295

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8351
