### ISSUE TITLE
[Bug Report] $prompt with inputType:'textarea' can't get focus

### ISSUE THREAD

**Issue by jialanmo** [ElemeFE/element#8269]
### Element UI version
2.0.4

### OS/Browsers version
All

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/jf6jv80u/](https://jsfiddle.net/jf6jv80u/)

### Steps to reproduce
Use $prompt with inputType:'textArea'

### What is Expected?
textarea in MessageBox can get focus

### What is actually happening?
Devtools show an error: 'Uncaught TypeError: Cannot read property 'focus' of null'. The cause of the problem at https://github.com/ElemeFE/element/blob/dev/packages/message-box/src/main.vue line 276.
```
setTimeout(() => {
    if (this.$refs.input && this.$refs.input.$el) {
        this.$refs.input.$el.querySelector('input').focus();
     }
}, 500);
```
And many places in this file such like`this.$refs.input.$el.querySelector('input')` didn't think of inputType: 'textarea'

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8279
