### ISSUE TITLE
[Feature Request] Standard Time am/pm option for Date and time range picker

### ISSUE THREAD

**Issue by jakehorn** [ElemeFE/element#8270]
### Existing Component
Yes

### Component Name
Date and Time Range Picker

### Description
Currently Date and Time Range Picker only allows for military time inputs. Being able to set component to standard time inputs would be greatly appreciated. Thank you!

**Comment by wacky6** [comment]
Internally, it uses `fecha`, so you can use `A` to represent AM/PM.

https://jsfiddle.net/96tfz8d8/

**Comment by pushchris** [comment]
@wacky6 that only brings it halfway to what @jakehorn is wanting. Your fiddle switches between AM/PM based on you picking a military time value (the dropdown still shows 24hrs in the hour picker). Ideally when you add ```A``` to the format, it would limit the hour picker to 12hrs and add an additional column for AM/PM picking.

**Comment by wacky6** [comment]
I guess the 12 hours + AM/PM switch won't be added anytime soon.

Also, format is only meant for formatting of string, it does not effect the UI.

**Comment by SimplyCorey** [comment]
Would love this feature as well :+1:

**Comment by petemolinero** [comment]
Would like this as well!

**Comment by firesh** [comment]
I crate a pull request to add am/pm mode in time selector, it works in any format contains `a` or `A`, e.g.`format="hh:mm:ss A"`
![image](https://user-images.githubusercontent.com/7334304/33495574-ebcf72a6-d701-11e7-83ed-6fca3bf5b4e1.png)
![image](https://user-images.githubusercontent.com/7334304/33495592-f7f0033e-d701-11e7-85fe-4bae8291d355.png)
Also works in range mode:
![image](https://user-images.githubusercontent.com/7334304/33495595-fc0f8cfa-d701-11e7-9674-6fd90ec6347b.png)

**Comment by jakehorn** [comment]
Awesome! Thanks @firesh

**Comment by MosheBerman** [comment]
I'd like to pile on another endorsement to this request as well. 

@firesh Thanks for putting time into a PR! As another user of Element, it looks pretty good. (I would like to be able to toggle the leading zero in 12 hour mode, but I guess that's a matter of taste and ISO 8601 standard. 😁 )

**Comment by firesh** [comment]
@MosheBerman Could you please post the excerpt of the standard you mentioned.

**Comment by Leopoldthecoder** [comment]
This will be supported in the next release.

**Comment by firesh** [comment]
@jakehorn v2.0.8 is release, I just post a demo:
https://jsfiddle.net/3s11upnb/

**Comment by brock-haugen** [comment]
Is there any chance this will be fully supported in the `DateTimePicker` sometime as well? Right now it's a little wonky:
https://jsfiddle.net/8hj99mo9/
