### ISSUE TITLE
The [Feature Request] shuttle array is not arranged in the order of shuttle

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#8273]
### Existing Component
是

### Component Name
transfer穿梭框

### Description
穿梭框右侧的显示顺序应该以穿梭的先后顺序一致，如先加入了条目3、4，然后加入了条目2，结果应该显示为3、4、2。而不是默认的2、3、4、

**Comment by Lpbzzz** [comment]
怎么实现呢？谁有方法或者API？

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by outman0503** [comment]
我也遇到这个问题  这就是个bug  失去了穿梭框的意义

**Comment by Will233** [comment]
I met this problem too,
as official team has no plan to fixed this
I fixed it myself  ,
my version is v1.4.2
I edit the source code of the Transfer
[Source file of Transfer](https://github.com/ElemeFE/element/blob/v1.4.2/packages/transfer/src/main.vue)


`

    computed: {
      sourceData() {
        return this.data.filter(item => this.value.indexOf(item[this.props.key]) === -1);
      },

      targetData() {
        // source code
        // return this.data.filter(item => this.value.indexOf(item[this.props.key]) > -1);

        //  here is my code
        let tmp = [];
        this.value.forEach(item => {
          let i = this.data.findIndex(it => it[this.props.key] === item);
          tmp.push(this.data[i]);
        });
        return tmp;
      },

      hasButtonTexts() {
        return this.buttonTexts.length === 2;
      }
    }
`

**Comment by 191824852** [comment]
你的方式 选择显示问题是解决了；但是保存完后重新展示不按照之前选择的顺序展示了！ 请问你解决了吗？

**Comment by conanliuhuan** [comment]
使用iView的穿梭框组件可解决此问题。

**Comment by KaivOU** [comment]
最新版本已经解决此问题
