### ISSUE TITLE
[Feature Request] wants to restrict uploading the same picture while using the upload component (not a successful callback), but without success

### ISSUE THREAD

**Issue by ThoughtZer** [ElemeFE/element#8276]
### Existing Component
Yes

### Component Name
Upload

### Description
在progress的callback中，循环了当前的fileList，判断时候重复，然后终止上传，但是终止之后仍然带着当前的file，进入了循环，不仅删掉了重复的，也删掉了之前的。代码如下：
    
    progressHandle(event, file, fileList) {
      for (let i = 0; i < fileList.length - 1; i  ) {
        if (fileList[i].raw.lastModified === file.raw.lastModified && fileList.length !== 1) {
          console.log('不可上传重复图片')
          this.$refs.upLoad.abort(file)
          fileList.length = fileList.length -1
        }
      }
    }

**Comment by helibin** [comment]
![image](https://user-images.githubusercontent.com/14595752/46939642-6a7dc080-d099-11e8-8e88-b253ec9ddcde.png)

![image](https://user-images.githubusercontent.com/14595752/46939593-41f5c680-d099-11e8-91c7-fe13df0047f7.png)

    handleRemove(file, fileList) {
      console.log(file, fileList, '取消上传')
      this.$refs.upload.abort(file)
      this.$refs.upload.clearFiles()
    },
表示根本暂停不住
