### ISSUE TITLE
[Feature Request] on Table components, you can add similar to this header style options.

### ISSUE THREAD

**Issue by lilong7676** [ElemeFE/element#8288]
### Existing Component
是

### Component Name
Table

### Description
如图

**Comment by lilong7676** [comment]
<img width="327" alt="wx20171115-121519 2x" src="https://user-images.githubusercontent.com/21004230/32820565-037301de-ca0a-11e7-9e05-43d42e041205.png">

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
