### ISSUE TITLE
[Bug Report] Loading may not be closed by bug

### ISSUE THREAD

**Issue by zhaoxiaohai** [ElemeFE/element#8289]
### Element UI version
1.4.4

### OS/Browsers version
win7/应该所有浏览器都会出现

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/Tindily/tw7k69yx/](https://jsfiddle.net/Tindily/tw7k69yx/)

### Steps to reproduce
点击"服务方式"按钮，Loading不会消失。
我看了源码，
https://github.com/ElemeFE/element/blob/dev/packages/loading/src/index.js
这个文件的36行和94行对比可知，Loading在显示的时候使用了Vue.nextTick()，但是关闭的时候没有做同样处理，不知道是作者故意而为之，还是遗漏了。
大部分异步的情况下，Loading都能被正确关闭，但是如果当Loading.service()和loading.close()几乎连续被调用的时候，close()会失效。

### What is Expected?
Loading动画应该被关闭

### What is actually happening?
Loading不会被关闭

**Comment by Leopoldthecoder** [comment]
加 `Vue.nextTick` 是为了避免另一个问题。服务方式的 Loading 需要异步关闭，我在文档里加一下吧。

**Comment by zhaoxiaohai** [comment]
还有，loading在关闭后，实际上DOM里面没有删除。需要手动调用instance.$emit('after-leave')，才能删除，而文档里面也没有写明。不知道这个是在什么情景下考虑如此设计的。
