### ISSUE TITLE
[Feature Request] within el-form, hope to set up tabindex attribute in el-input

### ISSUE THREAD

**Issue by wenbo** [ElemeFE/element#8294]
### Existing Component
Yes

### Component Name
el-input 

### Description
how to set tabIndex within el-input please?
I have a form that built by el-form, and I wanna move between the input field by tab key.

**Comment by Leopoldthecoder** [comment]
You can already do that without explicitly setting tabindex: https://jsfiddle.net/qomxyr94/ . Actually you don't have to set tabindex on form elements.

**Comment by khylias** [comment]
@Leopoldthecoder What if we want to set the index to -1?
