### ISSUE TITLE
[Feature Request] Indeterminate progress is in desperately need

### ISSUE THREAD

**Issue by Luzhanglei** [ElemeFE/element#8296]
### Existing Component
Yes

### Component Name
el-progress

### Description
Sometimes, the exact progress of an operation may be indeterminate. Because the completion of the task depends on many uncertain situations.

So I think a progress without exact value is required. Just like the indeterminate progress in Mac，it gives an animation to indicate the task is running without progress.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by CarterLi** [comment]
@Leopoldthecoder Any plan to implement this now?
