### ISSUE TITLE
[Bug Report] [ElContainer] Vertical layout judgment

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#8298]
### Element UI version
2.0.4

### OS/Browsers version
chrome

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/container/src/main.vue](https://github.com/ElemeFE/element/blob/dev/packages/container/src/main.vue)

### Steps to reproduce
官网文档:
el-container：外层容器。当子元素中包含  el-header 或 el-footer 时，全部子元素会垂直上下排列，否则会水平左右排列。

把el-header封装成组件
return tag === 'el-header' || tag === 'el-footer'; //失效

### What is Expected?
组件包装el-header生效

### What is actually happening?
组件包装el-header不生效

**Comment by Leopoldthecoder** [comment]
是的，这样 Container 无法判断，因此提供了 `direction` 属性用于直接指定排列方向。
