### ISSUE TITLE
loading自定义属性支持度

### ISSUE THREAD

**Issue by Helloooooooooo** [ElemeFE/element#830]
想要修改loading组件的背景色，发现不支持，也改不了呢！
感觉自定义程度有点低了。
希望能更新！
谢！

**Comment by Leopoldthecoder** [comment]
是的。近期会更新 Loading 的视觉，也有计划在目前 directive 的基础上再提供一个服务，这样有更大的自由度。

**Comment by Leopoldthecoder** [comment]
#1039 的修改允许用户自己设定背景色了，本周随下个版本发布。
