### ISSUE TITLE
[Bug Report] DateTimePicker date and time selector --format exception

### ISSUE THREAD

**Issue by Jack-93** [ElemeFE/element#8302]
### Element UI version
1.4.10

### OS/Browsers version
win10

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/8401855/32829932-8ebd2cbe-ca2e-11e7-8791-c7ddc30dca17.png)
饿了吗要反人类的关了中文Issues？？？不符合规定不给定中文版模式？？？你们洋文泡久了，不知道自己哪里长大的吗？？？态度有些不好，sorry

### What is Expected?
 <el-date-picker v-model="value1" type="datetime" format="HH-mm-ss"  placeholder="选择日期时间">
    </el-date-picker>

 format="HH-mm-ss"  格式化只影响输入框
不会影响日期面板中日期文本框

### What is actually happening?
 format="HH-mm-ss"  格式化影响输入框
同时会影响日期面板中日期文本框

**Comment by Jack-93** [comment]
图片那么明显了，还需要链接吗？？？
有病吧，简单的事非要复杂话，复杂是为了解决简单处理不了的问题，提个BUG还要东搞西搞，就你们团队时间精贵！！！！！

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
