### ISSUE TITLE
[Bug Report] Slider change event not working on drag and drop

### ISSUE THREAD

**Issue by vlechemin** [ElemeFE/element#8305]
### Element UI version
2.0.4

### OS/Browsers version
All

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/778y6bm0/](https://jsfiddle.net/778y6bm0/)

### Steps to reproduce
Drag and drop the slider

### What is Expected?
New value to be set

### What is actually happening?
New value is still the old value

**Comment by Leopoldthecoder** [comment]
`change` events will not fire if you use `value` instead of `v-model`. You need to listen to `input` in this case: https://jsfiddle.net/778y6bm0/1/
