### ISSUE TITLE
[Bug Report] Localization

### ISSUE THREAD

**Issue by slavkobabic** [ElemeFE/element#8306]
### Element UI version
2.0.4

### OS/Browsers version
Any

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ElemeFE/element/blob/c3ee5fc0df1fbbfabbc0b2f182809a77cc3f5a20/src/locale/lang/en.js#L24](https://github.com/ElemeFE/element/blob/c3ee5fc0df1fbbfabbc0b2f182809a77cc3f5a20/src/locale/lang/en.js#L24)

### Steps to reproduce
Checkout strings for datepicker.month[1-12]
All strings are in short format.
eg.
https://github.com/ElemeFE/element/blob/c3ee5fc0df1fbbfabbc0b2f182809a77cc3f5a20/src/locale/lang/en.js#L24 

### What is Expected?
Value of months should be in long format
```JavaScript
month1: 'January',
month2: 'February',
month3: 'March',
month4: 'April',
month5: 'May',
month6: 'June',
month7: 'July',
month8: 'August',
month9: 'September',
month10: 'October',
month11: 'November',
month12: 'December',
```
Like in Italian localization
https://github.com/ElemeFE/element/blob/c3ee5fc0df1fbbfabbc0b2f182809a77cc3f5a20/src/locale/lang/it.js#L24

### What is actually happening?
Valuees of months are abbreviated 

```JavaScript
month1: 'Jan',
month2: 'Feb',
month3: 'Mar',
month4: 'Apr',
month5: 'May',
month6: 'Jun',
month7: 'Jul',
month8: 'Aug',
month9: 'Sep',
month10: 'Oct',
month11: 'Nov',
month12: 'Dec',
```

https://github.com/ElemeFE/element/blob/c3ee5fc0df1fbbfabbc0b2f182809a77cc3f5a20/src/locale/lang/en.js#L24

**Comment by Leopoldthecoder** [comment]
This will be fixed in the next release.
