### ISSUE TITLE
[Bug Report] Can not control visibility of popover in table

### ISSUE THREAD

**Issue by chenyiqiao** [ElemeFE/element#8309]
### Element UI version
2.0.4

### OS/Browsers version
any 

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/zhmkgj0q/2/](https://jsfiddle.net/zhmkgj0q/2/)

### Steps to reproduce
cannot control the visibility of popover in table since i cannot add `v-model` to popover

### What is Expected?
I would expect that I can use `v-model` in popover just like everywhere else so that I can close it when I click confirm button. 

### What is actually happening?
In #7038, @Leopoldthecoder recommend we remove `v-model` to fix the issue.Now the only way to close it is to click `document` otherwise it just pops over there.

**Comment by Leopoldthecoder** [comment]
Your demo seems to be irrelevant with this issue (for example, the `handler` method is never executed). Please update your demo and submit a new issue with it.
