### ISSUE TITLE
The [Bug Report] form loses focus and does not trigger validation

### ISSUE THREAD

**Issue by kongjiea** [ElemeFE/element#8311]
### Element UI version
2.0.4

### OS/Browsers version
谷歌

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2/](https://jsfiddle.net/mmx38qxw/2/)

### Steps to reproduce
1、点击日结按钮、 点击input获取焦点 
2、然后失去焦点

### What is Expected?
应该会有验证提示，但是却没有，  但是点击保存提交按钮却有错误提示

### What is actually happening?
应该会有验证提示，但是却没有，  但是点击保存提交按钮却有错误提示

**Comment by Leopoldthecoder** [comment]
You need to add `key` to force a re-render: https://jsfiddle.net/mmx38qxw/4/
