### ISSUE TITLE
[Bug Report] Input component with `textarea` type do not support `prepend ` and `append ` slots

### ISSUE THREAD

**Issue by walkthunder** [ElemeFE/element#8312]
### Element UI version
2.0.4

### OS/Browsers version
all

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue](https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue)

### Steps to reproduce
https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue

### What is Expected?
Input componet with `textarea` and `text` type can both insert slots like `prepend`

### What is actually happening?
Slots feat is just supported for text input, NOT for textarea. Please note it in docs or accomplish the feature

**Comment by Leopoldthecoder** [comment]
I'll update the docs.
