### ISSUE TITLE
[Bug Report] When datetimepicker use format and value-format attribute, it cannot choose date

### ISSUE THREAD

**Issue by Pochodaydayup** [ElemeFE/element#8322]
### Element UI version
2.0.4

### OS/Browsers version
ubuntu / chrome 62.0.3202.89

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pocho/gvubsfzk/](https://jsfiddle.net/pocho/gvubsfzk/)

### Steps to reproduce
1. Click the input
2. choose the date 

### What is Expected?
chose datetime as datetimepicker format and value-format attrs

### What is actually happening?
1 . The input value cannot be init as in the vue data function
2 . Cannot choose  date

**Comment by wacky6** [comment]
Your format string is wrong. Should be: `yyyy-MM-dd HH:mm`, please read the documentation
