### ISSUE TITLE
[Bug Report] Menu use with customize color and collapse does not refresh when collapsing

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#8325]
### Element UI version
2.0.4

### OS/Browsers version
mac chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/m52qrcpg/1/](https://jsfiddle.net/m52qrcpg/1/)

### Steps to reproduce
you will find the background color will not become black until you move cursor to the menu

### What is Expected?
show correct color 

### What is actually happening?
show wrong color

**Comment by Leopoldthecoder** [comment]
`background-color` 加上 `#` 吧：https://jsfiddle.net/m52qrcpg/2/ ，这个值不会被处理，直接传给 style 了。

**Comment by njleonzhang** [comment]
@Leopoldthecoder 谢谢。。。行为有点奇怪  没想到写错了。
