### ISSUE TITLE
[Bug Report] Element Table: Row-Span not working properly?

### ISSUE THREAD

**Issue by ArnoBuschmann** [ElemeFE/element#8326]
### Element UI version
2.0.4

### OS/Browsers version
Chrome Version 59.0.3071.115 

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/9/](https://jsfiddle.net/mmx38qxw/9/)

### Steps to reproduce
The Jsfiddle reproduces the problem.

### What is Expected?
When using this method to do a row span:

```javascript
     arraySpan: function({ row, column, rowIndex, columnIndex }) {
      let spanArray = [1, 1]
      console.log('Logging as expected, each cell logs one time - rowIndex: ', rowIndex, 'columnIndex: ', columnIndex)
      if (rowIndex === 0 && columnIndex === 0) {
      	console.log('Unexpected, this cell logs 4 times - rowIndex: ', rowIndex, 'columnIndex: ', columnIndex)
        spanArray = [2, 1]
      }
      return spanArray
    }
```
- I would expect, that "First cell, first row" would get a rowspan of two, so it connects/includes "first cell, second row".
- I would also expect, that the content of "first cell, second row" gets overwritten, so its content doesn't show up at all.

### What is actually happening?
Cell content starts to swap all over the table, for example "Second cell, first row" from the first column appears in the second column.

**Comment by Leopoldthecoder** [comment]
To hide a cell, you need to set its `rowspan` and `colspan` to `0`: https://jsfiddle.net/mmx38qxw/10/ . The example on our doc illustrates this.

**Comment by ArnoBuschmann** [comment]
@Leopoldthecoder Thanks a lot for the great hint, that solves the problem perfectly. Keep the good work, Element is awesome :)
