### ISSUE TITLE
关于 ElementUI DateTimePicker 日期时间选择器 的配置

### ISSUE THREAD

**Issue by vxhly** [ElemeFE/element#8327]
时间组件默认出来的是这个月和下个月，
有没有办法让它变成上个月和这个月，
在官方文档里翻了一下，没有翻到
ElementUI 版本号1.4.10
![image](https://user-images.githubusercontent.com/17906558/32884435-3e34ff84-caf5-11e7-99f1-0713c01fd6a2.png)

**Comment by wacky6** [comment]
应该要2.0才行
1.4的 default-value 对 date-range 的支持可能有问题

**Comment by vxhly** [comment]
@wacky6 1.4的文档没说清楚，看的时候看走眼了，尴尬，我试一下
