### ISSUE TITLE
[Bug Report] icon size inconsistent

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/element#8330]
### Element UI version
2.0.4

### OS/Browsers version
OS X 10.11.6 / Chrome 61.0.3163.100（正式版本） （64 位）

### Vue version
2.5.3

### Reproduction Link
[http://element-cn.eleme.io/#/zh-CN/component/alert](http://element-cn.eleme.io/#/zh-CN/component/alert)

### Steps to reproduce
图标大小不一致，比如：el-icon-error 明显比 el-icon-info 大很多

### What is Expected?
图标大小一致

### What is actually happening?
图标大小不一致

**Comment by Leopoldthecoder** [comment]
This will be fixed in the next release.

**Comment by acmeid** [comment]
Thanks.
