### ISSUE TITLE
[Bug Report] introduces CSS files or uses babel-plugin-component to report errors

### ISSUE THREAD

**Issue by ChenCheng0914** [ElemeFE/element#8333]
### Element UI version
2.0.4

### OS/Browsers version
osx / chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ChenCheng0914/forum-vue](https://github.com/ChenCheng0914/forum-vue)

### Steps to reproduce
按文档引入import ElementUI from 'element-ui'
后使用组件、css没有样式、
后来使用了import 'element-ui/lib/theme-chalk/index.css'或者babel-plugin-component的时候
报错
This dependency was not found:

element-ui/lib/theme-chalk/index.css in ./src/client/main.js
To install it, you can run: npm install --save element-ui/lib/theme-chalk/index.css

### What is Expected?
按文档引入文件后能正常使用

### What is actually happening?
按文档引入文件后报错

**Comment by Leopoldthecoder** [comment]
webpack 配置错误。见 https://github.com/ChenCheng0914/forum-vue/pull/1 和 https://github.com/ChenCheng0914/forum-vue/pull/2
