### ISSUE TITLE
When [Bug Report] tree components use check-strictly attribute, when the node is expanded, click can realize the correlation, but when the node is lazy load, select the parent node, and then load the child node, the child node will be selected

### ISSUE THREAD

**Issue by ewgcat** [ElemeFE/element#8335]
### Element UI version
1.4.9

### OS/Browsers version
mac win10  -chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/4mkez6uy/2/)

### Steps to reproduce
在<el-tree></el-tree>加上check-strictly后，选中首节点，加载后子节点皆被选中

### What is Expected?
tree组件使用check-strictly属性时，当节点全部展开时点击可以实现互不关联，但当节点为懒加载时，选中父节点后，再加载子节点，子节点   不会   被选中

### What is actually happening?
tree组件使用check-strictly属性时，当节点全部展开时点击可以实现互不关联，但当节点为懒加载时，选中父节点后，再加载子节点，子节点   会   被选中

**Comment by ewgcat** [comment]
请大神看看

**Comment by Leopoldthecoder** [comment]
请参考 https://github.com/ElemeFE/element/issues/8044
