### ISSUE TITLE
[Feature Request] el-checkbox & el-select

### ISSUE THREAD

**Issue by fyang0728** [ElemeFE/element#8338]
### Existing Component
Yes

### Component Name
1.4.9

### Description
chrome6

### How to bind data when the data is uncertain？

template

`<el-date-picker v-model="data[list.name]" type="datetime" size="small"  placeholder="选择日期" @change="(v)=>data[list.name] = v"></el-date-picker>`

js

`data() {
 return {
  data:{}
 }
}`

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
