### ISSUE TITLE
[Bug Report] The el-popover first click is not display

### ISSUE THREAD

**Issue by shanxichen** [ElemeFE/element#8344]
### Element UI version
2.0.4

### OS/Browsers version
win7

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
(http://element.eleme.io/2.0/#/zh-CN/component/popover)
1, open the issue url.
2, click the popover button (click 激活)

### What is Expected?
The popover is display for button first clcik 

### What is actually happening?
The popover is not display for button first clcik

**Comment by Leopoldthecoder** [comment]
Duplicate of #8186

**Comment by carrollcai** [comment]
i also have this problem

**Comment by shanxichen** [comment]
@carrollcai This bug has been repaired, please update it to the latest edition
