### ISSUE TITLE
[Feature Request] date selection components have no alternative function

### ISSUE THREAD

**Issue by x-manJS** [ElemeFE/element#8345]
### Existing Component
是

### Component Name
date-picker

### Description
日期选择组件没有多选的功能，希望实现以下描述：
    input 聚焦后，显示出的日期面板，能够支持选择多个可以不连续的日期，点击确定按钮后才关闭面板，并触发事件。
   如果有这功能，希望告知下

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
