### ISSUE TITLE
穿梭框在点击左侧checkbox时触发校验是否合理

### ISSUE THREAD

**Issue by 241382976** [ElemeFE/element#8346]
Element UI version

1.4.6

OS/Browsers version

Windows 10 Chrome/61.0.3163.100

Vue version

2.3.2

Reproduction Link

Steps to reproduce

form中使用穿梭框，给其添加rules校验必填项

What is Expected?

正确校验是否必填

What is actually happening?

选中左侧checkbox时就校验了，对用户不友好

期望能添加如input组件中的validateEvent props，来控制是否需要dispatch事件

**Comment by outman0503** [comment]
穿梭框这个组件问题这么多  也不知道解决  只会敷衍  这次用element  ui 就是个错误的决定  bug太多了
