### ISSUE TITLE
[Bug Report] Vue Element-ui form verifies that the parent component mounted can normally pass object into the child component, but cannot check through the subcomponents

### ISSUE THREAD

**Issue by Fangty1** [ElemeFE/element#8358]
### Element UI version
2.0.4

### OS/Browsers version
windows 7, chrome 60.0.3107.4

### Vue version
2.5.3

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
vue子组件（代码已经整理的比较简单，直接贴上了）

<template>
  <div>
    <el-form>
      <el-form-item prop="name" label="名称" :rules="[{ required: true, message: '请输入名称', trigger:'blur,change'}]">
        <el-input v-model="value.name"></el-input>
      </el-form-item>
    </el-form>
  </div>
</template>

<script>
export default {
  props: {
    value: {
      type: Object
    }
  },
  data () {
    return {}
  },
  mounted: function () {
    console.info('son mounted, name is,', this.value.name)
  },
  updated: function () {
    console.info('son updated, name is,', this.value.name)
  }
}
</script>

父组件

<template>
  <div class="wrapper">
    <div><b> TEST PAGE</b></div>
    <div>
      <bb-son v-model="bean1"/>
      <bb-son v-model="bean2"/>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      bean1: {
        name: 'name1'
      },
      bean2: {
        name: 'name2'
      }
    }
  },
  methods: {
    showConsole: function () {
      console.info('current father name is, ', this.father.name)
    }
  },
  mounted: function () {
    console.info('father mounted')
    this.bean2.name = 'bbb'
  },
  updated: function () {
    console.info('father updated')
  }
}
</script>

组件注册js:

import BBSon from './bbc/BBSon'
Vue.component('bb-son', BBSon)

### What is Expected?
父组件被访问时，同时显示 连个子组件， 但第二个 校验失败 （提示必须输入）， 实际上组件也是有值的。

### What is actually happening?
null

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/11/
