### ISSUE TITLE
[Feature Request] Hope messageBox can offer a method to close

### ISSUE THREAD

**Issue by chenxxzhe** [ElemeFE/element#8360]
### Existing Component
是

### Component Name
messageBox

### Description
如果在打开了messageBox 之后，路由后退，messageBox会依然存在，希望提供一个方法在路由守卫里关闭它

**Comment by Leopoldthecoder** [comment]
After #8050, you can close it by `this.$msgbox.close()` or `MessageBox.close()`.

**Comment by ultraN** [comment]
Please write this solution into official document! I was looking for this for two days!
