### ISSUE TITLE
[Bug Report] After tree sets the isLeaf of defaultProps to function, updateKeyChildren will not refresh the node state

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8367]
### Element UI version
2.0.5

### OS/Browsers version
win10/chrome 62

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/ggf9btr1/](https://jsfiddle.net/ggf9btr1/)

### Steps to reproduce
1、defaultProps设置isLeaf:data=>data.isLeaf
2、根节点数据设置isLeaf为true
3、通过updateKeyChildren更新根节点

### What is Expected?
根节点的isLeaf应改为false，同时显示子节点

### What is actually happening?
根节点实际上有了子节点，但是因为isLeaf还是true，并不会展示子节点

**Comment by ayiaq1** [comment]
loadNode1(node, resolve) {
        if (node.level === 0) {
          return resolve([{ name: 'a' }]);
        }
        if (node.level > 1) return resolve([]);

        setTimeout(() => {
          const data = [{
            name: 'b',
            leaf: true
          }, {
            name: 'c',
            leaf: false
          }];

          resolve(data);
        }, 500);
      }
[https://jsfiddle.net/htzxkaLp/2/](url)
C没有子节点，但是仍然有三角形图标，反而b没有了 @element-bot
