### ISSUE TITLE
[Bug Report] el-table-column with show-overflow-tooltip and fixed UI error

### ISSUE THREAD

**Issue by tym1193** [ElemeFE/element#8373]
### Element UI version
2.0.5

### OS/Browsers version
Win10,Chrome 62

### Vue version
2.5.5

### Reproduction Link
[https://jsfiddle.net/qf1erh0o/](https://jsfiddle.net/qf1erh0o/)

### Steps to reproduce
纵向滚动至右侧，表头错位，1920*1080重现

### What is Expected?
表头正常

### What is actually happening?
滚动到右侧表头错位

**Comment by tym1193** [comment]
使用win10笔记本电脑默认的125%缩放比例，1920*1080

**Comment by Leopoldthecoder** [comment]
Same cause as #7833. We'll update in #7833.
