### ISSUE TITLE
[Bug Report] in electron-vue tooltip and menu collapse after the menu item tooltip can not be displayed normally

### ISSUE THREAD

**Issue by lichnow** [ElemeFE/element#8374]
### Element UI version
0.1.0

### OS/Browsers version
macos 10.13   electron v1.7.9

### Vue version
2.5.5

### Reproduction Link
[https://jsfiddle.net/lichnow/xkz14fz3/](https://jsfiddle.net/lichnow/xkz14fz3/)

### Steps to reproduce
使用`普通spa`(vue-cli生成的webpack模板编译所得)可以正常显示tooltip和折叠菜单的tooltip
而使用`vue-electron`生成的页面则无法正确显示tooltip,如下图
![](http://ozert6ei6.bkt.clouddn.com/2017-11-18-084715.png)

### What is Expected?
在`vue-electron`下能正确显示tooltip与折叠菜单的tooltip

### What is actually happening?
在鼠标hover时只有按钮会变色,tooltip不显示

**Comment by baiyaaaaa** [comment]
reproduction link is not about the issue.can't not reproduct the problem
