### ISSUE TITLE
[Feature Request] export global: `PopupManager.nextZIndex()` in the ability to access

### ISSUE THREAD

**Issue by yoyo837** [ElemeFE/element#8375]
### Existing Component
Yes

### Component Name
popup

### Description
Hope to open up the `PopupManager.nextZIndex()` in the ability to access, providing mixed with other UI library like ` mint-ui` unified maintenance of the possibility of `z-index`.

希望可以全局导出`PopupManager`或者`PopupManager.nextZIndex()`供使用，当存在多个ui库混用的情况(不讨论是否合理)，弹出层/遮罩等z-index需要统一维护。

ssr: SyntaxError: Unexpected token import.
ssr nuxt.js下不能正常导入PopupManager来使用

**Comment by Leopoldthecoder** [comment]
直接引入 `element-ui/src/utils/popup/popup-manager.js` 就可以。
`Unexpected token import` 是因为需要用 babel 处理一下这个文件。

**Comment by yoyo837** [comment]
我使用了`import PopupManager from 'element-ui/lib/utils/popup/popup-manager'`可以正常工作，且`element-ui`其他组件的z-index可以相接上。

**Comment by flybbjcs70** [comment]
CDN引用就不行了吧。
