### ISSUE TITLE
[Feature Request] Form Validations

### ISSUE THREAD

**Issue by leonardocaldas** [ElemeFE/element#8380]
### Existing Component
Yes

### Component Name
Form

### Description
Add a specific area in the documentation for the form validations rules. Today we have to look at the form examples to try to find what kind of validations are available, which is very bad because we cant be sure if all available validations are in the examples.

**Comment by yyqqing** [comment]
并且希望增加 Upload 组件的校验样例

**Comment by EricJin987** [comment]
@leonardocaldas I think they are using [async-validator](https://github.com/yiminghe/async-validator), you can check it.
