### ISSUE TITLE
Name is null when the name property is set by [Feature Request] select to submit the form

### ISSUE THREAD

**Issue by cntaoyu** [ElemeFE/element#8382]
### Existing Component
是

### Component Name
select

### Description
el-select multiple设置name="market",选中多个值提交表单后收到的market是空字符串
在线预览：https://jsfiddle.net/cntaoyu/okzrq587/1/

另外表格是否有导出excel功能的计划？

**Comment by Leopoldthecoder** [comment]
不是 bug，多选 Select 中的 `<input>` 元素会一直保持为空，因此用 FormData 来取值的话也就是空值了。这里自己 append 一下吧。

**Comment by zyc999** [comment]
wow
