### ISSUE TITLE
[Bug Report][El-Upload] Image stream not sent

### ISSUE THREAD

**Issue by Elfayer** [ElemeFE/element#8384]
### Element UI version
2.0.5

### OS/Browsers version
Windows 7 / Chrome 61

### Vue version
2.5.6

### Reproduction Link
http://element.eleme.io/#/en-US/component/upload

### Steps to reproduce
Try to upload any file, you will see the stream in the request payload is always empty.
I know the doc is pointing to a fake API, but still, the request sends no data, and on my application it behaves the same.
I receive nothing on my server side. The payload is empty of any data. Am I doing something wrong?

![2017-11-20 11_12_36-clipboard](https://user-images.githubusercontent.com/15869149/33000549-d507441c-cde3-11e7-8bfc-ce541c842e70.png)

Template:
```html
<el-upload
  class="image-uploader"
  ref="imageUploader"
  action="http://localhost:5000/images/"
  :auto-upload="false"
  :file-list="form.values.image"
  :limit="1"
  accept=".jpg, .jpeg, .png"
  list-type="picture">
  <el-button slot="trigger" size="small" type="primary">select file</el-button>
  <div slot="tip">jpg/png files with a size less than 500kb</div>
</el-upload>
```

On submitting:
```js
this.$refs.imageUploader.submit();
```

### What is Expected?
The file to be send.

### What is actually happening?
Nothing is sent.

**Comment by Leopoldthecoder** [comment]
Your code works fine for me (with a real upload API). Plus, the screenshot actually proves that the request is correct:
![image](https://user-images.githubusercontent.com/10095631/33055520-2c084d1a-cebb-11e7-9e36-4b3fc987cdb1.png)

So please check your server side code.

**Comment by ggmon** [comment]
It doesn't send data stream, I have the same problem
