### ISSUE TITLE
When [Bug Report] el-form verifies multiple rules, the specified trigger does not work properly, and trigger is not specified

### ISSUE THREAD

**Issue by Fangty1** [ElemeFE/element#8386]
### Element UI version
2.0.4

### OS/Browsers version
windows chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/cfj9qrk6/](https://jsfiddle.net/cfj9qrk6/)

### Steps to reproduce
https://jsfiddle.net/cfj9qrk6/

### What is Expected?
代码：
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui/lib/index.js"></script>
<div id="app">
        <el-form :model="bean1">
          <el-form-item prop="value" label="输入数字时不能正常通过校验" 
          :rules="[
          { required: true, message: '必须输入', trigger:'change'},  
          { type: 'number', message: '需要为数值', trigger:'change'}]">
              <el-input v-model.number="bean1.value"></el-input>
          </el-form-item>
        </el-form>
 </div>

var Main = {
  data () {
    return {
      bean1: {
        value: 'str'
      }
    }
  }
}
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')

### What is actually happening?
https://jsfiddle.net/cfj9qrk6/

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8400
