### ISSUE TITLE
[Feature Request] DateTimePicker feature request(①Time panel without click ②Add "step" parameter)

### ISSUE THREAD

**Issue by sonmunehiro** [ElemeFE/element#8390]
### Existing Component
Yes

### Component Name
DateTimePicker (el-date-picker)

### Description
(1)
DateTimePicker 日期时间选择器可以设计成不用另外点击就能选择时间吗?
时间选择器加在左右两边，如图片所示。
![2017-11-20 16 06 07](https://user-images.githubusercontent.com/25984670/33006709-c23928e8-ce0e-11e7-8a40-3b479000b9d8.png)

(2)
可以加入step(间隔时间)参数吗？
在选择时间的时候，会只有选择00、15、30、45分的需求

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by lisiyizu** [comment]
> Sorry, we have no plan to support this.

真没搞懂一个非常实际的需求，为啥不支持。DateTimePicker 设置 yyyy-MM-dd HH:mm ， picker-options: { start: '08:00', step: '00:10',  end: '23:30' } ，这个需求有那么难做吗？

**Comment by Cloud33** [comment]
很好的需求点，求支持
