### ISSUE TITLE
[Bug Report] CheckboxButton not found

### ISSUE THREAD

**Issue by lmxdawn** [ElemeFE/element#8392]
### Element UI version
0.1.0

### OS/Browsers version
Win、Mac

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
按照文档来的，实现按需加载，编译的时候直接 eslint 就检查出错，看了下是因为 CheckboxButton 这个组件找不到，其它的都能找到，错误信息：
http://eslint.org/docs/rules/no-unused-vars  'CheckboxButton' is defined but never used

### What is Expected?
编译成功

### What is actually happening?
编译出错

**Comment by sonmunehiro** [comment]
你difine了CheckboxButton，但没有使用它

**Comment by lmxdawn** [comment]
![tim 20171120164714](https://user-images.githubusercontent.com/21293193/33009922-64b68328-ce13-11e7-8ba8-ba2d7d5bd116.png)  编译器就直接报错了，其它组件都能正常
：
![tim 20171120165507](https://user-images.githubusercontent.com/21293193/33009970-9bd3b006-ce13-11e7-9f36-655e82ac337b.png)

**Comment by sonmunehiro** [comment]
少了`Vue.use(CheckboxButton)`

**Comment by lmxdawn** [comment]
恩，没注意到，复制的你们官方的。。。

**Comment by sonmunehiro** [comment]
我不是官方。。

**Comment by lmxdawn** [comment]
感谢，应该是官方文档忘记写了，

**Comment by Leopoldthecoder** [comment]
I'll update the docs.
