### ISSUE TITLE
[Bug Report] el-input  @keypress.native="function" 不能阻止用户输入

### ISSUE THREAD

**Issue by wehnhew** [ElemeFE/element#8394]
### Element UI version
2.0.5

### OS/Browsers version
win 10 / chrome 62 

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/zg6mfrmn/](https://jsfiddle.net/zg6mfrmn/)

### Steps to reproduce
文本框输入数据时

### What is Expected?
@keypress.native返回fase阻止用户输入

### What is actually happening?
@keypress.native返回fase不能阻止用户输入

**Comment by Leopoldthecoder** [comment]
封装的组件和原生组件会有一些不一致，建议绕一下：https://jsfiddle.net/zg6mfrmn/1/
