### ISSUE TITLE
[Bug Report] [Table] Unexpected horizontal scrollbar appears when setting the data prop of a bordered `Table` component asynchronously

### ISSUE THREAD

**Issue by blooddrunk** [ElemeFE/element#8395]
### Element UI version
2.0.5

### OS/Browsers version
OSX Windows / Chrome 62

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/jelinenaro/twmn0car/7/](https://jsfiddle.net/jelinenaro/twmn0car/7/)

### Steps to reproduce
update `data` prop of `Table` component with `border` prop set to true after it's mounted.

### What is Expected?
No unexpected  horizontal scrollbar appears

### What is actually happening?
An unexpected horizontal scrollbar appears unless
 * set `border` prop to false
 * call `doLayout` function explicitly after data is set

**Comment by Leopoldthecoder** [comment]
Yes, that's why we exposed `doLayout` to users in 2.0.5. For now you can use `doLayout` after data is fetched, and we'll see if we can find a better solution.
