### ISSUE TITLE
[Bug Report] table in the right aligned case, the sorting icon is blocked

### ISSUE THREAD

**Issue by pz25925** [ElemeFE/element#8397]
### Element UI version
2.0.5

### OS/Browsers version
windows 64 / chrome

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/15/](https://jsfiddle.net/mmx38qxw/15/)

### Steps to reproduce
1.设定表格列居右对齐.

2.设定可排序

### What is Expected?
排序图标正常显示

### What is actually happening?
排序图标被遮挡

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8405
