### ISSUE TITLE
[Bug Report] Something wrong when import components on demand with typescript

### ISSUE THREAD

**Issue by Simonalia** [ElemeFE/element#8398]
### Element UI version
2.0.5

### OS/Browsers version
Chrome 62.0

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Use Vue@2.6.5   Typescript@2.6.1 to set up project,  import  element-ui components on demand.

### What is Expected?
1. import the corresponding css automatically
2. when build, there should only include the components imported on demand

### What is actually happening?
1. no css at all
2. packaged the whole element-ui

**Comment by Leopoldthecoder** [comment]
Could see if #8068 helps?

**Comment by Simonalia** [comment]
@Leopoldthecoder No, the problem mentioned in #8068 has fixed in 2.0.5，but there are others

**Comment by shhdgit** [comment]
Can element-ui import components on demand without babel-plugin-component, but only with ts-loader?
