### ISSUE TITLE
Notification单独引入错误

### ISSUE THREAD

**Issue by hizhengfu** [ElemeFE/element#84]
### Vue version

单独导入引入Notification时
`import { Notification } from 'element-ui';`
会在此位置报错
`_this.$el.parentNode.removeChild(_this.$el);`
出错位置为/notification/src/main.vue文件49行

<img width="540" alt="qq20160919-0 2x" src="https://cloud.githubusercontent.com/assets/446359/18625831/b3a75222-7e83-11e6-9257-ed778fe8cf7b.png">

**Comment by Leopoldthecoder** [comment]
我这边试了一下，没有报错。所以请提供你的 vue 版本、element 版本，以及使用 Notification 的代码片段

**Comment by hizhengfu** [comment]
相关资源版本：
`"element-ui": "^1.0.0-rc.3",
    "vue": "^2.0.0-rc.6",
    "vue-resource": "^1.0.1",
    "vue-router": "^2.0.0-rc.5"
`
可能是我这用法的问题

`import { Notification } from 'element-ui';`

在ajax中增加了一个全局的逻辑，如果返回数据有需要提醒的提示信息就显示出来，不需要界面单独处理

`
Vue.http.interceptors.push((request, next) => {
            next((response) => {
            var data = response.data;
            if (data && data.message) {
                Notification({
                    title: '通知',
                    duration: 8,
                    message: data.message,
                    type: data.type || 'info'
                });
            }
        });
    }
});
`

**Comment by Leopoldthecoder** [comment]
`duration` 的单位是毫秒，改成 8000 再试试

**Comment by hizhengfu** [comment]
ok了，这个没仔细看文档，以为和vue-desktop是一致的。感谢
