### ISSUE TITLE
官方网站打不开了

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#840]
每次去官网看文档都很慢，能不能有离线的文档？

**Comment by QingWei-Li** [comment]
项目 clone 后，切到 gh-pages 分支，你就能获得一份离线文档

**Comment by qiuyaofan** [comment]
http://element-cn.eleme.io/#/zh-CN 这个可以

**Comment by bygsn** [comment]
> 项目 clone 后，切到 gh-pages 分支，你就能获得一份离线文档

请问怎么运行呀 我点击这个分支下的index.html文件 页面加载不出来
![image](https://github.com/ElemeFE/element/assets/51038773/3b7699ce-94ba-4b05-a757-dab88d111d68)
![image](https://github.com/ElemeFE/element/assets/51038773/602cb638-53f3-4503-8509-2770b035ee21)
