### ISSUE TITLE
[Bug Report]  input value small than min value, input value dose not be corrected

### ISSUE THREAD

**Issue by decadef20** [ElemeFE/element#8401]
### Element UI version
1.4.9

### OS/Browsers version
Version 60.0.3112.90 (Official Build) (64-bit)

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/741/](https://jsfiddle.net/pj71jkyw/741/)

### Steps to reproduce
Enter 0 or small then 1  multiple times

### What is Expected?
input value keep unchanged

### What is actually happening?
input value should be corrected.

If this is unexpected, I would like to PR and  I have fixed it and added  test case.

**Comment by Leopoldthecoder** [comment]
PR welcome.
