### ISSUE TITLE
[Bug Report] el-select component keydown.down and keydown.up event bubble

### ISSUE THREAD

**Issue by JackyCxq** [ElemeFE/element#8404]
### Element UI version
2.0.3

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/tgzu34p5/](https://jsfiddle.net/tgzu34p5/)

### Steps to reproduce
1 when el-select in el-tabs label
2 change el-select option
3 not change el-select option, but change current tab

### What is Expected?
1 el-select component keydown.down and keydown.up event stop bubble
2 el-tabs
   When arranged horizontally, only support keydown.left and keydown.right event.
   When arranged longitudinally, only support keydown.down and keydown.up event.

### What is actually happening?
el-select keydown.down and up event bubble.

**Comment by Leopoldthecoder** [comment]
Why do you use a Select as Tab label?

**Comment by JackyCxq** [comment]
In addition to some default tabs, we also allow the user to aggregate the display based on existing fields，This problem occurred after upgrading to element2.0

**Comment by vongo21** [comment]
element2.0升级后，整套视觉体验跟交互感觉跟另外一套比较火的组件差不多，基于对大团队的信赖就定了element这个组件框架。但是在 tabs 组件上遇到的问题，比如默认监听左右、上下按键的事件，跟在其他组件配合使用的过程中就踩坑了，希望这块的监听事件的方式以及对外暴露的接口可以再优化下 @Leopoldthecoder

**Comment by yanglming** [comment]
@Leopoldthecoder 补充一下 @JackyCxq 的问题：我们在一些场景中使用了tabs组件的可编辑添加功能，因为业务需求需要使用select作为定向编辑输入，这时候select选项的上下按键监听和tabs的冲突了。在这种场景中我们使用的是横向tabs，理论上不应该对上下按键做监听，而且现在没有任何参数让我们关闭这个监听。
另外，即使是在竖向的tabs中对上下按键做监听在有页面滚动的情况下也是有问题的（会使页面也一起滚动）。建议对上下键监听这个问题可以衡量一下其必要性，或提供选项对其进行禁用，亦或是默认无按键监听但可以设置参数打开。谢谢。

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/pull/8452
