### ISSUE TITLE
DatePicker 和 DateTimePicker 为什么默认不能返回yyyy-MM-dd 和 yyyy-mm-dd hh:mm:ss

### ISSUE THREAD

**Issue by zphtown** [ElemeFE/element#8409]
DatePicker 和 DateTimePicker 为什么默认不能返回yyyy-MM-dd 和 yyyy-mm-dd hh:mm:ss，
返回是Thu Oct 30 1997 00:00:00 GMT+0800 (中国标准时间)这样的，拿到手上还得转成yyyy-MM-dd或者yy-mm-dd hh:mm:ss

**Comment by Leopoldthecoder** [comment]
Use `value-format`.
