### ISSUE TITLE
树形控件，能不能增加菜单在加载时候某些菜单默认选中的功能

### ISSUE THREAD

**Issue by zhengldg** [ElemeFE/element#841]
树形控件，能不能增加菜单在加载时候某些菜单默认选中的功能

**Comment by furybean** [comment]
1.0.1 中增加了 nodeKey 与 defaultCheckedKeys 属性，应该可以满足你的这个需求。

**Comment by ilovezy** [comment]
defaultCheckedKeys 如果默认选中了父节点，会把所有子节点都给选中，但是我在最开始设置权限的时候，只是选中了子节点中的其中一个，保存到后台的时候后天要求父节点和子节点的 id都要传，
这样的话，返回回来 设置 defaultCheckedKeys的时候，我希望只有选中的那一个子节点被选中，而不是该父节点下面所有的子节点都选中
