### ISSUE TITLE
[Bug Report] Select selects exceptions

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8410]
### Element UI version
2.0.5

### OS/Browsers version
win10/chrome62

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/ous5h6um/4/](https://jsfiddle.net/ous5h6um/4/)

### Steps to reproduce
点击选择项

### What is Expected?
选中所点的项

### What is actually happening?
选中了所有的项，如果options里面的数据{a:"1",b:"xxx"}改为{value:"1",label:"xxx"}就是正常的

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/ous5h6um/5/

![image](https://user-images.githubusercontent.com/10095631/33060722-2dc030f0-ced4-11e7-8731-cf844f53325a.png)

**Comment by gaecfov** [comment]
多谢，看文档以为是Option需要绑定:key，原来是要select要绑定，多谢
