### ISSUE TITLE
Custom theme color for [Bug Report]

### ISSUE THREAD

**Issue by penxu** [ElemeFE/element#8413]
### Element UI version
2.0.5

### OS/Browsers version
windows/chrome

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
按照官网来编辑 element-variables.scss 文件来修改主题色，再引进项目根本没有用，如果不引进编译好的css文件，所有样式都会没有了。引进编号好的CSS文件，主题色只能是原来的

### What is Expected?
修改element-variables.scss 能替换主题色

### What is actually happening?
修改element-variables.scss 不能替换主题色

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly. You can minify your project and put it on GitHub.
