### ISSUE TITLE
[Bug Report] Form status-icon not work on select when blur

### ISSUE THREAD

**Issue by wangduanduan** [ElemeFE/element#8414]
### Element UI version
2.0.4

### OS/Browsers version
Mac / Chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://codepen.io/wangduanduan/pen/JOpqaW?editors=1010](https://codepen.io/wangduanduan/pen/JOpqaW?editors=1010)

### Steps to reproduce
1. 选择下拉框的一个值，然后鼠标点击其他地方

### What is Expected?
希望下拉框 status-icon的标记变成成功状态

### What is actually happening?
下拉框的status-icon还是错误的状态

**Comment by Leopoldthecoder** [comment]
Select 组件仅支持 `trigger: 'change'`
