### ISSUE TITLE
[Bug Report] [el-table] el-table-column 'hover-row' class error when expend column Embed el-table

### ISSUE THREAD

**Issue by ciwyaitd** [ElemeFE/element#8416]
### Element UI version
2.0.5

### OS/Browsers version
os x 10.11.6 / chrome 62.0.3202.94

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/ciwyaitd/yqpeco6r/3/](https://jsfiddle.net/ciwyaitd/yqpeco6r/3/)

### Steps to reproduce
1. expended first tr.
2. hover the least tr.

### What is Expected?
'hover-row' class set in current hover tr.

### What is actually happening?
'hover-row' class set in wrong tr.

**Comment by Leopoldthecoder** [comment]
#8423
