### ISSUE TITLE
[Bug Report] Dialog cannot work

### ISSUE THREAD

**Issue by tingrun919** [ElemeFE/element#8419]
### Element UI version
2.0.5

### OS/Browsers version
Chrome

### Vue version
2.5.7

### Reproduction Link
[http://jsfiddle.net/24yz1unb/](http://jsfiddle.net/24yz1unb/)

### Steps to reproduce
1、点击dialog弹出按钮
2、dialogVisible即为dialog绑定的model设置为true
3、显示dialog

### What is Expected?
dialogVisible改为ture，并且显示dialog

### What is actually happening?
dialogVisible通过watch发现已经修改，但是并没有显示dialog

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/33065890-c56c1d50-cee4-11e7-8910-50acd900c117.png)
