### ISSUE TITLE
[Bug Report] horizontal scrollbar appears in Select dropdown when ::-webkit-scrollbar width is defined.

### ISSUE THREAD

**Issue by wuyiw** [ElemeFE/element#8421]
### Element UI version
2.0.5

### OS/Browsers version
windows 10/chrome 64 & macOS/safari 10

### Vue version
2.5.7

### Reproduction Link
[http://jsfiddle.net/nzjacrb5/7/](http://jsfiddle.net/nzjacrb5/7/)

### Steps to reproduce
check the link

### What is Expected?
no horizontal scrollbar in select dropdown

### What is actually happening?
horizontal scrollbar appears

**Comment by Leopoldthecoder** [comment]
Select uses a custom scrollbar, so please avoid styling it.

**Comment by wuyiw** [comment]
actually i'm trying to style the scrollbar of the page, not the dropdown...
by your inspiration, css below solves the problem:
`
:not(.el-scrollbar__wrap)::-webkit-scrollbar {
  // scrollbar styles
}
`
thx
