### ISSUE TITLE
[Feature Request] can not get the halfCheck nodes?

### ISSUE THREAD

**Issue by xyhxyw** [ElemeFE/element#8422]
### Existing Component
Yes

### Component Name
Tree

### Description
if we have a Multi-level tree width checkbox,we can not get the halfCheck nodes. i konw we can resolve it with this [example](https://jsfiddle.net/leopoldthecuber/yu2me25j/),but it's not convenient.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
