### ISSUE TITLE
[Bug Report] When under dev mode and customize theme with scss variables,  el-button's styles will be imported multiple  times

### ISSUE THREAD

**Issue by feichao** [ElemeFE/element#8424]
### Element UI version
2.0.5

### OS/Browsers version
Mac OS 10.12.6 / Chrome 62.0.3202.94

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
just define custom variables and import original element-ui styles:

@import '_element-variables';

@import './node_modules/element-ui/packages/theme-chalk/src/index';

### What is Expected?
el-button's styles should be imported only once

### What is actually happening?
el-button's styles are imported multiple times

**From Element-UI source code: index.scss will import button.scss, but some components will also import button.scss (for example: dropdown.scss, message-box.scss ...), cause so.**

**Comment by feichao** [comment]
![muitiple_styles](https://user-images.githubusercontent.com/11988943/33070902-894cafbe-cef4-11e7-96f2-dc9fd9e6080a.jpg)

**Comment by diemah77** [comment]
Same here.

**Comment by Leopoldthecoder** [comment]
Some of the components are mutually dependent, so this seems inevitable. And in production all duplicated styles will be removed.

**Comment by feichao** [comment]
@Leopoldthecoder Maybe it's a design problem... and it's still a bug.
