### ISSUE TITLE
[Bug Report] Attribute `align-center` of `el-steps` has not been implemented?

### ISSUE THREAD

**Issue by chinesedfan** [ElemeFE/element#8425]
### Element UI version
2.0.5

### OS/Browsers version
OSX 10.12.6

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
Attribute `align-center` of `el-steps` is defined but not be used anywhere in [steps.vue](https://github.com/ElemeFE/element/blob/dev/packages/steps/src/steps.vue).

### What is Expected?
As the document described.

### What is actually happening?
Nothing happens.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/steps/src/step.vue#L96
