### ISSUE TITLE
[Bug Report] Attribute `route` of `el-menu-item` has not been implemented?

### ISSUE THREAD

**Issue by chinesedfan** [ElemeFE/element#8426]
### Element UI version
2.0.5

### OS/Browsers version
OSX 10.12.6

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
Attribute `route` of `el-menu-item` is defined but not be used anywhere in [menu-item.vue](https://github.com/ElemeFE/element/blob/dev/packages/menu/src/menu-item.vue).

### What is Expected?
As the document described. By the way, concrete examples of `route` structure is also needed. New users is hard to know what `route` means.

### What is actually happening?
Nothing happens.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/blob/dev/packages/menu/src/menu.vue#L246
