### ISSUE TITLE
[Bug Report] Select selector component radio custom filter, after selecting an option, you can't choose other options

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#8432]
### Element UI version
1.4.10

### OS/Browsers version
Chrome

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/17/](https://jsfiddle.net/mmx38qxw/17/)

### Steps to reproduce
先选一个选项，然后再次点击

### What is Expected?
可以选择其它所有选项

### What is actually happening?
只出来了一个选项

**Comment by Leopoldthecoder** [comment]
具体场景是？看上去你期望的行为就是 Select 的默认行为。

**Comment by LastHeaven** [comment]
官方自带的例子是选择一个之后，继续选择可以选其它选项，但是换成自定义的选完之后就只能选一个了。
有的时候不止是中文搜索，还需要加上拼音搜索，所以不能直接使用官方默认的搜索方式。

**Comment by LastHeaven** [comment]
虽然可以通过其他手段达到和官方例子一样的目的，比如监听visible-change事件，让选项显示的时候使query=''，但是我觉得这是一个不优雅的解决方案

**Comment by LastHeaven** [comment]
另外1.4.10版本官方例子中的可搜索下拉框，在选完之后，弹框会先由多个选项变成1个最后再消失，在视觉上感觉不是很好，估计是同一个原因导致的。

**Comment by wacky6** [comment]
要实现你这个情景的filter-method的话，确实要在选定以后把query清掉。

**Comment by wacky6** [comment]
当然，从组件 API 的角度上，我大概能了解你的意思。

Select 的 query（用户输入）应该作为内部状态，用户提供的 filter-method 应该作为一个判断方法（predicate），决定某个 option 是否应该显示（返回true/false）。当然还要考虑 filter-method 为异步的情况，比如你使用的拼音搜索库是异步的。目前 filter-method 的设计容许最大的灵活性。

---

取决于对组件化 / 语义化的理解：Select 应不应该根据自己的状态去控制子节点（Option）的状态。答案为是或者否有各自的好处和限制。

是：严格意义上，破坏了组件的封装，Select 不应该隐含地影响除了自己以外的节点；……
否：API 看起来 / 用起来不是那么爽；……

---

**Comment by LastHeaven** [comment]
@wacky6 
https://jsfiddle.net/mmx38qxw/40/
可以看到下拉框为多选的时候query是会被清空的。
<hr>
按照例子https://jsfiddle.net/mmx38qxw/41/
你输入的是双
但是当你选择‘双皮奶’选项之后,再点开下拉框query会变成双皮奶
我感觉选择之后由组件内部清空query并不会影响其灵活性，因为选择之后还需要要保留query的场景太少。就算需要保留query，也能通过添加额外代码去实现。
如果实在是不想去修改原有设计，是否能加上一个属性，当这个属性为true时，选择完之后清空query？
