### ISSUE TITLE
[Bug Report] table inline nesting select component

### ISSUE THREAD

**Issue by netcore-jroger** [ElemeFE/element#8434]
### Element UI version
2.0.5

### OS/Browsers version
Win 10 x64, 62.0.3202.94（正式版本） （64 位）

### Vue version
2.5.4

### Reproduction Link
[http://jsfiddle.net/ohbvk64w/8/](http://jsfiddle.net/ohbvk64w/8/)

### Steps to reproduce
1. open chrome-dev tool. switch `console` panel.
2. chose any `select` component and select an item. Operate at least two `select` components
3. always print 'change index: 3'

### What is Expected?
print success index number.

### What is actually happening?
Always displays the index of the last row.

**Comment by LastHeaven** [comment]
不要在一个数组中使用ref
Don't use ref in an Array.
你能像下面这样使用
You can use like this
http://jsfiddle.net/1oq8u8sk/1/

**Comment by netcore-jroger** [comment]
@LastHeaven thanks for your help! this issue ware resolved.
