### ISSUE TITLE
[Bug Report] dialog close button does not go before-close, call dialog and call messageBox will appear flash screen phenomenon

### ISSUE THREAD

**Issue by KnorienChang** [ElemeFE/element#8435]
### Element UI version
2.0.5

### OS/Browsers version
OS WINDOWS10 1709 
Browser Version Chrome 62.0.3202.94 (Official Build) (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Knorien/0jso65Lk/](https://jsfiddle.net/Knorien/0jso65Lk/)

### Steps to reproduce
点击取消按钮关闭弹窗并不走before-close这个钩子。messageBox就不提供链接了，我在自己的项目中调用确实是因为调用而出现了闪屏但是在jsfiddle中却没法复现，查看了许久是因为动态计算z-index的时候，还有messageBox显示动画的.3s导致的，具体没时间去研究。

### What is Expected?
关闭前都走before-close这个钩子，因为dialog的重置验证好坑啊，需要在before-close里做重置验证

### What is actually happening?
只有按钮取消不走before-close钩子，ESC和点击modal都能实现通过before-close

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/33129747-fb88801c-cfcb-11e7-9c81-2298cda6de93.png)
