### ISSUE TITLE
[Bug Report] DatePicker component, select the date / time after the @change parameter is undefined; set default-value invalid

### ISSUE THREAD

**Issue by ervinewell** [ElemeFE/element#8437]
### Element UI version
2.0.2

### OS/Browsers version
macOS Sierra 10.12.6 (16G1036) google chrome  62.0.3202.94 （64 位）

### Vue version
2.5.2

### Reproduction Link
[http://jsbin.com/jihimicuba/edit?html,console,output](http://jsbin.com/jihimicuba/edit?html,console,output)

### Steps to reproduce
涉及组件：DatePicker
点击选择时间后，通过@change事件获取设置的value值，并通过default-value属性回传给组件

### What is Expected?
@change事件的参数为当前设置的时间；设置default-value后，组件显示设置的时间

### What is actually happening?
@change时间的参数打印结果为undefined；设置default-value不生效。

**Comment by wacky6** [comment]
you need to use v-model, or bind value to date picker

**Comment by ervinewell** [comment]
@wacky6 
I use 'render' function to instantiate the component, which doesn't support v-model, and DatePicker doesn't have 'value' property.

**Comment by wacky6** [comment]
You should handle `input` event, whose handler should update the bounded value. (By vue convention). So it's better to just use `v-model`.

In addition, you should use Date objects for bounded value, or use `value-format` to specify a string format.

Please note: In the future, components may only respond to its bounded value. Using without `v-model` or `@input`+`:value` will **not** change component's visible states.

**Comment by ervinewell** [comment]
@wacky6 
Thanks for your answering. It'll help a lot. Have a good day.
