### ISSUE TITLE
[Feature Request] Slider slider hopes to support the selection of multiple range

### ISSUE THREAD

**Issue by seamanm** [ElemeFE/element#8438]
### Existing Component
是

### Component Name
Slider 滑块

### Description
比如现在是从0到100，用户需要选择10到20，30到50，80到86，88到99等多个range。

**Comment by LastHeaven** [comment]
就像这样？？如果是的话，我只能说能不能好好看文档
https://jsfiddle.net/8kkbtfys/

**Comment by Leopoldthecoder** [comment]
@LastHeaven 并不是这个意思，指的是在同一个 Slider 中选择多个范围。
@seamanm 不是一个很常见的需求，应该不会支持。
