### ISSUE TITLE
[Feature Request] Make table-column "sortable" and ":filter" icons position variable

### ISSUE THREAD

**Issue by Fer17** [ElemeFE/element#8439]
### Existing Component
Yes

### Component Name
table-column

### Description
I've searched (without success) for a way to select the icon position (both for "sortable" and ":filters") in table columns. Just now they seems to be fixed to the right but it could be great to allow them optionally to the left. That's necessary because if you attach "sortable" and ":filters" together in the same column they are mixed in a not very useful way. Thank you in advance.

**Comment by Leopoldthecoder** [comment]
`sortable` and `filters` icons misplacement is a bug of 2.0.5 and will be fixed in 2.0.6.
