### ISSUE TITLE
IE11 Error 对象不支持“remove”属性或方法

### ISSUE THREAD

**Issue by cycold** [ElemeFE/element#844]
version: 1.0.0.rc8

chrome ok

![default](https://cloud.githubusercontent.com/assets/2446601/20028451/d0de3ee2-a36c-11e6-9fae-5e88cabf530c.PNG)

**Comment by reverland** [comment]
这是哪个页面

**Comment by QingWei-Li** [comment]
fixed via https://github.com/ElemeFE/element/pull/823
