### ISSUE TITLE
[Bug Report] Form form numeric type verification only verifies that the initial letter is not numeric

### ISSUE THREAD

**Issue by mhy-web** [ElemeFE/element#8443]
### Element UI version
2.0.5

### OS/Browsers version
Mac/Google Chrome 版本 62.0.3202.94（正式版本

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/du2fxLdd/](https://jsfiddle.net/du2fxLdd/)
### Steps to reproduce
依次输入“3 DDD@#饿了”

### What is Expected?
期待输入非数字字符时报错

### What is actually happening?
仅首字符为数字时报错

**Comment by mhy-web** [comment]
ok

**Comment by LastHeaven** [comment]
v-model.number会自动把数字+字符（Sting类型）的情况转为数字（Number类型）；
所以不建议使用v-model.number，但是使用v-model的话，因为输入的是（Sting类型），用默认的数字校验不会通过。
这里有至少4种方式解决这个问题
1.使用v-model+自己写校验函数
2.不让用户输入[0-9.]之外的东西，这种方式比较麻烦，因为要判断小数点的情况
3.把.number这个bug提交到vue的官方issue，然后等
4.等待element官方改掉这个数字校验的BUG

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/5805
