### ISSUE TITLE
[Bug Report] wrong el-select value while submit

### ISSUE THREAD

**Issue by vibezzz** [ElemeFE/element#8445]
### Element UI version
2.0.5

### OS/Browsers version
Windows 10 / Chrome 

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/6gqc5dj1/1/](https://jsfiddle.net/6gqc5dj1/1/)

### Steps to reproduce
1. Have el-select inside of el-form
2. Make sure select has "name" scpecified and select some option with different name and value like {value: "1", label: "label1"}
3. Submit form using el-button with native-type="submit"
4. Check submited request params for select's name. There will be "label1"

### What is Expected?
Expected server will recieve select's value.

### What is actually happening?
Server recieve select's label. This way when multiple=false component works just like input.

**Comment by LastHeaven** [comment]
Native commit events will refresh the page，so the value will be init。
If you want to push something to the server，you can use post request。

**Comment by vibezzz** [comment]
@LastHeaven issue not about refreshing page, there is different  topic. Post or Get does not matter.  Not every app needs ajax and there is native-type=submit for native posting so form must work as native and "select" must submit it's value not "label".

**Comment by firesh** [comment]
Native form submit is not preferred by SPA. 
If you insist, it's better using a `type="hidden"` input and bind a value with el-select.

**Comment by vibezzz** [comment]
@firesh why do you speak about SPA? I dont need such advices, i know about it, but there is different topic! We have functionality (native-type=submit) for submit forms natively  and it do not work properly with el-select. 
Please stop speak about Ajax and SPA.

**Comment by firesh** [comment]
The el-select value property supports string/number/object, and native from value is only supports string/number, I think that's why native submit value is label property but not value property.
Wish you good luck.

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/33523580-c54d2980-d845-11e7-9a93-2b88571c7dec.png)

In the current implementation of Select, what you see in the input box (in this case, `'second'`) is exactly the value of the `<input>` element. It's different from the binding value (in this case, `2`). So you'll have to modify the FormData if you wish to use native form submit.

Making Select compatible with native form submit requires a major refactor, so I'm leaving this issue open to see if this is a popular demand.

**Comment by Leopoldthecoder** [comment]
Closing this issue since no other user is requesting this feature.
