### ISSUE TITLE
[Feature Request] DatePicker support multiple Select Date

### ISSUE THREAD

**Issue by cgkoreyoshi** [ElemeFE/element#8450]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Like this，support multiple Select Date
Please look at the image, thanks.

<img width="391" alt="wx20171123-104227 2x" src="https://user-images.githubusercontent.com/14900764/33157447-c4d458e2-cfc7-11e7-8fb9-66fec8c215a4.png">

**Comment by cgkoreyoshi** [comment]
现在有日期的范围选择，可以选起止日期，但期望实现的功能是：
支持选择多个单日期，而且可以不连续，如上图中所示，可以任意选择多个日期。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
