### ISSUE TITLE
The minimum width of [Bug Report] InputNumber is too large to add formatting

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8453]
### Element UI version
2.0.5

### OS/Browsers version
win10/chrome62

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/udxxnw20/](https://jsfiddle.net/udxxnw20/)

### Steps to reproduce
直接显示

### What is Expected?
如果输入的数字比较小，两三位数以内，最小宽度应和input差不多
另外希望增加格式化，显示小数位和前后缀

### What is actually happening?
比实际input宽很多

**Comment by Leopoldthecoder** [comment]
可以自己写 CSS：https://jsfiddle.net/udxxnw20/1/
