### ISSUE TITLE
How does [Bug Report] set native attributes, such as the pattern property of input?

### ISSUE THREAD

**Issue by pengxianggithub** [ElemeFE/element#8455]
### Element UI version
2.0.5

### OS/Browsers version
chrome

### Vue version
2.5.8

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
none

### What is Expected?
 none

### What is actually happening?
怎么设置原生属性 例如input的pattern属性？

**Comment by Leopoldthecoder** [comment]
I'm afraid you'll have to manipulate DOM.
