### ISSUE TITLE
[Feature Request] el-container content should move to left if el-aside(menu) is collapsed.

### ISSUE THREAD

**Issue by sudo-shubham** [ElemeFE/element#8456]
### Existing Component
Yes

### Component Name
el-menu

### Description
When El-menu in el-aside is collapsed the content of el-container should move to left.
How can I do this using CSS?

**Comment by Leopoldthecoder** [comment]
Bind the `width` of `<el-aside>` to a variable and update that variable when the Menu collapses / expands.
