### ISSUE TITLE
[Feature Request] Filtering in the tree

### ISSUE THREAD

**Issue by apox13** [ElemeFE/element#8457]
### Existing Component
Yes

### Component Name
Tree

### Description
If the node matches the filter conditions then you need to show all the child nodes.

**Comment by furybean** [comment]
Can describe the use of the scene?
If a node at top level matches the rule, all child nodes under the node are visible and can not be filtered.

**Comment by furybean** [comment]
Can describe the use of the scene?
If a node at top level matches the rule, all child nodes under the node are visible and can not be filtered.
