### ISSUE TITLE
[Bug Report] select menu of some problems and suggestions

### ISSUE THREAD

**Issue by dmlzj** [ElemeFE/element#8462]
### Element UI version
2.0.5

### OS/Browsers version
Mac/Chrome

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/18/](https://jsfiddle.net/mmx38qxw/18/)

### Steps to reproduce
1:当select出现滚动条的时候，下拉展开后，把滚动条拉到最下面或者做些下拉，然后如果不做任何选择，点击周围空白后，下拉收起来
2:再点开的时候

### What is Expected?
滚动条显示是在之前拉到的位置，下拉数据也是显示在之前选择的位置

### What is actually happening?
滚动条停留在了下拉的地方，但是数据却是回到了第一条的数据了，然后滚动条稍微做下滚动就到了最上面了。
### 小建议
下拉展开的时候能不能加个透明的modal层，不让其他有滚动条的地方再能滚动。现在是，这个下拉菜单会随着其他的滚动条动了，
![7](https://user-images.githubusercontent.com/3021601/33165660-9a3bde42-d072-11e7-9ab8-ab04b0f5c85d.png)
随着那个滚动条，滚出去了！

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8467/commits/6d73b7a03464a1fb2145cc20005c039e0a7722df

**Comment by dmlzj** [comment]
I copy your code to my project, but this problem is not solved

**Comment by dmlzj** [comment]
@Leopoldthecoder 帅哥，这个问题还没解决呢。。
