### ISSUE TITLE
[Bug Report] The option "manual" of property "trigger" of popover doesn't disable the option "click"

### ISSUE THREAD

**Issue by snowffer** [ElemeFE/element#8464]
### Element UI version
2.0.5

### OS/Browsers version
Mac OS 10.12.6 (16G1036) / Chrome  62.0.3202.94 (Official Build) (64-bit)

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/snowell/bkfxrdLd/3/](https://jsfiddle.net/snowell/bkfxrdLd/3/)

### Steps to reproduce

1. Create a DOM element (such as a div) which contains a button
2. Set a popover to the DOM element
3. Set the trigger of the popover to "manual"
4. Set a variable (such as "isShown") to the v-model of the popover to control show it or not
5. Bind a method of the click event of the button. In the method, set the isShown to true
6. Click the DOM element but not the button

### What is Expected?
The popover should not be shown.

### What is actually happening?
The popover is shown. And blur it, it would disappear.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8467/commits/b3c3dffac9e971933f455a212c89a7315ba27f29

**Comment by snowffer** [comment]
Which version would contain this fix, and when will it be released?
