### ISSUE TITLE
[Feature Request] Bind the context on the date picker options

### ISSUE THREAD

**Issue by nWidart** [ElemeFE/element#8465]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Hello,

For the datepicker component, when using the picker-options attribute, it would be nice to bind the current context inside the options.
For example:

```js
pickerOptions1: {
  disabledDate(time) {
  	console.log(this.myDates);
    return time.getTime() > Date.now();
  },
},
```
`this`, is not equal to the current vue instance. Full example here: https://jsfiddle.net/NicolasW/cm4ftkc0/1/
Thus, it's not possible to access properties and methods inside the options object.

However, this works: https://jsfiddle.net/cm4ftkc0/2/

```js
pickerOptions1: {
  disabledDate: function(time) {
  	console.log(this.myDates);
    return time.getTime() > Date.now();
  }.bind(this),
},
```

It's using the long version   calling `bind` manually.

Thanks,

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/cm4ftkc0/3/

**Comment by nWidart** [comment]
Thanks @Leopoldthecoder , but don't you think this feels hacky? What if `this` was already bound inside the callback?

**Comment by Leopoldthecoder** [comment]
Actually this is ES6 object notation:
```JS
const a = {
  name: 'aa',
  hello() {
    console.log(this.name) // log 'aa'
  }
}
```
 There is not much we can do.

**Comment by nWidart** [comment]
Ok, thank you for the explanation. 👍
