### ISSUE TITLE
[Bug Report] DateTimePicker Cannot read property'getHours'of null

### ISSUE THREAD

**Issue by icesman** [ElemeFE/element#8466]
### Element UI version
2.0.5

### OS/Browsers version
win7 / Chrome  62.0.3202.94（正式版本） （32 位）

### Vue version
2.5.8

### Reproduction Link
[http://element-cn.eleme.io/#/zh-CN/component/datetime-picker](http://element-cn.eleme.io/#/zh-CN/component/datetime-picker)

### Steps to reproduce
1、打开http://element-cn.eleme.io/#/zh-CN/component/datetime-picker；
2、打开DateTimePcikerRange的示例；
3、在左边的panel中选择某一天，并不对上方的日期inpu以及时间input做任何操作，保持默认状态；
4、在右边的panel中选中时间input，用鼠标滑轮选中23 : 59 : 59后，时间input显示的仍未 00 : 00 : 00，然后控制台报错，且组件无法使用

### What is Expected?
选择同一天的00:00:00 到 23:59:59应该正常使用，且不报错

### What is actually happening?
组件报错，且无法使用

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/pull/8467/commits/fd5af20be084289d8c3592389ec937aa478615cc

**Comment by hexufeng** [comment]
有解决吗？

**Comment by MiCoo** [comment]
2.3.0 版本依然有这个问题

**Comment by hexufeng** [comment]
可以看看这个问题下的回答，https://github.com/ElemeFE/element/issues/8606#issuecomment-388236639
