### ISSUE TITLE
The problem of [Bug Report] on paging components in switching the display size of each page

### ISSUE THREAD

**Issue by HengCC** [ElemeFE/element#8468]
### Element UI version
2.0.4

### OS/Browsers version
macos 10.12.6

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/22/](https://jsfiddle.net/mmx38qxw/22/)

### Steps to reproduce
初始分页总数为15条数据 , 每页显示10条, 当前第2页

1. 切换每页显示20条数据

### What is Expected?
只有 handleSizeChange 被触发, 并且能够或得重新计算后的实际分页数据. currentPage->1 (因为总数15,切换每页显示20条后, 虽然原先显示的是第二页, 但是经过计算后会变成只有1页数据), pageSize->20

### What is actually happening?
handleSizeChange 被触发, handlePageChange也同样被触发, 
这会导致2次请求, 并且请求的数据参数都会是错误的
第一次请求的条件是 {currentPage:2,pageSize:20}
第二次请求的条件是 {currentPage:1,pageSize:10}

**Comment by HengCC** [comment]
是否应该修改下分页的事件触发机制为:

当每页显示大小 或者总数 或者当前页发生变更的时候, 直接本地计算出最终的实际 page 和pageSize 

然后暴露出事件供获取这个变化来刷新数据呢?

**Comment by LastHeaven** [comment]
虽然这样就行了
https://jsfiddle.net/mmx38qxw/23/
但是也希望官方加上那个事件

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

In the `size-change` and `current-change` callbacks, you should update the consumer's data, or in your case, trigger Vuex mutations.

**Comment by LastHeaven** [comment]
@Leopoldthecoder
如例子https://jsfiddle.net/jkhcf1m0/2/ 
当总条数是30时,每页10条时，选择第3页，然后切换到每页30条。
这时会同时触发`size-change`和`current-change`事件。
这可能会导致2次翻页请求。
现在这里其实是需要一个`page-change`事件，同时提供当前页数和每页条数，当改变当前页数时只触发一次`page-change`事件,而不是触发可能导致2次翻页请求的`size-change`和`current-change`事件。

PS:虽然https://jsfiddle.net/mmx38qxw/23/
解决多次请求问题，但我已经懒得多写一行代码去判断了，smile （づ￣3￣）づ╭❤～

**Comment by HengCC** [comment]
@Leopoldthecoder  讲真. 我现在的临时解决方案就是 每次回调触发的时候, 在重新计算一次要不要去触发请求.  和 @LastHeaven 的处理方式类似.  

从框架层次的角度去考虑. 不是应该让使用者更少的去关注怎么处理分页吗.
