### ISSUE TITLE
[Feature Request] Add clearable prop to el-input

### ISSUE THREAD

**Issue by lbogdan** [ElemeFE/element#8469]
### Existing Component
Yes

### Component Name
el-input

### Description
It would be nice to have clearable text inputs, the same as selects. I achieved that with a wrapper component [here](https://codesandbox.io/embed/18wqp7lmrl?module=%2FExtElInput.vue), and it would help to have it directly in the library. If you agree, I could help with a PR.

Thanks!

**Comment by Leopoldthecoder** [comment]
PR welcome.

My opinion about this feature is that the clear icon should only appear when you hover on the input box (and you have something typed already, of course), same as Select. Another thing is that if a `clearable` Input also has a `suffix-icon`, the suffix icon should hide when you hover on Input, and the clear icon should take its place.

Please let me know your thoughts.

**Comment by lbogdan** [comment]
I completely agree, and I would also show it when focused, otherwise if you're navigating the form with the keyboard, you might now know there's a clear button (although if you're used to using the keyboard, you might just clear it using the keyboard, too).

Btw, I didn't mention my use case: a search field that filters a list *as you type*, and being able to reset the filter with just with a click.

**Comment by Leopoldthecoder** [comment]
Ah yes, it should show when focused. We'll be expecting your PR then.

**Comment by wacky6** [comment]
You may want to have a look at date-picker's not-so-perfect clear button design.

**Comment by lbogdan** [comment]
Hello,

So far it looks like [that](https://codesandbox.io/embed/qx4m0l311j?module=%2FApp.vue).

Please let me know what you think.

**Comment by Leopoldthecoder** [comment]
@lbogdan It looks great. Thanks!
