### ISSUE TITLE
When [Bug Report] enters Tree component data is prohibited, in some cases, the selection will fail and the console will not report error

### ISSUE THREAD

**Issue by lianmt** [ElemeFE/element#8472]
### Element UI version
2.0.5

### OS/Browsers version
win7/chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/lianmingtang/vmLpv3n7/1/](https://jsfiddle.net/lianmingtang/vmLpv3n7/1/)

### Steps to reproduce
一级不能取消选中状态，可查看实例。

### What is Expected?
传入Tree组件数据有禁止时，某些情况下反选会失效，控制台没有报错，如jsfiddle的例子。

### What is actually happening?
一级不能取消选中状态，可查看实例。

**Comment by lianmt** [comment]
Hurry up, please

**Comment by Leopoldthecoder** [comment]
Please refer to https://github.com/ElemeFE/element/issues/4767

**Comment by lianmt** [comment]
thanks
