### ISSUE TITLE
[Feature Request] Ability to use different colors in Radio-group Attributes

### ISSUE THREAD

**Issue by wsw70** [ElemeFE/element#8474]
### Existing Component
Yes

### Component Name
Radio

### Description
As far as understand, the Radio-group Attributes allow to select one font and background pair of attributes, to be used on all the buttons. Would it be possible to have each button styled on its own (to have one, say, red when selected, and another one yellow when selected)?

**Comment by sonmunehiro** [comment]
+1

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can write your own CSS.
