### ISSUE TITLE
[Bug Report] el-form's label-position property does not work without label-width 

### ISSUE THREAD

**Issue by njleonzhang** [ElemeFE/element#8477]
### Element UI version
2.0.5

### OS/Browsers version
chrome

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/2z9tzgvp/1/](https://jsfiddle.net/2z9tzgvp/1/)

### Steps to reproduce
open the link, you can see the issue

### What is Expected?
label-position take effect

### What is actually happening?
label-position does not take effect

**Comment by liaoyinglong** [comment]
This looks like another property（`label-width`），like this 

https://jsfiddle.net/2z9tzgvp/2/

**Comment by Leopoldthecoder** [comment]
This is by design in the current implementation. The `.el-form-item__content` element takes `label-width` as its `margin-left`, and if `label-width` is not specified, it'll take up all space available.

**Comment by njleonzhang** [comment]
add something in the Doc to claim this?

**Comment by Leopoldthecoder** [comment]
Great!
