### ISSUE TITLE
[Bug Report] 1.4.X版本的ele,日期时间选择器datetimerange中,使用format="yyyy-MM-dd HH:mm"组件中仍有秒钟选择

### ISSUE THREAD

**Issue by chouchou723** [ElemeFE/element#8481]
### Element UI version
1.4.10

### OS/Browsers version
win10/chrome最新

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
 <el-date-picker v-model="formLaunch.start_end_time" format="yyyy-MM-dd HH:mm" range-separator=" ~ " type="datetimerange">
 </el-date-picker>

用了format,日期时间选择器, 在选择时间时,仍旧会出现 秒的选择,

### What is Expected?
和2.x版本一样 点击后只出现选择 时钟和分钟

### What is actually happening?
 <el-date-picker v-model="formLaunch.start_end_time" format="yyyy-MM-dd HH:mm" range-separator=" ~ " type="datetimerange">
 </el-date-picker>

用了format,日期时间选择器, 在选择时间时,仍旧会出现 秒钟的选择

**Comment by Leopoldthecoder** [comment]
如果对这一点很介意，请升级至 2.0。1.x 版本中不会加入支持。
