### ISSUE TITLE
[Bug Report] 2.0.5 version, el-table no reason to appear horizontal scroll bar (1.4.10 version is normal)

### ISSUE THREAD

**Issue by lvdongbo** [ElemeFE/element#8488]
### Element UI version
2.0.5

### OS/Browsers version
Windows 10 / Chrome(62.0.3202.94)

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/lvdongbo/u2koe2hy/1/](https://jsfiddle.net/lvdongbo/u2koe2hy/1/)

### Steps to reproduce
1. 打开重现链接
2. 点击Run

### What is Expected?
不应该出现横向滚动条

### What is actually happening?
出现了横向滚动条（多出来的宽度为纵向滚动条的宽度）

**Comment by Leopoldthecoder** [comment]
You can use `doLayout` in 2.0.5: https://jsfiddle.net/u2koe2hy/3/ .

**Comment by lvdongbo** [comment]
好的。请问一下这个是BUG吗？如果是的话，我们就等修复后再升级到2.X的版本

**Comment by weifeiyue** [comment]
@Leopoldthecoder A horizontal scroll bar appears again when resize the brower

**Comment by michellebai** [comment]
使用了 doLayout，還是不行啊
