### ISSUE TITLE
[Bug Report] Table column‘s order wrong with v-for when wrap by component

### ISSUE THREAD

**Issue by ciwyaitd** [ElemeFE/element#8489]
### Element UI version
1.4.11

### OS/Browsers version
os 10.11.6 / chrome 62.0.3202.94

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/ciwyaitd/tpaspb2r/](https://jsfiddle.net/ciwyaitd/tpaspb2r/)

### Steps to reproduce
-

### What is Expected?
table column's order is correct.

### What is actually happening?
table column's order is wrong.

**Comment by ciwyaitd** [comment]
v-for props, and the props[0] move to last after rendering.

**Comment by wacky6** [comment]
https://jsfiddle.net/rh63o10p/

**Comment by ciwyaitd** [comment]
em...
my example is just a simple，and i need to do more difficult like this.
so i need to  wrap el-table-column by component.

**Comment by ciwyaitd** [comment]
@wacky6 i know this method.

**Comment by wacky6** [comment]
I guess that wrapping el-table-column will **not** work due to current el-table implementation.

**Comment by ciwyaitd** [comment]
Is there some processing to sort component?

**Comment by ciwyaitd** [comment]
https://jsfiddle.net/ciwyaitd/tpaspb2r/
😭 how did it happen.

**Comment by ciwyaitd** [comment]
I guess maybe columnIndex is something wrong.
