### ISSUE TITLE
[Feature Request] Add 'separator' and 'separator-class' to Cascader component

### ISSUE THREAD

**Issue by shawnrad** [ElemeFE/element#8490]
### Existing Component
Yes

### Component Name
Cascader

### Description
Currently, the Cascader component hardcodes the separator icon to be the slash character ("/")
https://github.com/ElemeFE/element/blob/dev/packages/cascader/src/main.vue#L49

It would be preferable to match the Breadcrumb component and allow the user to select their own separator (or separator class).

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/pull/8501
