### ISSUE TITLE
[Feature Request] Include Icon and Popover in Form?

### ISSUE THREAD

**Issue by elbsurfer** [ElemeFE/element#8491]
### Existing Component
Yes

### Component Name
el-form

### Description
Hello,
I use the el-form and el-form-item component. I am wondering how I can include an icon (for example here: http://d.pr/i/YOcMYA) and this icon should have make use of el-popover to show an info message.

How can I do that?

**Comment by Leopoldthecoder** [comment]
You can put it right after the Switch. Form and FormItem won't break it.
