### ISSUE TITLE
The bar of [Bug Report] scrollbar cannot be reset

### ISSUE THREAD

**Issue by ohhoney1** [ElemeFE/element#8493]
### Element UI version
2.0.5

### OS/Browsers version
win7/chrome60

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/cnjs/syeftemr/](https://jsfiddle.net/cnjs/syeftemr/)

### Steps to reproduce
1，点开select，拉到底，此时滚动条在最下方
2，然后点击空白处，下拉框隐藏。
3，再次点开select，发现滚动条仍在最下方，然而内容是从头开始的。

### What is Expected?
这个问题是我在用 el-scrollbar 组件时发现的。期望每次点开select，滚动条可以重新加载。 

### What is actually happening?
停在原始的位置。

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8467/commits/6d73b7a03464a1fb2145cc20005c039e0a7722df#diff-77681c030d3f0bb43a843a628ce7018cR421
