### ISSUE TITLE
[Bug Report] versions are different from 1.4.11 and 2.0.5 (Tree and Popover)

### ISSUE THREAD

**Issue by zyz** [ElemeFE/element#8494]
### Element UI version
2.0.5

### OS/Browsers version
win8.1/Google chrome版本 58.0.3029.110

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/30/](https://jsfiddle.net/mmx38qxw/30/)

### Steps to reproduce
1.Tree树
check-strictly="true"时，checkbox选择框，选择父checkbox子checkbox不会自动选择
2.Popower弹出框
trigger="manual"时，点击弹出框任意内容就隐藏

### What is Expected?
同1.4.11版本效果相同
1.Tree树
check-strictly="true"时，checkbox选择框，选择父checkbox子checkbox自动选择
2.Popower弹出框
trigger="manual"时，点击弹出框任意内容不隐藏，点出关闭才隐藏

https://jsfiddle.net/mmx38qxw/31/

### What is actually happening?
1.Tree树
check-strictly="true"时，checkbox选择框，选择父checkbox子checkbox不会自动选择
2.Popower弹出框
trigger="manual"时，点击弹出框任意内容就隐藏

**Comment by Leopoldthecoder** [comment]
Tree 的 `check-strictly` 的含义就是父子不再关联，因此 2.0 才是正确的表现。

Popover 2.0 里的行为是个 bug，下个版本会修复。
