### ISSUE TITLE
[Feature Request] please God on the official website announced el-scrollbar API document bar

### ISSUE THREAD

**Issue by sdlddr** [ElemeFE/element#8495]
### Existing Component
是

### Component Name
el-scrollbar

### Description
如题，目前看到官网组件介绍页中已经使用了此插件，正好项目中要用到。谢谢。

**Comment by Leopoldthecoder** [comment]
滚动条在使用上需要注意的地方比较多，之后也可能面临着用法的改变，所以不建议用户使用。如果一定要使用，可以参考官网的代码。

**Comment by longxingren** [comment]
@Leopoldthecoder 期待更新scrollbar文档
