### ISSUE TITLE
How to turn off animation effects when [Feature Request] vertical navigation menu bar expands / holds up?

### ISSUE THREAD

**Issue by sdlddr** [ElemeFE/element#8496]
### Existing Component
是

### Component Name
el-menu

### Description
如题，项目中垂直的导航菜单栏在展开/收起时，父容器已经另有动画效果，不需要导航菜单自带的特效。

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

Hint: 覆盖 CSS
