### ISSUE TITLE
When the [Bug Report] table is merged, the condition is the first column, but the last column is affected.

### ISSUE THREAD

**Issue by AnyGong** [ElemeFE/element#8497]
### Element UI version
2.0.5

### OS/Browsers version
macOS Hight Sierra Chrome  62.0.3202.94（正式版本） （64 位）

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/34/](https://jsfiddle.net/mmx38qxw/34/)

### Steps to reproduce
请看链接示例

### What is Expected?
第一列第1行和第二列第2行合并；
第一列第4行和第二列第5行合并；

### What is actually happening?
最后一列发生了不可预测的变化。第4列第3行被隐藏了。第4列第7行被隐藏了。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/39/

你错误地把第三行第一列和第七行第一列给隐藏了：
```JS
if (rowIndex === 2 && columnIndex === 0) {
  return [0, 0]
}
```
```JS
if (rowIndex === 2 && columnIndex === 0) {
  return [0, 0]
}
```

**Comment by AnyGong** [comment]
感谢，确实是这样的。
