### ISSUE TITLE
[Bug Report] There are some abnormal tooltips, such as top left, bottom left

### ISSUE THREAD

**Issue by yoker** [ElemeFE/element#8498]
### Element UI version
2.0.5

### OS/Browsers version
Chrome 62

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/38/](https://jsfiddle.net/mmx38qxw/38/)

### Steps to reproduce
move cursor on button

### What is Expected?
the arrows are normal 

### What is actually happening?
the arrows are abnormal for their position

**Comment by Leopoldthecoder** [comment]
You can refer to https://github.com/ElemeFE/element/issues/5302. I'm adding the offset to 8px to make it look better in https://github.com/ElemeFE/element/pull/8507/commits/d34798502ef6476a5103073e124df92862101187.
