### ISSUE TITLE
[Bug Report] Tag: [type=undefined (default)] should be gray and [type=info] should be blue

### ISSUE THREAD

**Issue by kenberkeley** [ElemeFE/element#8499]
### Element UI version
2.0.5

### OS/Browsers version
ALL

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/7f4j02Ly/](https://jsfiddle.net/7f4j02Ly/)

### What is Expected?
[type=undefined (default)] should be gray and [type=info] should be blue

### What is actually happening?
[type=undefined (default)] is blue and [type=info] is gray

**Comment by Leopoldthecoder** [comment]
This is by design:
![image](https://user-images.githubusercontent.com/10095631/33230229-653ad168-d21a-11e7-9758-044ca126ac49.png)

[type=undefined (default)] uses primary color, and [type=info] uses info color.
