### ISSUE TITLE
There is a problem when displaying data from data objects push to [Bug in table Report] data

### ISSUE THREAD

**Issue by lizhaoxuan1992** [ElemeFE/element#8500]
### Element UI version
2.0.5

### OS/Browsers version
win 10， chrome 64

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/59o0jkr7/3/](https://jsfiddle.net/59o0jkr7/3/)

### Steps to reproduce
在未添加之前的数据，点击编辑时，icon可以随意切换显示或者隐藏
bug复现步骤
1.点击添加，会增加一行
2.点击新添加行的编辑按钮，没有反应
3.点击其他已有的编辑按钮，新添加行会有反应（之后先点击新添加，再点击之前有的编辑才有反应）
4.如果多次点击新添加行，再点击以前已有编辑，会把之前没响应的交互一次完成

### What is Expected?
新添加的数据也包含和之前数据相同服务

### What is actually happening?
数据push进去，但是不会有反应，只有点击列表内之前已有的其他按钮才有反应

**Comment by Leopoldthecoder** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

https://jsfiddle.net/59o0jkr7/4/

**Comment by lizhaoxuan1992** [comment]
这个在 添加多条记录之后还是会有问题，比如添加了三条数据，三条数据都是同事修改的
