### ISSUE TITLE
[Bug Report] el-select does not fit el-col width

### ISSUE THREAD

**Issue by ellavas** [ElemeFE/element#8502]
### Element UI version
2.0.5

### OS/Browsers version
Windows / ALL

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/Lur942jr/](https://jsfiddle.net/Lur942jr/)

### Steps to reproduce
Embed a el-select in el-col with a defined size

### What is Expected?
The select should have the same with than the column.

### What is actually happening?
The el-select has a fixed size

**Comment by Leopoldthecoder** [comment]
The default `display` of Select is `inline-block`. You can override it to `block` in this case.

**Comment by ellavas** [comment]
Would it be possible to make it configurable?
