### ISSUE TITLE
[Bug Report] Text selecting on mobile devices

### ISSUE THREAD

**Issue by Timz** [ElemeFE/element#8504]
### Element UI version
1.4.11

### OS/Browsers version
chrome

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/---](https://jsfiddle.net/---)

### Steps to reproduce
On tablets and mobile devices, when you tap your finger on the elements of the interface, text is highlighted. For example, the navigation bar, buttons, tabs and others. It's annoying.

### What is Expected?
No selecting

### What is actually happening?
text is highlighted. Like this http://f3.s.qip.ru/lipRbnna.png

Solution: add in css elements: user-select: none

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop admin sites. We discourage people to use it on mobile devices.
