### ISSUE TITLE
[Feature Request] we need infinite scroll and refresh control

### ISSUE THREAD

**Issue by weituotian** [ElemeFE/element#8505]
### Existing Component
No

### Component Name
infinite scroll and refresh control

### Description
infinite scroll and refresh control can be used to show a list ,allow user to load more and refresh the list data just like android and ios do!
it is a commonly component , i hope yours can make it!

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by weituotian** [comment]
@Leopoldthecoder so bad as element ui
