### ISSUE TITLE
[Feature Request] What is the main difference between version 1.4.X and 2.0.X?

### ISSUE THREAD

**Issue by xeoshow** [ElemeFE/element#8508]
### Existing Component
Yes

### Component Name
element UI

### Description
Hi,

I am trying to select between  version 1.4.X and 2.0.X, but I am not sure what exactly the main differences and how to choose?

Thanks a lot.

Best regards, Jason

**Comment by Leopoldthecoder** [comment]
See the changelog.

**Comment by xeoshow** [comment]
I do have seen the change log from below link:
https://github.com/ElemeFE/element/releases

WHILE my real point is: version 2 and version 1, how should I choose one over another one? Are both series stable enough?

Thanks v much

Best reagards, Jason

**Comment by Leopoldthecoder** [comment]
We'll stop supporting 1.x as of next month.
