### ISSUE TITLE
[Bug Report] Right align sortable table header loses up/down icons.

### ISSUE THREAD

**Issue by notVitaliy** [ElemeFE/element#8511]
### Element UI version
2.0.5

### OS/Browsers version
macOS 10.12.6 / chrome 62.0.3202.94 (Official Build) (64-bit)

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/2u7hhvov/](https://jsfiddle.net/2u7hhvov/)

### Steps to reproduce
Use `sortable` and `align="right"` on a `el-table-column`

### What is Expected?
To be able to see the up/down icons.

### What is actually happening?
Can't see the up/down icons.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8405
