### ISSUE TITLE
el-row and el-col are not work well inside the el-header and el-main

### ISSUE THREAD

**Issue by amigoge** [ElemeFE/element#8512]
Here is my template

    <el-container>
        <el-header>
            <el-row>
                <el-col :span="24"><h1>header line 1</h1></el-col>
            </el-row>
            <el-row>
                <el-col :span="24"><h1>header line 2</h1></el-col>
            </el-row>
            <el-row>
                <el-col :span="24"><h1>header line 3</h1></el-col>
            </el-row>
        </el-header>
        <el-main>
            <el-row>
                <el-col :span="24"><div>main line 1</div></el-col>
            </el-row>
            <el-row>
                <el-col :span="24"><div>main line 2</div></el-col>
            </el-row>
            <el-row>
                <el-col :span="24"><div>main line 3</div></el-col>
            </el-row>
        </el-main>
    </el-container>

But the result seems not so good...
![image](https://user-images.githubusercontent.com/12947324/33242328-07ac8f24-d30e-11e7-8acb-8d0f1a64c0c9.png)

If I wanna use h1~h5 in the el-head,what should I do?

**Comment by kgrosvenor** [comment]
Lol ^
