### ISSUE TITLE
[Feature Request] Display formatting for Input Number

### ISSUE THREAD

**Issue by groenroos** [ElemeFE/element#8515]
### Existing Component
Yes

### Component Name
Input Number

### Description
I'd like to configure Input Number to format the displayed number, and format the number each time it's changed. This would allow the input to display thousands separators, suffixes and prefixes for currencies, etc.

**Comment by ericcgu** [comment]
Can use this gist as a component for now
https://gist.github.com/ericcgu/b4b16a6f7ce73c5329c4c395f02896c5
