### ISSUE TITLE
[Bug Report] select control in dialog and col combination control will be jitter

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#8517]
### Element UI version
1.4.11

### OS/Browsers version
win10 / chrome 62

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/wukon/39rncoop/](https://jsfiddle.net/wukon/39rncoop/)

### Steps to reproduce
select 控件 在dialog 和 col 组合中,在选择的时候,会出现抖动的情况.

element 版本 1.4.11 和  2.0.5 都存在这个问题.
![图片描述](https://sfault-image.b0.upaiyun.com/105/794/105794297-5a1b9e1446c06_articlex)

### What is Expected?
select组件 选择选项的时候,表单不会抖动.

### What is actually happening?
select组件 选择选项的时候,表单会抖动一下.

**Comment by Leopoldthecoder** [comment]
有 2.0 的截图吗？

**Comment by zsedcbm** [comment]
@Leopoldthecoder  你把示例中的elementui 版本改成2.0的就可以运行查看了.
我试过,360极速浏览器中抖动大一些,chrome浏览器 v62 中抖动小一些,但是还是可以察觉的.

**Comment by firesh** [comment]
我改了一分2.0的版本：
https://jsfiddle.net/39rncoop/1/show/
应该是没抖， @zsedcbm 看看。

**Comment by zsedcbm** [comment]
@firesh 是的,没有抖动了.更新到2.0.7就可以了?

**Comment by Leopoldthecoder** [comment]
@zsedcbm 请确认目前版本是否还有这个问题。

**Comment by zsedcbm** [comment]
@Leopoldthecoder  2.0.11 和 2.1.0 版本正常 , 1.4.13版本有问题.
