### ISSUE TITLE
[Bug Report] Add'lable'attribute to Table-column component when type==expand

### ISSUE THREAD

**Issue by fantasy9830** [ElemeFE/element#8518]
### Element UI version
1.4.11

### OS/Browsers version
Win10/Chrome  62.0.3202.94

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/m0wk5xLb/](https://jsfiddle.net/m0wk5xLb/)

### Steps to reproduce
`<el-table-column label="无效" type="expand"> ..... </el-table-column>`

### What is Expected?
The text in the label attribute can be displayed in header

### What is actually happening?
 The 'lable' attribute is invalid when type==expand

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/pull/8531
