### ISSUE TITLE
[Bug Report] Dialog's lock-scroll attribute dosen't work in iPhone's Safari browser

### ISSUE THREAD

**Issue by JackZong** [ElemeFE/element#8519]
### Element UI version
1.4.11

### OS/Browsers version
ios 11.1.2

### Vue version
2.5.8

### Reproduction Link
https://jsfiddle.net/mmx38qxw/46/#&togetherjs=BxyCiHH98g

### Steps to reproduce
当在dialog中嵌套表单的时候，当表单的内容较多时，一点开dialog，滑动dialog中的表单，dialog不动，body滑动

### What is Expected?
滑动dialog的时候，body锁定

### What is actually happening?
点开dialog，滑动dialog，dialog不动，body滑动

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop admin sites. We discourage people to use it on mobile devices.

**Comment by Sorazuu** [comment]
`.el-popup-parent--hidden {
    overflow: scroll;
    -webkit-overflow-scrolling: touch
  }`
Hope that help.

**Comment by siberiadev** [comment]
> Element is designed for desktop admin sites. We discourage people to use it on mobile devices.

I see this answer again and again, but people will use it on mobile. So we hope you will make it responsive in the feature
