### ISSUE TITLE
When the drop-down menu is included in the [Bug Report] table, click the drop down menu, and @row-click fails in Firefox

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#8522]
### Element UI version
2.0.5

### OS/Browsers version
Windows10/Firefox 57.0 64bit

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/9poeb4qz/](https://jsfiddle.net/9poeb4qz/)

### Steps to reproduce
0、在表格组件中用@row-click增加行点击事件
1、在表格组件中，使用 `<template scope="scope">` 自定义列内容
2、在自定义的列内容中增加一个 `<el-select>`
3、在Firefox中运行时，点击增加的下拉菜单，不会触发@row-click事件。而下拉菜单外的部分，会触发。

### What is Expected?
无论是否是下拉菜单，在表格行中点击，都应该触发@row-click。
此问题在Firefox中存在，IE、Chrome浏览器则正常，都正常触发@row-click

### What is actually happening?
Firefox浏览器点击到下拉菜单，不会触发@row-click。

**Comment by Leopoldthecoder** [comment]
和 Element 无关，FireFox 中点击被禁用的表单元素是无法触发 click 事件的：https://jsfiddle.net/9poeb4qz/1/

可能需要自己绕一下。

![image](https://user-images.githubusercontent.com/10095631/33262104-1654a3e4-d3a0-11e7-8286-f8a19f9ae07b.png)

参考：https://developer.mozilla.org/zh-CN/docs/Web/Events/click

**Comment by Leopoldthecoder** [comment]
和 Element 无关，FireFox 中点击被禁用的表单元素是不会冒泡的：https://jsfiddle.net/9poeb4qz/3/

可能需要自己绕一下。

参考：https://github.com/jquery/jquery/issues/2592
