### ISSUE TITLE
[Feature Request] can be set with multiple table rows selected in a row at initialization

### ISSUE THREAD

**Issue by kluslulu** [ElemeFE/element#8524]
### Existing Component
Yes

### Component Name
table

### Description
带多选的表格，希望能够有参数能够设置该行的选中状态，这样在翻页之后也能够记录各行的选中状态
比如： <el-table-column
         :checked="status"
          type="selection"
          width="55">
        </el-table-column>
        ..........
        data () {
            ...........
            this.status = true
            .......
        }
        ..........

**Comment by Leopoldthecoder** [comment]
如果是需要在翻页之后也能够记录各行的选中状态，请直接使用 `reserve-selection` 属性。如果是更一般的需求，可以在获取数据后调用一下 `toggleRowSelection` 方法。
