### ISSUE TITLE
[Feature Request] How to merge cells based on the same data?

### ISSUE THREAD

**Issue by xiyue0814** [ElemeFE/element#8530]
### Existing Component
Yes

### Component Name
table

### Description
objectSpanMethod({ row, column, rowIndex, columnIndex }) {
        if (columnIndex === 0) {
            // How to merge cells based on the same data
        }
}

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

Hint：有 row 和 column 就能获取到当前单元格的数据。
