### ISSUE TITLE
[Bug Report] IE browser is not compatible with Datepicker date selector

### ISSUE THREAD

**Issue by xLong1029** [ElemeFE/element#8533]
### Element UI version
2.0.3

### OS/Browsers version
window 10 / IE11

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
The DatePicker date selector can not bind the already value under the IE browser, especially IE11 is incompatible.

### What is Expected?
Datepicker date picker can be used normally in IE browser

### What is actually happening?
The DatePicker date selector can not bind the already value under the IE browser, especially IE11 is incompatible.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.
