### ISSUE TITLE
[Bug Report] Can't validate dynamically generated Form

### ISSUE THREAD

**Issue by CinKon** [ElemeFE/element#8534]
### Element UI version
2.0.5

### OS/Browsers version
MacOS / Firefox 58

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/CinKon/97m4hqd8/5/](https://jsfiddle.net/CinKon/97m4hqd8/5/)

### Steps to reproduce
I set up a form-object in the data-function and generate the actual form via v-for (see jsfiddle).

### What is Expected?
Defined rules should validate correctly.

### What is actually happening?
The rules associate with the correct fields, but they never return a valid status.

**Comment by wacky6** [comment]
el-form-item's `prop` must match the field path of the value provided in el-form's `data`.
https://jsfiddle.net/vwj18mc1/

Using `:rules` on form with dynamically generated form-items are discouraged. Consider moving `:rules` to el-form-item

**Comment by CinKon** [comment]
Unfortunately, this won't work when the form gets deeper: https://jsfiddle.net/CinKon/6df138vb/2/
I can't get it work with moving it to the el-form-item as well :(

**Comment by CinKon** [comment]
Got it to work. Seperated the form-model from the generator-model.
