### ISSUE TITLE
After [Bug Report] sets the manual attribute of toopTip to true, how do you pop up toolTip through the code?

### ISSUE THREAD

**Issue by ewgcat** [ElemeFE/element#8535]
### Element UI version
1.4.11

### OS/Browsers version
chrome

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/svabfwsf/](https://jsfiddle.net/svabfwsf/)

### Steps to reproduce
设置 toopTip 的  manual 属性 为 true 之后，无法通过代码弹出toolTip

### What is Expected?
设置 toopTip 的  manual 属性 为 true 之后，可以通过代码弹出toolTip

### What is actually happening?
设置 toopTip 的  manual 属性 为 true 之后，无法通过代码弹出toolTip

**Comment by ewgcat** [comment]
Reproduction Link has updated

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/svabfwsf/1/

**Comment by ewgcat** [comment]
thanks

**Comment by wangfengye** [comment]
When the manual property of toopTip is set to true, we can use ```v-model``` property  to controll  ```toolTip```  's show
 [such as](https://jsfiddle.net/maple_wang/b1p9ygvt/)
