### ISSUE TITLE
[Bug Report] DatePicker组件加了placeholder=""后异步更新日期数据时，在所有ie浏览器下都不显示更新后的日期值，其它浏览器正常

### ISSUE THREAD

**Issue by su1924** [ElemeFE/element#8540]
### Element UI version
2.0.3

### OS/Browsers version
win10/IE全部浏览器

### Vue version
2.3.2

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
在DatePicker组件加placeholder=""后异步更新日期数据时，在所有ie浏览器下都不显示更新后的日期值，其它浏览器正常

### What is Expected?
在ie下正常显示日期

### What is actually happening?
在ie下不显示日期

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by jerry7723** [comment]
我也遇到相同问题，设置了placeholder以后就无法更新，在ie10，ie edge上。ie9没问题
