### ISSUE TITLE
[Feature Request] select user experience improvement

### ISSUE THREAD

**Issue by erzh** [ElemeFE/element#8543]
### Existing Component
是

### Component Name
select

### Description
当启用allow-create的时候，建议点击select组件触发focus，而不是关闭下拉菜单，只有blur或点击select组件右边的图标时再关闭下拉菜单，因用户常习惯点击输入框后输入内容
![pic](https://user-images.githubusercontent.com/17918956/33302191-6e369fe6-d435-11e7-8e13-13e5da728282.png)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
