### ISSUE TITLE
[Feature Request] Row Attributes should add responsive grid number or grid attribute objects

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#8546]
### Existing Component
是

### Component Name
Layout 布局 el-row

### Description
在 Col Attributes  里面有  ` xs  sm  md ` 这些配置，但是在 Row Attributes 没有这些配置， 这就很尴尬了， 当你写了 gutter 删格间隔 之后， 无法在响应式 的同时改变删格间隔。

所以建议 Row 组件也加入 “响应式栅格数或者栅格属性对象”

例如

```
<el-row xs="{gutter:20, align:'top'}" sm="{gutter:40, align:'middle'}"></el-row>
```

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
