### ISSUE TITLE
[Bug Report] table won't display when column like <el-table-column :prop="1.2.3" :label="1.2.3">

### ISSUE THREAD

**Issue by fxxjdedd** [ElemeFE/element#8549]
### Element UI version
1.4.9

### OS/Browsers version
Version 60.0.3112.90 (Official Build) (64-bit)

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/6gqc5dj1/2/](https://jsfiddle.net/6gqc5dj1/2/)

### Steps to reproduce
run

### What is Expected?
should display

### What is actually happening?
not display

**Comment by Leopoldthecoder** [comment]
Table doesn't and will not support data structure like this
```JS
data: {
  'a.b': 1
}
```

You need to transform it into
```JS
data: {
  a: {
    b: 1
  }
}
```

**Comment by fxxjdedd** [comment]
Sorry, I'm talking about prop like system version, like : 
`
data:  {
  'v1.2.3': 0.975
}
`

**Comment by Sam--Shan** [comment]
Sir,i have this issues,too.@fxxjdedd

**Comment by Sam--Shan** [comment]
need help,please@Leopoldthecoder

**Comment by fxxjdedd** [comment]
try this:
https://jsfiddle.net/6gqc5dj1/13/
