### ISSUE TITLE
[Feature Request] Support el-radio-button without group

### ISSUE THREAD

**Issue by ellavas** [ElemeFE/element#8550]
### Existing Component
Yes

### Component Name
el-radio-button

### Description
Currently, el-radio-button must define a el-radio-group as parent and the display is inline-block.

The group is not mandatory in case of el-radio. Would it be possible to do the same for el-radio-button ?

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

For the CSS display, you can override it.

**Comment by ellavas** [comment]
Do you have a css example with el-radio-button rendered vertically ?
