### ISSUE TITLE
树控件中, 没有获取 - 节点相关的方法

### ISSUE THREAD

**Issue by sishen0112** [ElemeFE/element#8551]
在tree组件中, 有 getCheckedNodes, getCheckedKeys 两个方法获取选中的节点, 但是我需要获取节点的子树中有被选中的节点, 也就是 - 节点, 请问怎么获取? 是否有相关的方法获取?

![default](https://user-images.githubusercontent.com/11689187/33313187-f0723702-d464-11e7-930d-46a73ff62db2.png)

**Comment by dbjchan1121** [comment]
楼主有木有解决的办法,我也遇到了这个问题了,而且挺多人提这个问题的,官方都没有给解决的方案么,还是以前给过没有找到?

**Comment by hasbug** [comment]
同求！

**Comment by qiuxnlin** [comment]
同求

**Comment by tangmin721** [comment]
同求啊，很多人都碰到这个问题。

**Comment by dbjchan1121** [comment]
这个#1639 可以,我是用这个方法
链接: http://jsfiddle.net/leopoldthecuber/yu2me25j/

**Comment by Desdesdesgo** [comment]
给tree 一个ref 。然后
`let keys = []
            let nodesMap = this.$refs.tree.store.nodesMap;
            const filterChecked = v => {
                if(nodesMap[v].checked || nodesMap[v].indeterminate){
                    keys.push(v)
                }
            }
            var nodesKeys=Object.keys(nodesMap)
            nodesKeys.forEach(filterChecked)
console.log(keys)
`
