### ISSUE TITLE
[Bug Report] Tooltip: not shown for disabled buttons

### ISSUE THREAD

**Issue by d--j** [ElemeFE/element#8557]
### Element UI version
2.0.5

### OS/Browsers version
MaC OS/Chrome

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/48/](https://jsfiddle.net/mmx38qxw/48/)

### Steps to reproduce
Add an `<el-tooltip>` for an `<el-button>` that is disabled.

### What is Expected?
The tooltip of the disabled button gets shown

### What is actually happening?
The tooltip does not get shown

### Workaround
https://jsfiddle.net/mmx38qxw/49/

wrap the `<el-button>` with a meaningless `<span>`

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/33354918-25a5c2e6-d4f0-11e7-8e42-63d70144306f.png)

![image](https://user-images.githubusercontent.com/10095631/33354936-3590e6d6-d4f0-11e7-8517-5c6d761b18ad.png)

https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter

**Comment by jessefalzone** [comment]
Thanks for the hard work.  My team and I are really enjoying Element so far.

Unfortunately the workaround doesn't work well for disabled buttons inside an `<el-button-group>`.  Are there any plans to support this scenario?

### Reproduction Link
https://jsfiddle.net/mmx38qxw/179/

**Comment by d--j** [comment]
Hi @jessefalzone,
yes, there you need extra CSS and adding `el-button` to the wrapping span to make that work: https://jsfiddle.net/mmx38qxw/180/

Maybe a new element `<el-button-group-item>` that can be part of a `<el-button-group>` but can hold other stuff besides `<el-button>` would be a good addition to Element.
