### ISSUE TITLE
[Bug Report] el-upload clearFiles undefined

### ISSUE THREAD

**Issue by zzhtopcase** [ElemeFE/element#8559]
### Element UI version
1.4.11

### OS/Browsers version
57.0.2987.98 

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/9r5k5zys/1/](https://jsfiddle.net/9r5k5zys/1/)

### Steps to reproduce
el-upload 的clearFiles方法，未在before-upload 中调用，提示clearFiles未定义undefined

### What is Expected?
清空文件

### What is actually happening?
提示clearFiles未定义undefined

**Comment by Leopoldthecoder** [comment]
Dialog 的内容是懒加载的，在第一次打开之前 `this.$refs.upload` 是 `undefined`。

**Comment by zzhtopcase** [comment]
在处理的过程中，调整了下
showUpdateDialog(row) {
      this.test = Object.assign({}, row)
      this.dialogStatus = 'update'
      this.dialogFormVisible = true
      this.$refs.upload.clearFiles()
      this.fileList.push({name: this.test.xtfile, url: this.test.xtfile})
},  第一次弹出窗口的时候没有图片，后面每打开一次窗口的话就都会添加一次图片，搞不清楚这个clearFiles是怎么个回事
![default](https://user-images.githubusercontent.com/33108257/33361955-24a43a24-d515-11e7-8187-981986aabf5b.png)
