### ISSUE TITLE
The formatter of [Feature Request] table-column wants to increase the Vue instance object

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8560]
### Existing Component
是

### Component Name
TableColumn

### Description
稍微复杂一点的formatter一般都需要额外参数，比如小数位可能不定，需要在column上配置
例：`<el-table-column prop="money" fixed="2" formatter="fixed"/>`
此时fixed中希望能获取到fixed，尽管formatter可以用箭头函数：formatter="(row,col,value)=>fixed(value,2)"实现，但是一个是代码复杂，另外如果更加复杂的参数就不太方便，希望formatter中可以获取到column的vm实例，就可以获取到column的prop配置

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
