### ISSUE TITLE
[Bug Report] el-switch problem

### ISSUE THREAD

**Issue by zuxriddinkamalov** [ElemeFE/element#8563]
### Element UI version
1.4.2

### OS/Browsers version
62.0.3202.94

### Vue version
2.5.2

### Reproduction Link
None. Because my project is privancy.

### Steps to reproduce
When component created I load switch's state from server. From server responded 0 or 1. I use vue-router. 
<el-form-item label="Show as menu" v-if="post">
<el-switch
name="as_menu"                          
:on-value="1"
:off-value="0"
v-model="post.as_menu">
</el-switch>
</el-form-item>

 beforeCreate () {
       this.$http.get('admin-api/post/getPostById', {
        params: {
          id: this.$route.params.postId
        }
      }).then(response => {
        return response.json()
      }, response => console.log(response)).then(response => {
        this.post = response.data
      })
    },

### What is Expected?
When server responde 1 el-switch must be in state active else inactive.

### What is actually happening?
<el-switch
name="as_menu"                          
:on-value="1"
:off-value="0"
v-model="post.as_menu">
</el-switch>

Server responde 1 but el-switch change post.as_menu to zero.

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly. Your project is private but you can always minify you project to a demo.
