### ISSUE TITLE
表单切换时，resetField 的问题

### ISSUE THREAD

**Issue by nszbf** [ElemeFE/element#8565]
[线上地址 - 切换表单时resetField的问题](http://jsbin.com/suhufegele/edit?html,output)
在html部分标注出了问题所在
```
<!-- 不加else的时候，在T1 T2之间切换会报错 -->
<div v-else></div>
```
期望有更好的写法或者解决办法

**Comment by wslyh123** [comment]
不要用v-if，用v-show就没错。
<el-form-item label="确认密码" prop="checkPass" v-show="formType === 't2'">
          <el-input type="password" v-model="ruleForm2.checkPass" auto-complete="off"></el-input>
        </el-form-item>
