### ISSUE TITLE
[Bug Report] element-react official network pops up Message box component, and the page will be jitter

### ISSUE THREAD

**Issue by homer-wh** [ElemeFE/element#8566]
### Element UI version
2.0.6

### OS/Browsers version
macOS Sierra 10.12.5 / Chrome 版本 62.0.3202.94（正式版本） （64 位）

### Vue version
2.5.9

### Reproduction Link
[https://eleme.github.io/element-react/#/zh-CN/message-box](https://eleme.github.io/element-react/#/zh-CN/message-box)

### Steps to reproduce
进入重新连接, 点击任意 Message box 组件即可

### What is Expected?
安静地弹出 Message box 组件, 关闭该组件时, 安静地退出

### What is actually happening?
打开和关闭 Message box 组件时, 垂直滚动条会消失和出现, 导致页面会出现左右抖动现象

**Comment by Leopoldthecoder** [comment]
请使用 `lockScroll` 属性。
