### ISSUE TITLE
[Bug Report] Responsive Grid breaks on mobile if gutter is large

### ISSUE THREAD

**Issue by tuqire** [ElemeFE/element#8573]
### Element UI version
2.0.7

### OS/Browsers version
Chrome

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/ve75vg2r/](https://jsfiddle.net/ve75vg2r/)

### Steps to reproduce
Give an el-row component a gutter value of 60.

### What is Expected?
No horizontal scroll bar on mobile.

### What is actually happening?
The mobile view has a horizontal scroll bar.

**Comment by Leopoldthecoder** [comment]
Give the container a horizontal margin of `gutter / 2` can solve this: https://jsfiddle.net/ve75vg2r/1/.

Reference: https://github.com/ElemeFE/element/issues/5640
