### ISSUE TITLE
[Feature Request] Lacking documentation for form validation

### ISSUE THREAD

**Issue by ffxsam** [ElemeFE/element#8574]
### Existing Component
No

### Component Name
Documentation

### Description
Documentation is lacking with regards to validation:

1. How do we set it so the error isn't shown until user tabs out of a field? I'm pretty sure this is possible somehow.
2. Where is the documentation showing all possible options for validation rules object?

**Comment by dobromir-hristov** [comment]
It uses the Async-validator internally, you have to check that your self :/

**Comment by ffxsam** [comment]
I have a kind of dumb hack to initially set `show-message` to `false`, and once the user tabs out of the field, it changes `show-message` to `true` in case there's an error. Not ideal. IMO the UI library should allow us to change the behavior here, so that blur triggers validation rather than text change.

**Comment by p4m** [comment]
I use v-model.lazy for that

` <el-input v-model.lazy="user.username">`

**Comment by ffxsam** [comment]
@p4m Ah, thank you for that! I obviously need to re-review the Vue event modifiers.
