### ISSUE TITLE
[Bug Report] terrible memory leak using el-table with vue-i18n

### ISSUE THREAD

**Issue by sora54** [ElemeFE/element#8576]
### Element UI version
1.4.11

### OS/Browsers version
Chrome 62

### Vue version
2.5.9

### Reproduction Link
[https://codepen.io/sora54/pen/XzyKGQ](https://codepen.io/sora54/pen/XzyKGQ)

### Steps to reproduce
Running leak.txt file as html by Browser.
Open Task Manager can see the chrome process keep increasing huge memory, even just create and destroy 10 table by 500 ms. If remove the vue-i18n dependency, the memory will be keep stable without issue. And also the problem will be the same using the guide below to introduce vue-i18n with element-ui

Compatible with vue-i18n@5.x
Element is compatible with vue-i18n@5.x, which makes multilingual switching even easier.

import Vue from 'vue'
import VueI18n from 'vue-i18n'
import Element from 'element-ui'
import enLocale from 'element-ui/lib/locale/lang/en'
import zhLocale from 'element-ui/lib/locale/lang/zh-CN'

Vue.use(VueI18n)
Vue.use(Element)

Vue.config.lang = 'zh-cn'
Vue.locale('zh-cn', zhLocale)
Vue.locale('en', enLocale)

### What is Expected?
Memory can be released after destroying.

### What is actually happening?
Memory keep increasing without release at all.

**Comment by wyjieying** [comment]
how to solve this question?

**Comment by wyjieying** [comment]
@sora54

**Comment by sora54** [comment]
@wyjieying 
didn't resolved.  but seems caused by the below file, as it would help after comment the line 'Override(Vue, langVM)' in the index.js of vue-i18n/src/index.js.
vue-i18n/src/override.js

**Comment by wyjieying** [comment]
@sora54 thanks, i update the version with 7.x ，and so something compatibles, it can work well, and i tryed the version 6.3， it resolved the memory leak, but run very slow
