### ISSUE TITLE
[Bug Report] Version 2 documentation pages - search in page has problems

### ISSUE THREAD

**Issue by glittle** [ElemeFE/element#8577]
### Element UI version
2.0.7

### OS/Browsers version
Window/Chrome

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
Attempt to search in a v2 documentation page for a hidden word.

For example, go to http://element.eleme.io/#/en-US/component/table and search for "max-height" using the browser's "Ctrl F" find feature.  You will see that there are 4 hits on the page.  Hits 3 and 4 are visible and can be found.  Hits 1 and 2 are hidden and are impossible to find without expanding every sample section.

Please fix the v2 docs to be usable!

### What is Expected?
The v 1.4 document page (http://element.eleme.io/1.4/#/en-US/component/table) does not hide the search results, and the browser displays them in the browser's scrollbar.

### What is actually happening?
Hits 1 and 2 are hidden and are impossible to find without expanding every sample section.

**Comment by Leopoldthecoder** [comment]
In v2 docs the scrolling element is no longer `document.body` (the nav menu and main content scroll independently), so the browser may not be able locate keywords.

Separating nav menu and main content when scrolling was a popular demand in 1.x. So we may have to live with this side effect.

**Comment by glittle** [comment]
I'd strongly recommend finding a solution for this. I've had to rely on the browser search many times in using the documentation. Now that is not possible.

Maybe a compromise would be to have a way to open and close all the examples on a page at the same time. Then the browser can at least highlight the search results. This would be acceptable.

**Comment by glittle** [comment]
For anyone else who may find this discussion, this code will open all the demo sections so that the browser search function can be useful. View a page, then in the browser's dev tools console, run this script:

    Array.from(document.getElementsByClassName('demo-block-control')).forEach(c=>c.click())
