### ISSUE TITLE
Bug in the official example of integer verification [Bug Report]

### ISSUE THREAD

**Issue by tiger8888** [ElemeFE/element#8578]
### Element UI version
2.0.7

### OS/Browsers version
mac os/版本 64.0.3269.3（正式版本）dev （64 位）

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
不要看上面的链接,直接看官方示例:
http://element.eleme.io/2.0/#/zh-CN/component/form
中的数字类型验证:
在上面输入aaa111 ,验证错误,
输入111aaa,验证通过...

### What is Expected?
输入111aaa,验证不通过...

### What is actually happening?
输入111aaa,验证通过...

![111](https://user-images.githubusercontent.com/1930815/33410492-79c6f3ba-d5bb-11e7-90e8-46195c647b10.png)

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/7945
