### ISSUE TITLE
[Bug Report] [el-menu] opened/actived style

### ISSUE THREAD

**Issue by xovel** [ElemeFE/element#8580]
### Element UI version
2.0.7

### OS/Browsers version
win10/Chrome61

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/xovel/e4yh3yw1/](https://jsfiddle.net/xovel/e4yh3yw1/)

### Steps to reproduce
NaN

### What is Expected?
While `nav1` is opened or actived, set a special style(eg `color` and `bg-color`) to it. NOT the submenu item.

### What is actually happening?
Cannot set the opened style. `el-menu` set an inline css default.

**Comment by Leopoldthecoder** [comment]
An `<el-submenu>` cannot be active or highlighted. Only `<el-menu-item>`s can.
