### ISSUE TITLE
[Bug Report] el-date-picker V-model for unidirectional binding

### ISSUE THREAD

**Issue by Fangty1** [ElemeFE/element#8582]
### Element UI version
2.0.4

### OS/Browsers version
windows 7

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/gwL80ucc/](https://jsfiddle.net/gwL80ucc/)

### Steps to reproduce
通过按钮改变时间。
console输出新的时间， 但是组件显示的时间不能同步更新？

https://jsfiddle.net/gwL80ucc/

### What is Expected?
https://jsfiddle.net/gwL80ucc/

### What is actually happening?
https://jsfiddle.net/gwL80ucc/

**Comment by wacky6** [comment]
修改数据请赋值，不要用date的方法

**Comment by Fangty1** [comment]
直接赋值可以解决问题。
是不是因为vue双向绑定实现机制导致的无法监听date对象变化？

**Comment by wacky6** [comment]
Date方法是不会被监听的。
Vue的双向绑定实际上是单向数据流+事件的语法糖

**Comment by Fangty1** [comment]
好的。谢谢！
