### ISSUE TITLE
[Bug Report] [el-table] Class '.el-table__row--striped' is not styled

### ISSUE THREAD

**Issue by Elfayer** [ElemeFE/element#8584]
### Element UI version
1.4.12

### OS/Browsers version
Windows 7 / Chrome 61

### Vue version
2.5.9

### Reproduction Link
[http://element.eleme.io/#/en-US/component/table](http://element.eleme.io/#/en-US/component/table)

### Steps to reproduce
Doc: http://element.eleme.io/#/en-US/component/table
There is no distinction between stripped and not stripped row.

### What is Expected?
`.el-table__row--striped` class to be styled.

### What is actually happening?
`.el-table__row--striped` class is not styled.

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/33431065-ebbd1844-d60d-11e7-96b5-c67b6149313b.png)

The background color is striped.

**Comment by Elfayer** [comment]
Right... I can't see it on my screen, it is way too light. And I checked the style on the browser, I couldn't see anything set to `.el-table__row--striped`, that's why I thought there is no color change.
