### ISSUE TITLE
[Feature Request] can I format the style or contents of the "expend" table cell?

### ISSUE THREAD

**Issue by georgehpj** [ElemeFE/element#8585]
### Existing Component
是

### Component Name
table

### Description
项目中有个需求，希望点击文字来展开表格。
我看到设置type="expend"的时候，生成扩展列的代码是写死的，无法自定义。
于是只好hack，屏蔽掉了.el-table__expand-icon--expanded的rotate；替换掉了.el-table__expand-icon>.el-icon的position，修改了.el-icon-arrow-right:before的content的。。。
可能的话，是否以后会提供一个途径可以自定义扩展列的样式和文字呢？

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
