### ISSUE TITLE
When [Bug Report] table sets border and fit is false, the last column has fewer border

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8591]
### Element UI version
2.0.7

### OS/Browsers version
win10/chrome62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/wL679ffv/](https://jsfiddle.net/wL679ffv/)

### Steps to reproduce
无

### What is Expected?
最后一列的border完整

### What is actually happening?
最后一列少了border

**Comment by conanliuhuan** [comment]
傻了都……你自己给每一列都设置了width，结果总列width加起来都没你浏览器的width宽，右边当然会出现空白了。这种情况你应该用min-width，或者给其中一列不要设width让它自动width就可以了。

**Comment by gaecfov** [comment]
请看清楚问题，是最后一列少了边框

**Comment by Leopoldthecoder** [comment]
Fixed in #9326
