### ISSUE TITLE
[Bug Report] Tree重大bug，二级节点更新数据不更新UI

### ISSUE THREAD

**Issue by eurekao** [ElemeFE/element#8592]
### Element UI version
2.0.7

### OS/Browsers version
win10/chrome  60.0.3112.90

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/54/](https://jsfiddle.net/mmx38qxw/54/)

### Steps to reproduce
重现链接里面模拟更换节点位置，
点击 更换第一级节点位置 按钮 能够正常修改第一级节点位置
点击 更换第二级节点位置 按钮 第二级节点的子节点位置未变化 查看log显示d变化ata已经

### What is Expected?
第二级节点的子节点位置发生变化

### What is actually happening?
数据更新了，UI未更新

**Comment by conanliuhuan** [comment]
你为什么要通过$refs去修改内部的数据而不是直接修改外部传入的data数据？
如果直接在外部修改，就不会出现你的问题，例：
https://jsfiddle.net/mmx38qxw/67/

**Comment by eurekao** [comment]
@conanliuhuan 这里的例子是模拟render-content中，节点上的点击事件通过节点数据来切换节点位置，直接修改数据会导致展开的节点折叠。真实场景如下：
```
renderContent(h, { node, data, store }) {
      return (
        <span>
          <span>
            <span>{data.name}</span>
          </span>
          <span>
            <el-button-group>
              <el-button type="success" on-click={() => this.up(node, data)} />
```
```
up(node, data) {
      const parent = node.parent;
      const children = parent.data.children || parent.data;
      const index = children.findIndex(d => d.id === data.id);
      const temp = children[index - 1];
      this.$set(children, index - 1, children[index]);
      children.splice(index, 0, temp);
    },
```
问题是，一节节点可以达到预期，二级节点数据修改了，UI没有更新

**Comment by elfman** [comment]
并不推荐直接修改内部数据来实现切换节点，更新数据时要保持节点可以使用`default-expanded-keys`

**Comment by linliya** [comment]
可以通过`updateKeyChildren`更新节点对应的子节点的数据
