### ISSUE TITLE
[Feature Request] Get nested data in table prop

### ISSUE THREAD

**Issue by Yorgovan** [ElemeFE/element#8597]
### Existing Component
Yes

### Component Name
el-table, el-table-column

### Description
Is it possible to get nested data in prop for table column?
For example I get json like this:
```
[{
  "id":1,
  "name":"John",
  "gender": {
    "id": 1,
    "name":"Male"
  }
}]
```

When I set ```prop="name"``` for table column I get it in table but when I set ```prop="gender.name"``` I get error in console 'Cannot read property 'name' of null'

**Comment by douxc** [comment]
I tried. It worked normally. Could you paste your code here?

**Comment by Yorgovan** [comment]
@douxc here it is:
```
  export default {
    data () {
      return {
        tableData: [],
        usersURL: 'test.api'
      }
    },
    methods: {
      getUsers () {
        this.$http.get(this.usersURL).then(
          function (response) {
            this.tableData = response.body.data
          }, function (error) {
          console.log(error)
        })
      }
    },
    mounted () {
      this.getUsers()
    }
  }
```

and in table component I call it with `:data="tableData"`

**Comment by Leopoldthecoder** [comment]
Issues without a reproduction link will be closed directly.

**Comment by Yorgovan** [comment]
I also have tag on that column and now I realised when I remove it than it works fine.
Tag code is from examples like this (it's in pug format):

``` js
el-table-column(prop="gender.name" :label="$t('tables.gender')")
  template(slot-scope="scope")
    el-tag(
      :type="scope.row.gender.name === 'Male' ? 'primary' : 'success'"
      close-transition
    ) {{scope.row.gender.name}}
```

**Comment by douxc** [comment]
@Yorgovan https://jsfiddle.net/yyjcnef3/ em...

**Comment by Yorgovan** [comment]
@douxc thanks, it works like this but in my example it just returns error. It must be because of some other components, I'll have to check it further.
