### ISSUE TITLE
[Bug Report] is misplaced when there is a fixed column and a lateral scroll bar on the left

### ISSUE THREAD

**Issue by vboyok** [ElemeFE/element#8604]
### Element UI version
2.0.7

### OS/Browsers version
windows10/chrome62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/9svcau55/3/](https://jsfiddle.net/9svcau55/3/)

### Steps to reproduce
https://jsfiddle.net/9svcau55/3/

### What is Expected?
https://jsfiddle.net/9svcau55/1/
合计行正常显示

### What is actually happening?
https://jsfiddle.net/9svcau55/3/
合计行显示错位

**Comment by Leopoldthecoder** [comment]
Duplicate of #7875
