### ISSUE TITLE
[Bug Report] when <el-menu> include by <el-aside width="65px">

### ISSUE THREAD

**Issue by mario56** [ElemeFE/element#8607]
### Element UI version
2.0.7

### OS/Browsers version
mac/chrome

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/2n56jgjv/](https://jsfiddle.net/2n56jgjv/)

### Steps to reproduce
see code in https://jsfiddle.net/2n56jgjv/

### What is Expected?
when <el-menu> set collapse to true.  hove the <el-submenu> hope to see all sub menu item.

### What is actually happening?
hove menu icon can't see sub items, due to I use <el-aside width="65px"> to include <el-menu>.

.el-aside css class has attribute {overflow: auto} , which will hide sub menu items.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/8241
