### ISSUE TITLE
[1.0.0.rc8] Input 组件样式问题

### ISSUE THREAD

**Issue by niceue** [ElemeFE/element#861]
### ElementUI version
1.0.0-rc.8

### OS/Browers version
win10/Chrome 53

### Vue version
2.0.3

### Reproduction Link
https://jsfiddle.net/niceue/66mnsgLj/

### Steps to reproduce
添加后置元素： `<el-button type="primary" slot="append" icon="search"></el-button>`
添加 loadding 图标：`<el-input placeholder="请输入内容" icon="loading"></el-input>`

### What is Expected?
按钮表现为 primary 的样式
loadding 图标像其他图标一样

### What is actually happening?
按钮仍是灰色背景，loading 图标位置不对
![image](https://cloud.githubusercontent.com/assets/1498854/20036467/1aeb68ca-a444-11e6-96b9-cf7ef6bb1306.png)

**Comment by baiyaaaaa** [comment]
1. loading icon的问题已修复
2 前后置内容的按钮和下拉组件的样式是固定的。
