### ISSUE TITLE
[Bug Report] wanne a "before-click" option to stop node-click(想要有个点击前判断的事件)

### ISSUE THREAD

**Issue by xxholly32** [ElemeFE/element#8613]
### Element UI version
1.4.12

### OS/Browsers version
win10/chrome 62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/xxholly32/mmx38qxw/61/](https://jsfiddle.net/xxholly32/mmx38qxw/61/)

### Steps to reproduce
所有节点都能选，没有选之前的判断并阻止的功能

### What is Expected?
由于节点的一些特殊性，希望有些节点不能被选中

### What is actually happening?
所有节点都能够选中，没有一条数据是不能选的

**Comment by Leopoldthecoder** [comment]
为何不使用 `disabled`？

**Comment by xxholly32** [comment]
@Leopoldthecoder 

disabled | 指定节点选择框是否禁用

您说的这个是针对多选的情况

我这个是单选的，不让选的情况

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
