### ISSUE TITLE
[Bug Report] el-select allow-create doesn't display newly created OBJECT items

### ISSUE THREAD

**Issue by hemulin** [ElemeFE/element#8617]
### Element UI version
2.0.5

### OS/Browsers version
Ubuntu 16.04 /  Chrome 62.0.3202.94 (Official Build) (64-bit)

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/ydz2cdwx/1/](https://jsfiddle.net/ydz2cdwx/1/)

### Steps to reproduce
1. Choose some option in the select.
2. Type some characters in the select input and use mouse pointer or arrow keys to select the drop-down menu item

### What is Expected?
The "selected" items will be displayed correctly after selecting the newly created item

### What is actually happening?
The new created item is displayed as a new tag with empty string.

Looking into the vue-dev-tools console, one can see that the new item have `currentLabel: ""` under the ElSelect component

**Comment by Leopoldthecoder** [comment]
You need to use a computed property to transform the newly created option to an object. Internally Select doesn't have the new object as its option, so it cannot link the object with its value. https://jsfiddle.net/ydz2cdwx/2/
