### ISSUE TITLE
[Feature Request] Ability to mock the ID generator

### ISSUE THREAD

**Issue by etnbrd** [ElemeFE/element#8621]
### Existing Component
Yes

### Component Name
All

### Description
I am using Jest and its snapshot feature to test some views are correctly generated.

However, as Element UI randomly generates IDs for components, the snapshot are non-deterministic, and the tests fails.

Here is an example of the html rendered by a collapse component :
```
          <div role="tabpanel"
                 aria-hidden="true"
                 aria-labelledby="el-collapse-head-7804"
                 id="el-collapse-content-7804"
                 class="el-collapse-item__wrap"
                 style="display: none;"
            >
```
The aria-labelledby, and id attributes are randomly generated, hence non-deterministic, and make the snapshot test fail.

Would it be possible to allow the overriding of the generation of id.
Or maybe, is it already possible ?

**Comment by liril-net** [comment]
I have moved this to product backlog, so i would close this issue.

**Comment by kght6123** [comment]
@liril-net @furybean 
Is this function addition already supported?
I can't find the document, Issue, or PR and I don't know how to use it, so please let me know.

**Comment by jaa134** [comment]
Agreed! I am running into this issue as well in Element UI plus. Snapshots are a very powerful feature for Jest and it is unfortunate that Element-ui does not support them.
