### ISSUE TITLE
[Feature Request] element2.0.7 set layout doubts [NOT ISSUE]

### ISSUE THREAD

**Issue by thlws** [ElemeFE/element#8622]
### Existing Component
是

### Component Name
Container

### Description
element2.0.7  如何设置el-aside左边固定，而且不影响右边布局，像下面这个布局，用作后台控制，左边要固定起来（不好意思，刚接触，不太会用）。

```
<el-container>
  <el-header>Header</el-header>
  <el-container>
    <el-aside width="200px">Aside</el-aside>
    <el-main>Main</el-main>
  </el-container>
</el-container>
```

PS，如果可以希望官方能出一个示例项目，类似https://pro.ant.design 。

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
