### ISSUE TITLE
[Feature Request] Fullscreen loading should be able to be configured if target doesn't exist

### ISSUE THREAD

**Issue by Kris-Lee-SH** [ElemeFE/element#8626]
### Existing Component
Yes

### Component Name
Loading

### Description
If we have 2 components:

comp 1, it depends on 2 (or more) api request. For example, fetch filter data first then request data with the result in `mounted` function, both of these 2 api request will generate loading before request and close it after request with `Loading.service`;

comp 2, some normal component.

# -----

First we show comp1 and after mount it, we switch to comp2 (with destroying comp1). At this moment if the filter data request has not returned, it will cause a fullscreen loading!
That's because when we destroy comp1 while it's still requesting filter data, once the filter data was returned and it start data requesting, and before data requesting it create a loading with `Loading.service({ target: comp1_refs_loadingDom })`. However, this `comp1_refs_loadingDom` dom does not exist.

# -----
So, will u add a props or some api else to stop creating fullscreen loading once it can't find the target dom with `option.target`?

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
