### ISSUE TITLE
见过最任性的组件团队

### ISSUE THREAD

**Issue by luxueyan** [ElemeFE/element#8628]
1.x版本的不维护可以，当时为什么要把文档删掉，你让这些老项目不升级的情何以堪

**Comment by firesh** [comment]
1.4的文档有：http://element-cn.eleme.io/1.4/#/zh-CN/component/installation

**Comment by luxueyan** [comment]
但是我想看1.3的

**Comment by firesh** [comment]
拉代码，切到tag 1.3.x，`npm run dev`

**Comment by luxueyan** [comment]
好吧！谢谢
