### ISSUE TITLE
[Feature Request] adds the function of the custom rendering line cell display

### ISSUE THREAD

**Issue by vboyok** [ElemeFE/element#8633]
### Existing Component
是

### Component Name
table

### Description
增加 通过类似render-header 或 Scoped slot的方式，可以自定义渲染合计行单元格的内容，而不仅仅是通过summary-method自定义显示文本。
例如：我希望将【合计】两个字做成可点击的按钮，动态切换显示 页小计 或 总计

**Comment by Leopoldthecoder** [comment]
请使用 `append` 具名 slot
