### ISSUE TITLE
[Bug Report] when use el-menu build failed.

### ISSUE THREAD

**Issue by daviyang35** [ElemeFE/element#8634]
### Element UI version
2.0.7

### OS/Browsers version
macOS 10.13.1/Chrome 62.0.3202.94 64bit

### Vue version
2.5.9

### Reproduction Link
[https://github.com/daviyang35/element-ui-error](https://github.com/daviyang35/element-ui-error)

### Steps to reproduce
# use CLI install new vue project
vue init webpack demo
cd demo
npm install

# use element-ui
npm install element-ui -S

change project file pls check project source [https://github.com/daviyang35/element-ui-error](https://github.com/daviyang35/element-ui-error)
when i add el-menu tag in navigatorView,the builder while report error.

### What is Expected?
build successed.

### What is actually happening?
 error  in ./node_modules/element-ui/packages/tooltip/src/main.js

Module parse failed: Unexpected token (77:8)
You may need an appropriate loader to handle this file type.
|     if (this.popperVM) {
|       this.popperVM.node = (
|         <transition
|           name={ this.transition }
|           onAfterLeave={ this.doDestroy }>

 @ ./node_modules/element-ui/packages/tooltip/index.js 1:0-33
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/element-ui/packages/menu/src/menu-item.vue
 @ ./node_modules/element-ui/packages/menu/src/menu-item.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/NavigatorView.vue
 @ ./src/components/NavigatorView.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by Leopoldthecoder** [comment]
You don't need to import individual components in these files:
![image](https://user-images.githubusercontent.com/10095631/33534211-064286c4-d8e1-11e7-8176-aee336feddca.png)

You already registered them in `main.js`.

**Comment by daviyang35** [comment]
The component is webstorm 2017.3 automated import.
I remove components import from this 3 files, the build error already exist.

I test it, just error when i use el-menu-item components.

**Comment by daviyang35** [comment]
@Leopoldthecoder pls check el-menu-item component in 2.0.7
