### ISSUE TITLE
[Bug Report] el-switch can not use type of number / el-switch component cannot use a number type value

### ISSUE THREAD

**Issue by ybhuxiao** [ElemeFE/element#8635]
### Element UI version
2.0.7

### OS/Browsers version
windows10/chrome62.0.3202.89

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/tcgnjvqu/](https://jsfiddle.net/tcgnjvqu/)

### Steps to reproduce
项目中，value5: 100不能正常启动el-switch，只能写成value5: "100"

### What is Expected?
可以支持number类型

### What is actually happening?
只支持bool 和 string

**Comment by Darkphooo** [comment]
你可以在`el-switch`上将`active-value`和`inactive-value`绑定到number类型的变量上以使用number类型
demo在这里：https://jsfiddle.net/tcgnjvqu/1/

**Comment by Leopoldthecoder** [comment]
你少了冒号：https://jsfiddle.net/tcgnjvqu/2/

**Comment by ybhuxiao** [comment]
多谢
