### ISSUE TITLE
[Feature Request] Table column shows hidden (toggle) table column display hidden function

### ISSUE THREAD

**Issue by EthanOrange** [ElemeFE/element#8637]
### Existing Component
是

### Component Name
Table

### Description
表格列显示隐藏功能
在多列业务且需要编辑的表格中,增加一个dropdown菜单控制列的显示和隐藏是非常需要的
能大大提高表格的可使用性
当前表格column不接受v-show指令, 只接受v-if指令, 在进行v-if切换时 整个表格布局不能正确更新, 调用表格的doLayout方法也未起作用

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by TomCwl** [comment]
这个功能现在还没有吗？
