### ISSUE TITLE
建议2.0提供一套类似1.0的样式主题，太丑了

### ISSUE THREAD

**Issue by LoverMaker** [ElemeFE/element#8639]
Element UI version

1.4.11

OS/Browsers version

Mac OS

Vue version

2.5.9

Reproduction Link

None

Steps to reproduce

none

What is Expected?

我们在升级到2.0后，发现样式变化大，变丑了，设计师。希望在2.0提供一套类似1.0风格的样式主题

What is actually happening?

样式太难看，这样下去，element的用户可能会逐渐流向iview

**Comment by milu2003** [comment]
太丑了太丑了，间距什么的，都没法看。
