### ISSUE TITLE
[Feature Request] vue version is inconsistent with nuxt.js SSR(2.x)

### ISSUE THREAD

**Issue by yoyo837** [ElemeFE/element#8640]
### Existing Component
Yes

### Component Name
All

### Description
element-ui 2.x requires vue 2.5+ , nuxt.js currently uses vue 2.4.2, and report elFormItem error if element-ui uses 2.4.x.
Vue version and nuxt.js SSR inconsistencies may cause inconsistent dom rendering front and back end, it maybe report this error:
`
 [vue.runtime.esm.js: 570 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content . This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.]`

Is element-ui could be compatible with vue 2.4.2?

**Comment by yoyo837** [comment]
目前element-ui 2.x依赖vue 2.5+，nuxt.js当前使用vue 2.4.2，如果element-ui使用2.4.x，则会报elFormItem错误。
如果ssr情况下使用不同vue版本，则可能会出现同一个页面前后端DOM不一致的情况(刷新页面是后端渲染，跳转过去是前端)，element-ui 2.x是否可以考虑兼容到vue 2.4.2呢？

目前nuxt.js的最新一个版本发布于9月7号，且使用~2.4.2依赖vue及vue相关的包。

**Comment by Leopoldthecoder** [comment]
`elFormItem` 的报错需要 Vue 2.5 提供的 inject 默认值功能才能解决，所以这块 Element 没什么办法。

目前可能只能等 Nuxt 更新依赖。或者，其实 `elFormItem` 的报错并不影响使用，可以容受的话也可以用 Vue 2.4

**Comment by yoyo837** [comment]
猜测了很多可能性，设置都把nuxt.js fork下来改改自己发npm了，都不行，最后在v-for的外面套了两层div包起来居然解决了...

**Comment by levy9527** [comment]
楼上的兄弟，我遇到了同样的问题😭

**Comment by levy9527** [comment]
现在nuxt已把vue更新至2.5.x, 记得把element作为插件时，记得设置 `ssr: true` ![image](https://user-images.githubusercontent.com/9384365/36132266-1eae538e-10b1-11e8-9245-25e3cea9104a.png)
`
