### ISSUE TITLE
[Bug Report] with drop-down input, arrow style exception when pull down

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#8644]
### Element UI version
2.0.7

### OS/Browsers version
osx

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/1ccacszh/](https://jsfiddle.net/1ccacszh/)

### Steps to reproduce
下拉查看箭头位置

### What is Expected?
正常

### What is actually happening?
不正常

**Comment by Leopoldthecoder** [comment]
这种情况请自行覆盖 CSS：https://jsfiddle.net/1ccacszh/1/
