### ISSUE TITLE
table的筛选，选中第一次后，后续无法更改选中项

### ISSUE THREAD

**Issue by llsy** [ElemeFE/element#8649]
版本：2.0.7

描述：
使用了table的Table-column Attributes：filters，第一次选择一个筛选项，可以正常选中，第二次选择另一个筛选项，正常触发了filter-change，但是筛选项的选中项无变更

![image](https://user-images.githubusercontent.com/18343441/33544168-a833dc70-d914-11e7-942f-356237f75177.png)

**Comment by HuaRongSAO** [comment]
我也遇到了, 你是怎么解决的

**Comment by llsy** [comment]
我当时记得好像是升级，npm导致的，把node_module包全清了，重新装一次就好了。
