### ISSUE TITLE
[Bug Report] table component causes the page to not load

### ISSUE THREAD

**Issue by hzm07** [ElemeFE/element#8652]
### Element UI version
2.0.7

### OS/Browsers version
google

### Vue version
2.3.2

### Reproduction Link
[https://github.com/hzm07/elementTests/blob/4d44202acc6be4d7661a13abea81197bbd941de3/element2.0.7/index.html](https://github.com/hzm07/elementTests/blob/4d44202acc6be4d7661a13abea81197bbd941de3/element2.0.7/index.html)

### Steps to reproduce
Running files： index.html
this page cann't load

### What is Expected?
this page is normal display

### What is actually happening?
this page cann't load

**Comment by Leopoldthecoder** [comment]
Vue 版本太低了，请使用 2.5.2 以上的 Vue。

**Comment by guhongxin** [comment]
Vue使用版本为"vue": "^2.5.2"

**Comment by hankdandan** [comment]
我的版本是2.8.2，大概800个数据的样子，页面要卡死好几秒才能操作其他的，不知道该咋办了

**Comment by Yuppiezero** [comment]
2.9.6也会这样，并且空数据直接卡死页面
