### ISSUE TITLE
[Bug Report] remote search, remoteMethod method is not executed by default?

### ISSUE THREAD

**Issue by leeyinglee** [ElemeFE/element#8653]
### Element UI version
2.0.7

### OS/Browsers version
MAC chrome 62

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/614bofpz/4/](https://jsfiddle.net/614bofpz/4/)

### Steps to reproduce
element-ui@1.4.12中，远程搜索，如果有默认值，remoteMethod方法则会执行,下拉框中会有选项，然而2.0.7中下拉框中无数据

### What is Expected?
下拉框中有默认的数据显示

### What is actually happening?
下拉框无数据

**Comment by Leopoldthecoder** [comment]
1.4.x 的行为是一个 bug，`remote-method` 应该仅在用户输入关键词时才触发。如果需要显示默认值，请确保初始状态中 `options4` 含有这个选项。
