### ISSUE TITLE
[Feature Request] select Add Item shortcut

### ISSUE THREAD

**Issue by Yuliang-Lee** [ElemeFE/element#8656]
### Existing Component
是

### Component Name
el-select

### Description
now
when we need add an item to select, first need to input something in input ,then **click** the item in dropdown, it's inconvenience.

wish improve：
after input something in input, tap **enter** key to add item. 

example
https://codepen.io/Yuliang-Lee/pen/pdYEzw

**Comment by Leopoldthecoder** [comment]
Use `default-first-option`: https://jsfiddle.net/jqat4sq5/
