### ISSUE TITLE
Does the [Bug Report] el-select el-option tag do not use the XML abbreviation syntax?

### ISSUE THREAD

**Issue by Fangty1** [ElemeFE/element#8659]
### Element UI version
2.0.4

### OS/Browsers version
windows 7

### Vue version
2.5.3

### Reproduction Link
[  https://jsfiddle.net/whaex5n5/1/](  https://jsfiddle.net/whaex5n5/1/)

### Steps to reproduce
https://jsfiddle.net/whaex5n5/1/

### What is Expected?
使用如下样式的 el-option 无法被加载
        <el-option label="CCC" value='ccc' />

### What is actually happening?
https://jsfiddle.net/whaex5n5/1/

**Comment by Leopoldthecoder** [comment]
不建议这么写，有时会渲染错误：
![image](https://user-images.githubusercontent.com/10095631/33587755-7d7100bc-d9aa-11e7-8cb0-3e3984c5b3ad.png)

**Comment by Fangty1** [comment]
这是在哪个环节的限制， 从技术上将能解决吗？
