### ISSUE TITLE
[Bug Report] Autocomplete component asynchronously loading data BUG

### ISSUE THREAD

**Issue by zuopengcy** [ElemeFE/element#8665]
### Element UI version
2.0.7

### OS/Browsers version
Chrome 62.0

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/76xj7y2b/](https://jsfiddle.net/76xj7y2b/)

### Steps to reproduce
1. 输入‘三全鲜食1’
2. 快速删除所有的数据

### What is Expected?
组件已设置了trigger-on-focus=false，删除所有的搜索内容后，应该默认为清空操作，回到最初始的状态

### What is actually happening?
组件按照最后一个被删除的字符进行远程搜索，并弹出了选择数据

**Comment by ar53n** [comment]
So let fix it just need delete `!value` https://github.com/ElemeFE/element/blob/542d0485c63f63c96aaba4795c6040b105769686/packages/autocomplete/src/autocomplete.vue#L174-L181

**Comment by ziyoung** [comment]
@ar53n 应该不是这样。
https://github.com/ElemeFE/element/blob/df7bbe2ba4bcfa8c4cd866c58985548777eb9366/packages/autocomplete/src/autocomplete.vue#L152-L162

`fetchSuggestions` 的第二个参数是一个**回调函数**。之所以出现这样的问题，下面这段代码先执行的。在此之后回调函数调用的。

https://github.com/ElemeFE/element/blob/df7bbe2ba4bcfa8c4cd866c58985548777eb9366/packages/autocomplete/src/autocomplete.vue#L165-L168
