### ISSUE TITLE
[Feature Request] tree table

### ISSUE THREAD

**Issue by zxywd** [ElemeFE/element#8666]
### Existing Component
否

### Component Name
tree table

### Description
element-ui中有没有tree-table的控件，如何用element-ui实现这样的控件？就像附件中的
![treetable](https://user-images.githubusercontent.com/5567567/33593870-60de75d4-d9cc-11e7-99a7-f47d3fa2d4ed.png)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
