### ISSUE TITLE
[Bug Report] [Select] - packet selector multiselect, selected after the scroll position error

### ISSUE THREAD

**Issue by SidneySong** [ElemeFE/element#8668]
### Element UI version
2.0.7

### OS/Browsers version
win10/chrome 60.0.3112.90

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
应用场景：应用在城市选择的功能中，选择使用select选择器
具体问题：在设置分组多选配置后选中条目后，滑动条滑动位置定位出错，导致给用户交互及其不好。

### What is Expected?
在选择器控件中选中条目，滑动条位置不做改变，当前单击除选择浮框外的地方关闭选择浮框，这样带给用户更好的交互。

### What is actually happening?
可能在之前大家并未有或极少数去使用select选择器的分组多选来开发应用。

**Comment by SidneySong** [comment]
第一次在element-ui上提问题，大家请多担待！

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
