### ISSUE TITLE
The [Bug Report] menu component, when the unfolded, is wrong, and can not be compiled to unfold

### ISSUE THREAD

**Issue by JasonBai007** [ElemeFE/element#8670]
### Element UI version
2.0.7

### OS/Browsers version
windows

### Vue version
2.3.3

### Reproduction Link
[https://github.com/JasonBai007/vue-seed](https://github.com/JasonBai007/vue-seed)

### Steps to reproduce
yarn run dev 
单击左上角的按钮，让左侧导航菜单展开或折叠
控制台报错，但是菜单能展开或折叠
yarn run build
yarn run server
打开：http://localhost:3000/index.html
预览生成的文件
单击左上角的按钮，让左侧导航菜单展开或折叠，此时，浏览器卡死

### What is Expected?
开发时，不报错，编译后，能正常使用

### What is actually happening?
开发时，报错，编译后，左侧导航菜单不能展开或折叠，同时导致浏览器卡死

**Comment by Leopoldthecoder** [comment]
Element 2.x 最低兼容至 Vue 2.5.2，请升级 Vue 版本。

**Comment by JasonBai007** [comment]
非常感谢，膜拜大神
