### ISSUE TITLE
[Bug Report] [table] when the table header is too long, the sort icon style has a problem

### ISSUE THREAD

**Issue by SmallBlanckPig** [ElemeFE/element#8671]
### Element UI version
2.0.7

### OS/Browsers version
win7/chrome 60.0.3112.90

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/avnu6vy4/](https://jsfiddle.net/avnu6vy4/)

### Steps to reproduce
基本表格的编写即可

### What is Expected?
当表头文字过长时，排序图标样式依然正常

### What is actually happening?
当表头文字过长时，排序图标样式有问题，详见 https://jsfiddle.net/avnu6vy4/

**Comment by Leopoldthecoder** [comment]
暂时可以加一条 CSS 解决：https://jsfiddle.net/avnu6vy4/2/
```CSS
.el-table .caret-wrapper {
  position: relative;
}
```

下个版本会修复。
