### ISSUE TITLE
Implementing a scrollable dropdown

### ISSUE THREAD

**Issue by michaelbukachi** [ElemeFE/element#8676]
How does one implement a scrollable dropdown menu? I have a lot of items I need to populate a dropdown with.

**Comment by athena0304** [comment]
I've met the same problem

**Comment by michaelbukachi** [comment]
@athena0304 Use the select element instead

**Comment by athena0304** [comment]
@michaelbukachi 
here is the solution:
https://jsfiddle.net/athena0304/9z2n502k/
just add css
