### ISSUE TITLE
[Bug Report] Carousel Methods: setActiveItem, prev, next cannot be called successfully by child elements which are contained in Carousel-Item

### ISSUE THREAD

**Issue by YuanhengMu** [ElemeFE/element#8678]
### Element UI version
1.4.12

### OS/Browsers version
Google Chrome Version 62.0.3202.94 

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/72Lggn9o/](https://jsfiddle.net/72Lggn9o/)

### Steps to reproduce
Function setActiveItem cannot be called successfully when the button of "Go First" is in el-carousel-item

### What is Expected?
When the button of  "Go First" in el-carousel-item is clicked, the el-carousel will go to next  el-carousel-item

### What is actually happening?
Function setActiveItem cannot be called successfully when the button of "Go First" is in el-carousel-item

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/72Lggn9o/2/
