### ISSUE TITLE
The use of fixed in [Bug Report] table is misplaced

### ISSUE THREAD

**Issue by allny** [ElemeFE/element#8679]
### Element UI version
2.0.7

### OS/Browsers version
 62.0.3202.94（正式版本） （32 位）

### Vue version
2.2.2

### Reproduction Link
[https://jsfiddle.net/j9kh9e86/](https://jsfiddle.net/j9kh9e86/)

### Steps to reproduce
使用el-table求和时 ，同时使用fixed固定然后就错位了  还有el-table 中fixed的在没有数据时下面的滚动，到fixed范围下是不能选定滚动 

### What is Expected?
el-table可以fixed和求和一起使用

### What is actually happening?
el-table和ixed一起使用就错位了

**Comment by Leopoldthecoder** [comment]
Duplicate of #5415
