### ISSUE TITLE
菜鸡求教：switch开关的width的属性如何设置，能给个demo吗？

### ISSUE THREAD

**Issue by AppHL** [ElemeFE/element#868]
`<el-switch
      v-model="msg"
      width=58
      change="switchAction">
    </el-switch>`
按照如上方法，width报错只能解析成字符串，求个demo谢谢

**Comment by Leopoldthecoder** [comment]
```html
<el-switch v-model="msg" :width="58" @change="switchAction"> </el-switch>
```

**Comment by AppHL** [comment]
我试了一下，好像还是不行，虽然没有刚才那样的报错了，但是宽度不起作用（组件宽度会变成2px）

**Comment by Leopoldthecoder** [comment]
Element 版本是？

**Comment by AppHL** [comment]
npm安装的  ^1.0.0-rc.7

**Comment by AppHL** [comment]
哦 我看到更新的日志了 8修复了 我去安装新版本

**Comment by Leopoldthecoder** [comment]
是的，rc.8 就可以了
