### ISSUE TITLE
[Feature Request] Easier Table Integration

### ISSUE THREAD

**Issue by steffanhalv** [ElemeFE/element#8684]
### Existing Component
Yes

### Component Name
Table

### Description
Current table integration behaviour is more difficult then neccesary.

Why not just use a v-for loop instead?

I think about this each time I create a new table..

**Comment by Leopoldthecoder** [comment]
A v-for loop for what?

**Comment by steffanhalv** [comment]
Instead of:

<el-table v-model='mymodel'>
....

You could instead:

<el-table>
<el-table-header></el-table-header>
<el-table-body>
<el-tr v-for='item in items'></el-tr>
...

It would be easier for templating

**Comment by steffanhalv** [comment]
Instead of:

`<el-table v-model='mymodel'>`
....

You could instead:

```<el-table>
<el-table-header></el-table-header>
<el-table-body>
<el-tr v-for='item in items'></el-tr>```
...

It would be easier for templating

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
