### ISSUE TITLE
[Bug Report] Table Fixed aggregated if there is a horizontal scroll of page disorder

### ISSUE THREAD

**Issue by denonzhu** [ElemeFE/element#8686]
### Element UI version
2.0.7

### OS/Browsers version
Chrome 62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/3wt1d36j/2/](https://jsfiddle.net/3wt1d36j/2/)

### Steps to reproduce
表格Fixed 属性   show-summary 当出现横向滚动的时候

### What is Expected?
希望样式不要错乱

### What is actually happening?
会导致fixed列 样式错乱

**Comment by denonzhu** [comment]
这个是在计算fixed 高度的时候 出现的偏差，希望官方能尽快解决，谢谢

**Comment by denonzhu** [comment]
我也是这个bug ，没想到你发的比我早，这个只要官方对fixed列的计算高度 调整下就好了

**Comment by Leopoldthecoder** [comment]
Duplicate of #5415
