### ISSUE TITLE
[Bug Report] Upload: when upload items reach the limit, still showing the upload button

### ISSUE THREAD

**Issue by firesh** [ElemeFE/element#8689]
### Element UI version
0.1.0

### OS/Browsers version
Mac / Chrome 62.0.3202.94

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/0amqh5xq/](https://jsfiddle.net/0amqh5xq/)

### Steps to reproduce
1. the limit is set to 2;
2. upload 2 small image

### What is Expected?
The upload button should be hidden.

### What is actually happening?
The upload button still there but not works to upload any more image.

**Comment by FranckFreiburger** [comment]
I also expect the behavior described by @firesh. Or at least add a new property `:show-upload-area` (true by default) that allow to only show the list.
