### ISSUE TITLE
[Feature Request] global settings show-timeout and hide-timeout

### ISSUE THREAD

**Issue by ccqgithub** [ElemeFE/element#8695]
### Existing Component
是

### Component Name
el-dropdown, el-select, el-datepicker 等等...

### Description
全局设置show-timeout, hide-timeout, 和第一个弹窗初始的z-index

**Comment by Leopoldthecoder** [comment]
Global `z-index` is supported in #11257. We have no plan to support `show-timeout` and `hide-timeout`.
