### ISSUE TITLE
The columns of the [Feature Request] table are also returned remotely, and the prop value of the column is only valued until the background is returned. Want to implement the default sort (default-sort), the local try, as if not. But for the first column to be determined, it is possible to set up the default-sort directly. I would like to ask how to set up the default sort field in the case of remote request table data.

### ISSUE THREAD

**Issue by Angelsindevil** [ElemeFE/element#8697]
### Existing Component
是

### Component Name
table

### Description
表格的列也是通过远程返回的，列的prop值只有等到后台返回才有值。想要实现默认排序（default-sort）,自己本地试了下，好像是不行的。但是对于一开始列是确定的，直接设置default-sort是可以的。我想问下，在远程请求表格数据的情况下，要怎么设置默认排序字段？还有就是当重新请求后台数据时，能重新设置default-sort的值吗？（因为每次请求的排序字段都是不一样的）

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
