### ISSUE TITLE
[Bug Report] Input 输入框--远程搜索bug

### ISSUE THREAD

**Issue by Tiny-Tao** [ElemeFE/element#8698]
### Element UI version
2.0.7

### OS/Browsers version
Google Chrome 版本 62.0.3202.94

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
在输入框中输入‘honey’,搜索结果为空

### What is Expected?
期待能够搜索出'Hot honey 首尔炸鸡（仙霞路）'

### What is actually happening?
实际搜索结果为空

**Comment by Tiny-Tao** [comment]
Reproduction Link

https://jsfiddle.net/api/post/library/pure/

**Comment by Leopoldthecoder** [comment]
文档例子的搜索逻辑是
```JS
return (restaurant.value.toLowerCase().indexOf(queryString.toLowerCase()) === 0);
```

搜索方法是自己写的，完全可以实现你想要的效果。
