### ISSUE TITLE
只有一个input的情况下回车会直接提交了。加入<input type="hidden" value="0">也没用

### ISSUE THREAD

**Issue by wdaglb** [ElemeFE/element#8701]
<el-form :inline="true" :model="search" size="mini">

    <el-form-item label="关键词">
      <el-input v-model="search.key" @keyup.enter.native="onSearch" placeholder="ID/账号"></el-input>
    </el-form-item>

    <input type="hidden" value="0">

    <el-form-item>
      <el-button type="primary" @click="onSearch">筛选</el-button>
    </el-form-item>
  </el-form>

**Comment by ciwyaitd** [comment]
@wdaglb 
添加 onsubmit="return false" 即可解决。
`<el-form onsubmit="return false"></el-form>`
