### ISSUE TITLE
[Feature Request] Change event should include previous values and current values

### ISSUE THREAD

**Issue by jmmk** [ElemeFE/element#8705]
### Existing Component
Yes

### Component Name
el-collapse

### Description
The `change` event currently passes a single parameter with the current "active" panels. It would be nice to have both the previous state and the current state to determine what changed

**Comment by wacky6** [comment]
https://jsfiddle.net/oxr1ft5d/

We want to keep `change`'s parameter (and behavior) consistent with W3C style.

**Comment by jmmk** [comment]
@wacky6 that makes sense

Thanks for the example, didn't realize watchers worked like that
