### ISSUE TITLE
[Feature Request] iView has a complete background solution, and it is strongly recommended that ELE keep pace, and individuals prefer ELE style.

### ISSUE THREAD

**Issue by 420577898** [ElemeFE/element#8707]
### Existing Component
是

### Component Name
iview已有后台完整解决方案，强烈建议ELE也跟上步伐，个人还是比较喜欢ELE风格的

### Description
iview已有后台完整解决方案，强烈建议ELE也跟上步伐，个人还是比较喜欢ELE风格的

**Comment by Aibric** [comment]
+1

**Comment by liril-net** [comment]
@420577898 
目前官方没有相关的计划，所以我先关了这个 issue 了。可以先用 [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)。

There are no official plan currently, so i would close this issue. Maybe you can use [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) as a replace.
