### ISSUE TITLE
dialog中的input组件的autofocus属性只在第一次弹出时有用

### ISSUE THREAD

**Issue by tlzzu** [ElemeFE/element#8708]
如题

**Comment by u10k** [comment]
`<el-input v-focus></el-input>`

`  directives: {
    focus: {
      inserted: function(el) {
        console.log('%cinsertedel', 'color:red;font-size:16px;text-shadow:1px 1px 1px blue;', el)
        el.querySelector('input').focus()
      }
    }
  },`
