### ISSUE TITLE
[BUG REPORT] 带自动完成功能的 INPUT 输入框列表中出现两个 highlight 项

### ISSUE THREAD

**Issue by KingMario** [ElemeFE/element#871]
![image](https://cloud.githubusercontent.com/assets/3956876/20045127/8c319816-a4d9-11e6-9e73-cd3e463a6588.png)
官方示例中，如果鼠标放到自动完成列表某条目上，当使用键盘的上下键导航时，会出现两个 highlight 项。

**Comment by baiyaaaaa** [comment]
这是正常效果，鼠标的高亮是hover的效果

**Comment by KingMario** [comment]
参考我们的 搜索结果 自动完成：http://support.waylens.com/
我们也有 hover 效果，不过我们解决了两个 highlight 的问题。
当然，你们开发的组件，你们说了算。

**Comment by baiyaaaaa** [comment]
hover效果的背景色是出现了失误，应该是和select组件相同的灰色，rc9会做修正。我们保持把selectd和hover的效果做区分。
