### ISSUE TITLE
[Bug Report] datetimepicker is not changed after manual deletion of text data

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8711]
### Element UI version
2.0.7

### OS/Browsers version
w10/chrome62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/t4td3ef6/](https://jsfiddle.net/t4td3ef6/)

### Steps to reproduce
选择一个日期，已选显示已选日期
手工删除输入框内的日期文本（删完，删一半会因为格式不对复位），已选未变
点击输入框后边的清除按钮，已选显示为空

### What is Expected?
手工删和点清除按钮应一致，显示应与实际数据一致

### What is actually happening?
不一致

**Comment by Leopoldthecoder** [comment]
Fixed in #9409
