### ISSUE TITLE
[Bug Report] datetimepicker set the icon dislocation after display:inline

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8716]
### Element UI version
2.0.7

### OS/Browsers version
chrome62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/cpmfbk69/](https://jsfiddle.net/cpmfbk69/)

### Steps to reproduce
如图

### What is Expected?
图标居中

### What is actually happening?
如图

**Comment by Leopoldthecoder** [comment]
这种情况自己加一条样式吧：https://jsfiddle.net/cpmfbk69/1/
