### ISSUE TITLE
 [Feature Request] The Table table needs to use a more efficient way to load the data

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#8717]
### Existing Component
是

### Component Name
Table

### Description
当表格的行、列数据非常多的时候（如30列，有1000条行数据），此时，页面运行将非常缓慢，内存占用极大甚至浏览器直接崩溃。

这种问题是由于表格的显示方式造成的，现有的渲染是一次性将全部行全部列都渲染到页面上。当数据非常多的时候，会导致浏览器运行缓慢。

我参考了一些国外的表格渲染方式（如devExtreme），在渲染时可以虚拟的渲染可视区域的表格（可视区域外的数据使用空白的高度/宽度来占位），当表格滚动到某个位置的时候，再事实的将数据加载出来。这样的话效率会非常高。即使是30列、1000条数据，也不会导致浏览器卡死。

强烈建议：Element也引入这样的特性，允许用户配置使用这种方式渲染表格。

例子：https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/

**Comment by K-Wen** [comment]
I have the same question too.
In my vue & electron project, 300 rows, 4 cols el-table become very slow and hardly to use.
I have searched in google and found some ideas to improve the experience:
https://github.com/Akryum/vue-virtual-scroller
and here is the [demo](https://akryum.github.io/vue-virtual-scroller/)

**Comment by furybean** [comment]
Duplicate with #8875. #8875 provide a jsfiddle, so close this one.Please pay attention to the progress of the issue.
