### ISSUE TITLE
i18n reactivity issue

### ISSUE THREAD

**Issue by FranckFreiburger** [ElemeFE/element#8721]
### Element UI version
1.4.12

### OS/Browsers version
any

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/78/](https://jsfiddle.net/mmx38qxw/78/)

### Steps to reproduce
click on "change to en"

### What is Expected?
el-select placeholder message should be in english

### What is actually happening?
nothing

**Comment by furybean** [comment]
设计如此，短期内未计划支持。
