### ISSUE TITLE
[Bug Report] Table table component, dynamic switch column Bug

### ISSUE THREAD

**Issue by liaojw** [ElemeFE/element#8722]
### Element UI version
2.0.7

### OS/Browsers version
MacOS（10.12.6）／Chrome（62.0.3202.94）

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/91/](https://jsfiddle.net/mmx38qxw/91/)

### Steps to reproduce
该Bug就是在使用Table组件的过程中，通过v-if标签来控制多级表头列的显示时，如果该列有多级表头，那么当v-if为false，时，整个table组件会销毁，经排查源码，发现table-column组件的销毁方法被调用了多次，正常情况下应该只是多级表头列被销毁，而不是把整个最顶级的一级表头给销毁掉了。望修复该Bug，谢谢！

### What is Expected?
期待能通过v-if表情，动态切换表头与多级表头

### What is actually happening?
实际把整个表头全部给销毁了

**Comment by Leopoldthecoder** [comment]
牵涉到动态显示隐藏的，建议给 el-table-column 或 el-table 加上 key：https://jsfiddle.net/mmx38qxw/92/ 。例子中的 Math.random() 只是为了说明效果，实际使用任何唯一性的值都行。
