### ISSUE TITLE
[Feature Request] Anchor semantics in elements

### ISSUE THREAD

**Issue by ingria** [ElemeFE/element#8723]

**Comment by ingria** [comment]
Cool issue generator you have ❤️ 
Had to copy paste manually:

Existing Component: Yes
Component Name: el-button
Description: 
I may be doing something wrong, but I didn't find any possibility to create a simple anchor element. Specifically an anchor element styled like button, like bootstrap's <a class=btn>.

**Comment by wacky6** [comment]
So you need a `<a>` tag for button? Any reasons for `<a>` instead of `<button>`?

You can always override el-button's style if you need to.

**Comment by ingria** [comment]
Not really. I'd like to have something like the vue-router's `v-link` directive on buttons (or any other appropriate element).

Reason: I'd like to go to another page by clicking on the button 🤷‍♂️ .

**Comment by wacky6** [comment]
Try add `el-button`'s class name to `<a>` tag. Might work.

**Comment by ingria** [comment]
Yes, this of course will work, but it is a temporary solution. What if the classnames will change in the future?

**Comment by wacky6** [comment]
I don't think classname will change unless we are doing a major version upgrade.
