### ISSUE TITLE
[Bug Report] upload multiple file error

### ISSUE THREAD

**Issue by ThinkRealize** [ElemeFE/element#8729]
### Element UI version
2.0.7

### OS/Browsers version
OS X 10.12.6 / Chrome 62.0.3202.94

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/0x81xhxg/](https://jsfiddle.net/0x81xhxg/)

### Steps to reproduce
1. Click upload button.
2. Select multiple file.

### What is Expected?
Upload success and show file.

### What is actually happening?
Does not show file.

**Comment by Leopoldthecoder** [comment]
Use a real file upload API instead of `https://jsonplaceholder.typicode.com/posts` for `action` prop. As its name suggests, the latter is just a placeholder.

**Comment by ThinkRealize** [comment]
Thanks.
