### ISSUE TITLE
[Bug Report] inputNumber seems to be a problem, today, after the update of the win10 system.

### ISSUE THREAD

**Issue by hasbug** [ElemeFE/element#8730]
### Element UI version
1.4.12

### OS/Browsers version
win10

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/cfmq5v7c/](https://jsfiddle.net/cfmq5v7c/)

### Steps to reproduce
早上，未更新win10的时候貌似还正常。
更新后，单击加减会出现不定数值的增减，一般为1-2.
测试的浏览器：chrome firefox

（win10 的锅？触摸板其他操作都是单击，在这里貌似不算单击？）

### What is Expected?
按照步长来增减  

### What is actually happening?
数值乱跳。有图

提供我录制的图片

![](https://jsfiddle.net/cfmq5v7c/)

**Comment by sofish** [comment]
![](https://s3.ezgif.com/save/ezgif-3-3dcd978002.gif)

**Comment by Leopoldthecoder** [comment]
图片在哪里？

**Comment by hasbug** [comment]
@Leopoldthecoder  http://img.kaixiangshaiwu.com/za/bug.gif

**Comment by Leopoldthecoder** [comment]
在 win10 的 Chrome 上未能重现，而且没有其他用户报类似问题，请确认是否是设备或浏览器插件的问题。
