### ISSUE TITLE
[Bug Report] Multiple Select is shaking

### ISSUE THREAD

**Issue by iwillwen** [ElemeFE/element#8731]
### Element UI version
2.0.6

### OS/Browsers version
macOS 10.13 Chrome 63.0.3239.84

### Vue version
2.5.9

### Reproduction Link
[https://camo.githubusercontent.com/3c3216bc13bb88817be61521a7b068ec00159c9c/68747470733a2f2f73332e657a6769662e636f6d2f736176652f657a6769662d332d336463643937383030322e676966](https://camo.githubusercontent.com/3c3216bc13bb88817be61521a7b068ec00159c9c/68747470733a2f2f73332e657a6769662e636f6d2f736176652f657a6769662d332d336463643937383030322e676966)

### Steps to reproduce
select options to make that display in rows

### What is Expected?
Not shaking

### What is actually happening?
Shaking just like the video shows

**Comment by Leopoldthecoder** [comment]
I cannot reproduce this. Please minify your project, upload it to GitHub, and open a new issue with it.

**Comment by heroljy** [comment]
It's probably because Select Attributes adds filterable, and you make class (.el-select__input {
vertical-align: middle;
}) not vertical-align:middle, such as vertical-align: baseline; there will be shaking

**Comment by bq-hentai** [comment]
v2.0.11 exist also.

And set an extra style `.el-select__input { vertical-align: base }` as @heroljy commented, fixed.

**Comment by Wu-Sophie** [comment]
In the latest version of the Chrome browser， I reproduce this. And set extra style does not work

**Comment by z1948296027** [comment]
add .el-select__input did not work, and some computer do not has this problem

**Comment by wengxuan** [comment]
官网http://element.eleme.io/#/zh-CN/component/select

**Comment by wengxuan** [comment]
官网http://element.eleme.io/#/zh-CN/component/select
浏览器chrome 67.0.3396.99
滚轮缩放至90%

**Comment by wengxuan** [comment]
官网可复现bug  http://element.eleme.io/#/zh-CN/component/select
浏览器chrome 67.0.3396.99
滚轮缩放至90%
基础多选(Multi select)，选中5个
可复现这个抖动bug

**Comment by z1948296027** [comment]
是的,90%的时候可以复现

**Comment by sayhihi** [comment]
element-ui v2.8.2版本遇到同样的问题，最新版本，官网可复现https://element.eleme.io/2.8/#/zh-CN/component/select

**Comment by skyzhao1223** [comment]
I solved this problem by adding style below, hope it helps you

`
.el-select .el-input {
  overflow: scroll;
}
`

**Comment by hfc1994** [comment]
@skyzhao1223 
It seems pretty useful,I just add `padding-bottom: 1px;`
anyway thanks!

**Comment by IsaacMuTusimple** [comment]
padding-bottom does not work for my enviroment

**Comment by ghrGit** [comment]
> element-ui v2.0.10版本, 多行且页面放大110%时抖动, 查看代码是el-select__tags的clientHeight计算结果不断变化导致的, 解决的方式比较hack, 直接修改 .el-tag--small{ height: 25px; }
it working for me

**Comment by er567** [comment]
depend on your select number. or you can try `padding-bottom: 2px;`

**Comment by FrontendStack** [comment]
有有效的解决办法吗

**Comment by secondCat** [comment]
padding-bottom:1px  does not work ,when i  resize Chrome browser,the issue will  appear.

**Comment by chenxiyue** [comment]
@skyzhao1223 
我也解决了，只加了.el-select .el-input { padding-bottom: 1px; }

**Comment by ParkDyel** [comment]
how I can fix it?

https://codesandbox.io/s/green-wave-coucr?file=/src/App.vue

it was happening at browser zoom in 110%.
and it's index increase so fast

https://user-images.githubusercontent.com/13329748/111991106-46bae080-8b57-11eb-8a3f-0db80965ed9f.mp4

**Comment by chenxiyue** [comment]
> how can i fix it?
> 
> https://codesandbox.io/s/green-wave-coucr?file=/src/App.vue
> 
> it was happening at browser zoom in 110%.
> and its index increase so fast
> 
>  green-wave-coucr.-.CodeSandbox.-.Chrome.2021-03-22.21-36-30.mp4 
> The call stack obtained through BP is as follows. Will the resize keep happening?
> 
> ![image](https://user-images.githubusercontent.com/13329748/111995460-4a049b00-8b5c-11eb-9bcf-4f6786256175.png)

Set Style:
.el-cascader .el-cascader__tags {
  right: 1px;
  top: 1px;
  transform: unset;
}

**Comment by chenxiyue** [comment]
@ParkDyel 
Set Style:
.el-cascader .el-cascader__tags {
  right: 1px;
  top: 1px;
  transform: unset;
}

**Comment by chenxiyue** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I replied to you on GitHub, please try it!https://github.com/ElemeFE/element/issues/8731#issuecomment-806325120
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                458651114
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/22/2021 ***@***.***> wrote： 



how I can fix it?
https://codesandbox.io/s/green-wave-coucr?file=/src/App.vue
it was happening at browser zoom in 110%.
and it's index increase so fast
https://user-images.githubusercontent.com/13329748/111991106-46bae080-8b57-11eb-8a3f-0db80965ed9f.mp4

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ParkDyel** [comment]
@chenxiyue Thanks for the advice. It was well modified with the CSS provided. I was wondering if there is a way other than CSS, but it is unfortunate.

**Comment by chenxiyue** [comment]
@ParkDyel The simplest way here is CSS.

**Comment by Mario34** [comment]
**提供一个临时解决方案**

看下源码里的逻辑 [cascader.vue#L637](https://github.com/ElemeFE/element/blob/17de41f3e2eb97508c8e85afac7bc10a22a7cf7b/packages/cascader/src/cascader.vue#L637) , 这里判断下前后height相差3像素内不更新。

```js
if (Math.abs(inputInner.style.height - height) > 3) {
  inputInner.style.height = height
}
```

重写这个组件，替换原有的Cascader

```vue
<script>
import Cascader from 'element-ui/lib/cascader'

export default {
  extends: CascaderFix,
  methods: {
    updateStyle() {
      const { $el, inputInitialHeight } = this
      if (this.$isServer || !$el) return

      const { suggestionPanel } = this.$refs
      const inputInner = $el.querySelector('.el-input__inner')

      if (!inputInner) return

      const tags = $el.querySelector('.el-cascader__tags')
      let suggestionPanelEl = null

      if (suggestionPanel && (suggestionPanelEl = suggestionPanel.$el)) {
        const suggestionList = suggestionPanelEl.querySelector(
          '.el-cascader__suggestion-list',
        )
        suggestionList.style.minWidth = inputInner.offsetWidth + 'px'
      }

      if (tags) {
        const { offsetHeight } = tags
        const height = Math.max(offsetHeight + 6, inputInitialHeight) + 'px'
        if (Math.abs(inputInner.style.height - height) > 3) {
          inputInner.style.height = height
        }
        this.updatePopper()
      }
    },
  },
}
</script>

```
