### ISSUE TITLE
[Bug Report] date range selection settings after disable user display is unfriendly

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#8732]
### Element UI version
2.0.7

### OS/Browsers version
osx/chrome 54

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/ezrwuz2o/](https://jsfiddle.net/ezrwuz2o/)

### Steps to reproduce

[element  2.0.7 的实现]( https://jsfiddle.net/ezrwuz2o/)

[element 1.4.12 的实现](https://jsfiddle.net/d8a4ndms/)

可以比较两个选择器， 发现 旧版本的 今天 更加 明显， 新版本 的今天不太明显

将起始时间设置到昨天， 一直拖动到禁用的日期内， 选中的日期 和 禁用 的日期 背景颜色相近， 整个颜色区域连在了一起， 不太直观， 操作上不像以前一样有好， 虽然 UI 上更好看了一些， 这里的两个链接分别附上了两个版本的实现， 可以比较以下差异

### What is Expected?
通过颜色上区分 禁用日期 和 选中日期， 避免连在一起 

### What is actually happening?
禁用日期 和 选中日期 颜色上过于接近， 不易区分

**Comment by Leopoldthecoder** [comment]
We'll keep it as is.
