### ISSUE TITLE
The triangle dislocation of the drop-down frame of the [Bug Report] select component

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#8733]
### Element UI version
2.0.7

### OS/Browsers version
osx

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/4L9xv4xL/](https://jsfiddle.net/4L9xv4xL/)

### Steps to reproduce
点击 select 见 下拉列表， 三角形的位置异常

### What is Expected?
修复下拉列表 三角形 的错位 

### What is actually happening?
三角形 位置异常， 应该是 盒模型 使用的问题

**Comment by Leopoldthecoder** [comment]
Duplicate of #8644
