### ISSUE TITLE
[Bug Report] The tree component does not get the key that the child node has not finished

### ISSUE THREAD

**Issue by lmxdawn** [ElemeFE/element#8735]
### Element UI version
1.4.12

### OS/Browsers version
Windows

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/o5sq6f6L/2/](https://jsfiddle.net/o5sq6f6L/2/)

### Steps to reproduce
一个父节点有两个子节点（一共三个节点），只选择一个子节点，当通过 key 获取选中值时，只能获取到那个子节点的值。

### What is Expected?
获取选中值时，父节点的值 和 选中的的子节点的值都能获取（也就是能获取两个节点的 key 值）

### What is actually happening?
获取选中值时，父节点的值不能获取 ，只能获取选中的的子节点的值

**Comment by furybean** [comment]
Duplicate with #9295.
Please track progress of that issue.
