### ISSUE TITLE
Button in [Bug Report] table-row does not trigger Popover

### ISSUE THREAD

**Issue by gaecfov** [ElemeFE/element#8742]
### Element UI version
2.0.7

### OS/Browsers version
chrome62

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/phbsz0rc/](https://jsfiddle.net/phbsz0rc/)

### Steps to reproduce
行内button绑定了popover
点击行内的button
popover未触发

### What is Expected?
popover应触发

### What is actually happening?
popover未触发

**Comment by Leopoldthecoder** [comment]
`v-popover` 指令不支持这样使用。目前想实现每行一个 Popover 的话，需要在对应列的 `scoped slot` 里写 `<el-popover>`，并用 slot 的方式指定触发元素。
