### ISSUE TITLE
[Feature Request] Transfer can't add a multidimensional array in data. The actual scene is the three linkage at the provincial level

### ISSUE THREAD

**Issue by muiccc** [ElemeFE/element#8747]
### Existing Component
是

### Component Name
Transfer

### Description
Transfer 没法在 data里 添加 多维数组, 实际场景就是 省市级三联动

**Comment by Leopoldthecoder** [comment]
是指希望在 Transfer 的两个面板里放 Tree？

**Comment by muiccc** [comment]
@Leopoldthecoder 可以吗

**Comment by muiccc** [comment]
@Leopoldthecoder 1,tree; 2,在tree基础下多选,全选

**Comment by Leopoldthecoder** [comment]
Transfer 里不会支持 Tree。后面会考虑做一个 TreeSelect。
