### ISSUE TITLE
The label of [Bug Report] radio is an initialization state exception at number

### ISSUE THREAD

**Issue by baifan** [ElemeFE/element#8749]
### Element UI version
2.0.7

### OS/Browsers version
Ubuntu/Chrome62.0.3202.94

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/usey9u3d/](https://jsfiddle.net/usey9u3d/)

### Steps to reproduce
进入https://jsfiddle.net/usey9u3d/
就可以看到，未激活，没有被选中。

### What is Expected?
未激活被选中。

### What is actually happening?
未激活没有被选中。

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/usey9u3d/1/
