### ISSUE TITLE
select 做一个级联选择 如何初始化值

### ISSUE THREAD

**Issue by heymalio** [ElemeFE/element#875]

**Comment by xnumb** [comment]
直接在 变量里 初始化数组的第一个值就行 比如 [{name:'请选择',id:0}]

**Comment by Leopoldthecoder** [comment]
给 `v-model` 绑定的变量初始化就可以。先关闭这个 issue，如果还有问题可以再打开。

**Comment by nivekz** [comment]
hello，我和 @heymalio 在看同样的问题。我们的`el-select`的`value`和里面的`el-option`都是异步请求获得的。如果在`el-select`的`value`赋值时，`el-option`还没准备好，那么`value`就会被控件设置成`undefined`。

请问这个自动把不存在`option`的`value`变成`undefined`是一个feature吗？如果是的话，以上场景要如何处理，有没有推荐的方法？谢谢！

另外：我们尝试过一个hack，就是在赋值`value`的时候，如果`option`不存在，创建一个对应的`option foo`。但是当实际`option`被赋值的时候，界面上显示的还是旧的`foo`的label。
