### ISSUE TITLE
Whether [Feature Request] can add the function of the number of statistical results selected by el-table

### ISSUE THREAD

**Issue by blueroseslol** [ElemeFE/element#8752]
### Existing Component
是

### Component Name
el-table

### Description
用的是1.4版本，新版本也没有对应的属性。

无法统计筛选后的数据条数。

使用$refs.xxxx.data.length返回还是未筛选前的数量（文档不应该写成“显示的数据”，而应该写成接收到数据）

**Comment by Leopoldthecoder** [comment]
需要在 `filter-method` 里自己计算。

**Comment by blueroseslol** [comment]
好的谢谢，知道怎么做了
