### ISSUE TITLE
[Bug Report] Internet  Explorer SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by anoopmb** [ElemeFE/element#8755]
### Element UI version
2.0.7

### OS/Browsers version
internet Explorer 11

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
element ui is not launching on ie11

### What is Expected?
launch perfectly

### What is actually happening?
SCRIPT1003: Expected ':'

row.js

computed: {
****    style() {
      var ret = {};

      if (this.gutter) {
        ret.marginLeft = `-${this.gutter / 2}px`;
        ret.marginRight = ret.marginLeft;
      }

      return ret;
    }
  },

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
