### ISSUE TITLE
[Bug Report] how to use validateField in typescript

### ISSUE THREAD

**Issue by mu-yu** [ElemeFE/element#8756]
### Element UI version
0.1.0

### OS/Browsers version
typescript: 2.6.2

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
使用typescript配合element-ui，在表单验证某个字段的时候使用了如下方法：  

`(this.$refs[formRef] as ElForm).validateField('packageNames', function(errMsg: string): void {})`

但是会报错：`TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'void' has no compatible call signatures.`

### What is Expected?
callback应该为可选项，且可以传入简单的箭头函数

### What is actually happening?
callback为必选项，且传入简单的箭头函数会报错：  
` TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'void' has no compatible call signatures.`

**Comment by baixiaoji** [comment]
I meet the same problem

**Comment by tudi2d** [comment]
I´m facing the same problem. Writing `this.$refs["form"]["validateField"]("packageNames")` avoids the type checking. This is not a solution but a work around.
