### ISSUE TITLE
[Bug Report] Cann't add MaxLength property for el-autocomplete component

### ISSUE THREAD

**Issue by JFrameSea** [ElemeFE/element#8758]
### Element UI version
0.1.0

### OS/Browsers version
mac chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
ok,jsfiddle加载太慢，所以希望您可以看一下我期待行为和实际行为中的描述，谢谢

### What is Expected?
期待：通过外层组件向内层组件传prop的方式，设置el-autocomplete这个组件的maxlength属性

### What is actually happening?
实际：需要修改element-ui的源码，去设置maxlength

**Comment by Leopoldthecoder** [comment]
Autocomplete 没有 `max-length` 属性。

**Comment by JFrameSea** [comment]
为什么没有，Autocomplete内部用的el-input，el-input是有maxlength这个属性的
ok，那既然没有，那我们是否有其他方式去实现？

**Comment by robertluoxu** [comment]
这个能力为什么还没有提供？
