### ISSUE TITLE
[Bug Report] tabindex issue with el-tooltip + el-input

### ISSUE THREAD

**Issue by FranckFreiburger** [ElemeFE/element#8759]
### Element UI version
1.4.12

### OS/Browsers version
any

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/93/](https://jsfiddle.net/mmx38qxw/93/)

### Steps to reproduce
Use tab key de navigate through fields, then pay attention to the caret

### What is Expected?
We expect the usual tab key behavior: set the caret to the next field

### What is actually happening?
We need to press tab key twice to go to the next field.
It seems that the tabindex attribute is not set to the right element.

**Comment by Leopoldthecoder** [comment]
Fixed in #9990

**Comment by frostbolt** [comment]
tabindex property in `el-tooltip` is a number, but in `el-input` it's a string. I think this inconsistency should be reviewed too.
