### ISSUE TITLE
[Feature Request] Support for form validation of hierarchical (!) object

### ISSUE THREAD

**Issue by p4m** [ElemeFE/element#8760]
### Existing Component
Yes

### Component Name
el-form

### Description
I often have the need to create forms with hierarchical objects, like the example below. 

![image](https://user-images.githubusercontent.com/1651685/33823827-b335026e-de5c-11e7-860e-5fa7596bc60e.png)

### Nice to have the validation (rules) like this:

![image](https://user-images.githubusercontent.com/1651685/33823884-e88b7b46-de5c-11e7-8dc5-9de8a95c269d.png)

**Comment by Leopoldthecoder** [comment]
Supported in #8765
