### ISSUE TITLE
[Feature Request] Why the close button of <el-dialog> component is ineffective ？

### ISSUE THREAD

**Issue by ilinkit** [ElemeFE/element#8762]
### Existing Component
Yes

### Component Name
el-dialog

### Description
I use component as follow:

				<el-dialog 
					:visible="dialogVisible" 
					title="Money round the World"  >
				  <p>Welcome to Element</p>
				</el-dialog>
When set the variable 'dialogVisible' to true, the dialog will be visible.
But when we click the 'Close Button' at top-right of dialog, there is nothing happen.

How can I close the the dialog simply？
Thanks :)

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by aztack** [comment]
@Leopoldthecoder 
Here is a reproduction link you asked for
https://jsfiddle.net/ps8o4k88/2/

**Comment by Leopoldthecoder** [comment]
You need to add the `.sync` modifier: https://jsfiddle.net/ps8o4k88/3/ .
