### ISSUE TITLE
[Bug Report] el-autocomplete width

### ISSUE THREAD

**Issue by FranckFreiburger** [ElemeFE/element#8767]
### Element UI version
1.4.12

### OS/Browsers version
any

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/94/](https://jsfiddle.net/mmx38qxw/94/)

### Steps to reproduce
just look at the ui

### What is Expected?
<el-autocomplete> and <el-input> should have the same size (100%)

### What is actually happening?
<el-input> has width:100% whereas <el-autocomplete> no

**Comment by Leopoldthecoder** [comment]
The default `display` of Input and Autocomplete is different. You can override them if you prefer a same width.
