### ISSUE TITLE
[Bug Report] Table component head and column pairs in Safari (table component header and column cannot align in)

### ISSUE THREAD

**Issue by Ansel** [ElemeFE/element#8768]
### Element UI version
2.0.7

### OS/Browsers version
macOS High Sierra 10.13.2 / Safari 11.0.2 (13604.4.7.1.3)

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/eoston/5hbrztjb/](https://jsfiddle.net/eoston/5hbrztjb/)

### Steps to reproduce
el-table组件显示border，并对其中某列设置show-overflow-tooltip，在Safari浏览器下即可看出明显的对不齐，列更多的情况下该问题更明显。

Show border for the table component '<el-table></el-table>', set 'show-overflow-tooltip' for some columns. This issue can reappear in Safari.

### What is Expected?
Safari中表头和列内容能够对齐

The header and column can align in Safari

### What is actually happening?
Safari中表头和列内容不能对齐，列内容会比表头更宽，有明显的对不齐。（但是通过Safari的检查元素，将对应的.el-table__body, .el-table__footer, .el-table__header{table-layout: fixed;}样式中table-layout去掉，然后再应用，就可以实现表头和表格内容列对齐的效果）

Table component header and column cannot align in Safari, after reuse 'table-layout: fixed' for '.el-table__body, .el-table__footer, .el-table__header', this issue can be resolved.

**Comment by furybean** [comment]
先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。
