### ISSUE TITLE
[Bug Report]When Notification pop-up multiple , they overlaps

### ISSUE THREAD

**Issue by chenjiangshuo** [ElemeFE/element#8769]
### Element UI version
2.0.7

### OS/Browsers version
MAC/chrome

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/98/](https://jsfiddle.net/mmx38qxw/98/)

### Steps to reproduce
当一次点击事件或循环弹出 多个 Notifition 时，会出现重叠现象

### What is Expected?
多个 Notifition 不重叠

### What is actually happening?
多个 Notifition 重叠

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/7389

**Comment by aghArdeshir** [comment]
@acejudo works perfectly : )))) Thanks
