### ISSUE TITLE
validation always been triggered after input

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#8772]
### Element UI version
2.0.7

### OS/Browsers version
windows10 Chrome70

### Vue version
2.4.2

### Reproduction Link
https://jsfiddle.net/gd69Lmyt/

### Steps to reproduce
1. input some Latin letters
2. blur from the input 
3. validation will be triggered after blur
4. continue input letters
5. validation will be triggered after every input, instead of blur

### What is Expected?
validation only after blur as i defined in rules

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8776/commits/2bb485e73fe35d95eaeac11bc1f27d25fce043f0

**Comment by zzzgit** [comment]
i can not find this commit on dev branch

**Comment by zzzgit** [comment]
i found it not been resolved

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/gd69Lmyt/1/
