### ISSUE TITLE
tree控件的bug

### ISSUE THREAD

**Issue by cuitwangshicheng** [ElemeFE/element#8773]
tree控件调用getCheckedKeys时无法获取到没有展开的子节点key，只有在展开过一次子节点时才能获取到。并且子节点非全选时，无法获取到父节点的key

**Comment by tangmin721** [comment]
啥都关 不是解决问题的方式

**Comment by cuitwangshicheng** [comment]
这些人是不是看不懂中文？号称是饿了么的框架，全部在这拽鬼文，还动不动就关闭……

**Comment by glacierck** [comment]
getCheckedKeys 问题再报一次，，参数不管是传true还是false 都只能获取到叶子节点，半选的父类节点是获取不到的。。。。。。。。。。，请务必解决，或者去改改你们的api文档，还有中文的文档都有那么多坑爹的地方了，就别用不知所以然文去描述了。

**Comment by 744934982** [comment]
半选的父节点无法获取，这么长时间了都不解决吗
