### ISSUE TITLE
[Bug Report] Font size for textarea input

### ISSUE THREAD

**Issue by sylvaincaillot** [ElemeFE/element#8777]
### Element UI version
2.0.4

### OS/Browsers version
win10 / chrome 64

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/springrider77/ut5t8cw5/9/](https://jsfiddle.net/springrider77/ut5t8cw5/9/)

### Steps to reproduce
Start entering exact same text in the "Transported by" and "Comment" inputs
You will see that the text in the comment (textarea type) is much larger than the one above (text type)

### What is Expected?
Same font and same font size for all the inputs within the form for which the size has been defined

### What is actually happening?
The inputs of textarea type do not have the same font size as the other inputs of text type for example

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8776/commits/5a9ebdfc2a2de423b181e0e67582c2aa193f9d8d
