### ISSUE TITLE
[Bug Report] Overlap of el-date-picker in inline form

### ISSUE THREAD

**Issue by sylvaincaillot** [ElemeFE/element#8778]
### Element UI version
2.0.4

### OS/Browsers version
win10 / chrome 64

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/springrider77/ut5t8cw5/9/](https://jsfiddle.net/springrider77/ut5t8cw5/9/)

### Steps to reproduce
Overlap of el-date-picker in inline form. 
As you see, the date picker input overlaps the label of the quantity input on its right

### What is Expected?
To have the date picker not overlapping the label of the next form item in the case of inline form items

### What is actually happening?
https://jsfiddle.net/springrider77/vo1sqx2p/1/

This solution works by adding style="width: 100%;" to the el-date-picker but it doesn't seem to be a sustainable solution

**Comment by Leopoldthecoder** [comment]
DatePicker has a fixed width so that when a date is picked, it is wide enough to show the date. In this case you can write your own styles: https://jsfiddle.net/ut5t8cw5/10/
