### ISSUE TITLE
Datepicker组件v-model被重置后，日历依旧高亮选中重置前日期

### ISSUE THREAD

**Issue by jikkai** [ElemeFE/element#878]
### ElementUI version
1.0.0-rc.8

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.5

### Reproduction Link
[codepen](http://codepen.io/jikkai/pen/NRjxVj?editors=1010)

### Steps to reproduce
1. 选择一个日期
2. 将v-model设置为空字符串/undefined

### What is Expected?
v-model被清除，再次点击DatePicker组件打开日历，原来被选中的日期依旧高亮显示

### What is actually happening?
高亮选中的日期应“当天”

**选择日期前：**
![image](https://cloud.githubusercontent.com/assets/14025786/20048566/91dd9732-a4f8-11e6-8b3b-6728c52243ea.png)

**选中日期时：**
![image](https://cloud.githubusercontent.com/assets/14025786/20048571/9b7c12d2-a4f8-11e6-9cbe-2e0a09338139.png)

**清除日期后：**
![image](https://cloud.githubusercontent.com/assets/14025786/20048576/a35a0f04-a4f8-11e6-9968-3a83eb5a6f58.png)

**Comment by reverland** [comment]
想特别at下 #759

**Comment by QingWei-Li** [comment]
@reverland 那个要等设计资源到位了才做
