### ISSUE TITLE
blur event won't be triggered in daterange picker

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#8780]
### Element UI version
2.0.7

### OS/Browsers version
windows10 Chrome70

### Vue version
2.4.2

### Reproduction Link
https://jsfiddle.net/m5oqks24/

### Steps to reproduce
1. select date from `date picker`
2. log added in console
3. select date from `dateRange picker`
4. no log will be added

### What is Expected?
log

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8784
