### ISSUE TITLE
[Bug Report] element UI tree control el-tree checkbox single selection problem

### ISSUE THREAD

**Issue by hanmax214094** [ElemeFE/element#8781]
### Element UI version
1.4.12

### OS/Browsers version
Windows 10 64bit / Chrome 62.0.3202.94

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/3apgb0ck/2/](https://jsfiddle.net/3apgb0ck/2/)

### Steps to reproduce
若子node 为 disabled, 其所属父node则无法勾选（限其下一层所有直属node皆disabled）
依照jsfiddle范例, 

二级 1-1无法勾选
一级2 则是没问题的

### What is Expected?
实现树形控件check勾选框单选（套用disabled情况下）

### What is actually happening?
子node disabled则勾选框有问题

**Comment by Leopoldthecoder** [comment]
请参考 #8044
