### ISSUE TITLE
[Feature Request] el-table use summary, hope to open the API can cross

### ISSUE THREAD

**Issue by viewweiwu** [ElemeFE/element#8782]
### Existing Component
是

### Component Name
el-table

### Description
el-table use summary, hope to open the api can cross column

**Comment by Leopoldthecoder** [comment]
What does 'cross column' mean?

**Comment by viewweiwu** [comment]
就是想要 table-footer 开放跨列的 api

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
