### ISSUE TITLE
The sort buttons of [Bug Report] Table are covered with each other

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#8786]
### Element UI version
2.0.7

### OS/Browsers version
osx chrome 56

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/rgzox6xr/1/](https://jsfiddle.net/rgzox6xr/1/)

### Steps to reproduce
审查排序剪头的盒模型， 发现  `.el-icon-caret-top` 和 `.el-icon-caret-bottom` 的两个盒模型有重合，导致鼠标移入到 向上箭头 的底部边缘附近时没有办法使点击生效，无法切换排序方式

### What is Expected?
调整 排序按钮的盒模型,  使得两个按钮操作区域不重合

### What is actually happening?
两个按钮操作区域重合, 使得点击不能在按钮

**Comment by Leopoldthecoder** [comment]
Fixed in #8792

**Comment by zzzgit** [comment]
this bug only been fixed in chrome, but not firefox
