### ISSUE TITLE
the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots

### ISSUE THREAD

**Issue by PLAmao** [ElemeFE/element#8789]
用vue-cli编译时出现这个警告，虽然不影响执行，但是看错误要滚上去，每次这样好麻烦，怎样才能去掉这个警告（element是1.X的版本，vue就算装了2.5一下的版本也是不行）
 warning  in ./src/views/up/manager/task/index.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

 @ ./src/views/up/manager/task/index.vue 10:0-427
 @ ./src/views ^\.\/.*\.vue$
 @ ./src/router/_import_development.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.9.7@webpack-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/main.js

**Comment by forzeny** [comment]
the same issue , can you ask issue for right format
