### ISSUE TITLE
[Bug Report] select component change event trigger

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#8791]
### Element UI version
2.0.8

### OS/Browsers version
macos

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/jeu7n4b9/](https://jsfiddle.net/jeu7n4b9/)

### Steps to reproduce
默认value是空，mounted时设置value的值，这个时候不触发change事件，1.x版本是触发的

1.x  https://jsfiddle.net/7Ljo8p87/
2.x https://jsfiddle.net/jeu7n4b9/

### What is Expected?
默认value是空，mounted时设置value的值，触发change事件。

### What is actually happening?
默认value是空，mounted时设置value的值，这个时候不触发change事件，1.x版本是触发的

**Comment by Leopoldthecoder** [comment]
> ### 非兼容性更新
> - 综合
>    - 表单组件的 `change` 事件和 Pagination 的 `current-change` 事件现在仅响应用户交互

摘自 2.0.0 版本更新日志。
