### ISSUE TITLE
[Bug Report] Input change event like blur event

### ISSUE THREAD

**Issue by feusebio** [ElemeFE/element#8793]
### Element UI version
2.0.8

### OS/Browsers version
Windows 10 Home (64bits), Chrome 63.0.3239.84 (64bits)

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/zw97tx80/](https://jsfiddle.net/zw97tx80/)

### Steps to reproduce
1) Set a function in the change event for a input element

### What is Expected?
Fire the function when type a char

### What is actually happening?
Only fire the function when input lost focus

**Comment by Leopoldthecoder** [comment]
`change` event of `<el-input>` behaves just like the native `<input>` element: https://jsfiddle.net/zw97tx80/8/

More info: https://developer.mozilla.org/en-US/docs/Web/Events/change
