### ISSUE TITLE
[Bug Report] el-switch problem

### ISSUE THREAD

**Issue by zuxriddinkamalov** [ElemeFE/element#8795]
### Element UI version
1.4.12

### OS/Browsers version
Google Chrome 62.0.3202 (WebKit 537.36)

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/coderosg/4voyc4dn/](https://jsfiddle.net/coderosg/4voyc4dn/)

### Steps to reproduce
When I submit my form el-switch send value as "on".

### What is Expected?
I want that el-switch sent the value that I indicated in on-value or off-value.

### What is actually happening?
Actually el-switch send default system values.

**Comment by Leopoldthecoder** [comment]
If you must use FormData, you need to do some conversion on your end. Form elements are designed for JSON.

**Comment by zuxriddinkamalov** [comment]
Can you show this in the example?
