### ISSUE TITLE
[Bug Report] DateTimerPicker's TimePicker seems does not work properly.

### ISSUE THREAD

**Issue by decadef20** [ElemeFE/element#8798]
### Element UI version
2.0.8

### OS/Browsers version
MacOs/Version 60.0.3112.90 (Official Build) (64-bit)

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1.select a  date and time
2.click outside DateTimePicker to close 
3 reselect date

### What is Expected?
The selected TimePicker panel values are same as TimePicker input value

### What is actually happening?
The selected TimePicker panel values are 0s

 Is this  a feature or bug?

**Comment by furybean** [comment]
Issues without a valid reproduction link will be closed directly.
