### ISSUE TITLE
[Bug Report] table slot append outside table element 

### ISSUE THREAD

**Issue by apariciom** [ElemeFE/element#8800]
### Element UI version
2.0.7

### OS/Browsers version
Chrome / Version 63.0.3239.84 

### Vue version
2.5.8

### Reproduction Link
[https://jsfiddle.net/L7z6nntx/](https://jsfiddle.net/L7z6nntx/)

### Steps to reproduce
Run the JSFiddle and you'll notice the columns do not align. 

Prior to version 2.0.0, the rows/columns would be within the table element. 

### What is Expected?
I expect the rows/columns to be within the table element

The following link demonstrates the appropriate results using version 1.3.5
https://jsfiddle.net/L7z6nntx/1/

### What is actually happening?
The rows/columns are outside of table element losing the formatting and alignment

**Comment by Leopoldthecoder** [comment]
`append` slot is not designed for more table rows. It's suitable for other components, like an infinite loading indicator. This is intended and a breaking change of 2.0.

**Comment by liubaiye** [comment]
so,do you clear this bug?
I have the same trouble as you
If you have solved this bug, please leave a message！
thank you
