### ISSUE TITLE
[Bug Report] Cascader add filter then click arrow cant be hide

### ISSUE THREAD

**Issue by onlyfzz** [ElemeFE/element#8804]
### Element UI version
2.0.8

### OS/Browsers version
mac

### Vue version
2.5.10

### Reproduction Link
https://jsfiddle.net/635qc4mn/

### Steps to reproduce
官方文档的级联选择器的 #可搜索

### What is Expected?
按道理来说点击箭头应该是会被上拉的，但是添加了filter之后，整个input就获取了焦点，点击箭头上拉事件失效

### What is actually happening?
点击箭头上拉事件无效

**Comment by elfman** [comment]
这个bug是这段代码引起的，看不懂这里为什么`filterable`为`true`就要一直保持菜单打开，去掉这里的判断貌似也没出现问题。@Leopoldthecoder
https://github.com/ElemeFE/element/blob/9e6f1adafc1bebb635fa8b9235306b28dfea7d3a/packages/cascader/src/main.vue#L341-L343

```JavaScript
handleClick() {
  if (this.disabled) return;
  this.$refs.input.focus();
  if (this.filterable) {
    this.menuVisible = true;
    return;
  }
  this.menuVisible = !this.menuVisible;
}
```

**Comment by ziyoung** [comment]
@elfman 真的不算 bug。当 filterable 为 true 时，input 是在等待用户输入的。所以，重复点击不会切换。

**Comment by ziyoung** [comment]
大家可以试一下 ant.design 的 select 组件。https://ant.design/components/select-cn/#components-select-demo-search
行为也是这样的。

**Comment by ziyoung** [comment]
https://github.com/ElemeFE/element/pull/13279#issuecomment-435817101
