### ISSUE TITLE
[Bug Report] initial <el-form-item> error message is not display

### ISSUE THREAD

**Issue by FranckFreiburger** [ElemeFE/element#8808]
### Element UI version
2.0.8

### OS/Browsers version
any

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/106/](https://jsfiddle.net/mmx38qxw/106/)

### Steps to reproduce
look at the input's initial error message, just below the input field, it is not visible.

### What is Expected?
Initial error message must be displayed (error property)

### What is actually happening?
Initial error message is not displayed.
Error message is only displayed when changed.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8840
