### ISSUE TITLE
Table-column 的prop可以设置computed方法吗？试了没效果

### ISSUE THREAD

**Issue by Crazydiver** [ElemeFE/element#881]
想解决的问题，就是为每一行的数据加过滤器，vue2.0取消了过滤器，推荐用computed
为Table-column 的prop了设置computed方法，没效果

**Comment by QingWei-Li** [comment]
table 有提供 formatter 应该能满足你的需求

**Comment by furybean** [comment]
prop 应该是可以动态的？能提供一个例子么？

**Comment by Crazydiver** [comment]
用formatter实现的过滤功能
