### ISSUE TITLE
[Bug Report] Space doesn't work in el-autocomplete in el-menu

### ISSUE THREAD

**Issue by Yorgovan** [ElemeFE/element#8812]
### Element UI version
2.0.8

### OS/Browsers version
any

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/107/](https://jsfiddle.net/mmx38qxw/107/)

### Steps to reproduce
Create el-menu with el-autocomplete in it then press space in el-autocomplete element

### What is Expected?
Space should work

### What is actually happening?
Space doesn't work

**Comment by Yorgovan** [comment]
Update:

When space is pressed it is registered as click if I monitor events.
I also found this code in few files (menu.js, aria-menuitem.js,element-ui.common.js)
```    
case keys.space:
case.keys.enter:
  prevDef = true;
  event.currentTarget.click();
  break;
```
But changing it or commenting space part doesn't do anything.

**Comment by georgyfarniev** [comment]
Hello, we having similar problem because of space press event handler. Any updates?

**Comment by alexander-sharecreators** [comment]
https://jsfiddle.net/kulnaura/7oxpzg54/5/
I added wrapper for el-input and used "@keydown.stop" in it:
`
...
<el-menu-item index="1">
    <div **@keydown.stop**>
      <el-input 
                v-model="keyword" 
                type="text" 
                placeholder="placeholder"
                clearable
                autofocus>
      </el-input>
    </div>
  </el-menu-item>
...
`
This trick helped me.

**Comment by bpkennedy** [comment]
@alexander-sharecreators , this helped me as well.  This was an infuriating bug.

**Comment by dongmingxin** [comment]
@alexander-sharecreators, thank you
