### ISSUE TITLE
[Feature Request] Open popover on tab close icon click

### ISSUE THREAD

**Issue by arcadeJHS** [ElemeFE/element#8814]
### Existing Component
Yes

### Component Name
Tabs, Popover

### Description
It would be great to be able to display a popover when the user click on the "x" button on an opened tab. 
Maybe to ask for a confirmation.
Is it maybe already possible? I do not know how, anyway.

**Comment by Leopoldthecoder** [comment]
The event handler for clicking the "x" button is defined by you, so you can do whatever you want in the handler.

**Comment by arcadeJHS** [comment]
Do you mean the "@tab-remove" event handler?
But this handler takes as input the selected tab name.
How can I append a popover to the icon (or at least the tab)?
