### ISSUE TITLE
[Bug Report] BUG in the tree component

### ISSUE THREAD

**Issue by LongYue9608** [ElemeFE/element#8815]
### Element UI version
2.0.8

### OS/Browsers version
 Google Chrome	58.0.3029.110

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/5eh0hxkn/](https://jsfiddle.net/5eh0hxkn/)

### Steps to reproduce
After entering, we first close the first level 2 menu, then click on the sub menu of the first level 3, the first level 2 menu will expand automatically, not the design, so I think it's a BUG.
This is a code link：https://jsfiddle.net/5eh0hxkn/

### What is Expected?
It is expected that the start menu is unfolded, then the first level 2 menu is closed, and then the 3 menus submenu is clicked, and the level 2 menu should not be automatically expanded.

### What is actually happening?
The first level 2 menu is open

**Comment by LongYue9608** [comment]
This problem affects my actual use

**Comment by furybean** [comment]
@LongYue9608 我在最新的 Chrome 上并不能重现此问题，请问是否只能在 Chrome 58 上重现。
另外，如果方便，能不能做几张截图来说明这个问题。

**Comment by jasonc08** [comment]
![tree](https://user-images.githubusercontent.com/34789166/35583448-e84fe138-062c-11e8-98ca-3197545e8418.png)

**Comment by LongYue9608** [comment]
@furybean 问题 @jasonc08 已经贴出来了，事实上，按照他上面的步骤，第二步之后，你直接点击二级3-1或者二级3-2你就会发现问题了（上面的步骤饶了一大圈不过依然可以重现ＢＵＧ），一级二菜单会自动展开，你自己去尝试吧

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/35601968-a4607c96-0670-11e8-90cb-8d7d057a3e9f.gif)

@LongYue9608 按照步骤尝试了一下（运行 demo -> 收起「一级 2」-> 点击「二级 3-1」），没有复现问题。请告知步骤是否正确，或直接上传一张能够复现问题的截图。

**Comment by LongYue9608** [comment]
@Leopoldthecoder 勾选

**Comment by LongYue9608** [comment]
@Leopoldthecoder 勾选二级3-1或者二级3-2，一级二会自动展开

**Comment by littlePig-zzf** [comment]
感觉好像和这个default-expanded-keys属性有关

**Comment by furybean** [comment]
JSFiddle能重现，本地一直没重现，昨天修了个类似的问题，修复方法在这几行：https://github.com/furybean/element/blob/9b35b4bd5072f5d3c9e6f2a11b353159fd5811d2/packages/tree/src/model/tree-store.js#L66

需要等下个版本发布了再看这个问题还存不存在。

**Comment by ziyoung** [comment]
@LongYue9608 在最新的版本中，经过我的测试，已经不会再出现这个问题了。
