### ISSUE TITLE
[Bug Report] [Vue warn]: Missing required prop: "value"

### ISSUE THREAD

**Issue by ireeoome** [ElemeFE/element#8817]
### Element UI version
1.4.12

### OS/Browsers version
Windows10 Chrome 62

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/110/](https://jsfiddle.net/mmx38qxw/110/)

### Steps to reproduce
我看了下`el-select`组件的源码，
里面的`props`有个`value`的定义，而且是`required`，
但是你们的`select`的文档里面根本没有出现这个属性的说明，
我现在使用这个`select`就会报错`[Vue warn]: Missing required prop: "value"`，
你们可以看一下，
组件文档地址：<http://element-cn.eleme.io/1.4/#/zh-CN/component/select> 

`select.vue`的`props`定义：

```
props: {
      name: String,
      value: {
        required: true//就是这个
      },
      id: String,
      size: String,
      disabled: Boolean,
      clearable: Boolean,
      filterable: Boolean,
      allowCreate: Boolean,
      loading: Boolean,
      popperClass: String,
      remote: Boolean,
      loadingText: String,
      noMatchText: String,
      noDataText: String,
      remoteMethod: Function,
      filterMethod: Function,
      multiple: Boolean,
      multipleLimit: {
        type: Number,
        default: 0
      },
      placeholder: {
        type: String,
        default() {
          return t('el.select.placeholder');
        }
      },
      defaultFirstOption: Boolean,
      valueKey: {
        type: String,
        default: 'value'
      }
    },
```

### What is Expected?
不报错，并给出value的具体说明

### What is actually happening?
报错`[Vue warn]: Missing required prop: "value"`

**Comment by Leopoldthecoder** [comment]
用 `v-model`

**Comment by wuxianqiang** [comment]
我也遇到了这个问题，请问怎么解决的呀？我用 `v-module` 还是会报错.
