### ISSUE TITLE
webpack编译时出错，错误原因 严格模式下使用了with

### ISSUE THREAD

**Issue by zuank** [ElemeFE/element#882]
查看源码 发现源码中使用了严格模式 但是在暴露方法中使用了 with

很尴尬现在卡在使用ele ui的起步   

请教解决方法

**Comment by QingWei-Li** [comment]
请看 FAQ，同时下版本(rc9)会去掉打包后的 `use-strict` 确保 with 不会报错

**Comment by soulkiller** [comment]
我也出现这情况了~
ERROR in ./~/element-ui/lib/element-ui.common.js
Module build failed: SyntaxError: D:/vue-project/vue2-demo/node_modules/element-ui/lib/element-ui.common.js: 'with' in strict mode (1037:36)

  1035 | /***/ function(module, exports) {
  1036 |
> 1037 |        module.exports={render:function (){with(this) {
       |                                           ^
  1038 |          return _h('ul', {
  1039 |            staticClass: "el-pager",
  1040 |            on: {

 @ ./src/main.js 11:17-38
请问rc9发布了么？

**Comment by jikkai** [comment]
@soulkiller 目前最新版本为1.0.0，已经不是rc阶段了

**Comment by soulkiller** [comment]
@jikkai 大神，现在这个问题该如何解决？
