### ISSUE TITLE
[Feature Request] Multilingual support Malay

### ISSUE THREAD

**Issue by superliyy** [ElemeFE/element#8825]
### Existing Component
否

### Component Name
Pagination

### Description
support Malay，please!Thanks you !

**Comment by Leopoldthecoder** [comment]
As mentioned in the documentation:
> If your target language is not included, you are more than welcome to contribute: just add another language config [here](https://github.com/ElemeFE/element/tree/master/src/locale/lang) and create a pull request.

No one in our team speaks Malay, so we have to rely on the community.
