### ISSUE TITLE
[Feature Request] about model synchronization of form

### ISSUE THREAD

**Issue by HengCC** [ElemeFE/element#8827]
### Existing Component
是

### Component Name
form

### Description
现有的form 绑定v-model的时候, 如果model来自props 或者 vuex .  那么就不能够进行很好的双向绑定. 尤其是checkbox 和radio这些组件. 我知道这个是vue底层的限制没办法很好的处理. 必须在vuex中提供相应的mutation或者在computed中提供相应的set方法.  但是这块我觉得是不是可以参考 antd 对react form的处理. 我的大概思路如下:

1. model暴露成属性. 不在data中初始化. 
2. 通过属性传递进来的model 在生命周期函数中完成本地化. 意思是复制一份传递进来的model. 后续的更改跟传递进来的model就没有关系了. 本地model的变更完全由复制出来的托管.
3. 当对form进行编辑的时候, 实际变更的是本地复制的model. 如果调用reset方法. 就初始化为传递进来的model
4. 提供获取变更后的model的办法. 比如antd .在form校验后的回调函数中 将内部的model传递了出来. 

只是一个思路. 觉得有一定的可行性.  现在每次的form model在vuex中的同步写的实在是太繁琐了.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by milu2003** [comment]
问题解决了吗
