### ISSUE TITLE
[Bug Report] TableColumn props label can be slot element but expects String

### ISSUE THREAD

**Issue by karolinakuzniewicz** [ElemeFE/element#8831]
### Element UI version
2.0.8

### OS/Browsers version
macOS High Sierra / Chrome

### Vue version
2.5.10

### Reproduction Link
[https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-column.js](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table-column.js)

### Steps to reproduce
Create TableColumn component with label as a slot, f.ex. :
computed: {
    projectNameLabel () {
      const h = this.$createElement
      return h('span', [
        'Project name ',
        h('i', {
          staticClass: 'el-icon-d-caret',
          on: { click: this.handleClick }
        })
      ])
    }

In browser console you will get a warn that label in TableColumn should be String.

### What is Expected?
No any warns. In your docs label can be slot element.

### What is actually happening?
Warn about prop type.

**Comment by Leopoldthecoder** [comment]
Where does the doc say that label can be a slot?

**Comment by furybean** [comment]
@karolinakuzniewicz Label must be string type. If you want use a render function, you should use prop render-header.
