### ISSUE TITLE
[Feature Request] Implement responsive Boostrap-like column ordering for <el-col>

### ISSUE THREAD

**Issue by iamkd** [ElemeFE/element#8832]
### Existing Component
Yes

### Component Name
el-col

### Description
It would be great if Element UI had Boostrap-like column ordering. 
For example, Bootstrap 4 has column ordering http://getbootstrap.com/docs/4.0/layout/grid/#reordering

Or we can make like Bootstrap 3 classes: `.[xs, sm, md, lg]-pull` and `.[xs, sm, md, lg]-push`.

I will be really happy if this could be implemented.

EDIT:
I saw `push` and `pull` props on el-col, but they are not responsive.

**Comment by iTaster** [comment]
你的可以驳回了，官方里面有弹性布局的，自己多看看官方文档可好

**Comment by ilhamsa1** [comment]
i think elementUI already have that fitur ..
just type ..
`<div class="el-col-md-10">lorem</div>`
`<div class="el-col-md-14">lorem</div>`
