### ISSUE TITLE
[Bug Report] tables are dynamically hidden / displayed in multiple columns

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#8833]
### Element UI version
2.0.8

### OS/Browsers version
chrome

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/r8ho4sxr/1/](https://jsfiddle.net/r8ho4sxr/1/)

### Steps to reproduce
点击‘显示/隐藏’按钮

### What is Expected?
正确显示/隐藏列

### What is actually happening?
出现错误

**Comment by Leopoldthecoder** [comment]
牵涉到动态显示隐藏的，建议给 el-table-column 加上 key：https://jsfiddle.net/r8ho4sxr/3/
