### ISSUE TITLE
[Bug Report] Carousel lantern switch (below) a, page refresh

### ISSUE THREAD

**Issue by tenbamboo** [ElemeFE/element#8834]
### Element UI version
2.0.8

### OS/Browsers version
WIN7/Chrome 55

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/112/](https://jsfiddle.net/mmx38qxw/112/)

### Steps to reproduce
1.执行jsfiddle 
2.点击上一张或下一张
3.直接跳转 提示 {"error": "Please use POST request"} 
备注：实际项目中，直接做跳转了。

### What is Expected?
正常切换上一张或下一张

### What is actually happening?
未 切换上一张或下一张
分析：应该是 上一张或下一张的button 没有挂上 type="button"类型

**Comment by Leopoldthecoder** [comment]
Fixed in #8835
