### ISSUE TITLE
[Bug Report] Table calculate height incorrectly with fixed row

### ISSUE THREAD

**Issue by iGarym** [ElemeFE/element#8839]
### Element UI version
1.4.12

### OS/Browsers version
win10

### Vue version
2.5.10

### Reproduction Link
[https://codepen.io/anon/pen/XVbOXW](https://codepen.io/anon/pen/XVbOXW)

### Steps to reproduce
Resize the browser, it will appear when the browser window width is between 1157px and 1172px ( chrome-v62).

### What is Expected?
Height of the fixed row should calculated correctly.

### What is actually happening?
 Height of the fixed row is incorrectly.

**Comment by Leopoldthecoder** [comment]
1.x version is no longer maintained. 2.x has fixed this.
