### ISSUE TITLE
[Bug Report] in IE11 and edge browsers, composite input box icon misplacement

### ISSUE THREAD

**Issue by liunewshine** [ElemeFE/element#8841]
### Element UI version
2.0.8

### OS/Browsers version
win10/ie11/edge

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/liunewshine/8uohbg95/](https://jsfiddle.net/liunewshine/8uohbg95/)

### Steps to reproduce
直接打开即可看到搜索按钮错位

### What is Expected?
搜索按钮不错位

### What is actually happening?
搜索按钮错位

![image](https://user-images.githubusercontent.com/7698511/34034493-c4e80e60-e1b9-11e7-8478-ad70747dd5a3.png)

**Comment by Leopoldthecoder** [comment]
可以看一下是不是被什么样式影响到了，有兴趣的话可以提个 PR。
