### ISSUE TITLE
[Feature Request] element ui upgrade from 1 to 2 version

### ISSUE THREAD

**Issue by maqrat** [ElemeFE/element#8843]
### Existing Component
No

### Component Name
whole project

### Description
Hello. I have a huge app based on element 1. I have to update 1 version element to 2. I read changelog already. Can I automatically make all changes from "Breaking changes" chapter? Is there any "element ui upgrade guide"?

**Comment by Leopoldthecoder** [comment]
Going through the breaking changes one by one should be enough to safely migrate form 1.x. Plus, you'll get a warning in the console if you are using removed or renamed events and props.
