### ISSUE TITLE
[Bug Report] Locale setting not working for DatePicker

### ISSUE THREAD

**Issue by ksnyde** [ElemeFE/element#8844]
### Element UI version
2.0.8

### OS/Browsers version
macOS / Chrome

### Vue version
2.5.3

### Reproduction Link
[minified code base](https://github.com/ksnyde/problem-with-localization)

### Steps to reproduce
I initialise the Element library within VueJS's `main.js`:

```ts
import Element from "element-ui";
import en from "element-ui/lib/locale/lang/en";
Vue.use(Element, { locale: en });
```

I then use the DatePicker component like so:

```html
<el-date-picker
  v-model="birthYear"
  class="birth-year"
  type="year"
  size="small"
  placeholder="Pick a year">
</el-date-picker>
```
>Note: The repro link is not working because the code is in Typescript and therefore requires compilation and repository is private so I hope this is example URL is sufficient: https://stage.representativetruth.org/profile

### What is Expected?
I expect the date picker to look precisely like the "year picker" in the english demo site.

### What is actually happening?
I get Chinese characters in the title bar of the DatePicker. [Snapshot](https://www.screencast.com/t/IH7xjxtwuk)

**Comment by ksnyde** [comment]
also please note that unlike other examples of this (or similar) problems, I am _not_ using ** VueI18n**

**Comment by Leopoldthecoder** [comment]
Please provide a minimal demo on GitHub. We need to see you code to know what went wrong.

**Comment by Tlapi** [comment]
+1 Having the same problem here

**Comment by Tlapi** [comment]
From what i see in node_modules/element-datepicker/lib/index.js there are chinese characters packed right into this file like:

`selectDate:"选择日期"`

Is this correct?

**Comment by Leopoldthecoder** [comment]
@Tlapi That is because Chinese is the default language of Element, which means when you don't have i18n configured, Element displays Chinese.

Still, we need a reproduction.

**Comment by ksnyde** [comment]
I am _not_ using `vue-i18n@5.x, I _do_ have Element configured EXACTLY as is stated in the demo for Element-only I18n and observe this behaviour.

**Comment by ksnyde** [comment]
My only handicap in creating a reproducible demo is that everything I've done in VueJS is via Typescript and my build tools. I feel a bit handicapped in environments like jsfiddle.

**Comment by Leopoldthecoder** [comment]
You can minify your project and upload it to GitHub.

**Comment by ksnyde** [comment]
Ok, if that's useful I will do that. I did already send a link which has a running version of the problem illustrated ([link](https://stage.representativetruth.com/profile)) if that's also of use.

**Comment by ksnyde** [comment]
Ok, the link is now in place

**Comment by ksnyde** [comment]
I must say, I'm terribly embarrassed but I retried the default implementation of adding the english locale and it IS now working. Doh. I am closing this issue.

**Comment by marcelloinfoweb** [comment]
Estou com o mesmo problema de tradução para o Português do Brasil.

Estou usando CDN.
