### ISSUE TITLE
[Bug Report] use vue@2.3.3 and element-ui@2.0.8 simultaneously，slider component will tell an error.

### ISSUE THREAD

**Issue by feng-fu** [ElemeFE/element#8846]
### Element UI version
2.0.8

### OS/Browsers version
windows 10, mac os 10.13.1

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/vcfr_itft/bg774o83/](https://jsfiddle.net/vcfr_itft/bg774o83/)

### Steps to reproduce
use vue@2.3.3 and element-ui@2.0.8 at the same time, use slider component.

### What is Expected?
component will work well and brower has not error.

### What is actually happening?
component work maybe well but brower has throw an error tell me `[Vue warn]: You may have an infinite update loop in a component render function.`.

**Comment by wacky6** [comment]
element 2 requires vue >2.5.2
please refer to release note: https://github.com/ElemeFE/element/releases/tag/v2.0.0
