### ISSUE TITLE
[Feature Request] How to bind a dynamic class to a cell in a table?

### ISSUE THREAD

**Issue by wsw70** [ElemeFE/element#8849]
### Existing Component
Yes

### Component Name
Table

### Description
I would like to bind,to a cell in the current row, a class which would depend on the content of that cell. I see that there is an attribute `cell-class-name` which accepts a `Function({row, rowIndex})`.

From the description of the function, I believe that this style is applied to all the cells of the row? I am not sure how it is different from `row-class-name`?

Or is there a way to address a specific cell in the current row?

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/xrhsgwup/
