### ISSUE TITLE
[Feature Request] el-menu-item support children router fuzzy matching

### ISSUE THREAD

**Issue by daviyang35** [ElemeFE/element#8855]
### Existing Component
是

### Component Name
el-menu el-menu-item

### Description
When I use el-menu with router mode, it must fully match the path to be set to the current selected item.

My requirement is a two level router that does not display the submenu, just setting the current real route through the code.

At present, when a two - level route is set up, the first level menus cannot match the routing, and the selected effect can not be obtained.

** root router path:  **
```
/home
/account
/system
```

** account has some children router **
```
/account/dashboard
/account/transaction
/account/  redirect to :   /account/dashboard
```

```html
<el-menu>
  <el-menu-item index='/home'>Home</el-menu-item>
  <!-- 
     want router path fuzzy match /account/* or /account* 
  -->
  <el-menu-item index='/account'>Account</el-menu-item> 
  <el-menu-item index='/system'>System</el-menu-item>
</el-menu>
```

the el-menu just show root router path, account page has a sidebar to control his children router.
whether any account router path selected, my requirement is always Account menu focused.

Now, the Account menu can't set focus.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by xiongchengqing** [comment]
the same requirement comes to me. why not support? @daviyang35 do you get out from it?
