### ISSUE TITLE
[Bug Report] el-input change event is not tigger on keydown

### ISSUE THREAD

**Issue by pavinthan** [ElemeFE/element#8858]
### Element UI version
2.0.8

### OS/Browsers version
mac os high sierra

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
on key up no value logs

### What is Expected?
el-input change event is tigger on keydown

### What is actually happening?
el-input change event is not tigger on keydown

**Comment by zuxriddinkamalov** [comment]
Yout can use @change.native="samoFunction"

**Comment by Leopoldthecoder** [comment]
`change` event of Input behaves just like native change event of `<input>`. This is intended. You can use `input` event instead.

**Comment by pavinthan** [comment]
Please check this https://jsfiddle.net/mmx38qxw/114/, It's now working properly

**Comment by pavinthan** [comment]
Thank you @Leopoldthecoder, @input working as expected
