### ISSUE TITLE
官网文档页面经常无法访问

### ISSUE THREAD

**Issue by cgkoreyoshi** [ElemeFE/element#886]
![image](https://cloud.githubusercontent.com/assets/14900764/20051784/c314ddd4-a50b-11e6-980d-e8d43a5d0d95.png)
图上是我的本机IP地址，
本地PC Ping 域名element.eleme.io 解析到这个IP 151.101.16.133，经常超时

➜  develop ping element.eleme.io
PING github.map.fastly.net (151.101.16.133): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
64 bytes from 151.101.16.133: icmp_seq=4 ttl=43 time=501.331 ms

请问这是否是服务器不稳定造成的？  多次出现

**Comment by Leopoldthecoder** [comment]
官网是直接放在 gh-pages 上面的，可能你的网络到 GitHub 有些问题。其实可以把这个仓库 clone 下来，切换到 gh-pages 分支，就是一份离线文档。

**Comment by bygsn** [comment]
> 官网是直接放在 gh-pages 上面的，可能你的网络到 GitHub 有些问题。其实可以把这个仓库 clone 下来，切换到 gh-pages 分支，就是一份离线文档。

请问怎么运行呀 我点击这个分支下的index.html文件 页面加载不出来
![image](https://github.com/ElemeFE/element/assets/51038773/3b7699ce-94ba-4b05-a757-dab88d111d68)
![image](https://github.com/ElemeFE/element/assets/51038773/602cb638-53f3-4503-8509-2770b035ee21)
