### ISSUE TITLE
[Feature Request] How to refresh table actions or layout with new data from axios

### ISSUE THREAD

**Issue by kywar59** [ElemeFE/element#8860]
### Existing Component
Yes

### Component Name
Table

### Description
Hello, i extract data from server with axios to put it in a table... the table has actions to change values i mean i 3 colums, 2 of them are a switch to change values true or false just that, but when i get the data the leyout doesnt work so i cant change values :(

Add: reading doc i found a Method call doLayout, but I dont know how to call it when i recive the data from axios to refresh layout and the swtiches work :(

**Comment by firesh** [comment]
Only need change the binding model value, table will update automatic.  You should post your reproduce link. It does not matter with axios, you can try to use `setTimeout` to reproduce your issue.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
