### ISSUE TITLE
[Bug Report] the default sorting order on non default sorting columns is

### ISSUE THREAD

**Issue by wuyiw** [ElemeFE/element#8862]
### Element UI version
2.0.8

### OS/Browsers version
win10 /  chrome 64

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/ge947khw/](https://jsfiddle.net/ge947khw/)

### Steps to reproduce
click '姓名' header to sort

### What is Expected?
'姓名'  column sorted in descending order provided that ``:default-sort="{prop: 'date', order: 'descending'}"``

### What is actually happening?
it's marked sorted in ascending order.
though maybe the default-sort prop is just a combination of 'prop' and 'order' in the initial state, i hope the feature 'first click on a sortable column obey the order in default-sort prop' could be implemented, thx~

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
