### ISSUE TITLE
[Feature Request] theme-default in ui2?

### ISSUE THREAD

**Issue by tinshee** [ElemeFE/element#8865]
### Existing Component
否

### Component Name
 theme-default

### Description
I updated the framwork to 2.* ,But we have to use the theme "theme-default".  I add link to the  theme-default/index.css which copy from older framwork. But something like 'Date Picker'  not work. any way to work? or  the new  theme-default will be updated?

**Comment by Leopoldthecoder** [comment]
`theme-default` is only for 1.x. Use `theme-chalk` instead.

**Comment by tinshee** [comment]
有时候项目需要样式的连续性. 以前项目有一个用1作为标准的ui，现在部分模块更新到2,但还是需要1的样式 ，我只好不更新了永远用1？ 更新不能总是破坏性的吧 ？ 有theme-chalk就应该有个theme-default吧？您不能就这样关闭掉这个issue吧？

**Comment by PanJiaChen** [comment]
我也有吐槽一下，新版的主题颜色太淡了，设计师是不是只适配 retina 屏幕，看久了这个主题眼睛会疼。
当然用户可以自定义颜色，但我觉得大部分人还是很懒的，不太愿意也很麻烦去改。所以我觉得继续提供 `theme-default` 这个主题是一个很好的选择。

> 经过重新设计的 Element 2.0，符合当前设计趋势，适应当前时代审美。摒弃多余的设计修饰，坚持「少即是多」的设计原则。比如，高分屏普及的当下，我们让组件的整体比 1.x「大」了一圈，这样阅读体验会更加友好。与此同时，在默认组件尺寸的基础上，我们也提供了多种不同尺寸，以适应大家的不同需求。
总体来说，2.0 与 1.x 相比较，会显得更加的现代、更加的友好。

`theme-chalk` 可以理解为更现代化更性冷淡风一点，但同时 `theme-chalk` 这种鲜明的主题也是广受大家喜爱的。所以希望官方考虑一下这个问题。
`theme-chalk` 真的太淡了，看久了眼睛疼。
