### ISSUE TITLE
[Bug Report] Form validate not work when rules key is String and

### ISSUE THREAD

**Issue by jinan5694** [ElemeFE/element#8867]
### Element UI version
2.0.8

### OS/Browsers version
win8.1/chrome 63

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/1a510e91/2/](https://jsfiddle.net/1a510e91/2/)

### Steps to reproduce
click button "立即创建"

### What is Expected?
test field is required

### What is actually happening?
test is not required

**Comment by jinan5694** [comment]
update jsfiddle link

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8878
