### ISSUE TITLE
[Feature Request] customize el-form-item element click event

### ISSUE THREAD

**Issue by Wolferring** [ElemeFE/element#8868]
### Existing Component
Yes

### Component Name
el-form-item

### Description
	    <el-form-item 
	      v-for="field in fields"
	      class="form-item"
	      :key="field.id"
	      @click="formItemClick"
	    >
the click event formItemClick doesn't be fired

**Comment by Wolferring** [comment]
must I use @click.native to fire those intial events?

**Comment by Leopoldthecoder** [comment]
Yes.
