### ISSUE TITLE
[Bug Report] El-autocomplete-suggestion in el-dialog will display under model frame when I

### ISSUE THREAD

**Issue by sum131417** [ElemeFE/element#8870]
### Element UI version
2.0.5

### OS/Browsers version
Google Chrome 63.0.3239.84

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/min_su/vkxgwtar/3/](https://jsfiddle.net/min_su/vkxgwtar/3/)

### Steps to reproduce
step1: click the button named "open dialog"
step2: input something to el-input like "北京"
step3: close this dialog
step4: click the button named "open dialog" and then input something , this time we cannot see the autocomplete-suggestions list

### What is Expected?
show me the auto-complete suggestions list on the el-dialog

### What is actually happening?
the suggestion-list was under the dialog and cannot choose the item in list

**Comment by furybean** [comment]
@sum131417  Duplicate with #9315. Please track that one.
