### ISSUE TITLE
[Bug Report] form form validation, when verifying whether a number is a number, is not accurate enough

### ISSUE THREAD

**Issue by liunewshine** [ElemeFE/element#8873]
### Element UI version
2.0.8

### OS/Browsers version
Win10/Chrome 63.0.3239.84

### Vue version
2.5.11

### Reproduction Link 示例为官网原版代码
[https://jsfiddle.net/liunewshine/y74zsLm3/](https://jsfiddle.net/liunewshine/y74zsLm3/)

### Steps to reproduce
输入33dd

### What is Expected?
验证不通过

### What is actually happening?
验证通过

![image](https://user-images.githubusercontent.com/7698511/34097955-c998204a-e415-11e7-8751-f6e6c56fd3e3.png)

**Comment by sum131417** [comment]
这个验证确实有bug，只要首位输入的是数字就能通过验证，例如3ewerwr也是能通过的，我都是用正则表达式···

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/issues/7945
