### ISSUE TITLE
When updating the form data,'current-change'will be executed

### ISSUE THREAD

**Issue by Whalefallsea** [ElemeFE/element#8874]
### Element UI version
2.0.8

### OS/Browsers version
window 7/ chrome 63.0.3239.84

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/vnt4p6mr/](https://jsfiddle.net/vnt4p6mr/)

### Steps to reproduce
1、选择一行，弹出选择改变的弹框
2、点击更新数据按钮更新数据，这时也会弹出选择改变的弹框，并且值为null

### What is Expected?
更新数据不会触发current-change，只在人为选择的行的时候执行current-change

### What is actually happening?
更新表格数据会导致current-change被执行，并且变化值为null

**Comment by Clago** [comment]
解决了吗，我也碰到这个问题。搜索如果我先点击了后面的页数，再搜索，如果只有一页数据，改变total后会自动触发current-change事件，点击也是触发这个事件，这种情况下会触发两次http请求。

**Comment by furybean** [comment]
设计如此，如果不这么做，会导致 currentRow 是一个不存在的数据。如果你想你的例子里面的 current-change 不触发，设置一下 row-key="date" 即可。Online demo: https://jsfiddle.net/vnt4p6mr/1/ 。
