### ISSUE TITLE
[Bug Report] data table under the composite CPU occupancy increase, page (20%) by page Caton

### ISSUE THREAD

**Issue by EthanOrange** [ElemeFE/element#8875]
### Element UI version
2.0.8

### OS/Browsers version
win10/Chrome 63.0.3239.84

### Vue version
2.5.11

### Reproduction Link
[https://codepen.io/sanlang/pen/xpZEoo](https://codepen.io/sanlang/pen/xpZEoo)

### Steps to reproduce
等待fetch test data
拉动table滚动条 或者 进行表格行删除  
观察cpu占比 和 页面是否卡顿

### What is Expected?
大量复合元素组成的表格行 在进行页面交互时 不会卡顿

### What is actually happening?
行删除和表格滚动条拉动时 出现cpu占用率剧增  以及页面卡顿

**Comment by agrass-GitHub** [comment]
就只是单纯的行样式hover上下滑动都会导致 cpu 狂升。
