### ISSUE TITLE
[Feature Request] <el-col type="flex"></el-col> 设置wrap行为

### ISSUE THREAD

**Issue by lazywhite** [ElemeFE/element#8877]
### Existing Component
是

### Component Name
el-col

### Description
目前el-col使用flex布局， 只能设置justify行为， 无法设置wrap行为

**Comment by Leopoldthecoder** [comment]
是指 `flex-wrap` 属性？

**Comment by lazywhite** [comment]
对的

**Comment by Leopoldthecoder** [comment]
flex 相关的 CSS 属性有很多，我们可能不会把所有属性都内置为 API，目前提供的 `justify` 和 `align` 算是最常用的两个。其他属性请通过添加 CSS 来解决。
