### ISSUE TITLE
[Bug Report] Table sorting undefined (when some elements are missing?)

### ISSUE THREAD

**Issue by wsw70** [ElemeFE/element#8879]
### Element UI version
2.0.8

### OS/Browsers version
Chrome 62

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/6ttd5g6u/1/](https://jsfiddle.net/6ttd5g6u/1/)

### Steps to reproduce
The attached JS fiddle has a collection of elements to be tabularized. Some elements are incomplete (maybe this is the reason for the issue?).

When clicking on the column descriptor, the table is re-sorted but some of the positions are random. For instance when the first column is sorted down, the rowas are incosnistant (some blanks for that column, among others existing but otherwise not sorted correctly). 

The second column (where all elements are present - again, it may not be the reason) teh behaviour seems normal.

### What is Expected?
that the sorting works for a column (including one where all the elements are not present)

### What is actually happening?
some columns are not sorted correctly

**Comment by Leopoldthecoder** [comment]
Table uses `Array.sort` to sort the columns, but in this case it cannot work as expected: https://jsfiddle.net/6ttd5g6u/2/ (see the console). Implement your own `sort-method` instead.

**Comment by wsw70** [comment]
Thank you. So the issue was with the missing keys -- if someone happended to stuble upon the same problem, see for instance https://stackoverflow.com/questions/47870887/how-to-fill-in-missing-keys-in-an-array-of-objects, I used Faly's answer which was better than my code in the question
