### ISSUE TITLE
[Feature Request] Haven't access to wrap table rows in transition component

### ISSUE THREAD

**Issue by Sillanium** [ElemeFE/element#8882]
### Existing Component
Yes

### Component Name
Table

### Description
Hi. I want make transitions on table rows, but i can't wrap "tr" element in "transition" element. I would like get more control on table layout. Thanks.
Best, Alex.

**Comment by Leopoldthecoder** [comment]
In the current implementation, it is impossible to gain access to `<tr>`s. I'm afraid you'll have to implement your own table if you must use transitions for rows.

**Comment by Sillanium** [comment]
@Leopoldthecoder thank you for quick response ! Can i create feature request for virtual list component ?
