### ISSUE TITLE
[Bug Report] Missing TypeScript definition of TimeSelect

### ISSUE THREAD

**Issue by SamChan1204** [ElemeFE/element#8888]
### Element UI version
2.0.7

### OS/Browsers version
macOS Sierra 10.12.6 / Google Chrome 62.0.3202.94

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/jfLLnv85/](https://jsfiddle.net/jfLLnv85/)

### Steps to reproduce
import TimeSelect in TS file:
```
import { TimeSelect } from "element-ui";
```

### What is Expected?
Using the component normally.

### What is actually happening?
ERROR: 
```
module "/.../node_modules/element-ui/types/index" does not have exported member "TimeSelect"
```

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8898
