### ISSUE TITLE
[Bug Report] element-ui1.2.9 is unable to customize the topic

### ISSUE THREAD

**Issue by anfisherman** [ElemeFE/element#8889]
### Element UI version
1.2.9

### OS/Browsers version
mac & chrome

### Vue version
2.0.1

### Reproduction Link
[https://jsfiddle.net/jfLLnv85/](https://jsfiddle.net/jfLLnv85/)

### Steps to reproduce
安装element-theme@0.7.2和element-theme-default@1.4.12，然后执行et -i 总是提示' please install element-theme-default
上面的重现链接是无效请不必查看，谢谢！

### What is Expected?
安装element-theme@0.7.2和element-theme-default@1.4.12，然后执行et -i 能够生成element-variable.scss

### What is actually happening?
安装element-theme@0.7.2和element-theme-default@1.4.12，然后执行et -i 总是提示' please install element-theme-default

**Comment by anfisherman** [comment]
有人可以尽快帮助一下吗，已经试过很多种方法了，还是没有解决

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly. Please minify your project and upload it to GitHub.
