### ISSUE TITLE
[Bug Report]  remove element-UI case

### ISSUE THREAD

**Issue by ykl124** [ElemeFE/element#8891]
### Element UI version
2.0.8

### OS/Browsers version
windows 7

### Vue version
2.5.11

### Reproduction Link
[https://github.com/ykl124/ykl124.github.io/blob/master/Image.png](https://github.com/ykl124/ykl124.github.io/blob/master/Image.png)

### Steps to reproduce
i used (electron-vue)[https://github.com/SimulatedGREG/electron-vue] frame. 
As the screenshot , when i installed other node modules such as vue-resource, it automatically removed element-UI node modules.  i tried to install other node modules and got the same situation. 

### What is Expected?
if i installed other node modules and it automatically removed element-UI, i can't use element-UI at all. How can i use element-UI？

### What is actually happening?
if i installed other node modules and it automatically removed element-UI, i can't use element-UI at all. How can i use element-UI？

**Comment by Leopoldthecoder** [comment]
Perhaps you should ask this question in `electron-vue`
