### ISSUE TITLE
[Feature Request] paging components display undefined in total when they are internationalized

### ISSUE THREAD

**Issue by yushanapp** [ElemeFE/element#8893]
### Existing Component
Yes

### Component Name
el-pagination

### Description
elementui 版本 1.4.12
vue-i18n 版本 7.3.2

其它elementui组件都没有问题 分页组件中的 sizes, jumper也没有问题 只有 total 显示为undefinded

`<span  class="el-pagination__total">undefined</span>`

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
