### ISSUE TITLE
[Bug Report] el-tooltip doesn't update scope while in slot-scope

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#8895]
### Element UI version
2.0.8

### OS/Browsers version
Windows 10 / Chrome 63

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/1rzzhuy0/](https://jsfiddle.net/1rzzhuy0/)

### Steps to reproduce
1. click edit button on any row 
2. change some data in dialog and save it
3. table will update the row you modified
4. click the edit button on the same row on step 1, again

### What is Expected?
The data in dialog should change to what you modified on step 2.

note: if remove `el-tooltip` on edit button, everything works fine

### What is actually happening?
The data in dialog remains unmodified

**Comment by leozhang2018** [comment]
same as u

**Comment by supidea** [comment]
same as u

**Comment by lincenying** [comment]
https://jsfiddle.net/1rzzhuy0/1/

**Comment by troy351** [comment]
@lincenying 
Thanks a lot, it does solve the problem.
But still can't explain why my version was failed, guess `scope.row` was cached somehow.
