### ISSUE TITLE
[Feature Request] table attributes height string support Calc ()

### ISSUE THREAD

**Issue by iTaster** [ElemeFE/element#8896]
### Existing Component
是

### Component Name
table

### Description
“Table 的高度，默认为自动高度。如果 height 为 number 类型，单位 px；如果 height 为 string 类型，则 Table 的高度受控于外部样式。”
例如：<el-table
                :data="tableData.data"
               height="calc(100vh - 232px)"

这里的calc()应该算是字符串吧，能否支持直接这样写？

另外还发现，如果这样写：
html:
    <el-table
                :data="tableData.data"
                :style="styleObject"
                v-loading="listLoading"
                element-loading-text="加载中…"
js:
           styleObject:{
                height:'calc(100vh - 232px)'
            },
滚动条消失

**Comment by furybean** [comment]
@iTaster 目前的实现是：如果 height 如果是字符串，则高度是从外部样式决定高度。也就是说，height 随便设置一个值，然后这么使用：https://jsfiddle.net/Lb3yLo2r/2/。

**Comment by furybean** [comment]
@iTaster 这么用会更方便一些，后面我会考虑支持这么写。
