### ISSUE TITLE
[Bug Report]memory leaks after this.$confirm been called

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#8897]
### Element UI version
2.0.8

### OS/Browsers version
all

### Vue version
2.5.3

### Reproduction Link
https://jsfiddle.net/0qq32dym/1/

### Steps to reproduce
1. open chrome dev-tools, go to memory panel
2. take a heap snapshot
3. press foo
4. press home
5. press the button to call a confirm dialog
6. press foo
7. take a heap snapshot again
8. compare the two snapshot, there is a memory leak. vueComponents in home can't been destroyed

note:  step 5 is the most important one, if you don't call the dialog, and then continue the following steps, there will be no leaks

### What is Expected?
no memory leaks

**Comment by zzzgit** [comment]
guys, it's a serious bug

do you know how to know whether there is a memory leak?
![image](https://user-images.githubusercontent.com/1060733/34207759-c9c96328-e5c6-11e7-9cab-12a837b55a03.png)
these variables won't been destroyed if you take step 5

**Comment by furybean** [comment]
@zzzgit This is an expected behavior. MessageBox will create a singleton Vue component, and will use this componet until close this window.
