### ISSUE TITLE
提高 el-table 对 null 类型数据的容错性

### ISSUE THREAD

**Issue by jin5354** [ElemeFE/element#890]
### ElementUI version
1.0.0-rc.8

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.4

### Reproduction Link
https://jsfiddle.net/5692qoge/

### Steps to reproduce
看console

### What is Expected?
null 项渲染为空白行

### What is actually happening?
dataArray 的首项不为 null 的话，后续数组成员出现 null 时报错。

**Comment by furybean** [comment]
刚想去修这个问题，发现最新版本已经 Okay 了：https://jsfiddle.net/furybean/5692qoge/1/

**Comment by furybean** [comment]
应该是没问题了，因为换了多选的实现方式，你可以更新一下版本试试。 @jin5354

**Comment by jin5354** [comment]
@furybean  rc.9没问题了，good job！

**Comment by chenam** [comment]
1.3.3版本对数组成员出现null的容错，不支持了？
