### ISSUE TITLE
Cascader 级联选择器

### ISSUE THREAD

**Issue by alexx617** [ElemeFE/element#8901]
Element UI version

2.0.8

OS/Browsers version

win10

Vue version

2.5.2

Reproduction Link

[https://jsfiddle.net/635qc4mn/)

Steps to reproduce

官方文档的级联选择器的 #动态加载次级选项

What is Expected?

做省市县联动,点击省后触发@active-item-change,请求二级菜单ajax后端接口的话无法触发返回的二级菜单,需要再点击一次@active-item-change,如不请求ajax则无此问题

What is actually happening?

**Comment by Maconzhang** [comment]
我也有相同的问题  兄弟你解决了吗？
