### ISSUE TITLE
[Feature Request] element-datepicker

### ISSUE THREAD

**Issue by HuneLei** [ElemeFE/element#8904]
### Existing Component
是

### Component Name
DatePicker

### Description
Link
https://github.com/ElemeFE/element/tree/v2.0.8/packages/date-picker

Description
2.0.8版本的DatePicker组件太优秀了，但在此之前用旧版本完成的项目却用不上，虽然有element-datepicker提供，却不是最新的，非常希望能够同步一下，感谢你们提供了这么棒的库供我们使用！

**Comment by Leopoldthecoder** [comment]
Updated to 2.0: https://www.npmjs.com/package/element-datepicker . Note that you should install `element-theme-chalk` instead of `element-theme-default`.

**Comment by lutuandat0411** [comment]
Because some reasons, I only want to install element-datepicker and element-theme-chalk instead of install all package of element-ui. Can I?
