### ISSUE TITLE
[Bug Report] Theme-chalck recursive style including [SCSS]

### ISSUE THREAD

**Issue by expert** [ElemeFE/element#8905]
### Element UI version
2.0.8

### OS/Browsers version
Mac OS

### Vue version
2.5.12

### Reproduction Link
[https://github.com/expert/element-ui-bug](https://github.com/expert/element-ui-bug)

### Steps to reproduce
git clone git@github.com:expert/element-ui-bug.git
cd element-ui-bug
npm install
npm start

open in browser http://localhost:8080/

Get this result: 
https://drive.google.com/file/d/1pT0x2bSvJfFJaSJpQaNmOYxE076iFHIu/view?usp=drivesdk

### What is Expected?
To see one time compilation for css class: 

.el-input {
    position: relative;
    font-size: 14px;
    display: inline-block;
    width: 100%;
}

https://drive.google.com/file/d/1St4H4fUN8SV6qe6YB3fca7ouTUu9SICH/view?usp=drivesdk

### What is actually happening?
When I use SCSS file to precompile assets 
https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/index.scss

It include multiple times the same files. 
For example @imports -> 
https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/input.scss
https://github.com/ElemeFE/element/blob/dev/packages/theme-chalk/src/input-number.scss

The input-number.scss include again file input.scss. Which already was included in index.scss

**Comment by Leopoldthecoder** [comment]
`input-number.scss` has to include `input.scss` because all components can be imported on demand. In production these duplicate styles can be removed with `optimize-css-assets-webpack-plugin`. `vue-cli` already takes care of it for you: https://github.com/expert/element-ui-bug/blob/master/build/webpack.prod.conf.js#L53-L59

**Comment by expert** [comment]
@Leopoldthecoder thanks for clarification
