### ISSUE TITLE
[Bug Report] `v-loading` does not clear the `el-loading-parent` when the component is destroyed

### ISSUE THREAD

**Issue by AntoineEsteve** [ElemeFE/element#8906]
### Element UI version
2.0.8

### OS/Browsers version
macOS Sierra 10.12.6

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/zet1vyLg/](https://jsfiddle.net/zet1vyLg/)

### Steps to reproduce
- Create a component using `v-loading.fullscreen.lock`
- Destroy the component that contains the `v-loading` directive while it is still loading
- The `el-loading-parent` classes (`el-loading-parent--hidden` ...) are still there (preventing the user to scroll etc)

### What is Expected?
Remove the `el-loading-parent` classes 

### What is actually happening?
The `el-loading-parent` classes (`el-loading-parent--hidden` ...) are still there (preventing the user to scroll etc)

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8914

**Comment by AntoineEsteve** [comment]
Thank you ! What is the expected release date ?

**Comment by Leopoldthecoder** [comment]
Should be released before next Monday.
