### ISSUE TITLE
When two dialog appears in the [Bug Report] single page, the second dialog service mode loading does not work

### ISSUE THREAD

**Issue by bingzhimengwu** [ElemeFE/element#8908]
### Element UI version
2.0.7

### OS/Browsers version
chrome 62.0.3202.94（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/119/](https://jsfiddle.net/mmx38qxw/119/)

### Steps to reproduce
打开第一个dialog可以激活服务方式的loading加载，但是顺位第一个之后的dialog就不行

### What is Expected?
打开不同的dialog，都可以激活dialog状态

### What is actually happening?
打开不同的dialog，都可以激活dialog状态

**Comment by Leopoldthecoder** [comment]
因为页面上有两个 `.el-dialog` 元素，所以用 `.el-dialog` 永远都只能选到第一个 Dialog。https://jsfiddle.net/mmx38qxw/120/
