### ISSUE TITLE
[Bug Report] Slow performance for table component

### ISSUE THREAD

**Issue by xeoshow** [ElemeFE/element#8909]
### Element UI version
1.2.5

### OS/Browsers version
windows/chrome

### Vue version
2.0.3

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
此问题非常容易重现，只要表格数据超过500行，就非常慢。
不知是否有懒加载或分页模式？找了文档没发现。谢谢！！

### What is Expected?
很快可以加载出来，滚动数据顺畅

### What is actually happening?
加载比较慢，滚动慢

**Comment by xeoshow** [comment]
以前记得有virtual scrolling技术，可以大大加强巨大数据量下的表格性能，比如slickgrid之类:
https://github.com/mleibman/SlickGrid

如果elementui可以把这个技术吸纳融合进来，就完美了！

**Comment by Leopoldthecoder** [comment]
Duplicate of #6089

**Comment by patie** [comment]
checkbox checking is also very slow when there is more than 100 rows, its possible to do something with that?
