### ISSUE TITLE
[Bug Report] Some of the picker-options don't work for datetime picker

### ISSUE THREAD

**Issue by KingMario** [ElemeFE/element#8912]
### Element UI version
2.0.8

### OS/Browsers version
Mac OS X 10.12.6

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/KingMario/t8hn6fc4/](https://jsfiddle.net/KingMario/t8hn6fc4/)

### Steps to reproduce
set picker options for a date-picker of datetime type

### What is Expected?
the time picker part of the panel should use the picker options and have the same behavior as time-picker

### What is actually happening?
The following options don't work:

    selectableRange: '18:30:00 - 20:30:00',
    start: '08:30',
    step: '00:15',
    end: '18:30',

**Comment by Altamill** [comment]
+1 Having the same problem here

**Comment by Leopoldthecoder** [comment]
Duplicate of #8979

**Comment by Blizzard-liu** [comment]
已经实现了吗？
