### ISSUE TITLE
After [Bug Report] changes the data of the el-carousel-item, the picture is all display=none by default.

### ISSUE THREAD

**Issue by DengRiGuang** [ElemeFE/element#8915]
### Element UI version
2.0.8

### OS/Browsers version
google chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1.我从服务器上拿到图片资源，放到data中，在遍历到carousel。
2.然后有两个按钮，默认第一个选中，当我点击第二个按钮更换图片资源(资源都已异步请求下来的了，都放在data里)
3.最后carousel-item,的样式中都加上了display=none。

### What is Expected?
我想要的预期是，点击第二个按钮的时候，默认第一个展示出来，第二个以上的隐藏起来。

### What is actually happening?
数据都是没问题的，能拿到图片

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by DengRiGuang** [comment]
https://jsfiddle.net/mmx38qxw/122/?utm_source=website&utm_medium=embed&utm_campaign=mmx38qxw
