### ISSUE TITLE
After [Bug Report] changed the data of el-carousel-item, the default picture is all display = none

### ISSUE THREAD

**Issue by DengRiGuang** [ElemeFE/element#8918]
### Element UI version
2.0.8

### OS/Browsers version
google chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/122/](https://jsfiddle.net/mmx38qxw/122/)

### Steps to reproduce
1.从服务器上拿到图片资源，放到data中，在遍历到carousel。2. 
然后有两个按钮，默认第一个选中，当我点击第二个按钮时更换图片资源（资源都已异步请求下来的了，都放在数据里）
3.最后carousel-item，的样式中都加上了display = none。

### What is Expected?
我想要的预期是，点击第二个按钮的时候，默认第一个展示出来，第二个以上的隐藏起来。

### What is actually happening?
全部都隐藏了

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8921/files#diff-a79238b45d9b8b1c0f55fb07850b74eb

**Comment by DengRiGuang** [comment]
@Leopoldthecoder 可能我表达错误咯1，我是想好比点击一个按钮，carousel的第一个显示出来，点击第二个按钮时，属于第二个按钮的数据中的第一个显示出来，未显示的我可以隐藏起来，通过点击prev按钮或者next按钮切换就行，先行谢谢啦

**Comment by Leopoldthecoder** [comment]
是的，我在上面那个 PR 里修复了

**Comment by DengRiGuang** [comment]
@Leopoldthecoder 可是我照着来修改后，没发生改变

**Comment by Leopoldthecoder** [comment]
直接改没用的，要编译

**Comment by DengRiGuang** [comment]
@Leopoldthecoder npm i ？

**Comment by DengRiGuang** [comment]
@Leopoldthecoder 什么时候发？项目急着要，谢谢啦
