### ISSUE TITLE
[Feature Request] about the parent-child relationship of Tree components!

### ISSUE THREAD

**Issue by gorkys** [ElemeFE/element#8919]
### Existing Component
是

### Component Name
Tree

### Description
属性check-strictly，是否会增加:
勾选时：父联子，子联父，
取消勾选时：父联子，子联父。
而非现在的关联与不关联两个选项。

**Comment by furybean** [comment]
@gorkys 请描述一下你的需求的使用场景。如果一周内未反馈，此 issue 会被关闭，谢谢。

**Comment by gorkys** [comment]
@furybean 权限管理时使用树进行管理，当我点击父节点时相应的子节点应该全部勾选，当我取消某一个子节点时父节点不应该同时取消。

**Comment by furybean** [comment]
可以使用 #9730 中提供的 check 事件。这个事件中会告诉你当前的选中节点和半选中节点。

**Comment by gorkys** [comment]
@furybean 这个我是需要重新拉取这一版下来才会支持这个事件，还是在已有的element里面就可以直接使用？

**Comment by furybean** [comment]
需要等待下一版本发布。
