### ISSUE TITLE
[Feature Request] Is it possible not to cycle though "unsorted" in a Table?

### ISSUE THREAD

**Issue by wsw70** [ElemeFE/element#8920]
### Existing Component
Yes

### Component Name
Table

### Description
Currently, when a column has the `sortable` attribute, clicking on it cycles though

- an ascending sort
- a descending sort
- the "unsorted" version

**Is it possible _not_ to go though the "unsorted" version?** 

I find it more natural to click on a column to sort (up and down only), then on another one (which also sorts it up or down only). This is at least the typical behaviour of sortable tables (where there is no concept of "unsorted", save possibly for the initial data if there is no sorting default).

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
