### ISSUE TITLE
[Bug] bottom of el-switch is chopped off in table cell

### ISSUE THREAD

**Issue by jiayexie** [ElemeFE/element#8924]
### Element UI version
2.0.8

### OS/Browsers version
Windows 10, Chrome 63

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/125/](https://jsfiddle.net/mmx38qxw/125/)

### Steps to reproduce
The switches in the table example look cut off on the bottom. If I open up the Chrome inspector and uncheck 'overflow:hidden' in `.el-table .cell`, the switches look good. It looks like the switch's lower border is outside its actual size.

### What is Expected?
The switch should look complete.

### What is actually happening?
The bottom of the switch looks cut off.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/8925
