### ISSUE TITLE
The [Feature Request] checkbox and radio button item spacing could change by margin-right treatment

### ISSUE THREAD

**Issue by Wolferring** [ElemeFE/element#8928]
### Existing Component
Yes

### Component Name
el-radio,el-checkbox-group

### Description
目前的间距是margin-left实现，当宽度不够，选项需要换行时，样式很难看
![qq 20171221105411](https://user-images.githubusercontent.com/9334893/34238558-4f906e90-e63d-11e7-9b6f-8fb0cf89f3c0.jpg)
![qq 20171221105511](https://user-images.githubusercontent.com/9334893/34238590-72c5d058-e63d-11e7-85f1-f22f67f4ca85.jpg)

**Comment by Leopoldthecoder** [comment]
这种情况请自行覆盖 CSS。
