### ISSUE TITLE
Can [Feature Request] TABLE add a method to get the currently selected section?

### ISSUE THREAD

**Issue by mythbobo** [ElemeFE/element#8938]
### Existing Component
Yes

### Component Name
el-table

### Description
目前获取选中的section只有selection-change事件可以获取，能提供一个方法获取当前选中的section吗？

**Comment by Leopoldthecoder** [comment]
在 `selection-change` 回调里把当前选择行存在一个变量里，需要的时候随时访问这个变量就行。

**Comment by legendjslc** [comment]
的确不太方便
