### ISSUE TITLE
TimePicker 任意时间范围bug

### ISSUE THREAD

**Issue by hujin** [ElemeFE/element#894]
TimerPicker 官网上 任意时间范围demo , 结束时间选择小于开始时间后出现bug
![image](https://cloud.githubusercontent.com/assets/2917135/20059378/fc8470be-a530-11e6-89ef-14e733e34f7d.png)

**Comment by hujin** [comment]
然后再去选择结束时间时 只要结束时间不大于开始时间，结束时间就会去赋值给开始时间

**Comment by QingWei-Li** [comment]
fixed via https://github.com/ElemeFE/element/pull/911
