### ISSUE TITLE
[Feature Request] Add option for right alignment of top tabs

### ISSUE THREAD

**Issue by milislavov** [ElemeFE/element#8942]
### Existing Component
Yes

### Component Name
el-tabs

### Description
At the moment we have the option to set the layout of the tabs to be positioned on top, but we lack the option to specify if the items in the scroll should be aligned to the left or to the right. Since the scroll behavior is controlled with JS, it is not possible to solve this issue by only overwriting CSS. An option like align = left|right, in the case of top/bottom positioned tabs list would be great and is a common need.

**Comment by baiyaaaaa** [comment]
I can not get your problem exactly.Can you provide a actual usage scenario for this problem ?

**Comment by milislavov** [comment]
The usage scenario is as follows - I need to have a tabs component, where the tabs are positioned on the top, but are placed on the right, rather than on the left as it is now.
![image](https://user-images.githubusercontent.com/11681753/35095403-ff1cb4ee-fc50-11e7-94cf-4a3666fbb309.png)
Also, in our case we needed to put the title of the page aligned on the row of the tabs, so will be great to have such a slot.
![image](https://user-images.githubusercontent.com/11681753/35095464-37b960ea-fc51-11e7-99d1-e0effd260789.png)

**Comment by liril-net** [comment]
Moved to product backlog
