### ISSUE TITLE
After the [Feature Request] dropDownMenu opens the drop-down, the scroll bar slid and the pull down along with the move, unfriendly.

### ISSUE THREAD

**Issue by Jing951121** [ElemeFE/element#8949]
### Existing Component
Yes

### Component Name
dropDownMenu

### Description
dropDownMenu 打开下拉后，滚动条滑动，下拉随着移动，不友好。

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
