### ISSUE TITLE
[Bug Report] el-tooltip use native label in slot when el-table with el-pagination

### ISSUE THREAD

**Issue by SherwinChan** [ElemeFE/element#8952]
### Element UI version
2.0.8

### OS/Browsers version
windows 10 / Chrome 63.0.3239.108 (64位)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/L8odoc6h/](https://jsfiddle.net/L8odoc6h/)

### Steps to reproduce
1. click first row "bug测试" will console id
2. click next page and tableData will update
3. click the same row "bug测试" will console id which is the last id

### What is Expected?
fixed this bug.
It doesn't have bug in element-ui 1.x.x version，it shows when I update version to 2.0.8

### What is actually happening?
when use native label in el-tooltip，scope.row doesn't update in the same row（it is bug）。
use component such as el-button in el-tooltip， scope.row will update（it is normal）

**Comment by SherwinChan** [comment]
help me~

**Comment by Leopoldthecoder** [comment]
You need to add `key` to Tooltip: https://jsfiddle.net/L8odoc6h/1/ .

**Comment by SherwinChan** [comment]
@Leopoldthecoder think you~
