### ISSUE TITLE
[Bug Report] [Element Migrating][ElMenu][Attribute]: theme is removed.

### ISSUE THREAD

**Issue by gilbertguan2385** [ElemeFE/element#8953]
### Element UI version
2.0.7

### OS/Browsers version
Google Chrome 63.0.3239.84

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Validate a el-form and get rules attribute in created method like this: this.rules = eval( '( '  rulesStr  ')' )  or  
Object.assign(this.rules,eval( '( '  rulesStr  ')' ))

For some unkown reason,the browser console prints out '[Element Migrating][ElMenu][Attribute]: theme is removed.'

### What is Expected?
when submit form,the validation tips comes out;change some form-input values and the validation is passed, therefore the validation tips dynamically changes.

### What is actually happening?
the truth is that the validation tips is not dynamically changed.

**Comment by gilbertguan2385** [comment]
It's not easy to demonstrate it in a single demo.
Just wanna solve the validation problem caused by theme warning.

**Comment by wacky6** [comment]
The migrating warning is irrelevant.
Please provide a demo that shows the problem.

**Comment by gilbertguan2385** [comment]
The validation problem is not caused by migrating warning.
**Diff form-item.vue between v2.0.7 and v1.4.9**,you can find the required attribute in props is default undefined in v2.0.7.

```
required: {
        type: Boolean,
        default: undefined
      }
```

After I initialize the required value in el-form-item element in template and initialize the rules in created lifecycle, the validation is dynamically available.

**Comment by gilbertguan2385** [comment]
I write a demo and there is no dynamic validation problem.I don't know why this problem happens in my project.Here is my demo:
```
<html>

<head>
    <script src="https://unpkg.com/vue@2.5.2/dist/vue.js"></script>
    <script src="https://unpkg.com/element-ui@2.0.7/lib/index.js"></script>
</head>

<body>
    <div id="app">
        <el-form :model="formEntity" ref="formEntity" :rules="rules" label-width="100px" label-suffix=":">
            <el-form-item label="" prop="code">
                <el-select filterable v-model="formEntity.code" auto-complete="off">
                    <el-option v-for="item in list" :value="item.code" :label="item.name" :key="item.code" />
                </el-select>
            </el-form-item>
            <el-form-item label="" prop="name">
                <el-input v-model="formEntity.name" auto-complete="off"></el-input>
            </el-form-item>
            <el-form-item label="" prop="desc">
                <el-input type="textarea" :autosize="{ minRows: 1, maxRows: 2}" v-model="formEntity.desc" auto-complete="off"></el-input>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" @click="add">确 定</el-button>
            </el-form-item>
        </el-form>
    </div>
</body>

<style lang="scss" scoped>
    @import url("https://unpkg.com/element-ui@2.0.7/lib/theme-chalk/index.css");
</style>

<script type="text/javascript">
    var Main = {
        data() {
            return {
                list: [{
                    code: "aaaa",
                    name: "aaaaaaaaaaaa"
                }],
                formEntity: {
                    code: "aaaa",
                    name: null,
                    desc: null
                },
                rules: {}
            }
        },
        created() {
            console.log('created method execute begin...');

            Object.assign(this.rules, eval(
                '({code: [{required: true,message: "not empty",trigger: "blur"}],name: [{required: true,message: "not empty",trigger: "blur"}],desc: [{required: true,message: "not empty",trigger: "blur"}]})'
            ));
            console.log('created method execute end...');
        },
        methods: {
            add() {
                this.$refs['formEntity'].validate(valid => {
                    if (valid) {
                        console.log('validate success');
                    } else {
                        console.log('validate fail');
                    }
                });
            }
        }
    };
    console.log('before mount');
    var Ctor = Vue.extend(Main);
    new Ctor().$mount('#app');
    console.log('after mount');
</script>

</html>
```

I think the problem maybe the added default required value in v2.0.7,it changes the parent-child component interaction behavior.

**Comment by Leopoldthecoder** [comment]
You can minify your project and upload it to GitHub.

**Comment by Leopoldthecoder** [comment]
Closing for lack of reproduction.
