### ISSUE TITLE
[Bug Report] The Bug of el-tabs when tabs have table component 

### ISSUE THREAD

**Issue by huaibaomengxiang** [ElemeFE/element#8954]
### Element UI version
2.0.8

### OS/Browsers version
windows

### Vue version
2.5.13

### Reproduction Link
[https://github.com/huaibaomengxiang/manage/blob/master/index/src/page/monitor.vue](https://github.com/huaibaomengxiang/manage/blob/master/index/src/page/monitor.vue)

### Steps to reproduce
it will show when click diffenent tab

### What is Expected?
tabel width is 100%

### What is actually happening?
tabel width from 70% to 100% cause a quickly animation

**Comment by baiyaaaaa** [comment]
Reproduction Link 404
