### ISSUE TITLE
Whether [Feature Request] el-checkbox-group can determine a maximum of several checkbox

### ISSUE THREAD

**Issue by limingyangit** [ElemeFE/element#8958]
### Existing Component
是

### Component Name
el-checkbox-group 

### Description
目前el-checkbox-group 有max 属性判断最多选择几个。但是我想要超过最多选择后，可以给出提示。请问怎么添加此方法

**Comment by Leopoldthecoder** [comment]
设置了 `max` 属性后就无法超过最多选择了。
