### ISSUE TITLE
[Bug Report] uses el-autocomplete, pop-up bug in dialog

### ISSUE THREAD

**Issue by wang22123467469** [ElemeFE/element#8961]
### Element UI version
2.0.8

### OS/Browsers version
Google Chrome 62.0.3202.62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
我在dialog中使用从数据库中搜索数据，然后展示数据的层在dialog层下面

### What is Expected?
搜索出来的层应该，在dialog之上，z-index的值应该大于dialog的z-index

### What is actually happening?
yes

**Comment by wanghongrui** [comment]
You can add css with:
`.el-select-dropdown {
    z-index: 99999 !important;
  }`

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by OkanEsen** [comment]
Updated reproduction link: https://jsfiddle.net/okanesen/j8ssw60u/

Here's a video demonstrating the bug: 
![bug-vue-autocomplete-dialog mov](https://user-images.githubusercontent.com/552226/34651448-a6a48338-f3d0-11e7-8715-97930dcbbeac.gif)

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/34657198-f01a950a-f45e-11e7-9b45-1f3d188e6c61.gif)

Didn't reproduce it.

**Comment by OkanEsen** [comment]
It does need a few tries and happens randomly. Maybe it is browser related, I haven't had time to test it yet. I'm using Firefox 59.0a1.

**Comment by aaachou** [comment]
same issue here

**Comment by warplan** [comment]
same issue here

**Comment by warplan** [comment]
same issue here

**Comment by gangche** [comment]
same issue here

**Comment by Leopoldthecoder** [comment]
Ah, this will be fixed in the next release.
