### ISSUE TITLE
pagination component could not set active page when passing props "current-page"

### ISSUE THREAD

**Issue by zhangdongfarmer** [ElemeFE/element#8964]
this issue could be caused by the equation 
`<li
      v-for="pager in pagers"
      :class="{ active: currentPage === pager }"
      class="number">{{ pager }}</li>` in file packages/pagination/src/pager.vue line 16.
i changed operator "===" to "==" then it works fine for me.

**Comment by hainuo** [comment]
type of pager or currentpager is not match
