### ISSUE TITLE
[Bug Report] Can resize table headers by selecting header name

### ISSUE THREAD

**Issue by ozanmuyes** [ElemeFE/element#8967]
### Element UI version
2.0.8

### OS/Browsers version
Linux Debian Jessie (8) / Google Chrome 59

### Vue version
2.5.13

### Reproduction Link
[https://codepen.io/ozanmuyes/pen/mpOdaM?editors=1010](https://codepen.io/ozanmuyes/pen/mpOdaM?editors=1010)

### Steps to reproduce
The last header of the table is unresizable, but if you hover the mouse to previous header's edge and let the cursor change to resize icon ('ew-resize' specifically) and then try to select the text of the unresizable header you see the header resizes.

### What is Expected?
Expectation is the unresizable column's width stay fixed - unless of course a CSS change.

### What is actually happening?
Can resize a column with `:resizable="false"` attribute.

**Comment by liril-net** [comment]
The last column is "reassign" rather than "resize". Because `el-table` will dynamic reassign column width, it is hard to detect users' real purpose. Maybe it is a better solution to give last column a specific width?

**Comment by ozanmuyes** [comment]
Yes for the time being it seems a feasible solution. But nonetheless assigning fixed (pixel) widths (to be more generic anything fixed as measure) bloats the responsible architecture. Say if I want my table to have 50% of the device width for the first two columns under a CSS breakpoint I must do it in JavaScript. This is not always the desirable solution.
Also setting the width of the last 'unresizable' column will look ugly if I have right-fixed column, there will be a gap between last column's right edge and the fixed-right column's left edge. Stating no width for the last (last to fixed-right) column should have render it fluid. Wouldn't it be better?
Another question is reassigning to what exactly? Reassigning onto itself?

**Comment by liril-net** [comment]
1. What is "reassign"
"reassign" means reassign width of this column.

> fit: whether width of column automatically fits its container

`el-table` has a property called `fit` which will automatically reassign widths of columns(no specific width) to fit its container width.

2. gap

You will only see the gap if the sum of columns' width less than its container

**Comment by liril-net** [comment]
I am sorry to confuse you about the meaning of "reassign". What i mean here is that `el-table` will use all available space of its container to fit container's width if you have not specific columns' width.

The demo you provided did have a gap between last column and the right fixed column. This is because that the container width is half of the device(`el-col :sm="12"`). So if you specific the width of each column and the sum of these widths is less than half of the device, it will show a gap because the right fixed columns should align its container's right edge.

**Comment by furybean** [comment]
Sorry, we do not think this is a bug report.
