### ISSUE TITLE
menu 采用Menu-Item 的 route属性无法进行跳转

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#897]
## version
r0.8
```
<el-menu-item v-for="sub in menu.subMenu" :index="sub.routeName" :route="{name:sub.routeName}">
                  <i class="iconfont" :class="[sub.icon]" style="margin-right: 10px;"></i>
                  {{sub.title}}
                  <i class="el-submenu__icon-arrow el-icon-arrow-left"></i>
                </el-menu-item>
```
![qq 20161108000124](https://cloud.githubusercontent.com/assets/9530813/20064706/91d08c6a-a546-11e6-96bc-f85ecae3bad4.png)

已经设置成功，但是无法采用name的方式进行跳转，点击无反应

**Comment by DevilLeven** [comment]
`<el-menu theme="dark" router="router">
      <div v-for="nav  in navdata">

        <el-submenu v-bind:index.prop="nav.path" v-if="nav.children">
          <template  slot="title">{{nav.name}}</template>
          <el-menu-item v-bind:index.prop="cnav.path" v-for="cnav in nav.children" > {{cnav.name}}</el-menu-item>
        </el-submenu>
        <el-menu-item v-bind:index.prop="nav.path"  v-else>{{nav.name}}</el-menu-item>
      </div>

    </el-menu>`

首先 el-menu 的router设置成true，然后el-menu-item 的跳转是根据index属性的 ，index的绑定是这样的v-bind:index.prop="cnav.path"

**Comment by DevilLeven** [comment]
`<el-menu theme="dark" router="router">
      <div v-for="nav  in navdata">
        <el-submenu v-bind:index.prop="nav.path" v-if="nav.children">
          <template  slot="title">{{nav.name}}</template>
          <el-menu-item v-bind:index.prop="cnav.path" v-for="cnav in nav.children" > {{cnav.name}}</el-menu-item>
        </el-submenu>
        <el-menu-item v-bind:index.prop="nav.path"  v-else>{{nav.name}}</el-menu-item>
      </div>

    </el-menu>`

首先 el-menu 的router设置成true，然后el-menu-item 的跳转是根据index属性的 ，index的绑定是这样的v-bind:index.prop="cnav.path"

**Comment by DevilLeven** [comment]
```
<el-menu theme="dark" router="router">
        <el-submenu v-bind:index.prop="nav.path" v-if="nav.children">
          <template  slot="title">{{nav.name}}</template>
          <el-menu-item v-bind:index.prop="cnav.path" v-for="cnav in nav.children" > {{cnav.name}}</el-menu-item>
        </el-submenu>
        <el-menu-item v-bind:index.prop="nav.path"  v-else>{{nav.name}}</el-menu-item>
    </el-menu>

```
首先 el-menu 的router设置成true，然后el-menu-item 的跳转是根据index属性的 ，index的绑定是这样的v-bind:index.prop="cnav.path"

**Comment by masterzhang** [comment]
我之前是这么做的，但是我在一个内嵌的页面的时候，比如当前路由是
`http://www.xxx.com/a/b`
这时点击跳转
会变成`http://www.xxx.com/a/b/c`
如果当前在`http://www.xxx.com/a`
则跳转时是`http://www.xxx.com/c`
这是没有问题的，不知道是我路由配置不对还是怎么样？因此看到`Menu-Item`可以设置`route`属性觉得是不是可以设置这个进行跳转

**Comment by baiyaaaaa** [comment]
@masterzhang 对的，如果通过index只能帮你这么处理，你可以用route属性来设置，具体参数可以去看vue-router的文档。

**Comment by masterzhang** [comment]
@baiyaaaaa 我采用`:route="{name:sub.routeName}"`已经传递了`name`了，可是发现点击还是不能跳转的。
看官网的文档中`route`传递的是`Vue Router 路径对象`。我上面传递了一个命名的路径对象了，可是不能跳转，是不支持吗？还是哪里写的不对？

**Comment by DevilLeven** [comment]
@masterzhang 这个好像不能用:route 还有可以拜托你发一个vue-devtools 的chrome插件。我这谷歌上不去 十分感谢 ziguang_zhang8@163.com

**Comment by masterzhang** [comment]
@DevilLeven 已经发你邮箱了，你试试。还有，这个既然不能使用`:route`,那`:route`这个属性的作用是?

**Comment by baiyaaaaa** [comment]
@masterzhang 我测试这样是可以用的，你是不是配置错了？

**Comment by masterzhang** [comment]
ok，最后发现是自己的问题，之前采用`index`跳转时，由于自己给`index`传递的是'a`而不是`/a`以此在子页面的时候，点击导航栏被认为是相对路由了。

@baiyaaaaa 能否把你的例子给我看看呢？使用`:route`的时候，`Menu`的`router`属性应该是`false`是吧

huayanfighting@sina.com

**Comment by masterzhang** [comment]
@baiyaaaaa 是我错啦，我在使用`:route`的时候，把`Menu`的`router`属性设置成了`false`，被官网文档的`是否使用 vue-router 的模式，启用该模式会在激活导航时以 index 作为 path 进行路由跳转`给迷惑了，以为设置成了`true`就一定以`index`作为跳转。

**Comment by wujinfeng** [comment]
文档就不能写明白些吗？就不能举个例子吗？

**Comment by wujinfeng** [comment]
这个文档还是希望写清楚些，或者举个例子，这个太难搞了

**Comment by uinz** [comment]
exact: false 情况怎么处理?

**Comment by mzm008** [comment]
点击菜单后，我的整个页面都刷新了，导致 左边的menus 每次都刷新！！！
啊哟方法解决？？

**Comment by zmyfrank** [comment]
> 点击菜单后，我的整个页面都刷新了，导致 左边的menus 每次都刷新！！！
> 啊哟方法解决？？

嵌套路由撒

**Comment by wkmian** [comment]
源代码是
```
     handleItemClick: function handleItemClick(item) {
      var _this = this;

      var index = item.index,
          indexPath = item.indexPath;

      var oldActiveIndex = this.activeIndex;
      var hasIndex = item.index !== null;

      if (hasIndex) {
        this.activeIndex = item.index;
      }

      this.$emit('select', index, indexPath, item);

      if (this.mode === 'horizontal' || this.collapse) {
        this.openedMenus = [];
      }

      if (this.router && hasIndex) {
        this.routeToItem(item, function (error) {
          _this.activeIndex = oldActiveIndex;
          if (error) {
            // vue-router 3.1.0+ push/replace cause NavigationDuplicated error 
            // https://github.com/ElemeFE/element/issues/17044
            if (error.name === 'NavigationDuplicated') return;
            console.error(error);
          }
        });
      }
    },
```

所以应该是这么使用
`<el-menu-item  index :route="{name:'LeftTicketQuery'}">调整菜单</el-menu-item>`

蛋疼的写法

**Comment by GC1833938238** [comment]
您好，在开发过程中发现如果使用index属性进行路由参数的传递，会导致页面中的高亮效果无法显示
![image](https://github.com/ElemeFE/element/assets/49679578/f14d08e0-4d47-4efb-b41f-6e68170bc157)
![image](https://github.com/ElemeFE/element/assets/49679578/57a423cc-219b-477c-b6e7-14801b2db826)
但是如果使用route属性进行路由参数配置的话，是无法跳转的，请教下这种问题该怎么解决呀
