### ISSUE TITLE
[Feature Request] Please add checked prop to change checked status

### ISSUE THREAD

**Issue by returnlook** [ElemeFE/element#8976]
### Existing Component
Yes

### Component Name
el-tree

### Description
树节点中能否和节点数据进行双向绑定，通过设置节点数据的checked属性，改变节点的勾选状态，而不是通过方法手动设置节点的勾选状态

**Comment by eightpigs** [comment]
@returnlook  我是动态修改 "default-checked-keys" 属性实现的 ，但用起来还是很麻烦。
@element-bot  希望能尽快实现双向绑定。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by longjiahui** [comment]
why not?  I think that It will be convenient.
