### ISSUE TITLE
[Feature Request] DateTimePicker can use the parameters in the TimePicker component

### ISSUE THREAD

**Issue by Y00z** [ElemeFE/element#8979]
### Existing Component
是

### Component Name
DateTimePicker 

### Description
DateTimePicker 可否使用 TimePicker 组件中是参数

![image](https://user-images.githubusercontent.com/18053148/34331996-d1c375ac-e966-11e7-90fc-ddacfe0a2f08.png)

 我想把这个换成这个

![image](https://user-images.githubusercontent.com/18053148/34332007-edc70606-e966-11e7-8985-c8f5cf8c7f9f.png)

**Comment by wacky6** [comment]
现在换不了。大概3.0可能做？（如果会出3.0的话）

**Comment by wacky6** [comment]
related: https://github.com/ElemeFE/element/issues/8727 https://github.com/ElemeFE/element/issues/8922 https://github.com/ElemeFE/element/issues/8912

**Comment by Leopoldthecoder** [comment]
先加个 label。

**Comment by wacky6** [comment]
做这个feature的话就考虑把几个panel的props/data格式统一一下吧。这样就可以随意拼装了。

**Comment by mcdongWang** [comment]
@Leopoldthecoder 请问:
虽然time selecte 的配置参数不支持, 但是为什么 datetimepicker 中默认的timepicker的 selectableRange的属性为什么也不生效

**Comment by Altamill** [comment]
@Leopoldthecoder helo，请问这个bug修复需要多久或者是否在排期中，项目中正在使用elementui的这个组件，如改用time-select的话需要大批量改动后端代码。

**Comment by vifird** [comment]
已经实现了吗？

**Comment by Blizzard-liu** [comment]
已经实现了吗？

**Comment by worldstop** [comment]
马上2020年了，咋还没实现

**Comment by huhai122** [comment]
emmmmm 也遇到这个问题了

**Comment by Blizzard-liu** [comment]
不用改了 我们公司已经破产了
