### ISSUE TITLE
如何和验证组件vee-validator结合?

### ISSUE THREAD

**Issue by biosrs** [ElemeFE/element#898]
感觉这个基于VUE2.0的组件挺好用的,想问下如何验证el-input输入的内容?比如和vee-validator结合?
纯用input没问题,用el-input就不行了.
如下:
------------------------------------
import VeeValidate from 'vee-validate'
Vue.use(VeeValidate)
------------------------------------
<el-input v-validate data-rules="required|email" :class="{'input': true, 'is-danger': errors.has('email') }" name="email" type="text" placeholder="Email">
</el-input>
<span v-show="errors.has('email')" style="color:red">{{ errors.first('email') }}</span>

**Comment by QingWei-Li** [comment]
http://element.eleme.io/#/component/form#biao-dan-yan-zheng

**Comment by biosrs** [comment]
哈哈,谢谢,我怎么就是没找到呢. @QingWei-Li
