### ISSUE TITLE
[Feature Request] There is a new option in popper.js

### ISSUE THREAD

**Issue by cycold** [ElemeFE/element#8981]
### Existing Component
Yes

### Component Name
el-popover

### Description
Hoping el-popover add positionFixed property 

see https://github.com/FezVrasta/popper.js/pull/487#issuecomment-345430318

**Comment by liril-net** [comment]
What is the use case of this property?

**Comment by cycold** [comment]
> Sorry, Poor English
### Need `el-popover` do not append to body. In my case `el-popover` must be component direct children instead of body.

when `append-to-body` set to `false` the el-popover It doesn't append to body, but el-popover position is absolute. Here needs position is fixed because it's parent element style `overflow: hidden`

```
<div class="_com-grids-selector-wrapper">
    <el-popover ref="popoverGridsSelector"
      @show="$emit('show')"
      @hide="$emit('hide')"
      placement="top"
      trigger="hover"
      v-model="visibile"
      :open-delay="300"
      :offset="0"
      :append-to-body="false"
      :popper-options="{
        boundariesElement: 'body',
        gpuAcceleration: true,
        positionFixed: true,
        preventOverflow: true,
      }">
      <div class="_com-grids-selector">
     .....
```

**Comment by Haydenwoo** [comment]
> > Sorry, Poor English
> 
> ### Need `el-popover` do not append to body. In my case `el-popover` must be component direct children instead of body.
> when `append-to-body` set to `false` the el-popover It doesn't append to body, but el-popover position is absolute. Here needs position is fixed because it's parent element style `overflow: hidden`
> 
> ```
> <div class="_com-grids-selector-wrapper">
>     <el-popover ref="popoverGridsSelector"
>       @show="$emit('show')"
>       @hide="$emit('hide')"
>       placement="top"
>       trigger="hover"
>       v-model="visibile"
>       :open-delay="300"
>       :offset="0"
>       :append-to-body="false"
>       :popper-options="{
>         boundariesElement: 'body',
>         gpuAcceleration: true,
>         positionFixed: true,
>         preventOverflow: true,
>       }">
>       <div class="_com-grids-selector">
>      .....
> ```
Have you solved it？

**Comment by 2ming** [comment]
Have you solved it？positionFixed: true

**Comment by Corgis** [comment]
:append-to-body = "false"
