### ISSUE TITLE
table v-if控制 显示错乱问题

### ISSUE THREAD

**Issue by leiwensu** [ElemeFE/element#8984]
当tab切换时，用v-if控制表格列的显示，前一个tab的数据显示到了后一个tab表格里面，导致数据错乱
![image](https://user-images.githubusercontent.com/12728122/34339488-c3a25530-e9af-11e7-9082-73bd0b2ceb38.png)

![_20171225202024](https://user-images.githubusercontent.com/12728122/34339581-103f57ca-e9b1-11e7-9fd2-57974dbf97d7.png)

使用了官网提供的doLayout方法，无效
![_20171225202103](https://user-images.githubusercontent.com/12728122/34339590-25dd5050-e9b1-11e7-9cc1-110427d10fdd.png)

在表格每一列添加:key=“Math.random()”，表格会随着筛选区的输入内容的变化而重新渲染，虽然是实现了，但是表格会有一个刷新的动作，就是闪一下，让人以为是数据刷新了，实际上只是表格的重新布局，不知道有没有什么完美的解决方法？

**Comment by kang558** [comment]
@leiwensu  楼主解决了吗？我也遇到这个问题了，因为切换tab的数据格式不一样，所以table的宽高设置的也不一样。tab切换时table的宽高没有被刷新，还是上一个tab的宽高

**Comment by leiwensu** [comment]
@kang558 我现在每个Tab对应一个独立的表格，不再公用一个table了，如下：
![image](https://user-images.githubusercontent.com/12728122/36015466-8219b90a-0da9-11e8-87ac-444f0114e768.png)

**Comment by kang558** [comment]
@leiwensu 我现在也是这样的

**Comment by yuanyuanshen** [comment]
有人解决么？也遇到了一样的问题，每次在筛选框中输入，到会导致table重新渲染

**Comment by yuanyuanshen** [comment]
把key=“name” key=“age”  写死 不要写成随机数，不然页面其他数据有变化就会重新渲染

**Comment by xiaoniezi** [comment]
> 把key=“name” key=“age” 写死 不要写成随机数，不然页面其他数据有变化就会重新渲染

大兄弟，谢了！！
