### ISSUE TITLE
dialog弹窗width属性不起作用

### ISSUE THREAD

**Issue by chendechang** [ElemeFE/element#8988]
现在引入的版本是1.4.9，使用el-dialog组件，设置width=“30%”，实际弹窗的大小还是默认的大小，调试看到渲染的情形是：
<div class="el-dialog__wrapper" width="30%" center="" style="z-index: 2001;">
<div class="el-dialog el-dialog--small" style="top: 15%;">
.......
</div>
</div>
可以看到设置的width属性并没有修饰到dialog,而是修饰到wrapper。
期间也换过其他的版本，好像还是一样的问题。
按照这样的行为，样式串改的可能应该不是。
请问其他开发者有遇到这个问题？

**Comment by jason19901028** [comment]
也遇到同样问题，求element官方解答
