### ISSUE TITLE
[Bug Report] The range slider has bad performance or crashes the browser when used with large values

### ISSUE THREAD

**Issue by chetzof** [ElemeFE/element#8989]
### Element UI version
2.0.9

### OS/Browsers version
Ubuntu / Chrome Version 63.0.3239.108 (Official Build) (64-bit)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/127/](https://jsfiddle.net/mmx38qxw/127/)

### Steps to reproduce
Use the slider with the following props
   <el-slider
                v-model="value"
                :min="10"
                :max="100000"
                range
                show-stops
                :step="10"
        >

### What is Expected?
Large values should not affect the performance significantly, for example when displaying large currency ranges 1 million - 10 million
For example here it works fine with huge values http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html

### What is actually happening?
It crashes the browser or sigficantly affects pefrmance

**Comment by liril-net** [comment]
What is the reason to use `show-stops` in ur use case?

**Comment by chetzof** [comment]
Not any specific reason, just a copy from my working code. You can remove it by the issue will remain.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/130/ Removing it resolve this issue. You can refer to http://element-cn.eleme.io/2.0/#/en-US/component/slider#discrete-values to see what `show-steps` does.

**Comment by chetzof** [comment]
Actually the example you showed is pretty glitchy on my not so powerful PC, you can increase the max up to 100000 to see the issue https://jsfiddle.net/mmx38qxw/132/ It drags with significant delay and the CPU is at %100.

Also check the DOM
![selection_249](https://user-images.githubusercontent.com/467230/34356280-29929b12-ea45-11e7-940a-479df8da0023.png)

**Comment by wacky6** [comment]
`show-stops` does not make sense if stops are very dense.
CPU usage won't get any lower, because slider needs to compute every stop's state (shown / not shown)

**Comment by chetzof** [comment]
Yeah, forget about show-stops, I've removed it.
The thing is that there are plenty of other sliders that handle millions or even billions like it's nothing, here's one http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html

So i thought maybe there's a room of improvement for this one or maybe a bug. 
For example i wanted to use it to show price range for real estate and obviously the numbers would be high because a house costs hundreds of thousands of USD(for example) or millions.

**Comment by wacky6** [comment]
So basically you want to define custom stop points (white dots) instead of element-ui computing them for you based on `step`, which results in densely packed stops if `max-min/step` is large.

I guess this could be a PR-welcome? @Leopoldthecoder

**Comment by chetzof** [comment]
Having custom stop points would be nice, but that's a feature request that is out of scope of this ticket i guess....

The problem is that even with basic config
` <el-slider v-model="value1" :min="0" :max="1000000"></el-slider>`
it starts to consume a lot of resources, so all I was hoping is whether some optimization is possible.
Looking at the implementation over the link I provided above, looks like they are not generating a stop point for each step. I assume making Element component working the same would mean basically rewriting it from scratch.

**Comment by wacky6** [comment]
I just took a look into source code. You are right, there appears to be useless computations.

A naive fix will be "short-circuiting" `computed.stops()` if `show-stops` is false. It appears this computed property is only used for that purpose. However, if `show-stops` is true, this problem will still occur (I guess there's no easy fix given slider's current implementation).

Here's the fixed demo: https://jsfiddle.net/8kwe2svt/

The problem is `firstValue / secondValue` gets updated when slider moves, which results in recomputation of `stops` array. This is due to the way Vue considers/deduces state dependencies.

To completely solve this problem, need to redesign step/stops feature.

**Comment by chetzof** [comment]
That is great, thanks a lot! Hopefully this gets merged eventually in the master.

**Comment by Leopoldthecoder** [comment]
@chetzof Sorry I didn't realize this.
@wacky6 Thanks.
