### ISSUE TITLE
[Feature Request] Loading mask background style

### ISSUE THREAD

**Issue by An0nymous0** [ElemeFE/element#8993]
### Existing Component
是

### Component Name
Loading

### Description
加载时遮罩层为模糊效果，视觉感是不是会更好一些

**Comment by liril-net** [comment]
如果用 `filter` 去做 CSS 的模糊效果，需要考虑兼容性的问题。

**Comment by An0nymous0** [comment]
@liril-net 我想说的是，组件默认为模糊效果。不是我想要自己用css实现。

**Comment by liril-net** [comment]
额，我的意思是组件来做这件事得考虑到兼容性问题，所以如果你需要的话，得自己来实现。

**Comment by An0nymous0** [comment]
![image](https://user-images.githubusercontent.com/6836030/34454227-db8ec868-eda1-11e7-9b92-9d6839955cd7.png)
看你已经给这个issue关了。我想知道原生是否考虑这个效果。
