### ISSUE TITLE
[Bug Report] fixed column could height not be updated when the extension column changeed

### ISSUE THREAD

**Issue by scscms** [ElemeFE/element#8994]
### Element UI version
2.0.9

### OS/Browsers version
chrome 62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/scscms/sp102dfb/](https://jsfiddle.net/scscms/sp102dfb/)

### Steps to reproduce
open extension column and switch the TAB,then fixed column height could not be updated.

### What is Expected?
They the same line height

### What is actually happening?
The height can't change

**Comment by furybean** [comment]
This situation is taken into account when implementing the Fixed feature and this is an unfixable issue for implementation decisions. 

The decisions point is that fixed column should not be used with expandable column. If use expandable column, you just need to put the details info into the expandable column.
