### ISSUE TITLE
[Bug Report] el-table can not sort with Pug template language used.

### ISSUE THREAD

**Issue by hitlolo** [ElemeFE/element#8995]
### Element UI version
2.0.9

### OS/Browsers version
firefox/chrome

### Vue version
2.5.13

### Reproduction Link
[https://codepen.io/anon/pen/mpReOe](https://codepen.io/anon/pen/mpReOe)

### Steps to reproduce
Used the api document's data.Works fine in HTML,not working in PUG.

### What is Expected?
el-table sort works in PUG.

### What is actually happening?
not working

**Comment by leRenart** [comment]
This issue is still there, right ?
