### ISSUE TITLE
[Feature Request] Slider range selection numerical display

### ISSUE THREAD

**Issue by 214132049** [ElemeFE/element#8996]
### Existing Component
yes

### Component Name
slider

### Description
Slider range selection can be combined with numerical display (maximum, minimum, range critical value)？

**Comment by Leopoldthecoder** [comment]
不太清楚具体是什么需求，请用中文描述。

**Comment by 214132049** [comment]
231

**Comment by 214132049** [comment]
slider能否添加显示最大最小值、当前范围开始值和结束值的显示？
