### ISSUE TITLE
[Bug Report] [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "timeValue"

### ISSUE THREAD

**Issue by ireeoome** [ElemeFE/element#8999]
### Element UI version
2.0.8

### OS/Browsers version
Windows 10/Chrome 63

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/ireeoo/0rLrca5b/1/](https://jsfiddle.net/ireeoo/0rLrca5b/1/)

### Steps to reproduce
点击datepicker，选择开始时间和结束时间，然后点击确定，控制台会报错：`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "timeValue"`

### What is Expected?
不报错

### What is actually happening?
报错

**Comment by wacky6** [comment]
这个不是element的问题。
search-box的timeValue用法不对。封装组件要自己处理input事件和:value绑定。

参考：
 https://cn.vuejs.org/v2/guide/components.html#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6%E7%9A%84%E8%A1%A8%E5%8D%95%E8%BE%93%E5%85%A5%E7%BB%84%E4%BB%B6

**Comment by ireeoome** [comment]
@wacky6 searchbox的input事件往哪绑呢？input在datepicker内部，好像也没有抛出来~

**Comment by wacky6** [comment]
https://jsfiddle.net/9skL59rq/

**Comment by ireeoome** [comment]
@wacky6 http://element-cn.eleme.io/2.0/#/zh-CN/component/date-picker这里面好像没有input事件的api~

**Comment by wacky6** [comment]
input是vue对v-model的习惯约定。vue文档关于v-model的应该写了

**Comment by ireeoome** [comment]
@wacky6 
好的，是我孤陋寡闻了，已经搞定了，谢谢啦~
