### ISSUE TITLE
希望 el-upload 组件中增加一个默认显示缩略图。

### ISSUE THREAD

**Issue by oldway520** [ElemeFE/element#900]
希望 el-upload 这个组件中增加一个默认显示缩略图。 
![image](https://cloud.githubusercontent.com/assets/3321193/20085940/6aa1e57e-a5a7-11e6-8e07-9125197a12f0.png)
只能上传后才显示缩略
![image](https://cloud.githubusercontent.com/assets/3321193/20085952/84c30136-a5a7-11e6-8f30-b395b6edfa7d.png)

**能否通过设置默认值显示缩略图**

**Comment by baiyaaaaa** [comment]
其实现在你可以通过slot自己处理这一块的内容
![image](https://cloud.githubusercontent.com/assets/3655403/20086216/83051f08-a5a9-11e6-8935-a8ba1491e75b.png)
你的使用场景能简单说下吗？

**Comment by oldway520** [comment]
```
    <slot v-if="!showCover"></slot>
    <cover :image="lastestFile" :on-preview="onPreview" :on-remove="onRemove" v-else></cover>
```
```
  computed: {
    lastestFile() {
      var fileList = this.$parent.fileList;
      return fileList[fileList.length - 1];
    },
    showCover() {
      var file = this.lastestFile;
      return this.thumbnailMode && file && file.status !== 'fail';
    },
    thumbnailMode() {
      return this.$parent.thumbnailMode;
    }
  },
```
不希望重复再自定义solt
看到代码里面如果thumbnailMode=true的时候上传成功后会显示缩略图
是否可以把cover重复利用起来
其实是懒！

**Comment by baiyaaaaa** [comment]
1.0以后会对这一块进行功能增强
