### ISSUE TITLE
How does [Feature Request] Table-column support the maximum width of the limit?

### ISSUE THREAD

**Issue by stevieyu** [ElemeFE/element#9003]
### Existing Component
是

### Component Name
Table-column

### Description
有些Table-column用min-width 会造成多余空白，导致部分Table-column在大屏幕宽度不足，所以多个max-width搭配限制会好一点

**Comment by Leopoldthecoder** [comment]
不用给每个 Column 设置宽度。未设置宽度的 Column 会撑满容器。
