### ISSUE TITLE
[Feature Request] Circular Button

### ISSUE THREAD

**Issue by NoahCardoza** [ElemeFE/element#9006]
### Existing Component
Yes

### Component Name
Button

### Description
I think a circular button is in order, at least for icons. I kept editing CSS myself and finally figured a circle attribute should just be added to the Button element.  I'm pretty new to GitHub and all, but I'd be happy to add it.

I hope I'm requesting this through the right channels.

**Comment by QingWei-Li** [comment]
Can you provide an online example? We will communicate with our designers.

**Comment by QingWei-Li** [comment]
Can you provide an online example? We will communicate with our designers.

**Comment by NoahCardoza** [comment]
Sure thing, here you are https://jsfiddle.net/NoahCardoza/4zd9pz0a/2/

**Comment by NoahCardoza** [comment]
Those look amazing! Good work.

Thanks!
