### ISSUE TITLE
[Bug Report] 官网示例 DateTimePicker 选择 bug

### ISSUE THREAD

**Issue by MinosIE** [ElemeFE/element#9009]
### Element UI version
1.4.12

### OS/Browsers version
win 7 /  chrome v61

### Vue version
2.3.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
官网示例：
DateTimePicker 日期时间选择器 => 日期和时间范围 => 默认
先更改开始时间时分秒，点击确定输入框时间改变。
再更改结束时间时分秒，点击确定输入框时间没有改变

### What is Expected?
先更改开始时间时分秒，点击确定输入框时间改变。
再更改结束时间时分秒，点击确定输入框时间改变

### What is actually happening?
先更改开始时间时分秒，点击确定输入框时间改变。
再更改结束时间时分秒，点击确定输入框时间没有改变

**Comment by kuaipaowoniu** [comment]
el-date-picker组件是不是有BUG，官方的例子拿下来直接跑且没有任何操作都会有警告出现：
1、 Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "type"
2、$listeners is readonly.
3、$attrs is readonly.

**Comment by MinosIE** [comment]
@kuaipaowoniu 你是什么环境？哪个版本的？我部署在项目中是正常的，我反应的bug在官网的示例上面依然存在的

**Comment by kuaipaowoniu** [comment]
版本号2.0.9，系统window7，浏览器google
Vue-Cli的环境

**Comment by kuaipaowoniu** [comment]
点击输入框时就报出一堆warn！看意思是修改了从父组件传过来的prop值，可能会造成数据流的混乱，，给了一个警告

**Comment by MinosIE** [comment]
@kuaipaowoniu 我们项目用的是1.4.12， vue版本2.3.0。没尝试过升级，你看看你vue是哪个版本的，是不是需要同步到对应版本

**Comment by Leopoldthecoder** [comment]
@MinosIE 没能重现你的问题，另外 1.x 版本已经停止维护，请升级至 2.x

**Comment by MinosIE** [comment]
![test](https://user-images.githubusercontent.com/7985586/34472873-04592cba-efa6-11e7-8576-a76c7e16ba93.gif)
@Leopoldthecoder 上了一张截图，您参考一下

**Comment by paysage** [comment]
日期控件坑好多  在datetimepicker里 弹出时间选择的picker 此时失焦的话 整个面板收起 再次弹开的时候 时间选择的picker默认就展开了 而且指向的初值是0:0:0 并且惊奇的发现 无论1.x版本还是2.x版本 这个问题都存在  不知道官方怎么想的 bug太明显 这会官网都还挂着呢

**Comment by MinosIE** [comment]
@paysage 反馈无用了 1.x的版本 已经不维护了
