### ISSUE TITLE
The return value of [Bug Report] Select Events remove-tag is not tag, and returns a Vue component bug

### ISSUE THREAD

**Issue by Faithree** [ElemeFE/element#9011]
### Element UI version
2.0.9

### OS/Browsers version
win 10 / chrome v61

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/61x6dd8t/](https://jsfiddle.net/61x6dd8t/)

### Steps to reproduce
multiple模式下选中多个tag之后，点击删除，触发 remove-tag事件返回的不是tag值，而是一个vue组件

### What is Expected?
返回一个tag对应的value

### What is actually happening?
返回一个vue组件

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/9090
