### ISSUE TITLE
[Feature Request] sort-change passes to the processing function to pass {null, null, null}

### ISSUE THREAD

**Issue by KOMKZ** [ElemeFE/element#9014]
### Existing Component
Yes

### Component Name
el-table

### Description
设置：
```
sortable="custom" @sort-change="onSortChange"
```

然后发现，多次点击的时候传递过来处理函数的参数会有`{null, null, null}`, 这让我很困扰，此时我无法知道这个列是什么，我们的服务器使用以下格式进行多级排序：
```
?sort=-u_created_at, u_id, -u_updated_at
```
我需要在箭头没有高亮的时候将某些排序列从数组中移除出去，但是传递过来的参数让我不知道到底是哪个列。是否有其他方法可以解决呢！请问？

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by qusiba** [comment]
@KOMKZ 你可以在 table 的 @header-click 里面捕获点击事件记录最后点击的 column。
然后在 @sort-change 里面写个 setTimeout 0 来拿到这个 column。正好在做一个多重 sort 的需求。
不过初始显示多个 sort 还没想到要怎么做。
