### ISSUE TITLE
[Bug Report] official network NavMenu folding example, after adding group folding style error

### ISSUE THREAD

**Issue by UncleCarlos** [ElemeFE/element#9016]
### Element UI version
2.0.9

### OS/Browsers version
windows10/chrome63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/gkxvt7g9/](https://jsfiddle.net/gkxvt7g9/)

### Steps to reproduce
官网的NavMenu折叠示例
最外层加上<el-menu-item-group>分组
折叠后样式错误

### What is Expected?
RT

### What is actually happening?
RT

**Comment by baiyaaaaa** [comment]
Becaus when the menu collapse, menu-item require an icon to show in menu, however, the group item can not set icon in it. So the group is not support in outermost layer menu-item.
