### ISSUE TITLE
[Bug Report] border highlighting for the disabled radio button click

### ISSUE THREAD

**Issue by shanxichen** [ElemeFE/element#9017]
### Element UI version
2.0.9

### OS/Browsers version
win7/Chrome 58.0.3029.96 (64-bit)

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
(http://element.eleme.io/#/zh-CN/component/radio)
1, open the issue url.
2.click all the disabled radio button

### What is Expected?
No change for the disabled radio button click

### What is actually happening?
border highlighting for the disabled radio button click

**Comment by shanxichen** [comment]
I can't access jsfiddle.net, please try http://element.eleme.io/#/zh-CN/component/radio

**Comment by liril-net** [comment]
Disabled button should be focusable so that user will not miss it. So maybe it will be a good idea to overwrite its default highlight in your use case.
