### ISSUE TITLE
[Bug Report] In the case of more el-table columns, the left fixed column line will be covered by the scroll bar and the total line is disordered.

### ISSUE THREAD

**Issue by imf7** [ElemeFE/element#9019]
### Element UI version
2.0.9

### OS/Browsers version
win10；chrome63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/otbwuh59/1/](https://jsfiddle.net/otbwuh59/1/)

### Steps to reproduce
1、表格列比较多，出现横向滚动条
2、左侧有固定列
3、底部有合计行

以上三个行为不可缺少

### What is Expected?
1、合计行正常显示
2、滚动条不被遮挡

### What is actually happening?
1、合计行在固定列的单元格错位
2、固定列的合计行遮挡了滚动条

**Comment by Leopoldthecoder** [comment]
Duplicate of #5886

**Comment by imf7** [comment]
@Leopoldthecoder #9019被关闭了，但是问题并没有得到解决，Table在有固定列，并且横向出现滚动条，并且有合计行的时候就会出现合计信息上下错位，合计行固定列单元格也会遮挡滚动条，请看如下案例：https://jsfiddle.net/otbwuh59/3/   不知道是不是我使用不对，如果已经修正，能给出一个正确的案例引导开发么？

**Comment by Leopoldthecoder** [comment]
被关闭的原因是与 #5886。有进展会在 #5886 更新。

**Comment by imf7** [comment]
@Leopoldthecoder 明白了，非常感谢您的回复，如果能把合计行放在滚动条上面是不是就比较容易解决这类问题。辛苦官方团队了！
