### ISSUE TITLE
表单 el-input v-model 不一致bug

### ISSUE THREAD

**Issue by asmodai1985** [ElemeFE/element#902]
### ElementUI version
 1.0.0-rc.8 

### OS/Browers version
win10/Chrome 50 

### Vue version
2.0.3

### Reproduction Link
https://jsbin.com/halodof/edit?html,js,output

### Steps to reproduce
1、el-input 带有value + validator  + v-model
2、初始化后修改input

### What is Expected?
初始化时input 和vm中的值一致，以vm中的为准(抛弃初始值)
可以正常修改input的值

### What is actually happening?
发生锁死现象，初始化时就存在是输入框中的值和实际的vm示例中的值不一致的问题，这和vue2的设计是相违背的。

暂时只测试了el-input组件

**Comment by baiyaaaaa** [comment]
v-model实际上就是实用了:value="" + @input=""，为何还要自己再加一遍value?

**Comment by asmodai1985** [comment]
因为当前使用的还是偏传统的架构，vue作为类似组件调用。value是由后端组件自动填充的，算比较特殊的情况，我已经自己做了处理。但确实也算是个问题，只是优先级可以认为比较低，我疑虑是有其它隐患存在。
仅供参考
