### ISSUE TITLE
version 2.0.9 popover, tooltip directive can't be resolved.

### ISSUE THREAD

**Issue by china-fengguan** [ElemeFE/element#9023]
version 2.0.9 的tooltip,popover编译器不识别，报错[Vue warn]: Failed to resolve directive: popover
 
需要特殊配置吗？现在是
import 'element-ui/lib/theme-chalk/index.css'
import 'element-ui/lib/theme-chalk/display.css'

import ElementUI from 'element-ui'
Vue.use(ElementUI

**Comment by zpzxgcr** [comment]
楼主解决了吗

**Comment by china-fengguan** [comment]
把包清空以后重新安装就好了
