### ISSUE TITLE
[Bug Report] el-button button reuse problem, and the reused el-button click event has not been removed

### ISSUE THREAD

**Issue by magicalSam** [ElemeFE/element#9025]
### Element UI version
2.0.9

### OS/Browsers version
mac / chrome v60

### Vue version
2.2.3

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/137/](https://jsfiddle.net/mmx38qxw/137/)

### Steps to reproduce
1、按钮1,按钮2,按钮3绑定了clickBtn事件，按钮4没有绑定事件
2、点击按钮4，没有任何响应，正常。
3、点击按钮2 -> 显示alert弹窗 -> 点击确定 -> 显示按钮1
4、点击按钮1 -> 显示alert弹窗 -> 点击确定 -> 显示按钮2、按钮3、按钮4
5、点击按钮4，显示alert弹窗，不正常（因为按钮4是没有绑定事件的）。

### What is Expected?
期望在以上操作步骤完成后，点击按钮4，不做任何响应。

### What is actually happening?
在以上操作步骤完成后，点击按钮4，显示alert弹窗，不正常。
可能是el-button 按钮重用的时候，click事件没有被移除

**Comment by liril-net** [comment]
因为你没有加 `key`，所以 vue 会复用组件。
