### ISSUE TITLE
[Feature Request] Custom footer for multiple rows

### ISSUE THREAD

**Issue by mp3il** [ElemeFE/element#9033]
### Existing Component
Yes

### Component Name
Table

### Description
We weren't able to create a custom footer using the Table component 

neither the use of custom summary-method nor scope="append" helped.

the problem is that :
1. it's hard to add multiple rows - summary-method allow only 1 row
2. using append and custom layout make it hard to respect features such as fixed columns.

**Comment by liril-net** [comment]
Moved to product backlog.

**Comment by aoi-umi** [comment]
+1
