### ISSUE TITLE
[Bug Report] After the encapsulates the el-input component, it is not valid to setCurrentValue the el-input in the component

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#9034]
### Element UI version
2.0.8

### OS/Browsers version
windows 10/chrome 62.0.3202.94

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/1oqjojjx/1948/](https://jsfiddle.net/1oqjojjx/1948/)

### Steps to reproduce
封装el-input做一个两位小数的校验和自动返回校验后的值
例如：禁止字母输入，自动trim，和最多输入两位小数

### What is Expected?
```js
updateValue: function(value) {
      //把之前input的输入存入
      var preValue = this.$refs.input.value
      //验证精度为两位小数的正则
      var reg = /^(([1-9]{1}\d*)|([0]{1}))(\.(\d){0,2})?$/
      //对输入的值进行trim
      var formattedValue = value.trim()
      //不符合正则的，则返回之前的input值
      if (!reg.test(formattedValue)) {
        formattedValue = preValue
      }
      //把最后的值显示在el-input内(此处无法显示合规的值)
      this.$refs.input.setCurrentValue(formattedValue)
      //通过 input 事件带出数值(可以正确带出值，但el-input中的值无法实时变化)
      this.$emit('input', Number(formattedValue))
}
```

### What is actually happening?
input能带出正确的值，但是el-input中的输入无法作实时校验

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/1oqjojjx/1959/

**Comment by AprilXtt** [comment]
@Leopoldthecoder 不好意思，再问一个问题。
` <el-table :data="bill.detail" border>
    <el-table-column label="价格">
      <template slot-scope="scope">
        <el-form-item :prop="'detail.' + scope.$index + '.amount'"
                      :rules="{required: true, message: '', trigger: 'blur'}">
          <currency-input v-model="scope.row.amount"></currency-input>
        </el-form-item>
      </template>
    </el-table-column>
  </el-table>`
el-form-item的rules校验，对封装后的el-input组件是不是无效？
