### ISSUE TITLE
[Bug Report] steps step problem, loading data instability

### ISSUE THREAD

**Issue by bingzhimengwu** [ElemeFE/element#9039]
### Element UI version
2.0.7

### OS/Browsers version
chrome62.0.3202.94

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/138/](https://jsfiddle.net/mmx38qxw/138/)

### Steps to reproduce
实际是获取当前日期后选择当前周，现在直接定位到6月，点击月份自动展开该月下的周列表，并将active的值绑定到周列表中的第一个，现在的问题有两个。
1，在最开始渲染页面时，spet的顺序是选择月之前-周-选择月之后从0开始排列，但是在后面选择其他月份后，顺序变动为周在最后。
2，默认6月，显示正常。再多选几次其他月，最后选择1月的时候，发现1月的周显示缺少数据，不稳定的出现第1周，第4周，有时候只有第1周，没有2、3、4、5周。

### What is Expected?
选择月的时候，正常展开周数据

### What is actually happening?
实际是获取当前日期后选择当前周，现在直接定位到6月，点击月份自动展开该月下的周列表，并将active的值绑定到周列表中的第一个，现在的问题有两个。
1，在最开始渲染页面时，spet的顺序是选择月之前-周-选择月之后从0开始排列，但是在后面选择其他月份后，顺序变动为周在最后。
2，默认6月，显示正常。再多选几次其他月，最后选择1月的时候，发现1月的周显示缺少数据，不稳定的出现第1周，第4周，有时候只有第1周，没有2、3、4、5周。

**Comment by bingzhimengwu** [comment]
第2个问题是因为我给el-step绑定的key值重复，第一个问题还在想。

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/34460520-de65ab42-ee4b-11e7-9699-d8b603ab5ea0.png)

你的 demo 已经报错了，请准备一个能正常运行的 demo。另外，这个 issue 的描述和代码有些冗余，请精简一下，然后重新开一个 issue。
