### ISSUE TITLE
栅格系统改进建议

### ISSUE THREAD

**Issue by asmodai1985** [ElemeFE/element#904]
element使用的事24分栏，但就正常来说，24这个数字太大，不好把控，调整起来也繁复。
我当前自己扩展了以下el-row和el-col, 使用 5、5.5这种方式来控制col，不需要改动基础css,简单的使span、offset等属性x2取整展示。这样就回归到常规的12分栏里，又可以满足精细需求。

仅供常考，如果觉得无意义请直接关闭

**Comment by baiyaaaaa** [comment]
对中台或者后台系统来说，元素密度是相对比较高的，24分栏能更好地对布局进行控制。

**Comment by asmodai1985** [comment]
不反对24
<el -col :span2="11.5"></el-col>
等价使用 <el -col :span="23"></el-col>

**Comment by Shangri-GitHub** [comment]
现在有一个需求就是分成5份，24/5 = 4.8 。 :span="4.8"不识别小数不知道怎么处理
