### ISSUE TITLE
[Bug Report] Grouping table head style bug

### ISSUE THREAD

**Issue by chenyiqiao** [ElemeFE/element#9042]
### Element UI version
2.0.9

### OS/Browsers version
any

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/chen1qiao_/Lb3yLo2r/](https://jsfiddle.net/chen1qiao_/Lb3yLo2r/)

### Steps to reproduce
a normal table head after a grouping table head

### What is Expected?
the vertical line between `a normal table head **after** a grouping table head` should be complete.

### What is actually happening?
It's not

**Comment by liril-net** [comment]
I am sorry, but i can not reproduced this. Can you provide a screenshot for a better explanation?

**Comment by chenyiqiao** [comment]
![aj s spj3 cgxom mvnu8mg](https://user-images.githubusercontent.com/11814589/34402173-ff2fde38-ebda-11e7-9a29-71d1c426c549.png)   @liril-net

**Comment by liril-net** [comment]
Can you provide your os version and browser version?

**Comment by chenyiqiao** [comment]
Windows 7: latest chrome/ latest firefox
Mac: latest chrome/latest firefox
@liril-net
