### ISSUE TITLE
Select选择器加上multiple，设置size='small'无效

### ISSUE THREAD

**Issue by xiaowulaile** [ElemeFE/element#9045]
个人换了很多方式依然不太好解决这个问题，项目中整体需要size为small的布局，最终问题发现时因为设置了multiple之后，会把input顶开，希望能开放一个设置选中内容框的size设置，或者能自使用父级size的效果也可

**Comment by Leopoldthecoder** [comment]
你可以试试 `collapse-tags` 属性。

**Comment by xiaowulaile** [comment]
谢谢赐教，我试了一下能解决这个问题，但效果容易给人歧义，+1显示好像是显示的数据又加了一个似的，不过非常感谢了。




| |
吴正岗
|
|
邮箱：vip11531@163.com
|

签名由 网易邮箱大师 定制

在2017年12月28日 17:03，杨奕 写道：

你可以试试 collapse-tags 属性。
