### ISSUE TITLE
[Bug Report] Can't use the'this.$set'to update the: Data prop

### ISSUE THREAD

**Issue by kylin-z** [ElemeFE/element#9046]
### Element UI version
2.0.9

### OS/Browsers version
macOS/Chrome  63.0.3239.84

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/8n4Lnyac/2/](https://jsfiddle.net/8n4Lnyac/2/)

### Steps to reproduce
如`jsfiddle`中代码所示，在before-upload事件中使用`vue.set`去更新绑定在upload上的data 会更新失败，在network中查看请求的request payload 显示的依然是初次绑定的数据，而使用`=`去更新对象的属性则可以实现

### What is Expected?
使用`vue.set`或`this.$set`也能更新绑定在upload上的data

### What is actually happening?
使用`vue.set`或`this.$set`并不能能更新绑定在upload上的data

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/34406174-82252570-ebf2-11e7-81b5-661de0bdeaf0.png)

注意红框里的那句话。你需要这样写：https://jsfiddle.net/8n4Lnyac/3/
