### ISSUE TITLE
[Bug Report] Loading causes BUG to display in the 360 browser 9.1.0.362 version

### ISSUE THREAD

**Issue by mice33** [ElemeFE/element#9048]
### Element UI version
2.0.9

### OS/Browsers version
Win10 / 360 浏览器 9.1.0.362 / 内核 55.0.2883.87

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/139/](https://jsfiddle.net/mmx38qxw/139/)

### Steps to reproduce
在 jsfiddle 里不会被复现了，需要把代码放到本地。
初步测试 loading 模块碰上 el-steps 就会引起这个问题

### What is Expected?
正常显示

### What is actually happening?
会引起页面渲染异常

**Comment by mice33** [comment]
附带 Gif 效果图:[http://chuantu.biz/t6/188/1514443269x-1404764886.gif](http://chuantu.biz/t6/188/1514443269x-1404764886.gif)

**Comment by mice33** [comment]
有解决办法吗..

**Comment by QingWei-Li** [comment]
可否 demo 的仓库地址？

**Comment by furybean** [comment]
Maybe same issue as #8894.
You chould try again after fixed #8894.

**Comment by mice33** [comment]
@furybean use 'after-leave' same problem

**Comment by mice33** [comment]
@QingWei-Li https://gist.github.com/mice33/b98b040b52bc76d37c07ca6085fa61a5

**Comment by Leopoldthecoder** [comment]
@mice33 请确认这个问题在 2.1.0 版本中是否仍然存在。

**Comment by mice33** [comment]
@Leopoldthecoder 2.1.0 依然可以复现

**Comment by mice33** [comment]
@furybean @QingWei-Li @Leopoldthecoder 2.1.0 same problem

**Comment by mice33** [comment]
有解决办法吗

**Comment by furybean** [comment]
@mice33 请提供一个在线的可重现案例吧，可以使用 Github Pages.

**Comment by mice33** [comment]
@furybean 在线地址 https://mice33.github.io/
我测试了 360 版本 9.1.0.406 内核版本 55.0.2883.87 依旧可以复现

**Comment by mice33** [comment]
刚又发现使用微信 6.6.3.1260 版本，TBS 版本 043906，访问 https://mice33.github.io/ 也可复现此问题

**Comment by mice33** [comment]
@furybean 试试看

**Comment by emorlasar** [comment]
好像是flex的原因， 用float 就不会出现， 不知道怎么回事

**Comment by furybean** [comment]
@mice33 我做了个简单的测试，为 body 增加一个 position: relative ，然后取消这个样式，就会触发这个问题。

个人觉得你加一行样式就可以解决这个问题：

```CSS
body {
  position: relative;
}
```

**Comment by mice33** [comment]
3Q
