### ISSUE TITLE
[Bug Report] Select selection box disable style problem

### ISSUE THREAD

**Issue by zuopengcy** [ElemeFE/element#9050]
### Element UI version
2.0.9

### OS/Browsers version
Win10/Chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/byssh5qn/2/](https://jsfiddle.net/byssh5qn/2/)

### Steps to reproduce
1. 重写样式，设置select的height为26
2. 页面加载2秒后，设置select组件为disable状态

### What is Expected?
select选择框变为禁用状态，高度保持原状态

### What is actually happening?
select高度变为40px

**Comment by Leopoldthecoder** [comment]
目前只能通过 `!important` 来解决：https://jsfiddle.net/byssh5qn/3/ 。Element 这边如果要解决的话需要一个比较大的重构。
