### ISSUE TITLE
The [Bug Report] select component will appear the input input cursor when the Firefox browser clicks the drop-down selection.

### ISSUE THREAD

**Issue by blaze87** [ElemeFE/element#9051]
### Element UI version
2.0.9

### OS/Browsers version
select组件在Firefox浏览器 点击下拉选择的时候 会出现input输入光标

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
select组件在Firefox浏览器 点击下拉选择的时候 会出现input输入光标

### What is Expected?
select组件在Firefox浏览器 点击下拉选择的时候 会出现input输入光标

### What is actually happening?
select组件在Firefox浏览器 点击下拉选择的时候 会出现input输入光标

**Comment by Leopoldthecoder** [comment]
这是 FireFox 的原因：https://jsfiddle.net/6pnsyd6b/ ，`readonly` 的输入框也会显示光标。
