### ISSUE TITLE
The prepend Select mouse in the [Bug Report] Input moves into the style exception

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#9052]
### Element UI version
2.0.9

### OS/Browsers version
osx chrome 56

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/wfqororn/2/](https://jsfiddle.net/wfqororn/2/)

### Steps to reproduce
点击 Prepend 的 Select 
鼠标移入下拉选框
Select 左右出现两条蓝线

### What is Expected?
点击 Prepend 的 Select 
鼠标移入下拉选框
Select 左右不出现两条蓝线

### What is actually happening?
点击 Prepend 的 Select 
鼠标移入下拉选框
Select 左右出现两条蓝线

**Comment by Leopoldthecoder** [comment]
Fixed in #9089
