### ISSUE TITLE
[Feature Request] About NavMenu collapse attribute

### ISSUE THREAD

**Issue by githubSiYao** [ElemeFE/element#9057]
### Existing Component
Yes

### Component Name
NavMenu

### Description
When I use the navmenu component,how can I adjust the collapse speed?
Because the layout with nav menu lets me feel a little trapped.

**Comment by liril-net** [comment]
You can overwrite css about `.horizontal-collapse-transition`.Such as [https://jsfiddle.net/z5e7aqm2/](https://jsfiddle.net/z5e7aqm2/)
