### ISSUE TITLE
el-tabs @tab-click="handleClick"问题

### ISSUE THREAD

**Issue by chrislingxiao** [ElemeFE/element#906]
### ElementUI version
 2.0.0-rc.7

### OS/Browers version
macOS/Chrome 53 

### Vue version
 2.0.1

### What is actually happening?
el-tabs 的tab-click的回调，
`handleClick(tab) {
    console.log(tab);
    this.activeName = tab;
 },
`
为什么在MacOS下tab是VueComponet object, 在Windows下tab是string？

**Comment by baiyaaaaa** [comment]
先确保你两个操作系统下跑的element版本相同。rc.8开始已经将回调参数改成tab组件的实例

**Comment by chrislingxiao** [comment]
哦哦，原来新版本改了tab组件了。哦了，就是这个问题，谢谢了
