### ISSUE TITLE
[Feature Request] The CSS class named of "is-hidden" is easy to conflict with other CSS framework, like BULMA

### ISSUE THREAD

**Issue by mario-shang** [ElemeFE/element#9061]
### Existing Component
是

### Component Name
Table

### Description
The CSS class named of "is-hidden" is easy to conflict with other CSS framework, like BULMA, and it will make the fixed column rendering failed. May we have a more "EL-style" class name? Thank you.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
