### ISSUE TITLE
[Feature Request] span-method usage

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#9062]
### Existing Component
是

### Component Name
table

### Description
我想实现循环出三个表格，然后按着数据里每项数据的datas的长度来合并最后一列单元格，应该怎么做？（意思就是最后一列---数值3那一列应该是合并成一个单元格）（还有就是这个最后一列能动态取吗还是说只能写死4？？？）
链接在此，求助！！！
https://jsfiddle.net/ut2gu4mj/8/

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
