### ISSUE TITLE
[Bug Report] Tabs tag page component, when there is only one tab page, the current selected style is incorrect, and the bottom line is half displayed.

### ISSUE THREAD

**Issue by zangnan** [ElemeFE/element#9065]
### Element UI version
2.0.9

### OS/Browsers version
操作系统版本：win7 / 浏览器版本：Chrome 62.0.3202.94

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/zangnan/2tv2hb16/1/](https://jsfiddle.net/zangnan/2tv2hb16/1/)

### Steps to reproduce
Tabs 标签页组件，当只有一个tab页面的时候，代表当前选中的样式不正确，下方横线显示一半。
当有多个tab页面的时候，选中的tab页下方横线显示时正确的。

### What is Expected?
Tabs 标签页组件，当只有一个tab页面的时候，代表当前选中的样式不正确，下方横线显示完整。

### What is actually happening?
Tabs 标签页组件，当只有一个tab页面的时候，代表当前选中的样式不正确，下方横线显示完整。

**Comment by Leopoldthecoder** [comment]
Fixed in #9088
