### ISSUE TITLE
[Bug Report] circle progress bar component is inaccurate when percentage exceeds 90

### ISSUE THREAD

**Issue by 262060984** [ElemeFE/element#9067]
### Element UI version
2.0.9

### OS/Browsers version
win7

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/vkkqs616/](https://jsfiddle.net/vkkqs616/)

### Steps to reproduce
点击重现链接即可

### What is Expected?
percentage=97.5时应当还有空隙

### What is actually happening?
percentage=97.5时进度显示满了

**Comment by firesh** [comment]
It's not a bug. 
You can use `Math.floor(97.5)`, or try to add lagger `width` property.
https://jsfiddle.net/vkkqs616/1/
