### ISSUE TITLE
[Bug Report] should have a scrollbar when the elements of dropdown are too much to be displayed

### ISSUE THREAD

**Issue by athena0304** [ElemeFE/element#9068]
### Element UI version
2.0.9

### OS/Browsers version
chrome 63.0.3239.84

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/athena0304/wogago30/](https://jsfiddle.net/athena0304/wogago30/)

### Steps to reproduce
点击下拉菜单，选项太多，不能全部显示出来

### What is Expected?
当选项太多时，期望可以有滚动条，能正常显示和选择所有的条目

### What is actually happening?
部分条目无法显示

**Comment by Leopoldthecoder** [comment]
请自行添加 CSS：https://jsfiddle.net/wogago30/1/

**Comment by Esvalirion** [comment]
> 请自行添加 CSS：https://jsfiddle.net/wogago30/1/

in this case, the arrow disappeared
