### ISSUE TITLE
element-ui 中 无法单独引入TableColumn 这一组件，报以下错误:manager-debug.js:11749 Uncaught TypeError: plugin.apply is not a function

### ISSUE THREAD

**Issue by ouyangshan09** [ElemeFE/element#907]
element-ui 版本1.0.0-rc.8
vue版本：2.0.5

代码如下:
import Vue from 'vue';
import {Menu, MenuItem, Table, TableColumn} from 'element-ui';
import 'element-ui/lib/theme-default/index.css'

Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Table);
Vue.use(TableColumn);
....

在浏览器中Console选项中报出manager.js:11749 Uncaught TypeError: plugin.apply is not a function

唯独只有TableColumn 不能使用，去掉该组件，其他组件可以正常使用。

**Comment by blingz** [comment]
vue.common.js?e881:3219Uncaught TypeError: plugin.apply is not a function(…)

**Comment by blingz** [comment]
vue.common.js?e881:3219Uncaught TypeError: plugin.apply is not a function(…)
版本 vue2.0.5 + element-ui@1.0.0-rc.9

**Comment by QingWei-Li** [comment]
@blingz 已经修复，下个版本
