### ISSUE TITLE
[Bug Report] About the issue of "initial-index" property can not be set dynamically on "el-doalog" nested "el-carousel"

### ISSUE THREAD

**Issue by tank0321** [ElemeFE/element#9073]
### Element UI version
2.0.9

### OS/Browsers version
Windows 7旗舰版 / Chrome 版本 59.0.3071.115（正式版本） （32 位）

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/Lse8kkwf/](https://jsfiddle.net/Lse8kkwf/)

### Steps to reproduce
点击图片列表任意一张图片时，设置走马灯的“initial-index”为当前图片的index

### What is Expected?
点击图片列表任意一张图片时，设置走马灯的“initial-index”为当前图片的index

### What is actually happening?
点击图片列表任意一张图片时，设置走马灯的“initial-index”为当前图片的index后，实际的“initial-index”不是当前图片的index

**Comment by tank0321** [comment]
小弟才疏学浅，请大神们赐教

**Comment by tank0321** [comment]
原因是el-doalog的显示隐藏式用的是v-show，渲染dom后未删除dom，而el-carousel的initial-index属性是设置初始index，若要动态设置el-carousel的initial-index需要给el-carousel添加v-if重新渲染dom以达到重新设置初始el-carousel的index的目的

**Comment by tank0321** [comment]
https://jsfiddle.net/vwxcszzx/实现了期望效果

**Comment by tank0321** [comment]
原因是el-doalog的隐藏显示是用的v-show，未删除dom，而el-carousel的initial-index属性只是设置初始index。若要动态设置el-carousel的initial-index，需要给el-carousel添加v-if来重新渲染dom，以达到重新设置el-carousel的initial-index的目的。

**Comment by Leopoldthecoder** [comment]
是的。

**Comment by guohuihot** [comment]
initial-index 希望能做到sync
