### ISSUE TITLE
el-date-picker组件是不是有BUG，官方的例子拿下来直接跑且没有任何操作都会有警告出现

### ISSUE THREAD

**Issue by kuaipaowoniu** [ElemeFE/element#9075]
el-date-picker组件是不是有BUG，官方的例子拿下来直接跑且没有任何操作都会有警告出现：
1、 Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "type"
2、$listeners is readonly.
3、$attrs is readonly.

**Comment by kuaipaowoniu** [comment]
看错误1意思是修必了从父组件传过来的Prop 值

**Comment by yisayu** [comment]
hey bro !  have you sloved this bug?
