### ISSUE TITLE
拿不到自定义模板的scope，Property or method "scope" is not defined on the instance but referenced during render. 

### ISSUE THREAD

**Issue by agrass-GitHub** [ElemeFE/element#9080]
`<template slot-scope="scope">
                <span >
                     {{ scope.row[testpros[index]]}}
                </span>
            </template>
`
会报错Property or method "scope" is not defined on the instance but referenced during render。
我把一个table当作一个子组件来使用会报错，该如何解决？

**Comment by mocheaz** [comment]
@agrass-GitHub did you manage to solve this?
