### ISSUE TITLE
[Bug Report] The content is beyond the scope of the dialog

### ISSUE THREAD

**Issue by mstao** [ElemeFE/element#9081]
### Element UI version
2.0.9

### OS/Browsers version
Window10 / Chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/142/](https://jsfiddle.net/mmx38qxw/142/)

### Steps to reproduce
Click the reappear link

### What is Expected?
The content should not go beyond the scope of the dialog.

### What is actually happening?
The content is beyond the scope of the dialog.

**Comment by Leopoldthecoder** [comment]
This is not a bug: https://jsfiddle.net/dv4wL3xL/. You need to write some CSS: https://jsfiddle.net/mmx38qxw/143/

**Comment by mstao** [comment]
Thanks.
