### ISSUE TITLE
[Feature Request] add declaration or interface for locale

### ISSUE THREAD

**Issue by mia-san** [ElemeFE/element#9084]
### Existing Component
Yes

### Component Name
locale

### Description
compile
  `import locale from 'element-ui/lib/locale/lang/en';`
by typescript with --strict causes following error
```
ERROR in [at-loader] ./src/main/typescript/static/default/index.ts:1:20 
    TS7016: Could not find a declaration file for module 'element-ui/lib/locale/lang/en'. 'node_modules/element-ui/lib/locale/lang/en.js' implicitly has an 'any' type.
  Try `npm install @types/element-ui/lib/locale/lang/en` if it exists or add a new declaration (.d.ts) file containing `declare module 'element-ui/lib/locale/lang/en';
```
compile with --noImplicytAny or webpack with NormalModuleReplacementPlugin can workaround the issue, but not ideal.

Vue.js awares typescript and recommending compile options with --strict enabled.
(see "Recommended Configuration" in "TypeScript Support" page)

so, is it possible to have declaration file for locale?

also, having interface for locale(e.g. ElementLocale) and define locale as following
```
export default en: ElementLocale = {  ... }
export default de: ElementLocale = {  ... }
export default fr: ElementLocale = {  ... }
```
locale import could be slightly easier
`import {en, de, fr} from 'element-ui/locale';`

thanks.
//

**Comment by springxiege** [comment]
I have the same problem, too. but I can't resolve it. Do you have any better ideas?

**Comment by mia-san** [comment]
I have
```
    "strict": true,
    "noImplicitAny": false,
``` 
in my tsconfig.json for time being.
too bad typescript compiler doesn't allow us to override compile options per file basis...

of course, declaration file is ultimate solution.
I tried to create declaration file or something but no success...
//

**Comment by tahq69** [comment]
I have the same problem and `noImplicitAny` is not a best solution... I will try to create declaration module for this...

**Comment by sunshixiong789** [comment]
i want to konw hwo to git it

**Comment by Skytim** [comment]
I also want to know how to solve this problem

**Comment by subaru44k** [comment]
Adding `locale.d.ts` file in your project (for example, 'src/types' directory) may resolve the problem.
Content is following.
```
declare module 'element-ui/lib/locale/lang/en' {
}
```

**Comment by Skytim** [comment]
I think @subaru44k  methods is wording around to me.
Add locale.d.ts
![image](https://user-images.githubusercontent.com/7261694/42485554-a95e9b82-842a-11e8-8654-ac8d394b1ab6.png)
In main.ts
![image](https://user-images.githubusercontent.com/7261694/42485525-871a477e-842a-11e8-9228-fb730f869202.png)

**Comment by douglasg14b** [comment]
using the `locale.d.ts` brings up a new error 

>"Module '\"element-ui/lib/locale/lang/en\"' has no default export."

**Comment by johndcarmichael** [comment]
Same problem here. There is not a type file for the locales by the looks of it.
