### ISSUE TITLE
 current-node-key is not available any more in 2.0

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#9091]
### Element UI version
2.0.8

### OS/Browsers version
all

### Vue version
2.5.3

### Reproduction Link
no

### Steps to reproduce
1.  current-node-key is not available any more in tree, is there a alternative API for that in element 2.0?
2.  if not, I should use another component?

**Comment by Leopoldthecoder** [comment]
You can use the `setCurrentKey` method when you need to update the highlight node programmatically.
