### ISSUE TITLE
[Bug Report] NavMenu navigation menu component default-active does not take effect

### ISSUE THREAD

**Issue by povs2012** [ElemeFE/element#9092]
### Element UI version
2.0.10

### OS/Browsers version
win10/Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mqdnsvkh/](https://jsfiddle.net/mqdnsvkh/)

### Steps to reproduce
1、菜单项和当前激活菜单都是异步加载
2、菜单项在当前激活菜单之后返回
3、当前激活菜单的设置不生效
    watch: {
      defaultActive(value) {
        const item = this.items[value];
        if (item) {
          this.activeIndex = item.index;
          this.initOpenedMenu();
        } else {
          this.activeIndex = '';
        }
      },
应该是因为items在为空的时候又设置了一次defaultActive，而此时item不存在，所以将activeIndex 设为了空

### What is Expected?
当前激活菜单为所设置的菜单

### What is actually happening?
当前激活菜单的设置不生效

**Comment by Redtwodog** [comment]
em,this bug is also be in the version 1.4.12。I hope the it will be fixed in the feature... 。

**Comment by Leopoldthecoder** [comment]
@Redtwodog 1.x version is no longer maintained, so there'll be no fix coming to it.
