### ISSUE TITLE
有脚手架么 想要使用的话是直接改这个项目么？

### ISSUE THREAD

**Issue by freeyiyi1993** [ElemeFE/element#91]
rt

**Comment by QingWei-Li** [comment]
请看完规范再来提 issue https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md#issue-规范

使用上的问题或者建议请到 Gitter 上提问，issue 只是用来提 bug 和 feature，不符合的 issue 直接关掉。

我还是回答一下吧，会有。
