### ISSUE TITLE
$listeners is readonly.

### ISSUE THREAD

**Issue by ChenArno** [ElemeFE/element#9103]
Element UI version

2.0.10
OS/Browsers version

mac/chrome
Vue version

2.5.13
Reproduction Link

Steps to reproduce

开发环境，时间控件点击某天时调用时，控制台会报错：“$attrs is readonly 和 $listeners is readonly”；
What is Expected?
What is actually happening?

**Comment by ChenArno** [comment]
[QQ20180103-101238-HD.mp4.zip](https://github.com/ElemeFE/element/files/1599258/QQ20180103-101238-HD.mp4.zip)

**Comment by caolonggang** [comment]
webpack.renderer.config.js
let whiteListedModules = ['vue','element-ui']
