### ISSUE TITLE
[Bug Report] $listeners is readonly.

### ISSUE THREAD

**Issue by ChenArno** [ElemeFE/element#9104]
### Element UI version
2.0.10

### OS/Browsers version
 Google Chrome 版本 63.0.3239.84（正式版本） （64 位）

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element/issues/9103](https://github.com/ElemeFE/element/issues/9103)

### Steps to reproduce
开发环境，时间控件点击某天时调用时，控制台会报错：“$attrs is readonly 和 $listeners is readonly”；

### What is Expected?
不报错

### What is actually happening?
报错了

[QQ20180103-101238-HD.mp4.zip](https://github.com/ElemeFE/element/files/1599261/QQ20180103-101238-HD.mp4.zip)

**Comment by ChenArno** [comment]
https://user-images.githubusercontent.com/22111171/34507404-8c6232da-f070-11e7-98af-2d1da76d8aba.gif

**Comment by Leopoldthecoder** [comment]
综合[这里](https://github.com/vuejs/vue/issues/6698)、[这里](https://forum.vuejs.org/t/vue-warn-attrs-is-readonly/18053)和[这里](https://segmentfault.com/q/1010000010759119)，基本上是因为引用了不同的 vue 导致。
截图只能说明这个问题存在，但是并不能帮助我们定位问题。请简化你的项目并上传至 GitHub。

**Comment by ChenArno** [comment]
谢谢，我看了你的综合，确实是autodll-webpack-plugin引起的，我把element-ui剔除压缩行列，就不会出现这个问题了
