### ISSUE TITLE
tree-当前选中

### ISSUE THREAD

**Issue by ayiaq1** [ElemeFE/element#9111]
`this.treeData = response.data.data.data;
            this.treeNode = this.treeData[0][this.treeProps.id];
            this.$refs.tree.setCurrentKey(this.treeNode);
            setTimeout(() => {
              console.log('get key=>', this.$refs.tree.getCurrentKey());
            }, 500);`
tree设置默认选中无效，获取选中值也失败，在jsfiddle里面 用 this.$refs.tree.setCurrentKey([this.treeNode]);   改为数组也不行

https://jsfiddle.net/api/post/library/pure/
在线测试，当前选中

**Comment by curryhh** [comment]
@ayiaq1 这个问题有没有解决？怎么解决的我也遇到了

**Comment by ayiaq1** [comment]
增加参数:currentKey
<el-tree :current-node-key="currentKey"

      setCurrentKey() {
      this.currentKey=4;
        this.$refs.tree.setCurrentKey(4);
      }
demo:
https://jsfiddle.net/f6ptq19y/1/
