### ISSUE TITLE
[Bug Report] The TAB page contains a set of tabs

### ISSUE THREAD

**Issue by iTaster** [ElemeFE/element#9112]
### Element UI version
2.0.10

### OS/Browsers version
windows 10/chrome 63.0.3239.108

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/147/](https://jsfiddle.net/mmx38qxw/147/)

### Steps to reproduce
在一个页面里，如果使用标签页里面嵌套标签页，第二个标签页的tab-position部分失效！

### What is Expected?
第二个tabs属性tab-position不会受到父级第一个tab-position的影响

### What is actually happening?
第二个tabs属性tab-position会跟随第一个（仅在top/bottom）时失效

**Comment by iTaster** [comment]
我的临时解决方法：
.el-tabs--border-card > .el-tabs__header { width: 100%; }
.el-tabs--border-card .el-tabs__nav { display: -webkit-box; display: -ms-flexbox; display: flex; }

正确的顺序应该是：
.el-tabs--top.el-tabs--border-card > .el-tabs__header { width: 100%; }
.el-tabs--top.el-tabs--border-card .el-tabs__nav { display: -webkit-box; display: -ms-flexbox; display: flex; }

现在怀疑自己能解决的bug要不要撤回。

**Comment by Leopoldthecoder** [comment]
Fixed in #9159
