### ISSUE TITLE
How to reset the location of the select component, as follows

### ISSUE THREAD

**Issue by FolinSun** [ElemeFE/element#9113]
### Element UI version
2.0.10

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/2um0h71h/](https://jsfiddle.net/2um0h71h/)

### Steps to reproduce
需求如下：
项目中select使用collapse-tags，初始隐藏已选条件demo，change后把结果追加上最上方。这时候怎么给select重置位置。我看官方API并没有接口暴露出来。我看源码中过滤掉了collapse-tags
resetInputHeight() {
    if (this.collapseTags) return;
},

### What is Expected?
是否有其他方法可以调用resetInputHeight方法来重置select的位置

### What is actually happening?
目前项目中我只能把源码里面的这一步判断给注释掉来开发项目。不知是否有其他更好的解决方法

**Comment by Leopoldthecoder** [comment]
`resetInputHeight` 并不是用来更新下拉菜单位置的。你需要的是 `updatePopper`：https://jsfiddle.net/2um0h71h/1/
