### ISSUE TITLE
[Bug Report] InputNumber counter enters bug

### ISSUE THREAD

**Issue by nongshuqiner** [ElemeFE/element#9116]
### Element UI version
2.0.10

### OS/Browsers version
arch linux/chrome 62.0.3202.89

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/fLhn5rh2/](https://jsfiddle.net/fLhn5rh2/)

### Steps to reproduce
输入 0.01 等0.0开头的数字时会重归于0，输入小数位: .0 开头，4.01会重归于4（快速输入不会出现）

### What is Expected?
期待可以无障碍输入 .0 开头的小数位数值

### What is actually happening?
输入 0.01 等0.0开头的数字时会重归于0，输入小数位: .0 开头，4.01会重归于4（快速输入不会出现）

**Comment by wacky6** [comment]
https://jsfiddle.net/ax63mxkz/

**Comment by wacky6** [comment]
@Leopoldthecoder 
为什么输入是在input事件而不是change解析的？

**Comment by wacky6** [comment]
Patch: https://github.com/wacky6/element/commit/3ea811165e57ac5748b841eec0a52aaaa59fb352
Demo: https://jsfiddle.net/p0efwf9v/

**Comment by Leopoldthecoder** [comment]
@wacky 对的，应该是用 change。你提 PR 还是我这边改？

**Comment by wacky6** [comment]
我等会pr吧

**Comment by JingYihhh** [comment]
InputNumber可以限制整型吗？输入遇到小数点自动截取小数点前的整数

**Comment by wacky6** [comment]
在change里自己处理一下吧
