### ISSUE TITLE
rc.9 select 组件 change 事件触发时机与前版本有出入

### ISSUE THREAD

**Issue by jin5354** [ElemeFE/element#912]
### ElementUI version
1.0.0-rc.9

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.3

### Reproduction Link
https://jsfiddle.net/bhvqntcq/

### Steps to reproduce
rc.9 和 rc.8 行为不一样

### What is Expected?
rc.8 会触发一次 change 事件，rc.9 不触发了。

### What is actually happening?
这是 bug 还是 feature 啊，不兼容性更新可否在 release 文档里写全一点。

**Comment by Leopoldthecoder** [comment]
抱歉，这个我也没发现。不过现在的行为其实是和其他组件的 `change` 事件是一致的，因为在父组件的 `created` 钩子里改变 `v-model` 的绑定值的话，子组件是 watch 不到 `value` 的变化的：https://jsfiddle.net/leopoldthecuber/621bac80/ 。之前的实现可能绕过了这一点。

**Comment by jin5354** [comment]
@Leopoldthecoder 之前使用时我一般在 `created` 时为 `v-model` 赋个默认值，同时触发 `change` 事件做一些拉取数据/绘图/制表的初次操作；如果确定以后的行为都这样了，那我就改下逻辑，手动去触发那些初始化操作了。

**Comment by Leopoldthecoder** [comment]
是这样。这样的话感觉把赋默认值的操作移到 `mounted` 里可行。
