### ISSUE TITLE
[Bug Report] Dropdown and Select click lag

### ISSUE THREAD

**Issue by ingria** [ElemeFE/element#9120]
### Element UI version
2.0.10

### OS/Browsers version
Chrome, Firefox on Linux, iOS, Android

### Vue version
2.5.13

### Reproduction Link
http://element.eleme.io/#/en-US/component/select

### Steps to reproduce
Click on the dropdown or select. It will show the content not instantly, but after the significant delay.

| This lib behaviour |
| -----------|
| ![2018-01-03_18-18-00](https://user-images.githubusercontent.com/2178368/34526377-5d10673e-f0b3-11e7-99c9-6ad4e47094f8.gif) |

There's about 0.8 second lag between the click and the action.

### What is Expected?
Dropdown or Select to be expanded instantly.

| Example from another framework |
| -------------------------------- 
| ![2018-01-03_18-19-16](https://user-images.githubusercontent.com/2178368/34526473-9ce4f258-f0b3-11e7-9d1d-026259ef8dd4.gif) |

There's about 0.05 second delay between the click and the action.

### What is actually happening?
It lags 🤷‍♂️

**Comment by Leopoldthecoder** [comment]
Transition delay is removed in https://github.com/ElemeFE/element/pull/9158 . For Dropdown, you'll also need to set its `show-timeout` and `hide-timeout` to `0`.
