### ISSUE TITLE
[Bug Report] table using toggleRowSelection method cannot check defaults

### ISSUE THREAD

**Issue by hzm07** [ElemeFE/element#9127]
### Element UI version
2.0.7

### OS/Browsers version
Google

### Vue version
2.5.9

### Reproduction Link
[https://github.com/hzm07/elementTests/blob/master/element2.0.7/index_2.html](https://github.com/hzm07/elementTests/blob/master/element2.0.7/index_2.html)

### Steps to reproduce
First, open  the dialog and select one or more data，and then click the button to close this dialog.
Open the dialog again, I using toggleRowSelection method to check last selected data.But it didn't turn out that way.

### What is Expected?
I look forward to setting the  last selected data when opening the dialog.

### What is actually happening?
It didn't check last selected data.

**Comment by Leopoldthecoder** [comment]
https://github.com/hzm07/elementTests/pull/1 becase `{} !== {}`.
