### ISSUE TITLE
rc.9 pagination 组件 current-change 事件触发时机与前版本有出入

### ISSUE THREAD

**Issue by jin5354** [ElemeFE/element#913]
### ElementUI version
1.0.0-rc.9

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.3

### Reproduction Link
https://jsfiddle.net/fu6qog9f/

### Steps to reproduce
rc.9 和 rc.8 行为不一样

### What is Expected? & What is actually happening?
rc.9 页面加载时就直接会触发一次 current-change 事件，且值为 0，rc.8 版本及以前没有这种行为。
一般来说 current-change 事件中都是做记录当前页数，并拉取新数据的操作，将页数改成 0 这种行为妥妥的引起报错。

**Comment by furybean** [comment]
这个地方其实做了一个优化，在不设置 total 的时候依然可以使用。

改了改例子，这么改是可以正常跑的：https://jsfiddle.net/furybean/bky7v5p5/1/

**Comment by jin5354** [comment]
@furybean 原来是设置默认 total 带来的影响，改成 null 这个成本还可以接受；刚数了下项目中大概有 10+ 处分页组件了，全都行为错误了，差点我就滚回 rc.8 了。囧

**Comment by furybean** [comment]
current-change 在 rc.9 版本里面被改成了最小为 1，我试试看你这里的逻辑。

**Comment by furybean** [comment]
会出现 0 的情况已经在 #943 里修复了。

**Comment by jin5354** [comment]
@furybean  Good job！
