### ISSUE TITLE
[Bug Report] DatePicker doesn't change value when using computed method

### ISSUE THREAD

**Issue by wojtekroslan** [ElemeFE/element#9132]
### Element UI version
2.0.10

### OS/Browsers version
Windows 10 / Chrome, Firefox, Edge

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/szn97Lao/](https://jsfiddle.net/szn97Lao/)

### Steps to reproduce
Change the date with the DatePicker. New value doesn't show up.

### What is Expected?
DatePicker should behave exactly the same like with the data() method.

### What is actually happening?
It looks like it doesn't refresh the value in the UI, but it changes in the model as expected.

**Comment by wacky6** [comment]
Computed properties should not be mutated

**Comment by wojtekroslan** [comment]
Ok, thanks. Instead of using computed method, I think I should use created method to retrive data from backend and set in my data property.

https://jsfiddle.net/szn97Lao/1/
