### ISSUE TITLE
[Bug Report] how to add timezone for element datepicker component?

### ISSUE THREAD

**Issue by ybhuxiao** [ElemeFE/element#9133]
### Element UI version
2.0.10

### OS/Browsers version
windows

### Vue version
2.5.13

### What is Expected?
i want to add a dropdown component to select timezone, because some of my customer want statistic reports on the timezone they want to. 
![image](https://user-images.githubusercontent.com/17189297/34565543-3304a066-f196-11e7-8d67-439d1b891456.png)

i have post a same thread at segmentfault but get no anwser until now.
https://segmentfault.com/q/1010000012705106

### What is actually happening?
now i get the chinese timeformat default
![image](https://user-images.githubusercontent.com/17189297/34565770-1591efce-f197-11e7-9a80-3a1543201b34.png)

**Comment by wacky6** [comment]
Not supported. You need to do your own time zone stuff

**Comment by ybhuxiao** [comment]
thanks,i will use this code as temporary solution, and next try to add a paramter for the date picker component.
`
d=new Date();
localTime = d.getTime(); 
localOffset=d.getTimezoneOffset()*60000; 
utc = localTime + localOffset;
offset =10;
hawaii = utc + (3600000*offset); 
nd = new Date(hawaii); 
document.writeln("Hawaii time is " + nd.toLocaleString()); 
`

**Comment by wacky6** [comment]
Note: there is no plan to implement features related to timezone in near feature

1. Js date is never designed to handle timezone directly.
2. Simple solutions almost always have edge cases (for example, if the user lives in a country that use day light saving time)
3. For security reasons, timezone should be computed at server side (never trust user input). Use UTC/timestamp for communication

As a guideline, we encourage to use momentjs and moment-tz to deal with timezone before passing to / receiving from components.
As always, you can wrap or build your own custom component.
