### ISSUE TITLE
[Bug Report] Firefox table component sort button style misplaced

### ISSUE THREAD

**Issue by longFeiLi** [ElemeFE/element#9134]
### Element UI version
2.0.10

### OS/Browsers version
57.0.4 (64)

### Vue version
2.5.8

### Reproduction Link
https://jsfiddle.net/longfei0925/tvfbm5o2/

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/table

### What is Expected?
Display correctly

### What is actually happening?
Misplaced style

  
![image](https://user-images.githubusercontent.com/10267141/34592452-1afa2c84-f1ff-11e7-84f6-b25524337895.png)

**Comment by blank-x** [comment]
display:-moz-inline-stack

**Comment by Leopoldthecoder** [comment]
Fixed in #9156
