### ISSUE TITLE
[Bug Report] el-date-picker width is not adaptive, line breaks or block behind the content column layout

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#9135]
### Element UI version
2.0.10

### OS/Browsers version
windows 10/chrome 62.0.3202.94

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/0hy45aba/2/](https://jsfiddle.net/0hy45aba/2/)

### Steps to reproduce
https://jsfiddle.net/0hy45aba/2/

### What is Expected?
当页面宽度变小时，el-date-picker的宽度可以像select组件一样自适应调节。
或者 有没有避免换行和出现遮挡的方法

### What is actually happening?
el-date-picker的宽度一直固定为350px，屏幕宽度较小时，会出现换行或者布局重叠。

**Comment by AprilXtt** [comment]
如果修改宽度的话，
.el-date-editor--daterange.el-input__inner {
  width: 300px;
}
选择日期后，删除日期的close-icon的位置会换行。

**Comment by Leopoldthecoder** [comment]
为了显示完整的日期，DatePicker 的宽度肯定不能过窄。这个需要在页面的组织层面处理，给 DatePicker 留出足够的宽度。

**Comment by AprilXtt** [comment]
@Leopoldthecoder 那能不能规定最小宽度为350px，可以适当变长呢。
这样可以减小与后面el-col的空白间隔。
https://jsfiddle.net/0hy45aba/4/
