### ISSUE TITLE
[Bug Report] In the Table component, show-overflow-tooltip can not be used when

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/element#9136]
### Element UI version
2.0.10

### OS/Browsers version
mac os 10.12 / chrome 56

### Vue version
2.5.13

### Reproduction Link
[http://jsfiddle.net/rossroma/k5ejp59y/10/](http://jsfiddle.net/rossroma/k5ejp59y/10/)

### Steps to reproduce
1. 开启tableColumn的show-overflow-tooltip属性；
2. 单元格内放一张超过单元格大小的图片；
3. 鼠标移到该单元格上，会显示一个空的 tooltip，而且样式有些错位

### What is Expected?
1. 当内容为图片时，关闭tooltip
2. 或者显示images的alt属性

### What is actually happening?
显示一个空的 tooltip，而且样式有些错位

**Comment by QingWei-Li** [comment]
只支持显示过长的**文本**而非 HTML
