### ISSUE TITLE
[Bug Report] Table's setCurrentRow doestn't work as expect

### ISSUE THREAD

**Issue by goforward01** [ElemeFE/element#9137]
### Element UI version
2.0.9

### OS/Browsers version
Windows 10/Chrome(61.0.3163.100 32位)

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/goforward01/v0o226Lo/2/](https://jsfiddle.net/goforward01/v0o226Lo/2/)

### Steps to reproduce
1, click the **change** button to highlight the row of ('任务3'), the third row.

2, click the **delete** button to delete the first item of tableData.

### What is Expected?
The current highlight row should be the same as before if the row is still exist, and can change the current row by click as normal.

### What is actually happening?
After delete the item of tableData, the current highlight row is wrong and can't change the current row by click correctly.

**Comment by Leopoldthecoder** [comment]
You need to add `row-key` in this case: https://jsfiddle.net/v0o226Lo/3/

**Comment by goforward01** [comment]
@Leopoldthecoder That works! Thanks
