### ISSUE TITLE
[Bug Report] IE 11 <el-main> height cannot be adaptive

### ISSUE THREAD

**Issue by BenceSan** [ElemeFE/element#9139]
### Element UI version
2.0.10

### OS/Browsers version
win10  IE 11 

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/bmy2L8px/5/](https://jsfiddle.net/bmy2L8px/5/)

### Steps to reproduce
Element官网 >> 组件 >>  Container 布局容器 >> 常见页面布局 (注意: IE 11 可重现)

### What is Expected?
<el-main> 应该自适应高度

### What is actually happening?
<el-main> 在IE 11 未能自适应高度

**Comment by Leopoldthecoder** [comment]
Duplicate of #9042

**Comment by Leopoldthecoder** [comment]
布局组件采用了 flex，IE 11 对 flex 的支持并不到位：https://caniuse.com/#search=flex。
