### ISSUE TITLE
The [Bug Report] replaces the data structure of the multilevel header, and the header shows a big problem

### ISSUE THREAD

**Issue by dingyiming** [ElemeFE/element#9143]
### Element UI version
2.0.10

### OS/Browsers version
windows 7 / chrome 62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/dmfokv7g/](https://jsfiddle.net/dmfokv7g/)

### Steps to reproduce
打开 https://jsfiddle.net/dmfokv7g/， 多次点击切换结构，只是简单的替换表头数据结构，表结构突然就不行了，很是 莫名其妙，求救！

### What is Expected?
能正常切换表头结构，提供自由化，平铺的多级表头数据结构支持会好很多，这种深度的表头，很难用

### What is actually happening?
表头炸裂，开发背锅了

**Comment by Leopoldthecoder** [comment]
涉及到动态显示隐藏的，建议给 el-table-column 加上 key：https://jsfiddle.net/dmfokv7g/1/ 。例子中的 `Math.random()` 只是为了说明效果，实际使用任何唯一性的值都行。
