### ISSUE TITLE
[Bug Report] Method inside Expandable row run 3 times

### ISSUE THREAD

**Issue by choirool** [ElemeFE/element#9144]
### Element UI version
2.0.10

### OS/Browsers version
Latest mozilla ubuntu 16.04

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/oLkdsnno/](https://jsfiddle.net/oLkdsnno/)

### Steps to reproduce
Opening Reproduction Link then try expand row and see console.

### What is Expected?
Console run 3 times

### What is actually happening?
Run 1 time

**Comment by Leopoldthecoder** [comment]
Duplicate of #6276
