### ISSUE TITLE
[Bug Report] When the page component is inputted, the first return can be transferred to the home page normally, but it can not turn back again.

### ISSUE THREAD

**Issue by SmallBlanckPig** [ElemeFE/element#9148]
### Element UI version
2.0.10

### OS/Browsers version
windows 10/chrome 62.0.3202.94

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/t0mhb8f6/](https://jsfiddle.net/t0mhb8f6/)

### Steps to reproduce
http://element.eleme.io/#/zh-CN/component/pagination

1、官网分页组件，输入非数字字符入1-e，正常跳转至第一页
2、再次在该输入框输入如12-1，无反应，无法正常调整至正确页面
3、希望限制所有字母都不允许输入，现在是可输入e，其他字母不允许

### What is Expected?
正常跳转，非数字不允许输入

### What is actually happening?
不能正常跳转，可输入非字符

**Comment by SmallBlanckPig** [comment]
对于问题1，分析发现，输入非法时， internalCurrentPage一直为1，对internalCurrentPagede 的观察方法未执行，导致输入框一直未执行，进行如下修改即可
![image](https://user-images.githubusercontent.com/6890343/34638034-71564fe0-f2fe-11e7-99f0-c2e037bd5a3c.png)

**Comment by SmallBlanckPig** [comment]
问题2 解决 增加onKeypress事件，限制e的输入

**Comment by Leopoldthecoder** [comment]
对于 `type="number"` 的输入框，`-`、`e` 和 `.` 都是合法输入。
