### ISSUE TITLE
The [Bug Report] selcet component rolls the page in the drop-down display state, and the drop-down panel is too high at the index level to cover the other content

### ISSUE THREAD

**Issue by quyapeng** [ElemeFE/element#9150]
### Element UI version
2.0.8

### OS/Browsers version
Google Chrome版本 62.0.3202.94（正式版本） （64 位）

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/rx0oteh3/5/](https://jsfiddle.net/rx0oteh3/5/)

### Steps to reproduce
1.点击组件，下拉面板显示
2.滚动页面

### What is Expected?
滚动页面之后，下拉面板没有消失。滚动到顶部，下拉面板应该被header遮住

### What is actually happening?
滚动页面之后，下拉面板没有消失。滚动到顶部，下拉面板在header之上 ，header被下拉面板遮住了。

**Comment by Leopoldthecoder** [comment]
`.myhead` 的 `z-index` 给大点就行：https://jsfiddle.net/rx0oteh3/7/

**Comment by quyapeng** [comment]
如果是在对话框里面呢，感觉没有从根本上解决这个问题，毕竟对话框的z-index是动态的吧
