### ISSUE TITLE
[Bug Report]el-select's change event won't been emit after model has been changed

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#9151]
### Element UI version
2.0.10

### OS/Browsers version
all

### Vue version
2.5.4

### Reproduction Link
https://jsfiddle.net/64wjqbLc/

### Steps to reproduce
1. select any option in the el-select component
2. an alert will be shown
3. click the el-button
4. the value of the model will be changed to "Option5", but no alert will be shown

### What is Expected?
alert should be shown because model has been changed

**Comment by wacky6** [comment]
This is intentional in 2.0, please check changelog

**Comment by uwf-doc** [comment]
This breaks a ton of my code! I was programmatically setting a field in my code (e.g. this.values.selectId = 123), which would then set that value in the el-select and then trigger the @change event--which in turn would make an XHR call to fetch data and programmatically set some other el-selects.

What is the best solution here? Find every instance in my code where I was programmatically setting this.values and then manually call the selectOnChange method for each of them? I don't understand why something so useful was intentionally removed in v2.0.

**Comment by wacky6** [comment]
Use watch, or input event. This change is to align with native input/select's behacior

**Comment by uwf-doc** [comment]
I hate to set a watcher for every field on my form, but I guess that'll work (I don't think input will work since I'm talking about setting the values programmatically). Thanks for the quick response, @wacky6.
