### ISSUE TITLE
自定义模板Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by GivenchyLiu** [ElemeFE/element#9153]
在使用el-table组件展开功能时，对展开的模板里面报错说是Cannot read property 'row' of undefined，把官网给的样例代码完全复制过去也还是报这个错误
vue版本：Vue.js v2.5.13
element-ui版本：2.0.10

**Comment by milu2003** [comment]
问题怎么解决的？我也遇到这个问题了，子组件里面有el-table-column的时候就出现这个

**Comment by milu2003** [comment]
是vue版本太低的缘故，总之，一切库都要更新，版本匹配才行
