### ISSUE TITLE
[Feature Request] Select: should keep focus, ensure user tabs to the next input field

### ISSUE THREAD

**Issue by gralance** [ElemeFE/element#9154]
### Existing Component
Yes

### Component Name
select

### Description
The el-select component lost focus when user press Enter/Esc or select some items.

Expectation: The el-select should remain the focus no matter what user select or not select an item.

71ad23226aa2967691c403fba2e95013a9768e13

**Comment by Leopoldthecoder** [comment]
This feature request makes sense but #9155 doesn't seem to be a good implementation (it didn't pass tests actually). Closing the PR, and we'll think about this feature later.

**Comment by Leopoldthecoder** [comment]
#9456 has a more common description regarding this feature, so we'll update there.
