### ISSUE TITLE
The.Trim of [Bug Report] el-input is invalid

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#9157]
### Element UI version
2.0.10

### OS/Browsers version
windows 10/chrome 62.0.3202.94

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/1oqjojjx/1972/](https://jsfiddle.net/1oqjojjx/1972/)

### Steps to reproduce
1、在el-input中输入“      1”
2、焦点移开

### What is Expected?
焦点移开时，el-input中的输入内容由“      1”变成“1”

### What is actually happening?
虽然el-input中的.trim确实对结果作了trim，但并没有将trim后的值正确带回给el-input。

**Comment by Leopoldthecoder** [comment]
![untitled](https://user-images.githubusercontent.com/10095631/34646174-f30c1f5e-f39b-11e7-8903-4af5c814f7a2.gif)

无法重现。

**Comment by AprilXtt** [comment]
![el-input](https://user-images.githubusercontent.com/30852982/34646260-5c7e4550-f39e-11e7-8c53-4f9afb65fe85.PNG)

@Leopoldthecoder 我这边没有trim的效果啊

**Comment by Leopoldthecoder** [comment]
你的例子并没有加 `.trim`

**Comment by AprilXtt** [comment]
@Leopoldthecoder 是的，不好意思，link已修正。
https://jsfiddle.net/1oqjojjx/1974/
但是以下两种情况还是不会trim。
1. 直接将“   1”拷贝至el-input中
2. 输入“1”之后，在首位或者末尾输入空格
