### ISSUE TITLE
[Upload] 希望提供已上传文件列表

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#916]
## 建议
上传组件可否提供属性来设置已上传文件目录，并且对每个文件配置访问路径

## 场景
在表单编辑完成之后，保存，再次进行编辑，这时就需要从服务器拉取表单的所有数据，包括已上传的文件的列表，这时虽然可以另外提供一个列表展示已上传的文件，再用一个输入框显示新上传的文件，但是这种展现方式总感觉不太好

**Comment by furybean** [comment]
看不太懂，ping @baiyaaaaa

**Comment by masterzhang** [comment]
@furybean 
![image](https://cloud.githubusercontent.com/assets/9530813/20208432/15ab2d44-a829-11e6-801c-565fde2ca374.png)

我已经在表单A中上传到了一个文件到服务器保存并退出了，然后我需要修改表单A的数据，这时就得去服务器请求表单A的所有数据，做默认填充供用户修改。上传组件好像没有提供参数用于设置已经上传的文件列表
