### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by somnusnrlq** [ElemeFE/element#9162]
### Element UI version
2.0.10

### OS/Browsers version
win10 chrome  62.0.3202.75

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/TokyYX/t0ppw19k/](https://jsfiddle.net/TokyYX/t0ppw19k/)

### Steps to reproduce
表头行添加了class样式无效果

### What is Expected?
表头行添加了class样式有效果

### What is actually happening?
表头行添加了class样式无效果

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/t0ppw19k/1/
