### ISSUE TITLE
The problem of using echarts in [Bug Report] tabs components

### ISSUE THREAD

**Issue by DaoqiuDong** [ElemeFE/element#9163]
### Element UI version
1.3.7

### OS/Browsers version
chrome版本 62.0.3202.62

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/8hhshr0b/](https://jsfiddle.net/8hhshr0b/)

### Steps to reproduce
在tabs组件中使用echarts，无法渲染echarts图表

### What is Expected?
echarts图表正常渲染

### What is actually happening?
echarts无法渲染

**Comment by Leopoldthecoder** [comment]
DOM 节点在 `init` 时为隐藏状态，自然无法正常渲染：https://jsfiddle.net/8hhshr0b/1/
