### ISSUE TITLE
[Feature Request] Can provide disabled attributes for form components

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#9167]
### Existing Component
是

### Component Name
form

### Description
能否为 form 组件提供一个 disabled属性, 这样可以方便的通过 一个属性的设置 禁用整个form ,而不用给每个组件增加disabled属性来进行设置

**Comment by baiyaaaaa** [comment]
如果是整个表单都禁用的情况感觉用别的内容去呈现这个场景更加合适。

**Comment by zsedcbm** [comment]
做后台的时候,经常有这种情况,编辑和查看功能,如果页面少的话,可以直接通过新建一个查看页来处理.页面多的话工作量就比较大了.
目前我是通过给表单中的所有控件增加disabled属性进行统一禁用的.

**Comment by fergardi** [comment]
Can el-button-group and el-button be disabled too if they are in a disabled form?
