### ISSUE TITLE
[Bug Report] span-mehtod ---- Table multilayer nested merge cells do not meet expectations

### ISSUE THREAD

**Issue by AfterThreeYears** [ElemeFE/element#9171]
### Element UI version
2.0.11

### OS/Browsers version
macOS

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xcx5gzpt/1/](https://jsfiddle.net/xcx5gzpt/1/)

### Steps to reproduce
Check the form and find that some of the cells are not in the correct position

### What is Expected?
Merge the cell to the right position

### What is actually happening?
Merge cell to error

**Comment by Leopoldthecoder** [comment]
你的算法有问题，举例来说，当 `rowIndex` 为 2，`colIndex` 为 1 的时候（即第三行第一列）， 你的算法返回 `{ rowspan: 0, colspan: 0 }`，但实际上应该返回的是 `{ rowspan: 3, colspan: 1 }`。更新后的 demo：https://jsfiddle.net/xcx5gzpt/2/ 。

**Comment by AfterThreeYears** [comment]
@Leopoldthecoder 感谢！
