### ISSUE TITLE
[Bug Report] popover指令打包有问题，[Vue warn]: Failed to resolve directive: popover

### ISSUE THREAD

**Issue by thomasyus** [ElemeFE/element#9172]
### Element UI version
2.0.11

### OS/Browsers version
macos high sierra

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
在main.js里引入element：
import ElementUI from 'element-ui';
Vue.use(ElementUI);

在'./components/hello.vue' 里调用：
```
<el-popover
  ref="popover1"
  placement="top-start"
  title="标题"
  width="200"
  trigger="hover"
  content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
</el-popover>

<el-popover
  ref="popover2"
  placement="bottom"
  title="标题"
  width="200"
  trigger="click"
  content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
</el-popover>

<el-button v-popover:popover1>hover 激活</el-button>
<el-button v-popover:popover2>click 激活</el-button>
<el-popover
  placement="right"
  title="标题"
  width="200"
  trigger="focus"
  content="这是一段内容,这是一段内容,这是一段内容,这是一段内容。">
  <el-button slot="reference">focus 激活</el-button>
</el-popover>
```

### What is Expected?
正常由按钮控制popover的显示隐藏

### What is actually happening?
浏览器报错：
[Vue warn]: Failed to resolve directive: popover

(found in <HelloWorld> at src/components/hello.vue)

**Comment by Leopoldthecoder** [comment]
请将你的项目上传至 GitHub。

**Comment by alonprince** [comment]
一样的问题，版本2.0.11

**Comment by dexterliu1214** [comment]
`import { Popover } from 'element-ui'`
`Vue.use(Popover)`
