### ISSUE TITLE
[Bug Report] 页面引入select  select又内部引用了scrollbar 导致webpack时候报错 

### ISSUE THREAD

**Issue by rexwsd** [ElemeFE/element#9175]
环境 Laravel5.5 + Vue2 + webpack

页面加载了select插件  我看了一下select插件的源码里面引入了 scrollbar 这个插件初始化的时候报错了,不知道什么原因.

`ERROR in ./node_modules/element-ui/packages/scrollbar/src/main.js
Module parse failed: Unexpected token (65:12)
You may need an appropriate loader to handle this file type.
|         }, this.$slots.default);
|         const wrap = (
|             <div
|                 ref="wrap"
|                 style={style}
 @ ./node_modules/element-ui/packages/scrollbar/index.js 1:0-35
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/element-ui/packages/select/src/select.vue
 @ ./node_modules/element-ui/packages/select/src/select.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/first.vue
 @ ./resources/assets/js/components/first.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
`

**Comment by lrz0** [comment]
应该是因为引用了某个Element的组件引起的，可能是你手动引用或者IDE自动引入的。
