### ISSUE TITLE
[Bug Report] breadcrumb component generates an error

### ISSUE THREAD

**Issue by mediafigaro** [ElemeFE/element#9178]
### Element UI version
2.0.11

### OS/Browsers version
MAC 10.11.6 Chrome Version 63.0.3239.132 (Build officiel) (64 bits)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mediafigaro/oo1wtLzm/1/](https://jsfiddle.net/mediafigaro/oo1wtLzm/1/)

### Steps to reproduce

click on "click here = generates an error see console"
https://jsfiddle.net/mediafigaro/oo1wtLzm/1/

### What is Expected?
href should work

### What is actually happening?
error in console :
VM1241 index.js:1 Uncaught TypeError: Cannot read property 'push' of undefined
    at HTMLSpanElement.<anonymous> (VM1038 index.js:1)
or :
element-ui.common.js:18084 Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLSpanElement.<anonymous> (element-ui.common.js:18084)

https://jsfiddle.net/mediafigaro/oo1wtLzm/1/

**Comment by baiyaaaaa** [comment]
It'ss not a bug. You have not use vue-router in your code.

**Comment by mediafigaro** [comment]
thanks !
