### ISSUE TITLE
navmenu 能否通过数据生成，官方demo似乎没找到

### ISSUE THREAD

**Issue by kaven85** [ElemeFE/element#918]
### ElementUI version
1.0.0-rc.08

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.1

navmenu 能否通过数据生成，官方demo似乎没找到.dropdown的选项也是，没办法像select一样能够循环得出

**Comment by masterzhang** [comment]
可以的，自己设置菜单的树结构，做循环取出

**Comment by kaven85** [comment]
我的意思是通过组件+数据直接渲染出完整的html结构，而不是自己拼装html结构

**Comment by furybean** [comment]
v-for 应该都是可以使用的，请使用代码详细描述。

**Comment by Leopoldthecoder** [comment]
超过 7 天没有反馈的 issue 会被关闭。如果还有问题，可以重新打开。
