### ISSUE TITLE
[Bug Report] In Chrome, after setting the scroll bar height of the fixed column el-table, the column of the fixed appears longitudinal scrollbar

### ISSUE THREAD

**Issue by BowenZ** [ElemeFE/element#9181]
### Element UI version
2.0.11

### OS/Browsers version
win10/Chrome 63.0.3239.84

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/BowenZ/wt7h4f5y/](https://jsfiddle.net/BowenZ/wt7h4f5y/)

### Steps to reproduce
在Chrome中设置全局的滚动条样式，改变::-webkit-scrollbar的宽高，然后使用el-table，并且设置固定列fixed属性，如表格内容过多出现横向滚动条，则fixed的列就会出现滚动范围很小的一个滚动条

### What is Expected?
期望fixed的列正常显示

### What is actually happening?
实际上fixed的列出现了小幅滚动条

**Comment by furybean** [comment]
此问题在 2.1.0 中已修复，请确认：https://jsfiddle.net/wt7h4f5y/1/

**Comment by furybean** [comment]
先做关闭处理，如果还会重现，请留言，我会在确认后重开此 issue。
