### ISSUE TITLE
The.Trim of [Bug Report] el-input is invalid in some cases

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#9192]
### Element UI version
2.0.10

### OS/Browsers version
windows 10/chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/1oqjojjx/1974/](https://jsfiddle.net/1oqjojjx/1974/)

### Steps to reproduce
1、直接将“ 1”(数字1之前有空格)拷贝至el-input中
2、输入“1”之后，在首位或者末尾输入空格

### What is Expected?
能和input组件一致，后期输入的空格也能trim

### What is actually happening?
输入值之后，在首位或者末尾输入空格，el-input没有trim

**Comment by wacky6** [comment]
trim好像只能在原生input用吧：https://github.com/vuejs/vue/issues/5847
