### ISSUE TITLE
[Bug Report] el-switch with dynamic sub properties

### ISSUE THREAD

**Issue by llfbandit** [ElemeFE/element#9199]
### Element UI version
2.0.11

### OS/Browsers version
Windows 10 / Firefox 57

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/153/](https://jsfiddle.net/mmx38qxw/153/)

### Steps to reproduce
Please see the reproduction link:  https://jsfiddle.net/mmx38qxw/153/
Two components are defined, buggy-child & working-child.
The buggy-child component is binding to a sub-document property which is not working
The working-child component accesses directly to the property and now it's working...

### What is Expected?
binding dynamic sub-document properties should always work

### What is actually happening?
root properties are working but sub properties are not.

**Comment by Leopoldthecoder** [comment]
You're not using `computed` correctly: https://jsfiddle.net/mmx38qxw/157/ . As you can see in this demo, `model.input` does not update at all.

Remove `dynComponentProps` to `data` resolves this: https://jsfiddle.net/mmx38qxw/156/
