### ISSUE TITLE
Date Picker组件的bug反馈

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#92]
### ElementUI version
1.0.0-rc.3

### Vue version
2.0.0-rc.6

### Date Picker组件遇到的问题
1. date icon的样式有问题，被默认的el-icon样式重置了，如下图:
<img width="708" alt="date" src="https://cloud.githubusercontent.com/assets/10893176/18666666/aac2faf8-7f5f-11e6-973b-6b3d4de06ba3.png">
<img width="321" alt="date2" src="https://cloud.githubusercontent.com/assets/10893176/18666665/a9453fc4-7f5f-11e6-8458-cae18ba65f19.png">

2. 带快捷选项的时间范围(如图1)，操作点击 `最近一周` `最近一个月` `最近三个月` 会抛出错误，正常选择日期没问题。
```
[Vue warn]: Error in watcher "minDate" (found in component <date-table>)
Uncaught TypeError: i.getTime is not a function
```

**Comment by QingWei-Li** [comment]
我这边好像没这个问题，估计已经修掉了？
你试试用开发版，你 clone 这个项目下来，执行 `npm run bootstrap && npm run dist` 然后到你的项目下安装本地的 element

```shell
# 你的项目目录
npm install [你 clone 的 element 项目目录]
```

**Comment by isunkui** [comment]
@QingWei-Li 试过了，还是没有生效

**Comment by QingWei-Li** [comment]
第二个问题，我在文档页里并没有复现问题。你测试下文档页里会报错么，具体是哪一行？

**Comment by isunkui** [comment]
@QingWei-Li 第二个问题使用打包过后的文件就会有这个问题存在，我中午跟进下看看，我用下面这个pickerOption，只有今天触发了这个onClick触发并得到正确结果了，虽然两项虽然触发了，也没报错，但是没得到任何结果，用日期范围选择就会有错误，clone下来的项目里面dev模式没有出错。

```
pickerOptions1: {
            shortcuts: [{
              text: '今天',
              onClick(picker) {
                picker.$emit('pick', new Date());
              }
            }, {
              text: '昨天',
              onClick(picker) {
                const date = new Date();
                console.log('昨天');
                picker.$emit('pick', date.getTime() - 3600 * 1000 * 24);
              }
            }, {
              text: '一周前',
              onClick(picker) {
                const date = new Date();
                console.log('一周前');
                picker.$emit('pick', date.getTime() - 3600 * 1000 * 24 * 7);
              }
            }]
          }
```

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/cinwell_li/smawz7cj/ 并没有报错

**Comment by isunkui** [comment]
@QingWei-Li 找到问题了，`date-picker.md` 和 `datetime-picker.md` 文档错误，`picker.$emit('pick', date)` 接收的是 date 对象，不能接收时间戳
