### ISSUE TITLE
Error in callback for watcher "visible": "TypeError: this.$refs.tree.getCheckedNodes is not a function"

### ISSUE THREAD

**Issue by ragamuffinguil** [ElemeFE/element#9202]
### Element UI version
1.4.12

### OS/Browsers version
Win 7 / Google Chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/fo6k0s2q/](https://jsfiddle.net/fo6k0s2q/)

### Steps to reproduce
i declare everything in project just like in the demo 

### What is Expected?
to get getCheckedNodes values

### What is actually happening?
Error in callback for watcher "visible": "TypeError: this.$refs.tree.getCheckedNodes is not a function"

**Comment by Leopoldthecoder** [comment]
Your demo has only one Tree whose `ref` is `"tree1"`, but in the methods there're many `this.$refs.tree`. Changing them to `this.$refs.tree1` and everything works fine.
