### ISSUE TITLE
[Bug Report] IE11 layout container bug has found a solution, looking at the official corrections!

### ISSUE THREAD

**Issue by iTaster** [ElemeFE/element#9203]
### Element UI version
2.0.11

### OS/Browsers version
Window 10 / IE 11

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/cz5vf6qu/1/](url)

### Steps to reproduce
<el-container>
  <el-header>Header</el-header>
  <el-main>
      <el-table ...>...</el-table>
  </el-main>
</el-container>
-------------------------
在ie11下会el-main标签下的内容会不会显示出来

### What is Expected?
在IE11下显示出el-main标签下的内容

### What is actually happening?
在IE11下显示不出来。

已发现解决方法，望更正！

----------------------官方错误样式--------------

.el-main{-webkit-box-flex:1;-ms-flex:1;flex:1;box-sizing:border-box;padding:20px}

----------------------正确样式--------------

.el-main{-webkit-box-flex:1;-ms-flex:auto;flex:auto;box-sizing:border-box;padding:20px}

**Comment by Leopoldthecoder** [comment]
这段是 `autoprefixer` 处理的，如果不符合你的目标浏览器，请自行覆盖。

**Comment by wangmj** [comment]
And then?
How to fix this?
Has any solution?

**Comment by VinceBassman** [comment]
Would be great to have a solution for this...

**Comment by wangmj** [comment]
I fixed it by add an style to el-main,but I don't know why
.el-main{
  flex-basis: auto;
}
