### ISSUE TITLE
[Bug Report] the type definition of ELForm.validate is not right for Promise

### ISSUE THREAD

**Issue by aweiu** [ElemeFE/element#9206]
### Element UI version
2.0.10

### OS/Browsers version
mac sierra 10.12.6 / chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element/blob/4b3edc13abbac373d58503f9bc5223a7853d6df0/types/form.d.ts#L60](https://github.com/ElemeFE/element/blob/4b3edc13abbac373d58503f9bc5223a7853d6df0/types/form.d.ts#L60)

### Steps to reproduce
elForm.validate().then()

### What is Expected?
Not reported type error

### What is actually happening?
Property 'then' does not exist on type 'void'

**Comment by aweiu** [comment]
the `clearValidate` method is not defined too

**Comment by baiyaaaaa** [comment]
validate method do not return a promise

**Comment by aweiu** [comment]
@baiyaaaaa 
![wx20180111-164801](https://user-images.githubusercontent.com/15623620/34816222-3ffc1cfa-f6ef-11e7-9d37-a532875fa468.png)
