### ISSUE TITLE
Min and max value for el-input

### ISSUE THREAD

**Issue by gil0mendes** [ElemeFE/element#921]
**Type:** Feature request

**Description:** The `el-input` element should support `min` and `max` properties when the `type` is set to `number`.

## Example

The the value of the follow element can go bellow `1`:

```html
<el-input
  v-model="input1"
  type="number"
  :min="1">
</el-input>
```

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/element/blob/i18n/examples/docs/en-US/input.md#input-api

`maxlength` and `minlength` are supported.

**Comment by baiyaaaaa** [comment]
#922

**Comment by gil0mendes** [comment]
That doesn't work on numeric fields. You can see that on the [Input Element Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input). For `type="numeric"` fields must be used the `min` and `max`.

Quote from the `maxlength` specification: 

>If the value of the type attribute is text, email, search, password, tel, or url, this attribute specifies the maximum number of characters (in Unicode code points) that the user can enter; (...)

**Comment by baiyaaaaa** [comment]
I add the min & max support just now @gil0mendes Thanks~

**Comment by gil0mendes** [comment]
Thats awesome @baiyaaaaa ... Tks 😉

**Comment by ramon-src** [comment]
It is not working for me...

**Comment by kirandeep123** [comment]
User can still enter value greater than max value by manually entering in the fields.
