### ISSUE TITLE
[Bug Report] el-date-picker , type='datetime', the component value is not what we want , it is in 12-hours , but we want 24-hours.

### ISSUE THREAD

**Issue by tianwang8090** [ElemeFE/element#9214]
### Element UI version
2.0.11

### OS/Browsers version
win 10 / chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/7Lmm9qx8/3/](https://jsfiddle.net/7Lmm9qx8/3/)

### Steps to reproduce
you can try to choose the date : 2018.01.10 16:30:00 , you may get 2018.01.10 04.30.00 ; when you scroll the time-picker , you'll find the bug.

### What is Expected?
return 24-hours , like `new Date().getHours()`

### What is actually happening?
can not choose hours bigger than 12

**Comment by wacky6** [comment]
https://jsfiddle.net/r7m76mzw/
请仔细阅读格式化字串格式

**Comment by tianwang8090** [comment]
谢谢，‘小时’的格式化字符串时大写字母 “HH”.
