### ISSUE TITLE
[Bug Report] custom MessageBox problems

### ISSUE THREAD

**Issue by MrZhangbing** [ElemeFE/element#9216]
### Element UI version
2.0.11

### OS/Browsers version
2.5.9

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/p9fe1uy6/2/](https://jsfiddle.net/p9fe1uy6/2/)

### Steps to reproduce
1.进入页面，点击弹框 ，无法选中页面内容

### What is Expected?
期待每次点击打开弹窗时，弹窗中自定义组件内容能正常运行。

### What is actually happening?
自定义内容不响应

**Comment by ziyoung** [comment]
这不并不是 element-ui 的 bug。Vue 检测到数据的变化才会再一次重新渲染。

`this.$msgbox` 执行后在 document.body 下创建一个新的组件。而在这个新组件中，是无法监听 `is_send` 的变化的。

你可以使用 [dialog 组件](http://element-cn.eleme.io/#/zh-CN/component/dialog) 来解决该问题。
