### ISSUE TITLE
[Bug Report] upload audio upload 1000, set a limit of 200, but the page does not respond

### ISSUE THREAD

**Issue by nceliy** [ElemeFE/element#9218]
### Element UI version
2.0.11

### OS/Browsers version
windows10/chrome62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mg2javgg/1/](https://jsfiddle.net/mg2javgg/1/)

### Steps to reproduce
1、Click the upload button, upload 1000 audio, or file, the page does not respond

### What is Expected?
look forward to handleExceed methods

### What is actually happening?
has no respond

**Comment by nceliy** [comment]
https://jsfiddle.net/mg2javgg/1

**Comment by baiyaaaaa** [comment]
I can not create 1000 file upload case, but when i set the limit to 5 and upload 6 file a time, the handleExceed methods will be called

**Comment by nceliy** [comment]
yes,when you upload small amounts , handleExceed methods will be called. but you can try upload 1000 files case. this component will have no response.

**Comment by Leopoldthecoder** [comment]
@nceliy Could you try writing a native input with `type="file"` and uploading 1000 files at once and see what happens?

**Comment by nceliy** [comment]
e e e ...i have write a demo with type="file",the result is similar, the page has no response. I have inquiried many information but input file doesn't say it has limit , So I'm curious why it can't

**Comment by Leopoldthecoder** [comment]
I think it's because uploading 1000 files consumes too much resource so the browser crashes. It doesn't seem to have anything to do with upload limit.

Since the native upload also breaks in this case, there's not much we can do.

**Comment by nceliy** [comment]
OK，thank you very much~
