### ISSUE TITLE
[Feature Request] Switch component unique identifier on change event.

### ISSUE THREAD

**Issue by jonathanpmartins** [ElemeFE/element#9224]
### Existing Component
Yes

### Component Name
Switch

### Description
I cannot find in the docs information on how I can pass an identifier to the component, and later on, receive it in the change event.

I need to know, what component was changed, so I can proceed with the identifier and do an ajax request. The change event only return the value, and I do not like to put another event to do this, like a onchange event. It feels like an anti pattern.

Am I loosing something? Does anyone know another way that I can accomplish that?

Thanks very much

**Comment by wacky6** [comment]
What do you mean exactly?

```
<el-switch v-for="i in ..." @change="doSomething"></el-switch>
```
Try to get `i` in `doSomething`? If so, try high-order function.

**Comment by jonathanpmartins** [comment]
Yeah, little confusing. But right after posting I got it, heheehhe

Just needed to pass the argument in the method. Like so:

```
<el-switch v-for="i in ..." @change="doSomething(i.identifier)"></el-switch>
```

This is not an issue!
