### ISSUE TITLE
[Feature Request] Add custom icon class to Date / Time pickers

### ISSUE THREAD

**Issue by AdamSGit** [ElemeFE/element#9227]
### Existing Component
Yes

### Component Name
Date Picker, Time picker, Datetime picker

### Description
Unlike almost every component, it's not possible to change the date / time picker icon, both for prefix (the date or time icon) and suffix (the close icon)

I wanted to do it myself, just few lines to change, but I'm unaware of the building process, and didn't find any instruction. If you have a contributing guide I can solve this and send a PR.

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/tree/dev/.github Hope this helps.
