### ISSUE TITLE
[Feature Request] define table columns with Array/Object

### ISSUE THREAD

**Issue by Kris-Lee-SH** [ElemeFE/element#9229]
### Existing Component
Yes

### Component Name
el-table el-table-column

### Description
To add columns dynamicly in table, looking forward to defined columns with Array/Object.
This feature has already exist in iview & ant.
#### in ant:
```js
const dataSource = [{
  key: '1',
  name: '胡彦斌',
  age: 32,
  address: '西湖区湖底公园1号'
}, {
  key: '2',
  name: '胡彦祖',
  age: 42,
  address: '西湖区湖底公园1号'
}];

const columns = [{
  title: '姓名',
  dataIndex: 'name',
  key: 'name',
}, {
  title: '年龄',
  dataIndex: 'age',
  key: 'age',
}, {
  title: '住址',
  dataIndex: 'address',
  key: 'address',
}];

<Table dataSource={dataSource} columns={columns} />
```

#### in iview:
```js
<template>
    <Table :columns="columns1" :data="data1"></Table>
</template>
<script>
    export default {
        data () {
            return {
                columns1: [
                    {
                        title: 'Name',
                        key: 'name'
                    },
                    {
                        title: 'Age',
                        key: 'age'
                    },
                    {
                        title: 'Address',
                        key: 'address'
                    }
                ],
                data1: [
                    {
                        name: 'John Brown',
                        age: 18,
                        address: 'New York No. 1 Lake Park',
                        date: '2016-10-03'
                    },
                    {
                        name: 'Jim Green',
                        age: 24,
                        address: 'London No. 1 Lake Park',
                        date: '2016-10-01'
                    },
                    {
                        name: 'Joe Black',
                        age: 30,
                        address: 'Sydney No. 1 Lake Park',
                        date: '2016-10-02'
                    },
                    {
                        name: 'Jon Snow',
                        age: 26,
                        address: 'Ottawa No. 2 Lake Park',
                        date: '2016-10-04'
                    }
                ]
            }
        }
    }
</script>
```

**Comment by Kris-Lee-SH** [comment]
Actually we can use `v-for` to generate columns.
But when generating multiple headers recursively, father headers can't locate correctly.

**Comment by arisliang** [comment]
@Kris-Lee-SH Can you give a minimal example of how do you use v-for to generate columns? I have a similar case, would prefer the v-for solution, as it's more vue style.

**Comment by arisliang** [comment]
I found https://github.com/ElemeFE/element/issues/9101 to be helpful.

**Comment by Kris-Lee-SH** [comment]
@arisliang Actually, I've write an component with the following feature:
1. receives `data[Array]` and `columns[Array]` by props to render `el-table`
2. proxy `el-table` events and methods
3. add `custom-cell` component for it to accept customized cells

In `columns` props, the extra `renderType[String]` and `render[Function]` props for each column is defined to create a customized cell. And `render()` will receive `row`, `rowIndex`, `column` and `columnIndex` while rendering the current column.

All these ideas are inspired by reading the ***iview*** table source code.
Recommend u to read the source code!
Here is [my component](https://glitch.com/edit/#!/pepper-llama) for your reference.
