### ISSUE TITLE
[Bug Report] in table input is validate

### ISSUE THREAD

**Issue by DestinyHunter** [ElemeFE/element#9236]
### Element UI version
2.0.11

### OS/Browsers version
win10/chrome62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/159/](https://jsfiddle.net/mmx38qxw/159/)

### Steps to reproduce
```
<el-form>
  <el-table :data="list" border fit size="medium">
      <el-table-column align="center" label="首件/件">
        <template slot-scope="scope">
            <el-form-item prop="first">
              <el-input v-model.trim.number="scope.row.first"></el-input>
            </el-form-item>
        </template>
      </el-table-column>
  </el-table>
</el-form>
```

### What is Expected?
in table input can validate

### What is actually happening?
in table input no validate

**Comment by Leopoldthecoder** [comment]
你的 demo 里没有验证相关的代码，无法复现问题。

此外，即使是写原生 HTML，也不太会出现 `<form>` 元素里嵌套 `<table>` 这种结构，最好能重新规划一下页面结构。

**Comment by timshaw9791** [comment]
@Leopoldthecoder 写原生html，以现在的组件化开发程度，form中嵌套<table>也不过分的。我也在搜element以及底下的asyn-validator是如何校验一个对象中的数组中某个元素的属性的，我正在封装一个table中每行都能输入的组件。
举例来说，就是如何验证这个对象中的address.zipcode（而且是哪项出了问题就显示那项)
{number:'123'
 address:[
      {zipcode:'332500',name:'江西湖口'},
      {zipcode:'361005',name:'深圳蛇口'},
     {zipcode:'325035',name:'温州茶山'}
 ]
}

**Comment by timshaw9791** [comment]
@DestinyHunter  我翻了下el-form-item的源码，应该是可以的。但是要注意，我们在table.row中指定input的prop时，应该写的具体点：比如你的<el-form-item prop="first">应该写成<el-form-item prop="0.first">。表示数组中第0个元素的first属性。而上述我的应该是要写成prop="address.0.zipcode"。我还没写验证代码，但是我在控制台做过简单的测试，源代码分析如下：

这里的关键在验证功能是通过el-form-item.prop在model中找到需要验证的内容。
而根据el-form-item.prop拿到的值是一个叫做fieldValue的计算属性：
fieldValue: {
      cache: false,
      get: function get() {
        var model = this.form.model;
        if (!model || !this.prop) {
          return;
        }

        var path = this.prop;
        if (path.indexOf(':') !== -1) {
          path = path.replace(/:/, '.');
        }

        return (0, _util.getPropByPath)(model, path, true).v;
      }
    },
这里的path其实就等同于prop，所以关键就是_util.getPropByPath方法会不会给我们提供在数组中导航的能力，源代码如下：我们的数组下标会被直接变成属性的：


function getPropByPath(obj, path, strict) {
  var tempObj = obj;
  path = path.replace(/\[(\w+)\]/g, '.$1');
  path = path.replace(/^\./, '');
  var keyArr = path.split('.');
  var i = 0;
  for (var len = keyArr.length; i < len - 1; ++i) {
    if (!tempObj && !strict) break;
    var key = keyArr[i];
    if (key in tempObj) {
      tempObj = tempObj[key];
    } else {
      if (strict) {
        throw new Error('please transfer a valid prop path to form item!');
      }
      break;
    }
  }
  return {
    o: tempObj,
    k: keyArr[i],
    v: tempObj ? tempObj[keyArr[i]] : null
  };
};
