### ISSUE TITLE
[Feature Request] More icons for Element icon collection

### ISSUE THREAD

**Issue by AdamSGit** [ElemeFE/element#9238]
### Existing Component
Yes

### Component Name
Icon

### Description
I love Element icons, they are nices and minimalists, but the collection miss a lot of commons icons.

Here is the list, feel free to add yours :

Hamburger menu
Three vertical dot menu
Eye off (or view-off for consistency)
Chat, chat bubble and typing bubble
User
Group of users
Add user
Tag
Tags
Pin
Heart
Folder
Link / Broken link
Currency (USD, EUR, GBP)

Just a first proposal which should be discussed.

Are Element's icons designed by the core team, or is it compiled from a font generator ? If so, and if you want to share the process I can help with that.

Cheers guys

**Comment by liril-net** [comment]
I have moved this into product backlog, so i would close this issue.

**Comment by visualjerk** [comment]
@AdamSGit Are you already working on this? If not I would be glad to add some common icons.

**Comment by AdamSGit** [comment]
No I dont, feel free to do it.

I would be glad as well.

**Comment by visualjerk** [comment]
Right now I can't find a solid way to convert the existing icon fonts to SVG and back to the icon font + css styles. If the core team would share the process that would help a lot.

**Comment by AdamSGit** [comment]
Yes that's why I asked for too when opening this issue.
