### ISSUE TITLE
Whether [Feature Request] can return the number of current screening results in the filter-change event

### ISSUE THREAD

**Issue by blueroseslol** [ElemeFE/element#9239]
### Existing Component
是

### Component Name
el-table

### Description
我需要实现一个统计筛选结果数的功能。

table的data属性只能获得所有数据，无法获得数据的是否显示的属性，所以目前只能手动计算了。

目前只能通过各列的filter-method方法来维护一个存有各列结果数组的对象，之后通过交集计算来获得。但是重置后只能在filterChange中通过判断filters的名称与length，来清空维护的结果数组对象。

所以希望官方能够实现：

1、filterChange事件能够返回当前筛选结果数
或者
2、table的data属性能有数据是否显示的属性

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
