### ISSUE TITLE
radio-group 在v-for中循环失效

### ISSUE THREAD

**Issue by NotGeekAtAll** [ElemeFE/element#924]
version: 1.0.0-rc.8
browser: chrome53

html:
`<el-form-item v-for="item in innerNums" :label="item.label">
			  	<el-radio-group v-model="item.model">
			      <el-radio label="1">红包</el-radio>
			      <el-radio label="2">溯源</el-radio>
			    </el-radio-group>
			  </el-form-item>`

data:
`let inOp = [{
		        	label: '一级内码',
		        	model: '2'
		        },{
		        	label: '二级内码',
		        	model: '2'
		        },{
		        	label: '三级内码',
		        	model: '2'
		        },{
		        	label: '四级内码',
		        	model: '2'
		        }];`

因为我用这样的结构用在select上和其他input元素上都能操作model，但是用在radio上点击不了。

同样用在checkbox中也点击不了

@baiyaaaaa @Leopoldthecoder @QingWei-Li  http://jsbin.com/wiyopukasi/5/edit?html,output
我在vue-devtools 中是可以看到select的值改变，但是radio（checkBox一样的情况）不能点击。

**Comment by Leopoldthecoder** [comment]
你的例子里 `innerNums` 和 `outNums` 不应该是计算属性，因为手动对计算属性赋值是无效的。

事实上，Select 虽然可以点击，但是它对应的 model 也并没有发生变化。

**Comment by NotGeekAtAll** [comment]
@Leopoldthecoder 可以把代码通过devtools中观察，选择select，model是随之变化。
![](http://p1.bpimg.com/4851/5d45440329222e6b.gif)
可能我这个需求还是需要把数据定义data中，操作change时间改变data。

**Comment by Leopoldthecoder** [comment]
不知道为什么 devtool 里会变，实际上值是没变的：http://jsbin.com/sobamuvema/edit?html,output

**Comment by NotGeekAtAll** [comment]
@Leopoldthecoder 好吧，挺奇怪的。不过通过select还是能获取改变computed中的model，谢谢了！
