### ISSUE TITLE
[Bug Report]'s custom model component for the first time in the form does not trigger validation for the first time

### ISSUE THREAD

**Issue by lynzz** [ElemeFE/element#9240]
### Element UI version
2.0.10

### OS/Browsers version
macOS Hight Sierra 10.13.2 / chrome 版本 63.0.3239.84（正式版本） （64 位）

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/lynzz/m4vefuac/1/](https://jsfiddle.net/lynzz/m4vefuac/1/)

### Steps to reproduce
1. 省选择福建省，会提示请选择所在地，这是对的
2. 市选择福州市，会再次提示请选择所在地，这也是对的
3. 区选择市辖区，还是会提示请选择所在地，这是错的

### What is Expected?
1. 省选择福建省，会提示 请选择所在地
2. 市选择福州市，会再次提示 请选择所在地
3. 区选择市辖区，不会提示 请选择所在地，且三个选择框边框应都是绿色的

### What is actually happening?
当再次变更 区选择时，就不会提示 请选择所在地

同样的问题，如果更改省，因我并没有选择 市和区，这时应会提示  选择所在地，但实际没有给出提示

只有我再次切换省或者选择市时，才会给提示

总感觉自定义的 model 首次变更值没有触发到 el-form-item 的验证

直接点击 提交时，验证是 ok 的

**Comment by Leopoldthecoder** [comment]
父组件的 `form.areaId` 是在 `select-city` 组件执行 `this.$emit('selected-change', selected + '')`
 时才更新的，因此 `select-city` 组件中的 `<el-select>` 触发校验的时候，父组件上的值还未更新。

解决方法就是在父组件上的值更新之后再触发一次校验：https://jsfiddle.net/m4vefuac/2/ 。

**Comment by lynzz** [comment]
明白了，谢谢  @Leopoldthecoder
