### ISSUE TITLE
[Bug Report] When the el-menu component is folded, the child menus shows a bad effect after setting the overflow to the parent menu.

### ISSUE THREAD

**Issue by Jack-93** [ElemeFE/element#9241]
### Element UI version
2.0.11

### OS/Browsers version
win10/QQ浏览器

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/json93/nx660awg/](https://jsfiddle.net/json93/nx660awg/)

### Steps to reproduce
先折叠，
鼠标放在导航一

### What is Expected?
https://codepen.io/pen/?&editors=001
子菜单可以正常显示，
这是阿里ant-design的导航实现，对比后发现，饿了吗是把DOM放在了li子菜单下，ant是放在body里面独立一个DOM来存放，所以可以正常显示。
另外希望考虑左侧导航菜单很多时，希望可以出现滚动条，在导航DOM内部滚动，而不会影响整个页面。
期待elment能够越来越好，在vue这个派系中成为超越ant的开源框架
也期待可以贡献自己的一份力量，实在不想从vue转到react

### What is actually happening?
子菜单显示不正常

**Comment by Leopoldthecoder** [comment]
#9263 moved the popup menu to body. It'll be shipped with our next minor version.
