### ISSUE TITLE
[Feature Request] el-autocomplete     :fetch-suggestions="querySearch"  输入汉字时  queryString识别为拼音

### ISSUE THREAD

**Issue by wufeng123456** [ElemeFE/element#9245]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
现象：  
       使用 el-autocomplete组件时，搜狗拼音输入拼音‘nanjing’并确认汉字‘南京 ’后， querySearch方法参数  queryString 为 ‘nanjing’；在querySearch方法内部查看v-model的值也为‘nanjing’ ，发现是querySearch发生在v-model之前，导致后续操作出现问题。

涉及代码如下：

       <el-autocomplete
          popper-class="my-autocomplete"
          v-model="dataValueBefore"
          :fetch-suggestions="querySearch"
          placeholder="请输入内容"
          @select="handleSelect">
          <i
            class="el-icon-delete el-input__icon"
            slot="suffix"
            @click="handleIconClickBefore">
          </i>
          <template slot-scope="props">
            <div class="name">{{ props.item.value }}</div>
          </template>
        </el-autocomplete>
       

    querySearch(queryString, cb) {
      var dataOptions = this.dataOptions;
      var results = queryString ? dataOptions.filter(this.createFilter(queryString)) : dataOptions;
      // 调用 callback 返回建议列表的数据
      cb(results);
    },

    createFilter(queryString) {
      return (restaurant) => {
        return (restaurant.value.toLowerCase().indexOf(queryString.toLowerCase()) !== -1);
      };
    },

**Comment by baiyaaaaa** [comment]
please provide a bug reproduction demo.

**Comment by wufeng123456** [comment]
Version of the problem，why are you fucking close it??!!
