### ISSUE TITLE
When the [Bug Report] upload file fails, the file will pop up again; hope to support the hidden selection file button and only display the file list that has been uploaded.

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#9246]
### Element UI version
2.0.10

### OS/Browsers version
windows 10/chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/Lc83h7r9/2/](https://jsfiddle.net/Lc83h7r9/2/)

### Steps to reproduce
1.上传图片，上传失败后，列表中会显示该文件，然后再消失，整个页面会跳动一下
2.希望可以点击保存后，只显示上传成功的文件列表，隐藏“点击上传”的button，如果用v-show控制，会留下空白，而不是整体上移。

### What is Expected?
1.上传图片失败，直接在列表中不显示，而不是显示后再消失
2.可以提供隐藏上传button的方法

### What is actually happening?
1.上传图片，上传失败后，列表中会显示该文件，然后再消失，整个页面会跳动一下
2.希望可以点击保存后，只显示上传成功的文件列表，隐藏“点击上传”的button，如果用v-show控制，会留下空白，而不是整体上移。

**Comment by AprilXtt** [comment]
用 this.$el.childNodes[0].setAttribute('style', 'display: none') 可以实现button的隐藏
请问有没有更好的方式？

**Comment by Leopoldthecoder** [comment]
> 上传图片，上传失败后，列表中会显示该文件，然后再消失，整个页面会跳动一下

这是设计中的，从交互上说，如果上传失败，需要让终端用户有感知。

隐藏按钮可以直接通过 CSS 解决：https://jsfiddle.net/Lc83h7r9/5/

**Comment by AprilXtt** [comment]
@Leopoldthecoder 感谢你的回复。
把show作为flag传入upload组件中时，还是会有空白。
demo如下：https://jsfiddle.net/Lc83h7r9/48/

**Comment by Leopoldthecoder** [comment]
> 隐藏按钮可以直接通过 CSS 解决：https://jsfiddle.net/Lc83h7r9/5/
