### ISSUE TITLE
[Dev]  about custom development of element-ui 

### ISSUE THREAD

**Issue by my9074** [ElemeFE/element#9254]
### Existing Component
No

### Component Name
no

### Description
本人 fork 了 element-ui 项目，想自己定制一下~但是开发完测试的时候很是麻烦。之前是通过发布到 npm 上，然后测试项目再 `npm install`，这样很是繁琐。之后用 `npm link` 的方式将其 link 到全局，然后在测试项目下 `npm link xx-element` 再`npm install` ，但是会报这个错:
![image](https://user-images.githubusercontent.com/4555635/34867125-ed38533c-f7b9-11e7-983a-97f76348f1bb.png)
我现在不知道到底是测试项目 webpack 的问题，还是利用 `npm link`的方式不对？
望开发大大们指导个正常的开发测试流程~~谢谢

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
