### ISSUE TITLE
[Bug Report] Component, Container, Common layouts, The Last One existence Bug

### ISSUE THREAD

**Issue by yupeilin123** [ElemeFE/element#9256]
### Element UI version
2.0.11

### OS/Browsers version
chorme 

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/1sqmwdo0/2/](https://jsfiddle.net/1sqmwdo0/2/)

### Steps to reproduce
1.写两个包含el-header 和 el-footer的子组件，或三个包含el-main,el-head和el-footer的子组件
2.放在el-contanier中
3.布局失控

### What is Expected?
不会出现Layout的布局失控

### What is actually happening?
Layout的布局失控

**Comment by Leopoldthecoder** [comment]
`<el-container>` 无法检测到被封装的组件，你需要手动指定 `direction`：https://jsfiddle.net/1sqmwdo0/3/
