### ISSUE TITLE
[Bug Report] Tooltip too much content, style problems

### ISSUE THREAD

**Issue by lujunpeng** [ElemeFE/element#9258]
### Element UI version
2.0.11

### OS/Browsers version
Google Chrome 版本 63.0.3239.132（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/lujunpeng/z9eevo3u/](https://jsfiddle.net/lujunpeng/z9eevo3u/)

### Steps to reproduce
Tooltip content  too much

### What is Expected?
content  in body

### What is actually happening?
Left beyond body

**Comment by Leopoldthecoder** [comment]
自己写个 CSS 就好：https://jsfiddle.net/z9eevo3u/1/
