### ISSUE TITLE
[Bug Report] table bug

### ISSUE THREAD

**Issue by wenbo2018** [ElemeFE/element#9264]
### Element UI version
2.0.5

### OS/Browsers version
MAC OS

### Vue version
2.2.1

### Reproduction Link
NO
### Steps to reproduce
TypeError: Cannot read property 'row' of undefined
when use <template slot-scope="scope">
                        <span>{{ scope.row.roleDesc }}</span>
                    </template>

### What is Expected?
。

### What is actually happening?
。

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
