### ISSUE TITLE
请问有Axure和PS设计模版吗？只找到了sketch的模版

### ISSUE THREAD

**Issue by do-chieh** [ElemeFE/element#9269]
请问有Axure和PS设计模版吗？只找到了sketch模版

**Comment by clChenLiang** [comment]
https://github.com/ElementUI/Resources/blob/1.x/Element_Components_v1.1.0.rplib

**Comment by profoundsoul** [comment]
https://github.com/ElementUI/Resources 直接去这个仓库里面，下载zip包，就都有了。
