### ISSUE TITLE
[Bug Report] Form validation allow empty field to pass even the rule requires it to not be empty

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/element#9271]
### Element UI version
2.0.11

### OS/Browsers version
Chrome latest and Ubuntu 16.04

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/48e6r8or/](https://jsfiddle.net/48e6r8or/)

### Steps to reproduce
Click password input field but don't put anything in
Click somewhere else

Then the password field will show that it is valid, but it is not supposed to

If we call the validation again when submitting the form, it would suggests error
But it looks really confusing to suggest to user that the password is fine even if it is empty

### What is Expected?
Just the password field to lose focus

### What is actually happening?
The password field passed the validation and looked green

**Comment by Leopoldthecoder** [comment]
Change trigger from `change` to `blur`: https://jsfiddle.net/48e6r8or/1/ . Because the following steps don't trigger `change` event:
> Click password input field but don't put anything in
> Click somewhere else

**Comment by WangHansen** [comment]
Change to blur can solve the problem, but it is still an issue.
I upgraded to 2.0.11 two days ago and found the problem, at 2.0.8, the behavior is not like this.

**Comment by Leopoldthecoder** [comment]
I don't see any difference between [2.0.8](https://jsfiddle.net/48e6r8or/3/) and [2.0.11](https://jsfiddle.net/48e6r8or/).
