### ISSUE TITLE
[Bug Report] el-input

### ISSUE THREAD

**Issue by tianwang8090** [ElemeFE/element#9275]
### Element UI version
2.0.11

### OS/Browsers version
win 10 / chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/171/](https://jsfiddle.net/mmx38qxw/171/)

### Steps to reproduce
在官网页面选择【DatePicker 日期选择器】，然后打开控制台，在打印中会有浏览器错误，提示多个元素的id不唯一

### What is Expected?
修复表单组件内的id不唯一问题

### What is actually happening?
id不唯一

**Comment by Leopoldthecoder** [comment]
Duplicate of https://github.com/ElemeFE/element/issues/8907
