### ISSUE TITLE
[Bug Report] DateTimePicker clearance problem

### ISSUE THREAD

**Issue by wdnlwzd** [ElemeFE/element#9276]
### Element UI version
2.0.11

### OS/Browsers version
mac high sierra10.13.2/ chrome  63.0.3239.132

### Vue version
2.5.2

### Reproduction Link
https://jsfiddle.net/vasttian/df9e5o7t/

### Steps to reproduce
选择了时间后手动清除时间（并非使用清除按钮），然后输入框为空了，但是实际的时间值还是之前的。
使用清除按钮没有此问题， v1.4 手动清除也没有此问题。
![image](https://user-images.githubusercontent.com/17924984/34929175-4aefcf7e-f9fd-11e7-949f-d4c82a4e62ae.png)

![image](https://user-images.githubusercontent.com/17924984/34929167-3f7bab0e-f9fd-11e7-8e9b-ad8b22a0a28f.png)

### What is Expected?
一并清空

### What is actually happening?
并未清空

**Comment by wdnlwzd** [comment]
@Leopoldthecoder  请问

**Comment by fengyun2** [comment]
我也遇到了这个问题，请问有解决了么？

**Comment by wacky6** [comment]
https://github.com/ElemeFE/element/pull/9409
