### ISSUE TITLE
[Bug Report] Select component has a bug in IOS system

### ISSUE THREAD

**Issue by wishflyer** [ElemeFE/element#9278]
### Element UI version
2.0.11

### OS/Browsers version
IOS 8  (iphone/ipad)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/hn1052w5/](https://jsfiddle.net/hn1052w5/)

### Steps to reproduce
in ios(ipad/iphone) , click the select component can not show the menu ,but it is ok in PC or android.

![bug](https://user-images.githubusercontent.com/15098721/34930035-5e5ab61e-fa02-11e7-8fb6-04639c8fabd1.png)

### What is Expected?
click the select component must show the dropdown menu

### What is actually happening?
in ios(ipad/iphone) , click the select component can not show the menu ,but it is ok in PC or android.

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop pages. Please don't use it on mobile devices.
