### ISSUE TITLE
[Bug Report] Run unit test issue: when I run unit test, it shows: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by niboac** [ElemeFE/element#9279]
### Element UI version
2.0.11

### OS/Browsers version
MAC / chrome

### Vue version
2.5.13

### Reproduction Link
[https://github.com/niboac/vue-element-test](https://github.com/niboac/vue-element-test)

### Steps to reproduce
Clone this repro: https://github.com/niboac/vue-element-test, then run: npm install & npm run unit,  test this project.

### What is Expected?
Expect NO error.

when I remove the directive "v-loading", it has no error. so I think the bug is from v-loading.

### What is actually happening?
It shows a error: 
/Users/cb/GitHub/vue-element-test-issue/node_modules/vue/dist/vue.runtime.common.js:6903
  var transitionDelays = styles[transitionProp   'Delay'].split(', ');
                                                         ^

TypeError: Cannot read property 'split' of undefined
    at getTransitionInfo (/Users/cb/GitHub/vue-element-test-issue/node_modules/vue/dist/vue.runtime.common.js:6903:58)

**Comment by industral** [comment]
confirm. have same issue. can be reproduced when doing tests in loop. Occurs time to time.

**Comment by adin234** [comment]
so, any news?

**Comment by adin234** [comment]
so do we need to use a different fork of vue for the tests to work? :(

**Comment by industral** [comment]
ideally, wait until they merge it... Unfortunately I can see just tones of PRs in a queue..

**Comment by adin234** [comment]
so no other choice than to use a fork then. thanks for your work, im using it now @industral  :)

**Comment by adin234** [comment]
https://github.com/vuejs/vue/pull/8281

PR is merged so i think thin can be closed
