### ISSUE TITLE
[Bug Report] data changed but radio change Event can't emit

### ISSUE THREAD

**Issue by hszy00232** [ElemeFE/element#9284]
### Element UI version
2.0.11

### OS/Browsers version
mac

### Vue version
2.5.13

### Reproduction Link
[http://jsfiddle.net/hszy00232/s5xz40yx/16/](http://jsfiddle.net/hszy00232/s5xz40yx/16/)

### Steps to reproduce
1. radio3 default value is  'New York'
data () {
      return {
        radio3: 'New York',
        radio4: 'New York',
        radio5: 'New York'
      };
    },
2. on created event , is seted with ''Washington"
 created(){
    	this.radio3 = 'Washington'
    }
3. but changeEvent can't emit

### What is Expected?
when radio3's value is changed, the changeEvent is emit

### What is actually happening?
when radio3's value is changed, the changeEvent is  not emit

**Comment by Leopoldthecoder** [comment]
All form components (Input, Radio, Checkbox, Select, etc.) only triggers `change` event on user interaction, they'll not fire if you change their value programmatically. This behavior aligns with native input elements.

**Comment by hszy00232** [comment]
1.3.7 is supported，but the new version can't supported. would you please tell me some methods  for this situation

**Comment by wacky6** [comment]
use vue's watch

**Comment by wacky6** [comment]
you can also use input event if you do not care about frequent emission.
