### ISSUE TITLE
[Bug Report] el-date-picker ie lower back display failure

### ISSUE THREAD

**Issue by Denny-coder** [ElemeFE/element#9291]
### Element UI version
2.0.11

### OS/Browsers version
ie11

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/Denny_code/5oe90kq7/](https://jsfiddle.net/Denny_code/5oe90kq7/)

### Steps to reproduce
在ie下无法正常回显，但是将placeholder删除后将可以回显

### What is Expected?
我这个是否只是个例？

### What is actually happening?
在ie下日期无法正常回显，

**Comment by wacky6** [comment]
date-picker绑定值需要时date对象，或者用value-format指定格式

**Comment by Denny-coder** [comment]
@wacky6 试了一下依旧没有成功回显 https://jsfiddle.net/Denny_code/5oe90kq7/1/

**Comment by wacky6** [comment]
那大概是ie才有的问题。我这里safari/chrome没有复现

**Comment by furybean** [comment]
@Denny-coder 【回显】指的是什么？能否截图说明？

**Comment by furybean** [comment]
@Denny-coder Duplicate with #8097. Fixed in PR #9325.

**Comment by lizhenheng1** [comment]
在非IE 主流浏览器下返回的格式是yyyy-MM-dd 到IE这就成yyyy 年 MM 月 dd 日  了
