### ISSUE TITLE
[Bug Report] When using a dialog in a nested form, when there is only one input tag within the form, clicking back in the input tag will refresh the whole page

### ISSUE THREAD

**Issue by dadianzi** [ElemeFE/element#9292]
### Element UI version
2.0.11

### OS/Browsers version
win10/chrome63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/zy736920/mmx38qxw/173/](https://jsfiddle.net/zy736920/mmx38qxw/173/)

### Steps to reproduce
When using a dialog in a nested form, when there is only one input tag within the form, clicking back in the input tag will refresh the whole page.
在dialog里边嵌套表单，如果表单里只有一个input标签时，在input内点击回车 会刷新整个页面

### What is Expected?
Do not refresh the page

### What is actually happening?
Refresh

**Comment by furybean** [comment]
This is the default behavior of `<form>` tag. If you want to prevent this, just add @submit.native.prevent on `<el-form>` tag.

[Link](https://jsfiddle.net/mmx38qxw/174/)
