### ISSUE TITLE
[Bug Report] tree components and vue-devtools development use will be wrong

### ISSUE THREAD

**Issue by FuDesign2008** [ElemeFE/element#9293]
### Element UI version
2.0.11

### OS/Browsers version
mac OS / chrome

### Vue version
2.5.13

### Reproduction Link
[https://github.com/FuDesign2008/vue-element-tree-bug](https://github.com/FuDesign2008/vue-element-tree-bug)

### Steps to reproduce
@see https://github.com/FuDesign2008/vue-element-tree-bug

### What is Expected?
与 vue-devtools 配合使用不报错

### What is actually happening?
不确定是element tree 组件的问题还是 vue-devtools的问题

**Comment by Pochodaydayup** [comment]
我也出现了和你同样的问题。

**Comment by Glenfiddish** [comment]
好像是@node-expand 的递归调用触发的 max call

**Comment by FuDesign2008** [comment]
@Glenfiddish  熟悉相关代码么？ 熟悉的话fix 提个 pull 吧，个人刚学习这一块，不太了解

**Comment by Leopoldthecoder** [comment]
https://github.com/vuejs/vue-devtools/issues/528
