### ISSUE TITLE
[Feature Request] The tree control el-tree gets the ID of the parent node

### ISSUE THREAD

**Issue by lmxdawn** [ElemeFE/element#9295]
### Element UI version
2.0.11

### OS/Browsers version
Windows,

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/L8hokz6x/5/](https://jsfiddle.net/L8hokz6x/5/)

### Steps to reproduce
1.一共一个父节点，二个子节点
2.选中其中一个子节点
3.点击 “获取选中值” 按钮，
4.如果所有子级没有被选中，则获取不到父节点的id值

### What is Expected?
当 点击 “获取选中值” 按钮
即使不选中所有的子级 也要获取到父级节点的 id 值

### What is actually happening?
当 点击 “获取选中值” 按钮
所有子级都被选中的情况下才能获得父级的id，如果不选中所有的子级那么获取得到的id就只有子级的

**Comment by Hi-Linlin** [comment]
你好。
当子级没有全部勾选时，父级并不是勾选状态（CheckBox 里的 icon 为 [ - ], 而不是 [ √ ]）。
父级勾选的判定条件应该是: 所有子级已被勾选。
既然父级没勾选，获取不到 ID 也是正常的。

**Comment by lmxdawn** [comment]
@Hi-Linlin  你好，如果想让 icon 为 [ - ] 时也能获取到，该怎么样实现呢？

**Comment by zhangw** [comment]
@lmxdawn 可以考虑利用tree自身的store.nodesMap去找到indeterminate状态的节点

**Comment by furybean** [comment]
能描述下使用场景吗？

**Comment by lmxdawn** [comment]
@furybean  场景是这样的，我要做一个权限的节点，我希望选中了某个一个子权限，把父权限一起保存下来，但是现在需要把所有的子权限选中，父权限 才能获取到

**Comment by furybean** [comment]
@lmxdawn Okay，先记到 Feature Request  中。

**Comment by lmxdawn** [comment]
@furybean  好的

**Comment by hasbug** [comment]
这个需求几个月前就有了，坐等官方提供解决方案，谢谢。

**Comment by qingdengyue** [comment]
@furybean 话说 能否利用节点的parent来获取这个id?

**Comment by furybean** [comment]
@lmxdawn 
新增了 check 事件，应该可以满足你这个需求：https://github.com/ElemeFE/element/pull/9730

@qingdengyue 
新增了 getNode 的 api，可以根据 key、data 随意获取 Node 类型的对象，这样直接拿 node.parent 就可以。

**Comment by lmxdawn** [comment]
@furybean  自己根据节点状态变化记录值？

**Comment by furybean** [comment]
@lmxdawn 选中和半选中的变化比较复杂，没办法在一个事件里面告诉你变化的是什么。 check 事件会告诉你目前所有的选中和半选中的节点，只要把之前的状态全量替换掉就可以吧？

**Comment by lmxdawn** [comment]
@furybean 貌似是能这样了，就是这样不大方便个。。。

**Comment by tangmin721** [comment]
i think  the halfchecked is nouse api.  why not learn about ztree api?

**Comment by NoUserNames** [comment]
希望再增加一个API呢？可以获取父节点，也可以不获取父节点的。这样方便前端不熟练的后端开发

**Comment by LLJJTT** [comment]
希望再增加一个API！！！可以通过子节点 获取父节点！！
