### ISSUE TITLE
[Bug Report] el-input'change'event cannot trigger when value changed

### ISSUE THREAD

**Issue by YYQ8023** [ElemeFE/element#9297]
### Element UI version
2.0.11

### OS/Browsers version
win10 chrome63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/zw97tx80/](https://jsfiddle.net/zw97tx80/)

### Steps to reproduce
输入一个数据，不触发change事件，当输入框失去焦点时才触发。
按照w3c的文档，change事件是这样的没错，但是还是希望有一个实时监测的change事件。

### What is Expected?
输入改变就可以触发change事件

### What is actually happening?
失去焦点时才触发

**Comment by liaoyinglong** [comment]
看了一下代码，1.4.x的版本还是会实时触发`change`的，然后在2.0的时候移除了这个，具体为什么没仔细看。

另外如果有需要的话可以用`@input`事件也行吧。

https://jsfiddle.net/zw97tx80/10/

**Comment by Leopoldthecoder** [comment]
#9284
