### ISSUE TITLE
[Bug Report] Theme chooser demo is not properly localized

### ISSUE THREAD

**Issue by cfjedimaster** [ElemeFE/element#9299]
### Element UI version
2.0.11

### OS/Browsers version
Win10/FF

### Vue version
2.5.13

### Reproduction Link
[https://elementui.github.io/theme-chalk-preview/#/en-US](https://elementui.github.io/theme-chalk-preview/#/en-US)

### Steps to reproduce
Go to the theme app, https://elementui.github.io/theme-chalk-preview/#/en-US, select Change Theme Color and pick a new color. The buttons are in Japanese. Here is a screen shot.

http://www.evernote.com/l/AAPs8iI5CnVN7LxybdUb_KONToBehLg0R6A/

### What is Expected?
English buttons

### What is actually happening?
Japanese (I assume!) buttons

**Comment by Leopoldthecoder** [comment]
It's now fixed (actually the text was in Chinese).

**Comment by cfjedimaster** [comment]
Thanks - and sorry for misindentifying the language. Don’t tell my kids I screwed that up. ;) (Half are Chinese. :)
