### ISSUE TITLE
[Feature Request] Please add phone Touch events for Slider

### ISSUE THREAD

**Issue by hackyoMa** [ElemeFE/element#9301]
### Existing Component
是

### Component Name
Slider

### Description
Please add a mobile phone touch events Slider, Slider convenient for mobile use.

**Comment by Leopoldthecoder** [comment]
Element is designed for desktop pages. Please avoid using it on mobile devices.

**Comment by SergeyKolesnikPower** [comment]
Why did that element (http://element.eleme.io/#/en-US/component/layout) design for mobile pages?
