### ISSUE TITLE
[Feature Request] Datepicker component needs openingDate or a way to set currentDate

### ISSUE THREAD

**Issue by AshwinTayson** [ElemeFE/element#9302]
### Existing Component
Yes

### Component Name
el-date-picker

### Description
The current el-date-picker component doesn't have the ability to display custom date. Currently it just show the current date.

Example:
```

<el-date-picker
    v-model="campaignPeriod"
    type="daterange">
</el-date-picker>
```

If I click on this element, it opens the date-range component with Jan-Feb month (Today is 17 Jan). We need a method to change this to any preferred month. (eg. prop

>  :openingDate="getOpenDate"

 where getOpenDate can be "01-05-2018" and the calendar will open May-Jun 2018.

**Comment by wacky6** [comment]
see default-value

**Comment by furybean** [comment]
@AshwinTayson use default-value prop. online demo: https://jsfiddle.net/j5jfgc3x/

**Comment by AshwinTayson** [comment]
I have edited the fiddle accroding to my question. As you can see if I select the campaign the default value gets updated only once after that it doesn't change according to the campaign I select.

Fiddle Link: https://jsfiddle.net/j5jfgc3x/1/

**Comment by wacky6** [comment]
https://jsfiddle.net/nza8oemk/

Empty value should be falsy, do not use `[null, null]`
