### ISSUE TITLE
[Bug Report] if the width of the container of the select component is too small, the style of the selection will be disorganized

### ISSUE THREAD

**Issue by aeolusheath** [ElemeFE/element#9305]
### Element UI version
2.0.11

### OS/Browsers version
chrome  63.0.3239.84

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/gwhhxkeL/1/](https://jsfiddle.net/gwhhxkeL/1/)

### Steps to reproduce
这个是直接将官方的jsfiddle 实例做的改动：
1，将el-select组件根元素设置宽度为100px,或者手动加一个container（宽度为100px）
2, 然后点击选择option，发现样式乱掉----->>>>> 三角箭头跑到option的外边去了

### What is Expected?
期待的行为，三角箭头一直保留在option(item)上面，样式不会乱掉

### What is actually happening?
样式错位

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/35190181-9f42b558-fe96-11e7-9be1-2e51f20f140a.png)

@syn-zeta Actually this is about this triangle. Fixed in #9309.
