### ISSUE TITLE
Select component can not auto scale,Cause input component and select component length inconsistencies 

### ISSUE THREAD

**Issue by gmshiot** [ElemeFE/element#9306]
### Element UI version
2.0.11

### OS/Browsers version
win10/Chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/5ns0j44y/](https://jsfiddle.net/5ns0j44y/)

### Steps to reproduce
Scale browser window,then you will see.

### What is Expected?
auto scale,length consistent with input component.

### What is actually happening?
Select component can not auto scale,Cause input component and select component length inconsistencies .

**Comment by furybean** [comment]
@gmshiot Add style="width: 100%" to `<el-select>` will fix this. https://jsfiddle.net/5ns0j44y/1/
