### ISSUE TITLE
Table组件勾选问题

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#931]
### Steps to reproduce
![table-selection](https://cloud.githubusercontent.com/assets/7945757/20124749/c1900930-a663-11e6-9e55-0b2ecca35328.gif)
选中表格某行，然后通过删选去掉该行后`selection`的值还存在，因为此时没有触发`selection-change`事件。当把搜索条件去掉的时候，原来选中的行也没有勾选上，并且没有触发`selection-change`事件。

**Comment by furybean** [comment]
『当把搜索条件去掉的时候，原来选中的行也没有勾选上，并且没有触发selection-change事件。』
筛选是前端筛选还是后端筛选？如果是后端筛选，估计得加上 row-key + reserve-selection 才能保留吧。

**Comment by furybean** [comment]
『选中表格某行，然后通过删选去掉该行后selection的值还存在，因为此时没有触发selection-change事件。』
这个确实是一个问题，clearSelection 的时候我判断一下。

**Comment by reverland** [comment]
所以说都什么时候需要clearSelection。。。

**Comment by erguotou520** [comment]
前端筛选

**Comment by furybean** [comment]
@erguotou520 前端筛选的话，『当把搜索条件去掉的时候，原来选中的行也没有勾选上』，Table 的 data 的每次变化都会造成 clearSelection，感觉这个行为是预期行为。

**Comment by erguotou520** [comment]
这条是可以理解，但是另一个确实是问题
