### ISSUE TITLE
[Bug Report] Table controls are abnormal in some resolution and zoom

### ISSUE THREAD

**Issue by yinjunonly** [ElemeFE/element#9312]
### Element UI version
2.0.11

### OS/Browsers version
Windows10/Chrome 63.0.3239.132（正式版本） （32 位）
PC14寸，分辨率1080P，缩放150%

### Vue version
2.5.13

### Reproduction Link
http://element-cn.eleme.io/2.0/#/zh-CN/component/table

### Steps to reproduce
设置最右侧的列 fixed="right"

### What is Expected?
固定列能显示完全

### What is actually happening?
固定列未显示完全

**Comment by yinjunonly** [comment]
#### 系统及bug示例图如下链接：
[http://www.toway.asia:8090/upload/images/1516172728250-TIM%E5%9B%BE%E7%89%8720180117150429.png](url)

[http://www.toway.asia:8090/upload/images/1516172730844-TIM%E5%9B%BE%E7%89%8720180117150435.png](url)

**Comment by yinjunonly** [comment]
#### System Settings and bug screenshot below link：
http://www.toway.asia:8090/upload/images/1516172728250-TIM%E5%9B%BE%E7%89%8720180117150429.png

http://www.toway.asia:8090/upload/images/1516172730844-TIM%E5%9B%BE%E7%89%8720180117150435.png

**Comment by furybean** [comment]
@yinjunonly 麻烦确认下 2.1.0 是否仍有此问题。

**Comment by yinjunonly** [comment]
@furybean 你好，2.2.1仍有此问题。

**Comment by yinjunonly** [comment]
@furybean 你好，问题解决了！那我关闭了
