### ISSUE TITLE
[Bug Report] Table selection-change event

### ISSUE THREAD

**Issue by yanchongsheng** [ElemeFE/element#9314]
### Element UI version
2.0.11

### OS/Browsers version
Windows7/chrom

### Vue version
2.5.13

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN](https://elementui.github.io/issue-generator/#/zh-CN)

### Steps to reproduce
```JavaScript
data() {
	return{
		showList: [],	//这个list是后端返回的一个对象List 
		selectedList: []
	}
}
//methods						
handleSelectionChange(val) {
    this.selectedList = val;
},
async deleteObject() {
	for (let item of selectedList) {
		console.table(this.selectedList);  //循环的最后一次，selectedList的length会少1
		let index = this.showList.indexOf(item);
                this.showList.splice(index, 1);
	}
}
```
### What is Expected?
不管循环多少次，selectedList的length都不会变

### What is actually happening?
循环的最后一次，selectedList的length会少1

**Comment by furybean** [comment]
是有点问题，你可以先这么绕过去：
```JavaScript
handleSelectionChange(val) {
   this.selectedList = (val || []).concat();
}
```
