### ISSUE TITLE
[Bug Report] auto-complete in dialog z-index incorrect

### ISSUE THREAD

**Issue by chenyiqiao** [ElemeFE/element#9315]
### Element UI version
2.0.11

### OS/Browsers version
Windows 7 / latest Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/chen1qiao_/13psjvcL/3/](https://jsfiddle.net/chen1qiao_/13psjvcL/3/)

### Steps to reproduce
1. open dialog
2. input 'a'
3. select the 'aaa' item
4. click 'close'
5. open dialog again
6. input 'a'

### What is Expected?
auto-complete-suggestion z-index bigger than dialog no matter what.

### What is actually happening?
auto-complete-suggestion is not gonna show up because it's behind the dialog(z-index) now.

**Comment by Leopoldthecoder** [comment]
Fixed in #9339
