### ISSUE TITLE
[Bug Report] should don't fold the table row with 'expand-row-keys' attribute when data update 

### ISSUE THREAD

**Issue by huanguolin** [ElemeFE/element#9317]
### Element UI version
2.0.11

### OS/Browsers version
windows 7 (32 bit) / Chrome 61.0.3163.79 

### Vue version
2.5.13

### Reproduction Link
[https://codepen.io/alvinhuang/pen/rpqzXr?editors=1010](https://codepen.io/alvinhuang/pen/rpqzXr?editors=1010)

### Steps to reproduce
1. expand one row
2. click 'update data' button, you will see the row fold

### What is Expected?
should don't fold the row 

### What is actually happening?
table folded the row

**Comment by dhlong8555a** [comment]
遇到同样问题
