### ISSUE TITLE
[Feature Request] NavMenu collapsed and the menu-item wrapped in custom component can show tooltip

### ISSUE THREAD

**Issue by xiaoyanhao** [ElemeFE/element#9328]
### Element UI version
2.0.11

### OS/Browsers version
Windows 7 / Chrome 63.0.3239.132（64 bits）

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xiaoyanhao/pkfq64gt/](https://jsfiddle.net/xiaoyanhao/pkfq64gt/)

### Steps to reproduce
1. click "收起"
2. hover the last menu item

### What is Expected?
the last menu item display a tooltip

### What is actually happening?
the last menu item display no tooltip

**Comment by Leopoldthecoder** [comment]
#9343
