### ISSUE TITLE
[Feature Request] Can setCurrentNode/setCurrentKey focus?

### ISSUE THREAD

**Issue by Glenfiddish** [ElemeFE/element#9330]
### Existing Component
Yes

### Component Name
el-tree

### Description
 setCurrentNode/setCurrentKey choose correctly but never focus

**Comment by baiyaaaaa** [comment]
Please give a detailed description of your requirement and the usage scenario

**Comment by Glenfiddish** [comment]
- when setCurrentNode/setCurrentKey call it wont focus on current selected node
- another getCurrentNode return only data of node, would you ruturn with  node? it would helpful for tree-node operate

**Comment by ziyoung** [comment]
@Glenfiddish sorry, we have no plan to support it.

**Comment by dielangsea** [comment]
这个是很常见的需求，圈子太小了额
