### ISSUE TITLE
Message component centered vertically

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9331]
### Existing Component
Yes

### Component Name
Message

### Description
How the Message component is centered vertically or arbitrarily in the page.

**Comment by furybean** [comment]
[Message](http://element-cn.eleme.io/#/zh-CN/component/message) 从设计角度上看就是显示在页面顶部。

如果你需要全局居中显示，你可以通过覆盖 `.el-message` 的样式来实现。
