### ISSUE TITLE
[Feature Request] Whether the sub-option of the tree component can add slot

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9332]
### Existing Component
Yes

### Component Name
tree

### Description
Whether the sub-option of the tree component can add slot?

**Comment by furybean** [comment]
如果你指的是自定义节点内容，请参考 render-content 属性的用法。

**Comment by fengyun2** [comment]
@furybean 不可以提供一种slot的方式么？

**Comment by fengyun2** [comment]
@furybean 主要是jsx方式，扩展tree组件时，v-model不好操作。
