### ISSUE TITLE
Can the form component (el-input, el-select, etc.) add an asterisk（*） to a form option without defining the rules rule?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9333]
### Existing Component
Yes

### Component Name
form

### Description
Can the form component (el-input, el-select, etc.) add an asterisk（*） to a form option without defining the rules rule?

**Comment by furybean** [comment]
看不懂这个问题，请用中文描述一下，并简单介绍下使用场景。

**Comment by fengyun2** [comment]
form表单组件中的el-input、el-select组件没有添加验证规则(rules)时，有没办法添加星号(*)在它们前面呢？

**Comment by furybean** [comment]
@fengyun2 直接使用 form-item 的 required 属性就可以。
