### ISSUE TITLE
wants form-item to support span form support for row features

### ISSUE THREAD

**Issue by lichenhao** [ElemeFE/element#9334]
### Existing Component
是

### Component Name
el-form,el-form-item

### Description
利用row col能力可以将表单项合并单行多输入。充分使用空间，为复杂表单优化展示。

**Comment by furybean** [comment]
form-item 本身不处理布局相关，你应该使用 `el-col` `el-row` 来实现这种功能。

**Comment by lichenhao** [comment]
但这样会增加嵌套层级，而form的容器本身并没有因为增加行、列限制而破坏form本身的能力~

**Comment by lichenhao** [comment]
我说的是增加 行、列能力 并不会破坏 form本身的能力（提交，定义默认行为等）

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.
