### ISSUE TITLE
[Bug Report] select list jitter

### ISSUE THREAD

**Issue by ferozyj** [ElemeFE/element#9338]
### Element UI version
2.0.11

### OS/Browsers version
Chrome 63.0.3239.108

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
element官网 select中的基础多选 选多个后输入框高度变化 开始抖动（Chrome）

### What is Expected?
正常显示

### What is actually happening?
element官网 select中的基础多选 选多个后输入框高度变化 开始抖动（Chrome）

**Comment by Leopoldthecoder** [comment]
官网的例子在 Mac 上无法复现，先写一个有问题的 demo 备忘：https://jsfiddle.net/pd7zco1j/ 。待修。

**Comment by ferozyj** [comment]
![2018-01-18_14-28-37](https://user-images.githubusercontent.com/29189291/35083907-463f03b2-fc5c-11e7-953f-dc2a2c6b0e95.gif)

**Comment by maoyuyang** [comment]
应该是页面缩放比例不同造成的

**Comment by troy351** [comment]
赞同 @maoyuyang 观点。同样的环境下并不会抖动，调整Chrome缩放为110%时发生抖动

**Comment by ferozyj** [comment]
@maoyuyang @troy351 确实如此 谢谢！

**Comment by zhanghuohuo1996** [comment]
@maoyuyang 
添加样式
  .el-select__input {
    vertical-align: baseline;
  }
解决这类bug

**Comment by 52linyuepeng** [comment]
在 windows 下会有这个问题
经过一些测试 baseline 还是有问题, top 更加
```css
.el-select__input {
   vertical-align: top;
}
```

**Comment by JuneDeng2014** [comment]
@52linyuepeng 这样还是不行的。

**Comment by myNameCao** [comment]
如果size  赋值 就不会出现啦

**Comment by FrontendStack** [comment]
> 如果size 赋值 就不会出现了

问题解决了吗

**Comment by FrontendStack** [comment]
> 如果size 赋值 就不会出现了

问题解决了吗
