### ISSUE TITLE
How to combine tab components with Tooltip components for mouse movements Tab Tips

### ISSUE THREAD

**Issue by dweep119** [ElemeFE/element#9342]
### Element UI version
1.4.1

### OS/Browsers version
Ubuntu 16.04 / Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xngx7hh8/](https://jsfiddle.net/xngx7hh8/)

### Steps to reproduce
In given Reproduction link, when mouse hover on tab it change the text color and shows the clear icon.
Now you just need to add Tooltip option on mouse hover.
I want to use Tab component and Tooltip component together.
If client hover the tabpane label it shows the tooltip like, Sublime and Atom Editor do.

### What is Expected?
I want to use Tab component and Tooltip component together.
If client hover the tabpane label it shows the tooltip like, Sublime and Atom Editor.

### What is actually happening?
Right now I am not able to use Tooltip component in Tab component.

**Comment by ngopal1995** [comment]
@element-bot .... _Fiddle_ seems to be working for me..
![issue1](https://user-images.githubusercontent.com/15034669/35109863-803de182-fc9d-11e7-8f96-219ab1728be6.PNG)

**Comment by ngopal1995** [comment]
@dweep119  It seems that elements which are dynamically generated based on data cannot be nested within another component like `<el-tooltip>`. Looking for a solution myself

**Comment by furybean** [comment]
Tabs provide scoped slot `label`, Just put `el-tooltip` in the slot. A demo here: https://jsfiddle.net/xngx7hh8/2/

**Comment by dweep119** [comment]
Yeah It works for me.
Thanks @furybean.
