### ISSUE TITLE
[Feature Request] inputNumber empty value problem

### ISSUE THREAD

**Issue by mengyubo** [ElemeFE/element#9344]
### Existing Component
是

### Component Name
inputNumber

### Description
如果我用了inputNumber控件，那么这个值就会产生一个默认值0，如果我清空了inputNumber的value，那么希望得到一个null，因为这个选项不是必输项，用户不确定这个值到底应该填写什么。
界面上的值是0和空对用户来说产生的误解会很大，虽然这个是number控件，但是number类型的数据库字段是允许输入null的，至少希望开辟一个新的属性，来支持这个需求。

**Comment by baiyaaaaa** [comment]
we will attempt to support the value `undefined` when the input value is ''.

**Comment by zhangbing3** [comment]
> we will attempt to support the value `undefined` when the input value is empty.

but, it is warning Propety or method is not defined.
vue.runtime.esm.js?2b0e:619 [Vue warn]: Property or method "minValue" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
