### ISSUE TITLE
[Bug Report] Parsing error Unexpected character

### ISSUE THREAD

**Issue by paygle** [ElemeFE/element#9345]
### Element UI version
2.0.11

### OS/Browsers version
window 10  chrome 63

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
使用 npm  install  安装完成后， 执行npm run dist 报错（npm run dist:all 同样报错）如下：

C:\Users\dodar\Desktop\element-dev\packages\theme-chalk\src\alert.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\dodar\Desktop\element-dev\packages\theme-chalk\src\aside.scss
  1:1  error  Parsing error: Unexpected character '@'
......

✖ 83 problems (83 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-ui@2.0.11 lint: `eslint src/**/* test/**/* packages/**/* build/**/* --quiet`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@2.0.11 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dodar\AppData\Roaming\npm-cache\_logs\2018-01-18T09_31_02_083Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-ui@2.0.11 dist: `npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:umd && npm run build:theme`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@2.0.11 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dodar\AppData\Roaming\npm-cache\_logs\2018-01-18T09_31_02_118Z-debug.log

### What is Expected?
修复错误

### What is actually happening?
修复错误

**Comment by Leopoldthecoder** [comment]
删除 node_modules，改为用 yarn 安装依赖。

**Comment by paygle** [comment]
我删除了 node_modules，改为用 yarn 安装依赖。结果一样

**Comment by Leopoldthecoder** [comment]
试试在 .eslintignore 里加上 `*.scss`

**Comment by paygle** [comment]
在 .eslintignore 里加上 
```txt
*.scss 
*.ttf
*.woff
```
结果正常，但执行 npm run dist:all 时出现以下代码
```txt
[cooking@1.5.4] - info
    Asset     Size  Chunks             Chunk Names
    index.js  10.5 kB       0  [emitted]  index
       [0] external {"root":"Vue","commonjs":"vue","commonjs2":"vue","amd":"vue"} 42 bytes {0} [not cacheable]
......
```
不知是否正常，如果正常就没问题了
