### ISSUE TITLE
[Feature Request] Optimization of total functional performance of table components

### ISSUE THREAD

**Issue by chouxiaozi** [ElemeFE/element#9348]
### Existing Component
是

### Component Name
el-table

### Description
表格组件计算合计数据（summaryMethod）方法，能不能只运算一次。大概测试了一下好像重复得执行5次

**Comment by furybean** [comment]
@Leopoldthecoder 感觉这个问题应该一并解决了？

**Comment by Leopoldthecoder** [comment]
经验证 #9426 已修复此问题。
