### ISSUE TITLE
[Bug Report] el-select, long text label is pushed out of select element 

### ISSUE THREAD

**Issue by shridhar18** [ElemeFE/element#9351]
### Element UI version
2.0.8

### OS/Browsers version
All

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/tpttmjuq/3/](https://jsfiddle.net/tpttmjuq/3/)

### Steps to reproduce
1. Select longer text option

### What is Expected?
Long text label should not be pushed out of select element. it should have some thing like ellipsis 

### What is actually happening?
long text label is pushed out of select element

**Comment by Leopoldthecoder** [comment]
See #9352

**Comment by shridhar18** [comment]
Thanks for you help. it resolves the partial problem. I was asking is there
any way to restrict the height of the select element. It gets stretched if
enter long text. This increase row in the grid

[image: Inline image 1]

**Comment by shridhar18** [comment]
(multiple collapse-tags filterable)
https://jsfiddle.net/tpttmjuq/9/
https://jsfiddle.net/tpttmjuq/10/

We are using the select component in table component where each row height
is fixed and column width and height are fixed. we are looking for
solution, keeping the height and width of select component fixed.
The issue with the solution (https://jsfiddle.net/tpttmjuq/9/) is, entering
text results in more height of select component.
The issue with the solution (https://jsfiddle.net/tpttmjuq/10/) is, we have
fixed column size in the table. We can't increase the width of select
component more than certain width size.

Any better solution will be appreciated.

On Fri, Jan 19, 2018 at 12:37 PM, Shridhar Prasad <shridhar.prasad@gmail.com
> wrote:

> Thanks for you help. it resolves the partial problem. I was asking is
> there any way to restrict the height of the select element. It gets
> stretched if enter long text. This increase row in the grid
>
> [image: Inline image 1]
>
