### ISSUE TITLE
[Bug Report] Expandable table row with fixed table columns

### ISSUE THREAD

**Issue by jiayexie** [ElemeFE/element#9353]
### Element UI version
2.0.10

### OS/Browsers version
Windows 10 / Chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/184/](https://jsfiddle.net/mmx38qxw/184/)

### Steps to reproduce
Expand a table row. The expanded div has 100% percent width, but the highlight on hover only shows up on the left fixed columns.

### What is Expected?
When I hover over the expanded section, I should see the highlight throughout the row.

### What is actually happening?
When I hover over the expanded section, the highlight only shows up for the fixed columns, i.e. left half of the expanded section.
![image](https://user-images.githubusercontent.com/1333389/35128567-2cc6d63e-fc6c-11e7-958f-f80a04266a4a.png)

**[UPDATE in 
[https://jsfiddle.net/mmx38qxw/185/](https://jsfiddle.net/mmx38qxw/185/)]** Also, if there are too many columns that I need to do horizontal scrolling, the expanded component has the right side scrolling with the columns, so it looks like it's cut in two pieces:

![image](https://user-images.githubusercontent.com/1333389/35132616-ea9f1fc2-fc80-11e7-961a-fcb809a69e36.png)

**Comment by ngopal1995** [comment]
@jiayexie Can you check again if the fiddle is complete. It is only showing an input box.

**Comment by jiayexie** [comment]
@ngopal1995 Thank you! I just updated the fiddle link.

**Comment by jiayexie** [comment]
@furybean Thanks for taking it so promptly! I just updated the description and fiddler with another issue in this scenario. Thanks in advance for your effort!
