### ISSUE TITLE
Why does the background style of [Feature Request] el-menu, el-submenu, el-menu-item and other sidebar components not be defined by class, but now they are all in line styles. How should they be globally covered?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9354]
### Existing Component
是

### Component Name
menu

### Description
el-menu、el-submenu、el-menu-item 等侧边栏组件的背景样式为何不是通过class来定义，目前都是行内样式，该如何全局覆盖呢？

**Comment by Leopoldthecoder** [comment]
默认情况下就是通过 class 定义的，只有指定了 `background-color`、`text-color`、`active-text-color` 时才是行内的。
