### ISSUE TITLE
 [Bug Report] There is no strict alignment in the pagination

### ISSUE THREAD

**Issue by lianmt** [ElemeFE/element#9356]
### Element UI version
2.0.11

### OS/Browsers version
win7/chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/lianmingtang/jwx6adsu/](https://jsfiddle.net/lianmingtang/jwx6adsu/)

### Steps to reproduce
分页中间没有严格对齐，相差1px很纠结

### What is Expected?
分页中间没有严格对齐，相差1px很纠结

### What is actually happening?
分页中间没有严格对齐，相差1px很纠结

**Comment by Leopoldthecoder** [comment]
没看出哪里相差了 1px，请截图说明。
