### ISSUE TITLE
table组件同时开启合计和固定列时，当滚动表格时串行

### ISSUE THREAD

**Issue by xy985626** [ElemeFE/element#9359]
table组件同时开启表尾合计行（show-summary=true），固定列 <el-table-column fixed></el-table-column>时，当数据记录条目很多（超出表格高度）需要滚动时，所有固定列的最后一行数据无法显示，同时非固定列（最后一行可以显示）可以继续向上滚动一行，造成固定列与非固定列串行。

**Comment by jayzch** [comment]
居然被无情忽视了
