### ISSUE TITLE
dialog 和 级联选择器  el-cascader   组合 ，下拉选项被遮挡， z-index 问题

### ISSUE THREAD

**Issue by flouda** [ElemeFE/element#9360]
版本    "element-ui": "^1.4.12",

重现场景，
 1.el-dialog   里 嵌套表单el-form
 2.表单里嵌套el-cascader  
 3.下拉时，菜单被dialog遮挡

之前看到Issue列表里，dialog和select组合 有此类问题且已修复。
是因为z-index  dialog和select设置一致导致的。

但是当前1.4.12版本似乎没有修复此问题

![image](https://user-images.githubusercontent.com/3071113/35139964-6120dbea-fd30-11e7-9ee0-5b351dde41fa.png)

![image](https://user-images.githubusercontent.com/3071113/35139991-752d3f16-fd30-11e7-842e-37b3f01fc013.png)

**Comment by chenyi5266** [comment]
和你一样，只不过我的是dialog中的select，我更新到最新版本也不行，

**Comment by my9074** [comment]
+1

**Comment by gypjoy** [comment]
请问下，你们有解决方案了吗？
