### ISSUE TITLE
How to set the "z-index" of "v-loading"

### ISSUE THREAD

**Issue by Yangfan2016** [ElemeFE/element#9369]
How to set the "z-index" of "v-loading", Because of overflow the others special element (e.g. the top element of page)

**Comment by Yangfan2016** [comment]
Unfriendly

**Comment by ngopal1995** [comment]
@Yangfan2016 Hi ...
You need to submit through [issue-generator](https://elementui.github.io/issue-generator/#/en-US) to ensure fast resolves.

> Please remember that your issue being closed does not mean we don't respect your problem. An issue conforming to our requirements saves time and helps us locate the real problem more precisely. More info can be found at the issue generator page.
