### ISSUE TITLE
表单中存在datepicker时的校验问题

### ISSUE THREAD

**Issue by tangshiping** [ElemeFE/element#937]
### ElementUI version

1.0.0-rc.9

### OS/Browers version

macOS/Chrome 53

### Vue version

2.0.5

### Steps to reproduce

直接使用示例中表单校验的代码: http://element.eleme.io/#/component/form

代码中对date1设置初值，如new Date()

先点击“重置”，再点击“立即创建”

### What is Expected?

表单中的其它项会提示校验错误

### What is actually happening?

校验会停在date1处，后面的项不会提示校验, 查看console信息：

```
Uncaught TypeError: value.getTime is not a function(…)
  date @ date.js?d7d3:28
```

**Comment by liule1988** [comment]
这个问题并没有修复啊

**Comment by liule1988** [comment]
代码中对date1设置初值为string时，表单提交时，依然会停在此处，并且报错：value.getTime is not a function

**Comment by qiuyaofan** [comment]
我也遇到问题了，直接给date验证设置type="date",初始值转换为时间类型，比如new Date(value)再赋值给表单

**Comment by ShawshankLin** [comment]
我设置了type="date"也没有用
