### ISSUE TITLE
[Feature Request] Add static row id to sortable table rows.

### ISSUE THREAD

**Issue by dan2600** [ElemeFE/element#9374]
### Existing Component
Yes

### Component Name
el-table

### Description
In a table without sorting you can easily use the table row's index to reference it's data in a custom function. However, sorting breaks this because the index of the row changes with it's order. It would be nice for sortable el-tables to have a static row id to reference the row. The workaround for now is adding an index to to the table's data object and then referencing row.index in the custom function. 

example
https://jsfiddle.net/0jutbL7s/5/

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. You can expose the row object instead of its index to custom functions. https://jsfiddle.net/leopoldthecuber/0jutbL7s/6/
