### ISSUE TITLE
[Bug Report] Browser Auto-fill with filterable el-select

### ISSUE THREAD

**Issue by SquareBeard** [ElemeFE/element#9376]
### Element UI version
2.0.11

### OS/Browsers version
Chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/245/)

### Steps to reproduce
You need Chrome Auto-fill to be enabled and some data in it that might auto fill a field on your form.
If that field is a "el-input" or a filterable "el-select", when you start typing, it will trigger the browser auto-fill system.

### What is Expected?
In the case of a "el-select", the auto-fill feature should not be activated.

### What is actually happening?
The dropdown menu of the auto-fill feature covers the "el-select" dropdown menu.

![image](https://user-images.githubusercontent.com/5481247/35195644-f2149d48-fec6-11e7-8328-797c41002490.png)

There is an autocomplete="off" attribute on the input element but this does not work in modern browser anymore (See https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164 for reference). It seems that you need to set the autocomplete to an unknown value like "false".
"false" works for me on regular el-input fields where you can set the auto-complete prop. But I can't do it on el-select elements.

**Comment by wacky6** [comment]
Hi, your jsfiddle is empty

**Comment by Leopoldthecoder** [comment]
Looks like adding `autocomplete` on Select can fix this.

**Comment by SquareBeard** [comment]
Indeed, that would work.
