### ISSUE TITLE
El-select is used in [Bug Report] el-dialog, which can be remotely searched. When ref controls opening, it can get focus. But when ESC is closed, it will take two times to close.

### ISSUE THREAD

**Issue by 1008611** [ElemeFE/element#9378]
### Element UI version
2.0.9

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/C__C/7zvydcgo/](https://jsfiddle.net/C__C/7zvydcgo/)

### Steps to reproduce
打开dialog，自动获取焦点。键盘 esc，需要按两次。

### What is Expected?
希望可以esc 直接关闭

### What is actually happening?
先失去焦点，然后才关闭。

**Comment by Leopoldthecoder** [comment]
This is not a bug. Pressing ESC on Select will unfocus itself, and `stopPropagation` is called on the event.

**Comment by 1008611** [comment]
我要实现 esc直接关闭，该如何处理呢
