### ISSUE TITLE
The [Bug Report] [Bug Report] upload component cannot be dynamically modified in before-upload

### ISSUE THREAD

**Issue by 286506460** [ElemeFE/element#9381]
### Element UI version
2.0.11

### OS/Browsers version
Chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/Lfaosg6h/](https://jsfiddle.net/Lfaosg6h/)

### Steps to reproduce
在upload组件的before upload钩子中修改action上传地址，当前文件上传地址没有变化，再一次上传action才变化
<img width="1262" alt="1" src="https://user-images.githubusercontent.com/7390249/35204909-46958e54-ff6c-11e7-90ab-346cf6351084.png">
<img width="1253" alt="2" src="https://user-images.githubusercontent.com/7390249/35204911-49830dd0-ff6c-11e7-9b2b-cd389b518639.png">

### What is Expected?
在before upload钩子中修改action，并让当前文件按新地址上传

### What is actually happening?
当前文件依旧按旧地址上传，再次上传文件，action才是修改后的新地址

**Comment by Hi-Linlin** [comment]
你好，你可以这样解决:
https://jsfiddle.net/Lfaosg6h/3/

组件设计时，并不考虑改变原始值。 并且Vue的一些机制导致了这个问题，具体可以看这个例子:
https://jsfiddle.net/leopoldthecuber/Lfaosg6h/2/

**Comment by 286506460** [comment]
@Hi-Linlin 感谢你的解决方案

**Comment by isuye** [comment]
链接失效了,遇到这个问题了,能麻烦再放下链接么,谢谢

**Comment by 286506460** [comment]
@isuye  
```
<el-upload class="upload-demo" :action="url" :before-upload="test">
  <el-button size="small" type="primary">点击上传</el-button>
</el-upload>
var Main = {
    data () {
      return {
        url: '123'
      };
    },
    methods: {
      test (file) {
        return new Promise((resolve, reject) => {
          this.$nextTick(() => {
            this.url = '321'        
            resolve()
          })
        })
      }
    }
  }
```

**Comment by isuye** [comment]
@286506460 
谢谢

**Comment by jim888666** [comment]
链接打不开？？？

**Comment by DaiChongyu** [comment]
@286506460 你这个方法我试了不行的

**Comment by DaiChongyu** [comment]
@286506460 请问为啥我用了你这个方法还是不行？
![image](https://user-images.githubusercontent.com/22912524/70368566-34c41880-18e7-11ea-9cf2-a3b7d454ec26.png)
![image](https://user-images.githubusercontent.com/22912524/70368569-41487100-18e7-11ea-982e-5b1cafc2bbbf.png)
![image](https://user-images.githubusercontent.com/22912524/70368572-4e656000-18e7-11ea-8721-928cdef81a3c.png)
![image](https://user-images.githubusercontent.com/22912524/70368575-5a512200-18e7-11ea-80dd-0fa66a529a72.png)
这是为什么？

**Comment by 286506460** [comment]
@DaiChongyu this.Api = 321

**Comment by DaiChongyu** [comment]
@286506460 不好意思，刚图截错地方了，这个是正确的位置
![image](https://user-images.githubusercontent.com/22912524/70368911-d3eb0f00-18eb-11ea-83da-d883e50a92c7.png)

**Comment by LeiYuBoGitHub** [comment]
```
data: {
                url: ''
            },
            mounted: function() {
                this.changeUrl();
            },
            methods: {
                changeUrl: function () {
                    this.$nextTick(() => {
                        this.url = '321';
                    })
                },
            }
```

放到 mounted 里可以避免第一次不改变, 我这是引入模式 changeUrl函数放到其他函数里依然会导致第二次才能改变成功
