### ISSUE TITLE
[Feature Request] Suggestion box of el-autocomplete tag can't set it's width.

### ISSUE THREAD

**Issue by duotai** [ElemeFE/element#9389]
### Existing Component
是

### Component Name
el-autocomplete

### Description
Suggestion box of el-autocomplete tag can't set it's width.  the suggestion box can't be set itself width.

**Comment by duotai** [comment]
el-autocomplete 这个标签的建议框体, 建议框体的宽度无法进行单独设置.求开放能够单独设置.

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/9orLxL2o/ 用 CSS 覆盖即可。
