### ISSUE TITLE
[Bug Report] There is a short flash when NavMenu collapses or expands in IE11

### ISSUE THREAD

**Issue by xiaoyanhao** [ElemeFE/element#9394]
### Element UI version
2.0.11

### OS/Browsers version
Windows 7 / IE 11

### Vue version
2.5.13

### Reproduction Link
[http://element-cn.eleme.io/#/zh-CN/component/menu#zhe-die](http://element-cn.eleme.io/#/zh-CN/component/menu#zhe-die)

### Steps to reproduce
Keep toggling the NavMenu in native IE11.

### What is Expected?
Smooth collapse and expansion.

### What is actually happening?
NavMenu is shaking.

**Comment by baiyaaaaa** [comment]
I can not reproduce this problem

**Comment by Leopoldthecoder** [comment]
能否提供动图？

**Comment by xiaoyanhao** [comment]
![qq20180223-212301](https://user-images.githubusercontent.com/9431557/36596377-809c4e5c-18e0-11e8-9af6-9ae057ebd5a2.gif)

**Comment by 2256184693** [comment]
收起的时候为何没有动画

**Comment by shmy** [comment]
同样的问题
