### ISSUE TITLE
[Bug Report] ElSelect validation triggers for change failed

### ISSUE THREAD

**Issue by w-rudolph** [ElemeFE/element#9396]
### Element UI version
2.0.11

### OS/Browsers version
Chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/29656310/1/](https://jsfiddle.net/29656310/1/)

### Steps to reproduce
Click "validation" button, error displayed;
Click "Set a value" button but the error is still displayed；

### What is Expected?
Error should be not displayed

### What is actually happening?
Error is still displayed, i remember element-ui@1.x is OK

**Comment by wacky6** [comment]
Since 2.0, only user input will trigger change event and validation.

**Comment by Leopoldthecoder** [comment]
@w-rudolph Please check out the `Breaking changes` section on the 2.0.0 changelog.
