### ISSUE TITLE
[Bug Report] The input component is unable to accept the Vue v-on:input modifier

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#9397]
### Element UI version
2.0.11

### OS/Browsers version
 Chrome 53, Safari 11

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/evolutionjay/ve9zrc2e/](https://jsfiddle.net/evolutionjay/ve9zrc2e/)

### Steps to reproduce
有3个输入框.
第一个正常.
第二个和第三个输入框在输入的时候可以在 console 面板看到错误

### What is Expected?
支持 v-on:input 的所有修饰符.
因为 v-model 无法完成预期效果, 例如通过  :value 获取 store 计算函数, 然后 通过 v-on:input 去commit  store  修改参数  , 避免 v-model 死循环计算.

### What is actually happening?
支持 v-on:input 的所有修饰符.

**Comment by wacky6** [comment]
修饰符只能在原生input使用

**Comment by Leopoldthecoder** [comment]
You should listen to the native `input` event instead: https://jsfiddle.net/leopoldthecuber/ve9zrc2e/1/ , although I don't think the `trim` modifier can work with events.

**Comment by evolutionjay** [comment]
那起码以配置的形式给吧? 直接就关了真是的...

**Comment by Leopoldthecoder** [comment]
什么叫「以配置的形式给」？

**Comment by evolutionjay** [comment]
例如 Input Attributes 增加
trim = true | false
lazy
