### ISSUE TITLE
table: 鼠标滑过该行加背景色

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#940]
### ElementUI version
1.0.0-rc.9

### OS/Browers version
windows/Chrome 54

### Vue version
2.0.5

### Steps to reproduce
表格鼠标滑过即可复现，官网演示正常，实际使用不正常
### What is Expected?
当从第一行滑动到表头上时，第一行的背景色消失
### What is actually happening?
第一行背景色依然存在，当鼠标滑出表格区域或滑入到其它表格行上时消失

**Comment by QingWei-Li** [comment]
测试正常 http://jsfiddle.net/cinwell_li/6oj4n6wg/
请给一份可复现问题的 demo

**Comment by topul** [comment]
@QingWei-Li 线上无法重现，我再看下是否本地问题，先关闭了
