### ISSUE TITLE
[Bug Report] dialog component mask layer displays exceptions

### ISSUE THREAD

**Issue by ywwhack** [ElemeFE/element#9400]
### Element UI version
2.0.11

### OS/Browsers version
macOS10.13.2 / chrome63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/efxnLn1j/](https://jsfiddle.net/efxnLn1j/)

### Steps to reproduce
1. 点击打开 Dialog

### What is Expected?
dialog 出现在 modal 遮罩层之上

### What is actually happening?
dialog 出现在 modal 遮罩层之下

**Comment by Leopoldthecoder** [comment]
对于这样一个结构：
```html
<div style="z-index: 1" id="a">
  <div style="z-index: 1000" id="b"></div>
</div>

<div style="z-index: 2" id="c"></div>
```

`#b` 是在 `#c` 后面的。所以出现了 demo 里的情况。

解决方法有两种：
- Dialog 移出 header
- Dialog 加上 `append-to-body` 属性
