### ISSUE TITLE
[Feature Request] input autocomplete associative input

### ISSUE THREAD

**Issue by 3winscom** [ElemeFE/element#9406]
### Existing Component
Yes

### Component Name
input  autocomplete

### Description
能否限一个属性来限定输入多少个字符之后，再弹出下拉框。

**Comment by Hi-Linlin** [comment]
`
      querySearch(queryString, cb) {
        const validLen = 3;
        if (queryString.length < validLen) {
          cb([]);
          return;
        }
        var restaurants = this.restaurants;
        var results = queryString ? restaurants.filter(this.createFilter(queryString)) : restaurants;
        cb(results);
      }

`
