### ISSUE TITLE
Dialog上的Form在Dialog关闭时并没有重置验证

### ISSUE THREAD

**Issue by erguotou520** [ElemeFE/element#941]
### Reproduction Link
![dialog-validate](https://cloud.githubusercontent.com/assets/7945757/20129756/1c598b74-a68d-11e6-8e05-ec4f2845f12b.gif)

**Comment by Leopoldthecoder** [comment]
MessageBox 的 `prompt` 会重置验证状态，Dialog 不会重置。因为 Dialog 的内容完全是自定义的。可以在 `close` 回调中做这件事。

**Comment by erguotou520** [comment]
说的也对。。。
