### ISSUE TITLE
[Bug Report] sets the bug of isLeaf

### ISSUE THREAD

**Issue by ayiaq1** [ElemeFE/element#9412]
### Element UI version
2.0.11

### OS/Browsers version
win10/ Chrome62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/v5gs1xgw/](https://jsfiddle.net/v5gs1xgw/)

### Steps to reproduce
设置 isLeaf=‘leaf’
props: {
label: 'name',
children: 'zones',
isLeaf: 'leaf'
}
对数据写入：leaf: false
应该是没有子叶节点

### What is Expected?
对数据写入：leaf: false
应该是没有子叶节点

### What is actually happening?
按照正常理解 leaf=false应该没有三角形图标，leaf=true表示有子级应该展现三角形图标
![1](https://user-images.githubusercontent.com/3860498/35253525-d7837a2a-0020-11e8-97d3-9f12e35f09f9.jpg)

**Comment by Leopoldthecoder** [comment]
`leaf` 是你自己定义的 `isLeaf` 的别名。`isLeaf` 的含义是是否为叶子节点，为 `true` 的话就代表没有子节点，不显示三角图标，反之则显示。

**Comment by ayiaq1** [comment]
但是我在demo里面写 leaf =false应该不显示吧？ 
![image](https://user-images.githubusercontent.com/3860498/35470316-1d38b72e-0382-11e8-8f2a-d243452c0ea1.png)
