### ISSUE TITLE
[Feature Request] uses the el-slider list generated by the for loop to obtain the index of the current el-slider

### ISSUE THREAD

**Issue by rolitter** [ElemeFE/element#9420]
### Existing Component
是

### Component Name
el-slider

### Description
我的业务逻辑需要的el-slider 是for循环生成的,当el-slider改变的时候,我希望获取当前的index和value,但是element只提供value,没有提供当前index.
![image](https://user-images.githubusercontent.com/27326998/35261335-abbce82a-004a-11e8-9e36-ff39719de4aa.png)

**Comment by furybean** [comment]
使用 v-for 提高的 index：`<li v-for="(item, index) in items">`

**Comment by Hi-Linlin** [comment]
https://jsfiddle.net/hkz2b0Lr/1/

你好，可以这样
