### ISSUE TITLE
[Bug Report]  When uses the remote search function of el-select, the el-option position is shifted upwards when the search box is opened second times

### ISSUE THREAD

**Issue by 1008611** [ElemeFE/element#9427]
### Element UI version
2.0.11

### OS/Browsers version
Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/C__C/7zvydcgo/   我使用的是自己的服务器接口请求数据，暂无链接](https://jsfiddle.net/C__C/7zvydcgo/   我使用的是自己的服务器接口请求数据，暂无链接)

### Steps to reproduce
el-dialog中嵌套了一个 el-select进行远程搜索。
第一次打开进行搜索时候，搜索结果的列表位置显示正常。
```
el-select-dropdown el-popper
element.style {
    transform-origin: center top 0px;
    z-index: 2021;
    min-width: 420px;
    position: fixed;
    top: 234px;
    left: 250px;
}
第二次打开时候，历史记录的列表向上偏移
element.style {
    transform-origin: center top 0px;
    z-index: 2021;
    min-width: 420px;
    position: fixed;
    top: 214px;
    left: 250px;
}
top向上偏移了20px
```

### What is Expected?
希望top值固定，不要上移

### What is actually happening?
top向上偏移了20px

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/35274437-06a36dfa-0077-11e8-818b-93d23131e0a6.gif)

未能重现，多次打开下拉框位置一致。

**Comment by Hi-Linlin** [comment]
https://jsfiddle.net/7zvydcgo/4/

**Comment by 1008611** [comment]
这个是问题1，像这样  ![3](https://user-images.githubusercontent.com/13185839/35308968-1cd0e116-00e5-11e8-8708-76b277d5d72f.gif)

**Comment by 1008611** [comment]
@Leopoldthecoder  问题2，像这样
![4](https://user-images.githubusercontent.com/13185839/35309188-16fcae7c-00e6-11e8-8968-783bfcbd698a.gif)

**Comment by Leopoldthecoder** [comment]
第一个问题已经在 #9339 解决，请等待下次发布。
