### ISSUE TITLE
[Bug Report] The.Focus of DatePicker (type: daterange) is invalid

### ISSUE THREAD

**Issue by KumaCool** [ElemeFE/element#9430]
### Element UI version
2.0.11

### OS/Browsers version
macOS 10.12.6 / chrome 63.0.3239.132

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/KumaCool/7dz5v6Lj/](https://jsfiddle.net/KumaCool/7dz5v6Lj/)

### Steps to reproduce
`this.$refs.datePicker.focus()`
不知道是否是这样使用?
日期选择器(范围类型)
我无法通过外部触发该行为.但其它的类似组件是可用的.

### What is Expected?
可从外部触发.focus()行为.

### What is actually happening?
无法触发.focus行为.

**Comment by wacky6** [comment]
daterange有两个输入框，所以不能这么用。你可以试试直接focus到其中一个input。

**Comment by Hi-Linlin** [comment]
Duplicate of #9437
