### ISSUE TITLE
[Bug Report] Datepicker input element has a empty attribute "id"

### ISSUE THREAD

**Issue by Yangfan2016** [ElemeFE/element#9434]
### Element UI version
2.0.11

### OS/Browsers version
Win10 x64/ Chrome/63.0.3239.132 

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/247/](https://jsfiddle.net/mmx38qxw/247/)

### Steps to reproduce
打开控制台，出现如下错误
Found 2 elements with non-unique id #: (More info: https://goo.gl/9p2vKq)

### What is Expected?
不要加空的 id 属性

### What is actually happening?
加了空的 id 属性

**Comment by Hi-Linlin** [comment]
没太明白意思，控制台没有看到任何报错信息。

**Comment by Leopoldthecoder** [comment]
Duplicate of #8907

**Comment by Yangfan2016** [comment]
Thx
