### ISSUE TITLE
[Bug Report] table show-overflow-tooltip is still can 't work sometimes in IE

### ISSUE THREAD

**Issue by haogjin** [ElemeFE/element#9439]
### Element UI version
2.0.11

### OS/Browsers version
win10  IE11

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element/issues/9136](https://github.com/ElemeFE/element/issues/9136)

### Steps to reproduce
show-overflow-tool can not show in IE when it  within limits,but if  I change the screen ,it can show
在一定宽度的时候show-overflow-tool 不显示，但改变屏幕大小又可以显示，频繁出现

### What is Expected?
show-overflow-tool can  show in any case

### What is actually happening?
show-overflow-tool can not show in IE when it  within limits

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
