### ISSUE TITLE
[Feature Request] Issue with Radio display the'label'of prop

### ISSUE THREAD

**Issue by Luichooy** [ElemeFE/element#9440]
### Existing Component
是

### Component Name
Radio

### Description
When not giving a default slot to the radio, the default value of the radio would instead be displaying the prop of the label. Could it be possible to simply leave the default as empty instead of displaying the prop of the label, and provide an option to use the prop of the label but not using it as the default.

当没有给Radio组件提供子元素（slot）时，Radio组件默认会在 class="el-radio__label"的标签中显示label的值，希望取消这一默认行为，或者提供接口让用户决定在没有slot时，是否开启上述默认行为

**Comment by Hi-Linlin** [comment]
你好，这个特性是从初期就开始保留到现在的，我们目前还不打算提供接口去控制，希望你能理解。

虽然不知道你的使用场景是怎样的，但是目前可以这样达到目的:
  <el-radio v-model="radio" label="1">&nbsp;</el-radio>

**Comment by anrananran** [comment]
@Hi-Linlin 版本2.14.1 添加 &nbsp; 无效
