### ISSUE TITLE
 [Bug Report]  In the use of the template in the el-table component, the content of the template is inexplicable many times

### ISSUE THREAD

**Issue by sweetXiaoyan** [ElemeFE/element#9455]
### Element UI version
1.4.13

### OS/Browsers version
chorme  63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xiaoxiao_1/3Lj77kbj/](https://jsfiddle.net/xiaoxiao_1/3Lj77kbj/)

### Steps to reproduce
1. 在上面的例子中，加了一个 v-if 判断，该函数中的打印操作会执行很多次；所有当表格数据量比较大的时候，渲染就会很慢，不知道是不是这里的原因。

### What is Expected?
解决数据量大的情况下不会出现卡顿的现象，

### What is actually happening?
目前测试几百条数据会有卡顿现象

**Comment by furybean** [comment]
2.1.0 中此问题已修复，可以查看此示例：https://jsfiddle.net/3Lj77kbj/1/
