### ISSUE TITLE
The [Bug Report] time range selection is repeated after the two panels will be repeated

### ISSUE THREAD

**Issue by wonderFF** [ElemeFE/element#9458]
### Element UI version
2.0.11

### OS/Browsers version
osx chrome56

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/ajeambau/1/](https://jsfiddle.net/ajeambau/1/)

### Steps to reproduce
点击时间面板 选择 同一月份的两天， 再次激活下拉时间面板， 发现两个面板会重复

### What is Expected?
可以判断是否为同一月份的两天， 如果是同一月份的两天， 左面板显示当前， 右面板默认显示下一个月

### What is actually happening?
如果当前为同一月份的两天， 左右面板会重复， 点击面板上的  `<    <<     >>     >`  是无法实现两个面板显示同一内容的

**Comment by Hi-Linlin** [comment]
你好，感谢你的反馈，已修复。 #9471
