### ISSUE TITLE
[Tabs]希望为Tab-pane增加closable属性

### ISSUE THREAD

**Issue by francisfeng** [ElemeFE/element#946]
当前版本（1.0.0-rc.8）只能在 Tabs 上设置`closable`属性，所有的子项目 Tab-pane 要么都可以关闭，要么都不可以。

但在某些场景里，需要有可以被删除的，也有不可以被删除的项目。比如系统自带的 Tab-pane 和用户自行创建的 Tab-pane。

**Comment by newlife** [comment]
是的，希望增加这个功能
