### ISSUE TITLE
When [Feature Request] sets the value value of select, if there is this item in the data, it displays the corresponding label. If not, it displays the value of value, which should be displayed as empty or palceholder.

### ISSUE THREAD

**Issue by renlixin** [ElemeFE/element#9460]
### Existing Component
Yes

### Component Name
2.0.11

### Description
版本 63.0.3239.132（正式版本） （64 位）
demo地址：https://jsfiddle.net/5ps479w7/3/

**Comment by Hi-Linlin** [comment]
你好，你的使用场景是怎样的呢？ 为什么不把value的初始值设为 null 或者 '' ?

**Comment by qingdengyue** [comment]
设置为empty,在多项的时候会出现多个empty,可能更加困惑(还以为都是一模一样)，显示value,能及时确定绑定错误，以便重新调整其他的值。
