### ISSUE TITLE
[Bug Report] Loading component can't  be closed

### ISSUE THREAD

**Issue by Eysarh** [ElemeFE/element#9461]
### Element UI version
2.0.11

### OS/Browsers version
 windows10/ firefox 58.0 && firefox 57.0

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/ffexec/ay5qawe9/](https://jsfiddle.net/ffexec/ay5qawe9/)

### Steps to reproduce
create a loading component, and immediately invoke "close()" function.

### What is Expected?
the loading component have been closed after invokied "close()" function

### What is actually happening?
the loading component can't be closed

**Comment by Eysarh** [comment]
If wait a moment, the "close()" have  effected close component.

**Comment by Hi-Linlin** [comment]
hi, you can do this:

      this.$nextTick(() => {
        loading.close()
      })


https://jsfiddle.net/ay5qawe9/1/
