### ISSUE TITLE
How does the [Feature Request] dialog component and the message-box component operate in the vuex?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9472]
### Existing Component
是

### Component Name
dialog、message-box

### Description
dialog组件和message-box组件如何在vuex中操作关闭？

**Comment by Leopoldthecoder** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。

**Comment by rugor** [comment]
I am also figuring this out. I want to open the dialog using state in vuex because the dialog will be used (triggered) by many different button components. I have made an [example](https://codepen.io/rugor/pen/rJdPMK/) and understand the open and close events on the dialog, but how to open it from state in the store?

**Comment by rugor** [comment]
Listening for `@open` & `@close` events are not necessarily needed when using a setter for the computed state in vuex like so: 

```
// in the store
const state = {
  modalOpen: false
}

const mutations = {
  UPDATE_MODAL(state, value) {
    state.modalOpen = value
  }
}

const actions = {
  updateModal({ commit }, value) {
    commit('UPDATE_MODAL', value)
  }
}

const getters = {
  getModal: state => {
    return state.modalOpen
  }
}
```

```
// in component with modal
computed: {
  modal: {
    get() {
      return this.$store.getters.getModal
    },
    set(value) {
      this.$store.dispatch('updateModal', value)
    }
  }
}
```


```
// in template
<el-dialog :visible.sync="modal">
```

**Comment by fengyun2** [comment]
@rugor Click 'Open from store` no response.

**Comment by rugor** [comment]
[For you](https://codepen.io/rugor/pen/YejWRG) @fengyun2
