### ISSUE TITLE
[Bug Report] inputNumber - default value for "min" prop is not being applied

### ISSUE THREAD

**Issue by badcom** [ElemeFE/element#9473]
### Element UI version
2.0.11

### OS/Browsers version
Chrome 64.0.3282.119 (latest version)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/gmve9d3p/217/](https://jsfiddle.net/gmve9d3p/217/)

### Steps to reproduce
Add inputNumber element without the "min" prop.

### What is Expected?
"-" button should be disabled

### What is actually happening?
"-" button is enabled and the value changes to -1

**Comment by wacky6** [comment]
What do you mean? Why should not change to -1

**Comment by badcom** [comment]
Because the documentation states that the default value is 0, therefore the min value should be 0.

**Comment by wacky6** [comment]
@Leopoldthecoder 

Code says `-Infinity` to `+Infinity`. Which is correct, doc or code?

**Comment by Hi-Linlin** [comment]
HI，fixed #9479. THX!
