### ISSUE TITLE
element ui 远程搜索选择器 一直按back键报错

### ISSUE THREAD

**Issue by yapeili** [ElemeFE/element#9477]
element-ui.common.js?5820:7958 Uncaught TypeError: value.pop is not a function
    at VueComponent.deletePrevTag (element-ui.common.js?5820:7958)
    at Proxy.boundFn (vue.common.js?62e1:192)
    at _c.on.keydown (element-ui.common.js?5820:8577)
    at invoker (vue.common.js?62e1:2002)
    at HTMLInputElement.fn._withTask.fn._withTask (vue.common.js?62e1:1804)

**Comment by MssText** [comment]
> element-ui.common.js?5820:7958 Uncaught TypeError: value.pop is not a function at VueComponent.deletePrevTag (element-ui.common.js?5820:7958) at Proxy.boundFn (vue.common.js?62e1:192) at _c.on.keydown (element-ui.common.js?5820:8577) at invoker (vue.common.js?62e1:2002) at HTMLInputElement.fn._withTask.fn._withTask (vue.common.js?62e1:1804)

老哥解决没 我也遇到这个问题

**Comment by syLi95** [comment]
> > element-ui.common.js?5820:7958 Uncaught TypeError: value.pop is not a function at VueComponent.deletePrevTag (element-ui.common.js?5820:7958) at Proxy.boundFn (vue.common.js?62e1:192) at _c.on.keydown (element-ui.common.js?5820:8577) at invoker (vue.common.js?62e1:2002) at HTMLInputElement.fn._withTask.fn._withTask (vue.common.js?62e1:1804)
> 
> 老哥解决没 我也遇到这个问题

我也遇到同样的问题？请问有解决方法吗？

**Comment by syLi95** [comment]
> > element-ui.common.js?5820:7958 Uncaught TypeError: value.pop is not a function at VueComponent.deletePrevTag (element-ui.common.js?5820:7958) at Proxy.boundFn (vue.common.js?62e1:192) at _c.on.keydown (element-ui.common.js?5820:8577) at invoker (vue.common.js?62e1:2002) at HTMLInputElement.fn._withTask.fn._withTask (vue.common.js?62e1:1804)
> 
> 老哥解决没 我也遇到这个问题

@MssText 我也遇到同样的问题？请问有解决方法吗？
