### ISSUE TITLE
[Bug Report] "el-date-picker" 选择日期会比选择的时间少一天

### ISSUE THREAD

**Issue by fabin5** [ElemeFE/element#9481]
### Element UI version
2.0.11

### OS/Browsers version
windows7/chrome60

### Vue version
2.2.1

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、选择一个时间范围
2、输出选择的时间范围，绑定的value中的两个值

### What is Expected?
选择的正确的时间范围

### What is actually happening?
比选择的时间早一天（开始时间和结束时间都会早一天）

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/35423265-e33228c6-0287-11e8-8381-9482e04f1b2e.png)

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by fabin5** [comment]
谢谢
