### ISSUE TITLE
[Bug Report] Select drop-down arrowhead position error

### ISSUE THREAD

**Issue by coolzjy** [ElemeFE/element#9484]
### Element UI version
2.0.11

### OS/Browsers version
MacOS 10.13.2 / Chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/252/](https://jsfiddle.net/mmx38qxw/252/)

### Steps to reproduce
-

### What is Expected?
下拉框箭头位置正确

### What is actually happening?
下拉框箭头位置错误

**Comment by Leopoldthecoder** [comment]
Fixed in #9309 and will be shipped in the next release.
