### ISSUE TITLE
[Bug Report] is placed in the autocomplete remote search input box in Dialog, and then open after the dialog is closed, and the current box is covered by dialog

### ISSUE THREAD

**Issue by hearain** [ElemeFE/element#9487]
### Element UI version
2.0.11

### OS/Browsers version
windows 10 / chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/34uc24s9/#embed](https://jsfiddle.net/34uc24s9/#embed)

### Steps to reproduce
1、将autocomplete远程搜索输入框放在Dialog组件中  
2、autocomplete为激活出发搜索结果  
3、触发结果后直接点击遮罩处，关闭dialog，此时搜索结果也会被关闭  
4、再次打开dialog，激活autocomplete输入框，其返回的下拉菜单偶现被dialog组件覆盖的情况。  
并且，在激活autocomplete结果之后，将鼠标点击浏览器地址栏或者调试工具里的输入框，让autocomplete失去焦点，此时下拉结果不会被清空，之后点击dialog的遮罩处关闭dialog，此时autocomplete会再次触发一次fetch-suggestions。再次打开dialog激活autocomplete搜索结果，有很大概率下拉框到dialog下面

### What is Expected?
autocomplete丢失焦点后关闭dialog不应该触发fetch-suggestions，并且autocomplete的下拉框不应该被dialog遮盖

### What is actually happening?
autocomplete丢失焦点后关闭dialog触发fetch-suggestions，再次打开dialog，autocomplete的下拉框被dialog遮盖

![bug1](https://user-images.githubusercontent.com/9176349/35430037-869af5be-02b1-11e8-9cbf-98c7ddae6540.gif)

**Comment by yanxiafu** [comment]
el-menu 多级导航异步获取数据后在生成的子路由，在这些子路由里面刷新导航不展开 改成不用异步获取数据生成的（写死的路由）可以 展开，用了default-active 子路由元素有is-active但是没有is-opened ，这里面default-openeds添加了也不起作用,  感觉只有直接写的路由或者直接的定死data刷新能展开，动态获取数据后刷新就展不开了，刷新 只能展开一开始定死的data，怎么破

**Comment by Hi-Linlin** [comment]
#9339  遮挡的问题已经修了，下个版本将一起发布。

**Comment by hearain** [comment]
OK, this issue closed
