### ISSUE TITLE
[Feature Request] with icon's input box input cannot be controlled

### ISSUE THREAD

**Issue by 8283792** [ElemeFE/element#9489]
### Existing Component
是

### Component Name
Input

### Description
在使用带 icon 的输入框时，通过组件渲染出来的input框样式无法控制，比如是个用户名框，左边的图标样式控制font-size变大后右边的input框padding无法控制，导致图标覆盖到了右边的input框上。

**Comment by Leopoldthecoder** [comment]
这是 Bug Report，不是 Feature Request。请不要因为不想写 demo 就选择 Feature Request。
