### ISSUE TITLE
[Bug Report] el-select, multiple collapse-tags filterable, entering longer text in input to filter,  el-select height gets increased.

### ISSUE THREAD

**Issue by shridhar18** [ElemeFE/element#9493]
### Element UI version
2.0.8

### OS/Browsers version
All

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/w8k1dcpr/1/](https://jsfiddle.net/w8k1dcpr/1/)

### Steps to reproduce
1. Select long text first from the option list 
2. Enter by typing any other text option available from the option list

### What is Expected?
1. Height and width of el-select element should not be changed

### What is actually happening?
el-select height is increased

**Comment by Leopoldthecoder** [comment]
You should set the Select with a bigger width: https://jsfiddle.net/leopoldthecuber/w8k1dcpr/2/ , otherwise there'd be no space in the same line to put the filter input box.
