### ISSUE TITLE
[Bug Report] Different font sizes on form placeholders

### ISSUE THREAD

**Issue by fungl164** [ElemeFE/element#9496]
### Element UI version
1.4.13

### OS/Browsers version
Version 63.0.3239.132 (Official Build) (64-bit)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/fungl164/cfdz9pmd/](https://jsfiddle.net/fungl164/cfdz9pmd/)

### Steps to reproduce
Run fiddle

### What is Expected?
The TextArea font to be of the same size

### What is actually happening?
Larger font is displayed

**Comment by Hi-Linlin** [comment]
![1517060255018](https://user-images.githubusercontent.com/24927385/35472455-5e3ab5ce-03aa-11e8-896c-232cc1bf1337.jpg)

**Comment by fungl164** [comment]
@Hi-Linlin Thnxs!  I am able to set the size via css this way...
```CSS
.el-textarea__inner::placeholder 
  font-size: 12px
```
It seems that it can be fixed via code perhaps as a props property (e.g. size), but I am not sure if this is deliberate or just a plain oversight...many thnxs!
