### ISSUE TITLE
[Feature Request] Validation rules to be triggered on form submit

### ISSUE THREAD

**Issue by ahalimkara** [ElemeFE/element#9497]
### Existing Component
Yes

### Component Name
el-form, el-form-item

### Description
I would like to run validation rules only on form submit. This is the default behavior for Chrome and Mozilla, from [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-required):

> This attribute specifies that the user must fill in a value before submitting a form.

**Comment by Leopoldthecoder** [comment]
This can be done by setting `trigger` to something other than `blur` and `change` (like `submit` if you want): https://jsfiddle.net/leopoldthecuber/hbknoub4/ .
