### ISSUE TITLE
[Feature Request] Using "el-select-dropdown el-popper is-multiple" as checkbox group

### ISSUE THREAD

**Issue by fungl164** [ElemeFE/element#9500]
### Existing Component
Yes

### Component Name
Multiple Select Dropdown (to be used as Checkbox Group)

### Description
Am trying to figure out if it is possible to use a ```multiple select dropdown``` as a component so that it can be triggered by say a ```button``` and act as a ```checkbox group```. 

I'm trying to avoid displaying the chosen ```tags``` and just use the ```dropdown``` with checkmarks as the driver for the user selection(s).  Any help or ideas on how to do this with the current implementation are highly welcomed! Thnxs!

**Comment by Leopoldthecoder** [comment]
Perhaps you can do something like this: https://jsfiddle.net/leopoldthecuber/hqpgcke7/

**Comment by kylesean** [comment]
@Leopoldthecoder What about in loop? If button replaced by checkbox，and checkbox is like Array，Could you show a demo?Thanks any way!
