### ISSUE TITLE
Layout container not rendered properly in IE11

### ISSUE THREAD

**Issue by VinceBassman** [ElemeFE/element#9505]
### Element UI version
2.0.11

### OS/Browsers version
Internet Explorer 11

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/2wduenvL/](https://jsfiddle.net/2wduenvL/)

### Steps to reproduce
Just open the element-ui online documentation and then open the container component. Most of the containers are not rendered correctly in Internet Explorer 11.

### What is Expected?
Correct rendering of the containers like in Chrome or Firefox.

### What is actually happening?
1. Main section is mostly not shown
2. Header/Footer overlapped

**Comment by qingdengyue** [comment]
Fix: #9620
