### ISSUE TITLE
[Bug Report] element-theme et error

### ISSUE THREAD

**Issue by BusyHe** [ElemeFE/element#9506]
### Element UI version
1.4.13

### OS/Browsers version
centos 6

### Vue version
2.5.13

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
npm install element-theme -g 后执行 et报错
Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/element-theme/node_modules/node-sass/vendor'

### What is Expected?
希望改近

### What is actually happening?
改进

**Comment by Leopoldthecoder** [comment]
先把 usr/local/lib/node_modules/element-theme 移除，然后重新安装试一下（确保安装没有报错）。

**Comment by BusyHe** [comment]
@Leopoldthecoder 恩，确实报错了，node-sass
