### ISSUE TITLE
[Feature Request] Add to step element @click

### ISSUE THREAD

**Issue by ar53n** [ElemeFE/element#9507]
### Existing Component
Yes

### Component Name
Steps

### Description
Will be good addition to `el-step` `@click` event for navigation between steps or other different uses this event

**Comment by Leopoldthecoder** [comment]
Just add `@click.native` on `<el-step>`.

**Comment by ar53n** [comment]
@Leopoldthecoder but I can't pass any params

**Comment by Leopoldthecoder** [comment]
```html
<el-step v-for="i in 5" @click.native="e => clickHandler(e, i)">
```
