### ISSUE TITLE
[Bug Report]table show-overflow-tooltip still can't work  in IE and Firefox

### ISSUE THREAD

**Issue by haogjin** [ElemeFE/element#9509]
### Element UI version
2.0.11

### OS/Browsers version
win10   IE/firefox

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/6L2vL94y/7/](https://jsfiddle.net/6L2vL94y/7/)

### Steps to reproduce
之前有存在在IE和火狐下el-table show-overflow-tooltip属性有的显示不了的情况，在2.0.11版本更新日志中显示已修复，但仍然存在问题。
1、打开链接（建议直接在火狐浏览器中打开，IE有可能打不开）
2、表格中“地区”这一列有设置show-overflow-tooltip，改变屏幕大小，将地区这一列的数据缩小到显示为中国-广东省-深圳市-福...或者“中国-北京市-东城...”的位置，show-overflow-tooltip不会显示，改变成其他屏幕大小之后又可以显示。

### What is Expected?
不同的屏幕大小下show-overflow-tooltip都显示

### What is actually happening?
一定宽度的屏幕大小下show-overflow-tooltip不显示

**Comment by Leopoldthecoder** [comment]
Duplicate of #5049. The 2.0.11 changelog refers to another style bug of tooltip.
