### ISSUE TITLE
[Bug Report] with icon's input box input cannot be controlled

### ISSUE THREAD

**Issue by 8283792** [ElemeFE/element#9510]
### Element UI version
2.0.11

### OS/Browsers version
win7

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/nbhoqLtf/](https://jsfiddle.net/nbhoqLtf/)

### Steps to reproduce
按业务需求放大组件，icon可以变化，但是input框无法改变

### What is Expected?
希望增加input的距离icon的距离可控

### What is actually happening?
按业务需求放大组件，icon可以变化，但是input框无法改变

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/nbhoqLtf/1/ CSS 优先级问题。

**Comment by 8283792** [comment]
thanks
