### ISSUE TITLE
When can the Table of [Feature Request] ElementUI support TreeTable

### ISSUE THREAD

**Issue by SeasonGuo** [ElemeFE/element#9512]
### Existing Component
是

### Component Name
Table

### Description
ElementUI的Table组件有支持树型组件的打算吗？我有一些树型的结构的table数据需要处理，虽然自己可以写一个Table，但是却要重写ElementUI的树型结构。。。。

**Comment by Leopoldthecoder** [comment]
抱歉，近期没有支持 TreeTable 的计划。

**Comment by SeasonGuo** [comment]
有没有好的扩展方法推荐的。
