### ISSUE TITLE
How does [Feature Request] hide or display a line of data in Table?

### ISSUE THREAD

**Issue by SeasonGuo** [ElemeFE/element#9517]
### Existing Component
是

### Component Name
Table

### Description
当我做了某一个操作，我怎样隐藏与之相关的其他的行的数据，我找了找api没找到相关的接口方法。

**Comment by Leopoldthecoder** [comment]
操作原数据就行。

**Comment by SeasonGuo** [comment]
您是说直接删除元数据的？

**Comment by freedomdebug** [comment]
操作元数据不是我想要的，例如我本地要维护一份离线数据，最后做form的submit，当前我只是想隐藏部分row的数据，修改了元数据，submit的最后数据就丢失了
