### ISSUE TITLE
The [Bug Report] V-for generated el-table-column changes the order of the array to try not to trigger the update, and div is available

### ISSUE THREAD

**Issue by javaSwing** [ElemeFE/element#9518]
### Element UI version
1.4.13

### OS/Browsers version
all brower 

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/javaSwing/12v7bhhu/](https://jsfiddle.net/javaSwing/12v7bhhu/)

### Steps to reproduce
https://jsfiddle.net/javaSwing/12v7bhhu/

### What is Expected?
数组改变顺序后，试图能进行对应的改变

### What is actually happening?
无论怎么改变数据的顺序，sort，reverse之后，视图都没有改变

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/12v7bhhu/2/ key 给错了。对于每一列，在 reverse 前后的 `item.id` 是一样的，不会触发渲染。

**Comment by javaSwing** [comment]
@Leopoldthecoder 如果给的是index我对应列的formatter方法会，在原来列的位置起作用，比如我第3列是格式化money显示的，把他换到第8列，新的第3列会调用原来的formatter
请麻烦看下，我问了很多人也没有办法：
https://jsfiddle.net/javaSwing/qyks3qfm/2/#

**Comment by javaSwing** [comment]
@Leopoldthecoder 非常感谢大佬的回答！
