### ISSUE TITLE
el-select会自动把不存在对应option的value设置成undefined？

### ISSUE THREAD

**Issue by nivekz** [ElemeFE/element#952]
### ElementUI version
1.0.0-rc.9

### Vue version
2.0.1

### What is actually happening?

hello，我在看#875 同样的问题。我们的el-select的value和里面的el-option都是异步请求获得的。如果在el-select的value赋值时，el-option还没准备好，那么value就会被控件设置成undefined。

请问这个自动把不存在option的value变成undefined是一个feature吗？如果是的话，以上场景要如何处理，有没有推荐的方法？谢谢！

另外：我们尝试过一个hack，就是在赋值value的时候，如果option不存在，创建一个对应的option foo。但是当实际option被赋值的时候，界面上显示的还是旧的foo的label。

**Comment by Leopoldthecoder** [comment]
是的，Select 目前的实现不支持把 value 赋值为一个不存在的 option，不过后面会考虑支持。

不知道你的业务逻辑是否可以实现在 option 获取完毕后再获取 value，如果可以的话，这样是最方便的。你提到的 hack 应该也可行，关于「界面上显示的还是旧的 foo 的 label」，请确认 Element 的版本是 rc.9 或 1.0.0；如果还有这个问题，请提供一个可以复现的在线 demo。

**Comment by nivekz** [comment]
关于上面说的hack不能用的示例: https://jsfiddle.net/Lp6e6nm0/1/

**Comment by Leopoldthecoder** [comment]
@nivekz https://jsfiddle.net/leopoldthecuber/jLrxj7re/
在 `el-option` 里加上 `key` 就可以了。详细原因看这里：https://github.com/ElemeFE/element/issues/576

**Comment by nivekz** [comment]
谢谢回复。请问这里为什么要把key设置成label的值，而不是value的值？另一方面，在http://element.eleme.io/#/component/select#yuan-cheng-sou-suo 的例子里，key 设置的是value。不是很理解，求解释，谢谢！

**Comment by Leopoldthecoder** [comment]
原因其实在那个 issue 里已经说了，就是你的 `key` 在 `items` 变化前后也得是唯一的。你的例子里，`items` 变化前后的 `value` 没有变，而 `label` 变了，所以在这里需要把 `label` 当作 `key`。官方例子里其实 `label` 或者 `value` 都可以。

后面会考虑看看能不能绕过去。

**Comment by nivekz** [comment]
谢谢解释和指针！关于`vuejs`对于`key`这块的逻辑远离我还在理解中。。

同时我发现html的 `select` 和 `option` 貌似不需要`key` 也没有问题（见https://jsfiddle.net/hpnq20f1/ ）。请问 `el-select` 在这点上不一样是设计如此，还是有希望可以统一成 html 的情况？

**Comment by Leopoldthecoder** [comment]
@nivekz 是的，原生的 `option` 没有这个问题。「`v-for` 渲染的 `el-option` 需要 `key`」并不是设计的初衷，我后面会想办法。

**Comment by nivekz** [comment]
上述问题单独提了 #974 跟踪

**Comment by Leopoldthecoder** [comment]
这个 issue 先关掉了，有进展会在 #974 中反馈。
