### ISSUE TITLE
[Bug Report] table 组件 append slot 新增的dom 在tbody 外导致样式错乱，不能和上面的table联动

### ISSUE THREAD

**Issue by liubaiye** [ElemeFE/element#9523]
### Element UI version
2.0.11

### OS/Browsers version
Browser Version

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/p305uxz9/1/](https://jsfiddle.net/p305uxz9/1/)

### Steps to reproduce
暂无

### What is Expected?
希望能重现1.4版本

### What is actually happening?
样式发生错误，是否需要手动调式，还是我书写组件的方式问题

**Comment by Leopoldthecoder** [comment]
`append` slot 的设计初衷并不是让用户加入更多的表格行。它适合放入与表格无关的其他组件，比如对于无限滚动的需求，可以把加载时的图标放在 `append` slot 里。

这是 2.0 的一个非兼容更新，目前没有计划对它进行改动。
