### ISSUE TITLE
[Bug Report] table scroll bar bug

### ISSUE THREAD

**Issue by lujunpeng** [ElemeFE/element#9525]
### Element UI version
2.0.11

### OS/Browsers version
谷歌浏览器

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/lujunpeng/pnnjwyob/](https://jsfiddle.net/lujunpeng/pnnjwyob/)

### Steps to reproduce
table头部和尾部固定 设定最大高度，出现纵向滚动条  改变table的宽度，横向滚动条刚刚出现的时候样式有bug 滚动条会把table中间的挤上去

### What is Expected?
table中间部分没有被滚动条挤上去

### What is actually happening?
table中间部分被滚动条挤上去

**Comment by furybean** [comment]
@lujunpeng 2.1.0 已经无法重现此问题：https://jsfiddle.net/pnnjwyob/3/ ，麻烦抽空确认下。

**Comment by lujunpeng** [comment]
最新版本已经改好了 @furybean
