### ISSUE TITLE
After the [Bug Report] table-column is reordered with the V-for, the column's formatter will continue to execute the original column

### ISSUE THREAD

**Issue by javaSwing** [ElemeFE/element#9526]
### Element UI version
1.4.13

### OS/Browsers version
all brower

### Vue version
2.1.10

### Reproduction Link
[https://jsfiddle.net/javaSwing/qyks3qfm/4/](https://jsfiddle.net/javaSwing/qyks3qfm/4/)

### Steps to reproduce
https://jsfiddle.net/javaSwing/qyks3qfm/4/

### What is Expected?
视图进行重新渲染后，对应的formatter方法应当跟随列改变位置

### What is actually happening?
列的位置已经进行改变，对应的formatter方法，还在原来位置继续执行

**Comment by Leopoldthecoder** [comment]
已在之前的 issue 里回复。

**Comment by javaSwing** [comment]
@Leopoldthecoder 这并不是同一个问题，我这次问的是formatter问题！不是说排序的问题！
