### ISSUE TITLE
[Bug Report] submenu not visible in folding state if parent aside is folded too

### ISSUE THREAD

**Issue by derAndreas** [ElemeFE/element#9527]
### Element UI version
2.0.11

### OS/Browsers version
linux / chome 63 / firefox 58

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/tg45ao2s/2/](https://jsfiddle.net/tg45ao2s/2/)

### Steps to reproduce
1. collapse the side menu (default state)
2. hover over first item in the menu
3. submenu is not visible (should appear right to the menu item)
4. expand menu and open "navigation one" to see that there are submenu items

### What is Expected?
the submenu items should be rendered on top 

### What is actually happening?
- submenu is not visible
- `el-main` is on top of the submenu

### notes
- not sure if issue title explains it well, please edit if there is a better one
- tried to play with position properties and z-index, but I am not a CSS hero :(

**Comment by derAndreas** [comment]
Hi,

quick update: Found a workaround, but don't know if this a valid solution.
On the `el-aside` use `overflow: visible` and the menu appears

Demo: https://jsfiddle.net/tg45ao2s/3/

Would be nice if someone can confirm that this is the right way to do it.
Thanks in advance.

**Comment by Leopoldthecoder** [comment]
Current, yes, you can add `overflow: visible` to `<el-aside>`.

In the next release we'll insert the submenu to body, so this issue will no longer exist.
