### ISSUE TITLE
[Bug Report] el-select in el-dialog could not get right value when declare

### ISSUE THREAD

**Issue by lhldyf** [ElemeFE/element#9531]
### Element UI version
1.4.13

### OS/Browsers version
chrome  60.0.3112.90

### Vue version
2.5.13

### Reproduction Link
[https://github.com/lhldyf/SpringBootVue/blob/master/frontend/src/page/user/ModifyForm.vue](https://github.com/lhldyf/SpringBootVue/blob/master/frontend/src/page/user/ModifyForm.vue)

### Steps to reproduce
git clone https://github.com/lhldyf/SpringBootVue
cd frontend
npm install
npm run dev

open link:http://localhost:8012/#/user

click '修改', try to modify the value of sex

### What is Expected?
when i click the label '女', the select label will change to '女'

### What is actually happening?
when i click the label '女', the select label not change,bug i reopen the dialog, it change to '女'

another way, declare 'sex' as normal varible, not a computed varible, it works well.

**Comment by Leopoldthecoder** [comment]
Computed properties don't work this way. In this case, you need to use `value` and `@input` instead of `v-model`.

**Comment by lhldyf** [comment]
I try to use `value` and `@input` but failed, so i'm eager to learn how to fix by ur way. please help me.
I fix this by `watch` on the other way, declare the form in `data`, watch the `computed` variable and set the value of the form, code like this, which i think is inconvenient:

```
<el-form-item label="性别">
  <el-select v-model="modifyForm.sex">
	<el-option v-for="item in sexOptions"
			   :key="item.value"
			   :label="item.label"
			   :value="item.value" >
	</el-option>
  </el-select>
</el-form-item>

data() {
  return {
	sexOptions: USER.SEX_OPTIONS,
	modifyForm: {
	  sex: null
	}
  }
},

computed: {
  ...mapState('user', {
	visible: state => state.visibleDialog === USER.DIALOG.MODIFY,
	modifyData: 'modifyData'
  })
},


watch: {
  modifyData: function(val) {
	this.modifyForm = {...val};
  }
}
```
