### ISSUE TITLE
[Feature Request] Colorpicker: Real time update when choosing color

### ISSUE THREAD

**Issue by jvandop** [ElemeFE/element#9539]
### Existing Component
Yes

### Component Name
Colorpicker

### Description
Currently, the value of v-model of the colorpicker only updates when you press the 'Ok' button in the colordialog.
I would like to see the v-model gets updated instantly when selecting a color in the colorpalette (realtime when moving my mouse over the colorpalette)

**Comment by Leopoldthecoder** [comment]
You can do this using the `active-change` event: https://jsfiddle.net/leopoldthecuber/dn5j4wt0/ .
