### ISSUE TITLE
In [Bug Report] el-table-column, icon is rendered through render-table, click icon to come out el-popover window, set up the width window, the first time the location is wrong, no location is right.

### ISSUE THREAD

**Issue by carrollcai** [ElemeFE/element#9548]
### Element UI version
1.4.13

### OS/Browsers version
chrome52

### Vue version
2.3.0

### Reproduction Link
[https://github.com/ElemeFE/element/issues/9547](https://github.com/ElemeFE/element/issues/9547)

### Steps to reproduce
exceptionRender(createElement) {
      return createElement(ExceptionRateTable, {
        props: {
          actInfoItem: this.activityItems[this.itemTabsValue],
          infoItem: this.activityItems[this.itemTabsValue].lottyConfigList
        }
      })
    },

<el-popover ref="popover5" placement="top" trigger="click" width="800">
			<div style="padding: 8px;">
				<div class="exc-title">例外概率详情</div>
</div>
		</el-popover>
		中奖概率
		<i style="margin-left: 4px;color: #82D1FF;" v-popover:popover5 class="icon-probability" @click="tran"></i>

### What is Expected?
el-popover设置了宽度之后，el-popover位置偏移

### What is actually happening?
el-popover设置了宽度之后，第一次el-popover弹窗位置偏移，第二次是好的。

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
