### ISSUE TITLE
Elementui Upload fileList icon error

### ISSUE THREAD

**Issue by Attax** [ElemeFE/element#9550]
I'm sorry to write here rather than using issue-generator.because I have no way to show you a demo link here cause the upload api is private.

## Element UI version
2.0.11

## OS/Browsers version
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

Vue version
2.5.13

## Reproduction Link
sorry 

## Steps to reproduce
upload some **large files**,when http connect was **pending**,the progress bar was not showing,and the **filelist icon** was green checkmark

## What is Expected?
upload some files,when http conncet was pending ,showing the progress bar or dont make the filelist icon green checkmark.

## What is actually happening?
the progress bar was not showing,and the filelist icon was green checkmark.it makes users feels that the upload was complete but it didn't.

[reproduce img](https://imgur.com/a/vNHH4)

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/35552330-721bae7e-05ce-11e8-940f-6c014254e807.png)

I couldn't reproduce it.
