### ISSUE TITLE
[Bug Report] IE 9 select, checkbox icon misplacement

### ISSUE THREAD

**Issue by JasonGaoG** [ElemeFE/element#9555]
### Element UI version
1.4.13

### OS/Browsers version
win7/IE9

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/256/](https://jsfiddle.net/mmx38qxw/256/)

### Steps to reproduce
用ie9打开,查看 select和checkbox 图标

### What is Expected?
select位置，checkbox勾选图形正常

### What is actually happening?
用ie9打开，select 位置异常，checkbox 图标显示异常。
![image](https://user-images.githubusercontent.com/3345724/35553318-5d094be6-05d2-11e8-9552-f90888258b4d.png)
![image](https://user-images.githubusercontent.com/3345724/35553331-6a6fa15e-05d2-11e8-8858-c1fd25c0976f.png)

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/35565622-3a34402c-05f9-11e8-87a6-94bfdc189982.png)

Sorry, Element is not compatible with IE9.

**Comment by JasonGaoG** [comment]
![image](https://user-images.githubusercontent.com/3345724/35600377-8e119d06-0668-11e8-9134-35a2f5e5139f.png)

https://github.com/ElemeFE/element/tree/1.x
1.x also not supports IE9+ now ?

**Comment by Leopoldthecoder** [comment]
1.x is no longer maintained.
