### ISSUE TITLE
Upload 控件上传问题

### ISSUE THREAD

**Issue by DevilLeven** [ElemeFE/element#956]
### ElementUI version
1.0.0 

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.0-rc.4

```
<el-upload
  action="//jsonplaceholder.typicode.com/posts/"
  type="drag"
  :multiple="true"
  :on-preview="handlePreview"
  :on-remove="handleRemove"
  :on-success="handleSuccess"
  :on-error="handleError"
>
```
1上传控件 type=drag 并且 multiple="true" 选择多个文件同时上传，上传的文件将在下方显示上传进度 ，但是当上传成功后，下面文件显示消失了，只留下最后一个上传成功的文件。
2文件上传过程中不可以删除文件，停止上传，但是当文件上传成功后却可以删除，不懂为何要这样设计

**Comment by kangwenyun** [comment]
action参数是“上传的地址”，这个“上传的地址”是选择要上传的文件的地址还是要上传文件的目标地址？？？求解答

**Comment by liuzhibin123** [comment]
现在解决了 上传过程中不可以删除上传并删除文件吗？，暂停上传？
