### ISSUE TITLE
[Bug Report] The table component custom emptying filter can not be emptied by user - defined method

### ISSUE THREAD

**Issue by xionglihua** [ElemeFE/element#9560]
### Element UI version
1.4.13

### OS/Browsers version
Firefox 58.0.1

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/heyXiong/dttbq9kt/6/](https://jsfiddle.net/heyXiong/dttbq9kt/6/)

### Steps to reproduce
1 选择两个筛选项，选择完成后，会在表格头上增加连个tag标签
2 点击关闭其中一个标签
出现的问题：
点击关闭标签时，无法触发筛选项清空的操作

### What is Expected?
当点击关闭其中一个标签时，用户可以通过一个方法，将对应的筛选项清空，而其他的筛选项保持不变

### What is actually happening?
点击关闭标签时，无法触发筛选项清空的操作，没有提供对应的方法来触发该动作

**Comment by Leopoldthecoder** [comment]
你的 demo 无法正常运行（控制台报错且无样式），请更新。
