### ISSUE TITLE
[Bug Report] el-collapse

### ISSUE THREAD

**Issue by yubei61200** [ElemeFE/element#9561]
### Element UI version
2.0.11

### OS/Browsers version
windows/chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/yubei61200/0rva0990/](https://jsfiddle.net/yubei61200/0rva0990/)

### Steps to reproduce
当外层的el-collapse处于打开状态时，内层的el-collapse未打开时也会显示向下的箭头

### What is Expected?
当外层的el-collapse处于打开状态时，内层的el-collapse未打开时显示向右的箭头

### What is actually happening?
当外层的el-collapse处于打开状态时，内层的el-collapse未打开时也会显示向下的箭头

**Comment by singone** [comment]
嗨，此pr会造成另一个问题。
![image](https://user-images.githubusercontent.com/6127730/35721714-45d222b4-082e-11e8-977e-7e26961930d5.png)
当需要针对展开的样式进行修改样式的时候，会出现问题。
