### ISSUE TITLE
The [Bug Report] 360 compatibility mode or the el-pagination component under the IE browser can not jump on the input box page by enter

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9565]
### Element UI version
2.0.11

### OS/Browsers version
windows10/ie11

### Vue version
2.5.13

### Reproduction Link
[https://github.com/fengyun2/elementui-issue-demo](https://github.com/fengyun2/elementui-issue-demo)

### Steps to reproduce
在ie浏览器(全ie系列、360兼容模式8.1版本,9.1版本)输入页码数，按enter(回车键)，不会触发分页跳转。

### What is Expected?
在ie浏览器、360兼容模式下，输入页码数，按enter(回车键)，可以触发分页跳转（下载提供的demo，在chrome下运行是正常的跳转效果）。

### What is actually happening?
输入页码数，按回车键(enter),不会触发分页跳转。

**Comment by Leopoldthecoder** [comment]
Duplicate of #9530
