### ISSUE TITLE
[Bug Report]  The closeOnHashChange setting of MessageBox is invalid

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#9567]
### Element UI version
1.4.13

### OS/Browsers version
windows 10/63.0.3239.132

### Vue version
2.5.13

### Reproduction Link

https://jsfiddle.net/Lc83h7r9/32/

### Steps to reproduce
点击浏览器后退按钮时，触发beforeRouteLeave钩子，
在beforeRouteLeave中弹出$confirm弹窗，
弹窗一闪就消失了，url变化了，但是页面仍没有跳转。
http://element-cn.eleme.io/#/zh-CN/component/message-box
定义closeOnHashChange为false无效。

### What is Expected?
closeOnHashChange设定为false时，hashChange时MessageBox不关闭。

### What is actually happening?
点击浏览器后退按钮时，触发beforeRouteLeave钩子，
在beforeRouteLeave中弹出$confirm弹窗，
弹窗一闪就消失了，url变化了，但是页面仍没有跳转。
定义closeOnHashChange为false无效。

**Comment by Leopoldthecoder** [comment]
请提供 demo。

**Comment by AprilXtt** [comment]
@Leopoldthecoder 
demo如下：https://jsfiddle.net/Lc83h7r9/32/
步骤：点击[去about]按钮，再点击[退出]按钮，弹窗会闪一下。

**Comment by qingdengyue** [comment]
话说  在 '退出' 按钮的  click事件里，用this.$confirm是不是会好一点?

**Comment by AprilXtt** [comment]
@qingdengyue  是的，在退出按钮的click事件里弹出confirm窗口是没有问题的。
我demo里的退出，是模拟用户点击浏览器的‘后退’按钮（业务需要），所以才写在beforeRouteLeave里的。

**Comment by qingdengyue** [comment]
@AprilXtt 模拟用户浏览器的操作，实际上模拟的是window.confirm的功能，window.confirm可以阻止用户操作，也就是说window.confirm执行后，之后的代码是不执行的，在这种状态下才能实现你所说的效果。我在beforeRouteLeave试过，即使调用this.$confirm，其之后的代码也会立即执行。也就是说在this.$confirm回调执行之前，beforeRouteLeave就已经执行完毕了。所以this.$conform应该实现不了你所说的功能。

**Comment by uncleLian** [comment]
遇到同样的问题
element : 2.0.11 和 2.1.0
vue: 2.5.13
vue-router: 3.0.1
使用$router.go(-1) 和 浏览器后退按钮 触发 beforeRouteLeave钩子，在钩子里面使用confirm拦截，但是confirm 一闪而过没有了，页面留在了原页面，路由地址已经发生改变。confirm的promise回调 .then 和 .catch 并没有执行。closeOnHashChange 设置为fasle 也没有效果。

**Comment by NoLongerLazyDhl** [comment]
@Leopoldthecoder @qingdengyue 这个问题主要是closeOnHashChange 参数不起作用，其实和beforeRouteLeave没有关系。我简单看了下代码，closeOnHashChange 是在message-box进行到mounted时，注册了‘hashchanged’事件来进行关闭的，但是这个时候外界传递的option还没有替换掉instance的prop，导致传递的属性没有生效。

**Comment by Bonnie222** [comment]
请问最终这个问题怎么解决呢？？？

**Comment by loanniss** [comment]
有人有解决方案吗？？

**Comment by ziyoung** [comment]
@qingdengyue 说的很全了。不要 beforeRouteLeave 钩子函数的异步过程里调用 next。如果真想在 beforeRouteLeave 钩子函数异步过程中改变路由，我觉得可以这样来做。

```js
{
  // ...
  beforeRouteLeave (to, from, next) {
    // 异步过程
    setTimeout(() => {
      Vue.$router.go(-1)
    }, 200)
    next()
  }
}
```

**Comment by suyi91** [comment]
最近也遇到了这个问题。看了源码，MessageBox实现上是一个单例，mounted初始化只会执行一次。
```js
  mounted() {
      this.$nextTick(() => {
        if (this.closeOnHashChange) {
          window.addEventListener('hashchange', this.close);
        }
      });
    }
```
初始化时的`this.closeOnHashChange`是MessageBox被第一次调用时设置的值。后续调用的MessageBox传入`closeOnHashChange`都是无效的。

感觉可行的解决方法是:
> packages/message-box/src/main.vue

1. `mounted`和`beforeDestroy`中去掉this.closeOnHashChange的if判断
2. `getSafeClose `中`if (currentId === this.uid) this.doClose()`也加入`this.closeOnHashChange`的判断
