### ISSUE TITLE
The [Bug Report] DatePicker date selector appears BUG

### ISSUE THREAD

**Issue by zhang122622623** [ElemeFE/element#9572]
### Element UI version
1.4.12

### OS/Browsers version
win7/chrome61

### Vue version
2.5.13

### Reproduction Link
[https://github.com/nonono](https://github.com/nonono)

### Steps to reproduce
今天是31号， 发现DatePicker 日期选择器的BUG，，首次打开日期 DatePicker 日期选择器，切换到2017年，选择四月或者六月（30天的月份），组件会往前递增一个月，显示五月和七月，，，，选31天的月份，比如三月，，，就不会出现问题；该问题需在31号才会出现;;

### What is Expected?
选择哪月，便返回正确的月份

### What is actually happening?
今天是31号， 发现DatePicker 日期选择器的BUG，，，，首次打开日期 DatePicker 日期选择器，切换到2017年，选择四月或者六月（30天的月份），组件会往前递增一个月，显示五月和七月，，，，选31天的月份，比如三月，，，就不会出现问题；；
  开始以为是我项目中版本太老，后来在Element的官方文档中操作最新版，也发现一样的问题，，确定这是个BUG；
 猜测是处理31号的时候出现了 问题；官网链接：http://element.eleme.io/#/zh-CN/component/date-picker；
必须是首次，且是31号才能复现

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/35602241-34727f0e-0672-11e8-9f9e-b26321918bd9.gif)

先贴张复现的动图备忘。待修复。

**Comment by wacky6** [comment]
我等会看下吧。我记得这个问题2.0的时候修过了。

**Comment by wacky6** [comment]
https://github.com/ElemeFE/element/pull/9577
DEMO: https://jsfiddle.net/6akyvdds/

2.0的时候修了「左右箭头」导航，没修「月份label」导航 （逃

换到天数较少的月份时，内部状态是目标月的最后一天（这样键盘左右键操作的时候行为比较科学）
