### ISSUE TITLE
[Feature Request] The change method in the time and date selection control will also be invoked in the case where the control's internal value does not change, which is not reasonable

### ISSUE THREAD

**Issue by hearain** [ElemeFE/element#9576]
### Existing Component
是

### Component Name
TimePicker DatePicker DateTimePicker 

### Description
时间和日期选择控件中的change方法在控件内值并没有改变的情况下也会调用，这并不合理，可能会导致一些并不需要的函数调用

**Comment by wacky6** [comment]
有demo吗

**Comment by hearain** [comment]
sorry！看了一下最新的更新日志，我用的是2.0.9版本，这个问题好像在2.0.10版本里优化过了，可以关闭了，谢谢！
