### ISSUE TITLE
[NavMenu] Accessibility problem of menu items

### ISSUE THREAD

**Issue by inoc603** [ElemeFE/element#958]
在导航菜单中，`el-menu-item`使用的是`li`元素，如果以`<el-menu-item>Text</el-menu-item>`的形式使用，菜单项不能被focus，在不使用鼠标的情况下就不能点选。

虽然不是一个特别重要的功能，不过希望能够做出相应改动，提升组件的accessibility。

**Comment by Leopoldthecoder** [comment]
Accessibility 的问题我们目前还没有计划。
