### ISSUE TITLE
[Feature Request]  help me do an enhancement about  el-tree 

### ISSUE THREAD

**Issue by wenny1234** [ElemeFE/element#9584]
### Existing Component
Yes

### Component Name
el-tree 

### Description
When l cancel all children node at one's parent , the parent will be cancel checked status.
I want to the parent  will be cancel checked status unless I clicked the checkbox only.
The parent  node can get checked status(not a indeterminate status)  whether children exist.

for example--> no children's parent will can be selected
--parent
   |      
   |---parent   (checked)
         |---  children (no checked)
         |---  children (no checked)
         |---  children (no checked)
   |---parent

**Comment by Leopoldthecoder** [comment]
Honestly I don't quite understand your request, but it sounds like `check-strictly` can help: https://jsfiddle.net/leopoldthecuber/xsu51mmq/ .

If it doesn't, please provide a detailed description. Some pictures or gifs may help.

**Comment by wenny1234** [comment]
if check-strictly = true is set , you can select any nodes without father-child mode.
![1111](https://user-images.githubusercontent.com/22950755/35622871-60e4cd10-06c4-11e8-853f-4a4ff3986820.jpg)
my request is
1. still retain father-child mode (father is clicked ,all children also is checked) 
2. if all children is cancelled( unchecked), father will not be canceled, still checked

**Comment by Leopoldthecoder** [comment]
> 1. still retain father-child mode (father is clicked ,all children also is checked)
> 2. if all children is cancelled( unchecked), father will not be canceled, still checked

No, we won't support this.

**Comment by buremba** [comment]
@Leopoldthecoder any particular reason why it won't be supported? This is actually a common case, the parent is also an entity so even though the parent is checked, its children may not be selected. We're using this component in our permissions page and we have the following structure:

```
- Access the data
   - Access additional x data
   - Access additional y data
   - Access additional y data
```
