### ISSUE TITLE
[Feature Request] Placement of collapse button(arrow) for grouped item in menu.

### ISSUE THREAD

**Issue by fruxxx** [ElemeFE/element#9586]
### Existing Component
Yes

### Component Name
menu

### Description
I want to change placement of collapse button(arrow) for grouped item in menu.
Is it in the el-tooltip placement in this file https://github.com/ElemeFE/element/blob/dev/packages/menu/src/menu-item.vue?

**Comment by Leopoldthecoder** [comment]
Actually it's [here](https://github.com/ElemeFE/element/blob/dev/packages/menu/src/submenu.vue#L284).

**Comment by fruxxx** [comment]
Thank you!
So... there is no options for change placement of this collapse arrow buttons.
