### ISSUE TITLE
[Feature Request] Elements are kept pressed

### ISSUE THREAD

**Issue by armandomendivil** [ElemeFE/element#9588]
### Existing Component
Yes

### Component Name
<el-button />, <el-item-menu />

### Description
.-When I press a button it stays pressed
.-When I press an item menu it changes the background to white color for few seconds

**Comment by Leopoldthecoder** [comment]
> When I press a button it stays pressed

This means the button is still focused. It is intentional.

> When I press an item menu it changes the background to white color for few seconds

Please write a demo and open a bug report with it.
