### ISSUE TITLE
[Feature Request] table can drag the width of the column and the custom display column

### ISSUE THREAD

**Issue by miuqiang** [ElemeFE/element#9593]
### Existing Component
Yes

### Component Name
table

### Description
1、table 表格可以增加拖动效果以达到自定义宽度。
2、table自定义展示列的效果。比如默认有8列数据，我只想看其中的3列。

**Comment by Leopoldthecoder** [comment]
> table 表格可以增加拖动效果以达到自定义宽度

带边框的表格都可以拖动：
![untitled1](https://user-images.githubusercontent.com/10095631/35658419-2a1fb452-073c-11e8-8f0b-7ba9e0d42b6e.gif)

> table自定义展示列的效果。比如默认有8列数据，我只想看其中的3列

**Comment by jinyanliang** [comment]
PC project added border but table drag column width only works under ie browser
