### ISSUE TITLE
[Bug Report] Can not change the style of submenu items

### ISSUE THREAD

**Issue by xiaoyanhao** [ElemeFE/element#9594]
### Element UI version
2.1.0

### OS/Browsers version
Windows 7 / Chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xiaoyanhao/pesfqdko/3/](https://jsfiddle.net/xiaoyanhao/pesfqdko/3/)

### Steps to reproduce
1. Add class "el-menu-demo" to <el-menu>.
2. Add class "red" to submenu items.
3. Define style:
```scss
.el-menu-demo {
  .red {
    color: red;
  }
}
```

### What is Expected?
The submenu items display in red.

### What is actually happening?
The submenu items remain unchanged.

The custom el-menu class does not apply to its popup menu.

**Comment by Leopoldthecoder** [comment]
SubMenu is now a direct child of `document.body`, so the CSS selector fails. For now you can https://jsfiddle.net/leopoldthecuber/pesfqdko/4/ . In #9600 a new prop `popper-class` is added to SubMenu, so that you can add class to the popup menu.
