### ISSUE TITLE
日期时间选择器，如果为datetimerange类型，并且设置value-format="yyyy-MM-dd hh:mm:ss"，会出现问题。

### ISSUE THREAD

**Issue by AndsteLyc** [ElemeFE/element#9602]
Element UI version
2.1.0

OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Vue version
2.5.13

Reproduction Link
https://jsfiddle.net/Lddj1okr/

Steps to reproduce
选择一个日期时间区间，将开始和结束时间都设为00:00:00
Select a date and time range and set the start and end times to 00:00:00

What is Expected?
时间不会为12:00:00
Time will not be 12:00:00

What is actually happening?
时间为12:00:00
Time will be 12:00:00

![](http://data.andste.cc/developers/github/images/demo.gif)

**Comment by wacky6** [comment]
http://element.eleme.io/#/zh-CN/component/date-picker#ri-qi-ge-shi

**Comment by AndsteLyc** [comment]
好的谢谢，我再仔细检查检查。
