### ISSUE TITLE
[Table]增加展开行的功能

### ISSUE THREAD

**Issue by chenweiqun** [ElemeFE/element#961]
希望能增加一个treeGrid控件,类似于,[这种](https://ant.design/components/table/#components-table-demo-expand-children)

**Comment by furybean** [comment]
在计划中，1.1 版本应该会有。

**Comment by QingWei-Li** [comment]
1.1 已加入

**Comment by ouyangshan09** [comment]
@QingWei-Li  1.1加入了展开行的功能，好像不完成前文中的那种多级展开吧？

![tablegrid](https://cloud.githubusercontent.com/assets/3814130/21598368/c99884b4-d196-11e6-902f-de9e014972cb.png)
类似上面这种，也就是前面一个人提到的控件类似

**Comment by ChangeZhang** [comment]
有同样需求，希望可以增加！

**Comment by foolishchow** [comment]
try this [elemet-tree-grid][tree-grid] 

[tree-grid]:  https://github.com/foolishchow/element-tree-grid "tree-gird"
