### ISSUE TITLE
[Feature Request] messagebox how to custom title?

### ISSUE THREAD

**Issue by lujin123** [ElemeFE/element#9613]
### Existing Component
Yes

### Component Name
MessageBox

### Description
The message attribute of `Message Box` component can accept a `string` or `VNode`, but the `title` attribute can only be a `string`. If I want to customize an title, how do I do it? For example, I want to change the title into a picture

**Comment by wacky6** [comment]
Why using a picture? Any use cases? Can you give an example.

**Comment by lujin123** [comment]
@wacky6 标题里面不想要纯字符串，就是想嵌一个图片，这种情况要怎么办呢

**Comment by Leopoldthecoder** [comment]
We have no plan to support this. Try Dialog if you must put an image in the title.
