### ISSUE TITLE
[Bug Report] <el-table-column type="expand">    can't set attr: lable='***'

### ISSUE THREAD

**Issue by Nathanlee2010** [ElemeFE/element#9616]
### Element UI version
2.0.5

### OS/Browsers version
all

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/nonenonenonenonenonenone/](https://jsfiddle.net/nonenonenonenonenonenone/)

### Steps to reproduce
<el-table-column type="expand">    can't set attr: lable='***'   or mean: table dont show this column lable.

当el-table-column的type为expand时，  设置label无效。

### What is Expected?
hope that work.
期待有效。

### What is actually happening?
dont work.
无效

**Comment by Hi-Linlin** [comment]
demo 404了

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/zvtjkjz6/

**Comment by 2248157705** [comment]
@Hi-Linlin el-table-column type="expand" 那个三角图标怎么自定义？

**Comment by 2248157705** [comment]
@ Hi-Linlin ![image](https://user-images.githubusercontent.com/4066040/44647805-c3be6180-aa11-11e8-935e-70257a4e99d3.png)
