### ISSUE TITLE
[Feature Request] Color Picker add support for touch dragging

### ISSUE THREAD

**Issue by Ben-Mack** [ElemeFE/element#9619]
### Existing Component
Yes

### Component Name
Color Picker

### Description
We're going to use Element for our web app which will be used on both Destop and Mobile. 

Almost every components of Element work great on mobile, except one important component is Color Picker, currently does not support touch dragging (only tap to choose color now).

Please consider to add this useful feature, thanks for creating this great UI framework!

**Comment by wacky6** [comment]
Technically, element is designed for desktop. Maintainers will not actively support mobile usage.

Ask @Leopoldthecoder if mobile-related PRs are welcomed.

If you do make PR, you need to take responsibilities to maintain it, write tests to prove it working / protect others from breaking it.

**Comment by Leopoldthecoder** [comment]
Yes, we'll not support this feature. And we may not accept PRs regarding mobile usages since Element is for admin pages.

**Comment by jlabresh1** [comment]
@Leopoldthecoder I appreciate the desktop only approach, but in our case, our admin pages are used on desktop and tablets. In our industry and others, interfaces are moving to touch screen devices. Is the plan for element to only live on desktop and require a mouse?
