### ISSUE TITLE
[Bug Report] Select options list position need update while $el.offsetTop(or offsetBottom/offsetLeft/offsetRight) changed

### ISSUE THREAD

**Issue by joe223** [ElemeFE/element#9624]
### OS/Browsers version
All platform

### Steps to reproduce
just see: https://jsfiddle.net/aa3bj55u/2/

![image](https://user-images.githubusercontent.com/10026019/35714842-f5af25ee-0809-11e8-9a78-380d8b6672d0.png)

### What is Expected?
update list position

### What is actually happening?
DID NOT UPDATE

**Comment by Leopoldthecoder** [comment]
这种情况可能需要自己 hack 一下：https://jsfiddle.net/leopoldthecuber/aa3bj55u/3/ 。后期考虑提供选项将弹出菜单作为 Select 的子元素。

**Comment by joe223** [comment]
作为子元素可能会遇见层级（z-index）上的挑战，因为我们不确定 select 组件的父元素在某些场景下是否一定要比后面的兄弟元素 z-index 值小。

不过有个想法：如果监测下 window 的 resize 事件，并更新 position 是不是可以解决绝大部分这样的问题?
