### ISSUE TITLE
[Feature Request]  [el-date-picker]  Component  can not  refresh data  at IE 11

### ISSUE THREAD

**Issue by wenny1234** [ElemeFE/element#9625]
### Existing Component
Yes

### Component Name
[el-date-picker

### Description
 I add  [el-date-picker]  Component to  Dialog UI named A  for display/input date info,
I have a  list record UI named B， when  I click the first record , A UI will open by Dialog mode.
I can find the date is displayed by [el-date-picker] .(for example: 2018/02/01), That‘s OK。
I  will click the second record or other's record，
the date is displayed  in [el-date-picker]  Component can’t not refresh the date，displayed still 2018/02/01。
 it's happened   only IE 11

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
