### ISSUE TITLE
[Feature Request] in order to overwrite slider component, how to monkey-patch 

### ISSUE THREAD

**Issue by wenbo** [ElemeFE/element#9626]
### Existing Component
Yes

### Component Name
slider

### Description
currently when slider's value is smaller than the minValue,  the value in the input box of slider will be set to minValue. but our customer's request is Do Not reset the value when slider's value is smaller than the minValue,
So I have to overwrite the source code in following file.  But I have no idea how to properly overwrite ElementUI in our project.  Generally How to overwrite ElementUI when I want to custom some behavior please? 

https://github.com/ElemeFE/element/blob/dev/packages/slider/src/main.vue#L186

**Comment by Leopoldthecoder** [comment]
In your Element fork, run `npm run dist`, and the built files should be in the `lib` folder. Copy this folder and override `node_modules/element-ui/lib` of your project.
