### ISSUE TITLE
[Bug Report] from version 2.01 to 2.1 version of the table error source error is not found $el.

### ISSUE THREAD

**Issue by lifanlingjue** [ElemeFE/element#9632]
### Element UI version
2.1.0

### OS/Browsers version
chrome 6.0

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
更新完就不好使了。。。

### What is Expected?
好使了呗。。。

### What is actually happening?
我也不知道发生了啥啊。。。

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
