### ISSUE TITLE
TableColumn没有开放renderCell的属性

### ISSUE THREAD

**Issue by sindu12jun** [ElemeFE/element#964]
cell不能自定义render，只能显示原始数据；看到代码里是有renderCell的方法的，为什么没开放呢

**Comment by furybean** [comment]
我能想到的是：除非要求动态增删 column，并控制每个 column 的渲染内容；使用现有的 table-column 上加 inline-template 属性就可以满足。

建议讲一下自己需要使用 renderCell 的场景。

**Comment by sindu12jun** [comment]
大多数情况确实是不需要，只是看到renderHeader开放renderCell没开放强迫症犯了哈哈，

**Comment by varHarrie** [comment]
@furybean 对于jsx用户来说，`renderCell`还是很有必要的
