### ISSUE TITLE
[Feature Request] Pagination with table component

### ISSUE THREAD

**Issue by amittkSharma** [ElemeFE/element#9642]
### Existing Component
Yes

### Component Name
Table Component, Pagination component

### Description
Hello Team, 

Is there a way to incorporate pagination component along with table component? Can you please provide some hints or way to do this?

Or try to include pagination as part of table component.

Thanks
Amit

**Comment by Leopoldthecoder** [comment]
Just update the table data in `current-change` event handler.

**Comment by diaxis** [comment]
What are you suppose to do when this event is triggered ? A fiddle of how this could be accomplished would be great. Why is that not implemented yet directly as an option in the el-table? pagination of a tables is really important and a basic thing that should have been implemented in 2.0

**Comment by kevrousso** [comment]
I agree on this ^. Table with pagination is a must in most of the cases.
@Leopoldthecoder Could you make a fiddle example with your idea?
