### ISSUE TITLE
[Bug Report] can't use in monorepo

### ISSUE THREAD

**Issue by yozman** [ElemeFE/element#9643]
### Element UI version
2.1.0

### OS/Browsers version
chrome

### Vue version
2.5.13

### Steps to reproduce
init a project use lerna contain 2 packages UI & PREVIEW(generated by vuejs-templates/webpack). element is require by UI and UI is require by PREVIEW.

### What is Expected?
when use `npm run dev` to start in PREVIEW, everything works well is what I want.

### What is actually happening?
there is an error like this:
```javascript
94% asset optimization

 ERROR  Failed to compile with 10 errors                                                                                                                  21:40:42

This dependency was not found:

* vue in ../op-ui/node_modules/element-ui/lib/element-ui.common.js, ../op-ui/node_modules/element-ui/lib/tooltip.js and 8 others
```

wish u guys fix it

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by yozman** [comment]
@Leopoldthecoder 没法复现的原因是在编译阶段会出错，用到 monorepo 的结构里

**Comment by Leopoldthecoder** [comment]
把你的项目上传到 Github

**Comment by yozman** [comment]
@Leopoldthecoder 
。。什么时候开源项目成大爷了。。
bug 细节都明确描述出来了
