### ISSUE TITLE
[Feature Request] How to customize a row for table?

### ISSUE THREAD

**Issue by asd8855** [ElemeFE/element#9644]
### Existing Component
是

### Component Name
table

### Description
How to customize a row for  table?

**Comment by asd8855** [comment]
<img width="738" alt="333333" src="https://user-images.githubusercontent.com/20153584/35761462-afd99094-08c3-11e8-892f-1c793c7646ab.png">

**Comment by asd8855** [comment]
<img width="707" alt="44444444" src="https://user-images.githubusercontent.com/20153584/35761482-020b9290-08c4-11e8-935e-00b8e6f82cf0.png">

**Comment by Leopoldthecoder** [comment]
http://element-cn.eleme.io/2.1/#/zh-CN/component/table#zi-ding-yi-lie-mo-ban
