### ISSUE TITLE
[Feature Request] 建议upload增加limit之后，当达到限制数，上传框那个div隐藏

### ISSUE THREAD

**Issue by zhibikanmohuakai** [ElemeFE/element#9651]
Existing Component

是

Component Name

upload

Description

设置了limit，但是达到限制数之后，上传框还是存在，影响美观，所以建议达到限制之后，这个框就隐藏，如果用户删了一张图片，没达到限制数了，那么上传框又显示出来。谢谢

**Comment by zhibikanmohuakai** [comment]
@my9074 使用onchange可以解决。

**Comment by my9074** [comment]
@zhibikanmohuakai  谢谢~能给个 jsfiddle demo 不~

**Comment by dengxiaozhen** [comment]
@zhibikanmohuakai  怎么让 那个上传图片那个加号隐藏？操作 dom？
