### ISSUE TITLE
[Feature Request] After recommends upload to increase the limit, when the number of restrictions is reached, the upload box is hidden in the div

### ISSUE THREAD

**Issue by zhibikanmohuakai** [ElemeFE/element#9652]
### Existing Component
Yes

### Component Name
upload

### Description
设置了limit，但是达到限制数之后，上传框还是存在，影响美观，所以建议达到限制之后，这个框就隐藏，如果用户删了一张图片，没达到限制数了，那么上传框又显示出来。

**Comment by zhibikanmohuakai** [comment]
比如我限制三张，但是我要出现三张的时候，那个上传框取消，但是我要上传第四章图，才会触发那个钩子，所以还是没用

**Comment by qingdengyue** [comment]
@zhibikanmohuakai on-change 可解~

**Comment by zhibikanmohuakai** [comment]
已解决。onchange

**Comment by TreeVie** [comment]
@zhibikanmohuakai 请问怎么隐藏 上传框

**Comment by zhibikanmohuakai** [comment]
@TreeVie 用onchange判断文件数量，达到限制，取到上传dom并移除或隐藏他
