### ISSUE TITLE
[Bug Report] Publish source code for Component Live Examples: Font between Component Live Examples on website is different than the one in JSFiddle/Starter Pack

### ISSUE THREAD

**Issue by ericcgu** [ElemeFE/element#9656]
### Element UI version
2.1.0

### OS/Browsers version
Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/7kphxfhw/](https://jsfiddle.net/7kphxfhw/)

### Steps to reproduce
Font between Component Examples on website (http://element.eleme.io/#/en-US/component/date-picker) is different than the one in Try It JSFiddle / Starter Pack / Quick Installation.

I am having difficulty replicating the exact look of the component example, specifically the font of components (datepicker, select).
When clicking the live example, 
the font is Helvetica

When using 
1. Try It (reproduction link) 
2. Starter Pack
3. CLI
4.  Other examples (http://dahouge.oschina.io/houtai/dist/#/activePublic)

the font of the date picker and select picker is Times New Roman. 

I followed instruction 
(http://element.eleme.io/#/en-US/component/custom-theme) and can override theme color but very unclear on how and why the font defaults to Times New Roman. 

This must be something I am missing but was wondering if someone can clarify.

### What is Expected?
Component font to default to Helvetica like in Demo/Live Example

http://element.eleme.io/#/en-US/component/date-picker

### What is actually happening?
Component font defaults to Times New Roman

**Comment by konstantins-buts** [comment]
Bug still seems to be present in the version _2.4.2_.
Was it fixed before?

**Comment by smalesys** [comment]
Bug confirmed with Element 2.4.9 and Vue 2.5.17
I didn't find how to override this properly. If someone has a clue, please share the love :)

**Comment by ericcgu** [comment]
I am on the road right now but you can inspect element to find the
element/font and override the times new Roman font.
