### ISSUE TITLE
[Select]如何在获得焦点的时候自动展开下拉框

### ISSUE THREAD

**Issue by masterzhang** [ElemeFE/element#966]
在表单输入时，经常使用`tab`切换到下一个。但是切换到下拉组件的时候，下拉组件不会自动展开，必须按一下方向键的`↓`才能展开

**Comment by YuFengDing** [comment]
1.监听select 组件的 focus事件
2.给该select组件加上ref,在focus回调中手动触发 这个组件的click事件,即 this.$refs[refName].$el.click()

**Comment by obulks** [comment]
` <el-select @focus="$event.target.click()"></el-select>`
