### ISSUE TITLE
[Feature Request] dialog service

### ISSUE THREAD

**Issue by qiangbro** [ElemeFE/element#9662]
### Existing Component
否

### Component Name
$dialogService

### Description
希望elementUI可以提供一个官方的DialogService来弹出一个自定义的对话框，这个对话框拥有自己的data、methods、template等等，当对话框关闭后promise会被resolve，其作用域也会销毁。灵感来自于ui.bootstrap的 $uibModal，其实现在已经有人实现了，例如：https://www.npmjs.com/package/vue-dialog-service ，希望官方可以集成这个实用的功能。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
