### ISSUE TITLE
el-switch组件 设置on-text属性 在 el-form-item 组件中样式跑版了

### ISSUE THREAD

**Issue by isunkui** [ElemeFE/element#967]
### ElementUI version
1.0.0

### OS/Browers version
macOS/Chrome 54

![image](https://cloud.githubusercontent.com/assets/10893176/20172387/cc998268-a76f-11e6-99e5-994d9ab3ee03.png)

**Comment by furybean** [comment]
和 #987 重复，已经修正。

**Comment by qiangbro** [comment]
亲　你是怎样将文字的位置调到组件内部的，有示例代码么
