### ISSUE TITLE
[Bug Report] table span-method merge line, when there is a check box in front of the table

### ISSUE THREAD

**Issue by iaminvictus1993** [ElemeFE/element#9676]
### Element UI version
2.1.0

### OS/Browsers version
mac  chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/4jjet03t/](https://jsfiddle.net/4jjet03t/)

### Steps to reproduce
无

### What is Expected?
期待合并后能出现数据

### What is actually happening?
合并后数据消失

**Comment by Leopoldthecoder** [comment]
> 期待合并后能出现数据

是指哪些单元格出现？https://jsfiddle.net/4jjet03t/1/ 是否符合期望？
