### ISSUE TITLE
[Bug Report] table column  type="selection"   头部 bug

### ISSUE THREAD

**Issue by blank-x** [ElemeFE/element#9677]
### Element UI version
2.1.0

### OS/Browsers version
mac  OS   / chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/rjsbj573/](https://jsfiddle.net/rjsbj573/)

### Steps to reproduce
拖动横向滚动条到行尾，选中头部复选框

### What is Expected?
位置不变

### What is actually happening?
表头滚动到最左边

**Comment by syn-zeta** [comment]
Unrelated to this bug, but was the auto-translation using ElementBot switched off?
