### ISSUE TITLE
fullscreen loading 异步关闭的时候 body一直存在overflow：hidden

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#968]
### ElementUI version

v1.0.0
### Vue version

2.0.3
### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/6311122/20173354/eadcb034-a773-11e6-8605-a0f1aca834eb.png)

```
// 自定义的一个事件
const that = this
that.fullscreenLoading = true;
        setTimeout(function () {
          // this.fullscreenLoading = true;
          that.fullscreenLoading = false; 
        }, 1000);
```
loading已经关闭但是
body还是会出现overflow:hidden

**Comment by Leopoldthecoder** [comment]
你这段代码应该是不能正常工作的：`setTimeout` 回调里的 `this` 并不是当前的 `vm`。另外在回调里把 
`fullscreenLoading` 赋值为 `true` 是笔误？

请提供能重现问题的 demo。

**Comment by spademan** [comment]
@Leopoldthecoder  哦 那个this是手误
我忘了说一个条件就是我还结合了dialog一起用
demo
http://jsfiddle.net/v5hvh1tp/

**Comment by Leopoldthecoder** [comment]
Fixed in #986
