### ISSUE TITLE
[Feature Request] Replace field name in validation messages

### ISSUE THREAD

**Issue by danherd** [ElemeFE/element#9680]
### Existing Component
Yes

### Component Name
Form

### Description
How can I replace the field name in validation error messages with a better description of the field? I know I can replace the entire message by using the 'message' property in the rule, but I just want to, for example, replace 'firstName' with 'first name' (keeping the existing message templates).

Here's a fiddle showing what I mean: https://jsfiddle.net/utk3vh0o/

**Comment by wacky6** [comment]
https://jsfiddle.net/794qke8t/

**Comment by danherd** [comment]
@wacky6 Thanks for responding, but that's not what I'm after. Like I said, I know I can replace the entire message, but I just want to replace the field name in the existing messages. So, for example:

'firstName is required'

becomes:

'first name is required'

Thanks!

**Comment by wacky6** [comment]
Right no it's impossible. You have to write the entire message to achieve that.

**Comment by danherd** [comment]
That's a shame. OK, thanks!
