### ISSUE TITLE
[Bug Report] Inconsistent behavior of icon clicks on DateTime and DateTimeRange pickers

### ISSUE THREAD

**Issue by syn-zeta** [ElemeFE/element#9687]
### Element UI version
2.1.0

### OS/Browsers version
Not dependent

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/oru2gez5/](https://jsfiddle.net/oru2gez5/)

### Steps to reproduce
- Click on the time icon for datetime picker (top)
- Notice that the picker panel does not open
- Click on the time icon for datetimerange picker (bottom)
- Notice that the picker panel appears

### What is Expected?
Consistent UX on icon clicks for DT/DTR components.

### What is actually happening?
Icon click on DT picker does nothing, while it triggers the panel on DTR picker.

**Comment by Leopoldthecoder** [comment]
Fixed in #9966.
