### ISSUE TITLE
[Feature Request] Can you provide a way of building a local document.

### ISSUE THREAD

**Issue by eidonjoe** [ElemeFE/element#9689]
### Existing Component
否

### Component Name
local doc

### Description
Because we are using the version @1.4.4 for Element in prod, so we can not to migrate to version 2.x immediately, but the official docs of 1.x is no longer maintained. I just worry about official docs will be removed some day that we can't refer. So, Can you provide a way of building a local document by myself?

**Comment by garveen** [comment]
Actually if you clone this project and build it, you'll get the doc.

**Comment by Leopoldthecoder** [comment]
- Clone this repo
- `git checkout v1.4.4`
- `npm run dev`
