### ISSUE TITLE
dialog 无法关闭

### ISSUE THREAD

**Issue by zdz1993** [ElemeFE/element#969]
dialog 根本不能使用我用的是jsx 有个绑定一个了一个value在上面
 <el-dialog title="收货地址" value={this.show} size="tiny">
                    <span>hhh</span>    
                    <span slot="footer" class="dialog-footer">
                       aaa
                    </span>    
                </el-dialog>
这样出来的dialog点击右上角的小图标无法关闭

**Comment by furybean** [comment]
和 #970 重复。
