### ISSUE TITLE
[Feature Request] Can the dialog component add the destroyOnClose method (to destroy the subelements in the Modal when closed)?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9691]
### Existing Component
是

### Component Name
dialog

### Description
dialog组件是否可以添加destroyOnClose方法（关闭时销毁 Modal 里的子元素）？因为table页面的每一项列表后面都有操作，而且当这个页面的编号不唯一时，调用弹窗，就会因为编号不唯一导致弹框里面的内容还是上一次弹框的内容。

**Comment by furybean** [comment]
感觉这个需求有个悖论：如果 Dialog close 的时候就 destroy 了，那又怎么能再次打开？

**Comment by fengyun2** [comment]
https://codesandbox.io/s/n4jxxo6mrp，注意看弹框(message信息)的信息，当code值一样时，code不会再次弹出来，或者当detail组件具有直接操作dom时，改变dom内容后，再次打开弹出框dom不会被销毁。

**Comment by Leopoldthecoder** [comment]
没看懂这个例子。

##

> 当code值一样时，code不会再次弹出来

从代码来看，这个好像是期望中的行为？

##

> 导致弹框里面的内容还是上一次弹框的内容

例子并没有体现这个问题。

**Comment by fengyun2** [comment]
期望的行为是，当code值一样时，需要弹出message消息。

**Comment by baiyaaaaa** [comment]
既然你认为 code 值一样时也需要弹出code值一样时，那你为什么要 watch 呢。。。？

**Comment by fengyun2** [comment]
这只是举一个例子，就是编码相同的时候，每次点击，弹框里面的内容也需要清空（包括dom元素）。

**Comment by furybean** [comment]
不认为是一个常见的案例，建议通过代码解决。

**Comment by yezongyang** [comment]
常有这个需求啊，比如弹窗里填写表单，当我关闭后再打开希望是初始化的表单

**Comment by Leopoldthecoder** [comment]
@yezongyang 可以在 `close` 事件回调里重置表单。

**Comment by fengyun2** [comment]
@fairyier @yezongyang 临时办法就是在dialog加个v-if判断，每次重新生成dom。

**Comment by fengyun2** [comment]
感觉，官方提供一个参数决定是不是保留之前的状态会比较好，每次复用添加/编辑框就是个蛋疼的事情。

**Comment by xianshenglu** [comment]
https://github.com/ElemeFE/element/pull/16455
