### ISSUE TITLE
[Bug Report] npm run dist 

### ISSUE THREAD

**Issue by duizhenpeng** [ElemeFE/element#9693]
### Element UI version
2.1.0

### OS/Browsers version
windows10

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
npm run dist 

### What is Expected?
create dist 

### What is actually happening?
> eslint src/**/* test/**/* packages/**/* build/**/* --quiet

C:\Users\pc\Desktop\element-dev\packages\table\src\table.vue
  539:14  error  Missing semicolon  semi

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\tabs.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\tag.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\time-picker.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\time-select.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\tooltip.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\transfer.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\tree.scss
  1:1  error  Parsing error: Unexpected character '@'

C:\Users\pc\Desktop\element-dev\packages\theme-chalk\src\upload.scss
  1:1  error  Parsing error: Unexpected character '@'

✖ 84 problems (84 errors, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-ui@2.1.0 lint: `eslint src/**/* test/**/* packages/**/* build/**/* --quiet`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@2.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2018-02-06T07_38_45_540Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-ui@2.1.0 dist: `npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:umd && npm run build:theme`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@2.1.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2018-02-06T07_38_45_591Z-debug.log

**Comment by duizhenpeng** [comment]
npm run dev normal

**Comment by pflhm2005** [comment]
you could delete 'npm run lint' in dist commond,but as you complete the dist and copy the 'lib' directory to your local 'node_modules' directory,the el-pagination component would get a error message like '* push is undefined'...某改

**Comment by duizhenpeng** [comment]
I did not make any changes. Source package download and install package. After testing npm run dev open normal. When I want to generate dist file npm run dist error. I do not quite understand what you mean. You mean that I modified the tape file?

**Comment by pflhm2005** [comment]
I mean there is something with the eslint and the code,it has been a long time....delete the 'npm run lint',it is located in the package.json => scripts => dist

**Comment by littlePig-zzf** [comment]
@pflhm2005 good, it's ok.
