### ISSUE TITLE
element打算用何种方式整合PC端与移动端

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/element#97]
我看到ant.design出了移动版，想问element是怎么看待大屏与小屏的，是否由element统一自适应大小屏，还是额外再搞一个element-mobile？
我个人的看法是，其实ant design的自适应已经做得很好了，手机端和pc端无缝切换，所以个人认为element没必要再出一个mobile版

**Comment by QingWei-Li** [comment]
请看完规范再来提 issue https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md#issue-规范

使用上的问题或者建议请到 [Gitter](https://gitter.im/ElemeFE/element) 上提问，issue 只是用来提 bug 和 feature，不符合的 issue 直接关掉
