### ISSUE TITLE
还有那个dialog的open和close怎么用啊

### ISSUE THREAD

**Issue by zdz1993** [ElemeFE/element#970]
dialog 根本不能使用我用的是jsx 有个绑定一个了一个value在上面
 <el-dialog title="收货地址" value={this.show} size="tiny">
                    <span>hhh</span>    
                    <span slot="footer" class="dialog-footer">
                       aaa
                    </span>    
                </el-dialog>
这样出来的dialog点击右上角的小图标无法关闭

**Comment by furybean** [comment]
JSX 的 v-model 现在基本是残废的，建议在 JSX 中通过 ref 来 open 和 close。

**Comment by zdz1993** [comment]
我通过ref来open只能打开modal看不到dialog

**Comment by Leopoldthecoder** [comment]
与 #1031 类似。不过在 JSX 里由于不能指定 v-model，会导致无法使用 `open` 和 `close` 方法。需要等下个版本修复。

**Comment by Leopoldthecoder** [comment]
Fixed in #1038
