### ISSUE TITLE
[Feature Request] Allow dropdown menu have multi-level actions

### ISSUE THREAD

**Issue by ultraN** [ElemeFE/element#9700]
### Existing Component
是

### Component Name
el-dropdown-menu

### Description
This feature is similar to Cascader and Menu(submenu) components, allow us to group buttons with similar functionalities together and reduce total height of the dropdown.

Expected effect demonstrations:

http://element.eleme.io/#/zh-CN/component/menu#zhe-die

http://element.eleme.io/#/zh-CN/component/cascader

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
