### ISSUE TITLE
[Bug Report] input search box /select shrink box /Tooltip prompt box location error

### ISSUE THREAD

**Issue by nlx0201** [ElemeFE/element#9703]
### Element UI version
2.1.0

### OS/Browsers version
Windows

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1. 新建主页面A，设置页面大小，允许水平滚动条
2. 新建dialog窗体B，点击主页面A上的按钮打开dialog窗体B
3. 修改dialog窗体B样式，使其位置靠浏览器右侧
4. 在dialog窗体B中放置input，使input实现远程搜索提示功能
5. 在input中输入模糊匹配的数据，提示选项位置不正确

### What is Expected?
搜索建议结果弹层应该位于input下方并与input起始位置对齐

### What is actually happening?
受水平滚动的影响，搜索建议结果偏离input位置

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
