### ISSUE TITLE
[Bug Report] Top & left border appeared when loading shows upon border table

### ISSUE THREAD

**Issue by Kris-Lee-SH** [ElemeFE/element#9709]
### Element UI version
2.1.0

### OS/Browsers version
ALL

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/KrisLeeSH/jomm0ags/](https://jsfiddle.net/KrisLeeSH/jomm0ags/)

### Steps to reproduce
1. set table with border style via PROPS ```border```
2. show loading on table with ```<el-table v-loading="true">```

### What is Expected?
Loading mask covers all the table area including the top & left borders.

### What is actually happening?
Table's top & left border shows.

**Comment by furybean** [comment]
可以先这么绕一下：https://jsfiddle.net/jomm0ags/1/
