### ISSUE TITLE
How to set the height of [Feature Request] Dialog

### ISSUE THREAD

**Issue by coderstory** [ElemeFE/element#9711]
### Existing Component
Yes

### Component Name
Dialog 

### Description
目前似乎没有设置Dialog 高度的属性 只有设置宽度的属性 Dialog会自适应内容的高度 但有时候，需要设置内容过长的时候 Dialog内出现滚动条 而不是整个屏幕的滚动条

**Comment by Leopoldthecoder** [comment]
用 CSS。
