### ISSUE TITLE
[Feature Request] Tree components are very smart when using node filtering

### ISSUE THREAD

**Issue by Altamill** [ElemeFE/element#9715]
### Existing Component
是

### Component Name
el-tree

### Description
For example, we are trying to do the tree of the employee search, and use the node filtering function.

Phenomenon: when the first letter or text is entered, the match is very slow, and there is no problem in the following letter or text input.

Are there any optimization options?

filterNode(value, data) {
 if (!value) return true;
 return data.userid.indexOf(value) !== -1 || data.label.indexOf(value) !== -1;
}

**Comment by Altamill** [comment]
数据量比较大，输入首字母的时候 treeNodeId 往往超过1900

**Comment by furybean** [comment]
@Altamill  这个问题建议对 input 进行 debounce 解决，比如这个库：https://github.com/vuejs-tips/v-debounce 或者 https://github.com/vuejs-tips/tiny-debounce

暂时无计划在 Tree 上实现这个功能。
