### ISSUE TITLE
[Feature Request] Form in a table along with validation

### ISSUE THREAD

**Issue by nuneramu** [ElemeFE/element#9716]
### Existing Component
Yes

### Component Name
Table

### Description
I want to implement a form along with validation in a table. Want to have inline editing of a row. I'm able to use the select, input, checkbox etc fields, not with el-form-item.

The layout I expecting to implement is as follows:
1) Should have a regular table view.
2) An 'Edit' button above the table to toggle between edit and view.
3) When the edit button is clicked the table transforms into form elements with respective validations. Now the edit button text is replaced with 'View'
4) When View button is clicked the table switches back to regular table view with no form elements format.

Hope I'm able to convey you.

**Comment by Leopoldthecoder** [comment]
This is a usage question instead of a feature request. If you need some feature that is not provided, open a feature request with the specific feature point.
