### ISSUE TITLE
[Feature Request] Table filters can support input Val?

### ISSUE THREAD

**Issue by myzingy** [ElemeFE/element#9720]
### Existing Component
是

### Component Name
Table

### Description
这是一条建议或者询问！
我在使用 table 时，由于过滤项很多，需要使用表格 filters ，但目前 filters 只支持 “数组格式 Array[{ text, value }]”
我想让 filters 支持 input ，怎么扩展这个 filters ？能否提供一些思路 ？

感谢你们辛苦的付出

**Comment by Leopoldthecoder** [comment]
自带的 filter 不支持拓展。可以把 `<input>` 写在 Table 外部。

**Comment by myzingy** [comment]
![_20180208120654](https://user-images.githubusercontent.com/228342/35955169-a97106de-0cc8-11e8-844f-c0588f9cf9cf.png)
已经写过外面了，但是非常多的搜索条件本身查找起来就不方便

**Comment by myzingy** [comment]
解决思路写在这里：
1，将2个表格拼在一起，前者负责表头搜索，后者隐藏表头负责展示数据
前者：
`<el-table :data="[{}]">...<el-table>` 
后者：
`<el-table :data="tableData" :show-header="false">...<el-table>`

后者建议控制高度，不然垂直滚动时表头会滚上去；
**横向滚动的处理：**
当列很多时，前者和后者都会出现横向滚动条，很难看，也不好操作；通过以下代码实现2个横向滚动条合并为1个：
`
mounted(){

            let node = this.$el.querySelector('.el-table__body-wrapper');

            node.style.overflow = "hidden";

            let node2 = this.$el.querySelectorAll('.el-table__body-wrapper')[1];

            node2.addEventListener('scroll',(e)=>{

                node.scrollLeft = e.target.scrollLeft;

            })

        },
`
