### ISSUE TITLE
[Feature Request] can customize the attribute of Z-index in dialog

### ISSUE THREAD

**Issue by baifan** [ElemeFE/element#9724]
### Existing Component
Yes

### Component Name
el-dialog

### Description
在和其他插件一起使用Dialog的时候, 会出现其他组件的z-index高于dialog的z-index，希望可以覆盖dialog自动生成的z-index。

可以看以下这个示例，当和wangeditor一起使用的时候，如果预览已经上传的图片，弹出的dialog会和wangeditor的toolbar冲突。

https://jsfiddle.net/33nhstx0/2/

**Comment by Leopoldthecoder** [comment]
可以通过 CSS 解决。一种方案是降低富文本编辑器父元素的 z-index：https://jsfiddle.net/33nhstx0/3/ 。还有一种方案是给 Dialog 的 z-index 加 `!important`：https://jsfiddle.net/33nhstx0/4/ 。
