### ISSUE TITLE
[Bug Report] Failure in initialization of Loading

### ISSUE THREAD

**Issue by xujiale** [ElemeFE/element#9727]
### Element UI version
2.1.0

### OS/Browsers version
Windows 10 / Chrome64.0.3282.140

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/diuqilei/fm031tko/](https://jsfiddle.net/diuqilei/fm031tko/)

### Steps to reproduce
初始化loading=false，第一次设置loading=true无效，需要设置loading=false, loading=true后才生效

### What is Expected?
正确显示loading

### What is actually happening?
需要重复设置loading才能显示

**Comment by Leopoldthecoder** [comment]
Fixed in #9722
