### ISSUE TITLE
el-table-column sortable="custom" 点击排序表头，会有BUG

### ISSUE THREAD

**Issue by pannysp** [ElemeFE/element#9729]
![image](https://user-images.githubusercontent.com/1814535/35960313-37ce9034-0ce4-11e8-9db9-bfce703a4886.png)

如图显示：点击“支付时间“来排序，提交后端返回排序的数据，但点击排序事件永远返回的是:order: "ascending"，应该是ascending和descending，轮流返回才正确啊

**Comment by fanxiaolong** [comment]
你table组件,是不是已经销毁了,或者你的组件,table的父组件使用了v-if指令,改成v-show已经就可以了.

**Comment by kid1412621** [comment]
same here!
