### ISSUE TITLE
[Bug Report] NavMenu navigation menu receiving / expanding default-active property is not equal to the current selected index value

### ISSUE THREAD

**Issue by daxiongYang** [ElemeFE/element#9734]
### Element UI version
2.1.0

### OS/Browsers version
mac OS / chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
demo默认收起 -> 展开(默认选中index="1-4-1") -> 点击其他项(选中index="1-1) -> 收起 -> 展开

### What is Expected?
default-active值还是(默认选中项index="1-4-1")

### What is actually happening?
default-active === 选中项index

**Comment by daxiongYang** [comment]
您好，抱歉JSFiddle站点我这访问不了！这个bug在官方demo就存在的，我便直接贴官方demo JSFiddle地址。

**Comment by baiyaaaaa** [comment]
default-active is not responsive, if you want to synchronized the default-active value you should change it in the `select` event
