### ISSUE TITLE
[Feature Request] Can the table component be an internal editing function?

### ISSUE THREAD

**Issue by wishlong** [ElemeFE/element#9736]
### Existing Component
Yes

### Component Name
table

### Description
现在表格的行内编辑功能可以实现吗？ 如果没有，建议加上这个功能，有的场合需要大量的使用到。包括新增一行可编辑行。

**Comment by Leopoldthecoder** [comment]
http://element-cn.eleme.io/#/zh-CN/component/table#zi-ding-yi-lie-mo-ban
