### ISSUE TITLE
[Feature Request] [Question] CSS Custom properties How to change theme colours on the fly?

### ISSUE THREAD

**Issue by algil** [ElemeFE/element#9747]
### Existing Component
Yes

### Component Name
Theme

### Description
Is it possible changing color themes from javascript? Something like this demo: https://elementui.github.io/theme-chalk-preview/#/en-US

Doesn't theme chalk use css custom properties?

It'd be great can to do this:
`document.documentElement.style.setProperty('--color-primary', someColor);`

Thanks!

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
