### ISSUE TITLE
table的row-key属性在不使用reserve-selection 功能的情况，没起效

### ISSUE THREAD

**Issue by winnieBear** [ElemeFE/element#975]
table的row-key属性在不使用reserve-selection 功能的情况，没起效，看了下代码，逻辑没走到这来。
![image](https://cloud.githubusercontent.com/assets/7059683/20175571/6f03dc70-a77e-11e6-9f85-361567b9fe62.png)

**Comment by winnieBear** [comment]
主要是想要对table新增一行，譬如在头部插入一行，整个table不要重新渲染，而是只是重新渲染新增的那一行。就是vue的` “就地复用” 策略。如果数据项的顺序被改变，而不是移动 DOM 元素来匹配数据项的顺序， Vue 将简单复用此处每个元素，并且确保它在特定索引下显示已被渲染过的每个元素。这个类似 Vue 1.x 的 track-by="$index" 。`

**Comment by furybean** [comment]
Okay，近期会加上这个功能。
