### ISSUE TITLE
[Bug Report] check-box-group can bind an object array, but it can't be checked when set a default value to binder

### ISSUE THREAD

**Issue by bvvy** [ElemeFE/element#9752]
### Element UI version
2.1.0

### OS/Browsers version
chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/262/](https://jsfiddle.net/mmx38qxw/262/)

### Steps to reproduce
set a default object value to check-box-group.

### What is Expected?
shang hai is checked

### What is actually happening?
shang hai is not  checked

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/mmx38qxw/263/
