### ISSUE TITLE
单独安装element-datepicker没有样式

### ISSUE THREAD

**Issue by seveny** [ElemeFE/element#9756]
使用npm i element-datepicker -S单独安装datepicker,其他没有设置，引入之后，发现没有样式
查看node_modules下面的element-datepicker 也没有样式文件，是需要设置什么吗
![image](https://user-images.githubusercontent.com/953633/36016886-259077c6-0db0-11e8-9198-dd030bffe62c.png)
![image](https://user-images.githubusercontent.com/953633/36016909-527028ae-0db0-11e8-8ee2-50cdf6d1914b.png)

**Comment by shengxiuzhou** [comment]
后来是怎么解决的，我也是单独安装了datepicker ,但不知道如何只引入datepicker相关的样式。全局的样式文件太大了，我不想引入全局的~
