### ISSUE TITLE
[Bug Report]  Slow rendering form a very large amount of data, rolling, Carlton

### ISSUE THREAD

**Issue by conanliuhuan** [ElemeFE/element#9761]
### Element UI version
2.1.0

### OS/Browsers version
Windows 10 Firefox Chrome / macOS 10.13 Safari

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/ws23uuv1/11/](https://jsfiddle.net/ws23uuv1/11/)

### Steps to reproduce
当表格数据非常多（30 列，500 行），且需要编辑时（有Input编辑框），填充数据后，表格渲染非常缓慢，浏览器卡顿。需要20秒左右才可以显示出来，内存占用极大。

### What is Expected?
填充数据（30 列，500 行）后，应该在2秒内快速的显示出来，不应该影响用户体验，且内存占用不应该巨大。
建议考虑使用“Virtual Scrolling”的方式，将视图以外的表格数据移除不要渲染在DOM上。

### What is actually happening?
填充数据后，表格需要20秒左右才可以显示出来，内存占用极大。对用户体验的影响很严重。

**Comment by ericcgu** [comment]
Have you considered moving logic to server side?

https://nuxtjs.org/

**Comment by liril-net** [comment]
```html
<el-input v-for="n in 30000" :key="n" />
```

@conanliuhuan 

直接渲染 30000 `el-input` 也会卡死的，和 Table 组件无关，建议进行分页处理。只渲染可视化区域确实是个有效的方案，但目前改动成本太大，暂时不会实现。

It will still stuck when rendering 30,000 `el-input` component, you can use pagination as an alternative. Of course "Virtual Scrolling" is a good solution, but it costs a lot of work to do for rendering only visual area. So we will not implement it temporary.

@ericcgu 
The main compute is not business logic but browser render, so it may not be helpful to use server side render. Thanks for your advice.

**Comment by nailfar** [comment]
element 只是个玩具而已 做大项目还是用不了  各种性能问题 各种bug  可以考虑重新选型
