### ISSUE TITLE
[Bug Report] Select element is not show default value if value is an object list

### ISSUE THREAD

**Issue by kalaomer** [ElemeFE/element#9762]
### Element UI version
2.1.0

### OS/Browsers version
any

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/t1avpsw4/](https://jsfiddle.net/t1avpsw4/)

### Steps to reproduce
When el-select has a default value which is an object of list, prepared tags did not have any label.

### What is Expected?
el-select prepare tags from default value with labels.

### What is actually happening?
Tag label is null

**Comment by littlePig-zzf** [comment]
https://jsfiddle.net/t1avpsw4/1/   你model绑定的值只要
value: [{
      	id: 123
}],就可以了

**Comment by Leopoldthecoder** [comment]
If `v-model` for Select is an object, the value of options should also be objects: https://jsfiddle.net/leopoldthecuber/t1avpsw4/2/
