### ISSUE TITLE
[Bug Report] problem with the table styles that contain fixed column and summary row

### ISSUE THREAD

**Issue by qinshenxue** [ElemeFE/element#9764]
### Element UI version
2.1.0

### OS/Browsers version
any

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/b16dkxLj/](https://jsfiddle.net/b16dkxLj/)

### Steps to reproduce
如图所示
https://user-images.githubusercontent.com/10354498/36056632-f2d7956c-0e40-11e8-95d7-4243156d51d0.png

### What is Expected?
fixed column height keep same with table height

### What is actually happening?
fixed column height  less than table height

**Comment by Leopoldthecoder** [comment]
This has been fixed in the dev branch. Please wait for our next release.

**Comment by qinshenxue** [comment]
@Leopoldthecoder  When released next version?

**Comment by Leopoldthecoder** [comment]
Before the holidays.
