### ISSUE TITLE
Switch 初始化的时候会触发 change 事件

### ISSUE THREAD

**Issue by miaosun009** [ElemeFE/element#977]
### ElementUI version
 ElementUI 1.0

### OS/Browers version
win10

### Vue version
2.03

`<template>
      <el-table :data="tableData3" border style="width: 100%" @selection-change="handleSelectionChange">
            <el-table-column type="selection" width="55"> </el-table-column>
            <el-table-column prop="id" label="编号" width="80"></el-table-column>
            <el-table-column prop="username" label="用户名" width="180"></el-table-column>
            <el-table-column prop="remark" label="描述" ></el-table-column>
            <el-table-column prop="last_login_time" label="最后登录时间"  width="200"></el-table-column>
            <el-table-column prop="last_login_ip" label="最后登录ip"  width="200"></el-table-column>
            <el-table-column inline-template label="状态" width="120" >
                <el-switch v-model="row.status" @change="change"></el-switch>
            </el-table-column>
            <el-table-column fixed="right" inline-template label="操作" width="120">
                    <el-button icon="edit" size="mini" @click="edit(row.id)"></el-button>
                    <el-button icon="delete" size="mini" @click="del(row.id)"></el-button>
            </el-table-column>
        </el-table>

        <div class="f-mt-l f-fr">
            <el-pagination layout="prev, pager, next" :total="total"> </el-pagination>
        </div>
    </template>`

我在table的"状态"一列中，用inline-template 这个属性；每行定义了一个 switch 组件 ，调试发现每一个switch会被创建两次，也会同时响应两次change 时间， 

这种情况不知道是我的使用问题，还是有BUG， 希望解答

**Comment by furybean** [comment]
Table 的锁定列的功能是由多个全面渲染的 <table> 组成的，每一列会被渲染 1 - 3 次（左锁定 + 1，又锁定 + 1）。之所以这么做，是因为锁定列的高度同步如果做成用户无感知太难了，只能用这个方式去 hack。
这应该不算 Table 的 Bug，倒应该算 Switch 的，change 事件应该只有『由用户触发的操作』才触发。 @Leopoldthecoder

**Comment by miaosun009** [comment]
@furybean  嗯，我调试了好久，最终把table的锁定列去掉了，才好了，我看了源码也觉得是switch响应change 事件有点不对， 希望下一版本能修复switch这个问题。感谢您的回答。

**Comment by Leopoldthecoder** [comment]
Fixed in #1002
