### ISSUE TITLE
The [Bug Report] calendar component firstDayOfWeek property is invalid

### ISSUE THREAD

**Issue by evilgx** [ElemeFE/element#9772]
### Element UI version
2.1.0

### OS/Browsers version
0.0.0

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/evilgx/8qm0xbf5/)

### Steps to reproduce
<DatePicker
                firstDayOfWeek={1}
                value={this.state.weekDate}
                placeholder="选择周"
                isReadOnly={true}
                onChange={date=>{
                }}
                format="yyyy 第 WW 周"
                selectionMode="week"
            />

### What is Expected?
日历组件从周一开始

### What is actually happening?
日历仍然是周日开始

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/8qm0xbf5/1/
