### ISSUE TITLE
[Feature Request] Can ElTabs provide a header average allocation mode

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#9775]
### Existing Component
是

### Component Name
Tabs

### Description
当前tab的header会根据label的文字数量而改变宽度，如果tab多过则会出现移动按钮，如果tab过少则只会占用一部分的header，右侧留空。
能否提供一种tab header根据tab的数量平均分配大小的模式，即tab总是填满header，此时文字居中。若tab过多则切换回之前的模式

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
