### ISSUE TITLE
[Bug Report] plain Button doesn't restore status after mouseup

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#9778]
### Element UI version
2.1.0

### OS/Browsers version
Windows 10 / Chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/fkpzrs6g/](https://jsfiddle.net/fkpzrs6g/)

### Steps to reproduce
click every button in the given fiddle

### What is Expected?
button should highlight after `mousedown` and restore after `mouseup`

### What is actually happening?
all plain buttons can't restore after `mouseup` while others can.
Is this a feature or a bug?

**Comment by Leopoldthecoder** [comment]
Actually in Chrome, all buttons will have the focused style after releasing the mouse. Reference: https://zhuanlan.zhihu.com/p/33714597
