### ISSUE TITLE
The [Feature Request] Select selector should allow the setting of other types of default initial values rather than empty strings

### ISSUE THREAD

**Issue by Webdiyer** [ElemeFE/element#9781]
### Existing Component
否

### Component Name
Select 选择器

### Description
大多数情况下，下拉框绑定的是值是一个int类型的数值，在很多编辑语言中，int类型的初始默认值是不允许为空的，比如C#默认是0，这种情况下页面初始化时，如果设置v-model为该属性值，则select选择器无法显示placeholder，并将0作为默认选项显示了出来，而其实0这个值是没有任何对应选项的，所以应该有一个属性可以设置Select选择器的默认初始值，让这个值和现在的空字符串值出示一样的效果。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. Reference: #9460
