### ISSUE TITLE
anybody can help me?about el-steps

### ISSUE THREAD

**Issue by liukeyan** [ElemeFE/element#9784]
<el-step title="步骤 3" description="这是一段很长很长很长的描述性文字 can you help me?"></el-step>
how to show like this 
"这是一段很长很长很长的描述性文字
can you help me?"

**Comment by liukeyan** [comment]
<el-step title="步骤 3" description="这是一段很长很长很长的描述性文字"></el-step>

**Comment by liukeyan** [comment]
el-step    description="这是一段很长很长很长的描述性文字"

**Comment by liukeyan** [comment]
el-step description="这是一段很长很长很长的描述性文字"
how to show like this
"这是一段很长很长很长的描述性文字
can you help me?"

**Comment by jiafulu** [comment]
`<ul slot="description">
    <li>这是一段很长很长很长的描述性文字这是一段很长很长很长的描述性文字</li>
    <li>这是一段很长很长很长的描述性文字这是一段很长很长很长的描述性文字</li>
    <li>这是一段很长很长很长的描述性文字这是一段很长很长很长的描述性文字</li>
</ul>`
