### ISSUE TITLE
[Bug Report] npm run dist

### ISSUE THREAD

**Issue by xuqiang521** [ElemeFE/element#9786]
### Element UI version
2.1.0

### OS/Browsers version
macOS 10.13.3

### Vue version
2.5.2

### Reproduction Link
[https://github.com/ElemeFE/element](https://github.com/ElemeFE/element)

### Steps to reproduce
npm run dist

### What is Expected?
create dist success

### What is actually happening?
/Users/pc/Desktop/element/packages/table/src/table-body.js
114:15 error Expected indentation of 16 spaces but found 14 indent

✖ 1 problem (1 error, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-ui@2.1.0 lint: eslint src/**/* test/**/* packages/**/* build/**/* --quiet
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@2.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/xuqiang/.npm/_logs/2018-02-11T16_18_26_672Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-ui@2.1.0 dist: npm run clean && npm run build:file && npm run lint && cooking build -c build/cooking.conf.js,build/cooking.common.js,build/cooking.component.js -p && npm run build:utils && npm run build:umd && npm run build:theme
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the element-ui@2.1.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/xuqiang/.npm/_logs/2018-02-11T16_18_26_705Z-debug.log

**Comment by liril-net** [comment]
@xuqiang521 
Have you downloaded the latest version of code? The error you show means that you have 14 spaces at **line 114** in file `packages/table/src/table-body.js`. Can you check any thing wrong in your code format? It should be 14 spaces there, so i do believe you have changed some where else, for example you have indent code above this line by 2 spaces.

**Comment by xuqiang521** [comment]
It is the latest version of code, I just download the code and change nothing before npm run dist,  but it has the error with eslint. of course, it is not a big problem, So i open this issue ~ . At the beginning , I just want to create a pull request add customize submenuTitleIcon to submenu component .

**Comment by liril-net** [comment]
Have you installed the dependences via yarn?
