### ISSUE TITLE
[Bug Report] Datepicker manually enter a invalid date and click away will have calendar collapse

### ISSUE THREAD

**Issue by billguan-au** [ElemeFE/element#9790]
### Element UI version
2.1.0

### OS/Browsers version
Windows 10, Chrome 63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/j6heoxLL/](https://jsfiddle.net/j6heoxLL/)

### Steps to reproduce
Click on the datepicker to pop open the calendar, then manually enter an invalid date such as date in the future of incorrect formatted date.

Try using enter key to confirm the date selection, calendar refuses to collapse - this is the correct behaviour
However, try clicking away from the date picker will have the calendar collapsed and the date is left in the input as invalid or incorrectly formatted.

### What is Expected?
When invalid or incorrectly formatted date is entered in the input, clicking away from the datepicker should have the calendar refusing to collapse

or

Previously entered valid date is restored back into the input

### What is actually happening?
When clicking away from the date picker, calendar collapses regardless.

**Comment by Leopoldthecoder** [comment]
Closed in #10749

**Comment by SatanEnglish** [comment]
@wacky6 @Leopoldthecoder 
Thanks Guys that's an awesome time turn around thanks
