### ISSUE TITLE
[Bug Report] tooltip in table comes endless loop when content is too long

### ISSUE THREAD

**Issue by troy351** [ElemeFE/element#9794]
### Element UI version
2.1.0

### OS/Browsers version
Windows 10 / Chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/fLwrqyac/2/](https://jsfiddle.net/fLwrqyac/2/)

### Steps to reproduce
open the fiddle
hover the last column

### What is Expected?
show tooltip

### What is actually happening?
tooltip doesn't show
because the tooltip content is too long that cover the original column which causing `mouseleave` and hide the tooltip.
With the tooltip hiding, `mouseenter` triggered again and become an endless loop.

**Comment by Leopoldthecoder** [comment]
主要是因为 Tooltip 内容过多，当视口较小时，Tooltip 的位置会自动上移，覆盖住 Table 的单元格。视口足够大就不会有问题：
![image](https://user-images.githubusercontent.com/10095631/37563417-166186d2-2abb-11e8-943b-286354941788.png)


请自行控制单元格的文本量，这样一个 Tooltip 弹出来对用户也不友好。
