### ISSUE TITLE
[Feature Request] Make button-group to work with dropdown buttons

### ISSUE THREAD

**Issue by tomeightyeight** [ElemeFE/element#9795]
### Existing Component
Yes

### Component Name
http://element.eleme.io/#/en-US/component/dropdown

### Description
You can't currently wrap dropdown components that have nested button components in a button-group component. 

This would be useful when creating action toolbars where the action needs to have some context change.

I've looked for an existing issue that relates to this and couldn't find anything. Hopefully this isn't a duplicate.

**Comment by Leopoldthecoder** [comment]
Actually you can do something like this: https://jsfiddle.net/leopoldthecuber/43x2mwoc/
