### ISSUE TITLE
right to left on basic tab

### ISSUE THREAD

**Issue by Mojtabarahimi8** [ElemeFE/element#9797]
### Element UI version
1.4.7

### OS/Browsers version
all browsers

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/q2nks6hn/1/](https://jsfiddle.net/q2nks6hn/1/)

### What is Expected?
in making basic tabs rtl, for active tab is need to be translate be mines to display corecttly
first tab is display on the end and vice versa

### What is actually happening?
in making basic tabs rtl, for active tab is need to be translate be mines to display corecttly

**Comment by Mojtabarahimi8** [comment]
thanks its updated

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by Mojtabarahimi8** [comment]
at least give us a solution to correct this
