### ISSUE TITLE
[Feature Request] el-menu-item align to right ex. login button should be to the right of the window

### ISSUE THREAD

**Issue by serak** [ElemeFE/element#9798]
### Existing Component
Yes

### Component Name
el-menu-item

### Description
el-menu-item should have feature to align menu items to the right. for time being i am hacking component syle="position:absolute;right:0px" which is heck tick

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by FirstJavaMaster** [comment]
@Leopoldthecoder Really don't consider implementing this function? This usage scenario is very frequent, especially when multiple elements need to float right.
![image](https://user-images.githubusercontent.com/22362110/54663593-c2bf5f80-4b1c-11e9-90d5-67858cb2b098.png)

**Comment by GreatFireWall** [comment]
@FirstJavaMaster 他们自己都要拆开实现 `el-menu` 😏 .

![image](https://user-images.githubusercontent.com/4510984/56090212-c5ba2f80-5ed1-11e9-90e2-0477c04d5f86.png)

**Comment by xudong2019** [comment]
@GreatFireWall 请问您的例子里面为什么要在.dock-right前放上".el-menu--horizontal >  "?  我试了下如果只用.dock-right{float:right;} 不会起作用，不解。

**Comment by GreatFireWall** [comment]
@xudong2019  你看一下渲染出来的结构的 class 就明白了.

**Comment by Bertagit** [comment]
A solution for all elemnts (in my app I need all elements to right) is this:
`#top-menu {
    display: flex;
    justify-content: flex-end;
  }`
