### ISSUE TITLE
[Bug Report] Filtering a lazy tree leads to performance issues

### ISSUE THREAD

**Issue by gjactat** [ElemeFE/element#9799]
### Element UI version
2.2.0

### OS/Browsers version
CodeSandbox

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/yqxw2ods/1/](https://jsfiddle.net/yqxw2ods/1/)

### Steps to reproduce
Deploy a few tree nodes. Then, try to filter the tree with the input text box.

### What is Expected?
The current tree (with some nodes already lazy loaded and some other not) should be filtered.

### What is actually happening?
The "load" method is called recursively on all nodes, defeating the purpose of lazy load.
Since my sample tree is infinite, the browser shortly hangs.
Filtering should only be applied to already deployed nodes and should not trigger new "load" calls.

**Comment by levi1994** [comment]
[https://github.com/ElemeFE/element/pull/9655](url)

**Comment by levi1994** [comment]
目测是#9655这个提交的问题
