### ISSUE TITLE
[Feature Request] The website should increase the automatic completion of email suffix

### ISSUE THREAD

**Issue by BlackHole1** [ElemeFE/element#9805]
### Existing Component
Yes

### Component Name
el-autocomplete

### Description
> English

On the [ElementUI website](http://element.eleme.io/#/zh-CN/component/input#dai-shu-ru-jian-yi), no auto complete mailbox example

I think it should be added.

This is the demo I wrote:
https://jsfiddle.net/v7stcb4c/

> 中文

网站上没有邮箱自动补全的例子

在[elementUI网站](http://element.eleme.io/#/zh-CN/component/input#dai-shu-ru-jian-yi)上，没有自动补全邮箱后缀的例子

我认为这个应该被添加

下面是我写的demo：
https://jsfiddle.net/v7stcb4c/

**Comment by Leopoldthecoder** [comment]
I don't think this is necessary. Implementing such feature should be pretty easy.
