### ISSUE TITLE
[Bug Report] Cant set height of textarea

### ISSUE THREAD

**Issue by zjxpcyc** [ElemeFE/element#9806]
### Element UI version
2.2.0

### OS/Browsers version
win10  chrome63

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/272/](https://jsfiddle.net/mmx38qxw/272/)

### Steps to reproduce
1、textarea 外包裹 一个 div,
2、div 设置一个高度
3、textarea 设置高度 100%

### What is Expected?
textarea 高度达到 100%

### What is actually happening?
然并卵

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/mmx38qxw/273/

**Comment by zjxpcyc** [comment]
@Leopoldthecoder 除了这个，有没有更优雅的方案？
