### ISSUE TITLE
[Feature Request] NavMenu needs to add a links

### ISSUE THREAD

**Issue by excitedcat** [ElemeFE/element#9809]
### Existing Component
是

### Component Name
NavMenu

### Description
在标准的html规范中，导航内元素如果路由跳转需要使用链接方式，类似这样：

```
<nav>
  <ul>
    <li><a href="index.html">Home</a></li>
    <li><a href="#about">About</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</nav>
```
方便用户右键在新窗口打开网址

**Comment by Leopoldthecoder** [comment]
You can do that: https://jsfiddle.net/leopoldthecuber/g4bhqt6o/
