### ISSUE TITLE
[Bug Report] Whats the purpose of console.error when clicking on active link?

### ISSUE THREAD

**Issue by hansenbeautyspotter** [ElemeFE/element#9811]
### Element UI version
2.2.0

### OS/Browsers version
MacOS / 64.0.3282.140

### Vue version
2.5.13

### Reproduction Link
[https://github.com/ElemeFE/element/blob/ec30f9c67d30522d3d054a8433abf5934df90fe7/packages/menu/src/menu.vue#L249](https://github.com/ElemeFE/element/blob/ec30f9c67d30522d3d054a8433abf5934df90fe7/packages/menu/src/menu.vue#L249)

### Steps to reproduce
https://github.com/ElemeFE/element/blob/ec30f9c67d30522d3d054a8433abf5934df90fe7/packages/menu/src/menu.vue#L249

### What is Expected?
not having console error

### What is actually happening?
It will print a console error if clicking on the active route

**Comment by Leopoldthecoder** [comment]
https://github.com/ElemeFE/element/commit/c6e4a11b33798957c06582d211f7a4cbb704e478
