### ISSUE TITLE
[Feature Request] Search Bar inside el-table filter

### ISSUE THREAD

**Issue by dexterannatuchua** [ElemeFE/element#9816]
### Existing Component
Yes

### Component Name
el-table

### Description
1. Also setting of max height for filter.
2. Change icon bar for filter.

![28054262_1873356229342616_1998983836_n](https://user-images.githubusercontent.com/35212423/36192409-5b5e5932-119c-11e8-8608-7353a4dd59aa.png)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. As for the max height, you can set it using CSS.
