### ISSUE TITLE
button doesn't have correct focus style

### ISSUE THREAD

**Issue by LabiKyo** [ElemeFE/element#982]
### ElementUI version
1.0.0

### OS/Browers version
macOS/Chrome 54

### Vue version
2.0.1

### What is Expected?
```html
<el-button size='large' type='primary' @click='handleSubmit'>Login</el-button>
```
`:focus` should have the same style as `:hover`

### What is actually happening?
`:focus`'s style is the same as `:link`

**Comment by Leopoldthecoder** [comment]
Fixed in 1.0.2
