### ISSUE TITLE
[Bug Report] Dropdown triggering on right click

### ISSUE THREAD

**Issue by kaungmyatlwin** [ElemeFE/element#9821]
### Element UI version
2.0.11

### OS/Browsers version
Mac OS X, Chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/ajc84nyr/](https://jsfiddle.net/ajc84nyr/)

### Steps to reproduce
1. Use Element UI dropdown component (eg. el-dropdown)
2. Right click on it (in this case I want to override browser context menu to show a custom context menu)

### What is Expected?
Only the context menu should be shown, dropdown should be disabled at that point.

### What is actually happening?
Both context menu and dropdown is shown.

**Comment by kaungmyatlwin** [comment]
FYI, this usually happens in components where `el-input` is focused.

**Comment by Leopoldthecoder** [comment]
Fixed in #9894
