### ISSUE TITLE
[Feature Request] component table html structure rework

### ISSUE THREAD

**Issue by sanyashvets** [ElemeFE/element#9822]
### Existing Component
Yes

### Component Name
table

### Description
now we have `table` component, which contains separate `<table>` tags for each head, body of `table` component and matching width programmatically  on init, resize, etc
I have huge problems with flex-model of main page styles and table and responsive, of course.  For example, adding sort and filter params to table columns makes width of cells isnt equal (compating header and body cells). Also, I have lags during resizing of table and re-calculating its width.
Franky speaking, your demo site also lags during resizing from desktop to mobile sizes.

I'd like to have table, based on flex styles without separating it into different and undepended `<table>` tags. It gives us maximum flexible reaction on resize without unneccessary JS width calculations and no `style="width:****px"` in html code

From my investigations, it works good on increasing and bad on reduction in size

**Comment by willvincent** [comment]
Experiencing the same.

If using flex for layout, resizing only triggers on enlargement, not decreasing width.  This appears to be a problem with the resize listener entirely failing to fire when decreasing window size.

Whether the table markup is changed, or the resize listener is fixed, one or the other needs to occur as this is really unusable in it's current state.

**Comment by ffxsam** [comment]
So, there are a couple issues at play here:

1. The call to `addResizeListener(this.$el, this.resizeListener)` which is a polyfill for the resize observer doesn't actually fire off when the browser window is shrunk.
2. Once we replaced this with a native `window.addEventListener('resize', this.resizeListener)` call, it fired off consistently, but the code to figure out the table width/height failed to work properly, so no table updates were rendered.

**Comment by clementdubois** [comment]
Hi have the same issue using css grid layout. Increasing the size works well but decreasing the size doesn't work, it keep is current size.
