### ISSUE TITLE
[Feature Request] Show 'valid' status icon for pre-filled fields

### ISSUE THREAD

**Issue by danherd** [ElemeFE/element#9824]
### Existing Component
Yes

### Component Name
Select

### Description
I would like to pre-select an option in a select dropdown and also show that the pre-filled value is valid before validation is triggered. Is there a class or anything I can apply to the form element that can show the little green tick?

**Comment by Leopoldthecoder** [comment]
You can add the `class="is-success"` on `<el-form-item>` to turn its border green (https://jsfiddle.net/leopoldthecuber/bpx1hwj0/5/ ), but to show the green tick you'll have to manually trigger validation using JavaScript: https://jsfiddle.net/leopoldthecuber/bpx1hwj0/4/

**Comment by danherd** [comment]
But triggering validation validates the whole form, meaning every other field will display as invalid: https://jsfiddle.net/82ds3a7b/3/

**Comment by Leopoldthecoder** [comment]
Then you can use `validate` on a specific `<el-form-item>`: https://jsfiddle.net/leopoldthecuber/82ds3a7b/7/ . It is not documented in the docs, but is stable enough to use in production.

**Comment by danherd** [comment]
Actually, I've realised I could validate the form on mount, then add the rules for the other fields afterwards! Thanks for your help. Will post a jsfiddle soon for anyone else needing help with this.

**Comment by danherd** [comment]
Oh, even better than my solution! Thanks.
