### ISSUE TITLE
[Bug Report] NavMenu with router sync

### ISSUE THREAD

**Issue by llfbandit** [ElemeFE/element#9825]
### Element UI version
2.1.0

### OS/Browsers version
W10 / Firefox 58

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
- add a menu with two steps
```
<el-menu ref="user-menu" :router="true" mode="horizontal" default-active="/path1">
      <el-menu-item index="/path1">PATH 1</el-menu-item>
      <el-menu-item index="/path2">PATH 2</el-menu-item>
    </el-menu>
```

- when calling directly a route, the menu is not updated

### What is Expected?
Not sure if it's a bug or a feature request but I have a menu with router option and the menu items are not reflecting the current route path

### What is actually happening?
the menu items are not updated

For now, I handle this by adding this code:

```
watch: {
    '$route' (to, from) {
      this.updateSelectedTab();
    }
  },

  mounted() {
    this.updateSelectedTab();
  },

  methods: {
    updateSelectedTab() {
      // sync active tab with route, element menu bug ???
      const menu = this.$refs['user-menu'];
      if (menu && menu.activeIndex !== this.$route.path) {
        menu.activeIndex = this.$route.path;
      }      
    }
  }
```

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
