### ISSUE TITLE
[Feature Request]  Do you have a password type entry?

### ISSUE THREAD

**Issue by leoutnlp** [ElemeFE/element#9827]
### Existing Component
No

### Component Name
el-input

### Description
there would be a component equal to `<input type = "password" />`

**Comment by Leopoldthecoder** [comment]
https://jsfiddle.net/leopoldthecuber/rodn81tq/1/

**Comment by leoutnlp** [comment]
Thank you very much.
Sorry, in the documentation of "Input Attributes" it says that the type is
only "text / textarea"
http://element.eleme.io/#/en-US/component/input

2018-02-16 9:38 GMT-03:00 杨奕 <notifications@github.com>:
