### ISSUE TITLE
[Bug Report] Broken scroll el-select

### ISSUE THREAD

**Issue by zont** [ElemeFE/element#9828]
### Element UI version
2.2.0

### OS/Browsers version
all

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/w2za0mL9/1/](https://jsfiddle.net/w2za0mL9/1/)

### Steps to reproduce
1) make some scrollable containers, put el-select into it
2) click on select: dropdown is opened
3) sroll container

### What is Expected?
Dropdown list is change position

### What is actually happening?
Dropdown list is not change position

**Comment by Leopoldthecoder** [comment]
You can try `popper-append-to-body`: https://jsfiddle.net/leopoldthecuber/w2za0mL9/10/ , which is added in 2.2.0. Now there's an unnecessary horizontal scroll bar at the popper bottom, but is fixed in #9835.

**Comment by zont** [comment]
With `popper-append-to-body` dropdown list in incorrect position:
https://jsfiddle.net/w2za0mL9/13/

1. scroll to bottom
2. click on select

Expected: dropdown list under the select

Actual: dropdown list out of frame

**Comment by zont** [comment]
Up

**Comment by zont** [comment]
Up

**Comment by OrhanOzkercin** [comment]
When I set `popper-append-to-body` to false. Now this problem occurs. The dropdown should expand above.

![image](https://user-images.githubusercontent.com/25130814/139665035-9f02f988-3c1b-4e61-a7ed-a1a8055413dc.png)
