### ISSUE TITLE
[Feature Request] Add "checked" parameter to "select" table event

### ISSUE THREAD

**Issue by vloginov** [ElemeFE/element#9829]
### Existing Component
Yes

### Component Name
table

### Description
When user clicks the checkbox in a row, table emits "select" event which passes to the callback to parameters - "selection" and "row". I believe it would be super helpful to add third argument "checked" to inform about current state of the checkbox of the row. I'm having hard time without this feature. Is there any other way to know whether checkbox was set or unset?

**Comment by Leopoldthecoder** [comment]
This may help: https://jsfiddle.net/leopoldthecuber/cadnv7zz/3/

**Comment by vloginov** [comment]
Thank you!
