### ISSUE TITLE
增强表单验证功能

### ISSUE THREAD

**Issue by LabiKyo** [ElemeFE/element#983]
表单的api无法和验证互动，既不能获取valid状态，也不能设置error

**Comment by Leopoldthecoder** [comment]
> 不能设置error

是指想自定义验证失败的信息？如果是的话，文档的表单验证部分有说明。

**Comment by LabiKyo** [comment]
[http://element.eleme.io/#/component/form#biao-dan-yan-zheng](http://element.eleme.io/#/component/form#biao-dan-yan-zheng) 指的是这个文档么？我反复看了很多遍，没有找到控制error的地方。

我的意思不是控制validator message，而是比如提交表单远程验证之后，api返回的结果告诉我某个field有错误，我应该能够把这个错误输出到form-item上面。或许不是直接操作formItem.error，用其他更好的方案也可以。我现在暂时只能直接操作error（文档里没有体现）

**Comment by Leopoldthecoder** [comment]
ping @baiyaaaaa

**Comment by Leopoldthecoder** [comment]
Fixed in #1221
