### ISSUE TITLE
[Feature Request] Cancel/Apply buttons on Datepicker range

### ISSUE THREAD

**Issue by filipajdacic** [ElemeFE/element#9834]
### Existing Component
Yes

### Component Name
DatePicker

### Description
I am wondering because I was not able to find out how to enable footer buttons for Date Range picker?
Right now, I can see that buttons on DateTime Range picker, but on Date Range picker (picker without time) they don't exist.

Also, if there is a possibility to if I click on some of the predefined date range for date picker to not close and change the dates until I click Apply button?

Thanks in advance!

**Comment by liril-net** [comment]
I am sorry, but only `datetime` and `datetimerange` would show footer at current version(v2.2.0). We will discuss whether to expose this `prop` to users.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
