### ISSUE TITLE
[Feature Request] Support for element queries

### ISSUE THREAD

**Issue by abhipanda** [ElemeFE/element#9836]
### Existing Component
Yes

### Component Name
Layout

### Description
Element queries are a new way of thinking about responsive web design where the responsive conditions apply to elements on the page instead of the width or height of the browser.

Unlike CSS @media queries, @element Queries are aware of more than just the width and height of the browser, we can write responsive conditions for a number of different situations like how many characters of text or child elements an element contains.

Ref:

https://elementqueries.com/

https://tomhodgins.github.io/element-queries-spec/element-queries.html

**Comment by Veitor** [comment]
support +1!

I think it is necessary to add this.

Ref:

https://webdesign.tutsplus.com/zh-hans/tutorials/element-queries-the-future-of-responsive-web-design--cms-26945
