### ISSUE TITLE
[Feature Request] Change render-header property to a scoped-slot

### ISSUE THREAD

**Issue by TimYi** [ElemeFE/element#9837]
### Existing Component
是

### Component Name
ElTableColumn

### Description
A scoped-slot is more easy to use than a render-header property.

**Comment by VinceBassman** [comment]
Would be great to have this enhancement. Did you already plan it?

**Comment by ivanseidel** [comment]
Would be very useful for me as well

**Comment by breadadams** [comment]
I think this one can be closed, functionality seems to be implemented (https://element.eleme.io/#/en-US/component/table#table-column-scoped-slot).

**Comment by TimYi** [comment]
Yes, this function is already implemented.
