### ISSUE TITLE
upload组件thumbnail-mode模式下可否添加初始图片？

### ISSUE THREAD

**Issue by agileago** [ElemeFE/element#984]
现在上传组件 thumbnail-mode模式只有在上传完成后才显示预览图片，但我在表单编辑的时候需要把上次上传过得图片显示出来，目前看来uoload组件无法满足需求，是否可以加个`prop` `thumbnail-img`属性代表默认显示的图片？

**Comment by Lanceloft** [comment]
upload组件，header传输object的格式是怎么样呢

**Comment by Lanceloft** [comment]
upload组件里面，headers 类型为object，格式是怎么样呢。

**Comment by laughmaker** [comment]
const UPLOAD_HEADER = { token: TOKEN }
headers就是这样子的。

**Comment by agileago** [comment]
上面2位是不是走错issue了？

**Comment by baiyaaaaa** [comment]
@agileago 已支持 #1393
