### ISSUE TITLE
[Feature Request] Change scss variables with on-demand plugin

### ISSUE THREAD

**Issue by cristijora** [ElemeFE/element#9842]
### Existing Component
No

### Component Name
No component

### Description
The documentation provides some ways of redefining sass variables, however, it would be great if on-demand import will work with custom sass variables without generating a theme.
Use case on potential usage:
1. Create a new file with variables `element-variables.scss`
2. Overwrite some variables in it. `$--color-primary: red`
3. Use `babel-plugin-component` normally without generating a new theme with `et`

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by cristijora** [comment]
@Leopoldthecoder any starting points on how this could be potentially implemented? 
Tried specifying directly the `scss` files with https://github.com/ElementUI/babel-plugin-component but without luck. 

I'd be open to make a PR either here or to babel-plugin-component.
