### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by santiblanko** [ElemeFE/element#9844]
### Element UI version
2.2.0

### OS/Browsers version
safari

### Vue version
2.5.13

### Reproduction Link
[jsfiddle.com/idonthave](jsfiddle.com/idonthave)

### Steps to reproduce
other-1e4bc.firebaseapp.com

### What is Expected?
Slider like other.

### What is actually happening?
don't slide good.

**Comment by Leopoldthecoder** [comment]
Issues without a valid reproduction link will be closed directly.
