### ISSUE TITLE
[Bug Report] Form validation not working in `defaultField` rules

### ISSUE THREAD

**Issue by riku179** [ElemeFE/element#9845]
### Element UI version
2.2.0

### OS/Browsers version
Linux / Chrome v64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/wfckkbya/20/](https://jsfiddle.net/wfckkbya/20/)

### Steps to reproduce
Bind validation rules that use `defaultField` to validate array of multiple fields on `el-form`.

### What is Expected?
Form validation is working.
As below, `async-validator` used in el-form is working well in this situation.

https://runkit.com/embed/m4y80n4lhvk0

### What is actually happening?
Form validation is not working.

**Comment by tecnoloco** [comment]
This should be done, any way I can help? I passed a lot of hours thinking I was doing something wrong with my el-form rules object.
