### ISSUE TITLE
[Feature Request] Date Range selector: add a 'current' or 'present' option

### ISSUE THREAD

**Issue by web-surfer** [ElemeFE/element#9849]
### Existing Component
Yes

### Component Name
Date-Picker

### Description
For the Date-Picker component, there is a Date Range option that lets you select 2 dates: a start date, and an **end date**. It would be nice if the **'end date'** could have an option for a user to select '_current_' or '_present_', to indicate an on-going event.

**Comment by wacky6** [comment]
But how would you represent "current/present/on-going"?
`+Infinity`? (LMAO)

**Comment by web-surfer** [comment]
In databases like Postgres, you can represent an on-going date with `infinity`.

**Comment by wacky6** [comment]
Unfortunately, JS does not work this way. And date can not be Infinity. Though you can make something like `new Date(Math.pow(2,52))`.

I doubt this will ever be endorsed by other maintainers.

**Comment by wacky6** [comment]
The closest one could be `new Date(NaN)`.
