### ISSUE TITLE
[Feature Request] Date Picker onClear event

### ISSUE THREAD

**Issue by kaungmyatlwin** [ElemeFE/element#9850]
### Existing Component
Yes

### Component Name
Date Picker

### Description
Date Picker has @change event where we can get date changes. There is clearable attribute but it doesn't trigger method in @change. Can we have @clear event to bind a method for clearing the date?

**Comment by wacky6** [comment]
https://jsfiddle.net/573apv5q/2/

Clear button does trigger change event
