### ISSUE TITLE
[Feature Request]  When Cascader option clicked, close Cascader

### ISSUE THREAD

**Issue by lujunpeng** [ElemeFE/element#9851]
### Existing Component
是

### Component Name
Cascader

### Description
Cascader  
expand-trigger: hover
change-on-select: true
点击选项时，关闭Cascader

**Comment by lujunpeng** [comment]
Translation of this issue:

Existing Component
yes

Component Name
Cascader

Description
Cascader

Expand-trigger: hover
Change-on-select: true

When you click the option, close the Cascader

**Comment by wzwxwc** [comment]
全是链接和调整，能给个明白话不。。。看了半天都不知道你们
如何实现对这个控件的新需求：点击关闭需求

**Comment by ym13349140** [comment]
@wzwxwc 上面的链接都是别人引用到了这个issue，而且在下面这次commit已经解决了这个需求吧，我现在用的时候就是选中之后会自动关闭（虽然我的需求是要它不要关闭，囧......），如果想更清楚具体原理的话可以点击下面的链接看看具体改动的源码。
#11623

**Comment by coffee4code** [comment]
`this.$refs['your-cascade-comp'].toggleDropDownVisible()` working properly.

**Comment by htye** [comment]
> `this.$refs['your-cascade-comp'].toggleDropDownVisible()` 好好工作。

感谢感谢！能问一下这个是在源码里找到的吗？文档好像没有？
