### ISSUE TITLE
[Feature Request] Table multiple select with actions

### ISSUE THREAD

**Issue by smilee** [ElemeFE/element#9864]
### Existing Component
Yes

### Component Name
Table

### Description
Currently, there's no way to perform bulk actions on table row selections although selections can be made. If something showing bulk actions popped out somewhere, it would be helpful to many use cases. :)

**Comment by ChangJoo-Park** [comment]
related pull request is here https://github.com/ElemeFE/element/pull/9863

**Comment by QingWei-Li** [comment]
I wondering why not directly used table selections.

**Comment by smilee** [comment]
You can use table selections, but I was thinking more in lines of having a set of bulk actions pop up somewhere when selections are made. :)

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
