### ISSUE TITLE
 [Bug Report] The CSS attribute flex-basis of the el-main is set to auto to cause the el-aside fixed width to be affected

### ISSUE THREAD

**Issue by young7657** [ElemeFE/element#9865]
### Element UI version
2.2.0

### OS/Browsers version
win10 / chrome 64.0.3282.119

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/rujt4zjk/7/](https://jsfiddle.net/rujt4zjk/7/)

### Steps to reproduce
使用el-main和el-aside搭建左侧宽度固定、右侧宽度自适应的两栏布局，el-aside设置固定宽度，el-main没有设置宽度。
当el-main里内容不多时，布局显示正常。当el-main里存在过多文本或标签内容时，el-aside设置的宽度失效，实际宽度会被压缩。

### What is Expected?
使用el-aside和el-main实现左侧宽度固定，右侧宽度自适应的两栏布局。

### What is actually happening?
el-main标签内存在过多内容时，el-aside设置的宽度失效，实际宽度会被压缩。

**Comment by Leopoldthecoder** [comment]
Fixed in #9812

**Comment by young7657** [comment]
thank you very much
