### ISSUE TITLE
Can the height or max-height of the [Feature Request] table component support the dynamic calculation of the function?

### ISSUE THREAD

**Issue by zhongyue2332** [ElemeFE/element#9870]
### Existing Component
Yes

### Component Name
el-table

### Description
很多时候高度和宽度是不定的，例如flex布局的时候

**Comment by Leopoldthecoder** [comment]
参考 https://github.com/ElemeFE/element/issues/8896 和 https://jsfiddle.net/Lb3yLo2r/3/
