### ISSUE TITLE
[Feature Request] component tag need "click" event

### ISSUE THREAD

**Issue by tower1229** [ElemeFE/element#9872]
### Existing Component
是

### Component Name
Tag

### Description
plese add "click" event for component tag

**Comment by Leopoldthecoder** [comment]
是 Tag 还是 Tab？作用是？

**Comment by tower1229** [comment]
@Leopoldthecoder 是tag，有了click事件，再配合原有的closable特性可以实现一个集增加、删除、使用于一体的标签组。
增加@click的同时还需要增加一个:value属性，作为click回调方法的参数。
![tagcomp](https://user-images.githubusercontent.com/4016839/36624830-7ae61d16-194f-11e8-9174-a3c306ab4e67.png)

**Comment by Leopoldthecoder** [comment]
@click.native https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components

**Comment by tower1229** [comment]
这样啊，怪我文档看的不仔细
