### ISSUE TITLE
[Bug Report] DateTimePicker input value should not be changed when user not confirm the picked date

### ISSUE THREAD

**Issue by PanJiaChen** [ElemeFE/element#9873]
### Element UI version
2.2.0

### OS/Browsers version
Mac / Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/L9mpyv5e/1/](https://jsfiddle.net/L9mpyv5e/1/)

### Steps to reproduce
Pick the date
![datetimepick](https://user-images.githubusercontent.com/8121621/36624494-0922b012-194b-11e8-9fbe-1fa5dae7b4f4.gif)

### What is Expected?
DateTimePicker input value should not be changed when user not confirm the date

### What is actually happening?
DateTimePicker input value is computed with the user picked date.

**Comment by wacky6** [comment]
It's changed to current behavior to be consistent with TimePicker's behavior. You can verify that in 2.0 and 1.4, TimePicker emits value without hitting confirm.

Maybe we need to add a cancel button in this case.

**Comment by Leopoldthecoder** [comment]
This is by design. Actually other popular component libraries (like [ant design](https://ant.design/components/date-picker-cn/#components-date-picker-demo-time)) also apply the same design.
