### ISSUE TITLE
[Feature Request] table header merge requirements

### ISSUE THREAD

**Issue by huangningfa** [ElemeFE/element#9875]
### Existing Component
是

### Component Name
el-table

### Description
原有spanMethod属性可以合并表内容，但无法向左向右合并表头，如下图“科目”
![image](https://user-images.githubusercontent.com/22051092/36625131-8a4136ec-1954-11e8-8c3e-4728bdac9dd0.png)

**Comment by Learnliang** [comment]
I have the same problem ,somebody help?
