### ISSUE TITLE
[Bug Report] el-table header column width and content column width are not homogeneous

### ISSUE THREAD

**Issue by zh68319220** [ElemeFE/element#9877]
### Element UI version
2.2.0

### OS/Browsers version
windows 10 chrome 63.0.3239.108

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/ux5j2zg0/14/](https://jsfiddle.net/ux5j2zg0/14/)

### Steps to reproduce
不断拉大预览框的width

### What is Expected?
el-table表头列宽度与内容列宽度对齐

### What is actually happening?
当预览框的width越大（即table的宽度越大），el-table表头列宽度与内容列宽度的误差越大。
当预览框的width越小（即table的宽度越小），el-table表头列宽度与内容列宽度的误差越小。

**Comment by Leopoldthecoder** [comment]
![clip](https://user-images.githubusercontent.com/10095631/36630191-4a1c6b42-199d-11e8-9d45-08b86d3433ea.gif)

无法重现。

**Comment by zh68319220** [comment]
@Leopoldthecoder https://jsfiddle.net/ux5j2zg0/24/
![tim 20180306161633](https://user-images.githubusercontent.com/13728178/37021256-ea9d6b2a-2159-11e8-9e59-381603ec76ae.png)
![tim 20180306161653](https://user-images.githubusercontent.com/13728178/37021257-eae124d2-2159-11e8-9dbc-01beef87a0f7.png)
![tim 20180306161719](https://user-images.githubusercontent.com/13728178/37021258-eb24afb8-2159-11e8-9f52-951b9728d8b1.png)

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/37036289-2ca533a6-218a-11e8-9c89-a3ac9519a562.png)

在 windows 上仍未重现。由于没有其他用户反馈相同问题，这个 issue 先关闭了。建议换台机器尝试。

**Comment by zh68319220** [comment]
@Leopoldthecoder 也不知道这算不算BUG：
![image](https://user-images.githubusercontent.com/13728178/38020555-270d6498-32ad-11e8-831d-24f8fa808dc5.png)
win10的[显示设置]-[推荐缩放比]推荐的是125%，如果我设置成125%，el-table的表格就会对不齐；如果设置成100%就无法重现这个问题

**Comment by varHarrie** [comment]
遇到相同问题，情况与上述一致，设置缩放比例125%（系统默认）出现问题：
![image](https://user-images.githubusercontent.com/14304201/40166858-313dfa42-59f2-11e8-9de3-2bb826ff5b91.png)

缩放比例设为100%或者出现滚动条时，就没问题了：
![image](https://user-images.githubusercontent.com/14304201/40166964-6447b23e-59f2-11e8-8b66-68c55acd0e30.png)

**Comment by Dynan7** [comment]
same problem with increase custom dpi on Ubuntu 20.04
