### ISSUE TITLE
[Feature Request] DatePicker Design Improvement

### ISSUE THREAD

**Issue by wacky6** [ElemeFE/element#9878]
### Description
`{Date, Time, DateTime}Picker`, including `{Year, Month, Week, *Range}` derivatives, **are bundled together**. This makes the output size unnecessarily large.

In fact, it is one of the largest components in element-ui.

### Reasons:

* If one only uses DatePicker, other panels are still bundled. (wasted bytes)
* Improve code readability / maintainability (reduce 'if's regarding `type`, `isRanged`, etc)
* Encourage type / panel specific behaviors without having to worry about others
* Move `picker-options` to component tag, improve readability?
* Reuse / share basic components ({date, month, year} table)
* Split documentation, so developers are less likely to get confused about attributes

Therefore, I make this proposal to bundle/write these components separately. It could follow ant.d's style: https://ant.design/components/date-picker/ , for example: 

```jsx
<el-date-picker />
<el-date-time-picker />
<el-week-picker />
<el-time-picker />
...
```

Will be a **breaking change**, might be considered for 3.0 milestone.

### Additional Notes
* Expose underlying {date, month, year} table, so developers can build custom components https://github.com/ElemeFE/element/issues/12779. (eg: inline date-picker or simple calendar)
* Offer a common interface, so Time{Select, Picker} can be used interchangeably, see: https://github.com/ElemeFE/element/issues/8979, https://github.com/ElemeFE/element/issues/8912, https://github.com/ElemeFE/element/issues/11818, https://github.com/ElemeFE/element/issues/11594, https://github.com/ElemeFE/element/issues/13766 (i.e `value`'s format, input/change event emission behavior), 
* Support for week format (i.e. ISO-8601). May need to change underlying parser. Current parsing / formatting method is inappropriate (not modular). https://github.com/ElemeFE/element/issues/13746 https://github.com/ElemeFE/element/pull/13754
* Reactive panel type is possible. But I suspect for most use cases, panel type is fixed. If panel type does needs to be changed, use v-if to re-render the entire component is more appropriate: https://github.com/ElemeFE/element/issues/12119
* Expose underlying fecha parser / formatter
* Might be interested in https://github.com/linusborg/portal-vue to render panels elegantly
* Support custom format / parse function: https://github.com/ElemeFE/element/issues/11353 https://github.com/ElemeFE/element/issues/14612
* Better way to set disabled date and disabled time (group of ranges maybe?), try to improve performance?
* Make internal states one-way data-flow compliant: https://github.com/ElemeFE/element/issues/13015
* (low priority) Make time-picker support custom time range / step / start / end: https://github.com/ElemeFE/element/issues/13158
* Clear distinction between `value` and current selection: https://github.com/ElemeFE/element/issues/13103, https://github.com/ElemeFE/element/issues/9873
* More control over buttons: https://github.com/ElemeFE/element/issues/13880

Also see: https://github.com/ElemeFE/element/issues/8727

### Bundle analyzer output
![image](https://user-images.githubusercontent.com/9319556/36627905-00c6971e-199e-11e8-9806-80d4b70d3a23.png)

### Code before / after this proposal
Before:
```
<el-date-picker v-model="date" :pickerOptions="pickerOptions" />

data: {
  pickerOptions: {
    disabledDate(date) { ... }
  }
}
```

After:
```
<el-date-picker v-model="date" :disabledDate="disabledDate" />

data: {
  disabledDate(date) { ... }
}
```

**Comment by Altamill** [comment]
Is it possible to complete this change during the schedule or how long? 
If you can use TimePicker's picker options method in datepicker, it really greatly reduces the workload of our front and back ends.

**Comment by wacky6** [comment]
Sadly, there is no schedule for implementation. 

As mentioned, this will be a HUGE breaking change. Most of the internals will have to be rewritten. It might come with 3.0 of element-ui, or not getting implemented at all.

**Comment by buremba** [comment]
Any updates yet?

**Comment by orange-buffalo** [comment]
Hey @stalebot, this issue is still relevant.

**Comment by zazzaz** [comment]
Most of the changes mentioned above are implmented in Element Plus for Vue 3.0.

Check it here https://github.com/element-plus/element-plus/issues

**Comment by iamkun** [comment]
Close due to "done in Element Plus for Vue 3.0"
