### ISSUE TITLE
After using the fixed of [Feature Request] form component, the horizontal scroll bar appears only in the non fixed column, but does not appear on the fixed column. The current version will run through the entire form.

### ISSUE THREAD

**Issue by dwt11** [ElemeFE/element#9880]
### Existing Component
是

### Component Name
Table 表格

### Description
谢谢
版本2.2, 表格组件使用fixed 定义最左侧两个列后,
横向滚动条会贯穿整个表格,这样会导致点击最左侧两条处的横向滚动条无法左右拖动,
必须避开这两列才能拖动,
能否固定的这两列,不显示横向滚动条,
只在非固定列显示横向滚动条

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/36881784-ffe297be-1e0a-11e8-92b6-01a76bb3ae97.gif)

无法复现。有问题请写一个 demo，然后新开一个 issue。
