### ISSUE TITLE
[Feature Request] Table should provide option for exclusive filtering

### ISSUE THREAD

**Issue by albru123** [ElemeFE/element#9881]
### Existing Component
Yes

### Component Name
Table

### Description
In current implementation of table filtering, each row is checked one by one against each value selected in the filter, making it an inclusive (OR) filter effectively. However one table column may contain multiple values, especially when using custom column templates. That means when I select two options in the filter, I get rows where one or both selected values are present. However I'd like to get rows where only both selected values pass my filtering method.

This can be done two ways:
1. By setting the mode on the component itself 
Calling `values.every()` or `values.some()` based on the mode selected here: https://github.com/ElemeFE/element/blob/061130e1c76e0d960ba90978ca7f777cecb0a5e8/packages/table/src/table-store.js#L212
2. By passing all the selected values to the filtering function and letting user handle it completely

### Current filter example
Example table:

|Colors|
|---|
|Red|
|Red Blue|
|Blue|

I select **Red** and **Blue** filter

Current filter result:

|Colors|
|---|
|Red|
|Red Blue|
|Blue|

Desired result:

|Colors|
|---|
|Red Blue|

**Comment by QingWei-Li** [comment]
PR Welcome.

**Comment by albru123** [comment]
Sure a thing, I'll try to implement it.

**Comment by maltegrosse** [comment]
@albru123 any news?
