### ISSUE TITLE
[Feature Request] Nuxt.js integration instructions in the documentation

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [ElemeFE/element#9883]
### Existing Component
Yes

### Component Name
Any

### Description
Please, add Nuxt.js integration instructions into **Quick Start** Documentation section

**Comment by AndrewBogdanovTSS** [comment]
I don't these changes reflected in http://element.eleme.io/#/en-US/component/quickstart
do they need to be pushed to production?

**Comment by Leopoldthecoder** [comment]
Docs will update once we release a new patch.
