### ISSUE TITLE
[Feature Request] Prefix Icon for Select

### ISSUE THREAD

**Issue by pmochine** [ElemeFE/element#9885]
### Existing Component
Yes

### Component Name
Select

### Description
I'm not able to set a prefix icon in Select. 

My original task is to have a time picker that shows:

    16:00-16:30
    16:30-17:00
    17:00-17:30

I'm not able to this with Time Picker, so I'm using Select. But it would be great to use the same clock icon in Select as Prefix Icon.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
