### ISSUE TITLE
[Bug Report] NavMenu - Redundant Error Console Log When Clicking Same Menu Item in Vue Route Mode

### ISSUE THREAD

**Issue by jinweijie** [ElemeFE/element#9886]
### Element UI version
2.2.0

### OS/Browsers version
Windows 10 / Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Vue version
2.5.13

### Reproduction Link
Sorry, it's just a small code check, so no reproduction link.

### Steps to reproduce
1. in routeToItem function,  this.$router.push(route, function () {}, onError); , actually according to vue router's documenation, the third parameter is onAbort. router.push(location, onComplete?, onAbort?) (https://router.vuejs.org/en/essentials/navigation.html)
2. and in handleItemClick function, when calling routeToItem, it passes the onError function.
3. Since when clicking the same link, the vue router will raise the onAbort event, so onError will be get called.
4. And there will be an error logged in the console (undefined) since: 
     if (this.router) {
        this.routeToItem(item, function (error) {
          _this.activeIndex = oldActiveIndex;
          console.error(error);
        });
      }
5. It's better to check the error before logging, like:
    if (this.router) {
        this.routeToItem(item, function (error) {
          _this.activeIndex = oldActiveIndex;
         if(error) //check if error exist, when clicking the same menu, it's undefined.
             console.error(error);
        });
      }
     

### What is Expected?
No error should be log to console when clicking the same menu item in router mode.

### What is actually happening?
An redundant error log (undefined) is logged to console when clicking the same menu item in router mode.

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/element/pull/9871
