### ISSUE TITLE
When [Bug Report] dynamically increases el-menu-item, the use of the isCollapse attribute causes the interface to display bug

### ISSUE THREAD

**Issue by K-walker** [ElemeFE/element#9887]
### Element UI version
2.1.0

### OS/Browsers version
win7 64 / chrome 

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/vL8eh0yp/13/](https://jsfiddle.net/vL8eh0yp/13/)

### Steps to reproduce
点击“收起”按钮

### What is Expected?
导航处于收缩状态时，导航文字能够隐藏

### What is actually happening?
导航处于收缩状态时，导航文字仍然显示

**Comment by Leopoldthecoder** [comment]
In your demo, you are wrapping `<el-menu-item>` in a `<div>`, so the rendered DOM is:

![image](https://user-images.githubusercontent.com/10095631/36651794-9f4d6da2-1ae5-11e8-8b9a-f01ac43f4624.png)

According to the spec, `<div>` is not a permitted child of `<ul>`. You should find a way to eliminate that `<div>`.

**Comment by K-walker** [comment]
@Leopoldthecoder 我尝试了把div换成其他标签，还是会出现这个问题，还有一点不知道您有没有发现，第一个导航 “首页” ，在收缩时文字是隐藏的，只有当有多级子菜单时的导航，才会出现这个情况，所以应该不会是这个div标签的问题吧，不然“首页”这个导航的文字也不可能正常隐藏了啊
