### ISSUE TITLE
Whether the selected Association of the parent and child nodes of the [Feature Request] tree can be controlled by parameters

### ISSUE THREAD

**Issue by Evil-S** [ElemeFE/element#9889]
### Existing Component
Yes

### Component Name
tree

### Description
在开发时遇到一个用到树的场景：
比如我选择省市区的时候，例如浙江 杭州 滨江区（等几个区）都有一些监控站点，杭州市有杭州市的，并不是代表杭州市选中杭州市节点就是选中所有杭州市下的所有区划的监控站点，并且选中所有的杭州市下的区划的监控节点并不代表我选中了杭州市的监控节点，虽然这不符合树的逻辑，但是业务场景是有的，请问这种情况有什么好的解决方案？

**Comment by QingWei-Li** [comment]
可以使用自定义节点内容的功能，放一个自定义的 checkbox list

http://element.eleme.io/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong

Demo
https://jsfiddle.net/j9a309gf/4/
