### ISSUE TITLE
我通过ref来open只能打开modal看不到dialog

### ISSUE THREAD

**Issue by zdz1993** [ElemeFE/element#989]

**Comment by zdz1993** [comment]
render(h) {
        return(
            <el-dialog title="在线创建" ref="dialog" on-open={this.open} on-close={this.close} size="tiny">
                <el-form >
                    <el-form-item label="手机号" label-width="90px" required>
                        <el-col span={20}>
                            <el-input></el-input>
                        </el-col>
                    </el-form-item>
                    <el-form-item label="其他号码" label-width="90px">
                        <el-col span={20}>
                            <el-input></el-input>
                        </el-col>
                    </el-form-item>
                    <el-form-item label="商户名" label-width="90px" required>
                        <el-col span={20}>
                            <el-input></el-input>
                        </el-col>
                    </el-form-item>
                    <el-form-item label="地址" label-width="90px" required>
                        <el-col span={20}>
                            <el-input></el-input>
                        </el-col>
                    </el-form-item>
                    <el-form-item label="区域" label-width="90px" required>
                        <el-col span={20}>
                            <el-input></el-input>
                        </el-col>
                    </el-form-item>
                    <el-form-item label="项目编号" label-width="90px" required>
                        <el-col span={20}>
                            <el-input></el-input>
                        </el-col>
                    </el-form-item>
                </el-form>
                <div slot="footer" class="dialog-footer">
                    <el-button type="primary">取消</el-button>
                    <el-button type="primary" class="create">创建</el-button>
                </div>
            </el-dialog>
        )，
mounted() {
        this.$refs.dialog.open();
    },

**Comment by Leopoldthecoder** [comment]
集中在 #970 中反馈。
