### ISSUE TITLE
Can the [Feature Request] checkbox-group V-model attribute support the Object array?

### ISSUE THREAD

**Issue by kangkang07** [ElemeFE/element#9890]
### Existing Component
是

### Component Name
checkbox-group

### Description
checkbox-group 的 v-model 只是把选中项绑定的 label 放到了数组里面，这也许是因为 checkbox组件本身只绑定了label，而且限制了绑定的类型为 string / number / boolean。
然而我们经常希望将一个对象绑定到checkbox，然后希望在checkbox-group 的 v-model 里获取对象的数组。

**Comment by kangkang07** [comment]
the auto translation is perfect ... 😄

**Comment by Leopoldthecoder** [comment]
暂无计划支持，可以先用 computed property 来实现：https://jsfiddle.net/ngo6ckz1/4/
