### ISSUE TITLE
[Feature Request] element-ui can not bind corresponding elements when upload components are used multiple

### ISSUE THREAD

**Issue by asd8855** [ElemeFE/element#9891]
### Existing Component
是

### Component Name
upload

### Description
element-ui中upload组件使用多个时无法绑定对应的元素.
http://www.qingpingshan.com/jb/javascript/296964.html.
该作者解决了此问题，但你们官方是否打算处理此问题？

**Comment by Leopoldthecoder** [comment]
不需要这样改，用一个高阶函数就可以了。

**Comment by asd8855** [comment]
@Leopoldthecoder 能否细说一下？ 从入坑前端

**Comment by Leopoldthecoder** [comment]
参考 https://github.com/ElemeFE/element/pull/9589

**Comment by asd8855** [comment]
@Leopoldthecoder  谢谢懂了
