### ISSUE TITLE
The tooltip of the [Feature Request] slider needs the incoming configuration

### ISSUE THREAD

**Issue by evolutionjay** [ElemeFE/element#9893]
### Existing Component
是

### Component Name
el-slider

### Description
el-slider 的 tooltip 只给出显示, 还有格式化. 但是默认样式甚至class 都不给配置. 希望给出 样式配置, 至少 能给出 custom className 啊. 要不然像我是把这个 silder 放在一个黑色的背景上, 然后 背景也是黑的, tooltip 也是黑的, 好无力.

**Comment by QingWei-Li** [comment]
直接覆盖样式就好了

**Comment by evolutionjay** [comment]
@QingWei-Li 有些地方要不同样式. 例如我的 layout 的 有个 侧栏, 是黑色的, 其它地方是白色的. 但是 silder 的 tooltip 是 append 到 body 的, 加全局样式明显不行
