### ISSUE TITLE
[Feature Request] wants el-table-column to open cell-class-name

### ISSUE THREAD

**Issue by viewweiwu** [ElemeFE/element#9896]
### Existing Component
是

### Component Name
el-table

### Description
文档上，el-table-column 已经有 ‘class-name’ 这个属性，但是它会把标题也加上这个样式，希望 el-table-column 开放不给标题加样式的 'cell-class-name'。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. Use `td` in your CSS selector to declare styles dedicate to body cells: https://jsfiddle.net/wm0La7jo/ .
