### ISSUE TITLE
[Feature Request] el-cascader data is dynamically acquired, so how to get full path data when filterable is enabled?

### ISSUE THREAD

**Issue by ZhuangJiangtao** [ElemeFE/element#9898]
### Existing Component
是

### Component Name
el-cascader

### Description
el-cascader 的数据是从后台读取过来的地区数据，级别为国省市区镇，由于数据量巨大因此采用动态加载。第一级数据是国家，在已经启用 filterable 且第一级国家数据已经加载出来的情况下输入“中华人民共和国”提示“无法匹配到数据”。另外，我直接输入镇这一级别的数据时，目前是无法匹配全路径的。比如我输入“工业园区”，应该匹配“江苏省/苏州市/工业园区”、“甘肃省/平凉市/工业园区”……

**Comment by QingWei-Li** [comment]
Hi,
1. 请不要滥用 Issue，这里只处理 Bug 和 Feature，提交前请参考 [Issue 规范](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md#issue-规范)，同时按照 Issue 模板填写内容。不符合规范的 Issue 将直接关闭；
2. 有问题请到 [Gitter](https://gitter.im/ElemeFE/element) 里问，提问前可以先阅读 [FAQ](https://github.com/ElemeFE/element/blob/dev/FAQ.md#常见问题)。
