### ISSUE TITLE
[Bug Report] date and time control, no change event will be triggered

### ISSUE THREAD

**Issue by huangzhili** [ElemeFE/element#9901]
### Element UI version
2.0.10

### OS/Browsers version
win7/chrome 版本 64.0.3282.167（正式版本） （64 位）

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/y3r9n2un/1/](https://jsfiddle.net/y3r9n2un/1/)

### Steps to reproduce
日期时间控件，如果手写输入日期，按_enter_键，这时日历面板上的日期是变化的，但再点击_确定_键，不会触发change事件。
（应该要触发change事件，因为如果在日历面板中点击选择日期后，再点击_确定_键，是会change事件。）
注意：这种情况发生在第二次操作， 第一次操作是没问题。
示意图：
https://user-images.githubusercontent.com/36843555/36707827-f6ab11e2-1baa-11e8-8e0c-c2e9b58b4689.jpg

### What is Expected?
如果手写输入日期，按_enter_键，点击_确定_键，触发change事件。

### What is actually happening?
手写输入日期，按_enter_键，点击_确定_键，不触发change事件。

**Comment by wacky6** [comment]
确认是bug，我晚上处理一下

**Comment by wacky6** [comment]
https://jsfiddle.net/s2ak6k43/
