### ISSUE TITLE
In IE9 , scroll bar question in dialog.  emergency！

### ISSUE THREAD

**Issue by wayneFly** [ElemeFE/element#9903]
Element UI version
2.2.0

OS/Browsers version
windows IE9

Vue version
2.3.0

Reproduction Link
[look this picture](http://oc4vh4dg7.bkt.clouddn.com/Video_2018-02-27_105106%2000_00_05-00_00_11.gif)

Steps to reproduce
This is a EL-DIALOG,there is a table and scroll bar in  the dialog.Please look at the picture。

What is Expected?
What Can I do？Help！
What is actually happening?

**Comment by wacky6** [comment]
element 2 requires IE 10 and Vue 2.5.2. We won't support earlier browsers.
