### ISSUE TITLE
 v-loading.body="loading" 如果设置在dialog,会盖了黑色的遮罩层，毕竟我只想盖住dialog部分

### ISSUE THREAD

**Issue by spademan** [ElemeFE/element#991]
### ElementUI version

1.0.0
### Vue version

2.0.3
### What is Expected?
#122 中说到覆盖了，如果是fullscreen,是没有什么疑虑的，但是如果是body的话 是不是覆盖了就不太好了，
demo : http://jsfiddle.net/spademan/0ghwo68f/

**Comment by Leopoldthecoder** [comment]
是个问题。

出现这个现象的原因是 Dialog 组件的根元素是一个全屏的 wrapper，而 Loading 的大小是根据绑定了 `v-loading` 这个指令的元素计算的。我们会尽快优化 Loading。

**Comment by Leopoldthecoder** [comment]
试试 1.0.1 版提供的 `this.$loading`，将 `target` 指定为你需要覆盖的元素是否可以解决这个问题。

**Comment by fritx** [comment]
```vue
// 只想loading盖住dialog部分
// ui-form-dialog.vue
  watch: {
    loading (v) {
      if (v) {
        let dialogPanel = this.$refs.dialog.$refs.dialog // dialog面板的dom节点
        this.loadingInstance = this.$loading({
          target: dialogPanel
        })
      } else if (this.loadingInstance) {
        this.loadingInstance.close()
      }
    },
  }
```
