### ISSUE TITLE
[Bug Report] Table: head and body dislocation when set the max-height property

### ISSUE THREAD

**Issue by SirM2z** [ElemeFE/element#9912]
### Element UI version
2.2.0

### OS/Browsers version
win10 chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/coolmrz/dn8x8azz/](https://jsfiddle.net/coolmrz/dn8x8azz/)

### Steps to reproduce
滑动表格的横向滚动条到最右端，会看到表头和表体错位。2.1.0有同样的问题，2.0.11没有问题

Slide the table horizontal scroll bar to the far right, you will see the head and body dislocation.Have the same problem in the 2.1.0 version, no problem in 2.0.11 version

### What is Expected?
不错位

no dislocation

### What is actually happening?
错位

dislocation

**Comment by Leopoldthecoder** [comment]
可否在拿到数据后再更新高度？https://jsfiddle.net/dn8x8azz/9/

**Comment by SirM2z** [comment]
谢谢，当然可以，如果框架层面不好优化的话

**Comment by elfman** [comment]
在最新的dev分支`2d12519`上测试，没有再出现这个问题，应该在某个提交里修复了

**Comment by Leopoldthecoder** [comment]
是的，已在 https://github.com/ElemeFE/element/pull/10034 修复。本周会发一个版本。
