### ISSUE TITLE
el-table选中行高亮的问题

### ISSUE THREAD

**Issue by pandichao** [ElemeFE/element#9914]
1.我目前使用的是npm下载的最新版本，集成在jsp页面中使用的，之前使用el-table做了一个可以展开的table，内部展开以后仍然是一个table的需求，但是遇到了bug，展开以后内部的table选中高亮以后会出现问题，比如第一个选中高亮设置成功，点击一下外部的table某一行，高亮设置在外部的table行上，内部的table需要取消行高亮，然后调用取消的方法以后再次点击取消的那一行，就触发无法选中高亮的bug，但是选其他行可以高亮，并且选中其他行再选之前选中的行也可以高亮，这是可展开的table开发时遇到的bug，希望饿了么团队能及时修复或者找到bug的原因，解决自定义的需求，代码如下（由于是模板，只是实现对应功能，不贴后台代码了）：

<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<!DOCTYPE HTML>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>

<html>
<head>
<base href="<%=basePath%>">
<title>vue_menu_mgt.jsp</title>
<script type="text/javascript" src="js/vue.min.js"></script>
<script type="text/javascript" src="js/element-ui/lib/index.js"></script>

<link rel="stylesheet" type="text/css" href="js/element-ui/lib/theme-chalk/index.css"/>

<script type="text/javascript" src="js/axios.min.js"></script>
<style type="text/css">
  //撑大table的宽度，把横向滚动条干掉
  .el-table__body-wrapper, .el-table__footer-wrapper, .el-table__header-wrapper{
	width: 100.5%;
   }
</style>
</head>

<body>
   <div id="app">
	
	      
	      <div style="padding:2px;background-color: #ECECED;">
	            
			  <el-button v-for='(item,index) in buttonOptions.buttons' :type='buttonOptions.type' round :size='buttonOptions.size' :icon='item.icon' @click='item.click'>{{item.name}}</el-button>
	      </div>
	      
	      <div style="width:100%;height:90%;background-color: #ECECED;">
	        <template>
	          
			  <el-table
			    v-loading="loading"
			    ref="bigTable"
			    :row-key='getRowKey'
			    :expand-row-keys='expandKeys'
			    :border='table.border'
			    :data="tableData"
			    :height="table.height"
			    :size='table.size'
			    highlight-current-row
	            style="width: 100%"
	            @row-click='rowclick'
	            @current-change="rowCurrentChange"
			    >
			    <el-table-column
			      type='expand'
			      width='50'
			      >
			      
			      <template slot-scope="props">
			         
			        <el-table style='width: 100%;margin-top:-17px;margin-bottom:-17px;'
			        border
			        ref="chTable"
			        :show-header=false
			        :data="props.row.children"
		            @row-click='rowclick'
		            @current-change="rowCurrentChange"
		            highlight-current-row
		            :row-style='rowClass'
			        :size='table.size'>
			        <el-table-column v-for='(column,index) in table.columns' :label="column['label']" :prop="column['prop']" :width="column['width']" :formatter="column['formatter']?menuFormatter:false"></el-table-column>
					<el-table-column label='操作' width='70'>
						 <template slot-scope="scope">
							
						    <el-button  type="info" :size="table.size" @click="handleEdit(scope.$index, scope.row)">迁移</el-button>
						 </template>
					</el-table-column>
			      </el-table>
			    </template>
			  </el-table-column>
			    
			    <el-table-column v-for='(column,index) in table.columns' :label="column['label']" :prop="column['prop']" :width="column['width']" :formatter="column['formatter']?menuFormatter:false"></el-table-column>
			    <el-table-column label="移动" width='130'></el-table-column>
			  </el-table>
			</template>
	      </div>
	       
	       <el-dialog :title="menuAddAndEdit.type=='add'?'新增菜单':'编辑菜单'" :visible.sync="dialogVisible" :show-close=false center>
			   		 <el-form :model="menuRow" size='mini' :rules='rules' ref="ruleForm" status-icon>
					    <el-row>
						  <el-col :span="12">
						      <el-form-item label='编码:' label-width="120px" prop="menu_code" >
							    <el-input v-model="menuRow.menu.menu_code" ></el-input>
						      </el-form-item>
						  </el-col>
						  <el-col :span="12">
						  	  <el-form-item label='父级节点:' label-width="120px">
							     {{menuRow.pname?menuRow.pname:'无'}}
						      </el-form-item>
						  </el-col>
						</el-row>
						
						<el-row>
						  <el-col :span="12">
						      <el-form-item label='名称:' label-width="120px" prop='menu_name'>
							    <el-input v-model="menuRow.menu.menu_name" ></el-input>
						      </el-form-item>
						  </el-col>
						  <el-col :span="12">
						  	  <el-form-item label='图标类型:' label-width="120px" prop='menu_icon'>
							     <el-input v-model="menuRow.menu.menu_icon" v-if='menuAddAndEdit.type=="edit"'></el-input>
							     <el-input v-model="menuRow.menu.menu_icon" v-else-if='menuRow.menu.menu_property=="P" && menuAddAndEdit.type=="add"'></el-input>
							     <span v-else>{{menuRow.menu.menu_icon}}</span>
						      </el-form-item>
						  </el-col>
						</el-row>
						
						<el-row>
						  <el-col :span="12">
						      <el-form-item label='地址:' label-width="120px" prop='menu_url'>
							    <el-input v-model="menuRow.menu.menu_url" ></el-input>
						      </el-form-item>
						  </el-col>
						  <el-col :span="12">
						  	  <el-form-item label='菜单类型:' label-width="120px">
							     {{menuRow.menu.menu_property=='C'?'页面':'节点'}}
						      </el-form-item>
						  </el-col>
						</el-row>
  				</el-form> 
  				<div slot="footer" class="dialog-footer">
				    <el-button size='mini' @click="dialogVisible = false">取 消</el-button>
				    <el-button size='mini' type="primary" @click="menuAddAndEdit.type=='add'?addEditMenu('ruleForm','add'):addEditMenu('ruleForm','edit')">确 定</el-button>
			  </div>
		   </el-dialog>
	       
	       <el-dialog title="节点迁移" :visible.sync="moveDialogVisible" :show-close=false center>
			   		 <el-form :model="menuMoveRow" size='mini' ref="moveForm" status-icon :rules = 'moveRules'>
						      <el-form-item label='所选节点属于：' label-width="160px">
						         {{menuMoveRow.pname}}
						      </el-form-item>
						  	  <el-form-item label='迁移至：' label-width="120px">
								    <el-select v-model="menuMoveRow.value" placeholder="请选择活动区域" prop='select'>
								      <el-option
								      v-for="item in menuMoveRow.array"
								      :key="item.treeNodeSid"
								      :label="item.nodeName"
								      :value="item.treeNodeSid">
								    </el-select>
						      </el-form-item>
  					 </el-form> 
  				<div slot="footer" class="dialog-footer">
				    <el-button size='mini' @click="moveDialogVisible = false">关闭</el-button>
				    <el-button size='mini' type="primary" @click="moveMenu('moveForm')">保存</el-button>
			  </div>
		   </el-dialog>
	  
   </div>
</body>
<script type="text/javascript">
/**
   * 自己定义的ajax事件，模拟原来jquery传值的方式
   **/
   function ajax(options){
      if(typeof options != 'object'){
              options = JSON.parse(options);
            }
            var params = new URLSearchParams();
            if(options.data){
              //循环存放进去
              for(var item in options.data){
                params.append(item,options.data[item]);
              }
              //全部转换成json对象传过去，这样java后台可以不加注解获取到
            }
            //根据类型调用对应的方法，
            if(options.method == 'post' || options.method == 'POST'){
                //开始加载
	            axios.post(options.url,params)
	            .then(function(data){
	              options.success(data.data);
	            })
	            .catch(function(err){
	               options.error(err);
	               });
            }else if(options.method == 'get' || options.method == 'GET'){
	            axios.get(options.url,params)
	            .then(function(data){
	              options.success(data.data);
	            })
	            .catch(function(err){
	               options.error(err);
	               });
            }
   }
   
   /**
   * 外部定义的ajax查询table数据的方法
   **/
   function getTableAjax(_this,other){
     //创建的时候获取一下对应的菜单的信息
     _this.loading = true;
         ajax({
           url:'sysPrivilege/findmenu.htmls',
           method : 'POST',
           success : function(data){
             _this.tableData = data;
             _this.oldTableData = data;
             var size = _this.tableData.length;
	         for(var i = 0;i < size ; i ++){
	             //在这里判断当前状态是展开还是关闭的，如果默认是展开的，那么久存入key到数组中
	             if(_this.tableData[i]['state'] == 'open'){
	               _this.expandKeys.push(_this.tableData[i].menu_code);
	             }
	         }
	         //如果不为空，执行一下选中行操作
	         if(other != undefined){
	            other();
	         }
	         //关闭loading
	         _this.loading = false;
           },
           error : function(err){
             _this.loading = false;
             alert('err:'+JSON.stringify(err));
           }
         });
   }

   var vm = new Vue({
      el : '#app',
      data(){
       var menu_code = (rule,value,callback)=>{
         if(!vm.menuRow.menu.menu_code){
           return callback(new Error('菜单编码不能为空'));
         }else{
           return callback();
         }
       };
       var menu_name = (rule,value,callback)=>{
          if(!vm.menuRow.menu.menu_name){
           return callback(new Error('菜单名称不能为空'));
          }else{
           return callback();
          }
       };
       var menu_icon = (rule,value,callback)=>{
          if(!vm.menuRow.menu.menu_icon){
           return callback(new Error('图标不能为空'));
          }else{
           return callback();
          }
       }; 
       var menu_url = (rule,value,callback)=>{
         if(!vm.menuRow.menu.menu_url){
           return callback(new Error('菜单地址不可以为空'));
         }else{
          return callback();
         }
       };
       var select = (rule,value,callback)=>{
         if(!vm.menuMoveRow.value){
           return callback(new Error('迁移地址不可以为空'));
         }else{
           return callback();
         }
       };
       
       return{
         loading : false,//初始化的table加载时是否需要加载中ui
         oldTableData : [],//用来记录当前table的data
         tableData : [],
         expandKeys : [],//默认展开的arrays数组项
         menuAddAndEdit : {//用来保存menu菜单信息用于新增或者编辑的变量
           type : 'add'//这里依赖type给dialog判断的标准，是新增还是编辑，包括标题如何变动都是按照这个
         },
         //菜单迁移的时候绑定的对象
         menuMoveRow : {
           pname : '',
           array : [],
           value : '',
           oldData : null  
         },
         menuRow : {
           menu:{},
           pname : '',
           oldCode : ''//当编辑菜单的时候，记录一下之前的旧的菜单的值，用来比较是否进行了修改
         },//新增菜单或者编辑菜单的时候表单绑定的json对象
         dialogVisible : false,//新增菜单或者编辑菜单的时候dialog是否显示控制
         moveDialogVisible : false,//初始化迁移菜单的dialog是否显示 
         table : {     //初始化配置的table信息
           size : 'mini',
           border : true,
           height : 470,
           columns : [   
             /* {type : 'expand',width : '50'}, */
             {label : '编码',prop : 'menu_code',width : '140'},
             {label : '菜单名称',width : '140',prop : 'menu_name'},
             {label : '上级菜单',width : '130',prop : 'pname'},
             {label : '图标' ,width : '260' ,prop : 'iconCls'},
             {label : '地址',width : '250' ,prop : 'menu_url'},
             {label : '菜单类型',prop : 'menu_property',width : '90',formatter : true}
           ]
         },
         buttonOptions : {    //初始化配置的button配置
           type : 'primary',
           size : 'mini',
           buttons : [
             {icon : 'el-icon-caret-right',
              name : '展开',
              click : function(){
                 vm.$options.methods.openAll(vm);
               }
             },
             {
               icon : 'el-icon-caret-left',
               name : '折叠',
               click : function(){
                 vm.$options.methods.closeAll(vm);
               }
             },
             {icon : 'el-icon-refresh',
              name : '刷新',
              click : function(){
                 vm.$options.methods.refresAll(vm);
               }
             },
             {
               icon : 'el-icon-zoom-in',
               name : '增加',
               click : function(){
                 vm.$options.methods.addMenu(vm);
               }
             },{
               icon : 'el-icon-remove-outline',
               name : '删除',
               click : function(){
                 vm.$options.methods.delMenu(vm);
               }
             },
             {
              icon : 'el-icon-edit',
              name : '编辑',
              click : function(){
                vm.$options.methods.editMenu(vm);
              } 
             },
             {
              icon : 'el-icon-back',
              name : '取消选中',
              click : function(){
                 vm.$options.methods.cancelSelet(vm);  
              }
             }
           ]
         },
         //form表单验证
         rules : {
           menu_code : [
             /* {required: true, message: '请输入菜单编码', trigger: 'blur'}, */
             {validator: menu_code,trigger : 'blur'}
           ],
           menu_name : [
             {validator: menu_name, trigger: 'blur'}
           ],
           menu_icon : [
             {validator: menu_icon, trigger: 'blur'}
           ],
           menu_url : [
             {validator: menu_url, trigger: 'blur'}
           ]
         },
         //迁移的表单验证
         moveRules : {
           select : [
              {validator: select, trigger: 'blur'}
             ]
         },
         opens : [],
         fristTrees : [],
         treeLoadCount : -1,
         multipleSelection : null, 
         openall : false,
         getRowKey(row) {    //计算每一行的key的方法，手动设置
             return row.menu_code;
           }
       }
      },
      created : function(){
         var _this =  this;
         getTableAjax(_this);
      } ,
      methods : {
        click : function(){
           alert('点击事件触发');
        },
        handleEdit : function(index,row){  //点击迁移按钮触发的点击事件
           var _this = this;
          //获取一下对应的下拉展示的数据
          //弹出dialog
          _this.moveDialogVisible = true;
          _this.menuMoveRow.pname = row.pname;
          _this.menuMoveRow.oldData = row;
          ajax({
            url : 'sysPrivilege/treeTypeList.htmls',
            method : 'GET',
            success : function(data){
              _this.menuMoveRow.array = data;
            }, 
            error : function(err){
              alert('遇到异常了:'+err);
            }
          });
        },
        handleSelectionChange : function(val){
             this.multipleSelection = val;
        },
        //行样式
        rowClass: function (row, index) {
          var _this = this;
          if(_this.multipleSelection == row){
            return { "background-color": "red" };
          }
	    },
        //这里存在一个bug，连续快速来回点击两个菜单切换的时候会失去焦点，导致undefined异常报错，但是目前测试只有父table和子table来回切换会这样(原因可能是currentRow数据丢失，为undefinded)
        //bug的原因估测：应该是elmentui源码中用了一个变量接受当前已经选中的行，当这个行是刚刚选中的那一行的时候，再次选中不会触发行改变事件，所以就不会再次高亮，应该是没有考虑到table嵌套table的问题
        rowCurrentChange : function(currentRow,oldCurrentRow){  //父界面table选中行改变发生的变化(只要选中了就会触发)
           var _this = this;
           /* _this.multipleSelection = currentRow; */
           /* alert(currentRow.menu_property);
           if(currentRow.menu_property == 'P'){
             //当前是父table
             _this.$refs.bigTable.setCurrentRow(currentRow);
             //_this.$refs.chTable.setCurrentRow();
           }else if(currentRow.menu_property == 'C'){
             _this.$refs.chTable.setCurrentRow(currentRow);
             //_this.$refs.bigTable.setCurrentRow();
           }
           _this.multipleSelection = currentRow;  */
        },
        openAll : function(_this){   //点击按钮展开全部
           var size = _this.tableData.length;
           _this.expandKeys = [];
           for(var i = 0 ; i < size;i ++){
             _this.expandKeys.push(_this.tableData[i].menu_code);
           }
        },
        closeAll : function(_this){ //点击全部折叠
         _this.expandKeys = [];
        },
        refresAll : function(_this){ //点击刷新按钮
          //重新进行ajax联网获取最新table数据的操作
          getTableAjax(_this);
        },
        addMenu : function(_this){  //新增菜单操作
           if(_this.multipleSelection){
             _this.menuAddAndEdit.type = 'add'; 
             _this.menuRow = {
		           menu:{},
		           pname : '',
		           oldCode : ''
		       };
             if(_this.multipleSelection.menu_property=="C"){
               _this.$notify({
		          title: '提示',
		          message: '子菜单下面不可以在创建子菜单哦',
		          position: 'bottom-right',
		          type : 'warning',
		          duration: 1500
		        });
             }else if(_this.multipleSelection.menu_property=="P"){
                //创建一个新的menu对象绑定进去
                var newMenu = {
                  menu_code : '',
                  menu_name : '',
                  menu_pid : _this.multipleSelection.pk_tree_node,
                  menu_url : '',
                  menu_icon : 'icon-page',
                  pk_tree_node : _this.multipleSelection.pk_tree_node,
                  menu_property : 'C'
                };
                //设置为新增菜单的对象
                _this.menuRow.menu = newMenu;
                _this.menuRow.pname = _this.multipleSelection.menu_name;
                //开启dialog
                _this.dialogVisible = true;
             }
           }else{
             //说明当前是空的(新增主菜单)
                //创建一个新的menu对象绑定进去
                var newMenu = {
                  menu_code : '',
                  menu_name : '',
                  menu_pid : '',
                  menu_url : '',
                  menu_icon : '',
                  pk_tree_node : '',
                  menu_property : 'P'
                };
                //设置为新增菜单的对象
                _this.menuRow.menu = newMenu;
                //开启dialog
                _this.dialogVisible = true;
           }
        },
        //编辑菜单
        editMenu : function(_this){
          //首先获取以下当前选中的行
          if(_this.multipleSelection){
               //首先置空原来的menuRow
               _this.menuRow = {
		           menu:{},
		           pname : '',
		           oldCode : ''
		        };
		        //创建一个新的menu子对象用来展示editmenu的内容
		        var newMenu = {
                  menu_code : _this.multipleSelection.menu_code,
                  menu_name : _this.multipleSelection.menu_name,
                  menu_pid : '',
                  menu_url : _this.multipleSelection.menu_url,
                  menu_icon : _this.multipleSelection.iconCls,
                  pk_tree_node : _this.multipleSelection.pk_tree_node,
                  menu_property : _this.multipleSelection.menu_property
                };
                //设置为新增菜单的对象
                _this.menuRow.menu = newMenu;
                _this.menuRow.pname = _this.multipleSelection.pname;
                _this.menuAddAndEdit.type = 'edit'; 
                _this.menuRow.oldCode = _this.multipleSelection.menu_code;
                //开启dialog
                _this.dialogVisible = true;
          }else{
            _this.$notify({
		          title: '提示',
		          message: '请先选中菜单以后在进行编辑操作哦',
		          position: 'bottom-right',
		          type : 'warning',
		          duration: 1500
		        });
          }
        },
        //取消选中按钮的点击事件
        cancelSelet : function(_this){
          //根据这个绑定的对应的数据判断当前是哪个table选中了行，取消选中
          /* if(_this.multipleSelection.menu_property == 'P'){
             //当前是父table
             _this.$refs.bigTable.setCurrentRow();
           }else if(_this.multipleSelection.menu_property == 'C'){
             _this.$refs.chTable.setCurrentRow();
           } */
           //_this.multipleSelection = null;
           getTableAjax(_this);
           _this.multipleSelection = null;
        },
        //新增（编辑菜单的页面）点击确定按钮触发的点击事件
        addEditMenu : function(formName,type){
           var _this = this;
           _this.$refs[formName].validate((validate)=>{
             if(validate){
                //这里判断一下当前菜单是新增还是edit
                if(type == 'add'){
                  //验证通过了，开始提交菜单
	                ajax({
	                  url : 'sysPrivilege/savemenu.htmls',
	                  method : 'POST',
	                  data : {
		                  menu_code : _this.menuRow.menu.menu_code,
		                  menu_name : _this.menuRow.menu.menu_name,
		                  menu_pid :  _this.menuRow.menu.menu_pid,
		                  menu_url : _this.menuRow.menu.menu_url,
		                  menu_icon : _this.menuRow.menu.menu_icon,
		                  pk_tree_node : _this.menuRow.menu.pk_tree_node,
		                  menu_property : _this.menuRow.menu.menu_property
	                  },
	                  success : function(data){
	                      //data = JSON.parse(data);
					      if(data.mark=="success"){ 
				             //重新加载菜单数据
				               getTableAjax(_this);
				               //关闭当前dialog
				       		   _this.dialogVisible = false;
				          }
				          _this.$notify({
				          title: '提示',
				          message: data.msg,
				          position: 'bottom-right',
				          type : 'warning',
				          duration: 1500
				        });
				      },
	                  error : function(err){
	                    _this.$message({
				            type: 'error',
				            message: '遇到了异常：'+err
				          });
                           _this.dialogVisible = false;
	                  }
	                });
                }else if(type == 'edit'){
                   var url;
                   if(_this.menuRow.menu.menu_property == 'C'){
                     //那么验证子菜单是否编码重复
                     url = 'sysPrivilege/checkPrivilegeCode.htmls';
                   }else if(_this.menuRow.menu.menu_property == 'P'){
                     //验证主菜单是否编码重复的url
                     url = 'sysPrivilege/checkNodeCode.htmls';
                   }
                   var updateUrl = 'sysPrivilege/updatemenu.htmls';
                   var upateData = {
                      	  menu_code : _this.menuRow.menu.menu_code,
		                  menu_name : _this.menuRow.menu.menu_name,
		                  menu_pid :  _this.menuRow.menu.menu_pid,
		                  menu_url : _this.menuRow.menu.menu_url,
		                  menu_icon : _this.menuRow.menu.menu_icon,
		                  pk_tree_node : _this.menuRow.menu.pk_tree_node,
		                  menu_property : _this.menuRow.menu.menu_property
                   };
                   //先进行一次菜单重复验证，如果有做过修改就进行重复验证
                   if(_this.menuRow.oldCode != _this.menuRow.menu.menu_code){
	                     ajax({
	                     url : url,
	                     method : 'POST',
	                     data : {
	                       code : _this.menuRow.menu.menu_code
	                     },
	                     success : function(data){
	                        if(data){
	                          //有值就说明当前是false不可以进行提交的
	                           _this.$notify({
						          title: '提示',
						          message: '菜单编码已经存在，请重新输入',
						          position: 'bottom-right',
						          type : 'warning',
						          duration: 1500
						        });
	                        }
	                        return;
	                     },
	                     error : function(err){
	                       _this.$message({
				            type: 'error',
				            message: '遇到了异常：'+err
				          });
	                     }
	                   });
                   }
                   //说明当前验证没问题，可以进行修改提交
                       ajax({
                         url : updateUrl,
                         method : 'POST',
                         data : upateData,
                         success : function(data){
                           //刷新一下当前菜单页面
                         if(data.mark=="success"){ 
			             //重新加载菜单数据
			               getTableAjax(_this);
			               //关闭当前dialog
				          _this.dialogVisible = false;
				          }
				          _this.$notify({
				          title: '提示',
				          message: data.msg,
				          position: 'bottom-right',
				          type : 'warning',
				          duration: 1500
				        });
                         },
                         error : function(err){
                           _this.$message({
				            type: 'error',
				            message: '遇到了异常：'+err
				          });
                           _this.dialogVisible = false;
                         }
                       });
                }
             }else{
               return false;
             }
           });
        },
        //删除菜单
        delMenu : function(_this){
          if(_this.multipleSelection){
               var msg = "";
		       if(_this.multipleSelection.menu_property == 'P'){
		          msg = "您确认想要删除该记录以及所有子菜单？请谨慎选择！";
		       }else{
		          msg = "您确认想要删除该菜单？";
		       }
		       _this.$confirm(msg, '提示', {
		          confirmButtonText: '确定',
		          cancelButtonText: '取消',
		          type: 'warning'
		        })
		        .then(function(){
		           ajax({
		             url : 'sysPrivilege/daletemenu.htmls',
		             data : {
		             		'pk_tree_node':_this.multipleSelection.pk_tree_node,
							'menu':_this.multipleSelection.menu_property
		             },
		             method : 'POST',
		             success : function(data){
		               if(data.mark=="success"){
		                 getTableAjax(_this);
		               }
		               //显示弹窗
		                _this.$notify({
				          title: '提示',
				          message: data.msg,
				          position: 'bottom-right',
				          type : 'warning',
				          duration: 1500
				       });
		             },
		             error : function(err){
		               _this.$message({
			            type: 'error',
			            message: '遇到了异常：'+err
			          });
		             }
		           });
		        })
		        .catch(()=>{
		          _this.$message({
		            type: 'info',
		            message: '已取消删除'
		          });   
		        });
          }else{
             _this.$notify({
		          title: '提示',
		          message: '请选中对应的菜单进行删除操作',
		          position: 'bottom-right',
		          type : 'warning',
		          duration: 1500
		       });
          }
        },
        //迁移菜单的操作
        moveMenu : function(formName){
           var _this = this;
           _this.$refs[formName].validate((validate)=>{
             if(validate){
              //验证通过，开始进行ajax请求
              //弹一个confirm出来
               this.$confirm('您要迁移当前所选节点吗？', '确认操作', {
		          confirmButtonText: '确定',
		          cancelButtonText: '取消',
		          type: 'warning'
		        }).then(() => {
		          ajax({
		             url : 'sysPrivilege/menuMove.htmls',
		             method : 'POST',
		             data : {
		                privilegeSid : _this.menuMoveRow.oldData.pk_privilege, //当前菜单的sid
                        treeNodeSid : _this.menuMoveRow.value   //下拉选中的菜单sid
		             },
		             success : function(data){
		                if (data.mark == 'success') {
		                  //刷新数据
		                  getTableAjax(_this);
		                  _this.moveDialogVisible = false;
		                }
		                //弹出结果
		                 _this.$notify({
				          title: '提示',
				          message: data.msg,
				          position: 'bottom-right',
				          type : 'warning',
				          duration: 1500
				       });
		             },
		             error : function(err){
		               _this.$message({
			            type: 'info',
			            message: '遇到了异常：'+err
			          });
			          _this.moveDialogVisible = false;
		             }
		           });
		        }).catch(() => {
		        });
             }else{
               return false;
             }
           });
        },
        menuFormatter : function(row, column, cellValue){
          if(cellValue.toUpperCase() == 'P'){
             return '父菜单';
          }else if(cellValue.toUpperCase() == 'C'){
             return '子菜单';
          }else{
             return cellValue;
          }
        },
        //行点击事件
        rowclick : function(row,event,column){
          var _this = this;
          vm.$refs.bigTable.setCurrentRow();
          vm.$refs.chTable.setCurrentRow();
          _this.multipleSelection = row;
          if(_this.multipleSelection){
           if(_this.multipleSelection.menu_property == 'C'){
              //选中的是子菜单
              vm.$refs.chTable.setCurrentRow(row);
           }else{
              vm.$refs.bigTable.setCurrentRow(row);
           }
          }
          
          //先清理掉当前的table的数据，再重新赋值
          //触发table重新布局刷新
          /* _this.tableData = [];
          for(var i = 0;i < _this.oldTableData.length;i++){
             _this.tableData.push(_this.oldTableData[i]);
          }
           _this.multipleSelection = row;
          //再去判断当前点击的行，触发选中事件
          if(_this.multipleSelection){
           if(_this.multipleSelection.menu_property == 'C'){
              //选中的是子菜单
              vm.$refs.chTable.setCurrentRow(row);
           }else{
              vm.$refs.bigTable.setCurrentRow(row);
           }
          } */
          
          /* vm.$refs.bigTable.doLayout();
          vm.$refs.chTable.doLayout(); */
          /* if(_this.multipleSelection){
            if(_this.multipleSelection.menu_property == 'C'){
              alert('选中了子菜单');
              //说明之前选中的是父菜单，取消掉子菜单的点击事件
               vm.$refs.bigTable.setCurrentRow();
               //vm.$refs.chTable.setCurrentRow(row);
            }else{
              //说明之前选中的是父菜单，取消掉父菜单的点击事件
              vm.$refs.chTable.setCurrentRow();
              //vm.$refs.bigTable.setCurrentRow(row);
            }
          } */
        }
      }
   });
</script>
</html>

**Comment by 569202812** [comment]
在jsp写可以

**Comment by JackSengKing** [comment]
我们也遇到了这个问题，最终发现，是因为我们操作列加了fixed="right"的原因
![image](https://github.com/user-attachments/assets/a7186a72-ff52-4d6b-81a5-8695d079d14e)
去掉这个属性之后就好了
