### ISSUE TITLE
[Feature Request] Parent node highlight for tree component.

### ISSUE THREAD

**Issue by gkumar9** [ElemeFE/element#9915]
### Existing Component
Yes

### Component Name
Tree

### Description
Would it possible to have an attribute in tree component to highlight the parent node of the TREE.
Like (highlight-current) but just the parent node, not children even if you click children node it highlights parent.
Thank you and help would be appreciated.

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
