### ISSUE TITLE
[Bug Report] table content width display wrong in ie11

### ISSUE THREAD

**Issue by xyhxyw** [ElemeFE/element#9916]
### Element UI version
2.2.0

### OS/Browsers version
IE11

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/xyhxyw/kp3ffLtw/](https://jsfiddle.net/xyhxyw/kp3ffLtw/)

### Steps to reproduce
1 open the jsfinddle in ie11,nothing is showed,table can't render right. (it's just a copy of step2)
2 or open 'http://element-cn.eleme.io/2.2/#/zh-CN/component/table' in IE11，you'll found that talble content width is not right.

### What is Expected?
table content width render right（table内容应该是100%宽度）

### What is actually happening?
table content width render wrong（table内容宽度计算错误，在IE11中直接打开step2中的官网页面即可发现问题）

**Comment by fairyier** [comment]
element-ui 1.4.x 的时候，tabel中不设置宽度的<el-table-column>默认会占用表格的剩余宽度，现在新版本2.2.1在IE中不会自动占用表格剩余宽度，如官网例子：http://element-cn.eleme.io/2.2/#/zh-CN/component/table  在IE浏览器，未给宽度的“地址”列，很窄，使表格后面留空了

**Comment by rkdqudtjs1** [comment]
Bind the data in mounted()

**Comment by xyhxyw** [comment]
@Leopoldthecoder ，is  there a plan to fix the bug?

**Comment by emorlasar** [comment]
table.vue 里的this.doLayout()放$nextTick里执行就可以
```
mounted() {
  //this.doLayout();
  this.$nextTick(() => {
      this.doLayout();
  });
}
```

**Comment by xcchcaptain** [comment]
这个问题一直未修复啊

**Comment by Eviwang** [comment]
> table.vue 里的this.doLayout()放$nextTick里执行就可以
> 
> ```
> mounted() {
>   //this.doLayout();
>   this.$nextTick(() => {
>       this.doLayout();
>   });
> }
> ```

## bug 原因
IE 11浏览器满足下面两个条件时获取clientWidth为0.
1. 元素设置 `overflow: hidden`
2. 元素内没有文字内容

在 Chrome,Firfox 能获取到值。

## 解决方案
方案一、 子元素table内容渲染完毕后，再次做doLayout计算。element 社区解决方案 https://github.com/ElemeFE/element/issues/9916#issuecomment-384927440
此方案在渲染完毕后，再次doLayout会导致dom重绘，用户会有闪烁

方案二、 使用getBoundingClientRect().with 设置表格宽度
此方案第一时间获取到表格宽度，使用没有闪烁
