### ISSUE TITLE
The [Feature Request] Cascader component adds the menuVisible property and more flexibly unfolds / remembers the drop-down menu

### ISSUE THREAD

**Issue by QiDekang** [ElemeFE/element#9918]
### Existing Component
Yes

### Component Name
Cascader

### Description
为了UI风格一致，没有使用Cascader自带的选择输入框，需要通过点击自己写的选择输入框展开/收起Cascader下拉菜单。
如果能为Cascader组件增加menuVisible属性，会方便很多。
目前通过document.getElementById('').click()直接模拟点击事件，却只能展开不能收起下拉菜单。

**Comment by QingWei-Li** [comment]
https://jsfiddle.net/4Lraoscn/7/
