### ISSUE TITLE
[Feature Request] Add input-class attribute to date pickers

### ISSUE THREAD

**Issue by Stetzon** [ElemeFE/element#9919]
### Existing Component
Yes

### Component Name
DatePicker

### Description
Having the ability to add a class to the input element generated by the DatePicker and related components would be nice.  This could be added as an [attribute](http://element.eleme.io/#/en-US/component/date-picker#attributes) like we have for the `popper-class`. For example, being able to add Bootstrap's `form-control` class:

```
<datepicker name="date"
    input-class="form-control"
></datepicker>
```

generates: 
`<input  name="date" type="text" class="el-input__inner form-control">`

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this. But you can contribute if you're interested.
