### ISSUE TITLE
[Feature Request] tabindex -1 for Popover

### ISSUE THREAD

**Issue by gdi2290** [ElemeFE/element#9920]
### Existing Component
Yes

### Component Name
Popover

### Description
Hi, we need to be able to set tabindex to -1 for popover. Can you add this as a prop since it's added at created lifecycle

In our dashboard we have dynamic forms which means we are using Popover to describe each field. The only problem with this is that you're forced to focus in on the popovers when the user expects Tab to go to the next field
 
<img width="1014" alt="screen shot 2018-02-27 at 10 08 41 am" src="https://user-images.githubusercontent.com/1016365/36746054-3a476a0e-1ba6-11e8-805b-f03e18885ef9.png">

**Comment by K-Wen** [comment]
Also need to set tabindex to -1 for dropdown
