### ISSUE TITLE
[Bug Report] Nested other components in steps

### ISSUE THREAD

**Issue by gim-m** [ElemeFE/element#9922]
### Element UI version
2.2.0

### OS/Browsers version
Mac OSX / Chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/346/](https://jsfiddle.net/mmx38qxw/346/)

### Steps to reproduce
Here I was trying to create popovers (or tooltips) for each el-step. Since el-step needs to be an immediate child of el-steps, I couldn't use the default content slot and instead had to use the popover directive.

### What is Expected?
I would expect the popover to show for each el-step.

### What is actually happening?
There appears to be a bug where you cannot create the popovers with v-for as the binding code is attempting to access the vue component directly via:

`vnode.context.$refs[_ref].$refs.reference = el;` (note, the second `$refs`)

When a component is create by v-for, the $refs (the first one) end up being an Array of VueComponents. We should support the array format for refs here as well.

**Comment by QingWei-Li** [comment]
Please use slots.

```html
<el-popover
  placement="right"
  title="Title"
  width="200"
  trigger="focus"
  content="this is content, this is content, this is content">
  <el-button slot="reference">Focus to activate</el-button>
</el-popover>
```

**Comment by gim-m** [comment]
Yes, I would like to use slots, but in this instance the `el-steps` must wrap the `el-step`, so slots don't work. I tried to illustrate this in the jsfiddle. If you have other suggestions I'd love to hear them. Thanks!

**Comment by QingWei-Li** [comment]
Yes, you are right.
I have a workaround. But popover is only displayed when hover the title Is this what you need? 

https://jsfiddle.net/mmx38qxw/377/

**Comment by gim-m** [comment]
Hi QingWei, yes that's really close :) . Thank you for the example!

Ideally, I need the hover/click to work for the whole step rather than just the title. For instance, if the step has a description as well, I would like the popover to be trigger on any element in the <el-step>. Would that be possible?
