### ISSUE TITLE
[Feature Request] progress bar: a progress bar distinguishes different progress by different colors.

### ISSUE THREAD

**Issue by zhangzhongjiang** [ElemeFE/element#9927]
### Existing Component
是

### Component Name
Progress

### Description
目前进度条是单个进度条显示一个项目的进度，但是有时候项目中需要单个进度条显示几个不同项目的进度，通过颜色来区分。我在开发中是通过css定位来实现项目需求。希望element-ui可以提供这个功能，方面大家更快的进行开发。

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.
