### ISSUE TITLE
[Bug Report] Table components: When all checkbox is disable, table-header's checkbox can still click

### ISSUE THREAD

**Issue by lvsuming** [ElemeFE/element#9929]
### Element UI version
2.2.0

### OS/Browsers version
chrome 62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/samuel666/mmx38qxw/361/](https://jsfiddle.net/samuel666/mmx38qxw/361/)

### Steps to reproduce
Create a table.
Bind a attribute that name is 'selectable' and value is 'selectableFun'.
The function that name is selectableFun is 'return false';

### What is Expected?
table-header's checkbox cann't click

### What is actually happening?
table-header's checkbox can still click

**Comment by Leopoldthecoder** [comment]
This is a tradeoff against having to call selectable functions multiple times, which can be a performance issue.

Since the current behavior doesn't break anything, and clicking the header's checkbox doesn't trigger `selection-change`, we may keep it as is.
