### ISSUE TITLE
关于table组件增加行列合并和表头分组的建议

### ISSUE THREAD

**Issue by zhangliang2008v** [ElemeFE/element#993]
### ElementUI version
1.0.0

现在table组件只实现了一些基本的功能，不知道有没有行列合并和表头分组的计划

**Comment by furybean** [comment]
『行列合并和表头分组』目前优先级不高，并不在 1.1 的计划里面；1.1 目前只打算新增展开行的 Feature。

**Comment by furybean** [comment]
这个 issue 和  #670 #1012 重复，先关了，请关注另外两个主题。
