### ISSUE TITLE
[Bug Report] table show-overflow-tooltip attribute prompts beyond display screen width

### ISSUE THREAD

**Issue by DrifterD** [ElemeFE/element#9931]
### Element UI version
2.0.8

### OS/Browsers version
window/chrome 64.0.3282.167

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/367/](https://jsfiddle.net/mmx38qxw/367/)

### Steps to reproduce
鼠标移至指定列，展示tooltip

### What is Expected?
完整展示tooltip信息

### What is actually happening?
tooltip展示过长，查过屏幕显示

**Comment by Leopoldthecoder** [comment]
![image](https://user-images.githubusercontent.com/10095631/36834865-336f550a-1d6f-11e8-909a-6912fd825ec7.png)

并未超出屏幕。
