### ISSUE TITLE
steps如何居中显示？

### ISSUE THREAD

**Issue by fancyboynet** [ElemeFE/element#994]

**Comment by furybean** [comment]
不知道你说的是不是这个意思：http://jsfiddle.net/crq56xtg/

**Comment by fancyboynet** [comment]
@furybean 这个没有完全居中，步骤3的右侧从视觉上看是没有连接横线的，占的宽度却和其他是一样宽的，而且还必须设置space，text-align:center才生效

**Comment by furybean** [comment]
@fancyboynet 可以使用 margin-right 负值的方式解决，不过并不精确：http://jsfiddle.net/crq56xtg/1/

**Comment by QingWei-Li** [comment]
目前给的设计就是这样的只能左对齐，其实有写居中对齐的，我可以加个开关开启居中对齐的样式

**Comment by Leopoldthecoder** [comment]
Added in #1023
