### ISSUE TITLE
The select component in the [Bug Report] form directly modifies the value value of the select component binding, does not trigger change events, and other common input boxes and date selection boxes are normal.

### ISSUE THREAD

**Issue by wlinshicong** [ElemeFE/element#9941]
### Element UI version
2.2.0

### OS/Browsers version
win7/ie11

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
1.首先,很抱歉,公司关闭了所有VPN的端口,没法使用jsfiddle,所以抱歉了.
2.问题描述:直接修改select组件绑定的value值,不能触发change事件,只有用手点击下拉框,选择后才能触发,看到2.0.0的更新日志,看到如何解释,请问为何要这样更改

非兼容性更新
综合
表单组件的 change 事件和 Pagination 的 current-change 事件现在仅响应用户交互

而且.其他的普通输入框以及日期选择框都能正常触发事件

### What is Expected?
正常触发change事件,或者告诉我如何new一个callback,因为使用watch来监听value的变化,调用校验rules的方法validatorField,需要有一个callback才能正常显示错误提示

### What is actually happening?
表单中的selectchange事件不能正常触发?为何同样在表单中,输入框和日期等其他组件能正常触发change事件,select组件不能?

**Comment by wacky6** [comment]
为什么这么改：参照原声select行为

**Comment by Leopoldthecoder** [comment]
> 输入框和日期等其他组件能正常触发change事件

我测试了一下，输入框和日期等其他组件在通过代码修改绑定值的情况下也是不会触发 change 事件的，与 Select 组件行为一致。

> 调用校验rules的方法validatorField,需要有一个callback才能正常显示错误提示

不需要传 `callback` 也可以显示错误信息，`callback` 只是你可以拿错误信息去做其他事情，不需要就不用传。例子：https://codepen.io/leopoldthecoder/pen/BYMxBX

**Comment by wlinshicong** [comment]
我看了你的例子,我们的校验规则写的跟你不一样,我们绑定了校验规则rules, 初始化时这样添加规则this.rules.push({validator: this.validatorField, trigger: this.triggerType});其中this.validatorField是一个自定义的检验方法,里面需要return callback(new Error("错误信息""));

**Comment by Leopoldthecoder** [comment]
请在 codepen 写个例子。

**Comment by wlinshicong** [comment]
https://codepen.io/leopoldthecoder/pen/BYMxBX?editors=1111 初始化的时候自动触发了规则,此时没有传入callback,会报错. 下拉框选择女,自动触发了规则,callback可能是底层自动生成的,此时不会报callback不是function的错误

**Comment by wlinshicong** [comment]
有没有办法让代码改变绑定值,change事件也能正常触发?

**Comment by Leopoldthecoder** [comment]
好像忘记保存了，例子和我贴出来的一样。

**Comment by wlinshicong** [comment]
https://codepen.io/anon/pen/mXvKYB?editors=1111抱歉,第一次用,再试下

**Comment by Leopoldthecoder** [comment]
这样的话直接调 FormItem 上的 `validate` 方法：https://codepen.io/leopoldthecoder/pen/GQzBxX

**Comment by wlinshicong** [comment]
十分感谢

**Comment by wlinshicong** [comment]
十分感谢你的帮助,还有一个小小的问题不知道算不算bug,如果我用watch绑定的值,然后在检测到绑定值变化时,主动去调用validate,这样子,如果是手动选择,会触发2次校验事件,系统触发默认的change事件一次,watch到value变化后,主动去调用validate 触发一次.为了解决这个问题,我把{validator: this.validatorField, trigger: "custom-change"})这个规则里的trigger的值由"custom-change""改为了changge.但是这样有一个bug,还是会触发两次,只有改为custom,或者其他不含change的才触发一次.所以我觉得这算是一个小bug吧

**Comment by Leopoldthecoder** [comment]
看了一下，代码里确实是通过 `indexOf` 来命中 `trigger` 的。正常情况下没有问题，暂时可能不会修改。具体到你这个例子，可以通过一个开关的方式来确保每次只触发一次校验。
