### ISSUE TITLE
[Bug Report] Performance Issues on Google Chrome

### ISSUE THREAD

**Issue by ar53n** [ElemeFE/element#9942]
### Element UI version
2.2.0

### OS/Browsers version
Windows 10

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/zg1pfqt7/](https://jsfiddle.net/zg1pfqt7/)

### Steps to reproduce
Click or hover for showing popovers

### What is Expected?
Create DOM nodes and deleted after hidden popovers. Not increasing event listeners

### What is actually happening?
I seen on performance monitor. Increased DOM Nodes and event listeners.

**Comment by syn-zeta** [comment]
Looks okay to me. Did you force collect garbage after you start and before you stop recording?

The drops in the middle are actually auto-GC, and the node and listener count do go back to their original number.

<img width="1440" alt="untitled" src="https://user-images.githubusercontent.com/26761352/36806048-b514784e-1c73-11e8-98aa-81d02938e457.png">

**Comment by ar53n** [comment]
In jsfiddle ita ok but on site GC not work. http://element.eleme.io

**Comment by syn-zeta** [comment]
Well, that's not really isolating the issue, then. Why file a bug against popovers? If you can determine which component is causing the leak on Element's home page, then it can be looked into, but for now this ticket is too broad, and I'd suggest either updating it to make it more specific, or closing it. A new one can be filed later on when the component causing the leak is isolated.

**Comment by ar53n** [comment]
@syn-zeta okey, lets close this issue, just i want check performance vue and element library. And see that. DOM Nodes and listeners increase.
