### ISSUE TITLE
[Bug Report] el-aside width isn't fixed

### ISSUE THREAD

**Issue by Edhilion** [ElemeFE/element#9944]
### Element UI version
2.2.0

### OS/Browsers version
Chrome Version 64.0.3282.140, Firefox 58.0.2

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/fngvessf/2/](https://jsfiddle.net/fngvessf/2/)

### Steps to reproduce
Simply run the jsfiddle

### What is Expected?
The second Aside element has the same size than the first one (400px).

### What is actually happening?
The second Aside element is resized.

**Comment by QingWei-Li** [comment]
Duplicate of #9865
