### ISSUE TITLE
[Bug Report] Table column not re render when expand

### ISSUE THREAD

**Issue by lkmadushan** [ElemeFE/element#9947]
### Element UI version
2.2.0

### OS/Browsers version
Chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/j7LL9hmf/28/](https://jsfiddle.net/j7LL9hmf/28/)

### Steps to reproduce
When you click on the expand icon on each row it will show same data.

This happens when you assign props to data model and while using expand-change. Do you guys have any idea what's going on here? 

### What is Expected?
Data should be display on the expanded area based on the row data

### What is actually happening?
When you click on the expand icon on a row it will show same data for each one

**Comment by wacky6** [comment]
https://jsfiddle.net/7e4jqefz/

**Comment by lkmadushan** [comment]
@wacky6 Thanks. `:key` was the problem

**Comment by zzzgit** [comment]
@wacky6 , why don't you add `key` in documentation?

**Comment by ShawshankLin** [comment]
@Leopoldthecoder
