### ISSUE TITLE
[Bug Report] el-input-number not listening 'input' event

### ISSUE THREAD

**Issue by jerryWinhua** [ElemeFE/element#9949]
Element UI version
2.1.0

OS/Browsers version
Vue version
2.5.13

Reproduction Link
https://jsfiddle.net/Lvhcwuo3/1/

Steps to reproduce
随便用键盘输几个数

What is Expected?
el-input-number收到input事件时触发handleInputChange，同时触发上一级input事件，即重现内的alert

What is actually happening?
没触发

**Comment by southnan0** [comment]
这个问题你是怎么解决的呢

**Comment by jerryWinhua** [comment]
computed 事件( 但我發現這不是我得議題，可能我不會操作不小心變成我自己的議題)
我的議題是當"+按鈕" 拖曳時會出現連續click事件
