### ISSUE TITLE
[Bug Report] [Bug Report] el-input-number is unusual in press button

### ISSUE THREAD

**Issue by jerryWinhua** [ElemeFE/element#9951]
### Element UI version
2.2.0

### OS/Browsers version
Chrome version 64.0.3282.186

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/Lvhcwuo3/1/](https://jsfiddle.net/Lvhcwuo3/1/)

### Steps to reproduce
Not continuou click the button.
Keep pressing the plus button and move out to the button.
stop press the mouse button
非持續click按鈕
持續按壓
游標移出按鈕區塊時 即可放開按鈕
![1519868485796](https://user-images.githubusercontent.com/34858369/36823948-c0792334-1d3a-11e8-9f91-3b88bd6aeb57.gif)

### What is Expected?
not continuou click button when the el-input-number Keep pressing the plus button
按鈕按壓時不會有連續click狀況

### What is actually happening?
 continuou click button

**Comment by Leopoldthecoder** [comment]
![untitled1](https://user-images.githubusercontent.com/10095631/36833746-6f8e1700-1d6b-11e8-9894-2ee0197794e5.gif)

未能复现

**Comment by wacky6** [comment]
@Leopoldthecoder 多操作几次看看。我这里不稳定复现，可能是偶数次操作才有？

**Comment by jerryWinhua** [comment]
@Leopoldthecoder  @wacky6  兩位請嘗試這種方法 選取後再移出

![1519898320795](https://user-images.githubusercontent.com/34858369/36838501-4afd3254-1d7a-11e8-828e-6e127e427527.gif)

**Comment by wacky6** [comment]
不是能很稳定的触发。
按住加号，往下移出组建范围（此时数字被选中）。然后重复这个动作。

![qq20180301-212751](https://user-images.githubusercontent.com/9319556/36839937-83be0678-1d97-11e8-9624-2ea0ace66c8e.gif)

感觉这个操作序列在实际中并不是那么容易出现？

**Comment by Leopoldthecoder** [comment]
加了个 `@dragstart.prevent`，应该是没问题了。

**Comment by jerryWinhua** [comment]
@Leopoldthecoder 感謝您，非常成功

thank a lot

**Comment by PanYaping** [comment]
> 加了个 `@dragstart.prevent`，应该是没问题了。

我这边加了在Safari浏览器下还是无效
