### ISSUE TITLE
[Feature Request] Inline datepicker

### ISSUE THREAD

**Issue by choirool** [ElemeFE/element#9958]
### Existing Component
Yes

### Component Name
Datepicker

### Description
Inline display datepicker like https://jqueryui.com/datepicker/#inline

**Comment by Leopoldthecoder** [comment]
Sorry, we have no plan to support this.

**Comment by wacky6** [comment]
You might be interested in https://github.com/ElemeFE/element/issues/9878

Though there is no clear timeline when such a major version will be released.
