### ISSUE TITLE
时间控件在IE下赋值有问题，赋值后不能展示

### ISSUE THREAD

**Issue by jiangjiang1** [ElemeFE/element#9965]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>template</title>

  
<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css"> 

  
 <script src="https://unpkg.com/vue/dist/vue.js"></script> 

  
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
</head>
<body>

    <div id="app">
        <span class="demonstration">带快捷选项</span><br>
        <el-date-picker
          v-model="value2"
          align="right"
          type="date"
          placeholder="选择日期"
          value-format="yyyy-MM-dd">
        </el-date-picker>

        <h1>{{value2}}</h1>
        <el-button @click='test'>ee</el-button>
    </div>

</body>
<script>

    vm = new Vue({
        el:'#app',
        data:{
         value2: ''
        },
        methods:{
        	test: function(){
        			vm.value2 = '2018-11-11';
        	}
            
        }
    });

</script>
</html>

在IE下，点击按钮，日期并没有显示在控件上；但在其他浏览器上是没有问题的。

**Comment by SunnyDesmond** [comment]
i have the same question~
