### ISSUE TITLE
 [Bug Report]When the scrollbar of el-table is too long, the first line tool-tip moves up  with the scroll bar rolls down.

### ISSUE THREAD

**Issue by qiyongping** [ElemeFE/element#9967]
### Element UI version
2.2.0

### OS/Browsers version
window7专业版/IE11

### Vue version
2.5.13

### Steps to reproduce
在window7专业版/IE11下，当el-table的数据比较多时，出现比较长的滚动条，鼠标悬停在第一行数据上，出现提示框，这时候向下滚动滚动条，提示框就会向上移动，直到浏览器窗口顶部。

这个问题在firefox上没有出现。

因为是内部项目，所以无法提供复现链接，对不住。

### What is Expected?
向下滚动滚动条时，tooltip框不随着滚动条的滚动而移动。

### What is actually happening?
tooltip框随着滚动条的滚动而移动。

**Comment by Leopoldthecoder** [comment]
Bug 基本上都是在内部项目里发现的，但是复现链接不是需要你把整个项目搬上来，而是最小化为一个可以重现问题的 demo。请准备这样一个 demo，然后开一个新的 issue。
