### ISSUE TITLE
webpack引入index.css时报加载错误

### ISSUE THREAD

**Issue by gugotim** [ElemeFE/element#997]
element-icons.eot?t=1472440741
已使用url-loader, file-loader，都不能修正

      {
        test: /\.(png|woff|woff2|eot|ttf|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url'
      }

**Comment by furybean** [comment]
参考 FAQ 第五条：https://github.com/ElemeFE/element/blob/master/FAQ.md
