### ISSUE TITLE
[Bug Report] el-table-column do not render boolean value

### ISSUE THREAD

**Issue by aztack** [ElemeFE/element#9977]
### Element UI version
2.2.0

### OS/Browsers version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/0gsuwn04/5/](https://jsfiddle.net/0gsuwn04/5/)

### Steps to reproduce
see above fiddle

### What is Expected?
boolean columns render as true/false.
table cell text should always render as `String(row.col)` if formatter not present

### What is actually happening?
table cell is empty

**Comment by aztack** [comment]
see https://github.com/ElemeFE/element/issues/5933
I'm just not convinced  that ` boolean value itself should not be rendered`

**Comment by wacky6** [comment]
I don't think putting a `true` / `false` in table cell is appropriate. They are also meaningless for non-English speakers.

Booleans should almost always be represented with something specific: 

* `on` / `off`
* `yes` / `no`
* `active` / `inactive`
* \+ other languages

**Comment by Leopoldthecoder** [comment]
This is because Vue's JSX does not render Booleans.
```js
<template>
  <compo></compo>
</template>

<script>
  export default {
    components: {
      compo: {
        render(h) {
          return <div>{ true }</div>
        }
      }
    }
  };
</script>
```

This will render an empty `<div>` on the page. Guess the Vue team has similar thoughts as above.

**Comment by JaroslavPrt** [comment]
@aztack

```
<el-table-column :formatter="cellValueRenderer" :prop="someProp"></el-table-column>

cellValueRenderer(row, column, cellValue) {
      const isBool = typeof this.data[column.property] === 'boolean';
      return !isBool ? cellValue : String(cellValue);
}
```

**Comment by jllodra** [comment]
I needed it, so here it is the workaround:

```
    <el-table-column :formatter="cellValueRenderer" ...></el-table-column>

    cellValueRenderer(row, column, cellValue, index) {
        let value = cellValue;
        if (typeof row[column.property] === 'boolean') {
            value = String(cellValue);
        }
        return value;
    }
```
