### ISSUE TITLE
[Bug Report] Lame focus outline on first and last tabs

### ISSUE THREAD

**Issue by ingria** [ElemeFE/element#9981]
![2018-03-03 01-46-48](https://user-images.githubusercontent.com/2178368/36925802-ae8ebf0c-1e85-11e8-9d56-c46ed900ebfd.png)

### Element UI version
2.2.1

### OS/Browsers version
Any

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/nsndf6zs/5/](https://jsfiddle.net/nsndf6zs/5/)

### Steps to reproduce
1. Click on the last or first tab
2. Unfocus window
3. Focus window again

### What is Expected?
Right and left padding to be equal

### What is actually happening?
Right or left padding is 0

**Comment by hezhongfeng** [comment]
I have the same bug.
Looking forward to close It.

**Comment by helloMr** [comment]
I have the same bug.
Looking forward to close It.
just change the css doesn't work
