### ISSUE TITLE
Can the height of the [Feature Request] dialog component automatically vary according to the height of the browser window?

### ISSUE THREAD

**Issue by fengyun2** [ElemeFE/element#9983]
### Existing Component
是

### Component Name
dialog

### Description
dialog组件的高度是否能够自动根据浏览器窗口的高度变化（包括弹框弹出时和触发浏览器窗口resize时）呢？

**Comment by Leopoldthecoder** [comment]
用 CSS 控制就好：https://jsfiddle.net/etkjxgec/2/
