### ISSUE TITLE
[Bug Report] el-date-picker: The behavior of date clearing trigger "change" event

### ISSUE THREAD

**Issue by w-rudolph** [ElemeFE/element#9984]
### Element UI version
2.2.1

### OS/Browsers version
win10 / chrome64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/po0sgku8/2/](https://jsfiddle.net/po0sgku8/2/)

### Steps to reproduce
* Step 1: clear the initial date, "change" event not triggered
* Step 2: select another date, then clear this date, "change" event triggered

### What is Expected?
The behaviors of 2 Steps for date clearing should be same

### What is actually happening?
Date clearing in Step 1 not triggered "change" event and in Step 2 triggered

**Comment by Leopoldthecoder** [comment]
Fixed in #9986
