### ISSUE TITLE
[Bug Report] el-date-picker: date format is not working when blur the input control

### ISSUE THREAD

**Issue by w-rudolph** [ElemeFE/element#9985]
### Element UI version
2.2.1

### OS/Browsers version
win 10 / chrome 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/po0sgku8/2/](https://jsfiddle.net/po0sgku8/2/)

### Steps to reproduce
Clear the initial date, and type "222222" and blur the input control, the value was not formatted a valid date

### What is Expected?
The value should be formatted a valid date or empty value if not a valid date

### What is actually happening?
Do nothing

**Comment by wacky6** [comment]
Fixed https://github.com/ElemeFE/element/pull/10749
