### ISSUE TITLE
[Bug Report]  Table scrollbar can't scroll when show-summary is true

### ISSUE THREAD

**Issue by dwt11** [ElemeFE/element#9987]
### Element UI version
2.2.0

### OS/Browsers version
WIN10企业版/360极速9.0 内核55.0

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/dwt11/3vbn5t9q/4/](https://jsfiddle.net/dwt11/3vbn5t9q/4/)

### Steps to reproduce
运行示例代码,在编号和名称(fixed)列拖动横向滚动条是不起作用的,必须拖动第三列姓名 ,才能横向滚动.

 移除表格的show-summary后,上面的问题不会出现

### What is Expected?
有没有show-summary合计列,横向滚动条都可以在任意位置,拖动,并起作用

### What is actually happening?
运行示例代码,在编号和名称(fixed)列拖动横向滚动条是不起作用的,必须拖动第三列姓名 ,才能横向滚动.

**Comment by elfman** [comment]
与#5415 是同一个问题，fixed的列遮盖在其它列的上层，当鼠标从fixed列开始拖动时，实际并未点击到滚动条上。
照现在fixed列的实现方式感觉修复不了这个bug

**Comment by Leopoldthecoder** [comment]
Duplicate of #5415

**Comment by gzh4455** [comment]
how can I solve this issue?  now I used the version is 2.5. the issue is still existing
