### ISSUE TITLE
How to set height 100% with el-table

### ISSUE THREAD

**Issue by martin-wiseweb** [ElemeFE/element#9989]
### Existing Component
Yes

### Component Name
el-table

### Description
It would be useful to have the ability to set a liquid height (like 100%) on a table. This way if data overflows, the header can be sticky as the user scrolls

**Comment by furybean** [comment]
@martin-wiseweb Just set height prop as style.height value, [Demo](https://jsfiddle.net/chsuax9m/) . Tips: This works only when style.height="value" works as expect.
