### ISSUE TITLE
[Bug Report] dynamically generated el-menu, style display errors when the menu is contracted

### ISSUE THREAD

**Issue by K-walker** [ElemeFE/element#9995]
### Element UI version
2.1.0

### OS/Browsers version
win7 64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/vL8eh0yp/13/](https://jsfiddle.net/vL8eh0yp/13/)

### Steps to reproduce
点击收起按钮

### What is Expected?
收缩时菜单上的文字能够隐藏

### What is actually happening?
收缩时菜单上的文字没有隐藏

官方给出的解释是：[#9887](https://github.com/ElemeFE/element/issues/9887)

但是我换成其他任何标签去包裹el-menu-item都无法解决这个问题,所以说应该不是这个哥们说的div的问题，如果按照他所说的是div的问题，那么菜单第一项文字“首页”，却真实隐藏了，因此我个人觉得这是一个bug，希望能重视一下，如果我弄错了，或者哪个使用上有问题，那么请见谅。也希望官方能指出我的问题所在，谢谢了

**Comment by Leopoldthecoder** [comment]
我的意思是移除 `<div>` 标签，并不是把它换成其他标签。原因是隐藏菜单文字的 CSS 使用了 `>` 选择器。如果必须要在 `ul` 和 `li` 之间包一层标签，可以自行添加 CSS：https://jsfiddle.net/vL8eh0yp/45/

**Comment by K-walker** [comment]
@Leopoldthecoder 不好意思，谢谢了。
